### ISSUE TITLE
[Data] 10-10EZR: Determine how TERA expansion announcement is impacting EZR online

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77831]
As Alex, I would like to understand how the PACT Act expansion announcement is impacting online behaviors surrounding the 10-10EZR so that I can understand when we can rollout EZR to 100% without confusing Veterans who are coming to the EZR expecting to be able to enter TERA information.

**AS Note: below are some suggestions for things to look at, but please feel free to improvise and use any ideas you have, you're the expert.**
- [x] Look at Google search for EZR and TERA, or updating information and TERA
- [x] Look for site searches for EZR/TERA/updating information
- [x] Look at page views for updating information/EZR
- [x] Look at any other information that might determine how frequently users are attempting to update TERA online
- [x] **Success: We have an understanding of what the expectation for updating TERA information online is, and we can make a decision on when to go to 100% for EZR without confusing Veterans.**

**Comment by luis-simauchi** [comment]
google search console is not enabled for the GA property of VA.GOV, so I am going to have to use a crude measure of Google Trends

**Comment by luis-simauchi** [comment]
Google Trend for search query: TERA VA
https://trends.google.com/trends/explore?geo=US&q=tera%20va

Google Trend for search query:  healthcare VA EZR
https://trends.google.com/trends/explore?cat=19&geo=US&q=healthcare%20VA%20EZR

**Comment by luis-simauchi** [comment]
updated Google trends analyst:

https://trends.google.com/trends/explore?cat=19&geo=US&q=toxic%20exposure,radiation%20exposure,hazards%20exposure,Agent%20Orange%20exposure,risk%20activity&hl=en-US

**Comment by luis-simauchi** [comment]
no significant change in search terms used by sessions that made it to a EZR related pages during March MTD
(comparison is period over period: Mar 1 - Mar 11  vs.  Feb 19 - Feb 29) 

view of GA search terms here:
https://analytics.google.com/analytics/web/?pli=1#/report/content-site-search-search-terms/a50123418w177519031p176188361/_u.date00=20240301&_u.date01=20240311&_u.date10=20240219&_u.date11=20240229&_.useg=userDTydDpqxRPallLMr9Gwf6w&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100&explorer-table.rowStart=0/

**Comment by luis-simauchi** [comment]
Using common search terms associated to the TERA expansion, there was a decline in search volume from sessions that made it to a destination page.
(comparison is period over period: Feb 26 - Mar 11 vs. Feb 12 - Feb 25)

If anything it was interesting that the peak of TERA related searches occurred Feb 20th, prior to TERA questions released onsite

**Comment by luis-simauchi** [comment]
Pageview traffic to EZR pages: 42,778
Unique Pageviews: 30,469
Avg. Time on Page: 00:00:49
Avg for View: 00:01:02 (-20.91%)
Entrances:  1,074

**Comment by luis-simauchi** [comment]
**raw stats from HCA tera question pages from traffic channels:**
https://analytics.google.com/analytics/web/?pli=1#/report/acquisition-channels/a50123418w177519031p176188361/_u.date00=20240226&_u.date01=20240311&_u.date10=20240211&_u.date11=20240225&_.useg=userW2oi5HrbSnKwauMFId9sIA/

**Comment by luis-simauchi** [comment]
for PO sync:
https://analytics.google.com/analytics/web/?pli=1#/report/acquisition-channels/a50123418w177519031p176188361/_u.date00=20240305&_u.date01=20240311&_u.date10=20240227&_u.date11=20240304&_.useg=userW2oi5HrbSnKwauMFId9sIA/
