### ISSUE TITLE
Design: treatment start/end date is null

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#77849]
Based off research completed in this [initial ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/69020)

**QUESTIONS:**

As is, neither date field (month/year) are required. Would there be any issues with removing the current validation that requires the treatment start date be after the start of the earliest service period, other than the fact that the condition’s treatment date might not therefore logically be service connected?

Or would it be better to fix the logic so that only the year, or month and year (not month only), are validated against the earliest service period? For example, if the earliest service period was May 1, 2000. If only the year was entered, it would have to be 2000 or later. If a month and year were selected/entered, it would have to be May 2000 or later. And, if only a month was entered, it wouldn’t be validated (e.g., selecting and saving only March would not result in an error).

**N.B.** I should mention that making either of the above changes is **not** going to eliminate such warnings from being returned as part of the error_message response for a submission attempt that fails due to an unrelated `ERROR`. endDateIsNull will always appear as `WARN` because there is no treatment end date field as part of the VA medical records section. We can choose to ignore these 2 "error" types because they aren't of a severity level that will result in a validation error. But taking acton on either or both of the above questions might result in some overall UX improvements.

**Comment by sortizsh** [comment]
@juliepedtke  let's talk about this

**Comment by sortizsh** [comment]
HCD to draft initial messaging around what to say to the Veteran, so that it can be implemented on the FE.

**Comment by sortizsh** [comment]
We should get CAIA input but should not need a full collab cycle input. Shannon should approve.

**Comment by juliepedtke** [comment]
My thinking is it would be best to fix the logic so that only the year, or month and year (not month only), are validated against the earliest service period. We want to reinforce that it must be a service-connected condition. Since it's an optional field, I don't see a major issue with no validation if only a month is entered. 

The existing error copy looks fine for this path - "Your first treatment date needs to be after the start of your earliest service period." 

Is there some nuance to the multiple service periods that we need design input on, or is that just a matter of fixing the bugginess?

**Comment by juliepedtke** [comment]
If it's just a question of effort vs impact, we might want to get Emily's take on the amount of engineering effort required. The only risk to removing the validation entirely is that the Veteran might be more likely to enter a condition that is not service connected - but there's lots of other instructional text throughout the form about this, so if it's a major lift to fix the logic then maybe we could remove as an immediate fix and put it in the backlog.

**Comment by nnicholas7** [comment]
Currently, there is no need for design efforts. The current error message existing copy "Your first treatment date needs to be after the start of your earliest service period." can be used when only the month is written and when the year is out of the service period. Scott will continue to look to see where all the validations are happening for this question.

**Comment by freeheeling** [comment]
Having conferred with Nichole, the plan is to remedy the logic such that...
- only the year, or month and year (not month only), are validated against the earliest service period 
- if year is before or if only a month is entered, then the error message copy should be displayed

**Comment by nnicholas7** [comment]
No design work is needed for this ticket. Next step: Close this ticket for this sprint.

**Comment by freeheeling** [comment]
@nnicholas7 @juliepedtke In the case where only a month is input, it would be an easy update to change the copy from "Your first treatment date needs to be after the start of your earliest service period." to something that is more explanatory as to what the actual error is or what the user must do. I would just need to know what that message should be.

**Comment by juliepedtke** [comment]
My proposal was to not have validation if only a month is entered, since it's an optional field to begin with. Alternatively, we could have a message say "Enter a month and year" if we want it to be impossible to enter only a month. But not sure if the juice is worth the squeeze since it's all optional.

**Comment by juliepedtke** [comment]
I think Nichole misspoke in the earlier comment - either way we go, the existing error should NOT appear if only a month is entered.

**Comment by freeheeling** [comment]
Can accommodate either option – no error or "Enter a month and year" – depending on desired outcome. Apologies for the misunderstanding.

**Comment by juliepedtke** [comment]
No worries! If it's an easy add, let's go with "Enter a month and year." Thanks!
