### ISSUE TITLE
[Pension Module] Refactor pension pdf, sidekiq, shared code

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#77843]
Not to leave any pieces hanging in app/lib when unnecessary, refactor any shared code from pension to be contained in existing `app` and/or `lib`, and move pdf generation and sidekiq processes to pension module

Tasks:
- [ ] Refactor pdf generation to module
- [ ] Refactor sidekiq processes to module (if necessary)
- [ ] Refactor shared code to app/lib

Acceptance:
- [ ] ALL tests function correctly
- [ ] PDF generation functions

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77843?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by wayne-weibel** [comment]
This ticket may be split into several (if at all) since this will impact other teams.

**Comment by wayne-weibel** [comment]
closing as duplicate of https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/89506
and sidekiq job done as part of initial module ticket
