### ISSUE TITLE
Content model: VAMC "Register for care" page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7785]
## Problem Statement
How might we change the structure of [Register for care content](https://www.va.gov/pittsburgh-health-care/register-for-care/) so that
- some content can be reusable
- national/regional content cannot be edited locally
- the risk of introducing errors is reduced
- the editorial experience is enhanced and efficient

## OKR
Decrease the amount of national/regional content which is locally editable 

## Definition of done

- [ ] Content analysis 
- [ ] Content structure changes
- [ ] Front end mapped to new data structure
- [ ] Pages render as expected 
- [ ] Editorial experience review with CMS
- [ ] Content model review with CMS
- [ ] Feedback session with VAMC upgrade team 
- [ ] Migration plan
- [ ] Testing plan

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*
 
 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1594821112000/9932af464534c2676a2656992de3cf809cfad97b

**Comment by mmiddaugh** [comment]
Replaced by [Content model for facility nonclinical services to support Top Tasks #6341 (CMS epic)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6341)
