### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va.gov-team#77853]
### Name

Lauren Russell

### Email

lauren.russell@adhocteam.us

### Role

Designer

### Team

Flagship Mobile Team

### Additional Notes

I am requesting access to the VA workspace so that I can view files within the workspace. Please reach out to Ryan Thurlwell if you have any questions regarding this access. Thank you!

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to lauren.russell@adhocteam.us.
