### ISSUE TITLE
Poll LH for 526 submission status resubmit to benefits intake API

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#77851]
- Check the LH status of 526 backup submissions
- We already know a number of old submission have failed and should NOT Be resubmitted programatically to BI API. These are captured in #75354
- This ticket reflects identifying those recent failures, fixing the root cause, and resubmitting them. 
- This should only include LH status failures from the last month or so (Feb 2024). If more failures are identified, submit only the last month and/or notify me first.

**Comment by emilytheis** [comment]
This should only include LH status failures from the last month or so (Feb 2024). If more failures are identified, submit only the last month and/or notify me first.

**Comment by SamStuckey** [comment]
As of March 20th, 2024 there are no new failures in the Lighthouse Benefits Intake API.  The outstanding failures are from the following month / years:
"04-2023", "02-2023", "03-2023", "05-2023", "09-2023"

Closing this as there is no further action to take
