### ISSUE TITLE
Update USiP configuration with per-environment client IDs

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#77856]
Updates required in at least two spots:
- [src/platform/user/authentication/config/staging.config.js](https://github.com/department-of-veterans-affairs/vets-website/blob/d3e9826e84e536f497997fad92043bd8e9343bb9/src/platform/user/authentication/config/staging.config.js#L104-L109)
- [src/platform/utilities/oauth/constants.js](https://github.com/department-of-veterans-affairs/vets-website/blob/d3e9826e84e536f497997fad92043bd8e9343bb9/src/platform/utilities/oauth/constants.js#L32-L34)

**Comment by gabezurita** [comment]
Done as a part of [this issue](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/77862), but need to confirm.
