### ISSUE TITLE
Update SiS ClientConfig with per-environment client IDs

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#77862]
## Description
See [this commit](https://github.com/department-of-veterans-affairs/vets-website/commit/1ba7d153d41a0b0731369aca534d2b63acbdae90) for where client_ids need to be updated on a per environment config.

The ARP staging client_id is `ce6db4d7974daf061dccdd21ba9add14` and is being used [here](https://github.com/department-of-veterans-affairs/vets-website/commit/1ba7d153d41a0b0731369aca534d2b63acbdae90). It seems to be overriding the [arpWebOauthOptions constant value](https://github.com/department-of-veterans-affairs/vets-website/commit/1ba7d153d41a0b0731369aca534d2b63acbdae90), so we may want to refactor this. [This PR thread](https://github.com/department-of-veterans-affairs/vets-website/pull/28225#discussion_r1509590642) has more details.

## AC
- [x] ARP SiS ClientConfig `CLIENT_IDS` vary by environment
- [x] It is possible to log in as an ARP user in staging (possibly split to separate issue if the clientconfig does not fix this)

**Comment by a6marinos** [comment]
This ticket may require help from the Identity team, so keep scheduling in mind when it comes to this sprint/capacity.

**Comment by gabezurita** [comment]
Slack Canvas describing how it was figured out what needed to be updated to get this working in a staging environment:
https://dsva.slack.com/docs/T03FECE8V/F07CXK78K08

Ultimately, the below change was the only needed one:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2968/files

**Comment by gabezurita** [comment]
Additional, relevant PR: https://github.com/department-of-veterans-affairs/vets-website/pull/30878
