### ISSUE TITLE
Access for Julian Severino

### ISSUE THREAD

**Issue by jsev-io** [department-of-veterans-affairs/va.gov-team#7786]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Julian Severino
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSP-Operations
   > Role: DevOps Engineer
   > Company: Oddball, Inc.

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClxCEBTxsmBfmdHwWe5hmEy4T400dBmqGzNUg/8qbarCACJWeQkeARGR4eHYsK2y7ej7rwlq3aEJTCZJAivkFEAf0zOrTuirWdUl+Vo0BQD6zhH6OOaNPso34F10otJkbti/yVlkgEAZE33LrVecwVCPBjs+Q7gq7F73DkZxuZ0Sc+XGzfOU/O0wF3d7DNL6/a1A3WpoAM5JFUm5+xONezO1+Ecs6LJ4PD5Pk5fw/PnZkYMQ/JyRxD5SiB+hV1Rcj3wbArtasvJWa1SRW5DowTX1ZGtNC5oKTBLEOeNTWToA4Mdvj/4B1ND3PicolRVLBEEEW27L+q8Tazd9UzxD1Q9aAjawzpkZ55rT5T4+V29Xzu5dH93fSSQJOsSZ5WQHTQW5eSjVdFyCeZyXwotmbj8qlXvnN2IeZorERW3s3Xk9hwHBrxw1chjDewY1i+oyJp9qwr6YkRlLXQk5TPv8GV55L2y731C7030bZHonDLymxN1zpxOf1lA88b3nx4cGk= User@RunaiX
```

- [Grant AWS Console access?]
  > YES / NO
YES

  >  Please give a brief description for why you are requesting AWS access.
DevOps Engineer - Require access for all work tasks.

**Comment by jsev-io** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
I can walk you through the process for granting this access when time allows today if you'd like.

**Comment by jbritt1** [comment]
COR: @Jeff-Hayter 
User: Julian Severino

**Comment by ricetj** [comment]
@Jeff-Hayter has approved Julian for AWS access

**Comment by jbritt1** [comment]
Credentials / first time login credentials passed via Slack DM.

**Comment by Jeff-Hayter** [comment]
Approved for AWS Admin access per conversation with Dror and Kevin.
