### ISSUE TITLE
IPP - Design for In-Person appointment changes (Veteran Intake)

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#77881]
**Problem**
How might we allow a Veteran to cancel or reschedule an appointment from the Veteran Intake application?

**Questions**
- at what point should we introduce this?
- should this be integrated into the confirmation email - option to reschedule?
- should they keep their same case number? Or does it make more sense to just "start over" with a new one? If we're starting over, then should we just tell the Veteran that if they need to change facilities, or if they cannot make their appointment within 10 days, then they can go back to the application and select a new site (essentially repeating the process)? What does 'reschedule' mean in a walk-in situation? What if we changed our verbiage, removed phrasing around "appointment," and just said, "your Case number will be active for 10 days," or something like that? "There is no need to cancel if you can't visit your VA facility within 10 days. If your case number expires and you need to create a new one, or if you would like to change your VA facility, you may do so at any time by visiting www.va.gov-in-person-proofing-intake (or whatever the url). 

**User Story**
As a Veteran, I need to be able to cancel or reschedule a walk-in appointment in case I cannot make it during the 10-day window.

Design user flow first - consider possible entry points to a reschedule option.

AC

- [ Explore current flow Figma for internal understanding of potential design solutions] 
- [ Answer questions listed above using current flow as the supporting document]
- [ Explore where to leave content, i.e what screens are going to effected by this change]
- [ Complete and polish updated flow in Figma before started on mockups]

**Comment by JKG199** [comment]
Ideation of revised flow and screens [here ](https://www.figma.com/file/5XqRVr2xcXlhjqaGTJpwar/IPP-Iteration-Based-User-Flow?type=whiteboard&node-id=0%3A1&t=3rGiRJgZt8PhjZWu-1)

**Comment by JKG199** [comment]
Reviewing content with Carl and will tag the appropriate folks when content is final and the mockup is ready for review. Should be good to go for demo purposes.

**Comment by JKG199** [comment]
Content has been reviewed, @SophiaPhilipMO and @skirkman16 feel free to review mockups [here](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2990%3A39158&mode=design&t=zAfVEDhuuesbtN8e-1).

**Comment by JKG199** [comment]
Veteran Facing screens updated for: 
1. Appointment change content 
2. 'What to Bring' screen content and order 
3. 'Confirmation' screen content and order 
4. 'Email' screen content and order 

All changes can be viewed in the Figma file mentioned above.
