### ISSUE TITLE
AWS access for Nichelous Herndon (Access Renewal)

### ISSUE THREAD

**Issue by nichelous-herndon** [department-of-veterans-affairs/va.gov-team#77884]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Nichelous Herndon

### Your Email

nichelous.herndon@thoughtworks.com

### Team, Role, and Company of the target individual

VA Chatbot, Software Engineer Consultant, Thoughtworks

### Product Manager (PM) name and email

Alina Murphy amurphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais luciana.morais@va.gov

### Desired AWS Access

I need read/write access to dsva-vagov/va-virtual-agent space in AWS parameter store.

### Access Expiration

January 01, 2025

### E-QIP Transmittal Confirmation

From previous AWS Access Request Ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/62888):

"Contacted Lovejoy and confirmed E-QIP Transmission on 07/17/2023/"

### Additional Notes

I need read/write access to dsva-vagov/va-virtual-agent space in AWS parameter store.
Previously had access for 6 months. It's about to expire and I need an extension.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
User in Atlas
Previous documentation and approval here

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/62888

@department-of-veterans-affairs/operations-aws-approvers - This is a renewal.

**Comment by nichelous-herndon** [comment]
Also from the previous Access Request Ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/62888)
@Kshitiz-devops "AWS access created. Password sent in slack"

**Comment by nichelous-herndon** [comment]
@hgbarreto I accidentally deleted my previous message. 
I found the slack message with this info:
Console sign-in URL: https://dsvagovcloud.signin.amazonaws-us-gov.com/console
User name: Nichelous.Herndon
The password I forgot and the temp password sent no longer works. I think I need a reset.

**Comment by JonathanKamensDVA** [comment]
Ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/62888

Access approved.

**Comment by Mandalorian-Oddball** [comment]
User in Atlas.
