### ISSUE TITLE
[UX] 10-10EZR TERA: Modify TERA Designs to fit MVP constraints

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77886]
As a Veteran I would like to be able to answer the TERA questions online so that I can tell the VA what Toxic Exposure I have experienced and get the healthcare I have earned. 

- [x] Update designs to display TERA questions for MVP
- [x] Update the workflow accordingly so that we're displaying TERA questions in their own section or added to an existing section (team can decide)
- [x] Demo to PM and Devs to walk through layout and workflow
- [x] **Success: We have designs for TERA questions that accurately capture what we're going to release on April 10th**

**Comment by katelyncai** [comment]
**Updates**

- [Designs](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=1405%3A60260&mode=design&t=lKWPSdIkxQgtswTc-1) for MVP are now updated
- TERA questions will live in a new section, **Military Service**, now following the Veteran Information section. This aligns with EZ and provides a future-friendly spot for adding on TERA enhancements, post-MPV
- With @mkerns1 out today and me out Friday, plan to demo the designs on Monday 3/18

**Comment by katelyncai** [comment]
Demoed yesterday to PMs and engineers. Will work with Aliyah for content.
