### ISSUE TITLE
Identity SDK - Define Login component

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#77904]
Description:

Create several components that comprise of the `Login` component. Some, but not all, will be created from the identity sdk library, and others will be strictly project based in `vets-website`

- [ ] Create an interface to define the different Login components
- [ ] Create a prop for `LoginInfo` to accept a React component inline to avoid importing `SignatureForm` directly
- [ ] Create an interface to define the `onClick` handlers

**Comment by parkerbees** [comment]
Moved to Jira, closing
