### ISSUE TITLE
Update PDF Nomenclature to UUID_VHA_10_10D_*.pdf

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#77916]
As a PEGA user analyzing pdfs in the AWS S3 bucket, I want to identify the pdfs by a UUID

AC: Updated PDFs to be UUID_VHA_10_10D_*.pdf

**Comment by cloudmagic80** [comment]
https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/75508

duplicate of this ticket. 

Github link: https://github.com/department-of-veterans-affairs/vets-api/pull/15866

**Comment by baltes** [comment]
@cloudmagic80 @balexandr I can't approve this. Please rework and use an arbitrary identifier in the naming convention so that we're not using PII.

**Comment by baltes** [comment]
Moving this back to in progress while we get it resolved.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15885

Completed.

**Comment by balexandr** [comment]
It's worth noting in here that this UUID being used will in no way be able to relate back to our system but it's a good placeholder until we can figure that out.

**Comment by baltes** [comment]
@balexandr @cloudmagic80 Could one of you attach an example file to this ticket?

**Comment by balexandr** [comment]
@cloudmagic80 I tried to download it from Postman to no avail. I think you have the actual bucket login setup better than me so I'll let you attach it.

**Comment by baltes** [comment]
@cloudmagic80 Can you attach a sample file here?

**Comment by cloudmagic80** [comment]
[d398dc13-4e63-493e-90c0-3c20da767108_vha_10_10d-tmp1.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHpyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1934fbdca82ea77722cf72d862db4fddb63b6ad5/d398dc13-4e63-493e-90c0-3c20da767108_vha_10_10d-tmp1.pdf)
