### ISSUE TITLE
Embed Metadata in S3 Call

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#77914]
As a PEGA user, I would like to extract metadata directly from pdfs instead of having a separate file.

Revert work done in https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74703 per convo with Premal

AC: 
- When viewing the PDF, I can see the metadata like Author, Title, Subject, Keywords and other fields.
- The metadata includes the form contents
- The metadata is not in a standalone file
- 

Example from Denise:
```
Here is a JavaScript example.
  s3.putObject({
        Bucket: 'uploadmetatest',
       Key: 'vijaykishan.txt',
        Metadata: {OrgID: 'TEKKIHUT', PROFILE: 'HD'},
        Body: base64data,
       ACL: 'public-read'
    }, function (resp) {
        console.log('Successfully uploaded package.');
    });
```

**Comment by balexandr** [comment]
@marywang2 Does this ticket remove the changes that were made in https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74703 ?

**Comment by baltes** [comment]
The description and AC for this story reflect the desired state--implementation should embed metadata that includes the form contents in the PDF.

**Comment by balexandr** [comment]
@baltes I recently discovered that PDFs follow a specific metadata format:
```
The PDF metadata properties defined by the PDF specification (ISO 32000-1:2008) include:

Title: The title of the document.
Author: The name of the person or entity who created the document.
Subject: A short description or summary of the document's content.
Keywords: Keywords or phrases that describe the document, separated by commas.
Creator: The software application or tool used to create the document.
Producer: The software application or tool used to convert the document to PDF format.
CreationDate: The date and time when the document was created, in ISO 8601 format.
ModDate: The date and time when the document was last modified, in ISO 8601 format.
```
I'm thinking I can squeeze the metadata in the Keywords field as seen below. 
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c0d05f5d88d97269a509fd60b35beb20e8a5c80/Screenshot%202024-03-14%20at%203.23.54%20PM.png" alt="Screenshot 2024-03-14 at 3.23.54 PM.png" />

**Comment by balexandr** [comment]
Waiting to hear back from Cindy on how we should proceed with this.

**Comment by balexandr** [comment]
Waiting for platform review
