### ISSUE TITLE
Remove current job title field and child and spouse suffix fields

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#77924]
The web form contains **current** job title, child suffix  and spouse suffix fields, while the PDF does not. 
Similarly, there is a job title field that does not make it to the PDF.
To reduce burden for Veterans, lets not have them waste time entering data that doesn't get transmitted via the PDF.

## To do
- Take out child suffix field from web form
- Take out spouse suffix field from web form
- Remove the job title field in Current employment section (above) as it doesn't map to a field in the PDF. 
- Handle in-progress forms with this change (schema migrations)
- Update migration.js as required
- Update schema as required.

### Notes
Slack thread https://dsva.slack.com/archives/C05MS96P6P2/p1709767816036609?thread_ts=1706312629.113879&cid=C05MS96P6P2

## AC
- Make sure that this change does not cause any issues with capturing current or past employment, child name and spouse name
- With the removing these suffix fields from web form, make sure info from each section makes it across to PDF accurately
- This change does not cause submission issues in production

## Screenshots
https://staging.va.gov/pension/application/527EZ/employment/previous/history
<img width="550" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcabab796ceb1318aa93fd7bd443880ebd4b3707/image.png" alt="image.png" />

https://staging.va.gov/pension/application/527EZ/household/marriages/0
https://staging.va.gov/pension/application/527EZ/household/marriages/**[X times]**
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--641304edd8e46095d1def56fd679b346b86fd3c9/Screenshot%202024-03-22%20at%208.49.56%E2%80%AFAM.png" alt="Screenshot 2024-03-22 at 8.49.56 AM.png" />

https://staging.va.gov/pension/application/527EZ/household/dependents/add
<img width="447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c71e72d3e4ea155cd61c554354138909f50d67c/screencapture-staging-va-gov-pension-application-527EZ-household-dependents-add-2024-03-22-08_53_44.png" alt="screencapture-staging-va-gov-pension-application-527EZ-household-dependents-add-2024-03-22-08_53_44.png" />

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77924?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by ToddWebDev** [comment]
I see both of these fields in the PDF in 'SECTION V: EMPLOYMENT HISTORY' for a Veteran who is entering their employment history with no instructions to skip 5F: 'Job title'.

>If a Veteran chooses 'Yes'  to 'Are you currrently employed?", they are not instructed to skip any fields (While 'No' instructs to skip 5b and 5c)

It can be derived from the past tense terminology that a Veteran who enters 'Yes' can skip questions 5D - 5G, however it does not specifically instruct to do so.
 
Suffice to say the PDF form is ambiguous and difficult to translate into a human readable form.

<img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm4rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae01ec9295eaf016857c22c2dd3fa84140970ad7/Screenshot%202024-03-21%20at%2011.46.38%E2%80%AFAM.png" alt="Screenshot 2024-03-21 at 11.46.38 AM.png" />

**Comment by buddhima-coforma** [comment]
Good points, Todd.
<img width="567" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/143657406/8692407e-f389-4154-aed2-d26d73b740b6">
On the next screen there's past employment questions, need to check that these map to 5D through 5G?

Which can help us validate this requirement.
