### ISSUE TITLE
V3 Breadcrumb Formatting Issue

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#77920]
## Summary
The breadcrumb appears with a trailing arrow and the last item is not bolded. This issue occurs on the appointments home page when navigating from the static landing page.

The breadcrumb works as expected When navigating from the MHV on VA.gov home page, or hitting the appointments home page URL directly.

It's unknown whether it occurs when navigating from other URLs. It does not appear to affect the breadcrumb on other pages.

* Appointments home page: `https://staging.va.gov/health-care/schedule-view-va-appointments/appointments`
* Static landing page: `https://staging.va.gov/health-care/schedule-view-va-appointments/`
* MHV on VA.gov home page: https://staging.va.gov/my-health/

## Specs
- Device: MacBook Pro
- Browser: Chrome

## Steps to Reproduce
**Test User:** 

1. Login to VA.gov 
2. MHV on VA.gov home page: https://staging.va.gov/my-health/
2. Click the link to Upcoming appointments
3. The breadcrumb appears as expected
4. Return the the MHV on VA.gov home page
5. Click the link to Schedule and Manage appointments
6. Click the button to Go to appointments
7. The breadcrumb appears with a trailing arrow, and the last item isn't bolded.

### Actual Result
When navigating from the static landing page (Schedule and manage appointments, the breadcrumb appears with a trailing arrow, and the last item isn't bolded.)

<img width="692" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dba39bb4c4213614d33b35b702a4352ce386f76/image.png" alt="image.png" />

### Desired Result
The breadcrumb works as expected no matter the URL the user originates from.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by outerpress** [comment]
@jenniemc I just noticed another scenario where the formatting issue shows up:
- Log in as Judy
- Click "Start scheduling"
- From the type of care page, click the "Appointments" link in the breadcrumb
- Click okay to leave the page
- On the appointments home page, review the breadcrumb

**Comment by ldelacosta** [comment]
@outerpress - this ticket is ready to be validated.

**Comment by outerpress** [comment]
@jenniemc @ldelacosta confirming this is fixed for both scenarios. Thank you!

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
