### ISSUE TITLE
Flipper UI access for Drew Connelly

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#77933]
### Your Name

Drew Connelly

### Your GitHub handle (Flipper UI access is managed through GitHub)

@drewconnelly

### Team, Role, and Company of the target individual

Unified Appointment Experience, Backend Developer, Apothesource

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
confirmed in Atlas

E-QIP [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75140)

**Comment by bdech** [comment]
@drewconnelly You've been granted access to `lower` environments.

**Comment by drewconnelly** [comment]
Tested and confirmed access.  Thanks for your help @bdech!

**Comment by bdech** [comment]
You're welcome
