### ISSUE TITLE
Update vets-website Feature Toggle Guide docs to reflect recent chages

### ISSUE THREAD

**Issue by DanielMiller-agile6** [department-of-veterans-affairs/va.gov-team#77938]
### Description
Code in vets-website effecting Feature Flags is being updated and will require a couple of changes to platform documentation.

Once changes are merged to master, step 5 in the platform documentation's Feature Toggles Guide should read:

> **5. Add the feature toggle name to vets-website by updating featureFlagNames.json**
> ```json
> {
>  "showYourFeatureName": "app_name_then_your_feature_name"
> }
> ```

### Relevant URLs
Platform feature toggles documentation page & section
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-5.Addthefeaturetogglenametovets-websitebyupdatingfeatureFlagNames.js

PR with relevant code changes:
https://github.com/department-of-veterans-affairs/vets-website/pull/27459

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team (MyVa AuthExp)

**Comment by jknipes** [comment]
Hi @DanielMiller-agile6 thank you for flagging this. We'll take a look, and review with some engineers to determine the best course of action for this page, and will work to get any updates reflected on the website.
We will provide further updates in this ticket. Please feel free to reach out if there are any questions.

**Comment by jknipes** [comment]
Related [work ticket 77942](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/77942) added to Backlog

**Comment by jknipes** [comment]
@DanielMiller-agile6 it looks like the page may have already been updated. 
Can you please look at [this section](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-5.Addthefeaturetogglenametovets-websitebyupdatingfeatureFlagNames.js) and advise?

**Comment by DanielMiller-agile6** [comment]
I'm still seeing the docs for the older implementation:
![Screenshot 2024-04-29 at 9 55 58 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54035677/73e382d7-df86-451e-aee3-9638add0a45f)

The previous change converted the `.js` file to a `.json` file (which is then imported by`.js` and`.cjs` modules) in order resolve an issue with our cypress integration test runner.  See above ticket description again more details on changes.  Doc changes are a bit subtle for sure, so feel free to reach out here with any questions and I'm happy to help try and clarify anything :)

**Comment by jknipes** [comment]
Thanks @DanielMiller-agile6 , once we make the changes, we will request a review from a SME. Could you please advise whether this would belong to FE, BE or DevOps?

**Comment by DanielMiller-agile6** [comment]
doh, must have missed notification from here. copying from slack convo:

> thanks :slightly_smiling_face: likely FE issue, but a double check from devops could help too :thinking_face: 
Curt Bonade or #platform-cop-frontend would be the person or channel I'd check with, and I can help review too if it helps :+1:

**Comment by taylojill** [comment]
Page updated as requested, see screenshot below. Page date stamped and checked for launch-blocking issues. Ready for publishing (May 16, 2024).

cc @jknipes @DanielMiller-agile6 @CBonade 

![2024-05-15_15-12-17](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/c8be8301-ea67-4a9f-bf2e-d8acbf531605)
