### ISSUE TITLE
[Test Results] T1882: Navigation to MHV did not yield expected result

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#7793]
## What happened?
I tested [T1882](https://dsvavsp.testrail.io/index.php?/tests/view/1882) with new DS Logon credentials of [ruben.moreno](https://docs.google.com/document/d/1Qro8ry9xDp9DAig-jsiDV-q86IgSIDOxxjvNkp2DMNY/edit#). Click of "My Health" did open MHV successfully, but the user was in the signed-out state. 

## Specs:
- Device: MacBook
- Browser: Chrome on CAG 
- Test User: Bridget 

## Steps to Reproduce
See test result from 4/9: https://dsvavsp.testrail.io/index.php?/tests/view/1882

**Comment by marriej** [comment]
Tested again and was asked to complete account registration. Is this an ok result? @patrickvinograd @ericbuckley @hinzed1127

**Comment by marriej** [comment]
judy.morrison@id.me
