### ISSUE TITLE
[Post-MVP] Investigate changing Yellow Ribbon content

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7794]
# Description

Janice suggested that we make the following change:

`the Yellow Ribbon program can help pay for higher out-of-state, private school, or graduate school tuition` should be changed to `the Yellow Ribbon program can help pay for higher education tuition.`

Similar language is also in the intro text on the [Yellow Ribbon benefit content page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/) and should probably be changed there if we decide to move forward with this. 

## Related Issues
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7806

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7805

## Acceptance Criteria

- [ ] Determine if we should make the above content change @AnneHurley @andaleliz and post a comment here with the decision.
- [ ] Implement the content change (depending on the AC above).

**Comment by andaleliz** [comment]
I know we put a lot of thought into all content, so wonder what the reasoning is for that complex phrasing to begin with.  I think Janice's suggestion simplifies what we're trying to say and would take less mental load for a user to understand than what is currently there. 

Ultimately, I think this is up to our content team to make the final call on updating that language.

**Comment by AnneHurley** [comment]
Hm - they mean two different things, so we would need to check if it's true YR covers every kind of school l(including instate public schools) as well as the ones we currently list.

**Comment by kelsonic** [comment]
@AnneHurley 

Permission to change content from:
```
the Yellow Ribbon program can help pay for higher out-of-state, private school, or graduate school tuition
```
to:
```
the Yellow Ribbon program can help pay for higher education tuition
```

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/438449ed-4270-4284-bf87-65b27fafd3eb)

**Comment by andaleliz** [comment]
@AnneHurley I'm 99% sure Yellow Ribbon **does not** apply to in-state public schools.  I believe it only applies to out-of-state, private schools, or graduate schools.

Maybe something like `the Yellow Ribbon program can help pay tuition for higher education completed at out-of-state, private schools, or graduate schools` would be more clear?

For what it's worth, this did not stand out as something that confused users in our research study.  I don't recall anyone commenting on this aside from Janice (although, I do remember having to read it 2-3 times myself the first time I encountered it, to really understand what it meant)

**Comment by kelsonic** [comment]
>I'm 99% sure Yellow Ribbon does not apply to in-state public schools.
Ooo I did not know this, awesome!

It might also be a good idea to make it more clear in this first section of content that in order for any Yellow Ribbon benefit to be used, they **must use the full amount of their Post-9/11 GI Bill benefits first**.

**Comment by AnneHurley** [comment]
@andaleliz @kelsonic  I wonder if it would make more sense to explain the above ^ in the text on the main YR page, so that once people start using the search tool they will already know that.

**Comment by andaleliz** [comment]
Definitely a good idea to add it there! Doesn't our IA plan include adding links to the tool on other pages though? Would users who come to the tool via those links, or organic search, have the same information?

**Comment by AnneHurley** [comment]
I was just trying to help the search tool be as clear and simple as possible. I'd advocate for not having all the nuts and bolts in the tools itself - do we already have a link back to the main page on the YR program? that ought to cover us I would think...?

**Comment by kelsonic** [comment]
@AnneHurley @andaleliz Is the plan to not change the pre-content and keep as is?

You can see the current pre-content [here before searching](https://staging.va.gov/education/yellow-ribbon-participating-schools/) and [here after searching](https://staging.va.gov/education/yellow-ribbon-participating-schools/?name=abilene).

**Comment by AnneHurley** [comment]
I think it looks good as-is. We already have the link to the "Find out if you qualify" which I think should provide enough opportunity to learn more. Thoughts?

**Comment by andaleliz** [comment]
Agree with @AnneHurley.  If we count stakeholders with the Veterans we spoke to, 15 of 16 people read the statement in question without voicing confusion or a lack of clarity.

**Comment by kelsonic** [comment]
Awesome! Moving to close this then CC @MickinSahni
