### ISSUE TITLE
DR | Update Need Help component for consistency

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#77946]
## Value Statement
**_As a_** Veteran
**_I want to_** have the most accurate and direct contact information for VA
**_So that_** I can troubleshoot any issues I may have when filling out the form

---
## Background
Rocio brought up that the Need Help components are not matching between forms. Two different phone numbers are listed (the VA 411 line and the Benefits line).

Eileen checked with the contact center team ([thread](https://dsva.slack.com/archives/CNCEXNXK4/p1709907330967469)) and confirmed that the Benefits line (800-827-1000) would be the best line for anything regarding Benefits and Decision Reviews. The VA411 (800-698-2411) line would triage calls to the Benefits number (800-827-1000). They also mentioned that the MyVA411 call records would still include those that are directed to the Benefits line.

Availability is limited for the Benefits line, so we'll need to update the copy in order to reflect this. 

## Test Notes and Design Links
<img width="736" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0039e8f68f944ec1cb0015aa892dd7e2b648412/Screenshot%202024-03-08%20at%201.16.00%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 1.16.00 PM.png" />

## Acceptance Criteria
- [ ] User filing a 10182 sees the Need Help? component before the footer on each screen which directs them to the Benefits number.
- [ ] User filing a 20-0995 sees the Need Help? component before the footer on each screen which directs them to the Benefits number
- [ ] User filing a 20-0996 sees the Need Help? component before the footer on each screen which directs them to the Benefits number

## Tech Tasks
- [ ] Update component with design system form [component](https://design.va.gov/storybook/?path=/docs/components-va-need-help--default) for all 3 forms
- [ ] Move Need Help component into shared directory
- [ ] Update component with language specific to our forms and design.

## Out of scope
- Updating unrelated components

## Definition of Ready 
- [ ] Content and design approved for each form

## Definition of Done
- [ ] Test cases passed
- [ ] E2E testing updated
- [ ] Unit testing updated (90% coverage)
- [ ] Integration testing updated (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@rocio-desantiago I created a ticket for the inconsistency you spotted in https://github.com/department-of-veterans-affairs/va.gov-team/issues/76954 

We can review this in backlog refinement.

**Comment by saderagsdale** [comment]
@rocio-desantiago to estimate

**Comment by rocio-desantiago** [comment]
PR ready for review

**Comment by rocio-desantiago** [comment]
Ready for validation 🎉

**Comment by HeatherWidmont** [comment]
@rocio-desantiago will validate with @eileen-coforma async

**Comment by rocio-desantiago** [comment]
Validated with Eileen 👍

**Comment by Mottie** [comment]
Reopening because platform needs a `va-needs-help` component in the `FormFooter` still.

**Comment by Mottie** [comment]
We're leaving this open because Julie mentioned something about the need help content.

**Comment by saderagsdale** [comment]
@Mottie Oh yeah, thanks for the reminder!

**Comment by eileen-coforma** [comment]
Double-checked with Julie. We are good to move forward with the Benefits number: [800-827-1000](tel:8008271000)

I validated it in staging, good to close unless we want to validate again in standup @saderagsdale
