### ISSUE TITLE
Design feedback - Design intent Collaboration - GIBCT Estimate Your Benefits

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#7795]
**Feedback framework**

**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

### Do:

- No *Do* feedback at the moment

### Try:

- When usability testing this, test on mobile. Here is an article on how to usability test with mobile: http://uxpamagazine.org/hold-the-phone/ 

- Test with users that need assistive tech, but probably once it’s in staging 

### Consider:

- How might the drawer be designed in a way that could be used across VA.gov? If they were to abstract it, or “component-ize” it, what are the distinct parts of the drawer?

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by amyknox** [comment]
@CrystabelReiter - the links you mentioned to mobile usability testing didn't come through, could you re-post? 

For the patternization of the drawer, we're going to hold on that until after we conduct usability testing so we can incorporate any findings into the solution. We'll be looking forward to sharing this on an upcoming DEPO Monday Design call.

**Comment by CrystabelReiter** [comment]
Hi @amyknox  sorry about that! I found this one that could be helpful http://uxpamagazine.org/hold-the-phone/ 

I read it and it seems there's no perfect tool for remote mobile testing, but there are the options of resizing the browser or doing the "laptop hug" method 

That's a good idea to hold on it! Once testing is completed, you can determine whether it would be a good fit and whether to escalate it up to DEPO
