### ISSUE TITLE
[Post-MVP] Investigate adding sort functionality to YR

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7796]
# Description

Investigate adding sort functionality to the YR tool.

"`sortBy` and `sortDirection` logic may be interesting to add in a future version since 3-7% of people who take advantage of GI Bill 9/11 benefits choose schools that start with the letter `A` since everything is sorted alphabetically by default currently" ~ Luke Tickner

## Acceptance Criteria

- [ ] Determine if we want to add sorting functionality
- [ ] Modify the YR tool design to include the sorting functionality
- [ ] Implement the sorting functionality + design into `vets-website`

**Comment by kelsonic** [comment]
Can this be closed? CC @andaleliz @MickinSahni

**Comment by andaleliz** [comment]
I have not looked into analytics or anything to help us determine whether or not this is something we should pursue.   I don't think this is a team priority at the moment.
