### ISSUE TITLE
How to spin up services locally documentation

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#77973]
Create a README file for each service within vets-website, with documentation on how to spin up the service locally for the Benefit Management Tools team. 

The services listed should include the following:
- Claim Status Tool
- Rated Disability
- Payments
- Letters

Create a new README file [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/engineering) and have links point to these other readme files.

**Comment by pmclaren19** [comment]
Added additional information [here](products/claim-appeal-status/engineering/README.md).

**Comment by HeatherWidmont** [comment]
@jerekshoe to review
