### ISSUE TITLE
SOCKS access for Hassan Tariq

### ISSUE THREAD

**Issue by Hassantariq-MetroStar** [department-of-veterans-affairs/va.gov-team#77989]
### Your Name

Hassan Tariq

### Your Email

htariq@metrostar.com

### Your GitHub Handle

 Hassantariq-MetroStar

### Your Role and Team

Senior Devops Engineer for CMS Team

### Product Manager (PM) name and email

Grace Kretschmer - mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn - Erika.Washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/80PHfybSuLJK+9Uojo4+IjA9sa0wsiZJKZGYIsqOTYanmsjtQJGWd9UFR5FDo9EbOVcxqu++5xPxVAEW5LsdGpjz+QGYikclr3B/q+VM1KOhE04Slppe+ag2Tolln1NAPIEmrg3e7fQat8HbnjYE8/q9aciuJWZ8jH6JPqGPDjAYuuVWeABcsEy7kSiua2nbe8e1nu9xeNmejCyDBvxVh614MudO2aEzMN6bwRczdJbfogtI4w1TmqqElKRTwe+CTirumqXzALRbReLcVNUW0bSi5LfsNkN8D26akmrUq6xIfd4IzI8rbi3cLGc6WzUtK+cCLfvMP82F9iht1s4zO2OY1LWPyJVgHhYwN+d5JIQ01vSbCETLFaLYiltqukkCNc2Y1SyIyjW8u3MTKYtOEr7PmwVbzHdIIKN7fvuQ/Knt82c8jK/vrehaFu948XmnSWYZyqvAUUUciWSGcWDHBeVkFP1PV6cyffemgIcwXjfjSqUCR8ZhN/S8d0XaIxs= metrostarsystem\htariq@ITLP01068

### E-QIP Transmittal Confirmation

![Image20240308164640](https://github.com/department-of-veterans-affairs/va.gov-team/assets/159181886/f1bdfc5f-76d3-49d0-93e7-b2507fbbb746)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@Hassantariq-MetroStar Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
