### ISSUE TITLE
Update App Map

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#77985]
Make any updates needed to the App Map & make sure there's a clear way to find it. The purpose of this is to prepare Figma for the end of contract delivery. 

[App map](https://www.figma.com/file/y27KDDtZLBDSVZmAjXdbJn/CST-App-Map?type=design&node-id=221-154&mode=design&t=KycgltQoalbazRPM-11)

**Comment by uxgary** [comment]
I looked through the document and followed up with Skyler. The app map is up to date.
