### ISSUE TITLE
Update DataDog logging for User Type 

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#77983]
## Description ##
In order to confirm that all user flows have been verified in production, we need to be able to pull a report that shows the user flow type and give specific UUIDs. These UUIDs will then be sent to Andrew and David to confirm they made it through the system.

## Acceptance Criteria ##
- [x]  Reporting is updated to allow us to see the user type of specific UUIDs

## Next Steps ##
- Tricia to provide examples of UUIDs for each user flow scenario to Andrew and David

**Comment by tbaker1026** [comment]
@Thrillberg bumping back to in progress to make a new view in data dog .
