### ISSUE TITLE
Create token exchange functionality specifically for chatbot requirements

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#77998]
Chatbot needs the ability to effectively send a token to the azure backend that can then be used to get an ICN for a veteran. To do this, we should do the following:

- create a token exchange endpoint that takes an authenticated access token, and exchanges it with a SiS service account token
- The service account token should be a chatbot specific service account integration, which should only have access to a controller that returns a user ICN
- Chatbot can then send the service account token to their azure backend

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
