### ISSUE TITLE
List & Loop (for example, household info) in Forms section on design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#78]
I think this section may benefit from using diagrams.

Here are some points. These notes are not in any particular order.

The "fractal" form. Long list about a lot of things where follow-up questions are repeated based on certain conditions. For example: DOB, Name, Address, of each family member.

- When would you use this pattern?

Listing them first allows us to do things like label them specifically. “Tell us about Jane’s level of education and income. Okay, now tell us about Timmy” This helps maintain context with cognitive impairments, or just fatigue. Also, on small screens.

- How to add
- How to remove
- When/how to use a "management" capability

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by KevinMHoffmanUSDS** [comment]
## List and Loop

Some questions in forms only have one answer, such as "what is the city and state of your birth?" Other questions can have an unknown amount of answers, such as "list all the cities and states you've lived within." List and loop is a pattern that appears in forms when we don't know how many responses to a question a Veteran will provide, but we need to collect a number between 1 and "n," where "n" is all possible responses. This pattern appears in both simple and complex ways. 

### Simple List and Loop

A simple example of the pattern would include a small number of entry fields, such as one or two text fields in a single line. For a question like "Please list all the cities in which you've lived," a Veteran would list a single city, be given the option to add another city, and could continue adding additional cities until all cities were entered. Then the Veteran would choose to either continue to the next step in the form process or simply submit the completed form if they were at the end of the process. 

DIAGRAM OF PATTERN, SCREEN CAP

### Complex List and Loop with Conditionals

Consider the question "What are the addresses of all locations where have you served?" -- the associated inputs, such as street address, city, state, and zip code would need to be repeated for each additional address of services. However, there are going to be additional fields and form input rules based on whether or not the address is in the United States or international, such as the elimination/variation of "state" fields or variations on how zip codes are validated. Here's an example of how that might play out, and what it looks like in the VA Pensions Application Process.

**Comment by jaredcunha-usds** [comment]
Draft page: https://dev-design.va.gov/patterns/forms#list-and-loop

**Comment by caw310** [comment]
Closing as there is a list loop component.
