### ISSUE TITLE
Consolidate all Call center documentation available in Triage GitHub

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#780]
## User Story
As the new call center lead, I need consolidate important call center documentation into my team folders so I can review and make recommendations.

## Goal
Call center training recap, slide show are stored in the Triage folder.

## Acceptance Criteria
- [ ] Call center training Recap written by Chante is referenced in the triage folder
- [ ] Slide show deck used in the training is referenced in the triage folder

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Per the business recommendation we were asked not to include the WHH training slide show.
