### ISSUE TITLE
Create Representative User class

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78000]

**Comment by bosawt** [comment]
* Rep user attributes (name, email, etc)
  * Ability for representative to see all linked veterans
 
Will have to communicate with ARP team to determine what they currently have/want.

This should be an ephemeral class that is built when the user logs in (this way we can store extra attributes for extra validation and we don't have to store it in a persistent manner)

**Comment by bramleyjl** [comment]
Representative User class creation is included in @rileyanderson's [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15944)
