### ISSUE TITLE
Sign in Service Representative Attribute Validator

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78001]
* Validate sensible MPI attributes (like theft flag detected, death flag)
  * Validate that user information in CSPs has not changed from MPI records
  * Validate any other information that is relevant for representative user

**Comment by bramleyjl** [comment]
The [Representative user auth flow PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15944) contains these validations by implementing the same user login process as standard SiS logins. As part of this, the new Representative User is passed through `SignIn::AttributeValidator`, where MPI flags, attribute mismatches on name, birth_date, and SSN, and other validations are performed.

Looking at what attributes we are storing for RepresentativeUser Redis model, none of them are different from standard User attributes - I don't think any special validation for Representative Users on authentication is necessary.

**Comment by bosawt** [comment]
is there any way we could validate this user is actually a representative?

I believe this class `modules/veteran/app/models/veteran/service/representative.rb` refers to a representative definition (they uploaded a file that stored all the existing representatives), it would be nice to validate the authenticating entity was a member of this list

**Comment by bramleyjl** [comment]
Attribute validation is currently in a [Draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16084) to provide a model for the ARP team as they develop a solution for securely storing representative attributes (first/last name, DOB, SSN) that we can use CSP-derived attributes to validate against.

Marking this as blocked until such a solution is ready.

**Comment by bosawt** [comment]
I think we can close this ticket. ARP team is having to investigate a completely different solution to confirm the authenticating representatives, and we can help them facilitate that solution, but ultimately they'll have to lead the effort to implement it
