### ISSUE TITLE
Sign in Service representative user loader

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78003]
* Basically the same as the current user loader, but reloads a RepUser, instead of a User
  * Can remove a lot of functionality in UserLoader that isn’t relevant here

**Comment by bramleyjl** [comment]
This is covered in the [Representative User auth flow PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15944). The `RepresentativeUserLoader` is found in the ARP module at `/modules/accredited_representative_portal/app/services/accredited_representative_portal/representative_user_loader.rb`

**Comment by bosawt** [comment]
I'm gonna open this back up but add new requirements to refactor the existing RepUserLoader:
- Remove dslogon/mhv references in RepUserLoader
- Remove loa, or hard-code it to loa3, as there will be no possibility to authenticate at loa1
- Determine if there are other changes necessary (it might be possible there aren't other necessary changes)
