### ISSUE TITLE
Design feedback - Design intent Collaboration - GIBCT Sec. 103 Update

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#7800]
**Feedback framework**

**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

### Do:

- No *Do* feedback at the moment

### Try:

- No *Try* feedback at the moment

### Consider:

- If you are able to create the “learn more” content in a way that lends itself to the “additional info” component, that would be ideal. If you’d like to use a modal in the meantime because that’s the way the rest of the this tool works, it will be fine! Perhaps test out 2 versions: the current mockup or one with an additional info component

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by amyknox** [comment]
@CrystabelReiter - thanks for the input! We're going to incorporate some questions focused on the "learn more" content into the usability testing we're conducting next sprint.  We'll let you know what we find out.

**Comment by amyknox** [comment]
@CrystabelReiter - if you're ready for this story to close, we are too. =)

**Comment by CrystabelReiter** [comment]
@amyknox Thanks for reminding me! Closed~
