### ISSUE TITLE
Metrics for authentication

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78006]
* We mostly have this implemented, just need to confirm and update any metrics that are necessary

**Comment by bosawt** [comment]
Tested with a login.gov authentication through 'arp'. Here are the logs that result:

`[SignInService] [V0::SignInController] authorize -- { :type => "logingov", :client_id => "arp", :acr => "min", :operation => "authorize" }`
`[SignInService] [V0::SignInController] callback -- { :type => "logingov", :client_id => "arp", :ial => 1, :acr => "min", :icn => nil, :uuid => "8b928e9e-cf11-4a3c-b387-adc45633c728", :authentication_time => 10 }`
`[SignInService] [V0::SignInController] token -- { :uuid => "2f9d09dd-fa6e-4a13-9dbf-04b49b78c519", :user_uuid => "8b928e9e-cf11-4a3c-b387-adc45633c728", :session_handle => "42ff562a-0ca8-43f5-9986-a55df7f5fca1", :client_id => "arp", :audience => [ "arp" ], :version => "V0", :last_regeneration_time => 1712005349, :created_time => 1712005349, :expiration_time => 1712005649 }`

**Comment by bosawt** [comment]
@joeniquette did you have anything to add to this ticket? Metrics for VRO Rep auth?

**Comment by joeniquette** [comment]
Im not seeing the client_id, audience, user_uuid or several other listed values in the log here: https://vagov.ddog-gov.com/logs?query=SignInService%20SignInController%20token%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZBK9_yFHBarSQAAAAAAAAAYAAAAAEFaQkstQVIwQUFBT0R1ZHpxSUlYMEFFQwAAACQAAAAAMDE5MDRhZjgtMTBhOC00N2QyLWE1NmItNGVkMWMzMjRmNWM3&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1719243805832&to_ts=1719244705832&live=true

**Comment by joeniquette** [comment]
started a board here: https://vagov.ddog-gov.com/dashboard/eqx-rtq-ha9?fromUser=false&refresh_mode=sliding&tpl_var_env%5B0%5D=eks-staging&view=spans&from_ts=1719240827272&to_ts=1719244427272&live=true

**Comment by joeniquette** [comment]
the metrics mentioned above are still missing

**Comment by parkerbees** [comment]
@joeniquette / @bosawt is this still being worked or has it been de-prioritized? Happy to move it into a planning stage if there are other priorities. Thx.

**Comment by joeniquette** [comment]
the token logs are now [searchable](https://vagov.ddog-gov.com/logs?query=SignInService%20session%20created%20TokenResponseGenerator%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1719243805832&to_ts=1719244705832&live=true) by using 
``` SignInService session created TokenResponseGenerator ```

**Comment by joeniquette** [comment]
created two templates and one example with arp. 

1.  https://vagov.ddog-gov.com/dashboard/eqx-rtq-ha9/identity-arp-performance?fromUser=false&refresh_mode=sliding&tpl_var_payload.client_id%5B0%5D=cd51b861ce817f491763eb2f55de8f84&view=spans&from_ts=1721075780675&to_ts=1721680580675&live=true
2.  SiS template: https://vagov.ddog-gov.com/dashboard/pq8-u6y-mh9?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1721677259212&to_ts=1721680859212&live=true
3.  STS template: https://vagov.ddog-gov.com/dashboard/i72-yy8-i97/identity-sts-performance?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1721590542386&to_ts=1721676942386&live=true
