### ISSUE TITLE
Introspect serializer compatibility with representative user

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78004]
* Make sure introspect can work with rep users
  * Maybe `.compact` the serialized output so it doesn’t show fields that don’t exist for a rep user
  * Needs to authenticate with ‘Sign in Service’ authenticated route, which is separate from ‘vets-api’ authenticated route
    * Functionally, the only difference is this route doesn’t care what the client_id is (won’t block based on client_id)

**Comment by dickdavis** [comment]
Collecting observations/questions I have here...

### Observations
* The /introspect endpoint is a vets-api route. It responds with a JSON object that includes user attributes for the authenticated user.
* The authenticated user is referenced by `@current_user`, which is initialized via the `authenticate` method.
* The `authenticate` method calls the `load_user_object` method, which uses the `UserLoader` service to return the user object for a given access token.
  * The `/introspect` endpoint uses the vets-api `UserLoader`--not the `RepresentativeUserLoader`.
  * This makes sense given its a vets-api route and not contained within the ARP module (where `RepresentativeUserLoader` is implemented).
* The access token is derived from the bearer header (if present) or the access token in the cookie.

### Questions
* Do we need to modify the `load_user_object` method to call the correct user loader based on the client ID in the access token?
```ruby
klass = case access_token[:client_id]
        when Settings.sign_in.arp_client_id
          AccreditedRepresentativePortal::RepresentativeUserLoader
        else
          UserLoader
        end

klass.new(access_token:, request_ip: request.remote_ip).perform
```

**Comment by bosawt** [comment]
Just updating here that the plan for `/introspect` should be that it is refactored so it no longer relies on a `User` type object, and probably better to just more closely follow an oauth `/introspect` as defined in the RFC: https://datatracker.ietf.org/doc/html/rfc7662

**Comment by dickdavis** [comment]
We've had discussions over the past few days about how we'd like to approach this. We settled on removing the introspect serializer altogether because we use JWTs and not opaque tokens.
