### ISSUE TITLE
Vets-api terminal access for [Ahmed J Magdub]

### ISSUE THREAD

**Issue by ajmagdub** [department-of-veterans-affairs/va.gov-team#78010]
### Your Name

Ahmed J Magdub

### Your GitHub handle (terminal access is managed through GitHub)

@ajmagdub

### Your dsvagovcloud AWS user name (if applicable)

Ahmed.Magdub

### Team, Role, and Company of the target individual

Appointments, Developer, VA

### Product Manager (PM) name and email

@Leah De La Costa

### Product Owner (PO) name and email

@Jeff Roof

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I am a Developer in the Appointments Team and sometimes need access to the Rails console for specific tasks.

I am a current VA FTE, have been a VA FTE for 19 years, and have been issued a PIV card, which expires in 5/23/2026

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
confirmed in Atlas

confirmed [E-QIP](https://github.com/department-of-veterans-affairs/devops/pull/6732)

**Comment by bdech** [comment]
@ajmagdub You’ve been granted access to the `staging` environment.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by ajmagdub** [comment]
Thanks Brandon

I tried following the instruction you've sent to get terminal access but unfortunately I don't see the Terminal tab described.

Thanks for your help!


  AJ Magdub
  IT Specialist
  Office of Information and Technology, Development, Security, and Operations
  Software Product Management (SPM)
  Telehealth and Scheduling Product Line
  Work phone: 303 398-5594
  Alternate phone: 303 903-0062
  Monday through Friday, 7:30 to 5:00 Mountain





From: Brandon Dech ***@***.***>
Sent: Monday, March 11, 2024 10:26 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Magdub, AJ (OIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Vets-api terminal access for [Ahmed J Magdub] (Issue #78010)


@ajmagdub<https://github.com/ajmagdub> You've been granted access to the staging environment.

Here's some additional documentation for Vets API on EKS<https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess> that may help.

-
