### ISSUE TITLE
Identity SDK - Define Modal component

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#78022]

**Comment by acald-creator** [comment]
In this PR, https://github.com/department-of-veterans-affairs/identity-sdk/pull/3, there is a Modal that was copied direct from `component-library` for internal use and reference. While testing, I will be refactoring it to where I can get the component to work with the Login modal and others similar to this.

**Comment by acald-creator** [comment]
To do: Refactor `Modal` to use Typescript instead.

**Comment by acald-creator** [comment]
put back to backlog, will need to revisit this if the modal is not available from the component library

**Comment by parkerbees** [comment]
Moved to Jira, closing
