### ISSUE TITLE
Discovery: Optimize Datadog Integration for Breakers Metrics

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#78038]
## Description

Currently, our Datadog integration for breakers metrics (leveraging the circuit breaker pattern middleware integrated into Faraday) introduces challenges due to the lack of wildcard filtering and/or tagging support. Previously, with Prometheus, we could utilize wildcards to dynamically generate graphs for each service, streamlining our monitoring process. However, with Datadog, metrics are received individually (see any of the [api_external_http_request metric](https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1710172888023&end=1710176488023&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgViBpOGPIQAHQaCJ4aUM2NEE5wxAg6kWhOXAjyTkZBbU4AogBqAMqLTgDCmD71anDdVcAAVDwgPAC6VK7ueJih4ReqVxgxpfHHZyBtWGg5oPIYXwiDZRQHAwJyZa4aCCZRJoURwJxyRTKdKwqAwuFOehMZQiNweNDHfgQeyYLAIhQ5ECwkRKU48PjveSwhCrKTCGAoERXNA8IA)s and how the service name is integrated into the metric name itself), requiring manual creation of graphs for our 54+ downstream services. This manual approach is cumbersome and inefficient, disrupting our workflow. 

[Our OpenMetrics configuration ](https://github.com/department-of-veterans-affairs/devops/blob/548d04d193eaf5428584ed78e01e8ec33919f5f9/ansible/build/roles/datadog/vars/vets-api.yml#L4) currently collects metrics by 'api*', and we suspect that this may be affecting how breakers metrics are grouped. Our intention is to improve the metrics configuration by enabling filtering based on service/tag, to facilitate more dynamic chart creation.

There is an additional [conversation here](https://oddball.slack.com/archives/C045LCF8WU8/p1709837590820059) regarding some of the details in early discussion.

## Tasks
- [ ] Evaluate our OpenMetrics Config
- [ ] Evaluate other options for metric grouping, sorting, tagging, etc. Research potential solutions within Datadog to group individual metrics effectively, allowing for dynamic graph generation similar to our previous setup with Prometheus.

**Comment by jennb33** [comment]
This work was rolled into ticket [77891](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77891)
