### ISSUE TITLE
Slackbot Release to OCTO @ VA Slack Workspace

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#78042]
## User Story
As an Identity Team member, I would like the slackbot released to VSP-Identity so I may start using it to field requests from other teams.
* The slackbot will live in the `#vsp-identity` channel

### `octo-identity-bot` Slack Admin
- [x] reinstall `octo-identity-slackbot` to update with new OAuth permissions
- [x] `SLACK_APP_TOKEN`
    * Basic Information => Generate an App-Level Token, "Slackbot App Token", with the `connections:write` scope.
- [x] `SLACK_BOT_TOKEN`
    - [x] OAuth & Permissions => Generate Bot User Oauth Token with proper permissions.
        * app_mentions:read - view/respond when bot is mentioned
        * channels:history - view channel bot is part of, needed to read commands
        * chat:write - post messages announcing completion of slash-command workflow
        * commands - slash-command functionality
        * files:read - allows for screenshots to be uploaded to Slackbot forms 
- [x] Create /docs & /identity-support slash commands
- [x] Enable socket mode

### AWS ParameterStore
- [x] update `SLACK_BOT_TOKEN` & `SLACK_APP_TOKEN` values with new `octo-identity-bot` tokens
- [x] update `ISSUE_TICKET_REPO` value to `va.gov-team-sensitive`

**Comment by bramleyjl** [comment]
## Needed OAuth Scopes

- app_mentions:read - view/respond when bot is mentioned
- channels:history - view channel bot is part of, needed to read commands
- chat:write - post messages announcing completion of slash-command workflow
- commands - slash-command functionality
- files:red - allows for screenshots to be uploaded to Slackbot forms
 
<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94b90383116d32e908230021bcf2f989e8ba119c/Untitled.png" alt="Untitled.png" />

**Comment by bramleyjl** [comment]
@jhouston0 I added you to this ticket because we'll need to update most of the environmental variable values with new values from OCTO @ VA Slack & the `va.gov-team` Github repositories. We can coordinate the change once we get approval for the release; I'll keep you updated.

**Comment by bramleyjl** [comment]
The slackbot is now up and running on `#identity-project-support-process` (for testing) and `#vsp-identity` Slack channels.

Github tickets are still created in `identity-slackbot` until we are ready for our official release.
