### ISSUE TITLE
Discovery: Investigate freshclam running on container startup

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#78054]
## Description

We have identified an unintended behavior in our Docker container setup regarding the ClamAV signature updates. Our current expectation and configuration aim for the ClamAV signatures to be updated during the Docker image build process **only**. However, [alerts](https://vagov.ddog-gov.com/monitors/205156?cols=host%2Cservice&event_id=7480895533030523570&source=monitor_notif&view=spans&live=4h) and [logs](https://vagov.ddog-gov.com/logs?query=service%3Aclamav%20%22GET%20%2Fdaily.cld%20HTTP%2F1.1%22%20&agg_q=env&agg_q_source=base&cols=host%2Cservice&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort_m=&sort_t=&storage=hot&stream_sort=time%2Casc&top_n=10&top_o=top&view=spans&viz=stream&x_missing=true&from_ts=1709927422000&to_ts=1709934622000&live=true) indicate that updates are also being performed at container startup, which deviates from what's expected

### Detailed Description:
The Dockerfile for ClamAV includes a step where [freshclam is executed](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/Dockerfile#L32) to update the ClamAV signatures during the initial image build phase. This step is intended to ensure that the built image contains the latest virus definitions at the time of its creation. However, it has come to our attention that the [ClamAV daily.cvd alert](https://vagov.ddog-gov.com/monitors/205156?cols=host%2Cservice&event_id=7480895533030523570&source=monitor_notif&view=spans&live=4h) is triggering at container startup times as well, suggesting that updates are being performed outside of the image build process.

Upon further investigation, we discovered that our container's [ENTRYPOINT script](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/Dockerfile#L32) [includes the command `freshclam -d`](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/docker-entrypoint.sh#L31C1-L31C13). This command launches the freshclam daemon in the background `(freshclam -d &)`, which periodically checks for and applies updates to the ClamAV databases based on the configured frequency for virus signature updates. This behavior is potentially unintended for our deployment scenario, as it introduces variability in the virus definitions between container restarts, potentially affecting reproducibility and our security posture.

Based on [the freshclam.conf configuration](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/freshclam.conf#L8), the Checks directive is set to 8. This means that freshclam is configured to check for database updates 8 times a day. From research though, it appears that `freshclam` checks with our specified [`PrivateMirror` ](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/freshclam.conf#L10) for database updates every 3 hours (24 hours/8 checks), ensuring ClamAV remains up to date with the latest virus definitions available from the s3 bucket mirror.

**NOTE:** The concern above regarding the execution of freshclam might be a non-issue. It appears that the real challenge lies in the potential variability of virus definitions across containers during deployment, which could theoretically introduce inconsistencies. However, considering that `freshclam` retrieves signatures from our dedicated S3 bucket, rather than directly from the ClamAV network, this risk of variability is virtually eliminated. The controlled and consistent source for signature updates effectively ensures uniformity across all container instances, mitigating concerns about definition discrepancies and their impact on our security posture. We _may_ consider reducing the frequency of [`freshclam` checks](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/freshclam.conf#L8) if [the signatures in our S3 bucket are updated twice daily.](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/.github/workflows/s3_sync.yml#L7) - at one minute past hours 5 and 17.

### Expected Behavior:
The ClamAV signatures should only be updated at the time of the Docker image build. No updates should occur at container startup or during the container's runtime **(Also see note above regarding this being a non-issue)**

### Actual Behavior:
ClamAV signatures are being updated both at the time of the Docker image build and subsequently at container startup due to the background execution of the freshclam daemon.  **See note above regarding this being a non-issue. It may be that this is the expected behavior that we want. When freshclam runs (via the daemon process) it's pulling any updates to signature databases from our s3 bucket.**

### Outcomes:
- [ ] Discovery document on what was learned about having freshclam run on container startup

**Comment by LindseySaari** [comment]
The main concern is running freshclam after booting pods because we had connectivity issues with S3 during the TIC outage and our HPA was going crazy because it couldn't get healthy pods stood up.

**Comment by jennb33** [comment]
Errors are still occurring daily (between 1-3pm eastern) consistently. @rjohnson2011 is still getting up to speed with ClamAV errors/logs (link [here](https://vagov.ddog-gov.com/monitors/205156?cols=host%2Cservice&event_id=7480895533030523570&source=monitor_notif&view=spans&live=2d#status-history) )

**Comment by rjohnson2011** [comment]
Notes:
The `freshclam -d &` command is still being run in the [Dockerfile](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/Dockerfile#L32).
The modifications last week were changing it from [8 times a day to 1](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/freshclam.conf#L8).

**Comment by jennb33** [comment]
Next steps: 
We still want Freshclam-d to run in the background so that when we redeploy clamav pulls in the new signatures. 
We only need to update the signatures 1x per day, not 8x per day.
