### ISSUE TITLE
[ARF] Implement Header and Footer

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#78055]
### Potential Future Issues
- **_Update MobileHeader to be have functionality of site-wide header_**
  - Create when there is a greater level of certainty around the header dropdowns and buttons in the section underneath the logo
  - If we decide we don't need dropdowns here or greatly change the design then this ticket's output may not be useful
- **_Update WiderThanMobileHeader to not share any styles with VA.gov header_**
  - Currently this component is using the same styles as are used in the content-build `src/site/includes/header.html` with a few overrides.
  - In tweaking these styles it was assessed that the styles are very fragile and contain a good bit of technical debt
  - If these styles are altered with the purpose of altering `src/site/includes/header.html` it may alter the ARP header in unpredictable ways because of their differences and because of the `arp/header.scss` overrides
  - Therefore to not inherit this tech debt and to insulate us from potential breaking style changes it would be desirable to create our own styles for this component potentially in a WiderThanMobileHeader.scss file
  - However, the styles currently applied are aligned with the mockups so for the Pilot this may be a lower priority issue
- **_Update MobileHeader to not share any styles with VA.gov header_**
  - Currently this component is using the same styles as are used in the site-wide mobile header - src/platform/site-wide/header with a few overrides
  - These styles are implemented in a more modern way with less tech debt then the styles for content-build `src/site/includes/header.html`
  - However, if these styles are altered with the purpose of altering `src/platform/site-wide/header` it may alter the ARP mobile header in unpredictable ways because of their differences and because of the `arp/header.scss` overrides
  - Therefore it would be desirable to create our own styles for this component potentially in a MobileHeader.scss file
  - However, since there are not yet designs for the ARP mobile header this may be a lower priority issue

### Overview
- The `registry.json` file in the `content-build` repo registers the `vets-website` applications and specifies which `content-build` layout they are using:
```
{
    "appName": "Accredited Representative Portal",
    "entryName": "representative",
    "rootUrl": "/representative",
    "productId": "89100c00-5b5f-46fd-bd98-d3b35f220958",
    "template": {
      "vagovprod": false,
      "layout": "page-react.html"
    }
  },
```
- The `vets-website` `accredited-representative-portal` app is currently using the `page-react.html` layout like all other applications in the `registry.json`. 
- However, unlike all other applications we do not want most of the veteran facing content provided by the `page-react.html` layout or its children content:
  - `src/site/includes/header.html`
  - breadcrumbs
  - maintenance messaging
  - loading indicator and message
  - feedback button content
  - `src/site/includes/footer.html`
- `page-react.html` has provided a suitable placeholder for now but since we do not want most of its content we should migrate to our own `content-build` layout
- We determined that we would make our own version of `page-react.html` and we did this in a previous issue before this epic was created: [Determine where to build and implement the initial skeleton/layout for the representative-facing site content#72956](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72956)
- This issue created 3 template files in `content-build`:
  - src/site/includes/accredited_representative_portal/[header.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/accredited_representative_portal/header.html): opening `html` tag, `head` tags, opening `body` tag, `header` tags
  -  src/site/layouts/[accredited_representative_portal.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/accredited_representative_portal.html): our header, a div with our contents within it (our arp `vets-website` app), our footer
  - src/site/includes/accredited_representative_portal/[footer.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/accredited_representative_portal/footer.html): `footer` tags, closing `body` tag, closing `html` tag

### Goals
- Ensure all the content for `page-react.html and its children (`src/site/includes/header.html`, `src/site/includes/footer.html`, etc) are in 'accredited_representative_portal.html` and its children (src/site/includes/accredited_representative_portal/`header.html` and src/site/includes/accredited_representative_portal/`footer.html`) or the vets-website ARP application that is being injected into it
- The plan is to retain the needed functionality from `src/site/includes/header.html` without including any of its templating or styling, and instead provide the template and styling from a `header.jsx` component in our `vets-website` app
- In addition, no functionality was determined to be needed from `src/site/includes/footer.html` and so all the templating and styling will come from a `footer.jsx` component in our `vets-website` app
- Finally there may be some layout aspects needed to incorporate from `page-react.html` that we will have to bring into our `vets-website` `SignedInViewLayout.jsx` component

### Definition of Done
- When a user navigates from `staging.va.gov` to `staging.va.gov/representative` they  no longer see the va.gov standard header and footer and instead see our placeholder minimal header and footer. This may look like a slight regression but since we don't need most of the content in the `va.gov` header and footer its actually an enhancement and allows us to easily add our own header and footer.
- Between the header and footer our app layout should look unchanged
- When in development, developers should only see the ARP header and footer when in ARP

### Dependencies

None

**Comment by gabezurita** [comment]
@a6marinos and @williamphelps13, closing this epic as there is no more work to do.
