### ISSUE TITLE
[Post-MVP] Investigate changing filter content YR

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7806]
# Description

![image (1).png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/2358b4ef-deef-4fff-b9f6-39abe25d535a)

Tammy stated that the checkbox text `Only show schools that fund all tuition and fees not covered by Post-9/11 GI Bill benefits` was confusing when looking at it on https://staging.va.gov/education/yellow-ribbon-participating-schools/ and that it may be clearer if it were simplified.

## Related Issues
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7805

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7794

## Acceptance Criteria

- [ ] Unlimited Contribution Amount Checkbox: `Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill)`
- [ ] Unlimited Student Count Checkbox: `Only show schools that cover all eligible students`

**Comment by AnneHurley** [comment]
@kelsonic  - I'm a little confused - screenshot above doesn't signal "unlimited contribution amount." Not sure which actual phrase confused Tammy? also cc @andaleliz Do you know?

**Comment by kelsonic** [comment]
@AnneHurley It's the one in the screenshot

**Comment by kelsonic** [comment]
@AnneHurley Updated the ticket to be clearer, sorry about that 🙂

**Comment by AnneHurley** [comment]
@kelsonic @andaleliz How about:
- [ ] All tuition and fees are covered
- [ ] All eligible students are covered

**Comment by AnneHurley** [comment]
Also, for this problematic phrase: 
![image](https://user-images.githubusercontent.com/46570591/78929431-3ea58600-7a57-11ea-8ac0-06088f5e193a.png)

Why don't we go with the same phrase as in the beginning of the search:
All tuition and fees are covered

What say you @kelsonic  and @andaleliz

**Comment by andaleliz** [comment]
I think it's important to communicate somehow that Yellow Ribbon will fund whatever remains _after_ the Post 9/11 benefits are maxed out.  Maybe I'm over thinking it, but if you saw "all tuition and fees" you could think that you don't need Post 9/11 GI Bill and YR would cover everything. Or also maybe that somehow you could get get double money if you had both.

**Comment by andaleliz** [comment]
@kelsonic, we discussed in Slack but want to be sure I talk through this thoroughly with you and @AnneHurley before I update the designs.

You and @AnneHurley discussed, and still want to move forward with `All tuition and fees are covered`, 
> since we already state that they have to qualify for Post-9/11 GI Bill benefits in the pre-content

The pre-content I think you're referring to (on the landing page) is:
>If you already have Post-9/11 GI Bill benefits, the Yellow Ribbon program can help pay for higher out-of-state, private school, or graduate school tuition. The amount of money you get varies by school, degree type, and the program you're enrolled in.

Which to me, does not exactly say - "Yellow Ribbon funds a portion of (and in some cases, all) what remains after your Post 9/11 GI Bill benefits are maxed out"

I think there is a real possibility that `All tuition and fees are covered` could lead users to misunderstand how the benefit actually works.  At least as much as the term `unlimited` does.

Do you both still recommend `All tuition and fees are covered`?  Totally possible I'm overthinking this, but just want to cover all the bases.

**Comment by kelsonic** [comment]
> @kelsonic, we discussed in Slack but want to be sure I talk through this thoroughly with you and @AnneHurley before I update the designs.
> 
> You and @AnneHurley discussed, and still want to move forward with `All tuition and fees are covered`,
> 
> > since we already state that they have to qualify for Post-9/11 GI Bill benefits in the pre-content
> 
> The pre-content I think you're referring to (on the landing page) is:
> 
> > If you already have Post-9/11 GI Bill benefits, the Yellow Ribbon program can help pay for higher out-of-state, private school, or graduate school tuition. The amount of money you get varies by school, degree type, and the program you're enrolled in.
> 
> Which to me, does not exactly say - "Yellow Ribbon funds a portion of (and in some cases, all) what remains after your Post 9/11 GI Bill benefits are maxed out"
> 
> I think there is a real possibility that `All tuition and fees are covered` could lead users to misunderstand how the benefit actually works. At least as much as the term `unlimited` does.
> 
> Do you both still recommend `All tuition and fees are covered`? Totally possible I'm overthinking this, but just want to cover all the bases.

It makes sense to question this decision imo, but I do think it's the decision that makes the most sense. To postfix `"not covered by Post-9/11 GI Bill benefits"` to the max contribution amount field value and the checkbox texts seems very repetitive and in our usability testing it's confused a lot of users.

I think the best route is to update the pre-content to make sure it clearly conveys that YR benefits only kick in _after_ Post 9/11 GI Bill benefits are maxed out. @AnneHurley @andaleliz Can we brainstorm updates to the pre-content to make sure this is very clear and simple?

**Comment by andaleliz** [comment]
Yes, totally up for brainstorming.  

Also want to clarify that I think the current language is confusing too! But, I think there's gotta be a way to wordsmith it in a way that communicates what we need, without being confusing or misleading.

**Comment by kelsonic** [comment]
@AnneHurley 

Permission to change content from:
![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/74505e59-9d42-4057-9c71-f60d08b3322d)

to:
![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/82720616-363e-4485-b380-3c85c25bc65d)

https://staging.va.gov/education/yellow-ribbon-participating-schools/

**Comment by AnneHurley** [comment]
@kelsonic and @andaleliz  What about:
[ ] Yellow Ribbon covers all remaining tuition and fees
[ ] Yellow Ribbon covers all eligible students 

I know the second line is now a bit longer, but I wanted it to be in parallel structure with the top line. I think "Yellow Ribbon covers all remaining tuition and fees" gets the point across that we want to say, plus if someone sees this for the first time, they will see "remaining" so know they need to find out what that refers to. Without overpopulating the tool with text.
What do you think?

**Comment by andaleliz** [comment]
I like where you're headed with those, but I feel like those are odd labels for a checkbox as part of search criteria.  My sense is that the labels should reflect the action performed when the box is checked.  What about a combo of what we have, and your suggestion:

- [ ] Only show schools that cover all remaining tuition and fees
- [ ] Only show schools that cover all eligible students

or maybe inverting it will be more clear?

- [ ] Hide schools where I may have to pay a portion of tuition and fees out of pocket
- [ ] Hide schools that have a limit on the number of Yellow Ribbon students

**Comment by kelsonic** [comment]
> Only show schools that cover all remaining tuition and fees
> Only show schools that cover all eligible students

Oh I really like that! 💯

**Comment by AnneHurley** [comment]
^Me too. Let's do it @andaleliz  and @kelsonic

**Comment by andaleliz** [comment]
prototype updated!

**Comment by kelsonic** [comment]
Changing

**Unlimited Contribution Amount Checkbox:**
```Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill)```

**Unlimited Student Count Checkbox:**
```Only show schools that cover all eligible students```

as per Slack convo: https://dsva.slack.com/archives/C52CL1PKQ/p1586880041453400?thread_ts=1586876389.445700&cid=C52CL1PKQ
