### ISSUE TITLE
Minor accessibility tweaks YR

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7807]
# Description

Remove the focus outline for `No results found.` on the new YR tool. https://staging.va.gov/education/yellow-ribbon-participating-schools/?name=asdf

Remove superfluous sr-only nodes from the YR tool.

## Acceptance Criteria

- [ ] Remove the focus outline for `No results found.` on the new YR tool.
- [ ] Remove sr-only nodes for YRP fields that already have a visible label to avoid screen reader stating things multiple times.

**Comment by MickinSahni** [comment]
Validated on staging
