### ISSUE TITLE
QA Standards - OCTO Health Apps - MHV Medical Records

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#78081]
#### VFS team name
OCTO Health Apps

#### VFS product name
MHV Medical Records

#### VFS feature name
After Visit Summary

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No traceability reports attached.
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 85.81

- Functions %: 82.4

- Statements %: 85.78

- Branches %: 76.24

- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---
All categories must be at least 80%.

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by acrollet** [comment]
Here's the top-line coverage report for AVS from running `yarn test:unit --app-folder avs --coverage --coverage-html`:

```
95.98% Statements 311/324
94.19% Branches 146/155
97.89% Functions 93/95
96.12% Lines 298/310
```

@it-harrison let me know if you have any questions or if this satisfies the requirement? thanks!

**Comment by it-harrison** [comment]
> Here's the top-line coverage report for AVS from running `yarn test:unit --app-folder avs --coverage --coverage-html`:
> 
> ```
> 95.98% Statements 311/324
> 94.19% Branches 146/155
> 97.89% Functions 93/95
> 96.12% Lines 298/310
> ```
> 
> @it-harrison let me know if you have any questions or if this satisfies the requirement? thanks!

@acrollet - looks good! you can close this ticket.

**Comment by acrollet** [comment]
great, thank you @it-harrison !

cc @klawyer
