### ISSUE TITLE
Form tester: Optionally ensure all data is entered

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#781]
## Problem
1) We build a form to have a field `root_foo`
2) Our test data has `{ "data": { "foo": "bar" } }`
3) We change the form later to hide `root_foo` under some condition
4) Our test data is still in there, but `root_foo` is never shown, so the data is never entered

This causes a mismatch between the test data and the test run. That is to say, the data at the end of the test run (filling out all the fields) won't match the data we used to do the run. The trouble with this is the resulting "data rot" where we've got vestigial test data hanging around that's invalid for the case the test data was originally intended for.

(That's a lot of words; I'm having a hard time describing why exactly it's a problem. Basically it has to do with test data hygiene.)

## Goal
The form app tester checks that all the data in the test file is entered successfully into the form.

## Acceptance Criteria
- [ ] Add functionality to the form tester to check that data is entered as expected
- [ ] A configuration option is opened up to check for complete data entry (default `true`)
- [ ] If `true`, the tester ensures that all data in the test file is successfully entered into the form

## Possible solutions
Before we run the page hook for the confirmation page, we might be able to pull the `formData` from the redux store and compare it to the test data.

Barring that, we can check each field after we input the data and have some state object keeping track of what was successfully entered. (This is pretty gross, I think, so I'd prefer the above if at all possible.)

Data entry functions are split up into multiple methods depending on the type of data, so data validation will likely be configured differently for each data type.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by meganhkelley** [comment]
@caw310 @JoeTice I'm not sure if this is still an issue but am passing to your teams.

**Comment by ddzz** [comment]
The form tester enters data in three separate functions based on the type of data being entered. Currently I have data validation working for checkboxes, and I'm expanding on this to work with tex boxes. After that I'll work on modifying the form tester to add the option to enable or disable this feature per test.

**Comment by ddzz** [comment]
I've opened [a PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20469) that adds validation for some fields. It does not appear to be feasible to ensure data validation for all fields; some test data for existing tests includes data that has value or data that is used for configuration, and there is no obvious way to filter these out in the form tester.
