### ISSUE TITLE
[Development] 526: Explore Whether it is Possible to Pull V1 S3 File Attachment Links into V2

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7810]
## User Story or Problem Statement
As a veteran, I need to be able to submit a claim in the new system but may have some V1 files in the system that I don't want to lose.

## Goal
See if it is possible to include those in their V2 application when they start one.

## Acceptance Criteria
- [ ] We know whether the S3 links are still there (not expired)
- [ ] Is there any way we can "move" or otherwise make available to a V2 application (suggested approach would be to write a small API call to query S3 and link the files into a V2 application when it gets instantiated.  Assumption here is there is nothing to link to until they start a V2.  There is a number of ways to approach this).
- [ ] Is there a way to manually do it in the cases where someone calls the Call Center

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
Already being done! I added some comments in https://github.com/department-of-veterans-affairs/vets-website/pull/12349 as a future reminder.
