### ISSUE TITLE
Architecture Diagram for Representative Status Widget MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78103]
## Background
For the Privacy, Security, Infrastructure Readiness Review we'll need to provide a link to our Architecture Diagram.  

For reference: [Architecture Diagram for Find a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/launch-materials/arm-architecture-diagrams.pdf) if you'd like to take a similar approach.

## Tasks
- [x] Create an Architecture Diagram for Representative Status Widget MVP

## Acceptance Criteria
- [x] An Architecture Diagram has been created and reflects Representative Status Widget MVP

**Comment by holdenhinkle** [comment]
See Google Slides doc - https://docs.google.com/presentation/d/1CTkCFgoPNodllJaDUAOuN5fvNBRM9LI5fi90_iDhNAY/edit#slide=id.g1ff395eb91d_0_19
