### ISSUE TITLE
Adding Oren Mittman to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#78117]
Please add Oren Mittman as a multi-channel user 
work email: oren.mittman@adhocteam.us
va email: oren.mittman@va.gov

channels requested: 
api-benefits-claims 
team-dash

Oren is a new SWE on team Dash working on the Accredited Rep Management contract supporting Lighthouse. 

Thank you!

**Comment by LEHigley** [comment]
couldn't add to either channel but invited to slack and general
