### ISSUE TITLE
[Development] 526: Decouple V1 Flow Based on Whether Veteran Has a V1 SIP

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7811]
## User Story or Problem Statement
As a veteran, I need to be able to submit a claim in the new system but also need to be informed that my V1 claim expired.

## Goal
Provide the veteran entry into the V2 system to start a new claim even if they have a V1 claim in progress. Also, think about whether there is some messaging that can happen letting the veteran know they have lost their V1 claim.

## Acceptance Criteria
- [ ] There is no more option to continue a V1 claim
- [ ] A message is displayed (if possible) that the veteran has lost their V1 claim information.  Depending on whether there were files attached we may want to provide a different message.  This will be related/dependent on the discovery effort @SMLuthi is doing in #7810 

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
I think this ticket is closely related to #7810 in that users are now _always_ redirected to the version 2 form 526. The SIP data for v1 is automatically converted into a v2 format, including their attachments (#7810) and associated data.

The only problem is that some extra data may get passed from v1 to v2 data - related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8350

I think we can close this ticket.
