### ISSUE TITLE
[Spike] - List out components that use font awesome.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#78114]
## Background/Request
We tentatively expect Font Awesome to be deprecated at the end of May. To prepare for this, we want to list all components that currently use font awesome for displaying icons across our app. The VA design system is working on guidance for how teams can migrate onto `va-icon` which will be a new component for rendering icons

[Thread for more info](https://dsva.slack.com/archives/C03R5SBELQM/p1710173294036219)

### Goal
- [ ] All usage of font awesome across our app is identified and listed.

## Tasks
- Answer the following questions:
  - Q

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by jenniemc** [comment]
There are approximately 20 files that references font awesome icons:

1. src/applications/vaos/appointment-list/components/RequestedAppointmentDetailsPage.jsx:
2. src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentCard.jsx:
3. src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentColumn.jsx:
4. src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentColumnLayout.jsx:
5. src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentListItemGroup.jsx:
6. src/applications/vaos/appointment-list/components/AppointmentsPage/RequestAppointmentLayout.jsx:
7. src/applications/vaos/appointment-list/components/AppointmentsPage/RequestListItem.jsx:
8. src/applications/vaos/appointment-list/components/AppointmentsPage/tests/AppointmentCard.unit.spec.js:
9. src/applications/vaos/appointment-list/components/cancel/tests/cancelAppointmentConfirmationModal.unit.spec.js:
10. src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/CancelLink.jsx:
11. src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/PrintButton.jsx:
12. src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/PrintLink.jsx:
13. src/applications/vaos/appointment-list/redux/selectors.js:
14. src/applications/vaos/appointment-list/sass/styles.scss:
15. src/applications/vaos/components/calendar/CalendarCell.jsx:
16. src/applications/vaos/components/calendar/CalendarNavigation.jsx:
17. src/applications/vaos/covid-19-vaccine/components/ConfirmationPage.jsx:
18. src/applications/vaos/covid-19-vaccine/components/ConfirmationPageV2.jsx:
19. src/applications/vaos/new-appointment/components/CommunityCareProviderSelectionPage/ProviderSelect.jsx:
20. src/applications/vaos/new-appointment/components/ConfirmationPage/ConfirmationDirectScheduleInfoV2.jsx:

cc: @simiadebowale  @ldelacosta  @JRRoof

**Comment by ldelacosta** [comment]
New tickets have been created for the work: #79352, #79353, #79354, #79355.

**Comment by ldelacosta** [comment]
Closing the ticket.
