### ISSUE TITLE
Add a new feature flag for Datadog RUM

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#78115]
## Item Description
We will need to create a feature toggle for datadog RUM implementation.

---

## Tasks
- Add `va_online_scheduling_datadog_RUM` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated
---

**Comment by ldelacosta** [comment]
Feature toggle has been added. Closing the ticket. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2tZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d45d6c7fd687dbcd6bec21ba9ab6513d2d2c74c6/Screenshot%202024-03-27%20at%206.47.02%20PM.png" alt="Screenshot 2024-03-27 at 6.47.02 PM.png" />
