### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/va.gov-team#78145]
### Name

Christine Rose Steiffer

### Email

christine.steiffer@va.gov

### Role

Designer/Researcher

### Team

Disability Benefits - Employee Experience Team

### Product Manager (PM) name

Amy Lai

### Additional Notes

As Carolyn Dew is on leave, I am requesting Figma access to manage the design files for our team. Thanks!

**Comment by naomimarcussen** [comment]
Hi! You have full access now. :)

**Comment by ChristineRoseSteiffer** [comment]
@naomimarcussen should I have gotten an email about it or anything? I haven't seen anything. I try to login and it says my pw is wrong. If I try to reset it, I don't get an email to my va.gov email address about resetting it.

**Comment by naomimarcussen** [comment]
Hi! It looks like your account is with your agile6 email. If you'd prefer to have it with your va.gov email, I can transfer it over to that. But in terms of accessing your full access, you'll just need to log in with your agile6 email, and you should be able to do what you need with that.

Feel free to reach out if you can't get in. :)

**Comment by ChristineRoseSteiffer** [comment]
Hi @naomimarcussen - I think I would prefer to switch my access over to my VA.gov email if that is possible. Thank you for your help and sorry for the confusion!

**Comment by naomimarcussen** [comment]
@ChristineRoseSteiffer No worries! I just sent an invite to [christine.steiffer@va.gov](mailto:christine.steiffer@va.gov). Let me know once you create an account with that link so I can bump it up to full access.

**Comment by ChristineRoseSteiffer** [comment]
Hi @naomimarcussen - I just got my account set up if you want to bump me up! Sorry it slipped my mind over the weekend and I just realized this morning that I hadn't set it up yet. Thank you so much for your help with this!

**Comment by naomimarcussen** [comment]
Great! I've upgraded your va.gov email to full access and downgraded your Agile 6 account.
