### ISSUE TITLE
Log number of COMPENSATION & PENSION appointments

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#78141]
## Description
We want to track the number of Compensation & Pension (aka Claim Exam) that are displayed in veteran's appointment list.  Please create logging to capture the count of how many C&P exams are shown to veterans.

---

## Acceptance Criteria
Given an authenticated veteran
When viewing their appointment list
Then capture a count of all appointments of type COMPENSATION & PENSION

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cferris32** [comment]
Here is a biweekly summary of average C&P appointment counts across appointment list retrievals through VAOS. Note that lists containing zero C&P appointments are excluded from these metrics.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG94QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9791e7b563a3fb1eefcdf7a7cb7c609be2121bc7/Screenshot%202024-04-03%20at%201.34.20%20PM.png" alt="Screenshot 2024-04-03 at 1.34.20 PM.png" />
<img width="1518" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHN4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d89f1831bb93a6c94a8d7d41b114beae0584e20/Screenshot%202024-04-03%20at%201.34.54%20PM.png" alt="Screenshot 2024-04-03 at 1.34.54 PM.png" />
From this data, we can generally expect thousands of users to have at least one or two C&P appointments in their appointments list, and some even have as many as 10 or more.

**Comment by JRRoof** [comment]
@cferris32 - I'm not able to view the screenshots.  @ldelacosta - are you able to see them?

**Comment by ldelacosta** [comment]
@JRRoof - can you open this [link](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20Compensation%20and%20Pensio[…]%2Ctrue&from_ts=1710869639198&to_ts=1712165639198&live=true)

**Comment by cferris32** [comment]
Data for 4/3/24 - 4/15/24

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--babf0825820a1f386d71f299567d6ecf37b9dc11/Screenshot%202024-04-15%20at%201.32.17%E2%80%AFPM.png" alt="Screenshot 2024-04-15 at 1.32.17 PM.png" />
<img width="1548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66ce6369d4b4a885d5a7f7ed0cc745617c3d25f8/Screenshot%202024-04-15%20at%201.32.44%E2%80%AFPM.png" alt="Screenshot 2024-04-15 at 1.32.44 PM.png" />

**Comment by cferris32** [comment]
It appears that viewing the images through zenhub renders them properly, but not on github. Currently unsure why that is.
