### ISSUE TITLE
Delete InProgressForm after successful submission (Ticket 2 of 2)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#78148]
`[SHELL - NEEDS TO BE UPDATED]`

## Issue Description
After #72897 is completed we need to delete In Progress Forms after successful submission

During the FSR submission step where we update the submission's status, we want to delete the related IPF (only if submission is successful)

***NOTE, per Kevin, ticket 72987 needs to be completed as STEP 1, then we should complete ticket 78148 as STEP 2.**

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16110)
