### ISSUE TITLE
[BE] General AE: fix mhv session 400 errors

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#7814]
## Background

previous ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6391
mhv endpoint /mhv-api/patient/v1/session is returning a lot of 400 errors for certain mhv correlation ids. find a way to reduce the number of errors. i emailed mhv about steps we can take to reduce the errors and i'm waiting for a response.

## Tasks

- [ ] reduce mhv 400 errors

## Acceptance criteria

- [ ] errors have been reduced

**Comment by Samara-Strauss** [comment]
Still haven't heard back from MHV.

**Comment by lihanli** [comment]
after looking into this issue again, i think it might be up to the team that handles login related issues to fix it?

here is the explanation of the problem: when a user logs in we sometimes get a `mhv_correlation_id` from the external login api (id.me, dslogon, mhv, etc). then, as a logged in user, when they visit any non-legacy page on va.gov, the backend returns basic user data that the frontend needs access to.

one of these things is the mhv account type. however when calling the mhv api to get the account type the mhv api sometimes doesn't accept the `mhv_correlation_id` that we received from the external login provider, and gives us an error. i think the best solution would be to get the external login provider to stop giving us invalid `mhv_correlation_id` for users, and instead give us nothing so we stop trying to lookup a user's mhv account type.

**Comment by Samara-Strauss** [comment]
Thanks for this! Let's pull in someone from the login/identity team to determine next steps. I'll find someone you can sync with on this.

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/vets-api/blob/bb7f8ef91bb5f36b0177200440d078512b49f6e4/lib/mvi/responses/profile_parser.rb#L109

Some of these sentry reports might be relevant.

**Comment by mshea0606** [comment]
I'll set up a meeting with the identity team regarding this issue

**Comment by ajakabcin** [comment]
No longer an issue
