### ISSUE TITLE
Identity SDK - Define `CreateAccountLink` 

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#78165]
Description:

Create a reusable component that can be used to implement create an account link.

- [ ] Create an interface to define the `CreateAccountLink`
- [ ] Create an interface to define the `a` element

**Comment by acald-creator** [comment]
This was partially done but needs to be tested once the current class for the oauth is done

**Comment by parkerbees** [comment]
Moved to Jira, closing
