### ISSUE TITLE
10-7959f-2 - Schedule stakeholders for interviews

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#78170]
Acceptance criteria:

- Schedule interviews with identified stakeholders
- In invitation, mention we'd like to see walkthoughs of their processes

**Comment by marywang2** [comment]
Is this a duplicate of [this one](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/77753)?

**Comment by rachaelpenfil** [comment]
It's not - I just forgot to change the titles. I'll fix that now!

**Comment by rachaelpenfil** [comment]
No longer relevant, @brian-wilke is taking this over.
