### ISSUE TITLE
Document current downtime behavior 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#7819]
## Overview 

VA.gov relies on several backend services that experience scheduled and unscheduled downtime. Triggering and content for dow3ntime messages are decentralized and difficult to manage in the frontend. 

## Tasks 

- Review the [downtime notification documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/) 
- Review the [graceful degradation ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6681)
- Document all of the apps that use the `DowntimeNotification` component
  - For each app, list its service dependencies 
  - Forms apps will configure their downtime behavior with a [`downtime` property](https://github.com/department-of-veterans-affairs/vets-website/blob/767fdf6cd938b94d3e4627a48c1e6d4d72509dcc/src/applications/hca/config/form.js#L201-L204) on their form config 
  - For each, document its non-global downtime message behavior. In general they should use the default behavior but indicate if an application provides custom messaging for a service downtime message or component 
- Document apps implement nonstandard downtime alerts (these may not exist)
- Document apps that have no downtime behavior 
- Document what vets-api endpoints each app uses
- Use the service dependency map to determine if apps have VA service dependencies that are not in their downtime notification configuration 

## Notes 

- Consider the static-pages.js a single app when documenting. It has several widgets so we may need or list / group these

**Comment by bkjohnson** [comment]
What exactly does "nonstandard downtime alerts" mean?


I'm going to write some of the documentation in this issue until we decide on where we want an official document to live.

## GI Bill Comparison Tool

- No _listed_ dependencies

**Endpoints**
- `/calculator_constants
- `/institutions/autocomplete`
- `/institution_programs/autocomplete`
- `/institutions/search`
- `/institution_programs/search`
- `/institutions{FACILITY CODE}`
- `/zipcode_rates`

**Comment by rianfowler** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/frontend/downtime-notification-discovery.md
