### ISSUE TITLE
Add suggestion about how to order the conversation guide

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#78195]
### Description

I'd like to make some edits to the research with assistive technology users page in the research section of the Platform website. The Decisions Reviews team learned some lessons during recent research with screen reader users that may be useful to other teams.

The change:

For https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users

After the bullet: "Write assistive technology-specific screener questions", add another bullet:

* When planning your conversation guide, it can be a good idea to set up the screen sharing first after a few qualifying questions. This way, if you can't get the screen sharing working, you can choose to pivot the session. You could reschedule, cancel or pivot the session to suit your needs.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS

**Comment by jknipes** [comment]
Related [work ticket 79042](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/79042) added to Backlog

**Comment by jknipes** [comment]
@davidakennedy once again, thanks for bringing our attention to this. The updates have been made and we are closing this ticket.
