### ISSUE TITLE
Github team request for VA Lighthouse

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#78222]
### Describe the problem

Hello! The VA Lighthouse UX team has need to access certain github pages owned by platform (specifically read access to va.gov-research-repository and the va.gov-team-sensitive repo). 

Currently, we ask for each individual to be added to the VFS-team roster on a case-by-case basis. Because Lighthouse does not build on the VA platform, we don't send our staff through the rest of Platform Orientation.

### Who will benefit

VA Lighthouse and VA Platform

### Describe your idea

With the goal of streamlining things, I was wondering if it might be possible to set things up so that the "lighthouse-ux" GitHub team might be added as a contributor with read access to the va.gov-research-repository and the va.gov-team-sensitive repositories automatically?

Is that something the Platform might consider?

Thanks,
Carey

### Provide evidence

N/A

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by shiragoodman** [comment]
@sstrassberg as the OCTO Research lead, would you have any issues with Lighthouse team members getting direct read access to the va.gov-research-repository repo?

I am following up on the va.gov-team-sensitive repo internally and will respond shortly.

**Comment by sstrassberg** [comment]
@shiragoodman Not a problem at all.

**Comment by shiragoodman** [comment]
@careyotto can you please confirm the name of your team in gh? I was unable to find "lighthouse-ux"

**Comment by careyotto** [comment]
Thank you both! Shira, I have an ask with my program's engineering lead to confirm. Will get back to you as soon as I can.

**Comment by shiragoodman** [comment]
Ok, so one of the maintainers on the lighthouse-apis team will have to add the va.gov-research-repository repo to the list of repos. I believe that can be done[ here. ](https://github.com/orgs/department-of-veterans-affairs/teams/lighthouse-apis/repositories). @sstrassberg might have to approve it.

Still following up on the sensitive repo.

**Comment by bschofield-va** [comment]
I am a team maintainer for `lighthouse-apis`. It did not let me add `va.gov-research-repository`. Perhaps from the repo itself, a repository admin can add `lighthouse-apis` as a collaborator with read access.

**Comment by shiragoodman** [comment]
I might bring this question over the to the #github_information channel on Slack and ask the VA Github admins for help. I'm always uncertain if the best process is for the team to add the repo or the repo to add the team.

**Comment by shiragoodman** [comment]
@bschofield-va Shane was able to add your team to the gh repo. See this [Slack thread ](https://dsva.slack.com/archives/CU1E4CX9U/p1711378019335919)for details.

**Comment by shiragoodman** [comment]
@careyotto Regarding read access to the va.gov-team-sensitive repo, Platform leadership has denied the request as there is no clear understanding or justification in the request to require access.

I have cc'd Platform Engineering Lead @little-oddball. If you have further questions or concerns, please take it up with Clint. Thanks.

**Comment by careyotto** [comment]
Thanks for the update, Shira. Totally understand.

@little-oddball There are two reasons why VA Lighthouse team members need access to  the va.gov-team-sensitive repo. 

1. VA Lighthouse program owns the "Connected Apps" page under Profile. We coordinate with Samara's team when we make changes here, but we are the owners.

The only way our team can view, test, etc. these pages is by using the the VA.gov test user credentials to view it in staging. i.e. This page: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-bb.md

2. Additionally, VA Lighthouse uses the Platforms Optimal Workshop instance. Our credentials are stored here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/design/tools/optimal-workshop.md

Please let me know if that clears things up or if you have any other concerns about granting "lighthouse-apis" team members read-only access to the va.gov-team-sensitive repo.

Thanks,
Carey

**Comment by little-oddball** [comment]
@careyotto - That is useful information. Is there a specific current lighthouse team that you would want to be added? We definitely don't want to add the 25 or so there are.

**Comment by careyotto** [comment]
Sounds like a great compromise. I think if I ask nicely @bschofield-va can spin us up a more fine grained group for access. Stay tuned!

**Comment by careyotto** [comment]
@little-oddball Bryan was kind enough to create a child team of **lighthouse-apis** called **lighthouse-ux**, which just contains the program's UX practice, a much smaller subset of humans. Does that work for you for adding to the va.gov-sensitive-repo?

**Comment by little-oddball** [comment]
@careyotto - that looks good. I have added that team to the repos with READ access.

**Comment by careyotto** [comment]
Awesome, thank you, Clint!
