### ISSUE TITLE
[Consistency] User encounters design components that are inconsistent or confusing.

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#78237]
"_This ticket was generated during the pilot process for the new VA.gov experience standards. Please tag `@platform-governance-team-members` on Slack if you need assistance interpreting this ticket._

## Product Information
**Team:** 
**Product:** 
**Feature:** 

## Findings details
**VA.gov Experience Standard - issue:** User encounters design components that are inconsistent or confusing.
**VA.gov Experience Standard - category:** Consistency
**Launch-blocking:** No
**Design System Review:** Yes
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

The primary button has extra padding on the top and bottom.

## Recommended action
Testing: Remove the extra padding.

## References

- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Button ](https://design.va.gov/components/button)
- **Design System Pattern:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A
- **Accessibility Defect Severity:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner."

**Comment by caw310** [comment]
DST is aware of the extra padding and will fix it.
