### ISSUE TITLE
VAOS FHIR create top level v1 routes

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#7823]
**User Story**: As an API consumer I'd like VAOS to differentiate between v0, the current app, and v1, the FHIR version so that I don't mix JSON API and FHIR requests in my implementation.

**DoD**: 
- [ ] At least one new route exists to demonstrate how the FHIR routes and controllers will be wired up

**Comment by lenaecb** [comment]
@saneshark - is this still in progress?
