### ISSUE TITLE
SOCKS access for Dan Bivins

### ISSUE THREAD

**Issue by danbivins** [department-of-veterans-affairs/va.gov-team#78238]
### Your Name

Daniel Bivins

### Your Email

dan.bivins@adhocteam.us

### Your GitHub Handle

danbivins

### Your Role and Team

Accessibility Specialist, MHV Cartography team

### Product Manager (PM) name and email

Wes Rowe, wesley.rowe@agile6.com

### Product Owner (PO) name and email

Patrick Bateman, patrick.bateman@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8YG1I7xU9srk0CGGJJHiJoEyVHlQgtvuUHVKDRSRLa dan.bivins@adhocteam.us

### E-QIP Transmittal Confirmation

![eqip](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10236001/1c27fe52-6a63-49fd-aa55-5546363f449f)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@danbivins Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
