### ISSUE TITLE
Design/Research: multiple service history error messaging 

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#78249]
Related to this ticket: https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/69020

Need to find a design solution for when Veterans have more than one military service history in uploading documents.

**Comment by juliepedtke** [comment]
@lisacapaccioli I believe this was resolved in the [linked ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/69020), and we can close this out!
