### ISSUE TITLE
[FE] Appeals: implement analytics for appeals

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#78242]
## Background
We currently do not have GA analytics tracking for 
- API call to `/appeals` endpoint ([getAppealsV2](https://github.com/department-of-veterans-affairs/vets-website/blob/96038b651aa7a984267e3c404a20b486f24a7462/src/applications/personalization/dashboard/actions/claims.jsx#L45) function)
- CTA link clicks for appeals cards ([Appeal.jsx component](https://github.com/department-of-veterans-affairs/vets-website/blob/96038b651aa7a984267e3c404a20b486f24a7462/src/applications/personalization/dashboard/components/claims-and-appeals/Appeal.jsx#L111))

---
## Tasks
- [x] update getAppealsV2() 
- [x] update CTALink in Appeal component

## Acceptance Criteria
- [ ] events are being successfully tracked in GA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any dev
- _How can this work be validated?_ staging GA dashboard

## Resources
- [Adam's comment in PR review](https://github.com/department-of-veterans-affairs/vets-website/pull/28481#discussion_r1521688725)

**Comment by allisonlu** [comment]
@ajakabcin 

ready for validation! these changes should be on staging but i'm not sure where to find the My VA dashboard on GA for staging. 

in the meantime, can i get a validation from the devs? 🤠  @adamwhitlock1 @DanielMiller-agile6

**Comment by ajakabcin** [comment]
Confirmed the appeals cta link and api calls are being tracked in GA and Domo
