### ISSUE TITLE
NEW for 3/20/2024 UPDATE: Redis Upgrade: Wording - Maintenance Window

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#78250]
## Problem

While a [reusable maintenance page](https://github.com/department-of-veterans-affairs/vagov-content/pull/908/files) was create during the last upgrade attempt, the date and time frame of the maintenance window in this page need to be updated to reflect this.

New date is now March 20, 2024
Time remains 2am-5am eastern time

**Comment by flooose** [comment]
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4a984d796eff3f2be5329a959cd36a0c3a8d2db/image.png" alt="image.png" />
