### ISSUE TITLE
VAOS FHIR create v1 base controller

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#7825]
User Story: As an API consumer I'd like VAOS to differentiate between v0, the current app, and v1, the FHIR version so that I don't mix JSON API and FHIR requests in my implementation

**DoD**: 
- [ ] A new v1 directory exists with a base controller with logic that the other FHIR based controllers can inherit.

**Comment by ajmagdub** [comment]
base controller already created by Alistair in task: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7827
