### ISSUE TITLE
Data Pull Tickets Are Created (Request & Support Process)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#78261]
**User Story**
As an Identity Team member, I need all of the requests to have associated tickets, so that I may have a holistic view of the requests.

**Acceptance Criteria**
* Requests for Data Pulls have tickets created.
   * Any field where PII might be displayed will be redacted from the actual ticket.

**Comment by joeniquette** [comment]
duplicate
