### ISSUE TITLE
VFS Custom Events for Dependents Benefits & 27-8832, 28-1900, 21-686/674, 21P-530EZ, & COE/LGY 26-1800

### ISSUE THREAD

**Issue by zack** [department-of-veterans-affairs/va.gov-team#78274]
# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

## Our Forms

**Dependents 21-686/674**
https://docs.google.com/spreadsheets/d/1Jl6sDqyUb0QYky-IEVrb6bCBYYxuB1bA77ZLb4oLocY/edit?usp=sharing

**Burial 21P-530EZ**
_No uses of recordEvent_

**Chapter 31/VR&E 28-1900**
https://docs.google.com/spreadsheets/d/1ALCxLQtRzTcpaMEwaO-AqBYDJQr8-r-K9kMM-nbJRhQ/edit?usp=sharing

**Chapter 36/PCPG 27-8832**
https://docs.google.com/spreadsheets/d/1qjysuMtIWz1dtu-d5BPhf-Req6MVQKPXv7RijRpYyto/edit?usp=sharing

**COE/LGY 26-1800**
https://docs.google.com/spreadsheets/d/1YWx37mx5qzGaOmB9g_9TsbwmAY11Jxc64DBH_gGi0x8/edit?usp=sharing

**Comment by johnny-jesensky-adhoc** [comment]
@zack, Excellent - thank you for providing these docs so quickly! We'll add these to our queue, and will be in touch if we have any questions, as well as once these have been added to GA4.

FYI @jestutt
