### ISSUE TITLE
Traffic hitting erroneous scheduling URL

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#78283]
## Summary
Veterans are hitting the URL `/my-health/new-appointment` which shouldn't exist. We're seeing this in Google Analytics and Medallia data, but are unable to create the scenario that triggers it.

Pages with the erroneous URL string:
<img width="1740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6922f2f5c835b02a605e55bf8e30d44b5d31cc53/Screenshot%202024-03-12%20at%202.35.58%E2%80%AFPM.png" alt="Screenshot 2024-03-12 at 2.35.58 PM.png" />

Pages that Veterans are coming from when they hit that URL:
<img width="1559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d80a4465b6cf958361b9ae38e223bf5307de4a2/Screenshot%202024-03-12%20at%202.38.21%E2%80%AFPM.png" alt="Screenshot 2024-03-12 at 2.38.21 PM.png" />

Data shows that this started when we released the URL work (October 4, 2023):
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7281dfc7e5173b4afb5ff3e1defdc0b875fefb3/image.png" alt="image.png" />

See this pull request for more details: https://github.com/department-of-veterans-affairs/vets-website/pull/25957

## Specs
- Device: 
- Browser: 

## Steps to Reproduce
**Test User:** 

We've been unable to reproduce this on staging. Attempts to hit the URL directly lead to a 404 page.

1. Go to: _URL_
2. 

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

We don't know, but we are receiving complaints from this page.

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

The URL shouldn't exist, or be linked to from anywhere.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by outerpress** [comment]
@ldelacosta @JRRoof I'm not sure if this is related but user feedback came in around errors when folks are clicking the scheduling button:

> when I try to click the make an appointment button. it says not found


>"I was trying to schedule an appointment online and when I selected ""Make an Appointment"" the page it sent me to said ""Sorry"" so I will call.  I guess I would like it to get fixed or just remove appointment scheduling online, and tell me I have to call.  than's no problem.  Thanks, NAME_PII"

> When I click "schedule an appointment " it says page not found



> Unable to schedule appointment with online tool because when you click it, it goes to unknown page and says there is an error.

**Comment by jenniemc** [comment]
@outerpress @JRRoof @ldelacosta, It appears the ticket #71713  fix Empty state link to schedule appointment broken  has resolved the issue of users going to “my-health/new-appointment”.  The fix to the bug was deployed midday on 3/12/2024 to production. Looking at GA, there is 99.7% drop in users going to the erroneous link after March 12. 

I suggest checking the GA reports into next week to validate page view of erroneous url has stopped.
___
![Screenshot 2024-03-14 at 12 09 02 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/cdb8608b-d0b3-4f9a-b3bb-60b630a6a453)

**Comment by outerpress** [comment]
@jenniemc thanks! @JRRoof @ldelacosta I see the same thing in GA. [Link to report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20231001&_u.date01=20240313&explorer-table.filter=my-health~2Fnew-appointment&explorer-table.plotKeys=%5B%5D)

<img width="1628" alt="Google Analytics Showing pageviews from Oct 3-Mar 13" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2536801/1330ccb6-3309-4467-9036-97a138334471">

**Comment by ldelacosta** [comment]
We'll keep this ticket open for the next couple days. If there are no issues to report, we will close it out. cc: @jenniemc @outerpress @JRRoof

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @JRRoof @outerpress
