### ISSUE TITLE
Grafana changes for wider audience

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#7830]
## User Story or Problem Statement

The current Grafana setup that we have is sort of internal-facing. We're put in this place by the current work environment where each program is responsible for its own monitoring. However, our current setup and strategy has been identified as something that could be useful for partners that we work with in other parts of the agency, and we'd like to do some work to make the setup a bit more accessible to them. This may need to turn into an epic, but this ticket for now is going to be used to capture some of the asks so far.

- Allow anonymous reads to select dashboards — It doesn't look like this is doable except at the organization level. A possible thing that we can pursue is to use OAuth2 auth by registering an app with the Azure AD stuff internally. We can register applications easily, so this might be trivial to stand up.
- Add TLS — this was skipped in early versions because we were disconnected from the VA network and didn't want to deal with the hassle of forcing everyone to install the internal VA CA. Still not sure how much effort that support work will be, but would be ideal if we can do that.

## Goal
Central goal is being worked on, but generally trying to use this ticket to gather up what we want to build to help communicate out about the pain of running services currently.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Moved the reporting stuff out to a separate ticket as that can be treated as a separate concern.

**Comment by patrickvinograd** [comment]
When I filed #8602 I poked around a bit, and if you enable anonymous viewer access, you can then go and make individual dashboards not anonymous-viewable by removing the "Viewer" role from them. If you then made sure that all program staff had a more-than-Viewer role, that would be a viable way of making some but not all dashboards open to VA.

**Comment by jhouse-solvd** [comment]
We are moving the platform's monitoring to Datadog. I don't believe that this is relevant. Will revive if determined to be needed. 

Closing.

**Comment by patrickvinograd** [comment]
I would say the use case of being able to share monitoring dashboards more widely/easily is still something to keep in mind, even if not tied to Grafana. Ok with this remaining closed though.
