### ISSUE TITLE
Medallia 2.0 a11y - [Major] Fix submit/close button tab order

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#78312]
## Issue Description
Visually, the "Submit feedback" button appears before the "Close" button. But when using a keyboard to navigate the form (via TAB), you navigate to "Close" first. It looks like "Close" is actually first in the source, which doesn't match the visual presentation. 

[CAIA A11y Medallia 2.0 audit
](https://docs.google.com/spreadsheets/d/1Z_xXH2WnyP0YWNCJFKs0duwgSIug9VNEmzWR9RzxSYM/)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
https://app.slack.com/client/T03FECE8V/C05NUG2QB9S?selected_team_id=T1ZD0UBMZ

**Comment by aubreyarcangel** [comment]
After [discussing this issue with the Medallia team](https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/78405), it was determined that this could not be fixed as this time.
