### ISSUE TITLE
Medallia 2.0 a11y - [Minor] Remove confusing aria-label for submission "close" button

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#78317]
## Issue Description
When the form is submitted, the user is taken to a submission screen ("Thank you for taking our survey"). This screen has a "Close" button that's been given the aria-label "Close Survey, Survey completion message".

This aria-label is confusing - is the button how I close the survey, or is it a message? It's also  unnecessary - the visible text, "Close," is sufficient. 

Fix this by removing the aria-label from this button. Or, if an aria-label must be present, change that text to "Close" or "Close survey" (remove the "message" text).

This issue was identified during the [CAIA Medallia 2.0 audit](https://docs.google.com/spreadsheets/d/1Z_xXH2WnyP0YWNCJFKs0duwgSIug9VNEmzWR9RzxSYM)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
No longer relative - fixed with the 2.0 update
