### ISSUE TITLE
Generate example 0781 for Emily and Julie

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#78329]
Get an example or template of the 0781 pdf form for review and auditing

**Comment by SamStuckey** [comment]
@shaunburdick is completing this ([slack thread](https://dsva.slack.com/archives/C05MPTGMX0E/p1710345231519669?thread_ts=1710344359.765999&cid=C05MPTGMX0E))

**Comment by shaunburdick** [comment]
Templates can be found here: https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/pdf_fill/forms/pdfs
