### ISSUE TITLE
FE | General Maint | Check User 11 - should be checking disability_compensation endpoint but is not

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#78325]
## Background
I thought user 11 would hit the disability compensation endpoint and return results advising that the user has a fiduciary flag of some kind. 

 We need to check if the user data is dirty and needs to be revised or if there is some sort of problem preventing the endpoint from being requested. 

## AC 
-  [ ] create additional tickets after we determine what is going on

**Comment by adamwhitlock1** [comment]
I _think_ we can just close this one out. The user works to some extent and there isn't an issue with the Profile code specifically. 

There may be a need to reach out to platform support to 'reset' the state of the user if they don't have the account information that we think they should have, but other than that I think that about all we could do in that regard.
