### ISSUE TITLE
(Figma) Update designs with new copy for Gross monthly income > Other income

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#78330]
## Issue Description
On Gross monthly income, when you select "Other income," a follow-up field is revealed. The label on that conditionally-revealed field just says "Please specify," which isn't a label that can be understood on its own.

---
## Tasks
- [ ] Update designs with copy updates

## Acceptance Criteria
- [ ] Updated Figma design file for Gross monthly income page 
---
## References
Updated copy is included in the [staging review ticket for this issue](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73980)

**Comment by echin393** [comment]
@aplatt-coforma In terms of ways of working, what do handoff workflow do you recommend after the acceptance criteria is met for design tickets? I’ve made changes accordingly in Figma for this ticket and #78333, but I’m not sure if a new ticket should be created for implementation, if a review needs to be facilitated, or something else?

**Comment by aplatt-coforma** [comment]
@echin393 - typically, for deisgn tickets, the designer would do a review with our VA design lead (Julie Strothman) either during their weekly sync or async in slack. Once approved, the design or product will either update the eng ticket (if one exists) or create an new eng ticket making sure to include the link to the design files. 

For the 2 tickets you've worked on, I believe there are already dev tickets noted in the Dependencies section in the ticket. If there there are no approvals needed from VA design lead (you can check with Gretchen), then you can just add a link to the design files in those tickets and you're good to close these design tickets. 

This design ticket #78330 -> Eng ticket [#73980](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73980)
Design ticket [#78333](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78333) -> Eng ticket [#73973](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73973) and [#73981](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73981)

Thanks!!

cc @gmaciolek @buddhima-coforma @matt4su

**Comment by echin393** [comment]
Thank you! Super helpful.

**Comment by gmaciolek** [comment]
The [Figma design](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2644%3A134062&mode=design&t=uh8FQAwSpDTqoWwS-1) and [engineering ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73980) for this issue have been udpated.
