### ISSUE TITLE
Analytics Implementation or QA Support for [VSP Grafana]

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#7833]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

Implementation

- Who is this request for?

    - VSP Operations - Wyatt Walter
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#vsp-operations`._
    
- What team/project is this work for?

I'd like to get a tagmanager ID or whatever to get an "app" in Google Analytics for our internal Grafana instance to see how it's being used.
    
- Provide the Domain where Google Analytics needs to be implemented
    
    _Identify if PII is passed in URL or title tag_

No

    - grafana.vfs.va.gov (this is internal-only and used by VSP itself)
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - None, this is a nice-to-have and no rush

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - Viewing and editing dashboards I suppose? I don't know what I don't know yet on what's available.
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Go to http://grafana.vfs.va.gov from CAG/GFE or on SOCKS and sign in using GitHub OAuth :)

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Same, we don't have credentials. We just use GitHub OAuth.

- Certain conditions/responses that need to be reviewed

    - NA

- Additional Comments

    - This is likely not your typical request :) Grafana already has support embedded, we just need to provide it identifiers. The documentation has https://grafana.com/docs/grafana/latest/installation/configuration/#google-analytics-ua-id, but there's a google_tag_manager_id setting too.

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @wyattwalter  -- acknowledging receipt! We will take a look and get back with you!

**Comment by jonwehausen** [comment]
@wyattwalter We would also like to schedule a kick-off with you and your team to discuss your timeline, tracking components, KPIs, etc around this solution. 

Could you provide your upcoming availability for the week of 4/20 - 4/24?

**Comment by ricetj** [comment]
@jonwehausen I can setup a meeting with you. Please reach out in slack.

**Comment by ricetj** [comment]
From speaking with Jon, making some updates here. It sounds like we will be able to see most of what we want with GA basic.

Things we would like to see:
- number of users accessing Grafana
- Seeing which dashboards are most used or least used (if used at all)
- seeing the flow of users ie they start at one dashboard and move to x then y. 
- average time spent on each dashboard. 

We can start here and work from that.
cc: @jonwehausen

**Comment by ricetj** [comment]
@jonwehausen is this something we can get in place this week?

**Comment by jonwehausen** [comment]
Hi @ricetj , 

Thanks for checking in - I'll work on getting the initial GTM container setup and get that snippet over to you all. We can expect to bring into Sprint 26 starting on Wednesday. 

Thanks!

**Comment by jonwehausen** [comment]
Hi @ricetj ,

Thanks for your patience here! 

**The first step to get a vanilla version of GA stood up on Grafana will be to get the Google Tag Manager snippet put-in across the environment. **

Paste this code as high in the **\<head>** tag of each page as possible

```javascript
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-54T9PQG');</script>
<!-- End Google Tag Manager -->
```


Additionally, paste this code immediately after the opening **\<body>** tag:
```javascript
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-54T9PQG"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

@ricetj Once we get this in, we can validate to make ensure traffic is flowing into GA properly. From there, we can show you what you'll be able to see with an OOB GA and from there we can get a sense if theres additional items you'll need for phase 1.

**Comment by bsmartin-ep** [comment]
@jbritt1 -

Thanks for getting our GTM snippets into Grafana.  Is there any way to get the snippets in the locations [Jon indicated?](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7833#issuecomment-628837026)  Or is this a limitation of Grafana?

**Comment by jbritt1** [comment]
> @jbritt1 -
> 
> Thanks for getting our GTM snippets into Grafana. Is there any way to get the snippets in the locations [Jon indicated?](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7833#issuecomment-628837026) Or is this a limitation of Grafana?

I do not know where that snippet would even go to be honest. That is something @wyattwalter would likely have to provide guidance on.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Here is a GTM container for Grafana.  It should send in hits to GA for all pages views and history state changes where the Page contains _orgId=_.  This is due to Grafana triggering multiple history changes for each dashboard load.

https://tagmanager.google.com/#/container/accounts/144676348/containers/31380813/workspaces/2?orgId=oXPY3GFFQwaHnjNHpFLyFg

Looks good in GA...

![image](https://user-images.githubusercontent.com/62304138/82234756-cfe20500-98ff-11ea-802a-0b12622a438b.png)

**Comment by bsmartin-ep** [comment]
@jbritt1 -

We're [seeing data in GA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7833#issuecomment-630281839) from where you added the snippet, so it might not be a blocker for us.  

If it is possible for @wyattwalter to move them into the <head> etc, I still think it's a good idea.  If it's something Grafana doesn't allow, we understand.

**Comment by ricetj** [comment]
@jonwehausen 2 more things, can you link to the location on GA and 2nd can you grant my team GA access?  / What is the process for that?  I know Wyatt and I have it.

**Comment by bsmartin-ep** [comment]
@ricetj -

Grafana GA:

https://analytics.google.com/analytics/web/#/report-home/a50123418w232865244p218626196

Can you paste me a list of your team members?

**Comment by ricetj** [comment]
> @ricetj -
> 
> Grafana GA:
> 
> https://analytics.google.com/analytics/web/#/report-home/a50123418w232865244p218626196
> 
> Can you paste me a list of your team members?

Thank you and I already got them access.

**Comment by bsmartin-ep** [comment]
Add _orgId_ to the query parameter exclusion list, @jonwehausen?  Do we have multiple orgId's?

![image](https://user-images.githubusercontent.com/62304138/82255105-10eb1100-9922-11ea-8420-d0e275874a1c.png)

**Comment by jonwehausen** [comment]
Thanks Brian! Added `orgId` as a Exclusion Parameter

**Comment by jonwehausen** [comment]
@ricetj We have verified the property is collecting data properly and the orgId filter is working as expected, pageviews that contain orgId in the URL will be consolidated and removed. 

Here is a link to the Grafana GA property home page: https://analytics.google.com/analytics/web/#/report-home/a50123418w232865244p218626196

Let us know if any of your team members do not have access that need it. Also let us know where we can be of assistance from a reporting perspective and/or if you all have any additional tracking needs for phase 2.
