### ISSUE TITLE
(Figma) Update design for spouse Veteran question

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#78333]
## Issue Description
Household information > Spouse information > Is [name] also a Veteran? - The answer choices of "Yes" and "No" are not given in the same order as other yes/no questions. Almost all other questions are given as Yes then No, but in this case, it’s No then Yes. This could confuse the user.

---
## Tasks
- [x] Update Figma design

## Acceptance Criteria
- [x] Updated Figma design
---
## References
Guidance on copy/design updates is in the [staging review ticket](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73973)

**Comment by gmaciolek** [comment]
The [Figma design for this page](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2031%3A51846&mode=design&t=uh8FQAwSpDTqoWwS-1) has been updated with the requested changes

**Comment by echin393** [comment]
Thank you @gmaciolek for updating the respective engineering tickets with links to the Figma updates. Closing this ticket now.
