### ISSUE TITLE
Qualitative Data Request: Burial Allowance, 21P-530EZ

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78345]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

3/13/2023

### Date Range End

3/13/2024

### Product Name(s)

Application for Burial Benefits 21P-530EZ

### Product Description

VA Form 21P-530 (Application for Burial Benefits) enables eligible individuals to apply for compensation to help cover burial, funeral, and transportation costs.

### Survey URL(s), key term(s), case category or type

1. Specific feedback from this page: https://www.va.gov/burials-memorials/
2. Specific feedback from this page: https://www.va.gov/burials-memorials/veterans-burial-allowance/
3. All feedback under this root url: https://www.va.gov/burials-and-memorials/application/530/

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

laura.steele1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Also, these two URL's were not available in Medallia: https://www.va.gov/burials-memorials/veterans-burial-allowance/
 https://www.va.gov/burials-memorials/
