### ISSUE TITLE
move diagrams over to visio

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#78340]
we need to move all the important product diagrams into a shared folder within visio

**Comment by joeniquette** [comment]
I cant export the diagrams from lucid yet, there is an account issue. I have a meeting with a lucid support person next week to try and resolve my issue.

**Comment by parkerbees** [comment]
@joeniquette are you still working on this? It looks like it's been in the "current sprint" column for a while. Thx.

**Comment by joeniquette** [comment]
I havent worked on this in a while, Im going to try and get it closed out this sprint.

**Comment by joeniquette** [comment]
all diagrams from lucidchart have been downloaded to my personal machine. I need to move them to our sharepoint folder. Im not able to email zip files over to my VA email so I contacted the help desk to ask how I can send a large number of files so that I can upload them to sharepoint. (ticket opened on 7/26)

**Comment by joeniquette** [comment]
request update from yourit, no response yet.

**Comment by parkerbees** [comment]
@joeniquette how many files are there and/or how large is the Zip file? I might have some options for you.

**Comment by joeniquette** [comment]
about 60 files, about 25 mb

**Comment by parkerbees** [comment]
Oh that's not terrible! That's under the max file size for Slack, and as far as I know, .zip files are allowed. So: 

- on Oddball computer, open OCTO Slack > open a DM to yourself > attach files > hit send
- then on CAG, open Slack, open the DM you sent to yourself, download files, add to Sharepoint.

**Comment by joeniquette** [comment]
:facepalm: I cant believe I didnt think about that! I just came into the ticket to update that through support they increased my email attachment limit so I was able to get all the docs over except the zips. Im going to move the zips over via slack and then close this ticket out

**Comment by joeniquette** [comment]
all diagrams backed up to the team sharepoint folder.
