### ISSUE TITLE
Qualitative Data Request: Ch 36/PCPG/25-8832

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78353]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

3/13/2023

### Date Range End

3/13/2024

### Product Name(s)

Chapter 36 (PCPG), 25-8832

### Product Description

Personalized Career Planning and Guidance (PCPG), or VA Chapter 36, offers free educational and career guidance, planning, and resources to Veterans and their dependents who are eligible for a VA education benefit.

### Survey URL(s), key term(s), case category or type

Specific feedback from this page: https://www.va.gov/careers-employment/education-and-career-counseling/
Specific feedback from this page: https://www.va.gov/careers-employment/
Feedback from all pages under: https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832/

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

laura.steele1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
HI, I have shared the requested data. Thank you!
