### ISSUE TITLE
Qualitative Data Request: COE/LGY/26-1880

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78358]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

3/13/2023

### Date Range End

3/13/2024

### Product Name(s)

Certificate of Eligibility (Loan Guarantee) 26-1880

### Product Description

When Veterans want or need assistance getting a home loan, they can request a certificate of eligibility (COE) for a VA loan from the Loan Guarantee Service (LGY).

### Survey URL(s), key term(s), case category or type

Feedback from all pages under: https://www.va.gov/housing-assistance/home-loans/
Feedback from all pages under: https://www.va.gov/housing-assistance/home-loans/request-coe-form-26-1880

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

laura.steele1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Thank you!
