### ISSUE TITLE
Qualitative Data Request: Chapter 31/VR&E/28-1900

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78354]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

3/13/2023

### Date Range End

3/13/2024

### Product Name(s)

Chapter 31/VR&E/28-1900

### Product Description

Veteran Readiness & Employment (Chapter 31), Form 28-1900 form allows Veterans with a service-connected disability that limits their ability to work or prevents them from working helps them explore employment options and address education or training needs. In some cases, the Veteran's family members may also qualify for certain benefits.

### Survey URL(s), key term(s), case category or type

Feedback from all pages under: https://www.va.gov/careers-employment/vocational-rehabilitation/
Feedback from all pages under: https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

laura.steele1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Let me know if you have any questions. Thank you!
