### ISSUE TITLE
PLACEHOLDER WIP | Migrate LGY apps from eBenefits to va.gov

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#7836]
# _View and Apply for Special Adapted Housing Grant_

# _View and Apply for Certificate of Eligibility_

eBenefits URLs: 
- https://www.ebenefits.va.gov/ebenefits/SAH
- https://www.ebenefits.va.gov/ebenefits/coe

**Comment by RudyOnRails** [comment]
heads up @jason-gcio came across this epic when pulling up the main LGY one. looks like it's a double and you may want to close...
