### ISSUE TITLE
Document all custom GA events from MHV landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78362]
### User story

As a Cartographer, I want to document all custom GA events on the landing page, so that the platform team can migrate them appropriately to GA4.

### Notes
- see [slack](https://dsva.slack.com/archives/CE4304QPK/p1710258944850399) for instructions

Possible tasks:
- 

## Acceptance criteria

- Form submitted to Platform Analytics team

**Comment by carlosfelix2** [comment]
Created ticket for the platform team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79041
