### ISSUE TITLE
Intake DB Integration - UserCase Model

### ISSUE THREAD

**Issue by moanu404** [department-of-veterans-affairs/va.gov-team#78371]
We currently have a schema for an Intake user model, that is setup but is not collecting data or adding rows. Now that the Intake IdP integration is complete, we can set up the model to be integrated such that the Login process of the Veteran will create a row in our table with relevant details we would want to capture.

**Comment by lmorris3** [comment]
See data diagram for specific data points to capture.

**Comment by rdvyas** [comment]
ERD:  https://lucid.app/lucidchart/d59e0de9-7c74-4df7-8cf2-2683a22a2e2b/edit?invitationId=inv_5f233044-ccde-4c15-9ec3-3214ff8be07a&page=0_0#

**Comment by SophiaPhilipMO** [comment]
Got green build, will include information in PR. Ready for review shortly for @mateoclarke
