### ISSUE TITLE
Identity Slackbot Post-MVP Features

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#78383]
# Description
List of new features & technical refactors/improvements for the identity-slackbot that we might want to devote further engineering resources towards after its public launch.

## Features
- update `base` modal to include `github_username` field, allowing submitter to include their GitHub username to be tagged in the bot's Github issue
- update `help_details` input to be required on base/other form submissions to ensure some details for every request
- Slack button enabling requestor to mark Github ticket closed
- Slack notification upon Github ticket actions (closure, comments, etc.)
- "Chabot" Automatic replies to keywords in ticket creation base off of VA platform bot:
  > Automatic replies are created when known documentation exists, based on keywords, team, and topic. Replies are sent as a threaded response to the original support request post. Documentation mappings can be found in the responses google sheet. Users can give feedback on the usefulness of the reply by clicking a yes/no button in the reply. The feedback is recorded in a sheet in the responses document.
    - these replies could also trigger off of the form type submitted, and be where we suggest helpful documentation that is available to the requestor long-term, allowing us to pull documentation links out of the form itself

## Tech Debt & Refactoring
- add screenshots of how to use github web client to update Slack modals & Github form templates
- eslint linting added to github pipelines
- add logging (pino?)
- unify slash commands & all slack request handling in [`request-handler` in `/src`](https://github.com/department-of-veterans-affairs/platform-support-slackbot/blob/master/src/request-handler.js)
- define constants from process.env at the start in app.js, error handling if they're missing

**Comment by parkerbees** [comment]
Moved to Jira. Clsing.
