### ISSUE TITLE
Contact Center Review for Cartographers - Personal Health Care Contacts (Profile)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78387]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description

This is an update to the Profile product on VA.gov. We are adding a section to the profile called Personal health care contacts, which presents (for viewing only) up to two Emergency Contacts and up to two Next-of-kin contacts.

### Launch Date
This will be ready to launch around March 20, 2024

### Version Number
Incremented the product guide to v9

### Product Guide
*Please provide product guide link*

Sharepoint: https://dvagov.sharepoint.com/:w:/s/oitmhvonvagovcartographyteam/EZG7UnH-omVKrvLtHsIbgZIBjaviHi2i0OT7SPFiXAL0uw?e=pv7Ykx

### Product Video
*Please provide product video link*
N/A

### Product Video Transcript
*Please provide product video transcript link*
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by wesrowe** [comment]
cc @mtcA6 for awareness/tracking

**Comment by starlow00** [comment]
Beginning review today.

**Comment by wesrowe** [comment]
FYSA, I need you to pause review of the product guide. We just discovered a use case that we want to address and didn't want to waste your time. We'll update when it's ready!

**Comment by starlow00** [comment]
Hi @wesrowe. I'm just checking in to see if your team is still making updates on this before I proceed.

**Comment by wesrowe** [comment]
yes, I need to update. our engineer was OOO so it's been slow to get the screenshots. I will let you know when it's ready.

**Comment by starlow00** [comment]
Moving up a sprint due to product team review of additions.

**Comment by wesrowe** [comment]
Updating Github: I re-submitted the updated guide today.

**Comment by starlow00** [comment]
The draft looks good, and I am sending it to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. Working copy attached.[Uploading... VA.gov.Profile.product.guide.v9.03212024 SRT 03212024.docx]

**Comment by starlow00** [comment]
No changes from VEO. Working copy attached; please use for future revisions. Thank you!
[VA.gov.Profile.product.guide.v9.03212024 SRT 03212024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0lKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79e481f8fc251bc9628cf3be9ed98f480b393ca9/VA.gov.Profile.product.guide.v9.03212024%20SRT%2003212024.docx)
