### ISSUE TITLE
Generate form app e2e tester files

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#784]
## User story
As a VFS engineer building a form app, I want the starter app generator to scaffold the form app e2e test files so I don't have to do it manually.

## Goal
Streamline the process to build and test forms by using the newer form app tester.
Create boiler plate for form app tester.

## Acceptance criteria
The form app generator scaffolds:
- [x] The test JS file
- [x] The test data file

**Comment by brandonrapp** [comment]
@theodur - Just confirming that this is your next step? Run with Cypress for now and spin up a smaller example of it and draft a PR.

**Comment by theodur** [comment]
@brandonrapp That's correct, I will be going off the [current app e2e tester](https://github.com/department-of-veterans-affairs/vets-website/pull/9390) and creating a similar example with Cypress for now.

**Comment by meganhkelley** [comment]
@U-DON is this complete/any validation needed before we close this?

**Comment by U-DON** [comment]
@meganhkelley: This has not been done. The app generator doesn't currently produce a form test template for form apps.

**Comment by U-DON** [comment]
#10631 covers general Cypress tests while this is for form tests.

**Comment by meganhkelley** [comment]
Hey @U-DON is this one (and #10631) complete? Is there any validation needed before we close these?

**Comment by U-DON** [comment]
We're now on the latest app generator (`generator-vets-website@3.4.0`), which generates Cypress tests. I've validated that the correct tests are generated and run successfully.
