### ISSUE TITLE
Adding Adrian Jones to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#78409]
Please add Adrian Jones as a multi-channel user to DSVA Slack channels: vaapi-platform and team-cassowary
work email: adrian.jones@adhocteam.us 

Adrian is joing team Cassowary as the SME on the Lighthouse program

Thank you!

**Comment by LEHigley** [comment]
couldn't add to either channel, invited as multi channel guest but just to general.
