### ISSUE TITLE
Collect Regression Tests from VFS Teams into Regression Test Plan

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#78410]
# Description
Given the scope of the changes to the underlying infrastructure taking place for Preview Environment implementation, we need to cast a wide net of regression tests in order to verify that PEs are producing the desired experience.

## Tasks
1. Examine the available regression tests in TestRail in various VFS project spaces
2. Collect the relevant test cases into a bucket in the [Preview Environment TestRail project](https://dsvavsp.testrail.io/index.php?/suites/view/2617&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=9849)

## Acceptance Criteria
- [x] We have relevant regression test cases available in the Preview Environment TestRail project for our test planning and manual execution

**Comment by pjhill** [comment]
I've collected a few test cases into this Regression bucket in the Preview Environment project --
https://dsvavsp.testrail.io/index.php?/suites/view/2617&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=9849

**Comment by pjhill** [comment]
I think we have a good selection of regression tests available for execution now. Next / last step will be to create a regression test plan out of the selection.

**Comment by pjhill** [comment]
Many of the regression tests borrowed from other teams are out of date. I think the borrowed tests can serve as a good representation of what should be tests, but we will need to rework from of the tests.

**Comment by IGallupSoCo** [comment]
Initial test suite has been created on Test Rail within the Preview Environment project.
