### ISSUE TITLE
IPP - Remove VHIC from list of ID documentation options

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#78415]
**Problem**
We've been advocating for the use of VHIC + secondary documentation under the hypothesis that it could assist Veterans who may not have state-issued IDs. Our VA stakeholders are concerned that it will not meet NIST guidelines to include VHIC as an ID and have asked that we remove it as an option for the pilot.

**User Story**
As a Proofing Agent, I need to see a state-issued identification document when verifying a Veteran's identity so I can confirm the Veteran is the person to whom the account belongs.

**Acceptance Criteria**
GIVEN I have signed into the Proofing Agent application using proper identification
WHEN I am selecting the ID that the Veteran has brought in
THEN I see State issued ID options only 
AND I do not see an option to select VHIC

GIVEN I have signed in to the Veteran-facing intake application
WHEN I am reviewing information on the screens
THEN I see only state-issued IDs as acceptable forms of identification
IF there is a list of IDs that are not accepted
THEN VHIC is on this list
WHEN I receive an email and/or a letter confirming my walk-in appointment
THEN I see state-issued ID as the only type of ID I should bring

- remove references to VHIC on all pages of both the Proofing Agent application and the Intake application
- remove the VHIC drop-down selection from the PA application
- remove VHIC from any materials sent to the Veteran after intake, such as email and letter

**Comment by JKG199** [comment]
The Veteran intake screens have been updated on a new page in [Figma file](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3232%3A5653&mode=design&t=yiYMFvDatdrFHiqC-1) above. The prototype with the VHIC options haven't been touched. Still working on removing VHIC content from the Proofing Agent Flow. Just looping you in here. @SophiaPhilipMO

**Comment by JKG199** [comment]
Updated mockups completed here. [https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3232%3A5653&mode=design&t=0i11skKAfUVWnXjk-1](url)

**Comment by SophiaPhilipMO** [comment]
Reviewed and design is good to go. @lmorris3
