### ISSUE TITLE
Create UI automation to check logins for test environments

### ISSUE THREAD

**Issue by zyellowhorse** [department-of-veterans-affairs/va.gov-team#78429]
Right now there is a large list of test credentials that can be used for test environments which can be found here https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv

Sometimes there are issues where some logins dont work or may not have what you are specifically looking for to test. I am looking to create automation around the va.gov. I will be creating a E2E test framework as well as a way to provide feedback on which logins are working or not.

**Comment by parkerbees** [comment]
Closing this out based on Zac's last comment above
