### ISSUE TITLE
Proofing Agent Data Model Integration

### ISSUE THREAD

**Issue by moanu404** [department-of-veterans-affairs/va.gov-team#78423]
We currently have a schema for a Proofing Agent user model, that is setup but is not collecting data or adding rows. Now that the Proofing Agent IdP integration is complete, we can set up the model to be integrated such that the Login process of the Proofing Agent will create a row in our table with relevant details we would want to capture.

**Comment by lmorris3** [comment]
See data diagram for specific data points to capture.

**Comment by rdvyas** [comment]
ERD Diagram: https://lucid.app/lucidchart/d59e0de9-7c74-4df7-8cf2-2683a22a2e2b/edit?invitationId=inv_5f233044-ccde-4c15-9ec3-3214ff8be07a&page=0_0#

**Comment by moanu404** [comment]
Updatede ERD 
<img width="621" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/137448668/ab752a66-5b91-4ac1-bd77-98a1adb6553d">
