### ISSUE TITLE
[Tech Debt] Refactor claims controller

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#78422]
## Description
The boilerplate backend ticket sorta turned into a "unauth ping" ticket. I (Kevin) made some choices to just put the unauthed ping code under the claims controller index route, which is not where it should live for very much longer.

## Tech Debt Justification
Having the unauth ping code be organized under a structure dedicated to handling claims requests:
* makes it confusing when looking for where the unauth ping should live
* takes valuable and semantically meaningful structure from the claims request handling logic

## Acceptance Criteria
- [ ] When I look at the code, I see a ClaimsController and a PingController
- [ ] The Claims controller is empty
- [ ] The PingController has the unauth ping code in it.

## Demo
- Demoable? No
- How?
- Impact? 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by athifw** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15962
