### ISSUE TITLE
CT-103: Update Institution Profile to Display 103 information

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7843]
As a Comparison Tool user, I need to be informed of institutions that are in compliance with PL115 - Section 103, so that I am aware of any impact in being able to receive my education benefits.

## Assumptions:
1. This work is completed behind the feature flag #7773 
2. The [interactive prototype](https://bahdigital.invisionapp.com/share/7RIADHXPZFD#/screens) is for UI/Layout reference but is overruled by supporting artifact # 2.
3. The "Section 103 data" values referred to are loaded into GIDS in the Sec103 file.

## Acceptance Criteria
1. The "Institution Summary" area of the "Additional Information" section of the institution profile page displays the following line item for Section 103 data: "Protection against late VA payments:".
2. The Comparison Tool institutions are modified based on the business rules below (refer to supporting artifact # 3 for additional details):
  - a. If there is no 103 data for a facility, the institution profile displays 'No information available at this time' text.
  - b. If the 103 data value for “Complies with Section 103” is N, the facility is not displayed in the CT.
  - c. If the 103 data value for “Complies with Section 103” is blank OR the data for “Soley Requirs COE” is blank, the institution profile displays 'No information available at this time' text.
  - d. If the 103 data value meets the following criteria, the institution profile display the 103 text “Requires Certificate of Eligibility (COE) and additional criteria”:
    - Complies with Section 103 = Y
    - Soley Requires COE = N
    - Requires COE & Additional Criteria = Y OR Blank
  - e. If the 103 data value meets the following criteria, the institution profile display 'No information available at this time' text:
    - Complies with Section 103 = Y
    - Soley Requires COE = N
    - Requires COE & Additional Criteria = N
  - f. If the 103 data value meets the following criteria, the institution profile display the 103 text “Requires Certificate of Eligibility (COE)”:
    - Complies with Section 103 = Y
    - Soley Requires COE = Y
3. The user can click on "Protection against late VA payments" and the following content is displayed:

> **Protection against late VA payments**
> If VA payments to institutions are delayed, schools receiving GI Bill benefits must allow beneficiaries to continue attending their classes if they have sufficient proof of eligibility on file.
> 
> Schools may require proof of GI Bill eligibility in the form of:
> 
> - Certificate of Eligibility (COE) **or**
> - Certificate of Eligibility (COE) and additional criteria
> 
> **Schools can't impose late fees, deny access to facilities or classes, or otherwise penalize beneficiaries if VA is late with tuition and/or fees payments.** The restriction on penalties doesn't apply if the beneficiary owes additional fees to the school beyond the tuition and fees that VA pays. Students are protected up to 90 days from the beginning of the term from these penalties.
> 
> Contact this institution's school certifying official to learn more about their policy or [learn more about the Transition Act](https://benefits.va.gov/gibill/fgib/transition_act.asp).

4. The user interface matches the design supplied in Supporting Artifact # 2.

## Supporting Artifacts:
1. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d67739d6bbf5868225ab01c013b69958a6df46f9/products/education-careers/school-comparison-tool/Sec103/design/content/103-content-doc.md)
2. [UI Document - PL 115-407 Section 103 Enhancements 040920.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4461448/PL.115-407.Section.103.Enhancements.040920.pdf)
3. [103_Decision_Table.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4469550/103_Decision_Table.1.xlsx)
4. Sample Data File: [PL 115-407 Sec 103 Compliance Template Final.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4462292/PL.115-407.Sec.103.Compliance.Template.Final.xlsx)

**Comment by delli-gatti-michael** [comment]
To be tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/472

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/641
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/643
- https://github.com/department-of-veterans-affairs/vets-website/pull/12234

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-04-17 at 1.45.58 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/08414115-0735-49ba-a61e-58589d2ff991)

---

![Screen Shot 2020-04-17 at 2.41.13 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/265ac9be-a292-4c13-893e-85c03609d416)

---

![Screen Shot 2020-04-17 at 2.47.19 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/fb7e7801-933d-4638-bfe5-53358fd7c3a8)

---

![Screen Shot 2020-04-17 at 2.51.16 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/18a461de-83e4-4d1a-bb83-65d792a90c8f)

**Comment by delli-gatti-michael** [comment]
### The following schools were added to staging as test data for AC \#2

#### A - “No information available at this time”
- **College of Charleston** 11929140
- **American National University** 21910146

#### B - Should not show IN GIBCT
- **AIM CODE SCHOOL** 35000827
- **BELLEVUE UNIVERSITY** 31001527

#### C - “No information available at this time”
- **BRYANLGH COLLEGE OF HEALTH SCIENCES** 32002927
- **BUTLER PROFESSIONAL FARRIER SCHOOL** 25002527

#### D - “Requires Certificate of Eligibility (COE) and additional criteria”
- **CAPITOL SCHOOL OF HAIRSTYLING & ESTHETICS** 25002227
- **CHADRON STATE COLLEGE** 13900127

#### E - “No information available at this time”
- **COLLEGE OF SAINT MARY** 31802127
- **CONCORDIA UNIVERSITY NEBRASKA** 33000627

#### F - “Requires Certificate of Eligibility (COE)”
- **CREATIVE CENTER, THE** 24000227
- **CREIGHTON UNIVERSITY** 31800127
- **CUSTOM DIESEL DRIVERS TRAINING INC.** 25000727

**Comment by delli-gatti-michael** [comment]
Tested by TestRail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/480

**Comment by delli-gatti-michael** [comment]
@amyknox @ccruzgra @JenLJ 

This is ready for UI/UX Review

**Comment by amyknox** [comment]
This functionality operates as expected across all cases.  Good to go.

**Comment by delli-gatti-michael** [comment]
Changes are live in staging with QA and UI/UX approval. Closing this issue
