### ISSUE TITLE
DR | Contract Documentation

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#78444]
- [x] 1. Create an infrastructure map and annotate it with who owns which pieces, perhaps along the lines of what mobile’s done, e.g. Upstream service map
- [ ] 2. Create a stakeholder map with common reasons for connections (& specific people's names)
- [ ] 3. Create and share a zip file of Google docs/decks/sheets downloaded as MS files, particularly SME discussion notes and docs w/enduring value
- [ ] 4. Update product outline and active initiative briefs
- [ ] 5. Ensure any playbooks for support that exists in non-VA tools, like Google Docs, are transferred into Word and put in Sharepoint or added to the relevant GitHub repo
- [ ] 6. Share recommendations for top backlog tickets that don’t rise to the level of roadmap
- [x] 7. Audit GA Custom Events
- [x] 8. Document any custom scripts or queries that teams run for production support or reconciliation
- [ ] 9. Ensure product guides reflect current functionality
- [ ] 10. Summarize understanding of CaseFlow change questions, top challenges

**Comment by data-doge** [comment]
Documents to be included under Point 3 above:
- https://docs.google.com/document/d/1FDWa9v1ooG4L__RODnAYZtcqCt4La1azTyZ6vkEr6KA/edit
- https://docs.google.com/document/d/1QubK2pAkPKFaEhrFZwslyVgkG3VqUhmWOqj839mDEl0/edit
- https://docs.google.com/document/d/1sdOXRVnT00jNl8tdgjDRKlfmJa2HmR73JM4VyUfw5Kg/edit
