### ISSUE TITLE
Add Rep clientconfig for localhost

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78448]

**Comment by bosawt** [comment]
Here is the config in staging:

#<SignIn::ClientConfig:0x00007fc1029da6f0
  id: 6,
  client_id: "cd51b861ce817f491763eb2f55de8f84",
  authentication: "cookie",
  anti_csrf: true,
  redirect_uri: "http://localhost:3001/auth/login/callback",
  access_token_duration: 5 minutes,
  access_token_audience: "representative.va.gov",
  refresh_token_duration: 30 minutes,
  created_at: Mon, 12 Feb 2024 21:32:59.133091000 UTC +00:00,
  updated_at: Mon, 12 Feb 2024 21:34:26.592460000 UTC +00:00,
  logout_redirect_uri: "http://localhost:3001/representatives",
  pkce: true,
  certificates: nil,
  description: "Accredited Representative Portal Localhost",
  access_token_attributes: [],
  terms_of_use_url: nil,
  enforced_terms: nil,
  shared_sessions: false>,

We want this as a seed on localhost

**Comment by bramleyjl** [comment]
This is covered [in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15944) from @rileyanderson.

<img width="971" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJ6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73cd4197f6a91b789ef983f618cf050bdf92ded4/image.png" alt="image.png" />
