### ISSUE TITLE
Remove the user report of outdated information for Andrew Cornwallis

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78451]
## Background
I demo'd our Find a Rep product and part of that demo was reporting outdated information for Andrew Cornwallis.  It'd be nice if we can delete that report from our records, as it's a false report for demo purposes only.

<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenpoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd25edddacaffdbd6c83947a9cb38d86568edd34/image.png" alt="image.png" />
<img width="511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejNoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0930cf63051e769174991681708fb015907dd632/image.png" alt="image.png" />

## Tasks
- [ ] Remove outdated information report for Andrew Corwallis

## Acceptance Criteria
- [ ] We only store reports of outdated information from real users (not from team testing or demos)

**Comment by oddball-lindsay** [comment]
Holden's request to remove: https://dsva.slack.com/archives/CBU0KDSB1/p1710868269044429

**Comment by oddball-lindsay** [comment]
One additional record to remove (id: 6) 

Context: https://dsva.slack.com/archives/CBU0KDSB1/p1712076742397289?thread_ts=1712074391.082739&cid=CBU0KDSB1

**Comment by holdenhinkle** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1712167837100029
