### ISSUE TITLE
Import Audit Results to State Value

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#78458]
Once the results of the Audit from VBMS in #74482 are in, import them into the `aasm_state` field.

### Acceptance Criteria

- [ ] `aasm_state` field is populated with the latest audit results

**Comment by SamStuckey** [comment]
Closing in favor of State Clean up work https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/85076
