### ISSUE TITLE
Remove suffix fields

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#78478]
The web form contains suffix fields, while the PDF does not. To reduce burden for Veterans, lets not have them waste time entering data that doesn't get transmitted via the PDF

### To do
1. Take out child suffix field from web form
2. Take out spouse suffix field from web form
3. What happens to inprogress forms with this change?

### AC
- With the removing these fields from web form, make sure info from each section makes it across to PDF accurately
- Will require a migration.js change.
- WIll require a schema change.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/78478?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by mjknight50** [comment]
To be combined with #77924

**Comment by aplatt-coforma** [comment]
Combine with the title removal ticket.
