### ISSUE TITLE
Adjust FinancialStatusReportsCalculationsController and services

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#78475]
This ticket is follow on for #76696

76696 revealed places where FinancialStatusReportsCalculationsController and its related services need to change in order to accommodate the data passed in by the FE.

- Add a fixture based on andrew's actual FE request to the calculators
- Write controller specs using this fixture
- Ensure that all related services won't raise errors when top level data is missing

**Comment by HeatherRienks** [comment]
@Dr-Pongo to confirm testing and this can be closed.
