### ISSUE TITLE
Create custom 1010CG 404 Page

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#7848]
## User Story:
The Caregiver team does a ton of manual processing around their paper, and future virtual submissions, and the Caregiver team is worried they will be iodated with virtual submissions. Because of this we want to be able to toggle the form on, and off. As a user when the form is off I want to know how to submit my form via paper when the online form is not available. 

Because of these needs we need to create a custom 404 page when the online 1010CG is unavailable due to lack of man power to manually process forms.

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* When the 1010CG form is turned off for production we would like to see a custom 404 page that instructs the users how to apply using the 1010CG paper form.

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ala-yna** [comment]
Won't do - Public Websites is taking over this functionality (https://github.com/department-of-veterans-affairs/va.gov-team/issues/8853)
