### ISSUE TITLE
Implement un-enrolled use case and update phone numbers for all users

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78486]
### User story

As a user who is not currently enrolled in VA health care, I want the Personal health care contacts page in my VAgov profile to inform me that the page isn't relevant to me, so that I don't waste time trying to get contacts added to my profile.

### Notes

- Content suggestion: "Our records show that you don't **currently** receive VA health care benefits. If you think this is an error, call us at 800-827-1000 (TTY: 711). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET."
- UX suggestion: repeat this content within each of the two cards on the page, EC and NoK
- The above phone number is for the National Call Center, which is the same number that should be provided for updating NoK/ECs in the additional-info component under the H1.
- possible data: `va_patient` or `hasHealthData`
- consider data availability, performance, API teams notification, etc

<details><summary>Screenshot of Profile's content for similar situation w.r.t. education benefits</summary>

![screenshot - don't receive this benefit](https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/67a56fd7-436e-4e18-ab17-132eb00c6d2e)

</details>

Possible tasks:
- Finalize content (see suggestion above)
- Finalize UX
- Determine which user data in the FE should be used to determine whether the user has health care enrollment
- Clarify use case: if a user isn't currently enrolled but was enrolled _in the past_, should we display this same message?
- Inform any back-end team associated with new API requests this feature creates (consult Tom H)

## Acceptance criteria

- Add use case: If a user has no health enrollment, the personal health care contacts page informs them that NoK and EC are not currently relevant to them (unless there is an error in VA's data), and the CTA links to `www.va.gov/health-care/about-va-health-benefits/`
- Update phone numbers: Enrolled users who want to change their contacts are offered the phone number and hours of the NCC instead of MyVA411 – NCC: 800-827-1000 (TTY: 711), Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. [Link to Figma ](https://www.figma.com/file/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?type=design&node-id=143%3A7519&mode=design&t=x57CDCnAWS3iwSJO-1)
- Update hint text for NoK card(s), per design [Mocks in Figma](https://www.figma.com/file/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?type=design&node-id=98%3A5415&mode=design&t=UPiKUzPsOKtreKh7-1)
- Documented use/test cases and runs in TestRail, and possibly markdown if appropriate
- Notified PM to update the Product Guide for Contact Center Review
- a11y review

**Comment by jonathanjnelson** [comment]
Possible solution 

[Link to Figma ](https://www.figma.com/file/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?type=design&node-id=143%3A7519&mode=design&t=x57CDCnAWS3iwSJO-1)

![Screenshot 2024-03-15 at 4 41 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/e9bbbb81-2163-4876-af84-1ab4f2dc62da)

**Comment by wesrowe** [comment]
@jonathanjnelson, can you confirm the link is to `va.gov/health-care/`?

**Comment by jonathanjnelson** [comment]
@wesrowe I think `https://www.va.gov/health-care/about-va-health-benefits/ ` would make the most sense for this situation.

**Comment by jonathanjnelson** [comment]
Slight tweak in Secondary next of kin hint text content: 

![Screenshot 2024-03-20 at 2 08 20 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/bf2cc247-7dce-4a6f-b5d0-2fe0ea93f6a1)

**Comment by wesrowe** [comment]
Update: I didn't find better info on edge cases around whether NoK/EC would be useful for Veterans who aren't enrolled in VA health care (or were at one time, etc). I see this as low risk, as from a UX perspective someone looking at the "Personal health care contacts" is clearly in an area about health care.

If there are use cases for NoK or EC outside of VAHC benefits, then we should hear about it in qualitative feedback.

**Comment by radavis** [comment]
Notes:
- use `CONTACTS.VA_BENEFITS` (resolves to '800827100') in HelpDeskContact component
- update description for 'Other next of kin' in Contact component
- use `va_patient` property to determine if Veteran is enrolled.

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website

**Comment by allanto-ah** [comment]
Environment: staging

1. Verified that if a user is not enrolled, the personal health care contacts page shows the correct message.
2. Verified that users that are enrolled, still see the correct information. 

Filed [80183](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/80183) to address a place where the time frame is not updated
