### ISSUE TITLE
Implement DataDog RUM

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#78481]
## Description
We want to implement DataDog Rum for appointments on va.gov. 

Use this block of code to initialize DataDog RUM:

```
import { datadogRum } from '@datadog/browser-rum';

datadogRum.init({
    applicationId: 'fa7a1075-965f-484d-b812-6f10f4572694',
    clientToken: 'pub4705a09a8da66995fa85908096f42321',
    site: 'ddog-gov.com',
    service: 'va.gov-appointments',
    env: '<ENV_NAME>',
    // Specify a version number to identify the deployed version of your application in Datadog
    // version: '1.0.0', 
    sessionSampleRate: 100,
    sessionReplaySampleRate: 20,
    trackUserInteractions: true,
    trackResources: true,
    trackLongTasks: true,
    defaultPrivacyLevel: 'mask-user-input',
});
```

This should be behind the `va_online_scheduling_datadog_RUM` flag
---

## Acceptance Criteria
Background: the `va_online_scheduling_datadog_RUM` toggle is on
- [ ] DataDog RUM is initialized.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@simiadebowale Closing the ticket. Phase two will be masking the data due to PHI. Ticket to reference [#79492](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/79492).
