### ISSUE TITLE
GA Analytics Tagging

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#7849]
## User Story:
As product owners/developers/designers we want to know how users are using our product so we can fine tune the final product. So we need to add GA analytics tagging so we can track how much time users spend on each page.

Use Data Layers provided by the Analytics team [here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8081)

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* User analytics tags properly appear in the GA dashboard via staging

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
@ala-yna can you link this issue to the issue Platform Analytics will have to do re: your GA and/or Domo dashboard?
