### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by cora-goldston-bah** [department-of-veterans-affairs/va.gov-team#78507]
### Name

Cora Goldston

### Email

cora.goldston@va.gov

### Role

UX Designer

### Team

Veteran Transition Support

### Product Manager (PM) name

Yevgeny Dreyband

### Additional Notes

I am requesting a Figma account because I will be creating Figma designs for the Veteran Transition Support (VTS) project team. After being granted the viewer-only access account, I will comment in this ticket and request editor access.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to cora.goldston@va.gov. Reply here once you've created an account and I can give you full access.

**Comment by cora-goldston-bah** [comment]
Thanks so much, @naomimarcussen! I've created a Figma account using the invite email.

**Comment by naomimarcussen** [comment]
Great! You now have full edit access.
