### ISSUE TITLE
Access for Evan Clendenning 

### ISSUE THREAD

**Issue by eclendenning-va** [department-of-veterans-affairs/va.gov-team#7850]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecelia Lee
- Please provide your name.
   > Evan Clendenning
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >Lighthouse, Software Developer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8u9ItYgnN6wpDET04fD6uDfuDl3rkwN3bhizBPHE7+KMNVu0WMLLqijI9KmGtPRl9BrEVHnFUsuA3jMcwPOut+H9fqjXi9I84B5AlzSNvJW6oJ50T1aV+LnBfyfSX4wt8EfObwyzikQj7TGUVCqnxlyIfifLd7wxcvQZvpCFUaBE5r6V93OnAroDUe0fVHhERC57zxb4hozdP1ciIMXwgdAjjTaXt9v5SgTm83ZQefjqceQbX5GI/H7kyiHNZhU4njiQgkTeo2UBbjUTFJVRTdjDnJNHcwziE0434X05cUKAcZ9sxji7wM+685iOi2VSZFsCKr8PalYj8JlYkx9jd evan@evan-Latitude-3500
```

- [Grant AWS Console access?]
  >  NO

**Comment by eclendenning-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by benniemosher** [comment]
merged and deployed
