### ISSUE TITLE
Expand dsva-vagov-environment-tracking dynamoDB table

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#78512]
Manually adjust the dsva-vagov-environment-tracking dynamooDB table to add the following fields:
- eks-cluster-name
- vets-api-chart-name
- manifest-chart-version
- vets-website-version
- content-build-version
- 

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [x] **Scenario: Expand dsva-vagov-environment-tracking dynamoDB table**
  - Given the dsva-vagov-environment-tracking dynamoDB table is manually adjusted
  - When the following fields are added to the table:
    - eks-cluster-name
    - vets-api-chart-name
    - manifest-chart-version
    - vets-website-version
    - content-build-version
  - Then the table should now include the specified fields

**Comment by Mandalorian-Oddball** [comment]
Ticket is complete. You can verify state by running:

aws dynamodb get-item --table-name dsva-vagov-environment-tracking --key '{"envName": {"S": "SpecificEnvName"}}'
