### ISSUE TITLE
[QA] 10-10EZR TERA: TERA Question E2E testing with VES Team

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#78515]
As a Veteran, I would like to answer the TERA Questions and have them be reviewed by a VA employee so that they can judge whether or not I was exposed to Toxins during my service.

- [x] Connect with the EZ team (Heather) to figure out how to set up and conduct testing (over-the-shoulder testing, etc.)
- [x] Revisit once we've reached out to Heather
- [x] Prepare list of E2E tests
- [x] Schedule meeting with VES team (Alex)
- [x] Run through tests with VES team and make sure data goes through (in this case: a work item is created)
- [x] Complete E2E testing async
- [x] **Success: The team knows that when a Veteran submits an EZR with TERA questions filled out, that information is successfully stored in VES and processed in the way we expect TERA questions to be process (and that if there's no TERA data, no TERA data is stored).**

**Comment by allanto-ah** [comment]
E2E testing has been completed with the VES team on staging and production. 

Staging E2E results can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/TERA%20Question%20Feature%20Documents/10-10EZR-E2E-results-with-VES.md)
