### ISSUE TITLE
Guidance: Sign in widget placement and colors

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#78520]
We figured out our general guidance for sign in widgets, but now we need to 

User story:
- as a designer and dev at VA I want to understand how to place the Sign in Widget on a page (whether my own code or Drupal), where to place it, and how it should be styled. 

ex: should it be at the top or bottom of the page? Under or over which content blocks? And what color should it be? Same for all or different for forms vs tools?

**Comment by mnorthuis** [comment]
Our role in this effort will be to review guidance created by identity team and provide feedback.  Closing this issue since there isn't any direct work.
