### ISSUE TITLE
Augment document upload validations

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#78539]
The following builds upon an earlier investigation – [EVSS::DisabilityCompensationForm::SubmitUploads has exhausted its sidekiq queue](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/74386)

Uploads are performed asynchronously as part of the form 526 submission process, after a Veteran submits their claim. Uploads post to EVSS individually, and an error message is returned to the system for any upload that fails validation. A veteran wouldn't be aware or notified of a file upload failure to EVSS. Thus, it's likely many of the identified error instances have gone unresolved (i.e., some submitted uploads never make it to VBMS and into a veteran's eFolder). Record of a failed upload attempt is identifiable by reviewing ["Submit Form 526 Upload Retries exhausted" query logs](https://vagov.ddog-gov.com/logs?query=%22Submit%20Form%20526%20Upload%20Retries%20exhausted%22%20&cols=payload.job_id%2Cpayload.form526_submission_id%2Cpayload.error_message%2Cpayload.error_class&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&view=spans&viz=stream&from_ts=1701122746499&to_ts=1706306746499&live=true).

Following are contributing factors to `SubmitUpload` errors, ordered by frequency of occurrence as determined from a 10-week sample:
- `EVSS-15004` (file type is not a supported format) errors occur because the file text encoding is **not** UTF-8
  - the corresponding error message also mentions to "Try using a different file type such as PDF (unlocked), JPEG, BMP or TXT."
  - **initially raised as [an issue in June 2023](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60157)**
- `EVSS-15001` errors may be caused by 1 of 18 different validation checks, some of which we have no control over
- `EVSS-15006` (file is corrupted) errors are the result of a corrupt PDF or any unexpected error that occurs when validating a file, the latter of which is beyond our control
  - **initially raised as [an issue in June 2023](https://app.zenhub.com/workspaces/526ez-bugs-and-defects-646e4436ff6787001ac4771a/issues/gh/department-of-veterans-affairs/va.gov-team/60165)**
- `EVSS-15005` (file did not match the file extension) errors occur because an uploaded file's actual MimeType is determined to **not** equal the implied file name based on the extension of the file

All of the following are file upload validations implemented by EVSS:
- pid is valid
- file is not null
- `docType` is not null
- `docTypeDescription` is not null
- `claimId` is not null and must be alphanumeric
- `systemName` is not null
- doc cannot exceed maximum allowed size or be empty
- `BENEFICIARY` is not null
- `SSN` is not null
- `FIRST_NAME` is not null
- `LAST_NAME` is not null
- Error stamping PDF with “Submitted Electronically”
- `ReceivedDt` is not null
- `Filename` is not null
- file text encoding is UTF-8
- `MimeType` must equal the implied file name based on the extension of the file
- PDF is not corrupt

The objective is to implement validations in code prior to the SubmitUploads step to EVSS to decrease/avoid failures moving forward. Beyond the scope of this ticket is determining whether a process can be developed for handling a submitted upload once all retries to send to EVSS have been exhausted, implementing something similar to the backup path utilized by form 526. Also not scoped in this ticket, but discussed elsewhere, is designing a system to both track and provide notice when an upload failure occurs during the asynchronous process.

Two pre-existing tickets have already been created to address some validation errors:
- [Re-encode uploaded TXT files whose content is not valid UTF-8/ANSI](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/78251)
- [Add page size validations](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/77041)

**Comment by freeheeling** [comment]
I conducted some analysis of submissions with EVSS_15006 (file is corrupted) errors. The first thing that stood out, from the dozen of submissions I inspected, was the number of 15006 errors associated with each submission matched the number of uploads with a .PDF extension. Each submission may have had 1 to hundreds of uploads, but a 15006 error seemed to align with the presence of a .PDF extension. Noteworthy, is that .pdf extensions did not appear to result in an error.

Further analysis, after uploading files to an S3 bucket for inspection, revealed that those files with a .PDF extension prompted a popup requesting a password be provided to open the file, whereas those files with a .pdf extension opened in the browser without any issues. 

<img width="276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1QwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f55213533f0a3184d6a9712c1866e11d9bc8a4b1/Screen%20Shot%202024-03-19%20at%203.48.46%20PM.png" alt="Screen Shot 2024-03-19 at 3.48.46 PM.png" />

Each upload in 'form526_uploads' of a submission's form data includes an `is_encrypted` attribute. However, for the few .PDF uploads that I inspected, the boolean value for both was false. It warrants verifying whether at least these few PDFs are or are not password protected. It also may be worthwhile to determine how the `convert_to_unlocked_pdf` method in `EVSSClaimDocument` handles PDFs where the extension is not lowercase.

`normalize_text` in `EVSSClaimDocument` would also be useful in understanding the text encoding errors.

**Comment by freeheeling** [comment]
I believe the issue of **.PDF** uploads being flagged as corrupt when attempting to submit to EVSS is that they are not decrypted prior to being saved to S3, and are therefore inaccessible by EVSS. Given the following early return from [`unlock_pdf` in `FormAttachment`](https://github.com/department-of-veterans-affairs/vets-api/blob/4ad8a64fda22fe78c6ff4127e8924748aed7bfdb/app/models/form_attachment.rb#L39C5-L39C52)

```
return file unless File.extname(file) == '.pdf'
```
the evaluation should be modified to be case-insensitive.

**Comment by freeheeling** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16250) drafted to address case sensitivity of uploaded PDF extensions.

**Comment by sortizsh** [comment]
https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=387-7868&mode=design&t=TfT0TVc2rBuXJ3O8-4

Decision Reviews team just worked on error message for the measurements being oversized.

**Comment by sortizsh** [comment]
@freeheeling here is the work that Robin has been doing on page size https://github.com/department-of-veterans-affairs/va.gov-team/issues/74493

**Comment by freeheeling** [comment]
**To Do:** Create new tickets to address any remaining validations not yet ticketed, and close out this ticket by end of sprint.
