### ISSUE TITLE
Add address type and location mismatch validation & error handling

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#78530]
**Note:** [ticket #67906](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/67906) may be a duplicate of this task.

Work outlined in this ticket references investigative worked performed in [Spike primary path failures: form.submit.establishClaim.serviceError and External service unavailable](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/70892)

**Discovery**
Whenever a claim gets marked as INTERNATIONAL/MILITARY, the claim gets redirected to the Pittsburgh VA office to get worked. When a Veteran lives on a domestic base, they are considered DOMESTIC by the VA, but our code assumes that any AA/AE/AP state address is MILITARY. So when a Veteran enters an address at Camp Lejeune, for example, but with APO/AA for city/state, their submission was redirected to the wrong office.

**Remedy**
A while back, a UI solution was implemented for 686 claims encountering a similar issue. Validation and error handling was added on the FE to catch any mismatch between address type and location, requesting a Veteran enter a city/state, instead of a military PO and state code (e.g., APO/AA), when a domestic zip code is given.

**To Do**
Coordinate with Design regarding updates to the UI and track down tickets related to the work associated with changes to 686 to ideally implement a similar solution that will resolve the occurrence of an 'Invalid Zipcode' error type.

**Resources:**
- [Design system issue addressing the the military base problem
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78252)
- [686 Foreign Base Address Discrepancy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66996)
- [Dex 66996 foreign address discrepancy](https://github.com/department-of-veterans-affairs/vets-website/pull/26200)

**Bonus**
Another type of `form526.submit.establishClaim.serviceError` is 'Invalid City and Military Postal combination', which was raised in 2 instances, where the address `type` was 'INTERNATIONAL', `city` was 'APO' and `internationalPostalCode` was 3 digits (732 for Germany and 916 for South Korea). Most likely, 'APO' is not a city in Germany or South Korea, but it could be in another country, and I'm not sure what attributes are being evaluated and determined to be invalid in this particular situation.

**Comment by sortizsh** [comment]
closing, duplicate ticket
