### ISSUE TITLE
remove terraform output from /environment/global terraform in devops repo

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#78538]
in the devops repo, remove all terraform outputs from the /environment/global terraform.

### Acceptance Criteria
- [ ] Terraform outputs are removed from the /environment/global terraform.

**Comment by JoeTice** [comment]
SPRINT 49 UPDATE - Work was done, and is approved, still needs to be squashed & merged (and TF applied)
