### ISSUE TITLE
Analytics edge case KPI dashboard request for Identity MFA

### ISSUE THREAD

**Issue by joshmatulonis** [department-of-veterans-affairs/va.gov-team#78543]
[Edge Case KPI Dashboard Template - COPY.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14618901/Edge.Case.KPI.Dashboard.Template.-.COPY.xlsx)
# Request an Edge Case KPI Dashboard

## What this form is for

Use this ticket template to request a new edge case KPI dashboard on Domo for your product. Edge case dashboards are for products that fall outside of the scope of our standardized KPI dashboards [Forms](https://va-gov.domo.com/page/447193050), [Content](https://va-gov.domo.com/page/426422632) and [Search](https://va-gov.domo.com/page/1964748112).

If you are unsure what type of dashboard your product qualifies for, please check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739) on Domo.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. Please note that these dashboards will require additional data and design discovery and will take additional time to deliver. You can also reach out for updates on this ticket.

## Instructions for the VFS team

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. For edge cases, we also ask for product outlines or other resources that will help us understand success for your product and define metrics: 

- [x] Make a copy of [this Google Sheet](https://docs.google.com/spreadsheets/d/1TSynjEUrOrm_HfLxb2NAPDXxnn7wyy1bSEb2RruC67Q/edit#gid=0).
  - [x] Fill out product information basics.
  - [ ] If a part of your product involves any sort of linear process/funnel for which you want to be able to measure conversions, please include it in the "Forms" tab of the template.
  - [ ] All other pages associated with your product for which you'd want to track visits and engagement should be added to the "Content" tab.
- [x] Link to your completed spreadsheet here:__attached______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it.
- [ ] Answer the questions in the **VFS-provided information** section below.
- [ ] Add links to the **VFS-provided information** section below.
- [x] Add your team label to this ticket to follow its progress.

### Product questions
Help us understand your product better by answering the following questions:

1. **What does your team consider a completed task?** (_example: clicking submit button)_
2. **Who is your product's main user base?**
3. **Why does your product require an edge case?** _(example: form funnel uses combination of pages and events)_
4. **Does this product currently have a Domo dashboard?** If yes please add link.

### Product resources
Add links to product outlines, feature information, or any other resources you think would help us better understand your product and OKRs below. Feel free to also type background information into this section directly. The more context you're able to provide, the fewer questions we'll need to ask you before getting started!

- 
- 
- 

**Additional info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards.
- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request it here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by Blivaditis** [comment]
Labels:

1. Identity : All Identity related tickets
2. identity-slackbot
3. OCTO-Identity
4. identity-engineer-support : To request engineer support from the Identity team.
5. identity-product-support : To request support from the Identity team's product managers.
6. Identity-Bug
7. identity-ux
8. identity-frontend
9. identity-devops
10. identity-backend
11. Identity-Spike
12. Identity-Support-Requests : Requests that come through support channels that require our team's expertise or time.
13. identity-feature-request
14. OCTO-Identity
15. SSO : SSO Issues for the Identity Team
16. lga-deferred-identity-proofing
17. Request & Support Process : Identity creating processes to help other va.gov teams

**Comment by Blivaditis** [comment]
Dashboard is live ([link](https://va-gov.domo.com/page/680596002?userId=853813555)), closing ticket.
