### ISSUE TITLE
IVC Callback API technical discovery

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#78557]
Acceptance criteria
- The team has sufficient information about how/where to host an API endpoint in the VA ecosystem
- The team has sufficient information about what the calls  need to be for the endpoint and what the payload needs to contain
- Stories are written to implement the endpoint under the same epic as this discovery ticket

**Comment by balexandr** [comment]
Had a conversation with Stever Albers. Essentially using LHDI doesn't make sense for our needs and would be adding unnecessary complexity to a process that only needs to be in va.gov. Also keeping the data (table) in our realm makes changes and customizations much easier to do without relying on a completely other team.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/79920

Updated the ADR. See the PR above.

**Comment by baltes** [comment]
Moving back to in progress to reflect the AC for writing stories.

**Comment by cloudmagic80** [comment]
https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/80349
