### ISSUE TITLE
STEM: Update form 22-10203 submission.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7857]
As a developer, I need to update the new 22-10203 form submission to submit the form type and data as a 22-10203 so that it can capture the reported information accurately.

## Assumptions:
1. This work is completed behind feature flag #7271.

## Acceptance Criteria:
1. The following schema fields are not required:
    a. isPursuingTeachingCert
    b. bankAccount
    c. mobilePhone
2. The form_type of the submitted form is 10203.
3. The form submission is routed to the buffalo RPO#307.
4. Upon successful submission, a summary page is displayed (SA#1) with the following information that matches the layout as specified in SA#2:
    a. [First Name] [Last Name] of applicant
    b. Submission Confirmation Number
    c. Submission Date
    d. Address of Submission Office
5. The applicant can print the summary page (see SA#3 docs for depo documentation) that matches the layout as specified in SA#3d.
6. When multiple benefits are selected:
    a. If CH33 is one of the selected; CH33 is submitted.
    b. If CH33 is not one of the selected; any single one of the selected is submitted.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040835) as of 07/01.
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ac00ddfc52dd101577639d5bdcf25a720a029fbf/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#form-title-apply-for-the-rogers-stem-scholarship-11) as of 07/01.
3. Print Supporting Artifacts:
    a. https://github.com/department-of-veterans-affairs/vets-website/pull/12735/files
    b. https://github.com/department-of-veterans-affairs/vets-website/pull/12882/files
    c. https://github.com/department-of-veterans-affairs/va.gov-team/issues/6723
    d. [Print Preview](https://vsateams.invisionapp.com/share/ATW7AI7QXCV#/screens)
    e. [Print Preview](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/413780135_Caregiver_Confirmation_-_Desktop_-_V-02)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/448

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4483
https://github.com/department-of-veterans-affairs/vets-website/pull/13379

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-08 at 10.34.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e5dfc55f-069f-42c1-a265-fed0fd1d6c3c)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-08 at 10.48.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bf505486-9577-4187-a4e6-75aa8dd9afdb)
##
![Screen Shot 2020-07-08 at 10.48.28 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/79b51e58-2efb-4240-b3d6-61e7c9a7870a)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by JenLJ** [comment]
@sonntag-adam Myself and @ccruzgra have reviewed.  I've been able to successfully test unauthenticated and Cindy has been able to test both authenticated and unauthenticated users.  This should be good to go from a UX perspective

**Comment by sonntag-adam** [comment]
Closing story.
