### ISSUE TITLE
Cancelation Redesign - Alert state 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#78571]
## Description
When the user is trying to cancel their booked appointment or request and the cancelation has failed, the tool will need to alert the user. 

Current alert state: 
![image (10)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/b7870bc3-253f-4d97-ad26-9567141de2f6)
---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

- [ ] Given the user is in the cancelation workflow for a booked appointment
        When the user clicks on `Yes, cancel appointment` and appointment response fails for cancelation
        Then a new page will display an alert message to the user
        And page design matches the [design spec](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2280-135658&mode=design&t=zLTboBi7ujEPzc2X-0)

- [ ] Given the user is in the cancelation workflow for a request 
        When the user clicks on `Yes, cancel request `and appointment response fails for cancelation
        Then a new page will display an alert message to the user
        And page design matches the [design spec](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2280-135754&mode=design&t=zLTboBi7ujEPzc2X-0)

### Design Assets
[Figma file](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2280-135949&mode=design)

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Update copy doc
- [ ] Update Figma file 
- [ ] [Accessibility testing checklist ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/how-to/accessibility-testing-checklist.md)

---

**Comment by Cieramaddox** [comment]
[Alert State Design File](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2280%3A135949&mode=design&t=1ufGWAyNa5XdijjJ-1)

**Comment by ldelacosta** [comment]
I'll validate this. cc: @outerpress @Cieramaddox @melissa-lefevre

**Comment by ldelacosta** [comment]
<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef6ecf15006327f88e0da15ab80b89a0580cc1cb/Screenshot%202024-05-24%20at%2012.28.17%E2%80%AFPM.png" alt="Screenshot 2024-05-24 at 12.28.17 PM.png" />

@vbahinwillit - the request error message is incorrect. Can you take a look?

**Comment by ldelacosta** [comment]
Both use cases have been validated in staging. No issues to report. 

Cancel a pending request: 
<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd01hQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c190a18ba99d060427983f8ab66cd009c23085c/Screenshot%202024-05-28%20at%205.51.27%E2%80%AFPM.png" alt="Screenshot 2024-05-28 at 5.51.27 PM.png" />


Cancel an upcoming appointment: 
<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abd2aba0ba90db81a875153e5691fd700f7faa5c/Screenshot%202024-05-28%20at%205.53.05%E2%80%AFPM.png" alt="Screenshot 2024-05-28 at 5.53.05 PM.png" />

cc: @Cieramaddox @outerpress
