### ISSUE TITLE
[UX/BE] 10-10EZR: Discovery - Attach document discovery

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#78575]
As a Veteran, I would like to attach documents to my EZR so that I can show information, beyond just my DD214, that I incurred toxic exposure in the service. 

**Dev:**
- [x] How to get supporting documentation to VES?
- [x] Is this something that can be done today? Or will is need a VES update?
- [x] If VES update, what is timeframe?

**UX**
- [x] Do we feel we can explain this to Veterans? Including the vagaries of the document types?
- [x] Is there somewhere else (e.g. 526) that we explain this, or something similar, that we can leverage?

**Alex--originally email March 7, follow-up Mar 18**
- [ ] What are HEC seeing in terms of volumes of EZR with TERA?
- [ ] What are HEC seeing in terms of supporting evidence for TERA with paper forms?

**Success:**

1. We know if, and when, we can send document attachments to VES
2. We feel comfortable that we can, or cannot, explain this to Veterans
3. We understand the EZR mail volume since TERA launch, and if possible, how often TERA supporting evidence is included in those mail-in forms

[TERA FAQ](https://www.va.gov/HEALTHBENEFITS/resources/publications/10-1745_Toxic-exposed-Veterans.pdf)

**Comment by JoshingYou1** [comment]
After confirming with Josh Faulkner, VES is able to accept attachments. We would use the same format as the EZ.

**Comment by emily-brown34** [comment]
@alexseelig

**Comment by alexseelig** [comment]
I have a request in to Shana and Jessie Soza for EZR paper volume numbers. Haven't had any luck so far. Let's see if they have them in the next week or so, otherwise we can close out this ticket.
