### ISSUE TITLE
Publish resident rates

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#78576]
## Description
We may need to publish updates to the resident rate information on these modern pages:

- [GI Bill® School Feedback Tool](https://www.va.gov/education/submit-school-feedback/introduction)
- [In-state tuition rates under the Veterans Choice Act](https://www.va.gov/resources/in-state-tuition-rates-under-the-veterans-choice-act/)

To determine if updates are needed, education service stakeholders will compare the modern pages above to this legacy page:

- [GI Bill Resident Rate Requirements](https://www.benefits.va.gov/gibill/post911_residentraterequirements.asp)

### Step 1: Review
- [x] Stakeholders: Review the 2 modern pages alongside the legacy page to determine if updates are needed

### Step 2: Update, if needed
~~- [ ] DB: Draft updates in Drupal~~
~~- [ ] AP: Review updates~~
~~- [ ] DB: Share updates with stakeholders~~
~~- [ ] Stakeholders: Review updates~~
~~- [ ] MZ, ST: Copyedit and publish~~

### Step 3: Redirect
- [x] DB: Work with IA to open a redirect ticket

Redirect these legacy URLs:

- www.benefits.va.gov/gibill/417.asp
- www.benefits.va.gov/gibill/post911_residentraterequirements.asp

To this modern URL:

- www.va.gov/resources/in-state-tuition-rates-under-the-veterans-choice-act/

## Criteria
- [x] Stakeholders reviewed legacy and modern pages to determine if updates are needed
~~- [ ] Updates were published to modern pages (if applicable)~~
- [x] IA opened a redirect ticket for the legacy URLs

**Comment by d-beyer** [comment]
Update: Tammy has confirmed that the current content is accurate and sufficient. No updates are needed.

**Comment by d-beyer** [comment]
Update: I requested these redirects through Jenny Mayo.
