### ISSUE TITLE
10-7959f-2: Create form directory in front end repositories

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#78580]
As a product owner, I want to see the form basics generated for [10-7959f-2](https://www.va.gov/find-forms/about-form-10-7959f-2/) so that the rest of the form can be built out.

- Generate form skeleton using Yeoman generator
- Make tweaks to generated code as necessary (can skip Introduction and Confirmation pages for now)
- Create vets-website pull request for platform approval
- Create content-build pull request for platform approval
- Merge pull requests

**Comment by reiting** [comment]
This has been placed in PR for platform review.

**Comment by reiting** [comment]
So, vets-website is good to go here, however, they are having some issue upstream on content-build. I can't merge there yet, but once they figure it out, I will. @marywang2 should we place this in blocked for now?

**Comment by marywang2** [comment]
Yes I moved to blocked, thanks @reiting.

**Comment by reiting** [comment]
@marywang2 this PR has been merged. It's just the one for content-build that adds it to the register.json, so not really something to review probably. But it is merged and hopefully good to go!
