### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by AndrewGrayVBA** [department-of-veterans-affairs/va.gov-team#78594]
### Name

Andrew Gray

### Email

andrew.gray@va.gov

### Role

VBA Business Strategy

### Team

Office of Automated Benefits Delivery

### Product Manager (PM) name

Julie Strothman

### Additional Notes

Figma access needed for work in the claim status tool space

**Comment by naomimarcussen** [comment]
An invite has been sent to andrew.gray@va.gov.
