### ISSUE TITLE
SSOe UAT Test Plan

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7860]
Propose UAT/beta testing approach for SSOe launch.

**Comment by marriej** [comment]
3/26/20: @bridgethapner  started a research plan for UAT/usability testing session for Outbound SSOe here (work in progress):
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/SSOe-testing-plan.md

**Comment by bridgethapner** [comment]
Finished adding the minimum 6-8 tests that could be run to verify SSOe for each credential type. 

@marriej Am thinking we could post in the #va-adhoc channel to see if we are able to recruit a couple more folks to test - what do you think?
