### ISSUE TITLE
VFS Custom Events for Identity-Team

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#78610]
# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- _(If using the Google Sheet, you can link that here:_ _____).
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by johnny-jesensky-adhoc** [comment]
@asg5704  - Sounds good - feel free to keep this open, and just attach when it's ready. Thanks!

FYI @jestutt

**Comment by ianmagenta** [comment]
Hi @johnny-jesensky-adhoc - You can find the completed spreadsheet here: https://docs.google.com/spreadsheets/d/1xsAgO_5FSS-o7vFy6p2YmC2aqv3w62v2YVYz9FK_swA/edit?usp=sharing

CC: @asg5704

**Comment by johnny-jesensky-adhoc** [comment]
@ianmagenta - Excellent - thank you Ian! Confirming we can access the spreadsheet. We'll reach out if we have any questions.

FYI @jestutt, @asg5704

**Comment by asg5704** [comment]
Sounds good. Also you can consider the Identity team's GA4 conversion a low-priority since we will be removing GA once our Datadog browser integration goes in.

**Comment by johnny-jesensky-adhoc** [comment]
@asg5704 - Got it, do you know the exact timing on when that will happen? Also, if possible, we'd like to use this ticket to track our own work around this - is it ok if we reopen? We can remove your team's labels if that would be preferred.

If not, (or if throws off your team's reporting), I'm happy to just duplicate this. Let me know.

FYI @jestutt, @ianmagenta

**Comment by asg5704** [comment]
@johnny-jesensky-adhoc Yes, please re-open I'll yell at my PMs 😓 I've already removed Identity + Identity-frontend labels

The PR is already open but has yet to be merged. When it is merged we'd like to get at least a week to compare metrics between Datadog and GA. We will let your team know once we're ready to remove GA4.

**Comment by jestutt** [comment]
@asg5704 Can you please provide edit access for the file to jamie.stutt@oddball.com, blivaditis@thesocompany.com and christine.young@adhocteam.us? 

cc @johnny-jesensky-adhoc

**Comment by asg5704** [comment]
@jestutt sure thing. I just updated permissions for edit access. Can you confirm?

**Comment by jestutt** [comment]
@asg5704  Confirmed. Thank you!

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  This ticket is going to carry over -- tried to do something fancy that just wasn't working and had to scrap in order to publish the other events for this sprint.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for the update @jestutt -- think this ended up being our only carry over. We'll just have this at the top of our custom event queue for the sprint that started today.

FYI @jwoodman5, @davidconlon
