### ISSUE TITLE
Publish VET TEC providers list page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#78623]
## Description
First, we need to publish a new resources and support page to migrate the content on this legacy page:

- [VET TEC Training Providers](https://www.benefits.va.gov/gibill/fgib/vettectrainingproviders.asp)

Then, we need to update the link destination and text on these modern pages:

- [Veterans technology education courses](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/)
- [Apply for Veteran Employment Through Technology Education Courses (VET TEC)](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction)

### Step 1: Publish
- [ ] DB: Draft new resources and support page in Drupal
- [ ] AP: Review
- [ ] AP: Share with BP
- [ ] BP: Review
- [ ] DB: Share with stakeholders
- [ ] Stakeholders: Review
- [ ] MZ, ST: Copyedit and publish

### Step 2: Update Drupal page
- [ ] DB: Update the VET TEC page in Drupal
- [ ] AP: Review update
- [ ] MZ, ST: Copyedit and publish

### Step 3: Update product page
- [ ] AP: Identify the product owners of the VET TEC online application
- [ ] DB: Ask the product team if the legacy page is linked in the form flow or just the form intro page
- [ ] DB: Share new link destination and text with the product team

### Step 4: Redirect
- [ ] DB: Work with IA to open a redirect ticket

Redirect this legacy URL:

- www.benefits.va.gov/gibill/fgib/vettectrainingproviders.asp

To the new resources and support page URL.

## Criteria
- [ ] Published new resources and support page
- [ ] Updated link destination and text on VET TEC page
- [ ] Shared updated link destination and text for VET TEC application
- [ ] IA opened redirect ticket

**Comment by d-beyer** [comment]
Update: Beth confirmed in a meeting that this page is no longer necessary since the VET TEC program is ending.

**Comment by d-beyer** [comment]
Update: Since this program is defunct, I updated the task description and requested that Jenny Mayo have this page redirected.

**Comment by aprocik1** [comment]
Update: Based on SME feedback, we won't redirect this page until September 30, 2024.
