### ISSUE TITLE
Accessibility Testing for Identity, Terms of Use

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#78643]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

claytonzook

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [X] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

Seems like the Colorblindly extension for Chrome, mentioned in the instructions here, isn't currently working :( 
Otherwise no issues

### Who completed the axe scans?

claytonzook

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### axe DevTools scan results

0 issues found

### How did axe testing go?

Following the steps was very helpful - it's been a long time since I've done this test.

### Who completed the content zoom and reflow test?

claytonzook

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### Who completed the keyboard navigation test?

claytonzook

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

it's a pretty hierarchical page, so straightforward to test

### Do you have any other results to share?

I did some screen reader testing on this page. 
When quick testing on mobile - with text zoom the action link element near the top of our page to "sign in" the arrow overlaps text - but I'm noticing it also does the same when zooming on mobile on the [VA DS action link page](https://design.va.gov/components/link/action), so perhaps an issue with the DS?
Same thing for mobile zoom and [the warning alert element](https://design.va.gov/components/alert) near the bottom of our page

**Comment by parkerbees** [comment]
move dot jira, closing
