### ISSUE TITLE
LIgov / IDme: "Register" alert for newly verified credential users

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78641]
### User story

As a Veteran who just verified a new login.gov or ID.me credential, I want the MHV landing page to explain to me that I should "register with My HealtheVet" in order to access my Medications, Medical records, and Messages.

**Screen shot**
<img width="788" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/d92ef5eb-95a2-418b-a5d4-70ab608111bd">
### Notes
- This is the highest value of our needed credential alerts
- [Slack discussion](https://dsva.slack.com/archives/C0581MN69TJ/p1710350862411339?thread_ts=1710344579.615889&cid=C0581MN69TJ) with (among others) Patrick and Mikki

### Background / Related artifacts:
- This "registration" step will no longer be necessary after the Account Creation API is implemented (date unknown)
- Design and flow logic in [Figma](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=894-26695&t=Apyo6iaQWwsjZT1n-4) 
- Wes's [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713801267327/7599ddb1d5475a75d99332b2ecba253c9b0d2684?wid=0-1715699863487) depicting the three alerts and rationale

Possible tasks:
- [x] Work with CAIA to update content; make updates in [Figma file](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=715-9569&t=tgRfiuwBS7dEaPeR-4)
- [ ] Carefully name this something clear in the codebase that won't be confused with the other meaning of "registered" in the codebase (associated with a facility)
- [ ] Dev discovery to figure out how to determine whether accounts are registered with the MHV-API or not
- [ ] Implement alert for these users: 
  - LOA3 users who are **not registered** with the MHV-API
- [ ] QA: document in TestRail, and consider documenting in markdown/GH as well

## Acceptance criteria

- [ ] When the MHV landing page detects that a user's Login.gov or ID.me credential is not associated with an MHV account, a conditional alert as designed directs them to "Register" with MHV Classic (log into MHV Classic to create that association) at: `https://www.myhealth.va.gov/registration`
- [ ] No tools are hidden; the regular landing page content is still visible for this user (as rendered in Figma)
- [ ] UX review
- [x] Documented test cases and run in TestRail
- [x] QA review
- [ ] a11y review

**Comment by wesrowe** [comment]
@carlosfelix2 (and team), note that I did some thinking about sequencing, and I believe this alert story can/should be implemented first (of the three) and can be released by itself, as it's valuable to Veterans by itself and helps all three credential types.

**Comment by sterkenburgsara** [comment]
@jzucadi following [new information in this Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1717163859467739), the content for this alert is incorrect and I have moved this ticket to blocked. I will sync with content and our PO Patrick Bateman next week to ensure that we have accurate logic around which backend systems require MHV-API account pairing for access, and will update the content to reflect the accuracy of that information once we have it. // cc @wesrowe @LynneJohnson224

**Comment by wesrowe** [comment]
It [appears (slack thread)](https://dsva.slack.com/archives/C0581MN69TJ/p1717439174979839?thread_ts=1717185477.450519&cid=C0581MN69TJ) that the logic for this alert needs to be more narrow – this alert is only necessary for a user who does not yet have an MHV account _at all_. And the action is not "pairing", but rather "registering" (i.e., creating).

**Comment by sterkenburgsara** [comment]
Update: [posted this slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1718659625394319) to get OCTO stakeholder opinions on whether or not implementing on the landing page in and of itself is a full solution. Not sure if we should do this as a first pass, and implement fast-follow solution to solve for users who may come in via side-doors later?

**Comment by sterkenburgsara** [comment]
**Update**: From the Slack conversation (link in comment above), it sounds like there is buy-in to launch this alert within the full, regular landing page design. Any UX improvements to that concept can be made as follow-ons later after this initial implementation.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the "Register" alert appears for users that are verified, but do not have an associated MHV account. Also verified that when users do have an associated MHV account, the "Register" alert does appear. Have also verified that registering a verified user to have a MHV account, the "Register" alert is removed as expected (on staging there was a couple minutes of delay, so I'm not sure how immediate it is in production). Unverified users do not see the "Register" alert.
