### ISSUE TITLE
User flow diagrams

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7865]
Document user flows for sign up & sign in with all 3 credential types

**Comment by bridgethapner** [comment]
Planning to create flows for: 
- Sign In 
- Sign Up 
- Verify Identity (per Damien, the 10-minute clock affects this flow as well. Context: https://dsva.slack.com/archives/CHPA76VV5/p1586871589099000?thread_ts=1586359065.070900&cid=CHPA76VV5)  

Work in progress for **Sign Up**: ![ID.me Sign In Flow.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/46d12b77-3baf-4249-b1c6-74e693bb36e8)
