### ISSUE TITLE
Analytics Implementation or QA Support for [Virtual Agent Chatbot - Claims Status Feature]

### ISSUE THREAD

**Issue by anhansma** [department-of-veterans-affairs/va.gov-team#78656]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Virtual Agent Chatbot Team

- **Poduct Name**

    - Chatbot
      
- **When is the launch date?**
    - [4/11/2024]

- **Provide the link(s) for Product/Page urls**
  
    - https://www.va.gov/contact-us/virtual-agent/

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_

    - **Sessions successfully signed into our claims skill feature**
    
        a. Clicking `start chat` on the chatbot
        b. Type in trigger phrase "claim status"
        c. Click "yes" and sign in to account
        d. User receives message "This chatbot can only give you status information on disability compensation claims."

    - **Unique users who successfully signed into our claims status feature**
    - **Redirects to the _VA claim process after you file a claim_ after clicking a link displayed in a message from our chatbot**
        - After signing into the claims status feature, the second message received has a link to [VA claim process after you file a claim](https://www.va.gov/disability/after-you-file-claim/). We would like to track anytime this link is used. 
            
          ![Screenshot 2024-03-18 at 12 50 25 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/28b0b472-5b94-4518-b49f-058386c29dbc)

    - **Any button that is clicked from the claims status feature**
        - If user only has one claim:
          ![Screenshot 2024-03-18 at 12 54 58 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/fa58485e-b467-495a-8a86-d09c44697e3e)
         - If user has multiple claims:
           ![Screenshot 2024-03-18 at 12 52 22 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/77005e1c-b51e-485e-8f3d-7b3931793ccc)

           ![Screenshot 2024-03-18 at 12 54 00 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/393b40dd-dc64-42ef-b560-62d4e83669d9)

    - **Buttons clicked at the end of the flow to gauge whether the user had to further contact the VA for more information.**
        <img width="293" alt="Screenshot 2024-03-25 at 7 00 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/9555713d-d784-46af-9f8c-5b859e5ca957">
        - Desktop:
          <img width="284" alt="Screenshot 2024-03-25 at 7 02 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/c919c0e0-0dd1-4a68-9c7a-b1cb12f734e3">

        - Mobile:
        <img width="288" alt="Screenshot 2024-03-25 at 7 02 31 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/132290531/4f0da13c-d165-4b30-a20c-02ff60e9f21f">

    - **Redirects to the Claims Status Tool after clicking a link displayed in a message from our chatbot**
        -  After signing into the claims status feature, the last message received has a link to the [Claims Status Tool](https://www.va.gov/claim-or-appeal-status/). We would like to track anytime this link is used. 
    - **Redirects to Ask VA after clicking a link displayed in a message from our chatbot**
        - After signing into the claims status feature, the last message received has a link to [Ask VA](https://ask.va.gov)

    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - •	**Important** You must login through the chatbot, meaning you trigger a topic which will then tell you need to login to view this information. If you try to login with the sign in button on the site, it will use Oauth which is not setup to work with chatbot yet. You must login using the SAML method of authentication.
•	Navigate to chatbot with path /contact-us/virtual-agent. Be careful navigating with the links on the page because sometimes they will route you to the prod link and not dev or staging. 
•	Get passwords from test user dashboard, go to https://tud.vfs.va.gov/ (only accessible on GFE)
•	User logins:
o	All emails have format of vets.gov.user+{number}@gmail.com
o	+14 works in staging, not dev, has multiple claims and has ratings.
o	+35, +54 works in dev, not staging, only has one claim
o	+8, +4 works in dev, only has one claim
    - Testing in staging:
-	This is the preferred place to test as it is more stable, and ratings doesn’t actually work in dev anyways. O.O
-	Staging data should be coming from lighthouse, not the mock data repo
-	Steps:
o	Go to https://staging.va.gov/
o	Navigate to chatbot, trigger topic using same trigger phrases as for dev, ‘chatbot claims dev’ and ‘chatbot ratings dev’
o	Login using ID.me method
o	You should be routed back to the chatbot and start to see responses.
- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jestutt** [comment]
The custom events used for chatbot tracking are mostly templatized but those templates are in the process of updating as part of  #93539. Once we're sure of the new templates, we'll update here. 

cc @johnny-jesensky-adhoc @Blivaditis

**Comment by jestutt** [comment]
@anhansma  There are a number of default Chatbot events 
- Skills Entry is an `api_call` dataLayer event that is under the **api_call** event in GA4
- Button clicks are a `chatbot-button-click` dataLayer event that is under the **chatbot** event in GA4
-- the button text can be found under **Link text** 
- Link clicks are a `chatbot-resource-link-click` dataLayer event that is under the **chatbot** event in GA4
-- the link text can be found under **Link text** 

Staging Explore report -- Chatbot Events by Skill 
- Tab 7 are all the chatbot events related to the Claims skill 
- The API Call event that measures the skill entry will start to show up soon -- it was just added in GTM

The only two interactions I could find in GA or test myself is the phone numbers buttons at the end - they didn't load for the Chrome emulator. Do you have a way to get those to load so you can click on them? 
![Image](https://github.com/user-attachments/assets/37d8084a-d4e2-453b-9f09-ffe3450fc60a)


@johnny-jesensky-adhoc This ticket will continue into the next sprint as we try to confirm those phone number buttons.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @anhansma -- following up on Jamie's question, which was in her latest comment.

>" _The only two interactions I could find in GA or test myself is the phone numbers buttons at the end - they didn't load for the Chrome emulator. **Do you have a way to get those to load so you can click on them?**_"

Can you help us with this?

FYI @jestutt

**Comment by johnny-jesensky-adhoc** [comment]
Moving our final validation to [this separate ticket,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96619) which we're continuing next sprint.

FYI @jestutt, @anhansma
