### ISSUE TITLE
BUG: PCI is showing both the Clinic Stop Code Name and the Patient Friendly Name

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#78662]
## Task
Remove the type of care in day-of and pre-check-in so that it just shows the fallback value of `VA appointment` at all times.

## Issue
PCI is showing both the Clinic Stop Code Name and the Patient Friendly Name.  This Veteran has a concern with the Clinic Stop Code Name showing too much information about the exact nature of the appointment.  Based on the attached wireframe it looks like it should be showing Type of Care (if available) where the Clinic Stop Code Name is being used.  If Type of Care is not available I think it should show something like `VA Appointment`.   Let me know if this is not the case or you need more info.  Here is additional context:

## Screenshots
Here is a copy of what the veteran shared with us.   The veteran was concerned about the name of this clinic, however we don’t have that listed as the name of the clinic.  That information is the stop code definition used for this clinic.  Let me know if you need anything else.

 BHM - 521
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/885fa215-323f-4330-a3f4-1894ec1413c2)

 ## Code Info
[here is where the Stop Code Name is set in PCI codebase](https://github.com/department-of-veterans-affairs/vets-website/blob/efb684a9e9de31a527261959bbf23f5614c777e6/src/applications/check-in/components/AppointmentDisplay/AppointmentListItem.jsx#L87)

Here is the clinic data for the example screenshot in this thread (from here, search for text to find):
{
    "vistaSite" : 521,
    "clinicId" : "15509",
    "serviceName" : "BVC-WH-FLOAT-CRNP 01",
    "friendlyName" : "SUSAN CAMP CRNP WOMENS HEALTH",
    "medicalService" : "NONE",
    "physicalLocation" : "BHAM ANNEX",
    "phoneNumber" : "205-933-8101",
    "stationId" : "521GJ",
    "institutionId" : "521GJ",
    "stationName" : "Birmingham VA Clinic",
    "primaryStopCode" : 322,
    "primaryStopCodeName" : "COMP WMS HLTH GNDR DIVERSE PC",
    "secondaryStopCode" : 185,
    "secondaryStopCodeName" : "NURSE PRACTITIONER",
    "appointmentLength" : 30,
    "variableAppointmentLength" : true,
    "patientDirectScheduling" : false,
    "patientDisplay" : false,
    "institutionName" : "BIRMINGHAM VA CLINIC",
    "institutionIEN" : "15340",
    "institutionSID" : "1200100151",
    "timezone" : {
    "timeZoneId" : "America/Chicago"
    },
    "futureBookingMaximumDays" : 390
  }

**Comment by brianseek** [comment]
@loripusey this has been merged and is ready to validate locally on `main` now and will be on stage and prod soon

**Comment by loripusey** [comment]
@loripusey
