### ISSUE TITLE
[DevOps] Document the ePAS/AWS access process for CIE.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#78661]
## User Story
As an engineer, I want to document the ePAS/AWS access process to keep people from suffering the way that I did.

## Tasks
- [x] [DevOps] Add a document in our project folder covering this process before I forget.

## Acceptance Criteria
- [x] This process is documented and I can just link future sufferers to it instead of having to relive the experience.

**Comment by ndouglas** [comment]
I created a [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/team/onboarding.md) covering my experiences and learnings as of March 19. I'll need to add to it, though, as I continue through the process.

**Comment by loripusey** [comment]
@ndouglas I'm assuming this one is blocked, I'm going to move it out of the sprint for now, unless you are not blocked

**Comment by ndouglas** [comment]
I've validated that I have working AWS access and appropriate groups, so I concluded my documentation yesterday and this is good to finish.
