### ISSUE TITLE
CF: Clicking View details below on profile page caution flags does not shift focus for screen readers

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#7867]
On the profile page for any school with caution flags, the title of each flag is listed at the top of the page along with a link to "view more details". Clicking this link results in the page scrolling down to the "Cautionary information" section where there are more detail on the caution flags. If a screen reader is running, however, the screen reader's focus remains on the link. Attempting to use the screen reader's controls to read the cautionary information sections results in the focus jumping back to the top of the page to the element directly after the "view more details" link.

This occurs in all browsers _except_ Internet Explorer 11 (yes, you read that right)

![Screen Shot 2020-04-10 at 1.00.13 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ef24b72d-cd5e-49a3-88b7-4d32b2477725)

1. With a screen reader running, access and profile page with caution flags (https://staging.va.gov/gi-bill-comparison-tool/profile/14900416)
2. Tab to the "view more details" link and press enter
3. Attempt to use the arrow keys to navigate the content in the Cautionary information section

### Acceptance Criteria
1. When clicking (or pressing enter) on the view more details link, the screen reader's focus should shift to the "Alerts from VA and other federal agencies" header in this section
2. Using the arrow keys to navigate further down that page should shift focus to the first caution flag

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12202

Can be tested on vets-website branch `caution-flag-focus`

**Comment by delli-gatti-michael** [comment]
local testing complete
