### ISSUE TITLE
DISCOVERY WORK: Google links for Research and Design

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#78672]
- Do discovery work on who is the SME and what it will take to get rid of google links on the following 4 documents:

- [Synthesize and share](https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesize-and-share)
- [Successful screener questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions)
- [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)
- [Research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)

**Comment by jknipes** [comment]
Discovery work to identify SME and gauge the work necessary has been completed. Moving to _Done_
