### ISSUE TITLE
Change google link in Accessing Internal Tools (via SOCKS Proxy)

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#78674]
- [x] Edit Accessing Internal Tools (via SOCKS Proxy) to get rid of the google link.
- [x] Deploy Accessing Internal Tools (via SOCKS Proxy)

## Acceptance Criteria

- [x] Accessing Internal Tools (via SOCKS Proxy) no longer as the google link and has been deployed.

**Comment by jknipes** [comment]
Work has been completed, moving to _Done_
