### ISSUE TITLE
Review Implementation of Lighthouse API to IVC forms

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#78681]
As a stakeholder who is monitoring the performance of the IVC forms, I would like to know the status of the submitted forms. Lighthouse has a related solution in using their service for this. We need to know if lighthouse can interact with PEGA's system.

**Comment by baltes** [comment]
I'm going to close this one out, it'll be handled by https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/78554
