### ISSUE TITLE
SPIKE: Are there differences between stand-alone travel for OH & Vista

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#78698]
## Tasks
- Determine if there are differences between stand-alone travel for OH & Vista from a front-end user perspective

**Comment by benbrasso-agile6** [comment]
@cgednalske I'll take this for now, but might reassign to you. or we can collab.

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park @loripusey this is ready for validation. 

So, this is basically a copy of the userflow you guys did for adding eligibility into the OH userflow - https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711130372680/af42986654957f5cb47bf421ff89909c5595ecae?sender=u37bb983bd3fc3cc00c7d3286

It's really a copy. My process was to simply go through the OH userflow and look for nuances that might need to be considered if it was introduced into VistaA sites. And, there aren't any. 

Of course, we may later decide to change certain content in eCheck-in, for example, to allude to the ability to text "travel," but I wouldn't deem these as MVP, they're things we can deliver to Veterans later. 

@cgednalske I'm going to create that ticket I mentioned about creating a presentation-ready version of adding eligibility to OH or VistA (whatever we think is best to present) for VTP, and link this Mural in the ticket. Feel free to build off of and reference this as needed.
