### ISSUE TITLE
Remove UserCreator

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#78697]

**Comment by bosawt** [comment]
I just wanted to test this to see what could happen. The story is prob named wrong, we can't remove `UserCreator` the class, but we can remove the user creation inside of it.

Looks like we can successfully remove `create_authenticated_user`, and all related functions in that class that are no longer used, and then combine `UserCreator` and `RepresentativeUserCreator`, as they should be the exact same, then finally perhaps name the class something new that represents the new functionality (not exactly sure what, maybe `UserCodeMapCreator` is good enough)
