### ISSUE TITLE
Prevent MHV and DSLogon options for rep flow

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#78699]
SiS should only provide ID.me and Login.gov options

**Comment by bramleyjl** [comment]
This is covered [in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15944) from @rileyanderson.

<img width="1040" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC96QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8a0d3d1c989ced3e30d1bb43e694b06efd4350c/image.png" alt="image.png" />

**Comment by bosawt** [comment]
can we confirm that dslogon/mhv is actually prevented? It doesn't show up in the USiP, but I bet if you called SiS directly it would still work.

We have to decide if we want to add this functionality in SiS right now to block certain CSPs (would have to be a client config), or if there is a simpler way to block it for now

**Comment by bramleyjl** [comment]
I'm looking into how simple it will be to update the SiS authentication process to block CSPs based on client config. If it's too much I can add it to the Representative Attribute Validator #78001.

**Comment by bosawt** [comment]
Client Config two new fields:
- list of allowed CSPs
- list of allowed acr values (ial1 ial2 loa1 loa3 min)

Then '/authorize' can check the input CSPs and ACR, and see if they're in the list

**Comment by bramleyjl** [comment]
PRs to create validation of requested CSP type & ACR are in review; once the feature is merged I'll update the ARP ClientConfig to use the new feature to prevent MHV & DSL logins.
