### ISSUE TITLE
CF: JAWS w/ Edge: Search Results: Last caution flag in list is skipped 

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#7869]
In the screenshot below JAWS on Edge it skips the last bullet and goes straight to DODGE CITY, KS.

![Screen Shot 2020-04-10 at 12.56.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/84afa364-ab38-4401-9894-3b33d3ac1ced)

**Comment by ksantiagomorgan6** [comment]
Reached out to @1Copenut , looks like this version of edge is not a preferred browser to be used with JAWS and is not being tested. IE11 and chrome are the preferred browsers for JAWS.

**Comment by 1Copenut** [comment]
Concur. Right now Edge is not on the short list of best browsers for screen readers. We're hoping to try out Edge Chromium soon to see how well it works with JAWS.

**Comment by sonntag-adam** [comment]
Closing bug per comments above.
