### ISSUE TITLE
[UX] [Design] SPIKE: Determine where we should keep our content in relation to components

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#78703]
## Tasks
- Determine where we should keep our content in relation to components

**Comment by zach-park** [comment]
Here is the summary that came out of the SPIKE:

FORMAT
- Table

Location
- Figma for content including components and guides that stakeholders can reference.

Action item: Test out two types of contents
- Accordion 
- SMS text

**Comment by benbrasso-agile6** [comment]
LG. Creating follow up ticket now.
