### ISSUE TITLE
CF: AXE Error on profile page: Heading levels should only increase by one 

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#7870]
Running an axe analysis of the profile page for any institution with caution flags results in a `Heading levels should only increase by one` error. This is in reference to the header for the "School closed/closing" flag and the "This school has cautionary warnings" flag.

![Screen Shot 2020-04-10 at 12.42.22 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6a85c144-3e54-4ebb-affd-56e5248ff5bc)

![Screen Shot 2020-04-10 at 1.17.55 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/346cd409-be94-4228-a1a1-3812c5225c8a)

Acceptance Criteria:
1. Headers have been fixed so that there are no axe errors related to caution flags

PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/12200

**Comment by zurbergram** [comment]
the https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/AlertBox/AlertBox.jsx component uses a H3 heading

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12200

**Comment by delli-gatti-michael** [comment]
Locat testing complete

**Comment by delli-gatti-michael** [comment]
Confirmed in Staging. Closing this issue
