### ISSUE TITLE
Discovery - Sketch Audit - Getting Started on Design

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#78711]
- [x] Skim through the video posted on [Getting started with design](https://vfs.atlassian.net/wiki/spaces/RD/pages/2575925373/Getting+started+with+design)
- [x] Ask Naomi how we should handle this page.

## Acceptance Criteria

- [x] We have determined steps on how to handle [Getting started with design](https://vfs.atlassian.net/wiki/spaces/RD/pages/2575925373/Getting+started+with+design) with regards to mentions of Sketch.

**Comment by jknipes** [comment]
Discovery completed, moving to _Done_

**Comment by jknipes** [comment]
Discovery complete, moving to _Done_

**Comment by jknipes** [comment]
Discovery complete, Moving to _Done_
