### ISSUE TITLE
Discovery - Sketch Epic - Accessibility on VA.gov

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#78712]
Ask Martha, Jaime, and Naomi how to handle the mentions of Sketch on [Accessibility on VA.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/3124265207/Accessibility+on+VA.gov)

## Acceptance Criteria

- [x] We've determined next steps for how to handle the mentions of Sketch in [Accessibility on VA.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/3124265207/Accessibility+on+VA.gov).

**Comment by jknipes** [comment]
Discovery complete, moving to _Done_
