### ISSUE TITLE
Create new reps, orgs, and org_reps models

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#78732]
## Background
_What background/context has led to this work?  What problem are we trying to solve?_

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by oddball-lindsay** [comment]
On hold -- changing approach to underlying tables which will cary over to model changes.
