### ISSUE TITLE
CT: Staging - Profile page "Showing X of Y" discrepancy

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#7873]
Navigate to profile page https://staging.va.gov/gi-bill-comparison-tool/profile/21923146, scroll down and view the School Locations. The text "Showing 10 out of 120" should be "Showing 10 of 120 locations".  The text "locations" is missing and need to remove "out".

What it currently looks like
![Screen Shot 2020-04-10 at 2.32.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6ea3abdc-2eb7-47e2-9864-8f5cb940cfce)

What it should look like
![Screen Shot 2020-04-10 at 2.34.47 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f5cddcf2-1912-490e-8b9a-bbd9d70b9c95)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12196

Can be tested on vets-website branch `school-locations`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-14 at 8.02.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b5302bd1-0364-4fbd-8b62-34e4bdbf95ff)

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
