### ISSUE TITLE
Update date range fields

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#78742]
Add date range web component pattern support to the VA Forms library ([datePatterns.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/7bbb2a24e67a9a97812c95225e4e20747a67b8c7/src/platform/forms-system/src/js/web-component-patterns/datePatterns.jsx)) to replace the 'dateRange' widget. 

**Pages**
- Service period
- Prisoner of War
- Care expenses 

**Example** (Pseudo code)
```
uiSchema: {
   'ui:validations': [validateDateFromTo('fromField', 'toField')]
   fromField: currentOrPastDateUI,
   toField: currentOrPastDateUI
}
```

**Note**
You can see this technique being used in [fullNamePattern.js](https://github.com/department-of-veterans-affairs/vets-website/blob/7bbb2a24e67a9a97812c95225e4e20747a67b8c7/src/platform/forms-system/src/js/web-component-patterns/fullNamePattern.js)

**Comment by aplatt-coforma** [comment]
Demo'd during scrum. Closing as done.
