### ISSUE TITLE
Review Test Rail Cases

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7874]
Review Test rail cases for accuracy and feasibility.
Organize and prepare [cases](https://dsvavsp.testrail.io/index.php?/suites/view/30&group_by=cases:section_id&group_order=asc) for execution in the next sprint.

**Comment by ericbuckley** [comment]
@marriej I created 2 new subsections for our test cases.  `Pending Outbound SSO Test Cases (MHV links)` and `Pending Outbound SSO Test Cases (MHV & eBenefit links)`.  I moved all of the test cases out of the `Outbound SSO Test Cases` section that aren't ready to test right now.

Note: test C334 is still missing some details as to how we can test a mobile.va.gov URL in the staging environment.  I tried a couple of things through CAG, but it didn't work for me.  https://dsvavsp.testrail.io/index.php?/cases/view/334&group_by=cases:section_id&group_order=asc&group_id=83
