### ISSUE TITLE
Request 404 pattern added to dev docs and VADS

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78752]
### User story

As a Cartographer, I want to get the 404 pattern we established for react apps into the developer docs and VADS, so that Veterans will experience consistent behavior across VAgov going forward.

### Notes
- [thread](https://dsva.slack.com/archives/C0581MN69TJ/p1710877299587919?thread_ts=1710864614.672449&cid=C0581MN69TJ) with various inputs
- [slack canvas](https://dsva.slack.com/docs/T03FECE8V/F06G3J52NJE)

Possible tasks:
- 

## Acceptance criteria

- Create Figma file for this (required for VADS submission)
- Request ticket submitted to design system team
  - including suggestion for governance (e.g., DST take over 404 from CAIA)
  - include link to dev docs
- Request submitted for addition to platform developer docs

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82877
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82879
```

**Comment by carlosfelix2** [comment]
This seems to be a good place to add the 404 information to: https://depo-platform-documentation.scrollhelp.site/developer-docs/react-router-guidelines

**Comment by carlosfelix2** [comment]
Ticket created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82912

**Comment by carlosfelix2** [comment]
Ticket to add content to dev docs was submitted.
