### ISSUE TITLE
Upcoming DSLOGON outage: deploy advance sitewide scheduled downtime messaging

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7876]
## Planned DSLOGON outage will affect sign on from Saturday, April 25, 9:00 a.m. to Saturday, April 26, 9:00 a.m. ET.  

Via the CTO: 

> The Defense Manpower Data Center (DMDC) will make major updates to its production systems infrastructure on April 25-26, 2020. As a result, some services will be unavailable from 0600 PDT on Saturday until approximately 0600 PDT on Sunday. The outage will affect many applications including, but not limited to: DS Logon, RAPIDS, DoD eligibility and identity checks used by the military services, DoD medical facilities, contractors, and morale/welfare activities. Some applications (such as personnel accountability and personnel security applications) will have brief delays to updates to daily reports. DMDC test regions will remain available.

Even though there's currently a standard 'login down' message experience on the sign in modals, because this outage spans an extreme amount of time (24 hours) and a large % of vets use DSLOGON to sign on to VA tools, (~60%), we want to give Veterans plenty of advance notice and not be surprised at being locked out. 

Because this is kind of a weird situation - not really 'sitewide' maintenanance impacting all tools - I think we may need to slightly modify the message text. @peggygannon 

We will show our usual 3 stages of messaging (`advance`, `60 mins countown`, `during`).  

Potential Tickets:
- [ ] Engineering: 
  - Content from Peggy (might be existing content from the unexpected DSLOGON downtime content recently, but pared back a bit)
  - Advance sitewide notification promo announcement banner: 
    - Show 5 days in advance, starting Monday, April 20, to the point of DSLOGON downtime starting, April 25, 9:00 a.m. ET. 
    - 60 minute countdown
    - During DSLOGON downtime, show the during message. (Sign in modal will show down message at this point.)
  - After downtime, remove the banner

FYSA updated ^ 4/13: No new info at this point. Please move forward but please check in on the downtime or platform support channels for any new breaking info that might bubble up. - @MickinSahni @ncksllvn @kelsonic @peggygannon   

Per below comment - will be important to be clear that it's only DS LOGON that will be affected. Ppl using other forms of credentials (MHV, ID.me...) will still be able to sign in.

**Comment by MickinSahni** [comment]
👍 if it's cool, i'm going to convert this ticket to an epic so we can track work within

**Comment by kelsonic** [comment]
Currently our site-wide downtime messaging does not make it simple to configure the downtime messaging text without editing multiple files.

Would be cool if we could add a ticket here (CC @MickinSahni) to make the downtime messaging content very easy to configure if we're planning on using it for more than just `vets-api` downtime! 🙂

**Comment by jenniferlee-dsva** [comment]
For informational purposes - eBenefits is showing advance notification on their site. I don't think we should/need to mention COVID 19! But we do need to make it really clear that it's DS LOGON and that customers using other login credentials (like ID.me, MHV...) can still sign in. 

![image (7)](https://user-images.githubusercontent.com/43381063/79024474-084c3180-7b51-11ea-9a08-8ebeaa021e5c.png)

**Comment by jenniferlee-dsva** [comment]
Updated main ticket info above: 

> FYSA updated ^ 4/13: No new info at this point. Please move forward but please check in on the downtime or platform support channels for any new breaking info that might bubble up. - @MickinSahni @ncksllvn @kelsonic @peggygannon
> 
> Per below comment - will be important to be clear that it's only DS LOGON that will be affected. Ppl using other forms of credentials (MHV, ID.me...) will still be able to sign in.

**Comment by kelsonic** [comment]
Haven't heard anything lately for this ticket. Do we need to bring this ticket into sprint to ensure the site-wide **standard** downtime messaging appears for from Saturday, April 25, 9:00 a.m. to Sunday, April 26, 9:00 a.m. ET.?

**Comment by kelsonic** [comment]
## Before April 20 9am EST

Don't show.

## April 20 9am EST - April 25 7:59:99am EST

`We'll be doing site maintenance on ${formattedStartsAt} until ${formattedExpiresAt} You won’t be able to sign in or use some tools during this time.`

## April 25 8am EST to April 25 8:59:99am EST

`Scheduled maintenance starts in ${minutesRemaining} minutes. If you’re filling out a form, sign in or create an account to save your work.`

## April 25 9am EST - April 26 8:59:99am EST

`We're doing work on VA.gov. If you have trouble using online tools, check back after ${formattedExpiresAt}`

## After April 26 9am EST

Don't show.

CC @peggygannon @MickinSahni @jenniferlee-dsva @stephorkandatx

**Comment by stephorkandatx** [comment]
@peggygannon would you be able to review and provide guidance on how to approach the content for this situation? 

There will be a scheduled outage for a specific login method, DSLOGON, that will last 24 hours. Users with other login credentials (ID.me, MHV, etc.) will still be able to log in. So it's not a full outage for all log-in experiences, and we want to give our users notification of this well in advance. 

Jen screenshotted  a notification that eBenefits is displaying that may be useful. Would you recommend we modify that message (taking out the mention of COVID-19) or is there a more standard message we should use and modify?

**Comment by jenniferlee-dsva** [comment]
p.s. eBenefits example was not meant as a model (of what we want). We generally do NOT follow eBenefits style or standards.

**Comment by stephorkandatx** [comment]
@jenniferlee-dsva Got it, thank you for the clarification! I will update my previous comment to avoid confusion

**Comment by peggygannon** [comment]
@stephorkandatx Yes, will take a look and provide additional guidance. If this downtime is specific to DS Logon, then I'll be tweaking the notification to make that clear. 

To clarify, this downtime is affecting DS Logon only? 
And this message will appear sitewide in promo announcement banner and (during the actual downtime) on sign in modal? 

--Show 5 days in advance, starting Monday, April 20, to the point of DSLOGON downtime starting, April 25, 9:00 a.m. ET.
--60 minute countdown before downtime
--During DSLOGON downtime, show the during message. 
--During DSLOGON on sign in modal

**Comment by jenniferlee-dsva** [comment]
@peggygannon - confirming your above understanding. And just tbc - the sign in modal will show whatever existing 'DS LOGON not working' message they currently use. (i saw it earlier this week when it went down unscheduled.)

the sitewide PW promo announcement banner messages are what need new/updated text. Thank you!

**Comment by kelsonic** [comment]
@peggygannon @jenniferlee-dsva Are we planning on using the content I mentioned?

https://github.com/department-of-veterans-affairs/va.gov-team/issues/7876#issuecomment-614188996

I'll need to get a PR in this morning if we want this to show up Monday morning 😬

**Comment by peggygannon** [comment]
@kelsonic PLease see below for DS Logon downtime messaging. Let me know if you have any questions. 

cc @jenniferlee-dsva 
Advanced message: 

DS Logon will be unavailable from Sat. 4/25, 9:00 a.m. to Sun. 4/26, 9:00 a.m. ET. Please use ID.me or  MyHealtheVet to sign in or use online tools during this time.  


Countdown message: 

Scheduled maintenance on DS Logon will start in 60 minutes. You can still use ID.me or MyHealtheVet to sign in or use online tools. 

Sitewide during downtime: 

DS Logon is down for maintenance. Please use ID.me or MyHealtheVet to sign in or use online tools.  We hope to finish our DS Logon work by Sunday 4/26 at 9:00 a.m ET. 

During downtime on sign in MODAL: 

DS Logon is down for maintenance.  Please use ID.me or MyHealtheVet to sign in or use online tools during this time.  We hope to finish our DS Logon work by Sunday 4/26 at 9:00 a.m ET.

**Comment by kelsonic** [comment]
Thank you @peggygannon! Can we keep the timestamp formatting for the messaging as we had previously?
