### ISSUE TITLE
Allow optional month for va-date when using monthYearOnly

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#78778]
### Describe the problem

Veterans filling out 526EZ, questions 15B, 15C and 15D need a way to provide date ranges with month and year for various exposures. We learned from VBA, that month should be optional since the year only is sufficient for processing the claim. Also, the entire date ranges should be optional and not prevent the Veteran from completing the form.

### Who will benefit

Veterans filing disability claims related to the PACT ACT.

### Describe your idea

Provide a configurable option for the va-date component such that when the monthYearOnly prop is set to true, the month field is optional.
<img width="225" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127446042/44ae6050-18a3-4aa4-af61-0e68c3b29b08">

mocks: [526 Toxic Exposure](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0%3A411&mode=design&t=EGRdJuYA5rC1t3MT-1)

### Provide evidence

[Form 526 Toxic Exposure Usability Research Summary Sept 2023](https://docs.google.com/presentation/d/1VLqXexB72C_fPjUyw1MwL2Pjznvsg_q_UYbg16xk-iM/edit#slide=id.g27c8917d0df_0_0)

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [X] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [ ] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by caw310** [comment]
Adding to DST backlog.

**Comment by gopixelsgo** [comment]
Hi @caw310 - is this item still in DST backlog, or are there any status updates to report? Thanks!

**Comment by caw310** [comment]
@gopixelsgo this is in our backlog. We are focused on the upgrade to USWDS and global changes for the next 2 months. After that we will start to look at our backlog items.

**Comment by gopixelsgo** [comment]
Hi @caw310 - I know your team has been working through the upgrade, and it might be too soon to ask, but just checking if there was any update on this item. Thanks!

**Comment by christinec-fftc** [comment]
It looks like year only is working now! Perhaps from this [this change](https://github.com/department-of-veterans-affairs/component-library/pull/922)? In any case, would love to add to this to our form now, but am seeing a validation error when trying to blank out/reset the fields. Here's the steps in the test
1. enter year only and tab away. success!
2. add a month and tab away. success!
3. try to remove month and year - validation error. is this expected? is this something we could configure to allow blanking out the fields? on our form the date is an optional field.

https://github.com/user-attachments/assets/f4b2ac0f-b0f3-4feb-a3d4-7286ecba0adc

**Comment by micahchiang** [comment]
@christinec-fftc - you may be able to control the validation behaviour of the date by using [these props](https://github.com/department-of-veterans-affairs/component-library/blob/ce45605908d112eb6c5bb44b9d7061b3970fbba2/packages/web-components/src/components/va-date/va-date.tsx#L101-L103) in your component. 

[Here's an example in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/49d619f2918201d552f7c43ec55924220f8588b0/src/applications/appeals/995/components/EvidenceRecords.jsx#L125-L127)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/78778?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
@micahchiang and @rhasselle-oddball - Can you both coordinate on this one? It is a bug, IMHO, that the Forms Library (I believe) is inserting "X"s for optional fields in dates which leads to silent failures. It's important we address this in a way that prevents downstream failures. Thanks.

**Comment by rhasselle-oddball** [comment]
Also here is the writeup Christine did on findings and takeaways:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/94584_summary_of_invalid_dates.md
including how to reproduce at the very bottom.

Fixing validation alone may not solve this issue, based on that report.

**Comment by rhasselle-oddball** [comment]
Also from that report above seems useful:
> Web component pattern for dates (link):
^(\\d{4}|XXXX)-(0[1-9]|1[0-2]|XX)-(0[1-9]|[1-2][0-9]|3[0-1]|XX)$

> Lighthouse pattern for dates (link):
^(?:19|20)[0-9][0-9]$|^(?:19|20)[0-9][0-9]-(0[1-9]|1[0-2])$

reconciling these may be the first step, and testing the implications of changing our FE patterns

**Comment by it-harrison** [comment]
Hi @rhasselle-oddball I have a [draft PR](https://github.com/department-of-veterans-affairs/component-library/pull/1377) for an update to `va-date` that allows for the month to be optional in a month/year instance. I'm not sure about the other discussion of valid or invalid input - that seems beyond DST?

**Comment by rhasselle-oddball** [comment]
@it-harrison oh looks like the "X"s discussion got pulled into this issue - maybe we need to break that into a separate issue for our team to look into. 👍I'll make a ticket.

**Comment by rhasselle-oddball** [comment]
Created ticket https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1792
