### ISSUE TITLE
10-7959f-2: Add additional file support to the form in the back end

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#78786]
As a Foreign Medical Program user, I want to send supporting documents with my claim cover sheet so that I can get paid for my expenses.

- Add attachments to the filled out form
- Generate and fill the appropriate amount of form sheets for array-like data
- Create vets-api pull request for internal and platform approval (or combine with step 5)
- Merge pull request

**Comment by balexandr** [comment]
This is currently awaiting platform review

**Comment by marywang2** [comment]
@balexandr would you add points to this one?

**Comment by balexandr** [comment]
@marywang2 Added 1!

**Comment by balexandr** [comment]
This has been merged into master
