### ISSUE TITLE
Strategize with OCTO: Unauthenticated MHV portal experience

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78785]
### User story

As a Cartographer, I want to work with OCTO on a strategy for the unauthenticated MHV portal experience, so that we can identify a path toward sunsetting the unauthenticated MHV Classic experience.

### Notes
- octo requested in [slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1710203710846969) – attendees proposed by Lauren: Danielle, Mikki, Kaitlin, Kristen McConnell
- Kaitlin asked about an unauth strategy in [slack](https://dsva.slack.com/archives/C0581MN69TJ/p1710203710846969) on 3/12/24. Sara documented some considerations in that thread.

Current behavior: 
- An unauthed user trying to navigate to `/my-health/` is redirected to `www.va.gov/?next=%2Fmy-health` (the VA home page) with the login modal displayed

Possible tasks:
- [x] ~talk to Kaitlin first to crystallize options, draft preference (e.g., preferred point of entry/SEO as benefit hubs vs. unauth portal)~ Decided to draft points for consideration/discussion in [this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717105527438/4bc3627e06d3fde8554124000b478d9d3d6263bf?sender=uf94a77a19aaf687331c09367) to start our conversation when we meet
- [x] Schedule meeting - scheduled for Tuesday, June 4th from 1-2pm ET with Kaitlin Fink, Kristen McConnell, Danielle Thierry, Mikki Northuis, Laura Willwerth, and Sara Sterkenburg
- [ ] have meeting
- [ ] ticket next steps

## Acceptance criteria
- [x] Diagrammed entry point options ([Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717105527438/4bc3627e06d3fde8554124000b478d9d3d6263bf?sender=uf94a77a19aaf687331c09367))
- [ ] Documented options for paths forward and high-level pros and cons
- [ ] Documented any collective decisions made in the MHV landing page decision log
- [ ] Updated follow-up ticket with next steps: #68427

**Comment by wesrowe** [comment]
@batemapf, the team thinks we should tackle this after the octo offsite, which occurs at the end of sprint 28. Let us know if you hear any more urgent signals.

**Comment by carlosfelix2** [comment]
One comment on the current behavior:
1. An authenticated user navigates to `/my-health`
2. The user gets redirected to `www.va.gov/?next=%2Fmy-health` for login
3. User logs in
4. The va.gov index page flashes momentarily then the user is taken to `/my-health`

Since the user is ultimately taken to the MHV landing page, what is the ultimate goal of this issue?

**Comment by wesrowe** [comment]
@carlosfelix2, The existing experience is fine, maybe even quicker, for users who know where they're going. However, a page must be reachable by a web crawler/bot to be indexed by search engines. And from a ux perspective, we want less-familiar users who link directly to /my-health (e.g. from search) to see what they're being asked to sign into before we ask them for their credentials.

**Comment by sterkenburgsara** [comment]
Update: meeting scheduled for Tuesday, June 4th from 1-2pm ET.

**Comment by wesrowe** [comment]
Met today, 6/4. Sara (and others) took notes on stickies in the Mural linked in the ticket body.

Action items / Next steps:
- Audit unauth content for all the pages that need updates (CAIA)
- Audit existing best bets (CAIA)
- Audit xml sitemaps (multiple on various VAgov subdomains) ( Mikki)
- Look at timelines for promotion of VAgov and how those affect strategy (Kaitlin)

My complete meeting notes:
Unauthenticated Home / landing page
Future strategy could change – per MN, could change the structure of unauthed content.
DT: maybe eliminate tool pages; original goal wasn’t to get SEO around MHV. we wanted to get SEO for tools themselves.
KF: too many pages about tools/portal is just “see what sticks”
DT: also affects auth strategy
KF: if we’re building a portal in the auth exp, do we want the unauth part of the site to reflect that also?
DT: some people still refer to tools as “eBenefits” (old platform), but they’re using VAgov. Suggests we definitely need to maintain the concept of MHV

Would VAgov home page compete with MHV in SEO?
MN: when are we ready to promote the VAgov portal? When ready to promote it over the National Portal?
Note we’ll canonicalize one or the other to avoid conflict

Site search
DT: you need something for “prescriptions” term, even it’s a simple Q&A page in resources & support
MN seems to like pomoting the auth exp
MN worries about creating an unauth parallel to the auth page – do you end up doing that for everything in the auth exp, and then you end up back where we are now?
KF: feels the unauth stuff is very different from the auth stuff; it’s educational about what’s available for managing health.
DT: solution is probably a Drupal page with a sign-in widget. MN says it sounds like a fit for the R&S section. We believe that a sign-in widget can be added to R&S pages (not yet typical).
MN: we’ve talked about moving tool pages to R&S
Site search is a problem to solve: Best bets are key to getting VAgov links to top of site search; right now first 5pp of results are on natl portal

Branding/language challenges
SS & KF both notice that “MHV” is not really mentioned much in our existing unauth content. It needs to be more prominent so that Veterans don’t hear “MHV” for the first time when they get health care.
MN: generally we’ve avoided branding (My VA included).

Change management shift from Ph1 to Ph2
KF: shift from try-me to pushing Vets to move is dependent on these things.
DT: tools can shift to this phase at different times. 
KM: Appts is at parity with MHV Classic at the end of this week – will want to turn off Appts on NP soon.
SS & KF: MR needs to be in Ph1 before any shut-offs(?)

Process
DT: T&S articles don’t go through collab cycle
There is a light tagging capability in R&S

**Comment by wesrowe** [comment]
Good meeting. This can close. Also closing epic.
