### ISSUE TITLE
[Frontend] Update the styling for 'Add batteries to your order' in C2P1 (Add batteries to your order)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7879]
## User Story or Problem Statement
How might we ensure the tool in staging matches the prototype?

## Goal
_On C2P1 on the form (Add batteries to your order) the text that reads 'Add batteries to your order' needs to be a title_ [(InVision screen for reference)](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/405269595_C2_P1-_Select_Supplies_-_Batteries_-_Default)

## Objectives or Key Results this is meant to further
- _MDRT development_
---
## Tasks
- [ ] _Turn 'Add batteries to your order' into a title_

## Acceptance Criteria
- [ ] _'Add batteries to your order' will be a title in the form_

**Comment by leahkeeler** [comment]
Not needed per updated design
