### ISSUE TITLE
Vets-api terminal access for Steven Cumming

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#78791]
### Your Name

Steven Cumming

### Your GitHub handle (terminal access is managed through GitHub)

@stevenjcumming

### Team, Role, and Company of the target individual

Backend Engineer, Platform Reliability Team, Ad Hoc

### Product Manager (PM) name and email

Joe Tice joe.tice@oddball.io

### Product Owner (PO) name and email

Bill Chapman William.Chapman7@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [ ] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need to be able to deploy to production

<img width="889" alt="Screenshot 2024-01-22 at 3 13 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134282106/e47bc5bf-6422-4b88-bc76-295c67528848">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Platform Roster confirmed

E-QIP confirmed

**Comment by bdech** [comment]
@stevenjcummin, you’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Reminder that reliability team members do not need explicit approval from us, as per https://vfs.atlassian.net/l/cp/pG18Phaz. So this is approved!

**Comment by bdech** [comment]
Thank you for the reminder, @JonathanKamensDVA. 

@stevenjcumming, you've been granted access to `production`.
