### ISSUE TITLE
Allow cancellation of Oracle Health (Cerner) appointments

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#78804]
## Description
The CES team has updated vets-api so that Oracle Health appointments can be cancelled when the va_online_scheduling_enable_OH_cancellations is enabled for users.  For appointments that originate from Oracle Health, cancellations will route through the VETSAPI Patient Gateway (VPG) service in order to cancel the appointment in Oracle Health.  Currently Oracle Health appointments do not display the cancellation link when viewing the details of the appointment.  This needs to be changed so the when the va_online_scheduling_enable_OH_cancellations feature toggle is enabled then the cancellation link displays.

NOTE:  The CES team has already created the va_online_scheduling_enable_OH_cancellations feature toggle and they are using it to enable their routing functionality in vets-api.

---

## Acceptance Criteria
Background: the `va_online_scheduling_enable_OH_cancellations` toggle is on

Given an authenticated user
When looking at the details of an appointment originating from Oracle Health
Then the link to Cancel the appointment should appear
And page content matches the [appointment details content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/README.md) 
And page design matches the design spec

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [X] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
This ticket is not needed. CES team is working on the cancelation feature. Appts FE code will check for the cancelable flag in the appointment response to determine whether or not an Oracle Health appointment can be canceled online. 

If cancelable flag = false, FE code will not display the Cancel button and user cannot cancel the appointment. 
If cancelable flag = true, FE code will display the Cancel button and user can cancel the appointment. 

cc: @JRRoof
