### ISSUE TITLE
[Frontend] Stylize the radio button address lines as address blocks

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7880]
## User Story or Problem Statement
Problem description. How might we ensure MDRT's staging UI matches the InVision prototype?

## Goal
_The address radio buttons stylized as address blocks to increase legibility for our users_

## Objectives or Key Results this is meant to further
- _MDRT development_
---
## Tasks
- [ ] _Stylize the address radio buttons as address blocks_

## Acceptance Criteria
- [ ] _Updated UI displaying address blocks for the address radio buttons_

**Comment by bradl3yC** [comment]
being addressed in https://github.com/department-of-veterans-affairs/vets-website/pull/12295
