### ISSUE TITLE
Add versioning to vets-api module

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#78812]
## Description
The Travel Pay API has versioning in place to reduce downstream churn when endpoints change. In order to take advantage of this we should implement versioning on vets-api (and correspondingly vets-website). This will result in calling vets-api endpoints that look something like this:

* `GET staging-api.va.gov/travel_pay/v1/claims`
* `POST api.va.gov/travel_pay/v2/claims/mileage`

## Acceptance Criteria
- [ ] Current endpoints restructured within version 1, e.g. `v1` 
- [ ] Architecture docs exists
  - [ ] showing how this versioning scheme can scale
  - [ ] showing how this versioning scheme can map to any travel pay api versioning numbers (e.g. they are currently on v1.1, but I'd recommend sticking with `v1`, `v2`, `v3`, etc)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ayush-chak** [comment]
not necessary for rollout, but we will do this after rollout

**Comment by hinzed1127** [comment]
@kjduensing is there something more complex desired than [the initial versioning in place](https://github.com/department-of-veterans-affairs/vets-api/blob/ca7fdf63c5ff7581ad5810e84a09a86fcf6c5082/modules/travel_pay/lib/travel_pay/version.rb#L6), or is this ticket outdated now?
