### ISSUE TITLE
Link destination incorrect

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#78811]
### Description

Link destination incorrect on https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager#GoogleAnalyticsandGoogleTagManager-FrequentlyAskedQuestions

`Frequently Asked Questions
Check out our [answers to frequently asked developer questions](https://depo-platform-documentation.scrollhelp.site/wiki/pages/createpage.action?spaceKey=AT&title=Frequently%20Asked%20Questions%20for%20Google%20Analytics%20Developers).`

Link goes to a 404. 

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager#GoogleAnalyticsandGoogleTagManager-FrequentlyAskedQuestions

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS

**Comment by jknipes** [comment]
Hi @benbrasso-agile6 , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Link has been fixed, moving to _Done_
