### ISSUE TITLE
[BUG]  'Logged In' custom dimension (21) is not capturing data

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#7881]
## What happened?

Custom dimension 21 - _Logged In_ - is not recording any data in Google Analytics for production and non-production.

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/3a8b469f-1916-4286-ae70-8a909ecfc05a)

## Steps to Reproduce
- Log into production Google Analytics and access view _All VA.gov Website Data_
- Try to use _Logged In_ as a dimension in a session-based report

## Desired behavior
We should see a certain amount of users that report as being logged in.  If the similar _LAO Level_ custom dimension is working correctly, this should be between 8 and 9 %.

## Acceptance Criteria
- [ ] _Logged In_ custom dimension is reporting data.
- [ ] _Logged In_ custom dimension roughly matches non-ga logs (if such a thing exists)

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All changes have been QA and published

**Comment by bsmartin-ep** [comment]
Before I lose this research, the current variable is looking for the _login-user-logged-in_ event:

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/efdbe157-44c9-4e3f-9ef4-6818d05ac33e)

...which I don't see in GA.  Here are all the `^login.*-success.*` events I see.  Should we listen for all of them?  Skip the _login-or-register_ and _login-successful-start-form_ events?

### Event Label
login-successful-start-form
login-success-myhealthevet
login-success-idme
login-success-dslogon
login-or-register-success-myhealthevet
login-or-register-success-idme
login-or-register-success-dslogon

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Updated to look for the `login-success-.*` events.  Does that make sense?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000284

Working on staging if you want to QA.

![image](https://user-images.githubusercontent.com/62304138/81095782-7cb98c80-8ed3-11ea-9db5-3428173783e0.png)

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Looks good when I preview GTM and log in on staging:

![image](https://user-images.githubusercontent.com/62304138/83536217-ee7bfa80-a4c0-11ea-9622-c292db7d842f.png)

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w178298118p176884211/_u.date00=20200602&_u.date01=20200602&explorer-table.secSegmentId=analytics.customDimension21&explorer-table.plotKeys=%5B%5D/

**Comment by jonwehausen** [comment]
@bsmartin-ep Thank you very much. deployed !
