### ISSUE TITLE
VFS Custom Events for [MHV] & [MHV Secure Messaging]

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#78824]
# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file]([TEMPLATE.-.Custom.GA.Events.-MHV-Secure-Messaging.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14668947/TEMPLATE.-.Custom.GA.Events.-MHV-Secure-Messaging.xlsx)). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- _(If using the Google Sheet, you can link that here:_ _____).
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by bryan-riley-va** [comment]
[TEMPLATE.-.Custom.GA.Events.-MHV-Secure-Messaging.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14669072/TEMPLATE.-.Custom.GA.Events.-MHV-Secure-Messaging.xlsx)

**Comment by johnny-jesensky-adhoc** [comment]
Thank for submitting this @bryan-riley-va! Confirming we have this. We'll take a look and reach out if we have any questions.

FYI @jestutt
