### ISSUE TITLE
Implement Pre-Fill for Forms in Staging (686)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7883]
## Story
As a Veteran, having my information pre-populated in the form fields make completing the form much faster and easier.

## Goal
We want to ensure that the Form System pre-fills any data that the VA already knows about a Veteran or any applicant possible.  

## Considerations
- Does the form/ submission process need to be complete before fetching data?  
- Other forms seem to have a file included that speak to form saving and there is probably a thing in there that has some configuration for fetching the pre-fill as well.
- Data from the backend is passed to the front end, which needs to be configured to display it.
- This should work locally as well, if you have betamocks on your machine
- Focusing on **Pre-Fill** for now and adjusting for **Save in Progress**
- When a user makes a new form, we call MVI for their info and populate the fields.
- Some documentation from earlier Slack chats:
  - https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb
  - https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/models/form_profiles
  - https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings
- [An example ruby file used for the 526](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va526ez.rb)
_Seems that each field needs to be explicitly addressed._

## Tasks
-  [ ] Investigate the documentation to see what is required to implement Pre-Fill

## Acceptance Criteria
- [ ] The 686 form allows for pre-fill for as much info as available.

**Comment by lihanli** [comment]
it looks like the 21-686c form is already being prefilled? https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va21686c.rb

**Comment by jason-gcio** [comment]
Hmm not sure - was this from the previous team's effort?  @kathleencrawford or @digitaldrk can you take a peek?

**Comment by kathleencrawford** [comment]
@lihanli as Jason mentioned, there was some work done a while ago on an older version of the 686, so that file that you referenced is for the older version of the form.  I haven't taken a look, but its possible we could re-use some of it.

**Comment by lihanli** [comment]
this issue is blocked by this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4185), vets-json-schema updates can't be made to vets-api until that PR is merged

**Comment by kevinmirc** [comment]
@lihanli Just an FYI, this is also blocked by my PR which resolved the breaking changes of vets-json-schema 5.0.0.

https://github.com/department-of-veterans-affairs/vets-api/pull/4170

**Comment by jason-gcio** [comment]
@kevinmirc - Thanks for the heads up! Any idea when these will go through?

**Comment by kevinmirc** [comment]
My PR is also dependent on https://github.com/department-of-veterans-affairs/vets-api/pull/4185. So as soon as that's merged, I can merge right after. I'll get an approved review of my PR in the meantime to make sure there isn't any delay.

**Comment by kevinmirc** [comment]
@jason-gcio, @lihanli All breaking changes on `vets-api` from `vets-json-schema v5` have been resolved and merged via this PR https://github.com/department-of-veterans-affairs/vets-api/pull/4170. You should be unblocked now.

Thanks!

**Comment by lihanli** [comment]
@cohnjesse @micahchiang 
prefill has been merged and deployed
```javascript
fetch(
  "https://staging-api.va.gov/v0/in_progress_forms/686C-674",
  {
    "method":"GET",
    mode: 'cors',
    credentials: 'include',
    headers: {
      'X-Key-Inflection': 'camel'
    }
  }
).then((data) => {
  return data.json();
}).then((json) => {
  console.log(json)
});
```

**Comment by jason-gcio** [comment]
Thank you @lihanli! We really appreciate it!
