### ISSUE TITLE
Redundant entry changes

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#78847]
Users of 10-10d are able to re-use previously entered address information across applicants as they are added.

Acceptance criteria
- [x] For applicants > 1, users are able to select a previously entered address and apply it to the current applicant
- [x] If a previous address is used, the address content fields for the current applicant are automatically populated with that data
- [x] Auto-populated address fields are editable on the current applicant without affecting the original applicant/address

**Comment by michaelclement** [comment]
[Work is ongoing in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28728)

**Comment by michaelclement** [comment]
@baltes demo visible on staging. This ticket is ready to be closed out once you approve.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae32210c7e38504e2f8c9176d17591b492ce56b1/Screen%20Recording%202024-03-27%20at%2017.57.21.mov)
