### ISSUE TITLE
10-10d: urls for staging/prod

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#78843]
URLs for staging and prod for form 10-10d should follow CAIA guidance:

Teams can choose their own sub-urls, or get help from CAIA in choosing them or vetting them.
Note some standard sub-urls:
/introduction: use on the first page of the actual form (not the static page in drupal)
/review OR /review-and-submit: use for review steps in forms or tools
/results: use to display the results of a tool (not usually used in a form)
/confirmation: use for the confirmation page after form submission
Subtask URL slugs should be short, plain language, and drawn from the H1 if possible.
Reminder: Don’t create unnecessary or empty subdirectories when creating sub-URLs

base url: va.gov/health-care/champva/apply-form-10-10d/

sub urls:
Section 1:
va.gov/health-care/champva/apply-form-10-10d/introduction
va.gov/health-care/champva/apply-form-10-10d/signer
va.gov/health-care/champva/apply-form-10-10d/signer-information
va.gov/health-care/champva/apply-form-10-10d/signer-mailing address
va.gov/health-care/champva/apply-form-10-10d/signer-contact-information
va.gov/health-care/champva/apply-form-10-10d/signer-relationship

Section 2:
va.gov/health-care/champva/apply-form-10-10d/sponsor-information
va.gov/health-care/champva/apply-form-10-10d/sponsor-identification-information
va.gov/health-care/champva/apply-form-10-10d/sponsor-status
va.gov/health-care/champva/apply-form-10-10d/sponsor-status-date
va.gov/health-care/champva/apply-form-10-10d/sponsor-status-file
va.gov/health-care/champva/apply-form-10-10d/sponsor-mailing-address
va.gov/health-care/champva/apply-form-10-10d/sponsor-contact-information

Section 3:
va.gov/health-care/champva/apply-form-10-10d/applicant-information
va.gov/health-care/champva/apply-form-10-10d/applicant-identification-information
va.gov/health-care/champva/apply-form-10-10d/applicant-mailing-address
va.gov/health-care/champva/apply-form-10-10d/applicant-contact-information
va.gov/health-care/champva/apply-form-10-10d/applicant-relationship
va.gov/health-care/champva/apply-form-10-10d/applicant-marriage
va.gov/health-care/champva/apply-form-10-10d/applicant-marriage-date
va.gov/health-care/champva/apply-form-10-10d/applicant-marriage-file

remarriage:
va.gov/health-care/champva/apply-form-10-10d/applicant-remarriage
va.gov/health-care/champva/apply-form-10-10d/applicant-remarriage-date
va.gov/health-care/champva/apply-form-10-10d/applicant-remarriage-file
va.gov/health-care/champva/apply-form-10-10d/applicant-remarriage-separation-date
va.gov/health-care/champva/apply-form-10-10d/applicant-remarriage-separation-file

child:
va.gov/health-care/champva/apply-form-10-10d/applicant-relationship-child
va.gov/health-care/champva/apply-form-10-10d/applicant-relationship-child-file
va.gov/health-care/champva/apply-form-10-10d/applicant-dependent-status
va.gov/health-care/champva/apply-form-10-10d/applicant-dependent-file

Medicare
va.gov/health-care/champva/apply-form-10-10d/applicant-medicare
va.gov/health-care/champva/apply-form-10-10d/applicant-medicare-file
va.gov/health-care/champva/apply-form-10-10d/applicant-other-insurance-status
va.gov/health-care/champva/apply-form-10-10d/applicant-other-insurance-file

Section 5:
va.gov/health-care/champva/apply-form-10-10d/review

[Figma link](https://www.figma.com/file/UmAtr3ULQEInMXfNFwP0g0/10-10d-User-Testing-Prep?type=design&node-id=212-182602&mode=design&t=8HMZQmx15KpXbYcU-0)

**Comment by michaelclement** [comment]
@marywang2 Here is a list of all URLs the form currently uses, plus a mapping to the URLs you provided and a description of the page so we can verify the mapping is correct:
| current url | clean url | page description |
| ----------- | --------- | ---------------- |
| /introduction | va.gov/health-care/champva/apply-form-10-10d/introduction | Overview screen
| /your-information/description | | 
| /certification/name | | 
| /certification/address | | 
| /certification/phone | | 
| /certification/relationship | | 
| /sponsor-information/name-dob | | 
| /sponsor-information/ssn | | 
| /sponsor-information/status | | 
| /sponsor-information/status-date | | 
| /sponsor-information/status-documents | | 
| /sponsor-information/address | | 
| /sponsor-information/phone | | 
| /sponsor-information/disability | | 
| /sponsor-information/discharge-papers | | 
| /applicant-information | | 
| /applicant-information/:index/start | | 
| /applicant-information/:index/ssn | | 
| /applicant-information/:index/pre-address | | 
| /applicant-information/:index/address | | 
| /applicant-information/:index/email-phone | | 
| /applicant-information/:index/gender | | 
| /applicant-information/:index/relationship | | 
| /applicant-information/:index/child-info | | 
| /applicant-information/:index/child-documents | | 
| /applicant-information/:index/school-age | | 
| /applicant-information/:index/school-documents | | 
| /applicant-information/:index/helpless-child | | 
| /applicant-information/:index/adoption-documents | | 
| /applicant-information/:index/via-marriage-documents | | 
| /applicant-information/:index/marriage-details | | 
| /applicant-information/:index/remarriage-viable | | 
| /applicant-information/:index/marriage-dates | | 
| /applicant-information/:index/remarried-dates | | 
| /applicant-information/:index/remarried-separated-dates | | 
| /applicant-information/:index/married-separated-dates | | 
| /applicant-information/:index/spouse | | 
| /applicant-information/:index/second-marriage | | 
| /applicant-information/:index/second-marriage-dissolved | | 
| /applicant-information/:index/medicare-status | | 
| /applicant-information/:index/medicare-status-continued | | 
| /applicant-information/:index/medicare-ab-upload | | 
| /applicant-information/:index/medicare-d-upload | | 
| /applicant-information/:index/over-65-ineligible | | 
| /applicant-information/:index/ohi | | 
| /applicant-information/:index/ohi-upload | | 
| /applicant-information/:index/10-7959c-upload | | 
| /supporting-files | | 
| /consent-to-mail | | 
| /review-and-submit | | 
| /confirmation | |

**Comment by michaelclement** [comment]
@marywang2 @baltes Once these PRs (linked below) are reviewed by the team + platform, this ticket will be ready to close out. I'll circle back here when the URL changes are reflected on staging.

- [base-url change](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/content-build/1998) (awaiting approval)
- [individual page urls](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/vets-website/28934) (awaiting approval)

**Comment by michaelclement** [comment]
Still have not gotten a review of the base URL change PR. It'll have been 24hrs since the request was opened at 6pm today, so I'm anticipating these getting merged pretty early tomorrow morning. Will follow up here.

**Comment by michaelclement** [comment]
PRs are finally merged - waiting for changes to show on staging now

**Comment by michaelclement** [comment]
new URLS are live - this ticket is ready for closure whenever @baltes or @marywang2 verify
https://staging.va.gov/health-care/champva/apply-form-10-10d/

**Comment by marywang2** [comment]
@michaelclement seeing a '0' get appended to the url (for every url after this one - text blurb screen): https://staging.va.gov/health-care/champva/apply-form-10-10d/applicant-information-intro/0

**Comment by baltes** [comment]
@marywang2 I think that's specific to the applicant screens and the number will increment for additional applicants.

**Comment by michaelclement** [comment]
Just to keep this ticket relevant - as of August 2024 here are the current URLs in use:

| URL |
|-|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-type|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-info|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-mailing-address|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-contact-info|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-relationship|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-info|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-identification-info|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-status|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-status-date|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-mailing-address|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-contact-info|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-info|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-info-intro/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-identification-info/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-mailing-same/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-mailing-address/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-contact-info/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-gender/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-relationship/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-relationship-child/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-relationship-child-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-child-adoption-file/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-child-marriage-file/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-dependent-status/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-child-school-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-dependent-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-marriage-date/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-marriage-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare-continued/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare-d-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare-ineligible/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-other-insurance-status/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-other-insurance-upload/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-other-insurance-10-7959c-file/:index|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/supporting-files|
|/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/consent-mail|
