### ISSUE TITLE
SSOe traffic baseline [Security Review after-action]

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7884]
Full Security Review feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6823

- [x] Look into what kind of traffic SSOe is prepared to handle for launch (noting we have both logins + KeepAlive endpoint sessions) so we can have more confidence that the rollout of SSOe won't break the experience for Veterans.

**Comment by patrickvinograd** [comment]
Sent email to Damien/Perry/Lee Anne on 4/16

**Comment by patrickvinograd** [comment]
Got a response from Damien, Andrew Gunsch was cc'ed.

> So from the VA.gov SSOe-IA I see 56,000 authentications/day (12,000 authentications/hour).
> Looking at some of the recent SSOe numbers we have about ~175,000 authentications/day and ~12,000 authentications/hour @ peak time (~10 am – 5 pm ET).  

So VA.gov traffic is a significant percentage increase to SSOe traffic, but not completely dominating their capacity. 

Closing unless Andrew raises follow-up concerns.
