### ISSUE TITLE
Prioritize landing page problems-to-solve

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#78851]
### User story

As a Cartographer, I want to get alignment with immediate stakeholders on what problems we want to prioritize solving for Veterans, so that we can iterate the landing page in a thoughtful and data-driven way.

### Notes
- 

Possible tasks:
- workshop problems-to-solve/how-might-wes (HMWs) in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710953657694/ddfcad42ffa0af5e22ebeee9db17867436513217?sender=uebde62ceb342c6477fb09406)
- competitive analysis [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710792685965/130af5ff20096b650079e36b00db1187172c857f?sender=u24af215c7d9bf806b8545488)
- document and use prioritization rubric

## Acceptance criteria

- Prioritized HMWs into a prioritized list of problems-to-solve using a traceable process
- UXers+Wes met with Patrick and Kaitlin to agree on first problem to solve
- Wrote user story for next steps on selected problem

**Comment by fmccaf1** [comment]
We came to agreement during meeting today to focus on adding HRC contact center details to the landing page. [Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710953657694/ddfcad42ffa0af5e22ebeee9db17867436513217?sender=ua13e567cb5c4221acaa14949)

**Comment by wesrowe** [comment]
I'm going to inform Patrick and Kaitlin now.
