### ISSUE TITLE
Post Submission Notification: Failure Email

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#78866]
526 submission is processed in multiple steps; first the 526, then ancillary jobs which include ancillary forms, evidence uploads, etc. If the 526 submission is successful but an ancillary job fails, we want to notify the Veteran so that it's not a silent failure and they can resubmit the ancillary document.

Veterans submitting the 526 should receive an email notifying them that their submission was successful. Notifications to the Veteran are only sent when the submission uses the primary path; there is no notification on the backup path, whether it results in failure or success. For applications that succeed on the backup path, we want to [send the typical confirmation email](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78903). For applications that fail, there is an email template that prompts the Veteran to redo their entire application regardless of the failure, which needs to be redesigned to better identify the problem and direct the Veteran. 

Task:
- [x] Based on list of possible failures ([to be provided by eng](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78892)), speak with stakeholders to identify the best recourse for the Veteran in each type of failure
- [x] Craft language for the new notifications
- [x] Attend CAIA office hours/ Slack to see how to move forward on a content review
- [x] Add language to standard VA Notify email template / existing confirmation page as relevant
- [x] Present new emails to VBA/OCTO
- [x] Create 3 additional email notifications.  These notifications will be for forms 4142, 0781, 0781a.
- [x] Email CAIA to move forward on content for 4142, 0781, and 0781a
- [x] Handoff to Engineers for implementation

Acceptance Criteria:
- [x] Content/language reviewed by VBA and OCTO stakeholders
- [x] Content/language reviewed by CAIA
- [x] Email template with details as to what failed and how to submit a complete application

**Comment by freeheeling** [comment]
@nnicholas7 A clarification concerning

> If the 526 submission is successful but an ancillary job fails, we send the application down a backup path

An application is only attempted to be submitted via the backup path if the 526 submission fails. There is no backup path in place for ancillary job failures.

**Comment by juliepedtke** [comment]
For reference, working doc we're collaborating in with Nathan: https://docs.google.com/document/d/159xd4IOhboVaD7oobiKSLaKDkq0n6ejqBT1dNI9JkzQ/edit

**Comment by juliepedtke** [comment]
Based on conversations at sprint review and planning, we're focusing on a V1 that is the quickest possible solution. We've determined that all documents would go to the same intake address (Department of Veterans Affairs, Evidence Intake Center, P.O. Box 4444, Janesville, WI 53547-4444) but we have open questions around if evidenced mailed separately from a claim would be successful. Awaiting input from VBA. See [Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1711557666821949). 

In the meantime, @nnicholas7 can start drafting an email notification with placeholder text that we'll updated based on VBA guidance.

**Comment by juliepedtke** [comment]
[Slack conversation with stakeholders
](https://dsva.slack.com/archives/C04KW0B46N5/p1711557666821949)
Takeaways:

- We'll move forward with V1 email notification recommending the Veteran mail in missing documents. 
- We could include language that states to send the evidence in ASAP possible because a decision may be made without that evidence if there is a delay (I know that's not a great message to send but we may want to consider it)
- Using QuickSubmit instead of mail may be an option, but we need further technical discovery to determine if it might trigger the same error.

**Comment by juliepedtke** [comment]
[Figma in progress](https://www.figma.com/file/TZ23k4X5tnh3lFlehYER3f/526-Post-Submission-Upload-Failure-Notification?type=design&node-id=5%3A24746&mode=design&t=NDZr8XqU2pg6VJ3D-1)

Draft shared with stakeholders via Slack, will bring this to CAIA once we get sign-off on the direction.

**Comment by nnicholas7** [comment]
Mapped out the upload points within the 526 to note all points in the form where documents could be uploaded.  Created an email notification in Figma. Will be attending office hours today to determine the next steps with content.

Figma file: https://www.figma.com/file/TZ23k4X5tnh3lFlehYER3f/526-Post-Submission-Upload-Failure-Notification?type=design&node-id=1%3A4&mode=design&t=mijwCXmmJ2iuo5y0-1

Document Upload Points: https://docs.google.com/spreadsheets/d/1KNFeNGLiaX08SlB6fqh7VpM7qHNZ6ItxE7gYN9xnzqk/edit#gid=0

**Comment by nnicholas7** [comment]
Next steps: Hand off designs to engineers and close the ticket for this sprint.

**Comment by juliepedtke** [comment]
Reopening this ticket because the comments from CAIA in the document have not been resolved. Based on the comments, it's unclear if Laura's questions have been answered. 

I also don't see copy in the final version for the following [potential upload failures](https://docs.google.com/spreadsheets/d/1KNFeNGLiaX08SlB6fqh7VpM7qHNZ6ItxE7gYN9xnzqk/edit#gid=0):

- Additional Supporting documents for sexual trauma claim
- Service Treatment records
- Separation Health Assessment - Part A Self-Assessment

I assume the first email ("We couldn’t upload your document for your disability claim") will be sent in these cases, but we need to include the alternative content in the final version and confirm that CAIA has reviewed. 

I also noticed a couple minor errors in the copy which I've commented on in Figma.

**Comment by juliepedtke** [comment]
Update based on today's conversation:

For Veteran uploaded files, one generic email will be sent per file that does not specify where the email came from (eg private medical records, self assessment, 0781, etc.) We're corrected the Figma to reflect this (no H3s), and do not need versions for each upload failure point. This is the "MVP" we've asked Content to review. 

For the forms generated on the backend (4142, potentially 0781 and 0781a in cases where the Veteran did not upload these), we need different messaging to the Veteran to make it clear that they did not uploaded this and likely don't have a saved copy of the completed form. This update is still in progress, and we will need to resolve some final questions with Content once complete (URLs, heading styles).

Eng has split out this work into three tickets, while we are keeping the work together in one.
1. [Veteran uploaded docs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79945)
2. [Generated 4142s](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80044)
3. [Generated 0781/0781as](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80042)

**Comment by nnicholas7** [comment]
A content review was conducted by CAIA on 4/18.  There are concerns about the vagueness of the generic message and how helpful it would be to Veterans. Julie has setup a meeting with CAIA and VBA to discuss concerns.  This meeting will take place Monday morning.  0781 and 0781a screens have been reviewed and will be entered into VA Notify today.

**Comment by nnicholas7** [comment]
Held a meeting with OCTO, CAIA, and Team 1 to discuss wording for the Post Submission emails (generic, 0781/a and 4142).  Meeting notes for that meeting can be found [here](https://docs.google.com/document/d/1IV2OZ4bFvece8yQemjfWOflaIazfOSOqajpeYCLSfvg/edit#heading=h.d65dgzexe6ne).  In summary, the wording for this current email is for V1.  Concerns have been raised about the ability of the Veteran to call the Contact Center to receive guidance on the form name will need to be a V2 fix.  There seems to be a heavier engineer lift on the backend for the Cal Center Representative to see prompts about a Veteran's application status and file name.  V1 MVP is ready to be moved into VA Notify.

**Comment by nnicholas7** [comment]
Currently making some corrections to the visual appearance of the Figma file including change the gray box to include all instructions and the address. Awaiting feedback from Shannon and will upload changes to VA Notify.

**Comment by nnicholas7** [comment]
Figma file content has been uploaded to VA Notify.  Correction for spacing and phone number have been corrected and updated in VA Notify. Sample VA Notify messages were sent to OCTO, VBA, Team 1 and Team 2 for review and have been approved by Shannon. 

Next step: Handoff to engineers to implement.
