### ISSUE TITLE
Investigate OGC Rep ID within vets-api

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#78861]
## Description
An OGC Rep ID is an essential item to have in a [RepresentativeUser profile](https://github.com/department-of-veterans-affairs/vets-api/blob/83d28750b23156a5bbb9c64f5dadfbfcbee0eb1c/modules/accredited_representative_portal/app/models/accredited_representative_portal/representative_user.rb#L1-L25). This will allow ARP to tie a specific Rep user to OGC data (including POA codes). It would appear as if [representative_id in the Veteran::Service::Representative](https://github.com/department-of-veterans-affairs/vets-api/blob/867f456072ebecabe3eb884fa12517b942006905/modules/veteran/app/sidekiq/veteran/vso_reloader.rb#L87) model is in fact what can be used to validate a representative against OGC, but we need to confirm this.

## Acceptance Criteria
- [ ] ARF has confirmed that a VS::Representative representative_id is the same as the "OGC Registration Number" seen in other VA systems and we've confirmed that this identifier can be used to validate a RepresentativeUser against OGC

**Comment by amprokop** [comment]
@holdenhinkle could potentially help us out if he knows the answer offhand!
