### ISSUE TITLE
Update Appointment Lists Filtering/Statuses

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#7886]
## Problem Statement
We need to ensure that we are filtering our the correct appointments for both the Future and Past appointments lists

Statuses/display should match the table below which will be updated as we get more info:

![Screen Shot 2020-04-10 at 2.08.39 PM.png](https://images.zenhubusercontent.com/560c1d84638e718c995d70da/fab2a263-210c-4d39-bedb-46b5b805349c)

https://docs.google.com/spreadsheets/d/1BJ8FJTNDfiWjqhs-xIQ-nQaw6RXMxXdU2CV0EvCfJhI/edit#gid=0

## Goal
Veterans should see the correct appointments and statuses in their appointments list

## Acceptance Criteria
- [ ] List filtering should match the table above

**Comment by lenaecb** [comment]
Here is my recommendation. @lalexanderson-dsva - please confirm that this is the UI behavior you want for handling requests and future and past appointments. 

<img width="752" alt="Screen Shot 2020-04-13 at 8 49 41 AM" src="https://user-images.githubusercontent.com/16602559/79121706-ec6ca980-7d63-11ea-805c-a683ce6b7121.png">

**Comment by rtwell** [comment]
I concur w/ @lenaecb. most of these are either ripe for error / too dependent on humans to be useful to Veterans.

**Comment by lalexanderson-dsva** [comment]
Agree fully with @rtwell and confirming for future appointments. 

only question - in action required, is action required on the part of the veteran?

**Comment by lenaecb** [comment]
@lalexanderson-dsva - my understanding based on the review of Shawn and MHV emails where they map these status is that ACTION REQUIRED is actually mapped to ACT REQ/CHECKED IN and ACT REQ/CHECKED OUT (at least in MHV/Shawn's original mapping).

Shawn provided the following guidance on this particular status combination in his email Nov 2019 - "I’d go with COMPLETED for #1 and #2 to give everyone (patients and staff) the benefit of the doubt that the patient was indeed seen and maybe they just were never checked in and the encounter/note hasn’t started yet." 

Complete in this context for us means - "No status shown"

**Comment by lalexanderson-dsva** [comment]
ok

**Comment by lenaecb** [comment]
@narin - based on the above, I think we're good to go with this my previous recommendation.

**Comment by narin** [comment]
Perfect.  Thanks @lenaecb @lalexanderson-dsva @rtwell !!
