### ISSUE TITLE
[FE] 10-10EZR TERA: Frontend UI tweaks PART 1

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#78887]
As a Veteran, I would like to answer the TERA questions online in an easy-to-understand and clear manner so that I make sure I get the healthcare I have earned.

- [ ] Work with Alex and UX to review and prioritize fixes from the [UX review](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/78886)
- [ ] Work with QA to make sure test cases are up-to-date
- [ ] Make fixes
- [ ] Have QA and UX review (can be via a demo or by having them review on their own)
- [ ] Implement code freeze on 4/2/24
- [ ] **Success: All of the prioritized UX tweaks are fixed**

**Bugs/fixes**

1. Allow user to enter same start and end month and year in date ranges
2. Intro page content updates (see [Figma screens](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=2129%3A20855&mode=design&t=MH3a97BDiyluE5lB-1)); if possible wait until April 2 to make changes

**Comment by katelyncai** [comment]
Howdy, I've added some content change requests from Aliyah today (bug/fixes 2 and 3 listed above). The [Figma file](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=1405%3A60260&mode=design&t=MH3a97BDiyluE5lB-1) is currently up-to-date with those requests, but I added a note that waiting until April 2 when content changes are frozen would be best to avoid any swirl or additional changes. Thanks!

**Comment by katelyncai** [comment]
Ding ding, more content updates ✨ we're going to add some info on how to mail in supporting documents (this is aligning with content on EZ as well) to the EZR confirmation page. I added this task as bug/fix 4. I think it will be useful for us to do a walkthrough of the content changes next week, so I'll find a slot on the calendar for that.

**Comment by allanto-ah** [comment]
Environment: staging

1. Verified that users are now allowed to enter the same start and end month and year for date ranges
2. Verified that the EZR intro page matches the Figma designs
