### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#78882]
### Name

Dene Gabaldon

### Email

dene.gabaldon@va.gov

### Role

Design and Research lead

### Team

OCTO- Benefits crew

### Additional Notes

I am a new OCTO employee and will need full access as a designer.

**Comment by naomimarcussen** [comment]
Hi Dene! I just sent an invite to dene.gabaldon@va.gov. Reply back here once you've created an account and I'll bump you up to have full access.

**Comment by Dene-human** [comment]
Hi Naomi, great to see you again! Thank you!

My account is now created.

**Comment by naomimarcussen** [comment]
Great! I've upgraded you to have full access.

**Comment by Dene-human** [comment]
Thank you!
