### ISSUE TITLE
Qualitative Data Request - Medallia - Find a Representative (1 week post-launch)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78898]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

03-11-2024

### Date Range End

03-20-2024

### Product Name(s)

Find a Representative

### Product Description

The Find a Representative product enables users to search for an accredited representative based on representative type, location and name.  

The landing page provides additional context to accredited representatives and also contains the entry point into the Find a Representative product. 

### Survey URL(s), key term(s), case category or type

1. Find a VA accredited representative or VSO product page: https://www.va.gov/get-help-from-accredited-representative/find-rep/
2. Get help from a VA accredited representative or VSO landing page: https://www.va.gov/get-help-from-accredited-representative/

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

lindsay.li-smith@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. However, this URL, https://www.va.gov/get-help-from-accredited-representative/
did not come up on the Medallia. Thank you!

**Comment by oddball-lindsay** [comment]
Thank you @newworld2616 !
