### ISSUE TITLE
Qualitative Data Request - MyVA411 - Find a Representative (1 week post-launch)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78899]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

03-11-2024

### Date Range End

03-20-2024

### Product Name(s)

Find a Representative

### Product Description

The Find a Representative product enables users to search for an accredited representative based on representative type, location and name.

The landing page provides additional context to accredited representatives and also contains the entry point into the Find a Representative product.

### Survey URL(s), key term(s), case category or type

Key terms: accredited, representative, representation, attorney, claims agent, vso, vso representative, veterans service officer, service organization representative, 21-22, 2122, 21-22a, 21-22a

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

lindsay.li-smith@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, currently we do not have case category, case type or sub category that includes the requested list in MYVA411. Sorry for the inconvenience.
