### ISSUE TITLE
Claims Details V2] aria-describedby message not on page; remove it

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#78891]
## Value Statement
**_As a_** user type
**_I want to_** job to be done
**_So that_** desired outcome(s)

---
### Bug

**Issue description**

URL: `/track-claims/your-claims/600351984/files`

When you navigate to the "The files I uploaded support this claim only." checkbox, you here the announcement: ""To submit supporting documents for a new disability claim, please visit our How to File a Claim page below." thanks to the `aria-describedby`. However, that link isn't present on this page.

<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9da8de7a20185fd77de1e67c87e7bfc7a71342cf/image.png" alt="image.png" />

Code:

```html
<va-checkbox label="The files I uploaded support this claim only." message-aria-describedby="To submit supporting documents for a new disability claim, please visit our How to File a Claim page link below." checked="false" uswds="" class="vads-u-margin-y--3 hydrated"></va-checkbox>
```

This is an [a11y-defect-4](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric#Accessibilitydefectseverityrubric-a11y-defect-4).

**Remediation guidance**

Remove the `aria-describedby`:

```html
message-aria-describedby="To submit supporting documents for a new disability claim, please visit our How to File a Claim page link below."
```

**Does this impact visual design?**

No.

**Relevant standards**

N/A

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] `aria-describedby` is removed.

**Comment by pmclaren19** [comment]
Tested in staging and looks good! @davidakennedy this is now in Staging. Please let me know if anything else need to be done for this, otherwise marking complete and closing!

**Comment by davidakennedy** [comment]
@pmclaren19 Gave this a quick test, and it looks good. Thanks for fixing!
