### ISSUE TITLE
[FE/QA] 10-10EZR: Prevent user from entering only spaces in text field

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#78895]
As a Veteran, I would like to be prevented from doing anything that would corrupt the data in my EZR so that even if I fall asleep on the keyboard I will still be able to submit an EZR later.

- [x] Review the work Matt L did for EZ (PR #[28445](https://github.com/department-of-veterans-affairs/vets-website/pull/28445/files))
- [x] Implement this for all required fields for EZR
- [x] Work with QA to update test cases and test
- [x] **Success: user cannot enter only spaces in a text field**

**Comment by allanto-ah** [comment]
@dellerbie When entering only spaces for the Medicare Claim Number field, the error validation message doesn't seem to be correct. 

https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/4dcd203b-bd63-4bfa-b867-47d898b8a64c

**Comment by allanto-ah** [comment]
Environment: Staging

Verified the fix to the Medicare Claim Number
<img width="1570" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c064e3e28199dd87e4dae7a2b5f40396f98a18cd/Screenshot%202024-05-22%20at%2012.15.14%E2%80%AFPM.png" alt="Screenshot 2024-05-22 at 12.15.14 PM.png" />
