### ISSUE TITLE
IA Request [Third-party app directory ]+[Connected Accounts FAQ]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7889]
## Background "Apps Directory":
 Lighthouse API and Authenticated Experience teams want to link to an up-to-date list of **third-party apps** and services a Veteran can connect their VA data to. This content will need to be easy for the Lighthouse team to update, as we onboard new API consumers. There is a potential future use case of using this same content on developer.va.gov

For full context, there is also a [VA mobile](https://mobile.va.gov/) app store for VA apps that another dpt. owns. We are not planning on listing these apps on our page of third-party apps and services. Open to discussing it if you have a different point of view on this.

## Related tickets
- Request for [Copy and IA help from Lighthouse API for connected accounts #6838]([url](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6838))
- [Epic] Connected Accounts Updates #6814 

## Background "FAQ url"
There was a previous ticket for FAQ url for Connected Accounts that was never implemented. Since then, our needs have changed. We (ie. Lighthouse API and Authenticated Experience teams) want to link to this content from within a Veteran's account settings. Lighthouse may also decide to use this link in the original OAuth screens, as originally designed, when we revisit these screens later this year.

Related tickets
Request for Copy and IA help from Lighthouse API for connected accounts #6838
[Epic] Connected Accounts Updates #6814
Previous IA work done on this issue: Determine IA for Connected Accounts FAQ #15901

What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to or attach prototype or mockups
- Link to research readout/results ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md))
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure

**Suggested URL(s)**
- 

**Suggested entry points**
- Connected accounts area a Veteran's profile settings
- [Connected accounts FAQ page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864) (WIP)

**Crosslinking opportunities (Apps Directory)**
- [Connected accounts FAQ page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864) (WIP)
- developer.va.gov

**Crosslinking opportunities (FAQ page)**
- We'd like to also create a page that lists all of the apps and websites available to connect to and cross-link FAQ there. 
- TBD whether y'all will want to also bring connected accounts FAQs into here: https://www.va.gov/sign-in-faq/

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by Samara-Strauss** [comment]
@careyotto does this still need to be open, or is this part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/9238? If it's mostly duplicative, we can close this ticket.

**Comment by careyotto** [comment]
@Samara-Strauss I will leave that to @mnorthuis whether it is necessary or not. My understanding is this ticket is an IA request for an URL, not part of the design/build ticket.

**Comment by Samara-Strauss** [comment]
Got it. OK, we can keep it open as the team determines whether the apps directory is happening.

**Comment by careyotto** [comment]
Closing this out based on today's convo with @stephorkandatx and @markgreenburg . App Directory will be tabled for now, until an API is built to send the data over. In the meantime, Public Websites will revisit the FAQ content and include a simpler list of apps/links there.
