### ISSUE TITLE
[FE/BE/QA] 10-10EZR TERA: Verify TERA Questions are on Review and Confirmation Pages and update tests

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#78894]
As a Veteran, I would like to review my answers to the TERA questions on the EZR and then submit them and see them on the confirmation page so that I make sure I didn't make any mistakes or miss anything while filling them out. 

- [x] Update Unit Tests to test for TERA Questions on Review and Confirmation Pages
- [x] Update test cases to test that TERA Questions are Review and Confirmation Pages
- [x] Test that TERA info displayed on Review and Confirmation Pages is accurate
- [x] Test with no TERA info submitted
- [x] Test that submission works
- [x] **Success: Veterans can review their TERA question answers before submitting their EZR**

**Comment by longmd** [comment]
@alexseelig , the review page is dynamically-generated by the forms library. This task isnt necessary for anyone. Itll happen automatically.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the TERA questions appear on the EZR review page. TERA information also appears on the confirmation page after submission. 

See: [#79834](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/79834)
