### ISSUE TITLE
BE | Profile | Direct Deposit | Discovery: Direct Deposit API validation inconsistency

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#78908]
## Background
Scott Regenthal (Benefits & Claims/ DBeX 2) raised some questions around Direct Deposit account number validations.

In the [Benefits Claims API](https://developer.va.gov/explore/api/benefits-claims/docs?version=v1), the account number must be between 4 and 17 digits when submitting a 526 Form (POST /format/526):

However, in the [Direct Deposit API](https://developer.va.gov/explore/api/direct-deposit-management/docs?version=current), the account number does not apply the same validation rules.  I have been able to add an account number of length 1 and it will save in our staging environment.

## Tasks
- [x] Ask Lighthouse about inconsistencies.

## Acceptance Criteria
- [ ] Document answers and create any necessary tickets.

**Comment by tpharrison** [comment]
Reached out to Lorri Glover on Thursday, Mar 21st...
> I have some questions around Direct Deposit account number validations and I wasn't sure who to reach out to.
In the [Benefits Claims API](https://developer.va.gov/explore/api/benefits-claims/docs?version=v1), the account number must be between 4 and 17 digits when submitting a 526 Form (POST /format/526).  However, in the [Direct Deposit API](https://developer.va.gov/explore/api/direct-deposit-management/docs?version=current), the account number does not apply the same validation rules. I have been able to add an account number of length 1 and it will save in our staging environment.
Should the account number validation rules be updated for the DD Management API?

Lorri replied on Friday, Mar 22nd...
> I see what you mean, we weren't aware of the minimum 4 so we'll need to contact Benefits Claims team - but I agree they should have the same validation (they are both for Direct Deposit, savings/checkings, acct number for disability payments). Thanks!

cc/ @mtcA6

**Comment by mtcA6** [comment]
we opened a new ticket because it was in fact an issue
