### ISSUE TITLE
Make controller tests more robust

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#78913]
Currently every method of the client is doubled and responses faked. This prevents our tests from catching breaking changes to the service. 

The best method might be to have an intermediate service layer, so we could mock the client fully from the ctlr spec.
(like so)
<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9CQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b010cc9a69731ded4c9049d79194f81192a7cd79/image.png" alt="image.png" />

Another method might be to pass a connection from the controller into the client (and have 2 clients - 1 for veis and 1 for btsss) so that we can stub the requests to veis and btsss thereby allowing the business logic to run, which allows the controller tests to catch breaking changes.

Additionally, we could use the previously established interception pattern with VCR.

A drawback to both of these approaches is that the controller spec has to know details about the client class, but I'd argue that it's less coupled to know the urls the client is hitting than the implementation details of the client's methods.

**Comment by athifw** [comment]
Draft PR: https://github.com/department-of-veterans-affairs/vets-api/pull/17306
