### ISSUE TITLE
REMEDIATION NEEDED: 2472527, 2472537

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#78931]
NOTE: we cannot guarantee that the ticketed 'REMEDIATION NEEDED' work represents all submissions that need remediation.  These tickets are reminders

## Original
We have two 'new' impossible date failures.  they are too old to modify and resubmit, so they need to be packaged as pdfs and sent to Emily

Any data modified to get the PDF generator working should be tracked in a report that is delivered with the remediation package

**Comment by SamStuckey** [comment]
the submissions in question:
ids = [2472527, 2472537]

**Comment by sortizsh** [comment]
@SamStuckey  can you confirm this is done

**Comment by SamStuckey** [comment]
Closing in favor of audit 2 work, these have been marked as remediated
