### ISSUE TITLE
Priority #3:  Make sure the program page reflects MISSION Act eligibility updates as they take effect

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7893]
## Background 
[Public Websites update request from Caregivers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7326)

## High Level User Story/ies
As a Veteran and/or Caregiver, I need accurate/up-to-date eligibility Caregiver program information as changes occur.

## Hypothesis or Bet
**If** we update Caregiver eligibility information as changes occur **then** we expect less confusion from Caregivers, Veterans, and others.

## Acceptance Criteria
- [ ] Kickoff meeting- 4.8.20: 
  - Align on process and dates. Agree on timing for check-in to proceed (ie, one month prior to when each era eligibility change will take effect). Content process will depend on the nature of 
changes at that time.
- [ ] Alignment on information for Priority 1
  - Make sure live pages have accurate and up-to-date information.We’ve received reference documentation re: accuracy of information on the current landing page. We’ve listed the main accuracy points below and would like to go over them now to ensure we’re aligned in our understanding:
    - Avoid using the term “disabilities.”
    - Make sure eligibility criteria are clear and reflect MISSION Act changes.
    - Make sure wording around the expansion of eligibility due to MISSION Act changes does not imply that expansion automatically means Veterans of newly added service eras are eligible. Elsie will send specific language that has worked well, and content team can also look at caregiver team’s edits to recent content documents.
    - Make it clear that there isn’t just an application, but a full assessment process to determine eligibility, and that those Veterans who don’t meet the criteria for this program may be eligible for the Program of General Caregiver Support Services. We need to keep this information high level because the assessment process will soon change.
    - Make it clear that primary and secondary caregivers of approved Veterans are eligible for different benefits. Both are eligible for the menu of services and support. Then, primary caregivers are also eligible for the stipend and health care.
    - Make sure the content doesn’t mix up the audiences when talking to both the Veteran and caregiver

**Comment by stephorkandatx** [comment]
This is primarily a tracking ticket. Will not be updated until summertime.
