### ISSUE TITLE
[Claims Details V2]: Update first paragraph on Ask for your claim decision page to match text color

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#78930]
## Value Statement
**_As a_** Veteran
**_I want to_** have text that matches the rest of the site
**_So that_** it's consistent with the design and doesn't cause confusion.

---
### Bug

URL: `/track-claims/your-claims/600351984/ask-va-to-decide`

On the Ask for your claim decision page, the first paragraph is a blue color, which is similar to our link color, although different. It looks like this isn't intentional and needs to be fixed to the regular text color.

<img width="699" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1Q5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--553e613e24f40947f1e89f9d4833a5834f558c0a/Screen%20Shot%202024-03-21%20at%2010.13.02%20AM.png" alt="Ask for your claim decision page with the first paragraph in a blue color with a red arrow pointing to it." />

cc: @skylerschain @uxgary 

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Change the text color to match the rest of the text._

**Comment by jacobworrell** [comment]
this will be addressed in new 5103 experience
