### ISSUE TITLE
[Research] Dot indicator research: conduct additional sessions with screenreaders

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#78944]
## Background
Matt completed the initial study and target we wanted to reach for the usability testing sessions for the dot indicator however we weren't able to get any sessions with screenreaders. We need to request additional sessions with Perigean and conduct those sessions.

## Tasks
- [x] Ensure codepen is ready
- [x] Request additional sessions through Perigean 
- [x] Conduct sessions

**Comment by mattmarino-adhoc** [comment]
One session has been booked. Perigean has had difficulty getting us the 5 (with the goal of 3 interviews) participants we've requested. There is an additional backup candidate, but they use a screen reader that is not a commonly used tool - we will bring them in depending on what Perigean can manage.
