### ISSUE TITLE
[Efficiency] User can't easily perform the primary task free of distractions.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#78956]
_This ticket was generated during the pilot process for the new VA.gov experience standards. Please tag `@platform-governance-team-members` on Slack if you need assistance interpreting this ticket._

## Product Information
**Team:** Identity Core Team
**Product:** Terms of Use (ToU)
**Feature:** Terms of Use (ToU)

## Findings details
**VA.gov Experience Standard - issue:** User can't easily perform the primary task free of distractions.
**VA.gov Experience Standard - category:** Efficiency
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

Breadcrumbs: On the authenticated view of the TOU page, the page displays a minimal header to keep the user focused on the task at hand. The breadcrumbs should correspondingly be removed to ensure the user focuses on the task.

## Recommended action
Remove breadcrumbs on the authenticated view of the TOU page.

## References

- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Breadcrumbs ](https://design.va.gov/components/breadcrumbs)
- **Design System Pattern:** N/A
- **Content Style Guide:** N/A
- **Context:** Navigation
- **Accessibility Defect Severity:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by asg5704** [comment]
This is the [PR to remove breadcrumbs from TOU](https://github.com/department-of-veterans-affairs/content-build/pull/1745) in the content-build repository. Also note that because the breadcrumbs are generated through the `registry.json` in the `content-build` repository, we should really think about fixing the breadcrumbs issue there and updating documentation so that other teams do not face the same issue.

Y'all can close whenever you are satisfied.

**Comment by shiragoodman** [comment]
@asg5704 I wasn't sure who you were referring to when you said, "Y'all can close." just a heads up (since I've seen you comment on several tickets) that it's not Governance teams responsibility to close these tickets when the issues have been addressed. Per the Next Steps section within the ticket, we ask VFS teams to close these tickets, however you're welcome to tag Governance team members if you have questions and/or need help validating a fix.

**Comment by asg5704** [comment]
Yes, I can elaborate @shiragoodman I wanted to ensure Collab Cycle folks had a chance to read/address what I wrote before I closed anything.

**Comment by shiragoodman** [comment]
thank you! And thanks for sharing the PR. When the PR has been implemented and your PM and/or PO approves the change, then you're free to close the ticket. Thanks again.

**Comment by asg5704** [comment]
Fixed by department-of-veterans-affairs/content-build#1745
