### ISSUE TITLE
SLO: SSOe SessionsController#new Login - /v1/sessions/:csp_type/new

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#78961]
## Issue Description
Create Datadog SLOs for SessionsController#new.  `/v1/sessions/:csp_type/new` where `:type` parameter is in `['idme','logingov','mhv','dslogon']`
- [x] success rate
- [x] latency

**Comment by joeniquette** [comment]
not possible with the current `vets_api.statsd.api_rack_request` SLO. So we either need to use a different one or get these values added to rack.

**Comment by rileyanderson** [comment]
I think we'll just have to combine all the requests that hit `new` there isnt a way to get path parameters
