### ISSUE TITLE
SLO: SSOe SessionsController#new Logout - /v1/sessions/slo/new

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#78963]
## Issue Description
Create Datadog SLO for SSOe SessionsController#new Logout - `/v1/sessions/:type/new`  where `:type` parameter is `slo`
- [ ] success rate
- [ ] latency

**Comment by joeniquette** [comment]
do we need this if we have an SLO that covers slo saml callback like this: https://vagov.ddog-gov.com/slo/manage?query=ssoe%20&slo_id=2107713d95095f9ab74a42a97380a177&tab=status_and_history&from_ts=1708547380386&to_ts=1711139380386&paused=false

**Comment by rileyanderson** [comment]
@joeniquette Yeah I think so, they are technically two different endpoints. `sessions/slo/new` gets called when a user logouts, it then gets redirected to eauth or wherever, then eauth hits `v1/sessions#ssoe_slo_callback` which then redirects back to the frontend. We'll need to find a way to differentiate between login and logout since they use the same endpoint. That's why I was hoping we could get the path parameter but looks like that isnt the case
