### ISSUE TITLE
SLO: SSOe SessionsController#saml_callback

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#78962]
## Issue Description
Create Datadog SLOs for SessionsController#saml_callback
- [x] success rate
- [ ] latency

**Comment by joeniquette** [comment]
callback latency: https://vagov.ddog-gov.com/slo/manage?query=saml_callback%20&slo_id=d2097602a52c55dd86e01475e5ec8026&tab=status_and_history&from_ts=1708547065411&to_ts=1711139065411&paused=false

callback availability: https://vagov.ddog-gov.com/slo/manage?query=saml_callback%20&slo_id=82b743844bfe5cf6aeceb6be58f5b8c0&tab=status_and_history&from_ts=1708547114196&to_ts=1711139114196&paused=false
