### ISSUE TITLE
SLO: SSOe SessionsController#ssoe_slo_callback 

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#78965]
## Issue Description
Create Datadog SLO for SSOe SessionsController#ssoe_slo_callback 

- [x] success rate
- [x] latency

**Comment by joeniquette** [comment]
availability: https://vagov.ddog-gov.com/slo/manage?query=ssoe%20&slo_id=2107713d95095f9ab74a42a97380a177&tab=status_and_history&from_ts=1708547282429&to_ts=1711139282429&paused=false
latency: https://vagov.ddog-gov.com/slo/manage?query=ssoe%20&slo_id=e9db03117c6c592fbafa6bba59ff3bc6&tab=status_and_history&from_ts=1708547305143&to_ts=1711139305143&paused=false
