### ISSUE TITLE
Adding Ayush Chakravarty to DSVA Slack

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#78975]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)
✅ Verified

Please add Ayush Chakravarty as a full member. He is a Product Manager joining the Beneficiary Travel team and needs access to Slack for communicating with team members, other teams across VA.gov, and Product Owners and Stakeholders.
Work email: ayush@adhocteam.us
VA email: ayush.chakravarty@va.gov

**Comment by ayush-chak** [comment]
Hi there! Just following up on this - anything else you need on my end? Would love to get into Slack (and then Zenhub)!

**Comment by LEHigley** [comment]
done, but this was submitted 2x
