### ISSUE TITLE
Gem Update: Prawn 2.5.0

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#78981]
It [appears example PDFs need to be updated](https://github.com/department-of-veterans-affairs/vets-api/pull/15798#issuecomment-1997395820) as Prawn 2.5.0 tweaks them.

- [ ] Verify file sizes/differences are negligible
- [ ] Update PDF example files
- [ ] Merge [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15798) when passing

**Comment by ryan-mcneil** [comment]
Closing (duplicate: https://github.com/department-of-veterans-affairs/va.gov-team/issues/87290)
