### ISSUE TITLE
CF: Exclude filter - UI update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7898]
Update UI for Exclude filter & Learn more content

**Comment by ccruzgra** [comment]
CT  Caution Flags v0.3 - Filter Content Update: https://bahdigital.invisionapp.com/share/ZAIADJGP9QT

**Comment by ccruzgra** [comment]
Shared with BA Apr 16: https://bah-ssp.slack.com/archives/GH2AHGG7M/p1587048070062100
