### ISSUE TITLE
[UX] 10-10EZR TERA: Content Collaboration 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#79003]
As a Veteran, I would like to answer the TERA Questions online and clearly understand what is being asked so that I can disclose any toxins I was exposed to. 

- [x] Work with Aliyah in Figma to make suggested content changes
- [ ] Work through Use Cases with Aliyah (and investigate)
**Success:** We've reviewed the TERA questions with content and integrated their changes on Figma. Follow up to make sure they're reflected on the frontend

**Comment by JoshingYou1** [comment]
Two things that came up in demo:

1. Should we have more specific message for when a Veteran doesn't enter a year after entering a month and year previously?
2. Should we allow a Veteran to enter the same exact month and year for the To and From dates? Potential use case: Veteran was station at Camp Lejune for one month, was stationed somewhere with Agent Orange or nuclear waste for one month, etc.?
