### ISSUE TITLE
SLO for SSOe sessionscontroller overall availability

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#79006]

**Comment by joeniquette** [comment]
availability: https://vagov.ddog-gov.com/slo/manage?query=ssoe%20&slo_id=3aafb468eba75340a951c88d6f8e6759&tab=status_and_history&from_ts=1708547146336&to_ts=1711139146336&paused=false
latency: https://vagov.ddog-gov.com/slo/manage?query=ssoe%20&slo_id=8e7e0462451258b8ba83cb1749fe08c7&tab=status_and_history&from_ts=1708547162665&to_ts=1711139162665&paused=false

**Comment by joeniquette** [comment]
the latency ones use SLI (time slices) and they arent calculating a value. Ive pinged dd support to figure out why.

**Comment by rileyanderson** [comment]
> the latency ones use SLI (time slices) and they arent calculating a value. Ive pinged dd support to figure out why.

@joeniquette did you hear back from support? I was wondering about this too

**Comment by rileyanderson** [comment]
Looks like they fixed something. it just started to work
