### ISSUE TITLE
Flipper UI access for [Devin McCurdy]

### ISSUE THREAD

**Issue by devin-mccurdy** [department-of-veterans-affairs/va.gov-team#79000]
### Your Name

Devin McCurdy

### Your GitHub handle (Flipper UI access is managed through GitHub)

devin-mccurdy

### Team, Role, and Company of the target individual

Unified Appointment Experience Team, developer, Apothesource

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
confirmed in Atlas

SOCKS access, E-QIP confirmed

**Comment by bdech** [comment]
@devin-mccurdy You've been granted access to lower environments.
