### ISSUE TITLE
CT-EYB: VET TEC UI

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7901]
Refine concept
Discuss options w UX team
Update / refine

**Comment by ccruzgra** [comment]
GIBCT Estimate Benefits - VET TEC - v0.1: https://bahdigital.invisionapp.com/share/34IADJKHV5P

**Comment by ccruzgra** [comment]
@amyknox If this prototype needs no further adjustments, the story can be closed.
