### ISSUE TITLE
NoK/EC execute Canary phase of rollout

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#79017]
## User story

As a Cartography team member, I want to begin rollout phases per the launch plan when we've determined we're ready, so that we can get personal health care contacts to Veterans as quickly and confidently as possible.

## ACs
- ensured phone numbers update is merged
- notified VA Profile team (Jeff/Michael) of our intention so they can watch
- completed checklist below
- confirmed we are ready for Canary phase
- opened feature to >500 prod users and documented results in release plan
  - approach: 10% for 4 hrs should yield in the ballpark of 500 users

## Launch Readiness Checklist

Purpose: Confirm with the team that all preparations are complete **for Canary phase of roll-out** (activating the feature for just 500-1000 users in prod).

### Decision: GO

---
## Notes
- [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-health-care-contacts/release-plan/release-plan-mvp-mar-2024.md)
---

### UAT
Is smoke test complete?
- [x] Yes 
- [ ] No 

### BE 
Is monitoring and alerting configured and working as expected?
- [x] Yes 
- [ ] No 

Are you ready to monitor performance data for latency, errors, etc?
- [x] Yes 
- [ ] No 

### DEV 
Are there any Sev1 bugs or accessibility issues outstanding?
- [ ] Yes 
- [x] No

Are you ready to turn the feature on for 500 users?
- [x] Yes 
- [ ] No 

### PM/PO 
Is the Google Analytics/Datadog updated to track this product data and are they working as expected?
- [x] Yes 
- [ ] No 

Did you see KPI metrics populating from pilot? 
- [x] Yes – smoke-test pageview visible in GA
- [ ] No 
- [ ] N/A

Is call center ready to handle potential calls that may come in about the latest version profile (i.e. have we submitted our updated product guide)?
- [x] Yes 
- [ ] No 

Are you ready to monitor analytics data for trends and problems?
- [x] Yes 
- [ ] No 

Is the [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-health-care-contacts/release-plan/release-plan-mvp-mar-2024.md) complete and ready to execute against?
- [x] Yes 
- [ ] No 

### Everyone 
Does anyone have any concerns or reasons we should postpone a launch to 500+ users (canary)?
- [ ] Yes 
- [x] No

**Comment by radavis** [comment]
RE: KPIs and Datadog/GA concerns: add calls to `recordEvent()` in the frontend to inform analytics of user events.

**Comment by radavis** [comment]
Stage A Results [[doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-health-care-contacts/release-plan/release-plan-mvp-mar-2024.md#results-1)]: 

Results

    Number of unique users: [FILL_IN]
    Metrics at this stage (per your "success criteria"): [FILL_IN] a list that includes KPIs listed in the Rollout Planning section
    Was any downstream service affected by the change?: [PICK_ONE]: yes | no | N/A
    Types of errors logged: [FILL_IN]
    What changes (if any) are necessarily based on the logs, feedback on user challenges, or VA challenges? [FILL_IN]

**Comment by radavis** [comment]
The one 500 response recorded is from a user who is LOA2: [dd query](https://vagov.ddog-gov.com/logs?query=host%3Avets-api-web-66665dc776-knznl%20service%3Avets-api%20%40named_tags.remote_ip%3A%222003%3Aca%3A2739%3A89f0%3A51a7%3Aa93f%3Afdf5%3Ae03f%22&agg_q=%40http.status_code&agg_t=count&cols=host%2Cservice&context_event=AY7ELMrMAABOArf9tCap5AA1&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&top_n=10&top_o=top&viz=&from_ts=1712687951255&to_ts=1712688251471&live=false)
