### ISSUE TITLE
Duplicate chapter stepper showing on many forms

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#79012]
# Bug Report

- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

It seems that the logic in the [FormNav.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/2277b5a18452616ab53c7d1c1b8d3ba5aaebdeb0/src/platform/forms-system/src/js/components/FormNav.jsx#L145) in the Form System can't accommodate it when the v3SegmentedProgressBar isn't set explicitly in the form.js.

When `form.js` isn't set to: `v3SegmentedProgressBar: true,` you see the repeating info displayed.

Here is [an issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78775) that I created for the debt team.

Below are screenshots from a few other forms:

<img width="767" alt="Screenshot 2024-03-20 at 1 26 40 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/35079430-53c0-4b0c-8c44-08183fdd8e13">
<img width="962" alt="Screenshot 2024-03-20 at 1 26 59 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/720d9794-3cf1-484d-9e6b-bca4fe50bd54">
<img width="764" alt="Screenshot 2024-03-20 at 1 27 08 PM" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/1631062/2f4c23fc-f0b0-4b8e-b3d1-1e845ef76010">

## What I expected to happen

The form should only show the `segmented-progress-bar` component and not the old form system steps. 

Here is a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28646) I made for the FSR to fix the issue. 

## Reproducing

Here are a couple of forms it shows up on:

1. [10-10EZR](https://staging.va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/mailing-address) 
2. [VA Form 20-0995 - Supplemental claim](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/supporting-evidence/private-medical-records)

## Urgency
How urgent is this request? Please select the approriate option below and/or provide details
- [ ] This bug is blocking work currently in progress
- [ ] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [x] This bug is not blocking any work
- [ ] Other

**Comment by jeana-adhoc** [comment]
Adding a note here that the updated v3 Stepper is also loading with as an `<h4>` instead of the expected h2.  This is also happening on our [21-4142/4142a form](https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/).

**Comment by ndsprinkle** [comment]
This issue is staying open another sprint due to failing tests in the open pull request.

**Comment by ndsprinkle** [comment]
Closing the open PR to refactor this solution based on Robert's changes to the `v3SegmentedProgressBar` property here: https://github.com/department-of-veterans-affairs/vets-website/pull/30426

**Comment by rachelshearerux** [comment]
Looks good everywhere I've checked! 

|**Form** | **Environment** | **Screenshot** | 
|:--- |:--- |:--- |
| [20-0995](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/supporting-evidence/upload-evidence) | Staging | <img width="1098" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--296da6e0f47879d92030c3cfa92348e5be006b5f/20-0995%20-%20Duplicate%20stepper%20fixed.png" alt="20-0995 - Duplicate stepper fixed.png" />|
|[10-10EZR](https://staging.va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/contact-information)| Staging | <img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22cbcaaeadf841dc2f2e868713acc9c60b6e6509/10-10EZR%20-%20Duplicate%20stepper%20fixed.png" alt="10-10EZR - Duplicate stepper fixed.png" />|
| [21-0845](https://staging.va.gov/supporting-forms-for-claims/third-party-authorization-form-21-0845/security-information-answer)| Staging |<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--869b22e4975074ddd9b8915f7716a8b55677d2b9/Screenshot%202024-07-01%20at%203.30.53%E2%80%AFPM.png" alt="Screenshot 2024-07-01 at 3.30.53 PM.png" />|
| [40-0247](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247/identification-information) | Production | <img width="1263" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1sQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91ee52cdfc483e508db8fb918f5fa4944b07042a/40-0247%20-%20Duplicate%20stepper%20fixed.png" alt="40-0247 - Duplicate stepper fixed.png" />|
| [21P-0847](https://www.va.gov/supporting-forms-for-claims/substitute-claimant-form-21P-0847/preparer-personal-information) | Production | <img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5792dbd769f9a38d8d035dd27592384af369a92b/Screenshot%202024-07-01%20at%203.34.14%E2%80%AFPM.png" alt="Screenshot 2024-07-01 at 3.34.14 PM.png" />|
