### ISSUE TITLE
40-0247 Content changes: Step 6 (Your address)

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#79036]
## Issue Description
CAIA did another review of 40-0247 recently and asked for a few minor content changes.

The H3 shows a period at the end of the sentence, it should be removed

---
## Tasks
- [ ] Make 1 change to step 6: Your address
<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99dd6ff673f8eabd77f7735f85741cba295b616e/image.png" alt="image.png" />

## Acceptance Criteria
- [ ] Remove the period at the end of the H3
> Tell us where we should send the certificate.
---
[Figma](https://www.figma.com/file/U95x4PNKGVtA25aBvBdzrO/Prod---40-0247---Presidential-Memorial-Certificate?type=design&node-id=84-19902&mode=design&t=5QSu8vPg2JKie0ae-11)
[Source of Truth change log](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/pull/1146/files)

**Comment by tbaker1026** [comment]
Confirmed period has been removed
<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2hhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9d38f14ae9069b2ccd57cf49580bcecd01583bc/2024-04-12_16-05-17.png" alt="2024-04-12_16-05-17.png" />
