### ISSUE TITLE
40-0247 Content changes: Step 3 (Supporting documentation)

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#79035]
## Issue Description
CAIA did another review of 40-0247 recently and asked for a few minor content changes.

We still show a line above the file upload button "Upload documents" - CAIA would like us to remove it. 

---
## Tasks
- [ ] Make 1 change to step 3: Supporting documentation
<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07075b810a527a50d3e4590b3f23ff4e681b8b0d/image.png" alt="image.png" />

## Acceptance Criteria
- [ ] Remove the text above the "Upload file" button
> Upload documents
---
[Figma](https://www.figma.com/file/U95x4PNKGVtA25aBvBdzrO/Prod---40-0247---Presidential-Memorial-Certificate?type=design&node-id=84%3A19525&mode=design&t=5QSu8vPg2JKie0ae-1)
[Source of Truth change log](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/pull/1146/files)

**Comment by tbaker1026** [comment]
Verified Upload documents verbiage has been removed<img width="982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1phQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--300ce182d85d5d065279232eca0e395b0e189c57/2024-04-12_16-04-10.png" alt="2024-04-12_16-04-10.png" />
