### ISSUE TITLE
VFS Custom Events for MHV on VA.gov & MyHealtheVet on VA.gov

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#79041]
# VFS Custom Event Audit Form

Please see attached spreadsheet

[MHV on va.gov Custom GA Events.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14729802/MHV.on.va.gov.Custom.GA.Events.xlsx)

**Comment by johnny-jesensky-adhoc** [comment]
@carlosfelix2 - Thank you for submitting! Confirming we have this. We'll let you know if we have any questions on this.

FYI @jestutt

**Comment by rbsingleton** [comment]
@rbsingleton
