### ISSUE TITLE
CT-EYB: Dev Review - Full EYB Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7905]
Review UI and functionality with Dev team to promote seamless transfer of assets

**Comment by amyknox** [comment]
Walk-thru included traceability matrix as well.

**Comment by ccruzgra** [comment]
Reviewed all of the UI solutions for both mobile and desktop, to include 3 types of institutions: IHL, OJT, and VET TEC providers.

Introduced devs to Sketch Cloud file inspector tool. 

Reviewed Traceability Matrix.

Addressed need for a content file.
