### ISSUE TITLE
Place of last separation field on wrong page

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#79052]
In the 'Military History' chapter, the 'Place of last separation' field is mistakenly on the 'Other service names' page. It should be at the bottom of the 'Service period' page.

**Comment by aplatt-coforma** [comment]
Looks good.
<img width="447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmdPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c95072cbd3ba7e46e33e14a0b5f1c829062b9f28/screencapture-staging-va-gov-pension-application-527EZ-military-history-2024-03-26-06_27_20.png" alt="screencapture-staging-va-gov-pension-application-527EZ-military-history-2024-03-26-06_27_20.png" />
