### ISSUE TITLE
Vets-api terminal access for [Peter Hill]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#79059]
### Your Name

Peter Hill

### Your GitHub handle (terminal access is managed through GitHub)

@pjhill

### Your dsvagovcloud AWS user name (if applicable)

Peter.Hill

### Team, Role, and Company of the target individual

Platform Reliability Team, QA, Oddball

### Product Manager (PM) name and email

joe.tice@oddball.io

### Product Owner (PO) name and email

Aparna Nittala, Aparna.Nittala@omb.eop.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [ ] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need this access to address various support tasks including investigation of staging test user data as well as Test User Dashboard updates.

My original access request for AWS predates the requirement to attach e-qip transmittal -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/5037

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
@pjhill You've been granted access to `dev`, `staging`, and `sandbox` environments.
