### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by a6marinos** [department-of-veterans-affairs/va.gov-team#79078]
### Name

Michael Marinos

### Email

Michael.Marinos@va.gov

### Role

Product Manager

### Team

Benefits Representative Facing Team 

### Product Manager (PM) name

Jennifer Bertsch

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to Michael.Marinos@va.gov.

**Comment by naomimarcussen** [comment]
An account was created with mike.marinos@agile6.com instead of michael.marinos@va.gov.
