### ISSUE TITLE
[Certs] Update Certificates

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#79085]
- [ ] /ssl/dev-design.va.gov-2024.crt expires: 2024-05-29
- [ ] /ssl/dev-design.va.gov.chained-2024.crt expires: 2024-05-29
- [ ] /ssl/staging-design.va.gov-2024.crt expires: 2024-05-29
- [ ] /ssl/staging-design.va.gov.chained-2024.crt expires: 2024-05-29
- [ ] :warning: /ssl/dev-developer.va.gov-2024.crt expires: 2024-05-25
- [ ] :warning: /ssl/dev-developer.va.gov.chained-2024.crt expires: 2024-05-25
- [ ] :warning: /ssl/developer.va.gov-2024.crt expires: 2024-05-25
- [ ] :warning: /ssl/developer.va.gov.chained-2024.crt expires: 2024-05-25
- [ ] :warning: /ssl/staging-developer.va.gov-2024.crt expires: 2024-05-25
- [ ] :warning: /ssl/staging-developer.va.gov.chained-2024.crt expires: 2024-05-25
- [x] /ansible/deployment/config/fwdproxy/vaausvrsweb40.aac.va.gov.pem expires: 2024-05-25
- [x] /ansible/deployment/config/fwdproxy/vaausvrsweb20.aac.va.gov.pem expires: 2024-05-25
- [x] /ansible/deployment/config/fwdproxy/vaausvrsapp81.aac.va.gov.pem expires: 2024-05-24
- [x] /ansible/deployment/config/fwdproxy/api-gateway-lgy-dev-cert.pem expires: 2024-05-17
- [x] /ansible/deployment/config/fwdproxy/api-gateway-lgy-prod-cert.pem expires: 2024-05-17

**Comment by npeterson54** [comment]
Rolling into next sprint due to FOIA request and SFTP support request

**Comment by ph-One** [comment]
`vaausvrsweb20.aac.va.gov` was a part of EMIS and has been retired

**Comment by ph-One** [comment]
`vaausvrsapp81.aac.va.gov.pem` was a part of EMIS and has been retired

**Comment by ph-One** [comment]
The following are managed by LH and am waiting for them to submit a PR

developer.va.gov
staging-developer.va.gov
dev-developer.va.gov

**Comment by npeterson54** [comment]
Closing issue and adding unfinished certs (not a priority at the moment due to them being due at a later date)
