### ISSUE TITLE
Appointment Details Redesign - Content / CTA updates (view appointment details) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#79086]
## Description
As part of the Appointment Details Redesign initiative, our team will work on updating the content on the Appointment Details page. This update would help provide clarity on how the Veteran will attend or join their appointment. 

We will make updates to the existing appointment details page. This will not include the confirmation details screen (see ticket [#79364](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79364))

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

[Appointment types defined here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/backend-logic.md#appointment-types)

### In-person Appointments

- [x] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA In-Person`appointment
       Then the user will see the updated details page 
       And page design matches the `In Person` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195846&t=eMdLCpk0zzYtRNBt-4)

- [x] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA In-Person` appointment
       Then the user will see the updated details page 
       And page design matches the `In Person` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195846&t=eMdLCpk0zzYtRNBt-4)

- [x] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `VA In-Person` appointment
       Then the user will see the updated details page 
       And page design matches the `In Person` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195846&t=eMdLCpk0zzYtRNBt-4)

- [x] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA In-Person Vaccine` appointment 
       Then the user will see the updated details page 
       And page design matches the `In Person` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195846&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA In-Person Vaccine` appointment 
       Then the user will see the updated details page 
       And page design matches the `In Person` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195846&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `VA In-Person Vaccine` appointment 
       Then the user will see the updated details page 
       And page design matches the `In Person` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195846&t=eMdLCpk0zzYtRNBt-4)

### Video

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA Video Care at Home` appointment
       Then the user will see the updated details page 
       And page design matches the `Video` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195847&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA Video Care at Home` appointment
       Then the user will see the updated details page 
       And page design matches the `Video` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195847&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `VA Video Care at Home` appointment
       Then the user will see the updated details page 
       And page design matches the `Video` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195847&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA Video Care on GFE` appointment
       Then the user will see the updated details page 
       And page design matches the `Video` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195847&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA Video Care on GFE` appointment
       Then the user will see the updated details page 
       And page design matches the `Video` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195847&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their past `VA Video Care on GFE` appointment
       Then the user will see the updated details page 
       And page design matches the `Video` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195847&t=eMdLCpk0zzYtRNBt-4)

### Video at VA

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA Video Care at a VA location` appointment
       Then the user will see the updated details page 
       And page design matches the `Video at VA` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195872&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA Video Care at a VA location` appointment
       Then the user will see the updated details page 
       And page design matches the `Video at VA` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195872&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `VA Video Care at a VA location` appointment
       Then the user will see the updated details page 
       And page design matches the `Video at VA` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-195872&t=eMdLCpk0zzYtRNBt-4)

### ATLAS

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA Video Care at an ATLAS location` appointment
       Then the user will see the updated details page 
       And page design matches the `ATLAS` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-201335&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA Video Care at an ATLAS location` appointment
       Then the user will see the updated details page 
       And page design matches the `ATLAS` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-201335&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `VA Video Care at an ATLAS location` appointment
       Then the user will see the updated details page 
       And page design matches the `ATLAS` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-201335&t=eMdLCpk0zzYtRNBt-4)

### Phone

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `VA Phone` appointment
       Then the user will see the updated details page 
       And page design matches the `Phone` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-204420&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `VA Phone` appointment
       Then the user will see the updated details page 
       And page design matches the `Phone` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-204420&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `VA Phone` appointment
       Then the user will see the updated details page 
       And page design matches the `Phone` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-204420&t=eMdLCpk0zzYtRNBt-4)

### Community Care

- [x] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `Community Care`  appointment
       Then the user will see the updated details page 
       And page design matches the `Community care` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-207499&t=eMdLCpk0zzYtRNBt-4)

- [x] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `Community Care`  appointment
       Then the user will see the updated details page 
       And page design matches the `Community care` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-207499&t=eMdLCpk0zzYtRNBt-4)

- [x] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `Community Care` appointment
       Then the user will see the updated details page 
       And page design matches the `Community care` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-207499&t=eMdLCpk0zzYtRNBt-4)

### Claim Exam

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **upcoming** `Claim Exam` appointment
       Then the user will see the updated details page 
       And page design matches the `Claim Exam` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-210554&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Appointment list homepage 
       When the user clicks on `Details` for their **canceled** `Claim Exam` appointment
       Then the user will see the updated details page 
       And page design matches the `Claim Exam` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-210554&t=eMdLCpk0zzYtRNBt-4)

- [ ] Given the user is on the Past list  
       When the user clicks on `Details` for their **past** `Claim Exam` appointment
       Then the user will see the updated details page 
       And page design matches the `Claim Exam` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-210554&t=eMdLCpk0zzYtRNBt-4)

### VA Requests

- [x] Given the user is on the Pending list  
       When the user clicks on `Details` for their **pending** `VA appointment request` 
       Then the user will see the updated details page 
       And page design matches the `VA Request` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-213525&t=eMdLCpk0zzYtRNBt-4)

- [x] Given the user is on the Pending list  
       When the user clicks on `Details` for their **canceled** `VA appointment request` 
       Then the user will see the updated details page 
       And page design matches the `VA Request` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-213525&t=eMdLCpk0zzYtRNBt-4)

## Community Care Requests

- [x] Given the user is on the Pending list  
       When the user clicks on `Details` for their **pending** `Community care appointment request `
       Then the user will see the updated details page 
       And page design matches the `Community care request` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-215656&t=eMdLCpk0zzYtRNBt-4)
<br>
- [x] Given the user is on the Pending list  
       When the user clicks on `Details` for their **canceled** `Community care appointment request` 
       Then the user will see the updated details page 
       And page design matches the `Community care request` template in the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-215656&t=eMdLCpk0zzYtRNBt-4)

### Validate Test Cases
<details>
<summary>Use Case</summary>

- [ ] Validate upcoming VA In-person appointment (include Vaccine appointment) 
- [ ] Validate upcoming VA Phone appointment
- [ ] Validate upcoming VA Video appointment at home
- [ ] Validate upcoming VA Video appointment at VA location
- [ ] Validate upcoming VA Video GFE appointment 
- [ ] Validate upcoming ATLAS appointment
- [ ] Validate upcoming Community Care appointment 
- [ ] Validate upcoming Claim Exam appointment 
- [ ] Validate pending request for an appointment at a VA location
- [ ] Validate pending request for an appointment with a Community Care provider 
- [ ] Validate upcoming canceled VA In-person appointment
- [ ] Validate upcoming canceled VA Phone appointment
- [ ] Validate upcoming canceled VA Video appointment at home
- [ ] Validate upcoming canceled VA Video appointment at VA location
- [ ] Validate upcoming canceled VA Video GFE appointment 
- [ ] Validate upcoming canceled ATLAS appointment
- [ ] Validate upcoming canceled Community Care appointment 
- [ ] Validate upcoming canceled Claim Exam appointment 
- [ ] Validate a canceled pending request for an appointment at a VA location
- [ ] Validate a canceled pending request for an appointment with a Community Care provider 
- [ ] Validate past VA In-person appointment (include Vaccine appointment) 
- [ ] Validate past VA Phone appointment
- [ ] Validate past VA Video appointment at home
- [ ] Validate past VA Video appointment at VA location
- [ ] Validate past VA Video GFE appointment 
- [ ] Validate past ATLAS appointment
- [ ] Validate past Community Care appointment 
- [ ] Validate past Claim Exam appointment 
</details>

### Design Assets
[Figma file](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-(WIP)?type=design&node-id=2011-219410&mode=design&t=ICW5Ej9ETSB2jNkP-0)

### Reference
[Matrix](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)?type=design&node-id=2154-47915&mode=design&t=HP3Kp1PlP4cD2L1C-0) to test the appointment modality 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Copy doc updated 
- [ ] Figma file updated 

---

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta a lot of the AC aren't checked off, can you confirm this is ready?

**Comment by ldelacosta** [comment]
@outerpress - the data looks to be mocked data. I'm waiting to hear back from SPL team. 

As for the ATLAS update in caps, that bug [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84058) has been completed. 

Closing out the ticket.

**Comment by outerpress** [comment]
Thanks @ldelacosta the ATLAS content looks good to me!

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
