### ISSUE TITLE
Updates to Downtime notifications page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#79082]
### Description

A few updates for this page:

- [React code section](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Reactcode)
  - change line 7 of the code example from `} from 'platform/monitoring/DowntimeNotifications';` to `} from '@department-of-veterans-affairs/platform-monitoring/DowntimeNotification';`
- [Prerequisites section](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Prerequisites)
  - Change "The value must match that in the devops [config](https://github.com/department-of-veterans-affairs/devops/blob/67c1711a18486e0425bfb4795bb375bbe9fea31a/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L320)." to "The value must match that in the [vets-api manifest](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/4a67bb82f9e7614404a5eb2575fadce45a831a2e/apps/vets-api/prod/values.yaml#L2169)."
- [Configuration section](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Configuration)
  - Step 3 should read:
  > In the [Application Manifest repo](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests), add your service to the list of [maintenance services](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L441) in the `values.yml` file for each [vets-api environment](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api).
  - Step 4 should be removed
- [Testing section](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Testing)
  - The link for "PagerDuty::PollMaintenanceWindows job]" is broken and should be updated to point at https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/pager_duty/poll_maintenance_windows.rb

Thanks for your work on the site!

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Pagefooter-Helpandfeedback

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO Engineering

**Comment by jknipes** [comment]
Hi @acrollet , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by acrollet** [comment]
thanks @jknipes !

**Comment by jknipes** [comment]
work being done in [ticket 83375](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83375)

**Comment by CherylEvans** [comment]
[@acrollet](https://github.com/acrollet) [@jknipes](https://github.com/jknipes) I made the changes to the source page. The updates will be published when we run SVP at 3:30 PM ET.

**Comment by CherylEvans** [comment]
@acrollet @jknipes Platform page is updated successfully; closing ticket [83375](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/83375)

**Comment by jknipes** [comment]
@acrollet work has been completed as above, closing this request ticket
