### ISSUE TITLE
Publish prep course content

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#79113]
## Description
We need to migrate this legacy PDF to this modern page:

- Legacy PDF: [Preparatory Course](https://www.benefits.va.gov/BENEFITS/factsheets/education/PC.pdf)
- Modern page: [Undergraduate and graduate degrees](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/)

### Step 1: Recommend
- [x] DB: Recommend updated content design for the modern page
- [x] AP: Review recommendation
- [x] DB: Share with BP

### Step 2: Update
- [x] DB: Update modern page in Drupal
- [x] AP: Review
- [x] AP: Share with BP
- [x] BP: Review
- [x] AP: Share with stakeholders
- [x] Stakeholders: Review
- [x] BP: Share with RH to copyedit and publish
- [x] RH: Copyedit and publish

### Step 3: Redirect
- [x] DB: Work with IA to open a redirect ticket

Redirect this legacy URL:

- www.benefits.va.gov/BENEFITS/factsheets/education/PC.pdf

To this modern URL:

- www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/

## Criteria
- [x] Published updated modern page
- [x] IA opened a redirect ticket for the legacy URL

**Comment by aprocik1** [comment]
@d-beyer, Beth and Danielle recommended that we place the prep course content on [this page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/). But after reviewing it more closely, I think you're right that it should be its own page. 

Can you draft the content for this new page in a SharePoint document?

<details>
<summary>I've drafted this page design for you to consider:</summary>
[H1] Get paid back for prep courses

[Intro] [Rewrite "What is a preparatory course?" content from PDF.]


[Start of featured content box]
[H2] Am I eligible to get paid back for prep courses?
[Rewrite "Who qualifies for payment of preparatory course?" content from PDF.]
[End of featured content box]

[H2] What prep courses can I take?
[Rewrite "What preparatory courses are approved for VA benefits?" content from PDF. This can be a variation of this content I'm rewriting for the Fry Scholarship page:

> First, make sure we've approved the school you'd like to attend. You can use our GI Bill Comparison Tool to find out which schools we’ve approved.
> 
> [Use the GI Bill Comparison Tool](https://www.va.gov/education/gi-bill-comparison-tool/?_ga=2.260819661.1383470612.1712667432-2037629338.1694720648)
> 
> Then, make sure we've approved the program you'd like to enroll in. You can contact the school’s certifying official to ask them which of the school's programs we've approved.]

[H2] How many prep courses can I take?
[Rewrite "How many preparatory courses can I pursue?" content from PDF.]

[H2] How do I get paid back for prep courses?
["How do you apply for payment of preparatory courses?" content from PDF.]

[H2] How will you charge my benefits for prep courses?
["How is your education entitlement charged?" content from PDF.]
</details>
And I used these pages as references for the design:

- [Get paid back for test fees](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/)
- [Tuition Assistance Top-Up](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/)
- [Undergraduate and graduate degrees](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/)

The content you draft doesn't have to be final. We just need to demonstrate why a new page may be necessary. Let me know if you want to discuss this together. Thanks!

**Note:** I'm not sure if "get paid back" is the right framing for this page. We'll need to ask SMEs if VA pays for these courses before or after Veterans complete them.

**Comment by d-beyer** [comment]
@aprocik1 Here's a rough draft in a [SharePoint doc](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/Shared%20Documents/1.0%20Migration%20work/Education%20service/Draft%20-%20Preparatory%20course.docx?d=wae75a2604a714a85b8242326e34a0d4a&csf=1&web=1&e=9isnnZ). I continue to think this makes sense as its own page.

**Comment by aprocik1** [comment]
Thanks, @d-beyer! I think you're right about this being its own page.

If you feel good about this page design, can you send the SharePoint document to Beth?

You can mention that we're not seeking her review of the content yet. Instead, we're seeking her approval to publish a new page, since her and Danielle recommended that we place the content on [this page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/). If she approves, you and I can draft the content and send it to her for a full review in the future.

**Comment by d-beyer** [comment]
On 4.24, Beth said that there would be more work on this subject matter later this year and for now, we should just add the content as a Q&A on the "undergraduate and graduate degrees" page. I'm proceeding with that work.

**Comment by d-beyer** [comment]
Hey @aprocik1 -- I took our draft and worked through how to add the information to the "undergraduate and graduate degrees" page. 

The funny thing I ran into is that our prep course content draft is explicit about a bunch of stuff (eligibility, how to get benefits, how to find approved courses) that also applies to under/graduate degrees but that isn't talked about on this page. For that reason, I think the only new information that it makes sense to include here is "yes you can use your benefits to take prep courses". 

I left comments in our [draft document](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/Shared%20Documents/1.0%20Migration%20work/Education%20service/Draft%20-%20Preparatory%20course.docx?d=wae75a2604a714a85b8242326e34a0d4a&csf=1&web=1&e=GLOYMs) and added the [new Q&A in a Drupal draft](https://preview-prod.vfs.va.gov/preview?nodeId=929). Let me know what you think.

**Comment by aprocik1** [comment]
Thanks @d-beyer. I think you've included the right information in this Q&A. We may want to consider adding the GI Bill Comparison Tool to help find prep courses, but let's exclude it for now. We can add it if Beth or SMEs raise this in their review.

I'd like to simplify this sentence: "You can use any GI Bill benefits to pay for prep courses for tests that are used for admission to institutions of higher learning."

And I'd like to clarify what a "prep course" is. (I think they help you prepare for admissions tests.)

What do you think about any of these 3 options? Feel free to edit as you see fit!

> Can I use the GI Bill to pay for prep courses?
> 1. Yes. You can use any GI Bill benefits to pay for courses that help you prepare for admissions tests, like the ACT or SAT.
> 2. Yes. Your program or school may require you to take admissions tests, like the ACT or SAT. You can use any GI Bill Benefits to pay for prep courses that help you prepare for those tests.
> 3. Yes. Prep courses help you prepare to take admissions tests, like the ACT or SAT. You can use any GI Bill benefits to pay for those prep courses.
> **Note:** Your program or school may not require you to take an admissions test.

**Comment by d-beyer** [comment]
@aprocik1 -- Thanks, as always, for thoughtful edits. I think the first one is best. Very straightforward. I've updated Drupal. Should I share it with Beth?

**Comment by bethpottsVADEPO** [comment]
@d-beyer @aprocik1 Thanks for working up this Q&A. I would include a bit more info, and I think you should ask SMEs the best way to check which prep courses are approved. Is that through the GI Bill Comparison Tool? Their PDF has a link to "Choosing a School" but I find that confusing. Which link is the user supposed to use once they arrive at that page? I think we could get more specific. I included link text below that would point to whatever the SMEs say is the best place to find this info:

**Can I use my VA education benefits to pay for preparatory courses?**

Yes. You can use your VA education benefits to pay for courses that help you prepare for admissions tests required for college or graduate school. These "prep courses" include the SAT, the ACT, and others. There's no limit to the number of prep courses you can take as long as you have remaining entitlement and you use your benefits within the time limit you're eligible. You'll need to ask the school's certifying official to submit an enrollment certification to us for the prep course.
[Find out which prep courses are approved for VA education benefits]

**Comment by aprocik1** [comment]
Update: Derek emailed a preview link and screenshot of Beth's content to Tammy with these two questions:
- Where should the link at the end of the Q&A point to? The prep course PDF links to [Choosing a GI Bill approved school](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Feducation%2Fchoosing-a-school%2F&data=05%7C02%7C%7Ca171d5bcc35b495d2a8c08dc84b31040%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638531151801751104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ZqN40U2lm%2Fgpq4tw8k%2FSntLOpY0%2BMTUulgZ%2FSAC60Wg%3D&reserved=0), but that seems too broad. Is there a specific place on that page they should be going? Should we point to the GI Bill Comparison Tool?
- Is the Q&A otherwise acceptable?

**Comment by aprocik1** [comment]
Update: SMEs haven't followed up on Derek's questions above. I'm working with Beth via Slack to determine the best path forward for restarting this conversation with SMEs.

**Comment by aprocik1** [comment]
I'll take these next steps from Beth:

- Add to the Q&A any information that Tammy pointed to that you know for sure is accurate because it's straight from the form (avoid what you think is mixing apples/oranges as Cinda alluded to). Include the info about needing to already have applied and been approved for VA education benefits. And you need to request reimbursement after you've taken the class--you don't get paid ahead of time. And you need to include the receipt.
- Reply all to the latest message from Cinda and provide a Sharepoint doc that Education Service can edit in. Just say something like, "We wanted to follow up with you, Cinda, now that you're back. To make the feedback a little easier for you to provide, here's a Sharepoint file. We've made some updates according to the additional info from the application that Tammy pointed to with screen shots. Thanks for helping us make sure the content is thorough and accurate."
- Ask this again: Where should the link at the end of the Q&A point to? The legacy PDF links to [Choosing a GI Bill approved school](https://www.va.gov/education/choosing-a-school/), but that seems too broad. Is there a specific place on that page Veterans should go to? Should we replace this with a link to the [GI Bill Comparison Tool](https://www.va.gov/education/gi-bill-comparison-tool/)?

**Comment by aprocik1** [comment]
Update: Cinda provided feedback in a meeting with Beth and I. Then we made updates in this [SharePoint document](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EZM0M4uHqe1Jm5SBlbmEF4oBL2nB39Vf7O_kky6lfYiW6w?e=kbbjmy).

Next steps: Beth is researching one outstanding question. After she confirms the answer to that question, I'll update the document and share it with Cinda for a final accuracy review.

**Comment by aprocik1** [comment]
@megzehn and @saratorres2, this page is ready for your copyedit. I'm waiting for final approval from SMEs, so please don't publish it yet. 

Here's the [Drupal preview](https://preview-prod.vfs.va.gov/preview?nodeId=929). This is the new Q&A we've added: Can I use my VA education benefits to pay for preparatory courses?

Beth's goal is to publish this page by EOD today. I'll let you know when SMEs confirm. Thanks!

**Comment by aprocik1** [comment]
Update: I've incorporated SMEs' final feedback,. This page is ready to publish.

Next steps: Beth asked Randi to copyedit and publish this page. After it's published, I'll follow up with SMEs to let them know.

**Comment by aprocik1** [comment]
Update: This Q&A is now live on VA.gov: [Undergraduate and graduate degrees](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/)

@d-beyer, can you ask Jenny to include this redirect in her next batch? Thanks!

**Comment by bethpottsVADEPO** [comment]
We'll need to redirect the 2 enrollment verification legacy pages once that work is done. I think those will be the last 2 redirects needed. But I wouldn't let that hold up any communication Jenny might have queued up for education stakeholders since the timeline for publishing the EV FAQ is kind of uncertain.

**Comment by aprocik1** [comment]
Update: Based on SME feedback, we're publishing this new Q&A as a separate resources and support page (in additional to keeping it on the "undergraduate and graduate degrees" page). We'll redirect the prep courses PDF to the new resources and support page. I've moved this ticket back to in progress to reflect our ongoing work on migrating this page.

**Comment by aprocik1** [comment]
Update: In order to publish this content as a standalone resources and support page, it needs to be a "reusable Q&A" in Drupal. This type of Q&A has a character limit of 1,000, which includes spaces. As a result, I had to shorten the content that SMEs already approved. Here's the most up-to-date draft: [Prep course reusable Q&A](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EXa3T6MPLtZGgGe4ui7mPygBPiogtb1ftJT-xuq_GwQshQ?e=MC6KBu)

Next steps: I'll review this draft with Beth on Monday 7/15 before following up with SMEs and before creating the "reusable Q&A" in Drupal.

**Comment by aprocik1** [comment]
Update: I've created this new reusable Q&A and standalone R&S page: https://prod.cms.va.gov/resources/can-i-use-my-va-education-benefits-to-pay-for-preparatory-courses

And I've added the reusable Q&A to this existing page: https://prod.cms.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs

@megzehn and @saratorres2, can you two copyedit and publish this page at the end of this week? I'm not expecting anymore feedback, but it's possible that SMEs respond with a last minute update. Thanks!

Note: After we publish this page, we'll need to redirect the legacy prep courses PDF to the new standalone R&S page.

**Comment by aprocik1** [comment]
@megzehn, Beth has officially approved this page. Can you copyedit and publish it by the end of this week? Thanks!

**Comment by megzehn** [comment]
@aprocik1 I reviewed and published these 2 nodes. Thank you so much for your work on this!!

**Comment by aprocik1** [comment]
Update: I've shared the live link with SMEs and asked Jenny to implement the redirect from the legacy PDF to the new standalone resources and support page. I'm moving this ticket to validate, but keeping it open for now in case we need to return to it.

**Comment by aprocik1** [comment]
Update: The redirect has been implemented. I'm closing and tracking this ticket as complete.
