### ISSUE TITLE
CT-103: Testing Prototype

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7911]
Create prototype for back-up testing situation

**Comment by ccruzgra** [comment]
GIBCT PL 115-407 Section 103 v0.2 for Testing: https://bahdigital.invisionapp.com/share/QHIADJPTRJ8

**Comment by ccruzgra** [comment]
@amyknox If this prototype needs no further adjustments, the story can be closed.
