### ISSUE TITLE
Assess tuition assistance PDF

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#79111]
## Description
We need to migrate the content on this legacy PDF:

- [Tuition Assistance, Tuition Assistance Top-Up and VA Benefits](https://www.benefits.va.gov/BENEFITS/factsheets/education/TU.pdf)

Some of the content already exists on these modern pages:

- [Tutorial assistance](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance/)
- [Tuition Assistance Top-Up](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/)

### Step 1: Assess legacy and modern content
- [x] DB: Assess the legacy PDF and modern pages to determine what content still needs to be migrated
- [x] DB: Recommend where the legacy content should be migrated on the modern site
- [x] AP: Review recommendation

### Step 2: Draft and update content
- [x] DB: Draft remaining legacy content in Drupal, if necessary
- [x] DB: Replace links to the legacy PDF with links to relevant modern pages in Drupal
- [x] AP: Review
- [x] DB: Share with BP
- [x] BP: Review
- [x] DB: Share with stakeholders
- [x] MZ, ST: Copyedit and publish

## Criteria
- [x] Content on the legacy PDF has fully migrated to the modern site
- [x] Links to the legacy PDF are removed from the modern site

**Comment by d-beyer** [comment]
@aprocik1 I compared the PDF for tuition assistance to the modernized page. The only information that the modern page doesn't explicitly state is:
- You must be enrolled in education benefits to use Tuition Assistance Top-Up.
- TATU only applies to programs approved by VA.

But would we say that on this sort of page? Or is it implied by the fact that we're in the "How to use your GI Bill benefits" section? At most, this would be a line or two and a link to applying for benefits / checking that your program is approved.

Here's a quick and dirty [Google doc of the PDF content](https://docs.google.com/document/d/1R5M4NY9SPezx8BIpJc-WOTOzBrmxF4sZa_uMLQakcnk/edit?usp=sharing) that notes what's already covered or doesn't need to be.

**Comment by aprocik1** [comment]
@d-beyer, thanks!

> You must be enrolled in education benefits to use Tuition Assistance Top-Up.

I think is covered with this H2: How do I get these benefits?

> TATU only applies to programs approved by VA.

I think we should add a Q&A about the approved programs. This is something we need to clarify on a number of our other education pages also.

<details>
<summary>Here's the content I've drafted for other pages:</summary>

> First, make sure we’ve approved the school you’d like to attend. You can use our GI Bill Comparison Tool to find out which schools we’ve approved.
>
>[Find approved schools with the GI Bill Comparison Tool](https://www.va.gov/education/gi-bill-comparison-tool/)
>
>Then, make sure we’ve approved the program you’d like to enroll in. You can contact the school’s certifying official to ask them which of the school’s programs we’ve approved.

</details>

**Comment by d-beyer** [comment]
@aprocik1 Thanks! I missed that H2 under the line break. Is there a reason the line break is there? I can imagine users overlooking it as well.

Is it alright if I move to Step 2 and work your text into the Drupal page?

**Comment by aprocik1** [comment]
@d-beyer, yup, feel free to move into step 2. Thanks!

Context on horizontal lines: We're no longer adding them to any new pages. Research found that users stopped reading once they reached them--so your experience is true to others'.

**Comment by d-beyer** [comment]
@aprocik1 I added the new Q&A to the [Tuition Assistance Top-Up page](http://preview-prod.vfs.va.gov/preview?nodeId=927). I also removed the Q&A that linked to the legacy PDF.

The instructions above say to replace links to the legacy PDF with links to relevant modern pages. Do we have a list of where those are, or is there a way to get a list? Or should I dig around?

**Comment by aprocik1** [comment]
@d-beyer, thanks! I made 3 updates--any and all feedback welcome.
- I changed the question to this: Where can I use these benefits? This matches the way we ask a similar question on the [DEA page](https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/).
- I moved the question to be second to last on the page. I think it makes sense to place it directly above this question: How do I get these benefits?
- I shortened the content I drafted for the other education pages. Now it's 2 sentences and a link.

I also used the content audit tool in Drupal to search for "top-up" on all VA.gov pages. I think the only place we link to the legacy PDF on the modern site is the current [Tuition Assistance Top-Up page](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/). Let me know if you want a demo on using the content audit tool in Drupal.

**Comment by aprocik1** [comment]
@d-beyer, I incorporated Beth's edits in Drupal. This page is ready to share with stakeholders for an accuracy review. Thanks!

**Comment by d-beyer** [comment]
Update: I shared the draft with Tammy.

**Comment by d-beyer** [comment]
Update from 05.01 meeting with SMEs:
- Important distinction: SMEs say that VA approves programs, not schools.
- AP says that this contradicts a lot of information currently on the modern site. We need to investigate further.

**Comment by d-beyer** [comment]
@aprocik1 I tweaked the text based on SME input. I changed the language about approving schools to approving programs. 

We can talk about this at our sync, but I think we can move forward.

**Comment by d-beyer** [comment]
Hi @megzehn -- We added a new Q&A to the Tuition Assistance Top-Up page in order to migrate a legacy page. That's the only change/addition we made here. It's ready for your copyedit and publishing.

- [Preview: Tuition Assistance Top-Up page](http://preview-prod.vfs.va.gov/preview?nodeId=927) (Q&A: How do I know if I can use these benefits for my program?)
