### ISSUE TITLE
Removing Maurice Okumu from DSVA Slack

### ISSUE THREAD

**Issue by Maurice-Okumu** [department-of-veterans-affairs/va.gov-team#79122]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Please remove Maurice Okumu from DSVA slack as he is rolling off the VA account. Thank you

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by zinalpatel09** [comment]
@LEHigley - hello! Any update on this request?  thank you!
