### ISSUE TITLE
VFS Custom Events for Accredited Representative Management & Find a Representative

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#79127]
# VFS Custom Event Audit Form

Linking the Accredited Representative Management team's [Custom Event Google sheet](https://docs.google.com/spreadsheets/d/1UVRIbTAzw7hRfxonWen6OshVaXkcaKZ7H3PR8-1C3-A/edit#gid=2087351809) for Find a Representative.

### What this form is for.
---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.

- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by johnny-jesensky-adhoc** [comment]
@cosu419 - Thank you for the submission -- confirming we have these. We'll reach out if we have any questions on these.

FYI @jestutt, @oddball-lindsay

**Comment by jestutt** [comment]
@cosu419  Can you please add the file with your custom events? 

cc @johnny-jesensky-adhoc

**Comment by jestutt** [comment]
> @cosu419 Can you please add the file with your custom events?
> 
> cc @johnny-jesensky-adhoc

Nevermind. I see the link now.
