### ISSUE TITLE
Confirm cooperative rate for rates pages

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#79123]
## Description
We need stakeholders to confirm if cooperative rates should be added to from these legacy pages to these modern pages:

**Chapter 30**
- Legacy page: [Montgomery GI Bill active duty (Chapter 30) increased educational benefit](https://www.benefits.va.gov/gibill/resources/benefits_resources/rates/ch30/ch30rates100120.asp)
- Modern page: [Past rates: 2020-21 MGIB-AD](https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/past-rates-2020-2021/)

**Chapter 35**
- Legacy page: [Survivors' and Dependent's - (DEA/Chapter35) Increased Educational Benefit](https://www.benefits.va.gov/gibill/resources/benefits_resources/rates/ch35/ch35rates100120.asp)
- Modern page: [Past rates: 2020-21 Chapter 35](https://www.va.gov/education/benefit-rates/chapter-35-rates/past-rates-2020-2021/)

**Chapter 1606**
- Legacy page: [Montgomery GI Bill-SR (Chapter 1606) Increased Educational Benefit](https://www.benefits.va.gov/gibill/resources/benefits_resources/rates/ch1606/ch1606rates100120.asp)
- Modern page: [Past rates: 2020-21 MGIB-SR](https://www.va.gov/education/benefit-rates/montgomery-selected-reserve-rates/past-rates-2020-2021/)

**Note:** We may need to update this modern page as a part of this work: [Co-op training](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/co-op-training/)

### Step 1: Update, if necessary
~~- [ ] Stakeholders: Confirm if cooperative rates need to be added to the modern pages above~~
~~- [ ] DB: Update pages in Drupal~~
~~- [ ] AP: Review~~
~~- [ ] AP: Share with BP~~
~~- [ ] BP: Review~~
~~- [ ] DB: Share with stakeholders~~
~~- [ ] Stakeholders: Review~~
~~- [ ] MZ, ST: Copyedit and publish~~

### Step 2: Redirect
- [x] DB: Work with IA to open redirect tickets for the legacy > modern URLs above

## Criteria
- [x] Stakeholders confirmed that cooperative rates don't need to be added to the modern site, or cooperative rates have been added to the modern site and those updated pages have been published
- [x] IA opened redirect tickets for the legacy URLs

**Comment by d-beyer** [comment]
Beth marked that these pages can now be redirected in the audit spreadsheet. I've sent them to Jenny Mayo to be redirected.

Based on that, I don't think we have to make any updates. I'm crossing off step 1 unless we hear differently later.
