### ISSUE TITLE
'Is your child disabled?' question updates

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79129]
### Why do this?
We found two issues:
1. Currently, the “Is your child seriously disabled?” field only displays if the child is under 17.75 years old. Based on instructions in the form (bullet one), this logic is not accurate.
2. On the web form, the instructions that help them answer accurately are hidden in the info component. If they don't read it, they can wrongly answer the question.
<img width="1696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a59e31ba1f4be133b7fec31110eca6ae7ebae3cd/image.png" alt="image.png" />

## To do
1. Establish if any other logic is at play (other than for age)
2. Remove age-based logic so that this question is visible when inputting data about children, regardless of their age
3. Update how info content is shown
4. For in progress forms, remove their response to this question so that they can answer it again

## AC
1. Veterans with children are able to accurately answer this question
2. This change does not cause any issue with the schema / PDF generation / form submission

**Comment by gmaciolek** [comment]
Slack thread for reference: https://dsva.slack.com/archives/C05MS96P6P2/p1711139982710449

**Comment by echin393** [comment]
While reviewing options to represent the information differently (updated language, breaking up the question into two, breaking up the page itself), we found opportunities to zoom out and conduct further discovery into how questions and their conditionals are grouped.

The recommendation here is to scope down the ticket to just remove the age-based logic, displaying this question for any veteran with dependents. Then, create a separate discovery ticket on where/how household questions are asked. 

cc @gmaciolek @buddhima-coforma @aplatt-coforma

**Comment by buddhima-coforma** [comment]
Nice! I'm leaning towards the options where it's not in the hint (3 and 4). Work with Gretchen and run it by Julie/Dene when you're ready to share.

**Comment by echin393** [comment]
Sorry! I should've clarified – I reviewed these options with Gretchen and Julie during the research/design sync earlier this week, but the feedback was that the variants that break up the language require bringing it back to the collaboration cycle, and also surfaces inconsistencies in the use of conditional questions vs. conditional pages throughout the rest of the form. 

The recommendation Gretchen and I aligned on was to only remove the age-based logic for this ticket, so that there can be further discovery to determine if questions are grouped appropriately.

**Comment by aplatt-coforma** [comment]
Matt created the engineering ticket to remove the conditional logic here #80086: Remove age-based logic in "is your child disabled question"

Followup design ticket is here: #80269: Further design exploration for Is your child disabled?

**Comment by aplatt-coforma** [comment]
Closing this ticket as done now that we have the followup tickets.
