### ISSUE TITLE
[Discovery] Find out where/how to add link to travel pay claims page

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#79138]
## Description
In order to allow Veterans to easily find the travel pay claims status page, we need to add a link to the travel pay section on the mhv landing page. First we need to figure out what code needs to be changed in order to do that.

This ticket is not a blocker to the "real" claims page because for demonstration purposes, we can navigate to the claims page direclty

## Acceptance Criteria
- [ ] We have documented what code needs to be changed in order to link to the claims page
- [ ] We have documented any process or contacts we need to keep informed of our changes

## Demo
- Demoable? No
- How?
- Impact?

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by kjduensing** [comment]
File and code section: https://github.com/department-of-veterans-affairs/vets-website/blob/4e54a9f9d7e823ec96921a8f5050ef396fd5bd82/src/applications/mhv-landing-page/utilities/data/index.js#L145-L158

Not sure who we need to notify (if anyone) of the changes we make.

**Comment by kjduensing** [comment]
in `mhv-landing-page/utilities/data/index.js` around L145, add:

```javascript
{
      href: '/our/link/here',
      oldHref: null,
      text: 'Check travel claim reimbursement status',
      toggle: null, // we should find out how this is related to feature toggles
    },
```

**Comment by ayush-chak** [comment]
Team to reach out to Florence, Jonathan, and Sarah to determine next steps

**Comment by kjduensing** [comment]
This can be closed with [advice from Jim Z](https://dsva.slack.com/archives/C04DRS3L9NV/p1712086096463979?thread_ts=1712082887.913079&cid=C04DRS3L9NV).

> just open a PR for that link change on the homepage and github should automatically tag the vfs-mhv-integration team as reviewers
