### ISSUE TITLE
Implement frontend claims status page with fake data

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#79139]
## Description
As the designs are starting to stabilize, we should begin implementing the "real" claims status page. This could involve moving code over from the scaffold, moving code over from the codepen implementation, or a hybrid of the 2.

## Acceptance Criteria
- [ ] We have a location on VA.gov (a URL) where this page can be accessed
- [ ] I can hit staging.va.gov/endpoint/here as Nolle Barakat and see a list of claim summaries in various states
- [ ] The claims page should match as closely as possible the designs, but may exclude
  - [ ] filters
  - [ ] pagination

## Demo
- Demoable? Yes
- How? staging.va.gov/endpoint/here as Nolle Barakat
- Impact? Show initial implementation of designs

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by micahtaylor** [comment]
Put my code in [this branch](https://github.com/department-of-veterans-affairs/vets-website/compare/main...design-prototype). Jsut a heads up that I had to remove a lot of the legit code as the linter was freaking out and I couldn't figure out why `/* eslint-disable  */` wasn't working.
