### ISSUE TITLE
Document schema changes and  local development using yarn link

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#79183]
# Overview
Document the process to do local development using yarn link
Document the process to do schema changes

# Acceptance
- [ ] - Should provide clear documentation and steps for other engineers how to do schema changes
- [ ] -  Should provide clear documentation how yarn link can be used to rapidly prototype locally.

**Comment by wayne-weibel** [comment]
I would also like to have a simple script to facilitate the link and unlink for local development.
