### ISSUE TITLE
Access for Steve Wirt

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#792]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
Mary O'Toole
- Please provide your name.
Steve Wirt
- Please provide the name of your team, your role on that team, and the name of the company you work for.
116 VA Modernization through Agile6
I work for CivicActions
and am the Technical Architect on the project.

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCAsjy06Fb/O9hT1m8No7wWDrWe9UErSHOGYmXL7Z9eooxPvVFHKaNtG6/BFDaZBPAE+5SQDQXVOxRRXlA1uZX6rqFGrmWhdUHcRBppUihkd1q2EK8NwaR/mnGcL3gxWVIrVvMA62p4Y9bOyPa+z6fpzP8APDEfZ3r/TMLfxWtQUjGeJHtd3F7atUwAOzEQ7cBgEhjGA5xao132QgmDXmfaA2xeQekW869tUxege4hPHpjW36N0H9ydnfBQC038EO3ymEATxyUi0d9myITv6hsCi0UeujU9R/ufT0suUXToeLlbzjmAhdLBlntSud7WimsT3l+rmUc+1vqN1qvckQD swirt@Swirtubuntu

 
- [Grant AWS Console access?]
Yes

**Comment by swirtSJW** [comment]
@department-of-veterans-affairs/vsp-operations Request from Steve Wirt

**Comment by b00klegger** [comment]
@swirtSJW 
Hiya Steve, I think your edits got lost in the post. Can you update your issue with the COR name, team information, your SSH key and AWS access request?

**Comment by swirtSJW** [comment]
@b00klegger   Sorry about that, not sure where it went.   It is all there now.

**Comment by b00klegger** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Steve Wirt

Can you confirm? Thx! Happy Friday!

**Comment by swirtSJW** [comment]
@Jeff-Hayter   Just refreshing this to try to get it moved along.

**Comment by Jeff-Hayter** [comment]
@swirtSJW They're working on it.  The person who manages your paperwork has been out due to family emergency.  If you have a copy of your approved e-QIP submission (just the email) that will help expedite things.

**Comment by swirtSJW** [comment]
@Jeff-Hayter  Thank you.  They may have gone out before initiating my eQIP as I have not received an eQIP invitation yet. (unless they are using my previous clearance from DOJ or Dept of Ed).

**Comment by robrasmussen1970** [comment]
@Jeff-Hayter, is there anything we can do to move this along?  @MaryO-USDS, do you have any ideas?

**Comment by ElijahLynn** [comment]
@b00klegger @tskinn normally this is just adding ssh key to proxy. Did the process change?

**Comment by b00klegger** [comment]
@robrasmussen1970 Please refrain from tagging any other folks on this issue. 
@ElijahLynn We are waiting for eQIP paperwork before we can move forward. The workflow has been recently revised to ensure that folks joining the project have started the background check process.

**Comment by ElijahLynn** [comment]
> @robrasmussen1970 Please refrain from tagging any other folks on this issue.
> @ElijahLynn We are waiting for eQIP paperwork before we can move forward. The workflow has been recently revised to ensure that folks joining the project have started the background check process.

Thanks for clarifying that the process has changed!

**Comment by ElijahLynn** [comment]
> @swirtSJW They're working on it. The person who manages your paperwork has been out due to family emergency. If you have a copy of your approved e-QIP submission (just the email) that will help expedite things.

@Jeff-Hayter Do you know if there is anyone else who can help with initiating the e-QIP paperwork? This was unexpected with our application engineering leads changing and is really affecting our team right now.

**Comment by ElijahLynn** [comment]
> > @swirtSJW They're working on it. The person who manages your paperwork has been out due to family emergency. If you have a copy of your approved e-QIP submission (just the email) that will help expedite things.
> 
> @Jeff-Hayter Do you know if there is anyone else who can help with initiating the e-QIP paperwork? This was unexpected with our application engineering leads changing and is really affecting our team's progress right now.

We don't even have the e-QIP submitted yet, and @swirtSJW hasn't even gotten the e-QIP initiation email yet.

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/63433926-11399880-c3f2-11e9-8361-2b11a1006704.png)

Hopefully this can be moved along now.   Let me know if you need something more.

**Comment by Jeff-Hayter** [comment]
@ricetj @b00klegger Confirmed.  Please grant access.

**Comment by b00klegger** [comment]
@swirtSJW Access has been deployed and notice sent to user with AWS credentials. Please repoen ticket if experiencing issues.
