### ISSUE TITLE
Clarify medical evidence request

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79210]
### Learnings research
Most participants (P1,P3,P4,P5,P8,P10,P15) **didn't notice the alert** stating that they would need to provide medical evidence. This alert appears after selecting ‘NO’ to the question of whether they receive social security disability benefits.  For those who were explicitly prompted to read the alert, **none of them understood why they would need to provide medical evidence in this situation**, and some even assumed it was an error on the part of the application and continued.  These assumptions may result in incomplete application submissions. 

**P3**: Doesn't understand the pop-up box.  Thinks if he responded yes that he would need to provide some medical history.
**P4**: "It says you'll need to provide medical evidence with this application but I'm not requesting anything so that seems like kind of a stupid pop up"
**P5**: [after selecting no to receiving SS disability payments] "I said no but then I get a notice saying I need to provide medical evidence. I'd think that's a goof because I don't have any evidence that I'm not receiving it."
**P10**: Assumed that the pop-up meant that "No, I would not need to provide medical evidence”

### To do
Provide clarity and update behavior at this step to reduce confusion and promote user to read and understand what's needed

### AC
- Get sign off from stakeholders
- Validate any PDF schema changes
- Migrate any in-progress forms
- Get sign off from design once in staging
- Update product guide
- Coordinate changes between FE and BE

**Comment by gmaciolek** [comment]
This ticket will spill over into next sprint. The updated designs are [in progress in Figma](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3323%3A30340&mode=design&t=Co8bJZ8DfB0IGQah-1).

Here are outstanding design items to be addressed:

- Whether or not we want to implement a new interaction pattern for requesting documentation/medical evidence for this question that differs from all of the other places we ask for supporting documentation or if we should update all similar instances to use the same solution. See [Slack thread](https://dsva.slack.com/archives/C06E83RNLQM/p1712612416252899).
- Confirming that we need to add a triggering condition for this medical evidence request so that it shows as a bullet point on the review supporting documents page. (I don't think it does currently.)
- Get official confirmation from stakeholders re: removing the "Are you 65 or older?" question and using the applicant's birth date instead. Also, do we want to pad that time at all in case they are almost 65 when they're filing?
- Finalizing copy
- sharing updated design with VBA stakeholders

**Comment by aplatt-coforma** [comment]
@echin393 - can you please pick up this ticket where Gretchen left off? Please reach out to me if you need any assistance.

**Comment by aplatt-coforma** [comment]
@maddiefritz - I'm able to assign this ticket to you now. Please add comments as you make progress on this ticket. Especially if you're not able to attend daily scrum. Thanks!

**Comment by maddiefritz** [comment]
Some more copy insight from @jstrothman and @Dene-human. Will continue making some updates this morning.

**Comment by maddiefritz** [comment]
Working Figma file [here](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3023%3A3346&mode=design&t=NXCbDLuRtrbkES3d-1).

**Comment by maddiefritz** [comment]
Above needs in the previous comment have been met. Made a final update to this design and it's now ready for a collab cycle review.

**Comment by maddiefritz** [comment]
Link to Figma file for CAIA review [here](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=4084-14827&mode=design).

**Comment by mtri** [comment]
[Designs with CAIA content are ready.](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82099&t=b6yAPRgWdqCmIk9u-11)

**Notes**
-   In replacing alerts that users were missing and misunderstood in relationship to the supporting forms needed, we have introduced a pattern where we have a entire reminder page that lets the Veteran know they will need to submit additional forms. Whenever these pages are triggered, the corresponding supplemental form ask will be added to the [Supporting documents content](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4147%3A10537&node-id=5134-33078&t=rossf2XI7rn1fxgl-0&scaling=min-zoom&content-scaling=fixed).

-   [Financial information example](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4147%3A10537&node-id=5203-27931&viewport=-1317%2C-865%2C0.5&t=vy6XbYH69HkQJou9-1&scaling=min-zoom&content-scaling=fixed)
-   [Health and employment information example](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4084%3A14827&node-id=5134-19640&viewport=-1250%2C59%2C0.25&t=or4PKuKCd5UuAfsg-1&scaling=min-zoom&content-scaling=fixed)
-   There may be additional opportunities to lean into this pattern in other sections of the form (TBD)

**Comment by mtri** [comment]
Midpoint feedback to be implemented (applies to whole batch of usability improvements):

[Midpoint Review - Accessibility Feedback - Pension-Benefits, Pension, Usability Improvements #86503](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86503)
[Midpoint Review - IA Feedback - Pension-Benefits, Pension, Usability Improvements #86499](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86499)
[Midpoint Review - Design Feedback - Pension-Benefits, Pension, Usability Improvements #86451](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86451)

**Comment by mtri** [comment]
[Figma for Engineering](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82099&t=V5dUy3B0nNzkKbAT-11)

**Comment by aplatt-coforma** [comment]
Create engineering ticket #88388
