### ISSUE TITLE
Implement eligibility request routing to VPG

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#79218]
To support appointment scheduling capabilities at Oracle Health sites, we must route requests for patient eligibility to the VetsAPI Gateway (VPG).

**Acceptance Criteria**
* Requests that are currently made to `/vaos/v1/patients/#{user.icn}/eligibility` are routed to `/vpg/v1/patients/{icn}/eligibility` if the `va_online_scheduling_enable_OH_eligibility` feature flag is enabled
* Tests are updated as needed

**Comment by anita-halici** [comment]
carried over due to pending review on the appts team side
