### ISSUE TITLE
Vets-api terminal access for Eli Selkin (eselkin)

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-team#79216]
### Your Name

Eli Selkin

### Your GitHub handle (terminal access is managed through GitHub)

@eselkin

### Team, Role, and Company of the target individual

Sitewide Facilities, Software Engineer III, agile Six Applications, Inc

### Product Manager (PM) name and email

Jill Adams (Delivery Manager - Jane is leaving) - jill.adams@agile6.com or jill.adams1@va.gov

### Product Owner (PO) name and email

Michelle Middaugh  suzanne.middaugh@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [ ] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

<img width="1235" alt="Screenshot 2024-03-25 at 5 46 12 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5606931/747c6478-7b8e-4557-85fc-714c92fe933f">

I think my COR is Keith Riley

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
confirmed in Atlas
confirmed E-QIP

**Comment by bdech** [comment]
@eselkin You’ve been granted access to the `dev` environment.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
