### ISSUE TITLE
Clarify dependents assets questions (H)

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79212]
A few participants (P1,P3,P13) who responded 'NO' to dependents were confused by the follow-up questions regarding assets that referenced ‘your dependents’. A couple of participants, when they saw the question which asked whether they and their dependents had assets over $25,000, incorrectly included their adult children in their calculation of assets. 
P1 answered NO to dependents and then the next question asked 'Do you and your dependents have over $25000 in assets?’ 

P1: "I don't have any dependents, so I'm not sure why it is asking about my dependents. Why do you need to know what my dependents assets are? "   His confusion led him to (unknowingly) incorrectly report his assets.

P3: Did not have any dependents and when he read the following question referencing his dependents was confused about how he would factor his kid's assets into the question (even though he wouldn't need to).

P13: [reads the income and assets question....] “What? I don't have any dependents?"

See slide 21 of [[Usability Study Deck](https://docs.google.com/presentation/d/1c0m-4xy3fpi1K2ROxIt9cbOZbCUTmRVzQoA1RpVs7ZQ/edit#slide=id.g1f4d68376fa_0_141)]

Staging link to form: https://staging.va.gov/pension/apply-for-veteran-pension-form-21p-527ez/introduction

<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0YvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee4eb9acb8ef555d953448cccf6b4435b39ffe40/Screenshot%202024-04-22%20at%209.30.23%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 9.30.23 AM.png" />
### Background
<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ovQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6f27d9cd937bc29dc3168b90283ae1b4130586b/Screenshot%202024-04-22%20at%209.30.38%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 9.30.38 AM.png" />
.google.com/document/d/1nI0g96Or0_sOsjnvyno9bzh_HxIuPt3<img width="660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM04vQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10f72f8c1a60f2f6994a375a23a7b419d1ddc344/Screenshot%202024-04-22%20at%209.30.48%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 9.30.48 AM.png" />
n3Imb1tNIamw/edit#heading=h.kdz1ermzo8pq)**

<img width="856" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGg1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb42cd7317f6c6ab2fee24402917bec72fe04fe3/Dependents%20Screenshot%201.png" alt="Dependents Screenshot 1.png" />

<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjF1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--765844bae0be4307af95080125365fcc89f8a769/Dependents%20Screenshot%202.png" alt="Dependents Screenshot 2.png" />

<img width="660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1IvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed728705f5019b7ad8727e252d8d0aa7ac78bf3a/Screenshot%202024-04-22%20at%209.30.48%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 9.30.48 AM.png" />

### To do
- Review comment section for clarification on the meaning of dependent
- Define clearer content and interactions to avoid confusion and support users to do what's needed

### AC

* Stakeholders have signed off 
* Design has signed off in staging
* PDF schema changes are accounted for
* No issues with in-progress forms as they have been migrated
* Product guide has been updated

**Comment by Allexelaw** [comment]
Dependents for the question ""Do you and your dependents have over $25,000 in Assets" is not only referring to dependent children but to other dependents.  See the VA definition found [here](https://www.va.gov/view-change-dependents/#am-i-eligible-for-additional-v) .  See response from Julie S. at https://dsva.slack.com/archives/C06E83RNLQM/p1713523610096309 .   Therefore, the content for the question should clarify that it is referring to dependent spouses and parents and ideally include a drop down or link to the definition of dependents.  If a Veteran indicates that they do not have a dependent child, reference to a dependent child should be dropped in the following questions and only reference other dependents.

**Comment by maddiefritz** [comment]
Notes from ticket 'kickoff' -

- clarification of what's meant by 'dependents' may be needed on all relevant questions
- maybe a drop-down explaining what dependents are?

**Comment by maddiefritz** [comment]
Working Figma file [here](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3857%3A13595&mode=design&t=NXCbDLuRtrbkES3d-1).

**Comment by maddiefritz** [comment]
I think a q to confirm with VA folks is if the meaning of 'dependents' changes as the form progresses. W/i the paper form, there's a section (no 8) specific to Dependent Children; the following section (no 9) refers to dependents again, but doesn't specify which kind (per @Allexelaw 's previous comment, the VA considers multiple relation types subject to being considered 'dependents').

**Comment by maddiefritz** [comment]
Made some updates to the Figma file and tagged Dene and Julie in a comment for an initial review.

**Comment by maddiefritz** [comment]
More updates and tagged Dene and Julie for a secondary review round.

**Comment by maddiefritz** [comment]
More updates and changes made to the Figma file; tagged Dené and Julie for review.

**Comment by maddiefritz** [comment]
Made some changes to the copy on the submission pages of the form. Two options for Dené G and Julie S to review. Comment [here](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc?type=design&node-id=4053-13831&mode=design#801838393).

**Comment by mtri** [comment]
[Designs with CAIA content are ready.](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82095&t=b6yAPRgWdqCmIk9u-11)

-   [Supporting documents content](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4147%3A10537&node-id=5134-33078&t=rossf2XI7rn1fxgl-0&scaling=min-zoom&content-scaling=fixed) has been built out to support all documents and types of evidence that may be asked for. We identified two other examples not covered in the initial copy passed to CAIA so all should be covered now.
-   [Submit your forms](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4147%3A10537&node-id=5134-35974&viewport=-1317%2C-865%2C0.5&t=vy6XbYH69HkQJou9-1&scaling=min-zoom&content-scaling=fixed) now only shows one option and notes that the Veteran can submit the other two ways at the end of the experience. This eliminates redundancy and follows the typical confirmation page pattern.

**Comment by mtri** [comment]
Midpoint feedback to be implemented (applies to whole batch of usability improvements):

[Midpoint Review - Accessibility Feedback - Pension-Benefits, Pension, Usability Improvements #86503](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86503)
[Midpoint Review - IA Feedback - Pension-Benefits, Pension, Usability Improvements #86499](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86499)
[Midpoint Review - Design Feedback - Pension-Benefits, Pension, Usability Improvements #86451](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86451)

**Comment by mtri** [comment]
[Figma for Engineering](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82096&t=V5dUy3B0nNzkKbAT-11)

**Comment by aplatt-coforma** [comment]
Created eng ticket #88400
