### ISSUE TITLE
Integrate Postman into Control Plane CI (QA Effort)

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#79237]
# Description
Given that it's possible to execute a public Postman collection from GitHub Actions, we should integrate the execution of our Postman collection into a relevant GHA workflow in the `prt-control-plane` [repository](https://github.com/department-of-veterans-affairs/prt-preview-control).

# Acceptance Criteria
- [ ] A GHA workflow in the `prt-preview-control` repository is able to execute the Postman [collection](https://www.postman.com/vagov-prt/workspace/team-workspace/collection/15306072-de7fd1e5-ced7-4a8d-b70a-7da58c30ae9f?action=share&creator=15306072).

**Comment by IGallupSoCo** [comment]
Today's effort was spent standing up a basic job to add to the _build-and-publish.yaml_ GHA workflow, discovery on choices of test runner packages for the test suite, and clarification with Patrick on options for test suite storage.

**Comment by IGallupSoCo** [comment]
I've exported and added a suite of dummy Postman tests to the prt-preview-control repo, on this branch:
https://github.com/department-of-veterans-affairs/prt-preview-control/tree/integrate-postman-testing-to-publish-workflow

**Comment by IGallupSoCo** [comment]
This is how I've currently got newman configured to return in the terminal.  Any test failures will exit the CI job with code 1, which will fail the run.

<img width="619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3459701bc4c3e55633f9903b6bef9bd96fc854d2/Screenshot%202024-04-30%20at%209.30.24%E2%80%AFAM.png" alt="Screenshot 2024-04-30 at 9.30.24 AM.png" />

**Comment by IGallupSoCo** [comment]
<img width="757" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--081c4ca9d4b5baef7453cc7205f65b0f500f9154/Screenshot%202024-04-30%20at%203.00.27%E2%80%AFPM.png" alt="Screenshot 2024-04-30 at 3.00.27 PM.png" />

**Comment by IGallupSoCo** [comment]
I do believe I have a successful integration.

**Comment by IGallupSoCo** [comment]
So the code for integrating Postman is done, but I am running into continuing problems spinning up the needed containers for running the tests.  After meeting with Patrick and Steven, it appears that more work will be needed to stand up a functioning test iteration of the control plane.  Once that is resolved, refining the Postman tests into a useful state will be comparatively simple. <img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0NyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddcb4b006916f3cb26ff70900b44c364e433998e/Screenshot%202024-05-01%20at%203.53.00%E2%80%AFPM.png" alt="Screenshot 2024-05-01 at 3.53.00 PM.png" />

**Comment by IGallupSoCo** [comment]
[The latest CI logs](https://github.com/department-of-veterans-affairs/prt-preview-control/actions/runs/8914757933/job/24482996317l)

**Comment by IGallupSoCo** [comment]
By the end of this sprint, the integration of Postman itself has been achieved, but some additional work will be needed in order to enable the creation of a testable control plane instance within the GHA workflow.  Postman offers no means of spoofing success when certain key points of the setup are not available for test calls, and it would be a waste of time to stand up a completely different dummy environment that would not align with our overall testing goals.

**Comment by JoeTice** [comment]
Closing this ticket, as work is done, there are some setup tasks that need to happen to complete implementation, will define these in the morning
