### ISSUE TITLE
Build placeholder vets-website footer

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#79244]
#### User Story or Problem Statement
- The vets-website ARP app is currently using the `page-react.html` template like all other applications in the registry.json. 
- However, unlike all other applications we do not want all the content provided by the `page-react.html` or its children components: 
  - `src/site/includes/header.html`
  - `src/site/includes/footer.html`
- It was initially determined we do not want any of the code from `footer.html` and we decided to build all of the footer in vets-website instead of in content build. However, the first step of this issue would be to ensure that the bottom part of the va.gov footer is not legally required as part of VA websites: <img width="1870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFlRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab96b2e072c7eb6c5fc065422545cc78cd080753/Screenshot%202024-03-26%20at%2010.24.24%E2%80%AFAM.png" alt="Screenshot 2024-03-26 at 10.24.24 AM.png" />. Design has an action item around determining this so check in with this.

- This issue creates this vet-website footer

#### Implementation Details
- Add footer.js at `components/common/footer.js`
- Add content to content-build ARP footer if determined as desirable

### Acceptance Criteria
- [ ] The ARF app now has a footer that lives in vets-website that follows the current mockups
- [ ] Add content to content-build ARP footer if determined as desirable

#### Automated Testing
- Add a unit testing file at `tests/components/common/footer.unit.spec.js`

#### Accessibility (A11y) Testing 
- Ensure it does not raise any new A11y errors in the console

**Comment by kristen101606** [comment]
I've asked our VA stakeholders in [this Slack thread](https://dsva.slack.com/archives/C05SUUM4GAW/p1711999484002749) if they can help us determine how much/what parts of the footer content is required. 

For now, [this most updated design of the footer](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=588%3A35938&mode=design&t=gl4rb0WaYXFgAKt3-1). Assuming we don't have any major changes over the next few days, this will be the footer we use in usability testing in the coming weeks.
