### ISSUE TITLE
UX: Help Desk support number(s) on MHV landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#79258]
### User story

As an MHV-only Veteran (not Oracle) trying out the new portal, I want to be able to confidently find the correct support phone number both for MHV-related and non-health-related issues, so that I can quickly solve any problems.

### Notes
- Extensive discovery notes in #69656 

Possible tasks:
- review (and organize as needed) contact center discovery materials
- document value hypotheses and success criteria in a product outline
- create UX design
- identify experimental KPIs using existing or new discovery of contact center operations
- consult with Patrick and Kaitlin about validation strategy, stakeholder considerations

## Acceptance criteria

- UX design and product hypotheses documented
- documented recommendation for experimental/data-driven approach to validation, including data sources and experimental protocol [see here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/help-support/phased-plan.md)
- A11y review completed

**Comment by fmccaf1** [comment]
### Questions:
- What are people calling the helpdesk about?
- Where are people going to seek help (on the site)?
- Are there different numbers for the main four tools? How about med supplies? Payments?

### Timeline:
#### This week (Thurs + Fri)
- Discovery work (reading what is already there) and **collecting questions** (in our Mural) 1 day, by lunchtime @jonathanjnelson @sterkenburgsara @fmccaf1 
- Competitive analysis (in our Mural) 1/2 day @jonathanjnelson 
- Explore what else is on VA.gov; dig up old research from similar health tools @sterkenburgsara 
- Map out links on LP and see which are covered by which call centers/numbers (1/2 day) @fmccaf1 

#### Monday
- Meet to discuss findings from above activities^
- Review questions we've gathered and identify most important/actionable
- Plan out follow-up tasks, i.e. reaching out to SMEs

#### Tuesday-Friday
- Sketch/converse about ideas; prioritize and/or decide what is best (1/2 day)
- Possible KPI exploration (1/2 day) 
- First low-fi Figma mock-ups (1 day)
- Decide

#### Monday & Tuesday
- Refine Figma designs based on decisions made last week
- Internal team feedback

**Comment by sterkenburgsara** [comment]
[Link to Slack thread](https://dsva.slack.com/archives/C06QUGXJD8R/p1711726035407129)with @beckyphung  & @tygindraux (Ask VA) about overlap b/w what their tool covers and what we anticipate users having questions about for My HealtheVet on VA.gov. Sounds like we would need to work out clear definitions of what topics would need to be routed to the MHV Help Desk, but they already address many of the high-level topics that we would anticipate needing to cover in the AskVA tool.

**Comment by fmccaf1** [comment]
I wrote to Brenda Torres-Hill today in teams to get the ball rolling with uncovering any current plans for the HRC help desk during and after the transition. She pointed me to Theresa Hancock. I sent Theresa an email but she is out of hte office today.

**Comment by wesrowe** [comment]
In Sara's slack thread asking about the Seamless CX strategy, [Danielle](https://dsva.slack.com/archives/C0581MN69TJ/p1712069285059649?thread_ts=1712064462.952119&cid=C0581MN69TJ) weighed in on the structure of the Contact Us page.

**Comment by wesrowe** [comment]
I just came across a couple notes that might not be documented in the discovery materials:
- Becky Phung reached out to Wes on 2/5, she's PO on Ask VA – this is a contact form product similar to the one on MHV. (both are [documented in mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704739824626/19b2ef8a0b5a072f695d0f9b7b55ea95a3be3b97?wid=0-1707181862393)).
- UPDATE 2/12: per Sylvia Palmer, the MHV contact form is likely to be sunsetted during the transition. It has become a side door around the proper channels (this got particularly pronounced during the pandemic), and the transition offers a chance to shift Veterans toward the self-service model that VAgov is organized around.

**Comment by sterkenburgsara** [comment]
Couple of relevant threads:
* [AskVA conversation](https://dsva.slack.com/archives/C06QUGXJD8R/p1711726035407129) w/ Becky Phung re: health-related topics this tool covers
* [AskVA conversation](https://dsva.slack.com/archives/C06QUGXJD8R/p1712151000572829) w/ Becky Phung & Chante Lantos-Swett about routing paths to HRC and/or My HealtheVet helpdesk

**Comment by sterkenburgsara** [comment]
@wesrowe per that first thread I just linked above, AskVA does not currently cover all topics that My HealtheVet form covers, so there will be gaps in what VA.gov tools can cover re: health topics. It sounds like there are no routing pathways to the My HealtheVet helpdesk now from VA.gov tools, but there are some to the HRC helpdesk (which is the main "umbrella" helpdesk for healthcare, that's over the MyHealtheVet helpdesk - per Chante).

**Comment by wesrowe** [comment]
@sterkenburgsara, you seem to be talking about the My HealtheVet helpdesk and the HRC helpdesk as two different call centers. I believe that they are the same thing: HRC covers the MHV help number plus a couple other phone numbers. Lmk if I'm misinterpreting what you wrote...

**Comment by sterkenburgsara** [comment]
@wesrowe Yes, I am describing them as different. HRC is the "umbrella" call center for health (per Chante) and includes: 
* My HealtheVet
* Homeless Veterans
* First-party billing

What we're not sure about yet, is if HRC will answer questions or if they will just route callers to one of the narrower help desks. If that's the case, we hypothesize that it would be better to directly send users to the My HealtheVet help desk. Trying to get those answers soon.

**Comment by fmccaf1** [comment]
Outstanding tasks:
- [ ] create design of LP with the need help? DS component
- [ ] write up plan (from MVP -> final approach) @sterkenburgsara 
- [ ] get clearer on right phone number(s)
- [ ] solidify kpi strategy for MVP @fmccaf1 
- [ ] find knowledge-base article that Chante referred to?

**Comment by wesrowe** [comment]
To @sterkenburgsara's:
>What we're not sure about yet, is if HRC will answer questions or if they will just route callers to one of the narrower help desks.

I feel very confident that HRC is the actual MHV help desk. I got this from talking to Sylvia Palmer. Also, it's pretty strongly implied by this dashboard, a view within the MHV Analytics Dash (in PowerBI) that some of us have access to:
<img width="639" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/7c0a68a4-db71-462c-98ae-36ad574ec383">

**Comment by fmccaf1** [comment]
### Chat with Sylvia Palmer on Teams about MHV help desk:

Question: Does the MHV help desk track the source of calls (for example, those forwarded from other help desks?

> Sylvia: No they do not track the source of those calls except for categories of VA Employee, Veteran, Caregiver, Provider, etc. They can upon request run a reverse phone number look up report so if you had the My VA 411 phone number that would display on the incoming IVR you could ask them to pull a high level number of how many times that number has called the help desk but no granular detail such as topic or sub topic.

**Comment by sterkenburgsara** [comment]
Rough draft documentation in [github here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/help-support/phased-plan.md) - would love team edits/eyeballs!
