### ISSUE TITLE
HSRM Integration for VAOS Scheduling

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7926]
# Stakeholder input:
## High Level User Story / Problem / Opportunity
Want to interface with system used by CC clerks containing CC provider info, referrals, etc. UI may need to add/update current CC workflow. 

**Need more information on what problem we want to solve here. What's the end goal/strategy?**

## Goals / Outcomes
**Need to fill out**

## Stakeholder AC Score:
_(Calculations made [here](https://docs.google.com/spreadsheets/d/1fuGBtMRYTze0Z8_fvw4EmqiSVOwjC1ZIv8E5JECL2o0/edit#gid=836967960))_

---
# Next iteration of Epic after initial Stakeholder input:
## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

## Issues to create within this Epic

```
- If discovery needed, create Discovery/Research Epic
```

## How to configure this issue
- [x] **Labeled with `roadmapOCC` and `VAMF` and `vaos`**
- [x] **Add Epic to VAOS-R Roadmap Project in Github - must do this in GH, not Zenhub**

**Comment by laurenernest** [comment]
HSRM work will be covered in #14091
