### ISSUE TITLE
Restore AWS access for Daniel Cloud

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#79295]
### COR Name

Laurene "Reney" Cook

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Daniel Cloud

### Your Email

daniel.cloud@adhocteam.us

### Team, Role, and Company of the target individual

MHV Cartography, Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Lynne Johnson, lynne.johnson@agile6.com

### Product Owner (PO) name and email

Patrick Bateman, patrick.bateman@va.gov

### Desired AWS Access

I need SSM Access to lower environment instances. The specific IAM policy needed is "SSMApplicationLowerEnvironmentAccess", which can be granted via membership in the "dsva-vfs-developers" group.

I previously had access: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52511

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

Per https://github.com/department-of-veterans-affairs/va.gov-team/issues/52511#issuecomment-1422890373: 

> We received confirmation of you having a “previous investigation that meets or exceeds the current request” on 04/21/2022.

### Additional Notes

I need this access because I am working on the MHV to Va.gov project and need to be able to [tunnel to MHV APIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-api-tunnel-setup.md).

I [previously had this access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52511) before leaving then returning to this team.

I think Mark Junda became our COR after Reney Cook. Unsure if that is still the case

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
User is in Atlas

**Comment by ph-One** [comment]
Sent new credentials, waiting for response from user.

**Comment by dcloud** [comment]
I have received new credentials and logged in. Thanks!
