### ISSUE TITLE
[UX] Add documentation in Git for how/where to pull quarterly metrics

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79314]
## Tasks

- [x] Add documentation in Git for how/where to pull quarterly metrics

## AC

- [x] Share link with Lori for review

**Comment by benbrasso-agile6** [comment]
Sounds good

**Comment by loripusey** [comment]
@benbrasso-agile6 I am done, please verify not only the documentation but where I am grabbing each metric; the only one that I was not sure about was **10-Travel via Check-in error rate**

[How to Generate an Analytics Report for VA Stakeholders](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/analytics/how-to-generate-analytics-report-for-stakeholders.md#where-to-get-each-metric)

**Comment by benbrasso-agile6** [comment]
thanks, will take a look

**Comment by benbrasso-agile6** [comment]
Pulling this into in progress or I'll forget

**Comment by benbrasso-agile6** [comment]
10, 28 and 29 updated

checking the rest now
