### ISSUE TITLE
SOCKS access for Shaun Burdick

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#79335]
### Your Name

Shaun Burdick

### Your Email

shaun.burdick@coforma.io

### Your GitHub Handle

shaunburdick

### Your Role and Team

Technical Lead on VA Benefits team 1/2

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Zach Goldfine, zachary.goldfine@va.gov, Sade Ragsdale, sade@coforma.io

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJOKBxHHW+HObVgPAuULZd6jTj16zFl7+NmwNIXxc4Sh socks+shaun.burdick@coforma.io

### E-QIP Transmittal Confirmation

![2024-03-26_18 07 17_IiSScwdQ@2x](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5100175/5ab0c3e1-4034-4fe8-a3f9-53f9e9659855)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
Socks access provisioned
