### ISSUE TITLE
Implement MHV Help Desk phone number solution (MVP)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#79333]
### User story

As a Veteran signed in with a credential with access to health tools, I want to be able to confidently find the MHV Help Desk phone number in the new MHV-on-VAgov portal, so that I feel supported by VA phone options.

### Notes
- Implements design from #79258
  - [Figma file here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2165-24841&t=6ulRtFsFajxh0Ge9-0) 
- Design system component: [need-help](https://design.va.gov/components/form/need-help)
- Use cases discussion: [slack](https://dsva.slack.com/archives/C0581MN69TJ/p1715706670897059?thread_ts=1715706310.078869&cid=C0581MN69TJ)
  - Hide for users who can't use tools:
    - users who aren't registered need to call their facility (per that alert)
    - users who aren't verified need to take action to verify their credential
  - Don't hide from Oracle users - many of them also have VistA facilities

**Implementation details:** 
- Implement just for the MHV landing page for this ticket. Wes will reach out to tool POs to discover whether a shared component would be a good fit. (Note: we already [heard](https://dsva.slack.com/archives/C0581MN69TJ/p1715712757846609?thread_ts=1715706310.078869&cid=C0581MN69TJ) from Kristin that Appts has a NH? component with additional info specific to Appts.

Possible tasks:
- 

## Acceptance criteria

- New component displays support phone number(s) on the MHV landing page in Staging, behind the appropriate toggle for the integration, for users with facilities and a verified credential – i.e., users who have access to the tool links on the landing page
- QA review
- A11y review

**Comment by jonathanjnelson** [comment]
[Design mocks in Figma](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2228%3A26288&t=eXFy08AcOGnIezw5-1)
