### ISSUE TITLE
Backend Training Session w/Kevin Suarez on 4/2/24

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#79356]
## Issue Description
Front End engineers would like to learn more about Back End tasks (especially with Kevin's pending departure on June 28, 2024).

This ticket will be used to account for the effort of the "Training with Kevin" session.

Training Session is set for April 2, 2024 at 10amPT/1pm ET and is open to the entire team.

We will plan to record for future Engineers who will be joining the team.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
[Document used for presentation](https://docs.google.com/document/d/17Ts3DcQ15fSyVmNpGNh5STW4IpUI1WFHDrHuZ94ygZI/edit?usp=sharing)
