### ISSUE TITLE
Readiness review documentation

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#79351]
The last collaboration cycle touchpoint is a Privacy/Security readiness review. 
To complete this touchpoint we must complete a Readiness Review ticket that consists of answering a series of technical and product questions and providing the requested documentation artifacts where applicable.
Steps:
1. Create readiness ticket https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1573
2.  Respond to product questions
3.  Respond to technical questions
4.  Create applicable technical artifacts (e.g. architecture diagram)

Acceptance criteria:
1. Ticket completed
2. Applicable artifacts completed
3. Ticket submitted to  platform security team

**Comment by wayne-weibel** [comment]
[Pension - Architecture Diagram.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9ZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4a081765b68bd9a8ab0c93d562842bc602b505c/Pension%20-%20Architecture%20Diagram.pdf)
[Pension - Data Flow Diagram.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52b75361f2b14bcf2a5c9872612e3c8670233386/Pension%20-%20Data%20Flow%20Diagram.pdf)
[Pension - Sequence Diagram.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8886d728d03a809baa142f5c5fd51597761fbc5e/Pension%20-%20Sequence%20Diagram.pdf)

**Comment by wayne-weibel** [comment]
swagger pension api (old) https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/benefits_forms/addPensionClaim

BenefitsIntake API (start of downstream process) https://developer.va.gov/explore/api/benefits-intake

**Comment by wayne-weibel** [comment]
Incident Response:  contact - Matt Knight, Wayne Weibel; backup - Thomas Blackwell, Steve Albers
- correct code or update package
- commit to new branch
- get exception for merge
- request Out-of-Band Deployment https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Requestingout-of-banddeploys

response time @ 10 min (depending on code change and approvals)

**Comment by matt4su** [comment]
Readiness ticket submitted to Kyle Crockett of the Platform Security team 03/27 and he acknowledged its receipt.  Expect a few days turnaround on the review and any comments.

**Comment by matt4su** [comment]
Our collab cycle Privacy/Security Readiness ticket was just closed as completed by Kyle Crockett on the Platform Security team with "we recommend approval to proceed"
