### ISSUE TITLE
Add a Link to the In-App Survey to Travel, Pre-Check-in, and eCheck-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#79362]
## Description
As OCTO, Kay is asking for us to add back into our applications a link to the in-app Veteran survey so that we can begin to calculate a customer satisfaction score for the applications.

NOTE: I believe, at one time, we had a link to the survey in the Pre-Check-in & Check-in applications but removed it.

## Tasks
- Check-in: Add a link to the in-app survey in the completion page
- Pre-Check-in: Add a link to the in-app survey in the completion page
- Travel: Add a link to the in-app survey in the completion page

**Comment by loripusey** [comment]
@benbrasso-agile6 added this ticket, do you remember how we got the survey results before? (or did we)

**Comment by benbrasso-agile6** [comment]
No idea. Need to find out what team manages Medallia (could probably do a quick search in Slack). 

I might recommend some initial tasks: 

- Touchbase with team that manages Medallia and discuss the need, e.g., does Medallia take that quant question and make it a numeric value? 
- Is there a preference for how we control what pages it appears on? Can we do that in code or is that done in the Medallia javascript, for example? 
- How do we access the data?
- Identify pages that we want to place it on. (For example, we might also want it on error pages.)

**Comment by benbrasso-agile6** [comment]
Started slack here - https://dsva.slack.com/archives/CNCEXNXK4/p1711545874924439
