### ISSUE TITLE
Appointment Details Redesign - Content / CTA updates (confirmation appointment details) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#79364]
## Description
As part of the Appointment Details Redesign initiative, our team will work on updating the content on the Appointment Details page. This update would help provide clarity on how the Veteran will attend or join their appointment. 

We will make updates to the existing confirmation details page only. There is a separate ticket to handle the other appointment details pages [#79086](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79086)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

- [x] #80686
       When the user clicks on `Submit` to schedule a VA booked appointment 
       Then the user will see the updated confirmation details page 
       And page design matches the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A195846&mode=design&t=7xAm3Ts5T67F30L1-1)

- [ ] Given the user is on the Start scheduling workflow 
       When the user clicks on `Submit` to schedule a VA booked appointment then cancels the appointment 
       Then the user will see the updated confirmation cancelation details page 
       And page design matches the design spec

- [x] #81271
       When the user clicks on `Submit` to  request an appointment at the VA 
       Then the user will see the updated confirmation request details page 
       And page design matches the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A213525&mode=design&t=7xAm3Ts5T67F30L1-1)

- [ ] Given the user is on the Start scheduling workflow 
       When the user clicks on `Submit` to  request an appointment at the VA then cancels the request 
       Then the user will see the updated confirmation cancelation request details page 
       And page design matches the design spec

- [x] #80690
       When the user clicks on `Submit` to  request an appointment for a Community Care provider 
       Then the user will see the updated confirmation request details page 
       And page design matches the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A215656&mode=design&t=7xAm3Ts5T67F30L1-1)

- [ ] Given the user is on the Start scheduling workflow 
       When the user clicks on `Submit` to  request an appointment for a Community Care provider then cancels the request 
       Then the user will see the updated confirmation request details page 
       And page design matches the design spec

- [x] #81272
       When the user clicks on `Submit` to schedule an COVID-19 appointment 
       Then the user will see the updated confirmation request details page 
       And page design matches the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A195846&mode=design&t=7xAm3Ts5T67F30L1-1)

- [ ] Given the user is on the Start scheduling workflow for COVID-19 
       When the user clicks on `Submit` to schedule an COVID-19 appointment and cancels the appointment 
       Then the user will see the updated confirmation cancelation details page 
       And page design matches the design spec

### Design Assets
[Figma file](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A195846&mode=design&t=4cOfWaP3L9AYgK3W-1)

### Reference
[Matrix](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2021%3A230246&mode=design&t=7xAm3Ts5T67F30L1-1) to test the appointment modality 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Copy doc updated 
- [ ] Figma file updated 

---

**Comment by Cieramaddox** [comment]
@ldelacosta Is this ticket only concerning the banner across the top of the confirmed appt details pages?

**Comment by ldelacosta** [comment]
@Cieramaddox - this ticket is to validate canceling the appointment/request from the confirmation details page (after user books an appointment or after user submits an appointment request). I believe we have covered it. Let me know if we haven't.

**Comment by Cieramaddox** [comment]
Yep. Good to close out.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
