### ISSUE TITLE
Adding Jessica Downs-Bowen to DSVA Slack

### ISSUE THREAD

**Issue by MichelleDieudonne** [department-of-veterans-affairs/va.gov-team#79371]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Jessica is a new Requirements Analysist on the Self-Service team and will need DSVA Slack access in order to complete her job duties. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add jessica.downs-bowen@va.gov as a full member.

**Comment by LEHigley** [comment]
showing as a full member
