### ISSUE TITLE
vets-api swagger docs (status endpoint)

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#79382]
## Description
We have an endpoint for getting claims' statuses so we should also have a section in the vets-api swagger docs file to describe this endpoint.

## Acceptance Criteria
- [ ] I can visit the [hosted vets-api swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/) and see a section for Travel Pay
- [ ] Under the Travel Pay section, I can see an entry for the status endpoint

## Demo
- Demoable? Sure
- How? Show the swagger entry
- Impact? Shows product maturity 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ayush-chak** [comment]
This is fairly dependent on swagger documentation from the Migrations team

**Comment by athifw** [comment]
There's two options here - we could:
- have the swagger docs be under the `travel_pay` module, so they wouldn't be together with the rest of the VA api docs. To access the docs, one would visit the hosted [swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/) and then type in `https://dev-api.va.gov/travel_pay` in the search bar
- version the `travel_pay` API and group the swagger docs with the rest of the `v0` API. There's already a ticket for versioning: https://github.com/department-of-veterans-affairs/va.gov-team/issues/78812

Putting this ticket on hold while we wait for the claims endpoint to be finished.

**Comment by kjduensing** [comment]
> There's two options

What's your preference @athifw, and why?

**Comment by athifw** [comment]
My preference is the first option, to have the apidocs under their own `travel_pay` module. I think it makes the docs more manageable, especially when we have multiple endpoints under `travel_pay`.
