### ISSUE TITLE
[QA] 10-10EZR Questions: Identify Test Users and gaps in test users

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#79399]
As a Veteran, I want the EZR form with TERA Questions to be tested by user type so that I know it will work when I go to update my VA information.

- [x] Get list of test users that were used to test EZ Tera
- [x] Go through the list to identify user types for testing
- [x] Double-check with Joshua Faulkner about different user types we can expect
- [x] Identify user types that should not be able to fill out the form
- [x] **Success: Identify the test users we will use for TERA Questions, and any holes that the test users do not cover**

**Comment by allanto-ah** [comment]
User types have been identified to be used for testing.
