### ISSUE TITLE
Adding VSA Members to DSVA Slack

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#794]
Please add the following VSA team members:
lmajewski@governmentcio.com - Program Manager
shawna@adhocteam.us - Design Lead
mickin@adhocteam.us - Product Lead

as a full members to the DSVA Slack.

**Comment by CamelliaParham** [comment]
lmajewski@governmentcio.com and shawna@adhocteam.us are already members in our workplace. I've added mickin@adhocteam.us as a full member.
