### ISSUE TITLE
FE | EDU CH33 Migration | Update our downtime toggle for future use

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#79412]
## Background 

We have a feature toggle in place to allow us to turn off the C&P form for direct deposit. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/dd0e1b60-1663-41cf-ada2-c232c51f0899)

We should either remove or modify this toggle [`profile_hide_direct_deposit_comp_and_pen`](https://staging-api.va.gov/flipper/features/profile_hide_direct_deposit_comp_and_pen) so that it will function with the new unified form 

## Tasks 

- Update toggle to not mention CNP
- Update logic that uses the toggle
- Update tests around toggle
- Remove legacy toggle name from staging and production

## Acceptance Criteria 
- [ ] the toggle has been renamed and still turns off the unified form and replaces it with an alert

**Comment by adamwhitlock1** [comment]
the toggle is now called `profile_hide_direct_deposit` and Tom will be removing the `...comp_and_pen` version from staging and prod systems soon so it doesn't show up in the toggle dashboard UI.

Once it is confirmed as removed we can close this.

**Comment by tpharrison** [comment]
feature toggle `profile_hide_direct_deposit_comp_and_pen` removed
