### ISSUE TITLE
Update the ERD of the IPP Data Model

### ISSUE THREAD

**Issue by rdvyas** [department-of-veterans-affairs/va.gov-team#79422]
Using the ERD below as starting point, we need to update with any new data elements and use this as the blueprint for creating the data layer. 

https://lucid.app/lucidchart/d59e0de9-7c74-4df7-8cf2-2683a22a2e2b/edit?invitationId=inv_5f233044-ccde-4c15-9ec3-3214ff8be07a&page=0_0#

**Comment by SophiaPhilipMO** [comment]
Able to do for current state but need to revisit post-pilot once PII is being collected. Will use DBUI 
Need to confirm counter security measure this satisfies
New ticket needed once we collect PII

**Comment by SophiaPhilipMO** [comment]
@skirkman16 @SophiaPhilipMO identify epic

**Comment by moanu404** [comment]
<img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTFKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05798d747a9ee648a07766be31aee75f86f977f1/Pilot1erd.drawio.png" alt="Pilot1erd.drawio.png" />
