### ISSUE TITLE
Create a CSV export feature in Drupal

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7942]
## Status

**[2024-05-16]** Confirmation from Danielle via [Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1715884285581749?thread_ts=1715884076.888629&cid=C01K37HRUAH) today that this isn't needed: Correct, this isn't needed. We don't update rates via CSV file - that was never implemented or pursued further - so no need for the export part of it.
**[2024-05-16]** I messaged in [Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1715884076888629) Beth and Danielle with Dave C's question

## Create a CSV export feature in Drupal

As a CMS author, I want a way to export the current live rates table info as a CSV file so that the Drupal version is always the source of truth for the baseline rate updates. (For example, if we or SMEs lose the spreadsheet we previously sent to them, there’s an export way to recreate the spreadsheet of each table.)

Reference/related archive ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6905#issuecomment-610052002

Example mockup showing export file function for table csv files: https://camo.githubusercontent.com/c045fc73655453f36dddd73ea0368377fdd5b559/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564373930386431666232383866303030316365623835332f35346131353662342d643438312d346335642d396562382d396437393861376233313636

**ETA: This functionality will not be needed until 2021 when we start using the CSV upload method for ongoing rate updates.** 
  - Caveat: there are rates changing later this year (e.g. October, December 1st)
    - Would be helpful to have a list of those rates + change dates (see our Grooming doc for more context around this additional task)

Creating this ticket so we don't lose sight of this need. Can be in backlog until we're ready or have bandwidth to implement.

FYSA also @johnhashva and @daniellethierryusdsva

**Example rates pages - not a complete list:**

https://www.va.gov/pension/veterans-pension-rates/
https://www.va.gov/pension/survivors-pension-rates/
https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/disability/compensation-rates/veteran-rates/
https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/#va-funding-fee-rate-charts

---

## Tasks
- [ ] Create script - Beth
- [ ] Double check CSV structure - Steph/Anne

## Acceptance Criteria
- [ ] TBD
- [ ] TBD

**Comment by FranECross** [comment]
Added to Feb 20, 2024 Prod Sync.

**Comment by davidconlon** [comment]
@bethpotts @DanielleThierryUSDSVA Is this something we still need? I think you mentioned the other day that it probably was unnecessary.

**Comment by FranECross** [comment]
@bethpotts @DanielleThierryUSDSVA Just pinging about Dave's question above. Thanks!

**Comment by FranECross** [comment]
Question asked in [Slack ](https://dsva.slack.com/archives/C01K37HRUAH/p1715884076888629)as to disposition of this request.
