### ISSUE TITLE
IPP - Hide Data fields if Null (map screen, etc.)

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#79425]
This may pertain to the map only, but there are some data fields that are currently displaying even though there is no data coming in (i.e. currently no data for Mental Health phone number in Little Rock facility data on map screen).

**User Story**
As a Veteran or VA Staff member, I do not want to see empty data fields because this is confusing to me.

**Acceptance Criteria**
GIVEN I have logged into the Veteran Intake Application
OR the proofing agent application
WHEN I am viewing the map screen
OR any other screen with data elements
IF there are empty data fields (field value is null)
THEN I do not see the field

Notes:

- map may be the only screen, currently
- need to review additional screens to make sure there are no other empty data fields

**Comment by mateoclarke** [comment]
link to comment about mental health lines from Phil:
https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/76844#issuecomment-2023163091

**Comment by mateoclarke** [comment]
After reaching out to VADS support about the missing data fields, they explained that the VA Facilities API Sandbox isn't updated regularly and may be missing data that would be found in the production API. This explained why we weren't seeing mental health clinic phone lines for our sites but @SophiaPhilipMO could find them online.

I created this issue to request production access to the VA Facilities API. But for now, this is blocked until we have a version of the app deployed for use in the pilot.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79539

Despite that, I've gone ahead and created a PR to make this code fix in case other facilities are missing data or don't have a mental health clinic down the line.
