### ISSUE TITLE
Spike: Stale submission alerting

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79436]
### Background
The goal here is to surface or track any LH API submissions that are stale and haven't been acted upon.  They seem to either go to VBMS quickly or to just stay in a different status:
- Pending
- Uploaded
- Received
- Processing

https://developer.va.gov/explore/api/benefits-intake/docs?version=current

### To do
- Determine what is the reasonable amount of time for 'pending' submissions ([api-benefits-intake](https://dsva.slack.com/archives/CDRSFMWFL)
- Determine how best to track this.  Can this be done in DataDog alone?  Do we end up with a whole tracking table?

### AC
- Present a solution for how best to track submissions.

**Comment by mjknight50** [comment]
@buddhima-coforma - Can we refine this a bit?  It seems to cover a few things and I'm not sure what is still relevent.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/79436?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by mjknight50** [comment]
Need to schedule an engineering meeting on this.

**Comment by wayne-weibel** [comment]
https://dsva.slack.com/archives/C053U7BUT27/p1718202265553319

With in Datadog you are not able to query a specific submission.  Depending on the necessity for alerting on a 'stale' submission, the most likely candidate would be to have it as part of the daily benefit_intake_status_job.  Per documentation and thread above, 10 days would seem an appropriate time to consider a submission stale

https://vagov.ddog-gov.com/dashboard/4d8-3fn-dbp/benefits-intake-form-submission-tracking

@buddhima-coforma

**Comment by buddhima-coforma** [comment]
So a batch job that runs periodically to check, and if any submissions are in progress for more than 10 days, send an alert? @wayne-weibel
