### ISSUE TITLE
DataDog RUM for understand FE issues

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79452]
It provides information about the behavior of the front end application in Datadog, where we primarily have back end (API) information only today.  SO it can be good for understanding issues/errors/user behavior on the React app.

### To do
1. Work with Steve Albers to understand what's needed for this
2. Establish how issues will be surfaced

**Comment by aplatt-coforma** [comment]
Closing this ticket in favor of #82745 which will implement RUM for pension.
