### ISSUE TITLE
Update p12 cert for compatibility w/ openssl 3

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79477]
## Summary

4 .p12 (one per named environment) are used to decrypted data on an upstream service (VBMS) through the `connect_vbms` gem 

The existing certificates are only compatible with openssl 1. But the existing certs aren't compatible with openssl 3 which Debian requires  

## Tasks (as of 4/16/24)
- [ ] Update existing .p12 certificates using the password used to create them [more info](https://www.docuseal.co/docs/convert-legacy-p12-pfx-files-to-support-openssl-3)

Note: Check `openssl version` before converting 

## Acceptance Criteria 
- [ ] The certificate is compatible with openssl 3

### How to check compatibility 
This can be performed locally by verifying openssl 3 is running for you ruby version 
```
ruby -r openssl -e 'puts OpenSSL::OPENSSL_VERSION'
```
then run
```
OpenSSL::PKCS12.new(File.read(path_to_cert), password_on_cert)
```
If there's no error then it's compatible with openssl 3

**Comment by stevenjcumming** [comment]
The first attempt with the likely password failed. It appears the value in the parameter store needs to be converted to a binary in order to update it to be compatible with openssl 3
