### ISSUE TITLE
IPP Security Countermeasures - eMASS

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#79482]
Product/engineering to start on the eMASS as the first step in completing LHDI countermeasures

Steps:

- [x] talk to Yarden on Friday about completing eMASS
- [x] complete and submit to LHDI

**Comment by rdvyas** [comment]
eMASS for has been completed and submitted as part of the Unified System Registry Intake Form. Please see the submitted form at link below (behind CAG)

https://leaf.va.gov/NATIONAL/103/cybersecurity_request_portal/

**Comment by rdvyas** [comment]
Next steps: VA Teams will assign and review out request, then follow up with any open items or questions. I believe we can close this ticket at this time and open a new ticket for any follow up items.

**Comment by skirkman16** [comment]
Forms have been submitted. We can open another ticket once we get a response
