### ISSUE TITLE
Update remaining Formation color variables to their css-library counterparts

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#79489]
### Description
In [78822](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78822) many Formation sass color variables were updated, but some remain due to issues with the `proxy-rewrite` app. This ticket's goal is to complete the update.

### Tasks
* Merge this draft PR into `vets-website`, which includes all remaining instances of Formation variables in `vets-website` **except** those in:
   * `applications/proxy-rewrite` 
   * `plaftorm/`
   *  references to `$color-focus`
* Update `proxy-rewrite` and `/platform`. The issue here is that the Teamsites header/footer will break because the `proxy-rewrite` bundle does not include the `css-library` variables; therefore `css-library` variables in `proxy-rewrite` or in the `platform/` files included in the `proxy-rewrite` app will be undefined until the `proxy-rewrite` app imports the variables from `css-library`
* decide what to do about `$color-focus`. See comment in [78822](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/78822) for more details.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/79489?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by it-harrison** [comment]
follow up ticket: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/79871
