### ISSUE TITLE
Access for Peter Branam-Lefkove

### ISSUE THREAD

**Issue by jblefkove-va** [department-of-veterans-affairs/va.gov-team#7948]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Peter Branam-Lefkove
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse, Software Engineer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJSx8sBu9YByQlBx4KJ5+gkG0XCWUaEynYjVtfRa5vlaaiGymIJ1RoS6AdpS02GVTLuBmo6IiTqDTmWW9bQfHjF4pb4H00uS3h0Hv1q1/l7Nrw4x0P4N3IrsSLxtSPh5hfV+WGuHvnQ2O82IBetnb/hS12XLnoD9bFfVWR1g9TPpm9D+RL7xVtiB7qfVx7ZveHvb844nZmE5G/TX+PKNsUDsqZg8W91aTsvANtD87sf61HkycwYwkQUG+pEtu8bS5S6Q3Kp29818+GPlpdZzXKy7eAVXpKPaJauLZjLXkPh3VnLUGvpYvQ6pOx8W2HNEddLhxVVNxORjEBeslEeFoH AzureAD+PeterBranam-lefkove@DESKTOP-PBRANAM
```

- [Grant AWS Console access?]
  > NO

**Comment by jblefkove-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by benniemosher** [comment]
merged and deployed
