### ISSUE TITLE
EPIC - Request & Support Post-MVP

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#79499]
The next phase!

- Adding the following Request Types in ID Bot & Github
   - Bug Fixes
   - Feature Requests
   - Task Requests
   - Help Requests
   - USiP Questions
- Documentation on how we fix those request types
- Slackbot message automation
   - When a request is assigned.
   - When a request is closed.
- Identity Team branding updates
- Identity Team documentation updates

[Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Product%20Briefs/Request%20&%20Support%20Post-MVP.md)

**Comment by parkerbees** [comment]
All tickets complete or moved to Jira. Closing.
