### ISSUE TITLE
Mask PHI data in DataDog RUM dashboard 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#79492]
## Description
The frontend team will need to mask the data in DataDog RUM due to PHI information. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_datadog_RUM` toggle is on
- [ ] Session replays are captured in DD with PHI information masked.

## Reference 
[PHI mask data](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75744)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
