### ISSUE TITLE
Monthly CSP Data Pull

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#79508]
Pull monthly CSP use (unique logins, including mobile) and send to Lauren/Sophia on the last day of the month.

Def of Done

- [x] Monthly CSP data pulled from Domo/Datadog, etc
- [x] csv file emailed to lauren@themostudio.com and sophia@themostudio.com
- [x] Lauren/Sophia email to Tom/Samara on the 1st of the month

**Comment by sdickson-gt** [comment]
This is complete.  The March data has anomalies due to IAM SSOe's migration from SAML to OIDC and not reporting authentication transactions.
