### ISSUE TITLE
Improve NoK/EC Analytics (GA)

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#79507]
## Description

EPIC: department-of-veterans-affairs/va.gov-team#62159

### User story

As a Cartography team member, I want to know how many next of kin/emergency contact records are displayed to the user, so that I can determine if `/profile/contacts` page is working appropriately.

~As a Cartography team member, I want to know if users are clicking on the instructions for updating personal health care contacts, so that I have metrics for how many users have viewed this information.~
- update: we get this for free from the design system, there are "expand" and "collapse" events on the additional-info component

### Notes
- Per Jamie Stutt in office hours: the preferred way to do this is to add this info to the audience(?) parameter on the `onLoad` dataLayer. This will get the data into GA without creating a new event.

Possible tasks:
- 

## Acceptance criteria

- GA can report/segment on the number/% of users who have 0, 1, and 2 contacts in either NoK or EC sections

**Comment by radavis** [comment]
Notes:
- Page views for `/profile/contacts` is already a metric we can view in GA.
- The `useDatadogRum` hook is not called within the `vets-website/src/applications/personalization` app space, so utilize `recordEvent` to report user analytics to GA.

**Comment by wesrowe** [comment]
I can't think of any product/design decisions we would make based on the prevalence of 0/1/2 of each contact type. Closing.
