### ISSUE TITLE
Disability: Identify recordEvents for GA4 Migration

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#79521]
Due: Friday, April 5th

The Platform and Analytics Team has requested that all VFS teams identify and inventory all recordEvent actions currently living in their codebase (aka custom events). This will ensure that these events are transitioned properly to GA4.

Tasks
 Inventory the following forms and fill out th[is form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D) detailing what custom events exist.
526ez
4142

Acceptance Criteria
- All recordEvent actions recorded in Github ticket
- Github ticket submitted

**Comment by zack** [comment]
**21-526EZ (Application for Disability Compensation and Related Compensation Benefits)**
https://docs.google.com/spreadsheets/d/1ok7YLNdaDSFs4XG7b4IEUkwhy0EfaUYsbP5xgTRqr18/edit?usp=sharing

**4142 (Authorization to Disclose Information to the Department of Veterans Affairs (VA))**
_No uses of recordEvent_

**Comment by zack** [comment]
@sortizsh done: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79565
