### ISSUE TITLE
Heading issues on 526 

### ISSUE THREAD

**Issue by sudeeptibh** [department-of-veterans-affairs/va.gov-team#79529]
It appears that the pages that use the ArrayField component are not using semantic headings and, instead of using H3, are wrapped in a legend. These heading issues will make it harder for screen reader users to navigate through the page - navigation by heading is the most common way they navigate 

Known pages this impacts 
- Military History page
- Contact Information
- Conditions Page (CC team) 

Open Questions
- What pages does this impact? 
- Can the CC team fix this issue in staging, or does that have implications for the rest of the form? 

Also include:
- Instances of the ["standard" variation of the alert component](https://design.va.gov/components/alert#examples---standard---v3) should have their first line built as headings, including the alerts added with the [single direct deposit account](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78597) issue ([Slack discussion](https://agilesix.slack.com/archives/C04MJV66ZPC/p1711724441991369?thread_ts=1711498912.246149&cid=C04MJV66ZPC))

**Comment by RakshindaAslam** [comment]
cc @juliepedtke @alatempa24 @RakshindaAslam

**Comment by christinec-fftc** [comment]
The military history page (`review-veteran-details/military-service-history`) and add disabilities (`new-disabilities/add`) page are using a 526 custom component [ArrayField](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/components/ArrayField.jsx). Would be interesting to do some digging as to why the platform version of ArrayField could not be used at the time.

**Comment by sudeeptibh** [comment]
CAIA feedback for CC team - "So. We understand the concerns about doing this in isolation. And normally, we prioritize consistency in a form.
However. This nested fieldset pattern isn’t correct, it doesn’t read on VoiceOver (and iOS VoiceOver is a huge AT user group). We don’t want to “consistently” use a pattern that isn’t useful for people.
So, our recommendation is to a) get rid of that outer fieldset, make it an h3 as recommended, and b) put it in the backlog for any other spots you see this pattern in the 526 form so it can be fixed :heart:"

**Comment by mengA6** [comment]
Related to [Design discovery: Headings audit#65621](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/65621)

**Comment by evelynhilbrichdavis** [comment]
Seconding the accessibility concern for screen readers. I see this as the most acute user need. It would also be more time sensitive if it is blocking current users from navigating the form.

**Comment by sudeeptibh** [comment]
The CC team will take ownership of this ticket and consult with DBEX. We will copy and paste this ticket into our board and leave it as is for the record.
