### ISSUE TITLE
Refactoring the form.js file on vets-website

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#79532]
**Form.js refactoring**

Goal: The form.js file should export the form config and definitions and data should be defined externally in organized chapter folders with “page.js” files. The following suggestion would leave us with a very minimal form.js file with definitions living in the external chapter folders with a chapter.js and respective page.js and helper.js functions file.

Import organization
Suggestion: To create index.js modules for each chapter and maintain a single import file for each chapter at the top.
Helper function organization
Suggestion: Move helper functions to each chapters respective helper.js file. If there is a global form helper function, create a helper.js file in the form.js folder to hold these definitions
Form config organization
Suggestion: Continue organization of pages and chapters that are not following the folder structure
Suggestion: Define constants at the top of the file such as the save in progress messages.
Suggestion: Chapters should be imported from a index.js file
How come we don’t define an export in each chapter folder that contains the whole body with each page? Example: chapter.js imports page1-5.js, we export chapters only and define them in the form Config
Suggestion: For page organization, include the title and path as part of the definition in the page.js files

Result: The form config file would be greatly reduced in lines of code and the definitions would live externally in the chapter folders, this would allow for a cleaner navigation to edit individual chapters or pages.

**Comment by mjknight50** [comment]
This PR is under review and we will have an engineering meeting on Monday (4/1) regarding this.
