### ISSUE TITLE
Edit ticket: broken link we found as part of google audit

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#79531]
- [x] Fix the broken link in [Google Analytics and Google Tag Manager](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager).

## Acceptance Criteria

- [x] [Google Analytics and Google Tag Manager](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager) is deployed without the broken link.

**Comment by jknipes** [comment]
Work done, moving to _Done_
