### ISSUE TITLE
Spike:  Determine how sentry works in DataDog

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#79544]
# Overview
In this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77413) we changed our code to be specific to pension, but validation is a separate challenge.

# Goal
- [] - Determine what Sentry is
- [] - How is it logged in DataDog
- [] - Did #77413 work correctly?

**Comment by wayne-weibel** [comment]
Sentry is another monitoring platform which receives captured messages from an application, compared to Datadog which (for us at least) is parsing logs.

Sentry is not logged to Datadog in that it is an explicit action, most of our errors do appear in Datadog.

We need to wait for an error to occur to know.  I did setup the Sentry project and team, and a slack notification to benefits-pension-notifications

**Comment by wayne-weibel** [comment]
There is a thread about sending [Sentry to Datadog then onto Slack](https://dsva.slack.com/archives/CU058Q9FH/p1709841646806469), but I do not believe that to be necessary with setting up Sentry Notifications in Slack and/or a webhook process
