### ISSUE TITLE
DBEx1: Identify recordEvents for GA4 Migration

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#79572]
Due: Friday, April 5th

The Platform and Analytics Team has requested that all VFS teams identify and inventory all recordEvent actions currently living in their codebase (aka custom events). This will ensure that these events are transitioned properly to GA4.

Tasks
Inventory the following forms and fill[ out this form]([url](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D)) detailing what custom events exist.

4192
0781/0781a
Form 21-8940, Veteran's Application for Increased Compensation Based on Unemployability
Form 21-4192 (Request for Employment Information)
Form 21-0781, Statement in Support of Claim for Service Connection for Post-Traumatic Stress Disorder
Form 21-0781a, Statement in Support of Claim for Service Connection for Post-Traumatic Stress Disorder Secondary to Personal Assault
Form 21-4142, Authorization to Disclose Information to the Department of Veterans Affairs (VA)
Form 21-4142a, General Release for Medical Provider Information to the Department of Veterans Affairs (VA)
Form 21-4502, Application for Automobile or Other Conveyance and Adaptive Equipment
Form 21-2680, Examination for Housebound Status or Permanent Need for Regular Aid and Attendance
Form 26-4555, Application in Acquiring Specially Adapted Housing or Special Home Adaptation Grant
Form 10-1394 (Application for Adaptive Equipment—Motor Vehicle)
Form 21-0779, Request for Nursing Home Information in Connection with Claim for Aid and Attendance

Acceptance Criteria

- All recordEvent actions recorded in Github ticket
- Github ticket submitted

**Comment by zack** [comment]
@sortizsh done with my list above ^. nothing actionable here.
