### ISSUE TITLE
Update the alert message for request flow when the services is down 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#79613]
## Description
We will need to update the alert message in the request flow when the user cannot submit their request for an appointment. 

<img width="674" alt="Screenshot 2024-04-09 at 4 27 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/63ab50f9-edff-4bd6-a64d-7523f4f88bab">

---

## Acceptance Criteria

- [x] Given the user is on the request for an appointment workflow
      When the user clicks on `Submit request` button and the services couldn't process the transaction
      Then the user will see the updated header in the message `We can't submit your request.`
      And page design matches the [copy doc]()

### Design Assets
N/A

### Reference 

- [#39752](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/39752)

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@JunTaoLuo is there a way to recreate this in staging? If not, could you post some full page screenshot of the page(s) where this appears? I'll need to see mobile and desktop views. Thanks!

**Comment by JunTaoLuo** [comment]
Hmm that's good question. I'm not sure how it can reproduced in staging since you'll need for a failure response. I reproduced locally by mocking a 500 api response. I can send you the screenshot of desktop and mobile views, one minute.

**Comment by JunTaoLuo** [comment]
Desktop:
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/7735642a-6b01-4df3-bcd3-094d6f328f68">
Mobile:
![image](https://github.com/user-attachments/assets/dbc4f733-b148-4568-b98a-9e40705b2e0d)

**Comment by JunTaoLuo** [comment]
And just to be thorough, here are the screenshots of the alert message for direct schedule appointments, which remains unchanged.

Desktop:
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/7dd0fc69-5166-4ea1-b18d-11acb9564ba1">
Mobile:
![image](https://github.com/user-attachments/assets/9d46193d-349b-4d16-9dfa-1d49812010f8)

**Comment by outerpress** [comment]
Looks great @JunTaoLuo ! FYI @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
