### ISSUE TITLE
Vets-api terminal access for Jun Tao Luo

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#79625]
### Your Name

Jun Tao Luo

### Your GitHub handle (terminal access is managed through GitHub)

@juntaoluo

### Team, Role, and Company of the target individual

Modernized Check-in, Developer, Agile Six Applications Inc

### Product Manager (PM) name and email

Jeff Roof, jeff.roof@adhocteam.us

### Product Owner (PO) name and email

Kay Lawyer

### COR Name (leave "None" if you listed an AWS user name above)

Eunice Garcia

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

# E-QIP transmittal confirmation:

*Note that my eqip was submitted when I was on a different VA team
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2030323/d086a013-6b4a-498a-80df-383d793b7308)

# eAPP transmittal
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2030323/b34483b6-f4a2-4d41-8246-9cb6a7834747)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
@JunTaoLuo, You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
