### ISSUE TITLE
Discovery for Sketch Audit - Research checklist

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79633]
Ask Naomi how to fix [Research checklist](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773011/Research+checklist) and if anything else needs to change other than that 1 line mentioning Sketch.

## Acceptance Criteria

- [x] Next steps are determined in regards to [Research checklist](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773011/Research+checklist).

**Comment by laucon** [comment]
Naomi fixed it herself and will be deployed Monday.

**Comment by jknipes** [comment]
Discovery completed, moving to _Done_
