### ISSUE TITLE
Contact Center Review for [Pension Benefits Team - Pension 527ez- Post Launch Updates]

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#79638]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
We re-launched the Pension Benefits 527ez form online in January 2024. It was deactivated in November 2023. Since January we've made some post-launch improvements and updated the Product Guide accordingly and are providing it here for your review.  

### Launch Date
*Please provide the launch or rollout date and details.*
The post launch improvements are ongoing, this updates the changes between January's launch and 3/29/24.  Changes include a New URL, updated guide related to several post launch enhancements including the following areas: Health and employment, Previous employment, Income and Assets, Direct Deposit, Other payment options, Supporting documents, Additional information,  Review and submit.

### Version Number
*Please provide the version number of the guide and/or video.*
Guide: Pension 527ez Form Product Guide 0329

### Product Guide
*Please provide product guide link*

[Pension 527ez Form Product Guide 0329.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14806991/Pension.527ez.Form.Product.Guide.0329.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
(Will check for VEO comment and close by 4/5 if all is good)

**Comment by starlow00** [comment]
There are no changes from VEO. I've attached a working copy. Please use it for future revisions/additions. Thank you!
[Form 21P-527EZ Pension Form v2 Product Guide SRT 03292024.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14908698/Form.21P-527EZ.Pension.Form.v2.Product.Guide.SRT.03292024.docx)
