### ISSUE TITLE
[Pre-release] Run content validation script on a schedule

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7964]
## Problem Statement
As outlined in https://github.com/department-of-veterans-affairs/va.gov-team/issues/7953, we need to run content validation on a schedule rather than in the build and deploy process.

## Possible Approach
Create a scheduled Jenkins job which:
1. Clones `vets-website` (temporary home of the standalone content validation script)
1. `aws s3 sync`s down the whole production S3 bucket
    - I think this is feasible to do in a reasonable time, but we should validate that assumption
1. Runs the standalone content validation script against the files on the image

## Acceptance Criteria
- [ ] The content validation script is run on a schedule
    - Every weekday at 4:00pm ET
    - Subject to change; I just figured some time after the daily deploy goes out...just in case :man_shrugging: 
- [ ] Violation errors are reported out to the appropriate Slack channel
    - Currently #cms-team

**Comment by billfienberg** [comment]
Content Validation Design Doc: https://github.com/department-of-veterans-affairs/va.gov-team/pull/9658

**Comment by billfienberg** [comment]
branch with example scheduled job in CircleCI: https://github.com/department-of-veterans-affairs/vets-website/compare/add-nightly-build-to-circleci

**Comment by timwright12** [comment]
This request has been submitted to Ops: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17968

**Comment by timwright12** [comment]
@meganhkelley  The Circle integration part of this is now in PR: https://github.com/department-of-veterans-affairs/content-build/pull/43

Probably still worth having ops add it into Jenkins since we can't control it

**Comment by meganhkelley** [comment]
Dependent on Ops completing https://github.com/department-of-veterans-affairs/va.gov-team/issues/17968

Related to #9853

**Comment by timwright12** [comment]
PR for this item into Jenkins: https://github.com/department-of-veterans-affairs/devops/pull/8334
