### ISSUE TITLE
Create PCI Threat Model

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#79655]
## Description
As part of our ATO, we must create a threat model for our Patient Check-in applications.

## Tasks
- Use this [Microsoft Threat Modeling Tool](https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-getting-started) to create a thread model for PCI
- Direct any question to this [Slack thread](https://dsva.slack.com/archives/C038C047X2P/p1711739712275159)

**Comment by brianseek** [comment]
Responded in slack to Stephen's request for validation and gave some thoughts. Will keep this here in case he has more feedback or if he wants us to create more models.

**Comment by brianseek** [comment]
going to close this ticket. If we get tapped to do more of this work, we can make a new ticket.

**Comment by brianseek** [comment]
Re-opening this ticket for this sprint since we were asked to take a shot at creating this.
