### ISSUE TITLE
Identity SDK - Define modular approach to AuthN and AuthZ

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#79664]
Tasks:

- Define the module approach to Authentication and Authorization
- Define what authentication methods, process and other looks like
- Define what authorization responses, process and other looks like
- Review existing handlers - login, signup and verify #82027
- Create diagram of login flow #81992
- Create pseudocode for login flow #82021

Authentication usually happens with these methods / mechanism. For this library specific and as well as to the VA, we're using the NIST 800-63-3 Digital Identity Guidelines because of Authenticator Assurance Levels (AALs).

- Username / password (common)
- Passwordless authentication
- AAL1, AAL2, AAL3

Authentication factors
- Something you know
- Something you have
- Something you are

Single-factor authentication is based on one factor of authentication process.
Multi-factor authentication combines multiple authentication factors.

Authorization is verifying the resources that the user's or device can access, or what actions can be perform, rather their permissions. 

- Token-based
- Role-based access control (RBAC), PBAC, ABAC, and PAM

DsLogon - potentially going away January 31, 2025
MHV provider won't be needed, it is going away

**Comment by parkerbees** [comment]
@acald-creator it looks like this was moved to "current sprint" two months ago - is the intent to complete this work in the current sprint (before July 17)? If not I will move to backlog. Also it shows that this is blocking another ticket that is in progress - has that blockage been resolved? Thx.

**Comment by acald-creator** [comment]
Move to in progress for quality check

**Comment by acald-creator** [comment]
Completed
