### ISSUE TITLE
[Post-release] Remove content validation from build pipeline

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7966]
## Task
After we've verified that the standalone content validation script is running successfully on a schedule, we need to remove the content validation from the build. This includes:
- Accessibility stage in the Jenkins pipeline
- Broken link checker in the Metalsmith build

## Acceptance Criteria
- [ ] Content validation only occurs during the standalone content validation job

**Comment by billfienberg** [comment]
Content Validation Design Doc: https://github.com/department-of-veterans-affairs/va.gov-team/pull/9658

**Comment by meganhkelley** [comment]
Validation script is not in the build pipeline, it will be run manually as part of release
