### ISSUE TITLE
Display details when an ITF already exists

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79676]
### To do
When a logged-in user starts a pension application and a type ‘pension’ ITF already exists and is valid
- Display when it was set and when it is valid till
- Display context on what it means to user (what actions they need to take to reap the benefits, by when)
- Address any concerns (ie: That it won’t risk other benefits?)
- Address potential points of confusion (ITF date vs form expiry dates)
- Address potential lag time for the API to reflect ITF submitted via paper, phone etc

### AC
- When a user already has a pension ITF in place, communicate it clearly and help them understand what it means
- When there are API issues, messaging is sufficient and users aren't confused

**Comment by ToddWebDev** [comment]
It looks like the 21P-526EZ has a page when resuming an application with an ITF. We can potentially use this  pattern as an implementation model.
<img width="307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE51QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47d2341db24ed7241868c7586372fc94e1b2df9b/staging.va.gov_disability_file-disability-claim-form-21-526ez_introduction%20%281%29.png" alt="staging.va.gov_disability_file-disability-claim-form-21-526ez_introduction (1).png" />

<img width="689" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3B1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6eecdce3f8caea9b8f5711319c599412ebd10223/staging.va.gov_disability_file-disability-claim-form-21-526ez_introduction.png" alt="staging.va.gov_disability_file-disability-claim-form-21-526ez_introduction.png" />

<img width="648" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFp1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50c0849b5ae762024f9f49236192e773bd561822/staging.va.gov_disability_file-disability-claim-form-21-526ez_introduction%20%282%29.png" alt="staging.va.gov_disability_file-disability-claim-form-21-526ez_introduction (2).png" />

**Comment by matt4su** [comment]
no longer needed, closing
