### ISSUE TITLE
[V0] Logging for ITF

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79680]
### To do
After ITF backend work has been been done, let's setup logging to monitor ITF actions in DataDog to surface information on:
- When it was successful (read and set)
- When it failed to set ITF
- When it was retried, when there was a delay in setting ITF (ie: it wasn't on the true date the application was started)
- Info that can aid troubleshooting

Benefits - ITF dashboard https://vagov.ddog-gov.com/dashboard/9c7-45v-3fx/benefits-intent-to-file?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1713721286385&to_ts=1716313286385&live=true

### AC
- Logs contain sufficient details to be able to troubleshoot ITF related issues
- We are able to monitor how well ITF is working

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/79680?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by buddhima-coforma** [comment]
Might be too early to point this one? We can discuss the spec first.
