### ISSUE TITLE
Add submission date config to 20-10207

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#79684]

**Comment by AdamOye** [comment]
Per Tricia, Yes

**Comment by tbaker1026** [comment]
[content.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1VaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c89563de48137dd0ab404fa6304308cd8d4e3a5f/content.pdf)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1laQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0826b7b4681dfb0e4baac7cf7190451dcb97d2be/2024-05-28_12-49-32.png" alt="2024-05-28_12-49-32.png" />
