### ISSUE TITLE
Recently visited Design spec

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#79692]
## Task Description
Using the lo-fi concept as a starting point, create a design spec for devs. Once this spec is done, we can hand off to devs and they can determine more precise feasibility. 

## Notes and References
- [Scheduling ideation figma file](https://www.figma.com/file/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-ideation?type=design&node-id=2240%3A9755&mode=design&t=Z3SECb2OWVR8gEsK-1)

## Acceptance Criteria
- [x] Figma file is created, and cover page is properly titled
- [x] Design spec is complete
## Deliverables
[Dev tickets](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/53329)

**Comment by outerpress** [comment]
@melissa-lefevre could you add links to the dev tickets to this ticket?
