### ISSUE TITLE
Clean up large files in `va.gov-team`

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#797]
## User Story
As a developer, I need `va.gov-team` to not be so huge to check out.

## Goal
* Simplify the repo contents.

## Acceptance Criteria
- [ ] No large files remaining in the repo.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by gunsch** [comment]
Following the [BFG docs](https://rtyley.github.io/bfg-repo-cleaner/):

```
git clone --mirror git@github.com:department-of-veterans-affairs/va.gov-team.git
java -jar ~/Downloads/bfg-1.13.0.jar --strip-blobs-bigger-than 5M va.gov-team.git
git push
```

this seems to have worked-ish, but doesn't modify `master`/current commit. re-trying with that

**Comment by gunsch** [comment]
```bash
java -jar ~/Downloads/bfg-1.13.0.jar --strip-blobs-bigger-than 5M --no-blob-protection va.gov-team.git
cd va.gov-team.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```

that worked --- cut about 600MB from the repo, need to re-add it though

**Comment by gunsch** [comment]
now hitting this error:

`This repository is over its data quota. Purchase more data packs to restore access.`

welp

**Comment by gmaciolek** [comment]
@gunsch and @meganhkelley do we want to keep this issue open?
