### ISSUE TITLE
ARF Design Onboarding - Courtney (Kristen to refine)

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#79704]
Welcome, Courtney! This ticket has resources and research artifacts to help you onboard to the Accredited Representative-Facing (ARF) Team. We recommend moving through this checklist in order, rather than hopping around. To the best of our ability, we have tried to provide context for the level of review needed for each item. 

As you're moving through the checklist, feel free to:
- Ask any questions in the [OCTO Slack channel #benefits-representative-facing](https://dsva.slack.com/archives/C05SUUM4GAW)
- Add any open questions to [ARF Open Questions Canvas](https://dsva.slack.com/docs/T03FECE8V/F06PMJPHMJQ) (pinned in our OCTO Slack channel)
- Bookmark or create a list of resources that you'd like to revisit later. For example, Kristen keeps a Google doc for herself that contain notes for each of our recurring meetings, a link to various helpful Figma files, etc.

### Join Slack channels
- [ ] [OCTO Slack channel #benefits-representative-facing](https://dsva.slack.com/archives/C05SUUM4GAW) - this is ARF + stakeholders. Most of our communications are in here. The only thing we try to avoid in here is discussions that aren't ready for broader feedback.
- [ ] [OCTO Slack channel #benefits-accredited-rep-design](https://dsva.slack.com/archives/C0643ADPP60) - private, this is ARF design/research + ARM design/research. We talk about design-specific topics and it's a "safe space" that Lesley created for our discussions.
- [ ] [Ad Hoc Slack channel #proj-vso-accredited-rep](https://adhoc.slack.com/archives/C068FLMB26M) - this is managed by Agile 6 and just the ARF team and a few internal stakeholders from the contracting company side. We use for program management type things and conversations we want more private to the team.
- [ ] [Personal chatter channel #vso-watercooler](https://app.slack.com/client/T025UGMV9/C067MEL18HK) - private to the team to share personal things
- [ ] Check with Harold that you're included in the @arfdesign handle on OCTO Slack. 

### Add recurring meetings to your calendar
If you don't have invitations for the below calls, ask in our Slack channel. 
- Team standup: The time for this varies a bit each day. You should see a 30-minute invitation for meeting on Monday, Wednesday, and Thursday. We only join these shorter standup calls if someone has indicated they have a "blocker" or something they want to discuss in our daily standup Slack posts in our [OCTO Slack channel](https://dsva.slack.com/archives/C05SUUM4GAW). 
- Mondays at 10:00 PT: Veteran Digital User Experience Weekly Design Sync: a VA Design-wide meeting. Find more in the [OCTO #design](https://dsva.slack.com/archives/C0NGDDXME) channel. Note that this conflicts with standup, so our design team will usually select 1-2 folks to skip standup and go to this meeting. We ask them to take [notes]() for the rest of the team. 
- Mondays 12:00-12:45 PT: ARF Design/Research Sync. [Notes doc](https://docs.google.com/document/d/1Si-7U_CtMSHoPb3moqa9BWeiQXPwzRyJWmAW5f3Wlb0/edit#heading=h.2lhwk95gdbkn). This is a dedicated time for ARF Design to talk with our UX Design Lead on the VA side. Sometimes we get assistance with blockers, other times these are dry-runs of presentations or cowork sessions. Agenda varies.
- Tuesdays 9:00-10:00 PT: VSO - Accredited Rep Standup / Meandering. [Notes](https://docs.google.com/document/d/1u1Z44R1KhMzwJHocksmuBdkD3oW07vXL0JvGIT1_j4k/edit#heading=h.8jhjl3il2xb). The first half of this meeting is our regular standup, minus any VA stakeholders. The second half is time for the whole team to discuss project or meta issues. Agenda varies.
- 1st/3rd Tuesdays 8:35-9:00 PT: Accredited Rep / Enablement (optional). [Notes](https://docs.google.com/document/d/1zbgYAkK0rLytArUmbBa1QaUGwBrTH_hy4wL6NuX2A5Q/edit#heading=h.gtkb7vlmfwgc). This is another dedicated time for the team to meet with all of our VA enablement stakeholders. Attendance is optional, but we try to designate at least 1 Designer to attend and take notes.
- Wednesday 9:05-9:55: Accred. Rep Crew meeting (optional). [Agenda](https://dsva.slack.com/docs/T03FECE8V/F06H1TS0GBZ). Because ARF's work is so closely integrated with the Accredited Representation Management (ARM) team, this is a biweekly opportunity to discuss current work, our product roadmaps, and ideate on getting our products more closely aligned. Attendance is optional, but we try to designate at least 1 Designer to attend and take notes.
- Wednesdays 12:00-1:00: Being Humans (optional). A time for us to hang out and chat in an informal setting, unrelated to work. 
- Thursdays 9:35-10:30 PT: Sprint Planning/Refinement
- Fridays 9:00-9:50 PT: Representative Research/Design Sync. [Notes](https://docs.google.com/document/d/1q3viYPfg2SAtAiyujrnCDBQzJjtwC966aBGFidi3P0k/edit#heading=h.jvgk0qlnx3km). ARF/ARM Researchers and Designers (+ our mutual UX Design Lead from the VA) discussing work-in-progress, getting peer feedback, keeping abreast of upcoming research studies. 

### Share your calendar 
All folks at Ad Hoc should have access to your calendar. In addition, please share your calendar ([instructions to share calendar](https://support.google.com/calendar/answer/37082?hl=en)) with these teammates: 
- [ ] harold.baines@agile6.com
- [ ] mike.marinos@agile6.com
- [ ] renata.keck@agile6.com
- [ ] gabe@coa.solutions
- [ ] will@coa.solutions
- [ ] alex@verdance.co
- [ ] Please reach out to Harold Baines to be added to ARF's team calendar (VA-VSO AccreditedRepresentativeFacingTeam). This is where all-team meetings and PTO are shared. 

## File sharing
- [ ] Request permission to view the [VSO Team Drive folder](https://drive.google.com/drive/folders/11LGxncWxuFFGi1VePl97xBu3ZOm2PBTw).
- [ ] Request permission to the Benefits Portfolio Sharepoint and [ARF's team folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing?csf=1&web=1&e=nBcDcq)

## High-Level Project Overview

- [ ] **READ** [What is an Accredited Representative?](https://www.benefits.va.gov/vso/) (VA.gov)
- [ ] **SKIM/BOOKMARK** for later this [glossary of terms and their definitions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/terminology-definitions.md) related to accredited representatives (GitHub)
- [ ] **SKIM** [Visual Breakdown in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704209289585/904f4f60fccc4e9b015d92d97f19f37347614e6f?sender=ucd326fb05b27d09e40350092) of Product Brief and Accredited Representatives White Paper _<--- Is this currently the best high-level summary we have?_
**If preferred, review original documents:**
&nbsp;&nbsp;&nbsp;&nbsp; - [Accredited Representatives White Paper](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QIRHZa&cid=866978cd%2D2497%2D496e%2Dadae%2D42c02258162e&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FAccredited%20Representatives%20on%20VA%2Egov%20Brief%20%28JQ%29%20%2D%20draft%2Epdf&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72&parent=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing) (Sharepoint) - Note that there are links to prior research that are covered elsewhere in this ticket.
&nbsp;&nbsp;&nbsp;&nbsp; - [Product Brief](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B55B2D6F7-1D14-49A3-8018-B6F943EB0931%7D&file=Representative-facing%20tools%20-%20Product%20vision.docx&action=default&mobileredirect=true) (Sharepoint) 

## Background Research 

- [ ] **WATCH** [Secondary research literature overview](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/stream.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FAR%5Fsecondaryresearch%5Fpreso%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview) (Sharepoint). Covers what's been done on VSOs, gaps in knowledge. Note that this is an overview recording of [this report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/fc4cf2841f56caea6bb66502b29a4ef1cf25abde/products/accredited-representation-management/research/2023-09-secondary-research/2023-09-secondary-research-accredited-representation-management.md) (GitHub). I would recommend starting with the recording and looking at the report or the Lighthouse research as needed to fill in knowledge gaps; a deep-dive is not necessary.
- [ ] **SKIM/BOOKMARK** for later: [VEO/Lighthouse research on VSOs](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research) (GitHub). Much of this is covered in the secondary literature review, and learnings have been added to in-progress research artifacts.

## Current State/SEP

- [ ] **SCAN** As you're moving through current state resources, feel free to add to/edit/leave comments in our [Current State Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ucd326fb05b27d09e40350092). 
- [ ] **REVIEW** [VSO Persona - add link] and our [prough-state draft of Attorney and Claims Agent personas](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101259400/65b0c7a81b3837794b36d55a3c1f6ab3629253f2?sender=ua71936780d8bc9a2d2b29830) (Mural)
- [ ] **WATCH** [SEP Walkthrough with DAV](https://dvagov.sharepoint.com/:v:/s/vaabdvro/Ee3gR_HqQ45CnY4OO5URNgYBJ-4haXSIx60F8Mmwz0MzPw?e=uJTLu9&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) (Sharepoint) - one of the 'big 6' VSOrgs
- [ ] **WATCH** the [SEP Demo](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/SEP%20Demos/SEP%20Demo%20with%20CTO-20231208_111227-Meeting%20Recording.mp4?csf=1&web=1&e=a3abDH) (Sharepoint) with the VEO team behind the tool. Note that these are SMEs we interviewed ([Link to research plan in Google Doc](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit)). 
- [ ] **SCAN** SEP-specific [existing research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695929155059/a302158eccec694ec7089bd6a02954421721987d?sender=ua71936780d8bc9a2d2b29830) (Mural). Note that some of these resources overlap with the literature review and the recordings linked elsewhere in this ticket. The research reports about SEP are very interesting!
- [ ] **EXPLORE** - Pull login credentials to [SEP and eBenefits](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7BD10426C1-A013-4818-9B90-1A213E83DA01%7D&file=SEP%20Account%20For%20Testing.xlsx&action=default&mobileredirect=true) and explore on your own! (Sharepoint)
- [ ] **WATCH** [SME Interview](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/stream.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FResearch%2FSME%20Interviews%2FMarty%20Caraway%20%2D%20recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview) with Marty Caraway, VSO liaison (Sharepoint)
- [ ] **WATCH** [Accredited Representative listening session](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/01-23-24%20Representative%20Listening%20Session/Recording?csf=1&web=1&e=cRufIR) (Sharepoint) and **REVIEW** the [findings report](https://docs.google.com/document/d/10GwEHzdVfaBydnrtx9br9YnDaTlDlT7jvBMo28Xy0B4/edit#heading=h.5cqfkqo9cc9b) (Google Docs)
- [ ] _if there's time_ **WATCH** at least 1 of these [earlier VSO interviews](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QIRHZa&cid=866978cd%2D2497%2D496e%2Dadae%2D42c02258162e&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FRecordings&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72) (Sharepoint). Notes are in the Existing Research Mural and there is a lot of overlap with these interviews and the walkthrough, so no need to go too in-depth
- [ ] **READ** Our [most recent research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/research/02-2024-user-interviews.md) on how VSOfficers interact with SEP and what they hope our new tool can offer. If time, **WATCH** some of the interviews.

## Future State 

- [ ] **REVIEW** the [design research roadmap](https://docs.google.com/document/d/1Ksk88KhZcXFJxySHNC9icoacRUoISJznsGb0VfFSqX0/edit#heading=h.m4rk6edp852v) (Google Docs)
- [ ] **REVIEW** the [ARF Project Visualization](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704824541218/8f0b5512ee478f78e6df1597ff9ab7230ec82df2?sender=ucc14575938bb14be79634773) (Mural), which contains some wireframes. Note that these have since been updated and moved to Figma (linked to below), but this will give you some grounding for how our designs have evolved. 

## UI Files 
- [ ] **REVIEW** [Team Figma file](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=0%3A146&mode=design&t=gl4rb0WaYXFgAKt3-1)
- [ ] **REVIEW** [VA Design System](https://design.va.gov/)
- [ ] **REVIEW** [VA Figma component library](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=121%3A1484&mode=design&t=Hu7ewqOYg1wv2Egn-1)

**Comment by uxrebecca** [comment]
Added description of Slack channels
