### ISSUE TITLE
[FE] Changes following functional review of travel workflow 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79719]
## Tasks 

- [ ] Checking top/bottom padding on additional info component on vehicle page and address page. Is it 16px top and bottom, like it is on the no receipts page? 

## AC 

- [ ]

**Comment by loripusey** [comment]
@benbrasso-agile6 Engineering group suggests we not have a "back to last screen" on error pages; maybe the concept of a "Start over" on errors screens; let's PL in stand up

**Comment by loripusey** [comment]
@benbrasso-agile6 can you clarify about what px are needed and on what page. Also, can you attach the correct wireframes.

**Comment by benbrasso-agile6** [comment]
> @benbrasso-agile6 can you clarify about what px are needed and on what page. Also, can you attach the correct wireframes.

If we can, I would use 16px bottom padding on the additional information components on these pages. They are very close to the buttons. 

<img width="300" alt="Screenshot 2024-04-02 at 4 57 33 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/55f87916-fd70-4cc4-87d5-75cd975e8845">

<br/><br/>

<img width="419" alt="Screenshot 2024-04-02 at 4 57 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/b32173cf-1433-411c-8948-e0a55fcbf630">

**Comment by lee-delarm6** [comment]
I'm assuming we want this done for check-in-app and travel-app (making changes right now as such)

**Comment by lee-delarm6** [comment]
Noticed after starting this that there IS 16px of margin added to the additional info section once it's opened. So there will be 32px if I add more margin anywhere between these two once it's opened (no matter where I add it)

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske can you help here please

**Comment by lee-delarm6** [comment]
> @zach-park @cgednalske can you help here please

Never mind, margins overlap so it's 16px and not 32px in total. This is the result, looks good to my eye now

![Screenshot 2024-04-04 at 10 19 16 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/770a9684-c022-4830-8304-d0bd5b0c7cac)
![Screenshot 2024-04-04 at 10 19 13 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/6392d07f-e998-4ffe-b77d-518a7ae62b32)

**Comment by benbrasso-agile6** [comment]
That looks nice!

**Comment by benbrasso-agile6** [comment]
Prolly good to merge

**Comment by benbrasso-agile6** [comment]
"back to" is GTG too
