### ISSUE TITLE
Correct Canadian Provinces in PDF submission

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#79723]
Steps:
1. Fill out the pension form with a mailing address that is in Canada in Nova Scotia province:

> Address 15 Highway 217
> City/Town	Freeport
> State/Province/Region	Nova Scotia
> Zip/Postal Code	B0V 1B0
> Country: CAN

2. Submit the form
3. Review the PDF data

Results:
The Nova Scotia abbrevation is incorrect. It display NV but it should be NS
There may be other incorrect provinces. Please check all against this list: https://www150.statcan.gc.ca/n1/pub/92-195-x/2011001/geo/prov/tbl/tbl8-eng.htm

Additional info:
@TaiWilkin investgiate and said this needs to be fixed in the shared vet-json-schema definitions

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/79723?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
@matt4su - please review the CAN province list

**Comment by mjknight50** [comment]
I've broadcasted this change on several slack channels.

**Comment by mjknight50** [comment]
The changes within vets-json-schema have been merged.
Are there any accompanying pieces needed for `vets-website` or `vets-api`?
@TaiWilkin @scottsdevelopment

**Comment by TaiWilkin** [comment]
@mjknight50 I believe we'll need to update vets-json-schema in vets-website and vets-api to the version. Otherwise, the only change needed should be a FE migration for in-progress forms to update them if they have the removed value in an address.

**Comment by mjknight50** [comment]
I've created two new tickets related to this:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/80660
https://github.com/department-of-veterans-affairs/va.gov-team/issues/80659
