### ISSUE TITLE
FE | Profile | IdentityNotVerified

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#79720]
## Issue Description
Some changes were made to the IdentityNotVerified component which included a `signInService` being passed to the component so that conditional content could be rendered.

**This caused an issue for two reasons:**
 
- The fallback content if no signInService is provided cause duplicate words and uncapitalized start of a sentence.
- The existing instances of the component didn't get updated to pass in the new signInService prop and so would use the fallback content no matter what.

## Front end tasks
- Pull sign in service name from state within existing code to make sure the correct prop is passed
- Update fallback content to not cause content issues
- Use constants of CSP_IDS to align with existing possible service names
- Make signInService a required prop for the component

## Acceptance Criteria
- [x] Content is rendered appropriately

**Comment by adamwhitlock1** [comment]
This was resolved within this hotfix PR
https://github.com/department-of-veterans-affairs/vets-website/pull/28883

We can verify this by logging into staging with a LOA1 user and verify that the sign in service is mentioned in the content of the Verify Your Identity alert.

ID.me LOA1
![Screenshot 2024-04-01 at 11 13 26 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/6b94a5b7-9325-4c68-8071-324e1f0d9e49)

There should _never_ be an instance of the alert when the sign in service name is not found, since you can't log in and see  this alert without some sort of sign in provider, but in the case where the component didn't get used with the appropriate service name being passed it will now render like so:

![Screenshot 2024-04-01 at 12 22 02 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/06da093d-e212-4d19-8885-22d773544c6d)

**Comment by mtcA6** [comment]
@adamwhitlock1 this good to close then?

**Comment by adamwhitlock1** [comment]
yes this can be closed.
