### ISSUE TITLE
[Pre-release] Add new Drupal content deploy trigger to populate content bucket

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7973]
## Description
After we create a [new Jenkins job to deploy content from the `content-build` repo to the content bucket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7971) , the trigger from Drupal needs to be updated to use it.

## Acceptance Criteria
- [ ] Add a trigger to Drupal so the content bucket starts getting populated via the `content-build` repo

**Comment by meganhkelley** [comment]
Need Ops or Jenkins access to complete this.

**Comment by meganhkelley** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/Jenkinsfile.content

**Comment by timwright12** [comment]
Slack thread about where this currently happens: https://dsva.slack.com/archives/CBU0KDSB1/p1610045465183800

Documentation:
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy/#partial-deploy--static-page-changes-only

**Comment by timwright12** [comment]
PR for this item into Jenkins: https://github.com/department-of-veterans-affairs/devops/pull/8334

**Comment by timwright12** [comment]
It appears as though, this will be a byproduct of [7971](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/7971)

Once the deploy to dev is set up and working we would just need to activate staging and prod in that job.

**Comment by timwright12** [comment]
Relevant Slack thread https://dsva.slack.com/archives/CJYRZK2HH/p1597873544205500?thread_ts=1597775615.150700&cid=CJYRZK2HH

apps.dev.va.gov
apps.sandbox.va.gov
apps.staging.va.gov
apps.www.va.gov

content.dev.va.gov
content.sandbox.va.gov
content.staging.va.gov
content.www.va.gov

**Comment by timwright12** [comment]
Devops PR https://github.com/department-of-veterans-affairs/devops/pull/8534

**Comment by theodur** [comment]
Currently, there is a [trigger](https://dsva.slack.com/files/U01DADWHLM6/F01P9JZLRDM/screen_shot_2021-03-01_at_10.11.02_am.png) in Drupal that allows content editors to do a content release using the [vets-website auto deploy job](http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-website/). Once we are ready to get the `content-build` on prod, we need to add a new trigger for releasing content using the [content-build job](http://jenkins.vfs.va.gov/job/deploys/job/content-build-prod/).

**Comment by theodur** [comment]
After the CMS engineering sync meeting today, we will coordinate with the CMS team as we make progress with the content build separation. This should happen in sync when the content build goes to prod.

**Comment by meganhkelley** [comment]
@indytechcook do y'all have a different ticket for this work that you're using to track? If so I will close this
