### ISSUE TITLE
[Pre-release] Change CMS repo to depend on the content build repo

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7974]
## Description
Once we have a [content build repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7969), Drupal PR instances can start using it to build the static content.

**Note:** I don't know what all goes into this, so I'm leaving the ticket pretty sparse for now. Feel free to add all the necessary details.

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by meganhkelley** [comment]
First step will be discovery to flesh out ticket & set estimate

**Comment by theodur** [comment]
After the CMS engineering sync meeting today, we will coordinate with the CMS team as we make progress with the content build separation. This should happen in sync when the content build goes to prod.

**Comment by indytechcook** [comment]
The work on the CMS is being tracked in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5005

**Comment by meganhkelley** [comment]
Closing as duplicative of ticket linked by Neil
