### ISSUE TITLE
Migrate V1 components in the FSR that need to be updated (Due by May 3, 2024)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#79756]
### V1 Updates Required on the following components

**`components/alerts/Alerts.jsx`**
- ```jsx
  <va-alert class="row vads-u-margin-bottom--5" data-testid="server-error" status="error" />
  ```

**`components/householdExpenses/InstallmentContract.jsx`**
- ```jsx
  <va-number-input 
    error={(submitted && amountDueMonthlyError) || null}
    hint={null}
    currency
    required
    inputmode="numeric"
    label="Minimum monthly payment amount"
    name="amountDueMonthly"
    id="amountDueMonthly"
    min={0}
    max={MAXIMUM_INSTALLMENT_AMOUNT}
    onInput={handleAmountDueMonthlyChange}
    value={contractRecord.amountDueMonthly}
  />
  ```

**`components/householdIncome/PayrollDeductionSampleTable.jsx`**
- ```jsx
  <va-table class="usa-table usa-table--borderless">
  ```
- ```jsx
  <va-table-row slot="headers">
  ```
- ```jsx
  <va-table-row>
  ```

**`components/shared/ItemLoop.jsx`** Deprecated --- lets remove the entire component
- ```jsx
  <va-table className="vads-u-margin-top--3 vads-u-margin-bottom--0">
  ```
- ```jsx
  <va-table-row slot="headers">
  ```


In total, there are 32 updates required across 14 different component files.


## Acceptance Criteria
- [ ] update all v1 components on the site


## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
In total, there are 32 updates required across 14 different component files.

- [ ] `containers/App.jsx:` 2 updates
- [ ] `containers/ConfirmationPage.jsx:` 2 updates
- [ ] `containers/IntroductionPage.jsx: `2 updates
- [ ] `components/alerts/Alerts.jsx:` 1 update
- [ ] `components/debtsAndCopays/AvailableDebtsAndCopays.jsx:` 3 updates
- [ ] `components/debtsAndCopays/Benefits.jsx:` 4 updates
- [ ] `components/debtsAndCopays/EnhancedBenefits.jsx: `1 update
- [ ] `components/householdExpenses/InstallmentContract.jsx:` 1 update
- [ ] `components/alerts/ComboAlerts.jsx:` 4 updates
- [ ] `components/householdIncome/PayrollDeductionSampleTable.jsx:` 3 updates
- [ ] `components/shared/GetFormHelp.jsx:` 5 updates
- [ ] `components/shared/ItemLoop.jsx: `2 updates
- [ ] `components/shared/PreSubmitSignature.jsx:` 1 update
- [ ] `components/veteranInformation/VeteranInfoBox.jsx:` 2 updates

In total, there are 32 updates required across 14 different component files.

**Comment by josephrlee** [comment]
Addding comments about this from the DS team from a slack convo:

> Re: card and telephone - those are okay as is.
> Re: React Bindings - historically yes they also need the uswds prop.
> I want to be clear, if you are migrating V1 components, then the assumption is that they currently have uswds="false" set on them since we merged a PR in a couple weeks ago that internally defaulted all components to `uswds="true"`. So, all you would need to do to migrate to V3 would be to remove `uswds="false" `, no need to set it to true.
> 
> I realize this is a little confusing because prior to V3 the guidance was to set `uswds="true"` in preparation for the change. This was so teams had a chance to get out in front of test suites potentially breaking. Now that we have V3 defaults, any remaining instances of uswds="false" just need to be removed in order to properly migrate.
> 
> `va-table` doesn't have a V3 right now, so there's no action needed on your part. `va-loading-indicator` doesn't have the uswds prop, so no action needed.

**Comment by Dr-Pongo** [comment]
We didn't have any components that needed to be officially updated to v3, but we had a number with a property that was no longer needed since it is being defaulted to true. We decided to remove that property now that platform is officially moving to remove any older versions. 

Moving to blocked while we battle with CI/CD issues. [Looks like there is a known issue, and it is being worked on](https://dsva.slack.com/archives/CBU0KDSB1/p1713546463785819).

**Comment by Dr-Pongo** [comment]
Finally merged!
