### ISSUE TITLE
Migrate V1 components in the Combined Debt Portal that need to be updated (due by May 3, 2024)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#79757]
### V1 Updates Required on the following components

**`combined/components/BalanceCard.jsx`**
- ```jsx
  <va-card
    show-shadow
    class="vads-u-padding--3 vads-u-margin-bottom--3"
    data-testid={`balance-card-${appType === APP_TYPES.DEBT ? 'debt' : 'copay'}`}
  >
  ```
- ```jsx
  <va-card
    show-shadow
    class="vads-u-padding--3 vads-u-margin-bottom--3"
    data-testid={`balance-card-zero-${appType === APP_TYPES.DEBT ? 'debt' : 'copay'}`}
  >
  ```

## Acceptance Criteria
- [x] update all v1 components on the site

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Adding comments about this from the [DS team from a slack convo](https://dsva.slack.com/archives/C03R5SBELQM/p1711469955329559):

> Re: card and telephone - those are okay as is.
> Re: React Bindings - historically yes they also need the uswds prop.
> I want to be clear, if you are migrating V1 components, then the assumption is that they currently have uswds="false" set on them since we merged a PR in a couple weeks ago that internally defaulted all components to `uswds="true"`. So, all you would need to do to migrate to V3 would be to remove `uswds="false" `, no need to set it to true.
> 
> I realize this is a little confusing because prior to V3 the guidance was to set `uswds="true"` in preparation for the change. This was so teams had a chance to get out in front of test suites potentially breaking. Now that we have V3 defaults, any remaining instances of uswds="false" just need to be removed in order to properly migrate.
> 
> `va-table` doesn't have a V3 right now, so there's no action needed on your part. `va-loading-indicator` doesn't have the uswds prop, so no action needed.

cc: @amponce @OptionSelect @Dr-Pongo @HeatherRienks @Tom-Davis

**Comment by OptionSelect** [comment]
<img width="298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHB0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3524c00bae787bc3a55feac26dfbb25b421344b5/image.png" alt="image.png" />

<img width="473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHh0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45abbee94afa77e0d85810b92debcd7318b9e6c3/image.png" alt="image.png" />

Step one: Remove uswds="false" is good, we have none in CDP.

**Comment by OptionSelect** [comment]
<img width="536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek50QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdb0fe65f5d8eef58e9cd3e7c349ca5927d97f57/image.png" alt="image.png" />

Step two: In progress, fixing breaking tests!

**Comment by OptionSelect** [comment]
All unit tests passing. <img width="944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZ0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b95351d118a5a09ec36b75e218ae228a4b3c8446/image.png" alt="image.png" />

**Comment by OptionSelect** [comment]
All E2E tests passed as well! 

<img width="808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJ0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad80fbe78efadea3cdbdf47077f1bc43d0a9ee8/image.png" alt="image.png" />
