### ISSUE TITLE
access to va notify

### ISSUE THREAD

**Issue by Henos-Wolde** [department-of-veterans-affairs/va.gov-team#79769]
## Your Details
1.  **henos wolde**
​
2.  **Business Line**
    (vera.)
​
## Notification Details
1.  **Notification type**
    ( both)
​
2.  **Please describe your use case.**
    (text msg going as text and not hyperlink and wanted to check template)
​
3.  **What actions can the user take based on the notification they receive?**
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​
4.  **What is the desired business outcome?**
    ( fix hyperlink .)
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    (ex., BVA hearing reminders are kicked off from Caseflow)
​
6.  **What will trigger the notification?**
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​
7.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (ex., PO has seen the content but it is not approved)
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
​
11.  **What is the anticipated volume of notifications per day, week, month?**
​
12.  **When does this notification need to be in production?**

**Comment by bevnobev** [comment]
Hi @Henos-Wolde.  Are you on the same team as Elshadaye Eshete? He/She reported a similar problem about a week ago.
