### ISSUE TITLE
Platform Atlas - Create monitoring Dashboards for Atlas V1

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79770]
## Issue Description
In order to meet the required [Product Outline requirements](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template), Monitoring Dashboards must be created for Atlas V1.

---
## Tasks
- [x] Create appropriate monitoring dashboards for Atlas V1

## Acceptance Criteria
- [x] The appropriate monitoring dashboards will be stood up and running for Atlas V1

**Comment by LindseySaari** [comment]
Monitoring dashboard has been [created here](https://vagov.ddog-gov.com/dashboard/gpq-mw8-i8b?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1710772237330&to_ts=1712068237330&live=true). These are application level metrics and logs from a technical standpoint.
