### ISSUE TITLE
QA Standards - Virtual Agent Chatbot - Chatbot

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#79791]
#### VFS team name
Virtual Agent Chatbot

#### VFS product name
Chatbot
#### VFS feature name
Benefits Microservices - Claims Status Flow

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 55.63

- Functions %: 53.16

- Statements %: 55.72

- Branches %: 45.51

- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####

All categories must have at least 80% coverage. 

---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by bushnicoleVA** [comment]
In regards to where these percentages of code coverage are coming from, did this coverage report come from the va-virtual-agent repository as a whole, or the subsection of vets-website where the virtual agent sits? Just so we know where to direct the chatbot platform team to assist us. Thank you!

**Comment by it-harrison** [comment]
@bushnicoleVA we take the values from the [frontend support dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report) (then find the entry for your app which corresponds to the top-level folder in `/applications` in `vets-website`)

**Comment by bushnicoleVA** [comment]
got it, thank you

**Comment by leahspix** [comment]
Apologies. I forgot to add that this is being worked on by the Chatbot Platform team. Issue to reflect that [here](https://app.zenhub.com/workspaces/va-chatbot-6011826e423fcf000eb231cb/issues/gh/department-of-veterans-affairs/va-virtual-agent-platform/18).

**Comment by leahspix** [comment]
@it-harrison The Chatbot platform is now passing code coverage at over 80% across the categories Lines, Functions, Statements, and Branches. We are waiting on a PR to be merged, but you can find that here: https://github.com/department-of-veterans-affairs/vets-website/pull/29458. The plan is to launch the skill and PVA topic to production on Wednesday, 5/8.
