### ISSUE TITLE
IPP PA UT Research Report

### ISSUE THREAD

**Issue by JKG199** [department-of-veterans-affairs/va.gov-team#79805]
Context

The in-person identity proofing service and application require input from proofing agents, in this case, MHV coordinators that currently verify Veterans identities and troubleshoot issues that come with a Veteran verifying their identity or upgrading their current MHV account. We have identified these coordinators as proofing agents, and conducted usability testing to clarify assumptions and requirements the service will need to meet in order to succeed. 

The purpose of a formal research report is to be able to share out research findings to stakeholders and partners in a readable and organized way.

While synthesis is an internal framework that research teams follow to make sense of findings, the research report allows the findings to tie back into the research plan and support the purpose of research.

AC's 

- [x] Create a research report outline 
- [x] Populate outlined research report based on Key Findings outlined and drafted in synthesis
- [x] Populate outlined research report using hypotheses that were supported or contradicted in synthesis
- [x] Provide headcount's for Key finding
- [x] Populate outlined research report with conclusions for each key finding based on summaries and supported participant quotes
- [x] Provide detailed summaries for each Key Finding presented
- [x]  Provide recommendations that were decided on during synthesis

**Comment by SophiaPhilipMO** [comment]
@SophiaPhilipMO will assist with recommendations

**Comment by skirkman16** [comment]
@JKG199 has revised and resolved comments

**Comment by SophiaPhilipMO** [comment]
I have added in recommendations and we will identify who is responsible for review during Design Sync on 4/17

**Comment by JKG199** [comment]
@skirkman16 tagged you to review, but should be good to close this out EOD tomorrow.

**Comment by SophiaPhilipMO** [comment]
Reviewed and posted to [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/IPP%20Usability%20Testing/2024-1-in-person-proofing-pilot-proofing-agent-usability-test/2024-1-in-person-proofing-pilot-proofing-agent-usability-test-research-report.md)
