### ISSUE TITLE
VSP Ops Onboarding 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#7981]
## Overview 
Welcome to the platform and more particularly the VSP Operations team.  This ticket is a checklist and guide to try and improve the onboarding process and get you up to speed. 

If you have any question please reach out to TJ. 

### Access to what you need
- [ ] Share your calendar with VSP; vsp-team.group@adhocteam.us

### Understanding VSP and where we sit
- [ ] [Overview of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Welcome%20to%20VSP.md#welcome-to-the-veteran-facing-services-platform)
- [ ] [Getting to know VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/vsp-team-member-onboarding.md)
- [ ] [Overview Presentation of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/VSP%20Mission%2C%20Objectives%2C%20Roadmap%2C%20and%20OKRs%20-%207-23-19.pdf)

### VSP Operations
High level:
- [ ] [High level info of the team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/operations#operations)
- [ ] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/operations-team-charter.md#operations-team-charter)

More details on our work: 
- [ ] [VSP Onboarding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/onboarding.md)
- [ ] [Daytime oncall role](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/daytime-oncall-support-role.md)
 - [ ] Talk with TJ about Sprint Objects 
- When creating an issue in GH, make sure to use the “Standard Issue Template”

**Comment by dginther** [comment]
All reviewed, Onboarding documents are sent to Amber.
