### ISSUE TITLE
Midpoint Review - Content - Veteran Facing forms - 21-4138 - Statement in Support of Claim

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#79825]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions
Overall, the flow looks really good. Kudos for taking on something so complicated. Most of my content feedback is around the intro page and punctuation inconsistencies. These will most likely be resolved by CAIA. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- The intro page is a little confusing and may not achieve the goal of ushering users to different forms. It may be worth using a different intro page pattern for this form. For instance, if the goal is to direct users to more specific forms, the “When to use another form or service” section should be more prominent and blunter. The section and page could also be more “scannable” since users are being sent to the wizard. It may be worth testing to see if all the information is needed since users are being sent to the wizard anyway. Lots of opportunities on this page; CAIA should also have some great advice and feedback. 
- Decision review content - The 3 decision review options are bolded throughout the form. According to the [Style Guide](https://design.va.gov/content-style-guide/bold-text), we don’t use bolded words in this case. Please revise by removing the bolding.
- Intro page > When to use another form or service > Request help with your chapter 31 benefits - There’s a typo in the second sentence; the “the” is missing an “e.” Please revise.
- Veteran or non-veteran claimant > Which of these best describes you? - In the second option, the period usage is incorrect. Please place a period after “I’m submitting a statement on behalf of someone else” and “You’ll need to have proper authorization on file…claimant.”  
- A: Preform subtask > What kind of statement do you want to submit? - The first option (“I want to submit a statement for my claim…”). The last sentence of the subtext is missing a comma before the “too.” Please revise so the sentence reads as: “If you’re submitting a statement on behalf…you can select this option, too.”
- Periods in answer choices - There is an inconsistent use of periods in answer choices throughout the form. Please ensure that periods are applied consistently throughout.

### Should 
- Intro page > When to use another form or service > To submit a supporting statement (“buddy statement”) for your claim or someone else’s - The information in this section is repetitive; the first bullet essentially repeats what was written as the introduction. This should be revised so information isn’t being repeated.

## Notes
Thank you again for the opportunity to review your work. Please continue to work with CAIA to develop this content. If you have any questions on this feedback, please don't hesitate to ask!

## Governance team actions
- [ ] Format feedback as individual tasks (check boxes)
- [ ] Assign this ticket to the VFS team member that opened the Slack request
- [ ] Add the VFS team product label
- [ ] Add the VFS team the feature label (if applicable)
- [ ] Add the touchpoint labels
- [ ] Add the practice area labels
- [ ] Add the Collaboration Cycle initiative milestone
- [ ] Add the Collaboration Cycle initiative epic

**Comment by rachelshearerux** [comment]
Thank you for the review Rebecca! This was great feedback and we've coordinated with CAIA. We'll be taking a different approach that simplifies the intro page.
