### ISSUE TITLE
[UX][FE] 10-10EZ - Minor content updates to enhanced eligibility content

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#79828]
## Issue Description
As a Veteran, I want the references within the form about the enhanced eligibility criteria and what it means to be accurate and reflect the most recent

- [Slack convo](https://dsva.slack.com/archives/C05QKRZGHFS/p1711652621000219)
> these three bullet points are missing from the list:
You were discharged for a disability resulting from something that happened to you in the line of duty.
You were discharged for a disability that got worse in the line of duty.
You’re a combat Veteran discharged or released on or after September 11, 2001.

---
## Tasks
- [x] (UX) Update designs to reflect most recent list and let FE know when ready
- [x] (FE) Update additional info content on 2 pages - the toxic exposure intro and the household info intro
- [x] Test/validate

## Acceptance Criteria
- The form is updated to match the most recent changes made to this list  (VA.gov page said it was published on March 27)

---

**Comment by jessicastump** [comment]
The cleaned up [Figma link can be found here](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=2718-9469&mode=design&t=rs2zOqdLkWzF6Y6l-0)
Edits apply to the additional info component content for "enhanced eligibility status" and found on two pages - the Toxic Exposure intro/opt in and the household financial section intro
cc @longmd

**Comment by longmd** [comment]
@jessicastump , these updates have been completed.
