### ISSUE TITLE
Update Logs for ATO Audit events

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#79832]
We need to add metadata to events that have been deemed as audit events related to ATO controls.

## Add the following log capabilities
- [ ] Add `method of login`, aka login.gov, idme, etc. to the accept and decline terms and conditions. The current log can be found [here](https://vagov.ddog-gov.com/logs?query=%40client_ip%3A141.126.200.99%20&cols=%40message_content%2C%40payload.user_uuid%2Cenv&event=AgAAAY6fzpw7HBPqyAAAAAAAAAAYAAAAAEFZNmZ6cXFWQUFDUEwtODY4cFpEWVFBSwAAACQAAAAAMDE4ZTlmZDctNGFmMi00NTU3LThjODQtNjc4ZTA0NGFiOGEw&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1712076709965&to_ts=1712080309965&live=false). The current log already has uuid of the user impacted, event action, and time of event.

**Comment by parkerbees** [comment]
Copied to Jira, closing here
