### ISSUE TITLE
Midpoint Review - IA Feedback - Veteran Facing forms - 21-4138 - Statement in Support of Claim

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#79847]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for coming through the Collab Cycle! We love working with y'all.
- I really appreciate the clear message text to notify users logging in with only LOA1 credentials that they need to verify their identity.
- The complete a subtask pattern is well-implemented.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Must:** Y'all had questions about usage of `(opens in a new tab)`. Our rule of thumb is that on pages outside of the form flow (i.e. the intro page), it's not necessary to open links in a new tab. It's only on pages _within_ the flow, when folks are entering data, that it's necessary. Please take a look at the `Find a VSO` link in the `Need Help?` section of each page and ensure it's updated to open in a new tab during the form flow if possible. 
- [ ] **Should: character count/limit indicator on statement textarea** On a few other forms, there's an indication of maximum input size allowed; is there a maximum size on the textarea for typing a statement? If so, please indicate and follow the [character count pattern](https://design.va.gov/components/form/text-input#with-character-count). 

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by rachelshearerux** [comment]
Thank you for the review, Erin! We've made these changes according to your feedback:
- intro-page links open on the same page 
- Added character count to the statement text area
