### ISSUE TITLE
VFS Custom Events for IIR & Resources for Schools

### ISSUE THREAD

**Issue by nicksayre** [department-of-veterans-affairs/va.gov-team#79848]
👉 Please note, the spreadsheet did not contain my product so I was unable to use the required dropdown field. The product is "Resources for Schools". It is generated from [this file](https://github.com/department-of-veterans-affairs/vagov-content/blob/main/pages/school-administrators.md) in the vagov-content repo.

# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- _(If using the Google Sheet, you can link that here:[Google doc](https://docs.google.com/spreadsheets/d/1-nAEqMKXpyGmxPlh5FMQITqr54FEGTpiQ2k3INAJx8Y/edit?usp=sharing)).
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by johnny-jesensky-adhoc** [comment]
@nicksayre - Thanks for submitting! Can you share access to the Google Doc with myself and @jestutt?

**Comment by jestutt** [comment]
@nicksayre  I don't see any events in the spreadsheet. Can you confirm that you don't have any custom events? 

@johnny-jesensky-adhoc

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  Can you help follow up on this one?

**Comment by johnny-jesensky-adhoc** [comment]
@nicksayre -- we're just seeing one instance of a custom event `recordEvent` in your attached spreadsheet. Can you confirm if this is the only one your product has?

<google-sheets-html-origin>
Event Type | File URL | Code Snippet | FE Comments
-- | -- | -- | --
Custom | vagov-content/pages/school-administrators.md | onClick="recordEvent({ event: 'nav-linkslist', 'links-list-header': 'Trainings and webinars'});" | This event appears to be referenced elsewhere in this repo and in vets-website

FYI @jestutt

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- was going through my old Slack messages with Nick, and confirmed they just had one instance of the custom event -- which is the one they submitted in row of the spreadsheet -- (where the example was originally).

> "Hey Johnny! I work on VA IIR. I think you’ve recently been messaging with a teammate of mine, Mason Crane (Oddball). I’ve found one Google Analytics custom event in a product we own. I’m not sure if I need to report it or not because I can see it’s not unique to our product; it’s used elsewhere in VA codebases. The event is nav-linkslist. I wondered if you can help me determine if I need to do something, or if this event is already covered."

Event Type | File URL | Code Snippet | FE Comments
-- | -- | -- | --
Custom | vagov-content/pages/school-administrators.md | onClick="recordEvent({ event: 'nav-linkslist', 'links-list-header': 'Trainings and webinars'});" | This event appears to be referenced elsewhere in this repo and in vets-website

FYI @nicksayre
