### ISSUE TITLE
Edit Ticket: Analytics Customer Support Guide part 2

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#79841]
This is in regards to [Analytics customer support guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide).

Tasks:
- [x] Do discovery work to see if the widget is acceptable or not
- [x] Replace the widget with an image with alt text and a caption
- [x] Check if the analytics team is ok with it

## Acceptance Criteria

- [x] Page is deployed with an image with alt text and captions instead of a widget

**Comment by jknipes** [comment]
Work is complete, moving to _Done_
