### ISSUE TITLE
[BE] 10-10EZR - Bug - Updating mailing address is not being saved

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#79857]
**Testing Environment:**
Environment: Staging
User email #: 228

**Summary:**
This was found while performing regression testing for EZR TERA. When updating the mailing address using the EZR form, the change isn't being reflected in their profile. Updating the home address using the EZR form does work in the same manner. This could just be an issue with staging environment, but wanted to file something in case there is an issue. 

**Steps to reproduce (User 228):**
1. Login as the above staging user
2. Go to "VA Benefits and Health Care" > "Health care" > "Apply for health care"
3. Click on the "Update your benefits information" link
4. Scroll down and click on the "Start your health benefits update form"
5. Continue through the form until you get to the "Mailing address" section
6. Change the mailing address in this section to something different
7. Proceed through the form and submit this information.
8. Get confirmation that this went through
8. Wait a couple minutes and then go to the Profile page and notice that the change made to the mailing address isn't updated

**Expected results:**
The mailing address is updated properly by using the EZR form

**Actual results:**
The mailing address is not being updated by using the EZR form

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDR0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6239a0f42c3ae99561407a26ea8e978e2727b65/Screen%20Recording%202024-04-02%20at%205.21.46%E2%80%AFPM.mov)

**Tasks:**

- [ ] Reach out to Faulkner to verify that we're sending info correctly
- [ ]

**Comment by alexseelig** [comment]
Matt L: think this is a VES issue, take form data and submit to VES via vets-api, we're "just a broker"

**Comment by JoshingYou1** [comment]
The issue stemmed from using invalid test addresses. It turns out, VA profile runs validation on address data, so our test data was being rejected, which is why the changes were not being reflected. After using a valid address (Pizza Hut FTW), I can confirm the address was updated as intended.
