### ISSUE TITLE
[DOCUMENTS]: GIBCT - Section 702 PDF MUST be reviewed for accessibility

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#7985]
**Feedback framework**
- **❗️ Must** be evaluated 1-3 sprints post launch. Ideally sooner. 
- [508 defect 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Description

One of the links is to a PDF for Section 702 of the Choice Act. This PDF must be evaluated for accessibility to ensure all Veterans can receive the additional information easily. Screenshot attached below.

The VFS accessibility specialists and the VA 508 office have resources and expertise to help review PDFs as needed.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] PDF passes a scan with the full [Acrobat Pro X accessibility checker](https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html) **or**
- [ ] PDF passes a scan with the [Common Look](https://commonlook.com/accessibility-software/pdf-validator/) Acrobat plugin
- [ ] PDF reads in correct order using screen reader. Preferably JAWS.

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

<img width="1000" alt="Screen Shot 2020-04-14 at 8 20 05 AM" src="https://user-images.githubusercontent.com/934879/79229740-25228680-7e29-11ea-8161-ff9d1b498ba8.png">

**Comment by dneel-bah** [comment]
Passed this along to the EDU Services team on 04/16 as owners of the PDF.

**Comment by desireeturner** [comment]
@1Copenut This is ready for your review.

**Comment by 1Copenut** [comment]
@desireeturner I ran the linked PDF on staging through the Acrobat Pro checker ( https://www.benefits.va.gov/gibill/docs/factsheets/section_702_factsheet.pdf). Is that the right version? I saw a few issues but will hold on commenting until I'm sure I've got the right version.

**Comment by TamGIBill** [comment]
Can you please provide a link to the page containing this link.  I couldn't find it.  Thanks.

**Comment by 1Copenut** [comment]
@TamGIBill & @desireeturner If you check out https://staging.va.gov/gi-bill-comparison-tool/profile/14900416 there's a link to the document under the Cautionary Information accordion.

**Comment by desireeturner** [comment]
@TamGIBill Any luck tracking this down?

**Comment by TamGIBill** [comment]
This factsheet is no longer available.  Please remove the link from VA.gov.
