### ISSUE TITLE
Add Redis caching to PreferredName / demographics call

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#79853]
### User story

As a Cartography team member, I want the REST client on vets-api to cache calls to the demographics service on the Profile API, so that the service only receives one request per user session regardless of how many pages are viewed.

### Notes
- The recommendations and policies are captured in
  - [Notes in the sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/personal_information/notes/preferred_name_20230321.md)
  - The post-mortem ([PR here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1570), not sure where final file lives)
- There is at least one user/API of the demographics API endpoint. Do we want to have that user/API use the Redis caching as well?
- Use the existing calls to test the demographics endpoint. MHV Landing page's personalization uses this endpoint. You can search the codebase for other places this endpoint is used.
- Refer to [How-to Guide: Caching with Redis-Namespace in Vets API Introduction](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-guide-caching-with-redis-namespace-in-vets-) for more Redis info.

Possible tasks:
- figure out Redis caching
- meet with Tom Harrison from AuthExp team for alignment
- implement Redis caching for the demographics service
- test however you can without going to staging or prod (testing will come in next ticket, #79924)
- Do we need a feature flag for this caching? It will probably depend on the architecture.
- Informed VA Profile team of the addition of the caching before merging, so they know to expect changes to the traffic and can monitor for errors

## Acceptance criteria
- Informed VA Profile team of the addition of the caching before merging. 
- The Vets API demographics service uses Redis caching for API requests.
- Existing Vets API services that use the demographics service are not affected by the change.

**Comment by wesrowe** [comment]
I'm pretty sure we meant to pull this into the sprint – it wasn't supposed to be in Ready still. Moving to in progress.

**Comment by dcloud** [comment]
Since the preferred name work was reverted per https://github.com/department-of-veterans-affairs/vets-api/pull/16015, I'm looking for things caching-related, but came across some relevant _policy_ code that I will cross-post on the policy ticket:

https://github.com/department-of-veterans-affairs/vets-api/blob/74b1e8551bed8e605a40e5dfcbc91ddb787553e3/app/services/users/profile.rb#L96-L113

**Comment by dcloud** [comment]
## Notes from mtg with Tom

Platform support team is making changes to VAProfile code to migrate to v3 service to get contact information. This will use the API endpoint where you ask for multiple pieces of information in one call: we should piggyback off that.

It might not make sense to proceed on this ticket if Platform is building essentially the same thing. Rachel Cassity from Platform is likely the point person for the Platform effort

**Comment by wesrowe** [comment]
Refinement 6/12: Daniel and Tom to get clarity on timeline in the next couple days.

**Comment by dcloud** [comment]
Per Tom H., the platform product team is doing prep work for department-of-veterans-affairs/va.gov-team/issues/83181 in this sprint, and have the upgrade work scheduled

**Comment by dcloud** [comment]
It looks like https://github.com/department-of-veterans-affairs/va.gov-team/issues/83186 was moved into the current sprint today

**Comment by dcloud** [comment]
I'll likely pick this back up, but removed myself as the assignee while I look at the other ticket, #79924, which I think can/should be done first

**Comment by dcloud** [comment]
http://localhost:3001/sign-in/mocked-auth

**Comment by dcloud** [comment]
I ended up starting with the caching before the policy bit, so re-assigned this to me.

**Comment by dcloud** [comment]
`RAILS_ENV=test bin/rails spec:requests`
