### ISSUE TITLE
Update Mural Board of VSR steps in processing 527EZ applications

### ISSUE THREAD

**Issue by Allexelaw** [department-of-veterans-affairs/va.gov-team#79864]
**Summary:**
Based on our learnings from the VSR interviews, we want to update the mural board that represents the steps that they take to process the Pension application

**Acceptance Criteria/To Do**
- [ ] Update mural board located here < @Allexelaw can you please add the URL to the mural board>

**Comment by Allexelaw** [comment]
Review notes from March 2024 meeting with VBA SMEs and update Mural Board to reflect VSR steps for processing 527 EZ Pension benefit applications

**Comment by Allexelaw** [comment]
April 8th, 2024 met with VBA SMEs to review updates to the VSR Steps to Processing 527EZ Applications and made updates to the mural board https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1708629678413/23448c79bc4bdd9e0651c7cdce459a57715a8066?sender=u7ebb3c5845122387949f4600   Next steps are to update board with additional information from the VSR research and then share for a last review w/ VBA SMEs.

**Comment by aplatt-coforma** [comment]
Backlogged due to prioritization shifts

**Comment by Allexelaw** [comment]
Updated and made revisions to the Mural Board based on VSR shadowing.  Sent revised Mural Board to VBA SME Dan Gifford and Brianna Mullans with several questions.   In the process of coordinating a meeting with the VBA SMEs to discuss.

**Comment by Allexelaw** [comment]
Updated and made revisions to the Mural Board based on VSR shadowing. Meeting w/ VBA SMEs Dan Gifford and Brianna Mullans on Fri 6/21 to discuss updates and questions.
