### ISSUE TITLE
Updating the analytics-monitoring > design-system-components Documentation Page

### ISSUE THREAD

**Issue by jamigibbs** [department-of-veterans-affairs/va.gov-team#79863]
### Description

Hi Joe! The design system team would like to make updates to this page about component library analytics:

https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components

I don't have the content written yet but before I start, can you let me know the most convenient way to do that? Significant updates  will need to be made to the table (none of the current web components are listed there) and probably some additions to the content above too.

Would drafting something in Google Docs be the easiest way to hand it off? Or is it possible for me to edit this page directly?

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components

related DST issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2625

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform Design System

**Comment by jknipes** [comment]
Hi @jamigibbs ! 
Here are the Confluence docs that explain the editing and creation processes:
[Create a New Page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page)
[Edit Existing Page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2046558209/Edit+Platform+website+documentation)
The Edit page links back to the Create page several times so both are worth having.
Communication Procedures:
[Platform website support overview](http://platform%20website%20support%20overview/)

Let us know if you have any questions by reaching out on Slack: [#platform-content](https://dsva.slack.com/archives/CL181NRJQ)

**Comment by jamigibbs** [comment]
Thank you @jknipes! I'll review those links. 👍
