### ISSUE TITLE
Desk Research on forms 21P-0969

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#79872]
For the 21P-0969 Income and Asset Statement in Support of Claim for Pension review the existing journeys and existing research / artifacts around submission and the post-submission experience.

Review existing OCTO product research and design (include Slack channels, Github docs, Sharepoint content, relevant research share-outs from handoff meeting).

Find all existing notifications to Veterans after submitting forms.

Past research findings.

Connect with Veteran Facing forms teams to find artifacts and also establish communication

Acceptance Criteria:
Document or deck with synthesized findings

**Comment by djones2113** [comment]
[Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712687714063/af7567fa3a504efd1aba1827b0f7cd180fd15719?sender=u7ebb3c5845122387949f4600) to document work on this ticket
