### ISSUE TITLE
FE | Profile | Audit codebase for non-design system element usage / update to design system components in older code

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#79876]
## Issue Description
We have migrated all the exiting components to use the v3 version, but there are some elements that are used throughout profile that aren't using the design system components at all.

Examples include:
Button elements
Text input field elements for certain fields
Checkbox inputs
Anchor tag elements

We need to audit the codebase again and make sure anything that can be converted to use the design system components is doing this. Not only should we look at the personalization/profile folder, but we should also look at the profile code that lives in platform too, as there might be some areas in there that need attention.

## Front end tasks
- Update any vanilla elements to use design system components where possible
- Update unit tests and e2e tests to work with these changes

## Acceptance Criteria
- [ ] Code updated with design system components
- [ ] Docs updated for any instances of elements that couldn't be migrated to design system components
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.

**Comment by mtcA6** [comment]
Good call! The collab cycle said they were going to start dinging teams for using imposter components.

**Comment by adamwhitlock1** [comment]
Robin currently has a PR open to do the majority of the work on this that we both committed code on. It is waiting from reviews from the other codeowners since it touched several application's tests. Once that is merged I will update this ticket on what remaining work might be needed, but otherwise it should be good to go.

The only main component that we didn't update were the LoadingButton usages as they cant use the va-button yet, and we have the experimental design pattern that Liz and I are working on for that.

**Comment by adamwhitlock1** [comment]
Robin merged his work and I have checked that the forms all function as expected with the move to the web component versions. We can close this out now.
