### ISSUE TITLE
Analytics Implementation for Content Grouping - Deprecate Product Used Custom Dimensions

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7988]
# Analytics Implementation or QA Request

## Description
- Migrate content groupings from Product used dimensions to content groupings
- Deprecate and repurpose custom dimensions previously being used
- Will require a large test effort and extended collaboration with other teams

## Acceptance Criteria
- [x] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
FYI @jonwehausen - I fixed the regex for these content groups so they should be recording data now...

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w178298118p176884211/_u.date00=20200518&_u.date01=20200518&explorer-segmentExplorer.segmentId=analytics.pageGroup4&explorer-table.plotKeys=%5B%5D/

![image](https://user-images.githubusercontent.com/62304138/82232235-5ac10080-98fc-11ea-9cf2-232fb21a69a3.png)

**Comment by jonwehausen** [comment]
@joanneesteban here is the writeup you requested for this functionality. 

### Summary 
The Analytics and Insights team is interested in deprecating 35 custom dimensions that have existed since early 2019 in lieu of [**content groupings**](https://support.google.com/analytics/answer/2853423?hl=en).

### [Custom Dimensions - Prefixed "Product \(or Product Area\") Used](https://analytics.google.com/analytics/web/#/a50123418w177519031p184624291/admin/custom-dimensions/m-content-dimensionsContent.rowShow=100&m-content-dimensionsContent.rowStart=0&m-content-dimensionsContent.sortColumnId=index&m-content-dimensionsContent.sortDescending=false)

![image](https://user-images.githubusercontent.com/48527022/86005333-83034b00-b9e2-11ea-92df-77d065eef0c2.png)

### Rationale
These custom dimensions are currently designed to help segment users according to "product used" based on user's last visited page path. There are several limitations with this implementation -- however the primary pertains to these dimensions being "User" scoped.  This means Google Analytics will only retain the last page path the user visited. From our teams perspective, the only real **insight** that can be drawn from these dimensions is not any more than what content groupings will provide -- a snapshot high-level overview of what products are being used. 

**Content groupings will allow us to provide the same level of insight of the existing functionality while also:** 

1. Freeing-up 30+ custom dimensions -- we can re-purpose for **more product-specific customizations directly fulfill teams KPIs.** 
2. Enabling better use of the behavior flow report -- seeing users moving from content areas with an out-of-box report, this is not possible currently with custom dimensions. 
3. Being much easier to use from a reporting perspective -- cuts down time in producing across-the-board high level product-related usage

### Next Steps
- @joanneesteban - Should we make an announcement to teams regarding this proposal / deprecation? Identifying if there are teams out there using these dimensions in any of their reports? 
- @bsmartin-ep & @bmcgrady-ep - We can begin to stage this in GTM, and it's most likely best to test within the Production test view to get better test cases for real volume / pagepath coverage. I have started this within our va.gov - Test View

![image](https://user-images.githubusercontent.com/48527022/86009856-af21ca80-b9e8-11ea-9fa5-72917d456fda.png)

**Comment by joanneesteban** [comment]
Thanks for sharing this, @jonwehausen ! Do you know if teams are actively using this functionality and where they find it?

**Comment by joanneesteban** [comment]
@bmcgrady-ep to spot check domains after @bsmartin-ep has the container in GTM set up.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Content Groups have been added to GTM and ready for your QA...

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000322

I also added a `^` to the health care URLs, which were missing it.

I considered merging the regex's, but this seems a bit easier to maintain.

Looks good in GTM preview....

![image](https://user-images.githubusercontent.com/62304138/86541450-04734580-bedb-11ea-98cf-c6db678178f7.png)

I also updated Content Group #1 on non-prod ALL to use the  _tracking code_:

![image](https://user-images.githubusercontent.com/62304138/86541515-8c594f80-bedb-11ea-91f1-1f8026c666a1.png)

We'll have to make a similar config update to any GA view where we want Content Groups.

**Comment by jonwehausen** [comment]
@bsmartin-ep , thank you sir! Will go through today and take a look at the config as well as QA.

**Comment by jonwehausen** [comment]
@bsmartin-ep , 

Updates made to container: 
- Created a secondary content group in the container called "**Main Nav Landing Hub Pages**" 
-- this is designed to contain the main navigation landing pages from the primary dropdown navigation
![image](https://user-images.githubusercontent.com/48527022/86649802-14108e00-bfb0-11ea-9518-ee4059c440f8.png)
- Removed "**Benefits**" from hub-page benefit based connt group and replaced with "Pension & Fiduciary", "Profile & Records", "Burials & Memorials" where appropriate
- These are only going to be setup in the WBC Modernized view for now since this primarily location where we care about under this context

For testing, I've enabled in GA an (and published the container) for each of those content groups within the Production Property > va.gov Test View. I also setup a couple custom reports that we can use within the Production Property > va.gov Test View. Be sure to filter these reports starting with today. We will want to monitor these over the next 24 hours.
    > [Only modernized content](https://analytics.google.com/analytics/web/template?uid=oqx_y3w2RTe-q2zvyzrgPw), just for reference...we could also setup a modernized content test view....
    > [Product Benefit Hub Test Report](https://analytics.google.com/analytics/web/template?uid=GO1gCumxSNqqYUwfqhCNGg)
    > [Main Nav Landing Page Test Report](https://analytics.google.com/analytics/web/template?uid=Iz92YpcIT3OQxz-23ddjxg)

I will monitor these over the next 24 hours to confirm we are good to go, and then cutover to live views.

**Comment by jonwehausen** [comment]
### Closing Updates

### Description of content groups
Content Group | Description of Use Case
------------ | -------------
Benefit Hubs | - Designed to bucket content according to the 6 benefit hubs currently seen on [scorecard](https://www.va.gov/performance-dashboard/) <br> Simple way to report on activity across benefit hubs
Main Nav Landing Hub Pages | - Designed to bucket content according to pages coming from the main navigation dropdown <br> - Titles and possible values are aligned according to the current navigation labels

##### Notes
- Only setup within the **WBC Modernized view** at this time (can easily expand to other views as necessary)
![image](https://user-images.githubusercontent.com/48527022/86917790-b2f1d300-c0f3-11ea-8f63-7e60961c63b1.png)
- We will continue to maintain these over time, and look at new content groups we may want to introduce moving forward - one tentatively being "Product Specific" 
- We will be able to configure queries to BigQuery to leverage this functionality
![image](https://user-images.githubusercontent.com/48527022/86918382-9efaa100-c0f4-11ea-83fd-5893bb9976a2.png)
- We don't need to explicitly deprecate Product Used custom dimensions at this time -- as data populates within these content groups over time, we can begin to repurpose those dimensions on an as-needed basis, we're not in any dire-need of repurposing those dimensions at this time. 
- Possible Benefit Hub Content Group values: 
   - Disability
   - Education 
   - Health Care
   - Profile & Records
   - Pension & Fiduciary
   - Burials & Memorials
- Possible Main Navigation Landing Hubs Content Group values: 
  - Education
  - Disability
  - Health Care
  - Records
  - Housing Assistance
  - Pension
  - Careers & Employment
  - Life Insurance
  - Burials and Memorials
  - Family Member Benefits
  - Service Member Benefits
- QA'ed by checking page paths being returned as `(not set)` in Google Analytics and updated within GTM to include those that belong in a group

Additions include: 
**Benefit Hub Content Group**
   - `^/records.*` = Profile & Records
   - `^/.*-health-care` = Health Care (includes pages like Pittsburgh VAMC)

**Main Navigation Landing Hubs**
  - `^/claim-or-appeal-status.*` = Disability
  - `^/track-claims.*` = Disability
