### ISSUE TITLE
Loading modal missing transparent overlay

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#79894]
## Summary

On the choose a location page when you select a location and hit continue, a loading spinner pops up. It used to have a transparent white overlay behind it, that seems to be missing. The loading text is unreadable when it overlaps the page text.

<img width="540" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzR3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b6733e655733550c299db7c5d2feea74191e2c7/Screenshot%202024-04-03%20at%208.55.07%E2%80%AFAM.png" alt="Screenshot 2024-04-03 at 8.55.07 AM.png" />

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** 

1. Start scheduling a new appointment
2. Reduce your screen width to 360 px
2. On the choose a location, select a location and hit continue. You may have to try a few to get the loading screen to appear.
3. Note that the loading spinner text overlaps the page text.

### Actual Result
See summary

### Desired Result
See summary

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by jenniemc** [comment]
Per conversion with @Cieramaddox, we will not be using the transparency overlay to display the message on the "Choose VA location page" in the VA direct appointment flow nor in the COVID appointment flow. Instead the loading message will appear underneath the 'eyeblow'.
cc: @outerpress

**Comment by Cieramaddox** [comment]
Validated from UX and good to close out!! @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
