### ISSUE TITLE
[COGNITION]: GIBCT - CONSIDER updating abbreviations for more clarity and understanding

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#7990]
**Feedback framework**

- **✔️ Consider** updating this in 1-3 sprints post launch
- [508 defect 4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Description

We have two abbreviations in the Dodge City example alerts that are a bit confusing when I'm auditing with a screen reader:

* **Sec 702** in the This school isn't approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits alert
* Learn about DoD probation reads **DoD** phonetically in JAWS, instead of reading out the abbreviation Dee Oh Dee.

I'd like to consider updating these in a couple of different ways to improve understanding. Snippets below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Screen readers read out the full Section 702 text properly
- [ ] Screen readers announce DoD properly as Dee Oh Dee

## Possible Fixes (optional)

```html
<!-- Remove the Sec 702 and replace with Section 702 in the middle of the paragraph -->
<p>This school isn't approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits because it doesn't comply with Section 702. Section 702 requires public universities to offer recent Veterans and other “covered individuals” in-state tuition, regardless of their state residency. </p>
```

```html
<!-- Change the DoD to DOD -->
<a
  href="https://www.dodmou.com/Home/Faq"
  target="_blank
  rel="noopener noreferrer"
>
  Learn about DOD probation
</a>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

**Comment by desireeturner** [comment]
This story will be resolved by #8082

**Comment by desireeturner** [comment]
@delli-gatti-michael @sonntag-adam This story was resolved by #8082, which is now closed. Please close out this story if you agree it has been resolved. Thanks!

**Comment by delli-gatti-michael** [comment]
@1Copenut The fix for this is on Staging

[DODGE CITY COMMUNITY COLLEGE](https://staging.va.gov/gi-bill-comparison-tool/profile/14900416) still has all of the caution flags if you're looking for an example.

**Comment by 1Copenut** [comment]
I verified this in Staging. Will move to close.
