### ISSUE TITLE
Update dependencies in IPP repo

### ISSUE THREAD

**Issue by moanu404** [department-of-veterans-affairs/va.gov-team#79905]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGN4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--956e3769714093bace3a7981fcd3e1decd7d494e/image.png" alt="image.png" />

Dependabot has been creating pull requests in our repositories to upgrade certain express packages. This is to triage and resolve these open PR's.

**Comment by skirkman16** [comment]
Mateo completed during Sprint 44
