### ISSUE TITLE
Team | Profile | CH33 Modifications | Go /no-go tracking

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#79907]
# Summary

Update 7/1:
  - Development is complete 
  - Need to QA again to make sure nothing has changed 
  - Biggest challenge/blocker is UAT and the DGIB team having a successful migration 

# Schedule 

<details><summary>Details</summary>
<p>

## Development (Due: Apr 18)

| Task                 | Status      | Team    | Point Person | Due   | Blocked | Comment |
| -------------------- | ----------- | ------- | ------------ | ----- | ------- | ------- |
| FE changes completed | Completed | Profile | Adam/Allison |  4/9 | No      |         |
| BE changed completed | In progress | Profile | Tom          | 4/9 | No      |      Still working through logging [5/1]   |
| Analytics added      | Completed     | Profile | Adam         | Late April    | No      |         |
| Email Confirm - VA Notify Template Update?     | Completed     | Profile | Travis/Tom         |  4/17 | No      |   ~Travis schedule meeting with Melanie Jones~  Tom is working on the new form |

## QA/Staging Prep (COMPLETED)

| Task                                | Status      | Team               | Point Person            | Due   | Blocked | Comment                                                      |
| ----------------------------------- | ----------- | ------------------ | ----------------------- | ----- | ------- | ------------------------------------------------------------ |
| Identify staging users              | Complete | Lighthouse         | Lorri Glover/Travis     | 4/9 | Yes     |                                                              |
| Resolve CH33/Lighthouse differences | Completed | Lighthouse         | Lorri Glover            | 4/9 | Yes     | [Slack thread started Apr-3](https://dsva.slack.com/archives/C06JV0KHZNF/p1712169050386049?thread_ts=1712165279.383599&cid=C06JV0KHZNF) this isn't really resolvable, it's a defect in the build that we now need to account for |
| Verify LINKTEST is Operational      | Completed    | Profile/Lighthouse | Travis/Tom/Lorri Glover | 4/9 | ?       | Emailed Mary Slaveck 4/3                                 |
| [Privacy and Security  ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1625)              | Complete     | Profile            | Travis/Tom              | ?     | No      |                                                              |

## QA Testing (Due: ASAP 4/18 for round 2) COMPLETED

| Task                 | Status  | Team    | Point Person       | Due  | Blocked | Comment |
| -------------------- | ------- | ------- | ------------------ | ---- | ------- | ------- |
| QA test cases ready  | Complete | Profile | Travis/Team    | ?    | No      |   [ the cases are ready](https://docs.google.com/spreadsheets/d/1rOD8w0YNTlfbefVK7t2RsWoYK_ui1gTkVhCXlJE5VDg/edit#gid=0) locating users has been a challenge in staging     |
| QA testing (round1)| Completed | Profile | Travis/Team    | 4/12    | No|         |
| QA testing (round2 post modifications) | Completed | Profile | Travis/Team    |  4/19    | Yes     |    pending pr from BE and FE, ideally we can complete this round by 4/19     |
| QA review            | Completed | Profile | Travis/Chante/Team | ?    | Yes     |         |

</p>
</details> 

## QA Testing July Launch 

| Task                 | Status  | Team    | Point Person       | Due  | Blocked | Comment |
| -------------------- | ------- | ------- | ------------------ | ---- | ------- | ------- |
| QA test cases ready  | Complete | Profile | Travis/Team    | ?    | No      |   [ the cases are ready](https://docs.google.com/spreadsheets/d/1rOD8w0YNTlfbefVK7t2RsWoYK_ui1gTkVhCXlJE5VDg/edit#gid=0) locating users has been a challenge in staging     |
| QA testing| Completed | Profile | Travis/Team    | | No|        |
|  Contact center guide update         | Completed | Profile | Travis |     | No |         |

## UAT (Due: 7/18)

| Task                  | Status  | Team    | Point Person | Due  | Blocked | Comment |
| --------------------- | ------- | ------- | ------------ | ---- | ------- | ------- |
| Recruit UAT participants  | Completed | Profile | Matt Marino | 7/15 |         |         |
| UAT sessions | Completed! | Profile | Matt Marino |  7/15-18 |         |    may need to recruit additional participants call 7/16 to discuss |

**Comment by tpharrison** [comment]
@mtcA6 @adamwhitlock1 @pamela-drouin

I updated the schedule with more details.  Hopefully, we can reference this going forward.  Please change anything that isn't correct.

At this point, the "Staging Prep" tasks pose the most significant impediments and require urgent resolution.

**Comment by pamela-drouin** [comment]
@mtcA6 @tpharrison I added myself under UAT 😄

**Comment by mtcA6** [comment]
QA spreadsheet is done. The test users will need to be updated but we've seen that's in complete shambles so far so once we have updated info we can update the users. Otherwise the actual test scenarios, steps to reproduce, and the links to the figma files should be updated.

**Comment by mattmarino-adhoc** [comment]
Will need to reconvene on 7/17 after additional test sessions
