### ISSUE TITLE
Credential Lock & Unlock Rake Task

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#79903]
# Description
* [Slack Discussion Thread](https://dsva.slack.com/archives/C06JLV08D32/p1712091550796659)
* Add a rake task to invoke `credential_lock` and `credential_unlock` functions.
* task will log requested csp_uuid & UserVerification `locked` status
* task takes csp uuids, not ICN - direct proxy for individual methods
  * engineers will still use ICNs to query all connected UserVerifications
* paired engineers run rake tasks and copy console logs into an issue ticket - issue ticket provides auditability

**Comment by bramleyjl** [comment]
<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fea92305c0f445bb43ee24a81c62d1160195d5e7/image.png" alt="image.png" />

Logging of lock/unlock rake tasks is now functioning properly

**Comment by kingbmike** [comment]
@bramleyjl What Epic should this fall under?

**Comment by bramleyjl** [comment]
The closest is the FWA dashboard epic which was ultimately responsible for the creation of these rake tasks, unless there's a more up to date FWA epic that would be a better fit.
