### ISSUE TITLE
Update swagger with new ARM POA endpoint

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#79915]
## Background
Update swagger with new ARM POA endpoint

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by oddball-lindsay** [comment]
@holdenhinkle we have this in the backlog, but I'm wondering if this was already done in one of these tickets and can close this out?

#82505 or #78101

**Comment by oddball-lindsay** [comment]
Confirmed with Holden that this work has already been done.
