### ISSUE TITLE
Access for [Gabriel Olavarria]

### ISSUE THREAD

**Issue by golavarr-va** [department-of-veterans-affairs/va.gov-team#7992]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Gabriel Olavarria
- Please Provide your email.
   > gabriel.olavarria@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API Development and Operations, Chief DevOps Engineer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwqWbJtYqqan642ei077VXYMkSkc3JyHo7WKsj07HpY4sSBJ1O+n/4SR6WdlMayRKeLq27N4BPlqpvv6AJyCeDpK8oYMphABP4TCyrGY1JhRtivWRB4qQkpjfTUP4G3DcWao/Q+1vOduY+eYIjIE/GYpNV8VDYfmAJxOsRLdq4X+taclPV5JVL8+J64Rw8xJw/uBRdtFQF3IS+A0hDLYFe2md+K3yF80ZXEponq+L1f92ZTAre426kEdJxRfcGisyAZijx7puCukI+272Hsknb/nXgHeQ7ejlVQs1tqplNcVoIh/lBYnirPAOFN+kAFNYvwoYvRznj//7hF33a1rNj AzureAD+GabrielOlavarria@DESKTOP-GOLAVARRIA
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by golavarr-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by benniemosher** [comment]
merged and deployed
