### ISSUE TITLE
Add slack bot instructions to canvas

### ISSUE THREAD

**Issue by CaitHawk** [department-of-veterans-affairs/va.gov-team#79923]
Once the slackbot is deployed on ```#vsp-identity``` we need to add directions on using it to the canvas.

**Comment by kdmeg-bluetiger** [comment]
Hey @CaitHawk - I took the Slack canvas into consideration in [this ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/79860), so there's some suggested copy in here already.
