### ISSUE TITLE
Add canvas to identity channel

### ISSUE THREAD

**Issue by CaitHawk** [department-of-veterans-affairs/va.gov-team#79921]
We need to move [this canvas](https://testidentitybotapp.slack.com/canvas/C06593XK5U1) to the ```#vsp-identity``` channel once we get the go ahead. 

*Note:* once the slack bot is deployed we need to add the directions in the canvas as well.

**Comment by kdmeg-bluetiger** [comment]
Hey @CaitHawk - FYI there are some recommended content updates for the Slack canvas related to changes in office hours and the Slackbot release prepped in [this issue](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/79860) which is going into review now. 

I'm flagging the relevant updates here pending review + approval here [!image]((https://share.zight.com/4guW6ZKE). Lmk if you have any questions!
