### ISSUE TITLE
ITF Backend Changes

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#79926]
### Description
The purpose of this ticket is to implement the backend logic to use the 527EZ online application Start date/time rather than the Submit date/time as the  Intent to File date/time.  The front-end design and logging is handled in other tickets, for example #79676, #79679, and #79680.

### To do
When an authenticated  user clicks the button to start the 527EZ online application, provide the ability to:
1. Identify if a valid pension ITF date/time exists and if so make it available for display to the front-end.
2.  if there is a technical issue and it cannot be determined if a valid  pension ITF date/time exists make this status available to the front-end. Do not block the user from populating and submitting the application.
3.  If there is no pension ITF or an invalid pension ITF, set a new pension ITF for this user based on when they clicked the button to start the online application and make it available to the front-end.
4.  Expiration dates: when a saved application is re-opened, calculate the dates to expiration and make available to the front end or if expired set a new date (last expiration date + 1 year).

### Acceptance Criteria
1. System can validate if an existing valid pension ITF exists for a user and make it available to the front end
2. System can return an error status when it cannot be determined if an existing valid pension ITF exists for a user
3. System can set a new pension ITF for the user when none exists
4. System shall not block a user from completing the application if they are unauthenticated or a valid pension ITF can not be confirmed.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/79926?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by mjknight50** [comment]
Closing in favor of the other tickets tracking this.
