### ISSUE TITLE
Configure Pre-Check-in, eCheck-in & Travel Applications to Display the Medallia Feedback Button

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#79934]
## Description 
We need to add a link to the in-app Veteran survey to our CIE applications so that we can get direct Veteran feedback on our applications and have a calculated customer satisfaction score.

[Slack thread w/ Contact Center](https://dsva.slack.com/archives/CNCEXNXK4/p1712157407747369)

## Tasks
- Configure Pre-Check-in, eCheck-in & Travel Applications to Display the Feedback Button
 
<img width="531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzB4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8de158ee4329268ba7e1aa62d274d76ae5b6f9c4/image.png" alt="image.png" />

**Comment by loripusey** [comment]
Waiting to hear back from the Contact Center on this.

**Comment by brianseek** [comment]
PR is open here: https://github.com/department-of-veterans-affairs/content-build/pull/2023

**Comment by brianseek** [comment]
Merged content-build PR. Moving this ticket to validation. @loripusey we should see this on prod in the next deployment...Which is maybe tomorrow. Will check back tomorrow to verify.

**Comment by brianseek** [comment]
Feedback button is showing and working on prod:
<img width="315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjE1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1212082e9de934ae647441ac1c699f8524791c44/www.va.gov_health-care_appointment-check-in_error_error%3Dno-token.png" alt="www.va.gov_health-care_appointment-check-in_error_error=no-token.png" />

**Comment by brianseek** [comment]
@loripusey this is ready to validate

**Comment by loripusey** [comment]
validated
