### ISSUE TITLE
CF: Staging profile link appending to the current school URL

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#7993]
Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/14900416. Scroll down and select "Visit the school's website to learn more". Observe the link https://staging.va.gov/gi-bill-comparison-tool/profile/www.dc3.edu.

The link should navigate to www.dc3.edu without the staging link prior.

![Screen Shot 2020-04-14 at 10.49.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5027fb98-c55f-412e-be92-87768d051a0f)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/640

Can be tested on gibct-data-service branch `caution-flag-url`

**Comment by sonntag-adam** [comment]
Navigates correctly to https://dc3.edu/

**Comment by sonntag-adam** [comment]
In staging, closing bug.
