### ISSUE TITLE
[Document Upload Failure] Email Veteran on SubmitUploads EVSS upload retry exhaustation

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#79945]
## Overview

At the moment, when a Veteran uploads documents for their claim, we submit each file in the [`EVSS::DisabilityCompensationSubmitUploads` job](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/evss/disability_compensation_form/submit_uploads.rb), which uploads them to EVSS. If this has problems and  fails all of its retries, the Veteran is unaware of this fact.

Create a mailer that goes out the Veteran when this happens, and tells them the name of the file that failed and provides them a way to physically mail the document instead.

## Acceptance Criteria 
- [x] The mailer should get triggered when the job has exhausted all of its retries.
- [x] It should include the filename of the file that failed (possibly obscured for PII reasons)
- [ ] It should tell them clearly where they should mail the file 
- [x] We should include logging/metrics/alerts to track these emails are being sent successfully

**Comment by va-albers** [comment]
Hi @NB28VT - for part of this initiative should we discuss this change with the contact center, so they are aware of how to handle cases if the veteran calls?

**Comment by NB28VT** [comment]
@juliepedtke @nnicholas7 FYI see @va-albers comment above. I assume the call center is already in the loop but just making sure!

**Comment by va-albers** [comment]
Watch officer note - notifications from [DD-189093](https://vagov.ddog-gov.com/monitors/189093) relate to this Issue.

**Comment by acrollet** [comment]
Hi folks, we saw this monitor get triggered 3 times yesterday. Are submissions being fixed manually at this point, or are we in a state where the upload failed and the veteran doesn't know about it? Thanks so much!

**Comment by acrollet** [comment]
This monitor triggered again yesterday.

**Comment by acrollet** [comment]
Hi @juliepedtke @NB28VT @emilytheis , this monitor alerted again yesterday - could someone provide a status update on this work, and confirm if jobs are being processed manually? Thanks so much!

cc @va-albers

**Comment by va-albers** [comment]
> Hi folks, we saw this monitor get triggered 3 times yesterday. Are submissions being fixed manually at this point, or are we in a state where the upload failed and the veteran doesn't know about it? Thanks so much!

https://dsva.slack.com/archives/C04KW0B46N5/p1715287183254499

**Comment by NB28VT** [comment]
> Hi @juliepedtke @NB28VT @emilytheis , this monitor alerted again yesterday - could someone provide a status update on this work, and confirm if jobs are being processed manually? Thanks so much!
> 
> cc @va-albers

We're in the middle of implementing a mailer the veteran will receive when an upload fails with instructions on how to physically mail it instead. Additionally we're providing a list of uploaded files in the Form 526 overflow PDF so the claim adjudicator can look out for anything that may be missing in the eFolder.

We're in touch with the contact center and the VA regarding the changes and downstream training involved. The development work for both implementations above is in review and on course for testing.

In regards to current failures that may be part of the manual remediation outside of this work, @emilytheis is that the case or do we want to plan to retroactively send mailers out for the failed uploads? Additionally we could brief the claim adjudicators now to confirm with the veteran that the attached files they see include everything the veteran meant to upload?

**Comment by sanjabaj2** [comment]
This was triggered again over the weekend. Perhaps we should open a new ticket to track manual intervention and use this ticket to track process improvement? Ideally, team should respond to failure in the notification channel and perform what ever manual intervention we agree needs to be done.

**Comment by NB28VT** [comment]
> This was triggered again over the weekend. Perhaps we should open a new ticket to track manual intervention and use this ticket to track process improvement? Ideally, team should respond to failure in the notification channel and perform what ever manual intervention we agree needs to be done.

@sanjabaj2 following up with my team and OCTO on this, this one is difficult to manually remediate because the file upload likely failed all of its retries for a technical reason we could only fix by having the veteran mail the document in physically (which this email would accomplish). But I've floated a few ideas for either starting a manual remediation process (which arguably could take as long or longer than the fix) or retroactively contacting veterans that may have their documents missing. I'll keep in touch, thanks for reaching out

**Comment by va-albers** [comment]
Watch Officer note - notifications from [DD-232746](https://vagov.ddog-gov.com/monitors/232746?view=spans) relate to this Issue.  Watch Officers please note that this issue is actively being work on, and it shouldn't be necessary to ping the team for a status until they put the fix in place (through at least 7/1/2024).
