### ISSUE TITLE
Spike: supporting documents behavior

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79956]
This topic surfaced from our [research backlog](https://docs.google.com/spreadsheets/d/1leE9rlL3OXI4BQgVatHMDF4nEY0LZSfqE8auVugSftQ/edit#gid=505472718) related to understanding undue experiences related to uploading supporting documents.

**Questions to answer**
1. Are there limitations on the number of supporting documents that can be uploaded? On file types? On file sizes? If yes, record these limits so they can be communicated to users
2. Is it indicated anywhere if an uploaded document(s) isn't submitted successfully? If not, what can we do about this?

**AC**
1. Findings have been shared
2. Follow on tickets have been created

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/79956?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by danlim715** [comment]
Answers to questions:
1. Doesn't look like there's a limit to the number of files uploaded from the json schema validations. Expected file types are `.pdf`, `.jpg`, `.jpeg`, and `.png`. Max file size is `20971520` bytes, aka 20~ MB and minimum file size is 1024 bytes, which is 1KB. It should be noted that the description shown to veterans of the file types accepted don't reflect the true list of file types accepted, as shown here:
<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db9bd10219e0a0ca168917aeda2a131a1a76950d/image.png" alt="image.png" />

2. This is the error message when someone uploads a file larger than 20MB
<img width="533" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f175f9a7e33e9807215e9f221e103c33287f01a2/image.png" alt="image.png" />
The catch all error message for failed doc upload attempts seems to look like this:
<img width="539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXVBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a34677d911ab5d71b0a2db0bd458c694fb091d6d/image.png" alt="image.png" />

**Comment by aplatt-coforma** [comment]
Update the [research backlog](https://docs.google.com/spreadsheets/d/1leE9rlL3OXI4BQgVatHMDF4nEY0LZSfqE8auVugSftQ/edit#gid=997340249) > Repository tab > row 42
