### ISSUE TITLE
VFS Custom Events for Sitewide Facilities & Facility Locator

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-team#79968]
# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- _(If using the Google Sheet, you can link that here:_ [Facility Locator Spreadsheet](https://docs.google.com/spreadsheets/d/1shb0jv1qALlxA_Z1qnn0WPA-YdKXvRENChD6AtPnmmg/edit#gid=0)).
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by jestutt** [comment]
Hi @eselkin 

Would you share and edit link for the sheet or add jamie.stutt@oddball.com, blivaditis@thesocompany.com and christine.young@adhocteam.us as editors? 

Also, I have a few questions about the Facility Locator events. Would you prefer I ask them in the sheet, here or should we set up a meeting?

**Comment by jilladams** [comment]
Share link: https://docs.google.com/spreadsheets/d/1shb0jv1qALlxA_Z1qnn0WPA-YdKXvRENChD6AtPnmmg/edit?usp=sharing

**Comment by jilladams** [comment]
@jestutt if you could add them here in the ticket as a starting point, that would be helpful if you don't mind. 

cc @Agile6MSkinner for visibility. Michael is the new Product Manager on our Facilities team.  MIchael: for context, the Analytics team is migrating onto Google's GA4, and trying to reduce the number of custom analytics events in use. Eli did an audit ([#17532](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17532)) of Facilities custom events, and this ticket is follow up on that, specifically for the Facility Locator.

**Comment by johnny-jesensky-adhoc** [comment]
The work from this ticket carried over from last sprint into our current one. This submission of custom events was also one of our larger/complex batches, which has taken more time to implement than anticipated. 

While we gave this an 8, we likely should have broken this out further in hindsight.

Similar to #79590 -- we anticipate this work being completed early in the current sprint, in order to be finished before the Universal Analytics (UA) sunset date of Monday, July 1.

FYI @jestutt, @davidconlon, @jwoodman5

**Comment by johnny-jesensky-adhoc** [comment]
These custom events have been implemented in GA4 -- can be found here.

<img width="971" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/e5d9e3ad-6c82-4fd5-b202-1cf57e4b9448">

Moving this to _**Done**_.

FYI @jestutt
