### ISSUE TITLE
VFS Custom Events for Sitewide Facilities & Vet Centers

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-team#79970]
# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- _(If using the Google Sheet, you can link that here:_ [Vet Centers Spreadsheet](https://docs.google.com/spreadsheets/d/1Wigxg6eU6lhrRiN8JOHnTGNO4T2lpjeOBYCy7rb3v2c/edit#gid=0) Some Vet Center pieces are also covered in the VAMC spreadsheet).
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by jestutt** [comment]
@eselkin  Did you know that `image-click` and `directions-link-click` are not events currently being tracked? I'm not sure you need `directions-link-click` since any html links to Google maps will trigger the existing `outbound_link` event. 

Also, I see an accordion expand/collapse event with a note that says it's being replaced (have you considered using one of the Design System's expandable components?). Can you confirm that it still only has the one variable and that it's `operating-status-heading`.

**Comment by jestutt** [comment]
@eselkin Checking in on the above questions. Also DM'd on Slack. 

@johnny-jesensky-adhoc
