### ISSUE TITLE
Redirect Request: VA Direct Deposit and Contact Information Page

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#7997]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*Redirect VA Direct Deposit and Contact Information Page to new Direct Deposit page*

### Requestor team info
Public Websites

### Implementation date
Date new URL(s) will be live: *URL is live*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing:  It can be implemented now as URL is live.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
*https://www.va.gov/change-your-va-direct-deposit-and-contact-information/* | *https://www.va.gov/change-direct-deposit/*

### Definition of done
- [X] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
This redirect is vetted and can be implemented when needed. 

FYI, there are very few visits to this page, and if we remove the current search recommendation as a referrer,  there will likely be less than an avg of 25 visits per day.  We may not need to implement this redirect, but can if we want to be safe.

**Comment by lunascoop** [comment]
@mnorthuis We're going to move forward with the redirect per Jen's directive during our backlog grooming meeting. @ncksllvn or @kelsonic this can be implemented at any time before the end of this sprint since this is not a legacy page.

**Comment by kelsonic** [comment]
PR is up! 🙂https://github.com/department-of-veterans-affairs/devops/pull/6746

**Comment by kelsonic** [comment]
Merged and deployed to all envs! @lunascoop could you validate when you have a chance?

https://www.va.gov/change-your-va-direct-deposit-and-contact-information/

**Comment by lunascoop** [comment]
Validated and closing ticket. Thanks @kelsonic !
