### ISSUE TITLE
Figma A11y - Spelling and Grammar Check for Proofing Agent Facing Screens

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#79989]
As a designer, I need to make sure that the content on my Figma prototypes are completely void of errors. Adding a formal spelling and grammar check to our design iterations will help us avoid any confusion or further content iterations when running user tests or handing off designs to developers.

Who
Members of the design team

When
Any time there is a content iteration.

How
Request access to [SPELLL](https://www.figma.com/community/plugin/754026612866636376/spelll-spelling-grammar-checking-for-figma-figjam) and use the plugin to make sure that all content is free of grammar and spelling errors. Remove any abbreviations or acronyms and replace with complete words.

Definition of done

- [x] Use [SPELLL](https://www.figma.com/community/plugin/754026612866636376/spelll-spelling-grammar-checking-for-figma-figjam) to identify spelling and grammar checks.
- [x] Correct the errors before presentations and handoffs.

**Comment by SophiaPhilipMO** [comment]
<img width="418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e32ba4282e2912934c4737fc35340bf773ac55b4/image.png" alt="image.png" />

**Comment by SophiaPhilipMO** [comment]
Edits made
<img width="433" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3568f6ad5214b7952d0b0f2b776a9d4fabd3d653/image.png" alt="image.png" />

**Comment by SophiaPhilipMO** [comment]
Reviewed and made edits to all sections
