### ISSUE TITLE
GA4 Discovery: Research on Key Events within GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#79998]
### Description
This ticket is to perform additional research on how Google calculates some of the key metrics and events we are collecting, as well as looking for examples of where differences may emerge between the GA4 GUI and BigQuery. We are finding through validation and refinement, that certain metrics might lead to unexpected results, or differences in counts between GA4 and BigQuery.

Example of [resource](https://tanelytics.com/ga4-session_start-and-first_visit-events/) explaining difference in sessions -- number of session_start events ≠ number of sessions.

This information will eventually be used to help update our data dictionaries to make them GA4-specific.

Record all findings in this [artifact](https://docs.google.com/document/d/1RoGeotpQ6wnmTrxDffeJPkLmA5dkJgRlNqe2taaSjg8/edit).

---

### Tasks
- Perform research around some the key metrics and events we are collecting from GA4.
- Look for SQL queries we might be able to leverage within BigQuery.
- Share findings with Jamie, and Phil, including any identified SQL queries we can leverage, or instances where reporting may be off, or different from GA4 and BigQuery.
- Document findings in GA4 Migration 2024 Confluence space.

### Acceptance Criteria

- [x] Findings have been shared with team, and documented in GA4 Migration 2024 Confluence space.
- [x] Findings have been documented in Confluence, so we can reference for future training material, and updates to the Platform Website.

**Comment by johnny-jesensky-adhoc** [comment]
Look to block an hour of time per attribute for this.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt - can you add the specific events to research in this?

FYI @Blivaditis, @ChristineYoungZA

**Comment by jestutt** [comment]
@ChristineYoungZA @Blivaditis Of the items listed out in ticket 79416, here are the ones that I would focus on first: 

- date
- user
- session_id
- site_url
- isExit
- NewUser

I think Phil has found all the new field/column names so your really looking for change in formatting or calculation. 

If you get thru those, you might also take a look at these: 

- timing - think calculating time on site or page 
- session bounces vs the user_engagement event

**Comment by Blivaditis** [comment]
Thank you Jamie!

**Comment by Blivaditis** [comment]
Links/resources have been collected for each metric/dimension which can be found in this [artifact](https://docs.google.com/document/d/1RoGeotpQ6wnmTrxDffeJPkLmA5dkJgRlNqe2taaSjg8/edit). Johnny wants this info recorded in confluence however it will likely be more beneficial to unpack what we collected (find query portion/calculations) and then input our findings into confluence.

**Comment by Blivaditis** [comment]
Our findings can be found in our confluence page [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3111714860/GA4+Discovery+Resource+collection+on+Dimension+and+Metrics+within+GA4).

**Comment by johnny-jesensky-adhoc** [comment]
Thanks @Blivaditis -- I'll take a closer look, but moving this to Done for now.
