### ISSUE TITLE
Follow-up form.js refactor

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#80003]
Additional tasks following the form.js refactor:

- [x] consistent order to page definition:
```
export default {
  title: 'title',
  path: 'path',
  [additional arguments for the page],
  uiSchema: { ... },
  schema: { ... },
}
```
- [x] move `generateEmployersSchemas` and `generateMedicalCentersSchemas` to chapter 3 helper.js
- [x] move the `submit` function from pensions/helper.js to pensions/config/form.js

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/80003?planning-poker) with Zenhub @wayne-weibel @scottsdevelopment
