### ISSUE TITLE
Identify metrics to measure the impact of branding and self-service content

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#80008]
## Audience
_**Who** is this content for?_
Internal: Identity team and product leadership

## Purpose
_What will this content help the audience **do**? Use verbs to explain the purpose of the content._
- Understand the impact of content in the context of self-service
- Identify areas of improvement

## Brief description
_**What** is the request and **where** will the content be published?_

- Reports on metrics documented in internal Github documentation

## Content design tasks

- [x] Request access to GA and Domo
- [x] Identify measures of success for self-service and deflection
- [x] Define baseline measures for current performance
- [x] Meet with Analytics team to see what metrics we can ascertain from Github or Platform documentation
- [x] identify what metrics we can get from Github

## Documentation
_Related artifacts_
- [Github documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2024-01%20Identity%20Support%20Process/research%20on%20content%20metrics.md)
[Research doc](https://docs.google.com/document/d/1r4STYp4Ryf0aXRLtKiEQ5BtrkEzjsPffnyVx_YqysqY/edit?usp=sharing)
- [Identity team branding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2024-01%20Identity%20Support%20Process/team-branding-workshop-march27demo.pdf)
- [Support process research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2024-01%20Identity%20Support%20Process/support-process-project-research.pdf)

## Product notes
_Additional product or business considerations from stakeholders._

- [Support process post-MVP product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Product%20Briefs/Request%20%26%20Support%20Post-MVP.md)
- [Monthly metrics product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Product%20Briefs/Identity%20Monthly%20Metrics.md)

## Acceptance criteria
- [x] Documentation has been updated
- [x] Add finalized research to Github
- [x] Reviewed by UX Team
- [x] Reviewed by PMs
- [ ] Reviewed by CAIA (logged-out website content only)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kdmeg-bluetiger** [comment]
**Note:** we can get more baseline performance analytics with light engineering resources by using [Github APIs](docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-page-views). 

@jimcconnelly - is this something we'd like to do in an upcoming sprint to establish baselines measurements for self-service deflection through content/branding?

**Comment by jimcconnelly** [comment]
> **Note:** we can get more baseline performance analytics with light engineering resources by using [Github APIs](docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-page-views).
> 
> @jimcconnelly - is this something we'd like to do in an upcoming sprint to establish baselines measurements for self-service deflection through content/branding?

Yes, but I think as part of the Request & Support Post-MVP project overall.

**Comment by kdmeg-bluetiger** [comment]
> > **Note:** we can get more baseline performance analytics with light engineering resources by using [Github APIs](docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-page-views).
> > @jimcconnelly - is this something we'd like to do in an upcoming sprint to establish baselines measurements for self-service deflection through content/branding?
> 
> Yes, but I think as part of the Request & Support Post-MVP project overall.

Ok, is there any timeline for that work? For reference, Github offers page view data on a rolling 14-day basis. So we wouldn't get any baseline metrics unless we tackle this in an upcoming sprint.

If tracking these metrics after content changes are already made are still of interest, let me know and I can create a backlog ticket for that epic. TY!

**Comment by jimcconnelly** [comment]
Hi Megan, sorry I missed this, but at some point in the last week, it struck me we might be able to get engineering resources for this in the [Identity Monthly Metrics epic](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/80034) epic. It's where we're tracking the dashboards that Josh created.

Tracking the github engagement might be a natural for that.

**Comment by kdmeg-bluetiger** [comment]
Sounds good! I created a [backlog ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/82755) for that work whenever this project kicks off.
