### ISSUE TITLE
VSP QA feedback on Caution Flags Comparison Tool [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#8000]
### Links
**Test Runs Summary:**
https://dsvavsp.testrail.io/index.php?/reports/view/56
**Coverage for References Report**
Not supplied
**Defects**
https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3A%22bug%22+and+label%3A%22bah-cautionFlag%22+

### Feedback
**[Test Runs Summary](https://dsvavsp.testrail.io/index.php?/reports/view/56)** 
1. Great coverage represented in TestRail -- thanks!

**Coverage for References Report**
1. It looks like you have used the references field to link user stories from GitHub, but you did not generate a report.  For an example of this report, please read through [QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/executing-tests.md).

**Defects**
1. For future runs, please include links to defects from the relevant test case.  See #5 on within the [executing tests tutorial ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/executing-tests.md) for a bit more detail regarding how you might want to link defects from within TestRail.
1. If your defects are linked from TestRail to GitHub then you can easily run the Summary (Defects) report in order to get a quick view of all defects uncovered during your test runs.

## Definition of Done
- [x] Acknowledge each item of feedback with a decision
- [x] VSP QA will close ticket after reviewing feedback decisions

**Comment by delli-gatti-michael** [comment]
Hey Peter

I generated a [Coverage for References Report](https://dsvavsp.testrail.io/index.php?/reports/view/58
). If that's not the one you need, please let me know.

We can definitely start linking up defects the way you've described. I can see how that would be beneficial.

**Comment by desireeturner** [comment]
@pjhill is there any additional action we need to take before closing this issue? Thank you!

**Comment by pjhill** [comment]
Looks great -- thanks for the additional report!
