### ISSUE TITLE
Update Bank Account UI to use web components

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#80009]
Update the bank account information page to use web components. Currently the UI is rendered by a bankAccountUI widget.

- Account type
- Bank name
- Account number
- Routing number 

#### Existing
<img width="837" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVkyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d07267fd621fdb6f3c9e541c576019aa1f36abe4/AdditionalInformation-BankAccount.png" alt="AdditionalInformation-BankAccount.png" />

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/80009?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel
