### ISSUE TITLE
Analytics Implementation or QA Support for Comparison Tool Caution Flags Enhancements

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8001]
# Analytics Implementation or QA Request

## Description
- Is this request for Google Analytics implementation or QA? 
     - Google Analytics implementation

- Who is this request for?
     > VA.gov Education (Comparison Tool)
     - Will McCormack
     - Darrell Neel
     - Amy Knox
     - Dan Shawkey
     - Desiree Turner

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
     - VA.gov Education (Comparison Tool)
    
- Provide the Domain where Google Analytics needs to be implemented
    - https://staging.va.gov/gi-bill-comparison-tool/
    - https://www.va.gov/gi-bill-comparison-tool/
    - No PII is passed in the URL    
    
- Please provide any upcoming deadlines or important milestones
    - Target production release on 04/22/2020.

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
        - https://staging.va.gov/gi-bill-comparison-tool/
        - https://staging.va.gov/gi-bill-comparison-tool/profile/21015323
        - https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=college+

    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
       - 1. Track general use of this caution flag "View details below" jumplink at the top of flagged profile page
       - 2. Track aggregated clicks out of the Comparison Tool on the external links in the “Cautionary information” accordion   

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - [N/A - publicly available functionality]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - [N/A - publicly available functionality]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - N/A

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@dneel-bah Thank you -- Acknowledging receipt. We will take a look and get back with you.

**Comment by jonwehausen** [comment]
### Datalayer Requirements - WIP 

Description of Interaction | Screenshot | Datalayer Push
------------ | ------------- | -------------
Click on 'view details below' inside of warning alert box | ![image](https://user-images.githubusercontent.com/48527022/79370194-40bc8880-7f20-11ea-86a3-d7db7e6a84fb.png) | ```dataLayer.push({```<br>```'event':'nav-warning-alert-box-content-link-click',```<br>```'alertBoxHeading': 'This school has a cautionary warning'```<br>```});```
Click on 'learn more about this school's accreditation' | ![image](https://user-images.githubusercontent.com/48527022/79370512-d1936400-7f20-11ea-94b5-11c32fe1bd79.png) | ```dataLayer.push({```<br>```'event':'nav-warning-alert-box-content-link-click',```<br>```'alertBoxHeading': 'School has an accreditation issue'```<br>```});```

**Comment by dneel-bah** [comment]
@jonwehausen We are still on track.  We have 1 small item that we are expecting to get feedback on NLT tomorrow afternoon.

**Comment by jonwehausen** [comment]
@dneel-bah Great - May you confirm if the requirements above look to reflect each of the pieces you're looking to track?

**Comment by jonwehausen** [comment]
@amyknox and I spoke via Slack to confirm several variations cautionary flags will exist within the "Cautionary Information" accordion. Our requirements will cover each of these variations with the `alertBoxHeading` dynamically populating with each time of cautionary flag.

**Comment by sonntag-adam** [comment]
Changes are in staging, screenshots are in story[8097](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8097)

**Comment by jonwehausen** [comment]
Thank you @sonntag-adam for your QA. Datalayer looks great!

### Google Tag Manager QA - All Testing Passed
Description of Interaction | Screenshot | Test Status
------------ | ------------- | -------------
Clicking on "view details below" | ![image](https://user-images.githubusercontent.com/48527022/79995420-33a21b00-8485-11ea-9192-b3c3decd64ca.png) | ✔️ **PASSED**
Clicking on warning alert box - "Schools has accreditation issue" | ![image](https://user-images.githubusercontent.com/48527022/79995245-ff2e5f00-8484-11ea-8423-340631279180.png) | ✔️ **PASSED**
Clicking on "visit the About this Tool Page" | ![image](https://user-images.githubusercontent.com/48527022/79996571-9ba53100-8486-11ea-890c-a9849ec66174.png) | ✔️ **PASSED**
Clicking on "student complaints" | ![image](https://user-images.githubusercontent.com/48527022/79996862-ed4dbb80-8486-11ea-8163-fd6c219716ba.png) | ✔️ **PASSED**
Clicking on "All campuses" | ![image](https://user-images.githubusercontent.com/48527022/79997128-369e0b00-8487-11ea-8f57-83301eb3d62d.png) | ✔️  **PASSED**

**Comment by jonwehausen** [comment]
cc: @sonntag-adam @amyknox @bsmartin-ep 

Tested, published, and ready for launch.
