### ISSUE TITLE
Business intake form for Profile - Ch33 EDU Direct Deposit Migration to CorpDB

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#80019]
## Your Details
1.  **Your Name**
​Travis Cahill

2.  **Business Line**
    (ex., claims, health, etc.)
​AE Profile on va.gov 

## Notification Details
1.  **Notification type**
    (email, text/SMS, or both)
​email

2.  **Please describe your use case.**
    (This is your chance to tell us an overview of your plans.)
​When users update their direct deposit information we send them a confirmation email. [This was originally worked out under this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19233). Today, we have two separate forms on va.gov/profile/direct-deposit for C&P or EDU benefits. Moving forward this will be consolidated to one form. 

With Ch33 benefits are being migrated to CorpDB and the subsequent consolidation to one form we want to send only one email that doesn't reference the specific benefit but simply says that direct deposit information was changed.
 
3.  **What actions can the user take based on the notification they receive?**
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​reduce the current email templates from 2 to 1 

4.  **What is the desired business outcome?**
    (ex., fewer skipped appointments, less call center volume, etc.)
the new email will no longer reference the benefit (C&P or EDU) and will be benefit agnostic. 
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    (ex., BVA hearing reminders are kicked off from Caseflow)
va notify ​

6.  **What will trigger the notification?**
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​maintain the same behavior 

7.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.
maintain the same behavior, copy should now be benefit agnostic 
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (ex., PO has seen the content but it is not approved)
​maintain the same behavior so this isn't changing - PO is Chante 

9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​maintain the same behavior 

10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
​maintain the same behavior 

11.  **What is the anticipated volume of notifications per day, week, month?**

12.  **When does this notification need to be in production?**
4/26/2024

**Comment by mjones-oddball** [comment]
Closing this per our chat in slack https://dsva.slack.com/archives/C06JV0KHZNF/p1712251571575279
