### ISSUE TITLE
CT-EYB: Update Estimated Benefits on click for non VETTEC institutions.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8002]
As a Comparison Tool user, I need to be aware of changes to the benefits estimator panel while I am modifying the form inputs so that I can be fully aware of what my benefits are after answering all relevant questions.

## Assumptions:
1. This work is completed behind a feature flag #7780.
2. The [interactive prototype](https://bahdigital.invisionapp.com/share/J5IADLE7CEF#/screens) is for UI/Layout reference but is overruled by supporting artifact 1.
3. The [OJT interactive prototype](https://bahdigital.invisionapp.com/share/74IADLI2G58#/screens) is for UI/Layout reference but is overruled by supporting artifact 2.
4. The question layout is not being changed as part of this story; that is covered in #8404 
5. Update e2e to test new functionality of calculator on non-vettec profile pages.

## Acceptance Criteria:
1. When changing the answer to ANY of the questions in the "Estimate Your Benefits" section, no change is made to the "Your estimated benefits" panel in the section.
2. The user has the ability to initiate a recalculation of their estimated benefits by clicking the "Calculate benefits" button.
    a. The recalculation updates the "Your estimated benefits" panel.
    b. Focus is set on the "Your estimated benefits" panel after recalculation. 
    c. The "Your estimated benefits" header does not get the yellow focus halo on focus.

## Supporting Artifacts:
1. Institution Design Document: [gibct-eyb-schools-v0.2-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4530778/gibct-eyb-schools-v0.2-20200424.pdf)
2. OJT Design Document: [gibct-eyb-OJT-v0.1-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4530777/gibct-eyb-OJT-v0.1-20200424.pdf)
3. [Institutions Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-schools-desktop-v02)
4. [OJT Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-employers-desktop-v01)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12451

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/325&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/381&group_by=cases:section_id&group_order=asc
https://dsvavsp.testrail.io/index.php?/runs/view/382&group_by=cases:section_id&group_order=asc
https://dsvavsp.testrail.io/index.php?/runs/view/383&group_by=cases:section_id&group_order=asc
