### ISSUE TITLE
Final Validation of Custom Events

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#80020]
### Description:
This task is to ensure the custom events being implemented in GA4 are effectively tested, and validated within the GA4 GUI. This task will largely be done in tandem with Jamie's progress on adding custom events within GTM and GA4.

---

### Tasks:

- Cross Reference GA4 Variables to UA Variables.
- Identify if there are there any differences in the calculations, if so provide calculations and source of calculations.
- Start with metrics report provided by Phil for base report to cross reference.

### Acceptance Criteria:

- [ ] Screenshots of Custom Events within GA4 have been documented.
- [ ] Confirm with Jamie.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA and @Blivaditis - can y'all work to build out this ticket?

**Comment by dorseypa1** [comment]
This should be split into two tickets.  Ticket 1 is to verify that all of the custom events shared by the teams are showing up in GA4.  Ticket 2 - ...

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 --what was Ticket 2 supposed to cover?

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA  -- To help better prioritize the work in this sprint -- I'm removing this from the current sprint, so we can spend additional time on the Domo QCs. As discussed earlier, moving forward, if there are questions on a ticket that has been assigned to you, that needs to be brought up during sprint planning.

Some of this validation work will happen as part of the review process for the custom event tickets we have in the current sprint, specifically, the following:

#79590 
#82275 
#79968
