### ISSUE TITLE
CT-EYB: Add expandable summary panel to Estimate Your Benefits section on mobile displays

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8003]
As a Comparison Tool user, I need to be aware of changes to the benefits estimator panel while I am modifying the form inputs on mobile devices so that I can be fully aware of what my benefits are after answering all relevant questions.

## Assumptions:
1. This work is completed behind a feature flag #7780.
2. The [mobile interactive prototype](https://bahdigital.invisionapp.com/share/3XIADLG2GJD#/screens) is for UI/Layout reference but is overruled by supporting artifact 1.
3. The [OJT mobile interactive prototype](https://bahdigital.invisionapp.com/share/Z9IADLWBV7U#/screens) is for UI/Layout reference but is overruled by supporting artifact 2.
4. Update e2e to test new functionality of calculator on non-vettec profile pages.

## Acceptance Criteria:
1. An expandable panel is displayed at the bottom of the screen under the following conditions:
    a. For small screens at horizontal resolutions of 480px and below for all non VETTEC institutions.
    b. Once the "Estimate your benefits" accordion header is at the top of the screen.
2. Just before the “Estimate your benefits” panel enters the lower edge of viewport (approx 8-16px):
    a. the bottom sheet slides down and off the screen. 
    b. Estimate your benefits panel and bottom sheet are not be visible on the viewport at the same time.
3. The panel title is: **Your estimated benefits**
4. For non-OJT institution types the following information is displayed in the collapsed view:
    a. **GI Bill pays to school:** [calculated amount]
    b. **Housing allowance:** [calculated amount]
    c. **Book Stipend:** [calculated amount]
5. For OJT institution types the following information is displayed in the collapsed view:
    a. **Housing allowance:** [calculated amount]
    b. **Book Stipend:** [calculated amount]
6. The user can expand the panel to see information as specified in AC 7 & 8.
7. For non-OJT institution types the following information is displayed in the expanded view:
    a. **GI Bill pays to school: [calculated amount]**
    b. Tuition and fees charged: [calculated amount]
    c. Your scholarships: [calculated amount] - Only displayed if amount > 0.
    d. **Out of pocket tuition: [calculated amount]**
    e. **Housing allowance: [calculated amount]**
    f. **Book Stipend: [calculated amount]**
    g. **Yellow Ribbon: [calculated amount]** - Only displayed yes is selected as answer to "Will you be a Yellow Ribbon recipient? Amount = Total per year amount.
    h. **Total paid to you: [calculated amount]**
8. For OJT institution types the following information is displayed in the expanded view:
    a. **Housing allowance: [calculated amount]**
    b. **Book Stipend: [calculated amount]**
    c. [horizontal rule]
    d. **Estimated benefits per month**
    e. **Housing Allowance**
    f. Months 1-6: [calculated amount]
    g. Months 7-12: [calculated amount]
    h. Months 13-18: [calculated amount]
    i. Months 19-24: [calculated amount]
9. The user can collapse the panel to see information as specified in AC 4 & 5.

## Supporting Artifacts:
1. Mobile Institution Design Document: [gibct-eyb-schools-mobile-v0.2-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4531051/gibct-eyb-schools-mobile-v0.2-20200424.pdf)
2. Mobile OJT Design Document: [gibct-eyb-employers-mobile-v0.1-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4531054/gibct-eyb-employers-mobile-v0.1-20200424.pdf)
3. [Mobile Institutions Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-schools-mobile-v02)
4. [Mobile OJT Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-employers-mobile-v01)

**Comment by elder-joseph** [comment]
PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/12492

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/81194842-1f811200-8f8b-11ea-9c05-be5618b79671.gif)
##
![ezgif com-video-to-gif copy](https://user-images.githubusercontent.com/48804582/81194917-30ca1e80-8f8b-11ea-8826-89ed9974d96c.gif)
##
![ezgif com-video-to-gif copy 2](https://user-images.githubusercontent.com/48804582/81194978-40496780-8f8b-11ea-91eb-a65762bc8c3f.gif)

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/81195662-23f9fa80-8f8c-11ea-8cdb-5d770f8c638c.gif)
##
![ezgif com-video-to-gif copy](https://user-images.githubusercontent.com/48804582/81195675-2a887200-8f8c-11ea-96d1-92c0e24623ad.gif)
##
![ezgif com-video-to-gif copy 2](https://user-images.githubusercontent.com/48804582/81195689-307e5300-8f8c-11ea-80f0-725eef77c1e6.gif)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/344&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@ccruzgra in staging.

**Comment by sonntag-adam** [comment]
UX feedback/changes will be in the new story. Testing passes QA.

**Comment by amyknox** [comment]
UX Review - now with priorities
[https://app.zenhub.com/files/133843125/23d5eec0-b22a-4591-aac0-c19a56bd2ef4/download](https://app.zenhub.com/files/133843125/23d5eec0-b22a-4591-aac0-c19a56bd2ef4/download)![ID - bold text in collapsed sheet.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/b106f7cb-1f75-4ca8-91b7-49a7e177a7e6)![ID - top-bottom padding for fields.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/99f9e3a3-0632-4515-8eee-fb60817a310a)![ID - OJT headings.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/ca90e211-a3b7-44ed-a0eb-d186686b491d)![ID - OJT expanded fields typography.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/f5a16213-d4f8-4875-8767-672689a2c4de)![ID - collapsed bottom sheet title.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/f0c0f356-c2e6-4c6a-925f-e7b4d737b62f)![ID - field label width.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/c70e3307-e58b-4d25-a139-0c58e3362e97)![ID - bottom sheet drop shadow.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/1d2982f0-dafd-4694-8a8c-e2e6f9a1d016)![ID - OJT housing allowance.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/f1664a62-5283-425c-b156-be1ab80c7eb0)
