### ISSUE TITLE
User Story - Create Dashboards

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#80035]
**User Story**
As a VA.gov team member, I would like to see dashboards that show how the Identity Team is fulfilling requests so that I can evaluate their performance as a platform-oriented team.

**Acceptance Criteria**
Dashboards will be created to track the following metrics
- [x] Tickets opened
- [x] Tickets closed
- [x] Tickets by current status
- [x] Ticket requests by team
- [x] Ticket requests by product
- [x] Customer satisfaction survey score

## Acceptance Criteria
- [x] Domo Dashboard is updated
- [x] Reviewed by UX Team
- [ ] Reviewed by PMs

**Comment by joshmatulonis** [comment]
Yesterday, I was told that GH support ticket data is being captured already! But no word on the dashboard being created.
