### ISSUE TITLE
CT-EYB: Remove 'gibctEstimateYourBenefits' Feature Flag Toggle

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8004]
As a developer, I need to remove the 'gibctEstimateYourBenefits' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of [TBD].
2. The new functionality is live in production with no need remaining need for the toggle.

## Acceptance Criteria
1. The feature flag 'gibctEstimateYourBenefits' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4735

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13894

**Comment by delli-gatti-michael** [comment]
Local testing complete for this story

**Comment by delli-gatti-michael** [comment]
Flag is gone at https://staging-api.va.gov/flipper/features

Closing this issue
