### ISSUE TITLE
[Design] My VA 508 office audit: Review headers on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80051]
## Background
As a result of our 508 office audit Matt suggested we review our strategy around headers on My VA. This ticket is to review the structure of our page as it pertains to headers and labels and the interaction with screen readers.

## Tasks
- [ ] Review headers on My VA to determine areas for improvement

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_

## Resources
- see #78974 for findings from audit

**Comment by ACParker89** [comment]
@mattmarino-adhoc do we still need this? looks like there was work done on it

**Comment by mattmarino-adhoc** [comment]
@ACParker89 I think we're good for this, based on Daniel's changes?
