### ISSUE TITLE
Sign in Service Client Auth/STS audit usage with locally signed certs

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#80056]
Both Sign in Service client auth private key jwt and service account should confirm that the public certs they use as part of authentication are not locally signed. These should be signed by an approved entity. If on dev/staging/prod, and the cert is locally signed, we should periodically send a message to data dog that we can monitor and ensure we have no certs that are locally signed in these stacks

**Comment by dickdavis** [comment]
Closed in favor of https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/82171
