### ISSUE TITLE
Create key pair intended for vets-api applications that use Sign in Service STS

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#80054]
vets-api needs a cert pair it can use to interact with Sign in Service STS functionality, and even though it will be other teams that are using it, we should probably create a single key pair for them to use

We need an extra `Settings` field called: `Settings.sign_in.sts_client.key_path`
On localhost this field can be `'spec/fixtures/sign_in/privatekey.pem'`
On dev/staging/prod this needs to be a key-pair created in venafi, ask Joe for help with creating the key in venafi

**Comment by bramleyjl** [comment]
If you're looking to update the `staging` environment ServiceAccountConfig for these vets-api applications, it's #3 with a `service_account_id` a162aaef5fb869aa4ea5a227728a753f.
