### ISSUE TITLE
Remove file uploads in sponsor information section

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#80066]
The sponsor file uploads are not needed, so need to remove them from the form flow before user testing takes place.

Acceptance criteria:
- [x] No file uploads exist in the sponsor information section
- [x] File upload overview screen shows no required/optional files in sponsor section

**Comment by michaelclement** [comment]
@baltes [Done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29013) - waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by baltes** [comment]
https://www.figma.com/file/UmAtr3ULQEInMXfNFwP0g0?type=design&node-id=1191-82655&mode=design#757706156
