### ISSUE TITLE
Update back button behavior on file upload pages in review flow

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#80071]
When a user has filled out the form and is on the file overview screen at the end + clicks on one of the remaining files to upload, they are taken back to the appropriate file upload screen in the form. Currently, the "continue" button will jump them forward to that review screen (rather than continuing to the directly proceeding form page). However, the back button will take the user to the directly preceding page, and that then exits the user out of the review/upload loop. Instead, we want the back button to ALSO take the user to the files overview screen.

Acceptance criteria
- [x] While in review flow, clicking "back" on a file upload screen takes user back to file overview screen

**Comment by michaelclement** [comment]
@baltes [Implemented in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29019) - just waiting on:
- [ ] Team PR approval
- [ ] Platform approval

**Comment by baltes** [comment]
https://www.figma.com/file/UmAtr3ULQEInMXfNFwP0g0?type=design&node-id=1191-58561&mode=design#757769197

**Comment by baltes** [comment]
Thanks @michaelclement. I'll review on staging once it's merged.

**Comment by michaelclement** [comment]
@baltes it's been merged and is live on staging. Thanks!

**Comment by baltes** [comment]
@jamiefiore or @syd-hoeper, could one of you take a look at this change and confirm whether it's working as expected?

**Comment by syd-hoeper** [comment]
@baltes I'm seeing the changes!
