### ISSUE TITLE
Implement Certify & Submit section

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#80080]
Implement the file certify and submit pages in the form. This includes the user signature block, the submit confirmation screen, and the confirmation screen that lists any missing required files.

Acceptance criteria:
- [x] User is able to put their name in the attestation block on review page
- [x] Upon confirmation, user sees confirmation page that matches [this Figma](https://www.figma.com/file/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?type=design&node-id=190-4317&mode=design&t=WDSeQ75pyhMBo1CY-0)
- [x] If user had any remaining required files, they see a list of required files and a message stating they must be submitted by mail or fax (per [this Figma](https://www.figma.com/file/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?type=design&node-id=190-4317&mode=design&t=WDSeQ75pyhMBo1CY-0))

**Comment by michaelclement** [comment]
Done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29305). Currently waiting on:
- [ ] Prerequisite PRs to merge
- [ ] Team approval
- [ ] Platform approval

**Comment by baltes** [comment]
@michaelclement I'm sure this one's fine but I'd like to verify that it's merged on staging before closing it. When I click submit at https://staging.va.gov/ivc-champva/10-7959C/review-and-submit the page appears to hang like this: <img width="686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--817a8725a7fab7ea7685c9c8d2da1030e1cb0bad/image.png" alt="image.png" />

**Comment by michaelclement** [comment]
Sorry for the delay - this was merged in recently and has finally made it to staging:
<img width="629" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1bc4331fc4b0f438faf07bd07ab31991738bee2/Screenshot%202024-04-23%20at%2015.23.24.png" alt="Screenshot 2024-04-23 at 15.23.24.png" />
