### ISSUE TITLE
SOCKS access for Nicholas Pappas

### ISSUE THREAD

**Issue by nfpappas-oddball** [department-of-veterans-affairs/va.gov-team#80089]
### Your Name

Nicholas Pappas

### Your Email

nick.pappas@oddball.io

### Your GitHub Handle

 nfpappas-oddball

### Your Role and Team

Devops Engineer

### Product Manager (PM) name and email

TBD

### Product Owner (PO) name and email

Erika Washburn, Erika.Washburn@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovOKu417VraripPFxVYAxtYD2mDsHNeZxmsd0GPJp+N9ZUTntrDsxbdPp5lIjrCAEm5O9xze35UzGqC3pZ2EX69XbicqSeiodQD12Jc0Ew2+d+I94vv3nmEJBu+e3Y/Z4+ZB6DUpbH9R8jqd+WgcXB1kRc9bcbTVwaFIGW5D41gBpWhkzQ7dedgYLyEUaQ+xxnM9NV6Jvv8y8v8m9IQsZmsD++SamA1diA9F8isEH0eMCJ3T4qkZgPIx/iEXjkoXYkPvia5MZ5x8N5FpXMcWhSr6Nub9bngIrfP36TjWc+q8jGstfg6WB9+6KjdsgVUKhQnypmvee0ge2r+Gjx6wkNQDBAQc33pWLxRge+bNVg7pgKEivuUUzRqp3YhXJICECXjjRkWnUALinrTsaHSqnr1sHQskZPnDTB87VIz3Y0TxT7ar+En47I8iMp2cMQ5x/hb89jGmcd/51z+p5TXVsNyMl/Gu2HYXb2W4IGKXelCSoz+AC+EwxGjYtjSlgdS8= npappas@oddball

### E-QIP Transmittal Confirmation

![proof_of_background_investigation](https://github.com/department-of-veterans-affairs/va.gov-team/assets/165396779/a475439b-11bb-4e83-9f85-505376b09560)
![background_proof_2](https://github.com/department-of-veterans-affairs/va.gov-team/assets/165396779/bafce48e-2557-4b31-859b-df7c07df2474)
![background_proof_3](https://github.com/department-of-veterans-affairs/va.gov-team/assets/165396779/8c96aada-05f0-4a9e-af8c-4f295c0ee4ec)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Pubkey is being rolled out.

**Comment by ph-One** [comment]
Access has been granted already. Closing.
