### ISSUE TITLE
S51 [Kickoff Sprint 🏈]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#80101]
# Sprint Goals

### **Priority 1: SC and NOD | Downstream failures ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293))**

**Define solutions for complex downstream errors**
- #79406 
- #79961

**Remediate historical failures**
- #80442 
- #80448 

### **Priority 2: DR | Downloadable Copy of Submission ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71358))**
- #76812 
- #80475 

### **Priority 3: Logging and Monitoring, Tech Debt, & Design Enhancements**
- #66191 
- #65556 
- #63147
- #65544 
- #65555
- #65550 
- #67648 
- #19696 
- #68869 
- #64710 
- #80433 
- #80632
- #77946
- #65747

## Discovery
**Prioritize opportunities and sequence the roadmap**
- #77320 
- #80470

---

## Team Capacity
**Target velocity:** 
- TBD

**Outages:**
- Derek 4/11-4/12
- DK 4/11-4/12
- Robin 4/11-4/12 (intermittently)
- Annie 4/15
- @shaunburdick 4/23

## Sprint Risks and Assumptions
- TBD

## Reference documentation

- [High-level Roadmap](https://docs.google.com/presentation/d/18rYnaYCjp2L2cm8HdYmXsg1_Pz7KI_X0vNRkmT5AqEk/edit#slide=id.g2804f61cf5f_0_0)
- [Tactical Roadmap (WIP)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702419283589/39d0d78778b8a35a2a02b48496d665d86ec3c5a2?sender=ud80be02ce240061eb0f35352)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)
- [Story Estimator](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167)
- [Velocity Planner ](https://docs.google.com/spreadsheets/d/1i7pVgf2XQxuRkIbuhHC5dckx2RlZt87n/edit#gid=880321098)

**Comment by saderagsdale** [comment]
Saving for later: 

> **Reduce reliance on asynchronous polling by improving transaction observability**
> - #74628
> - #74610

**Comment by eileen-coforma** [comment]
@saderagsdale added #80632 to the sprint because @Mottie thought it was "a quick fix that could be done during meetings"

**Comment by anniebtran** [comment]
@saderagsdale I replaced the HLR KPI reporting ticket with the alerting one because _that_ is what I actually worked on 😅 the HLR KPI tickets should line up more closely with Supplemental Claims now:
<img width="884" alt="Screenshot 2024-04-12 at 4 55 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/44e476d5-85ec-4bf6-9020-e42b2802adfb">
<img width="883" alt="Screenshot 2024-04-12 at 4 56 20 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/40fa5440-af22-4a7b-94ba-51daadf2de8e">

**Comment by Mottie** [comment]
@saderagsdale I added #65747 to the priority 3 list since #64710 was completed by Rocio
