### ISSUE TITLE
Adding Jake Bapple to DSVA Slack

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#80100]
# Description

Please add Jake Bapple as a full member of DSVA slack. He is a new member of the VA-CMS team.

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@michelle-dooley i need an email address please

**Comment by michelle-dooley** [comment]
@LEHigley His email is jbapple@metrostar.com

**Comment by michelle-dooley** [comment]
Hello @LEHigley just following up on this request for Jake Bapple. I see my other request #79604 that I submitted at the same time has been completed (I see Nick Pappas in DSVA but I still don't see Jake).

**Comment by michelle-dooley** [comment]
@LEHigley I'm sorry please hold on this.
