### ISSUE TITLE
Access for AJ Magdub

### ISSUE THREAD

**Issue by ajmagdub** [department-of-veterans-affairs/va.gov-team#8010]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Judy Mercado
- Please provide your name.
   > AJ Magdub
- Please Provide your email.
   > ahmed.magdub@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VAOS, IT Specialist - App Software Developer, US Department of Veterans Affairs
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3ZZ4jAMF7doTQnUJRm6t8S1DaD5GDp7VbUzb8eGdWBBPmoB/otKrdRWopvZqEMdUo0eiehHDEv8tfK6znHmeHTKhyMWz9tIA19mkicsiVJreElkPKHVdCge6WWyBMBv1GWqqudMaG7XmTi/Jxi9Pd45uIO4RgKMqtiyO5LWUicV9WaM7DefqRdE9RGKbsUzIm8uCxCVIV2NQtskBUjb2ZdXlrGiZ+v0+o9SaIWv8FQsyhwmkPWhMJ1ffYsrBQJJJ7UT8nk7n744pxcsDxLCh/a7FgXgmkzFQnAdqMtBL0hcO0cv9HlMLL0PASYvWHCYTr/Lb6XyZeFB1GuIkm+Uz01Nx6Vq8itnX4TnbQBeGF07Anqx5zvGkXwe5X0WGJFbVQ9Al4Bahn6LBVMJ5dEGbHcBej/HJmr5rMytY2OU6afYer/Q5nEtCRNabZpeSXJN8MWPZ9ybjI1Uapooo5mit0Ku6owq1fcTWjl5pUdlbF1GpZSklT6U6XaMryUbGjlKk= ajmagdub@AJs-MacBook-Pro.local

```

- [Grant AWS Console access?]
  > YES 
  >  Just joined the VAOS project as a Software Developer and need this access to use the developer tools such as Jenkins, Grafana and Sentry.

**Comment by ajmagdub** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ajmagdub** [comment]
closed by mistake

**Comment by jbritt1** [comment]
User: @ajmagdub 
COR: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
Shoot, meant to close this yesterday when I merged that PR. Thanks @lenaecb for catching this!

**Comment by jbritt1** [comment]
We should probably leave this open until he gets AWS access if that is still needed? Or are we closing because he does not actually require AWS console access at this time?

**Comment by saneshark** [comment]
@kreek do you think there is an urgent need for AWS access for AJ? I'm leaning towards no because between the two of us we've got enough redundancy there, but I might be missing something. I think it might be required to jump on a staging instance, but it shouldn't be required I dont think for review instances so might be ok.

**Comment by kreek** [comment]
I think for him to be a full member of the team he should have it. Mainly for cloudwatch log access. We're ramping up our % of users that see the app so triage work is only going to increase.

**Comment by lenaecb** [comment]
All - checking in, can we close this out now?

**Comment by jbritt1** [comment]
Seems he is awaiting approval for AWS access. That requires an e-QIP be successfully submitted/received and then the COR has to sign off on granting the access. This process usually requires the ticket to remain open a bit longer than when doing just the SOCKS access part.

**Comment by ajmagdub** [comment]
Hello @lenaecb @jbritt1 any progress on AWS console access? I can't SSH into a review instance and believe it's caused by this. Thanks

**Comment by jbritt1** [comment]
Not having AWS access should not be blocking SSH. What user are you attempting to access the box with? Have you copied [our SSH](https://github.com/department-of-veterans-affairs/devops/blob/master/ssh/config) config locally?

**Comment by ajmagdub** [comment]
Thanks Jeremy, @jbritt1 , I replaced my SSH config file with the one you linked to but I still cannot ssh into the review instance. Here's the error I'm getting:
dsva@<cut...>-68-193.us-gov-west-1.compute.amazonaws.com: Permission denied (publickey).
kex_exchange_identification: Connection closed by remote host

**Comment by jbritt1** [comment]
Oh, I think I know what is happening here. Hang tight, going to try something. Will update shortly.

**Comment by jbritt1** [comment]
Alright, can you give it another shot at this time please?

**Comment by jbritt1** [comment]
We were able to obtain access over some DM's / config updates. I _think_ we have this solved going forward, but have asked AJ to let me know if that is not the case. 

For the AWS access, the only updates I really get are from Jeff once he confirms that an e-QIP has been submitted successfully.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jbritt1** [comment]
First time login credentials for AWS provided.
