### ISSUE TITLE
[Consistency] User encounters content that doesn't match other content on VA.gov.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80102]
_This ticket was generated during the pilot process for the new VA.gov experience standards. Please tag `@platform-governance-team-members` on Slack if you need assistance interpreting this ticket._

## Product Information
**Team:** Benefits Non-Disability
**Product:** Burial Form 530
**Feature:** 21P-530 Parity Updates

## Findings details
**VA.gov Experience Standard - issue:** User encounters content that doesn't match other content on VA.gov.
**VA.gov Experience Standard - category:** Consistency
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

On the file upload pages, the button is labeled "Upload". Per our [design system guidance](https://design.va.gov/patterns/ask-users-for/files#content-considerations), the button should be labeled "Upload file". Also, once a file is added a "Add another" button appears. Per our guidance that button should be labeled "Upload another file".

## Recommended action

Change the buttons to "Upload file" and "Upload another file".

## References

- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** [Files](https://design.va.gov/patterns/ask-users-for/files)
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A
- **Accessibility Defect Severity:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by DLarson-Oddball** [comment]
@steele-lm After review, looks like this has been resolved with [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29042/files). Please advise if we need to have the governance team review, otherwise we should be all set here. Thanks!
