### ISSUE TITLE
Create a Research Plan for 686 Submission Usability Session

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8014]
## Goal
We want to put the feature we have worked on in front of real users to ensure that we have provided an improvement over the legacy digital experience.

## Considerations 
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)
- There are several workflows that need to be looked at as well as a few hypotheses that need to be validated.

## Task
- Document a research plan to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/discovery-research-plan.md)):
  - Research method (moderated user interviews)
  - Participants & Recruitment
  - Timeframe
  - Team Availability
  - Roles (include emails)
  - Seek review before implementation
  
## Acceptance Criteria
- [ ] Research Plan has been reviewed by [Lauren Alexanderson in Recruiting](https://dsva.slack.com/team/U772MC9BQ) ([email](mailto:lauren.alexanderson@va.gov)) and Shawna

**Comment by sporeboy** [comment]
Research plan format stubbed-out here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-staging-0520/686-usability-staging-research-plan.md

**Comment by sporeboy** [comment]
Initial draft done. Final timeline is pending completion of development/testing in staging. Need Nick's and Shawna's review.

The link to the plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-staging-0520/686-usability-staging-research-plan.md

**Comment by sporeboy** [comment]
Plan will not be submitted to Lauren... Pending review and revision as development continues.
