### ISSUE TITLE
[BE] 10-10EZ - Submission failure Notification: Implement API keys from VA Notify

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#80179]
## Benefit to the Veteran
By moving our Submission Failure email notifications to VA Notify, we will accomplish several things:
- Utilize the target state notification platform
- More control over the messaging sent to Veterans
- Ability to track messages sent and click-through rate for Veterans returning to the application for resubmission
These accomplishments will help us to communicate effectively with Veterans and monitor their behavior when a submission failure notification is sent.

## Background
As part of the move to VA Notify for our Submission failure notification emails, we need to implement the API keys provided by the VA Notify team for the Staging environment, so we can test submission failures to trigger the new notification process.

Do we need to implement [Delivery Service Callbacks status](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#delivery-status-callbacks)?

**Reference** 
- VA Notify Intake ticket #79992 
- Screenshot of original email sent to Veterans through GovDelivery
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/9381735b-0ff0-4908-804b-2fb97e51d14e)

## Tasks
- [x] Add Staging API (received from VA Notify to VA emails) to notification trigger code
     - Do not deploy to production until this is fully tested (#81976 )
- [x] Create/Update technical documentation (workflow diagram, etc) to include the new API(s) information

## Acceptance Criteria
- API keys provided by VA Notify for the Staging environment have been implemented

**Comment by emily-brown34** [comment]
@hdjustice  will pull out last tasks "Complete testing to trigger an email upon submission failure" into new ticket

**Comment by hdjustice** [comment]
Done #81976

**Comment by allanto-ah** [comment]
Environment: Staging 

Verified with Brandon that this is working as expected
