### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#80177]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

09-01-2023

### Date Range End

05-01-2024

### Product Name(s)

Pension benefits

### Product Description

I'm from the pension web form team. We are looking for any feedback related to pension benefits to guide improving the web form.
Categories: Navigation Issues, Application Submission Issue, Upload/Download Documents, Inaccurate or Missing Information/Status, Inability to Access Tool, Unable to Update Information, Feedback, General Information	

### Survey URL(s), key term(s), case category or type

https://www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez/introduction (this is a new landing page URL as 3/28)
https://www.va.gov/pension/application/527EZ (prior URL)
https://www.va.gov/pension/

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

buddhima.kurukulasuriya@va.gov, daniela.jones@va.gov, Allexe.lawflood@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, however this URL https://www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez/introduction was not available in Medallia. I used all the URL's that were available under pension. Let me know if you have any questions. Thank you!

**Comment by buddhima-coforma** [comment]
@newworld2616 the URL was changed recently to what you shared. The URL was https:www.va.gov/pension/application/527EZ

**Comment by newworld2616** [comment]
Hi, the URL was not available in the Medallia site. Let me know if you have any questions. Thank you!

**Comment by buddhima-coforma** [comment]
Hi Sarifa, to confirm, did you also happen to look for sub URLs too? ie: /527EZ/introduction etc?

**Comment by newworld2616** [comment]
Hey, Yes, I did. It is not appearing on the Medallia search. Thanks!

**Comment by buddhima-coforma** [comment]
Thank you!
