### ISSUE TITLE
Implement URL Changes for the 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8018]
## Goal
IA has given recommendations on what the 686 application process should have as far as what urls should be in place and where.  We need to ensure we have accounted for the urls and how they will be used on entry by the user.

## Considerations
- Mikki has provided us with [this recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md).
- We have also created a list of all the form's urls located [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-workflow-urls.md)
- The landing page will be `/view-change-dependents/` as [requested](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8012) with Public Websites

## Tasks
Per the changes outlined from IA, changes to the url(s) need to be implemented in staging:
- [ ] `/disability-benefits/new-686/` - to be updated to: 
`/view-change-dependents/add-remove-form-686c/`

## Acceptance Criteria
- [ ] A PR has been merged that commits these changes to staging.

**Comment by micahchiang** [comment]
pr - https://github.com/department-of-veterans-affairs/vets-website/pull/12251
