### ISSUE TITLE
Remove Karan Krishnani from DSVA Slack

### ISSUE THREAD

**Issue by ksk385** [department-of-veterans-affairs/va.gov-team#80184]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please remove me from DSVA Slack as I am offboarding.

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
confirming i am deactivating your thoughtworks email address?

**Comment by zinalpatel09** [comment]
@LEHigley yes that's right. However, I had karan self deactivate his account.  I no longer see him in the DVSA slack - can you confirm?
