### ISSUE TITLE
Personal health care contacts page not showing the updated time frame for contacting for assistance

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#80183]
**Test Info:**
Environment: Staging
Staging user #: **11** (has EC/NoK), **18** (no EC/NoK)

**Summary:**
This [ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/78486) updated the phone number to contact for assistance. When the user has no EC/NoK listed they see the updated phone number and time frame to contact that phone number. However, if the user does have EC/NoK listed, the phone number has been updated, but the time frame still shows "We're here 24/7" instead of the "We're here Monday through Friday...". Is this expected? See screenshots below. 

**Steps to reproduce:**
1. Login as the above staging user 11
2. Go to the user's name on the top right and go to "Profile" page
3. Click on the "Review your personal health care contacts" link
4. Expand the "Learn how to update your personal health care contact information" at the top

**User has EC/NoK:**
<img width="1339" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEE4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5628d329b47b54ae63a2e34997d961ed9bd039f/Screenshot%202024-04-05%20at%201.15.20%E2%80%AFPM.png" alt="Screenshot 2024-04-05 at 1.15.20 PM.png" />

**User does NOT have EC/NoK:**
<img width="1330" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEU4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e7be033a9fb71df116411d5b2f4a2ca4669355c/Screenshot%202024-04-05%20at%201.18.33%E2%80%AFPM.png" alt="Screenshot 2024-04-05 at 1.18.33 PM.png" />

**Comment by jonathanjnelson** [comment]
[Updated Figma link](https://www.figma.com/file/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?type=design&node-id=97%3A4589&mode=design&t=hK0vWNVUVAt7kNQr-1)


<img width="963" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae4cc1662616f4e022504f28d8ec64e283f5233e/Screenshot%202024-04-15%20at%202.07.37%E2%80%AFPM.png" alt="Screenshot 2024-04-15 at 2.07.37 PM.png" />
