### ISSUE TITLE
10-7959f-1 Staging | UAT edits - String Changes

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#80180]
1) **Change title for this form across all pages**
2) **Insert the form number**

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGc4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--857c0475fe70e9637118c29cd3432705d9f30004/Changes_10-7959f-1_Step1-2.png" alt="Changes_10-7959f-1_Step1-2.png" />

3) **Collect only the middle initial (instead name)**

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG84QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--667014776582d7de0bdd776e4d4736d3e5e0f8fe/Changes_10-7959f-1_Step1-4.png" alt="Changes_10-7959f-1_Step1-4.png" />

4) **Insert the "Need help" block**

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHM4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6156c9af65a610c5f29e91e121c972fd13bdbb45/Changes_10-7959f-1_Step1-5.png" alt="Changes_10-7959f-1_Step1-5.png" />

5) **Change "Physical address" to "Home address"**

<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDQ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1190b5efc05a3bca3b2579604b21261c56ac1e0d/Changes_10-7959f-1_Step3-2.png" alt="Changes_10-7959f-1_Step3-2.png" />

<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDg4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a3c27f8a60a2b28cee98bfc1532db4886b7de96/Changes_10-7959f-1_Step4-1.png" alt="Changes_10-7959f-1_Step4-1.png" />

<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUE4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41894c415ea0bde8352bd1cbcc90b8ffa021d954/Changes_10-7959f-1_Step4-2.png" alt="Changes_10-7959f-1_Step4-2.png" />

<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUk4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f9b85980867a448b8cccfbde392a41e4c6bea62/Changes_10-7959f-1_Step6-1.png" alt="Changes_10-7959f-1_Step6-1.png" />

<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU04QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b58cc0bf7819186e711566b5c1e8cdf1c621c597/Changes_10-7959f-1_Step6-2.png" alt="Changes_10-7959f-1_Step6-2.png" />

**Comment by reiting** [comment]
This is currently a PR in team review

**Comment by reiting** [comment]
This branch has been merged. Should be in staging within a few hours I think.

**Comment by marywang2** [comment]
If you'd provide the feature branch, I can check it out locally @reiting!

**Comment by marywang2** [comment]
Here are some edits for this ticket @reiting:
- All pages: please add header text and form number.
- Review page: Add section header text (next to edit buttons) at the top of each section

**Comment by marywang2** [comment]
I'll close this one for now - seeing all the changes on local. **Note**: seems like we're not able to change the section header text easily (if the text is the same, it does not show the headers). cc @brian-wilke
