### ISSUE TITLE
10-7959f-1 Staging | UAT edits - Interaction Changes

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#80181]
**1) Navigation element, breadcrumbs, need to be inserted**

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWM4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--005398a9536603133b881f0eb28074090c7469cd/Changes_10-7959f-1_Step1-1.png" alt="Changes_10-7959f-1_Step1-1.png" />

**2) Number of steps in the process (6) needs to reflect in steps and labels [likely the result of needing to split of addresses collected]** 
This is also applies to the review page and the editing within the address section of the review accordion.

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXc4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfce137233db0a6a41115560700911620bf4a3ee/Changes_10-7959f-1_Step1-3.png" alt="Changes_10-7959f-1_Step1-3.png" />

<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkE4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8c36ee2748a8bb46be0c04719a19fff4743e77d/Changes_10-7959f-1_Step6-1.png" alt="Changes_10-7959f-1_Step6-1.png" />

<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkU4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64916dd31ea1071e4db8deba7e1db84b3b1ea28a/Changes_10-7959f-1_Step6-2.png" alt="Changes_10-7959f-1_Step6-2.png" />

**3) The order of Mailing address, then Home address is the correct order**

<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkk4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d432bcedfbaa73831f07690d349daa36a23e3d6f/Changes_10-7959f-1_Step3-1.png" alt="Changes_10-7959f-1_Step3-1.png" />

**4) SSN screen: update text to read 'or' rather than 'of' and please lower case from "File" to "file" (in VA file number)**

<img width="900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEZNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c77fbed8b18d8b1a494aff96e8d9aa118dd99202/Screenshot%202024-04-10%20at%209.45.03%20AM.png" alt="Screenshot 2024-04-10 at 9.45.03 AM.png" />

**Comment by brian-wilke** [comment]
@marywang2 , These are the interaction changes I have captured on the staging site following the UAT. 

I did include the minor change to the component for addresses that support APO (bases) not in this version of figma, but in our prototype and the base library component.

**Comment by marywang2** [comment]
I moved the 'same as' functionality into a [separate ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/81326) for now so that we can focus on making the changes in this ticket and closing it out. @reiting @brian-wilke

**Comment by reiting** [comment]
The branch for this is 10-7959f-1-interaction-changes. I am also putting it up for team review.

**Comment by marywang2** [comment]
Thanks @reiting! Seeing the changes. Will let @brian-wilke also confirm.
