### ISSUE TITLE
BE | Profile | Ch33 Direct Deposit | Update Swagger Docs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#80198]
## Summary
Update swagger docs for new direct deposit endpoint.

## Tasks
- [ ] Add swagger docs for new direct deposit endpoint.

## Acceptance Criteria
- [ ] Review docs with FE developer.

**Comment by mtcA6** [comment]
@tpharrison is this rolling with 2 points?

**Comment by tpharrison** [comment]
Moving to backlog and until additional upstream changes that will affect our API contract are implemented.
