### ISSUE TITLE
Add Community Care to static Appointment page by 8/17

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8020]
## Ask / Need:
On the VA.gov static scheduling page, we need to provide Veterans with information/resources about Community Care and why they may/may not be eligible  ( https://www.va.gov/health-care/schedule-view-va-appointments/ )

We are required to provide this information/resources as part of the Mission Act/Community Care for the VA Online Scheduling service. 

## Acceptance Criteria
- [ ] Update the VA.gov scheduling static page with information about Community Care. We need to be sure to provide  link to the Mission Act -- https://missionact.va.gov/
- [ ] Under "Can I use this tool to schedule non-VA appointments?"
Update content to: 
Yes. You can use this tool to schedule VA and community care appointments.

## How does legacy VAOS tool currently handle this requirement?
- On legacy VAOS login page - the below copy and link are provided to Veteran (see screenshot below)
![Screen Shot 2020-05-04 at 9.43.56 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/0ac1e438-870b-4152-b6fe-e59eeadd2f78)

- If user clicked link, it would pop open following modal (additional copy and link to additional resources)
![Screen Shot 2020-05-04 at 9.44.10 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/49f603b9-0fe9-4531-a393-4b4141cac665)

**Comment by lenaecb** [comment]
[Ad Hoc LLC Mail - Community Care resources.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4478349/Ad.Hoc.LLC.Mail.-.Community.Care.resources.pdf)

**Comment by lenaecb** [comment]
@lalexanderson-dsva - Please review and provide feedback on where we want these resources to live. I have recommended they live on the static appointments page. Let me know if you feel otherwise. I'll add Peggy to this once we're confirmed out AC.

**Comment by lalexanderson-dsva** [comment]
Yes - this content, rewritten in our styles, could be added to the va.gov schedule & view page wherever our team recommends.

**Comment by lenaecb** [comment]
@lalexanderson-dsva - I am going to hold on to this until we're ready to re-enable Community Care again. Doesn't make sense for the public website team to work on this now just to hide it for us.

**Comment by lenaecb** [comment]
@peggygannon - as part of CC being re-enabled, we also need to add a reference to these resources to VAOS. At a minimum these should be on the static VA.gov scheduling page - https://www.va.gov/health-care/schedule-view-va-appointments/

Should we also consider adding a reference inside of VAOS too? @lalexanderson-dsva @rtwell

**Comment by peggygannon** [comment]
@lenaecb I'm taking a look at this ticket and want to  get clarification: 

Do we need to add reference to CC just on the static scheduling page or do we also need to add content about this in the new VAOS tool?

**Comment by lenaecb** [comment]
@peggygannon - @lalexanderson-dsva has confirmed that these resources should go on the static VA.gov scheduling page for now. We'll revisit in the future if these will be added into VAOS itself.

**Comment by peggygannon** [comment]
**6/17/20** 

Updated Community Care go live date is now July 20. We'll need to make these updates in drupal to the static VA.gov scheduling page - https://www.va.gov/health-care/schedule-view-va-appointments/ and  keep the page in a draft state, until CC go live date.

**Comment by peggygannon** [comment]
@lenaecb @lalexanderson-dsva Per discussion today with the Public Website content team, I'm reassigning this ticket to that team since this is an update to the static page.  

cc @DanielleThierryUSDSVA , please let me know if you want to sync after you've taken a look at the content updates needed.

**Comment by MickinSahni** [comment]
Removing from Public Websites sprint commitments

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. @peggygannon and I are chatting about this now. This is an update to a PW-owned health care page, so I'll work on it. It's due by 7/20. Can we add back to sprint 25?

**Comment by MickinSahni** [comment]
> Hi @MickinSahni. @peggygannon and I are chatting about this now. This is an update to a PW-owned health care page, so I'll work on it. It's due by 7/20. Can we add back to sprint 25?

Hey @DanielleThierryUSDSVA, let's see! 

Couple questions:
- who's going to do the work for this and have they groomed it?
- what estimate can be added to this ticket? 
- is this more important than the other content items in this sprint?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @MickinSahni!

- I'm going to handle, with help from Peggy as needed. 
- This looks pretty simple. I'd put it at maybe a 2.
- It technically needs to be live by 7/20...so could potentially put as early next sprint in terms of priority w/ other work. Want to maybe just put it in Ready column and I'll pick up this sprint if I can, or first thing next?

**Comment by MickinSahni** [comment]
> Thanks, @MickinSahni!
> 
>     * I'm going to handle, with help from Peggy as needed.
> 
>     * This looks pretty simple. I'd put it at maybe a 2.
> 
>     * It technically needs to be live by 7/20...so could potentially put as early next sprint in terms of priority w/ other work. I think it's doable in this sprint...but could just leave in Ready for now if that's better.

sweet, preemptively adding to next sprint

**Comment by lenaecb** [comment]
@MickinSahni @DanielleThierryUSDSVA - The release date for our Community Care feature and drive-time has been pushed back again. 

New estimated date for release if 8/7. So, we will not need to release this updated content till 8/6.

**Comment by lenaecb** [comment]
@MickinSahni @DanielleThierryUSDSVA - just got confirmation that CC will now be re-enabled on 8/14, so this static content will need to be re-enabled by 8/14. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @lenaecb!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. Just wanted to keep you updated on this issue. I've moved it into in progress because we're also updating this page for the Cerner SSO work and the updates related to this issue also need to be applied there. Thanks!

**Comment by lenaecb** [comment]
@DanielleThierryUSDSVA - slight change in date, but feeling pretty confident this will stay after my meeting with the Community Care team yesterday. New date for re-enable of Community Care in VAOS is 8/17

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lenaecb. Just checking in on this. 

We've updated the content on this page to include community care as part of the Cerner SSO work. I'm OOO M-W, but will be publishing the community care updates on 8/17 (unless something has changed and you need me to hold off).

One question for you: In previous MISSION Act related work that I handled a while back, we linked over to the community care site rather than the MISSION Act site since the bulk of the info is there. I think this should work fine for this update as well (see below), but please let me know if there are any concerns. Thanks!

**Can I use this tool to schedule community (non-VA) appointments?**
Yes. If you’re eligible to receive care from a community provider outside of VA, you can use this tool to submit appointment requests. You must receive prior approval from us before getting care from a community provider.
[Learn more about community care](va.gov/COMMUNITYCARE/programs/veterans/index.asp)
[Find a community provider in the VA network](va.gov/find-locations)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @MickinSahni I moved this to sprint 28 since it will go live within next sprint. Thanks!

**Comment by lenaecb** [comment]
Great, thanks @DanielleThierryUSDSVA! Sounds good.

CC: @peggygannon - I verified with the Community Care team, and they also confirmed we should use this link (https://www.va.gov/COMMUNITYCARE/programs/veterans/General_Care.asp) that Danielle recommended.

**Comment by peggygannon** [comment]
@lenaecb OK, sounds good. thank you for confirming!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lenaecb. Just checking in. Sounds like this is being pushed back to 8/28, correct?

**Comment by lenaecb** [comment]
@DanielleThierryUSDSVA @MickinSahni - can you confirm when this will be live on prod? We are turning CC back on tomorrow morning (8/17) at 8am EST.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Most of these updates are being handled in the react widget that now houses this content. But I had to make updates to the intro in Drupal. Could you check the intro on this page for any errors and omissions and then set to publish ahead of today's deploy? Thank you!!
http://preview-prod.vfs.va.gov/preview?nodeId=37

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA The intro changes are all good. I've set this page to publish.
