### ISSUE TITLE
Add "Watchtower" section to "Monitor Applications and Infrastructure with Datadog"

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#80208]
### Description

As part of the code yellow effort, we need to update the monitoring documentation to add a section explaining required monitors and watchtower integration for VA.gov applications.

##### Required monitors 

All VA.gov apps must have the following core monitors with appropriate alerts configured:

* Error rate
* Anomalies
* Queue exhaustion (If the app does background processing)

Each core monitor should have the "watchtower" tag, and be tagged with the priority corresponding to its app’s tier.

##### App tier guidance

| Daily transactions/page views |	Learn about |	View benefits |	Use/manage benefits |	Apply for benefits |
| --------------------------------- | --------------- | ----------------- | ----------------------- | --------------------- |
| **10,000+** |	**tier 1** |	**tier 1** |	**tier 1**	| **tier 1** |
| **1,000+** |	tier 2 |	tier 2 |	**tier 1** |	**tier 1** |
| **100+** |	tier 3 |	tier 3 |	tier 2 |	**tier 1** |
| **0+** |	tier 3 |	tier 3 |	tier 2 |	tier 2 |

Follow the above chart to determine your app’s tier. Your app’s tier classification should be reviewed periodically and when functionality or usage changes significantly.

###### Category examples

**Learn about:** Informational, non-interactive content. Example: the [VA.gov](http://va.gov/) homepage
**View Benefits:** Personalized health or benefit information where no information is submitted. Examples: Letter downloads, MHV medical records
**Use/manage benefits:** Apps that enable updating or using information: Examples: Direct deposit update, MHV Prescriptions
**Apply for benefits:** Apps that enable applying for healthcare or benefits: Examples: 526, 1010ez

### Relevant URLs

- top level: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO

**Comment by jknipes** [comment]
Example: Hi @acrollet , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by acrollet** [comment]
Thanks @jknipes !

**Comment by jknipes** [comment]
work completed on ticket [80274](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80274)
