### ISSUE TITLE
Analytics Reporting Request for OMB

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8021]
# Metrics Reporting Request

## Description
Who is this request for?

Point of Contact: Cameren M
Report Presented to: OMB, monthly
    

## Timeframe for Analytics Requested
Year over Year
Ex: May 2020 metrics would be presented as Mar 2018-April 2019, Mar 2019-April 2020

## Analytics to Track Down

(Already Included)

- Total users
- Total Burials Submission
- Unique Log-ins (DSLogon, ID.me, and MHV)
- Total Claims Status Views
- Customer Satisfaction
- System Status

Add

- HCA Submissions
- 526 Claim Submissions

Edit

- Add annotations for unique logins. Segment by login type (MHV, eBenefits, DSLogin), potentially as a stacked column chart.

**Additional Metrics**
Insights to determine potential additional metrics.
Insights to determine how we might be able to compare legacy vs. modernized 

## Which Product Questions are you trying to answer?
How might we show progress of work done on VA.gov? How might we show effect on users?

Metrics due by first Monday of the month.

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Still need to add 526 submission. Moving to "Ready"

**Comment by amycesal** [comment]
@jonwehausen Can you add **526 submissions** to the **Monthly- OMB dashboard** https://va-gov.domo.com/page/1475431113

And see if you can segment out login types? Is that possible?

**Comment by jonwehausen** [comment]
@amycesal Added disability 526 submissions to bottom of OMB dashboard. 

Right now this is filtered on submissions successful, but can be quickly changed to all submissions or failed submissions where needed. 
![image](https://user-images.githubusercontent.com/48527022/82943277-597c7d00-9f67-11ea-8d0b-61797b8903dd.png)

fyi We don't have data for 2018 for 526

**Comment by amycesal** [comment]
@jonwehausen is there a reason WHY we don't have 2018 data? It would be good to add some sort of explanation in the dashboard

**Comment by jonwehausen** [comment]
Hey @amycesal , great question. Give me some time to dig into more as to why we would not have.
