### ISSUE TITLE
Adding Lisa Chung to DSVA Slack

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#80214]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Hello, Lisa Chung (Nava) has joined the ABD Toxic Exposure Team (VRO) as a full stack engineer and will need full member access.

- Please add lisachung@navapbc.com as a full member.

**Comment by BerniXiongA6** [comment]
cc: @lisac

**Comment by BerniXiongA6** [comment]
Sorry @LEHigley -- that was an error. Lisa should be a full member.

**Comment by lisac** [comment]
hi everyone, bumping up this request. I'm hoping to help out with VRO on-call duties next week, although a prerequisite would be access to the DSVA slack. Thanks for you consideration, and please let me know what other info is needed.

**Comment by EWashb** [comment]
I have added the user.
