### ISSUE TITLE
Add ngrok to suite of testing tools for local development

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-team#80225]
### Description

The Public Websites team uses **ngrok** for local development when traditional methods are down (CI issues, SOCKS blockers, etc.) We wrote up some documentation on how to use **ngrok** when running `vets-website` and `content-build` locally. If you feel it might be helpful for other teams, we could include this in the list of testing tools for local development.

### Relevant URLs

Our docs for `ngrok`: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17306#issuecomment-2043002447

Various `ngrok` documentation links are included in this write-up.

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS: Sitewide - Public Websites

**Comment by jknipes** [comment]
Example: Hi @randimays , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Per this [Slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1717769350555309), this issue no longer relevant and we are closing this ticket
