### ISSUE TITLE
Test E2E with VeText Team

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80242]

**Comment by loripusey** [comment]
@loripusey Can this happen next sprint?

**Comment by brianseek** [comment]
first round of testing was successful. Text `TRAVEL` to vetext -> CHIP -> LoROTA -> vets-website -> vets-api was a success. Vets-api to btsss had some errors.

 - Forward proxy seems to be broke in stage
 - with forward proxy off there was still an issue communicating with btsss
 
see [slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1721844887520039)

**Comment by brianseek** [comment]
closing this ticket since testing was completed, will do another round of testing after vets-api changes are complete
