### ISSUE TITLE
Analytics Implementation or QA Support for [Lighthouse Program - Google Tag Manager]

### ISSUE THREAD

**Issue by dami-va** [department-of-veterans-affairs/va.gov-team#80250]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    - Lighthouse Program

- **Poduct Name**

    - [Insert product name(s)]
    - Lighthouse properties on GA4
      
- **When is the launch date?**
    - [Insert launch date]
    - Already launched

- **Provide the link(s) for Product/Page urls**
  
    - [Insert link(s)]
    - Can we have a meeting to find out if GTM has been implemented for Lighthouse properties? Thanks.

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- playing a bit of catch up here. Do we still need to connect with the Lighthouse Team on this?...or can this be closed?

**Comment by johnny-jesensky-adhoc** [comment]
Closing this ticket.
