### ISSUE TITLE
[Research] Monitor Unmoderated Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80279]
## Description
We need to Monitor the research study for the Discovery - Multiple Selection of Appointments.

## Tasks
- [ ] Coordinate with Perigean to send out the study
- [ ] Monitor the results

**Comment by benbrasso-agile6** [comment]
@cgednalske I'll jump back into this and see if we can get this moving again

**Comment by benbrasso-agile6** [comment]
lol, what the heck, I went to copy/paste that appendix email.... nice

**Comment by benbrasso-agile6** [comment]
@cgednalske it looks like you made all the updates. TY!

Are the cohorts all set? I know Kristen and Cara had some feedback about them.

Saw the screener, looked good. 

Last thing to do would be to update the Perigean dates and reping Shane on https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/532#issuecomment-2059597743

**Comment by benbrasso-agile6** [comment]
Updated Shane's ticket with links to screener q's and email

**Comment by cgednalske** [comment]
@benbrasso-agile6 Just saw these comments - it's fun following your train of thought 😄 

I think you're all caught up, so now want to make sure I am. Yes, added screener questions and email! Had not gotten to Kristen and Cara's comments for cohorts yet, but sounds like you are picking that back up?

**Comment by benbrasso-agile6** [comment]
lol, I was catching up

**Comment by benbrasso-agile6** [comment]
Ummm, I would prefer you. to pick up the final step about the cohorts, because 1) I was thinking you touched base with Cara about them, and 2) I had the same question that Kristen asked about the diff between cohorts A and B

**Comment by benbrasso-agile6** [comment]
Moving to closed, as this is about to be completed
