### ISSUE TITLE
Update copy and behavior of the upload supporting docs page

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#80276]
Followup ticket for #79323: Supporting documents form flow framework and design.

**Acceptance Criteria:**
- Update designs with new clarifying copy and behavior
- Review/gain approval from CAIA, VA crew, etc.
- Make any adjustments to design per feedback
- Create implementation ticket for engineers

**Comment by aplatt-coforma** [comment]
@gmaciolek - here's the ticket to update the upload supporting docs page. Please edit as needed.
cc @matt4su

**Comment by aplatt-coforma** [comment]
@djones2113 - this ticket can go through the new HCD approach to see if we should work on this request.
cc @matt4su @Allexelaw

**Comment by djones2113** [comment]
FYI this ticket has been added to the holistic [527 usability improvements Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425030709/9bfbf3bb5b3a4375e4ab7806052589f11ca0bef9?sender=u6633b44b9a2da5d288ed7845) to be incorporated into the prioritized recs as relevant

**Comment by mtri** [comment]
This seems like its covered off by work on  [Clarify medical evidence request #79210](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79210) and [Clarify dependents assets questions (H) #79212](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79212). Closing as directed.
