### ISSUE TITLE
Add "Watchtower" section to "Monitor Applications and Infrastructure with Datadog" (Footer Ticket 80208)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80274]
### Description

As part of the code yellow effort, we need to update the monitoring documentation to add a section explaining required monitors and watchtower integration for VA.gov applications.

##### Required monitors 

All VA.gov apps must have the following core monitors with appropriate alerts configured:

* Error rate
* Anomalies
* Queue exhaustion (If the app does background processing)

Each core monitor should have the "watchtower" tag, and be tagged with the priority corresponding to its app’s tier.

##### App tier guidance

| Daily transactions/page views |	Learn about |	View benefits |	Use/manage benefits |	Apply for benefits |
| --------------------------------- | --------------- | ----------------- | ----------------------- | --------------------- |
| **10,000+** |	**tier 1** |	**tier 1** |	**tier 1**	| **tier 1** |
| **1,000+** |	tier 2 |	tier 2 |	**tier 1** |	**tier 1** |
| **100+** |	tier 3 |	tier 3 |	tier 2 |	**tier 1** |
| **0+** |	tier 3 |	tier 3 |	tier 2 |	tier 2 |

Follow the above chart to determine your app’s tier. Your app’s tier classification should be reviewed periodically and when functionality or usage changes significantly.

###### Category examples

**Learn about:** Informational, non-interactive content. Example: the [VA.gov](http://va.gov/) homepage
**View Benefits:** Personalized health or benefit information where no information is submitted. Examples: Letter downloads, MHV medical records
**Use/manage benefits:** Apps that enable updating or using information: Examples: Direct deposit update, MHV Prescriptions
**Apply for benefits:** Apps that enable applying for healthcare or benefits: Examples: 526, 1010ez

### Relevant URLs

- top level: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/80274?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
NOTE: This is not putting a section in an existing page. This is creating an ENTIRELY NEW PAGE and making it a child page of "Monitor Applications and Infrastructure with Datadog"

**Comment by BSmolensky** [comment]
My plan of action:

- [ ] Copy and Paste Provided Content into Draft Doc on Confluence
- [ ] Do a Formatting Edit
- [ ] Do a Style Edit
- [ ] Do a Copy Edit
- [ ] Flag any issues
- [ ] Contact SME and share Draft doc
- [ ] Work with SME to finalize
- [ ] Move to Home in IA
- [ ] Deploy

**Comment by BSmolensky** [comment]
Page is now live on the PW: https://depo-platform-documentation.scrollhelp.site/developer-docs/watchtower-integration

This ticket is ready to close.

**Comment by jknipes** [comment]
Work is finished, moving to _done_
