### ISSUE TITLE
AWS access for Nicholas Pappas

### ISSUE THREAD

**Issue by nfpappas-oddball** [department-of-veterans-affairs/va.gov-team#80287]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Nicholas Pappas

### Your Email

nick.pappas@oddball.io

### Team, Role, and Company of the target individual

AP team, devops engineer, oddball

### Product Manager (PM) name and email

Michelle Dooley

### Product Owner (PO) name and email

TBD

### Desired AWS Access

Admin access would be nice but at minimum:
EKS
IAM
route53
ec2
RDS
ECR
S3

### Access Expiration

January 1st 2025

### E-QIP Transmittal Confirmation

![background_proof_2](https://github.com/department-of-veterans-affairs/va.gov-team/assets/165396779/b7c8da62-048f-4658-96b2-bb7d950efa50)
![background_proof_3](https://github.com/department-of-veterans-affairs/va.gov-team/assets/165396779/855c867f-807e-4ce2-bc3d-dd9e96f3afd2)
![proof_of_background_investigation](https://github.com/department-of-veterans-affairs/va.gov-team/assets/165396779/eb8c155d-493b-4f7c-945c-156e72f3dbfc)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
AWS Access has been granted, and @nfpappas-oddball has been provided his credentials and login details
