### ISSUE TITLE
[FE/UX] 10-10EZR TERA: Update Static Page Content for Staggered Rollout--Must go out with Deploy on Tue 4/9

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#80291]
As a Veteran, I would like the content on the EZR Intro page to tell me what I can and cannot do online so that I know that filling out the online EZR will allow me to achieve what I came here to accomplish

- [x] Update Static Page content in Existing Widget--changes outlined [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65056#issuecomment-2043646862) (in the comments I believe)
- [x] From Aliyah: If it's inside of the same widget, the other content (2 versions) that's already there (under "How do I update my information") should remain.
- [x] Update Figma file to reflect content changes
- [x] Show to Aliyah and Megan Zehdner (can be in screenshot or Zoom Demo)
- [x] **Success: Intro page widget content and Figma are updated to reflect Aliyah's requested changes and deployed on 4/9/24**

**Comment by aliyahblackmore** [comment]
Thanks @alexseelig 

Cross posting the  word document from my ticket here.
[April 10 incremental launch 2 versions of content_4.8.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14911041/April.10.incremental.launch.2.versions.of.content_4.8.docx)


And sharing this note here. 

_Engineers still need to confirm if they will use a new widget or if they'll add this content to the ezr-submission-options widget or if there should be a new widget.  If it's inside of the same widget, the other content (2 versions) that's already there (under "How do I update my information") should remain._

**Comment by JoshingYou1** [comment]
I was able to merge the changes, but it was not in time for the 3:00pm EST daily deploy, so I didn't check the last A/C.
