### ISSUE TITLE
Looking for additional DataDog access to view and edit vagov.ddog-gov

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#80304]
Description 
Access Request
A few months ago I received access to DataDog. However, I need additional DataDog access to view and edit vagov.ddog-gov

Please grant me view/edit access so I can help support our team with this dashboard. 
Name: Devi Hill
VA email address: [devi.hill@va.gov](mailto:devi.hill@va.gov)
Team: CHAMPVA IVC FORMs

Definition of Done
Looking for access to the proper DD URL

**Comment by alyssagallion** [comment]
@lindsay-insco Updates here?

**Comment by dhill802** [comment]
Hello - Just following up to see if there is any update? Thanks.

**Comment by lindsay-insco** [comment]
Hello @dhill802 I apologize for the delay this slipped past my radar. 

While you may have access to DataDog if you do not have access to view the vague.ddog-gov instance you need to request that through yourit.va.gov - we cannot grant access to view dashboards though we can elevate your read access to write once you see it. 

You can follow the steps (here)[https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog#GetAccesstoDatadog-Step2:GainAccesstoDatadog] for how to fill out the form - you can let the team know that you have access to DataDog but you need the ability to view the vague.ddog-gov instance and they should be able to grant you that access.

Once you can see that dashboard, please do not hesitate to reach out in the #vfs-platform-support channel on Slack in order for us to escalate your access to write! We can knock out that part very quickly.

**Comment by dhill802** [comment]
Thanks for the direction
