### ISSUE TITLE
Burial | Update Monitoring and Logging

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80308]
## Issue Description
_Once form updates have been made, review and update the logging and monitoring for the Burial Form._

---
## Tasks
- [ ] Review existing logging and monitoring to identify updates needed
- [ ] Make updates

## Acceptance Criteria
- [ ] Logging and monitoring for Burial Form is up to date
---

**Comment by sortizsh** [comment]
no longer needed
