### ISSUE TITLE
SOCKS access for [Anthony Flowers]

### ISSUE THREAD

**Issue by AnthonyWFlowers** [department-of-veterans-affairs/va.gov-team#80317]
### Your Name

Anthony Flowers

### Your Email

anthony.flowers@oddball.io

### Your GitHub Handle

anthonywflowers

### Your Role and Team

Technical Support -Platform Team

### Product Manager (PM) name and email

Alyssa Gallion | alyssa.gallion@oddball.io

### Product Owner (PO) name and email

Erika Washburn | Erika.Washburn@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK4k4pY2SYBiuMCKgbNYOOmTkIJxvGO75yBi8RDc/JPq anthonyflowers@FlowersMac.local

### E-QIP Transmittal Confirmation

<img width="1108" alt="Screenshot 2024-04-09 at 11 00 51 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/161509257/f16cc40c-07a8-46f3-9310-08cfe69ed0a7">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
PR merged ✅ https://github.com/department-of-veterans-affairs/devops/pull/14202
