### ISSUE TITLE
[FE] COVID-19: Implement analytics tag for My VA health chat alert

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8033]
## Background

We need analytics on the "Learn more about VA health chat" button on the VA health chat alert box so we can detect how many people click the button.

<img width="852" alt="Screen Shot 2020-04-01 at 12 04 26 PM" src="https://user-images.githubusercontent.com/34068740/78160999-cb769100-7412-11ea-9008-978c3c9bba93.png">

Analytics ticket  is #7478. Below are the data layer requirements outlined in that ticket:

Interaction | Screenshot | Datalayer requirements
--- | --- | --- 
Click the *Learn more about VA health chat* button | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/584f39fb-5362-46af-9f68-2101b825f378) | ```dataLayer.push({ ``` <br> ```'event': 'dashboard-navigation',``` <br> ```'dashboard-action': 'view-link',``` <br>  ```'dashboard-product': 'learn-more-chat'``` <br> ```});```

## Tasks

- [ ] Implement FE tag for analytics tracking for the "Learn more about VA health chat" button

## Acceptance criteria

- [ ] Tag is implemented and analytics team is able to verify it's working

**Comment by Samara-Strauss** [comment]
@mshea0606 let's talk about this ticket in grooming today.

**Comment by mshea0606** [comment]
@Samara-Strauss sounds good

**Comment by Samara-Strauss** [comment]
cc/ @bsmartin-ep for awareness.

**Comment by erikphansen** [comment]
Yes the work for this was merged. Maybe we should check with analytics to see if we're seeing anything in GA and then close it?

**Comment by Samara-Strauss** [comment]
Great! I will follow up with them.

**Comment by mshea0606** [comment]
@Samara-Strauss @erikphansen Just heard back from Joanne. They have everything they need and its good to go.
