### ISSUE TITLE
Callback API: Database migration

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#80349]
As a user of the vets website and vets-api, submitting IVC CHAMPA forms in PEGA S3 bucket doesn't tell us whether they were imported into PEGA RPA system. To keep track of forms submission, I would like to have a database table that tracks each submission and the PEGA statuses.

Implementation Plan (Psuedo code)
Create a DB table like ivc_forms with columns [UUID (auto-generated), form_UUID, file_name, email, status, created_at, updated_at]
Ex: [AUTO UUID, a0a9682e-04f2-44ad-85ca-99e2d9ff6a21, a0a9682e-04f2-44ad-85ca-99e2d9ff6a21_vha_10_10d.pdf, veteran@aol.com, "pending", AUTO, AUTO]

Acceptance Criteria
- New DB is accessible and has the ability to CRUD data.

**Comment by balexandr** [comment]
Estimate updated from 5 -> 8 to make changes we discussed when I got back from vacation.

**Comment by balexandr** [comment]
Ticket has been approved by our team and is ready for review with vets-api team
https://github.com/department-of-veterans-affairs/vets-api/pull/16367

**Comment by balexandr** [comment]
This has been approved by platform and can be closed
