### ISSUE TITLE
10-7959f-1: add authentication to form (back end)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#80367]
As a user who is signed in and viewing the 10-7959f-1 form online, I want to see my information pulled from my VA.gov profile so that I don't have to fill out all the fields in the form.

- Identify all fields that can be pre-filled in the form by crossreferencing the available data in the back end
- Add Prefill support for all pre-fillable fields to the front end by creating a prefill-transformer
- Add all required Prefill data to be sent to the front end in the back end

Acceptance Criteria:
- Given the user is signed in and viewing the 10-7959f-1 form online
- When the user navigates to the form
- Then the user's information should be pulled from their VA.gov profile and pre-filled in the form
- And the user should be able to save their progress and return to the form later

Dev Ref: https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill#VAFormsLibrary-HowtoworkwithPre-Fill-Vets-APIWork

**Comment by marywang2** [comment]
Related to this [front end ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/77738).

**Comment by marywang2** [comment]
@balexandr I am seeing save in progress, which is great! But I'm not seeing my info pre-filled when logged in (on staging).

**Comment by balexandr** [comment]
@marywang2 It's not on any repo yet it's still up for review and FE still has to do work to figure it out and apparently we can't actually test it until its on staging so don't worry about testing right now

**Comment by balexandr** [comment]
Approved by team, awaiting platform review.

**Comment by marywang2** [comment]
@balexandr would you be able to check with platform if they can review before end of day today? Thanks!

**Comment by balexandr** [comment]
@marywang2 https://github.com/department-of-veterans-affairs/vets-api/pull/16446 was just merged into master. @reiting or @michaelclement will have to test when everything is on staging.

**Comment by RachalCassity** [comment]
@marywang2 There were comments in the previous PR that were not addressed and ignored. Spec tests were not added due to conflicting documentation. Can the documentation please be updated to prevent confusion in the future?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/32692924/f49638ce-22a7-49c3-a3d2-a6d07ada52f9)

**Comment by balexandr** [comment]
@RachalCassity Our team does not have the approval to update the documentation. Looks like the last person to make changes to it was Pat Siebenlist.

It's worth noting that a spec was added, just not able to test locally.

**Comment by balexandr** [comment]
This has been merged

**Comment by marywang2** [comment]
@reiting FYI!
