### ISSUE TITLE
[Tabs] Finalize spec for getting new tabs into VADS

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#80362]
## Background Context

This is a ticket to track the work in this [Experimental Design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2346). @davidakennedy and @skylerschain have a couple things to work out in order to get our V2 tab component added to VADS, which would be awesome for our team!

## Design
<img width="1017" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93542c6b8ea4bc1a2d9e8fa9c5b1759000a42efc/Screenshot%202024-04-09%20at%202.41.17%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 2.41.17 PM.png" />

## Open questions
- See ticket abovec

## Tasks
- [ ] _Resolve open questions_
- [ ] _Schedule another meeting with DSC to get this reviewed and hopefully formally approved_

**Comment by davidakennedy** [comment]
@skylerschain and I met on 6/28 to go over the work I completed on this ticket. I've added a [link to the Figma file and thoughts in the design system ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2346#issuecomment-2200772543). We can close this ticket as complete. If the design system has feedback, we can open a new ticket.
