### ISSUE TITLE
Add Clinic phone number with extension on the Appointment Details page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#80375]
## Description
We will display the Clinic phone number with the extension on the appointment details page if the data is available in the response. Adding this data will be a big help to the Veteran when they need a number to call for their appointment. 

---

## Acceptance Criteria

- [ ]  Given the user is on the Appointments landing page
        When the user clicks on `Details` for a booked appointment 
        Then the user will see the Clinic phone number with extension if the data is available in the appointment response 
        And page design matches the [design spec](https://www.figma.com/file/7fnXSBQ6FZ8HMDaPJXUMn7/Add-clinic-phone-%23-to-appt.-details-%7C-Appointments-FE?type=design&node-id=1-51&mode=design&t=LQhNWwWcERzhBMgb-0)

- [ ] Given the user is on the Appointments landing page
       When the user clicks on `Details` for a booked appointment 
       Then the user will not see the Clinic phone number label if the data is unavailable in the appointment response and will display the Main number. 
       And page design matches the [design spec](https://www.figma.com/file/7fnXSBQ6FZ8HMDaPJXUMn7/Add-clinic-phone-%23-to-appt.-details-%7C-Appointments-FE?type=design&node-id=1-51&mode=design&t=LQhNWwWcERzhBMgb-0)

### Design Assets
[Figma file](https://www.figma.com/file/7fnXSBQ6FZ8HMDaPJXUMn7/Add-clinic-phone-%23-to-appt.-details-%7C-Appointments-FE?type=design&node-id=1-51&mode=design&t=LQhNWwWcERzhBMgb-0)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Figma file updated
- [ ] Copy doc updated

---

**Comment by ldelacosta** [comment]
SPL completed the work[VAOSR ticket #7546](https://issues.mobilehealth.va.gov/browse/VAOSR-7546). FE work can begin.

**Comment by outerpress** [comment]
Adding this piece of logic, per conversation with Jennie and this [Slack thread](https://dsva.slack.com/archives/C0331ERT9C6/p1716924841399939):

- If the facility main number is not available, we'll display the Main VA phone number, with the label "Phone:"
- For the main VA phone number, use 800-698-2411

@Cieramaddox @ldelacosta @JRRoof this adds logic to cover the case where neither clinic phone nor facility phone aren't available.

**Comment by Bren22va** [comment]
Note: auto-release once pushed to staging

**Comment by jenniemc** [comment]
@ldelacosta this ticket is ready for validation.

**Comment by ldelacosta** [comment]
Validated the work in staging. No issues to report. Closing out the ticket. 

This work has been pushed out to production cc: @Bren22va @outerpress @JRRoof 

<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5476b64b32b74786a6c4cb04ca15655db7a80f4/Screenshot%202024-07-23%20at%2010.36.12%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 10.36.12 PM.png" />
