### ISSUE TITLE
Access for Shaun Hubbard[Thought Works]

### ISSUE THREAD

**Issue by shaunhubbard-va** [department-of-veterans-affairs/va.gov-team#8037]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Crystal Moultrie
- Please provide your name.
   > Shaun Hubbard
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > ThoughtWorks, Developer, ThoughtWorks
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJbUp78RzuLpd5s/FycOQtnztxcmtLUF4mjkcrcFEwp94f44OE34ixAmwiMfQ3kiNKAbg1P3NGzSdC1+H6GePhJmze7YnA+J/8yfb+Zc9JZkpwr4C6GIemMd9vJF0av28VLdtE8O7yGrOMsDSUk0A6QoNDbYgCUSYZMoVFhiC9U+xnn7oebSZyLzZc7P6AD/fd6nYF6FO7Ln0GQu/dYo6Db3V6nM8FWOs2XHyet/8ULHUM78drM+PdUhBwUmKczPFGJg+S0DfKRJzawfG5ph8EATFUA1DegPAlFX1ZugLLy95Ylo6fjpCMHc2CtpotUm8a0GkOtgH9hXHeHqKxzxlRZoAMsWms6EDIkpif7OmVI6ZmaGY7DzMz+MEAHrWBtEKpfrElXNmrVmdvEpgDOAYKb9LxQ2MlUxcVz04YHMtunt+f2i0D3f36XRqCSOc6mByKK7NCzJ1PFHhiKWiErPHevhTMaVgwZs36jGwCED7TBGloBlQ4rDK/Q5uZRIXIRqyM1wLR0KOuD0kYIjQVezj3rLtQNUGIgr5FgmCA+uEdmkBsAQqLx1ayxaynDHifvhTVcbGgDencbht2M8LHbq+Mg7t/5CDyYS8Pl/WO1VkxfBEl3sn+pjhU4Iob0hmLI/rg6/4+uOsaOc6TVHXZx7hiK6VWA5A97JwsZwnrinGcYQ== “shaun.hubbard@thoughtworks.com”
```

- [Grant AWS Console access?]
  > NO
  >  My PIV card has not yet been granted so I believe I am inelligible.

**Comment by shaunhubbard-va** [comment]
Sorry for a repeat request from #7675, had to generate a new RSA key. If possible to remove the old one please do

**Comment by jbritt1** [comment]
Other one already closed. Updating your key now.

**Comment by jbritt1** [comment]
Key updated, new config deployed.
