### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by alexiawunder** [department-of-veterans-affairs/va.gov-team#80398]
### Name

Bob Lewis

### Email

bob.lewis@bylight.com

### Role

UX Designer

### Team

Medical Records on VA.gov

### Product Manager (PM) name

Lichelle Bain

### Additional Notes

Bob is one of our generalists who will be helping out with any of the MHV on VA.gov tools.

**Comment by naomimarcussen** [comment]
An invite has been sent to bob.lewis@bylight.com. Once an account is created, I'll bump it up to have full access.

**Comment by naomimarcussen** [comment]
I see you created an account and have just upgraded it to have full access.

**Comment by alexiawunder** [comment]
Thank you, Naomi!
