### ISSUE TITLE
Update and make homepage coronavirus banner global

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8039]
## Update and make the homepage coronavirus banner global/sitewide (and consider adding dismissable function)

**Summary of problem:**
specific benefit pages include instructions about how to apply; usually one of those ways has been in-person; obviously, all in-person services have been affected by social distancing. We already cover this in the FAQs. The concern is how about on these specific benefit pages. 

Instead of manually updating the instructions here and there, I propose we come up with a more global and temporary solution, something that, once the pandemic ends, we just make a global change; or as the social distancing advisory changes (e.g., when certain regions/states start to have phased roll backs of social distancing) we have one place to update evolving guidance about VA locations and services, rather than manually updating specific pages every time.

## Acceptance Criteria
- [ ] 1/Update the existing Covid banner message, so it’s clear that it’s not just VAMC hours/services that are affected, but all VA locations that once supported Veterans in person. - @DanielleThierryUSDSVA 

- [x] 2/ Make the homepage banner ‘global’ (sitewide) - CMS/Drupal @RLHecht 

Is this available via Drupal? ~Yes, believe so~ Yes. See screenshot in this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8039#issuecomment-614324204

- [x] 3/ Add the ‘dismiss’ functionality on the banner that will appear on other (not VA.gov home) page; use the 'dismiss every time' choice in Drupal. [Confirming, yes.]

- [x] 4/  Keep the `homepage `banner **not dismissable** (as it is today).  
~Note: we have this [turned off in PROD for the homepage banner](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7098), currently available in staging)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jenniferlee-dsva. Definitely agree this is important and much better to do a global and easily reversible solution. Will add this to covid triage as well. Thanks!

**Comment by jenniferlee-dsva** [comment]
Hey good news!  

Adding some info regarding dismissable functionality in the Drupal driven banner. It looks like it's just a checkbox and it can be set to be 'every session' (message appears every time you visit, so you have to dismiss each return visit -- which is what we would want for this coronavirus banner). 

Screen shot attached:

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/25d90183-1767-464d-b3eb-5b17315ae601)

**Comment by jenniferlee-dsva** [comment]
Updated/added info in issue description ^

**Comment by jenniferlee-dsva** [comment]
Confirming post-Monday's COVID-19 triage call: yes, we will update the banner text & once text JTF-approved, add the banner to lower level VA.gov pages. Desired ETA next Monday April 27 deployment. (As early as April 25 Friday okay IF JTF text approval and Drupal changes ready.)  

@RLHecht - there's a bit of manual to-do's inside the Drupal banner interface, so let's TB before you start the Drupal part of this effort. Depending on how cumbersome the manual part is (adding the comma delimited node IDs), we may want to roll this out hub at a time to be sure we capture all the pages that should get this banner. 

Inventory for banner:
All of the static benefit hub and benefit detail pages, including root pages. 
EXCLUDE: medical center nodes on Drupal.

**Comment by stephorkandatx** [comment]
Is it possible to get an exported list of all the node ids? @beeyayjay can look into this

**Comment by ncksllvn** [comment]
Dev context:

This banner is GitHub-backed. It is processed from vagov-content into page data in this [file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/home.js#L38) and then rendered into HTML in the [header template](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/includes/header.html#L89) via a `homepage_banner` attribute which is applied only to the homepage page data. To make it global, we'd have to lift it out of the homepage scope and into a global scope, or add it into the page data for every page (minus the VAMC pages like Pittsburgh, which we want to leave alone bc they have their own banners.)

**Comment by beeyayjay** [comment]
Here's a list of all benefits pages with node id and type. It's a csv file so it would be easy to upload as an airtable or google spreadsheet if you want it to be shareable.

[benefits-pages.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4518840/benefits-pages.csv.zip)
(Note: github won't accept csv files, so I zipped it. If that doesn't work, let me know.)

**Comment by ncksllvn** [comment]
Dev note -

We can mark this banner as global via `metalsmith.metadata()`. I think we could change this [line](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/home.js#L52) to be 
```
metalsmith.metadata({ homepage_banner }, ...metalsmith.metadata()); // Make sure we don't overwrite old metadata
```

The the `homepage_banner` property should be in the scope of every page.

**Comment by beeyayjay** [comment]
@ncksllvn, could you modify that to target only benefits pages (content types 'page' and 'landing_page')?

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx **Content update:** Content drafted and sent to Lauren to take through review cycle. Will update here when we have approved content. Thanks!

**Comment by jenniferlee-dsva** [comment]
Regarding @ncksllvn 's dev note: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8039#issuecomment-618023088

Let's pull the current OPIA homepage banner out of this thread/ticket bc it needs larger discussion. One of the critical things is still enabling OPIA to have direct and immediate publish access BUT also having technical permissions setting so they can't push these out to all pages on VA.gov. I don't think Drupal has or if it could have that granular level of permission setting.

**Comment by stephorkandatx** [comment]
@ncksllvn Re: Jen's comment about OPIA, can we update this work to capture that?

**Comment by ncksllvn** [comment]
Yeah I think we need to clarify/expand on the acceptance criteria. I'm not sure I follow that well either. The [PR I have open](https://github.com/department-of-veterans-affairs/vets-website/pull/12365) would show the homepage banner as a non-dismissible banner across all non-VAMC pages

**Comment by jenniferlee-dsva** [comment]
Some confusion around ^ - let's sync to get on same page. See in flight thread: https://dsva.slack.com/archives/C52CL1PKQ/p1587996086014500 @stephorkandatx

**Comment by stephorkandatx** [comment]
Per conversation in Slack:
We will not be able to move ahead with the technical "workaround" due to OPIA requirements.
For this situation, it will need to be Drupal driven. 
We need to move back to the approach of the banner being recreated, via Drupal, in the individual nodes.

**Comment by RLHecht** [comment]
@stephorkandatx  @jenniferlee-dsva We are still awaiting the approved text for the banner but I entered in all the Drupal node IDs from Beth and saved as a draft.

**Comment by kelsonic** [comment]
Unassigning myself, lmk if you still need @ncksllvn or me to work on this at some point 🙂

**Comment by RLHecht** [comment]
This work was done 5/1 and banner is now sitewide with the same text that is on the home page banner.  This has been validated. Closing ticket.
