### ISSUE TITLE
Reports Powered by UA: Accredited Representation Management

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#80397]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

---

### Instructions:
**Step 1:** Please provide the following information on each actively used report your team uses that contains UA data at the bottom of this ticket. _(Or, if it's easier, attach a spreadsheet.)_
- Report Name
- URL Link
- Reporting Platform (Domo, GA, etc.)
- Description of Report (i.e. How it's used)
  
**Step 2:** Include your team name within the title of this form.

**Step 3:** Submit this form.

_Our team will follow up with you for any next steps._

> [!NOTE]
> - We are defining _"actively used reports"_ as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
> - Teams do NOT have to include the standard [Search](https://va-gov.domo.com/page/1964748112), [Content](https://va-gov.domo.com/page/426422632), or [Forms](https://va-gov.domo.com/page/447193050) KPI dashboards --  we are already working to update those.

> ### Example:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|VA Homepage Report|https://va-gov.domo.com/page/|Domo| Our team uses this report to analyze trends for our KPIs.|
---

## Reporting Information:

Until we have a dashboard available to track the performance of Find a Rep (open [Analytics Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70420) and [Edge Case Dashboard Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70424)), the ARM team is using these reports in Google Analytics to keep an eye on user activity.

| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
| Audience Overview for FAR user groups vs. all of VA.gov users |(https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20240312&_u.date01=20240318&_.useg=user0ChHUWxaSUWm-5ocHKwm0Q,user_5CvEnKiSOmYYMHT8kTpQQ,builtin1&overview-dimensionSummary.selectedGroup=system&overview-dimensionSummary.selectedDimension=analytics.browser/)| Google Analytics | These metrics help us to compare engagement for users who interact with ARM products vs. the baseline for all VA.gov users |
| Page traffic for Fin a Rep and the landing page | https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240310&_u.date01=20240319&explorer-table.plotKeys=%5B%5D&explorer-table.filter=get-help-from-accredited-representative/ | Google Analytics | We are using this to track traffic of the landing page and Find a Rep initial product page, including previous and next pages to understand how our product fits into the larger VA.gov experience |
| Page Traffic for the Find a Rep post-search experience | https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240311&_u.date01=20240318&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22BW%22,%22www.va.gov~2Fget-help-from-accredited-representative~2Ffind-rep~2F%3F%22,0%5D%5D/ | Google Analytics | This report helps us to understand how long users are spending on Find a Representative after performing a search, since the URL updates post-search 
| Link for clicks on elements in the experience | https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240408&_.useg=&_r.drilldown=analytics.pagePath:www.va.gov~2Fget-help-from-accredited-representative~2Ffind-rep~2F,analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-graphOptions.selected=analytics.nthDay/ | Google Analytics | We are using this to track user interactions with standard VADS elements

**Comment by oddball-lindsay** [comment]
@johnny-jesensky-adhoc first pass, but I'm taking the assignment to first confirm with my team that I have all the reports documented above.  I'll pass assignment back to you soon!

@jfinnerty13 I'm wondering if there are any other reports in Google Analytics related to our products, that are worth adding to the table above?  I think you had a GA report that covered all events for Find that I don't seem to have bookmarked, but that could be helpful to include.  Also heads up that there is content on the table to the right of the URLs -- the horizontal scrollbar can be easy to miss.

**Comment by jfinnerty13** [comment]
1. Double checking the link above is ONLY filter URLs correct?
2. [Link for clicks on elements in the experience.](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240408&_.useg=&_r.drilldown=analytics.pagePath:www.va.gov~2Fget-help-from-accredited-representative~2Ffind-rep~2F,analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-graphOptions.selected=analytics.nthDay/)

Does the above get you what you were looking for @oddball-lindsay ?

**Comment by oddball-lindsay** [comment]
Thanks @jfinnerty13 I'll add that to the table!  The ticket description says "all actively used reports that use GA Universal Analytics (UA) data" so I think it'd be any report -- filtered or not.  With that in mind, anything else to add?

**Comment by jfinnerty13** [comment]
Just in case
1. [The all page view.](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240409&explorer-table.filter=get-help-from-accredited-representative~2F&explorer-table.plotKeys=%5B%5D/)
2. [The audience segmentations.](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240408&_.useg=user_5CvEnKiSOmYYMHT8kTpQQ,user0ChHUWxaSUWm-5ocHKwm0Q/)

That's all I have thanks @oddball-lindsay !

**Comment by oddball-lindsay** [comment]
Awesome, I have those as the first two rows on the table above. Thanks for being my double check @jfinnerty13! 

@johnny-jesensky-adhoc passing back to you :)

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for the quick turnaround on this @oddball-lindsay! This information will be helpful as we try to assist and train teams on the new GA4 interface and reports.

FYI @jestutt, @Blivaditis, @ChristineYoungZA
