### ISSUE TITLE
Purge vets-website assets directory and vagov-content assets directory

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#804]
Currently, vets-website contains a static [assets](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/site/assets) directory, and so does [vagov-content](https://github.com/department-of-veterans-affairs/vagov-content/tree/master/assets). There are also static assets coming from the CMS. Many of these are unused, and are wasteful to leave sitting around.

Ultimately, all assets should be coming from the CMS, unless they're referenced in React pages. So then, the directories should be -

1. vets-website - only assets referenced from React pages or template files
2. vagov-content - only assets referenced from content pages, that should ultimately be migrated into Drupal, where the content team can control it.

**Comment by Karak888** [comment]
Moving to close thanks!
