### ISSUE TITLE
Review Form 21-22a, questions 19a and 19b

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#80406]
## Request

> @aprocik1 requesting your assistance with updated content for Appoint MVP, specifically [two new screens](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=4067%3A215564&type=design&node-id=4075-291199&viewport=-4542%2C188%2C0.5&t=cBkJaOy0LWpOG30x-1&scaling=min-zoom&mode=design) that reflect fields 19a and 19b of the [21-22a form](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf).
> 
> Originally we though these were related to the medical authorizations, but after stakeholder design review with OGC we have since learned that this is more related to overall access to all records. Here's the logic:
> 
>
> 1. Staff associated with the attorney/agent's POA code can access digital records (19a)
> 2. Staff that are specifically named can access records when they call/email/show up in person (19b)
>      a. This could include folks in bucket https://github.com/department-of-veterans-affairs/va.gov-team/issues/1 but could also include other folks
>
> Timing-wise, we'd like to enter another round of stakeholder review of Appoint MVP designs in the next sprint. Ideally we'd receive content recommendations for these two screens/questions by EOD next Wednesday, 4/17 if possible.

## Criteria
- [ ] We've provided content recommendations to the product team

**Comment by aprocik1** [comment]
Lindsay, I reviewed the updates to Form 21-22a authorization screens. I commented in [the Figma file](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=4075-291783&mode=design&t=jB2MpZCRO4nSm5dJ-4) and compiled these outstanding questions for you:

- I think we need to better define what records are being released. It seems like OGC SMEs said that they're not only medical records. Can you clarify what "overall access to all records" means?
- The legalese in "our personnel record access authorization policy" accordion says, "...I authorize to disclose all of the Veteran's records..." Is it always the case that Veteran's records are being released? Or would a non-Veteran claimant's records ever be released? For example, what should the legalese say if a dependent spouse is completing Form 21-22a to appoint their own accredited attorney?
     - The answer to this question will help determine header and body copy updates.
- Does the second screen only appear if someone selects "yes" on the first screen?
- Why is the legalese different on the first and second screens?
- Does the "if yes" component at the bottom of the second screen only appear if someone selects yes? Or is it a static component?

**Comment by oddball-lindsay** [comment]
> I think we need to better define what records are being released. It seems like OGC SMEs said that they're not only medical records. Can you clarify what "overall access to all records" means?

From stakeholder review, we clarified that signing the 21-22 and 21-22a forms authorizes access to any/all of the Veterans records.  This is called out in the block of text above the signature field, where it says "I authorize VA to release any and all of my records...".  So this is what we are referring to by "overall access to all records".  

The specific medical authorization for those four conditions come up because SECTION 7332, TITLE 38 U.S.C. requires additional authorization for these types of records.  Any records outside of these four conditions fall in the "any and all of my records" bucket.

> The legalese in the accordions says, "...I authorize to disclose all of the Veteran's records..."  Is it always true that the Veteran's records are being released? Or would a non-Veteran claimant's records ever be released? For example, what should the legalese say if a dependent spouse is completing Form 21-22a to appoint their own accredited attorney?

With OGC in the discussion, it sounded like there are concerns with messing with the legalese in any way and we should leave it as-is on the form in the accordion expansion.  

That said, we still can lean on our friendly copy outside of that accordion to help users understand what records are in play. I think we can lean on the [authorization logic from stakeholders](https://dsva.slack.com/docs/T03FECE8V/F05TK26L27J?focus_section_id=temp:C:cNLa4523ce0a1a74850925a58ab0), with the idea that:
1. It'd be the Veteran's records when it's the Veteran completing the form for their own representation, or a NVC seeking representation for survivor benefits
2. It'd be the "relevant records" for a NVC when they are applying for something other than survivor benefits (this is the example you posed about a dependent spouse)

> Does the second screen only appear if someone selects "yes" on the first screen?
No, we've determined these screens are for separate access.  
1. The first/left screen with "Do you authorize the [attorney or claims agent]’s team to access your records?" is authorizing any staff associated with the rep's POA code to have direct, digital access to VBMS.  
3. The second/right screen with "Do you authorize [attorney or claims agent]’s administrative staff to request your records?" is authorizing any additional staff the ability to contact the VA and obtain records through non-digital means (email perhaps).  The representative may forget who on their staff is attached to their POA code and could put redundant names here that are covered in `#1`.  But this is intended to be additional access authorization, albeit in a more manual manner of retrieval, for any add'l staff that doesn't have that POA code association.

> Does the "if yes" component at the bottom of the second screen only appear if someone selects yes? Or is it a static component?
Up for discussion, we hadn't talked too much about this behavior.  Do you have a preference?  I'm guessing it might be better on the accessibility front to have this be a static component, but that's just a guess!

**Comment by aprocik1** [comment]
Thanks, @oddball-lindsay!

**Content follow up notes**
- Let me know if "VA records" holds the same meaning as "any and all records" in the drafts for review below.
- I've drafted 3 variations of content depending on each scenario in the authorization logic. They align with the 3 variations of content I've drafted for the other authorization screens in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80428#issue-2235805908).
     - Note: There's a contradiction in the variation of content for non-Veteran claimants seeking help with non-survivor benefits. Based on the authorization logic from stakeholders, we're seeking authorization to release the non-Veteran claimant's records in this scenario. But based on the legalese, we're seeking authorization to release the Veteran's records always (assuming OGC won't let us edit that content). This seems like a confusing inaccuracy that we should clarify for non-Veteran claimants seeking help with non-survivor benefits.

**Design follow up notes**
- Let me know if I've captured the nuance of "access" v. "request access" in the drafts for review below.
     - Screen 1 uses this language: "This accredited representative's team may need access..."
     - Screen 2 uses this language: "People connected to this accredited representative may need to request access..."
- I'm not sure what accessibility will say about the dynamic v. static "if yes" component. The best solution may be to place it on it's own screen, but I think that depends on how the authorization works. What happens if someone answers "yes," but doesn't enter any names in the "if yes" component? Does that result in the same outcome as someone who answers "no"?
     - Depending on how this authorization works, I wonder if we forgo a yes / no question entirely. This screen may just need to become a prompt to enter the names of people connected to the accredited representative who can request access to records.

**Drafts for review**
<details>
<summary>Content variation 1</summary>

## Scenarios
- A non-Veteran claimant is seeking help with non-survivor benefits
- A Veteran is seeking help with their own benefits

## Recommendation for screen 1
[H2] Authorization to access your VA records

This accredited representative's team may need access to your VA records to help you file a claim or request a decision review.

[Accordion] Our personnel record access authorization policy
[Legalese]

Do you authorize this accredited representative's team to access your VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization to request your VA records

People connected to this accredited representative may need to request access to your VA records to help you file a claim or request a decision review.

[Accordion] Our personnel record request authorization policy
[Legalese]

Do you authorize people connected to this accredited representative to request access to your VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.
</details>

<details>
<summary>Content variation 2</summary>

## Scenario
- A non-Veteran claimant is seeking help with survivor benefits

## Recommendation for screen 1
[H2] Authorization to access Veteran VA records
This accredited representative's team may need to access [Veteran first and last name]'s VA records to help you file a claim or request a decision review for survivor benefits.

[Accordion] Our personnel record access authorization policy
[Legalese]

Do you authorize this accredited representative's team to access [Veteran first and last name]'s VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization to request Veteran VA records
People connected to this accredited representative may need to request access to [Veteran first and last name]'s VA records to help you file a claim or request a decision review for survivor benefits.

[Accordion] Our personnel record request authorization policy
[Legalese]

Do you authorize people connected to this accredited representative to request access to [Veteran first and last name]'s VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.
</details>

<details>
<summary>Content variation 3</summary>

## Scenario
- A non-Veteran claimant is seeking help on behalf of a Veteran

## Recommendation for screen 1
[H2] Authorization to access Veteran VA records

This accredited representative's team may need to access [Veteran first and last name]'s VA records to help them file a claim or request a decision review.

[Accordion] Our personnel record access authorization policy
[Legalese]

Do you authorize this accredited representative's team to access [Veteran first and last name]'s VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization to request Veteran VA records
People connected to this accredited representative may need to request access to [Veteran first and last name]'s VA records to help them file a claim or request a decision review.

[Accordion] Our personnel record request authorization policy
[Legalese]

Do you authorize people connected to this accredited representative to request access to [Veteran first and last name]'s VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.

</details>

**Comment by oddball-lindsay** [comment]
Great qs @aprocik1 and I don't have a confident answer for any of these.  I'm going to message the stakeholder group to confirm and will cc you!

**Comment by oddball-lindsay** [comment]
One clarification actually -- for the contradiction in the legalese for non-Veteran claimants seeking help with non-survivor benefits, @aprocik1 what legalese are you referring to?

**Comment by aprocik1** [comment]
@oddball-lindsay, I was referring to the legalese in [this Figma file](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=4075-291199&mode=design&t=nqQDAkMfV0LXjGCj-4). However, I'm now seeing that file doesn't match the legalese on the PDF form. I've corrected the content variations where the contradiction occurs below based on the PDF form.

<details>
<summary>Screenshot of Form 21-22a, question 19a legalese</summary>

<img width="357" alt="2024 04 12 ARM AAR 21-22a 19a (PDF)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/142408200/457c6eb3-0500-4144-a2ce-a22da7ecf480">

</details>

<details>
<summary>Screenshot of Form 21-22a, question 19b legalese</summary>

<img width="359" alt="2024 04 12 ARM AAR 21-22a 19b (PDF)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/142408200/0f64b61f-2763-4f2b-bdf6-4f056d35c26a">

</details>

The legalese in Form 21-22a, questions 19a and 19b says this:

> I authorize VA to disclose all my records...

That legalese works for these scenarios:

- A non-Veteran claimant is seeking help with non-survivor benefits
- A Veteran is seeking help with their own benefits

But that legalese doesn't work for these scenarios:

- A non-Veteran claimant is seeking help with survivor benefits
- A non-Veteran claimant is seeking help on behalf of a Veteran

That's because of the authorization logic from stakeholders. They've told us that non-Veteran claimants seeking help on behalf of a Veteran and non-Veteran claimants seeking help with survivor benefits both authorize access to the Veteran's records. That means the legalese needs to say this:

> I authorize VA to disclose all the Veteran's records...

If OGC doesn't want us to the change the legalese, then we'll be presenting a contradiction between the plain language in the question and the legalese in the accordion.

**Comment by oddball-lindsay** [comment]
@aprocik1 while that clarification is out for feedback, here's some answers to the other questions

> Let me know if "VA records" holds the same meaning as "any and all records" in the drafts for review below.

Confirmed that VA records holds the same meaning and is appropriate to move forward with

> Let me know if I've captured the nuance of "access" v. "request access" in the drafts for review below.

Update needed here!  After speaking with Jonathan, the end goal of both authorizations is to disclose records.  The only difference is the means of access -- 19a (screen 1) is digital access, mostly VBMS but he mentioned there may be some other digital records that also come into play.  19b (screen 2) is non-digital access.  Jonathan mentioned he's not sure if "digital" or "electronic" makes more sense, I'll let you make that call :).

> What happens if someone answers "yes," but doesn't enter any names in the "if yes" component? Does that result in the same outcome as someone who answers "no"?
Depending on how this authorization works, I wonder if we forgo a yes / no question entirely. This screen may just need to become a prompt to enter the names of people connected to the accredited representative who can request access to records.

For 19b (screen 2) the names should be required.  So while the form has both a checkbox and a free text field for names, there is the assumption that names will be entered if the box is checked.  Interesting idea to forgo the yes / no and just focus on the names, I could see that making sense!  cc @mtri for this particular piece, as there are design considerations here

**Comment by aprocik1** [comment]
THIS COMMENT IS IN DRAFT -- I'll return to it and tag Lindsay when I'm ready

Lindsay, thanks for following up with SMEs on these questions. I've updated one of the drafts for review below. After you review this draft and clarify the authorization logic / legalese contradiction, I can return to finalize the other content variations.

**Drafts for review**
<details>
<summary>Content variation 1</summary>

## Scenarios
- A non-Veteran claimant is seeking help with non-survivor benefits
- A Veteran is seeking help with their own benefits

## Recommendation for screen 1
[H2] Authorization to access your VA records online

This accredited [attorney, claims agent]'s team may need access to your VA records online to help you file a claim or request a decision review.

[Accordion] Our personnel record access authorization policy
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access your VA records online?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization to print your VA records

This accredited [attorney, claims agent]'s team may need to print your VA records to help you file a claim or request a decision review.

[Accordion] Our personnel record print authorization policy
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to print your VA records?
- Yes
- No

**Note:** You can cancel this authorization any time.

If yes,



</details>

**Comment by oddball-lindsay** [comment]
@aprocik1 i know we're bumping up against the Weds request date and have yet to clarify what seems to be a contradiction of "my records" on fields 19a/b for those scenarios you called out above. 

The latest update I have is a direct message from Jonathan saying that he thinks that the claimants files are within the Veteran's eFolder, but he's not totally sure.  I'll need to confirm that; just wanted to let you know that this is still on my radar and I am aware of the timing implications of this open q.

**Comment by aprocik1** [comment]
@oddball-lindsay, thanks for tracking down this clarification. And great catch on the requirements for 19b!

Here are the updated drafts of all 3 variations with 3 screens each:

<details>
<summary>Content variation 1</summary>

## Scenarios
- A non-Veteran claimant is seeking help with non-survivor benefits
- A Veteran is seeking help with their own benefits

## Recommendation for screen 1
[H2] Authorization for access in VA's systems

This accredited [attorney, claims agent] may work with their team to help you file a claim or request a decision review. Some of their team members may need to access your records in VA's information technology systems.

[Accordion] Our policy for access in VA's systems
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access your records in VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization for access outside of VA's systems

This accredited [attorney, claims agent] may work with their team to help you file a claim or request a decision review. Some of their team members may need to access your records outside of VA's information technology systems.

[Accordion] Our policy for access outside of VA's systems
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access your records outside of VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 3 (if "yes" in screen 2)
[H2] Authorization for access outside of VA's systems

You've authorized this accredited [attorney, claims agent]'s team to access your records outside of VA's information technology systems.

Enter the name of each team member who can access your records (*Required)
[Hint] Use commas to separate names
[Open text field]

**Note:** If you're not sure who to enter, ask the accredited [attorney, claims agent] you're appointing.

</details>

<details>
<summary>Content variation 2</summary>

## Scenario
- A non-Veteran claimant is seeking help with survivor benefits

## Recommendation for screen 1
[H2] Authorization for access in VA's systems

This accredited [attorney, claims agent] may work with their team to help you file a claim or request a decision review for survivor benefits. Some of their team members may need to access [Veteran first and last name]'s records in VA's information technology systems.

[Accordion] Our policy for access in VA's systems
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records in VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization for access outside of VA's systems

This accredited [attorney, claims agent] may work with their team to help you file a claim or request a decision review for survivor benefits. Some of their team members may need to access [Veteran first and last name]'s records outside of VA's information technology systems.

[Accordion] Our policy for access outside of VA's systems
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records outside of VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 3 (if "yes" in screen 2)
[H2] Authorization for access outside of VA's systems

You've authorized this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records outside of VA's information technology systems.

Enter the name of each team member who can access [Veteran first and last name]'s records (*Required)
[Hint] Use commas to separate names
[Open text field]

**Note:** If you're not sure who to enter, ask the accredited [attorney, claims agent] you're appointing.

</details>

<details>
<summary>Content variation 3</summary>

## Scenario
- A non-Veteran claimant is seeking help on behalf of a Veteran

## Recommendation for screen 1
[H2] Authorization for access in VA's systems

This accredited [attorney, claims agent] may work with their team to help file a claim or request a decision review for the Veteran. Some of their team members may need to access [Veteran first and last name]'s records in VA's information technology systems.

[Accordion] Our policy for access in VA's systems
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records in VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization for access outside of VA's systems

This accredited [attorney, claims agent] may work with their team to help file a claim or request a decision review for the Veteran. Some of their team members may need to access [Veteran first and last name]'s records outside of VA's information technology systems.

[Accordion] Our policy for access outside of VA's systems
[Legalese]

Do you authorize this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records outside of VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 3 (if "yes" in screen 2)
[H2] Authorization for access outside of VA's systems

You've authorized this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records outside of VA's information technology systems.

Enter the name of each team member who can access [Veteran first and last name]'s records (*Required)
[Hint] Use commas to separate names
[Open text field]

**Note:** If you're not sure who to enter, ask the accredited [attorney, claims agent] you're appointing.

</details>

**Comment by oddball-lindsay** [comment]
Thanks so much @aprocik1!  From Jenny's last message and some recent direct messages from Jonathan, it seems like they are trying to tell us that while yes, the Veteran's records may be referenced in these survivor and fiduciary/incompetent scenarios, the veterans records are connected to the claimants records in VBMS and therefore "my records" is all encompassing.

I'll kick off an email to the group to confirm that I'm interpreting this correctly; if so, then content variation 1 would apply to all scenarios.

**Comment by aprocik1** [comment]
Thanks, @oddball-lindsay. I think we still need these 2 content variations:

1. Content for non-Veteran claimants and Veterans who are appointing their own representative
2. Content for non-Veteran claimants who are appointing a representative on behalf of a Veteran

Let me know what you think of these drafts:

<details>
<summary>Content variation 1</summary>

## Scenarios
- A non-Veteran claimant is seeking help with their own benefits (non-survivor or survivor benefits)
- A Veteran is seeking help with their own benefits

## Recommendation for screen 1
[H2] Authorization for access in VA's systems

This accredited [attorney, claims agent] may work with their team to help you file a claim or request a decision review. Some of their team members may need to access your records in VA's information technology systems.

[Accordion] Our policy for access in VA's systems
[Legalese from PDF] If the individual in Item 16A is an accredited agent or attorney who has been approved by VA for access to VA information technology (IT) systems in accordance with 38 CFR 1.600 to 1.603, I AUTHORIZE VA to disclose all of my records (other than as provided in Items 20 and 21) to the associate attorneys, claims agents, and support staff affiliated with my representative.

Do you authorize this accredited [attorney, claims agent]'s team to access your records in VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization for access outside of VA's systems

This accredited [attorney, claims agent] may work with their team to help you file a claim or request a decision review. Some of their team members may need to access your records outside of VA's information technology systems.

[Accordion] Our policy for access outside of VA's systems
[Legalese from PDF] If the individual in Item 16A is an accredited agent or attorney, I AUTHORIZE VA to disclose all my records (other than as provided in Items 20 and 21) to the following individuals named as administrative employees of my representative. This applies to disclosures, outside of those made via access to VA electronic IT systems contemplated by 38 CFR 1.600 to 1.603.

Do you authorize this accredited [attorney, claims agent]'s team to access your records outside of VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 3 (if "yes" in screen 2)
[H2] Authorization for access outside of VA's systems

You've authorized this accredited [attorney, claims agent]'s team to access your records outside of VA's information technology systems.

Enter the name of each team member who can access your records (*Required)
[Hint] Use commas to separate names
[Open text field]

**Note:** If you're not sure who to enter, ask the accredited [attorney, claims agent] you're appointing.

</details>

<details>
<summary>Content variation 2</summary>

## Scenario
- A non-Veteran claimant is seeking help on behalf of a Veteran

## Recommendation for screen 1
[H2] Authorization for access in VA's systems

This accredited [attorney, claims agent] may work with their team to help [Veteran first and last name] file a claim or request a decision review. Some of their team members may need to access the Veteran's records in VA's information technology systems.

[Accordion] Our policy for access in VA's systems
[`Adjusted` legalese from PDF] If the individual in Item 16A is an accredited agent or attorney who has been approved by VA for access to VA information technology (IT) systems in accordance with 38 CFR 1.600 to 1.603, I AUTHORIZE VA to disclose all of `the Veteran's` records (other than as provided in Items 20 and 21) to the associate attorneys, claims agents, and support staff affiliated with `the` representative.

Do you authorize this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records in VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2
[H2] Authorization for access outside of VA's systems

This accredited [attorney, claims agent] may work with their team to help [Veteran first and last name] file a claim or request a decision review. Some of their team members may need to access the Veteran's records outside of VA's information technology systems.

[Accordion] Our policy for access outside of VA's systems
[`Adjusted` legalese from PDF] If the individual in Item 16A is an accredited agent or attorney, I AUTHORIZE VA to disclose all `the Veteran's` records (other than as provided in Items 20 and 21) to the following individuals named as administrative employees of `the` representative. This applies to disclosures, outside of those made via access to VA electronic IT systems contemplated by 38 CFR 1.600 to 1.603.

Do you authorize this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records outside of VA's information technology systems?
- Yes
- No

**Note:** You can cancel this authorization any time.

## Recommendation for screen 3 (if "yes" in screen 2)
[H2] Authorization for access outside of VA's systems

You've authorized this accredited [attorney, claims agent]'s team to access [Veteran first and last name]'s records outside of VA's information technology systems.

Enter the name of each team member who can access the Veteran's records (*Required)
[Hint] Use commas to separate names
[Open text field]

**Note:** If you're not sure who to enter, ask the accredited [attorney, claims agent] you're appointing.

</details>

P.S. Based on this clarification from SMEs, we don't need to distinction between non-Veteran claimants seeking help with non-survivor benefits and non-Veteran claimants seeking help with survivor benefits. I've updated my recommendation for the authorization screens content and logic in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80428#issue-2235805908).

**Comment by oddball-lindsay** [comment]
Thanks for all of this @aprocik1 🙏 

This upcoming design review is our final round so I am trying to get as close to stakeholder needs as possible so that we can minimize feedback and get into development.  I'm open to presenting the two variations to the stakeholders to get their feedback on the Veteran name call out, but have a feeling they may push for content variation 1 for all scenarios.  If not, great, but I want to be prepared for that outcome.

A couple of requests for these screens: 
1. Advise not to adjust legalese in the accordion component.  I've been leaning on the legalese component to curb any concerns about us having friendly copy front and center.  Adjusted legalese pushes into their desire to maintain the form legal copy in some fashion and from our past conversations, I have a feeling stakeholders are going to flag this.  
2. I've had a lot of conversations with Jonathan emphasizing the method of access for 19a vs. 19b.  Would like to lean into that in screen 3 with "Enter the name of each team member who can access the Veteran's records _outside of VA's information technology systems_".  It's longer, but maintains clarity on what's being provided for those named individuals.

Let me know what you think about these requests!

**Comment by aprocik1** [comment]
@oddball-lindsay, I want to confirm I understand your request around content variation 1 and the legalese.

If we use content variation 1 for all scenarios, a non-Veteran claimant appointing a representative on behalf of a Veteran will be presented with this content on screen 1:

- Snapshot of plain language: "some of their team members may need to access your records"
- Snapshot of legalese: "I authorize VA to disclose all of my records"

Based on the authorization logic from SMEs, we know that content is inaccuracate. A non-Veteran claimant needs to authorize access to the Veteran's records -- not their own records.

You're requesting that we use content variation 1 for all scenarios, despite that inaccuracy. Is that right?

(If we forgo using content variation 2, we could simplify the authorization logic in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80428#issue-2235805908), since there would be no need to ask why someone is appointing a representative.)

**Comment by aprocik1** [comment]
Update: Lindsay and I discuss my question above in a meeting. She's going to present content variation 1 for all scenarios to SMEs and report back on their feedback here.

**Comment by aprocik1** [comment]
Update: The product team confirmed that SMEs are okay with only using content variation 1 for all scenarios. Here's the updated Appoint tool [source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EZEW15_B_ZlMnxSTps9Tt8cBci2c-iWZTidg0IM4Pk2jMw?e=tgZWOz). Find the most recent content for all the authorization screens on pages 17-22.
