### ISSUE TITLE
Integrate three tools & secondary nav to MHV landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#80401]
### User story

As a Veteran, I want the "try me" experience on VAgov to provide a coherent and communicative experience as I use secure messages, appointments, and medications without having to return to the classic MHV website, so that I have the best chance of liking the new portal.

As a Veteran, if I choose a task that requires navigating to the Classic experience, I want VAgov to explicitly inform me that I'm leaving VAgov, so that I can avoid getting disoriented by unexpected navigation changes.

### Notes
- Three tools that will be on VAgov: Appts, SM and Medications
- UX design was established in #74454

## Steps/tasks
- Add secondary nav to tool pages – 5pts baseline (on LP), then 2-3 pts per tool
  - add details to release plan doc
- 

## Acceptance criteria

- Documented an implementation plan in Github in coordination with tool teams
- Documented a release plan in Github – [update this file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/integration-with-nav-release-plan-2024.md)
- The 3-tool landing page integration is ready to launch to Veterans behind a feature flag
- Secondary nav is implemented as designed, also behind the feature flag
- Special cases in the UX design are implemented:
  - Non-LOA3 use cases
  - Unregistered use case
  - Link(s) to MHV Classic notify the user as such 
- QA reviewed in coordination with tool teams as appropriate
- Design reviewed by UX team
- A11y specialist reviewed

**Comment by LynneJohnson224** [comment]
From [74454](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/74454)

## Feature Flag Use
- Secure Messaging
  - Root URL: `/my-health/secure-messages` 
  - Feature flag: `mhv_secure_messaging_to_va_gov_release`
  - When the flag is off: Users are redirected to `/health-care/secure-messaging`
  - Comments: The SM code has some leftover flags from the pilot days, so it can be confusing which flag to use. The flag `mhv_secure_messaging_cerner_pilot` incorrectly redirects to the same `manifest.rootUrl` giving a redirect loop, but this is no longer used.
- Medical Records
  - Root URL: `/my-health/medical-records` 
  - Feature flag: `mhv_medical_records_to_va_gov_release`
  - When the flag is off: Users are redirected to `/health-care/get-medical-records`
  - Comments: 
- Medications
  - Root URL: `/my-health/medications` 
  - Feature flag: `mhv_medications_to_va_gov_release`
  - When the flag is off: The app will display its about page at `/my-health/medications/about`
  - Comments: The Medications about page has text about trying out the tool, but I feel it is weird if a user gets here and the feature is not enabled.

## MHV Landing Page Links to Update
- Messages
  - Inbox - `/my-health/secure-messages/folders/inbox` 
  - Compose Message - `/my-health/secure-messages/new-message` 
  - Manage Folders - `/my-health/secure-messages/folders` 
- Medications
  - Refill VA Prescriptions - `/my-health/medications/refill` 
  - Track prescription delivery - ** DOES NOT MAP ** to the new app
  - Medications and Allergies - ** DOES NOT MAP ** to the new app
- Health Records
  - Download medical record - `/my-health/medical-records/download-all`
  - Lab and test results - `/my-health/medical-records/labs-and-tests`, but this is behind a feature flag `mhv_medical_records_display_labs_and_tests`
  - Health history - ** DOES NOT MAP ** to the new app. Will need to link to a new location
    - Comments: Health history includes allergies, immunization, medical events, personal health summary, etc.
 
## Remaining Questions
- What do we do for app features that are turned off like Lab and Test Results? Do we link to the old app? Or do we just remove the link?
- We will need a new link or different action for links that do not map to app pages on the new apps

**Comment by dcloud** [comment]
For refining, per Sara:

> Tool teams devs also need to do these things:
> 
> * update breadcrumbs on landing pages to point to MHV landing page
> * update all URLs to other tools to point to tools on VA.gov (not national portal)
> * implement Cerner/OH gating for any users with an oracle facility in their profile that routes them to MyVA Health

**Comment by wesrowe** [comment]
all issues closed. new epic picks up monitoring and iteration.
