### ISSUE TITLE
SOCKS access for Sean Midgley

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#80400]
### Your Name

Sean Midgley

### Your Email

sean.midgley@oddball.io

### Your GitHub Handle

Midge-dev

### Your Role and Team

Frontend Engineer - Non-Disability Experience

### Product Manager (PM) name and email

Laura Steele laura.steele@coforma.io

### Product Owner (PO) name and email

Emily Theiss emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFjXbseIm1rWqraBrdI7yd0sAq58DGeRmKaE0EnBNDHIxRI3AB9ry4IZ0R1i5Dox378hWLpC2pSQEJVV2JcYYOCx7uPFdB0LCdu9PhNdnnTD5fdCTAIaBcGXgXvVyUTJX4WcJUEi2OMEll7/fbFCPQ5AcDATyEoRLgZ9tUNgy2JIAPBin9S8QpPf50SHMnrwSmI2OwJvjPO3KAZLxOgPVqH1SKVoubft0/jMAVkLiFyaAHkC6r4rtLLVCMXPngaCEVCwXBbUQA/hJ7p54z1Dxpn9//2Nqk5xySNMaI7iajPd8zIlYP0hORHzHYjTaZzkEzGliA23ZWmT/HxhucyXrCMwdJBV4/9hZrXVALVGynstLRlOCLTQ0EyGz9DEUJf5+E72Uw/ITTS0ThalR2AQg9xDEeaHnyp/y2PXup88uGrlKoYwm3brMqV628+SCyUe7qkYOSelp0qDDyrdAqxIf1np8hpOJl9E93ANwPPcbHIj7+STS/uQnFRcNWW52ObD8= midge@Seans-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/2e58b1e6-6b86-4e0c-bb92-b767a3685f14)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/cc99c03d-f0da-4a03-99cc-986804f4fd5b)
<img width="1085" alt="Screenshot 2024-04-10 at 10 21 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/6005f6eb-97e5-4269-bf88-f9eda3cabde5">

I am requesting access for the same Macbook on Ruby version 3.2.3 (per api requirements) - I was only provisioned for 3.2.2 I guess, and so I am sending this new request. TIA

cc: @tblackwe 

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
PR approved and merged https://github.com/department-of-veterans-affairs/devops/pull/14206
