### ISSUE TITLE
Access for Monica Ramirez

### ISSUE THREAD

**Issue by mramirez-va** [department-of-veterans-affairs/va.gov-team#8040]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Monica Ramirez
- Please Provide your email.
   > monica.ramirez@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API Development and Operations, Software Engineer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPAY4Ntnj9DWMI6Aj4OONB0AzGBP2UhkoBS05uIe4DaA9d4wrMiFAeLpi2V+EO0orOESfeomwq4xrD/uBXXTxRXYK88Wy28GkiPZzn7Rb3IKfjz0A3dz7z4zOAZXLYIUKUPQ+cC1//nIFY2wM64JGD7ij4oGgzEI4ff5SYzp2Q7kHE2g2Vm60riyU1h7OXjh9QX2qHMKeVtnQLQIkuA/lvrdFB848nSuHXqpB1qaxGInTcw0iBtfhGInJ70DaxNBDyaFdrewFXHXEE3q67p5BRm3jHA9256e10wB4ucpcM4Efxw9+qCbDBVzYJ2dBGYIKA5AGzActa4Ozw8J0jwal3 mramirez@MacBook-Pro-3.local
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by mramirez-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
