### ISSUE TITLE
Automated Audit for IAM users in AWS

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8041]
## User Story or Problem Statement
ATO  requires an automated means of ensuring we don't have legacy users with accounts inactive for more than 90 days. We need a way to keep on top of this that isn't so manual.

## Goal
_Have an automated way to audit IAM users in AWS_

## Acceptance Criteria
- [x] _Automated solution in place to, at a minimum, warn the Operations Team of accounts getting close to the 90 day mark_
- [x] _Tested and verified_
- [x] _Explain and show proof of work to Faith for ATO approval_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
The work has been done and a working solution is currently in place. With Wyatt's suggestions, there is definitely some room for future improvements on the work that was done, but is likely a tad outside of the scope of the original ticket we have here. Faith was given an overview / explanation of the work that was done and how the work functions / fits into our daily operations and plans going forward. Closing at this time.
