### ISSUE TITLE
Access for Emily Subocz

### ISSUE THREAD

**Issue by esubocz-va** [department-of-veterans-affairs/va.gov-team#8042]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Emily Subocz
- Please Provide your email.
   > emily.subocz@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API Development and Operations. Software Developer. Liberty IT Solutions.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIMrtNHvoOc233bqsesVvfhkSGPUeWC86lM4ZpX0ShN+8ePclwgyHoa5fSVn7t7ISucw1CQmBpDPZ/yqOTblOJKI3jFF3HQ8RXd5dgn68SvIOP1C7bROA3WScsLOK39d64ODmQx6l7rUxqZKYfqRUGJjmdLr5D7y4PFRHPq/1LHnfcQe7FiXK3+XXmlNrNlN3JLal5/HEA6WbuRdlBklYJbVL0La+aGBt7qc6J6+xAKYADAo1cTcCJyMTcWO2uk2elSnxDp5qgDLqf+iHp3KvZ6rupisnQRbAu4YbdLoHrw28ubMANRwWX10UWg7C6ZWbAIaVsbag1xsXgSA9I0y2r lighthouse@libertyits
```

- [Grant AWS Console access?]
  > YES
  >  Please give a brief description for why you are requesting AWS access.

Required for support of vets-api and related projects as part of the Lighthouse contract

**Comment by esubocz-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jsev-io** [comment]
AWS Access Approval: @Jeff-Hayter 
User: Emily Subocz

**Comment by jsev-io** [comment]
cc: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jsev-io @jbritt1 Approved for AWS access.

**Comment by jsev-io** [comment]
Noticed that the key for socks here is just a little different than what's in department-of-veterans-affairs/devops#6739, changing to reflect the difference, and closing now that all related tasks are finished.

**Comment by jbritt1** [comment]
We will have your first time login credentials to you soon, @esubocz-va. We just have to work out a couple inconsistencies in our Terraform first.

**Comment by esubocz-va** [comment]
Okay great, thank you.


Emily Subocz|
Jr. Software Developer
emily.subocz@libertyits.com
505 N John Rodes Blvd
Melbourne,FL32934
CONFIDENTIALITY NOTICE: This email and any attachments are intended solely for the use of the named recipient(s). Please do not forward or copy without the author’s consent. Any dissemination of this email by anyone other than an intended recipient is strictly prohibited. If you have received this email in error, please permanently delete the email and all attachments from your system. All information contained in this document are considered proprietary and shall not be reproduced, transmitted or shared with any individual or company outside the specific group for which this information is strictly intended.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
