### ISSUE TITLE
Content-request: Consider possibility of changing Support to Support and Office Hours

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#80422]
### Describe the problem

I'm curious if data supports that the most viewed resource within Support is the Office Hours page and content. If so, although I wouldn't recommend changing the title of that section to Office Hours, I do think, potentially, on [Home Page](https://depo-platform-documentation.scrollhelp.site/), it might be nice to experiment with changing the title to Support and office hours. However, if the data doesn't support that, then I digress. And, could potentially change the page title of [Support](https://depo-platform-documentation.scrollhelp.site/support/) to "Support and office hours" to better reflect what users come to this section for. 

### Who will benefit

Anyone using Platform, if the data supports this change. And, it would encourage/promote use of VFS-to-Platform Team encounters. 

### Describe your idea

On the [Home Page](https://depo-platform-documentation.scrollhelp.site/), it might be nice to experiment with changing the title to Support and office hours. And, could potentially change the page title of [Support](https://depo-platform-documentation.scrollhelp.site/support/) to "Support and office hours" to better reflect what users come to this section for. 

### Provide evidence

Evidence would need to be gathered via analytics, e.g., pageviews of Support section. 

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [ ] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [X] Other

### Other:

Goes with the flow, i.e., aligns with what matters most to VFS teams.

**Comment by benbrasso-agile6** [comment]
Might need to change label to use the content request vs feature request. Apologies.

**Comment by jknipes** [comment]
Hi @benbrasso-agile6, Google Analytics shows the top 3 most viewed pages for the Support section of Platform Website are 

1. [Getting Help from The Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack)
2. [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/support-overview)
3. [Submitting a Feature Request](https://depo-platform-documentation.scrollhelp.site/support/submitting-a-feature-request)

**Comment by benbrasso-agile6** [comment]
Thx! Feel free to close or icebox.

**Comment by jknipes** [comment]
Discovery completed, moving to _Done_
