### ISSUE TITLE
Review Form 21-22 and 21-22a authorization screens

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#80428]
## Description
Provide content recommendations on [the Appoint a Rep authorization screens](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=3476-60783&mode=design&t=M8WIUGOEmZjBCs4E-4).

## Tasks
- [x] AP: Review screens

## Criteria
- [x] Provided content recommendations to the product team

**Comment by aprocik1** [comment]
@oddball-lindsay, I've left content recommendations in comments in [the Figma file](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=3476-60783&mode=design&t=M8WIUGOEmZjBCs4E-4). I've also recapped our conversation in Slack from 4/4.

<details>
<summary>Appoint a Rep logic for authorization screens</summary>

### Tell us who you are
Are you the Veteran?
- Yes
- No

### If no: Tell us why you're appoint an accredited representative
Why are you appointing an accredited representative?
- To help me with my VA benefit claims
- To help the Veteran with their VA benefit claims

### If my benefit claims: Tell us if you need help with VA survivor benefits
If you're the surviving family member of a Veteran, you may be eligible for these survivor benefits:

- Accrued Benefits
- Death Compensation
- Dependency and Indemnity Compensation (DIC)
- Restored Entitlement Program for Survivors (REPS)
- Special allowance under 38 U.S.C. 1312(a)
- Survivors’ and Dependents’ Education Assistance (DEA)—sometimes called "Chapter 35"
- Survivors Pension
- Veterans burial allowances—sometimes called “Veterans death benefits”

Are you filing a claim or requesting a decision review for survivor benefits?
- Yes
- No

</details>

**Comment by aprocik1** [comment]
@oddball-lindsay, I've updated my recommendations for authorization screen content and logic, based on the clarification from SMEs in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80406#issue-2235454968). left content recommendations in comments in [the Figma file](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=3476-60783&mode=design&t=M8WIUGOEmZjBCs4E-4). I've also recapped our conversation in Slack from 4/4.

 I think we still need these 2 content variations:

Content for non-Veteran claimants and Veterans who are appointing their own representative
Content for non-Veteran claimants who are appointing a representative on behalf of a Veteran
Let me know what you think of these drafts:


<details>
<summary>Authorization entry screens</summary>

## Recommendation for screen 1
[H2] Tell us who you are

Are you the Veteran?
- Yes
- No

## Recommendation for screen 2 (if "no" in screen 1)
[H2] Tell us why you're appoint an accredited representative

Why are you appointing an accredited representative?
- To help me with my VA benefit claims
- To help the Veteran with their VA benefit claims

<details>
<summary>Content variation 1</summary>

## Scenarios
- A non-Veteran claimant is seeking help with their own benefits (non-survivor or survivor benefits)
- A Veteran is seeking help with their own benefits

## Recommendation for screen 1
[H2] Authorization to access your medical records

This accredited [attorney, claims agent, Veterans Service Organization (VSO)] may need to access your medical records to help you get specialized health care services and treatments. You can authorize them to access all or some of these types of records:
- Alcoholism and alcohol abuse records
- Drug abuse records
- HIV (human immunodeficiency virus) records
- Sickle cell anemia records

Our records authorization policy
[Legalese from PDF] I authorize the VA facility having custody of my VA claimant records to disclose to the `[service organization named in Item 15 -or- the individual named in Item 16A, and the firm/organization/individual(s)
named in Item 19 (if approved by VA for affiliated access)]` all treatment records relating to drug abuse, alcoholism or alcohol abuse, infection with the human immunodeficiency virus (HIV), or sickle cell anemia. `[Redisclosure of these records by my service organization representative, other than to VA or the Court of Appeals for Veterans Claims, is not authorized without my further written consent -or- Redisclosure of further written consent]`. This authorization will remain in effect until the earlier of the following events: (1) I revoke this authorization by filing a written revocation with VA; or (2) I revoke the appointment of the `[service organization named in Item 15 -or- individual named in Item 16A]`, by explicit revocation or the appointment of another representative.

Do you authorize this accredited [attorney, claims agent, VSO] to access your medical records?
- Yes, they can access all of these types of records
- Yes, but they can only access some of these types of records
- No, they can't access any of these types of records

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2 (if "yes, but" in screen 1)
[H2] Authorization to access your medical records

You've authorized this accredited [attorney, claims agent, Veterans Service Organization] to access some of your medical records.

Select the types of records they can access
- Alcoholism and alcohol abuse records
- Drug abuse records
- HIV (human immunodeficiency virus) records
- Sickle cell anemia records

## Recommendation for screen 3
[H2] Authorization to change your address

This accredited [attorney, claims agent, Veterans Service Organization (VSO)] can help you change the address on your VA records. If the address on your VA records is incorrect or outdated, it may take us longer to contact you and process your benefit claims.

Our address authorization policy
[Legalese from PDF] I authorize `[the individual named in Item 16A -or- any official representative of the organization named in Item 15]` to act on my behalf to change my address in my VA records. This authorization does not extend to any other `[individual -or- organization]` without my further written consent. This authorization will remain in effect until the earlier of the following events: (1) I revoke this authorization by filing a written revocation with VA; or [(2) I appoint another representative, or (3) I have been determined unable to manage my financial affairs and the individual or organization named in Item 16A is not my appointed fiduciary -or- (2) I revoke the appointment of the individual named in Item 16A, either by explicit revocation or the appointment of another representative]`.

Do you authorize this accredited [attorney, claims agent, VSO] to change your address on VA records?
- Yes, they can change my address if it's incorrect or outdated
- No, they can't change my address

**Note:** You can cancel this authorization any time.


<details>
<summary>Content variation 1</summary>

## Scenarios
- A non-Veteran claimant is seeking help on behalf of a Veteran

## Recommendation for screen 1
[H2] Authorization to access Veteran medical records

This accredited [attorney, claims agent, Veterans Service Organization (VSO)] may need to access [Veteran's first and last name]'s medical records to help them get specialized health care services and treatments. You can authorize them to access all or some of these types of records:
- Alcoholism and alcohol abuse records
- Drug abuse records
- HIV (human immunodeficiency virus) records
- Sickle cell anemia records

Our records authorization policy
[Legalese from PDF] I authorize the VA facility having custody of `the Veteran's` VA claimant records to disclose to the `[service organization named in Item 15 -or- the individual named in Item 16A, and the firm/organization/individual(s)
named in Item 19 (if approved by VA for affiliated access)]` all treatment records relating to drug abuse, alcoholism or alcohol abuse, infection with the human immunodeficiency virus (HIV), or sickle cell anemia. `[Redisclosure of these records by `the` service organization representative, other than to VA or the Court of Appeals for Veterans Claims, is not authorized without my further written consent -or- Redisclosure of further written consent]`. This authorization will remain in effect until the earlier of the following events: (1) I revoke this authorization by filing a written revocation with VA; or (2) I revoke the appointment of the `[service organization named in Item 15 -or- individual named in Item 16A]`, by explicit revocation or the appointment of another representative.

Do you authorize this accredited [attorney, claims agent, VSO] to access the Veteran's medical records?
- Yes, they can access all of these types of records
- Yes, but they can only access some of these types of records
- No, they can't access any of these types of records

**Note:** You can cancel this authorization any time.

## Recommendation for screen 2 (if "yes, but" in screen 1)
[H2] Authorization to access Veteran medical records

You've authorized this accredited [attorney, claims agent, Veterans Service Organization] to access some of [Veteran's first and last name]'s medical records.

Select the types of records they can access
- Alcoholism and alcohol abuse records
- Drug abuse records
- HIV (human immunodeficiency virus) records
- Sickle cell anemia records

## Recommendation for screen 3
[H2] Authorization to change your address

This accredited [attorney, claims agent, Veterans Service Organization (VSO)] can help [Veteran first and last name] change the address on their VA records. If the address on their VA records is incorrect or outdated, it may take us longer to contact them and process their benefit claims.

Our address authorization policy
[Legalese from PDF] I authorize `[the individual named in Item 16A -or- any official representative of the organization named in Item 15]` to act on `the Veteran's` behalf to change `the Veteran's` address in `the Veteran's` VA records. This authorization does not extend to any other `[individual -or- organization]` without my further written consent. This authorization will remain in effect until the earlier of the following events: (1) I revoke this authorization by filing a written revocation with VA; or [(2) I appoint another representative, or (3) `the Veteran has` been determined unable to manage `their` financial affairs and the individual or organization named in Item 16A is not `their` appointed fiduciary -or- (2) I revoke the appointment of the individual named in Item 16A, either by explicit revocation or the appointment of another representative]`.

Do you authorize this accredited [attorney, claims agent, VSO] to change the Veteran's address on VA records?
- Yes, they can change my address if it's incorrect or outdated
- No, they can't change my address

**Note:** You can cancel this authorization any time.

</details>

**Comment by oddball-lindsay** [comment]
This seems to align nicely with what we have been discussing over in #80406 👍 

@mtri a heads up on these changes.  In stakeholder review I want to make sure we cover these scenarios and confirm the references to "your" vs. Veteran first/last name.

**Comment by aprocik1** [comment]
@oddball-lindsay and @mtri: Here's an update following our meeting earlier today: Lindsay will confirm with SMEs that we can move forward with only using content variation 1 for all scenarios. That means we can remove this question entirely from the form flow:

> Why are you appointing an accredited representative?

Here's the updated Appoint tool [source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EZEW15_B_ZlMnxSTps9Tt8cBci2c-iWZTidg0IM4Pk2jMw?e=tgZWOz). Find the most recent content for all the authorization screens on pages 17-22.

**Comment by aprocik1** [comment]
Update: The product team confirmed that SMEs are okay with only using content variation 1 for all scenarios. Here's the updated Appoint tool [source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EZEW15_B_ZlMnxSTps9Tt8cBci2c-iWZTidg0IM4Pk2jMw?e=tgZWOz). Find the most recent content for all the authorization screens on pages 17-22.
