### ISSUE TITLE
Burial | Create Data Flow Diagram

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80423]
## Issue Description
_For the [Readiness Review requirement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86756), we need to document the data flow of the burial form._

Requirements:
- What data is collected or used, and where, including information such as credentials used by this system?
- Where is the data is stored and how, including information such as any encryption used?
- How is the data transferred, including information such as any encryption used?
- Who accesses the data and in what capacity (read or read-write)?
- What is the audit trail of data access and manipulation?
---
## Acceptance Criteria
- [x] Documentation created and added to repo
- [x] Link to documentation added to #86756
---

**Comment by HeatherWidmont** [comment]
.

**Comment by HeatherWidmont** [comment]
.

**Comment by tblackwe** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/Burial%20Data%20Flow%20Diagram.png
