### ISSUE TITLE
Access for Steven Bair

### ISSUE THREAD

**Issue by sbair-va** [department-of-veterans-affairs/va.gov-team#8043]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Steven Bair
- Please Provide your email.
   > steven.bair@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API Development and Operations, Software Engineer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwAW35Hw+YqWuZr1Rq8PlSx8RDZHZctS9vDWbdg6KF4Zr0HTUmkoBpCFrdC46am9aME30ZW8clAZKXg/tpHXRMJBnTOOxTd0epbD12EENr+kuFNTbWvvWKvvfEE/YEuNFGKyQw5zIQcnTc+kLSvwRuNqLP4QCJDT01ZcKZTYhb9P/lwaBBxCnvfY9rgzgxOlWnyWniCTs3kVVcssmGKfCU7gptc1ck+ddOox5Q4Gjhl7TdCwspNCkCpSpOykmK248t8yWG8IbH7DkvjqVdiERxmVKbNJlxrw1vH7fHQhKTIbvDDq01OMitHi+14Dlo5zft0Gejb4H4+SKs7eiSaf4VOt9PBLxRe1QrjdyTKNtHt+IYa1I/kLfq4LugZy/IMdfXBf+QYURSeXby2JC8AtzoIOCCycuoq/bWKVqdNHsGXbYf6LgpKFwdgjzXZf48akJCSb92bJ0bpv4zwl/WyQ4xgcsREKE86DWLk+6YYnZXEl5LPCYMXA/K3YynZZgnTz8= AzureAD+StevenBair_vvvjkcf@DESKTOP-SBAIR
```

- [Grant AWS Console access?]
  >  NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by sbair-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
