### ISSUE TITLE
[spike] DR | Investigate how to download full history of failures

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#80442]
## Value Statement
**_As a_** VA staff member responsible for remediating supplemental claims or board appeals that silently failed
**_I want to_** know the exact nature of each types of transaction failure
**_So that_** I can create a remediation plan to make the Veteran's claim whole. 

---
## Background Context
- The VA staff responsible for supporting our remediation work will need info to identify affected Veterans, data, and potential next steps based on whether or not the Veteran is deceased. 

## Tech Tasks
- [x] Identify filters to use to find error logs in Sentry
- [x] Identify filters to use to find error logs in DataDog
- [x] Identify database queries needed to find missing / incomplete records
- [x] Identify who we need to pass the failure data to for further investigation
  - Can contact Alejandro Mendelioflores and John Gosnell to help us figure out exactly who will be working this data when we're ready
  - [ ] ~Identify what information about these failures they need (i.e. the data format that Alex has used with Thomas' team)~ Moving this to #81303 
- [x] Note any limitations on the data we can/cannot retrieve
  - Will have a gap in logging for any logs sent to Grafana
  - Need to rehydrate DataDog logs as we only have the last few months available

## Definition of Ready 
- [ ] Clear value description
- [ ] Data needs approved by the enablement team

## Definition of Done
- [ ] We've found ways to get the data we're looking for from logs and database records
- [ ] We know who our next point of contact is once we start to gather up data to hand off

**Comment by shaunburdick** [comment]
Meeting with Thomas and Annie today at 2pm EDT to discuss approach

**Comment by shaunburdick** [comment]
Spoke with Thomas and Annie, will setup meeting with Sam Stuckey next week to do some knowledge transfer.
We will need to know who is consuming this data. Alex Mikuliak (CorpDB) has in the past and would like the data in a specific format.

**Comment by shaunburdick** [comment]
Meeting with @tblackwe , @anniebtran and @SamStuckey is scheduled for 4/17 at 3pm EDT.

**Comment by saderagsdale** [comment]
@anniebtran is going to see if the devs can come up with scripts to pull all of the data.

**Comment by anniebtran** [comment]
Jotting notes on which filters to use in DataDog/Sentry and queries to use in the console to grab data [here](https://docs.google.com/document/d/1GxYoFA-kJRlY1pSOzbNUhHmv3rn7MqVZ1S_ZMzS7zN0/edit?usp=sharing)

**Comment by anniebtran** [comment]
Chatted with Thomas a bit more and wanted to note some limitations to what logs we'll be able to pull:
- Anything logged to Grafana (~late 2021 to late 2022) is not available because the logs expired and were purged.
- Everything else after Grafana is in DataDog but we will have to rehydrate DD for logs older than the past few months, will need specific queries to hand off to someone who can rehydrate them (also it costs $)

**Comment by anniebtran** [comment]
@shaunburdick I think I'm gonna move this item to the next task as it shouldn't _completely_ block us from starting to pull data:
> Identify what information about these failures they need (i.e. the data format that Alex has used with Thomas' team)

I think we can start with the more recent failures that have the most information available to us and then work backwards where there will probably be less we can access, and hopefully by the time we get to those we'll have a better idea of what data formatting we need

**Comment by anniebtran** [comment]
@saderagsdale [This ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81303) has the ancillary forms and evidence included in the AC and in the tasks — feel free to add any additional details there!
