### ISSUE TITLE
NOD & SC | Add maximum dimensions criteria

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#80446]
## Value Statement
**_As a_** Veteran
**_I want to_** submit evidence, which may include very large documents, for my NOD / SC
**_So that_** my appeal can be evaluated with all the information I believe is relevant.

---
## Background Context

As part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/74493, Veterans are blocked from uploading documents that exceed a certain dimension. Criteria is not listed ahead of time, which could cause friction with Veterans experiencing the error for the first time.  

## Test Notes and Design Links
- [FIGMA](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=387-7868&mode=design&t=NJdP53EHus4fKzrU-11)

## Acceptance Criteria
- [ ] User chooses to upload documents now and sees upload your additional evidence page
- [ ] User sees upload criteria/guidelines, including maximum file width and height information
- [ ] User sees error if file uploaded does not meet upload criteria/guideline

## Tech Tasks
- [ ] Update content

## How to Measure Success
_- Define the expected result and where to measure it._

## Out of scope
- Add here

## Definition of Ready 

- [ ] Clear value description
- [ ] Test cases defined
- [ ] Approved designs and success measure(s) included
- [ ] Sample data provided where appropriate
- [ ] Fits within the sprint
- [ ] Dependencies linked

## Definition of Done

- [ ] Test cases passed
- [ ] E2E testing updated
- [ ] Unit testing updated (90% coverage)
- [ ] Integration testing updated (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Status** (`Needs-Refinement`, `Needs-Estimate`, `discovery`, etc.)

**Comment by Mottie** [comment]
Ready for validation in staging
