### ISSUE TITLE
DR | Create a remediation plan for each category of failed submissions

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#80448]
## Value Statement
**_As a_** Veteran who submitted a claim on VA.gov that experienced a silent failure
**_I want to_** know that all data I shared was received and taken into account during claim development
**_So that_** my claim decision reflects the data I intended to share. 

---
## Background Context
Remediation plans, known as Code Yellows, will be created for all affected decision review types. This process typically involves: 
- Standing up a team of business line stakeholders to create a remediation plan and working group
- Resubmitting original data in batches using scripts
- Sending communications to Veterans so they're aware of the impact and next steps
- Getting stakeholder approval to close the effort

## Tech Tasks
- [ ] Discuss with Thomas Blackwell to check for existing CY processes/best practices
- [ ] Setup meeting with core stakeholder group to kickoff the process
- [ ] Join weekly code yellow scrum to share updates and identify support resources
- [ ] Determine what data needs to be re-submitted w/ business line
- [ ] Decide how to re-submit the data w/ the business line
- [ ] Confirm resubmission and data storage are complete w/ the business line

## Definition of Ready 
- [ ] We've documented the exact nature of all of our silent failures

## Definition of Done
- [ ] All failures have been remediated
- [ ] Reviewed and approved by product owner

**Comment by shaunburdick** [comment]
This will be ready once we meet with the VBA/BVA teams and generate a playbook

**Comment by eileen-coforma** [comment]
Met up with VBA and BVA last week, pulled the latest failures other than the silent ones that we can't control. Set up a process for remediation in the future.

**Comment by eileen-coforma** [comment]
Sent over some more silent downstream failures for SC and HLR and added to spreadsheet to let the teams know.

**Comment by eileen-coforma** [comment]
Cory wants a meeting with Annie and Derek to figure out the playbook for different kinds of errors and remediation plans

**Comment by eileen-coforma** [comment]
Annie is documenting all the steps we're currently taking

**Comment by eileen-coforma** [comment]
Went over documentation on error triaging, and current processes for remediation, reviewed with Amy and Cory. Continue to chip away. Document link will be added.

**Comment by eileen-coforma** [comment]
@anniebtran to add link to the documentation on this in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/engineering

**Comment by anniebtran** [comment]
Link to the google doc: https://docs.google.com/document/d/1xurTI-XFIcMk67OPpjxPJzQr-fz_MAhcBkyNsMgvONU/edit

Will work on adding to our github docs 👍

**Comment by eileen-coforma** [comment]
Cleaning up the repo of documentation in GH, and adding the WIP from the Google Doc

**Comment by anniebtran** [comment]
Cleaned up the [Monitoring Handbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/engineering/Monitoring%20Handbook.md) in GH a little bit. Still working on moving over the WIP from the Google doc but I've started added some of it [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/engineering/Remediation-Process-WIP.md)

**Comment by anniebtran** [comment]
WIP Remediation documentation has been moved into [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/engineering/Remediation-Process-WIP.md)

**Comment by Mottie** [comment]
We're going to open a subsequent ticket.

**Comment by anniebtran** [comment]
Link to follow-up ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/93459
