### ISSUE TITLE
[FE] 10-10EZR TERA Questions: BUG: Fix TERA Questions not showing up

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#80456]
Repro Steps: 

1. Login
2. Go to EZR
3. Go through EZR to TERA Questions
4. Expected: Bullets explaining the exposure
5. Current: No explanations for the exposure

**Comment by mkerns1** [comment]
Update:

PR rollback was successfully launched and deployed/tested. This ticket can be closed.
