### ISSUE TITLE
As a VFMP applicant, I need the systems that handle my application to talk to each other

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#80482]
As a VFMP applicant, I need the systems that handle my application to talk to each other so that it's possible for me to receive a complete status for my application after I submit it.

### Acceptance criteria

Given a submitted application from VA.gov
   - When the application is picked up by the IVC team for processing. 
     - Then the IVC team can notify VA.gov that the application is being processed. 

Given an application submitted from VA.gov
   - When IVC has attempted to import the application to PEGA. 
     - Then PEGA can notify VA.gov of a successful or failed import of the application. 
     - And PEGA can notify VA.gov of a successful or failed import for each supporting document. 
     - And PEGA can notify VA.gov when the application was handled. 
     - DOCMP can receive confirmation of successful call
     - DOCMP can receive confirmation of well-formed payload

### Engineering notes:
- Create endpoint nomenclature
- Accept payload
- Return a mock status
- DOCMP can confirm connectivity
- Can skip validation in staging

**Comment by balexandr** [comment]
@baltes This ticket is currently in PR but it can't be merged due to it having no auth. How would you like to rework this ticket? Should we put it back in progress until SiS is set up and adjust the AC?

**Comment by baltes** [comment]
Development is blocked while we get auth patterns set up with platform. If this remains blocked at EOD today, we'll alter the story and close it out, then move remaining work to a new story. Premal and Bo have next steps to follow up with platform.

cc @balexandr

**Comment by balexandr** [comment]
This has been approved and tested by myself and Trevor. It's awaiting platform review before being pushed up to staging. I've updated the implementation doc with how to generate the token locally.

**Comment by balexandr** [comment]
@baltes This has been merged into master

**Comment by balexandr** [comment]
This can be closed.

**Comment by baltes** [comment]
[Uploading... callback test staging.mov]

**Comment by baltes** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/assets/1290901/259ed97b-2398-4904-8064-d1e942107528
