### ISSUE TITLE
Log submitted data for failed appointment POSTs

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#8048]
We should include the submitted appointment data when appointment or request POSTs fail in Sentry. We can add this to the extra data field Sentry allows.

We'll need to remove:

- email
- phone
- additional information text

from the data we log, to avoid PII. It would be nice to replace those three fields with some metadata, like the length of the data in that field or something.

**Comment by lenaecb** [comment]
Delay until we see what happens with tracing on backend.
