### ISSUE TITLE
New VFS Team Member Template [Lisa Capaccioli]

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#80496]
## Welcome and Introduction
Welcome to the Department of Veterans Affairs (VA) Veteran Facing Services (VFS) team!

As a new VFS team member, you will be working in the web ecosystem we call the VA.gov Platform (or "**The Platform,**" for short).  The tasks on this list are designed to get you up to speed on the role of Platform, making it easier for you to do your job.

Because the VA is a huge organization that serves millions, the Platform it runs on is equally big, complex, and multilayered. Most people find that even learning the basics for their own practice area entails a significant learning curve.  The tasks on this checklist will help you acquire those basics as quickly and efficiently as possible.

## User Story
As a new VFS team member, I need to complete onboarding activities so I can successfully work on my project and support the VA.gov Platform.

## How to fill out this ticket
- [x ] Add your name to the ticket title
- [ ] Complete the Onboarding Checklist below
- [ ] Under **Get set up for your practice area,** you only need to complete the items for your role
- [ ] You can close this ticket when all items are completed in the Onboarding Checklist and the Platform Checklist

### Share your info with Platform
- [ ] Complete the fields below:
 - Name: Lisa Capaccioli
 - Pronouns (e.g. she/her): she/her
 - Role: Product Manager
 - Email: lisa.capaccioli@coforma.io 
 - GitHub handle*:  lisacapaccioli
 - Start date: 4/8/2024
 - VFS Team: DSVA Non Disability Claims (Pension and Proactive Benefits)

*Providing your GitHub handle will allow Platform to provide you access to the necessary GitHub repos.

### General

- [ ] Watch the [General orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Generalorientation) recording
- [ ] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)
- [ ] Watch [VA.gov overview video](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Purpose) for an overview of VA.gov
- [ ] Watch [VFS Orientation for Platform Website video](https://www.youtube.com/watch?v=yzl6nyLmqkA&ab_channel=PlatformCrew)
- [ ] Watch the [Platform Support overview video](https://www.youtube.com/watch?v=iwIQU4XepNQ)
- [ ] Review the [Getting help from the Platform in Slack guidance](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack)
- [ ] Review [Welcome](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html) documentation
- [ ] Review [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html) documentation
- [ ] Review the guidance on [Submitting a feature request](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html)
- [ ] [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
- [ ] Confirm that you have access to the [VA GitHub Organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization)
   - **Note:** Membership in the VA Github Organization is a prerequisite for getting access to `vets.gov-write` and access to many commonly-used repositories. Platform will not be able to complete this task if you are not a member of the VA GitHub Organization.
- [ ] [Opt out of Google Analytics](https://www.va.gov/analytics-opt-out.html) on all of your browsers on your work machines, personal machines (if you are not a Veteran yourself using the site for your own applications), and mobile devices
### Norms and standards
- [ ] Review guidance on the [Platform Satisfaction Survey](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey)
### Working on the platform
- [ ] Review the [Platform Principles](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-crew-principles)
- [ ] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [ ] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/digitalmodernizationstrategy.pdf)
- [ ] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/the-new-va.gov-briefing-2019-07.pdf) documentation
- [ ] Review the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) documentation on Platform Website
- [ ] Are you a Veteran? Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document

### Get set up for your practice area
- [ ] Review the [Research and Design Guide on Platform Website](https://depo-platform-documentation.scrollhelp.site/research-design/index.html)
- [ ] Learn how we do [research at VA](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)
- [ ] Watch the [getting started with design videos](https://depo-platform-documentation.scrollhelp.site/research-design/getting-started-with-design)
- [ ] Get oriented to the [Design System](https://design.va.gov/)
- [ ] Get oriented to the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [ ] Watch the [Design orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Design&researchorientation) recording
- [ ] Watch the [Accessibiliy orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) recording
- [ ] Review [frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [ ] Watch the [Front-end orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Front-endorientation) recording
- [ ] Watch the [Analytics orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Analyticsorientation) recording
- [ ] Watch the [Accessibility orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) recording
- [ ] Watch the [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAorientation) recording
- [ ] Watch the [Design System/Forms Library orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Designsystem/formslibraryorientation) recording
- [ ] [Schedule a PM intro via Calendly](https://calendly.com/collaboration-cycle/product-manager-intro) with Shira Goodman (Platform Governance Team PM).
- [ ]  Watch the [Analytics orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Analyticsorientation) recording
- [ ] Watch the [Accessibiliy orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) recording
- [ ] Watch the [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAorientation) recording

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [x] New VFS team member has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)
- [x] New VFS team member has been added to the vets.gov-write GitHub team

**Comment by sortizsh** [comment]
workin on it!

**Comment by AnthonyWFlowers** [comment]
Greetings @sortizsh Just checking back in to see if you were able to get the github name- we will move forward as soon as we receive the information

**Comment by sortizsh** [comment]
added above, but she has not be added to GH org yet

**Comment by AnthonyWFlowers** [comment]
Thank you @sortizsh  Currently Lisa (github handle: lisacapaccioli) does not yet have access to the VA Organization on GitHub. Please follow the [Getting access to the VA GitHub organization guidance](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-GettingaccesstotheVAGitHuborganization) Once completed, comment on this ticket and Platform will grant you access to the necessary GitHub repos.

**Comment by AnthonyWFlowers** [comment]
Greetings @sortizsh the user must be a member of the VA GitHub Org before proceeding on this request. We are closing this out, but asking you to re-open once the user has been added to the org. 

Thank you.

**Comment by sortizsh** [comment]
Hi @AnthonyWFlowers  she has been added to the org now, can you please proceed? thank

**Comment by AnthonyWFlowers** [comment]
Greetings @sortizsh We will continue the process. Thank you for the update!

**Comment by AnthonyWFlowers** [comment]
Greetings @sortizsh to confirm before adding this user to the group in Atlas I see DSVA as "DSVA Non Disability Claims (Pension and Proactive Benefits)" 
Would this be the correct choice for Lisa?

**Comment by sortizsh** [comment]
yes that's the one! thank you
@AnthonyWFlowers

**Comment by AnthonyWFlowers** [comment]
Added to Atlas

**Comment by AnthonyWFlowers** [comment]
Platform Checklist Complete
