### ISSUE TITLE
AWS access for [David Petras]

### ISSUE THREAD

**Issue by davidpetras** [department-of-veterans-affairs/va.gov-team#80497]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

David Petras

### Your Email

david.petras@adhocteam.us

### Team, Role, and Company of the target individual

Platform Technical Support, Technical Support Specialist, Ad Hoc LLC

### Product Manager (PM) name and email

Alyssa Gallion | alyssa.gallion@oddball.io

### Product Owner (PO) name and email

Erika Washburn | Erika.Washburn@va.gov

### Desired AWS Access

Brandon Dech or Lindsay Insco are my peers for mirroring access.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1278" alt="Screenshot 2024-03-29 at 3 42 51 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/161384139/8767e23c-3314-4b31-8a5a-04e16fba9ebc">

### Additional Notes

New employee onboarding for Platform Tech Support team.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
> Brandon Dech or Lindsay Insco are my peers for mirroring access.

Neither of your peers have AWS access. I will discuss this with the Support team to see what level of access is needed.

**Comment by davidpetras** [comment]
@ph-One Thanks for looking into it, it was on our onboarding checklist however it turns out we do not need access. Feel free to cancel that request and close this ticket. Thank you!

**Comment by ph-One** [comment]
@davidpetras thanks for the quick reply. Closing the issue.
