### ISSUE TITLE
Troubleshooting in BigQuery - VANotify: Report - BQ - VANotify PROD STATS LastActivity Report

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#80503]
### Description
This ticket is track the work being done on the Report - BQ - VANotify PROD STATS LastActivity Report

> "I wanted to reach out on the BG pull for VA Notify, as it appears to be off by a day since 3/11/2024. The last day that it was pulled accurately was on 3/8/2024. Please see attached. Is there any way that we can remedy this to be same day pulls?"

---

### Task
- Review the Report to understand what platform is producing it
- Review the platform scheduling features to understand why the dates are incorrect
- Update the scheduling configuration
- Test the result to confirm the fix

### Acceptance Criteria

- [x] The report shows the correct date
- [ ]  The report process is documented in confluence

**Comment by dorseypa1** [comment]
The report is generated by the Domo platform.  This is eident by examining the FROM email address.  The Domo dataset used to generate the report is BQ - VANotify PROD STATS LastActivity.  The scheduled report is connected to and accessed from the card also named BQ - VANotify PROD STATS LastActivity.

**Comment by dorseypa1** [comment]
The issue seems to be due to the refresh of the data set completing at 11:06 AM while the report is scheduled to send at 11:00 AM.  Due to the timing of the start of the issue I suspect day light savings may have caused the issue.  I will fix it by moving the data set refresh an hour earlier.

**Comment by dorseypa1** [comment]
The report run on 4/11/2024 displays the correct dates in the report sent to my email.  <img width="1359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bda48c06088819e3e54c3dc58cbf9d058889b918/image.png" alt="image.png" />
