### ISSUE TITLE
Inventory headers and global navigation across VA ecosystem

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#80505]
Follow-on from [defining IA for ARP tool ticket](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/71256), this issue is meant to capture any work understanding design patterns across subdomains in the VA ecosystem. Some work in this vein was already completed to define and design a rough footer for the ARP prototype

### Output
- [x] [Inventory](https://docs.google.com/spreadsheets/d/12Qptv4-IhAeBvj5ppyZM7af_yYaKtcLYbjdoDIGLTbc/edit#gid=0) of required global and utility header links
- [x] Addition of header inventory to [IA mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710857598969/32219746df15eb2602a01b1b3b1b3ccf9fa8760d?sender=u503219bf4e47eab9c75d3838)
- [ ] Wireframe of recommended global and utility header for ARP

### Resources
See links above

**Collaborators**
- Name
- @RenataKeck 

### Acceptance criteria
Global and utility header meet VADS or USWDS standards and the specific needs of ARP users.

**Comment by kristen101606** [comment]
Here's a list of subdomains that we're aware of. Some of them clearly haven't been updated in a while and might even be getting phased out. 

- https://www.innovation.va.gov/hil/home.html
- https://www.pathfinder.va.gov/
- https://vethome.va.gov
- www.myhealth.va.gov 
- www.ebenefits.va.gov
- www.accesstocare.va.gov
- www.gibill.va.gov/wave
- https://news.va.gov (previously www.blogs.va.gov)
- www.data.va.gov
- mobile.va.gov
- digital.va.gov (previously www.oit.va.gov)
- https://department.va.gov

**Comment by RenataKeck** [comment]
Had a conversation about the utility header and menu considerations during our [design sync](https://docs.google.com/document/d/1Si-7U_CtMSHoPb3moqa9BWeiQXPwzRyJWmAW5f3Wlb0/edit) on 4/15/24

**Comment by kristen101606** [comment]
[Inventory of header content](https://docs.google.com/spreadsheets/d/12Qptv4-IhAeBvj5ppyZM7af_yYaKtcLYbjdoDIGLTbc/edit#gid=720719514) across VA subdomains

**Comment by RenataKeck** [comment]
Pause on creation of wireframes until after testing ends.
