### ISSUE TITLE
VSR conversation guide and shadowing findings: incorporate feedback

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#80511]
[Link to conversation guide for reference](https://docs.google.com/document/d/1Rz4jFF_p9mDU29WzManXVcMvCMODtmLy1BjNiNxmYFk/edit)
 

- [x] Elicit feedback from the team on conversation guide
- [x] Incorporate edits
- [x] Conduct interviews
- [ ] Review all interview transcripts and provide summary of findings with next steps and recommendations 
- [ ] Review findings and recommendations with team
- [ ] Speak to VBA/SME about questions from the research
- [ ] Post research materials to research ops board for approval/visibility

Acceptance Criteria/To Do

- summarize findings and recommendations
- discuss with team and propose initial prioritization
- share findings more broadly

**Comment by djones2113** [comment]
Had a meeting with Dene and Shannon to discuss the direction of the research. After this discussion, we decided that adjusting the research plan and conversation guide to reflect changing this research to more of a shadowing study rather than an interview.

Given the changes in priority, we should move this ticket to the backlog to revisit after onboarding of new forms (0969 and 8416) has been completed.

**Comment by aplatt-coforma** [comment]
Backlogged due to prioritization shifts

**Comment by Allexelaw** [comment]
Incorporating findings and questions from the VSR Shadowing research into Mural Board. Mural Board was shared with VBA SMEs Dan Gifford and Brianna Mullins.  Next step is a meeting with VBA SMES to discuss questions and comments.  @aplatt-coforma suggest keeping this ticket in progress
