### ISSUE TITLE
Remove accordions and create clear information hierarchy

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80534]
As a Proofing Agent, I need to see information right away so I can quickly verify a Veteran's identity without clicking through too many prompts.

AC

- [x] Remove accordions
- [x] Format information from accordions in a hierarchy that reduces cognitive load
- [x] Come up with design rationale and share when asking for review
- [x] Conduct review

**Comment by JKG199** [comment]
draft for design revisions [here ](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3609%3A20846&mode=design&t=5Op87xYXedyH566n-1)

Would like to share out/review which option to go with with other designers and devs @skirkman16

**Comment by skirkman16** [comment]
shared in devign sync and option for hierarchy was chosen. a11y tests in progress.

**Comment by skirkman16** [comment]
@JKG199 will update screens with accordions by Friday 4/19 and @skirkman16 will review. @mateoclarke said that the engineering ticket for implementation of this update will be an estimate of "1"

**Comment by JKG199** [comment]
@skirkman16 ready for review here. [https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3609%3A20846&mode=design&t=ltY8SAQLQde5pbW1-1](url)

**Comment by skirkman16** [comment]
<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c6bc685e4b686327d8e4d51f9ba4786ca2f6f8d/Screenshot%202024-04-22%20at%208.56.52%20AM.png" alt="Screenshot 2024-04-22 at 8.56.52 AM.png" />

Reviewed and accepted changes. Latest changes are under page "Post PA UT Prototype 4/19/24."
