### ISSUE TITLE
Update PA Enter case number Screen

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80533]
As a Proofing Agent I want to know what a case number is so that I can make sure that I am asking for the right requirement from the Veteran for verification.

## AC

- [x] Provide PA’s more context surrounding case numbers
- [x] Spellcheck
- [x] Review

**Comment by CarlDickerson** [comment]
@SophiaPhilipMO tagged for review

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson gave feedback, let me know when the version of the docs are broken out so we can compare the PIlot 1 content versus the post pilot content
