### ISSUE TITLE
Update PA Fill in information Screen

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80531]
As a Proofing Agent, I want to know what the format is for my form field inputs so that I can make sure that I am entering the Veteran's information into the application correctly.

## AC

- [x] Provide guidance on SSN (dashes or no dashes) and DOB data entry
- [x] Sync w/ and finalize field box formats in devign sync

**Comment by JKG199** [comment]
I have added this frame with design notes and questions [here ](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3609%3A20846&mode=design&t=XywljEhYZJkiRWDL-1) with the title Fill in information screen. 

@skirkman16

**Comment by JKG199** [comment]
updated interim screen in screenshot below.  updates not required for P1 

<img width="583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE56QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3984ea7995d48ad9a59ed2bc0a21296ebe31f78/Screenshot%202024-04-18%20at%2010.49.07%20AM.png" alt="Screenshot 2024-04-18 at 10.49.07 AM.png" />

**Comment by skirkman16** [comment]
<img width="584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7412873e5b4554ad40630dfd41ca6e6ba032096/Screenshot%202024-04-22%20at%208.51.29%20AM.png" alt="Screenshot 2024-04-22 at 8.51.29 AM.png" />
Reviewed and added in text for Day, Month, and Year. All other revisions have been accepted.
