### ISSUE TITLE
Update PA Email confirmation Screen and content for emails

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80532]
As a Proofing Agent, I want to make sure that the Veteran is informed verifying their email at the appointment so that I can efficiently verify them.

## AC

- [x] Provide more context on why we are asking to confirm email address at this step for proofing agents
- [x] Write a foolproof script so that PAs do not give away the email they are trying to verify
- [x] Reiterate in confirmation email and reminders that Veterans will need to verify their email address at the VAMC

**Comment by CarlDickerson** [comment]
Tagging @SophiaPhilipMO for review https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson reviewed and added edits/comments. Let me know when the versions are broken out for pilot 1 and post pilot
