### ISSUE TITLE
(HIGH) - Path traversal in webpack-dev-middleware

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#80546]
# Description
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/146

# Acceptance Criteria
- [x] `webpack-dev-middleware` has been upgraded to a patched version and dependabot is no longer flagging it

**Comment by IGallupSoCo** [comment]
Issues is now flagged as fixed by dependabot.
