### ISSUE TITLE
(HIGH) - http-cache-semantics vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#80579]
# Description
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/107

# Acceptance Criteria
- [ ] `http-cache-semantics` dependency has been upgrade to a patched version and dependabot is no longer flagging it

**Comment by pjhill** [comment]
Dependency map --

yo 4.3.1 --> got 8.3.2 --> cacheable-request 2.1.1 --> http-cache-semantics 3.8.1

**Comment by pjhill** [comment]
I forked yeoman and tried to upgrade to got 11.8.6. It's not going great so far -- https://github.com/pjhill/yo-vets-website/actions/runs/8712152609/job/23897813492

I might try a lesser version.

**Comment by pjhill** [comment]
npm lock files changed formating at npm v7. Retrying the whole process with npm 7.24.2 running the installation process in order to create minimal lock file differences.

**Comment by pjhill** [comment]
I got a successful run of the yeoman CI by using got9, however merging from main broke it again. I'm not sure what's going on here -- https://github.com/pjhill/yo-vets-website/actions/runs/8712366250

**Comment by IGallupSoCo** [comment]
Successfully merged PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/29215
