### ISSUE TITLE
Investigate user error

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#80572]
An engineer from the MHV team is having issues with a user on staging.va.gov. Please investigate what is happening to the user referenced by this request id:
<img width="1431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8f6ac96f53704b0bb15bbb66ef166e8aa40c5a1/image.png" alt="image.png" />

**Comment by dickdavis** [comment]
Request ID: 92da4ca2-f8ae-4fd5-b00f-e85d789d2ac9

DD Search: https://vagov.ddog-gov.com/logs?query=92da4ca2-f8ae-4fd5-b00f-e85d789d2ac9%20&cols=host%2Cservice&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1712246904611&to_ts=1712851704611&live=true
