### ISSUE TITLE
[Credibility] User encounters content that does not align with VA.gov voice and tone content principles.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80586]
_This ticket was generated during the pilot process for the new VA.gov experience standards. Please tag `@platform-governance-team-members` on Slack if you need assistance interpreting this ticket._

## Product Information
**Team:** Benefit Tools
**Product:** Claim Status Tool
**Feature:** Improved Evidence Request Initiative

## Findings details
**VA.gov Experience Standard - issue:** User encounters content that does not align with VA.gov voice and tone content principles.
**VA.gov Experience Standard - category:** Credibility
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design), @rferguson13 (Content)

### Description

On the file upload page, per [our guidance](https://design.va.gov/patterns/ask-users-for/files#content-considerations) you should use the "upload" instead of "add". And use the word "delete" instead of "remove".

## Recommended action

Change the button to "Upload file" and "Delete file". Move the delete file button down to the bottom left of the gray card.

## References

- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** [Files](https://design.va.gov/patterns/ask-users-for/files)
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A
- **Accessibility Defect Severity:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by jacobworrell** [comment]
@shiragoodman noting that the new file upload component we're migrating to does not conform to the standards you gave us as feedback https://github.com/department-of-veterans-affairs/va.gov-team/issues/87835

[Link in storybook to component.](https://design.va.gov/storybook/?path=/docs/uswds-va-file-input--default)

**Comment by shiragoodman** [comment]
Thanks @jacobworrell . Tagging @allison0034 for her input. Allison, could you take a look at the file upload component and the feedback within this ticket? I'd be curious to know where the inconsistencies are.

**Comment by allison0034** [comment]
@jacobworrell if you are using the component you linked above then you should be good, it is the most current (v3) version. It does use "upload" and "delete" as we suggested. Be sure to check the other content to make sure it matches.
