### ISSUE TITLE
Edit content for 1st platform newsletter

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#8058]
## User Story

As a recipient of the first platform newsletter, I want to be able to read and understand the content, so that I can focus on the important updates contained within. 

## Description

Work with Service Design team to copy edit and suggest content edits as needed to the first platform newsletter.

**Comment by kristinagore** [comment]
We will edit the newsletter once it's ready, but the scope has expanded to include updates to docs as well. We'll continue collaborating with service design team.

**Comment by kristinagore** [comment]
Updated https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/front-end-standards/manual-reviews/ and Gretchen provided Mailchimp support for newsletter. We'll edit the newsletter once it's ready to go and will continue collaborating with Service Design.

**Comment by meganhkelley** [comment]
Initial VSP newsletter! https://us19.campaign-archive.com/?e=%5BUNIQID%5D&u=6e3ab59c527a3cc8ef560eeb5&id=cc381ab531
