### ISSUE TITLE
[QA] Profile 2.0 Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8059]
## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

Product/Feature Outline: [GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)
Product/Feature Epic: #2086
Product/Feature Pre-Launch Checklist: [Github doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)
Product/Feature Design artifacts: [InVision screens](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens)

## Product-team SMEs

\[List points-of-contact (just full names) for all involved Subject-Matter domains.  Most often, these would be the relevant development-team members (Product Manager, UX Designer, Front-End Developer, & Full-Stack or Back-End Developer]
Product Management: Matt Shea
Design/Research: Tressa Furner
Front-end: Erik Hanson, Sandra Hallie
Back-end: Lihan Li
QA: Tze-chiu Lei

## Proposed user-scenarios and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs.  IMPORTANT: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Test cases will be built along two dimensions:
1. User Levels of Access (LOAs):
    - LOA1
    - LOA3
2. Profile content/functional areas:
    - Account Security
    - Connected Apps
    - Military Information
    - Direct Deposit
    - Personal Information

\[See [Test Cases Matrix](https://github.com/department-of-veterans-affairs/va.gov-team/files/4898992/Profile.Test.Cases-Staging.Users.xlsx) for full details]

In TestRail, to support maximum test-run efficiency, test cases will be organized under LOA-specific sections, with specific test cases mapping to the content/functional areas.  Where appropriate, some Matrix cases will also be combined into a single, larger TestRail case.

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
TESTING, TESTING... Tagging myself to test where the auto-emails go...  @tzelei @tlei123

**Comment by tlei123** [comment]
TESTING... tagging @mshea0606 .

**Comment by mshea0606** [comment]
[Profile Test Cases-Staging Users.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4898992/Profile.Test.Cases-Staging.Users.xlsx)

**Comment by tlei123** [comment]
@mshea0606 , since most test-cases have been run. I've generated the reports for our Staging Review scheduled next Tuesday, so that @pjhill can at least review what's completed.*

TestRail links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/196)
- [Coverage for References (Cases)](https://dsvavsp.testrail.io/index.php?/reports/view/122)
- [Summary (Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/123)

*Pls. let me know once you have the answers to those yellow cells in my QA test-cases Google Sheet.  Thx much!
