### ISSUE TITLE
BUG - Vet w/ multiple 200CORP/200MH in MPI

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#80614]
***High-priority bug fix

VA database issue that’s causing sign-ins to fail on VA.gov. 

VA.gov blocks access to Veterans who have more than one 200CORP (VBA Corp) correlations in the MPI system. We believe this also happens if the Veteran has more than one 200MH (My HealtheVet) correlations in the MPI system.

Our idea is to remove this block and allow users to log in or change the error message so that it is clear. These users can log into My HealtheVet with no issue. 

Note***I read the encrypted email related to this which gives specific use case, but I believe the above is enough background for us to correct the issue.  If needed, I can absolutely give details of the email.

**Comment by joeniquette** [comment]
After discussing with Tom directly on 4/11 I believe we are going to leave both blocks in place. @kingbmike
