### ISSUE TITLE
VistA Scheduling Provider (/vsp/v1) Staging Testing

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8061]
Opening issue to track any of our testing activities for latest release of VistA Scheduling Provider v1

Organization:
- [x] Can make a request and get a non-error response
- [x] Can make a request with our expected params and get a usable response
   - EAS ticket created for pulling multiple organizations at once

Location:
- [x] Can make a request and get a non-error response
- [x] Can make a request with our expected params and get a usable response

HealthcareService:
- [x] Can make a request and get a non-error response
- [ ] Can make a request with our expected params and get a usable response

Schedule (N/A)

Slot:
- [x] Can make a request and get a non-error response
- [x] Can make a request with our expected params and get a usable response

Patient:
- [x] Can make a request and get a non-error response
- [x] Can make a request with our expected params and get a usable response

Appointment:
- [x] Can make a request and get a non-error response
- [x] Can make a request with our expected params and get a usable response
- [x] Can POST and get a non-error response
- [ ] Can PUT (cancel) and get a non-error response

**Comment by jbalboni** [comment]
Examples so far: 

https://veteran.apps-staging.va.gov/vsp/v1/Organization?identifier=983,984
https://veteran.apps-staging.va.gov/vsp/v1/Location/393833
https://veteran.apps-staging.va.gov/vsp/v1/HealthcareService?organization.identifier=983&_include=HealthcareService%3Alocation
https://veteran.apps-staging.va.gov/vsp/v1/Appointment?patient:Patient.identifier=1012845331V153043&date=ge2020-05-01T07:00:00Z&date=lt2020-08-31T17:00:00Z&_include=Appointment:location
