### ISSUE TITLE
Create a content doc for IPP prototype screens

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80627]
As a UX content strategist, I need to write content for a prototype in a doc to work iteratively and check for spelling and grammar.

## AC

- [x] Create and link google doc to ticket
- [x] Break out each screen into their own sections so content can be iterated on

**Comment by CarlDickerson** [comment]
@SophiaPhilipMO here is a link to the content document that I have put together for the IPP Prototype https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit?usp=sharing

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson feedback added

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson since there are other tickets that impact this as well, let me know when you've updated and I'll review again
