### ISSUE TITLE
Flipper UI access for Mitch Saltykov

### ISSUE THREAD

**Issue by Mitch-A6** [department-of-veterans-affairs/va.gov-team#80620]
### Your Name

Mitch Saltykov

### Your GitHub handle (Flipper UI access is managed through GitHub)

@Mitch-A6

### Team, Role, and Company of the target individual

10-10 Health Apps, Senior Full Stack Engineer, Agile 6

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

As part of the Health Enrollment team, I need Flipper access in all environments to see and change feature flag values for releases.

According to @hdjustice, I show up in Atlas for her (see attached screenshot from a month ago when I successfully applied for production Agro access) even though I can't seem to find myself in the system. Not sure why that is.

![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/153661030/5c36a721-860d-4504-86af-c8e136531d3b)

**Comment by davidpetras** [comment]
Access to lesser environments and Production has been granted
