### ISSUE TITLE
Add notes to 3 docs containing google links

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#80621]
Add notes to the top of the following documents, explaining how there are google links in them that aren't accessible within the VA network and we're working on it:

1. [Successful Screener Questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions)
2. [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)
3. [Research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)

## Acceptance Criteria
The following 3 documents have been deployed with appropriate notes at the top
- [x] 1. [Successful Screener Questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions)
- [x] 2. [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)
- [x] 3. [Research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)

**Comment by jknipes** [comment]
work completed, moving to _done_
