### ISSUE TITLE
(Figma) Update design files fields that require other explanation

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#80636]
## Background
We recently complete this staging review ticket that required us to add more explanation text for the fields that say "Please specify" when the "Other" radial button is selected. The dev ticket was complete and went beyond what was initially created asked for with respect to Income Sources. 

## Acceptance Criteria

- [x] Update Figma file to match what's on Staging/PROD for the Marriages > How did you get married? field
- [x] Update Figma file to match what's on Staging/PROD for the Spouses former marriages > How did the marriage end field?

## Notes
You can reference this PR to see screenshots of what the updates look like: 
https://github.com/department-of-veterans-affairs/vets-website/pull/29070

**Comment by echin393** [comment]
The Figma file reflected the latest changes for income sources but has now been updated to display the copy in production asking Veterans to tell us how they got married or how their marriage ended.
