### ISSUE TITLE
Isolate pension application for CI on vets-website

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#80641]
# Overview
Flakey test cases from other groups have been a constant source of slowdown for our team.  Moving the pension application to the isolated app-builds allowlist will help our group out significantly.

# Tasks
Modeling what was done in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71072), add our application to the isolate app-build list.  We want to be sure that we are not doing continuous deployment right now because it will only worsen our data definitions issues.
An example of turning off CD is here:
https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json#L36C5-L40C7

**Comment by sanjabaj2** [comment]
Just thinking out loud after looking at implemented #71072 ticket. Should steps 1 and 2 be done every time before the build? While we checked for cross import dependences and Megamenu at the time of deciding to allow for stand alone build, things could have changed later on? Does this make sense?

**Comment by ToddWebDev** [comment]
@sanjabaj2 According to the [documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/functionality-of-building-isolated-applications#Functionalityofbuildingisolatedapplications-Testing) the pension isolated app build will automatically run the Megamenu cypress test in addition to the suite of pension unit tests and e2e tests. The `check-app-imports` step will not be automatically run, however importing dependencies from other apps is discouraged so this shouldn't be something we have to regularly check for.

**Comment by sanjabaj2** [comment]
Is there a PR for this ticket? What exactly was done? Just added pension app to isolated app-builds allowlist? Are we building pension app independently from now on?

**Comment by ToddWebDev** [comment]
The associated PR is connected to this issue: https://github.com/department-of-veterans-affairs/vets-website/issues/29307
