### ISSUE TITLE
As a VFMP applicant, I need my supporting documents routed correctly according to their type

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#80644]
As a VFMP applicant, I need my supporting documents routed correctly according to their type so that all of my documents are processed as smoothly as possible.

### Acceptance Criteria
Given an application submitted by a CHAMPVA applicant
- When the user submits
- Then the form and each supporting document are sent as individual files
- And each file has its document type included in its metadata

Given a supporting document submitted with a VFMP form
- When the user selects a document type in the dropdown of the upload screen
- The uploaded document should have the user-selected doc type mapped to its metadata

**Comment by baltes** [comment]
@cloudmagic80 I modified the AC for this story, let me know if this still matches your understanding.

**Comment by cloudmagic80** [comment]
<img width="1289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efae8416e6035ea4bee7eded5f3b6cfebdaf3abe/Screenshot%202024-05-13%20at%201.25.31%20PM.png" alt="Screenshot 2024-05-13 at 1.25.31 PM.png" />

**Comment by cloudmagic80** [comment]
The supporting documents will be called "x-amz-meta-attachment-ids"

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/16726

**Comment by cloudmagic80** [comment]
@baltes This works for 1010d. The other forms will need to label their attachments specifically `applicants"=>  and "applicant_supporting_documents"=>`
