### ISSUE TITLE
Add custom GA analytics events on secondary nav

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#80654]
# Description

### User story

As a Cartography team member, I want clicks 

### Notes
- Propose custom event format/scheme that begins with `Navigation - ` and run it past Jamie Stutt (Analytics team) before implementing
  - example from megamenu: `Navigation - Header - About VA health benefits - https://staging.va.gov/health-care/about-va-health-benefits`
  - PROPOSE: `Navigation - MHV secondary nav - [link text] - [link url]`

Possible tasks:
- File [an analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) as soon as you pick up the ticket, to initiate collaboration. They know that this is coming and it's a high priority. 
  - Launch/target date is 5/23/24

## Acceptance criteria

- Google analytics events fire on secondary nav clicks, with naming convention approved by Analytics team
- Verified using AdSwerve that breadcrumb links on tool pages already have a GA click event (or else ticketed if that is not the case)
- QA review

**Comment by radavis** [comment]
The "formatting" that is seen within Google Analyitcs looks to be an example of a `nav-header-link` event.

```js
recordEvent({
  event: 'nav-header-link',
  'nav-header-action': 'Navigation - Header - About VA health benefits - https://staging.va.gov/health-care/about-va-health-benefits',
});
```

Example from vets-website: https://github.com/department-of-veterans-affairs/vets-website/blob/radavis/79823-ha-cpap-cta/src/platform/site-wide/mega-menu/containers/Main.jsx#L76-L83

See [VA Platform: Navigation Events](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/navigation-events). Scroll to `^nav-header-link$` event.

**Comment by dcloud** [comment]
Analytics implementation ticket created: department-of-veterans-affairs/va.gov-team/issues/82201 

cc @wesrowe

**Comment by dcloud** [comment]
@wesrowe I don't know what this means for this ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/82201#issuecomment-2098429083:

> @dcloud That looks like a GA UA taxonomy structure that would be created in GTM based on the variables in a dataLayer push event but I don't think that's what you're asking for. I think you want to share the dataLayer push event template for the custom event instead.
>
> Please note that the GA4 implementation project is the priority right now and other requests will likely be delayed until we have made further progress on that front -- which will likely not be until end of June/early July.

**Comment by wesrowe** [comment]
per further [discussion](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82201#issuecomment-2099250004) with Jamie from Analytics, she said she would have this set up by end of week (5/10).

**Comment by dcloud** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/82201#issuecomment-2115406233: 

```
'event': 'nav-mhv-secondary'  //feel free to change but share the final event name(s) with me so I can ensure the event is sent to GA 
'action': 'click'
'nav-link-text': //populate with the text of the link
'nav-link-url':  //populate with the destination URL
'nav-link-location': 'MHV secondary nav'  //using what you had in the ticket but change if you want something more descriptive
```

**Comment by wesrowe** [comment]
@dcloud, FYSA just to share a pro tip that Richard and I learned on the va-alert GA go-round: Jamie probably hasn't implemented the GTM side of this yet. so once you merge your recordEvent (or what have you), she'll probably need to do another GTM thing still.

**Comment by LynneJohnson224** [comment]
@wesrowe to review then close

**Comment by wesrowe** [comment]
Done! thanks, not sure how it missed the s32 tag.

**Comment by wesrowe** [comment]
I still don't see any GA4 event in adswerve. Jamie had promised to have this working by Monday AM, so I just [pinged](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82201#issuecomment-2148655325) the implementation ticket.

**Comment by wesrowe** [comment]
They're saying this "changed batches" and is now due to be complete on Mon, 6/17. Our potential launch day. [I pushed back](https://dsva.slack.com/archives/C1Q4294JJ/p1718304327616979?thread_ts=1718238293.683159&cid=C1Q4294JJ) in slack, a day earlier could potentially be very helpful.

**Comment by wesrowe** [comment]
I saw the secondary nav clicks in GA4 this morning! See [slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1719237747920879?thread_ts=1718238293.683159&cid=C1Q4294JJ) from Jamie Stutt for details. And here's a link to [the report I built](https://analytics.google.com/analytics/web/?pli=1#/analysis/p419143770/edit/dvxmtHCqTaaeZKalrojazw).
