### ISSUE TITLE
Increase contrast in Proofing Agent Screens

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#80666]
Based on a11y check in Figma, contrast needs to be increased by doing the following changes:
- Change all font with #0071BB to #Base/ink
- Increase contrast of drop down menu for ID types in Validate ID screen

See[ ticket](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/79985) for screenshots

**Comment by skirkman16** [comment]
Need to choose format for content after removing accordions first

**Comment by JKG199** [comment]
@skirkman16 updated and ready for review [here ](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3609%3A20846&mode=design&t=ltY8SAQLQde5pbW1-1)

**Comment by skirkman16** [comment]
<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c6bc685e4b686327d8e4d51f9ba4786ca2f6f8d/Screenshot%202024-04-22%20at%208.56.52%20AM.png" alt="Screenshot 2024-04-22 at 8.56.52 AM.png" />
Reviewed and accepted changes. Latest changes are under page "Post PA UT Prototype 4/19/24."
