### ISSUE TITLE
Non Disability/Dependents: Universal Analytics (UA) data reporting

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#80678]
Due date: Friday, April 26.

As part of the Google Analytics transition to GA4, all VFS Teams must create and share an inventory of their actively used reports that use Universal Analytics (UA) data. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

What do I need to do? 
Follow the instructions on this [Github form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-UA-Reports.md&title=Reports+Powered+by+UA%3A+%5BTeam+Name%5D), and include the name, URL link, platform, and brief description of any actively used reports that use Google Analytics UA data. We are defining "actively used reports" as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.

Questions? Please post any questions to the #vfs-analytics Slack channel. Additionally, feel free to join our team’s Office Hours, (every Tue & Thu @ 3:30pm ET)

Also, in case it's helpful -- [here is an example ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80397)of a completed form

**Comment by sortizsh** [comment]
@steele-lm  are you able to log in and run these reports?

**Comment by steele-lm** [comment]
Report submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/81142
