### ISSUE TITLE
Update content and layout for VA booked appointment detail page

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#80686]
## Description
This ticket was created from #79364 to make the PR review manageable.

## Acceptance Criteria
Background: the va_online_scheduling_appointment_details_redesign toggle is on

- [ ] Given the user is on the Start scheduling workflow
When the user clicks on Submit to schedule a VA booked appointment, Then the user will see the updated confirmation details page.

- [ ] Given the user is on the Start scheduling workflow
When the user clicks on Submit to schedule a VA booked appointment then cancels the appointment, Then the user will see the updated confirmation cancelation details page.

_**Page design must match the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A195846&mode=design&t=7xAm3Ts5T67F30L1-1)**_

**Comment by melissa-lefevre** [comment]
A11y check was good, no issues

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
