### ISSUE TITLE
Review and Document existing QA documentations and Document drafts for QA framework into github 

### ISSUE THREAD

**Issue by zyellowhorse** [department-of-veterans-affairs/va.gov-team#80691]
I received the following from Alexander Garcia regarding the QA framework.

1. ![:shrug:](https://a.slack-edge.com/production-standard-emoji-assets/14.0/apple-medium/1f937@2x.png) Not sure about this one.
2. I know platform has a whole list of tools of what they use for QA. However, our team in respect to tests: Mocha, Enzyme for unit tests, Cypress for E2E, TestRail for Test Plans (see [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards))
3. Yes. We have unit tests for authentication and its related applications. Identity Frontend team does not/will not do E2E tests. Datadog Synthetic tests from Frontend to Backend cover the E2E part
4. Honestly not sure, I'd recommend reviewing the [QA docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/qa-and-accessibility-testing)
5. Not sure yet.
6. Not sure if Platform CoP FE team is working on this right now but they used to have a [Test Stability Review](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-stability-review) mechanism in CI/CD that would add flaky unit and E2E tests to a disallowed list and post it to Slack to ensure teams check/fix their flaky tests. And I don't think it is working appropriately as it always displays that there are no flaky tests each week.
7. I know for certain teams Review Instances with authentication seems to be a hurdle due to it not being HTTPS (which is required for OAuth crypto libraries)
8. Nothing specific that I need right now. But the above items could help Platform CoP Frontend team out.
9. I believe there is a [QA Product Dashboard](https://depo-platform-documentation.scrollhelp.site/developer-docs/qa-product-dashboard-guide) (personally I've never used it, however I know one of the UX people on our team has DOMO access)
10. QA tests - unit tests and E2E both run during CI/CD (when a pull request opens).
11. 

I will be reviewing the documentation and workflows that Alexander mentioned. 

By going through I will drafting the QA framework improvments and

**Comment by parkerbees** [comment]
@joeniquette who is the best person for me to talk to about this effort? It doesn't look like it's been touched since Zac left. Thanks!

**Comment by parkerbees** [comment]
Closing this since it hasn't been worked since Zac left. If/when we circle back around to QA efforts, we can come grab this info from Zenhub.
