### ISSUE TITLE
[Bug]Veterans Choice Program link is Not Found

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#8069]
## What happened?
When clicking the link Veterans Choice Program from the primary site navigation (dropdown), instead of landing on the Vets Choice Program page -- here  https://www.va.gov/COMMUNITYCARE/programs/veterans/VCP/index.asp) -- I get a Not Found.

## Specs:
- Device: PowerMac
- Browser: Chrome, FF
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: From VA.gov, click on the About VA menu item on the main horizontal navigation, then click on Veterans Choice Program.
- Test User _(if applicable)_:

<img width="772" alt="Screen Shot 2020-04-16 at 7 32 33 AM" src="https://user-images.githubusercontent.com/63107147/79454895-fd165d00-7fb9-11ea-8d6c-729de9f007e9.png">

## Desired behavior
_From what I can tell, this program was discontinued as part of the Mission Act and the main nav link should be removed.  Source: https://www.military.com/daily-news/2018/06/06/trump-signs-55-billion-bill-replace-va-choice-program.html

## Acceptance Criteria
- [ ] Link should be removed

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Recommend changing to:

**[label]** **Community care**
**[link]** https://www.va.gov/COMMUNITYCARE/index.asp

**Comment by stephorkandatx** [comment]
After discussion in Slack, the agreed-upon path is to redirect to community care & to remove the page. 
Jen was able to disable the page temporarily. 
We have created two tickets to capture the remaining work
1- #8088 
2- #8092 

These two tickets will move to Backlog, and this ticket will be closed out
