### ISSUE TITLE
Update content and layout for CC appointment request detail page

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#80690]
## Description
This ticket was created from https://github.com/department-of-veterans-affairs/va.gov-team/issues/79364 to make the PR review manageable.

## Acceptance Criteria
Background: the va_online_scheduling_appointment_details_redesign toggle is on

- [x] Given the user is on the Start scheduling workflow
When the user clicks on Submit to request an appointment for a Community Care provider
Then the user will see the updated confirmation request details page

- [ ] Given the user is on the Start scheduling workflow
When the user clicks on Submit to request an appointment for a Community Care provider then cancels the request
Then the user will see the updated confirmation request details page

_**Page design must match the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A215656&mode=design&t=7xAm3Ts5T67F30L1-1)**_

**Comment by ldelacosta** [comment]
Validated the first use case and works in staging: 
<img width="660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79ad4369c407326f4f1d8981a49986eb272ed02f/Screenshot%202024-05-31%20at%2012.33.22%E2%80%AFPM.png" alt="Screenshot 2024-05-31 at 12.33.22 PM.png" />

The second stage does not work. A [bug ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84349) has been created. 
<img width="626" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a86fc5b5c6f30cb089dfc324c767d06816d2046e/Screenshot%202024-05-31%20at%2012.34.08%E2%80%AFPM.png" alt="Screenshot 2024-05-31 at 12.34.08 PM.png" />
