### ISSUE TITLE
Update IPP Code Repo to Meet LHDI code scan policy

### ISSUE THREAD

**Issue by mateoclarke** [department-of-veterans-affairs/va.gov-team#80719]
From LHDI Team:

_With the recent CodeQL scanning policy mandate announced by VA OIS and GitHub team, I'd like to address ongoing questions/ambiguities surrounding LHDI tenant usage of Snyk code (in lieu of CodeQL) for SAST and SCA scanning.
Context
The Lighthouse leadership team is in ongoing communication with VA leadership to ensure alignment on LHDI's continued usage of Snyk.
The policy announcement states that CodeQL is a hard dependency to some of the pull request workflow policies being enforced on repos.
While this policy is currently enforced on repos via GitHub Rulesets, repos will not be blocked by CodeQL vulnerability findings until April 15th
Next steps
The Lighthouse team will be executing a fresh assessment of CodeQL vs. Snyk, to determine if security scanning outcomes have improved for CodeQL since it was originally assessed in the summer of 2023. This assessment is on track to complete by this Friday (2/23/24).
If the assessment finds that the shortcomings in CodeQL vs. Snyk have been meaningfully addressed, a migration strategy from Snyk to CodeQL will be put into place and communicated to all LHDI tenant teams.
Otherwise, Team Tornado and Lighthouse Leadership will engage GitHub and VA OIS stakeholders with results that need to be addressed_

**Comment by rdvyas** [comment]
Completed this ticket:
1. [Submit an exemptio](https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/settings/custom-properties)n to bypass PRs on main branch + Request to bypass default CodeQL 
2. [Request](https://github.com/department-of-veterans-affairs/github-user-requests/issues/21432) to bypass critical remediation policy

Closing tickets at complete.
