### ISSUE TITLE
Fix breadcrumb to match page title

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#80714]
## Summary
The recent content changes to Community Care appointment flow has changes to the page title. Update the breadcrumb to reflect the changes.

## Steps to Reproduce

1. Start Scheduling for community care appointment request
2. Select Podiatry
3. Select a Date
4. "my-health/appointments/schedule/community-request/closest-city" does not match the title page
5. "my-health/appointments/schedule/community-request/preferred-provider" does not match the title page
6. "my-health/appointments/schedule/community-request/preferred-language" does not match the title page 

### Actual Result
<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXBmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c97d4aaacac8e9f6e5212a96ae91e7fedce9a7c/Screenshot%202024-04-15%20at%207.46.52%20AM.png" alt="Screenshot 2024-04-15 at 7.46.52 AM.png" />

### Desired Result
The last crumb should change from "What’s the closest city to you?"  to say "What’s the nearest city to you?"
The last crumb should change from "Request a podiatry provider"  to say "Which provider do you prefer?"
The last crumb should change from "Choose a preferred language"  to say "What language do you prefer?"

## Definition of Done
- [ ] Breadcrumb should match the title  of the appointment flow

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment]
Validated the breadcrumb matches the page title in staging:

1. What’s the nearest city to you?
2. Which provider do you prefer?
3. What language do you prefer?


FYI @outerpress for the next iteration for breadcrumb updates with the cartography team.
