### ISSUE TITLE
Burial | Update "Need Help" Component

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80738]
## Issue Description
_CAIA would like us to customize the footer on the burial form. See details in [this thread](https://dsva.slack.com/archives/C057W3N9K2S/p1711572473004929)._

It should read:

- **If you have trouble using this online form**, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24/7.

<img width="1074" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/7a557d53-dae6-4b43-948d-d02739309b06">
---

## Acceptance Criteria
- [ ] Need help section within the footer contains the updated text.
---

**Comment by DLarson-Oddball** [comment]
Code for this issue has been merged @steele-lm
