### ISSUE TITLE
NoK: Response codes associated with the correct stack layer

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#80741]
### User story

As a Cartographers team member, I want api.va.gov/v0/profile/contacts to handle service HTTP 4xx/5xx responses and raise vets-api Exceptions, so that vets-api errors and back-end (VA Profile) errors are categorized and monitored at the appropriate layer of the stack and can be scored to the appropriate SLO.

### Notes
- `/v0/profile/contacts` should have a defined pattern for translating 4xx/5xx service responses to api responses
        404 -> { data: [] }
        500 -> { errors: ... }
        malformed service response body -> { errors: ... }
- VA Profile Service class in vets-api should handle Common::Client::Errors and raise Common::Exceptions when necessary.
- Check if contact information impacted by Profile migration (v3)
- [SLO targets for vets-api errors](https://depo-platform-documentation.scrollhelp.site/developer-docs/core-service-level-indicators-and-objectives-for-v#CoreServiceLevelIndicatorsandObjectivesforVetsAPI-Errors)

Possible tasks:
- 

## Acceptance criteria

- Datadog dashboard for vets-api accurately tracks response codes that originate with vets-api
- 4xx/5xx errors at the VA Profile layer are visible to Cartography team members in Datadog as originating in the back-end
- Test suite output describes this mapping.
- QA review

**Comment by LynneJohnson224** [comment]
8/7/2024 Refinement Notes: Would like to complete this before working on NoK/EC edit. Will need to check if the contact information is impacted by the profile v3 migration.

**Comment by radavis** [comment]
Files of interest in vets-api:
- app/controllers/concerns/exception_handling.rb, specifically `render_errors` method
- config/locales/exceptions.en.yml

**Comment by wesrowe** [comment]
>Will need to check if the contact information is impacted by the profile v3 migration.

Did anyone take the action item to find out whether contacts are impacted by the v3 implementation?

// cc @radavis @LynneJohnson224 @dcloud

**Comment by wesrowe** [comment]
Reiterating my comment above:
>Did anyone take the action item to find out whether contacts are impacted by the v3 implementation?

Relatedly, this ticket needs points. I'm adding the "needs refinement" label back on.

**Comment by radavis** [comment]
> Reiterating my comment above:
> 
> > Did anyone take the action item to find out whether contacts are impacted by the v3 implementation?
> 
> Relatedly, this ticket needs points. I'm adding the "needs refinement" label back on.

v3 implementation of...?

**Comment by radavis** [comment]
The vets-api client/service code for reading Personal health care contacts through VA Profile API is in the [V3 Profile client](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/va_profile/profile/v3/service.rb#L26:L26)

**Comment by dcloud** [comment]
@radavis The _maybe_ related work is under this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/83181+ : "Upgrade V2::ContactInformation::Service to V3::ProfileInformation::Service"

You can see this in-progress PR: https://github.com/department-of-veterans-affairs/vets-api/pull/17397

Perhaps the key is that those are talking about "V2::ContactInformation::Service to V3::ProfileInformation::Service"?

It could also be that the code you're referring to might be get merged with or replaced by that work.

**Comment by radavis** [comment]
> Perhaps the key is that those are talking about "V2::ContactInformation::Service to V3::ProfileInformation::Service"?

Yeah, our client is namspaced under `VAProfile::Profile::V3:Service`, so I don't believe this will be a concern.
