### ISSUE TITLE
NOD | Review page header hidden

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#80752]
## What happened? 

**Describe what went wrong**: 
Review page header is not showing within the accordion. When an accordion header and page header are the same name, the page header gets hidden, resulting in a blank space where 'edit' appears.

This also happened previously on HLR, but it's not happening anymore (both accordion header and page header are showing)

**Add the steps to reproduce the bug**:
1. Start NOD and get to https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/review-and-submit
2. Open Board review option
3. Note that there's no panel page header
4. In error mode, panel page header only shows error icon, with no header

**Add a screen recording or photo**:
Not showing up on NOD
![NOD review](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVZoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad11c281544fb67ce93d51159e5f0386a5e029d6/Screenshot%202024-04-15%20at%203.21.41%E2%80%AFPM.png)

Somehow it's showing up in HLR
![hlr review](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ade055f7771702a2ded80a63cf9a283b221f45af/Screenshot%202024-04-15%20at%203.30.05%E2%80%AFPM.png)

## How severe is the problem?
- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP. 
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [x] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint. 

## What is the desired behavior?

1. _When a user does opens the review accordion, the **visual** result is page titles show up with an edit button next to it._

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by Mottie** [comment]
FIxed as part of #65747

**Comment by eileen-coforma** [comment]
@Mottie NOD still has a missing header:

![Screenshot 2024-05-01 at 9 41 24 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/9d5a8005-4c70-4293-950a-235974ea14f4)

**Comment by Mottie** [comment]
Oh derp... I fixed the header in HLR, not NOD... on it!

**Comment by Mottie** [comment]
Ready for review in staging

**Comment by eileen-coforma** [comment]
Validated in staging 👍
