### ISSUE TITLE
[Document Upload Failure Notifications - Testing] Hook up new VA Notify Disability Benefits Service - Staging

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#80760]
## Description

Before testing the new Notification Mailer https://github.com/department-of-veterans-affairs/vets-api/pull/16359/ in staging, we need to prepare the staging environment for our new VA Notify service.

* Doc on secrets setup https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-VetsAPIsettingsandsecrets

## Acceptance Criteria
- [ ] Obtain API service key 
- [ ] Obtain template_id for new mailer
- [ ] Add ENV path mapping to manifest repo values.yml https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blame/main/apps/vets-api/staging/values.yaml
- [ ] template_id can probably just go in settings.yml
- [ ] Get somebody to add the secrets to the staging environment via the EKS UI
- [ ] Make a ticket for doing this in prod (in a release ticket)

**Comment by tblackwe** [comment]
@tblackwe add the staging API keys
