### ISSUE TITLE
Sign-Out Page: Accessibility Test Plan

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#8076]
As part of the staging review (see: #6537). Complete Accessibility Test plans for new UI elements associated with the SSOe release.

https://staging.va.gov/sign-in/?auth=logged_out 

- [ ] Automated Tests - Alexis

- [x] Manual Tests - Bridget

**Comment by bridgethapner** [comment]
Manual tests are done, PDF is in GitHub and linked from [your doc here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/accessibility-plan-signin-page.md#manual-testing-required).
