### ISSUE TITLE
CT: SCO not in line with Contact Details

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#8078]
Navigate to both https://staging.va.gov/gi-bill-comparison-tool/profile/11929140 and https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/HACK%20REACTOR%20SOFTWARE%20ENGINEERING%20ONLINE.

Both Vettec and non-Vettec SCO is not aligning with contact details.

![Screen Shot 2020-04-16 at 11.14.46 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d841cd21-3a3e-45ee-9a06-3e1db2940894)

## Mobile view

For mobile displays,  SCO info and school address areas could have increased space on the right side so you can fit more info on one line. 
![Screen Shot 2020-04-27 at 9.59.05 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0100bda3-3dab-444c-9cc0-361d4090cfb4)

**Comment by hughes-dustin** [comment]
Branch: bah-8078
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12610

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-05-11 at 1.52.41 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/be765334-d41a-4398-aa22-e2a0b78de7a7)

---

![Screen Shot 2020-05-11 at 1.56.13 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/35e06297-eb13-4277-9db4-efece006dbbe)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This fix is on Staging and ready for review.

**Comment by delli-gatti-michael** [comment]
Bug fix has been approved. Closing this issue
