### ISSUE TITLE
Update 'Create a new Platform website documentation page' with Google Drive Language

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#80793]
Recently, we changed the Launch Blocking Issues list to include "Links to Google Drive." That list also appears on the [Create a new Platform website documentation page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page#Launch-blocking-issues).

The LB list on that page should be updated to reflect that addition of Google drive links. 

### TASKS

- [x] Update Create a new doc page with Google drive link verbiage

### DEFINITION OF DONE

- [x] Page contains new language on Google Drive links.

**Comment by BSmolensky** [comment]
This ticket is likely a simple copy and paste. The additional language already exists here: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+Content+team+deployment+instructions#Launch-blocking-issues

**Comment by jknipes** [comment]
Closing ticket, moving to _Done_
