### ISSUE TITLE
Design | EDU CH33 Changes | Run UAT

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#80803]
## Background 
This ticket is to conduct UAT research w Perigean

### Blocked by 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80802

## Tasks 
- [x] complete the research 

## Acceptance Criteria 
- [x] research is completed

**Comment by mattmarino-adhoc** [comment]
Will continue into the next sprint. Testing began on 7/15, the goal is to complete it by 7/18.

**Comment by mattmarino-adhoc** [comment]
Sessions completed on 7/22 (5 sessions, 2 internal).
