### ISSUE TITLE
Analytics Implementation for Links List Null Handler

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#8080]
# Analytics Implementation or QA Request

## Description
- Update null handler for to use `links-list-header` DL variables when available and click text when unavailable

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Tested the home page and a few other sub pages.  We will need to test the COVID FAQ dataLayer changes with this when that PR is ready.

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000265

**Comment by jonwehausen** [comment]
### QA Testing

#### Test Scenario 1 - ✅ **PASSED** - Clicks directly on description within link
- This scenario accounts for when the user clicks on the description as part of clicking on the link and no `links-list-header` available. Prior to this fix, this would pull in the click text of the description and taxonomy would not be as clean. 
1) Tested on existing COVID FAQ Page, 
2) Clicked on each link's description within the 'More Information' section 
![image](https://user-images.githubusercontent.com/48527022/79476947-9a33be80-7fd7-11ea-86cf-502e183c7084.png)

#### Test Scenario 2 - ✅ **PASSED** - Mirrored a `links-list-section` and `links-list-header` click (DL push)
1) Tested on existing COVID FAQ Page, 
2) Right portion of screenshot mirrors the DL push of a click on 'How to apply for a VA health care'
![image](https://user-images.githubusercontent.com/48527022/79477585-5ab9a200-7fd8-11ea-8949-9b937f18af70.png)

#### Test Scenario 3 - waiting on COVID FAQ Updates

Overall looks good but want to confirm with new FAQ updates before publishing.

**Comment by jonwehausen** [comment]
Published out 4/21 - Closing
