### ISSUE TITLE
BE | Profile | Direct Deposit | Promote template to production

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#80818]
## Background
The new "Direct Deposit Update Confirmation" template needs to be promoted to production.

See for more details - https://github.com/department-of-veterans-affairs/va.gov-team/issues/80210

## Tasks
- [x] Promote new direct deposit template to production.
- [x] Add template id to vets-api.

## Acceptance Criteria
- Need to test during UAT.

**Comment by mtcA6** [comment]
I agree w/your assessment the only way to test is w UAT
