### ISSUE TITLE
UX: Update content of Medical Records box for integration

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#80829]
### User story

As a Veteran, I want the MHV landing page to explicitly inform me that medical records links will take me to another website, so that I can avoid getting disoriented by unexpected navigation.

### Notes
- Needs UX design. Design system has guidance on [sub-domain links](https://design.va.gov/content-style-guide/links#va-sub-domain-exceptions-that-open-in-a-new-tab-or-window) that amounts to adding " (opens in new tab)" to links.

## Steps/tasks
- 

## Acceptance criteria

- Design in Figma depicts 1) which links should get this experience (e.g., Records links on landing page) and 2) what the experience looks like
- A11y specialist reviewed design

**Comment by wesrowe** [comment]
@fmccaf1, Could you please update this ticket when you have a chance? I have a feeling that some decisions have been made regarding this functionality. E.g., I think I heard you say in the OCC meeting that you and Kaitlin have settled on an "intermediary page." I would like to get engineer eyes on them in the spirit of preparation/acceleration.

**Comment by fmccaf1** [comment]
Part of this ticket that needs to happen but we haven't tackled yet: Communicating to users that MR links on the LP (non-secondary nav links) will go to an external page (the previous MHV). That will be making tweaks to landing page copy and likely more than that to accommodate the copy (design changes).

**Comment by wesrowe** [comment]
The solution to part of this story has been moved to #81734: a temporary MR landing/departure page.

**Comment by dcloud** [comment]
> That will be making tweaks to landing page copy and likely more than that to accommodate the copy (design changes).


It sounds like we don't know what those non-secondary link changes will be yet? 

For what its worth, it looks like the section (`#va-sub-domain-exceptions-that-open-in-a-new-tab-or-window`) on sub-domain links in the design system was removed

**Comment by fmccaf1** [comment]
[Started to think through some solution options but I think there are tons more to explore. Had to first de-componentize desktop design and re-align spacing.](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=0%3A523&mode=design&t=crUSmZEJzfnFwyzj-1)

@jonathanjnelson maybe you can take this on and do some creative exploring of other options?

**Comment by sterkenburgsara** [comment]
**Update**: We have begun creating messaging on the landing page within the Medical Records box. This general concept (with the "coming soon" tag) has been preliminarily approved by Kaitlin. We are still iterating and plan to present most approved content to OCC tomorrow 5/8 for further feedback. // cc @jonathanjnelson 

<img width="572" alt="Screenshot 2024-05-07 at 4 47 30 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/c646a8da-651f-4613-a89c-4bcb2b0c81e9">

**Comment by sterkenburgsara** [comment]
My HealtheVet links should not open in a new tab. VADS needs an update but this is against our guidance. 

We are experimenting with how to communicate that they are on another site, though.

**Comment by LynneJohnson224** [comment]
@jonathanjnelson following the OCC demo yesterday, can this ticket be closed?

**Comment by jonathanjnelson** [comment]
[Updated designs in Figma](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2138%3A28954&t=2wowkk9hJx8NNrs2-1)

<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlRYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc3c4dcb0689ca527bdf705ce6b618c927b24b58/Screenshot%202024-05-13%20at%204.16.51%E2%80%AFPM.png" alt="Screenshot 2024-05-13 at 4.16.51 PM.png" />

**Comment by sterkenburgsara** [comment]
This ticket has been handed off to dev. Closing.
