### ISSUE TITLE
CF: Update caution flag content based on DEPO staging review feedback.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8082]
As a user of the Comparison Tool, I need the language of the caution flags to be plain language and consistent to the experience provided on VA.gov so that I have a clear understanding of the information being communicated and a consistent experience throughout the platform.

## Assumptions:
1. This work originated from tickets #7792 and #7990.
2. This work is completed behind a flag so that it is only available in the staging environments and below.

## Acceptance Criteria
1. The caution flag description

     > An assigned receiver has motioned the court for an emergency closure of this campus. It may close soon.

     is replaced with the following: 

     > An individual or business placed in charge of this institution's finances has motioned the court for an emergency closure of this campus. It may close soon.

2. The caution flag description 

     > This school's accreditation has been revoked and is under appeal, or the school has been placed on probation as it didn't meet acceptable levels of quality.

     is replaced with the following: 

     > This school's accreditation has been taken away and is under appeal, or the school has been placed on probation, because it didn't meet acceptable levels of quality.

3. The caution flag:
    a. Header 

      > School denied recertification for Federal Student Financial Assistance Programs
      
      is replaced with the following: 
      
      > School denied recertification for federal student financial assistance programs
     
     b. Description 

      > This school's recertification application to participate in the Federal Student Financial Assistance Programs issued by Department of Education has been denied.

      is replaced with the following: 

      > This school's recertification application to participate in federal student financial assistance programs issued by Department of Education has been denied.

4. The caution flag:
     a. Header 

      > School is on heightened cash monitoring

      is replaced with the following: 

      > School placed on Heightened Cash Monitoring

     b. Description 

      > The Department of Education has placed this school on Heightened Cash Monitoring due to financial or federal compliance issues.

      is replaced with the following: 

      > The Department of Education has placed this school on Heightened Cash Monitoring because of financial or federal compliance issues.

5. The caution flag description 

      > Post 9/11 GI Bill (CH33) benefits can't be used at this school as the school is not approved for them.

      is replaced with the following: 

      > Post 9/11 GI Bill (Chapter 33) benefits can't be used at this school as the school is not approved for them.

6. The caution flag:
     a. Header 

      > School is facing a potential lapse in program approval

      is replaced with the following: 

      > School is facing a potential loss of program approval

     b. Description 

      > There may be a potential lapse in program approval for this school.

      is replaced with the following: 

      > There may be a loss of program approval for this school.

7. The caution flag:
     a. Header 

      > School has settled its case with the U.S. Government

      is replaced with the following: 

      > School has settled its case with the U.S. government

     b. Description 

      > The U.S. Government has reached a settlement with this institution. 

      is replaced with the following: 

      > The U.S. government has reached a settlement with this institution.

8. The caution flag:
     a. Header 

      > School has settled its case with the State Attorney General

      is replaced with the following: 

      > School has settled its case with the state Attorney General

     b. Description 

      > The State's Attorney General has reached a settlement with this school.

      is replaced with the following: 

      > The state's Attorney General has reached a settlement with this school.

9. The caution flag:
     a. Description 

      > This school is on Department of Defense (DoD) Probation for Military Tuition Assistance (TA). 

      is replaced with: 

      > This school is on Department of Defense (DOD) probation for Military Tuition Assistance (TA).

     b. The link text 

      > Learn about DoD probation

      is replaced with: 

      > Learn about DOD probation

10. The caution flag description 

      > This school isn't approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits because it doesn't comply with Sec 702. Section 702 requires public universities to offer recent Veterans and other “covered individuals” in-state tuition, regardless of their state residency.

      is replaced with: 

      > This school isn't approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits because it doesn't comply with Section 702. This law requires public universities to offer recent Veterans and other covered individuals in-state tuition, regardless of their state residency.

11. In all cases, when the institution does not have a website to reference, the 

      > <link> Visit the school's website to learn more</link>

      is replaced with 

      >  Visit the school's website to learn more.

## Supporting Artifacts:
1. Source document AC is based on [Caution Flag Copy for Review v.2.0.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4488285/Caution.Flag.Copy.for.Review.v.2.0.xlsx) - Columns O-S

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/644

**Comment by sonntag-adam** [comment]
AC #1
![Screen Shot 2020-04-20 at 11.45.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/79213424-c79d-4cd3-b5a8-c614563ab875)
##
AC #2
![Screen Shot 2020-04-20 at 11.46.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/edda9d20-2671-4042-a827-e4b0ee536b56)
##
AC #3
![Screen Shot 2020-04-20 at 12.18.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/710582e5-337b-4b3d-9b52-cfc4735d28d6)
##
AC #4
![Screen Shot 2020-04-20 at 12.20.08 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fe155e7f-3f76-46ca-8cc4-a17023dc5c72)
##
AC #5
![Screen Shot 2020-04-20 at 12.22.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cd8ae885-0794-4325-a56a-9ab2a1e9065d)
##
AC #6
![Screen Shot 2020-04-20 at 12.25.50 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/10cfdba5-9bba-4f2a-aabf-9a3daed7ab6a)
##
AC #7
![Screen Shot 2020-04-20 at 12.28.23 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a5bc4a9d-bacf-48a6-b6c9-20de497adcdb)
##
AC #8
![Screen Shot 2020-04-20 at 12.29.37 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8d306f93-b3a3-4d70-8ad9-4754c7715179)
##
AC #9
![Screen Shot 2020-04-20 at 12.31.06 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c76bcb70-ef0c-4325-b255-3eab0fa8ee9b)
##
AC #10
![Screen Shot 2020-04-20 at 12.32.06 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ebff0b2f-c03d-4e0c-a92e-73c512a9b0a8)
##
AC #11
![Screen Shot 2020-04-20 at 1.35.30 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/254dc2bd-633e-42eb-8778-0f8fe04b1b15)

**Comment by sonntag-adam** [comment]
Does not show in a production build locally.

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/298&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
