### ISSUE TITLE
UX & Eng: Secondary nav on MHV landing page (only)

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#80821]
### User story

As a Veteran who is registered at a facility and signed in with an LOA3 credential, I want a secondary nav bar at the top of the MHV landing page to provide links to tools, so that I can navigate the portal without losing a sense of place. 

As a developer, I want to implement the MHV secondary nav as a shared component, so it can be reused by different teams easily and effectively.

### Notes
- Three tools that will be on VAgov: Appts, SM and Medications
- ~UX design was established in #74454~ EDIT: moving UX design to this ticket
- Would the secondary nav be implemented on each app separately? Can it be done more generically, like at the header level?
- Will need to get feedback from other teams like Platform on the feasibility of having the secondary nav in a more generic location if applicable.

## Steps/tasks
- Look into whether secondary nav could live in sitewide header or outside (while visually appearing tied to header)

## Acceptance criteria
- [x] Documented UX design for secondary nav component
- [ ] Built alignment among Cartography team, tool engineering teams, and Platform (if necessary) on a shared-component approach
- [ ] Implemented secondary nav component such that tool teams can add it to their apps (SM, Appts, Meds)
- [ ] Added secondary nav to MHV landing page behind the appropriate feature flag
- [ ] Secondary nav is hidden for users who trigger the non-LOA3 or un-registered alerts
- [ ] QA reviewed implementation in staging
- [ ] a11y reviewed implementation in staging

**Comment by dcloud** [comment]
Duplicated ticket, need to update ACs

**Comment by wesrowe** [comment]
refinement:
- Dev = 8 pts
- UX = 
  - 3 done
  - 3-5 remaining

**Comment by wesrowe** [comment]
### Notes from eng-ux sync 4/22:
No feasibility concerns about the design.
Clarified some behaviors:
- 481px is the device width where full destination names become abbreviations (`$small-screen`)
- 768px is the break where the Home link is added in (and MHV title is not clickable)
- select state indicating the tool that the user is on is an underline with bold font
- hover state... we couldn't find it in figma
- screen magnifiers – we're following guidance that 320px (equivalent) is the smallest we need to design for
- desktop version is least likely to churn, so start dev there

**Comment by fmccaf1** [comment]
At this point, any future changes are most likely around hover/select states. For example, there has been some talk about making select state into a more tab-like style vs. a rounded rectangle. I'll make sure you're all aware of any changes that come up.

**Comment by fmccaf1** [comment]
[Secondary nav designs have its own file in Figma now](https://www.figma.com/file/6nWnlJUjSK91V9hjc3p0LN/MHV-Secondary-Nav?type=design&node-id=27%3A65&mode=design&t=ENtnD3r3o0u8TuqJ-1)

If you have any issues with access let me know (thinking nobody should but who knows in this wild world)
