### ISSUE TITLE
Plan feature toggles aspect of roll-out

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#80835]
Wes note: this seems to me to be part of release planning; is it a separate ticket?

### User story

As a Veteran, I want to reach the appropriate health tool (either MHV Portal or MHV on VA.gov tools) in a clear and consistent manner.

### Notes
- There will not be a %-based roll-out – will go straight to 100%
- The new VA.gov health tools each have their own feature toggle
- Do we need a feature toggle separate from the health tools for the MHV landing page links
- Feature toggle percentages for individual apps would affect different users
- Want to avoid veterans getting redirected back and forth between new and classic/national portals

Possible tasks:
- 

## Acceptance criteria
- Document in the release plan the feature toggles and logic to be used to present the new links to users.

**Comment by radavis** [comment]
If we want to roll out the health tools on VA.gov to a percentage of users, we would need a single feature toggle to control links on the landing page. However, each health tool has its own feature toggle that determines if it is enabled.

**Comment by wesrowe** [comment]
I'm going to pull the details from this ticket into the implementation planning ticket, and close this one as a dupe.
