### ISSUE TITLE
Track app/tool changes related to launch

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#80839]
Tool teams devs also need to do these things:

- update breadcrumbs on landing pages to point to MHV landing page
- update all URLs to other tools to point to tools on VA.gov (not national portal)
- implement Cerner/OH gating for any users with an oracle facility in their profile that routes them to MyVA Health

**Comment by dcloud** [comment]
We may want to do some or all of this work for the tool teams

**Comment by wesrowe** [comment]
Tool teams are going to take on the breadcrumb/links updates. We are going to try tracking in a dedicated ticket, which I wish I had done here. But now it's a dupe. :( closing

Note also: Sara raised the Oracle gating, and it's in place on SM and Appts already. Meds will implement themselves.
