### ISSUE TITLE
(Figma) Update date range fields

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#80847]
Engineer has implemented the update the form to use the date range web component pattern support to the VA Forms library ([datePatterns.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/7bbb2a24e67a9a97812c95225e4e20747a67b8c7/src/platform/forms-system/src/js/web-component-patterns/datePatterns.jsx)) to replace the 'dateRange' widget. 

### Acceptance Criteria:

Update the following Figma files to reflect what is shown in PROD.
- [x] Service period
- [x] Prisoner of War
- [x] Care expenses

**Comment by echin393** [comment]
* The Figma file was up-to-date except that it did not reflect the hint text displayed for the date range component. I've added the hint text accordingly. 
* Note that the latest version of the VADS Date Input component does not reflect the same input types in production. The Day field in the component library is a select dropdown, whereas production is text-input.
