### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by ilaflamme-va** [department-of-veterans-affairs/va.gov-team#8084]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Ian LaFlamme
- Please Provide your email.
   > ian.laflamme@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Lighthouse
   > Role: Software Developer
   > Company: Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDy4y2zHDohYMsC5k3si+fNfO4KaEoD3biBo/mLW4kSbzK6g8W8BHPI3Sqn0aTtrsfFTH5AGE3QRhuGCvC8QOCItQjP8oBNNOjfbD5/GlRVrep5TXYZC4EBvlkFtRwyZLIPNkNTsJq7XZwUwK09sVsUjUdS5lBi5UhoUrvzs+5u60g6xFd15ijDiLkTYKRgR0xoSkkXIiS1OcqbYFu+Rla3tXVYmWrirgxCj8sCDObs/zj3Te85yY2bbwVRrStpuIa3BEt7g0Di1SgfqsNHWzdijJ08IwIuFk8P69eH6ISWZWwLiaGN7cDkviAEH7vEMJWVclJO0+AAyfMPi+eQQa/5 ian@ian-Inspiron-7559
```

- [Grant AWS Console access?]
  > NO

**Comment by ilaflamme-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
