### ISSUE TITLE
[Nessus Finding] HSTS Missing from HTTPS Server - DUE MAY

### ISSUE THREAD

**Issue by kell-y** [department-of-veterans-affairs/va.gov-team#80844]
The Feb 2024 Nessus Scan revealed a new medium vulnerability finding on 2/2/24:

HSTS Missing from HTTPS Server, host 10.247.33.45

Nessus Solution: Configure the remote web server to use HSTS

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM096QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fa4d7eaaeab9d95f2178fb6faf466d09078b039/image.png" alt="image.png" />

**Comment by ph-One** [comment]
Keep in mind that IP addresses mean nothing in our environment. We can dig through CloudTrail and see what instance(s) _may_ have used this IP during this time period, but it's largely a shot in the dark.

**Comment by gary-fallon** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/440

**Comment by ph-One** [comment]
Initially I thought this may be from the revproxy, but they are all configured for HSTS. Looking elsewhere.

**Comment by ph-One** [comment]
Forward Proxy also has HSTS enabled. Looking elsewhere.

**Comment by kell-y** [comment]
Update on 6/24/2024: Infra did a little looking, and a decision was made to wait for the next scan (to be done some time in July) to see if this still appears. Othrwise, Infrastructure has been unable to locate an individual virtual machine based on just an IP address as a data point.

**Comment by keithdadkins** [comment]
I'm working on setting up a box to perform internal scans and some scripts to help map services to IP addresses. I'll perform a manual scan initially, but intend to build automation we can use if something like this pops up again. I suggest closing this ticket and creating a new one to scan for security headers.

**Comment by kell-y** [comment]
I think we'll need to keep this ticket to track the finding until it's closed or remediated, but go ahead and open a new one for the work you suggested!

**Comment by kflow85** [comment]
Further tracking on this ticket can be found in Github Projects https://github.com/department-of-veterans-affairs/va.gov-team/issues/80844#issue-2246451676

**Comment by ph-One** [comment]
@keithdadkins we will have to see the next set of scan results, but this may have been resolved by some Support-ish work that I did the other day, https://github.com/department-of-veterans-affairs/va.gov-team/issues/90377
