### ISSUE TITLE
10-7959f-2: Create urls for staging/prod

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#80860]
As a user, I want to be able to enter form urls directly into the browser so that I know where I can go to fill out the FMP claim form online.

URLs for staging and prodshould follow CAIA guidance:

Teams can choose their own sub-urls, or get help from CAIA in choosing them or vetting them.
Note some standard sub-urls:
/introduction: use on the first page of the actual form (not the static page in drupal)
/review OR /review-and-submit: use for review steps in forms or tools
/results: use to display the results of a tool (not usually used in a form)
/confirmation: use for the confirmation page after form submission
Subtask URL slugs should be short, plain language, and drawn from the H1 if possible.
Reminder: Don’t create unnecessary or empty subdirectories when creating sub-URLs

base url: va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/

sub urls:
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/introduction
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/veteran-information
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/identification-information
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/mailing-address
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/home-address
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/contact-information
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/upload-supporting-documents
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/review
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/confirmation

[FIGMA link (WIP)](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=0-1&mode=design&t=ELMY9uSPdZG3dsO6-0)

**Comment by reiting** [comment]
<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk85Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10cd77bfcfd729b81bf9470ef8eee1779d37699b/Screenshot%202024-09-09%20at%2010.08.05%E2%80%AFAM.png" alt="Screenshot 2024-09-09 at 10.08.05 AM.png" />

**Comment by reiting** [comment]
@marywang2 this is in staging and should be good to go.

**Comment by marywang2** [comment]
Thanks @reiting - do you know if 'review-and-submit' is standard (vs I had it as 'review' originally).
