### ISSUE TITLE
Spike for ITF on participant_id, veteranId, and PII

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#80862]
Question:
Is **participant_id** (we get this from VA Profile) the same as a **veteranId** (we need this for ITF API) which is what is needed for ITF. 

We need to know if we can store participant_id and/or veteranId in the database.  Are these stored in other tables already?

**Comment by aplatt-coforma** [comment]
Tagging @matt4su and @mjknight50 for your awareness.
Closing this ticket as done.
