### ISSUE TITLE
[Team] 10-10EZR/EZ: Update Error and Outage Document

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#80893]
As a team member, I would like a document that outlines how we handle errors and outages so I know what to do when something goes wrong.

- [ ] **Success: The team, PMs, and PO have approved the document and it has been linked to in the HCA post mortem.**

**Comment by hdjustice** [comment]
Do we need to keep this ticket open?

**Comment by hdjustice** [comment]
Closing - [Incident response document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Error%20and%20Outage%20Procedures%20for%201010%20Team.md)created and being updated regularly
