### ISSUE TITLE
Pull metadata for 165k Va.gov Submissions without VBMS Claim ID in DB

### ISSUE THREAD

**Issue by emilytheis** [department-of-veterans-affairs/va.gov-team#80892]
As part of the audit process, we sent Alex full form526 JSON for all of the va.gov.

SavedClaims without a VBMS Claim ID attached.

We need to also provide him the metadata associated with these submissions. The file of Submission IDs is attached.

The metadata should be paired with a va.gov submission ID and we expect the following fields

"status": 
"idType": 
"id": "
"edi": 
"firstName": 
"lastName": "
"birthDate": "
"gender": 
"fileNumber": 
"birlsfilenumber": 
"zipCode":
"claimDate": 
"formsIncluded":

**Comment by emilytheis** [comment]
[](url)[CY526A_SUBMISSION_IDS_20240416a.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aadda915f5673b64412cb7a75f6b4cbc376426a/CY526A_SUBMISSION_IDS_20240416a.txt)

**Comment by SamStuckey** [comment]
Just to confirm format, each matching submission should be represented as

**Comment by SamStuckey** [comment]
reached out to alex to confirm the above

**Comment by SamStuckey** [comment]
UPDATE: sample added to sharepoint

**Comment by SamStuckey** [comment]
COMPLETE: the CSV with the agreed upon output is now available in sharepoint, names 526_pii_audit_final.csv
