### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#80894]
### Name

Jared Pace

### Email

jared.pace@agile6.com

### Role

Product Manager

### Team

DBEX Team 1 (Agile Six)

### Product Manager (PM) name

Emily Theis

### Additional Notes

Req access to collaborate with the DBEX & VA team.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to jared.pace@agile6.com.
