### ISSUE TITLE
[Team] 10-10EZR: Make sure MHV landing page links to EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#80891]
As a Veteran, I would only like to be able to see the EZR Intro page if I'm logged in so that I don't get confused and try to fill out the EZR when I'm not already enrolled in healthcare.

- [ ] Work with Sara Steckenburg and MHV cartography team to make sure the content and links to EZR are accurate on the MHV landing page
- [ ] **Success: Users on MHV can get to the online EZR.**

**Comment by mkerns1** [comment]
Notes from my call with Sara:

- **Health Care Portal Navigation**: Users navigate to the health care portal and then to the EZR section.
- **Access Issues**: Unclear whether users who lost previous access should see the EZR directly or need to complete another EZ form.
- **Smart Alert Proposal**: Implement a smart alert for users who are unenrolled but previously had access, informing them that they are viewing past data.
- **Enrollment Definition**: Enrollment includes access to additional health portal apps.
- **COVID-19 Vaccine Access**: Employees of the VA who received a COVID-19 vaccine gain access to the portal.
- **Facility Registration Access**: Anyone registered at a facility is granted access to the portal.
- **Enrollment Criteria Alert**: Users associated with a facility but not meeting current enrollment criteria should receive an alert: "You are not currently enrolled. Please go fill out [blank]."

**Comment by alexseelig** [comment]
@allanto-ah @mkerns1 I'm thinking that the testing story for this should be on the MHV board since it really isn't testing our application, and then we can link to this story from that story, your thoughts?

**Comment by allanto-ah** [comment]
@alexseelig Yeah, that story has been tested and closed. The link to the EZR form from the MHV landing page is working as expected. I'm going to link it here and close this ticket: [72763](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72763

**Comment by alexseelig** [comment]
@allanto-ah awesome, thank you sir!
