### ISSUE TITLE
User flow diagram for integration

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#80895]
### User story

As a Cartography team member, I want to document the UX flow of the integrated portal, so that teams have a single source of truth for the intended experience.

### Notes
- Design portal-wide sitemap that communicates current state and the impending future state (point of integration)
- Create user flow w/ branching logic and routing info annotations where possible
- Surface jobs to be done
- Show concerns for Vista v. Cerner/OH users
- Come up with QA use cases
  - VistA only user
  - Hybrid user
  - Cerner/OH only user
  - Unauth user
  - Mobile user
  - AT user
  - User who is shadow banned from some tools
- Run by Wes, Mikki and Kaitlin
- Determine how to get tool teams aligned around flow – possibly a meeting like Bryan organized for downtime alerts?

Possible tasks:
- Create high-level sitemap diagram
- Create user flow diagram for various test scenarios (above) that illustrates jobs to be done for tool teams

## Acceptance criteria
- [x] [Current + future state sitemaps documented](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713450017254/6daf1f320cba1054fdfd840e4a7c881dda87120c?sender=uf94a77a19aaf687331c09367)
- [x] [User flows documented](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1667322271773/26b9a1c19e3d4f1dbcc1dba4e4218a56f0fbb75a?sender=uf94a77a19aaf687331c09367) - updated Phased UX Mural
- [x] Iterated with feedback from Wes, Kaitlin
- [x] Determined a way (meeting?) to circulate to tool teams

**Comment by sterkenburgsara** [comment]
[Sitemap schematic in MURAL here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713450017254/6daf1f320cba1054fdfd840e4a7c881dda87120c?sender=uf94a77a19aaf687331c09367)

**Comment by sterkenburgsara** [comment]
Per Kaitlin: 
* We may not need a diagram, but just a clear to-do list for health tool teams (via Slack is okay) where POs are cc'ed for visibility. From there, Kaitlin & POs will ensure that jobs to be done for integration are ticketed during PI planning


Does that sound right, @wesrowe? Do you still want this missing artifact that creates user flows for the test user cases that can inform QA?

**Comment by wesrowe** [comment]
I think this is a compelling document, but I'll let @allanto-ah answer whether it meets his needs for identifying test cases. I feel we don't need to QA every link within tools ourselves, that should fall to tool teams. But we have a strong point of view on how some flows work. Maybe we could talk in 16th minute one day about what a reasonable heuristic is for determining if Cartographers QA a particular bit of functionality.

**Comment by sterkenburgsara** [comment]
Other task (capturing User flows) I completed by updating the existing Phased UX diagram to reflect the integration. [See that here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1667322271773/26b9a1c19e3d4f1dbcc1dba4e4218a56f0fbb75a?sender=uf94a77a19aaf687331c09367).
