### ISSUE TITLE
CC Staging review: Secondary nav

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#80907]
### User story

As a Veteran, I want the Cartography team to take the final secondary nav implementation through staging review, so that I can feel confident of VA governance buy-in on the design and implementation quality.

### Notes
- [Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71571)
- We will not go to collab cycle until secondary nav is implemented and testable on SM, Meds and Appts

Possible tasks:
- Prep artifacts
- Schedule

```[tasklist]
## Acceptance criteria
- [x] Staging review meeting scheduled: Thursday, 5/30 @ 3:30pm ET
- [x] Test plan (and run) _and linked in CC ticket_ - @allan
- [x] Regression test plan _and linked in CC ticket_ (and run) - @allan
- [x] Link to e2e tests _and linked in CC ticket_
- [x] Test coverage report _and linked in CC ticket_
- [x] Coverage for references _and linked in CC ticket_
- [x] A11y artifact prepared _and linked in CC ticket_
```

**Comment by sterkenburgsara** [comment]
Will need test user accounts for the following scenarios: 
* unregistered user (should not see secondary nav)
* registered user sees it installed on all 5 locations:
  * Home (landing page)
  * Appointments
  * Messages
  * Medications
  * Medical records (temp landing page)
 * registered user / Cerner facilities in profile (sees secondary nav + Cerner gating alerts on 3 tool pages)
   * Home (landing page) - no alerts  
   * Appointments (sees Cerner alerts on this landing page)
   * Messages (sees Cerner alerts on this landing page)
   * Medications (sees Cerner alerts on this landing page)
   * Medical records - no alerts
  * user w/o verified identity (LOA1/2) - doesn't meet criteria, sees "verify your identity" alert on landing page and secondary nav is suppressed
    * if a user meeting this criteria types in a specific URL deeper than /my-health, they get route-guarded up to the landing page
