### ISSUE TITLE
Analytics Implementation or QA Support for [Claim Status Tool]

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#80920]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Benefits Management Tools Team

- **Product Name**

    - Claim Status Tool
      
- **When is the launch date?**
    - 4/29

- **Provide the link(s) for Product/Page urls**
  
    - va.gov/track-claims/your-claims

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
Essentially, we want to track the document submission conversion funnel. 

URL Path: 

https://staging.va.gov/track-claims/your-claims > https://staging.va.gov/track-claims/your-claims/xxxxxx/status > va.gov/track-claims/your-claims/xxxxxxx/document-request/xxxxxx  

The "xxxxx" in each URL denotes a unique claim ID. 

Description of User Behavior

1. User lands on CST listing page
2. User clicks "View Details" on a claim with an open request link
3. User clicks "View Details" on an open evidence request link
4. User Adds a File and then clicks "Submit Files For Review" button

    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Staging test user information: Row 25 (Kyle Cole) here: https://staging.va.gov/track-claims/your-claims/600471552/document-request/467558

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jestutt** [comment]
This is for reviewing the funnel in GA (see [Slack Support Ticket convo)](https://dsva.slack.com/archives/CBU0KDSB1/p1713359675256469) and I'd recommend an Explore Funnel report for this one. 

cc @johnny-jesensky-adhoc

**Comment by jestutt** [comment]
@jacobworrell Thanks for the quick chat this morning. As requested, here are the instructions for you to recreate the report in the GA UA Production View (VA.gov - Production --> All VA.gov Website Data [Production]). 

1 -  Click on **Explore** near the bottom of the menu on the left side of the window and then click on the **Blank** option under 'Start a new exploration'
![Screenshot 2024-04-26 at 11 58 43 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/0d44a790-10de-4dd6-90e3-264554c73967)

2 -  Under the **Variables** menu, click under **EXPLORATION NAME** to enter the report name. I used 'Claims Status Tool - Doc Submission Funnel'

3 -  Under the **Settings** menu, click the dropdown under **TECHNIQUE** to select 'Funnel exploration'

4 -  You'll find a **STEPS** section appear under the **Settings** menu. Click on the pencil icon to add/edit the funnel steps

5 -  Here, you'll enter in the conditions for each step of the funnel using the blue plus signs to add steps as you go

> Step 1: CST listing Page  (change the step names as you see fit)
> Page matches regex ^www\.va\.gov\/track-claims\/your-claims(|\/)(|\?postlogin\=true)$
> ![Screenshot 2024-04-26 at 12 10 28 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/304b3251-fa61-4d42-9803-3ada29573b7f)
> 
> Step 2: Claims detail page
> Page matches regex ^www\.va\.gov\/track-claims\/your-claims\/[0-9]{6,11}\/status\/$
> AND
> Previous Page Path matches regex ^www\.va\.gov\/track-claims\/your-claims(|\/)(|\?postlogin\=true)$
> ![Screenshot 2024-04-26 at 12 10 52 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/7fe709e3-5010-4f7a-acea-a5b107ece1b9)
> 
> Step 3: Evidence request page
> Page matches regex ^www\.va\.gov\/track-claims\/your-claims\/[0-9]{6,11}\/document-request\/[0-9]{4,8}\/$
> AND
> Previous Page Path matches regex ^www\.va\.gov\/track-claims\/your-claims\/[0-9]{6,11}\/status\/$ 
> ![Screenshot 2024-04-26 at 12 10 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/a4c1f6fb-ee7c-4935-948d-dfc9a0331239)
> 
> Step 4: Claim files page
> Page matches regex ^www\.va\.gov\/track-claims\/your-claims\/[0-9]{6,11}\/files\/$
> AND
> Previous Page Path matches regex ^www\.va\.gov\/track-claims\/your-claims\/[0-9]{6,11}\/document-request\/[0-9]{4,8}\/$
> ![Screenshot 2024-04-26 at 12 11 09 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/f198aa6e-1108-4eb8-a343-9802fe4980d9)
> 
> Click **Apply** to save your changes and return to the report view. 

To share this report so other GA users can view it, click on the people icon in the upper right of the report and then click share. 
![Screenshot 2024-04-26 at 12 15 47 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/cb80c1c3-4b65-48fd-852c-6157d0b7fa9d)

Please DM me on Slack if you have any questions while setting up the Production report. I'll follow up next week with the GA4 version of these instructions.

**Comment by johnny-jesensky-adhoc** [comment]
Catching up on the latest of this and may have missed some context without being in the huddles.  

@jacobworrell  -- **do we have everything you need from us on this?**

FYI @jestutt

**Comment by johnny-jesensky-adhoc** [comment]
@jacobworrell  --Going to close this ticket out for the work needed from our team on this for sprint reporting purposes . Feel free to pass any additional questions to our vfs-analytics Slack channel, or in 'Office Hours' -- moving this to Done.

FYI @jestutt
