### ISSUE TITLE
Update the "Where to Attend" Text for VVC Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80939]
## Description
The "Where to Attend" text in the details for a VVC appointment is misleading because the Veteran is supposed to use a tool to connect via video, not show up at a facility.

<img width="337" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1edf2155cf63c172198c35085db3387570bb1fd0/image.png" alt="image.png" />

## Tasks
- Update the wireframe(s)
- Insert a link to the wireframe(s) in the [FE work ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80942)

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/80939?planning-poker) with Zenhub @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
@loripusey pointed

**Comment by benbrasso-agile6** [comment]
- [pre-check-in in person detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-17716&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [pre-check-in phone detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-20615&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [pre-check-in CVT detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2053-5236&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [pre-check-in VVC or video at home detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-22891&mode=design&t=Yv8SXWdB9JWa2PMh-4)
