### ISSUE TITLE
[CHIP] SPIKE: How Can we Integrate with the New CES Modality Service

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80944]
## Tasks
- Determine how we will be able to integrate with the new CES Modality Service
- Determine when the new service will be ready for us to test with
- Create work tickets as necessary to do the integration

**Comment by loripusey** [comment]
@brianseek when you get back, we need to determine if we are ready to integrated with this service and add some detail & estimate to this ticket

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/80944?planning-poker) with Zenhub @brianseek

**Comment by brianseek** [comment]
I think this is less than a 5. I was thinking 2, 3 max.

**Comment by loripusey** [comment]
I picked 5 because that was how much it would take to get to our FE capacity and I wasn't sure if we could bring anything else in; let's discuss at planning
