### ISSUE TITLE
IA Request: Add decision reviews link to benefit hub pages

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#8094]
Because users may disagree with claim decisions on different kinds of benefits (other than disability benefits) we need to provide links to the [decision reviews hub page](https://www.va.gov/decision-reviews/) from the following benefit hub pages:
![image](https://user-images.githubusercontent.com/53535663/79463104-656b3b80-7fc6-11ea-8fe1-2f744259dcf0.png)

**Comment by mnorthuis** [comment]
Is this duplicative to #8276 ?

**Comment by stephorkandatx** [comment]
@mnorthuis I believe it is duplicative. @lwalsh617 any content we need to save on this ticket, or can it be closed out and we move forward with #8276 ?

**Comment by stephorkandatx** [comment]
I'm going to close this as a dupe, but will add a reference to #8276's comments in the event we need to pull it back
