### ISSUE TITLE
Update the "Where to Attend" Text for VVC Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80942]
## Description
The "Where to Attend" text in the details for a VVC appointment is misleading because the Veteran is supposed to use a tool to connect via video, not show up at a facility.

## Wireframes
- [pre-check-in in person detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-17716&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [pre-check-in phone detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-20615&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [pre-check-in CVT detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2053-5236&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [pre-check-in VVC or video at home detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-22891&mode=design&t=Yv8SXWdB9JWa2PMh-4)

## Tasks
- Update per the wireframe(s)

**Comment by benbrasso-agile6** [comment]
@wullaski I added the links here; note - this is not in current sprint
