### ISSUE TITLE
Write and socialize revised and focused ADR for PEGA integration

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#80948]
As a reviewer of the callback API implementation, I need an overview of background decisions so that I understand the current state of the design.

### Acceptance criteria
- There is an updated and scaled back discussion of our architectural decisions for implementation of the callback API
- Technical specs and sketches of implementation details are pull out into a separate document 
- Share with OCTO engineering in order to get input
- Bring updated documentation to Platform Security office hours
- Share with Robbie Holmes for feedback

### Additional info
An architectural decision record (ADR) is a document that describes a choice the team makes about a significant aspect of the software architecture they’re planning to build. Each ADR describes the architectural decision, its context, and its consequences.

**Comment by baltes** [comment]
This story is for paring down the ADR to a record of the implementation we've decided on

**Comment by balexandr** [comment]
Sent to Robbie today, will get reviewed by EOD

**Comment by balexandr** [comment]
@baltes Approved by Robbie

**Comment by balexandr** [comment]
@baltes Approved by Robbie

**Comment by balexandr** [comment]
Waiting for approval by someone from the security team as Gary is OOO.

**Comment by balexandr** [comment]
@baltes Kyle Crockett approved.
