### ISSUE TITLE
Write spec to share with DOCMP team

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#80952]
As a DOCMP team member, I need a means of sending the status import attempts into PEGA back to VA.gov so that VA.gov has status information about documents sent to PEGA.

Also, I would like a well-defined, well-documented, and easily consumable API info so that there is Improved developer experience for both internal and external consumers

### Acceptance criteria
- There is a concise specification that we can share with DOCMP so that they know how to configure their call to the API
- DOCMP team members understand how to make a call to our callback endpoint
- Cindy can move forward with her llambda function

**Comment by baltes** [comment]
This story is to provide our API spec to the DOCMP team

**Comment by balexandr** [comment]
@baltes Can we create another placeholder MarkDown file for me to fill out for PEGA?

**Comment by cloudmagic80** [comment]
@baltes  Is this the story for the swagger docs?

**Comment by baltes** [comment]
@balexandr I'm not sure exactly what you mean, but you're welcome to create anything that you need here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/champva

There's nothing special about this location, but this is where I've been adding things.

**Comment by baltes** [comment]
@cloudmagic80 The goal is to be able to tell Cindy and/or others in DOCMP how to hit our endpoint. Whether we use swagger or something else is an engineering call. But yeah, that's covered by this user story.

**Comment by cloudmagic80** [comment]
Endpoint: 
`post '/v0/ivc_champva_forms/status_updates'`

**Comment by baltes** [comment]
@cloudmagic80 Is there a swagger link for this?

**Comment by cloudmagic80** [comment]
https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/ivc_champva_forms/Endpoint_for_creating_a_new_form
