### ISSUE TITLE
Write overview of technical implementation of callback API

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#80953]
As a DOCMP team member, I need a means of sending the status import attempts into PEGA back to VA.gov so that VA.gov has status information about documents sent to PEGA.

### Acceptance criteria
- There is a document to guide discussion with OCTO platform team members so that they understand our architecture and design
- Share with OCTO engineering in order to get input
- Bring updated documentation to Platform Security office hours
- Share with Robbie Holmes for feedback

Placeholder file in github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/callback-api-technical-spec.md

**Comment by baltes** [comment]
This story is for taking technical implementation details out of the ADR and capturing them in a separate document.

**Comment by balexandr** [comment]
@baltes I moved the implementation into it's own file (you posted above) and will be updating it as a living document so people can see what columns exist, validations set, and overall structure

**Comment by cloudmagic80** [comment]
@balexandr  The link to the document doesn't work

**Comment by baltes** [comment]
@balexandr @cloudmagic80 added the md extension to the filename in the link, see if that helps.

**Comment by balexandr** [comment]
@baltes Approved by Robbie

**Comment by balexandr** [comment]
Waiting for approval by someone from the security team as Gary is OOO.

**Comment by balexandr** [comment]
@baltes Kyle Crockett approved.
