### ISSUE TITLE
CT-103: Only display 103 indicator on certain institutions.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8095]
As a developer, I need to remove the 103 indicator from non-relevant institutions because it is only applicable to institutions that meet specific criteria.

## Assumptions
1. The business rules in #7843 are still applicable.
2. This work is completed behind the feature flag #7773.

## Acceptance Criteria
1. The "Institution Summary" area of the "Additional Information" section of the institution profile page ONLY displays the "Protection against late VA payments:" indicator for institutions where the WEAMS facility codes starts with the following 2 digit pairs:
    - 11
    - 12
    - 13
    - 21
    - 22
    - 23
    - 31
    - 32
    - 33

## Supporting Artifacts:
1. [Sect 103 Facility Code.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4583149/Sect.103.Facility.Code.xlsx)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/12316
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/646
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/647

Can be tested with vets-website branch `section-103-ihl` and gibct-data-service branch `section-103-ihl`

**Comment by delli-gatti-michael** [comment]
Need to determine what qualifies as "IHL" before this can be tested

**Comment by delli-gatti-michael** [comment]
Tested by TestRail Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/595

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes now live in Dev. Closing this issue
