### ISSUE TITLE
10-7959f-2: Write front end unit tests

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#80960]
Deployment to production requires unit test coverage of at least 80%. Create necessary unit tests for 10-7959f-2 to ensure coverage should any issues arise.

Acceptance criteria

- Write new unit tests in vets-website for each page that test render, # of fields & error messages
- Unit test coverage report shows >= 80%

**Comment by reiting** [comment]
<img width="1021" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7e906072a6f640d44783baed7296978de91820b/Screenshot%202024-09-19%20at%2011.03.55%E2%80%AFAM.png" alt="Screenshot 2024-09-19 at 11.03.55 AM.png" />

**Comment by reiting** [comment]
@baltes @marywang2 this has been merged. It's not really testable visually since it is just tests, but you can see from the screenshot above that we're good.
