### ISSUE TITLE
CF: Datalayer updates for the Profile Page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#8097]
As a member of the education services team, I want to be able to utilize google analytics so that I can track how people are utilizing the caution flag enhancements made to the profile page of the Comparison Tool. 

## Assumptions
1. When this story is closed, a review of the changes should be requested in #8001 for the Analytics Team to review. 

## Acceptance Criteria: 
1. Updated requested to the data layer as part of #8001 have been implemented in order to better track analytics as they relate to the following actions on the Comparison Tool Profile Page: 
a. Clicking on header caution flag jump link (view details below link) populates the ' Jumplink - This school has a cautionary warning' in the data layer based on caution flag title.
b. Click on a caution flag link populates the alertBoxHeading in the data layer based on caution flag title.
c. Clicking "visit the About This Tool Page" link populates the value of the `edu-action` dataLayer field to "about-this-tool"
d. Clicking "student complaints" link populates the value of the `edu-action` dataLayer field to "student-complaints"
e. Clicking either of the "All campuses" links populates the value of the `edu-action` dataLayer field to "all-campuses"

### Datalayer Requirements 
Description of Interaction | Screenshot | Datalayer Push
------------ | ------------- | -------------
Click on 'view details below' inside of warning alert box | ![image](https://user-images.githubusercontent.com/48527022/79370194-40bc8880-7f20-11ea-86a3-d7db7e6a84fb.png) | ```dataLayer.push({```<br>```'event':'nav-warning-alert-box-content-link-click',```<br>```'alertBoxHeading': ' Jumplink - This school has a cautionary warning'```<br>```});```
Click on 'learn more about this school's accreditation' | ![image](https://user-images.githubusercontent.com/48527022/79370512-d1936400-7f20-11ea-94b5-11c32fe1bd79.png) | ```dataLayer.push({```<br>```'event':'nav-warning-alert-box-content-link-click',```<br>```'alertBoxHeading': 'School has an accreditation issue'```<br>```});``` <br> **-Populate `alertBoxHeading` with the proper heading for each of the variations of cautionary flags, `nav-warning-alert-box-content-link-click` should remain consistent**
Remaining clicks within "Cautionary Information" accordion | ![image](https://user-images.githubusercontent.com/48527022/79371757-e07b1600-7f22-11ea-87c0-4a21efc1b13b.png) | ```dataLayer.push({```<br>```'event':'education-navigation',```<br>```'edu-action': 'about-this-tool'```<br>```});``` <br><br> **Other `edu-action`'s include**: <br> - `student-complaints` <br> - `all-campuses`

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12280

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-21 at 1.10.03 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/45904123-1127-4889-8bd6-016997982527)
##
![Screen Shot 2020-04-21 at 1.11.13 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c479394a-5588-49f8-a813-bddc2fc38449)
##
![Screen Shot 2020-04-21 at 2.06.35 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/35708934-16ca-4f5b-a2ae-d352c8305158)
##
![Screen Shot 2020-04-21 at 2.07.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/114fe23b-5b47-44bc-b643-392097b808d4)
##
![Screen Shot 2020-04-21 at 2.08.05 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aa644326-5391-49b9-91ee-70b8dec39390)

**Comment by sonntag-adam** [comment]
In staging, closing story.
