### ISSUE TITLE
Implement SM & Meds landing page links for integration

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#80971]
STATUS: "Meds and allergies" link below needs special handling for Oracle users (probably alert added to /meds/alerts

### User story

As a Veteran, I want SM and Meds links on the MHV landing page to send me to tools on VAgov, so that I really get a sense of "trying" the new portal.

As a Cartography team member, I want to have the integration links for SM and Meds ready behind a feature flag, so that we can demo the integration and launch it easily when the time comes.

### Notes
- Appts is already integrated, and Medical records is still on MHV Classic – so only SM and Meds need to have links changed.
- From Carlos's comment in [UX ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/74454):
>## MHV Landing Page Links to Update
> - Messages
>   - Inbox - `/my-health/secure-messages/inbox` 
>   - **Send a new message** - `/my-health/secure-messages/new-message` (need to update link text as well)
>   - Manage folders- `/my-health/secure-messages/folders` 
> - Medications
>   - Refill VA Prescriptions - `/my-health/medications/refill` 
>   - HIDE ~~Track prescription delivery~~ - ** DOES NOT MAP ** to the new app
>   - **Review medications** - `/my-health/medications/` (need to update link text to remove "allergies" reference)

> - Health Records - update title of this box to "Medical records"

 Possible tasks:
- finalize IA
- implement
- QA

## Acceptance criteria

- Tool links for SM and Meds are altered to integrated state when feature flag is turned on
- QA review
- A11y review

**Comment by sterkenburgsara** [comment]
made a couple of updates to link assessment above, holler w/ any q's

**Comment by radavis** [comment]
@sterkenburgsara, Since we aren't changing over Health records/Medical records links in this ticket, can we keep "Health records" as-is, for now?

**Comment by LynneJohnson224** [comment]
per sprint planning meeting, @allanto-ah to QA

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the links are directing the user to the correct pages for SM and Meds on the MHV on va.gov landing page
