### ISSUE TITLE
As a 10-10d applicant I need to include more than a total of 3 applicants on the form

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#80989]
**Implementation Plan**
1. Fixture JSON to be > 3 applicants
2. Update model test (See vba_40_0247_spec.rb)
3. Port over https://github.com/department-of-veterans-affairs/vets-api/blob/6512caf3f5b3ee1d7e822f1037971406bb7e9437/modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb#L101-L118 and add logic on a per model basis as the key (applicant v. clamant) that needs looping will differ. 
- This new PDF will be treated as a new attachment(s).
```
def get_attachments
      attachments = []

      additional_address = @data['additional_address']
      if additional_address
        file_path = fill_pdf_with_additional_address.   <--------------- But fill_pdf_with_additional_applicants
        attachments << file_path
      end
```
- Get # of applicants/claimants and loop over them so additional attachments are generated
- Confirm multiple PDFs exist in the repo and tests pass

**Comment by cloudmagic80** [comment]
The initial estimate is 3-4 Sprints. 
There are a few ways to tackle this:
Option 1: update the fixture JSON to have more than 3 applicants, loop through the submit function based on how many applicants there are and update the test to expect the extra form/forms. Probably test with 10-10d since 7959a isn’t up yet.

Then maybe create a GeneratePDF service module.

**Comment by balexandr** [comment]
SimpleForms also mentioned they do something similar with addresses https://github.com/department-of-veterans-affairs/vets-api/blob/6512caf3f5b3ee1d7e822f1037971406bb7e9437/modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb#L101-L118 that we could leverage/repurpose

**Comment by balexandr** [comment]
@cloudmagic80 You worked on the attachment_ids portion. Can you update the plan above with anything that may need to be considered with the metadata?

**Comment by cloudmagic80** [comment]
You can change the metadata. yes

**Comment by balexandr** [comment]
[bd2ea1ef-0110-48bc-b513-28532e80ceec_vha_10_10d-tmp.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ddeb0ea7d13349e9ee05e3f8ad095f06f78e435/bd2ea1ef-0110-48bc-b513-28532e80ceec_vha_10_10d-tmp.pdf)
[bd2ea1ef-0110-48bc-b513-28532e80ceec_vha_10_10d_additional_applicants-tmp1.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a34125eda809864a7d03fc0d52ad4ff7aa6c8f39/bd2ea1ef-0110-48bc-b513-28532e80ceec_vha_10_10d_additional_applicants-tmp1.pdf)
[bd2ea1ef-0110-48bc-b513-28532e80ceec_vha_10_10d-tmp2.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5QQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c37281e5bd0dffafbf0deb4d8b265a42d8f2371a/bd2ea1ef-0110-48bc-b513-28532e80ceec_vha_10_10d-tmp2.pdf)

These files are from a 10-10D test with 6 applicants and an optional uploaded item.

**Comment by balexandr** [comment]
@baltes  We need a corresponding FE ticket for this work for 10-10D
CC: @cloudmagic80

**Comment by baltes** [comment]
Front end ticket is here: https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/85713

**Comment by cloudmagic80** [comment]
I'm putting this ticket back into In Progress. The metadata isn't correctly labeled.

**Comment by cloudmagic80** [comment]
Completed:
https://github.com/department-of-veterans-affairs/vets-api/pull/17135

**Comment by cloudmagic80** [comment]
Run all Unit test.
Run e2e test for these scenarios:
A: 1010D with 1 applicant.
B: 1010D with 4 applicants.
C: 1010D with 1 applicant with 1 social security attachment
D: 1010D with 4 applicants with 4 social security attachments and 4 birth certificates
E: 7959C with 1 applicant
F: 7959C with 1 applicant and 1 attachment
G: 7959F1 with 1 applicant
H: Check all PDF output locally.
I: Check all PDF output in S3
J: Check all metadata in S3

**Comment by baltes** [comment]
Awesome, thanks for all the detail on QA @cloudmagic80
