### ISSUE TITLE
Add `useWebComponentFields: true` to the documentation

### ISSUE THREAD

**Issue by zack** [department-of-veterans-affairs/va.gov-team#80986]
### Description
With the new V3 web component rollout, many teams are going to encounter issues where their forms, tested by the form tester utility, break. There exists an undocumented configuration option for the form tester to allow it to seamlessly work with the new V3 elements. I propose adding this configuration option to the documentation for the form tester utility page.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/form-tester-utility

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS Team

**Comment by jknipes** [comment]
Hi @zack, thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Reached out to @caw310 for possible collaboration

**Comment by humancompanion-usds** [comment]
This is an issue for the Forms team. @tbaker1026 - Can you queue this up for Robert and Nick to take a look at? Thanks.

**Comment by rhasselle-oddball** [comment]
hi, this was definitely needed when it defaulted to false, but now we we're able to push this to be true by default in this PR https://github.com/department-of-veterans-affairs/vets-website/pull/28969. So maybe not needed any more?

**Comment by tbaker1026** [comment]
@zack @humancompanion-usds - See above, let us know if it is still an issue

**Comment by humancompanion-usds** [comment]
A sensible default is great! But that does not obviate the need for documentation. Perhaps just reach out to Platform content ask them to document this?

**Comment by humancompanion-usds** [comment]
@rhasselle-oddball or @ndsprinkle should be your SMEs @jknipes

**Comment by laucon** [comment]
I think we can close this ticket. It sounds like we no longer need to edit the document at all, it turns out. :)

**Comment by jknipes** [comment]
@zack we have made the updates to this document, Thank you for bringing this to our attention! We are closing this issue as _Done_
