### ISSUE TITLE
FE/DE | Profile | Ch33 Direct Deposit Migration | Alert for Downtime

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#80982]
## Background

We need to get up some sort of alert advising that the entire direct deposit page will not work starting the 26th. 

We need copy - Chante working on copy w/Sitewide. 

ungate : `profile_show_direct_deposit_single_form_alert` < currently conditional to just users who receive both - modify this to display to everyone
- will show on hub and direct deposit pages 
 -as part of the ungating, we should also make sure this toggle `profile_show_direct_deposit_single_form_edu_downtime` isn't blocking the alert. 

`profile_hide_direct_deposit_comp_and_pen`

Show

**Comment by clantosswett** [comment]
Below is the copy for the upcoming direct deposit downtime and the message once all direct deposit functionality is down. This includes dates and times but we've tried to phrase it to show that it's not set in stone. CAIA is also going to be figuring out which other pages it might make sense to put these messages beyond the profile and profile hub and will get back to us with any questions.

## Copy for Upcoming Direct Deposit Downtime:

**Upcoming site maintenance for direct deposit**

We’ll soon be doing some work to update our systems for online direct deposit management. We expect the maintenance period will last for 5 days. 

During this time, you won’t be able to manage your direct deposit information online. You’ll still be able to manage your information for disability compensation, pension, or education benefits by phone. Call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Start:** Saturday, April 26, 2024, at TBD
**End:** Thursday, May 2, 2024, at TBD

## Copy for when direct deposit downtime is happening

**You can’t manage your direct deposit information right now**
We’re updating our systems for online direct deposit management. We expect to complete this work by **Thursday, May 2, 2024,** at TBD.

If you need to manage your direct deposit information for disability compensation, pension, or education benefits during this time, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by adamwhitlock1** [comment]
Okay, so for the upcoming downtime copy. Should that go in place of the alert we currently have?

![Screenshot 2024-04-19 at 9 48 16 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/ef42b933-71b0-4f8c-8163-9ba5763c958e)

I can update the current downtime content, but curious on how I should handle the upcoming message, and when that should go up? I would assume we would put it up asap @mtcA6 and @andaleliz what do yall think?

**Comment by mtcA6** [comment]
Yep I would push the change today if we can

**Comment by adamwhitlock1** [comment]
I don't think today will happen since the deployment goes out in 30 min, but I'll see what I can do.

**Comment by andaleliz** [comment]
@adamwhitlock1 just FYI I updated the mock-ups in Figma with the language Chante provided earlier today.  There wasn't an "upcoming downtime" message before so [now we have it](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=972-4456&mode=design&t=Oaz0lVu4pJRbLMBI-11).

**Comment by adamwhitlock1** [comment]
Hmmm so if the content around upcoming downtime essentially replaces the existing alert content that says "By April 20, 2024, you must have a single bank account for all VA benefit payments" then that would also show up on the Profile Hub page, and would also include the link to 'Check your direct deposit information' since the alert is the same component in both places.

I feel like this logic may need to be reworked

**Comment by andaleliz** [comment]
IMO we could take the alert off the hub page, since we don't need to draw attention to the DD section in order for them to take a particular action.  They should know the section is under maintenance once they get there, but idk that they need to think about that on the hub.

What do yall think?

**Comment by mtcA6** [comment]
We want them to take an action between now and 4/26 when we have to bring down the page. So i think linking and leaving this on the hub is okay. Pasting some more details below 

--- 

Start: Saturday, April 19, 2024, at TBD
End: Thursday, April 26th, 2024, at TBD

### Copy for Upcoming Direct Deposit Downtime:**
**Upcoming site maintenance for direct deposit**

We’ll soon be doing some work to update our systems for online direct deposit management. We expect the maintenance period will last for 5 days.

During this time, you won’t be able to manage your direct deposit information online. You’ll still be able to manage your information for disability compensation, pension, or education benefits by phone. Call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.


^^^ We can show this on the direct deposit page and the Hub. 

---

Start: Saturday, April 26, 2024, at TBD
End: Thursday, May 2, 2024, at TBD

### Copy for when direct deposit downtime is happening
**You can’t manage your direct deposit information right now**

We’re updating our systems for online direct deposit management. We expect to complete this work by Thursday, May 2, 2024, at TBD.

If you need to manage your direct deposit information for disability compensation, pension, or education benefits during this time, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.


^^^this also only needs to be on the direct deposit page.

**Comment by andaleliz** [comment]
>We want them to take an action between now and 4/26 when we have to bring down the page.

The upcoming downtime message doesn't tell them any action we want them to take. So do we need some combination of the current alert and what Chante provided, if there's an action we want them to take?

>Start: Saturday, April 19, 2024, at TBD

April 19 is today, Friday.  I also just realized that the copy Chante provided say "Saturday, April 26"

April 26 is a Friday.  Should it say Friday, or should the date be April 27?

**Comment by clantosswett** [comment]
I think it is less that we need them to take an action between now and the 26th but instead giving the users who might not be on the profile to update their DD awareness that the feature won't be available. So they can choose to make updates given that new bit of information. 

And yes, the 26th is a Friday. Thank you for catching that!

**Comment by mtcA6** [comment]
Should we turn this off until the new copy goes out? 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/2249451c-1831-4663-8c49-926f4e668e2b)

**Comment by mtcA6** [comment]
@adamwhitlock1 can you let me know when the updates to the copy are made so I can send an update to an email thread alerting folks to the changes? If you can share a screen grab of the alert as well that would be incredibly helpful so I can pass that along too.

**Comment by adamwhitlock1** [comment]
I will get it out today for the daily deployment.
