### ISSUE TITLE
Process new Trexler File

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#80980]
## Background
There is a newly accredited VSO - National Montford Point Marine Association, Inc. and we should keep an eye out to confirm this VSO is present in the forthcoming Trexler File this Friday. 

I am seeing the VSO listed in [OGC's accreditation tool](https://www.va.gov/ogc/apps/accreditation/accredvso.asp), so I expect this change to have been reflected in the GCLAWS database and be in the Trexler File.

## Tasks
- [ ] Confirm the Trexler File includes this new VSO
- [ ] Process the Trexler File

## Acceptance Criteria
- ARM products remain up-to-date with accredited rep information, including newly accredited parties.

**Comment by holdenhinkle** [comment]
There isn't a new Trexler File to process. I'll check again tomorrow (Friday).
