### ISSUE TITLE
Clone 2019 Disability Rates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8098]
## User Story or Problem Statement
As a user of VA.gov, I need to be able to access rates from prior years, so that I can review previous data.
This work is specific to 2019, as that is the only year that is (currently) housed on VA.gov

## Tasks
- [ ] Perform Clone process to clone the 2019 Disability Rates

## Acceptance Criteria
- [ ] 2019 Disability Rates are available via link on the Disability Rates page, as a cloned/archived page

**Comment by MickinSahni** [comment]
closing as duplicate
