### ISSUE TITLE
Contact Center Review for Claim Status Tool - Claim Details V2

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#80996]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Claim Status Tool - The place veterans go to check the status of pending claims. 

### Launch Date
4/29/2024

### Version Number
1.0

### Product Guide
[Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/Claim%20Status%20Tool%20Product%20Guide.docx)

### Product Video
N/A

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @jacobworrell. I came across the following product guide from 2020 in the VEO SharePoint archive. In light of this, is that version 1 of the guide for the tool/functionality, while your new guide is version 2? If so, I could make a note on the title page to distinguish the new guide as being for the "modernized" tool?

[Claim.Status.Product.Guide.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGgxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24547863147df6863633909af4a02122598348a1/Claim.Status.Product.Guide.docx)

**Comment by starlow00** [comment]
The draft looks good. Sent to VEO for review.

**Comment by starlow00** [comment]
There are no changes from VEO. I've attached the working copy; please use it for future additions and revisions. Thank you!
[VA Claim Status Tool Product Guide v2 SRT 04192024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04644df0103afcda3c1f01d07ea0b55f20eb0026/VA%20Claim%20Status%20Tool%20Product%20Guide%20v2%20SRT%2004192024.docx)
