### ISSUE TITLE
Migrate AskVA data to DOMO

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#80999]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a DOMO user, I need to have the ability to view AskVA data so I can track metrics and report activity to leadership. 

## Hypothesis or Bet
If we can have AskVa data included on the DOMO dashboard we expect to view "At-A-Glance" metrics for all Veteran Support escalated issues in the same document.
## OKR
_Which Objective / Key Result does this epic push forward? Data Consolidation. 

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] Data extraction from AskVA
- [x] Data Transformation (ETL) Extract, Transform, Load 
- [x] Validate data
- [x] Load data 
- [ ] Data testing

**Comment by ATMiddleton** [comment]
Duplicate #80997

**Comment by ATMiddleton** [comment]
All tasks to migrate AskVA data to DOMO are complete.

**Comment by clantosswett** [comment]
Have we created a ticket for the tier 1 data work? If not, let's please add any ticket(s) so we can track through the end of the quarter.

**Comment by ATMiddleton** [comment]
Yes -
https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/95488
Best regards,

Anita
Product Manager
305-522-2306
