### ISSUE TITLE
AWS Access for Norman Shipman

### ISSUE THREAD

**Issue by adhoc-nshipman** [department-of-veterans-affairs/va.gov-team#80993]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Norman Shipman

### Your Email

norman.shipman@adhocteam.us

### Team, Role, and Company of the target individual

Platform Tech, DevOps Engineer, AdHoc

### Product Manager (PM) name and email

Nate Peterson, nate.peterson@adhocteam.us

### Product Owner (PO) name and email

Aparna Nittala, aparna.nittala@va.gov

### Desired AWS Access

DevOps

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation
<img width="603" alt="Screenshot 2024-04-17 at 2 47 20 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/164942619/42fc7cee-5145-4199-86d6-f07c225c476f">

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Account created and credentials sent to user
