### ISSUE TITLE
Implement announcement banner for upcoming DSLOGON outage

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8100]
In order to support the upcoming DSLOGON outage, 
We need to perform some development work to set up a sitewide announcement banner so that users of VA.gov are made aware of the scheduled outage window

Engineering:
- [ ] Content from Peggy (might be existing content from the unexpected DSLOGON downtime content recently, but pared back a bit)
Advance sitewide notification promo announcement banner:
- [ ] Show 5 days in advance, starting Monday, April 20, to the point of DSLOGON downtime starting, April 25, 9:00 a.m. ET.
- [ ] 60 minute countdown
- [ ] During DSLOGON downtime, show the during message. (Sign in modal will show down message at this point.)
- [ ] After downtime, remove the banner

Acceptance Criteria:
- [ ] A maintenance message displays in the announcement banner that alerts users to the upcoming scheduled outage window (need to confirm the content)
- [ ] On production, the banner will begin to display on April 20th starting 9:00a.m ET through the start of the outage at April 25, 9:00a.m ET
- [ ] A 60 minute countdown will appear to users on April 25, 8:00a.m. ET
- [ ] During the downtime, there will be a downtime message
- [ ] After the downtime is over, there will not be an announcement banner re: DSLOGON shown to users

-----
From the Epic: 

#### Before April 20 9am EST

Don't show.

#### April 20 9am EST - April 25 7:59:99am EST

`We'll be doing site maintenance on ${formattedStartsAt} until ${formattedExpiresAt} You won’t be able to sign in or use some tools during this time.`

#### April 25 8am EST to April 25 8:59:99am EST

`Scheduled maintenance starts in ${minutesRemaining} minutes. If you’re filling out a form, sign in or create an account to save your work.`

#### April 25 9am EST - April 26 8:59:99am EST

`We're doing work on VA.gov. If you have trouble using online tools, check back after ${formattedExpiresAt}`

#### After April 26 9am EST

Don't show.

**Comment by kelsonic** [comment]
PR is open, will modify the PR once we get an update for the downtime messaging content.

**Comment by peggygannon** [comment]
@kelsonic and @jenniferlee-dsva Please see below for DS Logon downtime messaging: 

**Advanced message**

DS Logon will be unavailable from Sat. 4/25, 9:00 a.m. to Sun. 4/26, 9:00 a.m. ET. Please use ID.me or MyHealtheVet to sign in or use online tools during this time.

**Countdown message**

Scheduled maintenance on DS Logon will start in 60 minutes. You can still use ID.me or MyHealtheVet to sign in or use online tools.

**Sitewide during downtime**

DS Logon is down for maintenance. Please use ID.me or MyHealtheVet to sign in or use online tools. We hope to finish our DS Logon work by Sunday 4/26 at 9:00 a.m ET.

**During downtime on sign in MODAL**

DS Logon is down for maintenance. Please use ID.me or MyHealtheVet to sign in or use online tools during this time. We hope to finish our DS Logon work by Sunday 4/26 at 9:00 a.m ET.

**Comment by annaswims** [comment]
FYI - all login-related services (MVI,MHV, ID.me DS Logon) have automated downtime banners  https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/DS_logon.md#outage-status-and-maintenance-windows
