### ISSUE TITLE
Message Try-me phase on landing page, w/ opt-out

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#81003]
### User story

As a Veteran who is visiting the mhv on va.gov landing page for the first/second time, I want to know what's new on mhv on VAgov and why without having to seek out this information, so that I am inspired to trust the VA with my health.

_Does opt-out message go here?_

### Notes
Update: 4/18 Kaitlin provided a list of topics that octo would want Veterans visiting the MHV landing page to be informed about.

> For the integration we want to:
> - make the transition of MHV to [VA.gov](http://va.gov/)  clear to the user on the LP
> - make it clear to the user that they can still go back to the MHV Classic experience and remain there to get all their tools if they choose, that has not changed yet
> - help the user understand what is on [VA.gov](http://va.gov/) today as a "try me" and what is coming soon but not currently available on [va.gov](http://va.gov/) and you will be directed back to MHV classic or MYVAHealth
> - help a user understand what the future, integrated experience will be, including OH
> - get users excited and interested in all the MHV things they can do on [VA.gov](http://va.gov/) now. So continuing to drive them to the Phase 1 experiences to give us feedback, but give them an option to get to other MHV stuff that still exists on classic

Possible tasks:
- align with Kaitlin on addl-info vs alert components
- get content back from CAIA

## Acceptance criteria

- Designed a component that communicates to landing page users about the MHV to VAgov transition and help them understand what exists on VAgov in this "try me " phase vs. what still remains on MHV classic (work with CAIA on content) = Expandable alert
  - from octo: "as a user who is visiting the mhv on va.gov landing page for the first/second time, i want to know what's new on mhv on VAgov and why without having to seek out this information"
- Updated content just below the H1
- Implement design
- QA review
- A11y review

**Comment by wesrowe** [comment]
updated ticket with ideas from Kaitlin

**Comment by wesrowe** [comment]
@jonathanjnelson, Could you please update this ticket when you have a chance? I'm curious if you've opened a ticket with CAIA so they know it's coming. Also, it would be good to get an engineer's eyes on it as soon as the general shape of the thing emerges. Thanks!

**Comment by jonathanjnelson** [comment]
[Potential designs (Figma here)](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=1115%3A4839&mode=design&t=1XBOCdGlWprnr8WY-1)

**Comment by jonathanjnelson** [comment]
CAIA ticket #81779

**Comment by jonathanjnelson** [comment]
Updated designs. [Figma file](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=1844%3A35667&mode=design&t=2pMUfgoT64TajbJl-1)

**Comment by jonathanjnelson** [comment]
We plan to present mostly approved content to OCC today 5/8 for further feedback

Updated content and expandable alert 

![Screenshot 2024-05-08 at 11 56 24 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/d2e7496d-284c-4094-b479-ae1f825e1a4b)

Medical records 

<img width="697" alt="Screenshot 2024-05-08 at 11 06 59 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/77c4fa8b-5fdb-4952-8044-d571db167cf6">

**Comment by wesrowe** [comment]
This is out to Kaitlin for finalization/approval.

**Comment by jonathanjnelson** [comment]
@jzucadi Please see most current annotated [Figma file](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2101%3A30162&t=VNFYosgRvmOnzFeU-1)

**Comment by jonathanjnelson** [comment]
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2020e7eaa9e0ea5f0d71ff30911732ecc2fc2ea4/Screenshot%202024-05-13%20at%2011.55.23%E2%80%AFAM.png" alt="Screenshot 2024-05-13 at 11.55.23 AM.png" />

**Comment by jonathanjnelson** [comment]
@jzucadi Slight update for the link text only in the expanded alert. Designs are updated. Please let me know if you have any questions. 


<img width="872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba4bc2b87a81ffa823a2fcd92ed6127e5c1a28b1/Screenshot%202024-05-14%20at%201.18.50%E2%80%AFPM.png" alt="Screenshot 2024-05-14 at 1.18.50 PM.png" />

**Comment by jzucadi** [comment]
Initial Ay11 review yielded 0 issues:
<img width="577" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWplQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d646e9a0efa7750f9594a5126846aad3bd9af0ea/Screenshot%202024-05-14%20at%206.18.18%E2%80%AFPM.png" alt="Screenshot 2024-05-14 at 6.18.18 PM.png" />

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29791
