### ISSUE TITLE
VAOS log additional create appt request params

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#8101]
**User Story**: As a developer I'd like additional params logged during the appointment request create action so I can debug why VAMF is occasionally throwing 500s for it.

**DoD**: A log line prints create appointment requests POST bodies with PII filtered out.

**Comment by lenaecb** [comment]
Revisit after current 500 errors are resolved and VSP updates around Sentry in place.

**Comment by saneshark** [comment]
We can log whether it is null, and we can also log an MD5 hash of the fields in question to verify whether or not the same type of value is causing issues -- but we can't log the actual value.
