### ISSUE TITLE
Burial | Apply link does not work for v2

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81017]
## Issue Description
_The link to apply to for burial benefits on [this page](https://www.va.gov/burials-memorials/veterans-burial-allowance/) breaks when v2 of the burial form is toggled on. The link should take users to [this page](https://www.va.gov/burials-and-memorials/application/530/introduction)._

<img width="286" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJ1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--639971a452f05c300081e930f07fb657b211b55c/image.png" alt="image.png" />

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZ1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbc55dc778747f9abf01feec957a6eb2dec8e181/image.png" alt="image.png" />

---

## Acceptance Criteria
- [ ] When v2 of the form is toggled on, the apply for burial benefit link directs users to the apply page
---

**Comment by DLarson-Oddball** [comment]
Code for this issue has been merged
