### ISSUE TITLE
[Data] 10-10EZR: Establish baseline metrics for EZR using EZ relevant EZ metrics

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#81038]
As a 10-10 team member, I would like to understand how usage metrics for EZR compare to relevant parts of the EZ so that so that I can use this information to interpret how Veterans are using the EZR, and make it easier for them to use.

- [x] Come up with a list of metrics that could be tracked across both EZ and EZR (e.g. TERA Questions, Dependents, Financial Information, Insurance Information, Personal Information)
- [x] Come up with the metrics we would like to monitor across the two forms (e.g. time on page, individual page drop off rate, etc.)
- [ ] **Success: We understands how the first ~month of EZR compares to EZ where relevant, and we have a way to track these things going forward.**

**Comment by luis-simauchi** [comment]
first we can track responses to the TERA questions via this widget on the EZR dash:
https://vagov.ddog-gov.com/dashboard/kjp-9wp-u47/10-10ezr?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1714402206451&to_ts=1715007006451&live=true

**Comment by luis-simauchi** [comment]
net new metrics to measure from DD:
-- click interactions from questions posed on the forms
-- Avg Session Duration
-- Avg Page Views per Session

**Comment by luis-simauchi** [comment]
funnel viz for TERA respondents to completion view now up for both EZR & EZ

**Comment by luis-simauchi** [comment]
Start to Finish % funnel is also available and up in DD

**Comment by luis-simauchi** [comment]
Changes in Avg Page Loading Time

**Comment by luis-simauchi** [comment]
sessions with frustration signals is something we can also track and use for spotting potential engagement issues from the forms

**Comment by luis-simauchi** [comment]
benchmarks:

**Comment by luis-simauchi** [comment]
avg page load time is too different to compare, likely due to the fact that the EZ is substantially larger than the EZR and that lends itself to slower load times
