### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by bpatelctr** [department-of-veterans-affairs/va.gov-team#81036]
### Your Name

Bhavin Patel

### Your Email

bhavin.patel2@va.gov

### Your GitHub Handle

bpatelctr

### Your Role and Team

Tester

### Product Manager (PM) name and email

Tanner Bird tanner.bird@va.gov

### Product Owner (PO) name and email

Eric Spahn eric.spahn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAiGP9B7z1iaWr/SN5B9hsAMhQ3C+EUxgEkp1U0gypRA82oLVHJINs5FPiNFggXPsRxumsl+rhqkKht3HZJqeWR9Et04OLIRHkmB/LUmGUficzLJmosgQXBaerwCXE6Q7CSxGPTTgriCLgfL/iErzNqBG/y/aRBRAUtFfgTyeLuLp54A2QUgqkMne32B/wQwUB1EEd4jbEQB3qgeCIS7Hvema6i4wot0wQht7LHTQ2mVh5h1CI0KUsoYyI5mmsFDNmSsyePLz5HKwotXHaAK4Pd4KTIO5FOtw1yiCZXLaDUZAC1uINypSAnj2KRODlXRVds2LFXHDZVcxor5CF3+8PrwEG04ajmg0Zh2r+55edxegG49W2pYfDytFnv8DBxT+pn/mIRPCAkV5OkTO/eUtXCuPeW1teO5Rb62obVofD8KBJ8CNZIL5v+8/CedUTZOfWDSoCSQR+BShrigorMhxamCBf4SPr7l4O/+Btnwg5g0bVSILtbPSlxOnqcPL0rT8= bpatelctr@TABLET-L1JVEK10

### E-QIP Transmittal Confirmation

![TransmittalNotice](https://github.com/department-of-veterans-affairs/va.gov-team/assets/87036646/95d53f3c-1592-4d98-8d33-8d809815cc72)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
New pubkey deployed. SOCKS access  completed.
