### ISSUE TITLE
Full transform on backend Part 5 (MISC)

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#81058]
This ticket is dependent on [#81062](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81062)

**_TL;DR_** 
We want to take a JSON string like [this](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/pre_submission_fsr/pre_transform.json) as input and reliably generate an output string like [this](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/pre_submission_fsr/post_transform.json). 
This process currently happens on the FE around [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/utils/transform.js).

This effort has already been started on branch `81058-backend-full-transform-pt4-misc`

FSR elements that still need to be produced (each of these could be a separate ticket):
- `personalIdentification`
- `personalData`
- `discretionaryIncome` (could possibly be handled by `IncomeCalculator`)
- `installmentContractsAndOtherDebts`
- `totalOfInstallmentContractsAndOtherDebts`
- `additionalData`
- `streamlined`
## Acceptance criteria
Implement functions to generate the sections of the FSR that don't correspond to the `income, assets, or expenses` sections of an FSR from an [untransformed fsr data packet](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/pre_submission_fsr/pre_transform.json).
 Depending on scope of work this work may be broken down into more modular tickets.

**Comment by HeatherRienks** [comment]
This ticket will be broken up into 3 PR's - ended up being a large effort

**Comment by HeatherRienks** [comment]
Per BE Sync, we will create 3 additional tix for this monster effort :)

**Comment by maxx1128** [comment]
UPDATE: All three tickets handling the specific transforms have been merged with specs. I have [one small pull request with some refactoring](https://github.com/department-of-veterans-affairs/vets-api/pull/17097) that could only be done once they were all merged. Once that's merged, this ticket can be closed.

**Comment by maxx1128** [comment]
UPDATE: All of the transform tickets have been closed and merged, including the pull request with the refactoring. This ticket is officially ready to be closed, and the next steps of additional specs and controller setup are ready to start.
