### ISSUE TITLE
[FSR] Update StreamlinedDepends Calculations for GMT by using new Expenses Endpoints

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#81065]
Description
GMT calculation should implement calculated monthly expenses endpoint from back end to perform streamlined waiver determination.

Acceptance criteria
[ ] calculateDiscretionaryIncome uses response from BE for streamlined waiver calculations

Testing

**Comment by HeatherRienks** [comment]
Closing - created in error
