### ISSUE TITLE
[QA] Facility-level Operating Status Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8106]
## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

Feature Brief: [GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-level-alerts/feature-brief.md) (Facility-level Alerts)
Feature Epic: #7178 (Facility-level Alerts)
Product/Feature Pre-Launch Checklist: \[provide link]
Product/Feature Design artifacts: \[provide link, if separate from Epic]

Specific front-end task: #7635

## Product-team SMEs

Product Management: Michelle Middaugh
Design/Research: Ryan Thurlwell / Arika Lewis
Content/IA: N/A
Front-end: Gibran Rodriguez
Back-end: Lance Sanchez
QA (shared-resource): Tze-chiu Lei

## Proposed user-scenarios and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs.  IMPORTANT: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

1. <scenario-1> - <test-account-1>
2. <scenario-2> - <test-account-2> ...

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
Tried to get started running tests but front-end changes are not yet deployed -- #7635's PR is still under review.

Will check back Monday morning.

**Comment by mmiddaugh** [comment]
@tlei123 can this be closed?
