### ISSUE TITLE
IPP Content - Create a IPP info pamphlet for Veterans

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#81060]
Update[ educational content](https://docs.google.com/document/d/11fsQ-X5QqWzvzf-IbzJlDIuuWCyiqtyvEQ5JnC5JwTg/edit) so that all information that is linked is explicitly written out. 

Notes:
Tri-fold or bi-fold; create content first, then when handed off to design see what is feasible
Pull in visuals as you see fit, Design will work on lay out at the hand off
Pull content directly from site, tweak as needed for grammar/flow but overall should read the same

ETC: Wednesday, May 1st

**Comment by SophiaPhilipMO** [comment]
See resources here from[ Login.gov](https://login.gov/help/verify-your-identity/how-to-add-images-of-your-state-issued-id/) and[ ID.me](https://www.id.me/business/identity-verification#:~:text=video%20conference%20session.-,In%2DPerson,secure%20credential%20for%20important%20services.)

**Comment by SophiaPhilipMO** [comment]
[2023-06 Identity Verification Flow.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1TQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6cf163ea844b42b92f93346da1e10a405e8515e/2023-06%20Identity%20Verification%20Flow.pdf)
[2024-03 Opt-In IPP - Identity Verification Flow.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a443953b984e1181ee29de68ed7395484a2ef90a/2024-03%20Opt-In%20IPP%20-%20Identity%20Verification%20Flow.pdf)
[Uploading... 2023-08 Login.gov Authentication Flows (2).pdf]

**Comment by SophiaPhilipMO** [comment]
[Uploading... 2023-08 Login.gov Authentication Flows (2).pdf]

**Comment by SophiaPhilipMO** [comment]
[2023-08 Login.gov Authentication Flows (2).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXlTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1531f23bbc4142e7e1b4280be12f8df56b699f35/2023-08%20Login.gov%20Authentication%20Flows%20%282%29.pdf)

**Comment by CarlDickerson** [comment]
I've finished first pass of Identity Verification Pamphlet. Keeping in mind that there will be limited physical real estate, I tried to pair down content as much as possible. @SophiaPhilipMO please review and provide feedback. https://docs.google.com/document/d/192kWVNKnRni0tAunEAEWA-VkH8xkVWIG_WrGGCTDeI8/edit

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson reviewed and dropped in comments. Definitely like your approach to brevity.

**Comment by CarlDickerson** [comment]
@SophiaPhilipMO I made updates to content of the pamphlet, but I also created a version 2 of the pamphlet that is a little more comprehensive, focused on signing into VA.gov (which I think is the more evergreen solve) and is verification-centric. It can be found here https://docs.google.com/document/d/1RpiIfSWzpqfkTi54M6U_POz30gQLUD23icBgr8f6SOQ/edit?usp=sharing

**Comment by SophiaPhilipMO** [comment]
[v1 - verification centric](https://docs.google.com/document/d/192kWVNKnRni0tAunEAEWA-VkH8xkVWIG_WrGGCTDeI8/edit)
[v2 - sign-in focus](https://docs.google.com/document/d/1RpiIfSWzpqfkTi54M6U_POz30gQLUD23icBgr8f6SOQ/edit)

@CarlDickerson awesome adaptation and the focus on sign-in makes sense from that comprehensive lens you mentioned. Let's move forward with building out a template using v2
