### ISSUE TITLE
Plan a KO meeting with Perigean for Pilot 1 Onsite

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#81064]
After the research plan has been finalized with the pilot site details, we need to our [ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/495) in the Research Repo so that we may schedule a KO meeting with Perigean 2 weeks before the pilot.

**Comment by SophiaPhilipMO** [comment]
@skirkman16 ticket updated and KO meeting requested

**Comment by SophiaPhilipMO** [comment]
Scheduled for 1:00pm ET 4/30
