### ISSUE TITLE
[Initiative] EAS / FHIR Implementation for VAOS-R

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8110]
Starting this epic so we can start creating our implementation tasks and issues for migrating to the latest EAS and FHIR resources. 

## For tracking purposes, EAS / Apoth. team tracking of milestones:
- [EAS Milestone 1](https://issues.mobilehealth.va.gov/browse/VAOSR-111) - Complete - View work here
- [EAS Milestone 2 ](https://issues.mobilehealth.va.gov/browse/VAOSR-313)- Milestone 2 won't be 100% complete until SM Web is using VAR resources as the backend service. The bulk of the work to get VAR resources ready for that is complete. However, there will be remaining testing and tweaking of VAR resources after the release of 4.20 to SQA in support of sunsetting SM Resources. On track to be completed by end of April. 
- [EAS Milestone 3 ](https://issues.mobilehealth.va.gov/browse/VAOSR-540)- A few stories in-progress, but not fully underway

**Comment by laurenernest** [comment]
No longer needed
