### ISSUE TITLE
Reports Powered by UA: Public Websites

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#81105]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

### Dashboards - GA
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
| VA.gov Footer Top Events | [Link to Footer Top Events Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/glQEUzUSQMOvqOX0MheFjg/a50123418w177519031p176188361/)| Google Analytics| Our team uses this report to analyze usage of links in the Global Federal Footer|
| VAgov Homepage Refresh |[Link to VAgov Homepage Refresh Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/iVIimjd8RFG4Galuw2U8YQ/a50123418w177519031p176188361/)| Google Analytics | Our team uses this report to analyze usage of the modernized Home page of VA.gov |
| Income Limits Dash | [Link to Income Limits Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/t0400uoaQJmKFu3gf8aByA/a50123418w177519031p176188361/)  | Google Analytics | Our team uses this report to monitor Income Limits usage |
| Campaign Landing Page / Pride & Discharge Upgrade | [Link to CLP Pride Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/AmL4kPvpSNWS8tw0ENefOA/a50123418w177519031p176188361/) | Google Analytics | Our team uses this to gauge the value of the Campaign Landing Pages  |
| Campaign Landing Page / Covid Vaccine | [Link to CLP Covid Vaccine Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/TVlyUd0lRvKf-zya9phx8w/a50123418w177519031p176188361/) | Google Analytics | Our team uses this to gauge the value of the Campaign Landing Pages  |
| Content Landing Page - Veteran Trust in VA | [Link to CLP Veteran Trust Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/Xu16NiSGSdypUoPSjUaQHw/a50123418w177519031p176188361/) | Google Analytics | Our team uses this to gauge the value of the Campaign Landing Pages  |
| Form Detail Dashboard | [Link Form Detail Report ](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/Pq1Oso_0SWWgHWBkcxwqKg/a50123418w177519031p176188361/)| Google Analytics  | Our team uses this report to gauge traffic and and forms usage in Find a Form (Find Forms) |
| Find Forms Dashboard 1.0 | [Link to Find Forms 1.0 Report](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/MHSfv0WxQySyKRB5IYyw1Q/a50123418w177519031p176188361/)  | Google Analytics | Our team uses this report to compare legacy app and new app, and is a different report than the one noted above for Find Forms |

#### Custom Reports - GA
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
| [VA.gov Footer Top Events 2023-11-08](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/savedreport/8e0b2owkTxiBKuK3NCltZg/a50123418w177519031p176188361/_r.dsa=1&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Navigation%20-%20Footer&_.advseg=&_.useg=&_.sectionId=) | Link to A.gov Footer Top Events 2023-11-08 Report | Google Analytics  | I'm not sure how this report is different than the dashboard for the footer noted in the section above. If they are dupes, this one can be deprecated. |

#### Reports - Looker Studio Flagship Mobile 
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
| Android and iOS features | [Link to Looker Studio](https://lookerstudio.google.com/u/0/reporting/e28cd59a-b2e5-4f29-8ae4-a4eea6d23f9c/page/p_7hxeqg1k9c) | Looker Studio| Our team uses this report to mobile app feature usage |

**Comment by ChristineYoungZA** [comment]
Hello @FranECross can you provide the links to the Forms Details and the Va.gov Footer Top Events 2023-11-08 reports?

**Comment by FranECross** [comment]
@ChristineYoungZA Apologies for missing those! Added. 🎉

**Comment by johnny-jesensky-adhoc** [comment]
This information has been documented in a separate file -- closing out this ticket.

FYI @ChristineYoungZA, @Blivaditis
