### ISSUE TITLE
[COGNITION]: VAOS - Tabs MUST have hover and focus states for navigation and usability

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#8111]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

I had trouble determining "where I was" when I first tried to navigate through the new tabbed interface for upcoming and previous appointments. After a few runs, I realized the tabs could receive keyboard focus, but were not showing the yellow focus halo, and didn't have a hover state for mouse users. I'm attaching a screenshot below that shows the first tab with keyboard focus, but no change in the visual display.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Tab with pseudo-state `:focus` shows the yellow focus halo
- [ ] Tab with pseudo-states `:hover, :active` shows a unique look like our call to action buttons

## WCAG or Vendor Guidance (optional)

* [ WCAG2.1 Understanding Success Criteria 2.4.7: Focus Visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)

## Screenshots or Trace Logs

![Screen Shot 2020-04-17 at 8 12 06 AM](https://user-images.githubusercontent.com/934879/79573573-7c706300-8084-11ea-8c8b-8272527218f1.png)

**Comment by jbalboni** [comment]
Whoever works on this should look at the tabs in claim status and see if carrying over some of the classnames gets the focus and hover states.
