### ISSUE TITLE
[COGNITION]: VAOS - Past appointments filter MUST have a submit button or clear instructions 

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#8112]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The Past appointments tab has a `<select>` menu where I can filter my previous appointments. Screen reader users could be surprised or confused when the list updates after they have selected an option from the menu. This interface could be improved by adding a "Submit" button or clear instructions that the `<select>` menu will drive the result set. Screenshot below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Submit button drives the interaction OR
- [ ] Clear instructions are added that explain the `<select>` menu filter
- [ ] No axe errors appear during future scans

## WCAG or Vendor Guidance (optional)

* [On Input: Understanding SC 3.2.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html)

## Screenshots or Trace Logs

![Screen Shot 2020-04-17 at 8 22 33 AM](https://user-images.githubusercontent.com/934879/79574318-95c5df00-8085-11ea-8e01-8517934baadc.png)

**Comment by jbalboni** [comment]
@1Copenut Do you know of any examples of what "clear instructions" would be for something like this?

**Comment by 1Copenut** [comment]
@jbalboni Great question. Clear instructions could be something like "Your list of past appointments will update when you select a choice from the dropdown menu." The content writers will have a better feel for what language to use, but essentially we want to tell folks that the `<select>` is the driver. ( https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G13 )

I think a longer explanation text could be a hint to the label text or a sub-header to the Past Appointments, and the `<select aria-describedby="UNIQUE_ID">` that points to the explainer text.

**Comment by rtwell** [comment]
yeah if we could drop a primary button to the right of the drop down, i think this would appease mr. @1Copenut — I'm not sure what that button should say…Search? Display? Show? if you need me to comp something up @jbalboni i'm happy to

**Comment by jbalboni** [comment]
![Screen Shot 2020-05-04 at 4 21 50 PM](https://user-images.githubusercontent.com/634932/81009939-81266c80-8e23-11ea-8783-efff73073b29.png)

**Comment by rtwell** [comment]
@peggygannon any thoughts? I personally prefer the latter:

**Show** Past 3 months —> **Update**

**Comment by jbalboni** [comment]
We'd have to expand on the label and button text for the aria-labels, to make those more clear to people who aren't seeing how it's laid out horizontally, I think. Something like "Show appointments scheduled in the selected date range" and "Update the list to show appointments within the selected date range."

**Comment by 1Copenut** [comment]
I agree with @jbalboni on the more in-depth label and button. I think with the strong label text, the button `aria-label` could be "Update the list" or "Update my appointment list". I'll defer to Peggy for final language.

**Comment by peggygannon** [comment]
Hello, @jbalboni @rtwell @1Copenut here is my recommendation. Please let me know if you have any questions: 

"Select a date range for your appointments" 

"Update my appointment list"

**Comment by jbalboni** [comment]
@rtwell @1Copenut How much of the above text do you want displayed in the button and label, vs the aria-label?

**Comment by 1Copenut** [comment]
@jbalboni I'd be good with "Select a date range" and "Update" for the visible text, with full text blocks in the `aria-label` attributes. You *may* have to add an SR-only span for the `<label>`, not sure if it supports `aria-label` or not.

**Comment by rtwell** [comment]
**Label**: "Select a date range"

**Button**: "Update"
