### ISSUE TITLE
Review and refine high priority tickets from usability study and then continue with review of medium and low priority tickets

### ISSUE THREAD

**Issue by Allexelaw** [department-of-veterans-affairs/va.gov-team#81121]
Ongoing work to refine design tickets for our temp PT backfill designers

**Comment by Allexelaw** [comment]
Review high priority tickets to further refine/add to as needed to facilitate the pass off to design.

**Comment by Allexelaw** [comment]
Review for refinement ticket # Introduction Page, Dependents , Income and assets

**Comment by Allexelaw** [comment]
Reviewed findings and questions on unreimbursed expenses (H)#79214 ticket with Matt Reilly. Scheduled a meeting to discuss with Kate Murphy today.

**Comment by Allexelaw** [comment]
Reviewed #79214 Unreimbursed expenses w/ Kate M. who suggested design make revisions to the form and run them by CAIA before sharing w/VBA SMEs to discuss.  Reviewed and refined ticket # 79671 - provide context on assets; ticket # 79668 - household info improvements (multiple marriages); ticket # 79667 -  medical facility questions; ticket # 79665 - Military history date improvements

**Comment by Allexelaw** [comment]
Review and refinement of #79663 (past VA claims), #79668 (marriage fields context) completed

**Comment by buddhima-coforma** [comment]
There are some new tickets in the Usability Findings epic with no priority assigned. Can those be looked at and decided on too? @Allexelaw

**Comment by buddhima-coforma** [comment]
@Allexelaw @djones2113 pulled some stats on [drop off rates at each step](https://docs.google.com/spreadsheets/d/1Ccw5b_-E0AuJHgBKlIczW36AWx-RaSM-moVtaUmj26Y/edit#gid=1221853331)

- drop off numbers are less useful when they're related to a conditional step (can't tell if they answered in a way they skip a page or dropped off)
- kept %s that are double digit, non-negative (if you're wondering why only some rows have %s)

**Comment by aplatt-coforma** [comment]
For now we're going to close this ticket. If Allexe needs to provide additional support in inflight tickets for design, we'll create a new ticket.

**Comment by Allexelaw** [comment]
@aplatt-coforma  This ticket can be closed
