### ISSUE TITLE
Reporting for 527

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81135]
# Overview 
Emily has requested some reporting on 527

# Summary

> I'm preparing some statistics for a VBA-wide report and am wondering if we can grab any of the following straight from our InProgressClaims vs. SavedClaims in the DB, knowing we're still working out the kinks of our analytics tools:

- [x] - how many individuals have initiated a 21P-527EZ application using VA.gov since relaunch?
- [x] - how many individuals have submitted a 21P-527EZ application using VA.gov since relaunch?
- [x] - Can we calculate any amount of time, sessions the applicant spends completing the 21P-527EZ application using VA.gov (Number of sessions or number of days?) totally fine if not on this one

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81135?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by wayne-weibel** [comment]
SavedClaim.find_by_sql("SELECT * FROM public.saved_claims WHERE created_at > '2024-01-31 16:00:00' AND form_id = '21P-527EZ'").length
submitted - 2302 (saved claim created at > 2024-01-31, anonymous and logged in)

InProgressForm.find_by_sql("SELECT * FROM public.in_progress_forms WHERE created_at > '2024-01-31 16:00:00' AND form_id = '21P-527EZ'").length
initialized - 3026 (logged in, not submitted)

total - 5508

anonymous, started, not submitted ???

**Comment by wayne-weibel** [comment]
rough guess for durtaion, can only be based on logged in submissions - 13:08:01

<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEttQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba86b2147c9dd9039ce796d40ad3b2c86268071f/image.png" alt="image.png" />

**Comment by wayne-weibel** [comment]
```ruby
claims = SavedClaim.find_by_sql("SELECT * FROM public.saved_claims WHERE form_id = '21P-527EZ' AND created_at > '2024-01-31 16:00:00' AND itf_datetime IS NOT NULL")
duration = claims.map { |r| r.created_at - r.itf_datetime }
average = duration.sum/claims.length
Time.at(average).utc.strftime("%H:%M:%S")
Time.at(duration.max).utc.strftime("%H:%M:%S")
```

**Comment by mjknight50** [comment]
Thank you!

**Comment by wayne-weibel** [comment]
<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06c6720e4ac7b6395ad7e4701548a98aa1ac8a77/image.png" alt="image.png" />

**Comment by wayne-weibel** [comment]
update on the times

<img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2aa919fb03c6c8b11fa1887e60cf0588a77e933a/image.png" alt="image.png" />
