### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by hoorayarjun** [department-of-veterans-affairs/va.gov-team#81137]
### Name

Arjun Ganesh

### Email

arjun.ganesh@va.gov

### Role

Data Analyst

### Team

VES Product Analytics Team

### Product Manager (PM) name

Justin Lai

### Additional Notes

Subcontracting team for VES/CXPA requesting Figma access for current statement of work within the VES org. 

Please and thanks!

**Comment by naomimarcussen** [comment]
An invite has been sent to arjun.ganesh@va.gov
