### ISSUE TITLE
Content work to support Static Landing Page for 686 Changes (eBenefits)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8114]
This ticket is to capture the request and effort for the PW team, to provide content support for the static landing page for 686 changes (by eBenefits)

## Goal
- Content support for static public website pages
- Content support for authenticated application or tools
- For specific copy editing tasks

- Note: Because this work requires engineering effort, we should ensure the appropriate amount of coordination is undertaken with the engineer(s) who pick up the corresponding engineering ticket #8115 
---

### Background
(from Jason) *Provide a background of your tool/functionality:*
"Form 21-686c/674 is the form that allows a Veteran to add, remove or change their dependents and how they would be attached to an award or benefit.  We have included the View portion of this application to have a significantly different call out for the Veteran in order to make a more present and informed decision on what steps to take next.

The current landing page redirects Veterans to the legacy eBenefits site and does not reference the View portion of what we are providing, but there is a great deal of important information that has been preserved and reworked into the proposed landing page.

We have almost completed the rebuilding of the application for the Form 21-686c/674 and would like to modify the landing page so that we can better represent the functionality a Veteran will experience.  Most of this is some rearrangement and addition of words but closer to launch we will request the addition of some HTML around the first and second login widget, that we will provide below, that will allow Flipper to adjust traffic redirects for a graduated, controlled rollout.

- We would like this link: [/disability/add-remove-dependent](https://www.va.gov/disability/add-remove-dependent/) changed to reflect the content on this mockup and made to this url: [/view-change-dependents/](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/).  Please note that the `disability` hub has been removed; this will simply be off the root.
  - This is supported by IA in [this recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md)
  - The tool page is being updated in staging to reflect this: `/disability-benefits/new-686/` - to be updated to: `/view-change-dependents/add-remove-form-686c/` per [#8108](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8018)
      
- [ ] **Content support for a static public website page**
   * Is this to update existing static content? 
      * Yes
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * Yes
   * Provide a list of URL/s that need to be reviewed or updated. 
      - We would like this link: [/disability/add-remove-dependent](https://www.va.gov/disability/add-remove-dependent/) changed to reflect the content on this mockup and made to this url: [/view-change-dependents/](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/).  Please note that the `disability` hub has been removed; this will simply be off the root.

**Comment by peggygannon** [comment]
Hi, @stephorkandatx I'm dropping in the mockup that shows the updated static page. @lunascoop and I have been discussing this. 

https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/

cc @DanielleThierryUSDSVA

**Comment by mnorthuis** [comment]
Dropping IA information for reference if needed:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md

**Comment by lunascoop** [comment]
Here's the content audit and PDF with Mikki's and Danielle's feedback.
[Static Landing Page 686 Content Audit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4540333/Static.Landing.Page.686.Content.Audit.docx)

[view change dependents landing page.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4540331/view.change.dependents.landing.page.pdf)

**Comment by lunascoop** [comment]
Here's a draft for review.
[View or change dependents.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4554033/View.or.change.dependents.docx)

**Comment by stephorkandatx** [comment]
@lunascoop have you received feedback from the draft that you shared?

Unrelated to the draft you shared-
From the engineering ticket #8115 it appears that the widget work has been merged. The next item appears that we will edit the Drupal page (/disability/add-remove-dependent/, please confirm that is correct) to set up a new React widget with type 686UnauthContentBlock.
I believe the description of this ticket would incorporate this change, to match the mock-ups, please review and let me know if we need to generate a new ticket to address this specifically. Thanks so much!

**Comment by lunascoop** [comment]
@stephorkandatx I am still awaiting feedback. That sounds correct. I think a separate ticket to update the Drupal change would probably be best.

**Comment by stephorkandatx** [comment]
@lunascoop setting the new ticket up now

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Just confirming here, per our call with @peggygannon, that I'll do the review of this page instead of it going right to platforms review. Thanks to all for being flexible as we figure out how to best work out the review process!

I do have a question for Peggy, so I'm going to sync with her this morning on that real quick to make sure we're aligned and will post a version with my feedback today. Thanks!

FYSA @stephorkandatx

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA Yes, that sounds right. I included a draft version of my recommendations in the [comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8114#issuecomment-621409325).

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Hope you're feeling better! Here are my edits to the page. Document 1 is notes on your draft version. Document 2 is tracked changes based on the currently live page. I created document 2 because I wasn't able to edit the actual copy in the draft version since it was mainly screenshots and wanted to make sure that edits are clear. Also, I keep getting a "file to big to upload" message on the doc 1 word doc, so I've turned it into a pdf for uploading. Just let me know if you have questions or want to talk through any of the edits. Thanks!

@peggygannon I know we already connected on a couple of things in my edits, and I have one specific question for you in the intro of document 2. Beyond that, just let us know how you'd like to do your platforms review. Feel free to look over my edits and add any additional thoughts now, or if you'd rather wait until staging review, that's totally fine too. Thanks!

[View.or.change.dependents_DT review notes 1](https://app.zenhub.com/files/133843125/11b2a805-99ce-4c86-b9c6-6ec841e10d17/download)

[View or change dependents_DT review notes 2](https://app.zenhub.com/files/133843125/3ef50daa-3610-4479-841d-74568a645331/download)

FYSA @stephorkandatx

**Comment by peggygannon** [comment]
@DanielleThierryUSDSVA @lunascoop I've uploaded the doc with my content feedback (v. minor). Please let me know if you have any questions. thx. 

[https://app.zenhub.com/files/133843125/50b93ee9-eb4f-420d-b65a-95d72ababa49/download](https://app.zenhub.com/files/133843125/50b93ee9-eb4f-420d-b65a-95d72ababa49/download)

**Comment by lunascoop** [comment]
@jason-gcio here is the updated content for the static landing page. Perhaps we should get a mtg together to discuss everything. Let me know your availability for tomorrow or early next week (minus Memorial day).
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8114#issuecomment-630963065

**Comment by jason-gcio** [comment]
cc: @cohnjesse and @sporeboy

**Comment by lunascoop** [comment]
This content was reviewed w/team. Working on drupal draft w/copy. Will work circle back w/team to review draft w/new copy later this week.

**Comment by jason-gcio** [comment]
Awesome, thank you!

**Comment by lunascoop** [comment]
Preview/Draft version available for view on VA side (Citrix): http://preview-prod.vfs.va.gov/preview?nodeId=869

Will set up meeting to review w/team and ask further questions.

**Comment by lunascoop** [comment]
Hi @jason-gcio I've created a draft version of the static landing page. Let me know when you want to review it. I am available this afternoon and Monday (except for between 2'3pm)

**Comment by RLHecht** [comment]
@lunascoop This page has been copyedited in the draft form it's in now though I know you have more updates to do.

**Comment by lunascoop** [comment]
Met last week w/team to review page. Made "eBenefits" reference change. Closing this ticket and will create another ticket for the final drupal work (adding react widget and moving draft page outside disability hub).
