### ISSUE TITLE
Reports Powered by UA: Debt Resolution - Team

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#81147]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

---

### Instructions:
**Step 1:** Please provide the following information on each actively used report your team uses that contains UA data at the bottom of this ticket. _(Or, if it's easier, attach a spreadsheet.)_
- Report Name
- URL Link
- Reporting Platform (Domo, GA, etc.)
- Description of Report (i.e. How it's used)
  
**Step 2:** Include your team name within the title of this form.

**Step 3:** Submit this form.

_Our team will follow up with you for any next steps._

> [!NOTE]
> - We are defining _"actively used reports"_ as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
> - Teams do NOT have to include the standard [Search](https://va-gov.domo.com/page/1964748112), [Content](https://va-gov.domo.com/page/426422632), or [Forms](https://va-gov.domo.com/page/447193050) KPI dashboards --  we are already working to update those.

> ### Example:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|VA Homepage Report|https://va-gov.domo.com/page/|Domo| Our team uses this report to analyze trends for our KPIs.|
---

## Reporting Information:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|Form 5655 - Financial Status Report|https://va-gov.domo.com/page/447193050| Domo| Our team uses this report to analyze trends and strategize updates to the form to enhance the user experience.|
|KPIs Debt Managment |https://va-gov.domo.com/page/447193050| Domo| Our team uses this report to analyze trends with page views, bounce rates, and authenticated users viewing debt letters.|
|Debt Managment Page Views|https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=~2Fmanage-va-debt~2F&explorer-table.plotKeys=%5B%5D| Google Analytics| Our team uses this report to analyze trends and strategize updates to the form to enhance the user experience.|
| FSR Page Views Report 1 |https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240409&explorer-table.filter=financial-status-report&explorer-table.plotKeys=%5B%5D/| Google Analytics| Our team uses this report to analyze user interactions with the form and learn about our engagement`|
| FSR Page Views Report 2 | https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240409&explorer-table.filter=5655&explorer-table.plotKeys=%5B%5D/ | Google Analytics | Our team uses this report to measure similar engagement.|
|Combined Debt Portal GA PageViews | https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20240317&_u.date01=20240409&explorer-table.filter=manage-va-debt&explorer-table.plotKeys=%5B%5D|Google Analytics| Our team uses this report to measure user interaction with the Combined Debt Portal |

**Comment by OptionSelect** [comment]
Please let us know if there is anything else you might need or we missed! I'm not quite sure if we supplied the correct stuff so happy to amend this with more info if needed!

**Comment by johnny-jesensky-adhoc** [comment]
This information has been documented in a separate file -- closing out this ticket.

FYI @ChristineYoungZA, @Blivaditis
