### ISSUE TITLE
Reports Powered by UA: [Benefits Non-Disability and Dependents]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81142]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

---

### Instructions:
**Step 1:** Please provide the following information on each actively used report your team uses that contains UA data at the bottom of this ticket. _(Or, if it's easier, attach a spreadsheet.)_
- Report Name
- URL Link
- Reporting Platform (Domo, GA, etc.)
- Description of Report (i.e. How it's used)
  
**Step 2:** Include your team name within the title of this form.

**Step 3:** Submit this form.

_Our team will follow up with you for any next steps._

> [!NOTE]
> - We are defining _"actively used reports"_ as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
> - Teams do NOT have to include the standard [Search](https://va-gov.domo.com/page/1964748112), [Content](https://va-gov.domo.com/page/426422632), or [Forms](https://va-gov.domo.com/page/447193050) KPI dashboards --  we are already working to update those.

> ### Example:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|VA Homepage Report|https://va-gov.domo.com/page/|Domo| Our team uses this report to analyze trends for our KPIs.|
---

## Reporting Information:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|Burial - Unauth vs Auth Form Start | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/savedreport/fvZbma6tQKaBd2pAS3fo-g/a50123418w177519031p176188361/_u.date00=20240129&_u.date01=20240204&_.useg=builtin1,useri0ZvPaPpQKyUHGrYCFPigw,userXZpoGov_R4K1a1Biwj2YNg&_.advseg=&_.sectionId=&_r.dsa=1&_r.drilldown=analytics.pagePath:www.va.gov~2Fburials-and-memorials~2Fapplication~2F530~2Fclaimant-information~2F&explorer-table.plotKeys=%5B%5D/ | GA | Tracks auth vs unauth users who start the Burial 530EZ form |
| Burial - Form Submissions | https://analytics.google.com/analytics/web/#/savedreport/t-G5T3OiQYaRJn6HrNvPrQ/a50123418w177519031p184624291/_u.dateOption=last30days&_.sectionId=&_.useg=builtin1,usersYzZ0EUDT4uJLecPmCwn3Q,userBgZiUrK9Sieg7jBAnx44OQ&_.advseg=/ | GA | Tracks submission volume and how many are auth vs unauth |
| 686/674 - Submissions | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/savedreport/nYEuV3BCQpeqgLcNxVSFwQ/a50123418w177519031p176188361/_u.date00=20231101&_u.date01=20240229&_r.dsa=1&_r.drilldown=analytics.eventCategory:Transactions,analytics.eventAction:Forms%20-%20Disability,analytics.eventLabel:disability-21-686c--submission-successful&explorer-table.plotKeys=%5B%5D&explorer-graphOptions.selected=analytics.nthMonth&_.advseg=&_.useg=&_.sectionId=/ | GA | Tracks the number of 686c form submissions |
| 686/674 - Device | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/savedreport/NpjoT4ppSKWO69qsUmwbrA/a50123418w177519031p176188361/_u.date00=20240129&_u.date01=20240204&_u.dateOption=last30days&_.advseg=&_.useg=&_.sectionId=&_r.dsa=1&explorer-graphOptions.selected=analytics.nthWeek&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2Fview-change-dependents~2Fview~2F%22,0%5D%5D/ | GA | Tracks the device used to view the view/change dependent page |
| VR&E Previous Page | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/savedreport/MFcXYnh8TdyaQppqkj0URA/a50123418w177519031p176188361/_u.date00=20240129&_u.date01=20240204&_u.dateOption=last30days&_.advseg=&_.useg=&_.sectionId=&_r.dsa=1&_r.drilldown=analytics.pagePath:www.va.gov~2Fcareers-employment~2Fvocational-rehabilitation~2Fapply-vre-form-28-1900~2Fstart~2F&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&explorer-table.rowStart=0&explorer-table.rowCount=25/ | GA | Tracks the page users visited before the VR&E form landing page |
| 686c GA Dashboard | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/nR0nR4HKQzitQ_kd0sDv9w/a50123418w177519031p176188361/ | GA | 686c dashboard |
| VR&E GA Dashboard | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/4PGH_QHATcGBIpxEJA5VwA/a50123418w177519031p176188361/ | GA | VR&E dashboard |
| 686c GA Dashboard | https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/nR0nR4HKQzitQ_kd0sDv9w/a50123418w177519031p176188361/ | GA | 686c dashboard |

**Comment by johnny-jesensky-adhoc** [comment]
@steele-lm -- are you ok if I keep this open for our own team's tracking? We can remove your team's label if it helps clean up your board. Thanks you for submitting this.

**Comment by steele-lm** [comment]
@johnny-jesensky-adhoc Apologies! I didn't realize closing it on our board would also close it on yours.

**Comment by johnny-jesensky-adhoc** [comment]
This information has been documented in a separate file -- closing out this ticket.

FYI @ChristineYoungZA, @Blivaditis
