### ISSUE TITLE
Engineering work to support Static Landing Page for 686 Changes (from eBenefits)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8115]
This ticket is to capture the request and effort for the PW team, to provide content support for the static landing page for 686 changes (by eBenefits)

## Goal
- Engineering support for implementation of REACT sign in widgets

---

### Background
(from Jason) *Provide a background of your tool/functionality:*
Form 21-686c/674 is the form that allows a Veteran to add, remove or change their dependents and how they would be attached to an award or benefit.  We have included the View portion of this application to have a significantly different call out for the Veteran in order to make a more present and informed decision on what steps to take next.

The current landing page redirects Veterans to the legacy eBenefits site and does not reference the View portion of what we are providing, but there is a great deal of important information that has been preserved and reworked into the proposed landing page.

We have almost completed the rebuilding of the application for the Form 21-686c/674 and would like to modify the landing page so that we can better represent the functionality a Veteran will experience.  **Most of this is some rearrangement and addition of words but closer to launch we will request the addition of some HTML around the first and second login widget, that we will provide below, that will allow Flipper to adjust traffic redirects for a graduated, controlled rollout.**

- HTML to replace first login widget/section:
```diff
<div data-widget-type="view-dependents-CTA" id="view-dependents-CTA"></div>
```
- HTML to replace second CTA widget/section:
```diff
<div data-widget-type="686UnauthContentBlock" id="686ContentBlock"></div>
```
[Image: Code to replace second widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/images/VA_View_Dependents_Screens_W3_html.jpg)
   
- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * If needed

**Comment by stephorkandatx** [comment]
Will need to know the name of the widget type, to hand off to content. 

Content ticket at #8114 .

**Comment by ncksllvn** [comment]
@cohnjesse Did you mention your team is already working on this?

**Comment by ncksllvn** [comment]
The React portion of this is being worked on by eBenefits here - https://github.com/department-of-veterans-affairs/vets-website/pull/12437.

I'm guessing that the work on our end will be to edit the Drupal page (`/disability/add-remove-dependent/`, I think) to set up a new React widget with type [`686UnauthContentBlock`](/disability/add-remove-dependent/).

**Comment by stephorkandatx** [comment]
@jason-gcio can you confirm that your team created the widget for this? It appears they took care of the work. In which case, the remaining item would be to set up the widget on the Drupal page

**Comment by cohnjesse** [comment]
@stephorkandatx Yes, both of the branches of code for the widgets have been merged into master.

**Comment by stephorkandatx** [comment]
I am closing this ticket out and will track the remaining content work in its dedicated ticket
