### ISSUE TITLE
Design Intent - IA Feedback - Veteran Facing Forms & Authenticated Experience - Form Status on My VA & Updated Confirmation Page

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#81155]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thank you for working on this very complex project and bringing it through the collab cycle! 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Should: Move application status section up to be adjacent to claims status tool** - I hypothesize that having two request-status tools on this page will be confusing for users. If both tools will be there, though, they should be close to each other. 
- [ ] **Consider: doing research on mental models and language used for claims vs requests vs applications.** If the team ends up doing research on this feature I would be curious to hear about what Veterans' mental model is for claims vs. applications vs. other types of requests. Is it all just "I submitted a form and want to know what happens next?", or are there more discrete categories  in their minds that align with how things are done at the VA? Blue-sky I would hope that the Claims Status Tool eventually becomes a hub for understanding the status of all inbound requests so there's a one-stop shop for this info.
- [ ] **Consider: testing the status labels** There's a lot of good room to make sure that the status labels match Veterans' expectations and understanding. This could be another good thing to address in user research. I'm thinking especially of "pending", which could mean a number of things to different people.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [ ] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by jeana-adhoc** [comment]
These things are being explored in our upcoming research and have been accounted for as they can be in our designs. 

- [Figma File](https://www.figma.com/design/XAtdtChFlfwsHRvc7i6Dmd/WIP---Status-Project?node-id=0-1&t=Rst9If99rUQH9mlY-11)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Form%20Status/Research/conversation-guide.md)
