### ISSUE TITLE
21P-0969: Research Setup of New Application in vets-website

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#81161]
The purpose of this spike is Engineering team research on the approach for setting up new applications in vets-website for the new form 21P-O969, Income and Asset form.

One consideration is Applications that are isolated in the vets-website repository can take advantage of a faster continuous integration workflow in GitHub Actions. This faster workflow builds only the app(s) that the changed files in a branch belong to, in addition to only running their unit tests.

Related platform team documentation:
https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-applications-and-features
https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds

Tasks
- Perform documentation/code review
- Consider using Typescript for entire form
- Discuss with applicable SMEs
- Document findings and proposed approach

PDF Form:
[VBA-21P-0969-ARE.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6030a6fd5ccf505a520debe5d3b2c9c54191c303/VBA-21P-0969-ARE.pdf)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81161?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by matt4su** [comment]
Hey Todd, in researching the 0969 we saw a couple of patterns that might be applicable.
1. Multi page list loop- for repeated question loops: https://www.figma.com/file/OxzngjwHg4n0oNSGHkwJ5Z/WIP---Pattern---Multi-page-List-and-Loop?type=design&node-id=1-128050&mode=design&t=cbZ4jBncMsH4Eh1T-0
2. Sub task pattern - potentially for upfront "wizard type" questions to create the most efficient path through the form for Veterans based on their responses. 
https://design.va.gov/patterns/help-users-to/complete-a-sub-task

**Comment by ToddWebDev** [comment]
Thank you @matt4su. Those patterns should certainly be considered during the design phase.

**Comment by ToddWebDev** [comment]
Here is the associated documentation for technical implementation with vets-website: https://docs.google.com/document/d/1tyO3sP5FJSh6A_BUp_BzSkzhEHdcITeJWZuiIyzmx6I/edit?usp=sharing
