### ISSUE TITLE
SOCKS access for Tim Cosgrove

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#81165]
### Your Name

Tim Cosgrove

### Your Email

tcosgrove@metrostar.com

### Your GitHub Handle

timcosgrove

### Your Role and Team

Tech Lead on CMS Team

### Product Manager (PM) name and email

Grace Kretschmer, mkretschmer@metrostar.com 

### Product Owner (PO) name and email

Erika Washburn, erika.washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOHsB5XC1wwAsg3uYQYD7/pYdSvYIgj3Ya7fzeqCc5KM tcosgrove@metrostar.com

### E-QIP Transmittal Confirmation

<img width="616" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/203623/6d850806-3e4a-427c-9c96-574f79ad26e3">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by timcosgrove** [comment]
I previously had SOCKS access from my old work email (tim.cosgrove@agile6.com). This is a new email address and also a new key. 

The old public key for tim.cosgrove@agile6.com should be removed.

**Comment by timcosgrove** [comment]
Key was updated both here and in the associated PR in the devops repo. I accidentally deleted the keys and then recreated them.

**Comment by ph-One** [comment]
SOCKS access completed. New key has been rolled out. Old key has been cleaned up.
