### ISSUE TITLE
Offboarding of Louis Carlozo

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#8118]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Louis Carlozo
- Please provide the name of their team, their role on that team, and the name of the company they work for.
   > VSA Managing Editor
- Please provide any type of access they may have. 
  > ex: DSVA Slack, GitHub (loucarlozo63)
  
 
## AC
 - [x] Remove global/config.yml
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] SOCKS Access removed (if applicable) 
 - [x] AWS Access removed  (if applicable) 
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Org
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights

**Comment by jbritt1** [comment]
SOCKS / AWS access searched for this user, saw no entries so these are non-applicable. Checked the boxes to show this has been checked from the Ops team side.

**Comment by KevinMHoffmanUSDS** [comment]
@boris-ning-usds How do we remove someone in the new VA Github managed word? I can remove him from groups.

**Comment by joanneesteban** [comment]
Confirmed that he didn't have Google Analytics or Domo access.

**Comment by ricetj** [comment]
User Removed from VA GH Org
