### ISSUE TITLE
Drupal backup pipeline improvements

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#812]
The backup pipelines that exited in the old system were moved into VSP as they existed in the old system more or less. From our notes doc, we need to improve this in a couple of ways:

- [ ] the backup of db and filesystem and then sanitization are all 3 separate pipelines. these could likely be combined, but at the very least should be chained so they don't have to be done separately
- [ ] the deployments for everything else on the platform support a simple action like an RDS or EBS snapshot, but not more complex workflows like this before a deploy. we should extend the deployment configurations to support this model a bit better and automatically kick off these pipelines before a deploy

**Comment by b00klegger** [comment]
@wyattwalter 
The second item "... simple task kick off before deploy support" is that closely aligned with #811 ?

**Comment by wyattwalter** [comment]
It definitely could happen in a similar way. I was originally thinking the backup would be a separate Jenkins pipeline to make a "x job failed" message a bit more clear, but that's probably not necessary.
