### ISSUE TITLE
Error below Search button after signing into Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81204]
## Expected vs. Actual
**Expected**: After signing into the Widget in Find a Rep, the only thing that should update is the Widget state.

**Actual**: After signing into the Widget in Find a Rep, the Widget state updates AND an error appears below the Search button.  

This is happening across all Widget states and test users, on Chrome and Safari browsers for both desktop and mobile.

The post-login URL is https://staging.va.gov/get-help-from-accredited-representative/find-rep/?postLogin=true&page=1&perPage=10&name and I suspect this is behind the error we're seeing.

## Steps to Reproduce
1. Visit Find a Rep in Staging: https://staging.va.gov/get-help-from-accredited-representative/find-rep
2. Login with any [test user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv)
3. After a successful login, scroll down to the bottom of the page -- there is an error below the Search button

## Examples
<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFY3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c64718286df70fdae6e74da95147f5e036b5d72a/image.png" alt="image.png" />

**Comment by cosu419** [comment]
Merged to staging, giving time for team review

**Comment by oddball-lindsay** [comment]
Tested all states except Individual -- no error appearing, I think we're good here :)
