### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by UXCamG** [department-of-veterans-affairs/va.gov-team#81242]
### Request type

- [X] #81263
- [ ] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

2

### Subject matter expert

Camille 

### Approvals

Anita Middleton 

### Embedded media

- [x] Screenshot(s)
- [ ] Diagram(s)
- [x] Video(s)

### Audience

- [ ] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [X] Other

**Comment by jknipes** [comment]
@UXCamG thank you for contacting us regarding a new page for the [Platform Website](https://depo-platform-documentation.scrollhelp.site/). A team member will reach out to you to coordinate the creation of this page.

**Comment by UXCamG** [comment]
@jknipes Thanks for the update. I will look out for the team's response.

**Comment by jknipes** [comment]
@UXCamG To confirm, is this in regard to [this draft](https://vfs.atlassian.net/wiki/x/BwABug)?

**Comment by UXCamG** [comment]
@jknipes Yes, and there is a [sub page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3119841468/Getting+Help+from+the+Veteran+Support+Team) here

**Comment by UXCamG** [comment]
@jknipes  We would like for it to live under the analytics and insights section. 

[Platform URL](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/platform-data-sources)

**Comment by jknipes** [comment]
@UXCamG thank you, the page has been published on Platform Website [HERE](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-help-from-the-veteran-support-team). We are closing this ticket and moving to _Done_
