### ISSUE TITLE
[SPIKE] Research Tugboat On-Premises Implementation

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#81268]
## Description
There is an existing on-premises installation of Tugboat maintained by the VFS-CMS Team. There are a few ways to expand the use of Tugboat for other application previews:
- Assist with the scale-out of the existing Tugboat infrastructure.
- Create a new installation of Tugboat and migrate previous installation to it

## Acceptance Criteria
- [ ] Input from Tugboat engineers has been requested, received and considered
- [ ] Decision has been made how to host additional application previews. Greenfield or existing improvements.
- [ ] Follow-on implementation issues have been created.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
Ticket was part of the Tugboat epic. No longer need. Closing out the ticket. cc: @JRRoof @Bren22va @simiadebowale
