### ISSUE TITLE
Update content and layout for COVID-19 appointment request detail page

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#81272]
## Description
This ticket was created from https://github.com/department-of-veterans-affairs/va.gov-team/issues/79364 to make the PR review manageable.

Design Team: _"Covid appts are now using “in person” appts details pages, just will show “COVID vaccine” as type of care."_

**NOTE:** This feature is implemented in #80686

## Acceptance Criteria
- [ ] Given the user is on the Start scheduling workflow for COVID-19
       When the user clicks on `Submit` to schedule an COVID-19 appointment, Then the user will see the updated confirmation request details page, And page design matches the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A195846&mode=design&t=7xAm3Ts5T67F30L1-1)

- [ ] Given the user is on the Start scheduling workflow for COVID-19 
       When the user clicks on `Submit` to schedule an COVID-19 appointment and cancels the appointment, Then the user will see the updated confirmation cancelation details page, And page design matches the design spec

Page design must match the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A195846&mode=design&t=7xAm3Ts5T67F30L1-1)

**Comment by Cieramaddox** [comment]
@ldelacosta The name of this ticket is a COVID appt request detail page, but this is just a details page, no?

**Comment by ldelacosta** [comment]
Yes, just details page @Cieramaddox

**Comment by ldelacosta** [comment]
Closing out the ticket. We will validate the end to end flow when the following tickets are done: 
- #80690
- #79086
- #79364
- #81271
- #72652
- #72653


cc: @outerpress @melissa-lefevre @Cieramaddox
