### ISSUE TITLE
Update content and layout for VA appointment request detail page

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#81271]
## Description
This ticket was created from https://github.com/department-of-veterans-affairs/va.gov-team/issues/79364 to make the PR review manageable.

## Acceptance Criteria
Background: the va_online_scheduling_appointment_details_redesign toggle is on

- [x] Given the user is on the Start scheduling workflow, When the user clicks on Submit to request an appointment at the VA,Then the user will see the updated confirmation request details page
- [ ] Given the user is on the Start scheduling workflow, When the user clicks on Submit to request an appointment at the VA then cancels the request, Then the user will see the updated confirmation cancelation request details page

_**Page design must match the [design spec](https://www.figma.com/file/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?type=design&node-id=2011%3A213525&mode=design&t=7xAm3Ts5T67F30L1-1)**_

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta the AC aren't checked off, can you confirm this is ready?

**Comment by ldelacosta** [comment]
Validated the changes in staging: 

<img width="713" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0f4787476062637db4cf2af54662d5e29a5853c/Screenshot%202024-05-31%20at%2012.15.56%E2%80%AFPM.png" alt="Screenshot 2024-05-31 at 12.15.56 PM.png" />

Second AC is not correct. [Bug ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84347) is created to address the issue. 
<img width="814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHNxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ed00dab8638d881afe5e90e3706fc3851fd2aee/Screenshot%202024-05-31%20at%2012.17.07%E2%80%AFPM.png" alt="Screenshot 2024-05-31 at 12.17.07 PM.png" />
