### ISSUE TITLE
[FwdProxy] AL2 Deployment Automation in Production

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#81281]
## Description
Enable live traffic.  

## Resources 
Terraform needs created to replicate the behavior in Jenkins

## Acceptance Criteria
- [ ]  We have deployment parity with what we have in AL1

**Comment by ph-One** [comment]
We have identified some changes that need to be made to the lower environments. This work may no longer be appropriate for the Sprint.

**Comment by ph-One** [comment]
- @barbarello is working on the communication verbage for release to production
- @stoiven is working through any deltas detected between the old and new config files

**Comment by ph-One** [comment]
We are still working through issues in lower environments. This should not be a part of any Sprint until lowers have been deployed.

**Comment by ph-One** [comment]
This is being moved out in order to stabilize and monitor lower environments for a bit longer.

**Comment by ph-One** [comment]
Pushing this out two Sprints. We have uncovered a use case that was not previously accounted for, and additional work will have to be done before we can consider pushing the forward proxy beyond the lower environments.

**Comment by ph-One** [comment]
Pushing this out another two sprints. It doesn't make sense to have this in the same sprint as Sandbox. Once Sandbox is completed, this ticket can be pulled in

**Comment by ph-One** [comment]
We will be cutting live traffic over tonight at 11pm ET

**Comment by kflow85** [comment]
PROD was deployed on 12/17/24. Closing Epic.
