### ISSUE TITLE
Improve unit tests

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81292]
# Overview

For the initial relaunch of Pensions, we prioritized a high overall code coverage of the frontend unit tests over granular tests due to the time constraints. For example, see the [contact information unit tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/pensions/tests/unit/chapters/01-applicant-information/contactInformation.unit.spec.jsx), which just checks the number of fields rendered and the number of errors when navigating to the next page with a blank form. Compare this to the [dependent child information unit tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/pensions/tests/unit/chapters/04-household-information/dependentChildInformation.unit.spec.jsx), which validates that the correct number of each type of field is rendered, the correct number of errors are displayed on blank submit, the form submits successfully with valid data, the custom title behaves as expected, and that each of the data states which alter which fields are shown/required work as expected. 

- For each minimal page test set, add tests to check:
   - The correct fields are rendered
   - The required field and validation errors trigger on submit and prevent submission
   - The page can submit when data is valid
   - Special data states that change the page state are tested
   - Any custom functionality is tested

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81292?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel
