### ISSUE TITLE
Move common data definitions to vets-json-schema

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81297]
# Overview
Go through the pension form and identify common data definitions that should be moved to vets-json-schema so that they can be sourced from one place.   This will require some careful evaluation, but examples of this might be:
serviceBranchLabels (src/applications/pensions/components/ServicePeriodReview.jsx)

# Tasks 
- [ ] - Identify data definitions that can be moved to vets-json-schema
- [ ] - Move them and update the imports accordingly. (Save for next ticket)

**Comment by ToddWebDev** [comment]
If we decouple any web component schemas from their uiSchemas we risk becoming out of sync with any future changes to the web component pattern that can potentially break our implementation without us knowing it.

**Comment by mjknight50** [comment]
Please start with yesNoSchema and maybe another simple case and then run it by @ToddWebDev and @TaiWilkin.
