### ISSUE TITLE
[FwdProxy,GHA] VA Certificate Testing in Dev

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#81291]
## Description
Anytime we rebuild the VA cert image we need to test it.  This needs to be automated through Github Actions

## Notes
- We may have to update our script that pulls down all the VA certs  
- We need parity with what we have setup today 

## Acceptance Criteria
- [ ] VA certs are verified by GitHub actions anytime they are updated

**Comment by npeterson54** [comment]
Removing from sprint since https://app.zenhub.com/workspaces/platform-infrastructure-services-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/81841 was pulled in

**Comment by ph-One** [comment]
Closing. Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/81277
