### ISSUE TITLE
Spike: Prevent PDF and form overload

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81296]
# Overview
A bad actor/bot could force crash of our vets-api by generating a PDF that is too large to create and also too large to upload.

There are two parts to this, the validation rules on vets-website which @danlim715  has looked into and the overall rules on the back-end API.

Lighthouse Benefits Intake rules:

> Attachment & file size limits
> There is no limit on the number of files a payload can contain, but file size and page dimension limits do apply.
> Uploaded PDFs can't be larger than 78" x 101".
> Uploaded PDFs can't exceed 100 MB.
> The entire payload can't exceed 5 GB.

- [x] - Evaluate the current checks on PDF file creation to determine if they are sufficient, especially related to overflow.
- [x] - Add a check if needed to prevent a PDF that is too large to upload and too large to be reasonable (whatever that means)
- [ ] - Coordinate  with other benefits engineers and groups to communicate the size cap if the code is shared.
- [ ] - Add a check to determine file size before even trying to upload to LH Intake.
- [ ] 

Recent spike about file size limits with uploaded supporting doc: #79956 - Spike: supporting documents behavior

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81296?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by mjknight50** [comment]
It feels like the right place to do this validation could be just within the schema.  We could set a maxlength on all of the fields and be reasonably certain that it would handle malicious payload from the form submission.
