### ISSUE TITLE
Create SLAs

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#81307]
**User Story**
As a member of an OCTO Product Team, I want Service Level Agreements (SLAs) from the VA.gov Identity Team so that I can ensure we maintain a high level of service in managing user identities and access, and so that expectations are clear in terms of response times and resolution times, ensuring a smooth and efficient collaboration between our teams.

**Deliverables**

- [x] SLAs are selected
- [ ] SLAs are documented into a single document and stored within github
- [ ] A mechanism exists which allows me to automatically monitor and report out (on a request basis) on the SLAs

**Comment by dickdavis** [comment]
@jimcconnelly Do we need separate SLAs or can these all be combined into a single SLA? My thoughts are that it is simpler for us to maintain a single SLA, and customers would likely favor a single document.

**Comment by jimcconnelly** [comment]
Agreed: the simpler the better.

**Comment by dickdavis** [comment]
Initial draft: https://docs.google.com/document/d/19MqFWhbKdUtj-xrl0q3WiSDEFfesn8h_tfgaIdFemkA/edit

**Comment by dickdavis** [comment]
Whoops! I think this ticket is supposed to be for the Datadog dashboards containing the SLIs customers can reference to verify compliance with the SLA...? 😅
