### ISSUE TITLE
[xcred VSOs][Prototype] User Testing - Create task-specific prototype

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#81305]
### Description
This round of user testing will require mocks that have task-specific interactivity. Part of the requirements for these mocks have been defined by what is feasible from an engineering perspective for the ARP Pilot, while others will be defined by the results of v1 user testing with singly accredited VSO reps. 

### Output
- [ ] Creation of a mid-fidelity prototype in Figma. Creation of the prototype should draw on feedback from the prior participatory design session and feature evaluation workshop. 

**Fidelity**
Grayscale with task-specific interactivity. Confirm with the team which task flows will need to be interactive. 

### Leads or Collaborators
Lead:
Contributor:

### Resources
TBD

### Acceptance Criteria
- [ ] Prototype is prepared in Figma and has task-specific interactive elements
- [ ] Prototype has been reviewed and troubleshooting completed to ensure it is ready to be put in front of users.

**Comment by kristen101606** [comment]
We didn't get to this research before the end of the contract. Future teams can reference the [Future Research Activities Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718980793805/b1c89e3110a00b235ee30bc04bab3cc96a33c696?sender=u2a4240a640b257ce33545495) and create tickets for the research they want to run first.
