### ISSUE TITLE
DAV information in Staging does not match Trexler File

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81300]
## Expected vs. Actual
**Expected**: The Disabled American Veterans VSO has this information in the Trexler File.
<img width="1858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9CQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7116837f75820cfff5d961e221d38a57bc72dc6/image.png" alt="image.png" />

**Actual**: The Disabled American Veterans VSO has different phone number and address information in our Find a Rep Staging.
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30c0af0fc17ca5b080a102b9e1b546306e44ba81/image.png" alt="image.png" />

We just processed a new Trexler File (https://github.com/department-of-veterans-affairs/va.gov-team/issues/80980) that has the expected information.  Need to look into why that expected information is not carrying over into Staging.

## Steps to Reproduce
1. Visit [Find a Representative in Staging](https://staging.va.gov/get-help-from-accredited-representative/find-rep/)
2. Sign in with [test user vets.gov.user+232@gmail.com](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv) (row 15)

**Comment by jvcAdHoc** [comment]
Started looking at this when it was mentioned in standup. I think the issue is with the [VSOReloader](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/veteran/app/sidekiq/veteran/vso_reloader.rb#L59). 

My hunch is that using `on_duplicate_key_ignore: true` causes any possible update in the nightly OGC file to get ignored. Using `on_duplicate_key_update ` is probably what we want.

**Comment by oddball-lindsay** [comment]
Thanks @jvcAdHoc !  Adding a note that the difference in address may be due to our address validator.  The phone number should be updated to reflect The Trexler File though.

**Comment by jvcAdHoc** [comment]
Oh, yes, I didn't really tie that comment back to the specific issue. The address could only come from the Trexler file and we would display the validated version of that data. The phone number currently comes from the OGC scrape. The file available from OGC has the correct phone number, but if my above comment is correct, the old phone number would never change to the correct one.

**Comment by jvcAdHoc** [comment]
[pr](https://github.com/department-of-veterans-affairs/vets-api/pull/16470)
