### ISSUE TITLE
Publish standard definition of done or checklist to use for all VSP initiatives

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#8131]
That includes...
- Dissemination of user guide
- Release plan w/desired success metrics
- Training coordination
- Post-launch impact meeting

**Comment by rroueche** [comment]
Here's what we have so far: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/initiative-development-checklist.md

**Comment by andreahewitt-odd** [comment]
Launched Q3 2020
