### ISSUE TITLE
Document SLAs

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#81310]
**User Story**
As a VA Team member, I would like to see service level agreements related to the status and performance of authentication services on VA.gov, so I can understand what to expect from those services.

**Acceptance Criteria**
- [x] A Github-hosted document is created which explains each SLA, which contains:
   - [x] Link to the SLA data visualizations
   - [x] Easily-understood descriptions of the information contained with in the SLA data visualizations.
   - [x] Explanations as to why this SLA is important to Veterans logging into VA.gov.
 - [ ] A plan for communicating pre-determined downtime
    - [ ] How much lead time?
    - [ ] Which channels?
    - [ ] Banners during the downtime (if applicable)

**Comment by dickdavis** [comment]
Working draft for template: https://docs.google.com/document/d/19MqFWhbKdUtj-xrl0q3WiSDEFfesn8h_tfgaIdFemkA/edit
