### ISSUE TITLE
[xcred VSOs][Prototype] User Testing - Notetaking

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#81311]
## Description
This is a placeholder ticket for everyone notetaking as part of the user testing study. The person assigned to this ticket is responsible for ensuring that all notetakers complete the sub-tasks associated with this ticket and that documentation is properly stored.

### Output
**Before study kickoff**
- [ ] Create note taking template, pin from the study's Slack channel
- [ ] Create debrief documentation (Mural or Google Doc)

**Before an interview**
- [ ] Ensure notetaker has been identified for the session
- [ ] Ensure notetaker has a clean copy of the template with updated the header information for the relevant participant

**After an interview**
- [ ] Confirm notetaker has cleaned up notes 
- [ ] Ensure debrief notes are captured appropriately in [this Google doc](https://docs.google.com/document/d/1eK8JOBgYhKvSBSabjSRn0jOmX-t4R_kPXTgg4aSxtRo/edit)
- [ ] Download Mural notes as a PDF and upload to Sharepoint folder
- [ ] Add notes to session documentation within EnjoyHQ

**End of study**
- [ ] Confirmed all notes are in Sharepoint
- [ ] Upload completed [Google doc of key takeaways](https://docs.google.com/document/d/1eK8JOBgYhKvSBSabjSRn0jOmX-t4R_kPXTgg4aSxtRo/edit) to Sharepoint
- [ ] Confirmed all notes are in EnjoyHQ
- [ ] Confirmed all debrief documentation is saved

### Resources
- [Research plan]
- [Conversation guide]
- [Notetaking template (Mural)]
- [Sharepoint folder]
- EnjoyHQ project file

## Acceptance Criteria
Notes for all interview and debrief sessions are cleaned up and stored in Sharepoint and EnjoyHQ

**Comment by kristen101606** [comment]
We didn't get to this research before the end of the contract. Future teams can reference the [Future Research Activities Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718980793805/b1c89e3110a00b235ee30bc04bab3cc96a33c696?sender=u2a4240a640b257ce33545495) and create tickets for the research they want to run first.

**Comment by kristen101606** [comment]
We didn't get to this research before the end of the contract. Future teams can reference the [Future Research Activities Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718980793805/b1c89e3110a00b235ee30bc04bab3cc96a33c696?sender=u2a4240a640b257ce33545495) and create tickets for the research they want to run first.
