### ISSUE TITLE
SOCKS access for Troy Griffin

### ISSUE THREAD

**Issue by TroyCMSSupport** [department-of-veterans-affairs/va.gov-team#81325]
### Your Name

Troy Griffin

### Your Email

troy.griffin@hitssllc.com

### Your GitHub Handle

TroyCMSSupport

### Your Role and Team

Help Desk  CMS Drupal - VFS CMS Team

### Product Manager (PM) name and email

Michelle Dooley michelle.dooley@oddball.io

### Product Owner (PO) name and email

Erika Washburn  erika.washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWbk1WJ19P5cHfhGAzgNVldFPQ+JbEhDueNjQn6YubLHKHHU2bgPuT2/VGmkyiokPEHISE9iCYIEpyos9ydittosuAi9Dtpy50k849dbNqsIIOuPHeGkdf9OWPKKDzLJrzZjrD5U+yVgTwMNsglOrXOgtzbrh2fP70x0jc92cIatCB7uG2fhOKHafV8NGbQbhPknbeOMlKzDphR4hprcaaRDhhBR8g+A1cmELgMHVIshj9s4lTYZWNQUx1+uBdqMaQ8hTbB8+P9yf7CIoT1+09Sao/C9370saUTj959gEnTg9G0w8kSorazCof57eSUrPqtbk+B6oU6QW7f8ovHVnPpVBt/FBS8pxaQD0wx/fN8A+bA8y+bohKrH0edGwd9gUdrXdPIEpBTPfjx92GnyMgBIvCsof76Gy3kaFjqrY5eLoFOc6NuB6ZXzJaqqLdhnEVpMAdTInJnQFFSQqGUWgEaq0CecHBMk+X+yHZ4yRBMn0kDtXmT19baxOBjMhgpNk= troygriffin@Troy-VA-Support

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/166865749/10b43569-f245-4df7-b509-1c03c3188745)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by michelle-dooley** [comment]
Just following up on this request.
