### ISSUE TITLE
10-7959f-1: Edits to Intro page 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#81332]
As a user on VA.gov, I want to see the intro to the online FMP registration form so that I know what the form is about before I begin filling it out.  

- Update [intro page](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/introduction) copy to reflect latest Figma:
  - Remove "Have you applied....?"
  - Remove "Follow the steps below..."
  - Remove copy ("What if I need help filling....") underneath blue "Sign in" box on current staging page 
  - update subheader text (this should be applied to all other pages): "FMP Registration Form (VA Form 10-7959f-1)"
  - add intro text
  - add "What to know..." header and text
  - Add block of text (Respondent burden, view privacy Act statement link, etc) underneath blue "Sign in" box
  - In blue "Sign in" box, update button text to "Sign in to start your form"
  - Update link text to "Start your form without signing in"
- [Figma](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1241-57054&mode=design&t=KpUgTu70rkHUdo7b-0) link of intro page (navigate to 'intro page' area - also left a comment).

Acceptance criteria:
- Given I am a user on VA.gov,
- When I go to fill out the FMP registration form online,
- I see the intro page with the latest copy from Figma

**Comment by reiting** [comment]
@marywang2 branch is 10-7959f-1-intro-changes for local review

**Comment by marywang2** [comment]
Thanks @reiting! I just had a few minor comments:
- looks like there may be extra spacing above the "What to know before you fill out this form" header (but please check on your end)
- update link text and button text, should refer to "form" rather than "application" (since they are registering rather than applying).

**Comment by marywang2** [comment]
Changes look good, closing.
