### ISSUE TITLE
[BE] 10-10EZ - BUG: Investigate issue "Request Entity too large"

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#81336]
## Background
The 10-10EZ has received several errors with the message "Net::HTTPPayloadTooLarge: Request Entity Too Large".  We need to investigate how large these payloads are, compared to the 150mb limit for Enrollment system.  Possible that these are failing at the gateway between VA.gov and Enrollment system.

### Resources
- [DD APM Log from 4/22/2024](https://vagov.ddog-gov.com/logs?query=trace_id%3A1753581659191861307%20&cols=host%2Cservice&event=AgAAAY8HsY1TqQkjTQAAAAAAAAAYAAAAAEFZOEhzWlliQUFCMGk3blplOW1pNEFBRwAAACQAAAAAMDE4ZjA3YjMtMWIwYy00ODZlLTlhOWItYzhiYjZmYzMxYmUx&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1713820025010&to_ts=1713822027812&live=false)
- [DD APM log from 5/10/24](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20-status%3Aok%20resource_name%3A%22HCA%3A%3ASubmissionJob%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_span.count%2C%40_duration.by_service&fromUser=false&graphType=flamegraph&historicalData=true&query_translation_version=v0&saved-view-id=1736&shouldShowLegend=true&sort=time&spanID=661388937585140596&spanType=service-entry&spanViewType=errors&timeHint=1715377722605&trace=AgAAAY9ketTtT30FAQAAAAAAAAAYAAAAAEFZOWtldHhvQUFCdXZNT0REa0lFR2FrSwAAACQAAAAAMDE4ZjY0ZjMtMDdmNC00M2UzLTkxYzEtNTUzZmU4ODMwNWIz&traceID=768228758250608336&traceQuery=&view=spans&viz=stream&start=1715000743356&end=1715605543356&paused=false)
- [Sentry log from 5/10/24 (not much help)](http://sentry.vfs.va.gov/organizations/vsp/issues/249944/?environment=production&project=3&query=is%3Aunresolved+job%3AHCA%3A%3ASubmissionJob)

## Tasks
- [ ] Investigate error to determine root cause, or possible causes
- [ ] Discuss with PM/Team

## Acceptance Criteria
- We have discussed the cause(s) for this issue and identified next steps.

**Comment by coope93** [comment]
Looks like the 5.10.24 occurrence had 5 attachments.

**Comment by coope93** [comment]
We added more logging in the PR above around the payload size and number of attachments of form submissions. This should give us more context the next time this error occurs around what may be causing this issue. I am moving this ticket to closed, and if we see more occurrences we can create a new ticket for further investigation with the new logging there to hopefully find a good solution.
