### ISSUE TITLE
Align content for Rep Status Widget + Find a Rep

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81331]
## Background
In QA, some content updates were flagged for both the Rep Status Widget and the surrounding Find a Rep page.  These content updates are outlined in the task list below.

The [Figma for the Rep Status Widget states has been updated](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=1283-176978&mode=design&t=PkoB5qkNUXycfytE-0), for a visual of the expected Widget content.

#### Representative Status Widget content:
- [x] Update the **description copy above the Widget** to “We don’t automatically assign you an accredited representative, but you may have appointed one in the past.” (Staging has "VA doesn’t automatically assign you an accredited representative. But you may have appointed one in the past.” but that content has since been updated from CAIA)
- [x] **Auth no rep, Auth individual, Auth organization (3 states)**: Update FAQ URL to `https://www.va.gov/resources/va-accredited-representative-faqs/` 
- [x] **Auth individual, Auth organization (2 states)**: Update `hx` to "Your current accredited representative" (Staging has "Your accredited representative" but content source of truth has "Your current accredited representative") 
- [x] **Auth organization (1 state)**: Update `hx-1`, so it only has the VSO name (Staging has "Accredited with [VSO]" but content source of truth has "[VSO]", so we need to remove "Accredited with")
- [x] **Error (1 state)**: Remove the "What you can do" line (not in content source of truth, so we can remove for a slimmer alert)

#### Find a Representative surrounding content:
- [x] Update **first additional info component** to read "What does an accredited VSO representative do?" (leaning into the term update from VSO -> VSO Representative)
- [x] Update the **definition within this first additional info component**, so the **first paragraph** starts with "An accredited Veterans Service Officer (VSO) representative can help you gather evidence" and the **second and third paragraphs** start with "Accredited VSO representatives"  (leaning into the term update from VSO -> VSO Representative)

## Acceptance Criteria
- [ ] Content accurately matches CAIA's content source of truth

**Comment by cosu419** [comment]
Noticed a local change that wasn't committed for updating the 2nd and 3rd paragraphs of the additional info component - fixing now.

**Comment by oddball-lindsay** [comment]
95% there!  @cosu419 I'm getting a broken link on the Org state -- seems like it's trying to hit `https://www.va.gov/va-accredited-representative-faqs` which is incorrect.  Can you please update the Org state and double check the Individual state?  The link is working as expected on the No Rep state.

**Comment by oddball-lindsay** [comment]
FAQ link is working as expected now for both the individual and organization states -- thank you!
