### ISSUE TITLE
[ZOOM]: VAOS - CONSIDER Upcoming appointments tab goes to two lines at 400%

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#8134]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The Upcoming Appointments tab rolls over to two lines at 400% zoom by 1280px browser width. This is a low priority, consider fix only. Screen shot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Label stays on one line at 400% zoom, assuming 1280px screen width

## Screenshots or Trace Logs

<img width="1237" alt="Screen Shot 2020-04-17 at 11 00 21 AM" src="https://user-images.githubusercontent.com/934879/79589457-0c210c00-809b-11ea-8ac9-75a5d56ce386.png">

**Comment by jenniemc** [comment]
Hi @1Copenut, there is a mismatch in tab height because "Upcoming Appointment" did a text wrap to fit inside the tab. Would having matching tab height satisfy the fix? 

![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/cb2dd1ec-e699-40bd-9fd8-9650161dcfaf)

cc: @lenaecb

**Comment by 1Copenut** [comment]
Hi @jenniemc. I think matching tab heights would work, esp. if we could center the text vertically. I'm tagging @CrystabelReiter for her design input since I haven't designed anything in quite a while :)

**Comment by CrystabelReiter** [comment]
@jenniemc This works, perhaps we can center the "past appointments" tab within the tab to help with the balance of it. @1Copenut thanks for tagging me !
