### ISSUE TITLE
Research options for adding mock appointment data to CES

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#81348]
In order to properly test the Oracle Health Appointment functionality, we need to have existing appointment information available in the CES infrastructure.  Research the possibility of mocking Appointment data and document the recommended approach/location for the mocks.

**Comment by devin-mccurdy** [comment]
Uploaded example file to github

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/appointments-oracle-health-integration/engineering/loading-mock-cerner-data.md
