### ISSUE TITLE
Longer address text should wrap in container

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81340]
## Background
From our accessibility audit:
> I wasn’t able to find a user who meets these criteria, but using the dev tools I made it so that the street number and name were longer than 50 characters at 500% zoom, this causes the text above the address block to also spill outside of the viewport as seen in the screenshot attached. When I asked the DST about this, they said “[The text should wrap to stay not only within the viewport but also within the container.](https://dsva.slack.com/archives/C01DBGX4P45/p1713814442445109)” I’d say that this is probably pretty low priority since the only way I was able to trigger this issue was with an entirely contrived address. There is a chance VA’s databases don’t support street names this long. [Using the address block from the design system may help to resolve this issue](https://design.va.gov/components/address-block).

<img width="1164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFNDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b87c830b279458f172daa43b36f5c90b426b3d3/image.png" alt="image.png" />

#### Impact
Out of 17114 Reps:

- There are 4414 addresses that are greater than 48 characters.
- There are 3724 addresses that are greater than 49 characters.
- There are 3171 addresses that are greater than 50 characters. (18%)

Out of 105 Orgs:
- There are 12 addresses that are greater than 50 characters. (11%)

**Steps to Reproduce:** 
1. Using dev tools, edit the street name and number to be longer than about 50 characters long
2. After editing the street name and number zoom the browser, watching the address and surrounding text -- it will eventually overflow the containing div, and then the viewport. 

## Tasks
- [ ] Ensure text wraps in the container when zoomed in at 500%

## Acceptance Criteria
- [ ] Longer text wraps in the container when a user is zoomed in at 500%.

**Comment by cosu419** [comment]
I think there's an issue with how this was tested? It does break if there are 50 characters with no spaces, but if one space is included then it's not an issue. 

It looks like the longest possible word is 33 characters, so this only becomes a problem for addresses that contain a single word longer than that (would be surprised if one exists). Here's how it looks with 99 characters broken up by just 3 spaces:

<img width="1832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b90b6c6538d611ffc216e5ffbc91fc004b1de85/image.png" alt="image.png" />

<img width="1831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--698e25cd7acf9e8172dbbbadf17f1cf6bbad28fc/image.png" alt="image.png" />

Looking into a fix regardless, but there may be some styling rules which are being set on the va-card which are overriding my styling.

**Comment by oddball-lindsay** [comment]
Great find, thank you!  This was a "minor" priority from the accessibility team and I think that your finding means the acceptance criteria holds in a realistic scenario where the real limit is 33 characters.  Thinking we can close this out and I can let a11y know that the test scenario is likely not a realistic scenario ...and that we're covered for the realistic scenario. 

Sound okay @cosu419 ?

**Comment by cosu419** [comment]
@oddball-lindsay works for me. I did commit a one-line fix for this, but it's more of a fallback and doesn't change any existing use cases. Will close this out for now.
