### ISSUE TITLE
Identity SDK - Consider which tsdoc library to use

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#81354]

**Comment by parkerbees** [comment]
@acald-creator it looks like this was moved to "current sprint" about a month ago - is the intent to complete this work in the current sprint (before July 17)? If not I will move to backlog. Thanks!

**Comment by acald-creator** [comment]
will raise PR to add api-extractor by EOD

**Comment by parkerbees** [comment]
moved to Jira, closing
