### ISSUE TITLE
Verify all form validation and conditional page logic

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#81359]
Form 10-7959c's flow is now complete (from a structure standpoint, not content-wise), so this ticket is a QA/polish/bug finding ticket. There are several conditional page triggers and lots of form pages with special validation needs, so the goal here is to verify that the form behaves as expected and that users aren't confronted with vague errors or difficulties submitting.

[Figma link](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1155-73969&t=JMkoJgz24UZdROlA-0)

Acceptance criteria
- Manual verification of all inputs (spreadsheet of verification)
- Manual verification of dependent page logic (spreadsheet of verification)

**Comment by michaelclement** [comment]
[Spreadsheet of verified conditionals here](https://docs.google.com/spreadsheets/d/1NGNOYv4B9TP5U3IOUSshj6B-z6FTo5kczpFKB0tZaIc/edit?usp=sharing)

**Comment by michaelclement** [comment]
[Once this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31077) is merged this should be good to go. Only issue was on the confirmation page when required files were still missing. Had to update the alert from green to yellow per the Fima, and adjust some conditional wording.

**Comment by michaelclement** [comment]
Additionally, the validation was checked over in [this PR](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/87545) when making sure all the individual fields stamped on the PDF appropriately, so there's a bit of crossover there.

**Comment by michaelclement** [comment]
@baltes @marywang2 - PR merged. To review, please see the above attached spreadsheets. Thanks!

**Comment by baltes** [comment]
One file linked above looks good. I don't have access to the other yet, but I'm closing this out to close the sprint. I'll still check back on this and reopen if any issues pop up.
