### ISSUE TITLE
List of fixes on forms search experience (before and during phased launch)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8135]
## This is a list of fixes we need to make to the Find a VA form search experience. 

- [x] 1/ Remove the blue color for the form number+name header text. (Leave the bolding.)  - Blue makes it look like a link. We won't link this text until form detail pages are ready. 
**ETA:** This should be done before launch.

- [x] 2/  Update breadcrumb - it should show Home > Find a VA form -- see this root page as example: https://www.va.gov/change-address/ [This is a Drupal task.]    
**ETA:** This should be done before  launch.

- [x] 3/ Please re-open [this ticket #7474](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7474) to include the same download behavior on IE browser. (Update: #7474 has been re-opened with a comment)
**ETA:** This can be done after/ at 100% launch. 

- [x] 4/Complete ticket #8177 - move the Manage links into link+teaser component. 

- [x] 5/Make copy updates recommended by Peggy VSA Platform review. [The Drupal copy updates are complete. However, there are some updates needed inside the REACT component which require FE engineering help.  @ncksllvn - will upload doc below.]

^ If the release plan enables launching in phases - %age of traffic until 100 -- 1 and 2 should be done before the first %age phase; and 3 can be done anytime before 100% or shortly after 100% launch.

**Comment by rtwell** [comment]
## VA Form search landing — default

![image](https://user-images.githubusercontent.com/12564977/79783644-f6b41800-830e-11ea-80db-75ed8200ba2e.png)

## VA Form search landing — search results

![image](https://user-images.githubusercontent.com/12564977/79783736-19dec780-830f-11ea-9655-cbcf71f807c1.png)

## VA Form search landing — search results on mobile

![image](https://user-images.githubusercontent.com/12564977/79783773-295e1080-830f-11ea-9b4f-19fb25258a36.png)

**Comment by jenniferlee-dsva** [comment]
Fysa @stephorkandatx - updated original checklist above. 

@ncksllvn - per ^, I need your help implementing Platform suggested copy updates inside the REACT component. Attaching Word document here - see the blue highlights for you to make. 

[VA-forms-slp-updates-post-staging-review-pg-jl-042220.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4519491/VA-forms-slp-updates-post-staging-review-pg-jl-042220.docx)

@RLHecht - after Nick makes copy updates in the REACT part of the page, the whole forms page will be ready for your final once-over and copy edit. The attached Word doc shows all of the updates made today in highlights. (Blue - REACT changes. Yellow - Drupal changes.)

**Comment by ncksllvn** [comment]
@jenniferlee-dsva Do these updates to the blue boxes look okay?

![image](https://user-images.githubusercontent.com/1915775/80124167-d5953680-855d-11ea-8faf-96e78bfbc0f9.png)

**Comment by ncksllvn** [comment]
@rtwell I noticed the pagination component is left-aligned in your design but unfortunately that's a design system component that we're leaving on Find Forms. Should we plan on making the update there instead?

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - 2 things:

- Make text: "Frequently used forms" no hyphen.
- GI Bill card: "Equal to" is now "Includes" -- Includes VA Forms ...blah blah.

Can we also see the text change for the search bar? I think that's also inside REACT.

**Comment by ncksllvn** [comment]
Sure!

<details>
<summary>search bar</summary>
![image](https://user-images.githubusercontent.com/1915775/80125867-41789e80-8560-11ea-82ae-aac10f8b30f6.png)

</details>

<details>
<summary>blue boxes</summary>
![image](https://user-images.githubusercontent.com/1915775/80125851-3a519080-8560-11ea-8b65-07a1c3126b08.png)

</details>

**Comment by jenniferlee-dsva** [comment]
LG - thank you!

**Comment by jenniferlee-dsva** [comment]
Gonna answer for @rtwell - pretty sure he meant to use the design system centered pagination. Please use the design system style for forms.  @ncksllvn

**Comment by jenniferlee-dsva** [comment]
@RLHecht  ^ Looks like Nick has made the copy updates inside the REACT parts of the Drupal page, so this node is ready for your final copy check and publish. Could you please make sure to TB with @stephorkandatx  before making copy updates "publish"?  (To check on timing - that it won't collide with other staging review checks that might be happening at the same time.)  Thank you!

**Comment by RLHecht** [comment]
@jenniferlee-dsva @ncksllvn One change in the text above the three blue boxes (pretty sure that's in the widget and I can't access it in Drupal). It should read:
You can now do many forms-based tasks online, like filing a disability claim and applying for the GI Bill or for VA health care benefits. We'll walk you through the process step-by-step.

**Comment by jenniferlee-dsva** [comment]
Hi @RLHecht - I do see that change now in the screenshot of the REACT updates that Nick posted above in this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8135#issuecomment-618509690

Just checked the live page and see it there too: https://www.va.gov/find-forms/ (user: veterans / access: usausausa)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I'm not seeing the updated copy above the blue boxes. There needs to be another "and" in that sentence because the list is reading wrong to me. We are using "applying" for both the GI Bill and VA health care benefits.
  
New copy: 
You can now do many forms-based tasks online, like filing a disability claim and applying for the GI Bill or for VA health care benefits. We'll walk you through the process step-by-step.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - could you add the missing "and" per Randi's check ^? 

You can now do many forms-based tasks online, like filing a disability claim `and `applying for the GI Bill or for VA health care benefits. We'll walk you through the process step-by-step.

**Comment by RLHecht** [comment]
@ncksllvn Can you please change the text above the blue boxes in the widget to the following? It should read like this:

You can now do many forms-based tasks online, like filing a disability claim and applying for the GI Bill or VA health care. We'll walk you through the process step-by-step.

Once that's changed I can publish. Thank you!
FYSA @jenniferlee-dsva

**Comment by ncksllvn** [comment]
Opened a PR to update that, https://github.com/department-of-veterans-affairs/vets-website/pull/12395.

**Comment by RLHecht** [comment]
Nick's change was done and the page published.

**Comment by stephorkandatx** [comment]
Confirmed the change to the link color (task 1) and the changes to the copy (task 5). 
Per a conversation in Slack, I want to document that there was a minor update to the copy that was provided by Randi, so that it should read "You can now do many form-based tasks online, like filing a disability claim and applying for the GI Bill or VA health care. We'll walk you through the process step-by-step. "

The change, specifically, was changing "forms-based" to "form-based"
