### ISSUE TITLE
Write an E2E Cypress test

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#81361]
We need an E2E Cypress test both to ensure the form behaves as expected, and to satisfy the requirement before going to production.

Acceptance criteria
- An E2E test for form 10-10d exists
- the E2E test can be automatically run

**Comment by michaelclement** [comment]
Work is done on this. [PR is here](https://github.com/department-of-veterans-affairs/vets-website/pull/29525). Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by marywang2** [comment]
@michaelclement any pointers on how to review this?
