### ISSUE TITLE
Adding Bridget King to DSVA Slack

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#81362]
# Adding Bridget King to DSVA Slack

Bridget King is a GovCIO new hire who will be supporting the CoPs and currently does not have a slack account.

Are you requesting to add an individual as a:

- Full member X
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Please add bridget.king@va.gov as a full member.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by KevinMHoffmanUSDS** [comment]
Done
