### ISSUE TITLE
[Development] 526: Handle Additional Error Codes on inProgress Call

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#8138]
## User Story:
As a result of adding original claims support to the 526 form, there are a couple additional error codes that the front end should support on the inProgress request. Connect with the back end to verify the codes that need to be handled and how to handle them. Collaborating with design may be helpful in determining the appropriate error messaging to display. I believe handling these errors will involve making changes to the general form inProgress code flow, so it will also be important to make sure other forms are not negatively impacting by this change. 

## Acceptance Criteria:
- [ ] 526 handles additional error codes supplied by the back end with appropriate messaging

**Comment by luke-gcio** [comment]
Review this in sprint 25.

**Comment by annaswims** [comment]
Some of this has been done already.  We moved the "add person to MVI" code to a separate controller and @Mottie handled those errors already.  There may be additional error responses that have been there all along, but I don't believe they'd be specific to BDD.

**Comment by luke-gcio** [comment]
This started out under 526 (OG Claims) but it is now moved onto ensuring we are actually working with BDD since this code was added (additional error checking) and we just need to validate that it works.
