### ISSUE TITLE
Fix Sidekiq Jobs broken link

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#81397]
- [x] Fix all the broken links in the document, [Sidekioq Jobs](https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-jobs).

Acceptance Criteria

- [x] [Sidekioq Jobs](https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-jobs) is deployed with zero broken links

**Comment by jknipes** [comment]
Work completed, moving to _Done_
