### ISSUE TITLE
[EKS] ArgoCD

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#81399]
# Acceptance Criteria
- [ ] Deploy ArgoCD _per cluster_ using helm
- [ ] Add a flag for deploying Argo under `env_vars.yaml`

# Notes
- This migrates us from a central Argo to a per-cluster Argo
- Source will be located in https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure
- Enables exposing individual Clusters/ArgoCD's, while not exposing all

**Comment by ph-One** [comment]
@adhoc-nshipman evaluate if we still need this issue. Looks to be replaced by the newer [broken down] issues

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86468
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86470

**Comment by adhoc-nshipman** [comment]
We can close this @ph-One

**Comment by kflow85** [comment]
Closing ticket out in Zenhub as this is being tacked in GitHub Projects https://github.com/department-of-veterans-affairs/va.gov-team/issues/81399#issue-2259234819
