### ISSUE TITLE
[SPIKE] For MVP, brainstorm how we might want to show all referrals to Veterans

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81410]
## Tasks

- [ ] For MVP, brainstorm how we might want to show all referrals to Veterans.

**Comment by benbrasso-agile6** [comment]
@cgednalske what's the next step here? Is this work completed? And, we're going to address in research? I'm forgetting where we left off yesterday. Thanks

**Comment by benbrasso-agile6** [comment]
Appointments page, surfacing door to referrals - https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1441-26028&t=m52lmcLQ6is65hdi-4

**Comment by benbrasso-agile6** [comment]
@cgednalske rdy to close?

**Comment by cgednalske** [comment]
Linking to Ciera's [prototype/screens of the referral placement concept](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1755%3A82267&t=PZzCgsmKgF2wOvg0-1) we'll test with Veterans 🎉 

@benbrasso-agile6 yep, good to close!
