### ISSUE TITLE
Spike: Investigate how we can isolate TermsOfUseAgreementsController with Sign in Service Isolation

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#81428]
Components of this file `app/controllers/v0/terms_of_use_agreements_controller.rb` need to be moved to SiS only when the SiS isolation occurs, so we need to come up with a plan on how we can 'isolate this controller

**Comment by parkerbees** [comment]
Moved to Jira. Closed.
