### ISSUE TITLE
[team] 10-10EZR: Make sure every team member has access to tools

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#81425]
As a team member, I would like access to tracking and tracing tools so that I can help if something breaks. 

- [x] Come up with a list of all of the tools we could have access to: use [this list](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) as a jumping off point
- [x] Have tools we need
- [x] Name of people who need access and create a checklist
- [x] Keep a list of how to get access
- [x] **Success: Every team member has access to every tool they need to use**

**Comment by mkerns1** [comment]
| Tool Name        | Matt K        | Josh          | Derrick       | Allan         | Links to Docs |
|------------------|---------------|---------------|---------------|---------------|---------------|
| Datadog          |               |               |               |               |               |
| Sentry           |               |               |               |               |               |
| SOCKS            |               |               |               |               |               |

**Comment by emily-brown34** [comment]
josh has created a DD ticket, matt k is still in the process for submitting one

**Comment by emily-brown34** [comment]
have to do OCTO ticket first, then DD

**Comment by emily-brown34** [comment]
Allan to submit for edit/write access for the feature flags/flipper

**Comment by allanto-ah** [comment]
Submitted access [request](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/82720) here, pending resolution from that team

**Comment by allanto-ah** [comment]
Got access to everything listed

**Comment by JoshingYou1** [comment]
I have access to everything.
