### ISSUE TITLE
CES-318 CES: Migrate to mobile-framework-v2

### ISSUE THREAD

**Issue by BrittanySFowler** [department-of-veterans-affairs/va.gov-team#81432]
CES-318: https://issues.mobilehealth.va.gov/browse/CES-318

This work is tracked and merged in Jira CES-318 https://issues.mobilehealth.va.gov/browse/CES-318
Mobile-Framework v1 support is near EOL, and Mobile-Framework v2 is the successor with updated software libraries and dependency management.

**Acceptance Criteria:**

Service is updated to Mobile-Framework v2, following the migration guide: https://coderepo.mobilehealth.va.gov/projects/CKM/repos/mobile-framework/browse/docs/reference/upgrading/v1-migration-guide.md?at=refs%2Fheads%2FRelease%2F2.1
Service can be built successfully
All unit and integration tests run successfully

**Comment by crhicko** [comment]
This story is temporarily paused until a downstream dependency is upgraded to MFv2. That dependency is currently being upgraded and then this can be resumed

**Comment by BrittanySFowler** [comment]
This story will roll due to still waiting on the dependency upgrade

**Comment by BrittanySFowler** [comment]
Since the downstream dependency is still not done we are putting it back in the backlog until the dependency is completed
