### ISSUE TITLE
ESLint rule - no react partials

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#8143]
Sometimes we see this pattern:

```jsx

const myComponentPiece = <div>No props or args - just static text</div>;

// ...

return (
    <>
        {myComponentPiece}
        <AnotherComponent prop1="foo" />
    </>
);
```

Having the separate const or function to create a partial react component often doesn't add anything and just creates another layer of misdirection. Consider the effort required and the expected benefit of an ESLint rule that could automatically inline partials like the example shows.

**Comment by timwright12** [comment]
Was not able to find something off the shelf for this and and effort to create custom does not align with the value. Closing out.
