### ISSUE TITLE
10-10EZR - Bug - Redundant progress header sections at top of form

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#81439]
### Summary
Environment: Staging
Staging user: vets.gov.user+11@gmail.com

On the top of the 10-10EZR form, there are two progress headers (See attached video for reference). I also attached what the 10-10EZ form looks like as they don't have the two progress headers.

### Steps to reproduce:
1. Login as the above staging user (or any user that can fill out the EZR form
2. Navigate to the EZR form (https://staging.va.gov/my-health/update-benefits-information-form-10-10ezr/introduction)
3. Start (or continue) the form
4. Notice at the top of the page, there are two progress headers and will be seen throughout the entire form (see attached video)

EZR video:
[10-10EZR](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c29deb4f02d8f88cdd09f56191e3d7c0fb095f36/ezr-multiple-headers.mp4)

EZ screenshot:
<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b47a4e12afcb8d8c68d007fbb89e73b2f099a3e/ez-form.png" alt="ez-form.png" />

**Comment by longmd** [comment]
You can reference #81159 for steps to rectify. I took care of this with the EZ & CG last week.

**Comment by mkerns1** [comment]
<img width="865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b062465fe55c671e5b072f45fc676ac1b487d19d/image.png" alt="image.png" />
<img width="922" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20b35c3034bee47e4fb1554f283366176e9c99db/image.png" alt="image.png" />

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this has been fixed. 

<img width="1342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77ddcc34a6c6689d47193aa1c8cf5457a7eb3e72/Screenshot%202024-04-25%20at%203.30.12%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 3.30.12 PM.png" />
