### ISSUE TITLE
Design Intent - Design Feedback - BAH-MBS-SelfServ, Pre-Need Self Service, Pre-Need Address Validation

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#81463]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Matt: Must: I don't think you need the extra text in the buttons, use the "back" and "continue" buttons.
- [x] Matt: Must: I don't think you need to show the address again after they edit or confirm the address. You do not even need the confirmation message. We can allow them to review it at the review step.
- [x] Matt: Must: With the address you could not validate, if the fields return an error then show them as required. You can use the 1 question per page thing and ask if they have a foreign address before this page.
- [x] Matt: Must: If there is no recommended address available, then either default to an answer or do not give them a radio button that does nothing.
- [x] Should: Take a look at the [radio button tile](https://design.va.gov/components/form/radio-button#tile) UI option.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by barron-charles** [comment]
**For this one:** "With the address you could not validate, if the fields return an error then show them as required. You can use the 1 question per page thing and ask if they have a foreign address before this page." You can reference the prototype, but parts of the form preset required fields such as applying for self applicant and applying for someone else preparer sections, and the applying for self but the someone else sponsor section doesn't have required fields. We plan to introduce the required fields as you all recommended, when the user inputs information in a field that is a field such as the street address or postal code.

If this is the case, we wouldn't require the one question leading up to this page.

**Comment by barron-charles** [comment]
**With this one:**: If there is no recommended addresses available, then either default to an answer or do not give them a radio button that does nothing. 

Is the the interpretation basically to have the entered address default for the suggested address or remove the suggested address field entirely?

**Comment by allison0034** [comment]
The problem is when you cannot verify an address, both the entered and suggested addresses (which are radio buttons) are the same, which means you are asking the user to do something that is not actionable and could be confusing. You could ask them to verify the entered address by asking is this address correct and using a yes/no radio button, and I am sure there are other options. We just do not want to show 2 addresses that are the same and ask them to choose one.

**Comment by barron-charles** [comment]
@allison0034 thank you. Will reassess and keeping workin through solutions with this.

**Comment by carly-yamrus** [comment]
Hi @allison0034  ! Re: the feedback _"You could ask them to verify the entered address by asking is this address correct and using a yes/no radio button, and I am sure there are other options." _  Looking at this yes/no design -  by clicking "No", we are asking them to click "no" and "continue" (we would not want them to continue with a wrong address) or "no" and "back" (which is essentially having them click "no" for no reason.)
<img width="238" alt="Screenshot 2024-05-14 at 2 27 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/125381396/377b5283-3a66-489b-ae65-7ce16bd8b6a3">

Looking at other ways to let the user know that the address wasn't validated but they can continue or go back and edit.
