### ISSUE TITLE
Create and Review GIBCT tickets (GI Bill)

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#81473]
Review the current state of our transition of GIBCT to EKS and scope out work for it.

- [ ] Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/78105
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81011
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80300
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80302
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80303
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78107
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80372
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78111

## Acceptance Criteria

- [ ] Tickets are created for the upcoming work around GI Bill's EKS migration

**Comment by JoeTice** [comment]
We had a meeting on 11/4 to discuss the current state of this work, and tickets that were being created to help get this moving forward. At the moment, it seems like the currently existing set of tickets are still viable and will be part of this work.
