### ISSUE TITLE
[DRAFT] Analytics Implementation for Facility Locator Chatbot link

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8148]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description

Google Analytics implementation for link to new COVID-19 chatbot from Facility Locator main search page.  **This request is a DRAFT, pending the approval and addition of text: [#8147](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8147)**

Who is this request for?
- Michelle Middaugh

What team/project is this work for?
- Facilities
    
Provide the Domain where Google Analytics needs to be implemented
 - https://www.va.gov/find-locations
 - This page has no PII concerns
    
Please provide any upcoming deadlines or important milestones
 - As this is COVID-19 related, there is interest in implementing this quickly.
 
*Other User Interactions*: 
- We want to track the number of users who click on the Chatbot link located within the text of the Facility Locator main page.
- Facility Locator is part of the unauthenticated experience. Test users, etc are not applicable. 

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by mmiddaugh** [comment]
**This request is a DRAFT, pending the approval and addition of text: [#8147](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8147)**

**Comment by jonwehausen** [comment]
@mmiddaugh Thanks Michelle, confirming receipt.

**Comment by bsmartin-ep** [comment]
@mmiddaugh -

> We want to track the number of users who click on the Chatbot link located within the text of the Facility Locator main page.

If you're just looking to follow the path from the Facility Locator to the Chatbot page via a link or button, you shouldn't need any custom tracking from us.

One option is to view the [Previous Page Path](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p176188361/_u.date00=20200401&_u.date01=20200420&_r.tabId=explorer&navigationsummary-keySelector.searchTerm=find-locations&explorer-table.filter=coronavirus-chatbot&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22coronavirus-chatbot%22,0%5D%5D/) on the chatbot page itself.

(No data yet)

You could also use the [Navigation Summary report](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p176188361/_u.date00=20200401&_u.date01=20200420&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22%5E~2Ffind-locations~2F%5Bindex%5C%5C.html%5D*$%22,0%5D%5D&_r.tabId=navigationsummary&_r.drilldown=analytics.pagePath:www.va.gov~2Ffind-locations~2F&navigationsummary-keySelector.searchTerm=find-locations/) on the Facility Locator page.

**Comment by bsmartin-ep** [comment]
@mmiddaugh -

I see some data for the _Previous Page Path_ on the chatbot page...

https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p176188361/_r.tabId=explorer&navigationsummary-keySelector.searchTerm=find-locations&explorer-table.filter=coronavirus-chatbot&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22coronavirus-chatbot%22,0%5D%5D/

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/f3b780db-2e3f-459e-84ab-084c99a1b661)

Does this meet your criteria?

**Comment by mmiddaugh** [comment]
It sure does! Thank you @bsmartin-ep

**Comment by bsmartin-ep** [comment]
Great, @mmiddaugh!  Closing.

Please let us know if you have any other reporting requests related to the chatbot.
