### ISSUE TITLE
Datadog actions capture user navigation clicks

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#81491]
### User story

As a Cartography team member, I want Datadog to capture in a clearly named "action" which element the user clicked to get from the MHV landing page to one of the 4 main tools, so that we can distinguish between use of the secondary nav and other links.

### Notes
- Need to discover whether DD captures clearly-named actions by default or [requires custom attributes](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/#declare-a-name-for-click-actions) to be added to component(s)
- Is there a way to debug this in the browser before merging to Staging?

Possible tasks:
- Inventory links that tool teams are updating for integration

## Acceptance criteria

- A clearly named action is visible in Datadog funnels when a user navigates from one page to another using these navigation elements in the UI: 
  - [ ] secondary nav
  - [x] ~breadcrumb~ – no action required for landing page
  - [x] in-page links – existing datadog actions are adequate
- [ ] Update implementation plan doc to include the Datadog tips for tool teams
- [ ] QA review (by someone with DD access)

**Comment by dcloud** [comment]
Since I have [the documentation page](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/#declare-a-name-for-click-actions) open:

> The Datadog Browser SDK for RUM uses various strategies to get a name for click actions. If you want more control, you can define a data-dd-action-name attribute on clickable elements (or any of their parents) that is used to name the action.

**Comment by dcloud** [comment]
Outline elements with the action name in lime green: `document.querySelectorAll("[data-dd-action-name]").forEach(el => el.style.setProperty('outline', '6px double lime'))`. 

Could be a CSS rule in an extension like Stylus:

```css
[data-dd-action-name] {
    outline: 6px double lime;
}
```

I haven't found a browser extension or other tool specifically for verifying DDG actions, so perhaps we just test for the presence of the attribute? An idea

**Comment by dcloud** [comment]
Was pointed to [this doc about Datadog](https://github.com/department-of-veterans-affairs/va.gov-team/blob/main/platform/analytics/setup-real-user-monitoring.md#testing-for-exposed-content) that mentions using the Stylus browser extension, so I'm in good company and/or that may be where I learned of Stylus

**Comment by dcloud** [comment]
Added [some documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/integration-with-nav-release-plan-2024.md#datadog) to the implementation plan, mostly around testing `data-dd-action-name` attributes.

**Comment by dcloud** [comment]
For the secondary nav, we should add something like:

```
        data-dd-action-name={`MHV Secondary Nav - ${title || mobileTitle}`}
```

**Comment by dcloud** [comment]
The related PR, department-of-veterans-affairs/vets-website/pull/29609, is close, but will probably need some merge-conflict resolution after Carlos' tweaks PR gets merged. Hopefully soon

**Comment by dcloud** [comment]
Since I was in DDG today, here's a screenshot of those 2ndary nav events:

<img width="1392" alt="ddg-mhv-2ndary-nav--2024-05-22 at 11 21 08 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/279327/c6f98cfe-e770-40ff-a062-5157c6d0c0a8">
