### ISSUE TITLE
Use dedicated Redis instance for Sidekiq

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8149]
Quick notes to be replaced:

* Create a new redis instance in VAEC vpc running Redis 5
* Break off a sidekiq production worker to handle draining the existing jobs
* Configure sidekiq to use the new redis instance

Things to check
* scheduled cron jobs in sidekiq -- move them to new db? how does that work? replace with built-in sidekiq cron capabilitiy?
* sidekiq prometheus data -- check since it seems to be iffy

Related Ops Ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11980)

**Comment by johnpaulashenfelter** [comment]
After a discussion w/ @wyattwalter , looks like name is `vagov-prod-vets-api-sidekiq` for new instance of Redis as far as Terraform/etc go

**Comment by johnpaulashenfelter** [comment]
Looks like the rest of the train of Sidekiq PRs has left the station so can do some of this now :)

**Comment by johnpaulashenfelter** [comment]
Deveops first config is here using existing URLs but separating into two setting keys https://github.com/department-of-veterans-affairs/devops/pull/6868

**Comment by johnpaulashenfelter** [comment]
Reached out to devops to schedule for next week.

**Comment by johnpaulashenfelter** [comment]
Waiting for devops to get new elasticache instance in terraform

**Comment by alexpappasoddball** [comment]
Linked Ops ticket for the terraform work per the comment above in the description body
