### ISSUE TITLE
Set a build description for builds and deploys with ref value

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#815]
Elijah pointed out that we could update the description of a build rather easily, so it'd be slick to show what version a given deploy or build was based upon really quickly in the UI. I'd like to do this where possible.

This is contained in the CMS migration epic for now because it's a feature they asked for, but super useful platform-wide.

**Comment by ricetj** [comment]
@b00klegger when you get time, can you like the PR to this and then we can close.

**Comment by ricetj** [comment]
done
