### ISSUE TITLE
Post Submission - Contact Center messaging

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#81504]
After speaking with VBA and CAIA we have determined that guidance needs to be written for the Contact Center to better help the Veteran when they call about Post Submission failures. We plan to write instructions for VSRs to be able to help when a Veteran calls about the new [post submission failure email](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/78866). 

Task:

- [x] Research what type of messaging is already in use at the Contact Center (ask Team 1 about their process for updating the [product guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product/526ez%20Product%20Guide))
- [x] Draft content
- [x] Create Contact Center ticket to get their feedback
- [x] Feedback from VBA/OCTO
- [x] Under review with VEO
- [x] Finalize content and handoff to the Contact Center

Acceptance Criteria:
- [x]  VRS instructions for helping Veterans when they call about the Post Submission email
- [x]  Add additional images after testing (see comment below for details)

**Comment by juliepedtke** [comment]
[Helpful thread with Team 1 re: product guide](https://dsva.slack.com/archives/C053UDWMH7U/p1714068265100449)

**Comment by nnicholas7** [comment]
Request the Contact Center Review

Description
Please provide the name(s) of your product and a high-level description of your product.
Post-Submission Notification Email 

Launch Date
Please provide the launch or rollout date and details.
This is a quick fix for a backend failure.  We would like to rollout this product guide addition as soon as possible. 

Version Number
Please provide the version number of the guide and/or video.
This addition is a V1 addition. 

Product Guide
Please provide product guide link
Link: https://docs.google.com/document/d/1pxrSK8lJ7GoSzIDuVkCfFKlMbLqHRDnlvNBfW-u5NHs/edit

Product Video
Please provide product video link

Product Video Transcript
Please provide product video transcript link
No video included. 

Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed
- [ ]  Platform: Contact Center sends artifacts to appropriate contact centers
- [ ]  Platform: Platform Collaboration Point Tracker is updated

**Comment by juliepedtke** [comment]
@nnicholas7 Couple comments:

- I think you need to add a description not just a name. 
- For product guide, you can link the 526 product guide and explain that we're proposing an addition. We won't want to share the internal gdoc with them because it has some personal notes at the top, so we'll probably want to add it to the 526 product guide once we have Nathan and Shannon's input and provide that.

**Comment by nnicholas7** [comment]
Shannon asked that we add in an example of what the overflow text on the 526 PDF will look like and also tell them what will happen when there are too many files to display on the pdf.  Nathan explain that at the moment that can't be added.  He will have this language when testing begins. Research team will explain this to the Contact Center when we chat about the ticket.

**Comment by juliepedtke** [comment]
We can call out those additions that we'll add during testing in the CC ticket itself! I'm not sure we'll chat directly?

**Comment by nnicholas7** [comment]
To be updated soon: Mobile format makes it harder to read. This might be a reason to show actual emails instead of the Figma. Leaving it here for now until after we testing - along with adding an example of the overflow text - we'll also update the images

**Comment by nnicholas7** [comment]
Contact Center Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82085

**Comment by nnicholas7** [comment]
Contact Center Ticket Update: Content has been added to the correct template and sent to VEO for review.  We are awaiting the next steps from VEO.

**Comment by nnicholas7** [comment]
The post-submission email instructions have been submitted and accepted by VEO with no further changes. The ticket for this task is now closed. 

<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39e3d734aa0301449a6d1816ef6eec7361c2cd47/Screenshot%202024-05-13%20at%208.38.19%E2%80%AFAM.png" alt="Screenshot 2024-05-13 at 8.38.19 AM.png" />

**Comment by nnicholas7** [comment]
Don't forget to add the following:

From the ticket: 

A couple of additional notes for context:

- Our engineering team is working on implementing these emails and testing is forthcoming
- Once testing is underway we will be able to provide an example of the overflow text that will appear on the 526 PDF. 
- The character limit cutoff for file names is still TBD pending our technical solution.

We will also provide examples of the emails with the placeholder filled with mock user data (first name, file name, etc.)
We wanted to share what we have so that you can begin your review process and we will provide these additional materials as soon as possible.

**Comment by juliepedtke** [comment]
Additional note from recent conversations - there is a separate BDD product guide we should update as well. Anneliese is working on a new process for updating Product Guides via Sharepoint, so we should revisit this once we have the examples we need from testing.

**Comment by lisacapaccioli** [comment]
Waiting on Nathan. @NB28VT

**Comment by NB28VT** [comment]
@juliepedtke @nnicholas7 CC @lisacapaccioli I thought I had shared this already, but this is a screenshot of the mailer with the "X" fix to replace the "*" that were causing formatting issues. Note "_" also causes some issues (in markdown it gets interpreted as italics so you can see it is formatting some of the text that way) but unless VA Notify completely overhauls their templating system or we don't allow filenames with special characters (too much of a burden on the Veteran IMO) there is always going to be some potential for formatting issues. But using "X" instead of "*" will solve the majority of issues IMO since we are masking all of the filenames and "*" has some special meanings in markdown. Happy to explain on a call.

<img width="417" alt="Screenshot 2024-06-27 at 2 51 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8537428/f2b167a1-b7fc-4189-91d7-b8ae3a1920c2">

**Comment by juliepedtke** [comment]
For reference: eng [ticket for overflow page of PDF](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/86743) and [ticket for final mailer approvals](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/86728)

**Comment by juliepedtke** [comment]
Connected with Steven via Slack and created new tickets for the 526 and 526 BDD product guide updates. Awaiting their review and approval. 

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88765

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88767

**Comment by juliepedtke** [comment]
Received approval on both tickets. We're good to go!
