### ISSUE TITLE
ITF -- Evaluate and modify existing Rails code 

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81503]
# Overview
The 527 form needs to implement an intent to file in a way that can be re-used by other benefits groups.  The changes we make here need to easily re-usable by other teams.

## Task
- [ ] - Determine if existing ITF Rails code needs to be made more generic for multiple groups to use.  For example, is the form number a variable that is passed in?  
- [ ] Update the existing code if necessary and coordinate with those other groups.

### ITF API is working

1. As a veteran when I start the 527 form for the first time, I want to have that date recorded as my ITF date and shown the expiration date (1 year from date).
2. As a veteran when I start the 527 form and already have an existing ITF date, I want to be alerted that I already have an ITF and be shown the expiration date.
3. As a veteran when I start the 527 form and have an expired ITF date (over 1 year old), I want to be alerted that I had an expired ITF, that my ITF has been updated and shown the new expiration date (1 year from date)

### ITF API is NOT working at form start

1. As a veteran when I start the 527 form and the ITF API is not available, I want to be alerted that the service is down but we will continue to try.
2. As a veteran who did not get an ITF date established upon the start of the form due to the API service being down, I want to have that my in-progress date recorded as my ITF date.

### ITF API is NOT working at form start nor at submission

1. As a veteran who did not get an ITF date established upon the start of the form due to the API service being down and the API service is still down during submission, I want to have my in-progress date recorded as my ITF date on the generated PDF.

**Comment by aplatt-coforma** [comment]
This ticket is no longer needed
