### ISSUE TITLE
0781 Research Planning 

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#81505]
The 0781 is currently undergoing a redesign. This redesign includes additional questions and sections. We want to understand how these changes will impact the user experience.

Task:
- [x] Review the paper and digital vision of the new 0781
- [x] Identify top questions that are coming up in the redesign (eg placement of the flow, example text, VHA consent...) and brainstorm best methods for testing/researching each
- [x] Get feedback from Julie and Jina
- [x] Contribute to project roadmap to align with design process
- [x] Get feedback from Shannon, including timeline and what research happens pre- vs post-launch
- [x] Get feedback from Shannon on research plan
- [x] Draft research plan
- [x] Get feedback from Shane, Trauma-Informed CoP
- [x] Go through steps 1-2 of the [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)

Acceptance Criteria:
- [x] 0781 research plan approved by Platform

**Comment by nnicholas7** [comment]
Update
- Jina and I met to discuss the design roadmap and top questions that are coming up.  Top questions and other remarks were added to the UX Sync (Team 2) notes doc.  We also created an open questions document that will house both research and design open questions.
- After reviewing the roadmap, I noticed that concept testing was a suggestion.  I did some internal research to find out who has conducted concept research and what it is so that I could have better understanding to speak with Shannon about. 
- This is the most current version of the 0781 research plan.  We met with Shannon to discuss the research plan and roadmap to get Shannon’s thoughts. In a nutshell
    - Roadmap needs more detail. Jina will be speaking with Platform and CAIA about splitting up the work for 0781.  This will help us inform the timeline and provide better clarity. 
        - CAIA Meeting is set for May 15th
    - Research plan- Shannon’s initial thought was to do usability testing before launching the product. However, after talking to her about concept testing we decided to make this our first research plan. Shannon does want us to do a usability/discovery testing at least one month after the launch of the form. 
- I will incorporate this conversation into the research plan on Monday and plan to share the draft with you and Jina for feedback.

**Comment by juliepedtke** [comment]
Hi @nnicholas7 thanks for tracking these updates. Is there a link to the research plan document itself?

**Comment by nnicholas7** [comment]
Project Links
- Research Plan- https://docs.google.com/document/d/1CQC7nj8Wtbf-ySBy2R1c-7pmv3hltRK06lVYlhptbW4/edit- Brainstorm document- https://docs.google.com/document/d/1uCd_Z_Sd0Utbd1I88-f41gcpughxcqHdxd8Wre5Byfs/edit
- 0781 Trauma CoP Meeting Notes - https://docs.google.com/document/d/1hlfZduVl_1ktmjx8BJfLJiHYmiX0MLoX3hC4cDXgFcs/edit
- Meeting with Karen Cutright- https://docs.google.com/document/d/1ATf1hp5JyjUVz5U6BlPey_PPEchruzs3vw0yC_1iCas/edit

**Comment by nnicholas7** [comment]
This past week we have had many conversation with stakeholders (OCTO and members of the Trauma-informed group) to discuss design and the research plan.  There were a lot of good takeaways from Karen Cutright on recruitment and how past MST projects have been conduct (see Meeting with Karen Cutright document above).

From our conversation with Shannon we have gotten more clarity on the research plan.
- For concept testing, we'll focus on folks who have previously filed claims for related conditions. Recruit for a mix of all possible condition types (we should list them explicitly, as we'd like Perigean to show to Veterans). Remember that MST is not a condition, and be sensitive to this in phrasing.
- For future usability testing after launch, we'll consider shadowing methodology and recruiting first-time users.
4:21
What we still need to think through:
- What's the exact list of conditions we want to ask folks if they've claimed? See threads with CC team for context, we likely won't have an exhaustive list and we'll want to use plain language
- We could think about recruiting outside of Perigean, but we'd need to figure out what our approach would be. Are there VA partners or stakeholders who might have contacts?
- We could push Perigean to let us be more involved in creative ways (eg could they have us join the screening calls, but hide the Veterans number?)

**Comment by nnicholas7** [comment]
Update: the 1st draft of the research plan was submitted to Shannon, Evelyn, Rachel and Karen (trauma-informed group) for feedback and review.  Looking to get feedback from them and incoporate it next week. 

Draft Research Plan: https://docs.google.com/document/d/1CQC7nj8Wtbf-ySBy2R1c-7pmv3hltRK06lVYlhptbW4/edit

**Comment by nnicholas7** [comment]
Update before upcoming ooo:
Research Plan
The content for the research plan is complete.  There are a few outstanding items that need to be addressed by Shannon
- Approval from Shannon on research question Goal 2. Shannons initial issues was how the goal was written which has been addressed.
- Keeping question 6 of the screener questions.  This question is a way of give a heads up to our participants about the research study
- For Rachel: Understanding her availability to be with us on the interviews.  This question has not been as yet, but is on the agenda for the next 0781 Research meeting.  

Discussion Guide
- There are open comments on the Mural board (in blue sticky) to be addressed by Jana. These questions are regarding design. Julie will meet with Jina next week to chat and get her perspective.

Perigean Agenda
- Added agenda items to be asked at the Perigean recruitment meeting.  These questions will hopefully give us answers to how involved we can be in the recruitment process

Trauma Informed Guidelines
- Add comments to this document to help inform our own research process. Next step would be to pull together our own process that fits this study

**Comment by nnicholas7** [comment]
Summarize notes from live conversations:

To Do- Nichole 
- [ ] Watch the video from Jina (use this as a map for conversation guide 
- [ ] Create the notetaking template in Mural with all the screens
- [ ] Review and complete the V2 conversation guide

To Do- Julie
- [ ] Updated the V1 Conversation Guide
- [ ] Update the V1 Note taking template
- [ ] Update the research plan

To Do- Both
- [ ] Attend the meeting with CAIA to review recommendations 
- [ ] Sync after the above items are complete
- [ ] Submit to Platform for review  (Start with Shannon)

Plan to share with Shannon by Tuesday EOD

**Comment by nnicholas7** [comment]
We have submitted the research plan and conversation guide A & B to  the Platform team as well as made a request for recruitment.

- [Platform Ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/580)
- [Recruitment Ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/579)

All research materials are now on GitHub and can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2024-06%200781%20Research)

We are awaiting feedback from the Platform Team and Perigean. In the meantime, we will work on the to-do below and create a plan for synthesis.

Next Steps
- [ ] Finalize questions for the recruitment conversation with Perigean
- [ ] Review feedback from CAIA in Figma
- [ ] Review Trauma-informed checklist and determine what needs to be done before the study
- [ ] Draft questions for Rachael
