### ISSUE TITLE
Run Sidekiq admin in production

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8151]
With all the upcoming sidekiq/redis changes, ready access to Sidekiq admin in production is pretty crucial. What's the best way to enable, access, and secure?

**Comment by johnpaulashenfelter** [comment]
Talked to @wyattwalter and current plan to quickly roll out securely

* Run it on worker nodes instead of Rails instances
* Use a non-traditional port (default 9292 for puma likely is ok)
* Add basic authentication (store info in credstash)

This should let us access it through the SOCKS proxy on individual worker machines using the internal IP address with a non-standard port and some level of authentication

The ops team is going to need to add a firewall rule for access through the SOCKS proxy, but otherwise this should be mostly handled by be-tools

**Comment by johnpaulashenfelter** [comment]
```
$ credstash list | grep plat.prod.sidek
plat.prod.sidekiq_password                                -- version 0000000000000000001 -- comment
plat.prod.sidekiq_username                                -- version 0000000000000000001 -- comment
```

**Comment by omgitsbillryan** [comment]
There's a lot of PII that the sidekiq admin UI esposes:

![image](https://user-images.githubusercontent.com/3077884/79898112-b02af000-83d8-11ea-8999-8a38f43964b6.png)


I think the only thing we really want are the metrics, [which we already have](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8173#issuecomment-616739908). We could even be obtain metrics [using the rails console while ssm'd into a prod worker EC2 instance](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8173#issuecomment-617248495).

That said, the admin UI would also give us what we need, I just think it's maybe _more_ than we need and not worth the headache to set it up.

**Comment by johnpaulashenfelter** [comment]
@omgitsbillryan as we discussed offline, during these migrations I actually want to see the details of the jobs, not metrics. _For the purposes of the various migrations_ this seems to be on ok tradeoff of access.

Everything to set it up is already done with the exception of a firewall rule https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8189

I would *love* to use the encryption capabilities of Sidekiq Enterprise to deal with the meat of your comment -- i think that's a win for *everyone*

**Comment by omgitsbillryan** [comment]
@johnpaulashenfelter It's important to keep technical discussions public (despite us having also chatted offline), so apologies that you've had to hear this from me twice 😄 .

> I would love to use the encryption capabilities of Sidekiq Enterprise to deal with the meat of your comment -- i think that's a win for everyone

I don't understand this comment - which encryption capability are you talking about & how would we use it? Also you say you'd love to see it, does that mean it will be future work or work that will happen up front before we expose the prod sidekiq ui?

**Comment by johnpaulashenfelter** [comment]
@omgitsbillryan https://github.com/mperham/sidekiq/wiki/Ent-Encryption

Using the encrypt is a future todo. Honestly thought this was the core reason we had Enterprise but apparently we have it for `unique_for` looking at the code. Upside is this protects both in Redis and in corresponding logs as well since the important things are encrypted (eg PII). 

SidekiqUI exposure right now is no more than the risk as the PII in our database log (`PersonalInformationLog`), not that its not a concern, but its on par with current decisions we've already made.

**Comment by johnpaulashenfelter** [comment]
Still not completely getting the UI to render properly (css, js issues)

```aws ssm start-session --target <INSTANCE_ID> --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["3004"],"localPortNumber":["3004"]}'
```

```SIDEKIQ_USERNAME=foo SIDEKIQ_PASSWORD=bar bundle exec rackup sidekiq-admin.ru -d -p 3000 -o 0.0.0.0```

Both of these are useful, the first for mapping the port to a local port and the second for running the app

**Comment by johnpaulashenfelter** [comment]
A bit at a loss -- looks like Redis connection is timing out. Using

`SIDEKIQ_USERNAME=foo SIDEKIQ_PASSWORD=bar  bundle exec rackup sidekiq-admin.ru -o 0.0.0.0 -p 3000 -d -s webrick`

and 

```
require 'sidekiq'
require 'sidekiq-pro'
require 'sidekiq-scheduler/web'
require 'sidekiq/pro/web'

Sidekiq.configure_client do |config|
	config.redis = { :url => 'REDACTED', :size => 1, :id => nil }
end
  Sidekiq::Web.use Rack::Session::Cookie, key: 'sidekiq.session', secret: ENV['SIDEKIQ_USERNAME']
    Sidekiq::Web.use Rack::Protection, use: :authenticity_token

Sidekiq::Web.class_eval do
	  use Rack::Protection, :except => :http_origin
end
Sidekiq::Web.set :sessions, false
map '/sidekiq' do
	  use Rack::Auth::Basic, "Protected Area" do |username, password|
		      Rack::Utils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"]))
&
			            Rack::Utils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ
_PASSWORD"]))
		        end

	    run Sidekiq::Web
end
```

which is all the extra things to make the admin UI behave

**Comment by johnpaulashenfelter** [comment]
Turns out that even without ANY security/etc the browser times out trying to serve js and css files, just spinning until EOF/timeout. Tried with puma and webrick. Tried with and without security. Works great locally and in docker

**Comment by johnpaulashenfelter** [comment]
I’ve hit a wall trying to get access to a web app running on our staging docker containers for vets-api. TL;DR I can start the container, know how to map the docker-to-host ports (3004 ftw), and even have the port forwarding working through SSM. I get the HTTP basic auth prompt as expected, I get the title of the page, and then no CSS, no JS, and a blank page. Tried a *lot* of alternatives and clearly i’m getting to the server, but css and js are always (pending) in web console until a timeout hits, then i see the EOF in the web server (or equiv — i’ve tried both webrick and puma). So it seems like something is stopping CSS/JS files in the staging env? I know we have a revproxy for public facing things but didn’t think i’d need it when i’m using SSM port mapping to connect to a host… is this a @Taylor Skinner thing? someone else? Let’s talk tomorrow

**Comment by johnpaulashenfelter** [comment]
Turns out there's some socket blocking (likely because redis is already connected to sidekiq on workers?) but in any case if you just _wait a long time_ on the order of 3-5 minutes, it will load.

**Comment by johnpaulashenfelter** [comment]
Some of the blocking errors

```
Exception `IO::EINPROGRESSWaitWritable' at /usr/local/lib/ruby/2.6.0/socket.rb:1213 - Operation now in progress - connect(2) would block
Exception `IO::EAGAINWaitReadable' at /usr/local/lib/ruby/2.6.0/socket.rb:452 - Resource temporarily unavailable - read would block
Exception `IO::EAGAINWaitReadable' at /usr/local/lib/ruby/2.6.0/socket.rb:452 - Resource temporarily unavailable - read would block
```
