### ISSUE TITLE
[Certs] Update Certificates

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#81511]
- [x] /ssl/dev-design.va.gov-2024.crt expires: 2024-05-29
- [x] /ssl/dev-design.va.gov.chained-2024.crt expires: 2024-05-29
- [x] /ssl/staging-design.va.gov-2024.crt expires: 2024-05-29
- [x] /ssl/staging-design.va.gov.chained-2024.crt expires: 2024-05-29
- [x] :warning: /ssl/dev-developer.va.gov-2024.crt expires: 2024-05-25
- [x] :warning: /ssl/dev-developer.va.gov.chained-2024.crt expires: 2024-05-25
- [x] :warning: /ssl/developer.va.gov-2024.crt expires: 2024-05-25
- [x] :warning: /ssl/developer.va.gov.chained-2024.crt expires: 2024-05-25
- [x] :warning: /ssl/staging-developer.va.gov-2024.crt expires: 2024-05-25
- [x] :warning: /ssl/staging-developer.va.gov.chained-2024.crt expires: 2024-05-25
- [x] /ansible/deployment/config/fwdproxy/vaausvrsweb40.aac.va.gov.pem expires: 2024-05-25
- [x] /ansible/deployment/config/fwdproxy/vaausvrsweb20.aac.va.gov.pem expires: 2024-05-25
- [x] /ansible/deployment/config/fwdproxy/vaausvrsapp81.aac.va.gov.pem expires: 2024-05-24
- [x] /ansible/deployment/config/fwdproxy/api-gateway-lgy-dev-cert.pem expires: 2024-05-17
- [x] /ansible/deployment/config/fwdproxy/api-gateway-lgy-prod-cert.pem expires: 2024-05-17

**Comment by npeterson54** [comment]
This was added to the sprint due to upcoming deadlines for these certificates

**Comment by ph-One** [comment]
- dev-design.va.gov deployed to TIC
- waiting for staging-design.va.gov to be deployed to TIC

**Comment by ph-One** [comment]
:warning: Certificates have been deployed to {dev,staging,prod} reverse proxy as well as all AWS resources. I will communicate to Lighthouse a sample of the INC ticket that they will need to submit to have the TIC updated. Our teams work has been completed. Closing.
