### ISSUE TITLE
Design Intent - IA Feedback - BAH-MBS-SelfServ, Pre-Need Self Service, Pre-Need Address Validation

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#81517]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through the collaboration cycle! 
- There are a few other teams working on address forms - namely the Forms team. @jeana-adhoc might be a good contact if you want to talk about address patterns more broadly.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- [x] **Ask about military base address** If possible please follow the [address pattern](https://design.va.gov/patterns/ask-users-for/addresses) that asks users whether they're on a military base. The Forms team is currently working on this pattern and might have some ideas for you. I recommend reaching out to @jeana-adhoc for more info.
- [x] **Skip step in user flow where form is displayed again after address validation** I agree with Design feedback that this step is redundant and could be confusing.
- [x] **Improve flow for "no recommendations"**: The current [no recommendations available](https://www.figma.com/file/6ZBtsZJt7Llx1jA5rR8T83/Pre-Need---Address-Validation-Prototype?type=design&node-id=1024-17034&mode=design&t=t3SjzZ7Hxa6b89m7-4) screen has a radio button for an empty action ("No recommendations available.") This flow should be redesigned to ask, "we couldn't find this address, please verify this is correct."

### Should

- [x] **Required indicator and error message to address validation** The screens where users are selecting the correct address should indicate that this is a required field. Validation/error messages should be included for when users don't select one of the radio buttons.

### Consider

- [x] **Change tone/alert type for successful address matches** Instead of a yellow warning/error alert when a matching address is found, what if we showed users a success alert? Instead of "We can't confirm the address you entered with the Postal Service" how might the experience be improved (and users nudged toward accepting the new address) using a green alert that says something like, "We found a match for your address with the USPS. Should we use it?"

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by barron-charles** [comment]
**In terms of this one:** Ask about military base address If possible please follow the [address pattern](https://design.va.gov/patterns/ask-users-for/addresses) that asks users whether they're on a military base. The Forms team is currently working on this pattern and might have some ideas for you. I recommend reaching out to @jeana-adhoc for more info. We have a plan in place to speak to our stakeholders in more detail and will have a better feel with feasibility at that time.

**Comment by barron-charles** [comment]
Change tone/alert type for successful address matches Instead of a yellow warning/error alert when a matching address is found, what if we showed users a success alert? Instead of "We can't confirm the address you entered with the Postal Service" how might the experience be improved (and users nudged toward accepting the new address) using a green alert that says something like, "We found a match for your address with the USPS. Should we use it?"

I think it's a great suggestion and added it in there mockups and prototype.

**Comment by barron-charles** [comment]
@erinrwhite Our team was discussing the military base address in a bit more detail. Changing the military address to this pattern would require work by VBA automation to train their bots on the MBMS side to have fields for the information to go to. This would really make it significantly more complex, especially when looking at who would be applying for benefits. It also could be more of a use case with who is applying for benefits with this form with preparers and family members alongside Veterans.

**Comment by erinrwhite** [comment]
@barron-charles understood. Thanks for looking into it!
