### ISSUE TITLE
[Certs] Update Certificates

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#81513]
⚠️ The following are managed by LH and am waiting for them to submit a PR

developer.va.gov
staging-developer.va.gov
dev-developer.va.gov

___________________________________________________________________________

 /ssl/dev-design.va.gov-2024.crt expires: 2024-05-29
 /ssl/dev-design.va.gov.chained-2024.crt expires: 2024-05-29
 /ssl/staging-design.va.gov-2024.crt expires: 2024-05-29
 /ssl/staging-design.va.gov.chained-2024.crt expires: 2024-05-29
 ⚠️ /ssl/dev-developer.va.gov-2024.crt expires: 2024-05-25
 ⚠️ /ssl/dev-developer.va.gov.chained-2024.crt expires: 2024-05-25
 ⚠️ /ssl/developer.va.gov-2024.crt expires: 2024-05-25
 ⚠️ /ssl/developer.va.gov.chained-2024.crt expires: 2024-05-25
 ⚠️ /ssl/staging-developer.va.gov-2024.crt expires: 2024-05-25
 ⚠️ /ssl/staging-developer.va.gov.chained-2024.crt expires: 2024-05-25

**Comment by mramirez-va** [comment]
Resolved by https://github.com/department-of-veterans-affairs/devops/pull/14291
