### ISSUE TITLE
Adding Jessica Sanders to DSVA Slack

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#81524]
# Adding Jessica Sanders to DSVA Slack

- Please add jessica.sanders5@va.gov as a full member.

Are you requesting to add an individual as a:

- Full member X
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Jessica Sanders is a new hire for GovCIO who will be supporting the OCTO Contract/Acquisition Team under Josh Cohen.  

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by KevinMHoffmanUSDS** [comment]
Done
