### ISSUE TITLE
BE | Auth Exp | Identify and log outdated swagger docs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#81543]
## Background
Identify My VA and Profile endpoints that are incorrectly documented.

## Tasks
- [ ] identify endpoints that are incorrectly documented.

## Acceptance Criteria
- [ ] create a ticket for each endpoint that requires updates/fixes.

**Comment by ajakabcin** [comment]
@tpharrison and @DanielMiller-agile6 - do you mind if we separate this out into a ticket for profile endpoints and my va endpoints? that way they can show up on both of our boards (mine wont' show anything with the profile label)
