### ISSUE TITLE
Details Page: Don't Show Labels when Data is Not Available

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#81541]
## Background
The Appt & CIE teams decided that we should follow this pattern on appointment details pages when the following data is absent:
- If Provider value is null, blank, or otherwise not available
    - Do NOT display any label
    - DO NOT display a default value
- DO NOT display any value or label for Type of Care

## Tasks
- [FE] Make the changes above or confirm we are already doing this

**Comment by brianseek** [comment]
@benbrasso-agile6 / @loripusey This is merged and ready for validation. Also see [screenshots here](https://github.com/department-of-veterans-affairs/vets-website/pull/29593)

**Comment by loripusey** [comment]
Looks good, closing
