### ISSUE TITLE
VAMC: Missing stories/events

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8155]
## What happened?
Stories and Events blocks are not displayed on the VA Pittsburgh health care home page. This content previously appeared between "In the spotlight at VA Pittsburgh health care" and "Get updates from VA Pittsburgh health care" 

## Specs:
- Not browser specific

## Steps to Reproduce
- URL: https://www.va.gov/pittsburgh-health-care/
- Scroll toward bottom of page. Observe stories and events do not appear between blue "In the spotlight at VA Pittsburgh health care" and gray "Get updates from VA Pittsburgh health care" boxes. 

## Desired behavior
Stories and events appear on VA Pittsburgh health care home page, as before: 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/00364a75-8fb0-4cf7-aaa8-43dca98d0cce)

## Acceptance Criteria
- [ ] Veterans can view Stories and events on VA Pittsburgh health care home page. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12327
