### ISSUE TITLE
Investigate 422 scenarios

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81576]
### Background

From https://github.com/department-of-veterans-affairs/va.gov-team/issues/81342

We were able to validate that we're showing an error as expected, however we began to wonder why users would give us a `422` from Lighthouse.

This ticket is to investigate when/why Lighthouse would throw a `422`

**Comment by jvcAdHoc** [comment]
We're getting a 422 inside LH from [this line here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/controllers/concerns/claims_api/target_veteran.rb#L37) for `vets.gov.user+2@gmail.com ` and `vets.gov.user+5@gmail.com `.

That means we're able to find the test user ICN in MPI (not hitting the 404), but the response we get back from MPI does not contain a `participant_id` and that triggers the 422.

I'm pretty sure this is a mock data issue and will ask LH more about that.

BGS is able to return POA codes for both users when called directly outside of the acitve POA controller code path.

**Comment by jvcAdHoc** [comment]
Talked with Team Dash who has more experience with mock MPI data. It's an issue with the mock data. V2 of the LH endpoints use ICN to lookup profiles in MPI. Some the profiles of our test users do not contain participant ids in them despite the users actually having participant ids.

- example for `vets.gov.user+2@gmail.com` getting 422:

  [mock data](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/2202df9db6259d871ba56ca1210f1a996041eebb/mvi/profile_icn/1013174704V087163.yml#L39) does not contain an element with `USVBA^A` nor does it have a `profile.yml` file.

- example for `vets.gov.user+211@gmail.com` not getting an error from LH:
  [mock data](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/2202df9db6259d871ba56ca1210f1a996041eebb/mvi/profile_icn/1012845699V670513.yml) references a `profile.yml`

  that [profile](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/2202df9db6259d871ba56ca1210f1a996041eebb/mvi/profile/796098273.yml#L41)  does in fact have the participant id

**Comment by oddball-lindsay** [comment]
Got it, thanks @jvcAdHoc !  I'm asking that these users not be touched for now so we can at least have some users to trigger an error state for Staging Review.

But very helpful in understanding how to best create test users for our Rep Status Widget!  cc @holdenhinkle as this may be important for your test user discussion tomorrow.
