### ISSUE TITLE
Tools page still mentions Sketch

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/va.gov-team#81571]
### Description

This [page still mentions how to get access to sketch](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools), and I think it should be updated to mention Figma instead. ([Figma instructions are here](https://depo-platform-documentation.scrollhelp.site/research-design/figma-accounts-at-va))

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS - veteran facing forms

**Comment by jknipes** [comment]
@jeana-adhoc thank you for submitting this request. We are having trouble locating references to Sketch on that page. Could you please provide a screen shot?

**Comment by jeana-adhoc** [comment]
You're correct - I'm not seeing any mention of Sketch on this page. I think this can be closed. Sorry about that.

**Comment by jknipes** [comment]
Issue has been resolved, moving ticket to _Done_
