### ISSUE TITLE
[FE] 10-10CG - Improvements: Family Member Hub - Duplicate entry & any other cleanup

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#81588]
## Background
We received the message below from Mikki Northuis regarding an update to the PCAFC pages:
>In mid-June, we will be rolling out some revisions to the family member benefits hub.  These changes will impact the current placement and URLs of the PCAFC form and its corresponding static content page.  The CAIA team will be responsible for shifting the static page and implementing appropriate redirects, but we of course need your team's assistance in updating the URL of the form flow, the form's breadcrumb, and coordinating a redirect for it.  This does not need to happen at the exact same time, but we will want it to happen as close as possible so the form correctly reflects where the visitor is in the site. 

This ticket is for any content & remaining cleanup from the PCAFC Family Member hub URL redirect

#### References
- [URL Standards in the Content Style Guide](https://design.va.gov/content-style-guide/url-standards)
- [Family Member Hub - IA Design Doc with new URLs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md)
- [PCAFC CAIA Migration ticket](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/26?pane=issue&itemId=60389225)

## Tasks
- [x] Remove duplicate entry on content (cleanup)

## Acceptance Criteria
- Any remaining content cleanup is completed

**Comment by jessicastump** [comment]
There is one link on the introduction page that was impacted by these new urls. In step 2, the link "Learn more about the documents you can submit" should now be: 
_https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/_
