### ISSUE TITLE
Create a future state document for MVP features

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#81580]
## AC

- [x] add user flows from Sprints 44 and 45
- [x] have a draft ready (for Sprint 44 flows) by Tuesday 4/30
- [x] Write it out and then have @SophiaPhilipMO and @schisslerg review

**Comment by skirkman16** [comment]
Created a future state document that lives on [Google docs](https://docs.google.com/document/d/1B6F6t6vNchgGsyyTSWGvUNwtv5tcXBgNkKCPHW04cLc/edit) and [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/design/Future%20State%20document.md).

The first draft of this document captures the context, purpose, and user flows from Sprint 44.  It is ready to be reviewed by @SophiaPhilipMO and @schisslerg, but they are aware that the doc will continue to be iterated on over the next week as we present our flows back to the team for feedback

**Comment by SophiaPhilipMO** [comment]
@skirkman16 reviewed and comments left

**Comment by skirkman16** [comment]
First draft of this doc is done so this ticket can be closed. Google doc and Github has been updated. Next step is to plan with @schisslerg how to frame this document in relation to other documents that will help provide context and future considerations to our PO and future contributors.
