### ISSUE TITLE
SOCKS access for Jacob Bapple

### ISSUE THREAD

**Issue by JakeBapple** [department-of-veterans-affairs/va.gov-team#81591]
### Your Name

Jake Bapple

### Your Email

jbapple@metrostar.com

### Your GitHub Handle

JakeBapple

### Your Role and Team

Developer CMS Team

### Product Manager (PM) name and email

Grace Kretschmer mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLQdRJ1GK4dpm4YNxPkPZkGS+ub4A4T3t1jZBVhCwxxvQ/yy45EWb1ZgXRCbL8e/69VBVmGnqf9ta6TOP9QbqzWEtUlH1Y3JqZXMnlAXG5teLiYvISSIWepXzJbbWoOGHbquxNrlhQQYlAyseMh3wV5KGMC9As2ZO/vxhy7A7l5/f0NrclticSpk3cPXSaZg/xixgJ+frOppTxMhot9suQsWgn0EKTUa3hvv3qNN3JS9CzlX8VGe5JWEBBKHQfxDXKb+2376vIPG8CrbSYdangdden4EYaFPrm42dLnos7BQGEoXFfCIcsJwcwJqkMaALg2gB9P4MHQ4QRSCUjdaWL6Lr6VoDjT9vcqB1XkulRlazz5tnRkgkz/b0xBKIMSVY4prvUekK1qWdhOeZ5R5OwR9h1E4BPIkcQwe+PeyPEuEH8p+AIhr2CxvPRIzlSn2zO/sTHjHwCQy5DJNfyAJ4Uc3prNzB3w6QhChIfDyVP7UaOILz2aCj7+RtNsf4e8GXlAK5a1Sg/69I7C9sZyrrxWOi8SG7sopmw67KdH9zlcmJMqlX6CIDnMkrPjyF5HPZ7WdI2xxOKtYZyN9VnIsrjdDXQLUt2zvAzioTTkX1HqE7OIYryLx8O/lslib3Dq7chbPyzDCZvtqsjZrCXf+hfWd8QeJLKmyYiMBvweibBUQ== jbapple@ITLP01122.attlocal.net

### E-QIP Transmittal Confirmation

![Screenshot 2024-04-24 at 2 15 11 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/166155028/dd96afc5-9632-413f-b65a-428a9f7367d4)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by michelle-dooley** [comment]
@va-vsp-bot @JakeBapple is on Platform team and is on the Platform team roster. 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/f57139a2-4b10-4c07-bebe-36810785faa6)
