### ISSUE TITLE
Site maintenance for authentication for My VA Health portal from OCTO-Identity

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#81603]
# Public Websites Banner Intake Request Form

## Description
We need a downtime banner as the Identity team will be doing some work for authentication for the My VA Health portal (see [ticket for downtime copy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81353#issuecomment-2075211174))

## What do you need?

Choose one of the following and make sure you fill out at least the required details for it.
  
- [x] Maintenance Banner
  **Required Details:**
  - `startsAt`: `2024-04-25T21:00:00`
  - `expiresAt`: 1 hour
  - `title`: `Site maintenance`
  - `content`:

> **Normal content
> We’ll be doing some work on the sign in experience for the My VA Health portal. The maintenance will last about 1 hour.
>
> If you use the My VA Health portal, you won’t be able to sign in to the portal during this time. You can always contact your local VA medical center for health care needs. [Find your local VA medical center](https://www.va.gov/find-locations/)
>

```jsx
// above content in code
<>
  <p>
     We’ll be doing some work on the sign in experience for the My VA Health portal. The maintenance will last about 1 hour.
  </p>
  <p>
    If you use the My VA Health portal, you won’t be able to sign in to the portal during this time. You can always contact your local VA medical center for health care needs.{' '}<a href="/find-locations">Find your local VA medical center</a>
   </p>
</>
```
 
  __Optional Details:__
  - `warning startsAt`: `immediately`
  - `warning title`: `Upcoming site maintenance`
  - `warning content`: 
```jsx
<>
  <p>
     We’ll be doing some work on the sign in experience for the My VA Health portal. The maintenance will last about 1 hour.
  </p>
  <p>
    If you use the My VA Health portal, you won’t be able to sign in to the portal during this time. You can always contact your local VA medical center for health care needs.{' '}<a href="/find-locations">Find your local VA medical center</a>
   </p>
</>
```

## Stakeholders

- @department-of-veterans-affairs/octo-identity 
- @asg5704 
- @joeniquette 
- @Samara-Strauss

**Comment by asg5704** [comment]
![Screenshot 2024-04-24 at 4 13 12 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/67602137/641d3694-c780-406c-b738-9a90e64883b5)

Should look like this ☝️ (content is the same for upcoming & during site maintenance)

**Comment by Samara-Strauss** [comment]
Closing in favor of #81630
