### ISSUE TITLE
Design | Profile | Maintenance | Fix behaviors in contact information user flow

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81613]
## Background
Somehow the numbers notating behaviors have been removed from the annotations and everything just says `B` so it's hard to map it to the documentation. We need to clean this up.

## Tasks

- [ ] Go through the contact information Figma file and clean up the behavior notatations

## AC

- [ ] The Figma file is correctly annotated with behaviors

**Comment by andaleliz** [comment]
@mtcA6 I'm going to add this to the current sprint and close it out tomorrow.

**Comment by mtcA6** [comment]
@andaleliz sounds good. Could you add the sprint epic and sprint moving forward?

**Comment by andaleliz** [comment]
Sure thing!  This is complete.
