### ISSUE TITLE
Toxic Exposure - test submission of a claim from va.gov to VBMS

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#81611]
As the chosen one (a va.gov staging user) I can fill out the form 526ez with toxic exposure conditions, submit the claim, and a VSR can see the claim established in VBMS and see the 2022 526 generated pdf in my eFolder.

Because we don't have Lighthouse sync claim id coming back synchronously, we can fake this, but in order for it to come back successfully we can give it a fake claim id to move the process along.

Open questions & considerations:
1. Will a fake/synthetic claim id work? The doc upload endpoint requires a claim id - stakeholders understand that the "claim id" coming back and displayed to the user will not match a claim id in VBMS for now, not until the Lighthouse "sync" submit endpoint is ready.
2. ancillary forms will fail because it doesn't have the right claim ID - let's not fill out any ancillary forms for this testing
 
Tasks:
- [x] [vets-api] save the response the Lighthouse "async" endpoint "id" attribute as the claim_id for a `Form526Submission` for now - this will be displayed in the front end when the chosen one hits "submit"
- [x] [vets-api] ensure we are calling LH's staging environment - without it, we will not trigger the jobs that will generate the PDF and establish the claim
- [x] enable flipper flag for "the chosen one" at [staging.flipper](https://staging-api.va.gov/flipper), `disability_compensation_lighthouse_submit_migration`.
- [x] test!!! includes manually checking VBMS. question: does the claim status tool show this progress?
- [x] [vets-api][optional] add checking the status of a claim to the test harness for easier checking 

Acceptance Criteria:
- [x] manual check in VBMS
- [x] the claim ID is visible in VBMS
- [x] the pdf is in VBMS (staging env)
- [x] 15a is checked in the pdf
- [x] column 2 is populated with conditions
- [x] the submission has created an End Product (EP) in VBMS

**Comment by aurora-a-k-a-lightning** [comment]
# SUCCESS
1. staging.va.gov: filled out form with user "54" jesse "gray"
2. filled out Toxic Exposure sections with new "anemia" disability
3. hit "submit" from staging.va.gov
4. success. got a "synthetic" claim_id back from submit_all_claim endpoint
5. checked VBMS for new claim; they were there! (seth to provide PDFS)
6. checked with lighthouse benefit_claims#get_claim endpoint to get individual claim. EP code established, etc. (see below)

## sample lighthouse benefits_claims#get_claim call
```
 @service.get_claim("e9dab15b-9df2-4edc-88ce-c95110952ba9")
=> 
{"data"=>
  {"id"=>"600501880",
   "type"=>"claim",
   "attributes"=>
    {"claimTypeCode"=>"400SUPP",
     "claimDate"=>"2024-05-06",
     "claimPhaseDates"=>{"phaseChangeDate"=>"2024-05-06", "currentPhaseBack"=>false, "latestPhaseType"=>"CLAIM_RECEIVED", "previousPhases"=>{}},
     "claimType"=>"Compensation",
     "closeDate"=>nil,
     "contentions"=>[],
     "decisionLetterSent"=>false,
     "developmentLetterSent"=>false,
     "documentsNeeded"=>false,
     "endProductCode"=>"403",
     "evidenceWaiverSubmitted5103"=>false,
     "errors"=>[],
     "jurisdiction"=>"National Work Queue",
     "lighthouseId"=>"e9dab15b-9df2-4edc-88ce-c95110952ba9",
     "maxEstClaimDate"=>nil,
     "minEstClaimDate"=>nil,
     "status"=>"CLAIM_RECEIVED",
     "submitterApplicationCode"=>"VBMS",
     "submitterRoleCode"=>"VBA",
     "supportingDocuments"=>[],
     "tempJurisdiction"=>"St. Petersburg",
     "trackedItems"=>[]}}}
```

**Comment by sethdarragile6** [comment]
2 PDFs generated during testing attached, each with 15a checked and column 2 pop'd. claim ID found in VBMS
<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3U2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b69fcad5c7bc57f636ec2e1286f2d8419f9505c1/image.png" alt="image.png" />

[jesse grey LH 2024-05-06 (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3E2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74a194fb69dc083d85391bab79d42a689e803759/jesse%20grey%20LH%202024-05-06%20%281%29.pdf)
[jesse grey LH 2024-05-06 (2).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3k2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51571e6fbef4568442dad0cd6e272649d65cd4cd/jesse%20grey%20LH%202024-05-06%20%282%29.pdf)
