### ISSUE TITLE
Audit Design System for Accessibility

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#8161]
As a developer/designer on a VFS team, I want all the components and designs in the design system to be accessible so veterans can easily use the new features my team is building.

AC:
- [ ] Create an excel doc to track audit (https://docs.google.com/spreadsheets/d/1CcgJyKp1RZjCC09r8jElw3_ovIrvo24i7RTSiS6OtBU/edit#gid=1115838130)
- [ ] Audit all designs/components in design system or the accessibility criteria

**Comment by 1Copenut** [comment]
This work has been finished. Moving this to close.
