### ISSUE TITLE
Figure out best way to audit for consistency across design and dev resources

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#8162]
As a VFS team member, I want everything across design system to be consistent so I can use any components knowing they are the most updated design. 

AC:
- [x] Figure out how to best track the audit
- [x] Figure out how to best execute audit

**Comment by pjhill** [comment]
Did some solo thinking about this here: https://docs.google.com/document/d/1t5PlnMJqH9L8GRTIOQizS4fACNfW8qgLRW-8VDhyw3Y/edit?usp=sharing

Met with Dan and Crystabel and took notes in the same document here: https://docs.google.com/document/d/1t5PlnMJqH9L8GRTIOQizS4fACNfW8qgLRW-8VDhyw3Y/edit?usp=sharing

**Comment by pjhill** [comment]
Created a Trello Kanban board to try to manage these tasks -- https://trello.com/b/YkpizI34/audit-design-components

**Comment by pjhill** [comment]
To do -- Create a checklist for how to audit each design component

**Comment by pjhill** [comment]
Proposed checklist -- 

- [ ] Acceptance criteria (requirements, input/output, attributes, behavior)
- [ ] Evaluate ease of use (code complexity, reusability, common patterns) (Subjective scale of 1-5)
- [ ] Recommendation for sync
-- Scan for visual differences
-- Evaluating which system is out of sync
-- Evaluating level of effort required to sync a system
-- Make a recommendation for which systems to update

**Comment by pjhill** [comment]
Proposed audit procedure -- 

1. Create a ticket for each component in Trello
2. Schedule audit sessions with team (1 - 2 hour blocks every other day)
3. Grab a component ticket from Kanban board and run through checklist
4. Move ticket to completed with completed checklist including comments for recommendations
5. Export work from Trello into ZenHub for incorporation into Product Support backlog
