### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by wafimohamed** [department-of-veterans-affairs/va.gov-team#81635]
### Your Name

Wafi Mohamed

### Your GitHub handle (Flipper UI access is managed through GitHub)

@wafimohamed

### Team, Role, and Company of the target individual

verify your enrollment team / vye_team/frontend developer/GovCio

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
Verified in Atlas
E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78024)

**Comment by bdech** [comment]
@wafimohamed You've been granted access to `production` and `lower` environments.
