### ISSUE TITLE
IPP - Implement content and design changes into Proofing Agent Screens

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#81658]
Context: Post PA UT, the design team made changes to Proofing Agent screens based on research insights. Design team removed accordions, updated content, and added formatting to "Fill in information" form. 

[Go to page "Post PA UT Prototype 4/25/24" on Figma](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=3609%3A20846&mode=design&t=KpFaH8FtNxLJZuqT-1) 

## AC

# Enter Confirmation Case Number 
<img width="1171" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXJQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f825a2bde8d569129ae2766a3fda3db8b29a5141/Screenshot%202024-05-10%20at%208.59.23%20AM.png" alt="Screenshot 2024-05-10 at 8.59.23 AM.png" />

- [x] change case number to confirmation case number
- [x] change case number to confirmation case number over input box
- [x] implement content changes on page 10 of [content doc](https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit)

# Confirm applicant email
<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm5MQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3173c28fcb442afd41f8bb3f1cf0e6b965e2c7bf/Screenshot%202024-05-09%20at%2011.10.52%20AM.png" alt="Screenshot 2024-05-09 at 11.10.52 AM.png" />

- [x] implement content changes on page 11 of [content doc](https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit)

# Validate ID
<img width="507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ab91c622504d4917ed0e9ae3a9cd0f7b704a6f3/Screenshot%202024-05-09%20at%203.40.57%20PM.png" alt="Screenshot 2024-05-09 at 3.40.57 PM.png" />

- [x] remove accordions and put text into respective cards
- [ ]  ~Make sure state is changed from Maryland to Arkansas~ (this is not hardcoded, see [Slack thread](https://themostudio.slack.com/archives/C053T73JJ3U/p1715109851470739))
- [x] implement content changes on page 12 of [content doc](https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit)

# Fill in information

<img width="587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47d7e5d606ef8a1d30f6b24ada7f0b698ba3a815/Screenshot%202024-04-26%20at%207.40.32%20AM.png" alt="Screenshot 2024-04-26 at 7.40.32 AM.png" />

- [x] remove accordions and put text into respective cards
- [x] implement input box formatting for SSN (insert dashes between numbers) and DOB (MM, DD, YYYY)
- [x] implement content changes on page 13 of [content doc](https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit)
- [ ] Check in during Devign sync or async regarding if information in form should be filled

# Complete verification

<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9ZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2869f0b4b56ed9eaf542d32b4c024a3691f6aaf1/Screenshot%202024-04-26%20at%207.41.11%20AM.png" alt="Screenshot 2024-04-26 at 7.41.11 AM.png" />

<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6911172c18d0987722c846affd09a28d9e7e323/Screenshot%202024-05-10%20at%209.04.48%20AM.png" alt="Screenshot 2024-05-10 at 9.04.48 AM.png" />

- [x] remove accordions and put text into respective cards
- [x] implement content changes on page 14 of [content doc](https://docs.google.com/document/d/1gBLnFcPb6fm7HGdRnaHJvy4LdA67BrJROOqDhXW3te0/edit)
- [x] UPDATE: change quotes around "Complete" from double quotes to single quotes to match consistency

# Verification complete

<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--262462a055af490172e71899bfd450d90c928714/Screenshot%202024-04-26%20at%207.43.10%20AM.png" alt="Screenshot 2024-04-26 at 7.43.10 AM.png" />

- [x] make sure case number is updated to confirmation case number

**Comment by SophiaPhilipMO** [comment]
ICN formatting:
Each Veteran’s 17-character ICN (10 digits + “V” + 6 digits) is unique and serves the same purpose as an SSN through the entire community care experience.
https://content.govdelivery.com/accounts/USVHA/bulletins/2f74119

This link also references that it’s 17 characters, “Include the 17 alpha-numeric (10 digits + "V" + 6 digits) VA-assigned internal control number (ICN) in the insured's I.D. field. “
https://www.va.gov/COMMUNITYCARE/revenue-ops/Veteran-Care-Claims.asp 

And one more for triple checking: “Missing/Incomplete/Invalid Insured ID
Requires the 17 alpha-numeric internal control number (ICN) [format: 10 digits + "V" + 6 digits] or 9-digit social security number (SSN) with no special characters.”
https://www.va.gov/COMMUNITYCARE/revenue-ops/rejected-claims.asp

**Comment by skirkman16** [comment]
Mateo and I reviewed screens and changed the CTA on Validate ID from 'Next' to 'Continue'. We also decided to maintain the WCAG AA guidelines for the dropdown so we kept the dropdown selection background color to #767676

**Comment by skirkman16** [comment]
@mateoclarke I added in two content changes I missed. On the Enter case number screen, the input box should have confirmation case number over it and in the complete verification screen the quotes around Complete need to be changed from double to single to be consistent with the rest of the content
