### ISSUE TITLE
Fix Use My Location button size

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#81667]
## Issue Description
A platform change was put in that broke the sizing of the arrow on the Use My Location button on Find a Rep. 

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd07eb1cdbc4dfc06d471c57559b8e3db3855bc3/image.png" alt="image.png" />

---
## Tasks
- [ ] Refactor Use My Location button styling

## Acceptance Criteria
- [ ] Button is resized

**Comment by oddball-lindsay** [comment]
Seeing the icon back to it's expected size in both Staging and Production.

Staging:
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1d4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ca469faf43a3d0f9aeb7572c7d8160e3a5fe73b/image.png" alt="image.png" />

Production: 
<img width="723" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2F4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0653ab89773bee39c5f0551387f17ef994676cd5/image.png" alt="image.png" />
