### ISSUE TITLE
Deploy Proofing Agent App to LHDI DEV Region - CD

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#81663]
Context: We split the deployment ticket into CI and CD tasks. This ticket will track the deployment (CD) portion of the pipeline.

The outcome of this ticket is that the pipeline will take the packaged app in the container repo, create the AWS resources and then push our images to those servers. 

## AC
- [x] SecRel pipeline is able to run against our repo 
- [ ] Create the AWS resources: EKS, RDS and VPC
- [ ] Push the container image to the resources via Argo CD and Helmchart
- [ ] Setup internal connections between services
- [ ] Setup external connection to services (Login.gov, Google Earth)

Final outcome: IPP App full stack is deployed and accessible on the LHDI machine.

[LHDI Docs on CD](https://laughing-adventure-wllepqe.pages.github.io/Lighthouse-delivery-infrastructure-tools/Using-the-DI-tools/Step-4-Deploy-your-project-to-dev/Deploy-with-Argo-CD/)
[ArgoCD Console](https://ldx-mapi.lighthouse.va.gov/argocd)
[LHDI Cluster Information Docs](https://laughing-adventure-wllepqe.pages.github.io/Lighthouse-delivery-infrastructure-tools/Using-[…]Getting-to-know-your-environments/Service-mesh/)

**Comment by rdvyas** [comment]
1. Access ArgoCD Admin Console
2. Create a project for DEV region
