### ISSUE TITLE
Reports Powered by UA: [Virtual Agent Chatbot Team]

### ISSUE THREAD

**Issue by alexperson-tw** [department-of-veterans-affairs/va.gov-team#81683]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

---

### Instructions:
**Step 1:** Please provide the following information on each actively used report your team uses that contains UA data at the bottom of this ticket. _(Or, if it's easier, attach a spreadsheet.)_
- Report Name
- URL Link
- Reporting Platform (Domo, GA, etc.)
- Description of Report (i.e. How it's used)
  
**Step 2:** Include your team name within the title of this form.

**Step 3:** Submit this form.

_Our team will follow up with you for any next steps._

> [!NOTE]
> - We are defining _"actively used reports"_ as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
> - Teams do NOT have to include the standard [Search](https://va-gov.domo.com/page/1964748112), [Content](https://va-gov.domo.com/page/426422632), or [Forms](https://va-gov.domo.com/page/447193050) KPI dashboards --  we are already working to update those.

> ### Example:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|VA Homepage Report|https://va-gov.domo.com/page/|Domo| Our team uses this report to analyze trends for our KPIs.|
---

## Reporting Information:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|Chatbot Prescription Skill Users|https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20240226&_u.date01=20240227&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-table.filter=PI%20Request%20-%20Enter%20Chatbot%20Rx%20Skill%20-%20successful&explorer-graphOptions.selected=analytics.nthWeek| GA| Event triggered when a user successfully accesses the chatbot prescriptions skill.|
|Chatbot Microphone Usage|https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20240226&_u.date01=20240227&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-table.filter=microphone&explorer-graphOptions.selected=analytics.nthWeek|GA|Event triggered every time the microphone is enabled on the chatbot for voice input.|
|Outbound Link Clicks from Chatbot|https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20240226&_u.date01=20240227&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-table.filter=Resource%20Link%20-&explorer-graphOptions.selected=analytics.nthWeek|GA|Event triggered when a user clicks any link from a chatbot message. All links clicked from the chatbot will fire different events following the same naming convention "Chatbot - - Resource Link - LINK-TEXT - URL"|
|Chatbot QuickReply Button Clicks|https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20240226&_u.date01=20240227&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&explorer-table.filter=-%20Response&explorer-graphOptions.selected=analytics.nthWeek|GA|Event triggered when a user clicks a quickReply button from the chatbot. All events triggered by quickReply button clicks will follow the same naming convention "Chatbot - - SKILL CLICKED FROM - Response - QUICKREPLY BUTTON TEXT"|

**Comment by johnny-jesensky-adhoc** [comment]
This information has been documented in a separate file -- closing out this ticket.

FYI @ChristineYoungZA, @Blivaditis
