### ISSUE TITLE
Design Feedback - Design Intent - Community Care Direct Scheduling

### ISSUE THREAD

**Issue by naomimarcussen** [department-of-veterans-affairs/va.gov-team#81698]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Look to mobile app interfaces like One Medical for inspiration
- In order to streamline the flow, you could remove the continue button on the bottom and just have the selection of a radio button move you forward. The tile variation of the radio button might give you a bigger tap target for this purpose.
- Include as much info about the provider as you can to help the user make a decision.
- Consider simplifying the process by first selecting the provider, then focus on selecting a time. Maybe you could surface those providers with the soonest appointment first (based on research) and show that time/date, then on the next screen show all times to select from.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- 

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by cgednalske** [comment]
We brought our updated approach to office hours on 5/8 ([Figma mockups](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=629%3A31344&t=mn1Pq4pRTye1E0jS-1)), which addresses all design feedback included here. 

> Consider simplifying the process by first selecting the provider, then focus on selecting a time. Maybe you could surface those providers with the soonest appointment first (based on research) and show that time/date, then on the next screen show all times to select from.

-  The updated approach separates out the provider selection and date/time selection. 
- The [provider list](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=629%3A35128&t=mn1Pq4pRTye1E0jS-1) includes each provider's next available appointment (no interaction). 

> Include as much info about the provider as you can to help the user make a decision.

- We now include more provider information on [each provider's detail/date selection page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=633%3A31926&t=mn1Pq4pRTye1E0jS-1). If/when more provider information becomes available, we will continue to add to these pages and/or expand provider list filtering options.
