### ISSUE TITLE
Remove feature toggle: mhv_landing_page_enabled

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#81709]
Now that this feature toggle is at 100%, it can be removed.

- [x] Remove feature toggle from `vets-api`
  - department-of-veterans-affairs/vets-api/pull/17370
- [x] Remove feature toggle from `vets-website`
  - department-of-veterans-affairs/vets-website/pull/29573
  - department-of-veterans-affairs/vets-website/pull/30654
- [x] Merge changes
- [x] Wait for changes to propagate to envs.
- [x] Run `Flipper.remove(:mhv_landing_page_enabled)` in development (dev-api.va.gov)
- [x] Run `Flipper.remove(:mhv_landing_page_enabled)` in staging (staging-api.va.gov)
- [x] Run `Flipper.remove(:mhv_landing_page_enabled)` in sandbox (sandbox-api.va.gov)
- [x] Run `Flipper.remove(:mhv_landing_page_enabled)` in production (api.va.gov) [x2]

[VA Platform docs: Removing old/unused feature toggles](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)

**Comment by allanto-ah** [comment]
@radavis I still see the feature toggle in the production environment, api.va.gov. Is this expected?

<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3218f36b14a8fdc509a7028f37d26aef17cd18f0/Screenshot%202024-07-09%20at%208.26.58%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 8.26.58 AM.png" />

**Comment by radavis** [comment]
@allanto-ah That's strange because I was able to verify that it was removed in the following support request. I suppose I'll ask to have it removed, again...

https://github.com/department-of-veterans-affairs/va.gov-team/issues/87749

**Comment by radavis** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/87912

Half-an-hour after removal, it's showing up in the flipper UI.

We've gone through the steps. The feature toggle is removed from the codebase, which can be verified by searching `mhv_landing_page_enabled` and `mhvLandingPageEnabled` in vets-website and vets-api. As for removing the feature toggle permanently from the production database, this is a higher-level problem that's not going to be solved as part of this ticket.

**Comment by radavis** [comment]
@allanto-ah This should be ready for QA, now.

**Comment by allanto-ah** [comment]
Verified that the feature toggle has been removed from api.va.gov. Also verified that MHV landing page is working as expected
