### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by Lpatel24** [department-of-veterans-affairs/va.gov-team#81702]
### Name

Lauren Patel 

### Email

lauren.patel@va.gov

### Role

Health Science Specialist, Project Manager

### Team

ProGRESS Team

### Product Manager (PM) name

Jason Vassy, Principal Investigator, Attending Physcian

### Additional Notes

I am requesting access to design libraries to create a branding kit for a VHA /ProGRESS study

**Comment by naomimarcussen** [comment]
An invite has been sent to lauren.patel@va.gov.
