### ISSUE TITLE
Fix Sidekiq Instrumentation

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#8173]
## The Problem
We have don't have the metrics we need in prometheus to allow us to get a good sense of what is going on in our sidekiq queues / worker instances.

## Additional Context
Connects: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8150

[As part of migrating Redis from 3 to 5](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6865), we want full insight into our sidekiq queues & scheduled jobs. This would better allow us to:

- know which jobs live in each redis instance so we don't duplicate any
- know when the jobs from the old redis have been sufficiently "drained"

## Work to be Done
- [x] Discover / fix the fact that our `sidekiq-instrument` gem isn't reporting us the metrics that it's supposed to
- [ ] Discover & implement how to export any and all available sidekiq metrics to be consumed by prometheus

**Comment by johnpaulashenfelter** [comment]
You might want to check if sidekiq5 (which we can upgrade to with redis3 that we already have) changes any of that instrumentation or offers other options 

Sidekiq6 (which we should be at by end of sprint) has some prometheus style json endpoints built in https://github.com/mperham/sidekiq/wiki/Monitoring#using-the-built-in-dashboard as well as a monitoring app that seems less useful https://github.com/mperham/sidekiq/wiki/Monitoring#sidekiqmon

**Comment by omgitsbillryan** [comment]
I found a [neat little route (`/dashboard/stats`)](https://github.com/mperham/sidekiq/wiki/Monitoring#using-the-built-in-dashboard) that comes with sidekiq and returns some useful data:

```
{
  "sidekiq": {
    "processed": 12345,
    "failed": 56,
    "busy": 25,
    "enqueued": 178,
    "scheduled": 0,
    "retries": 0,
    "default_latency": 12
  },
  "redis": {
    "connected_clients": "120",
    "uptime_in_days": "35",
    "used_memory_human": "602.31M",
    "used_memory_peak_human": "1.01G"
  }
}
```

I also dug around our prometheus metrics and came across `api_jobs_*` that all looks useful:

![image](https://user-images.githubusercontent.com/3077884/79787319-ccfdef80-8314-11ea-984e-423236a1a946.png)


I had originally (and erroneously) looked for [the StatsD metric names](https://github.com/enova/sidekiq-instrument#statsd-keys) w/o realizing that these metric names get converted by the statsd-exporter while converting StatsD in prometheus.

**Comment by omgitsbillryan** [comment]
Not quite instrumentation, but semi-related: it's possible to check on sidekiq queue sizes via the `rails console`.

source: https://gist.github.com/ngsmrk/4ad439143622a46b8a5b
```ruby
stats = Sidekiq::Stats.new

stats.queues

stats.enqueued

stats.processed

stats.failed

scheduled_queue = Sidekiq::ScheduledSet.new

retry_queue = Sidekiq::RetrySet.new

default_queue = Sidekiq::Queue.new("default")

default_queue.each do | job |
	class_arg = job.args[0].split('-').select { | arg  | arg.match(' !ruby/class')  }[0]
	
	p class_arg.split[1].gsub '\'', '' unless class_arg.nil?
end
```

If `sidekiq-instrument` is not to our liking for whatever reason, we could write our own custom sidekiq job that uses the above to export our own stats.

**Comment by johnpaulashenfelter** [comment]
Probably time to take a look at https://github.com/prometheus/statsd_exporter

**Comment by erluti** [comment]
[This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4283) removed `sidekiq-instrument`.  It's successfully deployed to prod.
