### ISSUE TITLE
UX: Temporary medical records landing page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#81734]
# Description
## User story
As a My HealtheVet user, I want to have a consistent experience when I click any link on the secondary navigation menu, and get helpful information presented to me about each tool as I am trying out this new experience. 

As a My HealtheVet user, I want to know what to expect when I click "Records" in the secondary navigation menu so that I am not surprised and do not lose trust with the VA that the status of my medical records are unclear while the transition is still underway

As a designer on VA.gov, I want to communicate the current state of the My HealtheVet transition as transparently as possible to users, so that they know what to expect today and have clarity on what is coming soon. 

## Notes
As part of the secondary navigation design work in ticket #80821 - we were tasked with coming up with a plan for how to treat Medical Records, which is visible in the navigation and on the landing page, but is the only tool that is not publicly available on VA.gov (still in pilot phase 0). 

We presented a series of options and got buy-in on the option that we believe offers the best user experience, which is to create a temporary landing page for Medical Records that will do a few things: 
* provide a consistent experience to users for this link in the secondary nav (will link to a landing page like the other tools)
* that real-estate can be used to effectively communicate the "in progress" situation that medical records is in, and send users back to the National Portal to view their medical records for now

### Engineering notes
- Q: @sterkenburgsara to inquire about URL options (which drive implementation decisions)
  - A: It has to be a new app outside the `/medical-records/` path, because that path is un-gated during their Ph0. [thread](https://agilesix.slack.com/archives/C05PH6V3MJL/p1714590460462179?thread_ts=1714588791.412429&cid=C05PH6V3MJL)

## Acceptance criteria
- [x] [Design page in Figma](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=1268-16820&mode=design&t=5U7qU4ZecHH0lLTq-0)
- [x] Get stakeholder and MR team approval on design & URL

**Comment by sterkenburgsara** [comment]
[CAIA ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81736)

cc @laurwill

**Comment by sterkenburgsara** [comment]
Shared in-progress designs via Slack (private channel) with Medical Records UX team and @kfink24 on 4/26. Will discuss at the team's next UX weekly sync on Wednesday 5/1.

**Comment by sterkenburgsara** [comment]
Update: incorporated content changes from @laurwill and running the use of a tag component by accessibility @brea11y

**Comment by wesrowe** [comment]
created a separate implementation ticket, #82081

**Comment by sterkenburgsara** [comment]
Update: have approved URL and ready to-go Figma file / passing off to devs for implementation. 

* URL: `va.gov/my-health/records`
* [Figma file](https://www.figma.com/file/HnaBQQwuyjxM7ycFrTCozl/TEMP---Medical-records-landing-page?type=design&node-id=50-11&mode=design&t=L07sPToLWMMMc0eu-0)
