### ISSUE TITLE
Reports Powered by UA: [Pension benefits team]

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#81743]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

---

### Instructions:
**Step 1:** Please provide the following information on each actively used report your team uses that contains UA data at the bottom of this ticket. _(Or, if it's easier, attach a spreadsheet.)_

[Pension Team Report Inventory for GA4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15134463/Pension.Team.Report.Inventory.for.GA4.docx)

- Report Name
- URL Link
- Reporting Platform (Domo, GA, etc.)
- Description of Report (i.e. How it's used)
  
**Step 2:** Include your team name within the title of this form.
Done
**Step 3:** Submit this form.

_Our team will follow up with you for any next steps._

> [!NOTE]
> - We are defining _"actively used reports"_ as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
> - Teams do NOT have to include the standard [Search](https://va-gov.domo.com/page/1964748112), [Content](https://va-gov.domo.com/page/426422632), or [Forms](https://va-gov.domo.com/page/447193050) KPI dashboards --  we are already working to update those.

> ### Example:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|VA Homepage Report|https://va-gov.domo.com/page/|Domo| Our team uses this report to analyze trends for our KPIs.|
---

## Reporting Information:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|`[Report 1 Name`] |`[URL Link]`| `[Reporting Platform]`| `[Description]`|
|`[Report 2 Name`] |`[URL Link]`| `[Reporting Platform]`| `[Description]`|
|`[Report 3 Name`] |`[URL Link]`| `[Reporting Platform]`| `[Description]`|

**Comment by ChristineYoungZA** [comment]
Hi @matt4su could you update the ticket to include the reports name, url link, reporting platform and description of the report?

**Comment by matt4su** [comment]
Hi Christine, please see attached doc
[Pension.Team.Report.Inventory.for.GA4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15142525/Pension.Team.Report.Inventory.for.GA4.docx)

**Comment by Blivaditis** [comment]
Hi @matt4su, can you send the link for the GA Event Reports - Applicant Information and GA Funnel Report for 527EZ. The reports are included in the document however one has an incomplete link while the other is missing a link/

**Comment by johnny-jesensky-adhoc** [comment]
This information has been documented in a separate file -- closing out this ticket.

FYI @ChristineYoungZA, @Blivaditis
