### ISSUE TITLE
Contact Center Review for Toxic Exposure Employee Experience (EE) Team - Max Claims for Increase (CFI)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#81747]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

Max Claims for Increase (CFI): We are preparing to expand the max rating notice for all conditions by: updating the max rating API to include the max rating for all diagnostic codes, implementing the notice on the 526 form on VA.gov, adding logic to handle hyphenated conditions on the 526 form, and updating our Datadog metrics.

### Launch Date
*Please provide the launch or rollout date and details.*

**Phased rollout:**

- May 27, 2024: Backend feature flag is enabled to populate max rating percentage for all users. This does not control displaying max rating to the Veteran. Initial rollout to 10% of users who will see max rating notice for all conditions.
- June 3, 2024: Increase to 25% of users who will see max rating notice for all conditions.
- June 10, 2024:  Increase to 50% of users who will see max rating notice for all conditions.
- June 17, 2024: Increase to 100% of users who will see max rating notice for all conditions.

### Version Number
*Please provide the version number of the guide and/or video.*
Version 3.1

### Product Guide
*Please provide product guide link*
[526ez Disability Benefits Claims Product Guide.docx](https://github.com/department-of-veterans-affairs/abd-vro/files/15132171/526ez.Disability.Benefits.Claims.Product.Guide.docx)

### Product Video
*Please provide product video link*
n/a

### Product Video Transcript
*Please provide product video transcript link*
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Received 4/26; Veteran Support and VEO review on schedule for completion in the current sprint.

**Comment by starlow00** [comment]
Draft looks good. Sending to VEO for their review.

**Comment by BerniXiongA6** [comment]
FYI @starlow00 -- after submitting this ticket, we noticed that our first launch date lands on a federal holiday. Therefore, our team has decided to push out our phased rollout dates by one day. Please see the revised launch plan schedule:

(Revised) Phased rollout:
May 28, 2024: Backend feature flag is enabled to populate max rating percentage for all users. This does not control displaying max rating to the Veteran. Initial rollout to 10% of users who will see max rating notice for all conditions.
June 4, 2024: Increase to 25% of users who will see max rating notice for all conditions.
June 11, 2024: Increase to 50% of users who will see max rating notice for all conditions.
June 18, 2024: Increase to 100% of users who will see max rating notice for all conditions.

**Comment by starlow00** [comment]
Thank you! I will forward the updates to VEO.

From: BerniXiongA6 ***@***.***>
Sent: Wednesday, May 1, 2024 8:41 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Tarlow, Steven R. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for Toxic Exposure Employee Experience (EE) Team - Max Claims for Increase (CFI) (Issue #81747)


FYI @starlow00<https://github.com/starlow00> -- after submitting this ticket, we noticed that our first launch date lands on a federal holiday. Therefore, our team has decided to push out our phased rollout dates by one day. Please see the revised launch plan schedule:

(Revised) Phased rollout:
May 28, 2024: Backend feature flag is enabled to populate max rating percentage for all users. This does not control displaying max rating to the Veteran. Initial rollout to 10% of users who will see max rating notice for all conditions.
June 4, 2024: Increase to 25% of users who will see max rating notice for all conditions.
June 11, 2024: Increase to 50% of users who will see max rating notice for all conditions.
June 18, 2024: Increase to 100% of users who will see max rating notice for all conditions.

-

**Comment by starlow00** [comment]
No changes from VEO. Please use the attached copy for future versions. Thank you!
[VA Form 21-526EZ v3.1 product guide SRT 04292024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUsxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f6d4da430d18c8c0ef44386bd1997fff33b9ee3/VA%20Form%2021-526EZ%20v3.1%20product%20guide%20SRT%2004292024.docx)

**Comment by BerniXiongA6** [comment]
Hi @starlow00 there have been a few revisions to the phased launch dates. I'm posting them here for the record -- please share as you see fit:

Phased rollout (Revised 5/7/2024):
May 28, 2024: Backend feature flag is enabled to populate max rating percentage for all users. This does not control displaying max rating to the Veteran. Initial rollout to 10% of users who will see max rating notice for all conditions.
June 4, 2024: Increase to 25% of users who will see max rating notice for all conditions.
June 11, 2024: Increase to 50% of users who will see max rating notice for all conditions.
July 2024 (date TBD): After monitoring the launch stats at the 50% phase, the team will check in during July 2024 (date to be determine) to decide when to increase to 100% of users who will see max rating notice for all conditions.

**Comment by starlow00** [comment]
Notified VEO of changes to the final phase of launch.
