### ISSUE TITLE
Copyedit batch of pages about benefits for dependents

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#81742]
This ticket will track copyediting for a batch of 8 new page drafts about 3 related programs:
- CHAMPVA
- Spina bifida benefits
- Children of Women Vietnam Veterans benefits

I'll post each draft here as it's ready for copyedit, and Sara will check them off as she finishes each one:
- [x] [Spina bifida page in benefit hub.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/Spina%20bifida%20page%20in%20benefit%20hub.docx?d=w9d130108463d48c899a44affb494b47d&csf=1&web=1&e=Eq58lp)
- [x] [CWVV page in benefit hub](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/CWVV%20page%20in%20benefit%20hub.docx?d=w37f3d877a28e4817915b26a78ed6932d&csf=1&web=1&e=dLkFeK)
- [x] [RS14 SBHCBP and CWVV Q&As](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS14%20SBHCBP%20and%20CWVV%20Q%26As.docx?d=wd5b93e81620d452f9ff914ab815b2f99&csf=1&web=1&e=lDaGOD)
- [x] [RS15_File a claim for SB and CWVV.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS17_File%20a%20claim%20for%20SB%20and%20CWVV.docx?d=w791d6dad533d4cdfa8f3d2655d4e0e01&csf=1&web=1&e=k6286M)
- [x] [RS13_Meds by Mail_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS13_Meds%20by%20Mail_Draft.docx?d=w22bf61cb0ff046a68ba6112d7aa8b9ed&csf=1&web=1&e=t0hF8q)
- [x] [RS11_File a CHAMPVA claim_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS11_File%20a%20CHAMPVA%20claim_Draft.docx?d=w4c3a7664a2ab46d68877c511e21ae06b&csf=1&web=1&e=CwMbFd)
- [x] [RS12 - CHAMPVA Q&As_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS12%20-%20CHAMPVA%20Q%26As_Draft.docx?d=wdc2a257d4278440ca8df52d6793c5831&csf=1&web=1&e=ZbtNPX)
- [x] [CHAMPVA main page updates.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/CHAMPVA%20main%20page%20updates.docx?d=w3e9df0a1f0ee4410af638ea0943ff54e&csf=1&web=1&e=UiL5qX)

**Comment by laurwill** [comment]
Hi again @saratorres2 , I added 2 more docs to the top section — these are the 2 resources and support pages related to the spina bifida and CWVV programs. These pages aren't in Drupal. Let's have you start with this batch of 4 closely related documents and then check in before you start on the rest of the set. Thank you!

**Comment by laurwill** [comment]
Hi @saratorres2 ! One more ready for you — I'll post the last two shortly. [RS13_Meds by Mail_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS13_Meds%20by%20Mail_Draft.docx?d=w22bf61cb0ff046a68ba6112d7aa8b9ed&csf=1&web=1&e=t0hF8q)

**Comment by laurwill** [comment]
All posted now! The Meds by Mail page applies to all 3 programs, and the last 3 pages in the list are all about the CHAMPVA program.

**Comment by saratorres2** [comment]
@laurwill All pages have been copy edited. I've left a few queries here and there to clarify wording, and corrected a few punctuation errors.

**Comment by laurwill** [comment]
Thanks so much Sara! @DanielleThierryUSDSVA just tagging you for awareness — I'll reconcile these edits Monday morning, and then we can send the R&S pages to Kelly to build in Drupal.

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , the batch of community care pages is ready for you to review.

These 3 benefit detail pages are already in Drupal, I just need to update to match Word docs:
- [Spina bifida page in benefit hub.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/Spina%20bifida%20page%20in%20benefit%20hub.docx?d=w9d130108463d48c899a44affb494b47d&csf=1&web=1&e=Eq58lp)
- [CWVV page in benefit hub](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/CWVV%20page%20in%20benefit%20hub.docx?d=w37f3d877a28e4817915b26a78ed6932d&csf=1&web=1&e=dLkFeK)
- [CHAMPVA main page updates.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/CHAMPVA%20main%20page%20updates.docx?d=w3e9df0a1f0ee4410af638ea0943ff54e&csf=1&web=1&e=UiL5qX)

And these R&S pages are ready for Kelly to build in Drupal:
- [RS14 SBHCBP and CWVV Q&As](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS14%20SBHCBP%20and%20CWVV%20Q%26As.docx?d=wd5b93e81620d452f9ff914ab815b2f99&csf=1&web=1&e=lDaGOD)
- [RS15_File a claim for SB and CWVV.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS17_File%20a%20claim%20for%20SB%20and%20CWVV.docx?d=w791d6dad533d4cdfa8f3d2655d4e0e01&csf=1&web=1&e=k6286M)
- [RS13_Meds by Mail_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS13_Meds%20by%20Mail_Draft.docx?d=w22bf61cb0ff046a68ba6112d7aa8b9ed&csf=1&web=1&e=t0hF8q)
- [RS11_File a CHAMPVA claim_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS11_File%20a%20CHAMPVA%20claim_Draft.docx?d=w4c3a7664a2ab46d68877c511e21ae06b&csf=1&web=1&e=CwMbFd)
- [RS12 - CHAMPVA Q&As_Draft.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS12%20-%20CHAMPVA%20Q%26As_Draft.docx?d=wdc2a257d4278440ca8df52d6793c5831&csf=1&web=1&e=ZbtNPX)

**Comment by laurwill** [comment]
Closing! These are now in SME review.
