### ISSUE TITLE
AWS access for Joshua Bolling

### ISSUE THREAD

**Issue by jcbolling** [department-of-veterans-affairs/va.gov-team#81751]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Joshua Bolling

### Your Email

jbolling@metrostar.com

### Team, Role, and Company of the target individual

Joshua Bolling, DevOps Engineer, MetroStar

### Product Manager (PM) name and email

Grace Kretschmer | mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn | Erika.Washburn@va.gov

### Desired AWS Access

Admin access would be nice but at minimum:
EKS
IAM
route53
ec2
RDS
ECR
S3

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1048" alt="Screenshot 2024-04-26 at 4 22 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/21695687/7ea8cc83-c415-465d-8412-65510eba93f3">

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Good Afternoon, @jcbolling. Could you please tell me which team you're on? Ideally, this should be in your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile).

**Comment by jcbolling** [comment]
Good afternoon @flooose. I'm on the CMS Platform Team.

**Comment by flooose** [comment]
User is in platform roster

**Comment by flooose** [comment]
User is requesting prod access, flagging @department-of-veterans-affairs/operations-aws-approvers for approval.

**Comment by JonathanKamensDVA** [comment]
Approved.
