### ISSUE TITLE
Edit: Update Style Guide: Embedded Video Best Practice

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#81754]
As the Platform continues to pivot toward more video content, we need to shore up our guidance for videos. One issue that keeps coming up -- and therefore seems like a good candidate for our first video guidance update -- is embedded videos. 

There are two ways to embed videos in Confluence/PW. [This Discovery Ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/83009) saw the PCT pick the option we want to advise teams to use when embedding videos. This ticket involves updating the Style Guide to reflect this new Best Practice for Embedding Videos.

**NOTE: Once this is updated, it should become the next Tip of the Sprint.** 

### TASKS
- [x] Update Stye Guide per [this ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/83009)

### DEFINITION OF DONE

- [x] Style Guide has been updated with new, team approved language. 

### RELATED DISCOVERY TICKET:
[83009](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/83009)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/81754?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
@BSmolensky Tip of The Sprint creation has been removed from Tasks, please feel free to complete Planning Poker estimate

**Comment by BSmolensky** [comment]
Style Guide has been updated. https://vfs.atlassian.net/wiki/spaces/AP/pages/1806172307/Images+videos+and+other+media#Video-formatting

**Comment by BSmolensky** [comment]
This ticket is ready to close.

**Comment by jknipes** [comment]
work is completed, moving to _Done_
