### ISSUE TITLE
Architecture Diagram update to capture the work for Find Forms MVP

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8179]
To do item to generate an architecture diagram
To capture the work we did  for the MVP version of Find Forms Search
So that 
We can walk through the diagram with VSP during Staging Review and present an accurate picture of the changes that were needed to create this initiative.

**Acceptance Criteria**
Architecture Diagram created, shareable

**Comment by ncksllvn** [comment]
Just made this via daw.io -

![image](https://user-images.githubusercontent.com/1915775/79777239-f6af1a80-8304-11ea-8b82-43e326288758.png)

**Comment by stephorkandatx** [comment]
Thanks @ncksllvn I am going to snag this for the privacy & security request, and close it out
