### ISSUE TITLE
[Research] Monitor Unmoderated Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#81792]
## Description
We need to Monitor the research study for the Discovery - Multiple Selection of Appointments.

## Tasks
- [x] Coordinate with Perigean to send out the study
- [x] Monitor the results

**Comment by benbrasso-agile6** [comment]
For Friday - https://docs.google.com/spreadsheets/d/1rrkORjs03ooEPHnIcYmvb_yJL7vwci5rylDVIySpFOE/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
Closing. Pretty much have everyone we need. https://docs.google.com/spreadsheets/d/1rrkORjs03ooEPHnIcYmvb_yJL7vwci5rylDVIySpFOE/edit#gid=0
