### ISSUE TITLE
Investigate submission failures

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81802]
Two submissions failed with the same error message:
https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-prod+%40payload.to_state%3Afailure+%40payload.form_type%3A21P-527EZ&from_ts=1714197600000&to_ts=1714222698000&live=false&agg_m=count&agg_t=count&index=%2A&source=monitor_notif

https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-prod+%40payload.to_state%3Afailure+%40payload.form_type%3A21P-527EZ&from_ts=1714111200000&to_ts=1714189278000&live=false&agg_m=count&agg_t=count&index=%2A&source=monitor_notif

benefits intake UUID
753898cf-6f33-4e53-85c3-a009b2b8db6b 

benefits intake UUID
49ccf7bd-c7b6-4569-83fe-39d8d759f6a0

Both went from pending to failure.  The error was that it expired.

> - After a POST request, there is a 15-minute window during which documents must be uploaded via a PUT request.
> - An Expired status means the documents were not successfully uploaded within this 15-minute window.
> - We recommend coding to retry unsuccessful uploads within 15 minutes using the same submission in case of connection issues.
> 

https://developer.va.gov/explore/api/benefits-intake/docs?version=current

**Comment by wayne-weibel** [comment]
```ruby
irb(main):006> fs.last
=> #<FormSubmission id: 28253, form_type: "21P-527EZ", benefits_intake_uuid: "7e0eda46-00b6-4b3c-917d-b726f53b25ab", submitted_claim_uuid: nil, user_account_id: nil, saved_claim_id: 8901906, in_progress_form_id: nil, encrypted_kms_key: "v2023:AQICAHjgjYH+KWbNRYBxOGDWJ7R6hKgus/oZ2XWComyf...", created_at: "2024-04-30 20:47:30.642473000 +0000", updated_at: "2024-04-30 20:47:30.642473000 +0000", form_data: [FILTERED]>
irb(main):007> 

irb(main):008> fs.last.id
=> 28253
irb(main):009> FormSubmissionAttempt.where form_submission_id: fs.last.id
=> [#<FormSubmissionAttempt id: 28253, form_submission_id: 28253, aasm_state: "pending", encrypted_kms_key: nil, created_at: "2024-04-30 20:47:30.813254000 +0000", updated_at: "2024-04-30 20:47:30.813254000 +0000">]
irb(main):010> 
```

**Comment by wayne-weibel** [comment]
```ruby
irb(main):010> FormSubmission.where saved_claim_id: 8901759
=> 
[#<FormSubmission id: 26862, form_type: "21P-527EZ", benefits_intake_uuid: "753898cf-6f33-4e53-85c3-a009b2b8db6b", submitted_claim_uuid: nil, user_account_id: nil, saved_claim_id: 8901759, in_progress_form_id: nil, encrypted_kms_key: "v2023:AQICAHjgjYH+KWbNRYBxOGDWJ7R6hKgus/oZ2XWComyf...", created_at: "2024-04-27 03:39:33.843572000 +0000", updated_at: "2024-04-27 03:39:33.843572000 +0000", form_data: [FILTERED]>,
 #<FormSubmission id: 26863, form_type: "21P-527EZ", benefits_intake_uuid: "94eec427-9a47-439e-a5eb-12d30495e0d6", submitted_claim_uuid: nil, user_account_id: nil, saved_claim_id: 8901759, in_progress_form_id: nil, encrypted_kms_key: "v2023:AQICAHjgjYH+KWbNRYBxOGDWJ7R6hKgus/oZ2XWComyf...", created_at: "2024-04-27 03:43:12.599628000 +0000", updated_at: "2024-04-27 03:43:12.599628000 +0000", form_data: [FILTERED]>,
 #<FormSubmission id: 28255, form_type: "21P-527EZ", benefits_intake_uuid: "2ac3d807-4b9f-43cc-b746-234aba0c0842", submitted_claim_uuid: nil, user_account_id: nil, saved_claim_id: 8901759, in_progress_form_id: nil, encrypted_kms_key: "v2023:AQICAHjgjYH+KWbNRYBxOGDWJ7R6hKgus/oZ2XWComyf...", created_at: "2024-04-30 20:49:18.247377000 +0000", updated_at: "2024-04-30 20:49:18.247377000 +0000", form_data: [FILTERED]>]
irb(main):011> fs = _
=> [#<FormSubmission id: 26862, form_type: "21P-527EZ", benefits_intake_uuid: "753898cf-6f33-4e53-85c3-a009b2b8db6b", ...
irb(main):012> fs.last
=> #<FormSubmission id: 28255, form_type: "21P-527EZ", benefits_intake_uuid: "2ac3d807-4b9f-43cc-b746-234aba0c0842", submitted_claim_uuid: nil, user_account_id: nil, saved_claim_id: 8901759, in_progress_form_id: nil, encrypted_kms_key: "v2023:AQICAHjgjYH+KWbNRYBxOGDWJ7R6hKgus/oZ2XWComyf...", created_at: "2024-04-30 20:49:18.247377000 +0000", updated_at: "2024-04-30 20:49:18.247377000 +0000", form_data: [FILTERED]>
irb(main):013> fs.last.id
=> 28255
irb(main):014> FormSubmissionAttempt.where form_submission_id: fs.last.id
=> [#<FormSubmissionAttempt id: 28255, form_submission_id: 28255, aasm_state: "pending", encrypted_kms_key: nil, created_at: "2024-04-30 20:49:18.409507000 +0000", updated_at: "2024-04-30 20:49:18.409507000 +0000">]
irb(main):015> 
```

**Comment by mjknight50** [comment]
{"data":{"id":"7e0eda46-00b6-4b3c-917d-b726f53b25ab","type":"document_upload","attributes":{"guid":"7e0eda46-00b6-4b3c-917d-b726f53b25ab","status":"vbms","code":null,"detail":"","location":null,"updated_at":"2024-05-01T13:52:54.053Z","uploaded_pdf":{"total_documents":12,"total_pages":30,"content":{"page_count":9,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":499160,"attachments":[{"page_count":1,"dimensions":{"height":6.0,"width":4.0,"oversized_pdf":false},"file_size":95770},{"page_count":1,"dimensions":{"height":6.0,"width":4.0,"oversized_pdf":false},"file_size":94034},{"page_count":2,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":74968},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":192334},{"page_count":2,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":90967},{"page_count":1,"dimensions":{"height":8.5,"width":14.0,"oversized_pdf":false},"file_size":68157},{"page_count":7,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":400247},{"page_count":2,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":75862},{"page_count":2,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":37226},{"page_count":1,"dimensions":{"height":6.0,"width":4.0,"oversized_pdf":false},"file_size":2282265},{"page_count":1,"dimensions":{"height":6.0,"width":4.0,"oversized_pdf":false},"file_size":1472611}]},"line_of_business":"PMC"}}}}%

**Comment by mjknight50** [comment]
`{"data":{"id":"2ac3d807-4b9f-43cc-b746-234aba0c0842","type":"document_upload","attributes":{"guid":"2ac3d807-4b9f-43cc-b746-234aba0c0842","status":"success","code":null,"detail":"","location":null,"updated_at":"2024-05-01T07:53:34.057Z","uploaded_pdf":{"total_documents":2,"total_pages":26,"content":{"page_count":8,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":714954,"attachments":[{"page_count":18,"dimensions":{"height":10.83,"width":8.26,"oversized_pdf":false},"file_size":11209313}]},"line_of_business":"PMC"}}}}%`

**Comment by mjknight50** [comment]
In an effort to prevent this from happening again, this ticket will address the back-end:
https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/82040
