### ISSUE TITLE
VA Form pages documentation generation

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#81812]
Create a hook to generate the chapter/page list with `{title, path}` minimally
If it does not make a mess of the output also include other attributes, except uiSchema and schema, eg. `depends, howPagePerItem, arrayPath, pageClass`, etc

- [ ] The hook should be contained in an executable script in the `script` dir
- [ ] The hook should be run as part of the build process, but only for the specified applications
- [ ] The hook should only run for applications with a `form.jsx`
- [ ] The hook should output the pages 'manifest' to a standalone JSON file next to the `form.jsx`

Should this output file be committed? If not, needs to be added to the `.gitignore`

**Comment by mjknight50** [comment]
@wayne-weibel Thanks for writing this up.  Looks good.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81812?planning-poker) with Zenhub @scottsdevelopment @wayne-weibel
