### ISSUE TITLE
Vets-api terminal access for Tyler Fink

### ISSUE THREAD

**Issue by tfink419** [department-of-veterans-affairs/va.gov-team#81824]
### Your Name

Tyler Fink

### Your GitHub handle (terminal access is managed through GitHub)

tfink419

### Team, Role, and Company of the target individual

Benefits & Claims - NonDisability/Dependents, Software Engineer, Oddball

### Product Manager (PM) name and email

Laura Steele laura.steele@coforma.io

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

VOR: Jeff Langworthy jeff@coforma.io
E-QIP Proof (AWS SOCKS Access Approval):  department-of-veterans-affairs/va.gov-team/issues/60217

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
confirmed in Atlas
E-QIP confirmed

**Comment by bdech** [comment]
@tfink419 You've been granted access to `dev`, `staging`, and `sandbox` environments.
