### ISSUE TITLE
Support two versions of 526; one without TE and one with TE fields

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#81830]
There are two use cases we want to address:

1. As a Veteran who is **beginning a 526 form for the first time**, I want to be able to claim my conditions related to toxic exposure so that I can receive VA disability compensation for qualifying conditions.

2. As a Veteran who is **resuming an in-progress 526 form**, I want to complete my disability benefits application without disruption that might arise from a transition to a new version of the form.

Acceptance Criteria:

1. VA.gov can route users appropriately respective to the Veteran's use case listed above
2. VA.gov can display TE fields to Veterans who either have an IPF or don't have an IPF as needed based on business decisions
3. VA.gov can display TE fields for Veterans who have an IPF incrementally (e.g. 10% of users, 20%, 30%, 40% of users, etc.) as needed to reduce risk

**Comment by pacerwow** [comment]
The first release will be only to Vets who begin a new 526 form;
when successful, release to Vets who have an In Progress Form (IPF)

**Comment by tblackwe** [comment]
REQUIREMENTS SPIKE: What happens if we toggle on TE, and then need to roll back? How do we handle the data we've collection

**Comment by tblackwe** [comment]
First time = Does not have an IPF, or elects to restart claim from beginning.

**Comment by tblackwe** [comment]
This feature should not have impact on Intent to File

**Comment by freeheeling** [comment]
Current Toxic Exposure flow created by Thomas with my feedback used as basis for implementation:
<img width="447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjYrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ba219d4fc72b6207834f1a12b210e503385262a/Screenshot%202024-05-07%20at%209.04.13%E2%80%AFAM.png" alt="Screenshot 2024-05-07 at 9.04.13 AM.png" />

**Comment by freeheeling** [comment]
Draft [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16666) to add `toxic_exposure` to `form526_submissions` table.

**Comment by pacerwow** [comment]
@freeheeling 

Re TE Phase 2 (for Veterans with an IPF) is it technically possible to show Veterans the new TE fields if we Release TE while a Veteran has an active session? I'm not too concerned (yet) with "should we" but more if this is even possible.

**Comment by freeheeling** [comment]
As it's being developed, it **may** be possible, but not without unplanned logic included, to show Veterans the new TE fields if they have an active session. Only at the moment a Veteran starts a new claim would their In Progress Form (IPF) be conditionally flagged as having the TE section. If being able to update an IPF to have TE fields is desired, it would require additional work, although I don't think it would change the current design.

**Comment by freeheeling** [comment]
Drafted `submit_endpoint` data migration [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16693) that also includes functionality to programmatically set the enum attribute moving forward.

**Comment by freeheeling** [comment]
All checks now passing.

**Comment by freeheeling** [comment]
2 PRs submitted:
- [Assign toxic exposure submit endpoint & metadata](https://github.com/department-of-veterans-affairs/vets-api/pull/16802)
  - completes backend development to support two versions of form 526, with and without toxic exposure section
- [Explicitly load Form526Submission submit_endpoint data migration module](https://github.com/department-of-veterans-affairs/vets-api/pull/16823)
  - resolves an error attempting to execute the Rake task on staging
  
Remaining frontend work includes:
- [ ] sending an optional param (`includes_toxic_exposure`) when submitting a claim to the `/v0/disability_compensation_form/submit_all_claim` endpoint, indicating that the form data provided includes the toxic exposure section; this indicator will be used to set the `submit_endpoint` attribute on the `Form526Submission` record created when a claim is submitted, which will be necessary in determining the submission's destination. 
- [ ] updates to accept, store, and return the new `showToxicExposure` attribute in each `PUT` request to `v0/disability_compensation_in_progress_forms/21-526EZ`.
- [ ] confirming the implementation of the `:disability_526_toxic_exposure, <user>` Flipper

**Comment by freeheeling** [comment]
Remaining work to complete this task has been broken out and described in 3 separate tickets:
- https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/83847
- https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/83848
- https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/83849

Changing classification of this ticket to **Done**.

**Comment by freeheeling** [comment]
Comments regarding needed updates added to [diagram](https://lucid.app/lucidchart/12827838-5a2f-4fcb-9e5a-4007e4c29389/edit?existing=1&docId=12827838-5a2f-4fcb-9e5a-4007e4c29389&shared=true&invitationId=inv_7a291ff2-49be-4e4e-bc45-01d51e376e6e&page=8cGQsL8AN8jyu) depicted in [an earlier comment above](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/81830#issuecomment-2098640838).
