### ISSUE TITLE
[FE] Pilot rollout for new landing page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#81831]
We need to slowly roll out the new upcoming appointments list part of the new landing page so that we can monitor the new API performance and scalability. All the users would get the new flow of validate -> landing page -> questions -> complete. Only a percentage of users will see the upcoming appointments component.

- Use the feature flag percentage to control the rollout
- Add feature flag if needed
- Use feature flag to control the visibility and api call of the upcoming appointments component

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/81831?planning-poker) with Zenhub @wullaski

**Comment by wullaski** [comment]
@loripusey, @benbrasso-agile6 cc: @brianseek 

In our engineering sync we discussed this and decided that using the feature toggle percentage to control the rollout would be the best way to do this.

**Comment by loripusey** [comment]
So, sounds like we need to use this ticket to wrap everything in a feature flag?

**Comment by benbrasso-agile6** [comment]
Sounds fine with me

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 / @cgednalske This is ready to validate. See screenshots of day-of and pre-check with upcoming feature turned off
<img width="251" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4695a54a98a79d3dbd589238f354c465b20d5079/day-off-upcoming-off.png" alt="day-off-upcoming-off.png" />
<img width="246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89c8b2743c79eb5c8bd55570805f524e29e15bac/pre-check-in-upcoming-off.png" alt="pre-check-in-upcoming-off.png" />

**Comment by benbrasso-agile6** [comment]
Knowing that there's only ever mostly going to be 1 task to complete, does it make sense to have the refresh feature? Don't do anything yet though. Let's wait to talk this afternoon first. 

Otherwise, this looks good, if you did want to close it.

**Comment by brianseek** [comment]
there can be more than one day-of appointment, but makes less sense for pre-check-in. We can chat later today, but I'll close this one up and we can make a new ticket for what we decide.
