### ISSUE TITLE
Forward Proxy Continuous Release

### ISSUE THREAD

**Issue by barbarello** [department-of-veterans-affairs/va.gov-team#81841]
Ensure continuous release for the Forward Proxy mirrors that of the Reverse Proxy

**Comment by npeterson54** [comment]
Removing from sprint due to https://app.zenhub.com/workspaces/platform-infrastructure-services-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/81841 which needed to be done first

**Comment by npeterson54** [comment]
Rolling into next sprint

**Comment by npeterson54** [comment]
This will roll over into next sprint due to some higher complexity issues coming up within the story

**Comment by ph-One** [comment]
Pulling from sprint, as assignee was on Support

**Comment by barbarello** [comment]
closing.
we are now in the 'live traffic' phase for fwdproxy
