### ISSUE TITLE
Scheduled downtime for Elasticache production upgrade 

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8184]
Following a discussion on the va-eng-leads Slack channel and this document:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/scheduled-downtime-process.md

# Proposed downtime for vets-api

Systems affected: vets-api (effectively nearly all services, since redis stores authentication, caches other data)
Proposed date and time for staging: N/A -- staging is already running Redis v5
Proposed date and time for production: Saturday 4/25/2020 from 9:00 PM to 9:02 PM (approximately)

Time is honestly anytime in our Saturday "preapproved" window, but assuming we'll aim for around 9PM Eastern.

Additional steps:

- [x] Make an announcement at engineering meeting on Tu 4/21
- [x] Make an announcement in #vfs-all-teams in Slack on Th 4/23
- [ ] Make an announcement in #vfs-all-teams in Slack on Fr 4/24

**Comment by drorva** [comment]
Approved.

**Comment by johnpaulashenfelter** [comment]
The various folks on PagerDuty schedules for this time period:

* VSP oncall: @U-DON 
* Devops oncall: @nathanhruby 
* Incident commander: @gunsch 

Also mentioned to them in Slack. This is mostly an "inform" step unless @nathanhruby is assigned the execution.

**Comment by johnpaulashenfelter** [comment]
Draft plan:

# Redis migration
## Sign into AWS Console
[Amazon Web Services Sign-In](https://signin.amazonaws-us-gov.com/oauth?response_type=code&client_id=arn%3Aaws-us-gov%3Aiam%3A%3A464433863101%3Auser%2Fhomepage&redirect_uri=https%3A%2F%2Fconsole.amazonaws-us-gov.com%2Fconsole%2Fhome%3Fstate%3DhashArgs%2523%26isauthcode%3Dtrue&forceMobileLayout=0&forceMobileApp=0)

## Scale worker ASG to zero
https://console.amazonaws-us-gov.com/ec2/autoscaling/home?region=us-gov-west-1#AutoScalingGroups:view=details

Choose worker
Choose Edit
Desired capacity and min to **0**
Save
(Wait)

## Backup redis
https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#redis:

Choose **dsva-vetsgov-prod**
Choose Actions > Backup
(Wait)


## Upgrade redis engine
Still on page (https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#redis:)

Choose Actions > Modify
Choose Engine Version > **5.0.6**
(Wait

## Scale worker ASG back up
https://console.amazonaws-us-gov.com/ec2/autoscaling/home?region=us-gov-west-1#AutoScalingGroups:view=details

Choose worker
Choose Edit
Desired capacity and min to **4**
Save
(Wait)

**Comment by johnpaulashenfelter** [comment]
Current environments

Prod
redis: “dsva-vetsgov-prod.eqe4uk.ng.0001.usgw1.cache.amazonaws.com”
version: 3.2.4
vpc: old

Dev
redis: “dsva-vetsgov-dev.eqe4uk.ng.0001.usgw1.cache.amazonaws.com”
version: 5.0.6
vpc: old

Sandbox
redis: “dsva-vagov sandbox.eqe4uk.ng.0001.usgw1.cache.amazonaws.com”
version: 5.0.6
vpc: VAEC

Staging
redis: “dsva-vagov-staging.eqe4uk.ng.0001.usgw1.cache.amazonaws.com”
version: 5.0.5
vpc: VAEC

Future migration

* dsva-vagov-dev
* dsva-vagov-prod

Unused
	
* dsva-vetsgov-stag

**Comment by johnpaulashenfelter** [comment]
Successful migration completed as expected.
