### ISSUE TITLE
Figma access request Nicole Kontrabecki

### ISSUE THREAD

**Issue by nkontrabecki** [department-of-veterans-affairs/va.gov-team#81840]
### Name

Nicole Kontrabecki

### Email

nicole.kontrabecki@va.gov

### Role

Project Manager

### Team

Transition Experience

### Product Manager (PM) name

Gene Dreyband

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to nicole.kontrabecki@va.gov.

**Comment by nkontrabecki** [comment]
I have not received the invite yet.

**Comment by naomimarcussen** [comment]
That's strange. An account has been created with [nicole.kontrabecki@va.gov](mailto:nicole.kontrabecki@va.gov).

**Comment by nkontrabecki** [comment]
this is the message I get when I click sign in with SSO.

<img width="280" alt="SSO Figma" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/155753788/71b37d7b-3206-4961-b6ff-e43f16cee0af">

**Comment by naomimarcussen** [comment]
Your account doesn't work with SSO. You'll need to log in with your email and password. Hope this helps.
