### ISSUE TITLE
[FE] My VA Forms Status: Create new FE technical documentation for Benefit Apps section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81857]
## Background
We maintain FE documentation for implementation purposes, but we also need to maintain documentation that explains "how the page works" - i.e. how do forms appear there, are there specific configurations etc. TBD on whether this should be a section within the FE documentation or its own separate document in github.

## Tasks
- [x] Create technical documentation that outlines how this section works (both draft and form status work)

## Acceptance Criteria
- [x] We have technical documentation explaining how the section functions

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Review documentation

**Comment by allisonlu** [comment]
@DanielMiller-agile6 @mattmarino-adhoc 

ready for validation! check it out:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/frontend/benefit-applications-and-forms.md

**Comment by DanielMiller-agile6** [comment]
looks good to me 👍

**Comment by ACParker89** [comment]
@allisonlu does this need to roll into 49?
