### ISSUE TITLE
Accessibility Testing for Accredited Representation Management, Representative Status Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81867]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

oddball-lindsay

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [X] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

We are using the design system components and everything is looking good for all Representative Status Widget states.

### Who completed the axe scans?

oddball-lindsay

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### How did axe testing go?

No issues reported for all Representative Status Widget states.

### Who completed the content zoom and reflow test?

oddball-lindsay

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

Everything is looking good for all Representative Status Widget states.

### Who completed the keyboard navigation test?

oddball-lindsay

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Everything is looking good for all Representative Status Widget states.

**Comment by oddball-lindsay** [comment]
@briandeconinck I was keeping track of this along with our Staging Review.  Now that Staging Review has past, is it time to close this out?

**Comment by briandeconinck** [comment]
Yep -- totally fine to close this out!
