### ISSUE TITLE
CF: Add closed schools to search results caution flag filter

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8187]
As a comparison tool user, I need closing/closed schools to be excluded from the search results when I use the caution filter so that I am only viewing schools with no potential problems.

## Assumptions:
1. This work is completed behind a toggle so that it is only available in the staging environments and below.
2. The [interactive prototype](https://bahdigital.invisionapp.com/share/ZAIADJGP9QT#/screens)  is for UI/Layout reference but is overruled by supporting artifact # 2.

## Acceptance Criteria
1. The "Cautionary warnings" filter header is replaced with:
    > Warnings and school closings

2. The "Exclude institutions with warnings" filter text is replaced with:
    > Exclude results with warnings or closings

3. The filter Learn More modal content is the following:

    > **Cautionary warnings and school closings**
    > 
    > VA applies caution flags when we, or another federal agency, have increased regulatory or legal scrutiny of an educational program. We recommend students consider these warnings before enrolling in flagged programs.
    > 
    > When VA receives notice that a school or campus location will be closing, we add a school closing flag to that profile. Once the closing date passes, we remove the institution from the Comparison Tool during the next system update.
    > 
    > To learn more about caution flags, [visit the About this Tool page](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#CF).

4. When the user selects the filter, institutions with either caution flags OR a school closing flag are excluded from the search results.

## Supporting Artifacts:
1. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/1a79b78c093d5d897268fa262abb3ce23ede4b4f/products/education-careers/school-comparison-tool/caution-flags/content/content-doc.md)
2. Filter Mockup:
<img width="1002" alt="8187" src="https://user-images.githubusercontent.com/48260534/79875494-bc528580-83b7-11ea-9ebc-be79b6c1e40a.png">

**Comment by hughes-dustin** [comment]
vets-website:
 Branch: bah-8187
 PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12344

GIDS:
 Branch: babh-8187
 PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/648

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-27 at 11.31.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/df0c9def-7b1c-403d-9b9f-7af8f6d937b5)
##
![Screen Shot 2020-04-27 at 11.31.46 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2eafba9b-de82-44b1-8037-b9bcdd1e461d)
##
![Screen Shot 2020-04-27 at 11.32.12 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9006f66a-a01b-4f9d-99fa-fd86d120d554)
##
![Screen Shot 2020-04-27 at 11.32.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/93f5c332-864e-47f2-96ce-ea8d8d98e350)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/322&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
Not in production build.

**Comment by sonntag-adam** [comment]
In staging, closing story.
