### ISSUE TITLE
[BE] Appointments Controller: merge clinics

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#81883]
For each appointment, merge the clinics data by calling the get_clinic method in Facility Service

Tasks:
- in appointments controller, once appointments are retrieved, iterate through each appointment and fetch clinics by facilities
- merge and serialize the response

**Comment by loripusey** [comment]
@randomsync @kanchanasuriya How much work is left on this one?
cc: @anita-halici
