### ISSUE TITLE
Unit tests: Frontend

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#81888]
## Description
We're at a [lower-than-ideal coverage percentage for our front end tests](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/). We need [at least 80% unit test coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-VA.govQAStandards) to not be gated for a production launch.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c5f424b79efeb9f301499bf3e20277fbea57119/image.png" alt="image.png" />

## Acceptance Criteria
Run `yarn test:coverage-app travel-pay` to ensure:
- [ ] Statements coverage >= 80%
- [ ] Branches coverage >= 80%
- [ ] Functions coverage >= 80%
- [ ] Lines coverage >= 80%

## Demo
- Demoable? Yes
- How? Show Either the [QA standards coverage page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/), or the standalone results page from the terminal command: `yarn test:coverage-app travel-pay`.
- Impact? Shows importance of quality; compliance with QA standards; preparation for launch

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by hinzed1127** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29817#pullrequestreview-2059374514
