### ISSUE TITLE
Add port 9292 access to SOCKS firewall

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8189]
To help support https://github.com/department-of-veterans-affairs/vets-api/pull/4158, there needs to be a way to access port 9292 through the SOCKS firewall for engineers with a need to use the Sidekiq UI.

The port is configurable and 9292 is the default for puma, so it can be changed if necessary. This is a sort of well-known-port for rubyists at least, so likely OK.

The goal here is that a server that is running the Sidekiq web ui can be reached *only* on the socks proxy and only through this port.

**Comment by jbritt1** [comment]
New sg/rules were created in https://github.com/department-of-veterans-affairs/devops/pull/6801. Today's automated deploy should grab the new rule, leaving this open until after that is verified.

**Comment by johnpaulashenfelter** [comment]
Doesn't work, replaced with `aws ssm start-session --target <INSTANCE_ID> --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["3004"],"localPortNumber":["3000"]}'`
