### ISSUE TITLE
Design Intent - IA Feedback - Disability Benefits Experience Team 2, Disability Comp Application (21-526 EZ), Updated 0781 Flow

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#81907]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thank you for working on this very important project! It isn't easy subject matter and I appreciate all the emotional labor y'all are doing. 
- The flow you've presented here is a big improvement from the existing flow.
- You asked about the flow for evidence upload for 781. I agree that keeping this file upload immediately adjacent to the questions about it will allow folks to complete this stressful portion of the form as one discrete task, and give them the certainty that they can upload supporting documentation right away rather than needing to wait til the end of the form.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Should: explain why information is being requested and how it will help** The new designs are already doing this - _and_, wherever possible, there should be information included about why questions are being asked so that folks understand how their responses will be used, as well as how they will **not** be used. "We're asking you this so we can support you, not because you have to prove to us that what you're experiencing is real."
- [x] **Consider: survivor-affirming language on 'Was an official report filed?' screen** Sexual violence in particular often goes unreported. While asking survivors for details of their experience it could be worthwhile to note that _It is totally acceptable if no report was filed, and this information is not required to process your application._ The trauma-informed design community might be a good resource for this.
- [x] **Consider: content/supporting flows for scenarios that might not fit an "Event type" neatly** What might Veterans with these experiences need when using this form? Which checkboxes would they select? What content in the example text might help them?
  - Mental/verbal/emotional abuse or coersion (not physical harm)
  - Intimate partner violence
  - [CPTSD](https://my.clevelandclinic.org/health/diseases/24881-cptsd-complex-ptsd) and/or pervasive, hostile environments that do not have a single event
  - Sexual harassment that includes homophobia or transphobia

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by jinaryu** [comment]
- Added "why we ask this" where applicable
- Added survivor-affirming language to [official report page](https://www.figma.com/file/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?type=design&node-id=2296%3A13775&mode=design&t=1pcRPmO9Q3HrWEue-1)
- Added supporting content to ["event type" page](https://www.figma.com/file/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?type=design&node-id=2127%3A4617&mode=design&t=1pcRPmO9Q3HrWEue-1)
