### ISSUE TITLE
Update VFS onboarding process to include creating a Sentry team

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8190]
As part of the onboarding process, each VFS team needs a corresponding Sentry team so errors/notifications can be properly routed.

This means updating the onboarding process on the Support team side, and making sure we have relevant docs on the BE Tools team side.

This issue tracks any of the steps to make that happen.

**Comment by LindseySaari** [comment]
[VSP facing doc for how to manage sentry for the platform](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/backend/vsp-sentry-configuration.md)

**Comment by alexpappasoddball** [comment]
I talked to Andrea H. about this earlier this week.  There isn't necessarily a step in the orientation process where they can check this box.  From what I can tell, the best place to ensure this is done is through the security + privacy review which is conducted by Andrew G.  

I setup a meeting with Andrea and her team to walk us through the orientation process so we all have the same understanding of the process.  I'm going going to talk to Andrew in my next 1:1 on how to implement it during the security and review checkpoint.

**Comment by alexpappasoddball** [comment]
Moving this to the backlog until Sentry 10 is deployed and our documentation is current to the latest version and we have all the pieces in place before enforcement required.

**Comment by erluti** [comment]
Documentation exists here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-configuration.md
