### ISSUE TITLE
VistA facilities: create service scaffolding and data mapping code

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#8191]
We need to convert the var-resources data into the FHIR format that we'll be getting from EAS/VSP.

Do not update the application to use this service code, outside of unit tests.

Current service: /vaos/systems/983/direct_scheduling_facilities
New resource: /Location

AC:
- [ ] Service for the new resource has been created, if it doesn't already exist
- [ ] Service code is written to call current API function for service
- [ ] Errors are mapped to OperationOutcome format
- [ ] Successful service response is mapped to FHIR format
- [ ] Any data that is needed but has no place in FHIR structure is put inside a `legacyVAR` property
- [ ] Unit tests are written for new service and mapping code
- [ ] Create tickets where you were not able to map to the FHIR structure and/or other outstanding needs/issues

**Comment by lenaecb** [comment]
Reference to example implementation - https://github.com/department-of-veterans-affairs/vets-website/pull/12268
