### ISSUE TITLE
Mock wellHive Appointment endpoints

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81913]
## Tasks

- [x] Create FE mocks based on WellHive API swagger in order to prototype the process of pulling providers and their availability, displaying them on the FE for Veterans, confirming an appointment, and then sending that confirmation back to WellHive
- [x] Mock wellHive Appointment endpoints.

**Comment by benbrasso-agile6** [comment]
@simiadebowale are the AC's the potential tickets we should break out? If so, I can help create the tickets we need.

**Comment by simiadebowale** [comment]
@benbrasso-agile6 - yes, thank you!

**Comment by benbrasso-agile6** [comment]
k on it

**Comment by benbrasso-agile6** [comment]
So, do we want to validate this one mock? Or is there not a way to validate with @lee-delarm6 ?

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 is PR reviewed and validated? Rdy to close this ticket?

**Comment by simiadebowale** [comment]
yes @benbrasso-agile6

**Comment by lee-delarm6** [comment]
Yep
