### ISSUE TITLE
Create automated solution for patching vulnerable dependencies

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#81917]
## Issue Description. 
(Notes from Discussion TO BE EDITED)
- Image scanning - does scanning on image push
- Scans work on image push, but they need to do auto patching 
- Figure out auto strategy - create TICKET for it
- Will need to have that be moved into K8S stack
- 2 Sides of patching for applications 
- Internal libraries - raises 2.3.3 for ex, if security vulnerabilities 
- OS packages - updated them ex: ubuntu 20.20
- What makes this difficult is that some services don’t get picked up
- Some applications don’t get picked up until their running
- Some are in the manifests
- App files and OS files, running version and non-running version
- When running: java: latest, you won’t know what version is running. 
- Java latest was from 2 days ago
- For this app, it probably doesn’t matter
- For logic based package selection
- Feed in results from AWAS image scanning into automated patching

**Comment by vidjovanovic** [comment]
Have workflow to yum update and reduce what vulnerabilities we can in an automated way.

**Comment by parkerbees** [comment]
@vidjovanovic it looks like this was moved to Current Sprint a few weeks ago. Is the intent to work on this in the current sprint (before July 17) or should this be moved to backlog? Thanks.

**Comment by parkerbees** [comment]
Copied to Jira; closing.
