### ISSUE TITLE
Flipper UI access for Dan Hinze

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#81914]
### Your Name

Dan Hinze

### Your GitHub handle (Flipper UI access is managed through GitHub)

@hinzed1127

### Team, Role, and Company of the target individual

Beneficiary Travel Team, Sr. Software Engineer, Ad Hoc

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
verified in Atlas
E-QIP [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77484)

**Comment by bdech** [comment]
@hinzed1127 You've been granted access to Flipper lower environments.
