### ISSUE TITLE
Adding Brandon Cooper to DSVA Slack

### ISSUE THREAD

**Issue by emily-brown34** [department-of-veterans-affairs/va.gov-team#81920]
Please add Brandon Cooper as a full member to the following channels. He is a software engineer working on the Health Enrollment (10-10 Health Apps) team.

Email: brandon.cooper@adhocteam.us

Channels:
-  1010-health-apps
-  health-tools-1010-apm
-  vfs-change-announcements
-  vfs-platform-support
-  vfs-all-teams
-  feedback-backchannel

**Comment by hdjustice** [comment]
Hello!  This ticket has been open for a few days, any way we can get Brandon added?
