### ISSUE TITLE
Add Feature Toggle

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#81935]
#### Description
Implement a feature toggle for vets-website and vets-api to enable/disable the Income and Asset form application in the production environment. This task involves adding a toggle switch that can be controlled externally to disable the application when necessary.

#### Documentation
[VA Platform - Feature Toggles Guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

#### Acceptance Criteria
- [ ] Implement a custom feature toggle within the application codebase to show/hide the application on vets-website
- [ ] Ensure the feature toggle can be controlled in each environment (Dev, Stage, and Production)
- [ ] Verify that the feature toggle effectively disables the Income and Asset form application when toggled off
- [ ] Include appropriate error handling and messaging to inform users when the application is disabled.
- [ ] Test the feature toggle functionality in the development, staging, and production environments to ensure consistency.

#### Definition of Done
- The feature toggle mechanism is successfully implemented within the Income and Asset form application.
- The feature toggle can be controlled externally to enable/disable the application.
- The Income and Asset form application is properly disabled in the production environment when the feature toggle is turned off.
- Error handling and messaging are implemented to inform users when the application is disabled.
- The feature toggle functionality is thoroughly tested in various environments to ensure reliability and consistency.

#### Related Issues
N/A

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81935?planning-poker) with Zenhub @danlim715 @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by wayne-weibel** [comment]
<img width="1301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0x2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e83204579285ac8ad87b73a624a34c814acbfd3/image.png" alt="image.png" />
