### ISSUE TITLE
Generate new vets-website application

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#81941]
#### Description
Create the initial structure and setup for the Income and Asset form application using the Yeoman application generator for vets-website. This task involves setting up the basic project structure, configuring dependencies, and ensuring seamless integration with the existing vets-website infrastructure.

#### Documentation
[VA Platform - Creating a new application](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application)

#### Acceptance Criteria
- [x] Run Yeoman application generator for vets-website to scaffold the Income and Asset form application.
- [x] Verify that the generated application structure aligns with project requirements and best practices.
- [x] Ensure proper configuration of dependencies, including any necessary plugins or libraries.
- [ ] ~~Integrate Typescript for improved type safety and code maintainability.~~
- [x] Integrate the generated application with the vets-website infrastructure, including authentication, authorization, and data storage.
- [x] Confirm that the generated application can be successfully built and deployed within the vets-website environment.
- [ ] Document the setup process and any configuration steps for future reference.

#### Definition of Done
- The Income and Asset form application is successfully generated using the Yeoman application generator for vets-website.
- Typescript is integrated into the project for improved type safety and code maintainability.
- The generated application is properly configured and integrated with the vets-website infrastructure.
- Documentation is updated to include setup instructions and configuration details.

#### Related Issues:
N/A

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81941?planning-poker) with Zenhub @danlim715 @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel
