### ISSUE TITLE
Adopt Sidekiq guidelines for the Pension application

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#81989]
Steve Albers wrote up an[ Architectural Decision Record](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/architectural-decision-records/sidekiq-guidance.md) addressing Sidekiq guidelines for the Benefits team. 
We should audit and update sidekiq jobs in Pension application to conform to the guidelines. 

- [ ] Review the document and provide feedback
- [ ] Audit all Pension sidekiq jobs and document limitations and nonconformance per each job
- [ ] Depending on the scope of findings, update the code as needed and/or, create separate tickets for major work

**Comment by mjknight50** [comment]
Moving as @sanjabaj2 requested

**Comment by sanjabaj2** [comment]
> [Sideqik Job Audit for Pensions Related Code.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35537520e4432361ccebc51b84294b2d6ba8ebbd/Sideqik%20Job%20Audit%20for%20Pensions%20Related%20Code.pdf)

For some reason I can't access the attachment. Get 404 error. I am not on VPN, if that makes any difference.

**Comment by sanjabaj2** [comment]
File Permission Denied
Looks like you don't have access to this file, please ensure you are part of the Zenhub Organization that the file belongs to or contact your administrator.


From: Scott ***@***.***>
Sent: Friday, May 17, 2024 8:10 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Bajovic, Sanja ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adopt Sidekiq guidelines for the Pension application (Issue #81989)


Sideqik Job Audit for Pensions Related Code.pdf<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlR3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82afc79e98a28cc9024a088b90a2691e78bed933/Sideqik%20Job%20Audit%20for%20Pensions%20Related%20Code.pdf>

**Comment by sanjabaj2** [comment]
> [Sideqik Job Audit for Pensions Related Code.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlR3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82afc79e98a28cc9024a088b90a2691e78bed933/Sideqik%20Job%20Audit%20for%20Pensions%20Related%20Code.pdf)

File Permission Denied
Looks like you don't have access to this file, please ensure you are part of the Zenhub Organization that the file belongs to or contact your administrator.

**Comment by mjknight50** [comment]
[Sideqik Job Audit for Pensions Related Code.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/15353840/Sideqik.Job.Audit.for.Pensions.Related.Code.pdf)

**Comment by aplatt-coforma** [comment]
@sanjabaj2 - just uploaded to our Google Drive and shared the link with you. https://drive.google.com/file/d/1G4c1E4IVDmBS1CETxdoYwkxexw57MJ6t/view?usp=sharing

**Comment by wayne-weibel** [comment]
After discussion this morning, we will be creating 3 - 4 followup tickets to address the findings (none need immediate attention):
- idempotent and transactional
- document process for resubmission (manual)
- automated resubmission
- user facing submission confirmation

**Comment by sanjabaj2** [comment]
Just added a comment to the Google doc regarding sidekiq jobs that we believe are not our responsibility. Do we know who those teams are? Can you add names to the document if you know it.

**Comment by aplatt-coforma** [comment]
Added links to the 4 followup tickets that the team created.

**Comment by wayne-weibel** [comment]
https://dsva.slack.com/archives/CTXGRFUNN/p1716306145434949
