### ISSUE TITLE
Toxic exposure: otherLocationsServed and specifyOtherExposures input fields - revise error message for character input

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#81986]
## Overview
Provide guidance for FE error validation feedback for the other locations and other exposures fields
<img width="505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekNuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1505a15657335794f7bc4cafc42d7ca4248b78a9/image.png" alt="image.png" />

Questions to answer
1. What error message should we display to the Veteran when the input string does not pass Lighthouse's validation regex?

Some considerations
- LH's regex for these two fields has been updated to `^([-a-zA-Z0-9'.,&# ])+$`
- [Here's a tool](https://regex101.com/r/qLulYv/1) for trying out the regex with different test values. Some examples of failures are chars that are not alpha numeric or `'`, `.`, `,`, `&`, `#`, or spaces

<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--613d87d5142df356e5bbd7881b7d7c26855c0713/image.png" alt="image.png" />

<img width="491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelduQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c53e1bd05442098f4ed129e10efa8014d4c4486e/image.png" alt="image.png" />

- If we do not provide a custom error message, this is an example of the default error message
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--435677b54c37c60436ee27478272150ae69a1bf3/image.png" alt="image.png" />

## Acceptance Criteria
- [ ] new, human-readable error message design shared with stakeholders for visibility
- [ ] new error message design ready for implementation

**Comment by christinec-fftc** [comment]
Some other considerations
<img width="1451" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--192af2540a873ec2c474bbe3e74b8edf45e218ef/image.png" alt="image.png" />

**Comment by alatempa24** [comment]
Refinement 5/7/24:
Decision:
- Build for MVP: target 250 char visual with expanded vertical box to prevent horizontal scrolling, lean to smaller box
- Post-MVP research can iterate on text input size

**Comment by alatempa24** [comment]
recommendation and decision in this DSVA [slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1715797541344699).

> Since the hint text for max characters does not appear until the input reaches the max, we thought it might be good to add the max # of chars to the label, similar to what is on the add disabilities follow up pages.

**Comment by alatempa24** [comment]
still need to decide: if we want to update the error message to the Veteran when the input string does not pass Lighthouse's validation regex (screenshot above): as MVP or post-MVP enhancement.
Considerations: changing the message is trivial from engineering perspective but if there is a dependency on CAIA for language it could impact delivery speed.
