### ISSUE TITLE
Wording on forms - Form documentation on design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#82]
This could be general guidance on how to design forms, so not necessary about UI documentation. 

Can I edit the wording of a question?
- Sometimes. Certain benefit applications have specific terms that MUST appear in the question. Most questions can be rephrased in plain language. Review a form field by field with your stakeholder to understand how fields are used and understand how specific language is used.

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by peggygannon** [comment]
This issue is old and I've been documenting form wording and labels in this issue. (https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/5583)

As such, I'd like to close this one and track work in #5583.
