### ISSUE TITLE
CT-103: Remove 'eduSection103' Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8201]
As a developer, I need to remove the feature flag for the Section 103 content because it will not be disabled going forward.

## Assumptions:
1. The feature flag was configured as part of story #7773.
2. This functionality has been reviewed by UX as of 2020-05-14.
3. This functionality has gone through UAT with EDU and been signed off on as of 2020-05-20.
4. This functionality has been turned on as of 06/04 and no issues have been encountered.

## Acceptance Criteria:
1. The feature flag 'eduSection103' is not displayed here: https://[environment]-api.va.gov/flipper/features.
2. The Section 103 content on the profile page is still displayed per stories:
     a. #7843 
     b. #8095 
     c. #8313 
     d. #9190 
     e. #9283

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4339
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/660
https://github.com/department-of-veterans-affairs/vets-website/pull/12838

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
In staging, waiting for prod deploy for prod https://api.va.gov/flipper/features

**Comment by sonntag-adam** [comment]
Feature flag removed from production and functionality remains. Testing passes QA.
