### ISSUE TITLE
10-7959c: staging/prod urls 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82026]
As a VA.gov user, I want to be able to enter the 10-7959c form urls into the browser so that I can go directly to the online form.

URLs for staging and prod for form 10-7959c should follow CAIA guidance:

Teams can choose their own sub-urls, or get help from CAIA in choosing them or vetting them.
Note some standard sub-urls:
/introduction: use on the first page of the actual form (not the static page in drupal)
/review OR /review-and-submit: use for review steps in forms or tools
/confirmation: use for the confirmation page after form submission
Subtask URL slugs should be short, plain language, and drawn from the H1 if possible.
Reminder: Don’t create unnecessary or empty subdirectories when creating sub-URLs

base url: va.gov/health-care/champva/other-insurance-form-10-7959c/

(See attached spreadsheet for final URLs).

**Comment by michaelclement** [comment]
Here are the existing URLs in a spreadsheet along with comments and a space to add the new URLs. I figured this would be a lot easier to deal with than ZenHub's markdown for making tables.

You should be able to just open this up in Excel locally, or drag and drop it into Google Sheets.

[10-7959c OHI - URLS.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83880faace0fa7d8135aa470e8f4e543ba090fa3/10-7959c%20OHI%20-%20URLS.xlsx)

**Comment by marywang2** [comment]
@michaelclement I've attached the file with urls, let me know if they make sense (and/or if there are better ones we should use). Thanks! [10-7959c OHI - URLS_filled.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmpFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a389fcbf444c58461c12aa87f58a87f50b8bb2a/10-7959c%20OHI%20-%20URLS_filled.xlsx)

**Comment by marywang2** [comment]
[10-7959c OHI - URLS_filled_edited_513.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc41382dcc046b4819b25b0cf81d2c2ae3b910ba/10-7959c%20OHI%20-%20URLS_filled_edited_513.xlsx) - latest spreadsheet with updated urls.

**Comment by michaelclement** [comment]
URL's have been updated in these PRs ([vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/29759) and [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/2083)).

Waiting on:
vets-website PR
- [ ] Team approval
- [ ] Platform approval
content-build PR
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 new URLs [are live on staging](https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c) - this is ready for you to take a look at. Thanks!

**Comment by michaelclement** [comment]
I would say we go ahead and make a different ticket for that issue

**Comment by marywang2** [comment]
Tracking the other ticket [here](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/83567).
