### ISSUE TITLE
10-10d, OHI Documentation: Add latest versions of PDFs to Github for reference

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82020]
As a product owner, I want to see locally generated and completed PDFs on Github for any forms that have been worked on so I can easily reference them in one place rather than in separate tickets.

Add PDFs to their respective folders on Github (feel free to drop in main folder or create an engineering sub folder):

- [10-10d](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/champva/1010D)
- [OHI](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/champva/10-7959c)

Acceptance criteria:
- most recent version of form is used/generated
- metadata is included
- PDF is completed with fake user data in form fields
- the date/time stamp for the signature and auth level is displayed following [guidance](https://design.va.gov/patterns/ask-users-for/signature) 
- show what happens when there are multiple dependents

**Comment by marywang2** [comment]
@cloudmagic80 I believe we need the generated PDF output rather than the PDFs of the forms themselves.

**Comment by marywang2** [comment]
@cloudmagic80 @baltes this needs to show a sample PDF that we generate (to show how we are putting the signature on it, etc).

**Comment by cloudmagic80** [comment]
@marywang2  1010D attached generated PDF are in this link: 
https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/ivc_champva/templates

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/84933

Here is the pull request

**Comment by baltes** [comment]
@cloudmagic80 Could you also include the pdfs as attachments here?
