### ISSUE TITLE
10-7959c unit tests

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82039]
As a user, I need the forms I use to have unit test coverage so that I can be confident developers aren't breaking existing functionality when they add new features.

_Context_:
Deployment to production requires unit test coverage of at least 80%. 

Acceptance criteria

- New unit tests added
- Unit test coverage report shows >= 80%
 
Non-technical testing instructions:
- Review the screenshots of the unit testing coverage reports (attached in comments section)

**Comment by michaelclement** [comment]
[PR is here](https://github.com/department-of-veterans-affairs/vets-website/pull/29613)

**Comment by michaelclement** [comment]
Work is done. Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2  Coverage reports:

## Before
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1787535178e1aabd450d4da510a2b4857ace89d/b.png" alt="b.png" />

## After
<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--128ca04d54757ffd0a99d4b030e8d019fdc441d0/after.png" alt="after.png" />
