### ISSUE TITLE
10-7959c: update copy - Intro 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82038]
As a user on VA.gov, I want to read about what is needed for the OHI form so that I can be informed before I start to fill it out.

- header and subhead
- footer
- breadcrumb (url: va.gov/family-and-caregiver-benefits/health-and-disability/champva) - not yet live
- Intro page 
  - intro copy
  - sign in box
  - respondent burden info
  - OMB control #
  - privacy act link

Figma link: https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Y8cWvTGeyw2lKO6X-0

Acceptance criteria:
  - Given the user is on VA.gov and about to fill out the OHI form
  - When the user gets to the intro page
  - Then the user can sign in or review the information before they start filling out the form

**Comment by michaelclement** [comment]
[Work is happening in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30102)

**Comment by michaelclement** [comment]
Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 This should be good to take a look at. Thanks!
