### ISSUE TITLE
[Content/UX] 10-10EZR Attach Docs: Content for Attaching Documentation

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#82044]
As a Veteran who was exposed to toxins in the Service, I would like to have a way to attach my old orders to my EZR so that the VA has all the information I can provide on my toxic exposure.

- [x] Provide Aliyah with content notes
- [x] Meet with Aliyah to collab and discuss
- [x] Collab with her PM if needed
- [x] Figma discourse 
- [x] **Success: Content has reviewed document attachment designs and has helped provide the clearest explanation for Veterans**

**Comment by emily-brown34** [comment]
Hieu to follow up/meet with Aliyah for content updates to the designs/doc upload
