### ISSUE TITLE
SOCKS access for Adrian Jones

### ISSUE THREAD

**Issue by ajshred** [department-of-veterans-affairs/va.gov-team#82052]
### Your Name

Adrian Jones

### Your Email

adrian.jones@adhocteam.us

### Your GitHub Handle

ajshred

### Your Role and Team

Engineering Lead on Team Quokka

### Product Manager (PM) name and email

Jesse House, jesse.house@adhocteam.us

### Product Owner (PO) name and email

Peter Tebbenhoff, peter.tebbenhoff@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnUkxA4PcGF186Q18xxYuhLtXEC5Rc4/cJHIr9ZueeirRz4P8DbAdu4XvPpcvXKoQZdXZRy4Ill9POFRCYL7cxCT4yb4PauFlWJxZNBRSLXf/t0enT0Ap19X6CnaDg12XO5sZxK63uqjIX43AqnY0egqyIs7nzMIjMDpv/fYJijw792p6IJTQPHO93kcU2nsfMmo/c+csTiMeXIi2m9+CHjRhfwxrqFWtSOt4O4kt/0ZE4lI6E9ADpm23j0BOVr0NsmMbvAwvKdnkWfpayh7A+PUgeW961Hl+EMip/x0A/0jy6N+4GHX4m7NBGcEKOavV3THmFhophGJtcekimICWwlGnA0dVSk5zkXHGi/Ngaqmyl9pSwtlkaF27SD/gMJm2+a4fBg46LTjfkE05Fmql0H58mib3MXDChoibZ+aTh3c9KndThrvrGTUyBWtKv7clp7pcHlA8jQW7VflF1BDWnQekuW+5yJhhcWwTq6VQoVbOy8Yn3ZxNNdvQFwj8a+fs= ajones@ajones-HP-ProBook-445-G8-Notebook-PC

### E-QIP Transmittal Confirmation

![Screenshot from 2024-05-01 13-07-58](https://github.com/department-of-veterans-affairs/va.gov-team/assets/84713593/36c1ac7f-0cb4-454e-96aa-ca40913d5d06)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@ajshred I was unable to find you in Atlas or the Platform Roster and cannot proceed with this. Please coordinate with you COR and/or PM to get you added there.

**Comment by ajshred** [comment]
I've been added in Atlas now.

**Comment by jhouse-solvd** [comment]
@flooose - Adrian has been added to Atlas, and the auto-PR has kicked off. Can you let us know what's next? Please tag @ajshred with the next steps. Thank you!

**Comment by ajshred** [comment]
I don't see an option to re-open.  Please advise.

**Comment by flooose** [comment]
You can open a support ticket for this. Everything should be in place at this point. There's a devops person in support rotation at all times and they should be able to help diagnose and troubleshoot.
