### ISSUE TITLE
[BE] 10-10EZR Attach Docs: Discovery--Backend documentation and investigation for Attaching Documentation

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#82058]
As a Veteran who was exposed to toxins in the Service, I would like to have a way to attach my old orders to my EZR so that the VA has all the information I can provide on my toxic exposure.

- [x] Will VES have a separate TERA attachments table?
- [x] How does VES store these? Do they need us to make any clarifications around the file type?
- [x] What file types does VES accept?
- [x] Can we receive previously uploaded documents? Does EZ currently do this?
- [x] Do documents save in progress? (does EZ do this?)
- [x] **Success: Document file types, size, and follow along with the attachment issues with EZ/CG**

Already done: User can attach a document and it is sent to and stored in VES*

**Comment by alexseelig** [comment]
# ES only accepts these strings for 'va:format': PDF,WORD,JPG,RTF

**Comment by JoshingYou1** [comment]
We can only receive documents if the form is an in-progress form. It behaves the same way as the 10-10EZ

**Comment by JoshingYou1** [comment]
There will not a be a separate TERA attachments table
