### ISSUE TITLE
[Congressional] V11696777 Due 6/12/24 Congressman Burlison 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#82059]
## Issue Description
Veteran is trying to file a claim for hearing loss, but the website is not recognizing Veteran's name.

https://app.slack.com/client/T03FECE8V/C02BS78NYRM?selected_team_id=T1ZD0UBMZ&recommended_build_version=1713845250&build_manifest_last_modified=1713847809
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Sent email with details to Jeremy, EVSS Help Desk manager to confirm if they have any duplicate records for him.  Also BCC him on correspondence to the Veteran.

Sent email to Veteran asking for screenshots and which CSP he is using and if he is receiving the same issue with all of them when attempting to login.

Awaiting responses.

**Comment by Kimberley2023-CSM** [comment]
Jeremy messaged back indicating they have found a data mismatch and corrected the issue. 
JIRA ticket submitted ETSHD-2513.

I followed up with user indicating the issue has been found and the team that resolves it will reach out directly with instructions. I informed him he can follow up with a response if further assistance is required. 

Awaiting verification of resolved issue from EVSS team after contact and confirmation made with Veteran.

**Comment by Kimberley2023-CSM** [comment]
5/16/24:  Sent follow up email to Veteran inquiring if issues still persists.  Awaiting response.

5/16/24:  Sent follow up email to Jeremy asking for status update.  Awaiting response.
