### ISSUE TITLE
Update Medical records page with new info about Opt Out/Opt In buttons on MHV

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8205]
https://www.va.gov/health-care/get-medical-records/

Page was updated under # TBDTBD
We now have screen shot of easiest option, buttons on MHV, from Chris Johnston:

[MyHeatheVet Opt In and Opt Out buttons screen shot]
(https://app.zenhub.com/files/133843125/1cec81e2-119e-4a9b-9ec3-4147b6c4d607/download)
Email sent 4/21 to:
aliceli6@deloitte.com; VHADigitalMedia@va.gov; Jeffrey.Grandon@va.gov; Adrian.Osman@va.gov
pemarion@deloitte.com; Elizabeth.Meyer@dcgcommunications.com; Sabrina.Jacobs@va.gov; 

Asking to:
[x] 1. Verify these buttons exist on MHV
[ Not necessary] 2. Describe the path on MHV for Veterans to follow to use the buttons
[x] 3. Updated language to guide Veterans to just use the buttons on MHEV
[x] Stakeholders sent approved language. Our page is updated.
[x] Added info from Chris J. on checking opt in/out status.

@jenniferlee-dsva @DanielleThierryUSDSVA @stephorkandatx  FYSA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley. Did we hear back from SMEs around this? Just going through notes and checking in. Thanks!

**Comment by AnneHurley** [comment]
We haven't -I'll send another reminder tomorrow.

**Comment by DanielleThierryUSDSVA** [comment]
Okay, awesome. Thank you!

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  Got feedback from Alice Li, will make her changes.

**Comment by AnneHurley** [comment]
@RLHecht  Stakeholder updates are in and the page is ready for your review/publish. If you can think of a plainer way to say "Can I check my sharing preference status?" - those last 3 words seem like a bit of a mouthful. 

When the page is published I'll send the link out again to Alice et al. @DanielleThierryUSDSVA @stephorkandatx  FYSA

**Comment by AnneHurley** [comment]
@RLHecht  This is ready to be checked and pushed live whenever you have time.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate.FYSA @stephorkandatx
