### ISSUE TITLE
[FE] 10-10EZR Attach Docs: Build frontend flow for Attaching Documentation

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#82057]
As a Veteran who was exposed to toxins in the Service, I would like to have a way to attach my old orders to my EZR so that the VA has all the information I can provide on my toxic exposure.

- [x] Conditional on answering "Yes" to "Do you have TERA info?
- [x] Set up conditional toggle
- [x] Look into EZ/forms library attach document component
- [x] Add file upload page to form config
- [x] Add unit tests for page flow
- [x] Demo to team
- [x] **Success: We deliver a demoable frontend flow for Veterans to attach their documents to their EZR**

**Comment by allanto-ah** [comment]
Testing will be tracked in this ticket: [82062](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/82062)
