### ISSUE TITLE
Analytics Implementation or QA Support for Veteran Facing Forms - 21-0966 Intent to File

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#82068]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Veteran Facing Forms**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]

- **Product Name**

    - 21-0966 - Intent to File
      
- **When is the launch date?**
    - 4/3/2024

- **Provide the link(s) for Product/Page urls**
  **I put the staging URL - but this is for production - let me know if you need me to change it**

Here is a [Mural board](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/IntenttoFileWorkflow.png) that shows the different paths
- User can be a Veteran submitting on their own behalf - if we find an ICN # we hit the API and return the status of their Intent or create one on behalf of them
- Claimant
- Third party on behalf of a Veteran
- Third party on behalf of a Claimant

    - va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/introduction
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/preparer-identification
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/get-itf-status
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-benefit-selection
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-personal-information
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-identification-information
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-mailing-address
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-phone-and-email-address
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-veteran-personal-information
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/veteran-identification-information
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/surviving-dependent-relationship-to-veteran
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/review-and-submit
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/third-party-preparer-name
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/third-party-preparer-role
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/third-party-veteran-benefit-selection
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/veteran-personal-information
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/veteran-mailing-address
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/veteran-phone-and-email-address
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/third-party-surviving-dependent-benefit-selection
    - https://staging.va.gov/supporting-forms-for-claims/intent-to-file-form-21-0966/confirmation

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user](https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts/benefits_test_accounts.md)

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by Blivaditis** [comment]
Hi @tbaker1026 I have reviewed the submitted form funnel, I can confirm that base tracking appears on each page of the form. Here is a [GA4 explore report](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/9yF9VZNtTJmL9KvsYGruWQ) (non production) which shows the form events. If you are unable to access the report let me know.
