### ISSUE TITLE
10-7959f-2 - Veteran's Information page 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82067]
As a user on va.gov, I want to enter my information so that I can file my FMP claim (10-7959f-2).

[wireframes](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=726-21596&mode=design&t=ZWLOLAdfVxuqRAo5-0)

Acceptance criteria:
- display first name field (with entry required)
- display middle initial field (optional)
- display last name field (with entry required)
- suffix is selectable from dropdown (optional)
- date of birth is set to required
  - month is selectable from dropdown
  - date and year can be entered into date of birth fields
- data is pre filled if user is signed in
- user can go forward or back to previous pages
- include breadcrumb, form header, subhead text, progress indicator and footer

**Comment by reiting** [comment]
@marywang2 This is ready for review. The branch name is 10-7959f-2-veteran-info. It is currently in team review.

**Comment by reiting** [comment]
<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkx4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cef58b9dcf4af7abd56f1452e0e15446080100fa/Screenshot%202024-05-17%20at%202.46.59%E2%80%AFPM.png" alt="Screenshot 2024-05-17 at 2.46.59 PM.png" />
<img width="586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlB4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d946fa7946d17c315ec7f32d76747fd7b91a7b5/Screenshot%202024-05-17%20at%202.47.14%E2%80%AFPM.png" alt="Screenshot 2024-05-17 at 2.47.14 PM.png" />

**Comment by reiting** [comment]
Requested a platform review on this via the support channel.
