### ISSUE TITLE
10-7959f-2 - SSN and/or VA file number page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82069]
As a user on va.gov, I want to enter my SSN or my VA file number so that my identity can be verified when I go to file an FMP claim.

[wireframes](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=726-21596&mode=design&t=ZWLOLAdfVxuqRAo5-0)

Acceptance criteria:
- user can enter SSN into the field (with or without spaces or dashes)
- user can enter VA file number
- one or the other is required
- user can go forward or back to previous pages
- use v3 components

Build front end of the form using the forms-library

[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
In team review

**Comment by reiting** [comment]
In platform review now.

**Comment by reiting** [comment]
@marywang2 the branch is 10-7959f-2-ssn-page if you want to review
