### ISSUE TITLE
Adding Naomi Eke to DSVA Slack

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#82066]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

- Please add [naomi.eke@coforma.io](mailto:naomi.eke@coforma.io) as a full member joining the CAIA team under COR Pamela Jones and VA OCTO PO Danielle Thierry
- Please add [naomi.eke@coforma.io](mailto:naomi.eke@coforma.io) as a **FULL MEMBER** to
[#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH) and
[caia-team-internal](https://dsva.slack.com/archives/C03MP8MEPCN)

Are you requesting to add an individual as a:

- **Full member**
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Naomi Eke is from Coforma and will be joining the Sitewide CAIA Team as Delivery Lead.

We aim to complete slack requests within 24hrs.

**Comment by LEHigley** [comment]
@coforma-terry should they be added as a full member or multi channel guest? unclear from the above

**Comment by coforma-terry** [comment]
Hi @LEHigley - my apologies for the late reply - added as a full member please :)
Thanks!
