### ISSUE TITLE
[QA] 10-10EZR Attach Docs: QA for Attaching Documentation

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#82062]
As a Veteran who was exposed to toxins in the Service, I would like to have a way to attach my old orders to my EZR so that the VA has all the information I can provide on my toxic exposure.

- [x] Write test cases
- [x] Functional testing
- [x] Test save in progress where user uploads doc(s), saves their EZR, and comes back to it the attached doc is there
- [x] E2E testing with VES to make sure things are saved (including different file types)
- [x] **Success: User can attach a document and it is sent to and stored in VES**

**Comment by allanto-ah** [comment]
Environment: Staging

Testing has been completed for this feature. Once E2E is completed with VES, this ticket will be closed. We have already tested E2E before so we know that works, but wanted to run a couple more.

Test plan is attached here: [1010ezr-attach-docs-testrail.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHArQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0e618dddc86f794d9653649e62ca088a422df13/1010ezr-attach-docs-testrail.pdf)
