### ISSUE TITLE
10-7959f-2: Veteran Home address page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82073]
As a user on va.gov, I want to enter my address so that I can have my information associated with the claim I filed for the FMP program.

[wireframes](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=726-21596&mode=design&t=WkD8EY1rrT2jQsNa-0)

Acceptance criteria:
- country is selectable from dropdown (set to required)
- street address is text field (set to required)
- street address (additional lines) are text fields (optional)
- city (set to required)
- state is selectable from dropdown (set to required)
- zip code (set to required)
- data is prefilled when user is signed in
- use v3 components
- user can go forward or back to previous pages
- Street address line 2 and Street address line 3 should be displayed

Build front end of the form using the forms-library

[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
This has been completed and is in team review. <img width="563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e47ff0cc3781f8b7819c41af9b8bdf61b89f3860/Screenshot%202024-07-10%20at%202.02.32%E2%80%AFPM.png" alt="Screenshot 2024-07-10 at 2.02.32 PM.png" />

**Comment by reiting** [comment]
This was approved and merged. Should be on staging in a few hours, but going to wait until tomorrow morning to move to review, as I'm not sure if staging deployments stop at a certain time of day.

**Comment by reiting** [comment]
@marywang2 this was approved and merged and should be ready to be reviewed in staging now.
