### ISSUE TITLE
10-7959f-1 Increase test coverage - unit tests 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82080]
As a user, I want to make sure any issues are being flagged if there are any issues with the form I filled out.

Deployment to production requires unit test coverage of at least 80%. Create necessary unit tests for 10-7959f-1 to ensure adequate coverage.

Acceptance criteria
- Write new unit tests in vets-website for each page that test render, # of fields & error messages
- Unit test coverage report shows >= 80%

**Comment by reiting** [comment]
<img width="1896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNERMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a1f65d70d650dd6e570469f9364977824659e61/Screenshot%202024-05-09%20at%202.27.47%E2%80%AFPM.png" alt="Screenshot 2024-05-09 at 2.27.47 PM.png" />


This is in team review

**Comment by marywang2** [comment]
@reiting what is the % for statements (screenshot got a little cut off on the left)

**Comment by reiting** [comment]
@marywang2 this is done. <img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHJXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8c86e4da7b73bdc0ea6464b6b4a1cd20ec36fd7/Screenshot%202024-05-13%20at%2011.38.55%E2%80%AFAM.png" alt="Screenshot 2024-05-13 at 11.38.55 AM.png" />
