### ISSUE TITLE
Contact Center Review for [Disability Benefits Team 2 - Post-Submission Failure Emails]

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#82085]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
Post-Submission Failure Emails

The Post-Submission Failure emails will be sent to Veterans when a document fails after they submit their 526 claim. Documents that can fail are VA Form 0781, VA Form 0781a, VA Form 4142 and any form that the Veteran uploads with the claim. Currently, there is no notification to the Veterans that the documents have failed.

### Launch Date
*Please provide the launch or rollout date and details.*
This is a quick fix for a backend failure. We would like to roll out this product guide addition as soon as possible.

### Version Number
*Please provide the version number of the guide and/or video.*
These are new emails regarding an existing product.

### Product Guide
*Please provide product guide link*
See Major Issues and Error Message for the Post Submission Failure Email addition.  This is the only change to the product guide at this time.
[526.application.product.guide (1) (1) (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15180390/526.application.product.guide.1.1.1.docx)

### Product Video
*Please provide product video link*
No video is included.

### Product Video Transcript
*Please provide product video transcript link*
No video is included.

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by nnicholas7** [comment]
@juliepedtke @sortizsh

**Comment by nnicholas7** [comment]
A couple of additional notes for context:
- Our engineering team is working on implementing these emails and testing is forthcoming
- Once testing is underway we will be able to provide an example of the overflow text that will appear on the 526 PDF. The character limit cutoff for file names is still TBD pending our technical solution.
- We will also provide examples of the emails with the placeholder filled with mock user data (first name, file name, etc.)

We wanted to share what we have so that you can begin your review process and we will provide these additional materials as soon as possible.

Thanks

**Comment by starlow00** [comment]
@nnicholas7 , recent updates were addressed in https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/81747

**Comment by nnicholas7** [comment]
Hi @starlow00. I added our content to the template you provided and attached to this message. 
[NN Additions-VA Form 21-526EZ v3.1 product guide SRT 04292024.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15235675/NN.Additions-VA.Form.21-526EZ.v3.1.product.guide.SRT.04292024.docx)

I reviewed the Zenhub ticket above and I think that might be the wrong ticket for our team.  The ticket you posted above is about toxic exposure.

**Comment by starlow00** [comment]
Thank you, @nnicholas7. I think the way the issuing team wrote the ticket was confusing. However, the document plays. I'll take a look!

**Comment by starlow00** [comment]
Addition looks good. Sending to VEO for review.

**Comment by nnicholas7** [comment]
Thank you so much @starlow00. Look forward to next steps!

**Comment by starlow00** [comment]
No changes from VEO. I've attached the working copy for future additions and revisions. Thank you!
[VA.Form.21-526EZ.v3.2.product.guide.SRT.05072024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeExSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--337b08dd519d87f9bacc6a995e371dce979c8f69/VA.Form.21-526EZ.v3.2.product.guide.SRT.05072024.docx)

**Comment by nnicholas7** [comment]
Hi @starlow00 ! Thank you so much for the update and your help to get this into the product guide.

**Comment by juliepedtke** [comment]
Hi @starlow00 we're ready to make the aforementioned updates with a couple additional images explaining this solution. Is the working copy you attached still the most up-to-date guide that we should work from? 

Also, we learned that there is a separate product guide for the 526 BDD program. Could you share that guide as well? Updates will apply to both.

**Comment by juliepedtke** [comment]
Answered questions above via Slack - created new tickets for these updates.
