### ISSUE TITLE
Implement temporary medical records landing page 

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82081]
# Description
## User story

As a My HealtheVet user, I want to be told what to expect when I click "Records" in the secondary navigation menu, so that I am not surprised to navigate to another website and do not lose trust with the VA that the status of my medical records are unclear while the transition is still underway.

As a Cartographers team member, I want to communicate the current state of the My HealtheVet transition as transparently as possible to users, so that they know what to expect today and have clarity on what is coming soon. 

## Notes
- NOT a blocker for secondary nav staging review
- [Design in Figma](https://www.figma.com/file/HnaBQQwuyjxM7ycFrTCozl/TEMP---Medical-records-landing-page?type=design&node-id=50-11&mode=design&t=gy11M0baEZB8IiDQ-0), from #81734 
- Do we need to build a new app (at new url) or can we make it part of existing MR app?
- if a new app at new temp url, highlighting the MR link in secondary nav will require refactor of secondary nav
- est 5-8
- Q: @sterkenburgsara to inquire about URL options (which drive implementation decisions)
  - A: It has to be a new app outside the `/medical-records/` path, because that path is un-gated during their Ph0. [thread](https://agilesix.slack.com/archives/C05PH6V3MJL/p1714590460462179?thread_ts=1714588791.412429&cid=C05PH6V3MJL)
- Q: What is the new teamp url?
  - A: `va.gov/my-health/records`

## Acceptance criteria

- [x] Implement page (behind feature flag) at va.gov/my-health/records
- [x] Connect "records" link in My HealtheVet secondary nav to this temp page (behind feature flag)
- [x] "Records" link in secondary nav shows as selected on this page
- [x] QA
- [x] A11y review

**Comment by sterkenburgsara** [comment]
UX ticket moved to Q/A - work is ready for handoff to devs

**Comment by radavis** [comment]
Blocked. 
- Waiting on @department-of-veterans-affairs/va-platform-cop-frontend to review department-of-veterans-affairs/vets-website#29583
- Waiting on @department-of-veterans-affairs/teams/backend-review-group to re-review department-of-veterans-affairs/vets-api#16640

**Comment by radavis** [comment]
Now, blocked by js build OOM errors: https://dsva.slack.com/archives/C04868KS69L/p1715188176792509

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that with the feature flag enabled, when users navigate to the Records page, they are sent to the temporary MR page. Users without the feature flag are unable to see this temporary MR page. 
<img width="1497" alt="Screenshot 2024-05-21 at 10 16 54 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/a5b641d9-27cf-4016-a22a-8cdd9cf567f6">

**Comment by brea11y** [comment]
This looks great. No accessibility concerns.
