### ISSUE TITLE
10-7959f-1: end to end test coverage

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82086]
As a VA.gov user, I want to make sure that if there are any issues with the FMP form I filled out, they are flagged so that my registration goes through to the VA.

We need an E2E Cypress test both to ensure the form behaves as expected, and to satisfy the requirement before going to production.

Acceptance criteria

- An E2E test for form 10-7959f-1 exists
- the E2E test can be automatically run

**Comment by reiting** [comment]
<img width="837" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f8b2c7bd235326bb4d7a1a60e8edfd46a26947f/Screenshot%202024-05-16%20at%2011.07.14%E2%80%AFAM.png" alt="Screenshot 2024-05-16 at 11.07.14 AM.png" />

**Comment by reiting** [comment]
@marywang2 @baltes this is in platform review at the moment.

**Comment by marywang2** [comment]
@reiting would you be able to upload the screenshot again, it's not coming through. (I also couldn't open the end to end link).

**Comment by reiting** [comment]
![Screenshot 2024-05-16 at 11 07 14 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20195737/3c1484d5-a9d6-4daa-9dbb-35d8e78ce36a)
