### ISSUE TITLE
Toxic Exposure - test submission of a claim from va.gov to VBMS 15B and 15E Gulf War (iteration 3)

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#82090]
As the chosen one (a va.gov staging user) I can fill out the form 526ez with toxic exposure conditions, submit the claim, and a VSR can see the claim established in VBMS and see the 2022 526 generated pdf in my eFolder.

Because we don't have Lighthouse sync claim id coming back synchronously, we can fake this, but in order for it to come back successfully we can give it a fake claim id to move the process along.

Open questions & considerations:
1. Will a fake/synthetic claim id work? The doc upload endpoint requires a claim id - stakeholders understand that the "claim id" coming back and displayed to the user will not match a claim id in VBMS for now, not until the Lighthouse "sync" submit endpoint is ready.
2. ancillary forms will fail because it doesn't have the right claim ID - let's not fill out any ancillary forms for this testing
 
Tasks:
- [x] enable flipper flag for "the chosen one" at [staging.flipper](https://staging-api.va.gov/flipper), `disability_compensation_lighthouse_submit_migration`.
- [x] test!!! includes manually checking VBMS. question: does the claim status tool show this progress?

Acceptance Criteria:
- [x] manual check in VBMS
- [x] the claim ID is visible in VBMS
- [x] the pdf is in VBMS (staging env)
- [x] 15a is checked in the pdf 
- [x] column 2 is populated with conditions
- [x] 15b shows yes/no appropriately
- [x] date range in 15b is empty
- [x] 15e is populated appropriately
- [x] the submission has created an End Product (EP) in VBMS
- [x] capture what the data looks like in the PDF and attach to the ticket

**Comment by alatempa24** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Disability-Experience-63dbdb0a401c4400119d3a44/issues/department-of-veterans-affairs/va.gov-team/82090?planning-poker) with Zenhub @aurora-a-k-a-lightning @christinec-fftc @mchae-nava @michael-wojcik @sethdarragile6

**Comment by aurora-a-k-a-lightning** [comment]
successful transmission of Gulf War and Multiple Exposure data transformed from staging.va.gov -> vets-api -> lighthouse -> UAT VBMS
example with multiple exposure data: https://vefs-claimevidence-ui-uat.stage.bip.va.gov/pdf/4a375127-8cb9-4652-8472-9195c6bfed52?embedded=true
[jesse-gray-gulfwar-and-multiple-exposure.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTdsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e34a12431b444c9375a013ddec16e54e9d92772e/jesse-gray-gulfwar-and-multiple-exposure.pdf)

**Comment by aurora-a-k-a-lightning** [comment]
Tested with "NO" to gulf war question (15B) and 0 multiple exposures.
[jesse-gray-no-multiple-exposures-no-gulf-war.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXYyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a1b1f32ded31e31462f319e6306fd359b36691b/jesse-gray-no-multiple-exposures-no-gulf-war.pdf)
