### ISSUE TITLE
Research: submission experience for 526 backup path failure

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#82101]
Create plan, conduct research to evaluate solution, and identify findings for the scope of the parent epic.

See [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20and%20post-submission%20experience.md#problem-or-opportunity) for problem statements of the larger initiative.

**Comment by evelynhilbrichdavis** [comment]
Research tickets will be consolidated for a Veteran Research user testing after the design phase.
