### ISSUE TITLE
Individual state - focus and announcement issues

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82126]
After user 33 or user 108 logs in on Safari + VoiceOver (VO), VO properly announces "loading your accredited representative information". But after it finishes loading, 
a) it doesn't announce that it's finished, and 
b) focus goes to the browser (it left the page)

On JAWS + VO, something similar happens - JAWS started announcing items from the top of the page, and not from within the card itself.

Not sure if this is helpful, but Jamie with Accessibility found a good article about live regions: https://tetralogical.com/blog/2024/05/01/why-are-my-live-regions-not-working/

## Expected vs. Actual
**Expected**:  The user is made aware that loading is complete, and focus remains on the card.

**Actual**: The user is not notified that loading is complete, and focus shifts to the browser.

## Steps to Reproduce
On a mac:
1. Turn on VO, then go to staging FAR page in Safari
2. Log in from widget as [vets.gov.user+33](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv)
3. Listen for "loading your accredited representative," then note what happens when loading is complete

## Examples
Screen recordings:
VO: https://us02web.zoom.us/clips/share/bD-dgsZAr6vJ9koFtQTy7oXIBXEkztzRclY0m_QYJdPwYP6J3xPPX1BDhacE6EXqtzXp95thRCgDZpdd47EYTlcQ.ta3hTPnAdjRlKFUj
JAWS: https://us02web.zoom.us/clips/share/wcCWTdPdJnqT1DybH7VhMSSI1Tj_lDiu7ITCp8R_voduac2HDBfG10ogKI3YlICl8XuLvVStZi8_TF1r5nLSFmwF.vd3WdWvtL-LrJ2Cz

**Comment by cosu419** [comment]
Waiting for a JAWS license from AdHoc. Should be in by Tuesday 5/7 or Wednesday 5/8

**Comment by cosu419** [comment]
Correction - JAWS is windows only, so I'll just test with VO and ask Jamie to confirm the fix works in JAWS.

**Comment by oddball-lindsay** [comment]
Downloaded as expected on my Mac and was able to add the contact card 
<img width="797" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72c2bc8c1052509ed5b00c9fb5e82676368f3064/image.png" alt="image.png" />

On my iPhone, the donwload link opens up this contact card overlay, and there are options to save the contact at the bottom.  
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80a1f308aa50d91ff4d0be10da4209aca64be0c6/httpsstaging.va.govget-help-from-accredited-representativefind-reppostLogin%3Dtrue.jpeg" alt="httpsstaging.va.govget-help-from-accredited-representativefind-reppostLogin=true.jpeg" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee41e737192923a2eefddf6d11fb4025d95ee123/httpsstaging.va.govget-help-from-accredited-representativefind-reppostLogin%3Dtrue%202.jpeg" alt="httpsstaging.va.govget-help-from-accredited-representativefind-reppostLogin=true 2.jpeg" />

Looking good - thanks for the fix @cosu419!

**Comment by cosu419** [comment]
I tried moving all the focus logic from Find to the widget itself (which is where it belonged in the first place) as well as adding `aria-atomic` to the widget container. Everything still behaves as expected in Chrome, but still not Safari. 

It may be an issue with how the widget is being imported into Find... I will try a different approach and check with some other platform devs.

**Comment by cosu419** [comment]
Got some a11y feedback in this [Slack thread,](https://dsva.slack.com/archives/C05L6HSJLHM/p1715190936470849) but the consensus seems to be that our current implementation is minimally viable. Closing for now.
