### ISSUE TITLE
10-7959f-2 - Veteran Review and Confirmation pages

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82128]
As a VA.gov user, I want to review my FMP claim info and view the confirmation page so that I know my information has been submitted.

- review page with section headers and sub heads matching copy in Figma
   - statement of truth with privacy policy link
- confirmation page following [guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-confirmation-page.md)
  - confirmation message with print page button
  - further FMP information
- use v3 components

[Figma](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=4715-17051&node-type=SECTION&t=x6RV7LrddqoHVC0h-0) - use 'wip' 

Acceptance criteria:
- Given an FMP user on VA.gov
- When they have filled out the form, 
- Then they should be able to see the review page to confirm or edit their information, 
- And they should see the confirmation page once they've submitted.

**Comment by marywang2** [comment]
@reiting I updated the figma link to the 'wip' confirmation and email updates screen. That one should have the latest changes, thanks!

**Comment by reiting** [comment]
@marywang2 @jamiefiore a quick question. In Figma, I see on the review page, you want the payment selection section to say Veteran mailing address if Veteran was selected. If Provider was selected, do you want it to say Provider mailing address or just Provider (or something else I didn't think of). Not urgent,I'll just do Provider for now, and you can let me know when you  know for sure!

**Comment by reiting** [comment]
<img width="674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDYwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--207c7d96582c4260e5bf8efdd2e263d1b28d379a/Screenshot%202024-09-04%20at%201.55.39%E2%80%AFPM.png" alt="Screenshot 2024-09-04 at 1.55.39 PM.png" />
<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCswQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2821ad48357b22d853a32cbc9ebd96dcd171bac7/Screenshot%202024-09-04%20at%201.55.51%E2%80%AFPM.png" alt="Screenshot 2024-09-04 at 1.55.51 PM.png" />
<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUMwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef7060feb0155853abcbe4818771edd01c28f17a/Screenshot%202024-09-05%20at%201.39.44%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 1.39.44 PM.png" />
<img width="761" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUswQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--401a075a5d42bcee44aa55855fc6808c63ece865/Screenshot%202024-09-05%20at%201.39.52%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 1.39.52 PM.png" />

**Comment by marywang2** [comment]
@jamiefiore for review as well.

**Comment by marywang2** [comment]
There may be changes to this page after CAIA review but closing for now @reiting
