### ISSUE TITLE
10-7959f-2: Veteran's mailing address 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82125]
As a user on VA.gov, I want to enter my mailing address when I fill out the FMP claim form so that I can be sent checks and other correspondence related to my claim.

[wireframes](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=726-21596&mode=design&t=WkD8EY1rrT2jQsNa-0)

- country is selectable from dropdown (set to required)
- street address is text field (set to required)
- Street address line 2 and Street address line 3 should be displayed (optional)
- city (set to required)
- state is selectable from dropdown (set to required)
- zip code (set to required)
- data is prefilled if user is signed in w/LOA3

Acceptance criteria:
  - Given the user is filling out the FMP claim form
  - When the user enters their mailing address information (country, street address, apartment/unit number, city, state, zip code) on the mailing address screen
  - Then their information should be successfully saved

**Comment by reiting** [comment]
This has been approved and merged and should be in staging now @marywang2

**Comment by marywang2** [comment]
@reiting please change "application" to "claim". (cc @brian-wilke please review as well).
<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5d22a5ab5a1175666c0152463d65866a88db0b5/Screenshot%202024-07-11%20at%2012.04.01%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 12.04.01 PM.png" />

**Comment by reiting** [comment]
This is finally in platform review. There were some errors originally when pushed that were due to some problem in main. It has since been fixed so this finally passed and is waiting on platform.

**Comment by reiting** [comment]
This has been approved and merged. Should be on staging in a few hours.
