### ISSUE TITLE
Contact Center Review for Accredited Representation Management - Representative Status Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82124]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The Representative Status Widget product is a user-friendly, accessible widget on VA.gov that reflects a Veteran’s current representative status.

### Launch Date
Staged rollout is scheduled for 5/13 - 5/20 ([release plan for reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/release-plan-representative-status-widget-1.0.md))

### Version Number
Version 1.0

### Product Guide
[Product Guide for Representative Status Widget 1.0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/contact-center/product-guide-representative-status-widget-1.0.docx)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by oddball-lindsay** [comment]
@jwoodman5 We just received our Staging Review feedback and no launch-blocking items were reported. We're currently planning to move forward with our staged rollout from 5/13-5/20, but I wanted to see if there's any concerns with that given this Contact Center Review ticket is still open.

**Comment by starlow00** [comment]
Draft looks good! Sent for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. I've attached a working copy; please use it for future revisions/additions. Thank you!
[Representative-Status-Widget-v1.0_SRT_05172024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1FKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac6185ce583821c46300cb0c02207518d0e86d92/Representative-Status-Widget-v1.0_SRT_05172024.docx)
