### ISSUE TITLE
Research plan for search improvements design

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8215]
### User Story
As a Veteran, I need the Facility Locator to return meaningful results to my search so I can select a facility which will meet my need.

## Goals of research
Gather veteran feedback on the updated search ux prototype. Reference [#6750] 

**Areas of interest:** 
- [ ] How do the changes to the user/map interaction impact the search workflow and usability?
- [ ] How do the changes to the search parameters impact usability/veteran understanding?
- [ ] How do veterans use the available filters and why?
- [ ] How do filters impact usability/veteran understanding?

## Acceptance Criteria
[ ] Approved research plan which requests recruitment of 5-10 participants representing a population under age 40 yrs **and** over 60 years, preferably with a mix of urban/rural locations
[ ] Approved conversation guide

**Comment by arickalewis1** [comment]
Attaching folder with plan, script, session notes, and synthesis: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/research/user-research/FL-Search-march2020
