### ISSUE TITLE
[CAIA Intake] Verify Your Enrollment: Manage Your Benefits page (May 2024)

### ISSUE THREAD

**Issue by cassidy-beach** [department-of-veterans-affairs/va.gov-team#82157]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Verify Your Enrollment (VYE)
- **OCTO product owner:** Emily Theis
- **Product name:** Verify Your Enrollment
- **Product manager:**  Jason Wolf and Cassidy Beach
- **Slack channel:** #vye_team
- **Dedicated content writer on your team (if you have one):** Ryan Gray/RyanGrayVA
- **Dedicated a11y specialist on your team (if you have one):** None
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [X] Something else: We are transforming the legacy, non-compliant Web Automated Verification of Enrollment (WAVE) to Verify Your Enrollment (VYE) on VA.gov. We've already gone through the CAIA Intake Request for this project. VA Profile recommended that we reach out again after making some changes to the Benefits Profile page within our application to ensure it meets CAIA standards. 

### What's the nature of your initiative and desired outcomes?

We are submitting a new CAIA ticket at the request of the Platform team. We ran into an issue with the _VYE Benefits Profile_ page, now called the _Manage your benefits_ page, because of potential confusion with VA Profile (it cannot be integrated with VA Profile because of the inability of the WAVE/VYE backend to connect with VA Profile database). After meeting with them several times we agreed to keep _Mange your benefits_ under the Verify Your Enrollment web application. Our compromise was agreeing to meet with CAIA again to ensure we meet all content, accessibility, and information infrastructure requirements. Here is a link to our mockups in Figma: https://www.figma.com/file/B3Ds72oQhBZG1EtfffbAYk/VYE-Wireframes?type=design&node-id=42-4775&mode=design&t=E5886TXNCShOUj7I-0. 

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [X] Yes
- [ ] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Received feedback from IA and Design on October 19, 2023 for Design Intent.
Completed our first CAIA Intake Request October 23, 2023. 
Completed Midpoint Review December 4, 2023. 
Received feedback from Content, Accessibility, and IA on December 4 and 5, 2023 for Midpoint Review.
Looking to schedule Staging Review for the end of May 2024. 
Looking to schedule Privacy, security, infrastructure readiness review for the end of May 2024. 
Launching VYE in VA.gov mid-June 2024.

Ideally, we would like to meet soon so we can give ourselves enough time to incorporate the necessary changes into our product prior to launch. 

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [X]  Yes
- [ ]  No
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [X]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [X] Design intent 
- [X] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** #67530 [https://github.com/department-of-veterans-affairs/va.gov-team/issues/67530] 

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [VYE Figma Files <Wireframe v3>](https://www.figma.com/file/B3Ds72oQhBZG1EtfffbAYk/VYE-Wireframes?type=design&node-id=42-4775&mode=design&t=mVvhUgdidYycoPuV-0) 

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [x] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by aprocik1** [comment]
@cassidy-beach, thanks for submitting this intake. Katherine and I have already reviewed this Figma file as a part of your other intake (https://github.com/department-of-veterans-affairs/va.gov-team/issues/68205). If you'd like, we can re-review your Figma file after you update it to incorporate our recommendations and match what's in staging. Let me know if there's anything else you need from our content team.

Cc'ing @strelichl and @katherine-fung for awareness.

**Comment by cassidy-beach** [comment]
@aprocik1 thank you. I don't think the Figma files need to be re-reviewed after they're updated unless you think it would be helpful. We submitted another intake ticket to comply with Platform's request for us to do so.

**Comment by jennymayoco** [comment]
Hi @cassidy-beach @jason-gcio @RyanGrayVA - here is the URL for this page 

<img width="650" alt="Image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/c7404caa-574d-493b-9c55-1b58ce07edb9">

I've also mapped how this will look in the sitemap - it will live on the same level as `/verify-enrollments`

<img width="500" alt="Image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/1afabcb7-2015-4527-a697-00ccdce88e79">

I've also begun to document entry points and crosslinks in the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/mgib-benefits-info.md). I will review these with Mikki so there might be changes. Let me know if you have any questions.

One question for you - I noticed there's a "Pending documents" section in staging and Figma. Can you tell me more about that? The veteran facing forms team is working on a similar initiative to add forms with a status on MyVA so I wonder if there's potential to collaborate there.

**Comment by jennymayoco** [comment]
Hi @cassidy-beach thank you for that info! That form status might feel buried since it would be on a page that's about updating benefits info so I def recommend working with Auth experience and Veteran facing forms teams to collaborate on how to include the status for both those forms on MyVA so it's all in one place.

Here is the [finalized IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/mgib-benefits-info.md). Because info updated in this feature will only impact MGIB, we are recommending that there is content added to the crosslinks so that Veterans are aware that updating in one place won't update in the other. Please work with Sitewide Content for how to best showcase that alert. Let me know if there are any other questions!

cc @jason-gcio @RyanGrayVA @katherine-fung @aprocik1

**Comment by bethpottsVADEPO** [comment]
**Pages where we've added crosslinking within the unauth experience:**

- https://www.va.gov/resources/change-your-address-on-file-with-va/
Added a crosslink to VYE FAQs

![Image](https://github.com/user-attachments/assets/356f1351-3292-4bf6-9e43-b33c7876aa4d)


- https://www.va.gov/change-direct-deposit/
Added a "Note"

![Image](https://github.com/user-attachments/assets/2dbc628f-325f-4258-9ef0-84e665f3b6e0)

...Intentionally no changes made on [Change your address in your VA.gov profile](https://www.va.gov/change-address/), since it already crosslinks to the section of Change your address on file with VA that has information about contacting the department directly and the option to go to the VYE tool to update online.

**Comment by bethpottsVADEPO** [comment]
Recommendation for profile's direct deposit screen:

![Image](https://github.com/user-attachments/assets/6b278776-da01-4597-8ef2-fdcb660b9168)

Could we add an additional info component as I'm seeing on some of the other profile screens, so the text will unfurl when the user clicks the label, like this?:

![Image](https://github.com/user-attachments/assets/e82e2a63-b885-4eb4-8e72-a22f60f533d3)

FYSA @clantosswett

**Comment by bethpottsVADEPO** [comment]
Here is the text for copying and pasting (I updated it a bit from the above screen shot--please use this version):

[How to update your direct deposit information for Montgomery GI Bill]
If you’re getting benefits through the Montgomery GI Bill Active Duty (MGIB-AD) or Montgomery GI Bill Selected Reserve (MGIB-SR), you’ll need to update your direct deposit information using our enrollment verification tool. 
[Update direct deposit information for MGIB benefits](https://www.va.gov/education/verify-school-enrollment#for-montgomery-gi-bill-benefit)

**Comment by ACParker89** [comment]
> Here is the text for copying and pasting (I updated it a bit from the above screen shot--please use this version):
> 
> [How to update your direct deposit information for Montgomery GI Bill] If you’re getting benefits through the Montgomery GI Bill Active Duty (MGIB-AD) or Montgomery GI Bill Selected Reserve (MGIB-SR), you’ll need to update your direct deposit information using our enrollment verification tool. [Update direct deposit information for MGIB benefits](https://www.va.gov/education/verify-school-enrollment#for-montgomery-gi-bill-benefit)

Hi @bethpottsVADEPO! Is this text approved already or do we need to run this through CAIA? We are happy to meet with you to discuss where this is at!

**Comment by bethpottsVADEPO** [comment]
@ACParker89 This text is approved. You can move forward with it, thanks!

**Comment by bethpottsVADEPO** [comment]
Closing this ticket as the content work is complete. I'll follow the above-linked auth ticket separately.
