### ISSUE TITLE
Hide 10-10EZR link for un-registered users

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82174]
### User story

As a Veteran who is not registered at a facility or whose credentials are not LOA3 (identity-proofed), I don't want to see a link to "Update health benefits info (10-10EZR)", so that I don't have the option to view a form I can't use.

### Notes
- [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1714666706154059) on topic (links to other threads)
- Can use same selectors that are used for the corresponding alerts

Possible tasks:
- 

## Acceptance criteria

- 10-10EZR link is hidden on the MHV landing page when a user is 
  - [ ] un-registered OR
  - [ ] is signed in with a non-LOA3 credential
- QA review
- A11y review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the EZR link is hidden as expected for un-registered or non-LOA3 credentials. No a11y review needed

NOTE: Users can still find the 10-10EZR link by going directly to the 10-10EZR app using the URL, but they will be prevented to fill it out as expected. Just adding this as a note.
