### ISSUE TITLE
[V0] ITF -- Implement flow for new ITF pieces

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#82185]
# Overview
When in doubt about requirements, always use the [mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1714050769683/e4dffd0f80fc8aca04a773dbe53c0d40fd5f2dde?wid=70-1714662280565) as the source of truth.

This ticket represents the work needed to tie together the synchronous call and the asynchronous call.

## Task
- [ ] All changes should be behind a flipper

**Comment by buddhima-coforma** [comment]
NA any more
