### ISSUE TITLE
Analytics Implementation for MHV Cartographers - MHV Secondary Nav

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#82201]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - MHV Cartographers

- **Product Name**

    - Multiple tools: MHV tools and landing page
      
- **When is the launch date?**

    - 5/23/24

- **Provide the link(s) for Product/Page urls**
  
    - https://staging.va.gov/my-health and the MHV tools under `/my-health`

- **What Events need to be tracked?** 

Clicks on the MHV Secondary Nav, per department-of-veterans-affairs/va.gov-team/issues/80654.

The MHV Secondary Nav is in the process of initial implementation: department-of-veterans-affairs/vets-website/pull/29424

We propose `Navigation - MHV secondary nav - [link text] - [link url]` as the custom event scheme.

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - `ssoissoetesting+mhvcss4@gmail.com` or other users with health records per the [Test User Dashboard](https://tud.vfs.va.gov/)

- **Any additional comments**

    - The MHV Secondary Nav is a component that will be shared across MHV tools

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by dcloud** [comment]
@jestutt Our PM, @wesrowe, indicated you may have feedback on `Navigation -` scheme requests like this one. 

Could you let us know if `Navigation - MHV secondary nav - [link text] - [link url]` the right direction or if that needs tweaking?

**Comment by jestutt** [comment]
@dcloud  That looks like a GA UA taxonomy structure that would be created in GTM based on the variables in a dataLayer push event but I don't think that's what you're asking for. I think you want to share the dataLayer push event template for the custom event instead. 

Please note that the GA4 implementation project is the priority right now and other requests will likely be delayed until we have made further progress on that front -- which will likely not be until end of June/early July.

cc @johnny-jesensky-adhoc

**Comment by wesrowe** [comment]
@jestutt, we would be happy to use a GA4 approach instead. We have a major release coming at the end of May and we need to get some GA instrumentation on it – and it sounds like we all prefer GA4.

We need help understanding how to do custom events in GA4. Can you share an example of the GA4 "dataLayer push event template for the custom event"? Since we're familiar with the Navigation taxonomy from UA, it would be nice if the example was from a Navigation component you've already migrated.

Hopefully that's clear – I might suggest slack as a quicker alternative otherwise.

**Comment by jestutt** [comment]
@wesrowe  UA or GA4 would use the same dataLayer event to pass information thru to GA and a dataLayer event template looks like [what I shared for the alert render request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70772#issuecomment-2048552731). I think what you're asking for instead is the template, not the Event Action schema from UA. Give me until the end of the week and I should have that for you. 

@johnny-jesensky-adhoc

**Comment by wesrowe** [comment]
@jestutt, okay, hopefully it's clear what we need to get out of this template as you design it. I'm thinking there are those classic 4 pieces of info from UA events:
- Navigation
- Which menu
- Link text
- Link destination

it could probably be done in fewer than 4 fields, e.g., maybe we could lose the category "Navigation".

**Comment by dcloud** [comment]
> I think what you're asking for instead is the template, not the Event Action schema from UA. Give me until the end of the week and I should have that for you.

@jestutt I imagine you weren't able to get to this yet, but do you have an update? Thanks in advance

**Comment by jestutt** [comment]
@dcloud  Thanks for checking in! Give me one more day. I want to make sure what I give you maps the same way as other nav tracking. 

cc @johnny-jesensky-adhoc

**Comment by jestutt** [comment]
@dcloud  Here's the dataLayer push event template for the new MHV nav:
```
'event': 'nav-mhv-secondary'  //feel free to change but share the final event name(s) with me so I can ensure the event is sent to GA 
'action': 'click'
'nav-link-text': //populate with the text of the link
'nav-link-url':  //populate with the destination URL
'nav-link-location': 'MHV secondary nav'  //using what you had in the ticket but change if you want something more descriptive
```

Let me know if there are any questions. 

cc @johnny-jesensky-adhoc

**Comment by dcloud** [comment]
I think that all looks good. I've added the ["template" in this part of my PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29831/files#diff-7c94d90d7002aec9f2913fb4048d546b279d7f39f6ff9b01e474960e2112783fR55-R63), no edits

**Comment by wesrowe** [comment]
@jestutt, fysa we implemented our piece in Staging but the event doesn't seem to be connecting to GA correctly yet. Here's AdSwerve:
<img width="444" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/2f93a272-602e-4193-8c99-07c39d6a58d9">

Do you or @Blivaditis still need to do the GTM piece?

**Comment by wesrowe** [comment]
Bumping this post-holiday – @jestutt @johnny-jesensky-adhoc

**Comment by wesrowe** [comment]
@jestutt, I understood it would be GA4-only. I realize my screenshot doesn't convey that understanding – sorry. Anyway... thanks for the Monday offer.

**Comment by wesrowe** [comment]
@jestutt, checking in – I didn't see a GA4 event just now in adswerve. Thanks!

cc @johnny-jesensky-adhoc

**Comment by jestutt** [comment]
@wesrowe  The tracking for the new event has been published but I couldn't find the new menu on the staging site to test. Going to follow up in [Slack](https://dsva.slack.com/archives/C1Q4294JJ/p1718238293683159) for more info. 

@johnny-jesensky-adhoc

**Comment by wesrowe** [comment]
I believe we stopped at "Jamie can see the new event in adswerve but for some reason Wes can't."

**Comment by wesrowe** [comment]
I found these events working as expected in GA4 Explore. I'll come to office hours if I continue to not be able to see this event in AdSwerve. Thank you!
