### ISSUE TITLE
Breadcrumb IA for SM, Appts

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82203]
### User story

As a Cartography team member, I want to provide a breadcrumb pattern for child pages in SM and Appts (and Records?) that will enable a consistent pattern across the MHV-on-VAgov portal, so that Veterans can wayfind similarly on each health tool with minimal cognitive load.

### Notes
- Medical Records cannot have the same breadcrumb structure as other applications while it is in Phase 0 (it needs to be an island, unconnected from the My HealtheVet landing page and other experiences)
- SM and Appts breadcrumbs should follow the same high-level structure as Medications. All apps should be uniform and consistent

Possible tasks:
- Ask designers to agree on consistent padding across MHV
- Document plan for
  - details pages, 
  - form flows, 
  - subtasks, 
  - and general application pages

## Acceptance criteria
- [x] Breadcrumb designs prepared for SM and Appts
- [x] Sought feedback from tool teams, IA stakeholders
- [x] Send plan to tool team devs for implementation

**Comment by sterkenburgsara** [comment]
Breadcrumb plan [has been finalized in this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713558793852/31aadcbae7070a6f0f4cfea4f63e568721f1480d?sender=uf94a77a19aaf687331c09367)

Shared updates with UX teams, who I am expecting to pass off to their own devs / get tickets written in whatever system they use (JIRA, Zenhub, etc.)
