### ISSUE TITLE
Plan for research with pension-eligible Veterans

### ISSUE THREAD

**Issue by Allexelaw** [department-of-veterans-affairs/va.gov-team#82213]
Plan for research with Veterans who are eligible for the 527EZ Pension Benefit
- Speak with Perigean about their ability to recruit the population of Veterans who are eligible for Pension Benefits
- Identify the goals of the research and the questions that we have for these Veterans
- Identify the timing of the research, type of testing, and the tools (e.g. clickable prototype, staging) 

To do:
- [x] Reach out to Perigean and discuss research needs to identify participants and recruitment plan
- [x] Draft goals of research and list of what we hope to learn
- [x] Share findings from discussions and draft research goals and questions with enablement team

Staging changes we want to talk with the Veterans about:
- [Clarify Medical Evidence](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88388)
- [Improved intro page ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88387)
- [Clarify supporting docs page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88521)
- [Clarify dependents assets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88400)
- [Updated submit docs page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89519)
- [Update confirmation page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89520)

**Comment by djones2113** [comment]
Recording initial thoughts in [this GDoc](https://docs.google.com/document/d/12OAWzkrPtDQV6JMYslbDWFC7PQJw8GP1Mg4CWz-Y0D8/edit)

**Comment by djones2113** [comment]
This has been paused due to larger discussion about priorities

**Comment by Allexelaw** [comment]
Connected with Perigean to discuss research needs.  To reach actual users of 527EZ using assistive technology may take a few weeks for recruiting.  Goals of research were listed in draft document  @ap.  Ticket on hold while Design/Research Map activities and data needs.

**Comment by Allexelaw** [comment]
Will reconnect with Shane Strassberg and Perigean about establishing a Pipeline of 527EZ Eligible Veterans for future research.  Working with designer, Michael Tri, to prioritize and group research.

**Comment by djones2113** [comment]
@Allexelaw it looks like you've already completed all of the AC on this ticket. Now that you've started working on the research plan and conversation guide, can we close this ticket and create a new one focused on developing the research materials?

**Comment by gmaciolek** [comment]
Here are the 3 usability updates on staging that are ready for research:
- [Improved intro page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88521)
- [Clarify supporting docs page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88521)
- [Clarify dependents income & assets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88400)

Here's the [MURAL link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726003254057/dbb8e984faac405d0c7da02087f5185e36b6c7b0?wid=0-1727712875108) to where these changes have been documented and prepped for handoff to research. (Note: I'm still making a few updates to it, but should have my part wrapped up by the end of the day tomorrow 10/4)
