### ISSUE TITLE
Analytics Implementation or QA Support for [Virtual Agent Chatbot - Disability Ratings Skill Feature]

### ISSUE THREAD

**Issue by goelsunaynaVA** [department-of-veterans-affairs/va.gov-team#82210]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Virtual Agent Chatbot Team
- **Poduct Name**

    - Chatbot
      
- **When is the launch date?**
    - May,2023

- **Provide the link(s) for Product/Page urls**
  
    - [[Insert link(s)]](https://www.va.gov/contact-us/virtual-agent/)

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration

    - **Sessions successfully signed into our Disability Ratings Skill Feature**

       a. Clicking **start chat** on the chatbot
       b. Type in trigger phrase "What is my disability rating"
       c. Click "yes" and sign in to account

   - **Unique users who successfully signed into our claims status feature**
   - **Any links that are clicked from Disability Rating Skill Feature**
         - for standard ratings flow and 0% combined/null individual ratings
         We would like to track anytime these links are used
            
![Screenshot 2024-05-02 at 10 54 00 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/3fce5ab4-8698-466b-bf5b-cecb84bb7fac)
![Screenshot 2024-05-02 at 11 01 05 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/f3dbe989-2e9a-4485-b29e-5097a742edaf)
![Screenshot 2024-05-02 at 11 19 23 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/5dd2258c-6ad1-4d1e-b95a-7c8b5db8b1a3)

  - for null combined and null individual ratings
         We would like to track anytime these links are used
![Screenshot 2024-05-02 at 11 07 08 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/c49e0ee7-4774-4943-a0a4-e53bbf0c65ee)
![Screenshot 2024-05-02 at 11 07 29 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/ae4d08fe-aa6c-4d2c-873f-e1e5e5e0fac7)
- **Any buttons that are clicked from Disability Rating Skill Feature**
    - - for standard ratings flow and 0% combined/null individual ratings
      
![Screenshot 2024-05-02 at 11 15 54 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/21c316bc-f344-410a-b54a-b79a0ce7a7bd)
![Screenshot 2024-05-02 at 11 19 23 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/1ecf6098-e275-49df-8ccb-39f412f92788)
 - for null combined and null individual ratings
 
![Screenshot 2024-05-02 at 11 23 07 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/113139363/37aa4fc2-65f4-4ba3-9bdb-7330e5f122bc)

    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jestutt** [comment]
The custom events used for chatbot tracking are mostly templatized but those templates are in the process of updating as part of  #93539. Once we're sure of the new templates, we'll update here. 

cc @johnny-jesensky-adhoc @Blivaditis

**Comment by jestutt** [comment]
@goelsunaynaVA There are a number of default Chatbot events

- Skills Entry is an api_call dataLayer event that is under the api_call event in GA4
- Button clicks are a chatbot-button-click dataLayer event that is under the chatbot event in GA4
--the button text can be found under Link text
- Link clicks are a chatbot-resource-link-click dataLayer event that is under the chatbot event in GA4
-- the link text can be found under Link text

Staging Explore report -- Chatbot Events by Skill

- Tab 8 are all the chatbot events related to the Rating skill -- there hasn't been a lot of activity generated
- The API Call event that measures the skill entry will start to show up soon -- it was just added in GTM

All desired events look to be tracking correctly on staging tho.
