### ISSUE TITLE
[V0] DataDog Work

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#82225]
# Overview
Part of the work for ITF will involve adding some logging: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79680

This ticket is to support any DataDog related work such as a dashboard or widget showing ITF issues.

We need to setup a watchtower event for queue exhaustion.  An example of this is:
https://vagov.ddog-gov.com/monitors/189698?view=spans
`sum(last_15m):default_zero(sum:vets_api.statsd.worker_lighthouse_pension_benefit_intake_job_exhausted{env:eks-prod}.as_count()) >= 1)`

## Task
- [x]  Create a watchtower event for queue exhaustion

## AC
- Watchtower event is created

**Comment by danlim715** [comment]
Can't create a monitor for the exhaustions or failures yet, because none have been reported to Datadog as of yet. Apparently Datadog needs a reference to the actual error code in order to create a monitor for that code. We will have to revisit this once we turn on this feature in production.

**Comment by danlim715** [comment]
Create ITF Async Queue Exhaustion Monitor created here: https://vagov.ddog-gov.com/monitors/243639?view=spans

**Comment by danlim715** [comment]
Create ITF Async Job Dashboard here, but it's still empty for now. We need to discuss what information we wish to display here: https://vagov.ddog-gov.com/dashboard/dxs-5im-rs2?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1721056401699&to_ts=1721060001699&live=true

**Comment by aplatt-coforma** [comment]
Dashboard was created via  #88456 [v0] DataDog Dashboard for ITF?
