### ISSUE TITLE
AWS access for [Mohammad Ewaz Farhang]

### ISSUE THREAD

**Issue by ewaz-farhang** [department-of-veterans-affairs/va.gov-team#82227]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

Mohammad Ewaz Farhang

### Your Email

ewaz.farhang@accenturefederal.com

### Team, Role, and Company of the target individual

Automated Regression, SDET,  Accenture Federal Service

### Product Manager (PM) name and email

Manju Gopalakrishnan Manju.Gopalakrishnan@va.gov

### Product Owner (PO) name and email

Kelley Spearmon, Kelley.Spearmon@va.gov and Eddie Ricks Eddie.Ricks@va.gov

### Desired AWS Access

Requesting access to Dev instances to be able to properly create and link our mocked users to be able to sign in.

### Access Expiration

May 2, 2025

### E-QIP Transmittal Confirmation

![Screenshot 2024-05-02 at 4 25 47 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/84805897/db059105-3710-4bb1-8de5-c51611eed384)

### Additional Notes

I'm requesting this access because we created a number of id.me test users that aren't properly mocked in v[ets-api-mockdata ](https://github.com/department-of-veterans-affairs/vets-api-mockdata)and only work on localhost. I would like to be able to link these test users to the mockdata repository which would require access to run a rails console on a dev instance.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
The users is deactivated in github and was offboarded in march. None of the people mentioned in the description seem to be represented in github either. I'm closing this.

**Comment by ewaz-farhang** [comment]
Dear @flooose I got my VA github access 4 days ago on May 2. and I am not offboarded. Can you please specify what the issue is and how I can fix it. Maybe Manju Gopalakrishnan does not have access to github I can ask her to get her github access first or change supervisor. thanks

**Comment by flooose** [comment]
Hi @ewaz-farhang, I've reached out to leadership here on the Platform and they've put me in touch with Eddie Ricks in the DSVA Slack.

**Comment by ewaz-farhang** [comment]
Dear @flooose is there any new update on this request? thanks

**Comment by flooose** [comment]
No, @ewaz-farhang, unfortunately no word back from Eddie Ricks yet. I'm also off support rotation now, so I'll inform @patrick-black-oddball when I hear something.

**Comment by stoiven** [comment]
Hi there,

Just wanted to follow up on this request. Is there an update regarding this? Or is this issue still relevant?

**Comment by flooose** [comment]
@ewaz-farhang looking closer at the reasoning for this request, I'm wondering if you should maybe be requesting access to [rails terminal access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&projects=&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D) instead?

**Comment by patrick-black-oddball** [comment]
Closing this request - due to inactivity.
