### ISSUE TITLE
CT: Update Institution Profile Yellow Ribbon Modal Content [DRAFT]

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8222]
As a user of the comparison tool, I need the Yellow Ribbon information to be up to date, so I understand the Yellow Ribbon benefit.

## Assumptions:
1. This work is completed behind a toggle so that it is only available in the staging environments and below.

## Acceptance Criteria:
1. The content in supporting artifact # 2 is displayed when the user clicks one of the following links:
    a. "Learn more" next to the question "Will you be a Yellow Ribbon recipient?" in the "Estimate your benefits" section
    b. "Yellow Ribbon" in the "Veteran Programs" section

## Supporting Artifacts:
1. 

<img width="498" alt="yr_screenshot" src="https://user-images.githubusercontent.com/48260534/79986401-00a65a00-847a-11ea-8463-6e412980501d.png">

2. [Yellow Ribbon Modal Content.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4516301/Yellow.Ribbon.Modal.Content.docx)

**Comment by dneel-bah** [comment]
@peggygannon Can you review the content in Supporting Artifact # 2 (yellow ribbon modal content.docx) and provide feedback / let me know if we need a separate ticket.

**Comment by peggygannon** [comment]
thanks, @dneel-bah I've created a separate content review ticket for this work..

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8298

**Comment by peggygannon** [comment]
@dneel-bah content recommendations have been uploaded to: #8298

**Comment by dneel-bah** [comment]
@peggygannon I'll run this by EDU.  z

The one thing I noticed was that Post-9/11 GI Bill is no longer a link to https://www.va.gov/education/about-gi-bill-benefits/post-9-11/.  Is it OK to link that text as it was previously?

**Comment by dneel-bah** [comment]
@peggygannon We will be implementing this content change as part of #8524 .  EDU has approved the recommended content changes.  You can close this ticket if that is the next step; thanks.

**Comment by dneel-bah** [comment]
Closing issue as duplicate of 8524.
