### ISSUE TITLE
Analytics Implementation Veteran Facing Forms - 20-10207 Priority Processing

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#82238]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Veteran Facing Forms**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]

- **Product Name**

    - 20-10207 Priority Processing
      
- **When is the launch date?**
    - 4/24/2024

- **Provide the link(s) for Product/Page urls**
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/introduction 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/third-party-veteran-identity 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/third-party-non-veteran-identity 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/preparer-type 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/veteran-name-and-date-of-birth-a 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/veteran-name-and-date-of-birth-b 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/non-veteran-name-and-date-of-birth 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/veteran-identification-information-a 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/non-veteran-identification-information 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/veteran-identification-information-b
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/living-situation 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/living-situation-third-party-veteran 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/living-situation-third-party-non-veteran 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/other-housing-risks 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/mailing-address-yes-no 
- If answer no skip mailing address, if yes show mailing address
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/veteran-mailing-address 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/non-veteran-mailing-address 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/veteran-phone-and-email 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/non-veteran-phone-and-email 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/other-reasons 
- Above URL is conditional as to what they answered on living situtation
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/other-reasons-homeless-third-party-veteran 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/other-reasons-homeless-third-party-non-veteran 
  
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-financial-hardship 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-terminal-illness 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-als 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-vsi 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-pow-confinement 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-pow-confinement-2 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-pow-documents 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/evidence-medal-award 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/has-received-medical-treatment 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/medical-treatment 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/medical-treatment-third-party-veteran 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/review-and-submit 
https://staging.va.gov/supporting-forms-for-claims/request-priority-processing-form-20-10207/confirmation

 
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    -   [ Priority Processing workflow](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10207%20Priority%20Processing/PriorityProcessingWorkflow.png)

    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - I included the staging URL but this is for production tracking
    -
> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @tbaker1026 -- apologize for the delay on this. Our team is just now getting to this request due to some available bandwidth. Regarding a ticket to get this form added to our Forms KPI dashboard, yes -- can you please submit a request for that [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-and-update-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+%26+KPI+dashboard+update+request+for+%5BTeam%5D)?

Note that the most important thing on that form is to complete the [attached spreadsheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit?gid=0#gid=0).

Please reach out if you have any questions.

FYI @ChristineYoungZA, @Blivaditis

**Comment by Blivaditis** [comment]
Hi @tbaker1026 the base tracking has been confirmed on each page of the submitted funnel, here is a [GA4 report](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/fP7In2PMSXyTFU8EIX2BiQ) in the Non-production property which shows the events.
