### ISSUE TITLE
Error rate for Vets-API high

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#82254]
## Issue Description
Datadog is kicking off the error : "122.73% of the error budget for 7-day target has been consumed" (here)[https://vagov.ddog-gov.com/monitors/108853?from_ts=1714720213000&to_ts=1714721413000&event_id=7557436341448945400&source=monitor_notif]

Logs can be viewed (here)[https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20status%3A%28emergency%20OR%20alert%20OR%20critical%20OR%20error%29&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1687612289320&to_ts=1687785089320&live=true]
## Tasks
- [ ] VA.gov mobile team to investigate issue and communicate findings

## Acceptance Criteria
- [ ] Error resolved
- [ ] RCA (No need for post-mortem at this moment)
---

**Comment by alyssagallion** [comment]
@davidpetras @lindsay-insco is there a Slack thread for this one? I was thinking we could plop it into the description for context. :)

**Comment by davidpetras** [comment]
No slack ticket, @little-oddball put this on our radar. The mobile app team is currently discussing a fix

**Comment by alyssagallion** [comment]
@davidpetras @lindsay-insco Hey there! So do we need to follow up with the mobile team or?

**Comment by lindsay-insco** [comment]
Just in case [here](https://dsva.slack.com/archives/C04N9Q4D56K/p1714721175221989) is the original slack thread opening discussion.

**Comment by lindsay-insco** [comment]
Mobile discussion thread [here](https://dsva.slack.com/archives/C03DY3FN7HQ/p1707932098729139)

**Comment by lindsay-insco** [comment]
Will follow up with mobile team about their continued discovery.

**Comment by jperk51** [comment]
@lindsay-insco the latest is in the thread you linked earlier. The mobile team will be releasing a fix soon to limit request retries and the identity team put a patch in place to ignore the JWT issue it stops blowing up the logs and error budget
