### ISSUE TITLE
Spike - create mapping of param store values in vets-api code, helm chart and param store keys

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#82265]
Create a confluence page / google spreadsheet the details out the locations for environment values injected from the parameter store.

Of particular interest are:
1 - the source code module where the value is used / injected
2 - the helm resources that are defined in the parent helm chart (if applicable)
2 - the the resources in each environment wrapper chart that are used to pass the value in for each environment
3 - The parameter store key for each environment (dev, test, staging, prod)

This created document will be used to map out the helm chart and param store normalization efforts

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [x] **Scenario: Mapping of param store values in vets-api code, helm chart, and param store keys**
  - Given a confluence page or google spreadsheet is created
  - When the page or spreadsheet contains the following information:
    1. Source code module where the value is used/injected
    2. Helm resources in the parent helm chart (if applicable)
    3. Resources in each environment wrapper chart that pass the value
    4. Parameter store key for each environment (dev, test, staging, prod)
  - Then the document will be used to map out the helm chart and param store normalization efforts

**Comment by ericboehs** [comment]
Artifact: https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?usp=sharing
