### ISSUE TITLE
Create sub-urls for 21-4138

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#82269]
We're coordinating with CAIA to establish sub-urls for 21-4138 that follow their guidelines. 

For example: 

| URL before | New url | Page description |
| :--- | :--- | :--- |
| /supporting-forms-for-claims/support-statement-21-4138/review-and-submit | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/review | Review |

----
### Definition of done:
- [x] Define all 21-4138 sub-urls
- [x] CAIA approves new sub-urls
- [x] Update all 21-4138 sub-urls

### Resources:
- The IVC team put together a similar list for their 10-10d experience [(ticket here)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78843)
- `NEW`: [URLs doc in GitHub folder](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4138/21-4138%20URLs.md)

**Comment by rachelshearerux** [comment]
Jenny Mayo and I met today and created this list of URLs for 21-4138. The next steps are for CAIA to review + approve, then we'll update our URLs in staging. 

## URLS
### 21-4138 form flow
| Current url |	New url	| Page description | CAIA Approved | 
| :--- | :--- | :--- | :---: |
| /supporting-forms-for-claims/support-statement-21-4138/introduction | supporting-forms-for-claims/statement-to-support-claim-form-21-4138/introduction | Overview of the form |
| /supporting-forms-for-claims/support-statement-21-4138/name-and-date-of-birth | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/personal-information | Name and date of birth |
| /supporting-forms-for-claims/support-statement-21-4138/identification-information | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/identification-information | Identification information|
| /supporting-forms-for-claims/support-statement-21-4138/mailing-address | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/mailing-address | Mailing address
| /supporting-forms-for-claims/support-statement-21-4138/phone-and-email | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/contact-information	| Phone and email address |
| /supporting-forms-for-claims/support-statement-21-4138/statement | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/statement	| Statement |
| /supporting-forms-for-claims/support-statement-21-4138/review-and-submit | /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/review | Review |

### 21-4138 subtask flow

| Current url |	New url	| Page description | CAIA Approved | 
| :--- | :--- | :--- | :---: |
|/supporting-forms-for-claims/support-statement-21-4138/statement-type|/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/statement-type|Select statement type |
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/lay-or-witness-handoff| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/lay-witness-statement	|Suggests alternative, VA Form 21-10210, Lay/Witness Statement. |
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/decision-review|	/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/decision-review|	Asks about the claim's decision date||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/notice-of-disagreement-old-handoff|/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/new-supplemental-claim	|The decision is older than a year, so we suggest filing a supplemental claim|
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/decision-review-type|/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/select-decision-review|Select disagreement reason||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/notice-of-disagreement-supplemental-handoff |	/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/supplemental-claim	| They have new evidence, so we suggest filing a Supplemental Claim| |
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/notice-of-disagreement-hlr-handoff	|/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/higher-level-review	|Suggests requesting a Higher-Level Review||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/notice-of-disagreement-ba-handoff	| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/board-appeal	|Suggests requesting a Board Appeal||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/priority-processing-intro	| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/about-priority-processing |	Priority processing introduction||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/priority-processing-living-situation |/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/housing-risks	| Select a housing situation||
| |	/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/other-housing-risk |	Other housing risks||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/priority-processing-other-reasons-optional	| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/hardships	| Other hardships||
|	| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/statement-to-support-claim |Not qualified for priority processing, so we suggest submitting a 4138 statement|||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/priority-processing-qualified-handoff |	/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/priority-processing-request	|Suggests requestion priority processing||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/records-request-handoff |	/supporting-forms-for-claims/statement-to-support-claim-form-21-4138/personal-records-request |	Suggests requesting personal records||
|https://staging.va.gov/supporting-forms-for-claims/support-statement-21-4138/new-evidence-handoff	| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/claim-status-tool |	Suggests claim status tool||
|/supporting-forms-for-claims/support-statement-21-4138/vre-request-handoff	| /supporting-forms-for-claims/statement-to-support-claim-form-21-4138/chapter-31-support-request	| Suggests requesting chapter 31 support||

**Comment by rachelshearerux** [comment]
@pennja, I updated the ticket with a link to the new URLs, documented [➡️ here in the GH project folder](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4138/21-4138%20URLs.md). 

Thank you, @mnorthuis and @jennymayoco!

**Comment by jennymayoco** [comment]
Thanks so much for your work on this @rachelshearerux! I've also documented these URLs in the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4138.md), including the URL for the form. Just noting that the rest of the IA spec is a work in progress in case of any findings we learn from research.

<img width="1063" alt="Screenshot of URLs" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/013f0909-d25e-45e2-96e6-ecee9cb5d146">

cc @megzehn for awareness

**Comment by rachelshearerux** [comment]
I'm still seeing old urls for these three pages:

| Current URL | New CAIA-approved URL |
| :--- | :--- | 
|/statement-to-support-claim-form-21-4138/priority-processing-other-housing-risks | /statement-to-support-claim-form-21-4138/other-housing-risk |
| /statement-to-support-claim-form-21-4138/priority-processing-other-reasons | /statement-to-support-claim-form-21-4138/hardships |
| /statement-to-support-claim-form-21-4138/review-and-submit | /statement-to-support-claim-form-21-4138/review

**Comment by pennja** [comment]
Thanks @rachelshearerux, the `review-and-submit` URL is actually a protected URL which is automatically added to all of our forms. In order to change this one, I'd recommend a new ticket which can be dedicated to updating all of the underlying logic which manages this route. It would be a considerable lift to ensure the route continues to work as expected for all other forms in `vets-website`.

**Comment by rachelshearerux** [comment]
@pennja thank you, noted! I'll coordinate with CAIA to see if we want to make this a global update, and if so, get a ticket filed for the change.

@jennymayoco @mnorthuis FYI

**Comment by jennymayoco** [comment]
Hi @pennja thank you for this background! @rachelshearerux and I connected on this and understood the additional lift to change the sub-url for the review page. Let's move forward with `/review-and-submit`
