### ISSUE TITLE
Gather 2122 VSOrg stats using the BGS<>CorpDB integration

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#82278]
### Description
The below screenshot shows which VSOrgs handle the most volume:
<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2EwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e7b6539916c27f7b8dd4b826f0b11fc54a29a79/image.png" alt="image.png" />

> For the number of uploads to Quick Submit, which could be a useful data point as far as scale, the second VSO after DAV is the American Legion, followed by VFW. If we're curious about looking at a state, the North Carolina DVS has the highest numbers. These might be worth targeting for future use, even if they aren't SEP users now.

For each of the large VSOrgs pictured above, check to see how many total 2122 requests they have in CorpDB, how many are 'New', 'Pending', 'Accepted', and 'Declined'. If you think of the data points to look into, go for it!

Use the below Slack canvas as a guide:
https://dsva.slack.com/docs/T03FECE8V/F071ERTJU3C

BGS Catalog:
https://github.com/department-of-veterans-affairs/bgs-catalog/blob/main/VDC/ManageRepresentativeService/ManageRepresentativePortBinding/readPOARequest/response.xml

Data Points to consider:
-Decline Reasons
-Claimant/Veteran Address (cross state orgs, non-US countries)
-Origination Date for request vs date of status change
-Requests open for more than 30 days 

### Acceptance Criteria
- [ ]  Report on CorpDB POA request stats for all the large VSOrgs

**Comment by a6marinos** [comment]
@a6marinos Follow up w/ Lindsay and ARM team on any analytics/metrics to support which orgs are most active in SEP currently.
