### ISSUE TITLE
[BE] My VA Forms Status: establish connection with GET /uploads/{id} endpoint

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#82287]
## Background
We need to set up the backend for the forms status work on My VA. We need to ensure that the user endpoint can include statuses along with the array of drafts that it fetches. This ticket is to establish a connection with the GET/uploads/{id} endpoint form vets api and expose the new vets api endpoint to the frontend. Documentation in swagger will also be needed for this.

## Tasks
- [ ] ... 

## Acceptance Criteria
- [ ] ...

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_
- _How can this work be validated?_

**Comment by ajakabcin** [comment]
not needed for MVP requirements

**Comment by ajakabcin** [comment]
Per discovery this is not needed for MVP

**Comment by DanielMiller-agile6** [comment]
this is no longer needed now that we're using the [new endpoint Tom created](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/form-status/backend_documentation.md). closing this out.
