### ISSUE TITLE
Midpoint Review - Content - Iterate Innovate Run, Performance Dashboard, NA #67917

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#82283]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions
Looking good! Please let me know if you have any questions.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- Highlights section - The user finds the following sentence: "The VA is committed to providing world class and timely healthcare..." There should be a hyphen: world-class. Please revise to: "The VA is committed to providing world-class and timely healthcare..."
- Throughout the prototype: logged in versus signed in - There are several instances where the user finds "logged in" used instead of "signed in." According to the [Style Guide](https://design.va.gov/content-style-guide/word-list#l), we use "sign in/sign out" instead of "log in/log out." Please revise to "signed in."
-  Usage details - The user finds the subheading "Total signed in sessions." There is a hyphen missing: "signed-in." Please revise to: "Total signed-in sessions."

## Governance team actions
- [ ] Format feedback as individual tasks (check boxes)
- [ ] Assign this ticket to the VFS team member that opened the Slack request
- [ ] Add the VFS team product label
- [ ] Add the VFS team the feature label (if applicable)
- [ ] Add the touchpoint labels
- [ ] Add the practice area labels
- [ ] Add the Collaboration Cycle initiative milestone
- [ ] Add the Collaboration Cycle initiative epic

**Comment by raquelou** [comment]
Updates have been made to designs
