### ISSUE TITLE
[Discovery] Logged-in homepage: User research — Create card sort

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8230]
## Background

Epic #7268

As part of the logged-in homepage discovery phase, we have decided to conduct user a card sort to help us better gauge user needs and expectations.

## Tasks

- [x] Design card sort

## Acceptance criteria

- [x] Card sort is ready for testing

**Comment by andaleliz** [comment]
Making a note while looking at past research and thinking of it - these were tasks users went through on while authenticated as part of the brand consolidation research, could be ideas for cards:
Refill Prescriptions
Secure Messaging
Check Vitals
Check Claim Status
Upload Evidence
Check Payment History

also CC @sshein so you can follow this ticket.

**Comment by Samara-Strauss** [comment]
Thanks for this! At some point, let's talk over the [card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/personalization%202.0/discovery-research/card-sort/research-summary.md) I did last summer and what I think worked well/what didn't.

**Comment by andaleliz** [comment]
Making some notes here for documentation.  @Samara-Strauss [created a preliminary list of cards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/user-research/card-sort-list.md ) and shared via Slack [in this post](https://dsva.slack.com/archives/G010FUP1KLG/p1588190031013900).

Via the thread there, we decided to eliminate:
>GI Bill payments made to you by the VA
and instead use a card that says **Payments made to you by the VA**

And also add a card that reads "Updates on your claim or appeal status" to get at the idea of an alert or notification (without actually saying those words), vs "tracking" which could be something more subtle than an alert.

**Comment by Samara-Strauss** [comment]
@andaleliz in case it wasn't clear, you can totally use the doc I created to update the list if you want. I know there's some weirdness around updating other people's docs, but I created this with the intention of passing it off to you entirely.

**Comment by andaleliz** [comment]
@Samara-Strauss Thanks for clarifying! I'll update it with our new list then.

**Comment by andaleliz** [comment]
[Here's a link to the card sort](https://adhoc.optimalworkshop.com/optimalsort/7o81t7ix) we reviewed earlier today @Samara-Strauss 

If there are no changes, I think we can close this out... and then we're ready to submit to Lauren!

**Comment by Samara-Strauss** [comment]
This looks great! I think we're ready to submit to Lauren! 🎉

**Comment by andaleliz** [comment]
Woo hoo! I'll close this and submit to her.
