### ISSUE TITLE
VA Form 21-4138: Update primary action links

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#82306]
Jeana Clarke and Matthew Dingee have put together an experimental primary action link that we'd like to implement in the Form Upload.

The eventual goal is for the design system to replace the current primary action link with a new, more noticeable "primary" link.

There are a few primary action links in the subtask ofVA form 21-4138, please update these pages:

| Page | New action link | 
| :--- | :--- | 
| [Introduction page, when LOA3 verification is required](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=1163%3A220282&mode=design&t=WcIAT799Vi26ZmpO-1)  | <img width="1861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnExQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7fc220dcbae0e4bc240105d4382db2b619a18b6/image.png" alt="image.png" /> | 
| [Introduction page, when they're LOA3 authenticated](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=1042%3A298878&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnkxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f449784862e20db47fabfc88514dcc470fe00ab/image.png" alt="image.png" /> |
| [Subtask end: Lay or Witness statement](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239143&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1899" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMisxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c32254087f63ba482cb7f6bf9c3ce50052784157/image.png" alt="image.png" /> |
| [Subtask - NOD - Endpoint - Old decision ](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239195&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0sxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d88e264266b33170e6c419830f9400368b12e3e/image.png" alt="image.png" /> |
| [Subtask - NOD - Endpoint - Supplemental](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239215&mode=design&t=WcIAT799Vi26ZmpO-1)| <img width="1865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ExQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8935e97b310619fbdbca880fa1cddfef85c31b82/image.png" alt="image.png" />|
| [Subtask - NOD - Endpoint - HLR](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239217&mode=design&t=WcIAT799Vi26ZmpO-1) | [Uploading... image.png] | 
| [Subtask - NOD - Endpoint - Board appeal](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239227&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM20xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02feb5e77215147ffa931822c3ba855b68330674/image.png" alt="image.png" /> | 
| [Subtask - Priority Processing - Endpoint - Qualified ](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239252&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3UxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7bd5c60602c8782d365470e2cde708b0af31a54/image.png" alt="image.png" /> |
| [Subtask - Records request - Endpoint](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239141&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3kxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20001bdf2ad484c7840c9abdf17ec956bfddaeae/image.png" alt="image.png" >| 
| [Subtask - Evidence - Endpoint](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239134&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMysxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2fde8403034ca21cf517ae77c6acd4455dd5fd0/image.png" alt="image.png" /> |
| [21-4138 - Confirmation](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A264332&mode=design&t=WcIAT799Vi26ZmpO-1) | <img width="1754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEMxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a112e9d04e1c90de931ec89e65d75cc5a8d41856/image.png" alt="image.png" />
 | 
 

---
### Resources
- [ ] [21-4138 designs](https://www.figma.com/file/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?type=design&node-id=786%3A239227&mode=design&t=WcIAT799Vi26ZmpO-1)
- [ ] [New action link design](https://www.figma.com/file/jnxB6t5V4xgv1WcIL71Qgz/WIP%3A-Form-Upload?type=design&node-id=1%3A21&mode=design&t=k4dmIxH7oF4QXrsV-1) (collaboration between Jeana Clarke and Matthew Dingee)
- [ ] [Experimental design ticket for new action link](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1459)

**Comment by megansiddle** [comment]
Still wonky with the little triangle

**Comment by rachelshearerux** [comment]
Hey @pennja it looks great everywhere at 100% There are a handful of browser/zoom views where a thin line separation of occurs in the blue background / arrow cap. 

<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS8zQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff89c750981ec1f46da2fe8ba73f35099f23de2e/Screenshot%202024-05-20%20at%204.27.22%E2%80%AFPM.png" alt="Screenshot 2024-05-20 at 4.27.22 PM.png" />


---
|Browser | Zoom % when the separation happens |
|:---|:---|
|Firefox |110%, 120% |  
| MS Edge |90%| 
| Chrome | 90%| 
| Safari | 90%, 110% |

**Comment by rachelshearerux** [comment]
These have been implemented, and I created a bug ticket for the issue with the line of separation [(#83670)](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/83670).
