### ISSUE TITLE
[Discovery] Logged-in homepage: User research — Create co-design with veterans exercise

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8232]
## Background

Epic #7268

As part of the logged-in homepage discovery phase, we have decided we'd like to do a co-design exercise around the homepage instead of user testing the existing homepage or blue sky prototype. We hope this will give us a better idea of what veterans need/want without priming them too much with existing models.

## Tasks

- [x] Plan co-design exercise

## Acceptance criteria

- [x] Co-design exercise is ready for research

**Comment by andaleliz** [comment]
[Here's an example of the mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1588287883697/58994facc18f9750768a0992b9a6bafb2aacd9fe) we'll use for co-design exercise.  We'll create a new board for each participant.

Approach detailed in [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/user-research/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/user-research/conversation-guide.md).
