### ISSUE TITLE
QC Initial Domo Report - VA.gov VA Notify KPIs 

### ISSUE THREAD

**Issue by ChristineYoungZA** [department-of-veterans-affairs/va.gov-team#82333]
### Description
This ticket is account for QC'ing the VA.gov VA Notify KPIs dashboard with the newly create GA4 view. Focus on QC'ing the metrics specifically for changes in the naming conventions, confirm beast modes/charts are functioning and if they aren't identify what is the cause of the issue. 

**Note:** this dashboard is made up of 39 cards. All of that information and more and be found in [this document](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=721881515). 

### Tasks
Simple Standard QC Process Suggestion: 
1. Clarify what data is needed from BQ: specify what fields are needed, level of detail/aggregation, etc. - Send to Phil
2. Load initial 1 weeks worth of data to QA the following: 
         - Google Analytics: most metrics have equivalents in GA that can be reproduced. Compare between BQ view and  
            GA reports. 
         - Other data in BQ: query new view against existing views to spot check. Useful to pull small campaigns or 
            sessions. 

- [ ]  Test

---

### Acceptance Criteria

- [ ]

**Comment by johnny-jesensky-adhoc** [comment]
Merging our GA4 Domo Data QC into grouped tickets -- closing this one out.
