### ISSUE TITLE
[TechDebt] Migrate Radio Buttons V1 to V3 - Disabilities PTSD Chapter

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#82352]
Followup to #76057 
[PR #29199](https://github.com/department-of-veterans-affairs/vets-website/pull/29199) contains a sample of needed changes

## Front end tasks
- Update all v1 radio buttons from table below to v3 
- Ensure the page is styled according to design spec. 
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

| file                             | chapter      | page                                                                  | notes |
| -------------------------------- | ------------ | --------------------------------------------------------------------- | ----- |
| individualsInvolved.js           | Disabilities | disabilities/ptsd-individuals-involved-${index}                       | ptsd  |
| individualsInvolvedFollowUp.js   | Disabilities | disabilities/ptsd-individuals-involved-questions-${index}\`           | ptsd  |
| ptsdAdditionalEvents.js          | Disabilities | disabilities/ptsd-additional-events-${index}                          | ptsd  |
| ptsdBypassCombat.js              | Disabilities | new-disabilities/ptsd-combat                                          | ptsd  |
| ptsdBypassNonCombat.js           | Disabilities | new-disabilities/ptsd-non-combat                                      | ptsd  |
| ptsdSecondaryAdditionalEvents.js | Disabilities | disabilities/ptsd-781a-additional-events-${index}                     | ptsd  |
| secondaryOtherSources.js         | Disabilities | disabilities/ptsd-secondary-other-sources-${index}                    | ptsd  |
| secondaryUploadSourcesChoice.js  | Disabilities | disabilities/ptsd-secondary-upload-supporting-sources-choice-${index} | ptsd  |

**Comment by freeheeling** [comment]
Submitted [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30389) for review. Awaiting results from CI checks.

**Comment by freeheeling** [comment]
Merged and deployed to prod.

<img width="1546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzkrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--942d9230f568619042b45cddaa64e56ffc2b993e/Screenshot%202024-06-20%20at%204.10.52%E2%80%AFPM.png" alt="Screenshot 2024-06-20 at 4.10.52 PM.png" />
<img width="1546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzErQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ffb3aad17f4d593d7ccd3fb0cf00f2265348341/Screenshot%202024-06-20%20at%204.10.36%E2%80%AFPM.png" alt="Screenshot 2024-06-20 at 4.10.36 PM.png" />
