### ISSUE TITLE
Audit and Update the Figma Files for Priority 1 (New Landing Page w/ Upcoming Appointments)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#82358]
## Description
We need to review the Figma files for this Epic (i.e. New Landing Page w/ Upcoming Appointments) to ensure that all changes that have happened since we started this Epic are accounted for in the Figma Files.

**NOTE: we want to focus on Priority 1 Figma files only for this effort, I don't want to get bogged down in updating all of the priorities right now**

## Tasks
- Audit the Figma files for Priority 1
- Update the Figma Files for Priority 1
- Make a list of all of the changes that were made and put them in this ticket so Lori can create an engineering ticket for the work to bring the product up-to-date

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/82358?planning-poker) with Zenhub @benbrasso-agile6 @zach-park

**Comment by benbrasso-agile6** [comment]
Looking at these again this morning. This will be complete by sprint end. We'll likely schedule some time with engineers to make sure we're on the same page. Stay tuned for that invite.

**Comment by cgednalske** [comment]
Validated
