### ISSUE TITLE
[Design][Discovery] - Profile 2.0 - Benefits 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8235]
## Background
We would like to Figure out where Benefits should live?  We will need to work with benefits team to see what we can pull, what needs to be presented. Also, what aspects of benefits do ppl want to see? What will be shown in the profile vs logged in homepage?

## Tasks
- [ ] Create research doc for benefits within profile

**Comment by Samara-Strauss** [comment]
I'm actually gonna close this because we are going to look into this with logged in homepage research. That work is being tracked in #7268.

**Comment by mshea0606** [comment]
@Samara-Strauss ok sounds good

**Comment by Samara-Strauss** [comment]
But thank you for being on top of things and creating a ticket! I appreciate it.
