### ISSUE TITLE
Time zone issue on unit tests

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#82397]
## Description
The VAOS unit tests currently run and use timestamps that start in the local timezone. That could be the local developer timezone (PDT, EDT, etc) or could be UTC when the tests are automatically run in the CI pipeline. This causes the tests to erroneously fail at times either within the remote CI pipeline and/or locally depending on what the current time is and what timezone the tests are ran in.

To guard against this and improve developer experience, tests should:
- Always be run in UTC so that the local test environment mirrors the CI pipeline environment more closely
- Use a standardized way of mocking a date for test purposes

---

## Acceptance Criteria
- [ ] Tests no longer fail periodically

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by Bren22va** [comment]
Converted this to a Spike to determine the best approach for this issue.

**Comment by ryanshaw** [comment]
Converted from a spike issue to regular issue and added sizing

**Comment by ryanshaw** [comment]
@Bren22va I'm closing this as it has been merged in and reviewed by other developers. It's not something that product or QC can validate -- just updates a unit test.
