### ISSUE TITLE
Monthly CSP report

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#82405]
Pull monthly CSP use (unique logins, including mobile) and send to Gus/Sophia on the last day of the month.

Def of Done

- [ ] Monthly CSP data pulled from Domo/Datadog, etc
- [ ] csv file emailed to gus@themostudio.com and sophia@themostudio.com
- [ ] Gus/Sophia email to Tom/Samara on the 1st of the month

**Comment by schisslerg** [comment]
This was the report for the month of april, delivered on May 1. I'll duplicate this for the month of May (delivered on June 1)
