### ISSUE TITLE
Flipper UI access for Nate Douglas

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82414]
### Your Name

Nathan Douglas

### Your GitHub handle (Flipper UI access is managed through GitHub)

ndouglas

### Team, Role, and Company of the target individual

Check-In Team, DevOps, Agile Six

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Reconfiguring vets-api to make BTSSS requests via fwdproxy, need to switch the flipper for that.

**Comment by bdech** [comment]
@ndouglas, you've been granted access to `production`, and `lesser` environments.
