### ISSUE TITLE
Ensure that PRT EKS testing contributors have required permissions

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#82410]
# Description
Given that we are expecting to have to create and modify Datadog synthetic monitors by contributing code to `devops` Terraform code, contributors need to verify their permissions are sufficient from both a `devops` repository context as well as Terraform. Contributors should also familiarize with best practices for contributing code.

# Acceptance Criteria
- [ ] Contibutors' required permissions are verified
- [x] Contributors are aware of best practices and have documented them for team use

**Comment by pjhill** [comment]
Which permissions do we need exactly?
Here's what we want to be able to do --
* Review synthetic tests / monitors in Datadog
* Manipulate the configuration of synthetics directly in Datadog
* Create/modify synthetics as terraform code in `devops`

**Comment by pjhill** [comment]
My access to the [Datadog instance](https://vagov.ddog-gov.com/dashboard/ugi-r9m-ezp/eks-cpu-and-memory?fullscreen_end_ts=1687404282187&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1687317882187&fullscreen_widget=7879059333458880&tpl_var_kube_cluster_name%5B0%5D=dsva-vagov-dev-cluster&tpl_var_kube_namespace%5B0%5D=aws-ebs-csi-driver&from_ts=1687441384120&to_) has been removed???

**Comment by pjhill** [comment]
@IGallupSoCo -- I'm just jumping back into this, and I feel like I'm behind you. What is the set of permissions that you've requested for this task?

**Comment by IGallupSoCo** [comment]
I had to climb two different tiers of access.  Initially, they granted me a read-only account.  That was useful for seeing the dashboards, but blocked me from going deeper.  I will see if the Citrix issues from the beginning of the week have been fixed.  If so, I can retrieve the details of my request tickets and share them here.

**Comment by IGallupSoCo** [comment]
<img width="192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80d7e59767e8b138cd7813a2849e3d50b1b586ac/Screenshot%202024-05-16%20at%2010.35.48%E2%80%AFAM.png" alt="Screenshot 2024-05-16 at 10.35.48 AM.png" />

I'll share this messy screenshot here for posterity, since I can't paste the text inside the virtual desktop, where I can reach the ECC ticket system.

**Comment by pjhill** [comment]
Thanks Isaac, this morning I finally got my request in. I'm not sure why my original access was removed.

My request ID is -- REQ26451630

**Comment by pjhill** [comment]
No movement on my DD ticket

**Comment by pjhill** [comment]
I have access to Datadog now.

**Comment by pjhill** [comment]
I do not have permission to synthetic tests --
<img width="749" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGIzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--505ed2fc17b8b333afee9a8123b41cac4b054919/image.png" alt="image.png" />

**Comment by pjhill** [comment]
Reviewing the ticket update, I need to authenticate through Okta and then ping the agent who is processing this ticket --
<img width="911" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXIzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40f83fe22ddfd12802931bad4c9135501c103858/image.png" alt="image.png" />

**Comment by IGallupSoCo** [comment]
It looks like ECC has some kind of standard of never giving users a straight shot to write access.

**Comment by pjhill** [comment]
Still no movement on escalated permissions --
<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi85QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cde66139d49f54c8ff0bdc2720f9b12b3417926a/image.png" alt="image.png" />

**Comment by pjhill** [comment]
Given that most of this ticket is complete -- I'm going to plan to move the permission escalation from this ticket to a new ticket if it is still not closable tomorrow.

**Comment by pjhill** [comment]
Still unable to modify DD tests and monitors -- I'm breaking this lingering `write` permission out to a new ticket for the next sprint.
