### ISSUE TITLE
[Decision Reviews] Replace HTML redirect with server-side

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#8241]
We have a page in vagov-content that implements an HTML redirect located [here](https://github.com/department-of-veterans-affairs/vagov-content/blob/master/pages/decision-reviews/get-help.html). This was implemented this way because the greedy nature of our server-side redirects would have swallowed up traffic that it shouldn't. We should implement this redirect 

src: `/decision-reviews/get-help/`
dest: `/decision-reviews/get-help-with-review-request/`

The trailing slash in the `src` is optional, but the redirect should not be greedy or else it'll create a redirect loop.

## Acceptance criteria
- [ ] Redirect is implemented server-side
- [ ] vagov-content page doing the current redirect is deleted (`decision-reviews` dir)

**Comment by kelsonic** [comment]
@ncksllvn I think [we already have this server-side redirect](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml#L314) in-place ([related ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17663))

**Comment by ncksllvn** [comment]
@kelsonic ah good catch - I think the HTML redirect is there to catch the version without the trailing slash. I think the slash needs to be optional, but as a non-greedy redirect

**Comment by stephorkandatx** [comment]
@kelsonic or @ncksllvn How might we validate this change?

**Comment by ncksllvn** [comment]
Just by visiting va.gov/decision-reviews/get-help/ and observing the redirect to /decision-reviews/get-help-with-review-request/
