### ISSUE TITLE
Vets-api terminal access for Nate Douglas

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82415]
### Your Name

Nathan Douglas

### Your GitHub handle (terminal access is managed through GitHub)

ndouglas

### Your dsvagovcloud AWS user name (if applicable)

Nathan.Douglas

### Team, Role, and Company of the target individual

Check-In Experience, DevOps, Agile Six

### Product Manager (PM) name and email

Lori Pusey (lori.pusey@agile6.com)

### Product Owner (PO) name and email

Kay Lawyer (katherine.lawyer@va.gov)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [x] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![Screenshot 2024-05-06 at 12 13 30 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/bac61563-d44d-4b10-9e91-c9e820c4ef37)

I'm reconfiguring `vets-api` to send BTSSS requests via fwdproxy, need to poke around and confirm environment variables are being set correctly, that sort of thing.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Confirmed in Atlas
E-QIP confirmed

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@ndouglas You've been granted access to `Production`, with access to Production limited to 6 months, expiring 11/5/24.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1715024361221539)

**Comment by bdech** [comment]
@ndouglas Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by ndouglas** [comment]
@bdech I'll allow it to lapse; I don't normally work in this area. Thank you!

**Comment by bdech** [comment]
Thanks for letting me know Nate.

**Comment by bdech** [comment]
Production access revoked
