### ISSUE TITLE
Confirm Burial Form 21P-530EZ in Domo

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82436]
### Description

This task is to perform a QC of the work done in this ticket  -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80861 because that next data refresh won't happen until _**Sunday, May 12,**_ we are creating a separate tasks to confirm this then.

---

### Tasks
- Confirm is displaying in Forms KPI Dashboard
- Comment on original ticket with update, https://github.com/department-of-veterans-affairs/va.gov-team/issues/80861

### Acceptance Criteria

- [ ] Form has been verified in Domo and screenshot attached.

**Comment by ChristineYoungZA** [comment]
@dorseypa1 the 21p-530 EZ form still isn't showing in the Forms dashboard, can you take a look and see if it loaded over the weekend?

**Comment by dorseypa1** [comment]
It looks like the issue is the 'https' in the loading sheet for the steps and forms.  The urls need to start with just www, no https://.   I'll update them directly in the database to remove the https from the urls.

**Comment by dorseypa1** [comment]
I removed the "https:://" from the landing_page, root_url, and step_link in for all of the records for this forms.  A test run of the query that Domo uses pulls the data now.  
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/277ea8c7-b7af-4f09-a287-d3ef64fc8966)

**Comment by dorseypa1** [comment]
Domo should pull the records on the next refresh.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA - Note to check back in on this _**next Monday, May 20th.**_

FYI @Blivaditis

**Comment by johnny-jesensky-adhoc** [comment]
Hi @steele-lm  -- confirming that the 21-530EZ form has been successfully loaded into the Forms KPI dashboard -- thank you for your patience as we got this one loaded.

It can be accessed [here](https://va-gov.domo.com/page/447193050).

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/aa602818-d4e3-4eb1-8259-e5d98c34597a)

FYI @Blivaditis, @dorseypa1, @Blivaditis

**Comment by steele-lm** [comment]
@johnny-jesensky-adhoc Thanks for standing up the dashboard for the burial form. Is it possible to update the dashboard name to follow the pattern of the other dashboards (form number + benefit name)? In this case it would be 21-530EZ - Burial Allowance
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/b2487a76-e871-483f-8c83-89d5b45e681a)

**Comment by johnny-jesensky-adhoc** [comment]
Hi @steele-lm -- our data engineer made the change, so the name change should be reflected on Monday (6/2). Thanks!

FYI @dorseypa1
