### ISSUE TITLE
[SCREENREADER, COGNITION]: Directions link – Purpose of a link MUST be clear in link text

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#8243]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Within each search result there is a link for Directions. WCAG 2.0 success criteria states link text **must** make sense in context, and should make sense when taken out of context (problematic phrases include: “click here,” “learn more,” “more,” “read more,” etc.) [[WCAG 2.4.9](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-link.html), [WCAG 2.4.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html)]. 

### Why it Matters

For sighted users it is clear that the Directions link is part of the search result. For non-sighted users hearing the search results, visual design isn't available to support comprehension, so it is added using `aria-label` attributes or screen reader only text.

This rule is important because the intention is to to help users understand the purpose of each link in the content, so they can decide whether they want to follow it. Best practice is that links with the same destination would have the same descriptions, but links with different purposes and destinations would have different descriptions (see also [Success Criterion 3.2.4](https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification) which calls for consistency in identifying components that have the same functionality). Because the purpose of a link can be identified from its link text, links can be understood when they are out of context, such as when the user agent provides a list of all the links on a page.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As I screen reader user, I want to explicitly know the purpose of the link on a page.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: production

## Steps to Recreate

1. Enter https://staging.va.gov/find-locations in browser
2. Start screenreading device listed in Environment
3. Enter search criteria and submit via the search button
4. Listen to the search results
5. Verify it says "link, Directions"

## Possible Fixes (optional)

The industry best practice is to include an `aria-label` attribute or screen reader only clarity to the link as follows.

### Current code
```html
    <span>
      <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=1401 Medical Parkway, Suite 400, Building C, Cedar Park, TX 78613-2216" 
        rel="noopener noreferrer" target="_blank" style="text-decoration: underline;">
        Directions
      </a>
    </span>
```

### Suggested fix
```diff
    <span>
      <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=1401 Medical Parkway, Suite 400, Building C, Cedar Park, TX 78613-2216" 
        rel="noopener noreferrer" target="_blank" style="text-decoration: underline;">
        Directions 
!        <!-- dynamically add name of facility to sr-only text -->
!        <span class="sr-only">Cedar Park VA Clinic </span>
      </a>
    </span>
```
### Alternative fix
```diff
    <span>
      <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=1401 Medical Parkway, Suite 400, Building C, Cedar Park, TX 78613-2216" 
        rel="noopener noreferrer" target="_blank" style="text-decoration: underline;"
!      aria-label="Directions to dynamically add name of facility">
        Directions 
      </a>
    </span>
```

## WCAG or Vendor Guidance (optional)

* [Ensure that links with the same accessible name serve a similar purpose, Deque University](https://dequeuniversity.com/rules/axe/3.5/identical-links-same-purpose?application=AxeChrome)

**Comment by mmiddaugh** [comment]
This is an important issue but unrelated to the facility-level operating status. It was an existing issue in the backlog.

**Comment by jenstrickland** [comment]
I'll remove the facility epic assignment.

**Comment by mmiddaugh** [comment]
Closing as duplicate to https://github.com/department-of-veterans-affairs/va.gov-team/issues/6894
