### ISSUE TITLE
Landing page and secondary nav links handle new root font size

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82433]
### User story

As a Cartography team member, I want to ensure that the updated `root` font sizes of the VADS don't change the size of fonts on the MHV landing page, so that Veterans' experience is unchanged.

### Notes
- [Platform announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1714612416352079) of change in style and why it shouldn't affect apps
- VADS [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) linked from that announcement
- [slack](https://dsva.slack.com/archives/C04DRS3L9NV/p1715017222333279?thread_ts=1715014885.889939&cid=C04DRS3L9NV) - Daniel's analysis of why 
- Updates should be merged into department-of-veterans-affairs/vets-website/pull/26606 before it goes live
  - Team to ask DST if they agree with us updating their PR

Possible tasks:
- 

## Acceptance criteria

- The MHV landing page is styled such that the VADS's tweaks in their [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) don't cause a visible change _for even a second_
- Same for MHV secondary nav component
- QA review

**Comment by dcloud** [comment]
We may also need to tweak `rem` values in Secondary Nav, as mentioned on department-of-veterans-affairs/vets-website/pull/29592

**Comment by dcloud** [comment]
Looks like the landing page changes exist in the big PR now: https://github.com/department-of-veterans-affairs/vets-website/pull/26606/files?show-viewed-files=true&file-filters%5B%5D=#diff-3eb65c1def06b4b948dd2d4ffc6cc930ec11fda40bd770611d62866f4b1e8c3c

Things under `src/platform/mhv`, e.g. **Secondary Nav**, appear uncoverted at this time

**Comment by dcloud** [comment]
Created a PR pointing to the bigger PR, and [left a review comment](https://github.com/department-of-veterans-affairs/vets-website/pull/26606#pullrequestreview-2053691432) asking for those minor changes

**Comment by dcloud** [comment]
The Secondary Nav changes are merged into the larger PR, department-of-veterans-affairs/vets-website/pull/26606, and I have review typography/spacing changes on that branch and things look good.

I think this is done as far as we are concerned, but I don't know the ETA for when the bigger PR will get merged

**Comment by dcloud** [comment]
The larger PR has been merged
