### ISSUE TITLE
Add logs for ATO audit events - Terms and conditions

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#82447]
## Terms and conditions events

Create the ability for the following logs to be viewed in datadog for auditing purposes
- [x] Lack of logs over a one day period
- [ ] User accepts terms and conditions more than 10 sessions in 5 minutes
- [ ] (do we track which terms the application was initiated from? We may consider unknown applications for terms acceptance to be unusual)
- [ ] Multiple failed attempts to accept the terms
- [ ] Multiple changes in the users decision, accept or deny, in a short period of time.
  - Initially stick with more than 10 decisions in 5 minutes.
- [ ] High number of deny terms for an individual user
  - More than 5 times in an hour

**Comment by parkerbees** [comment]
Moved to Jira, closing
