### ISSUE TITLE
Add logs for ATO audit events - Security token issuing events

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#82448]
## Security token issuing events

Create the ability for the following logs to be viewed in datadog for auditing purposes

- [x] Lack of logs over a one hour period
- [ ] Higher number of tokens issued than normal
- [ ] Tokens issued to a client ID not on the approved list
- [ ] Unauthorized attempts to modify the list of approved client IDs (on github and within vets-api running instances)
  - Not sure how to execute on this one yet
- [ ] A token with a longer than possible expiration date
- [ ] High numbers of requests during hours they would not normally be expected
- [ ] Multiple failed attempts to request a token from the same client ID
- [ ] attempted tampering of a JWT to change roles (aud)

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
