### ISSUE TITLE
SOCKS access for Gabriela Canchola

### ISSUE THREAD

**Issue by gcan-va** [department-of-veterans-affairs/va.gov-team#82455]
### Your Name

Gabriela Canchola

### Your Email

canchola_gabriela@bah.com

### Your GitHub Handle

gcan-va

### Your Role and Team

Associate Product Manager

### Product Manager (PM) name and email

Joseph Justice justice_joseph@bah.com

### Product Owner (PO) name and email

Dawn Pruitt Dawn.Pruitt@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD2XWVGLPZilDy10t8UPnjsEoU1ea2iGfaOOFFvFDCoQAc3vzRMaD1kZESCWkGhSIKSuMxQev0Vn/IiSKo8Qu7m8JyZoxTO9l0BnetqRe1UJpbzmZltUxCYaaBlVEnQigAvDeDsbhWBpiZWPvkmA+kuQAK6JrYU705sgDbbsaIeaWaIXIBBb4SBbf9Q9yDrzDGSRXk/zvrhyd4SSMSXFZdHhfi9SYxtEt67Q9zapUvGv9bw1UBP7Fml6UUfoDgynUe2K2qAjAXb9nDIzUEly8VX2RvjFY/gFdFlznJnB4P38HK2ouEWvPaMo290tBF46eFYCIosxvCbdosLHmesQHGvY7fPxMeodCTeD6QM3Qryazapmjo+yRR4jKDeQqFKp+NY+YOxBhT2VTrWZ1rXx/H5LWf6FGRoDBZISXJapGFyLB/0jXhmv4FpliXNxWVske91O45PFnVdbj3GqPZYVRtVuK+VAmI5mcQLPa0SHcghAuD2GOeohhPCDVMAMqccgc= root@BAH5CD4010XX3
### E-QIP Transmittal Confirmation

![Capture](https://github.com/department-of-veterans-affairs/va.gov-team/assets/162593378/9d759856-4150-454a-ad73-22a543999f6f)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@gcan-va your ssh key seems to be invalid. Do you mind sharing where/how you got it? I can give you instructions, they'll be a little technical, so I can jump on a quick call, if you like, too.

**Comment by gcan-va** [comment]
Booz Allen Hamilton Internal

That would be amazing! When I did the vtk socks setup, I accidentally copy and pasted something else and lost the SSH key and I’ve been having a hard time finding it to add to this.
________________________________
From: christopher floess ***@***.***>
Sent: Tuesday, May 7, 2024 10:02:32 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Canchola, Gabriela [USA] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] SOCKS access for Gabriela Canchola (Issue #82455)

@gcan-va your ssh key seems to be invalid. Do you mind sharing where/how you got it? I can give you instructions, they'll be a little technical, so I can jump on a quick call, if you like, too. — Reply to this email directly, view it


@gcan-va<https://urldefense.com/v3/__https://github.com/gcan-va__;!!May37g!I7kcZ1Cb93uOmLGWEx7qdICk3NZFKfl1UkT18Zxpu-zVRxRw8h9zYYfZ3Zz_CTAUxCgOcPwLCbOr-m5yJpS31zu9TI8c$> your ssh key seems to be invalid. Do you mind sharing where/how you got it? I can give you instructions, they'll be a little technical, so I can jump on a quick call, if you like, too.

**Comment by flooose** [comment]
I'll reach out to you about this this afternoon

**Comment by gcan-va** [comment]
Booz Allen Hamilton Internal

Oh, I will be picking up my PIV and GFE this afternoon, can we talk tomorrow morning perhaps?

From: christopher floess ***@***.***>
Sent: Tuesday, May 7, 2024 11:16 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Canchola, Gabriela [USA] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] SOCKS access for Gabriela Canchola (Issue #82455)

I'll reach out to you about this this afternoon — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <department-of-veterans-affairs/va. gov-team/issues/82455/2098676558@ github. com>


I'll reach out to you about this this afternoon

**Comment by gcan-va** [comment]
Hello! I just reached out to you on Slack to see if we can get together sometime to work on this!

**Comment by patrick-black-oddball** [comment]
Socks acccess is complete - you may need to wait up to 10 minutes before the access propogates.
