### ISSUE TITLE
IPP Design - Create a IPP info pamphlet for Veterans

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#82465]
Context
Provide Veteran participants in the pilot with educational material already provided online in a paper format.

Tri-fold or bi-fold; create content first, then when handed off to design see what is feasible
Pull content directly from site, tweak as needed for grammar/flow but overall should read the same

Use content from[ v2 - sign-in focus](https://docs.google.com/document/d/1RpiIfSWzpqfkTi54M6U_POz30gQLUD23icBgr8f6SOQ/edit)

Use visuals from 
[ID.me](https://www.id.me/business/identity-verification#:~:text=video%20conference%20session.-,In%2DPerson,secure%20credential%20for%20important%20services.)
[Login.gov](https://login.gov/help/verify-your-identity/how-to-add-images-of-your-state-issued-id/)

**Comment by JKG199** [comment]
Started draft [here](https://www.figma.com/file/sWaKEav2QibZZKxAkbULG7/IPP-Pilot-Material?type=design&node-id=287%3A10&mode=design&t=b638ulcZ4CCKo7wk-1), working on inspo, ideation and best layout options.

**Comment by JKG199** [comment]
@SophiaPhilipMO draft is ready for review [here ](https://www.figma.com/file/sWaKEav2QibZZKxAkbULG7/IPP-Pilot-Material?type=design&node-id=287%3A10&mode=design&t=plZ7Vzn1w4W5SIF9-1) under the heading draft 1. I did my best! But I do think that after exploring different layouts, the one I landed on is best for the large amount of content we have to handle. Feel free to leave comments and questions and I'll address once you've had a chance to look!

**Comment by SophiaPhilipMO** [comment]
Minor edits but final version [here](https://www.figma.com/design/sWaKEav2QibZZKxAkbULG7/IPP-Pilot-Material?node-id=287%3A10&t=nV3k4531m5C0Hjsp-1[Inside v1.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEw3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00f07e22d7ed9b67fc405474ba757726ef48a6da/Inside%20v1.pdf)
)[Uploading... Front.png]

**Comment by SophiaPhilipMO** [comment]
<img width="1035" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFA3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9609609209638ae9601d0f77779d1d2586220e24/Front.png" alt="Front.png" />
