### ISSUE TITLE
[CAIA Intake] Appointments: Medication Review

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#82472]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Appointments FE
- **OCTO product owner:** @klawyer 
- **Product name:** Appointments FE
- **Product manager:**  @ldelacosta 
- **Slack channel:** [#appointments-team](https://dsva.slack.com/archives/CMNQT72LX)
- **Dedicated content writer on your team:** N/A
- **Dedicated a11y specialist on your team :** N/A
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [x] Something else: Add new content to appointments/across all pages.

### What's the nature of your initiative and desired outcomes?

We need to align on patient instructions to review their medications ahead of an appointment, and add that language to the appointment detail pages across all touchpoints (web, mobile, etc). This is from an OIG/Congressional request.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes - Congressional mandate
- [ ] No
- [ ] I’m not sure

### Where are you at in your timeline?

We don't have a final date set yet but this will be high priority for our team. We'd like to pull in CAIA (in this ticket) at two stages:

- An initial review of the proposal - to be completed by 05/17 at the latest
- Review of changes that come in from stakeholders to make sure we're meeting standards. Final date TBD

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No

This content will be released across multiple products - appts web, check-in, and mobile app. Each will have different release plans.

 
- [x]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

## Supporting artifacts

[This PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/82736) will be the source of truth. I'll keep this updated with CAIA feedback, and any other comments that come in from other sources.

- [Audit of similar language](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/projects/2024-05-medication-language-update/medication-content-audit.md) and are 
- [Medication review language proposal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/projects/2024-05-medication-language-update/proposed-language.md)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by outerpress** [comment]
@laurwill just noting that the proposed language is [here](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=1-2) and we'll pick this ticket up again once it's been reviewed in ticket #85061

**Comment by outerpress** [comment]
Thanks @laurwill ! I sent this back to stakeholders for review, and captured the updated language [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/projects/2024-05-medication-language-update/proposed-language.md)

I asked them to review/respond to the updates by July 5th, will drop a note here when they do.

**Comment by outerpress** [comment]
Hi @laurwill, the final language has been [approved](https://dsva.slack.com/archives/C074T950HL0/p1721154958738609)(woo!)

When the resource page is ready could you drop the URL here? @ldelacosta this is the URL we'll need to complete the dev work for appts.

**Comment by outerpress** [comment]
URL: https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/
Node ID: 69968

@laurwill @coforma-terry this request is resolved - thank you! Do I close the ticket, or do you all?

**Comment by laurwill** [comment]
I'll close it out, thanks Peter!
