### ISSUE TITLE
Implement content adjustments in Medical Records box on LP

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82487]
### User story

As a Veteran, I want the MHV landing page to explicitly inform me that Records links will take me to another website, so that I can avoid getting disoriented by unexpected navigation.

### Notes
- Follows design from #80829; expect clear handoff from UX
- Releases simultaneous with integration, use same toggle as other integration changes to links on landing page

## Steps/tasks
- 

## Acceptance criteria

- Changes to Medical Records box implemented behind integration feature flag
- Implementation reviewed by UX team
- QA review
- A11y specialist reviewed

**Comment by jonathanjnelson** [comment]
@radavis  [See designs in Figma here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2138%3A28954&t=tBDV9LOhLhmINQ2n-1)

<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6811df8b5817d476a0242c1a909d432d9c10f69b/Screenshot%202024-05-14%20at%201.06.56%E2%80%AFPM.png" alt="Screenshot 2024-05-14 at 1.06.56 PM.png" />
)

**Comment by allanto-ah** [comment]
Environment: Staging

Verified from QA that this is showing as expected

**Comment by LynneJohnson224** [comment]
@brea11y to do a11y review

**Comment by brea11y** [comment]
Accessibility review complete. No concerns or issues.
