### ISSUE TITLE
IA: Medications breadcrumbs

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82482]
### User story

As a Cartography team member, I want to provide a technically feasible MVP breadcrumb design for the Medications app that solves for as many Veteran scenarios as possible, so that Medications can implement and go live for Phase 1.

As a Veteran, I want the breadcrumbs in Medications to provide the context of where I am in the information architecture of the MHV-on-VAgov portal, so that I can stay oriented with minimal cognitive load.

### Notes
- 

Possible tasks:
- Map current breadcrumbs
- Communicate updates for needed breadcrumbs
  * Desktop
  * Mobile

## Acceptance criteria

- [x] Medications team has a breadcrumb design for child pages that they can implement and go live with for their Ph 1
- [x] IA for Medications landing page breadcrumb still points back to MHV landing page, per prior guidance

**Comment by sterkenburgsara** [comment]
@wesrowe update: have sent a breadcrumb plan for phase 1 to the medications dev team. Decisions are [outlined in this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713558793852/31aadcbae7070a6f0f4cfea4f63e568721f1480d?sender=uf94a77a19aaf687331c09367), which I'll expand to provide guidance to all teams for the integration.

**Comment by sterkenburgsara** [comment]
@wesrowe question - are these other a/c's all necessary for our team? since this ticket is blocking the other one I wanted to ask.

**Comment by wesrowe** [comment]
good question...
- definitely don't need QA
- reworded landing page AC to be clear it's not implementation
- do we need a11y review of the recommendation? probably not...

**Comment by wesrowe** [comment]
@sterkenburgsara, it seems like you finished this one off already. close if that's correct.
