### ISSUE TITLE
Articulate the exact circumstances in which a vet would receive a generic error message on claim submission

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#82480]
What status codes (from vets-api) will cause a vet to see this message?

If this is anything other than a 500, are there specific places in the code where we are triggering this code (resulting in this error)?

<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0s2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--160a07f3e8e970566f663febef0d17dd9a45e713/Screenshot%202024-05-06%20at%203.29.39%20PM.png" alt="Screenshot 2024-05-06 at 3.29.39 PM.png" />

**Comment by freeheeling** [comment]
In [src/applications/disability-benefits/all-claims/constants.js](https://github.com/department-of-veterans-affairs/vets-website/blob/7223facfd15a2beb191d46fa6264f5411d7dee3a/src/applications/disability-benefits/all-claims/constants.js#L132), an API `status` response from `/v0/disability_compensation_form/submission_status/<job_id>` of **"non_retryable_error"** is assigned a `submissionStatus` of **"failed"**.

Example response format:
```
{
    "data": {
        "id": "",
        "type": "form526_job_statuses",
        "attributes": {
            "claimId": null,
            "jobId": "5a964e136be3bd0e604036a6",
            "submissionId": 32,
            "status": "non_retryable_error",
            "ancillaryItemStatuses": []
        }
    }
}
```

The BE responds to the `/submission_status/<job_id>` request with a `status` of **"non_retryable_error"** for any errors returned by EVSS, upon submitting a claim's form data, that **do not** fall in the following categories:
- Common::Exceptions::BackendServiceException
- Common::Exceptions::GatewayTimeout
- Breakers::OutageException
- EVSS::DisabilityCompensationForm::ServiceUnavailableException
- EVSS::DisabilityCompensationForm::ServiceException, except for any pre-defined retryable errors with the following keys:
  - 'evss.external_service_unavailable' unless 'EP Code is not valid'
  - 'evss.disability_compensation_form.pif_in_use'
  - 'evss.disability_compensation_form.ws_client_exception'
  - 'refdataservice.errorResponse' where Reference Data Service is unreachable

If the `submissionStatus` is anything other than **"success"**, **"retryable_error"**, **"exhausted"**, or **"apiFailure"**, the `ConfirmationPage` renders the `submitErrorContent`, which contains the text included in the description screenshot. In summary, the message should only render as the result of requesting the submission status, and only if the response `status` is **"non_retryable_error"**.
