### ISSUE TITLE
Content review UX downtime flow

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#8249]
#User story
As a user, I want clear messaging on when the downtime happening on VA.gov, how long it will last and if this downtime will affect any tool or apps. 

Image of downtime message UX here to provide feedback: 

https://dsva.slack.com/archives/C011JLER2TT/p1586877252066600?thread_ts=1586877046.066300&cid=C011JLER2TT

PR to review: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/commit/74ca63808cd0b73f858d8b77de25ce3051ca8365

**Comment by peggygannon** [comment]
content and UX updates to downtime messages are in the PR: 

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/185

**Comment by peggygannon** [comment]
@jenniferlee-dsva @rtwell I've merged in our content and UX updates to the Error message dictionary. I will ping you next week when the updates are live and viewable.

**Comment by jenniferlee-dsva** [comment]
@peggygannon  - just flagging that some of these are in flight/changing as part of the larger banner discussions, with you, @rtwell and @davidconlon and others. (the advance downtime sitewide one.) I think it's fine to merge, since this corrects some erroneous UX that's out there now; but wanted to make sure that we're on the same page.

**Comment by peggygannon** [comment]
@jenniferlee-dsva Yes, agree. We're on same page. I know some of these will change based on our recent downtime meetings.

the PR contains some condensed messaging based on past conversations (and Ryan's UX recommendations), and wanted to get these other changes reflected into the doc.

**Comment by meganhkelley** [comment]
Related to Sitewide System Maintenance Banner #9223

**Comment by peggygannon** [comment]
closing this issue, as  I've opened a new and more detailed issue [#9536](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9536)  about the UX changes to downtime messages:
