### ISSUE TITLE
(Additional) Access for John Paul Ashenfelter

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8251]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > John Paul Ashenfelter
- Please Provide your email.
   > johnpaul.ashenfelter@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Tech Lead, VSP Backend Tools Team
- [Grant AWS Console access?]
  > YES
  >  Please give a brief description for why you are requesting AWS access.
I'm asking for additional AWS access permissions. Might be easiest to give me full admin, but I'd be better able to complete the work on our team with (i don't know exact permissions but these are the rough idea)

RDS administrator
Elasticache administrator
S3 administrator

All three of those services are used by the vets-api app, are directly involved in work we do for and with ops, and allow me to better serve the be-tools team and our work with the devops team.

NOTE: It is likely much simpler to give me all admin access like the devops team members.

**Comment by johnpaulashenfelter** [comment]
Today I also found I can read/write but not delete credstash credentials while i was helping the CARMA team. Another good argument for all admin

**Comment by Jeff-Hayter** [comment]
@ricetj Approved.
