### ISSUE TITLE
Rep status widget icons misaligned vertically

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#82515]
## Issue Description
The icons on the contact page are rendering lower than expected:

<img width="1384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHErQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0c0070e8d27c91b1564871454225e051381912b/image.png" alt="image.png" />

## Acceptance Criteria
- [ ] Icons are centered w/r/t their corresponding contact field

**Comment by oddball-lindsay** [comment]
Icons are looking good!

<img width="791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a83be2b1a661ab6bad04e6fed2df116b22e8d5b4/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
Did some of our own styling (like adding an extra margin) to get this behaving as expected, but keep an eye as future Design System changes may affect this.
