### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by pennja** [department-of-veterans-affairs/va.gov-team#82541]
### Name

Jacob Penner

### Email

jacob.penner@adhocteam.us

### Role

Full Stack Engineer

### Team

Veteran Facing Forms

### Product Manager (PM) name

Matthew Dingee

**Comment by pennja** [comment]
> Hi! An invite has been sent to [jacob.penner@adhocteam.us](mailto:jacob.penner@adhocteam.us).

@naomimarcussen I was able to find it but accepting the invite still results in an alert mentioning that my 14-day trial has expired when I attempt to access dev mode.

**Comment by naomimarcussen** [comment]
Hmmm... that's strange. Looks like your account was created and you should be able to log in with your adhoc email. Maybe log out and give logging in another try and see if you still get that message.

**Comment by pennja** [comment]
@naomimarcussen Unfortunately, logging out and back in again doesn't fix the issue.
