### ISSUE TITLE
design system, components 508-defect-2 [KEYBOARD]: Focus outline MUST be visible around focused content, pagination

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#8254]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

```diff
! Team: VSA Public Websites; Project: Find Forms MVP
```

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

For each page of search results, the focus outline **must** be visible around the entire page indicator. but is currently cropped at the top at bottom.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a keyboard user, I want to tab through the content and be able to see where focus is.

## Environment

* Operating System: all
* Browser: all
* Server destination: production

## Steps to Recreate

1. Enter https://www.va.gov/find-forms?q=medical in browser
2. Tab through page content to the pagination
3. Verify that the focus outline is cut off on the top and the bottom

## Screenshots or Trace Logs

![Screen Shot 2020-04-21 at 8 23 08 PM](https://user-images.githubusercontent.com/57469/79927839-087ce480-840f-11ea-9d64-26f3b358f3f5.png)

**Comment by 1Copenut** [comment]
Issue moved to [department-of-veterans-affairs/vets-design-system-documentation #249](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/249) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jenstrickland** [comment]
As this bug is still in the VSA Public Website's work, we should keep this bug open. Once the sitewide issue is resolved, we should ensure that the update is reflected in this work.

**Comment by 1Copenut** [comment]
Good call. There are a couple other pagination items I'll find and re-open too.

**Comment by jenstrickland** [comment]
Validated, this is fixed 🎉
