### ISSUE TITLE
Spike | Identify Font Awesome Components

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#82547]
## Issue Description
_The VA Design System is retiring the Font Awesome icon library and is replacing it with `va-icon` on June 19, 2024. We need to identify if any of our custom form components use Font Awesome icons, so they can be migrated to `va-icon`._

Notes from the Design System Team from [this post](https://dsva.slack.com/archives/C03R5SBELQM/p1714612416352079):
- The new icon set is available in [Figma](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=293%3A6211&mode=design&t=unKDZLSetqWFsv0R-1) and in [guidance](https://design.va.gov/foundation/icons).
- We've introduced an eslint rule that will display a message only, notifying users they can use va-icon. The message contains a link to the guidance on how to do so.
- Note that the default size for va-icon is set to 4. Users can change the value from 3-9 for sizing needs.
- Once June 19th arrives, we will be replacing the eslint message with an eslint error + quickfix option, and users will be required to update if they haven't.

---
## Tasks
- [x] Identify instances where Font Awesome is used in custom form components in the following forms:
   - [x] 686/674
   - [x] PCPG/CH36
   - [x] VR&E/CH31
   - [x] Burial
   - [x] COE 

## Acceptance Criteria
- [ ] A list of instances where Font Awesome is used and needs to be updated.
---

**Comment by Midge-dev** [comment]
@steele-lm No FA icons being used by our apps. (Burials/BurialsV2, LGY/COE, VRE, Dependents)
