### ISSUE TITLE
Map PEGA responses to vets-api back end

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#82557]
In support of sending an email update to a VFMP applicant, the PEGA response that represents the applicants data needs to be stored in the VA.gov back end.

### Acceptance criteria
Given a well-formed call to the callback endpoint
When the response is received
Then the response should be persisted so that status can be send back to the applicant

#### Part A
- Update database to remove email uniqueness index; Add index for `form_uuid`
- Update model to remove validation
- Update existing models to include email and uuid
- Add DB creation when file is being uploaded
- Add Rspec to ensure database record is being added
- Update existing tests
#### Part B
- Ensure validation from PEGA payload
- Add DB lookup with `form_uuid`
- Update db record with pega status

**Comment by baltes** [comment]
@balexandr Let's talk through this one more as needed. This is the story for handling the callback payload that gets sent back to us.

**Comment by balexandr** [comment]
@baltes We can update this ticket or create a new one but we need an acceptance criteria that CREATES the initial DB record on S3 submission and then UPDATES that same record after Pega hits the callback API

**Comment by balexandr** [comment]
Updated ticket from 3 -> 5 due to having two parts

**Comment by balexandr** [comment]
Part B was just merged into staging. Will leave in this column until they confirm connectivity

**Comment by balexandr** [comment]
@baltes Tested the end point on staging through Postman. The below is a screenshot of a staging database form before and after I hit the endpoint
<img width="1319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW4yQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--585f03f18f7e7392032fa8a35a6751fc2b7b18fa/Screenshot%202024-05-20%20at%2011.49.06%E2%80%AFAM.png" alt="Screenshot 2024-05-20 at 11.49.06 AM.png" />
