### ISSUE TITLE
VetsAPI: Expose location, practitioner, and clinic info on Slot search responses

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#82552]
> As a vets-api consuming service, I wish to see all available information for returned appointment Slots.

The vets-api VAOS module slot searches at:
```
/locations/:location_id/clinics/:clinic_id/slots
/locations/:location_id/slots
```
return the Slot id and time range, which is consistent with the return values from `vaos-service`. `vetsapi-patient-gateway` provides additional information which should be included in the response if provided.

**Acceptance Criteria**
* VAOS v2 slot search responses include the following fields, if present:
   * Location ID
   * Clinic IEN
   * Practitioner name
* Tests are added to validate new behavior

**Comment by devin-mccurdy** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/17597
