### ISSUE TITLE
[FE] Review your approved referral and start scheduling page

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#82555]
- Create review your approved referral and start scheduling (page)
- Should match wireframes (only rough wireframes available as of this writing)

<img width="348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0s0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7eb70980418b23b14fe253b6885243b7f47e623a/Screenshot%202024-05-06%20at%2011.42.11%E2%80%AFAM.png" alt="Screenshot 2024-05-06 at 11.42.11 AM.png" />

https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?type=design&node-id=222-8772&mode=design&t=FSsgO8BXb1yAKvgr-0

**Comment by benbrasso-agile6** [comment]
Rdy to close??
