### ISSUE TITLE
VA.gov mobile nav bugs

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#8256]
I found a handful of bugs with the mobile nav (actually the trigger button that shows the side nav on mobile).

## 1. When the menu trigger button "sticks" to the top of the window (or unsticks) when scrolling, the page content behind it jumps

![sticky-jump](https://user-images.githubusercontent.com/20728956/79928478-e9268d00-83f7-11ea-93a2-837762156b35.gif)

This is a common bug and is due to the trigger button being removed from the standard page flow when its position is set to `fixed` https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/b0e8508b7257d248663bb4a9a72039762bfb5783/packages/formation/sass/modules/_m-nav-sidebar.scss#L392 when the `.fixed-trigger` class is added to it. Near the bottom of the sample script [shown in the docs](https://design.va.gov/components/sidenav) it's this bit:

```js
window.addEventListener(
  'scroll',
  function() {
    if (mobileMediaQuery.matches) {
      if (offset < window.pageYOffset) {
        element.classList.add('fixed-trigger');
      } else {
        element.classList.remove('fixed-trigger');
      }
    }
  },
  false,
);
```

One proposed fix that would require the smallest amount of change would be to add an empty trigger placeholder `div` as a sibling to the `.va-btn-sidebarnav-trigger` button. When the trigger button has its position set to `fixed` set the height of the trigger placeholder div to the height of the trigger button, including its margins (52px in this case, but that should be computed and not hardcoded). When the trigger button's position is set back to relative or static, reset the height of the trigger placeholder to 0.

## 2. The trigger button disappears when the mobile sidenav menu pops open

![trigger-vanish](https://user-images.githubusercontent.com/20728956/79928499-f6dc1280-83f7-11ea-84d3-492acda3bcb0.gif)

This _seems_ like a bug to me, but there are [three lines of code in the sidenav.js](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/9aa5a922370c7c3341e5837a7d044d67fc08f90c/packages/formation/js/sidenav.js#L100-L102) file that are responsible for this (and [another three lines](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/9aa5a922370c7c3341e5837a7d044d67fc08f90c/packages/formation/js/sidenav.js#L142-L144) to restore the button when the menu closes). This is super easy to fix. But maybe there's a reason to remove the trigger after you've clicked it? ¯\_(ツ)_/¯

## 3. The trigger button can get stuck to the top of the window.

![trigger-stuck](https://user-images.githubusercontent.com/20728956/79928511-fe032080-83f7-11ea-8b4f-12bef3d5bcd3.gif)

The replicate this:

1. Scroll down the page far enough so the menu trigger button sticks to the top of the window.
2. Resize the browser in any dimension (or if you are on a phone, make sure orientation/rotation-lock is not turned on and rotate the phone).
3. Scroll up the page and notice that the menu trigger button sticks to the top of the window until you have scrolled to the top of the page.

This is due to the `offset` value getting reset by the script that sets up and manages the sticky behavior.  In the sample script at the bottom of the code sample [in the docs](https://design.va.gov/components/sidenav) it's this bit:

```js
window.addEventListener(
  'resize',
  function() {
    if (mobileMediaQuery.matches) {
      offset = element.offsetTop;
    }
  },
  false,
);
```

I initially thought the fix could be as simple not setting `offset` if it's already set. So:

```diff
function () {
+ if (offset) return;
  if (mobileMediaQuery.matches) {
    offset = element.offsetTop;
  }
}
```

But that would not be sufficient! Instead we'd need to make sure that the position of the element is not `fixed` before setting the value of `offset`.

So something like:

```diff
function () {
+ if (window.getComputedStyle(element).position === 'fixed') return;
  if (mobileMediaQuery.matches) {
    offset = element.offsetTop;
  }
}
```

Note: Gotta use `getComputedStyle(element)` instead of just `element.style.position` as the latter does not take into account style changes that happen during runtime.

**Comment by erikphansen** [comment]
@KevinMHoffmanUSDS @rtwell Chris Johnston suggested I share these bugs (with potential fixes!) with you.

**Comment by KevinMHoffmanUSDS** [comment]
Thanks, @erikphansen! Bringing this to the attention of @ncksllvn - Nick is this something that the  public website team can use to address the bug that Eric has identified? cc @MickinSahni @jenniferlee-dsva

**Comment by jenniferlee-dsva** [comment]
FYSA @stephorkandatx who is new PM for PW.

**Comment by jenniferlee-dsva** [comment]
This appears to have gotten orphaned when everyone was removed from the "Assigned."  Adding PW PM Brian for awareness, so this can get included in our board for 2021 work. 

@brianalloyd @johnhashva - An idea - maybe the team can dedicate a sprint in 2021 Q1/January to reviewing, triaging, and resolving bugs in the backlog.

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva received.  Great suggestion on triaging and bug resolution for Q1 2021.

**Comment by erikphansen** [comment]
@jenniferlee-dsva Thanks for finding digging this one up. I just ran into these bugs again yesterday and was sad that they hadn't been fixed :(

**Comment by brianalloyd** [comment]
@erikphansen I'm going to get this into next sprint for review and action, as @jenniferlee-dsva mentioned I think this might have been victim to some turn over and was orphaned.  I'll close the loop once we've resolved the issue.

**Comment by erikphansen** [comment]
@brianalloyd Feel free to validate and close when you get a chance!

**Comment by brianalloyd** [comment]
Closing per validation.  Thanks @erikphansen for the excellent work and support this sprint.
