### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by katbrinkley** [department-of-veterans-affairs/va.gov-team#82572]
### Name

Katlyn Brinkley

### Email

kat.brinkley@agile6.com

### Role

Experience Researcher II

### Team

MHV Cartographers at Agile6

### Product Manager (PM) name

Wes Rowe / Patrick Bateman

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to kat.brinkley@agile6.com
