### ISSUE TITLE
Qualitative Survey Data Request - Identity Team

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#82577]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2024

### Date Range End

04-30-2024

### Product Name(s)

Identity, authentication

### Product Description

Identity products cover authentication. We connect sign in credentials (from ID.me, Login.gov, MHV, and DSLogon) to both VA.gov and the VA mobile app. We own the universal sign in page, Terms of Use page, and, recently, all sign in flows from any page on VA.gov, like sign in widgets.

### Survey URL(s), key term(s), case category or type

URLs - can be anything across the site, since sign in is initiated from many different pages and the universal sign in page is a modal, not a static url
key terms - sign in, signin, sign on, signon, signing in, signing on, log in, login, log on, logon, logging in, logging on, sign out, sign off, signing out, signing off, log out, log off, logging out, logging off, password, pass word, account, username, user name, mfa, multifactor auth, 2 factor auth, two factor auth, two factor, authenticate, authentication, verify, verification, terms of use, terms of service, hacked, locked out, security,

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

clayton.zook@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, let me know if you have any questions. Thank you!
