### ISSUE TITLE
Generate a data-rich sample de-dupe for review

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#82576]
Per emily: [we'll want to do is take a look at a small sample of those. 10-15 users worth. So the submission ids, datetime, ideally the full raw JSON, and any ID information so we can see if they're truly untouched...](https://dsva.slack.com/archives/C04KW0B46N5/p1715096250313889?thread_ts=1714422192.089569&cid=C04KW0B46N5)

**Comment by lisacapaccioli** [comment]
@SamStuckey Is this still needed or is it done already?

**Comment by SamStuckey** [comment]
@lisacapaccioli done, closing
