### ISSUE TITLE
10-7959f-2 | Interim Hand-off for selected pages

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#82581]
This effort will port over the sections of 10-7959f-1 to 10-7959f-2 that can be repeated for use.

We understand there will be additional sections that need more design effort, but this will cover the sections that are considered complete to this point.

These sections are:

Part 1 :  Name and Date of Birth
Part 2:  SSN and VA file number
Part 5:  Contact Information

Sections that need further review will include:
Section 3: Mailing Address
Section 4: Home Address

Deliverable will be via page within the Figma file link in the comments below

**Comment by brian-wilke** [comment]
@rachaelpenfil , @marywang2 , @reiting .... this is the page in figma that has the correspondingly "simple" screens that can be leveraged into 10-7959f-2

https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=3419-83589&mode=design

**Comment by rachaelpenfil** [comment]
[A11y annotations ](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=3446-33594&mode=design&t=lUyHyeiAdqilfUYU-4) for the following sections are complete as of 5/9: 

Part 1 : Name and Date of Birth
Part 2: SSN and VA file number
Part 5: Contact Information

@brian-wilke @marywang2 @reiting
