### ISSUE TITLE
Vets-api terminal access for [Eric Oliver]

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#82595]
### Your Name

Eric Oliver

### Your GitHub handle (terminal access is managed through GitHub)

@olivereri

### Your dsvagovcloud AWS user name (if applicable)

eric.oliver

### Team, Role, and Company of the target individual

Check-In Experience, DevOps, Agile Six

### Product Manager (PM) name and email

Lori Pusey (lori.pusey@agile6.com)

### Product Owner (PO) name and email

Kay Lawyer (katherine.lawyer@va.gov)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/31904439/14eaaef8-ad39-4ece-9ec3-f05daddbdb3e)

I'm reconfiguring vets-api to send BTSSS requests via fwdproxy, need to poke around and confirm environment variables are being set correctly, that sort of thing.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
confirmed in Atlas
E-QIP confirmed

**Comment by bdech** [comment]
@olivereri You've been granted access to `Staging`. Access to `Production` is pending OCTODE approval, and we will update you as soon as its available.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@olivereri, you've been granted access to `Production`, 
with access to `Production` limited to 6 months, expiring 11/09/24.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1715285873707649)

**Comment by lindsay-insco** [comment]
@olivereri Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by lindsay-insco** [comment]
@olivereri Production access has been removed. If you would like access, please fill out a new request.
