### ISSUE TITLE
[Spike] - Consolidate ReasonCode Text Logic Into Appointment Service

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#82597]
Spike for the upcoming work to move Appointments team's reasonCode.text logic into the vets-api appointment_service. This will be a joint development effort by vets-website and vets-api.

We want to determine what fields need to be made available to the FE via vets-api.
Two primary functions we will need to get rid of are: `getAppointmentInfoFromComments` & 'getReasonCodeDS' found in  our `transformers.js` file `(src/applications/vaos/services/appointment/transformers.js)`.

## Tasks
- Answer the following questions:
- What new fields does vets-api need to start exposing to the FE for the team to successfully get rid of the above 2 function?
- What files will need to be updated in vets-website? (Think tests as well)

Timebox TBD

**Comment by simiadebowale** [comment]
Fields needed from the for **Appointment requests**:
Sample reasonCode.Text field:
```
"reasonCode": {
                "text": "station id: 983|preferred modality: FACE TO FACE|phone number: 6195551234|email: myemail72585885@unattended.com|preferred dates:06/26/2024 AM,06/26/2024 PM|reason code:ROUTINEVISIT|comments:test"
            },
```


These field values can be found in the appointment `reasonCode.text` field.

Field needed. some of the field
- `contact`- `[{ system: 'phone', value: phone },{ system: 'email', value: email }]`. Phone number and email are gotten from reasonCode.Text field.


- `preferredDates`: should return an array of strings. If date includes 'AM', i.e, 06/26/2024,  return 'Wed, June 26, 2024 in the morning', if date include PM, return 'Wed, June 26, 2024 in the afternoon'. `['Wed, June 26, 2024 in the morning', 'Wed, June 26, 2024 in the afternoon']`


- `reasonForAppointment`: should return a string based on code received:
`ROUTINEVISIT` - `reasonForAppointment` should return: 'Routine/Follow-up'.
`MEDICALISSUE` - `reasonForAppointment` should return: 'New medical issue'.
`QUESTIONMEDS` - `reasonForAppointment` should return: 'Medication concern'.
`OTHER_REASON` - `reasonForAppointment` should return: 'My reason isn’t listed'.

- `additionalAppointmentDetails`: should return whatever `comments` from `reasonCode` returns. i,e: 'test'.

Fields needed from the for **Direct Scheduled Appointment**:

**Comment by simiadebowale** [comment]
Sample reasonCode.Text field:
```
"reasonCode": {
                "text": "reasonCode:ROUTINEVISIT|comments:test"
            }
```
These field values can be found in the appointment `reasonCode.text` field.

**New Fields needed.**
- `reasonForAppointment`: should return a string based on code received:
`ROUTINEVISIT` - `reasonForAppointment` should return: 'Routine/Follow-up'.
`MEDICALISSUE` - `reasonForAppointment` should return: 'New medical issue'.
`QUESTIONMEDS` - `reasonForAppointment` should return: 'Medication concern'.
`OTHER_REASON` - `reasonForAppointment` should return: 'My reason isn’t listed'.

- `additionalAppointmentDetails`: should return whatever `comments` from `reasonCode` returns. i,e: 'test'.

**Comment by simiadebowale** [comment]
@cferris32 - Direct scheduling is ready for validation

**Comment by ldelacosta** [comment]
Since Corey is out of office, I'll close out the ticket and we will review this when he's back. I'll add it to our PM/Engineering agenda. Thanks!
