### ISSUE TITLE
Update content design system language for sign-in banner

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#82591]
## Audience
_**Who** is this content for?_

CAIA / Design Systems / Internal VA teams

## Purpose
_What will this content help the audience **do**? Use verbs to explain the purpose of the content._

Used as a starting point for banner message about sign-in issues on VA.gov.

## Brief description
_**What** is the request and **where** will the content be published?_

Update the existing language to include our 4th CSP: Login.gov. This applies to [scheduled downtime notifications](https://design.va.gov/content-style-guide/error-messages/system#scheduled-downtime-notifications) and [unscheduled downtime notifications](https://design.va.gov/content-style-guide/error-messages/system#unscheduled-downtime-notifications) for the sign-in page.

## Content design tasks

- [x] Submit documentation request to Design System team

## Documentation
_Related artifacts_

[Chat with team in #identity-ux](https://dsva.slack.com/archives/C05HM2QPQRG/p1715100652580909)

<img width="1596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGp4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e983e28ff5becf3b91f47548c622deda18102a62/image.png" alt="image.png" />

## Product notes
_Additional product or business considerations from stakeholders._

## Acceptance criteria
- [x] Request submitted to Design Systems
- [ ] Updates are reflected in the Design System
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Reviewed by CAIA (logged-out website content only)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kdmeg-bluetiger** [comment]
[Submitted documentation request here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2838)

**Comment by parkerbees** [comment]
@claytonzook is this work related to an existing effort/is there a product brief I can link it to? It's OK if not, I'm just trying to wrap my head around things. :)

**Comment by parkerbees** [comment]
Moved to jira; closing here
