### ISSUE TITLE
Consolidate ReasonCode Text Logic Into Appointment Service

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#82598]
This ticket is to capture the work for moving the Appointments team's reasonCode.text logic into the vets-api appointment_service. This will be a joint development effort by vets-website and vets-api.

Placeholder for any details to be added by Simi for the FE code on va.gov.

Blocked by related spike ticket #82597

**Comment by ldelacosta** [comment]
Not needed anymore. Closing out the ticket. cc: @cferris32 @simiadebowale
