### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by emilytheis** [department-of-veterans-affairs/va.gov-team#82608]
### Name

Emily Theis

### Email

emily.theis@va.gov

### Role

VA Product Owner

### Team

Benefits Portfolio (Disability, dependency, pension, burial, etc)

### Additional Notes

I have an existing figma account with this email from prior to when we shifted as an org, I'm not sure if that complicates things!

**Comment by naomimarcussen** [comment]
Hi! I see you already have an account in Figma. Are you not able to login? It does show that you only have permission to manage 1 project though. Let me know if you're having issues getting in to your project and we may need to start over with a new invite.

**Comment by emilytheis** [comment]
I'm not able to manage all the projects related to my work, which includes basically anything for benefits. An example of something I can't edit is this board within the disability benefits project https://www.figma.com/file/iRmZuM3vUEYKxeSjTpMdkT/526-ITF-Stopgap?type=design&mode=design&t=1udkD6qWcuwpL6ZY-0

**Comment by naomimarcussen** [comment]
I think I figured out what was wrong. I just sent you an invite to the team. Hopefully that resolves the issue for you.

**Comment by emilytheis** [comment]
Yes, the issue was resolved! thanks for the help!

**Comment by naomimarcussen** [comment]
Yay! Glad you're in. Let me know if you need anything else.
