### ISSUE TITLE
Make data fields driving "un-registered alert" consistent?

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82601]
### User story

As a Cartography team member, I want to use a single data field/signal to determine whether Veterans see the "un-registered alert" anywhere we've implemented on the MHV portal, so that the code is easier to maintain and Veterans have a consistent experience regardless of entry path.

In other words...
- For the original implementation of the un-registered alert, the landing page displays the alert based on whether the user has facilities associated with their profile
- For the route-guard, we check a different field, `mhvAccountStatus`
- Wes's concern: it's the same alert, is there a compelling reason we're using two different fields to display it?
- Recommend pulling Patrick into the discussion
- Daniel's diagram of user account checks (in a branch at the time) - [github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/dcloud/draft-mhv-decision-graph/products/health-care/digital-health-modernization/engineering/mhv-access-visibility-graphs.md)
- Slack thread with various teams about Jim's PRs - [thread](https://dsva.slack.com/archives/C0581MN69TJ/p1714666992208249?thread_ts=1714662482.503679&cid=C0581MN69TJ)
- And [another thread](https://dsva.slack.com/archives/C0581MN69TJ/p1715020636839619?thread_ts=1714768253.188939&cid=C0581MN69TJ) re which field to use
- The route guard PR for the secure messaging tool page revealed that the upcoming Oracle user migration will result in a section of users that do not have data in the vets-api. This means that they will not have an MHV (aka `mhvAccountState` ) which the route guard relies upon for user validation. Secure messaging currently has a validation process for showing a different alert to users based on backend services aka the vets-api.

### Notes
- 

Possible tasks:
- 

## Acceptance criteria

- Determined whether there is a functional reason for the route guard to condition on a different field than the landing page alert, and if not, which field we should standardize on
- Performed or ticketed implementation of recommended action

**Comment by wesrowe** [comment]
Refinement 5/29:
- We need to confirm use cases where a user might have data (eg vaccination), and whether either of these fields is preferable for determining whether to display tool links on the landing page.
- Team to determine correct path forward.
- Can we get an example real-world use case to focus our understanding on?

**Comment by jzucadi** [comment]
The route guard PR for the secure messaging tool page revealed that the upcoming Oracle user migration will result in a section of users that do have data in the vets-api. This means that they will not have an MHV which the route guard relies upon for user validation. Secure messaging currently has a validation process for showing an alert to users based on backend services aka the vets-api.

**Comment by wesrowe** [comment]
Patrick indicated in a meeting on 6/3 that the idea of a route guard goes against a paradigm that was agreed to a year ago: tools would manage their own access. We need to work though this with Octo.

**Comment by wesrowe** [comment]
closing this ticket because the topic of this ticket ended up needing broader discussion/consideration.
