### ISSUE TITLE
[FE] Filtering

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#82611]
## Background

Filtering list of providers:

- [Link to access filter standalone page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1485-96716&t=BGfk8mAIUenfSZ2M-4)
- [Filter standalone page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1483-30930&t=BGfk8mAIUenfSZ2M-4)
- [Calendar component](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1483-30971&t=BGfk8mAIUenfSZ2M-4) based on [USWDS data picker](https://designsystem.digital.gov/components/date-picker/)
- [Review comment #1](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4?node-id=1300-12451#809800744)

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/82611?planning-poker) with Zenhub @lee-delarm6

**Comment by lee-delarm6** [comment]
- Made a comment on the review #1 link
- Now that I'm looking into it, the USWDS calendar component is not on the list of VA components. I don't see it used anywhere on vets-website right now. @simiadebowale linked this component, a custom piece by the looks: `CalendarWidget: /src/applications/vaos/components/calendar/CalendarWidget.jsx` but the VA component is this: https://design.va.gov/components/form/memorable-date
    - If the modal is an acceptable use AND we can use it (engineering wise), awesome. If not, perhaps this other date picker was chosen for accessibility reasons?

Once these are responded to, I can give you a more accurate poker planning estimate on this ticket, which I assume is "Filter page completion for all display and functional components (to be tied into a BE call later of course) @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Correct, Appts doesn't use the USDWS date picker component needed for the filter page. We can just copy the code from the USWDS site and modify it to fit inside our web app. So, would point off of that assumption.

**Comment by lee-delarm6** [comment]
![Screenshot 2024-05-29 at 4 02 26 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/c9767c4c-33f5-46df-9fb0-d2490c05ec38)

**Comment by lee-delarm6** [comment]
![Screenshot 2024-05-29 at 5 08 43 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/0fddc669-8796-42af-baf1-fa2dac5cb991)

I got the basic portion of the CalenderWidget working today on the filter page

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 what are we including in the scope of this ticket? E.g., just the FE build out? 

Also, take a look at the annotations I left to confirm functionality of filters, although, these might not matter until we're integrated with WellHive: 

- [Date field annotation](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2130-7393&t=MdvE9JG1wH0vfhnW-4)
- [Facility field annotation](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2130-7407&t=MdvE9JG1wH0vfhnW-4)
- [Clear filters annotation](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1777-77522&t=MdvE9JG1wH0vfhnW-4)

Is all this work completed and/or need to be validated? 

Are we planning to do the submission logic in separate ticket? E.g., select filters, submit form, and see mock provider results. Do you want another ticket for that for next sprint? Note: We do need to work through [this issue](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4?node-id=2130-7431#829820263) I pointed out.

**Comment by lee-delarm6** [comment]
I built quite a bit of the front end out for this, including adding some store states for the filter data. This will be applied when you click apply and send you back to the main page. All front-end work, but more than just the page design was done here.

We do eventually need to hook it up to wellhive endpoints though, which we also validated this sprint.

Due to the setup process of a new token, we will not be able to integrate everything next sprint, but we do have a number of choices on what to start working on (token is up there, along with mocks)

**Comment by lee-delarm6** [comment]
![Screenshot 2024-06-10 at 11 38 00 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/c3e245e0-08fd-4c01-b4f6-a036aafb6cb1)

**Comment by anita-halici** [comment]
here is what is left on this ticket as of 6/11 per @lee-delarm6  :

- Make time slots available and selectable on the filter calendar
- Make sure redux store is working properly when you click "apply" so the values are accessible on the appointments viewing page (not fully integrated, just working)
@simiadebowale

**Comment by anita-halici** [comment]
@simiadebowale @lee-delarm6 - I noticed this task rolled over to the next sprint, and has been in works for 2 sprints what is left to be done in this ticket? is there any blocker?

**Comment by lee-delarm6** [comment]
@anita-halici Not a blocker, but we were on another project, this was almost done, needed a little more time to cook. I finished it up and it's ready for validation as of right now :)

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 do we have an env set up where I can start to validate tickets?

**Comment by lee-delarm6** [comment]
I don't believe we do, you'll have to pull locally. The commands to run it are identical to appts (we built within appts)

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/README.md

**Comment by benbrasso-agile6** [comment]
Nice. Would love for me and @JRRoof to get spun up next week.

**Comment by lee-delarm6** [comment]
As of right now, this is merged with main 🥳
