### ISSUE TITLE
[FE] Choose a community care provider (page)

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#82612]
- Create Choose a community care provider page
- Operate off existing (rough) wireframes, image as of this writing

- [Loading page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1633-69318&t=eqowEJC9Bcrrt6cO-4)
- [Provider list with patient preference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1485-96716&t=eqowEJC9Bcrrt6cO-4)

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/82612?planning-poker) with Zenhub @lee-delarm6

**Comment by lee-delarm6** [comment]
![Screenshot 2024-05-24 at 4 34 32 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/396f629a-a75d-47ce-a22d-195119b15809)
![Screenshot 2024-05-24 at 4 34 26 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/3467ad3a-fa89-459a-83f3-571890938eee)
