### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by alexiawunder** [department-of-veterans-affairs/va.gov-team#82635]
### Name

Scott Tyrcha

### Email

scott.tyrcha@bylight.com

### Role

UX Designer

### Team

Medications on VA.gov

### Product Manager (PM) name

Kay Lawyer

### Additional Notes

Scott is still setting up his Slack profile, but he will be the main designer for the medications tool.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to [scott.tyrcha@bylight.com](mailto:scott.tyrcha@bylight.com). Once an account is created, let me know, and I'll upgrade it to have full access.

**Comment by alexiawunder** [comment]
Good morning! His account has been created.

**Comment by naomimarcussen** [comment]
Great! I just gave him full access. Happy Figma-ing!

**Comment by naomimarcussen** [comment]
Hi! Your has been created and upgraded to have full access.
