### ISSUE TITLE
Adding Cesar Santiago to DSVA Slack

### ISSUE THREAD

**Issue by cesarsantiagova** [department-of-veterans-affairs/va.gov-team#82646]
# Description

Please add Cesar Santiago (cesar.santiago@va.gov) to the slack channel as a full member.

Cesar Santiago is a team lead for the https://github.com/orgs/department-of-veterans-affairs/teams/dgib-developers
group. He will be leading development and delivery of functionality to process GI Bill claims.

**Comment by cesarsantiagova** [comment]
Any update on this? Is there additional information needed?

**Comment by LEHigley** [comment]
@cesarsantiagova i just did this request but i am seeing you also have a slack account with your accenture fed email addres--you do not and should not have 2 slack accounts. i revoked the invitation. 

we can update your current account with your va email address?
