### ISSUE TITLE
Create example deploy pipeline scripts

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#82643]
## Description
In continuation of some of the work in documenting patterns and best practices in [this ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/81594), we want to create example deployment patterns to help guide future work. This will be added to the confluence page for these guidelines. 

### Tasks
- [x] Create Example deploy pipeline scripts
- [x] Document approaches

### Acceptance Criteria
- [ ] Guidelines for this is incorporated into the Confluence page

**Comment by ben-allen-oddball** [comment]
Standard Deploy MVP:

https://github.com/department-of-veterans-affairs/prt-github-workflows/tree/ba-81594

Example Working Repos:
https://github.com/department-of-veterans-affairs/prt-sandbox/tree/ba-69504
https://github.com/department-of-veterans-affairs/prt-example-repo/tree/ba-81594

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3157360797/Standardized+Github+Workflows

**Comment by JoeTice** [comment]
@ben-allen-oddball - I think this is done and guidelines have been added to the Confluence page, but noticed the AC wasn't checked, please check off that AC if it's completed
