### ISSUE TITLE
Prep analytics monitoring strategy for integration rollout

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82651]
### User story

As a Cartography team member, I want to have a UX monitoring strategy in place when the integration with secondary nav goes live, so that we can monitor risks and begin understanding usage and usability of the integrated portal.

### Notes
- The [implementation plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/integration-with-nav-release-plan-2024.md) has details on changes going out with this release
- Focus on Datadog, and secondarily GA3 (UA). GA4 won't be ready yet.
- Also include a plan for Medallia qualitative feedback review. Anne Costello-Kennedy from the SM team has been pulling Medallia daily, we should inquire about her workflow.
- 5/10 met with Robyn & Kaitlin
  - [Jenny's Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713561055500/5e8a24a555d8539f5165c4371c16eaf7632e8e23?wid=0-1715362346681) we worked on; note that other areas were Jenny+team analysis that led to the Word doc below
  - Jenny Wang's [Transition KPI strategy & implementation document](https://dvagov-my.sharepoint.com/:w:/g/personal/yizhen_wang_va_gov/EZzGU2alvZ5PoQ68QyrWwkgBnWB7XUyYih3J2vRnCVRe9Q?e=scoA1h) as an example
  - The [Secure Messaging analytics & feedback folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/analytics) for some inspiration; among these is the "SM dashboard" where Anne tracks stats monthly.

Possible tasks:
- 

## Acceptance criteria

- Key user flows and interactions are documented and prioritized in ____ (Mural?)
- Sought feedback from Robyn, Kaitlin and Patrick

**Comment by wesrowe** [comment]
Robyn requested a meeting about how we'll monitor qual survey feedback across the portal. I updated the Notes in the ticket body to include qual among our considerations; it doesn't seem (yet) to warrant a new AC or ticket.

**Comment by fmccaf1** [comment]
[Started Google doc (this allows Kat and I to collab since she's still lacking some permissions).](https://docs.google.com/document/d/1XCRyvbQWwwtbC1BgGtADsurqsrj4hyxDVTKLnyLtPrY/edit)

**Comment by katbrinkley** [comment]
This document outlines the integration KPIs discussed with cartography team and presented to Robyn (has link to Mural). Anne CK let me know how to request daily medallia pulls for monitoring qualitative survey feedback.
