### ISSUE TITLE
Test base font size changes

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#82658]
## Description

In [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26606) VA.gov's base font size is changing from 10px to 16px. This ticket tests those changes against complex UI in VAOS.

---

## Acceptance Criteria

For each of the pages below please provide 2 full page screenshots, one each at 320 px wide and > 800 px wide:

- [x] Appointments Landing page with upcoming appts
- [x] Past appts list 
- [x] Pending appts lis
- [x] Request calendar
- [x] Request calendar with weekends

Please also test each of those pages at 200, 300, and 400x text zoom. Only provide screenshots of the zoom levels if something looks broken.

## Definition of Done
- [ ] All acceptance criteria are met
- [x] Findings reviewed by UX team

**Comment by jenniemc** [comment]
Upcoming appt list 
---

- Viewed at 200x, 300x, and 400x text zoom. No observable errors on page.

Desktop view 800px >
---
![Screenshot 2024-05-13 at 1 30 58 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/2693772a-7240-44d2-8fd7-aad48a90d738)

Mobile view 320px
---
![Mobile_Upcoming_appt_list](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/05d1afc5-9391-4f24-8944-c35027afc86d)

**Comment by jenniemc** [comment]
Pending List
---

- Viewed at 200x, 300x, and 400x text zoom. No observable errors on pending page.

Desktop view 800px >
---
![Screenshot 2024-05-13 at 2 03 29 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/decaae51-074d-470e-adff-a1391f77ede0)

Mobile view 320px
---

![Mobile_Pending_list](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/096a57d1-a7f1-4a60-9bbd-c77e16677dda)

**Comment by jenniemc** [comment]
Past List
---

- Viewed at 200x, 300x, and 400x text zoom. No observable errors on past appt list.

Desktop view 800px >
---
![Screenshot 2024-05-13 at 2 12 38 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/bd558d5a-ab85-4e86-a06b-b18ec90d0d53)

Mobile view 320px
---
![Mobile_Past_list](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/ffad2668-cad5-420a-84cd-4d425bcec162)

**Comment by jenniemc** [comment]
Request Calendar (M-F)
---

- Viewed at 200x, 300x, and 400x text zoom. No observable errors on request calendar.

Desktop view 800px >
---
![Screenshot 2024-05-13 at 2 34 41 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/ff4f29eb-2480-4350-b385-358f2a182d5a)

Mobile view 320px
---
![Mobile_Calendar_5days](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/2ba6f7c7-50a1-4ddf-a300-4772f7fc5f9f)

**Comment by jenniemc** [comment]
Schedule Calendar (full week)
---

- Viewed at 200x, 300x, and 400x text zoom. No observable errors on schedule calendar.

Desktop view 800px >
---
![Screenshot 2024-05-14 at 8 07 52 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/9fa51f2d-d481-4315-859d-f4de6c388501)

Mobile view 320px 
---
![Mobile_calendar_fullweek](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/451a9312-d09b-498e-9e85-06889634b832)

**Comment by jenniemc** [comment]
Detail page
---

- Viewed at 200x, 300x, and 400x text zoom. No observable errors on detail page.

Desktop view 800px >
---
![Screenshot 2024-05-14 at 8 45 12 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/c7a3494b-4756-418b-b675-297a21ffb28d)

Mobile view 320px
---
![Mobile_detail_page](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/42ac7119-a29b-4cc5-a22f-a97044f9d16d)

**Comment by jenniemc** [comment]
@outerpress @ldelacosta Screen captures of 800px> and 320px screen added the ticket.  No observable display errors when viewing at 200x, 300x and 400x text zoom.  Ready for validation.

**Comment by outerpress** [comment]
Thanks @jenniemc ! I appreciate the deep dive, those look good to me too. FYI @ldelacosta it might be worth noting this ticket in a comment to the PR Jennie tested https://github.com/department-of-veterans-affairs/vets-website/pull/26606

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
