### ISSUE TITLE
Reports Powered by UA: [Modernized Check In]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#82698]
# VFS Report Inventory for GA4 Migration

### What this form is for.
In preparation for the transition to Google Analytics 4 (GA4), we need information on all actively used reports that use GA Universal Analytics (UA) data. This is needed to identify the best ways to assist teams with transitioning their reporting. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> [!IMPORTANT]
> Please complete this form as soon as possible, but no later than **Friday, April 26.** The sunset date for Universal Analytics is **July 1, 2024**, which means reports that rely on GA UA as a data source will stop collecting new data on this date. If reports exist within GA UA itself, they will become unavailable.

### Instructions:
**Step 1:** Please provide the following information on each actively used report your team uses that contains UA data at the bottom of this ticket. _(Or, if it's easier, attach a spreadsheet.)_
 
**Step 2:** Include your team name within the title of this form.

**Step 3:** Submit this form.

_Our team will follow up with you for any next steps._

> [!NOTE]
> - We are defining _"actively used reports"_ as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
> - Teams do NOT have to include the standard [Search](https://va-gov.domo.com/page/1964748112), [Content](https://va-gov.domo.com/page/426422632), or [Forms](https://va-gov.domo.com/page/447193050) KPI dashboards --  we are already working to update those.

> ### Example:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|VA Homepage Report|https://va-gov.domo.com/page/|Domo| Our team uses this report to analyze trends for our KPIs.|
---

## Reporting Information:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
| Bene Travel Claims from eCheck-in Report | [URL Link](https://analytics.google.com/analytics/web/#/dashboard/-LnfQTl3ShO8HbLIPQ7ZEQ/a50123418w177519031p176188361/_u.dateOption=last7days/) | GA | Used for reporting metrics to VA PO and for making product decisions|
| Pre-Check-In (PCI) | [URL Link](https://analytics.google.com/analytics/web/#/dashboard/DgeEvA4JTruKLAW444xXOg/a50123418w177519031p176188361/_u.dateOption=last7days/) | GA | Used for reporting metrics to VA PO and for making product decisions |
| eCheck-in (PCI) | [URL Link](https://analytics.google.com/analytics/web/#/dashboard/1iHzB1FJTq6wHfngzN0LQg/a50123418w177519031p176188361/_u.dateOption=last7days/) | GA | Used for reporting metrics to VA PO and for making product decisions |
| BT Claims from text "travel" at OH Sites | [URL Link](https://analytics.google.com/analytics/web/#/dashboard/yqkbRXcgQXKYTYs6ReQscg/a50123418w177519031p176188361/) | GA | Used for reporting metrics to VA PO and for making product decisions |

**Comment by johnny-jesensky-adhoc** [comment]
@loripusey - thank you for submitting! Confirming we have this - we'll plan to review these reports, and the kinds of metric your team reports on so we can offer support during the transition to GA4.

FYI @jestutt, @Blivaditis, @ChristineYoungZA

**Comment by johnny-jesensky-adhoc** [comment]
This information has been documented in a separate file -- closing out this ticket.

FYI @ChristineYoungZA, @Blivaditis
