### ISSUE TITLE
[FWDProxy] Setup Networking and DNS

### ISSUE THREAD

**Issue by stoiven** [department-of-veterans-affairs/va.gov-team#82702]
Load balancer and security groups, plus DNS are necessary prior to allowing them into the critical path

**Comment by stoiven** [comment]
@npeterson54 fyi, I'm piggybacking off Kyle's work here in regards to the forward proxy

**Comment by stoiven** [comment]
https://app.zenhub.com/workspaces/platform-infrastructure-services-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/82692 related

**Comment by npeterson54** [comment]
Rolling into next sprint
