### ISSUE TITLE
UX: Update BTSSS (travel pay) link to clarify it's external

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82707]
### User story

As a Veteran, I want the link to file a travel reimbursement claim to clearly indicate that I'm being taken to a different website/domain, so that I don't get disoriented by leaving VAgov by accident.

### Notes
- Came up in OCC weekly meeting

###  UX tasks:
- [x] Recommend new link treatement and mock up in Figma
- [x] Get stakeholder approval of new link text and/or behavior as needed (include Kaitlin Fink & Kristen McConnell)

Stakeholders approved this design on 5/23/24:
<img width="339" alt="Screenshot 2024-05-23 at 4 14 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/7ff6b2d8-ab05-489d-9123-59ef63d3fdf5">

### Implementation tasks (for devs): 
Update "Payments" box on landing page to match [Figma file here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2404-21524&t=0GQydEXiSQ9aJ3w4-0)
 - [ ] Swap order of two links in payments box so that "Copays" link is on top and the "travel reimbursement link" is below
 - [ ] Update link text of travel reimbursement link to read "**File a claim for travel reimbursement on the Beneficiary Travel Self-Service System website (opens in new tab)**" 
 - [ ] visual treatment: do not bold the link text; remove the caret symbol at the end of the line for this link
 - [ ] Make this link open in a new tab

## Acceptance criteria
- [x] Designed link text to indicate external system
- [x] Implemented link change
- [x] QA review
- [x] A11y review

**Comment by wesrowe** [comment]
Refinement 5/15: this needs stakeholder alignment.

In the meantime, need to remove "Opens in new tab" from the link (new ticket).

**Comment by wesrowe** [comment]
@jonathanjnelson, can you clarify where we're at with stakeholder alignment? (Kristen?)

**Comment by sterkenburgsara** [comment]
Update stakeholder approval for link text update (and behavior change to have link open in a new tab) documented[ in this Slack thread. ](https://dsva.slack.com/archives/C0581MN69TJ/p1716497679950539)

This is ready for handoff to developers.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this is matching the figma design and is working as expected
<img width="843" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8ca6056656df20cba3685a53e011354d35bdfe8/Screenshot%202024-05-31%20at%208.57.26%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 8.57.26 AM.png" />

**Comment by allanto-ah** [comment]
@brea11y can you review this when you get a chance? Thank you!

**Comment by radavis** [comment]
It seems as if this ask will change due to guidance by Public Websites: https://dsva.slack.com/archives/CE4304QPK/p1717097782458959

**Comment by wesrowe** [comment]
Since this is already merged, I think it should just close when ready. The new tweak will be a different ticket.

**Comment by brea11y** [comment]
This looks great. No accessibility issues seen (or heard with the screen reader). The link opens in a new tab, as expected, and is clear in the content that you are being taken somewhere outside of the MHV portal. Also verified that the font size is 19px like what is shown in the Figma file.
