### ISSUE TITLE
Adding Carissa Merrill to DSVA Slack

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#82706]
# Description

- Please add carissa.merrill@agile6.com as a full member.

Carissa is a researcher / designer on the Sitewide contract team. Thank you!

**Comment by aklausmeier** [comment]
email address was missing, Jill has updated

**Comment by EWashb** [comment]
User has been added. @jilladams can you have her confirm? Once confirmed this ticket can be closed. cc: @aklausmeier

**Comment by jilladams** [comment]
Confirmed! Thank you so much.
