### ISSUE TITLE
10-7959f-1: Add mapping to submit transformer

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82719]
As a VA.gov user, I want to provide my info to the VA when filling out the 10-7959f-1 form, so that I can get contacted if there are any issues or questions.

- add mapping to submit transformer
- allow backend to access contact info (phone number or email) for applicant as part of the callback API

Acceptance criteria:
  - Given the form has been submitted with contact information filled out
  - When the form submission is processed
  - Then the backend should be able to access the contact information for the applicant

**Comment by reiting** [comment]
@marywang2 @baltes this PR has been merged. There is nothing additional to review as this is just a change in what we are sending to the backend, so we can probably close it if you are okay with that.
