### ISSUE TITLE
Datadog RUM site for va.gov Pension (527) web app

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#82710]
This is a tracking issue for the addition of a Pension RUM application for DSVA Datadog.
https://dsva.slack.com/archives/C05MS96P6P2/p1714664561577479

It is not necessary for anyone else to actually add the RUM app - Steve can do this. We are tracking this for awareness/comment on adding new RUM tracking

The Pension application shows usage of approximately 3000 sessions per month. At a rate of $2.25/1000 sessions would cost approximately $6.75/month. Note that Pension applications include unauthenticated sessions; to reduce the risk associated with this it will implement a [Filter to remove typical bot sessions on intake](https://docs.datadoghq.com/real_user_monitoring/guide/identify-bots-in-the-ui/#filter-out-bot-sessions-on-intake) and will implement a monitor on `datadog.estimated_usage.rum.sessions` to track and alert for abnormal user session ranges.  Lastly if we have an abnormal spike in caused by an abnormal usage case (like an attack) we can request a reduction in session counts from the Datadog team.

Based on the low session rate it is planned to not sample/capture 100% of user sessions.

** Pilot status**

The team understands that this is a pilot effort that may be ended after review
The Benefits team is available for discussion prior to launch and and/or review of metrics after an initial launch, and we are flexible on items such as sample rate.

**Comment by aplatt-coforma** [comment]
@wayne-weibel can we close this now that you've completed the RUM tickets?
