### ISSUE TITLE
Staging Review finding: Fix the alignment of icons and text in card

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#82712]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Accredited Representation Management

**Product:** Appoint a Representative MVP + Representative Status Widget MVP
**Feature:** Appoint a Representative MVP + Representative Status Widget MVP

## Findings details
**VA.gov Experience Standard - issue:** [User encounters design components that are inconsistent or confusing.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** Yes
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

On the "Your current accredited representative" card, the icons and text seem to be misaligned.

<details><summary>Link, screenshot or steps to recreate</summary>

![Screen shot of card](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/71535-Allison-01.png?raw=true)

</details>

## Recommended action

Align the icons with the text.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Card ](https://design.va.gov/components/card)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by oddball-lindsay** [comment]
@shiragoodman the alignment got affected by the DST font-size update, but we've since corrected it :) 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/d1f643ca-181d-4753-8c78-51023807007b)

**Comment by shiragoodman** [comment]
FYSA @allison0034

**Comment by caw310** [comment]
DST has a ticket to fix this. [Button - Icon: Spacing between icon and label](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2850)
