### ISSUE TITLE
Flipper UI access for Allan To

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#82720]
### Your Name

Allan To

### Your GitHub handle (Flipper UI access is managed through GitHub)

allanto-ah

### Team, Role, and Company of the target individual

Health Enrollment and MHV on VA.gov, QA Engineer, Ad Hoc LLC

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
@allanto-ah You've been granted access to Flipper lower environments.
