### ISSUE TITLE
Redirect and retire page: Birth defects linked to Agent Orange

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#82729]
TASKS:
- [x] KRISTIN - Ensure new Spina Biffida page is published in family member hub
- [x] KRISTIN - Ensure new Children of Women Vietnam Vets page is published in family member hub
- [x] KRISTIN - Submit redirect ticket to pw. Redirect https://www.va.gov/disability/eligibility/special-claims/birth-defects/ to new spinda biffida page
- [x] KRISTIN - confirm redirect works
- [x] Update sitemaps
- [x] Ensure that left nav link in disability (where the old page used to live) now links to the family member hub.

**Comment by kristinoletmuskat** [comment]
Hey @laurwill question about this one. 

It's this page right? https://www.va.gov/disability/eligibility/special-claims/birth-defects/

I remember we had a convo about this but couldn't remember -- were just linking out to this page from family member hub right? Which page are we redirecting/retiring?

**Comment by laurwill** [comment]
In phase 1 we're linking to that page. In phase 2 we're publishing 2 new pages in the family member hub that will replace this page (one for spina bifida, one for children of women vietnam vets). We'll need to redirect this page to one of those pages — I'm thinking spina bifida probably?

**Comment by kristinoletmuskat** [comment]
Got it, thank you!

**Comment by kristinoletmuskat** [comment]
Closed and complete!
