### ISSUE TITLE
[Reverse Proxy] Fix Deployment Returning `NULL` for Tag

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#82732]
## Acceptance Criteria
- [ ] A `release-revproxy.txt` file is generated with the latest Reverse Proxy release version after each reverse proxy release workflow
- [ ] A `release-config.txt` file is generated with the latest Config release version after each config release workflow

## Notes
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/blob/main/.github/workflows/docker-image-config.yml
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/blob/main/.github/workflows/docker-image-revproxy.yml

**Comment by Efe-Oddball** [comment]
I have the code to create and upload the release files added to both workflows in my branch. I will test to ensure functionality and resolve the ticket

**Comment by Efe-Oddball** [comment]
This has been resolved and PR has been merged. Closing this ticket
