### ISSUE TITLE
Bug: PATCH cancellations sent to VPG have no request body

### ISSUE THREAD

**Issue by bcrosbyva** [department-of-veterans-affairs/va.gov-team#82750]
## Summary
While attempting to cancel an OH appointment an error was received back from VPG.
_Describe what went wrong_

## Specs
- Browser: Chrome

## Steps to Reproduce
Enable the 

1. In Flipper, enable the `va_online_scheduling_use_vpg` and `va_online_scheduling_enable_OH_cancellations` feature flags for Judy Morrison
2. Go to VAOS, open an upcoming OH appointment
3. Click the cancellation button

### Actual Result
VETSAPI sends a PATCH cancellation request to VPG with no request body, resulting in an error:
```
{
  "errors": [
    {
      "title": "Bad Request",
      "detail": "Required request body is missing: public org.springframework.http.ResponseEntity<?> gov.va.mobile.vpg.v1.resource.AppointmentResource.patchAppointment(org.springframework.cloud.gateway.mvc.ProxyExchange<byte[]>,java.lang.String,java.lang.String,java.lang.String,java.lang.String)",
      "code": "VAOS_400",
      "source": {
        "vamfUrl": "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vpg/v1/patients/434fce82be04d498f7e7e54f30c0d4c35f61bc4e53610137bcb446723597732a/appointments/38eb82d7451c9036df43fa75318a5453d1a66e3055ce09ebcec16821949e44cf",
        "vamfBody": "{\"code\":400,\"status\":400,\"message\":\"Required request body is missing: public org.springframework.http.ResponseEntity<?> gov.va.mobile.vpg.v1.resource.AppointmentResource.patchAppointment(org.springframework.cloud.gateway.mvc.ProxyExchange<byte[]>,java.lang.String,java.lang.String,java.lang.String,java.lang.String)\",\"id\":\"e16a2ff4-197c-4895-908f-96d1fcf13f3e\",\"traceId\":\"55fa6be23b2197b9f9c4d1a7975d21a6\"}",
        "vamfStatus": 400
      },
      "status": "400"
    }
  ]
}
```
<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d2d40cef555e54cf49ded390bbaa84c2b04a725/vaos-vpg-cancellation-error.png" alt="vaos-vpg-cancellation-error.png" />

### Desired Result
VETSAPI sends the PATCH request to VPG with the patch operations in the request body.

## Definition of Done
- [X] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by BrittanySFowler** [comment]
This was a bug found and pulled into sprint 10
