### ISSUE TITLE
Mock pilot session for IPP App

### ISSUE THREAD

**Issue by schisslerg** [department-of-veterans-affairs/va.gov-team#82759]
Acceptance Criteria

- [x]  Mock participants identified
- [x]  Schedule timespots
- [ ]  Address any issue identified in research
  - [ ]  Any critical priority fixes should flow into this sprint

**Comment by SophiaPhilipMO** [comment]
Rescheduled for 5/15

**Comment by SophiaPhilipMO** [comment]
Delayed due to change in site
