### ISSUE TITLE
Metrics for Github content performance

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#82755]
To establish baseline performance and track engagement with our support content over time, we can gather some metrics from Github pages via API. This will help us understand if folks are finding our content, moving through content they're viewing, and whether they're clicking through links to resources shared in #vsp-identity.

**Github developer documentation:**

- [Get page views](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/80008)
- [Top referral sources](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/80008)
- [Referral paths](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/80008)

Note: it's clear we can gather page view data for Github pages. It's not clear if we can get referral data or not (this may be limited to repos only). The effort of this ticket would be to investigate what metrics are possible for the pages identified below, and set up a way for the UX team to access the metrics.

**List of Github pages we'd like to track:**

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Troubleshooting_logging/troubleshooting_signin.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/470b2ba8c4c6c1b7cf168737755ce2607fc92954/products/identity/Support%20Process/identity-office-hours.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/d4640bb7398e8b7de94dac54af4273ff27475c46/products/identity/Products/Mocked%20Authentication/readme.md#L4
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/error-messages/sign-in-error-handling.md
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Policies%20and%20Procedures/SSOe_Outage_Response.md
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/login/unified-sign-in-pages
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/470b2ba8c4c6c1b7cf168737755ce2607fc92954/products/identity/Products/Design%20Documents/UserAccount_Creation_Flow.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/470b2ba8c4c6c1b7cf168737755ce2607fc92954/products/identity/Products/Design%20Documents/UserAttribute_Rules.md
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Documentation/Security/Rotate_certs.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Policies%20and%20Procedures/Require_MFA_VAgov.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Policies%20and%20Procedures/VA.gov%20Identity%20Solution%20Code%20Review%20Policy.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/reference-documents/auth/authentication-and-authorization.md#authorization
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/sso/ssoe_saml_response_attributes.md
- https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/user/getUser
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/a523e46183625ea11bb3ebde02813976cd2dd472/products/identity-personalization/developer/mock_data.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Support%20Process/Datadog_primer.md
- https://github.com/department-of-veterans-affairs/vets-api-mockdata?tab=readme-ov-file#add-credential-mocked-data-for-a-new-user---sign-in-service-login

**Comment by kdmeg-bluetiger** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80008

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
