### ISSUE TITLE
Jump links not working on Parent DIC rates page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8275]
## What happened?
_On this page anchor links not working_. Unclear if this is a FE or a Drupal issue.

## Specs:
On this URL: https://www.va.gov/disability/parent-dic-rates/
- Device: GFE PC
- Browser: Chrome
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/disability/parent-dic-rates/
- Test User _(if applicable)_:

## Desired behavior
_On this page anchor links should link you down to the matching H2 section headers_

## Acceptance Criteria
- [x] _Describe the desired working behavior_

## How to configure this issue
- [x] **Labeled with `Bug`**

**Comment by johnhashva** [comment]
Also not working: the first two On This Page Anchor links on Survivor Rates page https://www.va.gov/disability/survivor-dic-rates/#how-dic-may-affect-your-va-sur also  -- however, third one -- How DIC may affect your VA Survivors Pension or Survivor Benefit Plan -- is.

**Comment by stephorkandatx** [comment]
This may be Drupal - can we have FE take a look to see where the error is being generated?

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/81214398-067d5e80-8f95-11ea-81eb-4a0774892117.png)

Current hypothesis is that this is a CMS content-entry issue. @RLHecht let me know if updating the CMS doesn't resolve this and we can re-investigate 🙂

**Comment by RLHecht** [comment]
These anchor links have been fixed in Drupal on both pages and they work in preview. The anchor links that were in there weren't matching what the H2 tags were. It's possible the H2s changed after the anchor links were put in or they were never typed in right originally when I created them. Moving to validate and will close once on the live site.

**Comment by RLHecht** [comment]
These are now fixed on the live site. Closing ticket. FYSA @stephorkandatx @johnhashva

**Comment by johnhashva** [comment]
Awesome -- thank you!
