### ISSUE TITLE
Adding [Mohammad Ewaz Farhang] to DSVA Slack

### ISSUE THREAD

**Issue by ewaz-farhang** [department-of-veterans-affairs/va.gov-team#82769]
# Description

**Account is deactivated**: user has already an account but it seems it is deactivated. 

<describe the request>

Are you requesting to add an individual as a:

- Single guest
- Multi-channel

Hello I am part of DGIB test automation team. we recently started an effort to automate My Education Benefit Applications testing. To do this, I have been assigned to add new idme mock users and their data into vets api mock data. The main purpose of this ticket is to have access to slack ( I had once access about two years ago before I move to another teams) so that I communicate proper channel to request vets api mock repo write access. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_ewaz.farhang@accenturefederal.com_] as a single-channel guest to [_Not sure what channel can help me with write access to vets api mock data_].

**Comment by ewaz-farhang** [comment]
just wanted to follow up on this issue. any update?

**Comment by LEHigley** [comment]
@ewaz-farhang sorry just getting to this. i need you to let me know which channel they should be added to.

**Comment by ewaz-farhang** [comment]
Dear @LEHigley  thanks for reaching out. I really don't know what specific channel. I need access to vets api mock data which is a private repo and I think I need to first directly request in a channel or ask for direction. I think there should be a support team channel in slack to work on this type of requests.
