### ISSUE TITLE
IA Request: Decision Review Pages Entry Points and URLS

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#8276]
## Required Inputs:
- Link to product outline: [AMA Follow-up Changes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md#appeal-modernization-process-ama--follow-up-changes-outline)
- Link to or attach prototype or mockups: https://app.moqups.com/Rnc4BDEKrA/view/page/a5e3c0342
- Link to or attach final content including H1s (if separate from prototype/mockup)

**Entry Points**

**Health Care**

- [x] **Healthcare Left Nav** 
Location:  Within "Manage" spoke, place below "Check appeal status" Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [x] Page: https://www.va.gov/health-care/after-you-apply/
http://preview-prod.vfs.va.gov/preview?nodeId=30
Accordions
Location:  Within the "Other questions..." section, there are two accordions - what to do if application isn't approved and what if I will be removed – Update content to reflect the new Decision review labeling and language and provide a link to the Decision review pages as well as the claim status tool.
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

**Disability**

- [x] **Disability Top Nav Flyout**
Location:  In the “Manage your benefits” column, change “Decision reviews and appeals” to “Request a decision review or appeal” to match other “manage” links which start with verbs.  Links to:  https://www.va.gov/decision-reviews/ 

- [x] **Disability Left Nav**
Location: - Replace the existing "Manage a legacy VA appeal" link, which appears after "File for increased disability"
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [x] Hub Page:  https://www.va.gov/disability/
Location:  - Replace the existing "Manage a legacy VA appeal" link
Label and link:  Request a decision review or appeal https://www.va.gov/decision-reviews/ COPY: Request a decision review or manage a legacy appeal >
If you disagree with a decision on your disability claim, you can request a decision review. You can also manage any review requests or appeals you already filed. 

- [ ] Consider: [Disability > DIC page] Decision review page and Claim status tool
For consistency across hubs, consider adding an "After you apply" content section that includes links to claim status and decision reviews MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

**Education**

- [x] **Education Left Nav**
Location:  Within the "Manage" spoke, place as 7th item (after the check appeal status option) 
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [x] Page: https://www.va.gov/education/ Hub Page
Location:  - - Within the "Manage" spoke, place as 7th item (after the check appeal status option) Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/
Copy:  Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for education benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 

- [x] Page: https://www.va.gov/education/after-you-apply/
After you apply
Location:  - Add link and text under "What happens after I apply" section.
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 
Copy:  Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for education benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 
**http://preview-prod.vfs.va.gov/preview?nodeId=937**

**Careers**

- [x] **Careers Left Nav 1**
Location:  Within the "Manage" spoke, place as 7th item (after the Linked In option)
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [x] **Careers Left Nav 2**
Location:  Within the "Manage" spoke, place as last item below decision review
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/

- [x] Hub Page https://www.va.gov/careers-employment/
Link 1:
Location:  - - Within the "Manage" spoke, place as 7th item (after the Linked In option) Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/
Copy: Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for careers and employment benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 
Link 2:
Location : Within the "Manage" spoke, place as last item below decision review
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/
Copy: 

- [x] How to Apply page. https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/
Location: Add text and a link to decision reviews under the "What happens after I apply" section.
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ Copy: Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for careers and employment benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 

- [ ] Consider: How to Apply page. https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/
Location: - Add text and a link to claim and appeal status tool under the "What happens after I apply" section to be consistent with other similar content.
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/
MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

**Pension**

- [x] **Pension Left Nav**
Location:  - Add link to "Manage" spoke as 2nd item after claim status option
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [ ] ~**Consider: Pension Top Nav**
Location:  -  If Pension and Disability are most common appeals, consider adding link to top nav consistent with disability, as last option in "manage" column
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ ~

- [x] Hub Page   https://www.va.gov/pension/ 
Location:  Under H2 “Manage your pension benefits,” make it the 2nd link after claim status
Copy:
Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for pension benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 

- [ ] Consider:  How to Apply page. https://www.va.gov/pension/how-to-apply/
Location: - To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ Copy: Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for careers and employment benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

- [ ] Consider: https://www.va.gov/pension/aid-attendance-housebound/
Location: - - To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool. MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

- [ ] Consider: https://www.va.gov/pension/survivors-pension/
Location: -To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.  MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

**Housing**

- [x] **Housing Left Nav**
Location 1:  In the Home Loans spoke, add a link to decision reviews immediately after "Check appeal status"
Location 2:  - In the Housing Assistance spoke, add a link to decision reviews immediately after "Check appeal status"
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [x] Hub Page:  https://www.va.gov/housing-assistance/ 
This hub page is divided between 2 related benefits, a link to the decision review content should be added to both "spokes"
Location 1:  Put the link under “Get VA home loan benefits,” directly after “Check your appeal status”
Copy:
Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for home loan benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 

 Location 2:  Put the link under “Get Veterans housing assistance grants,” directly after “Check your appeal status” Copy:
Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for housing assistance grants, you can request a decision review. You can also manage any review requests or appeals you already filed.
http://preview-prod.vfs.va.gov/preview?nodeId=74

- [ ] Consider: https://www.va.gov/housing-assistance/home-loans/how-to-apply/
Location: To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool. MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

- [ ] Consider: https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/
Location: To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.  MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

**Burials** 

- [x]  https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/
To be consistent with other benefits, add link to the claim status too to the "If you don't qualify" section
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/

- [ ]  Consider:  https://www.va.gov/burials-memorials/veterans-burial-allowance/
create an "after I apply" section that includes links to the decision review content and the claim status tool.
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/.   MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)

**Life insurance**

- [x] **Life Insurance Left Nav**
Location:  - Add link to "Manage" spoke as 2nd item after claim status option
Label and link: Request a decision review or appeal  https://www.va.gov/decision-reviews/ 

- [x] Hub page:   https://www.va.gov/life-insurance/ 
Location:  - Add link to "Manage" spoke as 5TH option after claim status
Copy:
Request a decision review or manage a legacy appeal >
If you disagree with a decision on your application for life insurance benefits, you can request a decision review. You can also manage any review requests or appeals you already filed. 

- [ ] Consider Life insurance detail pages
To be consistent with other benefits, create an "after I apply" section that includes links to the decision review content and the claim status tool.  MOVED TO TICKET [10773](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773)
 

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @DanielleThierryUSDSVA @RLHecht @mnorthuis 
For a number of our hub pages, we want a link to the decision reviews and appeals hub page. It will under appear the "Manage your Veterans benefits" H2. Here are two different directions to go in terms of whether we want to position decision reviews as a way to disagree with a claim/benefit decision (helps gets users use to "decision review" language) or stick closer to H1 title they'll click to and gets in idea of managing reviews/appeals they've already filed. Language in brackets is variable by benefit page. Feedback much appreciated! 
<OPTION 1>
**Disagree with a claim decision**
If you disagree with a decision on your [disability claim], you have the right to request a decision review.  

<OPTION 2>
**Manage VA decision reviews and appeals**
Request a decision review If you disagree with a decision on a [disability claim]. Manage decision review requests and legacy VA appeals that you’ve already filed.

**Comment by mnorthuis** [comment]
Some additional things to think about:
- Is each business line prepared to handle a decision review request?
- A number of the hubs also have a link to "check an appeal" status - does the verbiage need to be tweaked, do we keep 2 links, do we reference status checking in the DR hub anywhere?
- Should all hub links and teaser text be the same or customized to what can be appealed? We do not really provide any context on this on the site currently. 
- Do we reference the decision review process on the "After you apply" pages, or is it not a process we want to highlight at this time?
- Do all links go to the DR hub page, or do deeper links make sense in some cases - i.e. Life insurance could link to insurance claims

**Comment by lwalsh617** [comment]
Great questions, Mikki.
Added my thoughts below yours. 


I

- Is each business line prepared to handle a decision review request? 
_I can email someone within each business line to alert them we're adding these links and that they may get requests. @jenniferlee-dsva, can you kindly point me toward contact person for each business line?_
- A number of the hubs also have a link to "check an appeal" status - does the verbiage need to be tweaked, do we keep 2 links, do we reference status checking in the DR hub anywhere?
Feels like we should have both links on disability and pension pages.  It doesn't seem like the status tool copy needs to change. 
_We already reference status tool on the DR hub page and on the "After you request a decision review" page. I'm not sure we need it on individual pages like Supplemental Claim, etc._ 
- Should all hub links and teaser text be the same or customized to what can be appealed? We do not really provide any context on this on the site currently.
_Customizing by what they would be appealing, e.g., "disability claim" versus "education benefit" could help to ground them as they scroll down the page. Plus, since this all still somewhat new and complex, would like to make things obvious where we can. _ 
- Do we reference the decision review process on the "After you apply" pages, or is it not a process we want to highlight at this time?
_We already have it on https://www.va.gov/disability/after-you-file-claim/ below process map. I don't see a similar page for pension. Will look at the rest._
- Do all links go to the DR hub page, or do deeper links make sense in some cases - i.e. Life insurance could link to insurance claims
_I almost suggested deeper links for insurance, contested claims and fiduciary -- but then thought we should keep the hub page for now. Reason being that it has the intro that explains the process had changed and that there's a legacy process. I feel like users might need to see that. Maybe in time, we switch to deeper links?_

**Comment by jenniferlee-dsva** [comment]
^ is a lot, so I will answer q's directly in comment above.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @DanielleThierryUSDSVA 
Would love your feedback on the following: For a number of our hub pages, we want a link to the decision reviews and appeals hub page. It will under appear the "Manage your Veterans benefits" H2. Here are two different directions to go in terms of whether we want to position decision reviews as a way to disagree with a claim/benefit decision (helps gets users use to "decision review" language) or stick closer to H1 title they'll click to and gets in idea of managing reviews/appeals they've already filed. Language in brackets is variable by benefit page. Feedback much appreciated!

Option 1:
Disagree with a claim decision
If you disagree with a decision on your [disability claim], you have the right to request a decision review.

Option 2:
Manage VA decision reviews and appeals
Request a decision review If you disagree with a decision on a [disability claim]. Manage decision review requests and legacy VA appeals that you’ve already filed.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lwalsh617!

Some thoughts on this:

- I do always like trying to match H1 of page they're going to as much as possible just for recognition when they get to that page.
- Something about "Disagree with a claim decision" as a CTA for a crosslink doesn't feel quite right to me. I like the idea of including a mention of managing already filed reviews/appeals too, but feel like we probably don't want to lose the "request" language. Could we make it just "Request and manage decision reviews" and then speak to "appeals" as well in the description?
- I like the conditional "If" first, as you have it in Option 1 so people can see right away if it applies to them. But I do also like mention of managing filed claims. Maybe we can make a hybrid of the 2 as below? Again, being conscious of space, I've cut out the words "decision" and "VA legacy" in the description so this hybrid doesn't get too long.
- I haven't been involved in the nuances of this particular language for a long while, and I wasn't the main content person on this even in the past, but I definitely remember there being a lot of sticky nuances...so please take these thoughts from that lens and feel free to disregard if they don't make sense or would cause issues w/ stakeholders!

**Request and manage decision reviews**
If you disagree with a decision on your [disability claim], you can request a review. You can also manage any review requests or appeals you’ve already filed.

**Comment by jenniferlee-dsva** [comment]
**Request a decision review or manage a legacy appeal**
[Teaser text...]

I think we can't yet lose the "appeal" verbiage until we can be more confident that Veterans grok this is what "appeals" are; and we need to provide information scent to Veterans who are still in the old appeals process.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @DanielleThierryUSDSVA --   I recommend not shortening "decision reviews" to "reviews" in the first instance in the teaser text. We need to keep driving the full term home until users begin to adopt it. By pairing "claim decision" and "decision review"  it will--hopefully start to feel natural for users that, when you get a claim _decision_ you disagree with, you ask for a _decision_ review. WDYT about this:
**Request a decision review or manage a legacy appeal**
If you disagree with a decision on your [disability claim] you can request a decision review. You can also manage any review requests or appeals you already filed. 
Thanks! L

**Comment by DanielleThierryUSDSVA** [comment]
@lwalsh617 That makes total sense to me, yes. I think this looks great - thank you! 

One tiny thing: I think we just need a comma after [disability claim],

**Comment by mnorthuis** [comment]
@lwalsh617 To focus this ticket on the entry points, can we move these 2 items to separate issues since they are not related?  These are each very different efforts as well. 

 Change url for https://www.va.gov/decision-reviews/multiple-party-claims/ to reflect new page title: Contested claims
- To change the URL of a page, a redirect request is needed, so this one can go in a redirect request issue. 

 Correct breadcrumb at https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/
- There are a couple things that need to happen with this one.  There's some content/copy work that needs to happen for this page and possibly an H1 change to differentiate this content page from the decision review version of it.  After that, then to move it to a URL we will need a redirect request

**Comment by mnorthuis** [comment]
@lwalsh617 Just checking in on this one.  

- Contested claims issue needs a redirect request
- Legacy board of appeals page - is this being worked on separately?
- Do we have all approvals we need to add links to all the hubs to decision reviews?

**Comment by stephorkandatx** [comment]
Note: we closed #8094 as duplicate content of this ticket

**Comment by lwalsh617** [comment]
@mnorthuis --
Here's the copy for each page and suggested location. I did not receive any requests from business line owners to hold off or adjust copy, so we're good to go.
Let me know if you have questions. 
![image](https://user-images.githubusercontent.com/53535663/81322983-b4a30a00-9062-11ea-9cd8-0dc6efc787c8.png)
![image](https://user-images.githubusercontent.com/53535663/81323007-bc62ae80-9062-11ea-8c29-d88ca67a3d4e.png)
@stephorkandatx FYSA

**Comment by lwalsh617** [comment]
@mnorthuis @RLHecht -- Mikki, can Randi go ahead and add the links above to the hub pages? Content is approved internally and by SMEs. Thanks!
FYSA @stephorkandatx

**Comment by mnorthuis** [comment]
I have not reviewed this yet, sorry.  Some of these hubs are already at their limit for the number of links on the hub page, and if this link is added to each hub it also needs to be added into the left nav.  I will slot this for later this sprint or next sprint.  

Do we have answers/next steps on these other two items?
Contested claims issue needs a redirect request
Legacy board of appeals page - is this being worked on separately?

**Comment by lwalsh617** [comment]
@mnorthuis Not sure what work you're referring to ^ on the legacy board of appeals page. Can you Slack me so I can start new ticket if needed? Thanks!

**Comment by mnorthuis** [comment]
@lwalsh617 this was my last note on that page:

There was a request to "Correct breadcrumb at https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/"
- There are a couple things that need to happen with this one.  There's some content/copy work that needs to happen for this page and possibly an H1 change to differentiate this content page from the decision review version of it.  After that, then to move it to a URL we will need a redirect request.

It looks like that legacy page has now been redirected to https://www.va.gov/decision-reviews/legacy-appeals/, but there is a link in that page that goes back to the old version so the user is in a loop. 

I thought the stakeholders wanted to keep the legacy board appeal page and that there was a plan to update it to differentiate it from the current board appeal page?

**Comment by mnorthuis** [comment]
I'm recommending a few additional entry points and some tweaks to the ones proposed above. At a high level, here are the changes:
- I focused on 4 potential areas for consistent linking: top nav, hub page, left nav,  and the How to apply or After you apply page. Not every hub has links in all 4 areas. 
- In some cases I did not include a link on the hub page, but did ensure links were provided elsewhere within the hub.  Example: The hub pages are supposed to be maxed at the 10 most important links per spoke -the health care hub is already maxed.   Also, Burials hub does not have a "Manage" section. 
- We should be consistently representing the Decision Review process on the "After you apply" pages or a similar content sections of each benefit type. 
- In most cases, I'm placing the decision review link AFTER the check status link.  The check status link applies to more than appeal status and is more frequently accessed. 


Proposed entry points are documented with the previous IA work for reference.  I'm happy to talk through these and would love a double check to make sure I am consistent too!
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-decision-reviews.md

**Comment by lwalsh617** [comment]
@mnorthuis @jenniferlee-dsva @RLHecht - 
Quick confirmation. On left nav, I believe we landed on this label:
**Request a decision review or appeal**
Reason being, users still don't know what "decision review" means. Down the road, we can potentially remove "or appeal" but I think we still need it now. Noticed the IA reccos did not include "or appeal" so want to confirm. Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - I revised top of this ticket after cross-referencing Mikki's IA list with checklist in comment ^.  Now there's one list. I think the only changes I can't make are top nav and left nav. So I boldfaced just those so they're easy to spot. LMK If you have any questions. Thanks!

**Comment by mnorthuis** [comment]
@lwalsh617 Checking in on the status of this

**Comment by lwalsh617** [comment]
@mnorthuis - Thanks for the reminder, Mikki. (Tried to knock these out and couldn't get into edit mode in Drupal on hub pages. Pinged CMS support so hope to get in asap.)

**Comment by lwalsh617** [comment]
COPY FOR HUB PAGES ENTRY POINTS:

Disability https://www.va.gov/disability/ 
Location:  Under H2 “Manage your Veterans disability benefits,” Replace “Manage a legacy VA appeal” and copy with:
Request a decision review or manage a legacRey appeal >
If you disagree with a decision on your disability claim, you can request a decision review. You can also manage any review requests or appeals you already filed.

**Comment by RLHecht** [comment]
@lwalsh617 I've added the links to all the left navs listed above. The only one I didn't do was the "consider" one in Pension. Let me know if I should put it in there as well. FYSA @mnorthuis

**Comment by lwalsh617** [comment]
@RLHecht @mnorthuis -- I'm not sure about the pension top nav question. I don't have anything in my SME notes about that item. Mikki, how did they respond to that in the IA review?
All "musts" are done on my end. Need to circle back with Mikki and Jen on two things:
1. Confirm language for claim status tool links 
2. Adding "What happens after I apply" sections. @mnorthuis I started looking at this and am feeling like we should have a discussion before I start adding these in. There are inconsistencies from page to page that already have this section so I want to be clear on purpose and elements to include--plus claim status tool language. I think we should move these to a new ticket.

**Comment by mnorthuis** [comment]
Its more of a question for content experts, if Pension is a top decision review/appeal request (like Disability), then I would recommend adding it.  If Pension only represents 10% of all appeals, then it may not be worth it.

**Comment by lwalsh617** [comment]
@mnorthuis spoke to @DanielleThierryUSDSVA about this ^. We don't have the info to make this call and need to get SME input if they didn't respond to the suggestion when IA was presented. I am doing some keyword and page traffic research to share with them so we have a POV based on SEO and traffic. LMK if you have questions. Thanks

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA @mnorthuis -- Judging from keyword volume and Google search results, it doesn't appear that va pension appeals has anywhere near the traffic that disability appeals do. (I looked at the other types of appeal, too, for comparison's sake.
While this sure isn't a deep dive, the numbers are so low, I'm not sure if we should even go back to the SMEs with it. LMK WYT. Thanks!
![Screen Shot 2020-06-30 at 1 05 54 PM](https://user-images.githubusercontent.com/53535663/86155565-97bf0c00-bad2-11ea-9ab0-16c43b87e846.png)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks for looking into this more, @lwalsh617! It does seem that the data doesn't back up there being much need.

I added @bethpotts to this ticket because she's currently working with the pension SME to get approval on the protect rates page. Beth, see above. If you happen to be able to ask Angie about how often people are asking for pension appeals, that might help inform this...otherwise, we may be able to just not add for now based on numbers and reassess if/when a need is raised. Thanks!

**Comment by mnorthuis** [comment]
To do:

- Review/validate all entry points have been added per the top description. (@mnorthuis to do this)
- We determined that an entry point in the Pension top nav is not necessary based on low search volume. 
- [Legacy board appeals page](https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/) needs to be moved into Decision Reviews area along with other legacy pages.  This can be done via redirect/url change request.  
- Prior to this ^^^ there should be a discussion around the content, H1 and URL of the legacy page to ensure that it is differentiated enough from the new [Decision Review Board of Appeals page](https://www.va.gov/decision-reviews/board-appeal/)  @bethpottsVADEPO to lead this

**Comment by mnorthuis** [comment]
Reviewed the implemented changes against the issue description.  There are 2 items that need to be fixed:

1. For Life Insurance, the left nav option should be moved up to the 5th option, just under "Check appeal status"

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/87e0167a-70b4-4b24-88b0-1defb68aaaab)

2. This item in Burials is not done:  
https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/
To be consistent with other benefits, add link to the claim status tool to the "If you don't qualify" section
Label and link: Check your VA claim status https://www.va.gov/claim-or-appeal-status/

All of the remaining unchecked items are documented in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10773

**Comment by RLHecht** [comment]
@mnorthuis I fixed the left nav for life insurance. Should be visible by later this afternoon. Please let me know if it's not.

**Comment by lwalsh617** [comment]
@mnorthuis @RLHecht -- I added the claim status tool link to https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/.
Here's the Drupal preview link: 
http://preview-prod.vfs.va.gov/preview?nodeId=863

**Comment by RLHecht** [comment]
@mnorthuis @lwalsh617 Just reviewed and published this page. It will be live after tomorrow's deploy. Can this be closed after validating? FYSA @MickinSahni

**Comment by mnorthuis** [comment]
Reviewed the entry point changes above and changes look good to me, thank you!

I believe the only items left to do on this issue are:
- Legacy board appeals page needs to be moved into Decision Reviews area along with other legacy pages. This can be done via redirect/url change request.
- Prior to this ^^^ there should be a discussion around the content, H1 and URL of the legacy page to ensure that it is differentiated enough from the new Decision Review Board of Appeals page @bethpottsVADEPO to lead this

**Comment by lwalsh617** [comment]
^ @mnorthuis and @MickinSahni @bethpotts -- We created a new ticket, [11229](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11229), to address the board appeals pages. We may merge the two pages, so would not need to move legacy appeals page to decision reviews. Will note on that ticket that we need to move legacy page if we do keep it. Closing this ticket.
