### ISSUE TITLE
10-7959c (Section 2): applicant contact information (remove email address)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82772]
**Form**: 10-7959c
**Section 2**: Applicant information contact information screens
**Issue**: Email address does not appear in the [10-7959c](https://www.va.gov/vaforms/medical/pdf/VA-10-7959c-fill.pdf) paper form currently and needs approval from the business first before it can be added to the online form.

**Current result**: email address appears on the contact info screen
**Expected result**: email address is not shown in the contact info screen (only the phone number field should display).

Figma link: https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=824-40187&t=79r2eTyXGKkp9txB-0

<img width="731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9qQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e0e4081f03219e80683d5fdee6547cf60376093/Screenshot%202024-05-15%20at%2011.54.18%E2%80%AFAM.png" alt="Screenshot 2024-05-15 at 11.54.18 AM.png" />

**Comment by michaelclement** [comment]
[Work is done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29937). Waiting on:

- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 this has been merged and will show up on staging shortly for you to review. Thanks!
