### ISSUE TITLE
[Design] Claim Status: Document Existing Design

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8277]
TBD placeholder for planning

**Comment by kevinstachura** [comment]
Claim Status Tool mapping has been turned into a PDF, uploaded to GH and can be viewed here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/claim-status-tool-mapping.pdf
