### ISSUE TITLE
Adjust helm chart to inject access cert at deploy of control plane

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#82773]
## Issue Description

A .pem file is used by the GitHub Apps (associated with prt-preview-manifest-prb repo) to authenticate the Control Plane and allowing the Control Plan to trigger workflows such as deploy-environment within the prt-preview-manifest-prb repo. The content of the .pem file is sensitive and should be securely stored and accessible to the Control Plane

---
### Tasks
- [x] Update helm chart to inject access certificate at deploy of control plane

### Acceptance Criteria
- [x] Certificate file is accessible to the control plane API

**Comment by ericboehs** [comment]
Let's assume we'll use a GH secret for storing the PEM.
