### ISSUE TITLE
Secondary Nav - Hovering away from an item changes the background shape from rounded edges to sharp edges

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#82797]
Environment: Staging
Staging user: vets.gov.user+0@gmail.com

Summary: On the secondary-nav, when the user is hovering away from one of the secondary nav items, the background hover shape changes from rounded edges to sharp edges. See attached video for reference

Steps to reproduce:
1. Login to staging with a user that has secondary nav enabled (use the user mentioned above if needed)
2. Navigate to the MyHealtheVet landing page
3. Hover using the cursor over one of the secondary nav items besides "MyHealtheVet" so that the secondary nav item is in a hover state
4. Move cursor away and take note of the background shape

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38aaebc5ddde0b1ccc96bd35fd72bafe3eae62b1/Screen%20Recording%202024-05-09%20at%2010.11.55%E2%80%AFAM.mov)

**Comment by carlosfelix2** [comment]
Already implemented in another issue
