### ISSUE TITLE
Include content from old doc into the official doc for Code Review Norms

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#8280]
There is some really fantastic content included in our deprecated vets.gov [Code Reviews Norms doc](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Code%20Review%20Norms.md) that aren't in the va.gov [version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md). I think including this content in the new doc would be very valuable to set expectations of how to conduct code reviews and what should be expected as an author.

Slack thread - https://dsva.slack.com/archives/CBU0KDSB1/p1587574477339100

### Acceptance criteria
- [ ] Content from vets.gov doc is included in the new va.gov-team doc for code review norms

**Comment by gunsch** [comment]
extra context: we *very explicitly* reduced the size of that doc substantially when rewriting. the first one is like 4-5 pages of prose that's a mix of "advice" and policy etc., the latter is much more process-focused. the intention was *not* to consolidate.

can you share about if there's specific content you think needs to be added to our code review _process_?

if this is about things like "best practices for reviewing code" and communication around it, I don't mind bringing that over, but please do so in a separate advice document around _communication norms_ and _best practices_ (or find some similar ones to link to, i.e. Google's [how to write code review comments](https://github.com/google/eng-practices/blob/master/review/reviewer/comments.md)), but let's keep that separate from the more policy/process oriented docs.

**Comment by ncksllvn** [comment]
Thanks @gunsch! That makes perfect sense. I suppose I personally think the advice there is helpful for setting expectations for authors and reviewers. I thought it was a really helpful part of my onboarding on vets.gov, although we're definitely a much bigger space than back then.
