### ISSUE TITLE
VRE 1A | Regnerate PDFs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#82812]
## Issue Description
_Regenerate batch of 12 VRE 1A pdfs with corrected date stamp that displays the date the claim was submitted rather than the date the pdf was generated._

---
## Acceptance Criteria
- [ ] Regenerate pdfs with date claim was submitted stamped in signature line
- [ ] Post pdfs to VA Sharepoint and overwrite the original pdfs that were submitted there

**Comment by evansmith** [comment]
@steele-lm I shared the file with you in OneDrive after confirming the dates.
