### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by LouisFettet** [department-of-veterans-affairs/va.gov-team#82825]
### Name

Louis Fettet

### Email

Louis.Fettet@va.gov

### Role

Engineer

### Team

Octonaut

### Product Manager (PM) name

Liz Townsend

**Comment by LouisFettet** [comment]
As our team doesn't have a dedicated designer, I will also need editor access.

cc @liztownd

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to [Louis.Fettet@va.gov](mailto:Louis.Fettet@va.gov). Let me know once you create an account and I'll bump you up to have full access.

**Comment by LouisFettet** [comment]
@naomimarcussen thanks! I've created my account.

**Comment by naomimarcussen** [comment]
Great! You're account now has full access.

**Comment by LouisFettet** [comment]
Thanks @naomimarcussen! Closing this out.
