### ISSUE TITLE
Implement and Refine Feedback From Design Intent for PCPG

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8282]
## Goal
After recieving feedback from the Design Intent Review, we need to  implement those recommendations where they make sense

## Considerations
If the Veteran is logged in, does that change the options on Step 1 at all? (Would we make any assumptions about who they are if they already have an account? For example - would we remove “Active duty service member with 6 months or less before discharge”?--We discussed this and for MVP we will give all the options--there’s talks in the future that it’d be more specialized.

## Tasks
- [x] Make changes to the screens to align with [recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8294) as necessary.

## Acceptance Criteria
- [x] Changes have been made and team and interested parties have been notified

**Comment by sporeboy** [comment]
Most feedback incorporated. Potential logged-in Veteran workflow added here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/screen/a21303f7-0ce5-45f1-82ef-251652c20c36/8832-Applicant-Info-LoggedIn-1
