### ISSUE TITLE
Epic: Sketch Audit

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#82847]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Design Team Member, I need to see guidance on Figma so I can work effectively with this tool.

## Hypothesis or Bet
**If** we replace Sketch mentions with guidance on Figma **then** design teams will be able to work more efficiently with Figma.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

All issues are completed, resulting in mentions of Sketch on Platform Website have been replaced with mentions of Figma tool.

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by laucon** [comment]
Done. @jknipes Can we close this?

**Comment by jknipes** [comment]
All issues in this epic have been completed and moved to _Closed_ pipeline. Definition of Done has been met, moving Epic to _Closed_
