### ISSUE TITLE
[Design] 1010d User Journey Map- First Draft

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#82843]
Using stakeholder, user and discovery research create a user journey map that captures personas, pain points and feelings and opportunities in the stages of typical CHAMPVA Enrollment. 

## Definition of Done
- [ ] Complete of 1 first draft of a visual graphic the user journey

## Assumptions
We can use what we learned up to this point to map out and validate the steps that a user takes after, during and immediately after enrollment.

**Comment by syd-hoeper** [comment]
First draft is complete: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715338195102/652a0008afe8f2bf45baf0154223a251a4a2c7c3?sender=uef36611991f345316f538329
