### ISSUE TITLE
Discovery for Sketch Audit - Testing your prototype with assistive technology users

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#82845]
Ask Naomi if we need to change anything other than the 1 line involving Sketch in [Testing your prototype with assistive technology users](https://vfs.atlassian.net/wiki/spaces/RD/pages/2500329488/Testing+your+prototype+with+assistive+technology+users)

## Acceptance Criteria

- [x] Next steps are determined on how to edit  [Testing your prototype with assistive technology users](https://vfs.atlassian.net/wiki/spaces/RD/pages/2500329488/Testing+your+prototype+with+assistive+technology+users).

**Comment by jknipes** [comment]
Work is complete, moving to _Done_
