### ISSUE TITLE
Research and Document Reporting Analytics related to Usability findings

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#82844]
The purpose of this ticket is to research and document reporting analytics related to Usability Research findings to help inform prioritization discussions.  

**Tasks**:

1. Perform research in Google Analytics, Domo and potentially backend queries to better understand Veteran behavior related to pain points in the [Research findings document](https://docs.google.com/document/d/1nI0g96Or0_sOsjnvyno9bzh_HxIuPt3n3Imb1tNIamw/edit#heading=h.kdz1ermzo8pq). Look at dropoff points and other relevant metrics against specific pain points identified and document findings.

2. Use findings to re-prioririze undone tickets attached to [Usability Findings epic](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/77821)

3. Create summary artifact to share what analytics is available and where to find it

**Comment by buddhima-coforma** [comment]
I pulled stats on drop offs from DOMO https://docs.google.com/spreadsheets/d/1Ccw5b_-E0AuJHgBKlIczW36AWx-RaSM-moVtaUmj26Y/edit#gid=1221853331

**Comment by buddhima-coforma** [comment]
Was recommended to use the new [GA4 view](https://analytics.google.com/analytics/web/#/p419143770/reports/explorer?params=_u..nav%3Dmaui%26_r..dataFilters%3D%5B%7B%22type%22:1,%22fieldName%22:%22unifiedPagePathScreen%22,%22evaluationType%22:3,%22expressionList%22:%5B%22527ez%22%5D,%22complement%22:false,%22isCaseSensitive%22:true,%22expression%22:%22%22%7D%5D%26_u.comparisonOption%3Ddisabled%26_u.date00%3D20240401%26_u.date01%3D20240513%26_r.explorerCard..rowsPerPage%3D50&r=8103367555&ruid=all-pages-and-screens,business-objectives,examine-user-behavior&collectionId=8103362278) in Google Analytics

**Comment by aplatt-coforma** [comment]
@djones2113 - adding you to this ticket for awareness

**Comment by aplatt-coforma** [comment]
Working doc that Buddhima created to knowledge share some of the analytics reporting that he was aware of: https://docs.google.com/document/d/15Zyp-s2b0FyPUesZ-owS8wCsf2wXS6Kiv0gL9M_UK3Q/edit
