### ISSUE TITLE
Staging Review finding: Change expandable alert to additional info on gross monthly income page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#82851]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Pension benefits
**Product:** 527EZ
**Feature:** Update multi-response (single page list loop) pattern

## Findings details
**VA.gov Experience Standard - issue:** [User encounters design components that are inconsistent or confusing.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

The Gross monthly income page has an expandable alert for the definition of "What is income?". We have noticed alert fatigue on VA.gov and according to our guidance, we only want to use alerts when absolutely necessary.

<details><summary>Link, screenshot or steps to recreate</summary>

![Screen shot of alert](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/81262-Allison-02.png?raw=true)

</details>

## Recommended action

Per [our guidance](https://design.va.gov/components/alert-expandable#when-to-consider-something-else), use additional info for clarifying background information, therefore you can switch this to the additional info component.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Alert-Expandable ](https://design.va.gov/components/alert-expandable)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by echin393** [comment]
Gretchen was a little wary of hiding the definition of income in a collapsed state, which informed the decision to make it an Alert instead – but because we now display the definition of income on the previous page (cannot be hidden), we can move forward with changing the Alert to an Additional Info component.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/82851?planning-poker) with Zenhub @ToddWebDev @TaiWilkin
