### ISSUE TITLE
[Bug] How to Apply Wizards not loading

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#8285]
## What happened?
How to Apply Wizards on [Disability Eligibility ](https://www.va.gov/disability/eligibility/)+ [Disability Claim](https://www.va.gov/disability/how-to-file-claim/) and [Education Eligibility](https://www.va.gov/education/eligibility/) **pages are not loading**. 

## Specs:
- Device: PowerMac, Catalina OS v. 10.15.4
- Browser: Chrome only; working in FireFox and Safari
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: 
https://www.va.gov/disability/eligibility/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/education/eligibility/

Note: @kelsonic and @ncksllvn have done some preliminary digging into this.

- Test User _(if applicable)_:

## Desired behavior
_User clicks on page
_Wizard should load asynchronously with page

## Acceptance Criteria
- [ ] Wizards should load asynchronously with page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by stephorkandatx** [comment]
Short update on this - 
We began to take a look and noticed a few things. 
It may be tied to app state somewhere, since it clears after a cache reload. 

This may end up be routed to Benefits Memorial team but we would like to take a look.

**Comment by ncksllvn** [comment]
Yeah, I think it's something to do with a change to our cache-breaking strategies. Thread here - https://dsva.slack.com/archives/CBU0KDSB1/p1587579822357900

**Comment by stephorkandatx** [comment]
Update on this: The Platform team has opened a ticket to look into the matter that we are experiencing. Their ticket for tracking is https://github.com/department-of-veterans-affairs/va.gov-team/issues/8560 .
