### ISSUE TITLE
"New" tag on MHV landing page H1

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82866]
### User story

As a Veteran, I want to see a "new" tag, so I notice things are different and I am in a new experience of My HealtheVet. 

### Notes
- Releases simultaneous with integration, use same toggle as other integration changes to links on landing page

Possible tasks:

- [x] Design: Add tag to landing page (mobile/desktop) 

## Acceptance criteria
- Implementation reviewed by UX team
- QA review
- A11y review

**Comment by jonathanjnelson** [comment]
[Please see Figma design file ](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2165%3A24483&t=tBDV9LOhLhmINQ2n-1)

<img width="1108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--549031933b43e46c907b474fa1fcec92faebcf9f/Screenshot%202024-05-14%20at%202.46.45%E2%80%AFPM.png" alt="Screenshot 2024-05-14 at 2.46.45 PM.png" />

**Comment by sterkenburgsara** [comment]
Related decision on "NEW" tags per Kaitlin Fink & Kristen McConnell ([Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1715706453911669)): 
* NEW tags will also be implemented on the Messages and Medications landing pages (not on Appointments, which is no longer considered "new"); at a later date we will consider using it on the BTSSS travel reimbursement claims status tool being developed and going through research now. 
* NEW tags will likely be used for around 6 months, until Medical records hits Phase 1.

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29791
