### ISSUE TITLE
[Security - Controls Effort] Create new AWS group for SBOM access

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#82861]
## Description
Security team would like access to Athena and possibly AWS Glue in order to run crawlers manually.
They should be able to see default Queries and create new ones on the SBOM table.
 NOTE - This story may rely on IaC for Athena, Glue and S3 bucket to be complete.

## Acceptance Criteria
- [ ]  New AWS Group/Roles/Policies in Terraform
- [ ]  Add Security users to new role
- [ ]  Create a "Getting Started" Document to pass on to Security folks.

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by adhoc-nshipman** [comment]
Currently, we are blocked waiting for Ken Mayo to gain AWS access before we can test permissions. 
Here is the PR in case I am unable to take this over: https://github.com/department-of-veterans-affairs/devops/pull/14575
