### ISSUE TITLE
[Security - Controls Effort] SBOM for AMIs

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#82862]
## Description
To meet and mature in the ID.AM-1 and ID.AM-2 security controls, Infrastructure Services would like to create the same SBOM GHA workflow logic utilized for the container images. Leverage the already created logic of `GHA Task -> S3 Bucket -> AWS Glue -> Athena` for our Amazon Machine Images Builds (AMIs). 
Note - Same JSON formatting will be required

## Resources 
- https://github.com/aquasecurity/trivy

## Acceptance Criteria
- [x] Instrument new folder in SBOM bucket for AMIs
- [x] Attach AWS Glue crawler (same one as container images or new one?)
- [x] Create queries that pull data on AMI packages
- [x] Add anything to the IaC as needed

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
Working on implementing Trivy and then SBOM on the AMI workflows. Should begin testing this afternoon

**Comment by Efe-Oddball** [comment]
Trivy worked good. Working on implementing SBOM using the existing SBOM work flow. I have to make some updates on the SBOM workflow, considering that the workflow was built with he assumption that the image is being pushed to ECR, which is not the case for the AMIs. Making adjustment so SBOM is created and pushed to S3 regardless of ECR usage.

**Comment by Efe-Oddball** [comment]
Updating ticket point to a 5 as it involves updating the shared SBOM workflow to accommodate AMI builds before before referencing the SBOM workflow within the AMI workflow

**Comment by Efe-Oddball** [comment]
I am having some issues with with Trivy functionality for the ami scanning that I am trying to work around. Trivy was working properly as it should with the AMI. I thought it was working good before but after digging through the output, I found that not to be the case.
I have created a separate shared SBOM  workflow for the ami with slightly different set up from the ocker image SBOM workflow

**Comment by Efe-Oddball** [comment]
Once I am done with the workflows, I will have to update the terraform to include crawlers for the AMI SBOM. Unfortunately, this ticket will have to be carried over to the next sprint

**Comment by Efe-Oddball** [comment]
I have gotten a breakthrough with Trivy and Cyclonedx for security and SBOM. functioning. I will update the the other workflows and terraform code, then push out the PR

**Comment by Efe-Oddball** [comment]
The Parker- hardened, EKS and ghar Workflows have been updated and tested for extraction of ami-id, trivy functionality and SBOM creation. I have also updated the terraform code, implementing the setup for lambda function and crawlers for all of those images. All I need to do is test the crawler, and once that is done, I will push out the PR required to resolve this ticket.

**Comment by Efe-Oddball** [comment]
I have pushed out all the PRs required for this workflow. Once the PR is approved, I will move the ticket to a resolved state

**Comment by Efe-Oddball** [comment]
I had Hector review the complete work on Friday, and there are a few updates I am working on to clean up the setup. The crawler tended to create a new table every time it ran, so I had to figure out the reason why and fix that. Not I am working to fix the issue where the crawler overwrites the output of the crawl on the existing table, instead of appending the output.

**Comment by Efe-Oddball** [comment]
All PRs have been merged, and I am moving this ticket to a resolved state

**Comment by kflow85** [comment]
This ticket is complete and is also tracked o GitHub Projects https://github.com/department-of-veterans-affairs/va.gov-team/issues/82862#issue-2289923270
