### ISSUE TITLE
Update SIP documentation with new FORM_LINKS configuration

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#82865]
### Description
Previously, when setting up save-in-progress for forms, the form ID was added to an object in vets-website in `src/platform/forms/constants.js` called `FORM_LINKS`. However, as of early 2024 that object no longer exists (under that name), but has been converted to a function `getAllFormLinks` that produces the same output as the previous object. Because of this, searches in the codebase for `FORM_LINKS` no longer explicitly lead to the correct object, and the documentation is referring to something that doesn't exist strictly speaking.

Recommend updating the content to point to the appropriate function name rather than to the `FORM_LINKS` object.

### Tasks
- [x] update page as recommended

### Acceptance Criteria

- [x] page has been updated and is ready for deployment

### Relevant URLs
- [Documentation that needs to be updated](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si) (specifically the bullet point that discusses `FORM_LINKS`)
- [PR where the change was made to](https://github.com/department-of-veterans-affairs/vets-website/commit/eb4b91c0488fbf5438f2c2f1511f34e051bf1f73) `FORM_LINKS`

### Which type of team are you on? (Platform team, VFS team, or Leadership)
- Integrated Veteran Care/CHAMPVA (form development team)

**Comment by jknipes** [comment]
Adding ticket to this sprint, due to increased capacity with the removal of ticket [72001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72001)

**Comment by taylojill** [comment]
Hi @michaelclement - I'll get the page updated and published on Monday May 13th. Thanks for letting us know!

cc @jknipes

**Comment by taylojill** [comment]
Hi @michaelclement - I updated the link text as requested. The page will be published on May 13th. Thanks for flagging this!


![2024-05-11_12-00-30](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/1fa1c485-1387-471b-8aef-86aca98b4fd9)


cc @jknipes

**Comment by taylojill** [comment]
Page updated and checked for launch blocking issues, ready for deployment.

**Comment by jknipes** [comment]
Tasks completed, AC met, moving to _Done_
