### ISSUE TITLE
Add 404 page not found pattern to the design system

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#82879]
### User story
As a designer, I want to have documented guidelines on how to use the 404 page not found, so I can design a consistent user experience.

## Acceptance criteria
- Create Figma file for this (required for VADS submission)
- Request ticket submitted to design system team
  - including suggestion for governance (e.g., DST take over 404 from CAIA)
  - include link to dev docs

**Comment by fmccaf1** [comment]
Could I get some help/guidance on what the figma file is/does?

**Comment by fmccaf1** [comment]
Images of screen to be mocked in Figma: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/9caea9f3-3aae-447b-84f0-b41a553ed843)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/d97601d0-5651-4d29-b6bc-dae33221cc26)

**Comment by fmccaf1** [comment]
[Experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2912) - it's pretty bare bones as I think the component is self explanatory (especially because it's called "404 page not found")
