### ISSUE TITLE
AWS access for Vanson Samuel

### ISSUE THREAD

**Issue by binq** [department-of-veterans-affairs/va.gov-team#82870]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Vanson Samuel

### Your Email

vanson.samuel@va.gov

### Team, Role, and Company of the target individual

Verify Your Enrollment, Programmer (vets-api), GovCIO

### Product Manager (PM) name and email

Jason Wolf (jason.wolf@govcio.com)

### Product Owner (PO) name and email

Darla van Nieukerk (darla.vannieukerk@va.gov)

### Desired AWS Access

I require read and write access to the following S3 buckets to enable communication between the VYE app on vets-api and BDN, Newman, and TIMS for daily data transfers related to verification of enrollment:

    dsva-vagov-staging-platform-sftp-internal
    dsva-vagov-prod-platform-sftp-internal (once it is created)

PS
I was told: "You will want to mention that VYE AWS group(s) will be needed. That way we can add/remove anything we need when it comes to your access."

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37637/b4de186b-aea1-4a4b-a3bf-c16ec7df64c3)

### Additional Notes

COR name Joseph Riccio (joseph.riccio@va.gov)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
eQip passes inspection
Vanson Samuel found in Atlas

**Comment by patrick-black-oddball** [comment]
Added to vye-developer role
