### ISSUE TITLE
[Security - Controls Effort] DISCOVERY | Evaluate AWS Config as an overall Platform compliance solution

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#82888]
## Description
To meet and mature in the ID.AM-1 and ID.AM-2 security controls, Infrastructure Services would like to evaluate/research the expanded use of the AWS Config tool. There seem to be a few things there but we can take a deeper dive to see how it could benefit us more.

## Resources 
- https://aws.amazon.com/config/
- https://tutorialsdojo.com/aws-config/

## Acceptance Criteria
- [x] Evaluate what is currently running
- [x] Evaluate any particular components of AWS Config that can immediately benefit Platform along with respective pricing
- [ ] Document any considerations and basic scenarios of interest

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
Doing a deep dive on AWS Config to get a full grasp of the capabilities, then I will work on identifying AWS Config attributes we are currently using as well as attributes that can be integrated

**Comment by Efe-Oddball** [comment]
Completed a deep dive on AWS Config, and I am trying to get a full grasp on how we are currently using AWS Config

**Comment by Efe-Oddball** [comment]
AWS Config is already applied to this account and apart from the Conformance pack feature of AWS config, there are already standard compliance rules in place, the dashboard is functional and with the activation of the recorder configured, other features like inventory, and config changes as it relates to configuration item are already being forwarded to the DSVA config bucket. I am working on how best to extract information like configuration changes, software updates, and other information like that. Then I will write up a short summary of findings

**Comment by Efe-Oddball** [comment]
Still trying to use Athena to extract resource configuration data from the S3 bucket. Hoping to round this up in the next few hours.

**Comment by Efe-Oddball** [comment]
Here is the link to the documentation that shows work done on AWS Config Discovery

https://docs.google.com/document/d/1vlXa-DvCbH9kuXqYIBNGNBjsYfJXf7Ou6bGoKhKFrQ0/edit

**Comment by Efe-Oddball** [comment]
Work on this ticket is complete. Moving the ticket to a resolved state.
