### ISSUE TITLE
[Design] Create template & spacing page in Figma and Screenreader spec page in Figma

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#82898]
## Tasks

- [ ] Create template/space page in Figma
- [x] Create Screenreader spec page in Figma for headings, aria labels, and any screenreader notes. Utilize [VADS Web Annotation Toolkit Figma Library components](https://www.figma.com/file/CZcnWfQOwtLqPm4WA5paYG/VADS-Web-Annotation-Kit?type=design&t=NYplyCPMLQXsfs5O-6). 
 

[Figma link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1873-32086&t=6czMYKo46fUHPLmf-1)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/82898?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by benbrasso-agile6** [comment]
@Cieramaddox how's this ticket coming along?

**Comment by cgednalske** [comment]
From our chat today, it sounded @Cieramaddox is done with the specs page - which looks good to me 🎉  (validation if needed).

It also seems like her [other ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83373) is kind of covered in the specs work as well - as far as tablet and desktop? 👀
