### ISSUE TITLE
[Research] Draft convo guide for research study 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#82900]
## Tasks

- [x] Draft convo guide 
- [x] Get it in a place to begin receiving feedback from different teams and individuals that are involved

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/82900?planning-poker) with Zenhub @cgednalske

**Comment by cgednalske** [comment]
I think we can close this - @benbrasso-agile6 do I need to open another ticket for incorporating feedback or just continue to complete separately?

**Comment by benbrasso-agile6** [comment]
Is it 1 pt or less?

**Comment by benbrasso-agile6** [comment]
I'll create a ticket real quick
