### ISSUE TITLE
Update link treatment of newsletter signup on MHV landing page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#82904]
### User story

As a Cartography team member, I want to make sure that we are not putting visual prominence on links that lead users away from VA.gov. 

### Notes
Per a conversation with Sara, Jonathan, and OCTO design lead Kaitlin Fink, we want to remove the prominent link treatment given to the newsletter signup link at the bottom of the landing page (get rid of the secondary action link treatment) and dial it back to just make it look like a regular old link.

<img width="763" alt="Screenshot 2024-05-10 at 4 21 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/b4d364d5-da29-485a-930b-803847b3b5d1">

Possible tasks:
- [ ] Change style of link (update component from secondary action link to regular link)
- [x] Devs make update

## Acceptance criteria
- [x] Newsletter link on landing page is no longer a secondary action link, it is now just a regular link (visually) (still has "opens in new tab")
- [ ] UX update Figma files for the landing page to match
- [ ] UX review in staging
- [x] A11y Review

**Comment by dcloud** [comment]
PR is up with visual change.

**Comment by fmccaf1** [comment]
Looks good in staging: 
<img width="791" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/ce9701db-b6ba-40eb-82f4-389326c5a0c7">

**Comment by fmccaf1** [comment]
I'm wondering @jonathanjnelson @sterkenburgsara @brea11y about the possibility of changing the link to look like this:

<img width="745" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/12214019-83cf-46d4-9acc-da7ce2a103d8">

Please share your thoughts!

**Comment by fmccaf1** [comment]
Hey @dcloud sounds like UX is aligned on moving forward with the design posted in my last comment (where the link is in-line with text). Let me know if you have thoughts or questions

**Comment by dcloud** [comment]
It looks like the mockup expects a page wrap at approx column 8 (of 12), which is the same as the introtext column…

**Comment by dcloud** [comment]
New PR will have screenshots shortly: department-of-veterans-affairs/vets-website/pull/30056

**Comment by dcloud** [comment]
Moved back to code review, assigned @fmccaf1 and @jonathanjnelson as reviewers on the PR, so they can look at the before/after screenshots

**Comment by fmccaf1** [comment]
Just checked out the screenshots in your PR and looks good @dcloud. Thank you!

**Comment by brea11y** [comment]
This looks great on my end and I see no accessibility issues. The link copy makes it clear to a user that they will be taken to an external site and it opens in a new tab, as expected.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this matches the proposed designs and is working as expected
