### ISSUE TITLE
[DESIGN] Finalize Figma Wireframes for Research

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#82902]
## Background
We plan to pursue moderated research that combines usability testing and concept testing. 

## Task
- [ ] Finalize Figma Wireframes for Research

## AC
- [ ] Wireframes have been created and shared with the team

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/82902?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/82902?planning-poker) with Zenhub @Cieramaddox
