### ISSUE TITLE
Add Medication Review Content to Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#82910]
## NOTE
Feature must be wrapped in a feature flag so that we can do a staging review.

## Description
We had an OIG/Congressional request come in to add some medication-related content to appointment notifications and detail pages for all appointment types on all channels. This impacts the mobile app, VA.gov web appointments, email reminders, text message reminders/pre-check-in, MHV Classic, and My VA Health portals. The objective is to remind Veterans to be ready to talk about any medication, supplement, vitamins, etc that they have been prescribed or are taking from any provider, VA clinic, or local store.

## Wireframes & Approved Content
- [User flow](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=545-5197&t=yWaeOEybo9LZgK1O-4)
- [PCI mockups](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=i7ZsGuqPq3w40iGu-4)
- [Final language](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZ1cVb_w1MZEod5kMVhU6dwBrMJD5C56RAwbfSerVCgqhg?e=tyTF62) (VA Network)

## Tasks
- Create the new "What should I bring to my health care appointments" page 
- Add new content to details page
- Add new content to completion page
- Add feature toggle in vets-api and vets-website `check_in_experience_medication_review_content`

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/82910?planning-poker) with Zenhub @brianseek @wullaski

**Comment by loripusey** [comment]
@brianseek @wullaski I think we need to re-point this as it involves creating a new page; @benbrasso-agile6 is updating the mock-ups that Peter prepared; @zach-park will update our CIE wireframes simultaneously with FE doing the work, so let's get with @benbrasso-agile6  and @zach-park to make sure we understand what the work is exactly

**Comment by brianseek** [comment]
@loripusey / @benbrasso-agile6 / @zach-park / @cgednalske 
This is merged and behind a feature flag. The feature can be turned on in stage to review. Also please see attached screen shots that show changes with the feature on and with the feature off.[feature-on.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2N4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--114cabb37da56126b54bcc5273ac11448df5c290/feature-on.zip)
[feature-off.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2d4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a737ff6a79d91d18fe49fc04f0ee7d2bd519c797/feature-off.zip)

**Comment by loripusey** [comment]
LGTM

**Comment by loripusey** [comment]
If UX needs a ticket, please create one.

**Comment by benbrasso-agile6** [comment]
What's different, Zach? I might have told Brian to change something.

**Comment by benbrasso-agile6** [comment]
Zach, that link you provided is for adding upcoming appts NOT medication review, which Brain is preparing for release.

**Comment by cgednalske** [comment]
If I'm interpreting it correctly, Zach might be bringing up a good question I was wondering about as well. If the medication review info includes some of the links that we're currently working to incorporate into the appointment list and confirmation page in the link collection format, we'll now need to think through how those different link collection designs work together.

**Comment by cgednalske** [comment]
In general everything looks good though for medication review 👍

**Comment by brianseek** [comment]
ok so it sounds like this ticket can be closed, and we will probably be changing some of these things in future tickets?

**Comment by benbrasso-agile6** [comment]
Knowing that medication is out in prod waiting on a feature flag, let's account for it now in the upcoming appts wireframes. 

I thought I analyzed this already and decided there was no concerns. But, I may have made a mistake. 

Yeah, let's go ahead and tackle it now.

**Comment by benbrasso-agile6** [comment]
Note: for UX, medication is just pre-check-in.

**Comment by benbrasso-agile6** [comment]
Oooooh, I see the issue for upcoming appts work. Good catch.

**Comment by benbrasso-agile6** [comment]
I can help with scheduling staging review next sprint. Should make sure John or someone completes(ed) the A11y artifact.

**Comment by brianseek** [comment]
so yes this can be closed?

**Comment by zach-park** [comment]
@brianseek , apologies for the commotion which I created...

**Comment by benbrasso-agile6** [comment]
I think it was good commotion :)

**Comment by brianseek** [comment]
I agree that it was a good thing to bring up, but I just want to know if this one is good to close. I'm not following al lthe UX nuance. 😢

**Comment by benbrasso-agile6** [comment]
You got many thumbs up that this release is GTG :)

**Comment by brianseek** [comment]
thanks!
