### ISSUE TITLE
Review Design system updates (within May and June)

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#82916]
## To do
1. Read through [this thread](https://dsva.slack.com/archives/C03R5SBELQM/p1714612416352079) and identify what applies to pension app
2. Specify what work needs to be done, in this ticket or create additional tickets

Summary of slack announcement from Design Systems team
1. Iconography - Teams can begin using va-icon instead of font awesome now, May 1st.
We do not use icons on our forms. 
2. V1 component deprecation - May 8th
We have completed this audit and work. (#75396, [Audit document with engineering tickets/status])(https://docs.google.com/document/d/1W7FtOdRj5sT_N9b5UFSGWzsR689WgQsgsVcRGfrp4OM/edit)
3. Typography Step 1: Root change from 10px to 16px - Wednesday, May 22
**The ask**: teams should conduct visual QA only on their applications using the review instance on this pull request, or, pull the branch locally and QA there. Checking heavily trafficked pages of your application should provide enough QA confidence.
**NOTE:** this change will result in no visual difference because all rem values have been scaled down.

### Acceptance Criteria
- [x] Conduct visual QA only of Pension http://db3498b1f26109865dedf10fc8d28545.review.vetsgov-internal/pension/apply-for-veteran-pension-form-21p-527ez/introduction
- [x] Create engineering tickets to fix any visual issues

**Comment by aplatt-coforma** [comment]
Will need to request SOCKs access using this form: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy

**Comment by aplatt-coforma** [comment]
Completed review of the Pension form on their staging env and found no new issues. There is one issue with the Feedback button at the bottom of the form but the Design team are aware of it and will be address that issue on their side. Here are some screenshots of our forms on the testing environment that shows the font size changes.
<img width="91" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9lQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--700afa9260cf0f9933c5f2729c9775e23c171088/screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-apply-for-veteran-pension-form-21p-527ez-review-and-submit-2024-05-14-14_08_28.png" alt="screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-apply-for-veteran-pension-form-21p-527ez-review-and-submit-2024-05-14-14_08_28.png" />
<img width="492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkRlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5953a4ac79555cc5b2c4f85852bc5344cb92aa9d/screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-apply-for-veteran-pension-form-21p-527ez-financial-transferred-assets-2024-05-14-14_05_38.png" alt="screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-apply-for-veteran-pension-form-21p-527ez-financial-transferred-assets-2024-05-14-14_05_38.png" />
<img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkhlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e6d595d0a62eb94ba1df1ba9006bf728810fa1a/screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-apply-for-veteran-pension-form-21p-527ez-applicant-information-2024-05-14-13_00_34.png" alt="screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-apply-for-veteran-pension-form-21p-527ez-applicant-information-2024-05-14-13_00_34.png" />
<img width="273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkxlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ece450763d1f670a5957ef60a1d7aed14f646d8/screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-how-to-apply-2024-05-14-12_58_14.png" alt="screencapture-db3498b1f26109865dedf10fc8d28545-review-vetsgov-internal-pension-how-to-apply-2024-05-14-12_58_14.png" />

**Comment by aplatt-coforma** [comment]
@buddhima-coforma @matt4su - We should be good to go with the global font size change. Included a few screenshots of the form in the above comment. Will close this ticket as complete.

**Comment by buddhima-coforma** [comment]
@aplatt-coforma your screenshots above aren't loading for me
