### ISSUE TITLE
VYE tool: Add Montgomery GI Bill to Post-9/11 GI Bill FAQs page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#82923]
## Description
We need to add content about Montgomery GI Bill enrollment verification to this page: 

- [Enrollment verification for Post-9/11 GI Bill FAQs](http://preview-prod.vfs.va.gov/preview?nodeId=55607) (Drupal preview)

## Resource
- [Draft with SME feedback](https://dvagov-my.sharepoint.com/:w:/g/personal/beth_potts_va_gov/EaETv7nsFw9Juiaeitn3r2gBGg3PqWF_jjymkUcNoYzRUA?e=rKaqMM) (BP OneDrive)
- [Draft for CAIA collaboration](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EaxHxnpmJHhDtd5lFr3Q2KkBTuSlWO4sSU5S6pbliuq20w?e=e1oTyL) (CAIA SharePoint)

### Step 1: Get MGIB content
- [x] BP: Share PGIB content with SMEs
- [x] SMEs: Review

### Step 2: Publish new page(s)
- [x] AP: Draft updates in SharePoint
- [x] BP: Review
- [x] AP: Share with SME
- [x] SME: Review
- [x] AP: Update in Drupal and share with MZ
- [x] MZ: Copyedit and publish

### Step 3: Redirect URLs
- [x] AP: Ask IA to redirect these URLs to the new R&S URL(s):
     - [ ] Legacy page: [Enrollment Verification](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp)
     - [ ] Legacy page: [Monthly Enrollment Verification FAQs](https://benefits.va.gov/gibill/isaksonRoe/EV_FAQs.asp)
     - [ ] Modern page: [GI Bill WAVE FAQs](https://www.va.gov/resources/gi-bill-wave-faqs/)

### Step 4: Update existing page
- [x] AP: Add link to new page(s) on this existing page: [Verify your school enrollment](https://www.va.gov/education/verify-school-enrollment/)
- [x] MZ: Copyedit and publish

## Criteria
- [x] New page(s) published
- [x] Existing page updated
- [ ] IA opened a redirect ticket

**Comment by aprocik1** [comment]
Agreed! Thanks for catching this, @jennymayoco.

**Comment by bethpottsVADEPO** [comment]
@aprocik1 Now that we have feedback from Shay in the Sharepoint doc, let's talk in our meeting on Monday about how to approach this: Can we expand this existing FAQ to include MGIB similar to the approach on this page that covers multiple education programs per topic/Q:
- https://www.va.gov/resources/compare-va-education-benefits/

We do already have an existing R&S article where additional DEA information could go, so I think whatever additional info we need to add to this page for survivors and dependents can be considered separately from the EV info for Veterans for the 3 programs that we are figuring out how to cover: 
https://www.va.gov/resources/verify-school-enrollment-for-dea-benefits/

So what we need to consider now are these options:
- An FAQ that has enrollment verification info for Post-9/11, MGIB-AD, and MGIB-SR
- One FAQ that has EV info for Post-9/11 and then a separate one for both of the MGIB benefits
Note: I don't envision a scenario where we need separate pages for the 2 MGIB benefits.

Would you try the first approach where we include Post-9/11, MGIB-AD, and MGIB-SR all on one page? I think it's possible, but I think you'll have to get into it a bit before we know for sure. Keep in mind that if the page Katherine created last year doesn't seem like the right template in the end, we can change that up.

**Comment by aprocik1** [comment]
@bethpottsVADEPO, here's my attempt at including MGIB and PGIB information on one page:

- [Draft with my edits](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EaxHxnpmJHhDtd5lFr3Q2KkBTuSlWO4sSU5S6pbliuq20w?e=rEIIkg) (CAIA SharePoint)

**Note:** I'm not sure if the MGIB information needs to be separated into two sections -- one for active duty (chapter 30) and one for selected reserve (chapter 1606). SMEs didn't provide that level of detail in their review.

- [Draft with SME feedback](https://dvagov-my.sharepoint.com/:w:/g/personal/beth_potts_va_gov/EaETv7nsFw9Juiaeitn3r2gBGg3PqWF_jjymkUcNoYzRUA?e=rKaqMM) (BP OneDrive)

**Comment by aprocik1** [comment]
@bethpottsVADEPO, this updated document is ready for your review: [GI Bill enrollment verification FAQs V2](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EcY1s0N__AtOuf0Hv8Ls7ucB_NMyUfL5Z0iWg__HlzkOMA?e=GvnW2M) (CAIA SharePoint)

Let me know what you think. Thanks!

**Comment by aprocik1** [comment]
Update: I asked SMEs for an accuracy review of our most up-to-date [SharePoint document](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/Ee38wjkQYgZDqvdt3jF2wk0ByAYfhE_VvlRybACjBWeJOg?e=YNIzww). This document includes updates to both the static tool landing page and the R&S FAQ page.

**Comment by aprocik1** [comment]
Update: I shared this [Drupal preview](https://preview-prod.vfs.va.gov/preview?nodeId=55607) with SMEs yesterday. And then I shared this [SharePoint document](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EW7mMqmeaQRDmHDM8MmpdAQBzjxQw9rd8SysEiKpZQXWAA?e=HzZEHM) with them today. I'm awaiting their final feedback before updating the Drupal preview again.

**Comment by aprocik1** [comment]
Update: Beth has followed up with SMEs to ask for a status update on their review. We hope to finalize this content in time for launching the new MGIB verification tool.

**Comment by aprocik1** [comment]
Update: I incorporated SME feedback and shared this document with them: [GI Bill enrollment verification FAQs V6.docx](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EQJjR6_iS3JJhVdkbT9caggBCath87UIsNYmG0SOTucuUg?e=sVXbYH)

I'm awaiting clarification from Cinda and Tammy on one outstanding question.

**Comment by aprocik1** [comment]
Update: I've incorporated all SME feedback and shared this preview with them: https://prod.cms.va.gov/resources/gi-bill-enrollment-verification-faqs

@megzehn and @saratorres2, can you two copyedit and publish this page at the end of this week? I'm not expecting anymore feedback, but it's possible that SMEs respond with a last minute update. Thanks!

**Comment by aprocik1** [comment]
@megzehn, SMEs have officially approved this page. Can you copyedit and publish it by the end of this week? Thanks!

**Comment by megzehn** [comment]
Hi @aprocik1, confirming I reviewed and published [this FAQ page](https://prod.cms.va.gov/resources/gi-bill-enrollment-verification-faqs). 

Thank you to both you and @d-beyer for putting this together!

**Comment by aprocik1** [comment]
Update: I've shared the live page with SMEs. Megan and I are aligning on how to publish the crosslinks outlined in the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/1bd7d0a7b0f3ea91250c19c2c0813f9a0629c210/products/information-architecture/ia-design-docs/mgib-verify-enrollment.md#nav). We're very close to complete on this ticket.

**Comment by jennymayoco** [comment]
Thanks for flagging @aprocik1! For the last page, we already have a redirect for it in this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/87445. and we recommended redirecting to the the static page. Should I update this existing ticket to the new destination now that the GI bill faq page is live? I'll loop in @RLHecht who I had worked with on this redirect

**Comment by aprocik1** [comment]
@jennymayoco, you and Randi can decide where to redirect the GI Bill WAVE FAQs page. The reason I included it in my comment above is due to [your comment on this ticket on May 17](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82923#issuecomment-2118318038).

**Comment by megzehn** [comment]
Confirming that I worked with @aprocik1 and published crosslinks to the FAQs page, as suggested in the [IA spec.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/1bd7d0a7b0f3ea91250c19c2c0813f9a0629c210/products/information-architecture/ia-design-docs/mgib-verify-enrollment.md#nav)

**Comment by bethpottsVADEPO** [comment]
@jennymayoco Would you follow up with stakeholders in the email string ("Batch 2") about the latest timing for redirecting these 2 pages. I want to make sure we don't surprise them:
Legacy page: [Enrollment Verification](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp)
Legacy page: [Monthly Enrollment Verification FAQs](https://benefits.va.gov/gibill/isaksonRoe/EV_FAQs.asp)

**Comment by jennymayoco** [comment]
@aprocik1 confirmed with Beth we can update that the WAVE FAQ page to the new [GI Bill enrollment verification FAQs](https://www.va.gov/resources/gi-bill-enrollment-verification-faqs/) page. It looks like the PW team has implemented the original redirect so I'll if we can still update it.

**Comment by jennymayoco** [comment]
Hi all! I've sent out the email to the Edu stakeholders and created the redirect ticket #89623 for the two legacy pages
