### ISSUE TITLE
CMS deploy is not included in deployments page

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#82945]
### Description
https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments

va.gov-cms code deploys the Drupal CMS. Details on that deployment are not included on this page, and should be. 

@department-of-veterans-affairs/platform-cms-devops-engineers  are the SME group for details about that deployment. 

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by jilladams** [comment]
Also, there's a line on this page: "View the [Frontend Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard) or the [Backend Dashboard](https://deploy-status-dashboard.fly.dev/apps/vets-api/deploy_status) to see the deployment status of a vets-website or vets-api commit, respectively."

The Frontend dashboard also includes the status of content-build deployments, so could add that:

![Screenshot 2024-05-13 at 9 06 21 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/42ae9e5d-1de8-437e-8b7d-387e74a128d8)

**Comment by jknipes** [comment]
work will be documented on [78673](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78673)

**Comment by taylojill** [comment]
Hello @7hunderbird and @MDomngz - I am working on a request to add Drupal CMS deployment details to the [Deployments page on the Platform website](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments). 
Where should we add the information? I was thinking the **Automated deployment schedule** table but wanted to verify that with you. If not the table, where should it go? 
Please advise on the desired text as well as the location. I'll work with you to update the page and get it published. Thanks!

cc @jknipes cc @gracekretschmer-metrostar

**Comment by taylojill** [comment]
Hi @7hunderbird and @MDomngz - I added Drupal CMS to the table, see screenshot below. If this is correct, please provide the following to complete the table row: Changes in by, Deployment Start, Release Information, GitHub Action Workflow/Jenkins Job

Here's a [link to the page in our draft space](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3178168321/Draft+Copy+of+Deployments). I can get this page updated and published once the above information is provided.

Please let me know if you have questions. Thanks!

cc @jknipes @gracekretschmer-metrostar @jilladams 

![2024-05-28_08-36-44](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/f8639abd-f86b-4c42-a183-a7945991ec37)
