### ISSUE TITLE
Add caching capability to MAP::SecurityToken::Service

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#82969]
There are times when services hit the MAP::SecurityToken::Service multiple times to get the same access token. We should probably facilitate this by making a short cache on these tokens.

Cache should definitely be less than the token expiration, and should be enabled/disabled by an optional param when calling the MAP::SecurityToken::Service

**Comment by bramleyjl** [comment]
[Datadog logs](https://vagov.ddog-gov.com/logs?query=%22%5BMAP%5D%5BSecurityToken%5D%5BService%5D%20token%20success%22%20%40payload.cached_response%3Atrue%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1717524950590&to_ts=1717525850590&live=true) of MAP token responses returning a cached token.
