### ISSUE TITLE
SOCKS access for Anh Platt

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#82965]
### Your Name

Anh Platt

### Your Email

anh.platt@coforma.io

### Your GitHub Handle

aplatt-coforma

### Your Role and Team

Delivery Lead/Project Manager

### Product Manager (PM) name and email

Buddhima Kurukulasuriya / buddhima.kurukulasuriya@coforma.io

### Product Owner (PO) name and email

Ryan Powers / ryan.powers3@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKcyj0q8V7bedqKrO68bxdG8euwmthH8Wy0y6b40wkuq anhplatt@Coforma-D7CN69VQGD-Anh-Platt.local

### E-QIP Transmittal Confirmation

![Screenshot 2024-05-13 at 11 05 42 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144471721/a802774f-3a27-442d-8907-35caa1aed621)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
User found in Atlas - Scrum master - Non-Disability Claims (Pension and Proactive Benefits)

**Comment by patrick-black-oddball** [comment]
Completed
