### ISSUE TITLE
[Spike] Identify how MFS data is used for clinic/facility logic

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#82979]
Recent triages have revealed that LH returns similar clinic/facility data as MFS, but with lower error rates. We currently use MFS because our understanding is that it offers extra details needed for our clinic filtering logic. We'd like to validate these assumptions and understand exactly what MFS might be offering over LH to see if switching to direct LH calls is an option.

Here's a running list of fields used from the MFS calls in vets-api and vets-website, to be filled out more as the spike is worked on.

1. Data used from MFS in vets-api:
- facility timezone
- 
- clinic service_name
- clinic physical_location
- clinic friendly_name (same as service_name)
- 

2. Data used from MFS in vets-website:
- 
-

In order to complete this spike, we'd need research from a frontend and backend developer.

Timebox: 10 hrs

**Comment by jenniemc** [comment]
FE vets-website uses the following data from MFS:

- facility.id
- facility.vistaSite
- facility.name
- facility.timezone
- facility.lat
- facility.long
- facility.website (future enhancement to link to facility website)
- facility.phone.main
- facility.physicalAddress.line
- facility.physicalAddress.city
- facility.physicalAddress.state
- facility.physicalAddress.postalCode

Not sure if the following clinic data comes from MFS but FE does use it:
- clinic.id
- clinic.physicalLocation
- clinic.phoneNumber
- clinic.phoneNumberExtension
- clinic.serviceName or clinic.friendlyName

cc: @cferris32

**Comment by JunTaoLuo** [comment]
@jenniemc updated your comment with some additional details from the BE.

**Comment by JunTaoLuo** [comment]
@cferris32 this is ready for validation.

**Comment by ldelacosta** [comment]
@cferris32 - thinking we can update our technical documentation with the information here.

**Comment by ldelacosta** [comment]
+ @simiadebowale for awareness. 

Team will be updating our documentation. No additional analysis is needed. Closing out the ticket.
