### ISSUE TITLE
Remove any reference of va_online_scheduling_GA4_migration feature toggle

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#82973]
## Description
Since the analytic team will be implementing the GA4 migration, we no longer need to reference the feature toggle `va_online_scheduling_GA4_migration` in the our codebase. 

---

## Acceptance Criteria

- [ ]  Remove any references of the feature toggle `va_online_scheduling_GA4_migration`
- [ ]  Delete the feature toggle `va_online_scheduling_GA4_migration` in staging and production
- [ ]  Changes have been updated in vets-website and vets-api
- [ ]  [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JunTaoLuo** [comment]
Code for the feature flag removal has been merged for both vets-website and vets-api and both are deployed to production. The feature flags have also been removed from dev/sandbox/staging environments. Removal in the production environment is pending in https://github.com/department-of-veterans-affairs/va.gov-team/issues/84111
