### ISSUE TITLE
Figma access request 

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#82976]
### Name

Lisa Capaccioli

### Email

lisa.capaccioli@coforma.io

### Role

Digital Product Manager

### Team

DSVA Benefits-Disability

### Product Manager (PM) name

Emily Theis

### Additional Notes

viewer-restricted access only

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to lisa.capaccioli@coforma.io.
