### ISSUE TITLE
10-7959f-1 add key for home address (for pre-fill)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82972]
10-7959f-1 url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/home-address

**Issue**: when user is logged in and gets to the home address screen, home address is not pre-filled from profile
**Expected result**: home address should also pull from user profile, in the same way that user's mailing address is pulled from their profile
**Actual result**: user needs to add it manually even though the info is in their profile

Related to this [front end](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/81646) ticket

**Comment by balexandr** [comment]
@reiting @marywang2 This was just merged into master https://github.com/department-of-veterans-affairs/vets-api/pull/16725

**Comment by balexandr** [comment]
@marywang2 This has been updated and according to FE it's working

**Comment by marywang2** [comment]
@balexandr I get the city now! But not seeing the rest.
