### ISSUE TITLE
SPIKE | Duplicate Burial Claim

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#82981]
## Issue Description
_On 5/9 at 17:03 and 17:16 two burial claims with the same info were submitted on VA.gov, but only one generated an EP. Suspicion is that the user received an error message prompting them to re-submit the form._

<img width="818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72282e4ee02d8379055d0cef04b3b1c72af4cabd/image.png" alt="image.png" />

---
## Acceptance Criteria
- [ ] Determine why two claims were submitted

**Comment by micahaspyr** [comment]
I checked to see if this type of behavior has occurred prior and I see no instances of this happening anywhere else.  My guess is that this was just submitted twice.  This seems like a fluke but if we see this happen again we'll have to dig deeper and likely need to bring in frontend to assist
