### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by MensurAhemed** [department-of-veterans-affairs/va.gov-team#82983]
### Name

Mensur Ahemed

### Email

mensur.ahemed@va.gov

### Role

Business Analyst

### Team

SCLA/ PLMO working on GCLWAS WEB

### Product Manager (PM) name

Gregory Johnson

### Additional Notes

Hi, I am a Business Analyst assigned to work on GCLAWS Web supporting Form 21A applications. I need a view only access to the Figma designs in order to create Mockups for my user stories.

Thanks.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to mensur.ahemed@va.gov.
