### ISSUE TITLE
Content review: Yellow Ribbon modal content

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#8298]
This content will be displayed when the user clicks one of the following links in the Comparison Tool.  
a. "Learn more" next to the question "Will you be a Yellow Ribbon recipient?" in the "Estimate your benefits" section

[https://app.zenhub.com/files/133843125/77c0c3b8-9938-450a-8253-0d6f33356ced/download](https://app.zenhub.com/files/133843125/77c0c3b8-9938-450a-8253-0d6f33356ced/download)

**Comment by peggygannon** [comment]
@dneel-bah Please see below my content review and recommendations for the Yellow Ribbon modal. Let me know if you have any questions about my feedback! 

[https://app.zenhub.com/files/133843125/564abfaf-7c0c-4921-9f11-7ac45ada3df6/download](https://app.zenhub.com/files/133843125/564abfaf-7c0c-4921-9f11-7ac45ada3df6/download)

**Comment by amyknox** [comment]
Hi @peggygannon - thanks for the updates to this content.  Quick suggestion for the link text at the end of para2: 

> To learn more about the Yellow Ribbon program, please [download our fact sheet (PDF)].

Link still directs to https://benefits.va.gov/BENEFITS/factsheets/education/Post-911_Yellow_Ribbon.pdf. Including the verb gives a clearer CTA and the expanded link length gives users a larger target.

**Comment by peggygannon** [comment]
Hi, @amyknox Yes, thank you! Great suggestion.
