### ISSUE TITLE
Document findings of custom event questions from Analytic Team for GA4 migration

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#82988]
## Description
The GA4 migration will be implemented by the Analytic Team. They had some questions concerning certain custom events and needed clarification. (1) What is the event name that triggers it? (2) What is the variable name? 

Document finding to the above questions for the following: 
 - Number of Days from Preference
 - Preferred Combination
 - Returned Number of Items
 - Upcoming Number of Cards
 - User

(3) Do we record reason for appointment booking notes? 
We record the reason for appointment which comes from the radio selection: routine-follow-up, new-issue, medication-concern and other. We need confirmation that the booking notes are not recorded in google analytics.

---

## Acceptance Criteria

- [ ] Document the findings

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by jenniemc** [comment]
@JRRoof @ldelacosta  Below is a summary that can also be found in the excel sheet under "Custom Metric Definition" which contains detailed and expanded information. Let me know if you have questions.
[GA4Questions.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15440757/GA4Questions.xlsx)
___
### Custom Metric: **vaos-number-of-days-from-preference**
Track the number of days between the current date and the requested appt dates. There should alway be three values since there are 3 max selection dates.  If the same number shows up twice that means the user has selected the AM and PM for the same day. If user does not select optional second or third date, it will be replaced with ‘null’ as a placeholder. This was implemented to track PID- Patient Indicated Date. 

### Custom Metric: **health-ReasonForAppointment**
Track the radio selection of reason for appointment. CC flow does not ask reason for appointment which explains why it shows “undefined”.  The values are: 'routine-follow-up’, 'new-issue’, 'medication-concern’, 'other’.
NOTE:  It does not record booking notes. 

### Custom Metric: **vaos-preferred-combination**
Tracks the best time to contact for CC requests. With the Acheron service, we [no longer offer the best time to contact on VA requests.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47728) 

### Custom Metric: **facility-id**
Tracks the facility id upon successful covid19 schedule submission

### Custom Metric: **vaos-number-of-items-retrieved**
Tracks number of items returns based on item-type. Item-types are listed below: 

1. item-type **upcoming**, it tracks all booked appointments regardless if it occurred in the past.  
``` diff 
- SUGGESTION: change the logic to display all valid future booked appointments. 
```

> {
>     "event": "vaos-number-of-items-retrieved",
>     "vaos-item-type": "upcoming",
>     "vaos-number-of-items": 9
> }

2. Within Upcoming appointments it is further broken down into various video item-types: '**video_home',‘video_atlas', 'video_va_facility', 'video_gfe',  'video_store_forward'** (No other appt types such as phone or in-person are broken down).

> {
>     "event": "vaos-number-of-items-retrieved",
>     "vaos-item-type": “video_home”, 
>     "vaos-number-of-items": 2
> }

3. item-type **covid19_available_facilities**, based on where the user is registered, this records the number of facilities (parent and child facilities) the user can access once the user is in the covid19 scheduling flow. However, while there may be ten facilities available for use, it does not filter whether the facilities are configured to support the covid19 type of care. 
``` diff 
- SUGGESTION: change the logic to display “covid19_supported_facilities”. 
```

> {
>     "event": "vaos-number-of-items-retrieved",
>     "vaos-item-type": "covid19_available_facilities",
>     "vaos-number-of-items": 10
> }

4. item-type **covid_slots**, it tracks the number of available time slots for the selected facility once user is in the covid scheduling flow

> {
>     "event": "vaos-number-of-items-retrieved",
>     "vaos-item-type": "covid_slots",
>     "vaos-number-of-items": 1
> }

5. item type **available_facilities**, based on where the user is registered, this records the number of facilities (parent and child facilities) the user can access. While there may be ten facilities available for use, it does not filter whether the facilities are configured to support the type of care selected. 
``` diff 
- SUGGESTION: change the logic to display “supported_facilities”. 
```

> {
>     "event": "vaos-number-of-items-retrieved",
>     "vaos-item-type": "available_facilities",
>     "vaos-number-of-items": 10
> }
___
### Custom metric: Upcoming Number of Cards
Cannot find anywhere in the codebase

### Custom metric: VAOS User
Cannot find anywhere in the codebase

### Event name: vaos-eligibility-direct-supported-failed
Cannot find anywhere in the codebase

**Comment by ldelacosta** [comment]
Closing out the ticket. @JRRoof and I will review the details at our next meeting.
