### ISSUE TITLE
10-10d url updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82997]
Update 10-10d urls in **bold** only:

- "signer" to "signer-type"
- "file" --> "upload"
- "information" --> "info"

base url change: 
- URL: va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/
- Breadcrumb: Va.gov home > Family and caregiver benefits > Health and disability benefits for family and caregivers > CHAMPVA benefits > [1010d form H1]
- [IA GH page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/champva-online-form.md) w/breadcrumb/url guidance

Related to this [original](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/78843) ticket

sub urls:
Section 1:
/champva/apply-form-10-10d/introduction
**/champva/apply-form-10-10d/signer** -- change 'signer' to 'signer-type' 
**/champva/apply-form-10-10d/signer-information** -- change 'information' to 'info'
/champva/apply-form-10-10d/signer-mailing address
**/champva/apply-form-10-10d/signer-contact-information** -- change 'information' to 'info'
/champva/apply-form-10-10d/signer-relationship

Section 2:
**/champva/apply-form-10-10d/sponsor-information** -- change 'information' to 'info'
**/champva/apply-form-10-10d/sponsor-identification-information** -- change 'information' to 'info'
/champva/apply-form-10-10d/sponsor-status
/champva/apply-form-10-10d/sponsor-status-date
/champva/apply-form-10-10d/sponsor-mailing-address
**/champva/apply-form-10-10d/sponsor-contact-information** -- change 'information' to 'info'

Section 3:
**/champva/apply-form-10-10d/applicant-information** -- change 'information' to 'info'
**/champva/apply-form-10-10d/applicant-identification-information** -- change 'information' to 'info'
/champva/apply-form-10-10d/applicant-mailing-address
**/champva/apply-form-10-10d/applicant-contact-information**  -- change 'information' to 'info'
/champva/apply-form-10-10d/applicant-relationship
/champva/apply-form-10-10d/applicant-marriage
/champva/apply-form-10-10d/applicant-marriage-date
**/champva/apply-form-10-10d/applicant-marriage-file** -- change "file" to "upload"

remarriage:
/champva/apply-form-10-10d/applicant-remarriage
/champva/apply-form-10-10d/applicant-remarriage-date
**/champva/apply-form-10-10d/applicant-remarriage-file** -- change "file" to "upload"
/champva/apply-form-10-10d/applicant-remarriage-separation-date
**/champva/apply-form-10-10d/applicant-remarriage-separation-file** -- change "file" to "upload"

child:
/champva/apply-form-10-10d/applicant-relationship-child
**/champva/apply-form-10-10d/applicant-relationship-child-file** -- change "file" to "upload"
/champva/apply-form-10-10d/applicant-dependent-status
**/champva/apply-form-10-10d/applicant-dependent-file** -- change "file" to "upload"

Medicare
/champva/apply-form-10-10d/applicant-medicare
**/champva/apply-form-10-10d/applicant-medicare-file** -- change "file" to "upload"
/champva/apply-form-10-10d/applicant-other-insurance-status
**/champva/apply-form-10-10d/applicant-other-insurance-file** -- change "file" to "upload"

# List of URLs with the changes above applied:
sub urls:
Section 1:
/champva/apply-form-10-10d/introduction
/champva/apply-form-10-10d/signer-type
/champva/apply-form-10-10d/signer-info
/champva/apply-form-10-10d/signer-mailing-address
/champva/apply-form-10-10d/signer-contact-info
/champva/apply-form-10-10d/signer-relationship

Section 2:
/champva/apply-form-10-10d/sponsor-info
/champva/apply-form-10-10d/sponsor-identification-info
/champva/apply-form-10-10d/sponsor-status
/champva/apply-form-10-10d/sponsor-status-date
/champva/apply-form-10-10d/sponsor-mailing-address
/champva/apply-form-10-10d/sponsor-contact-info

Section 3:
/champva/apply-form-10-10d/applicant-info
/champva/apply-form-10-10d/applicant-identification-info
/champva/apply-form-10-10d/applicant-mailing-address
/champva/apply-form-10-10d/applicant-contact-info
/champva/apply-form-10-10d/applicant-relationship
/champva/apply-form-10-10d/applicant-marriage
/champva/apply-form-10-10d/applicant-marriage-date
/champva/apply-form-10-10d/applicant-marriage-upload

remarriage:
/champva/apply-form-10-10d/applicant-remarriage
/champva/apply-form-10-10d/applicant-remarriage-date
/champva/apply-form-10-10d/applicant-remarriage-upload
/champva/apply-form-10-10d/applicant-remarriage-separation-date
/champva/apply-form-10-10d/applicant-remarriage-separation-upload

child:
/champva/apply-form-10-10d/applicant-relationship-child
/champva/apply-form-10-10d/applicant-relationship-child-upload
/champva/apply-form-10-10d/applicant-dependent-status
/champva/apply-form-10-10d/applicant-dependent-upload

Medicare:
/champva/apply-form-10-10d/applicant-medicare
/champva/apply-form-10-10d/applicant-medicare-upload
/champva/apply-form-10-10d/applicant-other-insurance-status
/champva/apply-form-10-10d/applicant-other-insurance-upload

**Comment by marywang2** [comment]
Hi @kristinoletmuskat! This is the 10-10d url update ticket for dev - wanted to make sure you were good with these changes! Thanks!

**Comment by kristinoletmuskat** [comment]
Hey hey just noting that the breadcrumb is: Va.gov home > Family and caregiver benefits > Health and disability benefits for family and caregivers > CHAMPVA benefits > [1010d form H1]

**Comment by baltes** [comment]
Hi @kristinoletmuskat , are any other changes in the works or should we go ahead and make the changes as shown above?

**Comment by kristinoletmuskat** [comment]
@baltes as of now, no changes! And we're planning to launch the new hub on Tuesday 6/25, so unlikely any last-minute change to the URLs come through. We could end up pushing the launch pending a left nav thing, but I don't think that should impact you all.

**Comment by baltes** [comment]
Thanks @kristinoletmuskat !

@michaelclement , moving this to Ready but let me know if this needs more info.

**Comment by michaelclement** [comment]
Done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30476) with two exceptions:
- sponsor-status-upload: does not exist because we don't collect any files in the sponsor section
- applicant-dependent-status: which page in the form does this URL belong to? Currently we don't have this URL in place

**Comment by michaelclement** [comment]
[PR Waiting on](https://github.com/department-of-veterans-affairs/vets-website/pull/30476):
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes @marywang2 This was merged to staging and should be ready for review now.

**Comment by marywang2** [comment]
@michaelclement - I'm not seeing the base url change on staging yet.

**Comment by michaelclement** [comment]
@marywang2  My mistake, I didn't remove health-care. That's been done in these two new PRs (in [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/30538) and [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/2152) repos.

Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
Breadcrumb is also updated in the vets-website PR:

<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e9dab168c9eff281890ae32925ec62a27304a9a/Screenshot%202024-06-26%20at%2008.29.33.png" alt="Screenshot 2024-06-26 at 08.29.33.png" />

**Comment by michaelclement** [comment]
Still waiting on platform to approve the [base url change](https://github.com/department-of-veterans-affairs/content-build/pull/2152) PR.

**Comment by michaelclement** [comment]
@marywang2 Everything has finally been merged. Should be visible on staging shortly. Thanks!

**Comment by marywang2** [comment]
@baltes I was about to close this one but leaving for your review as well.
