### ISSUE TITLE
Sign-in / authenticated /unauthenticated documentation on design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#83]
We'd love a suggestion on how this section should appear in the left nav/browser tab/h1. 

Here are some points. These bullet points are not in any particular order.

This documentation will be its own section, not specific to forms. It relates to differences in experience when a user is signed vs not signed in.
- Blue button when not signed in?
- Green button to launch tool?
- Continue unauthenticated, why discouraged/downplayed?
        - Notes
- Site header
- Verbiage to use: "sign in" vs "log in" vs "login" 
- What change in the experience when logged in?

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by smoonpeyes** [comment]
**_draft_** -- this needs more work!

# Dynamic call to action
A call to action (CTA) appears when an action is required or recommended before a user starts a process (like applying for a VA benefit.)  Content on the page, including the CTA, may change based on the authentication status of the user:
* Signed out
* Signed in
* Identity verified
* Identity not verified

## Dynamic CTA Components

### Authentication prompt
Use the [Authentication prompt]( https://design.va.gov/components/alertboxes#sign-in-or-tool-prompt)  when:
* The user needs to sign in or verify their identity before starting a process
* The CTA includes important supplemental information

To view a live example of the Authentication prompt, sign out of VA.gov and visit [VA Prescription Refill and Tracking]( https://www.va.gov/health-care/refill-track-prescriptions/). 

NOTE: On VA.gov, there are instances of Sign In/Create Account CTAs that use the informational alert component. I think we should consistently use the Sign in or tool prompt component in these cases. I’m not sure why they are different.

### Primary button
If the user is signed in and requires no further authentication, use a [green primary button]( https://design.va.gov/components/buttons#primary-buttons) as the CTA.

To see a live example, sign in to VA.gov and visit the [Apply for health care benefits]( https://www.va.gov/health-care/apply/application/introduction) page.

**Comment by jaredcunha-usds** [comment]
@smoonpeyes Thanks!

Yeah, the left navigation will have the anchor links. 
<img width="357" alt="Screen Shot 2019-05-24 at 2 02 11 PM" src="https://user-images.githubusercontent.com/25435289/58347850-efe60200-7e2c-11e9-9312-1f5f72296614.png">

Here are some of my thoughts:
- Assume signed out is the default state, so as we think about the documentation, the _changes_ are what happens after one signs in.
- For the header, I'm thinking maybe we should only describe the things that are actually changing after one signs. This will reduce the documentation overall, but I think more importantly, reduce the need to update this text with every change that happens to the header. This way, we can also put the two screenshots next to each other, and then describe it as something along the lines of "When the user signs in, the sign in link displays the users first name. My VA and My Health are also shown as top navigation elements).

The CTA writeup is great!!!

**Comment by smoonpeyes** [comment]
@jaredcunha-usds Thank you! I agree with your points about documenting the site header changes after signing in. I'll make those updates.

**Comment by jaredcunha-usds** [comment]
Cool. Ping me when you get that updated. I can also merge in your work any time as a draft if you want to see it on dev-design.va.gov per the group DM I sent this morning.

**Comment by jaredcunha-usds** [comment]
Draft page link: https://dev-design.va.gov/patterns/signed-out-signed-in

**Comment by caw310** [comment]
This is over 3 yrs old. There is documentation on sign in and sign out on design.va.gov.
