### ISSUE TITLE
[COGNITION]: Education STEM Update - Step 6 has the same page label twice in Education Benefit chapter

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#830]
## Issue

Step 6 `Education Benefit` chapter has the same heading repeated three times. This could be improved for all users, and especially screen reader users, by changing the titles to be descriptive to their respective pages. Screenshot attached.

Tagging @peggygannon for content guidance.

## Point of Contact

* Trevor
* Peggy

## Acceptance Criteria

* As a screen reader user, I would like to hear contextual page headings and contextual Edit button labels when I've opened the Education Benefit chapter.

## Environment
* MacOS
* Chrome latest

## Possible Fixes (optional)
Update the page headings to be more descriptive to their content.

## WCAG or Vendor Guidance (optional)
* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

## Screenshots or Trace Logs

![Screen Shot 2019-08-06 at 10 03 06 AM](https://user-images.githubusercontent.com/934879/62552380-28458b80-b833-11e9-9153-51b186ad13dd.png)

**Comment by amyknox** [comment]
@peggygannon we propose the following page titles

*Education benefit selection* for the page where the user selects which benefit they're using or has used most recently

and

*The Rogers STEM Scholarship* for the page which asks whether the user is applying for the scholarship and, if yes, displays conditional questions about their course of study

**Comment by peggygannon** [comment]
@amyknox Hi, Amy. the proposed updated title look good. 

Will these titles also appear at the top of the page itself or just on the summary screen (shown above)? I want to be sure changing the pages titles doesn't interrupt with the overall form design and chapter flow.  We should also look at the pages to see how it flows.

**Comment by zurbergram** [comment]
<img width="734" alt="Screen Shot 2019-08-08 at 1 43 36 PM" src="https://user-images.githubusercontent.com/1094999/62725190-ab591400-b9e2-11e9-97b8-3fe25ac9cf32.png">

<img width="661" alt="Screen Shot 2019-08-08 at 1 43 52 PM" src="https://user-images.githubusercontent.com/1094999/62725189-ab591400-b9e2-11e9-95df-c99de48cd942.png">

<img width="648" alt="Screen Shot 2019-08-08 at 1 44 21 PM" src="https://user-images.githubusercontent.com/1094999/62725188-ab591400-b9e2-11e9-91f2-61f7a2e31c28.png">

**Comment by zurbergram** [comment]
@peggygannon I have attached screenshots of what each page and review page would look like with proposed title changes

**Comment by peggygannon** [comment]
@zurbergram thank you. looks good.

**Comment by 1Copenut** [comment]
👍 Thanks team!

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/10550

**Comment by delli-gatti-michael** [comment]
QA Testing passes

<img width="671" alt="Screen Shot 2019-08-08 at 2 37 54 PM" src="https://user-images.githubusercontent.com/45575003/62728888-d9425680-b9ea-11e9-91f2-9a53be39777b.png">

**Comment by zurbergram** [comment]
@1Copenut changes are live on staging

**Comment by 1Copenut** [comment]
@zurbergram I saw that while testing out the other item. Thanks for capturing these together. Moving this to close.
