### ISSUE TITLE
2023 IA Audit - Final Drupal Changes

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#83005]
### Description
This ticket is to compile and track any outstanding tasks from the 2023 IA audit.

Task | Benefit Hub | Status
---- | ---- | ----
Update link label for [Mental health services](https://www.va.gov/health-care/health-needs-conditions/mental-health) to match H1 | Health care | Done, updated in IA spreadsheet
Fix breadcrumb level for [additional forms page](https://www.va.gov/disability/how-to-file-claim/additional-forms/) | Disability | Deprioritized, [PW ticket here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18204)
Update the H1 for [2024 VA protected disability and death pension rates](https://www.va.gov/pension/protected-pension-rates/) | Pension | Done, updated in IA spreadsheet
Update H1 for [VA Survivors Pension](https://www.va.gov/pension/survivors-pension/) | Pension | Megan connecting with Content team

**Comment by kristinoletmuskat** [comment]
Hey @megzehn wanted to check on these while Jenny is out -- do we have any next steps yet, or still waiting for feedback from Danielle/stakeholders?

**Comment by kristinoletmuskat** [comment]
@megzehn for number 3 -- 2024 VA protected disability and death pension rates, yes you are right about the change. We want it to be 'Current protected disability and death pension rates'. 

And for number 4 - VA Survivors Pension, we are authorized by Beth to remove 'VA' from the H1 and left nav (we already did the left nav). I answered your comment in the pension spreadsheet that I thought we could remove 'VA' in most places on the page as well, but you can def check that with beth. 

I am about to email the stakeholders about these 2 H1 changes to pension, and then feel free to make the changes!

**Comment by kristinoletmuskat** [comment]
FYI just sent the stakeholder email so we are ready to make these changes

**Comment by megzehn** [comment]
Latest update

----

**Task:** Update link label for Mental health services to match H1
**Status:** Done

**Task:** Fix breadcrumb level for additional forms page
**Status:** In progress for PW - [commented in ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18204)


**Task:** Update the H1 for 2024 VA protected disability and death pension rates
**Status:** Done


**Task:** Update H1 for VA Survivors Pension
**Status:** Chatted with Beth about this one and she wants to check some notes first, but we should hopefully update this one soon.

**Comment by kristinoletmuskat** [comment]
@megzehn just checking in on that final Pension item -- any updates on decision about removing 'VA'?

**Comment by kristinoletmuskat** [comment]
@megzehn just checking in on that final Pension item -- any updates on decision about removing 'VA'?

**Comment by megzehn** [comment]
Hi @kristinoletmuskat! Sorry for letting this one sit so long. I chatted with Beth and we agreed to remove VA throughout on Survivors Pension. 

And I know we're putting the breadcrumb change on hold for the Additional forms page, so I think we can go ahead and close this ticket out. 

Let me know if there's anything I'm missing!

**Comment by kristinoletmuskat** [comment]
Awesome! Thank you. I will close it out!
