### ISSUE TITLE
Appointment Details Page - Null state

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#83010]
## Description
We need to implement the logic if there is no data presented in the appointment response for the Appointment Details page.  

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

- [ ] Given when the services return a null value for type of care for all appointment types
When the user is on the Appointment Details page
Then the label `What` will not be displayed 
And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573&t=FCm7ZccXpWJX1nu8-0)

- [ ] Given when the services return a null value for the facility (but receive the facility ID) for all appointment types
When the user is on the Appointment Details page
Then the frontend will display the facility name
And a link to facility locator 
And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573&t=FCm7ZccXpWJX1nu8-0)

- [ ] Given when the services return a null value for the facility (no facility ID) for all appointment types
When the user is on the Appointment Details page
Then the frontend will display the text `Facility details not available`
And a link to the facility locator 
And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573&t=FCm7ZccXpWJX1nu8-0)

- [ ] ~~Given when the services return a null value for the clinic phone number for all appointment types
When the user is on the Appointment Details page
Then the frontend will display the facility phone number 
And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573&t=FCm7ZccXpWJX1nu8-0)~~

- [ ] ~~Given when the services return a null values for the clinic phone number and facility phone number for all appointment types
When the user is on the Appointment Details page
Then the frontend will display the VA main number 
And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573&t=FCm7ZccXpWJX1nu8-0)~~

_**Note:** The clinic phone number functionality will be addressed in this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80375_

### Design Assets
[Figma File](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@Cieramaddox @outerpress to confirm VA Main Phone number and add to ticket

**Comment by Bren22va** [comment]
Size changed b/c this was more work than anticipated.

**Comment by ldelacosta** [comment]
No issues found at the moment. Will continue to test in staging but will close out the ticket today. cc: @Bren22va @JRRoof @outerpress
