### ISSUE TITLE
Edit - Sketch Audit - Accessibility on Va.gov

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#83024]
- [x] Edit [Accessibility on Va.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/3124265207/Accessibility+on+VA.gov) based on Jaime's instructions.

## Acceptance Criteria

- [x] [Accessibility on Va.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/3124265207/Accessibility+on+VA.gov) has been edited and deployed.

**Comment by jknipes** [comment]
work is complete, AC met, moving to _done_
