### ISSUE TITLE
CTO Health Questionnaires TES Tiger Team: Proposed changes to screener

### ISSUE THREAD

**Issue by ninaranusavice** [department-of-veterans-affairs/va.gov-team#83031]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

## About your team

- **Team name**: `CTO Health Questionnaires`
- **OCTO product owner:** `Kristen McConnell`
- **Product name:** `Clinical Reminders: Health Questionnaires Pilot`
- **Product manager:**  `Mark Junda`
- **Slack channel:** [va-cto-health-questionnaires](https://dsva.slack.com/archives/C05AS3KQ132)
- **Dedicated content writer on your team (if you have one):** `N/A`
- **Dedicated a11y specialist on your team (if you have one):** `N/A'
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes
- [ ] No
- [ ] I’m not sure

### Where are you at in your timeline?
We just completed phase 1b of the pilot and are heading into phase. We would a mock-up of the proposed content changes on May 17, 2024.

TES Tiger Team: Proposed changes to screener. We would like help on the following:

**Topic 3: How to explain “What is a registry?”**
- Add definitions to each answer choice on the " Do you have follow-up Questions" screen.
- Ensure that all definitions are displayed on the same screen under the screener title.
- add explanation paragraph about each type of question above selection. -

**For review:** proposed description from plain language content group
We maintain a series of health registries to track and monitor the health of certain groups of Veterans. Our registries focus on Veterans who may have health problems related to exposure to certain toxins or environmental hazards during service. For example, we have registries for Veterans exposed to burn pits, Agent Orange, and radiation. The registry data helps us understand and respond to these health problems more effectively.
A free registry health exam can help alert you to health problems you should be monitored for. When you join a registry, you also help your fellow Veterans. We use the information you give us to better understand and serve all Veterans affected by toxic exposures or hazards.
Note: A registry exam isn’t a VA claim exam. You don't need to be enrolled in VA health care to get a registry exam. And you don’t need to have this exam to get other VA benefits. To get disability benefits, you’ll need to file a claim.
 
**OR**

A health registry is a way to collect data about health problems related to exposure to certain toxins or environmental hazards during military service. For example, we have registries for Veterans exposed to burn pits, Agent Orange, and radiation. We use this data to better understand and respond to these health problems more effectively.
A free registry health exam can help alert you to health problems you should be monitored for. When you join a registry, you also give us information that can help all Veterans.
Note: A registry exam isn’t a VA claim exam. You don't need to be enrolled in VA health care to get a registry exam. And you don’t need to have this exam to get other VA benefits. To get disability benefits, you’ll need to file a claim.

**Topic 4: How to explain what happens when selecting “Benefits/Claims Questions”**
- VHA to draft explanation of what selecting this option means to Veterans.
- The toxic exposure screening does not play a role in determining disability compensation. Your service-connection will not be reviewed or re-evaluated simply for completing the toxic exposure screening. Let us know if you have questions about filing a claim with VBA or if you are eligible for additional benefits.

**Topic 5: How to explain what happens when selecting “VA Health Care Enrollment and Eligibility Questions”.**
- VHA to draft explanation of what selecting this option means to Veterans.
- [Veterans with questions about eligibility for services may be connected with their local Heath Care Eligibility Center (HEC) or VSO office](https://github.com/department-of-veterans-affairs/va.gov-team/assets/108754235/200d362d-16c8-43d9-905f-63ad32d4888e)

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [X]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [X] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `N/A`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [TES Tiger Team: Proposed changes to screener](https://dvagov.sharepoint.com/:w:/r/sites/OCTOOCCSelf-ScreeningQuestionnairePilot/Shared%20Documents/General/Pilot%20documents%20(Eval%20plan,%20Project%20Plan,%20etc)/TES%20Tiger%20Team%20Proposed%20changes%20to%20screener.docx?d=wbfedcf601c6f456eac53ebe10a872349&csf=1&web=1&e=pzelE4) 
- [Emails Regarding Benefits vs Enrollment Eligibility](https://dvagov-my.sharepoint.com/:w:/r/personal/nina_anusavice_va_gov/Documents/Emails%20Regarding%20Benefits%20vs%20Enrollment%20Eligibility.docx?d=wabf37e4c6f4140349abd9d64b0fc6761&csf=1&web=1&e=kLL59T)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by laurwill** [comment]
Hi @ninaranusavice and @kristenmcconnell , here's a Sharepoint doc with suggested edits to the health registry blurb. The doc also has suggestions for the other screens in the flow, but I understand the scope for this update is smaller. 

For the info about what will happen if they select each option, I think we can skip those explanations for everything but the health registry option if we rewrite the answer options to be more descriptive. See what you think!

**Comment by kristenmcconnell** [comment]
Thank you. I'll review and add this into our prototype, then post a link here when it is ready.

**Comment by ninaranusavice** [comment]
Edited [Figma Link](https://www.figma.com/design/t1HWiNUBB0jIKAnuch6bDZ/Toxic-Exposure-Clinical-Reminder-%7C-Check-in?node-id=2-85&t=toYkZdXshRSVqBFA-0)

**Comment by laurwill** [comment]
I'm closing this ticket since we completed this content work — but curious @kristenmcconnell @ninaranusavice if these changes made it into the live version of the screener?

**Comment by ninaranusavice** [comment]
Hi Laura,

From my recollection, most did get implemented with a few minor changes from the TES Tiger team; would you like me to double check which ones did?

Nina

From: laurwill ***@***.***>
Sent: Tuesday, August 27, 2024 2:50 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Anusavice, Nina R. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] CTO Health Questionnaires TES Tiger Team: Proposed changes to screener (Issue #83031)


I'm closing this ticket since we completed this content work - but curious @kristenmcconnell<https://github.com/kristenmcconnell> @ninaranusavice<https://github.com/ninaranusavice> if these changes made it into the live version of the screener?

-

**Comment by laurwill** [comment]
Yeah if you have a link to the final version I'd love to see it just for my own curiosity! This was such a fun fast project, I'm psyched they implemented most of it.
