### ISSUE TITLE
[Security - Controls Effort] FwdProxy Monitoring Document

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#83048]
## Description
To meet and mature in the ID.AM-3 security controls, Infrastructure Services would like to add information on how we monitor FwdProxy connection to existing documentation.

## Resources 
- [FwdProxy Info](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594279/Forward+Proxy) <-- Evaluate adding monitoring section here

## Acceptance Criteria
Adding necessary information to existing documentation on how and why we monitor external service connection in the FwdProxy:
- [ ] Various monitoring methods
- [ ] Incident alerts/responses 
- [ ] Ensure appropriate information and documentation is attached to critical incident alerts.

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by stoiven** [comment]
https://vfs.atlassian.net/wiki/spaces/ECP/pages/3637706757/Explainer+-+Monitoring+Observability+with+Forward+Proxy

added in an `explainer` to go more in depth w/ monitoring

**Comment by hgbarreto** [comment]
REVIEWED

Added new story to continue maturing this document.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97382
