### ISSUE TITLE
Ensure all user sessions have a user email address present

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#8305]
(Issue discovered while implemeting #5417)

### Background
When a user initiates sign-in from VA.gov (either in previous implementation or in pending SSOe implementation), ID.me brokers the authentication for all credential types, and we are guaranteed to have an email address present for every user session. Not only that, but it is guaranteed to be a verified email address, since ID.me performs email address verification. For the credential providers that don't provide an email address, ID.me prompts the user to link their credential  to an ID.me wallet. 

However, when a user signs in with MHV or DSLogon credentials on another site, and then navigates to VA.gov (aka "inbound SSO"), their SSOe session will very likely not have an email address present. This means various features of VA.gov that have been able to safely assume that an email address would be available may break. The full impact of this is hard to assess, but the `user.email` attribute is used in several places in vets-api and populated into the user's profile for use by the frontend. 

Further discussion in this thread: https://dsva.slack.com/archives/CBU0KDSB1/p1587487030269700

### Other sources of email address info
- The "VA Profile" service that we use for address info also has a contact info service that can provide user email addresses. However, it's not guaranteed to be populated for every user.
- There is a `pciu_email` attribute in the user model, populated from some VBA service, that is used in conjunction with some benefits applications. It's not guaranteed to be populated for every user.

### How might we solve this?
1. Relax the assumption that email addresses are present. VSP platform owners are reluctant to do this as described in the above thread. 

2. We can check if the VA profile email address is present, and use that when one is not present in the user's session. But this will only work for some but not all users.

3. We can prompt users to supply an email address if one is not present. (This would probably be in combination with (2), so if we can't get an email from SSOe session OR VA profile). But then we need to store that email address to use on future inbound SSO sessions. We should not store it ourselves; VA profile is the logical place to store it via their API. We would need to implement a new user interaction to have them enter an email. Also this email would be unverified.

4. We could force the user to re-authenticate, which would send them through ID.me which would require the user to associate an email address with their credential AND would verify that email address. Upon returning to VA.gov we'd have an email address for the current session. But, we'd still need to store it (again in VA Profile) so that it would be available for future inbound SSO sessions.

**Comment by patrickvinograd** [comment]
A potential risk with writing back to VA Profile, is that we don't know offhand what other places VA profile is writing that email address to, and whether that will have unexpected/undesired consequences for the user. It's not always obvious that the email address the user associates with their ID.me wallet is the one they want used for other VA purposes.

**Comment by patrickvinograd** [comment]
Documenting known places where user.email (aka the email supplied by the identity provdier) is used (irrespective of whether it _should_ be used vs. using the VA Profile email address or PCIU address):

## Backend
- (Gets serialized in the `profile.email` object that is passed to the frontend for possible use there - see Frontend section below)
- Beta registrations controller (obsolete)
- VIC ID Card application attributes - not clear if mandatory or not
- MHV Account Creation API - candidate for removal
- GI Bill Status Controller - only used in a RecordNotFound error message in logs, not presented to user or any other service.
- BGS Dependent Service (Lighthouse) - used as a key, needs further analysis
- EVSS JWT generation - used for authorization headers for all EVSS calls - unclear if required, needs further analysis

## Frontend
None observed

## Areas where another source of email information is used:
### Backend
- FormProfile model used for prefill (uses Vet360 then PCIU in that order of precedence)
- Prescription Refill preferences - uses info from MHV prescription preferences API (may be obsolete)
- Secure Messaging preferences - uses info from MHV secure messaging preferences API (may be obsolete)
- Form526OptInsController - accepts email as input (unknown if prefilled on frontend)
- VIC ID Card announcement subscriptions - email provided as parameter (obsolete)
- Health Care Application - user-supplied in form
- Saved Pension/Burial claim models - user-supplied in form
- **Direct Deposit Confirmation Email** (PPIU Controller) - uses VA Profile emails

**Comment by patrickvinograd** [comment]
Follow-up queries awaiting answer:
- Question out to #evss-prod channel about EVSS JWT token on 4/28
- Question to Charley Stran from Lighthouse about DependentService on 4/28

**Comment by patrickvinograd** [comment]
I confirmed in the VA.gov/VIC staging environment that we can generate an ID card request with an empty email address, and the field is user-editable when they get to the VIC application, so we just need to update `IdCardAttributes` to have `user.email || ''` and that use case is addressed.

**Comment by patrickvinograd** [comment]
Response from EVSS team - ok to omit `email` claim in EVSS JWT if no email present: https://dsva.slack.com/archives/C8R3JS8BU/p1588171935161200

**Comment by patrickvinograd** [comment]
Response from BGS team: 
> I think we are fine either way. The idea of those fields is for you to be able to trace back operations back to the user that originally did the request.

> So the question back to you is, would you be able to identify the user in you system if we supply the information that you put in the ExternalUID and ExternalKey when you did the request? If the answer is yes (like I suspect) I thin we are good.

The combination of ICN and va_eauth_commonname should be good from our end for this purpose, so we don't need to depend on email address here.

**Comment by ericbuckley** [comment]
@patrickvinograd do we need to make a change to the power of attorney form in the claims api?  https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb#L92

**Comment by patrickvinograd** [comment]
Good catch. But if you follow that controller inheritance back, you'll see that it inherits from OpenidApplicationController, i.e. it's protected by the Lighthouse OAuth mechanism instead of by typical VA.gov sign-in.

OAuth is not getting integrated with SSOe, and hence will not have to deal with inbound SSOe, and hence will not have users without an email address. So we're good on that front.

**Comment by patrickvinograd** [comment]
I connected the dots to one additional use of user.email, which is the feature flipper actor thing. So that would mean that we could not enable a feature for a specific user who had SSO'ed in from another site. But I think we can live with that - the usual use case is opening testing to specific people, and we'd just need them to sign in starting at VA.gov.
