### ISSUE TITLE
SOCKS access for [Brandon Cooper] 10-10 Team 

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#83068]
### Your Name

Brandon L Cooper

### Your Email

brandon.cooper@adhocteam.us

### Your GitHub Handle

coope93

### Your Role and Team

Senior Software Engineer - 10-10 Health Apps

### Product Manager (PM) name and email

Heather Justice heather.justic@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman patrick.bateman@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFT1V0vbVHQ4iB8y3aJx9mCEa9GQevO5Ia6mSb9n6bI8 brandon.cooper@brandoncooper-Q23P9PMX07

### E-QIP Transmittal Confirmation

![Screenshot 2024-05-14 at 11 40 51 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16926386/b3bc8917-ec35-4b72-be9b-62df3ea3d2d2)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
Completed - you may need to wait 6-10 minutes for the credential to propogate
