### ISSUE TITLE
Update the Educational and Career Counseling Chapter 36 page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8306]
## Update the Educational and Career Counseling Ch 36 page

`PLACEHOLDER TICKET TO BE GROOMED AND BACKLOGGED WHEN AVAILABLE`

This page: https://www.va.gov/careers-employment/education-and-career-counseling/  

Summary: The program’s line of business name has changed to Personalized Career Planning and Guidance. At this time, no benefit/eligibility information has changed (that can be confirmed). Sometime in September 2020, the application process may change, but that is still TBD. 
 

[ ] H1 remains the same. Got sign off from Dawna Quick in OTED.
[ ] ~Update the body copy references to Chapter 36 to “formerly Chapter 36”~
[ ] Update the body copy to debrand the old program name from “Educational and Career Counseling” and just focus on the benefit itself, de-branded and lc'd: “educational and career counseling.” We'll have limited mentions of the new program name--perhaps just once in the intro paragraph.
[ ] Track this in a GitHub ticket to share with you and the program office. We will backlog this and pull it into a sprint as soon as we can. 
 
**One really important thing we need stakeholder confirmation on:**
•	Currently, the application instruction tells Veterans to use the VA form called “Educational/Vocational Counseling Application (VA Form 28-8832).” 
•	Is this still the correct form to use today? **Confirmed: yes, this is the form, and they aren't changing it's name to match their new program name.**

**Background SEO data via SEMRush:** 

- Currently, “chapter 36” (and variations of) has higher organic search volume and stronger/longer trend value. “Career counseling” and variations also get some search value. Together, phrases with “chapter 36” and “career counseling” have a monthly search value of 170. 
- “Personalized career planning and guidance” has a monthly search value of 10, and relatively new trending value (people haven’t searched using this phrase in the past).  This could indicate that OTED’s marketing efforts may be working. However, it’s still not outranking organic searches for “chapter 36” and “career counseling” phrases – which indicates that people who haven’t been exposed to marketing are still looking for information on Google and other search engines using some variation that includes “chapter 36” or “career counseling.”
- The modern  /education-and-career-counseling page ranks #1 for searches on these terms with high click through rate – which means people searching on those terms feel confident that our page is the information they’re looking for and want – our page matches the intent of their search. 

**Longer-term, if/when application process or benefit information changes, we will:**
Update the application process information, based on new information the program office shares with us. Per call, `possible application process change` is ETA September 2020. [clarified 4/23]

**Comment by jenniferlee-dsva** [comment]
SEMRush research shared with stakeholders per ^

[career-edu-counseling-seo-keywords-results-042220.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4561503/career-edu-counseling-seo-keywords-results-042220.pdf)

**Comment by stephorkandatx** [comment]
Holding on this ticket for now, as we confirm the change requests with the stakeholders. There is a meeting scheduled for next week and I expect to hear more after that.

**Comment by AnneHurley** [comment]
Original request from Sandy Tadeo via word doc 5/22:

Suggested updates to https://www.va.gov/careers-employment/education-and-career-counseling/

Educational and Career Counseling:
Personalized Career Planning and Guidance (38 U.S.C. 3697A,  Chapter 36)
Find out how to apply for the VA Personalized Career Planning and Guidance program, also known as Educational and Vocational Counseling, to get free Veteran Educational and Career Counseling services. You may be eligible if you’re leaving active service soon, if you’ve been discharged within the past year, or if you’re the dependent of a Veteran eligible for education benefits.
Who is eligible for Personalized Career Planning and Guidance?
You may be eligible for these services if one of the following is true. You:
	Will be discharged under conditions other than dishonorable from active duty within 6 months, or
	Separated from active duty under conditions other than dishonorable not more than one year ago, or
	Eligible as a Veteran or Servicemember for educational assistance under a VA educational program, or
	Are a Servicemember, Veteran, or dependent currently eligible for VA education benefits

Learn more about employment benefits for dependents
What benefits will I receive?
	Career Counseling to help you decide which civilian or military jobs you want
	Educational Counseling to help you determine a training program or field of study
	Academic and adjustment counseling to help you address issues or barriers that get in the way of your success 
	Resume support and goal planning to help you achieve your personal goals
________________________________________
How do I get these benefits?
There are 3 ways to apply for PCPG benefits: online at VA.gov, mail in an application using form VA form 28-8832 below OR walk your application into your nearest Regional Office or VetSuccess on Campus Counselor. Follow these steps to apply online now
1.	Sign in to your eBenefits account.
2.	Select Apply.
3.	Click Vocational Rehabilitation and Employment Benefits.
4.	Apply for Education and Career Counseling.
5.	If you're eligible, we’ll invite you to an orientation session at your nearest VA regional office.
Go to eBenefits to apply
You can also apply by mail
Fill out an Educational/Vocational Counseling Application (VA Form 28-8832).
Download VA Form 28-8832 (PDF)
If you qualify, we will  invite you to attend a PCPG appointment.

http://preview-prod.vfs.va.gov/preview?nodeId=720
@RLHecht  Ready for your review, and @DanielleThierryUSDSVA FYSA

**Comment by AnneHurley** [comment]
I edited the page but still have outstanding questions, which I slacked 5/27 to @DanielleThierryUSDSVA:
Hey there, so I took  a pass through the Chapter 36 page. Here: http://preview-prod.vfs.va.gov/preview?nodeId=720
10:35
A couple of questions that I'll outline in an email back to Sandy, and whatever else if you have additional questions:

1. The program is changing name. The copy they sent us had 2 references to "....also known as...[the former name]" I thought that was too confusing - if the name's changing we should use the new name, and say "formerly known as." Do you agree?

2. In the subway map instructions we refer users to a section inside eBenefits with a name that doesn't match either the new name or the former name. It seems confusing to me and I wonder if they'll be changing the name inside eBenefits to the new name at some point... so we don't have 3 names for the program floating out there.

3. There is a link on this page that goes to a whole separate page about benefits that dependents can get, and I think we should ask the stakeholders to update that page too, so they can both go live at the same time.  Here's that page currently: https://www.va.gov/careers-employment/dependent-benefits/#dependents-services

@RLHecht  FYSA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley. 

Agree with your points above. 

Though I have 2 notes/questions on the program name:

- We've always had it as "Education and Career Counseling." Now the "former"/"also called" term appears to be "Educational and Vocational Counseling." Do you think they're saying this "Educational and Vocational Counseling" is an alternate name of the new program? That doesn't seem right, but just wondering since this name doesn't matter the former name.

- I'm actually wondering if we can get away with not saying "formerly" at all by just saying in the intro: "Find out if you're eligible and how to apply for free educational and career counseling through the VA Personalized Career Planning and Guidance program. " Since both the former and the new names of the program are also benefit descriptions, it feels confusing to have both in there.  Thoughts?

And then, per Jen's notes above, we'd recommended changing this page H1 to **Career counseling (VA chapter 36)** _(note: I removed "formerly" from original since it's still Chapter 36)_ and debranding the content. 

I know it's important to the stakeholders to have the name of the new program prominently displayed on the page.

So perhaps we could do this:

# Career counseling (VA chapter 36)

Find out if you're eligible and how to apply for free educational and career counseling services through the VA Personalized Career Planning and Guidance program. 

## Am I eligible for career planning and guidance through this program?

I do wonder if "career counseling" for the H1 may be confusing since you do still actually get both career _and_ educational counseling, per the benefit bullets. I think our main goal is to use the branded program name as little as possible in order to focus on the actual benefit, rather than the brand. SEO matters too, and that's part of why we'd wanted "career counseling," but "chapter 36" is the greater SEO value.

So another option might be:

# Career planning and guidance (VA chapter 36)

Find out if you're eligible and how to apply for free educational and career counseling services through the VA Personalized Career Planning and Guidance program. 

## Am I eligible for career planning and guidance through this program?

Thoughts?

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  - Definitely want to reduce confusion. The top SEO terms all include "Chapter 36" so I'd think we would be fine to streamline the other names of the program. I hope to get answers back from VBA 5/28 and then I'll review to streamline. May need to circle back to them one more time about why they want to mention 2 different names, agree it seems unnecessary.

**Comment by jenniferlee-dsva** [comment]
Both "career counseling" and "chapter 36" are terms we should try to use often for this page. per original SEO data shared with business: 

>Background SEO data via SEMRush:
Currently, “chapter 36” (and variations of) has higher organic search volume and stronger/longer trend value. “Career counseling” and variations also get some search value. Together, phrases with “chapter 36” and “career counseling” have a monthly search value of 170.

I've also updated the original AC @stephorkandatx to prevent confusion in the future. Post-write up of the original AC, business clarified that this program is still actually chapter 36 - it's just the program office name that's changing, not the chapter 36 legal program reference.

**Comment by AnneHurley** [comment]
5/28 - Request for clarification sent to Sandy Tadeo, using Danielle's second suggested H1 and blurb above, and asking him / stakeholders to review all the pages mentioning chapter 36 to see where we may want to add the new name of the program. 
@DanielleThierryUSDSVA @jenniferlee-dsva  @stephorkandatx @RLHecht  FYSA

**Comment by DanielleThierryUSDSVA** [comment]
Yes, agree that we should use "career counseling" as well for SEO value. Just wasn't sure about using it as the H1 because it's just one of the benefits in the list (as is educational counseling).

**Comment by DanielleThierryUSDSVA** [comment]
Adding @bethpottsVADEPO onto this issue.

**Comment by stephorkandatx** [comment]
Next steps - follow up with stakeholders, with the preview page.

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  @stephorkandatx @jenniferlee-dsva FYSA 
Received this email from Terry Brown on 6/18 - changes on URLs are still being approved on their end. I'll check back with them ~ June 26.
From: Brown, Terry D., VBAVACO <Terry.Brown1@va.gov> 
Sent: Thursday, June 18, 2020 4:47 AM
To: Hurley, Anne (Ad Hoc, LLC) <Anne.Hurley@va.gov>; 'Anne Hurley' <ahurley@governmentcio.com>; Tadeo, Sandy A., VBAVACO <Sandy.Tadeo@va.gov>
Cc: 'Allison Ruyak' <allison.ruyak@dynamiciservices.com>; Castillo, Kimberly A. VBAVACO <Kimberly.Castillo1@va.gov>; Kemper, Charlotte, VBAVACO <Charlotte.Kemper@va.gov>; Potts, Beth <Beth.Potts@va.gov>; 'Lois L Collins' <llcollins@mitre.org>; Coleman, Clarence (Craig) VBAVACO <Clarence.Coleman2@va.gov>; VBA Digital Media <VBACO_DigitalMedia@va.gov>; 'ahurley@governmentcio.com' <ahurley@governmentcio.com>; Nicole Carey <nicole.carey@dynamiciservices.com>; O'Shea, Laura, VBAVACO <laura.oshea@va.gov>; Downs, Andrea VBAVACO <andrea.downs@va.gov>
Subject: RE: Following up: Chapter 36 updates - questions

Good morning Anne, 

My apologies, We made updates to the URL’s and submitted to the PDUSB for review.  The PDUSB wanted to see the updates and approve them before we submitted back to you and the VA.Gov team.  They are currently with the PDUSB team.  Once we get them back I will forward.

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  @stephorkandatx  We have a meeting with Sandy on 6/24 to go over these questions/changes. Given the note above saying other stakeholders want to get back to us 6/26 with the other URLs/pages that are affected - we can go ahead and meet with Sandy to check in on this w him. What do you think?

@jenniferlee-dsva  FYSA

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  - the page has all of Danielle's suggested edits in it now as well as the other updates from this week. 
http://preview-prod.vfs.va.gov/preview?nodeId=720

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO just an fyi that i'm removing myself from this issue. of course, feel free to ping me if you need me for anything!

**Comment by bethpottsVADEPO** [comment]
Update: Beth attended last week's larger VBA PCPG meeting and showed the main page. It wasn't the right venue for taking feedback. We need a separate meeting for that. 

Next step: Beth to set up a meeting to go over the main page rather than waiting for the peripheral pages with mentions to come back to us with feedback.

**Comment by MickinSahni** [comment]
Carry over to sprint 25

**Comment by bethpottsVADEPO** [comment]
Update: Confirmed with OTED (Charlotte Kemper) that the name of the PDF form will not change. This means there's nothing for us to update related to the language linking users to the PDF from our page.

**Comment by mnorthuis** [comment]
IA for the PCPG work is here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt36.md

This includes URLs, breadcrumbs entry points and any redirect requirements.  The IA is mostly finalized for this, just need to finalize some top nav questions with @bethpottsVADEPO and @DanielleThierryUSDSVA .

**Comment by bethpottsVADEPO** [comment]
Update: I received stakeholder edits to surrounding pages that have language that needs updating to account for the new name. Opening a new ticket for implementation by GCIO content team member.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Implementation of edits to static pages as well as nav work is captured in this ticket: #13842

**Comment by bethpottsVADEPO** [comment]
This work is done. Remaining left nav and top nav work is covered in #13842.
