### ISSUE TITLE
Vets-api terminal access for [Vid Jovanovic]

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#83095]
### Your Name

Vid Jovanovic

### Your GitHub handle (terminal access is managed through GitHub)

@vidjovanovic

### Your dsvagovcloud AWS user name (if applicable)

vid.jovanovic

### Team, Role, and Company of the target individual

Identity, Devops Engineer, Bylight

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

Samara Strauss [samara.strauss@va.gov](mailto:samara.strauss@va.gov)

### COR Name (leave "None" if you listed an AWS user name above)

Laurene "Reney" Cook

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

For EQIP - Refer to [onboarding ticket from last year](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71448)

I need access to production as well as dev/staging/sandbox in order to complete cert rotations, this requires terminal access to check that the certs have been uploaded correctly and I need to be able to re-cycle the pods in order for the certs to take.

I need production access for the same reasons as stated above, since we rotate certs for both lower envs as well as prod.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by AnthonyWFlowers** [comment]
Greetings @vidjovanovic For us to complete this request we need one of the following regarding your eQip status: 

- A screenshot of their Transmittal Notice email or something comparable proving they’ve submitted their eQIP survey
- A screenshot of their Background Investigation Complete email or something comparable proving they’ve received a favorable determination
- A link to another completed request containing this info
- There’s the possibility that the user has worked for the VA for years and no longer has this information. If that’s the case, instruct them to reach out to their VOR, who should be able to dig up proof for them

Unfortunately the link to the previous ticket does not have the screenshot regarding your eQIP. If there is someone on that old ticket that can confirm and or provide a screenshot that would be helpful as situationally I cannot approve that myself without the proper documentation.

**Comment by vidjovanovic** [comment]
> Unfortunately the link to the previous ticket does not have the screenshot regarding your eQIP. If there is someone on that old ticket that can confirm and or provide a screenshot that would be helpful as situationally I cannot approve that myself without the proper documentation.

Hi @AnthonyWFlowers , Here is another [ticket from last year](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55664) where I submitted my EQIP transmittal info. 

While I don't have access to my OPM, Amber Malcolm was able to get me the date last time. Here's a screenshot of her e-mail that she sent me last year:
<img width="879" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/94195657/8266ee58-b179-4ab0-a3e8-9940a8b7a950">

Please let me know if I need anything further.

**Comment by AnthonyWFlowers** [comment]
Greetings @vidjovanovic this should work! Let move this forward! 
User is in Atlas
eQIP attached

**Comment by AnthonyWFlowers** [comment]
@vidjovanovic  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@vidjovanovic You’ve been granted access to `production`, with access limited to 6 months, expiring 11/20/24.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll
receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1716310619428809)

**Comment by bdech** [comment]
@vidjovanovic, Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
Production access removed. If you would like access, please fill out a new request

**Comment by lindsay-insco** [comment]
Access revoked
