### ISSUE TITLE
Midpoint Review - IA Feedback - IVC Forms, 10-7959c CHAMPVA Other Health Insurance (OHI) Certification

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#83098]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- thank you for bringing this through Collab Cycle!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- [ ] **Clarify entry points** Sounds like there will be at least two entry points for this form (at the end of the 1010D and in Find a Form). Any others? It would be helpful to liaise with CAIA IA's on this - tagging @kristinoletmuskat @jennymayoco.

### Consider: "Insurance is confusing" edition

- [x] **Clarification on difference between Medicare types** On the [Medicare status page](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=348-21498&t=ZZsbm2PzrbdX8clx-4), can a little more info be provided about what Medicare A and B are? Even if it's just what's on Medicare cards - "hospital" and "medical"
- [ ] **Date flexibility or option for "I don't know"** For all insurance questions, are we required to collect day/month/year that the coverage starts and/or stops, or does a month/year suffice? I am guessing no - but wanted to ask, to potentially reduce cognitive load for folks. I see that Medicare cards have the day/month/year that coverage begins. For some non-Medicare types of insurance this info might not be available on the insurance card and might require some digging - or folks may just not know. If possible to accept month/year only, or to have an "I don't know" escape valve,  that would be tremendous.
- [x] **"I don't know" option on [Type of insurance plan screen](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=292-28705&t=OOBw6qmnWIAwomIT-4)** Is it possible to add an "I don't know" option here?
- [x] **Additional hints on [Secondary health insurance question](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=370-21972&t=OOBw6qmnWIAwomIT-4)** - consider defining or giving examples of what secondary health insurance is.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by jamiefiore** [comment]
@baltes @marywang2 
I clarified the entry points with Kristen on the updated [Family Member Benefits](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1712161697570&sender=u10700c583aaa99f809c88675) Hub
I added the considerations above as well. 
I'm closing this ticket out Here is the update [figma file ](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Sx2TqrKDxWoXWqLl-0)
