### ISSUE TITLE
Qualitative Data Request for "Contact us" and "Resources and Support" pages

### ISSUE THREAD

**Issue by beckyphung** [department-of-veterans-affairs/va.gov-team#83119]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

1/1/2022

### Date Range End

5/14/2024

### Product Name(s)

Contact us page and Resources and Support page

### Product Description

The Contact us page on VA.gov helps Veterans and other users get answers to health and benefits questions. The page also connects users to different ways you can connect with a live person.

The Resources and Support page connects Veterans and other users to FAQ articles, where they can also find answers to their questions.

### Survey URL(s), key term(s), case category or type

- https://www.va.gov/contact-us/
- https://www.va.gov/resources/

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

becky.phung@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Let me know if you have any questions. Thank you.
