### ISSUE TITLE
[launch blocker] remove death certificate mandate 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#83114]
## Issue description

Updates discussed when meeting with Sean/Fiorella/Aliyah on 5/15:
- Text on information page (Aliyah confirming)
- Update logic for required uploads
   - If it's a service-connected death a death certificate is required
   - If it's a service-connected death AND the death was NOT at a VA facility the death certificate IS required
- Text on Upload Documents section to use conditional language based on whether or not the claimant selected service-connected disability

Other notes:
Jennifer got back to us saying that we need to remove the mandate of requiring a death certificate for non-service connected Burial before we launch to 100%. 

The death certificate should only be required for:
Service connected death (if they select the 1st option for the “What type of burial allowance are you claiming?” question

see this[ Slack thread ](https://dsva.slack.com/archives/C057W3N9K2S/p1715618471204479)for full details and convo

![image (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/26395703/a4476557-94a6-44fd-b57c-140955713e76)

![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/26395703/a522dbfa-c7d5-4020-bdc8-1ac60eb50a28)

**Comment by sortizsh** [comment]
FYI @steele-lm

**Comment by fiorella-io** [comment]
Met with Aliyah, Sean and Laura

Changes we need to make:
- Update logic: If service-connect benefit is selected **and** the Veteran's death happened at a VA facility, the death certificate should **not be required**
- Show conditional content for the Death certificate page. Pending Aliyah's final copy
     - [Service-connected](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=2402%3A6415&t=YlAJrgkJwF1qCrK7-1)
     - [Not service-connected](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=2402%3A6715&t=YlAJrgkJwF1qCrK7-1)
- Possible content changes to the Introduction page. Pending feedback from Aliyah.

**Comment by fiorella-io** [comment]
We got the final content from Aliyah

Introduction page: Add "may"
<img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/001d0080-77d4-455f-8049-43282fdfb713" width="60%">

Show conditional content for the Death certificate page:
     - [Service-connected](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=2402%3A6415&t=YlAJrgkJwF1qCrK7-1)
     - [Not service-connected](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=2402%3A6715&t=YlAJrgkJwF1qCrK7-1)
