### ISSUE TITLE
[Frontend] Order Page - Not eligible 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8312]
## Story 

As a Veteran who wants to reorder hearing aid batteries but is not eligible I would like to know the reason why I cannot reorder batteries and/or supplies. If the reason is six month have not elapsed I would like to see the date that I am eligible. 

## Tasks 

Create error handing per design 

https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/406054376 
https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/406260564 
https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/406260563

##Acceptance

For any given test user that is not eligible to reorder batteries/hearing aid supplies the messaging should match the one in the design provided

**Comment by mr0sari0** [comment]
Can't complete https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/406054376 yet due to not having any data about rechargability (is that a word?) from the API yet.

**Comment by mr0sari0** [comment]
Making a new ticket to update content on these pages
