### ISSUE TITLE
[DevOps] Eric Oliver needs access to CHYSHY VistA

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83135]
## User Story
We need to be able to test things, can't currently test things. See #81378, which documents what is needed for this access.

## Tasks
- [x] [DevOps] Apply for access to CHYSHY VistA.

## Acceptance Criteria
- [x] Eric has applied for access to CHYSHY VistA.

**Comment by olivereri** [comment]
Signed PDF sent to Stephen Barrs

**Comment by olivereri** [comment]
CHYSHR database access approved
