### ISSUE TITLE
CT-103: Update content based on Usability Testing Findings

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8313]
As a user of the Comparison Tool, I need the information regarding Section 103 communicated in a clear meaningful way so that I understand the impact to my education and benefits.

## Assumptions:
1. This work is completed behind feature flag created in #7773 so that it is only available in the staging environments and below.
2. The [interactive prototype](https://bahdigital.invisionapp.com/share/NFIADPR38V2#/screens) is for UI/Layout reference but is overruled by supporting artifact # 2.

## Acceptance Criteria:
1. The content under the "Institution Summary" heading of the "Additional Information" section of the profile page is displayed in the following order:
    - Accredited:
    - Type of accreditation:
    - Veterans tuition policy:
    - Protection against late VA payments:
    - Credit for military training:
    - Independent study:
    - Rogers STEM Scholarship:
    - Single point of contact for veterans:
2. The message "No information available at this time" is replaced with: "Contact the School Certifying Official (SCO) for requirements".
3.  The following content is displayed when the user clicks "Protection against late VA payments":
> ### Protection against late VA payments
> 
> If VA payments to institutions are delayed, schools receiving GI Bill benefits must allow beneficiaries to continue attending their classes if they have sufficient proof of eligibility on file.
> 
> Schools may require proof of GI Bill eligibility in the form of:
> *	Certificate of Eligibility (COE) **or**
> *	Certificate of Eligibility (COE) and additional criteria such as an award letter or other documents the school specifies
> 
> **Schools can't impose late fees, deny access to facilities or classes, or otherwise penalize beneficiaries if VA is late with tuition and/or fees payments.** The restriction on penalties doesn't apply if the beneficiary owes additional fees to the school beyond the tuition and fees that VA pays. Students are protected from these penalties up to 90 days from the beginning of the term. 
> 
> Contact the School Certifying Official (SCO) to learn more about the school’s policy. [Read our FAQs on the Veterans Benefits and Transition Act](https://benefits.va.gov/gibill/fgib/transition_act.asp) to learn more about protections against late VA payments.

## Supporting Artifacts:
1. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b19e68e5ef0de311c1effc4ba91326c47248bec7/products/education-careers/school-comparison-tool/Sec103/design/content/103-content-doc.md)
2. [UI Document - PL 115-407 Section 103](https://github.com/department-of-veterans-affairs/va.gov-team/files/4583006/gibct-pl-115-407-sec-103-v0.3-14221973.pdf)
3. [Sketch Layout](https://www.sketch.com/s/3c354981-2708-4222-898d-dda9ff130dc4)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/653
- https://github.com/department-of-veterans-affairs/vets-website/pull/12613

Can be tested using the vets-website branch `section-103-updates` and the gibct-data-service branch `section-103-message`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-12 at 10.09.47 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c3a5d0c3-b37a-41fd-acbe-76d36faf3716)
##
![Screen Shot 2020-05-12 at 10.12.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c1f37691-79fd-499c-ab69-5f275932f153)

**Comment by sonntag-adam** [comment]
In staging, closing story.

**Comment by desireeturner** [comment]
@department-of-veterans-affairs/uxbah This is ready for review.

**Comment by JenLJ** [comment]
UX review complete - and no recommended changes
