### ISSUE TITLE
Discovery: Sentry - Audit and Enhance Error Reporting for Debt Card and FSR Components

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#83134]
### Description:

This is a follow-up ticket to address the missing date on the debt card as reported in issue #79636. We initially discussed adding Sentry logging to the CDP debt cards to gather more details on potential issues with the date not displaying, which was observed during a user testing session. The scope of this ticket has expanded to include an audit of the Financial Status Report (FSR) to identify other areas that provide vague or unclear error messages, making them difficult to debug. Here are some examples of the current issues:

Failed to fetch:

- [Sentry Issue 1](https://sentry.vfs.va.gov/organizations/vsp/issues/265304/?environment=production&project=4&query=is%3Aunresolved+5655&statsPeriod=14d)
- [Sentry Issue 2](https://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=4&query=is%3Aunresolved%205655%20url%3A%22https%3A%2F%2Fwww.va.gov%2Fmanage-va-debt%2Frequest-debt-help-form-5655%2Fadditional-income-values%22&statsPeriod=14d)
- Medical copays: false positive? [Sentry Issue 3](https://sentry.vfs.va.gov/organizations/vsp/issues/205539/?environment=production&project=4&query=is%3Aunresolved+5655&statsPeriod=14d)

Acceptance Criteria

- Implement Sentry logging on the CDP debt cards to capture details on the missing date issue.
- Perform an audit of the FSR to identify areas with vague or unclear error messages.
- Enhance error reporting to provide more specific and actionable messages.
- Verify that the enhanced error messages appear correctly in the Sentry logs and provide useful debugging information.

### Front end tasks

- Identify where we should Implement Sentry Logging
- Review the FSR components to identify areas where error messages are vague or unclear.
- Document all instances of vague error messages and propose improvements.
- Prototype if needed and use Sentry to verify that the new error messages are being logged correctly and provide useful information.

**Comment by Dr-Pongo** [comment]
Opened a PR to address history issues, there's an existing ticket for FSR to address wonky copay responses and their associated sentry errors. Here are some notes on existing logging. From what I could tell we have pretty extensive error logging in Sentry. Follow on ticket for Sentry error discovery:
**[FSR] Sentry logging for form submission [#93564](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/93564)**


#### Existing FSR Sentry logging:
- Main actions:
	- `src/applications/financial-status-report/actions/copays.js` 
		- Needs some updating to catch [object, Object] errors - ticket already made:
		-  Follow on ticket: **FSR Sentry error, failed fetch handling [#59611](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/59611)**
	- `src/applications/financial-status-report/actions/geographicMeansThreshold.js` 
		- Sentry message: "income_limits failed: ${error}"
		- Messaging seems straightforward - can help identify if zip is missing & we can contact endpoint owners
	- `src/applications/financial-status-report/actions/index.js` 
		- Sentry messages: 
			- "FSR fetchFormStatus failed: ${error.detail}", 
			- "FSR fetchDebts failed: ${error.detail}"
		- Catches errors with SIP fetch and debt fetch
- Calculation helpers:
	- `src/applications/financial-status-report/utils/calculateExpenses.js` 
		- Sentry Message: "calculate_monthly_expenses request handler failed: ${error}"
		- Catches endpoint errors
	- `src/applications/financial-status-report/utils/calculateIncome.js` 
		- Sentry message: "calculate_monthly_income request handler failed: ${error}"
		- Catches endpoint errors
	- `src/applications/financial-status-report/utils/streamlinedDepends.js` 
		- Sentry message: "checkIncomeGmt failed: ${error}"
		- Catches endpoint errors
- Components:
	- `src/applications/financial-status-report/components/otherExpenses/OtherExpensesChecklist.jsx` 
		- Sentry message: "calculate_monthly_expenses failed in OtherExpensesChecklist: ${error}" 
		- Catches bad response and detects bad data
	- `src/applications/financial-status-report/components/otherExpenses/OtherExpensesSummary.jsx` 
		- Sentry message: "calculate_monthly_expenses failed in OtherExpensesSummary: ${error}"
		- Catches bad response and detects bad data
	- `src/applications/financial-status-report/components/shared/SurveyInformation.jsx` 
		- Sentry message: "5655 Error loading end of form survey"
		- Adds info on failed satisfaction survey. Provides info if the script failed we can supply to the survey team if we note regular failures
	- `src/applications/financial-status-report/components/shared/DownloadFormPDF.jsx` 
		- Sentry message: "debt-fsr-pdf-content-fetch-fail"
		- Throws if FSR pdf blob that is returned is no good

**Comment by Dr-Pongo** [comment]
Rolling again bc CI/CD is mean

**Comment by Dr-Pongo** [comment]
PR with changes have been merged!
