### ISSUE TITLE
Vets-api terminal access for Josh Houston

### ISSUE THREAD

**Issue by jhouston0** [department-of-veterans-affairs/va.gov-team#83148]
### Your Name

Josh Houston

### Your GitHub handle (terminal access is managed through GitHub)

@jhouston0

### Your dsvagovcloud AWS user name (if applicable)

Josh.Houston

### Team, Role, and Company of the target individual

Identity, Devops Engineer, Bylight

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

Samara Strauss  samara.strauss@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Laurene "Reney" Cook

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

For equip  [onboarding ticket last year](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63945)
initial [request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63942)  (that was granted) for dev/staging/sanbox env's 
I need access to production as well as maintaining dev/staging/sandbox in order to complete cert rotations; this requires terminal access to check that the certs have been uploaded correctly, and I need to be able to re-cycle the pods in order for the certs to take.

I need production access for the same reasons as stated above, since we rotate certs for both lower envs as well as prod.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by AnthonyWFlowers** [comment]
User is in Atlas
eQIP is attached via previous ticket

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@jhouston0  You’ve been granted access to the `dev`, `staging`, `sandbox`, and `production` environments. Access to `production` is limited to 6 months, expiring 11/20/24. 

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require 
you to fill out a new request.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1716310320273289)

**Comment by bdech** [comment]
@jhouston0 Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
Production access removed. If you would like access, please fill out a new request

**Comment by lindsay-insco** [comment]
Access revoked
