### ISSUE TITLE
10-7959c (Section 3): Remove Medicare status description and eligibility screens

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83158]
As a user on VA.gov, I want to be able to fill out certain Medicare information on my CHAMPVA application so that I don't have to repeat it again when filling out the OHI form. 

**Section 3**: Applicant Medicare status and eligibility screens
**Change/update**: remove secondary Medicare status description question and Medicare SS letter (proof of eligibility) upload screen (since this is already being asked in the 10-10d form)
**Figma**: https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1156-74632&t=CmbjxN3AMniiaxbg-0

<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm5rQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e57593973d6873b7711b3906f6ede13c8d8cf45b/image.png" alt="image.png" />

Acceptance criteria:
  - Given the user is filling out the 10-7959c form,
  - When they get to section 4, 
  - Then the form should no longer ask about secondary Medicare status or require proof of eligibility

**Comment by michaelclement** [comment]
Work is [done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29932). Still waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 This has been merged and should be on staging shortly. Thanks!
