### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#83179]
### Name

Cindy

### Email

Cindy.Terdiman@agile6.com

### Role

UI/UX design and research

### Team

VA.gov Design System Form Engine

### Product Manager (PM) name

Kara Kemahli

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to Cindy.Terdiman@agile6.com. Reply back here once you've created an account and I can bump you up to full access.

**Comment by cjterdi** [comment]
Thank you— All set!

Cindy

**Comment by naomimarcussen** [comment]
Great! I just bumped you up. You should be good to go!

**Comment by cjterdi** [comment]
Awesome, thanks!

**Comment by naomimarcussen** [comment]
Hi! I've upgraded your account to have full access.
