### ISSUE TITLE
Create alert in profile that Direct Deposit may be unavailable

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8318]
## Background
We're having  issues with EVSS, beyond the PPIU errors. They had a production release yesterday and it seems to be affecting Direct Deposit.

 [Negative impact to submissions](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p187673796/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Profile%20Save%20Failure%20-%20Direct%20Deposit%20Information/)

[Design - Hide Direct Deposit information if the user is incompetent or has a fiduciary #6094](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6094)

## Tasks
- [ ] Create alert in the profile for Direct Deposit being unavailable

**Comment by tressaellen** [comment]
Here's copy for the alert.

<img width="547" alt="Screen Shot 2020-04-23 at 8 12 54 AM" src="https://user-images.githubusercontent.com/58752772/80122658-504c5a80-853a-11ea-9a3e-1951c7c83599.png">

**Comment by erikphansen** [comment]
@tressaellen can you maybe paste in the raw text for the alerts to make my life a little easier? :-D

**Comment by tressaellen** [comment]
@erikphansen oh for sure! Here ya go.

**The direct deposit feature isn't available right now**
You may have trouble updating your direct deposit information at this time. We’re working to fix this. If you need to update your direct deposit information, please call us at 800-827-1000 (TTY: 800-829-4833).

**Comment by Samara-Strauss** [comment]
Thanks for moving quickly on this! We can close this after the 3:00 deploy. I don't think we have a way to confirm that the alert went live because it's under the direct deposit heading and none of us have that feature on prod.

**Comment by erikphansen** [comment]
True. But there is no reason that this wouldn't work on prod if it works on staging.

**Comment by Samara-Strauss** [comment]
Alright, we can close!
