### ISSUE TITLE
CF: Add new caution flag plain language mappings

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8319]
As a developer, I need to update the Caution Flag content for any issues found post launch so that the user has a good experience when using the Comparison Tool

## Assumptions:
1. This story will remain open until the work is delivered to production, due to the nature of the mapping updates.

## Acceptance Criteria:
1. The Caution Flag "Federal Trade Commission Filed Suit for Deceptive Action" received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
    - Title: Federal Trade Commission (FTC) filed suit for deceptive action
    - Description: The FTC filed a suit against this school for deceptive action. VA may suspend benefits to this school.
2. The Caution Flag "States Attorney General Filed Suit for Deceptive Action" received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
    - Title: State’s Attorney General filed suit for deceptive action
    - Description: The state’s Attorney General filed suit against this school for deceptive action. VA may suspend benefits to this school.
3. The Caution Flag "Settlement reached with States Attorney General" received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
    - Title: Settlement reached with state’s Attorney General
    - Description: The state's Attorney General has reached a settlement with this school.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associate Pull Request: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/666

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/431&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
Assumptions:

This story will remain open until the work is delivered to production, due to the nature of the mapping updates.

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by amyknox** [comment]
Looks good to me.

**Comment by JenLJ** [comment]
@sonntag-adam I concur with Amy - looks good from a UX perspective!

**Comment by ccruzgra** [comment]
@sonntag-adam This checks out.

**Comment by sonntag-adam** [comment]
Closing story.

**Comment by sonntag-adam** [comment]
re-opening, closed by accident

Assumptions:

This story will remain open until the work is delivered to production, due to the nature of the mapping updates.

**Comment by sonntag-adam** [comment]
Waiting on rules to run in production and will need either the settlement csv or a list of schools with new language before testing in production. Moving to blocked for now.

**Comment by dneel-bah** [comment]
Closing this story out as OBE due to the fact that:
- The language of one of the caution flags has changed since the creation of this story.
- The remaining 2 AC are not verifiable in prod due to a change in the data being provided.

This issue will now be resolved in #9851 and #9857
