### ISSUE TITLE
10-7959c (Section 4): Add EOB file upload screen for prescriptions

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83201]
As a user, I want to be able to upload supporting documents when filling out the Other Health Insurance Certification form, so that I can get the coverage I need.

**Form**: 10-7959c
**Section 4**: Provider EOB for prescriptions
**Change/update**: Add new screen for schedule of benefits file upload
**Expected**: User should be able to upload supporting documents if they have no EOB
**Figma**: https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1156-74632&t=CmbjxN3AMniiaxbg-0

## Acceptance Criteria

  - Given the user is filling out the 10-7959c form section 4
  - When the user selects "no" in the previous screen (Provider does not provide an EOB)
  - Then the user should be able to select and upload a file
  - And the user should be able to continue filling out the form

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30048). Still waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
Screenshots of the new process matching those provided in the assignment:
| | s1 | s2 |
| -- | -- | --| 
| | <img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzhlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f99e5689b08cd804113cd4b6c1a495378504928a/Screenshot%202024-05-29%20at%2012.06.16.png" alt="Screenshot 2024-05-29 at 12.06.16.png" /> |<img width="675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEFlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2ae3b80378b33ad29d00d0af73f747264a1254d/Screenshot%202024-05-29%20at%2012.09.31.png" alt="Screenshot 2024-05-29 at 12.09.31.png" />
|

**Comment by michaelclement** [comment]
@marywang2  this has been merged and will be review-able on staging shortly. Thanks!

**Comment by michaelclement** [comment]
- [X] ~~add breadcrumb~~ [this is happening [in this other PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30102)]
- [ ] update title
- [ ] add subtitle
- [ ] update question copy so that 'first name' only pulls in dynamically (remove last name)
- [ ] update hint text
- [ ] remove "I don't know" answer option
- [ ] add footer

**Comment by michaelclement** [comment]
@marywang2 All the above work has been implemented [in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30106). Please review new screenshots on the PR description on GitHub

Waiting on: 
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
screenshot of breadcrumb which is in a different PR:
<img width="575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f57e53876e2f95af1e94221c3d925e87615f2052/Screenshot%202024-05-31%20at%2011.27.04.png" alt="Screenshot 2024-05-31 at 11.27.04.png" />

**Comment by michaelclement** [comment]
@marywang2 Merged, should be reviewable on staging shortly. Thanks!

**Comment by marywang2** [comment]
@michaelclement same comments as the other ticket: 

- update title: "File for CHAMPVA Other Health Insurance Certification"
- add subtitle: "CHAMPVA Other Health Insurance Certification (VA Form 10-7959c)"
- is the upload screen directly after the eob for prescriptions screen (if user selects no)?
- breadcrumb should be sentence case (following this IA GH [page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/champva-ohi-7959c.md), so the full breadcrumb would be "Home > Family and caregiver benefits > Health and disability > CHAMPVA benefits

**Comment by michaelclement** [comment]
@marywang2 
I believe the first two bullets are taken care of, but please let me know if not.
- The upload screen is in the correct position, but I didn't add the right show/hide conditions. I've fixed that so now that upload only shows if the user selects 'yes' for prescription coverage and 'no' for prescription EOB.
- Breadcrumb casing has been fixed
 
<img width="701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmt2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cacc0fc79475855c63d3adc9d06be26c2b65183a/Screenshot%202024-06-03%20at%2009.45.57.png" alt="Screenshot 2024-06-03 at 09.45.57.png" />

**Comment by michaelclement** [comment]
Side note on the breadcrumb: I set it to just say "home", but VA.gov is automatically added by the site (I'm seeing this behavior on other forms/apps within va.gov). I'm guessing it's a policy thing for clarity?

**Comment by michaelclement** [comment]
[Latest work is here](https://github.com/department-of-veterans-affairs/vets-website/pull/30130)

**Comment by michaelclement** [comment]
@marywang2 Just an update:
- Breadcrumb change is implemented as discussed
- Header/subtitle is updated
- Upload page conditions have been fixed

[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30130) is just waiting on:
- [ ] Platform approval

**Comment by marywang2** [comment]
fyi @jamiefiore
