### ISSUE TITLE
Remove "new-tab" content on BTSSS/travel pay link

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#83213]
### User story

As a Cartography team member, I want to remove the text " (opens in new tab)" from the travel pay link on the landing page, so that the experience makes sense while we wait on stakeholder alignment.

### Notes
- Link was changed in #82679

Possible tasks:
- 

## Acceptance criteria

- BTSSS link reads simply "File a claim for travel reimbursement" and opens in the current tab.
- QA review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the change has been made and when clicking on the link it opens in the current tab.
<img width="1331" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ae3951d510f006505ce4571bb5d73eb1bfc1838/Screenshot%202024-05-23%20at%2010.42.37%E2%80%AFAM.png" alt="Screenshot 2024-05-23 at 10.42.37 AM.png" />
