### ISSUE TITLE
Drop certificates column from config tables

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#83219]
## Issue Description
When all previous work has been completed, the `certificates` column is no longer necessary and can be dropped.

Write and execute a migration to remove the `certificates` column from the sign_in_client_configs and sign_in_service_account_configs tables.

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] AC1
- [ ] AC2

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
