### ISSUE TITLE
Spike: Allow a 10-10d submission with more than 3 applicants without having to submit the form multiple times

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83211]
As a CHAMPVA applicant, I want to be able to apply using the digital form when I have more than 3 family members to include on the application.

Currently the front end for form 10-10d limits the number of applicants to 3 because the back end doesn't have a means of handling more than three applicants once the information is passed to the back end. We want to understand the effort needed to accept more than three applicants on form 10-10d so that the user doesn't have to submit the form multiple times.

Acceptance criteria
- Look into whether we can generate multiple PDFs for a 10-10d when the application covers more than 3 applicants.

**Comment by baltes** [comment]
@marywang2 @cloudmagic80 Open questions:
- Can we start this investigation with a form that's more complete on staging?
- Specific to 59a, can you clarify "each PDF should have the correct claim information for that specific claim"

**Comment by marywang2** [comment]
I updated so it's hopefully(?) less confusing. Fine to deprioritize for now since we don't have anything yet on staging.

**Comment by marywang2** [comment]
Sorry @cloudmagic80 @baltes it sounds like we do not need this after all - I am going to close it out. Thank you!

**Comment by baltes** [comment]
@cloudmagic80 I'm going to open this back up and reframe it to cover 10-10d. I'd still like for us to understand what it would take to implement that pattern.

**Comment by baltes** [comment]
@cloudmagic80 I renamed this story to make align more with its goal. This one needed work, which is why it was in the Backlog column rather than Ready and wasn't ready to be picked up. We can touch on it in planning and talk about a timebox for the investigation as part of estimation, and we can add that to the acceptance criteria then.

**Comment by cloudmagic80** [comment]
```
def submit
  Datadog::Tracing.trace('Start IVC File Submission') do
    Datadog::Tracing.active_trace&.set_tag('form_id', params[:form_number])
    form_id = get_form_id

    # Simulate params.to_json containing an array with 3 elements
    parsed_form_data = JSON.parse([{"key1": "value1"}, {"key2": "value2"}, {"key3": "value3"}].to_json)

    parsed_form_data.each do |data_hash|
      file_paths, metadata, attachment_ids = get_file_paths_and_metadata(data_hash)
      status, error_message = FileUploader.new(form_id, metadata, file_paths, attachment_ids, true).handle_uploads

      render json: build_json(Array(status), error_message)
    end
  rescue => e
    puts 'An unknown error occurred while uploading document(s).'
    Rails.logger.error "Error: #{e.message}"
    Rails.logger.error e.backtrace.join("\n")
  end
end
```

**Comment by cloudmagic80** [comment]
@baltes  @marywang2 I would say the timeline will be between 4 to 5 Sprints. I wrote some sample code on how we can get this going although we have to fully test it. 
Imagine this code is like a recipe for handling file uploads in an application. The recipe has different steps, but there's a part where it checks the ingredients (data from your form).
In the original recipe, it treats the ingredients as a single item. But, what if you could list multiple sets of ingredients in your form?
The example code we wrote shows how the recipe could be adjusted. It looks for a specific ingredient (a variable in the form data) that acts like a shopping list. If that list has three items (represented by three sets of ingredients), the recipe would run through the steps (uploading files) three times, once for each set of ingredients in the list.
