### ISSUE TITLE
Implement SignIn::Certificate model

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#83216]
## Issue Description
Implement a model that provides an abstraction for certificates stored in a client or service account configuration.

The model should have the following relationships:
* belongs to configuration (polymorphic)

The client and service account models will need the following relationships:
* has many certificates as configuration
  * this will need to be temporarily named "new_certificates" to avoid conflicts with the certificates column
  * after existing certificates have been migrated, the association will need to renamed to "certificates" and then certificates column should be added as an ignored column
  * the certificates column can then be dropped

The model should include validations to:
* prevent expired certificates from being saved
* prevent self-signed certificates from being stored.

It should also provide instance methods for:
* extracting the public key from the certificate
* determining the number of days until the certificate expires
* returning the record as an X509 object

The model should provide class methods for:
* building a new certificate record from a given plaintext certificate
* creating a new certificate record from a given plaintext certificate

## Acceptance Criteria
- [ ] Model provides validation for rejecting self-signed certificates
- [ ] Model provides validation for rejecting expired certificates
- [ ] Model implements method for determining the number of days until certificate expiration.

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
