### ISSUE TITLE
Use relationship for loading certificates

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#83218]
## Issue Description
Once the existing certificates have been migrated, the client and service account configuration models will need to be updated to reference the new certificates table.

Both configuration models must be updated:
* The `certificates` column must be added as an ignored column.
* The has many "new_certificates" relationship must be renamed to "certificates"

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] AC1
- [ ] AC2

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
