### ISSUE TITLE
Replace breadcrumb with back link - VA request flow

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#83229]
## Description
This replaces the breadcrumb with a link that points to the previous page on the VA request flow.

---

## Acceptance Criteria
- [x] Given the user is on the [Preferred date](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/va-request--preferred-date.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Reason for appointment](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/va-request--reason-for-appointment.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Preferred modality](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/va-request--preferred-modality.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Confirm contact information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/va-request--contact-information.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Review and submit](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/va-request--review-and-submit.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

### Design Assets
[Other pages](https://www.figma.com/design/5qgOkdkqzZgdg9Gkj7j3nj/Add-MHV-Secondary-Nav-%7C-Appointments-FE?node-id=1305-51132&t=h0GMssy48c8HWuMW-4)

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by vbahinwillit** [comment]
Changes for this feature are covered in ticket #83227. This is due to an number of the workflows using shared screens and page templates.

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta this is good to go. My only note is that it doesn't specify what documentation needs to be updated so I left that open - that should probably be another ticket so it doesn't hold up release

**Comment by ldelacosta** [comment]
No issues to report. Validated in staging. Closing out the ticket.
