### ISSUE TITLE
Replace breadcrumb with back link - start of scheduling flows

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#83227]
## Description
This replaces the breadcrumb with a link that points to the previous page at the start of the scheduling flows.

---

## Acceptance Criteria

- [x] Given the user is on the [Choose a type of care](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/all--type-of-care.md) page
The page title is `Schedule an appointment`
And the last link in the breadcrumb matches the page title
And the browser tab title is `Schedule an appointment | Veterans Affairs`

- [x] Given the user is on the [Choose a type of sleep care](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/all--choose-a-type-of-sleep-care.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Choose a type of eye care](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/all--choose-a-type-of-eye-care.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Choose a type of audiology care](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/all--choose-a-type-of-audiology-care.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Choose VA or CC facility](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/all--choose-va-or-cc-facility.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

### Design Assets
[Type of care page](https://www.figma.com/design/5qgOkdkqzZgdg9Gkj7j3nj/Add-MHV-Secondary-Nav-%7C-Appointments-FE?node-id=1305-51133&t=h0GMssy48c8HWuMW-4)
[Other pages](https://www.figma.com/design/5qgOkdkqzZgdg9Gkj7j3nj/Add-MHV-Secondary-Nav-%7C-Appointments-FE?node-id=1305-51132&t=h0GMssy48c8HWuMW-4)

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
No issues to report. Validated in staging. Closing out the ticket.

**Comment by ldelacosta** [comment]
Validated in staging for Judy Morrison. Looking for a second validation from UX team.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
