### ISSUE TITLE
NoK/EC visibility to 100% of users

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#83231]
### User story

As a Cartographer, I want to make NoK/EC visible to all Veterans, so that they can see their contacts.

### Notes
- Data for ~6 weeks has been analyzed, and we solved the one issue that was within our control (recommendation for where to call to edit contacts). Most recent analysis was #83122. 
- Phone number issue was fixed ~5/8/24. 

Possible tasks:
- 

## Acceptance criteria

- Checked Datadog dash to make sure any errors are as expected
- Feature toggle increased to 100%
- [Wes] communicated to AuthExp team and Patrick that we're making this change

**Comment by dcloud** [comment]
@wesrowe I think you made the change to the feature toggle, https://api.va.gov/flipper/features/profile_contacts, do you think we need to [look at this dashboard widget](https://vagov.ddog-gov.com/dashboard/e4a-257-6wa/mhv-on-vagov?fromUser=false&refresh_mode=paused&view=spans&from_ts=1715615318000&to_ts=1716220118000&live=false&tile_focus=3207176928304754) (if I have the correct widget) after a certain time has passed?

**Comment by wesrowe** [comment]
That link didn't take me to the Profile dashboard. Try [this one](https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/tvi-nid-mu6).

I believe @radavis set up a monitoring alert for some threshold so that we wouldn't have to go check this dashboard all the time. It might be a good test-flight of our documentation to see if you can find that yourself, @dcloud. Should you choose to accept that challenge.

**Comment by wesrowe** [comment]
Also: thanks for the reminder to update the ticket :) 

I did raise to 100% last Thursday, 5/16. And I notified POs. This can close.
