### ISSUE TITLE
[QA] 10-10EZR - Test FontAwesome icon->va-icon migration

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#83239]
## Description
The Design System Team will be deprecating the use of FontAwesome icons on June 8, 2024. In an effort to get ahead of this deprecation, we need to migrate all icon usage to `va-icon`.

## Resources

- [Design System Va-Icon documentation](https://design.va.gov/components/icon)

## Tasks

 - [x] Review Dev story for what migrated
 - [x] Write test cases
 - [x] Test

## Acceptance Criteria

-  New va icons have been tested and approved, and we've released them to Prod

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the icon is appear as expected. Dev ticket: [80851](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/80851)
