### ISSUE TITLE
Replace breadcrumb with back link - CC request flow

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#83230]
## Description
This replaces the breadcrumb with a link that points to the previous page on the CC request flow.

---

## Acceptance Criteria
Background: the `toggle` toggle is on

- [x] Given the user is on the [Preferred date](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--preferred-date.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Nearest city](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--nearest-city.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Request a provider](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--request-a-provider.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Choose a language](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--choose-a-language.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Reason for appointment](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--reason-for-appointment.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Confirm contact information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--contact-information.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

- [x] Given the user is on the [Review and submit](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/cc-request--review-and-submit.md) page
The breadcrumb has been removed
A link has been added that navigates to the previous page
With the text `‹ Back`

### Design Assets
[Other pages](https://www.figma.com/design/5qgOkdkqzZgdg9Gkj7j3nj/Add-MHV-Secondary-Nav-%7C-Appointments-FE?node-id=1305-51132&t=h0GMssy48c8HWuMW-4)

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by vbahinwillit** [comment]
Changes for this feature are covered in ticket #83227. This is due to a number of the workflows using shared screens and page templates.

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta this is good to go (see note in other tix re: documentation)

**Comment by ldelacosta** [comment]
No issues to report. Validated in staging. Closing out the ticket.
