### ISSUE TITLE
[Data] 10-10EZR: May Monthly Metrics Pull

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#83242]
As a HEC member, I would like to see EZR usage metrics monthly so that I know how the online EZR is doing and we can compare to pre-and-post online EZR launch.

- [x] Pull metrics for the previous month (May)
- [x] Pull metrics we've been pulling (reference [this thread](https://dsva.slack.com/archives/CMJ2V70UV/p1715630292285879))
- [x] Pull any other metrics you find interesting
- [x] Pull lifetime (April 11) to date metrics
- [x] Send to HEC folks
- [x] **Success: We have pulled and sent monthly metrics to HEC**

**Comment by luis-simauchi** [comment]
May 1, 12:00 am – May 31, 11:59 pmMetric - From DD
Total submissions:	  3,806
Total Sessions:	6,497
Start to Finish %:	 51%
% of forms submitted with TERA Questions:	36%
Avg. session time:	8 min 45 s
number of sessions that applications started	4352
number of failed submissions	33
Types of status codes present in errors	404, 502, 503
Create Error rate	1.51%

**Comment by luis-simauchi** [comment]
Apr 11, 12:00 am – Jun 4, 12:00 pm
Metric - From DD
Total submissions:   7,167
Total Sessions:   8,164
Start to Finish %: 48.2%
% of forms submitted with TERA Questions: 34.3%
Avg. session time:  8 min 43 s
Avg Page Views per Session:   5.92
number of sessions that applications started:   8,126
number of failed submissions with no retries: 66
Types of status codes present in errors: 404, 502, 503
Create Error rate:    2.41%
