### ISSUE TITLE
[CAIA Intake] - AE Profile & Debt Resolution Teams: Debt Resolution Notifications

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83243]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: AE Profile, Debt Resolution 
- **OCTO product owner:** Chante Lantos-Swett (for AE), Denise Conveyduc (for Debt) 
- **Product name:** Profile - Notification Settings 
- **Product manager:**  Travis Cahill
- **Slack channel:** accountexp-authexp or debt-resolution
- **Dedicated content writer on your team (if you have one):** `Insert name and/or GH handle`
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
## About your initiative

Debt Resolution Team is looking to add notification settings into the VA.gov Profile Notification Settings Page. 

Currently we have 3 groups: Health Care, Board of Veterans’ Appeals, and Payments. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/ce436eca-b2de-4619-80a9-693d2355c030)

There are two main types of notifications that we have to add, 1) Medical Copay and 2) Benefit Overpayments - both of these use cases indicate that the Veteran owes money due to billing or because they received money for a benefit they did not utilize for whatever reason, not that they are receiving a payment. 

Should these be added into one of the current sections, e.g. Health Care, Payments, or should they go on their own into a new group? Please note that the Payment section includes disability and pension deposit notifications, which is money being paid to the Veteran (not owed). 

It's important we determine this before additional build as we will relay this information directly to VA Profile so the notifications are built with the appropriate nomenclature in the backend. 

New notifications:
1. Medical Copay - they have new copayment they need to pay, a notice is sent only once per copay, but the Veteran could have many copays based on their appointment volume.
2. Benefit Overpayment - an alert for a new overpayment debt

Option 1
- Health Care
     - Medical Copay
- Payments
     - Benefit Overpayment

Option 2 
- Debts
     - Medical Copay
     - Benefit Overpayment

Option 3 
any other idea CAIA has about these groupings and notifications 

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

We need content support to ensure we have the appropriate groupings of notification settings as we expand the notifications veterans can modify. 

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [ ] No
- [x] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Hoping we can resolve this with a 30 minute call. 

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [ ]  No
- [x] Not sure - will plan this in conjunction w/the Debt Resolution Team and VA Notify
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [x]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle. - from the VA.gov AE Profile side of things we wouldn't put this through collab cycle as this is really a content change to the page not a major update to functionality. I'm not sure if the Debt Resolution team has a collab cycle ticket.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.

- [product outline for notification settings](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences)
- [current user flow can be found in figma](https://www.figma.com/file/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?type=design&node-id=0%3A1&mode=design&t=y8vih7OCF5PGBczD-1)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by HeatherRienks** [comment]
following 
@Tom-Davis @denisecoveyduc

**Comment by laurwill** [comment]
Hi @mtcA6 , 
We can discuss more and get input from IA in office hours today, but noting a few thoughts:
- Option 1 seems lopsided to me—if we nest copays in health care, I'd maybe expect benefit overpayments to be nested in benefits
- Option 2 could work fine, I think. But I noticed in our style guide section about debts that mobile app nests debts under "Payments" as the top level category. So we could consider an Option 3 here: Change the existing "Payments" section to "Payments and debts" and nest all 3 (payments, overpayments, copay bills) in that section. 

cc @mistymg for connection to mobile app—let us know if you have thoughts here!

**Comment by mtcA6** [comment]
@laurwill you said: 
> Option 1 seems lopsided to me—if we nest copays in health care, I'd maybe expect benefit overpayments to be nested in benefits

I don't know if this will change your mind but I do think we'll need to add a `benefits` section here very soon. Had a conversation today with @jstrothman about [https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B19[…].docx&action=default&mobileredirect=true&DefaultItemOpen=1](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B19BAAD0C-6401-48B0-BFB7-13FD081B79AE%7D&file=AR77%20and%20notification%20preferences.docx&action=default&mobileredirect=true&DefaultItemOpen=1). She's going to submit another CAIA ticket to work through the implications of that rule on the Notification Settings page.  

Julie you were right, a comment on here is a good idea! I'll still bring this up on the 4:15 call but worth making note because I'll forget the linkages 6 months from now :) 

cc: @ACParker89

**Comment by mtcA6** [comment]
Started with: 
Payments
Disability and pension deposit notifications 
:black_square_button: Notify me by text

Benefit overpayment debt notification < is this a new debt letter? is it sending them to a letter? 
:black_square_button: Notify me by email

New health care copay notification
:black_square_button: Notify me by email


---
Leaving content office hours with: 

New benefit overpayment debt letter 
:black_square_button: Notify me by email

New health care copay bill
:black_square_button: Notify me by email

**Comment by mtcA6** [comment]
Thanks for the help!
