### ISSUE TITLE
PM | Profile Completion | Define Completion Criteria

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83262]
What things in the profile, once filled in, help a user advance additional tasks, and or provide the VA with vital details for surfacing benefits information? 

Account Security
- I don't think there is anything here but we'd need to confirm the flow 

Contact Information: 
- Mailing address (since this is where letters and RX's are sent) 

Notification Settings need: 
- Mobile Phone Number 
- email

The completion should be dismissible. If they don't want to add their details then we should let them dismiss it.  

POST MVP - encourage direct deposit, an annual update / data refresh

**Comment by mtcA6** [comment]
@clantosswett i think this would be the bare minimum set of things that we'd want to encourage veterans to complete and at a minimum we'd want to let people dismiss things and ignore it. Any other minim needs and then we can start to pull this in to an project outline? 

cc: @ACParker89

**Comment by clantosswett** [comment]
@mtcA6 thoughts on direct deposit? I realize not everyone has direct deposit so this might bring in too much conditional logic for an initial MVP. But seems like a worthwhile thing to encourage a user to fill out.

**Comment by mtcA6** [comment]
I feel like you're right not MVP. Also, new users to the site likely won't have applied for benefits yet where they'd be able to input their direct deposit info.

My thought by not including that is exactly what you highlighted, it has the potential to introduce a lot of conditional logic. I could see that being a great next step to try to build out the framework we've been talking about to nudge a user to fill in direct deposit info especially as a tutorial, HEY we see you have access to direct deposit but haven't filled it in yet. Follow this path to do so. 

That would be a powerful next step!

**Comment by mtcA6** [comment]
@clantosswett I'm thinking we use this to build good bones and keep the scope trimmed down as best as possible.

**Comment by mtcA6** [comment]
used this ticket as a starting point to write the [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/profile-completion/README.md)
