### ISSUE TITLE
SOCKS access for [Brandon Cooper] 10-10 Team

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#83274]
### Your Name

Brandon Cooper

### Your Email

brandon.cooper@adhocteam.us

### Your GitHub Handle

coope93

### Your Role and Team

Senior Software Engineer - 10-10 Health Apps

### Product Manager (PM) name and email

Heather Justice heather.justic@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman patrick.bateman@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6y1GNQYTYhJaSQ/uEEbUrOuLvJavXyZJHatJ0Zd2mT brandon.cooper@brandoncooper-Q23P9PMX07

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16926386/d546a08b-52aa-48a8-bc28-a859781ea690)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by coope93** [comment]
Apologies, but I forgot to write down my passphrase and could not remember it. Per some conversations I found in the slack I just deleted my old key and generated a new one and created a new request. I also made sure to add my passphrase to 1Password so I don't forgot it again.

**Comment by patrick-black-oddball** [comment]
All set - wait the 6-10 minutes and you should be good
