### ISSUE TITLE
[Benefit Detail Page] [PW intake] Update content on button in education wizard, request from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#83289]
### Status
**[2024-05-16]** Moved to Next refinement to discuss during meeting on 5/21 and added AC. Will target Sprint 5, which starts on May 29th.

### Indicate if you need front-end engineering support for

- [ ] Content audit
- [X] ~Implementation~ Editing of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [ ] Something else

### Describe your request

Education services is asking us to change the text on the button that starts the wizard on our [How to apply for the GI Bill and related benefits](https://www.va.gov/education/how-to-apply/) page. Instead of "Find your education benefits form" the new content should read:

Apply for education benefits

### AC
- [x] The text previously displayed ("Find your education benefits form") on the button now displays: Apply for education benefits

### Time constraints / launch deadlines

No hard timing. Education services said that they learned Veterans are finding the current button text confusing and asked for the change.

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by FranECross** [comment]
@FranECross to follow up and confirm the PW team will actually be doing this work. See slack thread.

**Comment by randimays** [comment]
Successfully validated in production. Closing!

<img width="721" alt="Screenshot 2024-05-30 at 12 26 20 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/19175324/116d55ff-a450-4a07-acc5-880b30e9e365">

**Comment by RLHecht** [comment]
Thank you so much for this fix!!
