### ISSUE TITLE
Create generic copy for Direct Deposit being down

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8328]
## Background
We're having  issues with EVSS, beyond the PPIU errors. They had a production release yesterday and it seems to be affecting Direct Deposit.

 [Negative impact to submissions](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p187673796/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Profile%20Save%20Failure%20-%20Direct%20Deposit%20Information/)

FE Ticket [Create alert in profile that Direct Deposit may be unavailable #8318](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8318)

## Tasks
- [ ] Work with Peggy to create copy for Direct Deposit being down

**Comment by Samara-Strauss** [comment]
This copy needs to mention:

- We are having trouble with the direct deposit feature and it may not be working
- In the meantime, people can still update their DD info by calling the helpline
- Helpline contact info

**Comment by tressaellen** [comment]
Here's a first pass based on some other messaging we have in the profile, @peggygannon . Any revisions or changes would be great.

![Screen Shot 2020-04-23 at 7.48.41 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/2b3c30ab-4f51-4a61-8ad9-257157c22b4f)

**Comment by peggygannon** [comment]
@Samara-Strauss @tressaellen 
Please see below for recommended messages. I created 2 options. Option A aligns with some other downtime work I'm doing right now (creating generic partial downtime messaging). 

 Option B provides more specific header to DD

-----

OPTION A: Generic header, with goal that this could be used going forward if **any** profile service is unavailable. We name **which** component in the body of the message. 

**Some profile services may not be available right now**

You may have trouble updating your direct deposit information at this time. We’re working to fix this. If you need to update your direct deposit information, please call us at 800-827-1000 (TTY:  800-829-4833). 

----

OPTION B: More specific header 

**The direct deposit feature isn't available right now**
You may have trouble updating your direct deposit information at this time. We’re working to fix this. If you need to update your direct deposit information, please call us at 800-827-1000 (TTY:  800-829-4833).

**Comment by Samara-Strauss** [comment]
Thanks for the fast turnaround! I prefer option B.

**Comment by tressaellen** [comment]
I also prefer option B. 

![Screen Shot 2020-04-23 at 7.58.56 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/1c2a8f69-7448-444b-a4c9-32733a3bbf7a)

**Comment by Samara-Strauss** [comment]
Thanks for this! Closing.
