### ISSUE TITLE
As a user certifying OHI, I need my supporting documents routed correctly according to their type

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83299]
As a user submitting form 10-7959c, I need my supporting documents routed correctly according to their type so that all of my documents are processed as smoothly as possible.

### Acceptance Criteria
Given a form 10-7959c submitted by a CHAMPVA applicant
- When the user submits
- Then the form and each supporting document are sent as individual files
- And each file has its document type included in its metadata

Given a supporting document submitted with a VFMP form
- When the user selects a document type in the dropdown of the upload screen
- The uploaded document should have the user-selected doc type mapped to its metadata 

### Implementation notes
This is similar to the work done for 10-10d in [this user story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80644).

**Comment by balexandr** [comment]
@cloudmagic80 If this ticket is similar to this https://github.com/department-of-veterans-affairs/vets-api/pull/16726 try to abstract the individual form logic to their models or to the `attachment.rb` service class to keep the controller clean and readable. We just don't want a list of conditionals in the controller bulking it up when it shouldn't really care about the individual forms all that much.

**Comment by cloudmagic80** [comment]
PR is here:
https://github.com/department-of-veterans-affairs/vets-api/pull/16856
