### ISSUE TITLE
[Design] Update Intro page to communicate that we're showing you more providers than just your preferences, if provided in the referral

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83298]
## Tasks

- [x] Update Intro page to communicate that we're showing you more providers than just your preferences, if provided in the referral

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/83298?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by cgednalske** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/83298?planning-poker) with Zenhub @Cieramaddox @benbrasso-agile6

**Comment by cgednalske** [comment]
Intro page updated and confirmed with UX. We'll test out [this approach](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1444%3A25527&t=zqnmWi4OcNeqL70u-1). 

Closing this out as Ciera will now incorporate it into the final mockups for #82902.
