### ISSUE TITLE
Migrate Research Content on GDrive to Github

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#83308]
## Context
Need to ensure all relevant content on GDrive is accessible in VA's Github
## AC

- [x] Audit current documentation to find gaps
  - [google spreadsheet](https://docs.google.com/spreadsheets/d/1OKn-o_TJY4UF2AZ7YUdwfzSXYgzGaBB-uGJEvTFba3E/edit#gid=1589371600)
- [x] create a list of items to upload for research content for communication campagin
- [x] create list of items to upload for research content for IPP
- [x] create list of items to upload for research content for discovery discovery
- [x] share with the design team to gain consensus
- [x] Document purpose and location in google spreadsheet
- [x] Copy over content to Github

Resource for MD conversion: https://euangoddard.github.io/clipboard2markdown/

Reviewer: @JKG199 

Notes:
Does not include NON-research content

Deadline: Monday, 5/20/24 by 12pm ET

**Comment by SophiaPhilipMO** [comment]
@JKG199 ready for review to cross check [research list ](https://docs.google.com/spreadsheets/d/1OKn-o_TJY4UF2AZ7YUdwfzSXYgzGaBB-uGJEvTFba3E/edit#gid=1589371600) and make sure all documentation is uploaded. The readme landing page of each research folder needs updating as the links are broken but waiting to do that until very end

**Comment by JKG199** [comment]
@SophiaPhilipMO reviewed research column and highlighted missing content in yellow. Otherwise, everything that's in the spreadsheet aligns with that is uploaded.
