### ISSUE TITLE
Incorrect Fax Number on Add dependents to your VA disability benefits page

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#8331]
## What happened?
_ The fax # for the "file a claim for additional disability compensation for a dependent parent" is incorrect.    Instead of 844-531-**7817** if you live in the U.S. it should be 844-531-**7818**

![image](https://user-images.githubusercontent.com/63107147/80119590-e5aa1780-8557-11ea-98b4-c792409e41c4.png)

## Specs:
- Device: N/A
- Browser: N/A
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/disability/add-remove-dependent/
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [x] _Fax number listed should be: 844-531-7818

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by stephorkandatx** [comment]
@lunascoop or @RLHecht is this a simple adjustment to the content?

**Comment by RLHecht** [comment]
@stephorkandatx Yep, I can make this fix in Drupal.

**Comment by lunascoop** [comment]
I'm having some trouble with access.

**Comment by RLHecht** [comment]
@stephorkandatx This has been fixed and published. Moving to validate and will close when on live site.

**Comment by stephorkandatx** [comment]
Thank you @RLHecht !

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket
