### ISSUE TITLE
Spike: IVC Form resubmission

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83319]
As a user applying to VFMP program (CHAMPVA, FMP, etc) I need my application to be recoverable if something goes wrong during transmission from the digital form.

### Acceptance criteria

Research options available and ideally make a recommendation so that we have a path to a solution for handling forms that don't reach their destination after being submitted from VA.gov.

Scenarios:
- We get anything other than a 200 from s3 on form submit
   - This should be rare, but we need to state how we can help applicants if it happens
- A form is submitted successfully to s3 but we don't get a response from PEGA after a specified amount of time
- An application and supporting documents are submitted to s3, but the PEGA response does not account for all documents

Documentation of options [Research Spike: Form Resubmission Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/research-spike-form-resubmission.md)

**Comment by balexandr** [comment]
I filled this doc out already, we need to hear back from Premal I believe

**Comment by balexandr** [comment]
Reached out to Premal in ivc-forms-engineering

**Comment by balexandr** [comment]
Here is the conversation with Premal/Adrian https://dsva.slack.com/archives/C068Y3ZFKNJ/p1717690517038599
I think as long as we have both avenues covered we should be good. By both avenues I mean:
1. Failure to upload to Pega's S3:
- Solution: Ensure error messaging is in place that's descriptive enough for the user to try again in the future
2. Failure to receive a status from Pega
- Solution: Added a Sidekiq job to submit all forms missing statuses to a DD dashboard
