### ISSUE TITLE
10-10CG - Bug - Review page shows incorrect text/formatting for Secondary Family Caregiver

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#83329]
**Test Info**
Environment: Staging
User: Unauthenticated 

**Steps to reproduce**:
1. Go to the 10-10CG form.
2. Fill out any required sections up to the Secondary Family Caregiver section
3. Select "Yes" to apply for benefits for Secondary Family Caregiver
4. Fill out all required fields and click "Continue"
5. Fill out all required fields on contact information page
6. At the bottom of this page, for the "Would you like to apply for benefits for another Secondary Family Caregiver?", select "Yes" or "No", doesn't matter which one is selected, but do select one of them and click "Continue"
7. Continue through form to get to the "Review application" page 
8. Expand the "Secondary Family Caregiver applicant information" and go to the last section
9. Notice that the formatting of the left side isn't correct

Screenshot:
<img width="1331" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnpxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b1bb419ad4d249e343c866bb49f2a640bb4f20f/Screenshot%202024-05-15%20at%2011.59.23%E2%80%AFAM.png" alt="Screenshot 2024-05-15 at 11.59.23 AM.png" />

Video:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c7ba396dfc015515723cd72ed89178d8cdfdf4b/Screen%20Recording%202024-05-16%20at%2011.22.09%E2%80%AFAM.mov)

**Comment by hdjustice** [comment]
@longmd - can you take a look at this and see what we can do fix it, and what kind of estimate we can put on it?

**Comment by longmd** [comment]
@hdjustice - The 3 that was on was way too high. Backing off to a 1. Its a quick change.

**Comment by longmd** [comment]
@allanto-ah , you can [hit this Review Instance](http://f27e63dff8426ffa1d1b33a216e6d156.review.vetsgov-internal/) to validate the changes. I have validated per the screenshots in the PR above.

**Comment by allanto-ah** [comment]
Environment: Review Instance

Verified that this has been fixed.
<img width="1384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12381b35d6b1920c5e8be6314dd2826ed19a266e/Screenshot%202024-05-28%20at%2012.25.45%E2%80%AFPM.png" alt="Screenshot 2024-05-28 at 12.25.45 PM.png" />
