### ISSUE TITLE
Move to new FMB benefit detail page: VA home loan programs for surviving spouses

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#83333]
## Description
We need to move this page from the Veteran benefit hub to the family member benefit hub: [VA home loan programs for surviving spouses](https://www.va.gov/housing-assistance/home-loans/surviving-spouse/)

### Step 1: Publish
- [x] DB: Clone and update the page in Drupal
- [x] DB: Update the H1 and URL in Drupal to align with the IA spec
- [x] ST: Copyedit and publish the page

### Step 2: Redirect
- [x] KOM: Tasks outlined in [order of operations ticket for phase 5?]

## Criteria

- [x] New family benefit detail page is published on VA.gov

**Comment by laurwill** [comment]
Kristin is this the same type of ticket as the "Migrate CHAMPVA" and "Migrate PCAFC" tickets in this phase?

**Comment by kristinoletmuskat** [comment]
Yes, I can change title to 'Migrate' so that is clearer!

**Comment by d-beyer** [comment]
I've [cloned the page](https://prod.cms.va.gov/va-home-loan-programs-for-surviving-spouses-cloned).

**Comment by laurwill** [comment]
Hi @kristinoletmuskat , Danielle mentioned we might not be migrating this page in phase 1 due to SME concerns — do you know the final call on that, or do we need to ask OCTO folks?

**Comment by laurwill** [comment]
SMEs didn't approve this migration for phase 1, we'll do this with rest of housing content instead.

**Comment by aprocik1** [comment]
Update: I emailed David Ahn about the FMB migration. I told him to expect a follow up email from Kristin about redirecting this page next week.

**Comment by d-beyer** [comment]
I've created [a new clone of the page ](https://prod.cms.va.gov/surviving-spouse-home-loan)to account for recent edits, and updated the H1 and url.

**Comment by saratorres2** [comment]
@aprocik1 @d-beyer VA home loan programs for surviving spouses page ([Drupal](https://prod.cms.va.gov/surviving-spouse-home-loan)) is published. Will QA later today when the page is live.

**Comment by saratorres2** [comment]
Confirming that I've archived the outdated node: "VA home loan programs for surviving spouses," https://prod.cms.va.gov/housing-assistance/home-loans/surviving-spouse
