### ISSUE TITLE
10-10CG - Bug - Trying to add a Secondary Family Caregiver on the "Review application" page shows a blank page

### ISSUE THREAD

**Issue by allanto-ah** [department-of-veterans-affairs/va.gov-team#83332]
**Test Info**
Environment: Staging
User: Unauthenticated 

**Steps to reproduce**:
1. Go to the 10-10CG form.
2. Fill out any required sections up to the Secondary Family Caregiver section
3. Select "Yes" to apply for benefits for Secondary Family Caregiver
4. Fill out all required fields and click "Continue"
5. Fill out all required fields on contact information page
6. At the bottom of this page, for the "Would you like to apply for benefits for another Secondary Family Caregiver?", select "No" and click "Continue"
7. Continue through form to get to the "Review application" page 
8. Expand the "Secondary Family Caregiver applicant information" and go to the last section and click on "Edit"
9. Change the "Would you like to apply for benefits for another Secondary Family Caregiver?" from "No" to "Yes"

Video:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37cd41e66d3a5d7abc07ac42b799720c86428bbc/Screen%20Recording%202024-05-16%20at%2011.23.02%E2%80%AFAM.mov)

**Comment by hdjustice** [comment]
@allanto-ah @coope93 - Was this tested and validated?  If so, can you please add a comment here about that?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this has been fixed. 

https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/f1417c61-2beb-41a5-bb67-0acc6aab7f36
