### ISSUE TITLE
Migrate Sidekiq setup instrux to -sensitive

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#8334]
This doc: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Vets-API/Sidekiq%20Enterprise%20Setup.md

Should be migrated to `va.gov-team-sensitive` 

And the link to it should be updated here: https://github.com/department-of-veterans-affairs/vets-api/#sidekiq-enterprise

**Comment by billfienberg** [comment]
PR to delete content from `vets.gov-team`: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20117

PR to add content to `va.gov-team-sensitive`: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/102

PR to update link in `vets-api`: https://github.com/department-of-veterans-affairs/vets-api/pull/4239

**Comment by gmaciolek** [comment]
@meganhkelley and @billfienberg looks like this one might be done?

**Comment by billfienberg** [comment]
> @meganhkelley and @billfienberg looks like this one might be done?

@gmaciolek, since all of the above PRs have been merged, I think it's safe to say this is **Done**.
