### ISSUE TITLE
Recent Facilities Endpoint in vets-api 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#83352]
## Description
Create an endpoint to capture the recent facilities for a user. 

The vets-api AppointmentService contains a method called `get_most_recent_visited_clinic_appointment` that performs the calls and checks needed to obtain a user's most recently visited clinics, if any. We will use this method to augment data returned from the AppointmentService, following these rough logical steps:

- Check the Upcoming appointments (included canceled booked appointments) for facility information
- Check Past appointments to retrieve facility information looking at the user's 12 months history.
- vets-api will collect the data beforehand and frontend will display recent locations on the locations page
- If no locations returned from vets-api, then frontend will display the By home address view.
- Track the user switching between toggles by recent location, by home address or by location.

Additional technical notes:
- We will likely need to add this data into the response for `get_appointments` since this is called at the start of the appointments flow and we will need this data available before a user submits a `create_appointment` request *we still need to determine for certain where exactly to put this data, or if the website needs to call the recent clinics endpoint separately*
- We will want to verify the recent clinic fetch functionality with new rspecs and vcr cassettes
- We can store the list of recent clinics in a new `recent_clinics` field in the appointment response

The spike ticket linked below references the implementation for fetching recent facilities.

Reference spike ticket: [#81136](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81136) 
---

## Acceptance Criteria
Background: the `va_online_scheduling_recent_locations_filter` toggle is on
[ ] - new `recent_clinics` field is returned in the appointments response, following the logic outlined above (the field will be nil if no data was found for it)
[ ] - new rspecs and vcr cassettes for the data returned from `get_most_recent_visited_clinic_appointment`
[ ] - all regression tests pass

### Design Assets
Figma File

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Bren22va** [comment]
Broken down into smaller tickets in place of this. Closing this "master" ticket.

**Comment by ldelacosta** [comment]
Please list out the small tickets before closing it out @Bren22va

**Comment by cferris32** [comment]
Here are the tickets for this work:

[Prototype vets-api endpoint](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/89322)

[Enhancements to finalize prototype endpoint](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/89323)

[Test coverage for endpoint implementation](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/89324)

**Comment by ldelacosta** [comment]
Closing out the ticket. No longer is needed.
