### ISSUE TITLE
[Bug] GI Bill: Participant ID Gating is Too Harsh

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8336]
## What happened?
During testing of Original Claims when the veteran browsed to their GI Bill information it failed to pull it up.  It seems like we are gating on the participant ID too harshly.

` :evss :access?` changes, per Silvio.

## Specs:
- Device: Windows
- Browser: Chrome

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
I have no idea what to do with this ticket. I believe this needs to be modified on the back-end only.

**Comment by annaswims** [comment]
This sounds like a BE ticket, but I don't quite know where to start.  

> when the veteran browsed to their GI Bill information it failed to pull it up

Where does a veteran browse to their GI Bill info?

**Comment by annaswims** [comment]
is it https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status

**Comment by annaswims** [comment]
the [GET GI Bill Status Requests (per time interval) ](http://grafana.vfs.va.gov/d/000000090/evss?panelId=1&fullscreen&orgId=1) shows that the failure rate dropped significantly after the last EVSS deploy (4/28 9pm EST) ![Screen Shot 2020-05-04 at 11.33.22 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/f5265488-4a26-4b2e-a56d-eb339d0d3790)

**Comment by annaswims** [comment]
related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8686

**Comment by annaswims** [comment]
we sould see this rate drop http://grafana.vfs.va.gov/d/000000056/evss-pundit-authorization?editview=versions&orgId=1

**Comment by annaswims** [comment]
Current behavior is to only query EVSS for `gi_bill_status` if we have a  `participant_id`, `edipi`, and `ssn` for that user.  

Before I make any changes I'd like to verify[ EVSS docs](https://csraciapp6.evss.srarad.com/wss-education-services-web/swagger-ui/index.html), but I'm struggling to find the proper ones.  The docs are linked here, but [VPN instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/evss-integration/readme.md#api-documentation) link to a non-responsive page

**Comment by annaswims** [comment]
chatted with Silvio and it sounds like no changes are necessary. Closing.
