### ISSUE TITLE
10-7959a urls 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83365]
- URL: va.gov/family-and-caregiver-benefits/health-and-disability/file-champva-claim-10-7959a/
- Breadcrumb: Va.gov home > Family and caregiver benefits > Health and disability benefits for family and caregivers > [10-7959a form H1]
- Github reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/champva-claim-7959a.md
- figma [link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=961-139667&t=Ko13IszQmJiM9ZRY-0)

URLs:
Intro: /intro

Section 1: Signer info

- Signer info: /signer-type
- Name: /signer-info
- Mailing address: /signer-mailing-address
- contact info: /signer-contact-info
- Relationship: /signer-relationship

Section 2: Sponsor information: 

- name and dob: /sponsor-info

Section 3: Beneficiary info:

- name and dob: /beneficiary-info
- identification info: /beneficiary-identification-info
- (if 3rd party signer)
- address selection: /beneficiary-address
- mailing address: /beneficiary-mailing-address
- phone number: /beneficiary-contact-info

Section 4: Health insurance information

- health insurance status: /insurance-status
- health insurance intro: /insurance-intro
- policy information: /policy-info
- insurance type: /insurance-type
- insurance review:  /insurance-review

Section 5: Claim information

- claim type: /claim-type
- claim relation to work: /claim-work
- claim relation to automative accident: /claim-auto-accident
- medical: /medical-claim-upload
- OHI: /eob-upload
- 2 OHIs: /additional-eob-upload
- pharmacy path: /pharmacy-claim-upload

Section 6: Review and sign
- review: /review-and-submit
- confirmation: /confirmation

**Comment by marywang2** [comment]
@kristinoletmuskat just checking that this is the breadcrumb and url to use for the CHAMPVA claim form.

**Comment by kristinoletmuskat** [comment]
@marywang2 yes, just updated the breadcrumb -- the first link according to our new guidance is always **Va.gov home**. This is different from most of what you will see on the site because the guidance is new.

**Comment by michaelclement** [comment]
@marywang2 @syd-hoeper Merged, should be visible on staging shortly

**Comment by michaelclement** [comment]
URL change was made in this PR. Waiting on:
- [ ] Team approval
- [ ] Platform approval

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2fc8c7f2fe5a876d52dfa8d8e8d6bcf2010969a/url.png" alt="url.png" />
