### ISSUE TITLE
[CAIA A11y Research]: VFF/Auth. Exp.: Confirmation page with Status, My VA (June 2024)

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#83382]
> [!NOTE]
> **High-Level Overview**: VFF and Authenticated Experience
> - **Initial Kickoff**: NA
> - **Research Timeframe**: June 11, June 13-June 25
> - **Time of Day:** Morning and Afternoon
> - **Pilot**:   5/29/2024 at 11 a.m. [Ticket 83814](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83814)
> - **Assistive Tech Users**: **Goal**: 12 AT Users (6 as of 6/12/2024) 
> - **Artifacts Available**: Yes
> - **Testing Environment:** CodePen
> - **Assistive Tech Being Used**: `3` screen reader users; `3` magnification/zoom users; `3` colorblind users; and `2` cognitively impaired users
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- Sara
- @SarahKay8 
- @coforma-jamie 

</details>

## About the Team

<details><summary>Toggle to view information about the team.</summary>

- Team name:VFF and Authenticated Experience 
- OCTO-DE product owner: Matthew Dingee and Chante Lantos-Swett
- Product manager: Tricia Baker and Ana Jakabcin (AJ)
- Designer: Jeana Clark and Matt Marino
- FE engineers: Nick Sprinkle, Jacob Penner, Robert Hasselle, and Allison Lu
- Product/team Slack channel: #veteran-facing-forms and #accountexp-authexp

</details>

### About the Research

<details><summary>Toggle to view the research goals and outcome expectations.</summary>

#### Research Goals

> - Evaluate the usability of presenting form statuses to users and their understanding of those statuses on the confirmation page and within My VA
>     - How do Veterans interpret possible error states?
>     - - How long do Veterans expect to have access to this information?
>     - - - Do Veterans understand where to look for claim status information?
> - Evaluate the effectiveness of presenting a “What happens next” task list and their understanding of those steps on the confirmation page and within My VA
> - Evaluate the usability and usefulness of providing a downloadable copy of the form submission
> - Gather findings on Veteran expectations of claim benefit submission and status overall
> - Evaluate the effectiveness of submitted benefit application cards on My VA

#### Outcome

> The findings from this research will help the forms team better understand a user’s understanding of their form submission status and what happens next. Based on the usability of the updated confirmation page and the changes to My VA, we will present findings and specific recommendations for updating form confirmation pages and My VA. In addition, we will be sharing our research findings with other VFS teams.

</details>

### Additional Intake Info.

<details><summary>Toggle to view more intake research ticket information</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### If you have an accessibility champion, what's their name?

In the VFF team @jeana-adhoc is an accessibility specialist 

### Calendar checking

- [x] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [x] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [x] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

### When is the timeframe for your testing?

June 11th, June 13-25th 

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

<details><summary>Toggle to view research timing information.</summary>

### Timeframe

- **Pilot Session**: #83814
- **Timeframe**: `See ticket for details` ~likely to be between May 30-June 14~ June 11th, June 13-25th 
- **Source of Truth:** [Canvas for the 2024-06 VFF and My VA Form Submission Status Research](https://dsva.slack.com/docs/T03FECE8V/F077GNGA29J)

### Length of sessions

- **Session length:** `90` minutes
- **Buffer time between sessions:** `30` minutes
- **Maximum sessions per day:** `4`

#### Participant Recruitment Goal for Team

- **Total Requested:** 16
- **Completed Sessions Needed:** 12, including:
    - 3 screen reader users
    - 3 magnification/zoom users
    - 3 colorblind users
    - 2 cognitively impaired users

</details>

###  Testing Schedule

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

Please toggle and use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

**Source of Truth:** [Canvas for the 2024-06 VFF and My VA Form Submission Status Research](https://dsva.slack.com/docs/T03FECE8V/F077GNGA29J)

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available | Notes
------------------|------------------|--------------|--------------|--------------|--------------|--------------|--------------
✈️ `PILOT SESSION 83814 ` | 5/29 | **Screen readers** (**JAWS) | Desktop; Windows | Safari, Chrome, etc. `TBD` | NA | @coforma-jamie  | #83814
P9 | 6/20/2024, 10-11 a.m. | Screen Magnification | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | Sara | Cognitive disability, Resizes text on screen, Zooms in
P10 | ~~6/20/24, 12-1:30 p.m.~~ 6/21/2024, 3-4:30pm `rescheduled` | VoiceOver | Tablet (iPad); MacOS, iOS  | Safari, Chrome, etc. `TBD` | Advanced (10 years VO) | @SarahKay8 | Does resize the text on my screen, Does use a screen magnifier (sometimes), Does use a screen reader(VoiceOver; 10 years, iPad), Colorblind, Cognitive disability 
P11 | 6/20/2024, 3-4 p.m. | Screen Magnification | Desktop; Windows | Chrome | Advanced | @coforma-jamie  | Does resize text on screen, does zoom in the text to see better, Cognitive disability: Prefer not to answer 
P14 | 6/24/24, 12-1:30 p.m. | JAWS | Desktop; Windows | Safari, Chrome, etc. `TBD` | Intermediate | @SarahKay8 | Colorblindness, Screen reader (JAWS; 3 years; Computer)
P15 | ~~6/25/2024, 10 - 11:30 a.m.~~ `cancelled` | VoiceOver | Laptop; MacOS, | Safari, Chrome, etc. `TBD` | Intermediate or Advanced `TBD` | @coforma-jamie  | Screen reader (VoiceOver, 5 Years, Laptop) 
P16 | 6/25/2024, 12-1:30 p.m. | VoiceOver | Mobile or iPad, MacOS, iOS | Safari, Chrome, etc. `TBD` | Advanced | Sara | Screen reader (VoiceOver, 18 years, iPad/Mobile Phone)
P17 | ~~6/26/24, 3:00-4:30 p.m.~~ `no-show` | JAWS | Desktop; Windows | Safari, Chrome, etc. `TBD` | Advanced | @coforma-jamie

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Product outline - VFF for Forms Status and My VA Confirmation Changes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#readme)
- [Product outline - My VA](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#readme)
- [Project outline - My VA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/README.md)
- [Prototype or mockups - at top of conversation guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Form%20Status/Research/conversation-guide.md)
- [Research plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Form%20Status/Research/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Form%20Status/Research/conversation-guide.md)
- [Epics/issue that may be helpful - VFF](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Product%20Outline%20Confirmation.md)
- [Epics/issue that may be helpful - My VA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/README.md)

</details>

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket
- [ ] **INITIAL MEETING:** Schedule meeting with team
- [ ] **(OPTIONAL) FEEDBACK REQUESTED:** Review Conversation Guide
- [x] **PILOT SESSION: SCHEDULE** Pilot session with team.
- [x] **PILOT SESSION: CREATE TICKET**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83814
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available.
- [x] Research availability by day - ballpark availability sent to Matt on 6/6/2024
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean)
- [x] **RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1o22HVZcZsOIgBQa-RtWCDNvHwHUKTVcseYXyOkvdAJY/edit?usp=sharing)
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support. **Source of Truth:** [Canvas for the 2024-06 VFF and My VA Form Submission Status Research](https://dsva.slack.com/docs/T03FECE8V/F077GNGA29J)
- [x] **Review research folder and assets**
- [ ] **Participate in research**  **Date Span:**`06/11/2024` and `06/25/2024`
- [x] **SESSION NOTES**: Create [CAIA notes document](https://docs.google.com/document/d/1o22HVZcZsOIgBQa-RtWCDNvHwHUKTVcseYXyOkvdAJY/edit?usp=sharing) for a11ys to use during the sessions
- [x] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [x] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket. **See Comments in this ticket**
- [x] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
```

```[tasklist]
### VFS TEAM Tasks
- [x] Tag @coforma-terry in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH)
- [ ] Schedule intial meeting with @coforma-terry and @sara-amanda
- [x] Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired (req. 5/21/2024)
- [x] Schedule a pilot session with CAIA a11ys (5/29)
- [ ] (OPTIONAL) Receive feedback on Conversation Guide for Screen Readers (if requested)
- [x] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section
- [x] **DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. **Source of Truth:** [Canvas for the 2024-06 VFF and My VA Form Submission Status Research](https://dsva.slack.com/docs/T03FECE8V/F077GNGA29J)
- [x] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in the `Table` in the ticket above.
- [x] **INVITES:** Forward invites from Perigean to CAIA A11ys (Sara or Terry)
```

**Comment by sara-amanda** [comment]
## Intake Received
Hi, @mattmarino-adhoc ! Just a quick note here to let you know that we received your intake ticket and it has been processed. 

## Next Steps
- [ ] Would your team be interested in doing a **pilot**, prior to your research? Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired.
- [x] For now, I put all-day **holds** on your dates.
- [ ] Do you happen to have **time slots for your dates** available that I can place holds on our [CAIA A11y Capacity calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York), in the meantime?

Looking forward to working with you again, Matt! 

cc: @coforma-terry

**Comment by mattmarino-adhoc** [comment]
Hi @sara-amanda, we would like to do an AT pilot prior to our research. We unfortunately don't have specific dates available for testing yet, but I can tell you as of right now I suspect we will start later than initially expected (just guessing right now, June 3rd seems more realistic). No matter what happens, we will have no testing on June 12 due to other team priorities that day. 

For the pilot, I believe any day next week/the beginning of the following week would work. 

Pre-pilot requirements:
* Let CAIA know what kind of AT use you hope to test with during your study
  - Screen readers (VoiceOver, JAWS, NVDA, Talkback)
 * Provide CAIA with your conversation guide, research plan, and the prototype(s) you intend to use during the study
  - [Research Folder with guides and plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Product/Form%20Status/Research) (Still being modified at the time of this posting)

Thanks for your help, and likewise, I'm excited about collaborating on this project!

cc: @jeana-adhoc @ajakabcin @tbaker1026 @allisonlu

**Comment by sara-amanda** [comment]
## Pilot Planning

Hi, @mattmarino-adhoc ! Thank you for the info.! Can you send over a few dates and times that work best for your team for the pilot, prior to testing on 6/3? 

> ### Pre-pilot requirements
>
> - Let CAIA know what kind of AT use you hope to test with during your study
>     - Screen readers (VoiceOver, JAWS, NVDA, Talkback)
> - Provide CAIA with your conversation guide, research plan, and the prototype(s) you intend to use during the study
>     - [Research Folder with guides and plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Product/Form%20Status/Research) (Still being modified at the time of this posting)

cc: @jeana-adhoc @ajakabcin @tbaker1026 @allisonlu
@coforma-terry @coforma-jamie @EvanAtCoforma @SarahKay8

**Comment by coforma-jamie** [comment]
This study is officially closed as of June 28, 2024:

> The plan is that if this participant calls back and can reschedule for tomorrow afternoon we’ll do it. But if we haven’t heard back by 10am est or if he can’t do it in the afternoon the study will be closed

**Comment by coforma-jamie** [comment]
## Jamie's findings

### Assistive tech
- P11 expressed a desire for VA.gov to have a dark mode toggle. They looked for on-page controls and were frustrated that there were none.
   -  “would love to see controls to change the background color, because it’s bright.”
   - Said the page wasn't accessible because “This page doesn’t have [any controls].” Says that it should be there, “there’s a lot of us [with visual impairments].”
   - P11 noted that blind veterans are sent a lot of paperwork that "they can't read, and throw it in the trash."
   - P11 talked about the time tax, disconnected systems at VA. I'm noting here that this can impact assistive technology users even more - navigating a website can take more time when you're using AT, which only increases the time tax.

## Usability
- P11 understood that their application was submitted
- P11 was confused by "received," and suggested that we use "pending review" instead
- P11 felt that the error message made them feel like "they did something wrong," and wanted a message that was specific and actionable.
   - “It says ‘action needed,’ but it doesn’t tell me what happened. It doesn’t tell me anything! This is useless to me.” “It doesn’t tell me what’s wrong. This page is a waste of my time, and a waste of the VA’s time.”
   - “It tells me there’s a problem with their system, so fix it, don’t tell me about it!”

**Comment by sara-amanda** [comment]
## User Research A11Y Feedback

### Assistive Tech Users

#### Screen Magnification 
- P9 - expressed an issue with the body text size, but the rest of the text on the site they do not have an issue with. 

#### Cognitive Processing
- P9: Confusion between the two cards: Claims and Appeals section vs. Benefit Applications and Other Forms section. 
    - > "In the beginning I couldn’t tell they were two different things."

#### Color/Contrast
- P9: **Color preference:** Confusion when trying to differentiate  the next steps/"show all steps" black and blue. 
    - > "Not sure if I am on stage one or stage two." 
    - > "I see the line there, but I am not sure." 
- P10: **Form Length:** Keep forms as short as possible. 
    - > "Keep them simple."

#### Equal Access
- P10: **Form Submission Goal**: User would like to submit forms themselves, and not need to contact a VSO.        
    - > “Keep my independence. Once you lose your vision that is the most important thing you want to do. … Just to be able to do forms, and a lot of times you don't want other people to know your business. Definitely have to keep your independence.”
- P16: **Vulnerability/Negative VSO Experience:** 2015 was likely the last time a form was submitted.
    - > "It was horrible, by me being totally blind, it was all paperwork, it wasn’t web-based. I had to get a VSO to help me do my paperwork. I think it was more of me, giving out my personal information to people, who I had no idea who they were." 
    - **_The process to the user was like reliving his four strokes, blindness and surgeries all over again._**


### Usability
#### Negative User Emotions
- P9: **Action Needed:** Me or You? User would like to know if it was user error:  Submission and failed, to see if it was on their end or not. 
    - > "Action needed is pretty clear." 
    - > "It is red, but it isn’t threatening."
- P10: **Error alert** - The error alert at the top of the page with the link to the form, made the user feel like they did something wrong. 
    - > "It is important for visually impaired users to know what they did wrong, so if it could let this user know at the top of the form you need to fix a, b and c, instead of making the SR user seek it out." 
    - > “Why? What did I do wrong? For me, being visually impaired, trying to find what part of the form is filled out wrong is kind of difficult. Like a lot of forms, they put an asterisk by what is wrong … but what would be easier is that the warning pops up, go to the link, then at the top of it if it says you forgot to, or this is missing, instead of scanning the whole application to find what is wrong.”
- P16: **Error alert:** It lets you know when you get that error, there was something that you probably didn’t do right. We got it on June 3 but we weren’t able to process it. We are letting you know something is wrong, so we can actually help you with this process. 
    - > "Form was submitted, there wasn’t enough information, if they call you it is pretty much nothing on their part, it may not be enough information for them to go to the very next step." 
    - **User is thinking it is something the user did or didn’t fill out.** 
    - “Action Needed” was read out. 
- **A11Y Feedback**: Respecting the user's effort with constructive feedback with visible error messages designed within close proximity to the error source, will help reduce cognitive load and negative user emotions. 

#### Signifiers
- P9: **Status Labels:**  Likes labeling of the statuses (IE) "reviewed" "received" 
- P16: **Status:** The user acknowledged understanding where the form was in the process and what next steps would be based on the labeling. 
    - > "Submitted to received you can know where it is at in the system. When I did mine, you were on standby waiting for someone to give you a phone call. This one, it gives you the steps so you know where it is going."
    - > "The link to review the steps, gives you a piece of mind and that is pretty much what veterans want." 
- P16: Link text reads: "What Your Form Status Means" 
    - Interesting that's the user is interpreting it as a list of steps at first review. 
    - It is a list of status names and definitions.

#### Positive User Emotions
- P16: **Ask VA:** User was impressed they could ask a question and provide useful links and phone numbers. 
    - > "Wow, then you can ask a question through Ask VA. You can actually chat and talk to an employee on the website and it gives you the website, so you aren’t looking for it."
- P16: **Self-Sufficient/Confidence Booster:** 
    - The user would rather get more information from the VA for what is going on that not, to help them be more self-sufficient. 
    - > "The way that y'all set this up makes me think...you know what, I can do this."

### Additional Notes
#### Prototype Issue
- P16: **CodePen** wasn't displaying correctly when the user clicked the “Check the status of your submission on MyVA” and it keeps pushing the user to the bottom of the page and there are a lot of links to go to. Prompted to go all the way up on the page. 
#### Screen Sharing Issue
- P16: **Low power mode** kicked the user out of screen sharing. 

#### Content Styleguide
- **Link Placement:** The team asked if the Ask VA link was in the right place and referenced that CAIA doesn't want embedded links in a paragraph. 
    - I provided the team with the following information and post-study conferred with CAIA Content and they confirmed this is best practice. 
        - [CAIA’s Content Styleguide](https://design.va.gov/content-style-guide/links)
            - > **Too many** embedded links can be distracting or overwhelming to people with traumatic brain injuries or other cognitive impairments.
            - > **In general,** put a link on a separate line to help it stand out. 
            - > **Exception**: Putting a link at the end of a sentence is OK if space is limited, like intro copy or alerts.

**Comment by sara-amanda** [comment]
## User Research 

### A11Y Feedback 
@mattmarino-adhoc  and @jeana-adhoc - please find our observations from the research in the two comments above from [Jamie](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83382#issuecomment-2197280243) and [myself](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83382#issuecomment-2197766336).  

#### Questions
If you have any questions, please let us know and we would be happy to expand upon any of the above. 

_Thank you for including CAIA in this study!_

cc: @mattmarino-adhoc @jeana-adhoc @coforma-jamie @NaomiPMC @SarahKay8
