### ISSUE TITLE
Qualitative Data Request for Outreach and Events

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-team#83397]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

02-13-2023

### Date Range End

05-17-2024

### Product Name(s)

Outreach Events

### Product Description

Outreach Events - listing of VA events and single event pages

### Survey URL(s), key term(s), case category or type

https://www.va.gov/outreach-and-events/events/

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

amanda.klausmeier@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Let me know if you have any questions. Thank you.
