### ISSUE TITLE
Improve Tracing of content sources 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#834]
Problem 
- it's difficult / impossible to trace specific markup on va.gov to specific source 

Goal 
- determine how to improve tracing in va.gov 

Possible tasks 
- use html comments to wrap markup from specific sources. at the very least indicate of it's from va.gov content, drupal cms, or react. for the drupal cms, indicating the template or other js helpers used could be helpful 
- understand the impact to prod performance. This would be good to have in prod for prod issue tracing. It shouldn't have an security implications since `vets-website` is open source.

**Comment by brandonrapp** [comment]
This work was included as part of the CMS Superteam work.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/2724
