### ISSUE TITLE
TeamSite docs are out of date

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#83412]
### Description
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43364 describes the necessary changes

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview#TeamSiteoverview-Considerationswheneditingandtestingtheallowlist

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS

**Comment by jknipes** [comment]
Hi @jilladams, thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps

**Comment by laucon** [comment]
I believe that all of this has been resolved on the document, [TeamSite overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview), and I _think_ that this ticket can be closed.

**Comment by jknipes** [comment]
Per comments above, work is done, moving to _Closed_
