### ISSUE TITLE
UX: Identify new icons on MHV landing page: Payments and Supplies

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#83415]
### User story

As a Cartography team member, I want to transition icons in the Payments and Supplies boxes to the new design system icons, so that we keep getting the benefit of the VADS.

### Notes
- [clarifying thread](https://dsva.slack.com/archives/C0NGDDXME/p1714582450407219?thread_ts=1714572472.637479&cid=C0NGDDXME) with design system team (Matt) - currently 6/17
- [Cartographers thread](https://dsva.slack.com/archives/C0NGDDXME/p1714582450407219?thread_ts=1714572472.637479&cid=C0NGDDXME) on options

Possible tasks:
- 

## Acceptance criteria

- Payments and Supplies render the new USWDS icons
- If necessary, check with any other teams whose products would be impacted by an icon switch
- Create an experimental design ticket for DST
- QA review
- A11y review

**Comment by fmccaf1** [comment]
For med supplies, [I created a Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1716493530606509) showing our options and asked directly for Kaitlin and Kristen's okay.

**Comment by fmccaf1** [comment]
Resolution from thread on med supplies: let's not add any new icons that other teams don't need. We might not still need them after the LP redesign. So, for med supplies, we'll go with the medical services icon (briefcase with +).

**Comment by fmccaf1** [comment]
[Slack thread created in the platform design system channel to ask about process for identifying icons we plan to use on the LP and within secondary nav.](https://dsva.slack.com/archives/C01DBGX4P45/p1716573520965869)

Matt Dingee reached out within that thread and asked me to file an [experimental design ticket, which I did.](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2874)

**Comment by wesrowe** [comment]
@fmccaf1, do you think the experimental design process will get these icons into the design system pretty quickly? I feel like the `pill` one went pretty quickly last week...

**Comment by dcloud** [comment]
FYI, the `attach_money` dollar sign is available for the Payments, and so is `medical_services` for the Supplies section… [my PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30012/files) is currently waiting on a fix for the pill icon, but wlll have screenshots on that PR once it is

**Comment by fmccaf1** [comment]
@wesrowe as stated in standup today I don't think this is holding up our work of implementing. I think it's more of a process for documentation, so it shouldn't hold up anything (as far as I'm aware)

**Comment by fmccaf1** [comment]
Actually wondering if we can close this. I asked for an async review; it doesn't seem there's any reason to track that through this ticket. I'll close.
