### ISSUE TITLE
Fix test coverage

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#83418]
# Overview
Our test coverage has dropped considerably since re-launch. 
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report

# Tasks
Fix the test coverage

**Comment by ToddWebDev** [comment]
The Frontend Support Dashboard isn't generating the correct coverages for Pensions. When the Pensions unit test coverage report is ran the actual results are:
| Statements | Branches | Functions | Lines |
| --------- | --------- | --------- | --------- |
| 91.37% | 81.33% |95.26% | 91.15% |

**Comment by ToddWebDev** [comment]
I'm closing this issue noting that the github action is not accurately reporting the coverages for the Pensions app. Pension unit test coverage percentages are above thresholds.
