### ISSUE TITLE
Design and Research Activity Log 

### ISSUE THREAD

**Issue by JKG199** [department-of-veterans-affairs/va.gov-team#83419]

**Comment by JKG199** [comment]
The purpose of this documentation document is to enable the simplest and more clear way for all relevant stakeholders, customers and partners to review design work that has been done over the course of the IPP lifecycle. This log will serve as a readme to be able to highlight the work that was done and the value add. 

AC's 
- [ ] Create readme outline in the form of a google doc 
- [ ] Review framework internally to ensure that the framework of this documentation makes sense and aligns with documentation needs 
- [ ] Populate readme outline with all design and research items that exist within the Figma documentation spreadsheet
- [ ] Populate readme outline with all content within Figma documentation spreadsheet 
- [ ] Review all content internally and ensure that readme documentation is ready for final review 
- [ ] Review all links and ensure that documentation links are all clickable

**Comment by JKG199** [comment]
In progress and should be ready to review by EOD Monday.

**Comment by skirkman16** [comment]
Updated value sections yesterday and tagged @CarlDickerson and @SophiaPhilipMO to fill in final missing dates

**Comment by SophiaPhilipMO** [comment]
Uploaded content to Github
