### ISSUE TITLE
Sidekiq: Hold a meeting with regards to further automation about queue exhaustion.

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#83426]
- https://github.com/sidekiq/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional

Per our kick off, we believe that we have never seen a job actually enter queue exhaustion, and further iteration of process would involve additional table structure and development. We want to align ourselves with the rest of the VA stakeholders and team by coming together to discuss how each team is handling these guidelines with respect to having an automatic failsafe automation for resubmissions and how it will impact our future iteration.

**Comment by mjknight50** [comment]
@scottsdevelopment What is the action item here?  To have a meeting?

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/83426?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by mjknight50** [comment]
Started a slack thread here on this:
https://dsva.slack.com/archives/C053U7BUT27/p1717170538451919?thread_ts=1717170529.248399&cid=C053U7BUT27

**Comment by mjknight50** [comment]
Meeting tomorrow (6/5) on this.

**Comment by mjknight50** [comment]
After discussions with @tblackwe and @shaunburdick, we should handle sidekiq queue exhaustion as follows:
If the exhaustion occurs within ITF:
1.  Log to intent_to_file_queue_exhaustion
2. Raise a watchtower event

if the exhaustion occurs outside, for example in the async job to submit, use a watchtower event to surface this.
