### ISSUE TITLE
Investigate 'parameter missing' errors from sessions controller where it appears authn is not getting passed in for a custom call

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#83436]
Starting May 15 or so, we appear to have an uptick in 'parameter missing' errors, as seen in this Sentry: http://sentry.vfs.va.gov/organizations/vsp/issues/79553/?project=3&query=is%3Aunresolved+parametermissing&statsPeriod=14d

I think this might be from a higher instance of people logging in with VAPIV method. Perhaps this is correlated with MHV Terms of Use?

https://vagov.ddog-gov.com/logs?query=%40http.url%3A%22%2F%2Fv1%2Fsessions%2Fcustom%2Fnew%3Fcsp_type%3D33%26csp_method%3DVAPIV%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1714683601162&to_ts=1715979601162&live=true

**Comment by joeniquette** [comment]
We are not going to support PIV logins directly. We are deferring to the CSP to handle this per Tom and Samara.
