### ISSUE TITLE
Implement Script to Validate existing Claims

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#83433]
Follow-on ticket to #82149

Write a script that iterates over all Form526Submission submissions from last 30 days
For each form, submit the form data to the validate endpoint created from ticket #82149 and record result

Output of the script should be a CSV file that contains the form 526 submission id, the job success indicator of the original submission, the validate value, and if validate is false, the reason for failed validation

**Comment by SloopKoning** [comment]
I have merged the work done on this ticket within developer branch `dbx-83433` into the developer branch `dbx-82149`.

There is a draft PR that combines the work from both tickets.[
](https://github.com/department-of-veterans-affairs/vets-api/pull/16887)

**Comment by SloopKoning** [comment]
While doing preliminary manual testing of the new `form_content_valid?` method in the From526Submission model, I ran across an error in the `Form526ToLighthouseTransform#transform` method.

```
transform_service = EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform.new
body = transform_service.transform(form['form526'])
```

Using a 526 test instance which had a treatment entry without a `startDate` element caused the transform method to raise an exception.

The test data used was create within my local environment my running both the frontend and backend processes together.  I entered the form 526 via the front end process.  I only entered the required fields.   This `startDate` value must not have be a required field at the time.

This needs to be investigated.  It is outside the scope of this ticket.

**Comment by SloopKoning** [comment]
@tblackwe  is this consistent with what you were thinking?

I have a framework for the rake task that makes use of this new capability.  rake form526:lh_validate[start_date,end_date]` where end_date is optional.  Both dates are in the format YYYYMMDD.

Currently this task compares the parameter dates against `updated_at` for the `form526_submissions` table.

The new `form_content_valid?` method in the model is run against each database record within the date range.  Currently there is not specific report format.  I'm unsure whether to present a result for each record or just those records that failed along with the reason why they failed.

**Comment by SloopKoning** [comment]
Still need specs for automation testing.

Both Scott and Thomas have received line by line walk troughs of the new code.

**Comment by freeheeling** [comment]
[Results](https://dsva.slack.com/archives/C04U3EDUR3M/p1718298983466739?thread_ts=1718297224.954319&cid=C04U3EDUR3M) of executed script on Staging.

**Comment by freeheeling** [comment]
@tblackwe Can this ticket be considered Done now that it has been executed in production?

**Comment by tblackwe** [comment]
Yes, can move to done in sprint
