### ISSUE TITLE
[Design] Zero results, search again, select different filters

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83442]
## Tasks

- [x] If a user applies too many filters, it's possible there are no results of providers. In that scenario, we need a design that communicates there's no providers, and instructions on how to start over. E.g., select different filters, or maybe a button that resets all filters. 

Explorations: [Figma Link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1873-25012&t=mITPRGZNow5yqcjX-1)

Example for reference:

<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmtRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5b0f7649885e5dd4ca4cd9b948b8f6610c685a0/image.jpeg" alt="image.jpeg" />

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/83442?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by benbrasso-agile6** [comment]
@Cieramaddox looked like this was close to being completed. @cgednalske are you validating? 

Could you add it to the MVP scope page when complete?

**Comment by cgednalske** [comment]
Yep! It's already [on the MVP scope page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2156-28715&t=pLCRFXvC2hy0aIMx-1) (though prob also needs to be added to specs). And unless that's the wrong version, it's validated as well 👍

**Comment by benbrasso-agile6** [comment]
Let me look

**Comment by benbrasso-agile6** [comment]
Oh that's fine, Cierra is doing the doings 👍
