### ISSUE TITLE
Fix sorting

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#83449]
## Description
Navigating to https://staging.va.gov/health-care/file-travel-claim/, selecting "by oldest" from the drop down and clicking "sort" does not appear to sort the claim cards. I would expect to see the claim cards be sorted from oldest to newest, and be able to sort from newest to oldest.

## Acceptance Criteria
- [ ] Go to https://staging.va.gov/health-care/file-travel-claim/
- [ ] Select "Show appointments in this order" -> `oldest`
- [ ] Click "Sort"
- [ ] Items should be sorted in ascending order by claim modified on datetime - oldest to newest
- [ ] Select "Show appointments in this order" -> `most recent`
- [ ] Click "Sort"
- [ ] Items should be sorted in descending order by claim modified on datetime - newest to oldest

## Demo
- Demoable? Yes
- How? Follow AC above
- Impact? Small demo, fixing bugs in prep for launch

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by hinzed1127** [comment]
I think this is getting resolved in #81888, but we'll need to validate in dev/staging once it's deployed first

**Comment by athifw** [comment]
Solved as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/84573
