### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#83448]
## Description
Our test user has many (145) claims. Actual users won't have quite that many, but some Veterans are likely to have 10+. In order to provide a good experience for Veterans with more than just a few claims, we should add pagination to the bottom of the status page.

## Acceptance Criteria
- [ ] Go to https://staging.va.gov/health-care/file-travel-claim/
- [ ] Scroll to the bottom of the list of claim cards
- [ ] Click the link labeled `2` in the pagination section
- [ ] See that the next page of claims is loaded
- [ ] See that the claims are loaded while preserving the order selected on the page
  - [ ] Default - 2nd page of claims is loaded in descending order on the page, and in comparison to the previous and next pages
  - [ ] Ascending - 2nd page of claims is loaded in ascending order on the page, and in comparison to the prev and next pages
- [ ] Ensure the `next` and `previous` buttons work the same way as above

## Demo
- Demoable? Yes
- How? Follow AC above
- Impact? Small demo, solidifying design in prep for launch

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by hinzed1127** [comment]
PR link: https://github.com/department-of-veterans-affairs/vets-website/pull/30269
