### ISSUE TITLE
Allow filtering by date range

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#83450]
## Description
We noticed from research that some Veterans wanted to be able to filter by date range. In this case, we should allow filtering by a valid date range.

A valid date range is any time in the past to the present. There is no reason to allow future dates to be selected, but it is not a problem if the date picker allows this by default.

### Short range to present
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] Select start date: 1 day ago
- [ ] Select end date: today
- [ ] See that claims beyond 1 days ago do not appear in the list
- [ ] See that claims within the date range are shown in descending order by modified date

### Medium range to present
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] Select start date: 45 days ago
- [ ] Select end date: today
- [ ] See that claims beyond 45 days ago do not appear in the list
- [ ] See that claims within the date range are shown in descending order by modified date

### Long range to present
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] Select start date: 10 years ago
- [ ] Select end date: today
- [ ] See that claims beyond 10 years ago do not appear in the list
- [ ] See that all claims for test user Nolle Barakat are present
- [ ] See that claims within the date range are shown in descending order by modified date

### Sort order is preserved
- [ ] Sort the claims in ascending order by modified date
- [ ] Add a medium term date range (~45 days)
- [ ] See that claims within the date range are shown in ascending order by modified date
- [ ] Clear the filter
- [ ] See that all claims are shown in ascending order

### Cross filtering is preserved:
***To be tested when Filter by Status (department-of-veterans-affairs/va.gov-team#83451) is complete***
- [ ] Select a status from the status filter
- [ ] See that only claims that match the status are shown
- [ ] Select a date range:
  - [ ]  Starts: claim with median (middle-most) modified on date
  - [ ]  Ends: claim with most recent modified on date
- [ ] See that only claims within the date range that have the selected status are shown (no filter overwrite)
- [ ] Clear the status filter only
- [ ] See that only claims within the date range with _any_ status are shown (no clear clobber)

## Demo
- Demoable? Yes
- How? Follow AC above
- Impact? Shows research-driven product

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by micahtaylor** [comment]
[Design ticket in progress](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/zh/318)

**Comment by micahtaylor** [comment]
Design ticket closed
> [Updated after CAIA and KM feedback](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1708602401825/9786edc7ee2a5b6c4efd1a895d067a07ae2a7f27?wid=0-1717770928839). 
> This design is where we will start but based on upcoming changes to how filters will be changing with Appointments we will likely revisit

**Comment by hinzed1127** [comment]
@kjduensing [replied to your mural comment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1708602401825/9786edc7ee2a5b6c4efd1a895d067a07ae2a7f27?sender=danhinze7235) with some thoughts on how that design could be abstracted out:

**Comment by hinzed1127** [comment]
Current WIP on filtering and sorting with date ranges added in
https://www.loom.com/share/bdb43d8fbc94486280a376d1a4355eed?sid=e4663b17-b0ba-476e-b109-02232791e98d

**Comment by hinzed1127** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30530)
