### ISSUE TITLE
Redirect Request: Decision Review pages

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#8345]
### Description
As decision review pages were updated, page titles and urls have changed, and we require the following two redirects:

- [ ] old url https://www.va.gov/disability/file-an-appeal/ 
new url: https://www.va.gov/decision-reviews/legacy-appeals/

- [ ] old url https://www.va.gov/disability/file-an-appeal/request-priority-review/
new url: https://www.va.gov/decision-reviews/legacy-appeals/priority-review/

### Requestor team info
Public Websites / Laura Walsh

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
This has been reviewed and is ready to implement. 

@ncksllvn There is an old vets URL (www.vets.gov/disability-benefits/claims-appeal/) that currently redirects to this page, traffic is very low, so I do not see the need to update that so I did not add it to the above list.

**Comment by mnorthuis** [comment]
@stephorkandatx @ncksllvn Just want to call this one out, because the old URLs are serving up 404s, so the sooner we can implement these redirects the better.  Thank you!

**Comment by ncksllvn** [comment]
Sorry, should have prioritized this, but I just opened a PR. Is Monday okay, or should I try to get this going tonight?

**Comment by mnorthuis** [comment]
@ncksllvn Today is good :-)

**Comment by stephorkandatx** [comment]
I tested the old URLs to confirm that I am redirecting to the new URLs per the ticket's details
