### ISSUE TITLE
Allow filtering by status

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#83451]
## Description
We noticed from research that some Veterans wanted to be able to filter by statuses. In this case, we should allow filtering by multiple statuses at once: "denied + in progress".

### Available status filter options
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] View the options in the filter
- [ ] See that the statuses available to filter by are only those present in the user's list of claims.

### Single status filter
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] Select 1 status from the filter
- [ ] See that only claims with that status are shown in descending order by modified date

### Multi-status filter
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] Select 2+ statuses from the filter
- [ ] See that only claims with any of the chosen statuses are shown in descending order by modified date

### Clear status filter
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] Select 1+ statuses from the filter
- [ ] See that only claims with any of the chosen statuses are shown in descending order by modified date
- [ ] Clear the status filter
- [ ] See that all claims are shown in descending order by modified date

### Sort order preserved
- [ ] Sort the claims in ascending order by modified date
- [ ] Add 1+ statuses from the filter
- [ ] See that only claims with the chosen statuses are shown in ascending order by modified date
- [ ] Clear the filter
- [ ] See that all claims are still shown in ascending order

### Cross-filter preserved
***To be tested when Filter by Date (department-of-veterans-affairs/va.gov-team#83450) is complete***
- [ ] Select a date range from the date range filter
- [ ] Select 1+ statuses from the status filter
- [ ] See that only claims with modified dates within the chosen date range and that have the chosen statuses are shown

## Demo
- Demoable? Yes
- How? Follow AC above
- Impact? Shows research-driven product

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by micahtaylor** [comment]
[Design ticket in progress](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/zh/318)

**Comment by micahtaylor** [comment]
Design ticket closed
> [Updated after CAIA and KM feedback](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1708602401825/9786edc7ee2a5b6c4efd1a895d067a07ae2a7f27?wid=0-1717770928839). 
> This design is where we will start but based on upcoming changes to how filters will be changing with Appointments we will likely revisit
