### ISSUE TITLE
Remove unused `dsva-vetsgov-stag` Redis cluster

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8346]
The `dsva-vetsgov-stag` is unused. It has ~4 connections (i'm assuming prometheus and similar probes), no new data for past two weeks, and is unreferenced in the devops repo.

Its time to remove it and any related statistics/graphs/etc

**Comment by wyattwalter** [comment]
All cleaned up 👍
