### ISSUE TITLE
Yellow Ribbon Post-MVP

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8347]
Part 2, Iteration and Continuation on the MVP experience for Yellow Ribbon.

Specific details to be added.

How might we make the Yellow Ribbon (YR) participating schools table information more useful for Veterans and more easily kept accurate by stakeholders?

## Goal
- Bring YR participating school information into the benefit hub as a more dynamic, user-friendly content than the current experience of 50+ manual table pages. 
- Improve UX for YR tables so that users can easily find info they're looking for
- Reduce the level of effort for stakeholder to keep YR data up-to-date on Veteran-facing page

**Comment by MarciMcGuireGCIO** [comment]
Closing; all items listed are complete.
