### ISSUE TITLE
Competitive Analysis

### ISSUE THREAD

**Issue by UXCamG** [department-of-veterans-affairs/va.gov-team#83483]
- [x] Identify 5 competitors in the government space 
- [x] Review the competitors User Interface 
- [x] Review the Users Journey of the competitors from End to End. 
- [x] Determine if the competitor has screensharing capabilities 

## Acceptance Criteria

 - [x] **Scenario: Identify 5 competitors in the government space**
  - Given a list of 5 competitors is identified
  - When the list is reviewed
  - Then all 5 competitors should be relevant to the government space
  
- [x] **Scenario: Review the User Interface of the competitors**
  - Given the User Interfaces of the competitors are reviewed
  - When the review is completed
  - Then the design and layout of each competitor's UI should be analyzed
- [x] **Scenario: Review the Users Journey of the competitors from End to End**
  - Given the end-to-end user journeys of the competitors are reviewed
  - When the review is completed
  - Then the overall experience and flow of each competitor's platform should be assessed
- [x] **Scenario: Determine if the competitor has screensharing capabilities**
  - Given the screensharing capabilities of the competitors are determined
  - When the determination is made
  - Then it should be clear whether or not each competitor offers this feature

**Comment by ATMiddleton** [comment]
Draft competitive analysis 
https://docs.google.com/document/d/1QvD_hUriOCpzefcPt77awYIGxCHJOCym49MaadLtYlg/edit
