### ISSUE TITLE
PROD: Exhaustion failures in its Sidekiq queued job

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#83487]
Production issue reported over the weekend. 
https://dsva.slack.com/archives/C0667PCPVLM/p1716134442602049

**To Do**
- [ ] Determine cause of failure
- [ ] If possible, rerun the job

**Comment by wayne-weibel** [comment]
claim_id: 9021819
`Invalid Document: ["Document exceeds the page size limit of 21 in. x 21 in."]`
The claim has 7 attachments, one of which is failing the validation.  BUT the option override for the size is not being applied - the actual size should be 78 x 101

**Comment by wayne-weibel** [comment]
<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c23aa7d3003c6ddc31257d955e45d26ed5d4d9fd/image.png" alt="image.png" />
