### ISSUE TITLE
Review breadcrumb spacing on Profile 2.0

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#8348]
## Description

The white space provided for the breadcrumb in the profile seems to be excessive.  We need to find out if this is standard or if we can change it. 

## Background

Epic #5346

## Design 

![Screen Shot 2020-04-23 at 10.14.12 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/721e98b1-2755-4ebd-a0f5-611c64bd279d)

## Tasks

- [x] Look into breadcrumb spacing
- [x] Let Tressa know if it's possible to change

**Comment by sanlouise** [comment]
@tressaellen could you confirm that this ticket is no longer needed since I merged https://github.com/department-of-veterans-affairs/vets-website/pull/12452? I attached screenshots to the PR for your comparison. Thank you!

**Comment by tressaellen** [comment]
@sanlouise this looks great - I'll go ahead and close this.
