### ISSUE TITLE
AWS Access for [Keith Adkins]

### ISSUE THREAD

**Issue by keithdadkins** [department-of-veterans-affairs/va.gov-team#83495]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Keith Adkins

### Your Email

keith.adkins@adhocteam.us

### Team, Role, and Company of the target individual

Platform Security

### Product Manager (PM) name and email

Kelly Argyros Kelly.argyros@adhocteam.us

### Product Owner (PO) name and email

Ray Wang gang.wang@va.gov

### Desired AWS Access

Permissions needed for DevOps/Infrastructure contributions. (Hector Barreto's permissions should suffice)

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

I already have my PIV 
![IMG_3594](https://github.com/department-of-veterans-affairs/va.gov-team/assets/539260/9a8e6214-209b-4805-94ae-68f8589b0ef1)

### Additional Notes

I am assigned to the Platform Security team but will be a contributing infra engineer on the Platform Infrastructure team for the foreseeable future. The Infrastructure team PM is Nate Peterson.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Found in both Atlas as well as Platform Team Roster under "Security Team"

**Comment by ph-One** [comment]
I have provided credentials as well as details surrounding next steps for @keithdadkins AWS access. Closing.
