### ISSUE TITLE
Determine long term plan for maintaining graphql query 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#835]
Problem 
- the current graphQL query may not be scalable long term 
  - it pulls all of the pages in a single query (no handling of node limits)
  - the [master query](https://github.com/department-of-veterans-affairs/vets-website/blob/920b2f4dd91f5f00d4adc3874c06de7d2c3b93a4/src/site/stages/build/drupal/graphql/GetAllPages.graphql.js#L40-L52) has several specific page references (the content model is not generalized for future pages 

Goal
- Determine if there is a way to abstract the way the graphQL query is maintained / the content model is updated. 

Possible tasks 
- research graphQL best practices 
- consider long term migration goals (this may require DSVA conversations)
- document risks of current approach

**Comment by brandonrapp** [comment]
This work was covered as part of the CMS Superteam work.
