### ISSUE TITLE
SM "What to know" updates for phase 1 portal integration

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#83531]
Updates needed to "what to know as you try out this tool" content in SM for phase 1 portal integration.

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714596810081/8bbb4c2a69d1dec47ce627f063121e2bca4e1b50?sender=9d982f8a-ca7a-4502-af16-c3f3bfdbf294

**Comment by laurwill** [comment]
Hi @kfink24 , I left a comment in the linked Mural — wondering if we can tuck the bullets about new features in an additional info component to avoid adding too much length to the landing page. See what you think!

**Comment by kfink24** [comment]
@laurwill We can close out this ticket, no longer needed!
