### ISSUE TITLE
[FE] My VA Ben App Drafts: Debug issues found from SiP testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#83536]
## Background
While testing the SiP configuration enhancement today on staging we found some issues that caused the My VA page to not load after a test was conducted. Screenshots below of console errors:
![2024-05-20_12-21-24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/0f8dc9e8-7598-48c2-a3de-6f130af4aa0c)

## Tasks
- [ ] investigate errors
- [ ] debug/determine solution
- [ ] Implement fix
- [ ] Re-test

## AC
- issues are resolved

**Comment by allisonlu** [comment]
@ajakabcin 

I set the estimate to 2 points yesterday, and I have a PR open for an update so majority of the work is completed.

For sprint 37, I'll give point it as a 1!

**Comment by allisonlu** [comment]
closing this ticket as @ajakabcin and i tested with Tricia today with success!
