### ISSUE TITLE
Analytics Reporting Request for Lacey

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8354]
# Metrics Reporting Request

## Description

**Requester**: @LEHigley 
    
**Report Purpose**: VA Communications
    

## Timeframe for Analytics Requested

Show the before & after the Covid outbreak -(in line the Covid dashboard) using March 13th as the before/after, since March 13th was the day it was declared a national emergency.

## Analytics to Track Down

- Increase in traffic to VA.gov
- Increase in new accounts
- % increase in Veterans now accessing online healthcare tools than prior to pandemic
- Total number of telehealth appointments

## Which Product Questions are you trying to answer?
How did the Covid outbreak affect VA.gov traffic, new users, and veteran access to online & telehealth services?

## Additional Comments
**Deadline:** Have the data visualized, QA'd, and delivered to Lacey by COB Tuesday, April 28th.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Some of these already exist in the Covid dashboard:

New Users & Total Users:
![image](https://user-images.githubusercontent.com/48964695/80149547-d8efe880-8584-11ea-9f2d-e696bd072609.png)

**Comment by joanneesteban** [comment]
### Metrics

- [x] [Increase in traffic to VA.gov](https://va-gov.domo.com/page/-100000/kpis/details/955415897)

![image](https://user-images.githubusercontent.com/48964695/80431757-4c189800-88c0-11ea-8827-1cc486c2eed0.png)

Mar 13-Apr 26, 2020: 513,747.5 avg page views
Jan 13-Feb 26, 2020: 466,579.4 avg page views
Increase of 47,168 

---
- [x] [Increase in new accounts](https://va-gov.domo.com/page/1872052027/kpis/details/1192542957)

![image](https://user-images.githubusercontent.com/48964695/80430985-3efaa980-88be-11ea-9a77-8d1c81bd8e8a.png)


---
- [ ]  % increase in Veterans now accessing online healthcare tools than prior to pandemic (need this number, @jonwehausen or @bsmartin-ep )

---
- [ ] semi-check? [Total number of telehealth appointments](https://dsva.slack.com/archives/C0106UMLKU1/p1588000287285800)

More than 516,700 tele-mental health encounters in FY20 - 35,500 more than in FY19

---

@amycesal will need to be visualized on a PDF or PPT (we can probably just export the charts from Domo, but if you think there's a better way to show these!)

**Comment by jonwehausen** [comment]
@joanneesteban @amycesal 

Just shared a dashboard for this request. The chart I put on there for the health care tools has the URLs of several of the tools off the main /health-care hub page. I moved over the two you had in the ticket @Joanne. PDF Export looks to be functioning if that's our output. Let me know what other cleanup you guys need on this data -- Lines indicate User volume for those pages

**Comment by joanneesteban** [comment]
[Dashboard](https://va-gov.domo.com/page/349560204) & PPT sent to Lacey EOD 4/28/20.

Thanks, everyone!! 🙌🏼
