### ISSUE TITLE
Changes to Form Submission page to reflect changes from 79210 and 79212

### ISSUE THREAD

**Issue by maddiefritz** [department-of-veterans-affairs/va.gov-team#83549]
Through various reviews of the Clarify medical evidence request ticket ([79210](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/79210)) and Clarify dependents' assets questions ([79212](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/79212)), several copy changes have been necessary to the Form Submission page. These changes ensure a more comprehensive and seamless form application process.

### To do
Ensure language on Form Submission page aligns with changes recommended in 79210 and 79212. 

### AC
- Get sign off from stakeholders
- Validate any PDF schema changes
- Migrate any in-progress forms
- Get sign off from design once in staging
- Update product guide

**Comment by matt4su** [comment]
Closing as the work reflected here is is capture in the [clarify medical evidence and dependent asset tickets
