### ISSUE TITLE
Properly Parse MAP HTML errors

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#83553]
MAP STS returns HTML errors for a certain class of errors, and we don't currently parse these properly. One example is the following error:

```
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
</body>
</html>
```

We should figure out a mechanism to properly parse these, it would be good to extract the message properly, although that might be difficult since this is HTML

https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20%40http.path_group%3A%22%2Fsts%2Foauth%2Fv1%2Ftoken%22%20status%3Aerror%20%40error.message%3A%22Net%3A%3AReadTimeout%20with%20%23%3CTCPSocket%3A%28closed%29%3E%22&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=metadata&traceQuery=&view=spans&start=1716155661411&end=1716328461411&paused=false

**Comment by bramleyjl** [comment]
This is covered in https://github.com/department-of-veterans-affairs/va.gov-team/issues/83081, closing.
