### ISSUE TITLE
Update 10-7959c base URL 

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#83567]
As a user, I want the root url of the CHAMPVA/OHI application to be `va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c` so that I have a full context of where I am in the CHAMPVA process when I navigate to VA.gov.

Also these changes _(Note: still need to review/finalize as there are probably more changes based on the recent copy updates):_ 

- https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/medicare-class --> change to medicare-plan

Acceptance criteria
- Base URL for 10-7959c is `va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c`
- Follow [GH guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/champva-ohi-7959c.md) for breadcrumb and url specific to this form
- URL change is visible on staging

**Comment by michaelclement** [comment]
Work is done in these two PRs ([first](https://github.com/department-of-veterans-affairs/vets-website/pull/30891), [second](https://github.com/department-of-veterans-affairs/content-build/pull/2188)). Waiting on:

- [ ] Team approval 
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 @baltes This change is now live [here](https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/) and ready for review.

**Comment by michaelclement** [comment]
|URLs|
|-|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/applicant-info|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/applicant-identification-info|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/applicant-mailing-address|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/applicant-contact-info|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/applicant-gender|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-ab-status|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-plan|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-pharmacy|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-a-carrier|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-b-carrier|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-ab-upload|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-d-status|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-d-carrier|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/medicare-d-upload|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-status|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-plan|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-medigap|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-info|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-type|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-prescription|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-eob|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-sob|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-upload|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/insurance-comments|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-plan|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-medigap|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-info|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-type|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-prescription|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-eob|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-sob|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-card-upload|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/secondary-insurance-comments|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/supporting-files|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/consent-mail|
|/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/form-signature|

**Comment by marywang2** [comment]
Noting that the original ticket was [here](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/82026).
