### ISSUE TITLE
Bug on Program of Comprehensive Assistance for Family Caregivers page: Wrong link

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8356]
## What happened?

The link to CHAMPVA is pointing to the wrong page.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b96352ea-bfbf-410e-a685-fcef694de12a)

## Specs:
- Device: All
- Browser: All
- Test User _(if applicable)_: n/a

## Steps to Reproduce
- URL: https://www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/
- Test User _(if applicable)_: n/a

## Desired behavior
The highlighted link should be pointing to this page: https://www.va.gov/COMMUNITYCARE/programs/caregiver/index.asp

## Acceptance Criteria
- [ ] CHAMPVA link is pointing to this page: https://www.va.gov/COMMUNITYCARE/programs/caregiver/index.asp

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Stakeholder noted that this link had not been updated. I told them we'd update for tomorrow's deploy. If you have any questions, please let me know!

FYSA @stephorkandatx

**Comment by RLHecht** [comment]
Link changed on page and moving to validate. Will close when live after next deploy.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much, @RLHecht!

**Comment by AnneHurley** [comment]
Thanks, @RLHecht

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket!
