### ISSUE TITLE
SOCKS access for Michael Skinner

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-team#83561]
### Your Name

Michael Skinner

### Your Email

michael.skinner@agile6.com

### Your GitHub Handle

Agile6MSkinner

### Your Role and Team

Product Manager on Sitewide Facilities

### Product Manager (PM) name and email

Michael Skinner - michael.skinner1@va.gov

### Product Owner (PO) name and email

Michelle Middaugh - suzanne.middaugh@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWlZxKkleTb9sqGqEZWpomfDqHPDkAZ63fMF64zt+SN truehoax@SkinnerM-A

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/167716994/39db7d18-3425-4f65-b9c2-6742d056cb30)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
Access granted - wait about 8 minutes then socks should work.

**Comment by Agile6MSkinner** [comment]
I had to generate a new key without a passphrase. I have edited it into the ticket.

**Comment by Agile6MSkinner** [comment]
Pasted the wrong key last time. Try again.

**Comment by hgbarreto** [comment]
@Agile6MSkinner - Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
