### ISSUE TITLE
Spike - 10-7959f-1: update copy for review page section headers

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83562]
URL: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/

- Review page: update section header (and subhead) copy to reflect latest design - follow the 'expanded' design to view subheads

<img width="100" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3I0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8215813678152651b0cd3fe2eb24994e3c8e11d2/Screenshot%202024-05-20%20at%208.37.52%E2%80%AFPM.png" alt="Screenshot 2024-05-20 at 8.37.52 PM.png" />

Figma link: https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?node-id=726-21596&t=TGjWUcWIDEWQadtF-0

**Comment by reiting** [comment]
@marywang2 should we tag this for sprint 18?

**Comment by marywang2** [comment]
@reiting going to put this in backlog for now.

**Comment by reiting** [comment]
This PR is in team review. <img width="721" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1dOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2586068846e2d324cf4def173c36830abd7d5bf/Screenshot%202024-06-24%20at%202.51.38%E2%80%AFPM.png" alt="Screenshot 2024-06-24 at 2.51.38 PM.png" />

**Comment by reiting** [comment]
Now in platform review.

**Comment by reiting** [comment]
This was approved and merged. Should be on staging soon.

**Comment by reiting** [comment]
@marywang2 this is in staging.

**Comment by marywang2** [comment]
@brian-wilke fyi - for your review. I am going to close but pls let me know of any comments.
