### ISSUE TITLE
FE | Military Information | incorporate periodOfServiceTypeText into military info page 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83581]
## Background 
One of the recommendations from our research that we can safely move forward with is incorporating `periodOfServiceTypeText` 

We should be able to use one of the military information figma files ([maybe the one we tested with](https://www.figma.com/design/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?node-id=10-11980&t=GhzyR35mST7YqVuM-4)) to display the "active duty" "inactive reserves" etc

## Depends on
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83780

## Tasks 
- [x] confirm which treatment of the myriad we have is the best 

## Acceptance Criteria 
- [ ] the military information page has the period of service type text

**Comment by mtcA6** [comment]
@adamwhitlock1 could you point this? 

Chatted with Chante and she thinks we should move forward with this update and then we could close out the military history epic and if/when the IES ILER stuff resurfaces we can create a new epic and a track that work separately. 

cc: @ACParker89

**Comment by adamwhitlock1** [comment]
I think we will need to discuss this further before I can point it. 

The `periodOfServiceTypeText` does not exist within the current service history response that we have in production, and I think that came from the military service profile endpoint that Tom had used to get the expanded info.

We only have this information available on each service history entry currently:

``` js
{
  branchOfService: 'Ait Force',
  beginDate: '2009-04-12',
  endDate: '2013-04-11',
  personnelCategoryTypeCode: 'V',
  characterOfDischargeCode: 'A',
}
```

**Comment by mtcA6** [comment]
@adamwhitlock1 you able to toss some points on here?

**Comment by tpharrison** [comment]
@adamwhitlock1 

A period service type will show on a service episode, but not on an academy episode (the fields will be null).

Here are the period service type values for reference...

| Code | Text
| ---- | ------------------------------------------------------------ 
| A    | Active duty member                                           
| B    | Presidential Appointees of all Federal Government agencies   
| C    | DoD and Uniformed Service civil service employee, except Presidential appointee 
| D    | Disabled American veteran                                    
| E    | DoD and Uniformed Service contract employee                  
| F    | Former member (Reserve service, discharged from RR or SR following notification of retirement eligibility)
| H    | Medal of Honor recipient                                     
| I    | Non-DoD civil service employee, except Presidential appointee 
| J    | Academy student                                              
| K    | Non-appropriated fund DoD and Uniformed Service employee (NAF) 
| L    | Lighthouse service                                           
| M    | Non-federal Agency civilian associates                       
| N    | National Guard member                                        
| O    | Non-DoD contract employee                                    
| Q    | Reserve retiree not yet eligible for retired pay ("Grey Area Retiree") 
| R    | Retired military member eligible for retired pay             
| T    | Foreign military member                                      
| U    | DoD OCONUS Hires                                             
| V    | Reserve member                                               
| W    | DoD Beneficiary, a person who receives benefits from the DoD based on prior association, condition or authorization, an example is a former spouse 
| Y    | Service affiliates                                           
| DVN  | DoD provided a NULL or blank value                           
| DVU  | DoD provided a value not in the reference table              
| CVI  | Value is calculated but created an invalid value             
| VNA  | Value is not applicable for this record type

**Comment by mtcA6** [comment]
@tpharrison @adamwhitlock1 weird there isn't an "inactive" do we have the right field selected?

**Comment by mtcA6** [comment]
should we use the military service episodes instead? 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/1d6c125a-1a17-4aba-81d1-0f4d2fb490db)

**Comment by tpharrison** [comment]
I'll look into it.

**Comment by mtcA6** [comment]
Chatted w/tom I think this is okay as we discussed today, he talked me through the details and showed me the vadir tables

**Comment by adamwhitlock1** [comment]
@mtcA6 We can validate this now with user 226 in staging, and will see active duty member as their periodOfServiceTypeText

**Comment by mtcA6** [comment]
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/31ffb047-1ec5-4b82-bca5-df77b6494926)
