### ISSUE TITLE
Design discovery: implications of new filter and sort

### ISSUE THREAD

**Issue by ayush-chak** [department-of-veterans-affairs/va.gov-team#83587]

**Comment by micahtaylor** [comment]
Documenting places around VA where there are multi-select 

https://staging.va.gov/find-locations/
<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGI4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--979c860ee3d5c07da63ceeef9edf63480b14cd08/Screenshot%202024-05-21%20at%2010.29.34%E2%80%AFAM.png" alt="Screenshot 2024-05-21 at 10.29.34 AM.png" />

Date picker in appointments
<img width="895" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVQ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4eb7b590cfc1d7d81ba76e84ea212e65baf0608c/Screenshot%202024-05-21%20at%2010.36.06%E2%80%AFAM.png" alt="Screenshot 2024-05-21 at 10.36.06 AM.png" />

https://staging.va.gov/education/gi-bill-comparison-tool/
<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXo4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d48577cf406e16aebdaf85d40eac1ea335d6105/Screenshot%202024-05-21%20at%2010.39.57%E2%80%AFAM.png" alt="Screenshot 2024-05-21 at 10.39.57 AM.png" />
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTM4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07d48764fd87dd7d065bc3fc4f4bb225c37b9838/Screenshot%202024-05-21%20at%2010.40.10%E2%80%AFAM.png" alt="Screenshot 2024-05-21 at 10.40.10 AM.png" />
