### ISSUE TITLE
On-Call Support for Vet360 Deployment

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#836]
@lkoenigsberg notes that the release is re-scheduled to go live tonight, details here.

Vet360 Build 8 Deployment 2 (B8D2) is scheduled for Thursday, August 8th. Highlights of the release are listed below. Full release notes are available in the Polaris entry.
 
To reiterate, Vet360 will be deploying changes to our existing Person Hub as part of our B8D2 release.  The existing Person Hub will be split into two - one for Person data and the other for Contact Info data.  This split will allow Vet360 to be more flexible to add other data domains in the future.  There is no new functionality associated with this change and should be seamless to our partners.  
 
We strongly encourage all partners monitor post-deployment and send details of any/all anomalies observed to our PM Team (Vet360pm@va.gv). 
 
Vet360 B8D2 (Polaris entry #23425) – Thursday, August 8th at 5pm EST.
Vet360 will be unavailable for the duration of the deployment (~3 hours)
UAM service is expected to remain online and available.

===================

@mattpointzxer0 commented on [Tue Aug 06 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19442)

**Request:
Vet360 Partners –
 
Vet360 Build 8 Deployment 2 (B8D2) is scheduled for Tuesday, August 6th. Highlights of the release are listed below. Full release notes are available in the Polaris entry.
 
To reiterate, Vet360 will be deploying changes to our existing Person Hub as part of our B8D2 release.  The existing Person Hub will be split into two - one for Person data and the other for Contact Info data.  This split will allow Vet360 to be more flexible to add other data domains in the future.  There is no new functionality associated with this change and should be seamless to our partners.  
 
We strongly encourage all partners monitor post-deployment and send details of any/all anomalies observed to our PM Team (Vet360pm@va.gv).** 
 
Additional Background:
Vet360 B8D2 (Polaris entry #22486) – Tuesday, August 6th at 3pm ET.
There is no downtime anticipated during this event.
992684 | Split Person and Contact Info in the Hub and Adapters | Split the Person Hub into separate Contact Info and Person hubs as well as create a new MVI Adapter. There is no new functionality associated with this code.Benefit to the Veteran: The ‘split’ of the person and contact information hubs will support a more resilient infrastructure, reduce partner calls, and  improve performance and testing efforts to provide a high quality Veteran experience.
909562 | Upgrade Spectrum to version 2018-2 | COTS product maintenance/ upgrade.Benefit to the Veteran: Vet360 core system upgrades are essential in providing a high performing, stable, MDM solution.  This upgrade is also the foundation for future enhancements.
909062 | Dashboard 1 - Vet360 Contact Information Overview Dashboard - Build Power BI Visualizations | Create a high level dashboard of Vet360 contact information data highlighting key performance metrics such as total veteran information, stored, updated, transaction volumes for source system reads and writes, composition of bio types, and transaction statuses.  Benefit to the Veteran: The dashboards and reports support greater operational awareness of information entering Vet360, helping to quickly identify improvements or deficiencies in the system.
1016178 & 1016339 | Develop Report for Volume by Source System & Transaction Status | Create a report that gives a detailed look into transaction volumes across different times, source systems, originating source systems, and transaction types.Benefit to the Veteran: The dashboards and reports support greater operational awareness of information entering Vet360, helping to quickly identify improvements or deficiencies in the system.

**Comment by batemapf** [comment]
Copied from `vets.gov-team` repo.

**Comment by annaswims** [comment]
we're seeing some alerts, but perhaps not unexpected https://dsva.slack.com/archives/C24RH0W11/p1565119659052900

[FIRING:1] Upstream5xxErrorRateCritical (prod monitor-prod api_gateway vet360_address_validation warn)
• *Upstream service vet360_address_validation served 50% 5xx errors, should be no greater than 5%.  See https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Alerts.md#upstream5xxerrorratecritical*
vet360_address_validation error rate 50% (http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.expr=sum%28rate%28kong_http_status%7Bcode%3D~%225..%22%2Cservice%21~%22argonaut_fhir_health_api_metadata%7Cargonaut_fhir_health_api%22%7D%5B1m%5D%29%29+BY+%28service%29+%2F+sum%28rate%28kong_http_status%5B1m%5D%29%29+BY+%28service%29+%2A+100+%3E+5&g0.tab=1)
 alertname: Upstream5xxErrorRateCritical env: prod monitor: monitor-prod scope: api…
 Show more
[FIRING:1] BlackboxAPIGatewayReachabilityCritical (prod monitor-prod /services/address_validation/v1/candidate api_gateway address_validation warn)
• /services/address_validation/v1/candidate reachability 0 < 95% for 5m.  See https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Alerts.md#blackboxapigatewayreachabilitycritical
API reachability issues (http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.expr=avg%28avg_over_time%28probe_success%7Bjob%3D%22api_gateway%22%7D%5B1m%5D%29%29+BY+%28path%2C+service%29+%3C+0.95&g0.tab=1)
 alertname: BlackboxAPIGatewayReachabilityCritical env: prod monitor: monitor-prod path: /services/address_validation/v1/candidate scope: api_gateway service: address_validation severity: warn

**Comment by lkoenigsberg** [comment]
At 10pm:

Vet360 Deployment of B8D2 has been successfully rolled back to B8D1 functionality.  Testers have verified functionality.  The Team will provide a Root Cause Analysis (RCA) tomorrow once analysis is complete

**Comment by kfrz** [comment]
Closing as stale.
