### ISSUE TITLE
10-7959a accessibility annotations

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#83607]
Complete updates to f-1 accessibility annotations ahead of handoff to dev.

**Comment by syd-hoeper** [comment]
Finished. Link to area: [https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=664-316899&t=4Nxu3DBPH14aRk7a-11](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=664-316899&t=4Nxu3DBPH14aRk7a-11)
