### ISSUE TITLE
Pension rewriting: Protected pension rates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8362]
# User story

As a Veteran or survivor with a pension under the older laws, I want to be able to easily find my current pension rate.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**
- [x] Draft page and build in GitHub
- [x] Strategy/voice/organization review
- [x] Managed editor review
- [x] Packaged with rewriting review instructions and sent to SMEs
- [x] SME feedback received

**Steps needed to complete this work now:**
- [x] Incorporate SME feedback from July 2019 (Danielle)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since SME review now (Danielle)
- [x] Migrate the rewritten page from GitHub to Drupal (Randi)
- [x] Implement solution for relevant historical rates pages (Randi, Anne?)
- [x] Do a final proof of the new Drupal page (Randi, Danielle)
- [x] Send the page back to SME for final approval (Danielle)
~~- [ ] Incorporate any additional SME feedback, and capture SME approval in documentation (Danielle, Randi)~~
~~- [ ] Re-start redirect process in [issue #2212](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2212) at this time (when rewritten page is ready & approved) (Selina)~~
06/29 last two steps moved to https://github.com/department-of-veterans-affairs/va.gov-team/issues/10737

## Information and files for reference

- **SME as of July 2019:** Alfreda Smith (Angie)

- **SME feedback:** Angie is concerned that users will miss reading the conditions information around income limits if it's not directly in the tables, as it appears on the legacy page.

- **Issue #18514 capturing this work originally:** https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18514

- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/448

- **Page in Github:**  https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-pension/pages/pension/protected-pension-rates.md

- **Heroku link:** https://github.com/department-of-veterans-affairs/vagov-content/pull/448

- **PDF sent to SMEs:** [Brand Consolidation Content Rewriting_Protected Pension Rates_6.24.19](https://app.zenhub.com/files/31788863/22caeffe-0a48-45ea-b6f5-5b17058c1a2d/download)
- **Drupal preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=720

## Acceptance criteria

- [x] Assigned to milestone
- [x] Assigned to epic
- [x] "Content" and "vsa-public-websites" labels added

### Definition of done

- [ ] Page approved by appropriate SMEs and published in Drupal

**Comment by DanielleThierryUSDSVA** [comment]
**Note:** I have got back into the GitHub doc from July 2019, addressed the SME's concern, and updated the income limits and rate amounts to the 2019 rates. This page is ready to be migrated into Drupal.

**GitHub doc:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-pension/pages/pension/protected-pension-rates.md

**Comment by RLHecht** [comment]
Friday Update: Migrated page to Drupal but still need to do rest of work on ticket.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I did a final copyedit of this page. There was one table where the year wasn't changed to 2019, so I fixed that. All the other numbers were transferred over correctly. 
Here is the preview link:
preview-prod.vfs.va.gov/preview?nodeId=5090

And here's a PDF: [https://app.zenhub.com/files/133843125/657e4303-2698-4a88-be10-a440fe1ed7b1/download](https://app.zenhub.com/files/133843125/657e4303-2698-4a88-be10-a440fe1ed7b1/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA question about turning the historic links at the bottom of this page into PDFs. I am essentially just PDFing the old TeamSite page and I made the links unclickable (so that users don't keep getting to older rates through this PDF). Do you think it's an issue that we are showing links on a page that can't be clicked? Here's the PDF: [https://app.zenhub.com/files/133843125/bff084e2-268b-4e25-986f-40ea065a80be/download](https://app.zenhub.com/files/133843125/bff084e2-268b-4e25-986f-40ea065a80be/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. That's a good question. I think it's not ideal to have links that can't be clicked, but I'm not sure how big of a blocker it is. I do wonder if it could be an accessibility issue...and that brings up a larger question around the historical rates approach of pdf'ing tables. Has the team involved Jen in that approach yet from an accessibility perspective? I want to make sure we don't create a whole bunch of non-508-compliant pdfs before getting her expertise on that.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Now that we've resolved the issue of historic rates links (no longer doing PDFs), this page is ready for you to review and then take to SMEs.

**Comment by DanielleThierryUSDSVA** [comment]
**6/3/20 note:** We're planning to share the DIC historical rates approach with Angie Smith, who is our SME for both DIC and pension. To respect her time, I'd like to share this one last rewriting page with Angie at the same time. @bethpottsVADEPO, let's connect on this to coordinate accordingly. Thanks! 

FYSA @stephorkandatx

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO Following up on our call, let's invite Angie to the next VBA biweekly to go over this. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
**For @bethpottsVADEPO :**

Here's the preview to share with Angie tomorrow: preview-prod.vfs.va.gov/preview?nodeId=5090

And here are a few notes:
- We should update the preview to align with our new, more accessible approach to table captions. I can try to get to that tomorrow before your meeting. If I'm not able to, please just let Angie know that we'll be doing some minor updates for accessibility and will send over the updated preview link for her final approval.
- When Angie reviewed this back in 2019, she'd had one concern. This concern was that  users could miss reading the conditions information around income limits if it's not directly in the tables, as it appears on the legacy page. I've reworked the tables to address this in the version in preview.
- I also updated all of the rates, and Randi double checked them. If you'd like to be a third set of eyes on those, that's always good with numbers. Maybe just let Angie know that we'll do a final review of the actual rate numbers while she's reviewing.
- I think there may be a typo on the legacy 2019 page. In the first table, it says if you're hospitalized on January 1, **2014** or later. But I don't think that's correct. The previous years have whatever the current year is for that disclaimer (ie, 2018 table has if you're hospitalized on January 1, **2018** or later). So I've used 2019, but would like to confirm with Angie if that's correct or if there's been a rule change that means it should actually be 2014. 

**Note for @stephorkandatx :**

This is going to SME tomorrow. SME approvals will carry this over into next sprint. We've started breaking out SME approvals into their own issues, so we could do that with this one if you'd like to close out this piece of the work for the currrent sprint. Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht Please see if you can figure out the anchor links so everything's functional on this page. Thanks!

**Comment by RLHecht** [comment]
@bethpotts These anchor links should all be working now.

**Comment by bethpottsVADEPO** [comment]
@stephorkandatx I sent the stakeholder this page today to review. Do you want to close this issue and open a new one for the stakeholder approval stage? Or edit the title of the issue to indicate the stage we're in? If the former, just bring over the info at the top of this one (Information and files for reference) into a new one.

**Comment by stephorkandatx** [comment]
I'll open a new one, thanks!
