### ISSUE TITLE
Life insurance rewriting batch 2: File a claim

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8363]
# User story

As the beneficiary of a VA life insurance policy, I want to be able to quickly and easily file a claim at my time of need.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Research current SEO keywords and alternatives via Moz
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will be the 3rd page within the "Manage your life insurance benefits" spoke.
- **URL (WIP):** /life-insurance/file-claim/
- **Left nav label:** File a claim
- We'll also crosslink to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/INSURANCE/sglivgli.asp
- **SEO keywords:** va life insurance claim, sgli payout
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Optimize page for keywords listed above
  - Implement VA.gov approach to how to apply/file info (look at existing how to apply pages in other benefit hubs for examples)
  - Bring [VMLI file a claim info](https://www.benefits.va.gov/INSURANCE/images/VMLI_Claim.pdf) onto page
  - Add related links to relevant pages

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/file-a-claim.md

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
Put Drupal preview link and Word doc in ticket 11234. Closing this ticket.
