### ISSUE TITLE
Life insurance rewriting batch 1: Convert to a commercial policy

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8365]
# User story

As a Veteran who has an SGLI, VGLI, or FSGLI policy, I want to understand the pros and cons of converting my current VA policy to a commercial one as well as how and when I can convert my policy.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [ ] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [ ] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi, Danielle, Beth as needed)
- [ ] Finalize existing GitHub draft (Laura) 
- [ ] Strategy/voice edit (Danielle)
- [ ] Migrate to Drupal (Laura, Randi)
- [ ] Add cross links to this page from other appropriate pages (Laura, Randi)
- [x] Copy edit (Randi)
- [ ] Platform review (content and accessibility, possibly design) 
- [ ] Package with other Life Insurance batch 1 pages and send to SMEs for review (Laura, Danielle)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will be the 5th page within the "manage your policy and benefits" spoke.
- **URL (WIP):** /life-insurance/convert-to-commercial-policy/
- **Left nav label:** Convert to commercial policy
- We'll also crosslink to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/INSURANCE/converting.asp
- **SEO keywords:** vgli conversion, military conversion, commercial insurance policy, 120 days, how long is 120 days 
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran).
  - Optimize page for keywords listed above
  - Be sure to highlight relevant deadlines
  - Look at relevant pages that should crosslink to this page (ie, [SGLI](https://www.va.gov/life-insurance/options-eligibility/sgli/), [FSGLI](https://www.va.gov/life-insurance/options-eligibility/fsgli/), and [VGLI](https://www.va.gov/life-insurance/options-eligibility/vgli/)). Pull details on converting to a commercial policy from these pages as needed/relevant onto this new page, and adjust content on original pages to effectively crosslink.
  - Add related links to relevant pages

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/convert-to-commercial-policy.md

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA -- Let's discuss a few potential edits.

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by RLHecht** [comment]
@lwalsh617 I've copyedited this page. Ready for next steps.

**Comment by RLHecht** [comment]
@lwalsh617 A few questions I had on this page I forgot to ask in the copy deck:

In the accordions where we have steps for converting to a commercial policy, the step where we mention what documents they need isn't really a step. Wondering if we should reword it as an action like "Complete the following forms" or something similar.

Also in the accordions we have bulleted items within the numbered steps but they aren't always styled as bullets. I am able to fix the ones that come as the last step in the list but not in the middle of the list (I think because we are already in the numbered list element). I don't love the inconsistency. Thoughts?

**Comment by lwalsh617** [comment]
@RLHecht -- Within the accordions, sometimes the bullets go flush left instead of aligning with the "step" copy above. Am going to un-bullet all of them for consistency. Thanks for catching that.

**Comment by stephorkandatx** [comment]
Closing this ticket out - future edits, updates will be written and handled in a new ticket. This batch was submitted for content review
