### ISSUE TITLE
Update eCheck-in Application for Multiple Stations Scenario

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#83664]
## Description
During our meeting with the BTSSS API team on 5/21/2024, the following was determined 
- Logic to calculate travel claim reimbursements for Veterans when they have appointments at multiple facilities on the same day is complicated. It was decided that we should refer the Veteran to the BTSSS portal to file claims when this scenario (edge case) arises.

- Logic to determine for which appointment to submit a claim when the Veteran has multiple appointments at a single facility on the same day is complicated. We should allow the Veteran to choose the appointment for which they want to submit a claim for that facility.

## Wireframes
[Wireframe Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83730)

## Tasks
- Update eCheck-in so that Veterans are only able to submit a travel claim via eCheck-in when they only have appointments at a single facility/station on that day; otherwise refer them to the BTSSS portal to file
- this is also a good time to sunset the `check_in_experience_travel_logic` toggle

**Comment by brianseek** [comment]
@loripusey 
This is merged and ready to validate. Its probably easiest to validate locally. 
To validate: 
 - check-in with a travel claim
 - check-in with a new appointment, and observe that you don't get offered to file travel
 - change the date or delete `health.care.check-in.travel.pay.sent` in local storage
 - check-in should now ask if you wish to file travel again

**Comment by loripusey** [comment]
validated
