### ISSUE TITLE
As a user submitting a FMP claim, I need my supporting documents routed correctly according to their type

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83684]
As a user submitting form 10-7959f-2, I need my supporting documents routed correctly according to their type so that all of my documents are processed as smoothly as possible.

### Acceptance Criteria
Given a form 10-7959f-2 submitted by a FMP claimant
- When the user submits
- Then the form and each supporting document are sent as individual files
- And each file has its document type included in its metadata

Given a supporting document submitted with a VFMP form
- When the user selects a document type in the dropdown of the upload screen
- The uploaded document should have the user-selected doc type mapped to its metadata 

### Implementation notes
This is similar to the work done for 10-10d in [this user story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80644).

**Comment by balexandr** [comment]
test

**Comment by balexandr** [comment]
Work being done in https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/91226
