### ISSUE TITLE
As a user submitting a CHAMPVA claim, I need my supporting documents routed correctly according to their type

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83681]
As a user submitting form 10-7959a, I need my supporting documents routed correctly according to their type so that all of my documents are processed as smoothly as possible.

### Acceptance Criteria
Given a form 10-7959a submitted by a CHAMPVA claimant
- When the user submits
- Then the form and each supporting document are sent as individual files
- And each file has its document type included in its metadata

Given a supporting document submitted with a VFMP form
- When the user selects a document type in the dropdown of the upload screen
- The uploaded document should have the user-selected doc type mapped to its metadata 

### Implementation notes
This is similar to the work done for 10-10d in [this user story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80644).

**Comment by cloudmagic80** [comment]
Initial mapping PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/17016

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/17268

**Comment by cloudmagic80** [comment]
[cbadb8dc-e1ac-4e09-aca8-20d874130867_vha_10_7959a-tmp.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f8fc4ebf696febca1045effdbc31d534c7ad6a8/cbadb8dc-e1ac-4e09-aca8-20d874130867_vha_10_7959a-tmp.pdf)
