### ISSUE TITLE
VR&E - check for cause of db save validation issues

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#83680]
### Determine & if appropriate eliminate the sources of errors for v0::veteran_readiness_employment_claims_controller

The "VRE API Errors" [monitor](https://vagov.ddog-gov.com/monitors/186965?from_ts=1716207905000&to_ts=1716209105000&event_id=7582395659812333483&source=monitor_notif) show a number of 4** errors/responses from the API in the past month:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/119101230/2bdac198-fd66-4e95-9bc2-0e5f059c6d5b)

- In particular you should look at the 422 status errors (yellow in the chart above) as custom metrics [here](https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1713730389472&end=1716322389472&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgViBpOGPIQAHQaCJ4aUM2NEE61CDoYIk5GGFCimvVwqvJoOFjqIghOmZg+LhgQaHhGwABUPN31mfhLABQAlCA8ALpUru54mKHhD6pPGDGl8dd3IG1YNA5UDyDBAhADZRQHAwFbPDQQTKJNATJxyRTKdIoqDI1H0JjKERuDxoa78CD2TBYNEKHIgABGGG0lluPD4-1m4gAwlJhDAUCInmgeEA)  
- The fact that the 422 status errors show up with this custom metric suggests that the exception is being thrown from the "else" block on [lines 18-20](https://github.com/department-of-veterans-affairs/vets-api/blob/c40e3a10a23f07bd523238432565433f8f308834/app/controllers/v0/veteran_readiness_employment_claims_controller.rb#L18)  

The code in question is [app/controllers/v0/veteran_readiness_employment_claims_controller.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/veteran_readiness_employment_claims_controller.rb)   

If you click on the errors provided in [this service view](https://vagov.ddog-gov.com/apm/services/vre-application/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=eks-prod&fromUser=true&groupMapByOperation=null&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&s3BucketDetails=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&view=spans&start=1713730536014&end=1716322536014&paused=true) on the errors widget you see that they are all `Common::Exceptions::ValidationErrors: Validation error`, which validates the assertion that the error is from line 18-20 in the code.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/119101230/f5f3eeda-e66d-4814-b3f3-a96e7203b6db)

If you look one of these entries up in [Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/250992/?environment=production&environment=prod&project=4&project=3&query=veteran_readiness_employment_claim&statsPeriod=14d)  you see a number of issues such as:  
- form - The property '#/veteranInformation/fullName' was not a valid schema
-  form - The property '#/veteranInformation/dob' was not a valid schema in schema
- form - The property '#/veteranAddress' was not a valid schema in schema
- form - The property '#/email' was not a valid schema in schema

Goal: 

- [ ] determine the cause of these errors 
- [ ] fix the validation errors if possible.  
- [x] update the monitor to not fail for "regular"/auth-related exceptions.

**Comment by va-albers** [comment]
This is for Datadog monitor DD-186965

**Comment by va-albers** [comment]
List of possibly related Sentry items: [link](https://sentry.vfs.va.gov/organizations/vsp/issues/250992/events/?environment=production&environment=prod&project=4&project=3&statsPeriod=14d)

**Comment by va-albers** [comment]
Datadog [APM traces](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20AND%20service%3Avre-application%20AND%20%40http.status_code%3A422%20operation_name%3Arack.request%20status%3Aerror%20&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&netviz=sent_vol%3A%3A%2Ctcp_r_pct%3A%3A%2Crtt%3A%3A&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=all&spanViewType=metadata&traceQuery=&view=spans&start=1715159933213&end=1716369533213&paused=false) related to this issue all of them show as Common::Exceptions::ValidationErrors

**Comment by va-albers** [comment]
Related Slack thread [here](https://dsva.slack.com/archives/C06C2D2PJQZ/p1716208868868889)

**Comment by va-albers** [comment]
Note the current monitor already ignores 401 status responses.

**Comment by tblackwe** [comment]
@va-albers what is the priority of this issue?

**Comment by micahaspyr** [comment]
Looking at Sentry, I'm seeing that this is coming from multiple sources that are also hitting the vre controller.


![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/b9034ba6-d7e5-4d88-af8c-ca89247e7101)

**Comment by micahaspyr** [comment]
> List of possibly related Sentry items: [link](https://sentry.vfs.va.gov/organizations/vsp/issues/250992/events/?environment=production&environment=prod&project=4&project=3&statsPeriod=14d)

@va-albers according to this sentry log, none of these claim submissions have a user that is signed in, which is required for VR&E.  See below



![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/8ff9352d-69c1-4dc3-9fe3-fa2d94634816)

I think this could be related to a session timing out when the claim is submitted.  We should check to see if the Veteran is logged in before trying to even save the claim.

**Comment by micahaspyr** [comment]
Sentry shows no reoccurrence of these errors since June 3rd as shown in the image capture below highlighted in blue.



![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/20db02fa-0fc0-4355-a93f-65851b866081)

**Comment by va-albers** [comment]
> Looking at Sentry, I'm seeing that this is coming from multiple sources that are also hitting the vre controller.
> 
> ![Image](https://private-user-images.githubusercontent.com/6454840/336612881-b9034ba6-d7e5-4d88-af8c-ca89247e7101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjg2NjEsIm5iZiI6MTcxODM2ODM2MSwicGF0aCI6Ii82NDU0ODQwLzMzNjYxMjg4MS1iOTAzNGJhNi1kN2U1LTRkODgtYWY4Yy1jYTg5MjQ3ZTcxMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMTIzMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY3OTcwMmYzOWJhMDM1YTA0ODQ1YWI4ZTM3M2IyZTZlMTYzNzU1MzgwY2RmYTcwYTlhYzUxNmRjNDgwODdkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JmWt4-mkFkhu61ExZz5K0H5rTdM-Hst-Mw6MK9LqPKg)
> 
> It should be noted, however, that these validation errors are not unique to the vre controller. This happens in other controllers as well, such as the caregivers_assistance_claims controller, [sentry log here](https://sentry.vfs.va.gov/organizations/vsp/issues/256990/?project=3&query=external_service%3A%22benefits_education%2Fservice%22)
> 
> Some of these include other validation failures as well, so I'm wondering if we're seeing a larger issue on the grander scale

For the purposes of this ticket you only need to worry about VRE errors.

**Comment by tblackwe** [comment]
We do not have an answer for this problem. It is NOT a silent error as the Veteran gets an error displayed, but we cant answer why this is happening. We can add the InProgressForm ID to the logs to try and improve our understanding

**Comment by tblackwe** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/4c697f2d-9b70-40a2-9af5-b50b230dac13)

**Comment by tblackwe** [comment]
@va-albers Looking at these DD logs, it appears to me that the issue is focused to a specific pod. 

https://vagov.ddog-gov.com/logs?query=%40name%3A%22V0%3A%3AVeteranReadinessEmploymentClaimsController%22%20%40payload.status%3A422%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.status_message&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=%40payload.status_message%2Casc&viz=stream&from_ts=1713299083766&to_ts=1721075083766&live=true

We cant find any reason this would be a code problem within VR&E

**Comment by tblackwe** [comment]
it isnt all requests to that pod though
[All Errors on a day](https://vagov.ddog-gov.com/logs?query=%40name%3A%22V0%3A%3AVeteranReadinessEmploymentClaimsController%22%20%40payload.status%3A422%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.status_message&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=%40payload.status_message%2Casc&viz=stream&from_ts=1720670400000&to_ts=1720756740000&live=false)
[All requests on the pod on that day](https://vagov.ddog-gov.com/logs?query=%40name%3A%22V0%3A%3AVeteranReadinessEmploymentClaimsController%22%20%40host%3Avets-api-web-5859d5c474-rn4r5%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.status_message&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=stream&from_ts=1720670400000&to_ts=1720756740000&live=false)

**Comment by mjknight50** [comment]
cc @va-albers @sanjabaj2

**Comment by mjknight50** [comment]
This issue seems very similar:
https://github.com/voxpupuli/json-schema/issues/514

**Comment by sanjabaj2** [comment]
@mjknight50  We had very recent occurrences of that json validation errors on VR&E. @va-albers added additional logging to [VRE dashboard.](https://vagov.ddog-gov.com/dashboard/94e-cku-2aq/benefits---veteran-readiness-employment-claims?fromUser=true&refresh_mode=sliding&view=spans&from_ts=1724360341547&to_ts=1724446741547&live=true)  
Down at Logs that match "VR&E claim was not saved" , we have seen quite a few yesterday which could be why we've seen monitor go off a lot. All on the same pod. So, the fix didn't work.
