### ISSUE TITLE
Midpoint Review - Content - Veteran Facing Forms & Authenticated Experience - Form Status on My VA & Updated Confirmation Page

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#83688]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions
Overall, I really like the updates that were made. With the content, always ensure you're being as specific and clear as possible to help users. Please continue to work with CAIA on this page. If you have any questions, please let me know. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Should
- [x] Confirmation page - Once the user navigates from this page, they can't get back to it. However, there is no content on the page explaining that. There should be some alert or explanation that warns the user that if they navigate away from the page, they can't get back to it. It's also an opportunity to demonstrate to users where they can find the information again. For example: "You can't return to this page once you navigate from it. However, all this information can be found in your My VA profile under the Forms section." 
- [x] Desktop A - Error - The user finds the following alert: “We couldn’t process the form you submitted. We’re sorry. Go to your forms to find out what to do next.” There is a link with the text “Go to your forms.” Where does this go? If they don’t follow that link, how would they find it? If they can go to a specific section on this page, it may be good to state that specific section title in the error message.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by jeana-adhoc** [comment]
For the confirmation page, we'll be testing the confirmation page and seeking to understand the Veteran's expectation on the recoverability of the confirmation page, or is everything accessible that they need on My VA?

**Comment by mattmarino-adhoc** [comment]
We are proceeding with making the recommended change related to error messaging, while holding off on adding additional content to the confirmation page.

**Comment by mattmarino-adhoc** [comment]
We are proceeding with making the recommended change related to error messaging, while holding off on adding additional content to the confirmation page.
