### ISSUE TITLE
Update testing environment(s) to point to sandbox-api.va.gov

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8369]
**Request**
Please update any apps in our testing environment(s) that are currently calling endpoints on dev-api.va.gov
To instead point to sandbox-api.va.gov as the hostname for development API requests

This change needs to take place before April 30th. 

**Task**
- [ ] All apps in testing environments point to sandbox-api.va.gov as the hostname

----
Instructions on how to switch
Step 1: Simply replace any instances of “dev-api.va.gov” in your code with the new hostname, “sandbox-api.va.gov”.

Step 2: Be sure to test the application in your lower environments after replacing the old instances with sandbox-api.va.gov.

Step 3: If you are having issues, please contact us.

**Comment by kelsonic** [comment]
@ncksllvn did you get a PR up for this yet? 🙂

**Comment by ncksllvn** [comment]
I did, https://github.com/department-of-veterans-affairs/vets-api/pull/4186

**Comment by kelsonic** [comment]
Oh that's right! Nice! 🎉

**Comment by stephorkandatx** [comment]
@ncksllvn ready to close this out?

**Comment by ncksllvn** [comment]
I think I made all of the updates. Yep, please close!
