### ISSUE TITLE
10-7959f-1: add 'same as' address screen 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83695]
URL: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/

- Add new ‘same as’ address screen after mailing address screen (progress indicator should also reflect additional step)
<img width="150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd240QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9dd85f567b575a0a72b1797d7f0ab35485d2a69/Screenshot%202024-05-20%20at%208.36.08%E2%80%AFPM.png" alt="Screenshot 2024-05-20 at 8.36.08 PM.png" />
- if yes, go to next screen (skip home address screen)
- if no, show home address screen
Figma link: https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?node-id=726-21596&t=TGjWUcWIDEWQadtF-0

**Comment by reiting** [comment]
This is now waiting for platform review.

**Comment by marywang2** [comment]
@reiting are we able to create the url for this page as well - /health-care/foreign-medical-program/register-form-10-7959f-1/mailing-address-same

**Comment by reiting** [comment]
@marywang2 I'm not sure what you mean about creating a url for another page? Can you clarify?

**Comment by marywang2** [comment]
@reiting we'll need a new url for this page (just like the others).

**Comment by marywang2** [comment]
Confirming the url that's there is fine - 'same-as-mailing-address' so no need to change @reiting

**Comment by reiting** [comment]
@marywang2 okay cool. This has been merged to staging. In a few hours it should be available, so I'll move it to review this afternoon.

**Comment by reiting** [comment]
Apparently there is an issue right now where staging hasn't deployed since yesterday afternoon. Just an FYI

**Comment by reiting** [comment]
@marywang2 they fixed whatever issue they are having so this is on staging now.

**Comment by brian-wilke** [comment]
Just to confirm, this additional page is not a step indicated in the progress indicator. It is a follow-up to the mailing address input, but not a separate step.  It would be contained inside the Mailing address section in the review page as a consequence as well (for context).

**Comment by reiting** [comment]
@brian-wilke my apologies! I think I saw a comment on Figma that it was supposed to be a separate step. I do see in the Figma that it is not shown as a separate step. I will change that ASAP!

**Comment by marywang2** [comment]
@reiting while you're in there :) we noticed that mailing address gets repeated twice on the review page.

**Comment by reiting** [comment]
@marywang2 yeah it's because of them being set up as separate steps. Putting them together on the same step[ will fix that problem too (double fix for half the work lol).

**Comment by reiting** [comment]
This has been completed and a draft PR is up and in team review.

**Comment by reiting** [comment]
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0YrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d6b5f1731db799b8adb20a2ecfd6bb8ff3667f7/Screenshot%202024-06-20%20at%209.55.02%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 9.55.02 AM.png" />
<img width="747" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0orQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eda94e6a8a5b70435dfac8de16401bac9df71f11/Screenshot%202024-06-20%20at%209.55.13%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 9.55.13 AM.png" />
<img width="970" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1IrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--410864002bc9876df68c3769a7dd62806cd296fc/Screenshot%202024-06-20%20at%209.55.25%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 9.55.25 AM.png" />

**Comment by reiting** [comment]
This has been completed and merged and should be on staging now.

**Comment by marywang2** [comment]
@brian-wilke I'm closing this one but please do review. Thanks!

**Comment by marywang2** [comment]
After discussing with @reiting @brian-wilke - the issue that arose with skipping from 5 steps to 6 steps in the progress indicator outweigh the potential benefit of adding the extra screen. Removing the 'same as' screen for now and reverting back to the original designs.

**Comment by reiting** [comment]
This was removed as part of the review page headers PR (it needed to be removed to be able to complete that story). It's in team review.

**Comment by reiting** [comment]
Now in platform review.

**Comment by marywang2** [comment]
@reiting thanks for your patience with this one...we will add this back in (per stakeholder confirmation) and move it so that the progress indicator does not change with the addition of this screen. Appreciate all your efforts!

**Comment by reiting** [comment]
<img width="784" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a653d1624435b4738851de6557234de4b027ded/Screenshot%202024-06-27%20at%209.57.27%E2%80%AFAM.png" alt="Screenshot 2024-06-27 at 9.57.27 AM.png" />
<img width="883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0NaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfa53f3dfff5d6c5edc3393874960202fec5c1d9/Screenshot%202024-06-27%20at%2010.04.13%E2%80%AFAM.png" alt="Screenshot 2024-06-27 at 10.04.13 AM.png" />
<img width="646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0taQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9be742baa65ba6d07f0a2797509d404b02d08c71/Screenshot%202024-06-27%20at%2010.04.26%E2%80%AFAM.png" alt="Screenshot 2024-06-27 at 10.04.26 AM.png" />
<img width="655" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09aQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71565576b4a98d7123180e3768a48f33e8687c26/Screenshot%202024-06-27%20at%2010.04.34%E2%80%AFAM.png" alt="Screenshot 2024-06-27 at 10.04.34 AM.png" />
<img width="934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1daQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--895b5fbcdb7c1847b68db8be6143be0bddfb7529/Screenshot%202024-06-27%20at%2010.04.41%E2%80%AFAM.png" alt="Screenshot 2024-06-27 at 10.04.41 AM.png" />

**Comment by reiting** [comment]
@marywang2 @baltes @brian-wilke this should be in staging and good to go. I hope.

**Comment by baltes** [comment]
@brian-wilke This looks good to me, could you double check and give a thumbs up?

**Comment by brian-wilke** [comment]
Yes. I think this is good!
