### ISSUE TITLE
Update design of VA.gov header to improve usability and visual appearance, even at larger font sizes

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#8370]
## Problem description

How might we update the header so that it looks great on mobile, even at larger font sizes (which many of our users require)? 

## Goal

1. The design/wording of "this is an official website of the US govt" banner needs to be revisited. The wrapping is bad, it takes up too much precious vertical space, can we just make it a link instead of having the extra words "here's how you know", etc.
2. The VA logo is too large and has too much top padding on mobile. Again, let's optimize for precious vertical space. 
3. Need to collapse the menu items further so that random misaligned "..." items do not display. 

## Tasks
- [ ] Design exploration
- [ ] Proposal to design council
- [ ] Accessibility review

## Screenshots

![Image](https://user-images.githubusercontent.com/47792423/80217968-85c27800-860e-11ea-98b6-97ec6c48b352.jpeg)

![Image (1)](https://user-images.githubusercontent.com/47792423/80218087-b6a2ad00-860e-11ea-89c2-c39a958efee3.jpeg)

**Comment by caw310** [comment]
The issue has been fixed. But would be good to match USWDS in the future. We will write up a new ticket to update header to USWDS.
