### ISSUE TITLE
10-7959f-1: unable to view confirmation screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83702]
url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/

**Issue**: There appears to be some error when submitting on the FMP registration review page since the user can't proceed to the confirmation screen (or access directly with the url).
**Current result**: user is unable to get past the review screen
**Expected result**: user should be able to land on the confirmation screen from the previous review screen (upon submit)

**Comment by michaelclement** [comment]
[PR is here](https://github.com/department-of-veterans-affairs/vets-website/pull/29919)

Waiting on:
- [ ] Engineering review
- [ ] Platform review

**Comment by michaelclement** [comment]
@marywang2 this has been merged in and should be visible on staging shortly. Thanks!
