### ISSUE TITLE
Create Reporting view for key 527 metrics

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#83700]
The purpose of this effort is to create a web accessible view into key 527EZ metrics.  Creating this view will provide business stakeholders access to the metrics without requesting manual pulls of data from developers.

Desired data points:
1. Submitted applications - with counts of authenticated and unauthenticated
2. In-progress (initialized) applications - with counts of authenticated and unauthenticated
3. Unique page views of applicant/information
4. Average time to completion
5.  Maximum time to completion

Access
1. To the extent possible utilize an existing tool to create the view 
2. Use the authentication mechanism already in place within the tool to enable business stakeholder access

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/83700?planning-poker) with Zenhub @wayne-weibel

**Comment by wayne-weibel** [comment]
https://dsva.slack.com/archives/C053U7BUT27/p1716321825668429

**Comment by wayne-weibel** [comment]
Intending to utilize Datadog and StatsD metrics.  The dashboard needs to following merging of the above PR.  The approach is to make the StatsD agnostic of form where possible, so similar reporting could be applied to other forms.
Page views of 'applicant/information' is accessible via DOMO/GA

**Comment by wayne-weibel** [comment]
@buddhima-coforma  This is what I have so far, had to go through some trial and error for how to accomplish some of it
https://vagov.ddog-gov.com/metric/explorer?fromUser=false&graph_layout=multi&start=1717620000196&end=1717706400196&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyABuiBpOGPIQAHQaCJ4aUK0YtVBOmZg+-UaecMCu7k7QyABMZPIAtACsMwDscABePM0Y9Zn4IggAFACUIHygkdG5sVgzicntaRnZyvmFxSC35ZU1dQ1NVrtCxdDQ9OB9AYYIZqOBOBA4FwQNBwZr7PCHcZuVRTKCzebLNabba7foHY5nC4RKI5L6lLAANgeKWeeCytPeECKiW+uQqVVqFgBLTaHVB4MhgxxsPhiOEKLR5Kxk2mc0WK3WWx2e3Jp3OAF0qBNVHhMKFwhg0BBdsoAApwEQaSQiAAEAGEpRoXQBlPAAI1U4gQEMSxtNGBi9ISVMt1tCIAAggQ2IcuaMoC77Y7nT7-YGNE7HKHseHIzo7ucKKBYzbcgAVHDtNCZh2F12+gMQAvOz5hzDKTKVflHW5kSlVkA1+MNpsupNMB0STLp3Od7tFo0l-u5QeqYe3Bnj6tW2uJkRSLCqfBerNt1f5tu9rcRm5Rl0LF23e4xk-TxuWudzxES9r3vLtH2LdxSx3IdKhHN8Py-SlDRANosBRGQQHkS1EGDZRHgwKAcBgMgmSoNwBG0Jw-RoXJ2hgT4KJ0JwjFqbQtBQAozCoK0RDhORFHKHArSgRJeLhegmGUc93EtSski7eRMCweEFFpP0MHYg0eD4VClPEN0pGEGAUBEU00B4IA

**Comment by wayne-weibel** [comment]
'unique views' and 'anonymous started' are incorrect in image since those are only on staging at the moment
<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea308b41822253f58946c9d0722dbe7dafbd478b/image.png" alt="image.png" />
