### ISSUE TITLE
[Tech Debt] Update alert text for Form526 high failure rate

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#8371]
## User Story or Problem Statement
Update the summary in the [Form526 high failure rate](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/application.rules#L107) alerting rule and linked documentation to make it more clear to the VSP dev on call what this error means and what action the BAM1 team would like taken.  

What the oncall engineer sees:
![Screen Shot 2020-04-24 at 9 51 12 AM](https://user-images.githubusercontent.com/19188/80220035-46495b00-8611-11ea-9b00-41a1cb80e581.png)
[documentation link](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md#form526failureratewarning)
[prometheus link](http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.expr=sum%28rate%28worker_evss_submit_form526_non_retryable_error%5B5m%5D%29%29+%2F+%28sum%28rate%28worker_evss_submit_form526_non_retryable_error%5B5m%5D%29%29+%2B+sum%28rate%28worker_evss_submit_form526_success%5B5m%5D%29%29%29+%2A+100+%3E+30&g0.tab=1)

Without knowledge of form 526, the on call may not know which team is repsonsible for 526 or how serious this alert is. 

## Acceptance Criteria
- [x] Provide documentation to VSP on updated error message text and ensure they are aware it is one of our products.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
I'm thinking something along the lines of " Form526  is a form that disabled veterans complete in order to receive disability compensation.  Notify the #vsa-benefirts-memorial team in slack", along with a team discussion of what we'd like to happen outside of business hours.

**Comment by annaswims** [comment]
the BAM team could also set alerts in slack for `Form526FailureRateWarning`

**Comment by annaswims** [comment]
related to https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8529

**Comment by SarahJaine** [comment]
- Application alerting rule: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/application.rules#L107
- More information link: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md#form526failureratewarning
- Product portfolio link: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez
