### ISSUE TITLE
[BE] 10-10EZR TERA Questions V2--Discovery--determine what changes will be made by VES in June

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#83726]
As a Veteran, I would like my TERA answers to be stored in a VA database and retrievable so that I can review them after I've answered them to make sure they are correct.

- [x] Talk to VES sustainment team about what is changing for their June 10 release and document this
- [x] Determine if we need to change how we send them data
- [x] Come up with implementation plan (can be very informal) for how we will change our API Send and Receive
- [x] Confer with team on any other disciplines that may be impact (e.g. FE, UX, content)
- [ ] **Success: We have a plan in place to update EZR to accommodate for the VES TERA updates**

**AS Note: [Here is a Slack Thread](https://dsva.slack.com/archives/CMJ2V70UV/p1714666977081299) about adding special characters in the June 10 release, we will need to update FE and content for this I believe**

**Comment by JoshingYou1** [comment]
Per Joshua Faulkner, nothing about the Jone 10th release is changing in terms of consumption (making requests to an API provider) of the ES API. Please refer to this slack thread: https://dsva.slack.com/archives/C06FDF2EN0H/p1716563549828229

**Comment by JoshingYou1** [comment]
In addition, we will not be able to pull previously submitted TERA question data for users.

**Comment by JoshingYou1** [comment]
With regards to determining whether a user has previously submitted TERA info, as of 5/29/2024, VES does not have any way of showing us that. Please refer to the slack thread link above.
