### ISSUE TITLE
Update eCheck-in Service Blueprints for Multiple Stations Scenario

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#83729]
## Description
During our meeting with the BTSSS API team on 5/21/2024, the following was determined 
- Logic to calculate travel claim reimbursements for Veterans when they have appointments at multiple facilities on the same day is complicated. It was decided that we should refer the Veteran to the BTSSS portal to file claims when this scenario (edge case) arises.

- Logic to determine for which appointment to submit a claim when the Veteran has multiple appointments at a single facility on the same day is complicated. We should allow the Veteran to choose the appointment for which they want to submit a claim for that facility.

## Tasks
- Update the service blueprints for the multiple station scenario for eCheck-in

**Comment by benbrasso-agile6** [comment]
Updated - https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696788763395/d3aa60a7420ece422a6f6b84659c33350279b782

Probably challenging to validate, but I'll leave this in validate just in case @brianseek  gets around to it 

No next step is needed on this ticket. Close when validated or not :)

**Comment by brianseek** [comment]
Looks good to me!
