### ISSUE TITLE
Update certs rotation readme with Eauth certs

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#83738]
## Issue Description. 
Update here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Documentation/Security/Rotate_certs.md

## Acceptance Criteria
- [x] Import new dates of expiry for Eauth non-prod and prod certs within Doc

**Comment by parkerbees** [comment]
Moved to Jira, closing here
