### ISSUE TITLE
[Congressional] V11776378 Due 7/3/24 Sen Casey

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#83744]
## Issue Description
Veteran has complaint regarding VA website not showing past claims (Sen. Casey)
VA’s current website layout doesn’t allow veterans to see all their claims at once but rather only the current claim that is being worked on. Veteran is curious as to why it was changed to this format when veterans used to be able to see all the claims.

https://app.slack.com/client/T03FECE8V/C02BS78NYRM?selected_team_id=T1ZD0UBMZ
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Reached out to Silke D, Jacob W, and Jerek S for guidance on how claims should appear.

**Comment by Kimberley2023-CSM** [comment]
Update:
6/4 - Reached out to Silke, Jacob, and Jerek for guidance on this issue.
6/5 - Jacob responded advising that the Veteran will need to click into a claim or the "manage claims" link to view a full list of their claims.  Upon logging in, a Veteran is automatically redirected to the MyVA Dashboard , which will only show a subset of claims.  
6/10 - Reached out to Veteran with these details for resolution for his request.  Awaiting a response.

**Comment by Kimberley2023-CSM** [comment]
6/12 - Jacob W. suggested a shadow call.  Jerek and Skylar may have to manage it.
6/15 - Follow up to determine availability.
6/15 - Sent follow up to Veteran informing him that a shadow call is needed and I will contact him to schedule.

**Comment by Kimberley2023-CSM** [comment]
6/21: Reached out to Veteran for availability for a shadow call (possibly today) with the engineering team.  Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
6/25 Update: KMD is sending out a Zoom invite to Veteran with instructions on how to connect. They will be on the phone with HD to help resolve the issue they are having On their Samsung tablet.

**Comment by Kimberley2023-CSM** [comment]
6/26 - Invite sent.  Accidentally put Peters, but updated invite to Congressional Casey.

**Comment by ATMiddleton** [comment]
Shadow call 6/2/24 11am eastern

**Comment by Kimberley2023-CSM** [comment]
6/27 - Shadow call scheduled for tomorrow, 6/28/24 at 11:00 AM ET with Jerek and Jacob from the Benefits team.
Will update accordingly after sync tomorrow.

**Comment by Kimberley2023-CSM** [comment]
Update:
6/28:  Shadow call held, Jacob determined and informed Veteran on the call, the issue brought to their attention can truly help many veterans; unfortunately, it’s going to take a little longer than our phone call. They have already taken back details to his team to begin the discovery work for this.
 I advised Veteran that I would reach out to a VSO and a member of the HRC team to possibly assist further.
Sent Regina Yount message on 7/1/24 requesting a team member reach out to Veteran to assist with claims details as well as remanded claims.  Also to provide a VSO to assist with C & P exam results.  She confirmed via email they would reach out and assist Veteran.
Awaiting response from Darryl Webb, for more information surrounding FOIA requests for C & P exam results. Will provide to Veteran once I have info.
