### ISSUE TITLE
Sidekiq Admin UI access for Nathan Burgess

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#83742]
### Your Name

Nathan Burgess

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

NB28VT

### Team, Role, and Company of the target individual

Disability Experience team 2 (Carbs), Software Engineer, Coforma

### COR Name

Jennifer O'Day

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

If any information is needed that is not covered by this template feel free to refer to my [recent request for terminal access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83477) which required more information

**Comment by davidpetras** [comment]
@NB28VT  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Thank you.
