### ISSUE TITLE
Implement the vets-api controller and GCLAWS Form21as endpoint request

### ISSUE THREAD

**Issue by a6marinos** [department-of-veterans-affairs/va.gov-team#83757]
### Description
To provide OGC with digital accreditation requests from the 21a form on vets-website, ARF will need to integrate with the GCLaws API that is currently being developed.

### Acceptance Criteria
- [ ] ARP Engine can make calls to the GCLaws Mock API 
- [ ] A controller is created for the front end to use

**Comment by hdbaines** [comment]
@gabezurita to add link to video

**Comment by gabezurita** [comment]
@hdbaines added it to the issue description!
    * [Video demo: Hager, Matthew W. (civitasdx Llc): Demonstrate Form 21a Mock API Endpoints](https://teams.microsoft.com/l/message/19:68c67fbb206f48ec9fcfde78de92fec8@thread.tacv2/1715298258459?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=4ef8e1aa-afd3-4551-b10b-c5b2848433a4&parentMessageId=1715298258459&teamName=OGC-VBA%20Integrations&channelName=Accreditation%20Portal%20(va.gov)&createdTime=1715298258459) — this is in Teams and requires CAG
