### ISSUE TITLE
Midpoint Review - IA Feedback - Form Status on VA Profile & Updated Confirmation Page

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#83752]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through Collab Cycle!
- I appreciate that you are testing different headings/labels for the forms section in My VA. I hope you'll share your research at a Monday design meeting.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Must: CAIA IA review:** if you haven't yet, work with CAIA IA's @kristinoletmuskat @jennymayoco to review the product and ensure that user flows, entry points and other IA wayfinding mechanisms are aligned with VA.gov best practices. Also, it's worth opening the conversation with them about next steps for IA considerations for this product (specifically the placement of the forms section in relation to the the claims status sections).

- [ ] **Should: evaluate content groupings and visual hierarchy on success page**. On the success page, I love the new functionality to generate a PDF. With more elements, and more complex design elements here (alert/info component, blue download box, accordion; three different types of link/button) it might be tough for users to discern hierarchy or the primary next step you'd like them to take. The current content flow is, roughly:  
  - Form submission status/check status
  - Save a copy of form
  - What you submitted
  - Print a copy of form
  - What comes next
  
  Maybe the order/grouping of content/actions can be changed and/or the background colors could be changed up to create a more cohesive grouping of info.
![Screenshot 2024-05-22 at 10 48 03 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/cdd0bf12-fe33-467e-b07e-0dd95bd8116e)

- [ ] **Consider: moving the forms section up to be adjacent to claims in My VA** Many of the design decisions the team is grappling with are because of the placement of this forms section at the bottom of the page. Maybe it _is_ in-scope to bring it up toward the top (and if user research bears this out, it might be worth approaching it this go-round).

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by jeana-adhoc** [comment]
####  Issue 1 - 
We've been in conversations with Laura W. and Megan Z. on this project and have met with Kristin O. For the small scope of this project the IA and entry points are ok. Future projects need to consider several IA concerns including ordering of items on My VA dashboard, how we handle showing statuses for some forms but not all. 

We've addressed the visual hierarchy issues in our prototype and will test with this:
<img width="398" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--270b6a28b1cb7612b2575c973b87fe770a7d27ec/image.png" alt="image.png" />

The groupings are 
- Success message
- How to get a copy of your data
- What to expect next
- How to get help

**Comment by mattmarino-adhoc** [comment]
**Issue 3 - Consider**
My VA is aware of the issues presented by the location of the form submission cards on the page, but for now we will keep this as-is. This however will be addressed in the future.
