### ISSUE TITLE
[FE] Accordion heading content change

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83769]
## Background

CAIA recommendation. 

## Tasks

- [ ] Change [accordion heading](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=977-60422&t=bYoprNsCMlOWF1eT-4) to 

> What if I can’t find my appointments in this list?

Impacts both pre-check-in and check-in appointment list pages.

**Comment by loripusey** [comment]
I'll add it to next sprint

**Comment by brianseek** [comment]
PR ready for when next sprint starts

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 This is ready to validate. See screenshot
<img width="808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDhlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10c852c41c45f752400486c88e2bfd8e7cbd8b6c/accordion-headings.png" alt="accordion-headings.png" />

**Comment by benbrasso-agile6** [comment]
LGTM
