### ISSUE TITLE
[Security - Audit Request] - Gather evidence/artifacts related to request from VA audit team

### ISSUE THREAD

**Issue by kell-y** [department-of-veterans-affairs/va.gov-team#83760]
In order to reply to the request by a VA audit team, Platform Security needs to provide evidence that Platform is compliant with five controls and respond to the audit team:

AU-2 (Audit Events)
IA-2(1) (Network Access to Privileged Accounts)
IA-2(2) (Network Access to Non-Privileged Accounts)
SC-8 (Transmission Confidentiality and Integrity)
SC-28 (Protection of Information at Rest)

We request some assistance from the Infrastructure team to gather the following artifacts:

- [x] A list of auditable events (AU-2.1)
- [x] A sample of a log showing the above auditable events being logged appropriately (AU-2.1)
- [x] Correspondence (email, meeting minutes, slack messages) showing the coordination of security audit functions with other organizational entities. This artifact should be as recent as possible, however any correspondence that confirms we're coordinating with the VA to properly audit is acceptable (AU-2.3)
- [x] A screenshot showing MFA is implemented for privileged accounts. (IA-2.1) Note: We should include the following systems as part of this item: AWS, GitHub, SOCKS, ArgoCD, Jenkins, Datadog, Postgres. Atlas, Sentry, Sidekiq are managed via GitHub login)

**Comment by hgbarreto** [comment]
## AWS 
Every user is added to the Force-MFA Group. Added screenshots of the group and the JSON policy attached to the group which enforces MFA-only access to AWS resources.
Note - We share our account with other programs, we are not accountable for every single user within this AWS account.

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bb850d5a58c6a6e5d97931afd042d24a5108d45/force-MFA-Group.png" alt="force-MFA-Group.png" />

## Github
2FA is enforced at the organization level. 
<img width="951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b9ea6ebb817af6b7ea51f68756a14367a6296fe/GH-MFA-Required.png" alt="GH-MFA-Required.png" />
Apps that use GH for Auth:
- Atlas
- SideKiq
- ArgoCD (SOCKS Proxy required)
- Jenkins (SOCKS Proxy required)
- Sentry (SOCKS Proxy required)

## Datadog 
Our instance of Datadog, although specific to VAGOV Platform, is managed by DOTS-VA via Okta auth. It requires a VA PIV Card to sign in.
<img width="406" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa8fa108b9ee08b5758fc920c342d54456e080a3/Datadog-OKTAscreen.png" alt="Datadog-OKTAscreen.png" />

## SOCKS 
Every SOCKS user is required to generate a personal SSH key that will be leveraged for their SOCKS access every time the use it.

## Postgres 
MFA authentication is not required. Our PostgreSQL RDS instances currently have their credentials stored in the AWS parameter store. Access to these various credentials is restricted and requires a privileged AWS account which leverage MFA.

**Comment by hgbarreto** [comment]
The remaining items are addressed in the sensitive repo below:
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/infrastructure
