### ISSUE TITLE
FE | Profile | Documentation Dust Up

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83776]
## Background
Update our FE documentation 

## Acceptance Criteria 
- [ ] we have updated documentation to help onboard our new full stack engineer

**Comment by adamwhitlock1** [comment]
this will roll over to next sprint. I have about half of it done, but am working on updating the rest still.

**Comment by adamwhitlock1** [comment]
Going to close this out, as I have finished updating the docs.
