### ISSUE TITLE
Remove copy, link, and pdf related to Agent Orange-related ships

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8377]
Ask from Sandy Tadeo and VBA - 

To remove the PDF list, link and text relating to Agent Orange - exposed ships from this page:

https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/

Text and copy are removed.
@ncksllvn  or @kelsonic  - This pdf I believe is housed in the GitHub assets folder - could one of you delete it, please? thanks.

https://www.va.gov/shiplist-agent-orange.pdf

**Comment by AnneHurley** [comment]
@RLHecht  - after PDF is deleted from GH, this will be ready for copyedit:
https://prod.cms.va.gov/node/876/edit

**Comment by kelsonic** [comment]
PR merged! 🙂

**Comment by RLHecht** [comment]
This has been published. Moving to validate.

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket.
