### ISSUE TITLE
Implement 6 va-icons on landing page body

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#83788]
### User story

As a Cartography team member, I want to update the landing page body's icons to va-icon, so that we are on the new icons going forward.

### Notes
- See #83415 for decisions on Payments and Supplies icons (tl;dr: no change)

Possible tasks:
- 

## Acceptance criteria

- 6 icons in landing page boxes updated to use new va-icon instead of font awesome
- UX review

**Comment by dcloud** [comment]
Per Sara, pending confirmation:

> The six icons are:
> - Appointments: calendar_today
> - Messages: forum
> - Medications: pill
> - Medical records: note_add
> - Payments: attach_money
> - Medical supplies: medical_services

**Comment by wesrowe** [comment]
pending whose confirmation, @dcloud? I'm trying to discern the blockage level here. Cc @LynneJohnson224

**Comment by dcloud** [comment]
Blocked by department-of-veterans-affairs/vets-design-system-documentation/issues/2875, " Pill icon has hard-coded fill value" in Design System

**Comment by dcloud** [comment]
Related 2ndary Nav PR: department-of-veterans-affairs/vets-website/pull/30009

**Comment by dcloud** [comment]
This is the design-system [PR to update the corrected pill icon fill](https://github.com/department-of-veterans-affairs/vets-website/pull/30036)… once that is merged, I should be good to update my PR and unblock this ticket

**Comment by brea11y** [comment]
All icons match what are shown in Figma (including the pill icon). No accessibility concerns.

**Comment by LynneJohnson224** [comment]
@dcloud - can this ticket be closed? @brea11y reviewed and gave her sign off.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified the 6 icons on the landing page. See attached screenshot for reference. Closing this ticket

<img width="1509" alt="Screenshot 2024-06-05 at 7 17 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/33225134-727d-44e8-b3fd-fde5d8dc4850">
