### ISSUE TITLE
[FE] Alert content updates

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83781]
## Background

CAIA updates

## Tasks

- [ ] Content update to alert for "[can't get upcoming appts from MAP](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=996-28105&t=bYoprNsCMlOWF1eT-4)"
- [ ] Body content update to alert for "[pre-check-in demos don't need to be reviewed success alert](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=961-51636&t=bYoprNsCMlOWF1eT-4)"

**Comment by benbrasso-agile6** [comment]
@loripusey same for these; needs to be placed into an epic and placed into a sprint. your call on priority. Might be good to do these prior to stage review.

**Comment by brianseek** [comment]
PR ready for when next sprint starts

**Comment by benbrasso-agile6** [comment]
1) LGTM
2) I believe a separate ticket superseded this. Sorry. Can find if needed.

**Comment by brianseek** [comment]
@benbrasso-agile6 so these are changing again? Yeah find that ticket if you can, we are trying to finish up all new landing page things.
