### ISSUE TITLE
Final Validation of Content, Forms, and Search KPI Dashboards QC

### ISSUE THREAD

**Issue by Blivaditis** [department-of-veterans-affairs/va.gov-team#83786]
### Description 
The initial QC of the standard Content, Search, and Forms KPIs dashboards are completed, the dataset has been recreated and is functional in its current state. There are however some updates that we need to make:

---

### Tasks
- Resolve remaining items from QC findings of Search, Forms, and Content KPI dashboards
-- [Data QC & Mapping Findings & Log](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log)
-- [GA4 Domo QC Record](https://docs.google.com/spreadsheets/d/1oaoXivzL854woEIUzgsPReoKW55Spz2p4S5WI_u_QHQ/edit#gid=721881515)
- Resolve remaining cards, and data issues for Search, Content, and Forms KPI

### Acceptance Criteria

- The GA4 powered dsahboards for the following Domo dashboards matching as expected
- [x] Search KPIs
- [x] Forms KPIs Dashboard matching as expected
- [x] Content KPIs

**Comment by johnny-jesensky-adhoc** [comment]
These standard dashboards are functioning and QCs and dataset issues have been resolved. Findings and changes have been documented in the below artifact on Confluence.

[Data QC & Mapping Findings & Log](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log)

FYI @Blivaditis, @dorseypa1, @ChristineYoungZA
