### ISSUE TITLE
SOCKS access for Devi Peruri

### ISSUE THREAD

**Issue by deviperuri-tw** [department-of-veterans-affairs/va.gov-team#83798]
### Your Name

Devi Peruri

### Your Email

devi.peruri@thoughtworks.com
devi.peruri@va.gov

### Your GitHub Handle

deviperuri-tw

### Your Role and Team

Senior Data Engineer and Chatbot/virtualAgent team

### Product Manager (PM) name and email

Nathalie Rayter, nathalie.rayter@va.gov

### Product Owner (PO) name and email

Nathalie Rayter, nathalie.rayter@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINXskwESOvnumB5P83Da5IAiWg8lbkgXy85SCSs1HzJN [deviperuri@devis-mbp-2.lan](mailto:deviperuri@devis-mbp-2.lan)

### E-QIP Transmittal Confirmation

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/f120634d-1dff-4ce9-acab-b31222a83eed">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by deviperuri-tw** [comment]
Hello, I am able to login to Atlas and see my name and account now.
Could you please re-assist me with this request? Thanks a lot.

**Comment by deviperuri-tw** [comment]
per this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/92502, I was added to the roaster. Could you please grant SOCKS access? Thanks!

**Comment by deviperuri-tw** [comment]
hi @patrick-black-oddball, my thoughtworks email has been updated in Atlas. Please go ahead and grant me access. I appreciate you waiting on this.

**Comment by bmatos312** [comment]
@deviperuri-tw Hello Devi, Patrick requested a fuller screenshot of the e-quip when you get a chance

**Comment by deviperuri-tw** [comment]
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/c15d0775-6efe-41d9-a7e1-305aa23b42f9">

**Comment by patrick-black-oddball** [comment]
transmittal email confirmed

**Comment by deviperuri-tw** [comment]
Updated ssh key - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN0CWxXHj81PLZ/I8AHuqs/y9oJiISw3pN6nx2Yj+Sjd deviperuri@devis-mbp-2.lan

**Comment by deviperuri-tw** [comment]
updated ssh key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINXskwESOvnumB5P83Da5IAiWg8lbkgXy85SCSs1HzJN deviperuri@devis-mbp-2.lan

**Comment by barbarello** [comment]
updated Public SSH Key section in this GH issue

**Comment by barbarello** [comment]
@deviperuri-tw Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
