### ISSUE TITLE
Jenkins clean up

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#83790]
## Description

- Jenkins has been migrated over to AL2
- The AL1 instance can be stopped
- Let's keep it around for a bit as a safety net

## A/C

- [x] Stop AL1 Jenkins Instance
- [x] Create a follow-up ticket once the AL1 instance has been stopped; this ticket will be for tearing it down, for good

**Comment by Efe-Oddball** [comment]
Al1 Jenkins instance has been stopped
