### ISSUE TITLE
[Epic] Lighthouse Document Upload Migration

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#83837]
## Description

There are several ancillary jobs that submit various documents to EVSS after a Form 526 is successfully submitted. As with the Form 526 submission itself, we need to port these document upload jobs to submit to Lighthouse instead of  EVSS. In this case, we will use the [Lighthouse Benefits Documents API](https://dev-developer.va.gov/explore/api/benefits-documents/docs?version=current).

Much of the discovery and implementation work was started [here in one large PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13835).

However, this project got deprioritized, first because we wanted to be able to poll Lighthouse after these documents are uploaded to see if they made it to the eFolder (by building a polling system [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75804)). **Releasing the polling system first is considered a semi-blocker to moving ahead with the migration**

Secondly, we prioritized [eliminating silent failures in the current uploads](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/81612) to stop these uploads slipping through the cracks.

[Here is a little status matrix on the spec as it stands on all of these to help us keep track:](https://dsva.slack.com/archives/C02CQP3RFFX/p1725386492372089?thread_ts=1718634292.110749&cid=C02CQP3RFFX)
- BDD Instructions, migrating to Lighthouse, no failure mailer planned, no polling planned
- Form 0781, migrating to Lighthouse, failure mailer planned, polling planned
- Veteran uploads, migrating to Lighthouse, failure mailer launched, polling planned
- Form 4142, not migrating to Lighthouse (yet), failure mailer planned, no polling planned (because we aren't sending it to Lighthouse) (edited) 

[Release Plan: Lighthouse Migration for Ancillary Document Uploads](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Lighthouse%20Migration%20for%20526%20Ancillary%20Forms.md)

**Comment by lisacapaccioli** [comment]
New platform requirement that will affect our work. Super supportive of this governance that helps us work toward 0 silent failures.

Matthew Dingee: 
As stated in yesterday's Team of Teams, there is a new QA standard for endpoint monitoring:
Endpoint Monitoring
All endpoints that the product accesses need to be monitored in [Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad). Monitors should be configured according to the guidance in [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/endpoint-monitoring.md). To satisfy this standard, VFS teams must complete a [playbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/template.md) that details how they will respond to any errors that fire.
This is a launch-blocking standard, meaning teams MUST have alerts set up in Datadog, and teams MUST submit their playbook.
Enforcement of this QA standard will begin this upcoming Tuesday September 10, and will be enforced immediately at Staging Review.
This standard is intended to help us get to Zero Silent Failures (silent to the Veteran) across the entire platform. Thank you for your hard work and support in getting us to this goal.

**Comment by lisacapaccioli** [comment]
@NB28VT and @alis - See [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md) for changes in labeling that will need to be included in your work.
