### ISSUE TITLE
Move help section per designs

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#83838]
## Description
We noticed from research that the help section was hard to find on the status page, especially for a user with many claims. We should move this to be more easily visible in order to get Veterans all the information they need.

## Acceptance Criteria
- [ ] Go to https://staging.va.gov/my-health/travel-claim-status
- [ ] See the help section in the same place as on the designs

## Demo
- Demoable? Yes
- How? Follow AC above
- Impact? Small demo, solidifying page in prep for launch

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by kjduensing** [comment]
@micahtaylor could you please add a link to the design showing the moved help section to this ticket?

**Comment by micahtaylor** [comment]
Design ticket documenting the change is [here](https://adhoc.rec.pro.ukg.net/ADH1000ADHOC/JobBoard/1893bc9c-1fe2-4c48-90e8-0de36fe3f2b2/?q=&o=postedDateDesc&f5=d0PPkQF6QkyGf3nmzWFSCQ). Let me know if you need more than that @kjduensing

**Comment by micahtaylor** [comment]
Designs are documented [here](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/gh/department-of-veterans-affairs/va.gov-team/80038#issuecomment-2101476074). Let me know if you need anything else @kjduensing

**Comment by athifw** [comment]
@micahtaylor here is what I've done locally - does this look good? Should I take off the link to the phone number?

<img width="982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK00yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12bff21d2f7be25478aa41d6529a16fe384b60a0/Screenshot%202024-06-04%20at%202.08.48%E2%80%AFPM.png" alt="Screenshot 2024-06-04 at 2.08.48 PM.png" />

**Comment by micahtaylor** [comment]
[Phone number link is good according to VADS guidance](https://design.va.gov/components/telephone#usage), so we'll keep it.

**Comment by athifw** [comment]
Oops.. forgot to take out the `"va-introtext"` class. Here it is without that class:

<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL28yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d38ae78bc5063f993cc578dd5353292213610b5a/Screenshot%202024-06-04%20at%202.26.26%E2%80%AFPM.png" alt="Screenshot 2024-06-04 at 2.26.26 PM.png" />

**Comment by micahtaylor** [comment]
Looks good
