### ISSUE TITLE
[LH Doc Upload] 0781/a (1) implementation

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#83846]
## Acceptance Criteria

- [x] Mask this behavior behind a Flipper
- [x] Update the `EVSS::DisabilityCompensationForm::Form0781` job to use the shared endpoint functionality that was implemented in https://github.com/department-of-veterans-affairs/va.gov-team/issues/88297
- [x] Add logging
- [x] Create a document upload record so we can poll Lighthouse later to determine if the upload failed and send a mailer if needed
~[ ] Ensure failure mailer sends~ (Moved to testing ticket: https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/7?pane=issue&itemId=84546667&issue=department-of-veterans-affairs%7Cva.gov-team%7C95694)

**Comment by AmyPlange** [comment]
Blocked waiting for BDD instructions release CC: @ajones446 during standup

**Comment by ajones446** [comment]
WIP Draft PR: https://github.com/department-of-veterans-affairs/vets-api/pull/18625

**Comment by ajones446** [comment]
Updated WIP: https://github.com/department-of-veterans-affairs/vets-api/pull/18923

**Comment by ajones446** [comment]
Related PRs:
Part 1: https://github.com/department-of-veterans-affairs/vets-api/pull/19186
Part 2 (specs): https://github.com/department-of-veterans-affairs/vets-api/pull/19231
