### ISSUE TITLE
10-7959f-1: mask SSN when pre-filled

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83841]
As a logged in user on VA.gov, I want my social security number to be masked when filling out the FMP registration form online, so that my personal information is more secure.

- In the SSN field, the user's SSN should be masked so only the last 4 digits can be viewed. 
- If the user wants to edit their SSN, they will need to enter their entire SSN into the field rather than being able to edit a portion.
- url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/

## Acceptance Criteria
  - Given a user is logged in and filling out the FMP registration form online
  - When the user's SSN is pre-filled in the SSN field
  - Then only the last 4 digits of the SSN should be visible, with the rest masked
  - And if they want to edit, the user must enter their entire SSN into the field

**Comment by reiting** [comment]
This has been done and is in team review. I'm including a screenshot, where I prefilled data locally and it shows as masked. It'll need to be tested on staging to be sure it actually works with prefilled data from the backend. 

<img width="635" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8086c62f2ecb175d5a231c25ef32fbfc46559c6/Screenshot%202024-06-11%20at%208.05.05%E2%80%AFAM.png" alt="Screenshot 2024-06-11 at 8.05.05 AM.png" />

**Comment by marywang2** [comment]
@reiting this goes back to question about process - but should this be in review if it's waiting on team review? Thinking it should still be in progress column but open to discussion.

**Comment by reiting** [comment]
We are having some issues on this with the dots being saved insterad of numbers when the ssn is masked. Putting back in progress to continue work on it.

**Comment by reiting** [comment]
Michael and I collaborated a lot on this one, and it's now in team review

**Comment by reiting** [comment]
This is now in platform review!

**Comment by reiting** [comment]
@marywang2 this has been approved and merged. It should be on staging in a few hours.
