### ISSUE TITLE
Update toxic exposure page visibility logic

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#83849]
## Issue Description
Utilize new attribute, `includeToxicExposure`, in `formData` prefilled by vets-api to determine whether to show toxic exposure section of form 526.

- update `Form526EZApp` to reference new attribute, replacing current toxic exposure toggle
- remove reading of toggle and setting of session storage 
- in [content/toxicExposure.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/content/toxicExposure.jsx#L135), update showToxicExposurePages to reference `includeToxicExposure` instead of toggle
- manually test 
- update unit tests to key off formData in place of session storage
- update [TE E2E test](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/tests/toxic-exposure.cypress.spec.js#L30), refactoring to use formData in place of toggle

## Front end tasks
- ~Ensure the page is styled according to design spec.~
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- ~Run axe checks using the Chrome or Firefox browser plugin~
- ~Test for color contrast and color blindness issues~
- ~Zoom layouts to 400% at 1280px width~
- ~Test with 1 or 2 screen readers~
- ~Navigate using the keyboard only~

## Acceptance Criteria
- [ ] ~Designer comments on this issue to approve page styling~
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] ~The data returned matches API response (for given user or scenario)~
- [ ] ~All axe checks pass~
- [ ] ~All color contrast checks pass~
- [ ] ~All zoom testing passes~
- [ ] ~All keyboard checks pass~ 
- [ ] ~All screenreader checks pass~
- [ ] Manually test running vets-api locally ensuring new form vs. IPF behaves as expected (IPF should not be presented with TE section, unless started with TE from new)

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by freeheeling** [comment]
In each `PUT` request to `v0/disability_compensation_in_progress_forms/21-526EZ`, update frontend to accept, store, and return the new `includeToxicExposure` attribute, set and sent by backend upon starting/creating a new IPF.

**Comment by tblackwe** [comment]
@freeheeling please update this ticket to reflect the new design.

**Comment by freeheeling** [comment]
Utilize the presence of the `includeToxicExposure` attribute in `formData` to determine the form version to present to a user.

Confirm that with each `PUT` request to `v0/disability_compensation_in_progress_forms/21-526EZ`, the frontend is accepting and returning the new `includeToxicExposure` attribute in 'formData`, set and sent by vets-api when starting/creating a new IPF.

A user can choose to apply now from `/disability/file-disability-claim-form-21-526ez/start` and starts the Disability Compensation Application from the `/disability/file-disability-claim-form-21-526ez/introduction`, the latter of which includes the form expiration date.

Network requests on both pages get feature toggle data from `/v0/feature_toggles?&cookie_id=<id>`, indicating the toxic exposure Flipper state for the current user:
```
{
  "name": "disability526ToxicExposure",
  "value": boolean
},
{
  "name": "disability_526_toxic_exposure",
  "value": boolean
},
```
Selecting start application requests from `/v0/disability_compensation_in_progress_forms/21-526EZ` vets-api, which responds with `formData` that includes the `includeToxicExposure` attribute for a user whose `disability_526_toxic_exposure` Flipper is enabled.

Thus, the FE must first evaluate the feature toggle in determining which expiration date to display (**note:** the date change will be implemented after rollout is complete, and will therefore not be dependent on the feature toggle). Then, throughout the duration of an In Progress Form's existence, wherever the toggle would otherwise be evaluated, the presence of the `includeToxicExposure` attribute in the `formData` should be referenced in determining the form version.

**Comment by freeheeling** [comment]
![Screenshot 2024-06-12 at 3 28 26 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/50811220/d7346c2f-860e-4ac5-a824-2df06f49ff1b)
![Screenshot 2024-06-12 at 3 28 04 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/50811220/21ef462e-9b16-4642-b29e-246ad6edee55)
