### ISSUE TITLE
[UX] 10-10EZR PG: Investigate PG

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#83855]
As a Veteran, I would like to see what Priority Group i am in and understand it so that I know what benefits I get, and why, and how I could potentially get more benefits. 

- [ ] Apply this to Attach Documentation (probably V2)
- [ ] **Have a better understanding of Priority Groups and have proposed next steps**

**Comment by katelyncai** [comment]
Tracking some discovery work for understanding priority groups and exploring opportunities for more accessibility/transparency here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716237131877/d5445e1065514e74c072bbfca413ca6a7f79081e?sender=ube02cc3d1108083a94f75471
