### ISSUE TITLE
Determine requirements for Supporting Document Uploads for Digital Accreditation 

### ISSUE THREAD

**Issue by a6marinos** [department-of-veterans-affairs/va.gov-team#83864]
- Which file formats are accepted/received?
- Reference guide: https://www.va.gov/OGC/docs/Accred/HowtoApplyforAccreditation.pdf
- 
AC - Determine what endpoint will be used, confirm file size & file types.

**Comment by a6marinos** [comment]
Currently planning for this to be a collaborative ticket between engineering and design, with input from Alex on previous discussion on potential solutions. We can definitely split this out to separate tickets for engineering research and design research if needed.

**Comment by hdbaines** [comment]
Needs an API from GCLAWS - Reach out to Randy Trexler for additional context

**Comment by hdbaines** [comment]
Need to break up into 2 tickets
1. Front End investigate front end
2. Backend, investigate GCLAWS API - confirm file size limit, confirm file types

**Comment by a6marinos** [comment]
Backend tickets for aligning with GCLAWS schema:
[Part 1](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/87164)
[Part 2](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/92751)
