### ISSUE TITLE
Add alert scenarios on provider list page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83872]
## Tasks

- [ ] ~[Patient indicated provider is NOT opted in to digital self-scheduling](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1633-68134&t=eqowEJC9Bcrrt6cO-4)~
- [ ] [Patient cannot receive care from patient indicated provider because of eligibility](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1661-6591&t=eqowEJC9Bcrrt6cO-4)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/83872?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by anita-halici** [comment]
@simiadebowale  - I noticed this task rolled over to the next sprint, what is left to be done in this ticket?what is the blocker?
