### ISSUE TITLE
10-7959f-1 Spike: remove phone number validation

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83884]
As a user, I want to be able to enter my international or domestic phone number in the field so that I can get contacted if there are any issues with my registration.

url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/contact-info
https://design.va.gov/components/telephone
- user should not be limited to 10 digits upon entry
- otherwise functionality/display remains the same
- basic validation for numbers
- verify longest country code (with phone number) and set to max limit

Acceptance criteria:
Given the user is filling out the FMP registration form online,
When they go to enter in their phone number on the contact information page
Then they should be able to enter either an international or domestic phone number without being restricted by the number of digits

**Comment by pshahVA** [comment]
It would probably be good to understand what limitations they may have in the current back end system (as this will be manually copied from the form and entered there)

**Comment by marywang2** [comment]
@pshahVA  Yep - we were supposed to cover this in the last meeting but ran out of time. Need to discuss today.

**Comment by reiting** [comment]
Looks like the longest phone numbers should not be longer than 15 digits.

**Comment by reiting** [comment]
@marywang2 I'm not sure of the end goal since this is a spike and there is a separate ticket for the work. However, I would recommend a validation that the input is just numbers and add a maxLength of 15, or 20 at most if you want to have some padding just in case something wonky comes along.
