### ISSUE TITLE
Forms migration

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#8388]
**Acceptance Criteria**
- [x] VA Forms are fully populated in CMS with published content from the DB.
- [x] Nightly migrations update and add new content from Forms DB.

**Implementation**
~~Migration code written and tested using DB data dump (CSV)~~  Migrations with two differing sources is not an option.
~~Code modified to use DB source directly and tested in devshop environment~~
- [x] Establish db connection locally https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2003
- [x] File is now present here http://prod.cms.va.gov/sites/default/files/migrate_source/va_forms_data.csv
- [x] Establish db connection in CMS BRD environments (dev, staging, prod)
- [x] Determine the unique idto use as the source key.  This is required for a migration.
    * Will be using `rowId` as the unique identifier, however will also attempt a lookup of url in case another row is added to the db with the same filename and path, that was meant to replace one that was removed.
- [x] Add nightly run of migration to yml tasks
- [x] Settings to handle updates on repeated runs.  (track changes, update fields.) 
- [x] Alias pattern set for `/find-forms/about-form-[form-nbr]`  Defined here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-forms-detail-pages.md
- [x] Update documentation in CMS repo to explain the migration and reading strategy.
- [x] PR submitted for review by CMS team https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2060

~~Note that this does not include handling forms deleted in the DB. That is currently blocked, pending a response from the Forms DB team about how deletions will be handled there.~~

**Key requirements of the migration** Still in discovery on this.

- [x] if the `IntranetOnly` field in the db is 1, don't migrate the record (the form's not public)
- [x] The owner (administration) field in the db should map to a top-level section (administration) term in drupal.  Maps to `Public websites team > Forms`

- [x] unpublish if deleted.   
- ~~**UNATTAINABLE with current source data.**~~ Unpublish forms from cms when db item is flagged for deletion.  Update 7/12:  Thi is now possible due to the addition of the `Deleted` and `Deleted` date field.
This is currently at odds though with the method of setting all new forms to unpublished.  As upon update all published forms would end up being unpublished.  This is going to need a custom handler.  Also a different log message should be set to indicate it was unpublished by the migration.

- [x] Page title (= "VA Form" + Form title)
- [x]  Form title
- [x]  Form number
- [x]  Form administration
- [x]  Issue date
- [x] Revision date
   inconsistent format of date is making this more difficult.
- [x] Number of pages
- [x] Link to form 
When there is only a file name, the full URL for Link to form will be generated using the pattern outlined by @jenniferlee-dsva in Slack: According to Kevin Reid:
IF the form owner ID is VA, URL_prefix= https://www.va.gov/vaforms/va/pdf/ + FileName – like this: https://www.va.gov/vaforms/va/pdf/VA40-10088.pdf
IF VBA, URL_prefix= http://www.vba.va.gov/pubs/forms/ + FileName 
IF VHA, URL_prefix= https://www.va.gov/vaforms/medical/pdf/ + FileName  – like this: https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf

**Documentation:**
- [Data flow overview](https://whimsical.com/UpSBvigLWBK72p8ajG8v3a) 
- [Data Sources on Node](https://whimsical.com/LeUX6vYYik6FGVgk6Ax3wH)
- [Source and Data field mappings](https://airtable.com/tblCJfaAxy7Ey3n9K/viwvMeFjt9tyK1tKV?blocks=show) (airtable)
- CMS PR for content type https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1774
- [Docs of discovery for form detail landing page.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/status-and-decisions.md#042920)

**Comment by jenniferlee-dsva** [comment]
@beeyayjay - migration discussion per today: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/status-and-decisions.md#042920

**Comment by swirtSJW** [comment]
I have a bit of data remapping to do and a few processes to alter in the migrate pipeline, but this is encouraging.
![image](https://user-images.githubusercontent.com/5752113/84697407-108f6700-af1c-11ea-8658-c7bb93c3b73b.png)

**Comment by swirtSJW** [comment]
The PR is in code review and QA.   https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2060
Will likely go out with Monday's CMS deployment.

**Comment by jenniferlee-dsva** [comment]
This is complete, per Steve's work tracked on the CMS team board, so closing.
