### ISSUE TITLE
10-7959f-1: Staging updates - confirmation page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83894]
Update copy for confirmation page on 10-7959f-1 to match designs:
- url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/confirmation
- Figma link: https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?node-id=732-40895&t=Qe9eQ23a1VyP2yZg-0
- green alert style around submission message
- remove confirmation number and text
- update text underneath blue box

**Comment by reiting** [comment]
This has been merged to staging @marywang2

**Comment by marywang2** [comment]
@reiting please add the name and text to the submission information, also please match the "What happens next" copy to the figma.

**Comment by reiting** [comment]
@marywang2 The user's name does show correctly on staging! And please let me know what is wrong with the what happens next text? As far as I can tell, it matches Figma<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0l2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44db7b273f8e681727779e29124712310ab1ef95/Screenshot%202024-06-03%20at%2011.21.05%E2%80%AFAM.png" alt="Screenshot 2024-06-03 at 11.21.05 AM.png" />

**Comment by marywang2** [comment]
@reiting weird, I wasn't seeing the changes before - but they are showing now. Not sure if there is a delay on staging?
