### ISSUE TITLE
Rec 19: Remove redundant entry from sponsor to applicant

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83907]
As a CHAMPVA applicant, I want to confirm that my address is the same as the sponsor's so that I don't have to type it in again.

### Acceptance criteria
Given a user filling out form 10-10d
- When prompted for their address
   - Then the user can select a previously entered address if it's the same as theirs (e.g. the sponsor's address)
 
### Research recommendation for reference
[Recommendation 19](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d9593da7070de683ad620091d43c2c8f3a1cf117/products/health-care/champva/1010D/research/users/Usability-Accessibility%20Test%20(April)/preliminary-form-improvements.md)

Participants were annoyed that they had to type in their address again after typing the same address for their sponsor.
Recommendation: Offer the ability to select a previous address after the sponsor's address rather than after the first applicant.

**Comment by michaelclement** [comment]
Work is [done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30081). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes and @marywang2  this has been merged and will be review-able on staging shortly. Thanks!
