### ISSUE TITLE
Rec 25: Alter sign in language

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83909]
As a CHAMPVA applicant, I need clearer guidance about signing in before I start my application.

### Acceptance criteria
Remove “Sign in to check your application status” from the page.

### Research recommendation for reference
[Recommendation 25](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d9593da7070de683ad620091d43c2c8f3a1cf117/products/health-care/champva/1010D/research/users/Usability-Accessibility%20Test%20(April)/preliminary-form-improvements.md)

Many participants didn’t notice or struggled to find the “Start your application without signing in.” They almost immediately clicked on “Sign in to check your application status” instead, even though the scenario set by researchers was that they had never applied for CHAMPVA before. Many had to be told where to find the “Start your application without signing in” link so they could continue the test.
Recommendation: Increase the prominence of the “Start your application without signing in” link. Consider moving the “Sign in to check your application status” lower on the page to reduce distraction.

**Comment by jamiefiore** [comment]
@marywang2 @baltes 
I updated this on [this Figma page](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/CHAMPVA-Application-(10-10d)-User-Testing-Prep?node-id=2017-51097&t=If1idGk4JtbGg0HH-0). All of the new updates post testing can live on this page. I'll eventually add the entire completed flow once we get the other updated in and completed. 
@StevenStraily @rachaelpenfil I added back the H2 above the Process list. It seems to have dropped off on the latest version. I also added annotations.

**Comment by marywang2** [comment]
@jamiefiore just making sure I'm clear on the change, you just removed the first sign in box right?

**Comment by jamiefiore** [comment]
@marywang2  Yeah. Just removed the Sign in box. The comment about adding back the H2 was a discrepancy on the Figma file that I fixed. It's correct on staging.
FYI, Some of the copy on Staging doesn't match up with what is on the figma file. Also the Sign in button on the alert is missing on Staging

**Comment by marywang2** [comment]
We will need to bundle all the 10-10d changes in another sprint (if there are more). In the meantime, I created a separate ticket [here](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/85308). @baltes @jamiefiore

**Comment by jamiefiore** [comment]
@marywang2 Awesome! Thanks Mary!
