### ISSUE TITLE
Rec 5: Make "sex assigned at birth" language consistent across pages

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83905]
### Bug fix
On the review page, content in the accordions still reads “Gender” rather than “Sex listed at birth.” Change content on review page to read "Sex listed at birth"

### Research recommendation for reference.
[Recommendation 5](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d9593da7070de683ad620091d43c2c8f3a1cf117/products/health-care/champva/1010D/research/users/Usability-Accessibility%20Test%20(April)/preliminary-form-improvements.md)

On the review page, content in the accordions still reads “Gender” rather than “Sex listed at birth.”
Recommendation: Ensure the content on the review screen matches the content on the form itself.

**Comment by michaelclement** [comment]
[Work is here](https://github.com/department-of-veterans-affairs/vets-website/pull/30087). Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes and @marywang2  this has been merged and will be review-able on staging shortly.
