### ISSUE TITLE
Rec 10: Make page headings unique

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#83908]
As a CHAMPVA applicant, I want pages to have unique headings so that it's clearer how I'm progressing through the application.

### Acceptance criteria
- Heading on each page of the application are unique

### Research recommendation for reference
[Recommendation 10](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d9593da7070de683ad620091d43c2c8f3a1cf117/products/health-care/champva/1010D/research/users/Usability-Accessibility%20Test%20(April)/preliminary-form-improvements.md)

Some participants seemed to be confused when two pages had the same heading, one after the other. This happened most frequently with “Relationship to Sponsor”: when the first answer was “child,” another page with the same heading appeared asking the participant to clarify that relationship (e.g., biological child, stepchild).
Recommendation: Ensure each page has a unique heading.

**Comment by jamiefiore** [comment]
Headers are updated and documented on this[ Figma file](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/CHAMPVA-Application-(10-10d)-User-Testing-Prep?node-id=2017-51097&t=CbrOKZRRPMbI6sX4-0)
Will review with the design team.

**Comment by jamiefiore** [comment]
@marywang2 @baltes I updated the headers. Here's[ figma file](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/CHAMPVA-Application-(10-10d)-User-Testing-Prep?node-id=2133-65866&t=SPiGcNE5G7bNQqut-4). There is a notes section with a list of updates with their linked sections.

**Comment by marywang2** [comment]
For this one, @baltes let me know if we should coordinate on any 10-10d changes for FE.

**Comment by baltes** [comment]
@marywang2 I'll create a story for this and ask @michaelclement to take a quick look to see if it needs refinement.

**Comment by baltes** [comment]
[Front end follow up ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/86011)
