### ISSUE TITLE
EADR - Document Technical Definitions

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#83911]
As part of generating the EADR Report, we need to create documentation for...

- [x] The technical definition of each data query

**Comment by joeniquette** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/External%20Auth%20Data%20Reporting/Working_docs/Queries_for_data.md

**Comment by bramleyjl** [comment]
More information about the technical queries can be found in #84139, ongoing maintenance of the queries Github document is covered in #84351
