### ISSUE TITLE
clean up remediation (follow up to Scotts work)

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#83928]
## Context
- [The Audit produced a short list of 'untouched submissions' that needed remediation.](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/80624)
- Scott took this list of untouched IDs and ran remediation. Most of them passed but some failed for various reasons (no ticket?)

## Next steps
- get a list of all the failed IDs.  this means everything in the CSVs with an error, as well as a list of 19 (?) that failed outright.  @freeheeling if you could please attach those 19 in a comment.
- get the task server back up and running.  This is the blocker, and Kyle M on platform is working on it with @SamStuckey
- Re-attempt these failures on the task server.
- Assuming some still fail, debug, hack, and discuss with @emilytheis  what we want to do until all of these are handled in some fashion

**Comment by freeheeling** [comment]
19 submission IDs that failed processing and subsequent creation of a signed_link:
```
[67380, 193731, 253684, 254141, 254836, 254866, 255868, 256483, 439266, 439288, 439311, 439368, 470222, 491894, 719974, 2453816, 2484393, 2621886, 2622136]
```

**Comment by SamStuckey** [comment]
BLOCKED: task server is down, awaiting devops help

**Comment by SamStuckey** [comment]
UNBLOCKED: server is back up

**Comment by SamStuckey** [comment]
BLOCKED: there is a bug in the batch that on which this cleanup is predicated, [ticket to fix that (and probably the original batch) here](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/84377)

**Comment by SamStuckey** [comment]
UNBLOCKED: patched the bug in prod and in the script.  This work has changed to include rerunning the entire batch, with contention and json files now that the 4142 fix is in place
