### ISSUE TITLE
Accessibility Testing for Cartographers, MHV on VA.gov, MHV Secondary Navigation

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va.gov-team#83926]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

@brea11y

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

Color testing went well. There were some initial color contrast issues in the hover state that have now been corrected by using a darker shade of blue for the copy and icon.

### Who completed the axe scans?

@brea11y

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### axe DevTools scan results

0 issues found during axe DevTools scan.

### How did axe testing go?

Testing went well. 0 issues found.

### Who completed the content zoom and reflow test?

@brea11y

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

Testing went well. No issues detected at up to a 400% zoom.

### Who completed the keyboard navigation test?

@brea11y

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Keyboard testing went well. All navigation links can be tabbed to and activated with keyboard. All links receive focus, as well.

### Do you have any other results to share?

I also testing the secondary navigation bar with a screenreader (all read out as expected during testing - including VoiceOver) and on mobile devices (both iOS and Android). Everything looked and functioned exactly as expected.

**Comment by wesrowe** [comment]
No issues in this ticket, so I'm closing. (Collab cycle ticketed a hover-contrast issue separately.)
