### ISSUE TITLE
Documentation - create dev guide/README

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83938]
From this [document](https://dvagov-my.sharepoint.com/:w:/r/personal/premal_shah_va_gov/Documents/Overall%20Finding%20of%20IVC%20code%20by%20VA%20office%20of%20CTO%20Engineering.docx?d=w22a7cc029d9347a8800c9ecbc90fa513&csf=1&web=1&e=Uh37rA)
<img width="466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d27a33881ddd3227da0021f653588adfff4fd4a4/Screenshot%202024-05-24%20at%201.17.17%E2%80%AFPM.png" alt="Screenshot 2024-05-24 at 1.17.17 PM.png" />

- dev guide/README document created and linked in GH
- socialized with team and stakeholders

**Comment by michaelclement** [comment]
@marywang2 [Ready for review](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/ivc-champva/README.md). Thanks!
