### ISSUE TITLE
10-7959c: update copy - Beneficiary information section

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83939]
As a user on VA.gov, I want to fill out the OHI form with the latest information so that I can report any changes to my other health insurance.

Common page elements:
- breadcrumb (url: va.gov/family-and-caregiver-benefits/health-and-disability/champva) - url is not yet live
- title and subtitle
- progress indicator
- footer

Pages in this section:
- page heading (first name populates dynamically from 'first name' field)
- beneficiary information (name and dob)
- beneficiary identification information (SSN)
- beneficiary mailing address
- beneficiary contact information (phone number)

Figma link ("Prep for staging review"): https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Y8cWvTGeyw2lKO6X-0

Acceptance criteria:
  - Given the user is on VA.gov and filling out the OHI form 
  - When the user gets to the beneficiary information section and enters information
  - Then the updated information will be saved and displayed in the PDF attachment for the form

**Comment by michaelclement** [comment]
[Work is done here](https://github.com/department-of-veterans-affairs/vets-website/pull/30058). @marywang2  Per our conversation where we determined that this form won't make use of pre-fill, I didn't make any of the prefill-centered changes.

Currently waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2  this has been merged and will be review-able on staging shortly. Thanks!

**Comment by marywang2** [comment]
@michaelclement a few changes:
- add breadcrumb (guidance is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/champva-ohi-7959c.md): URL (not yet live): va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/
Breadcrumb (full for bigger breakpoints): Home > Family and caregiver benefits > [Health and disability H1] > CHAMPVA benefits > [10-7959c form H1], use "CHAMPVA benefits" for smaller breakpoints/mobile
- update title to match Figma
- add subtitle
- add footer
- change heading to "Beneficiary" (to match figma) and "Beneficiary information"

**Comment by michaelclement** [comment]
- [X] ~~add breadcrumb~~ -> [See this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30102)
- [ ] update title to match Figma
- [ ] add subtitle
- [X] ~~add footer~~ -> [See this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30106)
- [ ] change heading to "Beneficiary" (to match figma) and "Beneficiary information"

**Comment by michaelclement** [comment]
[All work is done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30109) (please review screenshots attached on Github)
Waiting on
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 this just got approved/merged this morning, should be on staging in an little while. Thanks!

**Comment by marywang2** [comment]
@michaelclement please update title and add subtitle to match figma: 
- title: "File for CHAMPVA Other Health Insurance Certification" 
- subtitle: "CHAMPVA Other Health Insurance Certification (VA Form 10-7959c)"
