### ISSUE TITLE
10-7959c: update copy - Health insurance section (Secondary)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83948]
As a user on VA.gov, I want to fill out the OHI form with the latest information so that I can report any changes to my other health insurance.

Page elements:
- breadcrumb
- header and subhead
- progress indicator
- footer

Pages (following primary insurance questions): 
- secondary health insurance (answer options: yes,no)
- secondary health insurance information (name, start date, termination date - _not required_)
- insurance type (answer options: yes, no)
Prescription coverage screens covered in this [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/83201
- prescription coverage (answer options: yes, no)
- EOB for prescriptions (answer options: yes, no)
  - file upload screen
- insurance plan (6 programs listed)
  - if Medigap selected
  - display secondary Medigap screen (w/options)
- additional comments screen (character limit?)
- file upload screen

Figma link ("Prep for staging review"): https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Y8cWvTGeyw2lKO6X-0

Acceptance criteria:
  - Given the user is on VA.gov and is filling out the OHI form
  - When the user gets to the health insurance information
  - Then the user can include that information as part of the other health insurance certification and it is displayed on the PDF attachment

**Comment by michaelclement** [comment]
Once [this PR is merged](https://github.com/department-of-veterans-affairs/vets-website/pull/30197) this ticket will be good to go.

**Comment by michaelclement** [comment]
@marywang2 This has been merged in and should be review-able on staging shortly. Thanks!

**Comment by marywang2** [comment]
- selecting no on secondary health insurance screen goes to file upload screen (need to confirm w/jamie?)
- update copy for secondary health insurance screen: https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance
- insurance info screen - update header and remove both instances of "For example: January 19 2000": https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance-info
- schedule file upload - add period after 'fax'; can it read 'schedule of benefits document' rather than 'card' in the file dropdown: https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance-sob
- insurance plan - seems like there's a margin on the answer options, add space in "PrescriptionDiscount": https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance-plan
- file upload screen - update header and add copy, also update to 'Upload health insurance card' (above 'upload file' button: https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance-card-upload

**Comment by michaelclement** [comment]
The above changes have been [applied in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30246). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by marywang2** [comment]
- selecting no on secondary health insurance screen goes to signature screen (unless they have any Medicare uploads, then they would go to file upload screen)
- there's no margin on the insurance plan page (answer options) right? https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance-plan
- update header (remove "required" and make it "card" singular: https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/secondary-insurance-card-upload

**Comment by michaelclement** [comment]
@marywang2 
A couple clarifications
- For the first bullet point, that's the behavior I'm seeing. Is that correct, or should it be doing something else?
- Second bullet - the width of list items is capped at 320px (that's just the standard design system style). Do we want to override it to prevent text-wrap?

Thanks!
