### ISSUE TITLE
10-7959c: update copy - File upload section

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#83950]
As a user on VA.gov, I want to provide supporting documentation when filling out the OHI form so that I can report any changes to my other health insurance.

Page elements:
- breadcrumb
- header and subhead
- progress indicator
- footer

Pages (following secondary insurance questions): 
- upload supporting documents (upload medicare card link, upload health insurance card link)
  - if file is uploaded, then show success state 
  - if outstanding documents, then show supporting document summary (supporting document acknowledgement checkbox)

Figma link ("Prep for staging review"): https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Y8cWvTGeyw2lKO6X-0

Acceptance criteria:
  - Given the user is on VA.gov and is filling out the OHI form
  - When the user gets to the file upload section
  - Then the user can include their supporting documents as part of the other health insurance certification submission

**Comment by michaelclement** [comment]
[Work is done here](https://github.com/department-of-veterans-affairs/vets-website/pull/30282) - waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 This is ready for you to take a look at on staging. Thanks!

**Comment by marywang2** [comment]
(Not yet final feedback - need to consolidate still - WIP)
- Can you populate the health insurance's name in the upload links?
- Remove "Primary" and "Secondary" from the heatlh insurance bullets
- Can you increase the margin in between the links and by by 8px?

**Comment by michaelclement** [comment]
@marywang2 These changes have now all been implemented in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30366)

Screenshots attached on GitHub - thanks!

**Comment by michaelclement** [comment]
@marywang2 These changes have now all been implemented in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30366)

Screenshots attached on GitHub - thanks!

**Comment by marywang2** [comment]
@michaelclement I removed the front/back logic comment (forgot I had put it in there). Let's discuss....

**Comment by michaelclement** [comment]
(Plan is to discuss in a parking lot after huddle today 6/17)

**Comment by michaelclement** [comment]
Currently waiting on the final agreement from other designers ( @jamiefiore ), but it seems like requiring the user to upload multiple documents on screens where we want front/back is an acceptable solution.

**Comment by michaelclement** [comment]
@marywang2 Jamie confirmed designers were satisfied with this solution, so you should be able to check this out on staging whenever you have time. Thanks!
