### ISSUE TITLE
Unit Tests for Authorization Chapter

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83970]
## Background
We have created the following pages for the authorization chapter and will need to implement unit tests: 
1. Authorization for Certain Medical Records #83964
2. Authorization for Certain Medical Records - Select #83965
3. Authorization for Address Change #83966
4. Authorization for Access Inside VA Systems #83969
5. Authorization for Access Outside VA Systems #83967
6. Authorization for Access Outside VA Systems - Names #83968

## Tasks
- [ ] Create unit tests for the authorization chapter, with the pages listed above in mind.

## Acceptance Criteria
- [ ] Unit test coverage exists for the authorization chapter experience.

**Comment by cosu419** [comment]
Our unit test coverage has not been negatively impacted by the work we've done so far (which makes use of already-tested components), so I'm moving this to closed.
