### ISSUE TITLE
Update static pages with new disability claim statuses

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#83972]
When the CST releases the updated statuses list for disability claims, we'll need to update static pages to match the new list. The tool is only changing the status list for disability claims, not other claim types. So we'll need to decide how to adjust on pages that aren't specific to disability.

Blocked until we audit pages and decide how to approach.

**Comment by laurwill** [comment]
@saratorres2 we have 2 page updates ready for copyedit and prepub, but hold to publish until SME approves. 
http://preview-prod.vfs.va.gov/preview?nodeId=870
http://preview-prod.vfs.va.gov/preview?nodeId=8548

See [notes in the intake ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82302#issuecomment-2269452039)that may be helpful during copyedit. 

I know you're having Drupal issues, so let's check in tomorrow and see if we need a different plan for these — we'll need to publish them later this week, I think.

**Comment by saratorres2** [comment]
@laurwill These two pages have been copy edited and are ready for publication once you receive SME approval. 
After you file your claim: http://preview-prod.vfs.va.gov/preview?nodeId=870
What your claim status means: http://preview-prod.vfs.va.gov/preview?nodeId=8548

**Comment by laurwill** [comment]
thanks so much Sara! published and closing this out :)
