### ISSUE TITLE
Download Analytics Before GA4 Shut-off

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#83978]
## Issue Description
Download a backup copy of analytics prior to GA4 shut down.

## Tasks
- [ ] Download analytics
- [ ] Place in centralized location on Sharepoint

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Analytics have been captured for March - May: https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?usp=sharing

Build dashboard in GA4 - public view labeled ARM Team Metrics https://analytics.google.com/analytics/web/#/analysis/p419143770

Meeting with analytics team Friday to discuss discrepancies in metrics and how to do previous/next pages, and identify entrance traffic such as Google, Bing, etc.

**Comment by jfinnerty13** [comment]
Have a first draft completed in GA4. Some open topics though:
* @oddball-lindsay what are the status of these tickets? We have limited tracking on the search tool without these being fixed
** https://github.com/department-of-veterans-affairs/va.gov-team/issues/70420#issuecomment-2096289352
** https://github.com/department-of-veterans-affairs/va.gov-team/issues/82489 
* Jamie recommended we reach out to figure out tracking on widget to better track logins which would take tech lift - @oddball-lindsay are you ok owning that or did you want me to?
* Jamie is looking into how to get Average time on page, otherwise we can consider this closed until we hear more.

**Comment by oddball-lindsay** [comment]
@jfinnerty13 those tickets are in our backlog, no immediate priority at the moment -- the idea was to focus on Appoint momentum and pursue GA reporting for what we have for now.  I'll chat with Jen about priority of these open items when she's back tomorrow. 

> Jamie recommended we reach out to figure out tracking on widget
For this, did Jamie mean reach out to Analytics?

**Comment by jfinnerty13** [comment]
1. Just wanted to call out that if these are metrics we wanted to track we can't today until they're fixed and there is no way to get back metrics on these. We can track how many searches are triggered, although the data is messy, but I can demo that later as needed. So if that's enough then all good, if it's not enough then I'd leave it up to you and Jen to evaluate if we should fix this.
2. Jamie didn't specify, just that she had ideas on how to approach getting tracking on the widget which felt important and that I'd circle back up with you if that's something we want to pursue right now. Keeping in mind there is no back tracking, so we can't start tracking metrics around this until we get anything implemented.
Hopefully that helps! @oddball-lindsay

**Comment by oddball-lindsay** [comment]
Got it, I can check in with Jamie to see if Office Hours or a one-off meeting makes sense for discussing what she had in mind for tracking the Widget.  

If there's work for us to do, we could combine that with the updates needed for Find (https://github.com/department-of-veterans-affairs/va.gov-team/issues/82489) and comprehensively address all things pending for Analytics.  

Okay on my end to close this :)
