### ISSUE TITLE
Design Intent - IA Feedback - Transition Experience, tbd, V1 Transition Experience

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#83999]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through collab cycle! 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must: work with CAIA on entry points and user flow** We talked a little bit on our call about creating a conceptual model of All The Things involved with this tool - namely benefits and eligibility criteria. It sounds like something like this is already underway, so that work might be duplicative. However, because the team is hoping to have an entry point from the VA.gov homepage, please work with CAIA Information Architects to ensure proper placement and to optimize the user paths through the product.

- [x] **Must: provide skip option during questionnaire** it should be easy to skip options on the questionnaire so that folks can move through it quickly if they don't have all the answers.

- [x] **Should: add standard search results view components** If y'all stick with the search results design pattern for displaying a list of benefits, these are some of the emerging conventions for search results design on VA.gov:
    - Include a status message above the results ("Showing 9 results, filtered by X, sorted by Y") that changes each time a filter is applied
    - For the filters, include buttons or a single button to apply filters, rather than changing results dynamically based on a dropdown
    - For larger results sets, include [pagination](https://design.va.gov/components/pagination). 
    - Other search interfaces on VA.gov include [Find a location](https://www.va.gov/find-locations/), [GI Bill comparison tool](https://www.va.gov/education/gi-bill-comparison-tool/), [Find a Rep](https://www.va.gov/get-help-from-accredited-representative/find-rep/)
    
    The [Unified appointment experience team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80703) are working on a search/multi-filter feature for appointments search and we've talked with them a lot about their design. Might be worth reaching out to their team!

- [x] **Consider: on questionnaire, start with easier-to-answer questions first** if possible I recommend ordering the questionnaire starting with easy questions (either easier to recall answers, and/or less complicated interaction patterns). The service history pattern, for example, is pretty complex way to start the form. 

- [x] **Consider: reach out to IIR team working on related product** another team working in a similar problem space is the IIR team, working on the [Veteran New Account flow within authenticated experience](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82257). There are some synergies here that could be useful for both teams' products! They just had their Design Intent on May 14.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by erinrwhite** [comment]
Thanks @nkontrabecki this is helpful. Will there be a "don't know" option, or a way to indicate that estimates are okay, on some questions (specifically the dates on the service period screen)? That could functionally do the same thing, or help speed users along, rather than blocking them from completing the flow if they're not sure about something. CAIA IA's will also be able to offer some guidance here if you end up working with them. Thanks for considering!

**Comment by nkontrabecki** [comment]
@erinrwhite Just wanted to clarify that if someone doesn't answer a non-required question, it won't stop the user flow. The user will not be blocked from completing the flow if they are unsure how to answer a question. We just won't be able to use that field to determine if someone is potentially eligible for certain benefits.

As an example — if someone doesn't answer the question "Have you applied for and received a disability rating from VA?", we will still recommend benefits based on the other info provided, but we won't recommend anything that requires a disability rating (like VR&E)

**Comment by erinrwhite** [comment]
@nkontrabecki that's excellent! Thank you for clarifying this and providing the example.

**Comment by erinrwhite** [comment]
This satisfies the "must" feedback about being able to skip questions if possible. Thanks! 👍🏻

**Comment by nkontrabecki** [comment]
Item closes per comments above.
