### ISSUE TITLE
[Design] Combine My VA profile/account links 

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#8400]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost.  Currently there are links to account and profile from my VA.gov, these need to be combined into a single link to profile.

## Additional Information

Epic #8395 
Related to ticket #5522

![Screen Shot 2020-04-24 at 9.12.22 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b9786fc2-89e5-4632-a1e3-18dfc551000c)

## Tasks

- [x] Tressa work with Peggy to update content for combining 'Manage your profile' and 'Manage your account'

## Acceptance criteria
- [ ]  'Manage your profile' has been updated

**Comment by tressaellen** [comment]
@mshea0606

**Comment by mshea0606** [comment]
@tressaellen updated

**Comment by peggygannon** [comment]
@tressaellen can you tell me what on pages does this content above currently appear? I'm trying to  figure out where users will see these links..

**Comment by tressaellen** [comment]
@peggygannon this is on My Va, on the very bottom of the page.

https://staging.va.gov/my-va/

**Comment by peggygannon** [comment]
Hello, @tressaellen @sanlouise Please let me know your thoughts on this content? 

**View your profile**
Go to your profile to view the information you need to manage your VA benefits. You can make updates to your personal, military, and financial information, as well as update your account settings to access more online tools and services.   

{CTA button} Go to your profile

**Comment by sanlouise** [comment]
That content looks great to me! Thanks!

**Comment by tressaellen** [comment]
This looks great to me as well! Thanks so much @peggygannon

**Comment by sanlouise** [comment]
@mshea0606 Could you please validate this ticket? Thank you!

**Comment by peggygannon** [comment]
@tressaellen or @sanlouise Can I see an updated screenshot with the messaging?

**Comment by mshea0606** [comment]
![image](https://user-images.githubusercontent.com/60523453/81105584-29026f80-8ee2-11ea-80af-2b279e80a773.png)

**Comment by peggygannon** [comment]
ok, thank you. @tressaellen @sanlouise @mshea0606 Our style is to use sentence casing for heading and subheadings 

can you update the subhead to **View your profile** (removing the initial caps? )

**Comment by sanlouise** [comment]
Oops, sorry about that! Fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/12508/files.
