### ISSUE TITLE
Sidekiq Admin UI access for Bryan Alexander

### ISSUE THREAD

**Issue by balexandr** [department-of-veterans-affairs/va.gov-team#84014]
### Your Name

Bryan Alexander

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@balexandr

### Your dsvagovcloud AWS user name (if applicable)

Bryan.Alexander

### Team, Role, and Company of the target individual

IVC CHAMPVA, SWE III, Ad Hoc

### COR Name

Eunice Garcia

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [ ] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I need this because I want to create a job that checks `ivc_forms` DB table and generates a report for rows that are missing PEGA (third-party handling forms) status that way we know which forms are stuck.

**Comment by AnthonyWFlowers** [comment]
Greetings @balexandr You've been granted access to dev, staging, and sandbox environments. Please reach out with any additional questions or concerns.
