### ISSUE TITLE
Fix wrapping width of "need help?" component on LP

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#84011]
## Description
The width of the "need help?" component does not match the Figma file. Please update to match. 

### User story

As a Veteran, I want the landing page to have consistent widths, so that on Desktop it seems clean and linear, and is more scannable for me; I can easily find what I am looking for without having to look left-to-right for different distances throughout the page. 

### Notes
- Staging does not match [figma file here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2165-24841&t=XqGOKZJQp4QcvCAc-0) per specifications by @jonathanjnelson 
- See screen shot in comment below
- Define width as 8 columns out of 12 on desktop

Possible tasks:
- [ ] Change grid count width of "need help?" component to match the Figma file

## Acceptance criteria
- [ ] Wrapping point of the "Need help?" component matches the designer specifications
- [ ] Filed ticket with DST to get figma and implementation aligned

**Comment by sterkenburgsara** [comment]
<img width="561" alt="Screenshot 2024-05-28 at 10 59 40 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/394fea57-c1d8-4da2-8a67-af5161c067b8">

**Comment by sterkenburgsara** [comment]
Should look like this per Figma: 

<img width="508" alt="Screenshot 2024-05-28 at 11 08 17 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/2fa120e7-0605-432d-b769-8ea7e912c840">

**Comment by dcloud** [comment]
I changed the suggested col width to 8 cols after looking at the container for the introtext, which has `vads-l-col medium-screen:vads-l-col--8`.

Also in my follow-up PR for the newsletter link, where there is also an implied width: department-of-veterans-affairs/vets-website/pull/30056

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the "Need help?" section has been changed to match the width of the other text on the page

<img width="694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c97fa6c9493425df33322636edfc92dfe00b5f92/Screenshot%202024-06-13%20at%207.14.03%E2%80%AFAM.png" alt="Screenshot 2024-06-13 at 7.14.03 AM.png" />
