### ISSUE TITLE
[RESEARCH]: Editorial experience/workflow  

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8401]
## Problem Statement
How might we collect user feedback on the editorial workflow? 

## Goals
- To continue to improve the editorial experience
- To reduce editorial errors and the creation of technical debt

## Objectives or Key Results this is meant to further
- Improve Veteran search experience
- Improve data quality

## Task
- [ ] Determine process for gathering feedback on editorial experience

**Comment by jilladams** [comment]
Closing as no-op in favor of more specific iteration / feature driven research.
