### ISSUE TITLE
AWS access for Derek Dyer

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#84028]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Derek Dyer

### Your Email

derek.dyer@govcio.com

### Team, Role, and Company of the target individual

Derek Dyer, Backend Engineer, GovCIO

### Product Manager (PM) name and email

Tom Davis, thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### Desired AWS Access

Access to all resources related to vets-api project.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Transmittal Notice proof for Derek Dyer 5 28 24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/bfdaf725-2b4d-4dbb-ba1b-f88aea110fd0)

### Additional Notes

Access should be maintained until Derek is no longer associated with the VFS contract.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Hi there! I'm following AWS instructions on our side and it seems like you are not on `Atlas` or the `Platform Roster` 

> If the user is on a VFS team but not in Atlas, add the NOT YET label and instruct them to start the Platform orientation process [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). 

Is it possible for you to complete this then we can get you added.

**Comment by HeatherRienks** [comment]
@stoiven - I am seeing Derek Dyer (@digitaldrk) in Atlas. Please see attached screenshot and let us know if there is anything else needed. Thanks!
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/8e9bb5a4-f52f-4b79-80d9-148a16e1dddf)

**Comment by stoiven** [comment]
Sorry, I was looking at the wrong Atlas instance.
 I slacked Derek info about AWS

**Comment by stoiven** [comment]
Access granted and tempo creds passed to user
