### ISSUE TITLE
Sidekiq Admin UI access for [individual]

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#84034]
### Your Name

Don Shin

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

cloudmagic80

### Your dsvagovcloud AWS user name (if applicable)

don.shin@dsvagovcloud

### Team, Role, and Company of the target individual

CHAMPVA team

### COR Name

Eunice Garcia

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [x] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

**Comment by AnthonyWFlowers** [comment]
E-QIP in previous [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76757)

**Comment by AnthonyWFlowers** [comment]
@cloudmagic80  You've been granted access to Dev/Staging/Sandbox/Production, with access to Production limited to 6 months, expiring 11/29/2024

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1717009797774259)

**Comment by davidpetras** [comment]
@cloudmagic80  Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by davidpetras** [comment]
@cloudmagic80  since you have not responded we have removed your prod access. You will have to submit a new request if you would like to have access again.
