### ISSUE TITLE
Sidekiq Admin UI access for Derek Dyer

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#84037]
### Your Name

Derek Dyer

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@digitaldrk

### Your dsvagovcloud AWS user name (if applicable)

derek.dyer

### Team, Role, and Company of the target individual

Derek Dyer, BackEnd Engineer, GovCIO

### COR Name

Jennifer O'Day

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [X] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

Access required to complete job functions.
![Transmittal Notice proof for Derek Dyer 5 28 24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/fb4add8e-7978-4e9e-b7fb-61a5ee328779)

**Comment by HeatherRienks** [comment]
FYI @digitaldrk

**Comment by AnthonyWFlowers** [comment]
Greetings @digitaldrk You've been granted access to dev, staging, and sandbox environments.

Access to prod is pending approval by OCTODE, be sure to add as much detail as you can why you need prod access, and we'll update you as soon as it's available.

**Comment by AnthonyWFlowers** [comment]
Greetings @digitaldrk Access to prod does NOT require OCTODE approval so you also have that now as well. Sorry for the mixup. 
Production access is for 6 months, expiring Friday, November 29, 2024. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1717009677722959)

**Comment by davidpetras** [comment]
@digitaldrk  Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bmatos312** [comment]
@digitaldrk Hello Derek, since you have not responded we have removed your prod access. You will have to submit a new request if you would like to have access again.

**Comment by HeatherRienks** [comment]
@bdech- I believe that @digitaldrk does need access. I think this was overlooked.

FYI @Tom-Davis @dhill802
