### ISSUE TITLE
OCTO eng feedback: code cleanup 10-7959c, 10-10d

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#84043]
Ticket for adding PropTypes and delinting for 10-7959c and 10-10d.

**Comment by michaelclement** [comment]
[Work is done here](https://github.com/department-of-veterans-affairs/vets-website/pull/30208)

Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
Non-technical review details:

Linter output before fixes were applied - note the 5 warnings:
<img width="1194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50cf41628acad07f28cd1d63c7abb04a1c451854/Screenshot%202024-06-06%20at%2008.19.13.png" alt="Screenshot 2024-06-06 at 08.19.13.png" />

After addressing those concerns, linter warnings are gone:
<img width="404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8c7046e2a922b0e4030ba30b9453c6b28135ffe/Screenshot%202024-06-06%20at%2014.18.59.png" alt="Screenshot 2024-06-06 at 14.18.59.png" />

**Comment by michaelclement** [comment]
Non-technical review details for Proptypes - review screenshots

Before (note the warning and yellow underline):
<img width="861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5IQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c9c725c64d2728321632badf0cb99bf2c707157/Screenshot%202024-06-06%20at%2014.58.29.png" alt="Screenshot 2024-06-06 at 14.58.29.png" />


After (note absence of warning and yellow underline)
<img width="628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11e77c59998f41a08e5315386e691fd3ff758067/Screenshot%202024-06-06%20at%2014.59.10.png" alt="Screenshot 2024-06-06 at 14.59.10.png" />


This was done across all of IVC forms.

**Comment by michaelclement** [comment]
Blocked until I get platform review

**Comment by michaelclement** [comment]
@marywang2 This has been approved by platform and merged. It's ready for your review whenever - I've attached screenshots above for reviewing. Thanks!
