### ISSUE TITLE
IA Guidance: Title Tags

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#84040]
## IA standards request
Define clear standards and guidance that teams must meet related to Title Tags

Goal:
Document clear guidance and standards for Title Tags that teams need to meet, and identify where we need to edit/add info on the design system.

Existing Documentation:
- In January we worked with content and a11y to suggest updates to title tag guidance (getting confirmation from a11y council for these changes). We created a [DST Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2415) but it hasn't been updated since January. I asked Matt the status and waiting on response

### Acceptance criteria

- [x] Placement within the VA design system is identified
- [x] Standards are approved by OCTO IA lead, OCTO design lead(s)
- [x] Clear standards s are documented and published to VADS
- [ ] New standards are communicated out to teams

**Comment by kristinoletmuskat** [comment]
@mnorthuis and @erinrwhite I believe we reviewed this with Mikki back in January, but if we want to put it through our new process (or maybe if you can publish Erin instead of waiting on Matt), here is the draft: https://docs.google.com/document/d/1EA9iEw1mCE8P7-JxEwX5r7yFnz1xxyG-dCviPoh_oSA/edit

**Comment by mnorthuis** [comment]
Looks like for this one we just need to get the forms and subtasks info added as a second exception.  This info should likely either be repeated or there should be a link to this page from both the [subtask pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task) and the [templates - form page](https://design.va.gov/templates/forms/). 

I did not do a comparison of what's in the title tags section of the c[ontent style guide SEO/title tags](https://design.va.gov/content-style-guide/seo)vs what is in this google doc though...

Also agree that the meta data info may either need to be pulled out of the content style guide, or it may need to be titled as meta data vs writing for SEO.

**Comment by kristinoletmuskat** [comment]
Thanks for taking a look! Yes what I've tried to do is copy/paste sections directly from the design system and style guide, and then show the exact edits and additions we're looking to make. 

So for this first iteration, we're proposing that we create a new section of the style guide called "Title tags", given how frequently our design system users look for it and can't find it under 'writing for SEO'. So what will remain in 'writing for SEO' is 'SEO best practices for writing copy' and 'Meta properties'. And we would link to the new title tag section from the Writing for SEO page. Does this make sense?

![Screenshot 2024-05-29 at 3 59 47 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/fc0d5212-7cfc-4545-a7c3-2bc131ddc950)
![Screenshot 2024-05-29 at 3 59 53 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/5e70a1fc-b64f-4db7-8069-85b8f8d05b07)

**Comment by kristinoletmuskat** [comment]
Matt published our initial guidance from January here: https://design.va.gov/content-style-guide/title-tags

**Comment by erinrwhite** [comment]
@kristinoletmuskat I put in a [pull request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2986) to update the guidance - I spotted a formatting error that was making the examples for the form titles give incorrect guidance.

**Comment by kristinoletmuskat** [comment]
ooo @erinrwhite thank you so much!

**Comment by erinrwhite** [comment]
PR merged, okay to close this one.

**Comment by erinrwhite** [comment]
Sigh...reopening. We need to announce this new and improved [Title tag guidance](https://design.va.gov/content-style-guide/title-tags) to VFS teams! @mnorthuis tossing to you for next steps.

**Comment by mnorthuis** [comment]
communicated out on 9/24
