### ISSUE TITLE
CT-EYB: Group Estimate Your Benefits Section Questions to reduce vertical spacing.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8404]
As a Comparison Tool user, I need the Estimate Your Benefits Questions to be grouped so that the benefits estimator panel stays in sight as I complete the form.

## Assumptions:
1. This work is completed behind a feature flag #7780.
2. The [interactive prototype](https://bahdigital.invisionapp.com/share/J5IADLE7CEF#/screens) is for UI/Layout reference but is overruled by supporting artifact 1.
3. The [OJT interactive prototype](https://bahdigital.invisionapp.com/share/74IADLI2G58#/screens) is for UI/Layout reference but is overruled by supporting artifact 2.
4. The [mobile interactive prototype](https://bahdigital.invisionapp.com/share/3XIADLG2GJD#/screens) is for UI/Layout reference but is overruled by supporting artifact 3.
5. The [OJT mobile interactive prototype](https://bahdigital.invisionapp.com/share/Z9IADLWBV7U#/screens) is for UI/Layout reference but is overruled by supporting artifact 4.
6. Update e2e to test new functionality of calculator on non-vettec profile pages.
7. The mobile expandable panel is not part of this story and is covered in #8003 
8. The question conditionality behavior is not changed by the question grouping.
9. The "Your eligibility" widget is reused on on the landing page and the search results pages; by changing the name to "Your benefits" those locations will also be changed (if it is currently displayed) and that is acceptable.

## Acceptance Criteria:
1. The following text is the first information displayed under the left hand side of the "Estimate Your Benefits" section: "Use the fields below to calculate your benefits". 
2. The "Estimate Your Benefits" section questions are separated into four groups:
    a. Your benefits
    b. About your school
    c. Learning format and schedule
    d. Scholarships and other funding
3. The groupings have the following characteristics:
    a. "Your benefits" section questions are displayed on profile page load.
    b. "About your school", "Learning format and schedule", "Scholarships and other funding" section questions are hidden on profile page load.
    c. When a section questions are displayed all other section questions are hidden.
4. The following questions are displayed within the "Your benefits" grouping in the following order:
    a. What's your military status?
    b. Is your spouse on active duty?
    c. Which GI Bill benefit do you want to use?
    d. Are you eligible for the Post-9/11 GI Bill?
    e. Completed an enlistment of
    f. How many dependents do you have?
    g. Cumulative Post-9/11 active-duty service
    h. Did you use your Post-9/11 GI Bill benefits for tuition, housing, or books for a term that started before January 1, 2018?
5. The following questions are displayed within the "About your school" grouping in the following order:
    a. Are you an in-state student?
    b. In-state tuition and fees per year
    c. Tuition and fees per year
    d. Books and supplies per year
    e. School Calendar
    f. How many terms per year?
    g. How long is each term?
    h. Enrolled
6. The following questions are displayed within the "Learning format and schedule" grouping in the following order:
    a. How do you want to take classes?
    b. Where will you take the majority of your classes?
    c. Choose the location where you’ll take your classes
    d. Please enter the postal code where you'll take your classes
    e. I'll be taking classes outside of the U.S. and U.S. territories
    f. Will be working.
7. The following questions are displayed within the "Scholarships and other funding" grouping in the following order:
    a. Will you be a Yellow Ribbon recipient?
    b. Degree Level
    c. Division or School
    d. Yellow Ribbon amount from school per year
    e. How much are you receiving in military tuition assistance
    f. Eligible for kicker bonus?
    g. How much is your kicker?
    h. Participate in buy-up program?
    i. How much did you pay toward buy-up (up to $600)?
    j. Scholarships (excluding Pell)
8. If a grouping has no questions for a given institution type, that grouping is hidden.
    a. "About your school" section is not displayed for institution type OJT. (Note - There may be other triggers resulting in sections not being displayed; those will need to be added as AC)
9. The layout of the "Estimate Your Benefits" section on mobile matches Supporting Artifact # 3 for non OJT
10. The layout of the "Estimate Your Benefits" section on mobile matches Supporting Artifact # 4 for OJT

## Supporting Artifacts:
1. Institution Design Document: [gibct-eyb-schools-v0.2-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4530778/gibct-eyb-schools-v0.2-20200424.pdf)
2. OJT Design Document: [gibct-eyb-OJT-v0.1-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4530777/gibct-eyb-OJT-v0.1-20200424.pdf)
3. Mobile Institution Design Document: [gibct-eyb-schools-mobile-v0.2-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4531051/gibct-eyb-schools-mobile-v0.2-20200424.pdf)
4. Mobile OJT Design Document: [gibct-eyb-employers-mobile-v0.1-20200424.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4531054/gibct-eyb-employers-mobile-v0.1-20200424.pdf)
5. [Institutions Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-schools-desktop-v02)
6. [OJT Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-employers-desktop-v01)
7. [Mobile Institutions Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-schools-mobile-v02)
8. [Mobile OJT Sketch](https://www.sketch.com/s/Z5Jdx/p/eyb-employers-mobile-v01)
9. [Sample Institutions By Type](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/data/sample_institutions_by_type.md)
10. [Calculator Conditional Question Display](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/components/profile/CalculatorForm.jsx#L120)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12381

**Comment by zurbergram** [comment]
AC 4
https://github.com/department-of-veterans-affairs/vets-website/pull/12411

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12417

**Comment by zurbergram** [comment]
AC 5.D 
  - to get “Books and supplies per year” to display 
    - select chapter 31 i.e. “VR&E” for “Which GI Bill benefit do you want to use?”

AC 7.E 
  - to get "How much are you receiving in military tuition assistance" to display 
    - select chapter 33 for “Which GI Bill benefit do you want to use?” 
    - select "active duty" or "national guard / reserves" for "What's your military status?"

**Comment by zurbergram** [comment]
AC 5-10
https://github.com/department-of-veterans-affairs/vets-website/pull/12419

**Comment by zurbergram** [comment]
AC 6.F
 - to get "Will be working" to display
  - Institution must be OJT

**Comment by delli-gatti-michael** [comment]
Tested by TestRail Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/535

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-04-30 at 4.00.10 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5e69cba1-75e0-48ff-a069-7fa81241323b)

---

![Screen Shot 2020-04-30 at 4.01.09 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2288adc0-1e83-4ad9-8046-79089e40ebea)

---

![Screen Shot 2020-04-30 at 4.01.26 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d94961f2-8094-4c74-815c-98e09c7e8a5b)

---

![Screen Shot 2020-04-30 at 4.02.01 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/27c00660-20f9-4a6b-bac0-8ee1dae5cf67)

---

![Screen Shot 2020-04-30 at 4.03.57 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/abd70915-9e0b-473a-a5f7-10dfe4d32af8)

---

![Screen Shot 2020-04-30 at 4.04.06 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6d29d2c3-6b76-4d63-987c-9a21b290c2a5)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah 
This is live in staging and ready for your review

The test script located [here](https://dsvavsp.testrail.io/index.php?/cases/view/535) uses the following institutions to trigger all possible questions in the Estimate your benefits section:

[UNIVERSITY OF MISSISSIPPI](https://staging.va.gov/gi-bill-comparison-tool/profile/11806124)
[MILTON POLICE DEPARTMENT](https://staging.va.gov/gi-bill-comparison-tool/profile/10484047)

**Comment by amyknox** [comment]
UX reviewed - issues are here: https://airtable.com/tbljP9rzebaeT7S5y/viwEDTmC2v13AeOJ8?blocks=hide

We'll review in detail at 5/6 UXBA Sync.

**Comment by delli-gatti-michael** [comment]
Changes are in staging and all blockers have been resolved. Closing this issue
