### ISSUE TITLE
OCTO eng feedback: Audit of code cleanup 10-7959f-1

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#84045]
Ticket for adding PropTypes and delinting.

**Comment by reiting** [comment]
Put a small PR in with some proptypes updates. 
Before: 
<img width="550" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2c250a851a1953bcb06e24e1353924cbe9cc4fc/Screenshot%202024-06-25%20at%2011.23.54%E2%80%AFAM.png" alt="Screenshot 2024-06-25 at 11.23.54 AM.png" />
<img width="352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1QQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1abf8b23dfbd31c60cc75e425f346a0315bef84b/Screenshot%202024-06-25%20at%2011.24.10%E2%80%AFAM.png" alt="Screenshot 2024-06-25 at 11.24.10 AM.png" />

After:
<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--976198ec1ba0873ef9598d8464aae626c30c3629/Screenshot%202024-06-25%20at%2011.38.44%E2%80%AFAM.png" alt="Screenshot 2024-06-25 at 11.38.44 AM.png" />
<img width="299" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7d94a3e9e32cf8d9d65a0bd89d117f82d6517aa/Screenshot%202024-06-25%20at%2011.38.57%E2%80%AFAM.png" alt="Screenshot 2024-06-25 at 11.38.57 AM.png" />

Linting: 
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba7b677859a3bace5dddaf1e545f52cd5997a3e5/Screenshot%202024-06-25%20at%201.33.18%E2%80%AFPM.png" alt="Screenshot 2024-06-25 at 1.33.18 PM.png" />

**Comment by reiting** [comment]
This is in platform review.

**Comment by reiting** [comment]
@marywang2 this was approved and merged. There's no visible changes, but you can see the results of my proptypes above.
