### ISSUE TITLE
Disable qas-notifications messaging about failing e2e test suites

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84051]
## Issue Description
The #qas-notifications channel has a slack message that notifies the channel whenever an e2e test suite fails. This is a dated notification from when we had an entire team dedicated to QA. This notification is no longer monitored by a team or support or otherwise and should be removed, as there is a redundant notification in the #status-vets-website channel that is monitored by support for this purpose, along with the frontend support dashboard.

---
## Tasks
- [ ] Find source of #qas-notifications Slack notification of failing e2e tests and remove the notice.

## Acceptance Criteria
- [ ] The #qas-notifications channel no longer has regular notices of failing test suites.

**Comment by ericboehs** [comment]
Curt solved this yesterday.
