### ISSUE TITLE
ATLAS Appointment Content Update

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#84058]
## Summary
The word ATLAS should be in all caps when displaying the appointment type in the application 

## Specs
- Device: All devices
- Browser: All browser types

## Steps to Reproduce
**Test User:** patient999@id.me

1. Go to:  https://staging.va.gov/my-health/appointments/0fbc293324755816b690f11eab25c827b5e4fbea375ac06e8e9694205f95590e

<img width="526" alt="Screenshot 2024-05-28 at 5 34 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/37e6dd59-c740-4244-88f7-078bdacb2d02">

### Actual Result
The word ATLAS is not in all caps when displaying in the UI. It is currenly showing "Atlas" 

### Desired Result
It should display "ATLAS" on the appointment details page. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by ldelacosta** [comment]
Validated the work in staging. Kindly take a look and let us know if you find additional issues @Cieramaddox 

<img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a60e1959dc64bf4d1f4d850a4604a27aa0f12c6/Screenshot%202024-05-31%20at%2011.34.12%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 11.34.12 AM.png" />

**Comment by Cieramaddox** [comment]
@ldelacosta This has been validated by UX.

**Comment by ldelacosta** [comment]
No issues to report. Closing the ticket.
