### ISSUE TITLE
[Bug] Cancel request button 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#84063]
## Summary
When the user cancels their request, the CTA button `Yes, cancel request` should be displayed. Currently it displays `Yes, cancel appointment`. 

## Specs
- Device: All device types
- Browser: All browser types

## Steps to Reproduce
**Test User:** patient999@id.me

1. Go to: https://staging.va.gov/my-health/appointments/pending/09d37f650e6f6edeb33c89166880ffb561c633a546d861c3f455a192fcee2281
2. Hit the `Cancel` button

### Actual Result

<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ba3a791dea821561532653135b1d72cea3ee4a2/Screenshot%202024-05-29%20at%203.50.09%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 3.50.09 PM.png" />

<img width="405" alt="Screenshot 2024-05-28 at 5 50 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/63051fb3-35e9-4e2c-8201-e50fd4bc21bb">

### Desired Result
Yes, cancel request CTA button should be displayed 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by vbahinwillit** [comment]
This issue was fixed in PR [30011](https://github.com/department-of-veterans-affairs/vets-website/pull/30011)

**Comment by ldelacosta** [comment]
@vbahinwillit - updated the screenshots. Thanks!

**Comment by ldelacosta** [comment]
The first button 'Cancel request' was updated. 
<img width="724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d361efb21aff08bf3d4e5a8fb82c8294b167eaf/Screenshot%202024-05-31%20at%2011.28.58%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 11.28.58 AM.png" />

The confirmation page to cancel button was not updated: 
<img width="805" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0db208d15ef1a80bab8d292142e02eec73a4ca8e/Screenshot%202024-05-31%20at%2011.29.25%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 11.29.25 AM.png" />

@vbahinwillit - Moving the bug ticket back to In Progress.

**Comment by ldelacosta** [comment]
Validated in staging: 

<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUExQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40905beb90ea1133af8468d879a6c9ddf241d440/Screenshot%202024-06-04%20at%2010.59.57%E2%80%AFAM.png" alt="Screenshot 2024-06-04 at 10.59.57 AM.png" />

UX will do a quick validation to make sure there are no other errors.

**Comment by Cieramaddox** [comment]
There are some quirky things going on with pending appointments:

1. Only some (Community Care) have a cancel button. All pending requests should be able to be canceled.
2. After clicking on "cancel request" and using the browser back button to go back to the list, selecting any other pending request goes directly to the cancelation confirmation page. 


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVkyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43152394009ed2f4a6ed52b2a59bbebb7b4e1576/Screen%20Recording%202024-06-04%20at%209.24.41%E2%80%AFAM.mov)

**Comment by ldelacosta** [comment]
Validated the issue and it is working as expected. @Cieramaddox will open a separate ticket for the back browser issue.
