### ISSUE TITLE
Create PDFs of legacy historic rates pages and redirects from TeamSite pages to PDFs

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8408]
All benefits rates pages on VA.gov must contain 3 years of historic rates for tax reasons. 

Any historic rates tables that haven't been cloned in Drupal, and are still on TeamSite/benefits.va.gov, will be turned into PDFs, which will become the new links for those historic rates. 

Capturing the Tasks to complete this item, per comments below:
- [ ] Upload each of the 8 PDFs below (broken into 4 sections, based on their page) into the media GH folder (note: please check that there are hyphens between each of the words in the URL/PDF titles)
- [ ] Supply the GH media file URLs, so we can link to them from the Drupal page
- [ ] This ticket can be closed out when that is complete

1. For this page: https://www.va.gov/disability/compensation-rates/
[disability-rates-2017]
(https://app.zenhub.com/files/133843125/325aadc3-fb74-4128-a759-de89e2217f81/download)
[disability-rates-2018]
(https://app.zenhub.com/files/133843125/42ded996-9f0c-4866-92a5-5a9c19df3cf2/download)

2. For special monthly compensation page: https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
[disability-rates-special-monthly-compensation-2017]
(https://app.zenhub.com/files/133843125/b53f696a-9524-4a36-b847-25e692afe142/download)
[disability-rates-special-monthly-compensation-2018]
(https://app.zenhub.com/files/133843125/8efe3d3e-b18d-486c-91f2-df7706886ea5/download)

3. For special benefits compensation page: https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
[disability-rates-special-benefits-2017]
(https://app.zenhub.com/files/133843125/3b264ce6-c962-40d7-9f2f-ca03fda4f864/download)
[disability-rates-special-benefits-2018]
(https://app.zenhub.com/files/133843125/c6b0fa1b-885a-4409-882a-e7b36dad9522/download)

4. For birth defects benefits page: https://www.va.gov/disability/compensation-rates/birth-defect-rates/
[disability-benefits-birth-defects-2017]
(https://app.zenhub.com/files/133843125/118459e2-83c4-4407-b641-abb39b8ef680/download)
[disability-rates-birth-defects-2018]
(https://app.zenhub.com/files/133843125/fb9de85d-f33a-4eff-b6bd-d680636f378c/download)
-------

List of benefits rates tables pages that will need to be reviewed, and PDFs created:

Disability:
Main disability rates tables: https://www.va.gov/disability/compensation-rates/veteran-rates/
Special monthly compensation rates: https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
Special benefit allowances: https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
Birth defects compensation rates: https://www.va.gov/disability/compensation-rates/birth-defect-rates/

DIC:
Surviving spouses and children: https://www.va.gov/disability/survivor-dic-rates/
Surviving parents: https://www.va.gov/disability/parent-dic-rates/

**Comment by AnneHurley** [comment]
Related to full list of rates pages compiled by @lunascoop  :https://github.com/department-of-veterans-affairs/va.gov-team/issues/8071

**Comment by AnneHurley** [comment]
@RLHecht  @kelsonic @stephorkandatx @DanielleThierryUSDSVA --**Also mentioned as part of 4disabililty rates redirects** - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7202


@kelsonic Here are the historic disability rates PDFs that need to be uploaded into GH media file:

For this page: https://www.va.gov/disability/compensation-rates/
[disability-rates-2017]
(https://app.zenhub.com/files/133843125/325aadc3-fb74-4128-a759-de89e2217f81/download)
[disability-rates-2018]
(https://app.zenhub.com/files/133843125/42ded996-9f0c-4866-92a5-5a9c19df3cf2/download)

2. For special monthly compensation page: https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
[disability-rates-special-monthly-compensation-2017]
(https://app.zenhub.com/files/133843125/b53f696a-9524-4a36-b847-25e692afe142/download)
[disability-rates-special-monthly-compensation-2018]
(https://app.zenhub.com/files/133843125/8efe3d3e-b18d-486c-91f2-df7706886ea5/download)

3. For special benefits compensation page: https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
[disability-rates-special-benefits-2017]
(https://app.zenhub.com/files/133843125/3b264ce6-c962-40d7-9f2f-ca03fda4f864/download)
[disability-rates-special-benefits-2018]
(https://app.zenhub.com/files/133843125/c6b0fa1b-885a-4409-882a-e7b36dad9522/download)

4. For birth defects benefits page: https://www.va.gov/disability/compensation-rates/birth-defect-rates/
[disability-benefits-birth-defects-2017]
(https://app.zenhub.com/files/133843125/118459e2-83c4-4407-b641-abb39b8ef680/download)
[disability-rates-birth-defects-2018]
(https://app.zenhub.com/files/133843125/fb9de85d-f33a-4eff-b6bd-d680636f378c/download)

Acceptance criteria:

Each of the above 8 pdfs need to be uploaded into the media GH folder, so that we can link to them from the Drupal page @kelsonic - that should be the final piece to redirecting these 4 disability pages.

Kelson - we need hyphens between each of the words in the URL/PDF title and note that there are a couple of them I just noticed missing one hyphen. Can you easily correct that when you upload, or let me know and I can rename on my end, and re-upload. Thanks! Let me know if you have any questions or concerns.

**Comment by kelsonic** [comment]
Connecting to epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/7202

**Comment by stephorkandatx** [comment]
@kelsonic I added you as an assignee. I am going to update the description with Anne's comment regarding which PDFs to upload to GH media file. 

When they have been uploaded to GH media file, I will be able to add those urls to the redirect requests per page & that should conclude the PDF portion of the work.

**Comment by kelsonic** [comment]
@stephorkandatx @AnneHurley should we move this out of sprint + into "Ready"?

**Comment by AnneHurley** [comment]
@kelsonic  - Yes, good idea. Awaiting @DanielleThierryUSDSVA and @jenstrickland to weigh in on next steps to determine whether the PDFs meet accessibility standards.

**Comment by lunascoop** [comment]
@stephorkandatx 
[Veterans Compensation Benefits Rate Tables - Effective 12116.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4576711/Veterans.Compensation.Benefits.Rate.Tables.-.Effective.12116.pdf)
Here's my draft version of the PDF redo:

**Comment by stephorkandatx** [comment]
Thanks @lunascoop I added this to the accessibility request

**Comment by stephorkandatx** [comment]
Blocked pending further accessibility discussion/review. Scheduled for Wednesday 5/6/2020.

**Comment by stephorkandatx** [comment]
Closing this ticket - we are moving away from the PDF strategy
