### ISSUE TITLE
10-7959f-1: update text for additional address lines

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84088]
As a user, I want to be able to add my mailing and home addresses to the foreign medical program registration so that I can be notified of any related program information. 

Add extra lines in the street address (for both mailing and home address) on FMP registration form.

Update copy for street address (and add one more line): 
- Street address line 2 
- Street address line 3

Design library: https://design.va.gov/patterns/ask-users-for/addresses

Figma: https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?node-id=726-21596&t=UpvFvxPD6uLEJk0e-0

url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/introduction

Acceptance criteria:
Given I am a user filling out the FMP registration form
When I go to fill out my street address in the mailing and home address sections
Then I will see 3 lines for the address

**Comment by reiting** [comment]
@marywang2 ha I didn't even consider that! It looks like the default is State/Province/Region and when you choose US it does change to just State. I can change it around if needed, or whatever works best! If this is good, let me know and I'll create the PR, and if not let me know and I'll fix it! :)

**Comment by marywang2** [comment]
@reiting let's use whatever out of the box default is, thanks. Also, I realized the figma doesn't quite match what I stated above (needs to be updated) - but we should match what is in the design system ("Street address line 2", etc).

**Comment by reiting** [comment]
@marywang2 okay I updated the street address lines! Let me know if it's good to go for a PR!
<img width="847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU0wQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9506fdb471879dfd35e61b329856ff836451f849/Screenshot%202024-06-04%20at%209.07.50%E2%80%AFAM.png" alt="Screenshot 2024-06-04 at 9.07.50 AM.png" />
<img width="822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVEwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce212f6658fa67efd799d07b9b055ba82a066b3e/Screenshot%202024-06-04%20at%209.08.08%E2%80%AFAM.png" alt="Screenshot 2024-06-04 at 9.08.08 AM.png" />

**Comment by marywang2** [comment]
Thank you! This looks good @reiting. At some point we would like to go through the design system process and perhaps change the copy to something more exciting but going with the default for now.

**Comment by reiting** [comment]
Waiting on platform review
