### ISSUE TITLE
Set up and meet with Forms Team

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#84095]
Slack channel: #veteran-facing-forms
PM: Tricia Baker
```[tasklist]
### Tasks
```

**Comment by cjterdi** [comment]
Possible questions for the Forms Team:
What are the set of features in your wysiwyg prototype and how did you determine/prioritize those features?
What is the lifecycle of the form development process from the initial request to create/edit a form through publishing?
Any Veteran-facing usability testing/design iteration?
Thoughts on what questions can be standardized? Who, if anyone, would authorize this?

**Comment by Karak888** [comment]
1st intro meeting scheduled for Wednesday 6/12/24 at 12:30 EST.  This is just an initial meet and greet, but I do think it makes sense to keep questions we have for them documented here for the time being!

**Comment by cjterdi** [comment]
Copied questions into list of [consolidated questions ](https://docs.google.com/spreadsheets/d/19iNEGGWyOLxSiZUmfrkovaVp_qiZS-djJ4STFzmq-qM/edit#gid=922303338)on google drive. This ticket is complete
