### ISSUE TITLE
Create, use, and delete an accesibility links document

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#84090]
- [x] Create a testing document with both external and internal links
- [x] Place that document deep within the Platform website IA
- [x] Deploy the document
- [x] Test the links on the document
- [x] If the links all open in the same tab, delete the document
- [x] Deploy a second time after deleting the document

## Acceptance Criteria
- [x] All links in the new document open in the same tab

**Comment by laucon** [comment]
This is done.

**Comment by jknipes** [comment]
work is completed, moving to _Done_
