### ISSUE TITLE
Rotate Prod-sign-in-service-oauth-prod.pem

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#84093]
## Issue Description. 
Prepare Prod-sign-in-service-oauth-prod.pem for rotation within 30 days of expiration.

Rotate cert once proper PoCs are notified

## Acceptance Criteria
- [x] Download new cert(s) from Certsmgr
- [x] Reach out to PoCs for availability
- [x] Relay and coordinate actions with team
- [] Upload new cert to login.gov developer's portal
- [] Rotate cert(s)
- [] Ensure cert viability

**Comment by vidjovanovic** [comment]
In process of requesting Zendesk access so ticket can be made for formal request of cert rotation.

**Comment by parkerbees** [comment]
@vidjovanovic is this still blocked by the Zendesk access request? Thx.
