### ISSUE TITLE
Rotate Prod-sign-in-service-token-signing-prod.pem

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#84109]
## Issue Description. 
Prepare Prod-sign-in-service-token-signing-prod.pem for rotation within 30 days of expiration.

Rotate cert once proper PoCs are notified

## Acceptance Criteria
- [x] Download new cert(s) from Certsmgr
- [x] Reach out to PoCs for availability
- [x] Relay and coordinate actions with team
- [x] Rotate cert(s)
- [x] Ensure cert viability

**Comment by vidjovanovic** [comment]
Have made backup of key as per Trevor's instruction.

**Comment by parkerbees** [comment]
@vidjovanovic Is this still an active work item, or can it be closed? I'm trying to clean up the "current sprint" column. Thanks!
