### ISSUE TITLE
Ensure that schools' website addresses are clickable & open the school's website

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8412]
**Problem to Solve**
In testing the Yellow Ribbon work, we found a scenario where the data for a school's URL may not have https:// or http:// in front of it. The current experience, in this scenario, is that the school's website appends itself to the address for the va.gov page. This is not a valid experience. 

We want to resolve this by ensuring that, regardless of the data, when a school's website URL is clicked it opens the school's website

**Acceptance Criteria**
- [ ] when a user clicks the school's website (ex: www.schoolname.com) the school's website opens

Note: We have 2 ways to solve the website URL issue: 1) we can sanitize the URL and be sure to prefix https:// or 2) we can add target="_blank" to the a tag, which would open the link in a new tab . Need to review before we implement.

**Comment by stephorkandatx** [comment]
@andaleliz Pulling this out of Slack & into GH: We hit a scenario when testing YR and could use some thoughts on which path for resolution. @kelsonic was on the call when we saw the situation and can provide an example if that helps. He has flagged that we should confer with you before implementing a resolution.

For YR, it seems like some schools' data, for their URLs, is set up as www.schoolname.com instead of https://www.schoolname.com . On our new YR experience, this seems to cause an issue where, when you hover over the school URL it shows something like "https://va.gov.....www.schoolname.com" instead of showing the valid url of "https://www.schoolname.com" Hopefully this makes sense - if not I can rewrite to better explain.

**Comment by andaleliz** [comment]
@stephorkandatx and @kelsonic thanks for letting me weigh in on this. I caught up [on the Slack thread ](https://dsva.slack.com/archives/C52CL1PKQ/p1587751626474400?thread_ts=1587749847.472600&cid=C52CL1PKQ)too.  I'm totally on board with the `target="_blank"` solution that Kelson proposed.

**Comment by kelsonic** [comment]
PR is up! 🙂

**Comment by kelsonic** [comment]
@stephorkandatx ticket ready for validation! 🎉 

Navigate to https://staging.va.gov/education/yellow-ribbon-participating-schools/?name=university and click on website URLs, if they open up successfully in a new tab then SUCCESS! 📈

**Comment by stephorkandatx** [comment]
I have spot-checked a couple states & checked the specific university that we originally noticed had the issue (Abilene Christian University). Confirmed that the URL structure is as expected, no issues with any click-throughs. Closing this out.
