### ISSUE TITLE
Toxic Exposure: Create Test Rail Test Plan

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#84127]
## Overview 
Doc on creating a [Test Plan ](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)with example test cases

## Acceptance Criteria
Test Cases created for various TE scenarios, including: 

- [x]  Standard Claim + TE (alll of 15B, 15C, 15D) with various date range scenarios
- [x]  BDD (Benefits Delivery at Discharge) + TE
- [x]  FDC (Fully Developed Claim) + TE
- [x]  Standard Claim + Explicit no TE
- [x]  For each scenario, make sure the claim makes it to VBMS

## Out of scope 
- confirm the PDF is displaying correctly in a follow on
- do we want to go to staging review without being able to test e2e that the PDF displays correctly?

**Edge cases** - create new story
Consider whether to sprinkle these scenarios into the above or make their own test cases
- [x] None of these locations
- [x] I'm not sure if I served in these locations
- [x] I'm not sure of the dates I served in this location
- [x] Empty vs populated 'Other locations' with different values and special characters
- [x] Empty vs populated 'Specify other toxic exposures' with different values and special characters
- Don't forget to include Review and Submit in the Test Cases
- New claim vs IPF?

**Comment by michael-wojcik** [comment]
Completed test case for "None of these locations", and added reusable shared steps in TestRail to be used in the other test cases.

**Comment by michael-wojcik** [comment]
Mark and I have finished compiling the primary and ancillary test cases, which are now ready for review in TestRail

**Comment by christinec-fftc** [comment]
Great progress! I took a quick look and here's some questions/feedback

### Standard Claim + TE (alll of 15B, 15C, 15D) with various date range scenarios
step 18, 21, 24, 27 summary pages - should we add screenshots? there's actually a bunch of logic used to display this content. can we verify the content against what was entered on details pages (e.g. start date, end date, no dates, not sure)
step 22 - rephrase 'input locations manually' to something 'type in locations in the 'Other locations not listed here' field
step 30 - should note what should be listed here (i.e. previously entered conditions or selected rated disabilties)

Since this test case is 'various date range scenarios' should the test be instructing to enter specific dates and verifying each scenario on the summary page? did we cover these cases?
No dates entered
No start date entered
No end date entered

### BDD (Benefits Delivery at Discharge) + TE
this test case looks to be copied from existing. can we remove things that say 'New Functionality'? e.g. step 3. that was for a previous release.

### Standard Claim + Explicit no TE
Step 15 - do we need to add confirmation step that no more TE pages display? or is the existence of step 16 sufficient? At some point we'll also need to verify 15A on the PDF is marked 'NO'

### Edge Cases: "None of these locations"; "I'm not sure if I served in these locations"; "I'm not sure of the dates..."; "Other locations" with different values/special characters; "Specify other toxic exposures" with different values/special characters
Step 22 saying to include special characters and not being specific could cause confusion. Can we be specific about what to enter which would be successful vs cause an expected error message?

**Also in the AC**
> Don't forget to include Review and Submit in the Test Cases

**Comment by michael-wojcik** [comment]
@christinec-fftc AFAIK, we have the Review and Submit stepping the test cases already. Did you notice something that is missing in particular? Could you please clarify what you mean with including Review and Submit? Thanks!

**Comment by christinec-fftc** [comment]
@michael-wojcik  There was logic added for the review and submit page so that it can show different titles based on collapsed or expanded view

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/127446042/90b91948-d42f-4ed1-b3ce-c5f36946f9ac)

**Comment by michael-wojcik** [comment]
@christinec-fftc Thanks for the clarification! I've updated the Edge Cases test case to reflect the review-and-submit differences. I also added information to clarify the special character errors, in response to your other previous review comment about Step 22. Thanks again!

**Comment by michael-wojcik** [comment]
@christinec-fftc Also, the test case for VBMS Verification has also been updated for review: https://dsvavsp.testrail.io/index.php?/cases/view/79934

**Comment by michael-wojcik** [comment]
Closed this issue after review and feedback integration
