### ISSUE TITLE
[CST] [PROD] [ENG] Show new claim phase work only for disability compensation claims

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#84133]
## Value Statement
**_As a_** veteran who has filed a non-disability claim 
**_I want to_** see accurate descriptions of my claim process and not see information specific to the disability compensation claim process
**_So that_** my expectations about the process are managed.

---
## Background Context

As part of our claim phase expansion, we need to limit the feature to be only for disability compensation claims. It is important to note that this work is blocked by two factors: 

1. There is no attribute that allows us to use the 8 step paradigm on the listing page claim cards.
2. We need a validated list of EP codes and claim labels to ensure we're showing the experience for the right claim.

Here's a screenshot of the new overview experience we ONLY want to show for disability compensation claims: 

![Screenshot 2024-05-29 131912](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838260/e4a89f32-63a3-4e86-aaed-1fe04c688aa3)

And here are two screenshots of the other two areas mentioned in the AC for which we'll want to make sure only get changed for disability compensation claims: 

![Screenshot 2024-05-29 131747](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838260/0b09055e-d088-48a4-a947-ec659797b9eb)
![Screenshot 2024-05-29 131712](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838260/ceabf8f4-67eb-43fb-a151-a37aa79d6a6d)

## Engineering 
- EP Code is the `claim.attributes.claimTypeCode` , example: `110LCMP7IDES`

## Product Tasks
- [x] Jacob to track down EPs and claim labels for "disability compensation claims"
- [ ] Jacob to make request of LH to add needed phase attributes to the initial CST claim call.

## Engineering Tasks
- [x] Create helper function `isDisabilityCompensationClaim` which will return true or false and accept a claim type code as a parameter
- [x] What We're Doing section on the Status tab uses `isDisabilityCompensationClaim` helper function to determine which version of the UI to show
- [ ] ClaimOverviewHeader uses `isDisabilityCompensationClaim` helper function to determine which version of the UI to show
- [x] Overview tab uses `isDisabilityCompensationClaim` helper function to determine which version of the UI (which version of Claim Phase UI) to show

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _Behind claim phase feature flag (this is already the case)_
- [ ] _The new overview stepper associated with the Claim Phase release is only show for disability compensation claims and no other claim type_
- [ ] _The new  claim phase previews in the What We're Doing section associated with the Claim Phase release are only shown for disability claims and no other claim types_
- [ ] _The claim overview header only shows the 8 steps language when claim is a disability claim and no other claim types_

**Comment by pmclaren19** [comment]
@jacobworrell messaged Andrew about this and he is putting together a list for us. This ticket is blocked until we get those codes. https://dsva.slack.com/archives/C04KHCT3ZMY/p1717511668158509

**Comment by jacobworrell** [comment]
@pmclaren19 this is the official list of EP codes we're using. @jerekshoe mentioned us probably just being able to use the more generic codes (column A), but the more specific ones are also included in each row. 
[Rating EPs and Claim Labels For Claim Expansion Release.xlsx](https://github.com/user-attachments/files/15685342/Rating.EPs.and.Claim.Labels.For.Claim.Expansion.Release.xlsx)

**Comment by pmclaren19** [comment]
@jacobworrell updating the AC here to no longer include the claim card since this work is currently blocked and being handeled by https://github.com/department-of-veterans-affairs/va.gov-team/issues/82376 . Will updated the ac of this ticket to include calling our new helper function. 

Also updating the AC here to include the ClaimOverviewHeader.

**Comment by pmclaren19** [comment]
Validated that this is working correctly in Staging. When the feature flag is enabled and a given claim has a claim type code that matches the ones from our list the 8 phases are displayed and we show the new claim phase stepper, otherwise we show the 5 phases and the old timeline.
