### ISSUE TITLE
AWS access for Ryan Johnson

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#84135]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ryan johnson

### Your Email

ryan.johnson@oddball.io

### Team, Role, and Company of the target individual

Sr Software Engineer - Platform Product - Oddball

### Product Manager (PM) name and email

Jennifer Brown jennifer.brown@adhocteam.us

### Product Owner (PO) name and email

Andrea Hewitt andrea.hewitt@oddball.io

### Desired AWS Access

Require access to AWS Management Console, CloudWatch service, and plugins page to use PagerDuty API to complete this ticket -> https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77698

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![982B7E1A-508B-45C9-B5D3-9151F71D2043_1_105_c](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72466113/896470d9-d468-434d-be1e-4188c249eb64)

### Additional Notes

COR is Ray Wang
I have had AWS access in past with IAM name Ryan.Johnson - last logged in a few months ago and upon trying to login was receiving an error and DevOps support could not find my account.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
@rjohnson2011 access granted
