### ISSUE TITLE
CF: Production duplicates of caution flag

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#8413]
Navigate to https://www.va.gov/gi-bill-comparison-tool/profile/21007303 and https://www.va.gov/gi-bill-comparison-tool/profile/21823010 there are duplicates of the same caution flags for "School engaged in misleading, deceptive, or erroneous practices"

![Screen Shot 2020-04-24 at 3.20.14 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/08a359b2-a51d-4b1c-bf88-52ccd6532da6)
##
![Screen Shot 2020-04-24 at 3.20.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7442fa35-c9cd-48f5-893a-9e80c50e2285)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/649

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12369

**Comment by delli-gatti-michael** [comment]
Fix is in production closing this issue
