### ISSUE TITLE
Expose transform-and-submit endpoint to FE "Transform Logic points to Backend"

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#84132]
We have a service to preform the full transform on the backend. 
Now we need to expose an endpoint on the FSR controller which: 
- takes a form as params, 
- transforms said form via our service, 
- handles any errors that could arise
- submits the transformed form via the FSR service.

### Acceptance Criteria
- Add a controller endpoint to `DebtsApi::V0::FinancialStatusReportsController`
- Add a corresponding route
- your new endpoint should:
  1.  Hit the `FullTransformService`
  2. Handle any errors that could arise from the above call
  3. Take the result and use it to call `submit_financial_status_report` on a `FinancialStatusReportService` inst.

**Comment by digitaldrk** [comment]
I am having to adjust some of the services that this code is calling so the scope of this task has increased.

The team informed me that they have added some code so I might get through this soon but it's tough to tell what's ahead work-wise.

**Comment by digitaldrk** [comment]
Spoke with Max and Kevin about what I've had to change to get my code working.

Kevin advised I mark this blocked until he gets at least one, maybe 2 PR's merged. Mine should be good to go after that.
