### ISSUE TITLE
Bug: Error should prevent user from forgetting to select an option from the list of housing risks

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#84147]
### Description:
In the priority processing subtask of VA Form 21-4138, users have the option to select "none of these situations apply to me" when presented with qualifying priority processing circumstances. 

There are two errors that we should present to users to support their task of finding out whether they should complete the 21-4138, or transition to the other online service to request priority processing: 

1. **Missing selection error: If a user does not select an option from a list of qualifying circumstances, on `Continue` we should present an error with instructions to select something from the list. Selecting anything from the list will resolve the error.**
2. Conflicting statement error:  If a user selects a qualifying circumstance AND selects `None of these situations apply to me`, we should show them an error (captured in #[84151](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/84151))

### Steps to Reproduce:
| Step | Screenshot |
| :--- | :---: | 
| 1. Select  `I want to request that VA process my claim faster due to certain qualifying` from the first subtask page | <img width="538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e15cc10544042e97e45a9af755f397cff4cabb08/Screenshot%202024-05-29%20at%2012.53.59%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.53.59 PM.png" />|
| 2. `Continue` past brief PP introduction | <img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52b38416b2859badba1cb7ec44d25871a080c3d6/Screenshot%202024-05-29%20at%2012.52.53%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.52.53 PM.png" />| 
|  3. do not select anything and select `Continue`  | <img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUllQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29ab05fd74c5ebee14215c17227459b8de449183/Screenshot%202024-05-29%20at%2012.54.23%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.54.23 PM.png" />|

### Expected Result:
I should not bypass the list of housing risks

### Actual Result:
I'm able to skip the first list of qualifying circumstances

### Environment:
Staging: Accessed on Wed, May 29
Browser: Chrome
Device: Desktop

**Comment by pennja** [comment]
Hey @rachelshearerux , unfortunately I'm still unable to reproduce this issue. Could you walk me through exactly what you're doing in order to make this happen? Are you possibly making selections and then hitting the back button several times or perhaps loading an existing application from a spot further in the form? I'm attaching a video recording of my attempt in Staging.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1qQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb2839b345879378a5966ad450a0e345eb18725e/Screen%20Recording%202024-05-30%20at%208.37.22%20AM.mov)

**Comment by megansiddle** [comment]
Recheck after clearing cache.@rachelshearerux

**Comment by rachelshearerux** [comment]
Closing this bug ticket, I'm seeing expected behavior across browsers, including chrome where I first documented it:
<img width="455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05fe463164fd70617a5035c1c9a44cda267e104e/Screenshot%202024-05-31%20at%201.16.52%E2%80%AFPM.png" alt="Screenshot 2024-05-31 at 1.16.52 PM.png" />
