### ISSUE TITLE
Bug: Errors when users change their housing risk selection

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#84151]
### Description:
In the priority processing subtask of VA Form 21-4138, users have the option to select "none of these situations apply to me" when presented with qualifying priority processing circumstances. 

There are two errors that we should present to users to support their task of finding out whether they should complete the 21-4138, or transition to the other online service to request priority processing. 

1. **Missing selection error:** If a user does not select an option from a list of qualifying circumstances, on `Continue` we should present an error with instructions to select something from the list. Selecting anything from the list will resolve the error.
2. **Conflicting statement error:**  If a user selects a qualifying circumstance AND selects `None of these situations apply to me`, we should show them an error explaining that they 

### Steps to Reproduce:
| Step | Screenshot |
| :--- | :---: | 
| 1. Select  `I want to request that VA process my claim faster due to certain qualifying` from the first subtask page | <img width="538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e15cc10544042e97e45a9af755f397cff4cabb08/Screenshot%202024-05-29%20at%2012.53.59%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.53.59 PM.png" />|
| 2. `Continue` past brief PP introduction | <img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52b38416b2859badba1cb7ec44d25871a080c3d6/Screenshot%202024-05-29%20at%2012.52.53%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.52.53 PM.png" />| 
|  3. Select any housing risk option from the first list of housing circumstances and continue  | <img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUllQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29ab05fd74c5ebee14215c17227459b8de449183/Screenshot%202024-05-29%20at%2012.54.23%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.54.23 PM.png" />|
| 4. `Continue` to the next page, then go `Back` and unselect the statement |<img width="490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1441b38fc38cec8089f66bb9bdaf908d01d2bf0/Screenshot%202024-05-29%20at%2012.58.35%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.58.35 PM.png" />
 |
| 5. `Continue` to trigger the error | <img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50564b3f1313ae5d87b3906a6a1f990153cebff5/Screenshot%202024-05-29%20at%2012.52.37%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 12.52.37 PM.png" /> | 

### Expected Result:
1. I should be able to return to the list of housing risks and select "none of these situations apply to me" without triggering an error. 
2. I should be able to return to the list of housing risks and change my selection.
3. I should see an error if I attempt to select "none of these situations apply to me" AND a qualifying housing risk option. 

### Actual Result:
After answering the priority processing questions, when you navigate `back` and return to the list of housing or other qualifying hardships, you cannot select "none of these situations apply to me" without triggering an error. 

### Environment:
Staging: Accessed on Wed, May 29
Browser: Chrome
Device: Desktop

**Comment by pennja** [comment]
Hey @rachelshearerux , much like the other similar PP related issue, I'm unable to reproduce this on my end. If you could provide any further details to help me track this down, I'd appreciate it. Thank you!

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccd35e53eb4111c9ce641ca66a25685f8fff9889/Screen%20Recording%202024-05-30%20at%209.19.18%20AM.mov)
