### ISSUE TITLE
Correct file number values of untouched submission CSV

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#84153]
Emily reported on 5/28 that all the leading 0s were dropped from the File number/SSNs in the provided signed link CSV of untouched submission work. The column needs to be reformatted to include any leading 0s and resent to Emily.

**Comment by freeheeling** [comment]
Emily reported on 5/28 that all the leading 0s were dropped from the File number/SSNs in the provided signed link CSV of untouched submission work. The column needs to be reformatted to include any leading 0s and resent to Emily.

**Comment by freeheeling** [comment]
Created a formula to prepend the appropriate number of 0s for any file_number field to ultimately contain exactly 9 digits, replacing the initial values with the result of the executed formula.

Sent modified Excel sheet to Emily.

**Comment by lisacapaccioli** [comment]
@freeheeling Is this still in progress or should it be considered completed since you sent the Excel per the description?

**Comment by freeheeling** [comment]
@lisacapaccioli This appears in the `Done in sprint :)` pipeline on my board. Work is complete.
