### ISSUE TITLE
UX: Analyze Medallia user feedback daily – Sprint 34

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#84167]
### User story

As a Cartography team member, I want to create a scalable process for analyzing user feedback (Medallia) and tracking trends over time, so that we and stakeholders can understand how Veterans are responding to the portal and identify areas that are successful or need improvement.

As a Veteran, I want my feedback to be used to iterate and improve the experience on MHV, so that I trust that the VA takes Veterans like me seriously.

### Notes
- Kat has submitted ticket for daily Medallia pulls post launch
- Wes, Kaitlin, Jenny & Robyn have shared understanding of integration launch KPIs to track in [this doc + Mural](https://docs.google.com/document/d/1Qah8gSA6JCqEILg4hC1LTlmNSH9sRYRiWai3iprWgUg/edit#heading=h.4ku8bv7bajcw)
- ~Kat will meet with MHV team member this week to implement Datadog dashboard~
- post-launch [UX KPIs mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716414036737/5aa77bac68425356bf314724636ed828f6bb5743?wid=0-1716421371873) for reference

Possible tasks:

- [x] - Go through Anne CK's documentation processes that she gave as templates + adapt to our team's needs
- [x] - Create data management reference (living) doc outlining which data we're collecting, where, & how that Kat will manage going forward (integration versus ongoing collection)
- [x] - Ask AnneCK for any insights in tool-specific feedback that applies to MHV Home, secondary nav, or the portal more broadly

## Acceptance criteria
- Analyzed survey responses daily 
- Grouped responses that are actionable regarding the UX (pain/joy points) for solution exploration
- (If needed:) Created tickets for any solutioning required based on feedback
- Ticketed next sprint's user feedback analysis work

**Comment by wesrowe** [comment]
@katbrinkley, thanks for drafting this ticket! I want to give you feedback so you'll know why I changed what I did from your draft.
- I cut the scope down to just Medallia
- I changed the ACs from "document a proposed process" to "do the process on X weeks of data." This is a classic Agile thing, you know you won't think of everything ahead of time so just do the thing and adapt/rework on the fly. 

For reference, these are the ACs you drafted:

-     Create new process docs for qual & quant data tracking
-     Create data management reference doc
-     Team review

I really appreciate your willingness to jump in. :)

**Comment by wesrowe** [comment]
@katbrinkley @fmccaf1 @jonathanjnelson @sterkenburgsara – reflecting on the discussion in planning, I tweaked this ticket to simply review/analyze Medallia responses daily for the whole sprint. I'm guessing that the objective of a scalable approach might emerge from this as we do the work.
I also added a suggested task: Ask AnneCK for insights.

Please have a read through to see if we're on the same page.

**Comment by katbrinkley** [comment]
Updates:
- Jonathan took this over for the majority of the sprint and we touched base on Thursday. We looked at integration related feedback and now maybe can determine with the UX team if anything needs to be ticketed

**Comment by jonathanjnelson** [comment]
Link to [Excel file ](https://dvagov.sharepoint.com/:x:/s/HealthApartment/EckaFoxCux1Am12ROUHx7KkB6k6VjfpenzSiH7vO4KktBg?e=yZ0Odx) and [documentation here  ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/Medallia-post-launch-feedback-analysis.md)

**Comment by LynneJohnson224** [comment]
@jonathanjnelson just an FYI that excel link takes you to the team's capacity planning spreadsheet. Is it supposed to link to something else?
