### ISSUE TITLE
10-7959f-1: research readout to stakeholders

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84160]
Research readout to stakeholders for FMP registration findings.
- Prepare slide deck for Premal/Lois approval
- Tentative date: sometime in sprint 21 (July 3? TBD)

This ticket and the [presentation in the design CoP](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/84161) are timeboxed: 8 hours for first draft, 2 hours to incorporate edits from Lois and Premal.

**Comment by rachaelpenfil** [comment]
[FMP UXR stakeholder readout](https://docs.google.com/presentation/d/1X-Ol-w6TAz1O6WaOu7Exx4rGurGOMC0iAGJG1jp9eIA/edit#slide=id.g892adcb623_0_141) (WIP as of 6/14)

**Comment by rachaelpenfil** [comment]
Handed off draft to Lois and Premal as ppt on 6/18. Waiting for their comments.
