### ISSUE TITLE
Add case ID to db record and callback payload

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#84169]
As an IVC ops user, I need a PEGA case ID returned after application submit so that I can track submitted documents to statuses reported back from PEGA.

### Acceptance criteria

Given an application submitted on VA.gov
When a callback backload is sent from PEGA
Then the database can accept a case_id value
and the endpoint can process a case_id value

Cindy will send as case_id

Statuses
- Open
- Complete (IVC user has taken data from PEGA and entered in VISTA, no longer needs PEGA data)
- Rescan
- Resolved (resolved as duplicate)

**Comment by balexandr** [comment]
This will consist of two PRs
1. The migration adding a new `pega_case_id` column on the `ivc_champva_form` table
2. The logic in the controller to update the database as well as its tests

Awaiting platform review for the first one https://github.com/department-of-veterans-affairs/vets-api/pull/17017

**Comment by balexandr** [comment]
Both PRs have been merged into `master`
