### ISSUE TITLE
Create an Architecture Diagram for YR

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8417]
Dev task to create an architecture diagram for Yellow Ribbon (MVP)

So that we have a document of changes and we can review with VSP for security + privacy

**Task**
Generate an architecture diagram, similar to what Nick created for Find VA Form Search MVP

**Comment by kelsonic** [comment]
[Yellow Ribbon data flow.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4547130/Yellow.Ribbon.data.flow.pdf)

First draft of the Yellow Ribbon data flow diagram. Let me know if anything is unclear and I'm happy to modify it! 🙂
