### ISSUE TITLE
File experimental design ticket for MHV secondary nav

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#84174]
## Description
The secondary navigation component that was designed for My HealtheVet is not derived from any existing components in the VA design system, and needs to be submitted as an experimental design component so that it can be tracked over time. 

### User story

As a Cartography team member, I want to file a design system experimental design request ticket for the secondary navigation component, and present it to the Design System Council per VADS requirements. 

### Notes
This should not be a launch-blocker, but does need to happen per VADS requirements.

Possible tasks:
- [x] fill out [experimental design ticket here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=caw310&labels=platform-design-system-team%2C+experimental_design&projects=&template=3_experimental_design_request.md&title=Experimental+Design+%5Bcomponent+or+pattern+name%5D)
- [ ] cc relevant team members who may need to answer questions about the component
- [ ] present secondary nav to design system council

## Acceptance criteria
- [ ] secondary navigation is filed as an experimental design component with the design system team and has been presented to the council

**Comment by fmccaf1** [comment]
[Experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2889)
