### ISSUE TITLE
[DESIGN] Change style of schema array card cancel & remove buttons

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#8418]
## Description

The cards that currently appear in the 526 forms for users adding disabilities are not inline with latest card guidelines outlined by Ryan, which means they will be out of sync with newer card designs.  

We recommend tweaks to this tool so the card designs are more inline with latest standards.

<details><summary>Editable cards</summary>

![Screen Shot 2020-04-24 at 4 14 11 PM](https://user-images.githubusercontent.com/136959/80257508-b2928180-8646-11ea-9480-e61127215057.png)
</details>

In edit mode, a "Save", "Update", "Cancel" and "Remove" button may be seen

<details>
<summary>Cards in edit mode</summary>

![Screen Shot 2020-04-24 at 2 51 27 PM](https://user-images.githubusercontent.com/136959/80252823-b2da4f00-863d-11ea-9a0a-ca68326ea82c.png)
</details>

<details><summary>Review & submit page (review mode)</summary>

![Screen Shot 2020-04-24 at 4 15 45 PM](https://user-images.githubusercontent.com/136959/80257616-f5545980-8646-11ea-85f3-2046a0ce8955.png)
</details>

<details><summary>Review & submit page (edit mode)</summary>

![Screen Shot 2020-04-24 at 4 16 05 PM](https://user-images.githubusercontent.com/136959/80257655-056c3900-8647-11ea-82ef-dce5d13180ca.png)
</details>

In a related [Slack discussion](https://dsva.slack.com/archives/C0NGDDXME/p1587757297214100), it was determined that the following changes were needed:

- Change the "Cancel" button style to appear as a link - see related review card issue (https://github.com/department-of-veterans-affairs/va.gov-team/issues/8096) & PR (https://github.com/department-of-veterans-affairs/vets-website/pull/12363)
- Make the "Remove" button visible along with the "Edit" button instead of only visible in edit mode.
- Change "Update" text to "Save" to be consistent

Updated design: (To be added)

## Acceptance Criteria

- Make "Remove" button visible in review mode (non-edit mode)
- Change "Cancel" button appearance; make it similar to a link 
 
## Steps to Recreate

1. Go to https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
1. Log in as user 228
1. Within step 1
    - Add "A new condition"
    - Choose "Yes" when asked if you want to add a new condition
1. You should end up on this page: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/add
1. Add MORE than one new condition (see screenshot)
1. Click "Edit" on any of the cards and you'll see at least two of the following buttons: "Save", "Update", "Cancel" and "Remove"

## Definition of Done

- [ ] Item card, in review mode (non-edit mode) displays an "Edit" and "Remove" button
- [ ] Item card, in edit mode, displays a "Save" button and "Cancel" link.

**Comment by sshein** [comment]
@jonathanjnelson maybe you can take on this little ticket since you have a little bandwidth right now... we can chat about it at our 1:1

**Comment by Mottie** [comment]
Related: BDD design feedback asked about moving the card edit button below the empty header

- Design feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12678 (second bullet point under "should")
- Code changes: https://github.com/department-of-veterans-affairs/vets-website/pull/14091 (see screenshots)

**Comment by sshein** [comment]
@jonathanjnelson can you attach your latest thinking to this ticket and update with your intention to show it at a Monday design meeting?

**Comment by jonathanjnelson** [comment]
@sshein Yes, I will update first thing in the morning.

**Comment by jonathanjnelson** [comment]
These are some of my thoughts on the 526. I will attempt to get on the agenda and present at design meeting scheduled for September 17th. Here are the [mockups](https://vsateams.invisionapp.com/share/Y7X3DATRHTU#/421087183_Icon-Link-Closed_State) if you want to click around. 

**Make remove/delete button visible in review mode**
- Eliminate barriers
- Accessibility 
- Allow users to complete task

**"Cancel" styled as a link**
- Consistency across VA.gov
- Eliminate CTA overload 

**"Ghost button/white background**
- Consistency across VA.gov
- Accessibility

 **"Add another disability" styled as a link**
- Elimination of button overload 

 **Undo link** 
- Is it best to have have a confirmation modal or let the user reverse action with "undo" button

![Cards](https://user-images.githubusercontent.com/58444931/93539056-4d9d3800-f915-11ea-9953-965b598f074f.png)

**Comment by sshein** [comment]
this is great. Thanks @jonathanjnelson! I assume you mean September 21st instead of 17th :) @kristenmcconnell just reminded me that currently the "add another disability" is the list loop pattern so I'm wondering if it's technically feasible to change the styling to an icon + link for that. But I definitely agree when it was a button there were just too many buttons right next to each other in this view.

**Comment by Mottie** [comment]
Do we still want the edit button and delete link to have that same styling on the review & submit page?

**Comment by jonathanjnelson** [comment]
@sshein Yes, September 21st! 

@Mottie I think we do want the same styling on the review & submit page. Is that a possibility? What do you think @sshein?

**Comment by Mottie** [comment]
Yes, we can keep the same styling. I just wasn't sure if the positioning of the buttons & links would be the same on the review & submit page.

**Comment by jonathanjnelson** [comment]
@Mottie Good point. Let me take a look quick!

**Comment by jenstrickland** [comment]
Piping in with my 2¢ regarding two items:

1. Am I understanding correctly that the recommendation here is to style the Cancel link as a secondary button? If that is the recommendation, consider using styling consistent with the Delete/Remove option. This makes the call-to-action hierarchy clear, particularly for people with low-vision and cognitive considerations. Two secondary buttons side-by-side are likely to be confusing. Perhaps I misunderstood the annotation, though.
1. Regarding the suggestion of using undo/modal — I love the thinking here, and wonder if we could try some research to validate. Even if it is quick hallway tests with a range of our colleagues, I believe it is worth it. Modals can be challenging for a range of scenarios, so we try to minimize the use. I only worry that the styling here is so light touch that it may not be clear. Perhaps an icon could reinforce the signal?

**Comment by sshein** [comment]
Agree about the undo option - I think we'd definitely test and maybe make it more visible first before implementing

**Comment by jonathanjnelson** [comment]
@jenstrickland Yes, good points all around. 

@Mottie Let me think about this a bit more. I am thinking it would make sense to stay consistent with the "review and submit page"

**Comment by jonathanjnelson** [comment]
This is currently on pause because 526 falls under the B&M1 team. Kevin Stachura is interested in looking at 526 as a whole and making improvements all at once.

**Comment by Mottie** [comment]
@caw310 I think we can close this? I don't think we're keeping these older array page designs
