### ISSUE TITLE
10-7959c: update copy - Confirmation page (WIP)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84192]
As a user on VA.gov, I want to be able to see the confirmation message after filling out the OHI form so that I know if my other health insurance form was filed successfully.

Page elements:
- breadcrumb
- header and subhead
- progress indicator
- footer

Pages (following file upload screen): 
- Confirmation page 
     - confirmation message
     - blue submission information
     - next steps
     - home link
 - if files remain
     - message with instructions
     - blue submission information
     - next steps
     - home link
- need submission error states (once designs are final)
 
Figma link ("Prep for staging review"): https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Y8cWvTGeyw2lKO6X-0

Acceptance criteria:
  - Given the user is on VA.gov and is filling out the OHI form
  - When the user submits their form
  - Then the user sees the confirmation screen with message

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31394). Waiting on:

- [ ] Team approval
- [ ] platform approval

**Comment by michaelclement** [comment]
| |Before|After|
|-|-|-|
|All attachments|<img width="621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eda3d28181e8dbfaa3016efbdbe040d1dbfcfc0f/before_complete.png" alt="before_complete.png" />|<img width="558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUJhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f24a67c9a246c59b2e05feb4c9b0bdcbc51ff5e6/after_complete.png" alt="after_complete.png" />|
|Missing attachments|<img width="481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7278e6decf87f93d99a8fb4295247965c3ee51a3/before_missing.png" alt="before_missing.png" />|<img width="403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUphQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97acc05153e0cad6d9fc063fe9369ec5d699af22/after_missing.png" alt="after_missing.png" />|

**Comment by michaelclement** [comment]
@baltes @jamiefiore This has been merged and should be visible on staging shortly. Thanks!

**Comment by michaelclement** [comment]
[Link to form on staging](https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c)
