### ISSUE TITLE
Qualitative Data Request - MyVA411 - Representative Status Widget (1 week post-launch)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84202]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

05-20-2024

### Date Range End

05-27-2024

### Product Name(s)

Representative Status Widget

### Product Description

The Representative Status Widget is designed to reflect a user's current accredited representative status which could be: no accredited representative, an accredited Veteran Service Organization, an accredited attorney or claims agent, an error message.

### Survey URL(s), key term(s), case category or type

**Key terms**: accredited, representative, representation, power of attorney, poa, attorney, claims agent, vso, veteran service organization, vso representative, vso rep, veterans service officer, service organization representative, 21-22, 2122, 21-22a, 2122a, claims support

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

lindsay.li-smith@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello. There is not any case type or Case category for the requested data in MYVA411. Let me know if you have any questions.
