### ISSUE TITLE
Qualitative Data Request - Medallia - Representative Status Widget (1 week post-launch)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84203]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

05-20-2024

### Date Range End

05-27-2024

### Product Name(s)

Representative Status Widget

### Product Description

The Representative Status Widget is designed to reflect a user's current accredited representative status which could be: no accredited representative, an accredited Veteran Service Organization, an accredited attorney or claims agent, an error message.

### Survey URL(s), key term(s), case category or type

Find a VA accredited representative or VSO product page: https://www.va.gov/get-help-from-accredited-representative/find-rep/

Get help from a VA accredited representative or VSO landing page: https://www.va.gov/get-help-from-accredited-representative/

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

lindsay.li-smith@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Let me know if you have any questions. Thank you.
