### ISSUE TITLE
SOCKS access for Roberto Rodriguez

### ISSUE THREAD

**Issue by robertbylight** [department-of-veterans-affairs/va.gov-team#84200]
### Your Name

Roberto Rodriguez

### Your Email

roberto.rodriguez@bylight.com

### Your GitHub Handle

robertbylight

### Your Role and Team

Software Engineer on MHV medications

### Product Manager (PM) name and email

Raquel Robertson, raquel.robertson@va.gov

### Product Owner (PO) name and email

Patricia Henry, patricia.henry@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILHFzoUmOZQkQ+lWsvC3CvkjOojAy9PSoIXm1Jq7axJC robertorodriguez@N0VHRV6GW0

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/107279507/94cecc94-013c-4bb7-bcf9-09c2f9aa39ca)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
@robertbylight I'm assuming your SOCKS access is good now? I'll close the ticket, but please let me know if you have issues.
