### ISSUE TITLE
Staging Review finding: "Learn how to renew prescriptions" uses a new URL for an existing page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84215]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** MHV-Medications
**Product:** MHV Medications
**Feature:** Medications

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

On the `/about`, `/refill` and `/prescription/[ID]` pages, links to "Learn how to renew prescriptions" send users to a new page `/about/accordion-renew-rx` which appears to be the exact same content as the /about page but with another `h2` highlighted and one accordion expanded. Having the same page content at two separate URLs is confusing and results in broken/inconsistent breadcrumbs and URLs.

## Recommended action

When creating links to a certain portion of an existing page and/or expanding a certain accordion on a page, use a `#` to link to a certain anchor on the page, or use a URL parameter to perform the toggling action, rather than appending a new child segment for the page and thus creating an entirely new URL.

Example: `/about#renew-rx` or `/about?toggle=renew-rx`

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [URLs](https://design.va.gov/content-style-guide/url-standards)
- **Context:** URL formatting

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by IdeaTrail** [comment]
Completed with Jira ticket: https://jira.devops.va.gov/browse/MHV-58728
