### ISSUE TITLE
Add content into Figma prototype for usability testing

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#84211]
## Tasks 

- [ ] Need to remove placeholder content and use contextual content so the Veteran doesn't get stuck during usability testing in the Figma prototype
- [ ] Determine what content is needed and update content as needed

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/84211?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by Cieramaddox** [comment]
@benbrasso-agile6 The prototype is using all demo text, but if you see any that isnt, please tag me in the file. I may be missing it

**Comment by benbrasso-agile6** [comment]
Cool! I'll take a Quick Look!

**Comment by cgednalske** [comment]
And I've been trying to copy what Ciera has in the Figma prototype, so let me know if anything changes there! 👀

**Comment by benbrasso-agile6** [comment]
Sounds like ya'll were ahead on this ticket all along :)
