### ISSUE TITLE
Verify Appointment Slot DateTime Format/TZ We Get From Vista Service Provider

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#8421]
## User Story or Problem Statement
As a developer, I need to know what datetime format to expect from Vista Service Provider for appointment time slots so I can properly display and format them for the user.

Legacy var-resources was returning a date time without a tz applied and we had to do some non-standard stuff to apply the time zone.  We need to know if this will still be the case with VSP and update the slot transformer if necessary

## Acceptance Criteria
- [x] Verify datetime format and time zone we get from Vista Service Provider
- [ ] Update as needed to UTC to follow FHIR spec

**Comment by lenaecb** [comment]
Dependent on the VSP Slots endpoint

**Comment by jbalboni** [comment]
The date times from Slots are in UTC. I'm a little nervous about transforming the existing dates into UTC, because we could get out of sync if our timezone data is wrong. Might be worth some more discovery with the EAS folks about how timezones are handled in VistA up through VSP.

**Comment by jbalboni** [comment]
I'm handling this in #9078 by converting VSP times to facility time. Closing.
