### ISSUE TITLE
Staging Review finding: Title tag inaccurate on Medical Records page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84239]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Cartographers
**Product:** MHV on VA.gov
**Feature:** MHV Secondary Nav

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The first segment of the `<title>` tag for the [Medical records](https://staging.va.gov/my-health/records) page is "MyHealtheVet" which does not match the page's URL, H1 or current breadcrumb.

## Recommended action

Update the first part of the `<title>` tag to "Medical records".

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by sterkenburgsara** [comment]
This is my miss! Thanks to @erinrwhite for catching! 

Should be: `Medical Records | Veterans Affairs`

**Comment by LynneJohnson224** [comment]
@brea11y this ticket is ready for your review

**Comment by brea11y** [comment]
Verified that the title tag is "Medical Records | Veterans Affairs" (see Sara's previous comment above).

**Comment by LynneJohnson224** [comment]
@wesrowe - @brea11y has validated this fix. Can we close the ticket?
