### ISSUE TITLE
Staging Review finding: Cerner user can't determine next step when visiting medications list or refills from MHV landing page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84238]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Cartographers
**Product:** MHV on VA.gov
**Feature:** MHV Secondary Nav

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine next steps in a flow.](https://design.va.gov/about/experience-standards/#user-can-determine-next-steps-in-a-flow)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

When logged in as a Cerner user and accessing the "Review medications" or "Refill VA prescriptions" links from the MHV landing page there is not a useful information message sending the user to the other/original MHV. This info does appear on the About Medications page. 

This could result in a confusing and inconsistent experience for Veterans who use both the secondary navigation bar and the navigation links from within the MHV landing page. When accessing a medications page through the secondary nav, they'll be given a path to find the information they need. When accessing the medications page from the MHV landing page, they wlil not.

<details><summary>Link, screenshot or steps to recreate</summary>

- Log in as Cerner user
- From [MyHealtheVet landing page](https://staging.va.gov/my-health), select "Review medications" or "Refill VA prescriptions"

</details>

## Recommended action

Show the "Make sure you're in the right health portal" Cerner alert component on the `/medications` and `/refill` views.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** User flow

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by kfink24** [comment]
@wesrowe Tony on Meds has an open ticket for this and will be adding it to a PR he has open quickly. He had only added the alert on the /about medications page but will now add it to both /medications and /refill pages

**Comment by wesrowe** [comment]
@allanto-ah, when you have time could you please validate that the PR just above this comment did in fact fix the issue that the governance team raised.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the /about, /medications and /refill medication pages has the Cerner alert components. @wesrowe all good on my side!

/about medications page:
<img width="1504" alt="medications-about" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/94e84b34-ac03-463e-a6c6-942ab0c75a78">

/refill medications page:
<img width="1504" alt="medications-refill" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/a9876fc4-0d34-490e-b60a-f7a590d92abc">

/medications medications page:
<img width="1502" alt="medications-medications" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/160943382/ec1096a6-f4c3-4de2-975e-502041e8175e">
