### ISSUE TITLE
MHV Deeplinking Not Showing Authenticated State in Some Browsers

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#8424]
**Expected Behavior**

As a user logged into VA.gov with an active SSOe session, I expect that navigation with conditionalized MHV urls to link me to MHV pages where I'm already logged in (via the eauth-proxied URLs). Once I'm there, further navigation on MHV should remain logged in.

**Actual Behavior**

The linked page has a logged in state, but further navigation is logged out. 

This behavior has been observed in Firefox and Safari. 

Chrome and IE do not appear to be an issue.

**Comment by christine-dillman** [comment]
This is outside the scope of SSOe/Identity.
