### ISSUE TITLE
Check on the links in TeamSite Overview

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#84254]
After Ticket [83544](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/83544) has been closed and [TeamSite overview](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1855127627/TeamSite+overview) has been deployed and a few days have passed, check the staging links in [TeamSite overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview) to see if they work.

Acceptance Criteria:

- [x] The staging links in [TeamSite overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview) are confirmed to be working either because the staging issue was fixed by the VA or because we made a fix.

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/84254?planning-poker) with Zenhub @laucon

**Comment by laucon** [comment]
Jill approves, so this ticket is done and can be closed. :)

**Comment by jknipes** [comment]
work is finished, moving to _Done_
