### ISSUE TITLE
Contact Center Review for Cartographers - MHV-on-VA.gov Landing page and portal navigation

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#84276]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
The My HealtheVet-on-VA.gov landing page serves as a front door to VA.gov’s health-related applications. It also includes a My HealtheVet navigation bar (aka "secondary navigation"), which makes the MHV landing page and four main health tools easily accessible to users wherever they are in the My HealtheVet-on-VA.gov portal. 

### Launch Date
*Please provide the launch or rollout date and details.*
Production launch around June 17, 2024.

### Version Number
*Please provide the version number of the guide and/or video.*
2.0

### Product Guide
*Please provide product guide link*
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/contact_center/MHV%20on%20VA.gov%20Landing%20Page%20v2.0%20-%2005242024%20final.docx

### Product Video
*Please provide product video link*
N/A

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @wesrowe. The draft looks good, so I'll share it with VEO. But first, can you please give me a quick summation of the v2.0 update?

**Comment by wesrowe** [comment]
MHV Landing Page v1.0 primarily linked to tools on the MHV National Portal (myhealth.va.gov). 

MHV Landing Page v2.0 is the Home page of an integrated portal that lives on VA.gov. Now Veterans can stay on VA.gov when they use most of the tools related to their health care (except for Medical Records).

**Comment by starlow00** [comment]
There are no changes from VEO. The current copy is attached for future updates. Thanks!

[MHV on VA.gov Landing Page v2.0 SRT 06032024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL005QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a64d02618138891e7cc5e1e9a76a3d2cef0ad0f/MHV%20on%20VA.gov%20Landing%20Page%20v2.0%20SRT%2006032024.docx)
