### ISSUE TITLE
BE | Profile | Profile completeness | Missing contact information data discovery

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#84274]
## Background
To measure the success of our profile completeness MVP (project outline), we need to figure out the current number/percent of VA.gov users with LOA3 accounts that are missing:
- contact email address
- mailing address
- home phone
- work phone
- mobile phone

VA Profile can get us the numbers of total people missing that information, but their numbers don't account for whether or not the person has an identity verified VA.gov account.  

In this ticket, we'll work to determine how we can get access to metrics that answer the question "What percent of identity verified VA.gov users are missing [specific contact info]?" so we can query this periodically and see how we're moving the needle.

## Tasks

- [ ] (tom to fill out)

## Acceptance criteria

- We know whether or not we can get these numbers, and if we can, we have baseline numbers to use as KPIs for our MVP.
- We know how to get this information in the future when we want to check in and see how our MVP is impacting the numbers.

**Comment by tpharrison** [comment]
I'm wondering if I can run queries in some of the VA databases I have access to in order to answer the question.  I reached out to Mike Richards and Josh Lindsey to ask for their assistance.

**Comment by tpharrison** [comment]
@andaleliz I contacted Mike Richards and Josh Lindsey to see if I could run a query against the database I have production access to. Their reply was:

"The database is not related to VA Profile. Data retrieved from that location may not reflect the data we have in VA Profile or in the VA.gov Profile as it is retrieved from us. It might be a good source of MPI identities with LOA3 correlations, but I have no insight there."

Based on this response, I don't think this approach will get us any answers.
