### ISSUE TITLE
[CAIA Intake] <Transition Experience>: <Improved search results>

### ISSUE THREAD

**Issue by YevgenyDreyband** [department-of-veterans-affairs/va.gov-team#84270]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Transition Experience (VES)
- **OCTO product owner:** `Insert name and/or GH handle`
- **Product name:** Transition Experience
- **Product manager:** Gene Dreyband
- **Slack channel:** #ves-transition
- **Dedicated content writer on your team (if you have one):** `Insert name and/or GH handle`
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [x] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Interval search on VA.gov is sometimes overly specific and can be difficult to use for people that don't know the exact terms they are looking for.

We see this as an extension of the transition experience project goals; to acclimate different key groups to their benefits and VA.gov generally. This includes recently separated Veterans, transitioning servicemembers, Veterans returning to VA after a long absence and any other parties using the site. One of the natural actions someone might take after using our (in development) guided experience would be to search around VA.gov for more information.

For people new to VA, I see two key issues with search today:
1) When searching for something specific such as a form, only very precise search terms yield results; example "526" and "526EZ" return the disability form, but "526 EZ" and "526-EZ" return useless results
2) Those not intimately familiar with VA terminology will use their own best guess at describing something, which can yield results that take more effort. Example: "disability" and "disability compensation" return the main disability comp page, but "disability payment" brings up disability comp for PTSD (a sub-page) and VA Pension Benefits.

While it is possible to find these things with better accuracy on Google.com, it breaks continuity to have to leave the site, especially when we are trying to create a positive first impression.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [ ] No
- [x] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Our team is not currently addressing the issue, however it does impact the broader success of the transition experience so it is a subject of interest for our team. If this becomes a formal initiative from OCTO/CAIA we would like to be involved in the project.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [x]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.*

(This is a new exploration to bolster ongoing CAIA work to improve search, we would participate in collab cycle as a joint stakeholder)

### Collaboration cycle ticket

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Supporting artifact <name>](https://va.gov) `placeholder link`

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by mnorthuis** [comment]
@YevgenyDreyband This request appears to be directly aimed at improving search results - specifically the recommended results (aka best bets) within the search.gov experience used on va.gov.   Search.gov is not quite as robust as google, so we have a lot of legacy pages and pages not well optimized for SEO that show up in our search results.  We have limited ability to influence most of that, but we can help with the best bets.   

We have a[ Best bets request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco&labels=sitewide+content%2C+sitewide+CAIA%2C+Sitewide+IA&projects=&template=Best+Bet+Request.md&title=Best+bet+request+for+%3Ctopic%3E) that can be used for requests for new or changes to best bets.  

Otherwise, I am happy to have a conversation about some of the overall things you are seeing and want to focus on.

**Comment by YevgenyDreyband** [comment]
@mnorthuis that makes sense. Let me know if you'd like to schedule a chat or do it async via Slack, open to either. In the meantime should I create a Best Bets ticket instead?

**Comment by mnorthuis** [comment]
Gene and I discussed this and reviewed a few items.  There is no deeper work to do on this for now.  Best bet tickets will be opened in the future as needed.  Closing this.
