### ISSUE TITLE
Business intake form for Accredited Representation Management

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84313]
## Your Details
1.  Lindsay Li-Smith

2.  **Business Line** Benefits Portfolio
​
## Notification Details
1.  **Notification type** Email notification
​
2.  **Please describe your use case.**
At the end of our Appoint a Representative MVP experience, users will have an option to download a PDF version of the form they just filled out.  After clicking "Continue", all users will be routed to the final page in the flow, titled "your next steps" (appoint-rep/next-steps).  **We'd also like to send an email notification at this step**, confirming the form completion and reiterating next steps -- this would be  for users who have an email stored in their profile information, or have entered an email manually within the Appoint a Representative experience.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/6b913495-9f2c-40ae-a82d-69ddeca237c8)
​
3.  **What actions can the user take based on the notification they receive?**
    There are some links we'd like to include for reference around the process and next steps.  We'd also like to include a copy of the completed form for download, but are currently unsure if this is achievable as the form will include PII.  We'd like to discuss the download concept with a Privacy Officer, and are also curious if VA Notify has ever done something like this in the past, with another team.
**Update**: We are no longer pursuing a download link in the email notification.
​
4.  **What is the desired business outcome?**
    Awareness to users of next steps, in a way that can be referenced outside of our Appoint a Representative product.  In user testing, many did not fully grasp that there were additional steps after completing the Appoint a Representative experience.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    We plan to create a request in vets-api that will create a Sidekiq job to engage VA Notify's code to send out the email notification.
​
6.  **What will trigger the notification?**
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
   Clicking "Continue" in the final step of the Appoint a Representative process (i.e. on the Download screen).
​
7.  **Provide sample content per notification type, if you have it.**
    CAIA has been helping with our email notification content, and a template is [located in Sharepoint](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/_layouts/15/Doc.aspx?sourcedoc=%7BC3079214-7C45-4B47-B72C-F8AD962F23CF%7D&file=1.%20ARM%20AAR%20V1%20email%20content.docx&action=default&mobileredirect=true).
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (ex., PO has seen the content but it is not approved)
   We have sent the email notification content to a Privacy Officer and requested a meeting, but have not yet heard back.
**Update**: Privacy Officer Gina Siefert confirmed there are no issues on 6/24/2024.
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
   The Sidekiq job used to kick off the notification should be able to provide the email address, so we plan to provide contact information.
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
   We do not, and have no plans for text notifications.  
​
11.  **What is the anticipated volume of notifications per day, week, month?**
   This is a brand new product, so it's hard to say. 
​
12.  **When does this notification need to be in production?**
   We are planning to release our MVP in mid-August 2024.

**Comment by oddball-lindsay** [comment]
@mjones-oddball and @bevnobev since this is our team's first time partnering with VA Notify, I was wondering if we could have a kick off call to discuss:
1. The possibility of a form download in the email notification
2. Any things we should be extra-aware of, as newbies to your service

Let me know if you'd be open to a call, and if so -- who should chat with us.  Happy to set something up!

**Comment by mjones-oddball** [comment]
Hi @oddball-lindsay! Happy to have a call to discuss this use case. Can you provide a few days/times next week that work for a 30 minute kickoff call?

**Comment by oddball-lindsay** [comment]
Thank you @mjones-oddball!  Here are some options for a 30min call, in order of preference:
1. Tuesday 6/4 at 10am or 2:30pm ET
3. Monday 6/3 at 2:30pm ET
4. Wednesday 6/5 at 1pm or 1:30pm ET

**Comment by mjones-oddball** [comment]
@oddball-lindsay Here's the notes from our call! When you're ready let us know what the plan is and we can provide as much or as little support as desired. I'll need VA email addresses to onboard team members to the self service portal and to send Holden the API key (if needed).

- Use Case Details: There is a form that the Veteran can fill out digitally, but then they need to download, sign, have a rep sign, and return. These next steps are often lost, so the follow up email will be helpful to ensure the Veteran completes the process.
  - MVP is a confirmation/next step email that might include a link to download the form (under discussion)
  - Download of the PDF needs to be an authenticated experience due to PII/PHI
    - We suggested a couple options:
      - Full login to access the form download
      - Minimal validation for those who don’t have an account:
        - E.g. full name and DOB needs to match the form
      - Holden mentioned the possibility of OTP
- Question about finding a Privacy Officer: 
  - Christy recommended a chat with Patrick Bateman from the Collab Cycle perspective in case they have a Privacy Officer recommendation and shared the sharepoint link to the [OIT privacy list.](https://dvagov.sharepoint.com/sites/OITPrivacyHub/SitePages/Privacy-Officer-Locator-Resources.aspx) 
  - I recommended if all else fails ask the VA stakeholder or PgM might be able to ask the COR who their Privacy Officer is.
- We explained what form strike team support could look like and Lindsay is going to chat with her team and decide if she wants engineering assistance or not.
  - Forms Strike Team will need 2-4 week lead time to schedule the work if they are helping with engineering effort
- The self service portal has sample templates, so y'all can start from the email confirmation template and revise as needed for your use case to include the next steps. Documentation is in the portal as well if you need it.
@holdenhinkle here's some info on the vets-api module I mentioned: https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/va_notify#vanotify

**Comment by oddball-lindsay** [comment]
@GitSamJennings if the ARM team wanted to accept help from the Strike Team to build out the trigger, what would you need from us to complete that work?

**Comment by GitSamJennings** [comment]
@oddball-lindsay we would need the notification template ids from Staging and Production and the personalizations you are wanting to pass. We would also have to know when you anticipate releasing this and coordinate the release together. We could set up weekly meetings, in order to plan how we can accommodate this seamlessly, especially in regard to the staged rollout/feature flag piece.

**Comment by oddball-lindsay** [comment]
Thank you @GitSamJennings will consider all of that as we make our decision.

For now, requesting access to the self-service portal for:

1. lindsay.li-smith@va.gov
2. emmerson.hinkle@va.gov
3. janelle.finnerty-boos@va.gov
4. joshua.fike@va.gov
5. colin.osullivan@va.gov
6. michael.tri1@va.gov

**Comment by GitSamJennings** [comment]
Hi again @oddball-lindsay! I have added you all as Editors to the va.gov service in Staging and as Viewers in Production.

**Comment by oddball-lindsay** [comment]
Thank you!  I'm able to initiate login with PIV, but after entering my PIN the process seems to stall out and I end up just looking at a blank screen.  The playbook mentions assigning us to the right service for our team -- is that the missing link?

**Comment by GitSamJennings** [comment]
I will take a look to see what’s going on first thing tomorrow morning and
get back to you. You and your team have been assigned to the proper service
and you should be able to get to the landing page, after entering your pin
to PIV in, so I will need to dig a little. Would you mind sending me a
screenshot in Slack of the error screen, with URL?

**Comment by oddball-lindsay** [comment]
I'm building our email template in staging (wohoo!) and am seeing our CAIA-recommended messaging has a footer that differs from the sample template.  Are we able to customize the footer language, or is it recommended to leave that alone?

**Comment by GitSamJennings** [comment]
@oddball-lindsay Anthony has now been added. Also, you are able to customize the footer. The footer in the sample is used as guidance.

**Comment by oddball-lindsay** [comment]
@GitSamJennings I'm just noticing this piece in the VA Notify Playbook:

> VA Notify submits a communication preference intake for your team (if applicable)
Please note, if you have a new communication preference your team will need to determine a plan to communicate this to Veterans so they know a new notification is available to opt into.

Does this intake apply to our team's use case?

**Comment by GitSamJennings** [comment]
Hi @oddball-lindsay! You should be good, as confirmation emails don't require a notification setting on VA.gov.

**Comment by oddball-lindsay** [comment]
@GitSamJennings in the spirit of Zero Silent Failures, our team is thinking about implementing Datadog monitoring to know when there is an error with the email confirmation we send through VA Notify. 

There are two opportunities we can think of for errors:
1. There is an error when our product makes a call to VA Notify's endpoint.
2. There is an error when VA Notify sends the email notification to the user.

Monitoring for #1 should be straightforward enough as we'll be initiating the call on our side and will know if it fails. But for #2, will VA Notify pass any alerts back to us, if the email notification fails to send?

**Comment by oddball-lindsay** [comment]
@GitSamJennings @christy-tongty @mjones-oddball our release is now scheduled for December or January. We recently confirmed that the email notification is working as expected in Staging and promoted the template to Production.

What is the criteria for closing this Intake ticket out?

**Comment by GitSamJennings** [comment]
@oddball-lindsay I believe you should be good to go, since everything is working, as long as you also have Privacy Officer approval for the template.

**Comment by oddball-lindsay** [comment]
Sure @mjones-oddball! Dropping our [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/release-plan-appoint-a-representative-1.0.md) here for record-keeping, where we plan to do a staged rollout between January 6-13, 2025. I'll mention that in the channel too :).
