### ISSUE TITLE
Cancel button appears on the details page for  Phone Appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#84318]
## Summary
Phone appointments are not cancelable online. The updated changes from the `va_online_scheduling_appointment_details_redesign` feature toggle has made a change to the existing behavior. 

## Specs
- Device: All devices 
- Browser: Any browser 

## Steps to Reproduce
**Test User:** judy.morrison@id.me

1. Go to: https://staging.va.gov/my-health/appointments/e18be399aeba3aa892738188f21924edcc1fd85330c6e195ff531b625a950a64
2. Cancel button appears on the details page

### Actual Result
Cancel button appears on the Appointment Details page

<img width="539" alt="Screenshot 2024-05-30 at 10 04 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/df390ce6-02fb-4b68-9024-c3e9832c861a">

### Desired Result
Cancel button should not appear (screenshot of the current behavior/page - feature toggle turned off)

<img width="539" alt="Screenshot 2024-05-30 at 10 01 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/4212569b-c356-4e14-8d71-5d267b128e04">

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by vbahinwillit** [comment]
@ldelacosta - Is the phone scenario in the [Redesign Cancelation Flow](https://www.figma.com/design/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?node-id=2266-80310&t=mZpRHCJNmX9bcdBZ-4) correct or should it be updated? It shows the phone appointment detail page with a cancel button. Thanks

**Comment by ldelacosta** [comment]
@Cieramaddox - Could you please update?

**Comment by Cieramaddox** [comment]
@ldelacosta This ticket has been validated by UX

**Comment by Cieramaddox** [comment]
@ldelacosta @outerpress Copy docs need to be updated too. Our documentation states several times over that phone appts can be canceled online.

**Comment by ldelacosta** [comment]
@vbahinwillit - we will not make any changes. We will need to review the existing Phone appointment cancelation flow.

**Comment by ldelacosta** [comment]
Closing out the ticket.
