### ISSUE TITLE
Flipper UI access for Branden Bartlett

### ISSUE THREAD

**Issue by bradbergeron-us** [department-of-veterans-affairs/va.gov-team#84322]
### Your Name

Branden Bartlett

### Your GitHub handle (Flipper UI access is managed through GitHub)

Bbartlett26

### Team, Role, and Company of the target individual

My Education Benefits - Testing Lead - Accenture Federal Services

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by davidpetras** [comment]
@bradbergeron-us Good morning, Branden can be verified in Atlas however they are not a part of the VA GitHub org documentation to request access to that org can be found [here](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization). Once they are part of the VA GH org please feel free to reopen a Flipper UI access request. 

Thank you!

**Comment by bradbergeron-us** [comment]
@davidpetras, I had completed an [invite request](https://github.com/department-of-veterans-affairs/github-user-requests/issues/22245) for him to join the Org. I think he hadn't accepted the invite by mistake. He is added to our Github team now though.

**Comment by davidpetras** [comment]
@bradbergeron-us thank you for the quick response. @Bbartlett26 now has access to Flipper UI `lesser environments`.
