### ISSUE TITLE
Pension rewriting restart: Completing rewriting to enable redirects

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8432]
## Product Outline
Completion of pension hub rewriting.

## High Level User Story
As a Veteran or family member who needs or has a VA pension, I need to have clear, accurate, easy-to-access information about my pension benefits so I can plan my finances.

## Hypothesis or Bet
**If** _we provide VA pension information in a modernized, easy-to-read form_ **then** _we expect pension beneficiaries to find the information they need_.

## OKR
Finishing this epic will allow the team to meet the goal of redirecting all tier 1 legacy benefit pages by end of Q2.

### What must be true in order for you to consider this epic complete? 
All steps on [issue #8362](https://app.zenhub.com/workspaces/dsva-5e0105febd078d9165e53a99/issues/department-of-veterans-affairs/va.gov-team/8362) are complete and the last remaining rewritten pension hub page is live.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by bethpottsVADEPO** [comment]
This work is complete. Closing.
