### ISSUE TITLE
Update "View current rates" link on About GI Bill page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8433]
User story: 
As a Veteran I want to see a list of current GI Bill rates, as in the index page, when I see "View current rates."

Page changed:
Post-9/11 GI Bill (Chapter 33) https://www.va.gov/education/about-gi-bill-benefits/post-9-11/

Link changed: View current rates

Now links to:
https://benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp

**Comment by AnneHurley** [comment]
@RLHecht  This is done and ready for copy edit & publish:
prod.cms.va.gov/node/935/edit

@jenniferlee-dsva @DanielleThierryUSDSVA @stephorkandatx  FYSA

Do we need to send out an FYI email to stakeholders about this change?

**Comment by stephorkandatx** [comment]
@AnneHurley sorry for the delayed response. Were you able to get an answer to the question above?

**Comment by AnneHurley** [comment]
@stephorkandatx - no, because the page hasn't yet been published. @RLHecht Just checking in that you can do a copyedit pass and set this to publish?

Summary: Link on main About GI Bill page, https://www.va.gov/education/about-gi-bill-benefits/post-9-11/, that says "View current rates" links to an old page: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080118.asp

Instead, we agreed it should like to the "index" page that lists all the years' rates, including the current year. That link is: https://benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp

I think we could go either way on sending a heads up to stakeholders, or not. They'll be happy it's not linking to an outdated rates page, and I'm sure happy to link to the index page that's both correct and covers all the years. If that sounds OK to you.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate.

**Comment by RLHecht** [comment]
This change is now on the live site. Closing issue.
