### ISSUE TITLE
Life insurance rewriting restart: Completing rewriting to enable redirects

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8434]
## Related Epics
Life Insurance Content x Collab Cycle Plan #10930

## Product Outline
Completion of life insurance hub rewriting.

## High Level User Story
As a Veteran or family member who needs or has VA life insurance, I need to have clear, accurate, easy-to-access information about my life insurance benefits so I can plan my future.

## Hypothesis or Bet
**If** _we provide VA life insurance information in a modernized, easy-to-read form_ **then** _we expect Veterans and family members to find the information they need_.

## OKR
Finishing this epic will allow the team to meet the goal of redirecting all tier 1 legacy benefit pages by end of Q2.

### What must be true in order for you to consider this epic complete? 
All steps in related issues are complete and all pages are live.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by stephorkandatx** [comment]
We have made adjustments to batch 2 & 3 tickets, to modify and trim down the check list and assignees on each step. The adjustments came as a result of viewing the original check list in backlog grooming yesterday. Noting the updates have taken place here in the Epic.

**Comment by MickinSahni** [comment]
👋 @DanielleThierryUSDSVA @lwalsh617 is this epic intended to capture work across all batches or would individual epics for _each batch_ would be helpful?

**Comment by lwalsh617** [comment]
^ IMHO I'd leave it as one Epic because it's all part of a single effort we need to manage and track. We separated it into batches mainly for the SMEs, so we don't overwhelm them with 14 pages to review at once. Make sense?

**Comment by MickinSahni** [comment]
yep makes sense. btw i added the new epic for this initiative's progression thru the collab cycle: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10930

we're using this to track what we are/are not doing so please keep it up-to-date with any decisions made.

**Comment by FranECross** [comment]
All tickets in the epic are closed/completed. Closing the epic.

**Comment by diondredroidios** [comment]
see below.
