### ISSUE TITLE
Cancel VA Appointment Request on the Confirmation Details Page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#84347]
## Summary
When the user cancels a VA appointment request, the confirmation screen should match the [specs](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=0-1&t=jxDC0gNOEVsfX3Bq-0). 

## Specs
- Device: All types 
- Browser: All browser types 

## Steps to Reproduce
**Test User:** patient999@id.me 

1. Create a VA appointment request 
2. Cancel the VA appointment request from the confirmation screen 

### Actual Result
Cancelation confirmation screen does not match the design spec. 
- Missing the card 
- Cancelation message is incorrect.

<img width="556" alt="Screenshot 2024-05-31 at 12 17 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/91c850d5-f722-4c17-aa52-a608399c66fa">

### Desired Result
A screenshot from design spec. 
<img width="452" alt="Screenshot 2024-05-31 at 12 21 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/c3a67ff2-9921-4ce5-b6e9-71b3505c187a">

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by vbahinwillit** [comment]
@ldelacosta - I believe the cancelation message is correct. When the user is in the cancelation flow, the message should state, "You have canceled your appointment/request". See [Redesign Cancelation Flow.](https://www.figma.com/design/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?node-id=2277-131863&t=mZpRHCJNmX9bcdBZ-4) When the user selects the detail view for an appointment the message should state, "Canceled request for appointment".

**Comment by ldelacosta** [comment]
Closing this ticket. No issue detected.
