### ISSUE TITLE
Update TTY number 800-829-4833 to 711

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8435]
## What happened?
As part of our coronavirus chatbot work, we were alerted that TTY 800-829-4833 is an outdated number and it needs to be replaced by TTY 711.

Example from https://www.va.gov/change-direct-deposit/ below:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/35c7c503-d10d-4086-8bf4-57a2df23fb0c)

## Specs:
- Device: n/a
- Browser: n/a
- Test User n/a

## Steps to Reproduce
- URL: 

Needs to be changed on:
- [x] https://www.va.gov/change-direct-deposit/ 
- [x] https://www.va.gov/va-payment-history/ 
Potentially other pages in Drupal as well
- [ ] @kelsonic to search for and change on pages not accessible in Drupal

Also appears on Teamsite pages: https://www.va.gov/search/?page=2&query=800-829-4833. Can alert stakeholders of this.

- Test User _(if applicable)_: n/a

## Desired behavior
For all instances across the site, the TTY number 800-829-4833 should be replaced with 711.

## Acceptance Criteria
- [ ] All instances of 800-829-4833 across the site have been replaced with 711.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
For @stephorkandatx to assign as appropriate. Thanks!

**Comment by stephorkandatx** [comment]
May need a FE engineer to help search for impacted pages. 
The changes will be content updates.

**Comment by RLHecht** [comment]
Need to confirm whether all TTY numbers are being changed to 711 or only the 800-829-4833 number?

**Comment by RLHecht** [comment]
Update: Drupal instances have all been deleted. PR open for ones I can't get to. FYSA @DanielleThierryUSDSVA @stephorkandatx

**Comment by kelsonic** [comment]
List of TTY numbers used on `vets-website` currently:
```
1-800-799-4889
1-800-829-4833
1-800-877-8339
1-866-363-2883
711
800-829-4833
800-877-3399
800-877-8339
```

**Comment by kelsonic** [comment]
PR merged! 🎉https://github.com/department-of-veterans-affairs/vets-website/pull/12444 CC @RLHecht

**Comment by DanielleThierryUSDSVA** [comment]
Yay! Thank you so much, @RLHecht @kelsonic!

**Comment by kelsonic** [comment]
Of course! Let me know if we should update any of the other TTY numbers in the codebase @DanielleThierryUSDSVA! 🙂

https://github.com/department-of-veterans-affairs/va.gov-team/issues/8435#issuecomment-622092587

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket.

**Comment by stephorkandatx** [comment]
@RLHecht I am still seeing the TTY: 800-829-4833 on https://www.va.gov/va-payment-history/ . Are you able to confirm you see 711 on your browsers?

**Comment by RLHecht** [comment]
@stephorkandatx Nope, you're right. I saw the correct one on the Direct Deposit page. Let me check in Drupal and see if there's an issue.

**Comment by RLHecht** [comment]
@stephorkandatx This is now fixed. Will check after today's deploy to confirm it's on the live site.
