### ISSUE TITLE
[UX]10-10CG Caregiver application post-SME feedback content/design file adjustments

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#84352]
## Issue Description
As a Veteran, Caregiver or a Representative, completing the form, I want the form to be accurate and aligned with what is required (paper form).  

During the weekly sync stakeholders mentioned they have feedback to the content updates. They will be providing any high-priority concerns by end of day Monday 6/3. These will need to be vetted and content and design files updated. 

- [Ticket for prepping the doc that Stakeholders / SMEs are reviewing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83393)

---
## Tasks
- [x] Review feedback with team and content
- [x] Apply changes to designs in Figma

## Acceptance Criteria
- The designs are updated to fully reflect all changes that need to be included for the July 1 launch of the caregiver form updates. 
---

**Comment by jessicastump** [comment]
Adding doc that was sent end of day Friday 5/31
[VA.gov 10-10cg Feedback Review 5.31.24.docx](https://github.com/user-attachments/files/15518829/VA.gov.10-10cg.Feedback.Review.5.31.24.docx)

**Comment by jessicastump** [comment]
@hdjustice (and @longmd for visibility too) -- 
Status summary listed below of that document SMEs sent over but details can be found in Figma comments marked “From SMEs” in the content [source of truth section](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=494-7358&t=y1s0pUO3YbfvRdDQ-4) (and [confirmation page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=595-26630&t=y1s0pUO3YbfvRdDQ-4) content too)

**Intro Page**
- Removed the additional info component and some content from step 2
- Form subtitle updated: Application for the Program of Comprehensive Assistance for Family Caregivers (VA Form 10-10CG)

**Primary Caregiver Section**
- Added Primary Caregiver to label for Suffix

**Secondary Caregiver Section Changes**
- Removed some text around monthly payments on identification/ssn question

**Identification question overall**
- Removed “now” from content in second paragraph


**Confirmation page**
- Fixed duplicate text (to check to check)
- Another sentence edits in the works, see below


### Still in content review (for high-priority items)

- The content in step 3 of the intro page around making changes to Caregivers is still in the works (and this is throughout the form) —  Aliyah is trying to find a balance between the 1:1 paper form stakeholder request and a plain language way to explain the process that isn’t conquering for SMEs (the add language trigger), I have some suggestions in the Figma comments when Aliyah can circle back to this after other priorities
- Confirmation page about email next steps (I sent a proposed draft to via comments that she wants to make a small edit to…)


### On the Secondary Items, 

Grouped the edits not made, listed above, into these three groups:

1. Things to push-back and not change. (Postal code to Zip Code request example) due to clear deviations from the VA.gov content style guide standards.
2. **A SME QUESTION** — There are a couple of comments around removing the TIN references in the content and label on the various identification screens.. but that is on the paper form and online today. Can we learn more about this and their reasoning here?
3. Clarification and content additions all around caregiver roles, reqs and benefits. I think this needs to be looked at post-this round of updates and we should chat more about this before we talk to stakeholders again.

**Comment by jessicastump** [comment]
**[SUPER rudimentary prototype started here](https://www.figma.com/proto/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=1492-24291&t=y1s0pUO3YbfvRdDQ-0&scaling=min-zoom&page-id=376%3A15166&starting-point-node-id=1492%3A24291)** - this is a basic only the continue and back buttons function at this point, there is no conditional logic to skip over pages and no form field functionality but thought this could work to gather any (or sign off for accuracy) other SME content feedback pre-staging phase.

**Comment by jessicastump** [comment]
[VA.gov 10-10cg Feedback Review 5.31.24-WNotes.pdf](https://github.com/user-attachments/files/15570628/VA.gov.10-10cg.Feedback.Review.5.31.24-WNotes.pdf)

**Comment by hdjustice** [comment]
Thanks @jessicastump 
We still have that Caregiver Clarification epic out there that we can pull in after this June release.  Probably a good time for it.

**Comment by jessicastump** [comment]
Adding an update here

**Comment by jessicastump** [comment]
Post Stakeholder meeting on 6/7, adding updates below:
1. On intro page, step 3, second paragraph should read:

> If the Veteran is already enrolled in this program and wants to add a new family caregiver, the Veteran and the new caregiver can use this application. 

And remove references/paragraph on Primary and Secondary pages about if enrolled, add a caregiver. 

2. The county additional info component text for Veteran:

> Providing the county where the Veteran lives helps us determine the Caregiver Support Team.


3. And for caregivers:

> Providing the county will help the Caregiver Support Team connect caregivers with community resources that offer supportive programs and services.

4. The Veteran identification screen question was updated to remove references of TIN in the content and the field and remove the hint text. 

There were a couple of other minor content consistency edits Aliyah made directly in Figma I'll comb through again and list here: added "primary" to the copy on the caregiver contact page, change telephone to phone on all the labels, added hint text to the caregiver ssn field.

**Comment by jessicastump** [comment]
1. Added "Veteran" to Veteran suffix label
2. Added "If  you’ve already completed these forms, you can submit the decision letter." after the bulleted list of VA forms (Sign as rep section)
3. The alert on the Secondary caregiver page (if none is added) was updated to remove all add/change references.

**Comment by jessicastump** [comment]
Some bolding changes on the confirmation page (to remove on the "you maybe also be eligible..") and on sign as rep question additional info component for documents (added bolding to an "or") (Aliyah added/edited in Figma)
