### ISSUE TITLE
[blocked] Life insurance rewriting: Content strategy & IA confirmation & re-kickoff

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8436]
# User story
As a writer/content strategist/IA working on this hub, I want to know that the original recommendations from 2019 are still relevant to this work, and that I have all the current information I need to complete this work successfully. 

As a life insurance SME, I want to be prepared to receive rewriting content/IA recommendations for review and to fully understand the process from the beginning.

# Details

## Background and goals
Because this work was paused in summer 2019, and it involves many pages, we want to do a mini re-kickoff to ensure that recommendations are still relevant, our writer is fully briefed from the start, and we're working in full partnership with SMEs throughout the process.

## Process steps to completion

- [x] Regroup to go over original IA/content strategy recommendations as well as SME answers to open questions (received May 2019), and determine any needed changes. (Mikki, Danielle, Laura)
- [x] Determine how the l4 work may impact rewritten pages we're building as part of this effort. (Mikki, Danielle, Laura)
- [x] Update tickets as needed to reflect changes from internal regroup. (Danielle)
- [x] Check legacy pages to ensure no new pages have been created since this work was paused in July 2019 (Mikki)
- [ ] Go over existing live pages (specifically definitions of life insurance types and terms) for clarity, timeframes, and general accuracy check. Gather questions and create working questions doc for SMEs. (Danielle, Laura)
- [x] Group and prioritize pages in order to finalize/review/redirect in chunks. (Danielle, Laura, Mikki)
- [x] Schedule meeting with SMEs via Sandy Tadeo. (Danielle)
- [x] Meet with SMEs to re-brief them on rewriting/redirect process, and ask questions and gather feedback on existing pages that may also be relevant for rewriting effort. (Mikki, Danielle, Laura)
- [ ] Update rewriting tickets as needed to reflect changes. (Danielle, Laura)

## Files for reference

- [Original recommendations from WBC content audit](https://docs.google.com/spreadsheets/d/1zAyUp9Eo6mBXR0vPRxiXfcuD11bJK5Q8vsZtD0ekxXw/edit#gid=0)
- [Current IA recommendations from VA.Gov IA master sitemap](https://app.moqups.com/Rnc4BDEKrA/view/page/a4692ee17)
- [URL map/redirects documentation in VA.Gov Master IA file](https://docs.google.com/spreadsheets/d/1YucOtYihweNPI1gYtCgdsinKQmH4DMuSgPaSgJMfyYk/edit#gid=1855195586)
- [Open questions and SME responses document](https://app.zenhub.com/files/133843125/bf76921b-7fc2-4800-bf5e-ab87eb1fd87f/download), received with responses from Lori Hamilton on 5/29/19. Requires follow up on a few responses.
- Old issues related to open questions:
  - [issue #17955](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17955): Myths and rumors about SGLI-VGLI]: See open questions doc. Likely not a tier 1 page.
  - [issue #19012](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19012): SGLI contact information: We'd been discussing whether this needs to be its own page or whether it can live within the SGLI page. Need to decide before creating rewriting issue.
- New proposed nav order from old vets repo issue #18188
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/ef0bb99d-2388-4201-8c43-0c4e9a60fab6)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mnorthuis and @lwalsh617. Are you available later maybe Friday to regroup on IA/content strategy for this?

**Comment by lwalsh617** [comment]
I’m wide-open on Friday, aside from stand-up.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mnorthuis** [comment]
I am open in the morning Friday

**Comment by stephorkandatx** [comment]
There is a meeting scheduled for May 1,2020. Will inform the strategy and how we tackle this body of work

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA @mnorthuis - Should we get a time on the calendar for tomorrow?

**Comment by DanielleThierryUSDSVA** [comment]
Sure, of course! I used VA email so maybe that's it? Do you need me to send to your GCIO email as well? Mikki, I can do the same for yours as well.

**Comment by mnorthuis** [comment]
Please send to my adhoc email. thank you!

**Comment by DanielleThierryUSDSVA** [comment]
**Notes from Friday 5.1.20 IA/content strategy internal re-kickoff meeting:**

- Went through open questions document and added notes for the restart. [Updated doc attached here](https://app.zenhub.com/files/133843125/9bddbc9c-76d4-4170-9fc5-502f4a9f0a88/download).
- Discussed whether we need to have a formal platforms kickoff for this work. Mikki followed up with Megan and confirmed that we do not need this.
- Discussed the question of when to bring accessibility review into the process. Danielle followed up with Stephanie to discuss, and we'll follow up with Jen Strickland to confirm.
- Discussed the process leading up to stakeholder re-kickoff meeting and prioritization of issues. Danielle has updated process steps to completion above to reflect.

@mnorthuis @lwalsh617

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA @mnorthuis - 
Here's the draft working doc. I'll reach out about scheduling a quick call to discuss. Thanks!
[life-insurance-rewriting-work-plan_05-01-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4581317/life-insurance-rewriting-work-plan_05-01-20.docx)

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA I did a quick review of the left nav and primary nav links of the legacy life insurance area to make sure nothing was missed/added since our audit last year.  

I did find one page that I did not have reference to: https://www.benefits.va.gov/insurance/insurance100.asp
This is not Veteran content, so I don't believe there is anything for us to do here, but wanted to call it out. 

One other thing we should review, for those items that we are not migrating, we need to think about how users will get to them once we redirect most of the left nav.  This is probably a bigger conversation we need to have across all the hubs - one we started with VHA but didn't get very far.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @mnorthuis! Yes, let's sync on the larger conversation. 

@mnorthuis @lwalsh617 @stephorkandatx **Timing update:** Sandy has requested that we hold the meeting with the life insurance SMEs at the 6/3 VBA check-in. Since this is simply a re-check in, I think this is okay. Thinking we can aim to send our working doc notes and the batch 1 pages about a week ahead of the call so we can tackle both the re-kickoff stuff and get their actual feedback on batch 1.

**Comment by stephorkandatx** [comment]
Blocked, backlog until meeting takes place

**Comment by lwalsh617** [comment]
We had this kick off so am closing this ticket.
