### ISSUE TITLE
Data Request for 526 Submission Experience

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#84387]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

04/01/2024

### Date Range End

5/31/2024

### Product Name(s)

526

### Product Description

The 526ez is used by Veterans to apply for disability benefits. I am requesting this data so I can see if I'm missing any known problems with submissions as reported by Veterans. 

### Survey URL(s), key term(s), case category or type

/review-and-submit
/confirmation

### Sub URLs

Yes

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

evelyn.davis3@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Let me know if you have any questions. Thank you.
