### ISSUE TITLE
[V0] Testing 

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#84398]
**Tasks**
End to end testing in staging:
* An user starts a form -> ITF is set -> VBA sees it in VBMS test env
* An user resumes a form -> no actions taken
* Test re-try mechanism -> ITF set eventually -> VBA sees it in VBMS test env
* Test re-try exhaustion notification -> so we know when to rectify manually [this might not be possible to test]
* Check that pension app isn't overwriting ITFs or causing any confusion in VBMS that negatively impact Veterans
* Actions being tested appear in DataDog accordingly

**Engineering will test:**
- Unit tests
- Find a test user in the staging user list that doesn't have an ITF for pension:
-- run a curl to against the LH API to GET the status
-- run Dan's code to create a new ITF
-- re-run the curl against the LH API to GET the status
-- You should now see an ITF

**VBMS UAT and/or testing with VBA team**
- Check that ITFs are appearing as expected
- That dates match the start date seen on app end

**AC**
* Pension ITF implementation isn't causing any confusion in VBMS, especially if it negatively impacts Veterans
* Pension ITF V0 is functioning as expected and has necessary logging and monitoring in place to provide transparency
* Based on results, get sign off to proceed to turn on ITF in prod

**Comment by mjknight50** [comment]
I think this is what I would do for ITF testing

- Unit tests
- Find a test user in the staging user list that doesn't have an ITF for pension:
-- run a curl to against the LH API to GET the status
-- run Dan's code to create a new ITF
-- re-run the curl against the LH API to GET the status
-- You should now see an ITF

Anything beyond that has diminishing returns.  I don't think we need to check or validate sidekiq.

**Comment by matt4su** [comment]
test plan document. https://docs.google.com/document/d/1qjur6kRluuUcW5KKCazZTWbc8jyUQCRLCcScWFyMWxY/edit

**Comment by matt4su** [comment]
PDF used for testing


[content (5).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29JQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75d7946d184bdfb14a84135aeb263ff767e77318/content%20%285%29.pdf)
