### ISSUE TITLE
Life insurance rewriting batch 1: Calculate your needs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8439]
# User story
As a Veteran, service members, or family member considering my life insurance options, I need to understand how much insurance I need.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [ ] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi, Danielle, Beth as needed)
- [x] Finalize existing GitHub draft (Laura)
- [x] Strategy/voice edit (Danielle)
- [x] Migrate to Drupal (Laura, Randi)
- [x] Add cross links to this page on other appropriate pages (Laura, Randi) 
- [x] Copy edit (Randi)
- [ ] Platform review (content and accessibility, possibly design) 
- [ ] Package with other Life Insurance batch 1 pages and send to SMEs for review (Laura, Danielle)

### IA details
_(note: IA and specifically urls may change based on l4 initiative)_

- **URL:** /calculate-your-needs/
- **Spoke:** More resources
- **Order:** 1
- **Left nav label:** Calculate your insurance needs

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_

- **Source page:** https://www.benefits.va.gov/INSURANCE/introCalc.asp#what 
- **SEO keywords:** how much life insurance do i need, how much life insurance do i need calculator, life insurance needs
- ** What's needed:**
  - Create a new page in the VA.gov voice/style that will serve as a landing page for the [life insurance needs calculator tool](https://insurance.va.gov/NeedsCalculator). 
  - Update link labels/url on hub page and in left nav (this replaces the *How much life insurance do I need?* link in the *More resources* section of the hub page).
  - Determine relevant crosslinking to/from this page and other relevant pages within this section.

**Note:** This page is a landing page for a tool that lives in Teamsite. We will not be touching the tool right now. However, we've captured the tool for potential revisit in our [potential future tools file](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/va-gov-relaunch-2018/design/content/potential-future-tools.md).

## Github files for reference

- **Current page in GitHub:** 
https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/calculate-your-needs.md

**Comment by lwalsh617** [comment]
GitHub pages looks good. Recommend providing preview link to SMEs.

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by RLHecht** [comment]
@lwalsh617 This page is now built in Drupal. The preview link is preview-prod.vfs.va.gov/preview?nodeId=5581

**Comment by lwalsh617** [comment]
@RLHecht Here's the document with Drupal links for batch/phase 1. 
[life-insurance-rewriting-phase1_v1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4732295/life-insurance-rewriting-phase1_v1.docx)

**Comment by RLHecht** [comment]
@lwalsh617 I copyedited this page. Ready for next steps.

**Comment by lwalsh617** [comment]
@DanielleThierryUSDSVA - This is ready for you to review: 
![image](https://user-images.githubusercontent.com/53535663/84077962-18905980-a9a6-11ea-9ed7-97f42e4dfe94.png)
Here are the cross link recommendations:
![image](https://user-images.githubusercontent.com/53535663/84077860-f0085f80-a9a5-11ea-8158-9764476204bc.png)
FYSA - @stephorkandatx

**Comment by stephorkandatx** [comment]
Closing this ticket out - future edits, updates will be written and handled in a new ticket. This batch was submitted for content review
