### ISSUE TITLE
[V0] Support docs / product guide updates

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#84399]
**To do**
Update support teams so that they are aware of ITF being set in the background (ie: if they get calls similar to ‘how did I get an ITF when I didn’t explicity set one?’)

**Comment by aplatt-coforma** [comment]
Shared the FAQ doc on SharePoint here: https://docs.google.com/document/d/1PjvZaSLeGf_vBKLX16EhDBiKJe1yUBR-iWP_-E705kY/edit#heading=h.wtvwrjruq0vf

Currently reviewing and addressing initial feedback through comments in the doc. We'll close this ticket and spin up a new one if there are additional edits on that doc that warrant a larger change.
