### ISSUE TITLE
MHV on VA.gov Qualitative Data Request (May 2024)

### ISSUE THREAD

**Issue by MHVuser1** [department-of-veterans-affairs/va.gov-team#84404]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

05-01-2024

### Date Range End

05-31-2024

### Product Name(s)

My HealtheVet

### Product Description

My HealtheVet (MHV) is VA’s online personal health record. It was designed for Veterans, Active Duty Service Members, their Dependents and Caregivers. MHV is in the process of migrating to VA.gov.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/health-care
https://www.va.gov/my-health
https://www.va.gov/resources/my-healthevet-on-vagov-what-to-know
https://www.va.gov/health-care/schedule-view-va-appointments
https://www.va.gov/my-health/appointments
https://www.va.gov/my-health/secure-messages
https://www.va.gov/my-health/secure-messages/inbox
https://www.va.gov/my-health/secure-messages/drafts
https://www.va.gov/my-health/secure-messages/sent
https://www.va.gov/my-health/secure-messages/trash
https://www.va.gov/my-health/secure-messages/folders
https://www.va.gov/my-health/secure-messages/new-message
https://mobile.va.gov/login-information
https://www.va.gov/resources/signing-in-to-vagov
https://www.va.gov/health-care/view-test-and-lab-results
https://www.va.gov/my-health/medications/?page=1
https://www.va.gov/my-health/medications/about

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

kophie.mathis@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. I shared two files one is from Medallia site, and the other one is from MYVA411 site. On the requested form, you have mentioned sub URLS and MYVA411. I was not sure, if you needed for MYVA411 or Medallia, because Medallia includes the URLs and sub-URLs. Let me know if you have any questions. Thank you.

**Comment by MHVuser1** [comment]
Good morning Sarifa,

Thank you. I only needed the Medallia, but this does give me a chance to see if MYVA411 output is useful to enhance VA.gov products moving forward.  I'll be sure to remember to change the default next month.

V/R Kophie Mathis



From: Sarifa Khalilulah ***@***.***>
Sent: Monday, June 3, 2024 2:16 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Mathis, Kophie V. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] MHV on VA.gov Qualitative Data Request (May 2024) (Issue #84404)


Hi, I have shared the requested data. I shared two files one is from Medallia site, and the other one is from MYVA411 site. On the requested form, you have mentioned sub URLS and MYVA411. I was not sure, if you needed for MYVA411 or Medallia, because Medallia includes the URLs and sub-URLs. Let me know if you have any questions. Thank you.

-

**Comment by newworld2616** [comment]
Thanks for letting me know. I have shared the Medallia data.
