### ISSUE TITLE
Comprehensive testing of the BE Full Transform.

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#84447]
Once the BE Full-Transform service is complete we will need to test it against more than just one input & output file.  Work with the FE team to determine edge cases not covered by [the Maximal FSR fixture](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/tests/e2e/fixtures/data/fsr-maximal.json) 
### Acceptance Criteria
- Identify edge cases
- Generate new input and output files based on these edge cases
- Write specs around these new input/output files
- Update service as necessary

**Comment by kjsuarez** [comment]
What are all of the FSR versions we should be testing against?
- [ ]  Enhanced FSR maximal
- [ ]  Enhanced FSR minimal
- [ ]  SW FSR short
- [ ] SW FSR long

**Comment by HeatherRienks** [comment]
Per @kjsuarez  in Sprint Planning, this ticket has additional effort remaining (about 2 pts) and we are expecting it to roll over. This ticket is blocked by the work required in #84132 and #84473, but we expect to complete in the upcoming sprint.

**Comment by kjsuarez** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17095)
Fixtures added and FullTransformService complete.
