### ISSUE TITLE
Associate 422 with "No Rep" Widget state

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84448]
## Background

We have been receiving a `422` status from Lighthouse for our Representative Status Widget, which is related to when there is no participant ID on file for a user.  A user cannot have an appointed representative if they don't have a participant ID, so we can show the "No representative" state for these users.

## Tasks
- [ ] Associate the 422 from Lighthouse with the "No Representative" Widget state

## Acceptance Criteria
- [ ] Users without a participant ID have a `422` status from Lighthouse, and see a "No representative" state in the Rep Status Widget.

**Comment by cosu419** [comment]
422 is showing up as No Rep (tested with [user 7](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv)) Closing.

<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWUvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f55622ea1e503eb54208509f63d270c42e1400b/image.png" alt="image.png" />
