### ISSUE TITLE
10-7959f-1 update explanatory copy for pre-fill 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84445]
As a user, I want to know where my information is being updated when I fill out the FMP registration form so I know where the changes apply.

[Figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=726-21596&t=c27oYcUwiizSAgu0-0)
- display only to logged in users
- show on mailing address page only

Acceptance criteria:
Given a logged in user is filling out the FMP registration
When they get to the mailing address screen
Then they should see a message about where their information will update

**Comment by reiting** [comment]
@marywang2 This is in review, but right now the build is failing. It gave a 502 error on initial build, so I am going to wait a few minutes and rerun to see if that fixes it (basically it didn't connect to the server for some reason, and that can sometimes just be a wait and try again scenario). I moved this here even though I'm not having it reviewed by anyone just yet because I want to fix the build first. However, if I can't fix it, I'll move it to blocked and ping platform for assistance.

**Comment by reiting** [comment]
Whatever kinks were in the system seem to have been worked out. This is now in team review.

**Comment by reiting** [comment]
Waiting for platform review.

**Comment by reiting** [comment]
@marywang2 this has been merged, but please remember that it won't be in staging for a few hours most likely.

**Comment by marywang2** [comment]
Thanks @reiting! I should have specified but the "please go to your profile page" should be linked to this url: https://va.gov/profile/contact-information

**Comment by reiting** [comment]
This is now in platform review.

**Comment by reiting** [comment]
@marywang2 I have merged this just now. Should be on staging in a few hours.

**Comment by marywang2** [comment]
Thanks - is there a way to make this a relative link? (When I view this on other forms on staging - they go to the profile page on staging, rather than live, not sure how that works).

**Comment by reiting** [comment]
OK, changed it. Team review.

**Comment by reiting** [comment]
Now in platform review.

**Comment by marywang2** [comment]
Great, thanks so much @reiting - I will try to be more specific next time :)

**Comment by reiting** [comment]
@marywang2 no worries! It's a fast fix. This has been approved and merged!
