### ISSUE TITLE
SOCKS access for [Efegbare Efenedo]

### ISSUE THREAD

**Issue by Efe-Oddball** [department-of-veterans-affairs/va.gov-team#84453]
### Your Name

Efegbare Efenedo

### Your Email

efegbare.efenedo@va.gov

### Your GitHub Handle

Efe-Oddball

### Your Role and Team

DevOps Engineer on Platform-Infrastructure-DevOps

### Product Manager (PM) name and email

Nate Peterson "nate.peterson@adhocteam.us" 

### Product Owner (PO) name and email

Aparna Nittala  "Aparna.Nittala@omb.eop.gov"

### Access Type Requesting

platform  (Requesting same access as @hgbarreto)

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6JTctAn2pcuQkaaiOvRW9iRCrN8v+mxNqlxx46RYqzPZuxtrPk833bWQFZn8dnzS6EktoX3EynjSXG2cL/jqYJ1Rbf2CbwMJFKc84x9jkIBid7pLxsY8ix+dAQZefkLR4y2+PZ0na9yRM8MNxiVPZSYtQkbqRus+u0RsoalMidJmeFQTyplINDT6caf9LiUKAdr513++kHCRq35MY0nnrL+Cw4ca5Vdcv+Gm+he3vJOHIgoczIe4A/mR8OVMktMWHdoQIBYWq16wRZ89j1u/jIqVWfKuM6rl17H/5nunbenAd2ksZQRpKNbpKXZeNZ7piq9LDoh1SBioMuftMVCWXp3P17m0QKbMMAvLnEYQbeKAecmCCKQEbtfZl8OVeGB+Z9q+PXPcQTQuV3y4UZ/vCozcUgAkZNzOTAedjaRoXztSXV9Yiy39IDy4Qn18vlP99s+RucOWDzCKGIPFeENdYhWYjmBR1rmgfHqgPlRSavXSap2E2YT03B4qJUm/0xnk= efe@DESKTOP-K8PHPPT

### E-QIP Transmittal Confirmation

<img width="1674" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117599248/2d9c137b-8ea3-4618-ae8d-57b394776d18">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
@Efe-Oddball I'm assuming your SOCKS access is good now? I'll close the ticket, but please let me know if you have issues.

**Comment by Efe-Oddball** [comment]
@stoiven Yes, we are good to go
