### ISSUE TITLE
Access for Efegbare Efenedo

### ISSUE THREAD

**Issue by Efe-Oddball** [department-of-veterans-affairs/va.gov-team#84459]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Efegbare Efenedo

### Your Email

efegbare.efenedo@va.gov

### Team, Role, and Company of the target individual

platform-cop-devops, DevOps Engineer, Oddball inc

### Product Manager (PM) name and email

Nate Peterson "nate.peterson@adhocteam.us"

### Product Owner (PO) name and email

Aparna Nittala "Aparna.Nittala@omb.eop.gov"

### Desired AWS Access

I need similar access to @Hector

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1674" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117599248/09e8c6aa-3429-40b4-b6f6-7f1b7e0a2ff2">

### Additional Notes

I need this access because I am a New DevOps Engineer with the Platform infrastructure team and I am trying to get access to the remaining required tools after getting my remote access 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Approved for DevOps, which is production-level access

**Comment by ph-One** [comment]
Found in Atlas

**Comment by stoiven** [comment]
@Efe-Oddball going to close this ticket as you have AWS access now
