### ISSUE TITLE
Start using Full Transform BE endpoint

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#84473]
Once #84132 has been finished (give or take)-
We will have a service to preform the full transform on the backend and a new BE API endpoint which will perform the full transform and then submit the FSR all in a single http request.

### Acceptance Criteria
- Create a new feature flag to delineate between the BE transform and the old FE transform
- At the point in the FE logic where the transform currently takes place, add a conditional based on the above flag
  - If the flag is true, hit the new BE endpoint with the untransformed data
  - If the flag is false, carry on as usual, ie transform on FE and hit old submission endpoint

**Comment by Dr-Pongo** [comment]
Moving to blocked as the new endpoint is still being finalized. Once we have the new URL we can slam it in the PR and merge

**Comment by HeatherRienks** [comment]
This work is blocked by #84132 - we expect to close this ticket very soon!

**Comment by Dr-Pongo** [comment]
Closing this out now that the new endpoint change has been merged! We can default the feature flag to true in lower environments when they are ready by reverting the following change:

https://github.com/department-of-veterans-affairs/vets-api/pull/17187
