### ISSUE TITLE
STEM:  Analytics Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#8447]
Review analytics from live site
Share findings with team

**Comment by amyknox** [comment]
What's the rate of successful submissions now?  22-1995 STEM Successful Submissionshttps://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20190815&_u.date01=20190828&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension49&_r.drilldown=analytics.eventLabel:edu-1995--submission-successful/
What's the rate of denied applications?
Look at On-Click event for "Explore additional education benefits" button to see how often users who aren't eligible for STEM take that as an off ramp.

**Comment by amyknox** [comment]
82% completing form on "desktop"
