### ISSUE TITLE
[DataDog] Reduce noise for Traffic anomaly monitors

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#84484]
### Description
The traffic anomaly monitors go off quite frequently (multiple times a week currently) and since those are watchtower monitors we have been asked to find ways to reduce the noise of these monitors.

### Engineering notes
The suggested approach is to utilize a Composite monitor / monitors, mostly likely by mixing in a monitor that goes off when traffic to the CST drops below some positive threshold value

### Tasks
- [ ] Determine how we want to implement this

**Comment by jerekshoe** [comment]
This ticket should be fleshed out more in the next Engineering refinement

**Comment by jacobworrell** [comment]
@jerekshoe is this ticket still relevant? If not, please close.
