### ISSUE TITLE
[CST][DESIGN] Replace old timeline for non-disability compensation claims

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#84491]
## Value Statement
**_As a_** Veteran
**_I want to_** see the new version of the timeline (AKA "Process list") component in the Overview tab of non-disability compensation claims
**_So that_** I see the most optimal version of this design component

---
## Background Context

We are only releasing our new Claim Phases design to disability compensation claims for now. Until we create more specific experiences for non-disability compensation claim types. That new design replaces the existing timeline (AKA Process List) component (see below) which is outdated and has some accessibility issues that have been flagged by the Platform team. 

Current UI:
<img width="638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM014QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a45e327b8188295b10292bdc706c96c478b4c7a9/Screenshot%202024-06-03%20at%204.09.05%E2%80%AFPM.png" alt="Screenshot 2024-06-03 at 4.09.05 PM.png" />

Until we can create more refined solutions for different claim types (which might take a while) we should at least replace this component with this newer component from the design system: https://design.va.gov/components/process-list

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

[FIGMA](https://www.figma.com/design/ifXbQZaH56bnWyCMbYkh7t/Timeline-Update-for-Non-Disability-Claims?node-id=2-11&t=30StABADM0SwhMqF-0)

## Engineering notes

Link to [va-process-list ](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--docs)

### Enablement team (if needed)
@jstrothman 

## Open questions
- How should we handle recent activity in the timeline

## Design Tasks
- [x] _Create specific desktop mock for this design 
- [x] _Create specific mobile mock for this design
- [ ] Make sure designs cover an open claim and a closed claim

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _There is a desktop design for an updated timeline on the overview tab using the va-process list
- [ ] _There is a mobile design for an updated timeline on the overview tab using the va-process list
- [ ] _Discuss with engineers when design is done and determine next steps

**Comment by skylerschain** [comment]
Added Figma link to **Design** section

**Comment by pmclaren19** [comment]
@skylerschain looks like this was marked complete in sprint 56 on 6/21 ish and you were planning on presenting in XfN Sync. Closing since you are OOO and we are starting a new sprint.

**Comment by skylerschain** [comment]
@pmclaren19 Can we use this as an engineering ticket for implementation? Or would you prefer to create an entirely new ticket?

**Comment by pmclaren19** [comment]
I would prefer a new ticket since this work is being spread out over different sprints and so that we dont have to delete/change ticket info that is no longer relevant to the eng ticket.
