### ISSUE TITLE
Slack/github/google analytics Access ROE

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#845]
As a member of the VSP team, I want clear procedures written for how to give access to slack, github and google analytics for new teams onboarding so that I know the correct way to request permission.

**Comment by andreahewitt-odd** [comment]
But where do we store that approach? Who provides Slack access and how are they triggered to do it?

Patrick, Leah, David Bao can provide Slack access. VSP just needs to give them the list of email addresses.

For GH, we give the list to Jeff H and he gives access once their eQIP is done.

We need to write that up ^

Work with Mikki on where to store it.

**Comment by andreahewitt-odd** [comment]
##Slack

Create a list of email addresses that need to be invited. 

Reach out to Patrick Bateman or Leah Bannon on Slack to request Slack invitations. Provide the person giving access with a list of email addresses and ask them to make a specific channel for that team (ex: by-light-general or vsa-global-ux).

##Github

Make sure all team members have Git Hub accounts and collect their usernames. Find out if each user has started the eQip process or not. 

If users have started the eQip process, send the list of usernames to Nancy Smith and request write access to the department-of-veterans-affairs/va.gov-team repository.

If users have **NOT** started the eQip process, send the list of usernames to Nancy Smith and request read access to the department-of-veterans-affairs/va.gov-team repository. Ask users to tell you when they have started the eQip process so you can request write access. 


##Google Analytics

Make sure every team member has a google account tied to their corporate or va.gov email. 

Put in an issue on the VSP board using the Analytics Access Request Template. Do not include the email addresses in this template so it isn’t visible in the public board. 

Send a slack message to #vsp-analytics with the email addresses that need to be invited and a link to the Github issue.

Please *opt-out of analytics* on your work machines, personal machines (if you are not a veteran yourself using the site for your own applications), and mobile devices. This ensures that we are not collecting your data as a part of Google Analytics stats for va.gov. (Instructions here:  https://www.va.gov/analytics-opt-out.html)

**Comment by andreahewitt-odd** [comment]
Get rid of wording for template in google analytics.

**Comment by andreahewitt-odd** [comment]
Final draft: https://docs.google.com/document/d/1wMFU2XkRURBZ9CE0KC3x9rWiWvK0_yB8wx9SxtADdOw/edit?usp=sharing

@mnorthuis Can you let me know a good place to store this in Git Hub now that we're reorganizing the repo?

**Comment by andreahewitt-odd** [comment]
@joanneesteban @batemapf @leahbannon Can you guys review this and make sure this is how you want access requested since you guys are the ones granting access? https://docs.google.com/document/d/1wMFU2XkRURBZ9CE0KC3x9rWiWvK0_yB8wx9SxtADdOw/edit?usp=sharing

**Comment by batemapf** [comment]
@andreahewitt-odd dropped in some comments and made a few edits to the [Google doc](https://docs.google.com/document/d/1wMFU2XkRURBZ9CE0KC3x9rWiWvK0_yB8wx9SxtADdOw/edit?usp=sharing).

**Comment by andreahewitt-odd** [comment]
Nancy signed off 8/21 in slack

**Comment by mnorthuis** [comment]
@thatmattjohnson can you take a look for repo placement and we can chat?

**Comment by thatmattjohnson** [comment]
@mnorthuis recommend platform/about-vsp/onboarding

**Comment by mnorthuis** [comment]
@andreahewitt-odd/ @thatmattjohnson  - a small change to where to put this doc based on our convo of splitting the "about" and "working with" type documentation. 

Doc can go here:  /platform/working-with-vsp/onboarding
