### ISSUE TITLE
Analysis & UX: Address UX/access problems with "no access to MHV" alert on landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#84518]
### User story

As a Cartography team member, I want to know what is wrong with the unregistered alert ("no MHV access") on the MHV landing page and update the UX design, so that we can fix the issues.

### Notes
- [Mural of sign-in account checks and back-end systems](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717177396025/367057c4a9219404c3b7080e71210082b3c65771?sender=uebde62ceb342c6477fb09406)
- [Huge slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1717185477450519) on subject
- Types of problems that may exist:
  - any problems with the accuracy of the alert content, possibly for specific use cases
  - links hidden that should be available
  - the user data defining each use case where the alert is in error
- Are we hiding too much?
- Are we showing things that should be hidden (eg expandable news alert)?
- NEW FROM DEMO 6/5: review Kat's medallia analysis to see if there are clues in the qual feedback that reflect on this analysis

Possible tasks:
- Get Patrick's review of Mural

## Acceptance criteria

- Documented findings
- Landing page redesigned (in Figma) for integrated version with the "no MHV access" (aka unregistered) alert if needed
- Patrick has vetted design
- Kaitlin has vetted design

**Comment by fmccaf1** [comment]
Based on the mural linked above, the alert text remains correct: "To access My HealtheVet at least one of these descriptions must be true: You've received care at a VA facility or you've applied for VA health care."

The new content around integration though is more than this type of user needs to see. I removed a bunch of new content, including the blue dropdown, and I removed old content too that seems distracting. 

Next step is vetting by Patrick and Kaitlin.

**Comment by fmccaf1** [comment]
<img width="1280" alt="Desktop no access" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/a50001d0-80e8-4667-8606-462d9fc61df6">
![Mobile no access](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/2300fa79-2ce1-4645-8739-82e7ecdf9373)

**Comment by wesrowe** [comment]
@fmccaf1, would you include the designed-but-not-yet-in-prod "welcome" message for this user? I'm thinking yes but not with confidence...

**Comment by fmccaf1** [comment]
With this iteration, I'm thinking no @wesrowe. I'd say, let's make this is simple and straightforward as possible. The less elements the better. But if folks disagree, happy to stand down :)

**Comment by fmccaf1** [comment]
Here are the edited screens w Katelyn and Patrick's feedback

<img width="1280" alt="Desktop no access" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/c6c48761-d753-4bf3-aac5-b96bc2e0533d">
![Mobile no access](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/eff16203-9b5a-4851-b9d7-9eb5a29ae34f)

**Comment by fmccaf1** [comment]
All ACs have been met

![Mobile no access](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/f6ba1f8a-5424-4a2f-acb2-0b08b03a704e)
