### ISSUE TITLE
CT-103: Post-test Content Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#8452]
Update content after usability testing
Distribute to UX Team
Review / Update, if necessary

**Comment by amyknox** [comment]
[https://app.zenhub.com/files/133843125/c36bac04-fdce-4491-b47f-3e967c9619b4/download](https://app.zenhub.com/files/133843125/c36bac04-fdce-4491-b47f-3e967c9619b4/download)

**Comment by amyknox** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/design/content/103-content-doc.md
