### ISSUE TITLE
Add seed user data to test/demo ARP/21-22/21a Pilot Representative functionality in staging and localhost

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#84526]
#### Description

ARP needs Pilot Representative mock data to test associated functionality. Currently, va.gov mock users can be used for this purpose.

#### Acceptance Criteria

- [x] The ARP frontend sign-in can be tested using a mock user who has poa_codes and an ogc_registration_number (`vets.gov.user+1@gmail.com`)
- [x] Similarly, ARP form21a can be tested using a mock user who *does not* have poa_codes and an ogc_registration_number (most basic user possible) (`vets.gov.user+2@gmail.com`)

**Comment by hdbaines** [comment]
Potential for Mustafa or Daruis after they onboard

**Comment by gabezurita** [comment]
@HaroldLee-VA, I combined the issue as requested:
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/84526

**Comment by ddzz** [comment]
Moving to "Done" with follow-up tasks needed to address test coverage and last two bullet points of AC.
