### ISSUE TITLE
Add test users to lower environment OGC data set 

### ISSUE THREAD

**Issue by a6marinos** [department-of-veterans-affairs/va.gov-team#84529]
Need to document test rep users in ARP va.gov-team documentation.
We’ll need this to set up the user accounts we’ll need to validate the below user scenarios in following potential tickets:
    * Add a few reps in OGC data set with email matching primary ID.me/Login.gov test user email
    * Add a few reps in OGC data set with email matching secondary ID.me/Login.gov test user email
    * One with a non-unique email in OGC data set matching ID.me/Login.gov test user email
    * Write thorough instructions and documentation for future folks

**Comment by gabezurita** [comment]
Closing issue as it's getting merged with the below!
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/84526
