### ISSUE TITLE
Analysis: Validate planned "Verify" alert flow on landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#84522]
## Description

Update per 6/14/2024:
Look at 3 alerts and get content and implementation logic approved to implement these in the coming sprint:
* ID.me and Login.gov identity verification alert
* My HealtheVet basic identity verification alert
* **ADDED TO TICKET** - Register with My HealtheVet alert (for new ID.me and Login.gov accounts that have not been paired with the MHV-API).

### User story

As a Cartography team member, I want to ensure that our planned implementation of account-verification alerts provides an accurate UX and doesn't hide things from users unnecessarily, so that we can ensure we implement this flow correctly.

### Notes
- updated content for alerts on GitHub [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/sign-in-alerts.md)
- [Mural of sign-in account checks and back-end systems](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717177396025/367057c4a9219404c3b7080e71210082b3c65771?sender=uebde62ceb342c6477fb09406)
- [Huge slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1717185477450519) on subject
- [Figma of Verify flow](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=450-9421&t=pst2tjSjS9EktJvV-0)
- Types of problems that may exist:
  - any problems with the accuracy of the alert content, possibly for specific use cases
  - links hidden that should be available
  - do we know the user data that should define each step in the alert flow?
- ID-Verification alerts: there are 2 different non-LOA3 alerts: one for MHV credentials and one for LIgov/IDme (but UX around them could be the same)
  - This comes in sequence _before_ the "no MHV access" alert
  - Will need content update, so put "DRAFT" mark or similar on alert itself
- **NEW as of 6/14/2024:** Register with My HealtheVet alert: this will only be relevant for **new** ID.me and Login.gov accounts that have not previously been paired with the MHV-API. Backend logic will need to check for MHVAccountState property before showing this alert to users with those credentials. 

Possible tasks:

- [x] [Update flow in Figma ](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=942-11704&t=OeUGIJ38KWF8MlX9-1)

## Acceptance criteria

- [x] Updated Verify flow figma with latest shared understanding
~- [ ] Updated Mural system flow to reflect truth of user "steps"~ (difficult to convey in this diagram)
- [x] Tickets related to the Verify alert flow (in [this epic](#84932)) are updated and accurate
- [ ] Patrick has vetted analysis and all of the tickets for accuracy

**Comment by jonathanjnelson** [comment]
We are waiting on the content to be finalized by CAIA. Therefore, accomplishing the acceptance criteria listed below seems to be blocked. 

- Tickets related to the Verify alert flow (in this milestone) are updated and accurate
- Patrick has vetted analysis and all of the tickets for accuracy

Am I missing something @sterkenburgsara? CC: @wesrowe

**Comment by wesrowe** [comment]
@jonathanjnelson, per @sterkenburgsara's [slack message](https://agilesix.slack.com/archives/C05PH6V3MJL/p1718305664640669), it looks like content firmed up today just after your comment above.

**Comment by sterkenburgsara** [comment]
Update: stakeholders had questions in [Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1718634350276679?thread_ts=1718392016.608289&cid=C0581MN69TJ) about alert content in the My HealtheVet basic (LOA1) content that suggests shadow ID.me accounts are being created when users log onto VA.gov with an MHV basic account. This is true - sign-in flow is documented[ in this Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707497060514/1b011002bf25fbfe1f1c832c0566296ed86c0bb9?wid=0-1707497159207).

**Comment by jonathanjnelson** [comment]
[Slack thread conversation here ](https://dsva.slack.com/archives/C0581MN69TJ/p1718392016608289)

**Comment by sterkenburgsara** [comment]
Update: scope change. @wesrowe asked us on Friday to include content and OCTO approvals for the 3rd non-verification alert about registering with My HealtheVet. Changing the A/Cs to reflect.

**Comment by sterkenburgsara** [comment]
Update: per this slack thread, Patrick and Danielle Thierry suggested we get the technical situation for my HealtheVet basic users validated by identity folks prior to moving forward with alert implementation. We are unsure if this is a blocker for all alert implementation, or only the one alert (My HealtheVet basic "verify" alert). Question posed by @wesrowe [in this thread ](https://dsva.slack.com/archives/C0581MN69TJ/p1718656444304609?thread_ts=1718392016.608289&cid=C0581MN69TJ)
