### ISSUE TITLE
Upgrade Sentry redis instance

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8453]
During the work to  upgrade Redis for vets-api (department-of-veterans-affairs/va.gov-team#7545), the Sentry redis instance was also discovered to be running the older 3.2 version. To make matters slightly more complicated, it is running on a single node. Both of these should be addressed

- [ ] Upgrade `vagov-util-sentry-ec` to Redis 5.0.x
- [ ] Evaluate moving to at least two nodes like the rest of our infrastructure
- [ ] Double-check requirements from Sentry documentation to ensure we're running this correctly

**Comment by johnpaulashenfelter** [comment]
Likely superceeded by Sentry 10 https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/7064

**Comment by erluti** [comment]
Unnecessary due to Sentry 10 upgrade
