### ISSUE TITLE
Log users out on inactivity (session timeout)

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#84533]
Log ARP users out on inactivity. See [session timeout](https://github.com/department-of-veterans-affairs/vets-website/blob/374bd5cc7221d39121c91139e5eac79fc51c8afb/src/platform/user/authentication/components/SessionTimeoutModal.jsx#L1-L160) example.

## AC
- [ ] When an ARP user is inactive for X amount of time, they are logged out automatically

**Comment by kristen101606** [comment]
Related to this ticket: [Add Session Inactivity Alert to ARP #91636](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/91636)
