### ISSUE TITLE
10-7959f-2: remove phone number validation

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84547]
As a user, I want to be able to enter my international or domestic phone number in the field so that I can get contacted if there are any issues with my registration.

url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/contact-info
https://design.va.gov/components/telephone
- user should not be limited to 10 digits upon entry
- otherwise functionality/display remains the same
- update error message accordingly
- phone number should be set to _required_

Acceptance criteria:

- Given the user is filling out the FMP registration form online,
- When they go to enter in their phone number on the contact information page
- Then they should be able to enter either an international or domestic phone number without being restricted by the number of digits

**Comment by reiting** [comment]
Created PR and is in team review now. 
Required:
<img width="702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfed43b1039452560c292830046c3666fe2a1873/Screenshot%202024-07-10%20at%2010.33.58%E2%80%AFAM.png" alt="Screenshot 2024-07-10 at 10.33.58 AM.png" />
Contact info page:
<img width="621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--255fcf75bc2da47fc456f883084853bf37f58bd2/Screenshot%202024-07-10%20at%2010.35.25%E2%80%AFAM.png" alt="Screenshot 2024-07-10 at 10.35.25 AM.png" />
Showing long phone number accepted on review page:
<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8614d83445fd7b0a5e9be42be8f8a62fc5eed80/Screenshot%202024-07-10%20at%2010.35.33%E2%80%AFAM.png" alt="Screenshot 2024-07-10 at 10.35.33 AM.png" />

**Comment by reiting** [comment]
Now in Platform review.

**Comment by reiting** [comment]
This was approved and merged. Should be in staging in a few hours.

**Comment by marywang2** [comment]
I have changes for FMP reg - we'll need to make the same changes for this one - should we put in blocked for now @reiting?

**Comment by reiting** [comment]
@marywang2 do we know what the changes are yet? If not, yeah I'd move it to blocked.

**Comment by reiting** [comment]
@marywang2 do you want me to fix this on this ticket?I see that there's another ticket for it, so just wasn't sure if you wanted it here or there.

**Comment by marywang2** [comment]
We can fix on this one and the FMP registration changes would be on the other @reiting, thanks!

**Comment by reiting** [comment]
Okay, but the international phone component is a shared file for both f1 and f2. So fixing it fixes it across both forms (made it shared because there is no need to redo it when it can be used by both). This PR is in platform review. <img width="580" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd90a0b897db78055b27d75f49caa79096d29b21/Screenshot%202024-07-12%20at%202.35.04%E2%80%AFPM.png" alt="Screenshot 2024-07-12 at 2.35.04 PM.png" />

**Comment by reiting** [comment]
This PR was approved and merged. Should be available in staging for review in a few hours. @marywang2
