### ISSUE TITLE
Create Instructions mockups for Pre-check-in

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#84542]
## Task Description
Complete mockups for prep instructions that include medication review

## Notes and References
- [Project folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/projects/2024-05-medication-language-update)

## Acceptance Criteria
- [x] Mockups are complete
- [x] CIE team has approved mockups

## Deliverables
- [User flow](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=545-5197&t=yWaeOEybo9LZgK1O-4)
- [PCI mockups](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=i7ZsGuqPq3w40iGu-4)
- [Final language](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZ1cVb_w1MZEod5kMVhU6dwBrMJD5C56RAwbfSerVCgqhg?e=tyTF62) (VA Network)

**Comment by loripusey** [comment]
I thought this work had already been completed; the CIE team has a ticket to copy the design to our Figma files; do we need to wait for this ticket to be completed before we begin that work?
cc: @benbrasso-agile6 @cgednalske @zach-park @anita-halici

**Comment by outerpress** [comment]
@loripusey the intent of this one is to provide final mockups for CIE once stakeholders have approved the language (see #85061)

**Comment by outerpress** [comment]
@zach-park @loripusey I updated the user flow and mockups and linked the final language (under deliverables). Let me know if you need anything else!
