### ISSUE TITLE
TeamSite document edits

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#84575]
Jill Adams said,
Hi @laucon - I found one place the Allowlist link is still incorrect in the docs: in this paragraph:

There are an unknown number of TeamSite templates that drive the <head> content on TeamSite pages and there are several pages that receive the above markup that should not show the VA.gov header. The proxy rewrite application uses a [allowlist](https://github.com/department-of-veterans-affairs/vets-website/blob/b770f380270722228563e56629af440c64342157/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json) to drive the activation of the header content. Example allowlist entry:

That URL should be: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json

Otherwise, looks good! Thank you for getting this handled.

So I'll fix this according to these instructions.

Acceptance Criteria:
- [x] Document is edited according to the instructions above
- [x] Document is deployed

**Comment by laucon** [comment]
This is done. :)

**Comment by jknipes** [comment]
Work is completed, moving to _Done_
