### ISSUE TITLE
10-10d, 10-7959c: Verify save in progress 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#84576]
- 10-10D:
  - Verify save in progress (should be already set up)
- 10-7959c:
  - Verify save in progress (should be already set up)

**Comment by michaelclement** [comment]
10-10d needs a couple fixes [in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30170) but when that's merged it'll be verified

**Comment by michaelclement** [comment]
Other than the missing sign-in button on the intro page of OHI ([see this ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/85390)), this task is complete for both of these forms and ready for review.
@marywang2 @baltes

**Comment by marywang2** [comment]
Thanks Michael! Verified for OHI. @baltes would you please verify for 10-10d. Thank you!
