### ISSUE TITLE
10-7959a | Schedule interviews

### ISSUE THREAD

**Issue by syd-hoeper** [department-of-veterans-affairs/va.gov-team#84596]
Schedule interviews for CHAMPVA Claims

**Comment by jamiefiore** [comment]
Messaged the following people on Teams with time slots. We are waiting to hear back. 

Erick Maes (Processing Units, and Review and Resolution)
Johnson, Melissa-claims processer, supervisor and now she's a program analyst.
Melvin Brown-Program Analyst, has been with CHAMPVA for like 30 years.
Vanna Summers-she's a processor and a supervisor.

**Comment by jamiefiore** [comment]
Update: Vana, Erick and Melvin are scheduled.

**Comment by jamiefiore** [comment]
All of the interviews have been scheduled. Here's is the link to [the Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718049182430/1421fe86cf6cb3c74d17d0d422b5ae0a2ab66621?sender=u10700c583aaa99f809c88675) for notetaking

@marywang2 I'm closing this ticket.
