### ISSUE TITLE
Audit be-tools Grafana permissions

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8459]
Everyone on be-tools needs at least `Editor` if not `Admin` permission

- [ ] Bill
- [x] Keifer
- [x] Johnny
- [x] JP
- [x] Lindsey
- [x] Philip

**Comment by omgitsbillryan** [comment]
I'm an admin and everyone else on the list is an Editor.

I _think_ that's good enough, let me know if it isn't.
