### ISSUE TITLE
Add missing Redis datasources to Grafana Redis dashboard

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#8460]
Our active redis environments are not all included in the prometheus environments:

```
Active redis environments
dsva-vetsgov-prod
dsva-vetsgov-dev
dsva-vagov-sandbox
dsva-vagov-staging
vagov-util-sentry-ec

Future migration
dsva-vagov-dev
dsva-vagov-prod

Unused/Scheduled to delete
dsva-vetsgov-stag
```

while the screenshot shows what is available in the dashboard![Redis - Grafana 2020-04-27 09-59-49.png](https://images.zenhubusercontent.com/5453b9977c6ccc6277a5d25b/b8d5208d-5ee1-4117-98a1-0e7591a17b91)

**Comment by johnpaulashenfelter** [comment]
The vetsgov-util is also simply broken -- maybe it should connect to the sentry utility redis instance?

**Comment by omgitsbillryan** [comment]
Here's the new complete list of envs
![image](https://user-images.githubusercontent.com/3077884/82916577-38546600-9f40-11ea-8cd7-195eebf0063c.png)
