### ISSUE TITLE
Extract module generator

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#8461]
Discovered while attempting to remove `dry-types` and `dry-struct` from codebase in this PR https://github.com/department-of-veterans-affairs/vets-api/pull/4132

This is the module generator:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/commands/va/va_command.rb

Architecturally it makes sense to be a separate gem.  Then the boiler plate code it generates can be reevaluated for wether dry-types should be used.

**Comment by erluti** [comment]
@alexpappasoddball I think we should delete the module generator from the codebase because (i believe) it's not in use.  Then the PR this ticket references could be merged and we'll get two code cleanup wins.  And then the concept of a module generator is something that we would revisit with toolkit work.

**Comment by alexpappasoddball** [comment]
@erluti @LindseySaari here is an oldie and a goodie.  Anything relevant to the current work in this or can this be reused or closed?

**Comment by erluti** [comment]
I want to resurrect [this PR](department-of-veterans-affairs/vets-api#4132) at some point, but generally i think this can be closed

**Comment by erluti** [comment]
Generator has been rebuilt for modern goals
see here https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17215
