### ISSUE TITLE
PW intake: Setting up translated components for PCAFC static page

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#84625]
### Status
**[2024-07-09]** Unblocked, ready for work.
**[2024-06-24]** Blocked by [#86962](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962)
**[2024-06-11]** This ticket should be done after #83558  is deployed on 6/18.

### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [X] Implementation of Translation widgets
- [ ] Something else

### Describe your request

We will be redirecting https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers-esp/ to a new URL as part of https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/

The new page will need:
1. Language toggle
2. Left nav translation
3. Spanish breadcrumb

### Time constraints / launch deadlines

The redirect ticket is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/83558

The new Drupal spanish page has already been cloned at the new URL. Not sure if you need it!: https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp

### Your OCTODE product owner

@mnorthuis

## ACs

- [x] Spanish translation toggles appear on https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/
- [x] Translated left sidenav appears correctly in Spanish
- [x] Breadcrumbs appear correctly in Spanish
- [ ] CAIA (Laura Willwerth) and IA (Kristin ) have signed off in a Review Instance before merge

**Comment by laurwill** [comment]
Hi @jilladams @FranECross , 

The new [English](https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/) and [Spanish](https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/) PCAFC pages are now live, and the redirects from the previous URLs are working. 

Left nav work is TBD in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962), so that part of this translation ticket may need to wait, but I think you could go ahead with the toggle and the translated breadcrumb?

**Comment by jilladams** [comment]
Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962

**Comment by jilladams** [comment]
1. Language toggle -- an existing toggle is on the old page, so we can update that to be on the new page. 
2. Left nav translation -- This is content that CAIA will need to be added to the new menu (Family and Caregiver Benefits) which should appear in production today.
3. Spanish breadcrumb -- The breadcrumb is derived from the menu, so this will also happen after CAIA adds the Spanish content to the menu.

**Comment by kristinoletmuskat** [comment]
@jilladams by Menu do you mean the left nav? Or what is that referring to?

**Comment by jilladams** [comment]
Yes, sorry -- Drupal menus are the technical feature in Drupal that enables the left nav. So: 
* Yesterday the menu was created in Drupal: https://prod.cms.va.gov/admin/structure/menu/manage/family-and-caregiver-benefits
* in https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962 we are updating code so the menu / left nav will appear correctly in the front-end
* CAIA will need to enter the links / content into that menu, which we let Laura know here: https://dsva.slack.com/archives/C01K37HRUAH/p1719433014013829?thread_ts=1719332572.216609&cid=C01K37HRUAH

So the work in this ticket will really just be: 
1. Front-end updates to make the translation toggles appear on the new page.
2. Verifying that the SPanish breadcrumb works as expected and troubleshooting/fixing if not.

**Comment by kristinoletmuskat** [comment]
Hey @jilladams, I think we're ready to publish the left nav -- do we know when we might be able to pull this toggle work in?

**Comment by jilladams** [comment]
Yep - this is officially ready for work. Fran and I need to check with FE folks for who might be able to pick it up.

**Comment by FranECross** [comment]
Notified Randi and Chris via [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1720557886817669) that this ticket is unblocked.

**Comment by eselkin** [comment]
So, the PR merged which adds the lang tag to the page and the toggle as well (or maybe the toggle adds the lang to the page). Either way, the toggle works to switch the page and is in Prod today.

**Comment by kristinoletmuskat** [comment]
Thank you @eselkin! One Q (I am new to toggles so not sure what should be happening). 

In the english version, the benefit application is embedded under PCAFC in the left nav. In the spanish version, the application is not showing up in the left nav. 

Spanish-reading users can still get to the application through the action link on the PCAFC page, but should the 'Apply now' link in left nav also appear for spanish?
![Screenshot 2024-07-11 at 3 30 22 PM](https://github.com/user-attachments/assets/2a2f53b4-1ea1-4e2f-b87e-1b23bb45c070)
![Screenshot 2024-07-11 at 3 30 28 PM](https://github.com/user-attachments/assets/4f1efcb1-cefb-41f9-b54f-93a601ed3ec7)

**Comment by eselkin** [comment]
That may be a drupal question. Let me see.

**Comment by eselkin** [comment]
@randimays or @dsasser I'm not aware how the left nav picks up things like the apply link above. I don't see it in the drupal page and don't see anything specific to it in the templates.

**Comment by eselkin** [comment]
Ok, I found where it happens: https://prod.cms.va.gov/admin/structure/menu/manage/family-and-caregiver-benefits
There needs to be a submenu like for [Apply now](https://prod.cms.va.gov/admin/structure/menu/item/12922/edit?destination=/admin/structure/menu/manage/family-and-caregiver-benefits) but for filling out the form in Spanish. @kristinoletmuskat Do you want that link to say "Apply now" but in Spanish, or keep Apply now in English as the link title.

**Comment by eselkin** [comment]
I made it say "Apply now" (may not make it into a content release for today) for now and we can change the text when we confer on good text. I couldn't decide on whether using an imperative form as it is in English is appropriate in Spanish.

**Comment by laurwill** [comment]
Tagging in @moviedosoco , our team's bilingual copyeditor. Victoria, I know we recently discussed that links from Spanish pages to an English-only form should include "(en ingles)." So I think the questions are:
- How would we translate "Apply now" to go in this space in the left nav under the Spanish PCAFC page?
<img width="442" alt="image" src="https://github.com/user-attachments/assets/610ddc5a-0d90-410a-b870-91ffa61f9680">

- Should we include "(en ingles)" in that left nav label? 
- Any other concerns with placing a link to an English form under a Spanish page in the left navigation?

**Comment by moviedosoco** [comment]
@laurwill 

- The Spanish translation for "Apply now" is "**Solicite ahora**" 
- It's not necessary to include "(en inglés)" in that left navigation bar if that link will take you to a Spanish page. BUT, if that link redirects you to an English page or form (because it hasn't been translated yet), I think it is worth to include it. Once that page is translated, you can remove it from the left nav bar.  
- I don't think there's any other concerns since by including "(en inglés)" you're making it clear that is an English form under a Spanish page. 

I hope I've helped you!

**Comment by laurwill** [comment]
Thanks so much for the quick answer @moviedosoco ! The link goes directly to the online form which is in English only right now.

So @eselkin , does this work for a left nav label: **Solicite ahora (en inglés)**

**Comment by eselkin** [comment]
Changed. Thank you! This will probably go out Monday unless there's a content release before then.

**Comment by eselkin** [comment]
It went out yesterday it seems. So it's live on va.gov now.

**Comment by jilladams** [comment]
Verified in Prod, closing. CAIA: feel free to reopen if you have concerns. 

https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/

![Screenshot 2024-07-19 at 1 03 53 PM](https://github.com/user-attachments/assets/1fd0cf77-7faa-4287-8f5f-d8ad1cf1b569)

https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/
![Screenshot 2024-07-19 at 1 03 58 PM](https://github.com/user-attachments/assets/0b964709-01ec-4161-8c62-948940f3bdd3)
