### ISSUE TITLE
The 'How to join' section should not display for past phone appointments

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#84634]
## Summary
When displaying the appointment details for a past phone appointment, the 'How to join' section is displayed. This section should not be displayed.

## Specs
- Device: N/A
- Browser: Chrome
- Environment: Development/Localhost

## Steps to Reproduce
**Test User:** 

1. Create past phone appointment
2. View appointment details for past phone appointment

### Actual Result
When displaying the appointment details for a past phone appointment, the 'How to join' section is displayed.

<details>

![localhost_3001_my-health_appointments_](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3587066/f04a9389-f653-4d5c-8b68-ad6c44bec1ea)

</details>

### Desired Result
The 'How to join' section should not be displayed

<details>

![localhost_3001_my-health_appointments_past_past-phone-appointment](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3587066/c7a47fa7-92bb-494f-ae13-fda07baf1c6b)

</details>

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment]
Validated in staging. No issues to report. Closing it out. 
<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9dba5ee0ef3a1765451bedd4a16423423e98d76/Screenshot%202024-06-06%20at%2010.43.09%E2%80%AFAM.png" alt="Screenshot 2024-06-06 at 10.43.09 AM.png" />
