### ISSUE TITLE
Remove the secondary navigation from the scheduling flow (except Type of Care page)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#84637]
## Description
Remove the secondary navigation from the scheduling flow except for the Type of Care page. 

---

## Acceptance Criteria
Background: the `mhv_secondary_navigation_enabled` toggle is on - owned by MHV Cartography team

- [x] Given the user is on the Appointments homepage 
       When the user clicks on the `Start Scheduling` link
       Then the user will see the secondary navigation on the Type of Care page 
       And page design matches the design spec

- [x] Remove the secondary navigation from the scheduling flow pages except for the Type of Care. Scheduling flow for direct booking at a VA site, VA requests and Community Care requests. 

     **Scheduling flow pages:**
     - [x] Direct scheduling: Choose a type of eye care page
     - [x] Direct scheduling: Choose a type of audiology care page
     - [x] Direct scheduling: Choose a type of sleep care page
     - [x] Direct scheduling and VA request: Choose a location page
     - [x] Direct scheduling: Choose a clinic page
     - [x] Direct scheduling: Choose a preferred date (PID) page
     - [x] Direct scheduling: Choose a date and time page
     - [x] Direct scheduling: Reason for appointment page
     - [x] Direct scheduling: Contact Information page
     - [x] Direct scheduling: Review and submit page
     - [x] VA request scheduling: Preferred date page
     - [x] VA request scheduling: Preferred modality page
     - [x] VA request scheduling: Reason for appointment page
     - [x] VA request scheduling: Contact information page
     - [x] VA request scheduling: Review and submit page
     - [x] Cerner re-direct page: 
     - [x] Community care scheduling: Nearest city page
     - [x] Community care scheduling: Choose a provider page 
     - [x] Community care scheduling: Choose a language page
     - [x] Community care scheduling: Preferred date page 
     - [x] Community care scheduling: Reason for appointment page
     - [x] Community care scheduling: Contact information page 
     - [x] Community care scheduling: Review and submit page

### Design Assets
[Design Specs]()

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated in staging (judy.morrison@id.me). UX will do a second validation. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ea29c6032a5fdbc4a3d9a7aa6ff1d0c6bd639a3/Screen%20Recording%202024-06-24%20at%201.45.25%E2%80%AFPM.mov)

**Comment by outerpress** [comment]
@ldelacosta @vbahinwillit these all look good!

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
