### ISSUE TITLE
[Spike] Identify and verify unused files in the VAOS application

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#84657]
## Background/Request
During the Awesome Font icon conversion, there are several files that doesn't seem be to utilized in the latest version of vaos app. While the happy path was employed to separate the used files, the unused files may be utilized in outlier situations. 

Below are files that require verification as un-used:

- src/applications/vaos/new-appointment/components/ConfirmationPage/index.jsx 
~~- src/applications/vaos/new-appointment/components/ConfirmationPage/ConfirmationDirectScheduleInfoV2.jsx~~
- src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentListItemGroup.jsx
- src/applications/vaos/appointment-list/components/AppointmentsPage/RequestListItem.jsx 
- src/applications/vaos/appointment-list/components/RequestedAppointmentsList.jsx

### Goal
Identify and verify unused files in the VAOS application. Some files may be abandoned during prototyping or obsolete because of deleted feature flag association. 

### Requirements to Consider

The some files may be used in fringe situations, test those outlier paths.

---

## Tasks
- Answer the following questions:
  - Q. Are the files listed above verified as un-used?
  - Q. Are there other un-used, orphaned files?

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/84657?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ryanshaw** [comment]
#### [`src/applications/vaos/new-appointment/components/ConfirmationPage/index.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/new-appointment/components/ConfirmationPage/index.jsx)

This file is currently serving as a wrapper for the [`ConfirmationDirectScheduleInfoV2.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/new-appointment/components/ConfirmationPage/ConfirmationDirectScheduleInfoV2.jsx) component and **cannot** be removed without some simple refactoring.

My suggestion would be to consolidate this within a single `ConfirmationPage` component.

--- 
#### [`src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentListItemGroup.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/appointment-list/components/AppointmentsPage/AppointmentListItemGroup.jsx)

This file is not imported in any other component or test, it can be removed. After deletion locally, all unit tests and e2e tests passed. A search of the codebase revealed that it was not included in any other file.

---
#### [`src/applications/vaos/appointment-list/components/AppointmentsPage/RequestListItem.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/appointment-list/components/AppointmentsPage/RequestListItem.jsx)

This file is not imported in any other component or test, it can be removed. After deletion locally, all unit tests and e2e tests passed. A search of the codebase revealed that it was not included in any other file.

---
#### [`src/applications/vaos/appointment-list/components/RequestedAppointmentsList.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js)

While this component is not used, there are some existing unit tests that should be updated to use the more current `RequestedAppointmentsListGroup` component before this component can be removed.

Test assertions that should be up for consideration to update and potentially move are:

- [should show va request](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js#L36)
- [should show cc request](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js#L118)
- [should show error message when request fails](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js#L182)
- [should display request sorted by create date in descending order](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js#L197)
- [should display cc request and provider facility name if available](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js#L304)
- [should not show resolved requests](https://github.com/department-of-veterans-affairs/vets-website/blob/d0e1b6e06f68acfdab44d7e734de33517e48820c/src/applications/vaos/tests/appointment-list/components/RequestedAppointmentsList.unit.spec.js#L345)

---
#### `vaOnlineSchedulingBreadcrumbUrlUpdate` feature flag and code removal

We no longer use this feature flag, however it is present in ~44 files. Removing this could be a large effort, but in the long run will remove a lot of unused code. There are places where test coverage can be removed and also places where test coverage needs to be added -- where we are only testing cod that is not used in the application.

My suggestion would be to make this a single large issue with many smaller pull requests or create issues by upper level directories in the application (i.e. remove from `new-appointment/`, remove from `appointment_list/`, etc.)

I can make new tech debt issues for the files that can be easily removed above as well as the feature flag removal.

**Comment by JunTaoLuo** [comment]
Other than the files listed in the original description, are there any files and components that are not used in the VAOS app? I recall you mentioned that there are some tools that can help identify them.

**Comment by ryanshaw** [comment]
@JunTaoLuo I've updated my comments, there were a few more things that we should consider removing. I didn't note it in the ticket, but I did run another static analysis of the codebase that looked at functions and uncalled code in general (versus module imports) and there is a moderate to small amount of that.

cc: @simiadebowale

**Comment by ryanshaw** [comment]
@simiadebowale I wanted to call out this bit, as you worked on it and I don't have context:

> [src/applications/vaos/components/CernerTransitionAlert.jsx](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84657)
> The only use of this component in the codebase is commented out and located here: [vets-website/src/applications/vaos/appointment-list/components/AppointmentsPage/index.jsx at 42e16f044bc5f4e9484e4d1569b85c954ae35a1c · department-of-veterans-affairs/vets-website · GitHub](https://github.com/department-of-veterans-affairs/vets-website/blob/42e16f044bc5f4e9484e4d1569b85c954ae35a1c/src/applications/vaos/appointment-list/components/AppointmentsPage/index.jsx#L28)
> 
> If we are no longer needing this particular piece of functionality we should delete the file and remove the comments. It is related to this PR: [#78946: Remove Code to Prevent Lovell Appointment booking (#28920) · department-of-veterans-affairs/vets-website@0cbab09 · GitHub](https://github.com/department-of-veterans-affairs/vets-website/commit/0cbab09bd49f59b5ebc3ea54530e6f76747ed143)

**Comment by JunTaoLuo** [comment]
Thanks @ryanshaw for the detailed investigation! It now covers all the files I noticed when I manually looked for unused components so I'm glad the static analysis tool worked well. Looking forward to deleting all this dead code 😄 .

**Comment by ldelacosta** [comment]
Team has identified the work that is needed to clean up the unused files in the Appointments tool.

#92985
#92986
#92987
#92988
#92990
#92991
#92992
#92993
#92994
#93064

No further analysis needed. Closing out the ticket.
