### ISSUE TITLE
Adding Brenda Cudone to DSVA Slack

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#84661]
# Description

Please re-activate Brenda Cudone (brenda.cudone@adhocteam.us) as a full member. She has returned to VA as a project manager on the Appointments project and needs access to Slack for communicating with team members and other teams across VA.gov.

Here is a link to her [profile](https://dsva.slack.com/team/U03ALNF74LR).

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by laurenernest** [comment]
@KevinMHoffmanUSDS @LEHigley Hi! Would it be possible to get her access by this Thursday, 6/13?

**Comment by laurenernest** [comment]
Cross-linking [post](https://dsva.slack.com/archives/C01S729LX6X/p1718296880802299) in Slack for workspace admin help

**Comment by LEHigley** [comment]
reactivated

**Comment by anita-halici** [comment]
hi @LEHigley - @Brenda still doesn't have the access to slack. She hasn't received the auth code. Please advise.

**Comment by anita-halici** [comment]
Brenda was able to get the code but once authenticated she sees this 
<img width="427" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/132477250/11aad0a9-9202-446f-aac3-ebf42f0226fe">

@LEHigley 
@KevinMHoffmanUSDS

**Comment by Bren22va** [comment]
Slack is asking me for an **authentication code from a 2fa**. I cannot set up a 2fa with Slack without being signed into the account, and then I would need to be able to access the 2fa settings (which only admins and owners can do). I don't think this is how the account was set up in the past. Could someone please verify the 2fa requirement is disabled on my account so I can sign in? Slack offers this instruction:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/101590927/754424f3-cb8b-4225-8cb6-529da27aa2c7)
Oddly, other DSVA users can see me in Slack, even though I'm not able to access the workspace myself. 
@LEHigley
@KevinMHoffmanUSDS
