### ISSUE TITLE
Update link for prosthetic socks when new unauth medical supplies page launches

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#84667]
## Description
CAIA created a new Drupal page for medical supplies that combines the previous 3 pages (CPAP supplies, hearing aid batteries, and prosthetic socks). In theory, it would scale to support information for re-ordering any type of medical supply. 

Now the URL on our page for "prosthetic socks" needs to be updated to point to this new destination. Link text will also need to be updated to match the H1 of the destination page.

**Old link text:** `Order prosthetic socks`
**New link text:** `Learn how to order other medical supplies`
**New destination:** https://www.va.gov/health-care/order-medical-supplies/

### User story

As a Cartography team member, I want to update the links on the My HealtheVet home page to match the page destinations they link to, and avoid sending users to broken or outdate URLs. 

As a Veteran, I want to be directed to the most updated pages about medical supplies, so that I can manage my healthcare based on current information. I also want the destination of any link that I click to match where it said that it would take me.

### Notes
- Unsure of timeline for medical supply re-order page launching, but this is related to moving the supply re-ordering form under `/my-health` and adding a sign-in widget to this new unauth page #79823
- Important: the new Drupal page will have to be published _before_ the URL on our landing page can be updated (so that the URL will resolve)
- UPDATE: new page launched late June 2024, and redirects have been put in place from the previous 3 pages to this new one. 

Possible tasks:
- [x] Verify the new medical supplies page is deployed and available to all users.
- [x] Update URL destination and link text on landing page for the current link about prosthetic socks to now point to the broader page about medical supplies.
- [x] Have CAIA review link text update if necessary

## Acceptance criteria
- Update URL destination and link text on landing page for the current link about prosthetic socks to now point to the broader page about medical supplies.
- QA review
- A11y review

**Comment by sterkenburgsara** [comment]
**Update**: new link text approved by Laura W. in [this Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1721237852815759). Ticket has been updated to reflect the desired link text & destination. Devs can proceed with implementation

New link text: **Learn how to order other medical supplies**
New URL: `va.gov/health-care/order-medical-supplies/`

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the link text and the destination has been updated to match what is in the description.

<img width="1233" alt="Screenshot 2024-07-26 at 1 59 34 PM" src="https://github.com/user-attachments/assets/7f929d71-4889-4cdf-8493-2bc9c1374c59">
