### ISSUE TITLE
[Support] Implement Google Analytics for Disability Calculator

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#847]
## User Story
As a product owner of unauthenticated experiences, I want to understand how users are interacting with the disability calculator located at https://staging.va.gov/disability/about-disability-ratings-beta/.

This can include measuring the number of additional rows added (above and beyond the two rows present) and the ratings entered. 

## Resources
- Discussion with product owners is also listed on https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19247
- [Product Launch ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19144) 

## Goal
- Understand how many veterans are using the new disability calculator as opposed to the previous manual table [here](https://www.benefits.va.gov/compensation/rates-index.asp)

## Acceptance Criteria
- [ ] Submission event `disability-calculator--submission-successful` added to form
- [ ] Track clicks of 'Calculate' separate from current form submission paradigm
- [ ] With each 'Calculate' click, record the number of rating fields used
- [ ] Understand the clicks of each ratings accordion here [here](https://vagov-content-pr-268.herokuapp.com/disability/about-disability-ratings/#combined)--> this accordion will eventually live on same page as calculator
- [ ] Track the PDF downloads of the full manual table --> middle of screen [here](https://vagov-content-pr-268.herokuapp.com/disability/about-disability-ratings/#combined)

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonwehausen** [comment]
Hi @nedierecel , 

As it stands, I was able to quickly test / simulate the dataLayer we requested will enable tag functionality immediately. 

![image](https://user-images.githubusercontent.com/48527022/62713446-bef88080-b9ca-11e9-9e67-9ffb72dd761e.png)

We will see what other measurement is necessary, but if we are cool with sticking to our existing paradigm, this will work immediately when the DL is deployed.

**Comment by joanneesteban** [comment]
@Karak888 Do you know who we can contact about this while @jenniferlee-dsva is out?

**Comment by Karak888** [comment]
hi @joanneesteban sorry for delay was out of the office most of last week.  I believe @jenniferlee-dsva gets back tomorrow, and she really has been leading this, but we'll follow up with you. thanks

**Comment by jonwehausen** [comment]
@nedierecel Acceptance Criteria was updated according to conversation with @jenniferlee-dsva 

The goal is to have the accordion manual table [here](https://vagov-content-pr-268.herokuapp.com/disability/about-disability-ratings/#combined) merged on the same page as the disability calculator. 

@nedierecel I have started this functionality, changes are reflected within the Story 847 container.

**Comment by jonwehausen** [comment]
@nedierecel When the dataLayer is in place, this user story should be ready for QA. 

@ncksllvn says we should have the dataLayer requests in place by end of the week at the latest.

**Comment by nedierecel** [comment]
@jonwehausen These are the analytics changes to make in GTM:

1. Extra According Event could be removed: When clicking on the accordion expand or collapse on [Disability hub](https://staging.va.gov/disability/), we could rely on the existing Navigation event. 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/4cac9cc4-3910-474d-a5a3-5e3933143862)

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/85d1fa47-8cdf-4708-b233-aebd27a6ff24)

2. Custom Dimension 52 - It looks like this was intended to be the ratings percentage on the calculator, but it is set on the `Accordion Event` to pull in Click Text.

**Comment by jonwehausen** [comment]
Hi @nedierecel ,

Thanks for managing and testing this in my absence. 

For the disability calculator widget: 
1) Custom metric 11 is allocated to capture the number of fields used when calculate is clicked
2) I left Custom Dimension 51 there inadvertently, this can be marked as unused for re-purposing in the future. 


After reviewing and assuming we don't intend to capture the text label **anytime** a "Navigation Click" event occurs, and want to record only for accordion clicks...I think we should move forward with the following changes:

1) Use the Accordion Event for all accordion interactions
2) Allow accordion Click Texts to flow to custom dimension 52...which we can rename to be "Accordion Text Label" 
3) Do an exception on the "Navigation Click" event for Accordion Event Occurred. _I've staged this in the disability calculator workspace_

Let me know your thoughts.

**Comment by nedierecel** [comment]
@jonwehausen 

#1 and #3 - Sure - let's document this and try it for this approach. 
#2 - I'm leaning toward prioritizing the custom dimensions for more user, session, or other hit-level traits that are related to veteran-facing tools vs. Click Text. Though we still have 150 custom dimensions left, internal users are accustomed to seeing the Click Text pull through in the Event Action.

**Comment by jonwehausen** [comment]
@nedierecel With the accordion implementation being global, we may want to do a little extra QA. 

[Story 847 - Disability Calculator](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/657) container reflects the most recent changes:
- Added {{Click Text}} into the expand and collapse entries for Navigation Action Lookup
- Abandoned the Accordion Event, will be tracked within Navigation Click tag
- Marked Custom Dimensions 51 and 52 as Unused (no longer needed). 
- Renamed custom metric 11 as Disability Calculator Rows 
- Made changes in both non-prod and prod properties. 

Have submitted this container for approval.

**Comment by nedierecel** [comment]
@jonwehausen Good reminder to do a little more QA. For the disability calculator itself, these changes appear correctly.

_Disability Calculator_:
- {{Click Text}} looks correct
- Correct approach that I don't see CDs 51 and 52 set.
- metric11 is working correctly

_Global QA - Navigation Accordion + Collapse_: 
I met with the Andy and Jeff leading a new beta of VAMC that you can see here on Prod for Pittsburgh - https://www.va.gov/pittsburgh-health-care/health-services/

I see the nav-accordion events working in these locations:
- Left Rail - https://www.va.gov/pittsburgh-health-care/
- Main Content (See Primary Care section) - https://www.va.gov/pittsburgh-health-care/health-services/
- Right Rail - https://staging.va.gov/disability/

**Comment by jonwehausen** [comment]
Thanks for your feedback. Published and closed.
