### ISSUE TITLE
Add Cancel Request button the Request Details page for Video and Phone requests 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#84707]
## Description
The Cancel request button is not appearing on the request details page for video and phone appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

User: cecil.morgan@id.me

- [ ] Given when the user submits a request for an appointment for Video or Phone
        When the user is on the confirmation request details page
        Then the user should see a `Cancel request` button on the page
        And page design matches the [design spec](https://www.figma.com/design/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?node-id=2266-79782&t=5Ka0DppBzOoPmjPg-0)

- [x] Given when the user is on the Pending list page
        When the user clicks on the Details for the request for Video or Phone appointments
        Then the user should see a `Cancel request` button on the page
        And page design matches the [design spec](https://www.figma.com/design/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?node-id=2266-79782&t=5Ka0DppBzOoPmjPg-0)

Issue: 
<img width="530" alt="Screenshot 2024-06-04 at 6 17 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/8f928318-6d1b-4139-b213-1e82d30f81b2">
<img width="523" alt="Screenshot 2024-06-04 at 6 18 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/c3338553-9b80-4053-8b9c-949a00ba0996">

### Design Assets
[Design spec](https://www.figma.com/design/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?node-id=2266-79782&t=5Ka0DppBzOoPmjPg-0)

**Comment by Cieramaddox** [comment]
@ldelacosta This ticket has been validated!

**Comment by ldelacosta** [comment]
Validated the changes in staging. No issues to report. Closing the ticket. 

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb780019ca583302bfb9ccb6c8fc072c8cc22741/Screenshot%202024-06-11%20at%2011.52.41%E2%80%AFAM.png" alt="Screenshot 2024-06-11 at 11.52.41 AM.png" />

<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fdcf8ad74cba0c492094988f0aadd984ec08223/Screenshot%202024-06-11%20at%2011.53.02%E2%80%AFAM.png" alt="Screenshot 2024-06-11 at 11.53.02 AM.png" />

<img width="724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzVUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc3f39dc79a589f31974ce264c57539558910ed6/Screenshot%202024-06-11%20at%2012.35.28%E2%80%AFPM.png" alt="Screenshot 2024-06-11 at 12.35.28 PM.png" />
