### ISSUE TITLE
Fix content on system error

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#84705]
## Summary
Language is wrong on a system error. Refers to "New VA Online scheduling tool" which isn't new, and is not called that externally anymore.

## Specs
- Device: Mac OS
- Browser: Chrome

## Steps to Reproduce
**Test User:** Any

This came up when staging was down so I'm not sure how to reproduce but this was the error on the pending appointments page:

<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG8zQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f6591d17baa1832aab933f9c815ffee9415da73/Screenshot%202024-06-04%20at%2010.39.30%E2%80%AFAM.png" alt="Screenshot 2024-06-04 at 10.39.30 AM.png" />

### Actual Result
Heading reads "We're sorry, the new VA online scheduling application isn't available right now."

### Desired Result

Heading should read "We're sorry, the appointments tool isn't available right now."

## Definition of Done
- [x] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by outerpress** [comment]
@vbahinwillit  do you know what triggers this error? Fwiw I found it accidentally so can confirm it's fixed, but I want to document what sets it off. 

<img width="1584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38e6a67c979b61c867029b6771e580993d0783ae/Screenshot%202024-06-24%20at%2010.53.33%E2%80%AFAM.png" alt="Screenshot 2024-06-24 at 10.53.33 AM.png" />

FYI @ldelacosta

**Comment by vbahinwillit** [comment]
@outerpress, @ldelacosta  - Setting the feature flag "vaOnlineScheduling" to false will trigger this error. There is no appointment response. This message is strictly controlled by the feature flag.

```
// This selects the feature flag
const showApplication = useSelector(state => selectFeatureApplication(state));

// This displays the message
{!loadingFeatureToggles && !showApplication && <AppUnavailable />}

**Comment by ldelacosta** [comment]
No additional work is needed. Closing out the ticket. cc: @outerpress

**Comment by outerpress** [comment]
FYI this is documented here: https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=982-3324&t=uBXPG9qqJDV1EICb-4
