### ISSUE TITLE
CT-EYB: Dev Support

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#8474]
Review UI when updated by Dev team
Relay any edits / updates

**Comment by amyknox** [comment]
EYB implementation issues
https://airtable.com/tbljP9rzebaeT7S5y/viwEDTmC2v13AeOJ8?blocks=hide

**Comment by amyknox** [comment]
Still waiting on 7842- VET TEC Profiles
