### ISSUE TITLE
[UX] Create new text message to inform veteran about claim submission and some issues processing the claim

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84767]
## Description

To handle BTSSS timeout scenario based on the [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/travel-pay/claim-status-api-integration.md), there is a possible for `claim_status` api to return failed claim statuses.

In case of any below failed claim statuses,
 - Appeal
 - Closed with No Payment
 - Denied
 - Fiscal Rescinded
 - Incomplete
 - On Hold
 - Partial Payment
 - Payment Canceled

veterans should be informed about the claim submission & failure that happened while processing the claim.  This task is to create content for the new text message to be sent to veterans & get new template IDs from vanotify team for integrating with vets-api for notification.

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/84767?planning-poker) with Zenhub @benbrasso-agile6 @cgednalske

**Comment by benbrasso-agile6** [comment]
Let's discuss this at stand up today to ensure I'm getting this correct: 

<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjl5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2c2498e5427f9350f4abc13b08908f025aede85/Screenshot%202024-06-18%20at%2011.32.10%E2%80%AFAM.png" alt="Screenshot 2024-06-18 at 11.32.10 AM.png" />

<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0J5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2407a1dbbe16267d7fd2732f45f9041509aba99f/Screenshot%202024-06-18%20at%2011.32.16%E2%80%AFAM.png" alt="Screenshot 2024-06-18 at 11.32.16 AM.png" />

https://dvagov-my.sharepoint.com/:w:/r/personal/benjamin_brasso_va_gov/Documents/Online%20travel%20pay%20for%20Oracle%20Health/VA%20Notify%20SMS%20for%20BTS3%20API%20responses%20in%20eCheckin.docx?d=we56a9bc7b79c48759ae70c283d40b421&csf=1&web=1&e=OYePH1

**Comment by benbrasso-agile6** [comment]
Once validated, I will copy this over to VA Notify's document, where then Melanie can provide the template IDs

https://dvagov.sharepoint.com/:w:/s/VANotify-VEText/EZIrTO3T99tDu5YBtXc7h6QBLkV1f95tXXTCzF0-miCVOA?e=8QQAEL

Going to put these docs in our repo now

**Comment by benbrasso-agile6** [comment]
In our repo 

Created new [content readme](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/content/readme.md) 

And [BTSSS VA Notify SMS Content page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/content/btsss-responses-va-notify.md)

**Comment by benbrasso-agile6** [comment]
Making a change, based on stand up

**Comment by benbrasso-agile6** [comment]
Updated. @loripusey second set of eyes for validation. 

<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1p5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b571515aec80e2543785296c4567f1abb2ff414/Screenshot%202024-06-18%20at%2012.42.39%E2%80%AFPM.png" alt="Screenshot 2024-06-18 at 12.42.39 PM.png" />

**Comment by loripusey** [comment]
Should we say "can't go though" or "didn't go through"?

**Comment by loripusey** [comment]
Also, since we know their claim didn't go through, should we just tell them to submit another way?

**Comment by benbrasso-agile6** [comment]
Via Kanchana, Mark said no. Because basically, we're receiving a response that they can't file for this appointment because of one of these reasons: 

Appeal
Closed with No Payment
Denied
Fiscal Rescinded
Incomplete
On Hold
Partial Payment
Payment Canceled

So, the "action" would be to call their BT office to find out what the actual problem is and if it can be resolved. 

Make sense?

**Comment by benbrasso-agile6** [comment]
WHich is why I chose the word "can't" because they shouldn't retry.

**Comment by loripusey** [comment]
Sounds good

**Comment by benbrasso-agile6** [comment]
TY; finishing up the hand off steps now...

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske FYI, this new text message response for BT has been added into the [check-in design page](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=3564-4577&t=fzCWsXfYrZWbGhxP-4) in Figma, but not in production, since it's not in production yet.

**Comment by benbrasso-agile6** [comment]
All set; with Melanie - https://dsva.slack.com/archives/C010R6AUPHT/p1718742567252349?thread_ts=1706895333.034539&cid=C010R6AUPHT

Melanie will provide the IDs in the SLack thread or document for engineers. Need to wait for her resposnse.
