### ISSUE TITLE
SAML Error Messaging: UX and Content Changes

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#8487]
As a user logging into VA.gov it is important that I be presented with clear and concise error messaging so that I am not turned off from accessing needed services or information. There are two error pages that may leave a user confused.

1. Internal Protocol Error (login attempt after session timeout) **DONE**

2. Error 60: SAML message is invalid (over 10 minutes to login)

Changes should be made to make these pages more user friendly including alignment with the VA style guide and clear language.
![SAMLerror.png](https://images.zenhubusercontent.com/5e5d21ccbf668393ce8d133e/a95cda62-b3fe-441c-b3c8-5e5120e79086) 
![Screen Shot 2020-03-31 at 6.08.50 PM.png](https://images.zenhubusercontent.com/5e5d21ccbf668393ce8d133e/ef776e1d-a55b-44cb-b955-aa70b408be04)

**Comment by bridgethapner** [comment]
# Error 60 Page

We're sorry. Your single sign-on session has timed out. We set a time limit on signing in and identity proofing to keep your account secure. 

If you were working to verify your identity on ID.me, your progress has been saved.

Please return to VA.gov and sign in again.

**[Button to VA.gov]**

_Question: Is it correct that users would see this error message in only the following two scenarios: 1) if they took longer than 10 minutes to sign in and 2) if they took longer than 10 minutes to identity proof?_


# Internal Protocol Error
We're sorry. There was a problem signing you in. Please return to VA.gov and try to sign in again.

**[Button to VA.gov]**

_Question: Is there anything else we can do to direct users here aside from asking them to return to VA.gov again?_

**Comment by bridgethapner** [comment]
**Notes fr 4/28 stand up:** 
- We can only put a specific VA.gov error message here _if_ it can be detected that the error originated on VA.gov. We're waiting to hear about this. 
- Can we redirect to a VA.gov error page _if_ it can be detected that the error originated on VA.gov? 
- For now, I'll focus on slight copy tweaks we can make to existing Error 60 and IPE error pages.

**Comment by bridgethapner** [comment]
**Notes from 4/30 standup:** 

- For each stage of auth flows, we can control the error pages. The text after "error details" on Error 60 will need to stay. "SAML 20" and the timestamp will have to stay. Everything else on the page we can change. 
- "Error 60: SAML message is invalid" can be changed, or styled to be smaller
- WARNING NOTICE will need to be present
- Outstanding q: can we be site-specific about this page?

**Comment by bridgethapner** [comment]
Hi there @patrickvinograd - I think this tracks with what we discussed (open to any feedback! - esp on the headline. Does **Your session has timed out** sound like the best way to describe this error to you?)

![Error60_1.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/9171ba06-4e12-4754-91ea-7a751129337a)
![Error60_2.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/8fe55263-04dc-4f03-bbfd-df36b2bc041a)

**Comment by patrickvinograd** [comment]
The "Error 60: SAML message is invalid" may present because the sign in attempt timed out, or it may be due to another invalid SAML payload. The latter is probably rare (the various CSPs should not be sending otherwise invalid SAML), but possible, and I'm predicting the IAM team may object to making the error too specific. 

That's unless we do extra work to customize the message based on parsing the "error details" to know it's specifically a timeout issue vs. some other source of invalid SAML.
