### ISSUE TITLE
Create ESLint rules to call axeCheck in E2E tests properly

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#8491]
As an accessibility expert/FE reviewer, I want an ESLint rule to check to see if VFS engineers are calling the `axeCheck` helper method correctly in their e2e tests. ~~are including E2E tests with AXE checks so that I don't have to manually look at the E2E tests for every new feature and put ownership of accessibility testing onto VFS teams.~~

Rules: 
Verify that an AXE check is in every E2E test (MVP) 
Verify there is an E2E test that has an AXE check for hidden content based on actions

AC: 
This ESLint rule runs for all new code being built/merged to vets-website
The ESLint rule throws a warning if there are not AXE checks in the E2E tests for the code being merged
If a team disables that ESLint rule, then it has to be reviewed before merged by FE review group

Docs:
* https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/testing/e2e/nightwatch-commands/axeCheck.js

**Comment by 1Copenut** [comment]
Shipped to prod and documentation completed. Moving to close.
