### ISSUE TITLE
Update application generator to use registry.json

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#8496]
## Task
Because the `manifest.json` isn't what's used to create application landing pages anymore, we need to update the app generator to add an entry to the `src/applications/registry.json` as well.

## Acceptance Criteria
- [ ] The extraneous bits that Webpack doesn't use aren't added to `manifest.json`
- [ ] A new entry is appended to `src/applications/registry.json`

**Comment by meganhkelley** [comment]
Hey @cvalarida is this complete? If so could you close & link a PR, thanks!

**Comment by cvalarida** [comment]
Yessssss.....
https://github.com/department-of-veterans-affairs/generator-vets-website/pull/18
