### ISSUE TITLE
Remove the generic 'new VA.gov' welcome modal

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8499]
## Remove the generic 'new VA.gov' welcome modal

When we launched the new VA.gov in 2018, we created a 'new' onboarding modal. Because VA.gov is no longer new, please remove the 'new va.gov' modal. 

This needs FE engineering support.

AC:
[ ] Users no longer see the 'new' modal when they arrive on a VA.gov page.

**Comment by jenniferlee-dsva** [comment]
![image](https://user-images.githubusercontent.com/43381063/80509106-ecb19b00-8946-11ea-85fd-6b5eaeb1bc79.png)

**Comment by stephorkandatx** [comment]
Confirmed that this has been removed. Confirmed with google incognito browser, IE InPrivate browser mode

**Comment by jenniferlee-dsva** [comment]
Thank you @stephorkandatx  - this would be a good thing to include as a TOT item for awareness.
