### ISSUE TITLE
GIBCT: Missing icons on Institution Profile Pages

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8503]
Under the school name on the profile page, several brief descriptions of the school are listed. Each of these descriptions has an associated icon. The icons for length, type, and size are no longer displaying.

Example institution: https://www.va.gov/gi-bill-comparison-tool/profile/11802405

## Current:

![Screen Shot 2020-04-28 at 10.08.54 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/edd75904-6cff-48c8-971d-346c730e746e)

## Expected:

![Screen Shot 2020-04-28 at 10.09.01 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a567dd3c-e2c1-4013-ac24-da62e727625f)

**Comment by ksantiagomorgan6** [comment]
Pull request: 

https://github.com/department-of-veterans-affairs/vets-website/pull/12472

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This fix is in Staging and ready for review.

**Comment by ccruzgra** [comment]
@delli-gatti-michael Very nice job! This fix checks out.

**Comment by delli-gatti-michael** [comment]
Closing this out with QA and UX approval.
