### ISSUE TITLE
[DevOps] Eric Oliver needs access to VEText Datadog

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#85046]
## Description
Necessary for PCI on-call duty.

See https://github.com/department-of-veterans-affairs/checkin-devops/blob/main/docs/PCI%20API%20Tier%203%20Team%20Playbook.md

## Tasks
- [ ] [DevOps] Open a ECC service monitoring ticket for access.

## Acceptance Criteria
- [ ] Ticket opened.

**Comment by olivereri** [comment]
I already have access to VEText. This was initiated when I on-boarded with VA Online Scheduling.
