### ISSUE TITLE
GIBCT: "About this Tool" link is missing right padding on mobile

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8504]
At the bottom of the page for all Comparison Tool pages, there is an "About this tool" link. Next to the "About this tool" link, there is a "Download Data on All Schools" link. The padding between these links is missing in mobile view. The problem persists on all pages within the Comparison Tool.

![Screen Shot 2020-04-28 at 10.38.14 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f22bf372-2b7e-4854-8417-cc82558350d8)

![Screen Shot 2020-04-28 at 10.27.46 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/182e23c4-c89b-4c12-8471-2fa608831600)

**Comment by ksantiagomorgan6** [comment]
Pull Request: 

https://github.com/department-of-veterans-affairs/vets-website/pull/12473

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-04 at 12.50.43 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4015b2f1-6544-4e43-b05f-9891dcaecdb5)
##
![Screen Shot 2020-05-04 at 12.51.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6a199bbd-8da3-4b05-a03f-62ec988a8476)
##
![Screen Shot 2020-05-04 at 12.51.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5b6cbf51-ae54-48a8-ad95-5fe4775418fe)
##
![Screen Shot 2020-05-04 at 12.56.13 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a80ea6c2-08a3-4d65-8042-95e907fa23d3)
##
![Screen Shot 2020-05-04 at 12.56.22 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6ec50c90-8454-4733-b572-8bc2afd7b640)

**Comment by sonntag-adam** [comment]
@ccruzgra this is in staging.

**Comment by amyknox** [comment]
@sonntag-adam looks good!
