### ISSUE TITLE
[Launch] Original Claims: Check Status of 526 Product Guide and Video for Call Center

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8506]
## User Story or Problem Statement
We need to be able to provide the call center any updated guidance on 526 since Original Claims will be turned on.

Here is what already exists: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product

## Goal
Ready for launch and approved by call center.

## Acceptance Criteria
- [ ] Check to make sure no additional guidance needs to be added to the Call Center guide and update
- [ ] Write ticket/schedule meeting with call center as part of collab cycle
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
These exist, and they should be accurate per what is available in original claims. But just a disclaimer: found it difficult to locate these conditional logic items:

- Served Under a different name? - exists under a component called alernateNames and takes place after the veteran selects a claim type but ONLY appears if the veteran doesn't have rated disabilities
- Received military retired pay? - exists under a component called retirementPay and again only appears if the veteran doesn't have rated disabilities
- Other things that show only if you have no rated disabilities: separation pay, training pay, retirement pay waiver (for retirement pay waiver you have to have military retirement pay), and training pay waiver (for training pay waiver you have to have training pay)

We need to ensure it is obvious in the guide that **these items only show when the user has no existing rated disabilities.**

We can update this in the documentation that currently exists.
