### ISSUE TITLE
Make sure User table is not used in async jobs

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#85079]
# Overview
There is a pattern that has been used in on other forms that may also be an issue in our code.
The issue can happen when the veteran profile is retrieved from the User table in an async job, rather than being passed into it.  Since the data in the User table is only available when the user is logged in, you can run into a scenario where the data is missing for a user.

Here is an example of what we don't want:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/veteran_readiness_employment_claims_controller.rb

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/vre/submit1900_job.rb

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb

# Tasks
Make sure that our code doesn't try to retrieve the `User` from an async job.  It should either be passed into the async job or the data should be retrieved from the UserAccount table

**Comment by TaiWilkin** [comment]
I've confirmed that, during form submission, within the `Lighthouse::PensionBenefitIntakeJob`, we only use the user's UUID, which is passed in. We don't look up other user data within the async job.
