### ISSUE TITLE
Project Kickoff Claims Status

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8508]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/README.md

## Meeting attendees from **requesting team**
- Product Manager (required): Luke Majewski
- DEPO Product Lead (required): Andrea Schneider
- Entire VFS team (recommended): Anna Carey, Sarah-Jaine Szekeresh, Robin Garrison, Kevin Stachura, Christian Valla, Nick Sprinkle

## Scheduling
Anytime we have a gap, we can provide a specific set of times once we start chatting.

**Comment by meganhkelley** [comment]
Scheduled for 5/7

**Comment by vbellissimo** [comment]
Cancelling/old task.
