### ISSUE TITLE
AWS access for Tyler Guerrero

### ISSUE THREAD

**Issue by TylerGuerrero-va** [department-of-veterans-affairs/va.gov-team#85095]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Tyler Guerrero

### Your Email

guerrero_tyler@bah.com

### Team, Role, and Company of the target individual

Team Pivot (Lighthouse), Software Engineer, Booz Allen Hamiliton

### Product Manager (PM) name and email

Greg Feliberty feliberty_gregory@bah.com

### Product Owner (PO) name and email

Andrew Fichter andrew.fichter@va.gov

### Desired AWS Access

As part of the Lighthouse Pivot! team I need the ability to execute MR deployments of the OAuth and SAML Proxies deployed via AWS CodeBuild. These are manually triggered to higher environments as part of the Lighthouse maintenance request (MR) system.

Additionally, supporting our SLA'd environments with Lighthouse requires Cloudwatch log access to debug any monitoring or user reported errors for the Lighthouse OAuth services.

Param Store and DynamoDB are required for configuring the Lighthouse OAuth & SAML Proxies, both are edited during MR's as well as viewed during support events.

### Access Expiration

January 07, 2026 (Contract end date)

### E-QIP Transmittal Confirmation

I do not have a confirmation screenshot due to already having filled out the E-QIP application. I have a prior secret clearance so I did not need to feel out another E-QIP application.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
@TylerGuerrero-va AFAIK, we still require an E-QIP transmittal confirmation. Can you please check in with your COR member?

**Comment by TylerGuerrero-va** [comment]
Will check with them, I did onboard with my existing clearance so no e-qip was filled out, I can provide that email if needed stating that a previous investigation that meets or exceeds the current request was done

**Comment by dbrown-va** [comment]
@stoiven , Tyler already has his PIV and is a member of the VA API (Lighthouse) program.

There is not E-QIP that can be referenced in this case.

**Comment by andreahewitt-odd** [comment]
@stoiven Hey @TylerGuerrero-va is going to get his COR to comment because his eqip transmittal was years ago. Tyler, once your COR comments, we can move forward.

**Comment by vacoleec3** [comment]
I will go and check his E-QIP status with the Onboarding manager, once that is done I will relay his status back to you

**Comment by vacoleec3** [comment]
It is cleared. Transmittal date of 2/26/2024

**Comment by TylerGuerrero-va** [comment]
@stoiven Is there anything else that needs to be done for AWS access for the proxies on my end ?

**Comment by stoiven** [comment]
Sorry for missing this! I'm following AWS instructions on our side and it seems like you are not on `Atlas` or the `Platform Roster` 

> If the user is on a VFS team but not in Atlas, add the NOT YET label and instruct them to start the Platform orientation process [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). 

Is it possible for you to complete this then we can get you added.

**Comment by TylerGuerrero-va** [comment]
Hey @stoiven I already have filled out the VFS member template so I can be added to atlas like two months ago, the issue is here: [VFS member issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80221)

**Comment by stoiven** [comment]
Sorry for the delay -- I dm'd your AWS info on Slack

**Comment by stoiven** [comment]
Access granted and tempo creds passed to user
