### ISSUE TITLE
Design | Profile | Add Privacy Security Statement Component across the profile 

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#85101]
## Background

We need to add privacy and security statements where we collect contact/personal information. 

It should be one privacy and security statement in the profile (ie. it doesn't change per page). 
Link to a bigger/more extensive privacy and security document. 

- we need to confirm the content 
     - a little blurb with a link to the privacy statement to learn more 
     - accessibility question here, can we have two links on the page going to the same place, what are the rules? 
- mock this as a mini footer/sub footer that lives at the bottom of all the profile pages (including the hub and editing as a subtask) 

### Example
See examples at the bottom of other forms - they have a pattern that links off to the privacy/security statement
- privacy security example on a healthcare form ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/c5eefb6a-009a-4409-8bd3-e0b5387734f5) 

- modal triggered (we don't need to do a modal, but documenting here) ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/39a55964-886b-42ef-8313-9aef1e9872b6)

## AC
- [ ] we have a content and accessibility approved privacy and security statement we can include in a component across the bottom of all of the profile pages. 

## Output 
- [mockup](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=397-3146&t=9mmblURduiMwsjFY-0)

**Comment by andaleliz** [comment]
@mtcA6 I created this placeholder ticket but missed the part of planning where yall discussed any details around this. Feel free to add any details before our team meeting if you would like.

**Comment by andaleliz** [comment]
@clantosswett and @mtcA6, I'm thinking we can put a note above the feedback button like we do on the notification settings page for this statement too. [Here's a mock-up of how it would look on contact info](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=397-3146&t=cyeTW8ispwUS61C0-11), and I'll be taking the content to CAIA today to get it reviewed. What do you think?

I'm not quite sure how we'd handle this on the notification settings page since we have a specific policy that applies to that page only.  My instinct is to only show the more relevant one on that page, which would require a bit of FE conditional logic to run a check about which page we're showing before displaying the message. I think @adamwhitlock1 said that wouldn't be a big deal though.  Do either of you have any thoughts about how to handle that page?

**Comment by clantosswett** [comment]
@andaleliz I think this looks great! I agree that I think it would make sense to show the notifications specific message in place of this one. Since it seems like that sounds possible, let's go with that approach. If not, maybe we could move the notifications message to the top as you mocked up in an option and have this one reside on the bottom. But only if OGC feels like that is necessary. Thank you!

**Comment by andaleliz** [comment]
After reviewing this with content and a11y, I had to make some tweaks to the language and add a heading.  Adding the heading actually helps w/ the notification settings page though - I think we can leave the note at the bottom as-is, pending OCG approval of course.

I created [an annotated reusable component in the auth exp pattern library](https://www.figma.com/design/Byfu9NRKXCtXN3DuMYguKI/Authenticated-Experience-Pattern-Library?node-id=553-4914&t=V7S9Q0oEQ9KazlAF-11) for mobile and desktop that can be used to update all the mock-ups once this goes into production.  The next designer can either replace all the files w/ the new component, or copy/paste the content into the existing footer component being used across the files.  The artboards will all have to be resized so I'm not sure if one approach would be faster than another.

I also created an example of each section of profile with the new section on mobile, and did one desktop variation just to give folks an idea of how that would look.  [All of the examples are here](https://www.figma.com/design/Byfu9NRKXCtXN3DuMYguKI/Authenticated-Experience-Pattern-Library?node-id=553-7405&t=V7S9Q0oEQ9KazlAF-11), and use the new components I created at the bottom.

It may go without saying, but in case not - want to call out that we'll want to alert the cartography team to these updates so they can reflect them in their personal health contact files too.

Going to close this out but please feel free to reopen if you feel further work is needed!
