### ISSUE TITLE
[Development] 526: Remove excess rated disability fields from 526 submissions 

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#8510]
## Goal
Send EVSS only required and optional disability fields as defined by [endpoint documentation](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/index.html?url=https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/disability/526ez/engineering/evss-docs/wss-form526-services-web-v2.yaml#!/form526/submit). << check that this is correct

As part of the disability translation process [we simply duplicate the `ratedDisabilities`](https://github.com/department-of-veterans-affairs/vets-api/blob/4817e431cbd276935809b3c813e8c2f4fd2e0bdd/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L415) which means we're copying over and resending all the disability information we received from[ EVSS's rated disabilities endpoint](https://pint.ebenefits.va.gov/wss-form526-services-web-v2/swagger-ui/index.html?url=https://pint.ebenefits.va.gov/domain1/wss-form526-services-web-v2/rest/swagger.yaml#/form526).  This led to errors when EVSS started rejecting submissions with unnecessary fields.

This story also seems related to BDD in which we are getting a copy of the schema so we can ensure we match for facility location code, separation date, etc.

## Acceptance Criteria
- [x] Our submissions directly match the EVSS schema. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
updated docs! https://github.com/department-of-veterans-affairs/va.gov-team/issues/8528

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/evss-integration

**Comment by annaswims** [comment]
@Mottie removed the extra attribtues on the FE, which is just as good. https://github.com/department-of-veterans-affairs/vets-website/pull/12471

[this spec](https://github.com/department-of-veterans-affairs/vets-api/blob/8d10cab07224561b2c226a398d8cc1804e2e27ca/spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb#L966
) verifies our code matches the [schema documented here](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/index.html?url=https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/disability/526ez/engineering/evss-docs/wss-form526-services-web-v2.yaml#/form526/submit)
