### ISSUE TITLE
Design | Profile | Notification settings | Mock up privacy and and security statement

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#85100]
## Background

We're adding a privacy and security statement to the notification settings page and need to figure out where to put it.  Danielle has already created the content.

## Tasks

- [x] Mock up notification settings page w/ the new statement
- [x] Review w/ team

## AC

- [x] mock is done 

## Output 
- [mockup](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=251-4692&t=EXjQvwDbP401QNGp-0)

**Comment by clantosswett** [comment]
@andaleliz here is the language Danielle recommended for the notification preference page to clarify that notifications over these channels are not completely secure. 
Note: Text messaging and email aren't encrypted forms of communication.
[Read more about privacy and security for digital notifications](https://www.va.gov/privacy-policy/digital-notifications-terms-and-conditions/#privacy-and-security)

**Comment by andaleliz** [comment]
@clantosswett and @mtcA6 this is a fairly straightforward situation.

I'm thinking we can replace the note at the bottom of [the current page](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=251-8687&t=oXowbWaYh5JeJgjn-11) with this new note - [here's a mock-up](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=251-16178&t=oXowbWaYh5JeJgjn-11), and some thoughts:
- It feels clunky to have two notes, or an list of bulleted items that aren't clearly related
- I don't think the existing note is particularly valuable. People see it in research sessions and just say, "oh" or "ok" and quickly move on. Plus, we're adding more notifications soon so it'll quickly be irrelevant.
- Thought we don't have email notifications today, I think it makes sense to reference them here because they are coming and the page we're linking to talks about them as well.

If we feel this is important enough to elevate, we could move the note to the top of the page with contact info ([mock-up](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=252-16801&t=oXowbWaYh5JeJgjn-11)), but IMO it's fine at the bottom, and a fairly common place to expect to see content like that.

Thoughts?

**Comment by mtcA6** [comment]
Agree with everything you said, bottom of the page is great and replacing the note that's there would be a great move.

**Comment by andaleliz** [comment]
@clantosswett anything I can do to help facilitate that? If not, I will move this to validate so it can go to FE. 

I created a desktop mock-up with the note on the bottom - all are on t[his Figma page](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=251-4692&t=OUKefEIF70k90Ytu-11).

**Comment by clantosswett** [comment]
I don't think there's anything needed right now. I have a meeting with the group (including OGC) not next week but the following week to go over mockup which means you will be gone :( but I think it will be okay and worse comes to worse, we can put it at the top of the page. Thanks!

**Comment by mtcA6** [comment]
I've moved this to validate, once we get OGC's approval we can spin up the FE ticket for this. 

cc: @ACParker89

**Comment by mtcA6** [comment]
Actually, we can close this, we have the epic when we have OGC approval we can spin up any new tickets we may need
