### ISSUE TITLE
Analysis: Supply reordering app alerts and/or route guard

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#85108]
### User story

As a Cartography team member, I want to understand the existing state of alerts/guards in place on the supply reordering app, identify gaps, and then map out the right future state of alerts/guards when the app will be under /my-health/, so that we can cover gaps as we implement.

### Notes
- [Mural source of truth](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717177396025/367057c4a9219404c3b7080e71210082b3c65771?sender=uebde62ceb342c6477fb09406) for account requirements for all apps and supporting APIs
- [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1717526862232939?thread_ts=1717512744.362889&cid=C0581MN69TJ) with key questions/topics and input from Patrick
- Work to add a sign-in widget to the unauthenticated entry-point page for the tool is also heavily impacted (#79823)
- @Jenny-yw is the UX designer for the supplies app

Possible tasks:
- 

## Acceptance criteria

- Analyze the existing state of alerts/guards in place on the supply reordering app and identify gaps, i.e. use cases where 
- Is defining the future state a 2nd ticket??

**Comment by wesrowe** [comment]
Jenny shared [in slack](https://dsva.slack.com/archives/C0581MN69TJ/p1717787053596859?thread_ts=1717512744.362889&cid=C0581MN69TJ) this [mural of account checks](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717692986955/7ef2f8873dd34ea6ab9f0e37ed94508570b0be2e?sender=ueeece9e244394145c84e5173) specific to the supply-reorder app. It shows a couple alerts that need to be implemented (either in-app or via route guard).

@Jenny-yw, from a UX perspective, do you think the not-registered alert is in the right place in the chart? The way we have been thinking about a route guard that would catch unregistered users, that check might (I believe?) come before the series of checks starting with "deceased?".

**Comment by wesrowe** [comment]
Met with Jenny to brief her on the context around changes to the supply-reorder app. She's going to reach out to Laura and Sara to understand why a decision about route-guarding is blocking Laura from finalizing sign-in widget content.

**Comment by wesrowe** [comment]
@Jenny-yw and @sterkenburgsara, I just created [a story map](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717692986955/7ef2f8873dd34ea6ab9f0e37ed94508570b0be2e?wid=0-1718145728325) to help evaluate this work. Hopefully it's pretty self-explanatory. 

The key conclusion I'm reaching here is: the minimal thing necessary to move the app under /my-health/ really is adding sign-in widgets to the two existing unauthenticated entry-point pages. That would provide the user the same UX they have now. So you'll see a row of stickies labeled "Mimimal update: Current UX, moved to /my-health/" to reflect that.

To my mind, the work that is currently blocking us belongs in a later release. It's **_improving_** the UX of the entry points, and it's **_adding_** alerts about verification. But those things are not truly necessary to deliver real value to the user, of being under the portal.

**Comment by sterkenburgsara** [comment]
The sign-in widget content is all about using an identity-verified credential (which we won't actually be checking with the plan above). Do we need to eliminate the identity-verification language for now and make that a fast-follow improvement?  
<img width="913" alt="Screenshot 2024-06-12 at 9 32 13 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/04900ca5-2ce8-4842-9ccd-7514a5d2bb92"> 

// cc @laurwill @Jenny-yw

**Comment by wesrowe** [comment]
Apologies for the shifting ground under this one. I want to make sure this comment thread is synced with the latest developments from today, 6/13. 

I spoke with Patrick this morning about the supply-reorder app. 
- The immediate next step (see [slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1718301296345939)) is that CAIA will implement the new single/combined unauthed page for all supply reordering. This will have a regular CTA link to the app, not a sign-in widget.
- The order of operations to implement the future state is still up for grabs. But the future state will include:
  - A sign-in widget on the unauthed page that can inform unverified users that they need to complete verification
  - The app moving under `/my-health/`
  - The app providing users with no facility registration an alert to that effect
