### ISSUE TITLE
[FE/QA] 10-10EZR: Update form submission content to reflect async job implementation

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85115]
As a Veteran, I would like to know if my EZR submission was, or will be successful so that I don't expect that it has worked when it has not.

- [x] Update confirmation content to reflect Figma designs
- [x] QA on STG
- [ ] **Success: Content on submission reflects Figma **

**Comment by JoshingYou1** [comment]
Blocked as of 6/7/2024 due to review instances not being deployed when creating a PR. Please refer to this slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1717779568925129

**Comment by emily-brown34** [comment]
needs points

**Comment by JoshingYou1** [comment]
The review instance issue has been resolved.

**Comment by JoshingYou1** [comment]
<img width="681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85dae40250e45c98fe80025285b9379c19583661/Screen%20Shot%202024-06-10%20at%208.53.31%20PM.png" />
