### ISSUE TITLE
Submit an ESECC request to make OGC endpoints reachable from vets-api

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#85136]
## Background
Submit an ESECC request to make OGC endpoints reachable from vets-api

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
Platform request:
https://dsva.slack.com/archives/CBU0KDSB1/p1717091951946309

Response TL;DR
>Kyle A. Matheny  [9:48 AM]
>My guess is that you may need to put in an ESECC request 
>@Holden Hinkle
 >to allow us to talk with that domain over that port -- the owner of the domains should put in a request for who is >allowed access to make calls to them

Docs I found:

- https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration
- https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

That `.md` file directs me to the [ESECC portal ](https://esecc.va.gov/)which I discovered is only available in CAG. I reviewed the website and wasn't sure how to proceed so I emailed their support.

**Comment by holdenhinkle** [comment]
ESECC hasn't responded to my two emails.

I read over a bunch of the documentation on their portal this morning and I think I need to submit a "BPE & Internet Connection" request, but I'm not certain. All of this is foreign to me.

I submitted a request to platform support, asking if someone from DevOps could pair with me to help me complete the request form.

New support ticket - https://dsva.slack.com/archives/CBU0KDSB1/p1718037605615979

**Comment by holdenhinkle** [comment]
Scheduled pairing session with Steven Cruz, platform DevOps, tomorrow (Wednesday) at 3pm EST.

**Comment by oddball-lindsay** [comment]
Jen recommends reaching out to Steve Albers and Sam Wiley for assistance, perhaps a government engineer can assist.  Could be before submitting, or during the process and request help.

**Comment by holdenhinkle** [comment]
Convo with Steve Albers - https://dsva.slack.com/archives/C06ABHUNBRS/p1718129726147099

**Comment by holdenhinkle** [comment]
Request submitted!

**Comment by holdenhinkle** [comment]
Still no updates.

**Comment by holdenhinkle** [comment]
ESECC is adding my request to the agenda for their Thursday, 10am meeting that they're inviting me to attend.

**Comment by holdenhinkle** [comment]
I attended the ESECC meeting.

They told me if the request doesn't need to leave the VA network (ours doesn't) ESECC isn't involved. The told me to contact this group:

NEW GROUP FOR INTERNAL DNS:  IO.SS.FO.ActiveDirectory.Triage
IO.SS.AS.AD.DNS Adds Deletes & Modifications For DNS Adds, Deletes, and Modifications

**Comment by holdenhinkle** [comment]
Opening a new ticket to contact the internal dns group.
