### ISSUE TITLE
Contact Center Review for [Appointments team -Updated Product guide]

### ISSUE THREAD

**Issue by AdamOye** [department-of-veterans-affairs/va.gov-team#85161]
# Request the Contact Center Review 

## What this form is for
Appointments team Product guide review 

## Description
VAOS product guide: Fixed broken web links in the updated product guide.

### Launch Date
6/21/24

### Version Number
v.2

### Product Guide
https://docs.google.com/document/d/1LttFoD7DA66Djc3tkOlyEWGF0kkUKcwA/edit#heading=h.gjdgxs

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @AdamOye. Do you have this file in Word or something similar?

**Comment by AdamOye** [comment]
@starlow00 Yes. https://docs.google.com/document/d/1LttFoD7DA66Djc3tkOlyEWGF0kkUKcwA/edit#heading=h.gjdgxs

**Comment by starlow00** [comment]
Thanks, @AdamOye. I had to request access.

**Comment by AdamOye** [comment]
@starlow00 access granted

**Comment by starlow00** [comment]
The draft looks good, and I am sending it to VEO for their review.

**Comment by AdamOye** [comment]
@starlow00 Sounds like a plan. Thank you!

**Comment by starlow00** [comment]
There are no changes from VEO. The working copy is attached. Please use it for future revisions. Thank you!

[VAOS product guide v2 SRT 06062024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2RjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--489fd7314ab1e3eefd0c94c61c34d7dc56f63d85/VAOS%20product%20guide%20v2%20SRT%2006062024.docx)
