### ISSUE TITLE
[Document Upload Failure Mailer] Add Veteran-uploaded File List to Form 526 PDF Overflow Launch Prep

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#85179]
## Acceptance Criteria
- [X] Implementation completed, reviewed and merged
- [x] Basic behavior tested in staging
- [x] PDF examples (with and without full file list) shared with David Reiss for training purporses
- [x] Monitors implemented
- [x] EVSS notified of overflowText status (if it works in staging) so they can launch it in production
- [x] Will Lighthouse want to test in staging too?

**Comment by tblackwe** [comment]
Single File:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/7b3168f8-87fa-4378-aaa2-c3a4b610d442)

14 Files:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/7d9fea6d-2ded-46da-9f8f-e7e3c0d0db34)

100 Files:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/157ca3aa-1fbd-44d8-b2f5-e05a0fce2e6e)

**Comment by NB28VT** [comment]
Awesome thanks @tblackwe. So for testing I was hoping to cover the following cases:

1. Single file listed (done)
2. Multiple files listed (done)
3. File list that exceeds my 4000 character cap and only displays the message with the number of files "Veteran uploaded X files" instead of listing the files.
4. File list that exceeds 1000 characters but is less than 4000 characters. This is to validate the EVSS schema change is working and they are allowing an overflow that exceeds 1000 characters. In this case the full file list should be present. We will need to let them know if it worked in staging before they turn it on in production.

On 3, do you happen to know if the 100 files example above exceeded 4000 characters?

On 4. it appears we still need to test this as I don't think the 14 files example would have exceeded 1000 characters but I may be wrong.

How did you go about setting up these tests? If you have a script or something to share I can tweak it accordingly to validate 3 and 4.

**Comment by NB28VT** [comment]
Was able to configure the monitor here as planned (shows when the file list is included or not and how many files were present in each situation)

<img width="1246" alt="Screenshot 2024-06-17 at 1 40 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8537428/dba5765a-f4f3-4a08-bf97-f06559d044ce">


This is to allow us to monitor how many files are being included and decide if our threshold for how large the overflow text is is reasonable.

**Comment by tblackwe** [comment]
50 files ~2150 characters
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/c663a051-1943-443d-b2d2-b51537ddf95e)

**Comment by NB28VT** [comment]
[Notified EVSS](https://dsva.slack.com/archives/C1VBAHWQL/p1718650817030319?thread_ts=1713813700.917059&cid=C1VBAHWQL) that the overflow text schema change worked for us

**Comment by NB28VT** [comment]
[Shared examples of PDF overflow with David Reis](https://dsva.slack.com/archives/C04KW0B46N5/p1718652379182899)
