### ISSUE TITLE
Fix link and add link/blurb to Disability benefits hub

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8517]
1. Disability compensation rates link on hub page (https://www.va.gov/disability/) was pointing to old legacy page and needs to point to current page.

2. Hub page was also missing in More resources the link/blurb teaser to the "effective date" page. That blurb/link need to be created, then ordered to appear 2nd in the order of those blurbs to match left nav.

**Comment by AnneHurley** [comment]
Anne fixed the incorrect link, and wrote the blurb and created the teaser in Drupal on 4/27 Assigned to @RLHecht to review and publish. @mnorthuis  and @stephorkandatx FYSA

**Comment by RLHecht** [comment]
@AnneHurley I reviewed these changes. I changed the links to Node IDs for both (you always want to use node IDs instead of URLs in case the URL ever changes). I also changed effective date to "dates" to match the left nav, though the page title is just "date." Thoughts? I haven't published yet.

**Comment by AnneHurley** [comment]
@RLHecht Thanks for changing those to the nodeIDs - I found it confusing because the URL was what popped up, even when I was doing general searching. Thanks for that. 

And actually I would be happy for you to make a ruling on "effective date" vs. "effective dates" - that tripped me up too. I thought about making everything including the page title plural - maybe that's the best way to go to be consistent across the board. What do you think?

**Comment by stephorkandatx** [comment]
These need to be published, then can be validated and closed.

**Comment by RLHecht** [comment]
Published page. Will validate and close when live on site.

**Comment by RLHecht** [comment]
Validated on live site. Closing issue.
