### ISSUE TITLE
Access for Kendra Skeene

### ISSUE THREAD

**Issue by kskeene** [department-of-veterans-affairs/va.gov-team#8518]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Kendra Skeene
- Please Provide your email.
   > kendra@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse Program, Product Lead, Ad Hoc LLC
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0eNexUZ5xNC+mGPmo+pwUfWivPeocJsBEmc2ppeaimHTPvyaa1hRe4VU+cT+W6ChE1rQG32VJTHPjtbq+aQt44NZDrrvtFCGBnHhPZhBQrF1o4sO53NU+EAoBXutu3Szfyx3h3+PCyP5gcItt8B5QpAKiwkCyqqXSIJJDKQ6EcplGA+Z4DafK/5FE8NvE7Xaw3QNYImRMRagk1sclB8+Sea7GRLlbpSj1BJ2K5ABvD+VJayXf23CoP7iEptY+fT483PnugnT2QBh1xyCfKTrfg3rkhgosp+8QvvRUK3kKw0fOXoladcwKm25Ov1E7yteJm48GyzH32oU8nbR0gCFZ kendraskeene@Kendra-Skeenes-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by tskinn** [comment]
@kskeene you should be able to connect. Reach out in slack if you have any issues.
