### ISSUE TITLE
SOCKS access for Carissa Merrill

### ISSUE THREAD

**Issue by cmmerrill** [department-of-veterans-affairs/va.gov-team#85189]
### Your Name

Carissa Merrill

### Your Email

carissa.merrill@agile6.com

### Your GitHub Handle

cmmerrill

### Your Role and Team

Sr. UX Research + Design

### Product Manager (PM) name and email

Fran Cross fran.cross@agile6.com

### Product Owner (PO) name and email

Michelle Middaugh suzanne.middaugh@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjDuPSE65QjNEUl7w29E+VpsYgxaBMfIu6aZXJbP3qkLmCt4uBb0hsj73CiNdc/m9ESAGlXy5isbR/kTfFjOGrBu5nz9coEX6/WT52GxkfprMsSRPmKrai/W0wOq+Z92Ud8GE0Sqtq6ljUbUyQjkK9enSzLyGudYv9oivpcOvlNhb4CAEYid1aIdgfemFLIqp1pmyqFrYZTmEONlXcXbNgF7CzCmsWDuNrXnV5LWdtCaijmZ0/chdPa9p85dZ/j6x8nXviAgZlzk3glEIS9push8VDkaXrjzHIdcMiQnViNr3cnulG9r2rZVSoocHX+mv9wVDHwYDEFX6MxkuBfOcA3uTcyJ5XfXVgT9ZdukIOgK/lTjk2n017WjbYTSTaLbdp6zlXmc8TAthipB5HybRicQIVx40f3GlxYz2ZnWXQjjKkZPH0dN8VR+zH5m1oRgysXju5vysMjRUZik6uxR0ZjUbpY6hDtE5XVaOPv/snJFoOFmXuPV9J1prhZbq7nms= cm_a6@Carissa-Merrill.local

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/168835398/a7fb1480-bb3a-4015-8216-f0ae7a227cc2)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Merged your SOCKS PR. Please let me know if you run into any issues.

**Comment by stoiven** [comment]
Closing out ticket as SOCKS was granted
