### ISSUE TITLE
Feature toggles can define a default "enabled" value per environment

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#8519]
## Background

The current behavior is for features to be [enabled by default](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/flipper.rb) in development environments. This is causing problems for developers, because the SSOe flag is defaulted to enabled but SSoe is not ready for developers to use locally. See [this DSVA Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1589216158357600).

## Goal

Allow developers to specify a default value for a feature toggle in `config/features.yml` for each environment

## Acceptance Criteria 

- [x] Features default to disabled in all environments unless override key is  present
- [x] Adding a designated key/value pair in `config/features.yml` enables a feature by default in the specific environment
- [x] Existing feature configuration and behavior in test env remains unchanged
- [ ] Documentation for feature toggles updated

**Comment by alexpappasoddball** [comment]
@kfrz Do mind taking a look at this and seeing what would be involved?

**Comment by kfrz** [comment]
Are you suggesting developers could do something like this in `config/features.yml`:

```yml
 ssoe:
    actor_type: cookie_id
    description: >
      Enables ssoe, as opposed to saml authentication wrapped by id.me
    environments:
      development: false
```

[In the initializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/flipper.rb#L44) we could do something like this:

```rb
# ...
FLIPPER_FEATURE_CONFIG['features'].each_key do |feature|
  feature_config = FLIPPER_FEATURE_CONFIG['features'][feature]
  environment_overrides = feature_config.dig('environments')&.select { |_k,v| v == false }&.keys

  unless Flipper.exist?(feature) || Rails.env.in?(environment_overrides) 
    Flipper.add(feature)
    # default features to enabled for development and test only, unless environments/<env> is false
    Flipper.enable(feature) if Rails.env.development? || Rails.env.test?
  end
rescue
  # make sure we can still run rake tasks before table has been created
  nil
end
```

----

I suppose we'd have a few options, not all specifically the default-value route:

- modify the configuration to explicitly keep `SSOe` flipped off, would be straightforward to check for key but kinda hacky/ugly
- modify the local environment such that it *is* capable of handling SSOe and not breaking dev envs, not sure what that'd take
- use a [group gate](https://github.com/jnunemaker/flipper/blob/master/docs/Gates.md) to cordon off the "problem child" features 
- build a custom [adapter](https://github.com/jnunemaker/flipper/blob/master/docs/Adapters.md) for the ssoe-layer stuff?

@annaswims can you point to more specifics about why SSOe doesn't work in development/localhost? Or would you rather I PR the above example and call it a day?

**Comment by annaswims** [comment]
pretty much. I think we could just use the yaml structure from above and default features to disabled unless otherwise specified. 

````ruby
# default features to enabled for development and test only
    Flipper.enable(feature) if Rails.env.development? || Rails.env.test?
````
to something like this (with nil checks)
````ruby
  Flipper.enable(feature) if feature_config["environments"][Rails.env]
````

**Comment by kfrz** [comment]
That means features are disabled in production by default. This is fine but is more of a behavior change and would require modifying the `config/features.yml` to add a key to each feature. I was thinking, maintain the current behavior and allow developers to 'opt-in' to the new behavior by adding an *optional* `environment:` key? 

Either way I believe this is doable and we should be good to get it slated into Sprint 26. cc: @alexpappasoddball

**Comment by annaswims** [comment]
The current behavior is for features to be defaulted to disabled in prod/staging an enabled for dev/test.

**Comment by kfrz** [comment]
Capturing updated capabilities request:

- Desire is now to enable all features in development except those that are not already launched in production so that users see a more prod-like setup locally

**Comment by alexpappasoddball** [comment]
adding a task to update the documentation when this goes live, which can be found [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

**Comment by alexpappasoddball** [comment]
@kfrz @erluti are we just waiting to close this until the documentation is updated?  Can we knock this update out in the documentation and close it out?
