### ISSUE TITLE
SOCKS access for Adrian Jones

### ISSUE THREAD

**Issue by ajshred** [department-of-veterans-affairs/va.gov-team#85220]
### Your Name

Adrian Jones

### Your Email

adrian.jones@adhocteam.us

### Your GitHub Handle

ajshred

### Your Role and Team

Engineering Lead on Team Quokka

### Product Manager (PM) name and email

Jesse House, jesse.house@adhocteam.us

### Product Owner (PO) name and email

Peter Tebbenhoff, peter.tebbenhoff@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICGH2r6ulqvxzR7u/bwgYI3V+IKRgy/3XTMRyvJQgYO2 ajones@ajones-HP-ProBook-445-G8-Notebook-PC

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/84713593/7489fe9a-5aa0-4a88-a628-6271b2a2c972)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
I'm assuming your SOCKS access is good now? I'll close the ticket, but please let me know if you have issues.

@ajshred
