### ISSUE TITLE
CT: Update Profile Yellow Ribbon Modal Content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8524]
As a developer, I need to consolidate the Yellow Ribbon Modal content so that it can be updated in a single location resulting in improved maintainability.

## Assumptions:
1. This work is completed behind a toggle so that it is only available in the staging environments and below.
2. The content has been reviewed by EDU and agreed to as of 04/28/2020.
3. The content has been reviewed and approved by DEPO as of 04/27/2020.

## Acceptance Criteria:
1. When the user clicks on
    a. "Learn more" next to the "Will you be a Yellow Ribbon recipient?" question of the "Estimate your benefits" section of the CT profile page
    b.  "Yellow Ribbon" in the "Veteran programs" section of the CT profile page.
the following content is displayed:

> **Yellow Ribbon Program**
> 
> The Yellow Ribbon Program can help you pay for higher out-of-state, private school, or graduate school tuition that the [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) doesn’t cover.
> 
> Schools that choose to participate in the Yellow Ribbon program will contribute a certain amount toward the extra tuition. VA will match the participating school’s contribution, up to the total cost of the tuition and fees. To learn more about the Yellow Ribbon program, please [download our fact sheet](https://benefits.va.gov/BENEFITS/factsheets/education/Post-911_Yellow_Ribbon.pdf).
> 
> Veterans and Fry Scholarship and Purple Heart recipients, or their dependents using transferred benefits, are eligible for the maximum benefit rate. Active-duty service members and their spouses aren’t eligible for this program. (An active-duty service member’s dependent child using transferred benefits may be eligible if the service member is qualified at the 100% rate.) This information will be updated quarterly.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12653

**Comment by sonntag-adam** [comment]
Learn More link
![Screen Shot 2020-05-14 at 12.46.35 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/15c17eba-db1e-4e43-899f-4ec22d8a4fb3)
##
Yellow Ribbon link
![Screen Shot 2020-05-14 at 12.46.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e4598f23-899a-4531-8f87-e63c57d90027)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-14 at 1.02.48 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/576004e2-bdf6-42d9-8aa9-8465f8d98cae)

**Comment by sonntag-adam** [comment]
Does not show in a production build.

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/398&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam UXers took a look and this checks out!
