### ISSUE TITLE
Update Swagger Docs for VETS API for Yellow Ribbon

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8525]
In preparing for security, privacy review we discovered an issue with the swagger docs picking up the correct changes. 
This is a task to figure out why the latest updates are not showing & correct.

**Task**
- [ ] Investigate, make updates to Swagger docs

**AC**
- [ ] Swagger docs updated, ready to be viewed/shared

**Comment by stephorkandatx** [comment]
@kelsonic when this work is closed out, will this be the link I should share out? https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/default/gibctYellowRibbonPrograms

**Comment by kelsonic** [comment]
I think once it's merged it will actually be this link! 🙂https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/gi_bill_institutions/gibctYellowRibbonPrograms

**Comment by kelsonic** [comment]
But I'll need to validate it once it's merged to confirm 100%

**Comment by kelsonic** [comment]
Merged! 🎉https://github.com/department-of-veterans-affairs/vets-api/pull/4205

**Comment by stephorkandatx** [comment]
Thanks Kelson, Confirming - is this the accurate link? https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/gi_bill_institutions/gibctYellowRibbonPrograms

**Comment by kelsonic** [comment]
@stephorkandatx It is! Yay it looks so much better 😅

**Comment by kelsonic** [comment]
Validated on my side, looks ok to close 👍
