### ISSUE TITLE
Analytics Reporting Request for Facilities

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8534]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?
**Michelle Middaugh**

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?
**Facilities team, Display of facility-level operating status**
    

## Timeframe for Analytics Requested

- [ ] Baseline: Pre-implementation of facility operating status display (released on 4/22/2020)
- [ ] Periodic milestones, such as weekly for the first month and then monthly for a few months. 
    - The initial implementation is COVID-19-related so we expect to see immediate impact if we are successful. 
    - We are open to recommendations based on what is available and possible.  

## Analytics to Track Down
> Contact center call volume pertaining to changes to facility or service availability 
- questions such as: is the facility open? can I visit in person? is there a telehealth option? etc
- complaints about being turned away for service or visiting a closed facility

## Which Product Questions are you trying to answer?
- Has the addition of facility level operating status supported Veterans during COVID-19? 
- Has the availability of facility level operating status decreased call center volume?
- Is the information provided in the operating notes meaningful/relevant/understandable?
- Is facility level operating status displayed in places where Veterans find it to answer their questions or while preparing for a visit? 
- Should facility level operating status be added to other workflows?

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by clantosswett** [comment]
Currently, the contact center team does not have the ability to collect and track data that comes into VAMCs/clinical call centers. We will do some outreach to see if this is something that exists/we can have access to. In the absence of this data source, we will reach out to a few other call centers we work with for operating status question data and share with the team here.
