### ISSUE TITLE
Vets-api terminal access for Anita DeWitt

### ISSUE THREAD

**Issue by anitadewitt-va** [department-of-veterans-affairs/va.gov-team#85385]
### Your Name

Anita DeWitt

### Your GitHub handle (terminal access is managed through GitHub)

@anitadewitt-va

### Your dsvagovcloud AWS user name (if applicable)

Anita.DeWitt

### Team, Role, and Company of the target individual

VA Virtual Agent, Tech Lead, Thoughtworks

### Product Manager (PM) name and email

Vrushali Patil <vapatil@thoughtworks.com>

### Product Owner (PO) name and email

Nathalie Rayter <nathalie.rayter@va.gov>

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Liberty IT -  Michael G. Lovejoy

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [ ] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need access to remove old/unused feature toggles. 

Copy of previous socks ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/54760

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by davidpetras** [comment]
@anitadewitt-va Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by davidpetras** [comment]
@anitadewitt-va You've been granted access to Production, 
with access to Production limited to 6 months, expiring 12/16/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by davidpetras** [comment]
@anitadewitt-va Apologies as I meant to supply this link in the above comment.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by AnthonyWFlowers** [comment]
@anitadewitt-va  Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
No response, prod access is revoked. Will need to complete a new service ticket to regain access for prod.
