### ISSUE TITLE
[FE] don't convert time to UTC for travel claims

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#85389]
The BTSSS api expects time to be in the facility timezone. We are currently striping the offset and then running formatISO on the string resulting the the time being set as if its in UTC time but without the needed offset. 

According to the BTSSS engineers, we can submit the time with or without an offset. [ref](https://dsva.slack.com/archives/C02G6AB3ZRS/p1718995009129289?thread_ts=1718986442.173879&cid=C02G6AB3ZRS)

After digging around on stage, it seems like we are now getting start time with the appropriate TZ offset. So simply removing the stripTZ function should be all we need. 

If we want to really solidify this with a follow on, we can write the TZ we get back from facilities API to lorota, and then use the `utcToFacilityTimeZone` util. This util works properly even if the source time already has the correct offset, it doesn't need to be in straight UTC.

**Comment by brianseek** [comment]
This is wrong, the api expects time in the TZ offset of the facility

**Comment by loripusey** [comment]
@brianseek @wullaski so, is there any work to do or should I turn this ticket into a SPIKE?

**Comment by brianseek** [comment]
No, I'll update this ticket
