### ISSUE TITLE
VAOS FHIR service create operation

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#8538]
**User Story**: As a developer I want a FHIR create operation (RESTful POST) so that vets-api can add resource instances within VAOS.

**Acceptance Criteria**: Specs confirm that a #create method exists in the FHIR service, similar to the #read method, that performs http posts.

**Comment by saneshark** [comment]
This is redundant. Will be complete when Appointments#create is complete. Then again this one only has a 3 so maybe the idea was to tackle the two independently. I think it makes sense to have 1 ticket though since it will most likely be done as 1 PR.
