### ISSUE TITLE
The cancel appointment warning and confirmation page do not match the design spec

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#85393]
## Summary
The cancel appointment warning and confirmation page do not match the design spec. The appointment card is missing.

## Specs
- Device: Local development environment
- Browser: Chrome

## Steps to Reproduce

1. http://localhost:3001/my-health/appointments/
2. Select any cancellable appointment
3. Click 'Yes, cancel this appointment' button

### Actual Result
The appointment cancellation warning and confirmation screens did not match the design spec. The appointment card (border around the content) is missing.

### Desired Result
The cancel warning page should match:
<details>

<img width="138" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--519f63541cf48883cef0cd2454ce8f4e77df3847/image.png" alt="image.png" />

</details>

The cancel confirmation page should match:
<details>

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3587066/b2d41480-9cac-43b9-a8b9-38ce33fa3417)

</details>

## Definition of Done
- [ ] The cancel warning and confirmation pages should match the design spec
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment]
This has been validated in staging. No issues to report. 

<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0NDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--636cdbc0d04d4d6d801e175829ca48030ca74e96/Screenshot%202024-06-21%20at%202.01.29%E2%80%AFPM.png" alt="Screenshot 2024-06-21 at 2.01.29 PM.png" />

<img width="787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0dDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5221128538da0f9bff8b16d20edbc81c09c0da49/Screenshot%202024-06-21%20at%202.01.45%E2%80%AFPM.png" alt="Screenshot 2024-06-21 at 2.01.45 PM.png" />
