### ISSUE TITLE
10-7959c: add authenticated support to form

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85390]
As a user on VA.gov, I want to be able to log into VA.gov and fill out the CHAMPVA OHI form so that my application information is saved while I'm filling it out.

Acceptance Criteria:

- Given a user is logged into VA.gov
- When the user accesses form 10-7959c online and starts to fill it out
- Then the user should be able to save their progress

**Comment by michaelclement** [comment]
[Work is done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30406)

**Comment by michaelclement** [comment]
Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 Merged this into staging, should be ready for review shortly. Thanks!

**Comment by marywang2** [comment]
Not seeing the sign in option on staging yet.

**Comment by jamiefiore** [comment]
@marywang2 Same here, I don't see the sign in option yet

**Comment by michaelclement** [comment]
@jamiefiore @marywang2  
Updated 10-10d, 10-7959c, and 10-7959f-1 to show the sign in button in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30468) (see screenshots on GitHub)
Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 PR has been merged, should be viewable on staging shortly. Thanks!
