### ISSUE TITLE
Link to submit Okta Acount creation request is probably incorrect

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#85403]
### Description
For this text:
> If you are part of the DevOps CoP group on Platform, you must submit an [Okta account creation ticket](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/1016).

I believe that link is outdated and should be changed to https://jira.devops.va.gov/servicedesk/customer/portal/1/create/1233

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform team

**Comment by jknipes** [comment]
Hi @timcosgrove , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@timcosgrove we have completed the update, thank you for your suggestion. We are closing this ticket as _Done_
