### ISSUE TITLE
Life insurance rewriting batch 3: Dividend payment options

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8541]
# User story

As the VA life insurance policy holder, I want to understand my dividend options.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will be the 4th page within the "More resources" spoke.
- **URL (WIP):**/life-insurance/dividend-payment-options/
- **Left nav label:** Dividend payment options

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/insurance/dividends_options.asp
- **SEO keywords:** n/a
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Optimize page for keywords listed above
  - Recommend pulling the content out of the table and simply having h2s for each dividend option with "how it works" content beneath. Too much content for a table on mobile.
  - Note: The "special dividend rumor" link can link to where it currently links to, as that page will stay within legacy section for now. 
  
## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/dividend-payment-options.md

**Comment by DanielleThierryUSDSVA** [comment]
@lwalsh617 Just a note that the strategy guidance (per notes above) was to take the information out of the table because it's too much text for a table, especially on mobile. But it looks like it was written/built with the info still in the table...so we should definitely relook at that.

@mnorthuis This is a page I want to flag specifically for the IA/content strategy discussion. We don't seem to currently link to the legacy version from the life insurance hub page. We do, however, link to the [special dividend rumor page](https://www.benefits.va.gov/insurance/dividends_special.asp) (which we'd determined would stay as a legacy page for now because it's more "news") from the hub page. Do you recall why we don't link to Dividen Options, and what that means for IA?

**Comment by mnorthuis** [comment]
@DanielleSoCompany I don't recall why we don't currently link to it, possibly because it just didn't make the initial content cut for WBC, but my notes indicate that we intended to link to it under More resources once it is rewritten.  That page would then link to the legacy Special Dividend Rumor page within the body content.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @mnorthuis! That aligns with my notes as well...so yay :)

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
Closing this ticket. Added the Drupal preview link to [Life insurance rewriting batch 3: Content Review #12267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12267)
