### ISSUE TITLE
E2E test should fail on unexpected validation error

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#85434]
Currently in CI/CD if a Cypress E2E test is processing a form and encounters an unexpected validation error, the task does not fail, but hang until the process times out - this can take around 45 minutes.  This greatly hinders the development and merge process.  

- [ ] Update the E2E tests correctly exit the task when an unexpected validation error is encountered
- [ ] Reporting of failure should include the test and page/area/section of the form which failed

Additional:
- [ ] Have the E2E tests appropriately check for validation errors, instead of just the 'happy' path

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/85434?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel
