### ISSUE TITLE
Life insurance rewriting batch 2: TSGLI schedule

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8543]
# User story

As a Veteran with TSGLI, I need to understand the payment I'll receive for my specific loss.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will live within the "More resources" spoke (order tbd).
- **URL (WIP):**/life-insurance/uninsurable-medical-conditions/
- **Left nav label:** Uninsurable health issues

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/insurance/tsgli_schedule_Schedule.asp 
- **SEO keywords:** tsgli schedule of losses, tsgli standard for loss for adl
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Optimize page for keywords listed above
  - We need to take the legacy table, with links to various pop-ups, and create a simpler user experience that keeps all content on this page and easily accessible.

#### More on approach

For each row in the table, we'll create an accordion. Within each accordion, we'll have 3 subheads:
- **Loss** <br> Pull in the loss description from the **Loss** column
- **Payment** <br> Pull in the amount from the **Payment amount** column. Where there are different payments (shown as a table-within-a-table now on the legacy page), use bullets. 
- **Loss standards**  <br> Pull in the information from the related "View standards" pop-up and revise it to fit our standard approach to eligibility information, as shown in the example accordions.

#### Additional notes

- When there's additional information or a footnote, add it as a **Note:** at the bottom of the accordion.

- When there's no link to "loss standards," just leave that part out.

- For a loss such as **Facial reconstruction,** where there are multiple sub rows, use the main description for **Loss** and then use a bulleted list for each of the specific loss payments, such as:
  - **Jaw:** $75,000 <br> Defined as surgery to correct discontinuity loss of the upper or lower jaw.

- There's at least one pop-up that contains an image. Leave out for page.
- Also include a link to the PDF on the page.

  
## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/options-eligibility/tsgli/loss-standards.md
- **Heroku preview:** https://vagov-content-pr-386.herokuapp.com/life-insurance/options-eligibility/tsgli/loss-standards/

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
Put Drupal preview link and Word doc in ticket 11234. Closing this ticket.
