### ISSUE TITLE
Life insurance rewriting batch 2: Closed programs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8544]
# User story

As a Veteran with an older life insurance policy, I want to still have access to policy information I may need.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [ ] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [ ] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [ ] Finalize existing GitHub draft (Laura) 
- [ ] Migrate to Drupal (Laura)
- [ ] Add cross links to this page from other appropriate pages (Laura, Randi)
- [ ] Copy edit (Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will live within the "More resources" spoke (order tbd; place after "contact us" for now).
- **URL (WIP):**/life-insurance/closed-programs/
- **Left nav label:** Closed programs

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** We're merging the following pages into this 1 new page:
  - https://www.benefits.va.gov/INSURANCE/select.asp
  - https://www.benefits.va.gov/INSURANCE/usgli.asp
  - https://www.benefits.va.gov/insurance/vri.asp
  - https://www.benefits.va.gov/INSURANCE/vsli.asp
  - https://www.benefits.va.gov/INSURANCE/nsli.asp (include the information from this pop-up - https://www.benefits.va.gov/INSURANCE/popups/pua.htm - directly on the page)
  - https://www.benefits.va.gov/INSURANCE/capped_term.asp (include as relevant within the context of the NSLI and VSLI information)
- **SEO keywords:** n/a for now
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Consolidate the content from the 6 source pages into this 1 page.
  - Add related links to relevant pages (where there is a VA.gov page equivalent for a link that's currently going to a legacy page, please link to the VA.gov page; where there's not an equivalent yet on VA.gov, go ahead and keep legacy link for now)

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/closed-programs.md
- **Heroku preview:**  https://vagov-content-pr-386.herokuapp.com/life-insurance/closed-programs
- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/386

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by stephorkandatx** [comment]
@lwalsh617 please add an estimate to all the Batch 2 tickets. Thank you!

**Comment by MickinSahni** [comment]
Carrying forward to sprint 25

**Comment by lwalsh617** [comment]
I added the Drupal preview link and Word doc to ticket 11234
Am closing this ticket.
