### ISSUE TITLE
[CAIA A11y Research]: Veteran-facing forms, Form Upload (July 2024)

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#85447]
> [!NOTE]
> **High-Level Overview**: VFF (Veteran Facing Forms)
> - **Initial Kickoff**: `Date and Time TBD`
> - **Research Timeframe**: ~6/24 - 6/27/2024 - `Ideally`~ [Shifting to 7/8 - 7/18/2024 per 6/28 comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85447#issuecomment-2197546571) 
>   - ⚠️ **See Cautionary Note** Re: Conflicts in Testing Schedule section (found in this ticket)
> - **Time of Day:** Source of Truth [VFF Scheduling Canvas in DSVA Slack](https://dsva.slack.com/docs/T03FECE8V/F07AFT5FLTF)
> - **Pilot**:  6/18/2024 #85573
> - **Assistive Tech Users**: 5 AT Users (50% of the study)
> - **Artifacts Available**: Yes - `Requires Authentication`
> - **Testing Environment:** Staging `Req. Auth`
> - **Assistive Tech Being Used**: `Screen Readers` `Types JAWS + TBD`
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- Sara
-  SK - Pilot
- `TBD`

</details>

## About the Team

[DSVA Slack Thread Link](https://dsva.slack.com/archives/C8E985R32/p1718037085306769?thread_ts=1717710767.607809&cid=C8E985R32)

<details><summary>Toggle to view information about the team.</summary>

- **Team name**: Veteran Facing Forms
- **OCTO-DE product owner**: Matthew Dingee
- **Product manager:** Tricia Baker
- **Designer**: Rachel Shearer
- **FE engineer**: Eric Tillberg
- **Product/team Slack channel:** #veteran-facing-forms
- **Accessibility champion:** Jeana Clark

</details>

<details><summary>Toggle to view more intake research ticket information</summary>

### Is anyone on your team interested in becoming an accessibility champion?

**Rachel Shearer** - going through OAST Trusted Tester training currently 🙌

### Calendar checking

- [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [X] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

### When is the timeframe for your testing?

- ~Ideally 6/24 - 6/27~
- [Shifting to 7/8 - 7/18/2024 per 6/28 comment]
</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

<details><summary>Toggle to view research timing information.</summary>

### Timeframe

- **Pilot Session**:  6/18/2024 #85573
- **Timeframe**: ~`6`/24`/2024 - `6`/`27`/2024~ [Shifting to 7/8 - 7/18/2024 per 6/28 comment]

### Length of sessions

- **Session length:** `90` minutes
- **Buffer time between sessions:** `30` minutes
- **Maximum sessions per day:** `3`

</details>

###  Testing Schedule

> [!CAUTION]
> #### LIMITED CAPACITY 7/5-7/17
> - There will be limited CAIA A11Y capacity 7/5-7/12, with 75% (3) of CAIA A11Ys OOO. 
> - There will be 75% (3) CAIA A11Ys available 7/15-7/17 and 100% (4) available 7/18, 7/19 and the week of 7/22. 
> #### Dates with No Conflicts
> - There is currently no coverage conflict for: 7/23+

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

Please toggle and use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

#### Source of Truth
[VFF Scheduling Canvas in DSVA Slack](https://dsva.slack.com/docs/T03FECE8V/F07AFT5FLTF)

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available | STATUS
------------------|------------------|--------------|--------------|--------------|--------------|--------------|--------------
[PILOT](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85573) | 6/18/2024 11 a.m. to 12 p.m. | JAWS | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 | `COMPLETED`
P3 | 7/9/24, 1:30 - 3:30 p.m. ET | Screen Magnification | Desktop | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | NA | `NA`
P5 | 7/10/24, 2:30 - 4 p.m. ET | VoiceOver | Mobile iOS | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @sara-amanda | `NO SHOW`
P7 | 7/11/24, 2:30-4 p.m. ET | TalkBack | Mobile Android | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 | `PENDING`
P14 | 7/16/24, 3-4:30 p.m. ET | VoiceOver | Tablet (iPad) iOS | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` |  @SarahKay8 | `PENDING`
P15 | 7/17/24, 12 - 1:30 p.m. | JAWS, Fusion | Desktop; Windows | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 | `PENDING`

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Product%20Outline%20File%20Upload.md)
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712956678497/a6c9c95e6dafa6eb641566aec68c8fc6c74fced6?wid=12-1660829303201)
- [Prototype or mockups - **Note**: Requires authentication to access](https://staging.va.gov/form-upload/21-0779/upload)**
- [Research plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Research%20/Research%20plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Research%20/Conversation%20guide.md)
- [Form Upload collab cycle](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/80689)
- [Form Upload product epic](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1167)
- [Notetaking Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715192973802/81653cc9c8abcdc6d5ec9b396d89880eb2e71b0e?sender=u947c25618d9d69f7fa7d5512)

</details>

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket
- [x] **INITIAL MEETING:** Schedule meeting with team
- [x] **PILOT SESSION: SCHEDULE** Pilot session with team. `IDEALLY 6/17-6/21/2024 TIMEFRAME` 6/18 at 11 a.m. scheduled with SK
- [x] **PILOT SESSION: CREATE TICKET** Link ticket in this task list. #85573
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available.
- [x] Update calendar holds with new dates 7/8 - 7/18/2024 (on 7/1/2024)
- [x] Update Research Outlook Tracker (original dates)
- [x] Update Research Outlook Tracker with new dates 7/8 - 7/18/2024 (on 7/1/2024)
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean) updated with 5 sessions by SS on 7/8/2024
- [x] **RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1Mq28Pp6XuBTWLzS9YEOwNEJJnV1478lLExprm4ggi2U/edit?usp=sharing)
- [x] [VFF Team - Notetaking Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715192973802/81653cc9c8abcdc6d5ec9b396d89880eb2e71b0e?sender=u947c25618d9d69f7fa7d5512)
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support. Team made aware of research 6/10/2024. Session times/AT available and sent to team on 7/8/2024 - limited availability; SS assisting with scheduling 7/8/2024.
- [x] **Review research folder and assets**
- [x] **Participate in research** **Date Span:**`7/8/2024` and `7/18/2024`
- [x] **SESSION NOTES**: Create CAIA [notes document](https://docs.google.com/document/d/1Mq28Pp6XuBTWLzS9YEOwNEJJnV1478lLExprm4ggi2U/edit?usp=sharing) for a11ys to use during the sessions
- [x] **SYNC:** Connect with CAIA A11ys on research findings `meeting 7/23/2024`
- [x] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA  -supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket. (See ticket comment 7/29/2024)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85573
```

```[tasklist]
### VFS TEAM Tasks
- [x] Tag @coforma-terry in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH)-  [DSVA Slack Thread Link](https://dsva.slack.com/archives/C8E985R32/p1718037085306769?thread_ts=1717710767.607809&cid=C8E985R32)
- [x] Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired
- [x] Schedule a pilot session with CAIA a11ys - `VFF reached out via Slack for pilot 6/17-6/21 timeframe` #85573
- [x] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section
- [x] **DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. RCVD Updated by SS 7/8/2024 in table
- [x] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in `Table` in the ticket above.
- [x] **AT INFO.** Self-assessed skill levels and browsers being used in the AT sessions needed, if available
- [x] **INVITES:** Forward invites from Perigean to CAIA A11ys (Sara or Terry)
```

**Comment by sara-amanda** [comment]
## Pilot Scheduled
- Pilot to take place on 6/18/2024 at 11 a.m. with @SarahKay8 
    - Pilot session will be using JAWS. 
    - Invitation has been sent. 
    - This has been added to the CAIA A11Y Capacity Calendar. 
- Ticket updates:
    - This ticket has been updated. 
    - Task lists have been updated.
    - See pilot ticket for details: #85573

**Comment by rachelshearerux** [comment]
Hey @sara-amanda, fyi our [study's](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/581) been officially approved and we've connected with Perigeanto start recruiting! Our study dates are July 8th  - 18th.

**Comment by sara-amanda** [comment]
## Timeline Shift
- **Original Testing Dates:** 6/24 - 6/27/2024
- **Revised Testing Dates:** 7/8 - 7/18/2024

### CAIA Updates
- [x] Holds adjusted on [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?height=600&wkst=2&ctz=America/New_York&bgcolor=%23B39DDB&mode=WEEK&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23616161)
- [x] Dates adjusted in this ticket and this ticket's tasks
- [x] Dates adjusted in CAIA research tracker
- [x] Adding in cautionary statement to ticket body, due to overlapping studies

> [!CAUTION]
> #### LIMITED CAPACITY 7/5-7/17
> - There will be limited CAIA A11Y capacity 7/5-7/12, with 75% (3) of CAIA A11Ys OOO. 
> - There will be 75% (3) CAIA A11Ys available 7/15-7/17 and 100% (4) available 7/18, 7/19 and the week of 7/22. 
> #### Dates with No Conflicts
> - There is currently no coverage conflict for: 7/23+

cc: @NaomiPMC @SarahKay8

**Comment by sara-amanda** [comment]
## Scheduling Canvas

**Source of Truth:** [2024-07 Usability Study Veteran Form Upload - Observer Sign-Up Sheet Canvas in DSVA Slack](https://dsva.slack.com/docs/T03FECE8V/F07AFT5FLTF)

### CAIA A11Y Updates

- [x] CAIA A11Y Capacity Calendar Updated
- [x] VFF Canvas Updated to Reflect CAIA A11Y Coverage
- [x] This Ticket's Schedule Table Updated to Reflect CAIA A11Y Coverage
- [ ] CAIA A11Y Research Tracker

**Comment by sara-amanda** [comment]
## Additional Test User

- Per Rachel, on 7/18/2024, **Perigean found another screenreader user for a session on Friday, at 10am ET.** 
    - Adding to ticket, tracking, calendars and notes docs. 
    - I can take this one, but will need to shift our A11Y Meeting.

**Comment by sara-amanda** [comment]
# Research Feedback: Users of Assistive Technology 

**Ticket Status:** `Closing out ticket`

## Participants
- **Recruited:** 11 users of assistive technology
- **Successful Sessions:** 1
- **Partially Successful Sessions:** 2 (via Q&A)
- **Remainder of Participants:** 8 (no shows, or did not use AT in the session)

## Aggregated Feedback
**Feedback provided via:**  Feedback Channel in DSVA Slack, Raw CAIA Notes Document and Retro Meeting
- Feedback for the VFF Form Upload and the Form Status AT Sessions was given during a scheduled Zoom retro call. 
    - [That feedback was gathered and documented via Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721424603314/9b384db7e9a6136b7b59e6a1bd0c7ba2499e6b73?sender=ud94436ff2bf5d5ce166a5253) on Tuesday, July 23, 2023 from 1:00 – 1:45pm ET. 
- The retro feedback was then used by the VFF teams in the presentation given on Monday, July 29, 2024 at 1 p.m. ET. 
    - [There is a PDF document with the presentation slides ](https://dsva.slack.com/files/U049MQKDTT3/F07EG5D7KAR/2024-05_vff_and_my_va_form_submission_research_findings.pdf). 
    - There is additional [Q&A in the #design slack channel on 7/229/2024](https://dsva.slack.com/archives/C0NGDDXME/p1722258012583309). 
- CAIA feedback can also be found woven into the research findings in GitHub: [Forms/DocumentUpload_FindaForm/Research ](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Forms/DocumentUpload_FindaForm/Research%20)
