### ISSUE TITLE
Life insurance rewriting batch 3: Enroll in VGLI auto pay

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8545]
# User story

As a Veteran with a VGLI policy, I want to enroll in auto pay.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will live within the "Manage your policy and benefits" spoke as the 7th link.
- **URL (WIP):**/life-insurance/enroll-vgli-autopay
- **Left nav label:** Enroll in VGLI auto pay

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/INSURANCE/vgli_auto_pay.asp
- **SEO keywords:** n/a for now
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Add cross links to page as relevant

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/enroll-vgli-autopay.md
- **Heroku preview:** https://vagov-content-pr-386.herokuapp.com/life-insurance/enroll-vgli-autopay
- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/386

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
Closing this ticket. Added the Drupal preview link to [Life insurance rewriting batch 3: Content Review #12267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12267)
