### ISSUE TITLE
AWS access for Adrian Jones

### ISSUE THREAD

**Issue by ajshred** [department-of-veterans-affairs/va.gov-team#85452]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Adrian Jones

### Your Email

adrian.jones@adhocteam.us

### Team, Role, and Company of the target individual

Team Quokka, Engineering Lead, Ad Hoc LLC

### Product Manager (PM) name and email

Nate Peterson nate.peterson@adhocteam.us

### Product Owner (PO) name and email

Peter Tebbenhoff, peter.tebbenhoff@va.gov

### Desired AWS Access

I need the same access as Krutarth Joshi from Team Quokka.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot from 2024-06-06 11-59-45](https://github.com/department-of-veterans-affairs/va.gov-team/assets/84713593/44463a56-17e2-42c3-8893-25071db30a08)

### Additional Notes

I need access for developing and maintaining the Lighthouse dev portal and Kong Gateway.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Sorry for missing this! I'm following AWS instructions on our side and it seems like you are not on `Atlas` or the `Platform Roster` 

> If the user is on a VFS team but not in Atlas, add the NOT YET label and instruct them to start the Platform orientation process [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html). 

Is it possible for you to complete this then we can get you added.

**Comment by ajshred** [comment]
> Sorry for missing this! I'm following AWS instructions on our side and it seems like you are not on `Atlas` or the `Platform Roster`
> 
> > If the user is on a VFS team but not in Atlas, add the NOT YET label and instruct them to start the Platform orientation process [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html).
> 
> Is it possible for you to complete this then we can get you added.

@stoiven I thought it was shown to not be necessary for lighthouse members to go through this.  We established this previously for SOCKS access.  Here is my link as member of Team Quokka -> 

https://www.va.gov/atlas/product_directory/teams/252?filter=members

We need to see what needs to happen to codify this as official process for Quokka members.

**Comment by stoiven** [comment]
Sorry, I was looking at the wrong Atlas instance.

@ajshred I slacked you info about AWS

**Comment by stoiven** [comment]
Access granted and tempo creds passed to user
