### ISSUE TITLE
[Epic] eMail veteran when Form 4142, Form 0781 or Form 0781a failed to upload

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#85467]
As a follow on to our fix for [Veteran-uploaded documents we fail to submit to EVSS]( https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/81612), adds mailers to send to the veteran whenever we fail to upload a Form 4142, Form 0781 or Form 0781a in support of a Form 526 submission. The mailer will provide instructions for the veteran to take action and provide this information in a different way.

**Comment by lisacapaccioli** [comment]
@juliepedtke - This Epic has an upstream dependency on R&D for email content for each of the mail notifications needed. I am not sure if the plan was to use three different ones, or one that could be used in either of the three cases where the failure might happen. We should add a ticket for R&D work to this Epic as well, so we can track it. Thanks (cc @NB28VT)

**Comment by NB28VT** [comment]
> @juliepedtke - This Epic has an upstream dependency on R&D for email content for each of the mail notifications needed. I am not sure if the plan was to use three different ones, or one that could be used in either of the three cases where the failure might happen. We should add a ticket for R&D work to this Epic as well, so we can track it. Thanks (cc @NB28VT)

@juliepedtke and @nnicholas7 already did this work actually! So that's fortunately already done.

**Comment by NB28VT** [comment]
Note implementing the Form 0781 and Form 0781a is going to be problematic as I mentioned a few weeks ago. Both are intertwined in the same job, and the only real way to hook up this behavior properly is to split them into two jobs, which is a bigger lift (building and testing two new jobs) and a bigger risk.

We will want to weigh that work against how important it is we provide notifications in the PTSD cases, as those uploads should not fail unless something is broken on our end. Also, since we are redoing all of the Form 0781 behavior  anyway.

Happy to explain what I mean above in a project sync at some point as it may not be clear here.

**Comment by lisacapaccioli** [comment]
Thomas had a different idea for this Epic. Since the problem is on the backend failing to upload the document to the endpoint, it should require an internal remediation. Instead of notifying the Veteran that our system failed to do it's job, we instead create an alert for Watchdog and identify the issue and resolve through the backend. Will discuss with VA partners.

**Comment by lisacapaccioli** [comment]
Emily commented today that she wants to keep this as is using the mailer vs. just an alert. The feeling is that if we notify the Veteran/User that the system had a problem and to take their own action, is a safer response to the problem than waiting for a fix. This way the Veteran/User is notified as soon as possible and that seems to be the VA's and OCTO's biggest concern at this time. Fixing any issues or managing any Watchdog pieces is not part of this Epic. Those will have to be handled differently. For now we will have 3 email notifications.

1.  4142
2. 0781
3. 0781a 
(where the information in the emails for 0781 and 0781a may be the same, they are triggered at different times). 

Where 4142 may have less value, it has the smallest lift and would be beneficial to get that out as early as possible. 
0781 and 0781a will require more discovery on how to manage these separately. 

The team should plan any collaboration cycle work early on to make the progress to production quicker. We want to avoid as many road blockers as possible so it's more seamless.

**Comment by lisacapaccioli** [comment]
@juliepedtke, Could you please add tickets for tracking any collaboration pre-production work that R&D will need to do for these emails? If there is anything that R&D need to do, better than we plan early and attempt to get them done ASAP so as to not hold up the release and avoid road blockers. 

@NB28VT, Please take the time to plan out as many tickets as you can so we can more accurately know how long the entire epic will take. 

Thanks

**Comment by juliepedtke** [comment]
Ok, so we're back to the original plan. These emails are reviewed and ready to go, pending any changes in our approach. 

We're still planning to launch the Veteran-upload email first, correct? If so, I assume we should update the product guide and refer only to that email at first, then submit another round of updates when we're actually launching the following emails?

Product guide updates are being tracked in [this ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/81504), we can split out another ticket for the following emails if desired!

**Comment by lisacapaccioli** [comment]
Yes, split the work up if we have to track them all separately. If we can do one for all (even if we are releasing them at separate times), then even better. Basically we just need to make sure we plan the work vs. waiting until the last minute and add unplanned work. Thanks
