### ISSUE TITLE
Life insurance rewriting batch 2: Financial counseling

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8546]
# User story

As a Veteran with a VA life insurance policy, I want to know how to access the free financial planning and online will preparation services I'm entitled to.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [ ] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [ ] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [ ] Finalize existing GitHub draft (Laura) 
- [ ] Migrate to Drupal (Laura)
- [ ] Add cross links to this page from other appropriate pages (Laura, Randi)
- [ ] Copy edit (Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will be the 3rd page in the "Get benefits" spoke.
- **URL (WIP):**/life-insurance/financial-counseling/
- **Left nav label:** Financial counseling and online will prep
- We'll also cross link to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:**  https://www.benefits.va.gov/insurance/bfcs.asp <br> Note that there may also be info in https://www.benefits.va.gov/INSURANCE/forms/BFCSBrochure1.htm and https://www.benefits.va.gov/INSURANCE/forms/BFCSBrochure2.htm
- **SEO keywords:** n/a 
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran).
  - Implement VA.gov approach to how to apply info (look at existing how to apply pages in other benefit hubs for examples)
  - Add related links to relevant pages

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/financial-counseling.md
- **Heroku preview:** https://vagov-content-pr-386.herokuapp.com/life-insurance/financial-counseling
- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/386

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
Put Drupal preview link and Word doc in ticket 11234. Closing this ticket.
