### ISSUE TITLE
Order of operations for phase 1 launch

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#85465]
# Monday 6/24 after 10 am

1. Publish all pages. Confirm all the URLs are correct before hitting publish. Do not select "Provide a menu link." 
2. Notify PW when pages are live, so they can merge the redirects before the Tuesday 6/25 10 am deploy.

**Main hub page:**
- [x] [Family and caregiver benefits](https://prod.cms.va.gov/family-and-caregiver-benefits) URL: va.gov/family-and-caregiver-benefits/

**Landing pages:**
- [x] [Health](https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability) URL: va.gov/family-and-caregiver-benefits/health-and-disability/
- [x] [Education](https://prod.cms.va.gov/family-and-caregiver-benefits/education-careers) URL: va.gov/family-and-caregiver-benefits/education-and-careers/
- [x] [Survivor comp](https://prod.cms.va.gov/family-and-caregiver-benefits/survivor-compensation) URL: va.gov/family-and-caregiver-benefits/survivor-compensation/
- [x] [Life insurance](https://prod.cms.va.gov/family-and-caregiver-benefits/life-insurance) URL: va.gov/family-and-caregiver-benefits/life-insurance/
- [x] [Burials](https://prod.cms.va.gov/family-and-caregiver-benefits/burials-memorials) URL: va.gov/family-and-caregiver-benefits/burials-and-memorials/
- [ ] [Housing](https://prod.cms.va.gov/family-and-caregiver-benefits/housing-assistance) URL: va.gov/family-and-caregiver-benefits/housing-assistance/

**Detail pages:**
- [x] [CHAMPVA benefits](https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability/champva) URL: va.gov/family-and-caregiver-benefits/health-and-disability/champva/
- [x] [PCAFC program English page](https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers) URL: va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/
- [x] [PCAFC program Spanich page](https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp) URL: va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/

# Tuesday 6/25 after 10 am

- [x] Confirm all redirects are live
- [x] Add menu for Family and caregiver benefits hub: 
<img width="359" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/9a318a7b-5ecc-46a8-a895-f058ad3c713a">

- [x] Add menu links to all newly published pages and republish all new pages to push the menu changes live
- [x] In the Family and caregiver benefits hub menu, reorder pages as needed and save changes
- [x] Remove menu links from all redirected pages
- [x] Confirm PCAFC form is live at new url, point static page to new url, add form to left nav

**Comment by laurwill** [comment]
@kristinoletmuskat I created this ticket to record order of operations for publishing on Monday 6/17. Let's talk about this in our sync today and confirm steps and order.

**Comment by kristinoletmuskat** [comment]
Closing this out since we are done with phase 1!
