### ISSUE TITLE
Schedule and conduct pilot session for evaluative & Figma prototype research

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#85471]
## Tasks

- [ ] [Schedule and conduct pilot session with Veteran](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) for evaluative & Figma prototype research
- [ ] Make adjustments to Figma prototype and/or conversation guide based on pilot session findings

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/85471?planning-poker) with Zenhub @cgednalske

**Comment by cgednalske** [comment]
@benbrasso-agile6 you or @Cieramaddox might need to have the pilot session while I'm out. I don't think the timing will line up for me to be there. 👀

**Comment by benbrasso-agile6** [comment]
No prob, thanks for pointing.
