### ISSUE TITLE
Life insurance rewriting batch 3: About SOES

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8547]
# User story

As a service member, I need to understand the new SOES and how it affects me.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This will now be the 1st page within the Additional Resources spoke.
- **URL (WIP):**/ life-insurance/about-soes/
- **Left nav label:** SGLI Online Enrollment System
- We'll also crosslink to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/INSURANCE/SOES.asp 
- **SEO keywords:** SOES, sgli online enrollment system
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Optimize page for keywords listed above
  - Be sure to highlight relevant deadlines
  - Add related links to relevant pages
  - We'll want to rewrite this so that it doesn't feel like it's as much news oriented (ie, replace language like "now live" and "beginning october 1, 2018), but rather make it an evergreen page about the program.
  - Do not link to this graphic for now (https://www.benefits.va.gov/INSURANCE/images/SOES_Before_After_Graphic.pdf). But you can look at the copy and determine if it's useful on the page itself. 
  - Look at the existing [SGLI page](https://www.va.gov/life-insurance/options-eligibility/sgli/) and [FSGLI page](https://www.va.gov/life-insurance/options-eligibility/fsgli/) for ideas on language about SOES, and determine if we can/should avoid duplication.
  - Incorporate a link/description to this new "About SOES" page on the [Access your policy online page](https://www.va.gov/life-insurance/manage-your-policy/).

## Github files for reference

- **Current page in GitHub:**https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/about-soes-rewrite-lw.md
- **Heroku preview:** https://vagov-content-pr-386.herokuapp.com/life-insurance/about-soes-rewrite-lw/
- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/386

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
Closing this ticket. Added the Drupal preview link to [Life insurance rewriting batch 3: Content Review #12267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12267)
