### ISSUE TITLE
Midpoint Review - IA Feedback - IVC Forms, 10-7959a, CHAMPVA Claim form

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#85482]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Must: continue to work with CAIA**: thanks for sharing your IA spec from CAIA! Please continue to work with them to identify entry points, page titles and H1's, breadcrumbs, etc.

- [x] **Must: only open links in new tab if they're within the form flow** I saw "(opens in a new tab)" on a few links in the Figma mockups. The (somewhat buried) [guidance for when links need to open in a new tab](https://design.va.gov/components/link/#behavior) is, "only if clicking the link will result in the user losing progress or data" - so, not needed before the form flow has started. 

- [ ] **Should: offer way to view status of submitted claim** How might (authenticated) users who have submitted a claim be able to determine its status after the fact? Y'all shared yesterday that this isn't possible now, but is on your roadmap. We are beginning to encourage teams to account for the post-submission process for forms as well, so I encourage you to keep it prioritized.
    
- [x] **Consider: adding an explanatory step before medical path** I love that y'all are using the "now we're going to ask you about your claims" screen before beginning the Add Claim flow. When users are going through the medical claim path, they're going to postentially see up to three content-heavy screens asking them to upload documentation about their claim. Consider putting in another message right before the [medical path](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=734-38071&t=Cj5LYZcNwah23BuF-4) to the effect of, "Now we’ll walk you through submitting your claim(s). For each claim, we’ll ask for your medical bill, and documentation from each of your insurance providers." and remind folks that (if signed in) they can save their progress and return later if they need to.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by syd-hoeper** [comment]
Commenting that feedback has been addressed and implemented, but we are still waiting for CAIA to provide their second round of feedback, so that "must" bullet is not yet complete (though they did do an initial round). We are not going to add the explanatory step before the medical path because we've updated the flow to only allow for one claim -- because of this the flow is simpler and it's less necessary to have those primer screens.  Also we have it on our radar to provide status of a submitted claim to users, but that's not possible at this time due to technical constraints
