### ISSUE TITLE
Life insurance rewriting batch 1: Insurance plans

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8548]
# User story
As a Veteran or family member, I want to know about all of my life insurance plan options.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi, Danielle, Beth as needed)
- [x] Finalize existing GitHub draft (Laura) 
- [ ] Strategy/voice edit (Danielle)
- [x] Migrate to Drupal (Laura, Randi)
- [ ] Add cross links to this page from other appropriate pages (Laura, Randi)
- [x] Copy edit (Randi)
- [ ] Platform review (content and accessibility, possibly design) 
- [ ] Package with other Life Insurance batch 1 pages and send to SMEs for review (Laura, Danielle)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This will now be the 5th page within the "More resources" spoke.
- **URL (WIP):** tbd
- **Left nav label:** Life insurance plans
- We'll also crosslink to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/insurance/plans.asp
- **SEO keywords:** Veterans life insurance
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran)
  - Optimize page for keywords listed above

## Github files for reference

- **Current page in GitHub:**https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/plans.md
- **Heroku preview:** https://vagov-content-pr-386.herokuapp.com/life-insurance/plans/
- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/386

**Comment by lwalsh617** [comment]
Should discuss this page further. May need some additional content.

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting: Move this page to resources section since it applies to more than old plans.

**Comment by lwalsh617** [comment]
@RLHecht -- Here is the phase/batch 1 working doc with Drupal links. 
[life-insurance-rewriting-phase1_v1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4732290/life-insurance-rewriting-phase1_v1.docx)

**Comment by RLHecht** [comment]
@lwalsh617 I've reviewed all the life insurance pages in the copy deck you put in the comment above. I added some comments/questions to the copy deck. Figured it was the best place to keep track of it all: 
[life-insurance-rewriting-phase1_v1-RH edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4737309/life-insurance-rewriting-phase1_v1-RH.edit.docx)

**Comment by lwalsh617** [comment]
@RLHecht  - I will add those anchor links you mentioned and check the "20 Months" language as soon as I can get into Drupal. Thanks!

**Comment by stephorkandatx** [comment]
Closing this ticket out - future edits, updates will be written and handled in a new ticket. This batch was submitted for content review
