### ISSUE TITLE
[Design] Incorporate Call Center Data into "Grey Sky" Prototype

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#855]
## User Story
As a product health tool user, I need to see current call center data so I can incorporate call centers into my product prioritization and decision making.

## Goal
Amy and Chante to meet and verify call center data that should be added to product health tool.

## Acceptance Criteria
- [x] Chante provides available call center data
- [x] Chante and Amy meet to verify data
- [x] Amy incorporates "test" data into blue sky product health tool
- [x] _Stretch_ Amy incorporates data into "grey sky" product health tool

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@amycesal @clantosswett Making sure this is getting scheduled.

**Comment by joanneesteban** [comment]
Initial conversations and data sharing completed - data will get incorporated to Grey Sky.

**Comment by amycesal** [comment]
Prototype with REAL DATA!

<img width="1017" alt="Screen Shot 2019-10-01 at 12 51 35 PM" src="https://user-images.githubusercontent.com/1656046/65986815-43570500-e44a-11e9-8b1c-02bef3c28060.png">

**Comment by joanneesteban** [comment]
All AC plus stretch goals completed. Thanks, Amy & Chante!
