### ISSUE TITLE
Midpoint Review - Content - Collaboration Cycle for IVC Forms, 10-7959f-2, Foreign Medical Program Claim Cover Sheet

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#85500]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions
Overall, this looks good. I just have some feedback about formatting. Please continue to work with CAIA on this language. If you have any questions, please let me know.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- [ ] Section 6 - Payment selection: The user sees two bolded answer choices. However, the second choice is as follows: “Or, select the Provider option…” This use of bolding is unaligned with the [Style Guide](https://design.va.gov/content-style-guide/bold-text). 
I suggest the following:
Select the **Veteran** option if you have already paid for the care received. Payment will be sent to your mailing address.

Or, select the **Provider** option if the care received has not been paid for. 

- [ ] Section 3: The user is asked if their mailing address is the same as their home address. The question appears to be bolded. Please revise by un-bolding it.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by brian-wilke** [comment]
Moving this to In Progress for this sprint (Sprint 20)

**Comment by brian-wilke** [comment]
These "MUST" text and styling changes have been made to the figma file.
