### ISSUE TITLE
Create April Contact Center Report

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8550]
## User Story or Problem Statement
How might we show what users are calling in about for VA.gov so that VFS teams can prioritize their work in towards human-centered decisions?

## Goal
Create April Contact Center report.

## Acceptance Criteria
- [x] Create April contact center report
- [x] Share out reports in #vfs-analytics

**Comment by joanneesteban** [comment]
@clantosswett @Kimberley2019 how's the April contact center report going?

**Comment by Kimberley2019** [comment]
@joanneesteban, there are a few kinks that need to be worked out that @clantosswett is looking into.
Once those items are completed and reviewed, it should be good to go.

**Comment by clantosswett** [comment]
We created one report for April and May. Can be accessed here: https://domo.buzz/r/wAVKokP
