### ISSUE TITLE
SPIKE: Research Concatenation Effect on Custom Dimensions

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#8551]
# Analytics Implementation or QA Request

## Description 
- Research the effect of concatenating multiple dataLayer variables into one custom dimension
- Determine the trade off of this format vs individual custom dimensions for every value
- Determine if this is a pathway for us moving forward for forms where there are multiple DL variables (values) stakeholders need to understand

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Some sample concatenated data I added the other day...

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:Transactions,analytics.eventAction:Forms%20-%20Disability%20-%2021-686c%20-%20Submission%20-%20Successful

Is this what you were thinking?

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/a35ba63d-62a7-46aa-9c0e-889c0b892ab0)

**Comment by joanneesteban** [comment]
Work is being done on #686. Closing this ticket.
