### ISSUE TITLE
Midpoint Review - Design Feedback - Unified Appointment Experience, Appointments, Community Care Direct Scheduling

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#85515]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: Work with accessibility on the filter results. Instead of "4 results", try "Showing 1-10 of 11 results for "health"
- [x] Must: I see the reset filters is the new button icon. Per [our guidance](https://design.va.gov/components/button/button-icon#usage),  button icons are to be used in a Card or other container alongside a primary link. Unfortunately this will need to be a secondary button.
- [x] Must: Several teams have been working on "filters" for content. We really do not have a great pattern. I would suggest you submit this to [experimental design](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update).

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by benbrasso-agile6** [comment]
@allison0034 no feedback or still populating?

**Comment by benbrasso-agile6** [comment]
Oh, sorry. I see it, doh.

**Comment by allison0034** [comment]
@benbrasso-agile6 sorry, I got it in late today, I needed to confirm something with Matt. Just let me know if you have any questions.

**Comment by benbrasso-agile6** [comment]
> Work with A11y on results

[Done](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2424-42620&t=4LNO4gXSPPPUrflA-4)

> Can't use button icon

[Changed it](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2439-52550&t=4LNO4gXSPPPUrflA-4)

**Comment by benbrasso-agile6** [comment]
Will leave this ticket open to work on the experimental ticket

**Comment by Cieramaddox** [comment]
@allison0034  I'd like to get an opinion on changes I've made to the filter page actions.

I received guidance for Sara Sterkenburg regarding the cancel action - making it a link rather than a button. 

> I would just make cancel a link in this case. Apply can be a button since it is saving data and navigating (same rules as "continue" buttons in forms).



With that in mind, I've come up with this as a solution (solving some of the visual issues with buttons on buttons on buttons). The left shows what we had previously. The right shows the updated design.

<img width="1484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6331dc358613c4f98c01987e5b9ea0397ed5a2e7/Screenshot%202024-07-01%20at%2011.12.30%E2%80%AFAM.png" alt="Screenshot 2024-07-01 at 11.12.30 AM.png" />

**Comment by allison0034** [comment]
Hi @Cieramaddox , does "Cancel" navigate? Pulling in @briandeconinck since he will know best.

**Comment by benbrasso-agile6** [comment]
Depends on the definition of navigate. It does navigate the user back to the last screen, while it also cancels/stops that sub-task from being completed.

**Comment by allison0034** [comment]
Ok, it may be something you want to actually walk @briandeconinck thru the flow.

**Comment by briandeconinck** [comment]
I think a link is appropriate here. Sara hit the distinction exactly right: does clicking the element change user data? Button. Does it just move you to a different screen? Link. I believe the Veteran Facing Forms team has something in the works that will eventually follow that pattern with the forms library, with the Back button becoming a link.

**Comment by Cieramaddox** [comment]
Wonderful, thank you!

**Comment by benbrasso-agile6** [comment]
Pattern submitted, will ping Carol after other VFS team members have weighed in: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3185

**Comment by benbrasso-agile6** [comment]
DSC on Aug 29

**Comment by benbrasso-agile6** [comment]
Not presenting at DSC on Aug 29. 

OCTO-DE would like VFS Teams to collaborate on the pattern. Knowing this, it's likely one or more than 1 product is released prior to presenting the proposed pattern to DSC. E.g., this collab cycle work has a congressional mandate deadline to hit.
