### ISSUE TITLE
Midpoint Review - IA Feedback - Unified Appointment Experience, Appointments, Community Care Direct Scheduling

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#85523]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through! Lots of good work since the last time we saw you. Excited to see a search design coming through collab cycle.
- Thanks for including unhappy paths!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

> [!NOTE]
> All of my feedback is about the [provider results screen](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1899-75962&t=ikqrZvoZiFzelLQu-4).

- [x] **Must: include a button to apply sort** I didn't spot this before or during our call and @briandeconinck might note it too. There should be a button next to or below the "sort" dropdown that applies the sort to the results; the results should not change when the selected item in the dropdown changes. [Find a rep](https://staging.va.gov/get-help-from-accredited-representative/find-rep/?address=02920&lat=41.782692&long=-71.464874&page=1&perPage=10&sort=distance_asc&type=veteran_service_officer&name&distance=50) has a good example of how to do this. This allows users more control over the sorting action has accessibility implications too.

![Screenshot 2024-06-07 at 3 08 37 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/038e487b-3534-4e8c-9657-96f23361d1f3)

- [x] **Must: update "results" text to be more descriptive** When sort and/or search filters are applied, the text above the list of results should change, indicating what filters or sort were applied. Something like "4 results, sorted by distance" / "Results 1-10, ordered by name, with filters applied" This text should also receive focus on page load (Brian will likely give guidance about this!)

- [x] **Should: filter availability by date range rather than single date** this is likely a technical limitation; however, I'd be interested to see if user research indicates that folks are hoping to search by a date range rather than a specific date. If a Veteran is looking for an appointment, say, the week after next - they would need to search for an appointment for *each individual day* that week. Five filter adjustments, five searches.

- [x] **Consider: sort by availability** during the meeting the team shared the technical limitations of being able to get availability data for sorting. If this changes in the future, a sort by soonest available would likely be a big win.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by benbrasso-agile6** [comment]
> **Consider: sort by availability**

This will continue to be a limitation of the external system, WellHive. Right now, there's no plan for them to support this number of API calls.

**Comment by benbrasso-agile6** [comment]
> Should: filter availability by date range rather than single date

This won't be feasible with the external system, WellHive. Right now, there's no plan for them to support this number of API calls. 

It's possible we write some logic to say, "if less than 10 providers, show date range filter." This, I think, would be acceptable to WellHive. If the initial list is more than 10 providers, I don't think we can have a date filter available. cc @Cieramaddox

**Comment by benbrasso-agile6** [comment]
> Must: include a button to apply sort 

[Addressed in design comp](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2439-52550&t=4LNO4gXSPPPUrflA-4)

> Must: update "results" text to be more descriptive

[Addressed](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2424-42620&t=4LNO4gXSPPPUrflA-4)
