### ISSUE TITLE
Verifying accounting for all statuses for Past Appointments

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8553]
## What happened?
When user navigated to Past Appointments, they were able to see an appointment with status 'Confirmed.'
Veterans should not be able to 'confirmed' status for past appointments. 

## Steps to Reproduce
- In prod - navigate to Past Appointments
- if user has past appointments that show a combination of appointment statuses (instead of just one as previously thought) they will display an undesirable status in the UI - for this user is was 'confirmed appointment'

Screenshot from Prod User's Past Appointment:
![image (1).png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/1f668d5a-55e9-489d-8b13-82d071fc5924)

## Desired behavior
- Need to confirm all the various combinations of status that can be displayed (see all 'status' types in AC)
- We should only show the appropriate statuses as described in the AC below

## Acceptance Criteria
- Status should follow this criteria for Past Appointments
- New: We will show a status of "Completed" for some appoint statuses/combos (see below)
![Screen Shot 2020-05-05 at 1.52.40 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/17b127f1-c90e-4e0a-b162-697519325dd4)

(Updated Status doc with new statuses in [Sheet 2](https://docs.google.com/spreadsheets/d/1BJ8FJTNDfiWjqhs-xIQ-nQaw6RXMxXdU2CV0EvCfJhI/edit#gid=1413660998))

**Comment by lenaecb** [comment]
@lalexanderson-dsva - want to confirm that you are good with my suggestion here for handling the combos (see Acceptance Criteria)

**Comment by lenaecb** [comment]
@narin - I have updated this ticket. As you can see, in auditing what is believed (from multiple sources) the full list of statuses including combinations, we've also made some updates to a few statuses given the actual definition/purpose of the status. 

Let me know if you have any questions about this.

Marcy isn't sure how we can fully test these statuses because she doesn't have this exhaustive of a list.

**Comment by lenaecb** [comment]
cc: @lalexanderson-dsva @rtwell sharing for transparency. AC will be the direction we take Past Appointment and we'll add this to the list for user testing round 2.

**Comment by jbalboni** [comment]
It would probably be a good idea for us on the FE to map these to the FHIR statuses as part of this work: http://hl7.org/fhir/DSTU2/valueset-appointmentstatus.html

In the future, we're likely to lose the ability to make status distinctions beyond the 7 statuses listed there (or at best the 10 listed in http://hl7.org/fhir/valueset-appointmentstatus.html).

**Comment by narin** [comment]
@lenaecb Based on the mock data, it does look like video appointments have a status code, though I don't think we are actually checking them in the code.  The only one I see in our mock data though is `FUTURE`.  Is there a specific account you're looking at that I can check out?

**Comment by lenaecb** [comment]
@narin - I was looking with our test acct for Judy Morrison. Here's a screenshot of Past Appt for VVC ![Screen Shot 2020-05-06 at 12.46.14 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/702246f2-4b19-4dd2-b023-b208d9797588)

**Comment by jbalboni** [comment]
I think this is the list of VVS statuses: https://coderepo.mobilehealth.va.gov/projects/CSS/repos/mobile-appointment-service/browse/src/main/resources/video-visits_v2.json?at=refs%2Fheads%2FRelease%2F1.15#470

I asked Brad if this list was complete, he said it was as far as he knew.

**Comment by lenaecb** [comment]
So, the same as the original Vista statuses list. I wonder if you can have these strange combos with VVS appts as your can with other appts.

**Comment by narin** [comment]
> It would probably be a good idea for us on the FE to map these to the FHIR statuses as part of this work: http://hl7.org/fhir/DSTU2/valueset-appointmentstatus.html
> 
> In the future, we're likely to lose the ability to make status distinctions beyond the 7 statuses listed there (or at best the 10 listed in http://hl7.org/fhir/valueset-appointmentstatus.html).

@jbalboni I've created a new ticket to handle the FHIR status mapping here (#8864)

**Comment by lenaecb** [comment]
@narin - I saw you reopened this. Was there something else you were looking into? I did some very quick testing as well, but I am not sure how we can test the various combinations that can potentially populate.

**Comment by narin** [comment]
@lenaecb Nope. Sorry must've been an accident.  I did quick testing as well and it seems to be all good as far I can tell. Closing it out again.
