### ISSUE TITLE
Spike: PDF field character limits

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#85532]
### Background
We had a conversation  with Eric Henna (see Teams) regarding character field limits and how overflow content is generated. They're interested to **explore reducing the occurrences of overflow content (by increasing field character limits)**. They wish to explore what happens if we change PDF meta data etc on our end, to assess downstream impact of doing so (if any).

Shared with them:
<img width="1258" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUZKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--202a32d727873292c7bc3ce533cca0c500f9e8a3/image.png" alt="image.png" />

### Tasks
1. Evaluate what's needed to **generate a PDF with increased character limits**. Is it possible to do this in staging without affecting the production version? If not, I can check on the potential of passing them a manually adjusted PDF for review.
2. For the example file, expand character limits on 'boxed' fields and 'open text' fields - suggestion of 2 fields each
3. Investigate issue where a field value might be running over to the next field (see 2 images and attached PDF pg 10)[cdb54654-624f-420f-b7c7-64dd444fac49.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d0f843707bced0f56122c0fd6f7fec46ad2958c/cdb54654-624f-420f-b7c7-64dd444fac49.pdf)

<img width="791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05d4d56c073b3745c2b01199201b3f40de6cf665/image.png" alt="image.png" />

4. [Post 6/11 discussion with VBA] Investigate how we can reduce instances of addendum pages by increasing PDF field character limits. Let's create a sample PDF with sample data to share with VBA, which will also help to check if field changes cause any issues in downstream systems. Findings from this test can be used to inform how we address the broader problem next.
a) Increase character limit in 9I(3), 9J(3) free text field 
b) Increase characters in a 'boxed' field - pick a name field
c) Convert a boxed field to an open text field - pick a name field

**Comment by mjknight50** [comment]
The current PDF is using a font size of 10.  The smallest size possible is 9.
The total number of characters that a form field text box can be is configurable to anything you would like.
The visual width of each textbox is also configurable.
<img width="552" alt="Screenshot 2024-06-11 at 11 25 59 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/06791e26-93a3-430e-ae0f-e839d3bfbcc6">
<img width="559" alt="Screenshot 2024-06-11 at 11 25 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/62cd505a-161b-4130-ae68-6122f57c9532">
<img width="587" alt="Screenshot 2024-06-11 at 11 25 27 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/5362baaf-50dc-4ef3-8677-2a71ed1995c0">

**Comment by buddhima-coforma** [comment]
Thanks @mjknight50!
Any ideas on what might've caused #3 above?

**Comment by mjknight50** [comment]
After reviewing the case that Eric brought up, I think it is working as intended and correctly.
The dependent child is named:  
First: James Raphael 
Middle: Jovellano
Last: Pangilinan

The overflow correctly moved the first name to the addendum
The first character of the the middle name (J) was written to the PDF in the proper location

If there is an action item here, it could be that we should limit middle initial to a single character (maxlength).
@buddhima-coforma Would you please let him know that it appears to be correct?

**Comment by mjknight50** [comment]
Attached is a PDF with the minimal font size of 9.  
You can compare it to this one:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/fixtures/pdf_fill/21P-527EZ/kitchen_sink.pdf

The changes are pretty hard to spot unless you look at them side by side.

**Comment by buddhima-coforma** [comment]
@mjknight50 Double-checking that the font size has been changed to size 9 for all fields?
I typed in and counted 30 characters in this field <img width="440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cd6eeddd9c7a6b6b678142263c0023584812047/image.png" alt="image.png"/>

The original 527ez pdf does about 25 characters
<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad85d7155543afc2f2db00bf6393913f2483f5eb/image.png" alt="image.png" />

------
About the issue, this was the screenshot he shared in Teams <img width="619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e46a0bf64bab0c9b7c692923858a7ce870ad99bb/image.png" alt="image.png" />
How do we explain this?

This scans incorrectly for them where part of the name is mixed up with 'see addil in'
<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5cc651fd872a9c2bc04c134d1ca921461a2fcb7/image.png" alt="image.png" />

cc @matt4su

**Comment by mjknight50** [comment]
@buddhima-coforma - So, you gained 5 characters?  Good.

With respect to the second question.  It is working as designed.  If they want to reduce the width of the boxes or change the size, we can.

**Comment by buddhima-coforma** [comment]
Feedback provided to VBA
1. The sample PDF
2. Response on the 'issue' they asked about (which isn't an issue, more of something we could improve)

Follow up will be in a different ticket(s)
