### ISSUE TITLE
Midpoint Review - IA Feedback - IVC Forms, 10-7959f-2, Foreign Medical Program Claim Cover Sheet

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#85531]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- This is looking great!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Must: open any links inside the form flow in another tab** Specifically, on upload pages, links out to “find out which documents you need” and/or “specific types of files needed” should include “(opens in a new tab)” and open in a new tab [per our link guidance](https://design.va.gov/components/link/#behavior): "Links on VA.gov should open in a new tab only if clicking the link will result in the user losing progress or data."

- [ ] **Must: add `<label>` and required indicator on file upload fields** If file uploads are indeed required, please include an indicator that the field is required; and either way, the field will also need a `<label>`. These items are built in to [V3 of the file upload component](https://design.va.gov/components/form/file-input#examples---v3)

- [ ] **Consider: Way to see form status after submission** Post-submission, will there be a way for users who have submitted the form while authenticated to view the form status, or to see somewhere that they have submitted the form? I'm not sure if the Claims Status Tool would be a home for that, or if this could show up in My VA as an in-progress draft or a submitted form.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by brian-wilke** [comment]
Moving this to In Progress for this sprint (Sprint 20)

**Comment by brian-wilke** [comment]
@reiting, I have updated the MUST items that are visual in the figma file... but there maybe things here that are coding specific (such as the label that it opens in a new tab) that I don't add to the layout.

**Comment by marywang2** [comment]
@brian-wilke are we able to add these to the annotations?

**Comment by marywang2** [comment]
@reiting to address (using the annotations) when this moves to development.
