### ISSUE TITLE
Adding Greg Henley (New Email)  to DSVA Slack

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#85545]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

- Please add gregory.henley@oddball.io as a full member. (New Email)

Please delete gregory.henley@oracle.com account - Greg has switched companies! 

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [gregory.henley@oddball.io](mailto:gregory.henley@oddball.io) as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by SlakrHakr** [comment]
Is there anything additional needed for this request?

**Comment by LEHigley** [comment]
confirming you want me to delete the old account instead of just update w/the new email address?

**Comment by SlakrHakr** [comment]
I'm guessing updating the email would be enough to let him access the slack workspace again. Hopefully that's an easy quick thing.

**Comment by LEHigley** [comment]
account email changed to gregory.henley@oddball.io
