### ISSUE TITLE
Document CSP error pages

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#85567]
## Description
Similar to the AccessVA error codes we need documentation on errors from CSPs as it pertains to authentication, account creation, or identity verification. This should include all relevant CSPs including Login.gov and ID.me (you can reference their documentation/website) with less emphasis on MHV and DS Logon credentials

## Tasks
- [ ] Create a error pages document in Identity's Github about our CSPs
  - [ ] Include screenshots

**Comment by parkerbees** [comment]
Moved to Jira and blocked as "needing PM intervention". Closing in Zenhub.
