### ISSUE TITLE
10-7959f-1: create feature toggle and react widget ID

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85561]
- Create feature toggle - [Feature toggle guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) and provide name for release plan
- Create a React widget in vets-website for the dynamic content, per documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) and provide ID (to share with CAIA)

**Comment by reiting** [comment]
I have implemented this but am still testing the code to see if it works.

**Comment by reiting** [comment]
Final PR in team review

**Comment by reiting** [comment]
Final PR in team review

**Comment by reiting** [comment]
@baltes @marywang2 this should be in prod and ready to go. Adding screen shots below: 

<img width="865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEMvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa5938eddf929ca46cbbbf41c6a655069f4bbdd0/Screenshot%202024-07-03%20at%202.57.40%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.57.40 PM.png" />
<img width="917" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEcvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed45fc69d529ffdce64ed1f26b8f37a46f08073e/Screenshot%202024-07-03%20at%202.18.43%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.18.43 PM.png" />

<img width="1286" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEsvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00d6a5682859d176cadd7a008f7108ae20741e8c/Screenshot%202024-07-03%20at%202.57.30%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.57.30 PM.png" />
<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME8vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fae561205c58dab314b66b9c257299afa29c80c/Screenshot%202024-06-28%20at%2010.19.03%E2%80%AFAM.png" alt="Screenshot 2024-06-28 at 10.19.03 AM.png" />

**Comment by marywang2** [comment]
@reiting thanks! Do you have the react widget ID?

**Comment by reiting** [comment]
@marywang2 form107959F1

**Comment by marywang2** [comment]
@reiting the screenshot has the claim cover sheet but just making sure this is for the registration form.

**Comment by reiting** [comment]
@marywang2 oops. Yeah it is f1...I went to the wrong url. Do you want me to add a screenshot for f1 here?

**Comment by marywang2** [comment]
It's fine - I'm going to close :)

**Comment by marywang2** [comment]
@reiting I know this ticket is closed, but can we make the "F" lower case? (For the react widget ID - in general the forms follow lower case standard).
