### ISSUE TITLE
10-7959c: Medicare section - copy updates 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85560]
Changes to the Medicare and Insurance sections on OHI:

- [figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1840-131624&t=x84dMTrkKFRHmarD-0) - Medicare plus Health Insurance Information Alt flow - 6/7)
- [url](https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/medicare-ab-status) for Medicare section start
- [url](https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/insurance-status) for Insurance section start

Medicare section:
- Medicare Status screen - update question copy
- Medicare Part D status screen - update question copy
- lower case "carrier" in header (for wherever it appears - "Medicare Part A carrier", B, D, etc)

**Comment by marywang2** [comment]
@jamiefiore do you know if the hint text has been finalized? This ticket is just waiting on those updates.

**Comment by michaelclement** [comment]
@marywang2 Work is done [in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30586), with the exception of hint text which we're still waiting on.

**Comment by marywang2** [comment]
@michaelclement since you already did the work for this ticket, I'm fine with aiming to close this one out and then creating a new one for further changes.

**Comment by michaelclement** [comment]
@marywang2 Sounds good! In that case, we're just waiting on:
- [ ] Team approval
- [ ] Platform approval

Once those are met I'll move this to review.

**Comment by michaelclement** [comment]
Github is having a minor outage right now so i'm not able to merge this approved PR in. I'll update here when I can.

**Comment by michaelclement** [comment]
@marywang2 @baltes @jamiefiore - this has been merged and should be visible on staging shortly. Thanks!

**Comment by marywang2** [comment]
Thanks @michaelclement - this looks good to me, closing for now but @jamiefiore please review when you are back.
