### ISSUE TITLE
10-7959c - insurance flow updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85589]
Updates to the OHI design for the insurance section:
- [figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1155-73969&t=x84dMTrkKFRHmarD-0) - "Health insurance information alt flow - 6/7)
- [url]( https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/insurance-status) for insurance section

Changes:
- move comments screen _after_ file upload screens (for both primary and secondary insurance)
- move insurance plan question _after_ first question in the insurance section (for both primary and secondary insurance) 

<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb0d88606156b0799d02839f988e0c4f40766264/Screenshot%202024-06-12%20at%2012.41.38%E2%80%AFPM.png" alt="Screenshot 2024-06-12 at 12.41.38 PM.png" />

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30424). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by marywang2** [comment]
This looks good to me. Tagging @syd-hoeper for design review as well.

**Comment by syd-hoeper** [comment]
@marywang2 @michaelclement -- Looks good to me
