### ISSUE TITLE
FE | MHV Notifications | Create a feature toggle for Appointment Reminders

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#85580]
## Background 
We have one feature toggle today for all of the MHV notifications. They will not all be enabled at the same time and we need to carve off each notification preference so we can turn them on individually.

We'll need a toggle to enable Appointment Reminders independently of other MHV notification preferences 

#### current toggles 
there are two toggles out there now
- [profile_show_email_notification_settings](https://staging-api.va.gov/flipper/features/profile_show_email_notification_settings)
- [profile_show_mhv_notification_settings](https://staging-api.va.gov/flipper/features/profile_show_mhv_notification_settings)

we need to break up the `profile_show_mhv_notification_settings` so each of the respective notifications it enables are on their own toggle. 

This story is so we will have a toggle for email notifications related to appointment reminders. 

we should call this toggle: `profile_show_mhv_notification_settings_email_appointment_reminders`

#### notification toggles and naming convention documentation 
~[notification preferences workbook.xlsx](https://github.com/user-attachments/files/16269223/notification.preferences.workbook.xlsx)~

[Copy of notification.preferences.workbook (002).xlsx](https://github.com/user-attachments/files/16383640/Copy.of.notification.preferences.workbook.002.xlsx)

## Acceptance Criteria 
- [ ] we have an toggle that controls appointment reminders via email in the notification settings screen

**Comment by mtcA6** [comment]
@asiisii we should talk about this story a little more because there's another layer to the appointment reminders that I think it's important you understand. It might change how you wire up the toggle.

**Comment by asiisii** [comment]
> @asiisii we should talk about this story a little more because there's another layer to the appointment reminders that I think it's important you understand. It might change how you wire up the toggle.

@mtcA6 sounds good

**Comment by ACParker89** [comment]
@mtcA6 this will roll to 42

**Comment by asiisii** [comment]
wiring 4 feature toggles will be worked on the next sprint Jul 31- Aug 13 
department-of-veterans-affairs/va.gov-team#89528
