### ISSUE TITLE
[FE] OH travel expandable alert for appointment select page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#85597]
Add an expandable alert to the travel-mileage page for Mileage reimbursement rates.

[wireframes](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-|-PCI?node-id=3665-893&t=IPvVKoynwG0IMRQW-0)

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/85597?planning-poker) with Zenhub @brianseek

**Comment by loripusey** [comment]
@wullaski here are the updated [wireframes](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3181-3191)
[See Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1718137555931629)

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 / @cgednalske / @loripusey This is merged and ready to be validated locally or with these screenshots:
<img width="181" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXQ4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09ade6107220627fae9c3c546b3fec2475644d2a/340486130-1612938b-2523-41be-af7e-b3a6b04218c1.png" alt="340486130-1612938b-2523-41be-af7e-b3a6b04218c1.png" />
<img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXg4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--977e2b2d144fc1001821afd5aee0972cb25dca5d/340486500-29f12c8d-5de1-4f85-8030-37351ea4301b.png" alt="340486500-29f12c8d-5de1-4f85-8030-37351ea4301b.png" />

**Comment by cgednalske** [comment]
@brianseek could you provide a screenshot of the alert open as well?

**Comment by brianseek** [comment]
oh right, that makes sense 🙃
<img width="166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTErQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6944a3b10b9066216afbc1d3ab1302e6dfefec4/localhost_3001_my-health_appointment-travel-claim_complete%20%284%29.png" alt="localhost_3001_my-health_appointment-travel-claim_complete (4).png" />

**Comment by cgednalske** [comment]
Looks great! (Again, knowing that there are a few content tweaks to come) 🎉
