### ISSUE TITLE
[FE] OH travel add card and content to appointment select

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#85599]
Add cards and content for appointments in appointment selector and content for when there is one appointment.

[wireframes](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3181-3191&t=i7uVqRVXifIgL7qb-0)

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/85599?planning-poker) with Zenhub @brianseek

**Comment by loripusey** [comment]
@wullaski here are the updated [wireframes](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3181-3191)
[See Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1718137555931629)

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 / @cgednalske / @loripusey This is merged and ready to be validated locally or with these screenshots:
<img width="181" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTE4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bf76899ecccc13965db98e4cef16fe8ffd10bbe/340486130-1612938b-2523-41be-af7e-b3a6b04218c1.png" alt="340486130-1612938b-2523-41be-af7e-b3a6b04218c1.png" />
<img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTU4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b766bc6a7da52c810ec6c18d2193ef5d1cc8204f/340486500-29f12c8d-5de1-4f85-8030-37351ea4301b.png" alt="340486500-29f12c8d-5de1-4f85-8030-37351ea4301b.png" />

**Comment by loripusey** [comment]
Looks ok to me, though I guess we are still waiting on final content. Will let UX validate.

**Comment by cgednalske** [comment]
Looks great! 🎉  And yes, waiting on Laura's final content.
