### ISSUE TITLE
[FE] OH travel - Update conent on review page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#85600]
Update content on review page according to [wireframes](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-|-PCI?node-id=3582-4324&t=6Hm8XQSWhP865BQD-0)

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/85600?planning-poker) with Zenhub @brianseek

**Comment by loripusey** [comment]
@wullaski here are the updated [wireframes](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3181-3191)
[See Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1718137555931629)

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 / @cgednalske / @loripusey This is merged and ready to be validated locally or with these screenshots. This PR also includes changes to the success page.
<img width="120" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0Y4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d594fbb85b380f85faee240b63b73767f2834cd/340856304-40fcc7a1-dec0-4160-ab75-cf7cd2f4950d.png" alt="340856304-40fcc7a1-dec0-4160-ab75-cf7cd2f4950d.png" />

**Comment by loripusey** [comment]
@cgednalske I'm confused, the wireframes in the link above have a line drawn through them, can you provide a link to the correct wireframes for this ticket?
cc: @wullaski @brianseek

**Comment by cgednalske** [comment]
Looks good to me! 🎉

**Comment by brianseek** [comment]
@loripusey the wrong wires were linked, here are the day-of ones https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3146-4822&t=0PpiGBsk2skhsNyg-0
