### ISSUE TITLE
Add no-cache header to remaining FE assets 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#8560]
## Overview 

- Hash was removed from certain webpack chunks
- cache control header was not updated for these 
- suspect apps are crashing because the cached version of the chunks are incompatible with the current version of the app

**Comment by rianfowler** [comment]
We updated the S3 bucket to return the correct cache-control header. I've verified this in production. 

Todos remaining: 
- We need to update the vendor file name to bust any caches out there that didn't have the right header.

**Comment by jenniferlee-dsva** [comment]
Hello - just adding info - this behavior is happening on other pages and other REACT widgets. Per this slack thread - screenshot in thread (unable to upload image to Github on VA network): https://dsva.slack.com/archives/C52CL1PKQ/p1588199060139500?thread_ts=1588107241.103100&cid=C52CL1PKQ

REACT widgets on other benefit pages having same situation. Such as:
How to file a claim https://www.va.gov/disability/how-to-file-claim/
Disability ratings calculator https://www.va.gov/disability/about-disability-ratings/
(Chrome)
image.png 
image.png

**Comment by jbalboni** [comment]
Just wanted to add on to what @jenniferlee-dsva was saying, we also see this on https://www.va.gov/health-care/schedule-view-va-appointments/.

I can see that the vendor bundle cache control headers were updated, but it looks like widgets are still missing the `no-cache` header:

![Screen Shot 2020-04-30 at 9 58 38 AM](https://user-images.githubusercontent.com/634932/80719270-3a561100-8ac9-11ea-94d4-686758b54155.png)

**Comment by rianfowler** [comment]
This should be fixed now. Let me know if you continue to see issues.

**Comment by karlbrown-va** [comment]
@rianfowler we've seen an issue with the chatbot today that we suspect has something to do with caching. Can you look at the chatbot widget and see if anything has changed, or needs to?

**Comment by karlbrown-va** [comment]
For example this widget doesn't have the no-cache header:
https://www.va.gov/generated/cta-widget.entry.69da6eef86d62b0c0a82-1588355679784.js
nor an ETag

same with this one:
https://www.va.gov/generated/chatbot.entry.3681a6dc8d6bbaee34c7-1588355679784.js

**Comment by mchelen-gov** [comment]
Hi @rianfowler to follow up can you confirm this is the proper behavior?
Tested today on https://www.va.gov/coronavirus-chatbot/ with clean cache / hard reload, these script assets are returned with the following response headers:

https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.entry.7cf88bfdbe7ccc1d61a2-1588364859777.js
```
HTTP/1.1 200 OK
x-amz-id-2: Y7GUCuQvLX80IMzZBB7dwJg/Y8qKf2Gax4w+LGTkPSp+y15/JX0X/WljbPjHlTxRocbf+pUHkTQ=
x-amz-request-id: 8F2EEEC84F3BF049
Date: Mon, 04 May 2020 15:40:48 GMT
Last-Modified: Sat, 02 May 2020 05:10:38 GMT
ETag: "e1457325ced591395f6cd6682c70c250"
Cache-Control: public, no-cache
Content-Encoding: gzip
Accept-Ranges: bytes
Content-Type: text/javascript
Content-Length: 150029
Server: AmazonS3
```

https://www.va.gov/generated/chatbot.entry.3681a6dc8d6bbaee34c7-1588364859777.js
```
HTTP/1.1 200 OK
Date: Mon, 04 May 2020 15:40:48 GMT
Content-Type: text/javascript
Transfer-Encoding: chunked
Connection: keep-alive
Server: openresty
x-amz-id-2: 4tFP0zMc2GjfHkPrjK5Fpn+4CMD+O8PnJLmvQCoASivhyo+ilTbBEZo2RzyytVCKkIaCql3qBtM=
x-amz-request-id: 65FDA75854336063
Expires: Tue, 04 May 2021 15:40:48 GMT
Cache-Control: max-age=31536000
Cache-Control: public
Content-Encoding: gzip
```

**Comment by karlbrown-va** [comment]
I think in the case of content with hashes in the filename, max-age=31536000 is reasonable, b/c if the content changes it should get a new hash. it is strange that the static-pages-entry page has no-cache directive set.

**Comment by rianfowler** [comment]
I think the bug portion of this has been resolved. I added a dependency to this ticket.
