### ISSUE TITLE
SOCKS access for Derek Dyer

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#85619]
### Your Name

Derek Dyer

### Your Email

derek.dyer@govcio.com

### Your GitHub Handle

digitaldrk

### Your Role and Team

Backend Engineer | VSA Debt

### Product Manager (PM) name and email

Tom Davis thomas.davis@va.gov

### Product Owner (PO) name and email

Denise Coveyduc denise.coveyduc@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFolB6lGCy6uQC8tMEl02irpDiQL5EtRRfPIEOmwpbiR devdyer@KWYMJ7YDX2.local

### E-QIP Transmittal Confirmation

![Transmittal Notice proof for Derek Dyer 5 28 24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/4297274/b578138f-92a2-46d6-8ad6-0817d0fdd149)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Merged your SOCKS PR. Please let me know if you run into any issues

**Comment by digitaldrk** [comment]
> Merged your SOCKS PR. Please let me know if you run into any issues

Hey @stoiven thank you for your help.

I watched [the video about SOCKS](https://www.youtube.com/watch?v=OnBhO3FVTTg&t=23s) setup and it instructed to run this command to verify SOCKS setup:  `vtk socks setup`

When I run this command, I get the following error.
```
...
/vtk/commands/socks/setup.rb:398:in `launch_agent_variables': uninitialized constant Vtk::Commands::Socks::Setup::OpenStruct (NameError)
...
```
 I searched the OCTO slack for the error and didn't see any mention of it. Does it look familiar to you? Would you rather I post this in Slack?

**Comment by digitaldrk** [comment]
> > Merged your SOCKS PR. Please let me know if you run into any issues
> 
> Hey @stoiven thank you for your help.
> 
> I watched [the video about SOCKS](https://www.youtube.com/watch?v=OnBhO3FVTTg&t=23s) setup and it instructed to run this command to verify SOCKS setup: `vtk socks setup`
> 
> When I run this command, I get the following error.
> 
> ```
> ...
> /vtk/commands/socks/setup.rb:398:in `launch_agent_variables': uninitialized constant Vtk::Commands::Socks::Setup::OpenStruct (NameError)
> ...
> ```
> 
> I searched the OCTO slack for the error and didn't see any mention of it. Does it look familiar to you? Would you rather I post this in Slack?

I was advised to post on OCTO Slack, I'll post the question there.

**Comment by digitaldrk** [comment]
> > > Merged your SOCKS PR. Please let me know if you run into any issues
> > 
> > 
> > Hey @stoiven thank you for your help.
> > I watched [the video about SOCKS](https://www.youtube.com/watch?v=OnBhO3FVTTg&t=23s) setup and it instructed to run this command to verify SOCKS setup: `vtk socks setup`
> > When I run this command, I get the following error.
> > ```
> > ...
> > /vtk/commands/socks/setup.rb:398:in `launch_agent_variables': uninitialized constant Vtk::Commands::Socks::Setup::OpenStruct (NameError)
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I searched the OCTO slack for the error and didn't see any mention of it. Does it look familiar to you? Would you rather I post this in Slack?
> 
> I was advised to post on OCTO Slack, I'll post the question there.

I got access via [some help in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1718638549895119)
