### ISSUE TITLE
[Team] 10-10EZR Attach Docs: Complete Post Mortem (OOB)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85629]
As a Veteran, I would like to be clear on what documents I should attach to my EZR and know that those will go into my VA record so that I can get the health care I have earned.

- [x] Determine what to do about attach docs going out
- [x] Create post mortem
- [x] Fill out post mortem as a team
- [ ] **Success: We have come up with a solution to attach docs being deployed to prod early, and we have written up a post mortem for the OOB**

**Comment by emily-brown34** [comment]
Communicated to PO, identified risks, platform ticket submitted, OOB approved and redeployed, team is currently working on the post mortem for the OOB and intends to have it complete by EOD today

**Comment by allanto-ah** [comment]
Post Mortem completed [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2024/2024-06-10%20EZR%20Attach%20Doc%20OOB%20post%20mortem.md)

**Comment by emily-brown34** [comment]
Awaiting PM review, but PO has been notified that it is mostly done

**Comment by allanto-ah** [comment]
@alexseelig can this be closed? Or is there still any pending items?
