### ISSUE TITLE
[FE/QA] 10-10EZR Attach Docs: Make content updates (including document type) and test

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85628]
As a Veteran, I would like to know what documents I should attach to my EZR, and how to attach them, so that I make sure I get all of the health care I have earned.

- [x] Make change to content on the FE based on [content changes](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/82044)
- [x] Make changes to "document type" based on [discovery](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/85627)
- [x] Work with QA to test and make sure these changes are implemented (updated test cases if needed)
- [x] **Success: We have finalized content and workflow for attach docs!**

**Comment by allanto-ah** [comment]
Test cases updated and this has been verified. Closing.
