### ISSUE TITLE
Vets-api terminal access for Derek Dyer

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#85621]
### Your Name

Derek Dyer

### Your GitHub handle (terminal access is managed through GitHub)

@digitaldrk

### Team, Role, and Company of the target individual

VFS Debt Resolution, Backend Engineer, GovCIO

### Product Manager (PM) name and email

 Tom Davis, thomas.davis@va.gov

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Derek needs access to assist in troubleshooting FSR Form 5655 submissions for Veterans.

Please see attachment which confirms EApp (eQIP) proof of adjudication.
![Transmittal Notice proof for Derek Dyer 5 28 24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/32a24747-bbff-43ec-ac24-a4d8259eba62)

Thanks!

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by HeatherRienks** [comment]
FYI @digitaldrk

**Comment by bdech** [comment]
Confirmed in Atlas
E-QIP confirmed

**Comment by bdech** [comment]
@digitaldrk You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by HeatherRienks** [comment]
@bdech - any updates on this? Thanks!

cc: @denisecoveyduc

**Comment by bdech** [comment]
Hey @HeatherRienks I have not received any updates. OCTO checks these requests on a weekly basis. I'll include @JonathanKamensDVA here in this thread for visibility.

**Comment by JonathanKamensDVA** [comment]
Approved. Apologies for the delay.

**Comment by bdech** [comment]
@digitaldrk, It looks like you already have access to `dev`, `staging`, and `sandbox`. I've granted access to `production`, with access limited to six months, expiring 12/18/24. 

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by digitaldrk** [comment]
Good afternoon @bdech,

I got pinged about my access shutting off on 12/18. My team is up for possible contract renewal on 12/19 and there is some ambiguity on whether I should seek an extension to my access.

Is there an SOP for this situation? The concern is that it gets shut off and I'll not have access to support our project or maybe help with onboarding a new team.

If it's required my access is shutoff, no worries. Just wanted to make sure things continue to run smooth and veterans are supported.

**Comment by bdech** [comment]
Thanks for reaching out Derek. There isn't a SOP for this type of scenario. With that being said we give 72 hours from the day of your expiration to decide if you need an extension. We will work with you to ensure Veterans are supported and there's no gaps in that support. Do you think you'll have an answer on the 19th?

**Comment by HeatherRienks** [comment]
FYI @dhill802

**Comment by GWright321** [comment]
Good Afternoon and Happy Holidays  @digitaldrk Have you decided whether or not you want to renew access?

**Comment by dhill802** [comment]
Good afternoon @GWright321 - Currently @digitaldrk is unable to access this ticket to respond. He would like to renew access please. Ty!

**Comment by GWright321** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their access?

**Comment by bdech** [comment]
@digitaldrk  your Production access has been extended for 6 months, expiring 06/18/25.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by bdech** [comment]
Support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1735064422625719)

**Comment by digitaldrk** [comment]
Sorry I missed the pings team 😬 . Thank you for your help!

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by AnthonyWFlowers** [comment]
Support Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1750796544195969)

**Comment by HeatherRienks** [comment]
@AnthonyWFlowers - Please grant an extension for @digitaldrk. Thank you!

cc; @denisecoveyduc (Goct PO)
