### ISSUE TITLE
[UX/FE/BE] 10-10EZR Attach Docs: Discovery--Document Type

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85627]
As a Veteran, I would like clear instructions on what documents to attach with my EZR online application so that the VA knows I was exposed to toxins while in the Service and I have access to more healthcare.

- [x] Re-confirm with HEC (Simone) that they do not need the document type for documents attached to EZR
- [x] Check with Josh F. to see if there are any other document types we can list
- [x] Decide how to handle the document type field, if we want to show it and change verbiage for the answers, or not show it at all and default it to something on the backend
- [x] **Success: We have a decision on how to handle document type.**

**Comment by emily-brown34** [comment]
Does document type matter? Root question we are trying to answer. Veterans must select what kind of document for disability, but is it needed for EZR?
HEC initially noted that this was not needed and we don't want to add this in if it's not needed beyond the API requirements

**Comment by emily-brown34** [comment]
Emily to email Simone and clarify if this is needed

**Comment by emily-brown34** [comment]
Josh to create a BE ticket to 'autopopulate' doc type and remove drop down on FE

**Comment by emily-brown34** [comment]
Email sent to HEC/Simone to confirm that the Veteran does NOT have to fill out doc type/HEC does NOT need doc type to process

**Comment by allanto-ah** [comment]
No QA needed and this has already been done
