### ISSUE TITLE
[Data] 10-10EZR: June Monthly Metrics Pull

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85635]
As a HEC member, I would like to see EZR usage metrics monthly so that I know how the online EZR is doing and we can compare to pre-and-post online EZR launch.

- [x] Pull metrics for the previous month (June)
- [x] Pull metrics we've been pulling (reference [this thread] (or reference May ticket) (https://dsva.slack.com/archives/CMJ2V70UV/p1715630292285879))
- [x] Pull any other metrics you find interesting
- [x] Pull lifetime (April 11) to date metrics
- [x] Send to HEC folks
- [x] **Success: We have pulled and sent monthly metrics to HEC**

**Comment by luis-simauchi** [comment]
Timeframe: June 1, 12:00 pm – June 30, 11:59 am	
Metric	From DD
successful submission	4310
total sessions	8071
Number of pageviews per session	5.86
failed to submit with no retries	70
Error Rate %	0.867%
Start to Finish Ratio %	47%
Avg Session Duration	8min 57 s

**Comment by luis-simauchi** [comment]
Timeframe: 	Apr 11, 12:00 am - 6/30/2024 11:59:00
Metric	Metric - From DD
successful submission	10147
total sessions	17489
Number of pageviews per session	5.85
% of forms submitted with TERA Questions:	33.50%
Avg Session Duration	8 min 39 s
Start to Finish Ratio %	49.50%
number of sessions that applications started:	16147
failed to submit with no retries	122
Types of status codes present in errors:	404, 502, 503
Error Rate %	1.21%
