### ISSUE TITLE
[Data/BE] 10-10EZR Attach Docs: Come up with way to track document attachments in EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85630]
As a team member, I would like to know how frequently users are attaching documents to their EZR so that I know if it is being utilized and/or if we need to make changes to make it easier for Veterans. 

- [x] Change controller so we can discern what documents come from EZR 
- [x] Set up document attachment monitoring
- [x] Add new EZR attachments controller to the backend
- [x] Write tests
- [x] Change the frontend endpoint code to point to the new backend endpoint
- [x] Test in a review instance with QA to ensure everything works as intended
- [x] **Success: We know how Veterans are using the attach document functionality.**

**Comment by luis-simauchi** [comment]
https://vagov.ddog-gov.com/monitors/237140?view=spans&live=1m

**Comment by emily-brown34** [comment]
@JoshingYou1 when you return today, high priority for controller to differentiate EZR/EZ doc upload errors. Please tag up with @luis-simauchi on this!

**Comment by luis-simauchi** [comment]
Josh has created the ezr specific controller for this doc attachment function going to close the ticket

**Comment by JoshingYou1** [comment]
I increased the points to a 5 mainly because adding a controller meant adding new tests and some other code for ezr attachments. Also, I needed to change the frontend code to point to the new backend path (no longer `v0/hca_attachments`.
