### ISSUE TITLE
Update language on "Effective date/s" to be consistent and to make overall edits to page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8564]
On this page: https://www.va.gov/disability/effective-date/

Notes from @DanielleThierryUSDSVA 

Would the H2 maybe work ask:
How does VA decide my effective date?

Update language to remove "....hang in there"

Done = Danielle approves new language. 
Question - will stakeholders need to review?

**Comment by AnneHurley** [comment]
H2: How does VA decide effective dates?

Text: It depends on the situation. Learn how we decide effective dates in different cases.

Then changing headline/left nav/hub references to plural "rates", and using singular "rates" as we speak to the Veterans specifically about their own effective date.

**Comment by AnneHurley** [comment]
@RLHecht  Page is ready for your copyedit/publish: 
prod.cms.va.gov/node/868/edit
@DanielleThierryUSDSVA  FYSA

**Comment by RLHecht** [comment]
This page has been published. Moving to validate and will close when live on the site.

**Comment by RLHecht** [comment]
Changes validated on live site. Closing ticket.
