### ISSUE TITLE
Find a VA Form: Create a notification event when a form is added/removed in the VA forms database 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8567]
# Create a notification event when a form is added/removed in the VA forms database 

**Problem:** 
Because the Related to and Online tool data lives only in Drupal, not in the forms db, we need a way of being notified of a 'form added' event. This notification would alert the PW content team so that we can specify the online tool URL  and add other related to values if needed for high value forms. 

**Question TBC** - Do we need an event notification when a form is removed? (For content or engineering purposes? For redirect needs? Governance?) 

 **Acceptance criteria - to be groomed:** 
[ ] During nightly migration of forms db data into Drupal, a notification is triggered when a form has been added or removed in the forms database. 
[ ] The notification is in the form of an email message. (Desired)
[ ] The email notification is sent to specified PW content  team/person or PM. (TBD discussion)
[ ] The email notification includes the following pieces of info:
- Form number
- Form name
- Form owner ID
- Date of add/remove in the source forms database
- Related to

**This work needs:**
[ ] Drupal engineering support

This task is related to the Form detail landing page epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5590

**Comment by johnhashva** [comment]
Smart approach!

**Comment by stephorkandatx** [comment]
Blocked until we get the migration done

**Comment by stephorkandatx** [comment]
In sprint planning, it was discussed that CMS team has a separate (but related) initiative to enable this. But it's a big lift, with at least a couple sprints' worth of work. That blocks this ticket, but makes this ticket's ask smaller

**Comment by MarciMcGuireGCIO** [comment]
Since it's post 2020, I'm removing the blocked tag and popping it into icebox.

**Comment by swirtSJW** [comment]
This is likely outdated as we have flags and we do have Slack being notified, though not in a good spot (https://github.com/department-of-veterans-affairs/va.gov-team/issues/43239) 

This can probably be closed but handing to to Public Websites team as I take my face off it.  @wesrowe

**Comment by wesrowe** [comment]
I agree. closing.
