### ISSUE TITLE
SC | Migrate 4142 form to use Lighthouse Benefits Intake API

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#85680]
## Value Statement

**_As a_** product team

**_I want to_** have 4142 forms submitted to Lighthouse API instead of EMMS/CMP

**_So that_** we can take advantage of the guardrails that the API provides

---

## Background Context

Currently the 4142 that can submitted with a Supplemental Claim is being directly submitted to CMP instead of through Lighthouse. There's been a [large push to remove direct submissions to EMMS/CMP](https://dsva.slack.com/archives/C5AGLBNRK/p1716318708157029?thread_ts=1716216498.782459&cid=C5AGLBNRK) as a part of remediation efforts. It seems we're already using [the metadata validator](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/utilities/form_4142_processor.rb#L74-L77) in the form processor, but still need to shift the [submission piece of it](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/appeals/supplemental_claim_services.rb#L249) to call the LH API so we can benefit from the protections like rate limiting and built-in retries for downtime, etc. as Emily mentioned in the [thread](https://dsva.slack.com/archives/C5AGLBNRK/p1716320989402969?thread_ts=1716216498.782459&cid=C5AGLBNRK).

## Acceptance Criteria

- [x] Form 4142 is no longer being directly submitted to EMMS/CMP

## Open questions

- Which Benefits Intake Service should we use? 
  - ~[lib/benefits_intake_service/service.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/benefits_intake_service/service.rb) - used by Dependents and Non-disability teams, and 526 submissions for 4142~
  - ✨⭐️WINNER⭐️✨ [lib/lighthouse/benefits_intake/service.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_intake/service.rb) - used by Pension team
- Do we need to add any DataDog monitors to track the 4142 submissions to Lighthouse that come from our SC form?

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by wayne-weibel** [comment]
I created the `lib/lighthouse/benefit_intake` to be generic and it pulls in (and expands) the metadata validation as well.  I am biased of course, but recommend using that service library

**Comment by eileen-coforma** [comment]
Needs staging verification. Once done, will move into Prod

**Comment by eileen-coforma** [comment]
Messaged Steve Albers about data that might be affected by the migration to figure out unknowns.

**Comment by dfong-adh** [comment]
Connected with Steve Albers and confirmed that no DD dashboards/metrics currently use the statsd metric for `api.central_mail.upload.total`.

Verified in staging - no issues with 4142 form submissions to sandbox. Will enable the flipper in production and monitor the results.

**Comment by eileen-coforma** [comment]
Completed in staging. Derek will request for access to enable flipper. Shaun can help with the flipper if Derek doesn't get access by Monday. Will be released on Monday.

**Comment by eileen-coforma** [comment]
Turning on the flag today. Derek will monitor. Monitor a couple days for health before closing.

**Comment by dfong-adh** [comment]
Flag `decision_review_sc_use_lighthouse_api_for_form4142` has been enabled. Monitoring via DD logs.

**Comment by dfong-adh** [comment]
No issues observed with submissions to LH API as of 7/16.

**Comment by dfong-adh** [comment]
No issues observed as of 7/17. Closing as complete.
