### ISSUE TITLE
Pass UserAccount to FormSubmission during intake job

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#85690]
### Overview

It's sometimes necessary to look up a claim by user id, but [when creating a FormSubmission for polling a claim's submission status](https://github.com/department-of-veterans-affairs/vets-api/blob/dd9da376ef72c5db10a23b73651a81e7c1c6d74a/app/sidekiq/lighthouse/pension_benefit_intake_job.rb#L142), we don't currently fill the user_account_id field. We have access to the user_uuid field within the PensionBenefitIntakeJob when the user is authenticated, so we should be passing that while creating the FormSubmission. 

[Example of a FormSubmission being created with a linked UserAccount.](https://github.com/department-of-veterans-affairs/vets-api/blob/dd9da376ef72c5db10a23b73651a81e7c1c6d74a/app/sidekiq/central_mail/submit_central_form686c_job.rb#L71)

### Acceptance Criteria

- [ ] When the user is authenticated, the FormSubmission is linked to the user account when created
- [ ] When the user is unauthenticated (user_uuid is nil), the FormSubmission is created with no linked user account

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/85690?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by wayne-weibel** [comment]
The error in the PR is occurring because the UserAccount attached to form_submissions is found via `icn`, which is not the user_uuid supplied to the intake job.
