### ISSUE TITLE
[ECR,GitHub Action] Create Workflow for populating ECR with Public Images

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#85699]
- We want to leverage ECR for all of our images used within EKS clusters
- Create a GHA Workflow that can take a list of public images and push them up into ECR
- Scan with Trivy and generate SBOM

**Comment by Efe-Oddball** [comment]
Working on identifying all the public images we are currently using

**Comment by Efe-Oddball** [comment]
I have identified public images, and I am currently working on the workflow to push public images to ECR

**Comment by Efe-Oddball** [comment]
I have created a file image-list.yaml that public images that needs to be in the private ECR repo can be added, and I have completed the initial workflow that polls image-list.yaml and pushes the image to ECR, taking the image name and active tag into consideration.

**Comment by Efe-Oddball** [comment]
My work-flow is fully functional. I just need to evaluate using matrix instead of a for loop to parse the image-list.yaml file. Once that is done and tested, I will create a PR for the work. Everything is functional using the for loop option, but the matrix option will be cleaner and ensures parallel execution.

**Comment by Efe-Oddball** [comment]
I have successfully gotten the workflow to work using matrix strategy with parallel jobs. I just need to integrate Trivy scanner and SBOM generation into the workflow, and I will push out the PR

**Comment by Efe-Oddball** [comment]
I have the PR out for review, and this ticket will be merged once the PR is approved

**Comment by Efe-Oddball** [comment]
PR has been merged. Moving ticket to a resolved state.
