### ISSUE TITLE
[DISCOVERY] Using ECR for storing Helm Charts

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#85700]
## Description
Instead of using S3, does ECR provide what we need for storing Helm Charts

## Resources 
- Reliability team has already been leveraging ECR for this, they may be a resource to talk to

## Acceptance Criteria
- [ ] Discuss with team your findings

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
Evaluating our current set up for Helm Charts

**Comment by Efe-Oddball** [comment]
Testing changes to workflow for chart storage in ECR

**Comment by Efe-Oddball** [comment]
I have completed the workflow test to push to ECR and and I am writing up a mini-document on the steps required to implement this. Will be discussing with the team about it tomorrow.

**Comment by Efe-Oddball** [comment]
Here is a sample writeup on ECR storage for Helm Charts
https://docs.google.com/document/d/17nu6ZLYeRlnJgR_KnFDN2n0E3elxt9l3FQ8BODoonKY/edit

**Comment by Efe-Oddball** [comment]
This ticket will be moved to a resolved state after discussions with the team

**Comment by Efe-Oddball** [comment]
Here is the Workflow for pushing to ECR: https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/b85700/.github/workflows/helm-release.yaml

**Comment by Efe-Oddball** [comment]
This ticket will roll over pending discussion with the team about the next steps. Ticket will be resolved after discussion

**Comment by Efe-Oddball** [comment]
We have decoded against ECR helm storage implementation at this time. The documentation and the workflow branch have been added to the comment section.

**Comment by Efe-Oddball** [comment]
Moving the ticket to a resolved state
