### ISSUE TITLE
[DISCOVERY][Packer] Amazon CloudWatch Agent Implementation - Policies and Roles

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#85703]
## Description
In order to resolve the outstanding issue of EKS node volumes running out of space, we would like to implement the Amazon Cloudwatch agent to collect logs instead of storing them on the node itself.

Need to add new policies to current and new roles:
- ec2DescribeTags
- (set of permissions to allow writing to amazon cloudwatch)

Possible solutions: 
- Create new "ec2DescribeTags" policy
- Identify or create policy that allows for EC2 instance to write to CloudWatch
- Attach new policies to either current roles in use or new roles to be used.

## Resources 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74601

## Acceptance Criteria
- [ ] Setup a Working Session with the team to discuss potential solutions

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
Going through the GH comments in the Closed PR  and Slack discussions about this topic to understand what needs to be done

**Comment by Efe-Oddball** [comment]
The two images that will need to be taken into account here are the 
1. EKS node image
2. Al2-hardened

Approach_1
* Identify nodes or instances that are built off al2 hardened.

* Update the roles attached to the IAM instance profile with policies that gives permission to write logs to CloudWatch
* Configure logrotation to ensure cleanup.

Approach_2

* IAM instance profile role for AL2 hardened is passed directly within the packer file. We can replicate the packer file for the EKS node referencing the instance role profile and passing the required custom inline policy via terraform. (This fixes the issue at the image level.
* Implement logrotation 


Approach_3
* Implement CloudWatch insights at the cluster level for EKS node to handle moving logs to CloudWatch.
* Use one of the first two approaches for instances using AL2-Hardened
* Implement logrotation

**Comment by Efe-Oddball** [comment]
Updated some of the EC2 roles with Cloudwatch policies and with test functionality next week before updating the code and creating a PR

**Comment by Efe-Oddball** [comment]
I have updated all EC2 IAM profile roles within the AWS console. This includes roles connected to the legacy forward proxy, new reverse proxy  as well as the new fwd proxy in dev with _"ec2:describetags"_ policy. This also includes adding cloudwatch logging policy to the EKS nodes role IAM profile for all tiers. Working on running the Cloudwatch scripts to set up the Cloudwatch agent, then test functionality

**Comment by Efe-Oddball** [comment]
I am also working on updating the terraform code with all the updates I implemented within the console

**Comment by Efe-Oddball** [comment]
I am working on creating a cluster for the EKS updated image with the cloudwatch agent installed and then I will deploy nodes to the cluster and confirm that the logs are going to Cloudwatch correctly. Most of the terraform code  that provisions the policies have been updated. This ticket will also have to roll over to the next sprint

**Comment by Efe-Oddball** [comment]
I am back to working on this

**Comment by Efe-Oddball** [comment]
I am having some issues  setting up EKS cluster due to how gitbash handles path in windows. I am trying to resolve that to proceed with this ticket

**Comment by Efe-Oddball** [comment]
I have been able to bypass the issue with git bash "too long" path but I am still struggling with another issue as shown in the attached image, which I feel might also be related to how windows/gitbash is handling the script that creates clusters. I just want to create the clusters to test the changes

**Comment by Efe-Oddball** [comment]
│ fatal: '$GIT_DIR' too big
│ fatal: fetch-pack: invalid index-pack output

**Comment by Efe-Oddball** [comment]
Considering I could not figure out the solution to that error. I decided to change the terragrunt source path to use the local repo in my directory so I can carry out the necessary test

**Comment by Efe-Oddball** [comment]
Steven was able to create the container for me while I continue to figure out why I am having issues creating it from a windows system.
Upon connecting to one of the nodes, the cloudwatch agent does not seem to be working properly. i will be making modifications to the script to re-create the ami and spin up a new cluster to ensure the agent is properfly functional within the mode.
There is a high probability that this ticket will be rolling over

**Comment by kflow85** [comment]
This work continues and is being tracked in GitHub Projects https://github.com/department-of-veterans-affairs/va.gov-team/issues/85703#issue-2347078980

**Comment by Efe-Oddball** [comment]
I have created the final PR for this ticket. Once approved, the PR will be merged and ticket will be moved to a resolved state

**Comment by Efe-Oddball** [comment]
moving this ticket to a resolved state
