### ISSUE TITLE
Research/Design Triangulate Existing Research Data pointing to Challenge and Design Activities

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#85730]
Design and Research will create a Mural Board that incudes research data resources to date;table of tickets in flight, the problem to solve, the information that points to the problem, the design related activities, confidence levels and the data/research needed to evaluate the success of the identified solutions.  Additionally, Research/Design will draft a table of data related questions we would like to answer/monitor

## Acceptance Criteria
[ ] Triangulate existing research data**
  - Provide information on existing pension related research and design data sources
  - Create table that includes tickets in flight, problems to solve, data/information pointing to the problem, design activities, confidence levels, and data/research needed for monitoring success
  [ ] Draft a table of data related questions**
    - Then the table should include questions we want to answer or data we want to monitor to determine the success of identified solutions
   [ ] Share and discuss information with the enablement team** 
- Determine next steps
- Provide to VA crew for feedback

**Comment by mtri** [comment]
[Mural board link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425030709/9bfbf3bb5b3a4375e4ab7806052589f11ca0bef9?sender=ue8aedc08d995ffc3e8665432)

Meeting June 17th on adjustments and next steps.

**Comment by aplatt-coforma** [comment]
Provide summary for feedback here: https://dsva.slack.com/archives/C06E83RNLQM/p1719493568588709
