### ISSUE TITLE
Update all eCheck-in, Pre-Check-in, and Travel VA Notify Messages to Remove the Trailing Period

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#85756]
## Description
An issue was brought to our attention that the inclusion of a trailing period on VA Notify messages can cause some SMS clients to return a 404 when Veterans click the link because they don't automatically strip the trailing period. The trailing period was added to prevent the link web page preview from displaying. In an effort to account for those SMS clients that may not automatically strip the trailing period, we will remove it from our SMS messatges.

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1718144144807049)

## Tasks
- Update all eCheck-in messages in VA Notify to remove the trailing period
- Update all Pre-Check-in messages in VA Notify to remove the trailing period
- Update all Travel messages in VA Notify to remove the trailing period

**Comment by benbrasso-agile6** [comment]
https://dsva.slack.com/archives/C010R6AUPHT/p1718302771484739?thread_ts=1706895333.034539&cid=C010R6AUPHT

**Comment by benbrasso-agile6** [comment]
@loripusey I updated the VeText document for BT app; don't think they need a ping since I'm not sure they started their work yet. 

If we also want to look for this scenario in VeText (not VA Notify, which is what Adrian flagged), I feel like we might not a separate ticket for that. But, open to suggestions.

**Comment by loripusey** [comment]
@jwowk We need to update the VeText SMS messages; can you reach out to @benbrasso-agile6 to find out what the changes are and determine where in the roadmap this work might fall?

**Comment by jwowk** [comment]
@benbrasso-agile6 can you paste the corrected message verbiage here so we can get corrected asap?

**Comment by benbrasso-agile6** [comment]
I think this is on hold for a moment. 

@jwowk Adrian had reported that messages that have links with a trailing period are 404'ing for some users, e.g., the period isn't getting stripped out when a user selects the link. 

I don't know if PCI Team should be making the call universally if periods shouldn't be used at the end of a url. Could you talk to Shane a bit about this. There's an unresolved conversation about this with VA Notify in Slack - https://dsva.slack.com/archives/C010R6AUPHT/p1718373989251569?thread_ts=1706895333.034539&cid=C010R6AUPHT

**Comment by loripusey** [comment]
I thought we had decided to remove the trailing period so that no Veteran gets a 404; that is my vote; are there others that need to decide? Can we decide and move forward?
@benbrasso-agile6 @acrollet @jwowk

**Comment by benbrasso-agile6** [comment]
Well, at one point this was specific to a VA Notify message. But, then VeText was brought in too. So, we should figure out the scope of what messages in the PCI ecosystem we're looking to change right now. And, would love insight from the two messaging applications. I feel like I'm not an SME in that space to make an informed decision.

**Comment by loripusey** [comment]
I would we do all PCI messages that are in VA Notify; the trade off is that we are willing to have the Veteran see the preview so that we can avoid a Veteran getting a 404 error with certain phone devices

**Comment by benbrasso-agile6** [comment]
Confirming last message: we shouldn't update messages sent by VeText; only VA Notify (e.g., the one that Adrian first pointed out.)

**Comment by loripusey** [comment]
I think this is a good first step.

**Comment by benbrasso-agile6** [comment]
@loripusey ok to close?

**Comment by loripusey** [comment]
If we've communicated changes to Melanie, then ok to close.
