### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: alphabetize Facility dropdown options

### ISSUE THREAD

**Issue by Mitch-A6** [department-of-veterans-affairs/va.gov-team#85772]
## Background
The list of Facilities comes in in ID order, making it look arbitrarily shuffled to Vets. This makes it difficult to look for a specific facility, especially in a state with a longer list of Facilities like Texas or Florida.

## Tasks
- [ ] Sort the Facilities alphabetically by name

## Acceptance Criteria
- The Facilities are sorted, and otherwise still selectable as normal

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this is working as expected.
