### ISSUE TITLE
Save key GA3 baselines for posterity

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#85785]
### User story

As a Cartography team member, I want to save GA report data for events and other user behavior for previous periods of time, so that we have a basis for comparison after GA3 is turned off July 1.

### Notes
- could include:
  - clicks on the landing page links
  - 

Possible tasks:
- [x] Brainstorm in a Mural what metrics we think are most important to save from the landing page prior to the integration launch
- [x] Get data from GA3 for those metrics over the past 6 months
- [ ] Download in some format that is reusable & save in shared drive on the Network

## Acceptance criteria
- Identified some baseline numbers we might want in the future, and what time frames we're interested in
- Downloaded CSVs of those reports (could be saved in drive)

**Comment by fmccaf1** [comment]
Sara and I brainstormed what seems like it could be most useful to keep for posterity's sake:

These metrics seem like they could be most useful:
- [ ] Top clicks and lowest clicks
- [ ] Where are people coming from to get the landing page: global header, and breadcrumbs in appts
- [ ] Global header clicks (segment by mobile vs. desktop)
- [ ] Based on where they are coming from what are they doing
- [ ] Mobile and desktop users (get devices for all metrics)
- [ ] How many people are seeing alerts?

cc: @sterkenburgsara @wesrowe

**Comment by fmccaf1** [comment]
I believe I got top clicks for the home page. Will update with a link to the sharepoint location tomorrow.

**Comment by wesrowe** [comment]
Note the [landing page dash](https://analytics.google.com/analytics/web/?pli=1#/dashboard/Zz-BsIsFTru7HI16l-D2MA/a50123418w177519031p176188361/) makes some of this easier. Especially link clicks.

I see opportunities to reduce your list and/or reduce complexity in a couple areas.
- was there something specific about global header clicks that you want to gather? this sounds really broad, and not immediately relevant to our product (but maybe you had a targeted list of clicks in mind, eg auth menu).
- devices I'm not worried about, we should have that data back to Feb (when GA4 was first installed).
- "Based on where they are coming from what are they doing" – I'm guessing you have an approach in mind using previous-page-path or something... but this sounds (at first read) really complex and maybe not worth the effort to baseline

I like the alerts idea and this is easy to get. Lmk if you need an assist on that.

**Comment by sterkenburgsara** [comment]
@wesrowe We were curious about two things: 
1.) how people get to the landing page? before 6/17 there were two routes. Can we #s that came from each? 
  * My HealtheVet in global header
  * Breadcrumbs on appointments pages 
2.) What people do when they get there
  * engage with page: highest & lowest clicks on the page
  * leave the page: click in header or footer - header links seem more interesting - those that might be interesting to track specifically include the bullets below.
    * mega menu
    * MyVA
    * Search
    * Profile menu (mobile only)

I don't even know if we can track these things or download data like this. If LoE is too high, would love to get your PoV on that. 

When you say you're not worried about devices, do you mean the overall analytics split in general for landing page traffic by mobile/desktop, or that we can also easily see the device split for all other metrics too?

**Comment by sterkenburgsara** [comment]
**Update:** 
* Pre-integration launch traffic to the URLs on the landing page (January 1 - June 16, 2024) were captured from the MHV landing page dashboard from GA3. This dashboard is not a report and data was only accessible via PDF (not reusable). Was saved in the "Transition KPI Metrics" Sharepoint folder on the VA Network.

**Comment by fmccaf1** [comment]
Finished downloading reports from GA3 and uploaded all to [a new folder in our shared drive space.](https://dvagov.sharepoint.com/sites/oitmhvonvagovcartographyteam/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=XgGNff&CID=3f6adf9f%2Dcec9%2D4041%2Db120%2D45a3eef17a2e&FolderCTID=0x012000C7666D4A8B08EC4099C733EE6934F8DE&id=%2Fsites%2Foitmhvonvagovcartographyteam%2FShared%20Documents%2FGA3%20reports%20for%20posterity) I moved Sara's there too. Folder location
