### ISSUE TITLE
[DISCOVERY] Support VAMC content authors with a11y

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8578]
## User Story or Problem Statement
How might we help content authors make a11y decisions with their content?

## Background
This was mentioned in a [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5473#issuecomment-595504392) related to descriptive labels for downloadable PDFs on Pittsburgh's About us page. Generally speaking though, we can ensure more equitable experience for all users if we support content authors (help tips) during the editorial experience. 

## Goal
Equitable experience and access to content for all Veteran users
Improve the editorial experience

## Objectives or Key Results this is meant to further
- Objective 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] TBD
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@laflannery not sure if there's any specifics here that are still relevant or if all your current initiatives cover this

**Comment by laflannery** [comment]
@davidmpickett I would close this - Anything we want to do I any thing more holistically not just for VAMCs. So from my standpoint I don't have a specific reason to leave this open.
