### ISSUE TITLE
Draft confirmation email copy for 10-10d

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#85783]
As a CHAMPVA applicant, I need to receive a confirmation email so that I know my application is being processed and I know what to expect next.

Acceptance criteria
- Applicants get assurance that their application is moving forward
- Applicants have a general understanding of when they should hear from VA
- Applicants know what to do if they don't hear from VA

This email will be sent once PEGA has confirmed that an application has been successfully imported, so we can tell the applicant that they're application is being processed and let them know it will take approximately 60 days to process.

Current email template:
<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4debd4ddc20fef5102130adfc8d97dfd476b91b3/image.png" alt="image.png" />

**Comment by marywang2** [comment]
Intake [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/81725)

**Comment by syd-hoeper** [comment]
Link to Figma: https://www.figma.com/design/ZVHyqhH0lZGJ1sz8LsUbk8/Emails-and-confirmation-updates?node-id=10-72&t=ycSKTlead8IGDCXY-11
Link to email pattern documentation: https://design.va.gov/templates/email#example
Link to email content copy: https://github.com/department-of-veterans-affairs/va.gov-team/blob/5f97a222fd88dac069d04985e3bbfcd7cb9aff26/products/content/content-briefs/email-content.md?plain=1

**Comment by syd-hoeper** [comment]
@baltes links above if you could take a look at where this is at so far and provide your feedback

**Comment by baltes** [comment]
Thanks @syd-hoeper ! Left comments for you in Figma.

**Comment by baltes** [comment]
Figma looks good to me.

**Comment by baltes** [comment]
To clarify expectations, all we're looking for is a first draft we can use for testing in staging. The intent is not to use that as final copy in production. If that's not possible to complete, we can close this task.

**Comment by syd-hoeper** [comment]
If that's the case then I'd say this ticket is ready to go and can be closed/rolled over into the next sprint
