### ISSUE TITLE
Update confirmation page copy for 10-10d

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#85787]
Acceptance criteria:
- Confirmation number is removed from the blue box
- Content is updated to match figma
- Updates to text in what happens next section
- Updates to How to contact us section
- Add info about providing docs
<img width="313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS8xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe5460be18b86990861d9edca57465e05b1c0ad0/image.png" alt="image.png" />

- Remove this portion of the page footer:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXoxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e54831c4f2f26642349d54ff815248a9fa88dac7/image.png" alt="image.png" />

[Figma link](https://www.figma.com/design/ZVHyqhH0lZGJ1sz8LsUbk8/Emails-and-confirmation-updates?node-id=46-2584&t=ZX0z3QYY7QeIykKL-1)

**Comment by baltes** [comment]
@michaelclement This is still in a little bit of flux but we can talk about it if you need something to pick up.

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30956). Waiting on:

- [ ] Team approval
- [ ] Platform approval

**Comment by baltes** [comment]
@michaelclement Can we remove the sentence "You should receive a notification confirming CHAMPVA's receipt of your application within 7 days" under the What to expect next heading?

<img width="751" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e573f512d85f1af80f7c1416d3b9be8ad95db716/image.png" alt="image.png" />

**Comment by michaelclement** [comment]
The above update was made this morning, still waiting on platform approval. Thanks!

**Comment by michaelclement** [comment]
@baltes This has been merged to staging and should be visible shortly. Thanks!
