### ISSUE TITLE
Update copy on 10-10d confirmation page

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#85794]
As a CHAMPVA applicant, I need to know the status of my application when I click submit and what to expect next.

### Acceptance criteria
- When my submit gets a 200 response from s3
   - The messaging on the page lets me know my application submitted successfully
   - I get information about when I'll receive an email that my application is being processed
   - I get information on how to contact the VA if I want to follow up
- When my submit gets a 206 response from s3
   - The messaging on the page lets me know that not all of my documents made it through
   - I get instructions on what to do next
- When my submit gets a 400 response from s3
   - The messaging on the page lets me know that my submit failed
   - I get instructions on what to do next

### More info
When a user clicks submit after completing a 10-10d, the site will generate their PDF and metadata and send one or more files to an s3 bucket where it can be picked up by PEGA processes.

At the time of submit, we won't know anything about PEGA's processing status, so this messaging is meant to let the user know that we got their application and when they should expect to hear something new. This is distinct from what we'll send them in an email confirmation, which will happen after we know that their application has been imported successfully into PEGA.

**Comment by syd-hoeper** [comment]
This is not going to be completed this sprint because we do not have all the information we need to instruct users on how to fix the problem.

There is a base template available here in Figma for both affirmative and negative paths: https://www.figma.com/design/ZVHyqhH0lZGJ1sz8LsUbk8/Emails-and-confirmation-updates?node-id=0-1&t=8UZBg9utRaA4Myic-1

**Comment by baltes** [comment]
To clarify expectations, all we're looking for is a first draft we can use for testing in staging. The intent is not to use that as final copy in production. If that's not possible to complete, we can close this task.

**Comment by syd-hoeper** [comment]
Oh okay, if that's the case then I'd say this ticket is ready to go and can be closed/rolled over into the next sprint
