### ISSUE TITLE
10-7959c: Insurance section - copy updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85791]
Changes to the Insurance section on OHI:

- [figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1840-131624&t=x84dMTrkKFRHmarD-0) - Medicare plus Health Insurance Information Alt flow - 6/7)
- [url](https://staging.va.gov/health-care/champva/other-insurance-form-10-7959c/insurance-status) for Insurance section start

Copy changes:
- insurance screen - update header (remove "primary") and question copy
- insurance information screen - update header (remove "primary") 
- additional insurance screen - update header (change "secondary" to "additional") and question copy
- insurance information screen - update header (change "secondary" to "additional")

**Comment by michaelclement** [comment]
Work done in these two PRs ([first](https://github.com/department-of-veterans-affairs/vets-website/pull/30424), [second](https://github.com/department-of-veterans-affairs/vets-website/pull/30471))

Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
| | |
|-|-|
|remove "primary" from first insurance screen|<img width="605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0accadb9e0ef9c5c006b3c5a4c2cc4c14ee9e751/Screenshot%202024-06-24%20at%2009.29.20.png" alt="Screenshot 2024-06-24 at 09.29.20.png" />|
|remove "primary" from insurance info screen|<img width="564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1JQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdad4c11f160c61752acbc53c48ab465e182262b/Screenshot%202024-06-24%20at%2009.29.45.png" alt="Screenshot 2024-06-24 at 09.29.45.png" />|
|change "secondary" to "additional"|<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXlJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--846d520b965648ffaf4c63e0ce2ac65fa3ea42d2/Screenshot%202024-06-24%20at%2009.30.00.png" alt="Screenshot 2024-06-24 at 09.30.00.png" />|
|change "secondary" to "additional"|<img width="669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f244891b4ae668dd6cfdda7b54b6c3c21c4f4a3d/Screenshot%202024-06-24%20at%2009.33.06.png" alt="Screenshot 2024-06-24 at 09.33.06.png" />|

**Comment by michaelclement** [comment]
@marywang2 This has been merged to staging and should be ready for your review. Thanks!

**Comment by marywang2** [comment]
fyi - @syd-hoeper this is ready for review on staging.

**Comment by syd-hoeper** [comment]
@marywang2 @michaelclement looks good to me!
