### ISSUE TITLE
[Call Center] Input into Salesforce Development

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#858]
## User Story
As a member of the insights and analytics team, I need the WHH CRM to be developed with VA.gov needs in mind so I can improve the data being tracked.

## Goal
Identify priority needs in Salesforce development and get approval from WHH team to make the changes we've identified.

## Acceptance Criteria
- [x] Create document of our priorities for the WHH team to review.
- [ ] Get approval from WHH team to make changes we've outlined.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Have had one round of reviews. We are currently waiting to have the edits and changes reviewed again. Tentative deadline for 9/26. [https://app.zenhub.com/files/133843125/8baff444-6f83-438a-a87c-d0d57a62a984/download](https://app.zenhub.com/files/133843125/8baff444-6f83-438a-a87c-d0d57a62a984/download)
