### ISSUE TITLE
Auto-login redirect loop

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#8580]
**Expected Behavior**

Logging in with IAM enabled results in a user with an active SSO session upon redirection back to VA.gov

**Actual Behavior**

The keep-alive call and subsequent `hasSessionSSO` flag is failing, causing a successful login to immediately be redirected to an auto-logout

**Comment by iraqwarvet31** [comment]
This is still an issue unfortunately.
