### ISSUE TITLE
10-7959c: Health insurance section - add character limit to additional comments box

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85817]
As a user on VA.gov, I want to be able to write in the comments box so that I can supply any additional information to get my benefits.

- [Figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1260-85823&t=0fgfbDfvW7L6glrN-0)
- For the Health insurance section, add character limit to additional comments box (in both instances) - it should be 200 characters

Acceptance criteria:
  - Given a user is on the Health insurance section of the form
  - And there is an additional comments box present
  - When the user tries to input more than 200 characters 
  - Then the input should be limited to 200 characters
  - And the user should be notified that the character limit has been reached

**Comment by michaelclement** [comment]
Work is done in [this PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/30840).

Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 @jamiefiore This has been merged in and should be visible on staging shortly. Thanks!
