### ISSUE TITLE
Add "Prepare for your appointment" content to claim exams

### ISSUE THREAD

**Issue by AdamOye** [department-of-veterans-affairs/va.gov-team#85825]
## Issue Description
Add "Prepare for your appointment" section to claim exam appointments.

## Acceptance Criteria

- [ ] The `va_online_scheduling_med_review_instructions` feature flag is on

---

- [ ] When the user opens a Claim Exam appointment
        A `Prepare for your appointment` section shows above the appointment actions
        And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=1-35356&t=tVebbMz7mr4dmJtG-4)
        And the `Learn more about claim exam appointments` link points to the URL: `https://www.va.gov/disability/va-claim-exam/`

<br /><br />

- [ ] When the user opens a canceled Claim Exam appointment
        A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=356-8766&t=tVebbMz7mr4dmJtG-4)
       And the `Learn more about claim exam appointments` link points to the URL: `https://www.va.gov/disability/va-claim-exam/`
 

## Design

[Mockups](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32911&t=MybgwPnCCJcgmy0u-4)

**Comment by ldelacosta** [comment]
Validated in staging. UX team will do a second review. cc: @outerpress

**Comment by outerpress** [comment]
@JunTaoLuo @ldelacosta the font size looks good, and the content is does have semantic tags (`<li>`) - I'm assuming both are tied together, where semantic tags are needed to display the right base font size.

The other two issues from [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85118#issuecomment-2257119441) are still issues. And I wasn't able to test upcoming/canceled, but I know Leah is working on getting test users with those appts.

**Comment by ldelacosta** [comment]
Closing this out and addressing it in [#89551](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89551).
