### ISSUE TITLE
Datadog: add tags to 10-10d monitors to identify paths

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85849]
Add tags to forms so we can track which applicant type is filling out each form (for 10-10d).

This ticket should split out the signer type ("I’m applying for benefits for myself", "I’m a Veteran applying for benefits for my spouse or dependents", "I’m a representative applying for benefits on behalf of someone else")

- check SimpleForms and make sure we are generating all the same data points that they are utilizing
<img width="634" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18b8ccccc31601837505ff8aca5373d6bb977462/2024-06-03_10-57-56%20%281%29.png" alt="2024-06-03_10-57-56 (1).png" />

### Implementation Plan
1. Add some form of this code to models. We will have to change `preparer_type` to something in our JSON
```
STATS_KEY = 'api.ivc_champva_form.10_10d'
. . .
def track_user_identity
   identity = data['preparer_type']
   StatsD.increment("#{STATS_KEY}.#{identity}")
   Rails.logger.info('IVC ChampVA Forms - 10-10D Submission User Identity', identity:)
end
```
2. Call it in the uploads_controller like `form.track_user_identity`
3. Insert into DD dashboard to mimic SimpleForms API but update query to use our info per model (Note: I added a broken one as a template that needs changing)

Ref: 
- `simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb`
- `simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb:56`
- `simple_forms_api/spec/fixtures/form_json/vba_20_10206.json`

**Comment by marywang2** [comment]
fyi @baltes

**Comment by balexandr** [comment]
Added implementation plan

**Comment by balexandr** [comment]
@baltes @marywang2 
@michaelclement found this in vets-website repo. Is this what we want the "User Identity" to be tracked as?
<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fbd4ab6804a76ce4657bde571dd9977735dc7f1/image.png" alt="image.png" />

**Comment by marywang2** [comment]
I can't seem to open that image @balexandr :(
