### ISSUE TITLE
Discovery - Update Form detail pages with non-DB data from spreadsheets

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#8585]
## Problem statement
Drupal provides a migration tool to create 'entities' (taxonomy terms, node pages, etc) from external data. It keeps track of the entities it migrates and ties them to records in the external, source data. So when a migration runs, it looks at each record in the source data and checks to see if it's already been migrated. If it has, migration will update the entity that it created in the earlier migration. If it hasn't, it will create a new entity in drupal.

Forms pages have two sets of source data: the Forms DB, which contains core information about each form (name, number, etc) and a spreadsheet with additional information (e.g. 'related to' categories). If we migrated both sets of data we'll end up with two drupal form pages for each form, one with only core information, the other with only the additional information.

So we can't migrate the additional information in the usual way, but entering it by hand would be a major lift.

## Goal
Investigate technical solutions to automate import of additional form data from spreadsheet.

## Acceptance Criteria
- [ ] Formulate a plan of action for importing additional information into existing form pages in drupal.
- [ ] Present the plan along with an LOE so that a decision can be made on whether it's worth moving forward with an import tool.

**Comment by stephorkandatx** [comment]
Closing based on discussion in standup . Not needed.
