### ISSUE TITLE
[CY] 20 submission ID's that need PDF

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#85866]
There are still 20 submissions IDS that no PDF's were created for that need a resolution (either batch or manual) 

1. Identify which of the 20 can't be fixed and done in the batch process and put into the input files or which ones need to be "emergency fail safe - raw output of the data into 526 PDF.
2. For the ones that are quick fixes, fix the issue and rerun the batch for the input files
3. For the ones that are not easy fixes, create the raw output of the data and make the 526 PDF. 
3. Create and test the links 

Meeting link
https://coformaco.zoom.us/rec/share/vFdH6fsaCcUXfNHeXwucYT_pKoE0sfLUe0-nMTbEEicL6mSBrRQNdD3T6cDUoPG3.0FkEVXdpIdnT_Vvm
Passcode: c8^.C.Wy

**Comment by SamStuckey** [comment]
[ids_to_fix.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0poQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d147f59efea936b451abb891ec3ea62b66a63e67/ids_to_fix.txt)
These are the 20 IDs we are targeting with this work

**Comment by SamStuckey** [comment]
# Of the 20 given, my recommendations
## we should retry PDF generation:
- 2 of these are impossible (or leap year) dates. If we roll the data back to 2/28 we will be able to generate these. (less than a day of work)
- 4 these have problematic user uploads. IF we are allowed to simply exclude the problematic upload, these are easy to fix (less than a day of work)
- 6 of these have very problematic user uploads that cannot be easily filtered. I could manually go through each of these and find the breaking upload and exclude it. This would be 2 - 3 days of work. Again that is IF we are ok with excluding user uploads
## Too complex, send to text dump:
- 3 of these have some malformed form data that breaks the API. These problematic values could probably identified through a manual trial and error process, but it's possible that what's left will still have more issues.
- 5 of these just completely blow up the API. Debugging these would require cross team collaboration and likely be very complex, also with no guarantee we will be able to easily salvage what remains

**Comment by SamStuckey** [comment]
Next steps from @emilytheis 
- for the 2 impossible date failures, correct the data for future batching. These will be rolled into our next batch rerun. Emily has agreed to own making sure these submission IDs are included with the next list for reruning

**Comment by SamStuckey** [comment]
IN REVIEW:
- the 2 submissions with impossible dates (`906899, 906997`) have had their data corrected and are ready for rebatching
- the other 18 have been packaged and shared with @emilytheis in sharepoint as of 6/12/24 and are awaiting approval or feedback before we close this ticket.
