### ISSUE TITLE
Profile 2.0 breadcrumbs do not show current section

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#8586]
There are breadcrumbs at the top of each page in Profile 2.0, the last crumb in the trail is missing.

In this screenshot, there should be a final `Military information` crumb that should be bold and the `Your profile` crumb should be clickable.

![Screen Shot 2020-04-29 at 1.54.00 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/de8c70b6-e357-4086-a3d2-67b44a2c123a)

**Comment by sanlouise** [comment]
@mshea0606 Could you validate this ticket? Thank you 😀
