### ISSUE TITLE
SOCKS access for Dariusz Dzien

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#85879]
### Your Name

Dariusz Dzien

### Your Email

dariusz.dzien@adhocteam.us

### Your GitHub Handle

ddzz

### Your Role and Team

Full-Stack Engineer on VSO Accredited Representatives Team

### Product Manager (PM) name and email

Mike Marinos mike.marinos@agile6.com

### Product Owner (PO) name and email

Jen Bertch jennifer.bertch@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHtctnCPuv64KH+5EJULrzr9mHf9rh3PoD1W+16WB1t7 dariuszdzien@dariuszdzien-C02D1CQTMD6M

### E-QIP Transmittal Confirmation

<img width="1417" alt="Screenshot 2024-06-13 at 12 05 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3535749/4cd69a77-d27c-497b-a355-da4fd842c90d">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
I merged your SOCKS PR. Please let me know if you have any issues

**Comment by stoiven** [comment]
Closing out this ticket as SOCKS was granted
