### ISSUE TITLE
S56 [Longest Day 😎]

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#85878]
# Sprint Goals

| Previous Sprint | Next Sprint |
| :--------------  | ----------:  |
| ◀️  #85091          | #87301  ▶️        |

**Scrum Hero**: @dfong-adh  

### Priority 1: Remediate historical failures ([WIP epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80241))

**Send historical failure data for review to determine which claims need to be remediated.**
- #86343

### Priority 2: Submission Stability and Storage ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293))

**Update the existing decryption library to handle the latest encryption methods, so Veterans can submit more types of PDF evidence.**
- #83503
- #83132 

**Store Submissions**
- #84329 
- #84332 
- #84348

### Priority 3 : Move the 4142 within 0995 to LH

**Move the 4142 within the 0995 off EMMS API**
- #85680 

### Priority 4-5: HLR and SC Form Version Updates (epic links: [1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82220) and [2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82219))

**Mock designs and kickoff FE work for HLR and SC.**
- #81723
- #83774 
- #83861
- #85851
- #87098

### Accessibility, and Design Enhancements

- #85786 
- #82249 
- #80475

### Bug/Engineering Backlog

- #77455 (Adding this since we decided to close the other ITF ticket - Annie, 5/30)
- #83324 
- #81090 (Work taken on by another team)
- #83078 
- #79233
- #86685
- #86921 (bug)
- #65647
- #87096

---

## Blocked Items

- #83078 
   - Waiting for content team to finish their work
- #83772
   - Blocked until LH [updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83772#issuecomment-2154931490) the submission endpoint to support new questions
- #81507
   - Waiting for Lighthouse to release [new endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81507#issuecomment-2115701294) to capture generated PDFs

---

## Team Capacity

**Outages:**
- 6/19 - Holiday
- 6/19 - 7/1  - @anniebtran 
- 6/20, 6/21, 6/28 - @Mottie 
- 6/24, 6/28, 7/1, 7/2 - @skylerschain 
- 6/24 - @eileen-coforma 

## Sprint Risks and Assumptions
- TBD

## Reference documentation

- [Q3 Roadmap Prioritization](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/product%20management/Prioritization/DR%20Prioritization%20Scoring%20-%20April%202024.xlsx?d=wb661cf77374d4321969f619e845cabbd&csf=1&web=1&e=GIwNAH)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)

**Comment by eileen-coforma** [comment]
@shaunburdick  Requesting to add #85851 to sprint if @Mottie  finishes #83774
