### ISSUE TITLE
Login page should support a "to" parameter to customize post-login redirect

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#8587]
In discussion with Cerner team for their use of the static login page, they would like to pass a query parameter `to` to the login page, in addition to the `application` parameter. The `to` parameter would indicate where the user should be redirected to after signing in.

Allowing an entirely free-form redirect is a bad idea because of risks described here: https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

So, the base domain of the redirect should continue to be based on the configured value of the `application` parameter, with the `to` parameter only specifying the path part of the redirect.

Any other mitigations suggested in that OWASP guideline (such as stripping newlines) should be included.

Additionally, the Cerner team is encoding a second `to` parameter in their URL (for an additional redirect after our redirect), so we need to make sure whatever double-URL encoding is necessary to support that works correctly.

**Comment by patrickvinograd** [comment]
I have a real initial attempt at this in branch `pv-additional-redirect-param` that I pushed up to master. Leaving it there in case somebody takes this task over from me.

**Comment by patrickvinograd** [comment]
Example of a `to` parameter that Cerner is likely to provide, note the additional `to` parameter nested within their redirect location (but with the embedded `?` encoded):

```
https://va.gov/sign-in?application=myvahealth&to=%2Fsession-api%2Frealm%2F48745338-dc4e-47aa-8a46-e9eb830dbc51-ch%26to%3Dhttps%253A%252F%252Fpatientportal.myhealth.va.gov
```

**Comment by patrickvinograd** [comment]
Above URL is not quite right, I think there's an encoded `&` where there should be a `?`. Anyway I think this URL is what we'd want for staging:

```
https://staging.va.gov/sign-in?application=myvahealth&to=%2Fsession-api%2Frealm%2Ff0fded0d-d00b-4b28-9190-853247fd9f9d%3Fto%3Dhttps%3A%2F%2Fehrm-va-test.patientportal.us.healtheintent.com
```

**Comment by ericbuckley** [comment]
Originally we were thinking that the `application` parameter would control where to redirect the user to after login, but now with this request we have `to` needed to specify a custom path.  In other words, `application` becomes the domain of where to redirect and `to` becomes the path.

Is there really a need for 2 parameters to encapsulate this logic?  Can we simplify this logic with just 1 parameter, and have a whitelist in vets-api to make sure that we are redirecting users to acceptable domains?

**Comment by patrickvinograd** [comment]
Good point. There's definitely some path-dependence to our solution here since we started with just the application parameter. 

Consuming apps would have to customize the base URL per-environment. Whereas today we control that mapping and can configure it per-env.  So that's a slight amount of work that pushes from our plate to theirs but that's the only tradeoff I can think of.

**Comment by ericbuckley** [comment]
I didn't think about the different cerner environments, thats a good point
