### ISSUE TITLE
Payment History VBA Pre-MVP 1.0 - Implement page(s)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#85887]
### Description
This ticket covers the implementation of the Payment History page(s) for the VBA Pre-MVP 1.0. The implementation should reflect the design specifications and data mapping agreed upon in the previous review.

**Given**: The design and data mapping for the Payment History page(s) have been finalized
**When**: A user navigates to the Payment History page
**Then**: The user sees an accurately rendered page with correct debt details and transaction history
Tasks

- [x]  Set up the basic page structure according to the design
- [x]  Implement the debt details section, including current balance and original overpayment amount
- [x]  Create and populate the transaction history table component
- [x]  Verify backend API contains transaction data 
- [x]  Handle edge cases and fallback scenarios as agreed in the design review
- [x]  Remove **Note** from payment history section right below where the table is added 
- [x]  Include On This Page reference above

### Acceptance criteria

- [x]  The page layout matches the approved design, including all specified components
- [x]  The debt details section correctly displays the current balance and original overpayment amount
- [x]  The transaction history table is implemented and populated with correct data from the API
- [x]  Edge cases and fallback scenarios are handled as specified in the design review

### Testing

Testing passed and documented in this ticket based on the "Then" statement in the description

### Testing procedure:
- [x] Manual testing 
- [x] Unit testing

**Comment by HeatherRienks** [comment]
The team met on 6/25/24 to discuss the scope of work needed to complete this effort. This is the only FE ticket and we will create one backend ticket to add dummy data to vets-api-mockdata (fake endpoint). We plan to add it to “ready” but will not pull into S128.

FYI @denisecoveyduc @Tom-Davis

**Comment by OptionSelect** [comment]
Per convo with Joe only show increases/decreases that are 0408 code!

**Comment by OptionSelect** [comment]
Draft PR created: https://github.com/department-of-veterans-affairs/vets-website/pull/30559

**Comment by OptionSelect** [comment]
Per convo with Aaron officially moved to blocked as we await completion of endpoint to slot real data request in place of dummy stuff. Also giving design an opportunity to style over our initial laydown!

**Comment by HeatherRienks** [comment]
FYI @josephrlee  @mgleo 
Also, per last meeting on6/27 with DMC Team (Daniel Wildman, Pam Corbin-Jones), we are slated to receive the needed data in the coming week(s).

**Comment by OptionSelect** [comment]
Throwing the figmas in here just so I can keep track of em!
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=359-9076&t=qw2BMUdtc6tSxRT6-0
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=139-14044&t=8lY9zUJQ5pcesCxc-0

**Comment by mgleo** [comment]
@OptionSelect Here's a direct link to the Figma art board for Payment History VBA Pre-MVP 1.0:
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-17591&t=nSZ4H50XWQXOybBy-1

You should see the annotations and you should see the title "**Phase 1 MVP**" above the mockups (if not it may not be the correct mock ups).

**Comment by HeatherRienks** [comment]
Per Pam Corbin-Jones, Daniel (DMC) has completed his work and they have slated SQA this week and will be done by end of next week (so, 7/12/24!)

**Comment by OptionSelect** [comment]
Still awaiting data from external team to replace mocked data we laid down to implement component.

**Comment by OptionSelect** [comment]
Now blocked until back end formats data into mocks for FE by https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88596

**Comment by OptionSelect** [comment]
Joe left TODO's around to be removed in this effort as well.

**Comment by HeatherRienks** [comment]
@maxx1128 - please let @OptionSelect know when your efforts are completed- he is blocked until then!

cc: @Tom-Davis @alatempa24

**Comment by OptionSelect** [comment]
Per convo with Heather we are closing this ticket and creating a new one for the final implementation and TODO removal.
