### ISSUE TITLE
Implement content changes for users with "no access to MHV"

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#85897]
### User story

As a user without access to MHV, I want to quickly and immediately understand that I do not have access to MHV upon arriving at the home page, and I don't want to read through other unnecessary content. 

### Notes
- Follow-on implementation ticket from [design ticket 84518](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/84518)
- [Mural of sign-in account checks and back-end systems](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717177396025/367057c4a9219404c3b7080e71210082b3c65771?sender=uebde62ceb342c6477fb09406)
- [Figma file (section called "User does not have MHV access")](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=942-11556&t=r4wydZAgdwTCI5oH-1)

## Acceptance criteria
- Implemented the hiding of some landing page content per designs when the "no access to MHV" alert is displayed
  - secondary nav
  - expanding alert
  - links below "need help?"
- UX review
- QA review
- a11y review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the change to the "no access to MHV" alert matches Figma designs

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDRBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ff61f885fe6643e540f8e8fd582a8af7cd9dfd5/unregistered.png" alt="unregistered.png" />
