### ISSUE TITLE
Refactor Debt Selection, Copay Selection, and Waiver Agreement to Use VaCheckboxGroup

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#85928]
Description
This issue aims to refactor the following sections to use the new VaCheckboxGroup:

1. Debt selection
2. Copay selection
3. Waiver agreement

Tasks

- [x] Refactor debt selection to use VaCheckboxGroup
- [x] Refactor copay selection to use VaCheckboxGroup
- [x] Refactor waiver agreement to use VaCheckboxGroup
- [x] Ensure all related tests are updated and passing
- [x] Ensure `h3` focuses for screenreader users
- [x] Determine validation

Acceptance Criteria

- [x]  Debt selection uses VaCheckboxGroup
- [x]  Copay selection uses VaCheckboxGroup
- [x]  Waiver agreement uses VaCheckboxGroup
- [x]  All related tests are updated and passing
- [x] `h3` focuses when page is loaded

Notes
This follows up on the previous PR where the shared checklist was refactored to use VaCheckboxGroup. https://github.com/department-of-veterans-affairs/va.gov-team/issues/75752

**Comment by OptionSelect** [comment]
Work for this is happening under [this one](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/77425) my mistake!
