### ISSUE TITLE
Design system components throw false positive on VA security scans

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#85927]
---
# Bug Report or Design System update

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

We have a web application that is using the VA Design System and deploying to Lighthouse Delivery Infrastructure. Deploying to LHDI requires your application go through a code scanning process. The code scan triggered on this line in va-promo-banner:

https://github.com/department-of-veterans-affairs/component-library/blob/f7c77a5ba23c4ef2940e7dbfe66ee8e2d2e495db/packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx#L12

Because the const is named `foo_KEY` (even though it is referring to a _hash/dict key_, the code scanning tool thinks it is a hard-coded _secret key_.

This is a false positive, and can be dismissed as such, but it's a little bit of extra friction for every team who runs into this. 

## What I expected to happen

Ideally importing and using design system components should not result in any new security scan findings for my application. 

## Additional Context
* Narrowly scoped fix: change the const name above to not include `_KEY` so as to avoid this particular false positive.
* Broader fix: Ensure that the two approved code scanning tools (CodeQL and Snyk) are run on the design system code. While you are not directly deploying to LHDI, you could essentially be preflighting your product to save effort and cognitive load of the many teams who might adopt the design system and deploy to the LHDI platform. 

[Documentation for running the LHDI code scanning tool as a Github Action
](https://laughing-adventure-wllepqe.pages.github.io/Lighthouse-delivery-infrastructure-tools/Using-the-DI-tools/Step-5-Deploy-Your-API-To-Higher-Envs/modularization/). As this is a library, you would only be doing the code scanning, not the image scanning. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20694532/79f39af0-4dc2-4a1b-915d-982febf8193b)

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/85927?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by jamigibbs** [comment]
Updating the constant name in the component is straight forward but it would mean that users that had previously dismissed the promo banner will need to do it again. The value is set in `localStorage`.

**Comment by patrickvinograd** [comment]
Changing the const **name**, i.e. the variable name, shouldn't affect users - and that's where `_KEY` is present. I.e. as long as the value of that const remains `DISMISSED_PROMO_BANNERS` everything should stay the same, I think?

**Comment by jamigibbs** [comment]
@patrickvinograd Ah you are right! I'm not sure why I thought the localStorage name itself would be affected. Nothing to see here.
