### ISSUE TITLE
10-7959c: 'new' address question - add to mailing address screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85939]
user story TK

[Figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1156-74334&t=ellKVZDwpygn7GVI-0)

- add new address question to the bottom of the 'mailing address' screen
- if user selects 'yes' and 'I don't know' options, the 'new address' box should be checked on the PDF (as a trigger to those processing the form)

**Comment by marywang2** [comment]
Thanks @jamiefiore I added a placeholder ticket for it [here](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/85939), we can review in next refinement.

**Comment by michaelclement** [comment]
Work is done in these two PRs:
- [Frontend](https://github.com/department-of-veterans-affairs/vets-website/pull/30411)
- [Backend](https://github.com/department-of-veterans-affairs/vets-api/pull/17168)
 
Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
<img width="474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWgwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb02b510c0db58bbb15dbf08ba677983d3e88436/Screenshot%202024-06-18%20at%2016.37.14.png" alt="Screenshot 2024-06-18 at 16.37.14.png" />

**Comment by michaelclement** [comment]
| yes/unknown | no |
| - | - |
|<img width="610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXAwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1beef039e075bd71ff304756ce384970e3a3584/Screenshot%202024-06-18%20at%2016.15.38.png" alt="Screenshot 2024-06-18 at 16.15.38.png" />|<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXQwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--602ec244ac1f86d32e0472e29b35e9f07726d7e1/Screenshot%202024-06-18%20at%2016.15.07.png" alt="Screenshot 2024-06-18 at 16.15.07.png" />
|

**Comment by michaelclement** [comment]
@marywang2 Merged this into staging, should be ready for review shortly. Thanks!

**Comment by marywang2** [comment]
This looks good - appreciate the screenshots and PDFs.

**Comment by jamiefiore** [comment]
Agreed, It looks good. Thanks @michaelclement @marywang2
