### ISSUE TITLE
Education rewriting restart: Post-9/11 GI Bill (Chapter 33) rates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8593]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub (also in Drupal already?)
- [X] Initial copy edit
- [X] Strategy/voice edit 

**Steps needed to complete this work now:**

- [ x] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x ] Identify and address any potential content anomalies in preparation for moving to/updating in Drupal (Anne or Randi)
- [x ] Finalize existing draft in Drupal (Anne or Randi)
- [x] Add cross links to this page from other appropriate pages (Anne or Randi) - ***yes but 2 pages aren't yet built***
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
 - **Url:** /education/benefit-rates/post-9-11-rates/
 - **Left nav label:** Post-9/11 GI Bill rates

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page:** https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080119.asp
 - **SEO keywords:** post 911 gi bill rates, gi bill housing allowance, post 911 gi bill pay chart, gi bill bah rates, post 911 gi bill bah rates, gi bill pay rates, gi bill payment rates (need to add just 2 primary/secondary in Drupal meta data)
 - **What’s needed for rewriting:**
   - Incorporate the information and rate tables from: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080119.asp. 
   - Edit to align with plain language and VA.gov style standards.
   - Optimize for SEO.
   - Make clear that these rates also apply to the Fry Scholarship.
   - Consider how we might structure the page so that the user can easily get to/see the info they need without feeling overwhelmed, but also avoiding hiding pertinent info.
   - Consider how we might include the info on prorated rates and the chart from https://gibill.custhelp.va.gov/app/answers/detail/a_id/947. Could potentially be a question ("Will I get the full rate for these benefits?") or an accordion under each table.
   - Link to new “GI Bill resident rate and requirements” page. 
   - The page links out to https://gibill.custhelp.va.gov/app/answers/detail/a_id/1412/ and https://gibill.custhelp.va.gov/app/answers/detail/a_id/1480 for more info on housing allowance rates. Explore whether we can incorporate that additional info into this page while keeping content brief and focused.
   - Include links to the historic benefit rate tables, at the bottom of the page. We will be asking SMEs if these can be made into PDFs, but for now we'll link to legacy pages.
   - Crosslink to other pages (Yellow Ribbon, pages within How to Use Your Benefits as relevant.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/post-9-11-rates.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by AnneHurley** [comment]
Page is built in Drupal, but not yet shared with SMEs: 
prod.cms.va.gov/node/1009/edit


Note: need to check these two links/pages: 
--qualifying for in-state fees
--monthly housing rates

And there are 3 historic rates still linking to TeamSite pages.

Source legacy page: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080119.asp

@DanielleThierryUSDSVA  and @RLHecht  FYSA

**Comment by AnneHurley** [comment]
@RLHecht @DanielleThierryUSDSVA  This page was built in October, with the headline "2019". But I see the Montgomery GI Bill rates are headlined "2020" and the intro says "...for the 2020 school year." 

I feel like this page should be consistent with Montgomery, so that would mean changing the headline to 2020. But these rates go from August 1 to July 31 - so one could make the case for 2019. 

Would we ever consider a new naming convention for education benefits that cover the school year, as in '2019-2020 XX rates"?

**Comment by AnneHurley** [comment]
@RLHecht  This page is updated and ready for your review:

prod.cms.va.gov/node/1009/edit

All dates and rates have been updated to 2020-2021 year. Note that several benefits that are flat fees have stayed the same, as have percentages. 

I added a link for "Rates effective August 1, 2019," with a link to the benefits.va.gov page for now, until we decide if we want to clone the 2019 page, or do it as a PDF and if the latter, when we decide on a PDF convention. 

Also there are 2 broken links but it looks like those 2 pages just haven't been built yet. I will make sure to do those 2 pages and then update this page with the node links.
@DanielleThierryUSDSVA FYSA

**Comment by RLHecht** [comment]
@AnneHurley I read this over. I deleted the fourth historic rate link (the oldest one) and adjusted one of the new rates numbers in a table.

**Comment by AnneHurley** [comment]
@RLHecht I added the new node ID links (housing, in-state residency) as well as the REACT URL for the YR tool on this page. 
Could you check to see why there are still a couple of broken link alerts, and let me know if I need adjust anything?

**Comment by RLHecht** [comment]
@AnneHurley I checked over the page and the new node IDs look OK. Per Slack convo you are going to ask CMS about the broken links being a bug.

One question I have is will the Yellow Ribbon Program tool be live before we are finishing these pages? If not, the link you added to the tool won't work. We may want to take it out and only add it it once YR is finalized.

**Comment by RLHecht** [comment]
Fixing all broken anchor links. This page is now ready for Danielle.

**Comment by psanders86** [comment]
@RLHecht This is ready for a copy edit.

prod.cms.va.gov/node/1009/edit

Additional source material:
https://www.va.gov/resources/how-we-determine-your-percentage-of-post-911-gi-bill-benefits/
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
