### ISSUE TITLE
[Tech Debt] Replace instances of AlertBox in vets-website with Alertbox from formation-react

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#8594]
### Description:
Everywhere in `vets-website` where we are using an instance of `AlertBox`, we are grabbing it from `formation-react`. There are a few exceptions, and we should aim for consistency in the app and always grab `AlertBox` from `formation-react`.

### Tasks
- [ ] Investigate whether instances of `src/applications/gi/components/AlertBox.jsx` can instead use Alertbox from `formation-react`
- [ ] If true, replace those instances with AlertBox from `formation-react`

**Comment by erikphansen** [comment]
+1000. This might be related (or not) but I've seen instances where alerts don't have their headline aligned with the alert's icon. Example: 
![image](https://user-images.githubusercontent.com/20728956/80726149-e2171300-8ab8-11ea-9c77-aea3caf5515a.png)

**Comment by erikphansen** [comment]
Oh and I misread the original ticket on my first pass. I thought this was about the fact that we likely have places in `vets-website` where we don't use a React component at all and instead have raw DOM markup (probably cut and pasted from the sample HTML here https://design.va.gov/components/alertboxes)

**Comment by sanlouise** [comment]
Ah, yes you are right. I think replacing those instances (and investigating feasibility) should be a separate ticket.

These are the places not using an `AlertBox` component:

```
- vets-website/src/platform/forms/save-in-progress/FormSaved.jsx
- vets-website/src/applications/post-911-gib-status/components/UserInfoSection.jsx
- vets-website/src/applications/pensions/components/IntroductionPage.jsx
- vets-website/src/applications/pensions/helpers.jsx
- vets-website/src/applications/hca/helpers.jsx
- vets-website/src/applications/edu-benefits/1990/helpers.jsx
- vets-website/src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx
```
