### ISSUE TITLE
404 React component uses h1 heading

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#85960]
### User story

As a disabled Veteran, I want the page not found (404) for the React apps to be more readable by screen readers, so I can better understand the error message.

### Notes
- The current 404 page-not-found component uses an h3 for its main heading. It needs to be an h1 for proper screen reader action.

Possible tasks:
- 

## Acceptance criteria
- The page-not-found React component uses an h1 heading for its main heading.
- The page-not-found React component's main heading has keyboard focus upon loading, so screen readers can read the heading upon loading.
- QA review
- A11y review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the "page not found" page uses a h1 heading.

<img width="1862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58382a18264fb0a4e181cdec40b81ab445949661/h1.png" alt="h1.png" />
