### ISSUE TITLE
Design Intent - Design Feedback - Appointments Team, Appointments, Medication Review

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#85963]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Listen to the recording for Matt Dingee and Ryan Thurlwell's feedback.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: Check the [guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else) on additional info component. We prefer to only include critical information inside this component and not too much content.
- [x] Must: Matt Dingee: Update the new TTY icon.
- [x] Should: Use the [no-border additional](https://design.va.gov/components/additional-info#no-border) info component within the bullet to save space.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by outerpress** [comment]
> Check the [guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else) on additional info component. We prefer to only include critical information inside this component and not too much content.

@allison0034 @erinrwhite I fully agree and we'll work on nudging the stakeholder groups to slim down the content. There's a better chance it'll get read if it's shorter. 

I'll update y'all on this when we have the final content (#85061 is the tracking ticket for that).

FYI @laurwill @DanielleThierryUSDSVA @loripusey @brianseek

**Comment by outerpress** [comment]
> Must: Matt Dingee: Update the new TTY icon.

@allison0034 I confirmed web (appts and pre-check-in) doesn't use an icon for TTY, and the icon change is already on mobile's radar - cc @kidlaurenpeace @rtwell 

So I'm going to call this item done, but let me know if you need us to do anything else for this.

**Comment by outerpress** [comment]
@allison0034 we're addressing this by replacing the additional info in the medication review prompt with a link to an external page. [Updated designs](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=1-2)

Thanks @laurwill for the idea! Also cc: @kristenmcconnell @erinrwhite. 

I'm going to close out this ticket, but feel free to reopen if you have other concerns.
