### ISSUE TITLE
[Tech Debt] Clean up addressFormatter and use it in AddressValidationModal

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#8596]
### Description
While working on the international addresses preview, I noticed that we have some dead/outdated code in the `addressFormatter` helper function. We should especially clean up how we format military addresses.

We need to use the `addressFormatter` in the `AddressValidationModal` as well to ensure consistency among address formatting in our profile.

### Acceptance Criteria
- [x] Investigate if we are ever using `militaryPostOfficeTypeCode` and `militaryStateCode`
- [x] Undo passing in `type` to the `addressFormatter`
- [x] If first acceptance criteria is `false`, remove `case` statement for `military`, instead bucket military addresses with domestic ones
- [x] Use `addressFormatter` in `src/platform/user/profile/vet360/containers/AddressValidationModal.jsx`
- [ ] Ensure checkbox on Address Confirmation modal is not stretched out when using long addresses
- [x] Ensure unit tests are updated

**Comment by sanlouise** [comment]
@mshea0606 Hi Matt, this ticket is ready for review when you have a moment. I tested this PR is by checking that the addresses are still formatted correctly both in the Profile, as well as on the profile validation modal. Thank you!

**Comment by mshea0606** [comment]
Thanks @sanlouise!
