### ISSUE TITLE
Add Queue Exhaustion Block for NewStatementNotificationJob

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#85964]
We got a report from the platform team that our `NewStatementNotificationJob` is posting a lot of 'queue exhaustions'. It was recommended we add some code to handle this gracefully. 

[Slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1718374820439319)

**Comment by HeatherRienks** [comment]
@digitaldrk - any update on this ticket?

**Comment by digitaldrk** [comment]
PR submitted for review to our team and platform.

Closing this one since it's un-planned work and it's a small PR

**Comment by digitaldrk** [comment]
This has been Merged
