### ISSUE TITLE
Cancel button displays on a noncancelable appointment

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#85972]
## Summary
On staging, for some appointments the cancel buttons are displayed/enabled when the appointment is not able to be cancelled, resulting in an error message displayed to the user if the user attempts to cancel the appointment. 

[OCTO VA Slack thread mentioning issue](https://dsva.slack.com/archives/C062LRFAX7S/p1718218955926719)

## Steps to Reproduce
**Judy Morrison (`judy.morrison@id.me`):** 

1. Login as test user
2. Navigate to _upcoming appointents_ or go directly to test user's [In-person appointment](https://staging.va.gov/my-health/appointments/CERN52499028)
3. Click _Cancel appointment_ button
4. Click _Yes, cancel appointment_ button to confirm cancellation

### Actual Result
An error screen is **_correctly_** displayed after cancel confirmation as the appointment is not able to be cancelled and has `"cancellable": false` in data returned from the appointments endpoint.

<img width="886" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/587812/a95b5bb4-ca0c-4be1-909f-515ea16ec1a9">

### Desired Result
The user should not be given the option to cancel appointments when `"cancellable": false` is returned as part of appointment object. 

The cancel button should not be displayed to the user.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by ldelacosta** [comment]
Validated in staging. No issues to report. Closing out the ticket. cc: @JRRoof 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--173da92b624b05f69cd9d925cd8f48d070eeedb6/Screen%20Recording%202024-06-24%20at%202.16.07%E2%80%AFPM.mov)
