### ISSUE TITLE
Spike:  Estimate the scope of work to retrieve military history and and existing claims info

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#85982]
# Overview
In an effort to improve the form process, we could auto-populate many data points of the existing pension form.
This ticket is building off previous work that was done but should provide an estimate for work if we wanted to pull:

- military history
- claims/disability information

Previous research we did on pre-filling veteran information:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70121
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70482

VA Profile (need to be on Azure):
https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/Military-Personnel-Data.aspx?csf=1&web=1&e=QUwByA

# Assumptions
Use only the VA Profile API, not things like [BIE contention event queues](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIE-contention-event-queues-User-Guide)

#  Acceptance Criteria
- Provide an estimate for the work involved in pulling from VA Profile for military history (service dates, for example)
- Provide an estimate for the work involved in pulling from VA Profile for claims/disability information (has existing claim? existing claim status)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/85982?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by mjknight50** [comment]
The first step of the process is to fill out an intake 

lib/va_profile/profile/v3/service.rb

**Comment by mjknight50** [comment]
Summary:
The technical parts of pulling in military history and/or claims history are not difficult.  There is existing code to accomplish this.  The unknown here is what specific attributes we are looking for and how they would be rendered on the front-end.
With a fully scoped ticket, the technical side of this could be accomplished in a single sprint.

**Comment by sanjabaj2** [comment]
As far as what needs to be rendered on the screen, can we just display same fields that we are asking veteran to enter? Is the info here enough for UX folks to start the design?

**Comment by mjknight50** [comment]
Yes, I think this could enter a new phase where someone maps the form fields they would like to see populated back to the data elements available.  
cc @matt4su

**Comment by matt4su** [comment]
Desired fields as they appear in the 527 EZ:                                                                                                                                             Branch of service (*Required)- valid values: Army, Navy, Air Force, Coast Guard, Marine Corps, Space Force, USPHS, NOAA 

Date initially entered active duty (*Required)
For example: January 19 2000

Final release date from active duty (*Required)
For example: January 19 2000

Military Service number if you have one

Place of your last separation
City and state or foreign country

Did you serve under another name? (*Required)
If answer is yes:
First name (*Required)
Middle name
Last name (*Required)
Suffix
(this is a list loop that accommodates unlimited names)

Have you ever been a prisoner of war? (*Required)
If answer is yes:
Start of confinement
For example: January 19 2000
End of confinement
For example: January 19 2000

**Comment by mjknight50** [comment]
How would you like us to use this data for each of the fields you have identified?
Pre-populate the data but allow it to be changed?

**Comment by matt4su** [comment]
yes checked with the PM of another form that prefills this info and they indicated the best practice is to prepop but make editable in case the Veteran needs to make a change.

**Comment by mjknight50** [comment]
Created new ticket to track this.
