### ISSUE TITLE
[BE/QA] 10-10EZR Attach Docs: Set "Document Type" to a default value on the backend and send to VES

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85991]
As a Veteran, I do not want to have to select one of the default Document Types from the pre-existing list as I find it confusing when my uploaded document isn't one of the listed documents, but it is one that the VA is requesting.

- [ ] Work with Josh F. to determine how we preset a value
- [ ] Confirm with team and QA which value
- [ ] Build out and create unit tests
- [ ] Write test cases
- [ ] E2E QA testing
- [ ] **Success: The document type is default to one value on the backend and sent to VES**

**Comment by coope93** [comment]
If nothing is passed to the backend from the client, the document type for every attachment defaults to the value `5`. Relevant code is in the `enrollment_system.rb` and is `'va:type' => is_dd214 ? '1' : '5',`. The client code in @mkerns1's [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30306/files#diff-f5701288e56de039c84e9935201ff168389f9791b1d7d4bad87e903fdf710f63R1) does not set the `attachmentId` on the front end so nothing will be passed to our backend code, resulting in `5` being passed for every document type.
