### ISSUE TITLE
Design Intent - IA Feedback - Veteran Facing Forms - Form Review page changes (VADS pattern)

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#86001]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- FWIW, I am on the "edit by page" camp and think it aligns with our one-thing-per-page practice a little better. Interested to see how it tests.
- During our call I mentioned that the hub and spoke model for edits that introduce new questions would be less cognitive overload. After hearing Ryan's POV, I agree with him - we shouldn’t let people get to the final review page until all fields are filled.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Should: make sure users know the form isn't submitted yet** This design is a departure from the current review design (great!) and makes the page longer (fine!). The page's header could do some lifting here to indicate "almost done!" Y'all might also assess during research whether users think this is the end of the form or if they recognize that they still need to click through and submit.

- [ ] **Consider: "continue" button text for edit screens** It might be worth testing a couple of text variations on this button. "Save and return to review”?

- [ ] **Consider: design cues from Gov.Uk patterns** [Gov.Uk's task list](https://design-system.service.gov.uk/components/task-list/) and [summary list](https://design-system.service.gov.uk/components/summary-list/) patterns and their accompanying github comment threads might be of interest here, just to see how different designers across the pond are grappling with this.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by jeana-adhoc** [comment]
All of these items have been considered and documented in the [design decisions](https://www.figma.com/design/kBH2U6bfC6sA9Fim3gcnuc/WIP---Review-Page---Edit-by-page?node-id=432-65242&node-type=INSTANCE&t=i9kQjfr194H3T4Xz-11) page of the figma file.
