### ISSUE TITLE
Daily Qualitative Data Request

### ISSUE THREAD

**Issue by katbrinkley** [department-of-veterans-affairs/va.gov-team#86005]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

06/17/2024

### Date Range End

08/02/2024

### Product Name(s)

MHV Landing Page

### Product Description

The landing page serves as a bridge between VA.gov and MyHealtheVet (MHV) and evolves transparently while MHV applications are being integrated into VA.gov It provides a single sign-on authenticated experience between VA.gov and MHV and offers an intuitive and accessible front door to health benefits and information.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/my-health/ (only, not sub-directories/sub-paths)

### Sub URLs

No

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

katlyn.brinkley@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by jonathanjnelson** [comment]
Hi @newworld2616, 

Can we please add additional emails/people to this pull? 

Thank you! 

jonathan.nelson@va.gov 
kathryn.mccafferty@va.gov
sara.sterkenburg@va.gov

**Comment by newworld2616** [comment]
Hi, sure, I will share them to the listed emails. Thank you.

**Comment by newworld2616** [comment]
Hello, Could you clarify please, the end date is 08/02/2024. I shared the data for one of the data request. Just want to make sure when you would like to receive this data request. Thank you.

**Comment by katbrinkley** [comment]
Hi Sarifa! The end date of the daily pull request is 08/02/2024, so we basically want to be able to see data daily until then (it's our post-launch period of monitoring). This is for all Medallia feedback. Let me know if that doesn't answer your question, thank you

**Comment by newworld2616** [comment]
I see, this is the same request for daily pull. Got it. Thank you for confirming.

**Comment by newworld2616** [comment]
Completed!
