### ISSUE TITLE
Front end Rec 10: Make page headings unique

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#86011]
As a CHAMPVA applicant, I want pages to have unique headings so that it's clearer how I'm progressing through the application.

### Acceptance criteria
- Headings on each page of the application are unique

This  will implement the updated designs from [this ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/84650)

[Figma link](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/CHAMPVA-Application-(10-10d)-User-Testing-Prep?node-id=2133-65866&t=SPiGcNE5G7bNQqut-4)

### Research recommendation for reference
[Recommendation 10](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d9593da7070de683ad620091d43c2c8f3a1cf117/products/health-care/champva/1010D/research/users/Usability-Accessibility%20Test%20(April)/preliminary-form-improvements.md)

Some participants seemed to be confused when two pages had the same heading, one after the other. This happened most frequently with “Relationship to Sponsor”: when the first answer was “child,” another page with the same heading appeared asking the participant to clarify that relationship (e.g., biological child, stepchild).
Recommendation: Ensure each page has a unique heading.

**Comment by baltes** [comment]
@michaelclement When you get a moment, is there any other detail you'd want to include here for the heading updates on 10-10d?

**Comment by michaelclement** [comment]
@baltes I think that about covers it, thanks!

**Comment by michaelclement** [comment]
[Work done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30402)

**Comment by michaelclement** [comment]
Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes this has been merged and should be visible on staging shortly - ready for review.

**Comment by jamiefiore** [comment]
@michaelclement it looks like the header wasn't updated yet: https://staging.va.gov/health-care/champva/apply-form-10-10d/applicant-child-relationship/0
Here's the link to the page on the [figma file](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/CHAMPVA-Application-(10-10d)-User-Testing-Prep?node-id=2097-7753&t=pXTvyqQV7KxmVhuY-0) It should say: [Applicant] dependent status
The rest looks good. 
@baltes

**Comment by michaelclement** [comment]
@jamiefiore @baltes 
Header updated in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30468) (see screenshots on GitHub)
Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by baltes** [comment]
Reopening--I missed those last comments.

**Comment by michaelclement** [comment]
@baltes PR has been merged, should be viewable on staging shortly. Thanks!
