### ISSUE TITLE
Design Intent - IA Feedback - Debt Resolution - Payment History (VBA) MVP

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#86013]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thank you for doing this important work and bringing it through the Collab Cycle!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must: use headers to guide users through content**, specifically on Debt Details pages. Headings will help users more quickly identify what they're looking at and could also help the product team when discerning the best flow of information for the page. 

- [x] **Should: place key content in primary content section and avoid sidebar layout.** This will be complex! Drawing from design of credit card websites/mobile apps might be helpful here. Thinking about the inverted pyramid of information, what's most important to least important information? My guess below - I think the hierarchy will become clearer after user testing. 
  - What you owe
  - Yep, we got your last payment - thanks!
  - When the next payment's due
  - How to pay
    - How to get help if you need it
  - How to appeal
  - Details about this debt including past payments and debt letters

- [x] **Consider: reorder/regroup big numbers section on Debt Detail page** This section is visually appealing **and** the organization of information is a bit confusing. It goes back and forth between information about what is owed now, the original debt, what's already been paid, and what charges are accumulating. I think there is a more hierarchical way to reorder and visually group this information for fast understanding.
![Screenshot 2024-06-14 at 3 36 58 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/65a66d8b-a00e-4a0c-8046-e084f188cec1)

- [x] **Consider: test "overpayment" language** I understand this debt vs. overpayment language is very sensitive! I wonder if "overpayment" (by the VA) as a concept will be confusing when juxtaposed so closely with "payments" (by the Veteran). It's two separate models - what the VA has paid, vs. what the Veteran is paying. I admittedly am not familiar with all the research/conversation on this - just wanted to note that from an IA perspective, it's a potential label mismatch (The header on the page says overpayments, while the body content is about payments).

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by josephrlee** [comment]
All must and should changes have been addressed with One Thing Per page approach, [view updates files here](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2080-18754&t=kbCaI5mtWPYuQlJX-11). 

We are continuing to ideate and discuss the **Consider** changes.

cc: @mgleo @denisecoveyduc @HeatherRienks @charlottecesana @Tom-Davis

**Comment by josephrlee** [comment]
We plan to ask a question related to the language of overpayments/debt. Closing for now! 

cc: @mgleo @charlottecesana @HeatherRienks @Tom-Davis @denisecoveyduc
