### ISSUE TITLE
Grafana dashboard should be viewable without authentication

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#8602]
"As a Boris, when I am on a call discussing an outage, I want to point other VA people who might not have Github accounts to the VA monitoring dashboards."

Looks like Grafana supports anonymous access - the anonymous user gets "Viewer" role, and then you can simultaneously support OAuth login and logged in users can have a different role that allows read/write. And individual dashboards, if need to be hidden from anonymous access altogether, can have the "Viewer" role removed from them. 

Since Grafana is only available through socks proxy and VA network this seems reasonably safe. Might need some cleanup of existing role assignments.

**Comment by patrickvinograd** [comment]
cc @boris-ning-usds and @ricetj for triage/tagging.

**Comment by patrickvinograd** [comment]
The grafana demo sandbox allows anonymous access but then has a button to log in (the left-pointing arrow in the left nav): https://play.grafana.org/dashboards

**Comment by ricetj** [comment]
#7830 Planning on addressing this in that ticket.
