### ISSUE TITLE
Modal mentions actions after all rep info has been reported

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86026]
## Expected vs. Actual

After address/phone/email have all been reported (depending on what's available), the "You can add to your report" section should not be there, and the only action should be to "Close" the modal.

**Expected**: 
<img width="1969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63d3595214075fdb8668c23054101f4f8b915ecb/image.png" alt="image.png" />

**Actual**: 
<img width="1376" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--163957f2bb0d10e3c605df283166a342df728ca3/image.png" alt="image.png" />

## Steps to Reproduce

1. Perform a search in Find a Rep (I used Staging)
2. Report all information as outdated
3. Re-open the report modal

While we removed the "other" input, it seems the feature is still referencing that input after all other information has been reported.

**Comment by cosu419** [comment]
Keeping this one open - still needs "Close" button.

**Comment by oddball-lindsay** [comment]
Looks good @cosu419 !

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95db57ad19592805f76df38059f4a64e824172a3/image.png" alt="image.png" />
