### ISSUE TITLE
Analytics New KPI dashboard request for IVC Forms (FMP Registration)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86028]
# Request a New Standardized KPI Dashboard or an Update to an Existing Dashboard
## What this form is for

Use this ticket template to request a new standardized KPI dashboard or an update to an existing KPI dashboard on Domo for your product. 

**Tell us what you need done:**
- [x] [New Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-new-dashboards)
- [ ] [Updates to Existing Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-updates-to-existing-dashboards)

Standardized dashboards are currently available for [Forms](https://va-gov.domo.com/page/447193050?userId=853813555), [Content](https://va-gov.domo.com/page/426422632), & [Search](https://va-gov.domo.com/page/1964748112) products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## For New Dashboards

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here:(https://docs.google.com/spreadsheets/d/11m6TXQA5tqOsmqqyz2YGQ3R0KJ4YAkR5818MjthjRXg/edit?gid=0#gid=0)
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] **Add your team label to follow progress**

## For Updates to Existing Dashboards 

First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

**If you cannot locate your original worksheet you can create a new one:**
- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

**Additional Info For Both Options**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by johnny-jesensky-adhoc** [comment]
Hi @marywang2 -- thank you for submitting this, confirming we have it. Our team is prioritizing our migration to Google Analytics 4 (GA4), for the remainder of the month, but will look to pull into a sprint after the migration work is completed.

FYI @ChristineYoungZA, @Blivaditis

**Comment by marywang2** [comment]
Hi @johnny-jesensky-adhoc just checking on this one as well, thank you!

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA, as discussed over Slack, assigning this to you.

**Comment by ChristineYoungZA** [comment]
Hi @dorseypa1 I've updated the spreadsheet for the funnel update. Here is the link: https://docs.google.com/spreadsheets/d/1l0gQrLADqtuGiLVtFj8RlgHQNYS0oa3i6CHR6yzSQDc/edit?gid=1184161360#gid=1184161360

**Comment by dorseypa1** [comment]
Hi Christine,

For form '10-7959f-1 - Foreign Medical Program (FMP) Registration' the
version says V2 but we don't have that form in any of our forms tables.
Can you confirm that it should be V2 rather than V1?

Thanks

**Comment by dorseypa1** [comment]
Also, the Active_start_date is missing on the Forms_definition tab.  Can
you ask the customer to supply those values for both forms?

Thanks

**Comment by ChristineYoungZA** [comment]
Hi @dorseypa1, I've updated the spreadsheet with the active start dates and the form is supposed to be v1, it has been updated in the form.

**Comment by Blivaditis** [comment]
@marywang2 can you confirm if your form is still in staging? If so you will not see the from in the dashboard until it is live (not in staging). The funnel has been loaded and the form will appear in the dataset once the form is live.

**Comment by marywang2** [comment]
@Blivaditis yes confirming this is on staging only. We are going to staging review this week. And this is great, thank you!

**Comment by Blivaditis** [comment]
@marywang2 awesome, once the form is live I can verify that it is appearing in our dashboard! I will go ahead and close the ticket as all tasks are complete.
