### ISSUE TITLE
Figure out how to import work that is in GH projects into our established instance of ZenHub

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#86032]
The initial setup of [ZenHub for our Form Engine team](https://github.com/department-of-veterans-affairs/va.gov-team#workspaces/form-engine-666350119f54e1001cdd5680/board) has already been established.  This ticket is for determining how to import our current work stored in GH projects (under the general va.gov-team repo) into our ZenHub instance.  

Questions to be answered / Confirmed: 
1. I believe we need to create a new repository under the VA.gov-team repo,"Form Engine" and that should allow everyone to work in 
     ZenHub

2. The team will probably need to request access for ZenHub from [this page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) 

3. install the chrome extension for GH if this has not already been done

3. We should probably make a copy of our project work but I do believe we can move that under our repo somehow.

**Comment by humancompanion-usds** [comment]
I would not worry about this. We're currently evaluating moving off of Zenhub to GH Projects. If you are comfortable working in GH Projects then just stay put. I believe Zenhub is not long for this world at VA.
