### ISSUE TITLE
BGS::SubmitForm674Job and BGS::SubmitForm686Job parsing errors

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#86043]
If you look at [this query](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%28%28%40message_content%3ABGS%5C%3A%5C%3ASubmitForm686cJob%2A%20OR%20%40message_content%3ABGS%5C%3A%5C%3ASubmitForm674Job%2A%29%29%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718028344681&to_ts=1718633144681&live=true), you can see that our BGS::SubmitForm686cJob sidekiq_retries_exhausted "failed, retries exhausted!"  errors generally all have the warning
```
expect the argument to be a String, got NoMethodError (#<NoMethodError: undefined method `warning' for #<SemanticLogger::Logger:[...] @filter=nil, @name="Rails", @level_index=nil, @level=nil>>) 
```
If you do a search by ICN it appears that the error message that is happening during the loop is different than this:
```
GUIE50022&FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!!  FILE: FABTInterfaceCreator.cpp  LINE: 354This update is being elevated for additional review due to an Incident Flas:ORA-0000: normal, successful completion: - An unexpected error was encountered.  Please contact the System Administrator.
```
The two lines of code before the error is thrown are:
```
      user_uuid, icn, saved_claim_id, encrypted_vet_info, encrypted_user_struct_hash = msg['args']
      vet_info = JSON.parse(KmsEncrypted::Box.new.decrypt(encrypted_vet_info))
```
I'm wondering if this is indicative of a parsing error in this code since the error doesn't correspond to the error being thrown in sidekiq?  

The most important thing is to verify that the code is making it into the send_back_submission call that happens after this log message, and it appears that it does - I checked the user_uuid for a couple of these error cases in InProgressForm and it looks like the user_uuid in question has been removed, and there are "CentralMail::SubmitCentralForm686cJob" (/674Job) log messages for the user_uuids in question.  

Query to verify the backup is working:
```
service:vets-api env:eks-prod (@message_content:"CentralMail::SubmitCentralForm686cJob running!") @payload.user_uuid:[user_uuid] 
```
...with a user_uuid from the "BGS::SubmitForm686cJob failed, retries exhausted!" error log statement.

**Comment by evansmith** [comment]
@tblackwe I think if we substitute the inclusion of `error` here:
 ```
 Rails.logger.error('BGS::SubmitForm686cJob failed, retries exhausted!',
                         { user_uuid:, saved_claim_id:, icn:, error: })
```
and instead pass in msg['error_message'] this should work? I'll begin experimenting. 

Reference: https://github.com/sidekiq/sidekiq/wiki/Error-Handling

**Comment by mjknight50** [comment]
Now we can see this error:
https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%28%28%40message_content%3ABGS%5C%3A%5C%3ASubmitForm686cJob%2A%20OR%20%40message_content%3ABGS%5C%3A%5C%3ASubmitForm674Job%2A%29%29%20status%3Aerror%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718028344681&to_ts=1718633144681&live=true

**Comment by mjknight50** [comment]
@evansmith This PR is merged.  Can we close this?

**Comment by evansmith** [comment]
@mjknight50 good to close!
