### ISSUE TITLE
10-7959f-1 - update unit tests (for recent changes)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86052]
Update unit tests to accommodate recent changes for 10-7959f-1:
- addition of same as mailing address screen
- additional street address lines
- extending phone number max number limit

**Comment by reiting** [comment]
<img width="549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3dBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b63fdd89c2a45dee9918778bca4f4f2e398f149/Screenshot%202024-07-19%20at%209.55.14%E2%80%AFAM.png" alt="Screenshot 2024-07-19 at 9.55.14 AM.png" />
This is in team review right now.

**Comment by reiting** [comment]
@marywang2 <img width="1907" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--816609512cdbd260c7f301f7893f957be7d3825e/Screenshot%202024-07-29%20at%2010.58.45%E2%80%AFAM.png" alt="Screenshot 2024-07-29 at 10.58.45 AM.png" />

**Comment by reiting** [comment]
@marywang2 not sure what the first screenshot is. I assume a random mistake. But above is the code coverage for f1, so I think it's ready for review, because I'm not sure how else we can review this.
