### ISSUE TITLE
10-7959f-1: remove phone number validation

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86083]
As a user, I want to be able to enter my international or domestic phone number in the field so that I can get contacted if there are any issues with my registration.

url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/contact-info
https://design.va.gov/components/telephone
- user should not be limited to 10 digits upon entry
- otherwise functionality/display remains the same
- basic validation for numbers
- verify longest country code (with phone number) and set to max limit

Acceptance criteria:
Given the user is filling out the FMP registration form online,
When they go to enter in their phone number on the contact information page
Then they should be able to enter either an international or domestic phone number without being restricted by the number of digits

**Comment by reiting** [comment]
<img width="657" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEorQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d4052701e2db0cddf593664dc873f35c458fe04/Screenshot%202024-06-20%20at%201.51.26%E2%80%AFPM.png" alt="Screenshot 2024-06-20 at 1.51.26 PM.png" />
<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE4rQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afc70356c9441a2b12ac33a9edc1cd1cc79485aa/Screenshot%202024-06-20%20at%201.51.37%E2%80%AFPM.png" alt="Screenshot 2024-06-20 at 1.51.37 PM.png" />

**Comment by reiting** [comment]
This is currently in team review.

**Comment by reiting** [comment]
This has been merged and will be in staging in a few hours.

**Comment by reiting** [comment]
@marywang2 I think this should be in staging now.

**Comment by marywang2** [comment]
@reiting I'm not seeing the change on staging yet. @brian-wilke fyi for review.

**Comment by reiting** [comment]
@marywang2 somehow form.js didn't get updated in this PR. I've fixed it and put in a PR. Waiting on team review now.

**Comment by reiting** [comment]
It's now in platform review.

**Comment by reiting** [comment]
@marywang2 @baltes @brian-wilke this should be in staging and good to go.

**Comment by brian-wilke** [comment]
I will recheck. Earlier today, I still had the verification issue. Thanks
Rachel!

**Comment by baltes** [comment]
Morning @reiting , just checked and this is what I'm seeing on staging (Afghanistan country code and then a bunch of digits). It's over 10, but is there still a length limit?

<img width="1076" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61c142fc205fd670d1b3c814f3b243dab24576fe/image.png" alt="image.png" />

**Comment by brian-wilke** [comment]
[image: image.png]

This is the phone number for the British Embassy in Uruguay.


Additionally, I am not able to sign in, but I think that is a VA.gov thing.
This was done in the UNAUTH Flow.

**Comment by brian-wilke** [comment]
Works without spaces??? (this is the US embassy... I removed the spaces. It
did not work with spaces.)

[image: image.png]

**Comment by reiting** [comment]
@baltes @brian-wilke we restricted them to 15 digits because research showed that was as long as any phone number should be. Happy to completely remove that restriction or change the number! Brian, I can't see your image for some reason! But I do think the sign in is a va.gov issue. This PR didn't touch sign in, and you know it's flaky like that sometimes.

**Comment by reiting** [comment]
This is currently in platform review. Once it's approved, it should be easy to enter additional characters.

**Comment by reiting** [comment]
@brian-wilke @baltes @marywang2 This should be good to go in staging now.

**Comment by marywang2** [comment]
@reiting let me know when this is re-enabled on staging so I can view it :) thank you!

**Comment by reiting** [comment]
@marywang2 Just merged the PR that adds the spaces,. Should be able to view on staging in a few hours.
