### ISSUE TITLE
[FULL TRANSFORM] Release Monitoring

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#86081]
Since we are launching the full transform version of the FSR, we need to set aside time for monitoring and fixes

**Comment by HeatherRienks** [comment]
Let's add in info here on the issues we are seeing

**Comment by digitaldrk** [comment]
Bug found for "questions".

This has been coded, reviewed, and merged:
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87408

**Comment by HeatherRienks** [comment]
This ticket will roll over; we need to be sure to document any bugs we find with the release.

**Comment by digitaldrk** [comment]
New bug found while testing locally:
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87575

**Comment by digitaldrk** [comment]
Marking this as blocked until we get FE fix out and tested

**Comment by digitaldrk** [comment]
Andrew fixed the FE bug that was sending the wrong payload. 

I will test myself some and then we can open the FF back up and we will unblock this

**Comment by Tom-Davis** [comment]
The release of this initiative has been moved to the end of August or early in September - as a result we are moving the release related tickets back to "ready" and will pull them into the sprint when the release is scheduled.

**Comment by maxx1128** [comment]
This is a pull request with additional tracking for specific parts of the backend transform: https://github.com/department-of-veterans-affairs/vets-api/pull/18358

**Comment by dhill802** [comment]
Release is pushed back until Derek is back. 
 Monday 09/30/24 - 5%
 Wednesday 10/02/24 - 25%
 Monday 10/07/24 - 50%
 Wednesday 10/09/24 - 100%

**Comment by Tom-Davis** [comment]
This will roll over one more sprint as the last % update is scheduled for Wednesday.

**Comment by Tom-Davis** [comment]
Closing as the release is complete.
