### ISSUE TITLE
10-7959c: Review page - update copy, hide file upload section

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86099]
As a user on VA.gov, I want to be able to review my information when filling out the OHI form so that I can verify everything before I submit.

Page elements:
- breadcrumb
- header and subhead
- progress indicator
- footer

Pages: 
- Review and sign (accordion with editable information)
  - section headers and subheads (in expanded view)
  - hide file upload section (per [spike](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/84194) ticket)

Figma [link](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/10-7959c-Form?node-id=1155-73969&t=Y8cWvTGeyw2lKO6X-0) ("Prep for staging review")

Acceptance criteria:
  - Given the user is on VA.gov and is filling out the OHI form
  - When the user gets to the review section
  - Then the user can view, edit or update their information before submitting

**Comment by michaelclement** [comment]
[Work is done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30409). The headers inside the accordions may still differ a bit, but that's because they'll be directly addressed when #85791. Additionally, the file upload section of the review accordion was hidden in this [previous PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30382).

**Comment by michaelclement** [comment]
Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by jamiefiore** [comment]
@michaelclement Thanks! Looks good to me @marywang2

**Comment by marywang2** [comment]
- remove "Beneficiary's" (next to name and date of birth)
- remove first name next to "Medicare status"
- Health Insurance section - remove "primary"
- remove "primary" (wherever it appears)
- rename "secondary" to "additional"

**Comment by michaelclement** [comment]
@jamiefiore @marywang2 
Header updated in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30468) (see screenshots on GitHub)
Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 PR has been merged, should be viewable on staging shortly. Thanks!
