### ISSUE TITLE
Flipper UI access for Eli Selkin

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#86094]
### Your Name

Eli Selkin

### Your GitHub handle (Flipper UI access is managed through GitHub)

@eselkin

### Team, Role, and Company of the target individual

Sitewide Facilities, FE Engineer, AgileSix

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

FE Engineer who will be shipping features behind flippers and needs the power to enable / disable.

**Comment by AnthonyWFlowers** [comment]
Greetings @jilladams  this user has been granted access to Flipper UI Lesser environments and Production.
