### ISSUE TITLE
Flipper UI access for Fran Cross

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#86093]
### Your Name

Fran Cross

### Your GitHub handle (Flipper UI access is managed through GitHub)

@FranECross

### Team, Role, and Company of the target individual

Sitewide Public Websites, Product Manager, AgileSix

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Fran is the PM for a team that launches new features that should be enabled behind flippers in production, including for Cerner cutovers, VA.gov homepage, global search, and find a form. 

Fran is not actually listed in Atlas yet, but she is listed in the VFS Team Roster, and I've filed a Plat support request to fix the fact that she's missing in Atlas: https://dsva.slack.com/archives/CBU0KDSB1/p1718650336431679

**Comment by AnthonyWFlowers** [comment]
Greetings @jilladams  this user has been granted access to Flipper UI Lesser environments and Production.
