### ISSUE TITLE
[FE] Add Provider to Stand-alone Travel Appointment Info

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#86104]
## Description
Team decided to add Provider info to the Appointment Info

## Wireframes
[Wireframes](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3181-3191)

## Tasks
- Add Provider Info per wireframes

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/86104?planning-poker) with Zenhub @brianseek @wullaski

**Comment by brianseek** [comment]
We don't need this ticket, the work is already done
