### ISSUE TITLE
OOB Deploy Request - Vets-website remove dependence on flipper so Cerner component will call undeprecated endpoint

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-team#86164]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > Vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/30384

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  If the OOB deploy does not happen, perhaps 40% of Veterans use Cerner, so that amount may be affected.

## Has fix been confirmed in Staging?
- [x] Yes (prior change was deployed behind flipper but flipper is not working with old react code)
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
   > The Lighthouse team is decommissioning the v0 endpoint that the Cerner authed users use today. We replace the call to our new endpoint which calls the Lighthouse V1 endpoint. We tried to do it behind a flipper but the flipper wasn't being respected by the code.
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [ ] PagerDuty OOB Deploy Incident Opened
 - [ ] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [ ] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by jilladams** [comment]
Re: Veteran impact, we need to stop using Lighthouse V0 facilities endpoint, which is schedule for deprecation as of Friday. Per #s provided by Lighthouse here: https://dsva.slack.com/archives/CJ162GDDJ/p1718634787905759, we believe there were 22K calls to V0 in the last 7 days, and we believe that traffic is all due to the usage of V0 that we are looking to OOB deploy and move to V1 instead. 

I am saying that badly. In short: 22k every 7 days, ish, could begin failing if we aren't able to get off of V0 before deprecation.

**Comment by jilladams** [comment]
Was deployed, closing. https://dsva.slack.com/archives/CBU0KDSB1/p1718661724355239?thread_ts=1718657757.832269&cid=CBU0KDSB1
