### ISSUE TITLE
10-7959f-1: confirmation page copy updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86167]
As an FMP applicant, I want to see confirmation for my form submission after I click submit so that I know it went through.

[Figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=726-21596&t=GlSwmnIWjXyFQdFH-0) - WIP version has the latest copy
- update header copy
- update body copy 
  - include link to the FMP file claim [page](https://www.va.gov/resources/how-to-file-a-va-foreign-medical-program-claim/)
  - include link to [AVA](https://ask.va.gov/)
  - include phone number (formatting and style per design [library](https://design.va.gov/patterns/ask-users-for/phone-numbers))
  - remove 'need help?' footer **only** on this page

Acceptance criteria
- Given the user clicks 'submit' on the review page and submits their 10-7959f-1 form,
- When the confirmation page displays,
- Then the messaging on the page lets the user know their application was submitted successfully, along with info on how to follow up/who to contact.

More info
When a user clicks submit after completing 10-7959f-1, the site will generate their PDF and metadata and send one or more files to an s3 bucket where it can be picked up by PEGA processes.

At the time of submit, we won't know anything about PEGA's processing status, so this messaging is meant to let the user know that we got their application and when they should expect to hear something new. This is distinct from what we'll send them in an email confirmation, which will happen after we know that their application has been imported successfully into PEGA.

**Comment by marywang2** [comment]
@reiting thanks - the screenshot shows the info repeating twice, under the first link.

**Comment by reiting** [comment]
@marywang2 yes, they are 2 different screenshots. The info isn't repeating, just making 2 screenshots so that you can see the entire page.

**Comment by marywang2** [comment]
Ah, thank you @reiting

**Comment by reiting** [comment]
@marywang2 this was just merged. It will be in staging in a few hours.

**Comment by marywang2** [comment]
@reiting some changes: 
- update the text in the green box
- update the copy above the user's name

<img width="418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--309e48ba33cf1a4d6e7c2417761d6798719d8db6/Screenshot%202024-07-26%20at%207.42.00%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 7.42.00 PM.png" />

**Comment by reiting** [comment]
<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9a3dd40a151641653a48a550d3a58a34c8f8584/Screenshot%202024-07-29%20at%2011.28.45%E2%80%AFAM.png" alt="Screenshot 2024-07-29 at 11.28.45 AM.png" />
This is in team review

**Comment by reiting** [comment]
This was merged, but will probably be another hour or 2 before it hits staging.

**Comment by reiting** [comment]
@marywang2 this should be in staging and ready for review.
