### ISSUE TITLE
10-7959c: OHI confirmation page copy update

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86169]
As a CHAMPVA OHI user, I need to know the status of my form when I click submit and what to expect next.

- success message only
- error state will be out of the box (appears on the review page)
- leave out any mention of email notification
- remove 'need help?' footer since that info is different from the one we're providing

Acceptance criteria

- When my submit gets a 200 response from s3
  - The messaging on the page lets me know my application submitted successfully
  - I get information about how to contact the CHAMPVA call center if I want to follow up (use the same info from 10-10d)
  - I get information on general timing for processing

More info
When a user clicks submit after completing 10-7959c, the site will generate their PDF and metadata and send one or more files to an s3 bucket where it can be picked up by PEGA processes.

At the time of submit, we won't know anything about PEGA's processing status, so this messaging is meant to let the user know that we got their application and when they should expect to hear something new. This is distinct from what we'll send them in an email confirmation, which will happen after we know that their application has been imported successfully into PEGA.

**Comment by jamiefiore** [comment]
@marywang2 here's the [confirmation pages in Figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=2018-40521&t=p17cnSbL8kKTvXZ8-4) 
This include all docs uploaded and mail-in docs.

**Comment by marywang2** [comment]
Thanks @jamiefiore, would you be able to request CAIA review of this page? I want to make sure they see it.
