### ISSUE TITLE
"go back" links use "eauth" authenticated link

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86177]
### User story

As a Veteran, I want "go back to previous version" links to land me directly in a signed-in state of MHV Classic, so that there's not a page refresh after a few seconds.

### Notes
- Kaitlin noticed refresh behavior in launch party
- Carlos confirmed that using a link that starts with `eauth.` would do the right thing directly

Possible tasks:
- 

## Acceptance criteria

- Click on "go back to previous version" anywhere in MHV-on-VAgov portal links to `eauth` URL, such that there is no automatic refresh – Fix Cartographer-owned links, notify other teams if not
  - 3 on MHV Home
  - 1 on MR temp landing page
  - 1 on SM
  - 1 on Meds
- QA review

**Comment by radavis** [comment]
[Secure Messaging](https://github.com/department-of-veterans-affairs/vets-website/blob/a78233c/src/applications/mhv-secure-messaging/components/Dashboard/WelcomeMessage.jsx#L48:L48) and [Medications](https://github.com/department-of-veterans-affairs/vets-website/blob/9cec981/src/applications/mhv-medications/containers/LandingPage.jsx#L265:L265) are currently using the `mhvUrl()` helper, which will resolve to the correct URL for ssoe users.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that clicking on the "go back to" links keeps the user in a signed in state of MHV Classic as expected
