### ISSUE TITLE
Datadog tracks "go back to previous" link clicks on MHV Home

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86178]
### User story

As a Cartography team member, I want DD to track the three "go back" link click actions on MHV Home separately, as well as the one on the temporary MR landing page, so that we can understand what area/content a Veteran was engaged with when they went back to MHV Classic.

### Notes
- extending #85778 
- Wes opened a support thread with DD on Fri, 6/14; @dcloud was CCed on those
  - UPDATE: actions are working as expected in Prod post-launch
- Current state of actions
  - Daniel added a custom action to the go-back link in the MR box
  - See "MHV-on-VA.gov Integration RUM" [dashboard](https://vagov.ddog-gov.com/dashboard/hzz-d8e-79j/mhv-on-vagov-integration-rum?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1718140251209&to_ts=1718745051209&live=true) for a few funnels that capture the current state of these actions.
  - Note that the action names tracked in the dash are confusing, as they sometimes include more than just the text link – e.g., `click on If you’re not ready to try the new My HealtheVet, you can use the previous version anytime. Go back...` seems to include the whole second paragraph on MHV Home.

Possible tasks:
- 

## Acceptance criteria

- DD Actions are visible (in Prod and Staging) in DD for clicks on "go back" links on MHV Home and on the temp MR landing page
- We can tell in DD which link a given user clicked

**Comment by dcloud** [comment]
I have a meeting on 6/18 to discuss "missing clicks" with a Datadog technical support engineer

**Comment by dcloud** [comment]
As part of the support investigation with Datadog, it was suggested that we upgrade from v4 to v5, and I've been peeking at that. Currently Datadog is implemented platform/sitewide, so upgrading would either require:

- Upgrade for all teams, partner with platform to do so given this would affect all apps using DDG
- Yarn workspace-ification: I believe we could have our own package.json for the mhv-landing-page. Would need to evaluate feasibility and impacts, but it might be possible to upgrade DDG RUM only for our application.

## Some notes on upgrading

- [Upgrade RUM from v4 to v5](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#from-v4-to-v5)

### names of deprecated things

I put these lines in a file to grep for with rg (ripgrep)

```
removeUser
addRumGlobalContext
removeRumGlobalContext
getRumGlobalContext
setRumGlobalContext
addLoggerGlobalContext
removeLoggerGlobalContext
getLoggerGlobalContext
setLoggerGlobalContext
addContext
removeContext
proxyUrl
sampleRate
allowedTracingOrigins
tracingSampleRate
trackInteractions
premiumSampleRate
replaySampleRate
beforeSend
```

#### trackInteractions --> trackUserInteractions

Looks like many apps use the v5 name, usually alongside the v4 name…

```bash
delta -s --color-only <(rg trackUserInteractions -l vets-website | sort) <(rg trackInteractions $(rg -l trackUserInteractions vets-website) -l | sort)
```

### Intake domains

`https://browser-intake-ddog-gov.com` is in devops, so I think we're good here

**Comment by dcloud** [comment]
Saving the DDG session search that shows the Prod events for the medical records card: `@action.type:click "Medical Records Card"`:

<img width="1048" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/279327/32fc0097-8313-405a-bc92-d3202b63694a">

**Comment by dcloud** [comment]
Also: `@action.type:click @action.name:*Medical\ Records\ Card*`, where the backslash escapes spaces and so we can perform a wildcard search on the action name. As opposed to the version in my previous comment which searches multiple fields, not just the action name

**Comment by dcloud** [comment]
Per support, going to switch from the attribute to a function call:

> Next, from the screen recording, I see the data-dd-action-name attribute on the <a> tag, but maybe we can try using the datadogRum.addAction() function here to add the custom click action. 
https://docs.datadoghq.com/real_user_monitoring/guide/send-rum-custom-actions/?tab=npm#instrument-your-code

**Comment by dcloud** [comment]
I forgot to move this into code review, but this got reviewed and is merged. Should be in staging shortly

**Comment by dcloud** [comment]
Seeing _custom_ actions in DDG for staging, e.g. [this event for "Click on Landing Page: Intro - Go back to the previous version of My HealtheVet"](https://vagov.ddog-gov.com/rum/sessions?query=%40type%3Aaction%20%40application.id%3A1f81f762-c3fc-48c1-89d5-09d9236e340d%20env%3Astaging&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZBf1E9_tlQujQAAAAAAAAAYAAAAAEFaQmYxRS1uQUFDRjd1YzhPYkNSWWdBQgAAACQAAAAAMDE5MDVmZDQtNzRjZi00MWM4LTlhMDMtYTk4YTFjYzM3NTZk&fromUser=false&viz=stream&from_ts=1719591336266&to_ts=1719594936266&live=true)

**Comment by dcloud** [comment]
Not seeing actions recorded for the [MR Transitional page aka "Click on Medical Records: Coming Soon…" link](https://github.com/department-of-veterans-affairs/vets-website/blob/13bdfb115b0f0ca2aa58ef3803c264fb5d894a8e/src/applications/mhv-landing-page/components/MedicalRecords.jsx#L109) so far

**Comment by dcloud** [comment]
After merging the RUM config move to app-entry file, seeing the coming soon click action

```
@action.name:*Medical\ Records*
```

**Comment by dcloud** [comment]
It also looks like that config change may have fixed the bug with getting `DD_RUM` to output info in the console. I can run `DD_RUM.getInitConfiguration()` to see the config or `DD_RUM.getInternalContext()?.session_id ` to get the session id

**Comment by dcloud** [comment]
While https://github.com/department-of-veterans-affairs/vets-website/pull/30605 appears to have made some of the console functions work, making it possible/easy to grab a session_id via `DD_RUM.getInternalContext()?.session_id`, there are remaining issues:

- signficant lag between actions taken in a session and events appearing in DDG. Need to reload datadog to see events appear
- The issues with labelling click actions on the "Learn More" content accordian
  - Opening the accordion appears to record sibling content: "Welcome to the new home for My HealtheVet. Now you can manage your health care needs in the same pla [...]" - `@action.id:f1861868-b2dc-4ca5-b04a-20d87083d6d6`
  - Closing grabs the content inside the accordion, per `@action.id:1c375a4c-c7ef-4015-a282-198f9b1e43fb`
- Possible double-counted click actions, e.g. `@action.id:e9163295-a195-49c3-a20f-59f18f8bba8c` -> `@action.id:1976d1e0-8fdc-4811-9447-61540ddf68c3`… I wouldn't expect to see the non-custom click being recorded any more on links that have the `datadogRum.addAction` call

Per my clicking around in staging - `@session.id:2c298dca-f11a-4a8d-a42b-f53e4e1eb0d1`

These observations should probably be put into a "Datadog debug" ticket if we need to continue to fix things with DD_RUM
