### ISSUE TITLE
10-7959f-1: update confirmation email copy

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86171]
As an FMP user, I need to receive a confirmation email so that I know my application is being processed and I know what to expect next.

Acceptance criteria

- Applicants get assurance that their application is moving forward
- Applicants have a general understanding of when they should hear from VA
- Applicants know what to do if they don't hear from VA
- This email will be sent once PEGA has confirmed that an application has been successfully imported, so we can tell the applicant that they're application is being processed and let them know it will take approximately 60 days to process.

Current email template (need to confirm what email address this will get sent to):
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4debd4ddc20fef5102130adfc8d97dfd476b91b3/image.png

Intake [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/81725) w/instructions on how to access VA notify in comments. When this is ready we should have them review and/or help w/guidance and prep.

**Comment by brian-wilke** [comment]
Placeholder for both a successful and unsuccessful email communication have been built in the figma file for the registration form. 

This ticket is closing for this sprint (20). Next sprint (21) will likely contain updates on how to complete this feature for the dev team hand-off.

@baltes @marywang2
