### ISSUE TITLE
[CAIA A11y Research]: Appointments/Check-in, Community Care Self-Scheduling (July 2024)

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#86183]
> [!NOTE]
> **High-Level Overview**: Unified Appointments Experience (Appointments and Check-in)
> - **Research Timeframe**: Mid-July (18-22)
> - **Pilot**:  #86740 `6/25/2024`
> - **Assistive Tech Users**: 6 AT Users (8 to be recruited) [Canvas Source of Truth for Scheduling](https://dsva.slack.com/docs/T03FECE8V/F078M3C58N8)
> - **Testing Environment:** [CodePen Prototype](https://codepen.io/team/va-cie/live/WNBQNxb)
> - **Assistive Tech Being Used**: Mobile (ALL participants); Screen Readers (6); Screen Magnification (2)
> - **Task Lists**: See task lists for next steps/definition of done
> - **Team Contacts**: Christina will be OOO: 6/26-7/5/2024, Ben and Ciera will be providing Christina's coverage.

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- Sara
- SK
- Jamie
- Evan

</details>

## About the Team

> [!IMPORTANT]
> Since Christina will be OOO: 6/26-7/5/2024, Ben and Ciera will be providing Christina's coverage.Please contact them, during that timespan. 

<details><summary>Toggle to view information about the team.</summary>

- Team name: Unified Appointments Experience (Appointments and Check-in)
- OCTO-DE product owner: Kay Lawyer and Kristen McConnell
- Product manager: Jeff Roof, **Ben Brasso**
- Designer: **Ciera Maddox**, Christina Gednalske, Ben Brasso
- FE engineer: Simi Adebowale, Lee Delarm
- Product/team Slack channel: #appointments-cc-direct-scheduling (https://dsva.slack.com/archives/C06SQ48B205)

</details>

## About the Research

<details><summary>Toggle to view more intake research ticket information</summary>

### Purpose
> The purpose of this research is to get feedback from Veterans on the CC appointment scheduling process and develop a better understanding of Veterans’ expectations around referrals. We also hope to evaluate reactions to initial concepts for referral locations.

### Insights
> **This study will give us insight into:**
> - if Veterans find it easy to schedule their community care appointments using the proposed scheduling process
> - where Veterans expect to find their new and past referrals, and what information they expect referrals to contain
> - if our initial concepts for referral locations fit Veterans’ needs and expectations within the Appointments experience

### Criteria for AT
> **Primary criteria**
> - All participants must be able to attend sessions on a mobile device
> - All participants must have used Appointments on va.gov before to manage their appointments
> - All participants must use assistive technology
> - 6 screen reader users
> - 2 screen magnification users
> - All participants must be willing to use assistive technology during the session

### Background

> The Cleland Dole Act addresses Veteran homelessness, access to care, community care, mental health, research, telehealth, prostate cancer, provider oversight and transparency, long-term care, rural health, benefits, information technology and more.

#### Self-Scheduling and Community Care Self-scheduling Pilot Program

> As a congressional mandate under the Cleland-Dole Act, VA must address the following for Veterans by the end of 2024: Self-scheduling appointments

> Allows Veterans seeking for primary care, specialty care, and mental health care under the Veteran’s Community Care Program to self-schedule, modify, and cancel appointments directly online

> Allows VA to expand capabilities of an existing appointment self-scheduling technology or purchase a new appointment self-scheduling technology

> The pilot program MVP will allow Veterans at pilot sites in the Greater Los Angeles area to self-schedule physical therapy appointments using Appointments on va.gov once a referral is approved. They will also have the ability to cancel and reschedule those appointments.

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### Calendar checking

- [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [X] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

<details><summary>Toggle to view research timing information.</summary>

### Timeframe

- **Pilot Session**: #86740- may be async review of CodePenPrototype 6/25/2024
- **Timeframe**: 7/18/2024 - 7/22/2024

#### Availability for sessions:
- July 18: 9am - 10am, 11am - 7pm ET
- July 19: 9am - 7pm ET
- July 22: 9am - 7pm ET

### Length of sessions

- **Session length:** 1 hour and 15 minutes
- **Buffer time between sessions:** 30 minutes
- **Maximum sessions per day:** 5

</details>

###  Testing Schedule

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

Please toggle and use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

> [!IMPORTANT] 
> All sessions will be mobile, based on the research plan. 

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available
------------------|------------------|--------------|--------------|--------------|--------------|--------------
Pilot `CODEPEN` `#86740` | 6/25/24 | TalkBack | Mobile, Android | Chrome | Advanced  | @SarahKay8 
P13 | 7/18/24, 1-2:15 p.m. ET | JAWS | Desktop, Windows | Chrome | Intermediate | @coforma-jamie
P14 | 7/18/24, 4-5:15 p.m. ET | Screen magnification | Mobile | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P15 | 7/18/24, 6-7:15 p.m. ET | VoiceOver | Mobile | Safari, Chrome, etc. `TBD` | Intermediate | @EvanAtCoforma 
P16 `Rescheduled - former no show` | ~7/19/24, 9 - 10:15 a.m.~ 7/22/2024 11:30 a.m. - 12:45 p.m. ET | Screen reader and screen magnification / VoiceOver | Mobile | Safari | Beginner | @coforma-jamie 
P17 | 7/22/24, 9:30-10:45 a.m. | Screen reader and screen magnification / VoiceOver | Mobile | Safari, Chrome, etc. `TBD` |  Intermediate | @sara-amanda @rileyorr 
P18 `CANCELED` | 7/22/2024, 3:30-4:45 p.m. ET | Screen reader/VoiceOver | **Mobile**; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P19 | 7/22/2024, 5:30-6:45 p.m. ET | Screen magnification | **Mobile**; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @sara-amanda 

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

### Observer Sign-Up - Slack Canvas
[The team is utilizing a Slack Canvas for sign-ups.](https://dsva.slack.com/docs/T03FECE8V/F078M3C58N8)

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling)
- [User flows](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1174-25185&t=3GuqUBzkJcpsRczV-1)
- [Service Blueprint](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/discovery/service-blueprints/cc-digital-self-scheduling-service-blueprint-2024-05-12.md)
- [Service Blueprint 2](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717007634301/2e9fa61206c18e8cf196e2deb612eb0b577fb458?sender=ua2ec2e34eb6128f3375e0207)
- [MVP Designs](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1899-75962&t=3GuqUBzkJcpsRczV-1)
- [CodePen Prototype](https://codepen.io/team/va-cie/live/WNBQNxb)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/research/2024-06%20Community%20Care%20Self-Scheduling%20-%20Usability%20and%20Concept%20Testing/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/research/2024-06%20Community%20Care%20Self-Scheduling%20-%20Usability%20and%20Concept%20Testing/conversation-guide.md)

</details>

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket 6/24/2024
- [x] **PILOT SESSION: SCHEDULE** Pilot session with team. `TBD` may be async review of CodePen Prototype
- [x] **PILOT SESSION: CREATE TICKET** Link ticket in this task list.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86740
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available.
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean)
- [x] **RESEARCH NOTES** [CAIA notes document](https://docs.google.com/document/d/1ERw9InQv7WZyXMuDq91TaJx7YBC-PscmFBCIbHRuDUw/edit?usp=sharing)
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support. [Slack Canvas with Session Info](https://dsva.slack.com/docs/T03FECE8V/F078M3C58N8)
- [x] **Review research folder and assets**
- [x] **Participate in research**  **Date Span:**`7/18/2024` to `7/22/2024`
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
```

```[tasklist]
### VFS TEAM Tasks
- [x] Tag @coforma-terry in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH)
- [x] Your team's researchers and observers read through platform guidance on research with assistive technology users
- [x] Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired
- [x] Schedule a pilot session with CAIA a11ys (or async review of CodePen Prototype - per Slack Request)
- [x] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section
- [x] **DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. [Slack Canvas is being utilized for sign-ups](https://dsva.slack.com/docs/T03FECE8V/F078M3C58N8)
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in `Table` in the ticket above. `Noted all will be **mobile** based on research plan.`
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (Sara or Terry)
```

**Comment by sara-amanda** [comment]
## AT Sessions

- [x] Perigean has provided dates and times for five sessions to date, available in the [Observer Sign-Up Canvas](https://dsva.slack.com/docs/T03FECE8V/F078M3C58N8). 
    

> - **Thursday, July 18**
>     - 1 p.m. - 2:15 p.m. ET
>     - 4 p.m. - 5:15 p.m. ET
>     - 6 p.m. - 7:15 p.m. ET
> - **Friday, July 19**
>     - 9 a.m. - 10:15 a.m. ET
> - **Monday, July 22**
>      - 9:30 a.m. - 10:45 ET

- [ ] These dates have also been added to the table in this ticket. 
- [ ] These dates will be added to the CAIA A11Y Capacity Calendar. 
- [ ] These dates will be added to the Research Outlook Tracker.  


cc: @SarahKay8 @coforma-jamie @EvanAtCoforma

**Comment by sara-amanda** [comment]
## AT Sessions Update
- [x] Participant numbers added to CAIA A11Y Capacity Calendar on 7/15/2024
- [x] Internal CAIA notes doc added to A11Y invites and A11Y task list on 7/15/2024
- [x] PTO swap - Sara can grab the sesh earlier on 7/22 too (Canvas Updated) - last week
- [x] New session on 7/22 added to the calendar and tracking doc - Sara grabbing - on 7/15/2024
- [ ] **Pending additional information on participants (what we have is in the table in this ticket):** 
    - 🆕 Years Using AT: `Needed for all` - we just started asking for this
    - Skill level of user: 
    - Operating System: 
    - Assistive Technology being used: 
    - Internet Browser: 
    - Device Type: 

cc: @NaomiPMC @SarahKay8 @coforma-jamie @EvanAtCoforma

**Comment by sara-amanda** [comment]
## AT Sessions Update

- [x] Sessions updated from Canvas for 7/22/2024 and reflected in table and on CAIA Calendar (includes rescheduled session and additional session). - `COMPLETED`
- [x] 😄 Invited Maria and Riley to join and observe on Canvas via open slots (tagged and DM) - `OPTIONAL`
- [ ] Researcher tracker needs updated to reflect additional session (new P18; P19 is the old P18), rescheduled P16 session along with updated AT for this study. 

cc: @NaomiPMC @coforma-jamie @EvanAtCoforma

**Comment by sara-amanda** [comment]
# Assistive Technology Participant Takeaways

Thank you for including CAIA A11Ys in your User Research! We appreciate the opportunity to support your participants, and observe from an accessibility perspective. We hope you find the following aggregated observations helpful.

## Overview
57% (4 out of 7) participants completed the study with assistive technology, in addition to one pilot* that was conducted by CAIA, for a total of 5 tests with assistive technology.
- VoiceOver (3)
- JAWS (1)
- TalkBack (1)*

**Of those who tested (4):** The majority of the AT participants were on mobile devices (75%), and maintained a self-described intermediate (75%) or advanced (25%) skill level, primarily using iPhone devices (75%), with VoiceOver on Safari browsers. 

## Key Takeaways

### Prototype
- **P14 (VoiceOver):** The prototype is not showing critical information that the P needs to access to ensure everything is working properly.
- **P17 (VoiceOver):** 
    - **Appointment List:** When the participant has the “If you were approved for more than one appointment” additional details component open they are unable to tab to the content below.
    - **Choose time and date page:** The AT participant attempted to navigate to the “Continue” button to proceed with scheduling their appointment, but when they tabbed right from “Back” the focus seemed to go to hidden element that said “Optional for screen readers”, then they tabbed right again to the “Continue” button. They were very confused what the hidden element was for  “I don’t know why you have that in there. I hope you take that out.” 
    - **Review/confirm choices page:** The same button bug from the “Choose time and date” page is occurring on this page. 

### Text message
- **P13 (JAWS):** The language made him think that he needed to sign in before clicking on the link
### Breadcrumb
- **P13 (JAWS):**  Didn’t understand ‘breadcrumb’ - this is standard semantics, but lots of websites don’t use it correctly so he might not have heard it too often
### Appointment list: 
- **P13 (JAWS):**  
    - There’s no indication that “you can now schedule your appt” is connected to “expires in 310 days”
    - Thinks the appointments should be right after the schedule link. (Or put another way, the upcoming / pending / past menu is in the way.
    - Confusion between “Start scheduling” action link and “Schedule your appointment” link
- **P17 (VoiceOver):** Participant prefers “Preferred community care provider” vs “Preferred provider” label 
### Referral page: 
- **P13 (JAWS):** 
    - Lots of language confusion here. “Expiration date” (what is expiring?), “number of visits” (visits you’ve had, or visits you can schedule?), “referral number” (didn’t know what it was)
    - “Details you’ve shared” was unclear. Thought it meant appointment details, not referral preferences.
### Provider page: 
- **P14 (VoiceOver):** Likes that next available appt date is shown. Wouldn't know how to find a specific doctor or a specific treatment. Would like to have the doctor’s name be a link as well showing the information of the doctor.
- **P17 (VoiceOver):** Would have liked to see full availability.  July 6, 2024 (4 available appointments) - preferred - click here for times available, on that date. 
### Choose Date and Time: 
- **P17 (VoiceOver):** The participant expected the focus to go to the “Jul 26, 2024” button in the ‘choose a date’ section. The AT participant went back into the date picker component and picked July 25, when they exited the picker the focus went back to where they expected. 
### Filters 
- **P16 (VoiceOver):** Didn’t find the filtering options without prompting.

## Quotable Moments

### P13 - JAWS AT User: 

- [Goes line by line. Comes across the Crisis Line link.] “This is good…having this out there up-front is really important.” 
- [Schedule card] “What expires in 310 days? My appointment? I don’t know what you’re trying to say.” There’s no indication that “you can now schedule your appt” is connected to “expires in 310 days.”
- [Gets to the July 2024 heading.] “I don’t know why you have [this] all the way down here.” [Thinks the appointments should be right after the schedule link. (Or put another way, the upcoming / pending / past menu is in the way.)]

### P17 - VoiceOver AT User: 

- [Previous experience with the appointments tool.] 
- “No, I have tried and I just kept getting lost, so no, I haven’t been able to conquer that.” 
- “I can check my appointments. I can cancel appointments, but I haven’t been able to schedule any appointments. It has just become too cumbersome to do it.” 
- [Choosing date and time] “When I clicked that, it didn’t pop right back to July 26. It popped back up to the address. Usually when I go in, maybe for flight reservations, I click July 26 it clicks me right back to where this was.” 

## Related Items

-  #86740 
- [Detailed CodePen Audit findings from 6/25/2024 (Mobile/Android/TalkBack/Chrome)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86740#issuecomment-2189308373)
