### ISSUE TITLE
Implement Form 21a Save in progress (SIP)

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#86193]
### Problem
Forms on VA.gov support the ability to save progress to a user’s account and resume them later. This needs to be implemented for Form 21a.

### Mockups/Designs
<img width="699" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHR2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db24d08aa6fa15e944739b30ad96880ede7aa844/Screenshot%202024-06-17%20at%209.50.28%E2%80%AFPM.png" alt="Screenshot 2024-06-17 at 9.50.28 PM.png" />

### Implementation Details
- Frontend developer documentation > VA Forms Library How Tos > [How to set up Save In Progress (SiP)
](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si)
> - Enabling SiP requires:
>   - Configuring naming and messaging options in the form config
>   - Making the SiP form retrievable on the User Profile page
>   - Configuring prefill in vets-api

### Prerequisites
- None

### Acceptance Criteria
- [x] A Form 21a submission can be saved while in progress

### Automated Testing
- The implementation has e2e testing in Cypress if applicable

### Accessibility (A11y) Testing
- There are no A11y errors in the console
- The developer does not degrade built in VA Form Library A11y in order to implement custom functionality

**Comment by gabezurita** [comment]
This may be resolved by: https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/87799
