### ISSUE TITLE
pull SSH keys from GitHub API

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#862]
While we are working through details on proposal for GitHub user management, it's clear that one aspect we all agree on is letting GitHub store SSH keys and retrieve them from the API rather than storing in a repo as it was originally implemented.

Can be done on a group-by-group basis:
- [ ] update the ansible config file to use the GitHub user module to get the SSH keys. 
- [ ] Audit of current users listed, and remove any inactive - look for help to ensure validity
- [ ] migrate existing lists from what we currently have (email addresses) to GitHub usernames
  - for now we will continue to store the list in the git repo (ansible/global/config.yml), but remove the need for back-and-forth with users to get their keys
  - Ansible role updated to pull keys from GitHub instead of local files from inside repo
- [ ] Remove keys in old role directory ansible/roles/dsva-<something>/files/ tech details

**Comment by ricetj** [comment]
Nick will drive what is the first step.

**Comment by nwalke** [comment]
This is being tracked in other issues.
