### ISSUE TITLE
10-7959f-2: FMP claims process flow

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#86206]
Begin creating FMP [claims process flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718652759079/9b8e9bf6a84513373bc234644531bf694d9a4f84?sender=u3844370d13a440a7859d3526).

**Comment by StevenStraily** [comment]
Ready to be closed out to represent the work completed this sprint, a new ticket will be created for subsequent work in the next sprint.
