### ISSUE TITLE
Payment History VBA Pre-MVP 1.0 - Design -> Frontend

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#86212]
**Phase 1 MVP: Overpayment summary page and detail page:** 
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-17591&t=yCqrWzggTvn2bMBb-1

<img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2x6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9b8eb17556381edcc2274cf37c50b645a5648d6/Screenshot%202024-06-18%20at%202.41.59%E2%80%AFPM.png" alt="Screenshot 2024-06-18 at 2.41.59 PM.png" />

**Comment by HeatherRienks** [comment]
@mgleo and @josephrlee - thinking we might be able to close this one out?

**Comment by HeatherRienks** [comment]
no longer needed
