### ISSUE TITLE
Due May 26th: Redirect Request - Veteran Disability Compensation Rates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8622]
### Description
***This ticket captures legacy page redirects associated with the [Veteran disability compensation rates](https://www.va.gov/disability/compensation-rates/veteran-rates/) page. Additionally, it captures redirect URLs for PDF'd legacy rate pages. @mnorthuis will add legacy URLs associated with this page per her comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7202#issuecomment-621408462).

### Requestor team info
*Public Websites*

### Implementation date
Date new URL(s) will be live: TBD; Seven business days after stakeholders are notified of redirects.

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ X ] Other - Please indicate timing : Seven business days after stakeholders are notified of redirect.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.benefits.va.gov/compensation/resources_comp0118.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0114.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0113.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0112.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0111.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0109.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0108.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0107.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0106.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0105.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0104.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0103.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0102.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0101.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0100.asp | /disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp0199.asp | /disability/compensation-rates/veteran-rates/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

_______
Internal notes

Redirect from https://www.benefits.va.gov/compensation/rates-index.asp to: https://www.va.gov/disability/compensation-rates/
[disability-rates-2017]
(https://app.zenhub.com/files/133843125/325aadc3-fb74-4128-a759-de89e2217f81/download)
[disability-rates-2018]
(https://app.zenhub.com/files/133843125/42ded996-9f0c-4866-92a5-5a9c19df3cf2/download)

**Comment by mnorthuis** [comment]
Per a discuss with Jen and Danielle, it was determined that ALL legacy historical rates pages will be redirected to the new Drupal current rates page.   

I have updated the list of legacy rates pages in the description above to include all known legacy historic pages from 1999 through 2018 (2014/2015 are combined into a single page, as well as 2009/2010. )

These are ready to be implemented once the PDFs fo the 2019 and 2018 rates are live.

**Comment by kelsonic** [comment]
Any dev work here yet? 🙂

**Comment by lunascoop** [comment]
@kelsonic @ncksllvn Table has been updated to reflect updated list of legacy URLs to be redirected. **May 25th** is the scheduled date. Sending stakeholder notification.

**Comment by kelsonic** [comment]
PR is up 🙂

**Comment by lunascoop** [comment]
These redirects have been validated. Closing ticket and updating stakeholders.
