### ISSUE TITLE
Burial | Update form number to 21P-530EZ

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#86229]
## Issue Description
_The VBA noted that the online from flow references the old form number (21P-530) and it should reference the updated number (21P-530EZ)._

<img width="539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejF5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--564cb60668c762eb00e05702c80ccf016ca9e69f/image.png" alt="image.png" />

---
## Tasks
- [ ] Add "EZ" to all 21P-530 references

## Acceptance Criteria
- [ ] All form number references say 21P-530EZ

**Comment by DLarson-Oddball** [comment]
@steele-lm @tblackwe Hey Laura & Thomas, do you know if this update requires a change to the formId, which we use under the hood? We are currently using 21P-530V2, and previously 21P-530.

I am looking to understand how deeply we need to incorporate this change into the burials cleanup work.
