### ISSUE TITLE
Monitor callback API responses to PEGA on datadog dashboard

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#86228]
As a member of the IVC forms team, I need to see callback responses by form on a dashboard so that I know whether or not the PEGA team's calls are successful without them telling us.

Acceptance criteria
- Our knowledge of failed calls to the callback API isn't dependent on the PEGA team reaching out to us.
- IVC forms members will get an alert when failed callbacks reach a given threshhold (alert when 5% of calls fail, if we need a starting point)
- Monitor needs to alert quickly when errors show up--at least within an hour

**Comment by balexandr** [comment]
I forgot that the way we have this set up for UploadsController requires no code change. I added these two to the dashboard:
1. PegaController (Callback API) overall Logs
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1c92a380550e7c085222c8d53264d47f0bd6c26/Screenshot%202024-06-26%20at%204.46.31%E2%80%AFPM.png" alt="Screenshot 2024-06-26 at 4.46.31 PM.png" />

2. PegaController Status codes
<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ccb1b6b91e2bd4bf1449f13b0da468f81138895/Screenshot%202024-06-26%20at%204.47.20%E2%80%AFPM.png" alt="Screenshot 2024-06-26 at 4.47.20 PM.png" />

**Comment by balexandr** [comment]
Updated estimate to 1, easier than predicted.

**Comment by balexandr** [comment]
@baltes @marywang2 @cloudmagic80 Added a new monitor for the our callback API that can be found here: https://vagov.ddog-gov.com/monitors/240152?view=spans.
It will alert the dd channel in OCTO if there is a status != 200

**Comment by balexandr** [comment]
@marywang2  @baltes In Postman I did a 200, 400, and 500 request. You can see the 3 bars here in this image. So everything is up and running properly
<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61860343c6360936bef3dfca5edcb68567a08c6e/Screenshot%202024-06-28%20at%2011.12.48%E2%80%AFAM.png" alt="Screenshot 2024-06-28 at 11.12.48 AM.png" />
