### ISSUE TITLE
Callback error: investigate 500 returned to PEGA

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#86244]
Cindy is getting an error trying to hit the callback API. 

Expected result
- 200 returned to PEGA team
- Call from PEGA visible to IVC forms team

Actual result as reported by Cindy:

#### This is what I am sending

{'Content-type': 'application/json', 'Authorization': 'Bearer AUTH_TOKEN'}

{'form_uuid': 'uuid', 'file_names': 's3_key', 'status': 'vaStatus'}

 
#### And this is what I get back

<Response [500]>

b'{"errors":[{"title":"Internal server error","detail":"Internal server error","code":"500","status":"500"}]}'

**Comment by baltes** [comment]
@cloudmagic80 Just added this for the error Cindy was getting last week.

**Comment by baltes** [comment]
@cloudmagic80 Assigning this one to you for now, please go ahead and move it to in progress if you're working on it.

**Comment by balexandr** [comment]
@baltes This error is happening because they are passing a `String` instead of an `Array` as the `file_names:` value. I can add some error handling around this but fixing that value format will resolve the error.

**Comment by balexandr** [comment]
Update: Cindy got it working in Postman and in regular python code but needs to make changes to the lambda. We are waiting for Cindy to confirm its working.

**Comment by baltes** [comment]
Waiting for confirmation that this is working from the lambda, but we can close at sprint end if she's only hitting via postman.

**Comment by baltes** [comment]
Closing this. We still don't have confirmation from Cindy but there's nothing for us to act on. Anything new can go into a new ticket.
