### ISSUE TITLE
Get stakeholder approval for Verify alerts

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86248]
### User story

As a Cartography team member, I want to get the "Verify" and "Register" alerts approved by Patrick and other OCTO stakeholders for implementation, so that we can implement with confidence.

### Notes
- continues #84522 
- consider post-integration analytics on alert frequency?
- 6/25 [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1719335838877749) covers the steps to get to the bottom of this. Those steps:
> 1. Patrick will email Carnetta & Joe to get verification that shadow ID.me accounts are created when these users first sign onto [VA.gov](http://va.gov/) using their basic accounts
> 2. Laura & Sara will take another pass on simplifying what we communicate around the ID.me section of this alert & mock it up again 
> 3. Over time, move toward eliminating the ID.me wrapper that these users see when they first sign into [VA.gov](http://va.gov/) and simply don't allow MHV basic accounts anymore - users need to already have an MHV Premium account to access My HealtheVet with that credential type.

Possible tasks:
- Not sure what stakeholder we need approval from - Tom Black, Carnetta? 

## Acceptance criteria

- [x] Implementation tickets updated with approved content:
  - [x] #77357 
  - [x] #83069 
- [ ] Stakeholders agree to implementation

**Comment by sterkenburgsara** [comment]
Update: [relevant Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1719335838877749)

Meeting scheduled for Thursday, 6/27/2024 to do a live demo with @jonathanjnelson and Patrick walking through the process of signing into VA.gov using a brand new MHV basic account. We'll record so that others can view if questions arise.

**Comment by wesrowe** [comment]
I'll confirm in standup today that the latest content draft (in [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1719607296686899?thread_ts=1718392016.608289&cid=C0581MN69TJ)) that Laura finished before OOO is approved. I think Danielle endorsed it in the thread. If so, this will unblock the two implementation tickets that depend on this one.

**Comment by sterkenburgsara** [comment]
Closing this ticket to unblock our team for implementation on the alerts (follow-on tickets have been updated). We are still pending stakeholder approval of the My HealtheVet basic alert content, but if feedback necessitates a change, I will create an additional follow-on ticket to edit alert content in a future sprint.
