### ISSUE TITLE
Due May 26th: Redirect Request - Birth Defect Compensation Rates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8624]
### Description
***This ticket captures legacy page redirects associated with the [birth defect compensation rates](https://www.va.gov/disability/compensation-rates/birth-defect-rates/) page. Additionally, it captures redirect URLs for PDF'd legacy rate pages. @mnorthuis will add legacy URLs associated with this page per her comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7202#issuecomment-621408462). 

### Requestor team info
*Public Websites*

### Implementation date
Date new URL(s) will be live: TBD; Seven business days after stakeholders are notified of redirects.

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ X ] Other - Please indicate timing : Seven business days after stakeholders are notified of redirect.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL | Redirect Destination (new URL)
-- | --
https://www.benefits.va.gov/compensation/sb2019.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2018.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2014.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2013.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2012.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2011.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2009.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2008.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2007.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2006.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2005.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2004.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2003.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2002.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2001.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb2000.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.benefits.va.gov/COMPENSATION/sb1999.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/

We will also need PDF link redirects (once the PDF URLs have been created and posted by Anne), and other legacy URLs on that @mnorthuis has on a list (please add here)

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

_____
Internal Notes

Redirect from https://www.benefits.va.gov/compensation/sb2019.asp to: https://www.va.gov/disability/compensation-rates/birth-defect-rates/
[disability-benefits-birth-defects-2017]
(https://app.zenhub.com/files/133843125/118459e2-83c4-4407-b641-abb39b8ef680/download)
[disability-rates-birth-defects-2018]
(https://app.zenhub.com/files/133843125/fb9de85d-f33a-4eff-b6bd-d680636f378c/download)

**Comment by mnorthuis** [comment]
Ensure all legacy URL redirects are not case sensitive. 

The list of URLs above have been reviewed and are ready for implementation once the 2018 and 2019 historical rates are converted to PDF and linked to from production. 

For documentation purposes:
- There is no historical rates page for 2015 or 2010
- The historical rates for pre-1999 are saved in a Word document that we will not be linking to or redirecting https://www.benefits.va.gov/warms/docs/admin21/m21_1/part1/appb/sectXVI.doc

**Comment by lunascoop** [comment]
@kelsonic @ncksllvn Table has been updated to reflect updated list of legacy URLs to be redirected. **May 25th** is the scheduled date. Sending stakeholder notification.

**Comment by kelsonic** [comment]
PR is up! 🙂

**Comment by lunascoop** [comment]
These redirects have been validated. Closing ticket and updating stakeholders.
