### ISSUE TITLE
[Bug] CST: User with no claim or appeal status shows a blank screen

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#8625]
## What happened?

When opening the claim status tool (CST), and the user has nothing to show. A blank screen with no information is shown

![Screen Shot 2020-04-30 at 2 31 21 PM](https://user-images.githubusercontent.com/136959/80751548-9c297180-8aef-11ea-9fa8-101604b45440.png)

Tested on va.gov on my personal account:

API called: https://api.va.gov/v0/evss_claims_async 
Result: `{"data":[],"meta":{"syncStatus":"SUCCESS"}}`

While trying to find a testable user on staging, I tried user 2 and noticed these results:

API called: https://staging-api.va.gov/v0/appeals (only)
Result: 

```json
{
  "errors": [{
    "title": "Not found",
    "detail": "Appeals data for a veteran with that SSN was not found",
    "code": "CASEFLOWSTATUS404",
    "source": "A veteran with that SSN was not found in our systems.",
    "status": "404"
  }]
}
```
I will keep on the look out for a suitable user to test

![Screen Shot 2020-04-30 at 2 48 08 PM](https://user-images.githubusercontent.com/136959/80752763-b6644f00-8af1-11ea-8ec3-2b7eec1ea48e.png)

## Specs:
- Device: All
- Browser: All
- Test User: Unknown? I used my personal account on va.gov

## Steps to Reproduce
- URL: https://staging.va.gov/track-claims/your-claims
- Test User _(if applicable)_: ??

## Desired behavior

Show a message stating that the user does not have any submitted claims (see blue box in the screenshot above); but the content might need to be changed.

## Acceptance Criteria
- [ ] Show user with no claims or appeals a message

**Comment by luke-gcio** [comment]
Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/8815

**Comment by SarahJaine** [comment]
Unfortunately, the 404 response is what's expected.  I talked to @Mottie and we agreed this is really a FE ticket.  I'm happy to provide any support I can, but making the needed changes to the vets-website is out of my hands.  Reassigning to Robin and labeling FE.

**Comment by Mottie** [comment]
Possibly fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/13371 - will verify once that PR has been merged.
