### ISSUE TITLE
RUM replay improvement

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#86254]
noticed that RUM is [**abstracting the complete UI and not just PII**](https://vagov.ddog-gov.com/rum/replay/sessions/e56e0698-4a6a-43bc-bf26-0ea973ab0fc9?applicationId=b3319250-eeb3-419c-b596-3422aec52e4d&seed=f27f567c-4070-41b8-a120-58fce28018fd&ts=1718436018963)

**AC**:
- UI elements should be readable
- PII should remain abstracted

<img width="505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1J5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc42d0989c5c6cf3bee62889b03849f7c498d16e/image.png" alt="image.png" />

**Comment by wayne-weibel** [comment]
I am not sure why or how this is being controlled, but watching a replay specifically for the pension form and only the field values are being redacted

https://vagov.ddog-gov.com/rum/sessions?query=%40session.has_replay%3Atrue%20%40type%3Aview%20%40view.url_path%3A%22%2Fpension%2Fapply-for-veteran-pension-form-21p-527ez%2Fapplicant%2Finformation%22&agg_m=count&agg_m_source=base&agg_t=count&cols=&fromUser=false&viz=stream&from_ts=1719344557791&to_ts=1719430957791&live=true

<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21VQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6752b2a74093de5f854af1fa1c292169edfac59b/image.png" alt="image.png" />

**Comment by wayne-weibel** [comment]
<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24de8ec6809fae3f13c71ffbd060430be121dd18/image.png" alt="image.png" />
