### ISSUE TITLE
Due May 26th: Redirect Request - Special Monthly Compensation Rates Page

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8626]
### Description
***This ticket captures legacy page redirects associated with the [special monthly compensation rates](https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/) page. Additionally, it captures redirect URLs for PDF'd legacy rate pages. @mnorthuis will add legacy URLs associated with this page per her comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7202#issuecomment-621408462). @AnneHurley please add PDF links to the Redirects needed table below after ticket #8408 is completed.***

### Requestor team info
*Public Websites*

### Implementation date
Date new URL(s) will be live: TBD; Seven business days after stakeholders are notified of redirects.

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ X ] Other - Please indicate timing : Seven business days after stakeholders are notified of redirect.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL | Redirect Destination (new URL)
-- | --
https://www.benefits.va.gov/COMPENSATION/resources_comp02.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0218.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0214.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0213.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0212.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0211.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0209.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0208.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0207.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0206.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0205.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0204.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0203.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0202.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0201.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0200.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/COMPENSATION/resources_comp0299.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/

We will also need PDF link redirects (once the PDF URLs have been created and posted by Anne), and other legacy URLs on that @mnorthuis has on a list (please add here)

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
Ensure all legacy URL redirects are not case sensitive.

The list of URLs above have been reviewed and are ready for implementation once the 2018 and 2019 historical rates are converted to PDF and linked to from production.

For documentation purposes:
- There is no historical rates page for 2015 or 2010

**Comment by kelsonic** [comment]
Any dev work here yet? 🙂

**Comment by lunascoop** [comment]
@kelsonic @ncksllvn Table has been updated to reflect updated list of legacy URLs to be redirected. **May 25th** is the scheduled date. Sending stakeholder notification.

**Comment by kelsonic** [comment]
PR is up 🙂

**Comment by lunascoop** [comment]
These redirects have been validated. Closing ticket and updating stakeholders.
