### ISSUE TITLE
SOCKS access for [Gregory Wright]

### ISSUE THREAD

**Issue by GWright321** [department-of-veterans-affairs/va.gov-team#86274]
### Your Name

Gregory Wright

### Your Email

gwright@thesocompany.com

### Your GitHub Handle

GWright321

### Your Role and Team

Tier 1 - Platform Support Team

### Product Manager (PM) name and email

Alyssa Gallion - alyssa.gallion@oddball.io

### Product Owner (PO) name and email

Erika Washburn - Erika.Washburn@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlTYLhdFrvNB0pqPcP3h8wfWtH2StczXv4fvPz8XNgK gregorywright@Gregorys-MBP

### E-QIP Transmittal Confirmation

<img width="1116" alt="Screenshot 2024-06-18 at 2 33 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/168758955/ca7a07a4-f9d9-49b5-b2ae-70fd559ae934">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Merged your SOCKS PR. Please let me know if there's any issues.

**Comment by hgbarreto** [comment]
@GWright321  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.

**Comment by GWright321** [comment]
@hgbarreto OK. Thank you.
