### ISSUE TITLE
Spike: pdftk

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#86284]
# Overview
Another team is working to replace pdfkt with hexapdf since pdfkt is quite old and doesn't support newer encryption methods.  I've done a quick look at our code in pension and I see us using prawn for pdf creation, but I don't see references directly to pdftk.  Is prawn using pdfkit under the covers or are there additional references that I don't see?

Some context:
https://dsva.slack.com/archives/C0460N83Y9G/p1714615111455679

Replacement with hexapdf:
https://github.com/department-of-veterans-affairs/vets-api/pull/16989

# Tasks
- [ ] Determine if a switch to hexapdf is something we will need to deal with on pensions.
- [ ] Evaluate changes made in the [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16989) by the other team

**Comment by wayne-weibel** [comment]
pdftk is a binary library that the ruby gems are built on top of.  pdftk is not included directly by the Gemfile, but errors occur during install if it is not present and during runtime (creating a pdf) if there is a version issue.

**Comment by wayne-weibel** [comment]
https://www.reddit.com/r/ruby/comments/uyidkk/comment/ia6s3an/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by wayne-weibel** [comment]
pdftk is used with PdfForms within PdfFill, among other places in the codebase, as part of Settings
```
module PdfFill
  module Filler
    module_function

    PDF_FORMS = PdfForms.new(Settings.binaries.pdftk)
    UNICODE_PDF_FORMS = PdfForms.new(Settings.binaries.pdftk, data_format: 'XFdf', utf8_fields: true)
    FORM_CLASSES = {
```

**Comment by wayne-weibel** [comment]
Pension could break from the current PDF functionality and spearhead implementation of libraries to remove the need for `pdftk`.  There is functionality for filling interactive fields in HexaPDF, but it is more complex that the current way, but should be able to use the same form field dictionary.

**Comment by mjknight50** [comment]
Since we aren't doing encryption, I guess we could make this a lower long term goal to move off pdftk, if at all.
Closing this ticket.
