### ISSUE TITLE
Due May 26th: Redirect Request - Disability Rates Index Legacy Page

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#8631]
### Description
This redirect is for the Disability Rates Index Legacy Page to the main disability compensation rates page.

### Requestor team info
Public Websites

### Implementation date
Date new URL(s) will be live: TBD; Seven business days after stakeholders are notified of redirects.

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ X ] Other - Please indicate timing : Seven business days after stakeholders are notified of redirect.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.benefits.va.gov/compensation/rates-index.asp | https://www.va.gov/disability/compensation-rates/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
Please ensure legacy URLs are not case sensitive. 

This redirect can be implemented when you are ready.

**Comment by kelsonic** [comment]
PR is up! 🙂

**Comment by lunascoop** [comment]
This redirect has been validated. Closing ticket and updating stakeholders.
