### ISSUE TITLE
Form Details Landing Page - "Form Last Updated" label

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8633]
Update label to "Form last updated". 
This label will be shown in place of "Revision date" or "Issue date"

**Goal**
There is a field in form search results labeled "Revision date". It is currently populated by one of two db fields - revision_date or issue_date.
Some forms only have an issue date, because they have never been updated. 

To bring these into alignment, we recommending using the label "Form last updated" on the form detail landing page FE, so that we can display whatever the most recent date of the form, be it its issue or revision date. 

**Acceptance Criteria**
- [ ] For all forms landing pages, the frontend label name reads as "Form last updated".
- [ ] For the forms search results label that currently shows "Revision date" [added 6/ 16 Jen]
- [ ] The label corresponds to either the form's revision date or issue date (populate by one of two db fields). 
- [ ] If the form has never been revised after it was issued, the issue date will populate as for "Form last updated" field
- [ ] If the form has been revised after it was issued, the revision date will populate for for "Form last updated" field
- [ ] There should not be a situation where a live form does not have either an issue date or a revision date - if we find a real-world case of this, please alert Stephanie so we can clarify what should populate for this edge case

This is a Frontend task

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx - I added one more in the AC above. Feel free to pull it out as a different ticket if you want to keep form detail page updates separate from form search page updates. This field label logic and change happens to affect a field that appears on both search results and form detail page. 

`For the forms search results label that currently shows "Revision date" [added 6/ 16 Jen]`

**Comment by kelsonic** [comment]
PR merged! 🙂

**Comment by kelsonic** [comment]
Validated and moving to close!

![image](https://user-images.githubusercontent.com/12773166/87061063-8360ca80-c1c8-11ea-89f1-996b495a8337.png)
