### ISSUE TITLE
Platform Security Access Review [DUE September 16 2024]

### ISSUE THREAD

**Issue by kell-y** [department-of-veterans-affairs/va.gov-team#86333]
**Access Review Description:** 

OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

OCTO-DE teams periodically review user access to ensure that access is limited to users who currently need to access the systems and applications and that those users have the appropriate permissions.

Platform Security initiates each review cycle and application owners are responsible for executing the process for each application that they own. Once complete, application owners document the results of the access review and send the artifacts to Platform Security to document in eMASS as evidence.

Tasks:

- [x] Complete access review for [TestRail](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3214114851/ACCESS%2BREVIEW%2B-%2BTestRail&sa=D&source=calendar&ust=1719171735830741&usg=AOvVaw3yMkzoSwtC8E3Bi6iMkuiy)

AC:

- [x] Notify Platform Security that the access reviews are complete.

Resources:
Below are three links that describe the access review process:

- [Access Review Process](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2987917734/Access%2BReview%2BProcess&sa=D&source=calendar&ust=1719158451280711&usg=AOvVaw08AyZp9deGU070J8dJO3PF)
- [Access Review Rollout Plan - First Iteration](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3133177925/Access%2BReview%2BRollout%2BPlan%2B-%2BIteration%2B1&sa=D&source=calendar&ust=1719158451280711&usg=AOvVaw0GhA4tfW05Zzqt09vNiBkp)
- [Access Review Inventory](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2986115091/Access%2BReview%2BInventory&sa=D&source=calendar&ust=1719158451280711&usg=AOvVaw39aqVCe_N4uS34DpyhDjiG)

**Comment by bdech** [comment]
Closing. Duplicate to https://github.com/department-of-veterans-affairs/va.gov-team/issues/88217
