### ISSUE TITLE
Education rewriting restart: Montgomery GI Bill - Active Duty (Chapter 30) rates

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/va.gov-team#8634]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [X] Initial copy edit

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi) Preview: preview-prod.vfs.va.gov/preview?nodeId=5355
- [x] Add cross links to this page from other appropriate pages (Anne or Randi)
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
 - **Url:** https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/
 - **Left nav label:** MGIB-AD rates

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page: **https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100118.asp
 - **SEO keywords:** montgomery gi bill rates, mgib rates, chapter 30 gi bill rates
 - **What’s needed for rewriting:**
   - Incorporate the information and rate tables. Edit to align with plain language and VA.gov style standards.
   - Optimize for SEO.
   - Consider how we might structure the page so that the user can easily get to/see the info they need without feeling overwhelmed, but also avoiding hiding pertinent info.
    - Implement historical rate solution.
   - Work in crosslink to new $600 buy-up program rates page.
   - Add related links as relevant.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/montgomery-active-duty-rates.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by RLHecht** [comment]
This page is now built in Drupal with new 2020 rates put in and the historical rates links updated to the most recent last three years. We will change to PDFs once we get confirmation of how to proceed for all historic rates PDFs from an accessibility front.

**Comment by RLHecht** [comment]
@AnneHurley Can you please check that I entered in the 2020 rates correctly from the legacy page?
Drupal page: preview-prod.vfs.va.gov/preview?nodeId=5355
Legacy page to check against: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100119.asp

**Comment by AnneHurley** [comment]
@RLHecht  - Page looks good. Notes:
1. In TOC this link says "and" : "...between 2 and 3 years" and the headline it links to says "between 2 to 3 years" - I think either works, but will let you decide. 
2. A couple of questions i'll ask you about directly, about our style for "$ U.S." and punctuation in a couple of bullet lists

**Comment by AnneHurley** [comment]
@RLHecht Have updated all instances of explaining $ to: **$ U.S. dollars**
Good to go to Danielle.

**Comment by RLHecht** [comment]
@psanders86 Here's the word doc with my edits. Let me know if you have any questions. [https://app.zenhub.com/files/133843125/556d5d1f-0aa9-4bc5-b180-8541042b336d/download](https://app.zenhub.com/files/133843125/556d5d1f-0aa9-4bc5-b180-8541042b336d/download)
