### ISSUE TITLE
Education rewriting restart: Montgomery GI Bill - Selected Reserve (Chapter 1606) rates

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/va.gov-team#8635]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi) Preview link: preview-prod.vfs.va.gov/preview?nodeId=5449
- [x] Add cross links to this page from other appropriate pages (Anne or Randi)
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
 - **Url:** https://www.va.gov/education/benefit-rates/montgomery-reserve-rates
 - **Left nav label:** MGIB-SR rates

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page:** https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch1606/ch1606rates100118.asp
 - **SEO keywords:** reserve gi bill rates, chapter 1606 rates, chapter 1606 gi bill rates, mgib sr rates, montgomery gi bill selected reserve rates
 - **What’s needed for rewriting:**
   - Incorporate the information and rate tables. Edit to align with plain language and VA.gov style standards.
   - Optimize for SEO.
   - Consider how we might structure the page so that the user can easily get to/see the info they need without feeling overwhelmed, but also avoiding hiding pertinent info.
    - Implement historical rate solution.
   - Add related links as relevant.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/montgomery-reserve-rates.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by RLHecht** [comment]
This page has been built in Drupal and new 2020 rates info has been brought in. Note: There were no Historical rates links at the bottom of the Github page. Should these be added for consistency with other rates pages?

**Comment by AnneHurley** [comment]
@RLHecht  - Made one small copyedit. This is now ready to go to Danielle.

**Comment by RLHecht** [comment]
@psanders86 I copied edit this. Ready to move to validate. @SgardnerPMP Can you create a ticket for Beth to review?

**Comment by SgardnerPMP** [comment]
See review in story #39631
