### ISSUE TITLE
AWS access for Alexander Kharbush

### ISSUE THREAD

**Issue by AlexJKharbush** [department-of-veterans-affairs/va.gov-team#86352]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Alexander

### Your Email

alexander.kharbush@va.gov

### Team, Role, and Company of the target individual

AI team, MLE, VA

### Product Manager (PM) name and email

Kimberly McManus

### Product Owner (PO) name and email

kimberly.mcmanus@va.gov

### Desired AWS Access

Amazon S3: For storing model artifacts, training data, and logs.
Amazon SageMaker: For training new models and managing machine learning workflows.
Amazon CloudWatch: For monitoring and logging.
Amazon IAM: For managing permissions and access control.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateTags",
                "ec2:DescribeInstances",
                "ec2:TerminateInstances",
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "sagemaker:CreateTrainingJob",
                "sagemaker:DescribeTrainingJob",
                "sagemaker:CreateModel",
                "sagemaker:CreateEndpoint",
                "sagemaker:InvokeEndpoint",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:GetLogEvents",
                "logs:DescribeLogGroups"
            ],
            "Resource": "*"
        }
    ]
}

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

n/a

### Additional Notes

I am working with Kimberly to build and deploy models. Please let me know what else you need. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Hi there,

Do you happen to have an `e-qip` transmittal? This is needed for us to provide AWS account creds.

**Comment by AlexJKharbush** [comment]
Hey Steven, thank you for the help here. I just put in a request to get it. I will update here once I get it back, maybe 24 hours?

**Comment by AlexJKharbush** [comment]
I'm still waiting on this, I just sent a follow up email.

**Comment by AlexJKharbush** [comment]
I sent you a follow up on teams @stoiven

**Comment by AlexJKharbush** [comment]
My security information was transmitted to John Lewis on 5/16/24. Please let me know if you need anything else!

**Comment by AlexJKharbush** [comment]
Just Following up here, is there anything else you need from me @stoiven ?

**Comment by flooose** [comment]
@AlexJKharbush the eqip transmittal has to be attached to this issue.

**Comment by flooose** [comment]
Closing this for now. If and when you get your e-qip transmittal, feel free to reopen :)
