### ISSUE TITLE
Expand Postman Collection for `vets-api` EKS Next Testing

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#86357]
# Description
Given the characteristics of the spike solution created as a result of this [ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/84143), we need to continue to expand the scope of the initial Postman collection. We will create Postman tests for 5 additional authenticated endpoints. The list of endpoints will be determined as part of the scope of this work. The tests will be executed against the `vets-api` that is running in the EKS-Next cluster.

# Acceptance Criteria

- [x] A list of 5 `vets-api` endpoints that require authentication is available as a comment in this ticket
- [x] One test per endpoint has been added to the Postman collection
- [x] The Postman collection is capable of executing against the `vets-api` endpoints running in the EKS-Next cluster.

**Comment by IGallupSoCo** [comment]
The authenticated endpoints covered by at least one test:
- v0/user
- v0/feature_toggles
- v0/backend_status
- v0/contact_us/inquiries
- v0/coe/status
- v0/coe/download_coe
- v0/documents
- v0/form1095_bs/available_forms
- v0/onsite_notifications
- travel_pay/claims

**Comment by IGallupSoCo** [comment]
Newman CLI is running the collection locally without issue.  Seeing as how we are already using a collection variable for the root url of each request, it should be straightforward to pass in a specific address for the runner to use with the Postman collection once it's integrated into the relevant vets-api deployment GHA workflow.
