### ISSUE TITLE
Education rewriting restart: $600 buy-up program rates

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/va.gov-team#8636]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [x] Initial strategy/voice edit (partial)

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi) Preview page: preview-prod.vfs.va.gov/preview?nodeId=5572
- [x] Add cross links to this page from other appropriate pages (Anne or Randi)
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
 - **Url:** https://www.va.gov/education/benefit-rates/600-buy-up-rates
 - **Left nav label:** $600 buy-up program _(double check with left nav spreadsheet from Mikki)_

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page:** https://www.benefits.va.gov/gibill/resources/benefits_resources/rates/600_buyup.asp
 - **SEO keywords:** gi bill buy up program
 - **What’s needed for rewriting:**
   - Incorporate the information and rates. Edit to align with plain language and VA.gov style standards.
   - Optimize for SEO.
    - Implement historical rate solution.
   - Add related links as relevant.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/600-buy-up-rates.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by RLHecht** [comment]
5/6 update: Currently building page in Drupal from Github.

**Comment by RLHecht** [comment]
This page is now built in Drupal (preview link in checklist above): The rates have not changed for 2020 so no updates need to be made.

**Comment by AnneHurley** [comment]
@RLHecht  Did copyedit pass, looks good. Ready for Danielle.

**Comment by psanders86** [comment]
Hello @joshkimux and @AngelaFowler82 .. we're working on creating a new page for the GI Bill 600 Buy-Up program rates and we have an accessibility question on how to best display these rates, as there 30 rows of information and as many as 4 columns. A Veteran's payment could be affected by how much they've paid into the program and how much they're enrolled in school.

Here's a preview link with 2 approaches: http://preview-prod.vfs.va.gov/preview?nodeId=5572

The first approach (at the top of the page) is to break the rates into 4 different charts and put them in an accordion. The advantage is the page would be clean and simple, as would the tables, but we're also asking Veterans to click on an accordion to see the information.

The second approach at the bottom of the page is to create one large table with all the information. The disadvantage to that is it may be harder to read on a mobile device, and it's also a lot of numbers to throw at a Veteran.

Would love to hear your thoughts, as we're planning to wrap up this work during the current sprint. Thank you!

**Comment by joshkimux** [comment]
Hi @psanders86 we can explore, audit, and bring back recommendations first thing next week. Just from reading the comment, the first approach is likely to be more the more accessible option as:
- clicking accordions isn't necessarily an accessibility anti-pattern provided it's well labelled with plain language
- it's more mobile friendly (and 50%+ of our Veterans access VA.gov on mobile devices)

**Comment by bethpottsVADEPO** [comment]
@joshkimux @psanders86 For the first approach where you would break up the rates by enrollment status, you may want to consider a list, chunked somehow, rather than a chart.

**Comment by psanders86** [comment]
Thank you both!

**Comment by psanders86** [comment]
Hi @joshkimux Would you mind giving this one more review? 

After receiving your feedback on accordions and accessibility, we wanted to find a way to present the $600 Buyup program data in smaller chunks. This suggested solution (the group of accordions at the top of the page) uses smaller chunks in rate tables.

I like how it works but I want to make sure you think having short 5-column tables won't be an accessibility issue for mobile users

http://preview-prod.vfs.va.gov/preview?nodeId=5572

**Comment by psanders86** [comment]
Cheers @RLHecht this is ready for copyediting. Thanks!

http://preview-prod.vfs.va.gov/preview?nodeId=5572

**Comment by RLHecht** [comment]
Thanks, @psanders86 I copyedited this and it's ready for Beth's review.

**Comment by SgardnerPMP** [comment]
See review request in Story #39629
