### ISSUE TITLE
Education rewriting restart: Survivors' and Dependents' Educational Assistance Program (Chapter 35) rates

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/va.gov-team#8637]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [x] Initial strategy/voice edit (partial)

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi)
- [x] Add cross links to this page from other appropriate pages (Anne or Randi)
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
 - **Url:** https://www.va.gov/education/benefit-rates/dea-rates
 - **Left nav label:**  Survivor and dependents rates

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page:** https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100118.asp
 - **SEO keywords:** chapter 35, chapter 35 rates, chapter 35 benefits rates, dependents educational assistance rates, chapter 35 pay rates _(note: just put first 2 in Drupal)_
 - **What’s needed for rewriting:**
   - Incorporate the information and rates. Edit to align with plain language and VA.gov style standards.
   - Optimize for SEO.
    - Implement historical rate solution.
   - Add related links as relevant.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/dea-rates.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by AnneHurley** [comment]
@RLHecht Yes I'll take a look at this - I hope later today. Can we do a quick sync later or maybe tomorrow?

**Comment by RLHecht** [comment]
@AnneHurley This page is now built in Drupal, but the newer 2020 rates seem to have more tables on the legacy page than the 2019 page did, which means we need to add more information to our page as well. Would you be able to do this? Also, we have a note under the intro about three new programs that will go into effect after August 2018, so I think that all needs updating too. 

Drupal page: preview-prod.vfs.va.gov/preview?nodeId=5496
Legacy page: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100119.asp

**Comment by AnneHurley** [comment]
@RLHecht  The page is updated: prod.cms.va.gov/node/5496/edit 
A couple of things:
1. I moved the "Rates effective" and "all amounts in $ US" out of the first content section/table, because they apply to all the rates on the page. However, the font in the intro is giant. Should we move those 2 lines back inside the first table, and figure people will assume the dates and $ apply to everything on the page?
2. Apprenticeships and on-the-job training are 1 table, not 2
3. I wrote headlines with ellipses for the new ones to match the others, see what you think.
4. I am still trying to find out why the legacy page has double asterisks next to the 2 new charts -- https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100119.asp . On the legacy page they don't map to anything, but I want to be sure we aren't omitting something important. We can always ask the SMEs about that when we send them the pages.
@DanielleThierryUSDSVA @stephorkandatx  FYSA

**Comment by RLHecht** [comment]
@AnneHurley I read over your changes. I put the Rates effective and the Amounts in U.S. $ back under each table (I changed the header size of the tables to move them out of the table block and into its own WYSIWYG so that it could all fit. This way it matches other pages.

**Comment by psanders86** [comment]
Hello @RLHecht This is ready for a copyedit.

http://preview-prod.vfs.va.gov/preview?nodeId=5496

Sources:
https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/

https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100121.asp

**Comment by RLHecht** [comment]
I copyedited this and its' now ready for Beth's final review. Moving to validate.

**Comment by SgardnerPMP** [comment]
Review in Story #39627
