### ISSUE TITLE
Convert Font Awesome Icons to va-icon web components - Part 5

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#86378]
## Description
There are files that may be obsolete and not utilized by the vaos app but does calls on the use of font awesome icon.  On 6/20/2024, the design platform team will have eslint error out on instances where font awesome is detected and will be blockers for CI deployment. 

Convert remaining files that call on font awesome icon

---

## Acceptance Criteria

- [ ] Convert remaining files that call on font awesome icon to use `va-icon` web component

## Definition of Done
- [ ] VAOS no longer call on font awesome icon 
- [ ] all icon converted to use `va-icon` web component

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniemc** [comment]
@ldelacosta The last of the remaining files (even thought they may not used in the vaos app anymore) are converted to `va-icon`. Would you log into staging and do a validation look at the (1) appointment list, (2) request list  (3) direct schedule calendar (4) direct schedule confirmation (5) request schedule confirmation page to ensure all the icons are looking as expected?  Thanks!

**Comment by outerpress** [comment]
All icons are looking as expected @ldelacosta @jenniemc , thank you!

**Comment by ldelacosta** [comment]
Validated in staging for Judy Morrison. No issues to report. Closing out the ticket.
