### ISSUE TITLE
Analytics: Segment key KPIs for "Tryers" in DD dash

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86377]
### User story

As a Cartography team member reviewing user behavior in our Datadog KPIs dash, I want to be able to see the landing page KPIs for only "Tryers" (users who came to the MHV Portal through try-me banners on MHV Classic), ideally in the same widget that non-Tryers or all users' KPIs are also displayed, so that we can compare the behavior of Tryers to the other users.

### Notes
- For pre-finement: is there a best practice or feature for comparing user segments in Datadog? (It's native to GA)
  - e.g., for the "engagement" number in our KPIs dash, is there a way to make that widget show two numbers, one for Tryers and one for everyone or non-Tryers?
- how to filter Tryers (ideas):
  - maybe landing page facet?
  - maybe Tryers didn't have to sign in to VAgov?

Possible tasks:
- reach out to Patrick, Mark D., SM, other octo folks for guidance!

## Acceptance criteria

- _**Evaluated how the introduction of unique user IDs in DD affects this ticket**_
- Identified data signature in DD for users who arrive at the portal via a try-me banner (Tryers)
- Displayed KPI for the Tryer group alongside a comparison group (all users or non-Tryers) in the following dashboard widgets:
  - Engagement (non-bounce)
  - Conversion

**Comment by katbrinkley** [comment]
Done lots of research on this between Datadog documentation and chatting with Mark Dewey. I believe have found a way to show how users are getting to the site (using view.url_query.utm_medium - not the same as funnels but analyzes paths), but I'm not sure if it's hooked up on the backend to actually do this. I don't really understand how this could be a conversion or engagement unless we pulled those clicks from another larger dashboard that tracks outside of MHV. Reaching out to Wes and Daniel about meeting Monday to talk through some of this hopefully.

**Comment by katbrinkley** [comment]
Updates: Synced with Wes about this - we determined we need more information/steps to set up user segmenting and path analysis in DD.
- Wes asked Patrick for guidance on setting up a way to track through MHV classic to capture where users are coming from as a first step
- Still considering the utm approach, just need more information on how to do this

**Comment by wesrowe** [comment]
@katbrinkley, I moved this back to In Progress since we aren't really blocked. We're just problem-solving at this point. ;-)

**Comment by LynneJohnson224** [comment]
moving to ready - will analyze doing this in GA

**Comment by fmccaf1** [comment]
Decided not to keep pursuing datadog for this purpose right now
