### ISSUE TITLE
Education rewriting restart: Post-9/11 GI Bill monthly housing allowance rates

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/va.gov-team#8638]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [x] Initial strategy/voice edit (partial)

**Steps needed to complete this work now:**

- [x ] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [ x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [ x] Finalize existing GitHub draft (Anne or Randi)
- [ x] Migrate to Drupal (Anne or Randi) preview-prod.vfs.va.gov/preview?nodeId=5574
- [ x] Add cross links to this page from other appropriate pages (Anne or Randi)
1. Anne added link to this page from main Post-9/11 GI Bill (nodeId=1009)
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
**Where this page will live:** 6th page in rates section
 - **Url:** https://www.va.gov/education/benefit-rates/monthly-housing-allowance-rates
 - **Left nav label:**  Monthly housing allowance rates _(confirm)_

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page:** https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080118.asp; others?
 - **SEO keywords:** gi bill housing allowance, gi bill bah rates, post 911 gi bill bah rates, gi bill pay rates, gi bill payment rates  _(note: just put first 2 in Drupal)_
 - **What’s needed for rewriting:**
   - Incorporate the information and rates. Edit to align with plain language and VA.gov style standards.
   - Optimize for SEO.
    - Implement historical rate solution.
   - Add related links as relevant.

### Github files for reference

- **Current page in GitHub:** hhttps://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/monthly-housing-allowance-rates.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by AnneHurley** [comment]
@RLHecht  I've built this page here: preview-prod.vfs.va.gov/preview?nodeId=5574 
Couple of questions:
1. Is where I put the "All rates in $ US" by the table ok? I had it in the same "caption/header" as the "Rates effective" line but it looked too prominent. Is there a way to tuck it in under that header but before the actual table?
2. I think I was able to figure out the HTML inside the table **except** for how we format our square bullets. Can you possibly send me that code when you get a sec?
3. Please double check my various setting for the page/menu/etc - thanks so much. 
@DanielleThierryUSDSVA @stephorkandatx  FYSA

**Comment by RLHecht** [comment]
@AnneHurley I've read over this page. I added the related links at the bottom of the page from the Github file. I also moved around the Rates in U.S. $ and the Rates effective info. I took it out of the table caption and added it to the WYSIWIG above the table so we could format it to a smaller font. I also added the bullets in the table.

**Comment by SgardnerPMP** [comment]
@psanders86, to work on rewrite of content and prep for publishing.

**Comment by SgardnerPMP** [comment]
Moved to in Progress.

**Comment by RLHecht** [comment]
Thanks @psanders86 I copyedited this and will move to validate.

**Comment by SgardnerPMP** [comment]
Please review in #39620
