### ISSUE TITLE
[DevOps] Eric Oliver needs access to veterans-affairs PagerDuty

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86393]
## Description
See [this thread](https://dsva.slack.com/archives/C01U8EYHSEM/p1718380187489689?thread_ts=1718372878.674819&cid=C01U8EYHSEM).

## Tasks
- [ ] [DevOps] Ticket opened with ECC Monitoring for access to PD.

**Comment by olivereri** [comment]
RITM12074932 Submitted to Helpdesk

**Comment by olivereri** [comment]
No progress has been made so far.

**Comment by ndouglas** [comment]
Pinged Stephen today (07/23).

**Comment by ndouglas** [comment]
Access to this particular instance doesn't seem necessary; just request access to DSVA PD in #vfs-platform-support
