### ISSUE TITLE
Education rewriting restart: Post-9/11 GI Bill Resident Rate Requirements

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8639]
# User story

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [x] Initial strategy/voice edit (partial)

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to update rates to 2020 and bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi) Preview link: preview-prod.vfs.va.gov/preview?nodeId=1006
- [x] Add cross links to this page from other appropriate pages (Anne or Randi)
1. Anne added link to this page from main GI Bill rates page (nodeId=1009)
- [x] Ready for Strategy Review (handled in separate ticket)

(update 05/06/2020: we have moved some requirements of this story to package the pages, send to SMEs + get feedback & incorporate into other stories)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
**Where this page will live:** 7th page in rates section
 - **Url:** https://www.va.gov/education/benefit-rates/resident-rate-requirements/
 - **Left nav label:**  Resident rate requirements

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page:** https://www.benefits.va.gov/gibill/post911_residentraterequirements.asp
 - **SEO keywords:** n/a
 - **What’s needed for rewriting:**
   - Incorporate the information. Edit to align with plain language and VA.gov style standards.
   - Add related links as relevant.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/benefit-rates/resident-rate-requirements.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by RLHecht** [comment]
This page had been brought into Drupal previously. Node ID listed above in checklist. I updated two links to point to the GI Bill Comparison Tool instead of the outdated legacy pages.
