### ISSUE TITLE
Education rewriting restart: Compare education benefits

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8640]
# User story

As a Veteran looking to choose a GI Bill or other education benefits program, I need to know which program may be right for me. This is important because once I choose, I can't change my mind.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [X] Strategy/voice edit

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi) Preview Node Id: preview-prod.vfs.va.gov/preview?nodeId=5575
- [ x] Add cross links to this page from other appropriate pages (Anne or Randi)
- [x] Ready for Strategy Review (handled in separate ticket)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
  - **Where this page will live:**  This page will be the last page within the "More Resources" spoke (it will replace the current redirect to the legacy page).
 - **Url:** https://www.va.gov/education/compare-education-benefits/
 - **Left nav label:** Compare education benefits
- We'll also crosslink to this page from other pages within the section.

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page: **https://www.benefits.va.gov/GIBILL/comparison_chart.asp
 - **SEO keywords:** compare va education benefits, gi bill comparison
- **Additional queries to help inform phrasing:** what education benefits are there for veterans, which gi bill is best, which gi bill is better, which gi bill should i choose, which gi bill to use, which gi bill pays bah, which gi bill gives you bah, which gi bill is better for trade school, which gi bill is better for flight training, post 9/11 gi bill vs montgomery, post 9 11 gi bill vs chapter 30
 - **What’s needed for rewriting:**
   - Optimize for SEO.
   - Create a new page in our VA.gov style (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran).
   - Recreate the comparison table in the Github file. (Make any needed adjustments to the structure and copy. Work footnote information into the table to avoid the need for footnotes.
Reframe the various crosslinks on this page as related links, following our VA.gov style.

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/compare-education-benefits.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by RLHecht** [comment]
@AnneHurley This page is now built and ready for you to look over.

**Comment by AnneHurley** [comment]
@RLHecht  - Reviewed and it's ready for Danielle.
