### ISSUE TITLE
Education rewriting restart: Apply to restore GI Bill benefits

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8641]
# User story

As a GI Bill recipient whose school closed or was disapproved, I need to know how to restore my benefits so I can use those benefits for other educational pursuits.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub
- [X] Strategy/voice edit
- [X] Final copy edit

**Steps needed to complete this work now:**

- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Anne or Randi)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Anne or Randi)
- [x] Finalize existing GitHub draft (Anne or Randi)
- [x] Migrate to Drupal (Anne or Randi) Preview link: preview-prod.vfs.va.gov/preview?nodeId=5573
- [x] Add cross links to this page from other appropriate pages (Anne or Randi)
- [x] Ready for Strategy Review (handled in separate ticket)

### IA details

_(note: IA and specifically urls may change based on l4 initiative)_
  - **Where this page will live:**  This page is the last page within the "Manage Benefits" spoke. 
 - **Url:** https://www.va.gov/education/benefits-restoration
 - **Left nav label:** Apply to restore GI Bill benefits
- We'll also crosslink to this page from other pages within the section.

### Content details

_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
 - **Source page: ** https://www.benefits.va.gov/GIBILL/FGIB/Restoration.asp
  - **More info at:** https://gibill.custhelp.va.gov/app/answers/detail/a_id/1481/kw/application%20approval%20or%20disapproval/session/L3RpbWUvMTU1NDY4Mjk3MS9zaWQvaHNVbmxIYm8%3D
 - **SEO keywords:** va restoration of entitlement, forever gi bill, harry w colmery veterans educational assistance act of 2017
- **Additional queries to help inform phrasing:** what education benefits are there for veterans, which gi bill is best, which gi bill is better, which gi bill should i choose, which gi bill to use, which gi bill pays bah, which gi bill gives you bah, which gi bill is better for trade school, which gi bill is better for flight training, post 9/11 gi bill vs montgomery, post 9 11 gi bill vs chapter 30
 - **What’s needed for rewriting:**
   - Optimize for SEO.
   - Create a new page in our VA.gov style (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran).

### Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-education/pages/education/compare-education-benefits.md
 - **Branch:** https://github.com/department-of-veterans-affairs/vagov-content/tree/content-WIP-rewriting-education
 - **PR:** department-of-veterans-affairs/vagov-content#375
- **Heroku:** https://vagov-content-pr-375.herokuapp.com/

**Comment by RLHecht** [comment]
This page is built in Drupal. There are no rates on the page that need to be updated for 2020. Ready for next steps.

**Comment by AnneHurley** [comment]
@RLHecht  Copyedit done, no updates needed. Ready for Danielle.
