### ISSUE TITLE
Re-Add Vista Appointments to New Landing Pages for Pre-Check-in and Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#86410]
## Description 
In an effort to not remove functionality and given that we do not have the list of all Upcoming Appointments (including non-Vista ones) from the appointments service, UX has decided that we should add the appointment list back to Pre-check-in and Check-in for now. We will re-evaluate once we have access to all Upcoming Appointments.

## Wireframes
- [Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1440-31468&t=PFDuziMbWkvixu3D-0)
- [Wireframe ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85723)

## Tasks
- Add the Vista appointment list to Pre-Check-in per the wireframes
- Add the Vista appointment list to eCheck-in per the wireframes

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/86410?planning-poker) with Zenhub @brianseek @wullaski

**Comment by loripusey** [comment]
@brianseek @wullaski Please add detail to this ticket as needed and/or feel free to break it out however you need to. I wasn't sure if your plan @wullaski was to do this work as part of the tickets you already have in this sprint but I wanted to make sure it was accounted for.

**Comment by wullaski** [comment]
@loripusey This looks like a duplicate of this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/86078

**Comment by loripusey** [comment]
ok, that wasn't clear, closing this ticket
