### ISSUE TITLE
Check if a confirmation email was previously sent before sending

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#86428]
We send a confirmation email during the PensionBenefitsIntakeJob. There's no way to 'undo' this step, and we don't have any checks in place to see if the confirmation email was already sent, so this step could get run more than once if the job fails after this step. (It's unlikely the job will fail after this, since all we do afterwards is log the success, but in a worst-case scenario...)

Update Sidekiq job to check whether a confirmation email has been sent for the claim before sending the confirmation email, or otherwise prevent the confirmation email from being able to be sent twice.

One method of doing this might be to use a batch job of some type - [see here in Slack](https://dsva.slack.com/archives/C01UB5A823V/p1718731470125969).

Recommend beginning by seeing if `Sidekick::Batch.new` will work: [example](https://github.com/department-of-veterans-affairs/vets-api/blob/a3acc8b47dccd90ce7313c0ba68ba52f946269f6/app/models/form526_submission.rb#L201)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/86428?planning-poker) with Zenhub @danlim715 @TaiWilkin @wayne-weibel
