### ISSUE TITLE
Update Secure Messaging authorization rules and alerts

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#86422]
## Description

After review of the current [VA.gov Health Tools authorization rules](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-authorization.md), here are the recommended actions for the Secure Messaging app:

- Require that the user is signed in with identity-verified credentials
- Update the redirect for users who cannot use secure messaging to send user to MHV-on-VA.gov landing page (`/my-health`), where a "no access to MHV" alert will display. Currently they are redirected to `/health-care/secure-messaging`

## Possible tasks

- add user verification check on `RequiredLoginView`
- Change the [redirect that points to SM info page](https://github.com/department-of-veterans-affairs/vets-website/blob/b364d52879588928a756ebfcd7ebe7eaf7788aef/src/applications/mhv-secure-messaging/containers/App.jsx#L159) to instead redirect user to MHV landing page, where a "no access to MHV" alert will display
- There's [another redirect](https://github.com/department-of-veterans-affairs/vets-website/blob/b364d52879588928a756ebfcd7ebe7eaf7788aef/src/applications/mhv-secure-messaging/containers/App.jsx#L140) (also in `App.jsx`) that should probably also be updated
- Get feedback/approval from Oleksii (Alex) Morgun (Lead Engineer Secure Messaging on VA.gov), reminding him of [this conversation](https://dsva.slack.com/archives/C03ECSBGSKX/p1719417514868069).

The [RequiredLogInView](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authorization/components/RequiredLoginView.jsx) has a `verify` prop that should redirect users who need to verify. See [Is signed in? Is identity-verified?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-authorization.md#is-signed-in-is-identity-verified) in the MHV authorization doc.

## ACs

- Require that the user is signed in with identity-verified credentials
- Update the redirect to send user to MHV-on-VA.gov landing page (`/my-health`), where a "no access to MHV" alert will display

## Further context

[This discussion with Patrick B](https://dsva.slack.com/archives/C0581MN69TJ/p1719513016915229) which relates to the [brief conversation with Oleksii](https://dsva.slack.com/archives/C03ECSBGSKX/p1719417514868069)

**Comment by radavis** [comment]
This ticket spawned from the Authorization doc and https://github.com/department-of-veterans-affairs/va.gov-team/issues/84911

**Comment by wesrowe** [comment]
Per meeting with Daniel & Richard:
- a route guard is not the recommended approach here
- current UX of directing a user without SM access to the unauthed SM page is probably a suboptimal UX – they are offered the link again and could end up in a circle
- recommendations: 
  - add user verification check
  - redirect user to MHV landing page, where a "no access to MHV" alert will display

**Comment by dcloud** [comment]
I'm going to share this with SM folks, so assigning myself for purpose of communicating about the ticket

**Comment by dcloud** [comment]
@oleksii-morgun didn't have concerns with this approach, after I clarified that "redirect user to MHV landing page" meant to the VA.gov landing page (as opposed to MHV National Portal)

**Comment by wesrowe** [comment]
@dcloud, does that make this something we'll implement?

**Comment by wesrowe** [comment]
I guess, just refine it and lmk. :)

**Comment by dcloud** [comment]
I think we should do this work by opening a PR on the SM codebase and working with that team to get it reviewed. I can leave this assigned to me since I already spoke with Oleksii and am happy to implement

**Comment by dcloud** [comment]
Awaiting review feedback per [this slack thread](https://dsva.slack.com/archives/C03ECSBGSKX/p1723493044485509).

**Comment by wesrowe** [comment]
@dcloud, can you put points on this?
