### ISSUE TITLE
Check if claim was previously submitted before submitting a Pension claim

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#86426]
When we upload the claim to Lighthouse within the PensionBenefitsIntakeJob, if the job fails after we submit, there's no way to 'undo' this step, and we don't have any checks in place to see if the claim has already been submitted, so this step could get run more than once.

Update Sidekiq job to check whether a copy of the claim has been successfully submitted to Lighthouse before attempting to submit the claim.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/86426?planning-poker) with Zenhub @TaiWilkin @wayne-weibel @danlim715

**Comment by balexandr** [comment]
PR for ref: https://github.com/department-of-veterans-affairs/vets-api/pull/18733
