### ISSUE TITLE
[BE] 10-10CG - Improvements: Implement OAuth 2.0 for MuleSoftClient behind flipper toggle

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#86423]
As a first step for implementing OAuth 2.0 Authentication for the 10-10CG form, we need to update the existing MuleSoftClient to use the new authentication flow. 

- This will need to be behind a flipper toggle so we can turn it on for validation in lower environments. 
- More than likely this will follow a client credential grant flow (confirmed this is the case) as it is service to service authentication.
- Helpful info for OAuth 2.0 Client Credential flow with Okta is [here](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/)
- SI (DEV/QA) or DTC-I team (Stage/Prod) will create the application through AnyPoint Exchange for the API which is requested access by the consumer (va.gov)
- DTC-I team will provide us the auth server URL, Client Id, and Client Secret in an encrypted email. (These will need added to AWS Parameter Store with a platform support ticket)

**Comment by hdjustice** [comment]
closed as duplicate. Using #86425
