### ISSUE TITLE
Update Yellow Ribbon tool title tag and meta description

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8642]
## Update Yellow Ribbon tool title tag and meta description

This is still in staging right now, but before it launches the browser title (meta title tag) needs to be updated to follow our browser title format of H1 | Veterans Affairs {initial caps}. 

Format style guide here: https://design.va.gov/content-style-guide/seo#title-tags

https://staging.va.gov/education/yellow-ribbon-participating-schools/

**Currently:** Yellow Ribbon Schools | Veterans Affairs

**Should be:** Find A Yellow Ribbon School | Veterans Affairs

**Meta description:** {please have a content person review and/or provide edits if needed. Should follow this guidance: https://design.va.gov/content-style-guide/seo#meta-descriptions }

Need:
Content review + provide the meta description in this ticket, for FE to implement
FE engineering implementation (bc this is a REACT page?] update the meta tags in the manifest.js configuration

**Comment by kelsonic** [comment]
Could you tag me when the meta description is ready for implementation @AnneHurley? 🙂

**Comment by AnneHurley** [comment]
Meta tag headline: Find A Yellow Ribbon School | Veterans Affairs
Meta description: TBD TBD
