### ISSUE TITLE
Update Appointments authorization rules and alerts

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#86431]
### User Story

As a Veteran, I want to know what action I should take if I don't have access to Appointments, so that I can gain access to this health tool.

 ## Acceptance Criteria

- User is redirected to `/my-health` and shown the "Not registered" alert.
- unit/e2e tests exist within `vets-website/src/applications/vaos` for this functionality.

**Comment by radavis** [comment]
This ticket spawned from the Authorization doc and https://github.com/department-of-veterans-affairs/va.gov-team/issues/84911

**Comment by dcloud** [comment]
The "Not registered" alert reads differently from the current Appointments alert. Per the [mhv-authorization.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-authorization.md) doc 

- The "Not registered" alert uses "My HealtheVet" naming/branding, and the alert talks about access to "My HealtheVet". It uses the phrasing "VA health facility" in one location
- The Appoinments alert emphasizes _facilities_ and registering at a VA health facility.


I think this will **need an AC** for reconciling the messaging, given the "Not registered" alert on the landing page could lead to confusion about "My HealtheVet" when a veteran is trying to make an appointment

**Comment by wesrowe** [comment]
Mtg 6/25:
- Appts does have an alert covering this situation, and it's more specific to their specific use case
- they covered the verification use case we were checking for
Closing.
