### ISSUE TITLE
[526 State] Create SubmissionRemediation model

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#86438]
[documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#a-create-a-form526submissionremediation-model)

**Comment by freeheeling** [comment]
1. [Database migration PR](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/vets-api/17208)
2. [Model creation PR](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/vets-api/17237)

**Comment by freeheeling** [comment]
3. [Add enum, methods and scopes PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17274)

**Comment by freeheeling** [comment]
Deployed [Add enum, methods and scopes PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17274)  7/2
