### ISSUE TITLE
Update After Visit Summary authorization rules and alerts

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#86439]
### User Story

As a VA patient, I want to see instructions for verifying my identity before accessing my After Visit Summary, so that I can access my AVS.

### Acceptance Criteria

- Unverified users who attempt to access AVS are shown instructions to verify their account.
- unit/e2e tests exist for this functionality within `src/applications/avs`

**Comment by wesrowe** [comment]
Mtg 6/25: pass this recommendation to AVS team.

**Comment by wesrowe** [comment]
Via slack with Adrian Rollett we determined that there is no probable way for an unverified user to reach the AVS app. Closing as a no-op.
