### ISSUE TITLE
[526 State] Repair 526 backup polling

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#86432]
[Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#1-repair-our-backup-submission-polling-job)

TL;DR - our `Form526StatusPollingJob` doesn't seem to capture everything it should, e.g. some submissions that have been marked as successful in Benefits Intake have not been transitioned in our local state machine.

**Comment by freeheeling** [comment]
Polling status results for submissions created at least 4 days ago (as of 6/28/24) with a `backup_submitted_claim_id`:
- 10,444 submissions (oldest created 12/55/22)
- 9,812 submissions with `aasm_state` of 'finalized_as_successful'
  - assumed to be updated as intended
- 545 submissions with `aasm_state` of 'delivered_to_backup' (oldest created 5/18)
  - all have a Benefits Intake response status of either 'success' or 'vbms'
  - these should have transitioned an `aasm_state` of 'finalized_as_successful' if `Form526StatusPollingJob` is operating correctly
- 26 submissions with `aasm_state` of 'delivered_to_primary' (oldest created 5/18)
  - state will never be updated by `Form526StatusPollingJob`
- 1 submission with `aasm_state` of 'failed_primary_delivery' (ID 2858449, created 6/21)
  - state will never be updated by `Form526StatusPollingJob`

Thomas remarked that the 'success' status is **not** indicative of a successfully submitted claim, but that it was received by the OCR. Instead, only 'vbms' should be interpreted as confirmation that submission has been delivered successfully.

**Comment by freeheeling** [comment]
Drafted [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17364) submitted for review

**Comment by freeheeling** [comment]
@tblackwe @SamStuckey I have determined that, in some instances, the primary path job continues to retry after encountering a non-retryable error while also rerouting the submission to the backup path, resulting in submissions potentially being delivered via both paths, in the case where a submission ultimately succeeds on the primary path before reaching job exhaustion. 

To avoid double submitting and what could potentially be confusing to a claim reviewer, my recommendation is that this issue be further investigated and remediated.

**Comment by freeheeling** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17364) approved and ready for platform review.
