### ISSUE TITLE
[526 State] add backup_submitted_claim_status and point backup path polling at it

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#86434]
[documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#b-add-backup_submitted_claim_status-enum-to-the-form526submission-model)

## Tl;DR
1. add `backup_submitted_claim_state` to track results of backup submitted claim polling
2. change `Form526StatusPollingJob` to use `backup_submitted_claim_state`

**Comment by freeheeling** [comment]
Combining objectives of this ticket with those in [#86432](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/86432).

**Comment by freeheeling** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17364) approved and ready for platform review.
