### ISSUE TITLE
[526 State] Remove aasm_state from Form526Submission

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#86441]
[documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#3-backfill-our-new-state)

**Comment by SamStuckey** [comment]
When this is unblocked it can be handed off

**Comment by freeheeling** [comment]
Combining objectives of this ticket with those in [#86432](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/86432).

**Comment by freeheeling** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17364) approved and ready for platform review.
