### ISSUE TITLE
LH Document Migration: Investigate and Remediate Issues

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#86458]

**Comment by pmclaren19** [comment]
This is a placeholder ticket for @jerekshoe to add to as issues come up with the rollout for LH benefits documents.

**Comment by jerekshoe** [comment]
Found out that we are not running the antivirus on files that we are uploading to LH / EVSS. Had a few documents that were identified as containing viruses that were not caught by ClamAV (because we aren't running it against the files first)

**Comment by jerekshoe** [comment]
Also found that we need to improve our logging so that we can see the actual error messages coming back from LH as this will help improve our ability to diagnose issues going forward
