### ISSUE TITLE
Document header configurations for VA.gov

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#8645]
# Overview 

- It's not clear what configurations control the headers that appear on VA.gov hosted assets 
- Some [assets](https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.33d363d19b63f27f146b-1588285387717.js) are hosted directly from S3 directly 
- Some [assets](https://staging.va.gov/generated/cta-widget.entry.e8dc347356b222ce7ba1-1588285387717.js) are hosted from S3 through the reverse proxy 

# Goals

- `Cache-Control` header should be documented similarly to how the [Content Security Policy ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/content-security-policy.md)is documented. 
- Should include links to the configurations and an explanation of how the headers manifest on the site 
- Document the caching and cache-busting behaviors (future state)

**Comment by timwright12** [comment]
I would like to update this from documentation to a full rebuild of the header/footer.

**Comment by rmessina1010** [comment]
Expired. Closing.
