### ISSUE TITLE
User Credential Lock Updates

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#86453]
## description
- [x] update rake task to handle "lock all accounts" for an ICN
- [ ] better spreadsheet
  - alerts
  - notes
  - easy way to add lots of userverification entries

## credential_lock interactions - by ICN (more by credential_uuid)

march: 9

april: 4

may: 22

june: 30

july:

**Comment by bramleyjl** [comment]
The `lock_all` method is properly functioning and locking all UserVerifications based on an ICN. I have one small PR to include logging to terminal on production environments, but this is otherwise complete.

**Comment by parkerbees** [comment]
moved to Jira. closing.
