### ISSUE TITLE
Discovery: How to preserve Datadog data past 30 days

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86461]
### User story

As a Cartography team member, I want to be able to preserve/export Datadog Integration metrics so that we can look back at previous metrics.

### Notes
- Datadog only preserves RUM data for the past 30 days since it's primarily a real-time monitoring tool
- We want a way to save that data to look back on as a baseline/reference point

Possible tasks:
- Research ways to preserve data for longer
- Consider exports
- Strategize a system for maintaining access to Datadog analytics data long-term

## Acceptance criteria

- Research possible options for preserving data within Datadog
- Ask other researchers/designers if they have a process for this
- Review options with the team

**Comment by katbrinkley** [comment]
<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2678967fc6d3d63abda659ec3be240e53bc53db/image.png" alt="image.png" />
There is an option to export RUM data, however I don't know if we created this dashboard with RUM settings - seems like our view is different than what I'm seeing. Going to look deeper into this, as well as when the export timeframe captures (i.e., 30 days from today or a set 30 days from dashboard creation?

**Comment by wesrowe** [comment]
I can help with retention: 30-day retention is from the moment an event was recorded.

**Comment by katbrinkley** [comment]
thanks!

**Comment by batemapf** [comment]
Two things: (1) Robyn explored this earlier in the year, so please connect with her if you haven't already; and (2) the workaround here (or at least the most obvious one) is to convert RUM data into a Datadog Custom Metric. This is relatively straightforward to do.

**Comment by katbrinkley** [comment]
awesome thank you!

Updates:
- Can look into converting RUM data into custom metrics
- Can look into generating metrics from ingested logs (this might be a bigger learning curve than converting RUM > custom metrics)
- Kat will try to set up a meeting with the team to work through these

**Comment by LynneJohnson224** [comment]
Data is now being preserved past 30 days - will create a new ticket for custom metrics.
