### ISSUE TITLE
VSP QA feedback on Caregivers 1010CG [Prototype Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#8646]
### Links
**Test Plan / Execution logs:**
Test plan: https://dsvavsp.testrail.io/index.php?/plans/view/175
Test executions: Tests not executed at time of review
**Coverage for References Report**
N/A
**Summary (Defects) Report**
N/A

### Feedback
**Test Plan**
1. Excellent test plan description with loads of references and justifications for test cases created.
1. I noticed that the description calls out a wide selection of environments will be supported, but only one test run is present.  I'm sure this is already in your queue, but consider making use of TestRail's [_Configuration_](http://docs.gurock.com/testrail-userguide/userguide-gettingstarted#test_plans_and_configurations) definitions in order to automatically generate a test run for each environment that you will be testing.
1. [T1276](https://dsvavsp.testrail.io/index.php?/tests/view/1276&group_by=cases:section_id&group_order=asc&group_id=47) uses a previous test case as a precondition,  but only a subset of the steps from the previous test case are required.  This is a bit difficult to organize in TestRail.  Consider creating a copy of the test case being referenced that contains only the prerequisite steps for T1267 to execute successfully.
1. [T1277](https://dsvavsp.testrail.io/index.php?/tests/view/1277&group_by=cases:section_id&group_order=asc&group_id=47) has a similar issue with preconditions.  Consider creating a test case that terminates where the dependent test cases need to pick up from.

## Definition of Done
- [x] Acknowledge each item of feedback with a decision
- [x] VSP QA will close ticket after reviewing feedback decisions

**Comment by ala-yna** [comment]
Hey @pjhill - is there anything else you need @LinnJS to do on this?

**Comment by pjhill** [comment]
@ala-yna -- Since this was just a collection of suggestions and there has been ample time to absorb the feedback, I'm closing this ticket
