### ISSUE TITLE
10-7959c: Confirmation email - create copy

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86469]
As a CHAMPVA OHI applicant, I need to receive a confirmation email so that I know my application is being processed and I know what to expect next.

Acceptance criteria

- Applicants get assurance that their application is moving forward
- Applicants have a general understanding of when they should hear from VA
- Applicants know what to do if they don't hear from VA
- This email will be sent once PEGA has confirmed that an application has been successfully imported, so we can tell the applicant that they're application is being processed and let them know it will take approximately 60 days to process.

Current email template:
<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Y5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9a341acab2a2df6913d1f3956215a597e6d8d82/image.png" alt="image.png" />

Intake [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/81725) w/instructions on how to access VA notify in comments .

**Comment by marywang2** [comment]
DSVA slack [thread](https://dsva.slack.com/archives/C05QKRZGHFS/p1719517786259089?thread_ts=1719517786.259089&cid=C05QKRZGHFS) with example from another team.

**Comment by jamiefiore** [comment]
@marywang2 here is the [link to the email in Figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=2563-125177&t=p17cnSbL8kKTvXZ8-4)
