### ISSUE TITLE
[EKS] Bootstrap ArgoCD Configurations

### ISSUE THREAD

**Issue by adhoc-nshipman** [department-of-veterans-affairs/va.gov-team#86470]
# Acceptance Criteria
- [x] ArgoCD should be deployed with Github configs
- [x] ArgoCD should be able to deploy applications to the new cluster automatically

# Notes
- This migrates us from a central Argo to a per-cluster Argo
- Source will be located in https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure
- Enables exposing individual Clusters/ArgoCD's, while not exposing all
- [values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/41b734b55d0f6512e20db19f6152a4bb634433aa/chart/values.yaml#L1418)
```[tasklist]
### Depends On
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87225
```

**Comment by ph-One** [comment]
Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/87225

**Comment by ph-One** [comment]
This work has been completed. Closing.
