### ISSUE TITLE
Follow up on stale submissions

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#86471]
Since work was done #85842 to surface stale submissions
1. Work with enablement team and VBA to surface what we found
2. Identify if any follow up is needed (on their end or our end)

**Comment by aplatt-coforma** [comment]
Due to eng efforts on [failed submissions](https://github.com/orgs/department-of-veterans-affairs/projects/1278/views/15?sliceBy%5Bvalue%5D=PBP+No+Silent+Failures), we are going to close this ticket for now as won't do.
