### ISSUE TITLE
Add need to update revproxy config even for the VA.gov application generator 

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#86475]
### Description
In [Creating a new application](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application) in the [Manual set up section
](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Manualsetup)there is this step: 
> [Update revproxy config](https://depo-platform-documentation.scrollhelp.site/developer-docs/routing#Routing-ReverseProxyConfig) to reflect the addition of your application so that internal links created via react-router will work properly.

There is not this step in the [Yeoman generator section](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Yeomangenerator) though it is still necessary. Can we add this step to the Yeoman generator section:
> [Update revproxy config](https://depo-platform-documentation.scrollhelp.site/developer-docs/routing#Routing-ReverseProxyConfig) to reflect the addition of your application so that internal links created via react-router will work properly.

### Relevant URLs
Linked above:
- [Creating a new application](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application) 
- [Manual set up section
](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Manualsetup)
- [Yeoman generator section](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Yeomangenerator)
- The docs that should be referenced in the Yeoman generator: Routing - https://depo-platform-documentation.scrollhelp.site/developer-docs/routing#Routing-ReverseProxyConfig

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Benefits Accredited Representative Portal - technically a accredited rep facing team but closest would be a VFS team

**Comment by jknipes** [comment]
Hi @williamphelps13 , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
work being done on this ticket [86534](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86534)

**Comment by laucon** [comment]
@williamphelps13 I'm going to start working on this. I might reach out to you to check if my work looks accurate.

**Comment by laucon** [comment]
This has been completed and is done. :)

**Comment by jknipes** [comment]
@williamphelps13 we are closing this ticket, Thank you!
