### ISSUE TITLE
[FE] Update "How we calculate mileage" Content as Approved by CAIA

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#86481]
## Description
Update the expandable alert content for `How we calculate mileage` 

## Wireframes
[wireframe](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3181-3191&t=xVEXiLDsda1gMEwd-4)

## Tasks
- Update content

**Comment by loripusey** [comment]
@benbrasso-agile6 @cgednalske Do we have an update on whether this has been approved?

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park / @loripusey This is merged in and ready to validate. Can be done locally or with the screenshot below:
<img width="148" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f894469334a01e20df2bd5e84a6bf16defa82421/localhost_3001_my-health_appointment-travel-claim_travel-mileage%20%285%29.png" alt="localhost_3001_my-health_appointment-travel-claim_travel-mileage (5).png" />

**Comment by benbrasso-agile6** [comment]
LGTM
