### ISSUE TITLE
Infra Recommit - Phase 1: Migration of Ops Owned Services

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8649]
## User Story and Problem Statement

As a member of VSP Operations, I need to eat my own dog food by migrating my own services first, so that I can understand the best way to migrate services to the new infra before migrating customer services. 

### High Level Description: 
We will be identifying the services we own (ie rev proxy) and working to migrate those to ECS. We are taking this approach so that we can eat our own dog food and develop patterns for more streamline migrations. This will reduce the amount of breakage and interference on the customers. 

The plan is to spin up the new services in parallel to what we currently have, test, and then gradually turn off the old way. 

### Initiative Outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/infrastructure_recommit/product_outline.md

### The Work
-Coming soon

### Pain Points being addressed:
- Complexity
- Brittleness/older technology
- Lack of self-service on the platform.
- Amount of support due to the complexity
- Lack of confidence due to the current ecosystem

## VSP Objective (Q1 & Q2 2020)
O3: Stability and resiliency of the Platform's systems and teams continue to improve.	

### VSP in O3 2020
 The stability and resiliency of the Platform's systems and teams continue to improve.

## Measuring Success (KRs/KPIs)
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- [VSP KR] Increase in customer NPS
- the feeling of complexity will decrease. 

## We will know we're done when
- All our services are running in ECS successfully and the old services are turned off.

**Comment by jhouse-solvd** [comment]
need to migrate useful and relevant information from this epic into this new, more up-to-date epic: 

https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/14065

**Comment by jhouse-solvd** [comment]
Need to move relevant information from this epic into [this Q4 initiative](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14065) which has been re-framed to more accurately reflect the relevant work to be done surrounding this topic.

**Comment by jhouse-solvd** [comment]
Closing. See [HERE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14065) for more information
