### ISSUE TITLE
SOCKS access for Derek Houck

### ISSUE THREAD

**Issue by derekhouck** [department-of-veterans-affairs/va.gov-team#86495]
### Your Name

Derek Houck

### Your Email

derek.houck@agile6.com

### Your GitHub Handle

derekhouck

### Your Role and Team

Full Stack Engineer on Forms Engine

### Product Manager (PM) name and email

Kara Kemahli (kara@adhocteam.us)

### Product Owner (PO) name and email

Matthew Dingee (matthew.dingee@va.gov)

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILrC6Y2KjqLVmflp7buy9nVi3ssk2KgFqBNc/Z/pbb4Q derekhouck@Derek-Houck.local

### E-QIP Transmittal Confirmation

<img width="1171" alt="Screenshot 2024-06-20 at 2 10 00 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/12766168/fdf5e810-e83c-4963-bf59-fcf6cd09e00e">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@derekhouck - Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
