### ISSUE TITLE
Analytics Implementation or QA Support for IVC Forms - Form 10-10d CHAMPVA Benefits Application

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#86492]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - IVC Forms

- **Poduct Name**

    - Form 10-10d CHAMPVA Benefits Application
      
- **When is the launch date?**
    - July 31 (tentative)

- **Provide the link(s) for Product/Page urls**
  
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/introduction
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-type
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-mailing-address
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-contact-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/signer-relationship
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-identification-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-status
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-status-date
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-status-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-mailing-address
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/sponsor-contact-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-identification-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-mailing-address
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-contact-info
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-relationship
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-marriage
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-marriage-date
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-marriage-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-remarriage
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-remarriage-date
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-remarriage-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-remarriage-separation-date
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-remarriage-separation-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-relationship-child
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-relationship-child-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-dependent-status
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-dependent-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-medicare-upload
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-other-insurance-status
   - va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d/applicant-other-insurance-upload

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

   Standard tracking as described in the GA data dictionary. We'd like to track abandons if possible so that we can understand patterns if users are leaving the form without completing, and I didn't see those specifically called out.

We also assume the user's country will be captured but would like to understand these numbers if not.

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by baltes** [comment]
@johnny-jesensky-adhoc my teammate @marywang2 let me know that these requests may take some time to get to after she submitted one, but hoping for confirmation that this request is received and in your backlog. Thank you!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @baltes -- yes, we've been busy with the GA4 migration, but are hoping to have more bandwidth for this before too long. Confirming the Analytics Team has, and can see this request.

FYI @marywang2, @Blivaditis

**Comment by baltes** [comment]
fysa @pshahVA

**Comment by Blivaditis** [comment]
Hi @baltes the base tracking has been confirmed on each page of the form. Here is a [link](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/nkTrryE3RSunKDaA1fMgqg) to a GA report which shows your form events in staging.

**Comment by pshahVA** [comment]
@Blivaditis , I can't seem to see these events, I'm getting a permission issue.

**Comment by Blivaditis** [comment]
What is your email? Can you include a screen shot of the issue?

**Comment by baltes** [comment]
Seeing the same result for bo.altes@agile6.com

![image](https://github.com/user-attachments/assets/ea7f496f-d9ab-4b3c-8e56-10e57a901e29)

**Comment by Blivaditis** [comment]
Hi @baltes, I gave you permission to the non-production environment, refresh the page and let me know if that works. I can do the same for @pshahVA once I have his email address.
