### ISSUE TITLE
Old browser bug: impact, root cause and solution discovery

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86504]
### User story

As a Cartographer, I want to get to the bottom of why older Safari and Chrome browsers are laying secondary nav out wrong and how to deliver the right layout to those Veterans, so that we can determine a path forward for implementation.

### Notes
- Bug occurs for a total of 12% of VA.gov users between:
  - Safari 17.3 and older - 4%
  - Chrome 122 and older - 8%
  - MS Edge 122 and older - 3.5%
  - Firefox v122(?) and older - <.5%
  - mystery: FF v11.0 - 2.4%, but we can't figure out what this version means (sequence is wrong for iOS or main FF)
- Allan has access to BrowserStack, which is presumably how we will debug what's going on.

Possible tasks:
- 

## Acceptance criteria

- [x] Identified what browser versions have the bug
- [x] Determined why these browsers have the bug
- [ ] Implement a code approach that would render the secondary nav correctly for these versions

**Comment by carlosfelix2** [comment]
This is a browser bug that was fixed in later versions of browsers. It seems to be related to the inheritance of CSS classes in children elements.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified on the latest and several older versions of Chrome, Firefox, Safari and Microsoft Edge that this issue has been fixed

Older versions were tested using Browserstack

Screenshot example below is from Safari 15.6
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83b3dc8c81195b5d304f4a05fc792477c992865f/Screenshot%202024-06-21%20at%2011.56.34%E2%80%AFAM.png" alt="Screenshot 2024-06-21 at 11.56.34 AM.png" />
