### ISSUE TITLE
Midpoint Review - Content Feedback - [Disability Benefits Experience Team 1, Disability Comp Application (21-526 EZ), Submission Experience]

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#86518]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- After reviewing your Figma presentation, I realize you're still working with CAIA to finalize the content language regarding consistency and clarity. Working with CAIA and adhering to the Design System Style Guide is essential to creating quality products that support our Veteran community.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Should:
- Use Plain Language standards (Active vs. Passive Voice: Examples screenshots and Contractions: Don't vs Do not)
- Consistent Language across the Product: What Happens Next? The product design contains 2 sections with different content. I've attached screenshots of the images.
- Notifications and What Happens Next? The language isn't clear, making it difficult for the user to manage their expectations. I've attached screenshot images.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if needed)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

<img width="998" alt="Clarifying language for What happens next?" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/f11fe328-e795-46ed-ae51-9c8208fab475">

![Contraction example](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/10a682be-b743-4e03-9c27-ee8e273b8de3)

![Contraction example 2](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/cdbdbd95-4784-46fb-bd64-d2e59a70b543)

<img width="998" alt="Correct Use of Contraction  Don't" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/2f375b92-fef6-4e30-b22e-d72577e39741">

<img width="998" alt="Use Active vs Passive Voice" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/6f6c8431-e5c6-4abe-bbe1-95e36dae5a18">

![What happens next? Incorrectly worded sentence - Inconsistent with other What happens next? language](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/85bda0fa-5915-4421-abd5-0fb9d5ba3b0c)

**Comment by mengA6** [comment]
@CherylEvans Thank you for providing this promptly.

I've addressed all the feedback that was on screens / emails that are within our scope [in Figma](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/Submission-Experience?node-id=5626-129729&t=O2EGsqpMXmuId7UN-1). Note that some you called out (which are vertically lower on the canvas in Figma) are not within our scope to change for this release.

One question: On 

> Finally, it typically takes up to 3 days for us to receive your claim. 

I'm not sure about using the word "finally" there because that makes it sound like another step that happens after the email when we receive their claim (not the case). Your thoughts?

Also I removed "when you submit your claim" from the suggestion since at this confirmation screen, the Veteran already has submitted their claim.

**Comment by mengA6** [comment]
also with 

> Consistent Language across the Product: What Happens Next? The product design contains 2 sections with markedly different language. I've attached screenshot images.

I'm not sure where this is. Didn't find it in your screenshots or the figma file. If that issue still exists, can you point to where exactly?

**Comment by CherylEvans** [comment]
Mike,
I apologize for not being more clear in the comments on my screenshots.
There are time constraints during the meeting and I didn’t want to take up
too much time in the meeting with my feedback.
I meant that comment as an example of what you might say.
As long as the user understands the content, and it complied with the
design system style guide, it should  be fine.
If you have any more questions or comments, please let me know.
Thanks again,
Cheryl


Cheryl Evans | Senior Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by CherylEvans** [comment]
> also with
> 
> > Consistent Language across the Product: What Happens Next? The product design contains 2 sections with markedly different language. I've attached screenshot images.
> 
> I'm not sure where this is. Didn't find it in your screenshots or the figma file. If that issue still exists, can you point to where exactly?

<img width="998" alt="Clarifying language for What happens next?" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/ed687af7-86db-4dd6-9e02-ca5ada9e9342">

<img width="998" alt="Use Active vs Passive Voice" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98835292/48819825-91f5-4f9b-bee3-50c4a33f9eee">

These are the 2 screenshots containing the differing text in the What happens next? sections.
I realize they are 2 different scenarios, but I would expect the text under the heading to be the same.
I will change all of these to "Should" FB and your team can work with CAIA to determine what language works best. Thank you!

**Comment by mengA6** [comment]
Okay, thanks. I corrected that in figma - standardized on “it typically takes up to 3 days for us to receive your claim.”

I believe I have addressed all of this feedback that is within our scope for this work. 

Also please let me know your thoughts on keeping or eliminating “finally” per https://github.com/department-of-veterans-affairs/va.gov-team/issues/86518#issuecomment-2183375180

**Comment by CherylEvans** [comment]
> @CherylEvans Thank you for providing this promptly.
> 
> I've addressed all the feedback that was on screens / emails that are within our scope [in Figma](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/Submission-Experience?node-id=5626-129729&t=O2EGsqpMXmuId7UN-1). Note that some you called out (which are vertically lower on the canvas in Figma: "The VA claim process after you file your claim" page, My VA, and Claim Status Tool) are not within our scope to change for this release.
> 
> One question: On
> 
> > Finally, it typically takes up to 3 days for us to receive your claim.
> 
> I'm not sure about using the word "finally" there because that makes it sound like another step that happens after the email when we receive their claim (not the case). Your thoughts?
> 
> Also I removed "when you submit your claim" from the suggestion since at this confirmation screen, the Veteran already has submitted their claim.

Good morning! I recommend working with CAIA to fine-tune the language. My only thought was letting the user know that there is another important piece of information to note after the claim is submitted and the user receives the confirmation emails. CAIA is the best resource for you to use while you construct the language. My role is ensuring the adherence to the Design System Style Guide once the language in place. Thanks again for all of your comments and questions regarding my feedback. :-)

**Comment by mengA6** [comment]
Thank you. I removed the "finally" since it wasn't actually a separate step.

As for CAIA, our plan is to bring CAIA in after findings come in from the VFF / My VA research on submission status (per [Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1718992973715589?thread_ts=1718654600.232579&cid=C053UDWMH7U))
