### ISSUE TITLE
10-7959f-1: update copy for phone number screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86512]
As a FMP registrant, I want to understand what my phone number is being used for so that I can enter the right one.

- [Figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=726-22085&t=LVCYNAwKigMwhmFP-0) link
- Make phone number required
- update copy for phone number screen

Acceptance criteria:
  - Given the phone number field is present and the copy is updated
  - When a user tries to submit without entering a phone number
  - Then an error message should appear

**Comment by reiting** [comment]
This is in team review now. <img width="1224" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1NOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73809468666e9922fa3d1ed1ec7bc829cb4b97a1/Screenshot%202024-06-25%20at%209.35.18%E2%80%AFAM.png" alt="Screenshot 2024-06-25 at 9.35.18 AM.png" />

**Comment by reiting** [comment]
Now in platform review.

**Comment by reiting** [comment]
This has been approved and merged and should be in staging in a few hours.

**Comment by reiting** [comment]
@marywang2 this is in staging.

**Comment by marywang2** [comment]
@brian-wilke fyi for review. (This looks good to me so I'm going to close but pls take a look when you get a chance).
