### ISSUE TITLE
Infra Recommit - New Services

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8653]
## User Story and Problem Statement

As a member of the Operations team, we need to set up all the new services in the environments and make sure they are working as intended, so that we can work towards migrating all the services into the new infra.

### High Level Description: 
Depending on the tooling choices this is when we implement any new tools or services we choose. Ie Nomad, Loki, ciricleci, ect 

### Initiative Outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/infrastructure_recommit/product_outline.md

### The Work
-Coming soon

### Pain Points being addressed:
- Complexity
- Older tools

## VSP Objective (Q1 & Q2 2020)
O3: Stability and resiliency of the Platform's systems and teams continue to improve.	

### VSP in O3 2020
 The stability and resiliency of the Platform's systems and teams continue to improve.

## Measuring Success (KRs/KPIs)
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- [VSP KR] Increase in customer NPS
- the feeling of complexity will decrease. 

## We will know we're done when
- VSP Ops team has all the new services in each environment.

**Comment by jhouse-solvd** [comment]
Please see I[nfrastructure Recommit - Migrate 50% of Services to new infrastructure ](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14065) for the most recent incarnation of this effort.
