### ISSUE TITLE
[DevOps] Eric Oliver probably needs to be onboarded onto Venafi

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86536]
## Description
We have some Vista-API certs that expire starting in early November 2024.

## Tasks
- [ ] [DevOps] Is this ePAS? Is this managed through some other method? Find out.
- [ ] [DevOps] Ticket opened wherever necessary to get this onboarding.

**Comment by olivereri** [comment]
Context may be found here:
https://dsva.slack.com/archives/C051S52N1C6/p1719513236185779?thread_ts=1719419190.484539&cid=C051S52N1C6

**Comment by olivereri** [comment]
Jeremy thinks it might be 2253:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/31904439/5f1a2f38-f2e0-4039-8afe-740aedff13a1)

**Comment by olivereri** [comment]
ePAS document for Venafi group 2253 submitted. Applied to  0account

**Comment by olivereri** [comment]
@ndouglas 2253 is the right group. Finally followed up and opened a browser with my zero-account, browsed to vaww.certmgr.va.gov and see the vista-api.va.gov certificates.
