### ISSUE TITLE
Contact Center Review for [Benefits Management Tools - Claim Status Tool: Expanded Claim Phases]

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#86542]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Claim Status Tool: VA.gov product claimants go to get up-to-date information on the status of their claims and appeals. 

### Launch Date
7/30/2024

### Version Number
2.1

### Product Guide
[CST Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/Claim%20Status%20Tool%20Product%20Guide%206.21.24.docx)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @jacobworrell. The last revision of the product guide for the CST dropped in April 2024. At the time, it was labeled as being for the modernized CST and given the 2.0 designation. Should I update the attached with the latest draft you've sent here and call it v2.1?
[VA Claim Status Tool Product Guide v2 SRT 04192024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWlEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54add293593931d61d3b6cabcce7dbcf66380877/VA%20Claim%20Status%20Tool%20Product%20Guide%20v2%20SRT%2004192024.docx)

**Comment by jacobworrell** [comment]
Sure, calling it 2.1 is perfectly fine with me.

From: Steven Tarlow ***@***.***>
Sent: Friday, June 21, 2024 5:44 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: WORRELL, JACOB K. (COFORMA LLC) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Benefits Management Tools - Claim Status Tool: Expanded Claim Phases] (Issue #86542)


Hi @jacobworrell<https://github.com/jacobworrell>. The last revision of the product guide for the CST dropped in April 2024. At the time, it was labeled as being for the modernized CST and given the 2.0 designation. Should I update the attached with the latest draft you've sent here and call it v2.1?
VA Claim Status Tool Product Guide v2 SRT 04192024.docx<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWlEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54add293593931d61d3b6cabcce7dbcf66380877/VA%20Claim%20Status%20Tool%20Product%20Guide%20v2%20SRT%2004192024.docx>

-

**Comment by starlow00** [comment]
Okay, thanks @jacobworrell . So in the draft you've sent me here, can you please point out where the additions are for v2.1?

**Comment by starlow00** [comment]
@jacobworrell The reason I make that request is that if product teams don't make changes/additions to the most recent copy of the guide, things are going to be lost or potentially incorrect. Sorry for not making that clear before.

**Comment by jacobworrell** [comment]
@starlow00 sure, I mention it in the revision history section. The changes are in section 4.5 in the doc. That whole section has been reworked. Those are the only changes

**Comment by starlow00** [comment]
Got it, thanks @jacobworrell !

**Comment by starlow00** [comment]
The draft looks good. Sending to VEO for their review.

**Comment by starlow00** [comment]
There are no changes from VEO. The working copy (v2.1) is attached. Please use it for future revisions/additions. Thank you!
[VA Claim Status Tool Product Guide v2.1 SRT 06262024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHVhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b7f950611c12d88b151dda1026bb94f3630e665/VA%20Claim%20Status%20Tool%20Product%20Guide%20v2.1%20SRT%2006262024.docx)
