### ISSUE TITLE
High error Sentry Alert Faraday::TimeoutError: Net::ReadTimeout with #<TCPSocket:(closed)> (Faraday::TimeoutError)

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#86562]
Hi Benefits-Claims team.

I am performing some monitoring of high error sentry alerts and I came across this alert. https://sentry.vfs.va.gov/organizations/vsp/issues/249323/?project=3&project=4&statsPeriod=7d

The team on the alert is benefits-claims-appeal-status. Can you please take a look at this alert and determine if there is any action that needs to be taken. If possible, this may be a good time to move this alert to DataDog, if its not already monitored there.

Appears there's been a large uptick in errors starting June 12th.

**Comment by bdech** [comment]
@shaunburdick I've assigned this to you because I seen you're a participant on the alert. Please feel free to re-assign if you and your team are not the proper folks to investigate this alert.

**Comment by alyssagallion** [comment]
Removing our label since our portion is complete. Thanks! 

CC: @bdech @shaunburdick
