### ISSUE TITLE
Infra Recommit - Phase 2: Migrate Remaining Services

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8656]
## User Story and Problem Statement

As a member of the Operations team, we need to migrate all the services from the old infra into the new,  so that we can start using the new Infra.

### High Level Description: 
All the services in the old infra will need to be migrated over one at a time and work with each team that owns them so they have a smooth transition.

We need to identify ownership of these other services and work closely with them to make the switch. This will take a similar approach to phase 1, running the current service and bring up the new service in parallel.  

### Initiative Outline:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/infrastructure_recommit/product_outline.md

### Rollout Plan
- Coming soon

### The Work
- Coming soon

### Pain Points being addressed:
- Complexity
- Brittleness/older technology
- Lack of self-service on the platform.
- Amount of support due to the complexity
- Lack of confidence due to the current ecosystem

## VSP Objective (Q1 & Q2 2020)
O3: Stability and resiliency of the Platform's systems and teams continue to improve.	

### VSP in O3 2020
 The stability and resiliency of the Platform's systems and teams continue to improve.

## Measuring Success (KRs/KPIs)
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- [VSP KR] Increase in customer NPS
- the feeling of complexity will decrease. 

## We will know we're done when
- All the services are migrated and the old services are taken down.

**Comment by jhouse-solvd** [comment]
need to migrate useful and relevant information from this epic into this new, more up-to-date epic: 

https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/14065

**Comment by jhouse-solvd** [comment]
Need to move relevant information from this epic into [this Q4 initiative](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14065) which has been re-framed to more accurately reflect the relevant work to be done surrounding this topic.

**Comment by jhouse-solvd** [comment]
Closing. See []([HERE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14065)) for more information
