### ISSUE TITLE
Analytics New KPI dashboard request & KPI dashboard update request for [Disability Experience - 526 Flow]

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#86588]
# Request a New Standardized KPI Dashboard or an Update to an Existing Dashboard
## What this form is for

Use this ticket template to request a new standardized KPI dashboard or an update to an existing KPI dashboard on Domo for your product. 

**Tell us what you need done:**
- [ ] [New Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-new-dashboards)
- [x] [Updates to Existing Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-updates-to-existing-dashboards)

Standardized dashboards are currently available for [Forms](https://va-gov.domo.com/page/447193050?userId=853813555), [Content](https://va-gov.domo.com/page/426422632), & [Search](https://va-gov.domo.com/page/1964748112) products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## For New Dashboards

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

## For Updates to Existing Dashboards 

First, tell us what type of change you need to make:

- [ ] Change basic product info
- [x] **Forms**: funnel changes
- [x] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

**If you cannot locate your original worksheet you can create a new one:**
- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

**Additional Info For Both Options**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by pacerwow** [comment]
Here is the spreadsheet we used before that we've updated. The V3 Funnel tab is new, as is the Toxic Exposure tab, and we've updated the 526 tab to include the Toxic Exposure page url.
https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/

Here's the old ticket we used to create the dashboard request:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/62575

**Comment by johnny-jesensky-adhoc** [comment]
Hi @pacerwow, thanks for submitting this. Confirming we have recieved this request. We'll let you know once we've pulled this ticket into a sprint to work on.

FYI @Blivaditis

**Comment by pacerwow** [comment]
Thanks @johnny-jesensky-adhoc. Curious if you think this might be complete before Aug 1, 2024? We're planning a release around that time and having updated metrics would be useful for us to determine success during the staged rollout. Let me know if not, so I can set expectations please. Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @pacerwow  -- I've gone ahead and moved this into our _**On Deck**_ column. In regards to timing, our next sprint starts on Thursday, Aug 1, and runs through Aug 14th, so somewhere within that timeframe be the earliest we could get to this. 

Note, that once these pages are live, we'll also be able to view metrics on these pages directly in Google Analytics 4 (GA4). I went ahead and made a [basic Explore report](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/g5A9I3SfQTGsEbgzUedY7Q) for _Views_ of some of the Toxic Exposure Staging URLs in our Non-Production GA4 Property that might help give you an idea of what this might look like.

Depending on the _exact_ timing of our Domo report updates, this could be something to give y'all an early look into the traffic on those links.

![image](https://github.com/user-attachments/assets/0a6838be-279c-4f62-b3a0-c39d3051510b)
 
FYI @Blivaditis, @ChristineYoungZA

**Comment by Blivaditis** [comment]
@dorseypa1 here is the [BQ template link](https://docs.google.com/spreadsheets/d/14Sty-LiDlNOZyl0wUZGKoA3j86VE1gmnoFiaOrQYU60/edit?gid=1184161360#gid=1184161360).

**Comment by pacerwow** [comment]
Hi @dorseypa1 and @johnny-jesensky-adhoc curious if you have an update on timing for this. We're planning to begin moderated production testing this Friday. Thanks!

**Comment by Blivaditis** [comment]
The load has been updated, will verify once results are appearing in the Forms dashboard.

**Comment by johnny-jesensky-adhoc** [comment]
Great -- moving this to _**Done**_.

@Blivaditis, @ChristineYoungZA  -- leaving this as a note to verify the fix next week after the dataset has been refreshed.

**Comment by johnny-jesensky-adhoc** [comment]
@Blivaditis, @ChristineYoungZA -- can one of y'all please verify this update went through in Domo?

**Comment by pacerwow** [comment]
Hey, just wanted to ask if this was working. The GA funnel we're using doesn't display the TE pages
https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/BtqeUqzLR3y7cFsUETgZwQ
