### ISSUE TITLE
Discovery: Cleanup and move other resources from `dsva-vetsgov-${environment}`to `dsva-vagov-${environment}`

### ISSUE THREAD

**Issue by benniemosher** [department-of-veterans-affairs/va.gov-team#8661]
Work with @wyattwalter to determine what resources can be deleted, and what resources should be moved. Report back to this ticket with a list for completion.

**Comment by wyattwalter** [comment]
## dsva-vetsgov-dev

cms-peering is needed for SOCKS access to CMS stuff — doesn't migrate either

VPC stuff don't touch as well

security groups: 
- revproxy, vets-api, Prometheus, GIDS all moved to vagov
- Redis for vets-api is still in progress of moving (dsva-vetsgov-dev-redis-sg)
- check in w/ Charley on api-usage-reporter-lambda-sg, dsva-vetsgov-dev-developer-portal-lambda-sg stuff
- review instances moved to staging
- GIDS == gi-bill-data-service, some things used the name gibct
- appserver == vets-api + GIDS
- jumpboxes need to stay
- NAT need to stay
- delete scratch stuff
- Don't need Nessus module thing at the end
- dsva-vetsgov-dev-prometheus-node-exporter-sg needs to stay

Cloudwatch
- only thing that needs to stay is the flowlog thing at the end

Main
- check all the `data` blocks to make sure they're used
- need jumpbox stuff still
- don't need prometheus network interface or role
- don't need revproxy role
- prometheus assume role stuff for CMS account will be kind of special
- SSM stays, scratch can go
- Elasticache stays for now
- developer portal - check w/ Charley

**Comment by benniemosher** [comment]
cms-peering is needed for SOCKS access to CMS stuff — doesn't migrate either

VPC stuff don't touch as well

security groups:

- [ ] revproxy, vets-api, Prometheus, GIDS all moved to vagov
- [ ] Redis for vets-api is still in progress of moving (dsva-vetsgov-dev-redis-sg)
- [ ] check in w/ Charley on api-usage-reporter-lambda-sg, dsva-vetsgov-dev-developer-portal-lambda-sg stuff
- [ ] review instances moved to staging
- [ ] GIDS == gi-bill-data-service, some things used the name gibct
- [ ] appserver == vets-api + GIDS
- [ ] jumpboxes need to stay
- [ ] NAT need to stay
- [ ] delete scratch stuff
- [ ] Don't need Nessus module thing at the end
- [ ] dsva-vetsgov-dev-prometheus-node-exporter-sg needs to stay

Cloudwatch

- [ ] only thing that needs to stay is the flowlog thing at the end

Main

- [ ] check all the data blocks to make sure they're used
- [ ] need jumpbox stuff still
- [ ] don't need prometheus network interface or role
- [ ] don't need revproxy role
- [ ] prometheus assume role stuff for CMS account will be kind of special
- [ ] SSM stays, scratch can go
- [ ] Elasticache stays for now
- [ ] developer portal - check w/ Charley

**Comment by wyattwalter** [comment]
I see some stuff PRs got linked to this ticket, but I think the discovery aspect of this is done. A bunch of work is getting linked to https://github.com/department-of-veterans-affairs/va.gov-team/issues/8662 now, so I'm going to close this one off.
