### ISSUE TITLE
Accesssibility Review Request for PDF Formatting for Rates Pages for 508 Compliance

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8664]
Accessibility Request for PDF formatting

**The ask**
Please review these PDFs for accessibility, 508 concerns.
If these PDFs were linked to from va.gov, are there issues with their current formatting/content?

PDFs to Review
[disability-rates-2017](https://app.zenhub.com/files/133843125/325aadc3-fb74-4128-a759-de89e2217f81/download)
[disability-rates-2018](https://app.zenhub.com/files/133843125/42ded996-9f0c-4866-92a5-5a9c19df3cf2/download)
[disability-rates-special-monthly-compensation-2017](https://app.zenhub.com/files/133843125/b53f696a-9524-4a36-b847-25e692afe142/download)
[disability-rates-special-monthly-compensation-2018](https://app.zenhub.com/files/133843125/8efe3d3e-b18d-486c-91f2-df7706886ea5/download)
[disability-rates-special-benefits-2017](https://app.zenhub.com/files/133843125/3b264ce6-c962-40d7-9f2f-ca03fda4f864/download)
[disability-rates-special-benefits-2018](https://app.zenhub.com/files/133843125/c6b0fa1b-885a-4409-882a-e7b36dad9522/download)
[disability-benefits-birth-defects-2017](https://app.zenhub.com/files/133843125/118459e2-83c4-4407-b641-abb39b8ef680/download)
[disability-rates-birth-defects-2018](https://app.zenhub.com/files/133843125/fb9de85d-f33a-4eff-b6bd-d680636f378c/download)
[pensions pdf](https://app.zenhub.com/files/133843125/657e4303-2698-4a88-be10-a440fe1ed7b1/download)

*New*
In trying to trim down/out the erroneous clicks and links, a PW team member created a PDF based on the content of the tables. Would you mind reviewing this as well for feedback? This was not time intensive and, if we could get this to work, would be something we can recreate & review for others.
[Veterans.Compensation.Benefits.Rate.Tables.-.Effective.12116.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4576901/Veterans.Compensation.Benefits.Rate.Tables.-.Effective.12116.pdf)

**The situation**
We are in the process of placing redirects to some legacy rates pages, so that they redirect to current pages now hosted in Drupal. There are several years of historic rates on the legacy site, but we have made a decision to focus on the last few years to keep the scope manageable. 
The largest set is the Disability Rates pages.
Ex: https://www.va.gov/disability/compensation-rates/veteran-rates/

If you scroll to the bottom of the page, you will see "Historic Rates" followed by 3 links, to 3 different years. 
![image.png](https://images.zenhubusercontent.com/5e8e2c558120a9afb708b413/cdea86cc-af64-4371-8d1f-702bf6b01a60)

The most recent historic year is already hosted on Drupal, so there is nothing to do for this.
The next two years are currently linking to legacy pages. Our plan is to update those links to point to PDF versions of the legacy pages. Examples provided above

**Questions that have come up**
1. Are there general accessibility issues with the PDFs?
2. There is a section on the PDFs for additional Historic Years- and there are several years listed. 
- We can attempt to remove them from the PDFs, but we have found that different Rates pages have listed the Historic Years at the top of the page, which may be more difficult to remove for a PDF vs removing it from the bottom
- If we leave this section, is there an issue if the links do not work as expected? Should we disable them? 
- If the links are still functional, they will wind up taking the user back to the new, Drupal-hosted, rates page and not a page on the legacy site (due to redirects that will be implemented)

**Comment by stephorkandatx** [comment]
@jenstrickland this may be a good topic for us on our Monday meeting. I am not sure how best to enlist your help with this request, so as we work through how to submit other requests let's see how best to approach this.

The situation is a bit confusing (redirects, PDFs, legacy and current pages) so I've provided details on what is going on. Again, it may be easiest to talk and walk through what we are trying to do and how we can make sure we create content that is accessible. Thank you in advance.

**Comment by jenstrickland** [comment]
@stephorkandatx The two PDF links above take me to errors that look like this:

![Screen Shot 2020-05-04 at 10 22 37 AM](https://user-images.githubusercontent.com/57469/80976256-35f36600-8df1-11ea-8b43-237b8eb8cb8a.png)

Do I have to be in the VA environment to access them, or might they have been moved?

**Comment by stephorkandatx** [comment]
@jenstrickland Sorry about that! I have updated the links + included all the PDFs that would need review.

**Comment by stephorkandatx** [comment]
@jenstrickland I added another PDF, under "New" in the description with a quick explanation. It looks cleaner and is something we can create for the other rates. Would love your thoughts and feedback

**Comment by jenstrickland** [comment]
There are a too many accessibility issues in these PDFs to list here. 

I'd like to propose we have a meeting to:
    1. Watch how to evaluate the accessibility of a PDF
    1. Observe what is required to remediate

This may provide the information to help stakeholders understand why the PDF solution is unlikely to be tenable. The current plan will be very, very costly.

**Comment by stephorkandatx** [comment]
@jenstrickland I will set up a meeting shortly. Thank you for the time in reviewing the PDFs, I look forward to learning more

**Comment by stephorkandatx** [comment]
Going to close this out - we met, we reviewed findings, we discussed concerns, we showed what needs to happen to make PDFs accessible. I will let you know if we need a follow-up training or have any more questions. Thank you for your time!
