### ISSUE TITLE
SOCKS access for Efegbare Efenedo

### ISSUE THREAD

**Issue by Efe-Oddball** [department-of-veterans-affairs/va.gov-team#86681]
### Your Name

Efegbare Efenedo

### Your Email

efe.efenedo@oddball.io

### Your GitHub Handle

Efe-Oddball

### Your Role and Team

DevOps Engineer

### Product Manager (PM) name and email

Kyle Flores "kyle.flores@adhocteam.us"

### Product Owner (PO) name and email

Aparna Nittala "Aparna.Nittala@omb.eop.gov"

### Access Type Requesting

automation

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDfe/2psHDpiaZ4+A3iLdA8r8j4f7/KQPOZGGca43iv5edPkxWENR/fLhgjuuXb2njEodwPDbsBI88Rb7KzaP3EeXoxmaQdBqgoKy9hY/AgOGG/sX8BoPcpm0j1I8dtaVhF8MZH2iGOC3x3c+d9ZeJ1JI3E65n8xhWi+7imYpQw9tpm6xgtmS0mvLfivDxT402vqwqy3gbrhabce5fSuEx4y+Q0dl/LxwSHWJqYJmsFBh+fEw3edSelGiqLMSU6TPM4MBT8lojvBB/OD6RaUnoJ7xTU4G3G66nYUF3zafnJWZFRlv+APjQtM/iPZIGdau92lr6OAlktaUw10VyMhjvbvvq1Kz87B9zG6FU0QhIBw7Urv5Sk+nztyVE1xwRueQZZ/X7U8P1CCGn1F62NQj/CQmWkYh0fIHnF0HI6h84HUDDiJQJJyow1kA8XaAcMQYizGIJD4IL8JRaUM8GW4P0VSvoamVhbE73+mD4o7izq+u8USGVYxWbuzbR7uVH3aV8= ubuntu-22@DESKTOP-K8PHPPT

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117599248/3d2c0eb1-b403-4866-90f9-8ee8eee14138)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
Efe confirmed directly that he was now able to connect - Closing
