### ISSUE TITLE
Update Email Address on VA.gov for VIC

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8672]
Request came in via email--

We need to update the email address used on VA.gov, for VIC. A change took place yesterday and now anyone who emails the old email address, will get an 'undelivered' message. 

 Currently, it shows “email us at vic@va.gov” and we need to change the email address to vetidcard@va.gov

**Task**
Update the email address from vic@va.gov to vetidcard@va.gov
On https://www.va.gov/records/get-veteran-id-cards/vic/
Note: there are two sections on this page: 
Replace your Veteran ID Card if it gets lost or stolen
Get help with your application

**Comment by stephorkandatx** [comment]
@jenniferlee-dsva FYSA ticket to log that we are making this change

**Comment by RLHecht** [comment]
This change was made. Will move to validate and close once I see the new email on the live site.

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket.
