### ISSUE TITLE
Update how to set up SiP page (My VA section)

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#86759]
### Description

Authenticated Experience - My VA team has been working on implementing an improved method of configuring SiP forms to display under our Benefit application drafts section. With these new changes, we wanted to update the Platform documentation to communicate these changes for new teams. Let me know if this is the correct way to submit documentation changes!

We'd like to replace the content in the following screenshot to the proposed changes below:

**Current**
![Screenshot 2024-06-24 at 2 39 22 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/316b86d6-da80-480c-a7a2-100636a2ede9) 

**Proposed changes**

As of May 17th, 2024, the My VA team implemented an improved method of setting up save-in-progress forms.

Note: this work is still behind the [`my_va_enable_new_sip_config` feature flag](https://staging-api.va.gov/flipper/features/my_va_enable_new_sip_config).

**Instructions for teams:**

1. Add the **form ID** to the `VA_FORM_IDS` object in the [/platform/forms/constants file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L3)
2. Add the URL path of form to [`getAllFormLinks` function](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L164)
   - property name imported from the `VA_FORM_IDS` object with a value that calls the function `getAppUrl`. The parameter passed to `getAppUrl` is the `entryName` of the application specified in the [registry.json file in the content-build repository](https://github.com/department-of-veterans-affairs/content-build/blob/8fd8cb2592dde48f90c7573cad222cf45b4fcb64/src/applications/registry.json#L207)
3. Add the following information to the `MY_VA_SIP_FORMS` array of objects:
   1. `id`: property name imported from the `VA_FORM_IDS` object
   2. `benefit`: common name of form
   3. `title`: common name of form (with form ID)
   4. `description`: description of form
   5. `trackingPrefix`: unique abbreviation for analytics

**Example:**

If we needed Form 526-EZ to display on My VA under the Benefit application drafts section, we would need to add the following:

```
export const VA_FORM_IDS = Object.freeze({
  ...
  FORM_21_526EZ: '21-526EZ',
});

export const getAllFormLinks = getAppUrlImpl => {
  ...
  return {
    ...
    [VA_FORM_IDS.FORM_21_526EZ]: `${getAppUrlImpl('526EZ-all-claims')}/`,
  }
};

export const MY_VA_SIP_FORMS = [
  ...
  {
    id: VA_FORM_IDS.FORM_21_526EZ,
    benefit: 'disability compensation',
    title: 'disability compensation (21-526EZ)',
    description: 'disability compensation application (21-526EZ)',
    trackingPrefix: 'disability-526EZ-',
  },
];
```

---

### Relevant URLs

- Current page: https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-MyVAPage
- Implementation ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80036

### Which type of team are you on? (Platform team, VFS team, or Leadership)
My VA

**Comment by laucon** [comment]
@allisonlu I updated the document accordingly. The edits should be deployed at 3:30pm ET today. Thanks for giving us these edits. :)

**Comment by laucon** [comment]
The document has now been updated. :)

**Comment by allisonlu** [comment]
thank you @laucon! can confirm that changes look good on the Platform docs

**Comment by jknipes** [comment]
Closing this issue as _Done_
