### ISSUE TITLE
10-7959a: signer information

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86764]
As a VA.gov user, I want to fill out the CHAMPVA claim form with my (or the beneficiary's) information so that I can file a claim.

_**(Note: this section is final except for relationship screen)**_
~~[Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=961-139667&t=Ko13IszQmJiM9ZRY-0)~~ -> [Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1481-276887&t=LG8dR86iRSeFHJg4-11) (updated Jul 8)

- Page elements:
  - breadcrumb 
  - header and subhead
  - copy
  - footer
- Your information
- if not beneficiary
  - name
  - mailing address
  - contact info
  - relationship 
    - if relationship is not listed, then user can fill in open text field 
 - if beneficiary, then user goes to sponsor section

Acceptance criteria:

- Given the user is on VA.gov and about to fill out the CHAMPVA claim form
- When the user gets to the signer info page
- Then the user can fill out their information

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30729) (see screenshots on Github PR) - still waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 @syd-hoeper this has been merged and should be visible on staging shortly. Thanks!

**Comment by marywang2** [comment]
@michaelclement 
- when user is the beneficiary:
  - change "you're" to "the beneficiary", add period at end of sentence.
- when user is not the beneficiary: 
  - add period at end of sentence
  
cc @syd-hoeper for awareness.

**Comment by michaelclement** [comment]
The above changes have been implemented in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30828). Currently waiting on:

- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 @syd-hoeper Latest changes have been merged in and should be visible on staging shortly. Thanks!
