### ISSUE TITLE
Task Card Updates

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#86785]
## Tasks
- Review [CC task card UI](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1966-15111&t=LCu6HynSx7l1uQBW-1) - Coded as H2 and styled as Body
- Evaluate how to represent multiple appointments
- Update pattern for Check-in & Pre-Check-in New Landing Page in [Task Card UI updates feature page](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1677-78997&t=G6uK4D98KULzSaqr-1)
- One approved/confirmed, move page into "Waiting to be released section"

Example of possible multiple appointments approach:
<img width="341" alt="Screenshot 2024-06-24 at 1 35 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/7a286fcb-963d-434e-ae7e-4cc4b402777b">

**Comment by benbrasso-agile6** [comment]
@zach-park added comment for you in Figma

**Comment by zach-park** [comment]
@brianseek @wullaski @loripusey (cc: @benbrasso-agile6 @cgednalske ), validated and ready for engineering team. 
https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1677-78997&t=KO5BVE4JLqycu1cT-1

**Comment by benbrasso-agile6** [comment]
GTG here
