### ISSUE TITLE
Design feedback - 1010CG form

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/va.gov-team#8679]
Do: Mandatory feedback
Try: Exploratory next step
Consider: Sharing ideas/alternate ways of thinking

Do: 
- On this page, there is a lot of padding around the primary buttons. Reduce padding to 16px around the button label. Same for the “Print his page” button at the end of the application
- For all pages with back and continue buttons, Change the gray arrows in the “Back” button to blue 
- If we will have multiple CTA buttons on a page, change to blue instead of green (specifically on the form intro page with subway map)

Try:
_No **Try** feedback at this time._

Consider:
- On this page and on this page, instead of hiding the info in the “Learn more about what this means” in a modal, you could include this info under the additional info component instead. We’ve tested “learn more” information in modals and it’s not an optimal experience for those using assistive technology. 

Definition of Done:
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)
- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by jonathanjnelson** [comment]
Thank you for all your feedback! 

- Updated padding around the primary buttons on "intro page" and "print page" 

- Updated back button with blue arrows 

- Changed CTA buttons to blue 

You can see prototype here: 

https://vsateams.invisionapp.com/share/9XWSQZ6SMG5

Please note: We are pushing for alternatives for the modal as we understand it is problematic
