### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#86796]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
https://github.com/department-of-veterans-affairs/component-library/pull/1202
https://github.com/department-of-veterans-affairs/vets-website/actions/runs/9652631669

## Active Daily Users Impacted

The extra padding impacts all users of tier 2 sites such as the [NCA site](https://www.cem.va.gov/) where the problem was first reported.

## Has fix been confirmed in Staging?
- [] Yes
- [x] No

It's only impacting Teamsites which we cannot properly test in Staging.

## Description

A CSS change to va-alert somehow leaked into main.css via the injected header impacting all paragraph tags on tier 2 sites (i.e. unmodernized parts of VA.gov). This causes extra padding top and bottom of 1em.
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

This issue was escalated to Charles and both Sitewide and Design System teams were tasked with figuring out a solution. The solution was not identified before the 2pm cut off. Due to the widespread nature of the problem and the user visibility of the problem we decided an OOB deployment was necessary.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [ ] PagerDuty OOB Deploy Incident Opened
 - [ ] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [ ] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by micahchiang** [comment]
Closing. This has been addressed and a postmortem has been filed [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2024/2024-06-27-component-library-styles-bled-into-teamsites.md). Follow on work for the injected header has removed the dependency that initially caused this.
