### ISSUE TITLE
Flipper UI access for [Fatma Khan]

### ISSUE THREAD

**Issue by fatmakhan0395** [department-of-veterans-affairs/va.gov-team#86808]
### Your Name

Fatma Khan

### Your GitHub handle (Flipper UI access is managed through GitHub)

fatmakhan0395

### Team, Role, and Company of the target individual

VFEP, React developer 

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Hi, I'm from VFEP team and I would like to request access to Flipper.

**Comment by bdech** [comment]
Hi @fatmakhan0395, can you please provide a screenshot of your E-QIP transmittal, or some form of favorable adjudication?

**Comment by fatmakhan0395** [comment]
Hi @bdech, attaching screenshot here. 
![screenshot_1](https://github.com/department-of-veterans-affairs/va.gov-team/assets/145523589/86ae0faa-f6ed-48fc-aa2f-e47cf8be88a9)

**Comment by bdech** [comment]
Hi @fatmakhan0395, have you filled out your e-qip questionnaire? The E-QIP transmittal looks similar to the image I attached.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/fa345c1f-5ed7-432a-9ac6-b78e53cde0b7)

**Comment by fatmakhan0395** [comment]
here @bdech 
<img width="809" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/145523589/941ddf20-a20e-4638-9c86-88efecdd30ce">

**Comment by bdech** [comment]
Found in Atlas
E-QIP confirmed

**Comment by bdech** [comment]
@fatmakhan0395 You've been granted access to `production` and `lesser` environments.
