### ISSUE TITLE
Update the +more link to a secondary button (VA direct and request flow) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#86803]
## Description
Based on the midpoint review for Community Care Direct Scheduling, there was a callout that we will need to update the [+more]() to a secondary button for the Locations page (direct schedule flow/VA request flow)

<img width="521" alt="Screenshot 2024-06-26 at 9 38 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/10900b33-c8e1-420a-a2d0-f2c5c2507697">

---

## Acceptance Criteria

- [ ] Given when the user is on the direct schedule workflow (all type of cares except for COVID-19 appointment) 
       When the user lands on the Facilities page and has more than 5 facilities listed
       Then the secondary button will be displayed `Show X locations`
       And page design matches the [design spec](https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=PGFtqkMezFxltI29-0l)

- [ ] Given when the user is on the direct schedule workflow for COVID-19 appointment 
       When the user lands on the Facilities page and has more than 5 facilities listed
       Then the seconday button will be displayed `Show X locations`
       And page design matches the [design spec](https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=PGFtqkMezFxltI29-0)

- [ ] Given when the user is on the VA request schedule workflow (all type of cares) 
       When the user lands on the Facilities page and has more than 5 facilities listed
       Then the secondary button will be displayed `Show X locations`
       And page design matches the [design spec](https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=PGFtqkMezFxltI29-0)

### Design Assets
[Design spec]((https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=PGFtqkMezFxltI29-0)
<img width="326" alt="Screenshot 2024-06-26 at 9 34 05 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/37e58db0-3b16-4ca8-81a9-b612000edc89">

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated in staging for Judy Morrison. UX team <img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c2207c245e30712a5e59251110c68d259b15aaa/Screenshot%202024-07-09%20at%2010.01.04%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 10.01.04 AM.png" />
will do a second check as well.

**Comment by melissa-lefevre** [comment]
Look good to me <img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3JHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d628721ea448bd214a74b97c22c2e82de68ec20e/Screenshot%202024-07-09%20at%2012.39.20%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 12.39.20 PM.png" />

**Comment by ldelacosta** [comment]
No issues to report. Closing it out. cc: @JRRoof @Bren22va
