### ISSUE TITLE
Add paragraph above form upload download link

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#86813]

**Comment by Thrillberg** [comment]
[Uploading... image.png]

**Comment by rachelshearerux** [comment]
LGTM!
<img width="780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f90bfa7cf01821a22ff79ae112b11262382ce6f8/Screenshot%202024-07-16%20at%201.09.20%E2%80%AFPM.png" alt="Screenshot 2024-07-16 at 1.09.20 PM.png" />
