### ISSUE TITLE
Site Map - Broken Links

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#8681]
## What happened?
_As a user, when I click on some of the links on the VA.gov site map [https://www.va.gov/site_map.htm](url) I get 404 pages. These include, just as an example:

- Aquisitions [https://www.va.gov/oamm/oa/dbwva/](url)
- Benefits Information [https://www.vba.va.gov/VBA/](url)
- Budget [http://www4.va.gov/budget/products.asp](url)
- Burial Flags [https://www.cem.va.gov/bbene/bflags.asp](url)

## Specs:
- Device: PowerMac
- Browser: Chrome OS Version 81.0.4044.122, Firefox 75, 
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: Navigate to https://www.va.gov/site_map.htm and click on the specified links
- Test User _(if applicable)_:

## Desired behavior
_All links on the page should go to the intended page_. 

## Acceptance Criteria
- [ ] _When I user clicks on a link on the VA.gov sitemap, the links should route to the expected page_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**
<img width="549" alt="Screen Shot 2020-05-03 at 1 44 35 PM" src="https://user-images.githubusercontent.com/63107147/80921670-b0ff4280-8d45-11ea-8c53-ac0cd1ebdb41.png">

**Comment by ncksllvn** [comment]
This sitemap is a good find! However, it's actually not _our_ sitemap. That's a sitemap from TeamSite that appears to have been written manually. Our sitemap is here - https://www.va.gov/sitemap.xml. It's raw data (XML) for search engines to consume as opposed to a use-facing sitemap. I'm not a sitemap expert though. Google has some more info - https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190

**Comment by johnhashva** [comment]
Talked to @mnorthuis  and Jen about this and have sent a note to Josh Tuscher at OPIA to take see if he can make updates -- correcting/updating broken links.  Mikki is going to put the possibility of creating a new HTML site map on her "to do" list. @stephorkandatx let me know if we should close this one out.
