### ISSUE TITLE
[UX/BE] 10-10EZR TERA: Discovery -- Can we pre-populate/display TERA answers/eligibility?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#86815]
As a Veteran, I would like to know if I have answered the TERA questions and they have been recieved and processed by VA so that I don't have to answer them again.

- [x] Work with VES to determine what, if any, TERA info we can get back on the Veteran (and how complete that info is)
- [x] Determine where these answers/eligibility would come from (online EZ, online EZR, paper EZ, paper EZR, VistA, Cerner/Oracle Health, etc.)
- [x] **Success: We have determined if we can display TERA answers/eligibility.*

**Comment by JoshingYou1** [comment]
According to Josh Faulkner, we are not currently able to pull any previously submitted TERA answers. However, we can access a boolean field called `toxicExposureRiskActivityInd` that will tell us if a Veteran is eligible for TERA. To be clear, this field can be true even before a Veteran submits an EZ or EZR. Links to the conversations:

Original: https://dsva.slack.com/archives/C06FDF2EN0H/p1716563549828229
Follow-up/confirmation: https://dsva.slack.com/archives/C06FDF2EN0H/p1719846573526389
