### ISSUE TITLE
Staging Review finding: Content doesn't align with DSSG regarding active vs passive voice and requires a clarifying adjective for user comprehension.

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#86826]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** VYE Team
**Product:** Verify Your Enrollment
**Feature:** Verify Your Enrollment

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not align with VA.gov voice and tone content principles.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-aligns-with-vagov-voice-and-tone-content-principles)
**VA.gov Experience Standard - category:** [Credibility](https://design.va.gov/about/experience-standards/#category-credibility)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @CherylEvans (Content)

### Description

Montgomery GI Bill enrollment verification: Your monthly enrollment verifications: 

"Verifications are processed on the business day after submission."

"Payment is projected to be processed within 4 to 6 business days."

## Recommended action

I recommend using active voice:

"We will process your verification the next business day after submission." 

"We will process your payment within 4 to 6 business days."

Per the DSSG: Use active voice: "Always connect an action to a subject. If no subject takes responsibility for the verb, it’s likely passive voice."

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Plain language - Use active voice](https://design.va.gov/content-style-guide/plain-language/use-active-voice)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by alexisbetz** [comment]
Merged to prod on 11/5/24
