### ISSUE TITLE
Broken Breadcrumb on staging - "health care"

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8683]
## What happened?
This was reported in VFS-Platform-Support channel on May 4, 2020. 

Lenae Storey says that they have noticed a broken link in a breadcrumb on staging. 

* schedule-view-va-appointments page

When clicking on "Health Care" in the breadcrumb on staging, it goes to "sorry can't be found" page.

## Specs:
- Device: (e.g. iPhone 8, Macbook) Desktop, Windows
- Browser: (e.g. Firefox, IE 11) Chrome, IE 22
- Test User _(if applicable)_: n/a

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/schedule-view-va-appointments/
- Click "Health Care" in breadcrumb
- Observed: page cannot be found
- Expected: page contains health care content, as seen on https://www.va.gov/health-care/

## Desired behavior
This appears to be a situation with the breadcrumb or page on staging only. Production version of this experience is find

## Acceptance Criteria
- [ ] Breadcrumb works on staging

**Comment by ncksllvn** [comment]
This is related to some CMS work "behat" testing -  https://dsva.slack.com/archives/CDHBKAL9W/p1584629696241100

**Comment by stephorkandatx** [comment]
I am closing this, Kevin Walsh on CMS team is tracking this issue forward
