### ISSUE TITLE
Staging Review finding: Radio button is not rendered via a Design System Web Component

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#86831]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** VYE Team
**Product:** Verify Your Enrollment
**Feature:** Verify Your Enrollment

## Findings details
**VA.gov Experience Standard - issue:** [User encounters a component or pattern that isn't considered a best practice.](https://design.va.gov/about/experience-standards/#user-encounters-components-and-patterns-that-meet-best-practices)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @it-harrison (QA)

### Description

If a user updates an address on [benefits-profile](https://staging.va.gov/education/verify-school-enrollment/mgib-enrollments/benefits-profile/) the confirmation page uses a radio button that is not rendered with a Design System Web Component. 

## Recommended action

Use a Design System web component. In this case, you may wish to use a va-checkbox if there is to be only one option listed.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Radio button ](https://design.va.gov/components/form/radio-button)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by shiragoodman** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/d260562c-33b8-4a72-9d8a-d2e58cf599f8)

**Comment by wafimohamed** [comment]
removed Radio Button when there is no suggested Address
https://github.com/department-of-veterans-affairs/vets-website/pull/30537
