### ISSUE TITLE
Spike: Research load testing patterns

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#86866]
Investigate load testing patterns already in place and see what we might implement.

Acceptance criteria
- References to other implementations are linked in this ticket
- A recommendation is brought to the team for what we should do to cover load testing needs
- Recommendation is documented so that it can be shared with others

**Comment by cloudmagic80** [comment]
https://depo-platform-documentation.scrollhelp.site/developer-docs/load-tests

Load Testing Tools:

Our load testing arsenal includes two primary tools: Locust and wrk2.

Locust:

Strengths:
Easy to define test behavior with Python code.
Interactive testing through a web interface.
Creates swarms of test instances for high load simulation.
Provides detailed latency measurements for individual request paths.
Weaknesses:
Text output format can be limiting for scripted testing and report generation (current version).
wrk2:

Strengths:
Claims more accurate latency measurements using HdrHistogram and coordinated omission.
Simple to trigger tests against a single endpoint.
Supports scripting test behavior in Lua for complex scenarios.
Well-defined report format with the ability to customize reporting via Lua scripting.
Weaknesses:
Installation instructions require referring to the wiki

**Comment by cloudmagic80** [comment]
<img width="1276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9e3949c451d4afff3479fd57d65e5c1f66b67ab/Screenshot%202024-07-01%20at%2010.30.40%20AM.png" alt="Screenshot 2024-07-01 at 10.30.40 AM.png" />

**Comment by cloudmagic80** [comment]
We can start working on this. I was able to complete the spike ticket
