### ISSUE TITLE
MHV LP: document health-related user tasks/needs

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#86875]
### User story

As a Cartography team member, I want to recommend a page layout strategy for the MHV on VA.gov landing page that thoughtfully responds to many inputs and articulates the user needs the landing page should be meeting, as well as how we can measure the success of those how well we're meeting those needs over time.

### Notes and inputs

- [Mural folder: Landing page iteration](https://app.mural.co/t/departmentofveteransaffairs9999/r/1698186759596?folderUuid=eefcef6d-e068-4354-994a-8eded70deae5) – and please move related murals into there if appropriate
- Folder where Cindy Merrill saved [research into Veteran Top Tasks](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/research) (for VAgov as a whole, not just health) – NOTE, look for the readouts of this research, the linked folder appears to just have Excel files
- Focus on health-related tasks

Possible tasks:
- [ ] Value prop workshop
- [ ] Identify assumptions and track research opportunities (input for #86876)
- [ ] Share with and get feedback from larger team
- [ ] Work with Robyn, Patrick and Kaitlin to get their input

## Acceptance criteria

- UX Workshop(s) completed to gain insights from team members
- Drafted strategy for home page: Customer segments (aligned with different needs served by the home page), jobs, pains and gains, gain creators and pain relievers and gaps (all based on value prop canvas; could use different methodology)
- Get feedback from Kaitlin, Robyn and Patrick

### Not in scope:
  - Broader, non-health-related tasks on VAgov

**Comment by fmccaf1** [comment]
Looking at Cindy Merrills work on the now former landing page, I think these are the most helpful tidbits applicable to our work:
- Finding that many Veterans do not scroll AT ALL on the home page
- Finding that Veterans seek/want/need "content customized to me"
- Recommendation that top tasks (most visible tasks on LP) include both commonly used links as well as hardest to find links
- Recommendation that in addition to main LP content, the LP also includes visually prominent links to other tasks or content

**Comment by wesrowe** [comment]
next steps:
- structure approach to evaluating success per job
- use Robyn where MHV Analytics data is needed (eg HRC)

**Comment by fmccaf1** [comment]
There didn't seem to be much appetite for looking at this work now from the meeting with Robyn. Not sure exactly how to proceed, but wondering if this is a good place to close this ticket. I think Wes's next steps (comment above) is right (start working on evaluating success for our product).

**Comment by fmccaf1** [comment]
@wesrowe I'll wait for your guidance on this ticket

**Comment by wesrowe** [comment]
@fmccaf1, can you consider whether the follow-up ticket (depdencies above)  captures next steps adequately? or is there another ticket needed or existing...

**Comment by fmccaf1** [comment]
@wesrowe I think [this ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/87874) is sufficient for all work I'm thinking is necessary for next steps. If you agree, then I think we can close this ticket as part of sprint 35 (no work has been done on it yet this sprint)
