### ISSUE TITLE
Document prioritized research opportunities for home page

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#86876]
### User story

As a Cartography team member, I want to easily understand our prioritized research opportunities so I can start to understand and plan for upcoming research.

### Notes

[Google word doc here](https://docs.google.com/document/d/12M0eidYUbifTQFYQ4FV7zh15qyoKcPepFTCYQ_jov8s/edit) (for collaboration only). When we're making less frequent changes, we'll move to our team's github space. 

This work is to follow [work to define strategy for the home page](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/86875). The plan is to come away from that strategy work with a list of assumptions about our users needs and ability of home page to align with those needs. This list of assumptions is the starting point for this ticket.

Possible tasks:
- [x] Using assumptions from value prop work, come up with associated list of testable hypotheses and/or research questions 
- [x] Find best place to document these ^ and continue to edit and/or add research opportunities 
- [x] Bucket reseearch opportunities into possible test scenarios or topic areas (for example, all opportunities that touch on Veterans with cognitive disabilities)
- [x] Prioritize research opportunities into now, later, future
- Meet with Wes to go through research opportunities and discuss timing of next research project
- Meet with Robyn to get her feedback and insights (Are these the right things to look at? Are we missing something? Should we prioritize differently?)

## Acceptance criteria
- Team aligned on direction for next round of Veteran research

**Comment by wesrowe** [comment]
@katbrinkley @fmccaf1, I would like us to start grappling with research directions/ideas over the next couple sprints. Are we ready for this ticket yet, or is there a precursor needed?

**Comment by katbrinkley** [comment]
Would we be able to pull insights from our gap analysis work? if so, I think that covers most of the precursor work. Maybe an ideation session before creating tickets to form a vision forward at a high-level first? welcome thoughts from you both @fmccaf1 @wesrowe

**Comment by fmccaf1** [comment]
Estimate: 5
