### ISSUE TITLE
[V0.1] Watchtower Event for ITF re-try exhaustion

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#86893]
The purpose of this tickets is to create a watchtower event for ITF re-try exhaustion.
- In cases where the async post created for ITF V.0 fails to exhaustion, data about the failure shall be captured (e.g. user, date/time, pension application).
- This data shall be made available to business users through an alert (e.g in Slack notifications) or through a user interface.

**Comment by aplatt-coforma** [comment]
I think this is a duplicate of work requested in #82225.
