### ISSUE TITLE
vets-api generate new field from appointment request reasoncode.text - contact

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#86895]
As part of the vets-api code consolidation initiative we need to add a new field to the service layer that derives info from the reasoncode.text field. This is for appointment requests.

`contact`- `[{ type: 'phone', value: phone },{ type: 'email', value: email }]`. Phone number and email are gotten from reasonCode.Text field.

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
[ ] - new field created
[ ] - test updates

**Comment by JunTaoLuo** [comment]
From recent discussion with @simiadebowale, we've decided to update the new field to the following to match the API schema [here](https://github.com/department-of-veterans-affairs/vets-api/blob/387b6c3de195170969d1fef5d5e843a500e4192b/modules/vaos/app/schemas/appointments_index.json#L207-L226) and will look like:
```
      contact: {
        telecom: [
          { type: 'phone', value: '2125551212' },
          { type: 'email', value: 'veteranemailtest@va.gov' },
        ],
      },
```

**Comment by ldelacosta** [comment]
@simiadebowale will validate in staging.

**Comment by JunTaoLuo** [comment]
Just re-assigning myself so I can keep an eye on this issue more easily.

**Comment by simiadebowale** [comment]
Update api to match schema as discussed. Contact field should return `type` instead of `system`. cc: @JunTaoLuo

**Comment by simiadebowale** [comment]
This has passed validation.
