### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#86920]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2024

### Date Range End

06-25-2024

### Product Name(s)

Claim Status Tool

### Product Description

The claim status tool provides claim status to claimants checking claim status on VA.gov.

### Survey URL(s), key term(s), case category or type

all data with the root: https://va.gov/track-claims/

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

jacob.worrell@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
