### ISSUE TITLE
Create design specs for secondary [+more] button. 

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#86938]
## Task Description
Based on the midpoint review for Community Care Direct Scheduling, there was a callout that we will need to update the [+more](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86803) to a secondary button for the following pages Locations page (direct schedule flow/VA request flow), Clinics page (direct schedule workflow) and Providers page (Community Care request flow).

## Acceptance Criteria
- [x] Create specs for all screen sizes

## Design Spec
- [Figma Link](https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=BSSVIWQyci0Ixd5A-1)

**Comment by outerpress** [comment]
@Cieramaddox is this one done?

**Comment by outerpress** [comment]
@ldelacosta do you have a link to the dev tix for adding the secondary More button? I want to add those here before closing.

**Comment by outerpress** [comment]
Dev work completed in #87014 and #86803, closing
