### ISSUE TITLE
10-7959a: Review 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86957]
As a VA.gov user, I want to be able to review the CHAMPVA claim form I just filled out so I can edit any info before submitting.

[Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1481-276887&t=LG8dR86iRSeFHJg4-11)

- Page elements:
  - breadcrumb 
  - header and subhead
  - copy
  - footer
- Review page
  - accordion is closed by default
  - follow figma for expanded view - section headers 
  - statement of truth

Acceptance criteria:

- Given the user is on VA.gov and has filled out the CHAMPVA claim form
- When the user gets to the review page
- Then the user can review and/or edit their information before submitting

**Comment by michaelclement** [comment]
Work done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30819).

Currently waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
Note that the file upload review section will differ because that component hasn't been switched to v3 yet. Also, the list loop review represented in Figma doesn't match the behavior of the new list loop - it looks like this:
<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ce7a8956afd28e0fb53556f3697d4f91994d618/ll.png" alt="ll.png" />

**Comment by michaelclement** [comment]
[Staging URL](https://staging.va.gov/ivc-champva/10-7959a)

**Comment by michaelclement** [comment]
@marywang2 @syd-hoeper This has been merged and should be visible on staging shortly. Everything should be in line with the exception of the items noted above.

**Comment by michaelclement** [comment]
@marywang2  @syd-hoeper Latest fixes have been merged in as of a few minutes ago and should be visible on staging shortly. The notes above still apply. Thanks!

**Comment by marywang2** [comment]
Thanks @michaelclement. (@syd-hoeper it looks like the figma for the review page will have to be updated at some point per all the notes above).
A few changes:
- Beneficiary info section: I'm seeing 'phone information', it should be 'phone number'
- mailing address - it should pull in only first name for the 'has...mailing address changed...?" (not sure if that is how it appears on the form screen as well?)

**Comment by michaelclement** [comment]
@marywang2 I think these changes may just have not made it to staging yet when you checked? I'm seeing this:

Beneficiary Info Section (review)
| | |
|-|-|
|<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce65a359d99823f8a0b8e13ac0e7a052b1502441/Screenshot%202024-07-16%20at%2008.01.48.png" alt="Screenshot 2024-07-16 at 08.01.48.png" />|<img width="690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cb0a21917ff5864a51092219575621dbcb5e249/Screenshot%202024-07-16%20at%2008.02.19.png" alt="Screenshot 2024-07-16 at 08.02.19.png" />|

| |
|-|
|<img width="566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUxpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06e277f5117abdbcd17acaa6464c1f6f529a0d29/Screenshot%202024-07-16%20at%2008.04.55.png" alt="Screenshot 2024-07-16 at 08.04.55.png" />|
