### ISSUE TITLE
10-7959f-2 - file upload screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86950]
As a VA.gov user, I want to be able to include my supporting documents for my FMP claim so that my claim can be processed successfully.

- use v3 components
- Figma [link](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?node-id=732-40895&t=Xp5d6bGBoSRA7fiG-0)

## Acceptance Criteria

  - Given the user is filing an FMP claim and filling out the 10-7959f-2 form, 
  - When the user has supporting documents and receipts to upload and clicks on the "Upload" button
  - Then the user should be able to select files and the uploaded files should be displayed
  - And the user should be able to remove uploaded files if necessary

**Comment by reiting** [comment]
![Screenshot 2024-08-22 at 10 04 19 AM](https://github.com/user-attachments/assets/8b836b96-b725-4329-8a9d-16874f274fc9)
![Screenshot 2024-08-22 at 10 04 29 AM](https://github.com/user-attachments/assets/f4ac65e2-504e-470b-ad40-32d081cb039f)

**Comment by reiting** [comment]
@marywang2 this was approved and merged this morning and should be in staging now.

**Comment by marywang2** [comment]
@reiting not seeing this part (box with drag files...). <img width="1234" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b457ee0dfc209f3541b6b192a0eb5ed17ccde25d/Screenshot%202024-08-23%20at%205.55.53%E2%80%AFPM.png" alt="Screenshot 2024-08-23 at 5.55.53 PM.png" />

**Comment by reiting** [comment]
@marywang2 right, we agreed to not do that part now, and just have the regular upload component like the one in your comment!

**Comment by marywang2** [comment]
Got it, thanks!

**Comment by marywang2** [comment]
@jamiefiore for review as well.

**Comment by marywang2** [comment]
@reiting I know the figma needs to be updated, but can we unbold the first 3 sentences that are currently bold "Upload proof that you paid...Make sure it includes..."?
