### ISSUE TITLE
Implement unique user tracking in DD

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86966]
### User story

As a Cartography team member, I want to configure Datadog to track unique users on the MHV landing page, so that we can get better visibility into user journeys.

### Notes
- [PR for reference](https://github.com/department-of-veterans-affairs/vets-website/pull/29767/files) – Mark Dewey has offered support if we need it
- [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1719332251894649) that includes a little input from Mark

Possible tasks:
- Scan the data collected for any concerns about PII

## Acceptance criteria

- Implemented unique user tracking
- Determine if feature toggle is needed; if added, ticket for later removal
- Validated in DD that it is working as expected; e.g.:
  - On the Analytics Summary page in Datadog, unique visitor count is increasing over time
  - In the session details, the user Id is getting populated

**Comment by wesrowe** [comment]
refinement note: estimate is 3 if no toggle needed

**Comment by dcloud** [comment]
The minor challenge here is that we no longer have a single `App` wrapping everything, so this will require a little more thought

**Comment by dcloud** [comment]
I think I'll try out:

- Create a `LandingPageContainer` and move LandingPage controller(?) logic there from `App.jsx`
- Edit `App.jsx` to be a wrapper for the routes and make sure user data is loaded once for the application?

**Comment by dcloud** [comment]
Going to link to draft PR in a moment, but noticed that the feature flag from the reference PR was removed in https://github.com/department-of-veterans-affairs/vets-website/pull/30354

**Comment by dcloud** [comment]
I'm going to log into staging to test this further:

I plan to run `window.DD_RUM.getInternalContext()?.session_id` and/or `window.DD_RUM.getUser()?.id`, and look for the session with a user id in Datadog's Session Explorer

**Comment by dcloud** [comment]
[This a staging session](https://vagov.ddog-gov.com/rum/sessions?query=%40application.id%3A1f81f762-c3fc-48c1-89d5-09d9236e340d%20%40usr.id%3A%22bdf4d600-7d6c-46ef-9556-137a42c69a51%22%20%40type%3Asession&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZC3jC2poDfU7QAAAAAAAAAYAAAAAEFaQzNqQzJwQUFCa09YYWdDQ094YkVNRwAAACQAAAAAMDE5MGI3OGQtZDExYi00YzM0LThjOWEtYzc3M2QxNDQ2MGI2&fromUser=false&p_tab=session&refresh_mode=paused&sort_by=timestamp&sort_order=desc&track=rum&viz=stream&from_ts=1720458925746&to_ts=1721063725746&live=true) that shows a user id having been recorded. Checked the `@usr.id` value against the JSON response from the user endpoint. User doesn't have facilities at the moment, so going to log in with one who does (though that has no bearing on the unique user tracking).

**Comment by allanto-ah** [comment]
Environment: Staging, Production

Checked through several session replays and logs without session replays and saw that the `@usr.id` value is populated
