### ISSUE TITLE
Test connection of vets-api prod env to WellHive sandbox

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#86964]
## Description 

To help prepare for production, we want to get onto a production box with vets-api and see if we can make a curl statement to the WellHive prod API. WellHive can configure the sandbox with TIC and the same IP address ranges and ciphers and then from DSV AWS prod environment, hit that same sandbox. The end result is to confirm that vets-api can get to it their environment using TIC, prod IP address, etc. 

## Tasks

- [ ]

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created
