### ISSUE TITLE
10-7959a: Confirmation page copy updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86986]
As a VA.gov user, I want to be able to see confirmation for the CHAMPVA claim form I just filled out so I know my submission went through.

_**Note: need updates based on whatever we decide to do for the other forms**_

~~[Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=961-139667&t=Ko13IszQmJiM9ZRY-0)~~ [Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2031-36584&t=ImLeqovfx5BsE3V7-0) (updated Aug. 14, 2024)

- Page elements:
  - breadcrumb 
  - header and subhead
  - copy
  - footer (on all pages except confirmation page)
- Confirmation

Acceptance criteria:

- Given the user is on VA.gov and has filled out the CHAMPVA claim form
- When the user submits the form
- Then the user sees the confirmation page with message

**Comment by michaelclement** [comment]
Per Jamie, we're currently waiting on CAIA feedback before this is locked in.

**Comment by jamiefiore** [comment]
I updated the [Figma link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2031-36584&t=ImLeqovfx5BsE3V7-0) in the ticket. @marywang2 @michaelclement

**Comment by michaelclement** [comment]
| Confirmation Page|
|-|
|<img width="356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk45Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2820eea580810dd0337563f254edbfa04abda26e/Screenshot%202024-08-22%20at%2011.03.25.png" alt="Screenshot 2024-08-22 at 11.03.25.png" />|

**Comment by michaelclement** [comment]
@jamiefiore @marywang2 Please see the above screenshot to review

**Comment by marywang2** [comment]
@syd-hoeper for review as well.

**Comment by michaelclement** [comment]
@marywang2 This is working on staging now - thanks!
