### ISSUE TITLE
[CodePen] Make adjustments based on CAIA feedback

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#86980]
## Tasks

- [x] Make adjustments to CodePen based on [CAIA feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86740#issuecomment-2189308373) (See comment below for specifics.)

**Comment by benbrasso-agile6** [comment]
@cgednalske here are the updates we made in Figma, that need to be made in CodePen, cc @Cieramaddox 

- Expires in 310 days (for task card tag)
- Intro text on Referral into page:

> Your referring VA facility approved your referral. You can now schedule your appointment with a community care provider. After that, you’ll need to request a new referral.

- Changed Kristina Jones next available to the 26th on the list page
- On choose date and time page, make everything up until the 26th inactive

**Comment by benbrasso-agile6** [comment]
Need to rollover? @cgednalske

**Comment by cgednalske** [comment]
@benbrasso-agile6 I might be able to finish today unless I run into issues. I'll let you know if I can't and need to roll it over.

**Comment by benbrasso-agile6** [comment]
Rolling over: mostly complete but ran out of time + Christina is sick. Better healthy than... eh, I got nothing to rhyme.

**Comment by cgednalske** [comment]
Two items left in total. 
All CAIA changes completed except one, which I need to ask them about because in theory we already have an aria label. And then just the last task for the cancel button listed above.

**Comment by benbrasso-agile6** [comment]
@cgednalske can we make sure this one is knocked out and complete by today or tomorrow pls? Sorry, should have mentioned in stand up.
