### ISSUE TITLE
10-10d: create feature toggle and react widget ID

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#86998]
- Create feature toggle - [Feature toggle guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) and provide name for release plan
- Create a React widget in vets-website for the dynamic content, per documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) and provide ID (to share with CAIA)

**Comment by michaelclement** [comment]
Work is done in these three PRs. Order of operations is this:
1. [This vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17283) needs to be merged
2. [This vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30556) needs to be merged
3. [This other vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30558) needs to be merged

Once that's accomplished we should be able to view and interact with the toggle by going to https://staging-api.va.gov/flipper/features/form1010d

**Comment by michaelclement** [comment]
Based on [this document](https://depo-platform-documentation.scrollhelp.site/developer-docs/staged-rollouts), the react widget is a small widget we will add to a Drupal static page (which is yet to be created). This will be the jumping off point where veterans will access our form to begin with.

Getting this set up will require PRs in three repos: vets-website, content-build, and vagov-content

@reiting - does this track with your understanding? I'm pretty sure I see what we're doing but just want to double-check.

**Comment by michaelclement** [comment]
React widget ID: `form1010d`

**Comment by michaelclement** [comment]
I put together a [request for UI access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87083) so I can edit the flipper in production. Waiting on approval.

**Comment by michaelclement** [comment]
All PRs were merged and flipper is visible in the admin UI on staging [here](https://staging-api.va.gov/flipper/features) (search on the page for `form1010d`)

I'm still waiting on my access request to be approved, so until then we can't actually toggle the flipper.

**Comment by michaelclement** [comment]
@baltes @marywang2 @reiting - if you'd like to get access to the flipper UI to enable/disable forms you'll need to fill out a ticket like [mine](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87083) - [here's the link to create a new one.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request%2Cflipper-access-request&projects=&template=vetsapi-flipper-ui-access.yaml&title=Flipper+UI+access+for+%5Bindividual%5D)

**Comment by michaelclement** [comment]
@baltes This is ready for you to take a look at - if you visit 10-10d on staging you'll see that it's blocked by a feature flipper. Thanks!

**Comment by michaelclement** [comment]
@baltes It's not currently blocked because we needed to look at the form, but let me know when you want to review this and I can walk you through it. Thanks!

**Comment by baltes** [comment]
Hi @michaelclement , I see the block but then it hops to the intro page. Just wanted to make sure this is expected.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5c6fb1b9f23ae8486282a802f6cad060166e8d7/Screen%20Recording%202024-07-01%20at%2012.42.04%E2%80%AFPM.mov)

**Comment by michaelclement** [comment]
@baltes Yep, that happens because it first has to check if the form is enabled and that check takes a second
