### ISSUE TITLE
Payment History VBA Pre MVP 1.5 - FE/BE Development

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#86996]
## Issue Description
As a Veteran who is logged into the Debt Portal I would like the ability to view just the amount and changes (increase/decrease) my for my payment history.

**The Veteran should see:**
- Accordion removal from how to pay
- Additional scope TBD after tickets are defined
## Definition of done
- Design and Front End sync on technical implementation of design
- [x] Required
- [ ] Not Required
>
- [ ] Business rules and exceptions for displaying data are defined
- [ ] Create design 
- [ ] Business rules and exceptions for displaying data are accounted for
- [ ] Implement design 
>

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by HeatherRienks** [comment]
Confirming all work has been completed.
