### ISSUE TITLE
Number of pending appts drops to next line

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#86999]
## Summary
_Describe what went wrong_

On mobile (320px) the pending appointments link stays on the top line, but the number of pending appts drops to the next line. 

This is a result of the font normalization changes to update body fonts to 16.96 px. (This is not enabled for all users at this time 06/26)

<img width="328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a030f0be37f66fa1818cb6f3f0c975c15adb783/image.png" alt="image.png" />

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** 

1. Go to: staging.va.gov
2. Login as Judy Morrison
3. View pending page
3. View page at 320px

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

- Given `Pending (##)` 
- The number - `(##)` breaks to the next line
- And `Pending` stays on the top line

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

`Pending (##)` should always stay together.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by vbahinwillit** [comment]
@outerpress - The best solution I could come up with is to remove the count for pending appointments and remove the print icon since there is not enough space to support these items anymore. I tried the following:

- Decreasing the margin spacing between the menu items - Fail
- Removing the print icon and keeping the count - Fail
- Removing both print icon and count - Success

I attached a screenshot of the proposed solution (still working on the alignment). Basically, screen sizes less than 320, will trigger this layout. Thoughts???

![localhost_3001_my-health_appointments_ (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3587066/206ebb3a-61b6-4ac0-802f-75a1d410aaee)

**Comment by outerpress** [comment]
@vbahinwillit not sure if this would work but what about adding `white-space: nowrap` to the `Pending (##)` link?

It's okay if the links and button start dropping to their own lines, I just want to keep the number of pending appts together with "Pending"

I don't want to remove the icon or the number of pending appts for this.

**Comment by vbahinwillit** [comment]
@outerpress - That should work. I thought everything needed to stay on the same line.

**Comment by vbahinwillit** [comment]
Just a thought but how many people actually have a device at 320 or less? It seems like it wouldn't be that important if the count or icons were not displayed if you have a Motorola flip phone. :-)

**Comment by vbahinwillit** [comment]
@outerpress - This is what it will look like.

![Screenshot 2024-07-11 at 11 28 48 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3587066/70db09c7-2005-40a6-b91e-a44db0889a41)

**Comment by outerpress** [comment]
@vbahinwillit So 320px is the smallest size we support. So we don't need to put too much work into 319 and below. For this bug your screenshot looks good. 

With some of the upcoming work on referral scheduling we want to take another look at how we handle pending appointments so I think we'll have other opportunities to improve this menu in the nearish future.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. @Bren22va @outerpress
