### ISSUE TITLE
Content breaking out of date page alert

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#86993]
## Summary
On the calendar page on mobile screens:
- When an appointment can't be found for a given date
- And requests are enabled
- The alert content breaks out of the page boundary

Screenshot:

<img width="175" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEdUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61e5ca2f1cfb0c1651c703e4cb89ba9558f451b9/image.png" alt="image.png" />

## Specs
- Device: Mac
- Browser: Chrome 

## Steps to Reproduce
**Test User:** 

1. Go to: staging.va.gov
2. Login as Judy Morrison
3. 

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

### Desired Result
The text at the bottom of the alert should stack and be aligned to the left at all screen sizes:

[Button]Request an earlier appointment[/Button]

OR

[Link]Contact your local VA medical center[/Link]
## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by melissa-lefevre** [comment]
@jenniemc I am having a hard tie reproducing this, do you recall how you got this alert to show?

**Comment by jenniemc** [comment]
@melissa-lefevre , Steps to recreate:

1. Login as Judy Morrison
2. Turn on the Inspect tool to view the mobile S at 320px width
3. Schedule a Primary Care appointment
4. Select Cheyenne VA Medical Center
5. Select any VA clinic option presented. Do not select "I need a different clinic"
6. On "When do you want to schedule this appointment?" page, enter today's date
7. On the calendar page will show the alert to validate

**Comment by melissa-lefevre** [comment]
@jenniemc thanks for giving me those steps! I am however still getting the yellow warning alert versus the blue info alert. 

 <img width="77" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9ebc6cda5ebfa6683081e4763ace96f6db2e713/staging.va.gov_my-health_appointments_schedule_type-of-care.png" alt="staging.va.gov_my-health_appointments_schedule_type-of-care.png" />

**Comment by jenniemc** [comment]
Hi @melissa-lefevre, The blue info background alert image @outerpress attached to this ticket was created in my local environment to demonstrate the alert text expanding beyond the design boundary.  The exact appointment criteria is not replicable in staging to produce a blue background AND the alert text. The closest I can come up is using the same day criteria to display the alert text but a yellow warning background.

 If you're wondering whether warning alert is the correct label for same day appointment, here is an [archival link](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1-3266&t=UFKamuH4TbjuHUls-0) that shows using the warning alert for attempting a same day direct schedule appointment.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @outerpress
