### ISSUE TITLE
Masking numbers (PII/PHI) - documentation design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#87]
How do we mask information?

Here are some points. These bullet points are not in any particular order.
- Review pages
- What gets masked, what doesn't
- Show last 4 of SSN, for example
- Do we mask on info during input? why/why not?

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by caw310** [comment]
Closing as this is over 3 yrs old. And PII is masked on forms.
