### ISSUE TITLE
PM: Coordinate IA Intro for VSA Authenticated Exp Team

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#870]
### User Story
As a PM for a VFS team going through onboarding with VSP, I need to participate in an IA intro session along with relevant members of my team, so that we know best practices for IA and how to engage with the VSP content & IA team.

### Goal
Schedule and attend IA onboarding session with VSP's content and IA team and the PM, content writers, and designers on VSA Authenticated Exp.

### Definition of Done
- [x] VSA Authenticated Exp PM has reached out to schedule IA intro with VSP content & IA team.
- [x] Meeting has been completed: VSA Authenticated Exp has gone over best practices and ROE with VSP content & IA team.
- [x] Document findings and feedback from that meeting to recommend for doc iteration.
- [x] Ticket has been assigned to a sprint and an epic.

**Comment by rroueche** [comment]
@meganhkelley work with @mnorthuis to fill out the user story, goal, and acceptance criteria for this issue please!

**Comment by Justin-Pickett** [comment]
@mnorthuis please let me know when we can get this scheduled for early next week if possible. Thank you.

**Comment by Justin-Pickett** [comment]
This has session was completed with @mnorthuis @thatmattjohnson @artistgreen and @Justin-Pickett on 9/20/19. 

Closing this ticket.
