### ISSUE TITLE
[BE] 10-10EZ - Retrieve Facilities from VES DB to populate list from our DB

### ISSUE THREAD

**Issue by Mitch-A6** [department-of-veterans-affairs/va.gov-team#87005]
## Background
Any Facilities we send have to also exist in the VES Oracle DB, or it prompts errors downstream (cf. https://dsva.slack.com/archives/C0310PNS7TQ/p1718295305970269). As a result we deactivated this feature's integration with Lighthouse API (#75304 ). Instead, we'll add a script to pull the Facilities data from VES into our DB (following the pattern from Income Limits) and use that to populate the form.

## Tasks
- [x] Populate our DB's list of facilities from VES
- [x] Send the FE a list of facilities by state

## Acceptance Criteria
- We have an up-to-date `std_institution_facilities` table with (as of Friday) 3998 entries after the import script runs (4:30pm ET)
- We show only the Facilities for each state that are current AND would be valid in VES once both scripts have run and the flag is enabled.

**Comment by hdjustice** [comment]
This work was validated in staging and production.  Launch to Prod was completed on 8/27 successfully
