### ISSUE TITLE
Update the +more link to a secondary button (CC request flow)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#87014]
## Description
Based on the midpoint review for Community Care Direct Scheduling, there was a callout that we will need to update the [+more]() to a secondary button for Providers page (Community Care request flow). 

<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--072c8cff2e450261c3fd16e1b18f1f18ecbaa676/CC.png" alt="CC.png" />

---

## Acceptance Criteria

- [ ] Given when the user is on the CC request schedule workflow
       When the user lands on the Provider page and has more than _(5) providers listed_
       Then the secondary buttons will be displayed  for `+more` and `Cancel`
       And page design matches the [design spec](url)

### Design Assets
[Design spec](https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=Jg6FySfgu2Oq0Et6-1)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JunTaoLuo** [comment]
@ldelacosta the design spec links seems to be linking to the issues page so I can't completely verify the change. I'm going off of what's described here for now but if you can find the correct links I can make additional updates if necessary.

**Comment by melissa-lefevre** [comment]
@JunTaoLuo I updated the [design spec](https://www.figma.com/design/E3tsRYjRAo2sTIY4yWK4RY/Show-%23-more-secondary-button-%7C-Appointments-FE?node-id=2003-14186&t=Jg6FySfgu2Oq0Et6-1)

**Comment by JunTaoLuo** [comment]
@melissa-lefevre This looks like the design spec for the locations page, not the providers page. Can you double check that?

**Comment by ldelacosta** [comment]
Validated it in staging using Judy Morrison. UX team will do another check as well. 

<img width="650" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31c087b36daa8479b22f14bc599b27650d471c68/Screenshot%202024-07-10%20at%207.29.12%E2%80%AFPM.png" alt="Screenshot 2024-07-10 at 7.29.12 PM.png" />

**Comment by melissa-lefevre** [comment]
I did not find any issues, looks good to me.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
