### ISSUE TITLE
SOCKS access for [Fatma Khan]

### ISSUE THREAD

**Issue by fatmakhan0395** [department-of-veterans-affairs/va.gov-team#87038]
### Your Name

Fatma Khan

### Your Email

fatma.khan@va.gov

### Your GitHub Handle

fatmakhan0395

### Your Role and Team

React developer

### Product Manager (PM) name and email

Darla VanNieukerk, darla.vannieukerk@va.gov

### Product Owner (PO) name and email

Darla VanNieukerk, darla.vannieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHyCYqOynnSjHTcLkymDHgUufxHgCDZ5YwMwTUL4+e5J fatmakhan@Fatmas-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![screenshot_1](https://github.com/department-of-veterans-affairs/va.gov-team/assets/145523589/d81004b4-4f05-430e-8efb-18d7931abf87)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by bdech** [comment]
SOCKS PR https://github.com/department-of-veterans-affairs/devops/pull/14689

Closed above PR. Bot did create a PR.

**Comment by patrick-black-oddball** [comment]
merged
