### ISSUE TITLE
Adding Alex Chan to DSVA Slack

### ISSUE THREAD

**Issue by GcioGregg** [department-of-veterans-affairs/va.gov-team#87039]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Multi-channel
- What channel(s) do they need to be added to? vfs-platform-support, vfs-all-teams, govcio-vfep-team, govcio-vebt-team, vfs-change-announcements

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
Alex Chan is a Ruby on Rails backend developer on the VFEP team.  He needs Slack to get support, communicate with other vfep developers and keep up on current notifications to developers.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add alex.chan1@va.gov as a multi-channel guest to these channels: vfs-platform-support, vfs-all-teams, govcio-vfep-team, govcio-vebt-team, vfs-change-announcements
- Please add alex.chan1@va.gov as a full member.

**Comment by LEHigley** [comment]
@GcioGregg the above says alex should be added as both a multi channel guest and a full member--which of the two should it be?

**Comment by GcioGregg** [comment]
@LEHigley Full member please.  Thanks!

**Comment by GcioGregg** [comment]
Hi @LEHigley , any update on this request?  Thanks.

**Comment by GcioGregg** [comment]
@KevinMHoffmanUSDS @LEHigley Any update on getting Alex Chan access to Slack.  Thanks.

**Comment by LEHigley** [comment]
sorry i was OOO last week. this is now done.
