### ISSUE TITLE
Create a test suite for Salesforce::Service

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#8704]
**Description**
The API requires 90% test coverage for every file. Currently `src/lib/salesforce/service.rb` has no test coverage at all. `lib/carma/models/submission_spec.rb` runs the Salesforce lib code during testing because a method is not being stubbed. This allows the CI server to pass without the 90% test threshold error. If this spec were to be stubbed, as it should, the CI build would fail due to this error:
```
Coverage report generated for RSpec to /srv/vets-api/src/coverage. 32216 / 32510 LOC (99.1%) covered.
File (/srv/vets-api/src/lib/salesforce/service.rb) is only (61.11%) covered. This is below the expected minimum coverage per file of (90.00%).
```

**Solution**
- [ ] Add a test suite for `src/lib/salesforce/service.rb`
- [ ] Stub the method in `lib/carma/models/submission_spec.rb` that's hitting the Salesforce lib

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in over a year.  If work is needed, a new ticket will be created under an initiative
