### ISSUE TITLE
10-7959f-1: placeholder for UAT/updates before staging review (WIP)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#87043]
(also this [change](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/87183))

**Comment by brian-wilke** [comment]
We need to change any button or label that says "Application" to "form".  
1) this was on the intro page
2) this is also on the review/submit page.
