### ISSUE TITLE
SOCKS access for Wafi Mohamed

### ISSUE THREAD

**Issue by wafimohamed** [department-of-veterans-affairs/va.gov-team#87040]
### Your Name

Wafi Mohamed

### Your Email

wafi.mohamed@va.gov

### Your GitHub Handle

wafimohamed

### Your Role and Team

React Developer 

### Product Manager (PM) name and email

Darla VanNieukerk

### Product Owner (PO) name and email

darla.vannieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1mNRiP2BRRiIsdPDjQzd+qIrR7QNpDsIcWXFHoInR5303zTFrqJNr3UMx7G2kOpaPjzJT1MMKxc19AgmJYr1xHYluQrwI2z7/2EV0VuciNfXbIBklAGOYT/IGXCCblKGmAOWTw9myOhKRkcryvh3o4OPMWyWW514NEL0e+roZkjf3/8TNG4eoLfLS2Tq47reQey78lsNdEkWawju9yjb3NirN4U9T56N4k/jkH3mGcyDR9VN5RPMjGfXiiNs0vNMZDxg/6DJTIPorEy2qfYR0NcCdDo5hTxzkKfgETNzp39++8KsqHIZjKoEC+4rCLye+4vHYvgkAWgb/iQ4UEF82sXrnDBMYUv4rkI/JnLLc7pKcipHS1UyhFTeOIGnK3TRYCdxZC9np9b7L5oNdTmx1uEyc373uOtSWAgLEH+ySjgt8F2q2L8sjXmhCma5LsPdmPpP+wPGM7no4EN+Hzj6sPwiRZ4vhIGRzfMr1Vypl2kWRAnQvtYhAAo7KHSJb660= wafimohamed@Wafis-MBP.lan

### E-QIP Transmittal Confirmation

<img width="936" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/158514667/5b552e74-10cf-463b-8181-657fa3354db8">

### User must exist in a roster before SOCKS access can be granted

- [X] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Closing, since the accompanying PR has been merged.
