### ISSUE TITLE
Manually verify Domo CSAT calculations

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#87053]
### User story

As a Cartography team member, I want to validate that the Domo dash is calculating CSAT numbers accurately.

### Notes
- Domo: [MHV CSAT Dash](https://va-gov.domo.com/page/601491420)

Possible tasks:
- 

## Acceptance criteria

- Manually calculated CSAT scores from a time period and compared to Domo's result
- Spot-checked other calcs are as intended
- Consulted with Basil on the Analytics team to address any questions or discrepancies
- Ticketed next steps as needed

**Comment by fmccaf1** [comment]
I'm still thinking I can get this wrapped up before sprint demo tomorrow

**Comment by fmccaf1** [comment]
Waiting to hear back from contact center folks about some data being missing. [Ticket is here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87421)

**Comment by fmccaf1** [comment]
[I submitted a request to the analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87809) re: updating the MHV CSAT dashboard to appropriately treat survey responses without a rating (they should not be added to the denominator in the calculation). 

Also, Kat and Jonathan are working to retroactively get data so we have medallia data from both /my-health/ and /my-health (with final slash and without) to better align with the dashboard data getting pulled in. 

[Still waiting on the other data request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87421)to get to the bottom of continuing discrepancies between manual CSAT calculations and the domo dashboard. At this point, the dashboard is continuing to receive responses that our team does not receive in what seems to be the same medallia request. I will update when I get the requested data

**Comment by fmccaf1** [comment]
I summarized findings for four months and Robyn will take forward and let me know if there is more work for me to do here. [Slack thread with findings summarized](https://dsva.slack.com/archives/C0581MN69TJ/p1720712793819459)
