### ISSUE TITLE
VBA Request for ITF Metrics

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#87051]
Provide us the volume of instances where the date the claim was started, does not match the claim submission date.  And of those cases, how many of those claims are currently cleared, canceled or closed?

**Comment by wayne-weibel** [comment]
```
irb(main):005> claims.length
=> 3425
irb(main):006> overday = claims.select { |c| c.created_at - c.itf_datetime > 1.day }
=> [#<SavedClaim::Pension id: 8914640, created_at: "2024-04-30 02:41:16.683799000 +0000", updated_at: "2024-04-30 ...
irb(main):007> overday.length
=> 817
irb(main):008> overday = claims.select { |c| c.created_at - c.itf_datetime > 1.day || c.created_at.day != c.itf_datetime.day }
=> [#<SavedClaim::Pension id: 8914640, created_at: "2024-04-30 02:41:16.683799000 +0000", updated_at: "2024-04-30 ...
irb(main):009> overday.length
=> 981
irb(main):010> 
```
total: 3425
over 24hrs: 817
‘next day’: 981 (includes over 24hrs)

**Comment by matt4su** [comment]
Hmmm ... our last Sprint Deck listed 3897 submitted claims, 500 or so higher, curious on the source of the difference.

**Comment by wayne-weibel** [comment]
```
irb(main):001> claims = SavedClaim.find_by_sql("SELECT * FROM public.saved_claims WHERE form_id = '21P-527EZ' AND created_at > '2024-01-31 16:00:00' AND itf_datetime IS NOT NULL").uniq
=> [#<SavedClaim::Pension id: 8590702, created_at: "2024-02-29 18:03:52.428971000 +0000", updated_at: "2024-02-29 ...
irb(main):002> claims.length
=> 3436
irb(main):003> overday = claims.select { |c| c.created_at - c.itf_datetime > 1.day }
=> [#<SavedClaim::Pension id: 8914640, created_at: "2024-04-30 02:41:16.683799000 +0000", updated_at: "2024-04-30 ...
irb(main):004> overday.length
=> 821
irb(main):005> overday = claims.select { |c| c.created_at - c.itf_datetime > 1.day || c.created_at.day != c.itf_datetime.day }
=> [#<SavedClaim::Pension id: 8914640, created_at: "2024-04-30 02:41:16.683799000 +0000", updated_at: "2024-04-30 ...
irb(main):006> overday.length
=> 986
irb(main):007>
```
total: 3436 (only authenticated submissions)
over 24hrs: 821
‘next day’: 986 (includes over 24)

**Comment by wayne-weibel** [comment]
> Hmmm ... our last Sprint Deck listed 3897 submitted claims, 500 or so higher, curious on the source of the difference.

These counts are only using authenticated submissions.  The counts line up (not exact due to timing) with authenticated submissions since the report - @201 + previous total of 3241 (authenticated) = 3442

**Comment by matt4su** [comment]
BA is indicating that they can validate those other statuses (e.g. closed/cancelled) if we can provide the claim numbers or Veterans IDs.  Are those data elements we can provide?  (presumably for the 'next day' including over 24 hour subset)

**Comment by mjknight50** [comment]
Let's roll this over and @matt4su and  @wayne-weibel are back and on the same page.
