### ISSUE TITLE
ARM June Metrics Report

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#87050]
## Issue Description
Reporting on June ARM metrics.

## Acceptance Criteria
- [x] Update Excel sheet with GA4 metrics.
- [x] Create report for monthly reporting against OKRs.
- [ ] Share with team for feedback.
- [ ] Share with stakeholders.
- [ ] Finalize OKRs to recommend to Jen/Lesley

**Comment by jfinnerty13** [comment]
Created ticket to track June metrics. Will update the Excel sheet with GA4 metrics, then thinking adding to the Excel sheet the OKRs OR a PPT. I'm leaning PPT so ya'll can drop into presentations, but which would you prefer @oddball-lindsay ? Thinking OKR per slide then the metrics month to month on that slide?

**Comment by oddball-lindsay** [comment]
Nice @jfinnerty13!  Considering how the consumers of this information are our stakeholders, the presentation format seems really great.  Let's try it!  We could use our leadership syncs to review at the start of each month.

**Comment by jfinnerty13** [comment]
1. PPT first draft done
2. Updated Excel sheet with new GA4 metrics https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?usp=sharing
3. Need to have larger conversations on final OKRs on widget
Thanks!

**Comment by oddball-lindsay** [comment]
Took a pass over everything and left some comments, but agree that a larger conversation would be helpful for faster alignment!
