### ISSUE TITLE
Analytics Implementation or QA Support for Cartographers – Outbound link tracking for myhealth.va.gov subdomain

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#87061]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Carographers

- **Poduct Name**

    - MHV Home and MHV tools
      
- **When is the launch date?**
    - live (6/17)

- **Provide the link(s) for Product/Page urls**
  
    - /my-health/ and child pages under that path (or just enable this sitewide)

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - Track as an Outbound Click any click on a link whose href is in the `myhealth.va.gov` subdomain. Particular links of interest include the three instances of links whose text reads "Go back to the previous version of My HealtheVet"

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Any user with health data would work, e.g., user 11, user 41, user 0

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
@wesrowe -- thanks for submitting this, and confirming we have this on our backlog. We'll notify you once we pull this into a sprint, and will reach out if we have any questions.

FYI @Blivaditis

**Comment by wesrowe** [comment]
cc @rbsingleton

**Comment by johnny-jesensky-adhoc** [comment]
From refinement -- will likely need to reference how this will set-up in MyVA.

**Comment by Blivaditis** [comment]
Hi @wesrowe The tracking for outbound link clicks has been added and verified for /my-health/. Here is a [link](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/T5MhNVW9QgGHezaVR_bfyw) to a Google analytics dashboard showing the new tracking.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks @Blivaditis -- moving this to _Done_.

FYI @jestutt
