### ISSUE TITLE
10-7959f-2: add 'same as' address screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#87062]
- Add new ‘same as’ address screen after mailing address screen
- if yes, go to next screen (skip home address screen)
- if no, show home address screen
Figma link: https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)

**Comment by reiting** [comment]
This has been done and the PR is currently in team review. It didn't have points, so I added it.

**Comment by reiting** [comment]
@marywang2 this is done and should be ready for review in staging.

**Comment by marywang2** [comment]
@reiting this doesn't match the original figma, but I think it actually reads better/make more sense. @brian-wilke will update the figma to match this one, I will create a change ticket to make the same change on FMP reg. Thanks!
