### ISSUE TITLE
Need to update Slack notification for content editors Publishing code through Drupal   

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8706]
## User Story or Problem Statement
Right now the alerts in slack are confusing for anyone looking at them. We haven't changed these alerts since the workflow switched. 

The content deploy alerts look the same as the daily deploy alerts look the same (they are the same job). The notification needs to be made clear so people can understand what the alerts mean. 

Ref: https://dsva.slack.com/archives/C0MQ281DJ/p1588421347122400

## Acceptance Criteria
- [ ] _When a content deploy happens we need to say something along the lines of "a content deploy is happening in X minutes"_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Closing. If this is needed, will revisit.
