### ISSUE TITLE
Handle STS timeouts

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#87087]
## Issue Description
Some requests to the MAP STS service result in a timeout. These errors need to be logged and handled by the service object responsible for making the calls.

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] AC1
- [ ] AC2

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dickdavis** [comment]
Changes made and merged.

**Comment by parkerbees** [comment]
@dickdavis is this still being monitored or can this be closed? Thanks!
