### ISSUE TITLE
Rotate sign-up-service-localhost and sign-up-service-lowers certs

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#87106]
## Issue Description. 
Prepare sign-up-service-localhost and sign-up-service-lowers certs for rotation within 30 days of expiration.

Rotate cert once proper PoCs are notified

## Acceptance Criteria
- [] Download new cert(s) from Certsmgr
- [] Reach out to PoCs for availability
- [] Relay and coordinate actions with team
- [] Upload new cert to login.gov developer's portal
- [] Rotate cert(s)
- [] Ensure cert viability

**Comment by parkerbees** [comment]
moved to jira, closing
