### ISSUE TITLE
Rotate Prod-sign-up-service-token-signing-prod.pem

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#87107]
## Issue Description. 
Prepare Prod-sign-in-service-token-signing-prod.pem for rotation within 30 days of expiration.

Rotate cert once proper PoCs are notified

## Acceptance Criteria
- [x] Download new cert(s) from Certsmgr
- [x] Reach out to PoCs for availability
- [x] Relay and coordinate actions with team
- [] Rotate cert(s)
- [] Ensure cert viability

**Comment by parkerbees** [comment]
Copied to JIra, closing here
