### ISSUE TITLE
Past Appointments do not show which facility. 

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8710]
## What happened?
Based on Marcy's testing, Past Appointment cards do not show Facility 

" I have no idea if the appt is at CHYSHR or DAYTSHR.  Very confusing."

## Desired behavior
Card information should be same as card information on "Upcoming appointments" page for providers

## Acceptance Criteria
- Show facility and doctor/provider name on appointment card

**Comment by jbalboni** [comment]
It looks like there's a bug that's breaking the facility info fetch in some circumstances. You can see it clearly if you refresh while on the past appointments tab, though it happens if you just switch to that tab from upcoming appointments

![Screen Shot 2020-05-05 at 2.46.00 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/9a8afa95-e5f8-4c02-a8b5-313a0f5c072a)

**Comment by jbalboni** [comment]
This was the result of bad CDW data, which had duplicate site/clinic combinations coming back from the clinics service we call. Kevin Todd cleaned up the data and this appears to be working now.

We could add some defensive code to try to handle this better on the FE, but given that the bad data a pretty clear violation of the basic assumption we make about site and clinic ids, I think I'd rather have the error come up in our logs so we can raise it to the right folks.

Slack conversations:
https://vappgteam.slack.com/archives/CFCQT5XJL/p1588788228153800
https://vappgteam.slack.com/archives/CFCQT5XJL/p1588803038183000

JIRA ticket:
https://issues.mobilehealth.va.gov/browse/CDW-410

**Comment by lenaecb** [comment]
@jbalboni - because of the CDW data, is that why all cards are now looking like this?
![Screen Shot 2020-05-11 at 10.33.44 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/4f7ef5d5-a8e1-40b5-94f2-43de65e09fcc)

**Comment by jbalboni** [comment]
@lenaecb No, that appears to be due to some error happening with the facility api in staging: https://dsva.slack.com/archives/CBU0KDSB1/p1589208375327800
