### ISSUE TITLE
AWS access for Tyler Coleman

### ISSUE THREAD

**Issue by tycol7** [department-of-veterans-affairs/va.gov-team#87113]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Tyler Coleman

### Your Email

tyler.coleman@oddball.io

### Team, Role, and Company of the target individual

Team Dash, Senior Software Engineer, Oddball

### Product Manager (PM) name and email

Kayla Wantanabe, kayla.watanabe@adhocteam.us

### Product Owner (PO) name and email

Janet Coutinho, janet.coutinho@va.gov

### Desired AWS Access

- Lighthouse developers IAM
- `dvp-developers`

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![transmittal-notice](https://github.com/department-of-veterans-affairs/va.gov-team/assets/512195/d750afd9-e663-46ef-917d-650c5d4fe8fd)

### Additional Notes

Ongoing access needed for job duties (software engineer on Lighthouse program).

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by tycol7** [comment]
May also need `dvp-developers` access (please see my teammate's previous request https://github.com/department-of-veterans-affairs/va.gov-team/issues/60180). cc @FonzMP

**Comment by tycol7** [comment]
@flooose I see the `NOT YET` label on this request - is there anything I can do to unblock it? cc @FonzMP

**Comment by cilestin** [comment]
@flooose @department-of-veterans-affairs/va-platform-cop-devops  There was a revert (#14500) of Tyler's access but we can't see anything that will renew his access - is there anything special we need to do to get this to happen? He's been waiting for access for a number of weeks at this point 😿

**Comment by tycol7** [comment]
@flooose @department-of-veterans-affairs/va-platform-cop-devops I am in Atlas and recently got access to [ArgoCD](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87144) and [Sidekiq](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87145). Is there anything else I can do to get AWS access? Thank you. cc @cilestin @FonzMP
