### ISSUE TITLE
Project Kickoff VR&E CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8711]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **eBenefits** attendees (as listed below)
- [x] VSP <> **eBenefits** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/README.md)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **eBenefits**
- Product Manager (required): **Jason Wolf - jwolf@governmentcio.com**
- DEPO Product Lead (required): **Steve Kovacs - steven.kovacs@va.gov**
- VFS team (recommended): **James Adams**, Designer/ Researcher - jadams@governmentcio.com

## Scheduling
Preferred dates or times: Thursdays/ Friday: afternoons to accommodate west coast time zones

**Comment by meganhkelley** [comment]
Scheduled for 5/8 @ 2 pm
