### ISSUE TITLE
Flipper UI access for Jonathan VanCourt

### ISSUE THREAD

**Issue by jvcAdHoc** [department-of-veterans-affairs/va.gov-team#87118]
### Your Name

Jonathan VanCourt

### Your GitHub handle (Flipper UI access is managed through GitHub)

jvcAdHoc

### Team, Role, and Company of the target individual

Lighthouse Team Dash and Accredited Representation Management, software engineer, Ad Hoc

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by lindsay-insco** [comment]
Access to `staging` granted.
