### ISSUE TITLE
UX: Update 404 to mimic USWDS version

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#87127]
## Description
Update the design of the 404 React page to approximate the USWDS 404 design as closely as possible. 

### User story

As a Veteran, I want to see a consistent and helpful 404 page across the VA.gov site so that I understand when something I am looking for is not available, and see next steps on how else I might be able to move forward in finding what I am looking for. 

### Notes
- [Link to the experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2912)
- [Link to CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85865)
- [Link to figma file](https://www.figma.com/design/UTdcimZvoNyt5yEtIocNiP/404-redesign?node-id=0-1&t=HlJBLf3Y96RRRvbJ-1)
- Following Carlos' creation of a 404 page for React apps, we recognized some a11y issues with the sibling Drupal version that we wanted to remedy. A few of those changes were made in previous tickets, and a few outstanding a11y changes were still out there.
- On 6/27/2024, UX team presented the 404 React version to the Design System Council, who approve of 1.) governing a single 404 design and 2.) agree that our team can suggest improvements that should be consumed by the team responsible for the Drupal version. 
- So, rather than simply fix the problems with the original Drupal design, they are asking us try and replicate the USWDS 404 version wherever possible, and re-connect with them when we are ready to contribute that design. 

Possible tasks:
- [x] UX: Redesign the 404 page in Figma to mimic the [USWDS 404 page](https://designsystem.digital.gov/templates/404-page/)
- [x] UX: Resubmit this design to DSC via the experimental design process
- [ ] Dev: Implement the design

## Acceptance criteria
- [x] 404 updates are reflected in Figma with a11y annotations
- [x] DSC ticket has been filed (or DSC meeting attended) for approval

**Comment by fmccaf1** [comment]
I reached out to Carol Wong from DSC to ask for the right process to move forward and she requested that I take the design through the CAIA review process.

**Comment by fmccaf1** [comment]
[I reopened the CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85865)we used back this summer when we first tried to send a 404 design through DSC.

**Comment by fmccaf1** [comment]
I have let Carol Wong know that the design is complete from my/our POV; I wrote that we've received CAIA and a11y feedback and that I was passing it off to them (in experimental design ticket). Carol gave me a thumbs up so I think we can retire this ticket and open a new one if the DST has more needs or wants our team to implement. cc: @wesrowe
