### ISSUE TITLE
Remove feature toggle: mhv_helpdesk_information_enabled

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#87130]
Now that this feature toggle is at 100%, it can be removed.

- [ ] Remove feature toggle from `vets-api`
- [ ] Remove feature toggle from `vets-website`
- [ ] Merge changes and wait for changes to propagate to envs.
- [ ] Run `Flipper.remove(XXX )` in development (dev.va.gov).
- [ ] Run `Flipper.remove(XXX)` in staging (staging.va.gov)
- [ ] Run `Flipper.remove(XXX)` in sandbox
- [ ] Run `Flipper.remove(XXX)` in production (va.gov)

[VA Platform docs: Removing old/unused feature toggles](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)

**Comment by carlosfelix2** [comment]
> @carlosfelix2 I still see the flipper toggles in all the environments listed above in the description of this ticket: dev, sandbox, staging and production. Example screenshots below
> 
> dev: <img alt="Screenshot 2024-07-25 at 7 54 47 AM" width="1502" src="https://private-user-images.githubusercontent.com/160943382/352165547-4e83cee2-f499-435c-8788-dee130e0d884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjM4MjMsIm5iZiI6MTcyMTkyMzUyMywicGF0aCI6Ii8xNjA5NDMzODIvMzUyMTY1NTQ3LTRlODNjZWUyLWY0OTktNDM1Yy04Nzg4LWRlZTEzMGUwZDg4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNjA1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2RlOWUxODA5YzkyODdkNWE3YmUzNzhlYmMyOWFiYWVmMTQyZDMxNTkwMmM4NDAyNjcyMjE2YjE1YWQ1NTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lAuBUTrqFNtvy3g8kO6dRukZ5xc27IHNwIMzI54OKHw">
> 
> staging: <img alt="Screenshot 2024-07-25 at 7 54 57 AM" width="1506" src="https://private-user-images.githubusercontent.com/160943382/352165654-14a10906-3995-4c85-b111-e35871632a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjM4MjMsIm5iZiI6MTcyMTkyMzUyMywicGF0aCI6Ii8xNjA5NDMzODIvMzUyMTY1NjU0LTE0YTEwOTA2LTM5OTUtNGM4NS1iMTExLWUzNTg3MTYzMmE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNjA1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZThjMmQ2Njk3NTUxN2Y4NzI2OWJhMTNhYjA4ZmI4YzM3ZmU0NDNlODgyZGRlMGIyOWUzM2YzNjliNjYyYzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kCPCtsKkEoe8PuzUnH8Mr1ijZv6PMalnXR-3EYXfD4A">

I'll ask Richard to remove those once I get the Sec Nav in there too.

**Comment by allanto-ah** [comment]
Environment: Staging, Production

Verified that the flipper toggles have been removed from all environments.
