### ISSUE TITLE
Remove feature toggle: mhv_secondary_navigation_enabled

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#87134]
Now that this feature toggle is at 100%, it can be removed.

- [ ] Remove feature toggle from `vets-api`
- [ ] Remove feature toggle from `vets-website`
- [ ] Merge changes and wait for changes to propagate to envs.
- [ ] Run `Flipper.remove(XXX )` in development (dev.va.gov).
- [ ] Run `Flipper.remove(XXX)` in staging (staging.va.gov)
- [ ] Run `Flipper.remove(XXX)` in sandbox
- [ ] Run `Flipper.remove(XXX)` in production (va.gov)

[VA Platform docs: Removing old/unused feature toggles](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)

**Comment by allanto-ah** [comment]
Environment: Staging, Production

Verified that the flipper toggles are removed from all environments. Feature is still working as expected.
