### ISSUE TITLE
Implement new chatbot CTA on coronavirus FAQs page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8714]
# User story

As a Veteran, I need an easy way to get timely answers to my questions about the coronavirus and how it may impact my VA health care, benefits, and other services.

# Details

## Goal
Work with chatbot team to implement a new design treatment to the VA coronavirus chatbot CTA on the [coronavirus FAQs page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/).

## Process steps to completion

- [x] Chatbot team to upload mock-up (Todd)
- [x] PW team to assess implementation needs (Stephanie, Danielle, Randi, Nick or Kelson)
- [x] PW team to implement 
- [x] Todd to validate in preview
- [x] Nick or Kelson to remove existing cta in coordination with published Drupal page
- [x] PW team to publish
- [ ] PW team and Todd to validate on live site

## Acceptance criteria

- [x] Attached to epic
- [x] Labeled with team
- [x] Labeled with practice area
- [ ] All steps above completed

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx. @toddstanich is going to upload a mockup of the new design treatment for the VA coronavirus chatbot on the faqs page. Then we'll need to assess whether this is something @RLHecht can do in Drupal or if we'll need help from Nick and/or Kelson (I think the latter due to the design component, but will wait to check with you before we assign). Thanks!

**Comment by toddstanich** [comment]
Attached mockup below. This is using the "Featured content" design system component.

![FAQ-chatbot-CTA.png](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/7c7da851-7c9c-4a13-8b0b-3b2218178589)

**Comment by stephorkandatx** [comment]
@kelsonic and @ncksllvn would love your eyes on this. 
The current implementation can be seen at https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ . 
The goal is to incorporate the "Featured content" design system component, to the chatbot CTA. 

Would this be a FE task, or would you recommend it be set up via Drupal by Randi or another content team member?

**Comment by ncksllvn** [comment]
That looks like this to me -

The blue background is applied via the `fieldFeaturedContent` on a page, like [this](https://staging.va.gov/health-care/about-va-health-benefits/) for example.

Then the content is just a WYSIWYG, with a link styled as a button like -

```html
<a class="usa-button-primary" href="/coronavirus-veteran-frequently-asked-questions/ ">Go to the chatbot</a>
```

See the button-link `Track the status of your claim` on https://staging.va.gov/disability/how-to-file-claim/ for an example of that.

If this is possible via Drupal, then no dev work required

**Comment by RLHecht** [comment]
I am able to style the blue button in the featured content field in Drupal. It would just sit above the "On this page" section.

**Comment by DanielleThierryUSDSVA** [comment]
Just noting here that we don't need JTF approval for this update.

**Comment by RLHecht** [comment]
Chatbot was added to the FAQ like design above.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @toddstanich. Are you able to access the VA network? If yes, could you validate the chatbot cta treatment in preview?  

preview-prod.vfs.va.gov/preview?nodeId=3014

If you can't view preview, here's a screenshot. Thanks!

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b7f6e914-3b5d-473a-9a6d-70731a38c0d3)

**Comment by toddstanich** [comment]
@DanielleThierryUSDSVA I'm not able to access the network, but the screenshot looks good, thanks! Also confirming that this replaced the current CTA? Or do we need to coordinate something separate to remove that?

**Comment by DanielleThierryUSDSVA** [comment]
@toddstanich Excellent question, thanks! That was added outside of Drupal, so I do think we'll need to coordinate removing that separately, yes. I'll add that as a step above and reach out to the team about how to make that happen before this cta goes live. Thanks again!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ncksllvn @kelsonic. Would you be able to help us coordinate the removal of the existing chatbot cta that's coded in one or both of the below, with the publishing of the new cta that will live in Drupal? We'll want to wait until we're ready to publish the Drupal update. I'm hoping we'll be able to publish the new cta in this afternoon's deploy, but waiting on jtf approval of some other changes that are also in the Drupal draft page...so I can check in around 12 or 1 p.m. with an update. Thank you!

[1]https://github.com/department-of-veterans-affairs/vagov-content/blob/master/pages/coronavirus-chatbot.md
[2] https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/coronavirus-chatbot (edited)

**Comment by ncksllvn** [comment]
The link is removed! https://dsva.slack.com/archives/C52CL1PKQ/p1588777686353300

**Comment by RLHecht** [comment]
Thank you, Nick! The FAQ page was published with new Chatbot link in the featured content. Moving to validate.

**Comment by stephorkandatx** [comment]
Accidentally closed this - we will validate this work today
