### ISSUE TITLE
0781 Research Prep

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#87147]
We are getting ready to conduct research for 0781 concept test. There are a couple of items that need to be taken care of before research happens.

Task:
- [x] Finalize questions for the recruitment conversation with Perigean
- [x] Review the Trauma-informed checklist and determine what needs to be done before the study
- [x] Draft questions for Rachael
- [x] Sign up sheet for participants
- [x] Intro email statement, phone screener statement and study name change to be send to Perigean 
- [x] Update notetaking templates and conversation guides (after reviewing prototypes with Jina)

Acceptance Criteria:
- [x] Complete the above task and update the ticket with the status

**Comment by nnicholas7** [comment]
[Perigean Recruitment Meeting Agenda](https://docs.google.com/document/d/1imv9qmVXEhDcRqaSyaGOoxfG99xD8SI8wWatyS8Khxw/edit)

Trauma-informed [checklist](https://docs.google.com/document/d/1yBiUY6BHuXnqr_AjvRYmxM-fEc33ZFWVtzcQMyLL-5Y/edit) of items to be done before the study

**Comment by nnicholas7** [comment]
Recruitment
Study name change and email and phone blur were sent to Maria as requested from our touchpoint meeting this morning. We have also changed our availability for interviews to: Monday-Friday 10am-12p and 1-5pm ET.

**Comment by nnicholas7** [comment]
- Created an [observe sign up sheet](https://docs.google.com/spreadsheets/d/1OlO96NpSGPnFGPAxGAWbjfuBO0WQRF-NuklDwP5b2nY/edit?gid=0#gid=0). Also added the Research strategies as a tab so we don’t forget to complete this document as we do the research

**Comment by juliepedtke** [comment]
For the trauma-informed checklist, let's keep that unchecked and keep this ticket open until those items have been completed (debriefs have been scheduled, etc)

**Comment by nnicholas7** [comment]
There are a couple of items in the trauma-informed check list that an only be completed after the interviews are scheduled (ie. scheduling debriefs) so this box will remain unchecked until that is done. 

I was able to update the notetaking template V1 and V2 to reflect the current Figma file and make changes to V1 conversation guide.

**Comment by juliepedtke** [comment]
Let's only check things off the task list once they are complete - so sign-up sheet is awaiting the schedule from Perigean, so shouldn't be checked yet.

**Comment by juliepedtke** [comment]
I'm seeing 6 threads in the trauma-informed checklist that still require attention:

- [ ] Scheduling debriefs
- [ ] Decide on our approach to Rachael joining sessions - do we tell participants we have a social worker joining, or treat it like any other observer with an intro?
- [ ] Write up what resources we'd like to share (through Perigean) after the sessions
- [ ] Add ongoing consent check after break in both conversation guides
- [ ]  Checklist for solo debrief for team wellbeing
- [ ]  Determine approach for recognizing distress (it might be covered by existing resources)

**Comment by nnicholas7** [comment]
- Debriefs have been scheduled for interviews happening July 15-19 from 1-2:30p.  I will continue to check the calendar and add debriefs as interviews come in.
- Approach to Rachael- I think we should tell participants that a social worker is joining the conversation. That way if something doesn't happen it's not weird to find out that a social worker is on the line. Maybe Rachael could give more insight into best practices for how this would work
- Resources for after the session- currently working on [draft](https://docs.google.com/document/d/1nkX_4ykk2qq0UBRAiNZH4yVZrDLjRqkVL4jQkAiNJrM/edit).  Double checking resources and should be able to hand off today for a second look
- I think we can use the exiting resources for recognizing distress.

**Comment by juliepedtke** [comment]
Thanks for the update!

1. I'm missing a debrief for Thursday the 18th, was there a reason to skip that day? (We typically have our weekly sync with Rachael on Thursdays but that has been canceled because she is traveling)
2. Love the idea of asking Rachael about that approach. Can you add it to our [agenda](https://docs.google.com/document/d/1hlfZduVl_1ktmjx8BJfLJiHYmiX0MLoX3hC4cDXgFcs/edit?pli=1) for later today so we don't forget?
3. Resources after the session - sounds great, will take a look later.
4. Recognizing distress - ok I agree, let's note this on the comment thread in the doc and resolve that comment so the decision is documented.

**Comment by juliepedtke** [comment]
You haven't yet addressed two of the items I mentioned:

- [ ] Add ongoing consent check after break in both conversation guides
- [ ] Checklist for solo debrief for team wellbeing

**Comment by nnicholas7** [comment]
- Add an on-going consent check and awaiting review. I added it to the V1 conversation guide. Julie has approved and moved the change into both guides
- Debrief document with solo debrief is awaiting two to go. 
- Debrief sessions have been scheduled for all interviews on the calendar.  
- Thank you/resources letter has been created and awaiting Julie's 2 to go. 
- Sign up sheet is awaiting 2 to go and for our team to sign up for moderator positions before we send out to others.

**Comment by juliepedtke** [comment]
I gave feedback on the signup sheet - would like you to add Rachael in please!

**Comment by juliepedtke** [comment]
Notes from our live call...

- We decided that the moderator's only responsibility is to watch the zoom chat for (private) DMs about timekeeping. The notetaker will keep time and send reminders to the moderator on zoom. The notetaker will also keep an eye on the Slack thread and relay any questions that observers have. This should be noted in our intro blurb that we send ahead of each session on the feedback Slack channel.
- Edit intro blurb with observer instructions (for Slack, 30 minutes ahead of sessions)
- Write intro blurbs for [sign-up sheet](https://docs.google.com/spreadsheets/d/1OlO96NpSGPnFGPAxGAWbjfuBO0WQRF-NuklDwP5b2nY/edit?gid=584334505#gid=584334505) with context on the study, and same observer instructions
- Update the notetaking Mural with edits to conversation guides (both V1 and V2)

**Comment by nnicholas7** [comment]
- [ ] Add obervers/notetakers to the calendar invites

**Comment by nnicholas7** [comment]
- Slack intro blur that will be sent 30 mins before each interview can be found here[https://docs.google.com/document/d/1O9zIOut6Uk8nzxfFA6zHkLbKCkrpI0n7AnU3dZ3P5DU/edit](url)
- Intro blur for sign up sheet- 1st pass has been taken

**Comment by nnicholas7** [comment]
- V1 and V2 of conversation guide are up to date with changes from their respectively conversation guides

**Comment by nnicholas7** [comment]
Made some updates to the debrief activity in the Mural board. I also think that we should send out the 'Decompress Technique' in the Slack when we have difficult interviews, but open for discussion. 

Made updates to the thank you letter and included Ruben's suggestions.

**Comment by juliepedtke** [comment]
Just looked at the thank-you note together. Next steps:

- [ ] Find example of thank-you note from Perigean. Check Monday sync recording when Perigean last joined. 
- [ ] Share our [draft letter](https://docs.google.com/document/d/1nkX_4ykk2qq0UBRAiNZH4yVZrDLjRqkVL4jQkAiNJrM/edit?usp=sharing) along with Perigean's template with Rachael for feedback (can be async in shared channel, cc Shannon).

**Comment by nnicholas7** [comment]
Question for Rachael: We drafted this, want to know if there are other resources

**Comment by nnicholas7** [comment]
Draft thank you letter was shared  with Perigean for review and feedback.

**Comment by nnicholas7** [comment]
All above task for this ticket have been completed.
