### ISSUE TITLE
[DOCUMENT]: GIBCT Section 116 - Excel document SHOULD NOT have merged cells

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#8715]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

VA 508 office has identified the [Excel Download Data on All Schools](https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx) has some merged cells. This can interfere with screen readers' ability to interpret the page. I'll add specific tabs and cell identifiers below.

**Quick Facts tab**
* Row 1
* Row 8
* Row 10
* Row 13
* Row 19
* Row 23
* Row 24
* Row 29

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* [ ] No cells show as merged
* [ ] Groups have proper headings, and columns have proper headings

## WCAG or Vendor Guidance (optional)

* [Penn State University Excel Tips](https://accessibility.psu.edu/microsoftoffice/excel/)

## Screenshots or Trace Logs

![Screen Shot 2020-05-04 at 3 15 02 PM](https://user-images.githubusercontent.com/934879/81009491-5edc2100-8e1a-11ea-83ec-7c1ee438ba89.png)

**Comment by TamGIBill** [comment]
Brian Grubb replied to me this has been addressed.

**Comment by desireeturner** [comment]
@1Copenut This is ready for your review

**Comment by 1Copenut** [comment]
@desireeturner I took a look and the merged cells all look to be fixed. I'll pass this along to the VA 508 office for final approval.

**Comment by dneel-bah** [comment]
@1Copenut Any update on this issue?

**Comment by af-manish** [comment]
@noahgelman  Can you check the above and see where we stand on the fix?
