### ISSUE TITLE
Update Address fields to not require street and postal code

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#87156]
#### Problem Statement

The below design and functionality is what is needed for the Place of birth page:
<img width="1014" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--740cc39fd42d1f52054d02e401e89013c2c1d687/Screenshot%202024-06-28%20at%209.02.02%E2%80%AFAM.png" alt="Screenshot 2024-06-28 at 9.02.02 AM.png" />
When this was implemented using the addressNoMilitaryUI like this:
```
/** @type {PageSchema} */
export default {
  title: 'Place of birth',
  path: 'place-of-birth',
  uiSchema: {
    ...titleUI('Place of birth'),
    placeOfBirthAddress: addressNoMilitaryUI({
      omit: ['street', 'street2', 'street3', 'postalCode'],
    }),
  },
  schema: {
    type: 'object',
    properties: {
      placeOfBirthAddress: addressNoMilitarySchema({
        omit: ['street', 'street2', 'street3', 'postalCode'],
      }),
    },
  },
```
the UI looked correct and no errors occurred but the data was not being submitted in the POST. When this was implemented:
```
export default {
  title: 'Place of birth',
  path: 'place-of-birth',
  uiSchema: {
    ...titleUI('Place of birth'),
    placeOfBirthAddress: addressNoMilitaryUI({
      omit: ['street2', 'street3'],
    }),
  },
  schema: {
    type: 'object',
    properties: {
      placeOfBirthAddress: addressNoMilitarySchema({
        omit: ['street2', 'street3'],
      }),
    },
  },
```
the UI no longer matched the designs because it included street and postal code, but the data was being submitted. We need to update address fields including addressNoMilitarySchema to not require street and postal code.

#### Implementation Details

- Verify this is not possible with the current state of the Forms Library
- Inquire with the Forms Library Tools teams about this feature proposal and whether they can add it or we can add it (and they review it)
- With this issue, track the issue if they are adding the feature or implement the feature if we are adding it

#### Mockups/Designs

https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=1026-23223&t=AsHeVzwsGF99GfRd-4

### Acceptance Criteria

- [x] Address fields do not require street and postal code to submit data with the POST
- [x] Place of birth matches the above design
- PR - [ARF 87156 Update Address for Place of Birth](https://github.com/department-of-veterans-affairs/vets-website/pull/31102)

**Comment by ndsprinkle** [comment]
Hey @williamphelps13, do you try to use `omit` in the UI pattern as well? In your code examples, I only see `omit` being used in the `schema`. That may be the issue here.
