### ISSUE TITLE
0781 Research Synthesis

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#87154]
Synthesis of our findings from the 0781 Concept Testing interviews.  The synthesis process will be conducted on Mural and will help us understand how Veterans approach the 0781 and inform design prioritization. 

Task:

- [x] Prep! Review resources
- [x] Prep! Outline framework for synthesis (with input from Ruben and Julie), including steps we will take and a outline in Mural of where those steps will happen
- [x] Prep! Go through first interview notes to test synthesis framework. Review as a team and discuss any adjustments.

- [x] Pull in participant data to synthesis board
- [x] Conduct synthesis
- [ ] Tag other teams that may be relevant to the session
- [ ] Build final report

Acceptance Criteria:
- [x] Prep completed
- [x] Research synthesis is completed
- [ ] Final report is completed

**Comment by nnicholas7** [comment]
Met with Ruben to review the synthesis plan and receive resources. Currently reviewing resources to create the framework for synthesis.

**Comment by nnicholas7** [comment]
Reviewed  the synthesis board with Ruben and Julie to chat about changes/updates. Updates have been made. Codebook will be updated on a rolling basis as we come up with codes while reading the data.

**Comment by nnicholas7** [comment]
Codebook has been updated in the Google Doc and tags have been transferred to Mural.  On Monday, we had a team member around synthesis and how we would go about the process and will use the rest of this sprint to conduct the synthesis process.

**Comment by jinaryu** [comment]
**8/5**

- [ ] Final pass Goal 1 (Julie and Jina)
- [ ] First pass Goal 2 (Nichole and Ruben)

**Tomorrow 8/6**

- [ ] Final pass Goal 1 (Julie and Jina)
- [ ] First pass remaining Proto A (Jina)
- [ ] First pass Goal 3 (Nichole and Ruben)

**Wed 8/7**

- [ ] 2nd pass Goal 2 (Julie)
- [ ] First pass remaining Proto B (Jina)
- [ ] 2nd pass Proto A (Ruben)

_Nichole ooo_

**Thurs 8/8**

- [ ] 2nd pass Goal 3 (Julie)
- [ ] 2nd pass Proto B (Nichole and Ruben)
- [ ] Final pass on Goals 2-3 (Jina)
- [ ] Preview draft with Rachael + Shannon 

**Friday 8/9**

- [ ] Final pass on both Protos (Julie)
- [ ] Start drafting report OR…
- [ ] Finishing synthesis 

**Monday 8/12**	

- [ ] Clean up draft (word doc? deck?)
- [ ] Share draft with Shannon (+ Rachael) by EOD on Monday the 12th

**Tues 8/13**

- [ ] Shannon - 24 hours to review
- [ ] Team works on deck in the meantime

**Wed 8/14**

- [ ] 24 hours to incorporate Shannon’s feedback (Wed 8/14)
- [ ] Final updates to deck

**Readout ~15th**

**Comment by jinaryu** [comment]
**Link to running 0781 synthesis notes**

**Comment by nnicholas7** [comment]
Update: Research synthesis is completed. The team has begun to add findings, how might we, and recommendations (for some findings) into a deck. The deck will be shared with Shannon before our read out on Aug 15.
