### ISSUE TITLE
10-7959f-1: Update intro and review page - button text

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#87183]
Update intro page to match the [figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=1628-25393&t=T2mHOr8baXcFjNcm-0) for the intro and review pages - it should say 'Sign in to start your form" (instead of 'application')

**Comment by marywang2** [comment]
fyi @brian-wilke (in case there are other changes to this page in UAT)

**Comment by reiting** [comment]
I have created a PR for this and it is currently in team review. 

<img width="769" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52ded94594e9029eca682f68e84beca63aa38ce0/Screenshot%202024-07-18%20at%201.38.47%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 1.38.47 PM.png" />
<img width="657" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cbafaed27ba2fa71bf79f9a089b46cec2e5778f/Screenshot%202024-07-18%20at%201.39.01%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 1.39.01 PM.png" />
<img width="728" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWp3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c0eea5133cf40886002558d1846d1337a30fa66/Screenshot%202024-07-18%20at%201.39.07%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 1.39.07 PM.png" />
<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXJ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cd52081ad1659b02d1ee98ccaa6977dbc61a1d5/Screenshot%202024-07-18%20at%201.45.52%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 1.45.52 PM.png" />

**Comment by reiting** [comment]
@marywang2 this is ready for review.

**Comment by marywang2** [comment]
This looks good to me @reiting. Ccing @brian-wilke for awareness.
