### ISSUE TITLE
10-7959f-1: move explanatory copy for pre-fill to info screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#87187]
As a user, I want to know at the beginning, when I start the FMP registration, where my information is being updated so I know where the changes apply.

[Figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=726-21596&t=c27oYcUwiizSAgu0-0)
- display only to logged in users
- show on name/dob page only (remove from mailing address screen so user sees this earlier in the flow)

Acceptance criteria:
Given a logged in user is filling out the FMP registration
When they get to the name/dob info screen
Then they should see a message about where their information will update

**Comment by reiting** [comment]
This is in team review.

**Comment by reiting** [comment]
@marywang2 this should be ready and in staging by now. <img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFMvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6820ef69f45743206c48c52f90d2787b40e30ed/Screenshot%202024-07-05%20at%202.01.17%E2%80%AFPM.png" alt="Screenshot 2024-07-05 at 2.01.17 PM.png" />

**Comment by marywang2** [comment]
@reiting do you have a screenshot of the bottom of the page with the copy that says "Any updates you make..."? (With the feature toggle 'on' I can't check it out on staging).

**Comment by reiting** [comment]
@marywang2 this should be ready for review in staging.

**Comment by marywang2** [comment]
@brian-wilke would you please review.

**Comment by marywang2** [comment]
I'm able to view now. Let's remove the blue prefill box at the top (on this page) and the "Your application ID..." (where does that pull from?). Making the future pre-fill updates may also mean we remove the bottom copy but we can leave that where it is for now. @brian-wilke 
<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--886ad2f5303fe17742b8a7d652dbc68ded5361aa/Screenshot%202024-07-11%20at%2012.55.51%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 12.55.51 PM.png" />

**Comment by reiting** [comment]
@marywang2 to clarify, you want the blue box removed but the text to remain or the box AND the text in it gone?I have no idea where that app id number came from!

**Comment by marywang2** [comment]
A bit more investigation needed (also Rachel asking in team/dsva slack) on this one.

**Comment by reiting** [comment]
@marywang2 @brian-wilke I've done a bunch of research on this and asked around. There does not seem to be any standard way to determine if a user is logged in before arriving at the form or if they log in once they have arrived at the form. That being said, there may be a way to do it. At the moment, with just some preliminary ideas, I can't guarantee they would work or that they would be able to work consistently. The way to do it would be rather hacky, but it's POSSIBLE it will work. If you need more info than this, let me know and I can go more into it. You guys just let me know what you want me to do!

**Comment by marywang2** [comment]
For now can we remove the "Your application ID number..." sentence @reiting

**Comment by reiting** [comment]
@marywang2 <img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejNpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--151250b56c3327c7b5c236c5a8d0ecaea49d3979/Screenshot%202024-07-16%20at%207.54.33%E2%80%AFAM.png" alt="Screenshot 2024-07-16 at 7.54.33 AM.png" />

**Comment by marywang2** [comment]
I'll close this for now - we can make just that one change, thanks! @reiting
