### ISSUE TITLE
500 issues in VisitsController

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#8718]
Events in Sentry: 
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/117679/events/?query=vaos

MACM has been notified and is tracking here:
https://issues.mobilehealth.va.gov/browse/MAPSUP-920

**Comment by lenaecb** [comment]
@saneshark - looks like from the MAPSUP ticket that this is still in progress and they they are having to refactor MAS client to check for errors/partial data. 

Are you tracking this with them? Trying to make sure I understand what's in motion for our team.

**Comment by saneshark** [comment]
Yes, I'm tracking the ticket on Jira mostly. Will update here based on my comment asking about LOE for solutions.

**Comment by lenaecb** [comment]
Additional logging for this should happen with an upcoming release - 4.20.2

I am moving this to 'blocked' until the release has gone out and we've confirmed tracking. 

Link ticket for this in JIRA is - https://issues.mobilehealth.va.gov/browse/VAOSR-663

**Comment by saneshark** [comment]
This issue appears to have been resolved.
