### ISSUE TITLE
1010d signature field not populating on PDF

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#87181]
As a user, I want my signature entered on the form to show up on the generated PDF so that my application can be accepted. 

Bug description:
The signature field on the PDF for 10-10d is technically `@type="Signature`, rather than `@type=Text`. This causes our PDF filler functionality to skip over it.

Desired behavior:
The signature block should display the text entered by the signee upon generation.

Acceptance criteria:
- Generated 10-10d PDFs display the signature text entered by the user on the frontend.

**Comment by michaelclement** [comment]
Signature field metadata comparison
| 10-7959c (working) | 10-10d (not working)
| - | - |
|<img width="408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3lkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bae86f26cabb0908314429663f8ebacb485789ca/Screenshot%202024-06-27%20at%2012.21.39.png" alt="Screenshot 2024-06-27 at 12.21.39.png" />|<img width="887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c79681ff723da3ebfded4e320d1369a2129b7aeb/Screenshot%202024-06-27%20at%2012.10.11.png" alt="Screenshot 2024-06-27 at 12.10.11.png" />
|

**Comment by baltes** [comment]
Hi @michaelclement , are you able to confirm that this is resolved?

**Comment by michaelclement** [comment]
Yep! Here's a screenshot of 10-10d being stamped with a signature: @baltes 
<img width="568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc198ab5fe19827e5280f066d0cba27288ecb83b/Screenshot%202024-07-02%20at%2010.33.10.png" alt="Screenshot 2024-07-02 at 10.33.10.png" />
