### ISSUE TITLE
Vets-api terminal access for [Adrian Rollett]

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#87197]
### Your Name

Adrian Rollett

### Your GitHub handle (terminal access is managed through GitHub)

acrollet

### Your dsvagovcloud AWS user name (if applicable)

Adrian.Rollett

### Team, Role, and Company of the target individual

VA (OCTO)

### Product Manager (PM) name and email

N/A

### Product Owner (PO) name and email

N/A

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

eQIP proof in previous issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66592

I need prod access in order to debug an issue with the AVS application that is only occurring in prod.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by davidpetras** [comment]
@acrollet  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by davidpetras** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by JonathanKamensDVA** [comment]
@acrollet are you asking for persistent prod access or for prod access while you are debugging a particular issue? If the former, can you provide a bit more info about why you expect to need it moving forward; if the latter, can you give an estimate of how long you will need access for (we can always extend later if necessary, so doesn't have to be a perfect estimate). Thanks!

**Comment by acrollet** [comment]
I was trying to debug a particular issue that the backend CoP helped me with and is now resolved, so this can be downgraded to lower envs only and (I think) closed out.
