### ISSUE TITLE
Coordinate a 508 training session with the Authenticated Experience Engineering team

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#872]
Coordinate with the Engineering team, Justin, and Jose for putting together a learning session on 508 standards and best practices.

**Comment by Justin-Pickett** [comment]
@1Copenut please let me know when we can knock this training session out w/ the engineering team.

**Comment by 1Copenut** [comment]
This has been scheduled for Monday, September 23rd.

**Comment by 1Copenut** [comment]
Reschedule for Thursday, October 3rd.

**Comment by 1Copenut** [comment]
@Justin-Pickett Thank you for the flexibility to reschedule. Your team brought great questions and suggestions. I'll move this ticket to closed.
