### ISSUE TITLE
Multiple Page List & Loop Pattern Card Description

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#87212]
## Feature Enhancement Ticket

**Title:**
Enhance Multiple Page List & Loop Pattern Card Description to accept a string or a component

**Description:**
The [Array Builder Pattern(Multiple responses list & loop)](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md) pattern cards currently only support a string for the description and do not support a more detailed card description. Some implementations may want to include more information in their card descriptions. For example, the VA design system [card component example](https://design.va.gov/components/card#financial-status-report) may include a list of items:
```
const CardDescription = ({ incomeType, grossMonthlyIncome, payer }) => (
  <ul className="u-list-no-bullets vads-u-padding-left--0">
    <li>
      Income type:{' '}
      <span className="vads-u-font-weight--bold">
        {incomeTypeLabels[incomeType]}
      </span>
    </li>
    <li>
      Gross monthly income:{' '}
      <span className="vads-u-font-weight--bold">
        {formatCurrency(grossMonthlyIncome)}
      </span>
    </li>
    <li>
      Income recipient:{' '}
      <span className="vads-u-font-weight--bold">{payer}</span>
    </li>
  </ul>
);
```

**Examples:**
Card description as `string`
<img width="535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOCtlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4003506b64035ab0e0d12be14a7ef01b7bced72/Screenshot%202024-06-28%20at%209.13.42%E2%80%AFAM.png" alt="Screenshot 2024-06-28 at 9.13.42 AM.png" />
Card description as `component`
<img width="535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64591b6cf30bb51b761f59d2a89d3619aa95a716/localhost_3001_income-and-asset-statement-form-21p-0969_form-saved%20%287%29.png" alt="localhost_3001_income-and-asset-statement-form-21p-0969_form-saved (7).png" />

**Priority:**
[Low]

**Dependencies:**
[Array Builder Pattern(Multiple responses list & loop)](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md)

**Acceptance Criteria:**
The [arrayBuilderPattern](https://github.com/department-of-veterans-affairs/vets-website/blob/f35f7ab080fb6fb375c250fd6a4f9f762a38c6f6/src/platform/forms-system/src/js/types.js) card description prop accepts either a `string` or a `component`

**Testing Instructions:**
All existing unit tests pass
Button screen reader text is updated to work with string or object for Accessibility

**Additional Notes:**

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/87212?planning-poker) with Zenhub @danlim715 @TaiWilkin @ToddWebDev @wayne-weibel
