### ISSUE TITLE
FE| Profile | Ch33 Migration | Update Feature Toggles to Block BE Calls

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#87214]
## Background
We discovered our Ch33 Direct Deposit toggles are still allowing/making calls to the BE and we need to prevent those calls. 

- Related BE story is #87185 
- [mural where we determined the logic](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707938676024/48a9e34150b8a3058c8709b241373cb9515afee6?wid=0-1719588261532)

## Tasks
- [ ] comment out w evidence showing the updates working  

## Acceptance Criteria
- [ ] when the toggles are enabled (see the mural board for specifics) we should not allow the FE to make calls to the BE.

**Comment by mtcA6** [comment]
@asiisii can you plop in screenshots showing it's working ok?

**Comment by asiisii** [comment]
we are not making request to `ch33_bank_accounts` and `disability_compensations` endpoints anymore when single form toggle is turned on

<img width="1416" alt="Screenshot 2024-07-03 at 11 26 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/36644181/c6027f8b-adfb-452c-a390-703384f12f06">

cc: @mtcA6
