### ISSUE TITLE
[ExternalDNS] Records are not being created

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#87225]
## Description
ExternalDNS is deployed to clusters but is not creating records in Route53.

## Acceptance Criteria
- [ ] ExternalDNS is creating Route53 entries

**Comment by adhoc-nshipman** [comment]
Issue was resolved here: https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/pull/419
