### ISSUE TITLE
[UX/Team] 10-10EZR: Katelyn Knowledge Transfer

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#87252]
- [x] Priority Groups 
- [x] Attach docs and attach docs V2
- [x] Content process
- [x] Archer pics
- [x] Anything else
- [x] **Success: We have a good knowledge transfers from Katelyn to the rest of the team**

**Comment by katelyncai** [comment]
Adding my[ hand-off doc](https://docs.google.com/document/d/1UrWUg5F4h6UEs-cguJG1ogzmP6DccpISfS6cmVNc27s/edit) in here! @IMHieuVo to review and send over any questions. Thanks!
