### ISSUE TITLE
Qualitative Data Request: Authenticated tools

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#87261]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

05-01-2024

### Date Range End

06-28-2024

### Product Name(s)

Authenticated tools

### Product Description

These are authenticated tools that don't fit under a specific benefit. They each have a static page with information and a sign-in widget and we're looking at data on the static pages.

### Survey URL(s), key term(s), case category or type

**Only the static pages:**
va.gov/va-payment-history/
va.gov/change-address/
va.gov/change-direct-deposit/
va.gov/manage-va-debt/
va.gov/view-change-dependents

**Parameters for data:**
- Medallia feedback survey from tool static pages
    - Visitor answered "no" to whether they were able to complete their task
- Medallia intercept survey
    - Visitor rated 1 or 2 on overall experience
    - **Must include keywords: can't find**

### Sub URLs

No

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

jennifer.mayo1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by jennymayoco** [comment]
[CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60201) for this work for context

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
