### ISSUE TITLE
Dependent Card Info

### ISSUE THREAD

**Issue by tfink419** [department-of-veterans-affairs/va.gov-team#87272]
## Issue Description
_As a user, when I view my "view dependents" page on VA.gov, I want to understand more information about my dependents, so I can accurately verify them._
We can utilize the service through bgs `bgs.people.find_dependents` for a few of these details as well as information returned by `bgs.diaries.read_diaries`.

CURRENT CARD:
<img width="421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0YvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21b441d6ecc6a4e3fac66b01bed9d2404bfe3d5d/image.png" alt="image.png" />

IDEAL CARD:
<img width="660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f065187585ee185a43283908902d8c5b77593e33/image.png" alt="image.png" />
https://www.figma.com/design/bvj72inycD0iZkuCbjYTWL/Dependent-Verification-MVP?node-id=210%3A12530&t=0K9ybqS2Qs2iMvfP-1

---
## Tasks
- Add relationship type reported for each dependent (**find_dependents.ptcpnt_rlnshp_type_nm**)
- Show whether dependent is currently being awarded benefits (**find_dependents.award_ind**)
- If child, indicate when they will be automatically removed at 18
  - In **read_diaries.dependency_dec** get the **award_effective_date** for the element that has the **person_id** of the dependent and a **dependency_decision_type** of "T18" (Also possibly T23 or SCHATT[School Attendance Terminates])
- Non-relationship dependent descriptions: 
  - School Aged Child

## Acceptance Criteria
- [ ] 
---

**Comment by sortizsh** [comment]
@ajialeilani  do you know of a staging user that has dependents? can you chat with Tyler if so?

**Comment by ajialeilani** [comment]
Hi @sortizsh @tfink419 the only user I've had success logging in with is vetsgov+test239@id.me (Medge) who does have dependents based on test 686c submissions. I'll message you directly, Tyler.
