### ISSUE TITLE
SOCKS access for [Camron Martinez]

### ISSUE THREAD

**Issue by camronmartinez** [department-of-veterans-affairs/va.gov-team#87284]
### Your Name

Camron Martinez

### Your Email

martinez_camron@bah.com

### Your GitHub Handle

camronmartinez

### Your Role and Team

Assistant Product Manager on Team Ninjapigs

### Product Manager (PM) name and email

Lorri Glover glover_lorri@bah.com

### Product Owner (PO) name and email

Janet Coutinho jcoutinho@gmail.com

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDm/H8L5lAt33ZRHYJt/FpJYBUvRc0nUiZBpklPhPKiAoGoRp727UKjAr6tjY49QtdeO7l1enIocyDIeKRH+G4DrSY5sS4Eml+GGnQ0UzxJTGjw+ht6if1hU9lICmndKC6Vit0Gk3Wr0mgPFJ1OYNHJ1GwLlaDwdfo94yMFuwg1xGYkKsY2thn3Jzqm0RwXz2hHOCdEQRIfGpqjt5lbOcMtctYL9Ifo3ONS5sEyl9V0e1wPek5n8EHvUvP22nZZ4MOiO6pWHLq8yhX9K+XaziOxxLr9qfYOqX296z0gzWlk/JAVeYl7B2R+KA7e9/E1FNdGlnOtITfX+BPWZP60N8B8pzsT+nqQW3icAgt45IWzOqKbYdNxs8uA4BT3TdLkjLYgXRHAHlOUK59nnc8PYAyfD2atHgrOdkxa1cDVYwAzeerb9Q0JGGntHf5BaQ1hKlpZ9RAtNGGz1WCVaCLtc2Y/09AK9hWRHhtpd2LCgmuyMxAOQPhvElS2xhaXZV9WQ98= cmartinez@BAH5CG3333NCV

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/153761193/d0391bde-cd9d-4e94-892b-3e373f509a65)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@camronmartinez we need a screenshot of your E-QIP transmittal. It's an email that should have come from the VA. The screenshot of your ssh key is not sufficient.

**Comment by camronmartinez** [comment]
@flooose Oh sorry about that. Would that have been something that was generated while I was setting up the access? IE a recent email?

**Comment by camronmartinez** [comment]
I belive that I've found it. I've updated the request with the correct screenshot, but let me know if this isn't what you're looking for @flooose

**Comment by ph-One** [comment]
@camronmartinez Access completed.

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
