### ISSUE TITLE
[VETS-API] Bump lockbox gem (1.3.0 -> 1.3.3 or latest)

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#87288]
## Issue Description
As started in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17336), Lockbox needs to be bumped to latest, but there is a failing test. It seems like something has changed how the response is formatted, from a hash with strings as keys to symbols, causing test failures. We need to either see if we can adjust how it's formatting the keys, or determine if it's even problem.

Before:
```pending_submission.form_data
=> {"vaccine_interest"=>"INTERESTED",
 "zip_code"=>"97212",
 "time_at_zip"=>"YES",
 "phone"=>"808-555-1212",
 "email"=>"foo@example.com",
 "first_name"=>"Jon",
 "last_name"=>"Doe",
 "date_of_birth"=>"1900-01-01",
 "patient_ssn"=>"6665123456",
 "zip_lat"=>"45.544236",
 "zip_lon"=>"-122.643468",
 "sta3n"=>"648",
 "authenticated"=>true}
```

After:
```
Job::Perform>)> pending_submission.form_data
=> {:vaccine_interest=>"INTERESTED",
 :zip_code=>"97212",
 :time_at_zip=>"YES",
 :phone=>"808-555-1212",
 :email=>"foo@example.com",
 :first_name=>"Jon",
 :last_name=>"Doe",
 :date_of_birth=>"1900-01-01",
 :patient_ssn=>"6665123456",
 :zip_lat=>"45.544236",
 :zip_lon=>"-122.643468",
 :sta3n=>"648",
 :authenticated=>true}
```

```
$ rspec ./modules/covid_vaccine/spec/sidekiq/covid_vaccine/submission_job_spec.rb:16

>     Failure/Error: expect(pending_submission.form_data).to include(*expected_attributes)
         Expected { vaccine_interest: "INTERESTED", zip_code: "97212", time_at_zip: "YES", phone: "808-555-1212", email: "foo@example.com", first_name: "Jon", last_name: "Doe", date_of_birth: "1900-01-01", patient_ssn: "6665123456", zip_lat: "45.544236", zip_lon: "-122.643468", sta3n: "648", authenticated: true }
       to include "vaccine_interest", "zip_code", "time_at_zip", "phone", "email", "first_name", "last_name", "date_of_birth", "patient_ssn", "zip_lat", "zip_lon", "sta3n", and "authenticated"
```

---
## Tasks
- [ ] Determine whether we can adjust how payload is formatted, or adjust spec accordingly

## Acceptance Criteria
- [x] `lockbox` has been bumped and deployed to prod

**Comment by ericboehs** [comment]
Diff here: https://github.com/ankane/lockbox/compare/v1.3.0...v1.3.3

**Comment by ryan-mcneil** [comment]
Notes: 

Here's the [lockbox diff](https://my.diffend.io/gems/lockbox/1.3.0/1.3.3). The first changelog note in 1.3.1 and the changes in serialization in (`data/lib/lockbox/model.rb`) is likely the root of it. 

What I notice is that in [CovidVaccine::V0::Registration::Submission#after_initialize](https://github.com/department-of-veterans-affairs/vets-api/blob/rm-bump-lockbox-1.3.3/modules/covid_vaccine/app/models/covid_vaccine/v0/registration_submission.rb#L11), the expectation was that data was to be symbolized, yet if you pry'd in after the `symbolize_keys!` before and after updating versions, you would notice that before updating the `symbolize_keys!` method wasn't behaving as expected, and after it was.

I have a PR up that "fixes" it, by removing the `after_initilize!` method, because Eric and I determined that it never was working like intended (suggested by the expectation), but now it was causing issues. I'll talk to the engineer who last worked on it (Patrick Vinograd) before merging upon getting back from vacation.

**Comment by ericboehs** [comment]
This merged Tuesday and deployed yestereday. All set.

**Comment by JoeTice** [comment]
SPRINT 6 UPDATE: In Progress - This ticket was deployed late on 7/31 so didn't get closed before the end of the day.
