### ISSUE TITLE
Qualitative Data Request - MyVA411 - Accredited Representation Management (June 2024)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87293]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

06-21-2024

### Date Range End

06-30-2024

### Product Name(s)

Find a Representative, Representative Status Widget

### Product Description

The Find a Representative product enables users to search for an accredited representative based on representative type, location and name.

The landing page provides additional context to accredited representatives and also contains the entry point into the Find a Representative product.

The Representative Status Widget is present on both of these pages and allows users to see their current representation status.

### Survey URL(s), key term(s), case category or type

accredited, representative, representation, power of attorney, poa

attorney, claims agent, vso, veteran service organization, vso representative, vso rep, veterans service officer, service organization representative

21-22, 2122, 21-22a, 2122a

claims support

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

lindsay.li-smith@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, there is no cases in MYVA 411 for the selected case type or case categories. Let me know if you have any questions. Thank you.
