### ISSUE TITLE
S57 [Baby, You're a Firework! 🎆 ]

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#87301]
# Sprint Goals

| Previous Sprint | Next Sprint |
| :--------------  | ----------:  |
| ◀️  #85878        | #88351 ▶️     |

**Scrum Hero**: @eileen-coforma   

### Priority 1: Remediate historical failures ([WIP epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80241))

**Send historical failure data for review to determine which claims need to be remediated.**
- #86343

### Priority 2: Submission Stability and Storage ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293))

**Update the existing decryption library to handle the latest encryption methods, so Veterans can submit more types of PDF evidence.**

- #87405
- #88016

**Store Submissions**
- #84329 
- #84332 
- #84348

### Priority 3 : Move the 4142 within 0995 to LH

**Move the 4142 within the 0995 off EMMS API**
- #85680 

### Priority 4-5: HLR and SC Form Version Updates (epic links: [1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82220) and [2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82219))

**Mock designs and kickoff FE work for HLR and SC.**

- #85851
- #87098
- #87670

### Accessibility, and Design Enhancements

- #88106
- #82249 
- #80475
- #87782

### Bug/Engineering Backlog

- #88356
- #58833 
- #83324 
- #79233
- #87096
- #73584 
- #65563
- #60784

---

## Blocked Items

- #83078 
   - Waiting for content team to finish their work
- #83772
   - Blocked until LH [updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83772#issuecomment-2154931490) the submission endpoint to support new questions
- #81507
   - Waiting for Lighthouse to release [new endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81507#issuecomment-2115701294) to capture generated PDFs

---

## Team Capacity

**Outages:**
- 7/1 - 7/5 - @skylerschain 
- 7/3 - 7/5 - DK
- 7/4 - Holiday
- 7/5 - @dfong-adh, @eileen-coforma  
- 7/8 - 7/12 - Silke

## Sprint Risks and Assumptions
- Robin may need required training. Can't access CAG ATM.

## Reference documentation

- [Q3 Roadmap Prioritization](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/product%20management/Prioritization/DR%20Prioritization%20Scoring%20-%20April%202024.xlsx?d=wb661cf77374d4321969f619e845cabbd&csf=1&web=1&e=GIwNAH)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)

**Comment by eileen-coforma** [comment]
@shaunburdick @Mottie I added #87782 to the design enhancements section for pickup after other priority items are done. Not urgent since we're still blocked by LH endpoint.

**Comment by eileen-coforma** [comment]
There's a bug for AMA transition, but not our problem. More tests may be required to send downstream. @shaunburdick needs to add a ticket for this work.

**Comment by shaunburdick** [comment]
Added #88356

**Comment by eileen-coforma** [comment]
Closing this since the next sprint started.
