### ISSUE TITLE
UX new landing page branch bugs

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87334]
## Launch Blocking
- When selecting "Details" BEFORE completing pre-check-in, there should not be the content directly below the heading about "bring insurance." [Figma link](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=961-53612&t=dsUot75XDl6S7rGp-4). 
          - [Bug Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87410)
- "Review your information" eyebrow component should be on the demographic question pages in pre-check-in above the h1. [Figma link](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=996-25771&t=5rs37uwvjl6Jmg1h-4). 
          - [Bug Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87412)
- For check-in, we talked about pivoting the H2 to "Today's appointments at this facility". [Figma link](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1440-31577&t=dsUot75XDl6S7rGp-4).  
          - [Bug Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87413) 
          
## Not Launch Blocking
- Error pages need to get implemented. I.e., messaging isn't consistent with appt list and confirmation page and accordion content is no longer consistent across experience. [Check in Figma link](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1743-10526&t=dsUot75XDl6S7rGp-4). [Pre-check-in Figma link](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1733-17108&t=dsUot75XDl6S7rGp-4).
        - [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87416)
- When using the default mock UUID for check-in, if you select "no" to not being at the facility, it takes the user to "We couldn't check you in" page. This is not correct. Expectation: proceed to demos or travel questions. 
    - LP: I don't get this, it works fine on my machine
- Question: can we simulate in one of the mocks selecting "go back to today's appts" after checking in and seeing the task card removed and the appt changed to "you're checked in"? Or, no, we can't do that right now? (I'm assuming no, but just wanted to double check. Could use a mock to demonstrate this. E.g., you're checked in to your appt already after authentication.)
        - [SPIKE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87414)
- [Remove the two statuses from the appt list](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1549-29931&t=5rs37uwvjl6Jmg1h-4). 
        - [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87394)

**Comment by benbrasso-agile6** [comment]
@loripusey

**Comment by loripusey** [comment]
@benbrasso-agile6 everything has a ticket, I have @wullaski working on the launch blockers this sprint, he should be able to finish those before we release on Monday; the rest are in the next sprint; close this ticket if you don't have any questions or concerns

**Comment by benbrasso-agile6** [comment]
> When using the default mock UUID for check-in, if you select "no" to not being at the facility, it takes the user to "We couldn't check you in" page. This is not correct. Expectation: proceed to demos or travel questions.
LP: I don't get this, it works fine on my machine

I wonder if I was just cached into the same session still. Ok to release.
