### ISSUE TITLE
Load testing implementation

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#87350]
Implementation of load testing patterns found in [this spike](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/86866).

As a engineer using staging IVC forms, I would like to know the load and latency of these endpoints.
One of the endpoints is Pega's s3 bucket.

Acceptance criteria.

Document the load for Pega s3 bucket

**Comment by baltes** [comment]
@cloudmagic80 This is the start of a load testing ticket. Can you add details in the description about the options you plan to go with?

**Comment by cloudmagic80** [comment]
[Uploading... Screenshot 2024-07-01 at 2.11.53 PM.png]

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/14503

**Comment by baltes** [comment]
@cloudmagic80 I looked in github and zenhub and your images above aren't showing. Are they working correctly for you?

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/14510

<img width="1306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU92QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--904561e314693a85bafd8d067ca1ced094d9e430/Screenshot%202024-07-03%20at%209.02.10%20AM.png" alt="Screenshot 2024-07-03 at 9.02.10 AM.png" />

**Comment by baltes** [comment]
Who has access to the graphs above, and do we know who monitors it? Does it generate alerts?

**Comment by baltes** [comment]
@cloudmagic80 Forgot to tag you in the comment above about graphs and monitoring.

**Comment by baltes** [comment]
@cloudmagic80 Still open questions about this one, please see above.

**Comment by cloudmagic80** [comment]
Based on the other previous load testing results, it seems like the graphs are saved in the devops folder. It doesn't generate results and it is not a reoccurring test.
