### ISSUE TITLE
[Debts 1.0] Add data to payload from new DMC data

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#87364]
Once DMC sends us the transaction data for debts, we need to observe what we're getting back and maybe add some code to include it in the debts payload.

Daniel Wildman (DMC) let us know (via email) that the debt-letters/get endpoint is bringing back fiscal transaction data. 

The Backend Developers need to go out to production and run the request to see what the data looks like. Once they have an idea, they'll likely have to update mock data to return this new data contract so FE and BE developers can work with it.

**Comment by Tom-Davis** [comment]
This will roll over to the next sprint as Max is out until the first day of the next sprint. @maxx1128 please add more detailed roll over information once you are back.

@HeatherRienks
