### ISSUE TITLE
[UX, FE} 10-10EZ - Improvement: URGENT Update OMB Expiration with temporary extension time

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#87379]
## Background
The 10-10EZ was set to expire on 6/30/2024.  The OMB Approvals are taking longer than expected, so we have been authorized a 30-day extension (expiring 7/31/2024).  

We need to update the OMB expiration date to 7/31/2024.  Once the approvals are received, we will update with the actual expiration date (expecting a 3-year renewal).

<img width="307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK09rQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--101a8fc9332b81be3fdd845853a61aa6cba8230c/image.png" alt="image.png" />

## Tasks
- [x] Update designs and frontend to display OMB expiration 7/31/2024
- [x] Deploy to production

## Acceptance Criteria
- OMB expiration date on the 10-10EZ has been updated to reflect the temporary extension date of 7/31/2024.

**Comment by jessicastump** [comment]
[Figma files updated here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3670-14789&t=gIYuviYf7lJxlQXl-0) - only updated the source of truth page, did not create a 'ticket' page in Figma

**Comment by hdjustice** [comment]
Thanks @jessicastump!
@longmd - would you be able to knock this out today (amongst the CG stuff)?

**Comment by longmd** [comment]
@hdjustice , PR is pending for this.

**Comment by longmd** [comment]
This has been updated.
<img width="1904" alt="Screenshot 2024-07-02 at 10 39 30" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/59ccf985-2437-4da4-b094-70f01b60d7c1">

**Comment by hdjustice** [comment]
Thank you!
