### ISSUE TITLE
[Bug] Yellow Ribbon - Search MVP - IE 11 - Pagination unresponsive

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8738]
## What happened?
In Win IE11, on Staging [Find a Yellow Ribbon School](https://staging.va.gov/education/yellow-ribbon-participating-schools/) page, showing 2+pages of results, the pagination widget is not responding to any clicks.

## Specs:
- Browser: Windows Internet Explorer 11
- Test User _(if applicable)_: N/A \[this is unauthenticated experience]

## Steps to Reproduce

1. In Win IE11, go to https://staging.va.gov/education/yellow-ribbon-participating-schools/?state=FL
1. Scroll down to pagination widget \[below results-list], click any page/Next link.
1. Observe that nothing happens.

![yr-pagination-bug-ie11-200504](https://user-images.githubusercontent.com/587583/81026573-6823b880-8e2f-11ea-915b-88ef8133139e.gif)

## Desired behavior

1. Clicking on a page-link displays the appropriate page of results \[10 results].
1. Clicking Next link advances results by one page (10 results, except possibly last page).
1. Clicking Prev link reverses results by one page\[10 results].

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ncksllvn** [comment]
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/8f8af0af-a196-43a0-a296-6e69d68a3ce3)

CC: @kelsonic

**Comment by stephorkandatx** [comment]
@tlei123 I believe this has been resolved. In testing on my IE11, I am able to use the pagination elements. Can you validate and close, if you are seeing the intended resolution?

**Comment by stephorkandatx** [comment]
Closing this out @tzelei let me know if I need to re-open

**Comment by tlei123** [comment]
All good.  Validated.
