### ISSUE TITLE
Qualitative Data Request for Homepage

### ISSUE THREAD

**Issue by aklausmeier** [department-of-veterans-affairs/va.gov-team#87383]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-1-2024

### Date Range End

07-01-2024

### Product Name(s)

Homepage

### Product Description

VA.gov homepage

### Survey URL(s), key term(s), case category or type

https://www.va.gov/

ONLY the root url for the homepage, no additional urls under this. 

### Sub URLs

No

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

amanda.klausmeier@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
