### ISSUE TITLE
[Research] Conduct research during VSA teams onboarding sessions

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#874]
## User Story
As the Product Support team, we need to learn and understand where/how we can improve the onboarding process for new teams.

## Goal
Learn how to improve our onboarding process

## Definition of Done
- [x] Results and recommendations synthesized and communicated with the team
- [x] Issues created to implement improvements

**Comment by smoonpeyes** [comment]
Here are the survey results for the onboarding meetings:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Platform/Onboarding/research/Onboarding-VSA-AUG-2019/survey-results

**Comment by smoonpeyes** [comment]
Reviewed with Andrea. Closing.
