### ISSUE TITLE
[Bug] Yellow Ribbon - Search MVP - Copy/styling mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8741]
## What happened?
On Staging Find a Yellow Ribbon school page, some copy and styling details do not match design prototypes.

## Specs:
- This bug is browser-/device-agnostic.
- No test-account needed; Yellow Ribbon is an unauthenticated experience.

## Steps to Reproduce
1. Go to https://staging.va.gov/education/yellow-ribbon-participating-schools/
1. Observe copy/styling mismatches \[see screenshot below]:
![yr-copy-styling-bugs-200504](https://user-images.githubusercontent.com/587583/81032403-80ea9900-8e44-11ea-801f-cfe0f1b290db.png)

## Desired behavior
Copy/styling matches [design-prototype](https://vsateams.invisionapp.com/share/P4W04QPWHTK#/screens/405236720) [see screenshot below]:
![yr-copy-styling-specs-200504](https://user-images.githubusercontent.com/587583/81032320-379a4980-8e44-11ea-86d0-813570be5449.png)

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by stephorkandatx** [comment]
@andaleliz and @AnneHurley during testing, it was found that there is a difference in copy between what was in the designs and what is on staging for YR. 
Can you take a look at what is on staging and what is in the designs and confirm which one should be considered the latest and greatest copy that should be launched? That will help determine how we resolve this issue. Thank you!

**Comment by andaleliz** [comment]
Staging is correct in terms of latest and greatest content. I've updated the designs to reflect these changes; sorry for the oversight and causing extra work!

Regarding the button, I intentionally kept the button to be sized for the content, just maintaining the padding on the sides. I believe that is what we do throughout VA.gov on buttons so I don't think we'll need custom CSS to accomplish that.  Here's an screenshot from My VA of various buttons, all seem to be sized for the button label.

![image](https://user-images.githubusercontent.com/55992116/81238205-70b2f500-8fcf-11ea-9ecf-c9c234b6e121.png)

**Comment by stephorkandatx** [comment]
@tzelei based on the comment above, can we close as a non-issue?

**Comment by tlei123** [comment]
> @tzelei based on the comment above, can we close as a non-issue?

@stephorkandatx, general ticket-workflow like closing defects is actually up to your team.

That said, however, I should re-run the failed test-case against the updated design artifacts...

So...  would YOU mind if we kept this open 'til around mid next week when I can re-run my failed case?   If yes, then just assign this tic to me and I'll closed it after my re-run.

Thx much for circling back!

**Comment by stephorkandatx** [comment]
Moved to Validate so this can be re-run.

**Comment by tlei123** [comment]
Thx much, @andaleliz !  Validated.
