### ISSUE TITLE
Check-in: Implement New Landing Page Errors

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#87416]
## Description
Error pages need to get implemented. I.e., messaging isn't consistent with appt list and confirmation page and accordion content is no longer consistent across experience. 

## Wireframes
[Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1872-17169&t=vKAuee90FzLeA2Ua-0)

## Tasks
- Update Day-of Check-in errors

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/87416?planning-poker) with Zenhub @brianseek @wullaski

**Comment by brianseek** [comment]
we are meeting with UX on this today and can point after

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 / @cgednalske Here are screenshots to review for this work:
[day-of-errors.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjN2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--709b68f5ebf52f18f52cea8a9298d02da4c26b53/day-of-errors.zip)

**Comment by loripusey** [comment]
I think this H1 is supposed to say "We're sorry. This link has expired."

From the zip file:
![image](https://github.com/user-attachments/assets/b50c9ad8-aaf2-4e7c-88d9-2a80da2d8cb2)

From the Figma file:
![image](https://github.com/user-attachments/assets/a525be97-0e4b-4d08-a5e2-2878f8acf6d8)

**Comment by brianseek** [comment]
@loripusey updated! See new zip: [day-of-errors-2.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnp3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be61ad2830420ddc5d1f87b2e9ff6065f26855a8/day-of-errors-2.zip)

**Comment by zach-park** [comment]
Day-of-check-in--Errors--travel-fail-check-in-success-accordion-expanded.png
Day-of-check-in--Errors--travel-fail-check-in-success.png
The alert looks different from the wireframes Figma file (see attached below). Just wondering if the above screeenshots is the latest iteration. Other than that looks nice! Thank you. @benbrasso-agile6 @brianseek @loripusey 
![Screenshot 2024-07-18 at 11 35 21 AM](https://github.com/user-attachments/assets/264d977e-3c6f-4caa-b9b6-2328ada57ce2)

**Comment by brianseek** [comment]
Thanks @zach-park, I did not notice that subtle change in content. See new screenshots: [day-of-errors-3.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDN4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af808d1032920dc01584feba736cd807d2c9107e/day-of-errors-3.zip)

**Comment by zach-park** [comment]
LGTM. Thank you! Cc: @benbrasso-agile6 @cgednalske

**Comment by brianseek** [comment]
closing this ticket, code review and merging to take place in this ticket for next sprint: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/88841
