### ISSUE TITLE
[Bug] Yellow Ribbon - Search MVP - Number of results mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8742]
## What happened?
On Staging **Find a Yellow Ribbon School** page, searching on Cambridge, Massachusetts with no School name and no checkbox selected, 22 results are returned, instead of 12 as specified in pertinent Proposed Scenario in QA Test Plan #6918.

## Specs:
- Browser-/device-agnostic
- Unauthenticated experience

## Steps to Reproduce
1.  Go to https://staging.va.gov/education/yellow-ribbon-participating-schools/?city=Cambridge&state=MA
1.  Observe that **22** total results are returned:
![yr-results-bug-1-200504](https://user-images.githubusercontent.com/587583/81031970-17b65600-8e43-11ea-8c47-dd10667dce0c.png)

## Desired behavior
**12** results returned, according to pertinent Proposed Scenario in QA Test Plan #6918 \[see screenshot below]:
![yr-results-spec-1-200504](https://user-images.githubusercontent.com/587583/81031980-1be27380-8e43-11ea-82be-843404c6694a.png)

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by stephorkandatx** [comment]
@kelsonic If you could take a quick look at this. I imagine that this is where, in reviewing the test cases + comparing to the staging experience, I missed that the test case said 12 instead of 22. Let's confirm the correct data number (for now) and we can determine if there is a bug or a situation to update test cases.

**Comment by kelsonic** [comment]
I've confirmed via Postman that there are indeed 22 results for staging YR data, it should not be 12. This is not a bug and the API is behaving as intended 🙂
