### ISSUE TITLE
[VAMC Left Nav upgrade] VSA-QA Test Plan

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8743]
## Product/Feature summary
An upgrade to the local navigation component for Pittsburgh’s VAMC system of websites, beginning with the functionality available in staging and informed by the user research conducted in November/December 2019. This enhancement implements a revised design based upon initial veteran feedback and further veteran research conducted on the Pittsburgh health system site in November/December 2019. Improvements to the Left Nav were initiated by the Public Websites team and completed by the Facilities team with the goal of providing a straight to the point navigation allowing the Veteran to quickly find and complete their journey on the VAMC website. 

## Artifacts
[Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/fe-templates/left-nav/vamc-left-nav-enhancement-feature-brief.md)
[Product/Feature Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874)

Product/Feature Design artifacts: 
- Link to [Desktop Design Spec](https://app.zenhub.com/files/133843125/80583b15-6296-4091-b7c1-8e79987ce877/download)

Mobile spec: 
![VA-on-page-nav - pitts-home-mobile.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c4664bfd-c82e-4c32-b2ba-99364674e6fb)

![VA-on-page-nav - pitts-locations-mobile Copy.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/21142ae5-ffd4-41cf-9b1f-76fd3c9e2a4a) 

![VA-on-page-nav - pitts-locations-mobile.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/3af89f28-65e1-4ee6-96ae-d718b8ff140c)

## Product-team SMEs
Product Management: Michelle Middaugh
Design/Research: Ryan Thurlwell 
Front-end: Gibran Rodriguez and Ethan Teague
QA: Tze-chiu Lei

## Proposed user-scenarios 
No test accounts will be necessary: unauthenticated experience

Please reference [#7212], [#8476] and [Test Rail](https://dsvavsp.testrail.io/index.php?/cases/view/391&group_by=cases:section_id&group_order=asc&group_id=62) for Acceptance critera

Scenario 1: When a Veteran lands on https://staging.va.gov/pittsburgh-health-care/
Scenario 2: When a Veteran selects an item from the nav bar
Scenario 3: When a Veteran hovers over an item from the nav bar
Scenario 4: When a Veteran chooses a new item from the left nav after visiting another page
Scenario 5: When a Veteran wants to visit the previous page

Mobile: Please reference [Test Rail](https://dsvavsp.testrail.io/index.php?/cases/view/419&group_by=cases:section_id&group_id=62&group_order=asc) for the following scenario: 

Scenario 6: When a Veteran accesses the page on a mobile device

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Test Plan reviewed by Product Team.
- [x] Test Plan finalized per review feedback.
- [x] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
@mmiddaugh , I've completed all test-runs...

Defects logged: #8905, #8906, #8909, #8946

TestRail links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/225)
- [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/74)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/75)

cc @pjhill @brangi

**Comment by brangi** [comment]
@tlei123 @pjhill , I commented on  #8909, #8946 and  #8905. It would be nice to have your input so that we can groom fixes for them... cc @mmiddaugh
