### ISSUE TITLE
[BUG] Facility Type custom dimension is 'undefined'

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#8744]
## What happened?

On the page for [Beaver County VA Clinic](https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/), we should have a value of "Clinic" but I am seeing _undefined_ for custom dimension 52.

![image](https://user-images.githubusercontent.com/62304138/81068943-2d616500-8eaf-11ea-9181-36e5e3eb82fe.png)

## Desired behavior

We should have a value of "Clinic" or "Campus" in custom dimension 52 for facilities with these keywords in their names.

## Acceptance Criteria
- [ ] Pages like https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/ will have a value of Clinic

**Comment by bsmartin-ep** [comment]
@jonwehausen -

I believe this issue is because the string match is case sensitive and failing.  I updated the JS in this workspace:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000279

LGTM...

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/7977b436-a2eb-4557-b8b7-f7e61c55e335)

Do we have a location with "Campus" in the name (maybe on staging?) to test that?

**Comment by jonwehausen** [comment]
Thanks @bsmartin-ep ! Looks good from testing. Will close for now however we should discuss a more robust solution to fix moving forward.
