### ISSUE TITLE
[FE] 10-10EZ - TERA Improvements: Create branching logic based on Veteran's birth date

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#87452]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. 

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By introducing branching logic to the TERA questions, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for content](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

## Tasks
- [x] Update/create branching logic of questions so that the birth date determines the TERA questions that display to the Veteran
- [x] Inform QA/Team when the updates are ready to start testing 

## Acceptance Criteria
- The Toxic Exposure questions display based on time period compared to the Veteran's birth date.
- The updates are ready for QA testing

**Comment by longmd** [comment]
@allanto-ah , this will be ready for QA once the RI builds. Ill post that link in your QA ticket.
