### ISSUE TITLE
Flipper UI access for Rachel Eiting

### ISSUE THREAD

**Issue by reiting** [department-of-veterans-affairs/va.gov-team#87456]
### Your Name

Rachel Eiting

### Your GitHub handle (Flipper UI access is managed through GitHub)

reiting

### Team, Role, and Company of the target individual

IVC CHAMPVA , front end engineer, copilot

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need production (and lesser) access because my team is preparing to roll out CHAMPVA form 10-7959f-1 in the coming weeks/months and will be using a flipper to gate access to the application. As a developer on that project I have been tasked with implementing the flipper for this form.

**Comment by bdech** [comment]
confirmed in Atlas
E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71155)

**Comment by bdech** [comment]
@reiting You've been granted to `production` and `lower` flipper environments.
