### ISSUE TITLE
Documentation Support Request

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#8746]
## Two related missing links
(not stopping work, just reporting it):

- From https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-widgets/#arraycountwidget,
- Text, _see "Sequential duplicate form groups."_
- Link: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines.md#sequential-duplicate-form-groups)

Also on same page,
- Text: _To see a code example, refer to radio button group in form features._ 
- Link: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines.md#radio-button-group

That whole "available features and usage guidelines" page is 404.

### _What happens now?_ 
_The VSP Content & Information Architecture will triage your request and reach out for more info as needed. If your issue is urgent or you don't hear from us in a timely manner, please reach out to @Megan Kelley, @Gretchen Maciolek, @Kristina Gore in #vfs-platform-support._

**Comment by billfienberg** [comment]
PR to fix broken links: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/252
