### ISSUE TITLE
[Benefits Documents] Scan document uploads with ClamAV (Antivirus)

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#87467]
### Value proposition
We should be scanning documents to be uploaded to the Lighthouse Benefits Documents API with clamav so that we can return an error to the user right away if there is an issue with one of their files. This will help us to prevent silent failures

### Background
Lighthouse is running these documents through a virus scanner as well, so if we are unable to catch these issues before we pass the documents over to the Sidekiq job then we will end up with silent failures

### Tasks
- [ ] Update the lighthouse document service to scan documents using clamAV before they are sent to Lighthouse

### Acceptance Criteria
- [ ] Documents are being scanned for viruses before they are sent to Lighthouse Benefits Documents

**Comment by jacobworrell** [comment]
need to score this a 3.
