### ISSUE TITLE
Business intake form for VA CX SRP

### ISSUE THREAD

**Issue by jessetbowman13** [department-of-veterans-affairs/va.gov-team#87461]
## Your Details
1.  Jesse Bowman, developer on VA CX SRP (formerly WH Hotline) team
2.  VA Case management
​
## Notification Details
1. Email
2.   As part of the initiative to write information to VA Profile, VA CX SRP plans to utilize VA Notify to send an email alerting the user of information change. 

3.  **What actions can the user take based on the notification they receive?**
   The email will be for information only, no action 
​
5.  **What is the desired business outcome?**
    Provide the user with accurate data pertaining to their VA Profile information

6.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
     The notification will be sent from code or a flow owned by the VACX team in the VA Main Salesforce org
​
7.  **What will trigger the notification?**
      Upon finishing the update form, the agent working the case will submit the information to VAP triggering the notification to the caller
​
8.  **Provide sample content per notification type, if you have it.**
This template has been provided from the business. The {{contact info}} will display the change (email, phone, address etc) ​
![image-2024-06-06-15-28-50-593](https://github.com/department-of-veterans-affairs/va.gov-team/assets/77974537/9773cff9-d6c1-488c-a3ac-6423c9fb998f)

9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
​    Nothing to review per PO

10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
 Unsure at this point
​
11.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
No
​
12.  **What is the anticipated volume of notifications per day, week, month?**
​Unsure 

13.  **When does this notification need to be in production?**
November is the current target for production

**Comment by mjones-oddball** [comment]
Hey @jessetbowman13 your team already submitted an intake here and has been onboarded to VA Notify: https://github.com/department-of-veterans-affairs/va.gov-team/issues/78414

Is there anything you want to update in that existing intake before I close this one as duplicate?

**Comment by jessetbowman13** [comment]
I did not realize that. No, please close mine.

Thanks
Jesse Bowman
Sr. Salesforce Developer
***@***.*** | ***@***.***
706.979.5884

From: Melanie Jones ***@***.***>
Sent: Wednesday, July 3, 2024 3:42 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Bowman, Jesse T. (Booz Allen Hamilton) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for VA CX SRP (Issue #87461)


Hey @jessetbowman13<https://github.com/jessetbowman13> your team already submitted an intake here and has been onboarded to VA Notify: #78414<https://github.com/department-of-veterans-affairs/va.gov-team/issues/78414>

Is there anything you want to update in that existing intake before I close this one as duplicate?

-

**Comment by mjones-oddball** [comment]
Duplicate ticket - closed
