### ISSUE TITLE
Analytics Reporting Request for SSOe

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#8747]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Alexis James

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - [SSOe](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/README.md)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
Looking for analytics over the past year.

## Analytics to Track Down
> Examples
> 
> - [ ] How many times a user logs in during one session. (from va.gov, MHV and Ebenefits)
> - [ ] Number of successful logins using each of these methods: DS Logon, IDme, MHV)

## Which Product Questions are you trying to answer?
How many times do users authenticate during a session?
Will the launch of SSOe have an impact on how many times a user needs to authenticate during a session. 
Will SSOe impact a user's ability to authenticate successfully?

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@marriej -

Sorry for the delay in getting back to you.

1. How many times do users authenticate during a session?

For modernized logins, we have events we can examine to determine a conversion rate:


System | Login Attempt | Login Success | Conversion Rate
-- | -- | -- | --
ID.me | login-attempted-idme | login-success-idme | login-success-idme / login-attempted-idme
MHV | login-attempted-mhv | login-success-myhealthevet | login-success-myhealthevet / login-attempted-mhv
DS Logon | login-attempted-dslogon | login-success-dslogon | login-success-dslogon / login-attempted-dslogon

Unfortunately, we don't have the same dataLayer events for MHV and eBen logins.  I think we can look at other dimensions (Pages and Page sequences) to attempt to track these, though I may need your help verifying these with backend numbers.

### Are you able to provide me with successful login numbers by login system by site / subdomain?

In the meantime, I've created an Analysis dashboard to track our visualizations...

https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361/edit/t0bC95-FRGCmCJJlES2edA

You'll see five tabs:

1. Funnel analysis - ID.ME Login Completions
2. Funnel analysis - MHV Login Completions
3. Funnel analysis - DS Logon Login Completions
4. Funnel analysis - Combined Login Completions
5. Segment Overlap - Modern successful login vs eBen vs MHV
  - Our three segments:
    - Sessions with any `login-success-*` event
    - Sessions where a users goes from the MHV login page directly to another MHV page
    - Sessions where a user accesses an eBen eauth page (anything that contains eauth.va.gov/ebenefits)

**Comment by bsmartin-ep** [comment]
Hi @marriej - do you need anything else from us for this request?

**Comment by marriej** [comment]
@bsmartin-ep all good here. Thanks for your help.

**Comment by bsmartin-ep** [comment]
Sounds good @marriej.  Let us know if you need anything else.
