### ISSUE TITLE
[CAIA A11y Research]: Ask VA VA.gov Team, Ask VA – Form (August 2024)

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#87480]
> [!NOTE]
> **High-Level Overview**: ASK VA
> - **Research Timeframe**: ~Aug. 7 - 14, 2024~ Aug. 13-20, 2024
> - **Time of Day:** 9-10:30am, 11-12:30pm, 1-2:30pm, 3-4:30pm EST
> - **Pilot**:  `3 Pilots` [Mobile](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89026), [Desktop](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89027) and [TTS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89028)
> - **Assistive Tech Users**: 6 AT Users (3 minimum) 
> - **Artifacts Available**: Yes
> - **Testing Environment:** [Staging](https://staging.va.gov/contact-us/ask-va-too/introduction)
> - **Testing Schedule:** [Source of Truth](https://docs.google.com/spreadsheets/d/1Hvf97GB6l4hs-i30r0KHLt9BrOcERpKzRnghRzT7LjU/edit?gid=1814880187#gid=1814880187) **_also see table in this ticket_**
> - **Assistive Tech Being Used**: `Screen Readers` `Screen Magnification` `TTS` `3 Beginner SR and 3 Experienced SR`
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- Sara
- Jamie
- Riley
- Evan
- SK

</details>

## About the Team

<details><summary>Toggle to view information about the team.</summary>

- Team name: Ask VA
- OCTO-DE product owner: Becky Phung
- Product manager: CeeCee O'Connor and Terri Hollar
- Designer: Tyler Gindraux, Thomas Michaud
- FE engineer: Eddie Otero, Hemesh Patel
- Product/team Slack channel: #ask-va-public

</details>

<details><summary>Toggle to view more intake research ticket information</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### Calendar checking

- [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [X] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

### When is the timeframe for your testing?

- **Original**: ~August 7-14, 2024~
- **New**: August 13-20, 2024

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

<details><summary>Toggle to view research timing information.</summary>

### Timeframe

1. **Pilot Session Mobile**:`TBD`
2. **Pilot Session Desktop**:`TBD`
3. **`NEW` Pilot Session Async AT**:`TBD` 

**Timeframe**: 
- **Original**: ~8/7/2024 - 8/14/2024~
- **NEW** 8/13/2024 - 8/23/2024

### Length of sessions

- **Session length:**
    - 90 minutes (screen reader or alternative navigation tool)
    - 60 minutes (screen magnification tool)
- **Buffer time between sessions:** 30 minutes
- **Maximum sessions per day:** 2

</details>

###  Testing Schedule

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

Please toggle and use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

- **Dates**: Tuesday, August 13 to Tuesday, August 20
- **Times**: 9-10:30am, 11-12:30pm, 1-2:30pm, 3-4:30pm
- We will recruit 12 Veterans for:
     - minimum of 3 sessions with screen reader users
     - minimum of 2 sessions with alternative navigation users
     - minimum of 1 session with a screen magnification user

*For more details about our criteria, refer to our [Recruitment ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/603).

#### Source of Truth
[Testing Schedule - Google Sheet](https://docs.google.com/spreadsheets/d/1Hvf97GB6l4hs-i30r0KHLt9BrOcERpKzRnghRzT7LjU/edit?gid=1814880187#gid=1814880187) **_also see table in this ticket_**

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available
------------------|------------------|--------------|--------------|--------------|--------------|--------------
**PILOT MOBILE** | 8/1/24 from 2-3 p.m. | VoiceOver, JAWS, etc `TBD` | Mobile, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @rileyorr 
**PILOT DESKTOP** | 8/1/24 from 12-1 p.m.  | VoiceOver, JAWS, etc `TBD` | Desktop; Windows, MacOS  `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 
**PILOT AT (TTS)** | 8/2/2024 from 3-4 p.m. | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 
P1 | 8/13/24, 9 a.m. `canceled - participant wasn't AT user` | **TTS Dragon** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 
P2 | 8/13/24, 11 a.m. | **TalkBack** | Mobile; Android | Chrome | Novice | @coforma-jamie  
P3 | 8/13/24,1 p.m. | **Microsoft Magnification** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @sara-amanda 
P4 | 8/14/24, 11 a.m. | **VoiceOver** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P5 | 8/14/24, 1 p.m. | **Dragon** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 
P6 | 8/15/24, 9 a.m. `cancelled, hoping to reschedule` | **VoiceOver** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 
P7 | 8/15/24, 1 p.m. | **Pointer on Mobile** | Mobile; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 
P8 `couldn't use AT, switch to Q&A` | 8/16/24, 11 a.m. | **VoiceOver** | Tablet ; Windows, iPad OS | Safari | Intermediate | @coforma-jamie 
P9 | 8/16/24, 1 p.m. | **VoiceOver** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @sara-amanda 
P10 | 8/19/24, 11 a.m. | **Speechify** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P11 | 8/19/24, 1 p.m. | **Microsoft Magnification** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P12 | 8/20/24, 1 p.m. | **VoiceOver** | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/products/ask-va-phase-1-product-outline.md)
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1708479170047/8ebb517a213e05ebc500087f5661a993a41392e8?wid=1358-1710439493448)
- [Prototype or mockups](https://www.figma.com/proto/nI0nYMdLamogjKq9t5atj8/Ask-VA-Prototype-R4-(Staging)?node-id=2001-81942&t=qOlK188ntSKlJfwi-1)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/07-2024%20Assistive%20tech/Form/Research%20plan.md) `7/11/2024` – ~We don't have one yet, but our goals will relate to testing with assistive technology in staging~
- [Research conversation guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/07-2024%20Assistive%20tech/Form/Conversation%20guide.md)– ~We don't have one yet, but the prototype should provide some context~
- [Epics/issue that may be helpful](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80535) – Previous ticket with y'all!

</details>

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket
- [x] **REMOVED PILOT CALENDAR HOLDS** - Removed **pilot** holds on the A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago)
- [x] **PILOT SESSION MOBILE: SCHEDULE** Pilot session with team. `Conduct on or by 8/1/2024` 8/1 - Riley
- [x] **PILOT SESSION DESKTOP: SCHEDULE** Pilot session with team. `Conduct on or by 8/1/2024` - 8/1 - Jamie
- [x] **PILOT SESSION TTS: SCHEDULE** Pilot session with team. `Conduct on or by 8/1/2024` - 8/2 - Jamie
- [x] **PILOT SESSION MOBILE: CREATE TICKET** See `related tickets task list` in this ticket `89026`
- [x] **PILOT SESSION DESKTOP: CREATE TICKET** See `related tickets task list` in this ticket `89207`
- [x] **PILOT SESSION TTS: CREATE TICKET** See `related tickets task list` in this ticket `89028`
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available. Added by SS 7/9/2024.
- [x] **Updated Holds** Holds updated to specific slots for P1 - P12 on 8/7/2024 - waiting on official invites (table updated in this ticket as well, based on Roster tab)
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean) Updated holds 7/12/2024 ss
- [x] **RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1l8tZ4OyOgscoiIShwNeTp1OxvdRPS5N2XaWW6jizV00/edit?usp=sharing)
- [ ] **(OPTIONAL) FEEDBACK REQUESTED:** [Review Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/07-2024%20Assistive%20tech/Form/Conversation%20guide.md) `Ready by 7/23/2024`
- [ ] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support.
- [ ] **[Review research folder and assets](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/07-2024%20Assistive%20tech/Form/Research%20plan.md)** `Ready by 7/23/2024`
- [ ] **Participate in research**  **Date Span:**`8/13/2024` and `8/20/2024`
- [x] **SESSION NOTES**: Create [CAIA notes document](https://docs.google.com/document/d/1l8tZ4OyOgscoiIShwNeTp1OxvdRPS5N2XaWW6jizV00/edit?usp=sharing) for a11ys to use during the sessions
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
```

```[tasklist]
### VFS TEAM Tasks
- [x] Tag @Naomi Eke in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH)
- [x] Your team's researchers and observers read through platform guidance on research with assistive technology users
- [x] Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired
- [x] Request pilot sessions with CAIA a11ys
- [x] Schedule pilot session with CAIA a11ys (Mobile)
- [x] Schedule pilot session with CAIA a11ys (Desktop)
- [x] Schedule pilot session with CAIA a11ys (Async)
- [x] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section `Available by July 23, 2024` `RCVD 7/11/2024` [Staging Link]([https://staging.va.gov/contact-us/ask-va-too/introduction])
- [x] **DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. `Added dates/times from Roster on 8/7/2024 as holds on calendar too`
- [ ] (OPTIONAL) Receive feedback on Conversation Guide for Screen Readers (if requested)
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in `Table` in the ticket above.
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (Sara or Terry)
```
```[tasklist]
### Related Tickets
- [ ] #82856
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81692
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80535
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89026
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89027
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89028
```

**Comment by tygindraux** [comment]
I posted this on #accessibility-help per guidance in the ticket: [Slack post](https://dsva.slack.com/archives/C8E985R32/p1719940308545719).

**Comment by tygindraux** [comment]
We'd like to do a pilot, please 💚 We're aiming for piloting around August 1.

**Comment by sara-amanda** [comment]
## Quick Questions

@tygindraux quick questions for you (I also put them in the [Slack thread](https://dsva.slack.com/archives/C8E985R32/p1720460539636489?thread_ts=1719940308.545719&cid=C8E985R32), if that is easier). I will be processing this research intake ticket this week for you. 

### Prototype
Will the prototype you will be testing be in CodePen or Staging for this research?  

### Pilots
I see you would like to run one around 8/1, are you still looking to do one with one and one with desktop? 

### AT Users
- I have noted you are going to be recruiting screen magnification and screen reader users, is that still an accurate note? 
- Based on your reply to this question, which tech would you prefer we use for the pilot(s)? 

cc: @NaomiPMC

**Comment by tygindraux** [comment]
Cross-posting from Slack:

1. Testing in staging.
2. Happy to take your steer on this, but it seems like one on mobile and one on desktop would be good. Around 8/1 but we can be a little flexible as needed.
3. Yes, SR and screen mag.

Thanks!

**Comment by tygindraux** [comment]
@NaomiPMC @sara-amanda – I have some updates to share. (I'll send on Slack, too.)

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/07-2024%20Assistive%20tech/Form/Research%20plan.md) is ready, if you'd like to review. 
- We've adjusted our research dates slightly from ~August 7 - 14~ to August 13 - 20th. Can you confirm whether this is okay with your schedule? I looked at the capacity calendar and these dates seem potentially even better.
- We've heard that QA with your team before we go to sessions with users is very helpful (not surprised!). We've previously talked to you about scheduling 2 pilots (one mobile SR, one desktop SR). I'm wondering if it's worth us scheduling a 3rd review (this could be asynchronous instead of a pilot, or whatever you prefer) to include an alternative navigation tool.
- Research timeslots are now available in the research plan. Let me know if you have any concerns there eg. timezone. Once we have the agreed roster from Perigean, I plan to add you to the invites (and/or whoever the accessibility specialist is that's supporting the sessions). 

Let me know your thoughts.

**Comment by tygindraux** [comment]
@NaomiPMC @sara-amanda – I'm just following up from my Slack message. I'm hoping to confirm whether these tentative dates/times will work for CAIA:

- Desktop, Screen reader pilot on Thursday, August 1 at 12-1pm EST
- Mobile, Screen reader pilot on Thursday, August 2 at 2-3pm EST
- Dragon NaturallySpeaking pilot on Friday, August 3 at 12-1pm EST

We can also make one of these an async review if that's better for CAIA's capacity/time.

**Comment by sara-amanda** [comment]
## Pilot Sessions 

Good Morning, @tygindraux ! Yes, we would be happy to help with these three sessions. Notes below: 

- [ ] **Desktop**, Screen reader pilot on Thursday, August 1 at 12-1pm EST - **A11Y TBD**
- [x] **Mobile**, Screen reader pilot on Thursday, August 2 at 2-3pm EST (@rileyorr)
- [ ] **Dragon NaturallySpeaking** pilot on Friday, August 3 at 12-1pm EST - We do not have a license for Dragon, would you like us to use another tool? This one we might need to do async. - **A11Y TBD**

cc: @NaomiPMC @coforma-jamie @EvanAtCoforma @mutiaadhocteam @rileyorr @megansiddle

**Comment by tygindraux** [comment]
Thanks Sara! We're happy to do the 3rd (dragon) pilot async.

**Comment by sara-amanda** [comment]
> Thanks Sara! We're happy to do the 3rd (dragon) pilot async.

We do not have a license for Dragon, would you like us to use another tool? @tygindraux

**Comment by coforma-jamie** [comment]
@tygindraux since we don't have Dragon, I'm planning to use MacOS Voice Command (the built-in voice tool on Mac)

**Comment by tygindraux** [comment]
Thanks @sara-amanda and @coforma-jamie!

**Comment by coforma-jamie** [comment]
### Takeaways

- Paragraphs: Remove chunking of the paragraphs to allow the SR to read smoothly with the goal being not having to do multiple swipes to digest the content. Taking place in non-authenticated and authenticated views. TalkBack doesn’t like nesting FYI. I imagine it’s just because the controls quote unquote interrupt the text. VO is the same way.
- Logging in: Authentication assumed to be necessary because “healthcare related.”
- Page infinitely loading - known error. Provide a heads up to the participant before this happens, if still taking place when testing begins.
- Zoom Bug: Overlay meeting controls - keeping the screen visually crowded. Workaround: Facilitator paste in chat. Copy/paste of password worked, due to blocked typing.
- Number TalkBack Output: 3,333 (reading out)
- Category: first option is blank <option> - so that needs removed.
- Drop-down: Not reading out the list count, similar to desktop.
- Old list of label names: These have been fixed and won’t show in real test.
- Focus: Top of the page (not H1) for early (category + topic) pages.
- First few pages: Similar work needed to Pilot 1 notes for desktop, as on mobile.
- Radio Buttons: Address known issues with topics and category pages.
- Feedback: Topic (H3) for the page you are on and then percentage, which is currently an H2: <h2 class=“vads-u-font-size--h6 vads-u-margin-top--1p5">18% complete with form</h2>
- Demo prefill data: helpful if available IE SSN to save time when testing.
- Font Size: Differing font size on health facility page <labels> (when searching in Columbus, Ohio)
- Editing answers - alert: Close button is not the first element in focus. Maria, a CAIA a11y who is visually impaired, says that this is the correct behavior, and that VA’s modal component puts focus on the close button first, which is incorrect. She approved of [this guidance](https://accessibility.expedia.biz/pages/7-3).
- Editing answers - How should we contact you: these are editable, and shouldn’t be. And the “cancel” button isn’t working.

**Comment by sara-amanda** [comment]
## Mock Sign-In Update

> This means we will start on the first page after sign in, which is the 'dashboard' where someone can start a new question. 

@tygindraux this is wonderful news, and will be so helpful for the studies using AT, especially! 
Congrats to your team! 🥳 

[Ref. 8/7/2024 Research-Ops Thread](https://dsva.slack.com/archives/C0216PL32HJ/p1723060798673379)

**Comment by sara-amanda** [comment]
## Research Schedule
Happy Thursday, @tygindraux ! The research sign-ups are now complete for CAIA. 

### Sign-Ups Completed
- [x] The table in this ticket reflects this coverage.
- [x] [We have updated column I in your Research Schedule - August 2024 - Google Spreadsheet](https://docs.google.com/spreadsheets/d/1Hvf97GB6l4hs-i30r0KHLt9BrOcERpKzRnghRzT7LjU/edit?gid=331828355#gid=331828355&range=I:I) with CAIA team members covering the sessions. 
- [x] Our [CAIA Capacity Calendar has been updated](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/NewYork) (thank you for those invites); and I have added anyone who has signed up on our end to those invites, so we should be good to go! 
- [x] **Internal CAIA Note:** Our research tracker is also being updated. 

### Next Steps
We will need to collect the following during the testing: 
- [ ] User device
- [ ] User OS
- [ ] User Browser

cc: @NaomiPMC @coforma-jamie @EvanAtCoforma @SarahKay8

**Comment by coforma-jamie** [comment]
### Summary of findings
#### **Form Size**

* The form needs to be shorter and easier to complete and navigate.   
* Maintain Simplicity: The simplicity of the form was appreciated. Continue to ensure that forms remain straightforward and accessible.

#### **Pre-Filled**

* Pre-filled form fields must announce that they have already been filled. Otherwise, the user will assume that they are filled, attempt to fill them in, then edit what is in the field.

#### **Completion Rate**

* The percentages for completion should make numerical sense to the user.  
* Evaluate Necessity of Progress Indicators: While helpful, consider whether progress indicators are necessary for short or straightforward forms.

#### **Focus Behavior**

* Focus behavior regarding groups of components must be consistent.  
* User clicked “continue” which jumped them in the user flow, instead of “search” for the postal code, due to the zoom. 
* Confusion between "Next" and "Continue" buttons on the VA health facility screen. A partiicpant said that Next and Continue mean the same thing and the buttons were close enough to each other that he just hit the first one that made sense. 

#### **Form Functionality**

* Text option requested in addition to email and phone.   
* Updated postal code, even though user updated the phone number. The update was at the bottom of the page, which could be missed by zoom or a screen reader, vs. the top of the page, or near the item that was updated.   
* Include more relevant categories such as “Durable medical equipment” to better match the participants’ needs and experiences.

#### **Assistive Tech: Dragon**

* Dragon Considerations for Future Sessions:  
  * Continue leveraging the participant’s expertise with Dragon for efficient navigation and data entry.  
  * Ensure that session pacing is comfortable for the participant, with opportunities to pause and review as needed.  
  * Consider further training or adjustments to commands if needed to enhance usability and speed.

### Additional notes
You can read our full notes on [Google Docs](https://docs.google.com/document/d/1l8tZ4OyOgscoiIShwNeTp1OxvdRPS5N2XaWW6jizV00/edit#heading=h.bge1m11x3klh).

cc @tygindraux

**Comment by tygindraux** [comment]
Thanks for this summary!
