### ISSUE TITLE
FE/BE Pair - Discovery - getCalculatedMonthlyIncomeApi failed in helper:

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#87487]
### Discovery FE/BE pair investigation
[
Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/266691/?project=4&query=is%3Aunresolved+5655&statsPeriod=14d)

We're seeing an error in sentry that originates from the [Additional Income List](https://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist)

```getCalculatedMonthlyIncomeApi failed in helper: Error: No value destructured in response from getCalculatedMonthlyIncomeApi calculateTotalAnnualIncome```

## Acceptance Criteria

 - [ ] **Scenario: Successful calculation of monthly income**
  - Given the input data is valid and complete
  - When the API call is made to calculate the monthly income
  - Then the response should contain a calculated monthly income value without any errors

**Comment by HeatherRienks** [comment]
duplicate ticket; closing
