### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by underpaid1ntern** [department-of-veterans-affairs/va.gov-team#87498]
### Name

Benjamin Caldwell

### Email

benjamin.caldwell@bylight.net

### Role

UX Researcher / Designer

### Team

My HealtheVet on VA.gov / Portals and Access

### Additional Notes

Benjamin's Slack Profile: https://dsva.slack.com/team/U05L0JGUL4W

Ben will need the ability to edit in Figma since he's a researcher / designer and builds UI.

**Comment by naomimarcussen** [comment]
Hi! Ben already has an account in Figma with full editor access.

**Comment by underpaid1ntern** [comment]
@naomimarcussen , thank you!
