### ISSUE TITLE
[FE] - Change how FE determines in an address is overseas military or not and check/uncheck box

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8752]
## Background
When an overseas military address is saved to VA Profile, it comes back as a domestic address. 
The FE does flag it as an overseas military address when we make the call our API, but after the save succeeds it comes back from VA Profile as domestic. A side effect of this is that the "I live on a military base" checkbox is un-checked when you go to edit your address.

[slack convo reference](https://dsva.slack.com/archives/C909ZG2BB/p1588365365495800)

![image](https://user-images.githubusercontent.com/60523453/81087079-45dd7980-8ec7-11ea-84ac-09a2bdfdb0ee.png)

Note: #8596 Needs to be merged prior to this ticket as it changes a lot of the logic around military addresses.

## Tasks
- [ ] Change how the FE determines if an address we get from VA Profile is an overseas military or not so we can pre-check that box.

**Comment by sanlouise** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8596 Needs to be merged prior to this ticket as it changes a lot of the logic around military addresses.

**Comment by sanlouise** [comment]
@mshea0606 Could you validate this ticket? Thank you!
