### ISSUE TITLE
SOCKS access for Chinedu Nwawgu

### ISSUE THREAD

**Issue by ChineduNwagwu** [department-of-veterans-affairs/va.gov-team#87520]
### Your Name

Chinedu Nwagwu

### Your Email

chinedu.nwagwu@adhocteam.us

### Your GitHub Handle

ChineduNwagwu

### Your Role and Team

Product Manager on Lighthouse

### Product Manager (PM) name and email

Chinedu Nwagwu - chinedu.nwagwu@adhocteam.us

### Product Owner (PO) name and email

Peter Tebbenhoff - Peter.Tebbenhoff@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3Y6g3hd4uTnCXzq0fcy0LUc4E98pk11sSKt+2trtg9 chinedun@chinedun-VFPXMPQN9M

### E-QIP Transmittal Confirmation

<img width="1325" alt="Screenshot 2024-07-02 at 3 04 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104175055/4bdcc871-2f74-4ea4-8bfd-6c7c4ba00baf">
<img width="1325" alt="Screenshot 2024-07-02 at 3 04 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104175055/d4c4e935-b10a-4aa4-b01e-761eb2e951d5">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
@ChineduNwagwu access completed.

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
