### ISSUE TITLE
[FE} - Change Profile bread crumb hard reload to client side router change

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8755]
## Background
When you click the Profile crumb, it does a hard reload of the page rather than the nice instant client-side router change you get when clicking through the sidenav. I think we can get around this because the My VA Dashboard also uses the React Breadcrumb component and deals with this nicely

[slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1588694497036500)

[Issue GIF](https://files.slack.com/files-pri/T03FECE8V-F012N8H43FZ/breadcrumbs.gif)

## Tasks
- [x] update profile breadcrumb click result

**Comment by sanlouise** [comment]
@mshea0606 Could you please validate this ticket? Thank you!
