### ISSUE TITLE
Offboarding of Keith Adkins

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8756]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Keith Adkins
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Va start up, DevOps, a few weeks ago (unknown), Ad Hoc
- Please provide any type of access they may have. 
  > ex: SOCKS, Pagerduty, Google analytics, ect.
  AWS, SOCKs?, unknow as of others. 
 
## AC
 - [x] Remove global/config.yml
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] SOCKS Access removed (if applicable) 
 - [x] AWS Access removed  (if applicable) 
        - Ref: https://dsva.slack.com/archives/CJYRZK2HH/p1588690844268900
 - [x] DSVA Slack (if applicable) 
 - [ ] User removed from the VA GitHub Org
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
No PagerDuty account found for this user.

**Comment by jbritt1** [comment]
User removed from global/config.

AWS/SOCKS access revoked.

**Comment by joanneesteban** [comment]
Google Analytics access revoked.

**Comment by ricetj** [comment]
User removed from VA GH Org
