### ISSUE TITLE
UX: Analyze Medallia user feedback daily – Sprint 35

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#87574]
### User story

As a Cartography team member, I want to create a scalable process for analyzing user feedback (Medallia) and tracking trends over time, so that we and stakeholders can understand how Veterans are responding to the portal and identify areas that are successful or need improvement.

As a Veteran, I want my feedback to be used to iterate and improve the experience on MHV, so that I trust that the VA takes Veterans like me seriously.

### Notes
- Kat has submitted ticket for daily Medallia pulls post launch
- Wes, Kaitlin, Jenny & Robyn have shared understanding of integration launch KPIs to track in [this doc + Mural](https://docs.google.com/document/d/1Qah8gSA6JCqEILg4hC1LTlmNSH9sRYRiWai3iprWgUg/edit#heading=h.4ku8bv7bajcw)
- post-launch [UX KPIs mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716414036737/5aa77bac68425356bf314724636ed828f6bb5743?wid=0-1716421371873) for reference

Possible tasks:

## Acceptance criteria
- Analyzed survey responses daily 
- Grouped responses that are actionable regarding the UX (pain/joy points) for solution exploration
- (If needed:) Created tickets for any solutioning required based on feedback
- Ticketed next sprint's user feedback analysis work

**Comment by fmccaf1** [comment]
I'm realizing looking at this ticket that you won't need to pull data from Medallia because it's already coming on a regular basis. If possible this sprint, it would be great if you (whoever ends up taking on this ticket) could edit that regular report both for most recent days and going forward to include both /my-health/ and /my-health. Let me know if you have questions!

**Comment by katbrinkley** [comment]
did not mean to close this, so sorry!

**Comment by jonathanjnelson** [comment]
@jonathanjnelson Requested data pull from 06/17/2024 -
07/8/2024 for https://www.va.gov/my-health 

@katbrinkley Requested that both https://www.va.gov/my-health and https://www.va.gov/my-health/ will be included moving forward (7/9/24)

**Comment by jonathanjnelson** [comment]
[Qualitative analysis (Sharepoint) ](https://dvagov.sharepoint.com/:x:/s/oitmhvonvagovcartographyteam/EVY2_fiGl7dMpbL1nhDRDjQBbvhwxRsKc611SDKas9oa7A?e=G5mtdl)
