### ISSUE TITLE
Add state in DD where user hasn't set up but is eligible

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#8757]
## Background

Mocks don't seem to call out the state where a user has not yet set up DD but are eligible to do so.  User +200 can be used to view this in staging. 

##Additional Information

This is related to #5355

**Comment by tressaellen** [comment]
@erikphansen user +200 does not work anymore, any ideas on another user that could show this? Or do you have the screenshot at all?

**Comment by erikphansen** [comment]
I'll let someone know that user 200 doesn't work at all anymore. I don't know of other test users who are not set up with DD but are eligible to set it up. @mshea0606 can you make a note that we need to have a test user set up that allows us to see the "direct deposit not set up" state? And then we'll need to update [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/test-users.md) as well.

All that said, here is what the "not set up" state looks like with v1:

![image](https://user-images.githubusercontent.com/20728956/84156050-e6bad980-aa1d-11ea-87ea-9bf49b2ccd55.png)

**Comment by erikphansen** [comment]
@tressaellen confirmed that user 200 has a date of death so we can no longer log in with that user.

**Comment by tressaellen** [comment]
Thanks for looking into this @erikphansen

**Comment by erikphansen** [comment]
@tressaellen did you see that user 201 should work?

**Comment by tressaellen** [comment]
Ooh nope! But now I know, thanks!

**Comment by tressaellen** [comment]
![Screen Shot 2020-06-14 at 9.36.57 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/9794f07c-6ec6-4a06-8b98-f23a47176574)
