### ISSUE TITLE
[DOCUMENT]: GIBCT SCO - Dear SCO letter links MUST point to valid resources

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#8758]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

VA 508 office has identified the [Dear School Certifying Official](https://www.benefits.va.gov/GIBILL/docs/fgib/107_TandF_SCO_letter.pdf) PDF has a few links that are not pointing to valid URLs. It appears the links are breaking if they span across multiple lines. Screen shot attached below.

## Related Issue
* #3918 

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Remediation Resources
* Update the link URLs or ensure they don't break when spanning two lines. This might be an issue how Word or InDesign is interpreting line breaks.

## Acceptance Criteria

* [ ] Links open the intended URL

## Screenshots or Trace Logs
![dear-sco-links](https://user-images.githubusercontent.com/934879/81092129-c69b7600-8ec5-11ea-8139-d757acb38fba.png)

**Comment by desireeturner** [comment]
@TamGIBill I believe this is content that you can update. Please let me know if it is not. Thank you!

**Comment by TamGIBill** [comment]
Letter has been removed.
