### ISSUE TITLE
Flipper UI access for Liz Wendling

### ISSUE THREAD

**Issue by GovCIOLiz** [department-of-veterans-affairs/va.gov-team#87585]
### Your Name

Elizabeth Wendling

### Your GitHub handle (Flipper UI access is managed through GitHub)

GovCIOLiz

### Team, Role, and Company of the target individual

VFEP, Lead Frontend Dev @ GovCIO

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I'm the lead frontend dev on my team

**Comment by GovCIOLiz** [comment]
<img width="836" alt="Transmittal" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/170662489/4f79d34d-4dcb-4b86-bd66-6960fc24dcc0">

**Comment by bdech** [comment]
Hi @GovCIOLiz, I'm not finding you in Atlas. Have you gone through [Platform Orientation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)?  If not, can you please create a request from the link I sent you.

**Comment by GovCIOLiz** [comment]
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85473
- https://www.va.gov/atlas/product_directory/team_members?filter_by=first_name&filter_type=includes&filter=elizabeth&commit=Filter

**Comment by bdech** [comment]
@GovCIOLiz You've been granted access to `production` and `lower` environments.
