### ISSUE TITLE
Remove comment box + additional supporting docs option from Medicare section

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#87587]
As a user, I don't want to enter Medicare data that isn't represented on the paper OHI form so that my effort isn't wasted.

Acceptance criteria:
1. Additional comments box removed from Medicare section of form
2. Additional supporting docs option removed from Medicare card upload dropdown

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30829) - waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 @syd-hoeper This has been merged and should be visible on staging shortly. Thanks!

**Comment by marywang2** [comment]
@jamiefiore for awareness.
