### ISSUE TITLE
Design | Ch33 Migration | Update User Flow in Figma

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#87581]
## Background 
Now that we're close to launching we should update the user flow to more closely align with what is going to be in production. 

- [This user flow](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=0-1&t=tjUtMzjdL8IjTPXy-0) should be updated to show the unified form in lieu of the separate EDU and C&P forms. 
- [The desktop mock should also be updated but doesn't need to have the user flow just the unified form.](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=0-462&t=tjUtMzjdL8IjTPXy-0)

## Tasks 
- to be added by design 

## Acceptance Criteria 
- The figma files show the unified form

**Comment by ACParker89** [comment]
@twoangstroms - this is tentative for sprint 40, and will work as a pair on this with Travis. 
- Create a copy file

**Comment by mtcA6** [comment]
@ACParker89 as soon as we ended the call i found the link, [we actually already have the updated user flow w the unified form here](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=239-9210&t=nVUtZ1tdAaid0kKT-0) 

@twoangstroms it may still be worth familiarizing yourself [w/the current flow that's live in prod ](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=0-1&t=L6SGnTWVNzG15ZaM-0)and the updated flow that uses the unified form but I think we don't need this ticket, unless you want to use this ticket as a way to familiarize yourself w/figma. 

[Alternatively, we have this story that would also help you get familiar w/figma](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85867)

**Comment by twoangstroms** [comment]
Will close but noting this is an ongoing learning process
