### ISSUE TITLE
Add link for new page on checking the status of a claim (BTSSS)

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#87584]
## Description
The beneficiary travel team is standing up a new page on VA.gov that will allow Veterans to check the status of already filed travel reimbursement claims. This page will not require users to go to the BTSSS platform (external site) to see their claims. But users will still have to go to that site to file new claims or manage (make updates / do anything) to their claims. 

When the new page is ready for launch (ETA late July/August per @kristenmcconnell) we need to add a new link to the My HealtheVet on VA.gov home page to send users there. 

Kristen says we may want to sync the launch of this link with the product's launch, but it would be okay for ours to be a fast-follow. cc @ayush-chak for visibility into this ticket.

### User story
As a Veteran, I want to be able to find a link that tells me how to check the status of my existing travel reimbursement claims directly on VA.gov, so that I can stay within the health portal and don't have to travel to another website for that information. 

### Notes
- Direct any questions about implementation to @ayush-chak or @kjduensing (BTSSS team)
- Per appointments ux sync on 7/2/2024, @kristenmcconnell would like us to add a second link for BTSSS per this design (below) which she stated feels more consistent with how other tools handle similar task distribution (i..e appointments has a link to schedule and another to manage/view).  

![Screenshot 2024-06-24 at 3 33 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/7142280f-f9e2-4fd0-a2a8-16a40a27bb83)

Possible tasks:
- [ ] Add new link text: **"Check travel reimbursement claim status"** to landing page under the payments box
- [ ] Destination URL should be: va.gov/my-health/travel-claim-status

## Acceptance criteria
- [x] New link text has been added with correct formatting and URL destination **behind their feature flag**
    - [x] Feature flag: [travel_pay_power_switch](https://api.va.gov/flipper/features/travel_pay_power_switch)Main switch for the Travel Pay feature on VA.gov using the new BTSSS (travel pay) API. Enabled - Requests are handled as normal. Disabled - Requests are not handled. Server returns a 503 (Service Unavailable) until re-enabled.
- [x] QA review
- [x] Confirmed GA event is captured for this link
- [x] Notified Ayush Chakravarty that the link is ready (do NOT turn on feature flag)

**Comment by kristenmcconnell** [comment]
[Slack thread](https://dsva.slack.com/archives/C05UTPZRZFY/p1720030915108269?thread_ts=1719254561.664209&cid=C05UTPZRZFY) outlining what Sara and I talked about, which resulted in this ticket. cc @sterkenburgsara

**Comment by kjduensing** [comment]
Hey team - I'm an engineer on the beneficiary travel team. In preparation for this, I created a [PR that adds the link to the appropriate section](https://github.com/department-of-veterans-affairs/vets-website/pull/30245). There is some feature flag work in there as well, [as discussed with Jim in this thread](https://dsva.slack.com/archives/C04DRS3L9NV/p1717787202528799?thread_ts=1717595149.897789&cid=C04DRS3L9NV).

**Comment by wesrowe** [comment]
per Ayush [in slack](https://dsva.slack.com/archives/C05UTPZRZFY/p1720793834715979?thread_ts=1719254561.664209&cid=C05UTPZRZFY), BTSSS might be ready for us to add the link around the end of July. So sprint 37.

**Comment by wesrowe** [comment]
I just pinged the slack thread above to check status. (7/30)

**Comment by wesrowe** [comment]
per Ayush, mid-August target date

**Comment by wesrowe** [comment]
update today said another couple weeks

**Comment by kjduensing** [comment]
@wesrowe if you're talking about my update, I said a couple of **days**, not weeks :)

**Comment by wesrowe** [comment]
thanks for the clarification – but either way we'll be here when you're ready!

**Comment by kjduensing** [comment]
Thanks Wes!

**Comment by ayush-chak** [comment]
Hi All, here’s our rollout plan as of today:

Currently: 2 familiar users behind the feature flag
Next (pending some admin roadblocks): 19 members individually selected in a “friends and family rollout”
Mid-October (expected per our OCTO POs): 5%, 25%, 50%, 75%, 100% users at 2-3 days each. This is of course somewhat variable depending on outcomes.

Does that help in approaching the feature flag question?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the new link has been added to the MHV landing page for checking the status of a claim. When a user clicks on the link, it directs the user to: https://staging.va.gov/my-health/travel-claim-status. This is behind a feature flag. No regression issues with the feature flag disabled as well. 

![Image](https://github.com/user-attachments/assets/55ebdaef-fcba-49df-9abd-13c511b0bfa0)

**Comment by allanto-ah** [comment]
Slack conversation in regards to the empty space in the "Medical supplies" box: [Slack link](https://dsva.slack.com/archives/C0581MN69TJ/p1727814351734569). Team is aware, but nothing can be done about it at the moment, so it'll be there for now.

**Comment by allanto-ah** [comment]
Notification to Ayush Chakravarty in slack thread [here](https://dsva.slack.com/archives/C0581MN69TJ/p1727403671187579)

**Comment by wesrowe** [comment]
I went ahead and tested in Staging. 
![Image](https://github.com/user-attachments/assets/89f45a75-1182-4cb0-804d-6fad8e07d217)

**Comment by allanto-ah** [comment]
Thanks @wesrowe! Sorry, for reason my verification comment didn't show up, but verified using Debugger for Google Analytics extension.
