### ISSUE TITLE
Contact Center Review for [AE Profile - Direct Deposit]

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#87602]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

The Authenticated Experience Profile has an application for updating direct deposit. This feature has been live for several years as two separate forms within the Direct Deposit Information page. The two forms are being combined into one unified form. 

### Launch Date
*Please provide the launch or rollout date and details.*
- [Release plan, tentative launch of the revised UI 7/17](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/ch33-bdn-corpdb-migration/release-plan/README.md)
### Version Number
*Please provide the version number of the guide and/or video.*
- Version 10
### Product Guide
*Please provide product guide link*

- attached the file here [VA.gov.Profile.product.guide.v10.07032024.docx](https://github.com/user-attachments/files/16087016/VA.gov.Profile.product.guide.v10.07032024.docx)
- or it can be found in our [GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/README.md)

### Product Video
*Please provide product video link*

- n/a

### Product Video Transcript
*Please provide product video transcript link*
- n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Draft looks good, sending to VEO for their review.

**Comment by starlow00** [comment]
There are no changes from VEO. The current copy is attached to this ticket. Please use it for future updates/revisions. Thank you!

[VA.gov.Profile.v10.07032024 SRT 07032024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnEvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b1c7914b6522090fb33b7c26343100ef6ba98cc/VA.gov.Profile.v10.07032024%20SRT%2007032024.docx)
