### ISSUE TITLE
[Doc Upload Polling] Implement Model In Separate PR

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#87619]
Per the [vets-api documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations), Migrations need to have 3 PRs to ensure uptime.

Model, Model spec, and Spec factory [PR 15964](https://github.com/department-of-veterans-affairs/vets-api/pull/15964/files) into a unique pull request.

**Comment by freeheeling** [comment]
Drafted [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17407) that creates model, and includes supporting tests. Awaiting merge and deploy of PR [#17405](https://github.com/department-of-veterans-affairs/vets-api/pull/17405) in ticket #87617.

**Comment by freeheeling** [comment]
1. Drafted [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17407) that creates model, and includes supporting tests. Awaiting merge and deploy of PR [#17405](https://github.com/department-of-veterans-affairs/vets-api/pull/17405) in ticket #87617.
2. Drafted subsequent [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17439) that creates an object to encapsulate the parsing of a Benefits Documents API 'uploads/status' response and updates the state of a polled `Lighthouse526DocumentUpload` record.
