### ISSUE TITLE
UX: Landing page gap analysis

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#87610]
## Description
Following the team's UX sync on Monday, 7/1/2024, we are pausing on tickets related to design experiments on the MHV landing page and instead are being asked to respond to pain points identified by Veterans via data monitoring on the landing page (quantitative analytics or Medallia feedback). 

This assumes that all the necessary jobs of the landing page are already being done well. In order to better assess that assumption, we will take on some work this sprint to do a medium-weight gap analysis to better understand roles that this "home" page could play in meeting Veteran needs and/or expectations: 
1. Identify gaps between Veteran needs/expectations named in earlier generative research studies and what is currently offered by the MHV on VA.gov home page. 
2. Identify gaps between the current MHV on VA.gov home page and other health portals with top market share. 

### User story

As a Cartography team member, I want to analyze existing My HealtheVet research to identify any gaps between Veteran expectations with the MyHealtheVet landing page and what Veterans are currently experiencing on that page, so that we can communicate and assess the potential value of adding new design features that could address those expectations. 

As a Cartography team member, I want to analyze other common and highly used patient-facing health portals, so that i can see the hierarchy of roles that entry points/landing pages in those products are taking on, and document any gaps between those experiences and what our landing page is currently able to offer Veterans; this will illuminate ways in which we may (or may not) be meeting user expectations. 

### Notes
- Gap analysis work can serve as an input into the landing page prioritization effort named in follow-on ticket #86875.
- [Started Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720032090287/45ea8c3a6b9565d9fc9153ef904439297f8e5849?sender=uf94a77a19aaf687331c09367)

### Possible tasks:
- [x] Analyze previous high-level "concept research" done for My HealtheVet and [linked here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/research/previous-research-on-mhv-on-va.gov.md)
- [x] Conduct competitive analysis and desk research to evaluate other high-touch authenticated health and financial portals to see what types of roles main portal entry points are playing (i.e. navigation, notification, personalization, education, etc.) and in what hierarchy? @katbrinkley @sterkenburgsara 
- [x]  Review Medallia data/past analysis @jonathanjnelson 
- [x]  Document gaps between current-state landing page and any findings from these various analyses in the GH repo research folder. 

## Acceptance criteria:
- [x] Gap analysis is documented in GH and can be an input into strategy work articulated in follow-on ticket #86875

**Comment by fmccaf1** [comment]
[I started a mural yesterday to gather thoughts on research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719933641655/03e9a0ce9c86b8258cf7860d63b18b0ec530598e?sender=ua13e567cb5c4221acaa14949)

**Comment by wesrowe** [comment]
@fmccaf1 @sterkenburgsara @jonathanjnelson @katbrinkley – I created a more focused epic for this to live under, #87874. Please have a look at that epic and make any updates you feel appropriate.

**Comment by wesrowe** [comment]
ux refinemnt:
- gap between VA research and existing LP
- gap between LP and expectations from other websites
- next step: prioritize gaps

**Comment by sterkenburgsara** [comment]
Gap analysis work captured in these two artifacts: 
* [MURAL](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720032090287/45ea8c3a6b9565d9fc9153ef904439297f8e5849?sender=uf94a77a19aaf687331c09367)
* [GH Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/gap-analysis-2024.md)
