### ISSUE TITLE
[Doc Upload Polling] Implement Migration In Separate PR

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#87617]
Per the [vets-api documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations), Migrations need to have 3 PRs to ensure uptime.

split the db steps from [PR 15964](https://github.com/department-of-veterans-affairs/vets-api/pull/15964/files) into a unique pull request.

**Comment by freeheeling** [comment]
Drafted [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17405)
