### ISSUE TITLE
Investigate Datadog RUM issues with actions

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#87625]
## Description

Spawned from https://github.com/department-of-veterans-affairs/va.gov-team/issues/86178, we have a few open support tickets with Datadog support because we are seeing issues with 

* actions with unexpected action names (accordion buttons)
* actions sometimes being counted twice (one custom, one normal link action)

### User story

As a Cartography team member, I want Datadog RUM to record actions accurately and reliably

### Notes

DDG support requests:

- https://help.ddog-gov.com/hc/en-us/requests/5744 (@dcloud is cc'd on this)
- https://help.ddog-gov.com/hc/en-us/requests/5841 (@dcloud cannot view as of 7/3)

#### Prior investigation

[Notes from prior work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86178#issuecomment-2204275826):

> While [department-of-veterans-affairs/vets-website#30605](https://github.com/department-of-veterans-affairs/vets-website/pull/30605) appears to have made some of the console functions work, making it possible/easy to grab a session_id via `DD_RUM.getInternalContext()?.session_id`, there are remaining issues:
> 
> * signficant lag between actions taken in a session and events appearing in DDG. Need to reload datadog to see events appear
> * The issues with labelling click actions on the "Learn More" content accordian
>   
>   * Opening the accordion appears to record sibling content: "Welcome to the new home for My HealtheVet. Now you can manage your health care needs in the same pla [...]" - `@action.id:f1861868-b2dc-4ca5-b04a-20d87083d6d6`
>   * Closing grabs the content inside the accordion, per `@action.id:1c375a4c-c7ef-4015-a282-198f9b1e43fb`
> * Possible double-counted click actions, e.g. `@action.id:e9163295-a195-49c3-a20f-59f18f8bba8c` -> `@action.id:1976d1e0-8fdc-4811-9447-61540ddf68c3`… I wouldn't expect to see the non-custom click being recorded any more on links that have the `datadogRum.addAction` call
> 
> Per my clicking around in staging - `@session.id:2c298dca-f11a-4a8d-a42b-f53e4e1eb0d1`
> 
> These observations should probably be put into a "Datadog debug" ticket if we need to continue to fix things with DD_RUM

Possible tasks:
- 

## Acceptance criteria

- 
- QA review
- A11y review

**Comment by dcloud** [comment]
Noting that the at least two of the places the we see incorrect action names being recorded are on links within web componenents: 

- `<va-alert-expandable>` has the accordion toggle that uses an anchor, and the anchor text is not recorded, but text near the anchor is
- `<va-link>` components in the "hub links" are recording all the text in the container for the `<va-link>`

## Aside on datadogLogs

Talked with someone on pensions and [they wired up datadogLogs](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/pensions/hooks/useBrowserMonitoring.jsx) in addition to RUM. I wonder if this could help uncover client-side errors generally… I'm not sure how it might help with our RUM woes

**Comment by dcloud** [comment]
Also seeing [an action](https://vagov.ddog-gov.com/rum/sessions?query=%40type%3Aaction%20%40application.id%3A1f81f762-c3fc-48c1-89d5-09d9236e340d%20%40action.name%3A%2ASOON%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZCYk3Wb7FSrtAAAAAAAAAAYAAAAAEFaQ1lrNTJvQUFBalFqMFN6ZHpTSUFBQgAAACQAAAAAMDE5MDk4OTMtZDIzMy00MmRmLTg1YmUtNjkyYjkyYzEzMjAx&fromUser=false&sort_by=timestamp&sort_order=desc&track=rum&viz=stream&from_ts=1720460403171&to_ts=1720546803171&live=true) on the temp Medical Records page that also appears to grab random text. Not sure where the click is for

> click on Medical records COMING SOON Soon, you’ll be able to find, print, and download your medical records o [...]

My guess at this time is a click on an element within the `VaBreadcrumbs` in [MedicalRecords.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-landing-page/components/MedicalRecords.jsx)

**Comment by dcloud** [comment]
If I run vets-website locally with DDG manually _enabled_, I can pause in various points in the Datadog code, and using that I saw that `getTextualContent` gets run for the accordion, and that function tries to extract text from the `<va-alert-expandable>` web component rather than the `<a>` within `<va-alert-expandable>`. Since that is the `element` that gets inspected, it makes sense that DDG would grab the whole text inside the expanded element. 

I should look at the `<va-link>` elements since I'd expect that to grab the correct text because that component is a wrapper around a stock `<a>` element.

**Comment by dcloud** [comment]
Checking out the `<va-link>` and seeing that `computeClickActionBase` sees the event.target as the `<va-link>`… `event.target.textContent` and `event.target.innerText` are empty strings… 

The _fallback_ strategy in Datadog RUM code will go up the DOM tree [from elements to parent elements](https://github.com/DataDog/browser-sdk/blob/30e3c8c4447dc8fcbaed8a12628e417e40d2dae5/packages/rum-core/src/domain/action/getActionNameFromElement.ts#L177) to grab text. This is what we're seeing, though I was seeing just the heading above a link… 

It looks like it goes `va-link -> li -> ul.mhv-c-link-list -> nav -> div.vads-l-col--12`, and the div's `element.innerText` is `"My VA health benefits", and at least on localhost the recursion up the tree ends. That doesn't quite match what we've seen in staging and production where the entire div's content is in the action.

I'm not seeing those click actions appear in datadog, though my session did.

**Comment by dcloud** [comment]
Adding `data-dd-action-name` gets the Rum code to grab that value, but I still don't see actions recorded into ddg during my testing (a session is recorded but not the actions), so hard to confirm that would work in other environments

**Comment by dcloud** [comment]
As the event flow shows, I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/88060 which is to start discussion with VADS about the web components and how they interact with Datadog

**Comment by dcloud** [comment]
To reiterate findings:

- `<va-link />` wraps regular `<a />` link, but doesn't provide link text via `innerText` or other DOM methods. Since that component is [a wrapper around a normal HTML anchor](https://github.com/department-of-veterans-affairs/component-library/blob/fd18264145455efa224e0a1239136ecd00641abf/packages/web-components/src/components/va-link/va-link.tsx#L240-L246) with a custom Google Analytics event, there is littler reason to use it when the custom event is disabled.
- `<va-alert-expandable />` contains a `<a />` link as well, but is used as a button to show/hide the expandable alert. The only immediate remediation here would be to add a `data-dd-action-name` prop. Ultimately, the component-library needs to fix the issues with the component not providing the text of the clickable link-button

**Comment by wesrowe** [comment]
Closing
