### ISSUE TITLE
[LH Doc Upload] TBD- Trigger message to Veteran when Polled Document Upload Fails

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#87622]
TODO sync with @NB28VT @tblackwe @freeheeling to determine requirements for this ticket. 

## Overview
When we migrate to Lighthouse, we will add a new failure point where Lighthouse accepts the document. To track this we will have a 'polling' job that runs every hour and checks every upload we don't have a status on. If the this fails and the documents don't get it into the efolder Veteran's benefits will be impacted. 

When benefits upload API fails to send the doc to lighthouse, the new failure point **Polled document upload fail** in the LH flow occurs and should trigger a notification or a job to report the case is incomplete. This trigger is not a real time notification because LH failure will happen after timing out (_currently we fail in real time, this is changing to 48 hours_). This should be an edge case for system failures that were not resolved. 

Two options (so far) for what do do when the **Polled document upload fail**: 
1. Notify the Veteran that something went wrong and they will need to do the workaround (i.e., mail) to get their documents to the VA. Currently we have emails for 526, 424, 0781. 
2. ~Since this is a system error, rather than notifying the Veteran of a failure and placing the onus on them to deliver a failed document through other means, instead treat any failures as instances to be remediated (task to be determined).~

## Notes
Currently, a response of 'FAILED' from the Lighthouse Benefits Documents API '/uploads/status' endpoint for a given document upload will increment a `StatsD` metric and log a warning, along with additional identifying data, of 'Benefits Documents API responded with a failed document upload status'. The only alert that has been created is for failed 0781 document upload failures.

## Questions

1. If a Veteran whose document failed delivery to VBMS/BGS, regardless of document type, should they be notified of the failure via email? 
2. Would it be better, rather than notifying the Veteran of a failure and placing the onus on them to deliver a failed document through other means, to instead treat any failures as instances to be remediated?
3. If we need to notify the Veteran can we use the existing emails that are in progress/production today? 
4. Also to be determined is whether our responsibility for a failed document upload is finalized once email notice is sent. If so, should a tracking state be implemented to indicate notice of failure was sent thereby absolving us of responsibility?

**Background on why this is needed**
OCTO felt that polling was a must have. Even though Lighthouse has polling of their own, it would not tell benefits that it failed or not. Since we won't know when it fails from the LH polling, we need to build a polling because we don't have a better solution for tracking when the API fails. When it does fail it would go into the silent failure flow and an email would be triggered to notify the user. 

OCTO felt the email was still necessary and that was what they decided we should do.

**Comment by lisacapaccioli** [comment]
@tblackwe When do we need to get this done by?

**Comment by tblackwe** [comment]
Prior to when the document upload lighthouse migration is live in production

**Comment by lisacapaccioli** [comment]
@tblackwe and @freeheeling I reworded the objective of the ticket and some of the ask. Let me know if they make sense (feel free to tweak if you feel it needs it). Let's talk to @juliepedtke first about the best UX for this type of situation. Then when we feel ready we can take it to OCTO with our recommendation and ask them if they are OK with it. Thanks

**Comment by lisacapaccioli** [comment]
I moved this to be solutioned as part of the document upload migration vs. polling. It may be the ticket we need to start with before we can do others.

**Comment by lisacapaccioli** [comment]
@NB28VT @ajones446 @kylesoskin - Do you still want this ticket for tracking that we will trigger an email after LH polling returns explicit failure/error? If not, we should track it somewhere so that we validate it when the time comes. Totally up to you all where you want to track it. Thanks
