### ISSUE TITLE
[Doc Upload Polling] Finish PR for Implementation

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#87621]
After #87619 and #87617 are complete, Clean up the PR at https://github.com/department-of-veterans-affairs/vets-api/pull/15964 to finalize tests and resolve linting issues

**Comment by freeheeling** [comment]
1. Drafted [PR #17439](https://github.com/department-of-veterans-affairs/vets-api/pull/17439) that creates an object to encapsulate the parsing of a Benefits Documents API 'uploads/status' response and updates the state of a polled `Lighthouse526DocumentUpload` record.
2. Drafted [PR #17460](https://github.com/department-of-veterans-affairs/vets-api/pull/17460) that creates `DocumentsStatusPolling` and `UpdateDocumentsStatus` service classes.
3. Drafted [PR #](https://github.com/department-of-veterans-affairs/vets-api/pull/17473) that creates `Form526DocumentUploadPollingJob`.

Each is dependent on the one that precedes it.
