### ISSUE TITLE
DD Alerts - Create alert for failed 0781 document uploads

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#87623]
When an 0781 upload is marked as failed in Document Polling, generate an alert so the team knows to go remediate it.
```[tasklist]
### Tasks
- [ ] create Datadog monitor to watch metric and trigger alert
- [ ] set notification channel
```

**Comment by freeheeling** [comment]
@tblackwe Should a alert be created only in the event a 0781 document upload fails, or would it be better to alert regardless of document type: veteran upload, 0781, 0781a, or BDD instructions?

Also, included in @NB28VT's original implementation is tracking to indicate a document has been in a pending state for more than 24 hours. I'm not sure a monitor is warranted for alerting on such a state, or if logging of a potential processing timeout status is sufficient. Thoughts?

**Comment by freeheeling** [comment]
Alert created – https://vagov.ddog-gov.com/monitors/244896?view=spans – but could probably benefit from some refinement, if you're able to help me finalize, @tblackwe. Thanks!

**Comment by freeheeling** [comment]
Alert created and code developed. However, currently blocked by the following when I attempt to push up my local branch:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
indicating Git client is unable to authenticate with GitHub using SSH keys.

Will troubleshoot tomorrow.

**Comment by freeheeling** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17625) to 'log when Form 0781 document upload fails' ready for review.
