### ISSUE TITLE
[DOCUMENT]: GIBCT SCO - CONSIDER adding headers to the Dear SCO letter

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#8765]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

VA 508 office has identified the [Dear School Certifying Official](https://www.benefits.va.gov/GIBILL/docs/fgib/107_TandF_SCO_letter.pdf) PDF has some text that appears to be headings. These look like the sidebar sections identified in the screenshot below.

## Related Issue
* #3918
* #8758 
* #8761 
* #8764 

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* [ ] Acrobat Pro accessibility checker validates any headings that are tagged
* [ ] Heading(s) announce properly to screen readers

## Screenshots or Trace Logs
![Screen Shot 2020-05-05 at 11 56 35 AM](https://user-images.githubusercontent.com/934879/81093436-be443a80-8ec7-11ea-9cb1-9445780e8ee3.png)

**Comment by desireeturner** [comment]
@TamGIBill I believe this is content that you can updated. Please let me know if it is not. Thank you!

**Comment by af-manish** [comment]
@noahgelman  Where are we with this update?

**Comment by af-manish** [comment]
@noahgelman <cc @ERRonat0609 @mrblanco1 > Gentle nudge.

**Comment by TamGIBill** [comment]
This was resolved a while ago.  The link is not valid.  The letter has been removed.

**Comment by mrblanco1** [comment]
Per TamGIBill's confirmation above, we are closing this Issue since it is not valid any more as the letter has been removed.

Abe Blanco (AFS GIBCT)

**Comment by ERRonat0609** [comment]
Closing this issue per comments above.
