### ISSUE TITLE
Help section and filter design changes

### ISSUE THREAD

**Issue by micahtaylor** [department-of-veterans-affairs/va.gov-team#87697]
## Description
These are changes that came form CAIA and Kristen for the help section and filters.

If helpful code can been gleaned [here](https://q5xnjl.csb.app/travel-claim-listing.html)

<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWk1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--056da26206e69bea7318322ce9bea722d7fa4462/Screenshot%202024-07-03%20at%203.44.57%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 3.44.57 PM.png" />

**Comment by micahtaylor** [comment]
The gray text that says "4 results, sorted by newest first with 3 filters applied" is visible when on the sort and filters are applied. Kristen believes this will come up in Staging review as it has with other teams that are using filters.

**Comment by athifw** [comment]
<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0w3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c8d7429c9d92576d6ce051ae473f55d3342c6f9/Screenshot%202024-07-22%20at%202.05.22%E2%80%AFPM.png" alt="Screenshot 2024-07-22 at 2.05.22 PM.png" />

This is what I've done locally - @micahtaylor does that look good? The change to the filters ("4 results, sorted by newest first with 3 filters applied", for example) will be made in another ticket.

**Comment by micahtaylor** [comment]
@athifw Can you upload the screenshot again? It's not showing in the comment above.

**Comment by micahtaylor** [comment]
Atif DM'd this pic over...
![Screenshot 2024-07-22 at 2 05 22 PM](https://github.com/user-attachments/assets/9aed6700-e3ab-499e-9a2e-684b8f4ccef3)

**Comment by micahtaylor** [comment]
My feedback in the DM...
The desktop view should only span 8 columns. I have these classes in that div if it helps…. `vads-l-col--12 vads-u-padding-x--2p5 medium-screen:vads-l-col--8`
Also you can remove the external icon after “(opens in new tab).”

**Comment by athifw** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/30965
