### ISSUE TITLE
Additions to Figma setup guidance

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#87695]
### Description
This is a good overview of the content as is, but additions that might be useful: a direct link to download (saves a step or two) or to the Figma site, a screenshot of how to log in (what email to use to set up an account, how to store password securely).

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/research-design/figma-accounts-at-va

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by jknipes** [comment]
Hi @twoangstroms , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@naomimarcussen

**Comment by naomimarcussen** [comment]
I've added a Getting Started section with additional information noted in this ticket.

**Comment by twoangstroms** [comment]
Fantastic, thanks!


Dan Turner

Senior UX Designer, Ad Hoc
***@***.***

￼

**Comment by naomimarcussen** [comment]
Thank YOU for the feedback! :)

**Comment by jknipes** [comment]
This ticket appears to be complete, closing as _Done_
