### ISSUE TITLE
Build: Add KISS configuration for Digital Forms

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#87714]
We will do this work in `content-build`. [In a separate ticket, we'll add a normalization layer](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88634) that will allow us to more easily move this to `next-build` in the future, if needed.

## Acceptance Criteria
- [x] A KISS 'endpoint' is defined for fetching all Digital Form nodes
  - [x] The endpoint URL is `data/cms/digital-forms`
  - [x] All currently defined fields are included in the output

**Comment by Karak888** [comment]
content build or next build decision- CMS team will be directing us with this effort

**Comment by Karak888** [comment]
move forward with content build - bulk of what we create is not going to be specific to either of the repos. 

Next step circle back with CMS but advocating for content build 
- define a normalized layer
