### ISSUE TITLE
Add `Digital Form` content type

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#87711]
Initially, add most basic fields.

## Acceptance Criteria
- [x] Content type is configured
- [x] Fields are added:
  - [x] Form id/#
  - [x] Form name
  - [x] OMB tracking id

**Comment by derekhouck** [comment]
I am currently unable to push my branch to the va.gov-cms repo on GitHub.

**Comment by derekhouck** [comment]
GitHub issue resolved. PR created: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18717
