### ISSUE TITLE
CT-EYB: Focus is set on the "Your estimated benefits" panel after recalculation scrolls to top of page

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#8771]
When selecting "Calculate Benefits" on the profile page, if you scroll completely past "Your estimated benefits" and select the calculate benefits button it will scroll all the way to the top. If you still have "Your estimated benefits" still on the screen it goes to where it should be. Observe below
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/81103671-64e80580-8edf-11ea-94a3-5a539be43bc4.gif)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12521

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/81206814-a38ec600-8f9a-11ea-8682-423744ffe2a2.gif)

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
