### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#87710]
### Your Name

Shaun Burdick

### Your GitHub handle (Flipper UI access is managed through GitHub)

@shaunburdick

### Team, Role, and Company of the target individual

Benefits Team 1, Team Lead, Coforma

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need this access to enable/disable production features for my teams as Tech Lead.

**Comment by davidpetras** [comment]
@shaunburdick you have been granted access to `lesser environments` and `prod`.
