### ISSUE TITLE
Integrate single-app form-renderer code from initial spike

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#87719]
In the [initial spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83280), we were able to implement an app that dynamically loaded a `formConfig` object based on the url. 

We need to incorporate this code into our app that we have since [officially started to develop](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88669). Importantly, we need to add some testing.

## Acceptance Criteria
- [x] Code from initial spike is incorporated
- [x] Tests are added

**Comment by Karak888** [comment]
continue to build out our app.
