### ISSUE TITLE
Referral introduction page with referral and patient preferences

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87724]
[Wireframe](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2169-36403&t=V9cBvI3nquLU6fP9-4)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/87724?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by lee-delarm6** [comment]
Needs wireframe added/linked (or screenshot)

**Comment by benbrasso-agile6** [comment]
Will add; but ticket is specific for integrating mocks with the FE
