### ISSUE TITLE
[Integrate mocks] Filtering providers page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87729]
Wireframes
- [Initial view](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2439-52550&t=V9cBvI3nquLU6fP9-4)
- [Filters selected](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2439-52549&t=V9cBvI3nquLU6fP9-4)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/87729?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by simiadebowale** [comment]
endpoint: ` /vaos/v2/wellhive/provider-services`
path: `/src/applications/vaos/services/mocks/wellHive/providerServices.json`
