### ISSUE TITLE
[Integrate mocks] Provider list based on referral and patient preferences page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87727]
[Wireframe](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2424-42620&t=V9cBvI3nquLU6fP9-4)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/87727?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by simiadebowale** [comment]
endpoint: ` /vaos/v2/wellhive/provider-services`
`/src/applications/vaos/services/mocks/wellHive/providerServices.json`

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 rdy to close?
