### ISSUE TITLE
Remove `flipper_features` record when toggle removed from `features.yml`

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#8772]
## Background
[Slack chat](https://dsva.slack.com/archives/CQHBJ5U06/p1588695414101600):
The Flipper initializer adds new feature toggles to the `flipper_features` as they are added in the `features.yml` file [here](https://github.com/department-of-veterans-affairs/vets-api/blob/048f20f56ea0d786902873f2a30a41718d257dfc/config/initializers/flipper.rb#L46)
However, when an entry is removed from `features.yml` there is no code that removes it’s record from the `flipper_features` table.
As a result, our list of feature toggles just keeps growing and never removes the ones that have been removed from the codebase.
We should add some code to the initializer that removes `flipper_features` records that no longer have a corresponding entry in `features.yml`
This can be done using `Flipper.remove('feature_name')` [link](https://github.com/jnunemaker/flipper/blob/master/lib/flipper/feature.rb#L88).
We need to make sure corresponding `flipper_gates` entries are removed too.  Not sure if there is an association in place to handle that (i.e. `dependent: :destroy`) or if it needs to be done manually.

## Acceptance Criteria
- [ ] Add code to the `flipper` initializer to remove `flipper_features` records that no longer have a corresponding entry in `features.yml`.
- [ ] Ensure `flipper_gates` records are also removed.
- [ ] Update documentation so that it's clear that the references to the feature toggle need to be removed from the FE _before_ they are removed from `features.yml` (and subsequently the database)

**Comment by erluti** [comment]
resolved by this PR https://github.com/department-of-veterans-affairs/vets-api/pull/4938
