### ISSUE TITLE
[Integrate mocks] Upcoming appts page with referral task card

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87723]
[Wireframe](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2169-36402&t=V9cBvI3nquLU6fP9-4)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/87723?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by simiadebowale** [comment]
This is blocked, we are still trying to determine what fields VistA api X returns

**Comment by benbrasso-agile6** [comment]
K, I'll move it out of the sprint
