### ISSUE TITLE
[EKS] Upgrade to 1.30

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#87743]
## Description
Upgrade EKS to version 1.30

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/main/terraform/modules/platform-distro/variables.tf#L5

## Acceptance Criteria
- [ ] Platform v.Next is running Kubernetes 1.30

**Comment by keithdadkins** [comment]
@ph-One Please verify ami-019e25935ef9d0510 is the 1.30 you validated.
