### ISSUE TITLE
PEGA Status testing and create documentation

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#87752]
Ticket for testing PEGA status and related DataDog updates.
As a reviewer and user of DataDog dashboard for IVC Champva , I would like to know the basic functionality of the dashboards. In addition, I would like to know how to create and adjust the dashboards as needed in the future.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/datadog_ivcchampva/products/health-care/champva/datadog_dashboard.md
