### ISSUE TITLE
Analytics: Convert DD dashboard to custom metrics

### ISSUE THREAD

**Issue by katbrinkley** [department-of-veterans-affairs/va.gov-team#87751]
### User story

As a Cartography team member, I want to convert all the datadog widgets into custom metrics so that we can preserve this post-launch integration data.

### Notes
- Florence and Kat met with Mark D. and Robyn about how to do this

Possible tasks:
- Attempt to use the same formula from the current queries, should work okay based on what Mark demoed
- Pair with developer to make sure everything looks right and is being tracked correctly

## Acceptance criteria
- Create corresponding custom metrics to all widgets in the MHV Integration RUM [dashboard](https://vagov.ddog-gov.com/account/login?next=%2Fdashboard%2Fhzz-d8e-79j%2Fmhv-on-vagov-integration-rum%3FfromUser%3Dfalse%26refresh_mode%3Dsliding%26view%3Dspans%26from_ts%3D1718392915347%26to_ts%3D1718396515347%26live%3Dtrue).
- Verify with team that everything was converted correctly

**Comment by katbrinkley** [comment]
Updates: All widgets need to be complete before creating custom metrics. 
- The MHV home page main clicks widget still has some clicks that aren't being tracked (Reviee medications, Subscribe to newsletter, and all articles)

Next steps (tickets I will create)
- Convert the funnels widgets into clicks (conv. or eng.) > create custom metrics (next task for me)
- Dashboard the KPI widgets based off of the new custom metrics

**Comment by katbrinkley** [comment]
Blocked until I finish this [ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/88262).

**Comment by wesrowe** [comment]
@katbrinkley, I just noticed this didn't get a Sprint 36 tag. Do you see this as something we're still wanting to do? OR, did we kind of decide to wait and see what the evaluation plan requires?

**Comment by katbrinkley** [comment]
Updates: Chatted with Wes Thursday about this - custom metrics for all the widgets are created, but we're going to hold off on using those to create a whole new dashboard as it's harder than we expected and we think the evaluation plan will show what we need and if custom metrics is the right route or not.

**Comment by wesrowe** [comment]
Additional color on that – we tried making a widget driven by a custom metric, and the number coming out of our custom metric (the numerator for bounce) was about 2.5x the value that the same query surfaced in the RUM version of the widget. So we have some debugging to do and further learning about how to use custom metrics.
