### ISSUE TITLE
Talk to VFF engineers regarding form-submission questions from spike

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#87750]
Contact engineers on the Veteran Facing Forms team to discuss questions we raised as an [outcome of our form-submission spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89650#issuecomment-2361262052).

- [ ] Reach out on Slack to request "review" of spike and post questions for their response.
- [ ] If necessary, schedule face-to-face time for more discussion.

**Comment by Karak888** [comment]
Questions will be listed here

**Comment by ryguyk** [comment]
Slack thread with some discussion on some of the questions: https://dsva.slack.com/archives/C044AGZFG2W/p1727192689513649

**Comment by Karak888** [comment]
Thank you for including the slack thread between you and Nick for context.

**Comment by Karak888** [comment]
Hi Matt, 
I believe it was just a slack chat where Nick provided Ryan with some but not all answers and wanted to keep it for this sprint, but we can close this and create a new ticket for following up with Eric and Robert for future sprint.  @ryguyk I do think that makes sense and moving to close.  Thanks
