### ISSUE TITLE
[FE] Update Task Card

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#87756]
## Description
Task Card design has been updated.

## Wireframes
[Wireframe](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1677-86176&m=dev)
[Wireframe Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86785)

## Tasks
- Update task card

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 / @loripusey / @cgednalske 

Here are screenshots for the new task cards:
<img width="150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUh4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c270034380daba29c78d0b4bd3848a99c3608dc/localhost_3001_health-care_appointment-check-in_appointment-details_0001-0001%20%284%29.png" alt="localhost_3001_health-care_appointment-check-in_appointment-details_0001-0001 (4).png" />
<img width="128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUx4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aea7eea5283f90ea5d98303ffb2eb06370d7d864/localhost_3001_health-care_appointment-pre-check-in_appointments%20%283%29.png" alt="localhost_3001_health-care_appointment-pre-check-in_appointments (3).png" />

<img width="129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVB4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--138c9140dc47ab99e48b7edc789ac953c66d5a27/localhost_3001_health-care_appointment-pre-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%285%29.png" alt="localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (5).png" />

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by zach-park** [comment]
Looks nice! :)

**Comment by brianseek** [comment]
closing this ticket, code review and merging to take place in this ticket for next sprint: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/88841
