### ISSUE TITLE
Identity SDK - Refactor `AuthLevelManager`

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#87763]
Refactor `AuthLevelManager.ts`

```ts
    setAuthLevel(
        action: AuthAction,
        provider: IdentityProviderId,
        value: TAcrValue,
    ): void {
        if (!this.config[action]) {
            this.config[action] = {};
        }
        this.config[action]![provider] = value;
    }
```

The use of `!` is here. `!` is known as the non-null assertion operator. It is basically telling the Typescript compiler that I know the value might be null or undefined, it won't be when this code runes.

However, I would like to review this to see if this could be done with using the `!`

**Comment by parkerbees** [comment]
Created in Jira, cancelling in Zenhub
