### ISSUE TITLE
Analytics Implementation (Foresee) for My VA Dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8776]
# Analytics Implementation or QA Request
## Description
- Is this request for Google Analytics implementation or QA?

This is a request to implement the Foresee survey on the My VA dashboard, which can be seen by logged in users at https://www.va.gov/my-va/

- Who is this request for?

Samara/Matt Shea/the authenticated experience team

- What team/project is this work for?

The new logged in homepage redesign [epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6326) [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md).

- Provide the Domain where Google Analytics needs to be implemented

https://www.va.gov/my-va/

- Please provide any upcoming deadlines or important milestones

We don't have any upcoming deadlines. We want this implemented so we can gather baseline satisfaction metrics before the redesign.

- Test Users to replicate the event

You should be able to use any staging user, either LOA1 or LOA3, to view the My VA dashboard.

- Certain conditions/responses that need to be reviewed

None.

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
@mshea0606 for awareness

**Comment by joanneesteban** [comment]
@Samara-Strauss @mshea0606 Sincere apologies for the delay here. This has been published to Staging, let me know if this works for you all, and I can push it to Prod.

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/0881ad82-3785-4727-af59-647eea87fa86)

**Comment by Samara-Strauss** [comment]
That works for me. Thanks!

**Comment by mshea0606** [comment]
Thanks!

**Comment by joanneesteban** [comment]
Awesome, thanks @Samara-Strauss & @mshea0606 ! It's pushed to Prod. If it looks okay on your end, I can go ahead and close this ticket. Thanks!

**Comment by joanneesteban** [comment]
@mshea0606 - closing this ticket. We can reopen if this needs editing!

**Comment by Samara-Strauss** [comment]
Great, thank you!
