### ISSUE TITLE
Flipper UI access for Mary Wang

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#87764]
### Your Name

Mary Wang

### Your GitHub handle (Flipper UI access is managed through GitHub)

marywang2

### Team, Role, and Company of the target individual

IVC Forms, product, Ad Hoc 

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need production (and lesser) access because my team is preparing to roll out FMP form 10-7959f-1 in the coming weeks/months and will be using a flipper to gate access to the application.

**Comment by AnthonyWFlowers** [comment]
Confirmed in Atlas
Granted Access to Flipper production and lower environments. Please reach out with any questions @marywang2
