### ISSUE TITLE
Fix SignInApp code coverage

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#87767]
## Description/Task
Fix code coverage for the `SignInApp` component so that all statements, branches, functions, and lines are a minimum of 80%. 

## How to check code coverage
1. Run `yarn test:unit <location-of-unit-test> --coverage --coverage-html`
2. Open up the `coverage/index.html` file in a browser
3. Verify code coverage minimums and refactor as needed

**Comment by parkerbees** [comment]
moved to jira, closing
