### ISSUE TITLE
Identity SDK - Restructure the `crypto` as fallback to `oauth4webapi` library

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#87778]
`oauth4webapi` has been added as a replacement for the existing OAuth and PKCE implementation.

However, there still needs to be a fallback to the original `crypto` module for availability and to ensure that there is not a direct dependent on the `oauth4webapi` library.

**Comment by parkerbees** [comment]
Moved to Jira, closing in Zenhub
