### ISSUE TITLE
Identity SDK - Define error handling

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#87777]
Extract and refactor the existing error handling from `AUTH_ERRORS` and `OAUTH_ERRORS`

Split up:

1. Error codes - clearly define the error codes
2. Consolidate the existing error codes being used in Auth and OAuth together
3. Ensure that numbering are roughly the same to reduce changing the error code in `vets-website`

**Comment by parkerbees** [comment]
Moved to Jira, cancelled in Zenhub
