### ISSUE TITLE
Fix code coverage

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#87779]
## Description
The code coverage standards currently only applies to applications within vets-website repository and does not include the platform directory in that requirement. Our team should be the standard when it comes to code coverage in platform code.

## Tasks
Create a ticket for each of the tasks listed below (reference this ticket and the one created for the tasks in your PRs). Fix code coverage for the following components and utilities
- [ ] `downtime.js`
- [ ] `errors.js`
- [ ] `selectors.js`
- [ ] `utilities.js`
- [ ] `actions.js`
- [ ] `CreateAccountLink` component
- [ ] `SessionTimeoutModal` (do NOT refactor to web components)
- [ ] `SignInModal` (do NOT refactor to web components)

## How to check code coverage
1. Run `yarn test:unit <location-of-unit-test> --coverage --coverage-html`
2. Open up the `coverage/index.html` file in a browser
3. Verify code coverage minimums and refactor as needed

**Comment by asg5704** [comment]
@acaruso-oddball I added both Caitlin and Ian on this as well. This is the ticket I mentioned that would be a mini-epic and separate tickets will need to be created for each of those files/components.

cc @CaitHawk @ianmagenta

**Comment by parkerbees** [comment]
Copied to jira, closing here
