### ISSUE TITLE
Create Form Profile class in vets-api for 2122 and 2122a

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#87791]
## Background
The FormProfile class (`app/models/form_profile.rb`) in vets-api returns data needed for each form on va.gov. We need to add form 2122 and 2122a so it returns the following:

- The user's service branch
- if the user has an ICN (bool)
- if the user has a participant id (bool)

Instructions are in this file - https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill

Colin and I discussed this and the data he needs for both form 2122 and 2122a is the same, so we can perhaps just set this up for form 2122 only and add a comment that it also applies to form 2122a, or name the form `21-22-AND-21-22A` which is how he named it on the frontend.

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
This ticket came from a conversation with Colin where he asked how to get a user's service brach.

Here's part of that convo for reference:

```
Holden Hinkle
  11:34 AM
It seems you have to call /v0/profile/service_history to get a user’s service history
11:35
Here’s the controller in vets-api - app/controllers/v0/profile/service_histories_controller.rb
11:36
This comment is in the file:
      # Fetches the service history for the current user.
      # This is an array of select military service episode data.
      #
      # @return [Response] Sample response.body:
      #   {
      #     "data" => {
      #       "id"         => "",
      #       "type"       => "arrays",
      #       "attributes" => {
      #         "service_history" => [
      #           {
      #             "branch_of_service" => "Air Force",
      #             "begin_date"        => "2007-04-01",
      #             "end_date"          => "2016-06-01",
      #             "period_of_service_type_code" => "V",
      #             "period_of_service_type_text" => "Reserve member"
      #           }
      #         ]
      #       }
      #     }
      #   }
      #
```

**Comment by oddball-lindsay** [comment]
This [Slack update](https://dsva.slack.com/archives/CE4304QPK/p1720807406179199) regarding PII guidelines around ICN may be relevant to this work.

**Comment by jvcAdHoc** [comment]
Waiting for pr review
