### ISSUE TITLE
Migrate 21a into ARP

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#87799]
#### Problem Statement
- When the 21a application was created it was unknown if there would be time in the 21a release timeline to have 21a in ARP. Having 21a in ARP means that 21a release is dependent on ARP Sign-In/Sign-Up, Header, and Footer being complete.
- As such 21a was created as its own application
- It has now been decided that there is time to complete these dependencies
- As such we need to migrate 21a into ARP

#### Implementation Details

- vets-website
  - src/applications/accreditation/21a --> src/applications/accredited-representative-portal/21a
  - Organize POA Requests content into its own sub-folder
  - Organize common elements that will serve both accreditation and POA Requests
  - Similar examples: src/applications/ivc-champva
- content-build
  - remove 21a from registry.json
- devops
  -  update ansible/deployment/config/revproxy-vagov/vars/react_routes.yml
- vsp-platform-revproxy
  -  update template-rendering/revproxy-vagov

#### Mockups/Designs

https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=1026-23113&t=jRgivAFabaQuJxHs-4
  - Note the ARP header and footer

### Acceptance Criteria

- [x] 21a has been migrated into ARP across all codebases
- [x] There is a placeholder page for /accreditation
- [x] ARP Login takes you to /accreditation instead of /poa-requests
- [x] 21a has ARP header and footer

#### Automated Testing

- Update e2e tests based on the Acceptance Criteria's updating of the ARP portal

**Comment by nihil2501** [comment]
@williamphelps13 [tweak PR into yours](https://github.com/department-of-veterans-affairs/vets-website/pull/30927) of a basic error in the reducer structure we were returning. this should unlock the next more challenging phase of integrating SIP. see PR description.

**Comment by gabezurita** [comment]
@nihil2501, @HaroldLee-VA, and @a6marinos, here's the issue that will likely be resolved by this work:
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/86193
