### ISSUE TITLE
We need to update the type of Ticket to put in for Datadog access

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#87802]
### Description
The link we have provided for Datadog access is no longer being accepted by the team who processes requests:
"Good morning.  I'm contacting you about your Request for DataDog access.  
 
Unfortunately we cannot process an Access Request using this form.  Please use this form instead:  [Application Access - yourIT Service Portal (va.gov)](https://yourit.va.gov/va?id=sc_cat_item&sys_id=f0d3a475db1d13807ed130ca7c96196b)
 
Complete instructions may be found in this Knowledge Article:  [Self-Service - Datadog: Datadog Access (va.gov)](https://yourit.va.gov/va?id=kb_article_view_yourit&sys_id=3907c5e697ad8e102dcbfcc0f053af13&table=kb_knowledge)
 
I apologize for the inconvenience.  Please let me know if you have any questions."

### Relevant URLs
Page with the incorrect ticketing information: https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog

**Comment by jknipes** [comment]
Hi @va-albers , thanks for bringing this to our attention. We will update the page and reply to you once it is set to be published

**Comment by jknipes** [comment]
Work completed and commented in [80263](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80263)
