### ISSUE TITLE
Comply w Robyn's request to add our data to her MHV on VA.gov spreadsheet on a regular basis

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#87803]
## Description
In a sync with Florence and Kat, Robyn explained that she is working to create a centralized place for all MHV on VA.gov medallia data from all products. To fulfill her request of our team, we need to access that centralized place (an excel file on VA sharepoint) every other week at a minimum to add data pertaining to the MHV landing page.

### Notes
- [Here is a file with instructions and explanations for this repeating task](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/metrics-performance-monitoring/calculating-and-reporting-CX.md)
- [Here is the sharepoint doc where Rboyn has requested we save our medallia data every 1-2 weeks](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B8c161ac9-bb42-401d-9b5d-913941f1eca9%7D&action=editnew&wdsle=0)

Possible tasks:
- Go into Robyn's sharepoint file (linked above)
- Add all Medallia data for June 2024
- Add Medallia data for as much as possible of July
- Go through data and tag as appropriate (or grab tags from our own data sets)
- Copy this ticket and create a new one for next sprint

## Acceptance criteria

- All June data is in Robyn's spreadsheet, and as much July data as possible is also in the spreadsheet
- All of our data is appropriately tagged
- New ticket for next sprint is created 
- At least one Cartographer has a calendar reminder to do the next two updates (expected on the 15th and last day of each month)

**Comment by wesrowe** [comment]
Next step: propose a new approach with a single, massive pull for all /my-health/

**Comment by wesrowe** [comment]
@katbrinkley, is this ticket still needed? I'm wondering because of something you said in Standup on Friday about not needing to update the all-portal spreadsheet for now. Or, did the tasks of this ticket change?

**Comment by katbrinkley** [comment]
I believe this is changing.. from our last meeting Anne said she could create a custom spreadsheet that could pull data for us with formulas. TBD though because that's also a bit of an experiment - I'll know more Friday and let you know what we need re: this ticket @wesrowe

**Comment by wesrowe** [comment]
there was a pivot that makes this story a no-op. we can re-open if copy-paste comes back.

**Comment by jonathanjnelson** [comment]
Updated on [Sharepoint]( https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B8C161AC9-BB42-401D-9B5D-913941F1ECA9%7D&file=MHV)
