### ISSUE TITLE
Produce and present doc enumerating potentially sensitive data points

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#87840]
#### Problem Statement

- 

### Acceptance Criteria

- [ ] Document enumerating potentially sensitive data points
- [ ] Present doc with security people

**Comment by gabezurita** [comment]
Done as part of:
https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/accredited-representative-facing/engineering/ADRs/arp-architecture-intent-meeting.md
