### ISSUE TITLE
508-defect-1 ❗ Launchblocker [SEMANTIC MARKUP]: Form elements MUST be paired with labels

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#8786]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

(3x) Form elements must have labels | 508-issue-semantic-markup
`<input class="usa-input" name="yr-search-name" type="text" value="">`

See https://design.va.gov/components/form-controls

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As  user, I want to be able to click the label of an input to put focus on the input.

## Possible Fixes (optional)

    - Potential fix: add id="yr-search-name" to the input
    `<select name="yr-search-state">`
    - Potential fix: add id="yr-search-state" to the select
    `<input class="usa-input" name="yr-search-city" type="text" value="">`
    - Potential fix: add id="yr-search-city" to the select

**Comment by kelsonic** [comment]
Form inputs do have labels, moving to validate: https://staging.va.gov/education/yellow-ribbon-participating-schools/

![image](https://user-images.githubusercontent.com/12773166/81312782-44858b80-9044-11ea-96e7-cb5df6cec3ff.png)

**Comment by jenstrickland** [comment]
Please check the fields listed above, as I still see the issue in staging. The labels and inputs are not paired with the label's `for` attribute and an input's `id` attribute value.

1. school name
1. state
1. city

**Code in staging today**

```diff
<form class="medium-screen:vads-u-display--flex vads-l-grid-container vads-u-flex-direction--column vads-u-padding--0" data-e2e-id="search-form" name="yellow-ribbon-form">
!  <label for="yr-search-name" class="vads-u-margin-top--1 vads-u-margin--0">School name</label>
  <div class="vads-u-flex--1">
!    <input aria-label="Name of institution" class="usa-input" name="yr-search-name" type="text" value="">
  </div>
!  <label for="yr-search-state" class="vads-u-margin-top--3">State or territory</label>
  <div class="vads-u-flex--1">
!    <select aria-label="State of institution" name="yr-search-state">
      <option value="">- Select -</option>
      <option value="AL">Alabama</option>
      <option value="AK">Alaska</option>
      <option value="AS">American Samoa</option>
      <!-- other state options -->
    </select>
  </div>
!  <label for="yr-search-city" class="vads-u-margin-top--3 vads-u-margin--0">City</label>
  <div class="vads-u-flex--1">
!    <input aria-label="City of institution" class="usa-input" name="yr-search-city" type="text" value="">
  </div>
  <div>
    <div class="form-checkbox">
      <input id="errorable-checkbox-3" type="checkbox">
      <label name="undefined-label" for="errorable-checkbox-3">Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill)</label>
    </div>
    <div class="form-checkbox">
      <input id="errorable-checkbox-4" type="checkbox">
      <label name="undefined-label" for="errorable-checkbox-4">Only show schools that provide funding to all eligible students</label>
      </div>
    </div>
    <button class="usa-button-primary va-button-primary vads-u-width--auto vads-u-padding-y--1p5 vads-u-margin-top--2" type="submit">Search</button>
</form>
```

**Comment by kelsonic** [comment]
Oh awesome, thanks @jenstrickland! PR incoming! 🙂

**Comment by jenstrickland** [comment]
Fix validated.
