### ISSUE TITLE
508-defect-2 [AXE-CORE, SCREENREADER]: Heading levels SHOULD only increase by one

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#8787]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Heading levels **should** only increase by one.

    `<h3 class="vads-u-margin-top--1p5">Search criteria</h3>`

## Potential fix

Make this an `<h2>`.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the page structure confidently by headings.

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/81441268-b4704080-912e-11ea-85e8-1e9eacefb827.png)

Validated and is already in staging: https://staging.va.gov/education/yellow-ribbon-participating-schools/?name=test

**Comment by jenstrickland** [comment]
Validated in staging. 

@kelsonic Thanks for aiming to take care of this for me. Please let me know when issues are ready for validation as the process is documented, I'll review, then close if addressed.
