### ISSUE TITLE
Flipper UI access for [Bo Altes]

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#87877]
### Your Name

Bo Altes

### Your GitHub handle (Flipper UI access is managed through GitHub)

baltes

### Team, Role, and Company of the target individual

IVC Forms, Product Manager, Agile Six

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [ ] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
@baltes You've been granted access to `lesser` environments.
