### ISSUE TITLE
Staging Review finding: Bug: "Showing results" element does not always show accurate number of results

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87884]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** VA BTSSS - Travel Pay
**Product:** Travel Pay
**Feature:** MVP

## Findings details
**VA.gov Experience Standard - issue:** [User experiences an unexpected interaction with a component or pattern.](https://design.va.gov/about/experience-standards/#user-experiences-predictable-interactions-with-components)
**VA.gov Experience Standard - category:** [Usability](https://design.va.gov/about/experience-standards/#category-usability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

When you are on pages 2 or higher of results, and you apply filters to limit the results, the "Showing X results" text is incorrect.

<details><summary>Link, screenshot or steps to recreate</summary>

- From travel claim status page, scroll down to bottom of page where pagination is listed
- Click "2" to go to the second page of results
- Scroll back to the top of the page, open accordion and deselect all checkboxes except "Claim paid"
- Click “apply filters”
- New text showing number of results will show the incorrect number of results: `Showing 11 ‒ 3 of 153 events`

</details>

## Recommended action

Correct the search status text to accurately report total number of filtered results, current page, and number of results.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by hinzed1127** [comment]
Recreation steps no longer recreate the issue. This was likely fixed during multiple other staging review tickets addressing different fixes around filters. Considering this fixed for now.
