### ISSUE TITLE
Staging Review finding: No clear entry point for feature

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87880]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** VA BTSSS - Travel Pay
**Product:** Travel Pay
**Feature:** MVP

## Findings details
**VA.gov Experience Standard - issue:** [User does not have a path to the content or feature.](https://design.va.gov/about/experience-standards/#user-has-a-path-to-the-content-or-feature)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

There is no link from MyHealtheVet or resources and support, or other discernable path for Veterans to access this feature.

## Recommended action

Work with the MHV information architecture specialist @sterkenburgsara and CAIA IA team to ensure all entry points for this application have been identified and updated. Potential entry points include MHV landing page on VA.gov, [travel reimbursement R&S page](https://staging.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online/), BTSSS application, etc.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** User flow

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by ayush-chak** [comment]
Hi all, quick update on this: we're working with the MHV team to get this link up - though just a heads up that per conversations with our stakeholder Kristen McConnell, there is a possibility this link will be up on their page as a fast follow (within one week) to rollout. We will continue to update here as we coordinate with the MHV team!

**Comment by ayush-chak** [comment]
Confirmed that this is working as intended.

Implementation for entry point: https://github.com/department-of-veterans-affairs/vets-website/pull/32141
