### ISSUE TITLE
Staging Review finding: Prioritize the primary focus of the page and reduce primary buttons

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87883]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** VA BTSSS - Travel Pay
**Product:** Travel Pay
**Feature:** MVP

## Findings details
**VA.gov Experience Standard - issue:** [User encounters design components or patterns that are inconsistent or confusing.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

There are 3 primary buttons on the page. Per [our guidance](https://design.va.gov/components/button/) you do not want to have too many primary buttons.

## Recommended action

This is not a must item, however it is strongly encouraged. Prioritize the primary focus of the page and reduce primary buttons, you could change some to secondary buttons.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Button ](https://design.va.gov/components/button)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by athifw** [comment]
@micahtaylor - which buttons should we make secondary buttons? Locally I made the sort and reset buttons secondary, what do you think?

![Screenshot 2024-07-30 at 4 41 06 PM](https://github.com/user-attachments/assets/9d7835ba-8a0f-4cf5-ac06-9abaabb116db)

**Comment by micahtaylor** [comment]
Yup. Agreed!
