### ISSUE TITLE
Explore mechanisms for plugging into custom code where needed

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#87909]
The first and most obvious example is PDF transformations. We'll need a way to write custom code in vets-website and connect a Drupal-defined form to that custom code.

**Comment by Karak888** [comment]
Engineer will need to write some transformation - code in repo more than likely and need to figure out how to execute it and tie it to this form.

**Comment by Karak888** [comment]
what if we do need per form customizations - If employment needs custom transformations, need to find more generalized way.

**Comment by Karak888** [comment]
Form specific code is housed application for that form- this idea is not really necessary at this point, moving to close.
