### ISSUE TITLE
Edit link text in Messages card

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#87918]
## Description

As a Veteran, I want the CTA for composing a new message to be worded identically across the MHV-on-VAgov portal, so that my cognitive load is reduced.

## Notes
It came up in a [recent slack conversation](https://dsva.slack.com/archives/C03ECSBGSKX/p1720535620586779) that our "compose message" link does not match wording elsewhere. Our link should match the text, "Start a new message." The "start a new message" wording is already present in our historical figma files.

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7468ffbb3ff64c722ceefd669a53117cf1ed4091/image.png" alt="image.png" />

<img width="661" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bb68dc1190d1a83ccd60a9a2079ae328f8490ff/image.png" alt="image.png" />

## Acceptance criteria
- Link text to start a new message in the messaging card states, "Start a new message" (instead of "Send a new message")

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the text has been changed to the correct text (Start a new message)

<img width="1766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy8wQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59122912b3dd8535dacafea81c2fa1c11824e948/Screenshot%202024-07-19%20at%207.11.59%E2%80%AFAM.png" alt="Screenshot 2024-07-19 at 7.11.59 AM.png" />
