### ISSUE TITLE
Derek: Set up local environments

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#87923]
## Acceptance Criteria
- [x] va.gov-cms
- [x] vets-website
- [x] content-build
- [x] next-build
- [x] vets-api

**Comment by derekhouck** [comment]
Cloned all the repos, went through the installation steps. I'm not 100% sure everything is working as it should, but I'm at a point where I think I'll just troubleshoot further issues as they come up.
