### ISSUE TITLE
Plan and enact changes to Feedback Repository role-based views

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#87943]
## Purpose
Plan and execute changes on all 3 role-based views

Tasks
- [x] Identify the "Now", "Next", and "Soon" Changes in [this whiteboard](https://vfs.atlassian.net/wiki/spaces/SDT/whiteboard/3281715264)
- [x] Enact the "Now" Changes
- [x] plan "Next" changes

Acceptance Criteria
- [x] Now changes made
- [x] "Next" changes planned

**Comment by gopixelsgo** [comment]
This item will roll over to next sprint for completion.
