### ISSUE TITLE
PW intake: Content change in a react widget on schedule and view appointments page from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#87949]
## Status
- **[2024-07-09]** [Fran] Engineering notes (from Daniel S) added stating it's not in Drupal; the text lives in the CTA widget react markup. It's been pointed as a 2, but we should have the team confirm/repoint if necessary during Sprint Planning. 
  -  **Note:** Adding to Sprint 8 per Michelle, because the change for Indianapolis takes place on 7/15.

### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else
- [X] 

Engineering Notes: 
- From Daniel Sasser: This text lives directly in the CTA widget react markup. We should be able to update this text in React and won't need to touch Drupal
- There is a good explanation as to why this wasn't added to Drupal to begin with in the [CTA readme](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/health-care-manage-benefits/README.md#why-isnt-this-in-drupal).
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4883aa10635f6ac5aba11ab6c771acf75b14781d/image.png" alt="image.png" />

### Describe your request

We need to make a content change on our [Schedule and manage health appointments](https://www.va.gov/health-care/schedule-view-va-appointments/) page but all of this content lives in a react widget so we need a dev to help us with. 

The widget code in Drupal is: schedule-view-va-appointments-page

The change we're making is under the H2 How do I know if my VA health facility uses online scheduling? As of 7/15 Indianapolis will offer online scheduling. So the new content should read as follows (note that we're removing the bullets):

Online scheduling is available at all VA health facilities except in Manila, Philippines.

### Time constraints / launch deadlines

We were just told this change is happening 7/15 and VHA asked us to remove it now. So as soon as it can be implemented.

### Your product/team Slack channel

sitewide-content-accessibility-ia

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by davidmpickett** [comment]
I think this will just be a content change to https://prod.cms.va.gov/indiana-health-care/make-an-appointment
Compare with: https://prod.cms.va.gov/boston-health-care/make-an-appointment
- Under **Main Content** add a `React Widget` content block and set type to schedule-appointments
- Add H3 of "Make an appointment Online" to the end of the previous `Rich Text` content block
<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9a50f41e50efe472509aa2527ca464f45ac62ea/Screenshot%202024-07-09%20at%204.01.02%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 4.01.02 PM.png" />

**Comment by RLHecht** [comment]
@kristenmcconnell FYSA

**Comment by chriskim2311** [comment]
@RLHecht Hi! This has been completed and is PR. I saw in the ticket we can merge when ready is that still the case or did we want to wait until 7/15 when it launches?

**Comment by RLHecht** [comment]
Thanks @chriskim2311 VHA has asked us to wait until 7/15 for the change to go live. Can you link to the file here so I can just read over the content and make sure it's correct? Thank you!

**Comment by chriskim2311** [comment]
Sounds good thanks! Here is the PR with the changes https://github.com/department-of-veterans-affairs/vets-website/pull/30788

**Comment by RLHecht** [comment]
Thanks! Can you put a period at the end of that sentence? Other than that it looks great.

**Comment by davidmpickett** [comment]
@mmiddaugh @RLHecht I saved a [draft revision](https://prod.cms.va.gov/node/20027/revisions) of the Indiana health care Make an appointment page. You can [preview](https://preview-prod.vfs.va.gov/preview?nodeId=20027) if you want to see how it will look. 

Let me know if one of you plan to publish that revision on Monday or if you want me to

**Comment by chriskim2311** [comment]
@RLHecht PR has been merged and will go out with today's deploy.

**Comment by davidmpickett** [comment]
@RLHecht @mmiddaugh 

https://www.va.gov/health-care/schedule-view-va-appointments/ is updated on Prod:
![Screenshot 2024-07-15 at 2 05 10 PM](https://github.com/user-attachments/assets/f63d0ff2-d430-4a5f-a581-2a4168bee18c)

I just published the edits to https://www.va.gov/indiana-health-care/make-an-appointment/ and they should be live with the next Content Release

**Comment by davidmpickett** [comment]
Widget is live on Indiana VAMC page:
![Screenshot 2024-07-15 at 3 52 42 PM](https://github.com/user-attachments/assets/6cb46f50-d8ee-410e-b9e5-b6b09bf5acd8)
