### ISSUE TITLE
Coronavirus banner: Remove May 5 deadline alert

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8795]
# User story

As a Veteran, I need timely and regularly updated information about all the ways the coronavirus may impact my VA health care and benefits.

# Details

We need to remove the stimulus check May 5 deadline alert on May 6 once the deadline has passed.

**Process steps to completion:**

- [x] Remove alert from Drupal nodes banners and publish (Randi)
- [x] Remove alert from homepage banner (our team or Josh T's team?)
- [x] Validate in preview/staging (Randi)
- [x] Validate on live site (Randi)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Just creating this ticket to track the work of removing the May 5 alert from the banner. Thanks!

@jenniferlee-dsva Can you remind me if Nick or Kelson could remove the alert from the homepage banner, or if we need to leave that to Josh T's team? Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx FYSA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's the new banner text. This will replace all of the existing text.

For questions about COVID-19 and how it affects VA health care and benefit services, visit our [coronavirus FAQs](/coronavirus-veteran-frequently-asked-questions/) or read [VA’s public health response](https://www.publichealth.va.gov/n-coronavirus/).

Please contact us first before going to any [VA location](/find-locations/). Contacting us first helps us keep you safe.

For the latest coronavirus information, visit the [CDC website](https://www.cdc.gov/coronavirus/2019-ncov/index.html).

**Comment by RLHecht** [comment]
The banner alert was removed from the benefit pages. Should be visible on live site shortly.

**Comment by RLHecht** [comment]
This has been validated on live site. Closing ticket. FYSA @stephorkandatx @DanielleThierryUSDSVA
