### ISSUE TITLE
Minor Tweaks to File Names

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#87959]
There are 3 items that need attention for this ticket.

1. When an attachment is uploaded that is not a PDF it's missing when saved in the DB.
2. The file name we send to the S3 bucket is `4171e61a-03b5-49f3-8717-dbf340310473_vha_10_10d1.pdf` but saved in the DB like `4171e61a-03b5-49f3-8717-dbf340310473_vha_10_10d-tmp1.pdf`. This will certainly cause issues for them when sending the payload.
3. The metadata JSON file is being sent to S3 like `vha_10_10d_metadata.json` and it needs to include the form_uuid like `4171e61a-03b5-49f3-8717-dbf340310473_vha_10_10d_metadata.json` to ensure it's not overwritten.

**Comment by balexandr** [comment]
Merged into master https://github.com/department-of-veterans-affairs/vets-api/pull/17459

**Comment by balexandr** [comment]
Still not seeing file ext in the DB. Have to take another pass

**Comment by baltes** [comment]
@balexandr Can you show an example of this showing as expected in the db? Just need something to verify before closing.

**Comment by balexandr** [comment]
<img width="479" alt="Screenshot 2024-07-15 at 10 27 59 AM" src="https://github.com/user-attachments/assets/b35e4626-32a1-4fdf-9d4a-a965d646d3de">

Sure this is my local DB after i fixed the ext.
