### ISSUE TITLE
Contact Center Review for [10-10 Health Apps - Toxic Exposure]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#87963]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
- 10-10EZ Veteran Health Care application on VA.gov where Veterans can apply for VA health care online. 
- We have added a section of questions for Toxic Exposure, as well as updated some screenshots showing the new components.

### Launch Date
*Please provide the launch or rollout date and details.*
- Launch date was in March, it was a rushed release

### Version Number
*Please provide the version number of the guide and/or video.*
- Version 3

### Product Guide
*Please provide product guide link*
- [Draft HCA Product guide 7/9/2024](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/HJ%20Draft%20-%20HCA.Product.Guide%207-9-2024.docx)

### Product Video
*Please provide product video link*
- No video is provided

### Product Video Transcript
*Please provide product video transcript link*
- No video is provided

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by hdjustice** [comment]
There is an upcoming effort from VA to send text messages to Veterans starting on Tuesday 7/16/2024 through Tuesday 7/30/2024.  This guide update is in preparation for this effort.  We are in a close timeline for it

**Comment by starlow00** [comment]
The draft looks good. I am sending it to VEO for their review.

**Comment by hdjustice** [comment]
That is totally fine Steven, our team doesn't rely on that as much as the Veteran Support and other support folks do, so whatever makes the most sense is great.  Thank you!

**Comment by starlow00** [comment]
There are no changes from VEO. I've attached the current copy; please use it for future updates and revisions. Thank you!
[10-10EZ.Product.Guide_v3.1_SRT_07112024 (1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1acbfc60e47b0088aa75cc861a37aa670682c228/10-10EZ.Product.Guide_v3.1_SRT_07112024%20%281%29.docx)

**Comment by hdjustice** [comment]
Fabulous, thank you Steven!
