### ISSUE TITLE
Double entry - design.va.gov documentation

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#88]
When do we have users enter information twice?

Here are some points. These bullet points are not in any particular order.
- Cases where we don't do it?
- How do we determine when where to do it?
- How do we handle validation (for example, client or server) where we do do it?

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by caw310** [comment]
This is over 3 yrs old so closing.
