### ISSUE TITLE
create SSN route for backend form submission

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#88014]
there is currently a route within `in_progress_forms` that stores and uses the SSN of a user on VA.gov when they need to submit a form. Our team should create a single location for SSN to be pulled so that each team isnt making their own route.

Creating for review by PM and PO before delegating this to an engineer.

**Comment by joeniquette** [comment]
- [ ] develop framework and rules around being the authority for SSN on va.gov

**Comment by joeniquette** [comment]
@blacktm approved the work on 11Jul24 during tech lead sync. Priority tbd

**Comment by parkerbees** [comment]
Moved to Jira (VI-39) for work in Sprint 3 and beyond. Marking as cancelled here.
