### ISSUE TITLE
Create Draft Desktop/Mobile/Tablet Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#88041]
## Tasks

- [x] Create spec pages, e.g., desktop and mobile sizes for the appt details page
- [ ] Validate work with UX and Peter

**Comment by benbrasso-agile6** [comment]
@zach-park let me know if this is rdy to validate

**Comment by zach-park** [comment]
@benbrasso-agile6 , the [responsive breakpoints](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2569-1282&t=ZsqukaOdLQnmJfo8-1) are ready for validation. Thank you!
https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2569-1282&t=ZsqukaOdLQnmJfo8-1

**Comment by benbrasso-agile6** [comment]
Looking good. Left a few small comments. Thx @zach-park

**Comment by zach-park** [comment]
> Looking good. Left a few small comments. Thx @zach-park

Fixed!

**Comment by zach-park** [comment]
@benbrasso-agile6 a quick question, should I remove the "Who" and the CTA buttons?

**Comment by zach-park** [comment]
> @benbrasso-agile6 a quick question, should I remove the "Who" and the CTA buttons?

Please disregard the question. I just saw the ticket for the "Appt detail page and page type changes ([89874](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89874))" is moved back to the not started column. :)

**Comment by benbrasso-agile6** [comment]
Don't forget this one https://www.figma.com/file/RzugGEmu4drhCSHTyQ6hjl?node-id=2569:3&locale=en&type=design#915019695

**Comment by benbrasso-agile6** [comment]
This one too https://www.figma.com/file/RzugGEmu4drhCSHTyQ6hjl?node-id=2622:31278&locale=en&type=design#915024006

**Comment by benbrasso-agile6** [comment]
Nice work Zach!
