### ISSUE TITLE
Generate a PDF when the End Product is established but Lighthouse doesn’t generate the PDF

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#88044]
Placeholder: Build a workload that would generate a PDF if the claim is established but LH doesn’t generate the PDF and place it in the Vet’s eFolder.

Context, this ticket was an outcome of the 7/10 ToT meeting where we discussed wether we need to do this or if LH would be responsible for handing generatePDF failures. We'll discuss further with LH, but we wanted to capture this ticket for Post MVP enhancements, so it's not forgotten.

**Comment by aurora-a-k-a-lightning** [comment]
As of today, unless requirements change, we will always use the LH /generatePDF endpoint to generate the 526 PDF and remediate as planned.
