### ISSUE TITLE
Review Medallia feedback for entire portal

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#88055]
### User story

As a Cartography team member, I want to review a sample of medallia f/b from health tool URLs to see if comments are relevant to LP or secondary nav

### Notes
- Dates: post-integration (6/17)

Possible tasks:
- identify patterns (eg keywords) that will help us find this feedback more efficiently in the future

## Acceptance criteria

- Reviewed a reasonable sample of feedback from tools under /my-health/ for f/b about LP and secondary nav
- Identified clues to what feedback is relevant to our team

**Comment by jonathanjnelson** [comment]
[Working Mural here ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723044655606/28fa103b63e11c636a189d7bbdfa2e6100fd271a?sender=u24af215c7d9bf806b8545488)

**Comment by jonathanjnelson** [comment]
[Please see framework here (Mural)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723044655606/28fa103b63e11c636a189d7bbdfa2e6100fd271a?wid=0-1723045097213)

[Review of feedback ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723044655606/28fa103b63e11c636a189d7bbdfa2e6100fd271a?wid=0-1723143810092)
