### ISSUE TITLE
Burial | Create Architecture Diagram

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88053]
## Issue Description
_For the [Readiness Review requirement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86756), we need to document the architecture of the burial form._

Requirements:
- This diagram must go beyond simple boxes and lines.
- It must clearly indicate which portions of the architecture are within the scope of the review, which portions are dependencies within the product, and which portions are external dependencies.
- This diagram must also illustrate the following specifics.
   - Which implementation of security approaches were considered along with the approach that was chosen and why?
   - If there are any libraries or components that this code base will depend upon that are currently not yet part of the code base? How and why were these selected?

---
## Acceptance Criteria
- [x] Documentation created and added to repo
- [x] Link to documentation added to #86756
---

**Comment by tblackwe** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/BurialFlow.png
