### ISSUE TITLE
set hard session limit for ssoe

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#88064]
Currently there are no hard time limits for a session on va.gov (or mobile but thats not in scope here). NIST 800-63-3 June 2017 version, state that we shall limit sessions to 12 hours for AAL2. We are currently operating at AAL2, but I dont know if we are expected to enforce this. Here is a link to the text: https://pages.nist.gov/800-63-3/sp800-63b.html#:~:text=At%20AAL2%2C%20authentication%20of%20the,lasting%2030%20minutes%20or%20longer.

The ask here is to determine if we want to set a hard time limit for VA.gov sessions, and if so what amount of time. This would in affect force all users who have been logged in for 12 hours to be forced logged out, even if they are actively clicking around on va.gov. I suspect this will rarely occur, where we force a logout with this, but it did seem to come up a few times during our initial terms of use enforcement changes on VA.gov. Some users had automated mechanisms to keep the session alive so they could have a continuous view of their claim status. After we turned on ToU enforcement, these users were forced to logout and log back in, accept terms,  before they could access any parts of the va.gov again.

**Comment by joeniquette** [comment]
per meeting decision by @blacktm during the tech leads meeting on 11JUL24, we will hold on this until we do a full review of the new NIST standard guidelines https://csrc.nist.gov/pubs/sp/800/63/4/ipd

**Comment by parkerbees** [comment]
Copied to Jira (VI-40) for work in Sprint 3 and beyond; marking as cancelled here.
