### ISSUE TITLE
Migrate to react router v6 using react-router-dom-v5-compat

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#88078]
### User story

As a Cartography team member, I want our code to use current best practices and packages. React Router v6 was released in 2022, and an upgrade path is available to us. The `react-router-dom-v5-compat` package is already installed and set up in [platform startup code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/startup/router.js), and that lets us migrate our React Router v5 routing code to v6.

> React Router version 6 introduces several powerful new features, as well as improved compatibility with the latest versions of React.

Per [this announcement](https://reacttraining.com/blog/reach-react-router-future#features), this might reduce our app bundle size, which would be a performance win

### Notes

- [Upgrading from v5](https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v6)
- [Official v5 to v6 Migration Guide](https://github.com/remix-run/react-router/discussions/8753)
- [src/platform/startup/router.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/startup/router.js)
- v6 has a [redirect function](https://reactrouter.com/en/main/fetch/redirect#redirect) function which might improve our ability to redirect more quickly when needed

Possible tasks:

- Follow the "Convert `Switches` to `Routes`" guidances from the [Official v5 to v6 Migration Guide](https://github.com/remix-run/react-router/discussions/8753)

## Acceptance criteria

- MHV Landing Page app migrated to react router v6 using react-router-dom-v5-compat
- QA review
- A11y review

**Comment by radavis** [comment]
Build sizes before any changes: 

```
$ ls -tla build/vagovprod/generated/mhv-landing-page.*-rw-rw-r-- 1 rd rd   27685 Aug 12 09:30 build/vagovprod/generated/mhv-landing-page.css.map
-rw-rw-r-- 1 rd rd 6951779 Aug 12 09:30 build/vagovprod/generated/mhv-landing-page.entry.js.map
-rw-rw-r-- 1 rd rd    4729 Aug 12 09:30 build/vagovprod/generated/mhv-landing-page.entry.js.LICENSE.txt
-rw-rw-r-- 1 rd rd   15128 Aug 12 09:30 build/vagovprod/generated/mhv-landing-page.css
-rw-rw-r-- 1 rd rd 1998572 Aug 12 09:30 build/vagovprod/generated/mhv-landing-page.entry.js
```

**Comment by radavis** [comment]
Build sizes after switching over to 'react-router-dom-v5-compat':

```
$ yarn build --buildtype=vagovprod
  ...
  mhv-landing-page (1.93 MiB)
      mhv-landing-page.css
      mhv-landing-page.entry.js

$ ls -tla build/vagovprod/generated/mhv-landing-page.*
-rw-rw-r-- 1 rd rd   27685 Aug 12 10:43 build/vagovprod/generated/mhv-landing-page.css.map
-rw-rw-r-- 1 rd rd 6970227 Aug 12 10:43 build/vagovprod/generated/mhv-landing-page.entry.js.map
-rw-rw-r-- 1 rd rd    4958 Aug 12 10:42 build/vagovprod/generated/mhv-landing-page.entry.js.LICENSE.txt
-rw-rw-r-- 1 rd rd 2013590 Aug 12 10:42 build/vagovprod/generated/mhv-landing-page.entry.js
-rw-rw-r-- 1 rd rd   15128 Aug 12 10:42 build/vagovprod/generated/mhv-landing-page.css
```

`mhv-landing-page.entry.js` increased by 1,793 bytes

**Comment by dcloud** [comment]
@radavis Sorry I didn't notice this earlier, but it looks like you've paused before the ["4) Convert Switch to Routes"](https://github.com/remix-run/react-router/discussions/8753#:~:text=4)%20Convert%20Switch%20to%20Routes) step, which I think is where v6 kicks in. I wonder if what you're seeing with the build sizes is due to the code being in an interim state where v5 and v6 are loaded?

I think if we don't have lots of v5 routing code deep in our components we might be able to  the "Convert Switch to Routes" without the `CompatRoute` interim step

**Comment by radavis** [comment]
Ok! Now, that we're switched over to `<Routes>` and `<Route>`, the build size is:

```
$  yarn build --buildtype=vagovprod
  ...
  mhv-landing-page (1.46 MiB)
      mhv-landing-page.css
      mhv-landing-page.entry.js

$ ls -tla build/vagovprod/generated/mhv-landing-page.*
-rw-rw-r-- 1 rd rd 5150633 Aug 15 15:51 build/vagovprod/generated/mhv-landing-page.entry.js.map
-rw-rw-r-- 1 rd rd   27685 Aug 15 15:51 build/vagovprod/generated/mhv-landing-page.css.map
-rw-rw-r-- 1 rd rd    4284 Aug 15 15:51 build/vagovprod/generated/mhv-landing-page.entry.js.LICENSE.txt
-rw-rw-r-- 1 rd rd   15128 Aug 15 15:51 build/vagovprod/generated/mhv-landing-page.css
-rw-rw-r-- 1 rd rd 1511111 Aug 15 15:51 build/vagovprod/generated/mhv-landing-page.entry.js
```

`mhv-landing-page.entry.js` decreased by 500,686 bytes!

**Comment by radavis** [comment]
Recommended reading on react-router v6:

- https://reactrouter.com/en/6.22.3/start/overview
- https://reactrouter.com/en/6.22.3/start/concepts#main-concepts

`mhv-landing-page` thoughts:

Should we ever use react-router's [`<Link to />` component](https://reactrouter.com/en/6.22.3/components/link)? `<NavLink to />`? These components can be used when linking to routes within the app. Since other apps are mounted as their own entrypoint, we should continue to use `<a href />` tags when linking to health tools and elsewhere.

Could react-router's [`<Outlet />`](https://reactrouter.com/en/6.22.3/components/outlet) be helpful? For example, when rendering common page components for paths under `/my-health`. [react-router: Layout Routes](https://reactrouter.com/en/6.22.3/start/concepts#layout-routes)

We should consider adding an ErrorBoundary.
  - [react-router errorElement](https://reactrouter.com/en/main/route/error-element#errorelement)
  - [react error boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)
  - see: `src/applications/avs/components/ErrorBoundary.jsx`
  - Send error to DataDog/Sentry when called/rendered

**Comment by allanto-ah** [comment]
Environment: Staging

No regression issues. MHV landing page loads as expected and can navigate to the various pages without issue
