### ISSUE TITLE
Add the provider/practitioner name under the Who section in the details page redesign

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#88082]
## Description
Background: the va_online_scheduling_appointment_details_redesign toggle is on. When user click on the details page, the provider name displays under the "Who" heading. Otherwise, do not display the "Who" section if practitioner name is missing.

---

## Acceptance Criteria

Given the `va_online_scheduling_appointment_details_redesign` toggle is on

- [x] When user clicks on the **In-person** details page, then the page should display the provider name under the "Who" heading if practitioner/provider information is available. Otherwise, do not display the "Who" section if null. And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=3075-77912&t=DsVwD90NJcW8pqFp-0)

- [x] When user clicks on the **Phone** details page, then the page should display the provider name under the "Who" heading if practitioner/provider information is available. Otherwise, do not display the "Who" section if null. And page design matches the [design spec ](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=3081-80370&t=DsVwD90NJcW8pqFp-0)

- [x] When user clicks on the **Claim exam** details page, then the page should display the provider name under the "Who" heading if practitioner/provider information is available. Otherwise, do not display the "Who" section if null. And page design matches the [design spec](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=3081-79972&t=DsVwD90NJcW8pqFp-0) 

- [x] When user clicks on the **COVID-19** details page, then the page should display the provider name under the "Who" heading if practitioner/provider information is available. Otherwise, do not display the "Who" section if null. 

### Design Assets
[Figma design](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2072-398573&t=DsVwD90NJcW8pqFp-0).

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Waiting for SPL team to create phone appts in staging. Once they have created it, we will resume testing. cc: @outerpress

**Comment by ldelacosta** [comment]
VAOSR-8434

**Comment by outerpress** [comment]
Tested with phone appt under john morrison, this one is good to go @vbahinwillit @ldelacosta 

<img width="813" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--698152d3721bf8d3672fa6ca28f90982a3cbb307/Screenshot%202024-08-08%20at%207.11.04%E2%80%AFAM.png" alt="Screenshot 2024-08-08 at 7.11.04 AM.png" />

**Comment by JunTaoLuo** [comment]
Since @ldelacosta is out I'm just going to close this.
