### ISSUE TITLE
BUG: Submit Transformer has incorrect information for some data

### ISSUE THREAD

**Issue by reiting** [department-of-veterans-affairs/va.gov-team#88109]
The submit transformer for F1 needs to be updated so that we can pass the correct information to the backend.

**Comment by reiting** [comment]
This is finally in platform review. There were some errors originally when pushed that were due to some problem in main. It has since been fixed so this finally passed and is waiting on platform.

**Comment by reiting** [comment]
This has been approved and merged. Should be on staging in a few hours.

**Comment by reiting** [comment]
@marywang2 this has been approved and merged. It should be available in staging for review, though I'm not really sure how you review it.

**Comment by marywang2** [comment]
I'm able to get to the confirmation page but @balexandr will look at this in this [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/88109) to ensure the end to end is working.
