### ISSUE TITLE
Spike: LOE for URL change request from IA 

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#88117]
Background: The IA team has done an audit and requested major URL changes. The spreadsheet can be found [here](https://docs.google.com/spreadsheets/d/1A7xJ2JESNNL-olJzMSkt9tN9-xY-foB8LD2D_I0o01Q/edit?gid=0#gid=0)

Slack discussions for context: https://dsva.slack.com/archives/C05MS96P6P2/p1711719332619779 and https://dsva.slack.com/archives/C05MS96P6P2/p1719952820408009

In this ticket, the size of effort and what this level of change will touch within our code and reporting. 

Acceptance Criteria:
- Determine LOE to change 1 URL
- Write a "recipe"/steps to update 1 URL
- Outline repercussion on reporting

**Comment by mjknight50** [comment]
This change should be relatively straight forward.
For each entry in the [spreadsheet](https://docs.google.com/spreadsheets/d/1A7xJ2JESNNL-olJzMSkt9tN9-xY-foB8LD2D_I0o01Q/edit?gid=0#gid=0), we will need to find the corresponding page in vets-website:
`src/applications/pensions/config/chapters`

For example, within`src/applications/pensions/config/chapters/01-applicant-information/applicantInformation.js` we would change the path on line 49 to the new path of _veteran-info_

For each page that is changed, we will also need to do a migration in `src/applications/pensions/migrations.js`

Something like this:

```
// 9 > 10
  // This migration handles the url changes that have been made throughout
  // the pension form.  This was part of an initiative to update the form urls
  // so they are up to date with standards set by CAIA
  ({ formData, metadata }) => {
    const newFormData = { ...formData };
    const newMetadata = { ...metadata };
    // check if the user has history
    if (formData['view:history']) {
      // TODO: either do a dictionary or switch here, returning the new url
      // newMetadata.returnUrl = '/applicant/information';
      // delete newFormData['view:history'];
    }
    return { formData: newFormData, metadata: newMetadata };
  },
```

My estimate is that this would take a day.  2-3 points.

**Comment by mjknight50** [comment]
@matt4su - Leaving this here for your visibility and for you to prioritize

**Comment by matt4su** [comment]
@mjknight50 would it be possible to provide more info on analytics impact around the change (ga4, datadog, domo)?

**Comment by mjknight50** [comment]
https://dsva.slack.com/archives/C1Q4294JJ/p1722439140419169

 There's not a way to map old and new URLs in GA.

For Domo, you can have the Forms dashboard updated with the new URLs using the [Analytics Product KPI Dashboard - Request and Update Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-and-update-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+%26+KPI+dashboard+update+request+for+%5BTeam%5D)
