### ISSUE TITLE
Limit polling from vets-website

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#8813]
## User Story or Problem Statement
on http://localhost:3001/track-claims/your-claims  [vets-webisite polls](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/actions/index.jsx#L152) every 5 seconds, with no limit to the number of calls.  When vets-api is functioning well, this is perfectly acceptable, but should there be a time where our sidekiq queue become backed up, this polling could consume resource excessively.  If a veteran were to leave this tab open for hours/days  it's possible it could continue polling for the whole time, given the right circumstances on the back end.  

## Goal
Set a maximum number of times that vets-website would poll.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
@rianfowler I wrote this up as a specific issue for the BAM team, but I'm wondering if maybe this should be a VSP FE tools issue to make sure all the polling that vets-website does has some sort of limit.

**Comment by rianfowler** [comment]
@annaswims probably VSP thing to do. There's a [polling helper](https://github.com/department-of-veterans-affairs/vets-website/blob/9ab4ce64d40646fd0934095919715dc71e287193/src/applications/claims-status/actions/index.jsx#L152) but it needs to support an exponential backoff and (like most of our stuff) it's not easily discoverable.

**Comment by rianfowler** [comment]
duplicate #2644
