### ISSUE TITLE
10-7959f-1: Bug - breadcrumb stretched across page width

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#88132]
10-7959f-1
Issue: The breadcrumb is stretched across the page width
<img width="1369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5TQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ba854fc91b635315f8dd57346dce21a20091c4b/Screenshot%202024-07-11%20at%2012.50.43%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 12.50.43 PM.png" />

Expected result: the breadcrumb should be constrained to the page margins.

**Comment by reiting** [comment]
<img width="1053" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK253QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7b0c0523f58cfc889ec093f2da08840ab81f981/Screenshot%202024-07-18%20at%202.13.00%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 2.13.00 PM.png" />

**Comment by reiting** [comment]
@marywang2 this is ready for review.
