### ISSUE TITLE
Add the A11 (5 item question) intercept survey to confirm pages on pre-check-in and check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88146]
## Background

Robyn (OCTO Research Lead) and Kristen would like us to add the intercept survey to the confirm page on both pre-check-in and check-in. We should request that it open ~10-15 secs after the page loads, to give Veterans time to review the information on the confirm page first. 

They are working on an initial to pull product feedback into one place and use the same survey types. 

## Tasks

- [x] Submit request to add the A11 (5 item question) intercept survey to confirm pages on pre-check-in and check-in

**Comment by loripusey** [comment]
Requested via [Slack thread](https://dsva.slack.com/archives/CNCEXNXK4/p1721221404946229)

**Comment by loripusey** [comment]
The survey is already enabled and on ALL Pre-Check-in & eCheck-in pages; we requested they remove it from all pages except the complete pages; [Request ticket](https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/88729)
