### ISSUE TITLE
[Development] Original Claims: Determine Original Claims Based on Claims Status

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8815]
## User Story or Problem Statement
~The front-end user object should be pre-loaded with some parameter that indicates that the claim is an original claim.  We have determined that using the fact that BIRLS or CorpDB IDs exist is not sufficient.  Therefore, it is suggested we use one of the Claims Status endpoints on user object generation to~ The backend will call EVSS and determine whether there have ever been any previous DISABILITY claims filed (closed or open claims both indicate this not being an OC).  This should be a better indicator for Original Claims tracking.  ~The front-end team will use this parameter to trigger some Google Analytics that allows that team to track OC on our end and not rely on passing anything downstream to EVSS.~ We will add the indicator to statsD and use Grafana and Sentry for monitoring.

~The assumption here (which I believe is correct) is that~ We have confirmed that even if we don't have to hit MVI proxy-add to create the right user IDs on the back-end, it does not mean this is not an original claim.

Example of the above: https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/evss/claims/index/796090612.yml
benefit_claim_type_code: 130_dPNEBNADJ

Note: There may be an issue with the responsiveness of these calls from EVSS so it may create issues on profile/user load.  Also, there may be an issue determining claim type (may not be needed) from the EVSS endpoint.

## Goal
The ability to track the difference between an original claim and simply a new claim.

## Acceptance Criteria
- [ ] ~The front-end user~ The request object has a parameter that indicates whether this is an original claim or not.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Closed as completed by Griffana charts.

**Comment by SarahJaine** [comment]
@luke-gcio What kind of metrics are we interested in? Do we just need to know know failure information about the original claims **_submissions_** (things like error rate and error types for original claim submissions?)  Or did we also need to know the number of original claims started?  The answer will change the timing of when we call evss's claims status endpoint to determine if the user is creating an original claim.  
- If a.) we only need information about submissions, then we can add the evss claims status call to our form526 submit method and tag the statsd log with the fact that this submission is for an original claim.  
- If b.) we need to know how many original claims were started, then we need to either b.1.) call evss's claims status endpoint on the in progress forms show endpoint every time the user logs in and (re)starts the form, or b.2.) call evss's claims status endpoint just the first time the form is started and then add the original claim value to the SIP data.

There are likely many more options I'm not thinking of, but in any event, it seems important to decide what monitoring information we need before development work starts.

**Comment by SarahJaine** [comment]
Some notes in https://github.com/department-of-veterans-affairs/vets-api/tree/sj-submit-original-claim

**Comment by luke-gcio** [comment]
We are going to drop this into the IceBox and see if we can get the same (and more) data from Tableau.
