### ISSUE TITLE
Updates to 10-10d notification emails

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88164]
As a CHAMPVA applicant, I need info about my files that were received by VA and other helpful guidance in my email notification.

Acceptance criteria
- As an applicant I get one confirmation email per submit rather than one per file
- As an applicant I can see how many supporting docs were included with my application.
- As a VA-notify template editor I have a key for submit date to include rather than date updated

This is a task to update variables for the 10-10d VA-notify template.

Below is an example from form 10-10EZ that we can borrow from.
<img width="1014" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56b1012f1af1d8ae7fda1b49c59610451977fa4f/image.png" alt="image.png" />

Here's what we currently have in our template:
<img width="1014" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03763360db1183dd52f192d36f1f23fbc6f04325/image.png" alt="image.png" />

Change the metadata key for  ((updated_at)) to ((date_submitted)) so that it's clear that it's the date the form is submitted rather than a different update date.

Add a variable with a count for all supporting documents update that does not include the form itself. The user should see something to the effect of "We've received your form 10-10d and the X supporting documents you provided." We'll need a variable we can use in VA-notify to populate X.

Add a form name variable for use in VA-notify along with the existing for number. Use names as shown below:

| Form number | Form name |
|------------|-------------------------------------------------|
| 10-10d     | Application for CHAMPVA Benefits                |
| 10-7959a   | CHAMPVA Claim Form                              |
| 10-7959c   | Other Health Insurance (OHI) Certification      |
| 10-7959f-1 | Foreign Medical Program (FMP) Registration Form |
| 10-7959f-2 | Foreign Medical Program (FMP) Claim Cover Sheet |

Add variable for call center phone number so that we can add a key for either the CHAMPVA number or the FMP number.
| program                                                      | call center number |
|--------------------------------------------------------------|--------------------|
| Foreign Medical Program (FMP)                                | 877-345-8179       |
| Civilian Health and Medical Program of the Department of Veterans Affairs (CHAMPVA) | 800-733-8387       |

**Comment by balexandr** [comment]
First PR is for updates to the data model https://github.com/department-of-veterans-affairs/vets-api/pull/17651

**Comment by balexandr** [comment]
Second PR was merged https://github.com/department-of-veterans-affairs/vets-api/pull/17655

**Comment by balexandr** [comment]
Third PR with email fix and phone_number https://github.com/department-of-veterans-affairs/vets-api/pull/17667

**Comment by balexandr** [comment]
`form_name`, `file_count` and `phone_number` have been added to the email template
<img width="895" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd1e716a0d61ee13f5519bdd107e37dd846fe930/Screenshot%202024-07-23%20at%204.10.34%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 4.10.34 PM.png" />

**Comment by baltes** [comment]
@balexandr Can you double check the file count and confirm that it is only for supporting docs, not including the form itself?

This submit was for one applicant, with one file for marriage license, two files for insurance cards, and one file for OHI.
<img width="1132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53b007da7dff364defc07fe6c254977e162c302a/image.png" alt="image.png" />

**Comment by balexandr** [comment]
@baltes It includes the form itself as it is still considered a file that's being processed.

**Comment by baltes** [comment]
@balexandr It was always meant to be a count of supporting documents that doesn't include the form itself. No need to hide it if the count is zero.

**Comment by baltes** [comment]
@balexandr We still need the count changed so that it covers supporting docs and doesn't include the form. Let me know if we need to break that into a separate ticket.

**Comment by balexandr** [comment]
@baltes So right now it's doing the count based on the form_uuid so if there are multiple applicants with multiple PDFs for the form it will be all those minus the main one. Is that good? I'm basically putting in logic to take the entire count and subtract 1

**Comment by baltes** [comment]
@balexandr The goal is to tell the user "we received your application and X supporting documents." The user shouldn't have to be aware that we generated multiple form PDFs--it's just one application as far as they're concerned.

I'll close this ticket and break that part out into a new one if that makes sense at this point.

**Comment by balexandr** [comment]
That's okay I think I got it

**Comment by balexandr** [comment]
Another PR in review for this change https://github.com/department-of-veterans-affairs/vets-api/pull/17770

**Comment by balexandr** [comment]
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0lkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cf322f51e5f8fd0b9212dd37a86dc9c724ba389/Screenshot%202024-07-30%20at%201.16.25%E2%80%AFPM.png" alt="Screenshot 2024-07-30 at 1.16.25 PM.png" />

@baltes I did a submission with a birth certificate and front and back of medicare cards
