### ISSUE TITLE
[Development] BDD: Changes to Messaging/Gating for < 90 Days from Separation

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8818]
## User Story or Problem Statement
We were told that a BDD claim that ends up starting or being submitted < 90 days from separation date will put the service member into the "quick start" lane for 526. This is no different than an Original Claim at that point. However, there should be some messaging changes and this gating should be captured in the design.

Suggested messaging would need to be in two places.  Design team should be able to provide what this looks like.

1. Once during the gating process if they enter in a separation date that is < 90 days from separation. It should allow them to still file on VA.gov but provide some messaging to the veteran.
2. During the submission process, if the veteran started 90-180 days out but did a SIP and is now < 90 days, we should again allow the submission but have the same wording as above about the claim no longer being part of BDD.

## Goal
Allow service members to still submit < 90 days out but as part of Quick Start (which to us is the same as an Original Claim).

## Acceptance Criteria
- [ ] Allow veterans < 90 days out to submit.
- [ ] Updated messaging.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Do we need to verify that we evss will accept these?  In [grafana we see ](http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?panelId=13&fullscreen&orgId=1)

> [{"key"=>"form526.serviceInformation.SeparationLocationCode" "text"=>"The separation location code for the claimant with a future released from active duty date is missing" "severity"=>"ERROR"} {"key"=>"form526.serviceInformation.servicePeriods[0].ActiveDutyEndDateBefore90Days" "text"=>"Service members cannot submit a claim when they are within 90 days of their separation date" "severity"=>"ERROR"}]
