### ISSUE TITLE
Monitor whether applicants include email

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88208]
As a member of the IVC Forms team, I need to know how many applicants are including their email address (which is optional) when submitting a form so that I understand the impact of making email address required vs optional.

Acceptance criteria
- I can see percentages for a given time span for the percentage of users who are including at least 1 email* versus leaving email blank
- Since datadog is under our control and we want this metric available at go live, we should plan on including it there
- It's unclear when GA will be available to us, so we probably don't want to wait for that

* In the case of 10-10d, we'd just want to understand if there's at least one email included in the form.

**Comment by balexandr** [comment]
@baltes If I'm understanding this correctly, We want a percentage of applicants with email so if there are 100 forms and 50 forms with emails you want it to display 50%? Sounds like I can run a job/process every 15mins (similar to missing pega status) and then the number just updates

**Comment by baltes** [comment]
@balexandr If we can to it similarly to the LOA donut chart that would work. Is there a reason that can't run in real(ish) time also?

**Comment by balexandr** [comment]
@baltes I can set it up like the LOA where it just increments one if an email is used or not.

**Comment by balexandr** [comment]
This was just merged into staging and the DD pieces have been set up

**Comment by balexandr** [comment]
<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--900371e2289451ebde93db58c6fdba028d175a10/Screenshot%202024-07-31%20at%205.14.07%E2%80%AFPM.png" alt="Screenshot 2024-07-31 at 5.14.07 PM.png" />
