### ISSUE TITLE
10-7959c OHI Update Hint text on the Medicare questions

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#88209]
- Update the hint text on the [Medicare carrier question](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1260-85868&t=kGAFf4OYGVK8zr9n-4)n to[ CAIA's suggestion](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms?node-id=1260-85868#871811829) to help applicants determine what to fill out in the carrier name fields.
- Handoff to Mary to create a ticket for the engineers to update on Staging

**Comment by rachaelpenfil** [comment]
This looks good to me, @jamiefiore
