### ISSUE TITLE
Contact Center Review for [10-10 Health Apps - Caregiver 2024 Form Updates]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88205]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
- 10-10CG - Program of Comprehensive Assistance for Family Caregivers application
     - This form allows Veterans and Caregivers to fill out and submit the Caregiver application online.

### Launch Date
*Please provide the launch or rollout date and details.*
- Release date: 7/2/2024
     - The guide is being updated due to recent web component changes and new form fields that were released July 2nd.  There was a short preparation time before launch, and we were not able to have the guide updated timely.

### Version Number
*Please provide the version number of the guide and/or video.*
- Version number 1.2

### Product Guide
*Please provide product guide link*
- [Draft Product Guide for the 10-10CG in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Product/HJ%20Draft%20-%20Online-10-10CG-Product-Guide%207-11-2024.docx)

### Product Video
*Please provide product video link*
- There is no video for this update

### Product Video Transcript
*Please provide product video transcript link*
- There is no video for this update

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Draft looks good, sending to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Working copy attached; please use it for future versions. Thank you![Caregiver Benefits Application Form-10-10CG-v1.2_Product-Guide_SRT 07122024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjdsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b9aa02fd4300304dd66237afaccd837a388d166/Caregiver%20Benefits%20Application%20Form-10-10CG-v1.2_Product-Guide_SRT%2007122024.docx)

**Comment by hdjustice** [comment]
Thank you @starlow00 !
