### ISSUE TITLE
Documentation: How to for connecting to PEGA s3 bucket

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88213]
As a dev on the EZ Fax team, I need help connecting to PEGA's s3 bucket from the IVC forms team.

Acceptance criteria
- Write a brief how-to document for a dev audience that tells them how to set up a connection to PEGA's s3 bucket (the same place where we drop files in staging)
- DO NOT SHARE outside of the IVC forms team. Hand this off to Bo and he'll pass along to others. This is to avoid getting our engineers pulled into ongoing support.

**Comment by cloudmagic80** [comment]
Clarified with Bo who the intended audience is.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/PEGA%20AWS%20S3%20connection
