### ISSUE TITLE
10-7959f-1: update copy for 'same as' address

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#88230]
Update copy for the 'same as' address screen to match the change that was made to FMP claim form:

<img width="694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f39f2558d16f71da9897a6dfb3828653d784735d/Screenshot%202024-07-12%20at%201.25.38%E2%80%AFPM.png" alt="Screenshot 2024-07-12 at 1.25.38 PM.png" />

**Comment by reiting** [comment]
@marywang2 this is in staging and ready for review.
