### ISSUE TITLE
Flipper UI access for Gabriel Zurita

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#88238]
### Your Name

Gabriel Zurita

### Your GitHub handle (Flipper UI access is managed through GitHub)

gabezurita

### Team, Role, and Company of the target individual

Accredited Representative Facing, Software Engineer, Coa

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

The Accredited Representative Portal will need to be enabled in production.
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representative-facing

**Comment by davidpetras** [comment]
@gabezurita you have been granted access to `lesser environments` and `production`. Have a great weekend!

**Comment by gabezurita** [comment]
Thanks, @davidpetras !! Much appreciated, and you too!
