### ISSUE TITLE
[Design] - Create Upated Account Settings mock based on T&C ticket findings

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8824]
## Backrground
An updated design mock is needed to reflect the "terms and conditions not accepted" state

See ticket: [[FE] Investigate existing functionality for Terms & Conditions on Account page #8753](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8753)

Links: /health-care/medical-information-terms-conditions

## Tasks:
- [ ] Create updated design mock for new T&C state

## Acceptance Criteria
- Mock has been created for this state

**Comment by tressaellen** [comment]
Hi @peggygannon - the first screenshot is what we have currently for the Terms and Conditions section in Account security. The second screenshot is what was in the mocks for profile 2.0, do you have any suggestions on how to tighten up this messaging? Maybe something that in between the two?

![Screen Shot 2020-05-29 at 1.32.21 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/6148c6fe-a8b7-47bb-86ad-258482ca8c8d)

![Screen Shot 2020-05-29 at 1.32.27 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/25fe5cd1-3d3e-4ef1-8d95-13401eb5ef84)

**Comment by tressaellen** [comment]
Also @peggygannon this is the messaging for when a user has already accepted the Terms and Conditions. And a screenshot from the actual Terms and Conditions page. Do you think it would be useful to streamline the verbiage? (e.g. Health Tools vs Medical Information) The actual Terms and Conditions page uses both... I'm not sure if that's on purpose or not.

![Screen Shot 2020-05-29 at 1.46.36 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f58e7360-a776-42bc-8cc7-5aee92aa33a0)

![Screen Shot 2020-05-29 at 1.43.50 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/3d3b9b2a-9d91-4182-8e7d-0283a2d0b631)

**Comment by peggygannon** [comment]
@tressaellen here is an updated message. Let me know if you have any questions. 

Before using our health tools, you’ll need to read and agree to the terms and conditions for medical information. This will give us permission to share your VA medical information with you. Once you do this, you can use the tools to refill your VA prescriptions or download your VA health records. 

[Go to the terms and conditions for medical information](link to terms and condition page)

----
Please update accepted message to: 
You've accepted the terms and conditions for using VA.gov health tools

**Comment by tressaellen** [comment]
This looks great - thanks @peggygannon !

<img width="166" alt="Screen Shot 2020-06-02 at 11 42 03 AM" src="https://user-images.githubusercontent.com/58752772/83562491-20dc2680-a4c6-11ea-95fd-bc9c8062ceb8.png">
<img width="163" alt="Screen Shot 2020-06-02 at 11 42 10 AM" src="https://user-images.githubusercontent.com/58752772/83562494-220d5380-a4c6-11ea-8c02-febac31783c0.png">
