### ISSUE TITLE
DD bugfix for resource links

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#88256]
### User story

As a Cartography team member, I want to add datadog custom actions to the three columns of links below the six boxeson the landing page, so that we can track clicks on individual links (and overcome the issue with the va-link component not passing its link text through to DD).

### Notes
- Daniel filed [a ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3001) with the DS team to overcome the technical reason that the link text of a `va-link` doesn't automatically get read by DD as its action name
- See also https://github.com/department-of-veterans-affairs/va.gov-team/issues/87625

Possible tasks:
- 

## Acceptance criteria

- Confirmed that the DS team hasn't already solved this (consulted their ticket linked above, or checked DD)
- Replace `<va-link />` with normal `<a />` links the MHV landing page. 
- Confirmed clicks are being tracked in DD
- QA review

**Comment by dcloud** [comment]
This ticket originally suggested adding custom actions for links when really we should remove `<va-link />` since it doesn't work like a regular link, and our code disables the enhancement (custom GA event) that `<va-link />` adds on top of a regular link.

**Comment by dcloud** [comment]
Here's a [session where hub/resource link clicks were recorded](https://vagov.ddog-gov.com/rum/sessions?query=%40application.id%3A1f81f762-c3fc-48c1-89d5-09d9236e340d%20%40session.id%3A%22d27c65e5-ebd2-4d9f-88ba-8738532c082e%22%20%40type%3Asession&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZC9cJ7jmHI0EwAAAAAAAAAYAAAAAEFaQzljSjdqQUFDeTlPSEtwLWM5c0J5dgAAACQAAAAAMDE5MGJkODktYTZhNC00NGY1LWE4YzYtZDk2NTFjMTMzNzQ2&fromUser=false&refresh_mode=paused&sort_by=timestamp&sort_order=desc&track=rum&viz=stream&from_ts=1721080506381&to_ts=1721166906381&live=true) in staging.

You can also search in session explorer by link text, e.g.: `@action.name:"click on Pay copay bills"`

**Comment by allanto-ah** [comment]
Environment: Production

Verified that user clicks are being tracking in DD for the resource links
