### ISSUE TITLE
Bug: Failed 10-10d submit

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88261]
I was submitting a test app on staging that failed, so I thought this would be a good exercise to see what we know about the failure. This should be a multi-page form with supporting docs for each of 7 applicants.

App was submitted while logged in as test user EARL	M	ROGERS (check with Bo for login details)

Failed immediately after clicking submit. I haven't tried to resubmit. 

PDF of review page: (https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0xZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a83d342bb61ae1d3a2b5527c1e7520627d20e4b6/screencapture-staging-va-gov-family-and-caregiver-benefits-health-and-disability-champva-apply-form-10-10d-review-and-submit-2024-07-12-16_08_08.pdf)

Error displayed on the page
<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc5d0bffce8560d4826568853d05c2283d5f5dcb/image.png" alt="image.png" />

Application ID displayed on the page is 34014--confirm whether that tells us anything.

<img width="809" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9ZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3738c0e682f71c19984e1f495d78dd2a3d1327d/image.png" alt="image.png" />

**Comment by cloudmagic80** [comment]
In staging now
@baltes You can start testing.
https://github.com/department-of-veterans-affairs/vets-api/pull/17571

**Comment by cloudmagic80** [comment]
[Uploading... Screenshot 2024-07-17 at 11.08.31 AM.png]

**Comment by cloudmagic80** [comment]
<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd72e24a6cdd766312117f404ffa0bfe92cbaca5/Screenshot%202024-07-17%20at%2011.08.31%20AM.png" alt="Screenshot 2024-07-17 at 11.08.31 AM.png" />

**Comment by baltes** [comment]
Hey @cloudmagic80 , I submitted a 10-10d after our daily at about 11 central. Everything seems to have worked but I didn't get an email. I had my email address included for one of the applicants. Is that a separate issue? PDF of review page below:

[screencapture-staging-va-gov-family-and-caregiver-benefits-health-and-disability-champva-apply-form-10-10d-review-and-submit-2024-07-18-11_24_15.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1504cec0c8d38b6d6e74b32fd8cc5a3b3643427/screencapture-staging-va-gov-family-and-caregiver-benefits-health-and-disability-champva-apply-form-10-10d-review-and-submit-2024-07-18-11_24_15.pdf)

**Comment by cloudmagic80** [comment]
@baltes  It is a separate issue is the email is in a different program
