### ISSUE TITLE
Monitor whether applicants are authenticated

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88263]
As a member of the IVC forms team, I want to see metrics for how many users are authenticated versus not authenticated.

If possible, include LOA level.

**Comment by baltes** [comment]
@balexandr Please add info on how to review.

**Comment by balexandr** [comment]
@baltes I recently put it on the dashboard 
![Screenshot 2024-07-26 at 2 34 54 PM](https://github.com/user-attachments/assets/d303cae8-2049-4d3f-a016-1fb6f80a59fc)
