### ISSUE TITLE
DD: Integration KPI dashboard based on Metrics

### ISSUE THREAD

**Issue by katbrinkley** [department-of-veterans-affairs/va.gov-team#88264]
### User story

As a Cartography team member, I want to recreate an updated version of the [MHV-on-VA.gov Integration RUM dashboard](https://vagov.ddog-gov.com/dashboard/hzz-d8e-79j/mhv-on-vagov-integration-rum?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1720814621053&to_ts=1720818221053&live=true) with the same integratio KPIs (engagement, conversions) but based on our new custom metrics.

### Notes
- Using custom metrics seemed to be the most straightforward option to preserve RUM data past 30 days for us to analyze and refer back to.
- The original dashboard widgets use real-time queries, while this dashboard will show past data

## Acceptance criteria
- Verify that the custom metrics are indeed preserving the data longer than 30 days for:
  - Engagement widget
  - Conversions widget
  - _[any other Metrics?]_
  - NOTE: cross-check with #88531 (evaluation plan) so that the Metrics are measures we're interested in for the long term
- Team meeting (Wes/Florence/Kat/Robyn?) to approve

**Comment by katbrinkley** [comment]
Kat will take this next sprint

**Comment by wesrowe** [comment]
Dropping this unless/until GA can't meet the need.
