### ISSUE TITLE
Profile Data Component for the Veteran Information Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8829]
## Description
For some fields, we want to share that info for the Veteran to review it, and not update it.  The ultimate intent here is to allow the Veteran to correct it via the phone number if need be.

## Considerations
- We allow the Veteran to continue on if that information is incorrect
- VA file number needs to come from somewhere
- If you are missing a Participant ID or a SSN, you cannot use this form (you are not in CorpDB)
- Include GA Team to get these errors managed

## Tasks
- [x] Build a profile component on the Veteran Information Page that shows the Veteran profile info per [this mockup](https://xd.adobe.com/view/ca825c11-2268-458f-4fec-6aaecfec5b2d-bcb3/): 
  - **Name**, 
  - **DOB**, 
  - **Gender**

## Acceptance Criteria
- [x] A page is created per the mockup and a PR has been requested for merging

## Next Steps
- effects on unit tests, schemas?

**Comment by jason-gcio** [comment]
![Info-Review](https://user-images.githubusercontent.com/53826255/81216223-97116a00-8fa8-11ea-83b2-65f5c72a53c2.JPG)

**Comment by micahchiang** [comment]
Copying @sporeboy's comment from #8838 

The three screens that will change to address static biographical data presented in the form:
- The first Veteran info screen will show static info; the address screen will remain... [(Mockup)](https://xd.adobe.com/view/ca825c11-2268-458f-4fec-6aaecfec5b2d-bcb3/screen/dc153448-40b1-4d35-b890-698dca690305/Add-Modify-Dependents-Veteran-Details)
- Following the precedent in the 526 form, the Veteran info screen will display Name, Gender and DOB; SSN and VA File Numbers are not presented
- If one of Name, Gender, DOB, SSN or VAFN are missing, the form will error and show the user an alert... [(Mockup)](https://xd.adobe.com/view/057055ba-4c2b-4367-667b-7d7034cb43b4-7341/screen/457ed757-b2d0-46c1-9beb-f89980f6d5ca/Add-Dependents-Intro-LoggedIn-Error-1)
- Content/copy in the alert may change/pending review
- The 686 form review screen will not present the static Veteran biographical info, but will present and editable review of the address... [(Mockup)](https://xd.adobe.com/view/88794e80-ae26-4f3e-509e-94d09eb571f7-fe48/screen/f6ccacc0-0160-4213-a085-b3876cb6daa9/Verification-1A-ALT)
