### ISSUE TITLE
AWS access for Amanda Nantais-Austin

### ISSUE THREAD

**Issue by anantais** [department-of-veterans-affairs/va.gov-team#88299]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Amanda Nantais-Austin

### Your Email

anantaisaustin@metrostar.com

### Team, Role, and Company of the target individual

CMS Team, Drupal Devloper, Oddball and Metrostar

### Product Manager (PM) name and email

Grace Kretschmer mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Desired AWS Access

vfs-cms-developers

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/user-attachments/assets/00b28adc-a409-4170-8cc7-759290f8abd3)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
User is listed in the platform team roster.

**Comment by ben-allen-oddball** [comment]
Please reach out to your project manager to be added to atlas.

**Comment by little-oddball** [comment]
Being added to Atlas is not an absolute in blocking access for Platform teams.

**Comment by ben-allen-oddball** [comment]
Created pull request: https://github.com/department-of-veterans-affairs/devops/pull/14565
