### ISSUE TITLE
CT-EYB: Validation does not prevent the recalculation from occurring

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#8830]
Steps to reproduce:
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
2. Expand Learning format and schedule accordion
3. Enter in an invalid postal code
4. Expand Tuition and fees per year and modify amount so we can recalculate
5. Expand Learning format and schedule to see the validation error is still there
6. Select Calculate benefits
7. Observe calculation still occurred even with the validation error
##

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/81217081-03409d80-8faa-11ea-966a-e30ba3dba32d.gif)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12611

**Comment by sonntag-adam** [comment]
Validation error is retained after changing Which GI Bill benefit do you want to use? (Learn more) to anything non Post 9/11. The zip code field is hidden but prevents calculation. 

Steps on testing that failed QA

1. Type in an invalid zip code
2. expand your benefits accordion
3. change Which GI Bill benefit do you want to use? (Learn more) from post 9/11 to something else
4. go back to see that the zip code field is gone
5. then try and calculate
6. you can't calculate because of the validation error that is still occurring on the now hidden zip code field


Moving back to in progress.

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/82326110-58b57b00-99aa-11ea-8c8b-13aaf9055847.gif)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam UX took a look and this checks out!

**Comment by sonntag-adam** [comment]
Closing bug
