### ISSUE TITLE
AWS access for Jacob Bapple

### ISSUE THREAD

**Issue by JakeBapple** [department-of-veterans-affairs/va.gov-team#88301]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Jacob Bapple

### Your Email

jbapple@metrostar.com

### Team, Role, and Company of the target individual

CMS Team, Drupal Engineer, Metrostar

### Product Manager (PM) name and email

Grace Kretschmer - mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn - Erika.Washburn@va.gov

### Desired AWS Access

vfs-cms-developers

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![e-qip transmittal](https://github.com/user-attachments/assets/0924462f-0008-4a65-ad1b-8eb4fea580dc)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [X] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Hi @JakeBapple! I see that you're requesting access "vfs-cms-developers". Could you tell me what that is in reference to? Alternatively, if you give me the name of one of your team members, I can give you the same permissions.

**Comment by barbarello** [comment]
@JakeBapple are you still requesting this access ?

**Comment by JakeBapple** [comment]
I no longer am in need of AWS access. Thank you to those involved.
