### ISSUE TITLE
Standardize landing page design across alert states

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#88316]
### User story

As a Cartography team member, I want to standardize all no-MHV-access alert landing pages so that the same content (outside of alert) is shown to everyone OR so that any differences are intentionally made and documented

Possible tasks:
- Include any UX folks that have worked on these designs in the recent past to find common ground
- Alert states to document:
  - "Verify" alerts (non-LOA3)
  - "no MHV access" alert (not registered at facility)
  - ¿downtime alerts?

## Acceptance criteria
- Standardization of designs is complete and all documented in Figma
- [Design decisions are logged in the design decision github doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/design/decisions-tracker.md)

**Comment by wesrowe** [comment]
I confirmed that account-related alerts have also been cleaned up. I used an unverified (loa1) credential to get this version, which aligns with the no-facility-registration alert version:
![Image](https://github.com/user-attachments/assets/89eecb94-bcea-41c3-a729-3c12e67d4962)

closing.
