### ISSUE TITLE
CT-EYB: "About your school" questions out of order

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8831]
## Summary
For schools in the comparison tool, there are several fields used to calculate benefits. These fields are divided into sections. One of these sections is "About your school". Two of the questions in this section are out of order.

![Screen Shot 2020-05-06 at 2 45 52 PM](https://user-images.githubusercontent.com/45575003/81217288-59addc00-8faa-11ea-9f45-ece355b5a84c.png)

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool/profile/11806124
1. Access above URL
2. Expand the "About your school" group of questions in the Estimate your benefits section
3. Select No for "Are you an in-state student?"
4. Observe the ordering of the following questions:
- Tuition and fees per year
- In-state tuition and fees per year

## Desired behavior
The ordering of the questions in that section should be as follows:
- Are you an in-state student?
- **In-state tuition and fees per year**
- **Tuition and fees per year**
- Books and supplies per year
- School Calendar
- How many terms per year?
- How long is each term?
- Enrolled

## Acceptance Criteria
- [ ] Questions are ordered as described above

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12556

**Comment by delli-gatti-michael** [comment]
#### Local testing complete

![Screen Shot 2020-05-07 at 10.17.47 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/79d103b9-514f-4754-a8e2-61b731c56a74)

**Comment by delli-gatti-michael** [comment]
Changes are now in Staging. Closing this issue
