### ISSUE TITLE
Analytics Implementation or QA Support for [10-10 Health Apps - 10-10EZ Root URL update]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88325]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - [10-10 Health Apps team]

- **Product Name**

    - [10-10EZ Veteran health care application]
      
- **When is the launch date?**
    - [May 6, 2024]

- **Provide the link(s) for Product/Page urls**
  
    - [http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/introduction]

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - [We have updated the root URL for the 10-10EZ to align with VA.gov standards.  The URLs listed below should be updated in our current "**Form 10-10EZ - Enrollment Application for Health Benefits**" DOMO dashboard}

|URL|
|----|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/introduction|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/id-form|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/personal-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/maiden-name-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-sex|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/demographic-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/veteran-address|
|www.va.gov/health-care/aapply-for-health-care-form-10-10ez/veteran-information/veteran-home-address|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/contact-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/basic-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/pension-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/service-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/additional-information|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/toxic-exposure|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/radiation-cleanup-efforts|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service-dates|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/operation-support|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/agent-orange-exposure|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxins-or-hazards|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure-dates|
|www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/documents|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-use|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information-confirm|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-needed|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/marital-status|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-personal-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-additional-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-financial-support|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-contact-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependents|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependent-information|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/veteran-annual-income|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-annual-income|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/deductible-expenses|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicaid|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare-part-a-effective-date|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/general|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/va-facility-api|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/review-and-submit|
|www.va.gov/health-care/apply-for-health-care-form-10-10ez/confirmation|

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [No test users are needed]

- **Any additional comments**

    - [No further comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @hdjustice  -- thank you for submitting this. Confirming we have it on our backlog. Now that we're officially moved over to GA4, we'll be pulling in these kinds of requests, and will let you know once we've pulled this into one of our sprints.

FYI @Blivaditis, @ChristineYoungZA

**Comment by hdjustice** [comment]
Thanks @johnny-jesensky-adhoc !
@luis-simauchi FYI

**Comment by Blivaditis** [comment]
Hi @hdjustice, I was doing q quick review of the cards we have queued up for next sprint and I noticed two different 10-10ez update requests ([link to the other request)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85873). Based on URLs provided they all appear to be the same, however the order of the URLs is different. This will impact how your funnel is displayed in Domo once the update is pushed. Before we pull aa request in and start updating would you be able to confirm the correct order of the URLs. @luis-simauchi submitted the new request.

**Comment by hdjustice** [comment]
@Blivaditis Hi!  I am not sure what happened but the URLs for both requests are not quite right.  I updated the list in this request and we can close the other one, unless you would prefer to use the other ticket and spreadsheet, in which case I can update that instead.  (not sure why these tickets are different formats either, so sorry about all this!)
cc @luis-simauchi

**Comment by Blivaditis** [comment]
No worries I will use this as the main ticket, thank you!

**Comment by Blivaditis** [comment]
@dorseypa1 @johnny-jesensky-adhoc here is the link for the [BQ update spreadsheet ](https://docs.google.com/spreadsheets/d/1s1si8o7hdjmGHGcE_oLGv4E_lu5bgn0eMPP8U5LJA_g/edit?usp=sharing)

**Comment by Blivaditis** [comment]
The load has been updated, will verify once results are appearing in the Forms dashboard.

**Comment by johnny-jesensky-adhoc** [comment]
Great -- moving this to _**Done**_.

@Blivaditis, @ChristineYoungZA  -- leaving this as a note to verify the fix next week after the dataset has been refreshed.

**Comment by hdjustice** [comment]
Hello!  I see this ticket is done (so sorry for the lateness), but I am not seeing these URLs in the Forms dashboard, Can someone let me know if I am not looking at the right dashboard?

Using Domo URL - https://va-gov.domo.com/page/447193050
- Some how our 10-10EZ form ended up with 2 entries in the forms list, but neither of them have data.
