### ISSUE TITLE
[Prometheus] Remove Jenkins Deployments

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#88322]
## Notes
- http://jenkins.vfs.va.gov/job/deploys/

## Acceptance Criteria
- [ ] Jenkins is no longer deploying Prometheus

**Comment by stoiven** [comment]
Jobs that deploy Prometheus:

- http://jenkins.vfs.va.gov/job/deploys/job/prometheus-vagov-dev/
- http://jenkins.vfs.va.gov/job/deploys/job/prometheus-vagov-prod/
- http://jenkins.vfs.va.gov/job/deploys/job/prometheus-vagov-sandbox/
- http://jenkins.vfs.va.gov/job/deploys/job/prometheus-vagov-staging/
- http://jenkins.vfs.va.gov/job/deploys/job/prometheus-vagov-utility/

**Comment by stoiven** [comment]
Old release job seems to be deleted:
http://jenkins.vfs.va.gov/job/releases/job/prometheus/

Main build:
http://jenkins.vfs.va.gov/job/builds/job/prometheus/
