### ISSUE TITLE
[Prometheus] Disable Releases

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#88321]
## Notes
- http://jenkins.vfs.va.gov/job/releases/job/prometheus/

## Acceptance Criteria
- [ ] Jenkins is no longer generating releases for Prometheus

**Comment by nfpappas-oddball** [comment]
I removed all Prometheus references from the seed job. I noticed that the job still got re enabled but now now longer re-enables it self. Dont know if we should just delete the job and get it out of jenkins permanently
