### ISSUE TITLE
Contact Center Review for [Unified Appointments - After-visit summary MVP ]

### ISSUE THREAD

**Issue by ninaranusavice** [department-of-veterans-affairs/va.gov-team#88348]
# Request the Contact Center Review 

##  After-visit summary
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://dvagov.sharepoint.com/:w:/s/HealthApartment/EZnjwpw3QOpHtT_6VPfX6-0BaKVhfJBldzxb32zvhBNxAw?email=Steven.Tarlow%40va.gov&e=TMuF9r)
 

##  After-visit summary 
The After-visit summary (AVS) will provide a Veteran with a summary of their appointment visit with their medical provider at a VA facility. The Veteran can access their AVS according to the date of their appointment via the "Appointments" list page under "Past" appointments. The AVS will be available through MyHealtheVet on VA.gov. and will:
- Promote patient-centered, outpatient care
- Summarize medications, appointments, tests, patient education material and other instructions
- Enhance communication
- Engage patients in their care
- Improve recall of medical instructions
- Meet electronic health record Meaningful Use criteria

### Launch Date
The launch date is projected in July or August of 2024. However, only a select few Veterans will have access to their AVS.

### Version Number
*Version 1.0*

### Product Guide
*[After-visit summary](https://dvagov.sharepoint.com/:w:/r/sites/HealthApartment/Shared%20Documents/Appointments/After-visit%20Summary/[AFTER-VISIT_SUMMARY_PRODUCT_GUIDE.docx](https://dvagov.sharepoint.com/:w:/r/sites/HealthApartment/Shared%20Documents/Appointments/After-visit%20Summary/AFTER-VISIT_SUMMARY_PRODUCT_GUIDE.docx?d=w9cc2e399403747eab53ffa54f7d7ebed&csf=1&web=1&e=6g6zEi)?d=w9cc2e399403747eab53ffa54f7d7ebed&csf=1&web=1&e=6g6zEi)*

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by ninaranusavice** [comment]
Do I attach a shared link for anyone to have access to it?

Nina

From: Steven Tarlow ***@***.***>
Sent: Monday, July 15, 2024 2:48 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Anusavice, Nina R. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Unified Appointments - After-visit summary MVP ] (Issue #88348)


Hi @ninaranusavice<https://github.com/ninaranusavice>. Can you please attach the document in Word format?

-

**Comment by ninaranusavice** [comment]
@starlow00 added word format.

**Comment by starlow00** [comment]
Thank you, @ninaranusavice!

**Comment by starlow00** [comment]
@ninaranusavice The link gives me a 404 Not Found now. Are you able to attach the .doc in the comments?

**Comment by ninaranusavice** [comment]
@starlow00 I've also sent it to your email. 

[After-visit summary product guide](https://dvagov.sharepoint.com/:w:/s/HealthApartment/EZnjwpw3QOpHtT_6VPfX6-0BaKVhfJBldzxb32zvhBNxAw?email=Steven.Tarlow%40va.gov&e=WQJeeR)

**Comment by starlow00** [comment]
@ninaranusavice Got it, emailing to my VA address worked. Thank you!

**Comment by ninaranusavice** [comment]
Thank you Steven. Apologies for the initial difficulties.


From: Steven Tarlow ***@***.***>
Sent: Monday, July 15, 2024 5:15 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Anusavice, Nina R. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Unified Appointments - After-visit summary MVP ] (Issue #88348)


@ninaranusavice<https://github.com/ninaranusavice> Got it, emailing to my VA address worked. Thank you!

-

**Comment by starlow00** [comment]
Hi @ninaranusavice. I see that the last update (v3) for the Revision History note on this guide was from 3/5/2024. Is this July/August update technically v4, then? Also, how should the Revision History description for this latest release read?

**Comment by ninaranusavice** [comment]
Hi Steven,

From my recollection, I haven't made any new revisions since 3/5/2024. If your team made any changes, then yes, is should be v4 and just describe what changes were made.  Am I answering your question?

Thank you,
Nina Anusavice


From: Steven Tarlow ***@***.***>
Sent: Thursday, July 18, 2024 3:41 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Anusavice, Nina R. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Unified Appointments - After-visit summary MVP ] (Issue #88348)


Hi @ninaranusavice<https://github.com/ninaranusavice>. I see that the last update (v3) for the Revision History note on this guide was from 3/5/2024. Is this July/August update technically v4, then? Also, how should the Revision History description for this latest release read?

-

**Comment by kristenmcconnell** [comment]
This is actually the very first release of this product on VA.gov. The dates in the document are internal edits that we made throughout the development process.

**Comment by starlow00** [comment]
Understood. Thank you, @ninaranusavice and @kristenmcconnell!

**Comment by starlow00** [comment]
Draft looks good, sending to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. I've attached the current copy of the guide. Please use it for future product revisions. Thank you!

[AFTER-VISIT_SUMMARY_PRODUCT_GUIDE v1 release SRT 07182024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0FDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ea8a80156f1f50ccdabdc82e4faef00ac735704/AFTER-VISIT_SUMMARY_PRODUCT_GUIDE%20v1%20release%20SRT%2007182024.docx)

**Comment by ninaranusavice** [comment]
Thank you very much, Steven.

Nina

From: Steven Tarlow ***@***.***>
Sent: Tuesday, July 23, 2024 5:59 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Anusavice, Nina R. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Unified Appointments - After-visit summary MVP ] (Issue #88348)


No changes from VEO. I've attached the current copy of the guide. Please use it for future product revisions. Thank you!

AFTER-VISIT_SUMMARY_PRODUCT_GUIDE v1 release SRT 07182024.docx<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0FDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ea8a80156f1f50ccdabdc82e4faef00ac735704/AFTER-VISIT_SUMMARY_PRODUCT_GUIDE%20v1%20release%20SRT%2007182024.docx>

-
