### ISSUE TITLE
Track Puma backlog

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88350]
## User Story
As the developers and managers of the Platform,
We need to continue tracking the Puma Backlog,
So that we can determine when there are new errors that Puma is throwing. 

## Issue Description
This is an extension of ticket #87375, intended to monitor and track the Puma backlog. 

## Tasks
-  Monitor Puma backlog

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
Puma threads were lowered to 8 today. There was a slight spike during the sync that resolved relatively quickly (within 20 sec) - most likely for the HPA to scale up

**Comment by rmtolmach** [comment]
We saw a spike in the backlog when the external service VAOS was down intermittently. Investigating.

**Comment by LindseySaari** [comment]
The backlog is looking much better. We've identified that the appeals spikes are related to the long timeouts. VAOS service had an issue causing cascading latency, failures, etc that the team is tracking. Overall, the new readiness script combined with the HPA adjustments are proving to be effective!
