### ISSUE TITLE
Platform Orientation feedback ticket from Design System Team team

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#88365]
This ticket is for reporting to Governance the state of all materials referenced in the Platform Orientation process. If you have any questions or concerns, please contact Governance team on Slack using the @platform-governance-team-members group on the #platform-team channel. Thank you. 

- [ ] Update title of ticket with your teams name

## ALL Platform Teams
- [ ] Review the [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/.github/ISSUE_TEMPLATE/orientation-feedback.md)
- [ ] Review the [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team%2C+platform-tech-team-support&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
- [ ] Verify all links/references are accurate
   - [ ] If a broken link or wrong reference is identified, please include details below:
- [ ] Verify there are no gaps in what new team and team members need to know about Platform
   - [ ] If a gap is identified, please include details below:
- [ ] Make recommendations and/or suggestions for improvements to Platform orientation
   - [ ] If your team has recommendations or suggestions, please include details below:

## Platform Support team
- [ ] Watch the [Platform Support overview video](https://www.youtube.com/watch?v=iwIQU4XepNQ) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Platform Support will rerecord.
     - Ticket number:

## Platform Content team
- [ ] Watch the [VFS Orientation to Platform Website video](https://www.youtube.com/watch?v=yzl6nyLmqkA) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Platform Content will rerecord.
     - Ticket number:
        
## Design System Team
- [x] Watch the [Design System/Forms Library Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-DesignSystem/FormsLibraryOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [x] Video is not up to date and Design System team will rerecord.
     - Ticket number:

## Backend COP
- [ ] Watch the [Backend Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Back-endOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Backend COP will rerecord.
     - Ticket number:

## Frontend COP
- [ ] Watch the [Frontend Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Front-endOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Frontend COP will rerecord.
     - Ticket number:

## Analytics & Insights team
- [ ] Watch the [Analytics Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AnalyticsOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Analytics & Insights team will rerecord.
     - Ticket number:

## Governance team
- [ ] Watch the [Design & Research](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Design&ResearchOrientation) and verify content is up to date and accurate. 
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:
- [ ] Watch the [QA Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAOrientation) and verify content is up to date and accurate.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:
- [ ] Watch the [Accessibility Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AccessibilityOrientation) and verify content is up to date and accurate. 
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:

**Comment by caw310** [comment]
Onboarding orientation for VADS has been reviewed and it's fine for now. But we will update it once the three remaining v1 components are deprecated. I created a ticket to rerecord down the road. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3062

**Comment by caw310** [comment]
@shiragoodman this done.

**Comment by shiragoodman** [comment]
Thanks @caw310 - did you complete the section above for All Platform Teams? We'd like you to take a look at the gh ticket new teams and new team members are asked to complete.

**Comment by caw310** [comment]
@shiragoodman templates and links look good to me.
