### ISSUE TITLE
Update 'identity dashboard' development seed in vets-api - ROLL

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#88369]
The current `ClientConfig` seeded database values for the `identity_dashboard` application on localhost are out of date, so we need to update them with the following changes:

- Currently `client_id` is seeded to `identity_dashboard`, should be updated to `identity_dashboard_rails`
- `redirect_uri` should be set to 'http://localhost:4000/sessions/callback'
- `logout_redirect_uri` should be set to 'http://localhost:4000/sessions/logout_callback'
- `access_token_audience` should be set to 'identity dashboard'

**Comment by emilykim13** [comment]
Testing comment

**Comment by parkerbees** [comment]
Moved to Jira for sprint 3. Closing.
