### ISSUE TITLE
Qualitative Data Request | 

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88373]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

07/01/2023

### Date Range End

07/01/2024

### Product Name(s)

21-686c\21-674

### Product Description

The online 686c form allows Veterans to add or remove dependents from their VA benefits. The online form flow is integrated with the 21-674 form (Request for Approval of School Attendance), which is used when claiming benefits for a Veteran's child who is at least 18 years old, but under 23, and attending school.

### Survey URL(s), key term(s), case category or type

Navigation issues, submission issues, upload/download documents, Inaccurate or Missing Information/Status, Inability to Access Tool, Unable to Update Information, Feedback, Concern

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

laura.steele1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have nay questions. Thank you.
