### ISSUE TITLE
FMP Submission Bug

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88384]
As an FMP applicant, I need my form transmitted on submit so that it can be processed and I can get a confirmation message.

[Slack thread](https://agilesix.slack.com/archives/C06K2LXCQJG/p1721078011557299)

Implementation Steps
- F-1 isn't utilizing the attachments service module. Let's add it so that the file_name can properly get the prefixed uuid.

Testing
- Go through end-to-end and ensure pega gets through to the status update piece

**Comment by balexandr** [comment]
PR is up for review https://github.com/department-of-veterans-affairs/vets-api/pull/17559 we'll have to wait for PEGA to get their side back up and running properly before we can close this ticket.

**Comment by balexandr** [comment]
@baltes I think this can be closed. Mary and I were getting emails after PEGA fixed their metadata mismatch.
