### ISSUE TITLE
QA Standards - Appointments FE Team - Appointments on VA.gov

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#88393]
#### VFS team name
Appointments FE Team

#### VFS product name
Appointments on VA.gov

#### VFS feature name
Appointment Details Redesign

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Regression tests not executed or results of execution not included
#### Test Plan
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Test plan not executed or results of execution not included
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No Coverage for References attached
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 89.22

- Functions %: 85.62

- Statements %: 88.91

- Branches %: 81.02

- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by ldelacosta** [comment]
Hi @it-harrison. Could you look at our QA documents and let me know if I'm missing anything else. Thank you.

**Comment by it-harrison** [comment]
Hi @ldelacosta - I checked the regression plan and test plan artifacts in the Collab Request ticket but didn't notice any difference since the Staging Review...but I could be missing something (that is, the results of having executed the test plans).

**Comment by ldelacosta** [comment]
@it-harrison - We have executed the test plan and regression plan tasks. Per our conversation, I'm good to close the ticket. Please reach out if there's anything else. Thanks!
