### ISSUE TITLE
Draft ITF conversation guide

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#88394]
Acceptance Criteria
- [x] Draft conversation guide plan
- [x] Share for feedback from team
- [x] Incorporate feedback from team
   - [x] Update research plan with refined goals, hypotheses

**Comment by djones2113** [comment]
[Link to conversation guide](https://docs.google.com/document/d/1N-W19WkHmtLIiWskgvsYm0ThnmIhfj2kMd7SmlLYQ4w/edit) (Gdocs)

**Comment by echin393** [comment]
The conversation guide along with other research materials have been shared as a part of the research intake ticket: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/681

Any final tweaks will be covered as a part of the research prep ticket #93571 .
