### ISSUE TITLE
CT-EYB: Update accordion and question spacing to improve layout.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8842]
As a developer, I need to improve the spacing with the accordions and questions on the profile page so that the readability of the form is improved.

## Assumptions:
1. This work is completed behind a feature flag #7780.
2. Pixels are used in the AC of this story; if the css uses EM instead, use the corresponding EM value and specify in the notes.
3. The numbers available in sketch represent padding + margin.

## Acceptance Criteria
1. All questions have :
    a. margins 24px between questions
    b. margins 24px between question and accordion
    c. A max width of 400px
2. The mini-accordions (Your benefits, About your school, Learning format and schedule, Scholarships and other funding):
    a. Have a width of 400px.
    b. Have 8px of margins between collapsed accordions.
    c. Have the border color of: #AEB0B5
3.  The top margin of the "I'll be taking classes outside the U.S. and U.S. territories" question is 16px.
4. The spacing between the "Where will you take the majority of your classes?" question and it's Learn More link (currently about 24px) matches the spacing between the "Warnings and school closings" filter and it's Learn More link on the search results page (about 10px).
5. The spacing between questions and the radio button answers on the profile page (currently about 36px) matches the spacing of questions and the radio button answers (about 24px) on the search results page.
6. The aria label for "How much are you receiving in military tuition assistance" is: "Learn more about how military tuition assistance affects your benefits".

## Supporting Artifacts
1. AC1a
<img width="577" alt="AC1a" src="https://user-images.githubusercontent.com/48260534/81221267-9b418580-8fb0-11ea-84aa-47f7ecbe6b44.png">
2. AC1b
<img width="451" alt="AC1b" src="https://user-images.githubusercontent.com/48260534/81221272-9bda1c00-8fb0-11ea-969b-48616d0f1f55.png">
3. AC2a
<img width="818" alt="AC2a" src="https://user-images.githubusercontent.com/48260534/81221273-9c72b280-8fb0-11ea-97d5-8714f93239d1.png">
4. AC2b
<img width="786" alt="AC2b" src="https://user-images.githubusercontent.com/48260534/81221274-9d0b4900-8fb0-11ea-923e-3c41bcf2b6a8.png">
5. AC3
<img width="595" alt="AC3" src="https://user-images.githubusercontent.com/48260534/81221277-9d0b4900-8fb0-11ea-8fcf-8f2be8819d5a.png">
6. AC4
<img width="421" alt="AC4_Profile" src="https://user-images.githubusercontent.com/48260534/81221279-9da3df80-8fb0-11ea-8ddb-a92b04a366c6.png">
<img width="244" alt="AC4_SRP" src="https://user-images.githubusercontent.com/48260534/81221283-9da3df80-8fb0-11ea-8a7d-442f6058c004.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12634

**Comment by zurbergram** [comment]
resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/8988

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-05-14 at 9.12.09 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1f05b173-66c2-4cc5-bd83-3d6015087fba)

---

![Screen Shot 2020-05-14 at 9.12.22 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b77b2871-3f0a-419e-a2f6-22d5e4a4c46c)

---

![Screen Shot 2020-05-14 at 9.12.29 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f9656087-676c-4bf8-9acb-a896defb1e2c)

---

![Screen Shot 2020-05-14 at 9.15.26 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3e16350b-8ff8-4de5-9cf9-ccc38d18696a)

---

![Screen Shot 2020-05-14 at 9.21.30 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/62b04961-da96-443e-a720-eb044b3352ff)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Tested by TestRail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/610

**Comment by ccruzgra** [comment]
@delli-gatti-michael Looks like something strange is going on with the highlighted orange and blue areas in your images, like they should be shifted to the right. This is how they are in production: ![Screen Shot 2020-05-14 at 11.59.09 AM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/bd4b006b-79b4-470d-959d-3a9478e61d9e) ![Screen Shot 2020-05-14 at 11.57.26 AM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/2a1187ac-56cd-406c-891a-0e750d708431)

**Comment by delli-gatti-michael** [comment]
I restarted Chrome and that seemed to fix whatever issue my inspect tool was having. Updated screenshots below:

![Screen Shot 2020-05-14 at 1.02.07 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/856c1e3c-a9aa-43be-aede-3f453cc6725c)

---

![Screen Shot 2020-05-14 at 12.47.40 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b46303d1-4160-4cd3-a196-c9cd4e834288)

---

![Screen Shot 2020-05-14 at 12.59.47 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/73e4bb4e-d0a5-4e05-8222-7493c415bada)

---

![Screen Shot 2020-05-14 at 1.00.05 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/88dce85a-e2c6-446f-8d0a-30ecac6f59f8)

---

![Screen Shot 2020-05-14 at 1.00.19 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8a572e5b-ec63-401c-ba6b-b6d226d79514)

---

![Screen Shot 2020-05-14 at 1.00.37 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/0cc6a8b6-3ccd-4ab5-9d5d-8d473ea4f6b4)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah
This is now on Staging and ready for review

**Comment by JenLJ** [comment]
UX has reviewed and it looks good! @delli-gatti-michael

**Comment by delli-gatti-michael** [comment]
Closing this with UX and QA approval
