### ISSUE TITLE
FMP service blueprint/service artifacts

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#88438]
Continue creating creating FMP [service blueprint / service artifacts](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718652759079/9b8e9bf6a84513373bc234644531bf694d9a4f84?sender=u3844370d13a440a7859d3526).

**Comment by rachaelpenfil** [comment]
Ready for review, will send to Lois and Premal when Lois gets back week of 7/22.

**Comment by StevenStraily** [comment]
Closing this ticket for the sprint to represent the work completed. New tickets will be created as needed in the future.

**Comment by marywang2** [comment]
@StevenStraily @rachaelpenfil could we also throw the artifact links into the [GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/foreign-medical-program/10-7959f-1) if they're final?
