### ISSUE TITLE
Preview Environment EKS cluster functional in IP rich subnets

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#88431]
Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/88430

The Preview Environment EKS cluster needs to function in the IP rich subnets

## Acceptance Criteria
 - [x] EKS cluster functional in new subnets

**Comment by JoeTice** [comment]
SPRINT 6 UPDATE: DONE - This ticket was completed on 7/31, but didn't get marked as closed
