### ISSUE TITLE
Staging Review finding: Appointment details title different from h1

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88445]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Appointments
**Product:** Appointments
**Feature:** Appointment Details Redesign

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

On appointment details pages, the `<title>` is `VA appointment on [date] | Veterans Affairs`, but the H1s on these pages are `Video appointment`, `In person appointment`, or `Phone appointment`. 

## Recommended action

The first part of the`<title>` tag before `| Veterans Affairs` should match the text in the H1 on the page. See [guidance on title tags](https://design.va.gov/content-style-guide/title-tags) for more details.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by outerpress** [comment]
@ldelacosta I'm going to start by writing up how we landed on the current title tags and capturing some of the conversations we had around this. Then we can loop back and review with @erinrwhite to look for improvements. FYI also @sterkenburgsara @laurwill

**Comment by outerpress** [comment]
@ldelacosta I dug around and we actually did define new browser tab titles, I think we just never got the work into tickets. I stubbed out #88979 to capture the changes. We'll need to work with the devs to break this up. FYI @Cieramaddox

**Comment by outerpress** [comment]
@ldelacosta I think you can close this one, looks like dev work is done.

**Comment by ldelacosta** [comment]
Closing out the ticket since we have done the work.
