### ISSUE TITLE
CES 384: VPG: Support creation of booked Appointments in OH

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#88473]
CES-384: https://issues.mobilehealth.va.gov/browse/CES-384
> As a patient I need the ability to create appointments using VPG via the va.gov site.

The current VPG logic returns HTTP 400 for appointment creations with status of 'BOOKED'.  Remove this filter and add tests to ensure that booked appointments can be created using VPG.

**Acceptance Criteria**
* Booked appointments can be created in OH using VPG
* Tests exist that verify the successful creation of both VistA and OH booked appointments from VPG

**Comment by BrittanySFowler** [comment]
This will roll to sprint 16.  There was more involved in reworking the VPG code to handle booked appointments than expected
