### ISSUE TITLE
Remove logic that pulls contact from reason code in transformer for VA requests

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88470]
vets-api is now mapping the veteran's contact info from the reasoncode.text field to the appointment contact field. The FE no longer needs to have this logic.

```

contact: {
        telecom: [
          { type: 'phone', value: '2125551212' },
          { type: 'email', value: 'veteranemailtest@va.gov' },
        ],
      },

```

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

### AC:

- [x]  - Cleanup logic that pulls contact from reason code in transformer.
- [x] - Tests updated

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
