### ISSUE TITLE
FE | Profile | Direct Deposit | Remove control info from PUT request

### ISSUE THREAD

**Issue by asiisii** [department-of-veterans-affairs/va.gov-team#88484]
## Background
- The PUT request to the `/v0/profile/direct_deposit` endpoint is currently including control information in the body of the request. Remove the `controlInformation` and only pass the `paymentAccount` data.
```
{
    "id": "",
    "type": "direct_deposit/disability_compensations",
    "attributes": {
        "controlInformation": {
            "canUpdateDirectDeposit": true,
            "isCorpAvailable": true,
            "isEduClaimAvailable": false,
            "hasCpClaim": true,
            "hasCpAward": true,
            "isCorpRecFound": true,
            "hasNoBdnPayments": true,
            "hasIndex": true,
            "isCompetent": true,
            "hasMailingAddress": true,
            "hasNoFiduciaryAssigned": true,
            "isNotDeceased": true,
            "hasPaymentAddress": true,
            "hasIdentity": true
        },
        "paymentAccount": {
            "name": "WELLS FARGO BANK",
            "accountType": "Checking",
            "accountNumber": "****4567",
            "routingNumber": "*****0503"
        }
    }
}
```

## TASKS
-  Remove the `controlInformation` and only pass the `paymentAccount` data to the `/v0/profile/direct_deposit` endpoint
-  Update any related FE tests

## ACCEPTANCE CRITERIA
- the PUT `/v0/profile/direct_deposit` request doesn't send `controlInformation`. Test it on Staging

**Comment by mtcA6** [comment]
@asiisii i was like wait a min this was just open! You closed it while i was looking at it. 

Could you comment out proof that this has been validated? a screenshot showing the log before capturing the extraneous details and a screenshot after showing that it is no longer capturing those extra details? 

Going to reopen this and then once you comment w proof you can close it out again!

**Comment by asiisii** [comment]
**Before**- we can see `controlInformation` data getting passed down in the payload
<img width="727" alt="Screenshot 2024-07-30 at 7 22 23 AM" src="https://github.com/user-attachments/assets/30027cf7-60f5-4d7d-81f3-09aeea4a2c35">


**After** - we can't see `controlInformation` data getting passed down in the payload anymore
<img width="693" alt="Screenshot 2024-07-30 at 7 21 37 AM" src="https://github.com/user-attachments/assets/dc10ef44-c78d-4e48-b757-a2be6130db92">
