### ISSUE TITLE
SOCKS access for Belle Poopongpanit

### ISSUE THREAD

**Issue by bellepx0** [department-of-veterans-affairs/va.gov-team#88482]
### Your Name

Belle Poopongpanit

### Your Email

belle.poopongpanit@agile6.com

### Your GitHub Handle

bellepx0

### Your Role and Team

Software Engineer on Authenticated Experience Design Patterns

### Product Manager (PM) name and email

Lynn Stahl, lynn.stahl@agile6.com

### Product Owner (PO) name and email

Becky Phung, becky.phung@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpDuFfOB7Z3QDPGRu6tJ5s++aRggzbiCd3H+N0TrfJcxHbvvHQONNYyd5JA3ynGK32E4drpSzkVWQLhXvxwtAyF/xEgx40bYOsTCZWE0l14YBKa0OJi7wZiPocvXnRgO8afHCW3rhXmYPxODzcTgQcPBtANQ4r6lcsYTG2kAa1TEyjric4HcLHcQM+JDoHw7JcG17SM2keXx4uWlA20Pa0gnfx2UjAAsHpQUCYsrqLAkeNpGUqSQfdX9taNH81wyGZ9s+DmGenMqkO3RI+JpKOfnI7+nHqK6S/uUn0vjRIU4l/7/VchGbbi/+4+bKoOGSzEw0TnfxCnVeMNA1s6c1a2IRbVFYVQO4LaYF2NMY8g1/TEkVHOV4auyWR0UGWXX56sOJOq8QEM/a/ZikFh0+jNLNKnWd/Qld4+Ocfi9d5kLQiH8B9Gbgz09CRv+hWL8Ve2FIOZprhbaPKb71fu5uKUKomtOceqix2NIWbb6XOYXcnQbUD+Wl97WIlnjJCAG0= belle@Belle-Poopongpanit.local

### E-QIP Transmittal Confirmation

![IMG_4162](https://github.com/user-attachments/assets/8fe2c9b7-8982-490b-a9ed-a2b1e5b0f40a)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Closing this, since the associated PR has been merged. If there's additional work needed here, feel free to re-open this with a comment.
