### ISSUE TITLE
Content review: Yellow Ribbon tool (staging)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#8850]
## User story
As recipient of GI Bill benefits, I need to know if the school I'm interested in is part of the Yellow Ribbon program. 

This ticket captures VSP content feedback  Yellow Ribbon tool in staging. 

Staging link: https://staging.va.gov/education/yellow-ribbon-participating-schools/

## Acceptance criteria
- [x]  Peggy provides content feedback for Yellow Ribbon tool
- [x]  Public website team incorporates feedback and/or asks follow up questions about the feedback
- [x] Leave any comments for feedback you decide not to take
- [x]  Peggy checks tool after content feedback has been incorporated

**Comment by kelsonic** [comment]
Sorry for moving this 🙂

**Comment by jenniferlee-dsva** [comment]
I'm going to respond in-line to @peggygannon 's comments above. 

@AnneHurley when the copy updates on the Drupal static content pages are ready, please loop in @peggygannon for review.

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx @kelsonic (CC @andaleliz  @peggygannon ) - [See replies to comment. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8850#issuecomment-625513027)

@kelsonic - please make this text change on the tool page: 

**Current text:** 
Participating school information on this page is valid for the current academic year, from August 2019 through July 2020.

**Change to, incorporating part of Peggy's edits:** 
Information for participating schools is for the current academic year, August 2019 through July 2020.

**Comment by kelsonic** [comment]
> Information for participating schools is for the current academic year, August 2019 through July 2020.

PR is up for this, any other content updates I should make? CC @peggygannon @jenniferlee-dsva

**Comment by AnneHurley** [comment]
@peggygannon and @jenniferlee-dsva  The copy for static pages is ready for Peggy to review, and is captured in this ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8677

**Comment by peggygannon** [comment]
Thanks, @kelsonic we also need to make this edit: 

Please cap P in Program. Should be Yellow Ribbon Program (not program)

@AnneHurley 
thanks for adding the ticket for the static page.

**Comment by kelsonic** [comment]
PR is merged! Ready for validation 🙂
