### ISSUE TITLE
Remove aria-label from the Yes, cancel and No, do not cancel buttons

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#88523]
## Description
Based on the staging review feedback [Collab Cycle ticket #88449](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/88449), we will need to remove the aria-label from the buttons when asking the Veteran if they would like to cancel their booked appointment or request. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

- [x] Given the user is on the Upcoming list page
        When the user clicks on `Details` for an upcoming booked appointment and clicks `Cancel appointment` button 
        Then the aria-label will be removed for the buttons `Yes, cancel` and `No, do not cancel `

- [x] Given the user is on the Pending list page
        When the user clicks on `Details` for an pending request and clicks `Cancel` button 
        Then the aria-label will be removed for the buttons `Yes, cancel request` and `No, do not cancel`

- [x] Given the user is on the scheduling flow for direct scheduling
        When the user clicks on `Confirm appointment` and clicks `Cancel appointment` button from the confirmation screen
        Then the aria-label will be removed for the buttons `Yes, cancel` and `No, do not cancel `

- [x] Given the user is on the scheduling flow to submit a VA appointment request
        When the user clicks on `Submit request` and clicks `Cancel request` button from the confirmation screen
        Then the aria-label will be removed for the buttons `Yes, cancel request` and `No, do not cancel`

- [x] Given the user is on the scheduling flow to submit a Community Care appointment request
        When the user clicks on `Submit request` and clicks `Cancel request` button from the confirmation screen
        Then the aria-label will be removed for the buttons `Yes, cancel request` and `No, do not cancel`

### Design Assets
N/A

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
UX team will validate.

**Comment by outerpress** [comment]
@ldelacosta @vbahinwillit tested and confirmed this is good to go

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
