### ISSUE TITLE
Write evaluation plan for landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#88531]
### User story

As a Cartography team member, I want to document an evaluation plan that covers how Veterans use the MHV landing page as well as transition metrics that need to be reported out, so that we can guide our work and make sure we're ready to report July numbers.

### Notes
- Keep an eye out for an opportunity to test out unique users in Datadog and GA – e.g., sessions-per-user over a time period
- GA4 and DD are both on the table
- Robyn suggested starting from the [Mural of KPI ideas](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716414036737/5aa77bac68425356bf314724636ed828f6bb5743?sender=uebde62ceb342c6477fb09406)
- Robyn put a Word doc in our team Sharepoint that provides guidance and links to an [example document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/analytics/data-collection-and-analysis-draft.md) we can follow for SM.

Possible tasks:
- Review sample eval plan
- Adapt previous Mural thinking into new format

## Acceptance criteria

- [x] [Drafted evaluation plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/data-collection-evaluation-plan.md)
- [x] Shared back to Robyn for feedback - synced on 7/26 and 7/30
- [x] Ticketed next steps – e.g., July report for OCC, prioritization/ticketing of some portion of evaluation plan - see follow-on ticket #89217

**Comment by wesrowe** [comment]
Note from UX refinement: We decided to try to work the "jobs" work into the evaluation plan. In the hopes that this will combine the two streams of work and provide a holistic view of what we care about (whether it's in the "top 20" metrics in the eval plan or not).

Best case scenario, this might obviate #88043, which is a dedicated "jobs synthesis" story disconnected from this evaluation plan work.

@fmccaf1 @katbrinkley @jonathanjnelson keep me honest here if I'm representing this incorrectly.

**Comment by sterkenburgsara** [comment]
Update: Team began by creating [this google spreadsheet](https://docs.google.com/spreadsheets/d/1xdbURu2RKVeszYYyVRZVPlZU_44SGpA_2NeHu8VYLZc/edit?gid=0#gid=0), which was refined in a meeting with Robyn on 7/26 and put into a [markdown file on GH ](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/data-collection-evaluation-plan.md)by @jonathanjnelson during the week of 7/29.
