### ISSUE TITLE
Caregiver program application: Make it possible to turn off application access as needed

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8853]
# User story

As a caregiver program stakeholder, I need to be able to have the online 10-10CG application form and related button on the Program of Comprehensive Assistance for Family Caregivers "turned on/off" to: a) support a "dark release" of the form, and b) allow flexibility after full release.

# Details 

We need to work out a way to address the need to be able to quickly "turn off" the application and related functionality. This could potentially be a feature toggle + content changes in Drupal.

**Comment by stephorkandatx** [comment]
"Dark Release" planned for May 29th

**Comment by stephorkandatx** [comment]
We think we may be able to use Flipper to control access to the form + the specific content, but need to investigate to confirm. If that is the case, this would be a minor tech effort + Content to set up what should display (copy-wise) in the two experiences.

**Comment by stephorkandatx** [comment]
@ncksllvn and @kelsonic can you connect to talk about the logistics of the flipper, and if it can be used to turn on/off and throttle a block of content & a form?

We need to confirm if the team intends to throttle the % of users via unauth'd experience,  or auth'd. We don't believe we can throttle % for an unauth'd experience but are not sure. Would need to confirm their expectations and what is feasible

**Comment by ncksllvn** [comment]
Ohh I like the term "dark release." We can call this process the "Shadow Launch".

So this sounds like about the same thing BAM1 is going through with the HLR Wizard + HLR form. I had a sync with them today and offered some guidance that I think applies here too. Basically, it goes -

1. Identify the chunk of content on the tool landing page that will need to be changed with the form's rollout
1. A new feature is created in [Flipper](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/) named after this product
1. A FE engineer creates a React Widget with the following behavior -
    - The React Widget is hooked up to Flipper so it has access to the state of a feature (on or off)
    - If the Flipper feature is indicated as __off__, the widget should render the chunk of content that does not reference the new form
    - If the Flipper feature is indicated as __on__, the widget should render the new chunk of content that does reference the new forms (a wizard or CTA widget)
    - This could should be __merged to master__, with the Flipper feature set to off in production
1. The FE engineer tells a Drupal writer the "widget-type" for the React widget they built
1. A Drupal editors find the tool landing page, deletes the chunk of content that changes with the product launch, and replaces it with a React Widget of the widget type referenced above

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @ncksllvn! Your work on the shadow launch is much appreciated :) 

Question for you in terms of amount of keep this as simple as possible. Does it matter how much content is in the chunk that becomes a React widget? 

So, for example, would we be able to do this with a larger chunk of content like the one in the screenshot below that we want to display differently depending on whether the online application is of/off?

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/a141290a-9bf2-4d02-8cd0-df57476af4cb)

Or, would we be better off working with the copy to make the majority of it the same and just have, say, one line and the button change depending on whether it's on/off?

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/326b5292-4a8f-47fe-ab40-4f5668ed8147)

I think we can make either work from a content perspective with minor tweaking, so I'd like to go with what's simpler from an engineering perspective. 

Thanks!

**Comment by ncksllvn** [comment]
As long as the content itself is "contained" - as in, a single chunk on the page - then it should be totally fine no matter how large the content chunk is. If the affected content is spread out as just hyperlinks throughout the page in different places, we probably wouldn't be able to use Flipper, at least not easily. That kind of content change would probably have to wait for the Flipper feature toggle to always be on.

**Comment by DanielleThierryUSDSVA** [comment]
oh, that's great - thank you, @ncksllvn! We can definitely keep all the content in one chunk; that's no problem at all.

**Comment by stephorkandatx** [comment]
Notes from backlog grooming - We need to confirm the page & the chunk that contains this CTA. Should it affect the content on the CTA the same way it affects the form? Or only turn off the CTA?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx @ncksllvn @kelsonic. Thanks again for your partnership on this!

Here's the page where it lives currently: https://www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/

As part of this work, it's going to be moving to a new home with this url: 
va.gov/family-member-benefits/comprehensive-assistance-for-family-caregiver/ 

And here's the chunk of copy that will be affected. This is what it looks like in current state (and this is what the "off" state will continue to look like):

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/658e522e-713e-497a-8d81-c5c7fe1fa554)

This is a mock up (not yet approved) of what it will likely look like in the "on" state with cta:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/820223fa-108c-45ad-8e53-afcf79124d5c)

**Comment by ncksllvn** [comment]
@DanielleThierryUSDSVA Can you paste the copy of the "on" state?

**Comment by ncksllvn** [comment]
Or actually, if you can link me to the draft in Drupal, that would be even better

**Comment by ncksllvn** [comment]
Nevermind, I just wrote it by hand. 

@DanielleThierryUSDSVA I have some screenshots in this PR - https://github.com/department-of-veterans-affairs/vets-website/pull/12801.

Once merged, in Drupal, you should be able to add a widget with type `caregiver-content-toggle` to see it working.

**Comment by ncksllvn** [comment]
This widget will be ready after today's deployment. Similar to the wizard widgets like on `/education/how-to-apply/`, in Drupal, you'll just create a new React widget with the name/type `caregiver-content-toggle`. It should work in preview. 

You should notice the content will flicker in really quickly, because it has to check the state of the feature flag before rendering. That flicker will be the confirmation that it's working okay. If it looks okay, we can actually go ahead and publish the updated caregivers page and it won't have any affect until the feature flag is enabled.

I did _not_ hook up the feature flag into the Caregivers form though, meaning a user could still get there by directly navigating to the form's URL. Do we need to do that too?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ncksllvn. Great question about the feature flag for the form. @ala-yna, please see above. Could you please let us know if we need to do that as well, or if your team is handling that? Thank you!

**Comment by ala-yna** [comment]
Hi @ncksllvn  - Yes, when the toggle is off (CTA hidden), the form URL should also be unavailable. I'll tag @LinnJS in case he has any thoughts.

**Comment by DanielleThierryUSDSVA** [comment]
As a follow up, @ala-yna and I synced on timing. We don't need this in place for tomorrow, but should have in place by next sprint. We also just want to make sure that we address any risks w/ the feature because it can't be turned on until everything is ready on the backend (likely around July 30th). @ncksllvn @stephorkandatx let @ala-yna and I know if you'd like to talk through anything.

**Comment by LinnJS** [comment]
Everything looks and sounds good! One question though, so along with the content flip containing the CTA button which links to the `1010-CG` form, we should flip the actually application off too right? If yes to this question, I have a custom "404" page that I can flip on once this flip is implemented. This way I could just reuse the same flip for the content so its all congruent.

This way people cant just type in a URL, and get around the CTA link somehow. 

If you want to coordinate this with me after this ticket is completed let me know, or if this ticket includes that work I can pass over the designs or something @ncksllvn.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @LinnJS! Yes, application should flip to off along with the content w/ CTA button. A custom "404" page is great. Could we take a look at that just from a content perspective when you have a moment? Will let @ncksllvn speak to flipping on the URL at form level question. Thanks again!

**Comment by ncksllvn** [comment]
I implemented it into the app too, https://github.com/department-of-veterans-affairs/vets-website/pull/12855.

If the feature flag is disabled for the user and they navigate directly to the Caregiver form URL, then they're just redirected to the homepage. We can change this behavior obviously.

@LinnJS please review when you have time

**Comment by ncksllvn** [comment]
Merged! Caregivers team should be all set with Flipper now.

This means two things -

1. In your app, you can remove the environment-based feature flag
1. In Drupal prod, we can set up the new widget, confirm it looks okay, then publish it

Then, make sure you have access to Flipper UI in dev/staging/prod. You can test the flag works okay by flipping it to true in dev/staging.
