### ISSUE TITLE
[Data] 10-10EZR: What % of EZRs have attached docs

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#88548]
**Success: We know what percentage of EZR have attached docs since we launched attach docs on June 20**

**Comment by luis-simauchi** [comment]
going to modify the timeframe here, we don't see attachment create data come in till june 27th

**Comment by luis-simauchi** [comment]
going to add only count of successful attachment create requests here (i.e. 200 status code calls)

**Comment by luis-simauchi** [comment]
count of successful calls for successful attachment create requests during the timeframe: 

timeframe  - Jun 27, 12:00 am – Jul 22, 11:00 am

count - 1721

**Comment by luis-simauchi** [comment]
<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODc2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1085008b7b97c157ef0c9e2fb26ae5cc7a0c64b4/Capture2.PNG" alt="Capture2.PNG" />
query in metric explorer
