### ISSUE TITLE
Update form detail landing page wireframes

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#8854]
# Update form detail landing page wireframes

The mockups for the basic/generic and the custom form detail landing pages need to be updated to reflect the latest iteration in the forms search as well as changed content fields from the Drupal content modeling work. 

__Current version is v.7:__
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-form-master-detail-LP-patterns-mockups-v7.pdf 

__Tasks:__
~[ ] Update wireframe with for basic/generic form detail landing page~
~[ ] Update wireframe for custom form detail landing page~
~[ ] Update wireframe with consolidated fields for basic and custom detail pages, with call outs what will appear only when customized fields are filled out~
~[ ] Upload PNGs and PDFs of the design files here:  https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files~

__Wireframe updates needed:__
~[ ] Add a new field "Form last updated:"~
~[ ] Update the custom helpful links ~with correct component styling~ and updated section header "Helpful links related to VA Form XXXX"~
~[ ] Update standard helpful links version with correct links and section header "Helpful links"~
~[ ] Update ~(or remove)~ FPO breadcrumb~
~[ ] Update the form title header under the Related forms and instructions - to match copydeck styling~
~[ ] Update related to values to show what it would look like when multiple benefits apply. (Alphabetical, comma separated, "benefits" added at the very end: "Burials and memorials, Family member, Pension benefits"~

FYSA @stephorkandatx 

Will reach out to you @artsymartha68

**Comment by jenniferlee-dsva** [comment]
@artsymartha68 - here is an updated Word doc with genericized content for the form detail content fields. Highlighted the fields that are new or different from your v.7. 

The helpful links component is what you are already using - so no need to change that. It's called the "Related Links" component in Drupal and it uses an H3 that can't be changed. 

[Form-detail-page-content-fields-050820](https://app.zenhub.com/files/133843125/b33272a1-72d1-4a48-a043-fc0944ecebb8/download)

**Comment by artsymartha68** [comment]
PDF and PNG with changes per your Word doc (thanks for making it easy!) and our discussion, @jenniferlee-dsva  I have uploaded them here as well: 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files

![Generic-form-page-with-May-2020-updates](https://user-images.githubusercontent.com/47792423/81527795-3461fa80-9329-11ea-80b5-fc1dc52f0a36.png)

[Generic-form-page-with-May-2020-updates.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4607716/Generic-form-page-with-May-2020-updates.pdf)

**Comment by stephorkandatx** [comment]
Thank you @artsymartha68 ! @jenniferlee-dsva when you've reviewed please confirm here

**Comment by jenniferlee-dsva** [comment]
LGTM - thanks for the speedy turnaround @artsymartha68

**Comment by stephorkandatx** [comment]
Closing during grooming
