### ISSUE TITLE
[Congressional] V11963039 - Exwife illegally accessed medical records through VA.gov (Cong. Griffith) Due 8/9/24

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#88570]
## Issue Description
The veteran is stating that his ex-wife has been accessing his MHV account without his permission . Veteran mentioned that she went through ID.me (she is identified as Self) to access his health records and is asking if we can provided information/data showing what was downloaded from December 2022 and all through 2023.
Veteran changed MHV password, password hint answers and updated email. Veteran also spoke with ID.me and got account deleted. See MHV Incident Report document in folder for more information.
https://dsva.slack.com/archives/C02BS78NYRM/p1721162524075679?thread_ts=1721161548.382069&cid=C02BS78NYRM

---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
7/23 - Sent a follow up email to Susan inquiring about a status update on issue and if any additional details were needed for her review.
Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
8/22/24:  Followed up to see how I can obtain a copy of what was provided to the Veteran as not to provide contradicting information.

**Comment by Kimberley2023-CSM** [comment]
8/23:  Received details from Theresa H. Provided those details and attachment provided to Veteran via email.  Also included info for our CSP to ensure highest level of sign in security is utilized.  Advised of additional fraud resources.  

Awaiting response from Veteran.

**Comment by Kimberley2023-CSM** [comment]
8/26 - Sent another email ensuring the Veteran has received the needed information.  2nd attempt. 
Awaiting user response.

**Comment by Kimberley2023-CSM** [comment]
Vicki Caruso
  Tuesday at 3:51 PM
Complete: Case closed.
