### ISSUE TITLE
Submit Education Pages Updates to SMEs for Review

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8857]
Tracking task to submit the education rates work (part of Epic #8591) to the appropriate SMEs
So that
We can ensure they are able to review proposed changes, provide feedback and the feedback is incorporated.

**Task**
When the Education Rates tickets are completed internally & reviewed by Danielle:
- [ ] Package with the Education pages and send to SMEs for review (all Education pages to go as 1 package) (Anne, Randi)

**Comment by stephorkandatx** [comment]
I will set up Dependencies to the tickets asap. 
This ticket was created as a result of our discussion during sprint planning, as we discussed separating the submission to SMEs + the updates & publishing of changes from the rest of the work.

**Comment by AnneHurley** [comment]
@RLHecht and @DanielleThierryUSDSVA  - Because the SMEs didn't see at least some of these pages previously, do you think we need to create copydecks for each page? I'm thinking we should. And if so, this ticket will be more than a 1, because of the time to turn the pages into PDFs and attach with intros/explainers.

**Comment by DanielleThierryUSDSVA** [comment]
Good question, @AnneHurley. I would recommend that we use our rewriting SME review template for these. Here's an example in pdf and word format. Thanks!

[Brand Consolidation Content Rewriting_Active-Duty Service Members and VA Health Care_6.24.19.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4612636/Brand.Consolidation.Content.Rewriting_Active-Duty.Service.Members.and.VA.Health.Care_6.24.19.pdf)

[Brand Consolidation Content Rewriting_Active-duty service members and VA health care_6.24.19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4612638/Brand.Consolidation.Content.Rewriting_Active-duty.service.members.and.VA.health.care_6.24.19.docx)

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA - Thanks these look great. And it sounds like we are then OK to send the preview links to each page in Drupal/prod, rather than create entire PDFs of each page? We will still need these docs to explain/set up each page and its changes of course.

**Comment by DanielleThierryUSDSVA** [comment]
I think we're okay continuing to do it this way, though I'm also totally open to including pdfs of the full pages. Yes, agree, we'll still need the setup either way.

**Comment by RLHecht** [comment]
Super old ticket. Closing as these pages are live!
