### ISSUE TITLE
Set up Datadog log for appointment created date

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88580]
We are trying to determine if V0 appointments are still getting displayed for some users. We want to to log the created date for appointments to determine if there were any created around Dec 2022 (when we migrated from v0 to v2)

AC:
[ ] - Log created date for appointments on VA.gov.

**Comment by ldelacosta** [comment]
@simiadebowale - can you validate this when you have a chance and close it out if there are no issues.

**Comment by simiadebowale** [comment]
Confirmed that we are seeing the logs in DataDog.
