### ISSUE TITLE
Look into new data in debt-letters/get endpoint

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#88596]
We got word via email from Daniel Wildman that the debt-letters/get endpoint is bringing back fiscal transaction data. We need to go out to production and run the request to see what the data looks like. Once we have an idea, we'll likely have to update mock data to return this new data contract so FE and BE devs can work with it.

**Comment by HeatherRienks** [comment]
Closing this ticket as we have a duplicate ticket created for this effort (#87364).
