### ISSUE TITLE
Analytics: Create custom metric-based BTSSS widget in Datadog

### ISSUE THREAD

**Issue by katbrinkley** [department-of-veterans-affairs/va.gov-team#88604]
### User story

As a Cartographers team member, I want to create a widget with custom metrics to use to compare the usage of supply reordering and BTSSS links between mobile and desktop devices.

### Notes
- Precedes [this ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/87407) - we realized we didn't refine this properly and we need to create the widget for BTSSS before segmenting users by mobile and desktop before we can do segmenting.
- _WES: you don't have to create a widget to pull a number, do you? e.g. you could create a funnel or maybe get raw numbers. OR, can we use GA?_

Possible tasks:
- Create custom metric queries for querying BTSSS for the Datadog dashboard
- Create a widget

## Acceptance criteria
- A widget exists on the MHS integration DD dashboard based on custom metrics
- The widget is capable of being filtered/segmented based on mobile and desktop users - I believe this is done in the Explorer in DD

**Comment by fmccaf1** [comment]
Decided not to pursue datadog at this point
