### ISSUE TITLE
Report July transition KPIs (on July 30/31)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#88605]
### User story

As a Cartography team member, I want on the last day of July to grab all July stats for the transition KPI reporting slide(s) that Robyn shares monthly, so that we capture it before it's lost.

### Notes
- See Robyn's comment below for guidance on what numbers we need to gather. She said she would provide a template to capture the numbers by 7/26.
- June report available as a PDF [in slack](https://dsva.slack.com/archives/C04DRS3L9NV/p1720646815248189) – can ask Robyn for the powerpoint version if needed

Possible tasks:
- Work with Robyn on what numbers are needed
- Capture the numbers on July 31

## Acceptance criteria

- Captured stats for full month of July
- Captured a screenshot of the "Analytics summary" report in DD
- Discussed with Robyn that she has everything she needs

**Comment by rbsingleton** [comment]
Data reporting to include from landing page data: 
- Medallia quant stats from both intercept survey & feedback survey -> all questions; "how would you rate your experience" question most important for CSAT reporting but Trust item also high profile
- Synthesis of qualitative feedback - nature of which will depend on tags
- # of users who viewed landing page
- # of page views
- WOULD REALLY LIKE TO HAVE (more than "nice to have", but acknowledge that we haven't figured out how best to do this): # of users who were first time page viewers; # of users who were return page viewers. 
- Top 10 clicks from landing page
- Conversion rate (believe this is defined as proportion of users who did something -> went somewhere, clicked on something)
- Clicks on "take me back"
- Clicks on secondary nav

**Comment by fmccaf1** [comment]
Not yet @LynneJohnson224. I'm working on clarifying another weird discrepancy. Here are details:

## Looking at dates Jul 25-Aug 1

### Clicks on secondary nav - records from MHV home
- 3281 in datadog
- 8945 in GA (active users)
- 9813 in GA (event count)
^ so, big difference here. I looked at other secondary nav clicks to understand breadth of problem. 

### Clicks on secondary nav - appointments from MHV home
- 2566 in datadog
- 4623 in GA (active users)
- 4989 in GA (event count)

### Clicks on secondary nav - messages from MHV home
- 2706 in datadog
- 5983 in GA (active users)
- 6990 in GA (event count)

### Clicks on secondary nav - medications from MHV home
- 1999 in datadog
- 3858 in GA (active users)
- 4209 in GA (event count)

**Comment by fmccaf1** [comment]
Given conversation during 16th minute today, I will not continue to try to figure out the discrepancy above. Renamed our datadog dashboard to indicate data there is not reliable.
