### ISSUE TITLE
Update transformer to pull patient comments from the new patientComments field [VA Requests]

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88609]
Update transformer to pull patient comments from the new patientComments field [VA Requests]
```

patientComments: "This is a sample patient comment"

```

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
- [ ] - cleanup logic that pulls comments.
- [ ] - tests updated

**Comment by vbahinwillit** [comment]
During code review, it was determined that additional changes are needed on the BE (see PR). Issue should be migrated to next sprint.

**Comment by simiadebowale** [comment]
Validated in staging
