### ISSUE TITLE
Discuss & Determine EKS Testing Approach

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#88616]
# Description
Using the `vets-api` testing in EKS next cluster design document as well as the 4 option document to guide the discussion, create a consensus between the Platform Product Team, Platform Reliability Team, and Platform Leadership for the detailed solution that verifies the functionality of `vets-api` running in an EKS Next cluster.

# Acceptance Criteria
- [x] Platform leadership and PRT agree to the specified plan
- [x] Tickets added to Reliability Team board

**Comment by pjhill** [comment]
Created a design document to describe the 5th and hopefully final option for running tests in EKS against `vets-api` endpoints.
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3307569516/Helm+Tests+for+Vets-api

**Comment by pjhill** [comment]
Minimal comments have been added to the design document. The only remaining discussion item appears to be whether we use GHA or post-install hooks to fire off the testing. Still working through resolving this issue with stakeholders.

**Comment by pjhill** [comment]
All questions / discussion on the design document have been resolved with the exception of the triggering event. We have a meeting scheduled for Thursday to finally resolve that issue; however, the tickets are already created. We will just need to add the last specification to the ticket complete that work -- https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/89541

**Comment by JoeTice** [comment]
SPRINT 6 UPDATE: DONE - This ticket was completed on 7/31, but didn't get marked as closed
