### ISSUE TITLE
Remove any reference of va_online_scheduling_clinic_location feature toggle

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#88615]
## Description
Feature toggle va_online_scheduling_clinic_location appears to be a duplicate and is not in use.  Remove this feature toggle to reduce the number of VAOS feature toggles in flipper.

---

## Acceptance Criteria
- [ ] Remove any references of the feature toggle va_online_scheduling_clinic_location
- [ ] Delete the feature toggle va_online_scheduling_clinic_location in flipper staging and flipper production
- [ ] Changes have been updated in vets-website and vets-api
- [ ] Documentation is updated

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JunTaoLuo** [comment]
All changes have been merged and deployed. I removed the flag in all non-production environments and VFS Support has removed it from the production environment (see [discussion on Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1721753390798039)). Ready for validation.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @JRRoof
