### ISSUE TITLE
2024 Sprint 6 FOIA monitoring devops work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88612]
As the Product Platform team, 
We want to monitor the delivery of the FOIA request, as attached, 
So that the request is delivered by the Platform Product team.

This ticket is to serve as follow-up work. Original ticket is [87838](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87838).

The work done in Sprint 5 was the response to a FOIA request from Platform Support [here](https://dsva.slack.com/archives/CBU0KDSB1/p1720470475018979). The four files requested were: 

**List of archived tables:**
1. InsitutionsArchive
2. InstitutionProgramsArchive
3. VersionedSchoolCertifyingOfficialsArchive
4. ZipcodeRatesArchive

The files were all delivered via TK method to Elaine Suyat (contact: elaine.suyat@va.gov)) as of 11:00am eastern, July 17, 2024. The team is awaiting response from Elaine Suyat, which will validate the delivery of the requested tables. This ticket exists so that any additional work done by the Platform Product DevOps team may be tracked during Sprint 6, beginning 7/18/2024. 

Tasks:
Monitor the delivery post-7/17/2024 for completeness. Deadline is TBC

A/C:
Approval from Elaine Suyat

**Comment by alyssagallion** [comment]
[Ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/88943) to document process for future FOIA tasks that come to support. Will work with Jennifer's team in that ticket to get to a process and document it. Thanks!

_Note: Removing our label from this ticket._

**Comment by flooose** [comment]
Files are uploaded and shared via MS OneDrive
![Screenshot 2024-07-30 at 8 47 49 AM](https://github.com/user-attachments/assets/ac242056-70db-4ba0-9e5d-1db8151b952d)
![Screenshot 2024-07-30 at 8 44 33 AM](https://github.com/user-attachments/assets/77de88bc-22ea-4c6e-bbdc-58764caa956d)

**Comment by jennb33** [comment]
7/30 update - per @flooose:  attached screenshots of the delivered data, there's been only silence from them since last Thursday (7/25), and the issues with the FTP server have not been resolved, although there is a YourIT ticket for it open still.
Closing this ticket.
