### ISSUE TITLE
Create script to populate Tugboat instances with Digital Form test data

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#88658]
When using Tugboat, the database gets blown away every time we rebuild the environment. In order to persist non-prod data across deployments, we need to create a script that can be run manually after Tugboat deploys.

See [Slack discussion](https://dsva.slack.com/archives/CT4GZBM8F/p1721227364975279?thread_ts=1720535346.916149&cid=CT4GZBM8F) for more details and [VACMS-17969](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18271) for an example of how this has been done in the past. How much we want to recreate this work vs glom onto it is an open question.

Notes:

- The script will be run on the Tugboat PHP terminal.
- Content generation scripts live at https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/scripts/content
- To run the script:
    -  Log into the Tugboat dashboard for the new deployment.
    -  Click "Terminal" in the "php" row of the "Services" section
    -  `drush scr scripts/content/PATH-TO-SCRIPT/SCRIPT-FILENAME.php`
    -  In the browser, go to `/admin/content/` and verify the Digital Forms have been created.

**Comment by Karak888** [comment]
will see how review instances are working but will need to happen in future.
