### ISSUE TITLE
Design | MHV&DS Logon Retirement | Revisit Initial Messaging Designs with Updated Dates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#88653]
## Background
Based on an email sent on 7/17/2024 there are new dates for the credential retirement. We'll need to revisit and update the designs set out here:
- #73358 

>[...]
>In 2025, VA will transition from four online sign-in account options (Login.gov, ID.me, My HealtheVet, and DS Logon) to two sign-in account options: Login.gov and ID.me accounts. Veterans will be able to use either of these two options to sign in to VA.gov, VA mobile applications, or other VA online services.
>
>Veterans and other beneficiaries will no longer be able to use usernames and passwords for My HealtheVet after Jan. 31, 2025, or DS Logon after Sept. 30, 2025. After these deadlines, Veterans who have not yet transitioned will still be able to access their data and resume managing their benefits and services online once they have created their new account.
>[...]

[Designs can be found here](https://www.figma.com/design/OmY3qqcBnK043nnnUvlsjh/%2373358---Auth-Exp-Credential-Retirement-Phase-1?node-id=1-2509) > we'll need to revise LO1 and LO3  
## Acceptance Criteria 
- [ ] the designs are updated with the revised dates
- [ ] CAIA has approved the revisions we've made 
- [ ] We created a FE ticket to make the revisions (link the FE ticket here so we can trace back)

**Comment by mtcA6** [comment]
@twoangstroms on refinement you had questions about the AC for creating a new ticket. 

you can create new tickets on any GH page by selecting the `new ticket` button in the top right of any GH ticket page
![image](https://github.com/user-attachments/assets/b2d24a3b-a2aa-48bc-81ad-f4e4a83456f7)

search in the screen that pops up for Profile and create a new profile ticket. 
![image](https://github.com/user-attachments/assets/a5be9bff-0658-4ca3-99b3-45f8f8167716)

In the new ticket we use 3 sections Background, Tasks, Acceptance Criteria 

As for questions around how to work with [CAIA you should revie this platform page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request). You can attend CAIA office hours they have details on how to do that and they [publish messages like this on the days when they have content office hours](https://dsva.slack.com/archives/C01K37HRUAH/p1721666424757339). Since they have a slack channel #sitewide-content-accessibility-ia you could check in there or chat w/Matt about how to work this ticket. 

cc: @ACParker89

**Comment by twoangstroms** [comment]
Should be able to complete after clarification in CAIA office hours before next sprint

**Comment by twoangstroms** [comment]
Update: CAIA office hours recommended contacting someone who is OOO today, so this ticket will hold over to next sprint.

**Comment by mtcA6** [comment]
@twoangstroms could you take a stab at creating the follow on ticket to hand this off to the FE?
