### ISSUE TITLE
Flipper UI access for [Wayne Weibel]

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#88651]
### Your Name

Wayne Weibel

### Your GitHub handle (Flipper UI access is managed through GitHub)

@wayne-weibel

### Team, Role, and Company of the target individual

Pension, Engineering Lead, Ad Hoc

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need production access to perform necessary actions for rollout of features in pension 527ez, income and assets 0969, and pension ITF.  Currently, there is no backup person with access to do so.

**Comment by mjknight50** [comment]
Just to add to this, I really need Wayne to have production flipper access as a back-up for me on projects.

**Comment by bdech** [comment]
confirmed in Atlas
E-QIP [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77802)

**Comment by bdech** [comment]
Wayne has already has access to [lower environments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69231)

**Comment by bdech** [comment]
@wayne-weibel You've been granted access to `Production`.
