### ISSUE TITLE
Cancel Pending Appointment (Part 1) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#88661]
## Summary
There is an error after the user cancels an appointment requests and clicks on the `Back to pending appointments`. 

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**userID:** judy.morrison@id.me 

1. Go to: www.staging.va.gov
2. Login
3. Go to Pending list
4. Click on a request
5. Cancel the request
6. Click on 'Back to pending appointments`

### Actual Result

https://github.com/user-attachments/assets/989ae3da-0b59-4df5-ba2f-fa2fd01dca42

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by ldelacosta** [comment]
Reference collab cycle ticket: [88446](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/88446)

**Comment by vbahinwillit** [comment]
@ldelacosta - I just successfully canceled 2 appointment requests. Can you retry? Thanks.

**Comment by ryanshaw** [comment]
@ldelacosta I am not able to reproduce this locally or on staging with the steps above. Here's a screen recording:

https://github.com/user-attachments/assets/e61a782a-aebd-47e4-b95c-4c2ffc975c43

**Comment by ldelacosta** [comment]
No additional issues to report. Closing out the ticket.
