### ISSUE TITLE
Update 10-10CG Form Schema with latest changes

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#8867]
- Remove suffix form all names in 10-10CG
- Add "Unknown" as a gender for all persons on 10-10CG
- Remove country from all addresses in 10-10CG
- All enrollemnts are now required for 10-10CG
- Update secondaryCaregiver namespace to new format: secondaryCaregiverOne, secondaryCaregiverTwo

Relates to department-of-veterans-affairs/va.gov-team#7734, department-of-veterans-affairs/va.gov-team#8091

**Comment by kevinmirc** [comment]
Implemented here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8867
