### ISSUE TITLE
Update Gross Monthly Income Multiple Response Pattern

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#88676]
### Summary 
Implement the Multiple Page Response pattern on the Pension Benefits form (21P-527EZ) for gross monthly input. 

### Description
Replace the single-page multiple response gross monthly input pages with the [Array Builder Pattern (Multiple Page list & loop)](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) pattern and [Design](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) reference

### Acceptance Criteria
- Implement the multi-page response pattern for entering gross monthly input details in the 'Financial information' section of the 21P-527EZ form
- Ensure the multi-page response pattern is only displayed when the 'pension_multiple_page_responses' is enabled
- Ensure the single-page response pattern is not displayed when the 'pension_multiple_page_responses' is enabled

### Definition of Done
- [ ] Existing unit and E2E tests pass
- [ ] Items are added, edited and deleted via the multiple page list loop pattern
- [ ] Verify that the UI matches the design system designs
- [ ] Verify the layout on desktop and mobile viewports
- [ ] Verify that the form data is saved to the api and redux store

**Comment by gmaciolek** [comment]
@ToddWebDev I'm still seeing the single-page response pattern on staging for gross monthly income.

![Image](https://github.com/user-attachments/assets/c199be06-2452-45c8-b4c2-643bfaed9a1d)

**Comment by ToddWebDev** [comment]
@gmaciolek This work is still in code review. Hopefully it's approved soon and then it will be added to stage for review. I will let you know when it is on stage.

**Comment by ToddWebDev** [comment]
@gmaciolek This work is now on stage for design review

**Comment by aplatt-coforma** [comment]
Eng work is complete and changes are on staging environment for now. 
Will pick up multiple page list & loop work once it becomes prioritized with HCD.
