### ISSUE TITLE
Cancel Pending Appointment (Part 2) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#88670]
## Summary
Reference the first bug ticket [#88661](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88661)

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** judy.morrison@id.me 

1. Go to: www.staging.va.gov
2. Login
3. Click on a pending request
4. Error appears on the screen (note: the request has not been canceled) 

### Actual Result

https://github.com/user-attachments/assets/ad193d10-700f-47df-80c7-42e59db121ec

### Desired Result
No error message should appear. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by ldelacosta** [comment]
Reference collab cycle ticket: [88446](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/88446)

**Comment by vbahinwillit** [comment]
Appears to be for CC appointment requests. Adding response from server.
```
{"errors":"Access token has expired"}
```

```
{
    "errors": [
        {
            "title": "Bad Gateway",
            "detail": "Received an an invalid response from the upstream server",
            "code": "VAOS_502",
            "source": {
                "vamfUrl": "https://fwdproxy-staging.vfs.va.gov:4463/vaos/v1/patients/434fce82be04d498f7e7e54f30c0d4c35f61bc4e53610137bcb446723597732a/appointments/6dd7cb5359f54edb9eb0becd33d19118d3e93e266ef7644cf7b9ad2b9ed1262d",
                "vamfBody": "{\"id\":\"640dc8f4-3b61-4ff0-97f3-4d2bf250555a\",\"code\":500,\"errorCode\":7011,\"traceId\":\"66992eee000000003949c33bd1e7ed86\",\"message\":\"failed to cancel appointment\",\"detail\":\"Could not update CC appointment request through the Mobile HSRM Service.\",\"meta\":{\"upstreamErrorSource\":\"mobile-appointment-service\",\"upstreamErrorId\":\"beee3374-26ae-4d38-8def-c38f163ae98a\"}}",
                "vamfStatus": 500
            },
            "status": "502"
        }
    ]
}
```

**Comment by ryanshaw** [comment]
@ldelacosta I was unable to reproduce this locally or on staging, here's a screen recording:


https://github.com/user-attachments/assets/accae019-904f-4725-a057-a74f6ccaedf7

**Comment by ryanshaw** [comment]
I was able to reproduce this (as @vbahinwillit mentioned above) with CC requests. The backend is returning this response:

```json

{
    "errors": [
        {
            "title": "Bad Gateway",
            "detail": "Received an an invalid response from the upstream server",
            "code": "VAOS_502",
            "source": {
                "vamfUrl": "https://fwdproxy-staging.vfs.va.gov:4463/vpg/v1/patients/434fce82be04d498f7e7e54f30c0d4c35f61bc4e53610137bcb446723597732a/appointments/f3b7c26a0b7fdc3d01e19f8a06e9c521780696525c21277dc852fd38ed0cda59",
                "vamfBody": "{\"code\":500,\"status\":500,\"message\":\"An error occurred (ID: 39a98658-0085-4e0b-b52f-3b3162cf5987)\",\"id\":\"39a98658-0085-4e0b-b52f-3b3162cf5987\",\"traceId\":\"66b0f45f000000000a204e3ba6f957a1\"}",
                "vamfStatus": 500
            },
            "status": "502"
        }
    ]
}

```

**Comment by ryanshaw** [comment]
@ldelacosta I was unable to reproduce this on staging using `[judy.morrison@id.me](mailto:judy.morrison@id.me)` so reassigning and moving to validate. I believe there were intermittent backend service issues.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
