### ISSUE TITLE
Design Intent - IA Feedback - Appointments Team, Appointments, Oracle Health - Direct Schedule and Request for an Appointment

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#88688]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for coming through Collab Cycle! Great to see y'all twice this week 😄 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Consider

- [x] **Placement of "Do you have an urgent medical need?" alert** Currently this alert shows toward the end of the form flow, adjacent to the free-text field where Veterans describe their symptoms. I think it's smart to include this alert in this location. What about earlier in the flow as well? (Y'all indicated on the call that you're working on this! Just logging here for posterity.)

- [x] **Select a location page - "Current location" filter** I like that current location is included on the locations dropdown, in case the Veteran is not home and needs medical care. Will it show facilities even if the Veteran is not already registered there? If not, should this filter be included? (Again, the team indicated on the call that you're working on this!)

- [x] **Visibility of confirm button on review and confirm page** Once Veterans reach the review and confirm page, there's a final step - scrolling down and selecting the "Confirm this appointment" button. This is similar to the existing review page pattern, with the big difference being that it's using the new edit links instead of accordions to display each form section, and it has a new page title and submit button text. I heard a research readout recently that reported that some Veterans thought the form was submitted when they got to the review page, rather than knowing that they needed to submit the form. Will users still know that they need to scroll down and select "confirm" to submit the form and schedule their appointment? This might be a question for user testing, if you have not already tested this.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by outerpress** [comment]
@erinrwhite re: the review page, the Appts tool has been using the pattern with the edit links for about 4-5 years, so it's pretty well tested on our end :)  So I'm going to check off that item for now, but if other research calls this out as an issue we'll def adjust to meet the common pattern!

**Comment by outerpress** [comment]
@erinrwhite (sorry, working through these backwards) currently the facilities list only shows where a Veteran is registered. 

We looked at a concept for providing a path to registration (see workflow below) but we're hoping for a way to let Veterans enroll online before we get to this step, since asking them to call to register/schedule is always frustrating. I think there's a team working on this rn but I can't remember which. (FYI @kristenmcconnell for awareness). 

<img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFAyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81c3c30f77a50e32f8052d9e6d71193ae49ec911/image.png" alt="image.png" />

So we decided that was out of scope for the OH Scheduling work, but we have the options documented.

We're also still working on adding the option sort by recent locations. We want to see how that plays out before adding more complexity - [Follow the dotted lines to and from this page to see the complexity we're dealing with](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1048-3326&t=oLDBQFifSmp1291U-4). 

Given all that I'll check this off for now, but please reopen if I missed anything.

**Comment by outerpress** [comment]
Re: urgent care alert  - yes, we're testing this now! We're treating it as a separate project from the OH scheduling work, but [here's](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2937-42152) what @melissa-lefevre is looking at:

- Show the urgent care alert at the beginning of the flow, [on its own page](https://www.figma.com/design/1dSk9a4KDxqxKzgRDmXyPu/Prototype%3A-Scheduling-improvements--%7C-Appointments-FE?node-id=4374-51549&t=9FiAgNnF2mgidVjb-4), with the option to dismiss
- Offer an option to select "I need immediate care" in the type of care page, which leads to [a page](https://www.figma.com/design/1dSk9a4KDxqxKzgRDmXyPu/Prototype%3A-Scheduling-improvements--%7C-Appointments-FE?node-id=4115-16987&t=9FiAgNnF2mgidVjb-4) that provides info on 
- Use AI to analyze the language they enter in the free text box and, if anything problematic is flagged, [show the alert page](https://www.figma.com/design/1dSk9a4KDxqxKzgRDmXyPu/Prototype%3A-Scheduling-improvements--%7C-Appointments-FE?node-id=4115-16987&t=9FiAgNnF2mgidVjb-4).

Our next step is to decide if any of these approaches are worth pursuing - if so we'll def be back to collab cycle with them. So checking this off.

**Comment by outerpress** [comment]
I think everything here has been addressed - basically we've been looking at all of these and will be back through collab cycle when we're further along with them, but we're not doing them to support OH scheduling. 

So closing for now, but please do reopen if I missed (or misread) anything! FYI @ldelacosta @melissa-lefevre
