### ISSUE TITLE
Update transformer to pull patient reason for appointment from the new reasonForAppointment field [VA Requests]

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88684]
Update transformer to pull patient reason for appointment from the new reasonForAppointment field [VA Requests]
```

reasonForAppointment: "Routine/Follow-up",

```

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
- [ ] - cleanup logic that pulls comments.
- [ ] - tests updated

**Comment by JunTaoLuo** [comment]
Verified with Judy Morrison in staging: 
<img width="289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00a37bc101040c1da33a6812421bf31e5c2771af/image.png" alt="image.png" />
