### ISSUE TITLE
Update transformer to pull patient reason for appointment from the new reasonForAppointment field [VA Direct Schedule]

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88694]
Update transformer to pull patient reason for appointment from the new reasonForAppointment field [VA Direct Schedule]
```

reasonForAppointment: "Routine/Follow-up",

```

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
[ ] - cleanup logic that pulls reason code.
[ ] - tests updated

**Comment by JunTaoLuo** [comment]
Verified with Judy Morrison in staging:
<img width="319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1182af0cd701eaed3d3ad6a1e383227181fa4202/image.png" alt="image.png" />
