### ISSUE TITLE
Update transformer to pull patient comments from the new patientComments field [VA Direct Schedule]

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88695]
Update transformer to pull patient comments from the new patientComments field [VA Direct Schedule]
```

patientComments: "comments"

```

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
[ ] - cleanup logic that pulls comments.
[ ] - tests updated

**Comment by ldelacosta** [comment]
@simiadebowale - please let me know if we are good to close. Thanks!

**Comment by JunTaoLuo** [comment]
Verified in staging with Judy Morrison's appointment:
<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0UzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--650fb1581a99fada9fe6de4c0a9132f0eefb8ea9/image.png" alt="image.png" />
