### ISSUE TITLE
Contact Center Review for 10-10 Health Enrollment - 10-10EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#88696]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
10-10EZR allows Veterans to update their health care information for VHA

### Launch Date
July 2024

### Version Number
Version 2, no video 

### Product Guide
*Please provide product guide link*
[10-10EZR Health Benefits update form Product guide July-2024 AS RL.docx](https://github.com/user-attachments/files/16275455/10-10EZR.Health.Benefits.update.form.Product.guide.July-2024.AS.RL.docx)

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/10-10EZR%20Form/Product%20Guide 

### Product Video
No video

### Product Video Transcript
No video

**AS Note: I have tagged my colleagues Heather Justice and Emily Brown as I will be out until the middle of next week. Otherwise, I will make changes when I get back. Thank you!**

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The draft looks good. I am sending it to the VEO contact center for their review.

**Comment by starlow00** [comment]
No changes from VEO. I've attached the current copy of the guide. Please use it for future product revisions. Thank you!

[10-10EZR.Health.Benefits.update.form.SRT_08112024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed785370de23eb046d5a688294632fbe3d18ae07/10-10EZR.Health.Benefits.update.form.SRT_08112024.docx)

**Comment by hdjustice** [comment]
Wonderful, thank you @starlow00 !
