### ISSUE TITLE
Update transformer to pull patient preferredDates from the new preferredDates field [VA Requests]

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88698]
Update transformer to pull patient reason for appointment from the new preferredDates field [VA Requests]

```

preferredDates: ['Wed, June 26, 2024 in the morning', 'Wed, June 26, 2024 in the afternoon'],

```

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
- [ ] - cleanup logic that pulls comments.
- [ ] - tests updated

**Comment by vbahinwillit** [comment]
@simiadebowale - Should the dates be returned in a standard format? This way the client can format the date anyway they choose.

**Comment by simiadebowale** [comment]
This ticket has been validated in staging.
