### ISSUE TITLE
[FE] 10-10EZR: Update EZR Expiration Date DUE 7/31/24

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#88697]
As a Veteran, I would like to know that the EZR is not expired so that I don't get worried that I will lose all of my information to an expired form.

- [x] Update form expiration to 7/31/2027
- [x] Test
- [x] Release to prod
- [x] **Success: Expiration on intro page is update to 7/31/27**

**Comment by mkerns1** [comment]
Release Intent Notice
Hello team,
I wanted to inform you that the changes for ticket #88697, which update the expiration date for the EZR from 7/31/24 to 7/31/27, have been successfully demoed to the EZR Team and merged into the main branch in GitHub. These changes are scheduled to be released during tomorrow's 1pm release cycle.
Next Steps:
Monitoring: Please keep an eye on the release process tomorrow and report any issues immediately.
Verification: After the release, 
@allan.to
 and the @1010-ezr-team will ensure the expiration date update is reflected correctly across all relevant parts of the application.
Follow-Up: We will have a brief check-in post-release to discuss any feedback or issues.
