### ISSUE TITLE
Direct Scheduled appointment reasoncode.text - reasonForAppointment

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#88692]
As part of the vets-api code consolidation initiative we need to map the appointment `reason code` from the `reasoncode.text` field to the new reasonForAppointment field that was created for appointment requests. This is for Direct Scheduled appointments.

`reasonForAppointment`: should return a string based on code received:
`ROUTINEVISIT` - reasonForAppointment should return: 'Routine/Follow-up'.
`MEDICALISSUE` - reasonForAppointment should return: 'New medical issue'.
`QUESTIONMEDS` - reasonForAppointment should return: 'Medication concern'.
`OTHER_REASON` - reasonForAppointment should return: 'My reason isn’t listed'.

Related spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/82597

AC:
- [ ] - reason code is mapped to reasonForAppointment
- [ ] - test specs are updates.

**Comment by simiadebowale** [comment]
@JunTaoLuo - not able to validate this in staging. I'm not seeing the reasonForAppointment field for DS appointments

**Comment by JunTaoLuo** [comment]
Uh oh, let's take a closer look at this later today.

**Comment by JunTaoLuo** [comment]
@simiadebowale the PR with the fix has been fully deployed now so it's ready for another round of validation.

**Comment by simiadebowale** [comment]
validated in staging
