### ISSUE TITLE
Improve messaging of Slack notification for vets-website falling back to cached CMS data

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#887]
Currently, when we're compiling the website as part of Jenkins CI, we will fallback to cached CMS content if the website compilation step fails. The idea is that if the latest CMS data produces an error (a feature flag error or more commonly, a broken link) the build can use the CMS data from the last successful build. This is particularly valuable for pull requests, because it prevents other engineers from getting blocked by a CMS issue.

The vets-website build falling back to the cached CMS data means that we can't build off of the latest CMS data, so we can't deploy it. This means that there is an issue with the latest CMS data that others should be aware of. 

We currently post a message to the DSVA #devops-deploys channel announcing this -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/752a466b-0c50-46e1-b116-23d3fe1e5b73)

[link to Slack message](https://dsva.slack.com/archives/C37M86Y8G/p1563908681010300)

However, this message is very minimal, and generally flies under the radar unless you're monitoring that channel closely. We should improve on this by -

1. Post to a dedicated channel 
    - `#cms-content` and `#cms-engineering` 
2. The message should contain `@ here` and should (ideally) contain some useful output about which links are broken
    - This could be an opportunity to make the link-checker "smart" by inferring what could have happened on the content-side based on the errors. For example, `There are 27 broken links to Page 1 - could Page 1 have been unpublished?" That output could then be relayed in the Slack message.
    - We may need to add unique separators around the broken link output so that Jenkins can easily parse it into the Slack message.

**Comment by swirtSJW** [comment]
Is there anything we can do to help move this along?

**Comment by swirtSJW** [comment]
Sorry, just checking in on this again.  Is there anything we can do to support this or help prioritise this?

**Comment by alexpappasoddball** [comment]
@cvalarida Per the global-ux team, they are looking in the #cms-general channel for broken links update.  I know in the description is states to post to #cms-content & #cms-engineering.  @ncksllvn do you have any reason we choose the two channels in the description, any objection to posting to the general channel instead?

**Comment by ncksllvn** [comment]
@alexpappasoddball Nope, #cms-general is better!
