### ISSUE TITLE
0781 Research Closeout

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#88702]
After conducting 0781 research the team will share findings and present to VBA, OCTO, and others.

Task:
- [x] After final readout comments are integrated, upload to [Github page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2024-06%200781%20Research)
- [x] Schedule presentation for Monday Sync
- [ ] Add findings to [Monday Design Sync Presentation Deck](https://docs.google.com/presentation/d/1u0ThZqFbGKTW6m8WHW7WYhQiOiDbXvcKJBTL9311MGs/edit#slide=id.g892adcb623_0_141)
- [x] Completed closeout items on [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)

Acceptance Criteria:
- [x] Research findings are uploaded to Github and shared in disability-design Slack channel
- [ ] Findings are moved to Monday Sync Slide deck
- [x] Presentation with OCTO and our teams is complete
- [x] Checklist items complete

**Comment by juliepedtke** [comment]
FYI - restructured so that readout is included in synthesis ticket since it was easier to track our timeline, and this ticket is for closeout items after the readout.

**Comment by nnicholas7** [comment]
NOTE: Schedule presentation for Monday Sync

Naomi is out this week. I will send her a message on Monday to schedule the design sync.

**Comment by nnicholas7** [comment]
Monday Design Sync has been scheduled for September 30!

**Comment by nnicholas7** [comment]
- The research repo has been updating. I added a link to our Github page within the repo card so folks can find the findings report. Pasting the information into the repo card felt messy.
- Research has been shared with Eillen on MST. We spoke with the Trauma-informed CoP yesterday and plan to prepare a presentation on how we incorporated trauma-informed practices into our work. We are also scheduled to present at the Benefits Portfolio: all hands design sync on Aug 26, Monday Design Sync on Sept 30, and Trauma-informed CoP on Sept 27.

**Comment by nnicholas7** [comment]
A message was sent in the design channel of the recording of the readout, but not of the Github link to all of our documents.
