### ISSUE TITLE
fix mention of `vtk setup` to `vtk socks setup`

### ISSUE THREAD

**Issue by Mitch-A6** [department-of-veterans-affairs/va.gov-team#88705]
### Description
At the end of the `Prerequisites for SOCKS Proxy configuration` section, the Note says 

> After you have completed the `vtk setup` you’ll no longer needed the Personal Access Token.

but `vtk setup` is not a valid command. Presumably this should be `vtk socks setup`?

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-PrerequisitesPrerequisitesforSOCKSProxyconfiguration

### Which type of team are you on? (Platform team, VFS team, or Leadership)
10-10 Health Enrollment team

**Comment by jknipes** [comment]
Hi @Mitch-A6 , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@Mitch-A6 , we are revisiting this ticket. [The page was updated in late August](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-PrerequisitesPrerequisitesforSOCKSProxyconfiguration), would you say the page now addresses this issue?

**Comment by Mitch-A6** [comment]
Mostly - the Note still says
"After you have completed the vtk setup you’ll no longer needed the
Personal Access Token."

Is there any way to be notified when a page changes, or to compare the
current and previous versions?

**Comment by jknipes** [comment]
OK, I'm looking at it with a Platform engineer, and we will update with the correct information.

Noting on this ticket, [relevant Slack thread HERE.](https://dsva.slack.com/archives/CL181NRJQ/p1718121236069469)
