### ISSUE TITLE
Platform Orientation feedback ticket from Service Design team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#88708]
This ticket is for reporting to Governance the state of all materials referenced in the Platform Orientation process. If you have any questions or concerns, please contact Governance team on Slack using the @platform-governance-team-members group on the #platform-team channel. Thank you. 

- [ ] Update title of ticket with your teams name

Feedback:
In addition to the Feature Request link that exists, it would be great to inform incoming team members of the main method for submitting feedback about Platform Services and Products.  Here's a suggested line:
- [ ] Review guidance on [How to Submit Feedback about Platform Products & Services](https://depo-platform-documentation.scrollhelp.site/support/give-feedback-about-platform-products-or-services)

## ALL Platform Teams
- [ ] Review the [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/.github/ISSUE_TEMPLATE/orientation-feedback.md)
- [ ] Review the [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team%2C+platform-tech-team-support&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
- [ ] Verify all links/references are accurate
   - [ ] If a broken link or wrong reference is identified, please include details below:
- [ ] Verify there are no gaps in what new team and team members need to know about Platform
   - [ ] If a gap is identified, please include details below:
- [ ] Make recommendations and/or suggestions for improvements to Platform orientation
   - [ ] If your team has recommendations or suggestions, please include details below:

## Platform Support team
- [ ] Watch the [Platform Support overview video](https://www.youtube.com/watch?v=iwIQU4XepNQ) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Platform Support will rerecord.
     - Ticket number:

## Platform Content team
- [ ] Watch the [VFS Orientation to Platform Website video](https://www.youtube.com/watch?v=yzl6nyLmqkA) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Platform Content will rerecord.
     - Ticket number:

## Service Design team
- [ ] Review guidance on [How to Submit Feedback about Platform Products & Services](https://depo-platform-documentation.scrollhelp.site/support/give-feedback-about-platform-products-or-services)
        
## Design System Team
- [ ] Watch the [Design System/Forms Library Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-DesignSystem/FormsLibraryOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Design System team will rerecord.
     - Ticket number:

## Backend COP
- [ ] Watch the [Backend Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Back-endOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Backend COP will rerecord.
     - Ticket number:

## Frontend COP
- [ ] Watch the [Frontend Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Front-endOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Frontend COP will rerecord.
     - Ticket number:

## Analytics & Insights team
- [ ] Watch the [Analytics Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AnalyticsOrientation) and verify content is up to date and accurate. If not, please create a ticket to rerecord the video and prioritize it for an upcoming sprint. Share with Governance once ready.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Analytics & Insights team will rerecord.
     - Ticket number:

## Governance team
- [ ] Watch the [Design & Research](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Design&ResearchOrientation) and verify content is up to date and accurate. 
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:
- [ ] Watch the [QA Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAOrientation) and verify content is up to date and accurate.
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:
- [ ] Watch the [Accessibility Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AccessibilityOrientation) and verify content is up to date and accurate. 
   - [ ] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:

**Comment by shiragoodman** [comment]
@steel36 what is the status of this ticket? Please lmk. ty!

**Comment by steel36** [comment]
@shiragoodman I've inserted our guidance into the ticket.  Should be good to go!
