### ISSUE TITLE
Payment History - On this page link updates

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#88744]
### Summary
We need to update text and add two anchor links on the Payment History page that drop down to specific content sections on the same page.

### Acceptance Criteria

 **Scenario**: Display "How to request financial help" link in the "On this page" section
- Given the "Payment History" page is displayed
- When the user clicks on the "How to request financial help" link in the "On this page" section
- Then the page should scroll to the "How to request financial help" section
- And the instructions for requesting financial help should be clearly presented

**Scenario**: Display "How to dispute a debt" link in the "On this page" section
- Given the "Payment History" page is displayed
- When the user clicks on the "How to dispute a debt" link in the "On this page" section
- Then the page should scroll to the "How to dispute a debt" section
- And the instructions for disputing a debt should be clearly presented

**Scenario**: Replace "How do I pay my VA debt?" with "How to pay your VA debt"
- Given the "Payment History" page is displayed
- The text "How do I pay my VA debt?" should be replaced with "How to pay your VA debt"

**Comment by Tom-Davis** [comment]
Duplicate ticket - closing
