### ISSUE TITLE
Form-within-a-form experiences 

### ISSUE THREAD

**Issue by jinaryu** [department-of-veterans-affairs/va.gov-team#88750]
**Context**
DBEX team 2 and the Benefits Decision Reviews teams have been working on similar problems related to forms within a form. This is a ticket to track that collaboration and answer these key questions identified by CAIA:

**Questions to answer** ([slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1719255400370409))
1. How should forms let people know when they're in a separate form that's within a broader form? (I'm aware that Matt Dingee and [Mikki](https://dsva.slack.com/archives/C01DBGX4P45/p1721235934637899) say that CAIA's earlier recommendation for the 0781 to change the subheader doesn't make it clear enough)
- Danielle is going to thread some ideas in slack
2. How should forms with subforms handle redundancies? For example, asking people to upload evidence, and asking how they want to submit non-VA medical records more than once? (The 0781 team is testing this, and will have insights to share.)
- team is working around limitations (changes to the rest of the 526 form are out of scope, the trauma informed community of practice recommends keeping the 0781 questions all together). She may check in with Shannon Ford about these limitations and possible ways to iterate on redundancies.
3. How should forms direct people into subforms? (The 0781 team is testing this, and will have insights to share.)
- Danielle says we should def come up with a standard approach to this. One idea is to put the OMB info on intro pages and to mention the respondent burden time again when Veterans start the subform.
4. How should subforms provide points for people to exit the subform? (The 0781 team is testing a backlink to a list of additional forms. Design system doesn't have any guidance for this currently. Mikki has provided guidance specific to the 0781 backlink in this [thread](https://dsva.slack.com/archives/C01DBGX4P45/p1721244093112389?thread_ts=1721235934.637899&cid=C01DBGX4P45).)
5. How should subforms show progress through the subform? (The 0781 is testing H3s that refer to parts of the subform as "Section X of Y")
6. Where should OMB information about subforms go? Should we tell people about subforms on form intro pages? And if yes, what should that look like? (edited)

**Comment by jinaryu** [comment]
Providing an update about Question 5

Research findings (link to [mural section](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720718384066/24c39fd610fe152cc3c29a612652c374d77a0e46?wid=0-1722360064154)):

- response to the progress headers was positive 
- there were suggestions to make it more specific (ex. adding a progress bar)

**Comment by katherine-fung** [comment]
Thanks @jinaryu! That's helpful to know. I want to note that if your team wants to implement "Section X of 4" for the subform, we recommend you check the entire 526 for instances of the word "section," to make sure the form uses the word in a consistent way (aka not using "section" to refer to the broader Step 1/2/3/... of the form, etc)

cc @aprocik1 @shannonkford

**Comment by rubensun** [comment]
We've restructured the document organized around structural, navigational and presentation considerations, surfacing user needs, past precedent, and design decisions.

**Comment by eileen-coforma** [comment]
We're in the middle of our Supplemental Claims updates research, and have conducted 4 AT sessions so far.

We haven't tested the actual form-within-a-form flow yet, but when it comes to adding non-VA evidence (and submitting 4142 + 4142/a), adding hint text about us submitting the additional forms to radios for our non-VA location evidence entry point page has successfully informed AT-users that by adding non-VA facilities, we are submitting a separate form for them.

They have chosen not to submit non-VA medical evidence at this time, and due to time-constraints, we didn't push for them to do so. We still have one AT-test left, and a series of non-AT tests. If time permits, we can try to incorporate some of the non-VA facility flow (with the 4142 + 4142/a forms) into our study.

**Comment by rubensun** [comment]
@aprocik1 , @jennymayoco , @jstrothman , @kristinoletmuskat , @laurwill pulling you off of "assigned" just for our own sprint management purposes. 
Feel free to continue to follow the ticket for updates.
