### ISSUE TITLE
Contact Center Review for Disability Benefits Experience Team 2 - 526 Post-Submission Failure Email (BDD)

### ISSUE THREAD

**Issue by juliepedtke** [department-of-veterans-affairs/va.gov-team#88767]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
This is a follow-up ticket from https://github.com/department-of-veterans-affairs/va.gov-team/issues/82085

The Post-Submission Failure emails will be sent to Veterans when a document fails after they submit their 526 BDD claim. Documents that can fail are VA Form 0781, VA Form 0781a, VA Form 4142 and any form that the Veteran uploads with the claim. Currently, there is no notification to the Veterans that the documents have failed.

Changes since that update are we are releasing only one version of the email to start, and we have added images of how the email and the overflow text will appear.

We will be making the same update for 526 product guide, since the same failures apply there. See [ticket 88765](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88765)

### Launch Date
Anticipated launch around 7/23/24

### Version Number
*Please provide the version number of the guide and/or video.*
2.1

### Product Guide
See Post Submission Failure Email addition. This is the only change to the product guide at this time.
[526 Benefits Delivery at Discharge v2 - product guide - update 7-18-24.docx](https://github.com/user-attachments/files/16287615/526.Benefits.Delivery.at.Discharge.v2.-.product.guide.-.update.7-18-24.docx)

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by juliepedtke** [comment]
Thanks Steven. Since this is the same exact change as the [non-BDD 526](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88765), is it possible we can get these reviewed and approved together?

**Comment by starlow00** [comment]
No changes from VEO. I've attached the current copy of the guide. Please use it for future product revisions. Thank you!

[526.Benefits.Delivery.at.Discharge_v2_SRT 07232024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01DQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--380259d3b7e54ff639f416f35632e4ff2fb8c0dc/526.Benefits.Delivery.at.Discharge_v2_SRT%2007232024.docx)
