### ISSUE TITLE
Contact Center Review for Disability Benefits Experience Team 2 - 526EZ Post-Submission Failure Email

### ISSUE THREAD

**Issue by juliepedtke** [department-of-veterans-affairs/va.gov-team#88765]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
This is a follow-up ticket from https://github.com/department-of-veterans-affairs/va.gov-team/issues/82085

The Post-Submission Failure emails will be sent to Veterans when a document fails after they submit their 526 claim. Documents that can fail are VA Form 0781, VA Form 0781a, VA Form 4142 and any form that the Veteran uploads with the claim. Currently, there is no notification to the Veterans that the documents have failed.

Changes since that update are we are releasing only one version of the email to start, and we have added images of how the email and the overflow text will appear.

We will be making the same update for 526 BDD product guide, since the same failures apply there. See [ticket 88767](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88767)

### Launch Date
Anticipated launch around 7/23/24

### Version Number
*Please provide the version number of the guide and/or video.*
3.3 

### Product Guide
See Major Issues and Error Message for the Post Submission Failure Email addition. This is the only change to the product guide at this time.

[VA.Form.21-526EZ.v3.3.product.guide.SRT.07192024.docx](https://github.com/user-attachments/files/16287553/VA.Form.21-526EZ.v3.3.product.guide.SRT.07192024.docx)

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Draft looks good. Sending to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. I've attached the current copy of the guide. Please use it for future product revisions. Thank you!

[VA.Form.21-526EZ.v3.4.product.guide.SRT.07232024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6cd4b71cd4c5be9f34fbb46c0750e5b4ecb3541/VA.Form.21-526EZ.v3.4.product.guide.SRT.07232024.docx)

**Comment by starlow00** [comment]
Hi @juliepedtke. Is there a new update for this guide? I ask because I found this in the Veteran Support ticket backlog the other day, but don't see any changes since July 2024. Just wanted to check before I close this on our end. Thanks!
