### ISSUE TITLE
Discovery on certifying official role

### ISSUE THREAD

**Issue by uxrebecca** [department-of-veterans-affairs/va.gov-team#88761]
### Problem
In the future state for updating contact information, VSO certifying officials will be able to sign in and see the representatives from their organization. This information is captured in GCLAWS, kind of, and also kept in a spreadsheet which is where OGC updates the information.

### Resources
- [Future state map](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717174574592/c341950387ab12e53dc358182f0c84774e94efb2?wid=0-1718127916581)

### Acceptance Criteria

- [ ] Understanding and documentation of how certifying officials are represented in GCLAWS
- [ ] Draft proposal of how this will technically work in the future

**Comment by tjheffner** [comment]
Draft proposal located here: https://dsva.slack.com/docs/T03FECE8V/F07DM5PS63B
