### ISSUE TITLE
Re-load page on chunk error

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#8879]
Sometimes we get chunk errors, which happen when a user is using the app and deploy happens. We should reload the entire page when this happens, if we can properly catch the error.

I don't know where these errors would be thrown. Maybe from the promise called in the routes file?

Sentry: http://sentry.vfs.va.gov/vets-gov/website-production/issues/118312/?query=is%3Aunresolved%20source%3Avaos

**Comment by lenaecb** [comment]
VSP - is looking into this issue more globally. Check in to see where they are progressing on this first.

**Comment by jbalboni** [comment]
Related VSP issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8983

**Comment by lenaecb** [comment]
Moving this to 'blocked' until we see what VPS does with #8983
