### ISSUE TITLE
Midpoint Review - IA Feedback - Accredited Representation Management: Representative Status in Profile and MyVA

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#88800]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for coming through collab cycle!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Should: work with CAIA to map user flows, entry points and happy/unhappy paths** though Design Intent is an optional touchpoint, I realized during discussion that a user flow, something we ask for at Design Intent, would be helpful for all involved. It would help answer questions that were raised toward the end of the meeting, including "Should this be a page in Profile at all?" How might a Veteran access information about their appointed rep, or learn about how to appoint a rep? Where should they look for it? What should the flow for finding and contacting their rep look like? How might a page in Profile connect to the Find a Rep app, and what information would be helpful to display on each? Any other points of entry that should be considered?

- [x] **Consider: drop "information" from the page title** In Profile, what's the rubric for including the word "information" in a link and page title? Is the word "information" pertinent to this page, or could it be dropped from the page heading and sidebar link text?

  ![Screenshot 2024-07-18 at 2 32 44 PM](https://github.com/user-attachments/assets/9dbec9aa-d315-4f39-938d-5cf8e4eec38e)

- [ ] **Consider: placement on profile page, and grouping of information** I agree with Matt Dingee that we are getting close to needing some in-page IA (headings, other groupings) on the profile landing page now that we're up to 9 boxes. Anticipating a future where those headings might be needed, what types of choices might be made about grouping of cards on this page? How might cards be grouped together, and what headings could be placed above them to create more page structure? For example, would you want to create a section for Contacts and include this card, as well as personal health care contacts?

  ![Screenshot 2024-07-19 at 11 49 10 AM](https://github.com/user-attachments/assets/230aede7-b0f0-4da1-8a91-64ddbf59e988)

- [ ] **Consider: should VSO come first in the link text?** good question from @rtwell: Since we know that many veterans know what VSO means, moreso than Accredited Rep, should VSO come first in the page title and link text? 

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by oddball-lindsay** [comment]
> Consider: placement on profile page, and grouping of information

We think it makes the most sense to leave grouping of information to the authenticated experience team since they will have a deeper understanding of the Profile/MyVA IA and content, and how to approach this.   [Michael took a first pass](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2462%3A162679&node-id=8571-500083&t=IVg83Y69zy6kImim-0&scaling=min-zoom&content-scaling=fixed), which can be used to jump-start the ideation with that team.

-----

Here is our user flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721761212189/01166a89690962542557153b56a71343144eb05f?wid=0-1721772744244&sender=ubac5f0487f25bc4431288699

@erinrwhite did you want to take a look in case this brings up any other feedback around our [Profile designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=7528-75290&t=TsGd8rbY7uVCcLBL-0)?

**Comment by erinrwhite** [comment]
@oddball-lindsay 👀 love to see that mockup of the profile page! Thanks for sharing these updates.

**Comment by oddball-lindsay** [comment]
> Consider: should VSO come first in the link text? good question from @rtwell: Since we know that many veterans know what VSO means, moreso than Accredited Rep, should VSO come first in the page title and link text?

We have decided not to address this feedback, per OCTO's CAIA guidance which is to lead with "accredited representative" as an umbrella term, before introducing specific types of accredited representatives, like "VSO." The order of these terms in the H1 doesn't impact findability or SEO, so we shouldn't change it.

While research has shown users resonate with the term "VSO" we also haven't struggled with findability once the term "VSO" was mentioned in the header.

Closing this ticket out, @erinrwhite feel free to reopen if you have any concerns!
