### ISSUE TITLE
Improve easy navigation for key-board only users (Cancel Pending Workflow) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#88817]
## Description
When a user only navigates by keyboard, the navigation does not follow the same tab pattern when user chooses not to cancel their request. 

---

## Issue
When user tabs over and hits Enter/Return on the `Cancel request` button, then selects the `No, do not cancel` button. The next tab should be on the first link of the page. It currently goes back to MHV secondary navigation. 

https://github.com/user-attachments/assets/e81dd6cd-d69f-40b6-b575-40103311bab0

See [this collab cycle ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/88448) for more details. Their recommendation was to match the other interactions for this product --- when going to a new page, focus goes to the H1 using tabindex="-1".

## Acceptance Criteria
- [x] Given the user is on the Pending details page
       When the user tabs over the `No, do not cancel request `button, hits `Enter` and press `Tab` 
       Then the tab should go to the first link on the page

### Design Assets
Not applicable

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/88817?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/88817?planning-poker) with Zenhub @vbahinwillit

**Comment by ldelacosta** [comment]
Validated in staging. UX will take a second review.

**Comment by outerpress** [comment]
@ldelacosta @jenniemc validated! @jenniemc since Leah's out, you can close this one.
