### ISSUE TITLE
CF: Update Caution Flag value for Ashford University Online

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#8882]
As an EDU team member, I need the caution flag for Ashford University to display specific information so that Comparison Tool users are accurately informed when viewing the school profile.

## Assumptions:
1. This work is completed behind a toggle so that it is only available in the staging environment and below.

## Acceptance Criteria: 
1. When the following caution flag is received 
 > The State Attorney General filed a lawsuit against Ashford University for engaging in unlawful business practices, and litigation is pending

in the settlement.csv file loaded into GIDS the following caution flag is displayed:
    - Title: State’s Attorney General filed suit
    - Description: The State Attorney General filed a lawsuit against Ashford University for engaging in unlawful business practices, and litigation is pending.

## Supporting Artifacts: 
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/651

**Comment by dneel-bah** [comment]
Based on discussion with EDU on 08/24, this issue can be closed as OBE.  EDU will be able to manage settlement caution flag language using new caution flag file implemented as part of #10150.
