### ISSUE TITLE
UX: Interstitial page design for VA Health Chat integration

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#88847]
## Description
We're trying to integrate a service called the VA Health Chat onto My HealtheVet by offering a cross-link to it on the MHV home landing page.

* The issue is that it's an external site and is only useful if certain conditional criteria are true (the user is a patient at a facility that uses the service, has had an appointment within 36 months, and they clicked it within an active support window, not outside of business hours).
* Due to the conditionals, OCTO want us to create an interstitial page that warns users about these limitations, which might affect their access when they proceed to the website.

### User story

As a Veteran, I want to have access to help and support from the VA Health Chat app when I need it, and to understand whether there are limitations to that help so that I can set my expectations before I leave VA.gov and get to the VA Health Chat site. 

### Notes
- Open A11y question about what link text to use to describe the VA Health chat service, when it goes to an interstial page first that is not the actual destination. [Slack thread started here ](https://dsva.slack.com/archives/C05QG2H510T/p1721413999867259). 
- Broader thread around solutioning with Patrick and Kaitlin [in Slack here](https://dsva.slack.com/archives/C0581MN69TJ/p1720455552702589) 

Possible tasks:
- [ ] Design interstitial page in Figma that can be linked to before sending users onward to VA Health Chat
- [ ] Run designs and approach by an a11y SME
- [ ] Run approach and designs by Kaitlin & Patrick
- [ ] Discuss with devs
- [ ] Propose URL for this page and run by IA for approval

## Acceptance criteria
- [ ] Approved plan and interstitial design are ready for devs
- [ ] Follow-on implementation ticket has been created
- [ ] IA review
- [ ] A11y review

**Comment by sterkenburgsara** [comment]
**Convo with David Kennedy about this from a11y pov below. Also asked in #mhv-accessibility channel where additional opinions have been shared.** 



 <img width="1197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUQyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--594daedf7793833afac6997c30062e52341e97c6/Screenshot%202024-07-19%20at%202.31.43%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 2.31.43 PM.png" />

**Comment by wesrowe** [comment]
Closing as a no-op – we're going with static link.
