### ISSUE TITLE
Annotate Domo Reports with GA4 Changes

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#88854]
### Description
We need to ensure we are able to add all of our comments, and annotations we identified during the migration and QC process on the actual Domo reports themselves.

These are currently all tracked at the bottom of our [QC page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3269525541/Final+QC+Checks+--+Priority+Domo+Datasets). 

---

### Tasks

- [x] For each annotation in Domo, make them on the report.

### Acceptance Criteria

- [x] All of the comments/annotations from our QC process have been added to the Domo reports.

**Comment by Blivaditis** [comment]
A majority of the previously identified issues we had noted on our [round 2 doc](https://vfs.atlassian.net/wiki/spaces/AT/pages/3436019714/Annotations+for+Domo) were solved in Domo through ETLs/functions or solved themselves during the migration/append, see document for specifics. The document has been updated to reflect the new status, the only annotation we needed to make was the refinement rate and that has been added. Moving this to done as all issues have been solved and updates made.
