### ISSUE TITLE
Update secondary nav link for Medical Records Phase 1 launch

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#88851]
## Description

Medical records is set to launch into Phase 1 around September 2024. When this happens, the secondary navigation link for Medical Records will need to point to the actual medical records tool instead of the temporary page we built for the transition.

However, the launch plan will be incremental: at first only to around 1% of users, and over two months we will work up to 100% of users, with a goal of reaching 100% by November 2024. So, this will need to be feature-toggled. 

### User story

As a Cartography team member, I want to be prepared to launch secondary navigation updates that will coincide with the launch of Medical Records into Phase 1, so that their navigation options match their access and experience. 

As a Veteran, I want to be able to use secondary navigation to point me to the new medical records experience consistently and seamlessly. 

### Notes
- Current link in secondary nav: `va.gov/my-health/records/`
- New link we need to point to: `va.gov/my-health/medical-records/`

* please validate whether the trailing slash is correct?

Possible tasks:
- [x] Update secondary nav link to MR (behind feature flag) to point to: `va.gov/my-health/medical-records/`
- [x] figure out how to feature flag this for release to 1% of users at launch

## Acceptance criteria
- [x] secondary nav link to MR sends users to the correct URL `/medical-records/ `
- [x] Work is behind feature flag
- [x] we are prepared to launch this to only 1% of users alongside the MR launch to Phase 1
- [x] QA review
- [ ] A11y review

**Comment by carlosfelix2** [comment]
The MR App is behind this feature flag:
```
"mhvMedicalRecordsToVaGovRelease": "mhv_medical_records_to_va_gov_release"
```
Then they have other feature flags for each of the features inside the MR app
```
"mhvMedicalRecordsDisplayConditions": "mhv_medical_records_display_conditions",
  "mhvMedicalRecordsDisplayDomains": "mhv_medical_records_display_domains",
  "mhvMedicalRecordsDisplayLabsAndTests": "mhv_medical_records_display_labs_and_tests",
  "mhvMedicalRecordsDisplayNotes": "mhv_medical_records_display_notes",
  "mhvMedicalRecordsDisplaySidenav": "mhv_medical_records_display_sidenav",
  "mhvMedicalRecordsDisplayVaccines": "mhv_medical_records_display_vaccines",
  "mhvMedicalRecordsDisplaySettingsPage": "mhv_medical_records_display_settings_page",
  "mhvMedicalRecordsDisplayVitals": "mhv_medical_records_display_vitals",
```
HOWEVER: The app feature flag is already turned on for EVERYONE in prod along with other flags. The ones that are NOT on are:
```
mhv_medical_records_display_domains
mhv_medical_records_display_labs_and_tests	
mhv_medical_records_display_settings_page
```
SO... we need our own toggle.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the secondary nav link to the medical records page has been changed from `/records` to `/medical-records` and users are able to navigate as expected using the secondary nav.

https://github.com/user-attachments/assets/a44824e8-83b5-453c-8ba2-55f1d9e00307
