### ISSUE TITLE
Contact Center Review for [Pension Benefits Team - Pension 527ez- Intent to File Updates] 

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#88864]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
We re-launched the Pension Benefits 527ez form online in January 2024. It was deactivated in November 2023. We've made a post-launch improvement to add Intent to file functionality to the 527EZ and updated the Product Guide accordingly and are providing it here for your review.
When a Veteran logs in and starts a pension application online, the system will automatically establish an Intent to File (ITF) date that matches the date they started the application.  The ITF date can be used as the effective date once benefits are granted. 
Note there are no Veteran facing changes in this iteration of the feature, it is a back-end only change.

### Launch Date
A staggered launch is planned, with a launch to 25% of applicants the week of 7/22/24, a week of monitoring and a release to 100% of applicants the following week if no issues.

### Version Number
2007122024
Related updates on page 4 and page 7 only (and table of contents)

### Product Guide
[*Pension product guide link*](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Pension/Pension%20Support%20Guide/Pension%20527ez%20Form%20Product%20Guide%2007122024.docx?d=w4e6819d3870d411c95321ffdc6dc658b&csf=1&web=1&e=zXRFo8)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @matt4su. I can't access the link to the draft. Can you please attach it to this ticket as a Word doc?

**Comment by matt4su** [comment]
[Pension 527ez Form Product Guide 071224.docx](https://github.com/user-attachments/files/16365744/Pension.527ez.Form.Product.Guide.071224.docx)

**Comment by starlow00** [comment]
Initial review complete, sending to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. The current copy is attached to this ticket; please use it for future revisions. Thank you!

[527EZ Pension Benefits Application.Guide.SRT 07252024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--561bba242fa6a2a22b47407cdc1f7b6fc45ef99c/527EZ%20Pension%20Benefits%20Application.Guide.SRT%2007252024.docx)
