### ISSUE TITLE
SOCKS access for Michael Skinner

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-team#88872]
### Your Name

Michael Skinner

### Your Email

michael.skinner@agile6.com

### Your GitHub Handle

Agile6MSkinner

### Your Role and Team

Product Manager - Sitewide Facilities

### Product Manager (PM) name and email

I am the product manager

### Product Owner (PO) name and email

Michelle Middaugh - suzanne.middaugh@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWlZxKkleTb9sqGqEZWpomfDqHPDkAZ63fMF64zt+SN truehoax@SkinnerM-A

### E-QIP Transmittal Confirmation

![image](https://github.com/user-attachments/assets/a6aa2702-2723-4742-8885-4f2cab0e0827)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by Agile6MSkinner** [comment]
They key seems to have changed again. I have pasted the new one.

**Comment by flooose** [comment]
@Agile6MSkinner I've updated your key, but if this happens again, you might want to take this to [platform support in DSVA Slack](https://dsva.slack.com/archives/CBU0KDSB1). Under normal circumstances, your SSH key shouldn't change and they may be able to help you troubleshoot the situation. Here's the [documentation](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack) for requesting help.

Good luck!
