### ISSUE TITLE
UX/product discovery: VA Health Chat implementation options

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#88881]
### User story

As a Cartography team member, I want to analyze options for how to make VA Heath Chat available to Veterans who are eligible, so that we and OCTO stakeholders can chart a path that balances getting value quickly to Veterans with concerns around UX and accessibility for all Veterans.

### Notes
- "interstitial page option" = put a static link on MHV landing page, which links to a page on VAgov explaining more about the limitations of VAHC (VISN, hours, appt within 36 months, etc)
- [Large Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1720455552702589) that kicked off options discussion
- [Kaitlin's Mural of explorations](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718075410575/0f29fdbccc61d21bbf524d4769de17a2173e37cd?sender=uffe0b1e17d72421900bf8566)
- VA's mobile app directory has a [page with pretty detailed info](https://mobile.va.gov/app/va-health-chat) about VAHC availability by channel and VISN
- Ask Wes for his ongoing notes and analysis
- Patrick proposed a high-level roadmap/phased rollout approach in the [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1720455552702589):
  - v 0.1: put health chat link on landing page that connects to an interstitial page on va.gov that has info/disclaimer. use feature toggle to incrementally make available to users. keep an eye on things.
  - v 0.2: add in facility conditionality. we know exactly what facilities don't offer health chat. we know what facilities the user is registered. use a hard coded facility disallow list to hide the health chat link for users who won't ever have access.
  - v 0.3: assuming health chat availability api is not yet ready for us, do discovery on using our own appointments list integration as a basis for the 36 month eligibility window. also remember the stakes here: if a patient accidentally gets through to health chat and didn't have an appointment in the last 36 months, is that a real problem? (yes, Kaitlin thinks this is a UX problem, see screenshot below)

Possible tasks:
- Validate link-plus-interstitial page approach; authed or unauthed?

## Acceptance criteria

- Validated interstitial-page approach or proposed alternative – including a high-level phased roadmap if appropriate
- Met with Patrick & Kaitlin (office hours?) to review
- Ticketed next steps – e.g., draft interstitial page content (w/ CAIA), write product outline / iteration brief, etc

**Comment by wesrowe** [comment]
Consulted Patrick, Kaitlin, Robyn on injection via slack.

**Comment by wesrowe** [comment]
Met with OCTO trio today, we have agreement that the static-link approach is best. Rationale: an interstitial page on VA.gov would not be personalized at all, whereas the VAHC experience is personalized/dynamic – e.g., it shows the user what they can do in their VISN and whether those channels are open right now.

**Comment by fmccaf1** [comment]
Met with Patrick, Kaitlin, Wes and decided: MVP will be link on landing page that leads directly to VA Health Chat (no interstitial page).
