### ISSUE TITLE
VSP QA feedback on Yellow Ribbon MVP [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#8888]
### Links
**Test Plan / Execution logs:**
https://dsvavsp.testrail.io/index.php?/plans/defects/213
**Coverage for References Report**
https://dsvavsp.testrail.io/index.php?/reports/view/72
**Summary (Defects) Report**
https://dsvavsp.testrail.io/index.php?/reports/view/73

### Feedback
**Test Execution Logs**
1. Looks great!  I love that you organized the tests into test runs for each configuration as well as a common set of tests that only need to be hit once ("Device-agnostic").  Good stuff!

**Coverage for References Report**
1. 100% coverage -- excellent
1. It looks like the user stories from which you are deriving the test cases are pretty light on explanation. The Invision prototypes look great and are very useful for test case creation, but it would be great if there were formal definitions of behaviors as acceptance criteria as well.  Still, it's excellent that you have user stories for reference!

**Summary (Defects) Report**
1. I see three unresolved defects.
   1. [8742](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8742) appears to be resolved as a non-issue per the latest [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8742#issuecomment-625293835).
   1. [8741](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8741) appears to be near a resolution -- great!
   1. [8738](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8738) appears to be limited to IE11, but it is not yet resolved. Is the team comfortable going to production without IE11 users being able to interact with pagination?  This seems like a fairly major issue that should be resolved prior to production deploy.  Also, excellent use of a GIF!

## Definition of Done
- [x] Acknowledge each item of feedback with a decision
- [x] VSP QA will close ticket after reviewing feedback decisions

**Comment by kelsonic** [comment]
Sorry for moving this 🙂

**Comment by pjhill** [comment]
> Sorry for moving this 🙂

:relaxed:

**Comment by kelsonic** [comment]
> > Sorry for moving this 🙂
> 
> ☺️ -- no problem, still working on how best to classify these tickets. If I need to alter the ticket in any way to better fit your workflow then let me know.

Awesome, thank you! 🔥

**Comment by stephorkandatx** [comment]
@pjhill we resolved the items listed above. Please review

**Comment by pjhill** [comment]
> @pjhill we resolved the items listed above. Please review

Great work resolving these issues!
