### ISSUE TITLE
[Design] Add cancel steps into Community Care VSS after consult approval workflow (Mural)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88898]
## Tasks

- [ ] Add cancel steps into Community Care VSS after consult approval workflow ([Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717007634301/2e9fa61206c18e8cf196e2deb612eb0b577fb458?sender=u37bb983bd3fc3cc00c7d3286))

**Comment by loripusey** [comment]
I'm assuming we don't need this right now as cancel is no longer part of the MVP

**Comment by benbrasso-agile6** [comment]
Sounds good thanks
