### ISSUE TITLE
10-10d design review changes for go-live

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88909]
See changes below resulting from UX's 10-10d design review.

## Page: Throughout
Subtitle says “10-10d” — should be updated to say “Application for CHAMPVA benefits (VA Form 10-10d)
**Example**:
<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWo2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92fb0484df70d415940cf152c73e0d794b286b31/image.png" alt="image.png" />

## Page: Intro Page, bullet 2
Remove the line “Find out which documents you’ll need to apply for CHAMPVA” since it’s a dead link and the destination page isn't ready yet (CAIA is working on it).

## Page: Intro Page, bullet 3
Says [XX] for amount of time it will take to fill out the form. Should be changed to 10 minutes.

## Page: Upload supporting documents 2
The second page that’s called “Upload your supporting documents” should be called “Supporting documents summary”

**Comment by baltes** [comment]
@michaelclement Here's another one that's ready if you need to pick something up.
cc @marywang2

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30989). Waiting on:

- [X] Team approval
- [ ] Platform approval

| |Before|After|
|-|-|-|
|Intro|<img width="695" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61cda7d61b722ae8f899bd9ccf049edaccfb4fbe/intro_before.png" alt="intro_before.png" />|<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81dcf85d78129a58a08b1564f00a5714d99478b3/intro_after.png" alt="intro_after.png" />|
|Summary|<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f71b3a7c833370507c983dc1e6dbf024bfb125b4/upload_before.png" alt="upload_before.png" />|<img width="535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--121aeef0766ef1fb103efed7d38ad94bd905cb19/upload_after.png" alt="upload_after.png" />|

**Comment by michaelclement** [comment]
@baltes @marywang2 @jamiefiore This has been merged and should be visible on staging shortly. Thanks!
