### ISSUE TITLE
[Spot Check] Original Claims: Legacy Accessibility Check for 526 All Claims (Includes Original Claims)

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8890]
## User Story or Problem Statement
We need to perform an accessibility spot check for the entire 526 form.  It has been a long time since a check of any kind and since we are releasing Original Claims we are going to not kick that can further down the road and go ahead and do a full check of the 526 claims flow. When we get to BDD this will help.

### Required:
- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
- [x] Conduct axe browser scan, and document or address issues found 
- [x] Ensure end-to-end tests - including the axe check, pass 
- [x] Check color pairing for proper contrast 
- [x] Check for colorblindness issues 
- [x] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
- [x] Repeat for 300% 
- [x] Repeat for 400% 
- [x] Navigate all pages and core functionality with keyboard only 
- [x] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 
    
### Recommended:
- [x] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
- [ ] Add keyboard end-to-end tests in CI/CD test runs  
- [x] Conduct axe-coconut browser scan, document or address issues found 
- [x] Test with [WAVE tool](https://wave.webaim.org/) 

## Goal
Get ready for full release of Original Claims.

## Acceptance Criteria
- [ ] Above checklist is completed
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
I just finished the following for form 526/original claims:

- Used ChromeLens to test for colorblind issues
- Manually navigated through form 526 using the keyboard
- Tested pages with zoom at 200%, 300% & 400%
- Conduct axe browser scan, and document or address issues found:
  - https://github.com/department-of-veterans-affairs/vets-website/pull/12241
  - https://github.com/department-of-veterans-affairs/vets-website/pull/12449
  - More fixes in a PR yet to be opened.

**Comment by Mottie** [comment]
Update: header fixes PR opened that should resolve remaining accessibility issues for form 526. Once merged, I'll update the e2e test PR and make that ready for review.

**Comment by Mottie** [comment]
Status:

- Cypress e2e tests are available in a branch, but not quite yet ready for everyday use. Once available, it will replace the puppeteer e2e tests; and it has axe checks already built in. 
- I started working on keyboard e2e tests; but I'm stuck on getting authentication working. Given that I'm writing the test using Nightwatch and we're switching to Cypress soon, I may postpone completion of this path.

**Comment by Mottie** [comment]
I am still working on fixing a few more a11y issues that I found:

- Change date formats to a "month, day year" fornat to make it more readable (vs mm/dd/yyyy)
- Switch all-caps text to title case
- Fix focus management when adding, editing or removing new disabilities.

**Comment by Mottie** [comment]
Cypress e2e tests have been added - https://github.com/department-of-veterans-affairs/vets-website/pull/12978, thus completing this spot check. The only thing that wasn't done was added keyboard e2e tests, which would need to be built using Cypress.
