### ISSUE TITLE
Design feedback for  Staging Review [Yellow Ribbon MVP]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#8892]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:** 
No “do” feedback at this time

**Try:**
  No “try” feedback at this time

**Consider:**

- [On this content page](https://staging.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/), consider changing the links in the “On this page” section to follow the link typography format: source sans pro regular 16px in #004795

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@CrystabelReiter @emilywaggoner Since there appears to be no feedback, can this issue be closed?
