### ISSUE TITLE
Access for Ken Mayo

### ISSUE THREAD

**Issue by kenmayo** [department-of-veterans-affairs/va.gov-team#88932]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Ken Mayo

### Your Email

kenneth.mayo@oddball.io

### Team, Role, and Company of the target individual

Platform, Lead Security Engineer, Oddball

### Product Manager (PM) name and email

Kelly Argyros, Kelly.Argyros@adhocteam.us

### Product Owner (PO) name and email

Ray Wang, Gang.Wang@va.gov

### Desired AWS Access

I need Athena and Glue access to test a new role.

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/user-attachments/assets/37efe4d6-02af-46c6-8cca-5b5376f073a7)

### Additional Notes

Using this access to help DevOps test a new role for SBOM generation

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
Confirmed user is in the Platform Roster
