### ISSUE TITLE
FOIA Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#88943]
## Description 
We need to determine a process and document it for FOIA on the support side. We'll use [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2761326593#FOIA-Requests) to document it.

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Document the process when a FOIA request comes through on the [Advanced Support Best Practices doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2761326593#FOIA-Requests) (using the document that Jennifer create on our FOIA call)
- [x] Review with Jennifer/Alyssa
- [x] Publish

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by AnthonyWFlowers** [comment]
I created a copy [here](https://vfs.atlassian.net/wiki/pages/resumedraft.action?draftId=3347447809&draftShareId=4d3cc8a6-a4c8-4656-bf29-6696b294b83e)
It would need a look over as I am documenting what I saw as points of concern from postmortem

**Comment by AnthonyWFlowers** [comment]
This would need a review I suppose? @alyssagallion let me know if there is anything I need to ad or rephrase.

**Comment by alyssagallion** [comment]
Updated and reviewing with @jennb33 :)

**Comment by alyssagallion** [comment]
Published here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/3375169571/FOIA+Request+Process+Tier+1+Platform+Support

Jennifer/Alyssa will run by leadership from this point on. Closing!
