### ISSUE TITLE
Issue when selecting the directions link for CC appointments

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#88948]
## Summary
Currently, there is an issue with the direction links in CC appointment details. The link opens in Google maps the destination address not populated.

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** Judy Morrison

1. Go to: https://staging.va.gov.my-health/appointments
2. Select 'Past' appointments
3. Select date range: 'All of 2023'
4. Select CC appointment on April 28, 2023 at 1:00am ET
5. Click 'Directions'

### Actual Result
Google maps opens in new tab without directions to the CC location

### Desired Result
Google maps should open in new tab with directions to the CC location

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment]
@outerpress @vbahinwillit  - was trying to validate #88948 in staging.

Is the address in the Google maps correct? It has the same street address but the city on the details states
`Sinking Springs` but in Google maps it has `Reading, PA.` Let me know what you guys think.

<img width="891" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62e5d6dd1c3e2aa64b7592b616c74dfd7636705a/Screenshot%202024-07-23%20at%2010.20.44%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 10.20.44 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2eac85c6a2bab8ffd09cf059a143651bf204c0af/Screenshot%202024-07-23%20at%2010.21.10%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 10.21.10 PM.png" />

**Comment by vbahinwillit** [comment]
There are 4 addresses that all seem to point to the same location. The address passed to Google Maps is the Sinking Springs address. It looks like it's choosing the 1st address in the list.

![Screenshot 2024-07-24 at 7 14 39 AM](https://github.com/user-attachments/assets/5f2509c3-2e6e-40d5-9062-1726e7489e3e)
---
![Screenshot 2024-07-24 at 7 05 27 AM](https://github.com/user-attachments/assets/b8b64d7f-77c0-4a43-88a0-12645ae82dd0)

**Comment by ldelacosta** [comment]
@outerpress - please take a look and let us know if you see any other issues.

**Comment by outerpress** [comment]
@ldelacosta @vbahinwillit I tested a couple CC appointments for Judy and they're working perfectly. Thanks!

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @Bren22va
