### ISSUE TITLE
[ENG] 10-10 apps: Investigate ability to utilize flipper toggles for vets-json-schema changes

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88972]
## Background
As an action item on the [Postmortem for Special Characters](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/hdjustice-SpecialCharOOB/Postmortems/2024/2024-07-18%2010-10%20Special%20Character%20OOB%20Post%20Mortem.md), the team has determined additional process and documentation improvements are needed to ensure we follow all proper steps and precautions to avoid negatively impacting Veterans and causing additional work for ourselves and other VA teams.

Postmortem Action Item: 
- Problem to solve: 
     - Updating vets-json-schema currently requires PR’s in three separate repositories and coordinated deployments. The complexity of the update process here opens up opportunities for mistakes (such as occurred here) in the deployment process.  Currently, there is no mechanism for updating vets-json-schema behind a flipper toggle directly.
- Action Plan: 
     -  The 10-10 team would like to explore other ways to block vets-json-schema changes from going live in production, and be able to test the changes in a testing environment
- Implementation & Measurement: 
     - Apply solution to schema changes and test in  the existing Staging environment
- Failure Detection: 
     - Solution is not effective and schema changes are live and visible in Production

### Suggestion from Patrick
>true that changes to vets-json-schema (and the reference to the schema version in vets-website) cannot be placed behind a feature toggle. but validation logic could have been added in (basically the same logic that Mitch ended up adding) and put behind a feature flag. this would allow the schema to be bumped in vets-website, but not actually allow users in production to enter values newly allowed until we decided to.
>(and then if something went wrong with how those new values are handled — like here — the toggle could be turned off)

## Tasks
- [x] During Engineer sync, Engineers will explore options on how to apply a feature toggle when there are vets-json-schema changes
- [x] Review with team/PM 

## Acceptance Criteria
- Discovery is complete and discussed with the team.

**Comment by longmd** [comment]
After discussions and review of testing options, there is [a forms library method available](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-use-updateschema-and-repla) that would allow for the use of a feature flag to update the `schema` props in a form config declaration.

In this scenario, we could check the formData for the value and if true, return the default schema from the file, else, return some sort of hardcoded value that matched our previous schema props.

It may not be applicable in all cases, but could always be available as an option.

**Comment by longmd** [comment]
Noting there are is no current or upcoming body of work that will provide for any test scenarios to be ran through. Those tasks will not be able to be performed at this time.

**Comment by longmd** [comment]
Closing as completed with the addition of the documentation link into the team runbook.
