### ISSUE TITLE
Log when SignUpService is being called and user has multiple sec_id values

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#88977]
When a user has multiple sec_id values, their Sign Up Service calls will fail, so we should log that this user has multiple sec ids. This would be a log in this file: `app/sidekiq/terms_of_use/sign_up_service_updater_job.rb`

We've decided that we won't stop calling Sign Up Service for these users (like we do when they don't have a sec_id), so we are still going to call Sign Up Service, we just want to log for them

**Comment by parkerbees** [comment]
moved to jira, closing
