### ISSUE TITLE
[Feature Request] Update detail page browser tab titles 

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#88979]
## Description

This aligns the browser tab titles for details pages with the new page titles

---

### VA Requests

- [ ] Given a user is on a `confirmed` `VA request` details page
Then the browser tab title should read `Request for [Type of Care] appointment | Veterans Affairs`

- [ ] Given a user is on a `pending` `VA request` details page
Then the browser tab title should read `Request for [Type of Care] appointment | Veterans Affairs`

- [ ] Given a user is on a `canceled` `VA request` details page
Then the browser tab title should read `Canceled request for [Type of Care] appointment | Veterans Affairs`

### Community care requests

- [ ] Given a user is on a `confirmed` `cc request` details page
Then the browser tab title should read `Request for [Type of Care] community care appointment | Veterans Affairs`

- [ ] Given a user is on a `pending` `cc request` details page
Then the browser tab title should read `Request for [Type of Care] community care appointment | Veterans Affairs`

- [ ] Given a user is on a `canceled` `cc request` details page
Then the browser tab title should read `Canceled request for [Type of Care] community care appointment | Veterans Affairs`

### In-person appointments (including vaccine)

- [ ] Given a user is on a `Confirmed` `In-person` details page
Then the browser tab title should read `In-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Upcoming` `In-person` details page
Then the browser tab title should read `In-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `In-person` details page
Then the browser tab title should read `Past in-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `In-person` details page
Then the browser tab title should read `Canceled in-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

---

- [ ] Given a user is on a `Confirmed` `COVID vaccine` details page
Then the browser tab title should read `In-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Upcoming` `COVID vaccine` details page
Then the browser tab title should read `In-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `COVID vaccine` details page
Then the browser tab title should read `Past in-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `COVID vaccine` details page
Then the browser tab title should read `Canceled in-person appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video appointments (including GFE)

- [ ] Given a user is on a `Upcoming` `VA Video` details page
Then the browser tab title should read `Video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `VA Video` details page
Then the browser tab title should read `Past video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `VA Video` details page
Then the browser tab title should read `Canceled video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

---

- [ ] Given a user is on a `Upcoming` `VA Video over GFE` details page
Then the browser tab title should read `Video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `VA Video over GFE` details page
Then the browser tab title should read `Past video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `VA Video over GFE` details page
Then the browser tab title should read `Canceled video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video at VA location appointments

- [ ] Given a user is on a `Upcoming` `Video at a VA location` details page
Then the browser tab title should read `Video appointment at VA location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `Video at a VA location` details page
Then the browser tab title should read `Past video appointment at VA location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `Video at a VA location` details page
Then the browser tab title should read `Canceled video appointment at VA location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video at an ATLAS location appointments

- [ ] Given a user is on a `Upcoming` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Video appointment at an ATLAS location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Past video appointment at an ATLAS location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Canceled video appointment at an ATLAS location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Phone appointments

- [ ] Given a user is on a `upcoming` `phone appointment` details page
Then the browser tab title should read `Phone appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `past` `phone appointment` details page
Then the browser tab title should read `Past phone appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `canceled` `phone appointment` details page
Then the browser tab title should read `Canceled phone appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Community care appointments

- [ ] Given a user is on a `upcoming` `community care appointment` details page
Then the browser tab title should read `Community care appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `past` `community care appointment` details page
Then the browser tab title should read `Past community care appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `canceled` `community care appointment` details page
Then the browser tab title should read `Canceled community care appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Claim exam appointments

- [ ] Given a user is on a `Upcoming` `Claim exam` details page
Then the browser tab title should read `Claim exam appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Past` `Claim exam` details page
Then the browser tab title should read `Past claim exam appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [ ] Given a user is on a `Canceled` `Claim exam` details page
Then the browser tab title should read `Canceled claim exam appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@ldelacosta this addresses collab cycle ticket #88445

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/88979?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
break down into 4 tickets - VA & CC requests, in person appts & claims, phone & video requests, CC booked appts

**Comment by ldelacosta** [comment]
@outerpress - I converted this to a feature. We will link the development tickets here.

**Comment by ldelacosta** [comment]
Created the development tickets #89384 #89385 #89386 and #89387 cc: @Bren22va @outerpress @simiadebowale @JRRoof

**Comment by ldelacosta** [comment]
Feature was delivered in August. Closing out the feature. cc: @outerpress
