### ISSUE TITLE
Improve visual design of "Next Steps" page in PDF download

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#88986]
## Background
We have code in place to generate a completed 21-22 or 21-22a form, and are including a version of the "Next Steps" (last step on the frontend experience) in this download for users to reference.

Our first pass focused only on the content, and there is more work to be done to improve the visual design of this content.

**Consider**: If content / design changes for this particular step, is there a way to lean on the frontend code and minimize backend updates?

Frontend experience:
<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGI5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dce904e665eac6c984003714413c460f157827de/image.png" alt="image.png" />

Current state of the "Next Steps" page of the PDF download:
<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG45QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21ad00d0ab23de10fda3117fc6071a33ac60967e/image.png" alt="image.png" />

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] The PDF download includes a "Next Steps" page that visually matches the last step of the Appoint a Rep frontend experience.

**Comment by oddball-lindsay** [comment]
Apologies @opticbob but we seem to have changed the header copy at some point after this ticket was made. Screenshot below, and [link to actual design](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4311-284570&t=S3pwpVDo7dx21h4D-4) -- please update the header to "Request help from a VA accredited representative or VSO".

<img width="708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL080Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c4595d3e9d6f31eab431eda04a241e6c21f26a8/image.png" alt="image.png" />

**Comment by opticbob** [comment]
Screenshot of finished product:
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3krQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00e14fb1e11630d213c951b54ebc6bfb55114886/new_next_steps_page.jpg" alt="new_next_steps_page.jpg" />
