### ISSUE TITLE
CT-EYB: UX review of 8003

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#8899]
Per UX review, the following AC was not for met https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8003

1. “Collapsed bottom sheet: Monetary amounts are bold” - AC 4 & AC 5. The monetary amounts of OJT and non-OJT should not be bold. Below is a screenshot of the amounts being bold in staging. 
![Screen Shot 2020-05-07 at 4.30.27 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/49c441ab-62dd-4f34-9bd4-50130c487ac4)

2. For OJT, on the expanded bottom sheet, “Housing Allowance” should be “Housing allowance” - AC 8
![ca90e211-a3b7-44ed-a0eb-d186686b491d.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9f529067-5d84-4a19-90d2-cda46b8e44d2)

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12632

**Comment by delli-gatti-michael** [comment]
<img width="321" alt="Screen Shot 2020-05-15 at 11 52 32 AM" src="https://user-images.githubusercontent.com/45575003/82070645-096a0480-96a3-11ea-899a-9bd218a66246.png">

---

<img width="329" alt="Screen Shot 2020-05-15 at 11 53 37 AM" src="https://user-images.githubusercontent.com/45575003/82070653-0d962200-96a3-11ea-8a9a-612ae5c58126.png">

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah 
This fix is on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out for UX!

**Comment by delli-gatti-michael** [comment]
Closing this out with UX and QA approval.
