### ISSUE TITLE
Disabled states - design.va.gov pattern documentation

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#89]
Good documentation on disabled states available on IBM's [carbon design system](https://www.carbondesignsystem.com/patterns/disabled-states). 

It seems we don't really recommend using what they use their 'default' disabled state, so it might be good to document why that is. 

You can leave the write up in a comment below.

**Comment by smoonpeyes** [comment]
@jaredcunha-usds Do we have examples of disabled states on VA.gov?

**Comment by jaredcunha-usds** [comment]
There's a dropdown on the Facility Locator, but I don't think that's a pattern that we really like. I don't really know of other instances. I think @goldenmeanie mentioned to me at some point that we intentionally don't use disabled states (as depicted in the IBM carbon system). It's a pattern I've seen a lot elsewhere, so perhaps we can write why we may want designers to consider alternatives.
