### ISSUE TITLE
Staging Review finding: Inconsistent language around identity verification in "Check if your information is up to date" section

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89007]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Modernized Check-in
**Product:** Pre-Check-in & eCheck-in
**Feature:** New Landing page design

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not meet best practices.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-meets-best-practices)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (Content)

### Description

In the section "Check if your information is up to date" the descriptive text currently reads "First, we need your last name and date of birth to make sure it's you." VA.gov content guidelines recommend the language of "verifying your identity" in these situations (https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification) 

## Recommended action

Rewrite the descriptive text to read "First, we need your last name and date of birth to verify your identity." 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Specific topics: Sign in and identity verification](https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [x] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [x] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89007?planning-poker) with Zenhub @brianseek

**Comment by benbrasso-agile6** [comment]
@laurwill @DanielleThierryUSDSVA would you mind updating the VA.gov content guidelines https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification to clarify the differences of when to use "verify" content (e.g., full auth) vs. "... make sure it's you" for Low Risk One Time Authentication, e.g., via Patient Check In or other apps (like the upcoming online travel pay for OH facilities, Q4). <br><br>

<img width="186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG9CQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--600564ab0eee5745bdc2830240ca5dc4996c0a95/Verify%20Identity.png" alt="Verify Identity.png" />

**Comment by brianseek** [comment]
@benbrasso-agile6 Are we waiting to find out if we need to make a change for this one?

**Comment by benbrasso-agile6** [comment]
@shiragoodman @erinrwhite  are we okay to change this to NOT launch blocking based on our conversation and comment above?

**Comment by laurwill** [comment]
Ooooh thank you for raising this @KKitagawa-Bosch @benbrasso-agile6 ! When we created the sign-in section of the style guide, we didn't include guidance for talking about LOROTA sign-in process. We wouldn't use "verify your identity" here because we reserve that for describing the process of getting an LOA3 verified account through ID.me, Login.gov, etc. But seems like the style guide section needs an update to clarify this. I'll talk with Danielle and get this in our queue for updates!

**Comment by benbrasso-agile6** [comment]
Thank you, @laurwill !

@brianseek seems good to go, especially since Laura helped us write the content for LOROTA

**Comment by brianseek** [comment]
@benbrasso-agile6 nice! I'll assign this to you and let you close it when it feels wrapped up.

**Comment by shiragoodman** [comment]
late to the party, but yes this is good! we had already downgraded it from `launch-blocking` prior to the meeting FYI.
