### ISSUE TITLE
Staging Review finding: Missing punctuation in Appointments > What to do next

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89005]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Modernized Check-in
**Product:** Pre-Check-in & eCheck-in
**Feature:** New Landing page design

## Findings details
**VA.gov Experience Standard - issue:** [User experience is not consistent with the VA.gov design principles.](https://design.va.gov/about/experience-standards/#users-experience-is-consistent-with-the-vagov-design-principles)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (Content)

### Description

In the "Appointments" section under the header "What to do next", the sentence "Review your contact information for your Saturday, July 20 9:00 am appointment" is a complete sentence and should have a period at the end. 

## Recommended action

Add a period to the end so the sentence should read "Review your contact information for your Saturday, July 20 9:00 am appointment."

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Punctuation](https://design.va.gov/content-style-guide/punctuation)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by brianseek** [comment]
@benbrasso-agile6 / @cgednalske / @zach-park this sentence is now gone but we do still have this:
<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkl6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96ef1b9505f3acff4608adf124690e14d163eb4d/Screenshot%202024-08-05%20at%203.44.23%E2%80%AFPM.png" alt="Screenshot 2024-08-05 at 3.44.23 PM.png" />
should the title in the card "Review your contact information for your appointment" get the period?

**Comment by zach-park** [comment]
Hi @brianseek , I don't believe we include a period in the card title. (Cc: @benbrasso-agile6 @cgednalske ).

**Comment by benbrasso-agile6** [comment]
Now that we switched it up, the VA component doesn't call for a period in the heading

https://design.va.gov/components/card

Would close as resolved

**Comment by brianseek** [comment]
love it, thanks @zach-park & @benbrasso-agile6. closing
