### ISSUE TITLE
Staging Review finding: Incorrect apostrophe present in "Next of kin explanation" additional info section

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89008]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Modernized Check-in
**Product:** Pre-Check-in & eCheck-in
**Feature:** New Landing page design

## Findings details
**VA.gov Experience Standard - issue:** [User experience is not consistent with the VA.gov design principles.](https://design.va.gov/about/experience-standards/#users-experience-is-consistent-with-the-vagov-design-principles)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (Content)

### Description

The additional info box labeled "Next of kin explanation" includes a straight apostrophe. Va.gov style guidelines recommend the use of curly apostrophes in all instances. (https://design.va.gov/content-style-guide/punctuation#apostrophes)

## Recommended action

Replace the straight apostrophe with a curly apostrophe.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Punctuation](https://design.va.gov/content-style-guide/punctuation)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89008?planning-poker) with Zenhub @brianseek

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske to help with this movingn forward, we need to make sure that Figma files have curly apostrophes, because engineers often copy/paste from Figma. TY!

**Comment by brianseek** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/31211

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park / @cgednalske This is merged and ready for review locally, on stage, or in the following screenshot:
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8773fcd375e6a0c7ed320cb00fe3f1a68bcd18d9/apostrophe.png" alt="apostrophe.png" />

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by brianseek** [comment]
thanks @benbrasso-agile6! closing this ticket
