### ISSUE TITLE
Original Claims VSA-QA Test Plan

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8901]
## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

Product/Feature Outline: [Original Claims](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/disability-compensation-claim/original-claims/README.md)
Product/Feature Epic: [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1955)
Product/Feature Pre-Launch Checklist: Inside the [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1955)
Product/Feature Design artifacts: \[provide link, if separate from Epic]

## Product-team SMEs

\[List points-of-contact (just full names) for all involved Subject-Matter domains.  Most often, these would be the relevant development-team members (Product Manager, UX Designer, Front-End Developer, & Full-Stack or Back-End Developer]
Product Management: 
Design/Research: 
Content/IA: 
Front-end: 
Back-end: 
QA: Tze-chiu Lei

## Proposed user-scenarios and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs.  IMPORTANT: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

1. <scenario-1> - <test-account-1>
2. <scenario-2> - <test-account-2> ...

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
@luke-gcio , re. our convo around potentially "burnt" Staging test-accounts...

I met with BaM2 yesterday about this exact topic, and we came up with a testing workaround that might also be usable by your team for any flows that causes test-data changes that are irreversible thru the UI...

I suggest that, when our Scenarios list approaches maturity, we schedule a meeting w/ you, f/e, & b/e to validate this QA workaround against OC \[or whichever product you expect to reach Staging Review first].

Feel free to ping me on Slack directly if you have questions in the meantime.

Thx much!

**Comment by tlei123** [comment]
@luke-gcio , would you happen to have any additional Labels/Milestones that would further narrow down my filter below to capture the closed Orig. Claims tickets for which you need QA testing/validation?

Right now, this filter has 2 labels: **vsa-benefits** & **526**:
https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3Avsa-benefits+label%3A526+is%3Aclosed

If no add'l existing Labels are useful, I'd suggest adding a Label such as **StgRvw-QA** to the relevant tickets.

Thx much!

@pjhill, let us know what suggestions you may have.

**Comment by pjhill** [comment]
AFAIK, GitHub's issue search is only capable of ANDing labels. I encourage you to use ZenHub for it's better issue management. ZenHub's workflow / swimlane feature might help your team understand at glance what state each issue is in, and which team member needs to carry the issue to the next step. Does BAM team already have ZeHub workspace?

**Comment by tlei123** [comment]
Staging Review completed -- combined with BDD Stg Rvw.
