### ISSUE TITLE
[Event Bus] Determine how to deploy to argo 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#89038]

**Comment by LouisFettet** [comment]
I believe we can close this one; we already have an application setup in Argo CD, so by adding our application infra configs to the [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repo (and making some slight config changes to our Argo CD app), we should see things get "auto-synced" upon branch updates. This will be accomplished in #95680.
