### ISSUE TITLE
[Veteran Support] All Claims: Secondary Disability Claim Issue

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8904]
### Notes
This veteran was contacted and their initials aaaare XYZ.

We have/have not solved their issue.

### **IRIS: 200221-000446**

_I am unable to submit my form 21-526EZ to file an increase and secondary disability claims on va.gov. I called ebenefits and opened a work order and was sent an email yesterday afternoon advising me the problem was on va.gov end and not ebenefits. My application says "We're sorry. Something went wrong when we tried to submit your claim" when i tried to submit my claim. I have tried to re-submit my claim every day since Sunday 2/16/2020, multiple times a day with the same error. There is no error code associated with the error, just this same message that shows up._

https://www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation

```
File for disability compensation
Form 21-526EZ
We’re sorry. Something went wrong when we tried to submit your claim.
For help submitting your claim:

- Please call Veterans Benefits Assistance at 800-827-1000 <+18008271000>,
Monday – Friday, 8:30 a.m. – 4:30 p.m. ET, or
- Get in touch with your nearest Veterans Service Officer (VSO). Find
out how to contact your nearest VSO
```

I am using a Dell desktop computer.

The error occurs on all browsers.

I have used DS logon, myhealthevet and id.me to log in and still have the
same problem.

I have been trying for 2 weeks to submit my claim. Please assist me in
getting this resolved.

Thank you,

## Acceptance Criteria
- [ ] Claim is submitted
- [ ] Bug Fix ticket written

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Could we put tickets like this in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive ?  I'm guessing we could find out what the specific issue is pretty quickly if we were able to find the veteran's edipi.

**Comment by vhenry07** [comment]
Closed for lack of sufficient data. Will open a new ticket after discussion with call center.
