### ISSUE TITLE
[Bug] VAMC Left Nav - Mobile - Copy/styling mismatches [DRAFT]

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8905]
\[DRAFT: Will finalize details here once all pertinent test-runs are completed.]

## What happened?
On Staging VA Pittsburgh health care page, using mobile phone, copy & styling for **In this section** nav (mobile version of desktop's left-nav) do not match provided design screenshots:

## Specs:
- Mobile phones (Samsung S9/S6, Apple iPhone 11/6)
- Unauthenticated experience

## Steps to Reproduce
1.  Go to https://staging.va.gov/pittsburgh-health-care/
1.  Observe copy/styling mismatches from design:
  -  **In this section** button:
    - Button border-color does not match design.
    - Inside button, extraneous gray-underline appears under label-text and hamburger-icon.
      - On iPhone 11/6, button label-text is missing.
  - Blue CTA-buttons:
    - 2nd button label-text **View all health services** doesn't match design.
    - 3rd button label-text **Register for care** doesn't match design.

### Samsung S9/S6, Android 8 generic emulator:
![ln-copy-styling-bug-01-android8-200507](https://user-images.githubusercontent.com/587583/81357078-9e5b7500-9087-11ea-8628-52c1b487a564.png)

### iPhone 11/6 \[also not missing button label-text]:
![ln-copy-styling-bug-01-iphone11-200507](https://user-images.githubusercontent.com/587583/81362016-c1d8ec80-9094-11ea-8e54-56794e2c375a.png)

## Desired behavior
See design-screenshot provide to VSA-QA:
![ln-copy-styling-spec-01-mobile-200507](https://user-images.githubusercontent.com/587583/81372282-d1652f00-90ae-11ea-833e-70e1b435f9a3.png)

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
@tlei123 ,  checked with @ethanteague  and the copy is correct as it is now, however styles will need to be updated to reflect the wireframe ^

**Comment by mmiddaugh** [comment]
@tlei123
- the copy mismatch noted is acceptable since the design specs had placeholder text
- The "In this section" defect noted is documented in [#8958] 
I'd like to close this issue with your permission, unless I am missing anything that needs to be addressed otherwise. Thanks!
