### ISSUE TITLE
UX/IA: Document roll out plan for Records Ph1 integration

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89054]
### User story

As a Cartography team member, I want to document the roll out plan for MR phase 0.5 (and moving into Phase 1), so that we can identify any challenges (technical or UX) and be ready to implement.

### Notes
- does not include My VA changes (separate ticket #89274)
- Sara asked in slack:
>Open Question - MR is going to launch Phase 0.5 to only 1% of users at first (ETA September 2024), and incrementally work up to 100% over a 2-month span. Do devs need a ticket for discovery work around how to feature toggle the MR box on the landing page and the secondary navigation together for that?
   * No - we will not be linking to this experience from the national portal. The 1% will only happen on VA.gov side (users will be able to find / wander into the experience). It is possible that only a smaller portion of the 1% who have this enabled will use or find it. 
 - UX Updates include temp LP for MR would not show, different MR box on LP

Possible tasks:
- Kicked off collaboration with the MR team
- Understand how National Portal will roll out try me experience to 1% and eventually 100% by November.
  - A: Classic not doing anything
- Discovery - does the national portal use feature toggles? 
  - N/A – there will be no changes to Classic or try-me banners
- Coordinate timeline for increasing rollout - actual dates for each percentage increase
  - N/A? – can't we plan the rollout steps independent of the dates?

## Acceptance criteria
- Documented roll-out plan in collaboration with with developers (Cartographers and MR) - [Working draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/Medical-Records-Phase1-Integration-Release-Plan.md)
- Roll-out plan is vetted with OCTO stakeholders

**Comment by wesrowe** [comment]
Higher priority than #89470 due to MR Ph1 dependency.

**Comment by LynneJohnson224** [comment]
8/8 Refinement - split design/implementation and roll out into 2 separate tickets

**Comment by wesrowe** [comment]
Note: in office hours today, Kaitlin clarified that she anticipates this following the general cross-team pattern that we followed for the original 3-tool integration. My memory of the high level steps includes:
- Kick off with MR team, 
- collaborate with them to document steps in Slack canvas
- track progress in canvas
- dry-run the launch in staging, which doubles as final QA
- smoke test in prod with Kaitlin's real acct
-

**Comment by LynneJohnson224** [comment]
[Canvas link](https://dsva.slack.com/docs/T03FECE8V/F07GPNAHX2B)

**Comment by LynneJohnson224** [comment]
Created a [shell ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/Medical-Records-Phase1-Integration-Release-Plan.md)for the MR rollout plan - please make any and all updates here

**Comment by LynneJohnson224** [comment]
Kick off meeting with Medical Records scheduled for 8/21 1200 pacific/3 eastern.

**Comment by LynneJohnson224** [comment]
Draft canvas complete. Release/implementation plan ready for team to iterate on. No further action items for me right now.
