### ISSUE TITLE
[FE] Add Link to Access the Upcoming Appointments Page for Day-of and Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#89065]
## Wireframes
[Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1889-19465&t=VfR5cZYPsv2WOg9p-4)

## Tasks
- Day-of Check-in
    - Add a link on the Appointments What to Do Next page (see wireframes)
    - Add a link on the You're Checked In page (see wireframes)
- Pre-Check-in
    - Add a link on the Appointments What to Do Next page (see wireframes)
    - Add a link on the Your Contact Information is Up to Date page (see wireframes)

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89065?planning-poker) with Zenhub @brianseek @wullaski

**Comment by brianseek** [comment]
this should just get absorbed into 87872 in my opinion

**Comment by loripusey** [comment]
ok, closing this one, adding info to 87872
