### ISSUE TITLE
[Bug] VMAC Left Nav - Desktop - Several options still clickable after being selected

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#8906]
\[DRAFT: Will finalize details once all pertinent test-runs are done.]

## What happened?
On Staging [VA Pittsburgh health care](https://staging.va.gov/pittsburgh-health-care/) page, many options in Left Nav remain clickable after User has selected them and navigated to selected page.

## Specs:
- All major desktop browsers (Win Edge/IE11, Mac Safari, Win/Mac Chrome, Win/Mac Firefox)
- Unauthenticated experience

## Steps to Reproduce
1.  Go to https://staging.va.gov/pittsburgh-health-care/
1.  In left-nav, under **NEWS AND EVENTS** section, click **Events**.
1.  After **Events** page loads, click already-highlighted **Events** again.
1.  Observe that browser re-navigates to same page.

**NOTE**: This bug occurs with several other left-nav options, but not all.

Here's a **full list** of already-highlighted options that are still clickable \[thus triggering re-nav to same pages]:
- Health Services
- Events
- Stories
- Policies
- Contact Us

### Events option example
![ln-events-click-bug-win-chrome-200507](https://user-images.githubusercontent.com/587583/81365436-f6e93d00-909c-11ea-90b1-dcc461aa89d5.gif)
:

## Desired behavior
Already-highlighted options, after page-navs, should not be clickable, so that re-nav to same pages are not triggered.

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This issue was called out during staging review and needs to be addressed before moving to Prod

**Comment by mmiddaugh** [comment]
@tlei123 this is ready for your review

**Comment by mmiddaugh** [comment]
This issue is resolved.
