### ISSUE TITLE
SOCKS access for Tricia Baker

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#89070]
### Your Name

Tricia Baker

### Your Email

tricia.baker@oddball.io

### Your GitHub Handle

tbaker1026

### Your Role and Team

Product Manager

### Product Manager (PM) name and email

Megan Siddle megan.siddle@oddball.io

### Product Owner (PO) name and email

Matthew Dingee matthew.dingee@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

**Reactivate my access - not sure my SSH Key anymore**

### E-QIP Transmittal Confirmation

<img width="849" alt="2024-07-23_10-07-08" src="https://github.com/user-attachments/assets/9baa5138-cbdd-4228-a564-91b1dea44a5f">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by tbaker1026** [comment]
Need SOCKS to access Drupal - so was not sure what type of access I needed

**Comment by flooose** [comment]
Hi Tricia! If you've had SOCKS access previously, it's probably better to go through [#platform-support in the DSVA Slack](https://dsva.slack.com/archives/CBU0KDSB1). You can reference this issue and they should be able to guide you along, including migrating to the current SOCKS configuration changes. Here's the [guide](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack) to submitting the support request.

**Comment by tbaker1026** [comment]
I was able to have platform support help me with my SOCKS so this one can probably be closed.  Thank you
