### ISSUE TITLE
Update Task Cards to Not Show Bullet Point when there is One Item in the List

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#89076]
## Background
Based on feedback during our last Staging Review, for screen readers it would be better to not use HTML lists when there is only 1 item in the list (i.e. it would not show as a bulleted item).

## Tasks
- Update Task Cards to Not Show Bullet Point when there is One Item in the List

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89076?planning-poker) with Zenhub @brianseek @wullaski

**Comment by loripusey** [comment]
@wullaski @brianseek please estimate

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park This is merged and ready for validation on stage, local, or in the following screenshots.

Pre-check-in multiple appointments
<img width="163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzFWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1cb8f684ebeb1fca3711abfa6d1675f1d50a16d/localhost_3001_health-care_appointment-pre-check-in_appointment-details_0003-0001.png" alt="localhost_3001_health-care_appointment-pre-check-in_appointment-details_0003-0001.png" />
Pre-check-in one appointment
<img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85f0e589e4aa2cd3c60ef951fbd7a586f5140503/localhost_3001_health-care_appointment-pre-check-in_appointment-details_0003-0001%20%281%29.png" alt="localhost_3001_health-care_appointment-pre-check-in_appointment-details_0003-0001 (1).png" />
Day of one appointment
<img width="194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9008c6871aef045da1edcb40cad265d3d91b158e/localhost_3001_health-care_appointment-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%281%29.png" alt="localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (1).png" />
Day-of multiple appointments
<img width="94" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14dbeb9c0ff26dd3fd9f26406ee71561406af532/localhost_3001_health-care_appointment-check-in_appointment-details_0001-0001%20%286%29.png" alt="localhost_3001_health-care_appointment-check-in_appointment-details_0001-0001 (6).png" />

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by brianseek** [comment]
thanks @benbrasso-agile6! closing

**Comment by zach-park** [comment]
Look nice. Thank you!
