### ISSUE TITLE
10-7959c: update hint text for Medicare section

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89071]
figma [link](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1260-85823&t=PHU7lkStyK6TmdNM-0)

Medicare information section: Update hint text for medicare A carrier and B screens

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30997). Waiting on:
- [ ] Team approval
- [ ] Platform approval

|Before|After|
|-|-|
|<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMndIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04f894d7924e9c8bbb9bd76b1e1306635fbef3f7/before.png" alt="before.png" />|<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51c9bc7096ad0d73d79f9647dc32109d04b4b627/after.png" alt="after.png" />|

**Comment by michaelclement** [comment]
@baltes @marywang2 @jamiefiore This has been merged and should be visible on staging shortly. Thanks!

**Comment by marywang2** [comment]
@michaelclement would you please make the same change on the "Medicare Part B" carrier screen? Thanks!

**Comment by michaelclement** [comment]
@marywang2  Just updated in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31041), will have to get approved before it shows on staging but here's a screenshot - thanks!:

<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1d16a051a7d8378594b7dc68ca6cb5c08b80f3d/Screenshot%202024-07-26%20at%2011.45.40.png" alt="Screenshot 2024-07-26 at 11.45.40.png" />
