### ISSUE TITLE
[Bug] 526 Claims: Veteran Filing for Increase in Rating Cannot See Rated Disabilities 

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8908]
## What happened?
Veteran is not able to see their rated disabilities when requesting an increase.  We have confirmed that they do have rated disabilities in the system and have narrowed down the issue to gender not showing up from one of the back end services and being passed down to EVSS.  This is what gets loaded into their profile when they log in.  This has been scrubbed and half is cut off but you can see the NULL gender (and zip).

{"data":{"id":"XXX","type":"users_scaffolds","attributes":{"services":["facilities","hca","edu-benefits","form-save-in-progress","form-prefill","rx","health-records","evss-claims","form526","user-profile","appeals-status","id-card","identity-proofed","vet360"],"account":{"account_uuid":"XXX"},"profile":{"email":"XXX@gmail.com","first_name":"XXX","middle_name":"XXX","last_name":"XXX","birth_date":"XXX","gender":**null**,"zip":**null**,"last_signed_in":"2020-05-07T20:06:42.169Z","loa":{"current":3,"highest":3},"multifactor":true,"verified":true,"sign_in":{"service_name":"idme","account_type":"N/A"},"authn_context":"http://idmanagement.gov/ns/assurance/loa/3/vets"},"va_profile":{"status":"OK","birth_date":"XXX","family_name":"XXX","gender":"M","given_names":["XXX","R"],"is_cerner_patient":false,"facilities":[{"facility_id":"459","is_cerner":false}]},"veteran_status":{"status":"OK","is_veteran":true,"served_in_military":true},"in_progress_forms":[{"fo

We also confirmed the response from (I believe EVSS) comes back:

![Screen Shot 2020-05-07 at 3 33 27 PM](https://user-images.githubusercontent.com/53824125/81373948-30c93c00-90bb-11ea-9bfa-44e398715285.png)

There are two parts to this ticket:
1. Determine why and where we are obtaining a NULL gender and whether this is an issues in one of the downstream databases/APIs.  If this is not our issue, proceed to part 2.
2. Update our back-end code to look for a valid gender that gets loaded into a different part of their profile object.

## Specs:
- Device: (Laptop
- Browser: Chrome
- Test User: N/A, actual veteran

## Steps to Reproduce
Not really possible for us to reproduce since we do not have a test user with a NULL gender.  However, we were able to observe the veteran doing this.

## Desired behavior
They are able to view their rated disabilities. 

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by annaswims** [comment]
[gender is an optional feild for id.me](https://dsva.slack.com/archives/C6WGBD0SW/p1588952677049600). So, if we don't get gender from id.me we should fall back to MVI.

Once this happens we should see errors reduced here:
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116785/events/?query=evss

**Comment by annaswims** [comment]
Rolled back https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-api/4242 due to a circurlar dependency issue.  

Started on a fix that should take care of the issue and then we can unrevert the original PR https://github.com/department-of-veterans-affairs/vets-api/pull/4265

**Comment by annaswims** [comment]
I suspect that SSOe will be rolled out soon and will make this issue far easier to fix. I think that SSOe will provide MVI data more directly.  

SSOe will roll out pretty soon (jut a few more issues to be fixed)

**Comment by annaswims** [comment]
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116861/events/oldest/

**Comment by annaswims** [comment]
the issue for this veteran is that he had a gender in MVI but not in ID.me.  I believe that the SSOe rollout will fix the issue.  They're on an [incremental rollout plan](https://dsva.slack.com/archives/CHPA76VV5/p1591379383425200), at 1% today

**Comment by annaswims** [comment]
same issue as https://github.com/department-of-veterans-affairs/va.gov-team/issues/10400

**Comment by luke-gcio** [comment]
Closing as done and as a duplicate.
