### ISSUE TITLE
GIDS: Generate New Preview Version "are you sure" modal not displaying correctly

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8910]
After a user uploads files to gids, they can generate a new preview version by clicking the "Generate New Preview Version" button. After clicking this button, an "are you sure" modal displays where the user can again click a "Generate New Preview Version" button after reviewing the uploaded files. After clicking the button on the modal, the version is generated.

1. Access https://staging.va.gov/gids/dashboards and log in
2. Observe the modal displayed as part of the page (should be hidden at this point)
3. Upload a file and click the Smaller Generate New Preview Version button that should cause the modal to display
4. Click the larger Generate New Preview Version button that should be displayed as part of the modal
5. User receives error

![Screen Shot 2020-05-08 at 9.08.11 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/46082a59-a5fb-4a4e-bff0-bdea91c905ac)

---

![Screen Shot 2020-05-08 at 9.18.41 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/00dc90c7-0bc2-45ab-89ae-3f308067704b)

---

![Screen Shot 2020-05-08 at 9.23.49 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8dfa1fc2-c531-4871-85ef-cddb838425b5)

**Comment by zurbergram** [comment]
if you put the different env urls below into https://csp-evaluator.appspot.com/ 
you’ll see only staging is affected by the console error message below

- https://dev.va.gov/gi-bill-comparison-tool/
- https://staging.va.gov/gi-bill-comparison-tool/
- https://va.gov/gi-bill-comparison-tool/
- https://dev.va.gov/gids/
- https://staging.va.gov/gids/
- https://va.gov/gids/

**Comment by zurbergram** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1588961257298500

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/652

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/654

**Comment by delli-gatti-michael** [comment]
This is fixed in Staging. Closing this issue
