### ISSUE TITLE
[Feature Request] Update the spacing for Appointment List for (desktop view only) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89119]
## Description
Update the appointment list in desktop mode for Upcoming, Pending and Past list. 

---

## Requirements 

- [x] When the user is on the Upcoming list
       Then the spacing will be updated for desktop users
       And page design matches the [design spec](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=1-52&t=rzxrQfCl3NjjG5jA-0)

- [x] When the user is on the Past list
       Then the spacing will be updated for desktop users
       And page design matches the [design spec](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=1-52&t=rzxrQfCl3NjjG5jA-0)

### Design Assets
[Figma file](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=1-52&t=rzxrQfCl3NjjG5jA-0)

---
### Development Checklist

- [ ] Rename `UpcomingAppointmentLayout` component since it is also used by the past appointment list.
- [ ] update spacing for `RequestAppointmentLayout`
- [ ] update spacing for `UpcomingAppointmentLayout`

 ## Developer Reference
- [ ] [Upcoming list component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/appointment-list/components/AppointmentsPage/UpcomingAppointmentLayout.jsx) `src/applications/vaos/appointment-list/components/AppointmentsPage/UpcomingAppointmentLayout.jsx`

- [ ] [pending list component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/appointment-list/components/AppointmentsPage/RequestAppointmentLayout.jsx) `src/applications/vaos/appointment-list/components/AppointmentsPage/RequestAppointmentLayout.jsx`

## Definition of Done
- [ ] All task criteria are met

**Comment by ldelacosta** [comment]
UX team will do a second review in staging.

**Comment by outerpress** [comment]
Looks great! Validated @jenniemc @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
