### ISSUE TITLE
[BE] 10-10CG - OAuth2.0: (tech debt) carma_client in Form1010cg::Service (use or lose)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89112]
## Background
- Tech note: `carma_client` in the `Form1010cg::Service` [here](https://github.com/department-of-veterans-affairs/vets-api/blob/83b310b7437d0fe913107cba975c468a6b05a864/app/services/form1010cg/service.rb#L39) looks like it is currently unused as we are directly calling the client in the `process_claim_v2!` method. We can probably either remove this or actually use it.

## Tasks
- [x] Refactor the `Form1010cg::Service`  to no longer have methods that are not being used
- [x] Regression test the refactor

## Acceptance Criteria
- The `Form1010cg::Service` no longer has unused methods to ensure that the service is easier to understand, utilize, and support.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that users can submit the 10-10CG form as expected. No regression issues found
