### ISSUE TITLE
Caregivers Final Edits

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#8911]
**Global** 
- [x]  there is a lot of padding around the primary buttons. Reduce padding to 16px around the button label. Same for the “Print his page” button at the end of the application
- [x] For all pages with back and continue buttons, Change the gray arrows in the “Back” button to blue
- [x] If we will have multiple CTA buttons on a page, change to blue instead of green (specifically on the form intro page with subway map)
- [x] consider using the va-introtext styling for the line "We recognize the important role of family caregivers in supporting the health and wellness of Veterans." It feels off with the same weight treatment as the "Equal to VA Form 10-10CG (Application for Caregiver Benefits)". If it used the intro text styling, it may underscore recognition of the importance of caregivers.

**Takeaways from Program meeting**
- [x] Remove modal, update bullet in PFC healthcare
- [x] Remove required label from email address 
- [x] Add required label to Telephone number 

**Intro Page**
- [x] Please update name of paper form to the correct title: IT should be:
Application for the Program of Comprehensive Assistance for Family Caregivers
Equal to VA Form 10-10CG (Application for the Program of Comprehensive Assistance for Family Caregivers)
- [x] Please replace “of” with “for” of program in this line
Follow the steps below to apply for the Program of Comprehensive Assistance for Family Caregivers
- [x] To fill out this application, the Veteran and each family caregiver applicant will need to provide their:

- Address
- Telephone number
- Date of birth
- Social Security Number or Tax Identification Number

You will also need:
- The name of the VA medical center where the Veteran receives care
- Health insurance information for the Primary Family Caregiver

- [x] What if I have questions or need help filling out the form? 
If you have a question or need help, you can contact us in any of these ways:
- Call us at 877-222-8387 and ask for help filling out the form
- Use the online Caregiver Support Coordinator locator to find a coordinator at your nearest VA health care facility
- Contact the National Caregiver Support Line at 855-260-3274 or a Veterans Service Organization to get help filling out the form. 

- [x] Remove [Get help filling out your application] link. Incorporate into Veterans Service Organization in bullets above

- [x] Please change content in **Apply** section to: 

 Please remember, whether you’re the Veteran or a family caregiver, you’ll need to complete all form questions before submitting the form. After submitting the form, you’ll receive a confirmation screen that you can print for your records.

Each time the Veteran wants to add a new family caregiver, the Veteran and the new caregiver will need to submit a new application. There can only be 1 Primary and up to 2 Secondary Family Caregivers at any one time.

- [x] Change **Next Steps** to **Next steps**

- [x] Please change content in **Next steps** section to: 

A member of the Caregiver Support Program at the VA medical center where the Veteran plans to receive care will contact you to discuss your application and eligibility.

If you aren’t eligible for PCAFC you may be eligible for the Program of General Caregiver Support Services (PGCSS). To find out more, call the VA Caregiver Support Line at 855-260-3274, visit www.caregiver.va.gov or discuss your options with your local Caregiver Support Coordinator.

**Medical Center Page**
- [x] Change page header to: 
VA medical center
- [x] Change content to: 
A Caregiver Support Coordinator at this VA medical center will review your application (second paragraph) 
- [x] ❓ Change select box to: 
VA medical center (required)
- [x] Remove "Additional info" component 
- [x] Add copy: 
Note: Please choose the medical center or clinic closest to your home.
- [ ] The text input for the name of the medical facility should be wider to accommodate the length of facility names without cut-off. This may also be an issue for the VA Medical Center dropdown further down the page. Name of the facility should not be cut off in the selected state. The text inputs for the Veteran and Caregiver information are all longer than those provided for VAMC names. Just as the size of a Zip Code input is smaller than that of a street address, it is standard practice to size text inputs sufficiently to allow someone to see the content they're inputting without cut-off, when possible.

**Primary Family Caregiver** 

- [x] Please remove the modal on the Primary Family Caregiver definition and include this in the dropdown:
What’s a Primary Family Caregiver? 
[Expanded learn more]
A family member (defined herein), who is designated as a "primary provider of personal care services" under 38 U.S.C. §1720G(a)(7)(A); and who meets the requirements of 38 C.F.R. §71.25.

A Primary Family Caregiver is the main caregiver for the Veteran. They can be the Veteran’s or service member’s:
- Parent
- Spouse
- Significant other
- Son or daughter
- Step-family member
- Extended family member
- Non-family member who lives with the Veteran or service member, or will do so after approval.

- [x] Proximity of links — accessibility issues: Mobility – Interaction design best practice
The Learn more about what this means link is close to the legal statute link and may introduce errors. Interaction design best practice would recommend 1.5rem space between, in this case 24 pixels.
- [x] Please change "What is the Primary Caregiver’s relationship to the Veteran (not with)"
- [x] ❓ Remove placeholder text in the phone number fields which must be removed to align with the VA Design System. 

**Health care coverage page** 
- [x] Change page header to: "Health care coverage" 
- [x] Check that we have the updated content and style for the health care coverage radios (add CHAMPVA link) 
- [x] Please change additional health insurance label to: 
Name of health insurance (if there are multiple policies, please separate them with commas)
- [x] Check that we have the correct errors for the health care coverage radios

**Secondary Family Caregiver** 
- [x] Please remove the modal on the Secondary Family Caregiver definition and include this in the dropdown:
What’s a Secondary Family Caregiver?
[Expanded learn more]
Secondary Family Caregivers are people approved as a “provider of personal care services” for the eligible Veteran under 38 U.S.C. 1720G(a)(7)(A); meets the requirements of 38 C.F.R. 71.25; and generally serves as a backup to the Primary Family Caregiver.
They can be the Veteran’s or service member’s: 

- Parent
- Spouse
- Significant other
- Son or daughter
- Step-family member
- Extended family member
- Non-family member who lives with the Veteran or service member, or will do so after approval

- [x] "Please update this label:
What is the Secondary Family Caregiver’s relationship to the Veteran (not with)"
- [x] ❓ Please make the following sentence bold:
You can have up to two Secondary Family Caregivers.

**Secondary Family Caregiver (2)**
- [x] For the Secondary Family Caregiver (2) information, each of the information fields should include the (2) to provide consistent identification 

**Review** 
- [x] Move the legal notice from the top of the page to the bottom and update the language:
According to federal law, there are criminal penalties, including a fine and/or imprisonment for up to 5 years, for withholding information or for providing incorrect information. (See 18 U.S.C. 1001)
- [x]  Please add the sentence "I have read and accept the privacy policy" to each statement of truth
- [x]  For Statement of truth text input labels —  should be ""Enter Veteran or service member's full name" 
- [x] Update "sign and date" on signature page to just "sign"

**Confirmation Page**
- [x] Add to second paragraph of "What happens after I apply?
"If you aren’t eligible for PCAFC you may be eligible for the Program of General Caregiver Support Services (PGCSS)."

**Print style sheet** 
- [x] "Please update this line to make it active voice:
We’ve received your application"
- [x] "Please make “Applications” singular
Application details"

**Comment by psanders86** [comment]
All content changes in the Github ticket are reflected by highlighted text in this word doc that was approved by the program team on 5/11/20

[10-10CG Content Word Document  FINAL FOR STAGING 5.12.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4617576/10-10CG.Content.Word.Document.FINAL.FOR.STAGING.5.12.20.docx)

**Comment by jonathanjnelson** [comment]
Awesome work, Justin.

- [ ] Intro Page: Please update content

**Original Copy:** Equal to VA Form 10-10CG (Application for the Program of
Comprehensive Assistance for Family Caregivers)

**New Copy:** Equal to VA Form 10-10CG (Application for Family Caregiver Benefits)

<img width="692" alt="Screen Shot 2020-05-15 at 2 03 28 PM" src="https://user-images.githubusercontent.com/58444931/82086992-e6e0e700-96b4-11ea-9aaa-3917875f276e.png">

- [ ] Interior form headers: Change “Application” to “Apply”

**Original H1 Copy:** Application for the Program of Comprehensive Assistance for Family Caregivers

**New H1 Copy:** Apply for the Program of Comprehensive Assistance for Family Caregivers

<img width="758" alt="Screen Shot 2020-05-15 at 2 05 25 PM" src="https://user-images.githubusercontent.com/58444931/82087156-28719200-96b5-11ea-9aee-95fc36515a24.png">

- [ ] Health coverage page: Please update content

**Original Copy:** Is the Primary Family Caregiver currently in enrolled in Medicaid? 

**New Copy:** Is the Primary Family Caregiver enrolled in Medicaid? 

<img width="596" alt="Screen Shot 2020-05-15 at 1 02 21 PM" src="https://user-images.githubusercontent.com/58444931/82087867-923e6b80-96b6-11ea-9ef8-a760b890e9aa.png">

- [ ] Add period after "commas"

<img width="669" alt="Screen Shot 2020-05-15 at 2 25 11 PM" src="https://user-images.githubusercontent.com/58444931/82088756-f150b000-96b7-11ea-9538-429a294895ba.png">
