### ISSUE TITLE
Understand numbers of new and returning user sessions to MHV on VA.gov portal

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89113]
### User story
As a Cartography team member, I want to understand how many sessions are first-time users of the MHV-on-VA.gov portal versus returning users.

### Notes
- GA4's out of the box (OOB) behavior doesn't suit our purpose (focus on MHV portal exclusively)
- Also, OOB "returning" probably will only have visibility back to GA4 implementation around Feb 2024
- [Slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1724694032308319?thread_ts=1724687100.371079&cid=C1Q4294JJ) with Jamie Stutt re whether GA can know whether a user has been on the MHV portal (/my-health/) before. May require implementation of a "custom dimension."
- Update 9/30: Robyn thinks we have to use DD for this because it would take so long to get a custom implementation from the Platform Analytics team

Possible tasks:
- correspond with Jamie about custom dimension idea

## Acceptance criteria
- We can count sessions of new and returning users on the portal on VA.gov
- If possible, segment an Explore report by new/returning (to MHV portal specifically)
- Reviewed with Robyn

**Comment by wesrowe** [comment]
I played around with Segments in GA4 explore reports – the reports are side-by-side, which I don't love. See first tab of [this exploration](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/dvxmtHCqTaaeZKalrojazw).

I tried to use Comparisons (in the Pages and Screens report), but couldn't find the `first_visit` event in the comparison builder. Would love for this to work though! Will ping Jamie in #vfs-analytics.

**Comment by wesrowe** [comment]
Forgot to update... Jamie doesn't believe what we're trying to do is possible in GA. The exploration I linked above relies on GA4's OOB "new user" functionality, which means "new users for the GA property/domain." It can't be tailored to a subset of pages, i.e. the /my-health/ section of the site. So for example, someone who visited the unauthenticated Health care hub (/health-care/) last month and logs into /my-health/ for the first time today will be seen today as a return visitor.

**Comment by wesrowe** [comment]
I just poked around Datadog, looking for a way to see this. I found [this out of the box report](https://vagov.ddog-gov.com/rum/sessions?query=%40type%3Asession%20%40application.id%3A1f81f762-c3fc-48c1-89d5-09d9236e340d%20%40session.type%3Auser&agg_m=count&agg_m_source=base&agg_q=%40usr.id&agg_q_source=base&agg_t=count&fromUser=false&refresh_mode=sliding&top_n=1000&top_o=top&track=rum&viz=query_table&x_missing=true&from_ts=1728599910058&to_ts=1728686310058&live=true), which is coming pretty close because it shows **how many sessions each unique user has had.** Note that the top row's "blank user id" gets 13k.

<img width="1024" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f12947de3820b8b3d02059d1b2be4dd2b700656/image.png" alt="image.png" />

**Comment by wesrowe** [comment]
Based on the report/screenshot above:
- It says above table "based on 11.2k sessions." But 11.23k sessions _had no userID field._ Can I use a csv export or something to total up the sessions that DID have userIDs and see if these numbers make sense? (ie, are the sessions w/ID few enough so the rounded total is still just '11.2k'?)
- Is this report really from the past 1 hour? Does that mean that an actual user initiated 45 sessions in an hour? To answer, would need to review the Actions from each session.

**Comment by wesrowe** [comment]
I have a [slack thread](https://datadoghq.slack.com/archives/CHK12ELBG/p1730131677696449?thread_ts=1729721168.663429&cid=CHK12ELBG) going on the public DD slack; Egor has provided some clues about how to check if our implementation has an issue. Anyone can sign up for this slack and participate.

**Comment by dcloud** [comment]
Per engineering refinement, this could be multiple tickets

1. investigate why the app may be missing >50% userIDs
  - Are privacy tools able to block user id while still allowing DDG to record something?
  - Is code not reliably setting userId when an id becomes available?
  - Other possible reasons we might see (authenticated) users in DDG without the anonymous unique identifier
3. solution for tracking new vs returning users (presumably using global context)
  - DDG doesn't have a mechanism to do this, appearently?

**Comment by wesrowe** [comment]
Meanwhile, I'm pursuing the possibility that BigQuery could produce new/return stats from GA data. I filed a ticket with the Analytics team about it: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96473.

**Comment by wesrowe** [comment]
As time has worn on and we've exhausted options for this, Robyn finally threw in the towel in a DM to me on 12/10. Her view is that this metric is not as interesting now that we have a clear, rapidly approaching date for Veterans to be forced to use VA.gov. Closing.
