### ISSUE TITLE
[Toxic Exposure 1.0] Documentation about how to remediate 526 upload failure using the benefits intake API

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#89121]
As a user I want to be able to remediate the 526 upload failure for a submission.
This is part of the backup path. This already exists, we just need to put together a plan on how to use it. This is manual process for now. Engage Carbs on this as needed.

Add to these remediation steps
https://github.com/department-of-veterans-affairs/va.gov-team/blob/ca7b16292e7a5cc46cc2aa106227f8af61fdd349/products/disability/526ez/lighthouse_submission_remediation.md

## Tasks
- Find workflow for submitting a submission via the benefits intake API
- Test the methods to ensure they function as desired and confirmation that it works
- Write SOP documentation

## Acceptance Criteria
 - [ ] **Scenario: User can access documentation on remediating 526 upload failures**
  - Given the user has access to the documentation
  - When the user searches for information on remediation of 526 upload failures
  - Then the user should find clear instructions and guidance on using the benefits intake API to resolve the issue

**Comment by tommasina-va** [comment]
Captured work here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/lighthouse_submission_remediation.md
