### ISSUE TITLE
[Terraform] Update VPI to use latest Terraform and Terragrunt

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#89132]
# Description
Referencing the latest successful Terragrunt Nightly build, update the repo to use the latest version of Terraform as well as Terragrunt

# Notes
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/actions/workflows/terragrunt-nightly.yaml
- https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvsp-platform-infrastructure%201.8.5&type=code
- https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvsp-platform-infrastructure+v0.59.3&type=code

![Image](https://github.com/user-attachments/assets/1f6a2ff3-26e6-4c62-810d-9faa97c3bf97)

![Image](https://github.com/user-attachments/assets/9af46daf-b5b6-457e-922c-4230f7ac2a94)

# A/C
- [x] EKS `next` cluster deploys using latest Terraform
- [x] EKS `next` cluster deploys using latest Terragrunt

**Comment by Efe-Oddball** [comment]
Pushed out a PR for this update. Will be moving the ticket to review state and resolve when PR is merged.

**Comment by Efe-Oddball** [comment]
This ticket has been completed and will be moved to a closed state
