### ISSUE TITLE
Add OCTO PowerPoint template to research findings page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#89138]
### Description

Recommend adding a link to a PowerPoint template for research presentation readouts. Add the template in the `Quick Resources` list of artifacts.  

https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesize-and-share

### Relevant URLs

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS / Unified Appointment Experience / Check-in and online scheduling

**Comment by jknipes** [comment]
Hi @benbrasso-agile6 , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by benbrasso-agile6** [comment]
Thank you!

**Comment by jknipes** [comment]
The page in the description of this issue has changed to [Synthesize and Share](https://depo-platform-documentation.scrollhelp.site/research-design/synthesize-and-share).
@naomimarcussen is there a Power Point template for research presentation readouts that could be added to this section?

**Comment by naomimarcussen** [comment]
Thanks for the updated page @jknipes. I've added a link to the Power Point template to the Design Canvas along with the Google Slides to keep things together.

**Comment by jknipes** [comment]
@benbrasso-agile6 please see previous comment. We are considering this issue resolved and closing this ticket as _Done_. Please submit a new request if there are any further issues. Thank you!
