### ISSUE TITLE
[Feature Request] Remove feature toggle va_online_scheduling_status_improvement_canceled 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89130]
## Description
We will no longer need the feature toggle `va_online_scheduling_status_improvement_canceled`. We will need to remove the toggle from the flipper list and the code. 

---

## Requirements

- [ ] Remove `va_online_scheduling_status_improvement_canceled` from the flipper list and the application code. 

### Design Assets
Not applicable 

--- 

## Development Checklist

- [ ] Task 1
- [ ] Task 2

### Developer Reference
- [ ] [Swagger file]() if applicable
- [ ] [File page]() if applicable

### Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89130?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
The flag has been removed from all environments now. Ready for validation after [docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) are updated @jenniemc

**Comment by ldelacosta** [comment]
No issues to address. Closing out the ticket.
