### ISSUE TITLE
Add a feature toggle for OH Scheduling 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89139]
## Description
We will need to create a feature toggles for the OH scheduling work.  

---

## Requirements

- [ ] Add `va_online_scheduling_OH_direct_schedule`
- [ ] Add `va_online_scheduling_OH_request`

### Design Assets
Not applicable 

--- 

### Acceptance Criteria: 
- [ ] The toggles are created for VAOS

### Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89139?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
Validated and no issues to report. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm9ZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dfb5ee2832579c60ecd6a9a275ac9216ffd0948/Screenshot%202024-07-29%20at%201.33.14%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 1.33.14 PM.png" />
