### ISSUE TITLE
Confirmation email template updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89144]
Update confirmation email that is being sent for 10-7959f-1:

- call center hours are different for FMP (8:05-6:45 ET)
- there are no supporting docs so we should remove file count (or are we counting the form itself here?)
  - (for 10-10d, if there is only 1 document, can it read 'document' singular rather than plural)
- form name should have a lower case 'f'
- sentence case copy in the grey box ("Your application details", "Date submitted", etc.)
- remove the bottom contact info (since it contradicts the earlier copy)
- 

Also add templates for each form

<img width="805" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBendIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25c7853f507e0d3f1740c23536e58348c34c91de/image.png" alt="image.png" />

**Comment by balexandr** [comment]
Update: We will be using multiple templates now to keep things kosher

**Comment by balexandr** [comment]
Staging template PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3057

**Comment by balexandr** [comment]
@baltes Submitting the F-1 form and got the right template.
<img width="710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ZEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59eee9f8557d57b7751a539d34162aefd51ed9b2/Screenshot%202024-08-08%20at%202.57.37%E2%80%AFPM.png" alt="Screenshot 2024-08-08 at 2.57.37 PM.png" />
