### ISSUE TITLE
“Forgot your password?” on GIDS login page

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#8914]
Steps to reproduce

1. Navigate to https://dev.va.gov/gids/user/sign_in
2. Select "Forgot your password?"
3. Enter in email and select "Send me password reset instructions"
4. Error below

![Screen Shot 2020-05-08 at 11.55.25 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/78ce826f-a2a5-4745-b326-336a2cd6c4c2)

**Comment by zurbergram** [comment]
http://sentry.vfs.va.gov/share/issue/d82e1c5e75134eb4b3de1b6e75174395/

**Comment by zurbergram** [comment]
```
Faraday::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain))
```

**Comment by zurbergram** [comment]
From the rails console of a instance in the docker container
```
bundle exec rails c production
u = User.find_by(email: 'email@whatever.com')
u.send_reset_password_instructions
```

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/7121 appears to have fixed the issue in https://dev.va.gov/gids/

**Comment by zurbergram** [comment]
This issue occurs in staging and prod as well

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/7154 appears to have fixed the issue in https://staging.va.gov/gids/

**Comment by zurbergram** [comment]
http://va.gov/gids/ is working as well

**Comment by sonntag-adam** [comment]
This is working now. Was able to reset without error.
