### ISSUE TITLE
[Tech Debt] Document Flipper Usage

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#89165]
## Summary
Scattered around our code base are dozens of different feature flipper toggles.
Understanding what flippers we have and which ones could be removed would help with code cleanup.

## Story
To that end: 
As a tech lead
I need a list of the all the flippers associated with the Disability Claim (526EZ) application 
So that I can create and prioritize tickets for removing no longer needed code

## Acceptance Criteria
Fill out this table as best able (here or in linked spreadsheet)

| Flipper Name | Link to usage in Github | Status in Staging | Status in Production | Recommendation |
|---|---|---|---|---|  

## Breadcrumbs
[Flipper Documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)
[Staging Flippers](https://staging-api.va.gov/flipper/features)
[Prod Flippers](https://api.va.gov/flipper/features)
[Website Flipper Config](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/feature-toggles/)
[API Flipper Config](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml)
[Website Code Entrypoint](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/all-claims)
[API Code Entrypoint](https://github.com/department-of-veterans-affairs/vets-api/blame/master/app/controllers/v0/disability_compensation_forms_controller.rb)

**Comment by tblackwe** [comment]
Another valid approach:
Go through the flippers in https://api.va.gov/flipper/features looking for ones that look like they are in the 526 space. You'll end up looking at other teams code as well this way

**Comment by ajones446** [comment]
Documented in [Flipper Usage for Disability Claim (526EZ)](https://docs.google.com/spreadsheets/d/1aLh7a-Q8kt8yULSepveL4dJqbcDQrfw-nw6kx2SHKD0/)
