### ISSUE TITLE
Requested updates to VET TEC program page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8916]
## User Story or Problem Statement
As a Veteran, I need to get the most up to date information on VA VET TEC educational program benefit.

New request from Tammy Hurley, covering 3 pages:

1. To the main GI Bill page, add a new link taser under "More benefits" at the bottom. 
https://www.va.gov/education/about-gi-bill-benefits/
Unedited suggested copy from Tammy: Title: Veterans Technology Education Courses (VET TEC) 
Hyperlink: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/

Blurb: If you want to gain computer experience to start or advance your career in the high-technology industry, VET TEC program matches you with a leading training provider to help you develop high-tech skills.  Find out it you are eligible.

2. To main Post-9/11 GI Bill page, add link and link text.
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
Placement: Under H3: How can I use my Post-9/11 GI Bill (Chapter 33) benefits?
Under "Train for a specific career"
Unedited copy suggested:
Hyperlink Title: Veterans Technology Education Courses (VET TEC)
Hyperlink: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/

3. To main VET TEC page
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/
A. Add information and new link directed to providers, in addition to the language we have addressing Veterans, under H3 Vet Tec training providers. Will set copy up to have one section For Veterans, and another For providers. 
Unedited suggested text: 

Text: If you are a Training Provider that is interested in the VET TEC Program and giving Veterans the high-tech skills sought by today's top employers so they can acquire meaningful employment, please visit our Training Provider website to learn more and apply.

A provider is considered “preferred” if the training facility agrees to refund tuition and fees if a student doesn’t find meaningful employment within 180 days of completing the program.

Hyperlink: https://www.benefits.va.gov/GIBILL/fgib/VetTec_Providers.asp
Hyperlink Text to apply this to: Training Provider website to learn more and apply

B. Move Content:
"How can I show that I've completed the program?" section above "VET TEC Training Providers" section on va.gov page

C. Request for an alert on the page saying the program is projected to be out of money by May 27, 2020. Need to ask, through, Tammy for SMEs to clarify the bolded. Copy is not yet edited:

**VA projects that VET TEC funding will run out by May 27.  VET TEC is subject by law to a $15 million annual budget. 

If this happens, VA will no longer accept new VET TEC student enrollments until we can get more funding, or until the fiscal year starts on October 1, 2020.  Veterans currently enrolled can continue with their training uninterrupted.

We will continue to accept and make determinations on Veteran and Training Provider applications during this time. Please regularly check this page for updates.**

The third paragraph seems like it contradicts the one above it. Tammy advised I edit/revise and build the alert, but then send her Prod previews of all the pages with my question to clarify if applications are, or are not, being accepted after May 27. Or if we'll continue accepting applications for the new fiscal year starting October 1.

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  -- FYI I'm unclear on the exact requests above - what is new, what and where is the new content needing to go, etc. The word doc they sent does have one screen shot, and that looks like they'd like a link to VET TEC in the list indicated, which seems fine. But the rest of the copy listed in the word doc needs a little more context.

[Original notes requests for VET TEC page updates]
(https://app.zenhub.com/files/133843125/a0e10435-1b3b-47e4-beb6-ab1b9cc7eedb/download)

**Comment by AnneHurley** [comment]
@RLHecht Here are the three prod links for these pages. Note that I have made an assumption in the content in the alert box in the last paragraph and have question in to Tammy H to validate. 

About GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=915
Post-9/11 GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=935
Main VET TEC page: http://preview-prod.vfs.va.gov/preview?nodeId=930

Ready for your copyedit; any suggestions on making the alert box headline less unwieldy very welcome. 

@stephorkandatx @DanielleThierryUSDSVA @jenniferlee-dsva  FYSA

**Comment by RLHecht** [comment]
@AnneHurley These three pages are now copyedited. One question I had on the Post-9/11 GI Bill page is if we need to add (VET TEC) into the new text for SEO purposes.

**Comment by AnneHurley** [comment]
@RLHecht Good question - I assumed since we didn't have it in the H1 on the main page we didn't need it, but I'll look at our SEO doc to doublecheck.

**Comment by AnneHurley** [comment]
@RLHecht  Interestingly, this page is not fleshed out on the master SEO spreadsheet (attached). So I think we probably should match the H1 - the program is pretty new so not sure how many people are using the acronym. I think it's fine to use in blurb/copy/intro, though. @DanielleThierryUSDSVA  FYSA 
[VA.gov SEO spreadsheet July 2019]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4629383/VA.gov.SEO.spreadsheet.7.15.19.1.xlsx)

**Comment by AnneHurley** [comment]
@RLHecht I added (VET TEC) to that link ^ - and now all the pages are updated. @DanielleThierryUSDSVA  FYSA - Welcome your read of this as well, but the changes in the program are effective next week, so we'd like to get this live asap. If you want to do a read, please do; if not, Randi can push live. I'll also slack you.

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  if you have time to review this new alert today before daily deploy that would be great. If not, @RLHecht  has reviewed/approved: http://preview-prod.vfs.va.gov/preview?nodeId=930

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA 
Here is the new original text sent by stakeholders:

Due to the utilization of all available funding allotted for the program, VET TEC cannot support training for new participants until October 1, 2020. Individuals may still apply for a VET TEC Certificate of Eligibility in order to receive a formal eligibility decision for a program that begins on or after October 1, 2020. 

Suggest:
Because of the popularity of the VET TEC program, we've spent all the money available for the current fiscal year. We're still accepting eligibility applications for a program that begins on or after October 1, 2020. 
If you're currently enrolled, you can continue your training uninterrupted.
Please check this page for program updates.

**Comment by DanielleThierryUSDSVA** [comment]
For consideration:

Because of the popularity of the VET TEC program, we've used our full budget for the current fiscal year and can't accept new enrollments until October 1, 2020. You can still apply to receive a decision for a program that begins on or after October 1, 2020.

If you're currently enrolled, you can continue your training uninterrupted.

Please check this page for program updates.

**Comment by RLHecht** [comment]
This page has been validated on the live site. Closing ticket. FYSA @stephorkandatx
