### ISSUE TITLE
GIBCT: Calculations not occurring on page load for VETTEC institutions

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8917]
After selecting a program from the VETTEC search results, the Program Name and Tuition and Fees information should be pre-populated in the Your estimated benefits box. Currently, the box only displays "TBD" on page load.

## AC
1. Program name and tuition and fees information are displayed in the Your estimated benefits box on page load

### Current
![Screen Shot 2020-05-08 at 2.55.31 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a44484ef-f889-40da-811a-1843dbf31262)

### Expected
![Screen Shot 2020-05-08 at 2.55.57 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d03ba4a0-bb11-4a29-a4d5-dd5897c1e750)

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12600

Branch: bah-7842-2

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes live in staging. closing this issue
