### ISSUE TITLE
CT-EYB: Update profile page mobile layouts

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8918]
As a developer, I need to update the mobile spacing and fonts so that layout and usability is better on mobile devices.

## Assumptions:
1. This work is completed behind the EYB feature flag #7780.
2. All of these issues are on a mobile viewport.

## Acceptance Criteria
The mobile bottom sheet behavior:
1. The speed at which the bottom sheet slides into view matches the speed at which the bottom sheet slides out of view.
2. When the bottom sheet is expanded, it acts as a modal, preventing interaction with the page behind.
3. The text labels do not wrap on displays at a 320px width resolution.
4. The following bottom drawer items have the font H4 Bitter Bold:
    a. "Your estimated benefits" title label
    b. "Estimated benefits per month" title label
5. The following bottom drawer items have the font H5 Bitter Bold:
    a. Collapsed bottom sheet: "Your estimated benefits" label
6. The following bottom drawer items have the font Source Sans Pro at 16px:
    a. "Housing allowance:" amount label
    b. "Book stipend" amount label
    c. "Housing allowance" title label
7. The spacing between each bottom drawer label between "GI Bill pays to school" and "Total paid to you" is 12px.
8. Drop Shadow is 15%
9. The bottom sheet slides out of view when "Calculate benefits" button is in full view above bottom sheet.

## Supporting Artifacts:
**AC3:**
![AC3](https://user-images.githubusercontent.com/48260534/81439785-eb4d5300-913c-11ea-813c-a8be8879071d.png)
**AC4 & 5:**
![AC4](https://user-images.githubusercontent.com/48260534/81439787-ec7e8000-913c-11ea-8e3d-665077a337a0.png)
![AC4 5](https://user-images.githubusercontent.com/48260534/81439789-ed171680-913c-11ea-8cf1-c1d54955adca.png)
![AC5](https://user-images.githubusercontent.com/48260534/81439790-ed171680-913c-11ea-8b96-3ec721484190.png)
**AC6:**
![AC6](https://user-images.githubusercontent.com/48260534/81439791-edafad00-913c-11ea-9520-104c7c62f8a1.png)
<img width="494" alt="AC9" src="https://user-images.githubusercontent.com/48260534/81439793-edafad00-913c-11ea-880a-621b385776de.png">

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12675

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-18 at 10.58.50 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3ac1fd1c-f7ed-4075-b388-2dafe102b1f1)
##
![Screen Shot 2020-05-18 at 10.58.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8aa872fa-e095-472d-80af-41978f12ff08)
##
![Screen Shot 2020-05-18 at 10.59.09 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/220ae417-2b69-4e33-87cc-7f9ea0dd01d4)
##
![Screen Shot 2020-05-18 at 10.59.16 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5b31c10e-8e83-4408-aafa-ffd3af684d2e)
##
![Screen Shot 2020-05-18 at 11.03.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d4e5af2b-7f01-41b2-bc9c-3635f803cb38)
##
![Screen Shot 2020-05-18 at 11.03.55 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/469f078e-4063-45e2-875b-2f925f76a8e7)
##
![Screen Shot 2020-05-18 at 11.04.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3891c486-813f-488f-9201-6b0dab20326b)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-19 at 10.51.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5ffe1b17-6839-4577-965e-8750c4581d4d)
##
![Screen Shot 2020-05-19 at 10.52.22 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8162e98e-0843-4e25-bbf4-6c7134090204)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-19 at 10.54.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1073735c-2de8-4a2c-83f7-3b37b5231710)
##
![Screen Shot 2020-05-19 at 10.54.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1b68d58c-d27e-4ccc-a829-6b28fef73c46)
##
![Screen Shot 2020-05-19 at 10.54.42 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/be2e3057-d9f1-4df9-a53c-4f54ea2864ff)
##
![Screen Shot 2020-05-19 at 10.54.49 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/89fd37b3-fcd7-4676-9d84-b66042151f26)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-19 at 10.56.44 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b21a9ae6-24eb-46f2-91b6-284e3165e185)
##
![Screen Shot 2020-05-19 at 10.56.51 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3d5df739-84b4-4ada-95c8-d09f27917695)
##
![Screen Shot 2020-05-19 at 10.56.56 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bf2db1c2-4af1-4794-8eaa-35e24ad5cef4)
##
![Screen Shot 2020-05-19 at 10.57.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f2a65017-b8b0-49de-a4e0-7ba450efe264)

**Comment by sonntag-adam** [comment]
AC 7. The spacing between each bottom drawer label between "GI Bill pays to school" and "Total paid to you" is 12px. It is confirmed to be correct through demo and local testing. There is natural padding that a screenshot won't be able to show a 12 px exact number.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-19 at 11.38.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c3d14d80-d5f5-43fe-802e-8cfc40dcca67)
![Screen Shot 2020-05-19 at 11.39.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/77534a93-1a97-4cd8-a8c2-bd5448e69793)

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/82349619-582bdd00-99c8-11ea-941b-3dd435ed7f01.gif)
##
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/82349656-62e67200-99c8-11ea-84c3-459448d78779.gif)

**Comment by sonntag-adam** [comment]
The story is blocked by https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8981 as this needs to go in for AC 9 and 10 to pass

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/410&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review.

**Comment by ccruzgra** [comment]
@sonntag-adam UXers took a look and this checks out!

**Comment by sonntag-adam** [comment]
Closing story.
