### ISSUE TITLE
10-7959c: Copy updates/design QA (signer and review)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89183]
[figma link](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1155-73969&t=JMkoJgz24UZdROlA-0
)
url: https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/form-signature 

Signer Information
- Change "Signer information" to "Form signature" in the stepper

url: https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/review-and-submit

Review
- Change "Signer information" to "Form signature" in the accordion
- Add the "Review and sign" header
- Change "Review application" in the stepper to "Review form"

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31013). Waiting on:

- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes @marywang2 This has been merged and will be visible on staging shortly. Thanks!

**Comment by jamiefiore** [comment]
@michaelclement @marywang2 looks like the heading on the Form signature page changed too but it's supposed to be "Signer information". Only the stepper is supposed to read "Form signature" The rest of the changes look good. Thanks!

**Comment by michaelclement** [comment]
Reverted in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31051). Thanks @jamiefiore 

<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--480d86e8ec6b56c5b452fbd8a25157f6c62c6864/Screenshot%202024-07-26%20at%2015.48.48.png" alt="Screenshot 2024-07-26 at 15.48.48.png" />

**Comment by michaelclement** [comment]
@baltes @marywang2 The above screenshot shows the change Jamie recommended; it's implemented on staging. Thanks!

**Comment by marywang2** [comment]
@jamiefiore pls take a look, but this looks good to me.
