### ISSUE TITLE
Platform Orientation feedback ticket from Governance team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89191]
This ticket is for reporting to Governance the state of all materials referenced in the Platform Orientation process. If you have any questions or concerns, please contact Governance team on Slack using the @platform-governance-team-members group on the #platform-team channel. Thank you. 

- [ ] Update title of ticket with your teams name

## ALL Platform Teams
- [ ] Review the [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)
- [ ] Review the [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team%2C+platform-tech-team-support&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
- [ ] Verify all links/references are accurate
   - [x] If a broken link or wrong reference is identified, please include details below:
      - New VFS Team Member Template: All three "Accessibility orientation" links link to the correct page but don't skip down to the accessibility section.
      - Watch the getting started with design videos (remove)
      -  Watch the Design orientation recording/Watch the Accessibility orientation recording (make jump links to specific orientations)
      -  The links to the QA Orientation in the New Team Member Template have a typo in the anchor, so they don't jump to the QA section
- [ ] Verify there are no gaps in what new team and team members need to know about Platform
   - [ ] If a gap is identified, please include details below:
- [ ] Make recommendations and/or suggestions for improvements to Platform orientation
   - [ ] If your team has recommendations or suggestions, please include details below:

## Governance team
- [ ] Watch the [Design & Research](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Design&ResearchOrientation) and verify content is up to date and accurate. 
   - [ ] Video is up to date and accurate
   - [x] Video is not up to date and Governance team will rerecord.
     - Ticket number: #89428
- [ ] Watch the [QA Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAOrientation) and verify content is up to date and accurate.
   - [x] Video is up to date and accurate
   - [ ] Video is not up to date and Governance team will rerecord.
     - Ticket number:
- [x] Watch the [Accessibility Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AccessibilityOrientation) and verify content is up to date and accurate. 
   - [ ] Video is up to date and accurate
   - [x] #89424
     - Ticket number: #89424
     - Notes: Couple of times when I refer to things that are "coming soon" -- new VA.gov Experience Standards, enforcing WCAG 2.2, etc. Plus it would be good to highlight some of the newer accessibility guidance now available, like Jeana's [spectacular documentation on accessibility annotations](https://design.va.gov/about/accessibility/accessibility-annotations)

**Comment by briandeconinck** [comment]
Completed my review. Will need to re-record the accessibility orientation. Blank ticket created.

**Comment by allison0034** [comment]
Design & research complete. Blank ticket created.

**Comment by it-harrison** [comment]
@shiragoodman QA is good until we introduce Endpoint Monitoring

**Comment by it-harrison** [comment]
@shiragoodman left a comment on QA link in New Team Member template

**Comment by shiragoodman** [comment]
Governance team completed all tasks associated with this request. Closing.
