### ISSUE TITLE
VET TEC Profile page section headers shifted right

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8919]
On smaller screens (ex. iPhone 5) the headers on the VET TEC profile page (Approved programs, Estimate your benefits, etc..) are shifted to the right. The headers should behave the same way they do in production and have the same amount of padding on either side.

## AC
1. Headers have the same amount of padding on either side as they do in production

### Current (dev)
![Screen Shot 2020-05-08 at 3.02.45 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e8638e3c-4273-4779-b43d-6c2b183f376e)

### Expected (production)
![Screen Shot 2020-05-08 at 3.02.05 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/0b11b08a-493b-4524-b101-793a71f02e2e)

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12600

Branch: bah-7842-2

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes live in staging. Closing this issue
