### ISSUE TITLE
Figma design for VA Health Chat MVP

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#89210]
### User story

As a Veteran, I want to be informed about access to VA Health Chat and to understand what to expect before I engage with it.

### Notes
- Introduced by Kaitlin [via Slack](https://dsva.slack.com/archives/C0581MN69TJ/p1718992485674069)
- Add notes from meeting with "trio" on Monday

Possible tasks:
-

**Comment by wesrowe** [comment]
closing as dupe
