### ISSUE TITLE
File intake with VA Profile for NoK edit

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#89219]
### User story

As a Cartography team member, I want to get the VA Profile team engaged with our addition of edit functionality to Health care contacts on VA.gov, so that they can help us plan the integration.

### Notes
- Intake is thought to be the first step for getting the integration off the ground.

### Tasks
- 

## Acceptance criteria
- VA Profile team has acknowledged our request for this new phase of our project

**Comment by LynneJohnson224** [comment]
Reached out to Jeff Barnett on MS Teams re: submitting an intake request to kick off this effort

**Comment by LynneJohnson224** [comment]
Reached out to Thomas Trafficante on MS Teams re: submitting an intake request to kick off this effort

**Comment by LynneJohnson224** [comment]
Submitted intake request - Jira ticket CMDMRP-8451

**Comment by LynneJohnson224** [comment]
Intake request acknowledged by Thomas Trficante - the intake team is analyzing the request and will reach out for more information in the next few business days if needed.

**Comment by LynneJohnson224** [comment]
Thomas Traficante to set up meeting with VA Profile and Cartographers to discuss intake request. FYI @wesrowe the timeline section of the request was left blank and this may come up at the meeting - may want to have a rough roadmap for this effort.

**Comment by wesrowe** [comment]
This can close. It's not clear ATM whether we'll need to onboard again for the REST api.
