### ISSUE TITLE
[Epic] Implement evaluation plan in DDog and GA4

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#89217]
### User story

As a Cartography team member, I want to implement the evaluation plan that covers how Veterans use the MHV landing page as well as transition metrics so that we can guide our work and report July numbers.

### Notes
- [Link to evaluation plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/data-collection-evaluation-plan.md)

### Tasks
- Figure out the best place to measure / track each metric (DDog or GA4?)
- Update evaluation plan as things change / get updated when we dig into them

## Acceptance criteria
- [focus ACs on must-haves from eval plan?]
- [evaluation plan is implemented outside of those metrics that we're not fully confident are implemented correctly, or for those metrics we reached an obstacle]

**Comment by wesrowe** [comment]
Moved remaining issues out, can close.
