### ISSUE TITLE
Add logging for server side transfer

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#89225]
We need to add logging so we can get assets to debug with when BE transform is running

**Comment by maxx1128** [comment]
We merged [#17898](https://github.com/department-of-veterans-affairs/vets-api/pull/17898) to get basic Rails logging for the server-side transform. Currently, [#17946](https://github.com/department-of-veterans-affairs/vets-api/pull/17946) is awaiting review, which will also add DataDog stats.

After this point, the basic logging/tracking should be all set, and I believe this ticket could be closed. But if something comes up later and we see the need for further logging, such as a specific service in the server-side transform, this ticket will be reopened.

cc: @digitaldrk @HeatherRienks

**Comment by HeatherRienks** [comment]
@maxx1128 - any update on this ticket?

**Comment by maxx1128** [comment]
Been struggling to get the final specs passing, aiming to get it set by tomorrow.
