### ISSUE TITLE
Collaboration Cycle for [VEBT, Resources for schools, SCO]

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#89238]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1349) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
## VFS product information

This effort focused on the production of a new version of the legacy "Resources for Schools" page using React development tools and USWDS v3 components. The new page, which serves school administrators and certifying officials (SCOs), offers a more maintainable and extensible structure while preserving the look and feel of the original.    

### VFS team name

govcio-vfep-codereviewers

### Product name

Resources for schools 

### Feature name

Convert legacy markdown SCO page into a React app

### GitHub label for team

govcio-vfep-codereviewers

### GitHub label for product

Convert SCO to React

### GitHub label for feature

n/a

### Public DSVA Slack channel for VFS team

vfep-developer-support

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

The work was started in July 2024

### Will your work result in visible changes to the user experience?

Few changes have been required (breadcrumb activated, additional supporting links provided with guidance from the customer); primary effort was in converting the legacy SCO page using React and USWDS v3 components.

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools and applications

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

No

### Product outline

Product is described in "VFS Product Information" at the top of this ticket.
New SCO page URL: https://staging.va.gov/education/school-administrators/
Legacy SCO page URL: https://staging.va.gov/school-administrators/

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.
- Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C05T3DKGM7A/p1721922306207069)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Design Intent` slash-command in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback added to milestone
  - [ ] No feedback
- Design
  - [ ] Feedback added to milestone
  - [ ] No feedback
- IA
  - [ ] Feedback added to milestone
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [ ] Design prototype or high-fidelity mockup
  - Specify which pages are included in the review
- [ ] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

* Accessibility
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Staging Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [n/a] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [n/a] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL for new SCO page: https://staging.va.gov/education/school-administrators/
- [x] Staging URL for Legacy SCO page: https://staging.va.gov/school-administrators/
- [x] Pages: 1        
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. 

**Content artifacts**
- [Cleared for Staging Review by CAIA] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
  
**IA artifacts**
- [Cleared for Staging Review by CAIA] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/suites/view/3395&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
- [x] Test plan
- [ ] Coverage for References
- [x] Summary(Defects) reports: No defects detected (per Axe DevTools)
- [x] E2E tests: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/sco/tests/accessibility.cypress.spec.js
- [x] Code coverage: 98.57%:
   ![New SCO page code coverage summary](https://github.com/user-attachments/assets/1893f52c-0237-4fce-99ad-d485bc17fc34)
  
**Accessibility artifacts**
  
- [X] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). 
Axe DevTools detected two (flagged "Critical") issues in the legacy SCO page, and one (flagged "Serious") issue in the new page. Details are provided in the following 5 Axe DevTools images:

New SCO page issue detected by Axe DevTools:
![New SCO page issue detected by Axe DevTools](https://github.com/user-attachments/assets/83aaead8-c630-4260-90a2-7fbeccdaf9af)

Details:
![New SCO page issue detected by Axe DevTools: Details](https://github.com/user-attachments/assets/b2f05668-f2ca-4920-b402-99d879280108)

Legacy SCO page issues detected by Axe DevTools:
![Legacy SCO page issues detected by Axe DevTools](https://github.com/user-attachments/assets/3ce65fad-eef1-4110-acde-bed9caa118e4)

Details 1:
![Legacy SCO page issues detected by Axe DevTools (details 1)](https://github.com/user-attachments/assets/65e14804-59c8-43b9-8c4c-224c8c2aeca8)

Details 2:
![Legacy SCO page issues detected by Axe DevTools (details 2](https://github.com/user-attachments/assets/2e30aaf1-cf1b-41e6-b57b-2e16abcc2320)

  
##### Platform actions
- [x] Slack thread with VFS team: ~~https://dsva.slack.com/archives/C05T3DKGM7A/p1722363967429929~~ [Reschedule thread with VFS team](https://dsva.slack.com/archives/C05T3DKGM7A/p1722868311667009)
- [x] Meeting date/time: ~~August 8, 2024 at 3.30 PM ET~~ Rescheduled: **Tuesday, August 13, 2024 at 11:30am ET**

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/yyfL6v5nGOthbsLRUTmZA7KgfpTs6BFmAqf_g__8MhmQssRl9WHKsaOYPGQE2iSF.cr0LJRYC949tBtno)
  - Password: `2Tqej%G4`
  
##### VFS actions
  
- [x] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by GcioNapoleon** [comment]
Link to the legacy page

https://www.va.gov/school-administrators/

**Comment by gforbes4** [comment]
Supporting images collection: VEBT images #90809
