### ISSUE TITLE
FE | General Maint | Mobile Phone Extension Removal from Contact Info

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89234]
## Background 

See #31447 for more details 

We've discussed removing the extension field for mobile phone numbers with VA Profile and VA Notify. 

Based on this [thread ](https://dsva.slack.com/archives/C010R6AUPHT/p1707484309669859)and this [thread](https://dsva.slack.com/archives/C909ZG2BB/p1708635736154509) we've decided to remove the extension field from the UI. Extensions aren't supported for text messaging through VA Notify, maintaining this in one place (contact info page) and not the other (notification settings) could lead to uncertainty in the behavior and potential miscommunication/misdirected messages.  

- [contact information designs](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=0-787&t=GqYoOhphnQXfRQ9V-0)

## Acceptance Criteria 
- [ ] we removed the extension field from the mobile phone contact information section

**Comment by ACParker89** [comment]
@mtcA6 Nick has started working on this ticket 8/26

**Comment by ACParker89** [comment]
@nickjg231 @mtcA6 @ACParker89 - Nick will submit his PR for approval prior to EOS, so we will be able to close this out and create a new ticket for the PR for sprint 44
