### ISSUE TITLE
Update NoK/EC edit instructions to call HEC

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89276]
### User story

As a Veteran who wants to update my health care contacts, I want the page to tell me to call the HEC (Health Enrollment Center), so that I can get my contacts updated in the VES system so that they'll propagate to other systems (especially VA.gov).

### Notes
- Health Eligibility Center at 877-222-8387

Possible tasks:
- 

## Acceptance criteria

- Figma updated with instructions for Veterans to call the HEC
- Instructions updated on /profile/contacts page, with appropriate `tel` and accessibility links for three components:
  - Expanding additional-info component at top: "Learn how..."
  - Empty state of Emergency contact
  - Empty state of NoK contact
- QA review
- A11y review

```[tasklist]
### Tasks
- [x] UX to update Figma with new text and styling
- [x] Devs to update page with new content
```

**Comment by jonathanjnelson** [comment]
See updated[ Figma designs here ](https://www.figma.com/design/OVc7YyBq4Fr5mJhcHWlMrc/Archived%3A-Personal-health-care-contacts?node-id=0-444&t=va9ZZnqFnxzCEtmd-1)

Screenshot
<img width="1086" alt="Screenshot 2024-08-01 at 3 25 55 PM" src="https://github.com/user-attachments/assets/2c7e7df5-ea3a-4694-aa7a-fe13c8a9a6a0">

**Comment by wesrowe** [comment]
phone tree notes for HEC (877-222-8387):
- 0 : operator
- 1 : "for enrollment in VA health care"
- 2 : "for questions about billing, collections or insurance"
- 3 : "to transfer to VBA for [long list of VBA benefits]"

I dialed zero and the person who picked up verified that he can update contacts.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the instructions to update NoK/EC has been updated. See attached screenshots for example

<img width="1250" alt="Screenshot 2024-08-07 at 8 13 59 AM" src="https://github.com/user-attachments/assets/266829c6-cf2e-4ab8-b23c-402f50c60270">

<img width="1213" alt="Screenshot 2024-08-07 at 8 17 17 AM" src="https://github.com/user-attachments/assets/1cdd9a74-e543-41de-a527-0c1a156501f1">
