### ISSUE TITLE
AWS access for Tyler Coleman

### ISSUE THREAD

**Issue by tycol7** [department-of-veterans-affairs/va.gov-team#89273]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Tyler Coleman

### Your Email

tyler.coleman@oddball.io

### Team, Role, and Company of the target individual

Team Dash, Senior Software Engineer, Oddball

### Product Manager (PM) name and email

Kayla Wantanabe, kayla.watanabe@adhocteam.us

### Product Owner (PO) name and email

Janet Coutinho, janet.coutinho@va.gov

### Desired AWS Access

- Lighthouse developers IAM
- `dvp-developers`

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![343853627-d750afd9-e663-46ef-917d-650c5d4fe8fd](https://github.com/user-attachments/assets/ec5950e3-ad71-4a59-b2fc-d8f64783fc2a)

### Additional Notes

Ongoing access needed for job duties (software engineer on Lighthouse program).

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by tycol7** [comment]
Resubmitting due to [stale request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87113).

**Comment by FonzMP** [comment]
Hey all - Tyler's part of the VFS Team Member list in Atlas now - just wanted to see if we could get some movement on this.

**Comment by FonzMP** [comment]
hey @flooose , sorry to tag you in but wanted to check in if there were additional items needed here. I know originally Tyler was added but it was reverted - confirming if we're good to get this moving when y'all do your rotation. https://github.com/department-of-veterans-affairs/devops/pull/14499

**Comment by flooose** [comment]
Hi @FonzMP I'm on it. I've got a [PR](https://github.com/department-of-veterans-affairs/devops/pull/14625) up for it and as soon as someone has a chance to approve it, I'll get Tyler added.

**Comment by flooose** [comment]
I just sent @tycol7 is AWS access credentials. He should be all set to go.
