### ISSUE TITLE
Multiple Page List & Loop Pattern Summary Page Text Overrides

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#89286]
## Feature Enhancement Ticket

**Title:**
Enhance Multiple Page List & Loop Pattern Summary Page Text Overrides

**Description:**
The [Array Builder Pattern(Multiple responses list & loop)](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md) pattern summary page has a text override for 'summaryTitle'. This text override displays when the array has items. Some implementations may want to override the title text and description(with string or JSX) when the array does not have any items. For example, the Pension Benefits form would like to implement the summary page without items with a custom title and description.

**Examples:**
<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae80e68c8a3827614132cfa4bb88b054c185eca5/PensionBenefitsSummaryPage.png" alt="PensionBenefitsSummaryPage.png" />

**Priority:**
[Low][Medium][High]

**Dependencies:**
[Array Builder Pattern(Multiple responses list & loop)](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md)

**Acceptance Criteria:**
The [arrayBuilderPatternSummaryPage](https://github.com/department-of-veterans-affairs/vets-website/blob/6fba985c75563065c563f374b5dca5fca5e1d83f/src/platform/forms-system/src/js/patterns/array-builder/ArrayBuilderSummaryPage.jsx#L377) should include an **'arrayBuilderSummaryTitleUI(...)'** pattern that can be used on the summary page as the first page. This title pattern should include:
-  Custom page title(h1-h5)
-  Optional page description (allow any string, or JSX)
-  Yes/no question text as a default label.

**Testing Instructions:**
All existing unit tests pass
Summary page is updated to work with custom 'arrayBuilderSummaryTitleUI pattern for Accessibility

**Additional Notes:**

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/89286?planning-poker) with Zenhub @danlim715 @TaiWilkin @ToddWebDev @wayne-weibel
