### ISSUE TITLE
Add tests to account for a null appointment date time in the claims response

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#89291]
## Description
We need to add tests to the backend and frontend to cover the case(s) of a null appointment date time. Doing this may uncover a bug we also need to fix. 

From the API team:
> Good morning, we have resolved the null appointment date issue on our side. The appointmentDate field in the /claims endpoint can now potentially have a null value. I don't know if this would be a breaking change for you or not. Hopefully not

## Risks
- [ ] Adding these tests may uncover a bug we also need to fix, which may impact at least velocity and at most delivery

## Acceptance Criteria
- [ ] All BE tests pass
- [ ] All FE tests pass
- [ ] Test coverage > 80%
- [ ] Datadog metrics for how many have null appts.
- [ ] 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic**

**Comment by ayush-chak** [comment]
Links to 89328
