### ISSUE TITLE
[QA/Team] 10-10EZR Priority Group: Test Priority Groups 8e and 8g for EZR (DUE JULY 31)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#89317]
As a Veteran with an 8e/8g Priority Group, I would like to be able to either update my information with VA or know that I need to submit a new form so that I can apply for health care under the PACT Act Section 103. 

- [x] Determine how to test for users with 8e and 8g (maybe ask Faulkner)
- [x] Use shortened URL to test
- [x] Try to login as 8e and 8g users
- [x] Determine what happens when you try to hit EZR as 8e/8g
- [x] Discuss with team to determine if this is a good user experience (e.g. are they told to reapply, are they allowed to edit their info, etc.)
- [x] Write test cases (if needed)
- [x] If time: Try testing as PG 7 users
- [x] **Success: We know what will happen when HEC sends out a text nextish week to PG 7 and 8 users**

**Comment by allanto-ah** [comment]
**Environment:** Staging
**Test user:** vets.gov.user+45@gmail.com 
**Test method:** Worked with Josh F to change the priority group of a test user to see what that user sees when going to the EZR intro page with the shortened URL

**Test results:**
Priority group 8e and 8g - In the EZR intro page, user has a message that they are not enrolled in VA health care and has a link to the EZ to enroll in VA health care
Priority group 8a, 7, 5 - In the EZR intro page, user is able to fill and submit the EZR as usual
