### ISSUE TITLE
Create prototype endpoint to sort clinics in vets-api

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#89322]
As part of the recent facilities work, we want to create an endpoint in vets-api that can sort facilities based on what's needed, starting with recency. This will be to create a prototype of the endpoint to begin testing the base case of sorting by recency and give us a chance to address any currently unforeseen issues with this approach. We will use the fetched appointments list, extract clinic data, then sort those clinics as needed.

Related ticket for background context: https://github.com/department-of-veterans-affairs/va.gov-team/issues/83352

AC:
[ ] - create prototype endpoint that extracts clinic data from appointments list and sorts by recency

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89322?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit
