### ISSUE TITLE
Write tests for vets-api clinic sorting prototype endpoint

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#89324]
This ticket is to capture testing needed for the initial prototype version of the clinic sorting endpoint referenced in this ticket: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/89322

AC:
[ ] - test coverage for prototype functionality

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89324?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
Combine with 89323 and size up

**Comment by ldelacosta** [comment]
Team will work on 89323 and we will combine the requirements in that ticket. Closing the ticket out.
