### ISSUE TITLE
[BE/FE] 10-10EZR EC/NoK: Build feature toggles for EZR EC and NoK

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#89331]
As a Veteran, I would not like to see anything that is not completed/untested on Production so that my submission doesn't break and I don't have to redo my EZR.

- [x] **Success: We have build feature toggles, one for EC and one for NoK and it is in place as we build them out so we don't have an issue like with Attach Docs (This was a post mortem recommendation)**

**Comment by allanto-ah** [comment]
Verified that the flipper toggles can be seen in the flipper UI. Closing this ticket
