### ISSUE TITLE
Spike: Cypress to rail recorder plugin configuration 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89349]
Investigate how to incorporate cypress tests into Testrail to make our testing more robust (following standard guidelines).

**Comment by cloudmagic80** [comment]
TestRails API key was created. The corresponding testrail objects like projectID, suiteID, groupId were collected during a sample run. Under certain circumstances, the environment variables were created but not all. Platform is still trying to figure this out especially with TR_GROUPID.

**Comment by cloudmagic80** [comment]
Runs were successful in Cypress for 1010D.
