### ISSUE TITLE
FE + BE| Debt Team Notifications | Feature flags for new debt team notification items

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89359]
## Background 
The debt team has requested new notification settings. 

We need to create feature toggles for the two new communication items.

|Communication Group| Communication Item Name| Communication Item ID|Channel|
|:--|:--|:--|---|
|Payments|New benefit overpayment debt notification|13|email|
|Payments|New health care copay bill|14|email|

- the ID's should show up in swagger when available - https://int.vaprofile.va.gov:7005/communication-hub/swagger-ui/index.html#/CommunicationItemBio/pullManyCommunicationItems

## Tasks 
- [ ] confirm with VA Profile (Mike Richards) what the communication item ID's are so we can appropriately filter these on the FE. - [see VA Profile Intake Jira](https://jira.devops.va.gov/servicedesk/customer/portal/12/CMDMRP-8153)

![Image](https://github.com/user-attachments/assets/26aad8b2-c0f0-4854-b6d0-bf1ba9158b41)

## Acceptance Criteria 
- [ ] we have two new toggles, one for each the new notification settings

**Comment by mtcA6** [comment]
![Image](https://github.com/user-attachments/assets/85e965ac-e947-40d4-8941-2466e7682416)

**Comment by ACParker89** [comment]
@tpharrison - BE Code validation
@adamwhitlock1/ @nickjg231  -  FE code review?

**Comment by mtcA6** [comment]
https://dsva.slack.com/archives/C010R6AUPHT/p1724789605718989

tested in staging and alerted VA Notify and the debt team
