### ISSUE TITLE
Vets-api terminal access for Gaurav Gupta

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#89366]
### Your Name

Gaurav Gupta

### Your GitHub handle (terminal access is managed through GitHub)

@randomsync

### Your dsvagovcloud AWS user name (if applicable)

gaurav.gupta

### Team, Role, and Company of the target individual

Team Check-In, Backend Engineer, Kind Systems

### Product Manager (PM) name and email

Lori Pusey lori.pusey@agile6.com

### Product Owner (PO) name and email

Kay Lawyer, katherine.lawyer@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![image](https://github.com/user-attachments/assets/39c4173f-2af5-4d51-8bbc-566038a45022)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by GWright321** [comment]
verified in Atlas

**Comment by GWright321** [comment]
@randomsync  You’ve been granted access to the dev, staging, and sandbox environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
