### ISSUE TITLE
Remove feature toggle va_online_scheduling_appointment_details_redesign	

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89375]
## Description
Once we go fully live for the Appointment Details Redesign in August 2024, we will need to remove the feature toggle from the list and the application code. 

## Requirements 

- [ ] Remove feature toggle `va_online_scheduling_appointment_details_redesign` from the flipper list and the application code. 

### Design Assets
N/A

---
### Development Checklist

- [ ] Task 1
- [ ] Task 2

 ## Developer Reference
- [ ] [Swagger file]() (remove if not needed)
- [ ] [File path]() (remove if not needed)

### Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89375?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
Break down into smaller pieces, using this as the "shell"
Old code needs to be removed.

**Comment by ldelacosta** [comment]
Work can begin in Sprint 14. cc: @Bren22va @JRRoof @simiadebowale

**Comment by JunTaoLuo** [comment]
I have already removed the flags from dev, sandbox and staging environments. Looks like FE/BE changes are awaiting deployment to prod. Once that's completed tomorrow, I'll open the platform ticket to remove the ticket from prod environment.

**Comment by JunTaoLuo** [comment]
FYI we decided to leave this until early next week for the final removal of the feature flag in production.

**Comment by ldelacosta** [comment]
No additional issues have been found. Closing out the ticket.
