### ISSUE TITLE
Additions to "Screen reader instructions and troubleshooting during research"

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#89374]
### Description
CAIA has additional tips for researchers running assistive tech sessions with screen reader users. Could these be added to the page? Please rewrite to match the page style as needed.

##### Disabled audio
- Issue: When “sharing audio” the “mute” button becomes disabled not allowing researchers to hear participants. “Mute” button becomes grayed out 
- Solution: To prevent this, user shouldn’t share audio and instead voice to researcher what the screenreader output is while navigating through the study 

##### "Save password" popup
- Issue:  For SR users, focus is on the browser, and so the “Save password” popup doesn’t affect them. But sighted users see it covering the screen.
- Solution (JAWS users): If a popup comes up, like “Save password,” a JAWS user would hit “Shift + F6” to get focus to that window and close it.

##### Use of, and access to, Zoom chat
- Issue: Zoom chat messages are notifications that are announced by screen readers. VoiceOver, in particular, doesn’t allow a user to turn off spoken notifications. It is very distracting.
- Solutions:  
   - Avoid the use of Zoom chat during sessions, except for sharing links. Ask the participant where they’d like to receive the link - email, Zoom chat, dictated, etc. 
   - JAWS: Alt+H is the keystroke to open or close Zoom chat. But it doesn’t always work to close the chat - the chat box is still visible sometimes. To access links in Zoom chat using JAWS, follow these instructions:
      - Press ALT + H, focus will be on the message box
      - Press SHIFT + TAB to “chat list view” (the message history)
      - Use arrow keys to navigate within the chat list to the link
      - Press TAB to focus on the link
      - Press ENTER, then “open link” on the popup menu

##### Low battery causing screen share issues
- Issue: If a user is participating with a mobile device, and that device has the battery saver setting activated, there is a chance that screen sharing can fail. 
- Solution: Disable battery saver settings and, if possible, plug in phone. 

##### Screen curtain
- Issue: The screen is dark, even when the user is sharing their screen. 
- Solution: Make sure screen curtain is turned off. If the screen is blank - that probably means they have screen curtain turned on, which is something that happens from time to time. 
   - Try a 3 finger triple tap to turn screen curtain off. 
   - [Additional instructions are available.](https://support.apple.com/en-us/111797) 
   - Hit the home button to get rid of the screen. Gets to the main zoom screen. 
   - Share screen. 

##### Advancing past the shared screen modal / "Broadcast" screen
* **Type(s):** Mobile  
* **Device(s):** iPhone, iPad  
* **Issue**: After selecting “Start Broadcast,” the modal for screen sharing is counting up, and sharing, but the user can’t access their browser to conduct the usability test.    
* **Solution Option 1 (iPhone only):** Have the user hold their finger on the screen after swiping up and feeling the first vibration.   
* **Solution Option 2:** From the bottom of the screen, drag one finger until you hear two rising tones, then lift your finger. This will bring the user to the main Zoom window. Do this one more time to get back to the home screen, where the user can access their browser and other applications. Then swipe right using 3 fingers to find and open the app you're looking for. ([Option 2 video demonstration](https://drive.google.com/file/d/1MrJ2wQf\_ztOEk967VrIHo242PFkMtJkc/view?usp=sharing))  
* **Solution Option 3:** Use the app changer to toggle between screens.  Using 1 finger, from the bottom of your screen, swipe halfway to the middle of the screen until you feel 2 vibrations. Lift your finger, then swipe right using 3 fingers to find and open the app you're looking for. [Option 3 video demonstration]([https://www.youtube.com/watch?v=ILEy84MOd4E](https://www.youtube.com/watch?v=ILEy84MOd4E))

##### Zoom permissions
- Issue: After screen share, if permissions are not enabled for Zoom app, user will get directed to "Apps” window 
- Solution: To bypass this and enable Zoom permissions, flick right in the Apps window until you hear “zoom” and double tap. Zoom is the very last app because options are listed in alphabetical order.  Screen share should begin activating.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-instructions-and-troubleshooting-dur

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Sitewide CAIA

```[tasklist]
### Related Tickets
- [ ] #87136
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82145
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89374
```

**Comment by taylojill** [comment]
Hi @coforma-jamie - thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@coforma-jamie would you or someone from your team be able to work with us on this page update? We may need to have some conversations about how to fit the new guidance with the existing page.

**Comment by coforma-jamie** [comment]
@jknipes sure, I'd be happy to! Let me know what you need :)

**Comment by coforma-jamie** [comment]
I worked with the Platform Content team to add these tips to the Screen Reader instructions page. They ended up splitting it into three pages - desktop, iOS VO, and android talkback - which gives us room to add tips for other screen readers in the future! The [pages](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-instructions-and-troubleshooting-dur) have been published.

This is ready for closure review @sara-amanda

**Comment by jknipes** [comment]
Thank you for working with us on this @coforma-jamie!
Closing this ticket on our board as _Complete_.

**Comment by artsymartha68** [comment]
This is so great! Thanks!!!
