### ISSUE TITLE
Improve Primary Contact logic in submit transformer

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#89380]
As a user, I want to get a confirmation email regardless of the order in which I list applicants so that I can be sure I know my form was received.

Description:
Currently, we just check if the first applicant has an email address and if not, we won't have anywhere to send the confirmation email. However, it's possible that the user input an email address in a subsequent applicant on the form, so we need to expand the Primary Contact logic to check all applicants for email addresses. This will prevent us from overlooking an email address and not having anywhere to send the email.

Acceptance criteria:
- Email is sent to the first available applicant email address, regardless of applicant order in the form.
- If a single applicant has an email address, that address will receive the confirmation email
- If multiple applicants have email addresses, the first entered email address will receive the confirmation email

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31035). Waiting on:

- [ ] Team approval
- [ ] platform approval

**Comment by michaelclement** [comment]
This is done. To verify, you can add no email address to the first applicant, but do include on the second or later. You should receive an email regardless of which applicant has the address when you submit the form. @baltes @marywang2 
Thanks!

**Comment by baltes** [comment]
@michaelclement Just to confirm, it will only send an email to one address if more than one is provided?

**Comment by michaelclement** [comment]
@baltes yes, that's correct
