### ISSUE TITLE
Update Page Titles (VA and Community Care Requests - Part 1) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89384]
## Description
Feature ##88979
This aligns the browser tab titles for details pages with the new page titles

---

### VA Requests

- [x] Given a user is on a `confirmed` `VA request` details page
Then the browser tab title should read `Request for [Type of Care] appointment | Veterans Affairs`

- [x] Given a user is on a `pending` `VA request` details page
Then the browser tab title should read `Request for [Type of Care] appointment | Veterans Affairs`

- [x] Given a user is on a `canceled` `VA request` details page
Then the browser tab title should read `Canceled request for [Type of Care] appointment | Veterans Affairs`

### Community care requests

- [x] Given a user is on a `confirmed` `cc request` details page
Then the browser tab title should read `Request for [Type of Care] community care appointment | Veterans Affairs`

- [x] Given a user is on a `pending` `cc request` details page
Then the browser tab title should read `Request for [Type of Care] community care appointment | Veterans Affairs`

- [x] Given a user is on a `canceled` `cc request` details page
Then the browser tab title should read `Canceled request for [Type of Care] community care appointment | Veterans Affairs`

### Design Assets
N/A

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
- [Figma file]() (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89384?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by vbahinwillit** [comment]
@ldelacosta - I think this needs to be behind the 'vaOnlineSchedulingAppointmentDetailsRedesign' feature flag since the page title is matching the new design pages.

**Comment by vbahinwillit** [comment]
Blocked until 8/9 Fri. release which includes appointment details redesign. So no need for feature flag.

**Comment by ldelacosta** [comment]
Appointment Details Redesign release is set for EOD today. @vbahinwillit - you can start on this work tomorrow (new sprint). I'll remove this from the Blocked queue. cc: @Bren22va @JRRoof

**Comment by ldelacosta** [comment]
@outerpress - can you start re-testing again in staging.

**Comment by outerpress** [comment]
@ldelacosta Judy's back! This one's good to go.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
