### ISSUE TITLE
[EKS][PACKER] Implement EKS Node Log Rotation

### ISSUE THREAD

**Issue by Efe-Oddball** [department-of-veterans-affairs/va.gov-team#89388]
## Description
Amazon Cloudwatch agent has been implemented in EKS nodes to collect logs and forward to Cloudwatch. The next step needed is to implement Rotation and delete logs after first rotation to ensure that the logs are no longer being stored within the nodes.

Possible solutions: 
- Implement log Rotation
- delete logs after first rotation.

## Resources 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74601
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85703

## Acceptance Criteria
- [x] Confirm rotation is functional and logs are deleted afterwards
- [x] Merged PR

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by hgbarreto** [comment]
> The file Packer provisioner uploads files to machines built by Packer. The recommended usage of the file provisioner is to use it to upload files, and then use [shell provisioner](https://developer.hashicorp.com/packer/docs/provisioners/shell) to move them to the proper place, set permissions, etc.

[Packer File Provisioner Documentation](https://developer.hashicorp.com/packer/docs/provisioners/file)
