### ISSUE TITLE
Update Page Titles (Telehealth Appointment Video and Phone - Part 3)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89386]
## Description
Feature ##88979
This aligns the browser tab titles for details pages with the new page titles

---

### Video appointments (including GFE)

- [x] Given a user is on a `Upcoming` `VA Video` details page
Then the browser tab title should read `Video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `VA Video` details page
Then the browser tab title should read `Past video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `VA Video` details page
Then the browser tab title should read `Canceled video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

---

- [x] Given a user is on a `Upcoming` `VA Video over GFE` details page
Then the browser tab title should read `Video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `VA Video over GFE` details page
Then the browser tab title should read `Past video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `VA Video over GFE` details page
Then the browser tab title should read `Canceled video appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video at VA location appointments

- [x] Given a user is on a `Upcoming` `Video at a VA location` details page
Then the browser tab title should read `Video appointment at VA location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `Video at a VA location` details page
Then the browser tab title should read `Past video appointment at VA location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `Video at a VA location` details page
Then the browser tab title should read `Canceled video appointment at VA location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video at an ATLAS location appointments

- [x] Given a user is on a `Upcoming` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Video appointment at an ATLAS location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Past video appointment at an ATLAS location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Canceled video appointment at an ATLAS location on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Phone appointments

- [x] Given a user is on a `upcoming` `phone appointment` details page
Then the browser tab title should read `Phone appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `past` `phone appointment` details page
Then the browser tab title should read `Past phone appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `canceled` `phone appointment` details page
Then the browser tab title should read `Canceled phone appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Design Assets
N/A

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated
---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
- [Figma file]() (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89386?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
UX team - this is ready to be validated in staging.

**Comment by outerpress** [comment]
We won't be able to test the rest of the "Video at a VA location" appt states due to an issue on prod.

Also, I'm not sure how to identify GFE appointments. 

@vbahinwillit I'll reach out to you so I can take a look at these types on your local environment

**Comment by outerpress** [comment]
Confirmed with @vbahinwillit that we can't test video at va appointments. They're showing up as video appts on staging and his local env. @ldelacosta

**Comment by outerpress** [comment]
@vbahinwillit is going to try some other methods to recreate these.

**Comment by outerpress** [comment]
@vbahinwillit was able to recreate in his local environment - so this is good to go! I'll make a note to test the video at VA appts in staging too, when we can get them created again. @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
