### ISSUE TITLE
10-7959f-1: react widget updates

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89394]
Once the content is ready to go from CAIA, we will need to update the react widget so it reflects the correct content.
- update react widget content
- CAIA adds widget to drupal page
- work with CAIA to test
- process [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md)

**Content** 
(taken directly from this CAIA [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88012#issuecomment-2256789193)): We'll place the widget below the H2 "How to register" on [this page](https://www.va.gov/health-care/foreign-medical-program/).

### Side 1: No link to online form

Fill out an FMP Registration Form (VA Form 10-7959f-1). You’ll need your Social Security number or your VA claim number (also called VA file number). In most cases, your claim number and Social Security number are the same.

**Note:** You don’t need to be enrolled in VA health care to register for the Foreign Medical Program.

[primary action link] [Get VA Form 10-7959f-1 to download](https://www.va.gov/find-forms/about-form-10-7959f-1)

Then send your completed form to us in one of these ways.

**[H3] Option 1: Online**
[Upload your completed form through Ask VA](https://ask.va.gov/)

**[H3] Option 2: By mail**
Mail your completed form to this address:
> VHA Office of Integrated Veteran Care (OIVC) 
> Foreign Medical Program (FMP)
> P.O. Box 469061
> Denver, CO 80246-9061

**[H3] Option 3: By fax**
Fax your completed form to [303-331-7803](tel:+1303-331-7803).

### Side 2: Link to online form

You can register online, by mail, or by fax. You’ll need your Social Security number or your VA claim number (also called VA file number). In most cases, your claim number and Social Security number are the same.

**Note:** You don’t need to be enrolled in VA health care to register for the Foreign Medical Program.

[H3] **Option 1: Online**
[Primary action link] [Register for the Foreign Medical Program](URL for intro page of online form)

**[H3] Option 2: By mail**
Fill out an FMP Registration Form (VA Form 10-7959f-1).

[Get VA Form 10-7959f-1 to download](https://www.va.gov/find-forms/about-form-10-7959f-1)

Mail your completed form to this address:
> VHA Office of Integrated Veteran Care (OIVC)
> Foreign Medical Program (FMP)
> P.O. Box 469061
> Denver, CO 80246-9061

**[H3] Option 3: By fax**
Fill out an FMP Registration Form (VA Form 10-7959f-1).

[Get VA Form 10-7959f-1 to download](https://prod.cms.va.gov/find-forms/about-form-10-7959f-1)

Fax your completed form to [303-331-7803](tel:3033317803).

**Comment by reiting** [comment]
Having a meeting today to hopefully understand better what they want for this.

**Comment by marywang2** [comment]
FYI screenshots from CAIA of the content are in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88012)

**Comment by reiting** [comment]
I've put in a PR for this. Waiting on team and then platform review.

**Comment by reiting** [comment]
This has been approved by the team, but some unrelated cypress tests are failing in CI, which means that it cannot be merged yet. I'm leaving it in draft until that is resolved. I did put in a support request with the dsva support team and they are looking into it.

**Comment by reiting** [comment]
Moving this to blocked as it wasn't a simple, fast fix and we can't do anything until this issue is fixed.

**Comment by reiting** [comment]
Issue was resolved. Waiting on platform review now

**Comment by reiting** [comment]
This was approved by platform and has been merged! Should be in staging in a few hours, though I don't really know how you will test that.

**Comment by reiting** [comment]
@marywang2 @baltes this should be in staging and good to go.
