### ISSUE TITLE
10-7959f-1: Submission error on review page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89409]
- When entering a VA file number (not SSN), I get an error upon submission and am unable to submit the form. 
  - The VA file number does not appear on the review page 
- Upon removing the VA file number and entering an SSN, I am still unable to submit the form (there is no submit button).
<img width="1306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67f6226f3a6b8c609aa77a7c7166fee41a307423/Screenshot%202024-07-26%20at%202.16.09%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 2.16.09 PM.png" />
<img width="707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzRUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7143d9ebdecd1b82d3c5720204d4bf74afcf3c79/Screenshot%202024-07-26%20at%201.15.33%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 1.15.33 PM.png" />
No submit button:
<img width="921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6abc2dbbdcc265cd9f99e32ae236686a92934c4c/Screenshot%202024-07-26%20at%201.56.17%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 1.56.17 PM.png" />
Error:
2024-07-26 12:45:40.059626 E [6498:puma srv tp 005 uploads_controller.rb:34] Rails -- Error: file number is invalid. It must be 8 or 9 digits
2024-07-26 12:45:40.059767 E [6498:puma srv tp 005 uploads_controller.rb:35] Rails -- /Users/michael.clement/repos/vagov-repos/vets-api/modules/ivc_champva/app/services/ivc_champva/metadata_validator.rb:33:in `validate_file_number'

**Comment by reiting** [comment]
This has been completed and merged. Should be in staging in a few hours. <img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f37f4813fad989414a8be94462396fba1df364f9/Screenshot%202024-07-26%20at%202.57.40%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 2.57.40 PM.png" />

**Comment by marywang2** [comment]
This worked (did not get a submit error when I input a VA file number), but I don't see the file number in the review page where I expected to see it @reiting. <img width="1316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFlQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8edc8a900f191dfd7efaa1825a7fe598facfdb9/Screenshot%202024-07-30%20at%202.45.56%E2%80%AFPM.png" alt="Screenshot 2024-07-30 at 2.45.56 PM.png" />

**Comment by marywang2** [comment]
I'll close this one for now but please let me know if I should create a new ticket for what I'm seeing @reiting. Thanks!
