### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by Jones-Morgan** [department-of-veterans-affairs/va.gov-team#89418]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01/01/2024

### Date Range End

07/26/2024

### Product Name(s)

Authenticated Experience Design Patterns

### Product Description

We are working on improving design patterns for the authenticated experience. Our first task is the prefill experience.

### Survey URL(s), key term(s), case category or type

Key terms: 
- prefill
- pre-fill
- authenticated experience
- user data
- my data
- my information
- authenticated data

### Sub URLs

No

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

morgan.jones21@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi @jones-Morgan, could you provide me the URS's you need the data to be pulled. I am not able to find any results on provided case categories or case type on the Medallia.

**Comment by Jones-Morgan** [comment]
Also, can you include Christine in any results and or questions while I'm away next week?: ***@***.******@***.***>
Thank you,
Morgan
From: Sarifa Khalilulah ***@***.***>
Sent: Friday, July 26, 2024 1:47 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: JONES, MORGAN B. (Agile Six Applications, Inc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #89418)


Hi @Jones-Morgan<https://github.com/Jones-Morgan>, could you provide me the URS's you need the data to be pulled. I am not able to find any results on provided case categories or case type on the Medallia.

-

**Comment by newworld2616** [comment]
Got it, thank you for clarification. Sure, I will include him too.

**Comment by newworld2616** [comment]
Good morning, could you provide me Christine's VA email address please. Thank you.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Once I have Christine's email, I will share the data. Thank you.

**Comment by ChristineRoseSteiffer** [comment]
Hi @newworld2616 - my email is christine.steiffer@agile6.com or christine.steiffer@va.gov if you can only share via a VA.gov email address. Thank you for your help!

**Comment by newworld2616** [comment]
Hello, thank you for the email. I shared the requested data.

**Comment by Jones-Morgan** [comment]
Hi! I'm back and just going through emails. I can forward the results to her since I didn't give you her email before!

Thanks,
Morgan

From: Sarifa Khalilulah ***@***.***>
Sent: Monday, July 29, 2024 8:43 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: JONES, MORGAN B. (Agile Six Applications, Inc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #89418)


Good morning, could you provide me Christine's VA email address please. Thank you.

-

**Comment by newworld2616** [comment]
Welcome back. I got her email from her. Thank you for your response!

**Comment by Jones-Morgan** [comment]
Thank you! I saw that!

From: Sarifa Khalilulah ***@***.***>
Sent: Monday, August 5, 2024 9:00 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: JONES, MORGAN B. (Agile Six Applications, Inc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #89418)

Welcome back. I got her email from her. Thank you for your response!

**Comment by Jones-Morgan** [comment]
Hi Sarifa,
I’ve looked at the data that was returned and there doesn’t seem to be any survey results with the sort of information we are looking for. I’m wondering if it would be worth working with you to better refine our query?

From: Sarifa Khalilulah ***@***.***>
Sent: Monday, August 5, 2024 9:00 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: JONES, MORGAN B. (Agile Six Applications, Inc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #89418)

Welcome back. I got her email from her. Thank you for your response!

**Comment by newworld2616** [comment]
Hello,
if you could provide me with the URLs, that will help to extract the data
from Medallia. The categories that were provided, do not pop up on my
search in Medallia. That could be the reason, the data is not as useful as
it should be.
Let me know if you have any questions.

Best Regards,

Sarifa
