### ISSUE TITLE
Burial | Add Claim Class to Logs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89423]
## Issue Description
_In order to better identify burial claim logs, the claim class needs to be added to logging._

---
## Acceptance Criteria
- [ ] Burial claim class added to Burial logs
---

**Comment by mjknight50** [comment]
We need some more information on this.  Was it from @tblackwe ?
We need some more context or information.  If none, we can do a spike to look into this better.

**Comment by mjknight50** [comment]
This could/should also be caught by this work:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90177

**Comment by steele-lm** [comment]
@mjknight50 I think @micahaspyr first called this out when he was helping my try to fix a broken datadog submission report for the burial form. When we were trying to query burial claim submissions, the named_tag.source syntax no longer existed after the v2 burial form was launched, so we [had to use](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22Lighthouse%3A%3ASubmitBenefitsIntakeClaim%20job%20starting%22%20%40named_tags.class%3A%22StructuredData%3A%3AProcessDataJob%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.benefits_intake_uuid%2C%40class%2C%40named_tags.class&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1721407654351&to_ts=1722012454351&live=true) "StructuredData::ProcessDataJob" bc it is only used by Burials

**Comment by mjknight50** [comment]
We will address this as part of the overall work to move burials to its own module.

**Comment by aplatt-coforma** [comment]
Per @wayne-weibel - This one will likely be covered as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/91824. The ‘claim class’ could mean a few things, some of which is already in the logs and just need to know how to query it in datadog.
