### ISSUE TITLE
Flipper UI access for Anam Masroor

### ISSUE THREAD

**Issue by bradbergeron-us** [department-of-veterans-affairs/va.gov-team#89427]
### Your Name

Anam Masroor

### Your GitHub handle (Flipper UI access is managed through GitHub)

@amasroor88

### Team, Role, and Company of the target individual

My Education Benefits - Testing Lead - Accenture Federal Services

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by AnthonyWFlowers** [comment]
Confirmed user in Atlas

Greetings @bradbergeron-us, @amasroor88 been granted access to the Flipper UI lesser environments. Please reach out with any additional questions or concerns.
