### ISSUE TITLE
Review Medallia feedback for landing page – daily

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89434]
### User story

As a Cartography team member, I want to create a scalable process for analyzing user feedback (Medallia) and tracking trends over time, so that we and stakeholders can understand how Veterans are responding to the portal and identify areas that are successful or need improvement.

As a Veteran, I want my feedback to be used to iterate and improve the experience on MHV, so that I trust that the VA takes Veterans like me seriously.

### Notes
- Ticket for daily Medallia pulls post-launch has been submitted 
- Wes, Kaitlin, Jenny & Robyn have shared understanding of integration launch KPIs to track in [this doc + Mural](https://docs.google.com/document/d/1Qah8gSA6JCqEILg4hC1LTlmNSH9sRYRiWai3iprWgUg/edit#heading=h.4ku8bv7bajcw)
- Post-launch [UX KPIs mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716414036737/5aa77bac68425356bf314724636ed828f6bb5743?wid=0-1716421371873) for reference

Possible tasks:
- 

## Acceptance criteria

- Review feedback daily
- Post into a shared [Cartography spreadsheet ](https://dvagov.sharepoint.com/:x:/s/oitmhvonvagovcartographyteam/EVY2_fiGl7dMpbL1nhDRDjQBbvhwxRsKc611SDKas9oa7A?e=G5mtdl)
- Post and tag in the[ Aug 2024 shared portal spreadsheet ](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B8C161AC9-BB42-401D-9B5D-913941F1ECA9%7D&file=MHV)
- Ticket next sprint's version

**Comment by jonathanjnelson** [comment]
[Sprint 38 ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/zh/547)
