### ISSUE TITLE
Record only 1% of MHV Landing Page sessions in DD for Replay

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89435]
### User story

As a Cartography team member, I want to save the VA money by reducing the percentage of user sessions that get recorded by Datadog for replay.

### Notes
- [Slack thread with Patrick](https://dsva.slack.com/archives/C0581MN69TJ/p1722542826234699)

Possible tasks:
- 

## Acceptance criteria

- Datadog records only 1% of sessions for replay

**Comment by dcloud** [comment]
There may not be a way to verify other than to look in Datadog and say "I see far fewer sessions with the playback button"?

**Comment by LynneJohnson224** [comment]
@dcloud can we close this ticket?
