### ISSUE TITLE
Contact Center Review for [Disability Experience Team 1 - 526ez Toxic Exposure]

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#89438]
## Description
[Disability Comp Application (21-526 EZ)](https://depo-platform-documentation.scrollhelp.site/getting-started/disability-comp-application-21-526-ez) This product enables Veterans to file disability benefits claim via va.gov.

Functionality adds section 4 - Toxic Exposure section of the 526ez form when filing a Disability Benefits claim via va.gov. Also updates Form 21-526EZ to use version NOV 2022. Previous version was SEP 2019. 

The product changes require updates to two product guides.

URL: https://staging.va.gov/disability/file-disability-claim-form-21-526ez

### Launch Date
[Release Plan: 526 Toxic Exposure](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/Toxic%20Exposure%20Release%20Plan.md)

### Version Number
526ez Disability Benefits Claims Product Guide v4.0
526ez Benefits Delivery at Discharge - Disability Benefits Claims Product Guide v3.0

### Product Guide
[526ez Disability Benefits Claims Product Guide v4.0 DRAFT.docx](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Disability%20Benefits%20Experience/Documentation/Drafts/526ez%20Disability%20Benefits%20Claims%20Product%20Guide%20v4.0%20DRAFT.docx?d=wbbffafd269f544d18bafc5c4b1a92d71&csf=1&web=1&e=ttg4W8)
[526.Benefits.Delivery.at.Discharge.v3.0--.product.guide DRAFT.docx](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Disability%20Benefits%20Experience/Documentation/Drafts/526.Benefits.Delivery.at.Discharge.v3.0--.product.guide%20DRAFT.docx?d=w47dd3678fc38414e95cb42e2855bf1d0&csf=1&web=1&e=z3i2rY)

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by christinec-fftc** [comment]
Hi CC team 👋 , we need to update two product guides. Please let us know if it's ok to bundle this in one ticket or if you'd like two separate tickets.

**Comment by starlow00** [comment]
Hi @christinec-fftc. One ticket is okay since they're related to the same basic form.

However, I want to ensure that the drafts you've provided here were built on the most recent versions of the 526 BDD and 526EZ.  If so, we're ready for me to proceed. If not, I'll need your most recent updates incorporated into the versions attached to the following tickets:
https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/88765
https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/88767

Questions, please let me know!

**Comment by christinec-fftc** [comment]
Thanks @starlow00! I'll check on this and get back to you asap.

**Comment by christinec-fftc** [comment]
Hi @starlow00, both docs have been updated in sharepoint and are available at the same links in the description.

**Comment by starlow00** [comment]
Thank you!

From: Christine ***@***.***>
Sent: Tuesday, July 30, 2024 11:00 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: TARLOW, STEVEN R. (ODDBALL INC) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Disability Experience Team 1 - 526ez Toxic Exposure] (Issue #89438)


Hi @starlow00<https://github.com/starlow00>, both docs have been updated in sharepoint and are available at the same links in the description.

-

**Comment by starlow00** [comment]
(Note: I selected 12 points to reflect that this is a review of 2 guides.)

**Comment by starlow00** [comment]
Drafts look good, sending for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. Current copies are attached; please share them with the 526EZ and BDD teams and use them for future revisions. Thank you!
[526EZ Disability Benefits Claims Product Guide v4.0 SRT 07302024R.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3df063561d6722cf77e31a277cf4753832a173e1/526EZ%20Disability%20Benefits%20Claims%20Product%20Guide%20v4.0%20SRT%2007302024R.docx)

[526.Benefits.Delivery.at.Discharge.v3.0--.product.guide SRT 07312024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4baf1657fa424bf3f9d5398ac333fba5bee769c/526.Benefits.Delivery.at.Discharge.v3.0--.product.guide%20SRT%2007312024.docx)
