### ISSUE TITLE
Design intent Collaboration[BDD Usability test 2]

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#8943]
## Steps to complete Design Intent Collaboration
- [ ] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [ ] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [ ] VSP <> **requesting team** design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))

- BDD in staging: 
https://staging.va.gov/disability/file-benefits-delivery-at-discharge-form-21-526ez/introduction

## Meeting attendees from **requesting team**
- Designer(s) (required): **Christian V, **
- Product Manager (optional): **Luke M**
- DEPO design lead (required as applicable): **name**

## Scheduling
Preferred dates or times: 11 or 12 May 2020

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled May 13, 11:00 AM EST

**Comment by chrvalla** [comment]
This has been canceled. There is no need for a new design review, as this is a similar usability test as the initial BDD usability test.
