### ISSUE TITLE
Life insurance rewriting batch 3: SGLI contact information

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8944]
# User story

As a Reserve or Guard member with SGLI coverage drilling for points, I need to know who to contact about coverage status and premium payments.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** Need to confirm with Mikki
- **URL (WIP):** Need to confirm with Mikki
- **Left nav label:** SGLI contact information (TBD)
- We'll also crosslink to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/INSURANCE/popups/non-payPOC.htm
- **SEO keywords:** n/a
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style
  - Take the information out of a table for improved mobile readability. Go to the [old issue #19012](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19012) in vets repo for additional strategy notes.

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/options-eligibility/sgli-plus-sgli-contact-test.md

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.
- Consider adding a link to this secure messaging form where relevant: https://insurance.va.gov/ContactUs/.

**Comment by MickinSahni** [comment]
@lwalsh617 @DanielleThierryUSDSVA mind adding an estimate to this?

**Comment by DanielleThierryUSDSVA** [comment]
Looks like Laura added estimate - thank you!
