### ISSUE TITLE
GIDS: Validate SCO file data on upload

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8947]
As an Education Team Member GIDS user, I need the SCO data validated on file upload so that I can address any issues with the data prior to generating a new version for publishing.

## Assumptions:
1. This story is specific to the CSV file type "SchoolCertifyingOfficial" uploaded to GIDS.

## Acceptance Criteria:
1. A validation message for the data row, "Priority is not a valid value." is displayed when the contents of the "Priority" column do not match one of the following non-case sensitive values:
    - Primary
    - Secondary
2. The "School Certifying Official File Data Requirements" informational blue box displays the data requirements for the "Priority" column.

## Supporting Artifacts:
1. [Original SCO File Data Requirements.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4609418/Original.SCO.File.Data.Requirements.docx)
2. [SchoolCertifyingOfficial Data.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4609431/SchoolCertifyingOfficial.Data.csv.zip)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/656

**Comment by delli-gatti-michael** [comment]
Tested by the following TestRail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/613

**Comment by delli-gatti-michael** [comment]
The file attached to the original issue contains several commas that are causing unintended errors on upload. The below file has those commas removed. 

[SchoolCertifyingOfficial_commas_removed.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4646317/SchoolCertifyingOfficial_commas_removed.csv.zip)

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-05-18 at 3 11 51 PM](https://user-images.githubusercontent.com/45575003/82253130-586f9e00-991e-11ea-8d13-5ac0e3a358b4.png)

**Comment by delli-gatti-michael** [comment]
This is now in Staging. Closing this story
