### ISSUE TITLE
Discovery: Updating My VA to point to MHV on VA.gov tools

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#89470]
## Description

As MHV on VA.gov gets closer to all tools being in Phase 1 (last being MR, which is slated to enter Phase 1 in September), we are open and interested in changing the links on the My VA page to point to these new builds. Kaitlin states in [this Slack thread ](https://dsva.slack.com/archives/C04DRS3L9NV/p1721936072401309)that we do not necessarily need to wait for MR to reach Phase 1 to make the switch. 

### User story

As a Cartography team member, I want to develop a plan for updating links on My VA to point to the new MHV on VA.gov tools so that Veterans have a more seamless experience getting to the best experience for My HealtheVet, and do not have to jump through circuitous hoops to go to the National Portal, click a "try me" banner, just to get back to VA.gov again where they already were to manage their health. 

As a Veteran, when I sign-onto VA.gov and click a link to manage my health benefits, I want to stay on VA.gov to do that whenever possible, and stop being sent to the national portal. 

### Notes
- [Slack thread here](https://dsva.slack.com/archives/C04DRS3L9NV/p1721936072401309) started by AJ (auth experience team) about updating links and when that should take place. Kaitlin suggested a discovery ticket to look at clearer messaging around the new experience on the MyVA page before making these updates. 
- Current design in staging

<img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d02989010f5587482ea677c60d395bc8a5c2f4e9/image.png" alt="image.png" />

Possible tasks:
- [x] Do discovery around differences between links on MyVA vs. My HealtheVet home page (icons, link text, order of links, etc.)
- [x] Mock changes that may be helpful if they are different than what MyVA team already has behind feature flag & get peer-review from teammates
- [x] Share with Kaitlin for feedback
- [x] Connect with auth experience team to discuss & figure out what is feasible / what timeline may look like
- [ ] Have a data collection plan to understand the performance of those links and the traffic they funnel into MHV on VA.gov
- [ ] Discuss with Kaitlin, Patrick, Chante, Mikki, auth experience crew, etc. 

## Acceptance criteria
- [ ] A clear plan for updating My VA health-related content is detailed and approved by My HealtheVet OCTO stakeholders as well as Auth experience stakeholders. 
- [ ] Follow-on tickets related to implementation have been drafted as necessary

**Comment by sterkenburgsara** [comment]
Update: Discussed with Kaitlyn in 1:1 on 8/2/2024. Notes below:
* Look at current traffic to the various links under healthcare on MyVA page to understand % clicks to each of these 
* Sounds like link updates are already behind a feature flag on auth experience team, but some of hte link text doesn't work anymore and may require a few updates - see if that's the case and sync with auth experience devs and/or AJ to understand.
* Do we want to send users to tool landing pages or to the specific task-driven sub-URLs? (mock up both ways)
* If one of these 5 links gets low traffic, potentially swap for a link to the My HealtheVet landing page
* Update iconography to more closely match what we're using on the MHV landing page 
* Potentially update the H2 "healthcare" on the MyVA page to say "My HealtheVet"
* Keep this update simple and don't overthink it

**Comment by wesrowe** [comment]
This is lower priority than #89054 due to the MR launch dependencies of the latter.

**Comment by sterkenburgsara** [comment]
Update: discovery work complete & explored some different things in Figma here ([mocks here](https://www.figma.com/design/78M7pwgz2mU64WRiCwMVzE/MHV-Figma-Template?t=yMxrtFi59gokbvoz-0)). Received feedback from Kaitlin & Jonathan

Got approval from Kaitlin on design mocks on 9/4/24 & sent file onward to MyVA team via [Slack message here](https://dsva.slack.com/archives/C909ZG2BB/p1725472881748009). Will try and find a time to connect with them this week or next. Hopefully within the bounds of this sprint.

**Comment by sterkenburgsara** [comment]
Update: sync with Auth Experience team is scheduled for 9/18 at 3pm ET. Will not happen in this sprint & this ticket will move over. 

@LynneJohnson224 should I move this to blocked until then?

**Comment by sterkenburgsara** [comment]
@LynneJohnson224 @wesrowe  any thoughts on comment above?

**Comment by LynneJohnson224** [comment]
@sterkenburgsara I'll remove this from the current sprint. we can replan/add to a sprint after the meeting when we're ready to pick up the work.

**Comment by sterkenburgsara** [comment]
@LynneJohnson224 I don't think we should remove it from the sprint - over half of the tasks were completed by me this sprint. I just can't finish the other ones until the sync with the MyVA team happens next week (in the next sprint).

**Comment by sterkenburgsara** [comment]
Update: had sync on 9/18/24 with MyVA team and PO Chante. A few action items from the meeting were some questions around timeline and expectations for when these links would change, and MyVA wants to discuss our proposal to treat a link to the My HealtheVet home page differently, as well as dropping the second person "your" in link text. Chante took action items to connect with CAIA and Kaitlin Fink with these questions and said she would circle back.

**Comment by sterkenburgsara** [comment]
Update: follow-up [slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1726761215556829?thread_ts=1726757155.492599&cid=C0581MN69TJ), where it sounds like we are punting these updates until Medical Records crosses the finish line into Phase 1 (is at 100% of users) later this fall.

**Comment by wesrowe** [comment]
### Analytics notes
For Oct 1-7, My VA health links traffic ([GA4 exploration](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/7RSbd1NOTF2MVjudVvMHtw)):
- Refill and track prescriptions: 73k
- View your messages: 53k
- [Go to your inbox: 53k] _same clicks?_
- Sched/mng appts: 48k
- Get your VA medical records: 21k
- [Get your VA medical records _and lab results_: 21k] _same clicks?_

For same period:
- Go to My HealtheVet: 5.9k – I think this might be the button in an alert? "Go to My VA Health" got very similar clicks (5.8k)
- MHV tab in header doesn't appear in this report, not sure why not

**Comment by sterkenburgsara** [comment]
Only thing holding it up is MR moving into Phase 1. The My VA team didn't
want to deal with adding specific parenthetical link text for that one tool
that indicated a different portal experience b/c it throws off the design.
I think we could circle back now & discuss!
