### ISSUE TITLE
Midpoint Review - Design Feedback - Unified Appointment Experience, Patient Check In, Add Upcoming Appointments

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#89478]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Please watch the recording for all of Matt Dingee's and Ryan Thurlwell's feedback.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: Look at your additional info components and the amount of content in them. Review the [guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else) on how much content should be in additional info components. Specifically the "How to set up your device" additional info.
- [x] Must Matt Dingee: The language toggle has been updated. The [updated component is available in Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=3933-3682&t=oUjQwPgjXXR3hyPf-1) with the web-component to come soon (likely in September).

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by benbrasso-agile6** [comment]
@outerpress take a look at the first MUST comment

**Comment by benbrasso-agile6** [comment]
@zach-park until we meet with engineers to talk about if we're going to be including video appt types, just focus on the second MUST item

**Comment by outerpress** [comment]
@laurwill what do you think about moving the "how to set up your device" instructions to a separate page, similar to how we're handling the [medication review language](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=544-13770&t=IlXJJocUbtZmjlKX-4)?

**Comment by laurwill** [comment]
@outerpress I think that would be fine, and as an added benefit, people who aren't signed in to the tool and looking for this info right before an appointment could search "how do i prep for a va video appointment" etc and find unauth instructions

**Comment by outerpress** [comment]
@benbrasso-agile6 design ticket #89998 will cover the video visit work. Appointments product folks will need to prioritize this one, so I'm not sure when this will get picked up.

**Comment by benbrasso-agile6** [comment]
Thanks, Peter. Same comment I left on content feedback. LOROTA version will work on a fallback solution to not hold up the release (plus, we can't do the same things as full auth).

**Comment by zach-park** [comment]
Switched out the language toggle: https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1889-19465&t=brMk5eREqc92WiZm-1

**Comment by benbrasso-agile6** [comment]
Blocked; waiting for https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/89876 to be resolved

**Comment by benbrasso-agile6** [comment]
This has been resolved. No more add info component: https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4254-10780&t=rEMYmHA74jqUmT3L-4

@outerpress I believe you're tracking this work separately. Ok to close this ticket that's tied to a check-in collab cycle touchpoint?

**Comment by outerpress** [comment]
@benbrasso-agile6 yep! I have this captured on the appts side in #89998
