### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#89487]
### Your Name

Jared Pace

### Your GitHub handle (Flipper UI access is managed through GitHub)

@pacerwow

### Team, Role, and Company of the target individual

DBEX Disability Benefits Team 1 (T-REX), Product Manager, Agile Six

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need this access to perform UAT testing for my team's new feature.

**Comment by AnthonyWFlowers** [comment]
Requestor is a Federal User- placing the "Awaiting Approval" tag for review

**Comment by pacerwow** [comment]
@AnthonyWFlowers this access is needed for UAT testing for a feature we plan to take through Staging Review next week. Is there a possibility this access could be granted today?

**Comment by AnthonyWFlowers** [comment]
Greetings @pacerwow let me take a look and see what we can do please standby.

**Comment by AnthonyWFlowers** [comment]
Greetings @pacerwow I was able to confirm you are in Atlas- no need for OCTO confirmation

You have now been added to Flipper UI lower environments. Please let me know if you have any additional questions or concerns.
