### ISSUE TITLE
[Data] 10-10EZ AND 10-10EZR: Monitor EZ and EZR Traffic during HEC text blast for PG 7 and 8 (9/27-10/31)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#89489]
As a team member, I would like to understand the usage we see after the HEC text blast so that I know when and how Veterans are using the EZ/EZR, and I can help the team make improvements based off of this usage.

- [ ] **Success 1: We have, and report out, usage spikes as a result of the text blast**
- [ ] **Success 2 (Stretch Goal): We use this as an opportunity to learn HOW Veterans are using EZR and come up with recommendations for improvements based on this**

**Comment by luis-simauchi** [comment]
current source of data from GA4
https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/JRQi-lO0SlysTK9FZ22Evw

**Comment by luis-simauchi** [comment]
list of campaign names used during this period of text blasts
ar_pact_hc_oy4
ar_pact_benefits_oy4
ar_pact_oy4
ar_benefits_oy4
ar_pact_benefits_oy4_sur
ar_pact_oy4_sur
ar_pact_benefits_oy4_nca
ar_choosevabenefits_oy4_housing
ar_q1_oy4
ar_pact_hc_oy4_span
ar_pact_hc_oy4_aav
ar_benefits_oy4_housing
ar_pact_benefits_oy4_fraud
ar_pact_benefits_oy4_aav
ar_pact_hc_oy4_wv

**Comment by luis-simauchi** [comment]
150k texts are going out to Veterans in PG 7/8  on Oct 16! For those in 8e and 8g they should be directed to the EZ to re-apply, the rest will be directed to the EZR

**Comment by luis-simauchi** [comment]
the PG 7/8 email blast. 900,909 total emails sent @ Oct 9th

**Comment by luis-simauchi** [comment]
spreadsheet with raw results:
https://docs.google.com/spreadsheets/d/1SnHhigrQJvRLpUkPfBV6nerkBv9uWaz8T--gNCFtqic/edit?gid=983592217#gid=983592217

**Comment by luis-simauchi** [comment]
summary
the text blast / email blast sent during the month of oct did not materialize a significant amount of extra submissions or traffic on the HCA or the EZR compared to the previous months
measured by % of submissions & % of traffic per month
