### ISSUE TITLE
GIDS: Only include SCO data with a valid priority values in version generation.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8948]
As a developer, I need to update the GIDS version creation to only include SCO data with valid priority values so that the profile pages are displayed appropriately.

## Assumptions:
1. N/A

## Acceptance Criteria
1. SCO data with a priority other than "Primary" OR "Secondary", non case-sensitive, is not included in new GIDS version creation.

## Supporting Artifacts:
1. [Original SCO File Data Requirements.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4609466/Original.SCO.File.Data.Requirements.docx)
2. [SchoolCertifyingOfficial Data.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4609469/SchoolCertifyingOfficial.Data.csv.zip)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/655

**Comment by sonntag-adam** [comment]
Invalid data is being handled.
##
Invalid priority in csv and database of 1
![Screen Shot 2020-05-13 at 1.14.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/96b14c91-cd20-4488-b183-8ffb33d03495)
![Screen Shot 2020-05-13 at 1.16.25 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2dc779e3-e1ff-48e2-9c02-81108b561ae7)
##
Does not show in versioned
![Screen Shot 2020-05-13 at 1.22.32 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/678597c0-58e0-4741-8310-88a0f1ec788f)
##
Front end 
![Screen Shot 2020-05-13 at 1.16.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/409f021c-cbe6-414b-a27a-c52261399a30)

**Comment by sonntag-adam** [comment]
Invalid priority in csv being null
![Screen Shot 2020-05-13 at 1.33.25 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/95cb09d6-a95f-4036-90a9-a87e4d92c59d)
##
Invalid priority in database being null
![Screen Shot 2020-05-13 at 1.33.40 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cbfc5680-1aea-49d3-be18-a4ab60a558f4)
##
Does not show in versioned
![Screen Shot 2020-05-13 at 1.33.49 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/00141e0d-70fe-4579-8bfe-3bacfdd1c47a)
##
Front end
![Screen Shot 2020-05-13 at 1.34.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4831a298-dc72-44e3-9063-71c0cb1086f5)

**Comment by sonntag-adam** [comment]
Case sensitivity does not matter and still shows results
![Screen Shot 2020-05-13 at 2.18.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/edfe2d73-4b85-4337-ae95-e49210e4110b)
##
![Screen Shot 2020-05-13 at 2.36.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ebcb1f0f-4d47-40ce-8c8c-c9b1433298e2)
![Screen Shot 2020-05-13 at 2.36.46 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7d8112ec-8acd-4870-8052-72bd7c11e1cb)
![Screen Shot 2020-05-13 at 2.37.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1f1077a2-4958-4c84-b175-56d906bbfb3c)

**Comment by sonntag-adam** [comment]
In staging, closing story.
