### ISSUE TITLE
Add "Prepare for your appointment" section to community care appointments

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#89495]
## Issue Description
Add a "prepare for your appointment" section to community care upcoming and canceled details pages. These appointment types do not include the "how to set up your device" instructions for video appointments.

## Requirements

- [ ] The `va_online_scheduling_med_review_instructions` feature flag is on

---

- [x] When the user opens a community care appointment
     A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=50-4423&t=IlXJJocUbtZmjlKX-4)
       And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/)
      
<br />

- [x] When the user opens a canceled community care appointment
        A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=356-8649&t=IlXJJocUbtZmjlKX-4)
       And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/) 

Additional notes:
- The new section shouldn't appear for past appointments - just upcoming and canceled. Past appointments are kind of a mini-medical record, with (soon) info like after-visit summary and travel pay, so we treat those differently. 

- The link should open in the same tab since it's a va.gov link and there's no risk of data loss. See guidance on opening external links.

- The content under the heading has a font size of 16px, while the link is 16.96px (which is the new standard base size) - see screenshot below. Both should be 16.96px.
![Screenshot 2024-07-29 at 3 13 58 PM](https://github.com/user-attachments/assets/05ffb2c3-d417-417c-9fb4-411fa2b403ad)

- The content under the heading should ideally be wrapped in some kind of semantic tag `(like <p>)` to help screenreader users navigate - see the paragraph elements section in this [WebAIM article](https://webaim.org/techniques/screenreader/#navigating). Please notify the team if this is going to make it tricky to get the spacing right.

---

- [x] The changes are approved by the UX/UI team and any relevant stakeholders.
- [ ] The updated wording is reflected in user guides and help documentation where applicable.

## Design

[Mockups](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32911&t=MybgwPnCCJcgmy0u-4)

## Development Checklist
Background: the `va_online_scheduling_med_review_instructions` toggle is on 

- [ ] Task 1
- [ ] Task 2

### Design Assets
Not needed

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89495?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
Product and UX will validate in staging. cc: @outerpress

**Comment by outerpress** [comment]
@ldelacosta I haven't had luck digging up test users with CC appts. I found some canceled under Grethel, but the section wasn't showing up - I don't know if the FF is on for that user though. Will reconnect on Monday to finish testing.

**Comment by JunTaoLuo** [comment]
The FF is turned on in staging, and I see that there's a CC appt with the section for Cecil Morgan:
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTR0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5b26cdd70402bdd2bc9930b37fd066a31b49fc8/image.png" alt="image.png" />
Not sure why you weren't seeing on Friday though.

**Comment by outerpress** [comment]
Upcoming looks and sounds great. Working with @ldelacosta on getting a test user with a cancelled CC appointment so I can validate that piece.

**Comment by ldelacosta** [comment]
Moving to External Dependencies. Waiting for SPL team to create phone appts in staging. Once they have created it, we will resume testing. cc: @outerpress

**Comment by ldelacosta** [comment]
VAOSR-8434 ticket to SPL team

**Comment by outerpress** [comment]
Also VAOSR-8453

**Comment by ldelacosta** [comment]
@outerpress - try: joakim.j.jee@id.me

**Comment by outerpress** [comment]
@ldelacosta thank you so much! This looks great, validated

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
