### ISSUE TITLE
EDU: Add new recipient to daily report email distribution

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8949]
As a new education team member, I need to receive the daily reports so that I can effectively perform my responsibilities.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The email address "kathleen.dalfonso@va.gov" is added to the daily email reports in production for the following reports:
    a. Daily Spool Report
    b. Daily YTD Report

## Supporting Artifacts:
1. N/A

**Comment by shawkey-daniel** [comment]
PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-api/4253
