### ISSUE TITLE
FE | Contact Info Refresh | Change default behavior to "go back to edit"

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89516]
## Background 
Users have been accepting address overrides too quickly and erroneous address data has made it to backend systems. This story is to make the override acceptance process a little "stickier"

The buttons in the screenshot below should be reversed (the "go back and edit" should be the thing we 'default too' so users actively have to select the override option) 

![image](https://github.com/user-attachments/assets/456e7b85-3578-4c89-ba00-0033ff363806)

## Acceptance Criteria 
- [ ] the order if the buttons is reversed

**Comment by mtcA6** [comment]
@asiisii can you size this?

**Comment by asiisii** [comment]
@mtcA6 as discussed I will also be updating the button label `Update` to be `Use this address` to match our design

**Comment by mtcA6** [comment]
@asiisii can you size this? 2?

**Comment by mtcA6** [comment]
tested w user 202 and the functionality looks good!
