### ISSUE TITLE
Staging Review Accessibility findings for VAMC LeftNav 

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#8951]
**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This epic will contain the accessibility staging review findings issue tickets.

## Point of Contact

**VFS Point of Contact:** Jennifer

@1Copenut - my findings are ready for your review.

**Comment by jenstrickland** [comment]
@mmiddaugh One item on the staging review request ticket:
>  Ensure end-to-end tests - including the axe check, pass (required)

Can y'all verify that e2e tests include the axe check for the side nav and are passing?

**Comment by 1Copenut** [comment]
This review looks good. VSP has added one issue to the epic after talking with Jennifer.

**Comment by mmiddaugh** [comment]
The following issues have been tagged with the "Blocking-release" label and will be resolved before moving to Prod. 

- [#8961] 
- [#8958] 
- [#8974] 
- [#8975]

The other issues will prioritized for resolution in future sprints.

**Comment by mmiddaugh** [comment]
Closing this epic as all associated issues are closed
