### ISSUE TITLE
FE | Contact Info Refresh | Reword the military base outside US checkbox

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89514]
## Background 
[See this ticket for the design work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90194), this ticket is to implement whatever the ultimate recommendations are we receive from the design story 

[Updated Figma file](https://www.figma.com/design/9XT1LkxHFs4EPTkWMrp9l0/%2390194---AE-Profile---Reword-the-military-base-outside-US-checkbox?node-id=0-1&t=B1IId3FBuh2l4fcf-0) with the revised military base checkbox text  
this checkbox appears on:
- mailing address 
- home address
- bad address indicator (BAI) edit page  

## Tasks 
- [ ] update, in code, the checkbox text. Change it to "I live outside of the United States on a U.S. military base." (Note the final period.)

## Acceptance criteria 
- [ ] the mailing address, home address. and BAI forms are updated with new language for the military base checkbox

**Comment by twoangstroms** [comment]
@asiisii Update the link and Tasks.

**Comment by asiisii** [comment]
meeting with Adam Whitlock to talk about the `ProfileInformationFieldController` component before working on the component on 08/29

**Comment by mtcA6** [comment]
Weird I see your PR merged but it doesn't appear to have impacted staging. See user 202

![image](https://github.com/user-attachments/assets/797bd1f9-0960-4b74-89dc-62b08dd20a58)

**Comment by asiisii** [comment]
@mtcA6 My change hasn't been deployed to staging yet thats why

![Screenshot 2024-09-02 at 9 58 34 PM](https://github.com/user-attachments/assets/a59a7700-5bb8-45bc-99f4-96fde904b5b5)

**Comment by mtcA6** [comment]
Tested in staging w user 202, this looks good! 


![Image](https://github.com/user-attachments/assets/189cacb7-a673-4057-8ed8-f3b46b6542d1)
