### ISSUE TITLE
FE | Contact Info Refresh | (spike) VA Profile Override Behavior Updates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89517]
## Background 
VA profile is planning to change the address validation service behavior 

PM ticket where we built a workbook analyzing the error messages may be helpful but not a requirement to work this ticket: 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89513

### Today
- VA profile sends a validation key for ALL items, even in scenarios where there is a "critical" or "fatal" error 
 

_(Travis doesn't know how VA Profile defines critical or fatal, we can ask but I'm not sure it matters, they've given us a set list of 15 errors that will NEVER be accompanied with an override key)_ 

### New Behavior
- VA profile will no longer send a validation key in all cases 
- VA.gov profile behavior needs to change: 
     - if a user gets one of the non-overridable errors **or** no override key is returned from VA Profile 
          - then the user cannot be allowed to save
          - and the options should be "go back and edit" or "cancel" as the user should not be permitted to save the address 
               - if we do offer a cancel button we'd have to make sure it wasn't a single click destructive act so we'd have to fire off the cancel modal
          

#### list of errors where we will no longer receive an override key 

Severity (Address Service) | Key | Code | Description
-- | -- | -- | --
FATAL | SpectrumServiceError | ADDRVAL101 | The Spectrum Service returned an error
FATAL | InvalidAddressError | ADDRVAL102 | The Spectrum Service returned an address error
FATAL | CountryLookupServiceError | ADDRVAL103 | The Country Lookup Service returned an error
ERROR | InvalidRequestError | ADDRVAL105 | The request was invalid
ERROR | requestCountry.countryName.Size | ADDRVAL106 | size must be between 0 and 255
ERROR | stateProvince.name.Size | ADDRVAL107 | size must be between 0 and 255
ERROR | UnrecognizedPostalCode | ADDRVAL113 | Postal code entered could not be found
ERROR | CountryLookupUnavailable | ADDRVAL114 | The Country lookup service could not be reached
ERROR | InvalidRequestCountry | ADDRVAL201 | Only one of either country name or country code is required
ERROR | InvalidRequestState | ADDRVAL202 | Only one of either state name or state code is required
ERROR | InvalidRequestStreetAddress | ADDRVAL203 | One of addressLine1, addressLine2 or addressLine3 must be provided
ERROR | InvalidRequestNonStreetAddress | ADDRVAL204 | The request needs at least one address line and one non-address line field populated in order to process the request
ERROR | InvalidRequestPostalCode | ADDRVAL205 | Only one of either zipCode5 or international postal code is required
ERROR | MultipleAddressError | ADDRVAL206 | Multiple matches found for this address
ERROR | MissingReferenceData | ADDRVAL207 | The Address Validation API does not have the databases necessary to validate this address completely

## Acceptance Criteria 
- [ ] we know how we're handling these error codes today and once we complete this ticket we should create a follow up ticket for ensuring the FE can handle this behavior 
- [ ] we're ready to support https://github.com/department-of-veterans-affairs/va.gov-team/issues/91168
- [ ] we have an idea of how to work through the broader list of error messages in this ticket #91169

**Comment by mtcA6** [comment]
@asiisii we didn't talk about this one, this one is probably the biggest change but also the most difficult to prepare for

**Comment by asiisii** [comment]
@tpharrison Yes!!

**Comment by tpharrison** [comment]
Ok - just let me know when you want to meet.

**Comment by asiisii** [comment]
Update: meeting with Tom on Sep 17 to go over the error codes

**Comment by asiisii** [comment]
Closing this ticket as, upon review, we confirmed that the case where we don't receive a `validationKey` was already being handled. While reviewing, we also identified additional improvements that are documented in a new ticket. You can find the full description and details in the new ticket:

**Ticket:** [#93272](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93272)
