### ISSUE TITLE
Yellow Ribbon - Load Test

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8952]
As part of the privacy, security review for Yellow Ribbon, 

We need to:
* Load test the endpoint. See VSP's load-testing docs for a starting place.

**Tasks**
- [x] Load test endpoint (follow [this documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/load-testing/README.md) to get started)

When complete please let Stephanie know so we can alert Andrew

**Comment by stephorkandatx** [comment]
@kelsonic feedback from privacy, security review.

**Comment by kelsonic** [comment]
Results from load testing:

Type | Name | # requests | # failures | Median response time | Average response time | Min response time | Max response time | Average Content Size | Requests/s | Requests Failed/s | 50% | 66% | 75% | 80% | 90% | 95% | 98% | 99% | 99.9% | 99.99% | 99.999 | 100%
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
GET | /v0/gi/yellow_ribbon_programs?name=abilene | 44 | 0 | 160 | 169 | 148 | 228 | 803 | 0.01 | 0.00 | 160 | 170 | 170 | 170 | 180 | 220 | 230 | 230 | 230 | 230 | 230 | 230
GET | /v0/gi/yellow_ribbon_programs?name=argosy | 44 | 0 | 170 | 181 | 153 | 290 | 12349 | 0.01 | 0.00 | 170 | 180 | 180 | 180 | 260 | 260 | 290 | 290 | 290 | 290 | 290 | 290
GET | /v0/gi/yellow_ribbon_programs?name=university | 44 | 0 | 540 | 569 | 166 | 5619 | 12501 | 0.01 | 0.00 | 540 | 600 | 630 | 640 | 710 | 830 | 5600 | 5600 | 5600 | 5600 | 5600 | 5600
GET | /v0/gi/yellow_ribbon_programs?name=yeshiva | 44 | 0 | 160 | 172 | 148 | 264 | 2911 | 0.01 | 0.00 | 160 | 170 | 170 | 170 | 220 | 240 | 260 | 260 | 260 | 260 | 260 | 260
None | Aggregated | 176 | 0 | 170 | 273 | 148 | 5619 | 7141 | 0.05 | 0.00 | 170 | 180 | 200 | 240 | 570 | 640 | 770 | 870 | 5600 | 5600 | 5600 | 5600

**Comment by stephorkandatx** [comment]
@kelsonic sent those over to Andrew. Thank you!

**Comment by stephorkandatx** [comment]
Separated the request to review the query for performance issues into a new ticket, as discussed in stand-up. #9127
