### ISSUE TITLE
IAM Cleanup

### ISSUE THREAD

**Issue by jsev-io** [department-of-veterans-affairs/va.gov-team#8954]
# IAM Cleanup Tasks
_This issue exists to outline some changes for our current IAM configuration. While some of these tasks are immediately actionable, others require collaboration and possible communication with other teams to prevent possible interruption._
 
## User Story or Problem Statement
Problem description. How might we better structure IAM resources ?

## Goal
_What outcome(s) do we want to see?_
- Full assessment of current state of Identity and Access security in AWS
- More streamlined IAM Configuration
- Reduce the permission/group sprawl
- Better segmentation of groups / teams
- RBAC or ABAC
- Enforcing least privilege in the permission design
- Simplify the onboarding process
- Multiple AWS accounts???
- Security Hub Notifications directly to Slack

## Objectives or Key Results this is meant to further
--- Security and User Resource Management

### Identify and Plan
- [X] Identify Redundant Groups / Attached Policies
- [X] Identify Directly attached policies
- [X] Identify all users with AdministratorAccess policy attached

## Acceptance Criteria
_What will be created or happen as a result of this story?_
- Planning and discovery completed

**Comment by ricetj** [comment]
Julian to come up with an updated plan and present it to the team.

**Comment by jhouse-solvd** [comment]
@jsev-io to break this out into separate tasks
