### ISSUE TITLE
Count of supporting documents for email notifications

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#89546]
As a CHAMPVA applicant, I need verification of how many supporting documents were received so that I know that my supporting documents were received along with my application.

## Acceptance criteria
Add a variable with a count for all supporting documents update that does not include the form itself that can be included in VA-notify emails. The user should see something to the effect of "We've received your form 10-10d and the X supporting documents you provided." We'll need a variable we can use in VA-notify to populate X.

This requirement was pulled from https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/88164 and carried over here.

**Comment by balexandr** [comment]
@baltes Per our brief conversation yesterday, this can be closed as it was done in a previous ticket
