### ISSUE TITLE
Update to the upcoming appointment details page for Medication Instructions 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#89551]
## Description
Part two to address the items found during testing from #85118, #86473 and #85825 

This work will be applied for in person appointment, phone appointment and Claim Exam appointment

## Requirements

- The new section shouldn't appear for past appointments - just upcoming and canceled. Past appointments are kind of a mini-medical record, with (soon) info like after-visit summary and travel pay, so we treat those differently. 

- The link should open in the same tab since it's a va.gov link and there's no risk of data loss. See guidance on opening external links. (not applied to the Claim Exam appointment)

- The content under the heading has a font size of 16px, while the link is 16.96px (which is the new standard base size) - see screenshot below. Both should be 16.96px. (not applied to the Claim Exam appointment)
![Screenshot 2024-07-29 at 3 13 58 PM](https://github.com/user-attachments/assets/657ef3de-f31f-406c-94da-2c985b10c1d7)

- The content under the heading should ideally be wrapped in some kind of semantic tag `(like <p>)` to help screenreader users navigate - see the paragraph elements section in this [WebAIM article](https://webaim.org/techniques/screenreader/#navigating). Please notify the team if this is going to make it tricky to get the spacing right.

---

## Development Checklist
Background: the `va_online_scheduling_med_review_instructions` toggle is on 

- [ ] Task 1
- [ ] Task 2

### Design Assets
Not needed

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89551?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
Product and UX will validate in staging. cc: @outerpress

**Comment by ldelacosta** [comment]
VAOSR-8434 ticket to SPL team

**Comment by outerpress** [comment]
Just waiting on a canceled Video at VA appt to finish validating #85118 (see ticket https://issues.mobilehealth.va.gov/browse/VAOSR-8453)

#86473 and #85825 are good to go.

**Comment by outerpress** [comment]
@ldelacosta there's an issue on Prod that causes Video at VA appts to show as video appointments. So I'm not sure how to move this one forward without a resolution there. From [VAOSR-8453](https://issues.mobilehealth.va.gov/browse/VAOSR-8453)

> My understanding is that we are not able to set up a "Video at a va location" appointment, due to a defect which blocks us from setting up that type of video appointment. [VAOSR-6974](https://issues.mobilehealth.va.gov/browse/VAOSR-6974) PROD; Store Forward Video Visits Missing VVS Kind - Vets sees as @home instead of @VA facility - VA-MAP JIRA

**Comment by outerpress** [comment]
@vbahinwillit was able to recreate these appointments in his local environment - [screenshots](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=951-9&t=mg01tNd6IOIbovMr-4). So I'm calling this good to go @ldelacosta . Like the other tickets, I'll retest video at va appointments when they're available on staging, but this can be closed out.
