### ISSUE TITLE
Design intent Collaboration: STEM Stand-alone, VA Form 22-10203

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#8956]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [x] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/10203_product_outline.md)
- [Lo-fi mockups](https://bahdigital.invisionapp.com/share/MUIADS5R2HC)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Amy Knox (Knox_Amy@bah.com), Cindy Cruz (Cruz_Cindy@bah.com), Jen Jones (Jones_Jennifer2@bah.com)**
- Product Manager (optional): **Darrell Neel (Neel_Darrell@bah.com)**
- DEPO design lead (required as applicable): **Matt Self**

## Scheduling
Preferred dates or times: 
Thurs. 5/14, 1:30 - 2pm
Fri. 5/15, 2-2:30pm

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Scheduled Thurs. 5/14, 1:30 - 2pm
