### ISSUE TITLE
526e Missing Information Message - content update

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#89576]
Users who are missing the following: SSN, DOB, EDIPI/Birls ID, Participant ID / File ID, must contact the 1-800-MyVA411 to get the missing information added to their MPI. 

Currently a message exists in production (release July 2024) with some misleading information. Changes to the content are needed to more accurately support the Veteran: 

**Current Message Content**
> We’re missing your {formattedIdentifiers}. We need this information
>         before you can {titleLowerCase(title)}. Call us at{' ’}
>         <va-telephone contact={CONTACTS.HELP_DESK} /> (
>         <va-telephone contact={CONTACTS[‘711’]} tty />) to update your
>         information. **We’re here Monday through Friday from 8:00 a.m. to 9:00
>         p.m. ET.** Tell the representative that you want to add this missing
>         information to your file.
> We’re missing your {formattedIdentifiers}

**Current image in production (wrong information is highlighted in pink):** 

![Image](https://github.com/user-attachments/assets/6f5d626b-856a-4ce3-8664-a86026cc3de4)

### Notes
[CONTACTS.HELP_DESK](https://github.com/department-of-veterans-affairs/component-library/blob/52268bf59d4b2dd3a8250ec03a44f0568c6c7e81/packages/react-components/src/components/Telephone/contacts.js#L55)

### Acceptance Criteria: 

- [ ]  Change the content "We’re here Monday through Friday from 8:00 a.m. to 9:00 p.m. ET." to read "We're here 24/7."
- [ ]  Remove the last paragraph/line that list the same missing information again 

If the missing information is: EDIPI and/or BIRLS ID, then add the following content per these conditions: 
- [ ] If both BIRLS and EPID: "It's ok if you don't know your BIRLS ID or EDIPI ID."
- [ ] If just BIRLS: "It's ok if you don't know your BIRLS ID."
- [ ] If just EDIPI: "It's ok if you don't know your EDIPI ID."
- [ ] If just Participant ID: "It's ok if you don't know your Participant ID."
- [ ] If all three then Participant ID, BIRLS and EPID: "It's ok if you don't know your BIRLS ID, EDIPI ID or Participant ID."
        etc. for any of the combinations of the three missing IDs 

### Examples: 

We're missing your `Social Security Number.` We need this information before you can file for disability compensation with VA Form 21-526EZ. Call us 800-698-2411 (TTY: 711) to update your information. We're here 24/7. Tell the representative that you want to add this missing information to your file.

We're missing your `BIRLS ID`. We need this information before you can `file for disability compensation with VA Form 21-526EZ`. Call us at `800-698-2411 (TTY: 711)` to update your information. We're here 24/7. It's ok if you don't know your `BIRLS ID.` Tell the representative that you want to add this missing information to your file.

We're missing your `BIRLS ID and EDIPI ID`. We need this information before you can `file for disability compensation with VA Form 21-526EZ`. Call us at `800-698-2411 (TTY: 711)` to update your information. We're here 24/7. It's ok if you don't know your `BIRLS ID or EDIPI ID`. Tell the representative that you want to add this missing information to your file.

 

```[tasklist]
### Downstream dependency
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89179
```

**Comment by juliepedtke** [comment]
[Update from CAIA](https://dsva.slack.com/archives/C01K37HRUAH/p1722353588559869): for the pink highlight, we can replace the copy with... 
> We're here 24/7.
The phone number displayed should stay the same (eg we don't refer to it as "MyVA411")

CAIA asked a good question about defining what a BIRLS ID is, because this is likely an unfamiliar term to Veterans. We know the help desk reps are familiar with it, but I'd like to get more clarity on how they use it, how we might better describe it to the Veteran, etc. @lisacapaccioli to reach out with these questions for them. ([See Slack thread.](https://dsva.slack.com/archives/C05MPTGMX0E/p1722348831285629))

**Comment by lisacapaccioli** [comment]
Sent an email asking for more information.

**Comment by juliepedtke** [comment]
Info we learned from Jeremy Haas:

- Are Veterans familiar with what a BIRLS ID is?  No, generally not.
- Is there another term that BIRLS ID might go by that is more familiar to Veterans and would make sense to the Help Desk? Not that I am aware of.  On a VA site it refers to BIRLS as “A tool the Center For Verification and Evaluation (CVE) uses to verify an applicant is an eligible Veteran”
- How would the Help Desk describe it to the Veteran (or wouldn’t they) if a message displayed that said it was missing and was needed?  It is a database similar to DEERS that contains military history, used to verify is the applicant is an eligible veteran
- Does the Help Desk know what to do if the BIRLS ID is missing? What if we called it something different? Ideally the error description would be modified to something along the lines of “An error occurred, we’ve found a mismatch in your BIRLS Record”
- 

Based on this, I'd like to consider adding a conditional sentence: "It's ok if you don't know your BIRLS ID." before "Tell the representative that you want to add this missing info to your file." Let's ask how much of a technical lift this would be!

**Comment by lisacapaccioli** [comment]
@juliepedtke Let me know if the two AC's above match your expectations. Thanks

**Comment by juliepedtke** [comment]
Yes that looks right! Just to be extra clear, the formatting will be the same as the original message (no actual bold - that just indicates the new text). And we don't currently repeat the missing identifiers in a second paragraph, right? So they would only be mentioned once at the beginning and we'd remove the second "We're missing your {formattedIdentifiers}" on both messages.

**Comment by lisacapaccioli** [comment]
@juliepedtke Actually we do repeat the missing identifiers in the second paragraph. Thomas copied that straight out of production.

**Comment by juliepedtke** [comment]
Oh interesting, it's not shown in the screenshot. My sense is it's not necessary to repeat it again, so I'd suggest removing.

**Comment by lisacapaccioli** [comment]
Sorry @juliepedtke thought of one more thing. The EPIDS ID, should we assume that we will display the new content "It's ok if you don't know your ..." if the missing information is EDIPI ID or BIRLS ID?

**Comment by juliepedtke** [comment]
Good catch... so those are two different IDs that would show up listed separately? I have all the same questions about EPIDS (do we know what it is, will reps know what it is, is it ok that Veterans don't know what it is) but don't want to hold us up... so feels like a safe assumption to treat it the same as BIRLS! 

If both BIRLS and EPID: "It's ok if you don't know your BIRLS ID or EPIDS ID."

If just BIRLS: "It's ok if you don't know your BIRLS ID."

If just EPIDS: "It's ok if you don't know your EPIDS ID."

**Comment by lisacapaccioli** [comment]
Yes, I do know that that EPIDS is familiar to the reps. I remember Jeremy mentioning that one. It was BIRLS that we didn't ask about. I think it will be safe to assume that Veterans don't (Thomas commented that his own father didn't).

**Comment by lisacapaccioli** [comment]
Message examples

### If the missing information is SSN, DOB, Participant ID / File ID, display the following content in the message:
We're missing your Social Security Number. We need this information before you can file for disability compensation with VA Form 21-526EZ. Call us 800-698-2411 (TTY: 711) to update your information. **We're here 24/7.** Tell the representative that you want to add this missing information to your file.
 
### If the missing information is: EDIPI and/or BIRLS ID, display the following content in the message:
We're missing your BIRLS ID. We need this information before you can file for disability compensation with VA Form 21-526EZ. Call us <u>800-698-2411<u> (<u>TTY: 711<u>) to update your information. **We're here 24/7.** It's ok if you don't know your BIRLS ID. Tell the representative that you want to add this missing information to your file.

**Comment by lisacapaccioli** [comment]
R&D is done, just need to implement the change.

**Comment by SamStuckey** [comment]
UPDATE: this is WIP, but i'm having delays with some environmental issues. Nothing project related, just stuff specific to my development environment. Working through them now

[Slack thread](https://dsva.slack.com/archives/C04U3EDUR3M/p1726161573227479)

**Comment by kylesoskin** [comment]
In some situations this screen shows up differently than is pictured above, it also uses different/mismatched verbiage to wat is described in the the acceptance criteria (We're here 24/7 vs We’re here 24 hours a day, 7 days a week.)
![Screenshot 2024-09-19 at 9 37 09 AM](https://github.com/user-attachments/assets/e29b58a9-2f80-48ce-93e1-1b28c9001984)

I am wondering where that screenshot came from and if it is outdated before implementing this

**Comment by lisacapaccioli** [comment]
@kylesoskin The screen shot (as mentioned right above it) is the current image and wrong text that is in production and needs to be changed. The acceptance criteria is correct in how it needs to change. Design doesn't need to create new images in Figma for content changes, but they do need a new image to put the in the Product handbook. We are waiting for this to be delivered to staging and tested to capture a new screen shot. If the acceptance criteria is not clear enough we can refine them better. If including the image is too confusing, we can remove it.

**Comment by kylesoskin** [comment]
@lisacapaccioli 
> The screen shot (as mentioned right above it) is the current image and wrong text that is in production 

My comment is saying that this does not seem true, what is in prod code is what is in my screenshot, which does not align with what is in their screenshot. I am saying that there are multiple versions of this page, that show up differently depending on the state/attributes of the user, and that verbiage between them is different, and that this ticket does not account for multiple possible states of what shows up on this page.

**Comment by kylesoskin** [comment]
Relevant code
# Were we decide which content to show in this area
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/Form526EZApp.jsx#L216-L238

# what we show if missing birls id or edipi
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/containers/Missing526Identifiers.jsx#L83-L94

# What we show when there is a missing DOB, Service, or Edipi/Birls (shouldn't get triggered because first thing should take precedence??) 
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/containers/MissingServices.jsx#L102


Need to verify how and when this gets triggered because the new component, that was made by Nathan, does not appear to be used for me locally.

**Comment by lisacapaccioli** [comment]
@kylesoskin OK. Thomas gave me the content that you are showing for missing BIRLS ID or EDIPI and Nathan gave me the screen shot. When Nathan is back we'll do another refinement for this and get some clarification on why we had a message that was different than what you are seeing. Thanks for the clarification. Moving this back to needs refinement.

**Comment by kylesoskin** [comment]
After further information, this discrepancy between how things are showing up locally vs in staging has to do with a variable that is not populating locally but does in staging.

`form526RequiredIdentifierPresence` is not present in the profile object locally, I think it might have something to do with mocked auth. I can try to figure that out, but might be easier just to instead make the change and get it into staging and check?
![Screenshot 2024-09-19 at 1 28 20 PM](https://github.com/user-attachments/assets/250e75bd-9b5b-4b1b-b127-d901bb9bf636)

**Comment by kylesoskin** [comment]
![Image](https://github.com/user-attachments/assets/d7fe3679-5ab5-401f-ab97-42c88da49383)
EDIPI missing state

**Comment by kylesoskin** [comment]
Remaining work

- [ ] add tests
- [ ] make PR
- [ ] merge

**Comment by nnicholas7** [comment]
A ticket has been created for VEO review. [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93826). Awaiting review and response.

**Comment by kylesoskin** [comment]
@nnicholas7 @lisacapaccioli 

If we look at this functionality, and you can see this in the last picture, it will show ALL missing things, from the list of what it checks, not just birls and edipi, there are other things it needs too. 

participantId: true,
birlsId: true,
ssn: true,
birthDate: true,
edipi: false,

are all checked, and all potentially able to show up in the verbiage.

For ssn and birthday it is probably fine that we dont tell them it is ok if they dont know it, they will know those. 

But do we need to account for participant ID too? IE tell them it is ok if that is not known also?

**Comment by lisacapaccioli** [comment]
@kylesoskin - I updated the AC's to include Participant ID. So any combination of the three IDs would have the extra content "if you don't know...". Thanks

**Comment by shannonkford** [comment]
@kylesoskin Makes sense to me to include participant ID as noted above. Just here to note that the final 3 screenshots do not match the acceptance criteria copy - the "We're here 24/7" is misplaced and should come after the sentence containing the phone number.

**Comment by kylesoskin** [comment]
@shannonkford Ah, great catch 🤦 , thank you

**Comment by kylesoskin** [comment]
@lisacapaccioli @shannonkford was there any preference on EDIPI vs EDIPI ID? It looks we were using EDIPI in the top part telling them what is missing and using EDIPI ID in the its OK message. I imagine we want these to be consistent, just need to know which is correct.

**Comment by kylesoskin** [comment]
New images/screenshots

![Image](https://github.com/user-attachments/assets/47759750-b088-40bd-995c-1e864b95a358)
![Image](https://github.com/user-attachments/assets/0aab7d96-106a-4c58-8f99-b8443926424a)
![Image](https://github.com/user-attachments/assets/45fd94ae-ee2d-4939-aefe-81edad28c716)

**Comment by lisacapaccioli** [comment]
@kylesoskin sorry, I didn't see your question about whether to include "ID" in EDIPI. I see you didn't and I think that is fine. R&D wrote the content, I just copied it. Thanks

**Comment by lisacapaccioli** [comment]
@kylesoskin @nnicholas7 
If we are not sure about "ok" vs. "okay" we can check with Julie, I used the content she provided. 

I need to let CC know that we fixed the content with the correct times and the release date. Just let me know what you think that date will be. 

I will be mentioning these product guides: 
[526.Benefits.Delivery.at.Discharge.v3.3.product.guide_SRT_10032024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDRrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b97f6e45ab8d5027f1fa4c9592d411255f2613ca/526.Benefits.Delivery.at.Discharge.v3.3.product.guide_SRT_10032024.docx)
[526EZ.Disability.Benefits.Claims.Product.Guide.v4.3.SRT_10022024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--321a8c39c43719d3ec2c733e54182071bbb5cf04/526EZ.Disability.Benefits.Claims.Product.Guide.v4.3.SRT_10022024.docx)

Thanks

**Comment by nnicholas7** [comment]
Lisa will check with Julie about the 'ok' vs 'okay'. 
The product guide update has been avoided and is ready for production. Other information about this ticket is located [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89179).

**Comment by rubensun** [comment]
Let's just use **OK** in capitals.

**Comment by lisacapaccioli** [comment]
Email to CC sent.
