### ISSUE TITLE
Toxic Exposure 1.0 New Forms Moderated Production Testing

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#89586]
This ticket is a placeholder for the effort required by the team to perform the TE 1.0 release. We'll update it with the decided upon traffic thresholds as determined by the team and documented in the release plan.

## Prerequisite:
- Complete Staging Review

### Tasks

- Identify users who will perform moderated production testing
- Communicate the test cases they will use
- Toggle the flag
- Participants perform the testing
- DBEX teams analyze results against established metrics in the Release Plan
- Use DD to monitor for anomalies
- If any issues, disable feature flag and create ticket(s) to address
- Create tickets for remediation as needed

### Addition Information
- David Reis and Emily Theis can help identify users who will perform moderated production testing
- We need to determine the tactics on how we'll compare the pdf against the VBMS claim to ensure completeness and accuracy of the pdf
- We need a decision on which test cases to use (and if our testers will use Test Rail as a guide)
- We will definitely want to test the Standard Claim + TE test case, other ones we're not sure about
- We need to coordinate if this will be synchronous (video call) or async

### Acceptance Criteria
 - If any issues, disable feature flag(roll back) and create ticket to address

### Notes and Considerations 9/6 after VBA Sync meeting
1 Emily - Is there a way to block the production "moderated testing" cases from being sent to Mail Automation?

* When performing Moderated Production Testing (MPT), we don’t want the submission to ping the service that triggers Mail Automation. This is part of Rapid Ready for Decision (RRD). T-REX can create a toggle to prevent this from happening.
* We also want to prevent an ITF from being created
* We don’t want testers to fill out a 4142, so exclude this from the test cases
* We should have a test case that includes uploading fake evidence documents. We’ll provide an image file for testers to use
* We want to prevent the backup path being triggered, as this would trigger a human creating a claim and we won’t have the ability to delete it as soon as it comes through. Ideally we should block this from happening.

3 Jared - How might we delete the submitted claims in VBMS? Who can do this? Similar to Emily's question. How will we communicate with potential testers?
* Kevin, VBA will help with deleting a claim. He’ll cancel the EP and delete documents. Matt can help as needed.
* To help Kevin, provide him a screenshot of the Review & Submit screen form data, or if needed provide him with the raw formData JSON
* Emily will create a spreadsheet to track test cases - this will help us understand if the submitted data is the same as the claim in VBMS & the PDF
* T-REX to edit the MPT email/Slack script to include that we’ll need volunteers to send their file number and email address to Kevin over a Teams chat or an encrypted email. To be done when requesting our 6-8 testers, whichever 3-4 respond or can do it.
* Schedule 30 minute sessions to perform MPT synchronously

**Comment by pacerwow** [comment]
Emily to support. Use existing test cases as a guide. In the past this was done synchronously.

**Comment by mchae-nava** [comment]
Noting we want this to be run synchronously, still need to be determined who will block adjudication once we start

**Comment by pacerwow** [comment]
Hi [name],

The Disability Benefits team working on form 21-526EZ is looking for ~6 VA employee Veterans to help test the upcoming release of the Toxic Exposure section in the online version of the 21-526EZ form and wanted to ask if you could help. Your task would be to submit two claims for disability compensation on va.gov and claim that your service-connected disability is related to toxic exposure. We’d provide you with instructions on both scenarios that you would use to submit your claim.

* While you'll be using a documented test case to submit your claim, you'll be submitting a disability claim with your real data, so a limited number of members of our team and our partners in VBA would be able to see your service-connected disabilities and some PII like file number. This claim, however, would be canceled by VBA, ITF blocked, and noted that it was a fake test, so there would be no affect to your disability payments if you have them.

* We’re scheduling this activity to be completed anytime on August 16th. You’re free to schedule this around your other commitments, and we estimate that this task will take approximately 30 minutes to complete. There is absolutely no pressure to be a participant!

If you’re interested and have availability, please reply to confirm your availability for either one of those dates by Friday, August 9th and send your file number to Kevin over a Teams chat.

Thank you in advance for helping veterans claim toxic exposure benefits online for the first time!

**Comment by pacerwow** [comment]
@mchae-nava Kevin Schneider

**Comment by mchae-nava** [comment]
Modifying slightly to request specific times that work for the volunteer next Friday


> If you’re interested and have availability, please reply to confirm your availability and any times that work best for you on Friday, August 16th, and send your file number to Kevin Schneider over a Teams chat.

**Comment by mchae-nava** [comment]
Sessions have been scheduled, this is currently on hold until those sessions are complete on Friday
