### ISSUE TITLE
10-10d: code/tech debt cleanup

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89589]
- Audit to review code and address any glaring errors/do code cleanup.

**Comment by michaelclement** [comment]
[Work here](https://github.com/department-of-veterans-affairs/vets-website/pull/31133)

**Comment by michaelclement** [comment]
To keep PR sizes small, split off into a second branch for this work. When the first PR is merged I'll then follow up with a second PR for the next branch and keep doing that until things are in a good stopping place.

**Comment by michaelclement** [comment]
Two PRs in progress:
- [Part 1](https://github.com/department-of-veterans-affairs/vets-website/pull/31133) (waiting on platform)
- [Part 2](https://github.com/department-of-veterans-affairs/vets-website/pull/31152) (in progress)

**Comment by michaelclement** [comment]
This work has been done - as far as review goes there's not really anything to be done, but if you're curious I can hop on a call and walk through what was cleaned up. It's all behind the scenes stuff. Thanks! @baltes @marywang2
