### ISSUE TITLE
10-7959c: test coverage verification 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89581]
- Verify that we have adequate test coverage and that what we have meets the required % recommended by [platform](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage).
- make updates per any changes that were made recently

**Comment by michaelclement** [comment]
| |Coverage|
|-|-|
|before|<img width="1149" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd01pQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5da0d8a7c4895b073f1e1bae540a9b9e9d73d574/7959c_tests_before.png" alt="7959c_tests_before.png" />|
|after|<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1FpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7df2c69016b58638aba49642e2a8036ae443ea62/Screenshot%202024-07-31%20at%2010.14.33.png" alt="Screenshot 2024-07-31 at 10.14.33.png" />|

**Comment by michaelclement** [comment]
[Work done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31125). Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes @marywang2 This has been merged in. To review, please see the screenshots above. Thanks!
