### ISSUE TITLE
CES-778 VPG: VPG: Investigate appointment search performance issues

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#89580]
CES-778 https://issues.mobilehealth.va.gov/browse/CES-778 
Appointment searches in VPG are taking considerably longer than either the CFA or vaos component searches.  Investigate the endpoint and create Stories for improving the response times.

*+Items to investigate+*
* Identify opportunities for caching reference data rather than live querying

**Comment by devin-mccurdy** [comment]
Testing of staging/SQA has shown that the performance issues of VPG taking longer than CFA or VAOS searches has been resolved.
