### ISSUE TITLE
Analytics Implementation or QA Support for Comparison Tool Section 103 Enhancement

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8959]
# Analytics Implementation or QA Request

## What this form is for
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

>  BAH EDU Application Support Team
>  Darrell Neel
>  Amy Knox
>  Dan Shawkey
>  Desiree Turner
>  Will McCormack

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    - BAH Education Application Team
    
- Provide the Domain where Google Analytics needs to be implemented
    - Comparison Tool Profile Page.  ex: https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
    
    - Identify if PII is passed in URL or title tag: N/A
    
    - Staging: https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
    - Production: https://www.va.gov/gi-bill-comparison-tool/profile/11929140
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Targeting a release of the enhancement between 05/25 - 06/05

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - https://www.va.gov/gi-bill-comparison-tool/profile/11929140
    - The display of the "Protection against late VA payments" indicator is based on the institution type.
    
    - *Other User Interactions*: We'd like to know when:
        1. Users click the text itself "Protection against late VA payments" 
        2. Users click through to "Learn more about the transition act" from the modal content

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A; publicly available

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A; publicly available

- Certain conditions/responses that need to be reviewed

    - N/A

- Additional Comments

    - Screenshots for reference:
![Interaction # 1](https://user-images.githubusercontent.com/48260534/81587219-b9c6c880-9384-11ea-8bdc-1fcffc40ac6d.png)
![Interaction # 2](https://user-images.githubusercontent.com/48260534/81587251-c77c4e00-9384-11ea-9100-58488420aa10.png)

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @dneel-bah ,

Thanks for this request, confirming receipt and will be in touch shortly.

**Comment by dneel-bah** [comment]
@jonwehausen Checking in on this; do you think this will be ready by end of this week?

**Comment by jonwehausen** [comment]
### Datalayer Requirements - WIP

Description of Interaction | Screenshot | dataLayer Example
------------ | ------------- | ------------- 
_Clicking on "Protection against late VA payments"_ | ![image](https://user-images.githubusercontent.com/48527022/82224754-411abb80-98f2-11ea-8569-1b816f195ef8.png) |`dataLayer.push({`<br>`'event': 'gibct-modal-displayed',`<br>`'gibct-modal-displayed': 'protection-against-late-va-payments'`<br>`});`
_Click on "Read our FAQs on the Veteran Benefits and Transition Act_ | ![image](https://user-images.githubusercontent.com/48527022/82224998-948d0980-98f2-11ea-876b-f4ebad29a5b6.png) | `dataLayer.push({`<br>`'event': 'gibct-modal-link-click'`<br>`});`

**Comment by dneel-bah** [comment]
To be implemented in #9190 in the upcoming sprint.

**Comment by sonntag-adam** [comment]
#9190 is in staging with a screenshot of it implemented. @jonwehausen

**Comment by bsmartin-ep** [comment]
## DataLayer QA

@jonwehausen -

Interaction | Data Layer | Result
:--- | :--- | ---
_Clicking on "Protection against late VA payments"_ | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/ffb6e896-0cb0-4726-abdd-af9f342f5324) ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/04257b2b-b5a9-414e-9d82-1f24da4c5e30) | :x: I'm seeing multiple events. <br> `gibct-modal-displayed` should be a variable on the main event
_Click on "Read our FAQs on the Veteran Benefits and Transition Act_ | ![image](https://user-images.githubusercontent.com/62304138/82680589-7ee15200-9c1a-11ea-8b80-8959ef3be037.png) | Link text has changed, but: <br> :heavy_check_mark: PASS

**Comment by sonntag-adam** [comment]
Looks like that was implemented here
https://github.com/department-of-veterans-affairs/vets-website/pull/5289

https://github.com/department-of-veterans-affairs/vets-website/pull/5289/commits/0fc667826586f87868cd39f4453bbdfdb6544cb9

**Comment by dneel-bah** [comment]
@jonwehausen @bsmartin-ep 

We were not aware of a generic event that captured all learn more / modal event openings when we made the request.  Does the generic event distinguish between modals?

**Comment by jonwehausen** [comment]
Hi @dneel-bah ,

@bsmartin-ep and I are introducing the generic `gibct-modal-displayed` event to more easily identify the "learn more" clicks (that say learn more in the link) with those that do not say "learn more" in the link -- like our section 103 example here. 

We have since published out the GTM change to identify and track the section 103 modal click under this new paradigm. 

We would however like to request a removal of the `gibct-learn-more` event on this particular link in order to alleviate duplicate tracking. 

![image](https://user-images.githubusercontent.com/48527022/83024752-c68e2200-9ffc-11ea-8b30-6b679fffa055.png)

**Comment by sonntag-adam** [comment]
gibct-learn-more has been removed.

**Comment by jonwehausen** [comment]
Thank you @sonntag-adam ! Looks great. 

Interaction | Data Layer | Result
:--- | :--- | ---
_Clicking on "Protection against late VA payments"_ | ![image](https://user-images.githubusercontent.com/48527022/83527766-39444500-a4b6-11ea-9bd8-7dcfdaca605c.png) | ✔️ **PASS**


Also verified the other `gibct-learn-more` events are still in tact as usual. 

This is approved to move forward to production, we will close this issue.
