### ISSUE TITLE
MVI endpoint times out

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#896]
If you curl http://ps-dev.commserv.healthevet.va.gov:8110/psim_webservice/IdMWebService, it resolves to 10.227.210.223, but times out trying to connect.

- Should that URL still be valid?
- If that URL is no longer valid, what is the preferred URL to use when developing for MVI integration? 
- The hope is there is one that contains the same dataset that http://ps-dev.commserv.healthevet.va.gov:8110/psim_webservice/IdMWebService returned when we originally did our development as that would making comparing old and new results much easier.

All attempts to reach the members of the support team listed below have been unsuccessful. https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/Master%20Veterans%20Index.md

**Comment by davidsbao** [comment]
@brandonrapp @jholton Just to clarify, where exactly did you get these endpoints from? The URLs look to be more associated with My HealtheVet, and maybe as a service that their site has to get to MVI, but not as a direct connection to MVI..

**Comment by jholton** [comment]
It's before my time, but this was the endpoint used when we originally did our MVI integration development.  We used that endpoint to record our `vcr` cassettes (i.e. we recorded the responses) for testing.

In fact you can see it's still specified as the MVI endpoint in our [settings](https://github.com/department-of-veterans-affairs/vets-api/blob/2f6e5df8c0d774042c4060aed949ad87f517798e/config/settings.yml#L208) file.  (That value is not used in deployed environments)

I don't have an exact date for last known successful usage but @kreek told me he last used it "a while ago, like 1.5 years".

I can hit the DEV and QA MVI endpoints specified in the [doc referenced above](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/Master%20Veterans%20Index.md), but the data I'm getting back is very different than we got previously, which makes updating our tests a lot more painful than if it was the same dataset as before.

**Comment by davidsbao** [comment]
Maybe @annaswims has more recent MVI-related experience here?

**Comment by jholton** [comment]
No, she gave the email of one engineer, who I emailed and didn't hear back from.
@kreek also gave me an email address, who I emailed and didn't hear back from.

**Comment by brandonrapp** [comment]
We were able to get access to the endpoint now so I am closing this blocking ticket!
