### ISSUE TITLE
10-7959c: PDF fields verification

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89609]
As a user, I want to generate a PDF that accurately reflects the data I entered on the form.

Acceptance criteria:

- A checklist of PDF fields and whether or not they have been verified

**Comment by michaelclement** [comment]
This was already taken care of in [this ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/87545), unless there's some extra validation we'd like to get?
