### ISSUE TITLE
Update steps on removing feature toggles to include an important order of removal

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#89615]
### Description
Need to update the steps on removing feature toggles to include an important order of removal. Here is a suggested revision on the steps for the section titled "Removing old/unused feature toggles"

1. Remove all references to your :feature_toggle_name in the app(s).
2. Verify that the app(s) changes have been deployed to production before proceeding.
3. Remove the respective lines from `config/features.yml` in the `vets-api` repository. This cannot be deployed before the app changes or your features will be turned off by default regardless of the flipper settings.
4. Verify the `config/features.yml` changes have been deployed to production before proceeding.
5. (Less obvious) - Delete feature from the respective databases

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles

### Which type of team are you on? (Platform team, VFS team, or Leadership)
MHV Cartography Team

**Comment by taylojill** [comment]
Hi @carlosfelix2 - thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Submitted SME recommendation request via Slack Platform Support channel

**Comment by jknipes** [comment]
Updated content approved by @ericboehs , [discussion in this Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1724693927233049). Page will be checked for launch blockers and deployed on 9/3. Ticket can be closed once successfully deployed.

**Comment by jknipes** [comment]
@carlosfelix2 the Page has been deployed with your updates. Thank you!
