### ISSUE TITLE
[Pension Module] Testing and Launch plan

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#89629]
## Launch plan

**Action:** Get all remaining PRs before staging review merged.
  - https://github.com/department-of-veterans-affairs/vets-api/pull/17781
  - https://github.com/department-of-veterans-affairs/vets-website/pull/31094/files

**Action:** Finish Staging Review
**Action:** Begin Production Review
**Action:** Finish Production Review

## Local Development Review

**Action:** Verify that the models exist

Verified that the model SQL is working pending the remaining PRs needed.
This snippet of code can be used to see how the data is being saved when the form is submitted.
```ruby
raise "Mismatch test" unless Pensions::SavedClaim::count == SavedClaim::Pension::count
# new models
Pensions::SavedClaim::find(1).type # check the type, we are forcing the legacy "SavedClaim::Pension" 
Pensions::SavedClaim.new.type # check the type
# old models
SavedClaim::Pension::find(1).type
```

See that its using the model:

```ruby
3.3.3 :001 > Pensions::SavedClaim::count
2024-07-30 13:28:37.003456 D [7992:12300 log_subscriber.rb:167] ActiveRecord::Base --   Pensions::SavedClaim Count (1.4ms)  SELECT COUNT(*) FROM "saved_claims" WHERE "saved_claims"."type" = $1  [["type", "SavedClaim::Pension"]]
```

Installing the form filler, you can visit the script url and install it. See Slack for url. It is not fully working but it will save time for manual testing. Do a full rebuild of the vets website. Open the pensions application. Test the form both ways with the flipper function on and off.

I started seeing errors upon submissions in the console when testing, however I did verify that both endpoints are being hit when toggled back and forth. The errors are from a recent db migration that I was not able to install for whatever reason due to environmental conflicts when running the command: `PostgreSQL version (11.22) not supported in this version of Strong Migrations (2.0.0)`. The solution was to do a clean install of postgres for the macbook and run the db migrations again after swapping to v15.

Upon testing again with the form filler everything is working as intended. I believe we are ready to merge these PRs and head into staging testing and review.

## Staging Environment Review

**Action:** Test to make sure that the current pension claims works with the flipper module disabled.
Verified that form submission works and based off the API route shows that the flipper flag is diabled or not deployed.

**Action:** Swap the flipper flag, and verify that the new route is being used.
We need access to change the pension module to be enabled. Once this is done inspect the traffic and use the form filler and make sure the new front end flow is working as intended.

**Action:** Test to make sure that the current pension claims works with the flipper module enabled.

There should be a new record created from the new route, it should work with both of these models for now.

**Action:** Prepare any vendors

We will want to inform any vendors using this endpoint of the updates and also begin to deprecate the existing endpoints.

**Action:** Nothing else should be different

With the new database records being created when we swap and verify the new routes we should be able to move on to the production plan.

## Production Launch Review

**Action:** Swap on the pension module via production flipper
**Action:** Determine if we do pension integration test claims here on production and if it is a suitable time.
**Action:** Verify again by console
**Action:** Observability and logging

**Comment by wayne-weibel** [comment]
```
irb(main):002> Pensions::SavedClaim.last
=> #<Pensions::SavedClaim id: 70223, created_at: "2024-08-01 13:26:12.925707000 +0000", updated_at: "2024-08-01 13:26:12.925707000 +0000", form_id: "21P-527EZ", guid: "856e7574-e72f-4bed-97e9-9be11240c1c1", type: "SavedClaim::Pension", form: [FILTERED], encrypted_kms_key: "v2023:AQICAHjFuWwIOjVguJICwBXH2oiU/BP5ZpOCqP4H2nXP...", uploaded_forms: nil, form_start_date: nil, delete_date: nil>
irb(main):003> Pensions::SavedClaim.last.typ
(irb):3:in `<main>': undefined method `typ' for an instance of Pensions::SavedClaim (NoMethodError)
Did you mean?  type
               tap
irb(main):004> Pensions::SavedClaim.last.type
=> "SavedClaim::Pension"
irb(main):005> FormSubmission.find(70223)
(irb):5:in `<main>': Couldn't find FormSubmission with 'id'=70223 (ActiveRecord::RecordNotFound)
irb(main):006> FormSubmission.find_by(saved_claim_id: 70223)
=> #<FormSubmission id: 553, form_type: "21P-527EZ", benefits_intake_uuid: "917c5bfb-3b13-4e78-a96d-0e0da85c3c9b", user_account_id: nil, saved_claim_id: 70223, encrypted_kms_key: "v2023:AQICAHjFuWwIOjVguJICwBXH2oiU/BP5ZpOCqP4H2nXP...", created_at: "2024-08-01 13:26:16.416232000 +0000", updated_at: "2024-08-01 13:26:16.416232000 +0000", form_data: [FILTERED]>
irb(main):007> SavedClaim::Pension.last
=> #<SavedClaim::Pension id: 70223, created_at: "2024-08-01 13:26:12.925707000 +0000", updated_at: "2024-08-01 13:26:12.925707000 +0000", form_id: "21P-527EZ", guid: "856e7574-e72f-4bed-97e9-9be11240c1c1", form: [FILTERED], encrypted_kms_key: "v2023:AQICAHjFuWwIOjVguJICwBXH2oiU/BP5ZpOCqP4H2nXP...", uploaded_forms: nil, form_start_date: nil, delete_date: nil>
irb(main):008>
```

**Comment by wayne-weibel** [comment]
I updated DataDog to monitor for both the old and new sources (app vs module)
<img width="889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d870e8a061ba35f90849b089c1ea5a538cde6fd2/image.png" alt="image.png" />

**Comment by wayne-weibel** [comment]
https://dsva.slack.com/archives/C065JURET8C/p1723744472420729

**Comment by wayne-weibel** [comment]
Double checking I was successful as well
<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5sQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34ac19776d63aafb5f2f3ac67e14350527c7e69d/image.png" alt="image.png" />
