### ISSUE TITLE
OH - Remove My VA Health schedule link from VA direct scheduling location screen

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#89626]
## Description
As part of the Oracle Health direct scheduling effort, we need to remove the `Schedule online at My VA Health` link from the *Choose a VA location* screen in the VA direct scheduling flow. Doing so will allow users to proceed further into the direct scheduling flow instead of being shown the *How to schedule* screen

<img width="709" alt="Pasted image 20240730100855" src="https://github.com/user-attachments/assets/e098b8a9-ff85-40c5-bd2f-acc14c2f4bfc">

---

## Development Checklist
When the `va_online_scheduling_OH_direct_schedule` toggle is on

- AND the Veteran begins the schedule a new appointment flow
- AND chooses the `Nutrition and Food` type of care
- [ ] the location page **should not** display the `Schedule online at the My VA Health` link under Cerner facilities

### Design Assets

- [OH Direct Schedule MVP Figma](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=2980-18211&t=HjWdvItONK1mNucf-1)

### Developer Reference

- [OH Scheduling Requirements (business rules)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/oh-scheduling-requirements.md)

## Definition of Done
- [ ] All development checklist criteria are met
- [ ] Unit tests are updated
---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89626?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
@ryanshaw - I turned on the feature toggle `va_online_scheduling_OH_direct_schedule` for judy.morrison@id.me but the link still appears on the facility page. 


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjlyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d72936d435d08554930f112c58230d13cbdad97e/Screen%20Recording%202024-08-19%20at%203.42.10%E2%80%AFPM.mov)

**Comment by ryanshaw** [comment]
@ldelacosta It looks like the feature toggle is returned in staging as `vaOnlineSchedulingOhDirectSchedule` but when we initially added FE code to handle that feature toggle we used `vaOnlineSchedulingOHDirectSchedule`. Note the capitalized H.

I'll make changes to the FE code so we do not have to update `vets-api`...

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. 

<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzk0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--504694cafa99d08fd2bcce9ec6dd7f11cc6ac2d0/Screenshot%202024-08-21%20at%206.20.19%E2%80%AFPM.png" alt="Screenshot 2024-08-21 at 6.20.19 PM.png" />
