### ISSUE TITLE
Update evaluation interval on VAOS Vets API Error Rate

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#89630]
## Description
Update the evaluation interval to 15 minutes for this monitor:
https://vagov.ddog-gov.com/monitors/215209?q=%2A&sp=&view=spans&live=2d

---

## Development Checklist
- [ ] Update the interval from `last_5m` to `last_15m`

### Design Assets
- N/A

### Developer Reference

The idea of this request is to make the monitor trigger less frequently.   So if we change the interval to 15 minutes, do we also need to also change the comparison value?

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89630?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
This is one of the issues we sized yesterday so I'll move this out of the current sprint for now.

**Comment by cferris32** [comment]
Monitor has been updated with new interval, will keep an eye on how things behave with this change

**Comment by raudabaugh** [comment]
Hi @cferris32 , I'm on watch officer duty this week and saw the `/clinics` monitor [re-alerted at 5am today](https://vagov.ddog-gov.com/monitors/215209?q=%2A&sp=&view=span&view=spans&live=2d) where the error rate was around 40-50 for a couple minutes. If this is a false positive I'd suggest bumping the comparison value up further.

**Comment by JRRoof** [comment]
@raudabaugh - the 5am blips we see are caused by a scheduled backend deployment or reboot.  We have raised this with the MAP team, but they have not found a root cause.  I prefer to know the root cause before we bump up the comparison rate.  As well, a new mobile deployment has caused major issues with HSRM over the last two weeks.  I wouldn't recommend our team make any changes to our alerts until we have a path forward on resolving the HSRM latency and timeouts.

**Comment by ldelacosta** [comment]
No additional work is needed for this ticket. The team will open a new ticket if we need to make any updates. cc: @JRRoof
