### ISSUE TITLE
S59 [An August Sprint 🤩]

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#89634]
# Sprint Goals

| Previous Sprint | Next Sprint |
| :--------------  | ----------:  |
| ◀️  #88351        | #90716 ▶️     |

**Scrum Hero**: @anniebtran   

### Priority 1: Remediate historical failures ([WIP epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80241))

**Send historical failure data for review to determine which claims need to be remediated.**
- (Place holder as we wait for a response)

### Priority 2: Submission Stability and Storage ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293))

**Store Submissions**
- #84329 
- #84332 
- #84348
- #89790 
- #90103

### Priority 3: HLR Form Version Update  [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82220)
**QA HLR form and prepare for collab cycle.**
- #85851
- #88057
- #89863 
- #90144 

### Priority 4: SC Form Version Updates [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82219)
**Mockup SC and prepare for research.**
- #87098
- #87670
- #89502 
- #89715 
- #90568

### Accessibility, and Design Enhancements

- #82249 

### Bug/Engineering Backlog

- #88356
- #88513
- #58833 
- #77808
- #89020
- #89102
- #83078  - content team finished their work
- #71501
- #90112
- #66874
- #90344 90344

---

## Blocked Items

- #83772
   - Blocked until LH [updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83772#issuecomment-2154931490) the submission endpoint to support new questions
- #81507
   - Waiting for Lighthouse to release [new endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81507#issuecomment-2115701294) to capture generated PDFs
- #83324
  - Blocked until after the form redesigns 
---

## Team Capacity

**Outages:**
- 8/9, 8/12 - @anniebtran, @dfong-adh, @Mottie 
- 8/9 - @shaunburdick (half day)

## Reference documentation

- [Q3 Roadmap Prioritization](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/product%20management/Prioritization/DR%20Prioritization%20Scoring%20-%20April%202024.xlsx?d=wb661cf77374d4321969f619e845cabbd&csf=1&web=1&e=GIwNAH)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)

**Comment by eileen-coforma** [comment]
Found a bug in HLR while doing walkthrough. Added it to the list.

**Comment by eileen-coforma** [comment]
We have to run HLR through an expedited version of collab cycle (kick-off and staging review). We'll need to prep for those. Added a ticket.
