### ISSUE TITLE
MVP Screener

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#8963]
## User Story or Problem Statement
As a visitor to a VA facility, I need to complete the required covid screening protocol so I can gain access to the facility.

## Goal
Visitors to VA facilities are able to complete required covid screening protocols as/more effectively, as/more quickly, and as/more safely than interacting with a member of the VA facility staff that is administering the protocol orally.

## Objectives or Key Results this is meant to further
- Number of visitors screened per hour
- Number of false negatives (got a "pass" when entering the facility, got a "fail" when interacting with a clinician later)
- Number of false positives (got a "fail" when entering the facility, got a "pass" after being redirected for further screening)
- Number of employee-hours needed to service entrance checkpoints
- Average or median wait time for visitors at a given VA facility to enter the facility

---
## Tasks
- [ ] Break this card into smaller cards

## Acceptance Criteria
- [ ] Hypothesis has been validated/invalidated that a digital screening tool is as/more effective, as/more quick, and as/more safe than screening all visitors manually and the product has been shipped
---

**Comment by mchelen-gov** [comment]
are all the issues assigned to this epic in the backlog really necessary for MVP AC, or should this epic get resolved?

**Comment by artsymartha68** [comment]
Closing this epic and disassociating the remaining open issues per OK by Patrick. We are declaring that the screener MVP is DONE! 🥂
