### ISSUE TITLE
OH - Add patient relationship endpoint service and mocks

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#89641]
## Description
As part of the Oracle Health direct scheduling effort, we need to add a new service and mocks to the patient service. This new endpoint (`/relationships`) returns an object containing patient/provider relationships and takes both `facilityId` and `typeOfCareId` as optional parameters. 

Here's an example response:

```json 
{
  "data": {
    "patientIcn": "1234567890V123456",
    "relationships": [
      {
        "provider": {
          "cernerId": "Practitioner/1",
          "name": "Doe, John D, MD"
        },
        "location": {
          "vhaFacilityId": "757GA",
          "name": "757GA Zanesville OH VA Clinic"
        },
        "serviceType": "primaryCare"
      },
      {
        "provider": {
          "cernerId": "Practitioner/2",
          "name": "Doe, Jane M, MD"
        },
        "location": {
          "vhaFacilityId": "757GA",
          "name": "757GA Zanesville OH VA Clinic"
        },
        "serviceType": "audiology"
      },
      {
        "clinic": {
          "vistaSite": 534,
          "ien": 6569,
          "name": "GCR PACT 12 MS. MCFANN"
        },
        "location": {
          "vhaFacilityId": "534GD",
          "name": "Goose Creek VA Clinic"
        },
        "serviceType": "primaryCare"
      }
    ]
  },
  "failures": [
    {
      "system": "string",
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "status": "string",
      "code": 0,
      "traceId": "string",
      "message": "string",
      "detail": "string"
    }
  ]
}
```

---

## Development Checklist

*Note: Does not require the use of the `va_online_scheduling_OH_direct_schedule` feature toggle*

- [ ] Add new service is added to `src/applications/vaos/services/patient/index.js`
- [ ] Create local mocks to allow for local development

### Design Assets
- N/A

### Developer Reference

- [VPG Swagger File](https://coderepo.mobilehealth.va.gov/projects/CES/repos/vetsapi-patient-gateway/browse/vetsapi-patient-gateway/src/main/resources/swagger.json)
- [vets-api VAOS Swagger File](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/docs/vaos/v2/vaos_v2.yaml)
- [vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18187)

## Definition of Done

- [ ] A new service is added to `src/applications/vaos/services/patient/index.js`
- [ ] Relevant documentation for the service is updated
- [ ] Local mocks are updated to allow for local development before the `vets-api` portion of this work is completed

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89641?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ryanshaw** [comment]
@Bren22va Moving this to blocked and will link the issue here that is blocking it once created.

**Comment by simiadebowale** [comment]
@ryanshaw - this is ready to be picked up

**Comment by simiadebowale** [comment]
Validated. Closing ticket
