### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by ksantiagoBAH** [department-of-veterans-affairs/va.gov-team#89649]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > (https://github.com/department-of-veterans-affairs/vets-api/pull/17787)

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  137
## Has fix been confirmed in Staging?
- [ ] Yes
- [x] No

## Description
- Please provide the details/reason for the OOB Deploy
   > The date stamp on the pdf generated form 40-10007 was changed from MM/DD/YYY to YYYY-MM-DD in order to process our forms we need to have the date reverted back to the correct format MM/DD/YYY.
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [x] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by bdech** [comment]
Support request: https://dsva.slack.com/archives/CBU0KDSB1/p1722361317919829

**Comment by bdech** [comment]
Deploy complete and verified
