### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by JonathanPostMO** [department-of-veterans-affairs/va.gov-team#89667]
### Name

Jonathan Post

### Email

jonathan@themostudio.com

### Role

UX designer

### Team

VERA CVPS

### Product Manager (PM) name

Rashard Murdock

### Additional Notes

Not sure if you need it, but my VA email is: Jonathan.Post@va.gov. Cheers!

**Comment by naomimarcussen** [comment]
Hi! Thank you for reaching out. I'm not familiar with this team. What do they work on? 

We currently have very limited design seats available and are only supporting designers who work on Veteran-facing services.

**Comment by JonathanPostMO** [comment]
Hey @naomimarcussen, nice to meet you. [VERA](https://va.my.site.com/VAVERA/s/) is the application that veterans are currently using to book appointments at DROCs and ROs. We're redirecting/migrating to a va.gov URL in Q3, and will be making updates to the visual design and user experience in order to comply with OCTO policy and standards. Please let me know if you have any other questions, cheers!

**Comment by JonathanPostMO** [comment]
Hey @naomimarcussen I wanted to follow up on this and see if you had any questions or whatnot? Not having OCTO Figma access, I'm starting with wire frames for this project but would like to be able to use the most up-to-date components sooner than later, so I don't have to rebuild everything at a later date.

**Comment by naomimarcussen** [comment]
Hi! I apologize for the delay. I've just sent an invite to Figma. Let me know when you get it and I can bump you up to editor.
