### ISSUE TITLE
Add new preview EKS cluster to control Plane - automation needs to select the 'EXECUTE" subnets

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#89675]
The current prblack3 EKS cluster is in a subnet with limited IP addresses. The new "preview" EKS cluster has 40,000+ available IP addresses. The control Plane needs to be adjusted to utilize this new cluster.

## Acceptance Criteria

 - [ ] Change default EKS cluster to the "preview" cluster
 - [ ] Ensure terraform for preview deployment selects correct subnets for support services

**Comment by ericboehs** [comment]
We're going a different route and this one is no longer relevant.
