### ISSUE TITLE
10-7959f-1 bug: VA file number not appearing on review page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89687]
Current state: If a VA file number is entered instead of a SSN, the review page does not show the VA file number. 
Expected result: VA file number should be displayed on the review screen if entered.

<img width="1316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlloQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd1a00d5027456d17194a5fba7e629016900d408/image.png" alt="image.png" />

**Comment by reiting** [comment]
<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2doQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd4f2a815ab3e75bf93cea743cb927f7f5e38c19/Screenshot%202024-07-31%20at%2010.27.06%E2%80%AFAM.png" alt="Screenshot 2024-07-31 at 10.27.06 AM.png" />

**Comment by reiting** [comment]
This was just merged. Should be in staging in a few hours.

**Comment by reiting** [comment]
@marywang2 this should be in staging and ready for review.
