### ISSUE TITLE
[Bug] Original Claims: Errors in MVI Proxy-Add After Original Claims Rollout

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8969]
## What happened?
We rolled out Original Claims at 25% and we are seeing several (about half) of MVI adds failing:

“User is invalid or missing edipi” http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116743/events/14f8723dc67d4773a450647e1722c21d/

We need to determine if this is related to the EVSS issue of many EDIPI failures or whether this is truly an invalid user.  Luke will reach out to MVI.

## Specs:
- Device: N/A (back end)
- Browser: N/A (back end)
- Test User: N/A, live users

## Steps to Reproduce
Unknown, but following Original Claims flow.

## Desired behavior
No MVI failures.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by annaswims** [comment]
it seems really likely that va.gov just doesn't have an EDIPI for these users.  EDIPI is the primary key of DS Logon.  We get first try to get the edipi from the identity provider (but will only have it if they've logged in with DS Logon) and then from MVI (which may or may not have it).

**Comment by annaswims** [comment]
I'm thinking that it's all about the missing EDIPI in which case https://github.com/department-of-veterans-affairs/va.gov-team/issues/9263 will address this

**Comment by annaswims** [comment]
It looks to me that the root issue is that we aren't getting the EDIPI because the user isn't identity-verified.  I'm writing a story to prompt users to verify their identity.

**Comment by annaswims** [comment]
This should fix the vast majority of this should be fixed by identity-verification https://github.com/department-of-veterans-affairs/va.gov-team/issues/9448

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9448 entirely fixed the issue 
![Screen Shot 2020-06-05 at 2.46.19 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/030531cb-da74-4dd5-a5c4-053fb6c4180c)
