### ISSUE TITLE
Midpoint Review - IA Feedback - IIR, Veteran New Account Flow within Authenticated Experience, Welcome Pathway V1

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#89698]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for coming through collab cycle!
- I am very excited to see y'all bring the task list through experimental design.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must: Work with CAIA information architects** I saw @kristinoletmuskat on our call - please work with her and/or @jennymayoco to clarify user flows, ensure breadcrumbs, H1s and title tags are in sync, and ensure entry points are updated and there are no dead ends.

- [x] **Must: use same text for current breadcrumb, H1, and title tag** On the contact information update flow, the H1 on each page in the flow, the first part of the title tag before `| Veterans Affairs`, and the text of the current breadcrumb should be the same. For multi-page form flows, the [page title is typically the same on every page](https://design.va.gov/content-style-guide/title-tags#exception-2--forms-and-subtasks) in the flow for consistency. So in this case, the H1, current breadcrumb, and first part of title tag would be something like `Add contact information`. I encourage you to use H2's on each page to convey the step **and** the info you're asking for.
    - h1 “Add contact information”
    - h2 “Step 1 of 3: Email”
    
  ![Screenshot 2024-07-31 at 10 23 57 AM](https://github.com/user-attachments/assets/65006f4f-fdf8-4f0c-872f-42c4d4f71d42)

- [x] **Must: use mobile breadcrumbs** On the mobile view of the contact information form flow, there are a few screens that are missing breadcrumbs. All pages need breadcrumbs.

- [x] **Should: offer consistent links on welcome message for LOA1 and LOA3 users** For consistency and trustworthiness' sake, Veterans should see the same links in the Welcome message before and after verifying their accounts. I do like the idea of more options appearing after verification - like a level up in a game. I think y'all will find a way to do this neatly with a task list.
  ![Screenshot 2024-07-31 at 10 25 52 AM](https://github.com/user-attachments/assets/35c99ca0-cb1b-4657-8304-923bb8f700bd)

- [x] **Should: add "Back to profile" CTA on completion of contact info flow** The Contact update flow final page needs a [primary action link](https://design.va.gov/components/link/action#examples). I recommend “Go back to Profile” - sending folks back where they started.
![Screenshot 2024-07-31 at 10 21 28 AM](https://github.com/user-attachments/assets/0c51e0ea-8866-4f0f-bda6-cfa5c7e2afa4)

- [x] **Should: remove "skip" checkboxes** like other practice areas noted, there are a few ways to implement "skip this question" functionality that'll simplify the flow a bit. I recommend adding hint text to each skippable field indicating that we don't need it, but it's helpful.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by emcruer** [comment]
Hi @erinrwhite! We've made most of the edits, but based on testing and some code discoveries and then the discovery of an existing pattern for editing contact information that serves the same purpose for users, I have some questions! Is the best way to showcase our changed flow to sign-up for office hours? Just want to make sure I'm understanding everything right and applying it to the new design changes!

Thank you!

**Comment by emcruer** [comment]
Awesome! Thank you! I will take that slot and see you on Tuesday!

**Comment by emcruer** [comment]
I think we are good to go to close this one out. We have confirmation that with the new pattern, the breadcrumbs are accurate and once we complete all flows, we will ping either Jenny, Kristin, or Erin to take a look at our H1s, breadcrumbs and title tags together (likely next week - still working with our developers on making sure our patterns can function as expected)!
