### ISSUE TITLE
[FE] 10-10EZ - TERA Improvements: Update Gulf War locations question to display only applicable locations

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89690]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. To improve this experience, we are going to add logic to the Gulf War locations question, based on the time period for each location, so that we are displaying only those locations that were in effect after the Veteran's birth date.

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By displaying the Gulf War locations question based on time period, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for content](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

## Tasks
- [x] Update the Gulf War locations question so that only those locations that were in effect after the Veteran's birth date will display
     - Pending age limit confirmation from HEC
     - This could mean that all or a subset of locations will display
- [x] Inform QA/Team when ready to start testing
     - #89689

## Acceptance Criteria
- The Gulf War location question displays only those applicable locations based on time period compared to the Veteran's birth date.
- The updates are ready for QA testing

**Comment by longmd** [comment]
@allanto-ah , this is ready for QA. I will post the Review Instance link in your QA ticket when its finished publishing.
