### ISSUE TITLE
Flipper UI access for Scott Gorman

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#89707]
### Your Name

Scott Gorman

### Your GitHub handle (Flipper UI access is managed through GitHub)

@scottsdevelopment

### Team, Role, and Company of the target individual

Pensions Benefits, Software Engineer, Coforma

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need this access to enable the pensions module flipper flag on staging for testing.

**Comment by bdech** [comment]
Confirmed in Atlas

**Comment by bdech** [comment]
Hi @scottsdevelopment,

Can you please provide a screenshot for your E-QIP, or some form of favorable adjudication? This is a requirement for access.

**Comment by bdech** [comment]
@scottsdevelopment You've been granted access to lesser environments.
