### ISSUE TITLE
UX analytics: secondary navigation metrics 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#89719]
## Description

HIGH PRIORITY 

We need to have assessment metrics on secondary navigation performance for Robyn by her next OCC shareout if possible. Things that she needs to understand are % engagement with secondary navigation, average clicks on secondary navigation per session, etc. Which pages are getting most clicks in secondary navigation? 

### User story

As a Cartography team member, I want to understand the engagement with the secondary navigation, so that I can see if it is successful for users or not in helping them find and accomplish healthcare management tasks. 

### Notes
- Eval plan question this story answers: "what % of users use secondary nav"
- Robyn would like any updates we may have by 8/2 to share out with OCC the following week

Possible tasks:
- Overall secondary navigation clicks over time (i.e. each week, each month)
  -  With breakdown of clicks per link (Home, Appointments, Meds, SM, MR)
- Secondary nav engagement per session
- Figure out if we need to do path analysis in GA4, or if we can use DD

## Acceptance criteria
- Have consistent / stable data to report to Robyn and OCC about use of secondary navigation across portal in July metrics (and for future data collection)
  - % of users who engage with 2N
  - Sessions count where 2N is used
- Segment by desktop/mobile

**Comment by jonathanjnelson** [comment]
**Number of active users who engage with/click on the secondary navigation**

For July: 

251,340 active users of the health portal clicked on at least one of the 5 links in the secondary navigation. 

That is 30% of active users of the health portal. 

**Out of those 251,340 active users who clicked on the secondary navigation** 

Desktop: 158,098 or 63%
Mobile: 88,275 or 35%
