### ISSUE TITLE
UX analytics: How are users getting to the landing page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#89722]
## Description

HIGH PRIORITY
What are the methods and paths users are taking to get to the My HealtheVet on Va.gov landing page? 

### User story

As a Cartography team member, I want to understand the paths that users are relying on to get to the My HelatheVet on Va.gov landing page. 

### Notes
- Use GA4 to understand paths and validate with DD if possible / if it makes sense? 

Possible tasks:
- [x] Understand the stats on ways users are getting to the landing page
- [ ] Clicks on try-me banners versus those who sign-in from VA.gov to get to MHV?

## Acceptance criteria
- [x] We have a custom dashboard metric for the #s and %s of users who are getting to the landing page via each possible method

**Comment by fmccaf1** [comment]
Finally learned that we have tasks to complete to make it possible for link clicks to be captured as events in GA4. Working to complete an audit of what is working and what is not.

**Comment by fmccaf1** [comment]
Here's what I'm seeing on Adswerve when I click on My HealtheVet in the sitewide header:

<img width="508" alt="image" src="https://github.com/user-attachments/assets/63269dcd-2df8-4e87-a14e-3fe317566f34">

**Comment by fmccaf1** [comment]
Through path exploration in GA4, with endpoint set as /my-health, we have the following info (stats for month of July 2024):


## Path 1: directly from My VA - 148,695 active users
- login > My VA > /My-health - 100,623 active users
- VA.gov > login > My VA > /My-health - 73,812 active users

## Path 2: directly from VA.gov home - 82,058 active users
- login > VA.gov home > /My-health - 44,275 active users

## Path 3: directly from looking at claims - 35,367 active users

## Path 4:  directly from Profile - 16,371 active users

## Path 5: directly from disability rating - 11,446 active users

**Comment by fmccaf1** [comment]
For now, this level of info is sufficient but we want in the future to be able to check these numbers by also monitoring clicks on the links that land users on /my-health landing page.
