### ISSUE TITLE
10-7959f-1: test coverage verification

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89720]
Review unit test coverage to make sure we're at the recommended % coverage, per platform [guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage).

**Comment by reiting** [comment]
@baltes <img width="1901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUJDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a737b36ee70deed7f86ec791e2f4a2595c46f2a/Screenshot%202024-08-07%20at%208.45.18%E2%80%AFAM.png" alt="Screenshot 2024-08-07 at 8.45.18 AM.png" />
