### ISSUE TITLE
0781 paper form mapping

### ISSUE THREAD

**Issue by jinaryu** [department-of-veterans-affairs/va.gov-team#89734]
**Context:** Creating a [spreadsheet](https://dvagov-my.sharepoint.com/:x:/g/personal/jina_ryu_va_gov/EfaJZgNBG4NFkd8SghCWXOwBr410AmLEpuZ7V4L1yy7DOg?e=yWA5jO) to map paper form fields to online form. This will be helpful to have to show stakeholders what happened from paper to online mapping

**Tasks**

- [x] Create spreadsheet
- [x] Update spreadsheet with finalized flow form fields

**Acceptance Criteria**

- [ ] Completed spreadsheet
- [ ] Spreadsheet shared with relevant stakeholders

**Comment by jinaryu** [comment]
Putting this in the backlog. Will pick this ticket back up once we have finalized form fields post-research design changes.

**Comment by lisacapaccioli** [comment]
Draft version is here - [0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=0#gid=0). We'll upload the final to Github.
