### ISSUE TITLE
[Eng] Create code to handle not double booking an appt at the same time

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#89730]
## Description 

Veterans should not be able to schedule a CC appt at the same time and date of one of their other existing appts (from VistA, OH, CC, or VVC). 

## Tasks

- [ ] Create code to handle avoiding double booking
- [ ] Add unit test(s)

> We can't rely on the vaos-service check for appt booked on the same date/time because we will not be making a call to vaos-service for cc direct scheduling. We will have to add this logic to vets-api or vets-website. 

[Wireframe](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3707-7716&t=tSelSm1w39cWk4Kn-4)

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created
