### ISSUE TITLE
Investigate validation errors

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#89745]
# Overview
We have been asked to assist with some validation errors that are happening on the VR&E form:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/investigations/2024-07-22-vre-validation-errors.md

# Tasks
Please read the current ticket and try to determine the cause of the errors that they are seeing.

**Comment by wayne-weibel** [comment]
@scottsdevelopment it seems this is most likely an issue with the json_schema (combination of 1 and 3).  Please test the VR&E form workflow to locate the schema issue - locally and using ArgoCD terminal to attempt triggering the error on real data.  Copy any logs or terminal output and take screenshots to document the issue and findings and present to the other team.

**Comment by mjknight50** [comment]
Thanks for the update.  I agree that the best way to get to the bottom of this is to add logging.  Can you please open a PR that adds logging that would help to catch this?
