### ISSUE TITLE
10-7959a: CHAMPVA Claims confirmation page copy update

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#89769]
As a CHAMPVA Claims user, I need to know the status of my form when I click submit and what to expect next.

- success message only
- error state will be out of the box (appears on the review page)
- leave out any mention of email notification
- remove 'need help?' footer since that info is different from the one we're providing

Acceptance criteria

- When my submit gets a 200 response from s3
  - The messaging on the page lets me know my application submitted successfully
  - I get information about how to contact the CHAMPVA call center if I want to follow up (use the same info from 10-10d)
  - I get information on general timing for processing

More info
When a user clicks submit after completing 10-7959a, the site will generate their PDF and metadata and send one or more files to an s3 bucket where it can be picked up by PEGA processes.

At the time of submit, we won't know anything about PEGA's processing status, so this messaging is meant to let the user know that we got their application and when they should expect to hear something new. This is distinct from what we'll send them in an email confirmation, which will happen after we know that their application has been imported successfully into PEGA.

**Comment by jamiefiore** [comment]
@marywang2 here's the link for the [confirmation page](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1832-36405&t=f5lACfA39Q4xulQp-4). 
@syd-hoeper can you look at this too. I cut some of the content on it but let me know if you think we should add anything back.

**Comment by marywang2** [comment]
@jamiefiore @syd-hoeper we should have CAIA look at this page since it has changed - can we tag them or let them know?

**Comment by jamiefiore** [comment]
Just moved this to a separate page in the Figma so it's easier for CAIAto review. Here's the new [Figma Link](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1880-36481&t=AIZhZqmk3PIMSGyM-0)
