### ISSUE TITLE
Update link on "Creating a new application" page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#89767]
### Description

In step #4 on the [new application page](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application), the link should be updated as follows:

link text: vets-api source app middleware configuration
link destination: https://github.com/department-of-veterans-affairs/vets-api/blob/c80b278e3c8cc3014035d6ec3670dfaa18ff4368/lib/source_app_middleware.rb#L23

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineering

**Comment by taylojill** [comment]
Hi @acrollet - thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by rmtolmach** [comment]
Hey @taylojill I was helping Adrian with the vets-api PR related to this, so I also took care of the doc update.
