### ISSUE TITLE
10-7959a: Confirmation email - create copy

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#89771]
As a CHAMPVA Claims applicant, I need to receive a confirmation email so that I know my claim is being processed and I know what to expect next.

Acceptance criteria

- Applicants get assurance that their claim is moving forward
- Applicants have a general understanding of when they should hear from VA
- Applicants know what to do if they don't hear from VA
- This email will be sent once PEGA has confirmed that an application has been successfully imported, so we can tell the applicant that they're claim is being processed and let them know it will take approximately 60 days to process.

Current email template:
<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Y5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9a341acab2a2df6913d1f3956215a597e6d8d82/image.png" alt="image.png" />

Intake [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/81725) w/instructions on how to access VA notify in comments . 

Link to [OHI Figma file for ](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=2563-125216&t=yT4jbAKsC68EGteZ-4)reference.

**Comment by jamiefiore** [comment]
@marywang2 Here's[ the email ](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1838-36454&t=gMs05zoQ6zDskh2Y-4)

**Comment by marywang2** [comment]
Waiting for CAIA review of this [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/89338) so there are likely changes pending, but closing this one for now.
