### ISSUE TITLE
[SCREENREADER]: CONSIDER removing aria-label from the individual menu links

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#8977]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

In the code, the links have an `aria-label="Locations"` (for example, for the Locations link). The screen reader will read the link, and the aria-label is redundant. Since it introduces more code maintenance, **consider** removing the extra code.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to understand the content available in the secondary navigation.

## Environment

* Operating System: any
* Browser: any
* Screenreading device: any
* Server destination: https://staging.va.gov/pittsburgh-health-care/

## Steps to Recreate

1. Enter https://staging.va.gov/pittsburgh-health-care/ in browser
2. Start screenreading device listed in Environment
3. Navigate to the secondary navigation
4. Verify that the screen reader reads the secondary nav link items once
5. Verify that the aria-label doesn't add additional context

## Possible Fixes (optional)

**Consider** removing the `<span class="">` from around the link text if there's no need for it. If it's serving a purpose for positioning or CSS, let's leave it.

### Current code
```diff
<li class="va-sidenav-level-2">
!  <a aria-label="Locations" class="va-sidenav-item-label" href="/pittsburgh-health-care/locations" rel="noopener noreferrer" style="padding-left: 20px;">
!    <span class=""> 
      Locations 
    </span>
  </a>
</li>
```

### Recommended code
```diff
<li class="va-sidenav-level-2">
+  <a class="va-sidenav-item-label" href="/pittsburgh-health-care/locations" rel="noopener noreferrer">
    Locations 
  </a>
</li>
```

**Comment by 1Copenut** [comment]
@jenstrickland The only thing I'd add here would be to remove the `<span class="">` from around the link text if there's no need for it. If it's serving a purpose for positioning or CSS, let's leave it.

**Comment by mmiddaugh** [comment]
I believe this is resolved. Please validate at your convenience, @jenstrickland

**Comment by jenstrickland** [comment]
validated 🎉
