### ISSUE TITLE
Toxic Exposure: 1.0 - Modify backup submission process to use generatePDF properly

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#89789]
Submissions that go down the backup path will not ever use the Lighthouse generatePDF endpoint.
If the Veteran went through the Toxic Exposure flow and ended up needing to go down the backup path, the 2019 version of the form will be filled out instead of the 2022 version.
We must stop this before it's too late!

lib/sidekiq/form526_backup_submission_process/submit.rb:71 #perform
1. this is being called 
    a. Form526Submission.find(form526_submission_id).benefits_intake_api!
    b. which mutates the submit_endpoint of the submission to benefits intake 
2. then this is being called 
    a. Processor.new(form526_submission_id).process!
3. then #process! calls this
    a. gather_docs!
4. then gather_docs! calls this
    a. get_form526_pdf
5. then get_form526_pdf checks for this
    a. submission.claims_api?
    b. to go down the lighthouse generatePDF endpoint

but because of point #1a, it will never go to lighthouse generatePDF.

Fix this to use lighthouse generatePDF with the correct conditions in place

**possible solution**
1. lib/sidekiq/form526_backup_submission_process/processor.rb:333
look at the formData of the submission for startedFormVersion: '2019' or '2022' instead of the submit_endpoint column
 
Tasks:
- [ ] Fix it
- [ ] Unit test it
- [ ] Manual test?

Acceptance Criteria
- [ ]  lighthouse's generatePDF endpoint is called during the backup process under the correct conditions

**Comment by mchae-nava** [comment]
Taking a look at the unit tests

**Comment by sethdarragile6** [comment]
Verified in staging via Argo!
