### ISSUE TITLE
4142 discovery

### ISSUE THREAD

**Issue by jinaryu** [department-of-veterans-affairs/va.gov-team#89781]
**Context**

- During 7/9/24 VBA check in ([notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-meetings/VBA-syncs.md#70924-biweekly-vba-dbex-check-in)), the question came up of "how is 4142 treated in the back end if there are multiple facilities?" 
- One 4142 is sent per provider

**Questions to answer**
1. Does adding multiple treatment records generate multiple 4142 PDFs? On paper form, there's only one 4142 per provider.

**Comment by AmyPlange** [comment]
@NB28VT For tracking

**Comment by NB28VT** [comment]
@jinaryu yes it appears we only ever send one Form 4142 per Form 526 submission

**Comment by jinaryu** [comment]
@NB28VT thanks! would it be possible for me to see what the Form 4142 PDF looks like if multiple providers are entered?

**Comment by NB28VT** [comment]
> @NB28VT thanks! would it be possible for me to see what the Form 4142 PDF looks like if multiple providers are entered?

Yeah there may be a way to try and generate that locally,  but it would take a bit of engineering time to figure out and generate. @AmyPlange maybe we make this an engineering ticket for this?

**Comment by jinaryu** [comment]
Closing because we transferred this to another [issue](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/6?filterQuery=assignee%3A%40me+sprint%3A%22Sprint+36%22&pane=issue&itemId=75109776)
