### ISSUE TITLE
Investigation - Claim not displaying for user

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#898]
### Status

INVESTIGATING

### Severity Analysis

Unknown until the investigation is complete.

### User Impact 

Any va.gov user that has filed a claim (potentially)

### Description

On Wednesday August 7th, members of multiple teams joined a screen share with a veteran who is expressing some issues with her claims appearing correctly.

One issue that was noted during the call was she believes she filled a claim that is not showing up on her portal.  There is an appeal to that claim, and a resolution, however the initial claim does not appear.

We need to investigate if:
- If there is a claim that isn't be displayed to the user and what the root causes and resolution is
- If this in fact the intended functionality and the claim is represented correctly
   - if there are any feature improvements possible to make it more clear to the end user.

### Further Details

This is issue is being investigated due to the discovery of [this appeals issue](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/659)

**Comment by alexpappasoddball** [comment]
@AZSchneider @YanaRoy I created this issue on the Triage board as a reference ticket.  Feel free to move it to your board or link any tickets you have for this issue.  Let me know if we (Triage) can help in any way!

**Comment by clantosswett** [comment]
@alexpappasoddball @Kimberley2019  Here is the updated spreadsheet. The issues now have dates and I have tried to only keep issues that seem to be related to viewing the claims status. Some issues have more information than others and if contact information is needed, I can provide that. 

[https://app.zenhub.com/files/133843125/33ee9f5f-3c1d-4a1a-b9a3-dabafd255c9b/download](https://app.zenhub.com/files/133843125/33ee9f5f-3c1d-4a1a-b9a3-dabafd255c9b/download)

**Comment by Kimberley2019** [comment]
Spreadsheet with claim issues are below for review.  Spreadsheet will be updated with dates once available.

![image.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/d14bf21a-a9b2-4f91-a35d-6ec3870cfa77)

**Comment by Kimberley2019** [comment]
Spread sheet has been updated with claim issues that have been provided to us.  See below.

![image.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/e2f83899-8ba5-4d59-bbe6-3d7949bb357e)

**Comment by Kimberley2019** [comment]
@YanaRoy @AZSchneider @SMLuthi 

Are there any updates that can be shared concerning this issue?

**Comment by Kimberley2019** [comment]
@AZSchneider @SMLuthi @YanaRoy 

Good Afternoon,

Please add this to the list of other individuals that are having issues.  Please advise if any additional information is required.


Ticket #190923-000471 
Date & Time 9/25/2019 11:46AM

I’m still unable to review my appeals information after 2 months. I have made repeated inquiries and most of them have received no response. Why is I taking so long to correct my issue. Why do my inquiries go unanswered? This is unacceptable and very rude to ignore complaints repeatedly. Two months is entirely too long for an issue to go unresolved! Please provide me with an update of my issue and a timeframe of when there will be a resolution. Again here is my problem:

I am unable to get information in regard to appeals only on my VA.GOV account.

The URL I’m using is VA.GOV

The Error message I’m getting is: Appeal status is unavailable
VA.gov is having trouble loading appeals information at this time. Please check back again in a hour. Please note: You are still able to review claims information

Device I’m using is an iPad, iPhone, and HP laptop

I have tried multiple browsers

I have tried both my DS logon and myhealthvet logon accounts to sign in on

This issue has been going on for over 2 months now. I need this information!

Thanks.

**Comment by YanaRoy** [comment]
@Kimberley2019 after a team discussion, it would be best to set up time with the user to screen share and attempt to identify the issue and resolve ideally. Is this something you can help with getting set up? Thanks!

**Comment by Kimberley2019** [comment]
@YanaRoy Can you please advise which user you are speaking of?

**Comment by YanaRoy** [comment]
@Kimberley2019 The last one that you requested we add to the list (on sept 25).

**Comment by Kimberley2019** [comment]
@YanaRoy 
Thank you. I fill follow up with you soon.

**Comment by Kimberley2019** [comment]
@YanaRoy 

I have reached out to Mr. Barnes and asked if he is willing to have a session with the technical team.  Once he responds I will advise.
@clantosswett are you able to advise on the best way to have this meeting occur?  I want to ensure that we follow proper protocol.

**Comment by Kimberley2019** [comment]
@YanaRoy 
Mr. Barnes reached out and stated that he is available and willing to participate.  He said that he was open for the next few weeks all day.  Can you get together with your team to give me three days and times that this can happen?
Chante is not back yet, so this will give me a chance to confirm with her the easiest way to make this happen.

**Comment by Kimberley2019** [comment]
@YanaRoy 
Good Afternoon,  Please see additional issues below.

Also, any updates on three days and times that you and your team are available so that I can set up a call with the customer and your team?

VA.gov Tech Support	191001-001801	
My appeal from August 2019 is missing from VA.gov, what happened?  I havent heard anything yet. My appeal should be from August of 2019. It had said a decision had been reached and to expect a rating change. Then it disappeared.  
Updated	10/08/2019 06:00 PM	10/07/2019 09:23 AM

VA.gov Tech Support	190923-000471	
I’m still unable to review my appeals information after 2 months. I have made...	
Updated	09/30/2019 11:56 AM	10/08/2019 01:30 PM

VA.gov Tech Support	191002-000793	
Your IVR system is not working correctly and we cannot reach a live agent. The IVR disconnects 80 % of the time after entering all of the patient information on verifying a claim. Please look into this and actually use your system for claim processing. We cannot reply timely if this is not corrected.	Assigned	10/09/2019 01:52 PM	10/08/2019 03:30 PM

VA.gov Tech Support	191005-000073	
Hello and Good morning.  The Question I have is in regards to the VA.GOV site.   I'm trying to understand why all the status tracking has disappeared.  For example, it displayed stuff like Claim 1..  Status Closed or no longer needed. Anyway, the site used to display 6 months of status tracking info but now its all gone.  Just checking, Made me feel like no one was working my claim any longer.. Thx for your time....  VR/	
Assigned	10/11/2019 06:00 PM	10/08/2019 04:03 PM

**Comment by YanaRoy** [comment]
@Kimberley2019 Thursday 10/24 3-4pm EST; Friday 1/25 1-2pm EST; Monday 10/28 3-4pm

**Comment by Kimberley2019** [comment]
@YanaRoy  Thank you for the dates.  I will reach out to him today and hopefully receive an answer ASAP.  I will let you know what day works best for him.

**Comment by Kimberley2019** [comment]
@YanaRoy He emailed back and stated that 10/25 1-2 EST would be best for him.
Once I set up the meeting, I will send to you so that you can pass it along to the appropriate team members.

**Comment by Kimberley2019** [comment]
@YanaRoy I just sent an invitation for our call on Friday from 1PM to 2PM EST.  Please forward the invite to all parties that should be included.  Also, I did advise him that he will be required to screen share.

**Comment by Kimberley2019** [comment]
@YanaRoy There are additional claim issue tickets that need to be reviewed by you or your team, we will provide the details once our upcoming meeting has been had.

**Comment by Kimberley2019** [comment]
After meeting with the team on 10/28/2019, it has been decided that this ticket will be closed, however investigations will continue by the team.

A shared spreadsheet will be created and will be linked to this ticket for tracking purposes for these issues moving forward.  The spreadsheet will contain all relevant information as well as the team updating each issue for the Call Center.

Currently Kimberley is discussing with VA IT if a shared drive/folder can be created to house the spreadsheet containing all issues.  The challenge currently is that when on the VA side, gathering the issues, you cannot use Google Sheets.

**Comment by clantosswett** [comment]
@YanaRoy I have a number of new cases where users no longer see their appeals/claim status. Do you want me to create a new and separate ticket for these issues or should we reopen here when issues like this reappear?
