### ISSUE TITLE
On desktop, set detail page content width to 8 columns

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#89801]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Currently the page content for all details pages fill the full container on desktop. This ticket restricts the content 8 columns on desktop only (smaller sizes stay the same). 

The content includes:

- The appointment card
- The "need help" section

**Expected state** 

[See desktop views in this design file.](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=0-1)

**Current state**

Example showing page content extending full width of container

<img width="471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a4142f59d1c2be7ba6d1624a2dcb6654f0550e4/staging.va.gov_my-health_appointments_7561c1499214e82ea47483208900e26445c46a198be09423682a40a6e9b3603f.png" alt="staging.va.gov_my-health_appointments_7561c1499214e82ea47483208900e26445c46a198be09423682a40a6e9b3603f.png" />

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
- [Figma file]() (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
UX team will validate the changes.

**Comment by outerpress** [comment]
@ldelacosta I wasn't able to test community care appointments but I'm calling this one good to go since the card styling is set broadly across appt types.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
