### ISSUE TITLE
Remove Standard/Daylight indicator from timezones in appointment lists

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#89802]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

[Based on content guidelines](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones), we shouldn't include Daylight/Standard indicators in time zones.

We've removed most of these but Hawaiian time is still showing as HST

Screenshot from Judy Morrison's past appointments:

<img width="1574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ec974a960ff2941653335edc4a6469d9cb25c82/Screenshot%202024-08-01%20at%207.35.56%E2%80%AFAM.png" alt="Screenshot 2024-08-01 at 7.35.56 AM.png" />

This ticket:
- Sets Hawaii Time to display HT, and not include S/D
- Checks that we're not showing S/D in any other timezone

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
- [Figma file]() (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/89802?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by simiadebowale** [comment]
Hey @JunTaoLuo - I was able to confirm the following timezoneIds returned by LH:
- Guam: Pacific/Guam
<img width="1628" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHVWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4631b938578d53da8b40d8cb8bc08cf81e8a6f17/Screenshot%202024-08-28%20at%2011.38.17%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.38.17 AM.png" />
- Hawaii: Pacific/Honolulu
<img width="1770" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8832e8503fd1b2185aed1057ff908433ca045106/Screenshot%202024-08-28%20at%2011.40.02%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.40.02 AM.png" />
- American Samoa: Pacific/Pago_Pago
- <img width="1738" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a49280f7e3ddeeefae8b5b507cb724978c75b2a2/Screenshot%202024-08-28%20at%2011.53.15%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.53.15 AM.png" />
- Puerto Rico: America/Puerto_Rico
- <img width="1572" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1NWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5280b9135bfb0bd16e611fa853af4e1e6973875b/Screenshot%202024-08-28%20at%2011.57.21%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.57.21 AM.png" />
- US Virgin Islands: America/St_Thomas
<img width="1684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1WQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3088c8d60cf430c0832a027ce572ce34eb59f055/Screenshot%202024-08-28%20at%2012.38.44%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 12.38.44 PM.png" />
- Philippines: Asia/Manila
- <img width="1640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1858c1e18d210dc502f9f6b0ed2a81e5b03509e/Screenshot%202024-08-28%20at%2012.43.52%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 12.43.52 PM.png" />

**Comment by ldelacosta** [comment]
@outerpress - this is ready to be validated in staging.

**Comment by outerpress** [comment]
Looks good! Thanks @JunTaoLuo - fyi @ldelacosta 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--981cc011bf46faf1df2ce5caee508fcd92c3dae7/Screenshot%202024-09-03%20at%204.03.00%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 4.03.00 PM.png" />

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
