### ISSUE TITLE
[10-10CG] Bug - Abbreviation component not rendering text

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#89810]
The `Abbr` component has a prop named `key` that is used to pass in the abbreviation key that is used to render the title and text for an abbreviation. `key` is not valid as a prop because it is a restricted keyword for props, since React uses it internally. 

AC:
- [x] Abbreviations should display correct text
- [x] Update tests to ensure that if this component is broken we will catch it in the future.

 
![Screenshot 2024-08-01 at 9 34 24 AM](https://github.com/user-attachments/assets/b414594d-3b51-4263-9d64-713c83297338)

**Comment by allanto-ah** [comment]
Environment: RI

Verified that the bug has been fixed, will verify in staging before closing this ticket

**Comment by allanto-ah** [comment]
Environment: Staging

Verified this bug fix on staging. 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8af11eaee7ccecfadcf0f808665bdafb011109c9/Screenshot%202024-08-02%20at%2012.11.43%E2%80%AFPM.png" alt="Screenshot 2024-08-02 at 12.11.43 PM.png" />
