### ISSUE TITLE
CY Request for DB data

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#89827]
**Details**
A number of the submissions in the last batches sent have no contention data. So they have a full 526 PDF with lots of info and even requests for medical records, 0781a, etc, but no actually disabilities are listed, so they can't take action on the claims. 
VBA is making decisions on what to do with these claims, because it will likely involve some confusing messaging to the Veteran. 

Emily wants to triple-confirm that we actually truly have 0 contention data in our DB for these submissions (not that, for example, there was some error in generating the data or pdfs despite the data being there).

For the submission IDs in the attached CSV, generate a report that includes the following columns:

- va.gov submission ID
- original submission datetime
- File #/SSN
- Does the submission include contentions (just a yes/no or other binary indicator here is fine)

Send the report via encrypted VA email  or Teams to Emily
[SubIDs-check-for-contentions.csv](https://github.com/user-attachments/files/16553532/SubIDs-check-for-contentions.csv)

**Questions** 
- Lisa: Does anyone besides Thomas and Sam have access to the production database? 

[Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1722532727597809)

**Comment by SamStuckey** [comment]
BLOCKED: Emily is getting us submission IDs to make this easier

**Comment by lisacapaccioli** [comment]
@emilytheis Any updates on the submission IDs?

**Comment by emilytheis** [comment]
@lisacapaccioli  @SamStuckey  I updated this ticket itself [on August 8](https://dsva.slack.com/archives/C04KW0B46N5/p1723152179600639?thread_ts=1722532727.597809&cid=C04KW0B46N5) and the submission IDs are in the linked .CSV in the ticket description!

**Comment by SamStuckey** [comment]
COMPLETE: shared with @emilytheis via sharepoint, also available in S3 at s3://dsva-vetsgov-prod-reports/526_missing_contention_check/526_missing_contention_check_08292024.csv
