### ISSUE TITLE
Update error message on review page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89834]
Update the error message that appears on the review page (on all forms) so that it has the below copy:

**We couldn't submit your form**
We're sorry. There was a problem with our system. Try submitting your form again. 

If it still doesn't work, call us at 800-698-2411 (TTY: 711). We're here 24/7.

**Comment by michaelclement** [comment]
Work done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31180). Waiting on:
- [ ] Platform approval
- [X] Team approval

**Comment by michaelclement** [comment]
<img width="1616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDB0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b406e00045323a73e11f1e1f9593c3dd8cbdf7be/Screenshot%202024-08-02%20at%2014.16.08.png" alt="Screenshot 2024-08-02 at 14.16.08.png" />

**Comment by michaelclement** [comment]
@marywang2 @baltes This has been merged in. To review, please check the screenshot above and attached to the [GitHub PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31180). I can also do a demonstration if that's helpful. Thanks!
