### ISSUE TITLE
Document and fix lazy loading 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#8983]
## Overview 
- Lazy loading is a feature in Webpack that allows a user action to trigger dynamically loading javascript _as needed_. 
- Lazy loading on VA.gov does not follow best practices for cached experiences. 
  - JS files are purged during a new deployment 
  - Users may load an application that relies on a purged file. e.g. I load an app and come to it an hour later after a release and the app tries to lazy load a file that's no longer available. 

## Goals 
- Document the current lazy loading behavior on VA.gov- include specific examples. 
- Document how to detect lazy loading issues
  - search "chunk" on sentry
  - look at [this issue](http://sentry.vfs.va.gov/vets-gov/website-production/issues/117251/?query=is%3Aunresolved)
- Document and determine path forward for implementing lazy loading best practices 

## Notes
- We may want to remove some of the lazy loading behavior where it may not make sense (e.g. CTA widgets) and provide a standard component to apps to notify them when their app is out of date (so they can tell the user to refresh the page)
- The platform team may want to review lazy loading approaches to ensure they're not problematic (i.e. flag them for manual review) 
- [Second-guessing the modern web](https://macwright.org/2020/05/10/spa-fatigue.html)

**Comment by U-DON** [comment]
Might want to look into using [`React.lazy`](https://reactjs.org/docs/code-splitting.html#reactlazy).

**Comment by billfienberg** [comment]
While inspecting the webpack build, I noticed several bundles that had unintuitive names (`0.entry.js`, `1.entry.js`, `2.entry.js`, `3.entry.js`)

I did some digging, and found some dynamic imports that aren’t using webpackChunkName magic comments:
- https://github.com/department-of-veterans-affairs/vets-website/blob/1896e4a94df16ac64a91df56da6a518675608636/src/applications/static-pages/vre-chapter36/createChapter36CTA.js#L9
- https://github.com/department-of-veterans-affairs/vets-website/blob/1896e4a94df16ac64a91df56da6a518675608636/src/applications/find-forms/createFindVaForms.js#L20
- https://github.com/department-of-veterans-affairs/vets-website/blob/1896e4a94df16ac64a91df56da6a518675608636/src/applications/post-911-gib-status/createPost911GiBillStatusWidget.jsx#L20
- https://github.com/department-of-veterans-affairs/vets-website/blob/1896e4a94df16ac64a91df56da6a518675608636/src/platform/forms/tests/forms.unit.spec.js#L264

Questions:
- Should we encourage/discourage teams to use dynamic imports?
- Should we require magic comments for readable bundle names when using dynamic imports?
- Is it safe to add those magic comments knowing that will change the bundle name?

**Comment by jbalboni** [comment]
For what it's worth, VAOS is handling chunk errors this way, when lazy loading the form sections of the app: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/routes.jsx#L14

**Comment by timwright12** [comment]
I don't think this is an issue anymore since we dropped file hashes. we still see chunkErrors, but the filenames don't change anymore so it isn't a 404, it's more likely a network issue
