### ISSUE TITLE
10-7959f-1: remove pre-fill 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89837]
Remove pre-fill completely on FMP registration prior to staging review/launch:
- remove blue box with prefill language from each form page, **including intro page** ("We've prefilled some of your information....")
- does the form id appear at the top? (per CAIA, it should populate automatically with the "We'll save your application...." language - we should add this back in if it's missing).
- remove language at the bottom ("Any updates you make...")
- remove any text appearing in the fields for each screen

Expected result: 
- authenticated users do not see any of their info prefilled in the form fields
- form ID should appear on the auto populated save in progress messaging at the top

<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27254ba85eb380aebd6e041db7e84d0be55f8c5f/Screenshot%202024-08-01%20at%205.46.15%E2%80%AFPM.png" alt="Screenshot 2024-08-01 at 5.46.15 PM.png" />

<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f27173c78e99559912865adbf8279c0a04d94f9/Screenshot%202024-08-01%20at%205.56.54%E2%80%AFPM.png" alt="Screenshot 2024-08-01 at 5.56.54 PM.png" />

<img width="1248" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNndvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2bc2f451afa3c6f267564511807b8082da518d0/Screenshot%202024-08-01%20at%205.46.20%E2%80%AFPM.png" alt="Screenshot 2024-08-01 at 5.46.20 PM.png" />

**Comment by reiting** [comment]
This was approved but I had a merge conflict that usually kicks out all reviews so I had to get it re-approved. Team approval happened, now waiting for platform re-approval. If I don't get it by tomorrow morning, I'll put in a ticket about it because I'm not sure what their process is for knowing what to review (and since this was already reviewed and then got un approved...I don't know if they will know that or if they'll have it marked completed).

**Comment by reiting** [comment]
This was approved and merged. It should be in staging later today.

**Comment by marywang2** [comment]
@reiting I'm still seeing prefilled info, including this language on the intro page (are we able to customize this at all)? Additionally, when I enter either SSN or VA file number on the identification info page, I am unable to proceed (when signed in).

<img width="1500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0krQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--596ebcea944d18679ca11fece76d75100bc6488a/Screenshot%202024-08-07%20at%203.09.24%E2%80%AFPM.png" alt="Screenshot 2024-08-07 at 3.09.24 PM.png" />

**Comment by reiting** [comment]
I pushed some changes that should (I hope) fix the prefill issue. Waiting on platform review now.

**Comment by reiting** [comment]
@marywang2 @baltes @brian-wilke this should be in staging and available for review now.

**Comment by marywang2** [comment]
@reiting I'm not seeing any changes on staging....

**Comment by marywang2** [comment]
Adding this here as well for tracking but if we can't remove the prefill message on the intro page we may have to customize the message to be like this [form](https://staging.va.gov/supporting-forms-for-claims/lay-witness-statement-form-21-10210/introduction).

**Comment by reiting** [comment]
This required removing code from the backend. I did that today, and am waiting for platform approval.

**Comment by reiting** [comment]
This has been merged and it works in staging! It's ready for review @marywang2 @baltes @brian-wilke. Screenshots below from staging.

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c249d96937a15104d61afc08b25b2084e9a6c838/Screenshot%202024-08-12%20at%201.20.09%E2%80%AFPM.png" alt="Screenshot 2024-08-12 at 1.20.09 PM.png" />
<img width="633" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61e613660388793352ef6dcacf0d5a73f54606e5/Screenshot%202024-08-12%20at%201.20.19%E2%80%AFPM.png" alt="Screenshot 2024-08-12 at 1.20.19 PM.png" />
