### ISSUE TITLE
Spike: SIP standards

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89835]
Research spike to look into questions around save in progress for FMP registration form.
- where does the 'your form will be saved application on every change' appear? 
   - is it automatic? 
   - does it usually appear on every page or on a certain page?
   - can the copy be changed? (CAIA suggests: "We'll save your form on every change.")
- what is the form ID and should it appear alongside the language above
   - where does this ID pull from and how is it used?
- where/when does the green 'we've saved your form' alert box appear at the bottom of the page?

**Comment by michaelclement** [comment]
- 'Your form will be saved' appears at the top of data and review pages on forms with SIP enabled
  - It is automatic
  - It appears on every standard (non-custom) page
  - The copy cannot be changed (controlled at form-library level)
- The form ID is the ID given to in-progress save data that is created after a logged-in user starts a form. It appears alongside the above language by default
  - The ID is pulled from the SIP data stored in a user's profile
- The green "we've saved your form" alert box appears after a logged-in user makes a change to a form. It appears on every standard (non-custom) page

**Comment by michaelclement** [comment]
@marywang2 I think we've covered all the questions, but let me know if there's anything else we need to document. Thanks!

**Comment by marywang2** [comment]
@brian-wilke

**Comment by marywang2** [comment]
Adding link to this [ticket](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1407#issue-2366672157) since there may be future updates. @michaelclement @reiting

**Comment by michaelclement** [comment]
Thanks for the link! Updated my comment above to correct that the save message only shows on first page.
