### ISSUE TITLE
10-7959f-1: accessibility update to headings

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89832]
Per accessibility review findings, we will need to make a change to the headings.
ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/89740 
url: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/

Heading levels should only increase by 1

**Comment by reiting** [comment]
This has been fixed and pushed to a PR. <img width="421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51d5c28799ebf6a72716d42fac030509a4ed9bd9/Screenshot%202024-08-01%20at%202.47.37%E2%80%AFPM.png" alt="Screenshot 2024-08-01 at 2.47.37 PM.png" />

Waiting on team approval.

**Comment by reiting** [comment]
Now waiting on platform approval.

**Comment by reiting** [comment]
This was merged and should be on staging in a few hours.

**Comment by reiting** [comment]
@marywang2 this should be in staging and ready for review.

**Comment by marywang2** [comment]
ccing @rachaelpenfil for review.

**Comment by rachaelpenfil** [comment]
Looks good to me @marywang2 @reiting
