### ISSUE TITLE
Easily rememberable URL

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#8985]
As a a visitor to a VHA facility, I'd like to be able to easily remember the URL of the covid screener, so I can access the screener as quickly as possible.

**Comment by mchelen-gov** [comment]
www.va.gov/covid19screener correct?

**Comment by batemapf** [comment]
Settled on /covid19screen per https://dsva.slack.com/archives/C013WDER4FP/p1589922041098800?thread_ts=1589486899.218200&cid=C013WDER4FP

**Comment by batemapf** [comment]
implemented [here](https://github.com/department-of-veterans-affairs/vets-website/pull/12673/commits/2d01581b21120f89378203d6d84788265b9630b3)
