### ISSUE TITLE
Show my screener results

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#8986]
As a visitor to a VHA facility, I'd like to be able to easily show my screener results to anyone who asks (e.g. at an entrance checkpoint) including all of my responses and the date in which I completed the screener, so I can quickly pass through checkpoints or be routed to the appropriate triage area.

Design:
https://files.slack.com/files-pri/T03FECE8V-F013NJ70SHL/screenshot_2020-05-15_15.34.31.png

AC:
- [x] easily read from a distance (6ft)

**Comment by mchelen-gov** [comment]
icons: https://design.va.gov/design/icons
palette: https://design.va.gov/design/color-palette

**Comment by batemapf** [comment]
latest design: https://dsva.slack.com/archives/C013WDER4FP/p1589916111086200

**Comment by batemapf** [comment]
@mchelen-gov looks like you moved this to blocked. mind providing some more context on what is blocking?

**Comment by mchelen-gov** [comment]
oops i think i meant to put this to "done" because it had been sitting there awhile
