### ISSUE TITLE
Copy of [Spike] - Consolidate ReasonCode Text Logic Into Appointment Service

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#89864]
Spike for the upcoming work to move Appointments team's reasonCode.text logic into the vets-api appointment_service. This will be a joint development effort by vets-website and vets-api.

We want to determine what fields need to be made available to the FE via vets-api.
Two primary functions we will need to get rid of are: `getAppointmentInfoFromComments` & 'getReasonCodeDS' found in  our `transformers.js` file `(src/applications/vaos/services/appointment/transformers.js)`.

## Tasks
- Answer the following questions:
- What new fields does vets-api need to start exposing to the FE for the team to successfully get rid of the above 2 function?
- What files will need to be updated in vets-website? (Think tests as well)

Timebox TBD

**Comment by JunTaoLuo** [comment]
Is this ticket a placeholder for something else? I think we're mostly done with reason code text consolidation at this point.

**Comment by simiadebowale** [comment]
this ticket is no longer needed
