### ISSUE TITLE
Employee-focused screener

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#8987]
As a VHA employee that regularly visits the same VHA facility to do my job and is required to complete a covid screener every day to access my workplace, I'd need to be able to access the screener, complete questions that take into account my unique situation and risk level, and easily display the result, so I can get to my job on time or take the appropriate action should I report symptoms or exposure.

**Comment by batemapf** [comment]
From 5/27 stand up:
- "Are you an employee?" question is part of the base question set
- Based on response, get 1 of 2 different question sets

**Comment by DanielleThierryUSDSVA** [comment]
Latest version of this question that I have is this:

**Are you a:**

[button] Patient or support person

[button] Employee or contractor

But I think it might actually be better to go with a question geared specifically to employees:

**Are you a VA employee or contractor?**

[button] Yes
[button] No

@batemapf @artsymartha68 thoughts?

**Comment by artsymartha68** [comment]
Yes I love keeping the Yes/No framework if we can - less thinking

**Comment by DanielleThierryUSDSVA** [comment]
# New question 1 in flow

**Are you a VA employee or contractor?**

[button] Yes
[button] No

# Question 6

@mchelen New/revised content below. Thanks!

## Employee version

In the past 14 days, have you had close contact with someone diagnosed with COVID-19 when you weren't wearing a face covering?

## Non-employee version

In the past 14 days, have you had close contact with someone who you know was diagnosed with COVID-19?

**Comment by elliottshane** [comment]
I would change the employee version to: 

In the past 14 days, have you had close contact with someone diagnosed with COVID-19 when you weren't proper PPE?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @elliottshane. We've been intentionally avoiding proper PPE due to some sensitivities around that terminology.

**Comment by elliottshane** [comment]
Thanks, in some cases, this question is needed for employees who are working with active COVID-19 inpatients.  In those cases they would be using a PAPR or an N95 mask, not a face covering.  If you say proper PPE, you cover both situations 1) an employee working in an administrative area wearing a face covering and 2) an employee working in the ICU wearing a PAPR or N95 mask, or a procedure mask if > 6ft. I believe in this case it would be appropriate to use the word PPE.  If you leave it a face covering, it will create questions and potential confusion during screening.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @elliottshane. Totally understand this distinction, and agree that proper PPE is the correct, precise term here. 

To give you some more background on this: We'd had the PPE terminology originally for employees, but had to remove it due to sensitivities around PPE. This specific VISN then requested the face covering language per above. It's a bit of a tricky challenge, and one that I think we'll have to keep working through as we go. @lalexanderson-dsva may also be able to give more insight.
