### ISSUE TITLE
[Design] Finalize appt detail pages 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#89874]
## Tasks

- [x] Finalize appt detail pages based on what data and actions we'll be able to support in LoROTA
- [ ] Draft new content that needs to replace those elements that are removed

Notes on what to remove and add: https://docs.google.com/document/d/1_QB_4hBYQYATyw7Fj2GxNB2sxptf5S_i8p-EG3UexwY/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89874?planning-poker) with Zenhub @zach-park

**Comment by loripusey** [comment]
@zach-park please point

**Comment by zach-park** [comment]
@cgednalske , fyi.

**Comment by zach-park** [comment]
Working figma file link:
https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=2645-15044&t=99yKDeWLvcOeh4An-4

**Comment by loripusey** [comment]
@benbrasso-agile6 @zach-park when we finish these wireframes, please post in our team channel and ping frontend, why will need them to point their work ticket

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske, ready for validation:
https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=543-9595&t=g9M44JXLce1xwwEZ-1

**Comment by benbrasso-agile6** [comment]
Looks good. @loripusey I'm going to close this for now. Whenever Kanchana finishes her work, we can create a new ticket to update these. I don't think FE would want to start these, nor do I think you're going to want it to be a priority. Or, maybe you do. Anyways, check them out: 

[Pre-check-in appt detail pages (for upcoming appts)](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=607-13447&t=DbMmFHqAEf70oinX-4)
[check-in appt detail pages (for upcoming appts)](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4254-10430&t=rEMYmHA74jqUmT3L-4)

@zach-park nicely done

**Comment by benbrasso-agile6** [comment]
@outerpress do you mind look at these? I think you've been moving the headings around on the detail pages. Do we have these correct? Or do we need to wait a bit for your work to catch up? 

[Pre-check-in appt detail pages (for upcoming appts)](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=607-13447&t=DbMmFHqAEf70oinX-4)
[check-in appt detail pages (for upcoming appts)](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4254-10430&t=rEMYmHA74jqUmT3L-4)

Note that most, if not all, actions are removed because of limitations with low auth vs. full auth.

**Comment by outerpress** [comment]
@benbrasso-agile6 looks good! I dropped a couple of comments. Updates to the "other actions" section are still WIP so nothing to add from that here.

**Comment by benbrasso-agile6** [comment]
Updates are all set 👍 

[Pre-check-in appt detail pages (for upcoming appts)](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=607-13447&t=DbMmFHqAEf70oinX-4)
[check-in appt detail pages (for upcoming appts)](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4254-10430&t=rEMYmHA74jqUmT3L-4)
