### ISSUE TITLE
[DRAFT] Alert component with lock icon for account-related alerts

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89879]
### User story

As a Veteran, I want the account related alerts on the landing page to be consistent with other alerts that use the lock icon.

### Notes
- The standard VADS alerts do not allow to use the lock icon with any other color but green. We need to use the lock icon for the new alert designs that are in yellow and blue.
- As part of the sign in widget work, we [implemented a new component](https://github.com/department-of-veterans-affairs/vets-website/pull/31255/files#diff-e2a45174178a9d437b7cd95b99b93bfb10b2ee72a177e475a01326083bab6f57) that duplicates the alert's functionality, but allows any color and any icon.
- One day, the VADS may change to allow for these combinations, so keep in mind we may remove this custom component in the future.

Possible tasks:
- Refactor the [custom alert component from the sign in widget work](https://github.com/department-of-veterans-affairs/vets-website/pull/31255/files#diff-e2a45174178a9d437b7cd95b99b93bfb10b2ee72a177e475a01326083bab6f57) into a shared location and use it for the landing page as well. 

## Acceptance criteria
- MHV Landing Page account related alerts use the lock icon regardless of the color of the alert. (Need FIGMA link here)
- QA review
- A11y review

**Comment by wesrowe** [comment]
VADS might have this work in-flight. @sterkenburgsara will get an update on VADS effort and get back to us.

**Comment by sterkenburgsara** [comment]
VADS is creating custom components for these alerts, but the content keeps changing, so it isn't ready yet. It was almost finalized 2 weeks ago, but Laura & I realized that there are specific buttons that send users automatically down an authentication flow with the two credentials (ID.me and Login.gov) that will eliminate the need to explain roundabout steps that we previously had in the alert content before we knew these buttons existed. 

That revised alert is now back with VADS and they are updating to this version. I'll keep you posted when this work is ready for us? // cc @laurwill

**Comment by fmccaf1** [comment]
We'll pick this up when the component is in prod

**Comment by wesrowe** [comment]
Taken over by more specific stories adopting VADS verify components.
