### ISSUE TITLE
CT: Your estimated benefits box has shifted left

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8988]
The "Your estimated benefits" box on the school profile page should be aligned right with 20px of space between the right edge of the box and the right edge of the "Estimate your benefits" header. Currently, the box is shifted too far left. This issue exists on all non-vettec profile pages.

1. Navigate to the following profile page:
https://staging.va.gov/gi-bill-comparison-tool/profile/11802405
2. Observe the position of the "Your estimated benefits" box (see screenshot below)

## AC:
1. The "Your estimated benefits" box on the school profile page is aligned right with 20px of space between the right edge of the box and the right edge of the "Estimate your benefits" header.

## Current: 
![Screen Shot 2020-05-12 at 10.16.08 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/310ed3f9-3673-4a9f-9554-fa26dd7096fd)

## Expected:
![Screen Shot 2020-05-12 at 10.16.28 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/7988517d-40e6-4e8e-863b-ff008fd8ee95)

[Sketch Document](https://www.sketch.com/s/0ee1f7c7-6692-4ef8-912d-0a929b5e5154)

**Comment by zurbergram** [comment]
will be resolved by https://github.com/department-of-veterans-affairs/va.gov-team/issues/8842

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12634

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-05-13 at 11.10.09 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f4e3bcfd-6985-42ca-9fa9-4d91681bcd79)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah 
This fix is now on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael We're noticing the gray benefits panel on the right is dropping down too early into a single column display at 991px. The calculator fields and the benefits panel need to be responsive for smaller screens, similar to what's happening in production for those areas. If you prefer that we comment this as part of 8842 so it is worked out of that story, we can do that instead of here.

**Comment by ccruzgra** [comment]
<img width="544" alt="Screen Shot 2020-05-18 at 10 45 08 AM" src="https://user-images.githubusercontent.com/41477797/82226580-ac658d00-98f4-11ea-8499-fab0f6706106.png">

**Comment by delli-gatti-michael** [comment]
## Production
<img width="667" alt="Screen Shot 2020-05-18 at 1 17 09 PM" src="https://user-images.githubusercontent.com/45575003/82242215-7c75b400-990b-11ea-944c-2a57f5dbf053.png">

---

<img width="1002" alt="Screen Shot 2020-05-18 at 1 17 27 PM" src="https://user-images.githubusercontent.com/45575003/82242225-80093b00-990b-11ea-9510-e4f74f7926cb.png">

--

## Staging
<img width="653" alt="Screen Shot 2020-05-18 at 1 22 31 PM" src="https://user-images.githubusercontent.com/45575003/82242237-84355880-990b-11ea-8a34-a2468369916b.png">

---

<img width="986" alt="Screen Shot 2020-05-18 at 1 22 48 PM" src="https://user-images.githubusercontent.com/45575003/82242250-8ac3d000-990b-11ea-8753-a7dbb5a008c7.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12712

**Comment by zurbergram** [comment]
The EYB form is not 400px wide, it’s 9.375px padding left + 390.625px width which is 400px
this is so the left side “Use the fields…” lines up with the major accordion heading “Estimate yo…”

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-21 at 2.55.14 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fcd9b2b4-1d3b-4d9a-a2c5-0f1d9212cb22)
##
![Screen Shot 2020-05-21 at 2.55.25 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bbe346aa-b104-4c89-86de-c0dc44223f04)
##
![Screen Shot 2020-05-21 at 2.55.38 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/43f6a384-673f-4077-9e71-baf5667630e8)

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I reviewed and this checks out.

**Comment by sonntag-adam** [comment]
Closing bug
