### ISSUE TITLE
10-7959f-1: Content updates - review page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89887]
Content updates from CAIA review:

Review page:
- we can remove form number from header (success message)
- The first sentence can be updated to read: "We'll review your registration form. This can take up to 60 days."
- add (TTY:711) to the phone number (it should match the styling elsewhere on the site)
(Example screenshots below)

<img width="574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34e78aaf08bd3955c4fb7a4a7d6dc4a5fe24478a/Screenshot%202024-08-02%20at%208.40.38%E2%80%AFAM.png" alt="Screenshot 2024-08-02 at 8.40.38 AM.png" />

<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzByQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6173496f839d1ce8535830f6191cc15ab4f4be2a/Screenshot%202024-08-02%20at%209.57.14%E2%80%AFAM.png" alt="Screenshot 2024-08-02 at 9.57.14 AM.png" />

<img width="562" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDByQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--511e419f571e5a09bd3177f8a179f8c0a9fefdf9/Screenshot%202024-08-02%20at%208.41.26%E2%80%AFAM.png" alt="Screenshot 2024-08-02 at 8.41.26 AM.png" />

**Comment by reiting** [comment]
<img width="758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2077aec653119c157d9dd741c9b6593c3972aa79/Screenshot%202024-08-02%20at%202.47.06%E2%80%AFPM.png" alt="Screenshot 2024-08-02 at 2.47.06 PM.png" />
<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fab52400d6bc720950a917bce218f581494ab947/Screenshot%202024-08-02%20at%202.47.15%E2%80%AFPM.png" alt="Screenshot 2024-08-02 at 2.47.15 PM.png" />

**Comment by reiting** [comment]
@marywang2 this has been merged and should be in staging and ready for review.
