### ISSUE TITLE
Removal of marriage questions (WIP)

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#89908]
As a 10-10d applicant, I need fields removed so that I'm not answering questions that won't be used by the application.

Acceptance criteria
- Given a 10-10d application where the sponsor has died
   - When the applicant selects "Surviving spouse or partner from a legal union (including a civil union or common-law marriage" as their relationship to the sponsor
   - Then the applicant should only be asked for the date of marriage to the sponsor

#### Applicant should not see the following pages:

applicant-marriage/0
<img width="1022" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUVzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f418336ab8fa3e2a630d32137311eaa9691428d/image.png" alt="image.png" />

applicant-information/married-separated-dates/0
<img width="1067" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1de51adf8e93e3e235ef92c6d882ca09ed6addf8/image.png" alt="image.png" />

applicant-remarriage/0
<img width="1067" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69bab816c3c4f4336df0ef12862c7b9fb877d7d7/image.png" alt="image.png" />

applicant-remarriage-separation-date/0
<img width="704" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--238365f8c6dabe8e5032b3794e100bb4ae46a671/image.png" alt="image.png" />

applicant-remarriage-date/0
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69d2c31025a38265a244a6eca161f1927a2f8164/image.png" alt="image.png" />

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31185).

| |After|
|-|-|
|Marriage question|<img width="1040" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME10Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abc5b03712777bf74796cba06c1f73d2f4274a09/Screenshot%202024-08-02%20at%2016.15.39.png" alt="Screenshot 2024-08-02 at 16.15.39.png" />|
|Date|<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e96e10e64d031fc983bf46fad892356968333def/Screenshot%202024-08-02%20at%2016.15.53.png" alt="Screenshot 2024-08-02 at 16.15.53.png" />|
|Upload|<img width="921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFV0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b4290f37c63b297396796f392964e2b5c00fbe1/Screenshot%202024-08-02%20at%2016.16.05.png" alt="Screenshot 2024-08-02 at 16.16.05.png" />|

**Comment by michaelclement** [comment]
Waiting on:
- [ ] Team approval
- [ ] Platform approval
