### ISSUE TITLE
AWS access for JR Reed

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/va.gov-team#89938]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

JR Reed

### Your Email

jr.reed@oddball.io

### Team, Role, and Company of the target individual

Tech Lead / PM

### Product Manager (PM) name and email

Grace Kretschmer mkretschmer@metrostar.com

### Product Owner (PO) name and email

Michelle Dooley michelle.dooley@oddball.io

### Desired AWS Access

Would be nice if I could get read and write access to /cms/consumers/next-build/

### Access Expiration

10/9/2024

### E-QIP Transmittal Confirmation

<img width="880" alt="image" src="https://github.com/user-attachments/assets/aa46cad7-e852-4b79-8979-b0601776d6c4">

### Additional Notes

I need access because I'd like to help my team code :-(

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Hi @mreed101! Could you give me a couple of your team members as a reference so that I can look at giving  you similar permissions?

**Comment by flooose** [comment]
Also, I was unable to find you in our [VFS Roster](https://www.va.gov/atlas), which might mean that you still have to go through [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) before I can proceed with this.

**Comment by mreed101** [comment]
> Also, I was unable to find you in our [VFS Roster](https://www.va.gov/atlas), which might mean that you still have to go through [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) before I can proceed with this.

Hi @flooose I am on the Atlas list. I am a member of the platform team and not VFS https://www.va.gov/atlas/users?filter_by=name&filter_type=includes&filter=jr+reed&commit=Filter

**Comment by barbarello** [comment]
user in Atlas

**Comment by barbarello** [comment]
@mreed101 could you volunteer a name within your team so we can model your aws permissions off of ?

**Comment by mreed101** [comment]
@barbarello Please use Nick Pappas

**Comment by barbarello** [comment]
VA Approval is needed

**Comment by EWashb** [comment]
I approve. If OCTO engineering approval is required, Jeff Keene can do that

**Comment by JonathanKamensDVA** [comment]
> Also, I was unable to find you in our [VFS Roster](https://www.va.gov/atlas), which might mean that you still have to go through [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) before I can proceed with this.

My understanding is that the VFS Roster is obsolete and we should be using Atlas for these checks now.

**Comment by JonathanKamensDVA** [comment]
In any case, I'm OK approving this access, but as per our current protocol I would like to see at least one specific example in the ticket of what the access is needed for.

**Comment by mreed101** [comment]
> In any case, I'm OK approving this access, but as per our current protocol I would like to see at least one specific example in the ticket of what the access is needed for.

Hi @JonathanKamensDVA, I need to be able to test our s3 buckets to make sure that we are properly syncing data to them.

**Comment by JonathanKamensDVA** [comment]
Thanks. Just to be clear, I intended my comment above to signify approval, but in case that wasn't clear, yes, this is approved.
