### ISSUE TITLE
VSP QA feedback on VAMC Left Nav [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#8993]
### Links
**Test Plan / Execution logs:**
https://dsvavsp.testrail.io/index.php?/plans/view/225
**Coverage for References Report**
https://dsvavsp.testrail.io/index.php?/reports/view/74
**Summary (Defects) Report**
https://dsvavsp.testrail.io/index.php?/reports/view/75

### Feedback
**Test Execution Logs**
1. The test plan looks awesome!  Great job organizing everything!

**Coverage for References Report**
1. **Consider**: It looks like the coverage report include test cases that were not executed as part of your test plan for this release. Based on your test plan there appear to be only two test cases that are relevant for this release -- 'Desktop navigation' and 'Mobile navigation' as well as some a11y tests.  Consider running a Coverage for References Report that only includes the relevant section of tests such as -- https://dsvavsp.testrail.io/index.php?/reports/view/76

**Summary (Defects) Report**
1. I see four unresolved defects. I'll leave the a11y bugs alone and just discuss the two functional defects. Great bug reports by the way!
   1. [8905](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8905). This looks like a mismatch between requirements and what was implemented. I'm not overly concerned with this defect, but great catch!
   1. [8906](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8906). This looks like a functional problem with the UI that needs to be resolved before production deployment.

## Definition of Done
- [ ] Acknowledge each item of feedback with a decision
- [ ] VSP QA will close ticket after reviewing feedback decisions

**Comment by mmiddaugh** [comment]
[#8906] has been tagged with the "blocking-release" label and will be addressed before moving to prod
