### ISSUE TITLE
10-7959c OHI form field audit  

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#89940]
Review the Figma files for the OHI Cert and ensure that all fields are on the form are either on the PDF form itself or screener type of questions

**Comment by jamiefiore** [comment]
@marywang2 here's the[ spreadsheet for the form audit](https://docs.google.com/spreadsheets/d/1MWQslpcFQd_JnRK9Cp7j0EissgHi2s44vD1LdZdC1YE/edit?usp=drive_link). I marked the items in red that don't have a field to mapped to on the pd. We should probably remove or discuss these with the Engineers and see if they can re-map them. 
The ones in yellow are screener questions or things that we had to update because of updates to the Medicare/ Medigap programs. 
Let me know if this format works for you.

**Comment by jamiefiore** [comment]
Talked through all of the open items on [the audit ](https://docs.google.com/spreadsheets/d/1MWQslpcFQd_JnRK9Cp7j0EissgHi2s44vD1LdZdC1YE/edit?usp=drive_link)with the Engineers. I marked down the notes and next steps. I think we can close this out now. @marywang2 @baltes

**Comment by marywang2** [comment]
Thanks Jamie, are the notes/next steps in the spreadsheet or somewhere else?

**Comment by jamiefiore** [comment]
@baltes @marywang2 Yes. I took notes on the ones in the yellow fields  that we had questions on [in the spreadsheet](https://docs.google.com/spreadsheets/d/1MWQslpcFQd_JnRK9Cp7j0EissgHi2s44vD1LdZdC1YE/edit?gid=0#gid=0). The only fields that we are concerned with [now](url) are the DOB field which were removed in an engineering ticket already.
