### ISSUE TITLE
10-7959a: Intro page - Changes from internal QA

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89946]
Changes from design internal QA for CHAMPVA claims:
url: https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/file-champva-claim-10-7959a
- Update buttons and link to Sign in to start your form" and "Start your form without signing in" (change to "form" instead of "application")
- Add the Need help footer (to all pages, including the intro page)

**Comment by michaelclement** [comment]
Work is done [in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31386). Waiting on:

- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
| |before|after|
|-|------|-----|
|1|<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXRhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94b91193f1028486813aca980b521dd5221c1c51/before.png" alt="before.png" />|<img width="697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8fdac2bf5f57298ab07a3bf2f58f8417f487a1f/after.png" alt="after.png" />|

**Comment by michaelclement** [comment]
@jamiefiore @baltes This has been merged and should be visible on staging shortly. Thanks!

**Comment by michaelclement** [comment]
[Link to the form](https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/file-champva-claim-10-7959a)

**Comment by marywang2** [comment]
fyi @jamiefiore this looks good to me, closing.

**Comment by michaelclement** [comment]
Fixed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31514). Waiting on: 

- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
| |before|after|
|-|------|-----|
|SIP intro|<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHAzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd80390bbc6fb2e7203fbc60f80d66d2fe819e17/befo.png" alt="befo.png" />|<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHQzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a92cf02989e8f0e9f8843c0d7144d108ac119a0f/after.png" alt="after.png" />|

**Comment by michaelclement** [comment]
@marywang2 @jamiefiore This is visible on staging now. Thanks!
