### ISSUE TITLE
CT-EYB DESKTOP: Top of accordions are opening out of view.

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8994]
related to defect #8823

Steps to reproduce:
On desktop: With Your Benefits accordion open, scroll it past the top of the screen then open a different accordion. The top of the newly opened accordion “appears” off the top of the screen.

The Fix:
Top of accordion should reposition no higher than the top of viewport when opened. (Set focus on the accordion button)

![gif2.gif](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1244e609-0493-4c43-bf85-52dcdda66a06)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12682

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/82597634-48063000-9b77-11ea-9f4a-752b04bcc1f8.gif)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I reviewed and this checks out.

**Comment by sonntag-adam** [comment]
Closing bug
