### ISSUE TITLE
10-7959c: content update to supporting docs screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89951]
Upload Supporting docs screen (Mail in Docs):

- Change "application" to "form" and make it "we" instead of "VA": 
Original: "Your application will not be considered complete until we receive all of your remaining required files."
Update to: "Your form will not be considered complete until we receive all of your remaining required files."

- Remove the extra paragraph break under the Supporting Documents acknowledgement header.

**Comment by michaelclement** [comment]
Work done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31345). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
<img width="528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f4db89eb38324a50031ede5785e96e12c434c03/after1.png" alt="after1.png" />

**Comment by jamiefiore** [comment]
@marywang2 I'm not seeing the changes on Staging yet.

**Comment by michaelclement** [comment]
@jamiefiore The changes were just merged, so should be visible on staging shortly (maybe check back in 30m-1hr). Thanks!

**Comment by michaelclement** [comment]
@baltes @jamiefiore This was merged and should be visible on staging shortly. Thanks!
