### ISSUE TITLE
10-7959a: verify PDF mapping for claims

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#89952]
As a user, I want to generate a PDF that accurately reflects the data I entered on the form.

Acceptance criteria:

- A checklist of PDF fields and whether or not they have been verified
- A PR where any PDF filling issues discovered have been addressed

**Comment by michaelclement** [comment]
Fields have been verified ([spreadsheet here](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2hJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66fd586156c5da4c0488e9ea46ac331b5c5825ec/10-7959a%20pdf%20fields%20verified%20-%20Sheet1.pdf)). The only issue is that the form has an explicit `Signature`-type field in the PDF at the bottom, so we can't fill it with text like normal (it expects a PIV cert or something). Will work with BE to overwrite that area with plain text signature.

[Sample filled 10-7959a PDF here](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd5af8c8a4ef1eba970aefd67bcabf39d37e2490/107959a_filled.pdf)

**Comment by michaelclement** [comment]
Waiting on the following for two PRs (frontend, backend):
- [ ] Team approvals
- [ ] Platform approvals

**Comment by michaelclement** [comment]
Signature field issue has been addressed and will be functional as soon as [this PR is merged](https://github.com/department-of-veterans-affairs/vets-api/pull/17957).
