### ISSUE TITLE
Cache images in gh-actions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89959]
## User Story

As the developers and engineers on the VA Platform, 
We need to minimize the requests for docker images [87540](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87540), 
So that we can avoid rate limiting issues.

## Issue Description

In the previous issue, we introduced images from ECR Public Gallery to avoid issues of rate limiting from dockerhub. ECR unfortunately has its own rate limiting, which causes jobs to sporadically fail. In this issue we introduce image caching, which will be followed by [another story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90369) to switch entirely to private ECR images, once [that work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85699) is done by another team.

## Tasks
- [x] Pull images from repos once

## Success Metrics
Steps in gh-actions pull images once and subsequent steps use these images

## Acceptance Criteria
- [x] That all tasks, above, are complete and the ECR mirroring is proceeding. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Chris was working on caching first to solve the rate-limiting problem. We'll see how far this gets us before moving on to the ECR mirroring.
- PR: https://github.com/department-of-veterans-affairs/vets-api/pull/17877

**Comment by LindseySaari** [comment]
Chris has condensed the work to what we originally had around the retries. No caching for now and scoping the work to the original ask.

**Comment by jennb33** [comment]
Per @flooose this work is complete and the ticket can be closed.
