### ISSUE TITLE
Update form filler for pension form

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#89965]
We have a Greasemonkey script that we use for filling out the form doing manual testing from our browser. It it slightly out of date and a few updates would make this process easier to do.

**Comment by aplatt-coforma** [comment]
Tested and found an issue with it looping back to the age question after then the children question.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelk5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4aa5dd8947aa559943ec6d1925112467a4c3fb34/Screen%20Recording%202024-08-07%20at%2010.08.20%E2%80%AFAM.mov)
