### ISSUE TITLE
Design feedback for Staging Review [VAMC Left Nav]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#8997]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:** 
- Have the yellow focus outline, neatly around the content. 
- The layout breaks between 768px and 847px: 

**Try:**
- No “try” feedback at the moment

**Consider:**
- The black line behavior above certain sections seem inconsistent. 

**Definition of Done:**
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by mmiddaugh** [comment]
[#8974] and [#8975] have both been tagged with the "Blocking-release" label and will be resolved before moving to Prod. 
They are also both currently being addressed.
