### ISSUE TITLE
Create proposal for a modern approach DORA 

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#89971]
Create proposal for a modern approach DORA metrics and calculations.

1. Create a proposal for an approach that is event driven rather than scraping data.
2. Approach should be near real-time rather than batch processed

## Acceptance Criteria
 - [ ] **Scenario: Proposal for modern approach to DORA metrics**
  - When a proposal is created for a modern approach to DORA metrics
  - Then the proposal should include an event-driven, near real-time approach to calculating DORA metrics

**Comment by JoeTice** [comment]
SPRINT 7 UPDATE: IN PROGRESS - Work on this task is ongoing. but not completed by the end of the sprint due to unforeseen circumstances w/ power loss. @ben-allen-oddball, can you please provide a status update and share links to in progress or final outputs.

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3393421328/Future+Proposal
