### ISSUE TITLE
Update DORA Metrics

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#89970]
Update and publish DORA metrics for vets-api, vets-website and content-build.

1. Update metrics for vets-api
2. Update metrics for vets-website
3. Update metrics for content-build
4. Publish metrics to confluence

## Acceptance Criteria
- [x] **Scenario: Updating DORA Metrics for vets-api**
  - Then the updated metrics should be visible on confluence
  
- [x] **Scenario: Updating DORA Metrics for vets-website**
  - Then the updated metrics should be visible on confluence
  
- [x] **Scenario: Updating DORA Metrics for content-build**
  - Then the updated metrics should be visible on confluence

**Comment by JoeTice** [comment]
SPRINT 7 UPDATE: IN PROGRESS - Work on this task is ongoing. but not completed by the end of the sprint due to unforeseen circumstances w/ power loss. @ben-allen-oddball, can you please provide a status update and share links to in progress or final outputs.

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3393421328/Future+Proposal

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3409838085/Latest+Snapshot
