### ISSUE TITLE
[LH Doc Upload] Spike Monitoring and Release plan

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#90005]
## Overview
In migrating our document uploads to Lighthouse, we will need to have a plan for how we will test, monitor and release the migration

### Dashboard Design
- [x] Spike Team 1's Canary launch dashboards and logging
- [x] Come up with a rough strategy for how you will implement your dashboards
- [x] Include monitoring for the Polling Status system 
- [x] Remember to review strategy for testing with VBMS UAT
- [x] Update monitoring and release tickets for each migration

### Questions for Team 1:
- [ ] In creating a new EVSS provider, how are you testing that if the Flipper hides the Lighthouse behavior only? Are you just releasing it with the new EVSS service running for 100 percent of users?

**Comment by NB28VT** [comment]
Note we will need to present our rollout plan to the enablement team before we do the canary launch, add this to the ticket

**Comment by ajones446** [comment]
Draft of testing plan: https://docs.google.com/document/d/1JwM_hdNAfqKOTJgHDkBTWS812MqKL6GroPxg-0XHcgM/edit

**Comment by ajones446** [comment]
@lisacapaccioli This is what Kyle, Nathan, and I discussed during our sync on 9/25. 

- Because this feature is not Veteran-facing, we should not need to use the full production release template.

- For the BDD release, we want to start by setting the feature flipper to send 1% of BDD uploads to Lighthouse. After successfully passing the testing plan, we will then increase usage to 5%, 50%, then 100%.

- 0781 and the Veteran-uploaded documents will follow a similar pattern, based on how the initial BDD test goes.

- After this plan is approved, we need to update the next ticket [#90361](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90361) BDD Instruction Migration Production Release and Monitoring

**Comment by lisacapaccioli** [comment]
@ajones446 Thanks for the update. Here's the Release Plan: [DBEX Lighthouse Migration for 526 Ancillary Forms.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Lighthouse%20Migration%20for%20526%20Ancillary%20Forms.md)
We'll all work on this together. For now it's just a placeholder.

**Comment by lisacapaccioli** [comment]
@ajones446 I have added as much information as I can at this time for the release plan, there are spots where Engineering will have to fill in the gaps. If we don't know the information, we need to start thinking about them. We don't want the release plan to be the thing that prevents us from going to production. 

- Success criteria - how will you define that the work was successful? 
- New capabilities and changes - what was delivered - could be the names of api's, the DD monitors, etc. This is just to highlight the work you all did. 
- Release plan - we'll add dates when we know
- Risks - are there any and how would you handle them? For instance, is it possible to have more (silent) failures? Would emails be triggered if the uploads didn't work? etc. 
- Recovery plan - I started something, but you can write this for however it makes sense. Just need to know what would we do if we find it's failing? Does LH have to be involved? 

If there is anything else we have to think about we can add it. I just went by some standard things we generally track. 

Thanks

**Comment by ajones446** [comment]
Oct 4 Update:
- Latest version of BDD staging testing plan: [BDD Instruction Testing](https://docs.google.com/document/d/1JwM_hdNAfqKOTJgHDkBTWS812MqKL6GroPxg-0XHcgM/edit) 

- Latest version of release plan, dates still TBD: [DBEX Lighthouse Migration for 526 Ancillary Forms.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Lighthouse%20Migration%20for%20526%20Ancillary%20Forms.md)

- Blocker: Waiting on requirements from OCTO for polling failure emails for 0781 and Veteran-uploaded evidence. (This does not apply to BDD, we can keep moving ahead with BDD uploads.)

**Comment by NB28VT** [comment]
BDD staging testing plan looks great!

**Comment by NB28VT** [comment]
I think we can close this one, just cleaned up all outstanding BDD tickets
