### ISSUE TITLE
[Documentation] Developer Guide

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#90010]
There's some nuances to working on this platform and with this codebase that we should document.

Here are some ideas to cover:
* Commands to run locally that get run on CI/CD like linting
* Config files to get the app running locally
* Commands that run both FE and BE for our project
* any other ideas that come up while working through the list above

**Comment by maxx1128** [comment]
I've merged three pull requests for different documentation here, and @digitaldrk and I have agreed to mark this as closed for now. But we will keep our eyes open for any additional info to add or ways to refine this ticket.

**Comment by maxx1128** [comment]
Here are the links to the new documentation:

1. [Local setup for the front-end](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/local-setup.md)
2. [Local setup for the back-end](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/back-end/local-setup.md)
3. [Local setup for SOCKS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/general/socks.md)
