### ISSUE TITLE
Flipper UI access for Derek Dyer

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#90014]
### Your Name

Derek Dyer

### Your GitHub handle (Flipper UI access is managed through GitHub)

@digitaldrk

### Team, Role, and Company of the target individual

Debts team, Backend dev, GCIO

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [ ] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Hi there, thank you for your assistance.

I have had to ask teammates to toggle Flipper for code I've written on my behalf. It would be nice to gain access to prod to toggle myself.

I believe I'm in atlas, here's a query I've used to find myself:
https://dev.va.gov/atlas/users?filter_by=name&filter_type=includes&filter=derek&commit=Filter

**Comment by AnthonyWFlowers** [comment]
Greetings @digitaldrk You've been granted access to Production- Flipper UI. Please reach out with any additional questions or concerns.
