### ISSUE TITLE
10-7959a: react widget/feature toggle 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#90029]
Create feature toggle - [Feature toggle guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) and provide name for release plan
Create a React widget in vets-website for the dynamic content, per documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) and provide ID (to share with CAIA)

**Comment by michaelclement** [comment]
Work is done in these two PRs ([one](https://github.com/department-of-veterans-affairs/vets-website/pull/31466), [two](https://github.com/department-of-veterans-affairs/vets-api/pull/18089)) - waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
<img width="847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38deab05df8099b033a62b1bb100fe761cb14138/107959a_feature_toggle.png" alt="107959a_feature_toggle.png" />

**Comment by michaelclement** [comment]
Waiting on re-approval for the `vets-website` PR - had to fix a conflict

**Comment by michaelclement** [comment]
Widget ID for CAIA: `form107959a`

**Comment by michaelclement** [comment]
PRs have been merged. @baltes @marywang2 this should be visible on staging shortly. Thanks!
