### ISSUE TITLE
508-defect-3 [AXE-CORE] Elements must have their visible text as part of their accessible name

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#9003]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Reported axe error

![Screen Shot 2020-05-12 at 9 22 31 AM](https://user-images.githubusercontent.com/136959/81705360-94919300-9434-11ea-9910-e01586b6ea5a.png)

This involves the `FileField` (`src/platform/forms-system/src/js/fields/FileField.jsx`) upload button. The text in the `aria-label` & content don't match. The problem is that the button text is populated as follows:

| Files uploaded | Button text | aria-label |
|---|---|---|
| 0 | `ui:options.buttonText` | `uiSchema['ui:title'] \|\| schema.title` |
| 1+ | `ui:options.addAnotherLabel` | `uiSchema['ui:title'] \|\| schema.title` |

<details><summary>There is no axe issue when no file has been uploaded</summary>

![Screen Shot 2020-05-12 at 10 10 49 AM](https://user-images.githubusercontent.com/136959/81711158-f3f1a200-9438-11ea-9891-6bd5444eafee.png)
</details>

Once one file has been uploaded, the button text changes to "Add Another Document" (in this example). This screenshot is from `/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records` after adding one document.

![Screen Shot 2020-05-12 at 9 18 23 AM](https://user-images.githubusercontent.com/136959/81705068-3664b000-9434-11ea-9ab0-1f61b497e1b9.png)

## Acceptance Criteria

The button text has been included within or exactly matches the `aria-label`

## Environment

* Operating System: all
* Browser: all
* Screenreading device, if applicable: N/A, using axe-coconut
* Server destination: any; instructions are for staging

## Steps to Recreate

1. Log in to user 228
1. Go to https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
1. Get to step 3/5 Supporting evidence and check to include private medical records
1. On page /disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records do an axe check (no issue with the upload button will appear)
1. Upload a file
1. Do another axe check, and now you'll see an issue pop up for the upload button

## Possible Fixes (optional)

This can be fixed by prepending the button text content to the `aria-label`, but it won't always make grammatical sense, e.g. "Add another document upload your private medical records".

If this was done within the component, I'm afraid the axe test would pass but then the developer wouldn't be notified of the potential grammatical problem.

Alternatively, the `aria-label` could exactly match the button text.

## WCAG or Vendor Guidance (optional)

https://dequeuniversity.com/rules/axe/3.5/label-content-name-mismatch

## Screenshots or Trace Logs

See description

**Comment by taylorkaren** [comment]
Issue moved to [department-of-veterans-affairs/va-forms-system-core #252](https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/252) via [**ZenHub**](https://www.zenhub.com/)
