### ISSUE TITLE
10-7959a CHAMPVA Claims form field audit  

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#90048]
Review the [Figma files f](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=13-80&t=WY3zWIeCnDSUan5k-0)or the CHAMPVA Claims and ensure that all fields are on the form are either on the [PDF form](www.va.gov/vaforms/medical/pdf/vha-10-7959a-fill.pdf) itself or screener type of questions. 

- [ ] Complete the [audit spreadsheet](https://docs.google.com/spreadsheets/d/1UDNzEbT40Bkc4KFAGeqbnFyo5nwPGdYzkJ88UlizZ7o/edit?gid=0#gid=0) for CHAMPVA Claims
- [ ] Have a PM review to create any tickets needed for engineering.

**Comment by jamiefiore** [comment]
@syd-hoeper I assigned you on this because you were looking for some work. You can kick it back to me if your capacity fills up. It not due until Sprint 24.

**Comment by syd-hoeper** [comment]
Finished this up; nothing beyond things we already know and are already working on.

Link to spreadsheet: https://docs.google.com/spreadsheets/d/1UDNzEbT40Bkc4KFAGeqbnFyo5nwPGdYzkJ88UlizZ7o/edit?gid=0#gid=0

**Comment by syd-hoeper** [comment]
Ticket can be closed @baltes @marywang2
