### ISSUE TITLE
Contact Center Review for Appointments Front-end and Check-in Experience - Travel Reimbursement Submission for Oracle Health Facilities on VA.gov

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90045]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

**Travel Reimbursement Submission for Oracle Health Facilities on VA.gov**

This product allows Veterans to file a mileage-only travel reimbursement claim only on the day of their appointment (local time based on the facility) through VA.gov from their smartphone by texting “travel” to 54804. 

Currently, this is only available to Veterans that have a VA in-person appointment at a VA health facility that uses Oracle Health (formerly Cerner) Electronic Health Record (EHR).

### Launch Date
*Please provide the launch or rollout date and details.*

TBD. September 1, 2024 is a best guess. It's being discussed by IVC and VTP departments. 

### Version Number
*Please provide the version number of the guide and/or video.*

Product debut. 0.1.0

### Product Guide
*Please provide product guide link*

[Online Travel Reimbursement Submission for Oracle Health Facilities Product Guide.docx](https://github.com/user-attachments/files/16503211/Online.Travel.Reimbursement.Submission.for.Oracle.Health.Facilities.Product.Guide.docx)

### Product Video
*Please provide product video link*

n/a

### Product Video Transcript
*Please provide product video transcript link*

n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The draft looks good. Sending to VEO for their review.

**Comment by benbrasso-agile6** [comment]
@starlow00 FYI, I heard our release might not be as soon as Sept 1, FYI. This info is coming from Integrated Veteran Care (IVC). Just wanted to pass along in case it's helpful.

**Comment by starlow00** [comment]
No worries, thanks for the info!

From: Ben Brasso ***@***.***>
Sent: Wednesday, August 7, 2024 7:25 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: TARLOW, STEVEN R. (ODDBALL INC) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for Appointments Front-end and Check-in Experience - Travel Reimbursement Submission for Oracle Health Facilities on VA.gov (Issue #90045)


@starlow00<https://github.com/starlow00> FYI, I heard our release might not be as soon as Sept 1, FYI. This info is coming from Integrated Veteran Care (IVC). Just wanted to pass along in case it's helpful.

-

**Comment by starlow00** [comment]
There are no changes from VEO. The current copy is attached; please use it for future revisions/updates. Thank you!

[Online.Travel.Reimbursement.Submission.for.Oracle.Health.Facilities.Product.Guide_SRT_08072024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3REQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7876d72e205883df93ca85bd0f9945d40052baed/Online.Travel.Reimbursement.Submission.for.Oracle.Health.Facilities.Product.Guide_SRT_08072024.docx)

**Comment by benbrasso-agile6** [comment]
TY
