### ISSUE TITLE
Contact Center Review for IVC Forms team - FMP registration

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#90047]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Veterans who are outside the United States can register for the Foreign Medical Program using this FMP registration form (10-7959f-1) in order to cover costs for service-connected conditions.

### Launch Date
 BD (~ end of August/mid-September?), [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/fmp-registration-release-plan.md)

### Version Number
1

### Product Guide
product guide [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/Foreign%20Medical%20Program%20Registration%20Product%20Guide.docx)
staging [url](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The draft looks good. Sending to VEO for their review.

**Comment by starlow00** [comment]
There are no changes from VEO. The current copy is attached; please use it for future revisions/updates. Thank you!

[Foreign Medical Program Registration Product Guide SRT 08072024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ae0064052aab5485aa882e42c7a8da86c7f4ac1/Foreign%20Medical%20Program%20Registration%20Product%20Guide%20SRT%2008072024.docx)
