### ISSUE TITLE
10-7959c: remove beneficiary dob 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#90041]
Per [audit](https://docs.google.com/spreadsheets/d/1MWQslpcFQd_JnRK9Cp7j0EissgHi2s44vD1LdZdC1YE/edit?gid=0#gid=0) here, the beneficiary DOB has no corresponding field in the OHI PDF so it should be removed.

- current state: beneficiary name and DOB appears on the beneficiary info screen
- expected result: only the beneficiary name should appear
 - header should also be updated to "Beneficiary's name"
 
Figma [link](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=2306-43751&t=cs26ibfbr7OTIvbU-4)

**Comment by marywang2** [comment]
@jamiefiore once the figma is updated, please add the link here. Thank you!

**Comment by michaelclement** [comment]
Went ahead and removed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31333), has not been merged yet.

**Comment by michaelclement** [comment]
@baltes This has been merged in and should be visible on staging shortly. I've also attached screenshots that can be reviewed to the [PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/31333)

**Comment by jamiefiore** [comment]
@marywang2 I reviewed this on Staging. It's good to go.
