### ISSUE TITLE
Update slack notifications for failed vets-website master deployment 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9005]
## Overview
- Operations needs notifications about build and deployment failures 

## Problems 

- Notifications are not documented. 
- Two channels (#vfs-engineers and #devops-deploys) are for alerting about deployments 
  - they give conflicting information: #vfs-engineers [shows](https://dsva.slack.com/archives/C0MQ281DJ/p1588875279132900) website failed deployment while later the same day #devops-deploys [states](https://dsva.slack.com/archives/C37M86Y8G/p1588884525272600) that deployment was successful

## Goals
- Document notifications 
- Update messages so that it's clear what is actually deploying 
  - commit + commit date 
  - if it's a website build or just a content deploy 
- Maybe consolidate alerts into a single channel

**Comment by rianfowler** [comment]
Add wyatt, JP, Andrew, and Rian as reviewers to any work related to this

**Comment by meganhkelley** [comment]
Relevant Slack convo: https://dsva.slack.com/archives/C0MQ281DJ/p1618508215212200

This ticket still needs to be addressed, first step is to determine ideal setup/approach for Slack notifs

**Comment by meganhkelley** [comment]
On hold until GHA migration is complete

**Comment by oseasmoran73** [comment]
[Ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/30111) related to GHA

**Comment by laineymajor** [comment]
duplicate
