### ISSUE TITLE
Review staging ahead of testing | 59a

### ISSUE THREAD

**Issue by syd-hoeper** [department-of-veterans-affairs/va.gov-team#90056]
Go over what's in staging and make sure it's ready for user testing

**Comment by jamiefiore** [comment]
@syd-hoeper [here is the list](https://docs.google.com/spreadsheets/d/14ZcH9OYsm5Hi1vwWweg7vcWNdAgOazv_ygNiSc2tzZc/edit?gid=0#gid=0) of issues I found when I did my review

**Comment by syd-hoeper** [comment]
I finished going through and everything looks good to me. There's a couple of things on the [spreadsheet](https://docs.google.com/spreadsheets/d/14ZcH9OYsm5Hi1vwWweg7vcWNdAgOazv_ygNiSc2tzZc/edit?usp=sharing) that should be addressed, but no show stoppers. 

Ticket can be closed @marywang2 @baltes

**Comment by syd-hoeper** [comment]
Only thing to note is that I haven't been able to successfully submit the application, I just keep getting an error, so I have not seen the confirmation page

**Comment by marywang2** [comment]
@balexandr @cloudmagic80 I thought the BE work was done (in this [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/84650)) for claims. Is there more work needed?

**Comment by marywang2** [comment]
@balexandr @cloudmagic80 I thought the BE work was done (in this [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/84650)) for claims. Is there more work needed?

**Comment by balexandr** [comment]
I am working to resolve this

**Comment by cloudmagic80** [comment]
7959a isn't completed yet. I'll have to check with Mike

**Comment by marywang2** [comment]
Just following up on this @cloudmagic80 were we still waiting for something to complete submission successfully?
