### ISSUE TITLE
Document how to handle a failed deployment of the website 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9006]
## Overview 

It's VSP's responsibility to triage and fix failed master deployments to dev, staging, and production. There's no process for handling failed website deployments.

## Goals 
- Document failed deployment responsibilities for oncall and support developers (resolution, communication)
- Document process for resolving failed deployments 

## Notes
- Process should include links to views of useful information 
  - current commit in production: https://www.va.gov/BUILD.txt
  - master commit history [view](https://github.com/department-of-veterans-affairs/vets-website/commits/master) 
- Document what these status symbols mean- you may have to look at the jenkins job / github webhook documentation to figure out how these statuses are updated and what they mean specifically for vets-website 
![Screen Shot 2020-05-12 at 13 33 19](https://user-images.githubusercontent.com/4998130/81726349-3c1ebd80-9455-11ea-8a28-283bf6868c81.png)
- Document failed deployment notifications
  - what do they mean? 
  - Related #9005 
- How to revert changes that cause failed master deployments 
- Escalation process

**Comment by meganhkelley** [comment]
Complete: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/frontend/troubleshooting-build-failures.md
