### ISSUE TITLE
Update content on success page to remove content about texting again

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90062]
## Tasks

- [x] Update content on success page to remove content about texting again. E.g., Veteran can only file one claim per day per facility. 

## AC

- [ ] Provide wireframes for FE to make the change

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park rdy for validation - https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3748-5781&t=VjPc4WL7j8XnQPIE-4

**Comment by cgednalske** [comment]
I don't remember what it was before, but everything looks good 👍

**Comment by benbrasso-agile6** [comment]
Sorry, will try to keep a before/after for validation next time.

**Comment by benbrasso-agile6** [comment]
@loripusey content change on success and failure pages ready for FE - https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3748-5781&t=VjPc4WL7j8XnQPIE-4
