### ISSUE TITLE
Remove conflicting claim exam prep instructions from top of details

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#90070]
## Summary
The Claim exam details pages now have two separate, conflicting instructions for preparing for the visit. Remove the old section at the top of the page where it appears for upcoming, canceled, and past claim exams (where applicable)

## Specs
- Device: Macbook Pro
- Browser: Chrome 

## Steps to Reproduce
**Test User:** claudia.c.lapomarda@id.me

1. Login as Claudia
1. Go to her claim exam appointment details pages: _URL_
2. Note the "How to prepare for your appointment" section and content at the top of the page

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

The "how to prepare for this exam" section with conflicting info appeared. This should be removed:

<img width="1834" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWMzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40193c144cfa46c2fc535e3575b6427b6d612f23/Screenshot%202024-08-06%20at%208.35.57%E2%80%AFAM.png" alt="Screenshot 2024-08-06 at 8.35.57 AM.png" />

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

The section and it's content should be removed.

## Definition of Done
- [x] Desired result is achieved and/or document decisions made
- [x] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization
- [ ]

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/90070?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
this can be sized async and then added to Sprint 13 or 14 as appropriate

**Comment by outerpress** [comment]
Fix looks great @JunTaoLuo thank you! FYI @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
