### ISSUE TITLE
[FE] - Follow up for stale session redirect

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#90081]
- Take a look at adjusting the time to 15 minutes
- Don't set the timeout if it is already set
- postCheckInData shouldn't be getting called on refresh

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/90081?planning-poker) with Zenhub @brianseek

**Comment by brianseek** [comment]
Closing since no further validation needed.
two tech debt tickets created from review by @wullaski: 91745 & 91743
