### ISSUE TITLE
10-10d Spike: Options for including country on PDF

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#90085]
As a PEGA user I need to see an addresses country when reviewing a 10-10d pdf.

Acceptance criteria
- We have multiple options for including country on the PDF so that we can discuss with stakeholders and make a decision

**Comment by cloudmagic80** [comment]
[Uploading... sample_1010d_country_code_usa.pdf]

**Comment by cloudmagic80** [comment]
[sample_1010d_country_code_usa.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ae49440b66f9acc77d36fc3204bcf6ae0f75f2b/sample_1010d_country_code_usa.pdf)

**Comment by cloudmagic80** [comment]
[VA Form 10-10d - sample_1010d_country_code_mex.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93a0d06813eb449c9952d07dbae8b3f4107ac960/VA%20Form%2010-10d%20-%20sample_1010d_country_code_mex.pdf)

**Comment by baltes** [comment]
@cloudmagic80 I see one option, are there others?
