### ISSUE TITLE
Toxic Exposure 1.0: Build feature toggle for production testing

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#90091]
Create a Flipper feature toggle for production testers that does the following:
- don't send to mail automation (RRD)
- don't actually call the ITF check. simply return a favorable response from the endpoint
- don't send 4142 in the ancillary forms (don't have to disable on the frontend)
-- still upload fake evidence to make sure those are going through
- disable backup path

### Tasks
- Create moderated production feature flag that' adding to features.yaml
- Add FF check to each of those points above (discovery needed on these)
- Add this feature flag to the release plan
- Document this in GH
- Test this solution to ensure the AC is met

### Acceptance Criteria
- When sending a 526 submission, mail automation isn't triggered
- When sending a 526 submission, the ITF check isn't called
- When sending a 526 submission, the 4142 flow is blocked
- When sending a 526 submission, the backup path cannot be triggered
- A 526 submission ends up in VBMS
- 526 PDF is in the eFolder
- The raw form data still includes the full, complete, and correct attributes of the submission

**Comment by pacerwow** [comment]
**Notes and Considerations 9/6 after VBA Sync meeting**
1 Emily - Is there a way to block the production "moderated testing" cases from being sent to Mail Automation?

- When performing Moderated Production Testing (MPT), we don’t want the submission to ping the service that triggers Mail Automation. This is part of Rapid Ready for Decision (RRD). T-REX can create a toggle to prevent this from happening.
- We also want to prevent an ITF from being created
- We don’t want testers to fill out a 4142, so exclude this from the test cases
- We should have a test case that includes uploading fake evidence documents. We’ll provide an image file for testers to use
- We want to prevent the backup path being triggered, as this would trigger a human creating a claim and we won’t have the ability to delete it as soon as it comes through. Ideally we should block this from happening.

3 Jared - How might we delete the submitted claims in VBMS? Who can do this? Similar to Emily's question. How will we communicate with potential testers?

- Kevin, VBA will help with deleting a claim. He’ll cancel the EP and delete documents. Matt can help as needed.
- To help Kevin, provide him a screenshot of the Review & Submit screen form data, or if needed provide him with the raw formData JSON
- Emily will create a spreadsheet to track test cases - this will help us understand if the submitted data is the same as the claim in VBMS & the PDF
- T-REX to edit the MPT email/Slack script to include that we’ll need volunteers to send their file number and email address to Kevin over a Teams chat or an encrypted email. To be done when requesting our 6-8 testers, whichever 3-4 respond or can do it.
- Schedule 30 minute sessions to perform MPT synchronously

**Comment by pacerwow** [comment]
app/sidekiq/evss/disability_compensation_form/submit_form526.rb#141

**Comment by pacerwow** [comment]
app/models/form526_submission.rb:371
User.find(user_uuid)

**Comment by sethdarragile6** [comment]
Successfully tested the final polling fixes for LH submissions and EVSS (where the polling should not kick off at all). All pass! (submissions 1451 and 1452 in Staging). Closing out!
