### ISSUE TITLE
VA.gov Mapping for "View my representative"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9009]
## Goal
Using thumbnails, we need to build out the proposed mapping for this feature at a high level that also shows the in-roads and its placement.

## Tasks
- [x] Establish the proposed location for the feature and show where traffic might go and come from.

## Acceptance Criteria
- [x] A mapping is shared in GH

**Comment by sporeboy** [comment]
Finished initial set of use cases and IA flow for POA features: https://xd.adobe.com/view/612eab1b-3f29-4fa4-43c5-2f21deb912e3-171f/

**Comment by sporeboy** [comment]
After reviewing the POA feature in eBenefits and the associated screen on VA.gov, there are three discrete features:
- View representative
- Appoint representative (VA Forms 21-22 and 21-22a)
- Accredited representative search

There are at least four use cases:
- Veteran knows representative info, wants to submit form electronically
- Veteran knows some information, wants to search for complete info then submit form electronically
- Veteran wants to search for representative, then partially fill PDF for manual submission
- Veteran wants to view appointed representative

**Comment by jason-gcio** [comment]
This is good stuff Jim, thank you.

**Comment by sporeboy** [comment]
MD doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/poa-user-flows.md
