### ISSUE TITLE
Submitted Request summary screen does not show Other Details text entered by user

### ISSUE THREAD

**Issue by mshatalov-va** [department-of-veterans-affairs/va.gov-team#90106]
## Summary
Submitted Request summary screen does not show Other Details text entered by user.
Test patient user: cathedris.l.mitulski@id.me

## Specs
- Device: 
- Browser: 

## Steps to Reproduce

1. Go to: Schedule appointment https://staging.va.gov/my-health/appointments/schedule/type-of-care
2. Go through the steps to schedule a CC request
3. In What’s the reason for this appointment? - enter test text to check later
4. Continue through the steps to finish scheduling.  
5. Note the test text on the request summary screen
6. Click Submit request
7. Validate results on the request confirmation screen and check the newly created request details.
8. Validate that the text is being passed in Devtools in https://staging-api.va.gov/vaos/v2/appointments? call:

                "reasonCode": {
                    "text": "xxxxxxx"

where "xxxxxxx" is the text entered in step 5

### Actual Result
 What’s the reason for this appointment? - test text does not appear on summary screen

### Desired Result
 What’s the reason for this appointment? - test text must be shown on summary screen

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

![image](https://github.com/user-attachments/assets/4aef15d8-3cc4-4cf2-892b-009fda364dd9)
![image](https://github.com/user-attachments/assets/024472ab-82da-4310-8570-1b968b7c4ff3)
![image](https://github.com/user-attachments/assets/7eaf7918-c83e-49e8-b9ca-7cafef0d9dae)

**Comment by ldelacosta** [comment]
This is high priority ticket for Sprint 13 (bug production). 

I disabled the Appointment Redesign feature toggle in staging and the issue was still present. It is not related to the Appointment Details redesign work. 

See screenshot for Judy Morrison: 

<img width="1032" alt="Screenshot 2024-08-06 at 4 12 22 PM" src="https://github.com/user-attachments/assets/b5a6acb5-921d-4bf8-8baa-f5fd2a6f8ef8">

FYI: @Bren22va @JRRoof @simiadebowale

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/90106?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
Please size this asynchronously @simiadebowale @ryanshaw @JunTaoLuo

**Comment by Bren22va** [comment]
Please size this asynchronously @simiadebowale @ryanshaw @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Setting the estimate to 2 based on offline convo with @jenniemc and @simiadebowale

**Comment by ldelacosta** [comment]
@JunTaoLuo - once the fix is pushed to staging, please respond to the [thread](https://dsva.slack.com/archives/CSCD0B1V3/p1722970774185179) as well for awareness. Thanks! cc: @Bren22va

**Comment by JunTaoLuo** [comment]
FYI the fix has been deployed to staging. I'll update the slack thread now.

**Comment by mshatalov-va** [comment]
This appears to have been fixed, at least on the "We have received your request" confirmation summary screen.  
![image](https://github.com/user-attachments/assets/94a6f59c-be4e-4bb5-891e-d6b33e85f537)

However, we are unable to validate the Pending request details portion due to [this open issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90262)

**Comment by ldelacosta** [comment]
@mshatalov-va - you can resume testing this ticket since we are able to create requests and view the list under Pending. Let me know if you have any questions. Added my test comments in here: [#90262](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/90262)

**Comment by mshatalov-va** [comment]
This appears to have been resolved.  "What’s the reason for this appointment?" user input text is now shown on the summary screen

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
