### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by phillipfrymanva** [department-of-veterans-affairs/va.gov-team#90101]
### Name

Phillip Fryman

### Email

phillip.fryman@va.gov

### Role

Research Coordinator

### Team

GRECC

### Product Manager (PM) name

Patrick Lynch

### Additional Notes

Figma access request for research materials design creation

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to phillip.fryman@va.gov.

**Comment by phillipfrymanva** [comment]
Rec'd. Appreciate it!
