### ISSUE TITLE
[Spike] - Document Appointment Type logic

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#90109]
Spike for the upcoming work to move Appointment type logic into the vets-api appointment_service. This will be a joint development effort by vets-website and vets-api.

We want to document the Appointment Type logic I.e, cc appointment, cc request, request, VA appointment on the FE.
The primary function we will need to look at is: `getAppointmentType` found in  our `transformers.js` file `(src/applications/vaos/services/appointment/transformers.js)`.

## Tasks
- Answer the following questions:
- What are the logics for determining the different types of Appointments?

**Comment by simiadebowale** [comment]
- If Appointment.Kind === 'cc' and Appointment.start exists or is not empty/null, we set `appointmentType` as `ccAppointment`.
- If Appointment.Kind === 'cc' and Appointment.requestedPeriods is not empty/null, we set `appointmentType` as `ccRequest`.
-  If Appointment.Kind !== 'cc' and Appointment.requestedPeriods is not empty/null, we set `appointmentType` as `request`.
-  For all other appointments, we set `appointmentType` as `vaAppointment`.

**Comment by simiadebowale** [comment]
Mobile team need to review.
cc: @ldelacosta

**Comment by simiadebowale** [comment]
Logic for modality:
Here's the complete logic we have for determining the different types of video appointments:
Telephone appointments, Appointment - Kind field = 'phone'.
Video appointments, Appointment - Kind field = 'telehealth'.
Atlas, Appointment - telehealth field should have an atlas field. i.e telehealth: {atlas: ...}
VA Video Connect using a VA device,  Appointment - telehealth field should have vvsKind field === 'MOBILE_ANY'  i.e telehealth: {vvsKind: 'MOBILE_ANY'} & Appointment.extension.patientHasMobileGfe === true
VA Video Connect at Home, Appointment - telehealth field should have vvsKind field === 'MOBILE_ANY'  i.e telehealth: {vvsKind: 'MOBILE_ANY'} & Appointment.extension.patientHasMobileGfe === false
VA Video Connect at a VA location,  Appointment - telehealth field should have vvsKind field === 'CLINIC_BASED' or 'STORE_FORWARD'  i.e telehealth: {vvsKind: 'CLINIC_BASED'}

Claim Exam - appt.serviceCategory === 'COMPENSATION & PENSION';
Phone appointment - appt.kind === 'phone'

**Comment by ldelacosta** [comment]
Hey @jperk51. We completed the spike ticket for the Appointment Type. Let us know if you have any questions. Thanks!

**Comment by simiadebowale** [comment]
BE migration complete. Will open FE tickets to clean up code
