### ISSUE TITLE
Update accessibility documentation for improved Collab Cycle clarity

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9010]
## User Story 
As a VFS team member, I need to know what is expected of me for 508 compliance, so that I can embrace self-sufficiency, be prepared for successful VSP touch points, and build great VFSs. 

## Background/Description 
VSP expects VFS teams to complete their own manual accessibility checks throughout their development process. There is an abundance of documentation about this, but it's unclear whether (or how well) that documentation and process has been communicated to VFS teams. 

Some of this is incorporated into the VSP Collaboration Cycle — for example, the Staging Review issue template links here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/accessibility-test-cases-template.md — there's a checklist at the bottom here, but what is the expectation for VFS teams? What are the instructions? How does this relate to other accessibility documentation? 

The scope of this issue does NOT include a complete overhaul of all accessibility documentation that VSP has published. See `Definition of Done` below.

## Team Members
Responsible: Gretchen
Consulted: Trevor
Informed: Jennifer

## Definition of Done
- [ ] Accessibility artifacts required in VSP Collaboration Cycle templates have been updated to provide clarity as needed 
- [ ] Future ideas for updates to accessibility documentation are captured in ZenHub backlog or elsewhere

**Comment by gmaciolek** [comment]
Goal for this week is to move the content from the draft into GitHub. Trevor will review it when he is back in the office next week. Doc will be published next week. We will also deprecate a few docs that this updated doc replaces.
