### ISSUE TITLE
Toxic Exposure 1.0: Revisit retryable and non-retryable errors

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#90125]
As an engineer I need to know how our service should respond to Lighthouse errors so I know what to do in response.

Review [these notes from August 1st](https://docs.google.com/document/d/1BY17Zgw245-xbnRyEPKVscQ89imtXQ64i6z3U0npD8Q/edit), the "Retryable" and "Non-retryable" sections.

- add to Retryable:
  - HTTP 401
  - HTTP 429 - hit the rate limit 
  - HTTP 499 - 504 - usually indicates something wrong w upstream service
 - add to non-Retryable
   - HTTP 404 - bad ICN, resource doesn't exist
   - HTTP 413 - payload is too large (unlikely)
- Conditionally Retryable
  - HTTP 422: if there is no `pointer` attribute in the error. This indicates there was a problem with an upstream service that LH can probably retry. Retry for our usual 24 hours, then send down the backup path if   

## Tasks
- implement logic in submitForm526Job handle errors method
- Communicate changes to Carbs, ask for risks/challenges
- Put behind Toxic Exposure feature flag

## Additional Information
We share a client id with the claims status tool
We're also adding the polling job, using the same endpoint
Should do this before 5% Canary

**Comment by christinec-fftc** [comment]
Ask from Emily in planning today - can we revisit the Veteran experience when these various errors occur? We can use this opportunity just for FE discovery and file any new tickets (design or FE implementation) as needed.

Happy to pair on this!

**Comment by christinec-fftc** [comment]
related discussion on current UX ([thread](https://dsva.slack.com/archives/C04KW0B46N5/p1715876012906329))

**Comment by mayacarrolluxa6** [comment]
@aurora-a-k-a-lightning I took a pass at designing a conditionally retry able error page.<img width="163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1894a94807f83b23dd96339a0de1781c2a491ec1/Proposed.png" alt="Proposed.png" />
