### ISSUE TITLE
[Bug] EVSS gets called without EDIPI -  form526

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#9014]
## User Story or Problem Statement
Research how we are making form526 to evss without an EDIPI and report back to Michael Walker.

During a call with EVSS they mentioned that over a one week period they were seeing 37k failed hits to their services that require EDIPI.  Although a lot of these were 526 claims, it was not only those claims.  We believe we may have a gap somewhere in some of the form submissions that allows things to get through.  

Edit: splitting this into two issues #8676 is the PCIU issue.  This one is the  form526 issue, which likely happens less often of times we call EVSS without an edipi.

example form526 request to evss with no EDIPI
````
2020-05-01 13:55:22 CT
Unique ID: [1588359322771]
Server Name: [ManagedServer005]
Error Code: [AUTH_INVALID_IDENTITY] 
Missing Attributes: [EDIPI] Invalid Attributes: []
DETAILS OF FAILED REQUEST (in try/catch) --> https://www.ebenefits.va.gov:443/wss-form526-services-web-v2/rest/form526/v2/submit
REQUEST HEADER --> Host = www.ebenefits.va.gov
REQUEST HEADER --> user-agent = Faraday v0.17.0
REQUEST HEADER --> va_eauth_csid = DSLogon
REQUEST HEADER --> va_eauth_authenticationmethod = DSLogon
REQUEST HEADER --> va_eauth_pnidtype = SSN
REQUEST HEADER --> va_eauth_assurancelevel = 3
REQUEST HEADER --> va_eauth_firstname = [redacted]
REQUEST HEADER --> va_eauth_lastname = [redacted]
REQUEST HEADER --> va_eauth_issueinstant = 2020-05-01T17:22:27Z
REQUEST HEADER --> va_eauth_dodedipnid =
REQUEST HEADER --> va_eauth_birlsfilenumber = [redacted]
REQUEST HEADER --> va_eauth_pid = [redacted]
REQUEST HEADER FOUND BUT OMMITTED, POSSIBLE PII --> va_eauth_pnid
REQUEST HEADER FOUND BUT OMMITTED, POSSIBLE PII --> va_eauth_birthdate
REQUEST HEADER --> va_eauth_authorization = {"authorizationResponse":{"status":"VETERAN","idType":"SSN","id":"[redacted]","edi":null,"firstName":"[redacted]","lastName":"[redacted]","birthDate":"[redacted]","gender":"MALE"}}
REQUEST HEADER --> va_eauth_authenticationauthority = eauth
REQUEST HEADER --> va_eauth_service_transaction_id = vagov-0b49a02a-79c4-4696-a8e4-dfa167b7cc1d
 ````

## Goal
Reduction in number of EDIPI errors or put another way, requests with no EDIPI.

## Acceptance Criteria
- [x] Problem figured out, additional fix ticket (if needed) written.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
After many hours of investigation I am not able to discover a way for our service to make form526 submissions to EVSS without the EDIPI.  The [before action on the controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/disability_compensation_forms_controller.rb#L5) makes it impossible for any methods to be called without first checking for the EDIPI. As an extra precaution @annaswims and I searched the most recent 1,000 form 526 submissions and all had the EDIPI present. I do not think the posts to `/form526/v2/submit` with missing EDIPIs could have come from our application.
