### ISSUE TITLE
[FE] Check body styles on appt detail page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90154]
## Tasks

- [ ] Check body styles on appt detail page. Are all the body styles the same style and font size? To the eye, they look a bit different. Just want to double check. For example, the "bring your insurance..." looks a bit different than the rest of the body content on the page. But, I could be seeing things. <br><br>

<img width="350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEk4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea0c8d59d33b72d957b8ddef381986c2ebd63e01/Screenshot%202024-08-07%20at%2010.43.18%E2%80%AFAM.png" alt="Screenshot 2024-08-07 at 10.43.18 AM.png" />

**Comment by benbrasso-agile6** [comment]
@loripusey can this be brought into this sprint for FE?

**Comment by loripusey** [comment]
sure why not

**Comment by benbrasso-agile6** [comment]
@wullaski you want to point and grab this ticket please?

**Comment by wullaski** [comment]
@benbrasso-agile6 No you're not seeing things. There's something in the uswds that is making the font-size slightly larger than the base size of 16px.

```
p, a, ol, ul, li, dl, dt, dd, form, label, button {
  font-family: Source Sans Pro Web, "Source Sans Pro", "Helvetica Neue", Helvetica, Arial, sans;
  font-size: 1.06rem;
  line-height: 1.5;
}
```

Since a lot of the text on the details view is just wrapped in a div and isn't wrapped in one of those elements above it's being rendered at 16px instead of inheriting the 1.06rem size from that rule.

**Comment by benbrasso-agile6** [comment]
That's fine. I'm good to close this. Thanks for looking.

**Comment by wullaski** [comment]
We could wrap some of that content in a paragraph tag that way it would inherit that slightly larger font-size.

**Comment by benbrasso-agile6** [comment]
@outerpress take a look, FYI

**Comment by outerpress** [comment]
This is likely from the [design system font-normalization change](https://dsva.slack.com/archives/C03R5SBELQM/p1717618603508049) to set the base font size to 16.96px

I'm not sure why it doesn't apply to content that's not in semantic tags - but either way I agree with @wullaski that it should be in a `<p>` tag to support screenreader users

**Comment by wullaski** [comment]
@benbrasso-agile6, @loripusey I think we can keep this open pull into this sprint and make those changes. I can look elsewhere as well for anything that might not have a semantic tag around it.

**Comment by benbrasso-agile6** [comment]
Def not a release blocker. But, sounds good.

**Comment by wullaski** [comment]
@outerpress I was wondering the same thing about why it's not applied to the entire body. I was thinking about using an `<address>` tag but that wouldn't get the font size change.

**Comment by brianseek** [comment]
@benbrasso-agile6 this is merged and ready for validation. See screenshot:
<img width="222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d36c254f26dd488c7966073f911cdbd67a1192e/localhost_3001_health-care_appointment-pre-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%286%29.png" alt="localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (6).png" />

**Comment by benbrasso-agile6** [comment]
LGTM
