### ISSUE TITLE
Burial | Document Burial Submission Failure Points

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#90177]
Please document the various Failure scenarios that can occur in 530 submissions, and what we do in each scenario, ie. logging, stats, monitoring

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723151653207/96d1b1b708124876a531148a12fe71c865dc040f?sender=ud3f8cf5db16db1f0e9e72209

What happens when:
- vets-api is down
- vets-api controller unreachable
- SavedClaim cant be saved
- Benefits API fails
- Benefits API succeeds, but polling job shows failure
- anything else I missed

Acceptance Criteria:

- [ ]  update mural board to reflect failure locations and current monitoring. Include link to actual monitor for each log/statsd being recorded. 
- [ ]  Create tickets as needed (Identify proper statsd metric vs. logs)
- [ ]  Schedule meeting to review findings with team lead and VA eng lead

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/90177?planning-poker) with Zenhub @danlim715 @TaiWilkin @wayne-weibel @mjknight50 @scottsdevelopment

**Comment by sanjabaj2** [comment]
[This ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90218) can be linked as sub-ticket for individual findings.

**Comment by wayne-weibel** [comment]
Will plan the meeting to present this and [the pension findings](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/90282)

**Comment by TaiWilkin** [comment]
Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723151653207/96d1b1b708124876a531148a12fe71c865dc040f?sender=u2ee7ebd1bc9eabbc93bc6372
Tickets:
[Burial | Findings | remove v2 flipper](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91823)
[Burial | Findings | duplicate monitoring functions from pensions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91824)
[Burial | Findings | port burials code to a module](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91827)
[Burial | Pension | refactor monitoring class/functions to be reusable](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91828)
