### ISSUE TITLE
Draft a Product Success Tool for VAOS

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9017]
## User Story or Problem Statement
How might we present KPI dashboarding for the eBenefits team?

How might we expand the KPI version of the Product Success Tool & what does that effort look like?

## Goal
Create a KPI dashboard for VAOS on Domo.

## Acceptance Criteria
- [ ] Users can clearly see their KPIs on Domo so that they can understand if their product is healthy.

## Definition of Done
- [ ] Dashboard has been designed on Domo
- [ ] All available metrics are linked to their source
- [ ] Dashboard has been shared with users

---

Dependency on: [9016](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9016)

**Comment by amycesal** [comment]
Objectives are in and charts are more styled. 

https://va-gov.domo.com/page/565662008

[Uploading... Screen Shot 2020-06-09 at 4.00.23 PM.png ]

**Comment by joanneesteban** [comment]
To Do: For any charts that don't have dates shown, specify the date ranges either in notes or in the title. (i.e. April 13 - present).

**Comment by joanneesteban** [comment]
Additional AC:

- [ ] Dynamic or asterisk on date ranges for filtered data

**Comment by joanneesteban** [comment]
Closing this ticket - will open new tickets for any updates.
