### ISSUE TITLE
COE | Document Failure points

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#90182]
Please document the various Failure scenarios that can occur inCOE/LGY  submissions, and what we do in each scenario
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?wid=0-1721321111054&sender=u0e23f90bc2aa6d1f44e99992

What happens when:
- vets-api is down
- vets-api controller unreachable
- SavedClaim cant be saved
- COE API Fails
- anything else I missed

Acceptance Criteria:

- [ ]  update mural board to reflect failure locations and current monitoring. Include link to actual monitor for each log/statsd being recorded. 
- [ ]  Create tickets as needed (Identify proper statsd metric vs. logs)
- [ ]  Schedule meeting to review findings with team lead and VA eng lead

**Comment by sanjabaj2** [comment]
Please review/comment on [Steve's summary found here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/failure-error-reviews/coe.md).

**Comment by va-albers** [comment]
[modules/va_notify/app/sidekiq/va_notify/in_progress_1880_form_reminder.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_notify/app/sidekiq/va_notify/in_progress_1880_form_reminder.rb) should have an exhaustion handler, a monitor that catches it, and a process/playbook for addressing error cases

**Comment by va-albers** [comment]
Line 22 below it raises an error if the veteran ICN is blank.  Since this error is thrown in the Sidekiq job, I imagine this would just result in the same error happening 14 times in a row?
```raise MissingICN, "ICN not found for InProgressForm: #{in_progress_form.id}" if veteran.icn.blank?```
This could also potentially be a silent failure case - if the ICN does not exist what happens to the case?

**Comment by sanjabaj2** [comment]
Co0nsider [this requirement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89252) as well.

**Comment by micahaspyr** [comment]
@va-albers concerning this ticket, [COE | Findings | Failure/exhaustion alerts #91183](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91183), this codebase doesn't appear to be owned by our team.  It lies within the va_notify module. Do we just need to reach out and make them aware of this issue so that they may change it or maybe to get permission?
