### ISSUE TITLE
SSOe page in developer docs is very out-of-date

### ISSUE THREAD

**Issue by JonathanKamensDVA** [department-of-veterans-affairs/va.gov-team#90184]
### Description

The SSOe page in the developer docs starts like this:

>Status as of April 7, 2020: [VA.gov](http://va.gov/) sign-in via SSOe is still in beta. Once fully launched, SSOe will become a hard dependency for sign-in to [VA.gov](http://va.gov/).

Can we get this updated?

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/ssoe

### Which type of team are you on? (Platform team, VFS team, or Leadership)

Leadership

**Comment by taylojill** [comment]
Hi @JonathanKamensDVA - thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@LindseySaari or @joeniquette can you advise whether SSOe has been fully launched and whether we can simply remove this dated message from the page on Platform Website?

**Comment by jknipes** [comment]
Per Lindsey, we should review with Identity Team.

**Comment by jknipes** [comment]
[Edit work is being tracked in 92902](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92902)

**Comment by jknipes** [comment]
work completed in [ticket 92902](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92902), closing as _Done_
