### ISSUE TITLE
UX analytics: Track go-back links to nat'l portal

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#90193]
## Description

HIGH PRIORITY
How many users choose to go back to the national portal? In which tools are users clicking that link the most?

### User story

As a Cartography team member, I want to understand how many users are clicking the go-back links to return to the national portal. 

### Notes
- Use GA4

Possible tasks:
- [ ] Attend analytics office hours and/or watch past trainings to gain understanding 
- [ ] Validate what you create w Jamie Stutt and / or Wes Rowe

## Acceptance criteria
- [x] Report is set up to track clicks to go back to nat'l portal on the LP and on the tool pages
- [x] Categorize tool opt-outs/go-backs differently than the landing page opt-outs

**Comment by wesrowe** [comment]
Discussed dependency on Analytics team's implementation. Added blocking issue.

**Comment by wesrowe** [comment]
Jamie updated me that they are pulling this into their sprint starting 8/15, so we'll have "go back" links tracked pretty soon!

**Comment by wesrowe** [comment]
@fmccaf1 @katbrinkley, I just [got word](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87061#issuecomment-2310587781) that the Analytics team finished the outbound-link work that should enable our ticket! Github comment includes a link to a GA4 exploration that shows how to use it.

**Comment by katbrinkley** [comment]
Awesome! will we just pull this ticket into the next sprint? @wesrowe

**Comment by fmccaf1** [comment]
[Here is the report](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/wNwRxkQnRa6BXVjysnHA0Q)

One thing that is a little strange is the report shows 4 different links (though only 2 are really getting clicks). The one at the top of the report - getting the most clicks - is clearly the link in the MR card on our page. And seems the second highest is the link to the nat'l portal's home page from our lede text. The other two are unclear. 

Here are details about those other two: 
- The one that has received 14 clicks in the past week is going to url: https://www.myhealth.va.gov/mhv-portal-web/download-my-data
- The one that has received 5 clicks goes to: https://www.myhealth.va.gov/mhv-portal-web/home
