### ISSUE TITLE
Analytics New KPI dashboard request & KPI dashboard update request for MHV on VA.gov

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#90196]
# Request an Update to an Existing Dashboard

**Tell us what you need done:**
- [ ] [New Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-new-dashboards)
[ x ] [Updates to Existing Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-updates-to-existing-dashboards)

Standardized dashboards are currently available for [Forms](https://va-gov.domo.com/page/447193050?userId=853813555), [Content](https://va-gov.domo.com/page/426422632), & [Search](https://va-gov.domo.com/page/1964748112) products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## For New Dashboards

------------
## For Updates to Existing Dashboards 

First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [ x ] **Other:** Add in visualization for questions whereby track positives (4 or 5) and negative (1 or 2) responses in line graph over time___

Per Basil's instructions [in this thread](https://dsva.slack.com/archives/C1Q4294JJ/p1723052831159659?thread_ts=1722958669.556819&cid=C1Q4294JJ), won't include additional KPI request. 
------------------

**Comment by rbsingleton** [comment]
Existing Domo dashboard: [MHV on VA.gov CSAT dashboard](https://va-gov.domo.com/page/601491420?userId=1745144633)
- Additional request: update name of dashboard

**Comment by Blivaditis** [comment]
Hey Robin, making a note on here for tracking purposes that we are meeting Friday to discuss this along with potential discrepancies between your data in Power Bi and what we are seeing in Domo.

**Comment by Blivaditis** [comment]
Internal: here is a [link](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/zh/534) with more background on the ask

**Comment by johnny-jesensky-adhoc** [comment]
As discussed in refinement -- closing this ticket. This request was met via Slack.

FYI @Blivaditis
