### ISSUE TITLE
Index page for Drupal-managed simple forms

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#90201]
`/digital-form` would show an index page for all forms managed by Drupal. If this were implemented, it would show the list rather than indicating that a form id is missing.

It's possible this would only be a thing in lower environments, but that depends on what purpose we are trying to serve. It seems at first thought that we might not want this to be surfaced to Veterans because there should be no distinction to Veterans between Drupal-managed forms and other forms.

**Comment by Karak888** [comment]
Moving away from index page concept - moving to close.
