### ISSUE TITLE
Burial | Create Error Catch and Log for Confirmation Email Failures

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#90219]
## Issue Description
_When the confirmation email fails to send, [it triggers a claim status error for VRE](https://dsva.slack.com/archives/C06C2D2PJQZ/p1722445309071909). A separate error catch and log needs to be created form email failures, so we can differentiate between claim failures and email failures. This should be done for all forms that have a confirmation email._

---
## Tasks
- [ ] Create a separate error catch and log for the burial form

## Acceptance Criteria
- [ ] Confirmation email failures have a separate error catch and log than claim failures
---

**Comment by mjknight50** [comment]
Refinement result:  Confirm if there is an error catch on VA-Notify job itself.  If this ticket is instead related to isolating sidekiq processes (transactions?), then it should be low priority as an edge case.

**Comment by wayne-weibel** [comment]
duplicate, done in #90725
