### ISSUE TITLE
Update link + destination for medical supply URLs

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#90220]
## Description
This ticket describes a two-part problem. 
* 1.) We have two links on the landing page that refer to the same destination (the medical supply re-order form) and we need to combine those links so that we have one link for this 
* 2.) those links are currently routing users to the wrong URL destination. They go to the benefit hub page for supplies instead of the form. 

### User story

As a Veteran, I want to be able to re-order supplies that can be requested online in the most direct and efficient way possible, by being sent straight to the online order form instead of to a circuitous path via the` /health-care` benefit hub that is outside of the mhv health portal. 

### Notes
- Slack thread here, @Jenny-yw noticed that the top 2 links under the Medical Supplies box that say "order..." are not actually routing users to the online re-order form. _They should be_, but instead they go to the benefit hub page. 
- The top two links have a duplicative destination (both **should** be routing users to the form) and we want to combine these links so that there is one link to cover both supply types. 

Should look like this: 
<img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDArQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb76fa9bdf4eab71e0fb0ccf911accbf771036e1/Screenshot%202024-08-07%20at%203.46.32%E2%80%AFPM.png" alt="Screenshot 2024-08-07 at 3.46.32 PM.png" />

* [Figma file is here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/Archived%3A-MHV-Landing-Page?node-id=3630-1745&t=giwUuHNWX1avNpDt-0)

Possible tasks:
- [ ] Combine the top two links under the medical supply box to reflect a **single** link that reads: **"Order hearing aid and CPAP supplies"**
- [ ] Update the URL destination of that link to point to the right place, the actual medical supply re-order form: `va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction`

## Acceptance criteria
- Landing page links in medical supplies box match the link text + destinations named in this [Figma file](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/Archived%3A-MHV-Landing-Page?node-id=3630-1745&t=giwUuHNWX1avNpDt-0)
- IA review
- QA review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the two order links have been merged to one and it sends users to this URL: https://staging.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction

The "Learn how to order..." link brings the user to this link: https://staging.va.gov/health-care/order-medical-supplies/

**Comment by sterkenburgsara** [comment]
I flagged this issue with breadcrumbs for their team already. Not sure what's being done on that front, though. cc @Jenny-yw

**Comment by Jenny-yw** [comment]
Thanks for updating the link on MHV LP! Yes we're aware of the breadcrumbs issue, and it's in the backlog. Supplies team is shorthanded. @sterkenburgsara
