### ISSUE TITLE
Combine street 1, 2, and 3 text into a single line

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#90231]
As a user, I don't want my 2nd and 3rd street address lines to be dropped just because the form only has a single line for my street address, so that my information is complete.

Description:
Right now, 10-10d and 10-7959c just take `street1` and print that in the forms on their single street lines. This ticket is to concatenate the text from `street1`, `street2`, `street3` into a single line of text BEFORE we send data to the backend so that the BE can just print the entirety of street data in the single fields (like a user would do if filling it out manually).

Acceptance criteria:
- 10-10d pdf is stamped with all the text from the three street lines collected in the form
- 10-7959c pdf is stamped with all the text from the three street lines collected in the form

**Comment by baltes** [comment]
already done
