### ISSUE TITLE
Discovery: Identify existing common VA.gov account help issues for MVP learning center content

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9027]
# Discovery: Identify existing common VA.gov account help issues for MVP learning center content

[x] Identify current common/top VA.gov account support issues via call center data
[x] Gather existing call center knowledge articles on VA.gov account customer problems. 
[x] Identify existing VA.gov content on the public website (sign in FAQs, etc.) See list [here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9027#issuecomment-649849604)

**Drop source call center articles and data here;**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/call-center-source-articles

Content strategist: @DanielleThierryUSDSVA  / Call center SME @clantosswett 

## Headlines
**Product outline and info:**
[Learning center product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp) 

**WIP mockups** 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx  - I've updated the original issue. This has gone through DEPO intake and we can begin work. Let's sync to do a deep dive on how we move forward. We may do this as the kickoff or before the kickoff.

**Comment by jenniferlee-dsva** [comment]
@clantosswett  - We'd love to close this ticket so we can start actual writing/rewriting work next. 

Could you upload the source call center articles, call volume data, and any other source materials related to top VA.gov call center customer issues here;
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/call-center-source-articles

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva putting together list of potential questions based on contact center info.

**Comment by jenniferlee-dsva** [comment]
@danielle - this is the list of articles for MVP VA.gov account and profile topic that we discussed at our call with Chante, plus 1 omission and 1 addition (IRIS phone number page).  Take a look and thumbs up/down here if this is a reasonable list to start with. 

This is just to get something in front of users for research. We can and will of course add more VA.gov account issues for launch. 

1. Sign in FAQs `[already exists - just putting it into LC template]`
2. VA.gov profile FAQs` [already exists - just putting it into LC template]`
3. How to create your VA.gov online account -- `as a step by step w/screenshots`
4. How to sign in to VA.gov  -`- as a step by step w/screenshots`
5. Connected apps FAQs `[already exists - just putting it into LC template]`
6. Troubleshooting DSLogon 
7. Mismatched account error [ high incidence – single faq template? about?]

~Direct deposit video template – product video – from chante]~  `Let's omit this for this topic; we have a video template already mocked up, so let's see if Liz will be okay using that during research. `

8. [Phone number list?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/call-center-source-articles/IRIS%20Toll%20Free%20Numbers%20for%20Contacting%20VA.pdf)  - this could be an About template, with just text, or also accordions, and tables. (Source from IRIS) 

sorry I'm behind on my other items - will work on finishing them next week!

**Comment by jenniferlee-dsva** [comment]
@DanielleThierryUSDSVA @clantosswett - Is it okay to close this "identify" ticket now? See this comment for list of mvp articles to prototype with: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9027#issuecomment-649849604

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva Yes! I'm all good with closing this one. Thanks!
