### ISSUE TITLE
10-7959a: CHAMPVA Claims confirmation page CAIA updates

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#90284]
Update the content according the CAIA's suggestions in the Figma [file]
(https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1880-36481&t=cs26ibfbr7OTIvbU-0)

Original [Ticket #89771](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/89771) info below:
As a CHAMPVA Claims user, I need to know the status of my form when I click submit and what to expect next.

- success message only
- error state will be out of the box (appears on the review page)
- leave out any mention of email notification
- remove 'need help?' footer since that info is different from the one we're providing

Acceptance criteria

- When my submit gets a 200 response from s3
  - The messaging on the page lets me know my application submitted successfully
  - I get information about how to contact the CHAMPVA call center if I want to follow up (use the same info from 10-10d)
  - I get information on general timing for processing

More info
When a user clicks submit after completing 10-7959a, the site will generate their PDF and metadata and send one or more files to an s3 bucket where it can be picked up by PEGA processes.

At the time of submit, we won't know anything about PEGA's processing status, so this messaging is meant to let the user know that we got their application and when they should expect to hear something new. This is distinct from what we'll send them in an email confirmation, which will happen after we know that their application has been imported successfully into PEGA.

**Comment by jamiefiore** [comment]
[Updated with the CAIA comments ](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=1880-37000&t=cs26ibfbr7OTIvbU-0) @marywang2 @baltes

**Comment by marywang2** [comment]
@jamiefiore thank you, is the figma for this screen final or is it still in progress?

**Comment by jamiefiore** [comment]
The Figma is the most recent with the CAIA revisions
