### ISSUE TITLE
Pension | Document Pension Submission Failure Points

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#90282]
Please document the various Failure scenarios that can occur in 527 submissions, and what we do in each scenario, ie. logging, stats, monitoring.  The goal here is to understand the failure points and to make sure we don't have any silent failures or uncaught failures. 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723151514073/384e8cb5052fd80bfd6d93da645b97e5b22984b2?sender=ud3f8cf5db16db1f0e9e72209

What happens when:

vets-api is down
vets-api controller unreachable
SavedClaim cant be saved
Benefits API fails
Benefits API succeeds, but polling job shows failure
anything else I missed

Acceptance Criteria:

- [x]  update mural board to reflect failure locations and current monitoring
- [x]  Create tickets as needed (including identifying appropriate statsd metrics)
- [x]  Schedule meeting to review findings with team lead and VA eng lead

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/90282?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by wayne-weibel** [comment]
https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/90724

**Comment by sanjabaj2** [comment]
Let's schedule a call with Steve and I to review findings. In the mean time, I will be creating a summary page,[ similar to one that Steve created for COE](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/e1521448047411653601df009425204951ce6907/teams/benefits/failure-error-reviews/coe.md?plain=1).

**Comment by sanjabaj2** [comment]
@wayne-weibel Can you add link to specific monitors to each of logging line item in mural board?

**Comment by wayne-weibel** [comment]
@sanjabaj2 I added links to the existing comment threads in the mural board.  There are (currently) 3 primary locations for the monitors:

- pension controller, 3 monitors, catches validation errors, database issues, network issues, etc
- upload sidekiq job, 1 monitor, catches job exhaustion
- bulk status job, 1 monitor, catches lighthouse status failure
