### ISSUE TITLE
Migrate OnCall documentation out of vets.gov-team repo

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#903]
We have an OnCall documentation folder in the old vets.gov-team repo that needs to be migrated out, and I think the Operations team is probably best equipped to provide knowledge here. There's several document that are woefully out-of-date, so I don't want to just pick them up and move them as a first pass.

I'm putting them in va.gov-team-sensitive/OnCall since they'll contain some processes that could make it easier for phishing, and contain a good deal of contact info. Not all of it is necessarily "sensitive", but would like to keep it in one place if possible.

**Comment by ricetj** [comment]
@wyattwalter this is happening now right?

**Comment by wyattwalter** [comment]
This is done.
