### ISSUE TITLE
CF: Update link to include anchor reference

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9030]
As a Comparison Tool user, I need the link to take me to the relevant section of the linked page so that I do not have to search for the relevant content.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The link in "To learn more about Caution Flags, [visit the About this Tool Page](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp)." displayed on the institution profile page links to: "https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#CF"

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/12795

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/415&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I took a look and this looks great!

**Comment by sonntag-adam** [comment]
Closing story.
