### ISSUE TITLE
HLR | Staging Review - Regression test plan

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#90356]
A Regression Test Plan is a document that maps user stories to tests and which includes the results of executing those tests, thereby providing a strategy for verifying the functionality of your product prior to the work moving through the Collaboration Cycle. You are free to provide this information to Governance Team in whatever format is most convenient, though Platform recommends using [TestRail](https://dsvavsp.testrail.io/index.php).

Example: You can create a Regression Test Plan under the Test Runs & Results tab of TestRail. For an example regression plan, [see the VSP-Facility Locator regression plan](https://dsvavsp.testrail.io/index.php?/plans/view/149).

Note: VFS Teams not using TestRail are still expected to share a Regression Test Plan at the Collaboration Cycle Staging Review.

##Tasks

- [x] Create a Regression Test Plan
- [x] Execute tests
- [x] Document results

**Comment by eileen-coforma** [comment]
Started creating a test case (with existing test case as base)
https://dsvavsp.testrail.io/index.php?/cases/view/92233
It still needs a lot of work updating the screens, etc.

**Comment by eileen-coforma** [comment]
Eileen to meet with Skyler and DK on Thursday to chat about the remaining work

**Comment by dfong-adh** [comment]
DK will most likely pick this up while Eileen is out

**Comment by dfong-adh** [comment]
DK working on this while Eileen is out

**Comment by eileen-coforma** [comment]
Started on Friday. Links fixed and added steps. In progress with testing. Finished by tomorrow. No issues so far 🎉

**Comment by eileen-coforma** [comment]
DK has finished with this

**Comment by davidakennedy** [comment]
Update on this: Eileen reviewed the regression test I generated, and we agree it looks good. But Eileen wasn't able to generate a report. I need to investigate and figure out why.

**Comment by eileen-coforma** [comment]
Generating a report for: #90554

**Comment by davidakennedy** [comment]
Noting here that I've generated a report for #90554, and ran it by Jacob on the BMT. He confirmed that it's the right type of report, and it look normal to what he's generated before. All the tasks here are complete.
