### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90350]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > https://github.com/department-of-veterans-affairs/vets-website/pull/31286

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  Any user with a form or application in draft state (production and staging)

## Has fix been confirmed in Staging?
- [x] Yes
- [X] No (waiting for deployment as of 3:59 pm 8/8/24)

## Description
- Please provide the details/reason for the OOB Deploy
   > A PR was merged yesterday that broke My VA on staging and production as well. 
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [X] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [X] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [x] Notification is posted in the appropriate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests (This applies to revproxy and fwdproxy, but is not required for Frontend and Backend requests)
 - [x] Security Team has Reviewed the requests (This is not necessary for requests that are not related to security)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by AnthonyWFlowers** [comment]
PD Triggered [here](https://dsva.pagerduty.com/incidents/Q2L6MM72P8XHX0)

**Comment by AnthonyWFlowers** [comment]
Slack channels notified :https://dsva.slack.com/archives/CE4304QPK/p1723143683841759

**Comment by AnthonyWFlowers** [comment]
Fix has been verified in Prod, and the VA page is working as designed. OOB Deploy complete as of 6:05 Eastern
