### ISSUE TITLE
[FE] Add link collection component

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#90353]
## Summary
Add a link collection component below the medication review content on the pre-check-in complete page to help separate Medication review links from the existing links on the page.

This ticket will focus on changes to the pre-check-in medication review and following links.

## Tasks
- Change wording from `Find out how to check in on the day of your appointment` to `Find out how to check in`
- Add Header `Manage your appointments`
- Change link wording from `Sign in to manage all appointments` to `Sign in to VA.gov and schedule`

[Figma](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=2201-10449&t=7jnG7h3qXCHaMj1g-0)

**Comment by loripusey** [comment]
validated locally on main
