### ISSUE TITLE
[LH Doc Upload] BDD Instruction Migration Production Release and Monitoring

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#90361]
Releases the mgiration to the Lighthouse Benefits Documents API https://dev-developer.va.gov/explore/api/benefits-documents/docs?version=current iteratively for the `UploadBDDInstructions` job

Prerequisites
- [X] Both EVSS and Lighthouse API providers tested in staging
- [x] Production dashboard https://github.com/department-of-veterans-affairs/va.gov-team/issues/91269 built
- [x] Release plan presented to stakeholders
- [x] Rob and Greg at Lighthouse notified in vfs-evss-service-migration Slack channel

Release Checklist
- [x] Enable `disability_compensation_use_api_provider_for_bdd_instructions` flipper to start using new code
- [x] Thursday Oct. 22 enable `disability_compensation_upload_bdd_instructions_to_lighthouse` for 1 percent of users
- [x] Monday Oct. 28 enable `disability_compensation_upload_bdd_instructions_to_lighthouse` for 5 percent of users
- [x] Thursday Oct. 31 enable `disability_compensation_upload_bdd_instructions_to_lighthouse` for 50 percent of users
- [x] Wednesday Nov. 6 enable `disability_compensation_upload_bdd_instructions_to_lighthouse` for 100 percent of users
- [x] Create cleanup tickets for removing old code in UploadBDDInstructions job; remove checks for `disability_compensation_upload_bdd_instructions_to_lighthouse` this will just be on for everybody

**Comment by NB28VT** [comment]
@lisacapaccioli marked the "release plan presented to stakeholders" box done, if the retro counts?

**Comment by lisacapaccioli** [comment]
@NB28VT - Yes, I shared in the Benefits portfolio too and tagged Emily on it. While you were out, Kyle and Alison felt that a formal review for this work shouldn't be necessary. I trust you all if you think we are good with just letting them know via slack and review. Thanks

**Comment by NB28VT** [comment]
[Clean up ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96571) created, not sure when we want to close this ticket, I'd say we monitor Lighthouse at 100 percent for at least a week
