### ISSUE TITLE
[LH Doc Upload] 0781/a (5) Migration Production Release and Monitoring

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#90362]
This will be similar to the BDD release and monitoring checklist: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90361

Prerequisites
- [x] Both EVSS and Lighthouse API providers tested in staging
- [x] Production dashboard built
- [x] Release plan presented to stakeholders
- [x] Notify OCTO in benefits-disability slack channel
- [x] Rob and Greg at Lighthouse notified in vfs-evss-service-migration Slack channel

Release Checklist
1. Enable both 0781 migration flippers 
- [x] disability_compensation_use_api_provider_for_0781_uploads (ON)
- [x] Disability_compensation_upload_0781_to_lighthouse (1%)

2. Turn ON email flippers (just enable - not a percent)
- [x] Form526_send_0781_failure_notification (should be on already)
- [x] Disability_compensation_email_veteran_on_polled_lighthouse_doc_failure

**Comment by lisacapaccioli** [comment]
Thanks for the update. Here's the Release Plan: [DBEX Lighthouse Migration for 526 Ancillary Forms.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Lighthouse%20Migration%20for%20526%20Ancillary%20Forms.md)

**Comment by ajones446** [comment]
Status update: Rollout started for 1% of actors on November 13 at 2pm ET.

We will continue to manually monitor the dashboard for errors. A slack alert has been set to message the benefits-disability-notification channel with any errors.

- [ ] TODO: ask OCTO to double check the e-folder

**Comment by AmyPlange** [comment]
0781
For the 0781 release, we want to start by setting the feature flipper to send 1% of 0781 uploads to Lighthouse. After successfully passing the testing plan, we will then increase usage to 5%, 50%, then 100%.

Release date for 1%: Wednesday Nov 13
Release date for 5%: Friday Nov 15
Release date for 50%: Tuesday Nov 19
Release date for 100%: Thursday Nov 21
