### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by SnowboardTechie** [department-of-veterans-affairs/va.gov-team#90379]
### Name

Bryan Thompson

### Email

bryan.thompson@agile6.com

### Role

FS Engineer

### Team

Sitewide Public Websites & Facilities

### Product Manager (PM) name

Michael Skinner

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to bryan.thompson@agile6.com.

**Comment by SnowboardTechie** [comment]
I'm in now, thank you!
