### ISSUE TITLE
Troubleshoot: Missing Headers 

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#90377]
# Description
The issue of missing headers in VA.gov domains was introduced in the #platform-cop-devops channel -- Slack conversation link [here](https://dsva.slack.com/archives/C04CYC4LMU6/p1723143640617569). We know that CMS has recently integrated substantial changes to revproxy, but we don't know if that is involved int he root cause.

## Initial information
- HSTS headers are missing
- CSP headers are missing
- X-frame-options headers are missing
- Below screenshot showing current list of headers:
![image](https://github.com/user-attachments/assets/bc4b400b-b479-46e4-bb84-784b3aee85ee)

## Acceptance Criteria
- [x] The root cause of the missing headers has been discovered
- [x] A proposed resolution is described in a bug fix ticket

**Comment by ph-One** [comment]
Only website has the headers stripped out. Vets API returns all of the expected headers

**Comment by ph-One** [comment]
- Anything coming from S3 is missing headers
- Anything not coming from S3 has the headers.

**Comment by ph-One** [comment]
The root cause appears to be that when we fail-over between the Content buckets; we 404 and therefore lose all headers (Nginx does not preserve headers for non-successful requests). I'm explicitly adding these headers to the content blocks and testing my hypothesis

**Comment by ph-One** [comment]
Tests conclude that by adding back the headers during fail-over conditions between `@content` and `@nextcontent`, we get expected results

![image](https://github.com/user-attachments/assets/14a1e3e8-101d-412f-b93e-7066d5037b7b)

**Comment by ph-One** [comment]
This has been resolved and can be closed. See linked PRs for specifics on file changes made.
