### ISSUE TITLE
Qualitative Data Request [Medallia for July 2024 to present]

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#90384]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

07-01-2024

### Date Range End

08-09-2024

### Product Name(s)

526ez

### Product Description

Veterans use the 526ez to file for disability compensation on VA.gov. 

### Survey URL(s), key term(s), case category or type

www.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information
www.va.gov/disability/file-disability-claim-form-21-526ez/contact-information
www.va.gov/disability/file-disability-claim-form-21-526ez/housing-situation
www.va.gov/disability/file-disability-claim-form-21-526ez/terminally-ill
www.va.gov/disability/file-disability-claim-form-21-526ez/alternate-names
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/reserves-national-guard
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/federal-orders
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/separation-location
www.va.gov/disability/file-disability-claim-form-21-526ez/separation-pay
www.va.gov/disability/file-disability-claim-form-21-526ez/retirement-pay
www.va.gov/disability/file-disability-claim-form-21-526ez/training-pay
www.va.gov/disability/file-disability-claim-form-21-526ez/claim-type
www.va.gov/disability/file-disability-claim-form-21-526ez/disabilities/orientation
www.va.gov/disability/file-disability-claim-form-21-526ez/disabilities/rated-disabilities
www.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/add
www.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/follow-up
www.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/ptsd*
www.va.gov/disability/file-disability-claim-form-21-526ez/toxic-exposure/conditions
www.va.gov/disability/file-disability-claim-form-21-526ez/pow
www.va.gov/disability/file-disability-claim-form-21-526ez/additional-disability-benefits
www.va.gov/disability/file-disability-claim-form-21-526ez/adaptive-benefits
www.va.gov/disability/file-disability-claim-form-21-526ez/aid-and-attendance
www.va.gov/disability/file-disability-claim-form-21-526ez/individual-unemployability
www.va.gov/disability/file-disability-claim-form-21-526ez/additional-disability-benefits-summary
www.va.gov/disability/file-disability-claim-form-21-526ez/disabilities/summary
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/orientation
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/service-treatment-records
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/service-treatment-records-upload
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/evidence-types
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/evidence-types-bdd
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/va-medical-records
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records-upload
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records-release
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/additional-evidence
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/summary
www.va.gov/disability/file-disability-claim-form-21-526ez/how-claim-exams-work
www.va.gov/disability/file-disability-claim-form-21-526ez/payment-information
www.va.gov/disability/file-disability-claim-form-21-526ez/va-employee
www.va.gov/disability/file-disability-claim-form-21-526ez/retirement-pay-waiver
www.va.gov/disability/file-disability-claim-form-21-526ez/training-pay-waiver
www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit
www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation
 
 

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

evelyn.davis3@va.gov, michael.eng1@va.gov, Jared.pace@va.gov, shannon.ford1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
