### ISSUE TITLE
VSP - Make a VA appointment request

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9039]
As a veteran, I want to be able to request a VA healthcare appointment online.

## Definition of Done:
- [ ] Veteran can request VA appointment if eligible
- [ ] Eligibility for making VA appointment request:
   - Type of Care: Not all facilities support a given type of care – and even when they do, they may not support scheduling that type of care online. Each facility is configured independently from others.
    - Recency: Veterans are only able to use online scheduling if they’ve been seen at the selected facility for that type of care in the past 2 years
    - Request Limits: Facilities may opt to enforce a limit on the number of requests that can be outstanding simultaneously for a given type of care
- [ ] QA testing
- [ ] 508 Review

**Comment by laurenernest** [comment]
No longer needed
