### ISSUE TITLE
[COGNITION]: Include the visual label in aria-labels for videos and PDF downloads

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#904]
## Description

The visual labels for viewing videos and downloading PDFs are significantly different from the `aria-label` attributes. This could be confusing to users who are on the visual acuity spectrum but also use screen readers. Screenshots attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As an assistive device user, I want to hear the visual label included in the aria-label in a meaningful way

## Environment
* MacOS Mojave
* Safari
* VoiceOver

## Possible Fixes (optional)
We could adjust the `aria-label attributes like this to be more descriptive and follow the WCAG 2.1 guideline on label in name:

```html
<a
  aria-label="Go to video about VA disability compensation"
  class="video-link"
  target="_blank"
  href="https://www.youtube.com/watch?time_continue=3&amp;v=xE0LzeRgdAk"
  rel="noopener "
>
  <i class="fas fa-play-circle vads-u-padding-right--1"></i>
  Go to video
</a>
```

```html
<a
  aria-label="Download PDF VA helps service-disabled Veterans (2.48 megabytes)"
  class="file-download-with-icon"
  target="_blank"
  href="/files/2019-07/VA-Toolkit-9-Disability-Fact-Sheet-508.pdf"
  download="/files/2019-07/VA-Toolkit-9-Disability-Fact-Sheet-508.pdf"
>
  <i class="fas fa-download vads-u-padding-right--1"></i>
  Download PDF (2.48MB)
</a>
```

## WCAG or Vendor Guidance (optional)
* [Understanding Success Criterion 2.5.3: Label in Name](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html)

## Screenshots or Trace Logs

![Screen Shot 2019-08-09 at 4.53.23 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/874305e2-a66f-4f26-9e46-9434c16e51b2)

---
![Screen Shot 2019-08-09 at 4.55.55 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/6b909f56-a459-49bc-b8a4-ace6e4027b9c)

**Comment by jefflbrauer** [comment]
@1Copenut This fix is now on staging. please go ahead and retest.
https://staging.va.gov/outreach-and-events

**Comment by 1Copenut** [comment]
This update meets the spirit of the specification. I'll have the 508 office review it after we've remediated our issues and will re-open if they ask us to modify the `aria-label`.
