### ISSUE TITLE
Design Intent - IA Feedback - Modernized Check-in, Appointments, Travel Claims for Past Appointments

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#90412]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- This looks solid. Thanks for bringing it through!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must: within the form flow, links that go outside the flow should open in a new tab** The `check current mileage rates` link within the form flow should open in a new tab and the link text should indicate that with `(opens in a new tab)`. If there are any other links within the flow that lead to pages outside of the flow, those should open in a new tab (see [guidance on link behavior](https://design.va.gov/components/link/#behavior)). The `beneficiary travel agreement` link is a little different since it opens a detail child page _within_ the form and doesn't break the flow. 

- [x] **Should: adjust link text on first step of intro screen** The link text in the "Check your eligibility" step on the [intro screen](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2187-30609&t=nPB3tiWD7IpLtewe-4) could be a little clearer. If a user is only scanning headings and link text, how might the text more clearly state what the user will do? Check your eligibility? Learn more about travel reimbursement eligibility?
  ![Screenshot 2024-08-08 at 12 45 26 PM](https://github.com/user-attachments/assets/7ebc25df-b359-4c75-979a-ae562515d56a)

- [x] **Should: clarify back-link** Within the form flow, there is a back link and back button. Do they do the same thing? I know you're working with @sterkenburgsara on this. It could make sense to make the back link a "back to appointment" link. I know our guidance on this is...evolving. But, if there are two "back" options in this flow that do the same thing, we can likely remove one of them.

- [x] **Should: longer-term, create more paths to reimbursement in the web experience** (hat tip @sterkenburgsara who had this very good question) Currently to access this feature, Veterans will need to navigate to their appointments list, find a past appointment, then visit the CTA to start the reimbursement claim. Y'all have [outlined a few other ways](https://dsva.slack.com/archives/C022AC2STBM/p1723141899188609) that Veterans might access this reimbursement flow in the future (Card on My VA or MHV? Follow-up text message? Web notification?) I think these are all great ideas and should be explored. This also opens up a tiny can of worms for my next note...

- [x] **Consider: future content model for reimbursements** (again, @sterkenburgsara may already be discussing this) As we move more reimbursements to VA.gov, we should architect how the content model for a `reimbursement` relates to an `appointment` object. I ask these potentially silly questions as a way to keep the team thinking about how this flow should be architected in the IA, knowing that more reimbursement functionality is coming.
  - Could there be multiple reimbursements for one appointment?
  - Could there be multiple appointments with one reimbursement?
  - Are there reimbursements for non-appointment expenses?
  - Are `reimbursements` and `appointments` separate enough entities that they should not be bound together in the IA - i.e., the reimbursement flow should not necessarily be a "child" of the appointment, but its own separate but related flow? 
  - Would there be a future where `reimbursements` has its own section on MHV or My VA?

- [x] **Consider: conditional placement of direct deposit CTA** I understand it isn't possible now to detect whether folks have direct deposit set up. When that is possible, conditionally displaying the call to action to set up direct deposit would be extremely helpful.
![Screenshot 2024-08-08 at 12 46 55 PM](https://github.com/user-attachments/assets/3ab5736e-c3c8-43d0-bcda-2b48317ea450)

- [x] **Consider: task list for appointment tasks** I like the idea of building space for appointment tasks at the top of the appointment page. The IIR team is working on a [task list](https://design-system.service.gov.uk/components/task-list/) design to come through experimental design, similar to gov.uk's. Kat Kufalk is that team's PM if you want to reach out.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by benbrasso-agile6** [comment]
@micahtaylor 1, 2, 3 and 6 are yours :) 

@cgednalske @outerpress we need to meet up about items 4 and 7 in the coming weeks. We'll have to figure out timing... Christina and I were just talking about doing another research study (maybe unmoderated) to help steer decisions for these items. Will write a note to schedule some time for us to brainstorm.

**Comment by benbrasso-agile6** [comment]
Thanks, Erin!

**Comment by micahtaylor** [comment]
Addressed 1,2,3, and 6

**Comment by benbrasso-agile6** [comment]
Won't close this ticket out yet, but we're going to tackle the remaining items in a yet to be created collab cycle ticket based on [matt's response in Slack](https://dsva.slack.com/archives/C06RMRJCLHH/p1724700204356079?thread_ts=1724255551.018489&cid=C06RMRJCLHH)

**Comment by benbrasso-agile6** [comment]
> Would there be a future where reimbursements has its own section on MHV or My VA?

I think My VA accounts for linking to reimbursements. I'll double check as a follow up.

**Comment by benbrasso-agile6** [comment]
> Should: longer-term, create more paths to reimbursement in the web experience 

We started dialogue with VA Notify to send notifications to start scheduling and we've engaged VA staff to create a 7-day scripting message to let Veterans know how to self-schedule if they haven't started yet.

**Comment by benbrasso-agile6** [comment]
> Would there be a future where reimbursements has its own section on MHV or My VA?

There is an existing link on My VA. I would expect this link could change to point to Past Appointments, but the link text would also need to change. Currently, I think that link goes to the BTSSS portal. Tagging a few folks so we address this when released. @ayush-chak @loripusey @kristenmcconnell @mdewey @outerpress

**Comment by benbrasso-agile6** [comment]
<img width="728" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6837213d41d721a96436fcd91e3f0cb0de128d0/Screenshot%202024-08-28%20at%204.07.23%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 4.07.23 PM.png" />

**Comment by sterkenburgsara** [comment]
@benbrasso-agile6 I'm working on a ticket in my next sprint to update all MyHealtheVet links (except MR, until that one reaches 100% in Phase 1) to point to VA.gov builds. Can I get in on this conversation before I tackle that, so that we can reduce changes that MyVA team might need to make? 

I also want to +1 some of @erinrwhite's questions in this ticket around content modeling this work (and why we are building out travel reimbursement functionality in past appointments when we have a travel reimbursement page launching soon)? While you could argue that the appointment is part of the reimbursement mental model, it's actually the location of the facility where the appointment takes place that matters for reimbursement. I wonder if we could find some time to put head's together and think through this as a group? Holler if you have space for that, I'd love it!

**Comment by benbrasso-agile6** [comment]
When you say, "we have a travel reimbursement page launching soon," I believe there's plans to rebuild the entire BTSSS portal on VA.gov, but that might take a year or two. What's launching soon is an authenticated page that allows Veterans to review the status of their submitted claims on VA.gov. 

Knowing that there is a plan to rebuild BTSSS on VA.gov, but could take years... should we still meet? 

I'm not trying to deflect. Tbh, it's a good conversation to discuss with @kristenmcconnell at the SME sync. 

The Travel Pay Team is busy working on standing up that claim status page; so the launch of filing from past appts isn't imminent. There's time :)

**Comment by benbrasso-agile6** [comment]
Of course, our goal is to increase access to filing a claim; vs. filing in one place. E.g., check in, Appts, Appts in VAHB, check in in VAHB, Travel Reimbursement on VA.gov at some point (1-2 years; I honestly have no idea if that work is progressing). 

If/when Travel Reimbursement on VA.gov becomes a reality, then all those other places can be "doors" to file vs. separate places to file a claim.

**Comment by ayush-chak** [comment]
Hi folks! This looks like a broader conversation than the design intent items on this ticket - wanted to clarify a few things while catching up on this thread, but will respond on Slack (and link here). Happy to chat with everyone in a separate venue depending on what other information is needed!

**Comment by kristenmcconnell** [comment]
I just spent that last two days with the travel office talking about the change management process for travel pay. I'm going to write up that discussion, but I think that it will impact when we connect things up on My VA and MHV landing pages. So much more to come very soon.

**Comment by benbrasso-agile6** [comment]
@loripusey I think this also belongs to the Header change Epic

**Comment by benbrasso-agile6** [comment]
> Consider: task list for appointment tasks I like the idea of building space for appointment tasks at the top of the appointment page. The IIR team is working on a task list design to come through experimental design, similar to gov.uk's. Kat Kufalk is that team's PM if you want to reach out.

Agreed. Closing this ticket because this is also mentioned in the Design feedback.
