### ISSUE TITLE
Update SOCKS Access Request for passphrase check

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#90410]
Based on a recent scan that flagged a SOCKS Access Request, it was realized that the provided token did not have a strong passphrase. Based on that, security has requested that we add a checkbox to the SOCKS Access Request template. This checkbox would be required for the user to check prior to moving forward on their request. It was requested the text reads: "Please check this box to confirm that your SSH key has a strong passphrase"

**Comment by JonathanKamensDVA** [comment]
We may also wish to provide a link to instructions for how to add a passphrase to an SSH key on various platforms.

**Comment by bdech** [comment]
Here is the PR with the addition

https://github.com/department-of-veterans-affairs/va.gov-team/pull/91760

**Comment by bdech** [comment]
Visual example of what it will look like



![Image](https://github.com/user-attachments/assets/fceaca73-9599-4f50-bfda-dca452d5b9cd)

**Comment by bdech** [comment]
Heres is the code requiring the checkbox

![Image](https://github.com/user-attachments/assets/087d278c-0ea0-4f2e-913d-76f892a02739)

**Comment by bdech** [comment]
PR has been approved and merged into main.
