### ISSUE TITLE
SOCKS access for Keegan Kitagawa-Bosch

### ISSUE THREAD

**Issue by KKitagawa-Bosch** [department-of-veterans-affairs/va.gov-team#90439]
### Your Name

Keegan Kitagawa-Bosch

### Your Email

keegan.kitagawa-bosch@va.gov

### Your GitHub Handle

KKitagawa-Bosch

### Your Role and Team

Content Specialist on Governance Team

### Product Manager (PM) name and email

Shira Goodman, shira.goodman@oddball.io

### Product Owner (PO) name and email

Matt Dingee, matthew.dingee@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDS2BxkYqKWYa5ILtx4iX1DaIXntFKoLQCsMl7aHEd7oQWnjx51FBS+CBFw1OtrSowZV59svJ0HZnCu8T4lAfzRyF0V7HF2wEHZTUj24eBcOd4emazcuqVPcvKFQktY3/82syE/uBdObrnlexd6MCM8Lwch16YyKghGqdcR9J4evtxnxhgpVhDCpBLiPtnVagTEsr7nRvdXfazyXqlii/nSRajZWmo0TXXeVfMO4cazsM8+Mos5ICmUkNr34nKBnaR04i4PTH/cwPeJ7FyQw8ivBj769vaYiALk65Ytk9Dhm7gm0ezil3tVVFHudyBuOW61slEWs920osUtQV3GHThIK1nQ+4APoPqmbEaZQzQg8TZ5Qvd+01Iv192pVxo+mj+WGL5tixDqFq5kH/d2spWcxavovbkK7bhaMm4TVK3InhmgxVDXABu4xGn0FhCyG8+SwYusmIQ5dJ8jnkmDgvvXbY5uuOkM45mXoeL17o+qNwXjAO0XM+kfHG8Hli/Oe92a7PjK73ZUodEVYi/qnSQNSlURIt14eSB2JZ7XkuQeGwr0Ovr5yb/1KLc6720GEL9g7LpwSW0u/E8ESouFc65zoZWZz4mEq2D/NZOTONlAX/ogPN2H6RFPwGwNUMpdMKDIHCnJiA1HsDFehDjmmUBx/9n0KSc9Itc1o0dMk45GUw== keegankitagawa-bosch@Keegans-MBP.home

### E-QIP Transmittal Confirmation

N/A

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by bdech** [comment]
SOCKS PR

https://github.com/department-of-veterans-affairs/devops/pull/14709
