### ISSUE TITLE
SPIKE: Caseflow AWS and shared account

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#90454]
A request from security has been brought to Platform to look into Caseflow and their access with the AWS account that we share. The intent is to investigate what this looks like and document. Additionally, looking at options and recommendations on a path forward. Platform as a team has put out several suggestions / requests related to having our own separate account(s) and/or modifying the current account to isolate our space, etc. via profiles.

**Comment by little-oddball** [comment]
As a part of this we should look at not going under VAEC and get thoughts and insight together on what that might look like.

**Comment by little-oddball** [comment]
To follow up on this a little more, here is some specific discussion had in a recent government sync (9/31) and what information is being requested:

> The discovery work is related to one of the PTA changes likely to impact our ATO renewal significantly, which requires us to make a critical decision. We need to decide between two options: A. migrating our system under the VAEC AWS Organization or B. remaining a system in the Government Cloud outside of VAEC, with all necessary compliance controls properly implemented and documented.
> To make the decision, we need your expertise to conduct a thorough discovery of both options. The insights from this work are crucial in this decision process. For each option, we would like to understand the following:
> 
> - What is the scope of work, number of sprints, resources, licensing, and costs?
> - What limitations prevent us from doing what we do now, and how will we manage them in the future?
> - What new capabilities will we gain?
> - What are the dependencies and integrations?
> - What are the potential risks and mitigation strategies?

**Comment by kflow85** [comment]
Closing this ticket as further discussion and work will be tracked in ticket [#2006](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2006)
