### ISSUE TITLE
Vets-api terminal access for Alex Chan

### ISSUE THREAD

**Issue by alexchan-va** [department-of-veterans-affairs/va.gov-team#90478]
### Your Name

Alex Chan

### Your GitHub handle (terminal access is managed through GitHub)

@alexchan-va

### Team, Role, and Company of the target individual

VEBT Sustainment, Ruby on Rails Developer, GovCIO

### Product Manager (PM) name and email

Kara Ciprich, Kara.Ciprich@va.gov

### Product Owner (PO) name and email

Darla van Nieukerk, Darla.vanNieukerk@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

GovernmentCIO - Kimberly O. West

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

COR: Joseph Riccio Joseph.Riccio@va.gov

![transmittal](https://github.com/user-attachments/assets/1c998999-a233-49ce-989b-e6b29bd8c84e)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by GWright321** [comment]
Confirmed in Atlas
Transmittal notice provided

Access to dev and staging, provided

**Comment by GWright321** [comment]
@alexchan-va  You’ve been granted access to the `dev` and `staging` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
