### ISSUE TITLE
AWS access for Alex Chan

### ISSUE THREAD

**Issue by alexchan-va** [department-of-veterans-affairs/va.gov-team#90479]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Alex Chan

### Your Email

alex.chan1@va.gov

### Team, Role, and Company of the target individual

VEBT Sustainment, Ruby on Rails Developer, GovCIO

### Product Manager (PM) name and email

Darla van Nieukerk - darla.vannieukerk@va.gov

### Product Owner (PO) name and email

Darla van Nieukerk - darla.vannieukerk@va.gov

### Desired AWS Access

I need ssh access to the staging and dev EC2 instances to tail logs after code deploy success, confirm tasks were run, configurations are set correctly, and troubleshoot issues.

### Access Expiration

12/22/26

### E-QIP Transmittal Confirmation

![transmittal](https://github.com/user-attachments/assets/bff39cc1-00fc-4e54-b3e1-0822fe3c4765)

### Additional Notes

COR: Joseph Riccio Joseph.Riccio@va.gov

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by GcioGregg** [comment]
@GWright321 or anyone, any update on this request?  Thank you.

**Comment by GWright321** [comment]
Hello @GcioGregg. From my understanding the, @vsp-operations-aws-approver will review and update AWS access requests today. I am not apart of that team and accidentally assigned myself to this ticket 2 days ago. My apologies.

**Comment by GcioGregg** [comment]
Hi @GWright321, thanks for the update/comment.

**Comment by flooose** [comment]
Hi @GcioGregg and/or @alexchan-va since you're not looking at prod access, we can go ahead an move this along. Do you have any team members that I can reference so that I can give you similar permissions?

**Comment by GcioGregg** [comment]
Hi @flooose, I should have the same access level that we are seeking for Alex.  Thanks.

**Comment by flooose** [comment]
Thank you, @GcioGregg! I don't see Alex in our [VFS Roster](https://www.va.gov/atlas/product_directory/team_members?filter_by=last_name&filter_type=includes&filter=chan&commit=Filter). Could it be that he still needs to go through [orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)?

**Comment by GcioGregg** [comment]
Hi @flooose, I believe Alex has gone through all the orientation.  We also noticed he didn't seem to be part of the VFS Team Roster and commented on his original ticket to be added to the VFS Team Roster.  We were told that since he is a member of Atlas (confirmed) then he is part of the VFS Team Roster.  See Anthony Flowers comment here:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/85588.  Let me know if it's still an issue and I will follow up with Anthony.  Thanks!

**Comment by flooose** [comment]
Oh, I misspelled his name when I looked in Atlas! Sorry about that :)

Still though, the description about the desired access sounds like this is more of a Rails Console access request. Could that be? Since our application is hosted in k8s, simple EC2 ssh access wouldn't actually actually give you access to the logs, for instance.

**Comment by GcioGregg** [comment]
If you give Alex the same exact access that I have, he will have what he needs.  Thanks!

**Comment by flooose** [comment]
Finally got this across the finish line! Thank you for your patience.

**Comment by GcioGregg** [comment]
thank you!

**Comment by alexchan-va** [comment]
Hello, I tried accessing AWS for the first time to monitor ec2 instances and it says I am unauthorized. Could someone look over and make sure I have the correct permissions? Thanks.

![Screenshot_11-9-2024_172830_console amazonaws-us-gov com](https://github.com/user-attachments/assets/1329b7ed-da84-4495-83c1-6f246ab725e8)

**Comment by patrick-black-oddball** [comment]
@alexchan-va  - you are required to configure your account with MFA before you will be able to see any AWS resources in the console
