### ISSUE TITLE
Bug: Replace incorrect url with correct version

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#90505]
### User story

As a Veteran, I want the link to "download records using the previous version of My HealtheVet" to take me directly to the previous version of Medical Records. 

### Notes
- The blue "Learn More" dropdown alert on our landing page is pointing users to an incorrect (and less direct) link. Right now, link text "go back to the previous version of My HealtheVet" sends users to the nat'l portal home page
- The correct destination is the MR tool on the nat'l portal, which is the "download-my-data" deep link.

## Acceptance criteria
- Link within dropdown alert is sending users directly to the previous version of MR

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the "Go back to previous..." version link in the "Learn more..." blue expandable alert direct users to the previous version of the Medical Records tool on the national portal


https://github.com/user-attachments/assets/b60c1c8c-da93-411d-850b-7a6840b1ede5
