### ISSUE TITLE
Discovery: `vets-api` local testing consistency

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#90509]
# Description
Conduct a discovery effort to assess consistency between local testing and CI testing for `vets-api`. Focus on automated testing frameworks that impact developer workflow for integrating product changes. Seek to identify high level explanations of possible solutions. Describe the pros and cons of each possible solution. Analyze the possible solutions and put forward the best possible solution.

## Acceptance Criteria
- [ ] Possible solutions for enhancing `vets-api` test consistency have been recorded into a discovery document
- [ ] Analysis of each possible solution is recorded in the discovery document
- [ ] The best possible solution has been identified and detailed

**Comment by IGallupSoCo** [comment]
Initial discovery documentation:
https://vfs.atlassian.net/wiki/spaces/PRT/pages/edit-v2/3382312971

**Comment by IGallupSoCo** [comment]
<img width="911" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmh4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcc906cb16056d41913ef592f8494299236df92f/Screenshot%202024-08-20%20at%202.00.09%E2%80%AFPM.png" alt="Screenshot 2024-08-20 at 2.00.09 PM.png" />
<img width="916" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmx4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e03e0d46e96ed581f5694366331de8a41044b3c/Screenshot%202024-08-20%20at%202.00.19%E2%80%AFPM.png" alt="Screenshot 2024-08-20 at 2.00.19 PM.png" />
<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnB4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--064fa190e2296d11de45be49f4a281a4b7830e92/Screenshot%202024-08-20%20at%202.00.42%E2%80%AFPM.png" alt="Screenshot 2024-08-20 at 2.00.42 PM.png" />

**Comment by IGallupSoCo** [comment]
With Steven's assistance, I am beginning to get a sense of what local vets-api testing looks like, and to start collecting results for comparison with CI.

**Comment by IGallupSoCo** [comment]
<img width="470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTk0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--633519062b2e3da14e31fe7e774cb368e72e7e8e/Screenshot%202024-08-21%20at%203.56.51%E2%80%AFPM.png" alt="Screenshot 2024-08-21 at 3.56.51 PM.png" />

**Comment by IGallupSoCo** [comment]
<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekI0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4eb1d431c73f365d5c105c9d5d359c9535bfc124/Screenshot%202024-08-21%20at%203.57.28%E2%80%AFPM.png" alt="Screenshot 2024-08-21 at 3.57.28 PM.png" />

I'm having some trouble comparing my local test results with what I'm finding in CI.

**Comment by IGallupSoCo** [comment]
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWw0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82fe698c023d3ffcef109f91136766138692744d/Screenshot%202024-08-21%20at%204.24.27%E2%80%AFPM.png" alt="Screenshot 2024-08-21 at 4.24.27 PM.png" />

**Comment by IGallupSoCo** [comment]
Binstubs seems to be a strong, consistent solution for local testing when used with the provided Dockerfile.  While the Platform officially supports the use or rspec in native, hybrid, and docker configurations for local vets-api instances, I would be inclined to advocate for Binstubs becoming the gold standard for local testing, as it can run in a "CI" mode and perform the tests in parallel, as they would be performed in our actual CI.

**Comment by IGallupSoCo** [comment]
Unfortunately, my hardware limitations hampered the collection of a meaningful amount of data on local testing times.  That said, I believe that local vets-api testing is in a more stable place, at least as far as VFS teams are concerned.
