### ISSUE TITLE
Skeleton/first-pass QA test cases for NoK/EC edit

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#90522]
### User story

As a Cartography team member, I want create test cases for the Nok/EC edit feature to ensure that all functionality has been tested and is working as expected per requirements

### Notes
- [Use cases for Contact Info](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/use-cases) – address cases are particularly relevant

Possible tasks:
- 

## Acceptance criteria

- Test cases have been created in Testrail

**Comment by wesrowe** [comment]
@allanto-ah, feel free to add details to this ticket.

**Comment by wesrowe** [comment]
@allanto-ah, is this ticket dependent on having a UX design done?

**Comment by allanto-ah** [comment]
@wesrowe no, I can get started without the UX design, but once the UX designs are done, I will refine the test cases more with the actual names and labels

**Comment by wesrowe** [comment]
@allanto-ah, I added to details above a test case folder on GH that Travis shared. Address stuff seems relevant.

**Comment by allanto-ah** [comment]
First-pass QA test cases have been created in [Testrail](https://dsvavsp.testrail.io/index.php?/suites/view/1883&group_by=cases:section_id&group_id=15203&group_order=asc&display_deleted_cases=0). Will refine these once the designs are done
