### ISSUE TITLE
QA Standards - govcio-vfep-codereviewers - Resources for schools

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#90524]
#### VFS team name
govcio-vfep-codereviewers

#### VFS product name
Resources for schools

#### VFS feature name
Convert legacy markdown SCO page into a React app

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
There is no Test Plan attached to the ticket. I realize this product is a legacy conversion and therefore the Test Plan may be the same as the Regression Plan, but if so please explicitly state this.
#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
No Traceability Reports included
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 98.53

- Functions %: 96.55

- Statements %: 98.55

- Branches %: 100

- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by nawar-va** [comment]
The test plan and the regression plan are the same

**Comment by gforbes4** [comment]
The test and development teams are in agreement that the regression tests fully serve the purpose of a test plan in this context.
