### ISSUE TITLE
Link secondary nav "Records" to MR Ph1 app behind feature toggle

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#90521]
### User story

As a Veteran who is in the group of users enabled for Records Ph1, I want the Records item in the nav to take me to the new MR app, so that I can try it out and offer feedback.

### Notes
- 

Possible tasks:
- 

## Acceptance criteria

- "Records" in 2N links to new app, behind roll-out feature toggle
- QA review

**Comment by carlosfelix2** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/88851
