### ISSUE TITLE
Define and Document the Procedures to Perform Load Testing for the 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9052]
## Description
Overall we need to know what the procedures are and when we should perform load testing

## Tasks
-  Establish the need and procedures for load testing and in what environments 
  - Taking into consideration that submission will be on a job
  - Initial interactions might need a `200` response to get started

## Considerations
- Do we need to wait until the 686 is code complete before load testing?
- Concurrency is metric that needs to be checked
  - There could be a burst of up to 100,000 **concurrently** based on comms
- Documentation might exist in platform

## Acceptance Criteria
- [ ] Document in GH what the procedures are for load testing and what the guiding principles are

**Comment by micahchiang** [comment]
README for load testing - https://github.com/department-of-veterans-affairs/devops/blob/master/loadtest/README.md

**Comment by micahchiang** [comment]
Generating User Sessions - https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest/form526

**Comment by micahchiang** [comment]
Form 526 POST load test - https://github.com/department-of-veterans-affairs/devops/blob/master/loadtest/form526/form526_locust.py
