### ISSUE TITLE
Staging Review finding: Invalid URL: non-Veteran-facing page should remain outside of Veteran benefits experience section

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90536]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** govcio-vfep-codereviewers
**Product:** Resources for schools
**Feature:** Convert Legacy Markdown SCO page into a React App

## Findings details
**VA.gov Experience Standard - issue:** [Findability: User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

This tool has a new URL which places it inside the Veteran-facing Education benefits section of the site. The URL should not be changed from the existing URL.

  - Current/live URL: `/school-administrators/`
  - New page URL: `/education/school-administrators/`

If this tool does get permission to receive any new URL, the entry point links for this page will need to be updated. Tagging @mnorthuis for visibility.

## Recommended action

Per OCTO IA lead @mnorthuis please ensure the final URL of the tool matches the current live URL, `va.gov/school-administrators`. If a new URL is approved, please work with CAIA to identify and update entry point links to match the new URL or redirect the old page's URL to point to the new page.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** User flow

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by jsimonVA** [comment]
We are updating our URL to use /school-administrators/. This will be updated prior to our Prod Launch. I spoke with the CMS team and they have confirmed as long as I update the registry.json file we can push our React page with the URL that is currently being used by the Drupal page, and it will then point to the React page.

**Comment by alexisbetz** [comment]
https://jira.devops.va.gov/browse/VEBT-423

**Comment by shiragoodman** [comment]
@alexisbetz we ask that you don't close out the Staging Review finding tickets until the issue is resolved. Putting on the backlog doesn't suffice, so I am reopening this ticket. Thank you. Please feel free to reach out if you have any questions.

**Comment by alexisbetz** [comment]
> @alexisbetz we ask that you don't close out the Staging Review finding tickets until the issue is resolved. Putting on the backlog doesn't suffice, so I am reopening this ticket. Thank you. Please feel free to reach out if you have any questions.

Noted!
