### ISSUE TITLE
Staging Review finding: Breadcrumbs do not accurately represent the tool’s location in the site IA. 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90537]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** govcio-vfep-codereviewers
**Product:** Resources for schools
**Feature:** Convert Legacy Markdown SCO page into a React App

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

> [!NOTE]  
> This issue will be resolved if the tool returns to its original URL outside of the Education section of VA.gov.

The breadcrumbs are currently `VA.gov home > Resources for schools` but the tool is now one level deeper in the site, part of the education section, so the breadcrumbs need to be updated to reflect that there is a parent page for the tool.

<details><summary>Link, screenshot or steps to recreate</summary>

![breacrumbs](https://github.com/user-attachments/assets/14a94a34-3843-486f-abb9-8e3bb00b1777)

</details>

## Recommended action

Two options:

 - Move the tool back to its original URL, as a direct child page of VA.gov home; or
- Update breadcrumbs to accurately reflect the page's hierarchy on VA.gov.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Breadcrumbs ](https://design.va.gov/components/breadcrumbs)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** Navigation

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by alexisbetz** [comment]
Placed in our backlog

**Comment by alexisbetz** [comment]
https://jira.devops.va.gov/browse/VEBT-423

**Comment by shiragoodman** [comment]
@alexisbetz we ask that you don't close out the Staging Review finding tickets until the issue is resolved. Putting on the backlog doesn't suffice, so I am reopening this ticket. Thank you. Please feel free to reach out if you have any questions.

**Comment by alexisbetz** [comment]
Once we launched to prod on 9/17 this issue was resolved.
