### ISSUE TITLE
[FE] Remove Information about Filing Multiple Claims in 1 Day

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#90546]
## Wireframes
[Wireframe](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3748-5781&t=VjPc4WL7j8XnQPIE-4)

## Tasks
- Remove Information about Filing Multiple Claims in 1 Day

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park / @cgednalske I updated the text on the success page. It looks like the text is also supposed to be on an error page, but it feels very duplicative of what is already said at the end of the alert right down to the link and text. Is this really needed? If yes should this text be on every error page?
<img width="194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25d0b2648b85e74288fb0bee27a8dbe0e639bf35/Screenshot%202024-08-19%20at%204.11.25%E2%80%AFPM.png" alt="Screenshot 2024-08-19 at 4.11.25 PM.png" />

**Comment by cgednalske** [comment]
Good call out! UX might have to look at this more. It's definitely repeating some information (the double link is the most jarring part, probably), but it IS different information seeing as in one case it's talking about the appointment in question and using the LoROTA tool or BTSSS, and then later it's talking about a different appointment with BTSSS only. It's probably ok for now, but ya we might need to noodle on how else we can treat either the alert or the following body text  👀

**Comment by benbrasso-agile6** [comment]
Kinda agree. Most of the that second message is captured within the content of the alert. Will wait for @zach-park and @cgednalske to chime in too.

**Comment by cgednalske** [comment]
Agree something should change. Do we need another UX ticket?

**Comment by benbrasso-agile6** [comment]
Maybe go with Brian's solution for now. Release that. Then we can work on an iteration in a sep ticket.

**Comment by cgednalske** [comment]
Is the solution to leave out the body text and just have the alert for now until we can work on it? If so, I'm on board 👍

**Comment by benbrasso-agile6** [comment]
Yeah. Sounds good to me.

**Comment by brianseek** [comment]
thanks for hashing that out! I merged the success page update and its ready to validate locally, or with the following screenshot:
<img width="254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnB3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a68d8fa5e8a583ef8adafff6aa5c641540e9878a/success-change.png" alt="success-change.png" />

**Comment by brianseek** [comment]
@zach-park @cgednalske @benbrasso-agile6 ^

**Comment by zach-park** [comment]
Looks nice. @cgednalske @benbrasso-agile6

**Comment by brianseek** [comment]
closing with validation, thanks all!
