### ISSUE TITLE
Staging Review finding: Links should have descriptive language

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90544]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** govcio-vfep-codereviewers
**Product:** Resources for schools
**Feature:** Convert Legacy Markdown SCO page into a React App

## Findings details
**VA.gov Experience Standard - issue:** [User is uncertain where a button or link leads.](https://design.va.gov/about/experience-standards/#user-knows-where-a-button-or-link-leads)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

Many of the links on the page do not describe both the purpose of the link and the destination. The VA content style guide recommends that link text is descriptive and natural, and describes both the purpose and destination.

## Recommended action

Consider changing link text to describe purpose and destination, for example "School Certifying Official Handbook" could be changed to "Access the School Certifying Official Handbook".

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Links](https://design.va.gov/content-style-guide/links)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by shiragoodman** [comment]
@alexisbetz we ask that you don't close out the Staging Review finding tickets until the issue is resolved. Putting on the backlog doesn't suffice, so I am reopening this ticket. Thank you. Please feel free to reach out if you have any questions.

**Comment by alexisbetz** [comment]
> @alexisbetz we ask that you don't close out the Staging Review finding tickets until the issue is resolved. Putting on the backlog doesn't suffice, so I am reopening this ticket. Thank you. Please feel free to reach out if you have any questions.

Noted, thanks Shira!
