### ISSUE TITLE
HLR | Staging Review - Coverage for References and Summary (defects) Report

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#90554]
## Traceability Reports

*Not a launch blocker*

Traceability Reports have two components:

**Coverage for References:** the percent of the initiative’s user stories are covered by tests in the Test Plan. This can be reported as a chart, a table, or simply a number.

**Summary(Defects):** demonstrate what percent of defects uncovered during testing were uncovered by executing tests in the Test Plan as well as which defects are resolved or outstanding. This can be reported as a chart, a table, or simply a number.

Traceability Reports can be automatically generated in TestRail after executing tests in TestRail.

Example: You can create a Traceability Report by clicking on the appropriate link in the Create Report panel on the Reports tab of TestRail. For an example of a Coverage for References report, [see this Coverage Report for Search](https://dsvavsp.testrail.io/index.php?/reports/view/12). For an example of a Summary (Defects) report, [see this Summary (Defects) report for Search](https://dsvavsp.testrail.io/index.php?/reports/view/14).

Note: VFS Teams not using TestRail are still expected to share Traceability Reports at the Collaboration Cycle Staging Review.

## Tasks

- [x] Generate traceability report after executing tasks in TestRail

**Comment by davidakennedy** [comment]
Adding the report.

[testrail-report-956.pdf](https://github.com/user-attachments/files/16948189/testrail-report-956.pdf)
