### ISSUE TITLE
Fix incorrect link to CAIA intake form

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#90634]
### Description

The intake form link at the bottom of the page [https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request)   
  
currently links to (perhaps an older version but now) a blank GH issue template:   
`https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=strelichl%2CNaomiPMC&labels=sitewide+CAIA&projects=&template`**`=sitewide-CAIA-intake-form.md`**`&title=%5BCAIA+Intake%5D+%3CTeam+Name%3E%3A+%3CInitiative+Name%3E`  
  
but it (seems like it) should link to the current GH issue template:   
`https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=strelichl%2CNaomiPMC&labels=sitewide+CAIA&projects=&template`**`=CAIA-intake-form.md`**`&title=%5BCAIA+Intake%5D+%3CTeam+Name%3E%3A+%3CInitiative+Name%3E`

### Relevant URLs

[https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) 

### Which type of team are you on? (Platform team, VFS team, or Leadership) 

VFS team

**Comment by taylojill** [comment]
Hi @claytonzook - thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Per CAIA team, [the link should be this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=strelichl%2CNaomiPMC&labels=sitewide+CAIA&projects=&template=CAIA-intake-form.md&title=%5BCAIA+Intake%5D+%3CTeam+Name%3E%3A+%3CInitiative+Name%3E)

**Comment by jknipes** [comment]
work is being done in [90767](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90767)

**Comment by taylojill** [comment]
Linked updated, page date stamped, ready to publish.
