### ISSUE TITLE
Environments page should state explicitly that only production systems can connect to systems containing real PII / PHI

### ISSUE THREAD

**Issue by JonathanKamensDVA** [department-of-veterans-affairs/va.gov-team#90641]
### Description

We've had several privacy incidents involving non-production environments being connected to outside systems that contain real PII and/or PHI.

Note that "outside systems that contain real PII and/or PHI" is not, as you might expect, limited to production systems, because while we at VA.gov don't put any real PII/PHI in non-production environments, there are other teams within VA that have "pre-prod" environments that are allowed to contain real PII/PHI.

To make our policy clear and decrease the likelihood of similar incidents in the future, we would like the [environments page](https://depo-platform-documentation.scrollhelp.site/developer-docs/environments) to be updated to state explicitly that as a matter of policy no non-production environment may be interconnected with an outside system that contains real PII/PHI.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/environments

### Which type of team are you on? (Platform team, VFS team, or Leadership)

Leadership.

**Comment by taylojill** [comment]
Hi @JonathanKamensDVA - thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@JonathanKamensDVA thank you for bringing this to our attention. 

Based on the feedback you provided, would you suggest we put an "alert box" at the top of the page with the text
`as a matter of policy no non-production environment may be interconnected with an outside system that contains real PII/PHI.`?

If the page update requires additional editing, we ask that you please fill out this request instead:
[Documentation Support Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=documentation-support&template=documentation-support-request.yml&title=Documentation+support)

Thanks and let us know if you have any questions!

**Comment by JonathanKamensDVA** [comment]
Sure, that would be a reasonable solution to this ticket as far as I'm concerned. Thanks.
