### ISSUE TITLE
[Datadog] Create Monitor for VA.gov HTTP Headers

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#90644]
# Description
Create a monitor (or monitors) for checking the presence of required HTTP response headers while navigating to https://va.gov. Alerts should go to the DSVA Slack's #oncall channel, at a minimum

# Notes
- In response to https://github.com/department-of-veterans-affairs/va.gov-team/issues/90377

# Acceptance Criteria
- [ ] `X-frame-options` header is monitored for https://va.gov
- [ ] `Strict-Transport-Security` header is monitored for https://va.gov
- [ ] `Content-Security-Policy-Report-Only` header is monitored for https://va.gov

**Comment by Efe-Oddball** [comment]
Completed yaml files for all 3  monitors. Next step is to test functionality.

**Comment by Efe-Oddball** [comment]
I have built and tested monitors functionality. I just need to get some confirmation before deployment across board

**Comment by Efe-Oddball** [comment]
PR has been created for this. Once approved, PR will be merged and ticket will be resolved

**Comment by Efe-Oddball** [comment]
This ticket is complete. Moving ticket to a resolved state
