### ISSUE TITLE
Include ICN as patient identifier when making requests to Appointment resource

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#9064]
The appointment resource appears to need a patient identifier passed to it to pull appointments for the right person. The FE doesn't have the ICN, so this would need to be appended on the backend.

Should verify with Brad Crosby that this is how we're expected to fetch Appointments long term before working on this.

Example Appointment request:

```
https://veteran.apps-staging.va.gov/vsp/v1/Appointment?patient:Patient.identifier=1012845331V153043&date=ge2020-05-01T07:00:00Z&date=lt2020-08-31T17:00:00Z&_include=Appointment:location
```

**Comment by jbalboni** [comment]
FYI @saneshark @kreek

**Comment by laurenernest** [comment]
No longer needed. New tickets will be created for any EAS work.
