### ISSUE TITLE
[Analytics] Add Healthcare data to V1 Product Health MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#907]
## User Story
As a Healthcare decision maker, I need Google Analytics for my forms on the Product Health MVP so I can see my product's health at a glance.

## Goal
Add HCA Google Analytics data to V1 of the product health MVP.

## Acceptance Criteria
- [x] Add Google Analytics 1010EZ HCA data to the product health MVP
- [ ] _Stretch_: Automate Claims data to product health MVP

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

CC: @amycesal for design verification.

**Comment by nedierecel** [comment]
@joanneesteban @jonwehausen 

Here are the Health Care application (`hca-submission`) events to track: https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=hca--submission&explorer-table.rowCount=25

- `hca--submission`
- `hca--submission-successful`
- `hca--submission-failed`
- `hca--submission-failed-client` - We need clarity if this is distinct from the above event. I will try to hunt down an answer. 

Goal conversion: https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goal-funnel/a50123418w177519031p184624291/_.goalOption=13/

FYI - It appears there are about 10% of sessions where an applicant is directly accessing the confirmation page in another session. I will get back in touch with Lisa and Samara to research this. ![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/7c5e24fe-2f57-4d17-8fd0-4c30f8f14e23)

**Comment by nedierecel** [comment]
@joanneesteban @jonwehausen I've added the Health Care Application from the Health Care Modernized View. My next step is to validate.
