### ISSUE TITLE
Synthesize forms documentation feedback

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#9070]
Utilize feedback from our VFS\VSA users and stakeholders to identify documentation gaps and ambiguity.

We have a great deal of documentation created by VSA teams that we can use for updating\creating better forms documentation. 
[VSA Created Forms Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/engineering/forms-system)

**Comment by meganhkelley** [comment]
@caw310 passing to design system team

**Comment by micahchiang** [comment]
Migration is complete, closing this ticket.
