### ISSUE TITLE
[CAIA Intake] Disability Benefits Experience Team 2: 0781 Failure Emails

### ISSUE THREAD

**Issue by juliepedtke** [department-of-veterans-affairs/va.gov-team#90704]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: `Disability Benefits Experience Team 2 (Carbs)`
- **OCTO product owner:** `Emily Theis`
- **Product name:** `526 Form`
- **Product manager:**  `Lisa Capaccioli`
- **Slack channel:** `#benefits-disability`
- **Dedicated content writer on your team (if you have one):** n/a
- **Dedicated a11y specialist on your team (if you have one):** n/a
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [x] Something else:  `Creating a Veteran-facing email to notify them in the event of a backend failure that requires them to take action`

### What's the nature of your initiative and desired outcomes?

`Earlier this year we created emails to notify Veterans of possible backend failures with file uploads and ancillary form generation. Laura Willwerth worked with our team on the content. Since then, we've learned new information that has led us to adjust our approach and combine two of the emails into one.`

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

`We're drafting the new email content (it's currently in progress and will be ready in a few days). Our devs will be ready to launch these soon.`

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [x]  Yes
- [ ]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `n/a`
- **What is the name of your engineer who will build the React widget?** `na/ it's a VA Notify email`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Figma file of previous emails (new design will be in the same file shortly)](https://www.figma.com/design/TZ23k4X5tnh3lFlehYER3f/526-Post-Submission-Upload-Failure-Notification?node-id=59-16440&t=7UV0nSLphqpjjXvt-0)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90843
```

**Comment by aprocik1** [comment]
@juliepedtke, thanks for submitting this intake ticket. I'll be the content specialist working on this with you. Can you specify the screen(s) you'd like me to review in your [Figma file](https://www.figma.com/design/TZ23k4X5tnh3lFlehYER3f/526-Post-Submission-Upload-Failure-Notification?node-id=59-16440&t=7UV0nSLphqpjjXvt-0)? And are those screens ready for my review now? If not, that's okay! When they're ready, you can tag me in a comment on this ticket and I'll return to this work.

**Comment by juliepedtke** [comment]
Hi @aprocik1 ! Excited to work with you on this. One new screen should be ready for you by EOD, I'll comment back with a link when we have it.

**Comment by juliepedtke** [comment]
Hi @aprocik1 - here's the updated screen for your review, labeled Combined 0781 - for CAIA review.

**Comment by juliepedtke** [comment]
And once the digital form is updated to only submit the new 0781, the email would be updated as well, removing the paragraph about the change in the two forms.

**Comment by aprocik1** [comment]
@juliepedtke, thanks for this! I was involved in the 0781/a work, so I'm familiar with these changes. I just left you a [comment in your Figma file](https://www.figma.com/design/TZ23k4X5tnh3lFlehYER3f?node-id=459-82694#919725223). Let me know what you think.

**Comment by juliepedtke** [comment]
Looks like we got this resolved via Figma comments - thanks for your review!
