### ISSUE TITLE
Join appointment link fails if URL attribute is absent

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#90713]
## Summary
_Describe what went wrong_

When a join appointment button is available, it's possible that it doesn't have an associated URL.  This happens when the frontend code is looking for a `url` attribute in under `videoData` and it's not present.

## Specs
- Device: MacBook Pro
- Browser: Chrome

## Steps to Reproduce
**Test User:** 

1. Request a test user be set up who will have an active Join Appointment link setup during testing. That link should be mis-configured so there is no URL attribute
2. Click the link - nothing happens
3. Right-click the link - there is no option to open the link in a new tab.

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

The link displays when there's no 'url' attribute in the data.

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

In place of the link, display an error message using the https://design.va.gov/storybook/?path=/docs/uswds-va-alert--error component:

```
<h2> We're sorry, we couldn't load the link to join your appointment

<p> 
     Please contact your facility for help joining this appointment.

     Main phone: [Main phone number link]
<p>
```

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/90713?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by jenniemc** [comment]
@outerpress , you can see the screenshot alert on the PR https://github.com/department-of-veterans-affairs/vets-website/pull/31454

Let me know if this works for validation.

**Comment by outerpress** [comment]
@jenniemc walked me through the changes on her local machine and they look good, fyi @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.

**Comment by jenniemc** [comment]
@ldelacosta @outerpress  , I'm re-opening this ticket to address an accessibility concern Peter had brought up.

**Comment by jenniemc** [comment]
@outerpress  Per our conversation, I'm changing the default alert message h2 heading to h3

**Comment by jenniemc** [comment]
@outerpress @ldelacosta , this ticket is ready for validation 
This is screenshot that shows h3 heading for accessibility
![Screenshot 2024-08-20 at 10 10 25 AM](https://github.com/user-attachments/assets/a2d91385-f1d5-4e3b-8432-cb3dc9991798)

**Comment by outerpress** [comment]
Looks good, thanks @jenniemc !

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
