### ISSUE TITLE
S60 [Awe-Gust Zoomies  🐈 💨]

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#90716]
# Sprint Goals

| Previous Sprint | Next Sprint |
| :--------------  | ----------:  |
| ◀️  #89634        | #91502 ▶️        |

**Scrum Hero**: @dfong-adh    

### Priority 1: Remediate historical failures ([WIP epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80241))

**Send historical failure data for review to determine which claims need to be remediated.**
- (Place holder as we wait for a response)

### Priority 2: Submission Stability and Storage ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293))

**Store Submissions**
- #84332 
- #89790 
- #90103
- #91323
- #91324
- #91326
- #91327

### Priority 3: HLR Form Version Update  [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82220)
**QA HLR form and prepare for collab cycle.**
- #88057
- #89863 
- #90356 
- #90552 
- #90554 
- #90553 
- #90702 

### Priority 4: SC Form Version Updates [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82219)
**Mockup SC and prepare for research.**
- #87098
- #89502 
- #90568

### Bug/Engineering Backlog

- #88356
- #88513
- #90112
- #66874
- #90344 
- #90663 
- #91286

---

## Blocked Items

- #81507
   - Waiting for Lighthouse to release [new endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81507#issuecomment-2115701294) to capture generated PDFs
- #83324
  - Blocked until after the form redesigns 
---

## Team Capacity

**Outages:**
- 8/16 - @skylerschain 
- 8/21 - @anniebtran 
- 8/26-8/30 - @eileen-coforma 

## Reference documentation

- [Q3 Roadmap Prioritization](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/product%20management/Prioritization/DR%20Prioritization%20Scoring%20-%20April%202024.xlsx?d=wb661cf77374d4321969f619e845cabbd&csf=1&web=1&e=GIwNAH)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)

**Comment by Mottie** [comment]
Added #91286 to backlog
