### ISSUE TITLE
Spike: Add pega maintenance window functionality to IVC forms

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#90752]
See [this thread on DSVA](https://dsva.slack.com/archives/C068Y3ZFKNJ/p1723670255559939) from Premal.

Basic criteria (need to flesh this out)
- Create a PEGA service in PagerDuty
- Wrap all IVC forms in the `DowntimeNotification` component
- Subscribe to PEGA, login providers, and VA Profile maintenance windows via the `DowntimeNotification` component

**Comment by michaelclement** [comment]
- [ ] Make the PEGA service in Pager Duty (staging environment)
- [ ] Vets-api pull request to add PEGA to maintenance list
- [ ] Vsp-infra-application-manifests pull request to add PEGA to maintenance list (staging environment)
- [ ] Create React downtime wrapper on the following forms:
  - [ ] 10-10d
  - [ ] 10-7959a
  - [ ] 10-7959c
  - [ ] 10-7959f-1
  - [ ] 10-7959f-2

**Comment by michaelclement** [comment]
The wrappers have been added to all IVC apps, waiting on platform approval so they can go to staging. Once on staging, I'll create a maintenance window for the PEGA service and verify that all applications respond appropriately. At that point we should be good to close this ticket. Will update later.

**Comment by michaelclement** [comment]
The wrappers have been added to all IVC apps, waiting on platform approval so they can go to staging. Once on staging, I'll create a maintenance window for the PEGA service and verify that all applications respond appropriately. At that point we should be good to close this ticket. Will update later.

**Comment by baltes** [comment]
@michaelclement thanks very much for all of this. Could you also add a short procedure doc to github for a non-eng audience (or at least teamwide) for steps to take when we know planned downtime is coming? Let me know if that needs clarification.

**Comment by michaelclement** [comment]
@baltes Got it! New documentation is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/c91c83a6ca422cc04069e9c7e61d41e01ca79012/src/applications/ivc-champva/README.md#scheduling-maintenance-windows-for-external-backend-service-pega) - does this fit what you had in mind? Thanks!

**Comment by michaelclement** [comment]
Also, a screenshot here of the maintenance window working on staging:

<img width="1102" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmx3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--643efca06385ec6a8253433e776091eab7bd9f28/maintenance.png" alt="maintenance.png" />
