### ISSUE TITLE
Daily Qualitative Data Request - Appointments Team

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#90763]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

08-12-2024

### Date Range End

09-30-2024

### Product Name(s)

Appointments (formerly VAOS)

### Product Description

A tool for Veterans to schedule and manage their appointments online.

### Survey URL(s), key term(s), case category or type

Everything under https://www.va.gov/health-care/schedule-view-va-appointments/

Our team is requesting a daily file to be sent to us. If you have any questions, please reach out via Slack or email. Thank you. 

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

Leah.DeLaCosta@va.gov 

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. I will share them daily.

**Comment by ldelacosta** [comment]
@newworld2616  - I'm missing 8/18 Medallia feedback. Would you be able to send it when you have a chance? Thanks.

**Comment by newworld2616** [comment]
Hello, @ldelacosta, there was no data available for 8/18. Let me know if you have any questions. Thank you.

**Comment by ldelacosta** [comment]
Hi @newworld2616 - I'll be OOO starting tomorrow and will return 9/3. Would you be able to send one file on 9/3 with the feedback from 8/28 to 9/2? Let me know when you have a chance. Thanks!

**Comment by newworld2616** [comment]
Hi, sure, I will send the file on 9/3.

**Comment by ldelacosta** [comment]
Thanks @newworld2616 . I have a question, I've missed to request the comments under and including these URLS and all of their sub-URLs for:

- https://www.va.gov/health-care/schedule-view-va-appointments/
- https://www.va.gov/my-health/appointments

Would it be easier if I created a new ticket and we can close this one out?

**Comment by newworld2616** [comment]
No problem. Yea, new ticket will be great.

**Comment by ldelacosta** [comment]
I have submitted a new ticket [#92051](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92051). Closing out the ticket.
