### ISSUE TITLE
AWS access for Louis Fettet

### ISSUE THREAD

**Issue by LouisFettet** [department-of-veterans-affairs/va.gov-team#90777]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Coforma - Jeff Langworthy

### Your Name

Louis Fettet

### Your Email

louis@adhocteam.us

### Team, Role, and Company of the target individual

Benefits Management Tools Team, Software Engineer, Ad Hoc (Coforma)

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Amy Lai, amy.lai2@va.gov

### Desired AWS Access

Please copy Peri-Ann McLaren (@pmclaren19)'s permissions. Her access request was #75436.

### Access Expiration

November 1, 2024

### E-QIP Transmittal Confirmation

<img width="984" alt="Screenshot 2024-08-15 at 10 18 46 AM" src="https://github.com/user-attachments/assets/d2fb1629-2f72-41ef-ab67-3e67cc277119">

### Additional Notes

COR Name: Keith Riley

I recently joined the Benefits Management Tools Team. I need access to any resources necessary to develop features, fix bugs, and conduct investigations on the website and Vets API. Thanks!

**Note**: I previously (partially) onboarded to the [Octonaut Team](https://www.va.gov/atlas/product_directory/teams/245) but have made a note in my onboarding ticket (#82593) requesting that I be moved to the Benefits Management Tools Team.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Hi Louis! Could you tell me who a couple of your teammates are, so that I can give you similar access?

**Comment by flooose** [comment]
Hi @LouisFettet! I was unable to find you in our [VFS Roster](https://www.va.gov/atlas/product_directory/team_members?filter_by=last_name&filter_type=includes&filter=fettet&commit=Filter). Please complete [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) so that I can proceed with this request.

**Comment by LouisFettet** [comment]
@flooose I'm listed in Atlas here: https://www.va.gov/atlas/product_directory/team_members/775

**Comment by flooose** [comment]
Thank you! Searching by last name didn't yield anything. I'v addressed this with my team, but I can move forward with this now.
