### ISSUE TITLE
Spike:  Additional ideas for pre-populating

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#90771]
## Issue Description
As a spike, evaluate what additional fields can be pre-populated from data sources already available within vets-api.  

For example,
app/services/bgs/dependent_service.rb

---
## Tasks
- [ ] - If additional fields/sources are found that make sense, present to product for approval and next steps.

**Comment by TaiWilkin** [comment]
A challenge for most prefill sources I found is a lack of local mock data. In addition, it will be challenging to find Staging users with appropriate mocked data. 

## VAProfile / Vet360

### VA Medical Centers
Swagger: https://qa.vaprofile.va.gov:7005/profile-service/swagger-ui/index.html?urls.primaryName=ProfileServiceV3
Under health benefit bio -> health care -> visit summaries
Challenges: health benefit bio isn't mocked locally

### Marital Status
Swagger: https://qa.vaprofile.va.gov:7005/profile-service/swagger-ui/index.html?urls.primaryName=ProfileServiceV3
Under demographics -> maritalStatus
Challenges: demographics is mocked locally, but no examples of marital status currently

## User

Several User properties are already used in prefill. However, many of the fields are filled only when requested and use third-party services (for example, MPI, BGS, etc). 

### Dependents and/or Marriages
User.relationships
This is filled using MPI with BGS as a backup. 
Challenges: As far as I can tell, there are no users with mocked relationships locally. 

## EZR
See config/form_profile_mappings/10-10EZR.yml and app/models/form_profiles/va_1010ezr.rb
This is filled using data from HCA. It appears that it includes spouse data, medicare data, and possibly dependents data. 
Challenges: there doesn't appear to be any local HCA mocks

## BGS

### File number
`BGS::People::Request.new.find_person_by_participant_id(user: @user).file_number`
It appears that there is mock data for some users for this endpoint. In vets-api-mockdata: `bgs/person_web_service/find_person_by_ptcpnt_id/796104437.json`, `bgs/person_web_service/find_person_by_ptcpnt_id/796148937.json`, `bgs/person_web_service/find_person_by_ptcpnt_id/796330625.json`

## PPIU

### Direct Deposit
see `#initialize_payment_information` in `app/models/form_profiles/va_526ez.rb`
Appears to be mocked here: `evss/ppiu/payment_information.yml`

@mjknight50

**Comment by matt4su** [comment]
The next step is to ask our VBA colleagues for prioritization feedback on these data elements, tentatively scheduled for 9/10 VBA meeting.
