### ISSUE TITLE
10-10d updates to marriage flow

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#90786]
As a CHAMPVA applicant, I need correct guidance on my supporting docs based on whether my sponsor is still living.

Acceptance criteria
- Content is updated for applicants whose sponsor has died to reflect additional documentation needs
- Documentation requests are removed for applicants whose sponsor and spouse is living so that only marriage date is requested

[link to the marriage flow/content if the sponsor died](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=2097-7995&t=uh7KwhdyRYkUX7nI-4)
[link to the flow if the sponsor is alive](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=2097-9174&t=uh7KwhdyRYkUX7nI-4)

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31439). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes @jamiefiore This has been merged in and should be visible on staging shortly. Thanks!

**Comment by michaelclement** [comment]
[Link to the form on staging](staging.va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d)
