### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by mayacarrolluxa6** [department-of-veterans-affairs/va.gov-team#90781]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2020

### Date Range End

08-15-2024

### Product Name(s)

526EZ Disability Compensation Form

### Product Description

Veterans use VA Form 21-526EZ when you want to apply for VA disability compensation  and related benefits.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/disability/file-disability-claim-form-21-526ez/

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

maya.carroll@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
