### ISSUE TITLE
Audit BE code for PII leaks

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#90799]
https://dsva.slack.com/archives/CPE4AJ6Q0/p1723741842795809?thread_ts=1723670371.266369&cid=CPE4AJ6Q0

In light of our PII issue, we were advised to look into any other possible PII leaks in logging. This ticket exists to document going through our code and ensuring we are not printing PII to datadog.

Deliverable will be a spreadsheet of logging and description of contents

**Comment by HeatherRienks** [comment]
@digitaldrk - any additional information you can provide would be great.

**Comment by digitaldrk** [comment]
@HeatherRienks Added, let me know if we need more info

**Comment by digitaldrk** [comment]
[logging_audit.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek9kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9b94fe8f26da6ed9a0c4e03f2f09fbae8792914/logging_audit.xlsx)
