### ISSUE TITLE
Sidekiq Admin UI access for [Sanja Bajovic]

### ISSUE THREAD

**Issue by sanjabaj2** [department-of-veterans-affairs/va.gov-team#90795]
### Your Name

Sanja Bajovic

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@sanjabaj2

### Team, Role, and Company of the target individual

Benefits porfvolio, VA Engineering lead

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [X] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I need access to troubleshoot submission issues and assist contracting team with managing orphan sidekiq jobs. 
[Initial background check complete.pdf](https://github.com/user-attachments/files/16627601/Initial.background.check.complete.pdf)
sidekiq jobs.

**Comment by davidpetras** [comment]
Hi @sanjabaj2 you have been granted access to `dev, staging, sandbox, and production` with access to Production limited to 6 months, expiring 02/17/25.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by sanjabaj2** [comment]
Please extend my access for the next allowable term. Thank you.

**Comment by AnthonyWFlowers** [comment]
@sanjabaj2  your Production access has been extended for 6 months, expiring 08/03/25.

Please set a reminder for yourself to return to this Issue, reopen it, and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by sanjabaj2** [comment]
Can you please extend production access.

**Comment by AnthonyWFlowers** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their access?

**Comment by AnthonyWFlowers** [comment]
@sanjabaj2  your Production access has been extended for 6 months, expiring 2/1/26.

Please set a reminder for yourself to return to this Issue, reopen it, and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Greetings @va-albers, could you provide some insight on this? Is it similar to vets-api prod access where a federal user would retain access, or does it still follow the six-month access renewal cadence? Thank you!
