### ISSUE TITLE
Adding Caroline J. and Edward K. to Google Analytics

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#908]
# Analytics Access Request

## User Email Address
_Provide email address(es) for user(s) requesting access to the Insights team on the DSVA Slack channel: #VSP-Analytics. Please also link this issue. If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead"._

## Access Requirements
VA.gov, so thinking WBC?

## Date Required
Not urgent, but as soon as possible.

## Product Team / External Team / VA Office
External office:

>Office of Information and Technology
Enterprise Project Management Division
Benefits, Appeals & Memorial Affairs Portfolio

**Comment by nedierecel** [comment]
@batemapf Caroline has been added, and I will add Edward K. when his Google account is created. Thanks!

**Comment by nedierecel** [comment]
@batemapf Edward K. was provided with access this afternoon.
