### ISSUE TITLE
[Congressional] V12052547 Due 9/17/24 (Sen. Blumenthal)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#90805]
## Issue Description
Veteran created a Login.gov account on May 7, 2024. After uploading their driver's license, it never prompted them to the next step. They tried to get help from the VA by phone, but no one picked them up. Veterans are looking for assistance in completing this process.

https://app.slack.com/client/T03FECE8V?selected_team_id=T1ZD0UBMZ

---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
8/23: Sent email to user advising the matter must be handled by the corresponding CSP (ID.me/Login.gov) along with ID guidance and contact information.
Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
9/3 Update: Rachel H. from Login.gov reached back out to us and advised the Veteran reached out on 8/28/24 to the Login.gov team and was provided the information on how to search for a participating office.  

9/3: Reached back out to Veteran via email to understand if the issue has been resolved.  Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
9/4/24:  Veteran responded back advising that the information provided from Login.gov was previously provided and not helpful.

Veteran stated that the post offices provided to him knows nothing about the verification process.

Sent these details to my POCs at Login.gov for review.  Advised the Veteran and awaiting a response from Login.gov.

**Comment by Kimberley2023-CSM** [comment]
Update: 9/9/2024 - Veteran emailed back advising the issue has been resolved and he was able to verify his identity at his local Post Office.
:task_done:
