### ISSUE TITLE
IA Request for "Personalized Career Planning and Guidance (CH36)"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9082]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/prototyping, prior to moving to development

## Required Inputs:
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling)
- [Link to userflow](https://xd.adobe.com/view/f2e4cdec-1fa1-42ab-5cbf-e2a3c74c6663-84d5/screen/f991a1c5-51c6-4a4e-8d90-4357cef48c8f/Chapter-36-User-Paths-1), [mockups](https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/) and [prototype](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084/simulate/sitemap)
- [Link to research readout/results](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/ch36-user-flows.md) _Not conducting conventional research sessions_
- Link to [research history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list ~as applicable~
- [Link to or attach final content including H1s (if separate from prototype/mockup)](https://www.va.gov/careers-employment/education-and-career-counseling/)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content
education
career
counseling
personalized 
planning
guidance
chapter 36
CH36
VRE
TED

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure:
https://xd.adobe.com/view/f2e4cdec-1fa1-42ab-5cbf-e2a3c74c6663-84d5/screen/f991a1c5-51c6-4a4e-8d90-4357cef48c8f/Chapter-36-User-Paths-1

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale
**Current static landing page:** https://www.va.gov/careers-employment/education-and-career-counseling/
**Start application:**  https://www.va.gov/careers-employment/education-and-career-counseling/apply

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.
https://www.va.gov/careers-employment/

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?
These programs are all very closely related: 
CH31 ([Vocational Rehabilitation and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/))
CH33 ([Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/))
CH36 ([Personalized Career Planning and Guidance`*`](https://www.va.gov/careers-employment/education-and-career-counseling/))
`*` _"Educational and Career Counseling" name is being updated to "Personalized Career Planning and Guidance" by Oct 2020 once taken over by the TED Office_

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?
Probably the landing page to some degree: https://www.va.gov/careers-employment/education-and-career-counseling/

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by jason-gcio** [comment]
@mnorthuis - I think Jim (@sporeboy) is going to be taking this to Peggy pretty soon.  Just wanted to check in on this and let you know that the latest prototype is in place above.

**Comment by jason-gcio** [comment]
@mnorthuis - Hey, just wanted to touch base on this...I think we are about ready for this.  I have CH31 pretty much ready to go as well.  I think you mentioned these might be somewhat related from an IA standpoint?

**Comment by mnorthuis** [comment]
@jason-gcio So sorry for the delay!  I will get to work on this and get back to you soon.

**Comment by jason-gcio** [comment]
@mnorthuis - no worries at all! Ping me if you want to chat on this stuff :)

**Comment by mnorthuis** [comment]
Draft IA is posted for your review. I still have some outstanding items to work through.
- discuss wizard flows and placement
- discuss entry points and content strategy with PW team
- content sync with Peggy and PW

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt36.md

**Comment by mnorthuis** [comment]
Update:
Wizard flow added to IA work - decision was made that the wizard for the Chapt 36 and Chapt 31 forms will be independent of one another - if a user is referred to the other program, they will need to complete the wizard on that form as well. 

Had sync with Peggy and PW team on static page and wizard. Outcomes of that will be provided in individual content work streams and did not impact IA recommendations. 

I do still need to review entry points with the PW team and plan to do that within the next couple of days and this work will be finalized at that time.  

cc @peggygannon @DanielleSoCompany

**Comment by mnorthuis** [comment]
@jason-gcio IA info is finalized. Feel free to reach out with any questions or if you want to walk through the information.  You are welcome to close this issue, all IA info is documented in github:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt36.md

cc @bethpottsVADEPO URLs, breadcrumbs and entry points (nav links) are available in the IA doc above.

**Comment by shiragoodman** [comment]
@jason-gcio can this be closed out?
