### ISSUE TITLE
Stamp country from addresses onto 10-10d

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#90849]
As a 10-10d applicants, I need all of the addresses that I enter included on my submitted form.

### Acceptance criteria
Given a 10-10d application
- When the sponsor address is entered in the digital form
   - Then the country code corresponding to the country from the sponsor address in stamped next to the ZIP code on the PDF
- When any applicant address is entered in the digital form
   - Then the country code corresponding to the country from each applicant address in stamped next to the ZIP code on the PDF
- When a signer address is entered in the digital form
   - Then the country code corresponding to the country from the signer's address in stamped BELOW the ZIP code on the PDF so that the phone number is readable
 
All instances of the country code are stamped in a font and size similar to the rest of the text populated in the form.

Any subsequent PDFs due to more than three applicants follow the same patterns as above.

**Comment by baltes** [comment]
@cloudmagic80 Can you pick this one up when you have bandwidth? I'd like to make sure we get it covered in the current sprint.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/18158/files

**Comment by cloudmagic80** [comment]
<img width="784" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMStBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b402534ffa0e93076224caa3ae3649b382d650a/Screenshot%202024-08-22%20at%2011.11.31%20PM.png" alt="Screenshot 2024-08-22 at 11.11.31 PM.png" />

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/18158
