### ISSUE TITLE
IA Request for "Vocational Rehabilitation and Employment (CH31)" 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9086]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31)
- `TODO: Link to or attach prototype or mockups`
- [Link to research readout/results](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design/ch31-user-flows.md)
- Link to [research history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list ~~as applicable~~
- [Link to or attach final content including H1s (if separate from prototype/mockup)](https://www.va.gov/careers-employment/vocational-rehabilitation/)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content
vocational
rehabilitation
employment
VRE
work
services
benefits
services

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure
https://xd.adobe.com/view/397eb9d2-4b41-4e8c-6d56-b47ae93c54f1-4f4f/screen/f991a1c5-51c6-4a4e-8d90-4357cef48c8f/Chapter-31-User-Paths-1

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale
**Static landing page:** https://www.va.gov/careers-employment/vocational-rehabilitation/
**Start application:** https://www.va.gov/careers-employment/vocational-rehabilitation/apply

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.
https://www.va.gov/careers-employment/

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?
These programs are all very closely related: 
CH31 ([Vocational Rehabilitation and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/))
CH33 ([Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/))
CH36 ([Personalized Career Planning and Guidance`*`](https://www.va.gov/careers-employment/education-and-career-counseling/))
`*` _"Educational and Career Counseling" name is being updated to "Personalized Career Planning and Guidance" by Oct 2020 once taken over by the TED Office_

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?
Maybe this one? https://www.va.gov/careers-employment/

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by jason-gcio** [comment]
@mnorthuis - I am sure you know this but just a heads up, the VRE folks have changed the name of this to be Veteran Readiness and Employment, not Vocational Rehabilitation and Employment.  I updated our thoughts on what we think this url would eventually be:
**Static landing page:** https://www.va.gov/careers-employment/veteran-readiness/
**Start application:** https://www.va.gov/careers-employment/veteran-readiness/apply

Is that ok?

**Comment by mnorthuis** [comment]
@jason-gcio We already made all content changes with regards to the program name change and discussed the URLs with the stakeholders.  It is our standard to not brand the URL, and to keep it as a description of what the the benefit is (i.e. vocational rehab) - if they started branding disability compensation as a benefit package, we would keep the benefit hub labeled as "disability", this is what Veterans understand and how they talk about it.  Stakeholders agreed to this, so the URLs in my IA should not change.   We did create a vanity URL for them to use `www.va.gov/vre` for easy communication.

**Comment by jason-gcio** [comment]
Ah ok great!  Thanks very much.
I don't think I have seen that recommendation or it's quite possible I missed it...

I want to make sure we get these into the right url

**Comment by mnorthuis** [comment]
Draft IA is posted for your review.  I still have some outstanding items to work through. 
- clarification on form 28-0588 vs 28-1990
- discuss wizard flows and placement
- discuss entry points and content strategy with PW team

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt31.md

**Comment by mnorthuis** [comment]
Updates:
- wrt 0588, still waiting on whether we need to accommodate this form. Sent follow up to Beth Potts
- wizard placement has been determined - wizard will sit on introduction page of the form for initial launch.  The wizard for chapt 31 will be independent of the wizard for chapt 36, but they may refer/promote users on the other program.  
- Will work on confirming entry points this week.

**Comment by mnorthuis** [comment]
IA work on this has been finalized.  
- @bethpotts confirmed that we do not need to consider the 0588 form
- entry points have all been documented
- wizard placement was confirmed to be on the /introduction page of the form

This issue can be closed at your discretion once you have all the information you need.  Please follow up with any questions. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt31.md

**Comment by shiragoodman** [comment]
@jason-gcio can this be closed out?
