### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by oleksii-morgun** [department-of-veterans-affairs/va.gov-team#90874]
### Request type

- [ ] Writing new documentation
- [X] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [X] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other

### Anything else?

I would like to suggest a correction to Platform Documentation website. Specifically to the Functionality of building isolated applications page https://depo-platform-documentation.scrollhelp.site/developer-docs/functionality-of-building-isolated-applications 

There are at least 2 places in VA Platform Documentation website that cover Continuous Deployment configuration. [Functionality of building isolated applications](https://depo-platform-documentation.scrollhelp.site/developer-docs/functionality-of-building-isolated-applications) page states that continuousDeployment flag is optional and enables continuous deployment when set to true.
![image](https://github.com/user-attachments/assets/6c388b9d-4e74-461a-9a44-2b7c82d5ba2b)

However, from my understanding and experience, this may not be correct. As outlined on the other page [Continuous deployment](https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment#Continuousdeployment-Enablingcontinuousdeployment)  that the flag is required to be set to false to disable, otherwise enabled by default without a need to set to true as described in the first page

Unless, I am interpreting this incorrect, the [first page](https://depo-platform-documentation.scrollhelp.site/developer-docs/functionality-of-building-isolated-applications) may benefit from an update as follows:

> **Before**: continuousDeployment  No. Enables continuous deployment when set to `true`.

> **After**: continuousDeployment  No.  Disables continuous deployment when set to `false`, otherwise enabled by default for applications on the [allow-list](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json)

**Comment by jknipes** [comment]
HI @oleksii-morgun thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by CBonade** [comment]
@jknipes This looks accurate to me. Good catch and good change!

**Comment by jknipes** [comment]
work has been completed in ticket 90874, closing as _Done_
