### ISSUE TITLE
Adding kyle.soskin@coforma.io to DSVA Slack

### ISSUE THREAD

**Issue by SilkeDannVA** [department-of-veterans-affairs/va.gov-team#90880]
Please add kyle.soskin@coforma.io (mailto:kyle.soskin@coforma.io) as a full member. They will be joining the CEDAR Benefits & Claims Project as Director of Engineering. We will add them to the appropriate channels once they are in.

Please reach out to Jeff Langworthy or Silke Dannemann on DSVA slack for any questions/clarifications.

**Comment by coforma-terry** [comment]
Hey all - any update on this?

**Comment by SilkeDannVA** [comment]
Hey! Please let us know how this is going. Jeff Langworthy and I are here to answer any questions. Thanks!

**Comment by KevinMHoffmanUSDS** [comment]
Invited.
