### ISSUE TITLE
[FE] Badge indicator:badge indicator implementation strategy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90892]
## Background
We will be upgrading the dot indicator currently in production indicating unread messages in the health care section on My VA to be a badge indicator - that is an icon with a count telling the user how many unread messages they have.

## Tasks
- [ ] #91205
- [ ] #91204
- [x] #91206
- [x] #91208
- [ ] #91209

## Acceptance Criteria
- [ ] Badge indicator exists in code behind a feature flag

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm badge indicator is functional in staging behind a feature flag

**Comment by ajakabcin** [comment]
@ACParker89 for refinement next week - if this needs to be broken out into additional tickets that's fine by me!

**Comment by mattmarino-adhoc** [comment]
[Research findings and materials](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/dot-indicator/research/2024-03%20Dot%20Indicator%20and%20Slim%20Alert%20Usability%20Study)

**Comment by ajakabcin** [comment]
Complete - additional tasks broken out as listed above
