### ISSUE TITLE
Coronavirus crisis standards of care content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9089]
# User story

As a Veteran or family member of a Veteran, I need to understand how life-saving resources like ventilators may be triaged if the current coronavirus pandemic causes a shortage of resources.

# Details

We need to develop communications to openly and empathetically communicate crisis standards of care to Veterans and their family members.

To do this, we propose:
- A page on VA.gov
-  A letter linking to the page on VA.gov

### Process steps to completion

- [x] Determine approach (Jen, Lauren, Chante, Danielle)
- [x] Research information and develop content (Danielle)
- [x] Initial copy edit (Randi)
- [ ] Revise internally (Danielle, Jen, Lauren)
- [ ] Build Drupal page (Danielle, Randi)
- [ ] Final copy edit (Randi)
- [ ] Send through approvals (Lauren)
- [ ] All approvals received
- [ ] Incorporate feedback (Danielle)
- [ ] Validate on live site (Danielle, Randi)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @stephorkandatx

**Comment by stephorkandatx** [comment]
@DanielleThierryUSDSVA for this sprint, or the upcoming sprint?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx. Working on this now so definitely this sprint, and may continue into next depending on reviews. Thanks!

**Comment by stephorkandatx** [comment]
Backlog this until we hear back

**Comment by DanielleThierryUSDSVA** [comment]
Note: Iceboxing this because it never (thankfully) resurfaced.

**Comment by DanielleThierryUSDSVA** [comment]
This is no longer relevant. Closing.
