### ISSUE TITLE
Request that SSH keys be authorized for Cindy Cruz

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#909]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Doris Lin (meichih.lin@va.gov) < Out of office most of August. Back up is Debbie Lawson
- Please provide your name.
   > Cindy Cruz
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BAH Team supporting Education on VA.gov (Comparison Tool, etc)
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

  > ssh-rsa 
AAAAB3NzaC1yc2EAAAADAQABAAABAQDAKa6XOv3bF75WFjUrDeCzFc6ISaDKcxPyFQ3T21OhPyNjQ/9bQpg8mntBWwNAMFMvtErs0Sk20EUeOiXu8djTxnSFA67yqaiHYud2yxmjlYa+uwKGmx5w9HuwhQIUM+AE3zMYRznz7vTVwRIntYW45OQk1xW6BYYPhIvRoRWm05HFpWeKUOXMm+kw5heR3flNiMNHAcN93Bgzk2XjXPxGHbIOWLyKUjxQ9/iDorlZxIezbYHz4tIxGlmVyacwaVCF590oqlGixOthwH5TzCGIL5BItYw6WBed3k+DX+g8EpbtnCwJYvCeOcwxRcMEW42PRRNHSP7wvOK2k5pKwG8R cindycruzgranados@c02wj1rjhtdg.users.bah.com

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by desireeturner** [comment]
@department-of-veterans-affairs/vsp-operations this issue is ready for your review. Please let myself or @ccruzgra know if any additional information is needed. Thank you!

**Comment by b00klegger** [comment]
@Jeff-Hayter 
COR: Doris Lin (meichih.lin@va.gov) < Out of office most of August. Back up is Debbie Lawson
User: Cindy Cruz

**Comment by Jeff-Hayter** [comment]
@b00klegger Confirmed.  Please grant access.

**Comment by b00klegger** [comment]
Access granted to AWS console and ssh key deployed. You can continue with the setup process. Please reopen issue and update with any errors.
