### ISSUE TITLE
[Design] Implement design or a11y changes to date and time picker component error alert or inline alert

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90908]
## Description 

- [x] Reviewed feedback from Brian D.
- [x] Implement design or a11y changes to date and time picker component error alert or inline alert

## AC

- [ ] Validated with designers
- [x] Added/updated to MVP page in Figma

## Deliverable
[Link to Figma design](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4052-16346&t=uvkXLGbaWvmyvwyU-1)

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/90908?planning-poker) with Zenhub @cgednalske

**Comment by cgednalske** [comment]
@benbrasso-agile6 will Ciera work on this when she's back? Seems very UI-heavy as far as coming up with a reliable component.

**Comment by cgednalske** [comment]
@Cieramaddox We took [these designs](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3751-15001&t=15heeg4R8hWNofWU-1) to office hours to get feedback from a few different platform folks. 

Brian D. was leaning towards [this inline solution](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3614-9310&t=15heeg4R8hWNofWU-1) as it most aligns with the design system, but needed to look into more a11y things to make sure there weren't screen reader challenges.

**Comment by Cieramaddox** [comment]
After speaking with Brian DeConinck, we will move forward with [option 4](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3614-8075&t=g3Ev7LptybQoc8fS-1). The decision to go with that option is simply because "the error message appears in closer context to the timeslots", giving more specific directions to the Veteran.

**Comment by benbrasso-agile6** [comment]
Nice; LGTM
