### ISSUE TITLE
[SPIKE] How are we going to solve for knowing the referral ID from a unique url from a text message (VA Notify)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90906]
## Description 

How are we going to solve for knowing the referral ID from a unique url from a text message (VA Notify)? 

## Additional information 

It's likely we will need to generate a unique ID to pass to VA Notify (who will be sending out text messages to Veterans that they have a new referral to self-schedule an appointment for) that enables the Appts app to know the referral ID to use when a user selects that link from their text message and arrives on Appointments (after authenticating). We will need to show the correct referral information (i.e., referral ID and referral information that we'll get from a WellHive endpoint) in the [task card component on the Appts landing page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2169-36402&t=jwDjK5620DcDmKqq-4). 

Also need to answer the following questions: 

- [ ] Are there VA security and infrastructure considerations for generating and saving a unique ID? For example, how long can we save the unique ID and have it active for? What if the Veteran doesn't select the link in their text messages for 2 weeks? A month? 
- [ ] If there is an expiration date of the unique ID, will or how will we be able to re-generate a new unique ID on the fly so the Veteran impact is not disturbed? 

## AC

- [ ] Document our implementation approach 
- [ ] Document VA security and infrastructure resolutions

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/90906?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by benbrasso-agile6** [comment]
Workflow discussed on 08/20

- Store and encrypt referral ID from WellHive
- Create url 
- Send to VA Notify
- VA Notify sends out message and url 
- User authenticates using ID.me, etc., on VA.gov and we decrypt the url 
- Note: If we're creating and storing referrals, we should have an expiration date (because of "VA security things"). E.g., 30 days.

**Comment by benbrasso-agile6** [comment]
> Jonathan Kamens
  Tuesday at 5:05 PM
I'm guessing these consult/referral IDs are unique and therefore can be associated with an individual, and therefore yes, they would be considered PHI.

> If it is possible to implement required functionality while only storing a hash of these IDs in the database, then that would be great. If not, i.e., if the original IDs need to be stored in our database, then they should probably be encrypted since they are PHI.
5:08
To be clear, you're not supposed to use PHI in URLs regardless of whether they're in the URL itself or in the query string.
One solution to that problem would be to encrypt (+ encode into ASCII) the consult/referral ID using symmetric encryption with a key that is only used internally within the application. That would make it acceptable to include the ID in the URL.
5:10
If you're going to do that, you will want to make it possible to rotate the encryption key periodically. To do that you want your implementation to allow for a single key to be active at any given time for encryption while allowing multiple keys to be active for decryption. That way you can continue to support URLs encrypted with previous keys for some period of time, and then remove the old keys from the system after a predetermined time period when it is considered OK for old URLs to stop working.

> (There is something I want to be clear here, which is that I understand that the "Don't put PII or PHI into URLs or query strings at all" rule is quite strict and has not been uniformly followed in the past. We are trying to get better about following this rule. We understand that that has some cost associated with it, but we believe it is necessary to adequately protect PII and PHI flowing through our system.)

> Stephen Barrs
  Tuesday at 5:12 PM
if we can encrypt/decrypt as described, we would not need to store any values in the DB, correct?  Just want to make sure I am following.  I def like that solution and I agree with not using PHI / etc in URLs.

> Jonathan Kamens
  Tuesday at 5:13 PM
(Another thing I would like to suggest is that since we're still in early days of trying to get people to start following this pattern, if you do end up implementing encryption of the type described above, I'd encourage you to do it in a way that is reusable by other teams.)

> There is another option you can consider as an alternative to encryption/decryption... If these URLs are expected to have time-limited lifetimes, e.g., because after the referral or consult has happened the URL no longer has any utility, then you could create a table in the database mapping randomly generated identifiers to referral/consult IDs + expiration times, use those randomly generated identifiers in the URL, and run a periodic job to purge the rows from that table that are past their expiration times.
This would significantly reduce the sensitivity level of the identifiers in the URLs because they would only be used for this one purpose and they would be purged, thereby removing the ability to identity individuals through them, when no longer needed.

> If you decide to use that pattern then I would also encourage you to build a generalized implementation that can be reused by others.

> Stephen Barrs
  Tuesday at 5:17 PM
Thanks 
Jonathan Kamens
 for all the great info!  This work is related to a pilot that very much may not go beyond a handful of Veteran users, but if we do go down this path we will try to build a generalized solution for sure.

**Comment by benbrasso-agile6** [comment]
@simiadebowale @lee-delarm6 please review the comment above so we can make some decisions and document the workflow of how this is going to work. Can we create a page in our repo for this workflow?

**Comment by lee-delarm6** [comment]
Are there VA security and infrastructure considerations for generating and saving a unique ID? For example, how long can we save the unique ID and have it active for? What if the Veteran doesn't select the link in their text messages for 2 weeks? A month?

- We could store a lorota DB record? We've have to create a section to create the collection, which I think is entirely doable. I think there's another DB we could use as well

If there is an expiration date of the unique ID, will or how will we be able to re-generate a new unique ID on the fly so the Veteran impact is not disturbed?

- The unique ID would be generated on hitting the URL and validating the referral ID is valid. It would effectively be regenerated anytime they click the URL if the current ID is invalid based on however long we determine is the expiration

**Comment by lee-delarm6** [comment]
Better setup:

- Vetext encrypts on their end
- User gets URL with encrypted referral ID
- User clicks and is directed to full login page
- Login page redirects to specific URL which captures the encrypted referral ID which we store
- User goes to the referral page
- On the backend, we decrypt the referral ID, and then pull data from Wellhive, and we're done!

**Comment by lee-delarm6** [comment]
Things we need:

- How does Vetext know what the referral ID is and when/how do they send the URL to the user?
- Is storing/sending the encrypted referral ID ok? (I assume it is)

**Comment by lee-delarm6** [comment]
Scratch some of the above, we have the patientID when the user logs in so we can access all referrals. Identifying the specific one will be matching the encrypted ID to one of their referral IDs (if applicable)

**Comment by benbrasso-agile6** [comment]
> How does Vetext know what the referral ID is and when/how do they send the URL to the user?

We will be getting the referral ID from EPS. VeText doesn't do this type of notification to date.

**Comment by benbrasso-agile6** [comment]
> If we send the notification (Via VA Notify), when do we send them?

I'm going to start a dialogue with VA Notify; we can figure it out together. From our side, when we get a new referral ID from EPS, we would want to send it to the Veteran asap. So, we would send it to VA Notify asap. And, it would be up to VA Notify to send it out. They might have "batch sending" rules.

**Comment by benbrasso-agile6** [comment]
> If we send the notification, how do we get the referrals in the first place to know when to send them? Are we supposed to download referrals all the time?

From Ryan (EPS): 

Yes, noted.  As part of the Referral resource we are going to add to the WellHive Care Navigation API, we will include something like a "new or changed since" search parameter for Referral.search action.

**Comment by benbrasso-agile6** [comment]
Want to make sure we're on the same page. I think the flow will need to be closer to: 

EPS gets referral from CCRA
Appts gets referral from EPS
Appts encrypts and creates url and sends to VA Notify
VA Notify sends Veteran notification 
Appts decrypts when Veteran authenticates on va.gov to know which referral information to show in task card on Appointments landing page

**Comment by benbrasso-agile6** [comment]
I would recommend pinging Stephen in Slack about these questions: 

> Is storing/sending the encrypted referral ID ok? (I assume it is)

> Internal question, is there an encryption service already available to use?

Although, I think Stephen was saying we would need to build something to encrypt and then decrypt.

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724857034587/50f5a6735d13d9273970da070a5573385dd7fb2c?sender=u37bb983bd3fc3cc00c7d3286
