### ISSUE TITLE
Update Quick start guide

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9091]
# User story

As a Veteran, I need the latest guidance on COVID-19 and benefits across all materials.

# Details

On the welcome kit page at [va.gov/welcome-kit/](va.gov/welcome-kit/), we need to update the COVID-19 pdf with the latest approved version, updated with new CDC guidance. We also need to add a new burials and memorials guide pdf.

The COVID-19 update is urgent and needs to go in tomorrow's (5/12) deploy.

### 1 

Update the covid guide pdf that's linked to from this link label. 

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0246beec-34ac-4043-a855-14a5a0498208)

Replace the pdf with this updated, 508-compliant pdf.

[VAWK-QSG-Coronavirus-Update_3_Final](https://app.zenhub.com/files/133843125/611d55b9-d949-4ceb-b514-1076e8f49ae2/download)

### 2 

Add this new burials and memorial guide, 508-compliant pdf as the last link in the list of guides shown in the image below.

[VAWK-QSG-Memorial Benefits-2020-508](https://app.zenhub.com/files/133843125/c9bb9577-f7b4-4688-ace9-544ac6636dd1/download)

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/c5077ae8-605e-4bf8-97eb-42e08926076d)

**Link label:** Apply for burial in a VA national cemetery and for memorial products (PDF)

## Acceptance criteria

- [x] Issue is labeled with team and practice area
- [x] Issue is attached to an epic
- [x] COVID-19 pdf is updated
- [x] New memorial guide pdf is added to page
- [x] Changes are validated on live site

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx @RLHecht. This is a priority for tomorrow's deploy. Not sure if we need dev help to update the pdf files as well. Let's sync in the morning. Thanks!

**To note:** @jenstrickland has reviewed these and confirmed that they're 508 compliant.

FYSA @jenniferlee-dsva @lalexanderson-dsva @chrisj-usds

**Comment by RLHecht** [comment]
@kelsonic Can you please add the new updated covid PDF and the new burials and memorials PDF to the assets folder? They are attached above in this ticket. The Covid one can replace what's already there and we can name the burials and memorials one burials-and-memorials-guide. We want these for today's deployment. Thanks! FYSA @stephorkandatx @DanielleSoCompany

**Comment by stephorkandatx** [comment]
Will make sure we cover this request this morning

**Comment by kelsonic** [comment]
Sent PR up, PR reviewed + merged, awaiting validation now 🙂

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Should the teaser text for the new burials PDF be "Apply for burial and memorial products"?

**Comment by RLHecht** [comment]
Changes are live on the site. FYSA @DanielleThierryUSDSVA @stephorkandatx Closing ticket.
