### ISSUE TITLE
10-7959c: copy updates (WIP)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#90916]
Beneficiary's mailing address:
- at the bottom of the screen, add period to end of sentence (after "new mailing address")
url: https://staging.va.gov/family-and-caregiver-benefits/health-and-disability/champva/other-insurance-form-10-7959c/applicant-mailing-address

**Comment by rmessina1010** [comment]
[PR in progress here](https://github.com/department-of-veterans-affairs/vets-website/pull/32221)
