### ISSUE TITLE
Add Alert for "We can't show all your information right now" for Upcoming Appointments Page & Details Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#90926]
## Background
Based on Staging Review feedback and the fact that we may not have all of the information available for the upcoming appointments, we have decided to add an alert to that fact so that Veterans will understand that they may not see all of the appointment information here, and give them a link to go to the appointment source information.

## Wireframes
[Check-in](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4092-16545&t=6jQVRlP2bOjnfjkN-1)
[Pre-Check-in](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=471-22466&t=wlj891EhDvY5Zglh-1)

## Tasks
- Add Alert for "We can't show all your information right now" to 
    - Upcoming Appointments Page 
    - Details Page when accessed from Upcoming Appointments

**Comment by loripusey** [comment]
@cgednalske Add a link to the wireframes when they are ready

**Comment by cgednalske** [comment]
Figma links have been added 👍 

Pinged Laura about the alert content and will post any updates here.

**Comment by brianseek** [comment]
A couple of things to point out, we aren't showing the alert when there are no upcoming appointments and on details pages we don't show the alert on a canceled appointment to avoid alert stacking

**Comment by benbrasso-agile6** [comment]
... information, go to ...

**Comment by cgednalske** [comment]
@brianseek the Pre-Check-in alert version looks good to me 👍  However, I'm wondering about the "Review your contact information" heading that is appearing on some detail pages but not all of them, though there is no link to review information.

**Comment by cgednalske** [comment]
For the Pre-check-in comment, here are a few Pre-check-in screenshots in your PR with the headings below, but there is also one without. Wondering why the difference? Or is the one without supposed to have the Check-in alert?

### With
 
<img width="725" alt="Screenshot 2024-08-22 at 11 01 34 AM" src="https://github.com/user-attachments/assets/00f0d316-bacc-412c-acd9-1e380cca384d">


### Without
<img width="724" alt="Screenshot 2024-08-22 at 11 03 34 AM" src="https://github.com/user-attachments/assets/d0df400a-0d4a-4f9a-8001-12a83890d6b9">

**Comment by cgednalske** [comment]
For my Check-in comment, could we change the language to the following. Laura's wording said that they should check in for THIS appointment, but that's not always/usually the case, so we probably want it to be more generic. @benbrasso-agile6 @zach-park are you two ok with changing THIS to YOUR?

**Heading:** We can't show all your information right now
**Body:** Some of your appointment information is not available right now.
To find all your appointment information, finish checking in for your appointment first. Then go to appointments on VA.gov.

[Figma updated](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4092-16740&t=SxRx8DoRyeC2rpjK-1)

Before
<img width="305" alt="Screenshot 2024-08-22 at 11 10 01 AM" src="https://github.com/user-attachments/assets/6d8bd386-b7a6-4778-96bf-82b2cb4b1cdc">

Change to
<img width="228" alt="Screenshot 2024-08-22 at 11 11 02 AM" src="https://github.com/user-attachments/assets/2830123b-3228-4a49-ba3b-202bdc4ea9fa">

**Comment by benbrasso-agile6** [comment]
Generic makes sense

**Comment by brianseek** [comment]
@cgednalske ah I see that heading now 👀 - that is a bug, unrelated to this work though. I will create a ticket for it.

the text changes look good, I'll make an update.

**Comment by brianseek** [comment]
@cgednalske text changes have been merged. Also squarshed that heading bug. This is ready for validation again:
Pre-check-in:
<img width="85" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4907ccf9cd7131024241eac9e797c4688cec9dc7/localhost_3001_health-care_appointment-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%286%29.png" alt="localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (6).png" />
<img width="163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--070c114792e88abda97894ad30d41404432f8396/localhost_3001_health-care_appointment-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%287%29.png" alt="localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (7).png" />
Day-of check-in:
<img width="85" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fc48f139b92320e7366420921670138917af56d/localhost_3001_health-care_appointment-pre-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%287%29.png" alt="localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (7).png" />
<img width="139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc05862f6ceec105377332a58c299ed3e41d8606/localhost_3001_health-care_appointment-pre-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%2812%29.png" alt="localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (12).png" />

**Comment by brianseek** [comment]
@cgednalske okay this is ready for real this time. Content has been updated and heading bug was squarshed.

pre-check-in:
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b36b3c5f7f90d64c2b52743a7b3b447ed33a4347/localhost_3001_health-care_appointment-pre-check-in_upcoming-appointments.png" alt="localhost_3001_health-care_appointment-pre-check-in_upcoming-appointments.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f6c1cbac422802e477ea2494061177a2b02b65a/localhost_3001_health-care_appointment-pre-check-in_upcoming-appointments%20%281%29.png" alt="localhost_3001_health-care_appointment-pre-check-in_upcoming-appointments (1).png" />
Day-of:
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGVEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43a159487693d8eab0312859e17683084afdf391/localhost_3001_health-care_appointment-check-in_upcoming-appointments%20%281%29.png" alt="localhost_3001_health-care_appointment-check-in_upcoming-appointments (1).png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e98c16b6050399a0bc42fd452d385de947b9210b/localhost_3001_health-care_appointment-check-in_upcoming-appointments%20%282%29.png" alt="localhost_3001_health-care_appointment-check-in_upcoming-appointments (2).png" />

**Comment by cgednalske** [comment]
@brianseek both Pre-Check-in and Day-of look great! 🎉 🚀  Stamp of validation! ✅

**Comment by brianseek** [comment]
yay! thanks @cgednalske ...closing
