### ISSUE TITLE
[Bug] Medical Device Re-ordering Tool - Clicking Back button from Facility Locator doesn't return to form-page (U)

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9093]
## What happened?
On Staging **Order hearing aid batteries and accessories** form, many form-pages have numerous copy/layout elements that don't match design prototypes.

## Specs:
- Browser-/device-agnostic \[though exact symptom varies between certain browsers]
- `vets.gov.user+1@gmail.com`

## Steps to Reproduce
1.  Go to https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
1.  Click **Order...** button, then keep clicking **Continue** button until you arrive at **Order your supplies** - **Select the hearing aids...** form-page.
1.  Click **What if I don't see my hearing aid** toggler-link to expand respective content.
1.  Click **Find contact information...** link -- click **Leave** if prompted about in-progress form.
1.  Once on **Facility Locator** page, click browser **Back** button.
1.  Observe that browser either returns to incorrect form-page, or does nothing -- while Win/Mac Chrome returns to the wrong form-page, others browsers/devices doesn't return to a form-page unless you click **Back** several more times.
\[See GIFs below]

### Mac Chrome example \[returns to wrong form-page]
![mdt-fl-back-bug-mac-chrome-200513](https://user-images.githubusercontent.com/587583/81894054-c2c1c080-9563-11ea-822e-372a425f9dc2.gif)

### Mac Firefox example \[takes several **Back** clicks before returning]
This is host most of the non-Chrome browsers/devices behave
![mdt-fl-back-bug-mac-firefox-200513](https://user-images.githubusercontent.com/587583/81894063-c7867480-9563-11ea-9e39-2fdfd29fef39.gif)

## Desired behavior
Clicking **Back** button immediately returns to **Order your supplies** - **Select the hearing aids...** form-page.

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
Thanks @tzelei - @bradl3yC @mr0sari0 What is your recommendation for this scenario? Thanks!

**Comment by bradl3yC** [comment]
@tzelei This is fixed in the next deploy to staging.  Find facilities now opens in a new window.
