### ISSUE TITLE
Update "Drupal as source of truth" documentation

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-team#90948]
### Description
We are in a years-long transition from using VistA as the Electronic Health Records (EHR) system for VA Medical Centers to using Oracle Health (formerly Cerner). As part of the transition, we're moving all data management to Drupal.

Previously, we used a feature flipper called `pw_ehr_cta_drupal_source_of_truth` to conditionally point this EHR system to VistA or the new Oracle Health system depending on the state of the transition. In January 2023, we removed this flipper and all the logic inside the health care widgets that were using it: https://github.com/department-of-veterans-affairs/vets-website/pull/23018/files. Now all of those widgets are on the Oracle Health EHR system and their data is being managed by Drupal.

We need an update in the documentation to reflect this update. Under the `So, how do I use Drupal as the source of truth?` header, we have an example linked that demonstrates the flipper behavior, which is now removed.

We need to remove the text in the red rectangle below:

<img width="720" alt="Screenshot 2024-08-19 at 11 24 34 AM" src="https://github.com/user-attachments/assets/8403490c-665e-4838-8eb4-7dc43087ae6c">

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for#Howtoopt-intoDrupalasthesourceoftruthforOracleHealth-relatedappsandwidgets-So,howdoIuseDrupalasthesourceoftruth?

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS Team (Sitewide)

**Comment by jknipes** [comment]
Hi @randimays, thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@randimays is removing the info in the red box the only work that needs to be performed for this issue?

**Comment by randimays** [comment]
@jknipes Yes, this is all that needs to be done.

**Comment by jknipes** [comment]
work was completed in [ticket 92012](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92012), closing as _Done_
