### ISSUE TITLE
Flipper UI access for Bryan Thompson

### ISSUE THREAD

**Issue by SnowboardTechie** [department-of-veterans-affairs/va.gov-team#90955]
### Your Name

Bryan Thompson

### Your GitHub handle (Flipper UI access is managed through GitHub)

@snowboardtechie

### Team, Role, and Company of the target individual

Sitewide Team, FS Software Engineer, Agile6

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need Production access to manage feature flags created during feature work.

**Comment by AnthonyWFlowers** [comment]
Greetings @SnowboardTechie you have been given access to Flipper UI Prod and lesser environments.
