### ISSUE TITLE
FE - Display Link to New Claim Status Tool for Past Appointments where a Claim HAS been Filed

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#90966]
## User Story
As a Veteran, I would like to see the status of a mileage-only travel reimbursement claim that I filed for a past appointment so that I can understand when (or if) I might get reimbursed by the VA for my travel to a VA facility.

## Wireframes
- TBD

## AC
- Each appointment that meets the following criteria should have a link to the new BTSSS Claim Status tools that allows the Veteran to see the status of their mileage-only travel claim
   - A claim has already been filed for the date and facility associated with the appointment

**Comment by brianseek** [comment]
closing this as a dupe since it is covered in 90975
