### ISSUE TITLE
[FE] Fix action link display in appointments for this facility

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#90985]
Check in action link isn't showing up in Today's appointments section
![Screenshot 2024-08-19 at 4 36 33 PM](https://github.com/user-attachments/assets/6fadaef5-d17c-4b6b-9157-32315120c504)

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/90985?planning-poker) with Zenhub @brianseek

**Comment by brianseek** [comment]
this has been merged and validated by @wullaski, moving to closed since no further UX validation is needed.
