### ISSUE TITLE
Add caching for copay endpoint

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#90998]
We are alerting on the copays endpoint pretty frequently. It'd be nice to add caching to this endpoint to take the pressure off of VBS and get alerts down.

Here's what we should do:
- [ ] Add caching for empty responses
- [ ] Add feature flag for caching incase there is an issue with our caching code
- [ ] Add data dog metrics
  - [ ] All requests made
  - [ ] Every time a response is cached
  - [ ] Every time a cache response is returned
  - [ ] Dashboard for the above metrics

**Comment by digitaldrk** [comment]
This was unplanned work that we may need to re-prioritized, definitely rolled over.

The idea for this ticket was that we were hitting VBS too hard and in an effort to be good stewards of their resources, we were going to cache empty responses just like DMC.

After correspondence via email and a call with them. It was illuminated that there were errors being thrown on their side and they are going to look into that.

I still think it's a good idea to add this for better Vet experience but the urgency on this ticket isn't there anymore I don't think.

I have done some work on this ticket. Mainly researching what an empty response looks like so we know what to trigger the caching mechanism on.

After meeting with VBS, it

**Comment by maxx1128** [comment]
I can confirm this ticket is complete as of the end of the sprint. We're aiming to get the feature flag for it enabled for the functionality and DataDog tracking.

**Comment by maxx1128** [comment]
Confirmation that the added tracking for VBS cached responses is up and running.

![Screen Shot 2024-09-11 at 11 40 50 AM](https://github.com/user-attachments/assets/e255c2ad-36f1-48d3-ab0c-817d86440080)
