### ISSUE TITLE
Null state prior to canceling a booked appointment 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#90999]
## Description

Requirement 1: The provider name is displayed on the Upcoming Appointment Details page. The provider name is not captured on the review details page before canceling the appointment and on the canceled confirmation screen. The expected behavior should show the label and provider data. 

https://github.com/user-attachments/assets/7918aacf-3bdc-46e0-b3ab-28355638c0d6

Requirement 2: The provider name is not displayed on the Upcoming Appointment Details page. The `Who` label is displayed on the review details page before canceling the appointment and  on the canceled confirmation screen. The expected behavior should suppressed the label if no data is presented. 

https://github.com/user-attachments/assets/3dfdaa4e-d81e-476d-b9fb-c97ded7b5900

---

## Development Checklist

- [ ] Task 1
- [ ] Task 2

### Design Assets
- [Figma file]() (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by JunTaoLuo** [comment]
FYI moving to blocked since the scope of this issue increased to include cancellation confirmation pages for multiple appointment types. Given the increased scope, we need a bit more clarity on what sections should be displayed for the different appointment types and some more guidance on the UI hierarchy (e.g. heading sizes). We'll need clarification from product/design before engineering work can continue.

**Comment by JunTaoLuo** [comment]
Here are the updated designs for the cancellation pages: https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1087-86861&node-type=canvas&t=0xS216G9fTB7hONP-0

**Comment by ldelacosta** [comment]
Validated in staging. No issues to report. Closing out the ticket. 
<img width="537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f799fda30e68382d5706355c8ebd9d0def1bf6cc/Screenshot%202024-10-21%20at%205.45.16%E2%80%AFPM.png" alt="Screenshot 2024-10-21 at 5.45.16 PM.png" />
