### ISSUE TITLE
AWS access for Dina Steeve restored for DSVA AWS

### ISSUE THREAD

**Issue by dsteeve** [department-of-veterans-affairs/va.gov-team#90997]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Dina Steeve

### Your Email

dina.steeve@adhocteam.us

### Team, Role, and Company of the target individual

Team Cassowary  and Team Quokka

### Product Manager (PM) name and email

Chinedu Nwagwu  chinedu.nwagwu@adhocteam.us

### Product Owner (PO) name and email

Peter Tebbenhoff  Peter.Tebbenhoff@va.gov

### Desired AWS Access

I need to restore my DSVA access I had.  [See issue 25776](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25776).  I think it broke because I haven't used it for a period of time because I was focused on other things.

I have AWS dvp-gov-internal access, but I need DSVA access to confirm Forward Proxy connectivity for Lighthouse public APIs and to verify Kong consumers when asked questions on API access for API Teams setup on the Lighthouse public platform.

### Access Expiration

November 11, 2025

### E-QIP Transmittal Confirmation

<img width="864" alt="Eqip-transmittal-email" src="https://github.com/user-attachments/assets/e9fc207a-9f48-492d-b827-d74fae00379f">

### Additional Notes

I get this error when trying to use the MFA script to log into AWS DSVA 

"An error occurred (InvalidClientTokenId) when calling the GetSessionToken operation: The security token included in the request is invalid."

I get this error when trying to  use the[ DSVA login page. ](https://dsvagovcloud.signin.amazonaws-us-gov.com/console)
"Your authentication information is incorrect. Please try again."

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
I've re-enabled your account and sent you a temporary password in DSVA Slack.

**Comment by dsteeve** [comment]
Thank you!  I have reset my password and appears to be working.
