### ISSUE TITLE
CT: Program under Approved programs isn't consistent upon school selection

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9099]
Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Search VETTEC
3. Select Galvanize Data Science Immersive
4. Return to search results and select Hack Reactor Software Engineering
5. Under Approved programs see that the program name doesn't match your selection

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/81934928-c8e48b00-95bd-11ea-9d59-f18c522af950.gif)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12727

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/83041180-335de800-a00e-11ea-8464-3b1602aceeef.gif)
