### ISSUE TITLE
Broken Link on VA.gov Health Care Application Introduction

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#910]
## What happened?
There is a broken link on this url: https://www.va.gov/health-care/apply/application/introduction. When you click on the text link "get help filing your claim" the page is redirected to a 500 - internal server error message. 

## Specs:
- Device: HP laptop
- Browser: Google chrome

## Steps to Reproduce
- URL: https://www.va.gov/health-care/apply/application/introduction

Find the text link that says "Get help filing your claim"

Click on the link

## Desired behavior
I am not sure where the link is supposed to go but it shouldn't take you to an error message. 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ncksllvn** [comment]
CC: @Karak888 for visiblity

**Comment by Karak888** [comment]
@ncksllvn I'll schedule meeting tomorrow per our discussion.  Thanks

**Comment by ncksllvn** [comment]
This is actual a broken link in a series of React apps so not CMS-related. Already opened a PR to patch it, but just make sure you have on eyes on it too.

**Comment by ncksllvn** [comment]
Fix for this should be live tomorrow EOD. Thanks @clantosswett!

**Comment by clantosswett** [comment]
Awesome. Thank you!!
