### ISSUE TITLE
Consider fixing JSONEntityEscape warning from brakeman

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#9100]
Our static security analysis tool, brakeman was recently updated in department-of-veterans-affairs/vets-api#4261 and now issues the following warning:

== Warnings ==

Confidence: Medium
Category: Cross-Site Scripting
Check: JSONEntityEscape
Message: HTML entities in JSON are not escaped by default
File: config/environments/production.rb
Line: 1
This configuration was created in department-of-veterans-affairs/vets-api#56 explicitly in department-of-veterans-affairs/vets-api@c73c8fc and it is now flagged by a new check in the security scanner.

Since we tacitly approved this configuration years ago, it seems sensible to skip the warning. We would need to inventory/verify an enormous amount of JSON output to make sure changing this configuration had no ill effects, which seems like a high-effort, high-risk task for little gain. The security exception was granted in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/105

The work around actually addressing the issue is unclear but should be undertaken at some point and this is the PR to do it!

Related PRs
https://github.com/department-of-veterans-affairs/vets-api/pull/4261
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/105

**Comment by erluti** [comment]
@alexpappasoddball maybe we should get the security team's input?  It sounds like it won't be easy to remove if it's not a serious concern.

**Comment by alexpappasoddball** [comment]
@f1337 Do you have any thoughts on this?
