### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#91005]
### Your Name

Bo Altes

### Your GitHub handle (Flipper UI access is managed through GitHub)

baltes

### Team, Role, and Company of the target individual

IVC Forms, PM, Agile6

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [ ] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Ensuring coverage for reduced team roster for our upcoming contract year

**Comment by davidpetras** [comment]
@baltes you have been provided `prod` access within Flipper.
