### ISSUE TITLE
Tech debt: Clean up service & client

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#91012]
## Context
There is quite a bit of duplicated code and cruft floating around the code base, especially in the service and client files. We should clean these up.

## Justification
- makes way for future monitoring/logging/error handling enhancements
- reduces debugging cognitive load

## Acceptance Criteria
- [ ] Code passes codeql quality checks
- [ ] Code implements 1 cleanup suggestion from each engineer on the team (during PR)

**Comment by ayush-chak** [comment]
A lot of this has already been done while working on other items - we have an alternate means of dealing with tech debt now.
