### ISSUE TITLE
[FE] Add mocks and tests for no upcoming appointments

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#91028]
## Description

- add a UUID with no upcoming appointments
- make an e2e test with that scenario so we can make a screenshot of the unique page
- also take a screenshot of the populated upcoming page

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91028?planning-poker) with Zenhub @brianseek @wullaski

**Comment by brianseek** [comment]
moving this straight to closed since it was a dev ticket with no further validation needed
