### ISSUE TITLE
Voice interaction

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9102]
As a visitor to a VHA facility, I'd like to complete the covid screener questions via voice response rather than typing my responses in on my smartphone or using a shared kiosk, so I can quickly move through the screen process at a safe distance while keeping my hands free.

**Comment by artsymartha68** [comment]
I can get the content to read aloud using Voice Control but it only recognizes the first Yes button. I'll keep playing with it.

I think once we semantically set the 2 options to be radio buttons, I'll get the chance to answer no and move on?
