### ISSUE TITLE
Site-specific customization

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9103]
As a visitor to a VHA facility, I'd need the questions in the covid screener to be relevant and in context with the reality on the ground in at the facility I am entering, so I can be confident in the screening results and do not have to answer extraneous or potentially misleading questions.

## Examples
- http://va-etil-covidscreen.s3-website-us-east-1.amazonaws.com/
- http://screen.vetext.info/?type=emp
- http://screen.vetext.info/664/

## Acceptance Criteria:
- [ ] Alternate question text

**Comment by batemapf** [comment]
To me, gold standard would be integrate questions sets with the [Facilities API](https://developer.va.gov/explore/facilities) _and_ the CMS. So a facility can use the CMS to modify their questions w/o code, and then the Facilities API can deliver those question sets on a per-facility basis. All of the VHA VISN/VAMC/facility data structure already exists in both places (I believe) and there is something like this already happening with other COVID-19 alert messaging. Not _the_ solution, but definitely something to chew on.

**Comment by batemapf** [comment]
Context: we're getting push back from facilities who want to implement their questions...

**Comment by batemapf** [comment]
First question is how real is this demand for site specific content?

**Comment by batemapf** [comment]
Sources of context:
- Facilities API
- Facility Locator
- CMS

**Comment by batemapf** [comment]
i recommend speaking with @davidconlon and @davem-va about the first two bullets. @JeffBarnesUSDS for the third.

**Comment by mchelen-gov** [comment]
> To me, gold standard would be integrate questions sets with the [Facilities API](https://developer.va.gov/explore/facilities) _and_ the CMS. So a facility can use the CMS to modify their questions w/o code, and then the Facilities API can deliver those question sets on a per-facility basis. All of the VHA VISN/VAMC/facility data structure already exists in both places (I believe) and there is something like this already happening with other COVID-19 alert messaging. Not _the_ solution, but definitely something to chew on.

CMS integration would be really cool, probably a longer term goal that can be split out?

**Comment by batemapf** [comment]
Good idea. Going to flip this to an Epic and start attaching smaller chunks of work to it.
