### ISSUE TITLE
On video details pages, move the "Need to make changes" section below "Prepare for your visit"

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#91036]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

On video details pages, move the "Need to make changes" section below "Prepare for your visit". This aligns how these sections are placed across all details pages.

---

## Development Checklist
Background: the `va_online_scheduling_med_review_instructions` toggle is on

- [ ] Task 1
- [ ] Task 2

### Design Assets

<img width="375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUZ3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7166bd3646cccda66116405d807007e5f50ee4f4/image.png" alt="image.png" />

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
FYI @JunTaoLuo @ldelacosta this is the minor issue we saw during demo

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
