### ISSUE TITLE
Question content

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9104]
As a visitor to a VHA facility, I want the questions in the covid screener to be clear, concise and easy to understand given my level of comprehension, so I can quickly understand what I am being asked and confidently give a response in order to proceed through the screening process.

**Comment by batemapf** [comment]
Needs to be updated to match latest content: 

https://dsva.slack.com/archives/C013WDER4FP/p1589929706106200

**Comment by mchelen-gov** [comment]
is this completed?

**Comment by mchelen-gov** [comment]
closed by https://github.com/department-of-veterans-affairs/vets-website/pull/12744
