### ISSUE TITLE
Update BTSSS API path and credentials for eCheck-in Travel & OH Travel

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#91049]
## Background
The Claims Ingest API (the API we are currently using is finalizing the transition of a migration and we have new values for
Endpoint base:
- OAuth client ID:
- OAuth client secret:
- APIM subscription key east
- APIM subscription key south

**NOTE: We need to be on the new configuration by 8/31; this is a hard dealine**

## Resources
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1724168533884949)

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91049?planning-poker) with Zenhub @randomsync

**Comment by loripusey** [comment]
@randomsync can this be closed?

**Comment by randomsync** [comment]
yes, closing
