### ISSUE TITLE
FE | Contact Information | Go back to edit button is not responsive for mobile screen size

### ISSUE THREAD

**Issue by asiisii** [department-of-veterans-affairs/va.gov-team#91076]
### Bug Ticket: Styling Issue on "Contact Information" Page

**Title:** "Go Back to Edit" Button Not Taking Full Width on Mobile Screen in Address Group

**Description:**
On the "Contact Information" page, within the Address group, there are two sections: **Mailing** and **Home**. When a user clicks the edit button for either section and then saves their changes, the **"Go back to edit"** button does not take up the full width of the container when the screen size is 481px or smaller (mobile size). This behavior causes a visual inconsistency and affects the user experience on smaller devices.

**Steps to Reproduce:**
1. Navigate to the **Contact Information** page.
2. Locate the **Address** group, which contains the **Mailing** and **Home** sections.
3. Click the **Edit** button on either the **Mailing** or **Home** section.
4. Make any changes in the edit form.
5. Save the changes.

![Image](https://github.com/user-attachments/assets/4eaa6189-31b9-42e6-95e0-e89f2b8d2559)

**Expected Result:**
- The **"Go back to edit"** button should take up the full width of the container on screen sizes 481px or smaller.

**Actual Result:**
- The **"Go back to edit"** button does not take up the full width of the container on screen sizes 481px or smaller.

**Acceptance Criteria:**
- [x] The **"Go back to edit"** button should take up the full width of the container when viewed on screen sizes 481px or smaller (mobile size).
- [x] The styling should remain consistent with the rest of the page, ensuring that the button reverts to its default styling on screen sizes larger than 481px.

**Comment by mtcA6** [comment]
tested w user 202 changing the size w/chrome tools this worked as expected
