### ISSUE TITLE
Bug: Link Text on Upcoming Appts Page is Incorrect

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#91083]
## Task
- Change text of link on Upcoming Appts page that takes the Veteran back to the main appointments page
    - See [wireframe](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=393-18188)

**Comment by brianseek** [comment]
@cgednalske / @benbrasso-agile6 / @zach-park this is merged and ready to validate. See screenshots in PR https://github.com/department-of-veterans-affairs/vets-website/pull/31572

**Comment by zach-park** [comment]
LGTM, thank you!

**Comment by brianseek** [comment]
thanks @zach-park! closing
