### ISSUE TITLE
Unrelated errors are logged with "COE claim submitted to LGY:" message in Sentry

### ISSUE THREAD

**Issue by sanjabaj2** [department-of-veterans-affairs/va.gov-team#91111]
## Issue Description
Sentry is showing about [2k errors with "COE claim submitted to LGY:" message](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=3&query=%22COE+claim+submitted+to+LGY%3A+%22&statsPeriod=30d).  **First seen 19 days ago.** The errors seems to be unrelated to COE. 

Here are few examples:
[This seems to be 500 internal server error related to education.](http://sentry.vfs.va.gov/organizations/vsp/issues/275361/?environment=production&project=3&query=%22COE+claim+submitted+to+LGY%3A+%22&statsPeriod=30d)
[This one is 503 Service unavailable related to direct deposit.](http://sentry.vfs.va.gov/organizations/vsp/issues/275361/events/1ee64993699b4707a56b6b6867225def/?environment=production&project=3&query=%22COE+claim+submitted+to+LGY%3A+%22&statsPeriod=30d)
[This one 500 internal server error related to education / chapter 33.](http://sentry.vfs.va.gov/organizations/vsp/issues/275361/events/1a2acc19368d49259afd197ce1eac72d/?environment=production&project=3&query=%22COE+claim+submitted+to+LGY%3A+%22&statsPeriod=30d)

---
## Tasks
- [ ] Find the reason for crosspollination and fix the issue

## Acceptance Criteria
- [ ] Errors for services unrelated to LGY are no longer logged with "COE claim submitted to LGY:" message
---

**Comment by sanjabaj2** [comment]
Let's wait a little, before spending too much time on this. Steve though that this may be issue on Sentry side.[ I asked question ](https://dsva.slack.com/archives/CBU0KDSB1/p1724798178424289)in #vfs-platform-support slack channel.

**Comment by mjknight50** [comment]
@sanjabaj2 COE does use the LGY API for it's back-end API call as you can see here:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/coe_claim.rb#L10


What I do think we can action on here is the removal of sentry.  What I would suggest is that I do a simple PR to remove Sentry, since it is being deprecated anyhow, and log these errors to DataDog.

**Comment by sanjabaj2** [comment]
That works. Thank you.

**Comment by sanjabaj2** [comment]
The ticket says it is in review. Should it have a PR linked to it? Just asking process wise.

**Comment by mjknight50** [comment]
Combining this with https://github.com/department-of-veterans-affairs/va.gov-team/issues/90411

Both will be addressed by removing sentry and cleaning up logging.

**Comment by mjknight50** [comment]
Closing this ticket in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/92416
