### ISSUE TITLE
sitewide, forms — 508-defect-3 [SCREENREADER]: Consider updating phone number documentation in design system, to include spacing in the aria-label

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9114]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

> Located in [VSA BAM2 MDOT MVP a11y spot check](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5868#issuecomment-627425136)

> Previously documented https://github.com/department-of-veterans-affairs/va.gov-team/issues/6997

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

**Finding 2**

There is a new method for coding phone numbers on VA.gov, and Robin Garrison just added a PR for a global component. **Consider** adding the aria-label to ensure the screen reader reads the number empathetically. Using a title attribute on links is not recommended. 

This guidance applies to all of the phone numbers within the product.

Work initiated by @Mottie: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8793

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to read phone numbers spelling out each number with enough clarity to comprehend.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: all

## Steps to Recreate

1. Enter https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction in browser
2. Log in as username: vets.gov.user+1@gmail.com
3. Start screen reading device
4. Verify the title text is read, and the numbers read out may vary depending on the screen reader used; sometimes read as hundreds and thousands

## Possible Fixes (optional)

Remove the title attribute, and add an aria-label.

**Current code**
```html
<a title="Dial the telephone number 303-273-6200" href="tel:303-273-6200">303-273-6200</a>
```

**Recommended code**
```html
<a aria-label="3 0 3. 2 7 3. 6 2 0 0." href="tel:303-273-6200">303-273-6200</a>
```

## WCAG or Vendor Guidance (optional)

* [I thought title text improved accessibility. I was wrong.](https://silktide.com/blog/2013/i-thought-title-text-improved-accessibility-i-was-wrong)

* [Accessibility and phone number formatting](https://thatdevgirl.com/blog/accessibility-phone-number-formatting)

## Screenshots or Trace Logs

![Screen Shot 2020-05-12 at 11 32 31 AM](https://user-images.githubusercontent.com/57469/81713793-500df380-9444-11ea-8884-47e3514b831e.png)

**Comment by Mottie** [comment]
The `Telephone` component is now available to the developers of the vets-website repository. Now we just need to switch over all old links & encourage everyone to use it when creating new links!

**Comment by 1Copenut** [comment]
@leahkeeler && @MasterMahariel Can you review this issue when you have a few minutes? The Design System team has added a [Telephone component](https://design.va.gov/storybook/?path=/docs/components-telephone--default) that should alleviate the ask here.

**Comment by leahkeeler** [comment]
Thanks @1Copenut - we have this in our backlog. we are currently down on eFE dev, as FYI

**Comment by 1Copenut** [comment]
I appreciate the heads up @leahkeeler

**Comment by LinnJS** [comment]
@joshkimux would love some validation here when you get a moment, @craigwheeler did this work about a month ago.

**Comment by joshkimux** [comment]
@LinnJS I think the link in the original ticket is broken-- is there a specific page I can look at to validate this? 🙇

**Comment by LinnJS** [comment]
@joshkimux here is the link to our [form](https://staging.va.gov/manage-va-debt/request-debt-help-5655/introduction) we replaced the telephones components throughout the entire form. So unfortunately its global. But we mostly use the Telephone component in the intro page and footer.

**Comment by joshkimux** [comment]
@LinnJS Looks good to me! 
@1Copenut , since this is a sitewide ticket, should we keep this open or should we close this out?

**Comment by 1Copenut** [comment]
@joshkimux I think we close this one, and flag forms in staging reviews when we see legacy code.

**Comment by joshkimux** [comment]
Closing out 🥳
