### ISSUE TITLE
BAM2 bug — 508-defect-2 [AXE-CORE]: Heading levels SHOULD increase by one

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9115]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

> Located in [VSA BAM2 MDOT MVP a11y spot check](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5868#issuecomment-627431704)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Heading levels **should** only increase by one. The card headings are currently h4, but are not preceded by an h3. **Should** be an h3 and use the utility class to visually style as h4. On this page, the change should apply to both Permanent and Temporary address cards.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the hierarchy of the page content using heading levels to save time and frustration.

## Environment

- Operating System: all
- Browser: all
- Screenreading device: any
- Server destination: staging & production

## Steps to Recreate

1. Enter https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction in browser
2. Log in as username: vets.gov.user+1@gmail.com
3. Have developer tools open, and the axe browser extension loaded
3. Run an axe audit
5. Verify that <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">Permanent address</h4> is called out as an error of "Heading levels should only increase by one"
6. This error is repeated throughout the form process

## Possible Fixes (optional)

**Current code**
```html
<h4 class="review-card--title vads-u-display--inline vads-u-margin--0">Permanent address</h4>
```

**Recommended code**
```html
<h3 class="review-card--title vads-u-display--inline vads-u-margin--0 vads-u-font-size--h4">Permanent address</h3>
```

## WCAG or Vendor Guidance (optional)

* [axe-core 3.4 - Heading levels should only increase by one](https://dequeuniversity.com/rules/axe/3.4/heading-order)

## Screenshots or Trace Logs

![Screen Shot 2020-05-12 at 11 48 33 AM](https://user-images.githubusercontent.com/57469/81715729-8c425380-9446-11ea-9d92-7bcc1aa2fc97.png)

**Comment by cvalarida** [comment]
Looks like this is a BAM2 bug; I believe this markup is created in the [2346 `ReviewCardField` component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/2346/components/ReviewCardField.jsx#L375). See also the [edit view code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/2346/components/ReviewCardField.jsx#L256-L258).

**Comment by jenstrickland** [comment]
@bradl3yC Please review the above comment from Chris who indicates this is not a sitewide issue.

**Comment by meganhkelley** [comment]
Removing sitewide & VSP labels, but feel free to tag me or Chris if you need us on this!

**Comment by joshkimux** [comment]
@artsymartha68 do you know who owns MDOT now by any chance? Would you be able to forward this issue to them?

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
