### ISSUE TITLE
[BE/Data] 10-10EZR: Come up with way to differentiate between failed jobs still retrying and those that have failed completely and make sure we're retrying

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#91156]
As a team member, I would like to know when a submission fails initially versus when it fails completely so that I know when I need to investigate an issue, and when I need to wait to see if it succeeds later.

- [x] See [Slack Thread](https://dsva.slack.com/archives/C0310PNS7TQ/p1724094968489669?thread_ts=1724094188.538809&cid=C0310PNS7TQ)
- [x] Make sure jobs are retrying
- [x] Figure out if we can differentiate in the alert between jobs failed and exhausted failure after retry 
- [x] **Success: We know when a Submission Fails but still has retried (e.g. due to a down service), and when it fails completely **

**Comment by allanto-ah** [comment]
No QA needed. Closing
