### ISSUE TITLE
BGS::SubmitForm686cJob Sidekiq Exhaustion Errors

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91155]
## Issue Description
_I'm showing that we have 94 Sidekiq exhaustions in the last week in the following format:_
`BGS::SubmitForm686cJob b491ae45226b0381cf334b6f died with error expect the argument to be a String, got BGS::ServiceException (#<BGS::ServiceException: BGS::ServiceException>)`.

[Example of error](https://vagov.ddog-gov.com/dashboard/ftx-zzd-v9j/benefits-sidekiq-job-death-queue-view?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1723642833192&to_ts=1724247633192&live=true).

Can you please provide information on:

- Is this exhaustion veteran-impacting?
- If so, is this error being handled by an automated process?
- If not handled by an automated process, does the team have a monitor to alert for this exhaustion?  Is there a manual remediation process (please provide a link to any process info)
- If there is any danger of an exhausted veteran submission becoming a silent failure due to loss of information?

---
## Acceptance Criteria
- [x] Answer questions listed above
- [x] Create follow on tickets if necessary
- [ ] Update #91155 if needed
---

**Comment by micahaspyr** [comment]
1. This error is not veteran facing
2. The error is itself an error when trying to log an error message to Rails.logger/Datadog
3. This error exists inside an retry exhaustion block so it will only show up once per job submission cycle
4. Yes, but I wouldn't call this a silent failure

The biggest problem with the error is that the code calling the logger method happens before a backup submission is kicked off.  Moving the error code to the bottom would allow the backup job to kickoff before this error is reached

**Comment by micahaspyr** [comment]
Ok, I was able to track down the error at hand.  In a nutshell, the error message that is nested indicates that the application attempted to insert a value into the PHONE_NBR column of the VNP_PTCPNT_PHONE table, but the value's length exceeds the maximum allowed for that column.  This error is coming the 3rd party API as we're sending it 12 characters instead of the maximum of 11. 
An example of the error that is occurring is in this [link](https://vagov.ddog-gov.com/logs?query=%22BGS%3A%3ASubmitForm686cJob%20received%20error%2C%20retrying...%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZF2Yg-deFyyZAAAAAAAAAAYAAAAAEFaRjJZaDJtQUFEck9hTmVBSGt4TkFBNAAAACQAAAAAMDE5MTc2NjUtZDk4MC00NDE0LTk5YzgtYzMxMTJjZmUxZjg2&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718028344681&to_ts=1718633144681&live=true) in the payload key "nested_error"
This is odd because something like 907-707-9107, the normal display of a number, doesn't work here. What we can do is:

1. Strip the "-" out from the phone numbers before they are sent off
2. Tell the stakeholders to modify the DB column

It should be obvious that the second option is akin to moving mountains.  I think we should strip the dash out of the phone numbers.  I'll chat with some of the Dependents folks to go over this.

**Comment by mjknight50** [comment]
I agree that it is odd that we suddenly see this.    I agree that the best course of action is to just strip dashes and probably should .strip the phone numbers as well.

**Comment by steele-lm** [comment]
@micahaspyr Is the third party API BGS/BIS? (If so, this only applies to the 686 form and not our other forms, right?) Also, a side note, we do need to [migrate 686/674 off of the depreciated BGS SOAP service](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91282) and onto the new RESTful APIs. I assume we'll need to take a fresh look at the validation at that point to ensure nothing has changed.

**Comment by sanjabaj2** [comment]
Frequency of this error [increased around Thursday last week](https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-prod%20%40named_tags.dd.service%3Avets-api%20%28%22BGS%3A%3ASubmitForm686cJob%20failed%2C%20retries%20exhausted%21%22%20OR%20%22BGS%3A%3ASubmitForm674Job%20failed%2C%20retries%20exhausted...%22%29%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1721770060240&to_ts=1724362060240&live=true). Before we make code change, can we make an effort to find out what changed?
Also, we can't just remove dashes and maybe RBPS is relying on it if they parse it by any chance. We got to verify with them that would work? Could, by any chance this be related to adding international phone numbers? Just guessing.

**Comment by sanjabaj2** [comment]
August 13/14 coincide with pushing to production updated dependents form. We assured BGS that we were not changing any field coming to them, but it appears, that we may have changed an existing field.

**Comment by micahaspyr** [comment]
Strange that international numbers would be supported with only 11 characters/numbers as many countries can have more than 11 numbers (Australia, for instance, can have up to 15 numbers).  11 characters work for a dashless US phone number which is 10 numbers, 11 if a country code of 1 is included.  This makes me think that they are only wanting numbers on BGS side of things.  

So a number such as 1-512-555-6767 will be 11 characters long once the "-" is removed.  We can double check with them but I see no scenario where they want anything but numbers in the phone number.

**Comment by sanjabaj2** [comment]
We still should understand why sudden increase in number of instances. What changed when we pushed the code last week?

**Comment by micahaspyr** [comment]
@sanjabaj2 I see that there was a change to the logging on 8/15 for 686c and 674 submission jobs.  I think we can modify the logging method quickly and then we can dig into the error from BGS next week.

**Comment by mjknight50** [comment]
I think there are two things going on here.

1.  One is that we aren't properly logging the error.
2.  The other is that something changed on the phone number itself.  I haven't look at PR history, but sounds like something was recently changed related to international phone numbers.

As for the logging piece, 
[@Micah Frazier](https://dsva.slack.com/team/U055EUS2N95)
 asked about defining what comes back when we hit _sidekiq_retries_exhausted_
 
From what I can see:
When we kick off the async job in `SubmitForm686cJob < Job`
When that errors, we get back `BGS::ServiceException`  which I think is defined in bgs_errors (lib/bgs/exceptions/bgs_errors.rb),
There is this block

```
def raise_backend_exception(key, source, error)
    exception = BGS::ServiceException.new(
     key,
     { source: [source.to](http://source.to/)_s },
     403,
     error.message
    )
    raise exception
   end
```

ServiceException is defined in:
lib/bgs/exceptions/service_exception.rb
ServiceException inherits from:
 class ServiceException < Common::Exceptions::BackendServiceException
And in lib/common/exceptions/backend_service_exception.rb
I see

```
def errors
    Array(SerializableError.new(i18n_data.merge(render_overides)))
   end
```

So, end of the day, I think we were right when we had this?

Rails.logger.error('BGS::SubmitForm686cJob failed, retries exhausted!',
                         { user_uuid:, saved_claim_id:, icn:, error: })
(https://dsva.slack.com/archives/C07GG2L5N77/p1724442635771349?thread_ts=1724442612.128899&cid=C07GG2L5N77)

I'm not a Ruby person so if I missed something there, I apologize..

**Comment by mjknight50** [comment]
Reassigning to @tfink419

**Comment by mjknight50** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/18236

**Comment by steele-lm** [comment]
@tfink419 Will check datadog logs to ensure the issue is fixed.

**Comment by tfink419** [comment]
This appears to be successful. The last error to occur with this wording was on August 30.
https://vagov.ddog-gov.com/logs?query=%22expect%20the%20argument%20to%20be%20a%20String%2C%20got%20BGS%3A%3AServiceException%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1724392800000&to_ts=1725906360000&live=false
