### ISSUE TITLE
ARF Design Onboarding - Jim

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#91188]
Welcome, Jim! This ticket has resources and artifacts to help you onboard to the Accredited Representative-Facing (ARF) Team. We recommend moving through this checklist in order, rather than hopping around. To the best of our ability, we have tried to provide context for the level of review needed for each item. 

As you're moving through the checklist, feel free to:
- Ask any questions in the [OCTO Slack channel #benefits-representative-facing](https://dsva.slack.com/archives/C05SUUM4GAW).
- Add any open questions to [ARF Open Questions Canvas](https://dsva.slack.com/docs/T03FECE8V/F06PMJPHMJQ) (pinned in our OCTO Slack channel).
- Bookmark or create a list of resources that you'd like to revisit later. For example, Kristen keeps a Google doc for herself that contain notes for each of our recurring meetings, a link to various helpful Figma files, etc.

### Join Slack channels
- [x] [OCTO Slack channel #benefits-representative-facing](https://dsva.slack.com/archives/C05SUUM4GAW) - This is the channel for ARF and stakeholders. Most of our communications are in here. The only thing we try to avoid in here is discussions that aren't ready for broader feedback.
- [x] [OCTO Slack channel #benefits-accredited-rep-design](https://dsva.slack.com/archives/C0643ADPP60) - This is the private chat space for ARF design/research and ARM design/research. We talk about design-specific topics and it's a "safe space" that Lesley created for our discussions.
- [x] [Ad Hoc Slack channel #proj-vso-accredited-rep](https://adhoc.slack.com/archives/C068FLMB26M) - This is managed by Agile 6 and just the ARF team and a few internal stakeholders from the contracting company side. We use for program management type things and conversations we want more private to the team.
- [x] [Personal chatter channel #vso-watercooler](https://app.slack.com/client/T025UGMV9/C067MEL18HK) - This is private to the team to share fun, non-work updates and photos.
- [ ] Check with Harold that you're included in the @arfdesign handle on OCTO Slack. 

### Add recurring meetings to your calendar
Most of these were outlined in the onboarding documentation already provided. Please check with Mike or Harold to make sure you are added to team ceremonies.

### Share your calendar 
- [ ] Please share your calendar ([instructions to share calendar](https://support.google.com/calendar/answer/37082?hl=en)) with your teammates.
- [x] Please reach out to Harold Baines to be added to ARF's team calendar (va-vso_arft@agile6.com). This is where all-team meetings and PTO are shared. 

## File sharing
- [ ] Request permission to view the [VSO Team Drive folder](https://drive.google.com/drive/folders/0AHtMEJhzWhvjUk9PVA).
- [ ] Request permission to the Benefits Portfolio Sharepoint and [ARF's team folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing?csf=1&web=1&e=nBcDcq).
- [ ] Request permission to join the VA Mural space.
- [ ] Request permission to edit Figma files in the [Accredited Representative project](https://www.figma.com/files/project/176208173).

## High-Level Project Overview

ARF is tasked with building tools for accredited representatives—individuals approved by VA to assist Veterans with their claims. Our work has evolved dramatically since the start of our contract, but it can be loosely grouped into 3 projects: 
- Form 21a/accreditation (Kristen is the lead designer on this project)
- Representative contact updates with OGC (Danielle and Ben are the lead designers and researchers on this project)
- Form 21-22/Power of Attorney (Michael is the lead designer on this project)

You'll find resources specific to each project below, but first, start by learning some general team information:
- [ ] **READ** [What is an Accredited Representative?](https://www.benefits.va.gov/vso/) (VA.gov)
- [ ] **READ** and learn about relevant terms and phrases:
   - [ ] [ARM glossary of terms and their definitions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/terminology-definitions.md) (Github; note that Accredited Representative Management [ARM] is our sister team that works on similar products, but for the Veteran-facing experience.)
   - [ ] [ARF team jargon](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/product-info/team-jargon.md) (GitHub)
- [ ] **READ** our personas Mural boards:
   - [ ] [VSO representatives](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709236473099/7a69ce07dbe58af30f1954470bebbe59b7bf1160?sender=u8cf3f08a008c2b61ad621433) - Employed and accredited through a Veterans Service Organization, they provide free, individualized support for Veterans throughout their claims process. 
   - [ ] [Accredited attorneys](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717533456497/60064424f651818203ff49ac43d6fb9f0f2bccac?sender=u8cf3f08a008c2b61ad621433) - Specialists in Veterans law, they provide individualized support for Veterans seeking benefits by preparing, presenting, and prosecuting claims before VA.
   - [ ] [Accredited claims agents](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718731869465/cf73b89eddb92c604d292554a31e503f7ce5d982?sender=u8cf3f08a008c2b61ad621433) - Independent legal professionals who are not attorneys, they provide individualized support for Veterans seeking benefits by preparing, presenting, and prosecuting claims before VA.
- [ ] **SCAN** Our [Current State Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ucd326fb05b27d09e40350092), which shows various flows accredited representatives undertake. We haven't updated this recently, but it's still relevant to our work. 

## Background Research
- [ ] **WATCH** [Secondary research literature overview](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/stream.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FAR%5Fsecondaryresearch%5Fpreso%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview) (Sharepoint; if this link doesn't work, follow this Sharepoint folder path: Accredited Representative Facing > POA 21-22 > 00 Past Research > mp4 file). This discusses what research has been done on VSOs and where there are gaps in knowledge. This is an overview recording of [this report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/fc4cf2841f56caea6bb66502b29a4ef1cf25abde/products/accredited-representation-management/research/2023-09-secondary-research/2023-09-secondary-research-accredited-representation-management.md) (GitHub). I would recommend starting with the recording and looking at the report or the Lighthouse research as needed to fill in knowledge gaps; a deep-dive is not necessary.
- [ ] **SKIM/BOOKMARK** for later: [VEO/Lighthouse research on VSOs](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research) (GitHub). Much of this is covered in the secondary literature review, and learnings have been added to in-progress research artifacts.

### Contact information updates
- [ ] **READ** the [Contact Info Updates Resources doc](https://docs.google.com/document/d/1jNf8Xa9HkDgWAfexjcttyGvsu3FOEVRG4qq6rcA0Og8/edit#heading=h.afkbrrz4ptec) and the links within it to get an overview of the project. Reach out to Danielle and Ben with questions. 
- [ ] **READ** the [August 2024 Contact Information Updates user research content](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representative-facing/research/2024-07%20OGC%20Contact%20Information%20Updates). As of August 26, the report has not yet been written. For now, review the [research Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722968980539/8ff88ec576db19a80a13e1f09f5faccf62a86a66?sender=u8cf3f08a008c2b61ad621433) and sync with Ben to learn about its current state. 
- [ ] **REVIEW** the [Contact Info Updates Figma file](https://www.figma.com/design/RbVQnV4eBl2K1Z5xRpZi7H/Contact-Info-Updating?node-id=0-1&t=IRpP8awowpy8jUgM-1). 

### Form 21a/accreditation
- [ ] **READ** the [21a Resources doc](https://docs.google.com/document/d/1wJBXsWjCtqMK27Yzy8xZMFCTT4k_aajY4mOZ2CB8fh0/edit) and the links within it to get an overview of the project. Reach out to Kristen with questions.
- [ ] **REVIEW** the [21a Figma file](https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=616-23089&t=pMZkIcaOxz5wZfRc-1). 

### Form 21-22/POA
- [ ] **READ** the [21-22 Resources doc](https://docs.google.com/document/d/1drwU7dTnLoQoYWCQUzczSD59ncKdE9wu3528y_eAQIY/edit) and the links within it to get an overview of the project. Reach out to Kristen with questions.
- [ ]  **REVIEW** the [21-22 Figma file](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Design-Explorations?node-id=1-6972&t=qXCE7sGn8mr4czwy-1). 

Because our team has been working the longest on this project, we have the most research and resources on this project. Those are listed in the sub-sections below. 

#### Stakeholder Enterprise Portal (SEP)
The way VSOs currently accept power of attorney is through the Stakeholder Enterprise Portal (SEP). Learn about SEP through these resources:
- [ ] **WATCH** [SEP Walkthrough with Disabled American Veterans (DAV)](https://dvagov.sharepoint.com/:v:/s/vaabdvro/Ee3gR_HqQ45CnY4OO5URNgYBJ-4haXSIx60F8Mmwz0MzPw?e=uJTLu9&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D), one of the "big 6" VSOrgs (Sharepoint).
- [ ] **WATCH** the [SEP Demo](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/SEP%20Demos/SEP%20Demo%20with%20CTO-20231208_111227-Meeting%20Recording.mp4?csf=1&web=1&e=a3abDH) (Sharepoint; if that link doesn't work, follow this Sharepoint path: Accredited Representative Facing > POA 21-22 > 012024 Current State Analysis > SEP Demos > the one with CTO) with the VEO team behind the tool. Note that these are SMEs we interviewed ([Link to research plan in Google Doc](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit)). 
- [ ] **SCAN** The [screen-by-screen SEP demo deck](https://docs.google.com/presentation/d/1aDd9MVh-fg8bl040WeEAX_-0sZBnTntkgfhl1LEGxbg/edit#slide=id.g26c8e1bc7fa_0_43) we created to reference SEP UI (Google slides).
- [ ] **SCAN** SEP-specific [existing research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695929155059/a302158eccec694ec7089bd6a02954421721987d?sender=ua71936780d8bc9a2d2b29830) (Mural). Some of these resources overlap with the literature review and the recordings linked elsewhere in this ticket. The research reports about SEP are very interesting!
- [ ] **EXPLORE** SEP and eBenefits with these [login credentials](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7BD10426C1-A013-4818-9B90-1A213E83DA01%7D&file=SEP%20Account%20For%20Testing.xlsx&action=default&mobileredirect=true) (Sharepoint).

#### 21-22 User and SME Interviews
- [ ] **WATCH** [SME Interview](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/stream.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FResearch%2FSME%20Interviews%2FMarty%20Caraway%20%2D%20recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview) with Marty Caraway, VSO liaison (Sharepoint; if that link doesn't work, follow this Sharepoint path: Accredited Representative Facing > POA 21-22 > SME Interviews > Marty Caraway)
- [ ] **WATCH** [Accredited Representative listening session](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/01-23-24%20Representative%20Listening%20Session/Recording?csf=1&web=1&e=cRufIR) (Sharepoint; if that link doesn't work, follow this Sharepoint path: Accredited Representative Facing > POA 21-22 > 0124 Representative Listening Session > Recording) 
- [ ] **REVIEW** the [Jan 2024 Listening Session report](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representative-facing/research/2024-01%20Listening%20Session) (Github). This summarizes the video directly above.
- [ ] **WATCH** at least 1 of these [earlier VSO interviews](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QIRHZa&cid=866978cd%2D2497%2D496e%2Dadae%2D42c02258162e&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FRecordings&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72) (Sharepoint; if that link doesn't work, follow this Sharepoint path: Accredited Representative Facing > POA 21-22 > 00 Past Research > Recordings ). Notes are in the Existing Research Mural and there is a lot of overlap with these interviews and the walkthrough, so no need to go too in-depth. You can save this task for later if you're short on time.
- [ ] **READ** the [Feb 2024 User Interviews report](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representative-facing/research/2024-02%20User%20Interviews) about how VSOfficers interact with SEP and what they hope our new tool can offer. 
- [ ] **READ** the [March 2024 Single Accredited Testing report](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representative-facing/research/2024-03%20Single%20Accredited%20Testing). This was a test in which we ran a prototype past VSO reps who are accredited with a single organization. 
- [ ] **READ** the [May 2024 NACVSO report](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representative-facing/research/2024-05%20NACVSO). NACVSO stands for National Association of County Veterans Service Organizations. Some members of our team were able to travel to their conference in May to test prototypes and ask questions of VSOs in person. This report sums up that research. 

## Future State 
- [ ] **REVIEW** the [ARF Project Visualization](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704824541218/8f0b5512ee478f78e6df1597ff9ab7230ec82df2?sender=ucc14575938bb14be79634773) (Mural), which contains some wireframes. Note that these have since been updated and moved to Figma (linked to below), but this will give you some grounding for how our designs have evolved. 

## UI Files 
- [ ] **REVIEW** [VA Design System](https://design.va.gov/)
- [ ] **REVIEW** [VA Figma component library](https://www.figma.com/file/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?type=design&node-id=121%3A1484&mode=design&t=Hu7ewqOYg1wv2Egn-1)
- [ ] **REVIEW** the Figma files for the 3 main projects (these can all be found in the [Accredited Representatives Figma project](https://www.figma.com/files/project/176208173). They are linked to under their respective project headers above, but listed together here for convenience:
   - [ ] [Form 21a / representative accreditation](https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=616-23089&t=pMZkIcaOxz5wZfRc-1)
   - [ ] [Contact Information Updates](https://www.figma.com/design/RbVQnV4eBl2K1Z5xRpZi7H/Contact-Info-Updating?node-id=0-1&t=IRpP8awowpy8jUgM-1)
   - [ ] [21-22/Power of Attorney](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Design-Explorations?node-id=1-6972&t=qXCE7sGn8mr4czwy-1)

**Comment by jimuhh** [comment]
Test

**Comment by jimuhh** [comment]
READ What is an Accredited Representative? (VA.gov)
 READ and learn about relevant terms and phrases:
 ARM glossary of terms and their definitions (Github; note that Accredited Representative Management (ARM) is our sister team that works on similar products, but for the Veteran-facing experience.
 ARF team jargon (GitHub)
