### ISSUE TITLE
10-7959f-2: react widget/feature toggle

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91186]
- Create feature toggle - [Feature toggle guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) and provide name for release plan
- Create a React widget in vets-website for the dynamic content, per documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) and provide ID (to share with CAIA)
- name should be lower case

**Comment by baltes** [comment]
Closing this for now, we'll revisit all of these after f1 is sorted out
