### ISSUE TITLE
Add AVS parameter to appointments_service get_appointments

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#91198]
Through some recent triages with backend teams we had the idea to add a new "AVS" parameter to the get_appointments call on the appointment service in order to streamline the logic for when those calls are needed, and they can be skipped entirely for consumers who don't need them.

AC:
[ ] - add "avs" param to appointments_service get_appointments
[ ] - test updates

**Comment by ldelacosta** [comment]
No issues found. Closing out the ticket.
