### ISSUE TITLE
Replace dot indicator on My VA with badge indicator per design specs

### ISSUE THREAD

**Issue by ACParker89** [department-of-veterans-affairs/va.gov-team#91206]
### Background
We will be upgrading the dot indicator currently in production indicating unread messages in the health care section on My VA to be a badge indicator - that is an icon with a count telling the user how many unread messages they have.

### Tasks

- [ ] Update indicators based on [Figma Designs ](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=1744-27767&t=NCYUdza0BqJvVPeb-0) 

### Acceptance Criteria
 Badge indicator exists in code behind a feature flag
### Validation
Who can validate this ticket? (FE, BE, Design, PM)? Any team member
How can this work be validated? Confirm badge indicator is functional in staging behind a feature flag

**Comment by ajakabcin** [comment]
Closing - see #91205
