### ISSUE TITLE
Backend: Add "over 65" boolean value to 10-10d metadata

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#91221]
Related to frontend: https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/91216

As a Pega Backend analyst, I need to determine if any applicants in the form are over 65, we can introduce a boolean flag named hasApplicantOver65. This flag will be initialized to false and updated to true if an applicant with an age greater than or equal to 65 is found.

Acceptance Criteria: 
The boolean flag will be set to true if one or more applicants in the list loop are 65 years old or older.
This metadata will be added to all 10-10d submissions

**Comment by michaelclement** [comment]
[Associated frontend PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31531)

**Comment by cloudmagic80** [comment]
[Uploading... Screenshot 2024-08-28 at 1.00.16 PM.png]

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/18233

**Comment by cloudmagic80** [comment]
<img width="1042" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW1WQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1eda81d1a937ddf35d124f9e1110af9d36c99f0/Screenshot%202024-08-28%20at%201.00.16%20PM.png" alt="Screenshot 2024-08-28 at 1.00.16 PM.png" />
