### ISSUE TITLE
STEM Stand-alone, VA Form 22-10203 -- Design Intent Collab -- Accessibility Recommendations

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#9124]
## Accessibility Recommendations
I've broken out my recommendations by InVision URL because that felt like the easiest way to group things. I focused on places we could enhance accessibility through component reuse, calls to action, and aural announcements.

* https://bahdigital.invisionapp.com/share/MUIADS5R2HC#/screens/296036932
  * The "You may not be eligible" alert will need a `role="alert"` to announce to screen readers immediately. It's visually removed from the checkboxes, so we want to announce it without anticipating users will land on that information.
* https://bahdigital.invisionapp.com/share/MUIADS5R2HC#/screens/296036941
  * The background alert about receiving the scholarship while on active duty will need a `role="alert"` as well.
* https://bahdigital.invisionapp.com/share/MUIADS5R2HC#/screens/296036947
  * This feels really important, the two paragraphs of information if users select the **Stop direct deposit** radio button. Nielsen Norman Group's research [How Little Do Users Read?](https://www.nngroup.com/articles/how-little-do-users-read/) makes me wonder if we could raise awareness, especially the second paragraph outlining that users must get a waiver. Perhaps a heading for the paragraph or paragraphs that appear would help.
  * Adding an `aria-label` to the phone numbers for debit cards and the Treasury Dept. will help screen reader users parse the number.
    * That Dev Girl wrote a great article [Accessibility and phone number formatting](https://thatdevgirl.com/blog/accessibility-phone-number-formatting) that outlines our current recommendation. 
    * The design system has a PR pending for a centralized `Telephone` component: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/260 that would auto format these telephone numbers.
    * What do you think about making the debit card link and telephone link into list items? These links will likely be very close to one another and cause a small hit space for mobile users. Having them as a list with padding between items increases hit spaces for mobile / motor impaired users.
* https://bahdigital.invisionapp.com/share/MUIADS5R2HC#/screens/296036938
  * I think it would be better for the "Note: if you need help completing this form..." paragraph to be directly under the **Your STEM program** heading. It seems like a pretty important detail.

**Comment by dneel-bah** [comment]
> https://bahdigital.invisionapp.com/share/MUIADS5R2HC#/screens/296036932
> The "You may not be eligible" alert will need a role="alert" to announce to screen readers immediately. It's visually removed from the checkboxes, so we want to announce it without anticipating users will land on that information.

The prototype has been updated further, so this is OBE.  See new workflow prototype for reference
https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040836

**Comment by dneel-bah** [comment]
@1Copenut I believe all issues have been addressed, and the remaining item 11970 was put into the icebox.  Can this issue be closed?

**Comment by 1Copenut** [comment]
@dneel-bah Yes, I'll go ahead and close this now. Thank you for the heads up!
