### ISSUE TITLE
[LH Doc Upload] BDD production launch dashboard for monitoring

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#91269]
There should be a Datadog dashboard that will track the progress and automatically detect issues with Lighthouse API. 

In production we will simply duplicate the [staging dashboard we built for testing](https://vagov.ddog-gov.com/dashboard/gbu-ey4-ntt/upload-bdd-instructions-lighthouse-migration-staging?fromUser=false&refresh_mode=sliding&from_ts=1729005599461&to_ts=1729610399461&live=true) and tweak all of the queries to point at the production environment.

Acceptance Criteria
- [x] Matches the behavior of the staging dashboard
- [x] Conforms with all of the DataDog standards set out for all teams (see below)
- [ ] [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md)

**Datadog standards** ([from slack 7/24](https://dsva.slack.com/archives/C04KW0B46N5/p1721841520391079) )

- [ ] For monitors, tag them “service:disability-application”
  - For monitors we are more flexible with the titles because they double as the title of notifications that are posted in Slack - so starting everything with "Benefits - Disability Claims - etc" makes them less readable
  - An added benefit to using the service:disability-application tag is that it adds the monitor to the disability service overview found [here](https://vagov.ddog-gov.com/apm/services/disability-application/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&isInferred=false&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3Aall%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&view=spans&start=1721840782530&end=1721844382530&paused=true): 
- [x] Naming convention, consistently name Dashboards “Benefits - Disability- 526 - [details]" 
- [x] Use a shared, editable list that contains all of the Disability-related dashboards.
  - Steve created - [Benefits - Disability - 526](https://vagov.ddog-gov.com/dashboard/lists/manual/1735) (This can be renamed later if we feel there’s a better one to use.) 
  - Team members should add their dashboard to this shared list when they create new dashboards
  - Team members should check to see if any existing dashboards have been added and add them if necessary

**Comment by ajones446** [comment]
@NB28VT and @lisacapaccioli 
I checked off the criteria boxes I was able to complete today (using the standard naming prefix and adding the production dashboard to the shared list.)

A BDD monitor alert has not been set up yet, but I added the tagging criteria in the alert ticket to keep track of it. #95604

We don't send any emails for BDD, so I'm not sure what we need to do for the [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md). Do you have any ideas about what is required for BDD?

**Comment by lisacapaccioli** [comment]
@ajones446 @NB28VT Since BDD is not a ZSF concern (the Veteran doesn't need to know it failed) it won't need the ZSF tracking on it.  This one should just follow the standard naming conventions mentioned in the details above. I am not sure if there are any others since I haven't seen anything from Steve lately about new requirements for tagging and labeling beyond ZSF.

**Comment by ajones446** [comment]
Ok, thanks @lisacapaccioli! 

We also have a ticket for BDD to [Improve production monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95604) with acceptance criteria to check the ZSF mandate, so we can review it again during that task.
