### ISSUE TITLE
Yellow Ribbon - Review Query for Performance Issues

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9127]
As part of the privacy, security review for Yellow Ribbon, 

We need to:
* Dig into the query to see if there are any performance issues (pg_stat_statements). The BE support in #vfs-platform-support should be able to help you with getting information about (or access to) that. Related: which of those query fields are (or should be) indexed?

**Tasks**
- [ ] Review query for potential performance issues. If there are any found, we will want to discuss mitigation strategy & prioritization.

If issues are found, attach here so we can review for next steps. If no issues found, alert Stephanie and Andrew G.

**Comment by kelsonic** [comment]
Syncing with @annaswims on Monday to figure out tasks to complete this ticket 🙂

**Comment by annaswims** [comment]
All in all, it's looking like the performance of /gids/v0/yellow_ribbon_programs looks good in  [grafana](http://grafana.vfs.va.gov/d/000000050/backend-service-report?orgId=1&from=now-3h&to=now&var-service=GI&var-data_source=Prometheus%20(Production))

When I ran GIDS locally, it did look like they've got an n+1 query problem that they could fix, but I don't think it's enough that it should give your team trouble. 

<img width="1629" alt="Screen Shot 2020-05-18 at 5 14 01 PM" src="https://user-images.githubusercontent.com/19188/82260431-421c0f00-992b-11ea-8adb-949e365221a1.png">

**Comment by annaswims** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1589815209195400

pg_stat_statements were disabled for a while but were just re-enabled

**Comment by kelsonic** [comment]
Great news! Thanks @annaswims for digging into this!
