### ISSUE TITLE
[LH Doc Upload] BDD test environment testing end to end

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#91270]
Once the migration and the toggle switch are implemented we'll want to test the BDD document upload to Lighthouse before going to production. 

- [x] Test the dashboard
- [x] Test with the flipper/toggle enabled
- [x] Test with the flipper/toggle disabled 
- [x] Test "pending" status (when it's waiting to upload) - this might be harder if the process if fast 
- [x] Test successful completion (success status received)
- [x] Test failed to upload
- [x] Validate that the document is in the eFolder

**Comment by NB28VT** [comment]
This has been successfully completed as of last week
