### ISSUE TITLE
Remove distracting/unneeded links from MHV Landing Page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#91292]
### User story

As a Veteran, I want the Appointments and Messages boxes to have only two links each, so that distracting options are removed and I can find lower items more easily.

### Notes
- Appointments: lose "find a location" (redundant to links in header/footer)
- Messages: lose "Manage folders" 

Possible tasks:
- 

## Acceptance criteria

- Links are removed from the two boxes
- UXer review

**Comment by wesrowe** [comment]
Patrick confirmed with other stakeholders that we are good to go on this.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the two links in the description has been removed from the Appointments and Messages box on the MHV on VA.gov landing page

<img width="1261" alt="Screenshot 2024-09-12 at 11 20 13 AM" src="https://github.com/user-attachments/assets/d1a7e455-99e8-4508-9132-ea85f770108d">
