### ISSUE TITLE
Fix cosmetic issues with MHV secondary nav

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#91291]
### User story

As a Cartography team member, I want the implemented secondary nav to look exactly like the design in Figma, as we aligned on the pixel dimensions as the best presentation possible to Veterans.

### Notes
- Vertical alignment of icons/text within bar: right now, seems the text is a little higher than the vertical center

- Height of MHV home row on mobile: white bar is taking up more room vertically than looks right: height of white bar is 43 px and height of blue right under it is 67 for total of 110px height

- Padding above/below selected state: on desktop, the white selection rectangle is 43px high; on mobile, it is 59px high. Right now in staging the blue showing above and below the white selection rectangle is looking too thin (actually term should be short maybe)

- Radius on selected-item corners: radius could be bumped down slightly: on desktop, radius = 2; on mobile radius =4

- Icon size should be updated to align with USWDS icon sizes, so all icons should be 24x24p

#### Figma
<img width="219" alt="image" src="https://github.com/user-attachments/assets/e8f8bdac-169d-4d61-b601-152d6a09ffd3">

#### Staging
![image](https://github.com/user-attachments/assets/03d4713c-b836-4d70-bf37-e75b3a8203ba)

Possible tasks:
- Compare Figma file to V3 components
- Update the secondary nav components where there are discrepancies

## Acceptance criteria
- Update figma designs to v3 of VADS
- Implement design tweaks
- UXer review

**Comment by katbrinkley** [comment]
Est. 3 points

**Comment by dcloud** [comment]
Est 5 points

**Comment by sterkenburgsara** [comment]
Noticing that the shared component in Figma suggests a "small" (20pt) and "large" (24 pt) size option for iconography that is not supported by the design system sizes for icons. Only the "large" size (24pt) is possible in VADS, which maps to the smallest size 3. Logged into staging, where I am also only seeing size 3 no matter how i resize the screen. Recommend that we should update Figma to match this behavior, only using size 3 (if design fidelity still holds). 

Will connect with @fmccaf1 to validate & look into this & get her PoV before making updates in Figma. Other secondary nav cosmetic updates listed under "notes" in the ticket above still look valid though. Can identify specifics for devs if helpful (i.e. get a number for how rounded the corners should be).

**Comment by fmccaf1** [comment]
I think we're going to keep the smaller icon size (20px) for instances in which the icon and text are flowing horizontally (so, for desktop designs and other wider screens). I'll write a ticket to get DST's thoughts on keeping that smaller size even though it's not specifically sanctioned by v.3 of USWDS. The larger icon size (24pt) is for smaller screens, when the icon is sitting on top of the text.

**Comment by nichia** [comment]
Connected with @fmccaf1 and here is the list of code changes made with the MHV secondary navigation:
- vertically center the icons/text within MHV secondary nav bar
- Padding above/below selected state are changed so that:
  - on desktop, height of the white selection rectangle is 43px
  - on mobile, height is 59px
  - this change exposes more of the blue background above and below the white selection rectangle
- Height of MHV home row on mobile changed to:
  - white bar: 43px and
  - blue bar (below the white bar): 67px
  - this gives a height total of 110px
- Mobile view: Extend 'My HealtheVet' button to the full width of the screen
- Radius on selected-item corners:
  - desktop, radius: 2;
  - mobile, radius: 4
