### ISSUE TITLE
Adjust links to not use orphaned caret

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#91294]
### User story

As a Veteran, I want to be presented links on the MHV landing page without the distraction of arrows/carets that jump to a new line and make the content shift or look broken, so that I can focus on getting where I need to go.
<img width="319" alt="image" src="https://github.com/user-attachments/assets/606dc27c-4572-4459-8834-045b77f6827c">

About 5% of users (per GA) have a screen width that causes at least one orphaned caret.

### Notes
- (NOT relevant to MHV Home since we don't use DST component): Wes filed a [bug ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91872) with the DST.
- Ryan Thurlwell got the idea from VADS links that appear on the Benefit Hub landing pages – e.g. `/health-care/`
- In #89477 we determined a quick technical fix for the lonely wrapping carat is not available.
- Synced with Daniel on why we aren't using Design System links here – various reasons, including the mobile behavior of these links is different from the DS component
- These links-with-carets are apparently in the VADS as a sub-class of the "link" component, called "active link," [see here](https://design.va.gov/components/link/)
- Consider using mobile approach instead

Possible tasks:
- [ ] Edit desktop designs (well, designs for devices wider than 780 pixels) in Figma to utilize the mobile treatment & move caret to the end of the line instead of hugging the text. 
  - Do we need this? Or can we just send the info to devs?  
- [ ] Implement the change so that desktop & mobile operate the same way, with the trailing caret at the end of the line separated from the link text

## Acceptance criteria

- [x] UX identifies a way forward that doesn't involve wrapping carets and updates to the Figma design
- [x] Implemented the change
- [x] QA review
- [x] UXer review
- [x] A11y review

**Comment by katbrinkley** [comment]
UX est. 5
Eng est. 3

**Comment by fmccaf1** [comment]
Thinking UX estimate = 2

**Comment by sterkenburgsara** [comment]
Update: trying to keep this a light lift on our end, considering that we may want to pivot away from this design in the future anyway. Two options we are contemplating: 
* Pivot to using the VADS link component, sub-class style of "active link" instead of doing this in a custom way on our page
* Apply the mobile style to all screen widths to avoid the wrapping

**Comment by dcloud** [comment]
Per stand-up, we will make the mobile style the style on all screen sizes.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the carets on the MHV landing page has been adjusted to be mobile style. See attached video and screenshot

### Screenshot of mobile view 320 x 480
<img width="709" alt="Screenshot 2024-09-19 at 10 16 53 AM" src="https://github.com/user-attachments/assets/6b9869e6-0207-4810-a297-61ca77cf8dcb">

### Video of changing browser size
https://github.com/user-attachments/assets/717ee27d-0f69-49fa-87bd-65fab211860c

**Comment by allanto-ah** [comment]
Accidentally closed before asking for UX review. Re-opened and will close after UX review

**Comment by allanto-ah** [comment]
UX review signed off in this [slack](https://dsva.slack.com/archives/C0581MN69TJ/p1726769036993199) thread
