### ISSUE TITLE
Contact Center Review for [Disability Benefits Team 2 - Post-Submission Failure Emails]

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#91298]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Post-Submission Failure Emails

The Post-Submission Failure emails will be sent to Veterans when a document fails after they submit their 526 claim. One of the documents that can fail is VA Form 4142. Currently, there is no notification to the Veterans that the documents have failed. We have included updated language and an image regarding the Form 4142 failure email. The 4142 failure email would go out in the extremely unlikely event there is a problem with uploading a 4142.  

### Launch Date
*Please provide the launch or rollout date and details.*
We would like to roll out this product guide addition as soon as possible.

### Version Number
*Please provide the version number of the guide and/or video.*
These are new emails regarding an existing product.
- Compensation Claims Application  Benefits Delivery at Discharge Version 3.0
- Disability Benefits Compensation Claims Application Version 4.0

### Product Guide
- [526.Benefits.Delivery.at.Discharge.v3.0--.product.guide SRT NN Changes 8.26.24- In Progress (1).docx](https://github.com/user-attachments/files/16752211/526.Benefits.Delivery.at.Discharge.v3.0--.product.guide.SRT.NN.Changes.8.26.24-.In.Progress.1.docx)
- [526EZ Disability Benefits Claims Product Guide v4.0 SRT 07302024R - NN Changes 8.26.24 (2).docx](https://github.com/user-attachments/files/16752213/526EZ.Disability.Benefits.Claims.Product.Guide.v4.0.SRT.07302024R.-.NN.Changes.8.26.24.2.docx)

*Please provide product guide link*
- Compensation Claims Application  Benefits Delivery at Discharge Version 3.0
- Disability Benefits Compensation Claims Application Version 4.0

### Product Video
*Please provide product video link*
No video is included.

### Product Video Transcript
*Please provide product video transcript link*
No video is included.

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @nnicholas7. Do you have drafts that incorporate the new changes? The ones attached to this ticket appear to be copies of the previous version I sent earlier.

**Comment by nnicholas7** [comment]
Hi @starlow00 ! That's strange. I'm going to try the upload again. Let me know if you are still having an issue.
[526.Benefits.Delivery.at.Discharge.v3.0--.product.guide SRT 07312024 (1).docx](https://github.com/user-attachments/files/16716848/526.Benefits.Delivery.at.Discharge.v3.0--.product.guide.SRT.07312024.1.docx)
[526EZ Disability Benefits Claims Product Guide v4.0 SRT 07302024R (1).docx](https://github.com/user-attachments/files/16716849/526EZ.Disability.Benefits.Claims.Product.Guide.v4.0.SRT.07302024R.1.docx)

**Comment by starlow00** [comment]
Oh, wait. I think I may have just been going by the filename before. It looked unchanged, but I see it now.

From: Nichole Nicholas ***@***.***>
Sent: Thursday, August 22, 2024 12:47 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: TARLOW, STEVEN R. (ODDBALL INC) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [Disability Benefits Team 2 - Post-Submission Failure Emails] (Issue #91298)


Hi @starlow00<https://github.com/starlow00> ! That's strange. I'm going to try the upload again. Let me know if you are still having an issue.
526.Benefits.Delivery.at.Discharge.v3.0--.product.guide SRT 07312024 (1).docx<https://github.com/user-attachments/files/16716848/526.Benefits.Delivery.at.Discharge.v3.0--.product.guide.SRT.07312024.1.docx>
526EZ Disability Benefits Claims Product Guide v4.0 SRT 07302024R (1).docx<https://github.com/user-attachments/files/16716849/526EZ.Disability.Benefits.Claims.Product.Guide.v4.0.SRT.07302024R.1.docx>

-

**Comment by nnicholas7** [comment]
Hi @starlow00! Just want to note that there are some additions we want to add. I will make a note when the additions have been made and documents has been uploaded

**Comment by starlow00** [comment]
Okay, thanks @nnicholas7.

**Comment by nnicholas7** [comment]
My apologies @starlow00 for the confusion. The correct documents have been added to the ticket and are ready for review.

**Comment by starlow00** [comment]
Got it, I will proceed.

**Comment by starlow00** [comment]
Adjusted estimate to reflect review of 2 product guides.

**Comment by starlow00** [comment]
Drafts look good. Sent to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. Current copies are attached; please use them for revisions as we advance.

Please note that I used version numbers v4.1 (for the 526EZ guide) and v3.1 (526 BDD) because the last update to these already used 3.0 and 4.0.

[526.Benefits.Delivery.at.Discharge.v3.1.product.guide.SRT.08262024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWFRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acb36c92e54e641ec54db7627029a72e37d0df5d/526.Benefits.Delivery.at.Discharge.v3.1.product.guide.SRT.08262024.docx)
[526EZ.Disability.Benefits.Claims.Product.Guide.v4.1.SRT.08262024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0a26d6c39b7f25acd0777b315012371a87c5a33/526EZ.Disability.Benefits.Claims.Product.Guide.v4.1.SRT.08262024.docx)

**Comment by nnicholas7** [comment]
Good morning @starlow00 ! Thanks again for your help. We have another revision coming soon and will use the attached. I  will also change the version number on our Github page to reflect your note.

**Comment by lisacapaccioli** [comment]
Emailed reminder to CC 9/10/24.
