### ISSUE TITLE
Document discrepancies btwn DDog and GA4 for other teams

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#91290]
### User story

As a Cartography team member, I want to document the issues we've had with DD as a source of truth for user behavior, so that other teams can check our work and validate DD in their own apps.

### Notes

Possible tasks:
- Create visual / easy to communicate way of showing Robyn the discrepancies we're seeing for other teams between the two tools
- Will likely have back and forth w Robyn and will need to communicate with other teams

## Acceptance criteria

- [x] Checked on other team's (SM and Meds) data between datadog and GA4 to check for accuracy
- [x] Sent findings to Robyn

**Comment by wesrowe** [comment]
We shared our concerns with [Anne K-C via Slack](https://dsva.slack.com/archives/C0581MN69TJ/p1724854746281229?thread_ts=1724781060.279549&cid=C0581MN69TJ), and she ran a test and reported back that DD seems to be working correctly in SM and Meds tools.

**Comment by fmccaf1** [comment]
I pulled two weeks of SM data from both GA4 and data dog and documented some discrepancies here:
[Compare SM data on DD vs GA4.pdf(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFUyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--592f43d34dcd8fab4c3cbe3f7c48c9b357c23ff9/Compare%20SM%20data%20on%20DD%20vs%20GA4.pdf)

**Comment by fmccaf1** [comment]
Sent data comparison to Robyn who recommended I send to Anne CK. Anne responded by saying they're not looking at/pulling GA4 data right now so this is just going to sit there for now, not sure about next steps.
