### ISSUE TITLE
Access for Theresa McMurdo

### ISSUE THREAD

**Issue by tmcmurdo** [department-of-veterans-affairs/va.gov-team#913]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Doris Lin (meichih.lin@va.gov) < Out of office most of August. Back up is Debbie Lawson
- Please provide your name.
   > Theresa McMurdo
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BAH Team supporting Education on VA.gov (Comparison Tool, etc)
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw2I+dAcQCEoXTXSH/lnxArdhkjJD8YDRu6fP1Wh2OI/botOX5FqqbhdiZDw9wfIYZuxzAI/b69W+WvoQp4DS9kFmqXov/g4dIqXWt8+OFo/IH16IFt6GCEMB8XICd+vuyXy8LGJhHVTeX3BU7YIXUUzG994CUHgYL1rjXP0wCq724T8lRosPO/T0V/CbnLNyKOCZwymdYYiZcEGZf3RPUiPyuSfMTNG578W5fdHXbIR7qeRobMyI53U7L591/mevRjF3olTEUmQ1rOa2dtaS4DgYVf7bThv+ltWhimzvrR94W8TTtPgxY5TaCXOhDl75+Ls/jhOhx0eZsDXjMhE33 tmcmurdo@vcg-tmc-mac

- [Grant AWS Console access?]
  > YES 
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by b00klegger** [comment]
@Jeff-Hayter 
COR: Doris Lin (meichih.lin@va.gov) < Out of office most of August. Back up is Debbie Lawson
User: Theresa McMurdo

**Comment by desireeturner** [comment]
@department-of-veterans-affairs/vsp-operations this issue is ready for your review. Please let myself or @tmcmurdo know if any additional information is needed. Thank you!

**Comment by Jeff-Hayter** [comment]
@b00klegger Confirmed.  Please grant access.

**Comment by b00klegger** [comment]
AWS console access details forwarded via Slack and SSH key deployed to infrastructure. Closing ticket. If you experience issues please reopen and update.
