### ISSUE TITLE
Design feedback - Design intent Collaboration: STEM Stand-alone, VA Form 22-10203

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#9130]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**

- For address blocks,  use the address block we have in the sketch library. The city and state fields should be stacked 

**Try:**

- On the confirmation page, we can follow [VSA’s design](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/412943896) for the print button  (the “Go back to VA.gov” button should be blue too)

**Consider:**

- For the CIP code, consider asking  conditional questions so that the user is “led” to the code vs. having to search for it 

**Definition of Done:**
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by ccruzgra** [comment]
@CrystabelReiter The do/try updates were incorporated. Feel free to close the story!

**Comment by CrystabelReiter** [comment]
@ccruzgra Thank you!
