### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by cgeorge351** [department-of-veterans-affairs/va.gov-team#91319]
### Name

Christopher George

### Email

cgeorge351@github.com

### Role

Sr. Account Executive

### Team

Revenue

### Additional Notes

Need access to Figma for strategic account planning and access to product mapping to reference when working with clients

**Comment by naomimarcussen** [comment]
Hi! Could you provide a company or va.gov email address?

**Comment by cgeorge351** [comment]
Ah I think I opened this issue in the wrong area... I'm enterprise sales in the public sector

**Comment by naomimarcussen** [comment]
No worries. This Figma instance is only for design of Veteran-facing services on va.gov.
