### ISSUE TITLE
Investigate root cause of the new failing submissions

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#91325]
3 remaining in 'failure type' state. attempting to resend them to the backup path has not worked, failing with the same EVSS502 error (yes, on the backup path). 

[[2927910,
  ["1721752973",
   {"timestamp"=>"2024-07-23T16:42:53.537Z",
    "error_class"=>"Common::Exceptions::BackendServiceException",
    "caller_method"=>"error_hash_for_job_status",
    "error_message"=>"BackendServiceException: {:source=>\"EVSS::DisabilityCompensationForm::Service\", :code=>\"EVSS502\"}"}]],
 [2937715,
  ["1722014351",
   {"timestamp"=>"2024-07-26T17:19:11.962Z",
    "error_class"=>"Common::Exceptions::BackendServiceException",
    "caller_method"=>"error_hash_for_job_status",
    "error_message"=>"BackendServiceException: {:source=>\"EVSS::DisabilityCompensationForm::Service\", :code=>\"EVSS502\"}"}]],
 [2940375,
  ["1722092711",
   {"timestamp"=>"2024-07-27T15:05:11.683Z",
    "error_class"=>"Common::Exceptions::BackendServiceException",
    "caller_method"=>"error_hash_for_job_status",
    "error_message"=>"BackendServiceException: {:source=>\"EVSS::DisabilityCompensationForm::Service\", :code=>\"EVSS502\"}"}]]]

- [ ] remediate these with a dump
- [ ] investigate the cause of the failure

The saftey net for these will remain as 'failure type' forever, until we manually fix them, therefor there is no need to track the submission IDs. Once the logging goes out these ids will be part of our ongoing 'failure type' roundup.  In the meantime, I just know how to query for them (basically using the weekly report logic, which is in github)

[Slack](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=75558456)

https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=75558456

**Comment by SamStuckey** [comment]
UPDATE: this is now up to 15 failures

**Comment by SamStuckey** [comment]
UPDATE: just attempted to resubmit the (now 18) failing submissions from the past 2 weeks. here are their IDs and the reasons the API rejected them

```
[[3046410, "Unprocessable Entity"],
 [3046457, "Unprocessable Entity"],
 [3046573, "Unprocessable Entity"],
 [3046581, "Unprocessable Entity"],
 [3046589, "Unprocessable Entity"],
 [3048628, "invalid date"],
 [3048632, "invalid date"],
 [3049044, "invalid date"],
 [3049260, "Bad request"],
 [3049271, "Bad request"],
 [3049273, "Bad request"],
 [3049578, "Bad request"],
 [3050856, "Bad request"],
 [3050970, "invalid date"],
 [3050978, "invalid date"],
 [3050985, "invalid date"],
 [3051016, "invalid date"],
 [3051392, "Unprocessable Entity"]]
```

**Comment by SamStuckey** [comment]
UPDATE: we are down to 17 failing submissions. Here are the details

```
# get failures from the last 2 weeks
all_fubs = Form526Submission.failure_type.where(submitted_claim_id: nil)
at = Form526Submission.arel_table
cutoff = 2.weeks.ago.beginning_of_day
fubs = all_fubs.where(at[:created_at].gt(cutoff))


# attempt resubmission
report = { success: [], errors: [] }
fubs.each_with_index do |sub, idx|
  puts "\n\t processing submission #{sub.id} :: # #{idx} of #{fubs.count} \n"
  Sidekiq::Form526BackupSubmissionProcess::Processor.new(sub.id).process!
  report[:success] << [sub.id]
rescue => e
  report[:errors] << [sub.id, e.message]
end
puts "\n\n done \n\n"

# print_results
{:success=>[[3046410], [3046457], [3046573], [3046581], [3046589], [3051392]],
 :errors=>
  [[3048628, "invalid date"],
   [3048632, "invalid date"],
   [3049044, "invalid date"],
   [3049260, "Bad request"],
   [3049271, "Bad request"],
   [3049273, "Bad request"],
   [3049578, "Bad request"],
   [3050856, "Bad request"],
   [3050970, "invalid date"],
   [3050978, "invalid date"],
   [3050985, "invalid date"],
   [3051016, "invalid date"],
   [3052116, "invalid date"],
   [3052182, "Bad request"],
   [3052224, "Bad request"],
   [3055248, "Bad request"],
   [3055335, "Bad request"]]}
```

**Comment by SamStuckey** [comment]
BLOCKED: further remediation is blocked by Lighthouse API errors which @sethdarragile6 is investigating.  [slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1726156247371679?thread_ts=1725658206.639699&cid=C02CQP3RFFX)

**Comment by SamStuckey** [comment]
@lisacapaccioli we should probably rename this something like 'ongoing remediation'
