### ISSUE TITLE
Create StatsD counter for submission status

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#91327]
## Value Statement

Create a StatsD counter tracking the status of each submission as it changes.

Options could be:
- One counter with a tag value for each status
- One counter per status

---

## Background Context

- This will allow for a dashboard of statuses
- We can alert on error statuses

## Outcome, Success Measure, KPI(S), and Tracking Link

- A StatsD (or many) that track the changing status counts of each submission

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/18177 merged

**Comment by dfong-adh** [comment]
Staging verification done, will verify in production once deployed

**Comment by dfong-adh** [comment]
Verified in production.
