### ISSUE TITLE
DRAFT [Spot Check Request] Education Rates Content Rewrites (May 2020)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9135]
This ticket is WIP. Please do not act on it until it has been completed. When it is completed, "DRAFT" will be removed from its title, Assignees will be attached, and the request will be submitted.

### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review)

## Team Name

vsa-public-websites

## Product/Feature Name

Education Rates Rewrites

## Product description

As a Veteran considering or actively using the GI Bill and other VA education benefits, I want to quickly and easily see exactly how much tuition my benefits cover for different types of education and training, and how much money I can get for additional needs like housing and books.

## Review stage

- [ ] **Development intent review** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.

- [ ] **Spot check review** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

- [ ] **Other:** Please indicate what you're requesting

## Point of contact

Stephanie Orkand - PM
Danielle Thierry - Content Lead
Randi Hecht - Copy Editor
Anne Hurley - Content Writer

## Staging URL and credentials

The edits are in Drupal Preview on production. 
Pages for Review
[Education rewriting restart: Montgomery GI Bill - Active Duty (Chapter 30) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8634)
[Education rewriting restart: Post-9/11 GI Bill (Chapter 33) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8593)
[Education rewriting restart: Post-9/11 GI Bill monthly housing allowance rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8638)
[Education rewriting restart: Survivors' and Dependents' Educational Assistance Program (Chapter 35) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8637)
[Education rewriting restart: Post-9/11 GI Bill Resident Rate Requirements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8639)
[Education rewriting restart: Montgomery GI Bill - Selected Reserve (Chapter 1606) rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8635)
[Education rewriting restart: $600 buy-up program rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8636)
[Education rewriting restart: 2020 VA education benefit rates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8592)
[Education rewriting restart: Compare education benefits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8640)
[Education rewriting restart: Apply to restore GI Bill benefits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8641)

**Comment by laflannery** [comment]
@DanielleThierryUSDSVA This is another issue I found in my review, it's labelled Public websites but based on the description I think it might actually be Sitewide Content.  Let me know and I can update the labels.  Thanks!

**Comment by RLHecht** [comment]
This is a super old ticket. Closing! We got accessibility feedback on the rates work in our staging review and are submitting and 508 office audit request. Can close this!
