### ISSUE TITLE
Qualitative Data Request.

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#91366]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

08-01-2023

### Date Range End

07-31-2023

### Product Name(s)

10-10EZ, 10-10EZR, 10-10CG

### Product Description

10-10EZ - Veteran health care application to apply for VA health care
10-10EZR - Veteran health info update form to update personal information to their health enrollment record
10-10CG - Program of Comprehensive Assistance for Family Caregivers application for Caregivers to register with VA and receive specific benefits

### Survey URL(s), key term(s), case category or type

This request is for the call center data, previous requests were for Medallia survey data.

<Category | Case type>
Navigation Issues | Healthcare Application
Application Submission Issue | Healthcare Application
Upload/Download Documents | Healthcare Application
Inaccurate or Missing Information/Status | Healthcare Application
Feedback | General Feedback
Directory Assistance | Health Eligibility and Enrollment VHA

Key terms: health care, healthcare, caregiver, health update, health care update, enroll, enrollment, priority group, health benefit, health application

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

heather.justice1@va.gov; luis.simauchi@va.gov; alexander.seelig@va.gov; emily.brown8@va.gov; lois.lewis2@va.gov; Patrick.bateman@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared, the requested data for MYVA411. In MYVA411 disability claim case type, we usually see the 10-10EZ cases. I pulled everything under the disability claim just to make sure, we do not miss the cases. Let me know if you have any questions. Thank you.
