### ISSUE TITLE
CT-EYB: Create E2E Tests for Mobile CT Profile

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9136]
As a developer, I need to create end to end tests for the mobile view of the comparison tool profile so that the functionality can be regression tested as new functionality is developed.

## Assumptions:
1. We're using Cypress for these tests.
2. The test sets the screen width to 481px or less.
3. Axe checks are performed.
4. Additional search results testing will be in a new story once new search button is added.
5. The bottom sheet is not covered in these tests.
6. A follow-on story will cover the estimate your benefits functionality. 

## Acceptance Criteria:
1. A mobile end to end test exists and passes. Tests cover the following searches:
   a. VET TEC
   b. Chapter 33 (to represent non-VET TEC)
2. The test covers the navigation required to reach the profile page (landing page and search results).
3. Axe checks are executed on the search results filters display on mobile.
4. Axe checks are executed on the profile page.
5. Axe checks are executed on the landing page.

## Tasks
- [ ] QA observes the tests execute to ensure they hit all of the things we intend to test

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14296

**Comment by sonntag-adam** [comment]
Merged. Testing passes QA
