### ISSUE TITLE
Pre-entry Covid Screener URL Request

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9137]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
The CTO health products team is rolling out a nationwide screener to be used by VHA facilities at entry points. The screener will ask all prospective entrants a series of questions designed to identify covid symptoms or exposure to the novel coronavirus. Users will enter the screener by either: (1) navigating directly to the va.gov URL; (2) texting an SMS five-digit short code and receiving the va.gov URL back; or (3) scanning a QR code that will load the va.gov URL. At the end of the screener, the user will be given a status which will be used at a human-staffed check point to determine if the user needs additional screening.

We view this simple screener as the first step towards moving parts of the outpatient or on-campus experience into digital channels. In particular, we want to ensure that veterans/patients and their caregivers who would not normally interact with VHA digitally have a delightful experience and become more interested / less hostile to digital channels.

Additional details are [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/product-brief.md).

### Requestor team info
Patrick Bateman (CTO Health Products)

### Implementation date
Date new URL(s) will be live: Tentatively 5/19

Please indicate when the redirect(s) needs to be implemented"
- [ ] ~On the same date the new URLs launch~
- [ ] ~Can happen within 1-5 business days after new URLs launch~
- [ ] ~Other - Please indicate timing :~

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

N/A

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by stephorkandatx** [comment]
@batemapf any additional work needed from the PW team for this?

**Comment by mnorthuis** [comment]
This was an unnecessary ticket that I forced @batemapf to create.   No work for anyone to do here, his team will launch the URL when they launch the tool.  Closing issue.
