### ISSUE TITLE
10-7959f-1: react widget changes (CAIA edits) for staging review

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91382]
On version:
- make "Register for the Foreign Medical Program" primary link 
- by "By mail" header - "mail" should be lower case
- use address block formatting for the address
- add period at end of fax number sentence ("Fax your completed form...").
- make "Get VA form..." secondary link

Off version:
- make "Get VA form" primary link 
- make "Upload your completed form" secondary link

Original [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/89394) with copy provided from CAIA

**Comment by marywang2** [comment]
cc @laurwill

**Comment by reiting** [comment]
I have made a PR for th is and it is in team review.

**Comment by reiting** [comment]
This is now in platform review.

**Comment by reiting** [comment]
This has been approved and merged. It should be in staging in a few hours.

**Comment by reiting** [comment]
@marywang2 this should be in staging at this time.

**Comment by marywang2** [comment]
@reiting can we update the link styles to match the screenshots [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88012#issuecomment-2256789193)? Also can we turn the widget 'on' for staging review and so CAIA can review as well? Thank you!

**Comment by marywang2** [comment]
@reiting For the 'on' side, we'll need to make these edits (please review the screenshots in the link above):
- the first link under "Option 1: online" should be a green primary action link
- the second link is correct
- the third link under "Option 3: by fax" should be a regular text link, like the second link
-  missing a line of text above the address block — it should say "Mail your completed form to this address:"

**Comment by reiting** [comment]
Most recent changes are in platform review.

**Comment by marywang2** [comment]
@reiting not sure if you want to backlog this (which is fine too) but just tracking that for the 'on' side - change period to colon at the end of the sentence "Mail your completed form to this address:"

**Comment by reiting** [comment]
This has been merged, and should go out with the daily deploy today. You'd have to review the widget with someone to see the change, but here is a screenshot to show that I DID change it: 

<img width="1305" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZ6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58f7212a57aa28fc9c25dd08e266c6c3b61600c8/Screenshot%202024-09-05%20at%2011.29.51%E2%80%AFAM.png" alt="Screenshot 2024-09-05 at 11.29.51 AM.png" />
