### ISSUE TITLE
[CDP] Build a pay.gov compatible account number

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#91391]
## Description

[We need to generate a pay.gov compatible account number](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87678) so the frontend can display it to the veteran. This will make it easier for the vet to enter their information on pay.gov.

Both Vista and Cerner stations CCPC is sending 16 digits to VBS. VBS is sending those 16 digits to VODA. Those 16 digits make up the information needed for the first 4 parts of the information required for the pay.gov breakdown.  (see pink color on charts below) 

BE needs to breakdown the account number like so:

- Separate the 16 digits into four parts (part 1=3 characters, part 2= 4 characters, part 3 = 4 characters, and part 4 = 5 characters).  
- For the fifth part, the first 5 characters (or less) of the veteran's last name needs to be presented to represent part 5

![image](https://github.com/user-attachments/assets/e6bc7810-1536-4969-a399-5da90a7c2fe2)

Here are the [updated mockups in Figma](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=117-27779&t=KkrF6YXWL23qGjaw-11) and have added the above table as annotations. 

<img width="1091" alt="Screenshot 2024-08-29 at 2 25 33 PM" src="https://github.com/user-attachments/assets/197ca632-365d-480f-8171-9ba6f0c48862">

## BE Tasks
- [x] Format account number for VistA and Cerner based on the requirements from the table above
- [x] Send this updated format to FE to display in debt portal

## FE Tasks
- [ ] Coordinate with Design to ensure appropriate display
- [ ] Coordinate with BE to establish fallback values
- [ ] Update account number display for **Copay Detail** page 
- [ ] Update account number display for **HTML Statement** page
- [ ] Update associated unit test(s)
- [ ] Update associated e2e test(s)

## Design and BE sync on implementation of account number
- [x] Required (sync with @josephrlee)
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [ ] New formatting has been applied to account number
- [ ] FE has new format and it's been applied to Copay Detail and HTML Statement pages
- [ ] PR for updates have been merged

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
All the work left is on the FE portion - BE is complete.

**Comment by Dr-Pongo** [comment]
Updated FE task list to include coordination with everyone

**Comment by dhill802** [comment]
Bug - Account number not showing on the statement page [#97211](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97211) should fix this. @Dr-Pongo Please add details and close ticket if you can. ty!

**Comment by Dr-Pongo** [comment]
- Going to close out, as the work to generate the account number has been completed, and the work in the following bug fix ticket includes the new generated account number
department-of-veterans-affairs/va.gov-team/issues/97211
