### ISSUE TITLE
STEM: Prototype Updates - VSP / EDU

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#9139]
Update MVP prototype and content based on 5/14 input from VSP Design Intent Mtg and EDU requirements mtgs. 

Notes from VSP
Accessibility: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9124
Design: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9130

Also contact VSP content (Peggy) re:
* Modifications to subway map
* Potential new language around Direct Deposit

**Comment by amyknox** [comment]
Updated info on Direct Deposit https://www.va.gov/change-direct-deposit/

**Comment by ccruzgra** [comment]
New prototype updates are here (v0.1):
https://bahdigital.invisionapp.com/share/AUIADV5GTC2

Github content doc is being updated here: https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md
