### ISSUE TITLE
Travel Claim Details page v.1

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#91408]
## Description
UPDATE WITH @micahtaylor  - First version of the Travel Claim Details page focuses on minimum amount of information.  Include only what is currently supported in the claim card on the status page.  

## Acceptance Criteria
- [ ] 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic**

**Comment by micahtaylor** [comment]
This design is completed and can be seen [here](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=4060-3843&t=5TII6yjOhopnRC1I-4)
