### ISSUE TITLE
10-7959f-1: content updates (Name and home address screens)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91416]
Text removal request per CAIA as potentially confusing to user:
- Name and DOB screen ([url](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/veteran-information))
  - remove explanatory text below header "We use this information to verify..."
- home address screen ([url](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/home-address))
  - remove explanatory text below header "This is your current location..."
<img width="1184" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9GQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da7223a60462951d04cd6cbd259c53cf2d417259/Screenshot%202024-08-24%20at%208.05.02%E2%80%AFPM.png" alt="Screenshot 2024-08-24 at 8.05.02 PM.png" />
  <img width="1126" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed69cf9ab4e2e4c7b09551f5c83f89d40ba12099/Screenshot%202024-08-24%20at%208.06.36%E2%80%AFPM.png" alt="Screenshot 2024-08-24 at 8.06.36 PM.png" />

**Comment by reiting** [comment]
This is in platform review.

**Comment by reiting** [comment]
This has been approved and merged. It should be in staging in a few hours.

**Comment by reiting** [comment]
<img width="805" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f2780ac98dac986ad8ee634e649180f6ef9656e/Screenshot%202024-08-26%20at%208.56.50%E2%80%AFAM.png" alt="Screenshot 2024-08-26 at 8.56.50 AM.png" />
<img width="748" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0NOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--924d3f1703dfd5cce0cb45545ff0d3020f86af52/Screenshot%202024-08-26%20at%208.56.15%E2%80%AFAM.png" alt="Screenshot 2024-08-26 at 8.56.15 AM.png" />

**Comment by reiting** [comment]
@marywang2 this should be ready for review in staging.
