### ISSUE TITLE
Collaboration Cycle Kickoff [VERA CVPS, new product: VERA]

### ISSUE THREAD

**Issue by JonathanPostMO** [department-of-veterans-affairs/va.gov-team#91456]
### 1. Will your work result in visible changes to the user experience?
We're moving the regional office (VARO) meeting scheduler, [VERA](https://va.my.site.com/VAVERA/s/) ("visitor engagement reporting application"), a salesforce application, to va.gov. This will include integration with third-party and VA-owned systems, as well as a visual overhaul in order to meet OCTO standards & guidelines. 

### 2. Are you doing research with VA.gov users?
We'd like to do research (usability testing and potentially a card sort exercise for the "select services" page), but we're not sure how much we could do based on timelines and contractual obligations.

### 3. Will your work involve changes to: (select all that apply)
- [x] Tools, applications and dynamic pages*
- [ ] Static pages**
- [ ] Both
- [ ] Other

*For tools and applications, take into account if any static page entry points will need updates.
**Please review the [Static vs Dynamic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md) guidance.

### 4. Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?
This application is currently Salesforce powered, so no. 

### 5. Do you need to capture any additional analytics or metrics?
Yes, but will likely be capturing them using VA notify and Salesforce. I don't believe we planned on integrating any front end analytics. 

### 6. Will a VA editor (Drupal) notice this change?
No, but we would like to be able to pull in individual information about VAROs. Will likely be pulling this information from salesforce though, not from va.gov (i.e. will be able to actively update information like operating hours inside of salesforce and that information will populate as a variable within the scheduling form). 

### 7. Link to artifacts
It is the Product Manager’s responsibility to ensure the link to the [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md) is added to the ticket. The VFS team is responsible for providing all relevant and up-to-date links, screenshots, images, and designs of the product's as-is version.

**Comment by shiragoodman** [comment]
@JonathanPostMO this is an outdated template and does not have the correct labels, assignees and/or questions. If you are trying to submit a Collaboration Cycle kickoff, please follow the steps and links on the [Collab Cycle Kickoff page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff). Governance team will not be responding to this ticket.
