### ISSUE TITLE
Evidence Upload Silent Failure – SharePoint sample folder

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#91471]
Place a small sample of identified failed evidence uploads in a SharePoint folder to share and obtain feedback on format and usefulness. Include a couple of files for each different error type, if possible, as well as different file types:

**Error types:**
- EVSS_10027
- EVSS_15001
- EVSS_15004
- EVSS_15005
- EVSS_15006
- EVSS_15010
- EVSS-15011
- File Upload
- File Upload, Invalid file size:0
- Breakers::OutageException
- Connection reset by peer - SSL_connect
- execution expired
- SSL_CTX_use_PrivateKey: key values mismatch
- The specified key does not exist.
- EVSS::ErrorMiddleware::EVSSBackendServiceError
- HTTPClient::KeepAliveDisconnected: Broken pipe
- SSL_read: unexpected eof while reading
- the server responded with status 403
- the server responded with status 408
- the server responded with status 500
- the server responded with status 502

**File types:**
- .txt
- .pdf
- .jpg/.jpeg
- .bmp
- .png

```[tasklist]
### Tasks
```

**Comment by lisacapaccioli** [comment]
https://dsva.slack.com/archives/C04KW0B46N5/p1724689450759809?thread_ts=1724098999.865119&cid=C04KW0B46N5

**Comment by freeheeling** [comment]
Something that displays as `Iâ€™m not sure how â€œin depthâ€` on S3 appears as `I'm not sure how "in depth"` when saved as a .txt file.

**Comment by freeheeling** [comment]
Modified contents of folder to not include any files that ultimately successfully uploaded.
