### ISSUE TITLE
Log facility website links from the appointment response body in production.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#91474]
We want to log the location object from the appointment response body in production.
We want to log location values from `location` in the appointment response.
Sample response: 

```
"location": {
                    "attributes": {
                        "website": "https://www.va.gov/spokane-health-care/locations/mann-grandstaff-department-of-veterans-affairs-medical-center/",
}
}
```

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/91474?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by jenniemc** [comment]
We will be using Lighthouse to extract the facility website URL instead of logs from Datadog

**Comment by jenniemc** [comment]
The below table shows facility websites (VAMC and CBOC) extracted from Lighthouse for  Cheyenne and Dayton facilities.

Prod facilityID  | Staging facilityId  | Name  | facility website |
| ------- | ------ | ----- |----- |
| vha_442    | 983    | Cheyenne VA Medical Center  | https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/ |
| vha_442GC  | 983GC  | Fort Collins VA Clinic  | https://www.va.gov/cheyenne-health-care/locations/fort-collins-va-clinic/ |
| vha_442GD  | 983GD  | Loveland VA Clinic  | https://www.va.gov/cheyenne-health-care/locations/loveland-va-clinic/ |
| vha_442GB  | 983GB  | Sidney VA Clinic  | https://www.va.gov/cheyenne-health-care/locations/sidney-va-clinic/ |
| vha_442HK  | 983HK  | Wheatland VA Mobile Clinic  | https://www.va.gov/cheyenne-health-care/locations/wheatland-va-mobile-clinic/ |
| vha_442QA  | 983QA  | Rawlins VA Clinic  | https://www.va.gov/cheyenne-health-care/locations/rawlins-va-clinic/ |
| vha_442QG  | 983QE (the last 2 alpha differs from prod)  | Sterling VA Clinic  | https://www.va.gov/cheyenne-health-care/locations/sterling-va-clinic/ |
| vha_552    | 984    | Dayton VA Medical Center  | https://www.va.gov/dayton-health-care/locations/dayton-va-medical-center/ |
| vha_552GD  | 984GD  | Springfield VA Clinic  | https://www.va.gov/dayton-health-care/locations/springfield-va-clinic/ |
| vha_552GB  | 984GB  | Lima VA Clinic  | https://www.va.gov/dayton-health-care/locations/lima-va-clinic/ |
| vha_552GC  | 984GC  | Richmond VA Clinic  | https://www.va.gov/dayton-health-care/locations/richmond-va-clinic/ |
| vha_552GA  | 984GA  | Middletown VA Clinic  | https://www.va.gov/dayton-health-care/locations/middletown-va-clinic/ |
| vha_552GF  | 984FG  | Wright-Patterson VA Clinic | https://www.va.gov/dayton-health-care/locations/wright-patterson-va-clinic/ |

cc @simiadebowale , @ldelacosta

**Comment by ldelacosta** [comment]
No additional information is needed. Closing out the ticket.
