### ISSUE TITLE
Discovery: Associate Claims with Appointments

### ISSUE THREAD

**Issue by ayush-chak** [department-of-veterans-affairs/va.gov-team#91489]
## Context
We need to understand how best to associate a travel pay claim with an appointment. We know that both the check in experience and the BTSSS portal both assign a mileage expense to the first appointment of the day if at a single facility.

## Facts
* 1 claim can be submitted per day, per facility, per user

## Questions
- If a user visits 2 facilities in the same day, what are the restrictions?
  - Do we need to worry about those restrictions, or is that the BTSSS rules engine domain?
- We've heard it said that on average, a user attends 1.5 visits per facility per day - can we confirm this is true?
- What is the status of having facility ID added to the `/claims` travel pay api endpoint?
  - progress, version, point of contact, etc
- Is this an edge case? There was some discussion of "can this even happen" and if it does, how often?

**Comment by liztownd** [comment]
For matching a single claim with a single appointment:
There is this proposed endpoint: `/api/v1.1/claims/search-by-appointment-date`, which could help satisfy a list of "which claims were submitted for the specific day in question". The response currently does not include the appointment ID or the facility ID (the facility name is included). 
- Adding appointment ID to that response would help link the specific claim from the date to the appointment assigned to the claim, and allow the UI to show "there is already a claim for this facility for this date" (or something similar) if there are multiple appointments at the same facility for that date
- Adding the facility ID to the response would help link the specific claim for a specific date to the facility (without relying on a string match of the facility name) - if there are multiple appointments at multiple facilities for which a claim might be submitted 
  - Follow up question for business rules: Are travel pay reimbursements limited to one per day per user or one _**per facility**_ per day per user?

For getting the entire list of appointments and entire list of claims and merging them in the `vets-api` backend:
Currently, the appointment ID is not included in the `/claims` endpoint. Adding the appointment ID and the facility ID would help match the specific appointment to the claim more easily.

**Comment by liztownd** [comment]
Confirmed with Blaise in this [Slack thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1725558215094219?thread_ts=1724354336.692309&cid=C05Q9HH47PS) that the business rules allow for one travel pay claim per day **per facility**.

This means that yes, having the facility ID also returned in the `/claims` endpoints are needed for associating the travel claim with the correct appointment (at the correct facility).
