### ISSUE TITLE
S61 [It's a Marathon, Not a Sprint 🏃‍➡️]

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#91502]
**Sprint dates:** Aug 28 - Sept 17, 2024

# Sprint Goals

| Previous Sprint | Next Sprint |
| :--------------  | ----------:  |
| ◀️  #90716        | #93010 ▶️        |

**Scrum Hero**: @eileen-coforma 

### Priority 1: Remediate historical failures ([WIP epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80241))

**Send historical failure data for review to determine which claims need to be remediated.**
- #80448
- #91323

### Priority 2: Submission Stability and Storage ([epic link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293))

**Store Submissions**
- #90103
- #91324
- #91326
- #91327

### Priority 3: HLR Form Version Update  [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82220)
**Implement stakeholder feedback and QA HLR form.**
- #92170
- #89863 
- #90356 
- #90552 
- #90554 
- #90553 
- #91454
- #90188 
- #89522 
- #88057

### Priority 4: SC Form Version Updates [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82219)
**Mockup SC and prepare for research.**
- #90568
- #92193
- #92283
- #89502 
- #92621
- #92792
- #92801

### Design Backlog
- #92481

### Bug/Engineering Backlog

- #88356
- #90112
- #90344  
- #91508 
- #90265 
- #76676 
- #76176 
- #79184 
- #90223 
- #91696
- #91894

### Other Platform/A11y Improvements
- https://github.com/department-of-veterans-affairs/vets-website/pull/31741
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1548
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/978
- #92666
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3082
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2685
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3225
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3226
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3208
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3281

---

## Blocked Items

- #81507
   - Waiting for Lighthouse to release [new endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81507#issuecomment-2115701294) to capture generated PDFs
- #83324
  - Blocked until after the form redesigns 
- #88513
   - Blocked until we get answers from either Steven Ng or Michael Hobson 
---

## Team Capacity

**Outages:**
- 8/26-8/30 - @eileen-coforma 
- 9/3 - @Mottie 
- 9/3-9/5 - @shaunburdick (LeadDev)
- 9/9-9/13 - @shaunburdick (OoO)
- 9/26-9/30 - @comaurice 

## Reference documentation

- [Q3 Roadmap Prioritization](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/product%20management/Prioritization/DR%20Prioritization%20Scoring%20-%20April%202024.xlsx?d=wb661cf77374d4321969f619e845cabbd&csf=1&web=1&e=GIwNAH)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)

**Comment by eileen-coforma** [comment]
Added #92170 to incorporate VBA feedback before release, as requested by stakeholders. Already briefed @Mottie

**Comment by eileen-coforma** [comment]
Molly's been working on a PR that's on the vets-website part of GH. Can't pull the ticket in for now. https://github.com/department-of-veterans-affairs/vets-website/pull/31741

**Comment by eileen-coforma** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/31741 will be done when Main gets merged back in

**Comment by eileen-coforma** [comment]
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1548 and https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/978 are merged

Opened PR for https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3082
