### ISSUE TITLE
Clean up all deprecated API Endpoints

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#91508]
## Value Statement

**_As a_** developer

**_I want to_** to only have in service endpoints in our code base

**_So that_** our codebase doesn't smell

---

## Background Context

- Clean up all Decision Review API endpoints that are not in use
   - An endpoint is not in use if the there are no references to that endpoint in our codebase
   - Check DD/Fwd Proxy to endure there are no references to that endpoint
   - Kill it with fire
- Remaining v0 endpoints that are still in use (that Robin was able to find) are:
  - `/v0/decision_review_evidence` — we can keep this one as there are no new versions of this endpoint
  - `/v0/notice_of_disagreements/contestable_issues` — **there is an existing v1 endpoint to replace this so confirm that one doesn't require any additional changes (i.e. it's the same thing) and if we feel comfortable switching to v1, ask Robin make that switch on the frontend and clean up the v0 endpoint**
    - Checked LH docs — v1 (v0) is deprecated so we should definitely switch to v2 (v1 in our controllers)
## Outcome, Success Measure, KPI(S), and Tracking Link

- All unused endpoints are removed

## Out of scope

- Deleting in use endpoints

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Molly and Annie paired on this task, and it's in code review.

**Comment by eileen-coforma** [comment]
PRs have been approved. Will merge after production deploy.

**Comment by eileen-coforma** [comment]
Merged a few PRs. One's still up for review. One more PR required for additional cleanup. After that's done, we can call this complete.

**Comment by eileen-coforma** [comment]
PR opened for last task. Once it's merged, ticket can be considered complete.

**Comment by eileen-coforma** [comment]
PR will be merged later today

**Comment by anniebtran** [comment]
Validated in staging and it has been deployed to prod with no apparent issues according to dashboards. Closing 🎉
