### ISSUE TITLE
508 Review - Current version of VAOS Product Guide

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9150]
Need to perform 508 review of current version of VAOS product guide. 

Reach out for the Word .doc that's been reviewed/passed Microsoft Accessibility Review feature. (file to large to add to ticket)

@lenaecb will put the document through the VA's document review process on the network and Trevor will advise on any findings.

**Comment by 1Copenut** [comment]
@lenaecb I started work on this document today, but will have to pick it back up next week when I'm back. The document I opened on the Mac version of Word had some text blocks go sideways, so I'll work more closely on it with the Windows machine.

**Comment by lenaecb** [comment]
@1Copenut - I have another new version of our guide. I've put it through the accessibility checker in Word, but wanted you to get it a pass over too. 

How would you like me to send it to you? (it's too big to drop in here)
