### ISSUE TITLE
Implement temporary URL change for 10-10CG form

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9155]
# User story

As a caregiver or Veteran who wants to apply for the Program of Comprehensive Assistance for Family Caregivers, I need access to the most current 10-10CG form.

# Details

It appears that the 10-10CG form (housed at https:///www.va.gov/health-care/forms/vha-10-10CG.pdf#) was updated with a new ID that generated a new URL (https://www.va.gov/vaforms/medical/pdf/10-10CG_revised%202020.pdf). We need to reach out to the VHA forms manager to get the updated form uploaded to the correct evergreen ID/URL and temporarily change the links on our pages to point to the new URL in the meantime.

## Process steps to completion

- [x] Ask for confirmation from caregiver team that the version of the form at the new URL is correct (Danielle)
- [x] Reach out to the VHA forms manager to ask that the updated form be uploaded to the evergreen URL as soon as possible (Danielle)
- [x] Temporarily change the links to the form on our pages to direct to the new URL (Danielle, Randi)
- [x] Once the updated form is live on the evergreen URL, change the links on our pages back to the evergreen URL (Danielle, Randi)

**Comment by DanielleThierryUSDSVA** [comment]
FYS @stephorkandatx

**Comment by RLHecht** [comment]
I changed the link to the 10-10CG form on the Program for Comprehensive Assistance for Family Caregivers to point to revised PDF. Saved as draft in Drupal until we get confirmation from stakeholder that it's the correct form. FYSA @DanielleThierryUSDSVA @stephorkandatx

**Comment by RLHecht** [comment]
The PDF on the two pages was changed back to the evergreen url. Moving to validate! FYSA @DanielleThierryUSDSVA @stephorkandatx

**Comment by RLHecht** [comment]
PDFs are working again with evergreen url. Closing ticket. FYI @DanielleThierryUSDSVA
