### ISSUE TITLE
Adding Nicole Rodriguez to DSVA Slack

### ISSUE THREAD

**Issue by smythe5** [department-of-veterans-affairs/va.gov-team#91561]
Nicole had been a part of DSVA slack but her account was deactivated. Thank you for your help.

- Please add nicole.rodriguez10@va.gov as a full member.

**Comment by smythe5** [comment]
Hello @LEHigley and @KevinMHoffmanUSDS . Are you able to help with this request?

**Comment by KevinMHoffmanUSDS** [comment]
Resolved. Cheers!
