### ISSUE TITLE
Staging Review finding: Plain language standards in caution message

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91565]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Appointments FE Team
**Product:** Appointments
**Feature:** Medication Review

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not align with VA.gov voice and tone content principles.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-aligns-with-vagov-voice-and-tone-content-principles)
**VA.gov Experience Standard - category:** [Credibility](https://design.va.gov/about/experience-standards/#category-credibility)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

In the message under "we can't display all your appointments" the expanded text reads "contact the facility at which it was scheduled." The prepositional phrase "at which" is not ideal for plain language standards 

## Recommended action

Change "at which" to "where" so the text reads: "contact the facility where it was scheduled" 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Plain language standards](https://design.va.gov/content-style-guide/plain-language/use-simple-words-and-terms)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by outerpress** [comment]
@ldelacosta @benbrasso-agile6 this is related to the [partial appts alerts](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2952-41529&t=fqsxextm7KZyfHiA-4) - can you review this feedback along with the other work you're doing on those alerts from collab cycle feedback? And link any relevant tickets here?

**Comment by benbrasso-agile6** [comment]
I've made that change to the updated component here - https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=985-15693&t=riHtqgM6jhPNy1Wl-4

But, I still need to version them out a bit for the different appt modalities. 

In the meantime, depending on if you're trying to release this now, I went ahead and updated Keegan's feedback on

https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2910-41593&t=riHtqgM6jhPNy1Wl-4

https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2952-41531&t=riHtqgM6jhPNy1Wl-4

https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2952-41532&t=riHtqgM6jhPNy1Wl-4

In the expandable alerts

(I'm realizing you might not have wanted to me DO this work rather than cross-check other tickets. Sorry! I was just in the groove.)

**Comment by benbrasso-agile6** [comment]
The feedback will become moot when I work with Leah to create the new ticket with the new message. I guess it makes sense to do this now.

**Comment by benbrasso-agile6** [comment]
Looks like there was a recent change with the pre-check-in and check-in alert, but it's a bit nuanced to these apps. So, no other alignment is needed across apps. This was a recent update by Laura W. and @cgednalske - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=543-11042&t=LvbdjsjD5hZx6uFN-4

**Comment by outerpress** [comment]
@benbrasso-agile6 thanks! I do think this falls into the scope of the changes you're making, esp if we think about this alert as doing similar things in different contexts. Could you drop a link the ticket(s) where the work is happening? I'll keep track of those and close this out once they're done.

**Comment by benbrasso-agile6** [comment]
Yep; not created yet. But, yes, will drop it in in the next day or two here.

**Comment by outerpress** [comment]
Dev work was done in #93409 closing. FYI @JRRoof
