### ISSUE TITLE
Staging Review finding: Use va-icon to indicate back

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91564]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Appointments FE Team
**Product:** Appointments
**Feature:** Medication Review

## Findings details
**VA.gov Experience Standard - issue:** [User encounters a component or pattern that isn't considered a best practice.](https://design.va.gov/about/experience-standards/#user-encounters-components-and-patterns-that-meet-best-practices)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @it-harrison (QA)

### Description

On the details page, the "Back to appointments" link uses the "<" char but should use the va-icon left_chevron component instead

<details><summary>Link, screenshot or steps to recreate</summary>

[Back chevron](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/85480_ian.png)

</details>

## Recommended action

Use the va-icon#left_chevron component

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Icons](https://design.va.gov/foundation/icons)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by outerpress** [comment]
We filed an [experimental design ticket for a back link](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2797#event-13992883618). Once that's documented in the design system, we'll replace all our back links with that.

**Comment by outerpress** [comment]
Just noting here that the back link is done and has been added to the [design system](https://design.va.gov/storybook/?path=/docs/components-va-link--back). FYI @ldelacosta I think we can move forward with adding these back links to the scheduling flows and details pages, and remove the back button from details pages.

**Comment by outerpress** [comment]
We'll handle this work in ticket #93012

**Comment by outerpress** [comment]
Dev work is done, so closing this one @JRRoof @Bren22va
