### ISSUE TITLE
10-7959f-1: conf page - update FMP contact center number and header

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91577]
The FMP helpdesk number will change on **9/12** to: 833-930-0816. We will need to update the FMP registration confirmation page as well as the FMP reg confirmation email. 
- copy change: also update header text to "What to expect next" 

- [staging url](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/)
- [figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=2602-54276&t=8VPNfph1ihEl3XBp-0)

**Comment by reiting** [comment]
@baltes this was merged and should be ready in staging for review.

**Comment by baltes** [comment]
Gonna hold onto this one until our s3 connection is resolved, since that's preventing us getting to the confirmation page on staging.

**Comment by marywang2** [comment]
I'm seeing it now!
