### ISSUE TITLE
Website ops dashboard improvements 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9157]
## Overview 

Add ideas in the comments for improvements to [this](https://nextjs-blog-rho-nine.now.sh/).

**Comment by rianfowler** [comment]
- yarn / npm uptime status 
  - the security check can fail if `yarn audit` doesn't work. `yarn audit` proxies to `npm audit`

**Comment by timwright12** [comment]
This is the new link for the dashboard: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard
