### ISSUE TITLE
10-7959c: end to end testing w/PDF filler

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91584]
As a VA.gov user, I want to submit my completed form online and receive an email so that I know my form was processed successfully.

- all paths/flows are tested
- all user types are tested
- PDF is filled out correctly with the information in the corresponding fields
  - test non US address and military base as well

**Comment by michaelclement** [comment]
| End to End Test | PDF output |
| - | - |
| Has Medicare (ABD), both OHIs (Medigap), US address (new), third party signer |[ohi_maximal_test.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHlQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a6a97d0db0947e184760a5fff7e54450ae916c7/ohi_maximal_test.pdf)|
|No Medicare, no OHIs, US address (new), third party signer|[ohi_minimal_test.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0868a86c122b463c06379ce49fdf95e85e14cf9f/ohi_minimal_test.pdf)|
|No Medicare, both OHIs (Medigap), US address (new), third party signer|[ohi_no_medicare_yes_ohi.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9QQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a73080bee747f1f6ff908150be0d51276a26b0cb/ohi_no_medicare_yes_ohi.pdf)|
|No Medicare, one OHI (Medigap), US address (new), third party signer|[ohi_no_medicare_yes_primary.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e6603abf8981ddd234d7bf504a99d560c8b8438/ohi_no_medicare_yes_primary.pdf)|
|Has Medicare (ABD), no OHI, US address (new), third party signer|[ohi_yes_medicare_no_ohi.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWFQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91786f6edf8eacd6dde38bd24adf82999fa75c06/ohi_yes_medicare_no_ohi.pdf)|
|Has Medicare (ABD), one OHI (Medigap), US address (new), third party signer|[ohi_yes_medicare_yes_primary.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50672f07e07637f4556dda3b3d9478d253b88aa9/ohi_yes_medicare_yes_primary.pdf)|

<img width="963" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1QQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--165f3cee92a34c1a50182969405921fb037327aa/Screenshot%202024-08-27%20at%2011.30.08.png" alt="Screenshot 2024-08-27 at 11.30.08.png" />

**Comment by michaelclement** [comment]
As a note, when OHI or Medicare aren't present, we don't need to be checking boxes "No" in those sections.

**Comment by marywang2** [comment]
@jamiefiore we should review and discuss any changes we want to see for the generated PDFs.

**Comment by michaelclement** [comment]
@marywang2 @jamiefiore This ticket is ready for review. Thanks!

**Comment by marywang2** [comment]
Opened related BE ticket [here](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/91997)
