### ISSUE TITLE
[Security]  Harden pgaudit

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#91589]
## Description
As a DBA, I need to ensure that pgaudit is configured to audit all DB actions taken by a user.
This will allow for periodic reviews to take place.

DB scans from July reported that pgaudit.conf needs to be reviewed and updated to ensure we are capturing everything that is needed.

## Acceptance Criteria
- [x] pgaudit.conf configured and hardened for all non-aurora databases in lower environment

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
Working on getting a grasp of what needs to be done to implement pgaudit hardening across all non aurora databases

**Comment by Efe-Oddball** [comment]
I have updated Gids and vets-api databases with the pgaudit configuration and applied the terraform changes pending database instance restart. Platform-Atlas databases does not look to be provisioned via terraform, so I might be making updates directly within the console.

**Comment by Efe-Oddball** [comment]
Pushed out PR for this ticket. All that is left in the lower environment is to reboot the staging environment so the audit logging can start taking place, resolve this ticket and create a new ticket for prod environment

**Comment by Efe-Oddball** [comment]
Staging databases reboot was successful and pgaudit have been initialized in those databases. A new ticket has been created to implement these changes in prod environment. Co-ordination with the product team will be necessary to implement instance reboot after parameter update.
