### ISSUE TITLE
CT-EYB: Mobile formatting issues

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9159]
There are two mobile formatting issues as a result of #8842

1. The overlapping text in the accordion headers on smaller screens (specifically iPhone 5). This text should wrap to prevent overlapping as shown in the [Sketch Document](https://www.sketch.com/s/0ee1f7c7-6692-4ef8-912d-0a929b5e5154/a/vGA4ee)

 ![Screen Shot 2020-05-15 at 8.43.55 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/220011d1-b777-44cc-8db9-40530f50ce39)

2. The input fields and drop-downs are extending slightly off-screen. These fields should shrink to fit as shown in the [Sketch Document](https://www.sketch.com/s/0ee1f7c7-6692-4ef8-912d-0a929b5e5154/a/vGA4ee)

![Screen Shot 2020-05-15 at 8.45.26 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b32b9ab8-f4c6-41db-930c-6ae430b7e974)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12632

**Comment by delli-gatti-michael** [comment]
Fix to be included in the following PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/12632

**Comment by delli-gatti-michael** [comment]
Local testing complete

<img width="352" alt="Screen Shot 2020-05-15 at 11 31 20 AM" src="https://user-images.githubusercontent.com/45575003/82069371-33222c00-96a1-11ea-98ec-94978f0d819e.png">

---

<img width="343" alt="Screen Shot 2020-05-15 at 11 31 33 AM" src="https://user-images.githubusercontent.com/45575003/82069380-37e6e000-96a1-11ea-8a3b-89463f2ceb05.png">

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah 
This fix is on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael UX took a look and we found no issues.

**Comment by delli-gatti-michael** [comment]
Closing this out with UX and QA approval.

**Comment by sonntag-adam** [comment]
Occurring in staging again.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12786

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-26 at 10.44.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9fa4c85d-443d-48a0-853c-450f596a148c)
##
![Screen Shot 2020-05-26 at 10.44.24 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cdec8477-9e83-4ff4-8939-d83e340b752a)
##
![Screen Shot 2020-05-26 at 10.44.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/326caeac-d414-489d-8276-8a89dd4efae2)
##
![Screen Shot 2020-05-26 at 10.44.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/25d11cd3-be6c-4a8e-98ae-45f2d0c1a8c9)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review in staging.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12814

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-27 at 9.46.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/928c69ee-0706-46e0-93f3-9aaf899c1f13)

**Comment by ccruzgra** [comment]
@sonntag-adam We'd observed the contents of the EYB accordion were shifted to the right, but Matt fixed that so this work is good to go!

**Comment by sonntag-adam** [comment]
Closing bug.
