### ISSUE TITLE
Test Vagrant setup for Windows/Windows GFE and Mac

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#916]
## User Story
As an external team, I need get setup with my development environment to work with VA.gov. We need to be able to develop on Windows, Windows GFE, Linux, and also Mac.

Here is the link to the setup documentation:
[https://docs.google.com/document/d/1gigx9yOJ7UNvFtr8-oQg5p52VPTuooTx69R3aGGZWF4/edit?usp=sharing](https://docs.google.com/document/d/1gigx9yOJ7UNvFtr8-oQg5p52VPTuooTx69R3aGGZWF4/edit?usp=sharing)

## Goal
Have an easy and quick way to setup a development environment on Windows, Windows GFE, Linux, and also Mac.

## Acceptance Criteria
- [ ] Should be able to get setup on Windows/Windows GFE and Mac with minimal configurations
- [ ] Documentation should be accurate and complete.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peterhill-oddball** [comment]
>Create a new folder
$ touch va-gov

This should be mkdir, no?  'touch' just creates an extensionless file named 'va-gov'.

**Comment by peterhill-oddball** [comment]
Error message upon attempting `vagrant up` --

>$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'va-gov'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: va-gov_default_1565637014242_74367
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:
  https://www.virtualbox.org/manual/ch04.html#sharedfolders
This option can be disabled globally with an environment variable:
  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1
or on a per folder basis within the Vagrantfile:
  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3001 (guest) => 3001 (host) (adapter 1)
    default: 3000 (guest) => 3000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["startvm", "9e169000-384a-41ec-80e0-6e99e8e37223", "--type", "gui"]
Stderr: VBoxManage.exe: error: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by accbjt** [comment]
Try to do vagrant up again. Sometimes it doesn’t work the first time around

**Comment by peterhill-oddball** [comment]
It seems like perhaps Docker and Vagrant can not coexist on the same host: 
https://github.com/scotch-io/scotch-box/issues/195

I did the following --

1. Uninstalled Hyper-V in Windows features
2. Rebooted
3. Verified Virtualization was enabled in BIOS
4. Removed VM from Virtualbox
5. Removed Vagrantfile
6. ran `vagrant init va-gov.box`
7. ran `vagrant up`
8. No errors -- yay!?

**Comment by accbjt** [comment]
@peterhill-oddball I think the problem is you don't have an ssh key on your system. Did you ever create an ssh key? I remember you might have in when you first started for the Socks Proxy stuff. What I did is transfer my `.ssh` folder into my GitBash location. So I added it to my desktop. Then went into GitBash and then mv /Desktop/.ssh ~/. Then I added it to my computer using the commands in the my document. I think as long as you have that folder that might fix the issue.

**Comment by peterhill-oddball** [comment]
Still no joy with Vagrant + GitBash --

SSH Keys in place in GitBash
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/a67d6783-8e2e-449b-b633-806d72f2d99f)

New Vagrant files in place
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/e7c0b436-f376-453a-95e2-e289b861fd73)

`Vagrant up` fails to automatically connect
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/56f5e9e5-41dc-4e66-94d4-5c05901b7169)

Manually connecting to vagrant with `vagrant ssh` also doesn't work
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/2b9aedab-8acc-4627-a219-f68dd31df25d)

Using `vagrant ssh -- -vvv` shows a ton of info, but the public key information is:
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/837901b6-c0ea-4a8a-b544-c76c39027ef5)

**Comment by accbjt** [comment]
@peterhill-oddball did you create a new folder? If not some of your setting are still in that folder. I would make sure to destroy the vagrant box `vagrant destroy`. Then delete the `.vagrant` folder. Then try `vagrant up` again. If this doesn't work try created a brand new folder and move the `Vagrantfile` and `va-gov.box` into there then try it again.

**Comment by peterhill-oddball** [comment]
@accbjt 

I `rm -r`'ed the previous folder, recreated the folder with the same name, and copied the new files into it.

I did not run vagrant destroy previously.  I'll try a new folder name.

**Comment by peterhill-oddball** [comment]
Sigh -- no dice.  I wiped everything out:
1. ~/vagrant.d/
2. ~/va-gov/
3. vagrant destroy
4. ~/.ssh

Then I created new ssh keys.
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/bd5c7d78-27c2-428d-90cf-020b94eb5cd4)
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/38a808de-eefe-4fa5-85af-8e63995d41ab)

**Comment by peterhill-oddball** [comment]
After some live troubleshooting with Bill, it appears that there may be a configuration within the guest that is breaking ssh for me.

We were able to get a default vagrant box up and running without any issue.

We were also able to get the default vagrant image up and running using Bill's customized Vagrantfile.

**Comment by peterhill-oddball** [comment]
Somehow I broke my proxy access, and the server is telling me that my account is not available.  So, I get drupal errors when I start up the front-end.  

Anyway, I have the front-end and back-end started up.

WSL Front-end start time: 53904ms
Vagrant Front-end start time: 171681ms

However, I am unable to navigate to the website.  http://localhost:3001 doesn't work as it did on WSL.  I also tried the ip address of the Vagrant box -- http://10.0.2.15:3001.

**Comment by peterhill-oddball** [comment]
For posterity -- after some collaborative troubleshooting with Bill, the problem I was having connecting to the website was because the website was not binding to `0.0.0.0`.  This was resolved by using `yarn watch --host 0.0.0.0` instead of `yarn watch`.  This will be included in the Vagrant installation instructions going forward.

**Comment by peterhill-oddball** [comment]
I'll leave this ticket open until Trevor has a chance to test and weigh in with his results.  As far as I'm concerned, I have completed the Vagrant testing, and all of my issues have been resolved.
