### ISSUE TITLE
[In-Progress] Staging Review (2) - Caregivers MVP

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#9160]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to [form in staging](https://staging.va.gov/caregivers/)
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/release-plan.md)
- Link to [prototype](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5)
- Link to your product test cases/[test plan in TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/175) with test execution logs
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
 - Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.

*Required:*
- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
- [x] Conduct axe browser scan, and document or address issues found 
- [ ] Ensure end-to-end tests - including the axe check, pass 
- [ ] Check color pairing for proper contrast 
- [ ] Check for colorblindness issues 
- [x] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
- [x] Repeat for 300% 
- [x] Repeat for 400% 
- [x] Navigate all pages and core functionality with keyboard only 
- [ ] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 

*Recommended:*
- [ ] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
- [ ] Add keyboard end-to-end tests in CI/CD test runs 
- [ ] Conduct axe-coconut browser scan, document or address issues found 
- [ ] Test with [WAVE tool](https://wave.webaim.org/) 

*Known issues:*

* []()
* []()
* []()

## Meeting attendees from **Caregivers**
- Product Manager (required): *Alayna Abel**
- DEPO product lead (required): **C.C. Gong**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Jonathan Nelson, Justin Linn, Kevin Mircovich, Patrick Sanders**

## Scheduling
Preferred dates or times: Any time next week!

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by vbellissimo** [comment]
Cancelling/old task.
