### ISSUE TITLE
10-7959a: end to end testing w/PDF filler

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91615]
As a VA.gov user, I want to submit my completed form online and receive an email so that I know my form was processed successfully.

[frontend]
- all paths/flows are tested
- all user types are tested
- PDF is filled out correctly with the information in the corresponding fields
  - test non US address and military base as well

[backend - separate ticket]
- PDF is found in PEGA staging with no errors
  - correct doctype appears 
- metadata is sent correctly and ingested on PEGA end
- email is sent by VA Notify to user's email
- datadog reflects form activity
- if there is an issue, an alert captures the status

**Comment by michaelclement** [comment]
(pdfs generated locally)

|End to End test|PDF generated|
| - | - |
|Military base sponsor address, no OHI, pharmacy claim, work related, NOT auto related|[claims_military_address_no_ohi_pharmacy_work.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c09cccf2184657cc9e6f7d32a549cbfa0b8ea2d/claims_military_address_no_ohi_pharmacy_work.pdf)|
|Third party signer, beneficiary has foreign address, OHI, medical claim, work related, auto related|[claims_third_party_foreign_address_ohi_medical_claim_work_auto.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c484421c7f130cd877aa01a4d7db58f6d33e37ab/claims_third_party_foreign_address_ohi_medical_claim_work_auto.pdf)|
|Two OHIs, medical claim, insurance type other, NOT work, NOT auto|[claims_two_ohi_other_type.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99fcff76af0e53adf324ac3f1a98b6370a7eda02/claims_two_ohi_other_type.pdf)|

<img width="784" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3579e4da728768918f95d7c6177c3a09f4136bc9/e2e_success.png" alt="e2e_success.png" />

**Comment by michaelclement** [comment]
@marywang2 @jamiefiore This is ready for review - thanks!

**Comment by marywang2** [comment]
fyi @syd-hoeper
