### ISSUE TITLE
Create Optimal Workshop Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#91617]
## Tasks
- Create Optimal Workshop Study
- Address feedback from CIE & Appts
- Pilot test

**Comment by benbrasso-agile6** [comment]
Looks great. DM'd some minor feedback.

**Comment by cgednalske** [comment]
@benbrasso-agile6 I think we can close this? Working on getting materials submitted today or tomorrow.

**Comment by cgednalske** [comment]
Linking to [the repo issue for this study](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/680) for reference
