### ISSUE TITLE
SOCKS access for Alexander Person

### ISSUE THREAD

**Issue by alexperson-tw** [department-of-veterans-affairs/va.gov-team#91676]
### Your Name

Alexander Person

### Your Email

alex.person@thoughtworks.com

### Your GitHub Handle

alexperson-tw

### Your Role and Team

Developer on Chatbot Platform Team

### Product Manager (PM) name and email

Alina Murphy, amurphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Alexander Morais, Luciana.a.morais@omb.eop.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBJUyTsrYfyy9/TxasxYXCy+sbVd8LNSMHk8Af6og1yy alexperson@alexs-mbp.lan

### e-App (aka E-QIP) Transmittal Confirmation

<img width="732" alt="Screenshot 2024-08-27 at 4 10 59 PM" src="https://github.com/user-attachments/assets/745a38d1-949d-4afe-9767-d5c6f18c9ffd">

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by patrick-black-oddball** [comment]
complete
