### ISSUE TITLE
AWS access for Seth Darr

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#91677]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Seth Darr

### Your Email

seth.darr@agile6.com

### Team, Role, and Company of the target individual

Disability Benefits Experience Team 1, Full Stack Engineer, Agile Six Applications, Inc.

### Product Manager (PM) name and email

jared.pace@agile6.com

### Product Owner (PO) name and email

emily.theis@va.gov

### Desired AWS Access

I need read access to the dsva-vetsgov-prod-reports bucket in S3 in order to download report data generated there. Part of that access should include the ListObjectsV2 or s3:ListBucket operations, in order to avoid the following error:

`fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: User: arn:aws-us-gov:iam::008577686731:user/Seth.Darr is not authorized to perform: s3:ListBucket on resource: "arn:aws-us-gov:s3:::dsva-vetsgov-prod-reports" because no identity-based policy allows the s3:ListBucket action`

I need this primarily to support the launch of our upcoming toxic exposure release (526EZ). When we go to 5%, our stakeholders requested that we upload their submission data to Sharepoint. Similar permissions should already exist for user Sam Stuckey. Note that I already have some limited access to AWS, my username is `Seth.Darr`

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/user-attachments/assets/18870d74-7376-417a-af7e-6b467f55f2b5)

### Additional Notes

From Emily Theis:

> Allowing Seth to pull the raw submission data for these forms ensures that we're accurately capturing and translating all the fields in this huge form end-to-end, all the way to adjudicators. There are 3 systems between us and that point.  The script that is referenced does allows us to transfer and check the form data against the final output in a secure way, on network.
> Because [VA.gov](http://va.gov/) does not have a pre-prod environment with prod data, unfortunately bugs get caught in production even with thorough testing on staging. We can't catch certain types of bugs without doing this activity -- if a piece of data is mistranslated from the front-end to the generated claim doc, we would have no idea, and Veterans data would be wrong, which could affect the accuracy of their claims.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@JonathanKamensDVA user is requesting access to prod S3 bucket. @emilytheis is the PO here. If you have questions beyond the above stated need for this request.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by sethdarragile6** [comment]
Hello! 🙋‍♂️ Hate to be a nag, but is there anyway we can speed up this access? I'm trying to deliver some sample data reports for our stakeholders before next weeks staged rollout. 🙏

**Comment by sethdarragile6** [comment]
> Hello! 🙋‍♂️ Hate to be a nag, but is there anyway we can speed up this access? I'm trying to deliver some sample data reports for our stakeholders before next weeks staged rollout. 🙏

Standing down on the urgency of this request. It turned out that a team member had this access, and so we were able to deliver the reports. I still need this for the upcoming release next week (as well as the, erm, SSM access back 😬) But not this very minute. Thank you! Sorry for all the noise here, AND the ridiculous misunderstanding about my SSM permission 🤦‍♂️

**Comment by sethdarragile6** [comment]
@flooose I just submitted [another request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91988) for SSM access, if that expedites things.

**Comment by sethdarragile6** [comment]
hello, any update on this? @flooose

**Comment by patrick-black-oddball** [comment]
hey Everyone - I'm digging into this one this morning.  It would help a lot if I had a reference of a person on your team with the appropriate access

**Comment by sethdarragile6** [comment]
> hey Everyone - I'm digging into this one this morning. It would help a lot if I had a reference of a person on your team with the appropriate access

Thanks, Patrick, I slack you the names this morning, but for reference here: Aurora Hampton and Sam Stuckey. Sorry that got lost, I think I told Christopher on slack but it never made it here.

**Comment by patrick-black-oddball** [comment]
Completed
