### ISSUE TITLE
AWS access for [Sanja Bajovic]

### ISSUE THREAD

**Issue by sanjabaj2** [department-of-veterans-affairs/va.gov-team#91681]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Sanja Bajovic

### Your Email

sanja.bajovic2@va.gov

### Team, Role, and Company of the target individual

VA Eng lead

### Product Manager (PM) name and email

Emily Theis, emily.theis@va.gov

### Product Owner (PO) name and email

Ryan Powers, ryan.powers3@va.gov

### Desired AWS Access

I need access to AWS to assist the team with key management. I am a federal employee. 

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

[Initial background check complete.pdf](https://github.com/user-attachments/files/16770236/Initial.background.check.complete.pdf)

### Additional Notes

I am a federal employee, don't have COR or onboarding contact. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by va-albers** [comment]
@sanjabaj2 is a member of the OCTO Benefits Portfolio team.

**Comment by va-albers** [comment]
Sanja needs access to update the following dev/staging/prod Parameters Store keys - 
/dsva-vagov/vets-api/dev/lgy/api_key
/dsva-vagov/vets-api/dev/lgy/app_id
/dsva-vagov/vets-api/prod/lgy/api_key
/dsva-vagov/vets-api/prod/lgy/app_id
/dsva-vagov/vets-api/staging/lgy/app_id
/dsva-vagov/vets-api/staging/lgy/api_key

Sanja needs to be able to read the following: 
/dsva-vagov/vets-api/dev/lgy_base_url
/dsva-vagov/vets-api/staging/lgy_base_url
/dsva-vagov/vets-api/prod/lgy/base_url

**Comment by flooose** [comment]
> @emilytheis could you verify that Sanja is a member of your team?

[Confirmation](https://dsva.slack.com/archives/CBU0KDSB1/p1724852324975709?thread_ts=1724793654.075929&cid=CBU0KDSB1)

**Comment by flooose** [comment]
@JonathanKamensDVA user is requesting access to prod AWS Parameter Store

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by patrick-black-oddball** [comment]
Completed
