### ISSUE TITLE
Evidence Upload Silent Failure – Retrieve AWS logs prior to 1/17/20

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#91683]
## Tasks
- Search AWS CloudWatch for log data prior to 1/17/2020
- Create a record of all findings to include, at a minimum:
  - details about failed document: filename, S3 link
  - reason for failure
  - date of failure
  - associated claim
  - veteran identifiable attribute
- Document process, methodology, and helpful scripts

## Dependency
- Thomas recommended reaching out to Sam Raudabaugh for assistance obtaining logs

Follow steps in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/investigations/2024-07-31-evidence-upload-silent-failures.md#methodology to process and filter desired logs.

**Comment by lisacapaccioli** [comment]
No longer applicable as the team found another way to do this.
