### ISSUE TITLE
Update ATLAS content and spacing

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#91713]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The content change comes from staging review ticket #91566 .  I noticed the spacing issue while reviewing that feedback.

---

## Development Checklist

- [x] Under “How to join” change this text: `You will use this appointment code`
To `You’ll use this appointment code`
- [x] Remove the extra space under the “How to join” section (see screenshot). 
- [ ] The text under “How to join” is the standard 16.96 base font size. 

### Design Assets
<img width="306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b257c3fdc3d1f45bd7c58170a02049ad46632f19/Screenshot%202024-08-28%20at%207.34.59%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 7.34.59 AM.png" />

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
@ldelacosta assigning to you for prioritization

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/91713?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
As part of our discussions we decided to split out the font size work, which will be fixed systematically pending discussions in https://github.com/department-of-veterans-affairs/va.gov-team/issues/92090.

**Comment by ldelacosta** [comment]
UX team will do a second validation in staging.

**Comment by outerpress** [comment]
Looks good, validated @JunTaoLuo @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
