### ISSUE TITLE
A11Y improvements to details page facility section

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#91722]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The `role=group` can safely be removed from the span that wraps the state abbreviation under the "Where to attend" section. See collab cycle ticket #91568 for full background.

---

## Development Checklist

For all affected appointment types:
- [x] Remove `role=group` from the span that wraps the state abbreviation
- [ ] Font size for the content under "Where to attend" section should be 16.96px

### Design Assets
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ceeb276b8f5bf9ab24f2cee741fc7da1fb82eb8/Screenshot%202024-08-28%20at%208.18.24%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 8.18.24 AM.png" />

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/91722?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
As part of our discussions we decided to split out the font size work, which will be fixed systematically pending discussions in https://github.com/department-of-veterans-affairs/va.gov-team/issues/92090.

**Comment by ldelacosta** [comment]
UX team will do a second validation in staging.

**Comment by outerpress** [comment]
@ldelacosta @JunTaoLuo  I spot-checked appointment types on staging, didn't review all of them since this is a shared component. Validated the removal of `role=group` in that scope (ignoring the font-size as this work will be done in future tickets).

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
