### ISSUE TITLE
Remove aria-label from Add to Calendar button

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#91735]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The `aria-label` on the Add to Calendar button isn't necessary and may cause issues for voice control users. See staging review ticket #91569 for details

---

## Development Checklist

For all relevant appointment types:
- [x] Remove `aria-label` from Add to Calendar button

### Design Assets
<img width="1995" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba977e34e71db807839e6376364e97a640b65d90/Screenshot%202024-08-28%20at%209.32.39%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 9.32.39 AM.png" />

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
@ldelacosta assigned to you for prioritizing

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/91735?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
UX team will do a second validation in staging.

**Comment by outerpress** [comment]
@JunTaoLuo @ldelacosta looks good, validated

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
