### ISSUE TITLE
508-defect-1 ❗ Launchblocker [SEMANTIC MARKUP]: Form elements MUST be paired with labels

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9173]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The text input for the individual signatures **must** be paired with labels. In the code, the input must have a unique id attribute and the value must match the value of the for attribute of the associated label. This repeats for all signature inputs.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As user, I want to understand the label associated with the input..

## Environment

* Operating System: all
* Browser: all
* Server destination: staging

## Steps to Recreate

1. Enter https://staging.va.gov/caregivers/review-and-submit in browser
2. Start axe browser scan
3. Verify "Form elements must have labels" is listed, associated with `<input id="errorable-text-input-13" name="vet-signature-input" type="text" value="">`

### Current code
```diff
<article class="vads-u-background-color--gray-lightest vads-u-padding-bottom--6 vads-u-padding-x--1p5 vads-u-padding-top--1px vads-u-margin-bottom--7">
  <header>
    <h3>Veteran or service member statement of truth</h3>
    <p>I certify that I give consent to the individual(s) named in this application to perform personal care services for me upon being approved as Primary and/or Secondary Caregiver(s) in the Program of Comprehensive Assistance for Family Caregivers. I have read and accept the<a target="_blank" rel="noopener noreferrer" class="vads-u-margin-left--0p5" href="https://www.va.gov/privacy-policy/">privacy policy</a>.</p>
  </header>
-  <label for="vet-signature-input">Enter Veteran's or service member's full name</label>
  <div>
-    <label for="errorable-text-input-13"></label>
-    <input id="errorable-text-input-13" name="vet-signature-input" type="text" value="">
  </div>
  <div class="form-checkbox">
    <input id="errorable-checkbox-14" type="checkbox">
    <label name="undefined-label" for="errorable-checkbox-14">I certify the information above is correct and true to the best of my knowledge and belief.</label>
  </div>
</article>
```

### Recommended code
```diff
<article class="vads-u-background-color--gray-lightest vads-u-padding-bottom--6 vads-u-padding-x--1p5 vads-u-padding-top--1px vads-u-margin-bottom--7">
  <header>
    <h3>Veteran or service member statement of truth</h3>
    <p>I certify that I give consent to the individual(s) named in this application to perform personal care services for me upon being approved as Primary and/or Secondary Caregiver(s) in the Program of Comprehensive Assistance for Family Caregivers. I have read and accept the<a target="_blank" rel="noopener noreferrer" class="vads-u-margin-left--0p5" href="https://www.va.gov/privacy-policy/">privacy policy</a>.</p>
  </header>
  <div>
+  <label for="vet-signature-input">Enter Veteran's or service member's full name</label>
+    <input id="errorable-text-input-13" name="vet-signature-input" type="text" value="">
  </div>
  <div class="form-checkbox">
    <input id="errorable-checkbox-14" type="checkbox">
    <label name="undefined-label" for="errorable-checkbox-14">I certify the information above is correct and true to the best of my knowledge and belief.</label>
  </div>
</article>
```

## WCAG or Vendor Guidance (optional)

* [1.3.1 Info and Relationships Level A](https://www.w3.org/WAI/WCAG21/quickref/#info-and-relationships)

* [W3C Labeling Controls](https://www.w3.org/WAI/tutorials/forms/labels/)

## Screenshots or Trace Logs

![Screen Shot 2020-05-15 at 2 08 01 PM](https://user-images.githubusercontent.com/57469/82082148-84d4b180-96b5-11ea-8432-0674a3f1bd74.png)

**Comment by jonathanjnelson** [comment]
See [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9342)

**Comment by jenstrickland** [comment]
Validated.
