### ISSUE TITLE
CT-EYB: Sections of the Estimate your benefits box should be bold

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9175]
The below highlighted parts of the Estimate your benefits box should be in bold.

### Expected:
![856c1e3c-a9aa-43be-aede-3f453cc6725c.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/808d7232-3821-45fc-a2c0-47ce20fd3b40)

---

### Actual:
![Screen Shot 2020-05-15 at 2.03.47 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ed79e918-1600-48ba-97bc-8f27df91eaa7)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12695

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-21 at 3.14.50 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a05a2b17-c01f-402a-8a25-4b29c3c5d70f)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I reviewed and this checks out.

**Comment by sonntag-adam** [comment]
Closing bug
