### ISSUE TITLE
Staging Review finding: Sentence structure in travel-pay page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91798]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Modernized Check-in
**Product:** eCheck-in
**Feature:** Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not meet best practices.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-meets-best-practices)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

The phrase "If you’re claiming only mileage, you can file online right now. We’ll ask you a few questions. You won’t need receipts." is a bit choppy and difficult to read. 

Similarly, the phrase "If you’re claiming other expenses, like lodging, meals, or tolls, you can file online through the Beneficiary Travel Self Service System (BTSSS). Or you can file by mail or in person. You’ll need receipts for other expenses." has some difficult sentence breaks.

<details><summary>Link, screenshot or steps to recreate</summary>

https://staging.va.gov/my-health/appointment-travel-claim/travel-pay

</details>

## Recommended action

I would change the first phrase to "If you're only claiming mileage, you can file online right now. We'll ask a few questions, and you won't need receipts to file" or "If you're only claiming mileage, you can file online right now without receipts. We'll just ask you a few questions." 

For the second, I would recommend "If you're claiming other expenses, like lodging, meals, or tolls, you can file online through the Beneficiary Travel Self Service System (BTSSS). You can also file by mail or in person." or, if you go with the second option above, I would do this for consistency: "If you're claiming other expenses, like lodging, meals, or tolls, you will need receipts for these expenses. You can file online through the Beneficiary Travel Self Service System (BTSSS), by mail, or in person." 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Content principles](https://design.va.gov/content-style-guide/content-principles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by loripusey** [comment]
NOTE: if pick the first recommendation for the first sentence then pick the first recommendation for the second sentence

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91798?planning-poker) with Zenhub @brianseek @wullaski

**Comment by benbrasso-agile6** [comment]
Let me cross-check the Travel Pay Team's content. One moment.

**Comment by benbrasso-agile6** [comment]
Travel Pay chose: 

`If you’re claiming only mileage, you can file online right now. We’ll ask you a few questions. You won’t need receipts.`

I'll update our Figma file now. 

And...

`If you're claiming other expenses, like lodging, meals, or tolls, you will need receipts for these expenses. You can file online through the Beneficiary Travel Self Service System (BTSSS), by mail, or in person.`

ALSO, USE THE CURLY APOSTROPHES :)

**Comment by benbrasso-agile6** [comment]
Updated in Figma - https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=642-3804&t=zmgWxCS4I3LQXx3G-4

**Comment by brianseek** [comment]
@loripusey we need to coordinate around translations. @wullaski had a good idea around waiting to make the change until after we get new translations.

**Comment by brianseek** [comment]
@benbrasso-agile6 `If you’re claiming only mileage, you can file online right now. We’ll ask you a few questions. You won’t need receipts.` is what we currently have an not one of the new choices.

**Comment by benbrasso-agile6** [comment]
Laura from CAIA went back and forth in Figma. So, what we have in Figma should suffice for this ticket.

**Comment by brianseek** [comment]
Its exactly the same as what we had before

**Comment by brianseek** [comment]
@benbrasso-agile6 can you double check that on Monday? It seems weird to totally ignore the feedback without some reason.

**Comment by benbrasso-agile6** [comment]
What I see in Figma aligns with what this ticket is asking for. 

It's possible you (or John) made these updates in a different PR and didn't realize it was feedback from this ticket. 

![image](https://github.com/user-attachments/assets/89a27238-b9a8-4358-b372-a62df1102284)

**Comment by benbrasso-agile6** [comment]
When in doubt, blame John for working ahead 😃

**Comment by loripusey** [comment]
so are we good to close? @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
It looks great to me. Brian had some concerns, but I think this is complete based on comparison of feedback and screenshots of staging.

**Comment by brianseek** [comment]
also @benbrasso-agile6 what you are saying doesn't track. That text is 5 months old:
<img width="1829" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVM5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8acb7f93892b646b8be95b3ce45ac4106909fd9d/Screenshot%202024-09-09%20at%208.09.56%E2%80%AFAM.png" alt="Screenshot 2024-09-09 at 8.09.56 AM.png" />

**Comment by benbrasso-agile6** [comment]
Would recommend passing it off to @cgednalske. I don't doubt I might be missing something.

**Comment by benbrasso-agile6** [comment]
@cgednalske Laura played around with this content in a commend thread. I believe this same feedback was given and addressed in Micah's Figma file for simple-mileage only claim (SMOC) file. It might be in a resolved comment thread in that file. Not sure if this is helpful or not, but just wanted to let you know.

**Comment by cgednalske** [comment]
Thanks Ben! Brian brought this up in huddle. I'll look into it and reach out to Laura if it's not already resolved in a thread. 👍

**Comment by cgednalske** [comment]
Pinged Laura in Figma and Slack to update her on this and get her feedback, so we'll see what she says. 👍

**Comment by brianseek** [comment]
@cgednalske / @zach-park this is merged and ready to be validated locally or in the screenshots in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31826

**Comment by zach-park** [comment]
LGTM. Thank you!

**Comment by brianseek** [comment]
thanks @zach-park !
