### ISSUE TITLE
Staging Review finding: Consistency with page title of application

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91797]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Modernized Check-in
**Product:** eCheck-in
**Feature:** Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content with errors or inconsistencies.](https://design.va.gov/about/experience-standards/#user-encounters-accurate-consistent-content)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

This application uses the same <title> tag across all pages - `Travel Claim | Veterans Affairs'. This page title could be more descriptive and describe the purpose of the tool using active language. 

<details><summary>Link, screenshot or steps to recreate</summary>

![title-tag-mileage-claim](https://github.com/user-attachments/assets/9770decd-51a7-4591-90be-750a5a4de4f7)

</details>

## Recommended action

The first page in the app has the h1 "File a travel reimbursement claim" which seems to me to be the plain-language title of the form. I recommend updating the first segment of the title tag to match the h1 on the first page: `File a travel reimbursement claim | Veterans Affairs`. Refer to [title tags guidance](https://design.va.gov/content-style-guide/title-tags) for more information.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by benbrasso-agile6** [comment]
I would recommend following the guidelines referenced in the ticket for each page of the app - [title tags](https://design.va.gov/content-style-guide/title-tags)

[H1] | Veterans Affairs

**Comment by brianseek** [comment]
This one may be a bit tricky. It seems like the app name is getting injected as the title from content-build BUT [react-meta-tags](https://github.com/s-yadav/react-meta-tags) is installed, so we can try that out to change title. I don't see other apps using it for that tag but I don't see why it won't work. We should add this to all apps in our wrapper. Pointing with that in mind

**Comment by brianseek** [comment]
@cgednalske / @benbrasso-agile6 / @zach-park This is merged and ready to validate locally, on stage (give like 20 mintues), or in the screenshots of the PR https://github.com/department-of-veterans-affairs/vets-website/pull/31800

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by brianseek** [comment]
Thanks @benbrasso-agile6 ! closing
