### ISSUE TITLE
Staging Review finding: Link for mileage rates opens in a new tab without warning

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91796]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Modernized Check-in
**Product:** eCheck-in
**Feature:** Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software

## Findings details
**VA.gov Experience Standard - issue:** [User experiences an unexpected interaction with a component or pattern.](https://design.va.gov/about/experience-standards/#user-experiences-predictable-interactions-with-components)
**VA.gov Experience Standard - category:** [Usability](https://design.va.gov/about/experience-standards/#category-usability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

On the "Select the appointment..." page, there is a “Check current mileage rates” link inside the blue additional info component that opens in a new tab without warning.

<details><summary>Link, screenshot or steps to recreate</summary>

![check-mileage-rates](https://github.com/user-attachments/assets/83962830-77ee-4a82-ad30-9e2221e9623f)

</details>

## Recommended action

Add "(opens in a new tab)" to the link text.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91796?planning-poker) with Zenhub @brianseek @wullaski

**Comment by benbrasso-agile6** [comment]
LG. Same for this one @zach-park, should be updated in Figma file + prod file.

**Comment by brianseek** [comment]
thanks UX friends. closing

**Comment by zach-park** [comment]
> LG. Same for this one @zach-park, should be updated in Figma file + prod file.

Updated the "LoROTA Travel Reimbursement" Figma file. 
(Prod page is needed but on hold for now until UX team decide what to do for that for production)
