### ISSUE TITLE
Project Kickoff [Notifications]

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/va.gov-team#9180]
## Steps to complete Project Kickoff
- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **Notifications**
- Product Manager (required): **Kennedy Collins**
- DEPO Product Lead (required): **Clarice Chan**
- Entire VFS team (recommended): **Anushya Prasad, Kennedy Collins, Saman Moshafi, Marisa Hoenig, Punit Lad, Phil Herbert, Filip Fafara**

## Scheduling
Preferred dates and times: 
Tuesday 05/26 between 3:00 - 4:00pm ET
Wednesday 05/27 between 2:30pm - 4:00pm ET
Thursday 05/28 between 2:00 - 3:00pm ET

**Comment by meganhkelley** [comment]
Scheduled for 5/26

**Comment by vbellissimo** [comment]
Cancelling/old task.
