### ISSUE TITLE
Onboarding/Offboarding YAML Template Sample

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#91809]
## Description 
_Please include a brief description of the purpose of this ticket._

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@lindsay-insco This is for the next sprint, but if you could include @GWright321 in your work to show him how this would work I think it could be a good training opp!

**Comment by lindsay-insco** [comment]
Draft template [here](https://github.com/lindsay-insco/Test/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&projects=&template=test_required_fields_offboarding.yml&title=Offboarding+of+%5Bindividual%5D)

**Comment by alyssagallion** [comment]
Template completed. Will have leadership approve in next sprint. Closing!
