### ISSUE TITLE
Burial | Findings | port burials code to a module

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#91827]
We want to mimic the pension module approach for the burial code base.  This is to determine LoE for the transition, and break the task into actionable tickets.  See similar breakdown by [searching for "Pension Module" in the PBP engineering tab](https://github.com/orgs/department-of-veterans-affairs/projects/1278/views/14?filterQuery=-label%3AEpic+-status%3AEpics+label%3Aengineering+Pension+Module)

Can reference findings in the mural here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723151653207/96d1b1b708124876a531148a12fe71c865dc040f?sender=ud3f8cf5db16db1f0e9e72209

Burials form (staging) https://staging.va.gov/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez/introduction

Backend entry point https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/burial_claims_controller.rb

Tasks:
- [x] review current burials code base
- [x] create a transition plan
- [x] break down work into smaller tickets

Acceptance:
- [x] present plan
- [x] create tickets

**Comment by aplatt-coforma** [comment]
- 

- [ ] ticket 1
- [ ] ticket 2
