### ISSUE TITLE
SOCKS access for [Nitheesha Karnati]

### ISSUE THREAD

**Issue by NitheeshaKarnati** [department-of-veterans-affairs/va.gov-team#91826]
### Your Name

Nitheesha Karnati

### Your Email

nitheesha.karnati@va.gov

### Your GitHub Handle

nitheeshakarnati

### Your Role and Team

SQA, VA Chatbot

### Product Manager (PM) name and email

Nathalie Rayter

### Product Owner (PO) name and email

nathalie.rayter@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEDKDza2vjuAMgKo1Gii9hUWC2mKkoliMjDgALetQn5l [nitheeshakarnati@nitheeshasmbp2.lan](mailto:nitheeshakarnati@nitheeshasmbp2.lan)

### SSH Key Passphrase

- [ ] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![eQUIP](https://github.com/user-attachments/assets/071815f3-d8d8-44ed-8440-3a096be74e1c)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by patrick-black-oddball** [comment]
User was already in socks - not adjustment needed

**Comment by NitheeshaKarnati** [comment]
Hey @patrick-black-oddball - could you please check if you have the same ssh key on your side matches with this - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJzO+Fbd88Sc3m2c9bsl5IweeB8J5DP3Tu1xsLdpoVXK nitheeshakarnati@nitheeshasmbp2.lan 

I am getting permission denied when I run ssh socks

**Comment by rmtolmach** [comment]
@NitheeshaKarnati the ssh key on the devops side is listed here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/dsva-config/files/authorized_keys/nitheesha.karnati%40va.gov which is the same one that's in the description of this issue. But NOT the same one you pasted in the comment above 😕. i.e. the `ssh-rsa` key is the one we have on file, not the `ssh-ed` one. If it should be the `ssh-ed` key, put that one in the description of this issue.

**Comment by NitheeshaKarnati** [comment]
I updated my public key with the one I have provided in the description but it still says my public ket doesn't match with my private key. Could you please help?

**Comment by barbarello** [comment]
@NitheeshaKarnati Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.

**Comment by NitheeshaKarnati** [comment]
@barbarello still getting the same error. Could you please help? I can reach out on slack.

**Comment by NitheeshaKarnati** [comment]
@barbarello here is the new key ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEDKDza2vjuAMgKo1Gii9hUWC2mKkoliMjDgALetQn5l nitheeshakarnati@nitheeshasmbp2.lan

**Comment by barbarello** [comment]
@NitheeshaKarnati Access granted for your new public key you just added to this ticket ✅

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
