### ISSUE TITLE
Burial | Findings | remove v2 flipper

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#91823]
conflate version of burials to single standard form number and remove flipper

**Comment by ToddWebDev** [comment]
It looks like there is some related code on [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/c728a74dfe86756c06e831dc672a6103e3543ea6/src/applications/burials-ez/config/chapters/01-claimant-information/personalInformation.js#L38-L48) to be removed as well.

**Comment by balexandr** [comment]
This has been removing by running `Flipper.remove(:burial_form_v2)` on dev/staging/prod env
