### ISSUE TITLE
SPIKE: Explore possibility of rendering forms at custom URLs

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#91821]
## Description
10/23/2024: 
Per our meeting with Mikki, having a url structure like `va.gov/digital-form/[form_id]` is not ideal. This messes with breadcrumbs and removes forms from the "area" of the site they might belong.

We need to explore how we might work around this. The issue here effectively boils down to the fact that we want to have a single application render these forms (`form-renderer`) but we don't always want the leading slug (e.g. `digital-form`) in the url that indexes into the application. 

Some considerations:
- We could possibly implement some redirects, but these are ultimately vanity urls and do not "stick". They would redirect back to `digital-form/form-id`, and the same issues (breadcrumbs, etc.) would remain.
- We can perhaps use redirects as just one piece of the puzzle.
- Can we add a list of URLs somewhere that ultimately point into our app?
- What might this mean for our [list-and-loop blocker](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1497)?

## Acceptance Criteria
We might not be able to determine this definitively, so this first spike should explore possibilities and just learn about as many constraints/paths/etc. as possible.
- [ ] Findings are documented in this ticket.

**Comment by Karak888** [comment]
will talk with Mikki first to see if there are any workarounds that Mikki may state.

**Comment by ryguyk** [comment]
# Findings

## Overview
Below, there are four possible options to solving this. **Option 1 appears to be the path forward, at least initially** (see decision record below).

The single biggest takeaway is likely that there will be per-form configuration required _somewhere_ regardless of the option chosen. Going away from a catch-all path that can be indexed via a url parameter (e.g. `va.gov/digital-form/form-123`) towards a custom url for each form (e.g. `va.gov/path/to/form-123`) will require that somebody defines that custom url _somewhere_. That might be as a separate app (option 1), as server-side redirects (options 2 & 3), or as additional, per-form config in a single app (option 4). Ultimately, removing the catch-all path approach will introduce manual steps for url maintenance.

### Option 1: Create individual app for each form
***THIS WILL BE THE PATH FORWARD*** (see decision record below)

Our form-renderer logic could be extracted into a reusable React component that is used in each app. Each app would become a thin wrapper around the component:

```
<FormRenderer url={url} /> 
```
or
```
<FormRenderer formId={formIdFromUrl()} />
```

The specifics would depend on where/how the url mapping to `formId` is stored:
- Stored in Drupal alongside each form
  - In this case, the `<FormRenderer/>` component would hold the logic to convert a url into a `formId`, and so the entire url would be passed. 
  - The Form Builder UI in Drupal (and the Digital Form content type) would have a field for defining the root url.
- Hard-coded in code
  - If the mapping were stored as part of the config for each app, we would then have the `formId` and would pass it to the `<FormRenderer/>` component.

#### Pros
- **This would remove the list-and-loop blocker.**
- As far as these options go, this feels low risk. It's effectively just plugging into the existing, proven way of doing things (an app for each form).

#### Cons
- In line with the key takeaway, this would require a per-form step. Notably, in this case, that step feels larger than in the other options, as it would require an engineer to scaffold an entire app (and would remove us further from the goal of empowering non-technical users to create forms). That said, we could _potentially_ automate this code creation, perhaps triggered by the initial save of the Digital Form node in Form Builder. This wouldn't be straightforward, however, and there would be some human decisions regarding where the app would live, etc.

### Option 2: Rewrite URL on client-side *before* calling `<Router>`, and update all routes accordingly

Effectively, this:
1. Load app at `va.gov/digital-form/{form_id}`
2. Once app is loaded that houses our logic, re-write the current url to exclude `/digital-form`.
3. Define routes for React Router that also exclude `/digital-form`.

As part of this spike, I explored this possibility and came up with a seemingly working solution.

#### Pros
- **This would remove the list-and-loop blocker**
- It seems possible.
- It might be the best option for handling things within our existing approach (a single app) without depending on things outside our team.

#### Cons
- This feels risky. Manipulating urls feels like a hack rather than a bona fide solution.
- This would require server-side redirects to be implemented for each form, so there would still be an engineering task on a per-form basis. So would it really be that much better than option 1?
- It's not immediately clear what this might mean for potential url collisions. If we're manipulating urls within our app, what happens if the url we're changing to is somehow also defined via another app?

### Option 3: Update url on every page load (*after* page load)

#### Pros
- Compared with option 2, this url-rewriting approach is likely lower risk with regard to the potential to break things. All routing would happen as it already does, and we'd simply change the user-facing url *after* page load. It would be merely cosmetic, whereas option 2 would change the structure of all of the routing.
- As far as url rewriting goes, this is probably lower risk with regard to potential url collisions.

#### Cons
- **This would *NOT* remove the list-and-loop blocker**.
- Would require server-side redirects, just like option 2.

### Option 4: Platform changes to handle multiple URLs for an app
Functionally, this wouldn't be significantly different from option 1. It would be implemented differently, but, ultimately, the result would be multiple subdirectories that all load (largely) the same js bundle.

#### Pros
- **This would remove the list-and-loop blocker**
- Theoretically, this would be the cleanest solution, it seems. This would not require any redirects to be implemented (though would require per-form config to define the desired url) while also maintaining a single-app approach.

#### Cons
- This is out of our control and would create a significant blocker.
- It's not immediately clear whether this is even possible.
- It's not immediately clear whether Platform would have an appetite for this.
- This would still require ongoing config updates for defining individual urls for forms.

**Comment by ryguyk** [comment]
# Decision
In a meeting with Matt D on 10/25/2024, we agreed that option 1 (above) is the path to pursue. While it adds some manual steps, it's low risk and solves our problems without creating any blockers. Importantly, it actually removes a blocker (list and loop).
