### ISSUE TITLE
Create General Classes for Error Handling/Logging

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#91828]
refactor the existing class and functions used in pension (and income-and-assets) to be reusable from other form submission workflows

**Comment by aplatt-coforma** [comment]
Wait to do https://github.com/department-of-veterans-affairs/va.gov-team/issues/91824 before revisiting this one

**Comment by balexandr** [comment]
@wayne-weibel I know we briefly chatted about this but can you, in writing, reexplain how you envisioned this working?

**Comment by wayne-weibel** [comment]
@balexandr 
I was thinking something along the lines of a library (`lib/monitor`) with an 'abstract' class which would define a STATS_KEY (overridden in subclass or supplied in the constructor) and group of generic functions for monitoring - a request to a controller, sidekiq job, model changes (?), etc.
The message format and log payload would be consistent - the payload to include a 'statsd' key so the log could be referenced back to the metric, and (if possible) include the function name which invoked the log (ie. Pensions::ClaimController.create, bonus points for file name).
A related thread https://dsva.slack.com/archives/C07QVEDUQ2D/p1728588722593559
