### ISSUE TITLE
Contact Center Review for [Disability Benefits Team 2 - 0781 Post-Submission Failure Emails]

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#91834]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Post-Submission Failure Emails

The Post-Submission Failure emails will be sent to Veterans when a document fails after they submit their 526 claim. One of the documents that can fail are VA Form 0781 and 0781a. Currently, there is no notification to the Veterans that the documents have failed. We have included updated language and an image regarding the Form 0781/a failure email. This is the third email for post-submission failures.  

### Launch Date
*Please provide the launch or rollout date and details.*
We would like to roll out this product guide addition as soon as possible.

### Version Number
*Please provide the version number of the guide and/or video.*
- 526 Benefits Delivery at Discharge- Version 3.2
- 526 Disability Benefits Compensation Claims Application- Version 4.2

### Product Guide
- [526.Benefits.Delivery.at.Discharge.v3.2.product.guid-NN Changes 8.28.24 DRAFT.docx](https://github.com/user-attachments/files/16803208/526.Benefits.Delivery.at.Discharge.v3.2.product.guid-NN.Changes.8.28.24.DRAFT.docx)
- [526EZ.Disability.Benefits.Claims.Product.Guide.v4.2.-NN Changes 8.28.24 DRAFT (1).docx](https://github.com/user-attachments/files/16803210/526EZ.Disability.Benefits.Claims.Product.Guide.v4.2.-NN.Changes.8.28.24.DRAFT.1.docx)

*Please provide product guide link*
- https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Bq1VNW&CID=57e501d8%2D727f%2D427c%2D8d9b%2Df6bd2c3ab274&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FDisability%20Benefits%20Experience%2FDocumentation%2FDrafts

### Product Video
*Please provide product video link*
No video is included.

### Product Video Transcript
*Please provide product video transcript link*
No video transcript is included. 

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Adjusted points total to reflect 2 product guides.

**Comment by starlow00** [comment]
Drafts look good. Sent for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. Working copies are attached for future revisions/additions. Thank you!
[526EZ.Disability.Benefits.Claims.Product.Guide.v4.2.-SRT_09022024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVN2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--544d48a8e2db1324b71343c776000c63d1e9a604/526EZ.Disability.Benefits.Claims.Product.Guide.v4.2.-SRT_09022024.docx)
[526.Benefits.Delivery.at.Discharge.v3.2.product.guide_SRT_09022024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWV2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dddbd3d6b1e3d2fd28397bdda833f77aa2713ba1/526.Benefits.Delivery.at.Discharge.v3.2.product.guide_SRT_09022024.docx)
