### ISSUE TITLE
avoid SSOe auto login loops

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#9184]
SSOe auto login works by testing for a user session on VA.gov and on SSOe, and if the states differ making a request to the API to login.

There are a few scenarios in which a user will be logged into SSOe, but fail to log into VA.gov.  In this case we need to prevent auto login from happening after the first attempt to avoid an infinite loop.

One such scenario, outlined as [error case 5 in the SSOe product guide](https://docs.google.com/document/d/1gG6Ph1xvAYJ9Ith6RA5_F7i-ujYECX0U6j_NfQx-T-U/edit), is when a user signs in and their account has been flagged with suspicious activity.  In this case, SSOe will not redirect the user back to VA.gov, but instead just leave them on the IAM portal in a logged in state.  The inability to redirect back to VA.gov means that we will never be able to establish a session for that user, meanwhile their SSOe session status will always come back as "active".

**Comment by patrickvinograd** [comment]
Will add some more details, but this is critical not just to avoid the auto-login loop, but also to not get the user in a "stuck" state where VA.gov thinks they are not signed in but IAM does. That could happen with or without auto-login, i.e. in response to them explicitly clicking sign-in.
