### ISSUE TITLE
Update List & Loop summary title to accept a description

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#91848]
### Description
The List and Loop summary page title does not seem to currently allow adding a page description. The ArrayBuilderText type does has the following for the summaryTitle: `summaryTitle?: (props: ArrayBuilderTextProps) => string,`. The titleUI form pattern has the following to allow adding a description to all title:
```
{description && (
        <span className="vads-u-font-family--sans vads-u-font-weight--normal vads-u-font-size--base vads-u-line-height--4 vads-u-display--block">
          {description}
        </span>
      )}
```
Therefore, it would create consistency if the summaryTitle allowed passing both a title and a description.

In addition, for our team it would also solve an important recommendation in our work in updating List & Loop minimum items validation. This [Figma thread](https://www.figma.com/design/8iXEp5SC3vo8tpWizduF5F?node-id=11-38184#930454510) in the [List & Loop Minimum and Maximum](https://www.figma.com/design/8iXEp5SC3vo8tpWizduF5F/List-%26-Loop-Minimum-and-Maximum-Validation?node-id=6-9611&t=3LzataC7OqchZJZs-1) discusses this recommendation and the fact that it is currently blocked by the inability to add a description to the summary title:

### Acceptance Criteria
- [ ] The List & Loop summary title can accept a description

**Comment by tjheffner** [comment]
we can't directly write to `ui:description` as the summary page uses that key for the `<Cards>` that get shown. Will need to pass description in elsewhere and reference it, likely in that title area:

```
    if (arrayData?.length > 0) {
      uiSchema['ui:title'] = (
        <>
          {Title}
          {isMaxItemsReached && (
            <MaxItemsAlert>
              {getText('alertMaxItems', updatedItemData)}
            </MaxItemsAlert>
          )}
        </>
      );
      // ensure new reference to trigger re-render
      uiSchema['ui:description'] = <Cards />;
    } else {
      uiSchema['ui:title'] = undefined;
      uiSchema['ui:description'] = undefined;
    }
```
