### ISSUE TITLE
Update submit transformer on 10-7959f-2

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#91849]
As a user, I need my data entered on the frontend to be appropriately transformed to the format expected by the backend so that my form submissions won't be rejected.

**Details**:
The backend expects three specific properties to be present in the form data that aren't currently collected on the front end. They are: `primaryContactInfo`, `supportingDocs`, and `formNumber` - (more details below). These properties need to be created in FMP2's `submitTransformer` file ([see 10-7959a transformer for example](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/ivc-champva/10-7959a/config/submitTransformer.js)):
- `primaryContactInfo`: This contains an object with the name, phone, and email of the person who should be contacted after form submission. In the case of FMP 2 it will be the veteran's information and should take this format:
``` JSON
"primaryContactInfo": {
      "name": { "first": "First", "last": "last" },
      "phone": "2341232345",
      "email": "email@mail.gov"
}
```
- `supportingDocs`: This is an array of any file uploads present in the form data at submit time and looks like this:
```JSON
"supportingDocs": [
      {
        "name": "file.png",
        "confirmationCode": "36650811-4af5-4992-87d2-1aea872245c9",
        "attachmentId": "",
        "isEncrypted": false
      }
 ],
```

- `formNumber`: This is the value stored in the formconfig at `formNumber: formConfig.formId`

**Comment by reiting** [comment]
I've updated this and it is waiting for team approval. As it's just a submit transformer, no screenshots.

**Comment by reiting** [comment]
@marywang2  @baltes  This has been merged. No screenshots since this is just for communication with the BE.
