### ISSUE TITLE
[BE] My VA Forms Status: Filter MVP forms

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#91853]
## Background
We need to restrict the forms we're including in the forms submission status MVP to the following list:

1. 21-4142 & 21-4142a
2. 21-0966
3. 21-10210
4. 21-0845
5. 21-0972
6. 21P-0847
7. 20-10207
 
## Tasks
- [x] Update logic to filter statuses submission from the list provided.

## Acceptance Criteria
- [ ] MVP forms are whitelisted so that forms appear with statuses on My VA 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_: Dev
- _How can this work be validated?_ : Confirm form types are whitelisted in code

**Comment by ajakabcin** [comment]
@tpharrison and @DanielMiller-agile6 we need points and tasks on this when you have a moment :)

**Comment by tpharrison** [comment]
@ajakabcin There's already an estimate of 2 pts on it.

**Comment by ajakabcin** [comment]
whoops my mistake thanks @tpharrison !
