### ISSUE TITLE
decsion: deployificator event ingress logic

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#9186]
In department-of-veterans-affairs/vsp-infra-fluentd#6 @tskinn writes:
> another thing to chew on: All deployment webhook events will be sent to all environments at least as far as I understand right now. The API doesn't really decipher between environments. A webhook can subscribe to all deployment events or none. In other words we need to create a webhook to point to each environment and each webhook will get all deployments regardless of environment.

So we need to figure out how to ingress webhook events, this tickets will serve to document the discussion and decision.

**Comment by nathanhruby** [comment]
Just to get things working in Playground, pop a ELB onto a public subnet and point it at the internal apps ALB.  This setup will always be different from prod, and that's ok.  Most apps won't deploy here, and for things that do, we do want an explicit separate hook.

For the production account where we need to ingress traffic, I assumed we'd route things the same way as we do now for Jenkins (one hook per repo for one target).  What that target is and does I think depends on how strongly we want to isolate internal resources between environments.  

In the "most isolated" case, the thing that actually receives the webhook inspects the payload for the environment param, puts it on a sqs queue for that environment, and lets the deployer instance running in the in the environment pick it up and process it. (this is probably it's own small routing service)

In the "least isolated" case, the thing that actually receives the webhook inspects the payload for the environment param and proxies the request to the right env (if we do this in the revproxy with some openresty logic) or turns around and hits the correct deploy (if we decide to do it in a script).

In all cases the deployer will need to know what env name it is servicing, and validate that the payload is correctly addressed.

**Comment by tskinn** [comment]
I think we are in agreement. Do we have any ATO or other requirements that would push us toward the more isolated scenario? I think we are all drawn toward that direction anyways. What is the point of separate environments if they are all in the same environment kind of a thing. 

I would even be in favor of even having that "router" service running in lambda and pushing events onto queues from there so it isn't really part of any single environment. Then we could move the validation/verification portion to the router as well.

**Comment by nathanhruby** [comment]
I would think to be network accessible in VAEC it'll need to be housed in some environment?

That said, I would prefer to keep the verification portion in the deployer with the rest of the logic.  it makes config simpler and keeps security contexts seperate

**Comment by tskinn** [comment]
Yeah I agree. I'm saying if we were to go the SQS route we could have a lambda do the routing. That lambda would share the codebase with deployer and not be tied to a specific environment.

Something like this:
```
       Github                Lambda               SQS               Nomad

                                               +------------+      +-------------+
                                              /> dev        +------> deployer    |
                                            /- +------------+      +-------------+
     +-------------+       +-------------+/-   +------------+      +-------------+
     |deploy event +------->deploy-router+-----> staging    +------> deployer    |
     +-------------+       +-------------+ \-  +------------+      +-------------+
                                             \ +------------+      +-------------+
                                              \> prod       +------> deployer    |
                                               +------------+      +-------------+
```

Might be a bit overkill but its an idea.

**Comment by nathanhruby** [comment]
I guess that's fine but I am iffy on lambda only because it's yet another thing, but I guess we need a things someplace.
