### ISSUE TITLE
[Spindown] Transfer ownership of all Slack canvases to the enabling team

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#91861]
## Description
Our VA enabling team has asked us to transfer ownership of all Slack canvases to the enabling team. [See Jen's suggestion.](https://dsva.slack.com/archives/C05SUUM4GAW/p1724879115635449)

## Acceptance Criteria: 
- [ ] Audit our Slack canvases (consider a temporary spreadsheet?)
- [ ] Update canvases, if necessary (Note: some of the canvases might be superseded by other spindown content we create; in that case, we should put a banner across the top noting that it's outdated and linking to the updated location where we share that content)
- [ ] Transfer all canvases to enabling team (is this just 1 person or a group? Clarify with Jen or Lesley.)
- [ ] Link to canvases in all relevant places within Github and/or Sharepoint
- [ ] Share with the enablement team and incorporate their feedback, if any

**Comment by hdbaines** [comment]
Link describing how to reassign canvas ownership
 "If the creator of a canvas is deactived from your workspace, an Owner or Admin can transfer ownership of the member's shared canvases"

**Comment by gabezurita** [comment]
I updated ownership for all of the Engineering canvases in the [Slack canvas collection](https://dsva.slack.com/docs/T03FECE8V/F06HU14UKQC), but I do not know the status of the design canvases.

CC @hdbaines

**Comment by kristen101606** [comment]
I've checked that the design canvases are linked to in the right place. As [Gabe noted in Slack](https://dsva.slack.com/archives/C05SUUM4GAW/p1727290855310709), he ensured each canvas had org-wide access.
