### ISSUE TITLE
[Spindown] Document anything that runs on a background schedule

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#91866]
## Description
Our VA enabling team has asked to document anything that runs on a background schedule. 

## Acceptance Criteria: 
- [ ] Include update in Architecture Intent documentation that there are no background schedules for ARP
- [ ] Share with the enablement team and incorporate their feedback, if any

**Comment by kristen101606** [comment]
This doesn't apply because there's nothing to document. Share this with Jen and Lesley, and note this in our documentation so that it doesn't look like an omission.

**Comment by gabezurita** [comment]
Completed as a part of https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/engineering/ADRs/arp-architecture-intent-meeting.md
