### ISSUE TITLE
MR 1%: Remove "what's new" expanding alert

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#91873]
## Description

When MR launches to Phase 0.5, we no longer need to communicate "what's new vs. what's coming soon" to users, because everything will be available now. We don't need to caveat the experience - users in the 1% pool  can try it all out. 

### User story

As a Cartography team member, I want us to remove the blue informational / expanding alert for the feature flag work, so that this will no longer display for users in the 1% pool when MR launches to Phase 0.5. 

### Notes
- [Figma here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=3929-14161&t=T6fn8dGobxTflyXq-4) 

### Landing page w/o the expandable alert
<img width="603" alt="Screenshot 2024-09-05 at 11 56 09 AM" src="https://github.com/user-attachments/assets/bd9549b8-4e4b-4740-87f0-ba83d8383058">

Possible tasks:
- [ ] Remove the blue informational/expanding alert from the Feature Flag work

## Acceptance criteria
- [ ] the blue informational/expanding alert no longer displays for the users who will see the MR Phase 0.5 experience (feature flag work)
- [ ] UX review
- [ ] QA review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the expanding alert is removed from users enabled with this flipper toggle: `mhv_integration_medical_records_to_phase_1`. Users that are not enabled in this flipper toggle still see the expanding alert as expected.

### Landing page without expandable alert on staging:
<img width="1506" alt="Screenshot 2024-09-10 at 1 45 40 PM" src="https://github.com/user-attachments/assets/db3eb5dd-1c5b-4d05-9f62-086cd070056f">
