### ISSUE TITLE
GA4 debug: 2 BTSSS click events

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#91874]
### User story

As a Cartography team member, I want the travel pay link to only send one click event to GA4, so that we can better trust GA4.

### Notes

Very odd:
- Numbers are always almost exactly equal
- We haven't made any changes in the 

Aug 22-29:
- BTSSS double-counting is odd, the text changed a while ago.
<img width="506" alt="image" src="https://github.com/user-attachments/assets/f7af8202-d3da-47a3-b66d-4b5b7351ec7d">

Sept 3 _only_:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/1e634ff8-c14a-481d-9da9-0ab81cfa0fd8">

### Possible tasks:

- Confirm whether both texts exist in the code
- Confirm that both exist post-change
- NavCard.jsx is file to examine
- Check event types for what's recorded in GA4?
- Confirm that this is double-counting

## Acceptance criteria

- Determined why 2 events for travel pay (BTSSS) clicks
- Fixed or requested help as appropriate
- Link clicks are not being double-counted

**Comment by allanto-ah** [comment]
Not sure if this is helpful or anything, but wanted to a drop a note in case, but when inspecting with the browser devtools, I see that the link text are two different things or something. 

https://github.com/user-attachments/assets/3427de31-827b-4500-a078-f60afdd30c87

**Comment by carlosfelix2** [comment]
Using the GA4 debugger, one can see that there are 3 different events being recorded on a link click: 

- click (automatic event) 
  - each time a user clicks a link that leads away from the current domain 
  - uses `(opens in new tab)`
- link click (custom event)
  - by the record event call in our code
  - DOES NOT use `(opens in new tab)`
- outbound link - uses `(opens in new tab)`

Every time a link that goes outside the current domain/hostname is clicked then two more events are logged (click and outbound link). There are a few of such links in the landing page and it includes any links to MHV Classic and other sites like Health Chat. 

The question now is if this is really an issue as the events can be clearly filtered out. A filter with the following should be enough to isolate these events:
event name: link_click
dle_name: nav-linkslist
event_action: click
