### ISSUE TITLE
[Spindown] Document and describe our dashboards 

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#91871]
## Description
Our VA enabling team has asked to document dashboards used for application performance monitoring, analytics, and other purposes, along with short descriptions for how to interpret them. 

## Acceptance Criteria: 
- [ ] Document dashboards in Github and/or Sharepoint 
- [ ] Share with the enablement team and incorporate their feedback, if any

**Comment by kristen101606** [comment]
Dashboards are ready, though not in production. @gabezurita has offered to take on this ticket.

**Comment by gabezurita** [comment]
Completed as a part of https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/engineering/ADRs/arp-architecture-intent-meeting.md
