### ISSUE TITLE
[Spindown] Share a timeline of our changes/releases

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#91870]
## Description
Our VA enabling team has asked to share a simple release timeline that shows what features and changes were released throughout the contract.

## Acceptance Criteria: 
- [ ] Create release timeline
- [ ] Move artifact or link to it within Github and/or Sharepoint (Note: Google Docs and Sheets are not accessible to vA)
- [ ] Share with the enablement team and incorporate their feedback, if any

**Comment by hdbaines** [comment]
Open question for Jen

**Comment by hdbaines** [comment]
Jen said to close this. Not needed
