### ISSUE TITLE
decsion: deployificator cd patterns

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#9187]
In department-of-veterans-affairs/vsp-infra-fluentd#6 @tskinn wrote:
>  I'm not sure what strategy we want to follow as far as auto deployments to environments goes. Currently the command to create a deployment leaves out the environment so it defaults to 'production'. We will need to pick a strategy and setup deployments to environments more specifically that what is in this PR.

So we need to figure out some patterns for doing automatic deployment to envs.  We don't want to be prescriptive to users of the platform how they must do this, but we should have a couple of examples and use them ourselves for our services.

This ticket is to document the discussion and decision

**Comment by nathanhruby** [comment]
My vision here was that teams would implement what was best for their particular service and situation.  

Some probably will want to do manual coordinated releases, some will want to ship master to prod on every commit, but probably we'll have some level of promotion-- for instance, the vets-api model of a daily release train.

Most of this is achievable in CircleCI with filters on tags/branches, timers, and approval workflow type.

So for deployer, I would think
- ci runs tests/security scans on PR's, merge to master blocks on this
- on merge, ci has a master filter that runs tests again, then 
  - builds an artifact, tags with git sha
  - pushes it to repo, 
  - triggers a deploy to playground (and dev?) envs
- when we are ready to release changes beyond dev
  - manually git tag master with a release tag (git tag v 1.2.3) and push
    - optional: create github release with changelog, binaries,  etc..
  - ci sees this tag and takes actions filtered on just tags
    - pulls the image with that git sha, tags it with release, pushes back to repo (or [this](https://stackoverflow.com/questions/37134929/how-to-tag-image-in-docker-registry-v2/38362476#38362476) is ECR supports it
    - ci triggers a deploy for staging, prod, and sanbox with version tag, not git sha tag

For something like vets-api, the manual step would be replaced by a ci workflow on a cron trigger, but would basically be the above.

Does that make sense?  What else do we need to cover?

**Comment by tskinn** [comment]
Make sense :+1:
