### ISSUE TITLE
Access for Karl Brown to AWS console

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#9188]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Crystal Moultrie
- Please provide your name.
   > Karl Brown
- Please Provide your email.
   > kabrown@ThoughtWorks.com or karl.brown1@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > ThoughtWorks, Technical Principal, working on chatbot, devops assessment and notifications
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

SSH key has already been provided, doesn't need to change

- [Grant AWS Console access?]
  > YES
  >  I need to be able to access cloudwatch logs, as we have an endpoint in the back-end rails code.

Previous access request:
ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6661

Note: This access request is to get access to AWS console. I already have socks proxy access to Jenkins/Sentry. I have a PIV card.

**Comment by jbritt1** [comment]
Approval: @Jeff-Hayter 
User: Karl Brown

**Comment by ricetj** [comment]
Karl said he doesn't need AWS access right now and will re-request it if needed in the future
