### ISSUE TITLE
Ability to add in-body alert component on form detail landing pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9189]
## Ability to add in-body alert component on form detail landing pages

On form detail landing pages, we need the ability to display an in-body alert. Enable alert to be added above the `When to use this form + form download link` block.

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/bd326747-7e2b-4c62-afa6-5770446d3566)

**Potential use cases:** 

1. A content editor might need to add alert messaging about a form (for example: NOD form is being retired, therefore, go to this other content to learn about the new appeals process).  

Not urgent - just need to account for this before the content model is set rigid. 

@beeyayjay - Q: will form detail pages be nodes in Drupal? (Want to confirm that they would be and therefore would be able to display global banner for instance.)

**Comment by stephorkandatx** [comment]
The question of where this displays (to the user) would be FE.

**Comment by jenniferlee-dsva** [comment]
@swirtSJW  @stephorkandatx   - added screenshot ^. Looks like I had already specified where in the frontend experience the alert box should be enabled to appear. 

Since this ticket is just to add this capability in the CMS AX, do we need a separate ticket for the frontend work?  @stephorkandatx

**Comment by swirtSJW** [comment]
This was merged and should go out to production on Mon 6/28.

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to validate in Drupal to confirm completion
Can be carried over to sprint 25 for validate

**Comment by jenniferlee-dsva** [comment]
Validated in CMS. (No preview yet, so not validating FE rendering - just that the data can be added and viewed in the CMS AX.)
