### ISSUE TITLE
Provide a comment when Markdown syntax is received by Project Manager

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#919]
@Karak888 will provide this comment after @1Copenut has provided the Markdown guide from Github.

**Comment by 1Copenut** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by Karak888** [comment]
The Github Markdown syntax documentation has been provided and shared with Global UX team being onboarded.  
@lwalsh617 @RLHecht @AnneHurley 
CC:  @ncksllvn @1Copenut
