### ISSUE TITLE
[UX] 10-10EZ - Reg Only: Update designs and content to remove not sure radio button

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#91901]
Why: During review of EZ registration mpv work, PO and OCTO design lead suggested to review the "I'm not sure" radio button option.

Where: This was implemented sometime during final content CAIA and design review. The thinking for leaving it was to gain additional data via google analytics during the experimental proposal. There are concerns that if it doesn't go to a unique page, it is not behaving per radio button best practices. 

#### From Slack: 
Decision made on 8/28/2024
- CAIA (Content)* suggested to provide an "I'm not sure" option, along with the radio options to "Register for connected service care" or "Enroll in the full benefits package".
- When demo'd to PO, concern was brought up that the "I'm not sure" option would direct users through the application and submit.
     - This pathway is the same as the "enroll in full benefits package" option, duplicative action which is not advisable
- The team came together to discuss the "I'm not sure" option, and how best to present it to Veterans

**DECISION MADE**
     - Remove "I'm not sure" as a radio button option
     - Add some hint or other type of text on the screen to guide Veterans to select the "Enroll in full benefits package" option if they are not sure.
     - UX team will discuss with CAIA on proper content
     - We will not launch Reg Only into production until after these changes are made to the current development (in QA)
  
** change was made during content/final design/experiment proposal creation  

----

### Resources
- [Figma link](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5973-8972&t=M889KfkZE75RoW3h-4)
- [Note in CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67133#issuecomment-2318929153)

### Order of Operations / Tasks
- [x] Design to draft options of where to explain 
- [x] Review with CAIA during weekly content sync
- [x] Determine if additional tickets are needed and if so open those and close this
- [x] If this can be resolved during sync, update designs
- [x] Review with PM for sign off

#### Sign off
 - PM (Heather)

**Acceptance Criteria**

The registration only radio button options and content are approved by CAIA and ready to make edits in development.

**Comment by jessicastump** [comment]
Notes from weekly content + ux sync on 8/30/24:
- Recommendation to move hint text into the intro content as a note instead. 
- And add phone number in proximity to mention of HEC instead of in Need help? footer.


Copied notes from Aliyah's (CAIA) doc:

>     * Removing I'm not sure and use that in the hint text and instructing folks to call for help.
>     * UX folks talked about adding content to say that if you're not sure, choose to enroll. They weighed the pros and cons of leading Veterans down one specific path instead of allowing them to call and ask any questions to decide on their own.
>     * HEC expects calls about registration only and they would expect these calls about questions.
>     * Calling HEC will also allow the product team to test waters of registration only. HEC can register them on the phone as well, if that's what they decide.
>     * If HEC getting phone calls about registration team - the product team is hoping to get that information pretty immediately.
>     * For paper form - if someone selects both reg and enroll, HEC process right now is to automatically enroll. This is a future conversation.

**Comment by jessicastump** [comment]
Here is the updated content for sign-off @hdjustice  - there are still two items I am waiting for Aliyah to reply back in Figma. The "apply to enroll" change on the radio button and more clarification on calling for help. [Figma link](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=4870-53411&node-type=SECTION&t=vfDFieG8iTceZAI4-0)

**Question:** Should we run this one screen by HEC again since there were more adjustments?


![Registration](https://github.com/user-attachments/assets/05f64c60-4d9f-4385-9a41-8f707c667872)

**Comment by jessicastump** [comment]
Comments updated in Figma file from Aliya: No other changes/recommendations to what was posted previously in this ticket. Confirm as a team and close this ticket next week.

**Comment by hdjustice** [comment]
Yep, we can check with HEC this week via email.

**Comment by hdjustice** [comment]
Sent an email with before & after screenshots to HEC for review

**Comment by jessicastump** [comment]
HEC approved via email:
