### ISSUE TITLE
Staging Review finding: First segment of title tag should match h1

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91903]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** IVC Forms
**Product:** 10-7959f-1 Foreign Medical Program (FMP) Registration
**Feature:** new product

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The first segment of <title> tag is `Foreign Medical Program (FMP) Registration Form` but the H1 and current breadcrumb are `Register for the Foreign Medical Program (FMP)`. All page title elements should be the same text whenever possible. And, per our [title tag guidance](https://design.va.gov/content-style-guide/title-tags), page titles for forms should use the plain language form or task name.

<details><summary>Link, screenshot or steps to recreate</summary>

![screenshot of title tag](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/74178-erin-title-tags.png?raw=true)

</details>

## Recommended action

Update the first segment of the <title> tag before `| Veterans Affairs` to match the text of the H1.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by reiting** [comment]
<img width="656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU9vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e40aab2c6bb1a1ca74a01678bfd721ef80163c0/Screenshot%202024-09-03%20at%2010.13.44%E2%80%AFAM.png" alt="Screenshot 2024-09-03 at 10.13.44 AM.png" />

**Comment by reiting** [comment]
@marywang2 this is merged and should be in staging.
