### ISSUE TITLE
CT-103: Add analytics to new 103 content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9190]
As a developer, I need to add analytics tracking to the new 103 content so that the team can track the user interaction with the new content to make adjustments as needed in the future.

## Assumptions: 
1. This work is generated from [8959](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-630221895)

## Acceptance Criteria
1. Clicking on "Protection against late VA payments" uses the following analytics: 
```
dataLayer.push({
'event': 'gibct-modal-displayed',
'gibct-modal-displayed': 'protection-against-late-va-payments'
});
```
2. Click on "Read our FAQs on the Veteran Benefits and Transition Act" uses the following analytics:
```
dataLayer.push({
'event': 'gibct-modal-link-click'
});
```

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12741

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-21 at 10.57.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7f84da0f-9a82-4432-b75a-148024e0dcbb)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by sonntag-adam** [comment]
Commented on story [8959](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-630221895) as this is the original request. Not a UX review story.

**Comment by sonntag-adam** [comment]
Awaiting feedback on [8959](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-630221895)

**Comment by desireeturner** [comment]
@dmccurdybah We received feedback on this requesting one more change: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-634663167

**Comment by sonntag-adam** [comment]
Passes current AC, a new story will be created for the removal of the gibct-learn-more event.
