### ISSUE TITLE
10-7959c: confirmation page updates (from CAIA)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91915]
As a user, I want to see the confirmation page so that I know my information has been submitted and can find out what happens next.

[figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=2901-632&t=zTcYeWK9YwVPKEmU-4)

Acceptance criteria:
- Given a VA.gov user fills out the OHI form
- when they submit the form
- they should see the updated confirmation page

**Comment by michaelclement** [comment]
[Work done in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31725). Just waiting on CAIA to provide the URL.

**Comment by marywang2** [comment]
Just got this from CAIA @michaelclement: 
Here's the jump link URL:
https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/#supporting-documents-for-your

And again, noting that this content isn't live yet. It'll point to the "Supporting documents for your application" section of the page when Laura publishes the page. And she'll publish the page in coordination with you all.

**Comment by michaelclement** [comment]
Thanks! Just updated. Now waiting on:

- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9wQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77c6fdc3c9ff6f430569dd59741858303b010b77/Screenshot%202024-09-03%20at%2011.08.34.png" alt="Screenshot 2024-09-03 at 11.08.34.png" />

**Comment by michaelclement** [comment]
@marywang2 @jamiefiore This has been merged in and should be visible on staging shortly. Thanks!

**Comment by marywang2** [comment]
@jamiefiore if you can review - I think we probably need to change to '90 days' to match 10-10d. Also I see that the word 'form' is missing under the "How to contact us" section.
