### ISSUE TITLE
CT-EYB: Update Estimate Your Benefits section based on usability testing feedback

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9191]
As a comparison tool user, I need to understand how the answers to the questions are impacting my potential benefits at an institution so I can make an informed decision about where to use my education benefits.

## Assumptions:
1. This work is completed behind feature flag #7780.
2. Update e2e to test new functionality
3. VET TEC institutions do not have accordions

## Acceptance Criteria
The accordion labels are updated as follows:

1. "Your benefits" is replaced with "Your military details"
2. "About your school" is replaced with "School costs and calendar"
   a."About your school" does not exist for OJT
3. "Learning format and schedule" is replaced with "Learning format and location" for schools only
   a. "Learning format and schedule" for OJT does not change
4. “Scholarships and other funding" is replaced with "Scholarships and other VA funding"

## Supporting Artifacts:
1. N/A

**Comment by amyknox** [comment]
@desireeturner 

The accordion labels are updated:
a. "Your benefits" is replaced with "Your military details"
b. "About your school" is replaced with "School costs and calendar"
c. "Learning format and schedule" Is replaced with "Learning format and location" for schools only.  This label for OJT will stay "Learning format and schedule"

New update
Label for "Scholarships and other funding" should be updated to "Scholarships and other VA funding"

**Comment by desireeturner** [comment]
Issue updated to reflect changes described above by @amyknox.

**Comment by dmccurdybah** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12833

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-01 at 1.37.16 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/eac192bc-854d-4bc4-b722-cd8de5bc0d87)
##
![Screen Shot 2020-06-01 at 1.37.24 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b7c33e77-8231-4f97-8726-e2b74c8e415c)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/430&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging.

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I reviewed and the label updates check out.

**Comment by sonntag-adam** [comment]
Closing story.
