### ISSUE TITLE
Pre-Check-in: Update Content for Medication Review

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#91919]
## Description
Based on feedback from the Appts team's Staging Review for Medication Review, we need to make some changes to the content.

See [Staging Review ticket for Appts team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91567)

## Wireframes

Paragraph/content changes for pre-check-in FE under the Prepare for your appointment heading 

Complete page - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=285-17139&t=DbMmFHqAEf70oinX-4

Appt detail page - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=285-14615&t=DbMmFHqAEf70oinX-4

## Tasks
- Make changes as outlined in the Figma files above

**Comment by brianseek** [comment]
@benbrasso-agile6 on the complete page should this link be `Find out how to check in on the day of your appointment` with `(opens in new tab)` ? Or is it not supposed to open in a new tab? Currently it is `Find out how to check in (opens in new tab)`

On the details page the figma has `Find out how to check in link (opens in new tab)` Is the word `link` supposed to be there? Is there any reason why the link text can't just be the same between the two?

**Comment by benbrasso-agile6** [comment]
Use for both:

`Find out how to check in (link opens in new tab)`

@zach-park do you mind help with updating Figma files?

**Comment by brianseek** [comment]
@benbrasso-agile6 perfect! thank you

**Comment by zach-park** [comment]
> Use for both:
> 
> `Find out how to check in (link opens in new tab)`
> 
> @zach-park do you mind help with updating Figma files?

Productino Figma file is updated.

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 This is merged and ready for validation locally or with the screenshots in the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31787

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by brianseek** [comment]
Thanks @benbrasso-agile6 ! closing
