### ISSUE TITLE
PW intake: Add Spanish toggle and set up left nav for DIC - launch 10/8

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#91910]
### Statuses
**[2024-10-01] [Fran]** **_Request is to have this done by Oct 8th, to dovetail with their redirect._**
**[2024-09-10] [Fran]** Text received. Bumped to Sprint 14 by the Silent Failure spikes. If possible, implement in Sprint 14.
**[2024-09-10] [Fran]** Moving to Next refinement so this will be ready for implementation after we get the translated text.
**[2024-09-05] [Fran]** Comment to Kristin requesting translated text for left nav and breadcrumb.

### Describe your request

We will be redirecting https://www.va.gov/disability/dependency-indemnity-compensation-esp/ to a new URL as part of our family member hub migration. The new URL will be: va.gov/family-and-caregiver-benefits/survivor-compensation/dependency-indemnity-compensation-esp/

Drupal node for this page: 73249

The new page will need:

1. Language toggle
2. Left nav translation: Compensación para sobrevivientes y descendientes (DIC)
3. Spanish breadcrumb: Sobre VA DIC para cónyuges, dependientes y padres

The redirect ticket is here [91851](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91851)

### Time constraints / launch deadlines

Within 1-2 days of redirect being implemented -- ~~we're currently aiming for late September~~ October 8th.

### Your product/team Slack channel

#sitewide-content-accessibility-ia

### Your OCTODE product owner

@mnorthuis

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by FranECross** [comment]
@kristinoletmuskat Will you please provide the left nav and breadcrumb translations that should be used? Thanks in advance!

**Comment by jilladams** [comment]
Tagging into Sprint 13 based on the request for late September timing.

**Comment by kristinoletmuskat** [comment]
@aprocik1 who should we work with on our team to update the spanish content for DIC? I'm not sure if we're changing much other than the H1 (which would effect breadcrumb).

**Comment by aprocik1** [comment]
@kristinoletmuskat: @moviedosoco and @RLHecht lead our translation work.

**Comment by kristinoletmuskat** [comment]
@moviedosoco hey hey! We are migrating this page into the new family member hub, and want to make sure the H1 and left nav label are accurate in the spanish version. We are just moving the page, not changing any of the content, but it's possible we might change the H1 and left nav of the english DIC page -- I think @aprocik1 and @d-beyer are still working on that. Once we confirm whether we're changing the H1 of the english DIC page I thought we could circle back to the spanish to make sure they're aligned!

I put the current spanish translation in the body of the ticket above.

**Comment by moviedosoco** [comment]
Hey @kristinoletmuskat! Since the translations are already completed, @saratorres2 and/or @megzehn can take care of adding the Spanish toggle, left nav bar, and breadcrumbs, to the best of my knowledge.

Thank you.

**Comment by kristinoletmuskat** [comment]
@FranECross hey! I just chatted with @moviedosoco and we do need ya'll to implement, sorry about that!

**Comment by FranECross** [comment]
@kristinoletmuskat No worries! It's refined and in Ready, tagged for the sprint that starts on 9/18. Thanks for confirming!

**Comment by FranECross** [comment]
@kristinoletmuskat Just a quick head's-up that this ticket didn't make it into the sprint that started today due to the silent failure work that was prioritized by Chris. We do have it at the top of the Ready column so that if the team is able to pull it in, they will. Thanks! cc @jilladams

**Comment by kristinoletmuskat** [comment]
HI @FranECross, FYI that this ticket is ready to go. We are aiming to have these set up as close to our 10/8 launch (and the [related redirects](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91851)) as possible -- when do y'all think you might be able to get to this?

**Comment by FranECross** [comment]
Hi, @kristinoletmuskat . Thanks for letting me know! It will be in the sprint starting tomorrow, so I believe we can dovetail with your timing above. I'll put a note in the description and status.

**Comment by chriskim2311** [comment]
@FranECross @kristinoletmuskat Just checking in that we can merge this today for a release tomorrow 10/8. Redirects can be merged for a release on 10/10.

**Comment by chriskim2311** [comment]
@kristinoletmuskat Does this left nav look correct?

<img width="1126" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3MvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ef57d635be2e14f6a50d5beaeb98875b2a440e1/Sobre_VA_DIC_Para_Co%CC%81nyuges__Dependientes_Y_Padres___Veterans_Affairs.png" alt="Sobre_VA_DIC_Para_Cónyuges__Dependientes_Y_Padres___Veterans_Affairs.png" />

**Comment by kristinoletmuskat** [comment]
Hey @chriskim2311 , that png isn't opening for me, but I think the left nav looks right. 

One question about expected behavior -- when there are nested english items below a translated page, and you click on one of those nested items, should the translated left nav persist? I added this video showing my question:

https://github.com/user-attachments/assets/3da8fea7-f7a5-4a26-88d4-30063da66296

**Comment by chriskim2311** [comment]
@kristinoletmuskat Let me ask a Drupal engineer about that, I'll also take a look and see if I can find anything on my end if thats expected or not.

**Comment by chriskim2311** [comment]
@kristinoletmuskat Okay I think the parent link is not set up correctly for them.
Here is an example that is using a toggle with nested links that keep the same translated left nav value.

CMS: https://prod.cms.va.gov/admin/structure/menu/item/3768/.

The parent link for the Spanish nav should be "Survivor Compensation"
And the english links under them should relate to the parent link not the benefit hub.

I'll make the changes and see if they work.

**Comment by jilladams** [comment]
@kristinoletmuskat are you all set here? Wondering if that got resolved / this ticket can close?

**Comment by kristinoletmuskat** [comment]
Yes! We can close
