### ISSUE TITLE
[SPIKE] How are we going to set up a database to store referral IDs? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91911]
## Description 

How are we going to set up a database to store new referral IDs from EPS? (Stephen suggested reusing the existing database. Maybe talking about the CHIP db.)

[Community Care VSS referral to VA Notify userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724857034587/50f5a6735d13d9273970da070a5573385dd7fb2c?wid=0-1724938592386)

## Tasks

- [ ] Flesh out workflow or architecture of storing referrals IDs, encrypting, generating short urls for each referral ID, and managing which short urls (or db records) have been sent to VA Notify (or not yet). E.g., we shouldn't deliver the same referral ID/short url more than once to VA Notify. 
- [ ] Create any implementation tickets needed.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/91911?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by lee-delarm6** [comment]
- receive referral ID from EPS
- encrypt referral ID, store encrypted
- Store data in postgres DB via vets-api
- retrieve as necessary (for passthrough back to EPS

**Comment by benbrasso-agile6** [comment]
Note: We are no longer getting referral IDs from EPS. Right now, it's TBD. I've updated what we know in the userflow here - https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724857034587/50f5a6735d13d9273970da070a5573385dd7fb2c?wid=0-1724938592386
