### ISSUE TITLE
[FE] Integrate Search a Patient's Appointments API Endpoint with FE

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91929]
## Tasks

- [ ] Integrate Search a Patient's Appointments API Endpoint with FE

[API Endpoints](https://dvagov.sharepoint.com/:x:/s/HealthApartment/EawwB7rmk8VAhuTmIkly6HIBnCMjNuN6af5yNGUQsNfPHw?e=4KBugQ)

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created
