### ISSUE TITLE
[FE] Integrate Cancel a Booked Appointment API Endpoints with FE

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91927]
## Tasks

- [ ] Integrate Cancel a Booked Appointment API Endpoints with FE

[API Endpoints](https://dvagov.sharepoint.com/:x:/s/HealthApartment/EawwB7rmk8VAhuTmIkly6HIBnCMjNuN6af5yNGUQsNfPHw?e=4KBugQ)

**Comment by loripusey** [comment]
Cancel is no longer part of the MVP

**Comment by loripusey** [comment]
closing for now; we can open later under a phase 2 epic
