### ISSUE TITLE
Update monitoring channels in slack for staging and prod

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#91956]
Currently we have staging monitors active in #ivc-forms-datadog. For production, we'll update the slack channel to display alerts for prod only.

Implementation:
- Clone
- Update the env
- Add watchtower
- Make polling more frequent

**Comment by balexandr** [comment]
<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVMwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b53d924884995a2c26b8deecdd7f1c5081046b2/Screenshot%202024-09-05%20at%204.07.25%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 4.07.25 PM.png" />
