### ISSUE TITLE
Update staging and prod s3 connections

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#91955]
Work with Cindy/DOCMP to update connections to s3. "Your amazon account now has direct access to all 3 buckets. Please remove the keys and test."

Determine what the third environment is and update as well if we have an equivalent environment.

Acceptance criteria
- Submits from staging.va.gov are sent to the correct s3 bucket with updated credentials
- We're prepared for submits from va.gov (prod) to go to the correct s3 bucket with updated credentials

**Comment by balexandr** [comment]
@cloudmagic80 Can you update this ticket periodically so we know whats happening with your conversations with Adrian/Platform?

**Comment by andrea-merrill** [comment]
Here's the link to the [support thread](https://dsva.slack.com/archives/CBU0KDSB1/p1725636722483499) @balexandr

**Comment by balexandr** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/14696 by platform helped make this work

**Comment by baltes** [comment]
Staging is working, prod will have to be confirmed by upcoming deployment tests.
