### ISSUE TITLE
CT-103: Institutions that should be closed by the sec103 file are still showing in the CT

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9196]
If an institution is listed in the sec103 file and has `FALSE` under `complies with section 103`, the institution should be removed from the comparison tool. Currently, institutions with a `FASLE` value are still showing up on Staging.

## Steps to reproduce

1. Access https://staging.va.gov/gi-bill-comparison-tool/
2. Type "BELLEVUE UNIVERSITY" into the search bar and click Search Schools
- BELLEVUE UNIVERSITY (facility code 31001527) should not be included in the search results
3. Return to Access https://staging.va.gov/gi-bill-comparison-tool/
4. Type "HASTINGS COLLEGE" into the search bar and click Search Schools
- HASTINGS COLLEGE (facility code 31000527) should not be included in the search results

## Desired Behavior

-Any facility with `FALSE` under `complies with section 103` in the sec103 file does not appear in the comparison tool.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/657

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Re-tested on Staging. Closing this issue

Testing passes using this file which closes both institutions in the above steps to reproduce:
[Sec103_test.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4652482/Sec103_test.csv.zip)
