### ISSUE TITLE
Pension + Burial | Validate evidence documents at upload

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#91973]
We want to have validation of uploads as close to the veteran as possible.  We should not wait until sending to LH for this validation (as is currently the case), since an error will delay processing.  There is a function in BenefitsIntake::Service which will perform this validation `valid_document?` - a two fold check using a defined class and also the LH api.

https://dsva.slack.com/archives/C05MS96P6P2/p1725055109120929?thread_ts=1725033430.849399&cid=C05MS96P6P2

**Comment by mjknight50** [comment]
Sanja would like us to hold off on this until she or someone completes and architectural document that covers all groups
cc @sanjabaj2

**Comment by aplatt-coforma** [comment]
We will hold on this ticket until we have completed https://github.com/department-of-veterans-affairs/va.gov-team/issues/92412
