### ISSUE TITLE
10-7959f-2: content updates (intro and address screens) 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91974]
**Intro screen**:
- update intro sentence to add "we may cover the cost..."
- first bullet - add "upload" to "You'll need to upload an itemized billing statement..."
figma [link](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=4338-135299&node-type=section&t=kDgzKGXe9Rkmt5DU-0)

**Address screens** - text removal request per CAIA as potentially confusing to user:
- mailing address screen - remove second sentence.
- home address screen:
  - remove explanatory text below header "Provide the address..."
- [figma link](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=2602-54276&node-type=canvas&t=mPtVpD4SMqt6KI5w-0)

**Comment by marywang2** [comment]
@jamiefiore as an FYI

**Comment by marywang2** [comment]
@rmessina1010 did this get merged - do you know when it will appear on staging?

**Comment by baltes** [comment]
I don't see these changes on staging. Closing this out, but will clone and carry over for confirmation on staging.
