### ISSUE TITLE
Add claim association logic to common travel_pay service in vets-api

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#91972]
## Context
The appointments team has a process in place where they make list-oriented calls rather than single-appt oriented calls. Meaning in this case:
1. A call will be made to fetch all claims for the appointments listed (data stored in redux)
2. When a user navigates to the appt details, the claim will be associated with that appt
3. If a user refreshes the details page the "get single claim" endpoint should be called because the claim information will be lost from the Redux store.

As the travel pay team, we need to make sure the logic for associating a claim with an appointment stays consistent. This logic should be made common in vets-api so the travel pay module, the appointments code, and other modules/code can have the same experience.

## Acceptance Criteria
- [ ] Discover AND document what the logic is to associate claims/appts based on appt date, facility ID, etc
- [ ] Common service created in vets-api
- [ ] Method added that associates a list of appointments with their claims
- [ ] Should not make an external API call

**Comment by liztownd** [comment]
The claims endpoint (either get all or get by appointment date) returns an array of claim objects:

```    {
      "id": "uuid",
      "claimNumber": "string", // internal to BTSSS
      "claimStatus": "PreApprovedForPayment",
      "appointmentDateTime": "2024-09-27T17:38:11.703Z",
      "externalAppointmentId": "string",
      "facilityName": "string",
      "totalCostRequested": 0,
      "createdOn": "2024-09-27T17:38:11.703Z",
      "modifiedOn": "2024-09-27T17:38:11.703Z"
    }
```

In order for a user to submit a new claim, we must send in the BTSSS appointment ID, which can only be retrieved from the `/appointments` endpoint. An appointment object looks like this:

```
    {
      "id": "uuid", // BTSSS appt ID
      "appointmentSource": "API",
      "appointmentDateTime": "2024-09-27T17:40:54.077Z",
      "appointmentName": "string",
      "appointmentType": "EnvironmentalHealth",
      "facilityName": "string",
      "serviceConnectedDisability": 0,
      "currentStatus": "string",
      "appointmentStatus": "string",
      "externalAppointmentId": "string",
      "associatedClaimId": "uuid",
      "associatedClaimNumber": "string", // BTSSS internal
      "isCompleted": true
    }
```

I propose that we associate a VAOS appointment (i.e. what appears in the Appointments list) with a BTSSS appointment. They can be correlated by appt. date-time (which is what we planned to do with claims) and the existence of the `associatedClaimId` or `associatedClaimNumber` can be used to determine whether or not a claim has been submitted for that appointment. If a claim has not been submitted already, at that point we would already have the associated BTSSS appt. ID (required to submit the claim) without making an additional call. 

Two birds, one stone. 

Thoughts or opinions @kjduensing and @ayush-chak ??

**Comment by ayush-chak** [comment]
Additional discovery being conducted since this is a more complex issue than initially expected

**Comment by liztownd** [comment]
[Appointment Association Recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/appointment-association-recommendation.md) document with UX complications and technical considerations.
