### ISSUE TITLE
Staging Review finding: Time zones not present in lab and test results info 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91979]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Health Modernization (vfs-mhv-medical-records)
**Product:** Medical Records
**Feature:** Final Staging Review (Lab and Tests inc: Chem/Hem, Pathology, Microbiology, Radiology Reports)

## Findings details
**VA.gov Experience Standard - issue:** [User experience is not consistent with the VA.gov design principles.](https://design.va.gov/about/experience-standards/#users-experience-is-consistent-with-the-vagov-design-principles)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

Generally, the content style guide recommends including the time zone when referencing times for the sake of clarity. 

## Recommended action

Add the time zone to the date and time information in the format ET, PT, etc. 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Dates, times, phone numbers, and addresses](https://design.va.gov/content-style-guide/dates-and-numbers)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by lichellebain** [comment]
https://jira.devops.va.gov/browse/MHV-61563

**Comment by lichellebain** [comment]
As per 9/11/24 grooming call, the UCD and dev team stated this will not be able to be implemented with the data we are now receiving.

**Comment by shiragoodman** [comment]
@lichellebain thanks for the info. Opening this ticket back up as the issue it not resolved. We ask that SR findings tickets not be closed until the issue is addressed or it is determined not to be an issue. This is still an issue, whether your team has the ability to fixt it or not. Please lmk if you have any questions.

**Comment by bryan-riley-va** [comment]
We intentionally removed the time zone from Vitals and Labs and test results because we want to show the time on the clock when/where the Veteran had the vital/test, and we can't reliably get the time zone for those.
