### ISSUE TITLE
10-7959c: update backend mapping for no Medicare/OHI

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#91997]
Related to this frontend [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/91584), when OHI or Medicare aren't present, we don't need to be checking boxes "No" in those sections (will need to update backend pdf mapping to change this).

Current state: questions in the Medicare and OHI sections are being filled in even when the user answers no.
Expected state: if the user answers no to Medicare or other health insurance, the associated questions should not be filled in.

**Comment by balexandr** [comment]
This has been merged into staging.

**Comment by balexandr** [comment]
@marywang2 I tested this on staging and you can see below that the values are checking NO properly now.

<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnEwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10fb74f56ae15b4da332e1bfa8fa813055c39c00/Screenshot%202024-09-05%20at%203.29.56%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 3.29.56 PM.png" />

**Comment by marywang2** [comment]
@balexandr the fields in the Other Health Insurance section should be blank (not checked 'no') if the user answers 'no' to the question "Do you have health insurance other than Medicare?"

**Comment by baltes** [comment]
@marywang2 I'll go ahead and close, but reopen if I missed anything.
