### ISSUE TITLE
[Data] 10-10EZR: August Monthly Metrics Pull

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#91995]
As a HEC member, I would like to see EZR usage metrics monthly so that I know how the online EZR is doing and we can compare to pre-and-post online EZR launch.

- [x] Pull metrics for the previous month (August)
- [x] Pull metrics we've been pulling (reference [this thread] (or reference May ticket) (https://dsva.slack.com/archives/CMJ2V70UV/p1715630292285879))
- [x] Pull percentage of EZRs submitted with attachments (From June 27 to Aug 1--it was 52%)
- [ ] Pull any other metrics you find interesting
- [x] Pull lifetime (April 11) to date metrics
- [ ] Send to HEC folks
- [ ] **Success: We have pulled and sent monthly metrics to HEC**

**Comment by luis-simauchi** [comment]
Apr 11, 12:00 am – May 12, 11:59 pm	
Metric - From DD
Total submissions:	  
Total Sessions:	
Start to Finish %:	 
% of forms submitted with TERA Questions:	
Avg. session time:	
number of sessions that applications started	
number of failed submissions
Types of status codes present in errors	
Create Error rate

**Comment by luis-simauchi** [comment]
Timeframe:Aug 1, 12:00 pm – Aug 31, 11:59 am
MetricMetric - From DD
successful submission - 4,276
total sessions - 9527
Number of pageviews per session - 3.48
% of forms submitted with TERA Questions: 27.60%
Avg Session Duration - 7 min 1 s
Start to Finish Ratio % - 35.70%
number of sessions that applications started: 3227
failed to submit with no retries - 69
Types of status codes present in errors: 502, 503, 500, 401, 404, 422
Error Rate % - 0.724% (edited) 

Timeframe: Apr 11, 12:00 am - Aug 31, 11:59 am
MetricMetric - From DD
successful submission - 18,801
total sessions - 34,480
Number of pageviews per session - 5.09
% of forms submitted with TERA Questions: 31.12%
Avg Session Duration - 8 min 22 s
Start to Finish Ratio % - 45.58%
number of sessions that applications started: 26,239
failed to submit with no retries - 210
Types of status codes present in errors: 502, 503, 500, 401, 404, 422
Error Rate % - 1.455%

**Comment by luis-simauchi** [comment]
Avg % of submissions with attachment counts in AUG - 50.61%
