### ISSUE TITLE
[BE] [Tech Debt] remove BTSSS feature flag 'check_in_experience_travel_api_v2_cutover' and older configs

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#92006]
The feature flag `check_in_experience_travel_api_v2_cutover` was used to test pointing to the updated configs for BTSSS api. It is running correctly in production and can be removed. We should also remove the old configs from AWS param store and vsp manifests repo.

**Comment by loripusey** [comment]
@randomsync is this going to roll over?

**Comment by randomsync** [comment]
just had a working session with Brian and Nate and was able to validate a travel claim in staging. this will be completed by today.
