### ISSUE TITLE
Update language to SAH housing benefits page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9201]
As a Veteran I need the most up to date, understandable information about SAH housing benefits.

Request from stakeholder:
GM Anne,
I’d like to change some of the recent plain language revisions to the SAH website:
https://www.va.gov/housing-assistance/disability-housing-grants/. 
 
Previously the following language was changed regarding the 3 usages available for SAH eligible Veterans:
•	For FY 2020, you may be able to get up to 3 grants—for a total of up to $90,364—through the SAH grant program.
•	For FY 2020, you may be able to get up to 3 grants—for a total of up to $18,074—through the SHA grant program.
 
These changes are causing some confusion with the Veteran audience, who read this to mean that regardless of how many times they’ve used their grant in the past, they can receive up to 3 grants during FY2020. This is leading to readers calling the RLCs and demanding additional usages outside of what’s allowable by law. It’s important that we clarify the annual grant cap amount, and that Veterans who are rated eligible for the SAH grants get 3 usages over their lifetime, not in FY2020. FY2020 is only relevant to the grant $ amount.
 
Here’s my recommended language:
•	If you qualify for an SAH grant, you can get up to $90,364 for FY 2020.
•	Eligible Veterans may use their grant up to 3 times over their lifetime.
 
•	If you qualify for an SHA grant, you can get up to $18,074 for FY 2020.
•	Eligible Veterans may use their grant up to 3 times over their lifetime.
 
1.	Is a Veteran restricted to getting one (of their three over their lifetime) grant per any fiscal year? In other words, if they apply for one in FY2020, they may still have 2 others to use in other years during their lifetime. That’s correct. They can use any of their 3 usages at any time in their lifetime with not restrictions. So 1 in 2020, 2 in 2037, 3 in 2040, etc.
2.	Could a Veteran get that entire amount we mention as the cap, for both kinds of grants? This year, for instance, could a Veteran get $90,364 for SAH grant? The Veteran can use as much or as little of their entitlement as they choose to use at any time. It all depends on the bid they received from the builder and the adaptations they need. 
3.	Then if #2 is true, would that Veteran still be eligible for additional money in future years, assuming that future amounts would be more than the amount they got in 2020; for example, in FY 2030, if the cap amount is $100,364, could that same Veteran request and receive grant # 2 for $10,000 more? That’s correct. The grant amount follows an industry index and goes up almost every year. That additional cap sits in the Veteran’s “account” until they decide to use the grant again. 

 

Jason Latona: Jason.Latona@va.gov

**Comment by AnneHurley** [comment]
Draft of copy written in Drupal: http://preview-prod.vfs.va.gov/preview?nodeId=750

@RLHecht ready for your review.

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  - can you review the SAH section on the page, as I've added a math example of how a Veteran might use the three withdrawals on a SAH loan over the course of three different years. I want to make sure it's clear.

If you think this approach works, I'll write a math example for the 2nd type, SHA.
http://preview-prod.vfs.va.gov/preview?nodeId=750
Here's the current page: https://www.va.gov/housing-assistance/disability-housing-grants/
@RLHecht  FYSA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley. Looking at this today. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley. Thinking through this, it makes me nervous to offer "fake" amounts for future years for the sake of illustration. I totally see the rationale behind it, but I think people have a tendency to see numbers and they stick in the mind. And I think we can explain this without a math example with something like the following:

**Do I have to use the total grant amount this year?**

No. If you're eligible for an SAH or SHA grant, you can use money from your grant up to 3 different times over your lifetime.

Depending on the adaptations you need, and the bid from your builder, you can use as much or as little of your grant as you need this year. If you don't use the full amount, you can use more money from the grant in future years.

We usually increase the total maximum amount each year based on the cost of construction. You may receive up to the current total maximum amount for the last year you use the grant.

**Additional edits**

In looking at this page, our H2s and H3s go beyond our current 70-character limit. So, I've reworked those to split out the info differently to accommodate shorter H2s and H3s. Let me know if you have questions or concerns before sending to SMEs.

Once you've looked this over and many any final tweaks, we'll want @RLHecht to give it a final look to make sure my changes didn't introduce any errors.

Thanks!

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  Completely understand the rationale for taking out the for-example numbers. I think your wording is good. And thank you for the headline trims. I'll review these and then send to @RLHecht

**Comment by DanielleThierryUSDSVA** [comment]
@AnneHurley @RLHecht. Was thinking through this once more and think we should change "increase" to "adjust" since it sounds like it may not increase _every_ year. Also, just to confirm, do we need to circle back with stakeholders before publishing just to make sure our edits didn't impact accuracy? 

We adjust the total maximum amount each year based on the cost of construction. You may receive up to the current total maximum amount for the last year you use the grant.

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  @RLHecht  Yes, that's a good point. I'll make that fix today.
And I did send the preview link to Jason and his team last night for review. We won't need to re-send to make this last change, I don't think.
A.

**Comment by RLHecht** [comment]
I changed "increase" to "adjust" based on the comment above. This page is now published. Moving to validate @DanielleThierryUSDSVA @AnneHurley

**Comment by RLHecht** [comment]
These changes are validated on the live site. Closing ticket. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
Update 6/12: Per stakeholder request we are adding the word "may" before "adjust" in the sentence Danielle wrote above. Moving to validate and will close again once on live site. FYSA @bethpotts

**Comment by RLHecht** [comment]
Newest change validate on live site. Closing ticket. FYSA @bethpotts
