### ISSUE TITLE
[Spike] [Design] Review date and time page to ensure no changes need to be made

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92021]
## Description 

Veterans will now be assigned a provider to schedule with. There is no selecting a different provider. Of course, content can be present for who to contact if the Veteran has questions. 

Based on this change, going from the intro page to the date and time selection page, are any changes needed to the date and time selection page? Or other pages?

**Comment by Cieramaddox** [comment]
@cgednalske @benbrasso-agile6 

I dont think there are any other pieces of information needed on this page. 

Veteran is give:
Provider name
Type of care
Organization name
Address
Directions 
Phone numbers
Distance

**Comment by benbrasso-agile6** [comment]
Agree with this assessment

**Comment by benbrasso-agile6** [comment]
Closing
