### ISSUE TITLE
[Design] What to do with Edit link for provider on Review page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92026]
## Description 

Now that a Veteran can't change their provider selection, what changes need to be made to the Review page pattern. E.g., remove edit links? Different solution. 

## Tasks

- [ ] Design for new solution of Review page pattern since edit won't be an option on the provider.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/92026?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by Cieramaddox** [comment]
Lets remove the `edit` link. There are a few changes being made to the direct schedule review pages that will have a slight impact on this page. 

[See ticket #90898](https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/90898)
