### ISSUE TITLE
Design Intent - Design Feedback - AE Profile | Notification Settings | Appointment Reminders PHI/PII

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#92020]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Listen to the recording for any feedback from Matt Dingee or Ryan Thurlwell.
- This is looking good. Make sure to do testing around using the 2 check boxes together. Is it completely clear that you do not have to check both boxes? Do they understand that they must check the 2nd box in order to include the health information?
- Also consider if users fully understand what PHI is. Do you need to add content around ... we will not include personal info like blood test... that type of thing. This may not be an issue, user testing will let you know, just some things to think about.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] Must: Align the vocabulary. The checkbox has "include personal health information". The hint text above does not refer to anything as personal health information. Users may not realize that hint text if for the personal health information check box.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by twoangstroms** [comment]
We met with Laura WIllwerth to go over the issues the privacy reviewer had with the content and agreed that we want to proceed with the Collaboration Cycle in regards to the design pattern, treating the verbiage as to be resolved later. The privacy reviewer felt that even the "no PII/no PHI" communications contained PHI, so this requires future work, and that this should not block the new pattern.
