### ISSUE TITLE
Remove Speedcurve references

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#92041]
### Description
I was trying to find out if we are still using SpeedCurve and looks like there was a discussion in Slack ([reference](https://dsva.slack.com/archives/C04868KS69L/p1685557467880359)) and we no longer use SpeedCurve for web performance testing.

### Relevant URLs
- Table should be updated to remove SpeedCurve (https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/track-your-kpis)
- Table should be updated to remove SpeedCurve (https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools)
- Table should be updated to remove SpeedCurve (https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/platform-data-sources)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
OCTO Identity

**Comment by jknipes** [comment]
Hi @asg5704 , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
All work is complete, closing this ticket as _Done_
