### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by hermonica** [department-of-veterans-affairs/va.gov-team#92048]
### Name

J. Monica Lee

### Email

monica@bloomworks.digital

### Role

UX/UI Designer

### Team

Sitewide CAIA

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to monica@bloomworks.digital.

**Comment by hermonica** [comment]
@naomimarcussen Thank you!

**Comment by naomimarcussen** [comment]
You should now have editor access. :)
