### ISSUE TITLE
Documentation support for the redirect process

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#92049]
### Request type

- [ ] Writing new documentation
- [ ] Updating previously published documentation
- [X] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Subject matter expert

Jill Adams/Michelle Middaugh

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [X] Developers
- [ ] Designers and researchers
- [X] Product managers
- [ ] Other

## Background
- Currently, Sitewide Public Websites handles all redirects but the process is changing so that teams can do their own redirects and not be dependent upon our team. Jeff Keene, Mikki Northius, Clint Little, Joe Tice, and Kyle Matheny support this change. 
- Public Websites has documented the existing process to support teams who are doing their own redirects for the first time. 
## The ask
- The PW documentation should be moved from its current home in the Github engineering folder: [Redirect Implementation Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md) to the Platform site so that it has greater visibility and easy access by teams. 
- Additional Platform guidance may need to be added to the documentation, such as 
  - Platform will review redirects for syntax but the requesting team is expected to validate the redirect's behavior and destination
  - information related to the process of requesting and links to the new [Redirects guidance in the Design system](https://design.va.gov/components/url-standards/redirects)
- This change should be broadly communicated to teams

**Comment by jknipes** [comment]
Hi @mmiddaugh, thanks for your content request. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
[A new section has been added to the website](https://depo-platform-documentation.scrollhelp.site/developer-docs/redirect-implementation-strategies), we are closing this ticket as _Done_
