### ISSUE TITLE
10-7959f-1: receiving multiple confirmation emails upon submit

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#92055]
- Issue: getting 3-4 (or more) confirmation emails upon submitting form for 10-7959f-1
- Steps to replicate: Fill out and submit 10-7959f-1 as a signed in user - multiple emails will come through
- Expected results: only 1 email should be received per submit
- URL: https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1

**Comment by balexandr** [comment]
Currently [On Hold] as the fix hasn't gone up yet. Waiting for Platform

**Comment by balexandr** [comment]
@marywang2 I think we should close this. Without a proper way to recreate the issue there isn't much I can do. I placed a couple submissions with no duplicate emails.
