### ISSUE TITLE
10-7959f-1: updates to PDF formatting

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#92068]
- include suffix in the PDF output (currently it's not appearing anywhere in the name fields, even when entered in FE)
  - expected result - suffix should appear in the last name field, alongside last name
- street address line 2 and line 3 should appear on separate lines instead of being concatenated

**Comment by michaelclement** [comment]
Work is done in these two PRs ([1](https://github.com/department-of-veterans-affairs/vets-website/pull/31761), [2](https://github.com/department-of-veterans-affairs/vets-api/pull/18298)) . Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@marywang2 This is ready for review as soon as FMP is back online in staging. Thanks!
