### ISSUE TITLE
MVP Acceptance Criteria

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#9207]
- [x] update question content to match https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/content-messaging.md
- [x] update result screen display to match https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/content-messaging.md
- [x] improve desktop browser display (whitespace on sides)

**Comment by batemapf** [comment]
Still need to reach content parity with the content MD file.
