### ISSUE TITLE
10-10d: Confirmation page updates (latest CAIA edits)

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#92080]
Latest CAIA edits are on this [figma](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=3273-23345&t=e3F6kxCihMOr4jE2-4) for 10-10d.

Set the link for supporting docs on confirm page to: https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/#supporting-documents-for-your

**Comment by michaelclement** [comment]
The confirmation page in the new Figma shows a download link after the 10-7959c bullet point. That will require adjusting how the list of missing files is generated so we can include links in addition to the file names - taking this ticket as an opportunity to do some cleanup of the 10-10d "missing file" logic.

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31794). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
| |before|after|
|-|------|-----|
|Missing files|<img width="355" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOSswQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d15d412c186671585512e6b8e167c6b183be9058/before.png" alt="before.png" />|<img width="417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0MwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d9e5fad8b851f372a75f0e3580b48991e982cf4/after.png" alt="after.png" />|
|All files submitted |   NA   |<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0cwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef573c12a4ca25bd0c7bf13a827f944eb03507a9/Screenshot%202024-09-05%20at%2014.33.12.png" alt="Screenshot 2024-09-05 at 14.33.12.png" />|

**Comment by michaelclement** [comment]
@marywang2 @jamiefiore This is waiting on platform to approve before it can be merged in, but if you see anything in the screenshots above please let me know. Thank you!

**Comment by reiting** [comment]
FYI, this got approved by platform and I just merged it. Should be on staging in an hour or 2.
