### ISSUE TITLE
GA implementation

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9209]
Beyond basic GA metrics, we'd like to track:
- Starts/finishes
- "More screening" results

https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/analytics/

**Comment by batemapf** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9255

**Comment by batemapf** [comment]
We don't have our event trigger names yet, but please use stand ins like `covid19screener-start` or `covid19screener-outcome-fail` (or whatever makes most sense to you).

**Comment by jonwehausen** [comment]
@stephenBarrs and @batemapf Thank you for creating this. Please see comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9255#issuecomment-631615453) for dataLayer requirements.
