### ISSUE TITLE
Define key performance metrics

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#921]

**Comment by Karak888** [comment]
I a moving this to in-progress as I have been doing work on this.  I will create a new ticket to capture the metrics workshop with Insights and Analytics team. We will have pre-work to complete as a team ahead of the 9/10/19 meeting date.

**Comment by Karak888** [comment]
moving this to closed as I have an additional ticket to do second part of KPI workshop for Sprint 4
