### ISSUE TITLE
Prioritized link strategy for landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#92118]
### User story

As a Veteran, I don't want to see any links on the MHV landing page that send me back to MHV Classic, so that I will be more likely to adopt VA.gov.

As a Cartographer, I want to prioritize the types of links we want to tackle first in making the landing page more adoption-friendly.

### Notes
- Make buckets to strategize feasibly removable links to LP
- Use this input to define next step for handling the links

Possible tasks:
- Organize spreadsheet around categories
- Identify process/stakeholders for each category
- Prioritize categories

## Acceptance criteria
- [x] Use past research to verify low and high value links & draft recommendations based on analysis
- [x] Send to Kaitlin for review and ticket next steps as/if appropriate

**Comment by katbrinkley** [comment]
Sara made a [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727450730231/311598e610e0632eafbfcc9c113e7e6f029fa3c0?sender=ud98e9910d55cf2361b974487) for Kaitlin to more easily see the recommendations, was sent for review Friday 9/27
