### ISSUE TITLE
NoK/EC: Move HEC phone number out of additional-info component

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#92121]
### User story

As a Veteran, I want the phone number for updating health care contacts to be always visible instead of hidden behind an expanding component, so that I don't miss it.

### Notes
<img width="418" alt="image" src="https://github.com/user-attachments/assets/de428ce9-3d79-4839-b06e-18fac216764c">

- Medallia responses over the summer show that some Veterans don't have any idea how to update their contacts
- We have learned that very few users expand the expanding alert on MHV Home, and that is arguably more obvious
- Many Veterans complain about updates made in-person at VA appointments don't reach VA.gov; making the HEC phone number more obvious might help them get it changed correctly

Possible tasks:
- 

## Acceptance criteria

- Figma updated with non-expanding "how to update contacts" content
- Implemented: HEC phone number always visible
- QA review
- A11y review

**Comment by carlosfelix2** [comment]
Eng estimate: 2

**Comment by sterkenburgsara** [comment]
est. UX lift: 1 storypoint

**Comment by jonathanjnelson** [comment]
[Link to Figma mocks ](https://www.figma.com/design/uYMdNtQnrzq7OiDl0rPF9k/Profile---Personal-health-care-contacts?node-id=2098-27157&t=CdvdFxTrkiKBEEEO-1)

**Desktop**

<img width="779" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9nQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4319d944d25f0d794dfcdc7b2a959d9a543e3d1f/Screenshot%202024-09-17%20at%205.02.32%E2%80%AFPM.png" alt="Screenshot 2024-09-17 at 5.02.32 PM.png" />

**Mobile** 

<img width="230" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOExnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4d9cee443ccbdf4ec0774f2b510dc223b83db97/Screenshot%202024-09-17%20at%205.06.21%E2%80%AFPM.png" alt="Screenshot 2024-09-17 at 5.06.21 PM.png" />

**Comment by wesrowe** [comment]
looks great tome

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this change has been implemented. No regression issues
