### ISSUE TITLE
Add initial unit tests

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#9213]
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test

**Comment by batemapf** [comment]
Break this out into smaller chunks (e.g. unit testing for specific components).

**Comment by mchelen-gov** [comment]
initial PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12787
