### ISSUE TITLE
Add initial E2E tests

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#9214]
References:
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test/
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/test/

PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12994

**Comment by batemapf** [comment]
Definition of done: at least one end to end test runs during the daily production build that covers at least one piece of our app.

**Comment by mchelen-gov** [comment]
PR merged: https://github.com/department-of-veterans-affairs/vets-website/pull/12994
