### ISSUE TITLE
Update appointment request type logic to accommodate Cerner appointments

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#92185]
## Description
We want to enhance our appointment request logic to accommodate Cerner appointments. Booked Cerner appointments will still have requestedPeriods. To support this, we want to update the logic for requests to:
```
if (isCerner && isEmpty(appt?.end)) {
    return APPOINTMENT_TYPES.request;
  }
  if (isCerner && !isEmpty(appt?.end)) {
    return APPOINTMENT_TYPES.vaAppointment;
  }
```
**This will be a temporary FE change till the vets-api consolidation work is done.**

---

## Development Checklist

- [ ] Update request type logic
- [ ] update tests

### Developer Reference
- [src/applications/vaos/services/appointment/transformers.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/services/appointment/transformers.js#L17)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by ldelacosta** [comment]
Need to move this ticket to `External Dependencies.` 
Staging for OH is down until 11/19.

Issue: Appointments from OH is not shown in staging. 

Waiting until OH is available in staging to re-validate. 

cc: @JRRoof @simiadebowale @Bren22va

**Comment by ldelacosta** [comment]
[Slack thread](https://dsva.slack.com/archives/C062LRFAX7S/p1729709480722409)
[VPG team ticket ](https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea52[…]3b/issues/gh/department-of-veterans-affairs/va.gov-team/95753)

**Comment by ldelacosta** [comment]
Blocked to validate this ticket. Waiting for VPG team to release their changes. Ticket to [track](https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/96070).

**Comment by simiadebowale** [comment]
BE migration complete. Will open FE tickets to clean up code
