### ISSUE TITLE
[0781 Redirect] Limit the new feature to only new claims

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#92199]
Waiting on DEV to provide what element they will use to determine in progress vs. new claim. 

The system must limit the 781 redirect feature to only new claims from the time of release. Claims that were in progress before the release should not be impacted by any changes. 

Example as a way to explain the expectations: 
- If the start date/time of the claim is prior to the date/time of the release, the original flow should be used. 
- If the start date/time of the claim is after the date/time of the release, the new flow should be used. 

We can tell if the user has an inprogress form as part of the inProgressForms attribute that is returned from the user api endpoint. If they have not started a form yet it will be an empty array.

___________________
For an in-progress form we will have the following data, and can determine from it which path to take at the onset of them resuming, if needed, but I thought I recalled us only enabling the flow for new users, meaning we would only check if they had an in progress on or not, if so, take new path (and set a flag, such as version, in it to know it is the new path).

         {
                "form": "21-526EZ",
                "metadata": {
                    "version": 9,
                    "returnUrl": "/review-veteran-details/military-service-history",
                    "savedAt": 1713811317420,
                    "submission": {
                        "status": false,
                        "errorMessage": false,
                        "id": false,
                        "timestamp": false,
                        "hasAttemptedSubmit": false
                    },
                    "cfiMetric": {
                        "initLogged": true,
                        "cfiLogged": false
                    },
                    "createdAt": 1713811314,
                    "expiresAt": 1745347317,
                    "lastUpdated": 1713811317,
                    "inProgressFormId": 31659
                },
                "lastUpdated": 1713811317
            },

**Comment by lisacapaccioli** [comment]
@kylesoskin I copied what you wrote from the spike into here. If you could confirm any requirements that need to be tracked for coding, testing, delivering (whatever) that would be appreciated. Thanks

**Comment by SamStuckey** [comment]
# update
## Context
[Linking for context](https://dsva.slack.com/archives/C04U3EDUR3M/p1727889567510709) to a slack thread where we discuss how to implement this. It seems like the flipper work and the 'new forms only' work are essentially going to be the same change, but that change is more complex than anticipated TL;DR my current understanding
- backend changes are required for both flipper / new use conditions. they should be roughly the same backend change, but this does expand the scope in a meaningful way
- The front end will leverage this backend change in a way that is not super simple to implement. 

## Timeline
I think this pushes out our timeline for this specific change beyond this sprint. I will have a better idea soon about how complex this will be to implement, test, get approved, and roll out. The good news is that these changes are going to be very logically similar to toxic exposure work, so I can use that as a model 

cc @lisacapaccioli

**Comment by lisacapaccioli** [comment]
Moved this feature to the 0781 Paper Sync initiative since we won't be doing the redirect and this feature was intended to be reused for the paper sync.

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
