### ISSUE TITLE
[0781 Redirect] Spike

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#92200]
- [x] Determine how we identify a claim in progress vs. a new claim from the time of release (i.e., we are looking for claims that "start" on or after the release date/time vs. claims that were started before the release) 
- [x] Determine how the toggle switch will direct users to "new" flow vs. "existing" flow 
- [x] Determine how the toggle switch should work for a canary rollout and for whitelisted VA testers
- [x] Determine how to add a new page into the existing flow ???

**Comment by kylesoskin** [comment]
> Determine how we identify a claim in progress vs. a new claim from the time of release (i.e., we are looking for claims that "start" on or after the release date/time vs. claims that were started before the release)

Starting this now, editing as I go.

**Comment by kylesoskin** [comment]
> Determine how the toggle switch will direct users to "new" flow vs. "existing" flow


This can be done multiple ways. One example is via the form version, example here: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/appeals/996/migrations/01-lighthouse-v2-updates.js#L50

We could use this, in combo with a feature toggle.

**Comment by kylesoskin** [comment]
> Determine how the toggle switch should work for a canary rollout and for whitelisted VA testers

We should toggle and test in staging first. We should not really be testing in prod in my opinion. Canary rollout would just be small percent of prod users until confidence builds, after staging testing confirms desired state.

**Comment by kylesoskin** [comment]
> Determine how to add a new page into the existing flow ???

Adding relevant links

https://github.com/department-of-veterans-affairs/vets-website/blob/0b9bd4c51f567c60f44d62ed2d66f2b43a8928d5/src/applications/disability-benefits/all-claims/content/ptsdClassification.jsx

https://github.com/department-of-veterans-affairs/vets-website/blob/0b9bd4c51f567c60f44d62ed2d66f2b43a8928d5/src/applications/disability-benefits/all-claims/pages/uploadPtsdDocuments.jsx

https://github.com/department-of-veterans-affairs/vets-website/blob/0b9bd4c51f567c60f44d62ed2d66f2b43a8928d5/src/applications/disability-benefits/all-claims/pages/ptsd781aChangesIntro.js

https://github.com/department-of-veterans-affairs/vets-website/blob/0b9bd4c51f567c60f44d62ed2d66f2b43a8928d5/src/applications/disability-benefits/all-claims/pages/choosePtsdType.js

https://github.com/department-of-veterans-affairs/vets-website/blob/0b9bd4c51f567c60f44d62ed2d66f2b43a8928d5/src/applications/disability-benefits/all-claims/pages/newPTSDFollowUp.js

https://github.com/department-of-veterans-affairs/vets-website/blob/0b9bd4c51f567c60f44d62ed2d66f2b43a8928d5/src/applications/disability-benefits/all-claims/pages/ptsdWalkthroughChoice781.jsx

**Comment by lisacapaccioli** [comment]
@kylesoskin FYI - They use real people today to do production testing. For instance Toxic Exposure Rico (Coforma) volunteered to test it. The team just had to solution what to do on submit. For this feature, if it's a requirement from OCTO that we do a production validation post release, I don't think a submit is necessary. We only need to validate the new pages, upload a file and that the flow isn't broken. Then there is a process in which they can cancel the claim so there's no impact. Team 1 and the non-disability team have both gone through this before, so if this is necessary, we can work with them on how it's done. From what I heard, VA does not use "fake" user accounts.
