### ISSUE TITLE
Flipper UI access for Mindy Tommasina Miller

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#92205]
### Your Name

Mindy Tommasina Miller

### Your GitHub handle (Flipper UI access is managed through GitHub)

@tommasina-va

### Team, Role, and Company of the target individual

Team Benefits Disability Experience, Full-stack engineer, Nava

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need access because I'm on a VFS team and we are currently releasing work to production under Flipper flags.

**Comment by GWright321** [comment]
Hello @tommasina-va, you are not on the Platform Team Roster in [Confluence](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster).  Please reach out to your Product Manager to be added. I will place NOT YET on this ticket until then. Tag me once you have been added and I will be sure to get you Flipper UI access. Thank you.

**Comment by tommasina-va** [comment]
@GWright321 I'm so sorry about that, I must have accidentally selected Platform! I'm in Atlas.

**Comment by GWright321** [comment]
@tommasina-va No problem. I have confirmed that you are in Atlas and you have been granted access to to both lesser and production. Thank you for your patience.
