### ISSUE TITLE
Content Research/Discovery: Estimate for Manual Entry of Custom Form Content

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9224]
Content research task

**Goal** Develop and communicate a rough LOE (level of effort) for manually setting up additional, aka custom, content for forms, in Drupal, as part of the Form Detail Landing Pages initiative. 

There is custom content that lives outside of the the Forms DB that needs to make its way into Drupal so that it can be managed, updated, etc. alongside the rest of the forms information by our Drupal users. 

Examples of custom content includes a "Related to" field and an online tool URL. There are a few custom extras for our 'top forms' like "When to Use". 

Example of what to expect at https://drive.google.com/file/d/1WHWVLHpiiYDszGJbd6Z73Bcf2QcEGfVC/view

**Tasks**
1. Review the spreadsheet (note: the specific content is NOT COMPLETE but should give a good sense of what to expect)
2. Approximate how long it would take to set up a form that would only have check boxes that need to be set up for 'Related to' and Online Tool Data (a URL + text). 
3. Approximate how long it would take to enter, format fields for a 'top' form that would have the 'Related to' and Online Tool Data fields AND additional custom fields like When to Use This Form
4. Multiply the number from #2 by 460
5. Multiply the number from #3 by 40
6. Add #s 4 & 5 together

**Comment by stephorkandatx** [comment]
I need to add the spreadsheet to this ticket

**Comment by RLHecht** [comment]
@jenniferlee-dsva @stephorkandatx: Danielle and I met to review the LOE on this. See the breakdown below. Note this only includes the work of inputting and reviewing (not building the tool in Drupal). Is this already done or something Beth is currently doing?

We estimate a total of 22-30 hours of work:
11.5 hours to enter the 460 items with 2 fields
11.5 hours to review the 460 items with 2 fields
3.5 hours to enter the 40 items with more fields
3.5 hours to review the 40 items with more fields

Selina will do the work after I give her directive and screen share with her on the first few. This will also be a good way to give her more experience in Drupal. I'll then review when she's finished.

**Comment by jenniferlee-dsva** [comment]
@beeyayjay  - FYSA ^ LOE for manual content entry.

**Comment by jenniferlee-dsva** [comment]
Since the LOE has been completed, I'm closing this ticket.  A new ticket should be created for the backlog to actually do the Drupal entry, post form data migration into CMS. 

FYSA @lunascoop @stephorkandatx @RLHecht
