### ISSUE TITLE
Update Medical Records card design for Phase 0.5 launch

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#92252]
## Description

A few new changes are needed to the landing page (behind FF / 1% of users) to prepare for the Medical Records Phase 0.5 launch. 

### User story

As a Cartography team member, I want to update the landing page for users who will experience the launch of the new Medical Records experience, so that they no longer see "new" tag and misunderstand / are led to believe this means that there are new records for them to view.

Also want to clarify that the experience lets them view & read new records without having to generate a gigantic blue button report download. Signifying a big difference from how this tool was designed on the national portal

### Notes
- On 9/4, Kaitlin reached out to Jonathan and asked for some content changes to the MR box on the landing page, as well as the removal of the "new" tag
  - Kaitlin's message for context: "I prefer no New tag. I’m not sure it provides a ton of extra value and I think it could introduce confusion. But I think we could beef up the content there to “sell” the new version of what you can do here vs. MHV classic. I know Laura is OOO this week. But I’d like to see something like… One new tool allows you to view your medical records online before downloading. You still have the ability to download and print your medical records. Maybe there is something about making it faster to view your medical records." 
- [Mock-ups for the edits are here ](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=3942-2777&t=Y8xisG9NkSiIsvly-4)

Possible tasks:
- [x] UX edit designs to MR box to reflect these new requests 
- [x] Update this ticket to clarify implementation needs from devs
- [ ] Devs update the Medical Records box to match new approved design per Figma here
- [ ] Devs review designs in staging behind FF with QA & UX

## Acceptance criteria
- [x] The medical records box for the 1% launch behind a FF now reflects these updates from [Figma](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=3929-5341&node-type=CANVAS&t=gJgT4xYo4SCU4EHc-0): 
  - remove "new" tag
  - update link text to say: "Get medical records"
  - update content to say: "Get quick, easy access to your medical records. Now you can print or download what you need, when you need it." 
- [x] UX review
- [x] QA review

**Comment by sterkenburgsara** [comment]
Update: content edits approved by Misty (content designer on Mobile App team) while Laura is OOO; also approved by Kaitlin.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that contents have been updated to match Figma.

<img width="1395" alt="Screenshot 2024-09-10 at 1 41 46 PM" src="https://github.com/user-attachments/assets/dd328e3f-2d61-49ce-97ab-2992755abb24">
