### ISSUE TITLE
SOCKS access for Andrew Steele

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/va.gov-team#92264]
### Your Name

Andrew Steele

### Your Email

andrew.steele@adhocteam.us

### Your GitHub Handle

andrew565

### Your Role and Team

Front End Engineer on the Design System Team

### Product Manager (PM) name and email

Carol Wong, Carol.Wong@oddball.io

### Product Owner (PO) name and email

Matt Dingee, matthew.dingee@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC71Wqi8mGWZRTwdwNCPJW4r7lvu2161VsslvWVLiD3D2LxOpkT0p+zQp/DmdMd/8v/VPwX/XsSjV3ZtTaN4DIx+ddA25OBuZ1Xc0h7vAZQNFn0vjlXlMOHRl7HbVNg75mFA/CdjQjkWUe3WlrI5sCJJkN9erdy5tykJQPoXo6utOuRcmyxKT3SA+AuLq7Q48Q5YS9I8c//f4OjMATPtSypZ0loK6zQnVHu1aRVyCrg3TyXDp2CBnWLQ1V39iSFEi2Ar+2+Hy7L44pF6DLAEFGMJg2NrcUZEjD8Lx8plsFJTFO8KWSwxnq6KYMsYh6Ek9yr4QXtRSJSIJxDC18YU56vcqTbLmTUMFfoUJ3WapTe4RZsoVVQGeND0ayglavrtaIy++GFnwvfKFJ/DyxDTZdBVhAl8vswp4EH1ymq55aDnZ6bgyBmmehEBoYSocIGhDc/KZoBGbCiW0fbZRM6n6tqEsQc1YwNlFfmtH8sS07KMblpboRJ9iaNlNVPBK9nNax+pu6tcPq9Yu3+EisHwtA0iCM1o3lRB58l2ZnUz8TTi3DbMv64/BLHQhlYP6VIugKEuFjquUQHofepC0vyYC89sJU2qSNOU5Ue0+dfCmREca41L6BeorPQsq3ZWdOsrd2kTLWy1yf4vnbk7xiHHYMYry255CDKAaYRx3MBZamzYw== andrew.steele@adhocteam.us

### SSH Key Passphrase

- [X] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

e-App awaiting "reciprocity".

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [ ] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by patrick-black-oddball** [comment]
waiting on e-qip ipload

**Comment by Andrew565** [comment]
Here's my COR, which I've been told is even better than an e-app or e-qip transmittal notice.[Steele_COR.pdf](https://github.com/user-attachments/files/17138183/Steele_COR.pdf)

**Comment by Andrew565** [comment]
Got SOCKS Access, closing ticket.
