### ISSUE TITLE
SOCKS access for Joshua Drumm

### ISSUE THREAD

**Issue by JoshingYou1** [department-of-veterans-affairs/va.gov-team#92276]
### Your Name

Joshua Drumm

### Your Email

joshua.drumm@va.gov

### Your GitHub Handle

@JoshingYou1

### Your Role and Team

Software Engineer on the 10-10 health apps team

### Product Manager (PM) name and email

Heather Justice, heather.justice@adhocteam.us/Alex Seelig, Alex.Seelig@Agile6.com

### Product Owner (PO) name and email

Patrick Bateman, patrick.bateman@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyk/UpE/+aX/HBO357XNR4BliFSn8XCICkKnnbIVYCmzacfLJwg9Vd/eibyuPRkqsiyTCdAIf6J11HOVy7PSzic46h/lI5/21gbfr1QC5GK3fv1c5hc3HX5smsZcmlEH82LQIg9wGmg/bMN5ikZTWzdePoH8943aYrPgQoSrRm2QeaXW2t3AUFMacL8fj0DZRAKbVKjCn2Dt0h5/X66GqR2d8wNUt9aAooGRnjjMt9VFBXhhIoR/UWme/GzucEMcc1RylJ5jD9J0laNgcuvmqdL34MyO9u56WiAD0C4IZu2vuHsiNQ9fqlna3+C2Ibn4ngjGSkTdJPFj96tXDAp5FGyBNDs91mtyA6KmkvTxmIiN00XOsSDs1JKVt06fdqXKvAAmjhwuO139e0DB11Czmp8/2YwcZvmbeTyKXZjw3d2D7la9wUk1J2QbJIcHvuzWcSJDIGQnHcdSrz2Ao/rQdNR7IaDp8syXgz16VWA5PLlOUQ0NzRetcOfKxENuFb+sc= Joshua.Drumm@Joshua-Drumm.local

### SSH Key Passphrase

- [X] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![](https://github.com/user-attachments/assets/7eed136d-8a8e-46fc-9290-80d3f9d45bd9)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [ ] Work email address is listed
- [ ] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by JoshingYou1** [comment]
Sorry, can you look for `joshua.drumm@agile6.com` please? I'm already in the developers list here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml#L160

**Comment by davidpetras** [comment]
joshua.drumm@va.gov
