### ISSUE TITLE
ssoe downtime banner

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#9228]
When a `ssoe` maintenance window (the external service) is active, a downtime banner should be displayed indicating that we are having problems with signin.  This should happen on both the sign in modal and the standalone sign in page.

**Comment by ericbuckley** [comment]
@marriej / @bridgethapner when `ssoe` is down, should we use the language for the global downtime banner or the custom text described in the test rails case?

### global banner
```
header: You may have trouble signing in or using some tools or services
text:  We’re doing some work on VA.gov right now. We hope to finish our work
          by {formatDowntime(this.state.globalDowntime.endTIme)}. If you have
          trouble signing in or using any tool or services, check back after
          then.
```

### custom banner
```
header: Our sign in process isn't working right now
text: We're working to fix some problems with our sign in process, which is affecting VA.gov
        and some other VA sites.  If you'd like to sign into VA.gov, please check back later.
```

**Comment by bridgethapner** [comment]
Commented on the pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12720#issuecomment-631508822
