### ISSUE TITLE
Midpoint Review - IA Feedback - Identity, sign-in transition interstitial

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#92292]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Sorry to miss the call yesterday. I love that y'all are doing this intercept. It's going to make the transition easier for many folks!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Should: research Veteran concerns about changing to new sign-in** If possible during your research, if you could try to get a sense of what might make Veterans hesitant to switch sign-ons, that could inform future content design for the interstitial page. Questions I had while thinking about this transition:
  - How will the new logon ID connect to my existing account - or will it? 
  - Do I need to use the same email address to create my new account?
  - Am I going to lose all my existing account information if I have to change to the Login.gov or ID.me sign in option?

- [ ] **Should: get CAIA feedback before research** I know y'all have an open ticket with CAIA; if possible, incorporate any feedback from their content and IA folks before research.

- [ ] **Consider: clearer CTA's for signing in to modernized accounts** On the [user has a modernized account](https://www.figma.com/design/skWgD0gHYGlKSoLdH097OX/USiP-and-sign-in-modal---deemphasize-DSL%2FMHV?node-id=922-458497&node-type=FRAME&t=tLCi0DgPtr4XEIOH-0) views, there are buttons to sign in to Login.gov or ID.me. When scanning only the headings, links, and buttons on the page, it's not clear what the button that says says “Login.gov” does. It's a small thing, but there may be a couple of ways to make it clearer that the button is for **signing in with Login.gov**:
  - Change the button text to `Sign in with Login.gov`, and/or
  - Add a heading near the button to signal that the links below are sign-in links.
  
  ![Screenshot 2024-09-06 at 9 09 07 AM](https://github.com/user-attachments/assets/a6b2f95b-9e3d-461b-b76a-dbfee1e5c363)

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by claytonzook** [comment]
**Should: get CAIA feedback before research** - unfortunately compressed timing doesn't allow us to get CAIA feedback before research, but we feel good about having their suggested content for the sign in page, the MHV sign in page changes, and from the new sign in alert widgets, which we've pulled from and added MPR content suggestions.   
  
**Consider: clearer CTA's for signing in to modernized accounts -** we hear this concern, but with our compressed schedule and research so soon, we're opting not to make this design change right now. We do expect to have some take-aways that will apply to this
