### ISSUE TITLE
Create documentation for VFS teams on how to perform discovery of silent failures

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#92298]
By Thursday 9/12 we need at least a draft of a document that explains to VFS teams how they can perform discovery to determine if they have silent failures, and then ideally what to do with that information (which is, at the very least, report it to OCTO).

**Comment by artsymartha68** [comment]
Perhaps creating a workflow diagram is something every VA.gov team should created.

- I think we can all agree that if a team cannot explain their submission workflow then there is little chance of detecting silent failures. 
- There should be emerging recurring touch points that can be reused within an individual diagram, no sense reinventing or rediscovering repeated processes.
- Time estimate for creating this kind of workflow: a few sprints.
- We could introduce a Silent Failure Review in the governance process, based on these diagrams. 


Workflow diagram examples:
- [Form workflow from VA.gov to VBMS](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702671758787/1eee327caf163786a70af458b56128b9e5b3ce2e?sender=954d567f-8d91-47d1-b8a4-ce33e64ea3a2)
- [526 normal, backup, and emergency failsafe submission flows - high-level diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?sender=fc1d06dd-4c93-48d6-bd4c-75422cd32b16)
- [Service blueprint template](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1602203160048/af3bec42afc01d5d4f67bb99bdad13d7a1c79a84?sender=96f3d866-2966-4d22-9d49-ac6199e14c60)

**Comment by humancompanion-usds** [comment]
PR is up: https://github.com/department-of-veterans-affairs/VA.gov-team-forms/pull/1637

**Comment by humancompanion-usds** [comment]
Continuing to iterate on this:
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md

**Comment by humancompanion-usds** [comment]
Moved this doc to our new shared space: 
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-discover-if-your-app-has-silent-failures.md

**Comment by humancompanion-usds** [comment]
This doc has been shared with OCTO Product Owners in the portfolios. We now just want to add the diagram template for the flow of user data.

**Comment by humancompanion-usds** [comment]
[Template for user data flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726503880361/1915a698f2177e4b779dc68064f349b3392ffe5e?sender=u9ae4d29a0ed5c3d2753a7824) exists and is mentioned in the [How to create a user data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md) documentation. 

I've also announced this today in Team of Teams and followed that up with a post in #vfs-all-teams and #vfs-change-announcements.

I'm marking this as done as this issue was limited to performing discovery.
