### ISSUE TITLE
[FE] 10-10EZ - Facilities: Remove feature toggle

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#92316]
## Benefit to the Veteran
As a Veteran, I want to search for my preferred facility by zip code, so that I can find it quickly and with confidence.

## Scope
Now that the feature has been successfully deployed to production, we can remove the feature toggle from the Facilities API work, however we still want to use the toggle for future Facilities page work.

## Tasks

- [x] Update vets-api to disengage [feature toggle name] from the EZ Facilities API code
  - (instructions: https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)

## Acceptance Criteria
- The feature toggle has been removed from the last EZ Facilities code and is available for re-use in the future

**Comment by hdjustice** [comment]
Validated with Josh Faulkner that there have not been any issues or failures due to the facilities API update completed August 26th. We can move forward with removing the feature toggle

**Comment by Mitch-A6** [comment]
Removed usages in schema, backend, and frontend. We're leaving the flag itself in place for future use so we don't need to go through the whole cycle of re-adding the flag we'll need for impending work

**Comment by hdjustice** [comment]
Is there any further work on this one or are we good to close?
