### ISSUE TITLE
Content review: Section 103 updates to GI Bill Comparison Tool 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#9233]
This ticket captures VSP content feedback on section 103 update to GIBCT: 
Staging link:  https://staging.va.gov/gi-bill-comparison-tool/profile/11929140

## Acceptance criteria

- [x]  Peggy provides content feedback for Sec 103 updates
- [x]  Team incorporates feedback and/or asks follow up questions about the feedback
- [x] Teams leaves comments about feedback they decide not to take
- [x] Peggy checks tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Hello, @amyknox and @dneel-bah Please see below for my content recommendation for Section 103 content. I've also included recommendations for content in the other modal for your review/or to slot in to future work. ;)  Please let me know if you have any questions. 

[https://app.zenhub.com/files/133843125/1aece258-c43f-4bd9-834c-3ced35087cb6/download](https://app.zenhub.com/files/133843125/1aece258-c43f-4bd9-834c-3ced35087cb6/download)

**Comment by dneel-bah** [comment]
Team will review & incorporate the 103 modal updates in #9190.
The non-103 items will be reviewed with EDU and addressed in separate issues.
