### ISSUE TITLE
Contact Center Review for Sitewide Public Websites- Find a Form (aka Find a VA Form)

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#92362]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Find a Form was previously launched, and I've just revised the Product Guide to remove the information regarding a PDF alert banner (removed in ticket [Certificate Alert] Remove PDF Cert Expiration Alerts (end-of-usefulness) #[11520](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11520).

This request is a review of the Product Guide, with subsequent dissemination to the appropriate contact center folks/locations.

Please let me know if I'm also supposed to upload to Github, and if so, which location? (thanks in advance!)

### Launch Date
Previously launched; PDF alert removed

### Version Number
v5 of the Product Guide

### Product Guide

- Sharepoint Word Doc link: [Find VA Forms Product Guide (Word Doc) v5](https://dvagov.sharepoint.com/:w:/s/SitewidePublicWebsites/EfCvsXFgS6tBqYp9235gvRcBmz8YlgyudwFOb5Quv2IILg?e=kWnuWq)
- Sharepoint PDF link: : [Find VA Forms Product Guide (PDF) v5](https://dvagov.sharepoint.com/:b:/r/sites/SitewidePublicWebsites/Shared%20Documents/PW%20products/Find%20a%20Form/Product%20Guides/Find%20VA%20Forms%20Product%20Guide%20v5%20-%202024-09-06.pdf?csf=1&web=1&e=wIejN0)

Product Guides Attached:
[Find VA Forms Product Guide v5 - 2024-09-06.pdf](https://github.com/user-attachments/files/16984645/Find.VA.Forms.Product.Guide.v5.-.2024-09-06.pdf)

[Find VA Forms Product Guide v5 - 2024-09-06.docx](https://github.com/user-attachments/files/16984648/Find.VA.Forms.Product.Guide.v5.-.2024-09-06.docx)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @FranECross! Can you attach the draft to this ticket instead of Sharepoint?

**Comment by FranECross** [comment]
@starlow00 I'll be able to get the draft attached by tomorrow. Apologies for the delay, but when I logged into CAG today, all bookmarks were gone, I no longer had my Outlook account set up, and any work I did in all documents on 9/6 are gone. The product guide when I open it is back to being the template. I'll need to re-create it. 😦

**Comment by starlow00** [comment]
No worries, thanks @FranECross! I had a very similar issue via Citrix today. YourIT fixed me up.

**Comment by FranECross** [comment]
@starlow00 Thanks for your patience! I've attached both MS Word and Adobe PDF documents, as well as the corresponding links on Sharepoint (just for an audit trail).

**Comment by starlow00** [comment]
@FranECross That works, thank you!

**Comment by starlow00** [comment]
Draft looks good, sending for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. A copy is attached to use for future updates and revisions. Thank you!
[Find.VA.Forms.Product.Guide.v5_SRT_09132024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c8b188e7c06c9faf31f1838e5e534545b37d437/Find.VA.Forms.Product.Guide.v5_SRT_09132024.docx)

**Comment by FranECross** [comment]
Thanks so much, @starlow00 !!

**Comment by FranECross** [comment]
Uploaded to GitHub Find a Form contact center folder (product guides) https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form/contact-center
