### ISSUE TITLE
Remove feature toggle va_online_scheduling_med_review_instructions	

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#92385]
## Description
We implemented the medication review instructions 100% on September 2024. We will need to remove the feature toggle from the list and the application code. 

## Requirements 

- [ ] Remove feature toggle `va_online_scheduling_med_review_instructions` from the flipper list and the application code. 

### Design Assets
N/A

---
### Development Checklist

- [ ] Task 1
- [ ] Task 2

 ## Developer Reference
- [ ] [Swagger file]() (remove if not needed)
- [ ] [File path]() (remove if not needed)

### Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/92385?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
No additional issues to report. Closing out the ticket.
