### ISSUE TITLE
Change burials alert channel

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#92392]
# Overview
The burials form is alerting to the [#benefits-non-disability-notifications](https://dsva.slack.com/archives/C06C2D2PJQZ) channel.   Now that this is part of a new team and because the code is so similar to the pension application, we should move this [#benefits-pension-burial-notifications](https://dsva.slack.com/archives/C0667PCPVLM)

https://vagov.ddog-gov.com/monitors/manage?q=burial&order=desc

# Tasks
- [ ] - Change burial monitors to different channel

**Comment by wayne-weibel** [comment]
https://dsva.slack.com/archives/C05MS96P6P2/p1725901374263629

**Comment by mjknight50** [comment]
@sanjabaj2 Took care of this.
