### ISSUE TITLE
[ZOOM]: Section 103 - Modal windows MUST be usable at 200% to 400% zoom

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#9240]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️  Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Several of the modal windows are expanding out of the viewport at 200-250% zoom. I saw this on a few of the longer modals like Yellow Ribbon and the college housing. Screenshot of Yellow Ribbon attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] The modals do not break out of the viewport at any zoom between 200% and 400%
- [ ] No other zoom levels break or change their layout

## Environment

* Any browser, zoomed to 200% or more at 1280px width

## Screenshots or Trace Logs

<img width="1274" alt="Screen Shot 2020-05-18 at 7 54 54 PM" src="https://user-images.githubusercontent.com/934879/82276657-7bfd0d80-994b-11ea-8085-32695592ce23.png">

**Comment by 1Copenut** [comment]
Adding a tag for `BAH-EYB`. This issue is affecting modals for both efforts, and will likely be fixed with the same update.

**Comment by ksantiagomorgan6** [comment]
The fix should affect all modals

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12725

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out for UX!

**Comment by delli-gatti-michael** [comment]
@1Copenut The fix for this is on staging and ready for review

**Comment by 1Copenut** [comment]
Thanks @delli-gatti-michael . Verified in Chrome and IE11 on Staging (Win10). Moving this one to closed.
