### ISSUE TITLE
Toxic Exposure dates with XX for day

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#92417]
## Overview
Some claims are coming through with XX for day. For example, a gulf war 1990 date came over as "2006-06-XX". This is causing issues during submission since LH is expecting empty values e.g. 2006-06 or 2018 for the optional month or day scenarios.

**Comment by christinec-fftc** [comment]
I can reproduce this on gulf war 1990 details pages by selecting a month and entering a year (do not tab into or otherwise touch the date field). I am allowed to continue to the next page without validation.

I then tried reproducing this in [storybook](https://design.va.gov/storybook/?path=/story/uswds-va-memorable-date--with-month-select), however, the date is prepopulated so cannot simulate the same behavior. I then tried to find an example in mock-simple-forms with va-memorable-date and found [this](https://staging.va.gov/mock-simple-forms-patterns/date). I was delighted to see that month year only is [now supported](https://github.com/department-of-veterans-affairs/vets-website/pull/31288) (added just 3 wks ago) which is what we were originally hoping for in the[ toxic exposure mocks](https://www.figma.com/design/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?node-id=569-38927&t=PFBlGI9GrMHwtYRX-1). However the from and to dates are currently configured in the schema as required while TE needs them to be optional. I tried fiddling w/ schema locally, but no luck yet so far. Will continue looking into this.

Despite the current FE findings, I know we've had ongoing issues with date fields and XX's getting passed downstream unexpectedly and we can't always easily reproduce. Since we may also need to clean this up for any IPF's, i'm tempted to recommend we quickly fix this now on the BE to strip out cases of '-XX' days during submission and then continue looking for a better long term solution.

**Comment by christinec-fftc** [comment]
Discussed with Seth and Tommasina and agreed we should do the back end temp fix short term and then create separate tickets for FE and BE long term fixes.

Just noting that we'll essentially need to figure out a compromise between the web component patterns validation and LH which currently looks like this
```
UI pattern 	^(\\d{4}|XXXX)-(0[1-9]|1[0-2]|XX)-(0[1-9]|[1-2][0-9]|3[0-1]|XX)$
LH 		^(?:19|20)[0-9][0-9]$|^(?:19|20)[0-9][0-9]-(0[1-9]|1[0-2])$
```

**Comment by christinec-fftc** [comment]
For longer term FE solution, i updated existing ticket #78113. A feasible change, but would need some design guidance and more robust testing. we might even want to refactor the current unit tests to make it easier and more maintainable to test all the details pages using some utilities. currently it is only testing for the happy path (do all the fields render and can i submit all date fields)

**Comment by sethdarragile6** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18396) approved, merged to master and deployed to Staging. Validated in staging! 👍

**Comment by sethdarragile6** [comment]
Fix was deployed to Production, failing backup submission was successfully remediated upon retry 🎉
