### ISSUE TITLE
Catch 503/504 errors for LGY API

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#92416]
# Overview
We need to catch the 503/504 errors for COE and log them separately than other errors.  We are dealing with excessive monitor noise on errors that are not related to our code.

app/controllers/v0/coe_controller.rb
app/models/saved_claim/coe_claim.rb

The goal here is to catch 503/504 errors and log them with `Rails.logger.info` message and then tie them to a monitor with a super high threshold to be set off.

Then the regular errors should be tied to the existing monitor:
https://vagov.ddog-gov.com/monitors/186673

# Tasks
- [ ] - Separate the logging and monitors for COE

**Comment by mjknight50** [comment]
More context about the errors can be found in these tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90411
https://github.com/department-of-veterans-affairs/va.gov-team/issues/91111

**Comment by tfink419** [comment]
I've created the monitors https://vagov.ddog-gov.com/monitors/272234 and https://vagov.ddog-gov.com/monitors/272235
Each monitors one of the new messages and compares to amount of controller calls that have been logged similarly to the old error. Note that these monitors are of the Log type and the old one was of type Metric, there was no way to monitor based on the message content with a metric-type monitor
