### ISSUE TITLE
[UX] 10-10EZR NoK: Update Design to match EC

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#92420]
As a Veteran, I would like to be able to update my NoK online so that if something happens to me, VHA knows who to contact.

- [x] Update flow to match EC
- [x] Consider how to incorporate Primary/ Secondary into the 
- [x] Update content to match EC
- [x] Share with team
- [x] **Success: We update Figma so that NoK designs match EC and any other required tweaks for NoK**

**Comment by RenataKeck** [comment]
Figma file [here](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=0-11540&t=QvEZ4UlDCGfm8HwH-1). V1 (with red background) demonstrates ideal state for the NOK flow, while V2 reflects what the components in VADS currently permit.
