### ISSUE TITLE
[COGNITION]: EYB - Estimate your benefits SHOULD only read when users press Calculate benefits button in IE11

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#9242]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️  Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

IE11 reads a lot of extra information when I press the "Your benefits" button to close the first set of filters. It's confusing to hear the whole Estimate your benefits panel read when I haven't clicked the calculate button yet. Screenshot attached below.

## Related Issues
* #9241 

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Clicking the accordion buttons inside the Estimate your benefits big accordion should not read extra information. The button should read its name, and announce "expanded" or "collapsed".

## Environment

* Windows 10
* IE11
* JAWS
* https://staging.va.gov/gi-bill-comparison-tool/profile/11801605

## Steps to Recreate

1. Start JAWS screen reader in Internet Explorer 11
1. Load the University of California Berkeley (profile 11801605)
1. Tab to the Your benefits accordion button
1. Press `ENTER` to activate the button
1. Verify you are hearing the paragraph and Estimate your benefits panel read aloud

## Screenshots or Trace Logs

![Screen Shot 2020-05-26 at 8 49 19 AM](https://user-images.githubusercontent.com/934879/82909484-f66ef400-9f2e-11ea-9d53-87ca2b9913a0.png)

**Comment by 1Copenut** [comment]
@desireeturner I'm going to remove this one from the Staging Accessibility Review - GIBCT - Section 103 Updates epic because it's an Estimate Your Benefits issue. I got the two conflated last night while auditing. I'll update the tags so we can track effectively.

/cc @delli-gatti-michael && @sonntag-adam

**Comment by elder-joseph** [comment]
This issue was discovered using JAWS 2019 along with IE 11, After testing this issue using JAWS 2020 with IE 11, this issue is no longer reproducible. Waiting on confirmation of this from @1Copenut in order to close this issue.

**Comment by 1Copenut** [comment]
@elder-joseph I'm having some issue getting updated to JAWS 2020. If you're not seeing the issue anymore, I'm good to move this to close. Will re-open if the VA 508 office is able to recreate the finding in post-launch audit.
