### ISSUE TITLE
[UX/Content] 10-10EZR NoK: Work with CAIA to get NoK content 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#92421]
As a Veteran, I would like to be able to update my NoK online so that if something happens to me, VHA knows who to contact.

- [x] Review EC content with Aliyah
- [x] Make any suggested changes and update designs accordingly
- [x] Rinse and repeat as needed
- [x] Requires definitive primary/secondary, other than that the same
- [x] **Success: CAIA has written/approved content for NoK and we are ready to launch**

**Comment by RenataKeck** [comment]
10/7 - sent questions to HEC stakeholders re: NOK. Aliyah to review screens this week.

**Comment by RenataKeck** [comment]
Content has been reviewed/approved by CAIA and updates have been made to the mocks. I've pinged Derrick to let him know.
