### ISSUE TITLE
[QA] 10-10EZR NoK: Write Test cases for functionality Testing and Accessibility Testing

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#92426]
As a Veteran, I would like to be able to update my NoK online so that if something happens to me, VHA knows who to contact.

- [x] Write test cases
- [x] Write accessibility testing
- [x] **Success: We have written test cases for NoK for feature testing and accessibility testing**

**Comment by allanto-ah** [comment]
Test cases can be found in [Testrail](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=12879)
