### ISSUE TITLE
[COGNITION]: EYB - CONSIDER updating slash yr and slash mo to include screen reader only text

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#9244]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️  Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The Your estimated benefits panel has several `/yr` and `/mo` text strings. These are well-understood by a good percentage of users, but read out very ambiguously to screen readers. I'd like to consider adding screen reader only text to make these more descriptive. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Text reads out clearly and plainly to screen readers

## Possible Fixes (optional)
```diff
- <h5>$10,981/yr</h5>
+ <h5>
+   $10,981
+   <span aria-hidden="true">/yr</span>
+   <span class="sr-only">per year</span>
+ </h5>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2020-05-18 at 9 33 06 PM](https://user-images.githubusercontent.com/934879/82278483-f039b000-994f-11ea-86cf-5032560fcf56.png)

**Comment by 1Copenut** [comment]
@desireeturner && @hughes-dustin This is actually an Estimate your benefits issue. I'll update the labels and issue title, but leave it in the current epic unless you want to move it.

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/12781

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
@1Copenut this is in staging, ready for your review.

**Comment by 1Copenut** [comment]
@sonntag-adam I tested in staging with several combos, all read back 💯 
* JAWS + IE11
* JAWS + Chrome
* NVDA + Firefox
* NVDA + Chrome
* iOS VoiceOver + Safari

Moving this one to close.
