### ISSUE TITLE
Spike | 686 | Staging submission for spouse removal failing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#92466]
## Issue Description
_A test engineer reported that staging submissions on Va.gov for spouse removal due to divorce are not working. They were working prior to 9/3._

---

## Acceptance Criteria
- [ ] Determine why staging claims submissions for spouse removal due to divorce are not going through the primary submission pathway
---

**Comment by steele-lm** [comment]
A flipper related to the get_pension_award service API was turned on to allow us to debug and that caused issues with this submission type in staging. The flipper was turned off and staging functionality was restored.

**Comment by evansmith** [comment]
@steele-lm can we close this?

**Comment by steele-lm** [comment]
Yup, I marked it as done on the project board. I've stopped updating tickets on the zenhub board.
