### ISSUE TITLE
AWS access for Jacob

### ISSUE THREAD

**Issue by pennja** [department-of-veterans-affairs/va.gov-team#92474]
### COR Name

Reney Cook

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Jacob Penner

### Your Email

jacob.penner@adhocteam.us

### Team, Role, and Company of the target individual

Veteran Facing Forms, Software Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Tricia Baker tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee matthew.dingee@va.gov

### Desired AWS Access

I need access to S3 in order to read files uploaded to the /vff-simple-forms directory of the VBA bucket. (This bucket directory will still need to be created)

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2024-09-09 at 3 49 02 PM](https://github.com/user-attachments/assets/df264f36-0231-40d8-872d-8d05bdd3455e)

### Additional Notes

I need access to this resource because my team is building a tool to store pdf backups of user submitted data.

@flooose We are involved in the remediation work in conjunction with @emilytheis and her team.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by megansiddle** [comment]
COR = Reney Cook

**Comment by megansiddle** [comment]
Approvals from PO as might be required.

![](https://github.com/user-attachments/assets/5f1f5363-8054-4a27-96f9-e39ec4346853)

**Comment by patrick-black-oddball** [comment]
could you provide another team members as a reference so we get the permissions correct?

**Comment by megansiddle** [comment]
@patrick-black-oddball no one on the FORMS team currently has access. We are working with the Benefits Team and need to replicate the access that either Sam Stuckey or Kyle Soskin have.

**Comment by patrick-black-oddball** [comment]
Found in Atlas

**Comment by patrick-black-oddball** [comment]
Completed

**Comment by megansiddle** [comment]
@patrick-black-oddball looks like that didn't quite give the permissions we need. He needs to be able to access some of the S3 buckets. I believe Eric Tillberg has the correct setup. Can you replicate his settings for Jacob?

**Comment by humancompanion-usds** [comment]
@patrick-black-oddball - This is critical work. Can this be expedited please? Thanks.

**Comment by barbarello** [comment]
@pennja you have been granted more aws access than Eric.Tillberg who is said to have the correct setup.

**Comment by pennja** [comment]
@barbarello @patrick-black-oddball Thank you for your replies. Unfortunately, I'm currently greeted with the following errors when attempting to access/view S3 buckets on AWS:


![](https://files.slack.com/files-pri/T1ZD0UBMZ-F07N76LF4K1/screenshot_2024-09-23_at_12.20.12___pm.png)

![](https://files.slack.com/files-pri/T1ZD0UBMZ-F07NF483TFG/screenshot_2024-09-23_at_12.19.44___pm.png)
