### ISSUE TITLE
[FE] Referral Review - update design

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#92482]
Referral Details view - The one right after the appointments list page in the user flow.

- [ ] Update FE to match figma design updates
- [ ] Use mock referral data
- [ ] Create some unit tests

https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2217-61186&t=Rq3LontPGEuFBygU-4

Current File

`src/applications/vaos/referral-appointments/ReviewApproved.jsx`

**Comment by lee-delarm6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92482?planning-poker) with Zenhub @brianseek @wullaski

**Comment by wullaski** [comment]
@benbrasso-agile6 This is ready to validate. The PR has a screenshot https://github.com/department-of-veterans-affairs/vets-website/pull/31933

**Comment by benbrasso-agile6** [comment]
LGTM

Can phone value be tel href? 

I would consider this ticket closed. @Cieramaddox @cgednalske, I dropped in one or two comments in Figma to figure out if this is the finalized version. If we do have changes, we would want to add a new page in Figma for the referral page and then we can create a new ticket for FE. For example, here is where I left a few comments: 

https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4?node-id=4968-15975#976978564

https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4?node-id=4378-23957#971226868
