### ISSUE TITLE
[FE] Appointment List - Update design

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#92480]
Update design to match figma design for any missing changes and error states:

https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2169-36402&node-type=FRAME&t=4N7qTNCN0vsYSxVV-0

Location - (only one outside referral-appointments directory most likely)
src/applications/vaos/appointment-list/components/ScheduleNewAppointment.jsx

**Comment by lee-delarm6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92480?planning-poker) with Zenhub @brianseek @wullaski

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created
