### ISSUE TITLE
Vets-api terminal access for Tyler Spangler

### ISSUE THREAD

**Issue by tyler-spangler6** [department-of-veterans-affairs/va.gov-team#92484]
### Your Name

Tyler Spangler

### Your GitHub handle (terminal access is managed through GitHub)

@tyler-spangler6

### Team, Role, and Company of the target individual

Conditions Team, Data Engineer, agile6

### Product Manager (PM) name and email

Yurena Garcia-Hevia, yurenagarcia@navapbc.com

### Product Owner (PO) name and email

Jennifer Bertsch, jennifer.bertsch@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [X] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![image](https://github.com/user-attachments/assets/47b86999-68af-4374-a1e1-937a1904020b)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by GWright321** [comment]
Confirmed in Atlas
Confirmed E-QIP

**Comment by GWright321** [comment]
@tyler-spangler6 you have been granted access to the `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
