### ISSUE TITLE
[Security,IAM] Allow Users Access to Key IAM Metrics

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#92511]
As a Security and Ops engineer I need all AWS users to be aware of their own IAM usage. Without this information they cannot succeed in meeting/practicing Security standards without external involvement.

## Notes
- https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/global

![Image](https://github.com/user-attachments/assets/11b9ce4f-e4ab-4b24-b46e-ff2be099f926)

**Comment by Efe-Oddball** [comment]
Tested what policies needs to be added to grant users access to see IAM Access Key meta data. Currently working on implementing code update.
