### ISSUE TITLE
Contact Center Review for [VAHB Mobile App - Claims and Appeals]

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va.gov-team#92527]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Updates to existing Claims and Appeals UI in the VA Health & Benefits Mobile App. These updates will now include an option for users to submit evidence on an existing (active) claim.

### Launch Date
9/24/2024; app version 2.37

### Version Number
Product guide 7.7

### Product Guide
[DRAFT - VA.Mobile.App.Product.Guide.v7.7_draft.docx](https://github.com/user-attachments/files/16945947/DRAFT.-.VA.Mobile.App.Product.Guide.v7.7_draft.docx)

### Product Video
*Please provide product video link*
n/a

### Product Video Transcript
*Please provide product video transcript link*
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Draft looks good. Sent for VEO review.

**Comment by wavelaurenrussell** [comment]
Please hold off on using this version of the guide; we are not submitting Submit Evidence functionality in this release due to OCTO decisions.

**Comment by starlow00** [comment]
Noted. Informing VEO.

**Comment by starlow00** [comment]
Closing for the time being, per above notice. Will reactivate the ticket if new details emerge.

**Comment by starlow00** [comment]
Understood; I will communicate this to VEO.

From: lauren russell ***@***.***>
Sent: Friday, September 13, 2024 8:31 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: TARLOW, STEVEN R. (ODDBALL INC) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for [VAHB Mobile App - Claims and Appeals] (Issue #92527)


Please hold off on using this version of the guide; we are not submitting Submit Evidence functionality in this release due to OCTO decisions.

-
