### ISSUE TITLE
Analytics Implementation or QA Support for Benefits Management Tools: CST: Subsequent Development Letters

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#92525]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Benefit Management Tools

- **Poduct Name**

    -  Claim Status Tool
      
- **When is the launch date?**
    - 9/16/2024

- **Provide the link(s) for Product/Page urls**
  
    - https://staging.va.gov/track-claims/your-claim-letters

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - We need to be able to track number of downloads over time by letter type, both by doc type ID and by the unique labels we have assigned, which can be found in [this spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/CST%20-%20Letter%20Download%20Codes%20and%20names.xlsx?d=w266d54b5b5db471f84bf21212761bb88&csf=1&web=1&e=PycaTA).
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Row 25 on [this table in the sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
@jacobworrell  -- can you please share another version of the [spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/CST%20-%20Letter%20Download%20Codes%20and%20names.xlsx?d=w266d54b5b5db471f84bf21212761bb88&csf=1&web=1&e=PycaTA). you referenced in this ticket? I'm unable to access.

> We need to be able to track number of downloads over time by letter type, both by doc type ID and by the unique labels we have assigned, which can be found in [this spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/CST%20-%20Letter%20Download%20Codes%20and%20names.xlsx?d=w266d54b5b5db471f84bf21212761bb88&csf=1&web=1&e=PycaTA).

FYI @ChristineYoungZA, @Blivaditis

**Comment by jacobworrell** [comment]
Here is a more accessible version of the spreadsheet @johnny-jesensky-adhoc 

[CST - Letter Download Codes and names.xlsx](https://github.com/user-attachments/files/17100675/CST.-.Letter.Download.Codes.and.names.xlsx)

**Comment by jstrothman** [comment]
@johnny-jesensky-adhoc I gave you access on SharePoint to the [CST Letter Codes and Downloads.xlsx](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/CST%20-%20Letter%20Download%20Codes%20and%20names.xlsx?d=w266d54b5b5db471f84bf21212761bb88&csf=1&web=1&e=1h3RNm) so you can refer to the content source of truth for this work. (No changes have been made since Jacob uploaded a copy to this ticket.)

**Comment by jestutt** [comment]
@jstrothman This request is about adding the letter type to the `claim-letter-download` event right? We don't need the spreadsheet for that. Instead, `letter-type` needs to be added as a variable to the the existing custom dataLayer push event. 

```
event: "claim-letters-download",
gtm.element.textContent: "Download Claim Letter (PDF)",
gtm.elementUrl: "https://staging-api.va.gov/v0/claim_letters/[858]:id.pdf"
letter-type: // letter type 
```

Once it's ready on staging, we can make sure that GTM is seeing the new variable and show you where it will show up in GA. 

cc @johnny-jesensky-adhoc @jacobworrell

**Comment by jstrothman** [comment]
@jestutt That matches what we discussed -- that we'd identify what we wanted to track and put in a request so you all could verify best approach. The Benefits Management Tools team adding in our code the variable `letter-type` with the value of the text string (friendly name for the letter) sounds perfect. Thank you

**Comment by samcoforma** [comment]
@jestutt Hi Jamie,

I'm adding the 'letter-type' field to our GA event logging code right now, and wanted to confirm that the value for this should simply be the doctype if of the letter, and that you'd be mapping these into the friendly short names on the GA side (for reference: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92394#issuecomment-2338657245 ).

For example, the value I'd sent for 'letter-type' would be `859` instead of `Specific evidence request`. Correct?

cc: @jstrothman @jacobworrell

**Comment by johnny-jesensky-adhoc** [comment]
@samcoforma -- Confirming I'm seeing this comment. Jamie is OOO for the next couple of days -- but will have intermittent availability later in the week (starting Wed).

She is going to be the best person to answer this, so I'll flag this for her when she's back.

FYI @jestutt, @jstrothman

**Comment by jestutt** [comment]
@samcoforma Whether you're sending the doctype id or the short name is up to your team as they are the ones who will be using this data, so you probably want to talk to @jstrothman and @jacobworrell. I just tell you what parameter to add to your dataLayer and make sure it shows up in GA. 

@johnny-jesensky-adhoc

**Comment by jstrothman** [comment]
Thank you @jestutt 
@samcoforma @jacobworrell Here's the [user story I shared in Slack](https://dsva.slack.com/archives/C04KHCT3ZMY/p1725661110247619?thread_ts=1724710516.393749&cid=C04KHCT3ZMY):
>User story: As a product team member, I want to generate a single easily readable report that aggregates doc types in useful groupings with recognizable names so I can review and share letter download counts and trends and so I can assess later web activity for people who downloaded letters.

I'd like us to send the short name, not the doctype id: By passing a friendly name to a custom event parameter, we can create a single report usable by us and our stakeholders without needing to manipulate in cumbersome ways.

**Comment by jacobworrell** [comment]
@jestutt just echoing what @jstrothman said. I think a digestible snapshot based on the "short name" is preferable. Is it possible to get both views, though, one broken down by doc id and another by short name?

**Comment by jestutt** [comment]
@jacobworrell There is one dimension in GA4 that you are passing this information into. It's up to your team what you'll send -- doc ID, short name or combination of the two -- but we will not be creating anything new on the GA side for this. 

Something to consider is that the doc ID is passed thru as part of the Link URL so the information is already there if you need it in that form. (screenshot from [Explore report](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/ruUe7encT7a9J2cVm1UQiA)).

![Image](https://github.com/user-attachments/assets/58f2ef07-54cc-44ba-a6da-0b9df03f98d2)

**Comment by samcoforma** [comment]
@jstrothman This has been merged, so short names should start being logged in production later today or tomorrow.
