### ISSUE TITLE
CT: Error in console log

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9252]
1. Go to https://staging.va.gov/gi-bill-comparison-tool
2. Search for a school
3. Select a school
4. If the breadcrumb contains “Search Results” you should see both errors in screenshots below in the developer console of the browser
5. If the breadcrumb does not contain “Search Results” or you go directly to a profile url: the `getBoundingClientRect` error will not appear but the `addEventListener` error will appear

https://www.va.gov/gi-bill-comparison-tool/profile/31800215 and https://staging.va.gov/gi-bill-comparison-tool/profile/14900416.

![image.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/029c6f07-f4f9-4b58-9c09-157bbc1e7f46)
![image.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c62801f5-1f6b-49aa-9770-312b1cf92054)

**Comment by elder-joseph** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12722

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Fix is now in Staging. Closing this issue
