### ISSUE TITLE
Staging Review finding: Inconsistent titles in title tag, current breadcrumb and h1

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#92534]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Debt Resolution
**Product:** Debt Portal
**Feature:** Payment History MVP

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

All the elements on the page that serve as a title are using different text:
- title tag: `Combined Debt Portal | Veterans Affairs`
- breadcrumb: `Debt details`
- H1: `Your Post-9/11 GI Bill debt for books and supplies`

<details><summary>Link, screenshot or steps to recreate</summary>

![Inconsistent title elements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/85533_erin_titletags.png?raw=true)

</details>

## Recommended action

This issue exists across the entire Debt Portal application. Titles should all use the same or similar text when possible. Please update the first segment of the title tag before `| Veterans Affairs`, the current breadcrumb, and the h1 to use the same text. See expanded [guidance on title tags](https://design.va.gov/content-style-guide/title-tags) for additional information. Please work with CAIA to ensure that title tags do not reveal PII/PHI for Google Analytics.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by mgleo** [comment]
@erinrwhite 

@OptionSelect implemented this change very recently [#91555](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/91555). It may have been reviewed before this update was merged.

**Comment by HeatherRienks** [comment]
FYI @Tom-Davis @josephrlee @charlottecesana @denisecoveyduc

**Comment by Tom-Davis** [comment]
Verify this was complete and close if it was.

**Comment by josephrlee** [comment]
I just verified that the h1, title, and breadcrumb matching was indeed done by @OptionSelect [work here](https://github.com/department-of-veterans-affairs/vets-website/pull/31807) and was finished [during midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87951).

<img width="828" alt="Image" src="https://github.com/user-attachments/assets/38b2d3be-8e03-4d6c-b40c-f6a7d255c2d9" />
