### ISSUE TITLE
VSP QA feedback on Section 103 Updates to the GI Bill Comparison Tool [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#9253]
### Feedback legend
**MUST** - in order to meet minimum platform standards the feedback provided *must* be addressed
**SHOULD** - in order to adhere to industry best practices and platform guidelines the feedback provided *should* be addressed
**COULD** - in order to provide the best experience for Veterans the feedback provided *could* be addressed
**COMMENT** - general feedback that does not need to be addressed

### Links
**Test Plan / Execution logs:**
https://dsvavsp.testrail.io/index.php?/plans/view/399
**Coverage for References Report**
https://dsvavsp.testrail.io/index.php?/reports/view/78
**Summary (Defects) Report**
https://dsvavsp.testrail.io/index.php?/reports/view/79

### Feedback
**Test Plan**
1. **COMMENT:** Looks great! The test plan is a manageable size, targets specific user stories, and is built off of well documented user stories.

**Test Execution Logs**
1. **COULD:** While executing test cases it may be advisable to pass each step individually. Per step pass/fail evaluation helps identify exactly which step causes a defect.
1. **COULD:** TestRail supports timed executions. It may be advisable to use the timer during test execution to provide detailed information about how long a test case takes to execute. This information may guide estimates for future execution of the tests or test plan.
![image](https://user-images.githubusercontent.com/52456633/82338046-6a9f1a00-99ba-11ea-8c07-fc29380fb14c.png)

**Coverage for References Report**
1. **COMMENT:** It looks like quite a few more test cases than are in the test plan are covered by this report. Still, there is 100% coverage for references, so that's great!

**Summary (Defects) Report**
1. **COMMENT:** The report indicates that no defects were detected during test execution, great!

## Definition of Done
- [x] Acknowledge each item of feedback with a decision
- [x] VSP QA will close ticket after reviewing feedback decisions

**Comment by desireeturner** [comment]
@pjhill We've reviewed your feedback and incorporated it into our process. Is there anything else that needs to occur before closing this issue? Thank you!

**Comment by pjhill** [comment]
Great — thanks for reviewing!
