### ISSUE TITLE
Analytics Implementation or QA Support for COVID-19 Screening Tool

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9255]
# Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
- Who is this request for?
- What team/project is this work for?

    - Patrick Bateman & the COVID-19 Screening Team
    - Slack: #va-cto-covid-screener
    - Product guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/product-brief.md
     - Demo: Text SCREEN to (919) 355-0995.

- Provide the Domain where Google Analytics needs to be implemented
    - www.va.gov and all lower environments
    - No PII

- Please provide any upcoming deadlines or important milestones
    - Tool will be live on prod by 5/20. Analytics implementation as soon as possible but not a launch blocker.
    
- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* 
We're interested in tracking the number of visitors who begin and complete the screening process. We are also interested in the number of visitors who receive a "more screening needed" (fail state) outcome. Tool will live at www.va.gov/covid19screen (subject to change).
    
- Certain conditions/responses that need to be reviewed

    - "Pass" state: when all questions have been answered with a "No"
    - "Fail" state: when any question has been answered with a "Yes"

- Additional Comments

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @batemapf ,

Thank you! Confirming receipt! Will be in touch on this guy!

**Comment by jonwehausen** [comment]
### Datalayer Requirements

@batemapf @stephenBarrs 
 
### Developer Notes
- @stephenBarrs if it's not too much of a lift -- probably best that we get a click event on each answer button, since technically the user can "start" with any question being answered. We can grab the click text of "yes" or "no" thru GTM. 
- We wont build around if users change their answers for this first iteration - so get a dataLayer push in place for when the user has answered all the questions and a result is returned for the very first time. 



Description of Interaction | Screenshot | dataLayer Example
------------ | ------------- | ------------- 
_Click of any question answer within the series_ | ![image](https://user-images.githubusercontent.com/48527022/82476467-21bf9200-9a9c-11ea-836f-ff4f8e83f65a.png) |`dataLayer.push({`<br>`'event': 'covid-screeening-tool-button-click',`<br>`'screening-tool-question': 'In the past 24 hours, have you had a fever'`<br>`});`
_The **first** time a result is given (all questions answered)_ | ![image](https://user-images.githubusercontent.com/48527022/82476836-9abee980-9a9c-11ea-8b59-323b98806532.png) | `dataLayer.push({`<br>`'event': 'covid-screening-tool-result-displayed',`<br>`'screening-tool-result': 'More screening needed'`<br>`});`

**Comment by stephenBarrs** [comment]
@jonwehausen @batemapf  For the 'start' analytic it is pretty easy to send the event only once regardless of which button is tapped first.   Should we change the 'covid-screening-tool-button-click', event to be more 'start' specific?   If/when we want more granular metrics for each question we can easily add that as well, and I would think that would be a different event type than 'start'?

For the result analytic it will only send an event the first time a user sees a result.

**Comment by batemapf** [comment]
@stephenBarrs are you thinking something like separate event names for each question _a la_ `covid-screening-tool-button-click-q-{n}`?

**Comment by stephenBarrs** [comment]
@batemapf not exactly.  Was thinking something like `covid-screening-tool-start` for the initial click event.  If later we want metrics for each there could be just a single event like `covid-screening-tool-button-click` with data about which button it is.

**Comment by jonwehausen** [comment]
Hi @stephenBarrs / @batemapf , 

Thanks for your input. We're happy to shift to something like `'event': 'covid-screening-tool-start'` on the first button click if that is easier, lower lift. 

My main thought / recommendation is if we soon want to see users changing their answers, tracking across all button clicks will set us up nicely there - that said if not a need or in the foreseeable future, we can hold off and go with the single event push for start.

**Comment by stephenBarrs** [comment]
@jonwehausen  for this MVP launch we would like to track the `covid-screening-tool-start` event.  thanks!

**Comment by bsmartin-ep** [comment]
## QA dataLayer

Description of Interaction | dataLayer Screenshot | Pass?
------------ | ------------- | -----------
_**First** Click of any question answer within the series_ | ![image](https://user-images.githubusercontent.com/62304138/82595443-90bbea00-9b73-11ea-8fd5-40dbea912e91.png) | :question: @jonwehausen - `screening-tool-question` has values like _flu_ and _cough_.  Work for you?
_The **first** time a result is given (all questions answered)_ | ![image](https://user-images.githubusercontent.com/62304138/82595519-b648f380-9b73-11ea-95ee-6b95dd587dac.png) | :heavy_check_mark: **Pass**

**Comment by jonwehausen** [comment]
Thanks @bsmartin-ep for documentation / testing! 

For now, let's hold off on pushing `screening-tool-question` to GA with this event. Let's wait until we get more robust button tracking in place. Also the verbiage of some questions includes (_and may change unbeknownst to us_) multiple things that could require further context than just "flu" or "cough". 

This tracking has been published and is now live in staging / production!
