### ISSUE TITLE
CT: Add COVID Notification to Landing Page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9257]
As a Comparison Tool user, I need to understand the impact that COVID has on my education benefits so that I am aware of any changes and any actions that I need to take.

## Assumptions:
1. This work is completed behind a toggle so that it is only available in the staging environments and below.

## Acceptance Criteria
1. The following content is displayed on the Comparison Tool Landing Page.

> **Coronavirus and VA education benefits**
> 
> Visit [COVID-19 Information affecting education benefits](https://www.benefits.va.gov/GIBILL/COVID19EducationBenefits.asp) for questions on how VA is protecting your GI Bill and other education benefits. 
> 
> Not a student?  [See FAQs for School Certifying Officials (SCOs)](https://benefits.va.gov/gibill/covid19faqs.asp)

2. The content is displayed as a banner and matches DEPO stylings.
3. The banner is displayed between the blue header and the Comparison Tool breadcrumbs.

## Supporting Artifacts:
1. Example Banner:
<img width="1020" alt="example_banner" src="https://user-images.githubusercontent.com/48260534/82345526-5d3a5d80-99c3-11ea-83e6-654d4659eee9.png">

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12799

**Comment by delli-gatti-michael** [comment]
Tested by testrail test case
https://dsvavsp.testrail.io/index.php?/cases/view/627

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-05-27 at 12.08.50 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2483a369-d45f-4795-a226-d6b65e7e8507)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael, @JenLJ and I took a look and this looks good to go!

**Comment by delli-gatti-michael** [comment]
Closing this out with UX and QA approval
