### ISSUE TITLE
Access for Mike Lumetta

### ISSUE THREAD

**Issue by mjlumetta** [department-of-veterans-affairs/va.gov-team#9258]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Mike Lumetta
- Please Provide your email.
   > mike.lumetta@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA API/Lighthouse, Software Engineer, Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPoXCI24+UPu1Y1CFgCqPbx3UWlQY6KHUBVzR3RIe79vAKO8uD8arH1HeJUoeszG56rt19LknzmhaWlE5xNlUDys4tXY2GGBSIl6nLC1O84Zrv6frx48b7IWLYq/eMrkKPq0EzS0fMtnWWBZ9LPQOkpBYDWlnnwFFpFc12tFDr8touGmyyuoLjb+8NhntIjam/uK4wYszRL/VMjBuFjEovwPbZrytsvwPgaUd28eJI3SiMmpw6S9A44ZgrzcYLKx8Zt9X8Hu97NM2Zltsl5w0YlXWjRYAgAXrIn0zVfr7Nh0HlPgYADUdJwrVllwon6YZzxt9PkIBwAwFHJP1ujI3f mikelumetta@Mike-Lumettas-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > YES
  > I need access to CodeBuild for CI jobs, Cloudwatch logs, Credstash secrets, and probably other similar tools during development.

**Comment by mjlumetta** [comment]
tagging @department-of-veterans-affairs/vsp-operations to complete this issue as described in the instructions. thank you!

**Comment by jbritt1** [comment]
Working on SOCKS access now. 

For AWS access:
Approver: @Jeff-Hayter 
User: Mike Lumetta

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jbritt1** [comment]
@mjlumetta, will get you set up shortly. Please hang tight just a bit longer. Working to resolve another issue at this moment.

**Comment by jbritt1** [comment]
AWS account credentials provided to user.
