### ISSUE TITLE
STEM: Research the ability to retrieve applicant entitlement information.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9259]
As a developer, I need to research if it's possible to retrieve the applicants entitlement information so that it can be displayed as part of the 10203 workflow.

## Assumptions:
1. Entitlement is the amount of benefit a veteran has remaining.  This information is most commonly discussed as months/days.

## Acceptance Criteria
1. Documentation outlining how the entitlement information can be retrieved (or why it cannot be) is attached to this story.

## Supporting Artifacts:
1. URL Where the user can find the information themselves: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/

**Comment by dmccurdybah** [comment]
## Summary
The remaining entitlement data is already available in the vets-api EVSS service.

## Existing service code

Service:
  vets-api/lib/evss/gi_bill_status/service.rb

Response:
  vets-api/lib/evss/gi_bill_status/gi_bill_status_response.rb

Entitlement:
  vets-api/lib/evss/gi_bill_status/gi_bill_status_response.rb

## Implementation notes
This will be implemented in the 10203 form profile:

  - vets-api/app/models/form_profiles/va10203.rb

The form profile's mapping will need to be updated to map the data to the prefill response

  - vets-api/config/form_profile_mappings/22-10203.yml

## Example
```ruby
# using the logged in user
service = EVSS::GiBillStatus::Service.new(user)

# get the response
response = service.get_gi_bill_status

if response.success? && response.remaining_entitlement
  months = response.remaining_entitlement.months
  days = response.remaining_entitlement.days
end
```
