### ISSUE TITLE
Prep documentation for Architecture Intent Meeting

### ISSUE THREAD

**Issue by hdbaines** [department-of-veterans-affairs/va.gov-team#92590]
Sam mentioned the following "I just heard from Jeff Keene and Matt Dingee that we are approved to book an Architecture Intent meeting the week of the 23rd". For that meeting we'll need to document some steps found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f462610df9487e17c0049eb85ff992f7e98cde19/platform/engineering/collab-cycle/architecture-intent-meeting.md#architecture-intent-meeting-template)

## Acceptance Criteria
- [ ] Document is created based upon guidelines in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f462610df9487e17c0049eb85ff992f7e98cde19/platform/engineering/collab-cycle/architecture-intent-meeting.md#architecture-intent-meeting-template)

**Comment by gabezurita** [comment]
Draft:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/engineering/ADRs/arp-architecture-intent-meeting.md

**Comment by gabezurita** [comment]
Morning @raudabaugh, just to confirm, this will only cover what is getting pseudo-released into the VA.gov platform, which is the 21a?

**Comment by gabezurita** [comment]
Completed document lives below:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/engineering/ADRs/arp-architecture-intent-meeting.md
