### ISSUE TITLE
Exclude /pittsburgh-health-care* from google search

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#926]
## User Story
A a user of VA.gov, I still recognize pittsburgh.va.gov as the official website for VA Pittsburgh Health Care even though va.gov/pittsburgh-health-care is live, so that I'm not confused by the beta site.

## Goal
The entire /pittsburgh-health-care directory is hidden from google search 

## Acceptance Criteria
When a user visits google.com 
And enters search terms for "VA Pittsburgh" or similar terms
Then the user sees the same results as he sees today including links to pittsburgh.va.gov
And the user does not see any links to va.gov/pittsburgh-health-care

## Definition of Done
-**Attached to a Milestone** (7/23)
-**Labeled with Team** (CMS team support)
-**Labeled with Practice Area** (devops)
- **Labeled with Type** (request)

**Comment by batemapf** [comment]
@jefflbrauer deadline for this is 8/27 (the pittsburgh soft launch date), correct?

**Comment by jefflbrauer** [comment]
@batemapf I'd call that the drop dead date, but ideally the file is updated on production the week prior so we're not coordinating on an hourly basis the day of launch.

**Comment by ncksllvn** [comment]
robots.txt will be updated in production after today's daily!

**Comment by jefflbrauer** [comment]
Woot! Thanks @ncksllvn :)

**Comment by ncksllvn** [comment]
[Visible now](https://www.va.gov/robots.txt)!
