### ISSUE TITLE
Design feedback - Staging Review: Section 103 Updates to the GI Bill Comparison Tool 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#9262]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**

- The Section 103 in mobile view: The “x” covers the modal title here. We recommend to move any long modal titles to the next line so it doesn’t cover the "x"

**Try:**

- No “try” feedback for now

**Consider:**

- No “consider” feedback for now

**Definition of Done:**
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by amyknox** [comment]
@desireeturner @dneel-bah -Section 103 in mobile view: The “x” covers the modal title here. We recommend to move any long modal titles to the next line so it doesn’t cover the "x"

Think Kenny addressed this issue so don't want this story hanging out in the backlog unnecessarily.

**Comment by ksantiagomorgan6** [comment]
issue will be resolved along with ZOOM]: Section 103 - Modal windows MUST be usable at 200% to 400% zoom fix #12725
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12725

**Comment by desireeturner** [comment]
@emilywaggoner @CrystabelReiter The issue listed as "Do" has been resolved (see comment above from @ksantiagomorgan6 regarding the changes) and is now available on Staging for review. Please let us know if there is anything else you all need from us in order to close this out. Thank you!

**Comment by CrystabelReiter** [comment]
Thank you! I'll close now
