### ISSUE TITLE
UX: Kick off and refine user research study

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#92627]
### User story

As a Cartography team member, I want to define the direction of our next user research study, so that we can get it started.

### Notes
- Kickoff discussion with Robyn scheduled for Wed 9/24 at 5:30pm
- Ask + understand all internal team questions from Canvas needed in order to decide on research study goal and write the research plan

Possible tasks:
- Kickoff with stakeholders 
- Follow up kickoff with stakeholders 2.0 
- Draft research plan
- [Info about research plan and research at VA here](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)

## Acceptance criteria
- Met with all stakeholders and gathered feedback/preferences
- Identified a final research goal/research direction 
- Drafted the research plan
- Created follow-on tickets or separate tickets as needed

**Comment by katbrinkley** [comment]
This ticket might change based on our kickoff calls - tbd

**Comment by fmccaf1** [comment]
[Attempts made to learn about research done so far and answer the questions that Robyn posed as part of the research.](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727282271817/371efea8086edf6d386e9599bcfae6660af3c8b0?sender=ua13e567cb5c4221acaa14949)

**Comment by fmccaf1** [comment]
At this point, Robyn and UX-ers on the team have seen the research plan and have had opportunity to add comments/suggest edits. However, there are some key pieces missing that go into more detailed planning, i.e. how many participants? What are exact sourcing criteria? When will we be able to conduct interviews? These details will have to ironed out eventually but I'm not sure that they need to be answered right now. I think the main blocker is UX folks feeling some stuck-ness between just one or two people making a decision and moving forward, or working on putting together a longer team discussion and deciding together.

**Comment by fmccaf1** [comment]
@katbrinkley thanks for adding those notes in the mural! I just added some stickies to that section of questions that are still unanswered at this point.

**Comment by fmccaf1** [comment]
If we decide to close this ticket, we can open ticket(s) for the following tasks:
- Double-back on meeting with tool teams and getting answers to the questions in the mural board
- Finalize research plan (including exact recruiting requirements and dates for interviews)
- Once research plan is finalized, bring the doc into Github in the correct location
- Anything else?

**Comment by katbrinkley** [comment]
Update: Meeting with Anne to go over follow up questions Friday 11/1 for follow up questions
