### ISSUE TITLE
[Development/Design] Original Claims: Add Messaging to Use DS Logon for Missing EDIPI

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#9263]
## User Story or Problem Statement
We have deployed Original Claims in Production but due to missing EDIPI by not using DS Logon and inability to send veterans to VAMCs for correcting their IDs.

The messaging should be updated to reflect either using DS Logon or apologizing (due to COVID and not being able to go to VAMC) for having to go back to eBenefits to file their claim.

Essentially, we need to update some wording that says:
- Sorry your account is not configured for VA.gov use.
- DS Logon should work, so try using that.
- You can also go ahead and use eBenefits.
- Usually you can go to a VAMC to get your account sorted.

but we can't do that right now due to COVID-19.

## Acceptance Criteria
- [ ] Wording updated at some stage before getting to the error from MVI

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
I think that we should do this ticket first. https://github.com/department-of-veterans-affairs/va.gov-team/issues/9448. The main reason we don't have edipi is lack of identity-verification

**Comment by annaswims** [comment]
if you don't seen  'evss-claims' or  'original-claims' we know that we are either missing the EDIPI or the SSN and can't continue. 

Criteria for both:
'evss-claims'
    if user.edipi.present? && user.ssn.present? && user.participant_id.present?
'original-claims'
    if user.edipi.present? && user.ssn.present? && (user.birls_id.blank? || user.participant_id.blank?)

**Comment by Mottie** [comment]
This messaging is ready to be merged, but the call center asked us to delay implementation for 2 weeks to allow for training. Will follow up and merge this work in about 2 weeks.
