### ISSUE TITLE
FE | Contact Info Refresh | Build the error when save is not allowed

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#92664]
## Background 
VA Profile will stop providing an override key in some cases, we ne the FE to prevent users from attempting to override an address if no key is received from VA Profile
### Design to use 
- #91168

## Acceptance criteria 
- [ ] The FE no longer allows a user to override an address if, 1 no override key is present or if the BE sends one of the 15 fatal error codes

**Comment by ACParker89** [comment]
@nickjg231 @asiisii do we need this ticket still?

**Comment by asiisii** [comment]
@ACParker89 we can close this ticket!
