### ISSUE TITLE
Remove incorrect language from main Yellow Ribbon page

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#9266]
User story:
As a Veteran I want to see the latest information about my Yellow Ribbon benefits from year to year. 

Background: Tammy Hurley requests 2 changes to this page:

https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/

Can you please update the incorrect information on the following page – https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/

1. Remove highlighted text.  We do not require a new agreement every year.

H3: How your benefits may change from year to year
Q: If I participate in the Yellow Ribbon Program this year, will I automatically be in the program next year?
A: Not always. **We require a new Yellow Ribbon Program agreement each year.**

If your school has an approved agreement with us and continues to participate in the program, they must continue to offer the Yellow Ribbon benefits to you the next year as long as you meet all of the requirements listed below.

2. 
Q: If I participate in the Yellow Ribbon Program this year, will I automatically receive the same amount of funding next year?
A: No. Even if you stay enrolled, keep progressing in your program, and have money left in your Post-9/11 GI Bill benefits, **your school can choose to offer a different amount each year.**

Highlighted text is incorrect.  Even if a school reduces the amount for the program, the student will continue to receive the same amount they initially received if they stay continuously enrolled. 

Tasks:
- [x] Get additional details from Tammy so we can make updates. Anne, requested 5/19
- [x] Make changes to the page and build in Drupal. Anne
- [x] Copy edit. Randi
- [x] Send preview link to approve to Tammy. Anne Approved 5/22
- [x] Push live. Randi

**Comment by AnneHurley** [comment]
@RLHecht  - This page with 2 updates is ready for you. I've sent the prod link to Tammy and Matt, because she wanted 2 lines removed, but in removing them, the answers changed from No to Yes, so I made those changes as well. Just want to double check that w/ her.
http://preview-prod.vfs.va.gov/preview?nodeId=936

Preview sent 5/21

**Comment by RLHecht** [comment]
@AnneHurley I copyedited those two questions and all looks good to me.

**Comment by AnneHurley** [comment]
@RLHecht  Tammy Hurley has approved these changes on prod; the page can be pushed live.

**Comment by RLHecht** [comment]
This page has been published. Moving to validate. FYSA @AnneHurley @stephorkandatx

**Comment by RLHecht** [comment]
These changes are validated on the live site. Closing ticket. FYSA @stephorkandatx
