### ISSUE TITLE
Create a Cypress Test Standard Definition

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#92669]
# Description
In order to execute Cypress integration tests for an individual product we will need to create a new standard for defining which Cypress test spec files should be executed for a given product. Given that we expect the new workflow to be able to execute only Cypress tests associated with a given product, we need to define a standard that allows our automation to determine which tests to run.

## Details
See features 3 and 4 under the [design document features section](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3402760193/Design+Document+Cypress+Integration+Test+Workflow#Feature(s)).

## Acceptance Criteria
- [x] Cypress integration test workflow standard has been defined
- [x] Instructions for how to contribute a definition are included in the repository

**Comment by pjhill** [comment]
Created a new repository here to contain the example -- https://github.com/department-of-veterans-affairs/vagov-cypress-integration-tests

**Comment by IGallupSoCo** [comment]
As this work has developed, Peter and I determined that the best means of defining tests is to configure GHA to run any and all cypress test specs in a given app's folder, as specified by the end user.

We wrote the specPattern logic to find any such tests included with a given app, even if the teams behind them chose not to adhere to the standard directory architecture.
