### ISSUE TITLE
[FE, BE] My VA Ben App Drafts: Improve isolated error monitoring/handling on draft forms & apps (pt 2)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#92696]
## Background
Following up from the incident on 8/8/24, we identified areas where we can improve our isolated error monitoring and handling on My VA for draft forms and applications. The root cause of the incident was that the name of a form was changed by another team but was not changed in all places where that form exists, specifically in the `platform/forms/constants` file. We will be working separately with Platform to figure out how to avoid situations like this in the future, but in the meantime we should also improve our error monitoring and handling so that if this happens again, our page fails gracefully instead of crashing.

Part 1 of this was completed in #90712. Now we need to connect this monitoring to DataDog to be alerted in our slack channel.

## Tasks
- [x] Meet with Tom and Daniel re: connecting to Datadog from FE
- ~[ ] Connect monitoring to Datadog and alerts slack channel so that we are alerted if there's error~
- [ ] If Datadog is not an option review tests created in #90712 to consider options for creating a proactive alert

## Acceptance Criteria
- ~[ ] We are alerted in the `#accountexp-authexp_alerts` slack channel when there's an error~
- Unit and/or e2e tests catch situations where runtime error can happen

## Validation
- _Who can validate this ticket?_: FE
- _How can this work be validated?_: Verify tests all pass and account for mismatched or missing form IDs

**Comment by ACParker89** [comment]
@DanielMiller-agile6 does this need to roll into 49?

**Comment by DanielMiller-agile6** [comment]
looks like allison's test changes should be sufficient to ensure we throw an error in our tests, which should prevent this issue from happening in prod.  i was unable to reproduce the issue without tests failing, which will be caught in CI.  if we see any other similar issues with form configurations, we can create a new ticket.
