### ISSUE TITLE
Update broken links and old URLs on priority group page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#927]
@RLHecht - Not sure if you still have access to Drupal. IF YES, could you please update the below bugs today? Including @peggygannon to do the final check prior to publishing. 

## What happened?
On this page: https://www.va.gov/health-care/eligibility/priority-groups/

1. 
The "Learn more about your health care costs" link is pointing to https://www.va.gov/va.gov/HEALTHBENEFITS/cost/copay_rates.asp and erroring. 

Action: Update the link to go to: https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/ 

2. 
The "View current copay rates" link is pointing to https://www.va.gov/health-care/eligibility/priority-groups/va.gov/HEALTHBENEFITS/cost/copay_rates.asp and erroring. 

Action: Update the link to go to the new copay rates page here:  https://www.va.gov/health-care/copay-rates/

Screenshot A:
![image](https://user-images.githubusercontent.com/43381063/62949851-f4c7ab80-bdb4-11e9-888f-8966c41397d0.png)

3. 
There are 2 other copay rates links on this page (see screenshot below) that are pointing to legacy copayment page in Community Care. These should be updated, per Jenny HL (VHA), to the new copay rates page on our benefit hub. 

Current url: https://www.va.gov/COMMUNITYCARE/revenue_ops/copays.asp

Update url to: https://www.va.gov/health-care/copay-rates/ 

Screenshot B: 
![image](https://user-images.githubusercontent.com/43381063/62951353-d616e400-bdb7-11e9-8e66-0aeb6e314541.png)

@Karak888 for awareness only

**Comment by RLHecht** [comment]
@jenniferlee-dsva I still don't have access to the CMS (as well as Drupal) with my PIV card. I asked about it at the end of last week but will check on it again today.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I see. Okay. Then I will make the updates today, and have @peggygannon review. Because this is one of our most important benefit hubs, I need this updated today to show our stakeholder.

**Comment by jenniferlee-dsva** [comment]
@peggygannon - this is ready for you to review in Drupal. Please push "publish" for today's deployment if updates work fine. Drupal: http://prod.cms.va.gov/health-care/eligibility/priority-groups

**Comment by peggygannon** [comment]
@Karak888 @jenniferlee-dsva Links have been checked and page has been "published."

**Comment by peggygannon** [comment]
This change is live. Closing
