### ISSUE TITLE
[Bug] Cancel screen shows up twice before canceling 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#92708]
## Summary
When the user clicks on `Cancel request` or `Cancel appointment` and when the call is made to the API and has a delay, the user will see duplicate screen to cancel an appointment (should only be one). 

## Specs
- Device: Mac
- Browser: Chrome

## Steps to Reproduce
**Test User:** judy.morrison@id.me

1. Go to: www.staging.va.gov 
2. Go to the Appointments tool 
3. Click on the Details page for a booked appointment or pending appointment request 
4. Click `Cancel`
5. User will see the review details to screen to Cancel 
6. Click on Yes cancel request/appointment 
7. User will see the review details to Cancel 

### Actual Result
User will see the review details to Cancel twice after clicking the confirm to cancel button. 

### Desired Result
Once the user cancels the appointment/request, there will be a spinning loading indicator to let the user know it is in process to cancel.  

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by vbahinwillit** [comment]
@ldelacosta - What text should the loading indicator display?

**Comment by ldelacosta** [comment]
@outerpress - could you please provide guidance here?

**Comment by outerpress** [comment]
Let's just do `Canceling your appointment...` @ldelacosta @vbahinwillit

**Comment by melissa-lefevre** [comment]
I validated in staging, works as expected. You can close @ldelacosta

**Comment by ldelacosta** [comment]
No additional details needed. Closing out the ticket.
