### ISSUE TITLE
[BE/DISCOVERY] 10-10EZR - See if there's a way to prevent users from uploading attachments with invalid extensions

### ISSUE THREAD

**Issue by JoshingYou1** [department-of-veterans-affairs/va.gov-team#92710]
- [x] Investigate the backend to see if we can return an error when the file extension in invalid

**Comment by JoshingYou1** [comment]
I think we will need to QA this on the frontend. There will be a specific error message to let users know that the file extension they tried to upload is not supported.

**Comment by allanto-ah** [comment]
Gotcha, I thought there was a QA ticket somewhere since I saw that this was a discovery ticket
