### ISSUE TITLE
[Design] Add content to confirmation page about how to cancel appt

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92733]
## Tasks

- [ ] Knowing that an automated feature has been removed from the MVP, we need to provide information to Veterans on how to cancel their scheduled cc appt. For example, **review other appt types to check existing cancelation content - [upcoming video appt example](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=2011-196120&t=UVbVcboJSxgjwcNJ-4)**. 
- [ ] Add new content to [confirmation details page in Figma](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2169-36415&t=mG39iXMviAfKFjm8-4).

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92733?planning-poker) with Zenhub @zach-park

**Comment by benbrasso-agile6** [comment]
@brianseek @lee-delarm6 ya'll have a ticket (or want to create one... can backlog it) for this small content update to the success page? https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2169-36415&t=Pn4SiwJ3qg7hQy1U-4

**Comment by lee-delarm6** [comment]
I think we created a ticket for this one, will check

**Comment by benbrasso-agile6** [comment]
Thanks. I was trying to find, but you know, sometimes it's hard to find things.
