### ISSUE TITLE
Track users on New (AL2) SOCKS to support the Q3 security access review

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#92737]
## Description
For security access reviews, security needs either the list of users who are losing access, or the list of users who are keeping their access. We believe it will be easier to focus on the list of people who will continue to have access for this pass.

Security Team has requested we output to Confluence pages in this format:

**Details we need:**
- username
- role - standard user
- change made - Updated/Validated Need
- date of change - either when the update was made, or when they accessed

---

## Acceptance Criteria
- [ ] Create functionality to collect a list of users who are setup on and/or have accessed new SOCKS
- [ ] Collect those in a list that can be published to [this page](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3214147585/ACCESS+REVIEW+-+SOCKS)

**Comment by ben-allen-oddball** [comment]
provide results to @kell-y

**Comment by ben-allen-oddball** [comment]
$ aws s3 ls prt-reports
2024-10-09 08:25:58      12215 1728476756.json
2024-10-09 08:26:09      11970 1728476766.yaml
