### ISSUE TITLE
Midpoint Review - Design Feedback - MHV Secure Messaging, Landing Page/Navigation Updates

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#92756]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: Review the [guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else) around too much content in the additional info components. Your content is probably a little too much so if you can trim it down.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by underpaid1ntern** [comment]
We reviewed the guidance and started a discussion about content length here:
https://dsva.slack.com/archives/C03ECSBGSKX/p1726603177712559

For now we will keep the content as is as an MVP and after talking a little bit more with Allison Christman and @laurwill .

The content will still fit within the smallest VP that VADS considers (Iphone SE: 320 x 568)
![image](https://github.com/user-attachments/assets/33c39454-1a95-4cd6-bfd1-cee5fd301547)

**Comment by underpaid1ntern** [comment]
CC: @emilytaylorux
