### ISSUE TITLE
Adding [Juan Castillo] to DSVA Slack

### ISSUE THREAD

**Issue by anita-halici** [department-of-veterans-affairs/va.gov-team#92757]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<Access to dsva slack>

Are you requesting to add an individual as a:

- [x ] - Full member

- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to? 

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
It is a mobile engineer that will be interacting with at least 5 other teams, so he needs access to multiple places.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_[juan.castillomoreno@va.gov](mailto:juan.castillomoreno@va.gov)_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by anita-halici** [comment]
@LEHigley @KevinMHoffmanUSDS @lkoenigsberg could you please let me know when Juan will receive the access to the va slack?

**Comment by KevinMHoffmanUSDS** [comment]
Invited.

**Comment by anita-halici** [comment]
thanks! worked
