### ISSUE TITLE
Coordinate with Mikki re:  URL formatting for dev application 

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#92759]
## Description
Our single-app approach to rendering arbitrary forms has pushed us towards a url structure that includes a `/digital-form` subpath for rendering these forms in the browser (see below for more on this). We need to coordinate with Mikki Northuis regarding this approach, and get guidance regarding our restrictions, guardrails, suggestions, etc.

## Background
Our current working model is to render forms at a url like this: `www.va.gov/digital-form/{form-id}`. 
- e.g. `www.va.gov/digital-form/21-4140`

This is to be contrasted with other forms that are rendered at something like this: `www.va.gov/{optional-subpath}/{form-id-or-title}`
- e.g. `www.va.gov/records/request-personal-records-form-20-10206`

## Questions
We might be constrained a little bit by our architectural approach that utilizes a single app to render multiple forms - we need a subpath (i.e. `/digital-form`) in order to route into that app - but we can perhaps use some redirects if needed.

So, we need to keep that in mind, but we should figure out what sort of approach is "ideal".

- Are there any problems with our current model?
- If problems:
   - Are they non-starters, or just not ideal?
   - What are preferred paths/urls/general approach?
- If no problems:
  - Do we need to do anything to "finalize" or codify this approach?

**Comment by Karak888** [comment]
Need to gather questions together and Kara will schedule meeting.
