### ISSUE TITLE
Perform Form21a JSON schema validation in vets-api

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#92770]
In [this GCLAWS POST Form21as JSON schema issue](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/87164), the ARF team [transformed the Form21as post request](https://github.com/department-of-veterans-affairs/vets-website/pull/31680/files#diff-b5ad49a6d5d3084f8db45c38d503d64ec3f3c86b855de55a7e7de5641be40629) on the frontend. However, to ensure data integrity and maintain security, we should also perform some level of JSON schema validation on the **vets-api** side. This could be done using either a simple **strong parameters** implementation or a more robust approach with **VetsJsonSchema**.

The [vets-api form21a_controller](https://github.com/department-of-veterans-affairs/vets-api/blob/740384ebec98322fb83a33b70ce42d0bc09bc34a/modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/form21a_controller.rb) currently does the below, though it is [arguably not enough (see thread)](https://dsva.slack.com/archives/C06ABHUNBRS/p1726166397049459):
```
      before_action :parse_request_body, only: [:post]

      attr_reader :parsed_request_body

      # Parses the raw request body as JSON and assigns it to an instance variable.
      # Renders a bad request response if the JSON is invalid.
      def parse_request_body
        @parsed_request_body = JSON.parse(request.raw_post)
      rescue JSON::ParserError
        Rails.logger.error('Form21aController: Invalid JSON in request body')
        render json: { errors: 'Invalid JSON' }, status: :bad_request
      end
```

### Possible Approaches for Validation:
The below list is not exhaustive, and it is up to the implementer to pick the appropriate approach! Please perform some searches in vets-api for examples.

1. **Strong Params (Simpler Approach)**
   A strong parameters implementation in **vets-api** would provide a lightweight solution for sanitizing the incoming request. This can be an appropriate choice during this non-production phase, offering a straightforward way to filter out unnecessary or harmful data before it is passed to downstream systems.

   Example:
   ```ruby
   def form21a_params
     params.require(:form21a).permit(:field1, :field2, :field3)
   end
   ```

   Strong parameters are easy to implement and offer a basic level of security by ensuring that only whitelisted fields are passed to the next layer.

   **Reference Examples**:
   - [ClaimsBaseController strong params example](https://github.com/department-of-veterans-affairs/vets-api/blob/ecaa4bfcbdb5bfb647c9009ea5ae6b9f6fd529be/app/controllers/claims_base_controller.rb#L22-L31)
   
2. **VetsJsonSchema (More Comprehensive Approach)**
   Using **VetsJsonSchema** aligns with [its purpose](https://github.com/department-of-veterans-affairs/vets-json-schema?tab=readme-ov-file#purpose)) to enforce a consistent contract for data validation throughout the request flow, from frontend to backend. This approach provides more granular and flexible validation rules, supporting nested attributes, complex data structures, and custom validation logic. It would be appropriate if we want to maintain consistency with other VA.gov form submissions and ensure stricter data validation.

   While strong parameters allow simple filtering, **VetsJsonSchema** can ensure that the data adheres to the expected structure and format.

   **Reference Examples**:
   - [ActiveRecord JSON schema validation](https://github.com/department-of-veterans-affairs/vets-api/blob/5a040d83ca512d5c9969e18e6d7f6a55011bac01/app/models/saved_claim/burial.rb#L38-L44)
   - [Redis form JSON schema validation](https://github.com/department-of-veterans-affairs/vets-api/blob/db3a9d09de18882c5512dad604fcd18942cb74f4/app/models/concerns/redis_form.rb#L51-L56)

### AC:
- [ ] **vets-api** validates incoming Form21as requests

Below are the relevant PRs, but they may need to be further integrated with ARP!

https://github.com/department-of-veterans-affairs/vets-json-schema/pull/936/files
https://github.com/department-of-veterans-affairs/vets-website/pull/32129/files
cc @nihil2501

**Comment by candilemoine** [comment]
Transform 21a form data client side (before submitting it to the server)
# [This transformation function](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/accredited-representative-portal/accreditation/21a/config/submit-transformer.js) is the one that needs to be implemented and tested
# For some inspiration, an incomplete attempt was recently reverted [here](https://github.com/department-of-veterans-affairs/vets-website/pull/32145)
# The "official" schema to convert into for the backend lives [here](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21A-schema.json) in the project vets-json-schema
