### ISSUE TITLE
Flaky Rspec Failure: uploads_request_spec

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#9279]
## The Problem
The [`uploads_request_spec`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/spec/request/v0/uploads_request_spec.rb) periodically fails, causing unexpected build failures in Jenkins.

## Extra Context
Here is an example of this spec randomly failing:
http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-api/detail/master/2668/pipeline/

## Work to be Done
- [ ] Discover why this test is flaky
- [ ] Fix / refactor / delete spec based on discovery

**Comment by johnpaulashenfelter** [comment]
Just in case ordering matters, fails with seed 37039 from http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-api/detail/master/2668/pipeline/

**Comment by omgitsbillryan** [comment]
Whoops - this ticket was already created on March 27

https://github.com/department-of-veterans-affairs/va.gov-team/issues/7305

**Comment by omgitsbillryan** [comment]
Closing as a duplicate ☝️
