### ISSUE TITLE
Broken link on How to apply (health care) page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#928]
@RLHecht - please update broken link today. @peggygannon to review before publishing. 

## What happened?
On this page: https://www.va.gov/health-care/how-to-apply/

The "Download VA Form 10-10EC (PDF)" link is  pointing to https://www.va.gov/vaforms/medical/pdf/vha-10-10EC-fill.pdf and erroring.

Action: Per Jenny HL (VHA stakeholder), update the URL to: https://www.va.gov/vaforms/medical/pdf/10-10EC%20Fill%202017.pdf 

Screenshot: 
![image](https://user-images.githubusercontent.com/43381063/62952320-6bff3e80-bdb9-11e9-8870-4102979669e3.png)

@Karak888 for awareness

**Comment by jenniferlee-dsva** [comment]
@peggygannon this one is ready for your review in Drupal: http://prod.cms.va.gov/health-care/how-to-apply 
Please push "publish" for today's deploy if all fine. 

(Randi doesn't have CMS access yet with her new PIV, so I'm making the updates as I need this to go live today for JHL.)

**Comment by peggygannon** [comment]
@jenniferlee-dsva @Karak888 Link update has been checked and page has been set to publish.

**Comment by peggygannon** [comment]
This is live. Closing.
