### ISSUE TITLE
[BE] [Tech Debt] remove BTSSS v1 configs from AWS param store

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#92804]
The older v1 configs for BTSSS have been removed from:
- vets-api code: https://github.com/department-of-veterans-affairs/vets-api/pull/18401
- vsp-infra-application-manifests:
  - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3098
  - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3099

This ticket is to remove those configs from AWS param store.

**Comment by loripusey** [comment]
@randomsync is this going to roll over?

**Comment by randomsync** [comment]
The older configs for staging were removed on 9/18. While testing, I noticed that we're seeing this error:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
 : {:uuid=>"71b9a678-05d9-4c1e-8d68-f6e859d8e81e"}
```
I don't think these are related to the config removal, but just to be double sure, we'll need to dig into this and confirm 100% that they are not related, before we remove the older configs for production. Currently, the production travel claims are working fine.

for reference, here are the older configs that need to be removed:
https://console.amazonaws-us-gov.com/systems-manager/parameters/?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:%2Fdsva-vagov%2Fvets-api%2Fprod%2Fcheck_in%2Fbtsss

https://console.amazonaws-us-gov.com/systems-manager/parameters/?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:%2Fdsva-vagov%2Fvets-api%2Fprod%2Fcheck_in%2Ftravel_reimbursement_api%2F

**Comment by randomsync** [comment]
just tried to make a request through fwd-proxy in staging through insomnia and got a connection refused. so this might be an issue with fwdproxy in staging
