### ISSUE TITLE
[CAIA A11y Research]: IIR, Welcome Pathway (November 2024 EOM)

### ISSUE THREAD

**Issue by raquelou** [department-of-veterans-affairs/va.gov-team#92823]
> [!NOTE]
> **High-Level Overview**: IIR, Welcome Pathway
> - **Research Timeframe**: sometime after November 22 `estimated`
> - **Pilot Session(s)**: Likely between November 18 and 22 `To be Scheduled`
> - **Assistive Tech Users**: `#` AT Users
> - **Artifacts Available**:  Research Plan & Convo Guide
> - **Testing Environment & Schedule:** `TBD` - _Coded Prototype in CodePen or Staging_
> - **Assistive Tech Being Used**: Screen Readers (Majority), Alternative Navigation (Voice Control) and Screen Magnification
> - **CAIA Internal Doc:** `Pending`
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

@coforma-jamie 
@EvanAtCoforma 
@sara-amanda 
@mutiaadhocteam 

</details>

## About the Team

- **Team name:** IIR (Iterate, Innovate, Run)
- **OCTO-DE product owner:** Jeff Barns
- **Product manager:** Pete Egan
- **Designer:** Liza McRuer/Raquel Eisele
- **FE engineer:** John Rodriguez/Nick Sayre
- **Product/team Slack channel:** #iir-product-teams-public

<details><summary>Toggle to view more intake research ticket information</summary>

> ### Do you have an accessibility champion?
> 
> No, we don't have a champion (yet)
> 
> ### If you have an accessibility champion, what's their name?
> 
> _No response_
> 
> ### Is anyone on your team interested in becoming an accessibility champion?
> 
> Raquel Eisele
> 
> ### Calendar checking
> 
> - [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
> - [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support
> 
> ### Have you reviewed the CAIA capacity calendar?
> 
> - [X] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe
> 

</details>

### Initial Request

> ... help review the AT research plan and conversation guide I am putting together. I created a ticket thinking this would help me get paired with a specialist ...

<details><summary>Toggle to view the problem statement, desired outcomes and solution approach as of Sept. 17, 2024.</summary>

### Problem Statement
[c/o Product Outline / Problem Statement Section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/product-outline.md#problem-statement)

> _VA.gov needs to have a defined onboarding experience on VA.gov. We hypothesize that a lack of digital onboarding guidance for newly transitioning Veterans presents challenges in efficiently and effectively getting Veterans the relevant services and resources they need, leading to potential frustrations, delays, and missed opportunities for support and access to eligible benefits._

### Desired Outcomes
[c/o Product Outline / Desired Outcomes Section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/product-outline.md#desired-user-outcomes)

> - _Basic understanding of challenges associated with the transition process, specifically with regard to how VA.gov could remedy those pain points_
> - _A simplified Onboarding experience that walks a new Veteran user through key activities and benefits they should do to get started._

### Solution Approach
[c/o Product Outline / Solution Approach Section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/product-outline.md#solution-approach)

> **After digesting the research and looking at the comparative analysis, we are tasked with finding ways to**
> 
> 1. incorporate an onboarding experience within an existing product and
> 2. overlaying the experience in a temporary manner so that users who do not need the onboarding experience can dismiss it.
> 
> _The initial phase will be rolled out to welcome Veterans who have not created a VA.gov account and prompt them to front-load data that VA.gov can then utilize when the Veteran is going through the existing benefit application experience. This provides a complementary support structure to the existing VA experience.gov while also utilizing a step-by-step type approach for those who might feel overwhelmed or as though they are not entitled to all the benefits offered on VA.gov._

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

### Timeframe

<details><summary>Toggle to view research timing information.</summary>

1. **Pilot Session Mobile**: `TBD` 
2. **Pilot Session Desktop**:`TBD` 

> We are estimating around October 28, 2024

### Length of sessions

- **Session length:**
    - `TBD` 
    - **AT Session Timing Examples**: 
        - `90` minutes (screen reader or alternative navigation tool)
        - `60` minutes (screen magnification tool)
        - **Buffer time between sessions:** `30` minutes
        - **Maximum sessions per day:** `2`

</details>

###  Testing Schedule

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

<details><summary>Toggle to view time-related items</summary>

#### Enter Testing Information
- **Dates**: `[Start Date Est.]` Oct. 28, 2024 to `11/8/2024`
- **Times**:  `TBD`
- **Planning to Recruit `#` Veterans for**:
     - minimum of `#` sessions with screen reader users
     - minimum of `#` sessions with alternative navigation users
     - minimum of `#` session with a screen magnification user

#### Examples
- **Date Range Example**: _Typically around `2` Weeks_
- **Timing Example**: _`9-10:30am`, `11-12:30pm`, `1-2:30pm`, `3-4:30pm` EST_
- **Recruitment Example**: _Planning to Recruit `12` Veterans for: a minimum of `3` sessions with screen reader users; minimum of `2` sessions with alternative navigation users; and a minimum of `1` session with a screen magnification user._

#### Source of Truth
Testing Schedule (🔗 `To be Provided` as source of truth;  **_also see table in this ticket_**

Please use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available
------------------|------------------|--------------|--------------|--------------|--------------|--------------
Pilot | 10/23/24, #:##-#:## #m | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | `TBD- Based on a11y availability`
P# | #/#/24, #:##-#:## #m | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | `TBD- Based on a11y availability`
P# | #/#/24, #:##-#:## #m | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | `TBD- Based on a11y availability`

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/product-outline.md)
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715019181472/206d1983971576ee7696c1984666185a2fbff545?fromVisitorModal=true&sender=u4356f0478274fc3cca5b5144)
- [Prototype or mockups](https://www.figma.com/design/CertVj7cu66kFv9TnseR30/Welcome-to-My-VA?node-id=1429-7381&t=AHKQsioSyMM2FOMT-1)
- `DRAFT` [AT Convo Guide (GH)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/assistive-tech%20research/AT%20conversation%20guide.md)
- `DRAFT` [AT Research Plan (GH)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/assistive-tech%20research/AT%20research%20plan.md)
- [Epics/issue that may be helpful](Insert URL here between the parenthesis)

</details>

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket post OCTO/a11y refinement meeting 9/17/2024
- [x] **OUTREACH**: [Initial outreach](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92823#issuecomment-2359004103) to team post-refinement with next steps
- [x] **Links Requested**: Research Guide and Convo Guide Support Requested via Slack (added to ticket from GitHub folder) - `DRAFT` flag added in supporting artifacts
- [x] **INITIAL MEETING:** Schedule an initial meeting with team to discuss the research process and support. `Scheduled`
- [x] **REVIEW REQUESTED:** `DRAFT` [Convo Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/assistive-tech%20research/AT%20conversation%20guide.md)
- [x] **REVIEW REQUESTED**: Research Plan `DRAFT` [AT Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/assistive-tech%20research/AT%20research%20plan.md)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/93662
- [ ] Receive prototype from Team the week of 9/30/2024 via Figma c/o @raquelou
- [ ] #93664
- [x] **PILOT CALENDAR HOLDS** - Set **pilot** holds on the A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago)
- [ ] **PILOT SESSION MOBILE: SCHEDULE** Pilot session with team. `Conduct around 11/22/2024` `a11y TBD`
- [ ] **PILOT SESSION DESKTOP: SCHEDULE** Pilot session with team. `Conduct around 11/22/2024` `a11y TBD`
- [ ] **PILOT SESSION MOBILE: CREATE TICKET** See `related tickets task list` in this ticket.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/95524
- [ ] **PILOT SESSION DESKTOP: CREATE TICKET** See `related tickets task list` in this ticket.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/95525
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available. `Note on 9/25/2024` **Research EOM October** Prototype won't be ready until EOM.
- [ ] Receive Source of Truth for Scheduling 🔗 (Examples: Google Sheet, Slack Canvas, etc.)
- [ ] **Requested device breakdown:** Desktop, Mobile and Tablet
- [ ] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support.
- [ ] **Updated Holds:** waiting on official invites (table to be updated in this ticket)
- [ ] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean) Updated holds x/xx/2024
- [x] **Review research folder and assets**
- [ ] **OFFICIAL RAW RESEARCH NOTES** Create [CAIA notes document](🔗)
- [ ] **Participate in research** **Date Span:**`Estimated Start` 10/28/2024 and `x/xx/2024`
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
- [ ] **TEMPLATE SESSION NOTES**: Create [CAIA notes document] for a11ys to use during the sessions
```

```[tasklist]
### VFS TEAM Tasks
- [x] Tag @Naomi Eke in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH) Link to VA [OCTO Slack Thread 9/18/2024](https://dsva.slack.com/archives/C01K37HRUAH/p1726675576803719)
- [x] Your team's researchers and observers read through platform guidance on [research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users) and have also read and learned [how to be respectful of participants with disabilities](https://depo-platform-documentation.scrollhelp.site/research-design/disability-etiquette)
- [ ] Your team's researchers have read through the resources for researchers on the VA Platform's [Accessibility on Va.gov page.](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-on-va-gov#AccessibilityonVA.gov-ResourcesforResearchers)
- [ ] [Inclusive Recruitment Strategies](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md)
- [ ] Consider [creating your prototype in CodePen](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen) for the most accurate results
- [ ] `Recommending Pilot` Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired
- [x] Initial meeting with CAIA a11ys `Scheduled`
- [x] Request pilot sessions with CAIA a11ys - EOM October (earliest)
- [ ] Schedule pilot session with CAIA a11ys (Mobile)
- [ ] Schedule pilot session with CAIA a11ys (Desktop)
- [x] Requested Design Review prior to Pilot
- [ ] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section. `Note on 9/25/2025` **@raquelou to send CAIA the final Figma prototype early next week (week of 9/30/2024)**
- [ ] **DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. `Estimated Start: 10/28/2024`
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in `Table` in the ticket above.
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (@sara-amanda)
- [ ] **Device Detail:** Desktop, Mobile and Tablet - Device breakdown needed for session prep
```
```[tasklist]
### Related Tickets
- [ ] #93662
- [ ] #93664
```

**Comment by sara-amanda** [comment]
# CAIA a11y Research Support

@raquelou _Thank you for submitting a research ticket with CAIA! Our a11ys are looking forward to working with you on your latest research project._ 

## Next Steps
**The following are the initial, next steps in our process:** 

- [ ] Review the refined ticket above. 
- [ ] Review the VFS Team Task list items, that will assist us in supporting you.
- [ ] Let's go ahead and schedule your initial meeting with a CAIA a11y(s) - just send us your availability [in the Slack thread ](https://dsva.slack.com/archives/C01K37HRUAH/p1726675576803719) with a tag `@sitewide-caia-accessibility`. 
    - [ ] _You can additionally choose to post your availability in this ticket's comments and tag me @sara-amanda._ 
- [ ] If possible, provide your official research dates (start and end) so we can set holds on our calendar. 
- [ ] If available, let us know where you plan to conduct your research: CodePen or Staging?
- [ ] If available, let us know what assistive technology you are looking to test users with. 
- [ ] If possible, let's go ahead and schedule your [pilot session](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) with a CAIA a11y, so that we can test your prototype with the AT you will be testing real users with. 

_**We are happy to answer any questions you may have, along the way. Thank you for reaching out to us and we are happy to help!**_ 

cc: @NaomiPMC @artsymartha68

**Comment by raquelou** [comment]
Hello @sara-amanda, here is my availability this upcoming week. Please let me know a time that will work for you!

Set 23, 10-11, 2-3 EST;
Sept 24, 1-5 EST;
Sept 25 12:30-3 EST

**Comment by sara-amanda** [comment]
> Hello [@sara-amanda](https://github.com/sara-amanda), here is my availability this upcoming week. Please let me know a time that will work for you!
> 
> Set 23, 10-11, 2-3 EST; Sept 24, 1-5 EST; Sept 25 12:30-3 EST

## Invite Sent 
@raquelou , thank you for your availability! An invite has been sent for our initial meeting. 
- **When**: Wednesday, September 25
- **Duration**: (30 min.)
- **Time**: 1:00 to 1:30 p.m. EST

**Comment by coforma-jamie** [comment]
Thanks for meeting with us @raquelou! Here are our action items so far:

You will:
- send us a link to the Figma mockups, since you'd like us to do a design review first.

We will:
- update our calendar - the earliest you can do a pilot + research is the end of October
- review you research plan and conversation guide, and give you feedback as a comment in this ticket

**Comment by EvanAtCoforma** [comment]
Yes, glad we could all connect on this early @raquelou !

Here's some notes I have regarding the research plan:
- The research dates aren’t reflective of the projected time to conduct sessions. Sounds like the prototype wont be developed until end of October at the earliest, so it would be great if the dates can be updated or TBD for the time being.
- Looks like 8 total participants are being requested, but only 7 have designated AT (2 desktop SR, 2 mobile SR, 2 screen mag, 1 speech recog). Not sure we are doing 2 speech recognition participants, but please update when you have a chance.

Appreciate it!

cc: @sara-amanda

**Comment by coforma-jamie** [comment]
Suggestions for the convo guide @raquelou:

- **Ask whether, and what, assistive tech they're using during the Intro.** Recommend not waiting until the setup portion because it's fairly common to get either "false positive" signups - folks who don't actually use AT - or participants that signed up with one AT, but prefer to use another (ex., signed up with JAWS, but using an iPad). Make sure they're using AT first, and disqualify them if not - that way, you aren't wasting anyone's time.
- **Give options for how to receive the link to the prototype.** Zoom chat can be cumbersome to access, so some folks prefer email or dictation.
- **Create a shortlink.** And use a "human" slug - bit.ly/TheTest, for example. This'll make it easier to dictate if needed.
- **Emphasize that they don't have to log in.** Logging in is a huge blocker for people. Make sure it's clear that you're emulating it, and that they aren't actually logging in to anything. It'll be a relief. 😄 
- **Tell folks not to click ahead.** If you want them to talk through a screen before clicking on things, say that up front. This is especially important with screen reader users, because screen readers are _noisy_ - if they move ahead and you tell them to stop, they might not hear you over the screen reader.

**Comment by coforma-jamie** [comment]
This team decided that they aren't going to move forward with user research right now, they'll do internal testing instead. They'll test with users during their next phase (next year).

Closing this ticket.
