### ISSUE TITLE
CT-103: Update 103 Content based on staging review.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9283]
As a user of the Comparison Tool, I need the information regarding Section 103 communicated in a clear meaningful way so that I understand the impact to my education and benefits.

## Assumptions:
1. This work is completed behind feature flag created in #7773 so that it is only available in the staging environments and below.

## Acceptance Criteria:
1.  The following content is displayed when the user clicks "Protection against late VA payments":

> **Protection against late VA payments**
> If VA is late making a tuition payment to a GI Bill school, the school can’t prevent a GI Bill student from attending classes or accessing school facilities. 
> 
> Schools may require students to provide proof of their GI Bill eligibility in the form of:
> - Certificate of Eligibility (COE) **or**
> - Certificate of Eligibility (COE) and additional criteria like an award letter or other documents the school specifies
> 
> **In addition, schools can't charge late fees or otherwise penalize GI Bill students if VA is late making a tuition and/or fees payment.** This restriction on penalties doesn't apply if the student owes additional fees to the school beyond the tuition and fees that VA pays. Students are protected from these penalties for up to 90 days from the beginning of the term.
> 
> Contact the School Certifying Official (SCO) to learn more about the school’s policy. [Read our policy on protecting students from late VA payments](https://benefits.va.gov/gibill/fgib/transition_act.asp).

## Supporting Artifacts:
1. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/9fe97d6a580faf5189600d84892ef52dee757a54/products/education-careers/school-comparison-tool/Sec103/design/content/103-content-doc.md)
2. [UI Document - PL 115-407 Section 103](https://github.com/department-of-veterans-affairs/va.gov-team/files/4583006/gibct-pl-115-407-sec-103-v0.3-14221973.pdf)
3. [Sketch Layout](https://www.sketch.com/s/3c354981-2708-4222-898d-dda9ff130dc4)

**Comment by amyknox** [comment]
GH content doc has been updated.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-21 at 10.47.49 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ce79b9f7-9fbc-4e07-b8dc-5a784190a962)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-21 at 10.50.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/54979c8e-5be1-4f70-a821-0a7155e7e6fa)

**Comment by sonntag-adam** [comment]
The work is behind feature flag created in #7773

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/413&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam This checks our for UX.

**Comment by sonntag-adam** [comment]
Closing story.
