### ISSUE TITLE
Midpoint Review - Content Feedback - Modernized Check-in, Appointments, Travel Claims for Past Appointments

### ISSUE THREAD

**Issue by KKitagawa-Bosch** [department-of-veterans-affairs/va.gov-team#92865]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must:** in the past appointments section, one bulleted list has bold tags while another does not. I think you can make an argument for either option, but they should be consistent 
- [x] **Must:** in the penalty statement, the text currently reads "a fine, or imprisonment, or both." The middle item in the list does not need the "or". 
- [x] **Should:** "are you claiming only mileage" is a bit formal; "claiming only mileage" would align better with plain language standards
- [x] **Consider:** there are a few places in the copy where extremely short sentences are used that, while not technically out of guidance, could be perceived as terse or choppy to a reader. Consider combining sentences when the two sentences share a subject, object, or verb. 

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by benbrasso-agile6** [comment]
> Must: in the past appointments section, one bulleted list has bold tags while another does not. I think you can make an argument for either option, but they should be consistent

Peter

>  Must: in the penalty statement, the text currently reads "a fine, or imprisonment, or both." The middle item in the list does not need the "or".

Micah

> "are you claiming only mileage" is a bit formal; "claiming only mileage" would align better with plain language standards

Micah

**Comment by micahtaylor** [comment]
I've addressed the `Consider` and am reaching out to CAIA about the `Should` as I have some reservations about changing it but am validating that reservation.

**Comment by benbrasso-agile6** [comment]
We'll talk to Peter and Appts FE UX Team this week about the `Must`

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92865?planning-poker) with Zenhub @benbrasso-agile6 @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
FYI, this would be for pointing the `Must` feedback that we'll pair with Appts Team on

**Comment by benbrasso-agile6** [comment]
Changed the must for headings - https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2160-2072&t=eMbpPmJ6uz8UYmQP-4

**Comment by micahtaylor** [comment]
>Should: "are you claiming only mileage" is a bit formal; "claiming only mileage" would align better with plain language standards

After talking it through with CAIA I am opting to keep this content as is.

My two items are addressed.

**Comment by benbrasso-agile6** [comment]
@micahtaylor how are we handling the penalty statement `must` feedback?

**Comment by micahtaylor** [comment]
I saw Peter's name over that item and skipped right over it. Realizing now that his name is under the first item. My mistake. I'll pick it up.

**Comment by micahtaylor** [comment]
Already done. Closing!
