### ISSUE TITLE
Toxic Exposure 1.1 Moderated Production Testing

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#92887]
This ticket is a placeholder for the effort required by the team to perform the TE 1.0 release. We'll update it with the decided upon traffic thresholds as determined by the team and documented in the release plan.

### Dependencies
- #90990 
- #94191 

### Tasks

- Identify users who will perform moderated production testing
- Communicate the test cases they will use
- Toggle the flag
- Participants perform the testing
- DBEX teams analyze results against established metrics in the Release Plan
- Use DD to monitor for anomalies
- If any issues, disable feature flag and create ticket(s) to address
- Create tickets for remediation as needed

### Addition Information
- David Reis and Emily Theis can help identify users who will perform moderated production testing
- We need to determine the tactics on how we'll compare the pdf against the VBMS claim to ensure completeness and accuracy of the pdf
- We need a decision on which test cases to use (and if our testers will use Test Rail as a guide)
- We will definitely want to test the Standard Claim + TE test case, other ones we're not sure about
- We need to coordinate if this will be synchronous (video call) or async

### Acceptance Criteria
 - If any issues, disable feature flag(roll back) and create ticket to address

### Notes and Considerations 9/6 after VBA Sync meeting
1 Emily - Is there a way to block the production "moderated testing" cases from being sent to Mail Automation?

* When performing Moderated Production Testing (MPT), we don’t want the submission to ping the service that triggers Mail Automation. This is part of Rapid Ready for Decision (RRD). T-REX can create a toggle to prevent this from happening.
* We also want to prevent an ITF from being created
* We don’t want testers to fill out a 4142, so exclude this from the test cases
* We should have a test case that includes uploading fake evidence documents. We’ll provide an image file for testers to use
* We want to prevent the backup path being triggered, as this would trigger a human creating a claim and we won’t have the ability to delete it as soon as it comes through. Ideally we should block this from happening.

3 Jared - How might we delete the submitted claims in VBMS? Who can do this? Similar to Emily's question. How will we communicate with potential testers?
* Kevin, VBA will help with deleting a claim. He’ll cancel the EP and delete documents. Matt can help as needed.
* To help Kevin, provide him a screenshot of the Review & Submit screen form data, or if needed provide him with the raw formData JSON
* Emily will create a spreadsheet to track test cases - this will help us understand if the submitted data is the same as the claim in VBMS & the PDF
* T-REX to edit the MPT email/Slack script to include that we’ll need volunteers to send their file number and email address to Kevin over a Teams chat or an encrypted email. To be done when requesting our 6-8 testers, whichever 3-4 respond or can do it.
* Schedule 30 minute sessions to perform MPT synchronously

**Comment by pammicmac** [comment]
Conversation from sprint planning, 1-3 users

**Comment by pammicmac** [comment]
dependent on 90990, 94191

**Comment by mchae-nava** [comment]
1.1 Results
- No issues encountered during either run
- Form 526 flow verified to be working to submission, both with an IPF created before and after the Toxic Exposure 1.0 rollout
- Confirmed notification appeared on summary page when submitting a form started pre-TE
- Tested evidence upload with a test png file

**Comment by mchae-nava** [comment]
Updates made in team ModProd doc: https://docs.google.com/document/d/1p09g0NSFT3fC35eO5RIdVBMYxuo_rHnTS6ECPJtVyPQ/edit?tab=t.0
