### ISSUE TITLE
Use the New DS Action Link Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#92883]
## Description
We are unable to get click event metrics for all of our action links because we are not using the DS Action LInk component. As a team, we need to have access to these click events so that we can properly evaluate the use of our applications.

## Recourses
- [Slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1724846287697959)

## Tasks
- Find out if the new DS Action Link component is available in the DS
    - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3136
 - Use the New DS Action Link Component

**Comment by brianseek** [comment]
@cgednalske / @zach-park / @benbrasso-agile6 This is merged and can be validated locally or on stage. See screenshots in PR: https://github.com/department-of-veterans-affairs/vets-website/pull/32301

**Comment by benbrasso-agile6** [comment]
GTG

**Comment by brianseek** [comment]
Thanks @benbrasso-agile6, closing
