### ISSUE TITLE
Address Issues Resulting From E2E Review

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9289]
## Goal
Upon closer examination there may be a few issues that need to be resolved ahead of launch.

## Considerations
- Staging was having an issue May 19, 2020 from about noon to 3:30 ET

## Description: Checkbox bypass issue
Steps to reproduce:
1. Login as User 1 (Greg Anderson) or Users 76, 99, 123
2. Go to 686 intro screen, enter form using green button
3. Note Veteran info screen with static biographical data
4. Click continue, complete address
5. Click continue
6. Note Review screen
7. Click "back" from the bio info and get to the checkbox screen, you have to select one
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] The issue described above has been addressed

**Comment by micahchiang** [comment]
I _think_ this issue will be resolved once [this pr](https://github.com/department-of-veterans-affairs/vets-website/pull/13543) gets merged in.
