### ISSUE TITLE
[Design] Update eCheck-in BT pages with community care content change

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#92895]
## Description 

Kristen via IVC asked the BT web app for OH to mention that there's no support for community care appts. For continuity, we should make a similar change in eCheck-in. 

[Finalized content in BT web app for OH](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=642-3804&t=hwkB5lBpPoSQyXNY-4)

## Tasks

- [ ] Update eCheck-in BT pages to mention no support for cc appts
- [ ] Ping FE for them to create ticket when complete

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/92895?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by zach-park** [comment]
@cgednalske (cc: @benbrasso-agile6 ), this ticket is ready for validation:
https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4550-7029&t=iM1Kbtmf5pUxF40z-1

**Comment by cgednalske** [comment]
This content all looks good to me, but aren't we supposed to avoid stacked additional info components? Any way to separate them - like move the eligibility additional info component above the body text?

**Comment by benbrasso-agile6** [comment]
This exists on this page in prod today. Might recommend keeping this for now, and finding another solution in a different ticket later. 

Or, Zach, feel free to iterate based on Christina's feedback. I think, for eCheck-in, we def want to try and keep the content on the page to a minimum, knowing that checking in is most important (vs. the standalone OH app, which there's no time constraints).

**Comment by zach-park** [comment]
@benbrasso-agile6 , @cgednalske , I've added [alternate option](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4558-284&t=jXveHj2N72qcE3uX-1) based on Christina's feedback. So please take a look. Thank you!

**Comment by zach-park** [comment]
@benbrasso-agile6  @cgednalske   Validated as team review. Closed
