### ISSUE TITLE
Add Feature to Limit Access to One or More Facilities

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#92905]
## Description
We will be doing UAT at at least one facility for the OH Travel application. We have been asked to limit access to the application to only certain facility(ies).

## Questions
if multiple appointments, should we filter out all appointments that are outside of the pilot and let them file for any that are within? Or should we send back the error if any are outside of the pilot?

## Tasks
- Add Feature to OH Travel to Limit Access to One or More Facilities
   - [UX ticket for content to return for SMS ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93050#issuecomment-2359334533)
- create an error response for vetext to use to display [this text](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=715-6651&t=xYhEZCxvq3ZWZprj-4) back
- coordinate with vetext on how to handle the error response

**Comment by benbrasso-agile6** [comment]
I don't see a scenario where station 2222 wouldn't be part of the 3-digit station. (That doesn't answer your question.) 

But, because this scenario is highly unlikely, it seems that option B would be preferred. That is, let the Veteran file a claim and it will go in to manual review for travel clerks to do their downstream work.

**Comment by brianseek** [comment]
Thanks @benbrasso-agile6! Thats what I was thinking too. I agree that this would be a pretty rare thing for a patient to visit two different parent stations in one day. I guess that brings up another question, are we running the pilot at a 3 digit facility level or 5 digit?

**Comment by benbrasso-agile6** [comment]
If you're doing the work now, lol, I mean, I would just build in support for 5-digit stations too. E.g., there's always a random station or two that isn't an actual facility to see a provider.

**Comment by brianseek** [comment]
This work is deployed on stage, leaving here until we can e2e test it with vetext's work.
