### ISSUE TITLE
[BE] 10-10EZR: Create automated email notification to Veteran on Exhaustive Failure 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#92911]
As a Veteran, I would like to know of any failure that occurs with my EZR application so that I can follow up with the VA and/or try again.

- [x] Talk to Brandon about how he did this for EZ
- [x] Put in VA Notify ticket
- [x] Create an email on exhausted failure
- [x] Work with team on email [content](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=5276-65200&t=18klZPO4M7Bzvjd5-1)
- [x] Research an application ID
- [ ] Update submission page
- [x] Setup email template for Staging
- [ ] Setup email template for Production
- [x] Determine how to handle this if they don't have an email
- [x] Test to make sure user gets failure email
- [ ] **Success: Veterans get an email when their application fails exhaustively. **

**Comment by alexseelig** [comment]
@dellerbie here is a note I just got from Heather: 
implement the Delivery Status Call backs as well, to ensure we are notified of any emails that fail to send to the Veteran.  We should already capture the Veteran data with the submission failure, so if the email fails too, we can send it to VHA like usual.  [Here is our ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93247) for reference.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified the content update for the email. 

### If first name is missing in form data, the salutations will be removed
![Image](https://github.com/user-attachments/assets/dbbc2700-f021-410c-90a7-519afe8cca30)

### With first name
![Image](https://github.com/user-attachments/assets/99ff4f61-e148-432b-85fb-8b7858e1b999)

**Comment by allanto-ah** [comment]
Still a couple tasks need to be done before closing this task. See description
