### ISSUE TITLE
PW intake:  Fix broken link in medical records widget from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#92920]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else

### Describe your request

We got a SiteImprove report showing a broken link on our [Get your VA medical records oneline](https://www.va.gov/health-care/get-medical-records/) page. However, the majority of that page is within a react widget that CAIA can't access so we can't fix in Drupal. 

The broken link is in the accordion "What if I can’t access all of my medical records through VA Blue Button?" The text link for "Learn how to get DoD Health Records on the TRICARE website" should now go here: https://tricare.mil/PatientResources/MedicalRecords

### Time constraints / launch deadlines

No hard timing but we'd like to avoid having a broken link on the site for too long.

### Your product/team Slack channel

sitewide-content-accessibility-ia

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [X] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by randimays** [comment]
Validated successfully in production; closing as complete.
