### ISSUE TITLE
Qualitative Data Request - VA.gov

### ISSUE THREAD

**Issue by AnastasiaHananVA** [department-of-veterans-affairs/va.gov-team#92922]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

08-01-2024

### Date Range End

08-31-2024

### Product Name(s)

VA.gov

### Product Description

Hi, We're trying to get intercept open end data across all of VA.gov for one month. 

### Survey URL(s), key term(s), case category or type

All of VA.gov URLS (Or top 50 most traffic)

### Sub URLs

Yes

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

No

### VA Email Address(es)

anastasia.hanan@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.
I am not able to add assignees.

**Comment by newworld2616** [comment]
Hello, i Have shared the requested data. Let me know if you have any questions. Thank you.

**Comment by AnastasiaHananVA** [comment]
Thank you so much!

From: Sarifa Khalilulah ***@***.***>
Sent: Monday, September 16, 2024 1:32 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Hanan, Anastasia ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request - VA.gov (Issue #92922)


Hello, i Have shared the requested data. Let me know if you have any questions. Thank you.

-

**Comment by newworld2616** [comment]
Anytime!
