### ISSUE TITLE
EYB: Add conditional indicator to Estimate Your Benefits Section questions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9296]
As a comparison tool user, I need to be made aware of questions that are conditionally displayed and related to each other so that I can provide the most accurate information in order to receive the most accurate estimate benefits.

## Assumptions:
1. This work is completed behind a feature flag #7780.
2. Update e2e to test new functionality of calculator on non-vettec profile pages.
3. If a question is not listed in supporting artifact # 1 or AC, raise it so that it can be addressed as part of this story.

## Acceptance Criteria
1. All questions that are conditionally displayed on the following pages in the Comparison Tool are visually distinguished using the DEPO blue bar conditional pattern to left of the conditionally displayed question and the parent question.
  a. Landing Page
  b. Search Page
  c. Profile Page
2. On the Profile Page:
  a. When a conditionally displayed question has a parent question inside a different Estimate Your Benefits form accordion then the conditionally displayed question is not visually distinguished using the DEPO blue bar conditional pattern to the left of the conditionally displayed question.

## Supporting Artifacts:
1. [EYB_Section_Conditionality_Breakdown.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4652861/EYB_Section_Conditionality_Breakdown.xlsx)
2. Examples of Blue Bar Pattern:
Sample parent question before selecting option that causes a conditionally displayed question to display
![image (6)](https://user-images.githubusercontent.com/1094999/83062276-62835200-a02c-11ea-837a-9046d4a39dcc.png)

Sample parent question and conditionally displayed question after selecting option that causes a conditionally displayed question to display 
![image (7)](https://user-images.githubusercontent.com/1094999/83062284-64e5ac00-a02c-11ea-9368-094ae94c5b97.png)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12822

**Comment by zurbergram** [comment]
The conditionally displayed elements that follow “Which GI Bill benefit do you want to use?” in render order are:

- “Post 9/11 GI Bill” warning: select Active Duty and Ch33
- “To apply for VR&E benefits…” info box: select VR&E (ch 31)
- Cumulative Post-9/11 active-duty service: select ch33
- Completed an enlistment of: select ch30
- Are you eligible for the Post-9/11 GI Bill?: select VR&E (ch 31)
- How many dependents do you have?: select VR&E (ch 31) and select “no” to “Are you eligible for the Post-9/11 GI Bill?”

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael, @JenLJ and I think this checks out.

**Comment by delli-gatti-michael** [comment]
Tested by the following test cases:
- https://dsvavsp.testrail.io/index.php?/cases/view/634
- https://dsvavsp.testrail.io/index.php?/cases/view/635
- https://dsvavsp.testrail.io/index.php?/cases/view/636

All three test cases run under the following test run:
https://dsvavsp.testrail.io/index.php?/runs/view/432&group_by=cases:section_id&group_order=asc
