### ISSUE TITLE
Audit content components in online forms and tools

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#9298]
## User story

Do an  "audit" of current content  in VA.gov online  tools and forms to ensure they are consistent and adhere to Va.gov content guidance for forms.  Sometimes updates are made to the tool and form content without having a content review beforehand.. This is a task to do a sweep of tools to ensure we fix/catch instances of this. 

Some examples to look for: 
- Are they any new labels that we need to add to our form labels masterlist? 

- Are all headers, subheaders, labels and CTA buttons rendered sentence-cased? 

- For boilerplate content, are we using same language for standardized messaging? Are we giving users the same and consistent guidance/direction such as how to go about a task? (Some examples: 
 -- *If you need to update your personal information, please call Veterans Benefits Assistance at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.*
-- *How we ask for addresses*
-- *Need help? footer*

- Is there any other content that is clunky or doesn't adhere to VA.gov style or tone?  

### List of VA.gov tools/forms to review
- [x]   Health care form  10-10EZ
- [x]  Disability compensation form 526-EZ
- [x]  Education forms (1990, 1990N, 1990E, 5490, 5495, 10203) @amygoldman 
- [x]  Pension form
- [x]  Burial allowance form
- [x]  Pre-need Burial form
- [x] Benefit Letters 
- [x]  VA online scheduling
- [x] View disability rating

## Acceptance criteria
- [x] Audit complete for content components in above tools/applications 
- [x] Review audit and determine content recommendations
- [ ] Content recommendation are shared with appropriate product team

**Comment by peggygannon** [comment]
**11/13/2020 update**

Audit has been reviewed. Am now compiling recommendations for updating some content elements throughout forms.

**Comment by peggygannon** [comment]
Content takeaways from audit: 

GLOBAL fixes for all forms: 

1. Sentence case all H1s, chapter heads, subheads, labels, and buttons. 
I thought this fix got applied to all forms when we made this style update, but it looks like the updates never happened or somehow got reverted

Next step: will reach out to Design system team to get this update in the queue

2. Respondent Burden language
I recommend we make this plain language. This information is pulled directly from the VA paper forms, so we need to investigate with form stakeholders: 
- if we can update this language to be more plain language
- if this language can't be updated,  then can we add information to form introduction pages (e.g, This form will take you about [x] minutes to complete) letting users know in more plain language way time to complete form. 

Next step: am working @DanielleThierryUSDSVA on this 

3. Need help? Footer contact info.
What phone number should we put here? Most forms list the VA Benefits and Services number, but should the update general VA number (800) 698-2411 go here? 

Next step: will reach out to Chante and contact center team to find out best number. 

------

Form specific updates
Peggy to work with product form teams to get these minor content updates in their backlog.

**Comment by DanielleThierryUSDSVA** [comment]
This is awesome, @peggygannon. Thank you so much for doing this!

**Comment by peggygannon** [comment]
**11/20/2020 update**

This issue addresses recommendation number 1 above: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/261

**Comment by peggygannon** [comment]
Closing this issue. Recommendations and next steps are being tracked in this ticket: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16526
