### ISSUE TITLE
Analytics Implementation or QA Support for IVC Forms - 10-7959f-2 (FMP Claims)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#92984]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - IVC Forms

- **Poduct Name**

    - 10-7959f-2 Foreign Medical Program Claim Cover sheet
      
- **When is the launch date?**
    -  TBD - December?

- **Provide the link(s) for Product/Page urls**
  
    - base url: va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/

sub urls:
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/introduction
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/veteran-information
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/identification-information
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/mailing-address
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/same-as-mailing-address
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/home-address
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/contact-information
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/upload-supporting-documents
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/review-and-submit
va.gov/health-care/foreign-medical-program/file-claim-form-10-7959f-2/confirmation

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
 
       - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - N/A

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by Blivaditis** [comment]
The form is not currently available in staging. Will confirm tracking once it is live in staging.

**Comment by Blivaditis** [comment]
@baltes the form funnel has been reviewed and tacking has been confirmed on each page. Here is a google analytics dashboard [showing the events](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/Ij7FvoxySJGyprZFuEDp0w). Please reach out if there are issues or you have any questions.

**Comment by baltes** [comment]
@Blivaditis Thanks! Can you add permissions for me? bo.altes@agile6.com

![Image](https://github.com/user-attachments/assets/1f56e6a5-f6b6-4619-a758-451f8cc0485f)

**Comment by Blivaditis** [comment]
It has been updated!

**Comment by andrea-merrill** [comment]
@Blivaditis Hi! our urls have since changed - Do I submit a new ticket with new URLs or how do I update that?

**Comment by Blivaditis** [comment]
Hi @andrea-merrill can you fill out a [new version of this request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=analytics-request-and-update-kpi-dashboard.md)? Fill out the spreadsheet with all requested information, add the updated URLs, and include the end date of the last version and the start date of the new version. Once submitted we will review the request and get it queued up!

**Comment by andrea-merrill** [comment]
I might be horribly confused, so apologies in advance. I thought that this ticket (92984) was for Google Analytics whereas the ticket you linked for the [new version](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=analytics-request-and-update-kpi-dashboard.md) was for Domo.

I have already submitted a [new ticket for updates to KPI Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/108510), which again I thought was Domo, using the link you listed above.  I haven't commented on that ticket yet, but noticed that the automation to add to a board and assign a team member didn't work. 

How do I update google analytics with the new urls?

**Comment by Blivaditis** [comment]
Sorry I didn't see the domo ticket, for the google analytics just submit a new version of this ticket with the new URLs and requested tracking. @jestutt feel free to add anything I missed!

**Comment by andrea-merrill** [comment]
Fab, so just do another [Analytics Implementation or QA Support for [Team Name]](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) and we're golden for GA. 

No worries on missing the domo ticket, I fear I am the saboteur - I keep submitting tickets to you guys but they don't get picked  up by the automation to get then on a board.

**Comment by Blivaditis** [comment]
@andrea-merrill It may have been due to the PO change, we had to update our GitHub tickets to fix the automation.
