### ISSUE TITLE
Remove unused PrintLink component

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#92991]
## Description 

As part of a recent [spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84657) effort to catalog unused application code and unit tests, it was determined that the following component and unit test are unused and can be safely removed from the VAOS application.

### Development Checklist

- [ ] Remove component: [`src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/PrintLink.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/42e16f044bc5f4e9484e4d1569b85c954ae35a1c/src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/PrintLink.jsx)
- [ ] Remove associated unit test:  [PrintLink.unit.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/42e16f044bc5f4e9484e4d1569b85c954ae35a1c/src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/tests/PrintLink.unit.spec.js)

## Definition of Done
- [ ] Checklist completed
- [ ] All unit tests pass
- [ ] All e2e tests pass

**Comment by JunTaoLuo** [comment]
Removal complete. Given that this is a tech debt issue that won't change any functionality or UI, I'm closing the ticket.
