### ISSUE TITLE
Remove RequestedStatusAlert component

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#92994]
## Description
As part of a recent [spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84657) effort to catalog unused application code and unit tests, it was determined that the following component and unit test are unused and can be safely removed from the VAOS application.

### Development Checklist

- [ ] Remove component: [`src/applications/vaos/appointment-list/components/RequestedStatusAlert.jsx`](https://github.com/department-of-veterans-affairs/vets-website/blob/42e16f044bc5f4e9484e4d1569b85c954ae35a1c/src/applications/vaos/appointment-list/components/RequestedStatusAlert.jsx)
- [ ] Remove associated unit test:  [RequestedStatusAlert.unit.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/42e16f044bc5f4e9484e4d1569b85c954ae35a1c/src/applications/vaos/appointment-list/components/tests/RequestedStatusAlert.unit.spec.js)

## Definition of Done
- [ ] Checklist completed
- [ ] All unit tests pass
- [ ] All e2e tests pass

**Comment by ldelacosta** [comment]
@simiadebowale - if you could review and close if needed.

**Comment by JunTaoLuo** [comment]
Given that this is a tech debt ticket and we're only removing unused code, I think this is safe to close. Simi, let me know if you think otherwise.
