### ISSUE TITLE
QA Standards - IVC Forms - 10-10d CHAMPVA Application Form

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#92995]
#### VFS team name
IVC Forms

#### VFS product name
10-10d CHAMPVA Application Form

#### VFS feature name
new product

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
no traceability reports included
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 95.78

- Functions %: 95.4

- Statements %: 95.97

- Branches %: 93.27

- [x] Standard has been met
- [ ] Standard has not been met
#### Endpoint Monitoring (Completed Playbook)
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
You have the required information and plan to respond to errors / failures but need to use the [platform playbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/template.md).

---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by baltes** [comment]
IVC Forms playbook: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/team/ivc-forms-monitoring-playbook.md
