### ISSUE TITLE
Replace back links with DS component

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#93012]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The DS recently built a [back link component](https://design.va.gov/storybook/?path=/docs/components-va-link--back).  

Use this component to replace the current custom back links on:

* Upcoming, Past, and Pending details pages
* Scheduling pages (all except type of care)

Please note:
* There are no changes to content. 
* There are no changes to breadcrumbs.

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
- [Figma file]() (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/93012?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
UX team will validate in staging.

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta looks good on all scheduling pages! Clicking the icon is working too.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
