### ISSUE TITLE
[SPIKE] Consider unmoderated study to solicit quick feedback on content changes

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93025]
## Tasks

- [x] Think about: what concerns or questions about the content do we have about 1 or more of the low-fi wireframes? E.g., will Veterans understand what to do based on this content? 
- [x] Consider unmoderated study to solicit quick feedback on content questions. Could we do a study to get answers to these questions?

**Comment by cgednalske** [comment]
Proposing an unmoderated survey to allow us to gather data that can inform **a)** any design iterations that need to be made before piloting this change and **b)** in-person questions we'd like to ask at facilities. We can also check if there is a possibility of sending a survey to staff as well, to similarly gather data that can inform our in-person questions and allow us to really dig into the problem space.

**Note:** Contents of proposed structure may change - working with @benbrasso-agile6 to understand how this survey can incorporate questions that will support the in-person questions.

### Overview of survey contents:

- General questions for Veterans who have used check-in
- Questions to check effectiveness of content changes on specific pages

### Proposed survey setup (Veteran-facing):

Include our disclaimer about how we won’t judge opinions and want to hear them.

> #### Part 1: General questions about past use of online check-in
> 
> - We’ll start with a few general questions about online check-in.
> 
>   - Have you used online check-in in the past to check in for a medical appointment at your VA health facility?
>   - Tell us about your experience using online check-in. (ask to include facility name?)
>   - How would you rate your experience using online check-in?
>   -  Tell us about your experience interacting with staff when using online check-in. (ask to include facility name?)
>   -  How would you rate your experience interacting with staff when using online check-in?
>   -  Is there anything you would change about the online check-in process?
>   -  How likely are you to recommend online check-in to a friend or family member?
> 
> #### Part 2: Specific questions about the pages that have changed
> - Now we’d like you to review a few screens and answer some questions.
>   - Image 1: Imagine you just started Check-in and arrived on this page. 
>     - Tell us your interpretation of this page.
>     - Do you have any additional comments about this page you’d like to share?
> 
>   - Image 2: Next, imagine you answered a variety of questions about your contact information and then arrived on this page. 
>     - Tell us your interpretation of this page.
>     - Based on the information provided on this screen, have you completed online check-in in this scenario?
>     - Is there anything else you need to do?” If so, what?
>       - Yes / No 
>     - Do you have any additional comments about this page you’d like to share?
> 
> #### Part 3: Follow-up
> - Do you have any other comments you would like to share about online check-in or the screens/pages you reviewed during this activity?
> 
> - Thank you for your participation and feedback!

**Comment by cgednalske** [comment]
@benbrasso-agile6 we good to close this? Info above is just a starting base for questions.

**Comment by benbrasso-agile6** [comment]
Yep yep, plan is looking awesome
