### ISSUE TITLE
Remove Heather Justice from EZR Product Manager

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#93040]
### Description
Remove Heather Justice from EZR Product Manager, leave Alex Seelig

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS Health Apps

**Comment by jknipes** [comment]
Hi @alexseelig , Which page on [Platform Website](https://depo-platform-documentation.scrollhelp.site/) needs this update?

**Comment by alexseelig** [comment]
Hi sorry, the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) page

**Comment by jknipes** [comment]
@alexseelig thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Hi @alexseelig , Please submit the request using the [Product Directory Change Request](https://github.com/department-of-veterans-affairs/product-directory/issues/new?assignees=cbonade&labels=&template=update-product-request.yml&title=Product+Directory+Change+Request+for+%5BProduct+Name%5D)

**Comment by alexseelig** [comment]
Thank you!
