### ISSUE TITLE
10-7959a Research - Synthesis & Analysis

### ISSUE THREAD

**Issue by StevenStraily** [department-of-veterans-affairs/va.gov-team#93053]
- Synthesize everything captured during research sessions in the Mural
- Organize everything and perform thematic analysis
- Analyze the different themes and create a draft research report

**Comment by jamiefiore** [comment]
[First draft of the report](https://docs.google.com/document/d/1_BxpXb8z1ao4MMs1BbeILVi7n8H7UbjVO-UY13pRqIk/edit) is complete. Will close this and open a new ticket for the revisions.
