### ISSUE TITLE
[UX] Determine text to use for clinics not in the standalone app pilot

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93050]
## Tasks

- [x] Determine text to use for clinics not in the standalone app pilot. Avoiding creating a new template would be no blocker for VeText.

**Comment by benbrasso-agile6** [comment]
@brianseek here's the text message that we are planning (should plan) to use for someone texting 'travel' to the OH SMS number. 

https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=715-6651&t=xYhEZCxvq3ZWZprj-4

So, Horton probably implemented this nationally. But, if we're creating something in CHIP to look for 3-digit stations, the text message would be the same (as the link above). 

That what we need here for this ticket? cc @loripusey

**Comment by loripusey** [comment]
I think that should do it.

**Comment by brianseek** [comment]
@benbrasso-agile6 is this a new message or the existing one? Either way, we will need to work with vetext so they know to expect this type of error back from CHIP, but that can go in that ticket.

**Comment by benbrasso-agile6** [comment]
Yeah, I didn't change the content. I'm guessing Horton has implemented all of these, since he reviewed them a while back. 

You going to take a next step here?

**Comment by brianseek** [comment]
@benbrasso-agile6 yep, I can take it from here. @loripusey did you already create an engineering ticket? Also any word on which stations we are piloting?

**Comment by brianseek** [comment]
found the ticket here: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/92905

**Comment by brianseek** [comment]
I added some more details to that ticket
