### ISSUE TITLE
[Feature] Clean up unused files in the Appointments tool 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#93068]
#### Objective: Team will provide the details here_

<details>
   <summary>Feature Checklist</summary>

## Product Checklist 
<details>
  <summary>Product Checklist</summary>

### Product (N/A) 
- [ ] Initiative Summary
- [ ] Release Plan
- [ ] Update product guide

### VSP Collaboration Cycle (N/A) 
- [ ] Project Kickoff
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging Review
- [ ] Privacy & Security Review
- [ ] Full Accessibility & 508 Audit
</details>

### UX Design Checklist (N/A) 
<details>
  <summary>UX Design Checklist</summary>

#### Design (N/A) 
- [ ] Review problem/opportunity statement
- [ ]  Add questions and assumptions to initiative brief
- [ ]  Add research links to initiative brief
- [ ]  Note any related icebox tickets
- [ ] Review VAOS OKRs
- [ ]  Review OCTO goals
- [ ] Document high-level research/design plans

</details>

### Engineering Checklist 
<details>
  <summary>Engineering Checklist</summary>

#### Engineering 
- [ ] Review design specs
- [ ] Add unit test coverage
- [ ] Add E2E test coverage
- [ ] Update Rspec
- [ ] Update swagger
- [ ] Document business logic changes

</details>

### QA Checklist (N/A) 
<details>
  <summary>QA Checklist</summary>

#### QA (for collab cycle) (N/A) 
- [ ] Regression test plan
- [ ] Test plan
- [ ] [Coverage for References
- [ ] [Summary(Defects)
- [ ] E2E tests
- [ ] Code coverage

**Comment by JunTaoLuo** [comment]
We've completed all the cleanup identified in the first pass. @ryanshaw do you want to run your tool again and see if any new components or files are flagged? If nothing shows up then I think this feature can be wrapped up.

**Comment by ldelacosta** [comment]
Per @ryanshaw - we are good to close out the feature.
