### ISSUE TITLE
SOCKS access for [Kyle Soskin]

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#93083]
### Your Name

Kyle Soskin

### Your Email

kyle.soskin@coforma.io

### Your GitHub Handle

kylesoskin

### Your Role and Team

Benefits and Claims, Tech Lead, Coforma

### Product Manager (PM) name and email

Lisa Capaccioli <lisa.capaccioli@coforma.io>

### Product Owner (PO) name and email

Emily Theis <emily.theis@va.gov>

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHdG8Gs2RXIlq/3szI6LaIcdE0QiS9y+z+XvsOVjLrNj kylesoskin@Coforma-GWG17F9XG2-Kyle-Soskin

### SSH Key Passphrase

- [X] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

Previously Adjudicated/Already favorably adjudicated, no new eQip completed/required

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by barbarello** [comment]
@kylesoskin kylesoskin Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
