### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by nicholashibbits1** [department-of-veterans-affairs/va.gov-team#93098]
### Your Name

Nicholas Hibbits

### Your GitHub handle (Flipper UI access is managed through GitHub)

@nicholashibbits1

### Team, Role, and Company of the target individual

Education Data Migration Team, Frontend Developer, GovCIO

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Adding a new feature, need to enable or disable it depending on the environment.

**Comment by bmatos312** [comment]
@nicholashibbits1 Hello Nicholas, can you provide some reasoning for the prod access to get the ticket moving a bit quicker?

**Comment by nicholashibbits1** [comment]
@bmatos312 thinking I need to switch the feature toggle to On, when the feature is ready for prod. If best practice is to defer to my dev or project lead to enable/disable the feature, please let me know.

**Comment by bmatos312** [comment]
@nicholashibbits1 That shouldn't be a problem and you are granted 6 months of prod access and when it gets close we will setup a reminder and ping you again to see if you still need prod access

**Comment by bdech** [comment]
Reached out to Nicholas and he still requires this access. Reinstated Flipper access to all environments.
