### ISSUE TITLE
[Tier 3: Low] Submitted Claim Not Processing

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#9312]
**Date issue reported:** 5/19/2020
**Issue Topic:** Disability claim application, Intent to File 
**Source of the issue and ticket number**: IRIS 200310-000060
**Priority**: Low

**Description of Issue**

1.	Have you separated from your military or uniformed service? YES
2.	Had you filed a claim before this most recent claim? YES
3.	You said you were able to successfully complete the claim application on VA.gov. Is that correct?

NO YOUR SYSTEM HAS SAID SINCE IT CAME ONLINE OVER A YEAR NOW (WE ARE SORRY WE ARE HAVING ISSUE AND OUR SYSTEM DOES NOT WORK) I GET A MESSAGE LIKE THIS MOST TIMES WHEN I WAS ABLE TO CLICK ON THE BLUE BOX FOR SUBMITTING A CLAIM AND IT takes me to questions then to a box saying since I am in the system it will fill in some data for me  CLICK ON IT WILL DOWNLOAD MY DATA (BANG WERE SORRY) most times I don't even get that far. After Over 6 Months E-Benefits allowed the data in their system to be submitted. I sent a screen shot prior I will cut and past your system steps and the results of what it has said over a year basically a screen shot (I did get a letter in the mail March 2019 saying I had opened a new claim the first time  I tried using your system in Feb 2019 but nothing since)

_Error Message Seen by User_
We’re sorry. Something went wrong on our end.
We’re sorry. Your Intent to File request didn’t go through because something went wrong on our end. For help creating an Intent to File a Claim for Compensation, please call Veterans Benefits Assistance at 800-827-1000, Monday – Friday, 8:00 a.m. – 9:00 a.m. ET. Or, you can fill out VA Form 21-0966 and submit it to:
Department of Veterans Affairs
Claims Intake Center
PO Box 4444
Janesville, WI 53547-4444
What is an Intent to File?

**Comment by clantosswett** [comment]
I reached out to the veteran today to get more details of his issue. Once I have those, I will add to the issue and loop in the benefits and memorial team to investigate further.

**Comment by clantosswett** [comment]
The veteran responded and provided new information that I have added to the issue. This case needs to be assigned to the benefits and memorial team to investigate further.

**Comment by clantosswett** [comment]
@luke-gcio This issue has been with your team for seven days and we have not received any confirmation. Please advise if there is any additional information that we can obtain and provide to you in order for your team to accurately address this issue. Thank you!

**Comment by jwoodman5** [comment]
This will move forward with BAM1 team as part of a holistic effort to better support these types of requests.
