### ISSUE TITLE
Update edit contacts design based on how NoK/EC is used by medical center staff

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#93138]
## Description

Validate edit contact experience against real-life usage by front-line staff & revise this ticket on edit functionality based on what we learn. 

### User story

As a Cartography team member, I want to understand how front-line staff use the NoK/EC fields in practice, to help us determine how to present the information to users in the FE experience. 

As a Veteran, I want

### Notes
- [Figma file with designs](https://www.figma.com/design/uYMdNtQnrzq7OiDl0rPF9k/Profile---Personal-health-care-contacts?node-id=0-444&t=3d4ghKWFYD4CsiSz-1)
- Kristen McConnell sent us names of front-line staff who we can contact to reach out about NoK/EC usage by front-line staff. 

Possible tasks:
- [x] Reach out to the contacts sent by Kristen McConnell
- [x] Find out how it's used wtihin facilities
- [x] Update UX design 
- [x] Get A11y feedback 
- [x] Finalize designs (to the extend we can) 
- [x] Document rationale behind designs 

## Acceptance criteria
- [x] We understand how the fields are used within medical center facilities by front-line staff
- [x] designs reflect this knowledge
- [x] follow-on tickets created as needed
- [x] Finalize designs (to the extend we can) 
- [x] Document rationale behind designs

**Comment by jonathanjnelson** [comment]
[Slack thread with Kristen McConnell ](https://dsva.slack.com/archives/CMNQT72LX/p1726173889513699)

**Comment by jonathanjnelson** [comment]
Screenshots with mock data of CPRS system: 

**With 2 next of kin listed** 

<img width="1188" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHYvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9748403c7ab12f5402d0039c7cb225a04ed6087/Screenshot%202024-09-23%20at%202.32.54%E2%80%AFPM.png" alt="Screenshot 2024-09-23 at 2.32.54 PM.png" />

**With one emergency contact and next of kin listed:** 

<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi8vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d84f9f12f36b278351c5796ef8088aaa990c86f/Screenshot%202024-09-25%20at%2010.51.24%E2%80%AFAM.png" alt="Screenshot 2024-09-25 at 10.51.24 AM.png" />

**Comment by jonathanjnelson** [comment]
**High level takeaways from email responses from from Kyle Oakman (former Assistant Chief at Bay Pines)** 

- Reinforces the contextual nature of contacting Emergency contact and next of kin and the importance of relationship to the Veteran (“discretion of the medical provider”) 
- Typically, it would stop after first NOK was reached (but again, would reference the relationship)
- We have learned from screenshots from Elizabeth - if two next of kin, it is labeled as “Next of kin information” and “Secondary next of kin” 

9/20/24 Conversation with Elizabeth Marinella (Assistant Chief HAS at Pittsburgh VAMC) 

**High level takeaways from conversation with Elizabeth**

- Poorly understood terms - Emergency contact and Next of kin. Spends the majority of her days explaining what each is
- Staff will not rely on order or label Primary/Secondary
- It is typically nuanced and contextual (i.e., who has been coming to appointments lately) 
- Will often look at the relationship to the patient 
- Would love some kind of definition - explaining each - and a link “These names aren’t who you want here’s how to fill out an advance directive

**Comment by jonathanjnelson** [comment]
[Link to A11Y review ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92319)

**Comment by fmccaf1** [comment]
Just went into the figma file and made some small tweaks. I think this is done and ready to be picked back up when we're ready to implement this work.
