### ISSUE TITLE
Access for Gregg Puhala

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#93147]
I have a backend developers that I would like to request access for them to a specific s3 bucket.
The developer is :

- Gregg Puhala
The account to mimic for access is:
- Vanson Samuel
The devs should already have AWS accounts.
Justification for access: All devs work on the same project and have a need for visibility to ensure files are moving on a daily basis. Access should only be needed for 2 months if an end date needs to be specified.

**Comment by barbarello** [comment]
fixed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/93141
