### ISSUE TITLE
AWS access for Mindy Tommasina Miller

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#93160]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Tommasina Miller

### Your Email

tommasinamiller@navapbc.com

### Team, Role, and Company of the target individual

Team Benefits Disability Experience, Full-stack engineer, Nava

### Product Manager (PM) name and email

Jared Pace jared.pace@agile6.com

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### Desired AWS Access

I am on the VA Benefits team and will be developing features and bugfixes, along with investigating issues, to the vets-api and vets-website repos.

I need access to debug and investigate issues in those environments, and also need all permissions needed to develop on the platform.

Access requested should be ongoing as issues that need resolved/debugged could come and go at anytime.

I also need access to the s3 bucket for staging and production for our team.

At a minimum, I need group_memberships = ["dsva-vagov-developers", "dsva-vfs-developers", "adhoc-vetsgov-ssm-prod", "force-MFA"]

Thank you!

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/c9c7bee0-4b32-4b23-9e64-8f0dc1209a05">

### Additional Notes

I had previous access before I left for parental leave. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by stoiven** [comment]
User exists in Atlas

**Comment by stoiven** [comment]
group membership required - adhoc-vetsgov-ssm-prod

@department-of-veterans-affairs/operations-aws-approvers - User is requesting access to parameter store as well as S3 prod access.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by tommasina-va** [comment]
@hgbarreto is there something else I need to do to get AWS credentials? Just curious about the status on this. Thanks! cc: @JonathanKamensDVA
