### ISSUE TITLE
Adding Shannon Eversoll to DSVA Slack

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#93188]
# Description
Please add shannon.sversoll@va.gov as a single-channel member to #medallia-collaboration. 

She is a Business Process Analyst for Enterprise Measurement and Configuration Services and coordinates our work with VSignals for Medallia implementation on VA.gov.

**Comment by LEHigley** [comment]
i couldn't add to that channel for some reason, but invited to slack and the general channel
