### ISSUE TITLE
[Content] Update content for can't show all appts expandable alert

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93181]
## Tasks

- [ ] Update content for can't show all appts expandable alert on appt list pages; specifically, content change reco from CAIA

**Comment by benbrasso-agile6** [comment]
@outerpress https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2267-8113&t=wZytfLpL3R8JnDhz-4

**Comment by outerpress** [comment]
@benbrasso-agile6 could you update this to use the [VAOS UX Task Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d6c10129e7ba32134f9a04532bd3df47b67e6860/.github/ISSUE_TEMPLATE/vaos-ux-task.md?plain=1#L4)? And link the CAIA ticket and the design file in there.

**Comment by benbrasso-agile6** [comment]
Closing this ticket, since I duped it here - https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/93387
