### ISSUE TITLE
[Content] Update canceled appt alert on details page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93180]
## Tasks

- [ ] Update canceled appt alert on details page; specifically, unbold first sentence based on CAIA and VA content guidelines

**Comment by benbrasso-agile6** [comment]
@outerpress created a ticket to track this work - https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2268-35206&t=wZytfLpL3R8JnDhz-4

**Comment by outerpress** [comment]
@benbrasso-agile6 could you update this to use the [VAOS UX Task Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d6c10129e7ba32134f9a04532bd3df47b67e6860/.github/ISSUE_TEMPLATE/vaos-ux-task.md?plain=1#L4)? And link the CAIA ticket and the design file in there.

**Comment by benbrasso-agile6** [comment]
Closing, replaced with https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/93385
