### ISSUE TITLE
Update Old UA Documentation on Platform Website

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#93209]
### Description
We need to update some broken links, and outdated content around GA on our Platform Website. This will include removing links to our old UA Properties, removing links to old dashboards, etc.

---

### Tasks
- Review list of pages being flagged as outdated. Use [this list](https://docs.google.com/spreadsheets/d/1hdstMrAC1UFYl_6mqeGT3f0kHLxmRefT3oymA1IGOB0/edit?gid=0#gid=0).
- Make edits to pages where necessary.
- Pages have been fully/partially updated: 
- New Users to Google Analytics - CY - Fully Updated;
- Frequently Asked Questions - CY - Partially Updated - Outstanding notes in spreadsheet

### Acceptance Criteria

- [x] Pages have been updated
- [x] Updates have been pushed to Platform Website

**Comment by johnny-jesensky-adhoc** [comment]
We added this to the current sprint due to some extra bandwidth from @ChristineYoungZA. 

Christine, can you please add what pages you are updating into the description on this ticket?

**Comment by ChristineYoungZA** [comment]
Do you want those that are only fully updated or partially updated also? @johnny-jesensky-adhoc

**Comment by Blivaditis** [comment]
I update our documentation for the Google Analytics and Google Tag Manager page as well as the Google Analytics Data Dictionary page. There are other pages under these sections that need updating however they tie into components, events, DLE, and have not been updated in a minimum of two years. These docs will need more than minor updates we will likely have to rework them and add two years worth of updates.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA -- looks like these are the pages you updated.

- [New Users to Google Analytics](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/new-users-to-google-analytics) - CY - Fully Updated;
- [Frequently Asked Questions](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/frequently-asked-questions) - CY - Partially Updated - Outstanding notes in [spreadsheet](https://docs.google.com/spreadsheets/d/1hdstMrAC1UFYl_6mqeGT3f0kHLxmRefT3oymA1IGOB0/edit?gid=0#gid=0)

Moving this to _Done_. Though updating our docs will be an ongoing effort.

FYI @Blivaditis
