### ISSUE TITLE
Action Items from Exploration of Pre-Check-in Drop in Completions

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#93224]
Action items to explore:

- [x] Remove the Refresh button from Pre-Check-in?
- [x] Change the wording of the "Review your information now"?
- [x] Change the wording of "Your appointments"?
- [x] Create new feature page in pre-check-in Figma file

For action item # 3: In previous discovery, we came up with possibilities "Appointments for pre-check-in" or "Your appointments for pre-check-in," but we are still trying to determine how we can word this without including "pre-check-in" (or at least eventually not have pre-check-in). (I think including the word "pre-check-in" could be a good test - Ben)

**Comment by zach-park** [comment]
@benbrasso-agile6 , ready for validation:
https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=266-6584&t=t7w5zbWITK4kWEBP-1
https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=266-6536&t=t7w5zbWITK4kWEBP-1

**Comment by zach-park** [comment]
@benbrasso-agile6 , ready for validation:
https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=768-5412&t=t7w5zbWITK4kWEBP-1

**Comment by benbrasso-agile6** [comment]
Tagging @cgednalske  too :)

**Comment by zach-park** [comment]
Ready for validation @cgednalske @benbrasso-agile6

**Comment by cgednalske** [comment]
🎉  Added some comments in Figma!

**Comment by zach-park** [comment]
> 🎉 Added some comments in Figma!

Updated the wireframes with annotation and the header. And it's ready for validation.

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park we either need to stub out a ticket for FE to refine next, next sprint for this work OR post information about this work in Slack and make it clear to engineers to stub out their own tickets for this work, cc @loripusey

**Comment by loripusey** [comment]
Can we annotate exactly what the changes are? It's hard to just look at these Figma files and understand exactly what is changing. Engineers should be able to look at them and only have to focus on the call-outs for the changes.
@benbrasso-agile6 @zach-park

**Comment by loripusey** [comment]
I'll create a FE ticket but I'd like the changes highlighted.

**Comment by zach-park** [comment]
> Can we annotate exactly what the changes are? It's hard to just look at these Figma files and understand exactly what is changing. Engineers should be able to look at them and only have to focus on the call-outs for the changes. [@benbrasso-agile6](https://github.com/benbrasso-agile6) [@zach-park](https://github.com/zach-park)

Change notes are added now. Thank you!

**Comment by benbrasso-agile6** [comment]
To help the engineers, you might think about relocating or moving the options that aren't being used to a different section on that page. And then, provide a link to the final wireframes section. 

Then, they don't have to do any guesswork which wireframes to be looking at.
