### ISSUE TITLE
[BE/QA] 10-10EZR - Prevent users from uploading attachments with invalid file types

### ISSUE THREAD

**Issue by JoshingYou1** [department-of-veterans-affairs/va.gov-team#93248]
We had several incidences where the user altered the file extension of an attachment on the frontend in order to circumvent validation. They were then able to successfully upload the document. However, because VES only accepts certain file types, the submissions would ultimately fail.

- [x] Disallow users from being able to manually change the file extension of a file and create it.
- [x] Write tests
- [x] QA

**Comment by JoshingYou1** [comment]
Refer to the discovery ticket here: #92710

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that users are unable to upload attachments with invalid file types. Users are able to upload file types that are supported as expected.
