### ISSUE TITLE
[Design] Badge indicator: Create FE documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93244]
## Background
We need to create the FE documentation including specs and implementation details for the badge indicator as we'll be implementing it on the "Go to your inbox" link in the health care section on My VA.

## Tasks
- [x] Complete FE documentation started [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/badge-indicator/badge-indicator-FE-documentation.md)
- [x] Share with PMs and devs for review

## Acceptance Criteria
- Design related content for FE documentation is complete, besides error handling

**Comment by mattmarino-adhoc** [comment]
I inquired about how VA Mobile App team handled a possible error scenario with item count not being displayable, their answers appear in this Slack thread: https://dsva.slack.com/archives/C018V2JCWRJ/p1727804592232889

**Comment by mattmarino-adhoc** [comment]
Marking as complete, but we still need to finalize error handling as well as get technical documentation here.
