### ISSUE TITLE
Contact Center Review for VBA Regional Offices Modernized Pages

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-team#93253]
# Request the Contact Center Review 

## Description
VBA regional offices modernized pages bring additional functionality and context to the regional office facility pages for the veteran benefits administration. Editors have the ability to add detailed information about the services offered at their facilities, in addition to things like parking instructions and detailed contact information.
[Collaboration Cycle Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029)

### Launch Date
The modernized pages have already begun rolling out. The facilities themselves are responsible for performing the updates, so more pages will continue to come online as editors perform the necessary steps. Editors are undergoing training in cohorts and we are currently training the third cohort in four sessions.

### Version Number
The product guide version is the 9/19/24 update

### Product Guide
[Facility-Locator-product-guide-updated 09.19.24.docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/Facility-Locator-product-guide-updated%2009.19.24.docx)

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
The draft looks good. Sending for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. Current copy attached; please use for future revisions. Thank you![Facility-Locator-product-guide-SRT 09232024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1FQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1264f09786129159bd486917045e2c43def0e827/Facility-Locator-product-guide-SRT%2009232024.docx)
