### ISSUE TITLE
[SC]: Some errors for form fields not announcing in screen readers because of focus management

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#93251]
## What happened?

**Describe what went wrong**:

Some error messages don't announce properly because we move focus to another container. That change of focus blocks the announcement of the `role="alert"` on error messages. This doesn't happen everywhere, but it some places. Also, note that it occurs in multiple places. Check out the videos.

**Add the steps to reproduce the bug**:

1. Go to `https://staging.va.gov/decision-reviews/test-sc/ or the regular SC form.
2. As an example, go to the "Do you want us to get your medical records from a VA or military treatment location? (*Required)" question.
3. Turn on VoiceOver or similar screen reader.
4. Try to proceed without selecting an option.
5. Hear the error text not announce. Instead, the question announces again because focus is shifted to the container.

**Add a screen recording or photo**:

Check out me reproducing this in both the SC prototype and on the staging from.

Prototype form:

[Prototype form video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd858bf7bbe71e9613e57613f7bc106ae2585a37/video1404541702.mp4)

[SC form on staging](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd25zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb51a34a05a6d60a7587bdd8a2e8b407cc00fc65/video1065849850.mp4)

**Suggested fix**:

- Don't move focus when an error occurs. Let the `role="alert"` announce. The Veteran will hear the error and need to navigate to it.
- In the future, we'll try to work toward a better solution for errors in the design system.

## How severe is the problem?

- [X] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

## What is the desired behavior?

1. _When a user triggers an error, the **visual** result is the error appears on screen and announces in a screen reader._

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

_Note:_ We may need to check other forms.

**Comment by anniebtran** [comment]
Robin is going to open a couple PRs for this

**Comment by Mottie** [comment]
Still not available in staging... hopefully they'll fix the problem by tomorrow

**Comment by Mottie** [comment]
It looks like the alternate focus method is ready in staging now! I've only updated the SC & HLR prototypes:
* https://staging.va.gov/decision-reviews/test-sc
* https://staging.va.gov/decision-reviews/test-hlr

**Comment by davidakennedy** [comment]
Just wanted to note that I [tested the SC form already here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92801#issuecomment-2408023455).

In testing the HLR form, I'm seeing some inconsistencies:

Most of the sections move focus when clicking on "Edit" to the next available focusable form input. A few of them move it to the heading in the section. Ideally, we'd move focus to headings if they're there of form inputs if no headings exist. @Mottie We talked about this, I think, but let me know if I'm misremembering challenges with this approach.

Here's a video of my testing:

https://github.com/user-attachments/assets/d572d8e5-c56d-4029-b5b4-4887a6dc5e09

**Comment by Mottie** [comment]
Hmmm, that's very weird. I feel like I forgot to turn on something for HLR... let me double check

**Comment by kayline** [comment]
@davidakennedy to determine if this behavior should apply to all forms

**Comment by kayline** [comment]
For now, apply to all DR forms, wait to apply to forms outside our team

**Comment by kayline** [comment]
3 PRs ready for review

**Comment by kayline** [comment]
DK will present to accessibility team

**Comment by davidakennedy** [comment]
I presented this Friday, 11/7 at Accessibility Specialists Office Hours. There was broad support that the current changes made by @Mottie are good changes to keep in place. This ticket can be closed, cc: @comaurice.

Next steps for DK:

- File a ticket with the design system team to update error message documentation.
- File a ticket for improving error messages with an error summary component.

**Comment by comaurice** [comment]
Thanks @davidakennedy. Closed.
