### ISSUE TITLE
Flipper UI access for Alison Jones

### ISSUE THREAD

**Issue by ajones446** [department-of-veterans-affairs/va.gov-team#93257]
### Your Name

Alison Jones

### Your GitHub handle (Flipper UI access is managed through GitHub)

ajones446

### Team, Role, and Company of the target individual

Benefits and Claims, Full-stack Engineer, Oddball

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

My team (DBEX team 2 carbs) releases work to production under feature flags, including upcoming releases related to the Lighthouse API migration.

**Comment by GWright321** [comment]
Greetings @ajones446 we confirmed your presence in Atlas and now you have been given access to Flipper UI Lesser Environments and Production. Please reach out if you have any additional questions. Thank you!
