### ISSUE TITLE
Analytics Implementation or QA Support for [Verify Your Enrollment]

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#93250]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - [govcio-VYE-codereviewers]

- **Poduct Name**

    - [Verify Your Enrollment]
      
- **When is the launch date?**
    - [July 16th or 19th 2024]

- **Provide the link(s) for Product/Page urls**
  
    - [va.gov/education/verify-school-enrollment/mgib-enrollments]

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    • We want to capture the following:
    • how many users click the submit button
    • how many users click the Benefits profile
    • how many users click to edit their direct deposit
    • how many users click change address    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Administrative/vagov-users/vye-staging-users.csv](Administrative/vagov-users/vye-staging-users.csv)

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks @GcioNapoleon -- confirming we've received this. We'll review in an upcoming refinement session, and let you know about timing and whether we have any follow-up questions.

**Comment by Blivaditis** [comment]
Hi @GcioNapoleon I am reviewing the tracking on the link provided and had a quick question. How do users get to the benefits profile? I have been looking for it to verify the tracking, and want to be sure I have the right interaction.

**Comment by Blivaditis** [comment]
Hi @GcioNapoleon, I have reviewed the enrollments page and verified the tracking you highlighted. All tracking functioned as expected and I did not encounter any issues, here is a [GA4 report ](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/mKdilX0dQtCOayzrKV5jjg) which shows your events.

**Comment by GcioNapoleon** [comment]
@Blivaditis  When I click on your link I see the following screen

![Image](https://github.com/user-attachments/assets/9dd30d1b-686b-4da8-8487-e911312db497)
