### ISSUE TITLE
Sidekiq Admin UI access for Eric Tillberg

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#93263]
### Your Name

Eric Tillberg

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@Thrillberg

### Team, Role, and Company of the target individual

Veteran Facing Forms, Fullstack Engineer, Pluribus Digital

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

COR is Reney Cook.

**Comment by GWright321** [comment]
@Thrillberg  You’ve been granted access to the dev, staging, and sandbox.
