### ISSUE TITLE
Remove back link when identity verification alerts are visible 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#93267]
## Description

Sara + Laura audited the sign-in flows from My HealtheVet on Va.gov to MHV Classic following some updates in the sign-in process writ large & identified a few issues. It appears that LOA1 credentials can no longer sign-in directly on the national portal, however there is a loophole where users can sign-in as LOA1 on VA.gov and go backward to the national portal. When they do that, they hit a sign-in alert that creates a ping-pong effect, sending them back and forth from Va.gov to the national portal with confusing messaging around identity verification. 

We should eliminate the ability for non-ID verified users to go back to the national portal from the MHV on VA.gov landing page to remove this problematic route. Doing so would also align the VA.gov experience with the national portal's, which no longer allows LOA1 users to see the classic version whatsoever. 

### User story

As a Cartography team member, I want to remove second paragraph (which includes the back-link to classic) in the lede text of the MHV on VA.gov landing page in any scenario where an ID-verification alert is present, so that I don't enable a route that creates a horrible ping-pong experience for users.  

### Notes
[Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1726840710795319)
<img width="795" alt="Screenshot 2024-09-20 at 8 50 35 AM" src="https://github.com/user-attachments/assets/2bd4dcd7-2ab4-49fb-a2df-373c0f232994">

Possible tasks:
- [ ] Remove the second paragraph of the lede text (pictured above), including the back link to the national portal for these alert scenarios: 
  - [ ] ID-verification alert for My HealtheVet basic credentials (LOA1) that tells users to sign in with a different type of credential.
  - [ ] ID-verification alert for ID.me/Login.gov LOA1s  

## Acceptance criteria
- [ ] the back link to national portal is no longer visible for any users with an LOA1 credential (see ID-verification alerts) who visit the MHV on VA.gov landing page. 
- QA review

**Comment by allanto-ah** [comment]
Slack conversation to remove the second paragraph from the unregistered alert as well: [Slack link](https://dsva.slack.com/archives/C0581MN69TJ/p1726854224882899)

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the paragraph with the back link when verification alerts are visible have been removed. 

Unverified
![Image](https://github.com/user-attachments/assets/235957f2-137e-463d-9cdb-beeb5b651fb2)

Unregistered
![Image](https://github.com/user-attachments/assets/6e75439e-f542-4364-bcf8-e391745afac4)
