### ISSUE TITLE
FE | Contact Information | Update Button Logic & Alert Messaging on Address Section

### ISSUE THREAD

**Issue by asiisii** [department-of-veterans-affairs/va.gov-team#93272]
### **Description:**

This ticket addresses changes to the Address section of the Contact Information page in the frontend UI, based on updated requirements:

1. **Remove Redundant Button:**
   - **Current Behavior:** When the backend sends no `validationKey` and there are no `confirmedSuggestions`, both the `Go back to edit` and `Edit Address` buttons are displayed. Both buttons open the address form in edit mode, making the `Edit Address` button redundant.
   - **New Requirement:** The `Edit Address` button should no longer be displayed in this scenario, and only the `Go back to edit` button should remain visible.

2. **Alert Message Updates:**
   - Update the alert messages displayed for two specific cases:
     - **Case 1:** No `validationKey` and no `confirmedSuggestions`.
     - **Case 2:** No `validationKey`, but there is a suggestion.
   - **Note:** The designer is still working on updating the Figma designs for these cases, and the exact wording for the Alert message will need to be incorporated once provided.

---

### **Acceptance Criteria:**
- [ ] The `Edit Address` button is not displayed when no `validationKey` is present and there are no `confirmedSuggestions`.
- [ ] The `Go back to edit` button remains as the only option in this scenario.
- [ ] Update alert messaging for:
   - No `validationKey` and no `confirmedSuggestions`.
   - No `validationKey` but with a suggestion.
- [ ] Implement the exact alert message wording once the updated Figma designs are available.

---

### **Additional Notes:**
- Work with the designer to ensure the updated Figma designs are reflected in the implementation.
- Ensure the UI reflects the removal of the `Edit Address` button as per the new requirements.

**Comment by ACParker89** [comment]
@ACParker89 Roll Over to 45

**Comment by asiisii** [comment]
Questions:

1. what's `SHOW_SUGGESTIONS_NO_CONFIRMED_OVERRIDE` - file `src/platform/user/profile/vap-svc/constants/addressValidationMessages.js`:66
2. document the definition for the `override` and `validationKey` and how they relate to terms of code and design

**Comment by ACParker89** [comment]
@asiisii do we want to roll this into 47?

**Comment by ACParker89** [comment]
@asiisii - is there any additional work needed to follow on to this ticket? Should we create a testing support ticket for this?

**Comment by asiisii** [comment]
> [@asiisii](https://github.com/asiisii) - is there any additional work needed to follow on to this ticket? Should we create a testing support ticket for this?

@ACParker89, I’m still waiting for my PR to be reviewed. Once it’s merged, we’ll need to validate it
