### ISSUE TITLE
Implement gating approval mechanism in CI pipeline for approved apps

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#93271]
## Issue Description
As part of staged continuous deployment, after the code deploys to staging we will need a pause inserted into the CI deployment that requires a senior developer from an app team to approve the deployment. This will give teams the opportunity to review their code on staging if they wish before deployment, while still giving them control over when they deploy.

---
## Tasks
- [x] Implement CI approval required check that requires an approval to deploy from a senior VFS developer.

## Acceptance Criteria
- [x] Deployment now pauses for a staging review, allowing senior VFS developers to approve their team's deployments.

**Comment by JoeTice** [comment]
Bumped to Sprint 16

**Comment by CBonade** [comment]
This gating mechanism has been figured out and is ready to be implemented. However, as there are currently concerns around the permissions and our ability to adjust them we are going to hold on merging it until we see what GitHub support comes back to us with. Closing this out as the principal implementation is done and figured out and may just need slight tweaks to follow in another ticket.
