### ISSUE TITLE
Remove unnecessary aria attributes from appts lists

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#93285]
## Description

The appointments lists have some overzealous aria labelling that can be removed to clarify for screenreader users. See CC ticket #55864 and #55851 for full context on these changes. These changes are for both the upcoming and past appts lists.

1. For the aria-label on a div in the first column of each appointment:

- Remove the `aria-label` attribute, and move its content into `<span class="sr-only">` tags inside the div it's currently attached to. (`aria-label` isn't a valid attribute for `div`s)
- Remove the text ` appointment on` from the content. The span should just contain the date information, i.e.: `<span class="sr-only">Friday, September 20, 9:40 a.m. Pacific Time</span>`

<img width="1797" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy92Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fb46a9cd3a573cfe5fba58e5caddb1dca7e7c3c/Screenshot_2024-09-20_at_8_43_37%E2%80%AFAM.png" alt="Screenshot_2024-09-20_at_8_43_37 AM.png" />

---

2. Remove `<span class="sr-only">Appointments in</span>` from the H2 month/year headings:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEh2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cc60be59d917af9db52da01377524a9ccd8c2eb/Screenshot%202024-09-20%20at%208.47.52%E2%80%AFAM.png" alt="Screenshot 2024-09-20 at 8.47.52 AM.png" />

---

3. Remove the `aria-labelledby` attribute from the ul that follows the heading. The context of the heading is enough to create the association. (Also remove the ID on the heading if this isn't being used for other functionality).

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFB2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12e5c7c5a59b46327fa43131938512e30f1a5d8b/Screenshot%202024-09-20%20at%208.58.59%E2%80%AFAM.png" alt="Screenshot 2024-09-20 at 8.58.59 AM.png" />

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
- N/A

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
@ldelacosta this is to address feedback in an old collab cycle ticket - #55864

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/93285?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
UX team will validate in staging.

**Comment by outerpress** [comment]
Looks and sounds good @ryanshaw @ldelacosta !

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
