### ISSUE TITLE
CT-EYB: Mobile “Calculate benefits” button and EYB benefits panel is too close

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9328]
The Calculate benefits button is too close to the estimate your benefits panel in mobile view.
https://www.sketch.com/s/0ee1f7c7-6692-4ef8-912d-0a929b5e5154/a/vGA4en#Inspector
##
Currently in staging
![Screen Shot 2020-05-20 at 8.41.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f56dcded-8bfb-441b-a3a0-9f65797a7227) 
##
What it should be in sketch
![Screen Shot 2020-05-19 at 3.37.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cb406ccd-14f0-43e5-8914-ab9062f62010)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12738

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif copy](https://user-images.githubusercontent.com/48804582/82591993-2a809880-9b6e-11ea-927b-51bb8ce0e97d.gif)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I reviewed and this checks out.

**Comment by sonntag-adam** [comment]
Closing bug
