### ISSUE TITLE
CT-EYB: "Calculate benefits" button too narrow on mobile

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9329]
[Sketch](https://www.sketch.com/s/0ee1f7c7-6692-4ef8-912d-0a929b5e5154)

For mobile view (screens under 481px wide) the "Calculate benefits" button should span the full width of the EYB section. Currently, it is the same size as desktop. This is present on all non-vettec profile pages on Staging.

### Current
![Screen Shot 2020-05-20 at 8.58.36 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/10fb877b-4b56-4b76-8e99-5fcda3bcbed6)

### Expected
![Screen Shot 2020-05-20 at 8.58.18 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d181af49-fd12-4514-abfc-eb511de7db30)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12738

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif copy](https://user-images.githubusercontent.com/48804582/82591942-19378c00-9b6e-11ea-94b0-1d152d42ee27.gif)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam, @JenLJ and I reviewed and this checks out.

**Comment by sonntag-adam** [comment]
Closing bug
