### ISSUE TITLE
Design intent Collaboration Covid Screening Tool

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#9330]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [X] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [X] VSP <> **requesting team** design intent collaboration meeting completed
- [X] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [x] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/product-brief.md
- Sketches: n/a
- Lo-fi mockups: https://invis.io/CPXBETTE4UT#/417923097_FullScreenOption
- Content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/content-messaging.md
- Actual code (VIEW ON MOBILE): http://www.va.gov/covid19screen
- First round guerilla testing synthesis (prototype): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/guerilla-testing-synthesis.md
- Second round usability testing synthesis (actual code): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/COVID-screener/synthesis-study-1.md

## Meeting attendees from **requesting team**
- Designer(s) (required): @artsymartha68 
- Product Manager (optional): @batemapf 
- DEPO design lead (required as applicable): @JeffBarnesUSDS 

## Scheduling
Preferred dates or times: Tues May 26 or after

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs): This is a new pattern in that it's optimized for mobile, on-the-go usage
- A list of existing applications or pages with similar execution or patterns with URLs in staging: I could find none

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility
- Note that @jenstrickland has been looped in already
- Content designer is @DanielleThierryUSDSVA

**Comment by CrystabelReiter** [comment]
Scheduled May 26, 11:30 am EST. Thank you!

**Comment by artsymartha68** [comment]
Notes from @mchelen so we have it for the record:

steps:

1. started by following https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started. got a little stuck on the content build process, glad to see those docs have been updated, for our eventual use case we didn't really need to be running build at all which may still be unclear
2. looked at https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/ and couldn't determine if this was appropriate, our form might be "multi-page" and have optional fields, but does not need to read or write data anywhere.
3. someone pointed out https://design.va.gov/patterns/wizards and we said ah perfect, that's exactly what we want! dug around to find codebases, looked at first 2 examples and got completely overwhelmed with complex applications
4. looked at disability claim example https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/disability-benefits/wizard which seemed the simplest
5. disability claim seemed to be using https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/wizard/index.js but couldn't understand how
6. since disability claim seemed to be a widget (no manifest.json in https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/disability-benefits/wizard) tried to develop a widget locally
7. followed https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-widget but was unsure where to put code snippets, or how to develop/test widget without having to deal with content repos
8. based on VFS suggestion (thank you!) looked into application approach instead
9. followed https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-application and used yeoman generator
10. huge success, got barebone "hello world" application running locally at http://localhost:3001/covid19screener/ !
11. able to proceed with development :tada:
12. used https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/collapsiblepanel/ for initial version
13. determined component did not match our design needs, cribbed some of the scroll functions
14. used https://design.va.gov/components/ for buttons and https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/ for alertbox


summary:

1. vets-website is very easy to get up and running locally
2. all additional repos/steps may be unnecessary depending on use case
3. there is overlap and discrepencies between https://github.com/department-of-veterans-affairs/vets-website and https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started
4. content & BE docs were not tested
5. wizard pattern is difficult to implement without simpler example or more documentation
6. application generator is lovely
7. react-jsonschema-form is cool! would it work for our use case? should we use it without the rest of VAFS? 
8. would our multi-page app be useful to contribute as a formation component? did we miss one that already exists?
9. can/should we find a 3rd party lib to handle this use case such as https://formio.github.io/formio.js/ ?

**Comment by rtwell** [comment]
my 2¢:

1. looks like the line-height of the bullet points is more generous than the questions. I would make them the same.

2. Because these folks have to use this every day, I'm wondering if we could drop an affordance to help ppl easily navigate back to this page (maybe near the final section "OK to proceed"?). Something like "You'll need to fill out this screener every day you need to access the VAMC. Bookmark this page to quickly take the screener" (awful language, i know). maybe it could/should be at both the top+the bottom? In the same vein, I want to say I saw a message that pops up if a user stays on this page and the next day, opens their browser to this page and we say something like "start the screener" or something—which is also a great affordance to make this as seamless as possible!

**Comment by artsymartha68** [comment]
I think we're safe to close out this issue. We have generated lots of smaller issues to cover all the things we'd like to fix. Thank you all for the lively discussion. Next time I'll do this meeting at the right point in the design cycle.
