### ISSUE TITLE
Adding Sarah Huber to DSVA Slack

### ISSUE THREAD

**Issue by seheart** [department-of-veterans-affairs/va.gov-team#93317]
# Description

Please add Sarah Huber as a full member.

Sarah is a Senior Product Manager for Ad Hoc on the VA Flagship mobile app. Email is [sarah.huber3@va.gov](mailto:sarah.huber3@va,gov).

**Comment by LEHigley** [comment]
do they have a VA email address?

**Comment by seheart** [comment]
Not yet. Still going through the onboarding.

**Comment by seheart** [comment]
@LEHigley any updates? We really need to get this team member into DSVA slack. Thanks.

**Comment by rtwell** [comment]
@LEHigley is a VA email addy required? or can we use the Ad Hoc one posted above? I feel like i heard VA IT would require a VA email address.

**Comment by DonMcCaugheyUSDS** [comment]
> [@LEHigley](https://github.com/LEHigley) is a VA email addy required? or can we use the Ad Hoc one posted above? I feel like i heard VA IT would require a VA email address.

Also @KevinMHoffmanUSDS @lkoenigsberg do either of you know?

**Comment by goldenmeanie** [comment]
Manually invited as full member with sarah.huber3@va.gov address

**Comment by DonMcCaugheyUSDS** [comment]
> Manually invited as full member with [sarah.huber3@va.gov](mailto:sarah.huber3@va.gov) address

Thank you @goldenmeanie !
