### ISSUE TITLE
Google Search Console 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9331]
## Implementation Info 

- [x] Generate or select [email account to be used for admin purposes](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/search_admin.md)
- [x] Store access info for that email in an internally accessible place
- [x] Verification of www.va.gov
- [x] Enable Google Search Console within GA directly
- [x] Verify proper users have appropriate access - add users as necessary
- [x] Transfer of ownership to new depo.search@gmail.com email

**Comment by jonwehausen** [comment]
### Update

Friday May 29 @bsmartin-ep and I were able to setup Google Search Console and verify immediately thru GTM. The admin panel for search console can be [accessed here](https://search.google.com/search-console). 🎉 

Next steps will be to convert ownership from Brian and myself to the username [setup here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/search_admin.md).

**Comment by jonwehausen** [comment]
In the process of attempting to transfer ownership to `depo.searchadmin@gmail.com` Google let us know this account has not been setup as a Google Account. 
![image](https://user-images.githubusercontent.com/48527022/83754613-3bcfa780-a63a-11ea-92e8-87ad49b3c935.png)

The next step would be to have a DEPO admin [go thru this process](https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp) to create a Google account with that email. We're happy to perform this process with approval. cc: @johnhashva @KevinMHoffmanUSDS @joanneesteban 

From here, we should be able to get this account added as a verified owner.

**Comment by johnhashva** [comment]
@jonwehausen here is my approval (if needed) -- TY.

**Comment by jonwehausen** [comment]
### Update

**Per slack conversation**: https://dsva.slack.com/archives/C011K1VSTC3/p1592851278005000

### Google Search Console
###
Within Google Search Console, the depo.search@gmail.com account has been added as a verified owner. 
![image](https://user-images.githubusercontent.com/48527022/85328088-1813ba80-b49e-11ea-8ccb-318155e070af.png)

### Bing Webmaster Tools
Within Bing Webmaster Tools, the account has been added as an Administrator: 
![image](https://user-images.githubusercontent.com/48527022/85328613-067ee280-b49f-11ea-9194-7830184f5c37.png)

**Comment by jonwehausen** [comment]
### Added Google Search Console to GA
### Notes
1) We have successfully turned on the Google Search Console <> GA connection
2) It can take up to 2 days for data to populate
3) @bmcgrady-ep if we could add the verbiage around disparity between GA and Search console to our [FAQ's ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0b421b349c86951fc92bc0276c93343cba6fea2f/platform/analytics/google-analytics/google-analytics-frequently-asked-questions.md#when-should-i-use-pageviews-vs-sessions-vs-users)

![image](https://user-images.githubusercontent.com/48527022/85331076-742d0d80-b4a3-11ea-8723-7e961da8eb59.png)
