### ISSUE TITLE
Bing Webmaster Tools

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9332]
## Implementation Info 

- [x] Generate or select email account to be used for admin purposes
- [x] Store access info for that email in an internally accessible place
- [x] Verify www.va.gov domain
- [ ] Verify proper indexing and collection
- [ ] [User signup](https://www.bing.com/toolbox/webmaster) for those needing access - necessary to get into Bing Webmaster Tools
- [ ] Verify proper users have appropriate access - add users as necessary
- [ ] Transfer ownership to search admin account [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/search_admin.md)

**Comment by bsmartin-ep** [comment]
I was able to verify ownership in Bing Webmaster tools, however I was given "Read/Write" access and not "Admin".  So I am unable to add any other users or modify roles.

Next step would be @jonwehausen giving it a shot to see if his GTM permissions result in admin rights in Bing.

**Comment by jonwehausen** [comment]
### Note for all 

There are two versions of the Bing Webmaster Tools console -- [existing](https://www.bing.com/webmaster/home/dashboard?url=https://www.va.gov/) & [new beta](https://www.bing.com/webmasters/searchperf?siteUrl=https://www.va.gov/)

**Comment by bsmartin-ep** [comment]
@KevinMHoffmanUSDS / @johnhashva -

I'm trying to add our new Search Engine development account to Bing as an admin, but it doesn't look to be activated yet...

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/01fe02fb-ee12-4e6f-b596-0dad83ebb1b4)

Should this be working for me?

Thanks!

**Comment by bsmartin-ep** [comment]
@johnhashva -

The search admin account has been added as an admin to Bing Webmaster Tools.

https://www.bing.com/webmaster/configure/user/management?url=https%3A%2F%2Fwww.va.gov%2F

Do you need anything else from us or should I close this ticket out?

Thanks!

**Comment by johnhashva** [comment]
Not for Bing (so let's close this one out) -- but for Google Search Console, looks like there could be benefit to linking GSC to GA --> https://www.bounteous.com/insights/2018/03/06/how-connect-google-analytics-and-search-console/.    If you agree, I can create a separate ticket for that if needed.

**Comment by jonwehausen** [comment]
@johnhashva Yes sir! Check out latest update in [9331](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9331). We have just enabled and should start seeing data within the next two days. 

We are also going to be adding verbiage to our FAQ around the disparity what you will see in GSC directly and what you will see in GA.
