### ISSUE TITLE
AWS access for Bryan Thompson

### ISSUE THREAD

**Issue by SnowboardTechie** [department-of-veterans-affairs/va.gov-team#93328]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Bryan Thompson

### Your Email

bryan.thompson@agile6.com

### Team, Role, and Company of the target individual

Sitewide Facilities, Senior FS Engineer, Agile 6

### Product Manager (PM) name and email

Jill Adams (DM) , Michael Skinner (PM)

### Product Owner (PO) name and email

Michelle Middaugh (suzanne.middaugh@va.gov)

### Desired AWS Access

SSM Access to lower environment instances

### Access Expiration

1747810800 (5/21/25 - midnight UTC)

### E-QIP Transmittal Confirmation

<img width="1064" alt="Screenshot 2024-09-20 at 12 14 45 PM" src="https://github.com/user-attachments/assets/99b5a480-e26d-40d1-bdfe-526f470c1711">

### Additional Notes

Need tunnel access to lower environment forward proxy (similar to: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-api-tunnel-setup.md) for local development of vets-api for accessing PPMS data (only accessible through firewall not through SOCKS).

I will also need AWS credentials.

My COR is Keith Riley

My VA email is [bryan.thompson3@va.gov](mailto:bryan.thompson3@va.gov) if that's preferred over the agile6.com one.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by barbarello** [comment]
user in Atlas

**Comment by barbarello** [comment]
@SnowboardTechie  do you have a team mate who has the kind of access you are requesting ?

**Comment by barbarello** [comment]
@SnowboardTechie aws access has been granted
