### ISSUE TITLE
Implement Search Optimization Tools for VA.gov

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9333]
## User Story 

As a search analyst and/or information architect, I need to utilize a search optimization tool for VA.gov, so that I can understand how to improve search rankings of VA.gov based on user behavior.

## Description

SEO has not been a primary focus during WBC efforts. Information architects and content strategists have tried to optimize where possible to the best of our ability and knowledge, but we've had no data or tool to see how we're doing or where the trouble spots are. As we add even more content and bring legacy sites over to VA.gov, this will continue to be a struggle. 

For example, in many cases anecdotally, VA.gov ranks lower than other .gov sites (such as military.com or legacy VA.gov subdomains), which is directly at odds with our goal of making VA.gov the single source of truth for Veterans who with to apply, track, manage benefits.

Search optimization tools are also a great planning tool from an IA taxonomy perspective — they help us understand how our users are looking for and talking about certain topics. This can particularly come into play with subdomains — we can better understand and explain to stakeholders why subdomains hurt us (in some cases) and when a subdomain might actually make sense. 

## Acceptance Criteria
- [ ] Users (information architects, VSP Insights & Analytics, VSA Public Websites, DEPO can access accurate Google Search Console information
- [ ] Users can access accurate Bing Webmaster Tools information

**Comment by meganhkelley** [comment]
Megan, Mikki, John, Brian met 5/19

**Comment by johnhashva** [comment]
Megan, I fixed one type -- Military.com instead of Military.gov -- everything else looks spot on.   Worth noting: @KevinMHoffmanUSDS will set up the VA.gov accounts for us at [Google Search Console](https://search.google.com/search-console/welcome) and [Bing Web Developer](https://www.bing.com/toolbox/webmaster) with usernames he recommends.

**Comment by mnorthuis** [comment]
work done, closing epic.
