### ISSUE TITLE
[Content] Update content for can't show all appts expandable alert

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93387]
## Task Description

- Update content for can't show all appts expandable alert on Appt List Page template

## Notes and References

- Laura W. left a comment in Figma (CC VDSS) on Aug 13, 2024 about [cleaning up the content for the can't show all appts expandable alert that appears on the Appt List Page template](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4?node-id=3707-7920#910534167). 

## Acceptance Criteria
- [x] Wireframes are updated

## Deliverables
- [x] [Finalized wireframes](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2267-8113)

**Comment by benbrasso-agile6** [comment]
@outerpress which Epic should this one belong to?

**Comment by outerpress** [comment]
You got the right one :) This looks good. @ldelacosta could you work with @benbrasso-agile6 to set up the dev work for this?

**Comment by outerpress** [comment]
Dev ticket: #93409

**Comment by outerpress** [comment]
Dev work is done, closing
