### ISSUE TITLE
Update content for can't show all appts expandable alert

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93409]
## Description

Update content for can't show all appts expandable alert on Appt List Page template

### Design Assets

[Figma File](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2267-8113)

---
### Development Checklist

- [ ] Update content in the expandable caution alert for can't show all appts scenario. [Upcoming and Past appointments pages](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2267-8113&t=mCcS6awTjBsrhZ25-4).
- [ ] Update content in the expandable caution alert for can't show all appts scenario for [Pending page](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2267-8195&t=mCcS6awTjBsrhZ25-4). 

 ## Developer Reference
- [ ] [Swagger file]() (remove if not needed)
- [ ] [File path]() (remove if not needed)

## Definition of Done
- [ ] All task criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed, remove there is none)

**Comment by benbrasso-agile6** [comment]
@ldelacosta and @outerpress, just created this ticket. Let me know if anything needs to change.

**Comment by outerpress** [comment]
Assigned @ldelacosta for prioritization and added the needs-grooming label, other that that looks good 👍

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for validation.

**Comment by outerpress** [comment]
Looks good @JunTaoLuo ! I'll close out the ticket. 

FYI @Cieramaddox @zach-park I updated these alerts in the [feature reference](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2952-41529&t=SXvZCSmlna0XcXEm-4)
