### ISSUE TITLE
10-10CG Caregiver A11y Findings

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#9342]
## Violation ❗️(the feedback **must** be applied)

**Location/Page(s):** Review and submit 
- [x] Name input for signature boxes 

- [See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9173)

<img width="1325" alt="Violation" src="https://user-images.githubusercontent.com/58444931/82372697-0e4ff080-99e2-11ea-87c5-64872788b550.png">

## Violation ❗️(the feedback **must** be applied)

**Location/Page(s):** Health care coverage screen 

- [ ] Radio inputs that have the same name value must be part of a group, ensuring related <input type="radio"> elements have a group and that the group designation is consistent. Fieldset contains unrelated inputs.

-  [See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9174)

## Best practice ⚠️ (the feedback **should** be applied) 

**Location/Page(s):** Global <h5>Need help?</h5> 
- [x]  Heading levels should only increase by one, Ensures the order of headings is semantically correct 

- [See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8558) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8556) 

## Best practice ⚠️ (the feedback **should** be applied) 

**Location/Page(s):** Block headers (e.g. VA Medical Center, Health care coverage, Contact information, etc) 

- [x]  Heading levels should only increase by one. 

The "VA Medical Center" heading is currently h5, but are not preceded by an h3 or h4. This should be an h3. It is currently an h5 with h4 styling. Ensures the order of headings is semantically correct

- [See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9170)

## Best practice ⚠️ (the feedback **should** be applied) 

**Location/Page(s):** Confirmation screen 

- [x] Side note: There's a typo in the "(VA From 10-10CG)" which should be Form.
- [x] Heading levels should only increase by one

The "You’ve successfully submitted your application." heading is currently h3, but is not preceded by an h2. This should be an h2 with with h3 utility styling.

The "Application for the Program of Comprehensive Assistance for Family Caregivers (VA Form 10-10CG)" is currently an h4, but is not preceded by an h2. This should be an h3 or an h2 with h4 utility styling.

- [See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9273)

## Best practice ⚠️ (the feedback **should** be applied) 

**Location/Page(s):** Phone numbers 

- [x] By default, numbers may be read in a variety of ways by different screen readers. It may be challenging to understand the numbers. 

There is a new pattern for phone numbers on VA.gov, that adds an aria-label="8 0 0. 5 5 5. 1 2 3 4." attribute to the phone number link. This pattern should be added to all phone numbers throughout the application.

[See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9299)

## Best practice ⚠️ (the feedback **should** be applied) 

**Location/Page(s):**  Edit buttons 

- [x] On the review screen the "Edit" links should indicate what they will edit.

In the screenshots below, the "Edit" link for the contact information is coded to include the context in a screen reader only span. This pattern should be applied to the first button, and the suggestion is "Edit" veteran or service member personal information.

There is also a section header missing in the first accordion, and consider adding a heading, for example "Personal information", like the one for "Contact information."

The changes should be applied to each section, Veteran, Primary, and any Secondary Caregivers

[See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9303)

## Best practice ⚠️ (the feedback **should** be applied) 

**Location/Page(s):**  Confirmation screen 

- [x] On the final confirmation screen, the focus is on the h1, but had been on the h2 throughout the flow. 

On the confirmation screen the focus should be on the h2 "You've successfully submitted your application." This is of consequence for the screen reader experience.

[See Jennifer Strickland's ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9305)

**Comment by LinnJS** [comment]
Location/Page(s): Health care coverage screen concerning the radio buttons will be addressed in a later ticket due to the root issue residing in platform code.

**Comment by LinnJS** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12791
