### ISSUE TITLE
Vets-api terminal access for Jacob Penner

### ISSUE THREAD

**Issue by pennja** [department-of-veterans-affairs/va.gov-team#93423]
### Your Name

Jacob Penner

### Your GitHub handle (terminal access is managed through GitHub)

@pennja

### Your dsvagovcloud AWS user name (if applicable)

Jacob.Penner

### Team, Role, and Company of the target individual

Veteran Facing Forms, Software Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Tricia Baker tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee matthew.dingee@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Laurene "Reney" Cook

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need this access because my team is involved in OCTO's Zero Silent Failures initiative. In order to fulfill the requirements of this initiative, my team needs the ability to remediate form submissions in Production. In order to do this, I will be running Rake tasks in Production to kick off an automated service.

![Image](https://github.com/user-attachments/assets/337d7658-f7a6-483d-a924-af127dfa1150)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by pennja** [comment]
cc: @megansiddle @humancompanion-usds

**Comment by AnthonyWFlowers** [comment]
@pennja  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by pennja** [comment]
@AnthonyWFlowers It would appear that I'm unable to access https://argocd.vfs.va.gov/applications at all at this time. I'm currently connected to SOCKS as well. Is this to be expected at this time?

**Comment by AnthonyWFlowers** [comment]
Greetings @pennja I was able to access this page behind SOCKS, what error were you receiving when attempting to navigate to this page?

**Comment by pennja** [comment]
> Greetings [@pennja](https://github.com/pennja) I was able to access this page behind SOCKS, what error were you receiving when attempting to navigate to this page?

Hey there @AnthonyWFlowers , I'm currently greeted with the following browser error page:

```
This site can’t be reached
Check if there is a typo in argocd.vfs.va.gov.
DNS_PROBE_FINISHED_NXDOMAIN
```

![Image](https://github.com/user-attachments/assets/fe7e7a7d-f3df-4276-9b02-d4e4c1c00eca)

**Comment by AnthonyWFlowers** [comment]
Greetings @pennja I tested the link again myself with success. When you check your SOCKS connection it shows you as connected? Have you tried multiple browsers and still get the same results?

**Comment by AnthonyWFlowers** [comment]
Notes for ticket: Confirmed user was in appropriate Github teams for access.

**Comment by pennja** [comment]
Hey @AnthonyWFlowers , I've tried on Chrome, Safari, and Firefox and I'm still getting the same/similar error.

My SOCKS connection appears to be working properly:

![Image](https://github.com/user-attachments/assets/2b41cfa9-77ad-4f4b-8cc3-98610b2efe58)

**Comment by pennja** [comment]
@AnthonyWFlowers I'm willing to get on a call if that would help expedite fixing the issue!

**Comment by AnthonyWFlowers** [comment]
Sorry @pennja I have back to back meetings for the next two hours. We can meet up after 4pm ET today or I can make time for you tomorrow as well.  To reiterate no issues connecting to Jenkins, Sentry, Review Instances, Grafana, only when accessing ArgoCD?

**Comment by pennja** [comment]
@AnthonyWFlowers Actually, it looks like I can't access those either. This may be a SOCKS issue. I'll dig into it and possibly re-install.

**Comment by pennja** [comment]
I was able to troubleshoot and solve my connection issues. I'm able to access ArgoCD now. Thanks for all your support @AnthonyWFlowers !

**Comment by AnthonyWFlowers** [comment]
Greetings @pennja great news! Now we are just waiting on OCTODE approval for prod access so stay tuned!

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by AnthonyWFlowers** [comment]
Greetings @pennja  You've been granted access to Production, with access to Production limited to 6 months, expiring 03/27/25. 

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Reminder link [here](https://dsva.slack.com/archives/C06CY71PCAX/p1727446405283469)
