### ISSUE TITLE
Add Tagalog Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#93422]
## Tasks
- Add the following Tagalog translations
    [NewTagalogTranslations.json](https://github.com/user-attachments/files/17102265/NewTagalogTranslations.json)
- Generate zip for error screens & give to Lori

**Comment by brianseek** [comment]
bring-insurance-cards-list-medications-other & check-current-mileage-rates are no longer in the application

**Comment by brianseek** [comment]
@loripusey these translations seemed to extend beyond just error pages, so I made a zip of all pages.[tagalog.zip](https://github.com/user-attachments/files/17297667/tagalog.zip)

**Comment by loripusey** [comment]
Thanks, I will create the documentation for the State Department. If there are any changes/corrections, I'll put them in a new ticket. Closing this one.
