### ISSUE TITLE
[Ongoing Service] Maintain and evolve the IA of VA.gov

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9343]
### User Story

As a Veteran or other VA.gov user, I need to be able to find tools that help me complete key tasks on VA.gov, so that I can apply for/manage/track my benefits etc. 

As a VFS team, I need to know the ideal IA of the content/tool I am building within the VA.gov ecosystem, so that I can best meet the needs of Veterans and other users.

### Problem Statement

As VA.gov evolves over time, and as the range of VFSs on the site expand through continued WBC efforts, how might we continuously re-evaluate and modify the IA of VA.gov to best support the needs of Veterans and other users? 

## VSP Objective (Q1 & Q2 2020)

O2: Customers use qualitative and quantitative data to build and iterate on VFSs.

## Measuring Success (KRs/KPIs)

- IA health of VA.gov
- [VSP KR] Reduction in time it takes to perform a VSP review across 5/10 practice areas

## Details and Notes

This ongoing service is co-owned by information architects on DEPO and VSP. VSP supports the ongoing evolution of VA.gov information architecture via maintenance and documentation.

### Assumptions and Hypotheses

- We assume that additional VFSs will continue to be migrated to VA.gov from various subdomains.
- We assume that VA.gov should be the single source of truth for Veterans looking to apply/manage/track benefits.
- 

## Areas for Discovery

**Comment by mnorthuis** [comment]
Closing this epic.  All IA work that is direct design work for va.gov (not in support of VFS or platform initiatives) such as IA enhancements, bug fixes, IA/design debt, etc., will be tracked in #2231.

**Comment by mnorthuis** [comment]
Reopening epic and moving issues back. Will utilize this issue over 2231.

**Comment by mnorthuis** [comment]
Closing old epic used for trackingon VSP
