### ISSUE TITLE
Create YAML Version of Onboarding Template

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#93442]
## Description 
_Please include a brief description of the purpose of this ticket._

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by GWright321** [comment]
Draft template [here](https://github.com/GWright321/Test/issues/new?assignees=&labels=new-vfs-team-member%2C+platform-orientation&projects=&template=Onboarding.yml&title=Onboarding+of+%5Bindividual%5D)
