### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#93455]
### Name

Todd Rizzolo

### Email

todd.rizzolo@adhocteam.us

### Role

FE Engineer

### Team

Pension & Burials

### Product Manager (PM) name

Sarah Shields

**Comment by naomimarcussen** [comment]
Hi! I just sent an invite to todd.rizzolo@adhocteam.us.

**Comment by ToddWebDev** [comment]
Received and accepted. Thank you.
