### ISSUE TITLE
[Design] My VA Forms Status: Add form 20-10206 to accordion copy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93457]
## Background
Form 20-10206 was added to the MVP so we need to add it to our figma files and documentation in the accordion.

## Tasks
- [x] Add `Request personal records (VA Form 20-10206)` to copy of info accordion in Figma 
- [x] Add `Request personal records (VA Form 20-10206)` to copy of info accordion in FE documentation

## Acceptance Criteria
- `Request personal records (VA Form 20-10206)` is added to info accordion documentation and designs

**Comment by mattmarino-adhoc** [comment]
Completed
