### ISSUE TITLE
Upload Employment-History PDF and generate mapping

### ISSUE THREAD

**Issue by ryguyk** [department-of-veterans-affairs/va.gov-team#93460]
Objective:
Take PDF put it into repo and generate a mapping from it.  Starting with Employment History but will apply to all forms.

- there is script to run to do 

AC:

- [x] PDF is added to vets website repo
- [x] utility is run against the PDF
- [x] Mapping file is generated

**Comment by derekhouck** [comment]
See Ryan's findings here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/89650#issuecomment-2361262052

**Comment by derekhouck** [comment]
In order to complete this task, I will need the PDF of the 21-4140 form.

**Comment by derekhouck** [comment]
See https://github.com/department-of-veterans-affairs/vets-api/pull/15984 for an example PR of what needs to be added to the repo during this step.

**Comment by derekhouck** [comment]
I might be blocked by #90576 as I need a fixture of submission data from 21-4140.
