### ISSUE TITLE
Add alternate global route for vaos module

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#93478]
The current vets-api vaos module sends all requests to a single vaos-service endpoint.  In support of potential future testing efforts, add an optional feature flag (defaulted off) that will redirect the VAOS requests to an alternate URL.

**Comment by devin-mccurdy** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/18753
- https://github.com/department-of-veterans-affairs/vets-api/pull/18755
