### ISSUE TITLE
Delete 10-10CG pdf forms & folder in GH and implement redirect

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9348]
# User story

As the caregiver of a Veteran, I need access to the latest form to apply for the Program of Comprehensive Assistance for Family Caregivers.

# Details

There is a new pdf version of the 10-10CG. It was uploaded with a new title, which caused a change to the evergreen URL. In addition, we appear to have been also hosting a version of the form in GitHub. 

**What's needed from engineers:**

- [ ] Delete GH files folder here: https://github.com/department-of-veterans-affairs/vagov-content/tree/master/assets/health-care/forms
- [ ] Implement a server-side redirect to https://www.va.gov/vaforms/medical/pdf/10-10CG.pdf

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ncksllvn. This is a follow-up issue for work associated with our slack conversation around this form. Please just let me know any questions, concerns, etc. Here's the related [content issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9349). Thanks!

FYSA @stephorkandatx

**Comment by ncksllvn** [comment]
These redirects are live!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @ncksllvn!
