### ISSUE TITLE
[QA] 10-10EZR Zero Silent Failure: Test Failure Email

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#93501]
As a Veteran, I would like to know when my EZR application has failed and know that the VA will reach out to me so that I don't have to worry

- [x] Coming from VA Notify
- [x] Just did it on EZ, duplicate that
- [x] Write test cases/use EZ test cases
- [x] **Success: We have a way to test failure email and we test it.**

**Comment by allanto-ah** [comment]
Testing in staging have been completed. Notes are in this ticket - [92911](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92911)
