### ISSUE TITLE
[Duplicate] Redirect Request: Legacy Form Landing Page for NOD

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#9350]
### Description
As a user looking for form 21-0958, I need to understand the form is no longer in use but that I can still manage my legacy appeal or use the new decision review process. We need to redirect the current url: 
https://www.va.gov/vaforms/form_detail.asp?FormNo=21-0958
to #1 in process map on legacy appeals page. Screenshot attached. 

![Screen Shot 2020-05-20 at 12.00.44 PM.png](https://images.zenhubusercontent.com/5d41d21a6db71633490a2764/33dca5bd-d474-495c-9255-a58b7e0d3e80) 

### Requestor team info
Public Websites
Laura Walsh @lwalsh617 

### Implementation date
Date new URL(s) will be live: The legacy page with updated content is live now. 

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - page is live so as soon as reasonably possible 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  https://www.va.gov/vaforms/form_detail.asp?FormNo=21-0958 | 

Redirect Destination (new URL)  |  
<https://www.va.gov/decision-reviews/legacy-appeals/#a-legacy-appeal-follows-these->

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@lwalsh617 @stephorkandatx If you want the redirect to go to a specific place on the page, the anchor/ID tags are needed and the URL needs to specify the correct anchor.  

I don't see an ID on step 1 in the subway map.  There is an anchor tag on the heading of that section, the URL to take users there would be: https://www.va.gov/decision-reviews/legacy-appeals/#a-legacy-appeal-follows-these-

If you want to go to step 1, an anchor tag is needed.

**Comment by lwalsh617** [comment]
@mnorthuis - Drupal won't allow me to create an anchor anchor tag on Step 1, I don't think. Had Randi take a look, too. We're assuming that, like accordions, the subway map headers don't allow for anchor links. Because the NOD line is so close to the H2, I think we're fine having it on the h2. Do you agree?

**Comment by mnorthuis** [comment]
@lwalsh617 I think the H2 will work great.

**Comment by lwalsh617** [comment]
@MickinSahni @bethpotts -- I believe we need to notify VA stakeholders of this redirect.

**Comment by jenniferlee-dsva** [comment]
All - The original request for this redirect was made (by me) a few months ago, and I already communicated this redirect to Paul at that time. There is no 'new' comms that's needed. Also this is not a "legacy" or a "parity" redirect -- it is simply a 404 redirect for a form that's been deprecated and not being replaced, and therefore doesn't need to go through the process in place for "legacy" or "parity" redirect. 

fysa @bethpotts @mnorthuis @lwalsh617 

@bethpotts - If you have regular syncs with Sandy, Paul Shute, and Fred Sommers, this would be just a nice courtesy thing to remind them (that we already communicated this a few months ago, but are letting them know again because it took some time to implement).

**Comment by lwalsh617** [comment]
We discussed this on stand up this morning. Ticket [8396](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8396) was assigned to dev. I dropped a note on that ticket about the anchor tag so this should be redirected shortly.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva @lwalsh617 I'll let the stakeholders know. When will this be live? Also, why is the Anchor tag chopped off like this, without "steps" on the end?: a-legacy-appeal-follows-these-

**Comment by lwalsh617** [comment]
Beth, I pulled the anchor tag from the source code which didn’t include “steps.”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MickinSahni** [comment]
> All - The original request for this redirect was made (by me) a few months ago per #8396 , and I already communicated this redirect to Paul at that time.

Hey folks, this is a duplicate of #8396. Unless I hear different from folks by tomorrow afternoon-ish, i'll close this out

**Comment by lwalsh617** [comment]
Redirect completed. (See ticket 8396.) Closing this ticket.
