### ISSUE TITLE
Remove paragraph content below success alert

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93512]
## Description 

Addresses initiative change, i.e., Veterans can only file one claim per day per facility. 

## Tasks

- [ ] Remove content below the VADS success alert on the /complete page. (Link to [Figma file](https://www.figma.com/design/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-PCI?node-id=3432-3868&t=EPfDlWJOZG6MFiFh-4) that shows no content below the success alert.)

**Comment by brianseek** [comment]
@cgednalske / @zach-park / @benbrasso-agile6 This one is merged and ready to validate on stage, locally, or in the screenshot in the PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/32694

**Comment by zach-park** [comment]
Looks great. Thank you!

**Comment by brianseek** [comment]
Nice, thanks @zach-park. Closing
