### ISSUE TITLE
Analytics Implementation or QA Support for [Chatbot Platform Team - Skill Tracking Analytics]

### ISSUE THREAD

**Issue by alexperson-tw** [department-of-veterans-affairs/va.gov-team#93539]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Chatbot Platform Team

- **Poduct Name**

    - VA Chatbot
      
- **When is the launch date?**
    - ASAP

- **Provide the link(s) for Product/Page urls**
  
    - https://staging.va.gov/contact-us/virtual-agent/

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_

### **Skill entry events**
- **Desired change:** We would like to add an additional "topic" attribute to our existing skill entry tracking events:
  - api-name: "Chatbot Skill Entry - va_ratings_bot"
  - api-status: "successful"
  - event: "api_call"
  - topic: "va_ratings_bot"
![Image](https://github.com/user-attachments/assets/55bc84d2-318b-4978-8bc5-5d6f2f1fac47)

- **How to trigger a skill entry event:** Using our Ratings skill as an example, this event is generated whenever a user starts a chat, types "ratings", successfully completes the sign-in process with test user, triggering the first message from our Ratings bot (message captured in screenshot below):

<img width="582" alt="Screenshot 2024-09-24 at 2 05 05 PM" src="https://github.com/user-attachments/assets/1c9910cb-9035-4165-8a88-338b70cfa35b">

### **Link clicks**
- **Desired change:** We would like to add an additional "topic" attribute to our existing link click tracking events:
  - event: "chatbot-resource-link-click"
  - link: "https://staging.va.gov/disability/view-disability-rating/rating"
  - linkText: "View your VA disability ratings page (opens in new tab)"
  - topic: ""va_ratings_bot""
<img width="481" alt="Screenshot 2024-09-24 at 2 09 00 PM" src="https://github.com/user-attachments/assets/3590ac5d-ac14-4fcb-a6b6-8de5b55d45c7">

- **How to trigger link click tracking event:** Using the [View your VA disability ratings page](https://staging.va.gov/disability/view-disability-rating/rating) presented to the user as the second link as an example, the following event is generated whenever a user starts a chat, types "ratings", successfully completes the sign-in process with test user, and clicks the [View your VA disability ratings page (opens in new tab)](https://staging.va.gov/disability/view-disability-rating/rating) link from the second message in our Ratings skill (message captured in screenshot above):

    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_
    -Stored in chatbot folder in `va.gov-team-sensitive` repository

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for submitting this @alexperson-tw -- we'll review this, along with the other Chatbot requests we have in our backlog.

**Comment by lealmendozaalexander** [comment]
Changed the login credentials as the previous ones provided do not currently work. The folder path is teams/chatbot/ratings_staging_test_user.md

**Comment by jestutt** [comment]
@alexperson-tw @lealmendozaalexander Everything is looking great on staging. It's ready for production. 
 
Skill entry events
![Image](https://github.com/user-attachments/assets/1c80729b-7da9-4a71-a0af-20067ab54734)
![Image](https://github.com/user-attachments/assets/a95e3d0b-67a5-44ea-b5d2-7822369b4047)
![Image](https://github.com/user-attachments/assets/88df8400-f5e7-4074-8722-9648e978fb6c)

Resource link click events
![Image](https://github.com/user-attachments/assets/8ebb9b76-0f31-45f3-bd1b-e0160d12c1b1)
![Image](https://github.com/user-attachments/assets/811a8787-19eb-429b-b9ab-2165ea3cda35)

Button click events
![Image](https://github.com/user-attachments/assets/971956ce-0f25-4887-8c20-496015c542ad)
![Image](https://github.com/user-attachments/assets/e9d8897e-4d61-466e-9348-d515f836bf08)
![Image](https://github.com/user-attachments/assets/10094ae5-0784-4aaf-b785-334f51ee7655)
![Image](https://github.com/user-attachments/assets/9fec72b2-7e13-43d0-9ba1-14e965b9c78e)


Staging Explore report -- [Chatbot Events by Skill](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/OgYGv9BxTYy2qmM46K2q3Q)

- Tab 0 = Chatbot Skills
- Tab 1 = Chatbot DataLayer Event Names (rows) by Chatbot Skill (columns)  
- Tab 2 = Daily Chatbot event counts by Chatbot Skill
- Tab 3 = Chatbot click events Click text (rows) by Chatbot Skill (columns)
-- Blank Click text is the microphone enable event 
- Tab 4 = Daily API Call event counts by chatbot entry API Names
- Tab 5 = Chatbot entry events API Names  (rows) by Chatbot Skill (columns)
--  This was added to GTM during today's testing so you won't see it in GA until tomorrow (24 Oct)
- Tab 6 = VHA Health Assistant skill events
- Tab 7 = Claims skill events
- Tab 8 = Ratings skill events

Happy to review the report with you in an upcoming Office Hours.
