### ISSUE TITLE
Update sub-directories and page names

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93536]
## Description 

After reviewing documentation for the Appts app and VADS content guidelines for URLs, we need to use the sub-directories and page names documented in Figma. 

## Tasks

- [ ] Update sub-directories and page names that are documented in [Figma](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2145-37798&t=tcGErNs27ZHULCEu-4).

**Comment by benbrasso-agile6** [comment]
@brianseek this ticket a dupe and/or already getting worked on? Should we close? 

[Updated page names in Figma](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4745-7445&t=w2Jb9WPY9dzYnWIP-4)

**Comment by brianseek** [comment]
Yeah we can close this, I have this one that can cover it:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/94817
