### ISSUE TITLE
[CAIA A11y Research]: Debt Resolution, VHA Payment History

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#93530]
> [!NOTE]
> **High-Level Overview**: Debt Resolution 
> - **Research Timeframe**: **Pilot**: 09/25-27;  **Sessions**: 09/30-10/11
> - **Pilot Session(s)**: 09/26
> - **Assistive Tech Users**: `2` AT Users
> - **Artifacts Available**:  [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/payment-history/research/VHA-usability-study-9-2024/research-plan.md) & [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/payment-history/research/VHA-usability-study-9-2024/conversation-guide.md)
> - **Testing Environment & Schedule:** [CodePen](https://codepen.io/team/Debt-Team/live/yLddmpm)
> - **Assistive Tech Being Used**: `Screen Readers` 
> - **CAIA Internal Doc:** `Created` [Internal Notes: CAIA (Google Doc)](https://docs.google.com/document/d/1Wd37qsT-ByIObSlISkBEseKs_-R_o3rknuxApTACSfw/edit?usp=sharing)
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- @mutiaadhocteam 
- @coforma-jamie 
- @sara-amanda 

</details>

## About the Team

- Team name: Debt Resolution
- OCTO-DE product owner: Denise Coveyduc
- Product manager: Tom Davis
- Designer: Megan Gayle, Joseph Lee
- Researcher: Charlotte Cesana 
- FE engineer: Andrew Rodiek
- Product/team Slack channel: #debt-resolution

<details><summary>Toggle to view more intake research ticket information</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### Calendar checking

- [x] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [ ] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [x] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

### Timeframe

<details><summary>Toggle to view research timing information.</summary>

1. **Pilot Session Mobile**: Sept. 26 
2. ~**Pilot Session Desktop**: Sept. 30 - Oct. 11, 2024~

> Pilot: 09/25-09/27  Research Sessions: 09/30-10/11

### Length of sessions

- **Session length:**
    - **Session length:** 60 minutes
    - **Buffer time between sessions:** 1 hour
    - **Maximum Sessions per day:** 2

</details>

###  Testing Schedule

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

<details><summary>Toggle to view time-related items</summary>

#### Enter Testing Information
- **Dates**: Sept. 30 - Oct. 11, 2024
- **Times**:  `TBD`
- **Planning to Recruit `2` Veterans for**:
     - minimum of `2` sessions with screen reader users
     - minimum of `#` sessions with alternative navigation users
     - minimum of `#` session with a screen magnification user

#### Source of Truth
[Testing Schedule as source of truth](https://docs.google.com/spreadsheets/d/16eH4A-lHK7o2HlrryarhtfOe8hbsamW-CDQy6QZEtfQ/edit?gid=0#gid=0)  **_also see table in this ticket_**

Please use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available
------------------|------------------|--------------|--------------|--------------|--------------|--------------
✈ **Pilot** | 9/26/24, 4:30 p.m. - 5:30 p.m.  | VoiceOver | Mobile iOS | Safari | NA | @coforma-jamie and @mutiaadhocteam Ticket [#93594](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93594)
P15 | 10/10/2024, 2 p.m. - 3 p.m. | VoiceOver  | Mobile; iOS | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @mutiaadhocteam 
🛑 P16 | 10/11/2024, 11 a.m. - noon `participant cancelled` | Screen Reader "Vision" | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

## Supporting Artifacts

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/payment-history/initiative-brief.md)
- [User flows](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3107-43147&t=rdvTuXpPGEpXiX9l-1)
- [Prototype or mockups](https://codepen.io/team/Debt-Team/live/yLddmpm)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/payment-history/research/VHA-usability-study-9-2024/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/payment-history/research/VHA-usability-study-9-2024/conversation-guide.md)
- [Epics/issue that may be helpful](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/18859)

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket post OCTO/a11y refinement 9/24/2024
- [x] **OUTREACH**: [Initial outreach](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93530#issuecomment-2372466613) to team to schedule the pilot.
- [x] **PILOT CALENDAR HOLDS** - Set **pilot** holds on the A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago)
- [x] **PILOT SESSION MOBILE: SCHEDULE** Pilot session with team. `Conduct around 9/25- 9/27` `TBD`
- [x] ~**PILOT SESSION DESKTOP: SCHEDULE** n/a~
- [x] **PILOT SESSION MOBILE: CREATE TICKET** See `related tickets task list` in this ticket.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/93594
- [x] ~**PILOT SESSION DESKTOP: CREATE TICKET** n/a~
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available.
- [x] Receive [Source of Truth for Scheduling](https://docs.google.com/spreadsheets/d/16eH4A-lHK7o2HlrryarhtfOe8hbsamW-CDQy6QZEtfQ/edit?gid=0#gid=0) c/o Slack Channel 🔗 (Examples: Google Sheet, Slack Canvas, etc.)
- [x] **Requested device breakdown:** Desktop, Mobile and Tablet
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support.
- [x] **Updated Holds:** waiting on official invites (table to be updated in this ticket)
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean) Updated holds x/xx/2024
- [x] **Review research folder and assets**
- [x] **OFFICIAL RAW RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1Wd37qsT-ByIObSlISkBEseKs_-R_o3rknuxApTACSfw/edit?usp=sharing)
- [x] **Participate in research**  **Date Span:** Estimated Start: 9/30/2024 through 10/11/2024
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
- [x] **TEMPLATE SESSION NOTES**: Create [CAIA notes document](https://docs.google.com/document/d/1Wd37qsT-ByIObSlISkBEseKs_-R_o3rknuxApTACSfw/edit?usp=sharing) for a11ys to use during the sessions
```

```[tasklist]
### VFS TEAM Tasks
- [ ] Tag @Naomi Eke in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH) Link to VA [OCTO Slack Thread `PENDING`] (`xxx`)
- [ ] Your team's researchers and observers read through platform guidance on [research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users) and have also read and learned [how to be respectful of participants with disabilities](https://depo-platform-documentation.scrollhelp.site/research-design/disability-etiquette)
- [ ] Your team's researchers have read through the resources for researchers on the VA Platform's [Accessibility on Va.gov page.](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-on-va-gov#AccessibilityonVA.gov-ResourcesforResearchers)
- [ ] [Inclusive Recruitment Strategies](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md)
- [x] Consider [creating your prototype in CodePen](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen) for the most accurate results - `CodePen`
- [x] `Recommended Pilot` Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired
- [x] Request pilot sessions with CAIA a11ys
- [x] Schedule pilot session with CAIA a11ys (Mobile)
- [x] Schedule pilot session with CAIA a11ys (Desktop)
- [x] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section
- [x] **DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. `Estimated Start: 9/30/2024`
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in `Table` in the ticket above.
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (@sara-amanda)
- [ ] **Device Detail:** Desktop, Mobile and Tablet - Device breakdown needed for session prep
```

**Comment by sara-amanda** [comment]
## Scheduling Your Pilot Session

Good Evening, @mgleo @charlottecesana @josephrlee ! 

_CAIA a11ys would be happy to assist you with a pilot, as you prepare for your study. Since your participants will be half mobile and half desktop, which would you prefer we test with you, during the pilot? Assuming from the recruitment criteria you would like to test with a screen reader such as VoiceOver. Do you prefer VO or would you prefer NVDA or JAWS?_ 

### Pilot Prep
- **Preferred Device for Testing**: `TBD` 
- **Assistive Technology**: `TBD`
- **Best Day:** Req. Wed. 9/25 - Fri. 9/27 `TBD`
- **Best Time:** `TBD`
- **Testing Environment:** [CodePen](https://codepen.io/team/Debt-Team/live/yLddmpm)

#### Segment of Recruitment Criteria 

> - At least 1-2 assistive technology users (user with low vision, or user of hearing aide, user who uses **voice over**) (_Primary_)
> - At least 2 of 12 people who use a **screen reader** (_Demographic_)
> - 50% of participants should complete the session on a **smartphone**. (_Primary_)
> - 50% of participants should complete the session on a **desktop** computer. (_Primary_)

#### Pilot Resources

- [CAIA a11y Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago)
- [AT pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md)

cc: @mutiaadhocteam @coforma-jamie

**Comment by mgleo** [comment]
Hi @sara-amanda, we have one confirmed participant who uses a screen reader on October 10th at 2pm ET. They will be using VO on an iPhone. Perigean mentioned on Friday that they are recruiting for another screen reader user but there are currently no other screen reader users on the schedule.

cc @charlottecesana

**Comment by sara-amanda** [comment]
> Hi [@sara-amanda](https://github.com/sara-amanda), we have one confirmed participant who uses a screen reader on October 10th at 2pm ET. They will be using VO on an iPhone. Perigean mentioned on Friday that they are recruiting for another screen reader user but there are currently no other screen reader users on the schedule.
> 
> cc [@charlottecesana](https://github.com/charlottecesana)

Thanks for the update @mgleo ! I put a hold on our capacity calendar, if you would like to send me the invite, I can replace the hold and arrange for coverage of this session and potentially your second session. 👍

**Comment by sara-amanda** [comment]
## CAIA Research Support

**This ticket has been updated to reflect the following:** 

- [x] **P15**: 10/10 at 2 p.m.  - SR iPhone VO - @coforma-jamie 
    - [x] invite received and added to calendar
- [x] **P16**: 10/11 at 11 a.m. - Screen Reader TBD - @mutiaadhocteam  
    - [ ] invite pending - hold placed on CAIA a11y capacity calendar

**Comment by mgleo** [comment]
Hi @sara-amanda, @mutiaadhocteam, @coforma-jamie 
Friday's session is at 12pm ET. 

Here's the info we have so far:
P16 (VoiceOver) - Thursday, October 10 2PM ET
P15 (Vision [?]) - Friday Oct 11, 12PM ET 
Perigean is confirming the software that P15 is using.

**Comment by sara-amanda** [comment]
> Hi [@sara-amanda](https://github.com/sara-amanda), [@mutiaadhocteam](https://github.com/mutiaadhocteam), [@coforma-jamie](https://github.com/coforma-jamie) Friday's session is at 12pm ET.
> 
> Here's the info we have so far: P16 (VoiceOver) - Thursday, October 10 2PM ET P15 (Vision [?]) - Friday Oct 11, 12PM ET Perigean is confirming the software that P15 is using.

Thank you for the update @mgleo! I went ahead and updated the ticket and calendars accordingly. The comment above also reflects your updated time, and that @coforma-jamie and @mutiaadhocteam switched sessions. 😄
