### ISSUE TITLE
Coronavirus chatbot: Create customized CDC messages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9354]
# User story

As a Veteran, I need clear and concise guidance based on the results of my self-checker.

# Details

Technical limitations at chatbot launch required us to add VA-specific exit messaging in addition to CDC messaging for the self-checker tool. Now CDC is allowing us to customize their messaging. 

## Process steps to completion

- [x] Review latest CDC exit messaging (Danielle)
- [x] Customize exist messaging with VA-specific messages (in GH markup file - new branch) (Danielle)
- [x] Copy edit and check again CDC doc (Randi)
- [x] Send to Lauren to confirm whether JTF review is needed (Danielle)
- [x] If no approval needed, send to chatbot dev team for implementation (Danielle)
- [ ] Validate in staging (Danielle or Randi)
- [ ] Validate in production (Danielle or Randi)

## Files for reference

- Github file for customized messaging: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/customized-cdc-va-exit-messaging/content/cdc-wrapper-messages.md
- Latest CDC protocols messaging: https://github.com/CDCgov/covid19healthbot/blob/master/screening_protocols/latest/covid_19_protocol_content_and_messages.pdf

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Could you review  the github file for customized messaging: https://github.com/department-of-veterans-affairs/covid19-chatbot/blob/customized-cdc-va-exit-messaging/content/cdc-wrapper-messages.md for:

- General copy edit
- Anything that seems like it doesn't alignment with the relevant matching message in https://github.com/CDCgov/covid19healthbot/blob/master/screening_protocols/latest/covid_19_protocol_content_and_messages.pdf _(note: not all of the messages in the CDC pdf are reflected in the Github doc. this is intentional, so just compare the msgs that we also have).

FYSA @stephorkandatx

**Comment by RLHecht** [comment]
This was copyedited and compared to the CDC matching messages.

**Comment by DanielleThierryUSDSVA** [comment]
6.16: Lauren confirmed we do not need JTF approval. Handing off to dev team for implementation, and moving issue to validate. 

FYSA @stephorkandatx

**Comment by stephorkandatx** [comment]
This will likely hang out in Validate for a bit, as Coronavirus chatbot team wraps up a bit of work

**Comment by MickinSahni** [comment]
Carrying to sprint 25

**Comment by MickinSahni** [comment]
Closing out per convo in planning but will reopen/recreate as needed
