### ISSUE TITLE
FMP missing PEGA status incident

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#93546]
First slack alert: https://dsva.slack.com/archives/C06RQR7V9CM/p1727205402073439

Follow the playbook here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/team/ivc-forms-monitoring-playbook.md

We know the root cause, but document here.

Alerts are actively firing in Datadog, so please identify the steps needed to clear those errors and make sure PO (Premal) and PM (Bo) are aware before initiating any db updates or deletions.

**Comment by cloudmagic80** [comment]
Work on it with Steven Long
