### ISSUE TITLE
[PM, BE] My VA Forms Status: Prep endpoint monitoring playbook

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93559]
## Background
In preparation for forms status staging review we need to prepare an endpoint monitoring playbook as part of the zero silent failures initiative.

## Tasks
- [ ] ~Complete the draft template started [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/my-va-forms-status-endpoint-monitoring-playbook.md)~
- [x] PM to attach to collab cycle ticket

## Resources
- [Example from CST](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/claim-status-tool-error-monitor.md)

**Comment by DanielMiller-agile6** [comment]
As discussed in standup, we might be able to combine this ticket into the document Tom has been working on.  That doc outlines our strategy for "silent errors" across all of AuthExp, so this ticket might be unnecessary.  Currently, we have a shared doc for working on the report, but we can move that into github as needed upon completion.

**Comment by ajakabcin** [comment]
Great work @tpharrison and @DanielMiller-agile6! Full monitoring playbook linked [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/auth-experience/playbooks/monitoring.md) and I've attached to our collab cycle ticket. Thank you both!
