### ISSUE TITLE
Provide content strategy support for IA decisions

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9356]
## Description

As an IA/content team, we need to consider both IA and content strategy together when making IA decisions.

## Details

Kickoff meeting on 5.21.20 with Mikki to discuss upcoming IA needs. Not sure yet of additional work that may come from this.

**Comment by DanielleThierryUSDSVA** [comment]
Content strategy and IA are integrated now. Closing.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Is this ticket still needed? Thanks!

**Comment by FranECross** [comment]
Closing old ticket with the assumption that if this is needed, a new ticket or tickets will be created and prioritized.
