### ISSUE TITLE
[Spike] Determine if V1 VAOS APIs are still needed

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#93575]
## Background/Request

As part of the zero silent errors effort, I found that we have VAOS v1 APIs that are not being used by the FE webapp. I'm not sure what the history is regarding the v1 APIs and we might be able to remove these if no one is using them.

### Goal

- Determine if the VAOS v1 APIs are being used anywhere and if not, whether they can be removed

### Requirements to Consider

- In case we decide to remove v1 APS, do we need to deprecate them first before removing them outright?

## Tasks
- Answer the following questions:
  - Are the VAOS v1 APIs used by us or another team
  - If not, can we remove the v1 APIs
  - To test this, we can just remove the routes and monitor if any workflows break.

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/93575?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
Engineering tickets have been filed:

FE: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95620
BE: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95622

The PR to deprecate the v1 API routes has been merged so we'll keep an eye out for failures until the end of sprint and we can start on the full removal of the obsolete code as early as next sprint.

**Comment by ldelacosta** [comment]
Tickets have been created. No additional research is needed. Closing out the ticket. cc: @simiadebowale
