### ISSUE TITLE
QA updates: Next Steps page

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/va.gov-team#93570]
## Issue Description
QA for https://github.com/department-of-veterans-affairs/va.gov-team/issues/91413 using https://github.com/department-of-veterans-affairs/vets-website/pull/31833 for screencaps.

## Defects
- "Your next steps" and "After you submit your printed form" should be H2 headings and styled as H2s.
- The display of the representative information is a unique instance that occurs on the [Replace step](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=1474-1830550&node-type=frame&t=f1jfEEA2MuzlFHgC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A216659&show-proto-sidebar=1) and this page. The difference is the "Brian Daniel" representative name and "Disabled American Veterans" should be swapped in position and styling.

- It looks like the card has some extra padding on the top. Top and bottom padding should match ![Image](https://github.com/user-attachments/assets/47f5630d-33e2-4943-bbe7-3239f84b2e63)

## Acceptance Criteria
- [ ] Defects have been addressed

**Comment by jvcAdHoc** [comment]
Bumping the estimate to a 5. The assumed data shape from original development was incorrect and the whole page needs re-written. Also need to figure out how to have a page after the confirmation page that doesn't include the built in form navigation progress bar.

**Comment by jvcAdHoc** [comment]
There are screen shots in the pr. Going through the flow doesn't get to the page due to issues with pdf generation that I can disable locally, but can't do on staging so testing it there will be delayed.

**Comment by oddball-lindsay** [comment]
@mtri ready for you! See Jon's comment above about reviewing through screenshots (as opposed to Staging).

**Comment by mtri** [comment]
Last tweak:
- The top level heading of the instance of the card on the [Replace](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1474-1830550&node-type=frame&t=Uqmorbhn0csnDMqW-11) and [Next steps page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4376-204896&node-type=frame&t=Uqmorbhn0csnDMqW-11) should be H3 styled as an H4.

Other than that, looks good thanks!

@oddball-lindsay do we need a new ticket for this?

**Comment by oddball-lindsay** [comment]
New ticket - #95218 :)
