### ISSUE TITLE
Update Spanish Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#93590]
## Tasks
Make the following edits to Spanish content:

|   Key | Old content | New content| 
|-------------|--------------|----------------|
| or-you-can-call-MyVA411 | principal de información | de información principal |
| youve-successfully-reviewed-your-contact-information | Ha revisado | Usted revisó |
| vitamins-supplements-herbal-remedies | hierbas medicinales | medicinas a base de hierbas |
| allergies-or-reactions | pasados | anteriores |
|  this-claim-is-for-your | es por  | corresponde a |
| the-link-selected-has-expired | contacto | contacto en ese momento |
| sorry-we-cant-file-now | una reclamación de reembolso de viaje para usted | su reclamación de reembolso de viaje |
| you-can-review-online-until-date | hasta | hasta el |
| you-canceled | Ha cancelado | Usted canceló |

**Comment by brianseek** [comment]
@loripusey this is merged and ready to validate locally or on stage

**Comment by loripusey** [comment]
validated

**Comment by brianseek** [comment]
thanks @loripusey, closing
