### ISSUE TITLE
COVID-19 screening tool: Develop one-pager promotional sheet

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9360]
# User story

As the OIT team, we need a promotional one-pager to help tell the story of the COVID-19 digital screening tool.

# Details

Work with designer to develop a one-pager.

**Comment by batemapf** [comment]
Decided to break this into two one-pagers: one for facilities (internal facing?); one for PR purposes (external facing?).

**Comment by batemapf** [comment]
@artsymartha68 please update email and then close this out. thank you!

**Comment by artsymartha68** [comment]
@batemapf Current subject line is "Covid Screener Inquiry". Is that OK or would you prefer something else?

**Comment by batemapf** [comment]
works for me!

**Comment by artsymartha68** [comment]
Updated 1-pagers are here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/COVID-screener/visual-collateral
