### ISSUE TITLE
Redirect Request: Contested Claims

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#9362]
### Description
The term "Contest Claims" replaced "Multiple party claims" on all page content. The url for the page sill references multiple-party-claims and needs to be adjusted to contested-claims. 

### Requestor team info
Public Websites
Laura Walsh @lwalsh617 

### Implementation date

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing : When possible. (There's no error message or urgent matter driving this.)

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
*https://www.va.gov/decision-reviews/multiple-party-claims/ * | *https://www.va.gov/decision-reviews/contested-claims/ *

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
~~[ ]~~ All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@lwalsh617 @stephorkandatx 
The redirect requested above can be implemented once the actual page URL has been updated in Drupal.  Once the page is at its new URL, then the old URL can be redirected.

**Comment by RLHecht** [comment]
@lwalsh617 @mnorthuis This URL was changed in Drupal.

**Comment by lunascoop** [comment]
@kelsonic or @ncksllvn this redirect can be implemented now since it is not a legacy redirect.

**Comment by kelsonic** [comment]
@lunascoop Yupp! On it! 🙂

**Comment by lunascoop** [comment]
Validated that the redirect has gone live. Closing ticket.
