### ISSUE TITLE
Remove postman from vets-api workflows and helmchart used for Preview environments

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#93623]
## Issue Description

Remove postman from the preview environment helmChart and workflow

## Acceptance Criteria

- [ ] vets-api builds for preview environments no longer build postman containers

**Comment by ericboehs** [comment]
@patrick-black-oddball will investigate this ticket more to decide if the description is correct or if this can be closed as won't fix.
