### ISSUE TITLE
Remove links under gray boxes

### ISSUE THREAD

**Issue by katbrinkley** [department-of-veterans-affairs/va.gov-team#93622]
### User story

As a Cartography team member, I want to remove the identified links from the MHV landing page to reduce the number of non-useful links on the page so that Veterans have a more streamlined experience.

### Notes
- Removing low-value links is a first step follow-up to the UX strategy ticket recommendations (other recommendations could require more lift, but need review feedback from Kaitlin still)

Possible tasks:
- Remove list of links from the resource section on the backend
- Consider creating a plan for the other recommendations going forward (re: organization, surfacing actionable health-related links higher on the page, replacing high-clicked Classic links with updated content, etc.)

## Acceptance criteria
- Identified links are removed from the landing page
- QA review
- Potentially create follow up tickets as needed re: other recommendations, if approved

**Comment by wesrowe** [comment]
This story imagined a smoother path forward. We instead are going to take it slower, focusing on specific links piecewise.
