### ISSUE TITLE
Datadog charts for submits by form aren't populating on prod

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#93631]
### Expected behavior
Total submits as shown on our datadog dashboard are visible broken down by form in individual graphs.

### Actual behavior
Currently, graphs are updating for form 10-7959f-1 submits in production, except for the "10-7959F-1 Submissions." See image below. these charts appear to be working in staging.

### Acceptance criteria
- Viewer should see submits in the 10-7959F-1 Submissions chart
- We should be confident that submits for the rest of the forms will be visible once they're in production

<img width="551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3NBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c492e26a16922e670f5b20d9ff2449f6901c5e63/image.png" alt="image.png" />

**Comment by cloudmagic80** [comment]
I am still waiting on the production access. There is one more approval I need

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/93728

**Comment by cloudmagic80** [comment]
Looks like there is a mismatch between how the form ID is being set in the Ruby code and how it's being queried in the Datadog configuration.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/18676/files

**Comment by cloudmagic80** [comment]
Stilling pending from Platform. 24hrs is almost up and they will need to approve soon. I can't test in Dev.

**Comment by baltes** [comment]
This is working for f1 in prod, we'll have to continue to verify as other forms are deployed.
