### ISSUE TITLE
Evidence Upload Silent Failures - investigate upload failure email not dispatched upon job exhaustion event

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#93646]
A comparison was made of the number of logs indicating an upload failure email notification had been sent and the number of failures identified when comparing form uploads and eFolder contents.

Submission ID created after the evidence upload failure email service was enabled that requires further investigation:

- 3050565
  - The job to submit an evidence upload exhausted all retries and should have sent an email notifying the veteran, but did not have an accompanying log event indicating the mailer had been dispatched. A quick search for a log that there had been a failure in the exhaustion block for that job did not return any results, thus I can't be certain that notice was ever sent for this upload that appears in the form data but not in the associated eFolder.

Action item for 3050565:

- [ ] investigate and resolve reason the `Form526DocumentUploadFailureEmail` job was not triggered upon the "Submit Form 526 Upload Retries exhausted" event

Evidence Upload Silent Failures - Compare doc upload failure email count to suspected failures
[#92914](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92914)

**Comment by freeheeling** [comment]
@NB28VT 

Reviewing [logs](https://vagov.ddog-gov.com/logs?query=%28%40payload.form526_submission_id%3A3050565%20%7C%7C%20%40payload.submission_id%3A3050565%29%20&agg_m=count&agg_m_source=base&agg_t=count&cols=%40payload.form526_submission_id%2C%40payload.obscured_filename&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&view=spans&viz=stream&from_ts=1725861600000&to_ts=1726034340000&live=false), the last event associated with submission ID 3050565 is 'Submit Form 526 Upload Retries exhausted'. There's no evidence of a document upload failure email notification ever being dispatched when the job to send the corresponding evidence upload exhausted all retries. 

The metrics on the [Veteran-Uploaded Document Upload Failure Email Sent dashboard](https://vagov.ddog-gov.com/dashboard/jpm-85h-fea/form-526-document-upload-tracking-production?fromUser=false&fullscreen_end_ts=1726034340000&fullscreen_paused=true&fullscreen_refresh_mode=paused&fullscreen_section=overview&fullscreen_start_ts=1725948000000&fullscreen_widget=3397807297386214&refresh_mode=sliding&from_ts=1727209636107&to_ts=1727814436107&live=true) for September 10 match the count of [logged "Submit Form 526 Upload Retries exhausted" events](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22Submit%20Form%20526%20Upload%20Retries%20exhausted%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=%40payload.form526_submission_id%2C%40payload&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=desc&view=spans&viz=stream&from_ts=1725948000000&to_ts=1726034340000&live=false) on the same day.

The logging of 'Submit Form 526 Upload Retries exhausted' in code succeeds the conditional block evaluating whether the `Form526DocumentUploadFailureEmail` job is queued.

- You left a comment on May 16 about this flipper eventually being removed. How long should the [form526_send_document_upload_failure_notification flipper in SubmitUploads](https://github.com/department-of-veterans-affairs/vets-api/blob/ffcf4aedaf133a4b077c5be0e91139de9fefa716/app/sidekiq/evss/disability_compensation_form/submit_uploads.rb#L34) remain in place before it becomes more of a liability than an asset?
- Is it possible that this flipper was momentarily disabled, thus bypassing the `Form526DocumentUploadFailureEmail` job? Emily [commented](https://dsva.slack.com/archives/C053U7BUT27/p1721764883704359?thread_ts=1721760044.710529&cid=C053U7BUT27) once on phantom flippers. It's a shame there aren't any records to confirm when a flipper's state is modified to provide evidence for this theory.
- I wonder if it would be worthwhile running this particular evidence upload through the `EVSS::DisabilityCompensationForm::SubmitUploads#perform` method in an attempt to resubmit or at least trigger the mailer notification if it fails.

**Comment by freeheeling** [comment]
@lisacapaccioli – Changing status to `Done` with potential future action needed after receiving input from Nathan and/or others in response to questions posted in previous comment.

**Comment by freeheeling** [comment]
`FeatureToggleEvent` tracks `operations` and `values` of `feature_name` flippers, but it doesn't appear that this particular flipper was disabled at the time a notification mailer should have been dispatched. So perhaps something phantasmaniacal occurred and the anomaly, with a reference to the respective ticket, should be backlogged.
