### ISSUE TITLE
Adding Rachel Pope to DSVA Slack

### ISSUE THREAD

**Issue by andrea-merrill** [department-of-veterans-affairs/va.gov-team#93652]
# Description

Please add Rachel Pope, a new Adhoc Ux Design/Researcher, on IVC Forms (CHAMPVA) team to DSVA Slack as a Full Member.
rachel.pope@adhocteam.us

Rachel should be added to #vfs-all-teams, #vfs-change-announcements, #ivc-forms, #ivc-forms-UX, #1010-design-team, and any other pertinent UX/Design/Research and VFS general channels for new team members.

**Comment by andrea-merrill** [comment]
Good morning @KevinMHoffmanUSDS , @LEHigley , & @lkoenigsberg ! Rachel hasn't received her invite to slack, just checking to see if there's an update on this ticket.

**Comment by andrea-merrill** [comment]
fyi - @eunicegar & @pshahVA

**Comment by pshahVA** [comment]
Hey, She's on my team, i'll take care of it.
