### ISSUE TITLE
Adding stacy.wise@coforma.io to DSVA Slack

### ISSUE THREAD

**Issue by SilkeDannVA** [department-of-veterans-affairs/va.gov-team#93653]
Please add [stacy.wise@coforma.io](mailto:stacy.wise@coforma.io) as a full member, they will be joining the CEDAR CDS project. We will add them to the appropriate channels once they are in.

Please reach out to Jeff Langworthy and/or Silke Dannemann on DSVA slack for any questions/clarifications.

**Comment by SilkeDannVA** [comment]
Please provide the status of Stacy Wise's Slack request on 9/23. 
cc: @jlang10761

**Comment by SilkeDannVA** [comment]
They do not yet have access to their VA email address ***@***.***),
so the Slack invite must go to their corporate email.

Thank you.

*Silke Dannemann, PMP*  She/Her
Sr. Project Manager
M 301.455.4502   ***@***.***

<https://coforma.io/>
Read our Collectively newsletter on LinkedIn
<https://www.linkedin.com/newsletters/collectively-7019363458403995648/>

**Comment by amylai-va** [comment]
@LEHigley, Stacy's VA email is: stacy.wise@va.gov

But as Silke mentioned, she does not have access to her VA email yet. Could we invite her to slack using her Coforma email address?
cc: @coforma-terry

**Comment by SilkeDannVA** [comment]
The description for the Slack request specifically states that if you do
not have a va.gov email address to use your corporate or company email.

Currently the user can only access DSVA slack through their company email.

Yes, the person can connect to DSVA Slack with their company email.

Thank you,

Silke Dannemann

**Comment by JonathanKamensDVA** [comment]
Invite sent. Once a VA.gov email address has been created please switch the primary email address on the slack account to the VA address.
