### ISSUE TITLE
Adding saliha.ghaffar@coforma.io to DSVA Slack

### ISSUE THREAD

**Issue by SilkeDannVA** [department-of-veterans-affairs/va.gov-team#93655]
Please add [saliha.ghaffar@coforma.io](mailto:saliha.ghaffar@coforma.io) as a full member, they will be joining the CEDAR Benefits Management Team project. We will add them to the appropriate channels once they are in.

Please reach out to Silke Dannemann and/or Jeff Langworthy on DSVA slack for any questions/clarifications.

**Comment by SilkeDannVA** [comment]
Please provide the status of Saliha Ghaffar's Slack Request on 9/23.
cc: @jlang10761

**Comment by LEHigley** [comment]
do they have a VA email address?

**Comment by amylai-va** [comment]
@LEHigley, Saliha's VA email is: saliha.ghaffar@va.gov

But as Silke mentioned, she does not have access to her VA email yet. Could we invite her to slack using her Coforma email address?
cc: @coforma-terry

**Comment by JonathanKamensDVA** [comment]
Invite sent. Once a VA.gov email address has been created please switch the primary email address on the slack account to the VA address.
