### ISSUE TITLE
Contact Center Review for Veteran Facing Forms - New Confirmation Page

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#93658]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*  A new confirmation page which will be rolled out on one form to start 21-10210. 

### Launch Date
* Week of October 7th, 2024

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
*[Confirmation Page product guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/2024-05%20VFF%20and%20My%20VA%20Form%20Submission%20Research/Confirmation%20Page%20Product%20Guide%20(2).docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @tbaker1026. I'm getting a 404 Not Found on the GitHub link to the draft.

**Comment by tbaker1026** [comment]
[Confirmation Page Product Guide (2) (1).docx](https://github.com/user-attachments/files/17156779/Confirmation.Page.Product.Guide.2.1.docx)
@starlow00 - Can you see the attached?  I was not getting a 404 for the github link, let me know if the attached does not work.

**Comment by starlow00** [comment]
That one works for me, @tbaker1026. Thanks!

**Comment by starlow00** [comment]
Hi, @tbaker1026. Before I send this to VEO, I have a few questions:
1. Does this new confirmation page apply only to VA Form 21-10210?
2. Related to that, in the Description section, before going into the bullet points, it would be best to begin with a general description (a "square 1" description for the uninitiated, as much of Tier 1 contact center staff falls in that category) of what a confirmation page on VA.gov is.
3. In the Navigation section, the third bullet point ("For test users") URL gives me a 404 when I click.

**Comment by starlow00** [comment]
Thanks, @tbaker1026, that works. Sending to VEO for their review.

**Comment by starlow00** [comment]
There were no changes from VEO. The working copy is attached. Please use it for future revisions. Thank you!
[Confirmation.Page.Product.Guide.v2.1_SRT_09302024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--482bb550107e834f9873d4dc4efab85d46b10ac9/Confirmation.Page.Product.Guide.v2.1_SRT_09302024.docx)
