### ISSUE TITLE
Staging Review finding: Use va-radio instead of imposter components

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#93688]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Transition Experience
**Product:** Transition Experience MVP v1
**Feature:** V1 Transition Experience

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not meet best practices.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-meets-best-practices)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @it-harrison (QA)

### Description

In 2, 3, 5, and 6 an imposter radio component is used instead of the DST va-radio component

<details><summary>Link, screenshot or steps to recreate</summary>

![radio step 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/82863_ian_2.png?raw=true)
![radio step 3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/82863_ian_4.png?raw=true)
![radio step 5](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/82863_ian-6.png?raw=true)
![radio step 6](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/82863_ian_7.png?raw=true)

</details>

## Recommended action

use the va-radio component

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Radio button ](https://design.va.gov/components/form/radio-button)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by nkontrabecki** [comment]
Hi [@platform-governance-team-members](https://dsva.slack.com/admin/user_groups), thank you for reviewing our staging site and providing Staging Review feedback.

We have one question related to [feedback ticket #93688](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93688). We will remove any impostor components for radio buttons, but we need guidance on the maximum width for the va-radio component.

In the development environment, there is a platform-wide style that sets the component's maximum width to 320px. However, the [radio button component in Figma](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=495-11389&t=wgKrdCe9TTuD3UYj-4) has a max width of 480px, not 320px.

We can't find anything the [VADS site](https://design.va.gov/components/form/radio-button) or [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--docs) that expressly says confirms what the max width should be (unless I'm missing it somewhere). Can you confirm for us? Or is there someone else we should contact?
@cora-goldston-bah @RonnieYoung-UX @vetskrieg @iseabock

**Comment by nkontrabecki** [comment]
Completed and tested in Sprint 13. 10/9/2024.
