### ISSUE TITLE
Sync and Submit Mockdata for the 686-674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9370]
## Goal
Mockdata is handy when we are unable to get a hold of more "live" data and this hasn't been updated for a while now. 

## Tasks
- [x] Verify all BGS 674-686 calls are present and up to date with latest responses.

## Acceptance Criteria
- [x] A PR has been requested and merged for approval

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/141
