### ISSUE TITLE
[QA] 10-10CG - Form Updates: Complete testing for file upload alert

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93717]
## Benefit to the Veteran
As a Veteran, I want to see clear messaging on file upload alerts and errors, so that I can make decisions and adjustments to my attachment for a successful application.

## Background
Now that the July form updates have been released, we want to review content and make some adjustments to better align with VADS guidelines.
The changes is listed below.  Refer to [Figma design file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=2FrxXdW6Q7EbOvWb-0) for visual guidance.

1. "Check your upload" alert box should appear after the file is uploaded, not before.

### Resources
- [Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=2FrxXdW6Q7EbOvWb-0)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [ ] Complete QA testing on the File Upload "Check your upload" alert box
     - Should appear after file has been uploaded, not before
     - Should not change the file upload functionality

## Acceptance Criteria
- 10-10CG File Upload screen is confirmed to be updated with the correct order of information to display

**Comment by allanto-ah** [comment]
Verification comment in the FE ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90633
