### ISSUE TITLE
A11y Sev 1: Secondary nav – current section must be announced

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#93727]
### Defect

>The menu options at the top of the page invert colors when selected. For example, when Appointments is selected, it is visually highlighted as the colors are inverted that distinguishes it from the other menu options. If a menu option is visually shows as being selected there must be an audio indication that it is selected when focus is placed on the component. Something like "Selected Appointment Link"

### Notes
- 

Possible tasks:
- 

## Acceptance criteria

- When a user focuses on the secondary nav item/section that is visually highlighted to indicate the page's location, screen reader indicates this as well
- QA review
- A11y review

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the secondary nav items and the currently select secondary nav item are announced on macOS (VoiceOver) and Windows (NVDA)
