### ISSUE TITLE
"Coming soon" tag wraps to new line

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#93732]
### User story

As a Veteran, I want the Coming Soon tag to be on a line with "Medical records," so that the tag doesn't disrupt the flow of the page for me.

#### Tag wraps in staging
![Image](https://github.com/user-attachments/assets/2ea08e04-5998-421c-a87b-76f9538239a7)

#### Figma design
![Image](https://github.com/user-attachments/assets/fe2aa0f4-df16-4ec7-b66d-ee617ea2664b)

Possible tasks:
- 

## Acceptance criteria

- Tag doesn't wrap to new line for desktop layouts
- QA review

**Comment by radavis** [comment]
Ni [filed a support request](https://dsva.slack.com/archives/CBU0KDSB1/p1727459545493749) on the 'small-desktop-screen' breakpoint.

**Comment by radavis** [comment]
It appears that the following [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/32053) has resolved this issue.

**Comment by dcloud** [comment]
Per [my comment on the ticket](https://github.com/department-of-veterans-affairs/vets-website/pull/32265#discussion_r1792462829), the AC of "desktop layouts" is vague and open to interpretation. The VADS use of 1008px as a "desktop" width could be what the AC is referring to, though 1008px is an arbitrary length as far as I can tell. How can we validate this?

Also, "so that the tag doesn't disrupt the flow of the page" is 🙃

**Comment by nichia** [comment]
Base on [feedback](https://dsva.slack.com/archives/C0581MN69TJ/p1729011786673909?thread_ts=1727982964.858519&cid=C0581MN69TJ), we want to update this ticket to wrap the 'Coming Soon' tag when the line is full, instead of the previous method of wrapping at a fixed breakpoint of 1024px.

**Comment by LynneJohnson224** [comment]
@nichia can you please add a story point to this ticket when you have a minute?

**Comment by LynneJohnson224** [comment]
@allanto-ah do you need anything else to QA this?

**Comment by allanto-ah** [comment]
Verified that this is working as expected.

See attached video
https://github.com/user-attachments/assets/66cf3f92-4778-4ab4-9cc5-99bd0bf77c86
