### ISSUE TITLE
September evaluation report

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#93733]
### Notes
- [Here is the google doc presentation](https://docs.google.com/presentation/d/1HcP1ra-TrTj33mLVZIalVU4R2zB4-AptPPtyd9-5qWI/edit#slide=id.g30c16498a54_0_7)

Possible tasks:
- Pull data from GA4 and create evaluation report
- Thinking through the flow of the report and the story we're telling (this is likely to require edits on last month's report)
- Likely to include new stats, especially comparison of Sept and Aug numbers

## Acceptance criteria
- Present report with stakeholders at office hours
- Add report to folder in Sharepoint

**Comment by fmccaf1** [comment]
Planning to share report/presentation
