### ISSUE TITLE
CT: Error on click for "Calculate benefits"

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9373]
Steps to reproduce:

1. Open console
2. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/31800121
3. Select "Calculate benefits"
4. Observe error
5. Observe the Learning format accordion expands as well by default

![Screen Shot 2020-05-20 at 2.17.00 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d37707b2-cfe3-4183-9a29-c59d3d0b77b7)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12767

**Comment by sonntag-adam** [comment]
Error no longer occurs which fixes Learning format accordion expanding on click

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review.

**Comment by ccruzgra** [comment]
@sonntag-adam, @JenLJ and I took a look, and this checks out!

**Comment by sonntag-adam** [comment]
Closing bug.
