### ISSUE TITLE
Pension | submission failure saved_claim_id 8777636

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#93744]
Investigate and remediate (if possible) failed submission

saved_claim_id | confirmation_number | created_at | authenticated_start | first_submit_attempt
-- | -- | -- | -- | --
8777636 | 798412d8-48b5-41eb-bb06-dcacaa1a8a69 | 2024-04-04 19:47:26 UTC |   | 2024-04-04 19:47:26 UTC

`
https://api.va.gov/services/vba_documents/v1/uploads/fcc20f61-4621-44ee-92fc-d2d54e136250
{"data":{"id":"fcc20f61-4621-44ee-92fc-d2d54e136250","type":"upload","attributes":{"guid":"fcc20f61-4621-44ee-92fc-d2d54e136250","code":"DOC202","updated_at":"2024-04-10T12:46:09.829Z", "detail":"Upstream status: Unidentified Mail: We could not associate part or all of this submission with a Veteran. Please verify the identifying information and resubmit.","uploaded_pdf":{"total_documents":1,"total_pages":9,"content":{"page_count":9,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":500131,"attachments":[]},"line_of_business":"PMC"},"status":"error","location":null}}}
`

# Tasks
- [x] Determine if the veteran was logged in
- [x] If not, look at the in_progress or submission to see if it looks like junk
- [x] If it looks legitimate, resubmit it.

**Comment by wayne-weibel** [comment]
resubmitted
`
{"host":"vets-api-sidekiq-6c8574b5c4-pn6mf","application":"vets-api-server","environment":"production","timestamp":"2024-09-26T17:40:49.804838Z","level":"info","level_index":2,"pid":20103,"thread":"12060","file":"/app/modules/pensions/lib/pensions/monitor.rb","line":158,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"81c17169680eee089e3e6c7c19afd0a2f76702cd","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Lighthouse::PensionBenefitIntakeJob submission to LH succeeded","payload":{"claim_id":8777636,"benefits_intake_uuid":"5cd91197-71ee-4114-8ac7-a1c308bc8409","confirmation_number":"798412d8-48b5-41eb-bb06-dcacaa1a8a69","user_uuid":null}}
{"host":"vets-api-sidekiq-6c8574b5c4-pn6mf","application":"vets-api-server","environment":"production","timestamp":"2024-09-26T17:40:49.805520Z","level":"info","level_index":2,"pid":20103,"thread":"12060","file":"/usr/local/bundle/cache/ruby/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/redis_connection.rb","line":15,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"81c17169680eee089e3e6c7c19afd0a2f76702cd","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Sidekiq","message":"Sidekiq 7.2.4 connecting to Redis with options {:size=>10, :pool_name=>\"internal\", :url=>\"redis://dsva-vagov-prod-sidekiq.eqe4uk.ng.0001.usgw1.cache.amazonaws.com:6379\"}"}
=> "5cd91197-71ee-4114-8ac7-a1c308bc8409"
`

**Comment by aplatt-coforma** [comment]
We have resubmitted the failed submission. If this particular id fails again, we will know and create a remediation ticket to submit the PDF to the Remediation Sharepoint folder.

**Comment by wayne-weibel** [comment]
at success
`
https://api.va.gov/services/vba_documents/v1/uploads/5cd91197-71ee-4114-8ac7-a1c308bc8409
{"data":{"id":"5cd91197-71ee-4114-8ac7-a1c308bc8409","type":"upload","attributes":{"guid":"5cd91197-71ee-4114-8ac7-a1c308bc8409","code":null,"updated_at":"2024-09-26T22:09:29.617Z","detail":"","uploaded_pdf":{"total_documents":1,"total_pages":9,"content":{"page_count":9,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":500427,"attachments":[]},"line_of_business":"PMC"},"status":"success","location":null}}}% 
`
