### ISSUE TITLE
HLR | socOptIn value is undefined and causes 422

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#93742]
## What happened?

We got an [alert](https://dsva.slack.com/archives/C05UPRR0HK3/p1727366253868259) about an HLR submission that errored with a 422 and the [error body from the Lighthouse response](http://sentry.vfs.va.gov/organizations/vsp/issues/283264/events/fdb97d5397c3415aa6aeab60de1ba357/?project=3) said that the `socOptIn` value was missing. [Robin suspects](https://dsva.slack.com/archives/C05UPRR0HK3/p1727369546727579?thread_ts=1727366253.868259&cid=C05UPRR0HK3) that a recent change may have caused the issue.

## How severe is the problem?

- [x] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

## What is the desired behavior?

From [Robin](https://dsva.slack.com/archives/C05UPRR0HK3/p1727369546727579?thread_ts=1727366253.868259&cid=C05UPRR0HK3): "there's a checkbox. If they don't touch it, it should get set to false"

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by Mottie** [comment]
Verified with Derek, closing
