### ISSUE TITLE
[FE, QA] 10-10EZ - Reg Only: Minor changes to content (pre-launch)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93741]
## Benefit to the Veteran
As a Veteran, I want to have clear guidance and messaging on the application, so that I know what steps to take when I need assistance

## Scope
During a routine HEC call on 9/25, we received feedback on a couple of items that need content changes.  We are addressing a few of them here before we launch the Reg Only feature.  The changes are listed below.

1. Update Reg Only info page on the statement "We recommend calling our HEC to register".  The Veteran cannot register over the phone, but can receive guidance and assistance. The statement should align with this direction.
2. Rearrange the info accordion on the Reg/Enroll question page, moving the accordion toward the top of the page so that the information is findable and accessible to those Veterans who would like more information here.
3. ~Update the "Check your personal information" page - currently lists the Benefits phone number to change their information, however Veterans need to call the EED (Eligibility & Enrollment Dept) to change their personal info.~

### References
- [Figma Design](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6560-83996&node-type=section&t=1z1wMPBZVSltPNLo-0)

## Tasks
- [x] Update the UI screens as described and per design
- [x] Inform QA/PM when UI updates are ready for review
     - Signoff in the comments is required prior to launch

## Acceptance Criteria
- 10-10EZ is updated with the appropriate content and ready for launch.

**Comment by hdjustice** [comment]
There was some back & forth with the HEC team on the Personal info page, and we settled on leaving the benefits number as it is today.

**Comment by jessicastump** [comment]
Updated the [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3025-106249&node-type=canvas&t=VIHON3lf3JfNWak5-0) to put a big red "x" on the explorations the past couple days that we are not using for the personal info note content... @longmd let me know if there are any questions I can try and answer ;)

**Comment by hdjustice** [comment]
Reviewed staging for Authenticated user 16 and confirmed the "Check your personal information" page is retaining the benefits hotline, as agreed with HEC on 10/1/2024 via email with Angela Fulton.
![Image](https://github.com/user-attachments/assets/d64b84e5-c79d-4b9f-ac3c-8b8a81b5922f)

**Comment by longmd** [comment]
@hdjustice , just a note that none of this work is in staging yet. PR merge is blocked by the ongoing CI issues.

**Comment by hdjustice** [comment]
haha, i forgot.. Thanks!

**Comment by hdjustice** [comment]
Reviewed all changes and confirmed everything is displayed as expected per feedback discussions with HEC team prior to launch.  We are ready to go live in production.

### Validation details

- Check your personal info page retains the benefits number and design in place, agreed upon via email with Angela Fulton and team
     - ![Image](https://github.com/user-attachments/assets/e82115da-69c2-42db-8843-23694bbe76a2)
---
- Accordion info has been moved up on the Reg-vs-Enroll page, per verbal feedback from HEC team (feedback was around concern for Veteran's understanding of what they are choosing)
     - ![Image](https://github.com/user-attachments/assets/21be3f8c-0a13-4205-86f0-ab60f20c6b28)
---
- Reference on Reg info page to calling to register has been reworded to advise Veterans if they need help or have questions, and specifically point out that they can register by mail or in person.  Feedback was provided y HEC via email and confirmed verbally that Veterans cannot register over the phone.
     - ![Image](https://github.com/user-attachments/assets/e4198938-a48a-42a6-a8bc-47de1682382b)
