### ISSUE TITLE
Contact Center Review for Identity Team - Sign in page changes

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#93754]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The existing [sign in page](https://www.va.gov/sign-in/) and the [sign in modal](https://www.va.gov/?next=loginModal) are where we are making changes. These are where veterans who sign in from VA.gov and other VA online services sign into their VA account for a personalized experience. We are making some visual and content changes to highlight the deprecation of the MHV and DS Logon sign in methods, but the page and modal will still work the same as present.

### Launch Date
Sometime between ASAP and not later than Oct 31.

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
*Please provide product guide link* We aren't sure if there is an existing product guide for the sign in page or sign in modal. If your team has information on that we'd appreciate it. We are happy to update that or to put one together if we conclude that one doesn't exist.

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @claytonzook. I went through VEO's SharePoint archive, and I don't know that I've found precisely what you're looking for, but here are a few to consider. One of them is rather old...
[My VA 2.0 v8 guide SRT 01232024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee22d500e9e8142c9959751fc69bde75b67d51c6/My%20VA%202.0%20v8%20guide%20SRT%2001232024.docx)

[VA.gov.Profile.product.guide.v9.03212024 SRT 03212024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49a9f83e8c12e3290b9f64f742e8de8c10463518/VA.gov.Profile.product.guide.v9.03212024%20SRT%2003212024.docx)
[Two.factor.authentication.Product.Guide.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2e5169ff93974f82ed8b92b66d82ee0b6058254/Two.factor.authentication.Product.Guide.docx)

**Comment by claytonzook** [comment]
@starlow00 we have a product guide put together! V1 for sign in experience. Please let me know if there's anything else you need from our team for this review

[Sign in Experience Product Guide.docx](https://github.com/user-attachments/files/17316743/Sign.in.Experience.Product.Guide.docx)

**Comment by starlow00** [comment]
The draft looks good. Sending it to VEO today for their review.

**Comment by starlow00** [comment]
No changes from VEO. A working copy is attached; please use it for future revisions. Thank you!
[Sign.in.Experience_v1Product.Guide SRT 10152024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e0979b2bf71ce6c670c070b17c04096fb849de0/Sign.in.Experience_v1Product.Guide%20SRT%2010152024.docx)
