### ISSUE TITLE
Vets-api terminal access for Steve Long

### ISSUE THREAD

**Issue by stevelong00** [department-of-veterans-affairs/va.gov-team#93759]
### Your Name

Steve Long

### Your GitHub handle (terminal access is managed through GitHub)

stevelong00

### Team, Role, and Company of the target individual

IVC Forms, Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Bo Altes bo.altes@agile6.com

### Product Owner (PO) name and email

Premal Shah premal.shah@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Eunice Garcia

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![Image](https://github.com/user-attachments/assets/2e4641ee-9ee4-4d4e-b920-1dfd98a28671)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by lindsay-insco** [comment]
Access to `dev`, `staging`, and `sandbox` provided.
