### ISSUE TITLE
[CAIA Intake] Appointments Team: First time scheduling "The scheduling tool is not meant for emergency care" message

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#93755]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.

## Your team

- **Product name:**Appointments on VA.gov
- **Team name**: Appointments Team (formerly VAOS)
- **OCTO product owner:** Kay Lawyer (Kristen McConnell while Kay is on leave)
- **Product manager:** Lauren Earnest
- **Designer(s):** Melissa Lefevre
- **Slack channel:** [#unified-appointment-experience](https://dsva.slack.com/archives/C06RMRJCLHH), [#appointments-ux](https://dsva.slack.com/archives/C03CGTDLTFF), [#appointments-team](https://dsva.slack.com/archives/CMNQT72LX)
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** N/A

## Your CAIA team:
_Filled out by CAIA_
- **IA:** 
- **Content:** 
- **Accessibility:** 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  

### What's the nature of your initiative and desired outcomes?
`Tell us briefly about your work and the outcomes you’re aiming to achieve.`

**User Story:** As a Veteran scheduling an appointment for an urgent matter, I need to easily discover and understand where I can get help for immediate medical needs without being overwhelmed by alerts.   The objective is to balance the need for Veterans to be aware of immediate care options without causing them to feel overwhelmed by constant alerts. By strategically placing these messages and making them dismissible, the tool aims to enhance the scheduling experience while ensuring critical information is communicated effectively.

### First time scheduling "The scheduling tool is not meant for emergency care" message:
**Activation Conditions:**
First time the Veteran uses the scheduling tool, and every time they schedule unless they opt out of the message. 
**Functionality:**
The message appears only once unless the Veteran chooses to dismiss it by selecting "don't show this message again."
**Purpose:**
To provide critical information about immediate care resources without causing alert fatigue.
## Supporting artifacts
Figma file [First time scheduling message](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=3181-9969&t=nTqfJH0R7Oiqhqd4-1)

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We ran usability testing and iterated based on user feedback. We also met with the VHA mental health group to get feedback on the content and iterated based on their feedback. 

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [x]  Yes
- [ ]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** March 1-31
- **What is the name of your engineer who will build the React widget?** [Simi Adebowale](mailto:simi.adebowale@adhocteam.us)

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- **Hyperlinked Ticket Number:** 

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by laurwill** [comment]
Hey @melissa-lefevre , I took a look at this with Danielle and [futzed around with the content in a new frame](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=3260-1528&t=7v10OIxXJy9xMapH-1) — see what you think! I left you a few comments in Figma as well. Happy to chat more next week.

**Comment by laurwill** [comment]
Hi @melissa-lefevre , just checking in on this work — do we need to chat about the suggested updates (maybe in our SME sync tomorrow?), or okay to close this?

**Comment by melissa-lefevre** [comment]
We can close this ticket. I made the updates in the design.
