### ISSUE TITLE
Pension | Silent failure: submission failure saved_claim_id 9513803

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#93750]
Investigate and remediate (if possible) failed submission

saved_claim_id | confirmation_number | created_at | authenticated_start | first_submit_attempt
-- | -- | -- | -- | --
9513803 | 1a9e1276-b91e-4b0d-940e-babb1b894aa0 | 2024-08-02 22:49:15 UTC | 2024-08-02 21:35:53 UTC | 2024-08-02 22:49:28 UTC

`
https://api.va.gov/services/vba_documents/v1/uploads/6496f547-25cc-4fac-a7d0-a76922a3a728
{"data":{"id":"6496f547-25cc-4fac-a7d0-a76922a3a728","type":"upload","attributes":{"guid":"6496f547-25cc-4fac-a7d0-a76922a3a728","code":"DOC202","updated_at":"2024-08-03T00:03:51.307Z","detail":"Upstream status: Errors: ERR-EMMS-FAILED, Packet submission validation failed. Object reference not set to an instance of an object., File: EMMS-GCIO-22404636.xml;","uploaded_pdf":{"total_documents":7,"total_pages":465,"content":{"page_count":9,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":501241,"attachments":[{"page_count":55,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":4653363},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":7861814},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":15871631},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":1774233
`

https://dsva.slack.com/archives/CDRSFMWFL/p1722863631921379

Application name: Pension application, 527EZ
Team: Pension and Burial Team
Product Owner: Dene Gabaldon, Sanja Sanja Bajovic
API(s) used by your application:  LH Benefits Intake API
Application launch date: Re-launched 1/31/2024
Number of users impacted:1
Error category: DOC202
Date of first error: 8/2/2024
Submission date: 8/2/2024
User flow diagram: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703103128492/30dc0956f99482beffb457eb2ae884430cc2d3f4?sender=ud143866fd5369378295a0267
UUIDs: 6496f547-25cc-4fac-a7d0-a76922a3a728

# Tasks
- [x] Determine if the veteran was logged in
- [x] If not, look at the in_progress or submission to see if it looks like junk
- [x] If it looks legitimate, resubmit it.

**Comment by wayne-weibel** [comment]
resubmitted
`
{"host":"vets-api-sidekiq-6c8574b5c4-pn6mf","application":"vets-api-server","environment":"production","timestamp":"2024-09-26T17:44:45.109349Z","level":"info","level_index":2,"pid":20103,"thread":"12060","file":"/app/modules/pensions/lib/pensions/monitor.rb","line":158,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"81c17169680eee089e3e6c7c19afd0a2f76702cd","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Lighthouse::PensionBenefitIntakeJob submission to LH succeeded","payload":{"claim_id":9513803,"benefits_intake_uuid":"b8e252c6-d3bf-4dae-a82e-612083ed434a","confirmation_number":"1a9e1276-b91e-4b0d-940e-babb1b894aa0","user_uuid":null}}
=> "b8e252c6-d3bf-4dae-a82e-612083ed434a"
`

**Comment by aplatt-coforma** [comment]
We have resubmitted the failed submission. If this particular id fails again, we will know and create a remediation ticket to submit the PDF to the Remediation Sharepoint folder.

**Comment by wayne-weibel** [comment]
in vbms
`
https://api.va.gov/services/vba_documents/v1/uploads/b8e252c6-d3bf-4dae-a82e-612083ed434a
{"data":{"id":"b8e252c6-d3bf-4dae-a82e-612083ed434a","type":"upload","attributes":{"guid":"b8e252c6-d3bf-4dae-a82e-612083ed434a","code":null,"updated_at":"2024-09-27T18:06:29.151Z","detail":"","uploaded_pdf":{"total_documents":7,"total_pages":465,"content":{"page_count":9,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":501240,"attachments":[{"page_count":55,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":4653363},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":7861814},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":15871631},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":17742331},{"page_count":100,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":8441253},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":691367}]},"line_of_business":"PMC"},"status":"vbms","location":null}}}
`
