### ISSUE TITLE
[UX, PM] 10-10EZ - Notifications: Submission Failure email content review

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#93766]
## Benefit to the Veteran
As a Veteran, I want to have clear messaging when my 10-10EZ application submission fails, so that I know what steps to take for a successful submission

## Scope
Now that we have launched the 10-10EZ submission failure email notification through VA Notify (previously govDelivery), we can refine the content with our CAIA SME.

### References
- Screenshot of email with VA Notify template
     - <img width="805" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b288edf67dd07d35f525cbf9ebb430bf0e4c7c16/image.png" alt="image.png" />
- Old email from govDelivery
     - <img width="1910" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ef9168dc96ebea4a240a87aa5d5401fb6947ee9/image.png" alt="image.png" />
- In-Progress Reminder email
     - <img width="873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66e3dec4341dfa1a065e65c39b2c7d596a5e9a26/image.png" alt="image.png" />

## Tasks
- [x] Review content of the Submission failure email with CAIA
- [x] Review with PM once finalized
     - Signoff in the comments is required prior to updating template

## Acceptance Criteria
- The EZ Submission failure and Inprogress email content has been reviewed with CAIA

**Comment by jessicastump** [comment]
A [Figma page setup](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6579-85175&node-type=canvas&t=aURFbdJ4NsOaOxqZ-0) with the screen captures provided for the old version, and the newer VA Notify ones are mocked up so CAIA (Aliyah) can adjust with any recommended changes.

**Comment by jessicastump** [comment]
cc @hdjustice status update, from Aliyah post weekly content sync: 

> I'm going to ask Lily what would be best for the EZ email. I'll confirm if you should open up an intake request by next week.

I was asking if we can have both the EZ and EZR emails go through the same CAIA ticket since they were so similar or if we needed two - the email is waiting for review/changes from Aliyah.

**Comment by jessicastump** [comment]
[CAIA ticket link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93761) for the EZR one opened already - so it is easier to find

**Comment by hdjustice** [comment]
@jessicastump - can you add an estimate for this ticket?  I don't think we need to review it together, but if you want to, that is ok too

**Comment by jessicastump** [comment]
@hdjustice - Pointed a 2 just because there is a CAIA intake request ticket along with it :) 
- [Link to request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93979#issuecomment-2386575632)

**Comment by jessicastump** [comment]
@hdjustice - CAIA is asking about previous reviews and I wanted to confirm history tracking -- for the in-progress email, I found this old ticket and it looks like the reviews were just different then...
- Increase conversion of saved-in-progress health care applications by sending a reminder email [#23609](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23609)
- Are there any other old tickets/links that could be helpful?

**Comment by hdjustice** [comment]
hi @jessicastump - For the In-progress email, the VA Notify ticket is [#38707](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38707) and Allison with CAIA reviewed it.  It was way back in March 2022, and things were a little different then.

**Comment by jessicastump** [comment]
Here is the [Figma link](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6579-432679&node-type=frame&t=m2mzycsCtRLQH3Vt-0) with content recommendations and screen capture below: 
![Image](https://github.com/user-attachments/assets/63ceadcf-d9ec-485c-b3ac-bae65f343158)

**Comment by jessicastump** [comment]
@hdjustice Noting this is almost the same as the EZR version that HEC approved, should we sent this one along too for them to review?
Waiting to hear back on the in-progress version and if that needs a CAIA ticket or anything for next steps.

**Comment by hdjustice** [comment]
I would think it is ok, I can mention it tomorrow during HEC that they are similar in content and structure for consistency.

**Comment by jessicastump** [comment]
Updated screen capture for the submission failure email with draft updates from Aliyah on 10/10:

![Image](https://github.com/user-attachments/assets/d9ca3b71-8ecb-49e1-85b6-98a044cfe008)

**Comment by jessicastump** [comment]
No concerns as long as the HEC/E+E process stays as it is in the note

**Comment by jessicastump** [comment]
Realized I forgot to tag you @hdjustice yesterday - CAIA review is done (again) and recommendations are above! :) 
Subject line recommendation updates are also included. 
There was a callout from CAIA that there is updated guidance in the works for confirmation form page content to call out the number and type of emails post-submission that a Veteran can expect, there may be changes needed for that in separate tickets/CAIA intake requests.

**Comment by hdjustice** [comment]
Yep, looked at it and in the process of finding the right way to contact a Privacy Officer.  Thanks @jessicastump !

**Comment by hdjustice** [comment]
We can close this ticket.  The content looks good and will be submitted shortly to the Privacy Officer for review (#96499 )
