### ISSUE TITLE
[FE] My VA Forms Status: (QA bug) Copy for no forms to show state incorrect

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#93764]
## Background
On staging, when a user has no forms to show (drafts or otherwise) the copy in the Benefit applications and forms section should read:  **You have no benefit applications or forms to show.**

Currently on staging:
- LOA1 users in this scenario see this text instead: You have no benefit application drafts to show.
- LOA3 users in this scenario see this text instead: You have no applications in progress.

## Tasks
- [ ] Change copy in code for scenario when a user has no forms to show to read: You have no benefit applications or forms to show.

## Acceptance Criteria
- For all users (LOA1 and LOA3) who have no forms to show, they see copy in the Benefit applications and forms section that reads: You have no benefit applications or forms to show.

**Comment by allisonlu** [comment]
PR merged! will tag matt and aj once this gets onto staging and is ready for validation

**Comment by ajakabcin** [comment]
Confirmed on staging with LOA3 user (Cecil Morgan), and LOA1 user - content is fixed
