### ISSUE TITLE
NOD | Fix confirmation page typo

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#93772]
## What happened?

**Describe what went wrong**:
 
There is a typo in NOD's confirmation page success alert

**Add the steps to reproduce the bug**:

1. Submit NOD
2. Observe typo in confirmation success alert

**Add a screen recording or photo**:

<img width="500" alt="NOD success alert on confirmation page" src="https://github.com/user-attachments/assets/bd96f260-b9a5-4489-a7a1-3393f315dac1" />

## How severe is the problem?

- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [x] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

## What is the desired behavior?

Fix typo

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by eileen-coforma** [comment]
I don't see the change updated in staging yet, I'll check again later.
