### ISSUE TITLE
Contact Center Review for Public Websites - Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#93785]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Discharge Upgrade Wizard: Based on learnings from the PACT Act wizard, this new Discharge Upgrade Wizard will improve the ability for Veterans to determine their eligibility for a discharge upgrade by re-modernizing the product to align with current VA.gov design and content standards, updates to content to improve understanding, and conversion to a modern subtask pattern, which displays one question per page. Branching logic controls which next page the user is presented, depending on their answer(s) to previous question(s). CAIA also provided some content updates to the questions to improve understanding and readability.

### Launch Date
Tentative launch date is October 25. This date depends on CAIA content review completion, as well as Platform Governance Collab Staging Review completion.

### Version Number
This is v1 of the Guide. Although the Discharge Upgrade Wizard isn't a new product, Steve Tarlow has confirmed that there isn't an existing product guide for the wizard, so this will be the first one.

### Product Guide

- Guide in [Sharepoint](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/PW%20products/Discharge%20Upgrade%20Wizard/Product%20Guides/Discharge%20Upgrade%20Wizard%20Product%20Guide%20.docx?d=w539ee57b04ce4d0c80dd8f1ce91158fb&csf=1&web=1&e=ki7hAX)

As well as attached below in MS Word and PDF:

[Discharge Upgrade Wizard Product Guide  (1).docx](https://github.com/user-attachments/files/17156767/Discharge.Upgrade.Wizard.Product.Guide.1.docx)
[Discharge Upgrade Wizard Product Guide .pdf](https://github.com/user-attachments/files/17156768/Discharge.Upgrade.Wizard.Product.Guide.pdf)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The Veteran Support review complete, sending the draft for VEO review today.

**Comment by starlow00** [comment]
No questions from VEO. The working copy is attached for future revisions. Thank you!
[Discharge.Upgrade.Wizard.Product.Guide.v1_SRT_10012024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmtnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98159e959da374207edf624322587e866356eecd/Discharge.Upgrade.Wizard.Product.Guide.v1_SRT_10012024.docx)
