### ISSUE TITLE
Ensure claim information is masked in logs and URIs

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#93791]
## Context
Claim numbers `TC00000001234` are certainly PII, but because no one, even at OCTO levels, understands where the PII boundaries are, and also because the stakes are high if we're wrong about something NOT being PII, we need to strip any potentially PII & PII-adjacent information from any logging systems.

## Details
This has been done before in [vaos](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/helpers/vaos/anonymizers.rb) for ICNs and in appointments for VistA IDs.

We need to do the same for the opaque claim UUIDs.

## Acceptance Criteria
- [ ] As Nolle, I can visit a claim details page and see any relevant information including:
  - [ ] the url with opaque claim ID
  - [ ] the claim number on the page I can use to call my travel pay number
- [ ] As a dev, I can go to Datadog for the transaction described previously and see:
  - [ ] General information about the request (status, traces, etc)
  - [ ] NO references to claim IDs or claim numbers

**Comment by ayush-chak** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Beneficiary-Travel-BTSSS-65147e21930cd900223d8e64/issues/department-of-veterans-affairs/va.gov-team/93791?planning-poker) with Zenhub @hinzed1127 @kjduensing @liztownd

**Comment by hinzed1127** [comment]
Got a couple PRs up in draft. The `vets-api` one probably needs a few updates after some review discussion. The `vets-website` one is pretty limited. If the `vets-api` approach is valid, that one should be good to get promoted out of draft pretty quickly.

`vets-api` PR: https://github.com/department-of-veterans-affairs/vets-api/pull/18863
`vets-website` PR: https://github.com/department-of-veterans-affairs/vets-website/pull/32380
