### ISSUE TITLE
SOCKS access for Stacy Wise

### ISSUE THREAD

**Issue by dysbo** [department-of-veterans-affairs/va.gov-team#93796]
### Your Name

Stacy Wise

### Your Email

stacy.wise@coforma.io

### Your GitHub Handle

dysbo

### Your Role and Team

Engineering Lead on Benefits Management Team II

### Product Manager (PM) name and email

Saliha Gaffar, saliha.ghaffar@coforma.io

### Product Owner (PO) name and email

Amy Lai, amy.lai2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEw3RxHyFCUJWW0/FNpkbj/Y1xSJo4WDzq0z6sWj2pWk stacywise@Coforma-LQL2QM4N46-Stacy-Wise.local

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/c26fd131-830b-43f1-996c-1887b6c54e5c)

If that screenshot is not sufficient I will try to find another option.

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by dysbo** [comment]
Updated transmittal notice screenshot with email I received on Friday afternoon

**Comment by stoiven** [comment]
Found user in Atlas
Valid e-APP

SOCKS access granted. 

@dysbo please try using SOCKs now. I'll close this ticket, but feel free to re-open if you're having issues.
