### ISSUE TITLE
Create final wireframes for "go see staff" after checking in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93804]
## Description 

Based on [low-fi wireframes](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4366-34003&t=UXoHaANr655s2lGv-4). 

## Tasks

- [ ] Create final wireframes after IPT presentation feedback
- [ ] Add annotations for engineers, if needed

**Comment by benbrasso-agile6** [comment]
@zach-park you want to add an estimate to this ticket?

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , this ticket is ready to be validated:
https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4571-1061&t=frLAHedOoI95yswn-1

**Comment by zach-park** [comment]
Validated as team review

**Comment by zach-park** [comment]
I made a mistake of closing this ticket, reopened.
