### ISSUE TITLE
VA.gov Secure Messaging | Silent failure: No send on bad attachment

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#93807]
### Application name

VA.gov Secure Messaging

### Team

Secure Messaging team

### Product Owner (PO) name

Patrick Bateman

### API(s) used by your application

MHV messaging API

### Application launch date

2024

### Number of users impacted

<200 in last 30 days

### Error category

MHV error

### Date of first error

TBD

### Submission date

TBD

### Datadog query

https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20service%3Amhv-messaging%20status%3Aerror%20%40http.status_code%3A400%20%40error.message%3A%22BackendServiceException%3A%20%7B%3Astatus%3D%3E400%2C%20%3Adetail%3D%3E%5C%22Attachment%20scan%20failed%5C%22%2C%20%3Acode%3D%3E%5C%22SM172%5C%22%2C%20%3Asource%3D%3E%5C%22%5C%22%7D%22&agg_m=count&agg_m_source=base&agg_q=%40http.client_ip&agg_q_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=all&storage=hot&top_n=10&top_o=top&traceGroup=&view=spans&viz=stream&x_missing=true&start=1719673362512&end=1727449362512&paused=false

### User data flow diagram

user attaches file in browser --> user hits send --> vets-api --> MHV backend

### Relevant log output

BackendServiceException: {:status=>400, :detail=>"Attachment scan failed", :code=>"SM172", :source=>""}

### Additional Notes

Extensive background is in [Slack](https://dsva.slack.com/archives/C03T8JY2DM2/p1727447644490499?thread_ts=1727191268.702959&cid=C03T8JY2DM2).

**Comment by lichellebain** [comment]
https://jira.devops.va.gov/browse/MHV-62502

**Comment by humancompanion-usds** [comment]
Summary from the Slack thread:

1. user opens [VA.gov](http://va.gov/) SM tool[a]
2. user starts new message
3. user attaches file that will cause the SM backend to error out
4. user clicks send
5. user does not see error
6. message is not sent
7. User is returned to the message draft

167 instances were found in Datadog in the last 30 days. Patrick and team did an out of band deployment to return an error to the user. Post-mortem to follow.

**Comment by humancompanion-usds** [comment]
@batemapf - Your team fixed this, yes? Can we close this?

**Comment by batemapf** [comment]
yep! OK to close.
