### ISSUE TITLE
[Discovery] Logged-in homepage: Liz <> Tressa handoff

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#9381]
## Background

Liz is rolling off the project (boooo!) but Tressa will be ready to start ramping up on design by the time discovery is over (yaaaay!). Liz and Tressa should find time to regroup after the final synthesis is written to do a full deep dive and make sure Tressa feels ready to start taking on the new logged-in homepage designs.

## Tasks

- [ ] Tressa and Liz meet as often as they need to complete handoff.

## Acceptance criteria

- [ ] Tressa feels fully read-in on discovery and ready to dig into design!

**Comment by Samara-Strauss** [comment]
@mshea0606 @tressaellen this was on the list of to-dos for sprint 24 (see #10352) but I don't see that milestone associated with this. Did this get lost in the mix? If so, we will need to move to sprint 25.

**Comment by tressaellen** [comment]
@Samara-Strauss I think it must've been lost in the mix - I didn't have that on my radar for sprint 24 at all.

**Comment by mshea0606** [comment]
@Samara-Strauss @tressaellen It looks like it got lost. I will remove it from this sprint's objectives and add it to Sprint 25.

**Comment by andaleliz** [comment]
Meeting scheduled for 7/14

**Comment by tressaellen** [comment]
Meeting rescheduled for 7/15
