### ISSUE TITLE
Vets-api terminal access for Bryan Thompson

### ISSUE THREAD

**Issue by SnowboardTechie** [department-of-veterans-affairs/va.gov-team#93816]
### Your Name

Bryan Thompson

### Your GitHub handle (terminal access is managed through GitHub)

SnowboardTechie

### Your dsvagovcloud AWS user name (if applicable)

Bryan.Thompson

### Team, Role, and Company of the target individual

Sitewide team, FS Software Engineer, Agile 6

### Product Manager (PM) name and email

Jill Adams (Delivery Manager) - jill.adams@agile6.com or jill.adams1@va.gov

### Product Owner (PO) name and email

Michelle Middaugh suzanne.middaugh@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![Image](https://github.com/user-attachments/assets/3f2576a5-e5a2-40a8-83b7-0f3508aefd32)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by davidpetras** [comment]
@SnowboardTechie  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
