### ISSUE TITLE
SOCKS access for Chad Chotikasatien

### ISSUE THREAD

**Issue by govcioChad** [department-of-veterans-affairs/va.gov-team#93825]
### Your Name

Chad Chotikasatien

### Your Email

chad.chotikasatien@va.gov

### Your GitHub Handle

govcioChad

### Your Role and Team

Frontend Engineer on VEBT

### Product Manager (PM) name and email

Kara Ciprich - kara.ciprich@va.gov

### Product Owner (PO) name and email

Darla van Nieukerk - darla.vannieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDP9ZkxHxTt5DDfdU1WV0rZus6XGhtlCf4dpFGGyD8u9Mqo57pA84RxW77sgMur6omo5O+Rmmz03Zh/juMwIjkIjQB6GNOmGVn2zfsxJzuaTEXKIzzmiblqDv24Gg38ETOuaA4asU9bKA3ksMCPQQCK+JcnBUnmlqjUHtkUJRxWkoH01EXup4ywlyq+E3R5gYIfONZUHAX1yntzkmLhSvBkOX/Sd52OxPwZSi0mlomw0BX5BR3x1DWC3u2ZV/PxlNQC4/7uCI8vpXg807tJQNaxF0QE3u4O7SY/OEBdWTkUeQVKdSMMvM8VRxbse1IPriZYLKoN1zFHYi9GD5CMtaxo+PfaYDaPfEKKcLnb4NxDivccwUQE6EnWwLeM5N51ephDQQqCilw8fdYKMja1RWz6uluAqUrej12Yo0JPZuxP7iY9YbOW/1YDfgxiiCPE6tO6aI3n89OvT9JzoqiC9kphJnPvC2cw6WbLKjEA8dITq0/IjjiXEUGeZSJpcCZIbq0= chad@chad-VirtualBox

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/7e5ed00d-4c75-4e1d-be73-a5094fbb1041)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by stoiven** [comment]
Found user in Atlas
Valid e-APP

SOCKS access granted.

@govcioChad please try using SOCKs now. I'll close this ticket, but feel free to re-open if you're having issues.
