### ISSUE TITLE
Business intake form for Platform Services & Governance Crew

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#93857]
## Your Details
1.  Matthew Dingee
​
2.  **Business Line**
   VA.gov and mobile app Platform

## Notification Details
1.  Both
​
2.  **Please describe your use case.**
   As the Crew lead of the Platform Services & Governance Crew I need access to be able to view notifications that teams have established in order to govern the platform.
​
3.  **What actions can the user take based on the notification they receive?**
   n/a

4.  **What is the desired business outcome?**
    VFS teams are adhering to Platform guidance, specifically forthcoming guidance in the Design System to communicate with users who submit a Benefits request to us.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    Applications on VA.gov

6.  **What will trigger the notification?**
    Clicking submit on a form.

**Comment by mjones-oddball** [comment]
Relevant discussion happening https://dsva.slack.com/archives/C010R6AUPHT/p1727536721325619

@humancompanion-usds I'm closing this ticket since it's not for a new notification use case. We can continue assisting you with portal access in slack. 
CC @davidconlon @GitSamJennings
