### ISSUE TITLE
ARM: Draft content for 60 day expiration

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#93866]
## Description

<details>
<summary>Request from Michael</summary>

Hello @aprocik1 ! We're in need of a content pass related to work to enact changes related to a 60 day limit expiration on pending requests for v2. This has led us to readdress content on:

- [Confirmation page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10692-272217&node-type=frame&t=k01fawK2X7C9taSa-11)
- [Pending widget states](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10617-236552&node-type=frame&t=k01fawK2X7C9taSa-11)
- [NEW Declined widget state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10716-317932&node-type=frame&t=k01fawK2X7C9taSa-11)

This new content:

- Adds a note with dynamic date expiration
- Further aligns widget content with the confirmation page

We are also interested in new email notification content

- Update the v2 email confirmation to mention that this will expire in 60 days
- A new email notification when the expiration date is approaching
- A new email notification when the request has expired

We are happy to join office hours again to discuss any of this if that would be more efficient. Thanks!

</details>

<details>
<summary>Additional context from Lindsay</summary>

Jen forwarded a new policy contact at OGC who recommended the new email notifications Michael is requesting above. While he did not have specific guidelines for content, he sent over an example in case it helps.

> The USPTO allows TM applications to be signed electronically and sent via e-mail to the signer. The e-mail that’s sent to the signer includes the following notice regarding a 60-day time limit in which the form must be signed before it becomes invalid:
> 
> You have been sent this message by Nicholas Xanthakos for e-signature service through the Trademark Electronic Application System (TEAS), U.S. Patent and Trademark Office. The e-signature process was initiated on Thu Jul 11 15:35:08 ET 2024 and will expire on Mon Sep 09 15:35:08 ET 2024. Please be advised that the form must be signed and the filing to the USPTO completed within 60 days based on the minute the e-signature process was started.
> 
> I don’t know how applicable that notice is to your use case, but it does show that other federal agencies have time limits on signatures of electronic forms and the type of notice provided.

</details>

<details>
<summary>Deliverables from 10/1 office hours</summary>

- [AAR V2 email content](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESvrhUCMTilImpRgT4FLv3oBb_cUmTMw7EWPQGP9YCD2IA?e=TbK3rv)--"What to expect next" section (SharePoint)
- [60 day expiration content](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10692-272217&t=wf8yPU7InSJuiacV-4) (Figma)
- [RSW header content](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10761-359500&t=wf8yPU7InSJuiacV-4) (Figma)
- [Non-member VSO content](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=10769-379656#971576091)--form flow (Figma)
- Non-member VSO and POA content--FAQ page (SharePoint)
  - Note: These edits are being tracked in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82133#issue-2275394056
  
</details>

### Step 1: Screens

- [x] AP: Draft recommendations
- [x] AP: Share recommendations with product team
- [x] AP: Finalize recommendations with product team

### Step 2: Emails

- [x] AP: Draft recommendations
- [x] AP: Share recommendations with product team
- [x] AP: Finalize recommendations with product team

## Criteria
- [x] Content recommendations for the screens have been finalized with the product team
- [x] Content recommendations for the emails have been finalized with the product team

**Comment by aprocik1** [comment]
@mtri and @oddball-lindsay

Here are my content recommendations for the review page and widget states:

- [Recommendation 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=10692-272217#968114803)
- [Recommendation 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=10617-236552#968119703)
- [Recommendation 3](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=10716-317932#968133418)

Here are my recommendations for the existing email:

- [ARM AAR V2 email content](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESvrhUCMTilImpRgT4FLv3oBb_cUmTMw7EWPQGP9YCD2IA?e=DPSCND) (CAIA SharePoint--pages 2 and 3)

Here are my questions about the new emails:

- Who's the audience for each of these emails--Veterans or accredited representatives?
- What's the call to action for each of these emails?
 
> - A new email notification when the expiration date is approaching
> - A new email notification when the request has expired

**Comment by oddball-lindsay** [comment]
@aprocik1 

> Who's the audience for each of these emails--Veterans or accredited representatives?

Veterans and claimants! We can share this email template content with the rep-facing team too though, in case they want to incorporate any mentions of this notification or a similar rep-facing notification in their products.


> What's the call to action for each of these emails?

Honestly I just had awareness in mind so the Veteran is aware their POA request is close to expiration, or has expired. But thinking about their end goal (a response to the request), I think an appropriate call to action would be to contact the representative. @jfinnerty13 anything to add for this?

**Comment by jfinnerty13** [comment]
Nothing to add. Next steps would be to reach out the representative, or find a new representative would be my thoughts.

**Comment by aprocik1** [comment]
@oddball-lindsay, I've drafted the expiration emails for AAR V1. I've also updated the confirmation email for AAR V1 (to align with our current email pattern and include expiration information). Here's the content source of truth: [ARM AAR V1 email content](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ERSSB8NFfEdLtyz4rZYvI88BGm4dkfFK7385vhZVoK1pcQ?e=uoFeee)

Any and all of your feedback is welcome!

**Comment by jfinnerty13** [comment]
Left a couple comments in the doc, but question, is this email for the MVP pre fill PDF form or digital submit? Because we mention that the form will expire but I was under the impression that it only expired for the digital submit flow, not if they pre fill the PDF form? @oddball-lindsay

**Comment by oddball-lindsay** [comment]
Yes, the expiration is for when the online request to the rep expires which is solidly in digital submission land. 
Paper forms don't really have this concept of expiration -- the Veteran/claimant will print and bring it to the rep when they can. 
Sorry for not being clear about that!

@aprocik1 The content is on the right track, but should be moved to the v2 email templates and perhaps the expiration speaks more to "submitting another request" as opposed to "fill out a new form".

**Comment by aprocik1** [comment]
@oddball-lindsay, thanks for clarifying. Here are the updated source of truth documents:

- 1. [ARM AAR V1 email content](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ERSSB8NFfEdLtyz4rZYvI88BGm4dkfFK7385vhZVoK1pcQ?e=wtXMkD)
- [2. ARM AAR V2 email content](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESvrhUCMTilImpRgT4FLv3oBb_cUmTMw7EWPQGP9YCD2IA?e=z2cxIp)

Let me know if you have any suggestions or questions.

**Comment by oddball-lindsay** [comment]
Thank you @aprocik1!

**AAR v2 email content** - I have some feedback which I've left directly in the Sharepoint doc to maintain context. Let's chat over there!


**AAR v1 email content** - we are starting to ramp up towards QA and Staging Review and I'd like to minimize changes to the v1/MVP experience. I see that you updated the content in the lower section of the emails -- could we save those updates to be implemented in v2? It's seeming like we will follow right up with v2 development, after MVP launches.

**Comment by aprocik1** [comment]
@oddball-lindsay, I just responded to your comments in the AAR V2 document. You can save the AAR V1 updates as a fast follow. Those are minor--just to align with our most up-to-date confirmation email patterns.

**Comment by oddball-lindsay** [comment]
Thanks @aprocik1, I think we might be good to go on both of the comments I've left? Let me know when you think content is officially finalized and I can take the next step of adding these templates to VA Notify :).

**Comment by aprocik1** [comment]
@oddball-lindsay, I just re-reviewed these emails. They're ready for VA Notify!

I'm moving this ticket to validate, so that we can close it. Feel free to comment here again if I need to return to the emails and re-open the ticket. Thanks!
