### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by JonathanPostMO** [department-of-veterans-affairs/va.gov-team#93871]
### Name

Jonathan Post

### Email

jonathan@themostudio.com

### Role

UX Designer

### Team

Secure Sign-In Transition

### Additional Notes

We have a new PM onboarding soon (accepted an offer!), I believe @SophiaPhilipMO is acting as our interim. @Samara-Strauss is the Secure Sign-In Transition team PO.

**Comment by naomimarcussen** [comment]
Can you provide an email for the person who needs access?

**Comment by SophiaPhilipMO** [comment]
jonathan.post@va.gov

**Comment by Samara-Strauss** [comment]
If this needs approval from me, consider this approved.

**Comment by naomimarcussen** [comment]
Thanks, @SophiaPhilipMO! Jonathan already has an account with edit access (created on Aug 6). He just needs to log in with his jonathan@themostudio.com email. Let me know if he'd like this transferred to his va.gov email. Otherwise, he's good to go!

**Comment by JonathanPostMO** [comment]
I literally logged out and logged back in and it fixed everything, Figma's out here being the best troll it can be. Thanks @naomimarcussen and @SophiaPhilipMO, cheers!

**Comment by naomimarcussen** [comment]
Yay! Happy you're in.
