### ISSUE TITLE
VA Forms Overview docs -- read more -> dead links

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#93873]
### Description

[The VA Forms Overview docs page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) presents a link to [Getting Started with VA.gov Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md) at the top of the page. Unfortunately, there are a number of dead links in that document which makes it not so useful as a resource when studying the VA Form system.

Consider removing the link to `https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md` or updating the dead links in that document.

### Relevant URLs

Output of Simple Link Checker on that page (red links are 404s):

![Image](https://github.com/user-attachments/assets/972574dd-e6f0-41ea-b02b-80f2caafdfee)

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS team

**Comment by jknipes** [comment]
Hi @radavis , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@JaciWilkinson is there a new GitHub document to replace [the one mentioned above that contains several dead links](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93873#issue-2556876401)?

**Comment by jknipes** [comment]
reached out to Jack Wilkinson again, [via Platform Content channel in Slack](https://dsva.slack.com/archives/CL181NRJQ/p1731099794850269)

**Comment by jknipes** [comment]
We have been advised to replace the GitHub link with a link to a [page on the the Design System ](https://dsva.slack.com/archives/CL181NRJQ/p1731101458401459?thread_ts=1731099794.850269&cid=CL181NRJQ)

**Comment by jknipes** [comment]
@radavis the page has been updated, we are closing this ticket as _Complete_
