### ISSUE TITLE
Qualitative Data Request - Claim and Appeals Status Tool

### ISSUE THREAD

**Issue by jstrothman** [department-of-veterans-affairs/va.gov-team#93895]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

06-26-2024

### Date Range End

09-30-2024

### Product Name(s)

Claim and Appeals Status Tool

### Product Description

The Claim/Appeal Status provides a place for Veterans to view information about their claims, including: status, recent activity, and requests to the Veteran and to others. Veterans can also use the tool to upload evidence associated with their claims.

### Survey URL(s), key term(s), case category or type

/track-claims
/decision-reviews

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

None

### VA Email Address(es)

julie.strothman@VA.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.

**Comment by jstrothman** [comment]
Thank you @newworld2616 !
