### ISSUE TITLE
Adding Penny Lischer to DSVA Slack

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#93907]
# Description

Please add Penny Lischer new Agile Six Sr. Software developer on Debt Resolution team to DSVA Slack as a Full Member.
[penny.lischer@agile6.com]

Penny should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineers and VFS general channels for new team members.

**Comment by dhill802** [comment]
fyi @denisecoveyduc

**Comment by dhill802** [comment]
It shows that Penny was in DSVA slack at one point and is in a deactivated state currently. She was on the VA.gov platform CMS Team previously. Penny will now be with the VA team - Debt Resolution. Thank you!

**Comment by dhill802** [comment]
Hello - Just looking for a follow-up on timing to see when Penny will have Slack access? If there is any additional information you need, just let us know. Thank you.

**Comment by pshahVA** [comment]
I added based on @denisecoveyduc request.

**Comment by dhill802** [comment]
Thanks @pshahVA
