### ISSUE TITLE
How do pending cc appts appear in the Request and referrals page?

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#93904]
## Description 

Knowing that there's a manual process for MSAs to add scheduled appts into HSRM which will then tell VistA the appt is scheduled, how will our CC appts appear in the new pending page? 

## Tasks

- [ ] Wireframe how CC "pending" appts appear in the new pending page

**Comment by cgednalske** [comment]
@benbrasso-agile6 can we talk through this one more? I'm not sure I'm following what the task is.

**Comment by benbrasso-agile6** [comment]
Yes, I added it to SoS agenda

**Comment by benbrasso-agile6** [comment]
Forgot that we didn't need this. Thx for closing.
