### ISSUE TITLE
Update community care provider facility api version.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#93949]
## Description

We need to update the facility api version from v1 to v2.
current endpoint: `/facilities_api/v1/ccp`
updated endpoint: `/facilities_api/v2/ccp`

---

## Development Checklist
- [ ] endpoint updated from v1 -> v2
- [ ] Update mocks and tests.

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by JRRoof** [comment]
Validated in Staging using test user Judy Morrison, Audiology, Community Care, Hearing Aid Support.  Here are the providers that were displayed.
<img width="547" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--946c95dedcb351cb4ad60b6f83daae0e9e8329df/image.png" alt="image.png" />
