### ISSUE TITLE
686/674 Backup Submission Failure on 9/27/24

### ISSUE THREAD

**Issue by tfink419** [department-of-veterans-affairs/va.gov-team#93944]
# Overview
An error occurred on 9/27/24 that was alerted in slack [here](https://dsva.slack.com/archives/C063YELFVLM/p1727455635585059). The error was shown as:

```
Time | Host
-----------------------------
16:45:33 UTC | vets-api-sidekiq-6c8574b5c4-kl9l5
CentralMail::SubmitCentralForm686cJob failed!
-----------------------------
```

[Datadog link](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22CentralMail%3A%3ASubmitCentralForm686cJob+failed%21%22+%40named_tags.dd.env%3Aeks-prod&from_ts=1727455244000&to_ts=1727455544000&live=false&agg_m=count&agg_t=count&index=%2A&source=monitor_notif)

# Tasks
- [x] Determine cause (veteran name not in payload)
- [ ] Attempt resubmission

**Comment by evansmith** [comment]
I ran the resubmission and got a success from central mail. This was due to the missing veteran information that rarely occurs.
![](https://files.slack.com/files-pri/T03FECE8V-F07PQQFJATU/screenshot_2024-09-30_at_2.38.03_pm.png)

**Comment by mjknight50** [comment]
Thank you!  Should we be doing some FE validation to prevent this?
