### ISSUE TITLE
VR&E User UUID is being used in sidekiq

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#93953]
# Overview
The VR&E controller is passing the `current_user` to sidekiq which is a problem with the async nature of that job.
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/veteran_readiness_employment_claims_controller.rb#L13

# Tasks
- [ ] - Switch to the `user_account_uuid`

**Comment by sanjabaj2** [comment]
Do we have past cases where this happened and we lost the submission? If so, another ZSF:Remediation ticket should be opened if we can find those failed cases.

**Comment by evansmith** [comment]
This will be slightly more involved than just passing a different uuid. We'll use the same scheme of an encrypted user_struct to imitate a user so that we don't have to rely on attempting to find the user in the job.
