### ISSUE TITLE
10-7959f-1: Ensure flipper shows correct content for both conditions

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#93951]
As a user accessing the FMP registration form on production, I need to see the correct content based on whether or not the flipper lets me through to the digital form.

### Acceptance criteria
Given a user arriving at the static page for FMP registration
- When the user is allowed through to the digital form by the flipper
   - Then the user should be taken to the digital form that they can submit online
- When the user is allowed through to the digital form by the flipper
   - Then the usr should be taken to the PDF form that they can download

**Comment by baltes** [comment]
Refer to this user story for background on the content for those who are not allowed through to the digital form.
https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/89394

**Comment by reiting** [comment]
@baltes this was merged!
