### ISSUE TITLE
Exclude p_auth parameter from All and MHV views

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#9395]
We have a URL parameter - *p_auth* - in MHV that I believe is unique for every login:

![image](https://user-images.githubusercontent.com/62304138/82559026-e2954d80-9b3c-11ea-9bbe-56efd423153b.png)

This is artificially inflating our Page URL cardinality.  For instance, I see over 200,000 unique URLs with this parameter for 5/18/20:
 
![image](https://user-images.githubusercontent.com/62304138/82559187-28521600-9b3d-11ea-951b-3bc2e0e4ecab.png)

Since this is a unique session-based param (like the various tokens we currently exclude), I suggest we add it to the URL Query Parameter exclusion list for these views:

- All Web Site Data
- myhealth.va.gov

**Comment by bsmartin-ep** [comment]
@jonwehausen -

I added _p_auth_ to the non-prod MHV view exclusion list so we can see the change in URLs.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Results from yesterday.

### Unique MHV URLs on non-prod dropped from [875](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w178298118p176884211/_u.date00=20200521&_u.date01=20200521&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22~2Fmhv-portal-web~2F.*%3F.*p_p_id%22,0%5D%5D/) to [238](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w178298118p182431357/_u.date00=20200521&_u.date01=20200521&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22~2Fmhv-portal-web~2F.*%3F.*p_p_id%22,0%5D%5D), a drop of 72.8%.  :champagne: 

I'm thinking there will be a larger drop on production since it won't just be someone testing the same page many many times like on staging here.

**Comment by jonwehausen** [comment]
@bsmartin-ep Thanks for testing this in staging! Let's move forward with adding to the production All Website Data view. Please make an annotation on the view when live.

**Comment by bsmartin-ep** [comment]
This has been updated and annotated in:

#### Prod
All
MHV 

#### Non-Prod
All
MHV
