### ISSUE TITLE
Contact Center Review for [VA - IIR - Veteran New Acct Flow w/in Authenticated Experience]

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#93963]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Product - Welcome To My VA*
*Welcome to MyVA is the launching product for a new Veteran experience in MyVA. Current state of a new user who accesses MyVA for the first time is a blank landing page as there are no claims in process or any identifiable actions. Welcome to MyVA aims to improve that initial experience by:
1) acknowledging a user's status as being new to MyVA (Welcome to MyVA Modal message)
2) Informing them of what MyVA is
3) directing them to actions they can take to immediately improve their profile with the main goal of decreasing time to benefits
-This will help guide a user to verify their identity and become an LOA3 user, which will then allow them to leverage all VA.gov has to offer

### Launch Date
*The tentative launch date is the middle of December.*

### Version Number
*V1*

### Product Guide
*Please provide product guide link*
[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/product-outline.md](url)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @kingbmike. Can you please attach a copy of the draft to this ticket? Thank you!

**Comment by starlow00** [comment]
Hi @kingbmike 
Just following up. Thanks!

**Comment by starlow00** [comment]
Hi @kingbmike. Since I haven't heard from you, I will close the ticket on this end. Please feel free to reopen if you have updates. Thanks!
