### ISSUE TITLE
Review GA / GTM accounts

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#9396]
With the recent changes in the Analytics-Insights team, I think it is a good idea to review all current  GA / GTM admin accounts to make sure they still valid.

I have created a spreadsheet of current accounts:

https://docs.google.com/spreadsheets/d/1LtGhKytH1Qxz6nK6tavDazRYiWULPZV3jETVIn4txaQ/edit?usp=sharing

Due to the sensitive nature of these accounts, we should work there or in Slack.

### Account Review Process

1. Is the account still necessary?  If associated with a person, is the person still with the VA? Is the person still active on the platform and requires this access?
2.  If it's an account created to run reports or access the API, is it still use?  Does it have appropriate (i.e. minimal) permissions? <br>
**NOTE:** have a dev search in credstash.

3.  If it's a non-domain account (like gmail), can we transition to a @va.gov email?

### Definition of Done
- [ ] All current GA / GTM accounts have been reviewed
- [ ] Any invalid accounts have been removed
- [ ] Appropriate platform team members have been notified

**Comment by bsmartin-ep** [comment]
@joanneesteban -

This user is still an Organization Admin (with Manage Users) permissions because they are in the *United States Department of Veteran Affairs* group.

![image](https://user-images.githubusercontent.com/62304138/84433989-3277a980-abfd-11ea-9906-7982868e3597.png)

Should we remove him from the group?  Looks like he requested removal of other access:

https://github.com/department-of-veterans-affairs/devops/issues/4763

**Comment by bsmartin-ep** [comment]
Per this [Slack conversation](https://dsva.slack.com/archives/GMP330AG3/p1601320757004300), the following GA accounts have been removed...

clar----.com
aar----mail.com
rei----ail.com
tmb7----.com
ko----il.com
davs----.com
cait----ail.com
man----il.com
emer----il.com

**Comment by jonwehausen** [comment]
### Remaining Steps towards Closure 
- [ ] BCC email all folks with a `@gmail` account currently in our GTM/GA 
     - Give a grace period of 10 days, for all folks who we **don't** hear from, remove access following the 10 days
     - For folks who respond with a _"yes I would like to maintain my access"_, we follow-up separately with them and request for them to go thru our normal process of creating a Google account associated with their va.gov email
- [ ] For folks who are deactivated users in Slack, remove immediately. 
- [ ] For folks who are **activated** users in Slack, reach out separately indicating status of account. 

cc: @joanneesteban and @bsmartin-ep for visibility

**Comment by jonwehausen** [comment]
## Updated Google Sheet with accounts: `https://docs.google.com/spreadsheets/d/1edJSf5zuFPiU3BCbcK6jbptNjRT_NOYnKvy4rU9uKaU/edit#gid=1693051957`

**Comment by bsmartin-ep** [comment]
The following GA accounts [were attached to deactivated Slack accounts](https://dsva.slack.com/archives/GMP330AG3/p1605065152005100?thread_ts=1605018761.002400&cid=GMP330AG3) and have been removed:

```
ahuxxxxxxxx@xxxxxxxxernmentcio.com
alex.sexxxxxxxx@xxxxxxxxle6.com
andrew.suprexxxxxxxx@xxxxxxxxocteam.us
annekainixxxxxxxx@xxxxxxxxil.com
brett.thompxxxxxxxx@xxxxxxxxgov
caroline.javornxxxxxxxx@xxxxxxxxgov
cc.xxxxxxxx@xxxxxxxxgov
chris.givexxxxxxxx@xxxxxxxxil.com
clarice.xxxxxxxx@xxxxxxxxgov
xxxxxxxx@xxxxxxxxocteam.us
davidxxxxxxxx@xxxxxxxxgov
elxxxxxxxx@xxxxxxxxocteam.us
elizabeth.xxxxxxxx@xxxxxxxxgov
elizabeth.lxxxxxxxx@xxxxxxxxocteam.us
emilytaxxxxxxxx@xxxxxxxxil.com
fatima.xxxxxxxx@xxxxxxxxgov
jane.newxxxxxxxx@xxxxxxxxgov
jeddalyn.pxxxxxxxx@xxxxxxxxughtworks.com
joy.wxxxxxxxx@xxxxxxxx.gov
jxxxxxxxx@xxxxxxxxocteam.us
julie.fixxxxxxxx@xxxxxxxxme
kerry_i_lenxxxxxxxx@xxxxxxxx.eop.gov
laura.cochraxxxxxxxx@xxxxxxxxil.com
marcella.jaxxxxxxxx@xxxxxxxxgov
mexxxxxxxx@xxxxxxxxapbc.com
michael.ferxxxxxxxx@xxxxxxxxgov
mikexxxxxxxx@xxxxxxxxocteam.us
natalie.moorxxxxxxxx@xxxxxxxxil.com
raquelromanxxxxxxxx@xxxxxxxxil.com
robbieholmexxxxxxxx@xxxxxxxxil.com
ryan.bxxxxxxxx@xxxxxxxxocteam.us
```

**Comment by joanneesteban** [comment]
Putting this into QA. We can close after 12/2 and the gmail accounts have been removed.

**Comment by jonwehausen** [comment]
Per 0 email receipts from users wanting to convert their access and 12/2 marking the end of our grace period...the remaining 18 GA accounts have been removed: 

```
ryan.bxxxxxxxx@xxxxxxxxocteam.us
john.hashixxxxxxxx@xxxxxxxxil.com
amyxxxxxxxx@xxxxxxxxil.com
adrollixxxxxxxx@xxxxxxxxil.com
luciana.a.moraisxxxxxxxx@xxxxxxxxil.com
Andrea.schneider.xxxxxxxx@xxxxxxxxil.com
andrew.hughey.xxxxxxxx@xxxxxxxxil.com
ombjxxxxxxxx@xxxxxxxxil.com
JQuaxxxxxxxx@xxxxxxxxil.com
rdaxxxxxxxx@xxxxxxxxil.com
brian.grxxxxxxxx@xxxxxxxxil.com
lwalshmaxxxxxxxx@xxxxxxxxil.com
ep.va.read.xxxxxxxx@xxxxxxxxil.com
chante.lantosswetxxxxxxxx@xxxxxxxxil.com
andrew.lewandowski.xxxxxxxx@xxxxxxxxil.com
randallweidberg.xxxxxxxx@xxxxxxxxil.com
melissa.schaff.xxxxxxxx@xxxxxxxxil.com
josephjxxxxxxxx@xxxxxxxxil.com
matthewself.xxxxxxxx@xxxxxxxxil.com
```
