### ISSUE TITLE
Investigate Sporadic Review Instance Issues

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#93988]
# Description
Given the sporadic reports of Review Instance issues in the past week, we should investigate the potential root cause(s) of the issues. Below are two examples of the support requests --
1. https://dsva.slack.com/archives/CBU0KDSB1/p1727381189081689
2. https://dsva.slack.com/archives/CBU0KDSB1/p1727707808185709

## Acceptance Criteria
- [x] The root cause for the first example issue has been discovered and recorded here or in Confluence
- [x] The root cause for the second example issue has been discovered and recorded here or in Confluence

**Comment by ben-allen-oddball** [comment]
More info from @pjhill http://jenkins.vfs.va.gov/blue/organizations/jenkins/deploys%2Fvets-review-instance-deploy/detail/vets-review-instance-deploy/153535/pipeline

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/pull/506

Bump disk sizes on default base image.  This will not fix any existing deplyoments.  But will solve for future...... I hope...
