### ISSUE TITLE
Benefit application introduction

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#94]
This is an introductory statement about benefit applications. This will be at the top of the page that includes documentation for eligibility, how to apply, apply now, and after you apply. 

---

# Benefit applications

Benefit applications are where users can go to apply for benefits in any of the benefit hubs on VA.gov.  The policies and regulations around these benefits are very complex, and users often have difficulty determining if they are eligible, what they need to provide, and what to expect after they've submitted their application. For this reason, benefit applications, as a pattern, are divided into four distinct "epics" that help users navigate the process from start to finish.

 The four epics typically found within each benefit application are:
1. Eligibility
2. How to apply
3. Apply now
4. After you apply

Structuring benefit applications in this way has, through rigorous usability testing, demonstrably improved how to educate users about the benefits and how to set expectations about the application process. For the Department of Veterans Affairs, this means that applications are more accurate and complete, so the Department to better serves its constituents.

**Comment by jaredcunha-usds** [comment]
@lalexanderson-dsva @goldenmeanie @smoonpeyes Would love your thoughts on this and let me know if anything here is inaccurate.

**Comment by jaredcunha-usds** [comment]
Once I see the documentation for service history and waivers, I'll be sure to include a brief blurb here as well.

**Comment by rtwell** [comment]
is this where we want to list out a user story-ish approach to this pattern—kinda like "as a new designer at DSVA tasked with digitizing Benefit Application 1234, I can begin to break the form into the following sections…" or would each section (e.g. Eligibility) contain that documentation?

**Comment by jaredcunha-usds** [comment]
Hmmm, I feel a little strange about formatting patterns as a user story. It's not something I believe I've seen in other design systems that document design patterns. That feels more like something I'd see in a ticket. Like the rest of the pattern, it sort of follows the line of "this is what this pattern is" and "this is how the pattern is designed and why it is designed that way that it is."

**Comment by rtwell** [comment]
blurgh i didn't explain that very well—what i mean is, if I were a new designer to VA and I have to digitize Form 1234, how will that ☝️ text (what you initially wrote) help be break down that form?

**Comment by jaredcunha-usds** [comment]
@rtwell Gotcha! Perhaps it might need some tweaking once we see how those pieces are all put together? But I was attempting to be succinct here because the page is already going to be pretty dense. 

So basically, it says "a benefit application is X. the requirements and overall process is complex, so it's broken into four parts (in the numbered list, can probably write a brief sentence to explain what the parts are in VERY minimal detail). we know this works." after that, we'll have the write-up for eligibility, followed by the write for how you apply, followed by etc, etc. 

Does that make sense? Does that explain why the _epics_ exist?

**Comment by jaredcunha-usds** [comment]
Once the write-ups for all the epics get closer to being complete, I'm going to get a single pull request on design.va.gov together so we can better evaluate how well everything lines up too.

**Comment by caw310** [comment]
Closing as this is over 3 yrs old.
