### ISSUE TITLE
Mobile auth token discovery

### ISSUE THREAD

**Issue by ayush-chak** [department-of-veterans-affairs/va.gov-team#94008]

**Comment by liztownd** [comment]
The Mobile team uses an auth token from the VA Sign in Service for authentication (vs. the cookie based system VA.gov uses). 

Although the VA SIS is used for both our STS token (required to hit the Travel Pay API) it is different from the SIS token used by the mobile app, so we will still need to retrieve an STS token in the mobile app.

I confirmed ([DSVA slack message](https://dsva.slack.com/archives/C018V2JCWRJ/p1727893093699489?thread_ts=1727878299.897189&cid=C018V2JCWRJ)) with the identity team that the user object used by the Mobile app has all the same attributes as the user object used on VA.gov, so the existing token service and caching should work with that user object without requiring adjustments.
