### ISSUE TITLE
10-7959f-1: Update processing estimate to 90 days on confirmation page

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94006]
Currently the FMP registration confirmation page tells the applicant the form will take 60 days to process. We should change this to 90.

<img width="527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7aa5f3dea52cabdad120473945d9eeab907db52e/image.png" alt="image.png" />

**Comment by reiting** [comment]
<img width="716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b0712a3d2f8ae9702f831add5c410451821e3ab/Screenshot%202024-10-01%20at%2011.22.52%E2%80%AFAM.png" alt="Screenshot 2024-10-01 at 11.22.52 AM.png" />

**Comment by reiting** [comment]
This is done and has been merged! @baltes
