### ISSUE TITLE
CT: Remove Profile Yellow Ribbon Modal Content Prod Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9401]
As a developer, I need to remove the prod flag for the yellow ribbon modal content updates so that the functionality is available in the production environment.

## Assumptions:
1. The content update was reviewed by EDU on staging and approved as of 05/21/2020.

## Acceptance Criteria
1. The work completed in #8524 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12759

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-05-26 at 10.48.46 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/af6d3013-7cc8-42ee-88d8-2e0c8d604ac1)

**Comment by delli-gatti-michael** [comment]
Updated content is now in Production. Closing this issue.
