### ISSUE TITLE
Qualitative Data Request Va.gov homepage

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#94019]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2024

### Date Range End

09-30-2024

### Product Name(s)

VA.gov homepage

### Product Description

The landing page for VA.gov

### Survey URL(s), key term(s), case category or type

https://www.va.gov/

### Sub URLs

No

### File Delivery Format

All in one file, on one tab

### Word Cloud

None

### VA Email Address(es)

suzanne.middaugh@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
