### ISSUE TITLE
Qualitative Data Request - Income Limits

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#94018]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2024

### Date Range End

09-30-2024

### Product Name(s)

Income limits wizard

### Product Description

Veterans can answer 2 questions to learn how their income may affect VA health care eligibility and costs.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/health-care/income-limits/ and all subpages

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

None

### VA Email Address(es)

suzanne.middaugh@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if yo have any questions. Thank you.
