### ISSUE TITLE
Design: Revisit CAIA changes for FMP Claim Confirmation/ Email 

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#94011]
Review the latest comments left by CAIA on both the confirmation page and the email and make the necessary edits on the[ Figma File ](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=4715-17051&node-type=section&t=uuOdGTvXrqhXRABE-0)

**Comment by jamiefiore** [comment]
@baltes Here's the updated [Figma file ](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=4715-17051&node-type=section&t=uuOdGTvXrqhXRABE-0)for the confirmation page/ email. I dont think Mary had send this it over to the Engineers yet. It looks like the original design is what they used on Staging. Let me know if you want me to write out details instructions on what to update on this page.

**Comment by baltes** [comment]
@jamiefiore Sure, feel free to write that up for a backlog item if you have the bandwidth.
