### ISSUE TITLE
Qualitative Data Request - Outreach events and materials

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#94017]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2024

### Date Range End

09-30-2024

### Product Name(s)

Outreach and events

### Product Description

Users can explore resources for our outreach partners such as Veteran Service Organizations (VSOs), and view or sign up for events.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/outreach-and-events/ and all below, including
- https://www.va.gov/outreach-and-events/outreach-materials/
- https://www.va.gov/outreach-and-events/events/

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

None

### VA Email Address(es)

suzanne.middaugh@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. The last file sent includes the correct date for the data request. Thank you.
