### ISSUE TITLE
CT-EYB: Create and use Feature Flag for Profile 'Bottom Sheet'

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9403]
As a developer, I need to create a toggle for the Estimate Your Benefits Bottom Sheet, so that it can be enabled / disabled without requiring a deployment.

## Assumptions:
1. The Feature Flag is configured per environment.
2. When the feature flag is:
     a. Off: The "Estimate Your Benefits" section bottom sheet is not displayed.
     b. On: The "Estimate Your Benefits" section bottom sheet is displayed.
3. The feature flag `gibctEybBottomSheet` is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. A Feature Flag is available to be used for the Estimate Your Benefits development.
2. The Feature Flag name is: gibctEybBottomSheet
3. The Feature Flag description is: "Panel that displays while the user is modifying inputs to give context to their currently estimated benefits until they reach the full your estimated benefits panel."
4. The Feature Flag is defaulted to the OFF state in the DEV, STAGING and PROD environments.
5. The bottom sheet is not displayed when the feature flag is in the off state.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12844
backend PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4340

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-29 at 7.11.24 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a90462d9-4639-4f1c-9dc1-707b29210ca7)

**Comment by sonntag-adam** [comment]
[Uploading... Screen Shot 2020-05-29 at 9.54.35 AM.png ]

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-29 at 10.01.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a30d14a6-5c5c-467b-9916-585942a0d27d)
##
![Screen Shot 2020-05-29 at 10.01.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/32677105-cb97-4ef3-bb86-4ce49b78773d)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/417&group_by=cases:section_id&group_order=asc

**Comment by ksantiagomorgan6** [comment]
New pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12865

**Comment by sonntag-adam** [comment]
In staging, closing story
