### ISSUE TITLE
[3 pts left] [Discovery] How to recover when a text message fails on Travel Pay Submission

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#94038]
During the Zero Silent Failure investigation, it was revealed that we could have some in the Travel Pay integration. The zero silent failures comes from if the claim creation fails and the text message fails. 

This ticket is discovery on how we can mitigate this failure. 

## User Story

As a Veteran, I want to know that my claim creation has failed,  so that I can take actions to remediate that and submit my claim. 

## By the Numbers

>Date range:Jan 1, 12:00 am – Sep 30, 11:59 pm, ~9 months
47 failed text messages

we have logs for 24 (out of the window of log retention), all 24 the claims the claims were successfully made.

## Questions to answer
- [ ] How can track when both the claim fails and the text fails
- [ ]  Can we better understand the error to why the text message fails?
- [ ]  How can use VA notify to explore other avenues of notifications? 
- [ ]  Can we retry the text after a certain waiting period

## Acceptance Criteria
- [ ] Answers the questions
- [ ] Figure out next steps.

**Comment by loripusey** [comment]
@kristenmcconnell FYSA

**Comment by lee-delarm6** [comment]
Rough guess, 2 points @kanchanasuriya , what do you think?

**Comment by kanchanasuriya** [comment]
How can track when both the claim fails and the text fails
>> Currently, both claim & text failures are tracked in Travel Claims Datadog dashboard

Can we better understand the error to why the text message fails?
>> Text message failures are logged in Sentry with exceptions from VANotify API & can be further investigated to understand the failure reason.  

How can use VA notify to explore other avenues of notifications?
>> Currently, the text failure rate is 0.003% in the past 90 days.  We should be able to address the failure issue with a retry mechanism

Can we retry the text after a certain waiting period?
>> As of today, by default VANotify client has retry for Timeout, IOError, EOFError, CONNABORTED, EPIPE, or SSLError. However, we can add an additional retry level in the CIE Travel Claims module to retry the API call as part of this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96416).

**Comment by kanchanasuriya** [comment]
> Question: if VANotify already has a retry, why do we need to duplicate this effort. Are there errors that their retry will not address?
> 
> [@kanchanasuriya](https://github.com/kanchanasuriya) [@randomsync](https://github.com/randomsync) [@lee-delarm6](https://github.com/lee-delarm6) [@brianseek](https://github.com/brianseek)

Failure with VANotify is very rare and the current error rate is 0.003% over the past 90 days. An additional retry mechanism is just to ensure that even this failure is addressed, but we can leave it as it is if everyone agrees with the current low error rate.
