### ISSUE TITLE
Design: 10-7959-f1 Update FMP Registration form with Pre-fill

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#94032]
Add a Prefill flow to the latest versions of the Figma files for:

[FMP Registration](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=726-21596&node-type=canvas&t=AqKCNGZx3hMZVHT2-0)

Use the pattern established in the [FMP Claims Form](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=4338-135745&t=AqKCNGZx3hMZVHT2-4) as a reference. 

Things to consider:

What type of information can we pre-fill from their VA profile?
What types of information from the applicant's VA profile would be helpful to pre-fill?
What types of information from the applicant's VA profile would be confusing for an applicant to see prefilled? 
What content would be helpful to add to the messaging on the pre-fill alerts/messaging?

**Comment by rspope** [comment]
@baltes Please review and let me know if you see any issues.
https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=3274-34560&t=DyEnKSbLNTIRS21l-4

**Comment by baltes** [comment]
Thanks Rachel, lgtm
