### ISSUE TITLE
Improve load time

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9407]
Load speeds over different connections across devices

**Comment by batemapf** [comment]
Potentially causes accessibility, usability, trust issues.

**Comment by batemapf** [comment]
How much can we actually do about this if it is the platform stuff that is weighty?

**Comment by batemapf** [comment]
@Yuffster-usds now that we've got a decent bit of traffic to /covid19screen, does it make sense to start thinking about looking at page performance? if so, please either grab this ticket and move it over to In progress and assign yourself, or let me know if there is additional stuff needed to make this ticket actionable.

**Comment by batemapf** [comment]
first instance of page size potentially being a problem, from Baltimore VAMC: 

>Underground garages can be an issue with slow down but **also deceased cell service based on service provider**.

(emphasis added)

**Comment by batemapf** [comment]
some basic site speed data from GA: https://analytics.google.com/analytics/web/#/report/content-site-speed/a50123418w177519031p184624291/_u.date00=20200601&_u.date01=20200603&_.useg=&_.gSectionId=site_usage&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:~2Fcovid19screen~2Findex.html&_r.tabId=histogramTab/

**Comment by mchelen-gov** [comment]
possibly relevant: https://github.com/department-of-veterans-affairs/vets-website/issues/8391

**Comment by batemapf** [comment]
@Yuffster-usds ping @batemapf for help with access to GA.

**Comment by batemapf** [comment]
Slack convo link.

Three possible paths:
- platform load times
- getting React to render before everything gets done loading
- break out of the VA.gov platform framework / system (e.g. mobile-intentional design w/ minified header/footer; etc...)

**Comment by mchelen-gov** [comment]
https://github.com/department-of-veterans-affairs/vets-website/issues/8391

**Comment by mchelen-gov** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/1682

**Comment by mchelen-gov** [comment]
Super long slack discussion about this: https://dsva.slack.com/archives/CBU0KDSB1/p1593611301102000
