### ISSUE TITLE
Contact Center Review for Sitewide Public Websites - Find a VA Form

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#94089]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The Find a VA Form product provides the ability for Veterans et al to find VA forms, view the form's details, download a form in PDF format, and for certain forms, click a link to fill out the form online.

The product guide was edited as follows:

- Updated screenshots to reflect the change on Find a VA Form search results, and Form Detail Pages, specifically the ‘Form last updated’ field label, which is now ‘Form revision date’ and the date that displays is truly the forms revision (aka version) date.
- Added screenshot depicting error message when no search results are found to section ‘Major Issues & Error Messages’
- Added Table of Figures section, along with bookmarks/links.

### Launch Date
Previously launched. Product Guide updated due to field name change on Find a VA Form Search Results and Find a VA Form Form Details Pages.

### Version Number
v6

### Product Guide

[Find VA Forms Product Guide v6 2024-10-01.pdf](https://github.com/user-attachments/files/17281363/Find.VA.Forms.Product.Guide.v6.2024-10-01.pdf)
[Find VA Forms Product Guide v6 - 2024-10-01.docx](https://github.com/user-attachments/files/17281362/Find.VA.Forms.Product.Guide.v6.-.2024-10-01.docx)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @FranECross. Can you please attach the draft to this ticket? Thank you!

**Comment by starlow00** [comment]
Draft looks good. Sending for VEO review today.

**Comment by starlow00** [comment]
No changes from VEO. The working copy is attached here for future revisions. Thank you!
[Find.VA.Forms.Product.Guide.v6_SRT_10072024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE5GQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da3052d22b83a7f0822b438e3a50a78e2444337b/Find.VA.Forms.Product.Guide.v6_SRT_10072024.docx)
