### ISSUE TITLE
CT-103: Staging modal persists on browser navigation

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9408]
Steps to reproduce

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Search on College of Charleston
3. Select College of Charleston on results page
4. Scroll down on profile page and select Protection against late VA payments and modal displays
5. Select back on the browser to go back to search results page
6. Observe the modal is still there
7. Select back again
8. Observe modal still displays

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/82574451-2a27d380-9b55-11ea-91e7-53f7f4db1d00.gif)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12755

**Comment by sonntag-adam** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/82931933-a6575800-9f55-11ea-8ec8-b83b00748b50.gif)

**Comment by sonntag-adam** [comment]
In staging, closing story.
