### ISSUE TITLE
Account Creation API: Align stakeholders around consistent UX

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#94098]
## Description

Now that the code for the account creation API is available and our team has been able to look at it to assess our understanding of the API's architecture, we have validated how the MHV-on-VA.gov portal will receive errors from the API (if they occur) and what alert messaging users in those scenarios will need. However, this work is not only relevant on the MHV on VA.gov landing page - there are many side-door entry points directly to the affected tool applications themselves, so Veterans coming in through those paths will also need to be informed. And the VAHB app uses the VA.gov sign-in flow.

We suggest creating shared alert components that the other affected apps can grab & implement in their own applications, but we'll need OCTO to make a decision on a common user experience that we want to implement when/if these errors occur. In order to help them make this decision, we need to: 
* diagram routing options and use cases
* present ux options to the affected tool POs (medications, secure messages, medical records) 
* draft an implementation strategy for Cartographers and affected app teams
* implement the strategy 

This ticket is focused on the first bullet: presenting UX options to the affected tool POs

### User story

As a Veteran, I want to clearly understand why I am receiving an error or am not able to access certain tools within My HealtheVet so that I understand how to take steps to recover from those errors in a consistent way across the experience.

As a Cartography team member, I want to align VA.gov stakeholders for MHV-ID-dependent products around an approach to alerting their users about issues with the MHV account creation API, so that Veterans can experience a consistent and informed experience across VA.gov and the VAHB app when there is an issue with the API.

### Notes
- [Account Creation API architecture mural here ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?sender=uf94a77a19aaf687331c09367)
- [Alert designs](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=0-1&node-type=canvas&t=pJFR7uJv6AmiPHLp-0)
- [Documentation of Account Creation API overview + decision options for POs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/account-creation-api.md)

Possible tasks:
- [x] Ask affected tool teams to report how they are currently handling users w/o an MHV-Identifier (or - if applicable - what route guards are doing)
- [x] Document the Account Creation API work at a high-level & diagram the logic
- [x] Outline routing decision options for POs of affected tool teams 
- [x] Schedule a sync with affected app POs and any stakeholders who should be aware of the Account Creation API purpose/scope/ux impacts at a high level
  - Medications: Kaitlin Fink 
  - Medical records: Marci McGuire
  - Secure Messages: Patrick Bateman
  - VAHB: Don McCaughey (for visibility - their implementation details & alert content will need to be different since they don't support medical records on the app) 
- [x] Schedule sync w/ engineering team responsible for account creation api. Bring questions.
- [x] Present the API at a high-level and a diagram for routing options
- [ ] Get clarity from POs on clear next steps to get this work incorporated into roadmaps as part of PI planning in early January

## Acceptance criteria
- [x] Important information has been shared with stakeholders in a meeting (Kaitlin, Robyn, and affected tool/app team POs)
- [x] Stakeholders have had a chance to review the documentation, provide feedback, and share any relevant information about how to work with their PI planning processes to get this work prioritized in January 2025. 
- [ ] We are prepared to move on to the next ticket: drafting the implementation strategy

**Comment by wesrowe** [comment]
We're probably not ready for this.
Still need discovery: is there a "pending" state in API/redux state?

**Comment by sterkenburgsara** [comment]
Update: Laura will be on PTO in the next sprint, but I stubbed out a CAIA ticket for her to help us draft alert content when she returns, likely second week of November. 

[Ticket here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96184)

**Comment by fmccaf1** [comment]
Question from sprint planning: 
Is there a pending state? Or is it a simple Y/N

**Comment by sterkenburgsara** [comment]
Update: Daniel + Sara synced on this on Friday 9/7. Spun up [Slack canvas](https://dsva.slack.com/docs/T03FECE8V/F080HK4F997) on this effort to capture conversation. Per @dcloud - no pending state will be available. 

Also: Slack convo within that Canvas linked above ([specific convo link here](https://dsva.slack.com/archives/C080HK4F997/p1731104923929129)) indicates need for UX to cover alert plan for additional scenarios where API fails due to system errors, and potentially specific SM scenario where user cannot get access due to eligibility issues. Confidence in these solutions will require outreach to the affected tool teams & MHV Access + Portals team for broader conversation.

**Comment by sterkenburgsara** [comment]
Per standup, moving this ticket back to Ready column to wait until the current ticket "evaluate API in staging" is unblocked and can be finished. Things are changing w/ the API implementation as identity team continues w/ testing in prod & we would rather wait for those updates to happen & provide feedback at that point.

**Comment by sterkenburgsara** [comment]
Update: Stakeholder sync took place on 12/16/24 at 5pm ET but only Don McCaughey (VAHB mobile app) was able to attend. @wesrowe has scheduled a follow-up to try and get the stakeholders who missed the first session on Thursday (12/19).

**Comment by mcarterA6** [comment]
@sterkenburgsara @wesrowe  - I think majority of this work has been done for this ticket. Can we make a sub issue to carry into the next sprint for maybe 1-2 points to account for the remaining work?

**Comment by sterkenburgsara** [comment]
@mcarterA6 Yes, the outstanding items are: getting clarity on next steps for working with PI planning timelines across teams & communicating this work clearly w/ all affected health tool POs. 

I will write up a smaller spike ticket to complete the stakeholder shareout sessions in a more ad hoc fashion since our scheduled times didn't work out as expected. Closing.
