### ISSUE TITLE
Integrate Cypress tests with TestRail

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#9409]
## Overview

There is a Cypress plugin that will allow test runs to report their results to TestRail test cases.

[cypress-testrail-reporter](https://www.npmjs.com/package/cypress-testrail-reporter)

[Slack discussion](https://dsva.slack.com/archives/CQH357ZTP/p1590072472195900)

**Comment by meganhkelley** [comment]
@JoeTice @pjhill passing to your team, feel free to close if this is duplicative of tickets you already have for this work

**Comment by pjhill** [comment]
> @JoeTice @pjhill passing to your team, feel free to close if this is duplicative of tickets you already have for this work

Thanks -- this has been completed under another ticket. Closing this
