### ISSUE TITLE
VA Notify Business intake form for Pension and Burial team

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#94099]
## Your Details
1.  Matt Reilly
​
2.  **Business Line**
    Pension and Burial forms delivery team
​
## Notification Details
1.  **Notification type**
    (email)
​
2.  **Please describe your use case.**
   I am a Product Manager on the Pension team and we are looking to create some zero silent failure notifications mimicking work that Jeana Clark of the Veteran Facing forms team did.  See [thread](https://dsva.slack.com/archives/C044AGZFG2W/p1727811633182579).  Looking to access VA Notify and make copies of Jeana's notifications to create Pension specific versions.
​
3.  **What actions can the user take based on the notification they receive?**
  Drives awareness of failed submission and provides next steps to the applicant.
​
4.  **What is the desired business outcome?**
  Applicant awareness of failure and how to proceed.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    Lighthouse failures and associated monitoring.
​
6.  **What will trigger the notification?**
    Lighthouse failures and associated monitoring.
​
7.  **Provide sample content per notification type, if you have it.**
    We'll leverage/copy the ["Action Needed" template](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/VA-notify-email/3-action-needed.md) created by the Veteran Facing forms team in VA Notify (see image below)and customize it to create a Pension-specific form and a Burial-specific form. Map pension specific elements as identified in the template. Design system visual example of the Action needed template can be found [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).

The Action needed notification as there is an 11/12/24 deadline associated with it for the Zero Silent Failures Initiative.

Template Details from VA Notify staging environment:
1. Pension form
Template Name: 21P-527EZ – Action Needed Template
Template ID: ea0cae3a-3638-4524-8042-7259ebb0c437

2. Burial form
Template name: 21P-530EZ – Action Needed Template
Template ID: f78126ea-eab3-4ff7-a4e0-b77d31a93904
--

We have a related future goal to create a Submission in Progress and Received email later this year.  See those design templates [here](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Design/patterns/Application%20status/VA-notify-email)

​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (Our PO is Dene Gabaldon)
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., we'll provide email submitted in the pension application.)
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (No)
​
11.  **What is the anticipated volume of notifications per day, week, month?**
Low volume, associated with zero silent failure scenarios
​
12.  **When does this notification need to be in production?**
11/12/2024

**Comment by GitSamJennings** [comment]
Hi @matt4su! Does your team currently utilize VA Notify? If so, are you needing more folks added to your Service? Additionally, VA Notify is working on adding the 3 new sample templates that Jeana's team provided us to our VA Notify Sample Templates. Until they are implemented this sprint, folks are welcome to copy/paste them into our Editor. The templates are provided here: https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Design/patterns/Application%20status/VA-notify-email

**Comment by GitSamJennings** [comment]
@matt4su I wanted to circle back and see if anything more was needed on this intake or if your team has everything. Thanks!

**Comment by matt4su** [comment]
@GitSamJennings  @mjones-oddball We are ready for this to move forward, there may be some small tweaks but we are ready to go.

**Comment by GitSamJennings** [comment]
@matt4su do you need anything from VA Notify, before I close this out?

**Comment by matt4su** [comment]
I believe the only thing we need at this point is for the below templates to be pushed to production.  Assuming we can make small tweaks after that if needed.

Pension form
Template Name: 21P-527EZ – Action Needed Template
Template ID: ea0cae3a-3638-4524-8042-7259ebb0c437

Burial form
Template name: 21P-530EZ – Action Needed Template
Template ID: f78126ea-eab3-4ff7-a4e0-b77d31a93904
--

**Comment by GitSamJennings** [comment]
Perfect, feel free to push to production, when you feel ready to do so and we will be here, if you have any additional questions.

**Comment by matt4su** [comment]
Suggest closing  this ticket at this point

**Comment by mjones-oddball** [comment]
@matt4su is your notification launch date still 11/12?

**Comment by aplatt-coforma** [comment]
@mjones-oddball - we are on track with that deadline date. cc @matt4su
