### ISSUE TITLE
10-10d: Ensure flipper shows correct content for both conditions

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94101]
As a user accessing the CHAMPVA application form on production, I need to see the correct content based on whether or not the flipper lets me through to the digital form.

### Acceptance criteria
Given a user arriving at the static page for CHAMPVA
- When the user is allowed through to the digital form by the flipper
   - Then the user should be taken to the digital form that they can submit online
- When the user is allowed through to the digital form by the flipper
   - Then the usr should be taken to the PDF form that they can download

**Comment by rmessina1010** [comment]
Leaving this note, as am rolling off the team.  I believe the task here ( and in similar issues) is much the same as in 10-7959f-1.
1) Confirm with CAIA about the static page
2) Add redirect to app, as necessary

**Comment by michaelclement** [comment]
@baltes To confirm, this is referencing the production environment, correct? That means this ticket will have to take place [after 10-10d has been enabled in production](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/94133). Just want to verify the order the tickets go in.

**Comment by baltes** [comment]
Thanks Ray! Closing this ticket out, remaining work is covered by [10-7959f-1: Feature toggle for staged release](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/94344)
