### ISSUE TITLE
CT: "School Locations" accordion is taller than the others.

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9411]
Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11905103
Scroll down to the "School Locations" accordion and observe that it's taller
Occurs on all screen sizes
##
![Screen Shot 2020-05-21 at 11.41.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/95773995-c398-4043-bc65-85aa83c210bc)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12756

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-21 at 3.41.23 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/34265b06-62be-41a7-abcf-5626fbc06580)
##
![Screen Shot 2020-05-21 at 3.41.35 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e2b81f05-76b4-4ef6-913d-f42b8fceafec)
##
![Screen Shot 2020-05-21 at 3.41.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/21e640c7-47e3-49b4-bab2-81136c682150)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I reviewed and this checks out.

**Comment by sonntag-adam** [comment]
Closing bug
