### ISSUE TITLE
[526/4142 Email] Trigger an email after backup path LH Benefits Intake API has exhausted

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#94128]
As a user, if I submitted a disability claim that appeared to be successful when I submitted it online, but the system failed to produce the end results, I want to be notified (via email) that I need to take action in order to get my claim processed. 

The solution must solve for when the 526 document is considered a failure and there are no more attempts to deliver it to eFolder (VBMS). 

- [ ] Trigger the email when the retries on the backup path LH Benefits Intake API has been exhausted. 
- [ ] Polling is required
- [ ] DD monitoring (see [526 Email] Datadog monitoring/dashboard[#94165](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94165))
- [ ] - [ ] [Design specs with elements](https://www.figma.com/design/TZ23k4X5tnh3lFlehYER3f/526-Post-Submission-Failure-Notification?node-id=557-288638)

**Validations**
- Validate that no email is triggered if the the API is successful (VBMS if that is possible) 

**Dependencies**
- R&D Email Template  

**Resources**
- [Va.gov Benefits forms - Normal backup emergency flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?sender=ua8d1f105fba69675aba15464)
- [Zero-Silent-Failures-Checklist-.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/investigations/Disability%20526-%20Zero-Silent-Failures-Checklist-.md)

**Comment by nnicholas7** [comment]
An email template has been created in VA Notify entitled '526- Silent Failure Email'. The Staging Template ID:
a4b5df4f-6f29-4b0d-a61e-fb02e1ebdb40.

**Comment by nnicholas7** [comment]
Nathan, if you need help with the trigger in VA Nofity, please contact folks in the VA Notify see [Slack message](https://dsva.slack.com/archives/C010R6AUPHT/p1727978556440579) for details
