### ISSUE TITLE
Write conversation guide for research

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#94135]
### User story

As a Cartography team member, I want to define the direction of our next user research study, so that we can get it started.

### Notes
- [Link to conversation guide info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
- [Link to research plan in Sharepoint](https://dvagov.sharepoint.com/:w:/r/sites/HealthApartment/Shared%20Documents/General/Portal%20research/Fall%202024%20Portal-wide%20research/Research%20plan%2010-24.docx?d=w93b8b753830c4187bc4c58a925fc487c&csf=1&web=1&e=R6Zozt)

## Acceptance criteria
- Robyn gives the go-ahead for the conversation guide

**Comment by jonathanjnelson** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/research/adoption-study/conversation-guide.md
