### ISSUE TITLE
Discuss code reuse strategy with Platform team

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9413]
Meet with platform team to evaluate code reuse options.

Options to evaluate:
- Use [wizard](https://design.va.gov/patterns/wizards) pattern
- Use [VAFS](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/) / [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) 
- Use 3rd party library such as https://formio.github.io/formio.js/
- Publish our component to [Formation](https://design.va.gov/documentation/contributing-to-formation#how-to-contribute)
- Contribute to [content](https://design.va.gov/content-style-guide/) or [design](https://design.va.gov/design/) guides

Some discussion: https://dsva.slack.com/archives/CBU0KDSB1/p1589295104425000

**Comment by mchelen-gov** [comment]
wrote up summary of options in issue text

**Comment by batemapf** [comment]
pinged platform re: a meeting about this.

**Comment by mchelen-gov** [comment]
meeting set up for Friday @ 2pm

**Comment by mchelen-gov** [comment]
opened https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/192

**Comment by batemapf** [comment]
@batemapf to either add that ^^^ repo to this board and track ticket or create our own ticket to track it.

**Comment by batemapf** [comment]
Now tracking vets-design-system-documentation#192 on our ZenHub board.
