### ISSUE TITLE
10-10d: Prod deployment

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94133]
As a member of the IVC Forms team, I need to begin smoke tests for 10-10d in production

### Acceptance criteria

- Feature toggle is implemented so that all traffic to the form will see a "we're still working on this form" (or similar) message until traffic is allowed via the Flipper admin
- The form is available in production to traffic once allowed by the Flipper admin

**Comment by michaelclement** [comment]
Set 10-10d to go to production in [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/2310) (the form is behind a feature toggle, so nothing will be exposed). Waiting on:
- [X] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
Platform approved and the PR was merged in. 10-10d will be hidden behind the feature toggle, live in production after tomorrow's deploy.

**Comment by michaelclement** [comment]
[10-10d is live in production](https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/apply-form-10-10d) - hidden behind a feature toggle.
