### ISSUE TITLE
Contact Center Review for Disability Benefits Experience Team 2 - post submission 526 failure email notification

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#94155]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

### Launch Date
*Please provide the launch or rollout date and details.*

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
*Please provide product guide link*

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @lisacapaccioli. Can you please attach the draft to this ticket? Thank you!

**Comment by lisacapaccioli** [comment]
@starlow00 Sorry for any confusion, This is just in our backlog right now, @nnicholas7 and @rubensun are working on the drafts. We'll keep you updated.

**Comment by starlow00** [comment]
Sounds good, thanks @lisacapaccioli

**Comment by nnicholas7** [comment]
Here is the information to complete the ticket above:
Description
Please provide the name(s) of your product and a high-level description of your product.


Our team is currently working on the 526 Post-Submission Failure Email. When Veterans submit an online disability claim the form itself, ancillary forms (ie. forms 4142 and 0781), and supporting documents (ie. evidence) can fail to upload to the back end. To ensure that Veterans understand the status of their disability claim and next steps, we are sending emails to affected claimants to instruct them about the submission failure and how to proceed.
Launch Date
Please provide the launch or rollout date and details.


The 526 Post Submission Failure Email will be launched by November 15, 2024.
Version Number
Please provide the version number of the guide and/or video.


[526 Product Guide Version 4.4](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B7F2ED09A-E738-42EE-BEDA-D6307A3028C6%7D&file=526EZ.Disability.Benefits.Claims.Product.Guide.v4.4.-SRT_10212024.docx&action=default&mobileredirect=true)

[526 BDD Product Guide Version 3.4](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B9D7330E4-1979-4A67-A347-B55A28ED3423%7D&file=526.Benefits.Delivery.at.Discharge.v3.4.product.guide_SRT_092724.docx&action=default&mobileredirect=true)

Product Guide
Please provide product guide link

Product Video
Please provide product video link


No product video.
Product Video Transcript
Please provide product video transcript link


No product video transcript.

**Comment by nnicholas7** [comment]
This ticket has not been submitted yet, we are awaiting a screenshot of the most up to date email, which we are currently making changes to from the CAIA feedback. Can probably use a screenshot from VA Notify.

[526 Failure Email Product Guide Update](https://docs.google.com/document/d/1lGOqo1pKGe-PRXhVGI6MpUYAWXeSvBy4UV1l4Xf9ewA/edit?pli=1&tab=t.0)

**Comment by starlow00** [comment]
Hi @lisacapaccioli and @rubensun. I can't tag Nichole directly through Zenhub, but I need a draft of the last guide she posted attached to this ticket as a Word file (not as a Google or Microsoft link). Hoping someone can assist so I can put it through the review process. Thank you!

**Comment by lisacapaccioli** [comment]
@starlow00 - Not sure how she normally gave it to you, but does this work? 
[526 Failure Message-Product Guide Update.docx](https://github.com/user-attachments/files/17578636/526.Failure.Message-Product.Guide.Update.docx)

**Comment by starlow00** [comment]
It does. Thank you, @lisacapaccioli :)

**Comment by starlow00** [comment]
Failure message draft looks good, sending for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. A working copy is attached for future updates. Thank you!
[526.Failure.Message-Product.Guide.Update v1 SRT 10302024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90ee38daac9d77e89f9ba6857e175d8a2d3fb4de/526.Failure.Message-Product.Guide.Update%20v1%20SRT%2010302024.docx)

**Comment by lisacapaccioli** [comment]
@rubensun - If you get a new screen shot with the small format changes will you please update the Product Guide and upload a copy to this ticket? Thanks

cc @starlow00

**Comment by christinec-fftc** [comment]
@starlow00 Were these documents (noted [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94155#issuecomment-2435359776)) updated as part of this ticket? Is it possible to get the final versions of those? Want to make sure I'm building the next versions off the latest. Thanks!

![Image](https://github.com/user-attachments/assets/1eb0ff3c-55b8-48c8-bb09-f6bab00e7041)

**Comment by christinec-fftc** [comment]
Copies of the latest product guides from @starlow00 
[526.Benefits.Delivery.at.Discharge.v3.4.product.guide_SRT_092724.docx](https://github.com/user-attachments/files/17852905/526.Benefits.Delivery.at.Discharge.v3.4.product.guide_SRT_092724.docx)
[526EZ.Disability.Benefits.Claims.Product.Guide.v4.4.-SRT_10212024.docx](https://github.com/user-attachments/files/17852904/526EZ.Disability.Benefits.Claims.Product.Guide.v4.4.-SRT_10212024.docx)
