### ISSUE TITLE
10-7959f-2: fix react widget/feature toggle 

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#94150]
As a user accessing the FMP registration form on production, I need to see the correct content based on whether or not the flipper lets me through to the digital form.

###Task
Remove toggler  logic  (WIC) from 10-7959f-2 app
The toggle should occur in the static-app, logic already in place.
Follow changes as performed for [10-7959f-2, here.](https://github.com/department-of-veterans-affairs/vets-website/pull/32184)

###Acceptance criteria
Given a user arriving at the static page for FMP registration

When the user is allowed through to the digital form by the flipper
Then the user should be taken to the digital form that they can submit online
When the user is allowed through to the digital form by the flipper
Then the usr should be taken to the PDF form that they can download

**Comment by rmessina1010** [comment]
PR in [progress here](https://github.com/department-of-veterans-affairs/vets-website/pull/32218)

**Comment by baltes** [comment]
Closing this for now, we'll revisit once we find the right pattern going forward.
