### ISSUE TITLE
[Development] BDD Military Service History Wording

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#9418]
## Issue Description
The Military Service History page in BDD should be adjusted so its language more accurately describes users who do not have previous military history. This is necessary because users filing BDD frequently have no past military history imported.

![image](https://user-images.githubusercontent.com/53942725/82586181-28fea280-9b65-11ea-8494-ce4953477073.png)

## Tasks
- [ ] Work with design to adjust Military Service History page language to explain the situation better

## Acceptance Criteria
- [ ] Military Service History page text makes sense in all contexts of previous history

**Comment by kevinstachura** [comment]
"Please add your military service history details below."
