### ISSUE TITLE
Newsletter UAT 

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#9420]
UAT steps: 
1. Signup to newsletter https://mailchi.mp/334fcd88fdc3/va-platform-newsletter
2. Get email
3. Read content
4. Click on links

Please add a comment with feedback on the following areas:
- Signup and email experience
- Content
- Design
- Calls to action
- Anything else? 

Feel free to use the do/try/consider framework.

**Comment by rroueche** [comment]
This is awesome y'all! First piece of feedback: the signup page doesn't say anything about signing up to beta test the newsletter, instead it looks more

**Comment by KevinMHoffmanUSDS** [comment]
Good morning, @jchasia-adhoc and @naomimarcussen! 

On the UAT side

1: Successful at completing the form. 
2 and beyond: did not receive the e-mail after 3 attempts. The 

Feedback (will add more when I recieve

* Signup and e-mail experience
	* The resolution on the VA logo is too low, and looks pretty bad on a monitor. 
	* There needs to be something on the sign up page about what the newsletter and the platform is. 
	* “This newsletter provides monthly updates to teams building applications for Veterans on the VA.gov platform, including new features and tools, changes to our systems, and other key information.” 
	* +1 to Rachel’s comment regarding announcing it’s a beta test on the sign up page. 
	* 3 attempts, I didn’t receive the email
	* Mailchimp has a setting/message option for "You've already subscribed." Is this not enabled? 
* Content
       * Need to get the message. :)
* Design - Illustration style
	* Let’s pick illustration/images that convey the following themes
		* Support, bridge, service, group collaboration, concierge, gifts
https://unsplash.com/s/photos/support
https://unsplash.com/s/photos/bridge
https://unsplash.com/s/photos/service
https://unsplash.com/s/photos/working-together
https://unsplash.com/s/photos/concierge
https://unsplash.com/s/photos/gift
https://undraw.co/search (has some good results for the above terms if we want to stick with this style)

We can also recolor these as per the design system for a simple, sustainable approach
https://thenounproject.com/search/?q=support
https://thenounproject.com/search/?q=bridge
etc.


	* Let’s avoid the following themes
		* Clean up, helping, fixing, gateways, checkpoints, approvals
* Calls to Action
       * Need to get the message. :)

**Comment by rroueche** [comment]
Got the newsletter this morning, woohoo!

Additional pieces of feedback:

- Since I imagine you'll give ppl x days to sign up and then will send the beta newsletter to all of them at once (as opposed to ppl receiving the newsletter immediately upon entering their email address), indicate that on the beta sign up page. Along the lines of "hello, we're going to send a beta test of our forthcoming platform newsletter on May 25th. Sign up if you'd like to be a beta tester." Something like that. Here's some inspiration for language around beta testing and beta users: https://beta.apple.com/sp/betaprogram/
- This feedback I believe will require action from @gmaciolek and @brandonrapp: the description on the [product brochure](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/service-design/product-brochure-automated-frontend-code-reviews.md?mc_cid=a00d95c3b6&mc_eid=2bab966d79) needs to speak more to how this tool is meant to help users. For the "What is it" part of the brochure, here's the language I recommend instead: ```Automated code quality checks that run directly in Jenkins (?) so you can iteratively see issues and update your code on your own as you go, allowing you to move faster and bypass reviews from platform engineers when they're not necessary. These checks use an automated process that looks for code additions and modifications that don't meet baseline code quality criteria, and will alert a platform engineer to help out and do a review only if certain more complex issues are found.```

**Comment by emilywaggoner** [comment]
Hello everyone! Here is my feedback:

### Sign up page and process
- [X] UAT: Sign up to newsletter

#### Feedback
- The VA seal logo looks a little pixelated. Let's swap in a higher res version, or an SVG if there is one. (I can help find out, let me know)
- "latest news" - It doesn't feel quite right to call this the "latest news" from Platform. The latest is really happening in Slack, but this is a less frequent, more organized, strategic communication about our objectives and progress. Let's try and communicate that instead.
- Success message - consider adding an expectation of what to happen next. _You'll be prompted to confirm your email address._ Or _you'll get your first newsletter next week._

### Get email
- [X] UAT: Received email

#### Feedback
It took much longer than anticipated to get the email - I thought it would be immediate, or at least have a confirmation email come through immediately.

### Read content
- [X] UAT: Read content

#### Feedback
- 3 stories/items seems like a good place to start, and I wonder what you imagine the maximum amount to be. (Or will it always be 3?)
- I think there should be 1 primary call to action per newsletter item. So just one button, and anything else is a text link.
- The "eyebrow" labels work well - "New release" and "Coming soon" - those are useful bits of contextual info
- Fonts: Source Sans Pro for the first heading works well and is consistent with the design system, but that font doesn't carry through to the body or button text. Could it?
- "Share your thoughts" - I think this call to action text should be customized to each newsletter item. What kind of thoughts are we looking for? 
- For the 2nd and 3rd newsletter items, are there are any other artifacts we could link to? We could consider having the primary call to action be something like, "follow along on Zenhub here" or "here is the product outline" and asking for thoughts/feedback be the secondary call to action.

### Click on links
- [X] Clicked on links, they all worked

#### Feedback
- It was surprising to have the "Share your thoughts" link open in Slack (even though thinking back, I knew this was the plan). It felt a little jarring and unexpected. I think setting the expectation in the link text would be an improvement: "Share your thoughts in the #xyz Slack channel".
- Consider renaming the channel where you want to receive the thoughts/feedback. Even though the description of the channel says "Questions and feedback related to the platform newsletter" the `vsp-` prefix makes it feel like the Slack channels where VSP folks are communicating about work. Maybe something consistent with the newsletter name, like #platform-newsletter-feedback.
- For some reason, only the text of the CTA buttons is clickable. The whole shape should be clickable if possible.

**Comment by KevinMHoffmanUSDS** [comment]
Final UAT 
UAT steps:

- [ ] Signup to newsletter https://mailchi.mp/334fcd88fdc3/va-platform-newsletter
- [ ] Get email
- [ ] Read content
- [ ] Click on links

Please add a comment with feedback on the following areas:

### Do

Content
Design
Calls to action

### Try

Content
Design
Calls to action

### Consider

Content
Design
Calls to action

**Comment by Khyatinp18** [comment]
2/21/2022:
This issue is no longer needed since Newsletter is deprecated.
