### ISSUE TITLE
[Development] BDD Payment Information Alert Box

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#9421]
## Issue Description
In the BDD form, the Payment Information alert box should have its wording adjusted to more accurately represent users who are entering banking info for the first time.

![image](https://user-images.githubusercontent.com/53942725/82589084-9f050880-9b69-11ea-9746-5eed61c94f23.png)

## Tasks
- [ ] Work with design to adjust Payment Information alert box text

## Acceptance Criteria
- [ ] Payment Information alert box wording should more accurately represent users without prefill banking information

**Comment by kevinstachura** [comment]
For first time bank account additions, remove the last sentence that says "your current payments will continue to be deposited into the previous account we showed."
