### ISSUE TITLE
Loading page content changes

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#94220]
## Issue Description
As a Veteran, I want my expectations to be set for the amount of time I should wait while my application is being submitted so that I am not left wondering how long this will take to process. As a Veteran possibly using accessible technology to access the site, I need this to be compatible with my AT devices.

The new copy reads "This may take up to 30 seconds. Please don’t refresh the page." However, always check the Figma file for the most up-to date designs.

This spinning wheel is accessible and will not confuse AT users. Coupled with the new copy, this screen sets better expectations for Veterans. They know the screen is loading and have greater confidence in what will happen next.

For reference the Figma design file for this feature is [here](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-Submission-Experience?node-id=34-73279&node-type=canvas&t=ApNRPKRTgXAYAMBh-0).

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] The spinner is kept on Loading page, with no visible changes made
- [ ] The copy is also updated on the page to reflect the designs

**Comment by pacerwow** [comment]
@StevenStraily @mayacarrolluxa6 @christinec-fftc 
- What will the experience be like for Veterans who have applications that immediately fail? Will we show the progress bar?

**Comment by mayacarrolluxa6** [comment]
@pacerwow The progress bar displays while the application CESTs in the background. If the CESTing process never starts, the veteran would immediately see the generic error page.

**Comment by pacerwow** [comment]
Closed as a dupe, replaced by #95230
