### ISSUE TITLE
[Design] Update DD Header

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9423]
## Background

The current direct deposit header is very long - especially on mobile. We need to update the copy (if possible) so it's not so long.

Epic #2086

## Current copy
![Screen Shot 2020-05-21 at 10.01.21 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/c5dce00b-0b55-415c-821c-16a63656ab2e)

Direct deposit information for disability compensation and pension benefits

## Tasks

- [x] Update copy
- [x] Implement correct copy.

## Acceptance criteria

- [x] All mocks have been updated

**Comment by peggygannon** [comment]
Hi, @tressaellen Yes, let's update to: 

Direct deposit information for disability and pension benefits

**Comment by tressaellen** [comment]
Hi @peggygannon is there anyway we could have the title be shorter and then some smaller clarifying text underneath? The title still seems really long and will take up a lot of screen space. Something like:

**Direct deposit information** 
The bank account information you input is where you will receive your disability compensation and pension benefits.

Or we could do a drop down below the title that says something like:

What services would this account information be used for?

What are your thoughts?

**Comment by peggygannon** [comment]
@tressaellen Yes, I will update... . A followup question: 

Will a user's bank account information always be populated on this screen? or will some users be coming to this screen and entering their DD/banking information for the first time? 


Also, 
I'd want to recommend that if we're adding a line of intro copy to the DD screen, that we do the same for other profile 2.0 screens. This might be a good solution to help users understand all the elements/infor on the page. 

Let me know your thoughts?  If you agree, I will then through the updated mock and suggest a line or two of intro content for the other screens.

**Comment by tressaellen** [comment]
Great question @peggygannon , some users will be coming to this screen and entering their DD/banking information for the first time. Which is ticket #8757 - so that's definitely something we can work on now. 

As far as the adding intro copy...Connected apps already has some intro copy... but other than that I think the other pages (Personal and contact information, military information and Account security) are pretty self explanatory...I'm definitely open to adding it if you feel like the page needs it for clarity. I just don't want to add clutter if it isn't needed.

**Comment by peggygannon** [comment]
hi, @tressaellen ok, thanks! Here is a recommendation for the DD screen. 

**Direct deposit information**
The bank account you enter here is where we'll pay your disability compensation or pension payments.

**Comment by Samara-Strauss** [comment]
I'd like to submit the following for approval. Thoughts?

- Shortened heading to Direct deposit information
- Replaced "Bank account" heading with "Disability compensation and pension benefits"

![Direct deposit_heading update](https://user-images.githubusercontent.com/34068740/82681298-95d47400-9c1b-11ea-982f-118235382e28.jpg)

If we wanted, we could also create a callout for the edu benefits like so, but this is a separate problem from the heading and definitely NOT something we have to do if we don't want to:

![Direct deposit_add block for edu](https://user-images.githubusercontent.com/34068740/82681406-b56b9c80-9c1b-11ea-91a8-befdb9d0834c.jpg)

**Comment by peggygannon** [comment]
Hi, @Samara-Strauss I like it. I think this works. It's allows for a more comprehensive page, showing users all the options for updating DD information. (even if they don't have EDU benefits).

**Comment by tressaellen** [comment]
@Samara-Strauss sorry to be late to the game - but I think this is a great idea!

**Comment by Samara-Strauss** [comment]
Awesome! Feel free to take it from here. Didn't mean to hijack your ticket :) It's totally up to you how you want to adapt the idea from here.

**Comment by tressaellen** [comment]
I still think this is a great approach - the only change I made is switching the term 'sign in' to 'log in'

![Screen Shot 2020-05-28 at 3.07.47 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/85364dfe-480d-4f3a-a1f3-9c1abe46f6d0)

**Comment by tressaellen** [comment]
Edit: I misremembered that correct content patterns - I am changing 'log in' back to 'sign in' to comply with the content style guide.
