### ISSUE TITLE
Profile 2.0 mobile nav trigger is broken

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#9425]
Sometimes in the past few days or week the mobile nav trigger button broke.

- clicking it no longer opens the mobile nav
- the trigger is no longer sticky as you scroll down the page

Maybe something about the change to server Profile 2.0 at the `/profile` route broke something with the CSS? That's the only thought I have at the moment.

**Comment by sanlouise** [comment]
@mshea0606 This ticket is ready for validation whenever you have a moment :)
