### ISSUE TITLE
"Edit" functionality for rep accordion in Review page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94256]
## Background
The Review page has been mostly built out in https://github.com/department-of-veterans-affairs/va.gov-team/issues/91411 but we still need to include functionality for the "Edit" button on the accredited representative accordion.

Currently, the team's ideal UX is to take the user back to the accredited representative chapter so they have an opportunity to not only select a representative, but an organization and also see the confirmation screens for contacting the rep and (if applicable) a heads up that their current rep will be replaced.

And then bring the user back to the Review page after they have completed the applicable steps in the Accredited Rep chapter.

There is an example in the 10-10 form to draw from. We'll need to consider how to manage states in local storage.

Implementation notes:
1. Pre-populate the initial search (and related results) in the rep selection screen -- this is already in place, but just confirming the expectations.
1. If the user doesn't change their representative, the "Back" and "Continue" buttons will redirect back to the Review page.
2. If the user does change their representative, have them step through the representative chapter as originally planned. After the chapter is complete (there's some conditionality here based on the selected rep), bring the user back to the Review page.

## Tasks
- [ ] Implement the logic above, for bringing the user back to the Accredited Rep chapter from the Review page.

## Acceptance Criteria
- [ ] If a user wants to change their rep, when originally on the Review page, they are brought back to the first chapter to make those changes.

**Comment by oddball-lindsay** [comment]
May need to make a small change, but can add that commit to the same PR.

**Comment by oddball-lindsay** [comment]
Failing CI test, so may need to bring this back to In Progress to correct, before design review.

**Comment by oddball-lindsay** [comment]
@mtri ready for you!

**Comment by mtri** [comment]
- @cosu419 Is it possible for the back button on the initial select page to go back to the review page after tapping edit?
- Noting there’s no way anymore to go back to the “Are you the Veteran?” question since the back button is disabled on the select step. I think this may be okay, that question is cut and tried and I can’t see someone having to edit their selection, but I’m not sure platform governance would agree.

Based on response to above I can create a QA ticket or not. Everything else seems good.

CC: @oddball-lindsay

**Comment by oddball-lindsay** [comment]
>Noting there’s no way anymore to go back to the “Are you the Veteran?” question since the back button is disabled on the select step. I think this may be okay, that question is cut and tried and I can’t see someone having to edit their selection, but I’m not sure platform governance would agree.

I think I agree that there isn't a likelihood someone would need to go back and edit that selection, that question seems pretty straightforward and it is also in other VA Forms experiences. If Governance raises this at Staging Review as a launch-blocking item, we can tackle at that time.

**Comment by oddball-lindsay** [comment]
> Is it possible for the back button on the initial select page to go back to the review page after tapping edit?

Locally, the back button was working to get back to the Review page and that is the expectation; just tried in Staging and this seems to be working as expected.

@mtri were you experiencing something different? 

Curious, but this is not critical for getting into team QA.

**Comment by mtri** [comment]
Sorry, I need to be more specific– I’m referring to the back button on the select page next to continue not the browser back button.

![Image](https://github.com/user-attachments/assets/a5ff10fe-7102-47ce-bbcf-52db8420da9a)

This back button does nothing while editing which could create problems if the user is used to using this button to move backwards and forward in the form.

I was wondering if it’s possible for this back button to return to the Review page.

**Comment by oddball-lindsay** [comment]
Thanks for clarifying @mtri ! 

I feel like we're already doing something that may infringe on user expectations by jumping them back into the Rep chapter when they click "Edit" on the Review page. If this "Back" button goes back to the Review page, we're deviating even further from user expectations as it used to point to the "Are you the Veteran?" page and now it's pointing to the Review page. 

I get now why you mentioned there's no user to go back to the “Are you the Veteran?” page 😅.

My current preference is to keep the "Back" button at this stage as originally rigged up (to maintain the same expectations) -- point to the "Are you the Veteran?" page -- and if the user wants to navigate back to the Review page, they can use the browser's back button. 

But let's also talk about this as a team when you're back because I'm curious what Janelle and Lesley think! And I can make a ticket after we discuss with the team, about how the "Back" button should behave in this particular scenario.

Until then, **I think this ticket is okay to close out because we have met the logic originally outlined.**
