### ISSUE TITLE
PR Bot Testing: Obtain GH Token

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#94262]
## Description 

We are reviving the PR Bot to ensure that all requirements are met before a Pull Request (PR) is submitted for review to the Tier 2 team. The following steps outline the tasks necessary to launch a test of the PR Bot.

Acceptance Criteria:

- GitHub and Slack tokens are successfully acquired.
- The code is hosted on Heroku for continuous operation.
- The route for PR responses is tested to an alternate channel.
- Once the setup is approved, messages will be rerouted back into the support channel.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Token Access: Acquire a GitHub Token

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bmatos312** [comment]
Spoke with the github admins and they said a PAT token should suffice and if not I can follow the road of a getting a bot access token which is not tied to any user.

**Comment by alyssagallion** [comment]
GH token obtained. Closing.
