### ISSUE TITLE
SOCKS access for [Adrian Rollett]

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#94283]
### Your Name

Adrian Rollett

### Your Email

adrian.rollett@va.gov

### Your GitHub Handle

acrollet

### Your Role and Team

OCTO Engineer

### Product Manager (PM) name and email

Bill Chapman (william.chapman7@va.gov)

### Product Owner (PO) name and email

Bill Chapman (william.chapman7@va.gov)

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAA8rs/FCyzg/Evzm9fkLSK4nV7nSt3j+neD/Mbd+HRw OITECHRolleA@HAC-LT3537169

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![eqip image](https://private-user-images.githubusercontent.com/101649/271427861-1d22d740-a218-48c7-aff3-8cf17962550a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzkwMjAsIm5iZiI6MTcyNzk3ODcyMCwicGF0aCI6Ii8xMDE2NDkvMjcxNDI3ODYxLTFkMjJkNzQwLWEyMTgtNDhjNy1hZmYzLThjZjE3OTYyNTUwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxODA1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjVjMzljMDY1ZDVkOTljZWQzNDg1ZjJkZDFiMjEwYWQ3MmY3NzAyYzc3MTRlMjdlNjYzMWE3MjYwNWIzNjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4LWf0AYvaz06hAJB2zEZPqDgCUblb5LfASRfd4uX9mM)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [ ] Work email address is listed
- [ ] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by ph-One** [comment]
I believe this one should be closed. Will hold off until we get confirmation from @acrollet .

**Comment by acrollet** [comment]
Good to close!
