### ISSUE TITLE
color background vs. white background for results screen

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9432]
supposing the pass/fail contrast was b/w blue with white text (pass) and white with blue/dark text (fail), maybe w/ a border around the div? this would be very distinguishable from a distance...

Slack thread: https://dsva.slack.com/archives/C013WDER4FP/p1590090846256000?thread_ts=1589916111.086200&cid=C013WDER4FP

to do:
- [x] mock up
- [ ] dev: increase check icon size and header font size 
- [ ] dev: change font to be Source Sans for everything, even headers
- [ ] dev: increase font size, change line wrapping for the day/time name so it can be seen a bit more easily
- [ ] dev: align two bottom sentences left instead of center
- [ ] get feedback/decide if we want to do it :-)
- [ ] FE implementation

**Comment by artsymartha68** [comment]
<img width="587" alt="Screenshot 2020-05-28 12 06 20" src="https://user-images.githubusercontent.com/47792423/83165547-ab461400-a0db-11ea-9e26-85575badf7fa.png">

Something like this?

**Comment by batemapf** [comment]
@Yuffster-usds this one is ready for implementation. see above for mock ups and original comment for proposed to-do's.

**Comment by Yuffster-usds** [comment]
How's this?

![](https://user-images.githubusercontent.com/63240636/84068796-81240a00-a997-11ea-8d06-b662cdd8a33c.png)

![](https://user-images.githubusercontent.com/63240636/84068734-71a4c100-a997-11ea-81d7-a429ab839a9d.png)

**Comment by artsymartha68** [comment]
NIIIIICE  😻

**Comment by artsymartha68** [comment]
Are the longer months abbreviated to 3 letters?

**Comment by Yuffster-usds** [comment]
No, is that a blocker?

**Comment by artsymartha68** [comment]
No but it'll cause weird wrapping now that we've bumped the font size up, methinks. We can open a separate issue. June and July are short so we have time :)

**Comment by Yuffster-usds** [comment]
Exactly my thoughts.

**Comment by batemapf** [comment]
Issue [created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9971). Checked to see what would happen with a longer month. Looks fine on an iPhone 5, which is a pretty small screen, so might not need it:

![image](https://user-images.githubusercontent.com/7645362/84137142-41523680-aa1a-11ea-9ea6-a0d5b6c6be2b.png)
