### ISSUE TITLE
Deduplicate reason and patient comments rendering logic

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#94339]
## Summary

WIP, we'll need to take a look at this with Tony when he's back to get a better understanding of what's needed here.
 
Currently noticing duplicated logic in the following places which may lead to rendering inconsistent information:
- https://github.com/department-of-veterans-affairs/vets-website/blob/83dc4374dc653d6b462c6be6bae4bc3dd803063f/src/applications/vaos/appointment-list/redux/selectors.js#L204
- https://github.com/department-of-veterans-affairs/vets-website/blob/83dc4374dc653d6b462c6be6bae4bc3dd803063f/src/applications/vaos/appointment-list/redux/selectors.js#L228
- https://github.com/department-of-veterans-affairs/vets-website/blob/83dc4374dc653d6b462c6be6bae4bc3dd803063f/src/applications/vaos/services/appointment/transformers.js#L209-L223

## Specs
- Device: 
- Browser: 

## Steps to Reproduce
**Test User:** 

1. Go to: _URL_
2. 

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment]
@JunTaoLuo @vbahinwillit - if you can take a look at this ticket and let us know if there are additional work needed. cc: @simiadebowale @JRRoof ([see thread](https://dsva.slack.com/archives/C0331ERT9C6/p1729028930204889))

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/94339?planning-poker) with Zenhub @jenniemc @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/94339?planning-poker) with Zenhub @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Actually, there's nothing to validate in this ticket since the approach we took was some minor refactoring that removed the duplicated code. If anyone disagrees, feel free to re-open.
