### ISSUE TITLE
Design: 10-7959C must collect the MBI

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/va.gov-team#94334]
As a processor of OHI forms, I need the submitter's Medicare Beneficiary Identifier (MBI) so that I can process their information appropriately.

- [ ] Update OHI Figma to add required MBI

**Comment by pshahVA** [comment]
The OHI team would like to add collection of the Medicare ID to the 10-7959C form.  This can only be done after the PDF has been updated.

**Comment by jamiefiore** [comment]
@baltes  I have 2 options [on the Figma ](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3485-170957&node-type=canvas&t=evfYGLqDwQ8Dajgx-0)to review with the team. 
I also have some questions for Premal and the IVC stakeholders that may change this.

- Do applicant's still need to provide a copy of their Medicare cards?
- Is there any situation the a Medicare number would differ between the Part A and B plan? 
- Do Advantage Plan applicants need to report their ID number as well?
