### ISSUE TITLE
Spike: Look into improving datadog dashboard with more zero silent failure monitoring

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#94337]
Review the Burial teams datadog dashboard.  See how we can use best practices used by other teams.

**Comment by baltes** [comment]
@cloudmagic80 Let's timebox this to wrap up by the end of the sprint, and consider this spike done once you're able to add recommended updates to this ticket. Let's discuss those before we make any changes.

cc @andrea-merrill

**Comment by baltes** [comment]
Closing this one out, we can capture any future recommendations in a new user story.
