### ISSUE TITLE
10-7959f-1: Feature toggle for staged release

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94344]
As a user registering for the Foreign Medical Program during the staged release of 10-7959f-1, I need to be shown consistent content as determined by the flipper so that I can complete my registration regardless of whether I can fill out the online form or must use the PDF form.

### Acceptance criteria

(all links go to staging for illustrative purposes, but staged release will be managed in production)

When a user visits the [static page](https://staging.va.gov/health-care/foreign-medical-program) and Flipper shows the user the new static page, then the user sees the link to the [online form](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1) and the user can view and complete the online form 

When a user visits the [static page](https://staging.va.gov/health-care/foreign-medical-program) and Flipper shows user the old static page, then the user sees the link to download the PDF form AND the user does not see the link for the online form

When a user visits the [online form](https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1) URL directly and is not accessing it through the static page entry point, then the user should see the content shown below under **Yellow box replacement text**.

A product manager must be able to control all of the above conditions through the [Flipper admin](https://staging-api.va.gov/flipper/features/form107959f1) so that a code change is not required to move from one stage of the release to the next (e.g. moving from allowing 10% of traffic to 25% of traffic).

A [meta tag is applied to block search indexing](https://developers.google.com/search/docs/crawling-indexing/block-indexing) during the staged release.

The IVC forms team must be able to remove all of the above conditionals once the staged release is over and the form is 100% live.

### Yellow box replacement text

> We’re still working on this form
> 
> We’re working on a new online registration form for the Foreign Medical Program (FMP). Check back soon.
> If you want to register for FMP now, you can use our PDF form.
> 
> Learn about FMP and how to register [https://www.va.gov/health-care/foreign-medical-program/]

Reach out to Jamie for guidance on any UX details for this page.

### Implementation details

Engineering to add as needed...

**Comment by rmessina1010** [comment]
This PR reverses #32184, reinstates the toggler component on the 10-7959f-1 app; 
https://github.com/department-of-veterans-affairs/vets-website/pull/32288

**Comment by reiting** [comment]
@baltes this has been merged and should be completed!
