### ISSUE TITLE
10-10d Update param store with VA Notify template ID

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94365]
As a CHAMPVA applicant, I need to receive an email confirmation after I submit my form so that I know it was received.

### Acceptance criteria

Production param store is updated with the 10-10d VA Notify template ID so that notification work correctly in prod.

**Comment by cloudmagic80** [comment]
[Uploading... Screenshot 2024-10-15 at 1.24.45 PM.png]

**Comment by baltes** [comment]
Closing this, though it might be a while before the form is in a state for a live test.
