### ISSUE TITLE
Custom error/form-not-submitted page

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#9437]
Given that we need to send veterans who could not be found in MPI to the paper form
I want to build a custom error/form-not-submitted page
So that users who could not automatically be verified can understand next steps.

Design Specs: 
https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/426398082_Error-Desktop-V-04

*Additional acceptance criteria:*
Adjust on screen focus to center on error after submission

**Comment by LinnJS** [comment]
Designs: https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/419830701_Error

**Comment by LinnJS** [comment]
Conversations about overwriting error component: https://dsva.slack.com/archives/CBU0KDSB1/p1592233036426000

**Comment by LinnJS** [comment]
This ticket is blocked due to the conversation above, the current form builder only supports a hard coded error message. Needs an overwrite feature added to platform code.

**Comment by LinnJS** [comment]
This ticket is blocked by #10233
