### ISSUE TITLE
Add digital acceptance back to the search results cards

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#94384]
## Background
There are mentions of if a VSO can/cannot accept digital requests on the [organization selection page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4528-249462&t=bOI3ScqzOHskgvvB-4), but what if a user chooses a VSOR that is only accredited with a single organization, or they choose an entire organization up front? In these scenarios, the user will not have the hint as to if digital acceptance is available. 

To solve for this, we'll need to add back in mentions of digital acceptance on the [search results cards](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6329-256216&t=bOI3ScqzOHskgvvB-4). 

## Tasks
- [x] Add mentions of can/can't accept digital submission back to the rep search result cards, for Appoint v2 designs

## Acceptance Criteria
- [x] When searching/selecting an individual with a single VSO accreditation, or an entire VSO at the start of the Accredited Representative chapter, users will be able to see if digital submission is available.

**Comment by mtri** [comment]
All Appoint v2 select screens have been updated to include the message indicating whether or not a representative can digitally accept the form.

All variations of this language are visible on the following screens:
[Select](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=6329-256216&node-type=frame&viewport=9839%2C-14118%2C0.5&t=YTMbVffUl68kbZMv-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893)
[Select with organizations](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=8890-504749&node-type=frame&t=HvG9FQRDXafhEuJ0-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1)
