### ISSUE TITLE
Update Designs of New Confirmation Page and New Email Touchpoints

### ISSUE THREAD

**Issue by pammicmac** [department-of-veterans-affairs/va.gov-team#94385]
### **Issue Description**
Prepare New Email Confirmation Page and New Email Touchpoints for engineering to begin work. 
Final review is scheduled for 9 am ET on Friday, 10.18.
Delivery to engineering is scheduled for 4 on ET on Friday 10.18.

**Figma File**
https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-Submission-Experience?node-id=5626-129729&t=pf2aUXajxbZl9rNi-1

### Acceptance Criteria
1. Overview Page
Missing Contextual Information: Ensure the page includes links to research artifacts, product briefs, and other relevant documentation. This will help engineering dive deeper into the project context and understand the designs more comprehensively.

2. Discovery Page
Dependencies: Add documentation about dependencies (e.g., VFF, VA Notify) to ensure alignment with current standards.

Quality Check (QC): Perform a final review to confirm the documentation is clear and up-to-date.

3. Design File vs. Design History
Clarify Iterations: Clearly distinguish prior iterations from the latest designs to prevent engineering from referencing outdated versions.

4. Accessibility Annotations
Missing Annotations: Accessibility notes created in earlier versions need to be incorporated into the latest file provided to engineering.

QC Required: Ensure the annotations are accurate and properly integrated.

5. Research Annotations
Add Research Insights: Include research annotations from previous design versions to highlight relevant areas without obscuring the designs.

Address Feedback: Engineers have noted a lack of visibility into the rationale behind design decisions. Ensure research insights are embedded in the Figma files for added context, even if these were previously discussed during walkthroughs.

6. Release Horizons
Update the designs to align with engineering’s incremental build and release schedule:
New Confirmation Email (First Release): Review and update the copy accordingly.

Submitted Email (Second Release): Ensure both the confirmation page and email copy reflect the updated context.
Received Email (Final Release): Adjust the copy on the confirmation page and email as needed for consistency.

7. GitHub Tickets
Project Details: Add relevant project details to the GitHub tickets for today’s refinement meeting to prepare engineering for the next sprint.

8. Socialization
OCTO Review: Share the designs with OCTO for final feedback to avoid last-minute surprises regarding the changes made.

9. CAIA Coordination
Feedback Loop: Continue working with CAIA to resolve feedback, document decisions, and develop a plan for handling unresolved feedback in future sprints.

10. Email Fonts
Font Update: Update the email fonts to web-safe Arial to reflect the technical constraints and match the end-user experience accurately.

11. Technical Feasibility Check
Constraints Validation: Confirm with engineering that all technical constraints are accurately represented, including:
Claim ID visibility at the appropriate points (e.g., Happy Path, Retry, Backup, and Evidence Failure paths).

12. Claim Details Box in Email Touchpoints
Content Alignment: Ensure the content in the claim details box matches the VA Notify template and is consistent with the emails from CARBs for a seamless user experience.

### Key Reviewers
Jared Pace
Maya Carroll
Evelyn Davis
Aurora Hampton
Shannon Ford

**Comment by evelynhilbrichdavis** [comment]
We are awaiting update from CAIA on the revised designs, hoping to get an estimated date for the feedback by EOD.

**Comment by mayacarrolluxa6** [comment]
I've put together a [checklist of tasks to complete](https://docs.google.com/document/d/1BCR0kpivRaZZD6MEWmXQqf5DJmvxZ1NUs-TJ26HcIXE/edit?usp=sharing) to prepare the New Confirmation page and Email touch points for Engineering on Friday. Let’s collaborate today to address the remaining items. I’ve scheduled a progress check for 9 AM ET on Friday, and the final handoff to Engineering is set for 4 PM ET the same day.

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis We've already been through 2 rounds of CAIA review. Let’s try to avoid being in a position of ‘waiting for CAIA.’ As an HCD team, we all share the responsibility for our copy decisions. It might also be helpful for us to upskill on the [content guidelines](https://depo-platform-documentation.scrollhelp.site/getting-started/content-hub) together at some point in the future

**Comment by StevenStraily** [comment]
Work completed for the first increment, reviewed, and shared out today 10-18.

[New Confirmation Page Designs](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8187-81093&t=p3ziITq3Qpe50Ovs-4)
[New Confirmation Page Annotations](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8187-81090&t=p3ziITq3Qpe50Ovs-4)

**Comment by mayacarrolluxa6** [comment]
@StevenStraily On 10/18, we received feedback from Matt Dingee that the VFF confirmation was recently merged into the Forms Library and will go live next week. Let’s discuss adjusting the confirmation page design to align with the new form pattern during today’s huddle.
