### ISSUE TITLE
Set Up empty app on va.gov

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#944]
As a veteran, I want to be able to access my online healthcare scheduling tools on VA.gov so that I can just go to one place to manage all of my interactions with the VA.

## AC:
- [x] Add VAOS app shell to VA.gov to allow for further VAOS dev work on the VA.gov platform.
- [x] No new VAOS pages should be available in production.

**Comment by narin** [comment]
Validated on staging and confirmed `/vaos` isn't accessible on production.
