### ISSUE TITLE
SOCKS access for Harshil Moradia

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va.gov-team#94407]
### Your Name

Harshil Moradia

### Your Email

harshil.moradia@adhocteam.us

### Your GitHub Handle

harshil1793

### Your Role and Team

Sr. software engineer, DST

### Product Manager (PM) name and email

Carol Wong, Carol.Wong@oddball.io

### Product Owner (PO) name and email

Matthew Dingee, matthew.dingee@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEIc27ebxEm0e2BmKYgfTZkvPMyBKXuZvEab0gxFiTy7 harshil.moradia@harshilmoradia-PYWY4DK942

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/66b7ee25-5d5c-4aa1-9f03-f34ce1a7f00e)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by hgbarreto** [comment]
@harshil1793 Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
