### ISSUE TITLE
Gather artifacts for Denise

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#94401]
[Denise mentioned she needs information for a presentation on Tuesday 10/8](https://dsva.slack.com/archives/G01KBHYEXV2/p1727989995779519)

Here are the requests I've compiled from the Slack thread:
## Questions
* How does the debt portal (including the FSR) handle scheduled and unscheduled downtime?
    * Debt portal does not have a “switch” or feature flag for downtimes scheduled or otherwise. We do have a mechanism within vets-api [that will detect a threshold of 50% error rate](https://github.com/department-of-veterans-affairs/breakers?tab=readme-ov-file#services). If this threshold is met, the app will halt organic requests to the service. It will try requests every minute until successful requests are made. This "breaker" functionality is for services that retrieve debts and copays. This is not applicable to FSR.

* At any time in the previous 3 months were users unable to access part/all of any of the products/features?
  * Debts
    * There are/have been many times in the past 3 months that debts were not retrievable due to timeouts. It's tough to pinpoint specific moment(s) where the service was completely down since there were some successful requests trickling in. See graphic below, the red are errors and those were unsuccessful reqeusts:<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65f30ffdc6646b59a73d09cc9e101ddae493dd23/image.png" alt="image.png" />
 
  * Copays
    * One known downtime for getting PDF statements happened during a partner update around 9/10. This was fixed by them on 9/16.
      <img width="1138" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ltQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1693c8ba44ae0bb652bf5127df432bf48e7a2292/image.png" alt="image.png" />

  * FSR
    * We know that the FSR had a downtime on 7/22 due to Sharepoint credentials becoming invalid (they invalidate after a year). This downtime carried on until 7/29. We were able to work with a team on the Sharepoint side to remediate missing forms manually.
    * <img width="1016" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ltQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2d58352c0f4eee9c0dbf25deea1f04593d403bb/image.png" alt="image.png" />

* With something like that dashboard view I'd need a little context so I can speak to any questions that come up. For example (using the image above)- the Sharepoint request success rate is only sitting at 94.37%, or the 73 failure - do we know why or what is causing that.
  * Hoping you'll get that in this ticket, let me know if you need more info.

* It sounds like this presentation will become a quarterly one for OCTO Leadership so I will be needing the same info in December - having a place would be helpful.
  * We should set up a dashboard group that has all this information so that we can just grab a quick screenshot of it.

### Full Transform
* I need to articulate what the key results were (or said differently what changed as a result of this work) I assume it made the application more reliable and efficient - but how?
  * The main win here is that we offload the data mutation needed to submit to our partners to the backend (vets-api) this is better suited for this type of work. It prevents the need to maintain business logic across the stack (vets-website and vets-api)

* Did the response times from our API's decrease? Did it decrease our error rates? Did it reduce the number of cycles on VA servers (therefore saving money) etc.
  * This was essentially a simplification of our FSR submissions on the frontend. This does not reduce calls to any API. We submit the same way to our partners. 
 
Here are the submissions we've had so far:
<img width="1586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a78bb2fa803564af8493d1cdd02e4eea316e064/image.png" alt="image.png" />

## Summary
I'd say the bulk of the backend work for the past 6 months have been putting out fires. We've had a noisy alert channel and we've not made any major changes to our code. All of the errors we've hit have been due to services we integrate with having problems.

We've optimized the debts and copays endpoints to speed up responses and attempt to reduce errors. We've also cleaned up our dashboards removing empty graphs and getting better insight to issues. We have begun rolling out the full transform functionality as well.

We've made progress to mitigate silent errors with Sidekiq exhaustion blocks getting added to our jobs with better error messages.

We will be setting up an alert for every form that gets its status set to `error` as well.

**Comment by denisecoveyduc** [comment]
Thank you @digitaldrk for detailing all of this information and 'putting out the fires' over the last 6 months.  While we don't like fires we do like the fact that we are getting a lot smarter about some of these alerts and monitors which will help us continuously improve this experience for Veterans.  
I have what I need for today's presentation but please give some thought to how best to track outages/incidents moving forward so we have a detailed record of events as they are popping up.  (FYSA: @Tom-Davis, @dhill802 )
