### ISSUE TITLE
Create new Experience Standard for notifications

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#94416]
## User Story
As a Governance team member, I want to ensure our Experience Standards include proper notification coverage for Veterans so that VFS teams are encouraged to build products that meet the notification coverage standards.

Assignee: @erinrwhite @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description

On October 1 and 2, the OCTO Team Zero Errors check-in meetings occurred. The purpose of these meeting were for OCTO-DE to check in with VFS teams to ensure their products on VA.gov had zero silent failures, and teams had plans in place to remediate any known errors. While we were glad to learn that there were few instances of silent failures, we did learn that there were some instances within VFS products where the UI/UX had some inconsistencies. For example, we learned that if the VA cancels a Veterans appointment (for example, due to facilities closures) that the cancellation will be visible on VA.gov, however a Veteran isn't sent a notification via email or text message to communicate the cancelled appointment. This is not ideal as Veteran's shouldn't have to log into VA.gov everyday just to confirm that there appointment hasn't been cancelled.

The purpose of this ticket is for Governance team to create a new VA.gov Experience Standard focused on proper notifications. Per @humancompanion-usds, "...if it’s worthy showing in the UI, then it’s possibly worth sending as a notification too. "  VFS teams must notify veterans in both paths (belts _and_ suspenders). The secondary path is email, or text, and needs to happen for critical points in the experience. 

**Updates post conversation with @humancompanion-usds on 10/25:** At this time, the priority for Governance is to add the new standard to the [VA.gov Experience Standards](https://design.va.gov/about/experience-standards/) so that it is visible and hopefully adhered to by VFS teams. Also within the scope of this ticket, Governance team will modify the operational process at Design Intent and Midpoint Review for the Design and IA practice areas to help guide the VFS into using appropriate notifications by asking intentional questions about the flow for the Veteran outside of the VA.gov experience. Governance team has several larger initiatives planned to better determine how notification standards can be incorporated into Collab Cycle, and where/how our processes and learnings may need to change to support notifications standards

### Live pages
- [VA.gov Experience Standards](https://design.va.gov/about/experience-standards/)
- [How to complete a Design review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2605056001/How+to+complete+a+Design+review+for+Design+Intent)
- [How to complete an Information Architecture (IA) review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
- [How to complete a Design review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492563471/How+to+complete+a+Design+review+for+Midpoint+Review)
- [How to complete an Information Architecture Midpoint review for Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+review+for+Review)

### Drafted pages
- 

### Changes to standards
- [x] Before defining anything, please read through the [Updating Experience Standards and descriptive tags](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) guidance
- [x] Using the description above as well as [Matt's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94416#issuecomment-2436435333), propose a new standard for VFS teams building on VA.gov 
- [x] Share standard with peer reviewer for feedback
- [x] Once assignee and peer reviewer are in agreement, share with Governance team and Matt Dingee via the #platform-governance-team channel in Slack

### Changes to operational guidance
- [x] Update the IA and Design operational guidance for both Design Intent and Midpoint Review to include guidance for asking the VFS teams questions about the Veteran experience for notifications outside of VA.gov (I won't be overly prescriptive here wrt how you do this, however I do really like the IA E[valuation Criteria for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent#Evaluation-Criteria-for-Design-Intent))

### Publishing and announcing
- [x] Write a change announcement for Slack following the [Slack change announcement format
](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129/Slack+Change+Announcement+format)
- [x] Write a new post for the Platform Website/Collaboration Cycle Change history page
- [x] Submit a pull request to update the Experience Standards page on VADS and work with @it-harrison to get it approved and merged
- [x] Once Governance and Matt sign off on new standard, publish pages and post change announcement

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has published a new VA.gov Experience Standard for ensuring notifications (email, text) are sent if/when a critical action occurs on VA.gov
- [x] Governance team operational guidance at DI and MPR has been modified to help direct VFS teams to build products that meet our new notification standard
- [x] VFS teams have been made aware of the changes to the VA.gov Experience Standards

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Notes from the team at refinement on 10/21:

- This is related to Service Design, which is new territory for us. 
- How do we know/determine when a notification is necessary?
- We want to talk to Matt to better understand the scope

**Comment by humancompanion-usds** [comment]
Visibility of system status” is number one on the list of the “[10 Usability Heuristics for User Interface Design](https://www.nngroup.com/articles/ten-usability-heuristics/)” from the Nielsen Norman Group. The rule states that “the system should always keep users informed about what is going on, through appropriate feedback within a reasonable time.” 

Our system will do this in 2 ways at critical touch points when a user submits data/makes a request to the VA:
1. Notifications via SMS and email
2. Providing status in the UI

This allows us to provide system status of a request such that if the user misses one they will (hopefully) see the other. 

First and foremost, we've asked all VFS teams to send 3 types of notifications for asynchronous form submissions as detailed in an update to the VA Design System pattern [Help users to stay informed of their form submission status](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status) by 11/11/24. Governance currently enforces patterns in the Design System and will be expected to enforce this one as well.

After that deadline, from my perspective, the next step is the addition of an experience standard to cover notifications that go beyond this pattern as notifications are a critical part of the user experience on [VA.gov](http://va.gov/) and the mobile application. Not all silent failures are form submissions. Creating an [Experience standard in the Design System](https://design.va.gov/about/experience-standards/) is how we achieve this which gives the Governance team some leeway in how they make sure teams are providing an excellent user experience.

Since I filed this, we discussed with Dave Conlon that the standard could exist in VA Notify's documentation. I'm agnostic as to where it lives so long as it gets created quickly as we have an impending deadline and need to ensure that teams do not ship new work that allows for silent failures.

**Comment by erinrwhite** [comment]
Started a [documentation draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3576037395/94416+-+Erin+Allison+-+New+experience+standard+for+notifications) - @allison0034 and I are meeting tomorrow to talk more

**Comment by erinrwhite** [comment]
hi @KKitagawa-Bosch!

@allison0034 and I just came up with a [few options for wording](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3576037395/94416+-+Erin+Allison+-+New+experience+standard+for+notifications#Potential-standards-language) for the new experience standard. Here's our current thinking:

> User has timely and appropriate information about their account status.

Can you review this, and the other ideas we had in the doc, and let us know what you think? 

We are also curious what you think about the "account status" language. We batted around a few different options - really want to clarify that this standard is about Veterans having information about their individual access to VA services, rather than being on a broadcast text notification list.

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch this was our thinking too! What might be some good replacements?

> User has timely and appropriate information about their _______.

- submission status
- request status
- form status
- changes to their account
- access to VA services
?

**Comment by KKitagawa-Bosch** [comment]
I kinda like changes to their account, though that may suggest it's only when the account itself changes. Maybe "changes impacting their account?" So it's nice and vague.

**Comment by shiragoodman** [comment]
chiming in here after reading the comments. I haven't viewed the draft doc. 

It appears that the goal you all are trying to achieve is to introduce this new standard with the same level of granularity as the existing standards...ie a very broad, high-level standard. I'm wondering if we should be more specific. For example, "User has timely and appropriate information about their ___" (whatever the blank ends up being) doesn't state anything about notifications or anything about the experience outside of VA.gov. As far as I'm concerned, most teams (including Appointments) are currently meeting this standard bc the "timely and appropriate information" does exist within the VA.gov experience. We need this standard to communicate that the notification must occur OUTSIDE of the VA.gov experience too. Also, I'm not sure "information" is the right choice. If I were a VFS, I could interpret this to mean that the page loaded in a timely manner. 

Please take into consideration my comments and lmk if you have any questions. I imagine Matt will be looking for something a bit more on the nose. Keep in mind we can always change the standard later on after our research is completed. Thank you!

**Comment by erinrwhite** [comment]
@shiragoodman @allison0034 @KKitagawa-Bosch thanks Shira, I think a good next step is to get Matt's take on this. We had a much more specific option in the doc as well - I'll ask if he prefers that, or the more broad one.

**Option 1: more specific**
> User receives appropriate notification about events that affect their access to VA or VA.gov services.

This wording is specifically about notifications and explicitly names that it includes experiences outside of VA.gov.

**Option 2: more broad**

> User has timely and appropriate information about changes impacting their account.

With this wording, the new standard would include both notifications and being able to verify information or check status after form submission - another thing we’ve been asked to verify recently at Design Intent/Midpoint.

**Comment by erinrwhite** [comment]
[Chatted through this on Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1730296310979529) and landed on:

> User receives appropriate notification from the VA or VA.gov about the status of their request.

Proceeding...

**Comment by erinrwhite** [comment]
@allison0034 next steps for us:

- work on our operational documentation for Design and IA
  - [How to complete a Design review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2605056001/How+to+complete+a+Design+review+for+Design+Intent)
  - [How to complete a Design review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492563471/How+to+complete+a+Design+review+for+Midpoint+Review)   
  - [How to complete an Information Architecture (IA) review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
  - [How to complete an Information Architecture Midpoint review for Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+review+for+Review)
- draft [change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3576037395/94416+-+Erin+Allison+-+New+experience+standard+for+notifications#Draft-change-announcement)
- pull request for [Experience Standards](https://design.va.gov/about/experience-standards/) page on VADS

I can start on my docs, and create the pull request. 

Can you do your docs, and start a change history post?

**Comment by erinrwhite** [comment]
Updated IA docs:

[How to complete an Information Architecture (IA) review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
[How to complete an Information Architecture Midpoint review for Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+review+for+Review)

**Comment by allison0034** [comment]
[Took a shot at change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3576037395/94416+-+Erin+Allison+-+New+experience+standard+for+notifications#Draft-change-announcement) and tagged @KKitagawa-Bosch to see if he could improve content : )

**Comment by shiragoodman** [comment]
@erinrwhite @allison0034 per discussion from standup yesterday, Matt would like all teams building out a form to use the [Stay informed of their form submission status](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status) pattern. I think it might make sense for you to include this in the operational guidance for your practice areas at DI and MPR. Please lmk if you have any questions.

**Comment by allison0034** [comment]
@shiragoodman that is very hyper focused. My guidance does not get that granular. I don't think we should start to get that specific otherwise we would be listing every piece of guidance we have. Instead, I point to the design system as a resource. 

If we do start listing these things at this level, it will also be a maintenance nightmare. The DS is very fluid and ever changing.

**Comment by erinrwhite** [comment]
> [@shiragoodman](https://github.com/shiragoodman) that is very hyper focused. My guidance does not get that granular. I don't think we should start to get that specific otherwise we would be listing every piece of guidance we have. Instead, I point to the design system as a resource.
> 
> If we do start listing these things at this level, it will also be a maintenance nightmare. The DS is very fluid and ever changing.

@shiragoodman agree - our guidance is varying fidelity so it could be awkward to add links to specific VADS guidance where there is none already. My DI guidance is more broad and does not link directly to the design system, but the IA midpoint guidance is very specific (linking to several components/patterns already) so I added the link on the midpoint page.

**Comment by erinrwhite** [comment]
@shiragoodman Should we include changes to the Drafting Template as part of this work, or can that be a follow-up next sprint? We have this new standard and the new pattern guidance we mention above. There've also been a few other adds/edits to VADS in the past few months that should be reflected in the drafting template - could bundle 'em together.

**Comment by erinrwhite** [comment]
@allison0034 @KKitagawa-Bosch [PR for updated experience standards page](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3492) ready for your eyeballs!

**Comment by erinrwhite** [comment]
Moving this ticket to review 🎉 

These pages are updated
- [How to complete a Design review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2605056001/How+to+complete+a+Design+review+for+Design+Intent)
- [How to complete a Design review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492563471/How+to+complete+a+Design+review+for+Midpoint+Review)
- [How to complete an Information Architecture (IA) review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
- [How to complete an Information Architecture Midpoint review for Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+review+for+Review)

These pages are awaiting peer review before publishing:
- [Change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3576037395/94416+-+Erin+Allison+-+New+experience+standard+for+notifications#Draft-change-announcement)
- [pull request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3492) for Experience Standards page on VADS

**Comment by allison0034** [comment]
Keegan we are just waiting for the pages to post, can you confirm you reviewed everything in Erin's comment? I believe you have.

**Comment by KKitagawa-Bosch** [comment]
I did!

**Comment by erinrwhite** [comment]
[Experience Standards page on VADS is updated!](https://design.va.gov/about/experience-standards/#user-receives-appropriate-notification-from-the-va-or-vagov-about-the-status-of-their-request)
