### ISSUE TITLE
SOCKS Access for Dror Matalon

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#9441]
# Instructions
1. Access to Dror Matalon to SOCKS proxy
2. Add the label used by your team (VA VSP)

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Dror Matalon
- Please Provide your email.
   > dror.matalon@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   VA VSP Digital Janitor
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB7qX1MEYbaUcTlzYwhFXPT4wPjOb+Cy1yEArHkM2+6p0So0D87luN0kKBlOteAcsIonoMeGZDaP4HOrl2AFUDfSEG+YMFscT/uvNfrhTWeoPquM3UgvOqkduN1zRG8g2vvFFzaQo60vkPjGd867ppF8Xg9HBL1cw15/svpnZpNG/JZ1cn0O02xJWWNHk2N36T3QnqBX9nByNsscwoXZMvdR1xuAx+pGFewx7+Ac7VUglbK0XyJb4H/hM+KAo3Jp4HkWefeVqH44mDOHNi6X9wbOFhP+g6NswMm4N3HpNWnv5AG3fsfe+RkpDRwXb/xBIX1+DMGfohS3ocoYg+zwO3 dror@36aa454ae51a
```

- [Grant AWS Console access?]
  NO

**Comment by drorva** [comment]
@department-of-veterans-affairs/vsp-operations please do your magic.

**Comment by tskinn** [comment]
@drorva you should be able to connect. Reach out to operations in slack if you have any issues.
