### ISSUE TITLE
Add link to research presentation template to Research section on Platform site

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94431]
### Description

On the Platform site within research, it would be great to provide links to the Google Slides presentation templates. I.e., there's a GitHub template for the markdown file on https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesis, but no links to folks to utilize the presentation templates, which are located in this [Slack Canvas](https://dsva.slack.com/canvas/C0NGDDXME). 

Specific links include: 

https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit?pli=1#slide=id.g892adcb623_0_141

https://docs.google.com/presentation/d/19l8281cENnUmdz0qIsyPcVIeoyB8uw_kzoHYWbuYlwA/edit#slide=id.g892adcb623_0_141

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesis

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VSF team - Appointments and Patient Check-in

**Comment by jknipes** [comment]
Hi @benbrasso-agile6 , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@benbrasso-agile6 on Platform website we are unable to link out to Google docs, slides, or sheets. I believe this is why the Google links are only available via Canvas.

@naomimarcussen , could you confirm?

**Comment by benbrasso-agile6** [comment]
I had someone ask me for the templates that couldn't access Google either. Could they be uploaded as PPTs? 

Problem: someone DM'd me asking where the templates were. Can we make them easier to find?

**Comment by naomimarcussen** [comment]
@benbrasso-agile6 Thank you for your feedback! We aim to make links from the site viewable to everyone. Since folks on the VA network and those on GFEs can't access Google products, we don't link to Google slides from the Platform website and have directed folks to Slack instead.

I've uploaded a PPT version of the template to the #design canvas so that it is accessible to those on the VA network.

**Comment by benbrasso-agile6** [comment]
Tysm feel free to close
