### ISSUE TITLE
[Tier 3] User Issues Uploading Claim Documentation

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#9443]
**Issue Description:** Users are experiencing issues when attempting to upload documentation for claims.  Some are getting error messages, which are included in the descriptions below.

**Priority:** Low

**Total Number of Issues:** 3

**Issue Number and User Description:**

### **SF: 02480985**

- Please copy and paste the URL or web address you were on when you experience the issue.
            _https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit_

- If you saw an error message, please copy and paste the exact text of the error message
           _"We’re sorry. Some information in your application is missing or not valid._
           _Please check each section of your application to make sure you’ve filled out all the information that is required."_

- What type of device are you using (i.e. dell laptop, MacBook, iPhone, etc.)?
            _I have tried on multiple devices including: MacBook, Windows laptop and desktops, and iPhone._

- Try a different browser (i.e. Internet Explorer, Firefox, Chrome, etc.). Does the issue occur on all of these browsers?
        _I have tried on all the browsers mentioned above plus Safari and Edge. I also used the latest versions._

- What account do you use to sign into VA.gov (DS Logon, Myhealthevet, ID.me)?
        _I have used DS Logon and Myhealthevet to login._

**Initials: EN**

### **SF: 02759337**

_Hi Kimberley,_

_I will answer your questions one by one below.  Firstly, my last name is Boody please ensure you have that corrected in your system as I do not want that to cause confusion.  The place where one would normally upload supporting documents for a claim is on VA.gov in the track your claims section.  When you select the specific claim you would like to upload supporting documents for, it opens a page showing the status along with a number of options on the right hand side where you can select upload documents.  With my status currently shown as "We don't know your status," there is no where for me to upload supporting documents._

_1)  https://www.va.gov/track-claims/appeals/SC378079/status_  
_2) No error message, simply a current status of "We don't know your status We're sorry, VA.gov will soon be updated to show your status."  Which has been present since March 28, 2020._
_3) Laptop with windows_
_4) Have tried Internet Explorer, Firefox, and Chrome.  All provide the same message of not knowing status._  
_5) DS Logon_

_Please let me know what you find out, as there has been no change in status and I am unsure if the VA has received the documentation from the private medical facility yet or not._

**Initials: AB**

### **SF: 02741821**

_Ms. Daniels,_

_Thank you for your reply. Below, I have pasted the two URLs for the successive screens I encounter when I go to submit my claim. The first URL displays the "Submit application" button/icon. Once I click the "Submit application," I'm taken to the second URL is where I  encounter the "Sorry" message (immediately below is a copy of the message I receive)._
-----------------------------------------------------
_We’re sorry. Something went wrong when we tried to submit your claim._
_For help submitting your claim:_
_Please call Veterans Benefits Assistance at 800-827-1000, Monday – Friday, 8:30 a.m. – 4:30 p.m. ET, or_
_Get in touch with your nearest Veterans Service Officer (VSO). Find out how to contact your nearest VSO_
------------------------------------------------------

_https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit_

_https://www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation_

_To answer your other questions, I have tried multiple browsers (Firefox, IE, Microsoft Edge, and Google Chrome). I have also used multiple computers (HP laptop w/ Windows 10, and an ACER Chromebook). Additionally, I have logged in with both my DS Logon and ID.me. I encounter the same error no matter what operating system, computer, browser, or logon I use...it's always the same._

_I'm pretty desperate for a solution at this point. I have resorted to assembling a version of my claim for mailing, but am now have technical issues printing it for hard copy due to printer issues and files not cooperating._

_I hope you are able to assist me further, and I look forward to hearing from you._

**Initials: JP**

# **New Issues added 6/3/20**

### **SF:  02802330**

 

Unfortunately, I cannot copy and paste. I can provide, snapshots from my cellphone. I was initially using my personal computer, when I tried submitting my compensation and pension claim. 

I have attached snapshots from my work computer; using google and IE. 

![image.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/ee32c7ee-e691-4516-aacc-3b34c5b9ec39)

I can get to the “intent to file”. I can review everything and make changes. That’s in E-benefits and the re-directed site, VA.gov. 

My end result is to just; submit the claim. Or start the claim to process. As you will observe the error messages from both internet conduits. 

"Always Live Life & Enjoy Living"

Sent from my phone 
**Initials: TB**

**Comment by Kimberley2019** [comment]
@luke-gcio @AZSchneider @SMLuthi 

Currently, this issue has been with your team for seven days and we have not received any confirmation. Please advise if there is any additional information that we can obtain and provide to you in order for your team to accurately address this issue.

Thank you in advance.

Kind Regards,

The VSP Contact Center Team

**Comment by Kimberley2019** [comment]
Reaching out via benefits-memorials slack channel on 6/9/2020.

**Comment by Kimberley2019** [comment]
@annaswims @luke-gcio 

Has there been any movement on this issue? If not, can the team advise on how you would like to handle this issue? If yes, can the ticket be updated with the information and closed?

**Comment by annaswims** [comment]
02480985 - There is not enough information  to act.  The key is "We’re sorry. Some information in your application is missing or not valid".  I would expect that if the veteran paged through the form they'd find something highlighted in red, but I couldn't say what it might be.

**Comment by annaswims** [comment]
# 02480985
There's a solid chance that 02480985 was fixed by https://github.com/department-of-veterans-affairs/va.gov-team/issues/13452

However, we still see that behavior many times a day dut to a variety of validation errors http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/events/?query=url%3A%22https%3A%2F%2Fwww.va.gov%2Fdisability%2Ffile-disability-claim-form-21-526ez%2Freview-and-submit%22

https://github.com/department-of-veterans-affairs/va.gov-team/issues/2138 is the ultimate fix for 02480985

**Comment by annaswims** [comment]
I know this is pretty late, but we'll need PII to properly troubleshoot 02741821

**Comment by annaswims** [comment]
SF: 02759337 is related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/11801 but no work has been completed

**Comment by denisecoveyduc** [comment]
Related to #14143

**Comment by dampad** [comment]
I keep getting "We’re sorry. Something went wrong when we tried to submit your claim." Application ID: 3040391. Please help. @annaswims

**Comment by Kimberley2019** [comment]
@vhenry07 these cases are pretty old.  I do not think that it is worth following up with the veteran due to the amount of time that has lapsed.
If you feel that this would be beneficial for your team to review in case it could fix more bugs, please do.  

I am closing the ticket, but please reopen if you feel it presents a benefit.
