### ISSUE TITLE
Midpoint Review - Content Feedback - Veteran Facing Forms - Service history patterns

### ISSUE THREAD

**Issue by KKitagawa-Bosch** [department-of-veterans-affairs/va.gov-team#94442]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must:** make sure all apostrophes are curly, never straight apostrophes
- [x] **Must:** in the DD214 section, in the sentence "Learn more about how to request a DD214" the word "request" is missing the letter "t". 
- [x] **Must:** make sure all complete sentences have terminal punctuation, including in bulleted lists and checkbox lists
- [x] **Should:** under the "is this information correct" question, the phrasing "if not, select no" feels redundant and a bit clunky, consider rephrasing. 

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by JaciWilkinson** [comment]
Asked @KKitagawa-Bosch for clarification about "make sure all apostrophes are curly, never straight apostrophes" - don't understand where those straight apostrophes exist in the design or how to change them.

**Comment by bpandone** [comment]
Note that CAIA feedback was different on the punctuation of complete sentences included in a list. For specifics, comments were made in the Figma file and have been resolved per CAIA guidance.

**Comment by KKitagawa-Bosch** [comment]
> Note that CAIA feedback was different on the punctuation of complete sentences included in a list. For specifics, comments were made in the Figma file and have been resolved per CAIA guidance.

The design system content guidance on list punctuation changed soon after this feedback ticket was created (updated guidance was posted October 10th), so I'm glad y'all were able to get updated info from CAIA!
