### ISSUE TITLE
SPIKE: Do we need an empty state when there are no referrals on the new Referrals and requests page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94443]
## Description 

Since the new Pending page is named "referrals and requests," what does the page look like if there are no referrals, which will be the case for 99% of Veterans? For example, would there be an h2 for "referrals"? Would we tell Veterans they don't have any referrals? Or link them to any content about community care appts? 

## Tasks

- [ ] Determine what's needed on the referrals and requests page if a Veteran has no referrals

**Comment by benbrasso-agile6** [comment]
@Cieramaddox added this ticket here

**Comment by benbrasso-agile6** [comment]
Leave at 0 estimate, since Ciera is working on this, not Christina

**Comment by benbrasso-agile6** [comment]
@Cieramaddox moved this to ready since Lauren gave approval on changing Pending to Referrals and Requests. 

cc @cgednalske @melissa-lefevre @outerpress 

Note: it seemed like this will go out along with the CC scheduling release

**Comment by Cieramaddox** [comment]
Content has been approved and designs are complete.

**Comment by cgednalske** [comment]
Awesome! 
cc @loripusey 

[Linking the design for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5844-9399&t=tqPKn3e19YE8dN5g-1)
