### ISSUE TITLE
Allow VETS API to have dynamic CORS

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-team#9445]
This is a follow up of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1630.

Current challenge is that our demo environments have "Make an appointment online widget" React widgets (and others) inside the build that cannot access the dev/sandbox-api.va.gov API endpoints, and were broken, @indytechcook created a [PR that manually whitelists some of the domains](https://github.com/department-of-veterans-affairs/devops/pull/6920), which was merged and works for now, but we do not want to have to do this for every new environment and need the demo domains whitelisted automatically. 

AC:
- [ ] All requests coming from *.cms.va.gov domains are automatically whitelisted (no manual PR submissions) to access the dev|sandbox-api.va.gov endpoint, specifically they have the correct hostname in the CORS repsonse header (since CORS spec does not allow wildcards, it [must be done server side](https://dsva.slack.com/archives/CBU0KDSB1/p1588881098229600?thread_ts=1588801087.185800&cid=CBU0KDSB1)). 

**NOTES**
Currently, the VETS API only allows static domains to be configured in CORS.  This doesn't work for our CI model where domain names are dynamic and temporary.

* Location within the vets-api where CORS is setup: https://github.com/department-of-veterans-affairs/vets-api/blob/6833e2fe1aaccb790c726d7172efc71586a5fbd1/config/application.rb#L52
* web_origin settings are configured in the devops repo in the <env>-settings.local.yml.j2 files (e.g. prod-settings.local.yml.j2)
* As far as CORS goes, no, CORS spec only allows *, nullor the full domain in the Access-Control-Allow-Origin header.
* Our backend uses the rack-cors gem for this configuration. https://github.com/cyu/rack-cors#origin

**Comment by gunsch** [comment]
Can you share more about why your demo environments don't have predictable domain names?

Side q: are these domains SSL-protected?

**Comment by indytechcook** [comment]
> Can you share more about why your demo environments don't have predictable domain names?

Absolutely!

There are two different types of dns names.
1. A site is spun up with every PR we have form github.  They are named based upon the github issue number.  Examples are http://pr1773.ci.cms.va.gov and http://pr1773.web.ci.cms.va.gov/ for the PR 1773.
2. Demo sites are spun up for editors or product teams to test migrations.  Current examples are  http://altoonahealthcare.demo.ci.cms.va.gov/ and http://altoonahealthcare.web.demo.ci.cms.va.gov

> Side q: are these domains SSL-protected?

Not yet but they are all behind SOCKS.  We have an issue in github to make all demo servers behind https:  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1376

**Comment by jholton** [comment]
Should be resolved by linked PRs
