### ISSUE TITLE
Create a system for incoming Analysis of Call Center Data

### ISSUE THREAD

**Issue by salihaghaffar** [department-of-veterans-affairs/va.gov-team#94457]
We need to create a system to review and synthesize the call center data in order to identify pain points and opportunities for improving the CST.

Currently the data resides in a spreadsheet located in Sharepoint.  It contains PII so it needs to remain in Sharepoint.  Consequently, it may be a time consuming process to comb through the data, but the value gained will be worth the effort.

For this particular issue, we will focus on creating a repeatable process for analyzing the data and defining what the output of that analysis should be in order to be easily utilized by the team.

**Comment by dysbo** [comment]
@janechodance received her PIV card yesterday and will be going through an introduction on using it to log into the various systems today, so she will take charge of locating and reviewing the data.
