### ISSUE TITLE
Decision Reviews - add custom metrics to track exhaustion failure items

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#94461]
## Value Statement
**_As an_ OCTO principal with responsibilities to report metrics on application performance,
**_I want to_** be aware of _all_ cases where Benefits Portfolio systems result in a silent failure, or require that a veteran is notified of a system failure.
**_So that_** we can focus resources on addressing issue, ensure that teams are responding to silent failure cases by having a metric available in Datadog, built in a way that minimizes complexity for the implementing team.

---
### New Feature
1. In all cases where a Decision Reviews system operations result in a _silent failure_ write out a Datadog metric which captures the issue 
```
statsd.increment('silent_failure', [tags=[service:"appeal-application",function:"lighthouse upload"])
```
  - *silent failure* is defined as any case where a veteran is not aware that a request made by them was not completed.
  - the _service_ tag value should be the application's name from the Datadog Service Catalog list of services.
  - the _function_ tag value should be selected by the team and clearly represent the application function that had the silent failure.  This should be the original function that failed (such as "lighthouse evidence upload" or "appeal submission", not a failed notification step ("VANotify").
  - we anticipate there are two cases where this scenario would happen:
    - the system has a silent failure issue and hasn't been updated to notify the Veteran of the issue.
    - the system had a silent failure and the attempt to contact the Veteran to notify them of the issue failed.

2.  In all cases where a BMT system operation _would have_ resulted in a silent failure, but that silent failure was avoided by notifying the Veteran of the issue,  write out a Datadog metric which captures the avoided issue 
```
statsd.increment('silent_failure_avoided', [tags=[service:"appeal-application",function:"lighthouse upload"])
```
- The _service_ and _function_ tags should follow the guidelines listed above.

3. If there are cases where we cannot write these metric note these cases with the ticket creator & product owner.  An example of this would be a case where the team only received notification of errors in email, or where an API used by the system does not provide a success/failure response that matches this goal.

## Outcome, Success Measure, KPI(S), and Tracking Link
- All cases of silent failures, and cases where silent failures were avoided by sending the Veteran a notification of a failure, are tracked with the metrics listed above.
- All metrics are properly tagged for application and function.

## Design
- Add here

### Enablement team (if needed)
@va-albers 

## Product Owner 
@amylai-va 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by pshahVA** [comment]
Hello can we please add a PO and all the appropriate labels as indicated [in this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727392241472/ff14036aadadd12d211990fa217340424a24b8b4?fromVisitorModal=true&sender=premalshah3040)

**Comment by comaurice** [comment]
> Hello can we please add a PO and all the appropriate labels as indicated [in this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727392241472/ff14036aadadd12d211990fa217340424a24b8b4?fromVisitorModal=true&sender=premalshah3040)

Added

**Comment by pshahVA** [comment]
Thanks

**Comment by shaunburdick** [comment]
[platform/practices/zero-silent-failures/logging-silent-failures.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md)

**Comment by shaunburdick** [comment]
Service Tag Values:

- supplemental-claims
- notice-of-disagreement
- higher-level-review

**Comment by dfong-adh** [comment]
Would something like this be good for 4142 failures?
```rb
StatsD.increment('silent_failure', tags: { service: 'supplemental-claims', function: 'lighthouse form 4142 submission' })
```

**Comment by dfong-adh** [comment]
PR ready for review: https://github.com/department-of-veterans-affairs/vets-api/pull/19187
