### ISSUE TITLE
SOCKS access for Jesse House

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#94486]
### Your Name

Jesse House

### Your Email

jesse.house@va.gov

### Your GitHub Handle

jhouse-solvd

### Your Role and Team

Product Crew Lead on the Lighthouse Public API Platform

### Product Manager (PM) name and email

jesse.house@va.gov

### Product Owner (PO) name and email

peter.tebbenhoff@va.gov 

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEmJF0tyExLxjH+svlprSb/5m/BaY7GVtGGDmhdFdPwB jesse.house@jessehouse-YKFVJPF472

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/ffb5b9c2-711e-4c4b-ac93-8d6ba76bbb05)

### Lighthouse?

- [x] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by rmtolmach** [comment]
Jesse is listed as the **Product Crew Lead** on the Lighthouse Roster. 
✅ Added to Atlas: https://www.va.gov/atlas/product_directory/team_members/991
✅ PR to add new key (and delete old): https://github.com/department-of-veterans-affairs/devops/pull/14777

@jhouse-solvd run `vtk socks setup` again, and you should be good!

I'm doing this to unblock Jesse. The process for adding Lighthouse members is not perfect yet! Somehow he's not able to grant permission to any tier 1 or devops tier 2 people to see the Lighthouse Roster 😕 so we're coming up with a fix for that. _In the meantime, please tag me if there are any more LH SOCKS requests and I will check the roster_ 🙂
