### ISSUE TITLE
Conduct desk research on the Board Appeals process and began pairing with BMT 1 engineers

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#94510]
Review existing documentation on this and have the team conduct preliminary research for CST BOA process with BMT1

**Comment by dysbo** [comment]
BE Engineering introductory meeting scheduled with Sam from BMT1 on Thursday, October 10, 2024.

FE Engineering introductory meeting schedule with Jerek from BMT1 on Tuesday, October 15, 2024.

Planned topics include:
1. Talking through any issues encountered while BMT2 engineers are working to get local development environments set up
2. Quick tour of the code base to showcase areas where updates are most likely going to occur
3. Talk through the process of submitting changes for PR review (who needs to be involved, etc.)
4. Discuss the system used for feature flagging
5. Identify opportunities in the near term to set up pairing sessions or transfer ownership of tasks from BMT1 engineers to BMT2 engineers
