### ISSUE TITLE
Sidekiq Admin UI access for [Brandon Cooper]

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#94513]
### Your Name

Brandon Cooper

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

coope93

### Your dsvagovcloud AWS user name (if applicable)

Brandon.Cooper

### Team, Role, and Company of the target individual

1010 Health Apps - Senior Full Stack Engineer - Ad Hoc

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [x] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [x] dev
- [x] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

COR Name is Pamela Jones

**Comment by bdech** [comment]
Found in Atlas
E-QIP confirmed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83274)

**Comment by bdech** [comment]
@coope93 You've been granted access to `dev`, and `staging`.
