### ISSUE TITLE
Update codeowners for pension and burials

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#94527]
# Overview
With the team ownership change, we should update the codeowners for pension and burials to reflect this change.
I've already changed the team name:
https://github.com/orgs/department-of-veterans-affairs/teams/pension-and-burials

Any references to @department-of-veterans-affairs/pensions should be changed to the new naming convention.
Any references to burials code that still uses benefits-non-disability can be changed.

# Tasks
- [ ] - Change codeowners for burials related code to our team.
- [ ] - Change codeowners for pension to reflect new team name

**Comment by balexandr** [comment]
@mjknight50 This was already done by Steve Cummings here: https://github.com/department-of-veterans-affairs/vets-api/pull/18826
