### ISSUE TITLE
[Discovery] Review past research studies for findings related to onsite search

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#9452]
- review yellow ribbon and logged in homepage studies for findings/notes around search
- any other past studies that have related findings?

**Comment by andaleliz** [comment]
@stephorkandatx I'll add details to this later, but went ahead and created it now so we don't forget.  Is there an epic I should associate it with created yet?

**Comment by stephorkandatx** [comment]
@andaleliz I've added it to the on-site search epic thank you!

**Comment by andaleliz** [comment]
I didn't turn up any great insights from previous research, unfortunately.  The participant comments that came up in my studies are captured below, but these aren't a trend seen across other studies or even participants in a single study.

**Yellow Ribbon Participating Schools Research**
- Participants resorted to site search when they didn't find Yellow Ribbon within 2-3 pages.
- Participants easily found the site search.
- Participants were hesitant to click on search results item under "top recommendations" because it was lacking a description.  The second listing on the page was identical to the top recommendation but did include a description.

**Logged-in Homepage Redesign Research**
- One participant was  frustrated by wide array of results spanning various VA business units (VHA, Cemeteries, etc), and date ranges.  They wished for a way to "limit it down" and search for specific areas within the VA
- [Analytics summary examined top search terms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5e024293babf383e7bf22c377d5a96b11f100fe3/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#people-are-searching-for-general-health-and-benefit-information-forms-and-some-specific-tasks-we-may-want-to-do-a-better-job-of-elevating) over the last 12 months on VA.gov

I came across [one document speaking to the design issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/7c2e502d370cde9dc8693f14b9954d99dce7e849/products/global/header-footer-and-navigation/secondary-header-footer/README.md#design-problems-for-users-on-a-va-website-that-is-not-vagov) related to search across subdomains, which is good for us to keep in mind. Not sure how this fits into the scope of our team's work.
