### ISSUE TITLE
App generator should comply with ES Lint rules

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#9453]
The Yeoman app generator creates files that violate ES Lint rules, namely `va/use-resolved-path`.

We should generate an app, see if there are other errors, and fix them.

**Comment by gunsch** [comment]
cc @cvalarida

**Comment by jhonnyoddball** [comment]
This [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12861) fixes all ESLint errors
