### ISSUE TITLE
Design: Create Prototype of OHI Medicare and HI section

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#94534]
Create a clickable prototype of the Medicare and Health Insurance section to present to IVC Claims and OHI processing team. This will support this [Figma file](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3267-182334&t=0T201CXULxf3Upct-4). The goal of the presentation it to show the IVC team what we are changing on the digital form from the original pdf. We will need to also confirm with them if we captured all of the data that they would need to complete a CHAMPVA enrollment/ update.

We will be presenting this to the Stakeholders on 10/16

Here's [an example](https://dvagov-my.sharepoint.com/:v:/r/personal/kevin_hoffman1_va_gov/Documents/Recordings/Veteran%20Digital%20User%20Experience%20Weekly%20Design%20Sync-20241007_180021-Meeting%20Recording.mp4?csf=1&web=1&e=DCIRYe&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) on how to present a clickable prototype and the PDF form

**Comment by rspope** [comment]
@baltes This prototype has been completed and reviewed with stakeholders. Please review and close the ticket.
[Figma file](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3300-77112&t=i9J2BONYHuXq5zhK-4)
[prototype](https://www.figma.com/proto/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-10-7959c-Form?node-id=3187-34818&node-type=canvas&viewport=9520%2C6628%2C0.28&t=i9J2BONYHuXq5zhK-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=3334%3A90280)
