### ISSUE TITLE
[CAIA Intake] Veteran Facing Forms: <form maintenance alerts>

### ISSUE THREAD

**Issue by JaciWilkinson** [department-of-veterans-affairs/va.gov-team#94539]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.

## Veteran Facing Forms

- **Product name: Form maintenance alerts **
- **Team name**:Veteran Facing Forms
- **OCTO product owner:** @humancompanion-usds 
- **Product manager:** @tbaker1026 
- **Designer(s):** @JaciWilkinson 
- **Slack channel:** #veteran-facing-forms
- **Dedicated content writer on your team (if you have one):n/a ** 
- **Dedicated a11y specialist on your team (if you have one): @jeana-adhoc **

## Your CAIA team:
_Filled out by CAIA_
- **IA:** 
- **Content:** 
- **Accessibility:** 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [x] Something else: creating standardized alerts for form introduction and review pages  

### What's the nature of your initiative and desired outcomes?
These alerts will autopopulate sections of the form introduction and review pages when an there is scheduled or unscheduled maintenance that prevents the form from being submitted. This is part of the zero silent failures initiative and its goal is to prevent users from attempting to submit a form during downtime and notify them of downtime and that they have to return to submit at a later time in a uniform way.

We're seeking feedback on both the content and IA of this work before 10/16/24 so we can have these alerts in place/ready to use by 10/29/24.  

## Supporting artifacts
- [Figma file with all designs](https://www.figma.com/design/EJzrjLM07kSoXRCQfo4RhN/WIP---Form-Maintenance-Alerts?node-id=3-10210&t=xe06XHHAxII3PJ1W-1) >> review and add comments to anything that's on the page titled "example user flows"
- **Please only leave comments in the Figma file do not edit content or designs directly**
- I directly adapted content from the [system messages section of the content style guide](https://design.va.gov/content-style-guide/error-messages/system) 

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ x] Yes
- [] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We're seeking feedback on both the content and IA of this work before 10/16/24 so we can have these alerts in place/ready to use by 10/29/24.

Accelerated design timeline - no research planned

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [x]  Yes
- [ ]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** TBD
- **What is the name of your engineer who will build the React widget?** TBD

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- **Hyperlinked Ticket Number: n/a ** 

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by JaciWilkinson** [comment]
Please let me know if anyone from CAIA needs access to the Figma file for leaving feedback in comments.

**Comment by laurwill** [comment]
Hey @JaciWilkinson , just requested access!

**Comment by laurwill** [comment]
Hey @JaciWilkinson , just checking in on this — I think we may have resolved everything in Figma. Any more content collab needed on these, or okay to close?

**Comment by laurwill** [comment]
I believe all the work for this intake is done, closing this.
