### ISSUE TITLE
[Content Fix] Yellow Ribbon Top Recommendation

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#9454]
## What happened?
The Top Recommendation description for the Yellow Ribbon program is lacking a good description.   Per @andaleliz, during a recent user testing session, a Veteran said this left him confused.

## Specs:
- Device: Desktop Web
- Browser: N/A
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/search/?query=yellow+ribbon
- Test User _(if applicable)_:

## Desired behavior
Go to Search.gov and update the Best Bet/Top Recommendation for Yellow Ribbon to include more descriptive text.

## Acceptance Criteria
- [ ] The Top Recommendation for the Yellow Ribbon program will be more descriptive and thus helpful to the user.

## Screenshot

<img width="809" alt="Screen Shot 2020-05-22 at 2 27 03 PM" src="https://user-images.githubusercontent.com/63107147/82698460-cbd42100-9c38-11ea-9f19-fefa0c197740.png">

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva @stephorkandatx. We can definitely assign a team member to address this particular page. But this appears to be a similar issue that I'd brought up recently around another page. So I'd like to talk about putting a process in place to address this holistically. We have meta descriptions for all of our pages, so let's discuss how we can set up a process/cadence for how to make sure those are reflected in Best Bets. Thoughts?

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA Yes, agree.  Worth noting: I've asked the Search.gov team to provide an Excel of the current batch of Best Bets/Top Recommendations live on site.   This will give us a complete view of what we have put in place over the past year +.

**Comment by johnhashva** [comment]
9/23: **Closing this ticket** as  I updated the Best Bet/Top Recommendation with the following descriptive text: _The Yellow Ribbon Program can help you pay for higher out-of-state, private school, or graduate school tuition that the Post-9/11 GI Bill doesn’t cover. Find out if you're eligible, and if your school takes part in this program._
