### ISSUE TITLE
CT-EYB: VET TEC & Bottom sheet UI Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9456]
Update controls & system content per testing recs
Includes limited bottom sheet adjustments
Review with UX team

**Comment by ccruzgra** [comment]
VET TEC prototype: https://bahdigital.invisionapp.com/share/RNIADY2EW4G

Reviewed VET TEC updates with EDU yesterday, and they said it was good to go.

BOTTOM SHEET: 
UXers recommend bottom sheet to slide up as the user scrolls down and the header in the profile page is out of view. 

@amyknox This story can now be closed.
