### ISSUE TITLE
Adding Oren Mittman to DSVA Slack

### ISSUE THREAD

**Issue by jsnider84** [department-of-veterans-affairs/va.gov-team#94577]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

- Please add oren@verdance.co as a full member.

**Comment by LEHigley** [comment]
do they have a VA email address?

**Comment by jsnider84** [comment]
> do they have a VA email address?

oren.mittman@va.gov. Thank you!

**Comment by jsnider84** [comment]
@LEHigley Are there next steps from our end? Apologies, this is my first VA project, so I'm still learning the process.

**Comment by jsnider84** [comment]
@eunicegar Any idea what we should do to progress this ticket forward? Thank you so much!

**Comment by jsnider84** [comment]
@LEHigley and @eunicegar we really need our engineering lead @nihil2501 authorized in slack. Is there anything at all we can do to escalate this? Thank you so much!
