### ISSUE TITLE
CT-EYB: Post-Test Prototype Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9457]
Update prototype to reflect post-test content updates

**Comment by ccruzgra** [comment]
Here are the new prototype links. The VET TEC mobile proto is still a WIP:
Schools - desktop: https://bahdigital.invisionapp.com/share/SDIADYE8CVM
Schools - mobile: https://bahdigital.invisionapp.com/share/Q6IADXOGVA3
Employers - desktop: https://bahdigital.invisionapp.com/share/SPIADYG4BUE
Employers - mobile: https://bahdigital.invisionapp.com/share/9ZIADYIGHYV
VET TEC - desktop: https://bahdigital.invisionapp.com/share/RNIADY2EW4G
VET TEC - mobile: https://bahdigital.invisionapp.com/share/5RIADYKQ2H3 (need to add our new approved programs ui and also to create the responsive table style for mobile)

**Comment by ccruzgra** [comment]
@amyknox All updates are in. This story can be closed.
