### ISSUE TITLE
Update link in New VFS Team Member Template

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#94592]
### Description
As I was going through the platform orientation checklist, I discovered that one of the links went to a 404 page (6th bullet point under **General**): 
`Review the [Getting help from the Platform in Slack guidance](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)`

### Relevant URLs
- Link: https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS => ART (Accredited Representative Tools)

**Comment by jknipes** [comment]
@shiragoodman would you be able to fix this link on the checklist?

**Comment by shiragoodman** [comment]
@jknipes yes. I'll add our teams label. Thank you!

**Comment by shiragoodman** [comment]
Issue has been resolved. Link is now directing to the correct page on Platform Website.
