### ISSUE TITLE
PW intake: Adding Spanish toggle to disaster help page from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#94600]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [x] Implementation of Translation widgets
- [ ] Something else

### Describe your request

We need to add a toggle to the new disaster help R&S page we published. https://www.va.gov/resources/disaster-help

The Spanish page hasn't been created yet but the page will be https://www.va.gov/resources/disaster-help-esp

There is no left nav work needed as these are R&S pages. 

### Time constraints / launch deadlines

This is a high-priority page as we are publishing ahead of Hurricane Milton. Since Florida has a large Spanish-speaking population we'd like to get this page live ASAP.

### Your product/team Slack channel

sitewide-content-accessibility-ia

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [x] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by FranECross** [comment]
@chriskim2311 It look like you've started working on this already, so I removed the needs refining label and changed the status to in progress.
