### ISSUE TITLE
Update want to file a bt claim page in eCheck-in app with CC content

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94605]
## Description 

IVC wanted to make it clear that BT is for VA appts and not CC appts. 

## Tasks

- [ ] Update content on the first travel reimbursement page in the eCheck-in app. ([Wireframe](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4550-7185&t=Y4q3b8XH3ZDpSX2A-4).)

**Comment by brianseek** [comment]
@benbrasso-agile6 does this change need to happen in both check-in and OH travel?

**Comment by benbrasso-agile6** [comment]
I believe I separated out the FE tickets for echeckin/precheckin vs. OH app

**Comment by brianseek** [comment]
@benbrasso-agile6 do you have a link to the other ticket? I think we should keep all of this work to a single ticket since we have shared components.

**Comment by benbrasso-agile6** [comment]
Ya'll completed it already - https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/1?sliceBy%5Bvalue%5D=department-of-veterans-affairs%2Fva.gov-team%2369812&pane=issue&itemId=80761056&issue=department-of-veterans-affairs%7Cva.gov-team%7C92827

**Comment by benbrasso-agile6** [comment]
The experience is a bit different between apps. E.g., OH uses the process list DS component, whereas eCheck-in does not. If this is a problem, let us know.

**Comment by brianseek** [comment]
@benbrasso-agile6 nice

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park / @cgednalske This is merged and ready to validate on stage, local, or in the screenshot in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/32693

**Comment by benbrasso-agile6** [comment]
Nice! @zach-park You want to make sure this change is moved up to check-in `Latest Design` and in check-in `production` Figma file?

**Comment by zach-park** [comment]
> Nice! [@zach-park](https://github.com/zach-park) You want to make sure this change is moved up to check-in `Latest Design` and in check-in `production` Figma file?

Both Figma files are updated

**Comment by benbrasso-agile6** [comment]
THanks Zach!

**Comment by benbrasso-agile6** [comment]
@brianseek close when you're ready

**Comment by brianseek** [comment]
Thanks @zach-park and @benbrasso-agile6 !
