### ISSUE TITLE
Create deployment EnvVars in vets-api parent helm chart

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#94628]
Modify the vets-api parent helm chart to create kubernetes Deployment Environment variables for the vets-api application.

Match the ENV variable name to the suggested name detailed in the "Suggested Param Store Path" tab of this doc - [https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=371837002#gid=371837002](https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=371837002#gid=371837002)

Also source the environment variable from the paramter store path detailed in the same tab of the google doc.

SCALE: approx. 600 environment values.
Out of scope - settings values that do not have a Suggested Path Prefix

NOTE - All param store values MUST be set up prior to merging

## Acceptance Criteria

 - [x] First batch of environment Variables are added to parent helm chart

**Comment by JoeTice** [comment]
An additional ticket was created for the completion of this work: [95667](https://github.com/orgs/department-of-veterans-affairs/projects/927/views/14?sliceBy%5Bvalue%5D=patrick-black-oddball&pane=issue&itemId=84519970&issue=department-of-veterans-affairs%7Cva.gov-team%7C95667)
