### ISSUE TITLE
Copy Parameters Store Values for parameter store normalization

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#94629]
Create Paths and key/values pairs for ALL Settings keys with a recommended parameters store path in the "Suggested Param Store Path" Tab of [https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=1404962702#gid=1404962702](https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=1404962702#gid=1404962702)

For each value, a parameter store value MUST be set for ALL static environments (dev, sandbox, staging, prod) - NO EXCEPTIONS.

SCALE - approx 600 settings = 2,400 Parameters store values

## Acceptance Criteria

 - [x] First batch of parameters store values are set

**Comment by JoeTice** [comment]
An additional ticket was created for the completion of this work: [95667](https://github.com/orgs/department-of-veterans-affairs/projects/927/views/14?sliceBy%5Bvalue%5D=patrick-black-oddball&pane=issue&itemId=84519970&issue=department-of-veterans-affairs%7Cva.gov-team%7C95667)
