### ISSUE TITLE
Analytics Implementation or QA Support for 10-10 Health Apps - Registration Only path MVP

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#94648]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - 10-10 Health Apps team

- **Product Name**

    - 10-10EZ Veteran Health Care application
      
- **When is the launch date?**
    - 10/3/2024

- **Provide the link(s) for Product/Page urls**
  
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/introduction
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/id-form
    - [NEW] www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/check-your-personal-information
    - [NEW] www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits-package
    - [NEW] www.va.gov/health-care/apply-for-health-care-form-10-10ez/care-for-service-connected-conditions
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/maiden-name-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-sex
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/demographic-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/veteran-address
    - www.va.gov/health-care/aapply-for-health-care-form-10-10ez/veteran-information/veteran-home-address
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/contact-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/basic-information
    - [NEW] www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/benefits-package
    - [NEW] www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/service-connected-care
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/pension-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/service-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/additional-information
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/toxic-exposure
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/radiation-cleanup-efforts
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service-dates
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/operation-support
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/agent-orange-exposure
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxins-or-hazards
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure-dates
    - www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/documents
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-use
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information-confirm
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-needed
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/marital-status
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-personal-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-additional-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-financial-support
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-contact-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependents
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependent-information
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/veteran-annual-income
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-annual-income
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/deductible-expenses
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicaid
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare-part-a-effective-date
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/general
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/va-facility-api
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/review-and-submit
    - www.va.gov/health-care/apply-for-health-care-form-10-10ez/confirmation

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - No funnel needs at this time
    
    - `hca-reg-only-flow` event

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - This feature has both an authenticated and unauthenticated path  
         - User vets.gov.user+16@gmail.com can be used to test for authenticated path, (new pages appear at the beginning of the form). 
         - Unauthenticated path has the new pages after the Compensation question, about the middle of the form

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/introduction](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/introduction)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/id-form](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/id-form)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/check-your-personal-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/check-your-personal-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits-package](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits-package)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/care-for-service-connected-conditions](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/care-for-service-connected-conditions)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/maiden-name-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/maiden-name-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-sex](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/birth-sex)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/demographic-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/demographic-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/veteran-address](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/veteran-address)
[www.va.gov/health-care/aapply-for-health-care-form-10-10ez/veteran-information/veteran-home-address](http://www.va.gov/health-care/aapply-for-health-care-form-10-10ez/veteran-information/veteran-home-address)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/contact-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/veteran-information/contact-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/basic-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/basic-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/benefits-package](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/benefits-package)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/service-connected-care](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/service-connected-care)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/pension-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/va-benefits/pension-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/service-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/service-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/additional-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/additional-information)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/toxic-exposure](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/toxic-exposure)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/radiation-cleanup-efforts](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/radiation-cleanup-efforts)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service-dates](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/gulf-war-service-dates)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/operation-support](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/operation-support)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/agent-orange-exposure](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/agent-orange-exposure)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxins-or-hazards](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxins-or-hazards)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure-dates](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/military-service/other-toxic-exposure-dates)
[www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/documents](http://www.va.gov//health-care/apply-for-health-care-form-10-10ez/military-service/documents)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-use](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-use)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information-confirm](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/share-financial-information-confirm)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-needed](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/financial-information-needed)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/marital-status](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/marital-status)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-personal-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-personal-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-additional-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-additional-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-financial-support](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-financial-support)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-contact-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-contact-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependents](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependents)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependent-information](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/dependent-information)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/veteran-annual-income](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/veteran-annual-income)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-annual-income](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/spouse-annual-income)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/deductible-expenses](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/household-information/deductible-expenses)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicaid](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicaid)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare-part-a-effective-date](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/medicare-part-a-effective-date)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/general](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/general)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/va-facility-api](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/insurance-information/va-facility-api)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/review-and-submit](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/review-and-submit)
[www.va.gov/health-care/apply-for-health-care-form-10-10ez/confirmation](http://www.va.gov/health-care/apply-for-health-care-form-10-10ez/confirmation)

**Comment by johnny-jesensky-adhoc** [comment]
@hdjustice -- Thanks for submitting this -- this is a relatively straight forward request, so we'll try to fit it into our next sprint, which starts tomorrow.

FYI @Blivaditis, @ChristineYoungZA

**Comment by Blivaditis** [comment]
@hdjustice the updated 10-10 EZ form funnel has been loaded and all 49 pages are appearing in Domo. Here is a screenshot of the forms page showing the funnel data. <img width="1377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95ef45839631f01d820115daa3f719ae450dfaf8/Screenshot%202024-10-21%20at%201.43.58%20PM.png" alt="Screenshot 2024-10-21 at 1.43.58 PM.png" />

**Comment by hdjustice** [comment]
Great, thank you!

**Comment by hdjustice** [comment]
@Blivaditis hey there, was the custom event we added included in the update?  
We didn't really need a funnel since this is a temporary experiment, but we did want to make sure the custom event was accounted for

>- What Events need to be tracked? NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration
>
>     - No funnel needs at this time
>
>     - `hca-reg-only-flow event`

**Comment by Blivaditis** [comment]
Yes the custom event is appearing in GA4, here is a[ report showing](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/apiuOOB9R8O-Dybq49pVsw) the specific event discussed
