### ISSUE TITLE
CC appointments and requests do not display the correct null state when patient comments is empty

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#94689]
## Summary

- The expectation from the design team is that when patient comments are empty, we should display "Other details: Not available" like other appointments/requests. Currently it displays "Other details: none" due to our [selector logic](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/appointment-list/redux/selectors.js#L213). See screenshot below.
- Our selector logic should be updated to match design expectations.

## Steps to Reproduce

Create a CC appointment or request without patient comments and view the details.

### Actual Result

Note that this is a cancellation page but it has the same logic as appointment details
![Image](https://github.com/user-attachments/assets/238fd6ef-bd88-4ad5-8b2a-05cc6ec500ea)

### Desired Result

When patient comments are not available, "Other details: Not available" should be displayed.
This affects:
- CC appointment details
- CC request details
- CC request cancellation page

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by JunTaoLuo** [comment]
Just noting here that after a conversation I had with @vbahinwillit that this bug is related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/94339. I suspect if we untangle the comments field, we'll also end up fixing this bug.

**Comment by ldelacosta** [comment]
UX will take a second look in staging.

**Comment by outerpress** [comment]
Looks good! Validated @ldelacosta @juntaoluo

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
