### ISSUE TITLE
10-7959f-1: Removal of feature toggle from staged release

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#94693]
To be completed once 10-7959f-1 is open to 100% of traffic in production.

This will remove the feature toggle and any other conditions of the feature toggle implemented by [10-7959f-1: Feature toggle for staged release](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/94344)

Ensure coordination with CAIA to publish the correct static page with widget removed.

**Comment by michaelclement** [comment]
[Documentation on removing a feature toggle](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#FeatureTogglesGuide-Removingold/unusedfeaturetoggles)

**Comment by reiting** [comment]
@baltes are we ready for this?

**Comment by michaelclement** [comment]
Main things that have to happen
1. Coordinate with CAIA
2. Remove feature toggle code from the frontend
3. Remove feature toggle code from backend
4. Manually delete references to the feature toggle from the databases in each environment

**Comment by michaelclement** [comment]
Frontend and backend PRs are up, waiting on approvals. I'll reach out to Laura to coordinate removing the React widget from the static page.

**Comment by michaelclement** [comment]
Until I hear from CAIA about removing the widget in production, I'm not able to move forward.

**Comment by michaelclement** [comment]
Laura said she will probably be able to swap the content this afternoon, I'll follow up here later.

**Comment by michaelclement** [comment]
Update from Laura: there were some other items that required her attention, but she's going to take the widget out tomorrow (11/5)

**Comment by michaelclement** [comment]
Update from Laura (11/5) - the static page (sans widget) is now being reviewed by their copy editor, so we're still blocked.

**Comment by michaelclement** [comment]
Static page removed as of last night. Going to merge the feature goggle removal code now.

**Comment by michaelclement** [comment]
@baltes This is ready to go. Thanks!
