### ISSUE TITLE
STEM: Testing Results Matrix

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9469]
Create Testing Results matrix for logging tasks & task scores
Mural for synthesis

**Comment by JenLJ** [comment]
Testing Matrix for STEM

[https://app.zenhub.com/files/133843125/1c40f3f1-48b5-46a0-8a88-6ce02a9a8e40/download](https://app.zenhub.com/files/133843125/1c40f3f1-48b5-46a0-8a88-6ce02a9a8e40/download)
