### ISSUE TITLE
Fill out UAT tracker plan template that BAH/PMD provides

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94713]
## Description 

Toni is responsible for providing a template to outline the system integration testing between Appts and EPS, as well as start the template for UAT in production. 

[VDSS and EPS UAT PI 1 S1 Scheduler Acceptance Originial  Doc_.docx](https://github.com/user-attachments/files/17544159/VDSS.and.EPS.UAT.PI.1.S1.Scheduler.Acceptance.Originial.Doc_.docx)

[UAT Test Plan VDSS and EPS Pilot V1.docx](https://github.com/user-attachments/files/17544163/UAT.Test.Plan.VDSS.and.EPS.Pilot.V1.docx)

## Tasks

- [x] Fill in template, working with larger team, once provided

**Comment by loripusey** [comment]
Who is Toni and do you have a link to the template?

**Comment by benbrasso-agile6** [comment]
Sent email to appropriate team members with draft document

Also here: 

[APPTS and EPS Integration User Acceptance.docx](https://github.com/user-attachments/files/17560628/APPTS.and.EPS.Integration.User.Acceptance.docx)
