### ISSUE TITLE
Adding Patrick Deutsch to DSVA Slack

### ISSUE THREAD

**Issue by vievemarg** [department-of-veterans-affairs/va.gov-team#94711]
Please add patrick.deutsch@adhocteam.us as a full member. Patrick Deutsch has joined the Watch Tower team as a SRE/SWE.

**Comment by LEHigley** [comment]
do they have a VA email address?

**Comment by vievemarg** [comment]
We are waiting on that @LEHigley

**Comment by LEHigley** [comment]
invite sent. please update their account to reflect their VA email address once they have access, and then you can close this ticket @vievemarg

**Comment by LEHigley** [comment]
status on VA account? @vievemarg

**Comment by vievemarg** [comment]
All set! Patrick.Deutsch@va.gov
