### ISSUE TITLE
QA updates: Contact Accredited Representative

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/va.gov-team#94719]
## Issue Description
QA for Contact Accredited Representative #91079

## Defects
- [x] Alert content can be the same for [organization select](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=8890-493083&node-type=frame&t=ZUTCaxAUQa7GnDXi-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A217022&show-proto-sidebar=1) and individual representative select. (This was something got updated the last time we refreshed the content after our last usability study with Veterans. Figma has been updated to reflect this) - in other words, remove conditional logic
- [ ] ~Hide icon from representative card. While it's not really hurting anything for it to be there, the idea was to have visual continuity between the card in the results list and the card on the contact screen.~
- [x] Padding should be consistent on top and bottom of alert 
![Image](https://github.com/user-attachments/assets/8d5e6393-4a5b-40cb-9202-9d7a33b7cf56)

## Acceptance Criteria
- [ ] Defects have been addressed

**Comment by oddball-lindsay** [comment]
The first point about the icon may be addressed with this PR https://github.com/department-of-veterans-affairs/vets-website/pull/32607

**Comment by jvcAdHoc** [comment]
1. The DRY up pr did not address the icon. That's a one line fix.
2. Waiting for a double check from @mtri on which of the two paragraphs should become the only one in use.
3. Have not looked at the padding yet

**Comment by jvcAdHoc** [comment]
Confirmed with Michael:
- The original individual content variation should be the only content in the warning alert
- The icon can stay
