### ISSUE TITLE
Adding Trevor Pierce to DSVA Slack

### ISSUE THREAD

**Issue by SilkeDannVA** [department-of-veterans-affairs/va.gov-team#94723]
Please add trevor.pierce@oddball.io (mailto:trevor.pierce@oddball.io) as a **full member**. They will join the CEDAR Benefits Management Team 2 project. Once they are in, we will add them to the appropriate channels.

If you have any questions or need clarification, please contact Silke Dannemann and/or Jeff Langworthy on DSVA Slack.

**Comment by LEHigley** [comment]
do they have a VA email address?

**Comment by SilkeDannVA** [comment]
They do not yet have access to their VA email address ***@***.***
), so the Slack invite must go to their corporate email.


*Silke Dannemann, PMP*  She/Her
Sr. Project Manager
M 301.455.4502   ***@***.***

<https://coforma.io/>
Read our Collectively newsletter on LinkedIn
<https://www.linkedin.com/newsletters/collectively-7019363458403995648/>

**Comment by LEHigley** [comment]
@SilkeDannVA invite sent. please update their account to their VA email address once they have access, and then close this ticket.
