### ISSUE TITLE
Documentation Site — Discovery & prep to launch post-MVP tool

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9477]
### High Level User Story/ies
As a VFS team member, I need a single source of truth for documentation for building on VA.gov that is robust and well-maintained, so that I can embrace self-service and develop in an agile way.

As a VSP team member, I want to be in a position to immediately migrate documents to the new documentation tool when it is procured, so that I can quickly give VFS and VSP better access to our documentation.

### Problem Statement 
VSP Content & IA made a recommendation to DEPO for a new documentation site tool on 4/29/20 (as tracked in #7567); software acquisition is likely to take few months still. In the meantime, there is a huge amount of prep work to do before an assumed migration happens — auditing docs, determining new IA, defining a crucial docs set for migration, etc. 

How might we prepare to launch a documentation site using a new tool while also providing short-term value to VFS teams leading up to the migration process? 

### Hypothesis or Bet
If we launch a documentation site in Confluence Cloud, then we will be able to provide customers with a better documentation experience that enables them to embrace self-service and develop in an agile way.

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.

### Success metrics 
- Readiness for migration (qualitative) — as estimated by Content & IA team

_Note the following success metrics for documentation site product overall:_
- Increase in the following as tracked by VSP teams: "Did VSP response include link to existing documentation? (Y/N)"
- Increase in the following as tracked by VSP teams: "If yes (above metric), did the docs link alone completely resolve this? (Y/N/NA)"
- [VSP KR] Increase in positive feedback from teams on the value of the platform quarter over quarter

### We will know we're done when...
- [ ] VSP team members are granted access to a new documentation software solution _(further work tracked in migration super epic)_ *or* we have pivoted this work away from awaiting software acquisition to re-examine a tooling recommendation (and that is tracked in a new, separate super epic)
- [ ] We have validated the taxonomy, the critical types of docs, and the information architecture of our ideal solution

### Artifacts
- [Documentation site product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/product-outline.md)
- Artifacts for tooling recommendation documented on ticket #7567

### Communication
- Team that owns this super epic: Content & IA

**Comment by drorva** [comment]
We considered using max.gov since it includes confluence.
Unfortunately, it looks like it does not provide a way to make spaces and pages public. The following screenshot show that. Even when setting the pages to the least restrictive permission, I still get prompted to log in when in incognito mode.

![Screenshot from 2020-07-08 10-07-31.png](https://images.zenhubusercontent.com/5e5433d11c68b67ee8c64154/a812f6bb-4377-44bd-891d-10e08563b9e9)

!![Screenshot from 2020-07-08 10-07-56.png](https://images.zenhubusercontent.com/5e5433d11c68b67ee8c64154/d907a733-b6a1-42a4-b8fd-c6138e2dda7b)

**Comment by mchelen-gov** [comment]
any reason not to use `va.gov-team` + Gatsby per https://github.com/department-of-veterans-affairs/va.gov-team/issues/9703#issuecomment-682190996?

**Comment by meganhkelley** [comment]
Hi @mchelen you can view the full documentation tool discovery results and summary here: 
* [recommendation summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/v2/confluence-recommendation-5-2020.md)
* [presentation](https://docs.google.com/presentation/d/1FUMIikoxUuMAKd5NhHcOHd6OvP9bnukhALsW6xG5_vY/edit#slide=id.p1)

**Comment by vbellissimo** [comment]
Cancelling/old task.
