### ISSUE TITLE
Forms-compatible calendar UI

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#948]
## Story
As a veteran, I want to be able to pick my appointment dates / times within a calendar so that I can easily tell what's available and what isn't without first trying different options in dropdowns.

## AC
- [ ] Calendar only shows available dates as clickable
- [ ] Calendar shows unavailable dates as greyed out
- [ ] In direct scheduling, once date selected, available times expand beneath
- [ ] In request flow, once date is selected, am / pm option expands beneath (confirm this behavior with @rtwell )
- [ ] Calendar shows dates and times in facility timezone (confirm this as well)
- [ ] Calendar shows available dates up to 45 days in advance (this specific number may change)
- [ ] Calendar shows available dates for two stacked months at a time
- [ ] Calendar includes 'next' / 'previous' buttons that allow veterans to advance months
- [ ] Calendar looks like [current mocks](https://vsateams.invisionapp.com/share/USU2W52K37A#/screens/385581689) (date should be clickable in the prototype)

**Comment by rtwell** [comment]
@goldenmeanie will be picking this up in my absence.
