### ISSUE TITLE
Enable SSOe for eBenefits

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#9480]
Coordinate with eBenefits team (Courtney Rive & Michael Walker) to enable outbound and inbound SSOe to eBenefits. The eBenefits team is launching id.me and MHV authentication flows as well as a few other changes scheduled for completion 6/24.

@ericbuckley could you please add technical details to this ticket? thx.

**Comment by ericbuckley** [comment]
@marriej there is [one open PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12661) right now to convert all of the eBenefits links created by the content teams, however the work that we've done to convert the links in vets-website has already been merged.

Once outbound SSOe has been enabled, we just need to flip a feature flag (`ssoe_ebenefits_links `) to enable this for all users.

Let me know if you need any more information.

**Comment by CoryTrimmUSDS** [comment]
It appears that EVSS does not have this in production. [See thread here](https://dsva.slack.com/archives/C8R3JS8BU/p1589393762200800).

This could be something that could be a fast-follow on for work after SSOe Outbound is up and functioning at a better level.

CC: @jholton @benniemosher @christine-dillman

**Comment by joeniquette** [comment]
Unlikely this ticket will be completed in its current state. When eBenefits is ready for SSOe then we can create a new effort for it.
