### ISSUE TITLE
[FE] My VA Forms Status: Remove 21-0966 (Intent to File) from info accordion on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94811]
## Background
We learned that are potentially two paths form 21-0966 (intent to file) can take when the user submits, one of which results in the form _not_ appearing on My VA post-submission. There is a long term solution to allow this to work, but for the purposes of MVP we are going to remove it from the BE so that it will not display on My VA regardless of the path the form takes. We also need to remove the form from the informational accordion on My VA so that we do not confuse users.

![Image](https://github.com/user-attachments/assets/eb140eec-ae4a-4847-8514-0bea096065af)

## Tasks
- [ ] Remove form 21-0966 from the list of forms in the copy in the informational accordion 
- [ ] Tag Matt for validation

## Acceptance Criteria
- Form 21-0966 no longer appear on My VA post-submission
- Form 21-0966 still appears as a draft form when the user creates it but does not submit it

**Comment by mattmarino-adhoc** [comment]
Reviewed in staging, LGTM
