### ISSUE TITLE
Add eBenefits content to modal

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#9481]
Once SSOe is enabled to/from eBenefits permanently, edit the modal to mention eBenefits (as shown in the attached screenshot) without any further feature flag checks.![Screen Shot 2020-05-26 at 7.04.46 AM.png](https://images.zenhubusercontent.com/5e5d21ccbf668393ce8d133e/a90290e3-8b98-4bae-8716-77247c131e25)

**Comment by hinzed1127** [comment]
I've added logic to conditionally display the mentions of eBenefits and benefits based on if the eBenefits links feature flag is on. This ticket should now be work to remove that extra logic once we can permanently enable all SSO-related features.

**Comment by christine-dillman** [comment]
Waiting on eBenefits to except MHV and ID.me before we can complete this ticket.

**Comment by AGarcia-Clarity** [comment]
@nsoutouras  This is already implemented. Closing.
