### ISSUE TITLE
[BE] My VA Forms Status: Remove 21-0966 (Intent to File) from My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94810]
## Background
We learned that are potentially two paths form 21-0966 (intent to file) can take when the user submits, one of which results in the form _not_ appearing on My VA post-submission. There is a long term solution to allow this to work, but for the purposes of MVP we are going to remove it from the BE so that it will not display on My VA regardless of the path the form takes.

## Tasks
- [x] Remove form 21-0966 from BE table
- [ ] Move to validation for testing

## Acceptance Criteria
- Form 21-0966 no longer appear on My VA post-submission
- Form 21-0966 still appears as a draft form when the user creates it but does not submit it

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Any team member
- _How can this work be validated?_ 
  1. Log into staging with user 100 (or any LOA3 staging user who does not already have an intent to file submitted)
  2. Beginning filling out form 21-0966 but **do not** select that you are a Veteran (select spouse or representative options)
  3. Partially complete the form, allowing it to save
  4. Navigate to My VA
  5. Confirm the draft of 21-0966 you were just working on still displays on My VA in the Benefit applications and forms section
  6. Return to the form
  7. Complete and submit the form
  8. Navigate back to My VA and confirm you _do not_ see the submitted form 21-0966

**Comment by mattmarino-adhoc** [comment]
Tested some scenarios, no sign of the Intent to File showing up on My VA - LGTM @tpharrison
