### ISSUE TITLE
[CAIA A11y Research]: Sitewide Public Websites, Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-team#94815]
> [!NOTE]
> **High-Level Overview**: Sitewide Public Websites Discharge Upgrade Wizard
> - **Research Timeframe**:  **Pilot**: Oct. 16 **Participants**: Oct 22-Nov 1
> - **Pilot 1**: Mobile with Screen Reader: Ticket - 94866 
> - **Assistive Tech Users**: `3` AT Users (13 in full research; 3 AT segment)
> - **Artifacts Available**: [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/research-plan.md) and [Convo Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/conversation-guide-at.md)
> - **Testing Environment & Schedule:** [Staging Test Environment](https://staging.va.gov/discharge-upgrade-instructions/introduction) and Source of Truth for Scheduling (Link) 
> - **Assistive Tech Being Used**: `Screen Readers` or `Screen Magnification`
> - **CAIA Internal Doc:** [**CAIA Raw Session Notes: Google Doc**](https://docs.google.com/document/d/1hAXf9SwxNiNdjU76bGe8xr8cNuqETj3rQ0F7ETxLT-w/edit?usp=sharing)
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- **Pilot (Mobile):** 10/16/2024 #94866
    - @mutiaadhocteam (pilot)
    - @coforma-jamie (co-pilot)  
- **Research Session Support:**
    - @sara-amanda `October 18 – 25, 2024`
    - @mutiaadhocteam `OOO October 18 – 25, 2024`
    - @SarahKay8 
    - @coforma-jamie 

    
</details>

## About the Team

- Team name: Sitewide Public Websites
- OCTO-DE product owner: Michelle Middaugh (PO), Amanda Klausmeier (VA UX Lead)
- Product manager: Fran Cross
- Designer: Jordan Wood
- FE engineer: Chris Kim
- Product/team Slack channel: #sitewide-public-websites

<details><summary>Toggle to view more intake research ticket information</summary>

### Do you have an accessibility champion?

Yes, we have a champion

### If you have an accessibility champion, what's their name?

Laura Flannery

### Calendar checking

- [ ] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [ ] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [x] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

</details>

## About the Research

The team is looking to enhance the edit flow to account for questions with branching logic.

<details><summary>Toggle to view the team's research goals.</summary>

### Research Goals

> 1. Veterans can understand how to edit an answer that introduces branching logic and navigate back to the review page.
> 2. Veterans can understand why they may be asked additional questions when editing an answer to a particular question.
> 3. After editing a question, updates to the review page are clear and easy for Veterans to understand.
> 4. Veterans can navigate through the entire flow using the subtask pattern with ease.
> 5. Veterans that use assistive technology, like screen readers or screen magnifier technology, can navigate through user flows with ease.

> We will conduct remote moderated usability testing to observe research participants using the Discharge Upgrade Wizard in a live coded environment (staging or production) with the updated sub task pattern. This will allow us to use the current branching logic and our experimental edit flow pattern.

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

### Timeframe

<details><summary>Toggle to view research timing information.</summary>

- **Pilot sessions:** Oct 15-21 (requesting one session - mobile)
    - Scheduled: 10/16 #94866
- **Participant sessions:** Oct 22-Nov 1

### Length of sessions

- **Session length:**
    - `TBD` 
    - **AT Session Timing Examples**: 
        - `90` minutes (screen reader or alternative navigation tool)
        - `60` minutes (screen magnification tool)
        - **Buffer time between sessions:** `30` minutes
        - **Maximum sessions per day:** `2`

</details>

###  Testing Schedule

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

<details><summary>Toggle to view time-related items</summary>

#### Enter Testing Information
- **Dates**: Oct. 22, 2024 to Nov. 1, 2024
- **Times**:  `TBD`
- **Planning to Recruit `#` Veterans for**:
     - minimum of `#` sessions with screen reader users
     - minimum of `#` sessions with alternative navigation users
     - minimum of `#` session with a screen magnification user

#### Examples
- **Date Range Example**: _Typically around `2` Weeks_
- **Timing Example**: _`9-10:30am`, `11-12:30pm`, `1-2:30pm`, `3-4:30pm` EST_
- **Recruitment Example**: _Planning to Recruit `12` Veterans for: a minimum of `3` sessions with screen reader users; minimum of `2` sessions with alternative navigation users; and a minimum of `1` session with a screen magnification user._

#### Source of Truth
Testing Schedule (🔗 `To be Provided` as source of truth;  **_also see table in this ticket_**

Please use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available
------------------|------------------|--------------|--------------|--------------|--------------|--------------
Pilot | 10/16/24, 2-3 p.m. EST | VoiceOver, JAWS, etc `TBD` | **Mobile**; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | **Pilot** | @mutiaadhocteam  @coforma-jamie 
P 1 of 3 |10/#/24, #:##-#:## #m | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | `TBD- Based on a11y availability`
P 2 of 3 | 11/#/24, #:##-#:## #m | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | `TBD- Based on a11y availability`
P 3 of 3  | 11/#/24, #:##-#:## #m | VoiceOver, JAWS, etc `TBD` | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | `TBD- Based on a11y availability`

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

### Supporting artifacts (if any)

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/veteran-military-records/discharge-upgrade-wizard)
- [Prototype or mockups](https://staging.va.gov/discharge-upgrade-instructions/introduction)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/conversation-guide-at.md)

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket 10/11/2024
- [x] Receive prototype from Team
- [x] **Links**: Research Guide and Convo Guide Support
- [x] **PILOT CALENDAR HOLDS** - on the A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) `HOLDS ON CALENDAR FOR DATE RANGE`
- [x] **PILOT SESSION MOBILE: SCHEDULE** Pilot session with team. `Conduct around 10/16-21/2024` 
- [x] **PILOT SESSION MOBILE: CREATE TICKET** See `related tickets task list` in this ticket.
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available. `HOLDS ON CALENDAR FOR DATE RANGE`
- [ ] Receive Source of Truth for Scheduling 🔗 (Examples: Google Sheet, Slack Canvas, etc.)
- [ ] **Requested device breakdown:** Desktop, Mobile and Tablet
- [ ] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support.
- [ ] **Updated Holds:** waiting on official invites (table to be updated in this ticket)
- [ ] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean) Updated holds x/xx/2024
- [x] **Review research folder and assets**
- [x] **OFFICIAL RAW RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1hAXf9SwxNiNdjU76bGe8xr8cNuqETj3rQ0F7ETxLT-w/edit?usp=sharing)
- [ ] **Participate in research** **Date Span:** `10/22/2024` and `11/1/2024`
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
- [x] **TEMPLATE SESSION NOTES**: Create [CAIA notes document](https://docs.google.com/document/d/1hAXf9SwxNiNdjU76bGe8xr8cNuqETj3rQ0F7ETxLT-w/edit?usp=sharing) for a11ys to use during the sessions
```

```[tasklist]
### VFS TEAM Tasks
- [x] Tag @Naomi Eke in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH) Link to VA [OCTO Slack Thread 10/10/2024](https://dsva.slack.com/archives/C8E985R32/p1728593064618919)
- [ ] Your team's researchers and observers read through platform guidance on [research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users) and have also read and learned [how to be respectful of participants with disabilities](https://depo-platform-documentation.scrollhelp.site/research-design/disability-etiquette)
- [ ] Your team's researchers have read through the resources for researchers on the VA Platform's [Accessibility on Va.gov page.](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-on-va-gov#AccessibilityonVA.gov-ResourcesforResearchers)
- [ ] [Inclusive Recruitment Strategies](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md)
- [x] Consider [creating your prototype in CodePen](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen) for the most accurate results - `Using Staging`
- [x] `Recommending Pilot` Review our [assistive technology pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) and request a pilot, if desired - `REQUESTED MOBILE`
- [x] Request pilot sessions with CAIA a11ys  `
- [x] Schedule pilot session with CAIA a11ys (Mobile) **[Available](https://dsva.slack.com/archives/C8E985R32/p1728662548407519?thread_ts=1728593064.618919&cid=C8E985R32)**: 10/16, 17 or 18 (1-3 p.m. CT)
- [x] ~Schedule pilot session with CAIA a11ys (Desktop)~ `REQ. MOBILE ONLY`
- [x] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section.
- [ ] **SPECIFIC DATES NEEDED** See `Table` in the ticket above. Please provide date range and slots for AT sessions being planned. `Estimated Start: Oct. 22/Nov. 1`
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in the `Table` in the ticket above.
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (@sara-amanda)
- [ ] **Device Detail:** Desktop, Mobile and Tablet - Device breakdown needed for session prep
```

```[tasklist]
### Related Tickets
- [ ] #80777
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/94866
```

**Comment by coforma-jamie** [comment]
@thejordanwood, I reviewed your conversation guide! It looks great, just wanted to note a couple of things for you to consider:

**2 hour sessions:** While it’s recommended to give extra time for assistive tech users, there’s a good chance that you won’t need the full 2 hours to complete all the tasks. Couple of recommendations:

* Screen magnification users really don’t need the extra time (unless they have a cognitive disability as well). They navigate a web page the same as non-AT users, just zoomed in\! So you can safely reduce the amount of time for those users, IMO.  
* Less advanced screen reader users will take more time, but it’s definitely possible to end before the 2-hour mark. Maybe instead of “This entire session should take about 2 hours,” say “This entire session will take up to 2 hours?”

**“Share sound”:** A heads up that if the participant is using a phone or tablet, there won’t be a share sound button, and very likely you won’t hear their screen reader speaking. You *will* see a prominent focus indicator surrounding whatever item on the page is being read aloud. You can also ask those folks in particular to speak what actions they’re taking, since you won’t be able to hear them.  

**Screen mag over Zoom:** A heads up that often, screen mag doesn’t visually come through over Zoom, depending on the means of the magnification (browser text size increases will show, full-screen zooming in and out often won’t). So don’t panic if you don’t see the magnification, just double-check with the participant and let them know that you don’t see it on your end.

**Comment by sara-amanda** [comment]
# CAIA a11y Research Support

@thejordanwood   _Thank you for submitting a research ticket with CAIA! Our a11ys are looking forward to working with you on your latest research project._ 

## Next Steps
**The following are the initial, next steps in our process:** 

- [ ] Review the refined ticket above. 
- [ ] Review the VFS Team Task list items, that will assist us in supporting you.
- [ ] If available, let us know what assistive technology you are looking to test users with. 
- [x] **Generic holds** have been set on our capacity calendar. 
    - [ ] When available, please send us (@sara-amanda ) the invites from Perigean to add to our capacity calendar. 
- [x] We have scheduled your [pilot session](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) for 10/16 at 1 p.m. Central, with our CAIA a11ys, so that we can test your prototype with the AT you will be testing real users with. #94866
    - [ ] Right now we have: Mobile listed and screen reader. If there is a specific screen reader you would like used, please let us know. 

_**We are happy to answer any questions you may have, along the way. Thank you for reaching out to us and we are happy to help!**_ 

cc: @NaomiPMC @artsymartha68 @coforma-jamie @mutiaadhocteam @SarahKay8

**Comment by thejordanwood** [comment]
@coforma-jamie Thanks for reviewing! I updated the copy about the session length to what you suggested and added a couple of notes so that I would remember your heads up about the screen readers and magnifiers.

**Comment by coforma-jamie** [comment]
I checked in with the team - Laura F will be handling AT tech support; CAIA's work is done on this ticket. [See Slack thread.](https://dsva.slack.com/archives/C52CL1PKQ/p1729524030777599)
