### ISSUE TITLE
[10/10/2024 - 5:18PM ET] Monitor incident - Missing PEGA status

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#94827]
Per playbook, opening ticket to track details of this [DD monitor alert](https://dsva.slack.com/archives/C06RQR7V9CM/p1728595123325609).

**Intake**
- [X] PM (Bo) and DM (Andrea) have been notified
- [X] PM and DM confirmation of ticket creation

**Investigation**
- [x] Verify that vets-api is receiving submits from vets-website
- [x] Verify that files are sent successfully to s3
- [x] Verify that the callback API is available
- [x] Determine whether the issue arose due to a deployment, either by the IVC Forms team or the PEGA team.
  - [ ] IVC
    - [ ] If root cause has been identified as an issue in vets-website or vets-api, notify PM and DM to determine next stpes with PO
  - [x] PEGA
    - [x] If root cause has been identified as an issue outside of vets-website and vets-api, work with the PM, DM, and PO to determine contacts and next steps.

**Resolution**
- [X] Acknowledge monitoring alerts in slack
- [x] IVC Forms engineering will provide updates on development and deployment of a solution and its status in each environment
- [x] IVC Forms engineering will notify PM and DM when resolved
- [x] IVC Forms engineering will monitor outstanding missing statuses and ensure they are cleared appropriately. No statuses should be deleted or cleared without agreement from PO and or PM
- [x] If traffic to the site has been altered, PO or PM will determine when to return to previous levels.

**Comment by michaelclement** [comment]
@baltes @andrea-merrill @cloudmagic80

**Comment by michaelclement** [comment]
@baltes @andrea-merrill @cloudmagic80

**Comment by cloudmagic80** [comment]
<img width="1966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTg4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--780fb4f3963c7aa9ae87c32f3f55a6455d81f4fe/Screenshot%202024-10-10%20at%204.45.00%E2%80%AFPM.png" alt="Screenshot 2024-10-10 at 4.45.00 PM.png" />

**Comment by michaelclement** [comment]
[For updates, please refer to the thread in DSVA](https://dsva.slack.com/archives/C06RQR7V9CM/p1728595123325609)

**Comment by cloudmagic80** [comment]
We will need to discuss with Cindy about my the case_id and pega_status is nil. It looks good in the s3 side. I'm not seeing any errors on the vets-api

**Comment by andrea-merrill** [comment]
Cindy might be ooo tomorrow, so Bo asked who we could work with.  I'll keep an eye on his response and we'll set up a call with them tomorrow.

**Comment by cloudmagic80** [comment]
Resolved: The DOCMP PEGA team's AWS parameter store had to be updated with the correct keys.
