### ISSUE TITLE
[CAIA Intake] Health Enrollment Team: 10-10EZ in progress email

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#94826]
The silent failure email was priority and this is the secondary request for in-progress email:
- [CAIA Intake] 10-10 Health Enrollment: EZ submission failure email #93979
- [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6580-432765&t=a6crzTxp7LKzwlRP-4)
- 1010 team ticket covering both emails: [UX, PM] 10-10EZ - Notifications: Submission Failure email content review #93766

cc @aliyahblackmore

**Comment by aliyahblackmore** [comment]
I already chatted with Jessica and Laura about this. I'll take a look at this next week.

**Comment by aliyahblackmore** [comment]
Hi @jessicastump 

The content updates for this saved in-progress email are in the FIgma file. 

You all are one of the first teams CAIA is supporting on this specific email template. So this content will help our team build out the template in the future - this means that the template that rolls out in the future may have some slight changes. We'll let you all know if you'll need to make any adjustments at that time!
