### ISSUE TITLE
[FE] My VA Forms Status: Post-launch code cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#94831]
## Background
Post-launch of forms status on My VA we need to a do a standard post-launch code cleanup to remove the feature flag.

_Are there are any other cleanup steps needed here?_

### vets-website repo
- [x] remove all instances of `myVaFormSubmissionStatuses` feature toggle
- [x] update unit and e2e tests if needed
- [x] ensure all unit and e2e tests still pass

### vets-api
- [x] open PR to remove `my_va_form_submission_statuses` from list of features 
- [ ] (opt) get team member to approve PR before pinging platform support

## Acceptance Criteria
- [ ] Feature toggle removed from code
- [ ] Feature toggle removed from toggle manager
- [ ] Feature still functioning as intended

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Dev
- _How can this work be validated?_ 
  1. ...
  2. ...

## Resources
- ...

**Comment by ACParker89** [comment]
@a6marinos @allisonlu @DanielMiller-agile6 @mattmarino-adhoc Do we still need this or is it covered elsewhere?

**Comment by mattmarino-adhoc** [comment]
@ACParker89 Not sure on this one, I leave it up to engineering

**Comment by allisonlu** [comment]
PRs have been opened:
- cleanup in FE `vets-website` repo: https://github.com/department-of-veterans-affairs/vets-website/pull/33081
  - current blocker: [some tests are affecting the CD pipeline](https://dsva.slack.com/archives/C5HP4GN3F/p1732049220782879)
- remove toggle from `vets-api` repo: https://github.com/department-of-veterans-affairs/vets-api/pull/19521

**Comment by allisonlu** [comment]
both PRs have been merged! ready for validation.

## to validate:
1. ensure the [feature flag is turned off on staging](https://staging-api.va.gov/flipper/features/my_va_form_submission_statuses) (since it hasn't been deleted from the cache yet)
2. log into staging as user 58
3. navigate to **Benefit applications and forms** section
4. confirm that you still see statuses within the form cards

**Comment by asiisii** [comment]
Verified changes on the staging environment using the +58 test user, ensuring the `my_va_form_submission_statuses` feature flag was turned off during testing 🚀

![Image](https://github.com/user-attachments/assets/ec23854d-b1ad-4fb0-8ac0-8f94d6561e97)
