### ISSUE TITLE
[Congressional] V12290868 Due 11/20/24 Congresswoman Strickland 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#94849]
## Issue Description
Veteran’s name and gender still has not been updated on the VA.website.

https://app.slack.com/client/T03FECE8V?selected_team_id=T03FECE8V
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
10/8: Issue sent to Jeremy, on the EVSS team by Vicki C. for review and resolution.

Update from Jeremy: EVSS is looking into this issues and hoping to have it resolved tomorrow (10/9), if not before.

**Comment by Kimberley2023-CSM** [comment]
10/14: Reached out to Jeremy for status update.  Company closed in observance of Indigenous People Day.
