### ISSUE TITLE
Content for Id.me SAML Warning 

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#9485]
Id.me is able to add text to prepare users for the possibility of encountering the SAML 60 error. Their proposed text is as follows:

"If your session took longer than 10 minutes you may receive an error message when being redirected to the VA. If you encounter this error, simply log back in to the VA application using your id.me credentials."

Review for placement and simplification of [content.

![ID.me_VA Image.png](https://images.zenhubusercontent.com/5e5d21ccbf668393ce8d133e/6aea906d-e13e-4471-80f8-ddabb53563e0)

**Comment by bridgethapner** [comment]
@peggygannon Would you be able to review this proposed copy? 

"If your session took longer than 10 minutes you may receive an error message when being redirected to the VA. If you encounter this error, simply log back in to the VA application using your id.me credentials."

Here is the context: There are some errors we know users may run into in the process of signing into VA sites through SSOe, and we're trying to put copy in place to explain what a user should do if they run into a problem. In this case, users who take longer than 10 minutes to log in would need to perform login again in a faster timeframe.

**Comment by peggygannon** [comment]
Hi, @bridgethapner Here is my recommendation for this message. Please let me know if you have any questions or need additional tweaks. 


*Note:** If it takes you longer than 10 minutes to sign in, you may get an error message when being directed to VA.gov. If you get this message, you can simply sign back in to VA.gov using your id.me account.

**Comment by marriej** [comment]
Hi @peggygannon unfortunately, this error could occur when a Veteran originates from other sites besides VA.gov so the message needs to be more generic, while being accessible as well.
Thanks.

**Comment by peggygannon** [comment]
@marriej hi, alexis, thank you for the clarification. Let me know if this messaging is general enough: 

**Note:** If it takes you longer than 10 minutes to sign in, you may get an error message when being directed to a VA site.  If you get this message, you can simply sign back in to the VA application using your ID.me account.

**Comment by peggygannon** [comment]
Hi, @marriej and @bridgethapner checking in to see if the message ^^ is good ? or if you need additional tweaks from me?

**Comment by marriej** [comment]
Thanks @peggygannon this is good to go.
