### ISSUE TITLE
Flipper UI access for [Kyle Soskin]

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#94856]
### Your Name

Kyle Soskin

### Your GitHub handle (Flipper UI access is managed through GitHub)

kylesoskin

### Team, Role, and Company of the target individual

Benefits & Claims (BDEX2/Carbs) - Engineering Lead [Coforma]

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need this access to test and develop vets-api flippers for backend code related to features for the 526 disability flow.

**Comment by davidpetras** [comment]
@kylesoskin you have been granted access to `lesser environments` and `prod`
