### ISSUE TITLE
Update URL for Veteran Health Information Card 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#94861]
## Description
We are currently linking to the wrong thing that is not the _actual_ Veteran Health Information Card on the landing page. ([See Slack thread here from Kaitlin Fink](https://dsva.slack.com/archives/C0581MN69TJ/p1728661316023329?thread_ts=1728311401.091389&cid=C0581MN69TJ)) 

The actual link for this routes to a different VHIC that is required for Veterans when they check-in for their appointments and we need to fix the link to route Veterans to the correct card asap.

### User story

As a Veteran, I want to be able to find information about how to get a copy of my VHIC so that I can be prepared and have what I need to check-in for my appointments and manage my care. 

### Notes
- All of the links in that first column at the bottom of the landing page should be VA.gov resources once this one is updated

### Possible tasks:
- [ ] Update destination URL for the Veteran Health Information Card:
  - current URL: https://mhv-syst.myhealth.va.gov/mhv-portal-web/health-information-card
  - needs to be: https://www.va.gov/health-care/get-health-id-card/

## Acceptance criteria
- [ ] Link has been updated to route Veterans to the correct page for the VHIC
- [ ] QA review

**Comment by sterkenburgsara** [comment]
Story point estimate: 1. But I'll leave to @nichia to confirm/add points based on her analysis. Thanks!

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the "Veteran health information card" link on the MHV landing page is directing users to this URL: https://staging.va.gov/health-care/get-health-id-card/ as expected
