### ISSUE TITLE
SOCKS access for Penny Lischer

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-team#94876]
### Your Name

Penny Lischer

### Your Email

penny.lischer@agile6.com

### Your GitHub Handle

penny-lischer

### Your Role and Team

Fullstack Engineer Debt Resolution

### Product Manager (PM) name and email

Denise Coveyduc: denise.coveyduc@va.gov

### Product Owner (PO) name and email

Denise Coveyduc: denise.coveyduc@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIARzIgCg2Ke3oOc4l7SCzNVIGvvq1T0NxRorEuF3pB2m penelopelischer@Penny-Lischer.local

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/fd82e899-392a-4af9-9310-343bdf4c3838)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by ph-One** [comment]
SOCKS access granted.
