### ISSUE TITLE
Refactor cross-domain redirects in `vets-website`

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#9487]
# Description

The current pattern for adding cross-domain redirects in `vets-website` is quickly [becoming difficult to manage](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/proxy-rewrite/redirects/crossDomainRedirects.json). It would be great to separate out the redirects in separate files (maybe not a great idea for maintainability since searching for a previous redirect would be that much more difficult) or at least the ability to add comments to the redirects to group them by ticket for future reference.

It would also be nice if the redirect logic were the same as our implementation in `devops` so that the developer experience is more or less the same. We should also develop a way to test these redirects before shipping them to staging/prod.

# Acceptance Criteria

- [ ] Create an e2e testing suite for redirects in `vets-website` (cross-domain redirects).
- [ ] Separate redirects for readability via code comments.
- [ ] Add regex support for cross-domain redirects that mirrors the same functionality as adding redirects in the `devops` repo.

**Comment by kelsonic** [comment]
Going to start working on this ticket today 🙂

**Comment by ncksllvn** [comment]
I'm thinking through the best way to do this...it also ties into how we can test the whole injection script, beyond just the redirects.
