### ISSUE TITLE
Show scheduled appts that aren't in vaos service yet

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94914]
## Description 

When a referral is scheduled/booked through EPS:

Step 1: Appointment retrieval from EPS. You can retrieve the Appointment with the details and status as of the last time WellHive interacted with the external provider's system for an update (e.g. when the appointment was just booked, or when WellHive last polled which happens every 24 hours). This is what Appointment.search returns. 

So, pull the booked appointments from the EPS appointment.search endpoint (/appointments) when a Veteran hits the Appointments page AND the Referrals and Requests page. 

When appointments are moved from EPS to HSRM and vaos service starts returning them, HSRM will return the appointment with the referral Id (or number).

Step 2: Compare referral Ids (or number) between appointments from EPS and HSRM (through vaos service). If ids match, exclude the EPS duplicate from the appointment list displayed to the Veteran.

Note: Based on [completed SPIKE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93946).

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created

**Comment by benbrasso-agile6** [comment]
Adding this info to this closed ticket; just so it's somewhere - 

Annotations added to Figma mvp page on the Appointments page and the Referrals and Requests page 

https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5434-4830&t=uVyyXHr8BUIFNtD2-4
