### ISSUE TITLE
Create UX onboarding documentation

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94913]
## Tasks

- [ ] Create UX CIE/Appts onboarding documentation

**Comment by benbrasso-agile6** [comment]
Anything missing that you'd like to see? @cgednalske @zach-park @loripusey @anita-halici 

[UX onboarding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/team/ux/ux-onboarding.md)

**Comment by cgednalske** [comment]
Not that I can think of - looks great and very thorough! 🎉

**Comment by loripusey** [comment]
Great job @benbrasso-agile6 , very thorough!
