### ISSUE TITLE
Create wireframe for intro page with content

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#94911]
## Tasks

- [ ] Create wireframe for new intro page for check in with content. Check in with Christina about feedback from IPT on userflow in the [Presentation](https://docs.google.com/presentation/d/145qZEsAgXjVHg-kLFxj4c7fQ6g5y6vl156qxzANMvoI/edit#slide=id.g309369826a2_0_97).

**Comment by benbrasso-agile6** [comment]
@cgednalske  please review ticket description and add an estimate number

**Comment by benbrasso-agile6** [comment]
@cgednalske reping

**Comment by cgednalske** [comment]
@benbrasso-agile6 I added an estimate of 2 yesterday. Do I need to add it in the new projects board too? 👀

**Comment by benbrasso-agile6** [comment]
I'll add your 2 to the other ticket, thanks

**Comment by benbrasso-agile6** [comment]
Wait see, the urls are being changed. Ummm. I think best practice is to go to board and then click on the ticket from there - https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/1?sliceBy%5Bvalue%5D=department-of-veterans-affairs%2Fva.gov-team%2362496

**Comment by benbrasso-agile6** [comment]
I added the 2

**Comment by benbrasso-agile6** [comment]
Incorrect view

![Image](https://github.com/user-attachments/assets/a4f06f45-9110-4941-8cf7-98e15b6893e7)

Correct view

![Image](https://github.com/user-attachments/assets/830d7bb8-0752-47d0-8c31-9ae2d158e94f)

**Comment by loripusey** [comment]
You can get to the Estimate field regardless of which link you use

**Comment by benbrasso-agile6** [comment]
I cannot; maybe we can demo later today

**Comment by benbrasso-agile6** [comment]
Left some feedback in Figma, @zach-park

**Comment by zach-park** [comment]
@cgednalske @benbrasso-agile6 , the Figma link is included and ready for review.

**Comment by cgednalske** [comment]
I think these versions make sense to test. My only question is do we need that mention of facility on V1. BUT I do think our testing can/will reveal the answer to that question. 

@zach-park has V1 been updated in the survey? If it has, I'll duplicate that for V2 so you can add that version in the V2 survey as well.

**Comment by cgednalske** [comment]
@zach-park the duplicated Version 2 study is also ready - in the same folder - if you can add the V2 images.

**Comment by zach-park** [comment]
@cgednalske , the version 2 is also updated now and ready for validation. Thank you!

**Comment by cgednalske** [comment]
@zach-park the intro page all looks good, so unless Ben has concerns this can be closed. 

But take a look at my Figma comment about the confirmation page in the surveys not matching the designs.

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) the intro page versions both look good, so unless Ben has concerns this can be closed.
> 
> But take a look at my Figma comment about the confirmation page in the surveys not matching the designs.

Fixed! :)
