### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by nhuckleberry6** [department-of-veterans-affairs/va.gov-team#94926]
### Name

Natasha Huckleberry

### Email

natasha.huckleberry@oddball.io

### Role

UX Designer

### Team

Mobile Feature Support including Military History

### Product Manager (PM) name

Pete Egan/Jennifer Brown

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to natasha.huckleberry@oddball.io. Let me know when you have an account created and I'll bump you up to edit access.

**Comment by nhuckleberry6** [comment]
Hey, thank you! I've joined the VA.gov Platform on Figma.
