### ISSUE TITLE
HLR | Fix informal conference validation

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#94935]
## What happened?

While testing the Higher-Level Review validation on the review & submit page, I noted that the validation error messages weren't showing up on the informal conference radio questions when the form data is undefined. It allowed submission without a value. This isn't a critical issue because the steps involved aren't possible without having using the save in progress menu

**Add the steps to reproduce the bug**:

1. Turn off `hlr_updateed_contnet` feature toggle
2. Start a new HLR form in staging
3. Use save in progress menu to jump to the review & submit page
4. Edit the informal conference page
5. Use "Update page" and note that no error shows
----
1. Turn on `hlr_updateed_contnet` feature toggle
2. Edit the informal conference page
3. Use "Update page" and note that no error shows

**Add a screen recording or photo**:

| Feature toggle Off | On
|----|----|
| ![toggle off, using update page while editing the required informal conference question doesn't show any errors and closes review page edit mode](https://github.com/user-attachments/assets/639551f6-932c-4f01-a117-9d38ca580982) | ![toggle on, using update page while editing the required informal conference question doesn't show any errors and closes review page edit mode](https://github.com/user-attachments/assets/6b3f88d8-c9a5-4714-8ce2-ba4def5ea7f4) |

## How severe is the problem?

- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [x] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

## What is the desired behavior?

Error message is shown if no value is selected

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by davidakennedy** [comment]
@Mottie and I hopped on a call and verified this together. Everything is working as expected.
