### ISSUE TITLE
Global | Review & submit page fix page error highlight

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#94938]
## What happened?

Some array pages are not correctly showing a chapter or page error.

**Add the steps to reproduce the bug**:

1. Start a Higher-Level Review form
2. On the issue page, add at least 2 issues
3. On the first area of disagreement page, use max characters in the text input
4. Navigate to the review & submit page
5. On the area of disagreement page, check at least one checkbox (an error will appear)
6. Open the second area of disagreement page and uncheck all the checkboxes & clear the text input
7. Use "finish this application later" link
8. Refresh the page
9. Continue the form
10. Submit the review & submit page
11. Note that the accordion chapter and first area of disagreement page title doesn't highlight (background should turn light red)
12. Edit the first area of disagreement
13. Uncheck all checkboxes
14. Use first area of disagreement "Update page" button
15. Note that the second area of disagreement page does highlight
 
**Add a screen recording or photo**:

Slightly alternate approach than the above steps to reproduce

![first area of disagreement has excessive text but no error shows on submission; after editing and unchecking the second and third checkbox, the error clears. Updating the page now shows an error on the second area of disagreement page](https://github.com/user-attachments/assets/5872d3c4-8282-4c4d-9ca5-225219a31fd4)

## How severe is the problem?

- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [x] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

## What is the desired behavior?

When there's an error on an array page, or custom page, the chapter & page should highlight

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by davidakennedy** [comment]
@Mottie and I hopped on a call and verified this together. Everything is working as expected.
