### ISSUE TITLE
Design feedback for Design intent Collaboration Covid Screening Tool

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#9493]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**

- Change the background of the buttons (currently in the “secondary button style”) to white for greater state contrast between checked and unchecked
- Change the typography for the questions to create a clearer hierarchy. I suggest exploring something that is sufficiently large and high contrast, but not in a bold weight to distinguish it more clearly from the header. Consider the VA intro text style. https://design.va.gov/design/typography#paragraphs. Using the H1 style for the heading and the questions results in insufficient contrast between the two; ownership isn’t clear.

**Try:**

- Try moving the sentence, “We won’t store or share your data” up with the first paragraph and add some padding between the header and nav bar

**Consider:**

- Consider the hierarchy of the typography. For question #3, consider listing the symptoms using the mobile H2 (Bitter 24px) 
-Consider variants (text size, button placement) for tablet and desktop sizes for future iterations
- Usability test to see if side by side buttons will work. I’m not convinced from your usability testing information that the side by side buttons are an issue - thumb reachability is not a human factor issue of orientation; it’s a human factor of distance from the bottom corner of the phone, depending on left handed or right handed.
- This is a great case for pushing our design system tools forward to support this use case. To that end, I don’t think including the VA header and footer is the necessary “checking the box” step for web brand consolidation. If this application is going to sit “outside” the IA of VA.gov, and only be accessible by text, it actually is a detriment to the application to provide full header navigation. I think web brand consolidation means a consistent experience: voice and tone is consistent, UI for similar tasks is consistent, and the brand of the VA is presented (visually) in a consistent way. Curious how you might use Ryan’s new minified header solution, or if you would propose a new “mobile web app specific” solution for header and footer that meets gov’t web site requirements, but focuses the user more successfully. 

**Definition of Done:**
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily, Crystabel, or Kevin will close the ticket once those things are all set. Thank you!

**Comment by artsymartha68** [comment]
@batemapf here are the design council issues. 

I opened #9610 to address button styling. 

We opened #9600 for the breadcrumbs.

I have a mockup attached to #9432 for styling and font sizing changes. We are juggling lots of feedback from lots of sources and stakeholders, as you might imagine.

**Comment by artsymartha68** [comment]
Closing this main ticket per our screener team review today. The sub-tickets cover the work products, nothing left to do on this main ticket.
