### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by yulia-melnikova** [department-of-veterans-affairs/va.gov-team#94966]
### Your Name

Yulia Melnikova

### Your GitHub handle (Flipper UI access is managed through GitHub)

yulia-melnikova

### Team, Role, and Company of the target individual

VA Medications, QA tester, ByLight

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by GWright321** [comment]
@yulia-melnikova you have been granted access to lesser environments
