### ISSUE TITLE
CC Technical Documentation & Diagrams

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#94979]
- Create technical documentation and diagrams (need URL location to store it)
- Copy over sequence diagrams from last ticket (https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/19?pane=issue&itemId=81619952&issue=department-of-veterans-affairs%7Cva.gov-team%7C93897)
- Make sure it covers the app at a high level
- Include high-level system diagram? (optional)

**Comment by lee-delarm6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/architecture/community-care-technical-documentation.md

**Comment by loripusey** [comment]
No longer using Palantir, so don't need this ticket, closing.
