### ISSUE TITLE
Flipper UI access for [Rajasree Venkatesh]

### ISSUE THREAD

**Issue by RajiVenkatesh18** [department-of-veterans-affairs/va.gov-team#94974]
### Your Name

Rajasree Venkatesh

### Your GitHub handle (Flipper UI access is managed through GitHub)

@RajiVenkatesh18

### Team, Role, and Company of the target individual

VA.gov Medications Team, Tester, American Communications Solutions LLC

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by GWright321** [comment]
@RajiVenkatesh18 You have been granted access to `Lesser Environments.`
