### ISSUE TITLE
Create Palantir connection, includes connection but not fully fleshed out endpoints

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#94981]
[ ] Create data "endpoint" via Palantir instructions, possibly requires setup help from Palantir admin according to their docs
[ ] Create palantir connection, able to pull data from palantir (whichever type works best, websocket, http, etc.) but most likely http if possible 
[ ] Test pull (via vets-api new connection just made) some data to make sure it works as expected

- Question, do we need to test this in staging? If so, feature flag ticket required

**Comment by loripusey** [comment]
obsolete
