### ISSUE TITLE
Midpoint Review - Design Feedback - Accredited Representation Management, digital submission designs (Appoint a Representative v2, Find a Representative v3, Representative Status Widget v2)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#94999]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: We currently have a lot of teams that use a lot of icons. We are trying to align those as best we can. Look at [our icon set](https://design.va.gov/foundation/icons) and see if any align with your icons. For example, the appointments team uses a building for in person appointments. We also have a new filter icon you could use, [Experimental Design Filter Icon](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3118)
- [x] Must: We have several products that have a "status" tied to them. Claims and appeals is one. [Collaboration Cycle for Veteran Facing Forms & Authenticated Experience - Form Status on My VA & Updated Confirmation Page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80272) recently come thru collab cycle showing the status of forms. Take a look at existing statuses and see if there is anything in those that may help you. Try to make it really clear what the status is. Also, consider adding a time frame or letting the user know they can contact the rep by phone/email if something is pending after a long time.
- [x] Must: Look at our guidance around [additional info components](https://design.va.gov/components/additional-info#when-to-consider-something-else). Per our guidance, only include critical information inside this component. This includes form fields that require a lot of explanation. Link to another page, consider an [Accordion](https://design.va.gov/components/accordion), or shorten the content. Collaborate with a member of CAIA to edit content and explore alternatives. Your additional info components have a bit too much content.
- [ ] Must: Take a look at the [how to apply template](https://design.va.gov/templates/forms/how-to-apply#example) and introduction pages for forms. I think there are some things you can lift from these templates to align with your content. For example, under how to apply you see options. If you can take some things from that template it will help with consistency, however, knowing your form is different it may not work and that is ok too.
- [x] Must: Change your slim alert to a [standard alert](https://design.va.gov/components/alert/) on the status widgets. Slim alerts are reserved for Immediate feedback to the user. You can also move content out of the alert if after styling it as a standard alert it does not work with what you have.
- [x] Should: Make the fill out online link an [action link](https://design.va.gov/components/link/action) so it stands out more. It seems to blend with all the other content right now.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [ ] Add the touchpoint labels
- [ ] Add the practice area labels
- [ ] Add the Collaboration Cycle initiative milestone

**Comment by mtri** [comment]
**Unchecked items with notes:**
>Must: Take a look at the how to apply template and introduction pages for forms. 
I think there are some things you can lift from these templates to align with your content. For example, under how to apply you see options. If you can take some things from that template it will help with consistency, however, knowing your form is different it may not work and that is ok too.

This has been considered and this content is housed on the Get help landing page which is the gateway to both the Find and Appoint experiences. We’ve worked with CAIA on this content and flow.
