### ISSUE TITLE
Content Review for Live Chat Escalation

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#94993]
## Issue description

> We're looking for content guidance on what has been shared as "standard to include" from working with the MHV team, while considering the impact of this content on the specific product goal of directing a Veteran to the live chat service.

---
## Tasks
- [x] Review 
- [x] Share with requesting team

## Acceptance Criteria
- [x] Feedback has been shared with requesting team

**Comment by laurwill** [comment]
@strelichl why doesn't this ticket have all the fields like target date, etc? Am I doing something wonky when I set these up?

**Comment by laurwill** [comment]
Weird, I dunno! Working now.

I provided suggestions to Dale in the intake ticket, moving to validate.
