### ISSUE TITLE
Review appeals terms for word list (content style guide)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#95]
Hi Randi - Can you take a look at this list of Appeals terms, which I think came from Allyce and/or through Beth Potts, and edit the definition text to fit our typical style in the word list definitions?  

https://design.va.gov/content-style-guide/word-list 

Please work with @bethpotts as she has background knowledge on some of these terms.  

I've added tracked comments to the doc for questions that I think the definition should address.

Another item to consider -- Should these go all under Appeals entry or alphabetically for each term? 

One last thing - this is NOT a priority over legacy, parity, and CMS related work. So please fit it into your schedule accordingly. Let's use this issue to keep track and revisit in a few weeks. 

Thank you! 
[Appeals Word List.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3229802/Appeals.Word.List.docx)

**Comment by RLHecht** [comment]
@jenniferlee-dsva These had all been added to the style guide before the transition. Am I right that @Karak888 can close this ticket?

**Comment by jenniferlee-dsva** [comment]
@RLHecht - correct! Can close.
