### ISSUE TITLE
[QA] 10-10CG Validate pdf deletion

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#95008]
Perform QA on https://github.com/department-of-veterans-affairs/vets-api/pull/18846 to ensure that the pdf file is being downloaded to the browser and being properly deleted from the server.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the PDF file is downloading and contains the info entered as expected and the PDF file is deleted from the server
