### ISSUE TITLE
Implement 4142 submission tracking

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#95001]
## Value Statement

**_As a_** developer

**_I want to_** be able to see submitted 4142s and their Lighthouse guid

**_So that_** so I can track and update their progress, and remediate any errors

---

## Background Context

- Sometimes forms and files that are submitted to Lighthouse fail later in the process. We need to have a record of the form, and its Lighthouse guid, and order to track those later failures

## Outcome, Success Measure, KPI(S), and Tracking Link

- Every submitted 4142 has a representation in the vets-api DB including the form info and Lighthouse guid

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by kayline** [comment]
Merged, needs staging validation (dev validation)

**Comment by kayline** [comment]
Staging test with 
vets.gov.user+38@gmail.com, icn: 1012845630V900607, for eye loss
