### ISSUE TITLE
[Feature] Update the header content on the Direct Schedule Workflow

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#95036]
## Description
We implemented the header content changes earlier this year for VA and Community Care Requests workflow. We are looking to modify the headers in the direct schedule workflow to align the changes we have done for the request workflow. 

## Requirements 

- [ ] Whe user is on the direct schedule workflow, they will see the updated content changes. 

### Design Assets
[Figma File](https://www.figma.com/design/5dWfMQkBCvEX9XYJsNdcT3/Change-direct-schedule-headings-to-questions-%7C-Appointments-FE?node-id=44-8190&node-type=instance&t=G1AR7aoaon5ncLAu-0) 

---
### Development Checklist

- [ ] Task 1
- [ ] Task 2

 ## Developer Reference
- [ ] [Swagger file]() (remove if not needed)
- [ ] [File path]() (remove if not needed)

## Definition of Done
- [ ] All task criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed, remove there is none)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/95036?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
@outerpress this ticket is ready for UX validation.

**Comment by outerpress** [comment]
@JunTaoLuo on the type of care page it looks like the "Home address" alert is now above the heading. Can this be moved back under the heading? (We want screenreader users to hit the page title, and the H1, before the alert heading and any subheadings so they have context on the page).

[For comparison here's what's on prod](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1272-181808&t=W6qupE1wzXd7CUz3-4). And here's a screenshot from that page on Judy:

![Image](https://github.com/user-attachments/assets/5bcbf553-3b21-41ac-b07f-2170b62ab627)

**Comment by outerpress** [comment]
@JunTaoLuo on the clinic choice page, when there's a single clinic, could you add a line break/space between the phone number and question?


![Image](https://github.com/user-attachments/assets/78ed6453-a0df-4209-bd49-0550a46e7869)

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for another look.

**Comment by outerpress** [comment]
Looks great @JunTaoLuo ! Validated

**Comment by JunTaoLuo** [comment]
Thanks everyone for getting this completed early @outerpress @vbahinwillit @jenniemc!
