### ISSUE TITLE
[Spike] To show the user they have already a booked appointment on the Calendar page [Direct Schedule]

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#95035]
## Request
Looking to improve the user experience when a Veteran already has a booked appointment scheduled at a later date. 

### Goal
To see what technical solution we can implement on the Calendar page to notify the user that they have selected a date and time that they have a scheduled appointment already. 

### Requirements to Consider
[Design concepts](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4893-28292&node-type=frame&t=ZZ04umRUnmOnzqUj-0)

---

## Tasks
- Answer the following questions:
  - Q1: Could we retrieve the user's booked appointments in the early stage of the direct schedule flow and notify the user that they have already scheduled an appointment with the same date and time. 
  - Q2: What technical solution is feasible for this request? 
  - Q3: Are there any design recommendations to implement the goal? 
  - Q4: What is the logic for the[ current alert as it exists today](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1247-3156&t=id1PCjxIx66vUqCs-4) (this alert is triggered on the last page of the scheduling flow)? And is this logic in the FE or BE?

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/95035?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by vbahinwillit** [comment]
- Q1: Could we retrieve the user's booked appointments in the early stage of the direct schedule flow and notify the user that they have already scheduled an appointment with the same date and time. 
  - A1: Yes. Booked appointment have already been retrieved to display the upcoming appointments page.
  - Q2: What technical solution is feasible for this request? 
  - A2: The CalendarOptionsSlots.jsx component could be modified to display the requested error message, however the CSS required to achieved the desired formatting will be tricky. 
  - Q3: Are there any design recommendations to implement the goal? 
  - A3: A better solution would be to just select the appointment date and time for upcoming appointments when the calendar is displayed. No need for the error message.
  - Q4: What is the logic for the[ current alert as it exists today]
  - A4: This is achieved by make the following changes to the DatetimeSelectPage component.

```
  // Select upcoming appointments
  const bookedAppointments = useSelector(selectUpcomingAppointments);

  // 'selectedDates' contains users previously selected dates. Copy to local variable so changes can
  // be made.
  let mySelectedDates = [...selectedDates];

  // Only pre-populate the calendar when the page is initially displayed
  if (mySelectedDates.length === 0) {
    // Get booked appointments for the current month
    const appointments =
      bookedAppointments[moment(mySelectedDates[0]).format('YYYY-MM')];

    // Loop through booked appointments looking for the 1st appointment that matches an
    // available slot.
    appointments.some(date1 => {
      return availableSlots?.some(date2 => {
        const isFound = moment(date1.start, 'YYYY-MM-DDTHH:mm:ss').isSame(
          moment(date2.start),
        );

        // Add booked appointment to pre-populate calendar
        if (isFound) {
          mySelectedDates = [date2.start];
          data.selectedDates = mySelectedDates;
        }

        return isFound;
      });
    });
  }

  ....

 // Modify all use of 'selectedDates' variable to use 'mySelectedDates' variable
          <CalendarWidget
            maxSelections={1}
            availableSlots={availableSlots}
            value={mySelectedDates}
            id="dateTime"
            timezone={timezone}
            additionalOptions={{
              required: true,
            }}
            disabled={loadingSlots}
            disabledMessage={
              <va-loading-indicator
                data-testid="loadingIndicator"
                set-focus
                message="Finding appointment availability..."
              />
            }
            onChange={(...args) => dispatch(onCalendarChange(...args))}
            onNextMonth={(...args) => dispatch(getAppointmentSlots(...args))}
            onPreviousMonth={(...args) =>
              dispatch(getAppointmentSlots(...args))
            }
            minDate={moment()
              .add(1, 'days')
              .format('YYYY-MM-DD')}
            maxDate={moment()
              .add(395, 'days')
              .format('YYYY-MM-DD')}
            required
            requiredMessage="Please choose your preferred date and time for your appointment"
            startMonth={startMonth}
            showValidation={submitted && !mySelectedDates?.length}
            showWeekends
          />
```

| a | b | c |
| ------ | ----- | ----- |
| ![Image](https://github.com/user-attachments/assets/38941cdb-2d7c-43fc-9eb8-fcc5bd920755) | ![Image](https://github.com/user-attachments/assets/ed690b77-200d-4b69-8ae3-6eb25db3114b) | ![Image](https://github.com/user-attachments/assets/2dffa7fe-c9cc-4fa2-9b50-03c7c4147b17) |

**Comment by Bren22va** [comment]
Can we put notes here to explain why this has been in Validate for 12 days? If it's due to people being out, or blocked for some reason, let's just document that. Thx!

**Comment by outerpress** [comment]
This one didn't hit my radar - @JRRoof this looks good to go from a UX perspective. I linked it in our Design ticket: #92002

**Comment by JunTaoLuo** [comment]
Looks like this spike is completed so I'll close the ticket. Let me know if this needs to be re-opened for any reason though.
