### ISSUE TITLE
[Congressional] V12315380 Due 11/24/24 (Sen. Hirono)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#95030]
## Issue Description
_VA database has the incorrect Branch of Service for the veteran as Army. It should be U.S. Air Force.
https://app.slack.com/client/T03FECE8V/C02BS78NYRM

---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
10/31:  Issue details sent to Jeremy with EVSS team for review.
Acknowledgement of issue was received.  Possible status update by COB today.

**Comment by Kimberley2023-CSM** [comment]
10/31:  Issue details sent to Jeremy with EVSS team for review.
Acknowledgement of issue was received.  Possible status update by COB today.
:heart:
1



Vicki Caruso
  [Nov 15th at 8:51 AM](https://dsva.slack.com/archives/C02BS78NYRM/p1731678705314259?thread_ts=1729017605.918589&cid=C02BS78NYRM)
[@Kimberley Monroe-Daniels](https://dsva.slack.com/team/U05HCLCLZ7V)
 Good Morning, Just a friendly reminder. This is due next week Friday, 11/22 by 4:00 PM EST. Have a great day.


Vicki Caruso
  [Nov 15th at 8:59 AM](https://dsva.slack.com/archives/C02BS78NYRM/p1731679158122289?thread_ts=1729017605.918589&cid=C02BS78NYRM)
11/15: Followed up with Jeremy for an update.


Vicki Caruso
  [Nov 15th at 11:20 AM](https://dsva.slack.com/archives/C02BS78NYRM/p1731687635799979?thread_ts=1729017605.918589&cid=C02BS78NYRM)
Jeremy received conformation from Veteran that the issue has been resolved.
[11:21](https://dsva.slack.com/archives/C02BS78NYRM/p1731687663276559?thread_ts=1729017605.918589&cid=C02BS78NYRM)
Complete: OCTO Response has been submitted in VIEWS
