### ISSUE TITLE
Enable maintenance windows for FMP registration

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95059]
As the iVC forms team, I need to be able to take down form 10-7959f-1 without taking down other forms so that users can still use functioning services during an incident unrelated to what they're trying to accomplish.

### Acceptance criteria
- A member of the IVC forms team in pager duty must be able to open a maintenance window that will take 10-7959f-1 down for maintenance in production without impacting other forms.

**Comment by michaelclement** [comment]
@baltes  New [pagerduty service is here](https://dsva.pagerduty.com/service-directory/P63EKXC). Waiting on the backend updates to be approved/merged before we can start adding maintenance windows to FMP1. Thanks!

**Comment by baltes** [comment]
@michaelclement I see this in PD. Not sure if it matters, but it looks like it's not assigned to our team.

**Comment by michaelclement** [comment]
Ah, thanks for catching that - I've updated it to point to our team:
<img width="1321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2642dd92a1b5840197576ca30e01d36ff56acc58/team.png" alt="team.png" />
