### ISSUE TITLE
VAOS + FHIR - Search Patient Resource (Collection)

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#9505]
Add controller, routes, parameter validations, and mock VCR Cassette for specs for the FHIR Service to support Patient resource.

Additionally:

- ICN query parameter needs to be appended to what front end requests (`?identifier=<ICN>`)
- Any ICNs in the Patient resource data should be filtered out (these appear to be in the `identifier` array on the resource)

**Comment by ajmagdub** [comment]
patient search controller, specs and cassettes written. code merged into master.
