### ISSUE TITLE
Bad mailing address - VEO

### ISSUE THREAD

**Issue by ThaniBoskailo** [department-of-veterans-affairs/va.gov-team#95054]
## Your Details
1. Neshelle Thaxton
​
2.  VEO
    (ex., claims, health, etc.)
​
## Notification Details
1.  Both
    (email, text/SMS, or both)
​
2.  **Please describe your use case.**
  40K Veteran records that may have incorrect addresses, and notification to Veterans is needed to have them review and if necessary update their mailing or physical address
​
3.  **What actions can the user take based on the notification they receive?**
   Update their profile contact information (addresses)
​
4.  **What is the desired business outcome?**
    Fewer pharmacy and miscellaneous mailings because the address is accurate
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    VA Notify
​
6.  **What will trigger the notification?**
    list of potentially impacted population (ICNs) provided to VA Notify
​
7.  **Provide sample content per notification type, if you have it.**
    Leveraging language that was used for addresses around the North Chicago situation (generalized statement) - but we would want a more targeted communication to have the Veteran reviewing their physical and mailing
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
   No
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
  ICN
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    No
​
11.  **What is the anticipated volume of notifications per day, week, month?**
1 time release 
​
12.  **When does this notification need to be in production?**
ASAP as CIO is looking for immediate remediation

**Comment by davidconlon** [comment]
After discussion with @ThaniBoskailo this should be solved by passing the list of impacted Veteran IDs to VAProfile so that VAProfile can then mark those profiles with the 'bad address' flag and utilize the existing bad address trigger/notification that is in-place.
