### ISSUE TITLE
PW intake: Adding language toggles from CAIA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#95052]
## Status
**[2024-10-23] [Fran]** Randi H has given the go-ahead on this ticket in [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1729714113929979?thread_ts=1729030276.642179&cid=C52CL1PKQ). 
**[2024-10-16] [Fran]** This is awaiting QA back from State, but Randi H expects that to happen this week, and I've added the Sprint 15 tag so we can be ready to implement once approval is given.

### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [x] Implementation of Translation widgets
- [ ] Something else

### Describe your request

We published 2 R&S pages related to sign-in and need the Spanish/English toggles added to the page once we've gotten QA back from State. The two pages are:

- https://www.va.gov/resources/creating-an-account-for-vagov-esp/
- https://www.va.gov/resources/verifying-your-identity-on-vagov-esp/

### Time constraints / launch deadlines

As sign-in is a high-priority area we are hoping to get these up ASAP. However, we are still waiting for final QA back from State. We are hoping to get that in the next few days and then we would be ready to go live with the toggles.

### Your product/team Slack channel

Sitewide CAIA

### Your OCTODE product owner

Randi Hecht

### Notify Sitewide Public Websites of this issue, and tag @Fran Cross & @jilladams.

- [x] I acknowledge that I must notify `#sitewide-public-websites` in Slack after submitting this issue.

**Comment by FranECross** [comment]
@chriskim2311 Randi H has given the go-ahead on this ticket (via [Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1729714113929979?thread_ts=1729030276.642179&cid=C52CL1PKQ)). I've removed the Blocked and Awaiting Feedback labels and feel free to release at will!

**Comment by chriskim2311** [comment]
@FranECross Thanks for the update! I'll merge today.

**Comment by FranECross** [comment]
Confirmed language toggles in prod. Messaged Randi H in the existing Slack thread that this is ready for [their ](https://dsva.slack.com/archives/C52CL1PKQ/p1729876489339429?thread_ts=1729030276.642179&cid=C52CL1PKQ)review.

**Comment by FranECross** [comment]
Randi H verified and approved; closing.
