### ISSUE TITLE
Research prep and interviews

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#95063]
## Description
Get ready to run interviews for the study and then conduct them! 

[Research plan link
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/research/adoption-study/Research-plan.md)[Conversation guide link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/research/adoption-study/conversation-guide.md)
[Mural/observation doc link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1730128785856/913b7b53aa89251b8a2fb4b472906fbf61db1e41)
Note-taking template link

### Possible tasks:
- [x] Familiarize self with nat'l portal and location of "try-me" banners
- [x] Double-back on meeting with tool teams to get answers to [questions in mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727282271817/371efea8086edf6d386e9599bcfae6660af3c8b0)
- [x] Complete pilot interview 
- [x] Explore whether we need someone in interviews or on-call with a deep knowledge of national portal and common tech issues (?)
- [x] Create mural or other type of doc for observations
- [x] Create a template for note-taking
- [x] Complete research interviews

## Acceptance criteria
- Interviews are completed
- We're ready to move on to synthesis

**Comment by katbrinkley** [comment]
Added research plan to GH [here](products/health-care/digital-health-modernization/mhv-to-va.gov/research/adoption-study/Research-plan.md)

**Comment by katbrinkley** [comment]
Things I noticed we still need to refine by Friday 10.25:
- N (total participants + pilot)
- Interviewer availability
- Disability rating incl/excl criteria
- Timeline (so far: submitting Friday 10.23)
- Dates/times of pilot and of interviews
- PIlot user(s)
- Session length
- Accessibility specialist present or not for AT users

**Comment by katbrinkley** [comment]
Update: More info from tool team follow up found in the Adoption Study Mural [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727282271817/371efea8086edf6d386e9599bcfae6660af3c8b0?wid=0-1729529179672)

**Comment by jonathanjnelson** [comment]
Moving into synthesis:[ Ticket here ](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/96159)
