### ISSUE TITLE
October evaluation report

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#95066]
## Description
Create evaluation report for entire month of October to share with Robyn

[Report for our team's perusal here (google doc)](https://docs.google.com/presentation/d/1Jr_U8fWNrjwvRb8GhRZI7UWxPyzs1ucujJ0X_muQ63s/edit#slide=id.p)

## Possible tasks:
- Pull data from GA4 and create evaluation report
- Thinking through the flow of the report and the story we're telling (this is likely to require edits on last month's report)
- Likely to include new stats, especially comparison of Aug, Sept, Oct numbers

## Acceptance criteria
- Present report to Robyn / get feedback
- Add report to folder in Sharepoint

**Comment by wesrowe** [comment]
Robyn had some thoughts on timing: present to Wed Weekly ux mtg on 11/20

**Comment by fmccaf1** [comment]
Include sanke diagram?

**Comment by fmccaf1** [comment]
[I added slides from report to Robyn's document on sharepoint ](https://dvagov-my.sharepoint.com/:p:/g/personal/robyn_singleton_va_gov/EU1AHcgL4BtEl9gn20WkorIBSs5IrDq44SMZmyh9alhZlA?email=KATHRYN.MCCAFFERTY%40va.gov&e=WwpRWP)

Still would like to find some ways to make some of these slides more visual
