### ISSUE TITLE
Medallia: Biweekly analysis + tagging

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#95065]
**User story**
As a Cartography team member, I want to review Medallia responses on a biweekly basis to identify patterns in user feedback

[Link to October Medallia sheet (shared by Anne)
](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedo[…]edallia%20feedback.xlsx&action=default&mobileredirect=true)

[Link to original Medallia shared sheet (Robyn's spreadsheet)
](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B8C161AC9-BB42-401D-9B5D-913941F1ECA9%7D&file=MHV)

**Notes**
- Transitioning from daily pulls to biweekly pulls since post-launch monitoring is concluded
- Sarifa sends 2 weeks of data at a time: this is the data used for this ticket (no need to pull in additional reports from Sarifa)

**Possible tasks:**
- Review medallia feedback pull from Sarifa
- Doublecheck that there is not older data that didn't yet make it into the spreadsheet (for example, if we didn't do this work the sprint before, it might need to be done for two different sets of data from Sarifa)
- Add to master Medallia shared sheet in Sharepoint
- Add tags to **each response** in Robyn's spreadsheet
- Identify any patterns/significant user experiences that we could work on if high priority

**Acceptance criteria**
- Transfer Medallia data pull from Sarifa to the shared spreadsheet
- Add tags to all data on a biweekly basis

**Comment by fmccaf1** [comment]
@katbrinkley could you add a link to the shared spreadsheet in the ticket?

**Comment by fmccaf1** [comment]
Just filled in data and tagging for the first two weeks of October. Sarifa should be sending the following two weeks this sprint.

**Comment by katbrinkley** [comment]
Just added in the Medallia data for pull 2/2 for October. Still needs analysis and tagging, will finish that up Monday.
