### ISSUE TITLE
Finalize and submit research plan / convo guide

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#95060]
### Notes

Possible tasks:
- Finalize recruiting needs and interview availability
- Submit convo guide and research plan to Shane Strassberg
- Schedule a kickoff meeting with Perigean
- Add research ticket to the research repo
- Schedule and conduct pilot interview
- Move research plan and conversation guide to relevant Github folder

## Acceptance criteria
- Research docs reviewed and received "OK" from Robyn
- Research docs submitted for Shane's review
- Pilot interview scheduled

**Comment by katbrinkley** [comment]
Added research plan to GH [here](products/health-care/digital-health-modernization/mhv-to-va.gov/research/adoption-study/Research-plan.md)

note:
- Added location (Remote, Zoom)
- Removed emails for Team Roles (per GH guideline, left in doc for visibility for now)

**Comment by katbrinkley** [comment]
Things I noticed we still need to refine by Friday 10.25:
- N (total participants + pilot)
- Interviewer availability
- Disability rating incl/excl criteria
- Timeline (so far: submitting Friday 10.23)
- Dates/times of pilot and of interviews
- PIlot user(s)
- Session length
- Accessibility specialist present or not for AT users
