### ISSUE TITLE
Error page for EPS submission call failed

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#95073]
## Tasks 

- [ ] Create wireframe for error when call to EPS submission endpoint fails. E.g., user selects "confirm" and EPS is unreachable. Check with Peter or Ciera about what's in VAOS direct scheduling today from a content perspective. I left a comment for Peter here since it's missing from documentation - https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy?node-id=1-3489#988985125. 
- [ ] After Christina and Ciera review, move up to MVP scope page and Specs pages in CC Figma file.

**Comment by benbrasso-agile6** [comment]
@zach-park screenshot here. Just need to recreate in Figma. 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726688922423/1707b7c34332fa682664d69ee7e9e4489a05f7f0?wid=0-1729114617155

**Comment by benbrasso-agile6** [comment]
@zach-park I would work on this sooner than later so engineers can get started

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , [this wireframe](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5455-9811&t=wP9Sgrz336FKGsTy-1) is ready for review:
https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5455-9811&t=wP9Sgrz336FKGsTy-1

**Comment by benbrasso-agile6** [comment]
@zach-park could you apply the alert to our review page template we have here - https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4?node-id=2490:44318&locale=en&type=design

**Comment by zach-park** [comment]
> [@zach-park](https://github.com/zach-park) could you apply the alert to our review page template we have here - https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4?node-id=2490:44318&locale=en&type=design

It is updated. Thank you!

**Comment by benbrasso-agile6** [comment]
Feedback provided in Figma

**Comment by benbrasso-agile6** [comment]
LGTM; waiting for ciera and christina to review

**Comment by cgednalske** [comment]
Looks good to me, but it's probably most important that @Cieramaddox gives the thumbs up. And is [this link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5455-9811&node-type=section&t=5tIRbdJdNEHx6du8-0) the correct one to look at @zach-park?

**Comment by zach-park** [comment]
> Looks good to me, but it's probably most important that [@Cieramaddox](https://github.com/Cieramaddox) gives the thumbs up. And is [this link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5455-9811&node-type=section&t=5tIRbdJdNEHx6du8-0) the correct one to look at [@zach-park](https://github.com/zach-park)?

Yes, that is the right link. :)

**Comment by benbrasso-agile6** [comment]
Moved up in to MVP page in Figma
