### ISSUE TITLE
Flipper UI access for [Premal Shah]

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/va.gov-team#95076]
### Your Name

Premal Shah

### Your GitHub handle (Flipper UI access is managed through GitHub)

@pshahva

### Team, Role, and Company of the target individual

OCTO PO

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [ ] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I'm the PO and need to be able to control staged releases for my apps.

**Comment by bmatos312** [comment]
Hello Premal, I've sent you an invite to lesser and prod environments that will last for 6 months. We will ping you again then to ensure you still need access. But you should be good otherwise.
