### ISSUE TITLE
CT: on screen widths 641-767px, the institution details are not horizontally aligned

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9507]
For all profile pages, the institution detail summary (locale, website, type, etc...) falls out of horizontal alignment for screens with a width between 641 and 767 pixels. These details should be in-line for screen sizes above 640px. 

![Screen Shot 2020-05-26 at 2.38.08 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5d62e615-620d-4192-b7e4-84ef614e7e39)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12853

**Comment by sonntag-adam** [comment]
![ezgif.com-video-to-gif.gif](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/296153dd-eb39-4868-bfde-40f8dd3599d4)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam, @JenLJ  and I took a look, and the defect is fixed!

**Comment by sonntag-adam** [comment]
Closing bug.
