### ISSUE TITLE
Atlas Offboarding Audit

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95080]

**Comment by alyssagallion** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95112

**Comment by davidpetras** [comment]
Users have been audited and deactivated within Atlas, teams from the related ticket have been consolidated.

Results of the user audit can be found here: [LINK](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3581935628/Q4+2024+ACCESS+REVIEW+-+Atlas)

Complete
