### ISSUE TITLE
Warn VA Profile team about Preferred Name

### ISSUE THREAD

**Issue by nichia** [department-of-veterans-affairs/va.gov-team#95090]
### User story

As a Cartography team member, I want to keep the VA Profile team updated on our launch date with the Preferred Name and expected API traffic increase so that we don't have any unexpected internal issue.

### Notes
- 

Possible tasks:
- [ ] Provide a traffic estimate of unique users
  - Average sessions on www.va.gov: 700k per day
  - Max daily sessions: 980k
  - Max hourly sessions: 90k

## Acceptance criteria

- Informed VA Profile team of expected increase in traffic

**Comment by wesrowe** [comment]
@dcloud, I just added traffic baselines to the ticket body. Hopefully that means we're ready to let VA Profile know about it.

**Comment by dcloud** [comment]
Notified Mike Richard, passed along the 700k sessions average, in [this Slack thread](https://dsva.slack.com/archives/C7TE0PFTL/p1731601570604089), mentioning @wesrowe

**Comment by wesrowe** [comment]
I ended up in a quick chat with Mike Richard. He's going to mention this at scrum-of-scrums tomorrow morning (11/15). Should be good to go for roll-out next week, he'll let us know if any concerns.
