### ISSUE TITLE
Analytics Implementation for Disability How to Apply Wizard

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#9510]
# Google Analytics Implementation

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description

- Who is this request for?

    - John Hashimoto
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#vsa-public-websites`._
    
- What team/project is this work for?
    _Public Websites_
    
- Provide the Domain where Google Analytics needs to be implemented
    _www.staging.va.gov/disability/how-to-file-claim_
    
### Interactions to Track
- [ ] Expands and collapses of Let's get started button
- [ ] Click on "File a disability compensation claim" at end radio button clicks
- [ ] Ineligibility alert box displayed
- [ ] Clicks on links contained within ineligibility alert boxes

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Wizard standardization spec: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md

**Comment by jonwehausen** [comment]
@Mottie is implementing the specification here for how to wizard tracking

**Comment by Mottie** [comment]
I've just merged in the analytics updates for Form 526's wizard

**Comment by jonwehausen** [comment]
@ianMcCullough-ob I have handed this ticket off to you for QA of the data layer and tagging. 

There is no workspace for this because the GTM tagging is already in place - so you can use the default workspace when testing. 

Please refer to this [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md) for the event taxonomy -- each of these items should be tested + documented.

**Comment by jonwehausen** [comment]
Hi @ianMcCullough-ob , 

Could you provide an update on the status of this QA? Thanks in advance here

**Comment by ianMcCullough-ob** [comment]
Hey @jonwehausen sorry for the delay, here's my testing below. Unsure where or how to test the video tracking aspect.

Description/Screenshot of Interaction | DataLayer Screenshot | Dev Notes
------------ | ------------- | -------------
User chose to start over the wizard<br />![Screen Shot 2021-02-16 at 1 46 11 PM](https://user-images.githubusercontent.com/73119703/108107900-dbfd1d80-705d-11eb-9244-41c81a8b51a9.png) | ![Screen Shot 2021-02-16 at 1 45 48 PM](https://user-images.githubusercontent.com/73119703/108107941-e8817600-705d-11eb-80e6-393a5c8b38d5.png) | Pass 
Form field changes (clicks on radio button answers)<br />![Screen Shot 2021-02-16 at 1 58 27 PM](https://user-images.githubusercontent.com/73119703/108108778-10bda480-705f-11eb-8009-179603547ef2.png) | ![Screen Shot 2021-02-16 at 1 42 59 PM](https://user-images.githubusercontent.com/73119703/108108452-a3117880-705e-11eb-8e2a-e03114262cce.png) | Pass 
Received alert notice following a question answer <br>![Screen Shot 2021-02-16 at 1 43 40 PM](https://user-images.githubusercontent.com/73119703/108108451-a278e200-705e-11eb-9d25-2f55611c3346.png) | ![Screen Shot 2021-02-16 at 1 59 12 PM](https://user-images.githubusercontent.com/73119703/108108851-2a5eec00-705f-11eb-8c89-d3231c16069c.png) | Pass 
Click on link within blue box notice <br>![Screen Shot 2021-02-16 at 1 47 31 PM](https://user-images.githubusercontent.com/73119703/108108446-a1e04b80-705e-11eb-84c8-5bfff98fe045.png) | ![Screen Shot 2021-02-16 at 1 47 39 PM](https://user-images.githubusercontent.com/73119703/108108444-a1e04b80-705e-11eb-8d7d-c483e3b52a47.png) | Pass 
How to wizard primary CTA is surfaced / visible<br />![Screen Shot 2021-02-16 at 1 48 00 PM](https://user-images.githubusercontent.com/73119703/108108442-a147b500-705e-11eb-8ace-e2ff31b9d5e9.png) | ![Screen Shot 2021-02-16 at 1 45 15 PM](https://user-images.githubusercontent.com/73119703/108108449-a278e200-705e-11eb-8b66-7369b2ce644c.png) | Pass 
User clicks button to apply now <br />![Screen Shot 2021-02-16 at 1 48 00 PM](https://user-images.githubusercontent.com/73119703/108108442-a147b500-705e-11eb-8ace-e2ff31b9d5e9.png) | ![Screen Shot 2021-02-16 at 1 48 06 PM](https://user-images.githubusercontent.com/73119703/108108440-a147b500-705e-11eb-83ef-12254bc51395.png) | Pass 
User clicks link to skip how to wizard <br>![Screen Shot 2021-02-16 at 1 46 40 PM](https://user-images.githubusercontent.com/73119703/108108448-a278e200-705e-11eb-99b3-c4a77a9bba7d.png) | ![Screen Shot 2021-02-16 at 1 46 46 PM](https://user-images.githubusercontent.com/73119703/108108447-a1e04b80-705e-11eb-9dd0-31b69c266b8a.png) | Pass 
Video Tracking with a **progress bar** |  |

**Comment by jonwehausen** [comment]
Thanks @ianMcCullough-ob ! 

This looks good to go 👍
