### ISSUE TITLE
Business intake form for Benefits Management Tools Team 1

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#95101]
## Your Details
1.  Jacob Worrell
​
2.  **Business Line**
Claims
​
## Notification Details
1.  **Notification type**
Email
​
2.  **Please describe your use case.**
We want to notify people when their evidence submissions fail to make it to VA claims processors due to system errors. 
​
3.  **What actions can the user take based on the notification they receive?**
They can attempt to re-submit their evidence through direct mail. 
​
4.  **What is the desired business outcome?**
  Veterans never mistakenly believe a submitted piece of evidence is being used to decide their claim when it did not successfully get to claim processors. 
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
  We have created an exhaustion handler that will tell VA Notify to send an email when the final Sikekiq job attempt fails to submit the evidence.
​
6.  **What will trigger the notification?**
 Final Sikekiq job failure. 
​
7.  **Provide sample content per notification type, if you have it.**
our template can be viewed in staging here: https://staging.notifications.va.gov/services/efd5806d-64d8-4453-acc9-8f842b2c5d65/templates/416ac1c7-a76e-46fa-8a79-e18ce11c82de
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
I do not believe a privacy officer has approved the content and I don't know who my privacy officer is. 
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
 We are using ICN
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
  We do not.
​
11.  **What is the anticipated volume of notifications per day, week, month?**

300-500 emails/month
​
12.  **When does this notification need to be in production?**

ASAP. This is a high priority OCTO-wide initiative.

**Comment by davidconlon** [comment]
@nathanbwright Can this team be using the Vets-API module?

**Comment by nathanbwright** [comment]
@davidconlon - sorry that I completely missed this. Yes, if they are using vets-api they should be able to use our module. Reach out in slack (ideally) @jerekshoe if you have any questions.
