### ISSUE TITLE
SC | Fix review page missing primary phone error

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#95117]
## What happened?

On the Supplemental Claim review & submit page, if a primary phone number chose is missing, an error message is displayed, but it doesn't conform to how we have been showing error messages

**Add the steps to reproduce the bug**:

1. Start a Supplemental Claim in staging
2. From the first page, use the save-in-progress menu to jump to the review & submit page
3. Open the "Veteran information" accordion
4. Note the primary phone error message

**Add a screen recording or photo**:

Current method of showing missing form values (contact info example)

<img width="500" src="https://github.com/user-attachments/assets/d9a341e6-614f-48f3-92b9-9e3997b425d8" alt="missing all contact info with the left column showing the label name and the right showing red text with a missing value message, e.g. 'Missing phone number' error" />

Current missing primary phone error (note that this question only appears if the Veteran has both a home & mobile phone)

<img width="500" src="https://github.com/user-attachments/assets/48c6598b-85c1-46ce-a7b6-649102edee9f" alt="primary phone page with no columns and the error message 'you must choose a primary phone number' message aligned to the left side with a red border" />

## How severe is the problem?

- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [x] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

This is a minor issue because you would need to somehow get past the required question within the form flow to get to the review & submit page.

## What is the desired behavior?

Follow the same format as the other error messages

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by Mottie** [comment]
Ready for validation in staging.

**Comment by davidakennedy** [comment]
![Review and submit page showing the "Missing primary phone" in red.](https://github.com/user-attachments/assets/f08f30c2-f414-4ee4-b14c-0208946d713a)

This is completed, and the error aligns with the other ones now.
