### ISSUE TITLE
Infra Overhaul: Spike: Gravitational teleport

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#9511]
## Goal
Spend a sprint looking at gravitational teleport to see if it will handle our access needs:
- ssh socks proxy
- jumpbox/bastion host

## Why
This product supports all of our service needs (proxy, bastion), as well as offers github auth and ssh ca management to eliminate having to manage ssh keys for users

## What
- Setup Teleport in vsp-infra-local
  - minimal automation, just enough to see if it works and repeat the setup
  - manual steps are ok
- Things we want to evaluate
  - web shell
  - ssh ca from teleport server -> teleport client (no manual key management needed for user)
  - socks works
  - Windows, Linux, Mac compatibility 
  - Understand how teleport user to os user mapping works
  - Github Auth and Team -> User mapping
  - Test `nomad alloc exec` workflow
  - How can we install stuff into the environment that users use (eg, users need nomad and vault cli tools)
  - Understand how to add / remove nodes from server
  - Understand how to config the service
  - Understand how to backup / restore the service (or replace)
  - Understand how to integrate with Review Instances
  - Generally, is the experience using and maintaining the service good?

**Comment by jbritt1** [comment]
- [x] Setup Teleport in vsp-infra-local 
- [x] minimal automation, just enough to see if it works and repeat the setup
- [x] manual steps are ok
- [WIP] web shell
- [WIP] ssh ca from teleport server -> teleport client (no manual key management needed for user)
- [WIP] socks works
- [WIP] Windows, Linux, Mac compatibility
- [WIP] Understand how teleport user to os user mapping works
- [WIP] Github Auth and Team -> User mapping
~Test nomad alloc exec workflow~
- [WIP] How can we install stuff into the environment that users use (eg, users need nomad and vault cli tools)
- [WIP] Understand how to add / remove nodes from server
- [WIP] Understand how to config the service
- [WIP] Understand how to backup / restore the service (or replace)
- [WIP] Understand how to integrate with Review Instances
Generally, is the experience using and maintaining the service good?
 - _Will include a brief description here_

**Comment by jbritt1** [comment]
Teleport was evaluated and demo'd to the team. Taking a pause this sprint due to pressing ATO obligations, but for the scope of this ticket this is likely good to close until we can pick back up on this work.
