### ISSUE TITLE
UX Discovery/Design: State of sign-in widgets on unauthed tool pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#95136]
## Description

This ticket is related to an OCTO sync that took place with Danielle Thierry, Laura Willwerth, Robyn Singleton, Sara Sterkenburg, Wes Rowe, and several members of the identity team during the week of 11/5/2024. 

We need to update sign-in, ID-verification, and Cerner-OH routing alerts on all /health-care benefit hub pages representing the "big four" tools prior to EOY. The goal is to update recently launched global sign-in & ID-verification alerts ([see VADS here](https://design.va.gov/components/alert/alert-sign-in/)) in high-touch unauth pages on VA.gov that will be impacted by two major transitions: 1.) sunsetting the MHV sign-in credential and 2.) transition of My HealtheVet on VA.gov - as all tools will be fully in Phase 1, and appointments will soon be be sunset on Classic. 

### User story

As a Cartography team member, I want to document the current state of sign-in widgets including verification alerts for the benefit hub pages for SM, Meds, Records, and Appts, so that we can scope the work to bring all of them up to the same best standard.  

~~As a Cartography team member, I want to improve upon the current Cerner/OH routing alerts and create a template that can be used to route users to that health portal from any of the "big 4" tool pages in the /health-care benefit hub.~~(changed direction & have decided not to put these alerts on `/health-care` benefit hub pages)

### Notes
- Delivery goal of this work (including implementation) is mid-December. 
- [Mural of widgets (as of early 2023)](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1651166973924/bc8bc44cab4e4ae7b84819d22ba89b11aa70e5e1?sender=uebde62ceb342c6477fb09406) – Note that the Appointments widget has been updated to a better and more accessible UX; we will follow that pattern for the other 3.
- URLs:
  - [Appts](https://staging.va.gov/health-care/schedule-view-va-appointments)
  - [Medications](https://staging.va.gov/health-care/refill-track-prescriptions)
  - [Messages](https://staging.va.gov/health-care/secure-messaging/)
  - Records
    - [View lab & test results](https://staging.va.gov/health-care/view-test-and-lab-results) 
    - [Get medical records](https://staging.va.gov/health-care/get-medical-records/)

Possible tasks:
- [x] Determine how to handle Cerner/OH routing alerts, including looking at governance team feedback on this alert design from previous collab cycle touchpoints (ask Appointments team for links) 
- [x] Connect w/ Appointments team to grab their updated routing alerts & iterate from their mocks 
- [x] Template out an alert for the Cerner/OH routing alert (based on appointments version)
- [x] Develop a plan with CAIA for which pages need to have which alerts ~and determine URLs that should be revealed on each of the tool pages for users who sign-in with ID-verified credentials.~ (Realizing we don't need to deal with the URL part until Phase 2 of benefit hub updates in Feb-March 2025 when we flip the URLs on those pages to point to the new builds on VA.gov)

## Acceptance criteria
- [x] [Plan is documented in GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/transition/benefit-hub-page-updates.md)
- [x] An updated OH routing alert template for benefit hub pages are[ mocked up in Figma](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=263-24267&node-type=canvas&t=6GWonl0uzAh40ZVQ-0) w/ annotations (takes into account governance team feedback given to the appointments team for these alerts) 
- [x] [Follow-on ticket for implementation on appointments page first](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96469) is updated
- [x] Follow-on ticket for implementation on the other 3 tools is created (to be done after appointments first)

**Comment by wesrowe** [comment]
Robyn pinged during office hours 11/4, would like to meet with Danielle the week of 11/17 (after OCTO off-site).

**Comment by wesrowe** [comment]
I asked in slack whether UXers would be okay with making this ticket a UX design ticket instead of discovery, since the pattrn is obvious (per CAIA in a meeting this morning).

**Comment by sterkenburgsara** [comment]
Pattern is obvious for initial sign-in & id-verification alerts for benefit hub pages (and ID-verification for health tool pages). Not as obvious for Cerner/OH routing alerts. Proposed a suggestion for that approach [in this Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1731009382313229)& will mock this up in Figma for socialization with affected teams & stakeholders this sprint.

**Comment by sterkenburgsara** [comment]
**Update**: synced w/ @wesrowe about this & decided it's not necessary to mock-up benefit hub pages w/o these routing alerts. Instead, will tag Danielle on the thread (linked above in previous comment) w/ appts team where this idea was hashed out a little bit already. We'll see what she thinks about it.

**Comment by laurwill** [comment]
Hi @wesrowe and @sterkenburgsara , I noticed the question marks on the link for medical records at the top of this ticket, and realized that there are currently 2 different health tool landing pages for medical records:
- [View lab and test results](https://staging.va.gov/health-care/view-test-and-lab-results/)
- [Get medical records](https://staging.va.gov/health-care/get-medical-records/)

The ultimate plan is to retire the "view lab and test results" page and combine into a single "Get your medical records" page, but I'm not sure how this fits in to the widget changes timeline. Let me know if you want to chat about this!

**Comment by sterkenburgsara** [comment]
I think we should put widgets on both pages, but we won't know whether users who are ID-verified on the benefit hub pages & are given access to these links will actually have access to Medical Records. It's possible that they don't have a facility in their profile & need to see the "no access" alert. So, I need to better understand how OCTO would like to route users generally for a few scenarios before I can fully answer this / validate an approach.

**Comment by sterkenburgsara** [comment]
I'd probably suggest revealing links to the most relevant My HealtheVet page on each of these unauth pages until we're able to consolidate them; and let the apps handle redirects or route guards on their end as needed?
* **View your VA lab and test results** --> send users here: va.gov/my-health/medical-records/labs-and-tests
* **Get your VA medical records online** --> send users here: va.gov/my-health/medical-records/

What do you think about that?

**Comment by sterkenburgsara** [comment]
**Update**: drastically updating this ticket based on a simplified direction to remove OH/Cerner routing alerts from the health-care benefit hub pages for the "big four" tools. [See Slack thread here](https://dsva.slack.com/archives/C03CGTDLTFF/p1731009382313229). Slack approval from Danielle & Laura W. in that Slack conversation.

Cerner/OH alerts, as well as some other "portal-wide" alerts now need to be governed / standardized across the health tool teams, and that work will be picked up in[ this related ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/97034) soon.

**Comment by sterkenburgsara** [comment]
**Another update**: @wesrowe pointed out something important[ in a comment on this ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/96469): URLs on 3 our of 4 benefit hub pages for the tools are **not being updated** until Feb/March '25. Thus, removing the OH/Cerner routing would force users on a path to the National Portal before they'd see any routing to the My VA Health portal, which isn't great for those users. We should put the removal of OH/Cerner alerts behind feature flags until the links can be updated on those 3 tool pages, and make sure these alerts stay in place until then.

**Comment by sterkenburgsara** [comment]
@wesrowe only outstanding item on this ticket is templating the OH/Cerner routing alert for the benefit hub pages. I can do that today, but Kaitlin indicated in office hours yesterday that it probably isn't worth fixing the ones on benefit hub pages since they're in place now & work as expected. Knowing that we plan to remove them in Phase 2 (your epic), teams may push back against  the only slight UX value that will come from modifying these alerts. I think the "meat" of the work here is just getting the new VADS sign-in and ID-verification alerts in place on those tool pages.

**Comment by sterkenburgsara** [comment]
![Image](https://github.com/user-attachments/assets/5bc08e2e-9556-4daf-a6c1-d6a5e8732491)

[Figma here](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=263-24267&node-type=canvas&t=6GWonl0uzAh40ZVQ-0). 

// closing ticket.
