### ISSUE TITLE
10-7959f-2 Confirmation page: None of the page-specific content matches the design.

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95130]
Update confirmation page content to be consistent with designs.

**Comment by jamiefiore** [comment]
Here's the Figma File for the [confirmation page](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=5097-35469&t=HyfS1DjwRz2kfrWt-4)

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32735). Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes this is ready for you to take a look at. To review, please see the screenshots attached to the [GitHub PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32735)

**Comment by baltes** [comment]
@jamiefiore This looked good to me based on screenshots above, do you want to review?

**Comment by jamiefiore** [comment]
@baltes the screen shots in Github look good.
