### ISSUE TITLE
10-7959f-2 All pages: Content has additional left/right padding; should match width of help footer

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95131]

**Comment by jamiefiore** [comment]
@baltes  Here's the [figma file](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=4338-134275&node-type=canvas&t=HyfS1DjwRz2kfrWt-0)

**Comment by reiting** [comment]
@baltes @jamiefiore this is in staging and can be reviewed.

**Comment by jamiefiore** [comment]
@reiting @baltes  Looks good! Thank you!.
