### ISSUE TITLE
[Spike] Provider selection page in the OH schedule workflow

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#95150]
## Request
We are looking for assistance from the team to do an analysis on how we can implement the Provider selection page for the schedule workflow to the Oracle Health system. We are looking for a solution that provides value to the Veteran's experience and can be done as part of the OH MVP. 

### Goal
The goal is to provide the user the ability to select a Provider of choice

### Requirements to Consider
[Design user workflow](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=5475-49205&node-type=instance&t=0pn0SYFiNL10YbtB-0)

---

## Tasks
- Answer the following questions:
  - Q1: Determine when in the user flow when we will perform the check for `relationshipage`, `eligibility check`? 
  - Q2: Based on the design spec, does the team recommend the approach? Are there any suggestion that we can implement that meets the goal? 
  - Q3: We currently have checks in our tool that still remains applicable for Oracle Health. Please review the dead end alerts in the FIgma file and let us know if the design can easily be implemented without complex logic on the frontend or vets-api. 

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/95150?planning-poker) with Zenhub @ryanshaw @simiadebowale

**Comment by simiadebowale** [comment]
Q1: Determine when in the user flow when we will perform the check for relationshipage, eligibility check?
A:We will perform this check with the current facility configurations check.

Q2: Based on the design spec, does the team recommend the approach? Are there any suggestion that we can implement that meets the goal?
A: Suggestion steps in order:
- Show list of recently visited facilities.
- Make relationshipAge and requireVisitWithinDays checks with facility configurations api
- Make call to patient-relationships endpoint to get list of providers
- Display list of providers patient has previously seen
- Check provider slots when provider is selected
- Drop to request flow if no slots are available
Q3: We currently have checks in our tool that still remains applicable for Oracle Health. Please review the dead end alerts in the FIgma file and let us know if the design can easily be implemented without complex logic on the frontend or vets-api.
A: Alerts can be easily implemented.

**Comment by simiadebowale** [comment]
@melissa-lefevre - this is ready for validation

**Comment by melissa-lefevre** [comment]
@simiadebowale It looks good except for this step: "Check provider slots when provider is selected" I thought Brad said we could make a check for a single time slot (to reduce the load of calling all time slots) and then once they click on the provider, we will look for all time slots. The first check is more of a does the provider have time slots at all to direct schedule yes / no.

**Comment by Bren22va** [comment]
Please document with notes here why this has been in Validate for 2 weeks+. If it's due to people being out, blockers, etc, that's fine, just document that here. Thx!

**Comment by simiadebowale** [comment]
I missed the comment above from @melissa-lefevre 
@melissa-lefevre - That's correct, the first check will just check if the provider has time slots at all to direct schedule.

**Comment by outerpress** [comment]
Looking at @melissa-lefevre 's designs I think this is captured, so I'm closing. Feel free to reopen if I'm missing anything.
