### ISSUE TITLE
Access for Mark Dewey

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#9516]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Mark Dewey
- Please Provide your email.
   > mdewey@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA; Role: Senior Front-End Engineer; Employer: GovernmentCIO
- SSH key (public)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZQm3sclSHr5VxZmE3u105tn+QR+XdxZH7/mwGDvgrNN5xRmK+HmsepIR+SfMxZV9bGTvxd9Rk+klLFarHc/xb+yHNoMWJnCxfcdXi+NCXcEBoo/6EGEsR+xSmkbEvOCndwGaCUxvZHg8dHMXicS/Rg2da/Yha2wqqIAPC9/0qAw6p9AiU/yVBXQZDbIFCkKDR/vSWeWRlrxl9x3P9g0CWFHYqLauYzgpZvfPbgxUXRMA8EcW/SjXSFmHGs348XK8kTejTFjeL914A97TCM/JkQzW1iFngPDRdNzoGXsU9jDANCniwb3yp+rb9+9sURCYuzY/GwIufqcnHNl8dNpOEIpi+hcwiPqMJ9TFTxsE3sF2Rreh12WdupJnEKULoewYIItaDqucZDKC1Xj4hR7JrjTDXIHZVujTBb91Lxl0vdiKovkMz2qOGdqY70L1iltritiLZFn6Xg6VdVmoWbuZRv7GGZgQ4g3mI7kET4+yU6Y1BuWud45TI43vwA1GgRL8= markdewey@Mark-Dewey-MacBook-Pro.local
```

- [Grant AWS Console access?]
YES
>General: software development, troubleshooting, and understanding of systems, potential pipeline and delivery improvement. Specific: shell access to development and staging systems for troubleshooting, log analysis, testing, and walk-through with developers.

**Comment by mdewey** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mdewey** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mdewey** [comment]
I am not able to add a label for my team, but it would be `VSA`

**Comment by jsev-io** [comment]
Tagging @Jeff-Hayter for AWS Access Approval

**Comment by jsev-io** [comment]
@mdewey This ticket has been open for a bit, can you confirm you still need AWS access?

**Comment by jsev-io** [comment]
Closing for now. If further assistance is needed please reopen, and reach out. 
Thanks!
