### ISSUE TITLE
Staging Review finding: Change the text and fix sizing on Save button

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95170]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Benefits Decision Review
**Product:** Higher Level Review

**Feature:** 

## Findings details
**VA.gov Experience Standard - issue:** [User encounters design components or patterns that are inconsistent or confusing.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

When a user [clicks edit on their contact information](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#editing-relevant-information-to-the-current-application), they see a save and cancel button. The button text should be “Update” instead of “Save”. The sizing of the button is also off.

<details><summary>Link, screenshot or steps to recreate</summary>

![Screen shot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/90188-Allison-2.png?raw=true)

</details>

## Recommended action

Change the button text to “Update” and check the button size. Be sure you are using the Storybook component.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Button ](https://design.va.gov/components/button)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by Mottie** [comment]
This "Save" button is unique in that it's still a React component. When clicked, it will become disabled and show a loading icon.

Once the Design System Team [adds a web component button that includes an icon and can be disabled ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2792)

**Comment by Mottie** [comment]
Work has been merged and is ready for validation in staging

**Comment by davidakennedy** [comment]
This change is complete.

![Phone number screen with text field showing update button](https://github.com/user-attachments/assets/824bab51-c472-49a3-9620-1a7b70054572)
