### ISSUE TITLE
Staging Review finding: Address required after selecting "yes" to homelessness question

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95175]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Benefits Decision Review
**Product:** Higher Level Review

**Feature:** 

## Findings details
**VA.gov Experience Standard - issue:** [User can't complete a necessary flow or hits a dead end.](https://design.va.gov/about/experience-standards/#user-can-complete-necessary-flows)
**VA.gov Experience Standard - category:** [Usability](https://design.va.gov/about/experience-standards/#category-usability)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The new question on this form asks, "Are you experiencing or at risk of homelessness?" then on the subsequent page asks the user to verify their mailing address, which is required to proceed through the form. If someone is homeless and does not have a mailing address, how will they proceed through the form?

<details><summary>Link, screenshot or steps to recreate</summary>

![screenshot of homelessness question](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/90188_erin_homelessness.png?raw=true)

</details>

## Recommended action

I understand this is complex. Some potential options include adding a note on the "edit address" page that indicates folks can use other addresses (family members, VSOs) or allowing users to proceed through the form without entering a mailing address. Other options exist on the guidance for [asking for housing status](https://design.va.gov/patterns/ask-users-for/housing-status) in the design system.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** User flow

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by Mottie** [comment]
I tested this locally, and it appears to be working as expected? I'd like to test this in staging, but I don't know of any users that don't have a mailing address.

![choosing "yes" for homelessness, then proceeding past the contact info page that doesn't have a mailing address. Then navigating back and choosing "no" for homelessness, then while trying to proceed past the contact info page, we see an error alert stating "Add a mailing address to your profile"](https://github.com/user-attachments/assets/d7aee118-6754-4d34-aea0-d4334f8b7695)

**Comment by comaurice** [comment]
Follow up on thread with Erin to confirm we can close

**Comment by shiragoodman** [comment]
@comaurice you don't need our approval (or Erin's) to close the ticket. We operate on an honor system, so if you believe the issue is resolved, you're free to close. However, if you'd like @erinrwhite's help in validating it, they can take a look.

**Comment by erinrwhite** [comment]
I think this is all set to go based on our [Slack discussion](https://dsva.slack.com/archives/C5AGLBNRK/p1729624204103739) but let me know if y'all have other questions/things you want to talk through here.

**Comment by comaurice** [comment]
Gtk! Thanks Shira and Erin
