### ISSUE TITLE
Staging Review finding: Remove persistent “Sorry we could not find any eligible issues” alert 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95174]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Benefits Decision Review
**Product:** Higher Level Review

**Feature:** 

## Findings details
**VA.gov Experience Standard - issue:** [User encounters design components or patterns that are inconsistent or confusing.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design), @erinrwhite (IA)

### Description

When a user gets to step 2/4 and sees the list of issues they are requesting to be reviewed, they have a “go back and add it link. If they click that link, they are still seeing the alert “Sorry we could not find any eligible issues” even though they have added one.

<details><summary>Link, screenshot or steps to recreate</summary>

![Screen shot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/90188-Allison-5.png?raw=true)

</details>

## Recommended action

That alert should only appear if there are no issues. Once a user has added one that alert should no longer appear.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by Mottie** [comment]
This is ready for review in staging

**Comment by davidakennedy** [comment]
![Contestable issues page without the no issues error after adding a fresh one.](https://github.com/user-attachments/assets/71f63ca4-2b46-4254-8aff-b02735a2936d)

I added a fresh issue on an account that had none, and the error message wasn't present after adding it. This should be good to close.

**Comment by kayline** [comment]
@comaurice Ready to close, validated by DK

**Comment by comaurice** [comment]
Reviewed DK's validation, thanks. Good to close @kayline
