### ISSUE TITLE
Staging Review finding: Link text issue in "why isn't my issue listed here?" dropdown in step 2 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95182]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Benefits Decision Review
**Product:** Higher Level Review

**Feature:** 

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that doesn't match other content on VA.gov.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-is-similar-to-other-content-on-vagov)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

The link text "Get VA Form 20-0996 to download (opens in a new tab)" doesn't match other link texts on VA.gov

![Image](https://github.com/user-attachments/assets/0a3e94b6-1111-4ae2-9362-284127037ad3)

## Recommended action

Change the link text to "Download VA Form 20-0996" 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Government forms](https://design.va.gov/content-style-guide/government-forms)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by KKitagawa-Bosch** [comment]
@eileen-coforma confirmed with Laura, there is a separate guidance for form detail pages, I've asked CAIA to add that guidance to the content style guide and you don't need to make any changes for this ticket!
