### ISSUE TITLE
10-7959f-1 Require email address on FMP registration form

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95198]
As the VA, I need the ability to notify users about the status of their forms.

### Acceptance criteria

When a user fills out form 10-7959f-1, the user must include an email address in order to submit

**Comment by reiting** [comment]
<img width="668" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1Z2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c4759a28d84ecd4753ba3556489bfc7fde5341b/Screenshot%202024-10-24%20at%209.47.12%E2%80%AFAM.png" alt="Screenshot 2024-10-24 at 9.47.12 AM.png" />

**Comment by reiting** [comment]
@baltes this has been merged and should be in staging soon.

**Comment by baltes** [comment]
checked in prod without submitting and test submits in staging look good.
