### ISSUE TITLE
PBP | ZSF general monitoring functions

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#95195]
Implement the suggested statsd + log format for 'silent failure'
https://dsva.slack.com/archives/C07QVEDUQ2D/p1728588722593559

[Silent Failure Logs.pdf](https://github.com/user-attachments/files/17415062/Silent.Failure.Logs.pdf)

[Pension: new statsd to feed ZSF Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94515)
[Burials: new statsd to feed ZSF Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94516)

Task:
- [ ] implement functions for monitoring of 'silent failure'
- [ ] create separate lib folder for `zero_silent_failures`

Acceptance:
- [ ] code is able to be reused by other teams
- [ ] 100% test coverage
- [ ] 100% documentation

**Comment by sanjabaj2** [comment]
Just a small note on PDF document.  Recently (last Friday) we changed the statsd spec for the case where we send email to VANotify but don't know if it was successfully sent. 

"Silent failure, user emailed (unknown if successfully emailed):
statsd.increment('silent_failure_avoided***'
"

Should be "statsd.increment('silent_failure_avoided_no_confirmation',". Apologies for changing spec mid-flight.
