### ISSUE TITLE
Look into adding new metrics for Logging silent failures

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#95196]
A silent failure is defined as any case where a Veteran is not aware that a request made by them was not completed. A silent failure is silent to the Veteran or other user. A VA system has accepted their form, evidence, or other submission on VA.gov or the mobile app, but that submission failed somewhere in the handoff to downstream systems, and we never told the user that it failed.

Logging unresolved silent failures
Use this log message when your team has identified a silent failure. A silent failure occurs when the application is not sending an email notification to the user for any reason.

statsd.increment('silent_failure', [tags=[service:"appeal-application",function:"lighthouse upload"])

AC:
Log unresolved silent failures
Logging resolved failures
Log message details

**Comment by andrea-merrill** [comment]
This will follow the guidelines laid out [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md).

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/19370
https://github.com/department-of-veterans-affairs/vets-api/pull/19253

**Comment by cloudmagic80** [comment]
There is another ticket tracking monitoring improvements.
https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/95531

**Comment by cloudmagic80** [comment]
Our goal is to have our "zsf" error show up in this dashboard.
[Uploading... Screenshot 2024-11-13 at 7.27.54 AM.png]

**Comment by cloudmagic80** [comment]
This slack chat is discussion different ways zsf can be measured and coded. https://dsva.slack.com/archives/C053U7BUT27/p1729525668948129
"The primary goal for these metrics is to be leadership reportable: here are the number of silent failures, or silent failures that were avoided by notifying the veteran, broken down by system and function in the system.  So for things like function name something that makes sense to this audience is best." - Steve Albers

**Comment by cloudmagic80** [comment]
Here is the ZSF monitor used by the burials team.
https://github.com/department-of-veterans-affairs/vets-api/blob/b01c9205ccf3b6927a6fdf42015bd6a2cda39294/lib/zero_silent_failures/monitor.rb

This one used by simple forms team.
https://github.com/department-of-veterans-affairs/vets-api/pull/19035/files

As you can see, the implementation is vastly different
