### ISSUE TITLE
Create YAML Template for Lighthouse Onboarding

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#95201]
## Description 
We need to create a YAML template for Lighthouse Onboarding because the process differs from the general onboarding process. A YAML template will help us systemize the information we collect.

---

## Definition of Done
All tasks below complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by GWright321** [comment]
Draft Template [here](https://github.com/GWright321/Test/issues/new?assignees=&labels=Lighthouse-Onboarding%2C+platform-orientation%2C+new-vfs-team-member&projects=&template=Lighthouse_Onboarding.yml&title=Onboarding+of+%5Bindividual%5D).

**Comment by alyssagallion** [comment]
LH Roster access moved to a new ticket since the template portion was completed for this (the original scope).  New ticket here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/96472
