### ISSUE TITLE
The top level heading of the instance of the card on the Replace and Next steps page should be H3 styled as an H4.

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#95218]
## Background
Small styling tweak, called out by Design QA: https://github.com/department-of-veterans-affairs/va.gov-team/issues/93570#issuecomment-2418074208

> The top level heading of the instance of the card on the [Replace](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1474-1830550&node-type=frame&t=Uqmorbhn0csnDMqW-11) and [Next steps page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4376-204896&node-type=frame&t=Uqmorbhn0csnDMqW-11) should be H3 styled as an H4.

![Image](https://github.com/user-attachments/assets/897c7b0d-941a-4413-ad55-119fe09a9c35)

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

**Comment by oddball-lindsay** [comment]
This could actually be tackled in https://github.com/department-of-veterans-affairs/vets-website/pull/32607

**Comment by oddball-lindsay** [comment]
@mtri double checking on this finding. Specifically for the Replace screen, the [annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8967-303471&t=EAvsgPuw0NJnvWyP-4) indicate that the header in the card component should be an H5, not an H4.

I'm wondering if this finding should be restricted to only the Next Steps page?

**Comment by mtri** [comment]
There are differences between the confirmation page and the replace page not captured in the initial finding. Apologies for any confusion. The direction indicated on https://github.com/department-of-veterans-affairs/va.gov-team/issues/98032 is more correct for the Replace page.

**On the replace page**
You are right, H5 is the correct heading level for correct nesting. They would then be styled for consistency with other instances of the cards (H3/H4).

The annotations kit now has an easy way of displaying this. [I have updated the annotation.](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153573&node-type=frame&t=toRFXhNZSLttcaNE-11)

![Image](https://github.com/user-attachments/assets/bfc9546a-2341-48f8-9be3-18b1f9c06272)

**On the next steps page**
The QA finding stands that the top level heading of the instance of the card on the [Replace](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1474-1830550&node-type=frame&t=Uqmorbhn0csnDMqW-11) and [Next steps page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4376-204896&node-type=frame&t=Uqmorbhn0csnDMqW-11) should be H3 styled as an H4.

I’ve updated [the annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153573&node-type=frame&t=toRFXhNZSLttcaNE-11) to include the styling difference.

![Image](https://github.com/user-attachments/assets/d3aef873-85a8-4c9c-8807-4749584f87f1)

**Comment by oddball-lindsay** [comment]
Thanks @mtri I'm going to close this out and we'll pursue alignment over in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98032 to blend your recommendation with the CAIA accessibility finding.
