### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/va.gov-team#95222]
### Your Name

Robert Hasselle

### Your GitHub handle (Flipper UI access is managed through GitHub)

@rhasselle-oddball

### Team, Role, and Company of the target individual

VA Forms, Tooling and frontend developer

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Testing feature toggles. Standard development.

**Comment by lindsay-insco** [comment]
@rhasselle-oddball you have been granted access to the Flipper lesser environments.
