### ISSUE TITLE
Exclude scheduling flow pages from the Intercept Survey (keep review & confirmation pages)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95238]
## Description
We have been asked to ONLY have the Intercept Survey appear on the Review & Confirmation pages. So, we will need to submit a request to the Contact Center have the other pages excluded.

[Slack thread](https://dsva.slack.com/archives/C06RMRJCLHH/p1729188388170459?thread_ts=1729170799.258759&cid=C06RMRJCLHH)

**Comment by loripusey** [comment]
@brianseek Do we have a list of all of the URLs for CC? I need to create a contact center ticket to exclude all but the review and completion pages.

**Comment by brianseek** [comment]
If not on the review or completion pages, that leaves only two:
- https://va.gov/my-health/appointments/schedule-referral/
- https://va.gov/my-health/appointments/schedule-referral/date-time

**Comment by loripusey** [comment]
thanks

**Comment by loripusey** [comment]
The contact center team has not completed our request from back in July to exclude some of our URLs for Pre-Check-in, eCheck-in, & OH Travel from the popup survey. Since they have not started the ticket, I went ahead and added the 2 URLs above to the list and let them know.  Here is the ticket: https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/88729
