### ISSUE TITLE
New Confirmation Page: Successful submit flow (with claim id, less than 30 seconds) - part 1

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#95230]
## Issue Description
Part 1 of the scenario where `submit_all_claim `returns 200 success and `submission_status` also returns 200 with a claim id.

mocks: https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8405-81028&node-type=canvas&t=GfE5gH2njk8MkOsV-0

1. Modify content (text only) of loading page
![Image](https://github.com/user-attachments/assets/dbaf3534-a5c2-4c56-9b4e-b21f37ebb73a)

2. Modify content of success alert on confirmation page, utilizing new forms-system's ConfirmationView ([doc](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/ConfirmationView/README.md)) Note: the date in the alert header has the same date as in the 'Date submitted' on the blue card
![Image](https://github.com/user-attachments/assets/8978f6c6-206b-45f2-82b4-7427583abef8)

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Verify text on loading screen is updated to display 'Preparing your submission. This may take up to 30 seconds. Please don’t refresh the page.'
- [x] Verify success alert has all the new text content
- [ ] ~Verify claim id is still displayed on blue card (any further edits to the blue card are in a subsequent story)~ 10/31/24 Removing from AC. Since we're now using the new Confirmation template, the blue card has not yet been added yet (any old components on the confirmation page will not display with toggle on). Will be added with part 2 story.
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [ ] ~The data returned matches API response (for given user or scenario)~ n/a, no api changes
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mayacarrolluxa6** [comment]
@christinec-fftc The Confirmation page design has been updated to align with the VFF template. You can find the latest designs on page in the Figma [file](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/(526ez)-New-Confirmation-Page-and-Email-Touchpoints?node-id=8410-163646&t=X4DE2T78g8DAOn44-4) underlined in red. 

![Image](https://github.com/user-attachments/assets/8bdc0107-e09e-4b89-a4ca-107e909fa4e8)


A few notes from the our meeting with @pacerwow and @StevenStraily:
- @pacerwow has confirmed that building the new confirmation page can be pulled out of Sprint 10 and into Sprint 9.
- We have confirmed with the VFF team that the date in the "Form submission started on date" should be the date the user clicked submit on the form connected to the confirmation page.
- Claim ID will not be on the confirmation page on a successful backup path. 
- The blue box's title "Disability Compensation Claim (Form 21-526EZ)" will be adjusted to align with the plain language guidance that CAIA published today, please coordinate directly with @StevenStraily  on this copy update.

Mockup of Confirmation Page Design - Happy Path below 👇
![Image](https://github.com/user-attachments/assets/4b69759e-680c-4360-ad46-f97603eeecc4)

**Comment by christinec-fftc** [comment]
Paired with Steven this morning to walk through what was built. We're good to go 👍
