### ISSUE TITLE
Staging Testing for Separation Locations (BRD) feature in 526

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#95246]
Test the LH BRD provider for form 526 on staging

The testing on staging should be a couple points worth of work, unless it is difficult to clear the redis cache/check if the new LH BRD provider was used in the call, which we can see in datadog
-- the cache may be cleared due to time already for a staging user, so try that first.
-- the complexity here is that the data call is wrapped in the redis cache.
-- is there a way to clear this cache and re-retrieve the data to test that this is working properly?
-- we may be able to do this through the rails console
-- this may also not be necessary because the redis cache clears for a user, so we may just have to hit the page in the form and we'll be good.

Note: Only in the BDD flow

Tasks:
- [x] on [staging-api.va.gov](https://staging-api.va.gov/flipper/features), turn on the Flipper flag for brd:  `disability_compensation_lighthouse_brd`
- [x] find where BRD is used on the front-end (separation locations page)
- [x] trigger the component to search for a brd
- [x] at this point check 2 things:
- [x] 1. check datadog for the log: `@payload.action:"disability compensation factory choosing API Provider" @payload.provider:"lighthouse" @payload.factory:"brd"`
- [x] 2. the list of separation locations shows up
- [x] report results to team

## Acceptance Criteria
- [x] The Separation Locations page looks the same as it did before
- [x] The Separation Locations page functions in the same way as it did before
- [x] There is no difference in the user experience
- [x] We are able to make a decision on to deploy or not deploy
- [x] If additional work is needed, tickets are created

## Additional Information
Data could be lost for Veterans who have an In Progress Form (IPF). 
For every deploy the cache is cleared? This may have some impact. We're not sure why this happens

To start BDD flow on Staging, select "yes" for active duty question, then answer future separation date with a date that's between 90-180 days in the future.

**Comment by tommasina-va** [comment]
We tested this on staging by: 
- Starting BDD flow on Staging, selecting "yes" for active duty question, then answering future separation date with a date that's between 90-180 days in the future.
- In Argo,  running ```EVSS::ReferenceData::ResponseStrategy.find("all_users:get_separation_locations")``` to see the cached separation locations
- Selecting a separation location in the UI, then save application for later
- In Argo, we cleared out the list of locations with ```EVSS::ReferenceData::ResponseStrategy.pop("all_users:get_separation_locations")```
- Then, enabled the `disability_compensation_lighthouse_brd` flag
- Then restarted the application and navigate to the separation location page
- The UI should now have the separation location in the type-ahead text box
- In Argo, ```EVSS::ReferenceData::ResponseStrategy.find("all_users:get_separation_locations")``` will now show the Lighthouse separation locations as Active Record objects. 
- In the UI, the list looks the same and functions the same as before.

Also just a note that someone needed to update our staging Lighthouse API key for our BRD requests to work.
