### ISSUE TITLE
Create the referrals and requests page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95266]
![Image](https://github.com/user-attachments/assets/a687f339-bf49-4d4e-89a8-4e9795871ce5)
[figma link](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4873-21647&node-type=frame&t=7WYzFHFmfSMP6M5H-0)
 - [ ] Copy pending appointments page and make new page for referrals and requests
 - [ ] Create new route in appointments-list
 - [ ] unit tests
 - [ ] page should only work if feature is on (maybe redirect to pending if off)

**Comment by loripusey** [comment]
validated screenshot from PR with wireframe, closing

**Comment by wullaski** [comment]
@loripusey, @brianseek This work has been merged into production.
