### ISSUE TITLE
[0 pts left] Mock data for referrals (happy & error paths)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95262]
Tasks:
 - [x] Referral mock is generated with an array of objects like the example below(subject to change when data comes from map):
    ```
    Sta6aKey: String
    ReferralStatus: String
    ReferralCreateDate: Date
    ReferralFromDate: Date
    ReferralToDate: Date
    FirstActiveDateTime: Date
    FirstScheduledDateTime: Date
    HSRM_AllocatedDate: Date
    HSRM_DateSetToAccepted: Date
    HSRM_DateSetToApproved: Date
    HSRM_DateSetToFirstAppointmentMade: Date
    HSRM_DateSetToInitialCareGiven: Date
    HSRM_DateSetToRejected: Date
    EarliestDate: Date
    CareCategory: String
    ReferralNumber: String
    VendorName: String
    VendorNPI: String
    Zip: String
    ReasonForReturn: String
    driveTime: string,
    driveDistance: string,
    UUID: string,
    numberOfAppointments: number
    typeOfCare: string
    ```
 - [x] All date fields should be generated dynamically into the future from time mock is generated. Dates should be relative from `ReferralCreateDate` into the future
 - [x] Default to 3 for now a few days apart, make it easy to update.
 - [ ] Add referral API fetch to appointments page if feature is on and store in redux (move to a new ticket if this feels too much)
 - [x] maybe sanitize the naming convention of fields in redux to make sense to the application i.e. VendorName -> ProviderName
 - [x] create mock for no referrals (empty array)
 - [ ] create mock for 500 error

**Comment by brianseek** [comment]
Referral object has changed based on https://dsva.slack.com/archives/C06RMRJCLHH/p1730405565522599?thread_ts=1730405555.512689&cid=C06RMRJCLHH

Mock currently contains:
```
    ReferralCategory: String,
    ReferralDate: Date String,
    ReferralExpirationDate: Date String,
    ReferralLastUpdateDate: Date String,
    ReferralLastUpdateDateTime: Datetime String,
    ReferralNumber: String,
    ReferringFacility: String,
    ReferringProvider: String,
    SourceOfReferral: String,
    Status: String,
    CategoryOfCare: String,
    StationID: String,
    Sta6: String,
    ReferringProviderNPI: String,
    ReferringFacilityInfo: {
      FacilityName: String,
      FacilityCode: String,
      Description: String,
      Address: {
        Address1: String,
        City: String,
        ZipCode: String,
      },
      Phone: String,
      Fax: String,
    },
    ReferralStatus: String,
    UUID: String,
    numberOfAppointments: Number,
```

**Comment by brianseek** [comment]
Created new ticket for implementation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96439

**Comment by brianseek** [comment]
this is now merged moving to closed since there is no further validation needed.
