### ISSUE TITLE
[2 pts left] Create Task Card Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95265]
![Image](https://github.com/user-attachments/assets/935a02f0-afd3-4769-af85-20ce2b47d80d)
 - [ ] Create component for displaying referral as task card
 - [ ] component takes referral object as prop
 - [ ] fetch referral from redux by UUID
 - [ ] conditionally show if UUID passed and feature is on
 - [ ] show date in `Month DD, YYYY` format
 - [ ] add unit tests

**Comment by juancstlm-a6** [comment]
@zack and @cgednalske mind taking a review at the screenshots here https://github.com/department-of-veterans-affairs/vets-website/pull/33014 and leave any comments if needed.

**Comment by cgednalske** [comment]
@juancstlm-a6 everything looks great with the card! 

One question I have: Do you know where did the second action link for "Review and manage your appointment notifications" come from? That's not something we just added for CC, is it?

**Comment by juancstlm-a6** [comment]
> [@juancstlm-a6](https://github.com/juancstlm-a6) everything looks great with the card!
> 
> One question I have: Do you know where did the second action link for "Review and manage your appointment notifications" come from? That's not something we just added for CC, is it?

I believe the action link you are referring to shows up when we enable the feature flag for CC direct scheduling, which it is on for any work for CC like this component. This is existing feature so not sure why it shows up then maybe @wullaski knows
