### ISSUE TITLE
[2 pts left] Mock data for Provider availability (happy & error paths)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95263]
Tasks:
 - [x] create a mock that takes a providerId param and returns data like the example below (get with Lee for a more detailed view of the data the names below are just made up)
     ```
     ProviderName: string, (maybe in the referral payload)
     typeOfCare: string,
     orgName: string,
     orgAddress: {
        street1: string,
        street2: string,
        street3: string,
        city: string,
        state: string,
        zip: string,
     },
     orgPhone: string,
     location: string,
     slots: [
        {
           id: number,
           start: date,
           end: date,
       }
    ]
     ```
 - [x] slots should be generated dynamically into the future from the current date
 - [x] Add provider API fetch to date picker page and store in redux, think about storing this within the referral object in question (move to a new ticket if this feels too much)
 - [x] create mock for no slots

**Comment by brianseek** [comment]
this is now merged, no further validation needed.
