### ISSUE TITLE
Hook up to the mock data

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95269]
The Referral for [type of care] page is created but needs to use the mock referral data.
[Figma for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4968-15975&node-type=frame&t=yDs1IXGTLdmg6Dy5-0)

Tasks:
 - [x] Select referral data from redux to populate page content
 - [x] If referral data missing this page should trigger an API call to get it in a useEffect

**Comment by brianseek** [comment]
this got completed with the PR from https://github.com/department-of-veterans-affairs/va.gov-team/issues/96439

Moving to closed
