### ISSUE TITLE
QA updates: Replace Current Representative [2]

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/va.gov-team#95260]
## Issue Description
Continuation of https://github.com/department-of-veterans-affairs/va.gov-team/issues/93763

## Defects
- [ ]  Padding looks good on the top h3! The padding is still different on the h4s than elsewhere on VA.gov. Thanks for addressing this!
Expected:
![Image](https://github.com/user-attachments/assets/c70b66af-fbc1-424e-9683-5945727ef9bb)
Actual: (just need to adjust vertical padding; ideally matching global settings) 
![Image](https://github.com/user-attachments/assets/b4e3e944-0abe-49aa-88ec-b4a8e40f2683)

- [ ] The "Your current Veterans Service Organization (VSO)" content is intended to change on the current representative to match the type of representative? I'm using a test user than may just have some dummy data configured wrongly, but it's showing the individual rep as a Veterans Service Organization.

The "Note: You can work with any accredited VSO representative at this organization." will not display on an individual either.

![Image](https://github.com/user-attachments/assets/421eb159-6836-4aad-9033-4193ab21a9ba)

## Acceptance Criteria
- [ ] Defects have been addressed

**Comment by oddball-lindsay** [comment]
@mtri can you please share what the expected design is?

_Note: Tamara Ellis is part of the old models, but it may be hard to find a test user that doesn't have her as a rep._

**Comment by mtri** [comment]
Confirming the VSO content is displaying for the current representative regardless if it's an attorney or claims agent.

[I put together the expected design here.](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=12063-591877&node-type=frame&t=eGkET19HQjry5DH7-11)
- Dynamic text would display depending on the type of representative like [on the typical widget](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1411-386887&node-type=frame&t=eGkET19HQjry5DH7-11). (The widget heading being dynamic depending on the type is a later update that has not yet been implemented for the widget)
- Just like with a VSO representative, the "Download your accredited representative's contact information" and "Learn about accredited representatives" will not display.
- This screen also shows how the current accredited attorney or claims agent would display on this page.

@cosu419 let me know if something doesn't make sense to you here, happy to sync on this!

**Comment by oddball-lindsay** [comment]
I'm logged in as a test user that has an appointed attorney ([line 6 in our test user spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv)) and some of the defects listed here may have been resolved:
- Padding is looking as expected for the h3 (less vertical space on the bottom)
- The representative has "Accredited Representative" below their name, as opposed to "Veteran Service Organization"

![Image](https://github.com/user-attachments/assets/7203136c-7dcb-4e41-adc9-b473d136d854)

It seems like the only thing remaining to fix is removing the note for non-VSO and VSOR selections. @mtri can you take a look and confirm you're seeing the same?
