### ISSUE TITLE
Fix a few page details

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95272]
Tasks:
 - [ ] Selected date validation should happen after clicking to continue
 - [ ] Telephone number should be clickable with `href=://tel:` 
 - [x] ~~Store selected date keyed on referral UUID in session to restore on refresh~~
 - [ ] Restore selected date from session on reload
 - [ ] Time zone should be based off of referring facility
 - [ ] Use existing VAOS TZ formatters

**Comment by loripusey** [comment]
@brianseek can you validate this today and close?

**Comment by brianseek** [comment]
Just did a code review and it looks good to me, so this can get closed after the PR is merged once someone with approval powers approves it, or before this sprint ends, which ever comes first.
