### ISSUE TITLE
QA updates: When user hits "back" to the rep-selection page, resurface their original query (same session only) [2]

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/va.gov-team#95279]
## Issue Description
Continuation of https://github.com/department-of-veterans-affairs/va.gov-team/issues/93957

## Defects
- [ ] Select this representative still seems to hang on click and way more so when authenticated. Perhaps we should test as a team later, it may just be a me thing.

- [ ] When going back to the select page the back and continue button pair is now hidden. It shouldn't be.
 ![Image](https://github.com/user-attachments/assets/474adcb9-892e-4a1f-9ee4-98f1569d9c66)

## Acceptance Criteria
- [ ] Defects have been addressed

**Comment by oddball-lindsay** [comment]
The "Back" and "Continue" buttons are now appearing as expected:

![Image](https://github.com/user-attachments/assets/69713a1f-7ee6-4781-b618-475b743e0e84)

And I'm able to see rep search results come up in near real time (doesn't feel like a long wait to me), so perhaps this was related to the test rep data. Closing this out, but we can revisit if anyone experiences long load time in our QA exercise.
