### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95270]
The Referral for [type of care] page is created but needs unit tests.
[Figma for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=4968-15975&node-type=frame&t=yDs1IXGTLdmg6Dy5-0)

Tasks:
 - [ ] Create unit tests for all functions
 - [ ] acceptable code coverage

**Comment by loripusey** [comment]
@brianseek can you validate this today and close?

**Comment by brianseek** [comment]
@loripusey @juancstlm-a6 The PR is approved and there is no further validation needed. So this can get closed once the PR is merged, or before we wrap up the sprint, which ever comes first.

**Comment by juancstlm-a6** [comment]
Closing ticket. Tests updated and waiting on merge which will be tracked in https://github.com/department-of-veterans-affairs/va.gov-team/issues/97923
