### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95274]
Schedule an appointment with your provider page is created but needs unit tests.
[Figma for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5388-5267&node-type=frame&t=yDs1IXGTLdmg6Dy5-0)

Tasks:

- [ ] Create unit tests for all functions

This work is blocked by: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95271

**Comment by brianseek** [comment]
@loripusey this work is complete but not merged, closing this ticket with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98769) created to track the merge
