### ISSUE TITLE
Hook up to mock data

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95271]
Schedule an appointment with your provider page is created but needs to use the mock referral data.
[Figma for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5388-5267&node-type=frame&t=yDs1IXGTLdmg6Dy5-0)

Tasks:

 - [ ] Select referral data from redux to populate page content
 - [x] Select provider data from redux to populate page content and get slots
 - [x] Select Upcoming Appointments data from redux to use in validation
 - [ ] If referral data missing this page should trigger an API call to get it with a useEffect
 - [x] If provider data missing this page should trigger an API call to get it with a useEffect
 - [x] If Upcoming Appointments data missing this page should trigger an API call to get it with a useEffect

**Comment by brianseek** [comment]
@loripusey this work is complete but not merged, closing this ticket with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98769) created to track the merge
