### ISSUE TITLE
Create Complete page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95282]
This page needs to be created. See Figma [here](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=5383-5019&node-type=frame&t=MaCBbjQO2WtKWgOn-0)
 - [x] Create page component
 - [x] utilize existing VAOS components like the `Add to calendar` button and print button
 - [ ] Add to referral-appointments subrouter (make a new page - figure out new URL with UX)
 - [x] Select referral data, provider, and selected date from redux
 - [x] Restore selected date from session on reload, if no selected date, redirect to appointments 
 - [x] fetch referral and provider data from API on refresh with useEffect
 - [x] create unit tests

Questions remain about refresh and folks who click old completed text links. This should be further refined and broken down as we know more but the 8 point represents that effort too.

**Comment by juancstlm-a6** [comment]
Closing as code complete in further details needed to be clarified will be tracked in https://github.com/department-of-veterans-affairs/vets-website/issues/33761
