### ISSUE TITLE
Create Review your appointment details page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95281]
This page needs to be created. See Figma [here](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=2217-67077&node-type=frame&t=MaCBbjQO2WtKWgOn-0) 

Look for selected date in redux first. If its not in redux, look in session, if not in session, redirect back to schedule page.

Tasks 
 - [x] Create page component
 - [x] Add to referral-appointments subrouter
 - [x] Select referral data, provider data, and selected date from redux 
 - [x] fetch referral and provider data from API on refresh with useEffect
 - [x] Restore selected date from session on reload
 - [x] create unit tests

**Comment by brianseek** [comment]
the work here is done, closing this ticket with this [follow on](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99643) to track its merge and validation
