### ISSUE TITLE
Bug: Submit by form charts in prod datadog aren't working

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95294]
### Expected behavior
Submits for a given form type will populate the relevant graphs specific to that form

### Actual behavior
The view below includes a form 10-10d submit, but that submit doesn't show on the 10-10d submit chart. 

<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5YQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bba3dc475035343cd8da86fd4777c5334176ea9/image.png" alt="image.png" />

**Comment by andrea-merrill** [comment]
Specifically looking at the 1010-d submissions

**Comment by cloudmagic80** [comment]
Completed
