### ISSUE TITLE
Request access to tools

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#953]
Read and follow the instructions in [Github request access to tools document](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md)

Comment "done" when completed.

**Comment by mojaray2k** [comment]
I cannot finish this until I get my laptop

**Comment by Samara-Strauss** [comment]
Done

**Comment by artistgreen** [comment]
Done.  (I have requested a Sketch/InVision license through Shawna.)

**Comment by lihanli** [comment]
done

**Comment by erikphansen** [comment]
Done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by Justin-Pickett** [comment]
@mojaray2k please comment done if you have completed this step.

**Comment by mojaray2k** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. team has completed this task. Closing this ticket.
