### ISSUE TITLE
[10/18/2024 - 1:16AM ET AND 10/21/2024 - ~12PM ET] Monitor incident(s) - Missing PEGA status

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#95305]
Per playbook, opening ticket to track details of these [DD monitor alerts](https://dsva.slack.com/archives/C06RQR7V9CM/p1729228603024899) ([and followup](https://dsva.slack.com/archives/C06RQR7V9CM/p1729228722234589)).

**Intake**
- [x] PM (Bo) and DM (Andrea) have been notified
- [x] PM and DM confirmation of ticket creation

**Investigation**
- [x] Verify that vets-api is receiving submits from vets-website
- [ ] Verify that files are sent successfully to s3
- [x] Verify that the callback API is available
- [ ] Determine whether the issue arose due to a deployment, either by the IVC Forms team or the PEGA team.
  - [x] IVC
    - [x] If root cause has been identified as an issue in vets-website or vets-api, notify PM and DM to determine next stpes with PO
  - [ ] PEGA
    - [ ] If root cause has been identified as an issue outside of vets-website and vets-api, work with the PM, DM, and PO to determine contacts and next steps.

**Resolution**
- [x] Acknowledge monitoring alerts in slack
- [ ] IVC Forms engineering will provide updates on development and deployment of a solution and its status in each environment
- [ ] IVC Forms engineering will notify PM and DM when resolved
- [ ] IVC Forms engineering will monitor outstanding missing statuses and ensure they are cleared appropriately. No statuses should be deleted or cleared without agreement from PO and or PM
- [ ] If traffic to the site has been altered, PO or PM will determine when to return to previous levels.

**Comment by michaelclement** [comment]
Notes for changes we want to make as a result of this:
- Research the ability to make a DD monitor track if users are seeing error screens on the FE

**Comment by michaelclement** [comment]
[Relevant task on board for storing all JSON](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/94080)

**Comment by andrea-merrill** [comment]
Adding the [Watch Tower Ticket](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/275) link.  We'll want to circle back to this once this is resolved.

**Comment by michaelclement** [comment]
[DSVA thread where most communication has been happening](https://dsva.slack.com/archives/C05UDS77ZPH/p1729255474905159)

**Comment by michaelclement** [comment]
[Top level ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/95317) - more individual tickets to come, but this represents the DD goals in one place.

**Comment by michaelclement** [comment]
Engineers will be having a meeting at 12CT today to discuss moving forward with DD improvements.

**Comment by cloudmagic80** [comment]
Notes for backend: Create a ticket for save parsed json data into PEGA S3.

**Comment by michaelclement** [comment]
UPDATE - After a successful weekend, we've had a 2nd failure at noon ET on 10/22. ([Link to initial Data Dog message in DSVA Slack is here](https://dsva.slack.com/archives/C06RQR7V9CM/p1729526502495529)). 

Investigation ongoing, but going to lump in with this ticket since it's likely a similar issue and we haven't closed this out officially yet.
