### ISSUE TITLE
Datadog monitor and slack alerts for non-200 responses from s3

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95306]
As an IVC Forms team member, I need to be actively alerted when an upload from our forms to s3 en route to PEGA is anything other than 200.

The 400 shown below (from 10/18/2024) and any other non-200 responses should trigger an alert that gets sent to #ivc-forms-datadog for greater visibility.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3a265851018570796fc247484b504d75858e48f/Screen%20Recording%202024-10-18%20at%208.11.33%E2%80%AFAM.mov)

AC:
- Other errors, such as 403/404/500, that don't cause missing Pega Status, will still be sent to Data Dog channel so we're aware the error occurred
- Discuss with team to determine if we want one time per error sent to DD slack or if it's a reminder that goes off until cleared (identify process for clearing the error so notifications stop if we go the later route. Maybe the resolve action in DD dashboard works well here?)

**Comment by reiting** [comment]
I finally got a datadog monitor set up and working! It will send messages to the datadog channel on errors. Yay! @baltes

**Comment by reiting** [comment]
@baltes it's just datadog config. The slack alerts are set up there as well as the monitor.

**Comment by baltes** [comment]
@reiting Since we saw a 403 in prod a little while ago, should that have triggered anything in slack?

**Comment by reiting** [comment]
@baltes I'm not sure. Do we know what time the 403 was? The datadog monitor may not have been set up and running yet. It should be running NOW, but it may not have been running when that error occurred.
