### ISSUE TITLE
Fix bug with displaying note to authed users in Appoint a Rep flow

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#95319]
## Background
The helper function `isLoggedIn()` isn't working.

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
This is done.

**Comment by holdenhinkle** [comment]
This is fixed and ready for QA:

![Image](https://github.com/user-attachments/assets/5c4bfb92-4159-40b8-81ee-15bf190c4fbe)

**Comment by oddball-lindsay** [comment]
@mtri ready for you!
