### ISSUE TITLE
E2E tests are disabled with Yeoman + test docs

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#9531]
@mchelen-gov commented on [Wed May 27 2020](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/265)

## Describe the bug
Following docs for application creation & E2E testing does not result in E2E test being run locally.
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-application
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/test

## To Reproduce
1. Create app with yeoman
    - manifest looks like:
    ```json
    {
      "appName": "Your App",
      "entryFile": "./app-entry.jsx",
      "entryName": "yourapp",
      "rootUrl": "/yourapp"
    }
    ```
    - `src/applications/your-app/tests/00.your-app.e2e.spec.js` contains:
    ```js
    module.exports['@disabled'] =
      !manifest.production || __BUILDTYPE__ !== 'production';
    ```
    *note: this does not exist in example snippet https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test*
1. run `yarn build` and `yarn watch`
1. run E2E test: `yarn test:e2e src/applications/your-app/tests/00.your-app.e2e.spec.js`
1. Message shows: `00.your-app.e2e.spec module is disabled, skipping...`

## Expected behavior

Following the docs should result in successfully running E2E test.

## Notes
Some solutions are:
1. Remove the `module.exports['@disabled']` snippet from the E2E test 
1. Run prod build command `NODE_ENV=production yarn build --buildtype vagovprod` from https://github.com/department-of-veterans-affairs/vets-website#more-commands
1. Add `production: true` to `src/applications/your-app/manifest.json`

I wasn't sure though which of these is the intended approach?

## Resolution
- [ ] Update generator template https://github.com/department-of-veterans-affairs/generator-vets-website/pull/27
- [ ] Update docs?

**Comment by mchelen-gov** [comment]
took a crack at a PR here but unsure if it is correct

**Comment by meganhkelley** [comment]
@U-DON is this still an issue?

**Comment by U-DON** [comment]
This is no longer applicable since we started using Cypress for E2E tests. The app generator now produces a Cypress test instead of Nightwatch.
