### ISSUE TITLE
Enable syntax highlighting for code snippets

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#9532]
@mchelen-gov commented on [Wed May 27 2020](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/263)

**Is your feature request related to a problem? Please describe.**
Code snippets on pages like https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/ do not have any syntax highlighting, making them harder to read. 

**Describe the solution you'd like**
Enable syntax highlighting for Gatsby

**Additional context**
https://www.gatsbyjs.org/packages/gatsby-transformer-remark/

**Comment by mchelen-gov** [comment]
PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/264

**Comment by meganhkelley** [comment]
Platform Website strategy is Confluence-based so we are not going to make this change.
