### ISSUE TITLE
Add feature flag to remove Podiatry from type of care list

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#95325]
## Description
Add a feature toggle to remove Podiatry from the type of care list when scheduling an online appointment.  The removal of the podiatry option will need to be coordinated with communications to veterans, so a feature toggle is needed.

---

## Development Checklist
- [ ] Add vaos_online_scheduling_remove_podiatry feature toggle

## Definition of Done
- [ ] All tasks criteria are met
- [ ] Technical Documentation is updated

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/95325?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by ldelacosta** [comment]
Validated in staging the flipper. No further work is needed. Closing out the ticket. cc: @JRRoof
