### ISSUE TITLE
Docs: add "Edit this page in Github" link

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#9533]
@mchelen-gov commented on [Tue May 12 2020](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/258)

**Is your feature request related to a problem? Please describe.**
When viewing a page of documentation on https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/ there may be updates or corrections that require editing the corresponding file on Github. The process of finding the correct file to edit takes several manual steps.

**Describe the solution you'd like**
Add a link to the bottom of each docs page that would take you to edit the source file in Github.

**Describe alternatives you've considered**
Manually browsing the Github repo to find the correct file.

**Comment by karlbrown-va** [comment]
Just wanted to add a +1 to this FR.

**Comment by jhonnyoddball** [comment]
It's live and working properly
