### ISSUE TITLE
Design: 10-7959-f1 Add a required email field to Figma File

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#95338]
Add a required email field to the [FMP Registration form in Figma ](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=2602-54276&node-type=canvas&t=TdGzMIlRPHFRJLB0-0)so we can send communication about the form's progress to the applicant. 

- [x] Create the field [in Figma](https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=2602-54276&node-type=canvas&t=TdGzMIlRPHFRJLB0-0)
- [x] Handoff to the engineers so they can complete[ Ticket #95198](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/95198)

**Comment by rspope** [comment]
@baltes The Figma file has been updated to indicate email as a required field. The engineering ticket is not dependent on this design, but please review and close. 
https://www.figma.com/design/PzB1F5TYuBK5KQgPbuhAwH/FMP-Registration-10-7959f-1?node-id=3258-49250&t=eIgjWhYCJif9KLY1-4
