### ISSUE TITLE
Remove Podiatry as an option from type of care list

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#95332]
## Description
The Office of Connected Care is requiring that requests for community care podiatry appointments come from referrals and not veteran requests.  Therefore, the option to select Podiatry from the type of care list when scheduling online must be removed.  This change will be behind a feature toggle so that the removal of this option can be coordinated with communications to the veteran.

---

## Development Checklist
Background: the `vaos_online_scheduling_remove_podiatry` toggle is on 

- [ ] Remove the Podiatry option highlighted (bolded/italicized) below from the list of menu options when the feature toggle is enabled:

What care do you need? (*Required)
- Amputation care
- Audiology and speech (including hearing aid support)
- COVID-19 vaccine
- Eye care
- Mental health
- MOVE! weight management program
- Nutrition and food
- Pharmacy
- _**Podiatry (only available online for Community Care appointments)**_
- Primary care
- Sleep medicine
- Social work

### Design Assets
- N/A

### Developer Reference

- Page URL to change: https://va.gov/my-health/appointments/schedule/type-of-care
- Current page content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-a-type-of-care
- 
## Definition of Done
- [ ] All tasks criteria are met
- [ ] Technical documentation is updated

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/95332?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JRRoof** [comment]
Tested with feature toggle enabled for Judy Morrison.
![Image](https://github.com/user-attachments/assets/405e19f8-1140-423f-bed4-2f11450dcffd)
