### ISSUE TITLE
Adding Margaret Borowczyk to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#95351]
Please add Margaret Borowczyk as a multi-channel member to:
#research-ops and #design

Margaret Borowczyk is a UX researcher on the Lighthouse progam and will need access to perform her job responsiblities.
 
Work email: margaret.borowczyk@adhocteam.us
VA email: malgorzata.borowcyk@va.gov

Thank you!

**Comment by huggins-va** [comment]
@KevinMHoffmanUSDS @LEHigley @lkoenigsberg   Maragaret B. is still waiting for DSVA access.  Can you please provide an update?

**Comment by Dmharris625** [comment]
Created: #96477
