### ISSUE TITLE
Analytics Implementation or QA Support for Veteran Facing forms - Confirmation page events

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#95364]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Veteran Facing Forms**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]

- **Poduct Name**

    - New Confirmation page on 21-10210
      
- **When is the launch date?**
    - 10/22/2023

- **Provide the link(s) for Product/Page urls**
  
    - [Confirmation page](https://staging.va.gov/supporting-forms-for-claims/lay-witness-statement-form-21-10210/confirmation)

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_

 **Track the following events:**

- Check stats on my va - "lay-witness-10210-confirmation-check-status-my-va"

- Download PDF - "lay-witness-10210-confirmation-pdf-download".
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @tbaker1026 -- thanks for submitting this. Our team will take a look, and let you know what we find, and any potential next steps.

FYI @ChristineYoungZA, @jestutt, @Blivaditis

**Comment by johnny-jesensky-adhoc** [comment]
Hi @tbaker1026 -- I realize some of this was addressed in [this support ticket](https://dsva.slack.com/team/U04M530NCP4), as well as an _Office Hours_ session last week.

`lay-witness-10210-confirmation-check-status-my-va` is already being tracked as a va-link component, and the download event has not yet been activated.

FYI @jestutt, @rhasselle-oddball

**Comment by tbaker1026** [comment]
@johnny-jesensky-adhoc Yes we can go ahead and close it - Robert did address it. Thank you!
