### ISSUE TITLE
AWS access for [Brandon Dech]

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#95393]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Brandon Dech

### Your Email

brandon.dech@oddball.io, brandon.dech@va.gov

### Team, Role, and Company of the target individual

Platform Tech Team Support, Support Specialist, Oddball

### Product Manager (PM) name and email

Alyssa Gallion | alyssa.gallion@oddball.io

### Product Owner (PO) name and email

Erika Washburn | Erika.Washburn@va.gov

### Desired AWS Access

Requesting access to reset MFA and passwords

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/64f96188-66b3-47ec-b809-2e1408521b5c)

### Additional Notes

COR: Ray Wang

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by ph-One** [comment]
Onboarded. This was during a call we had for onboarding specific members of Support to AWS.
