### ISSUE TITLE
Jenkins Job to Build Sentry 10

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#9539]
## The Problem
Sentry 10 does not yet have a "Build" job in jenkins.

## Why?
All of our BRD jobs needs a build, release, and deployment job in jenkins so that engineers and automation can start these jobs.

## Extra Context
The `sentry10` "build" has been merged into the devops master ([link](https://github.com/department-of-veterans-affairs/devops/pull/6929))

## Work to be Done
- [x] Create a PR modifying the [`seed_job.groovy`](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy) with the `sentry10` build job
- [x] Copy + paste the new seed job into Jenkins
![image](https://user-images.githubusercontent.com/3077884/83055309-b0df2380-a021-11ea-8c65-061ab6e33cec.png)

- [ ] Run the [`seed-job` jenkins job](http://jenkins.vfs.va.gov/job/seed-job/)

**Comment by kfrz** [comment]
This has been merged by @omgitsbillryan in `/devops` [PR](https://github.com/department-of-veterans-affairs/devops/pull/7132)
