### ISSUE TITLE
Everyone read the Norms For Using Tools Document

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#954]
Read the [Norms for Using tools](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-tools.md) documentation. Please complete the instructions included that pertain to you. Once completed please comment "done".

**Comment by mojaray2k** [comment]
Done

**Comment by Samara-Strauss** [comment]
Done

**Comment by lihanli** [comment]
done

**Comment by erikphansen** [comment]
done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by Justin-Pickett** [comment]
@artistgreen please comment done if you have completed this already.

**Comment by artistgreen** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. team has completed this task. Closing ticket.
