### ISSUE TITLE
Spanish language content, questions, and collateral

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9540]

**Comment by batemapf** [comment]
Hill inquiry about Spanish language materials that might be pertinent:

https://dsva.slack.com/archives/G0107KRQMD5/p1591879318004400

**Comment by batemapf** [comment]
Reaching out to Eunice at HQ about an offer to help w/ Spanish language translation. If that's still available, will ship over content files (question config + page content) and a link to the CDC screener that has lots of translation done already so she can work on it while we are on hiatus.

**Comment by batemapf** [comment]
Timestamp should be in Spanish, too. E.g. https://stackoverflow.com/questions/30842477/momentjs-time-in-spanish

**Comment by batemapf** [comment]
Shipped this over to Eunice: 
[VAgov-covid-screening-tool-content-library.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4938805/VAgov-covid-screening-tool-content-library.docx)

**Comment by batemapf** [comment]
latest version: 
[Translation for VA Tool - pfb (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5024626/Translation.for.VA.Tool.-.pfb.1.docx)

**Comment by artsymartha68** [comment]
<img width="739" alt="Screen Shot 2020-09-23 at 10 04 40 AM" src="https://user-images.githubusercontent.com/47792423/94023619-6ded4c80-fd84-11ea-9839-b833bce99731.png">

Thinking the first and last screens would look something like this.

**Comment by artsymartha68** [comment]
Reworking the first screen, thinking we need both languages for all instructions?

**Comment by artsymartha68** [comment]
Screenshot updated above. Patrick's excellent idea of having a link for the Spanish path.

**Comment by mchelen-gov** [comment]
closed by https://github.com/department-of-veterans-affairs/vets-website/pull/14499
