### ISSUE TITLE
SPIKE: Set up CC backend structure in the VAOS module (Where at, standalone or under VAOS)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95402]
Talking to Appointments team to decide where to put module

**Comment by lee-delarm6** [comment]
@simiadebowale Answered it's totally fine to drop this under the VAOS module 👍

**Comment by randomsync** [comment]
started a conversation in vaos-engineering channel in terms of co-locating the cc resources (referrals and appointments) within vaos module
