### ISSUE TITLE
AWS access for Lindsay Insco

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#95400]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Lindsay Insco

### Your Email

lindsay.insco@oddball.io

### Team, Role, and Company of the target individual

Platform Team, Tier 1 Support, Oddball

### Product Manager (PM) name and email

Andrea Townsend 

### Product Owner (PO) name and email

Erika Washburn - erika.washburn@va.gov 

### Desired AWS Access

I need support-level access in order to assist with daily Platform Support tasks (Password and MFA help for locked-out users)

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/7df90d5d-1db3-4f01-b80d-18491a8339f3)

### Additional Notes

COR is Ray Wang

Ongoing access is requested to maintain the ability to provide support for users with password or MFA issues. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by lindsay-insco** [comment]
I couldn't remember if you needed my PIV sponsorship confirmation so I uploaded it in case.

![Image](https://github.com/user-attachments/assets/7ea0b5ff-c447-435d-b4a6-c5a91b476311)

**Comment by ph-One** [comment]
Onboarded. This was during a call we had for onboarding specific members of Support to AWS.
