### ISSUE TITLE
Develop logic to de-dupe appointments EPS vs. VistA

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95414]
Additionally:

Create mock endpoint and write unit tests (Ruby, RSpec, request specs)

**Comment by lee-delarm6** [comment]
Implement logic to check for duplicate referrals, existing appointments, and expired referrals

- A duplicate referral refers to a referral that has already been entered into our system. The incoming referral ID will match an existing referral ID in our postgress DB. This is likely a referral that hasn't been scheduled into an `appointment` yet. See blow for `existing appointment`
- An existing appointment refers to an appointment that has been made with a referral ID, that referral ID matches to a "new" referral, which means it was already made. We can also possibly hold referrals in our DB and mark them as "completed" or "referral made" in the same manner, after the user has completed making an appointment with a referral
- Expired referrals are referrals whose end date has expired, regardless of if an appointment exists or not

**Comment by lee-delarm6** [comment]
This ticket should call (but not implement) the services to get EPS appointments, and VistA appointments, as well as checking what's in the PostgresDB itself to validate the appointment.

Also, this should probably be called "validateReferral" or something like that
