### ISSUE TITLE
Document website header configurations. Set policy 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9545]
## Background

- VA.gov sends several headers to users browsers. The configurations for all of these headers are not documented. Policies for them are not set. 

## Tasks 

- Document all of the headers sent by VA.gov for maintainers. 
  - I should be able to figure out how to update any header (CORS, CSP, cache-control, etc) by reading this document 
- Identify where there are no policies set and determine if we should have best practice guidelines. ensure the policy is testable or monitored. 

## Notes

- Review existing documentation. Some headers are [already documented](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/content-security-policy.md) and this artifact should be reconciled with those.

**Comment by rmessina1010** [comment]
Expired. Closing.
