### ISSUE TITLE
DRY up address, email, phone, google map link, contact card and standardize the order email and phone appears in

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#95459]
## Background
The ContactCard component has not be used used by all the contact cards that are rendered in Appoint because of various minor differences between all of them. I met with Michael to discuss the issue and he agreed that they should all be 'standardized' - all rep cards should have the person icon, the order of the contact info should always be email then phone, etc.

Refactor Appoint so all contact cards use the ContactCard component.

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
Done

**Comment by holdenhinkle** [comment]
There's a bug on this page - https://staging.va.gov/get-help-from-accredited-representative/appoint-rep/representative-replace

![Image](https://github.com/user-attachments/assets/db7b5ff8-2ea5-4474-b7f5-2bd99a43a82e)

No error logs in the console.

**Comment by holdenhinkle** [comment]
PR for bug fixes - https://github.com/department-of-veterans-affairs/vets-website/pull/32697

**Comment by oddball-lindsay** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/32611 should be merged before the PR to address this issue.

**Comment by holdenhinkle** [comment]
Found a new bug and fixed it. The fix has been merged and I verified we're good now:

![Image](https://github.com/user-attachments/assets/388188c5-87fd-4d70-87f6-4aa78f773dfe)
