### ISSUE TITLE
Kick off Unmoderated Study with Perigean & Monitor

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#95475]
- [ ] Hold kick-off meeting with Perigean
- [ ] Monitor study

**Comment by cgednalske** [comment]
@loripusey fyi this is also blocked as I wait for a 👍 or feedback

**Comment by cgednalske** [comment]
@loripusey I received feedback from Kristen but have some edits to make. As a result, I may still get the study submitted to Shane before end of sprint for the other research ticket, but this ticket will definitely need to roll over.

**Comment by cgednalske** [comment]
@StevenStraily I'm adding you to this ticket as well so you can join me on this work as we go into the study 🙂

**Comment by loripusey** [comment]
yes, let's close this one and create a duplicate for next sprint
