### ISSUE TITLE
Update DOMO dashboard to include Tier I data

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#95486]
This epic focuses on enhancing the existing Domo dashboard to incorporate Tier 1 data for improved visibility and analysis. The update will allow users to interact with and report on key Tier 1 data metrics alongside existing data, providing a comprehensive view of business performance. This epic covers data ingestion, dashboard updates, user training, and testing.

**Comment by clantosswett** [comment]
@ATMiddleton @newworld2616 are we considering this done? I think we should and we can open up new tickets/epics for any future dashboard work.

**Comment by newworld2616** [comment]
@clantosswett I will close the ticket.

**Comment by newworld2616** [comment]
Completed!
