### ISSUE TITLE
Use `user` selectors in `vet360` selectors

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#9548]
There are selectors in https://github.com/department-of-veterans-affairs/vets-website/blob/399167559ff532bc8c15eb9cd2359b0f368ec0f7/src/platform/user/selectors.js that should be leveraged in these selectors https://github.com/department-of-veterans-affairs/vets-website/blob/f82c16c4c8823f8e00952e58e027bf3511539b9e/src/platform/user/profile/vet360/selectors.js

**Comment by sanlouise** [comment]
@mshea0606 There is nothing to validate on your end since this is a tech debt ticket. Thanks 😄

**Comment by mshea0606** [comment]
@sanlouise thanks!
