### ISSUE TITLE
SOCKS access for David Formanek

### ISSUE THREAD

**Issue by oddballdave** [department-of-veterans-affairs/va.gov-team#95504]
### Your Name

David Formanek

### Your Email

dave.formanek@oddball.io

### Your GitHub Handle

oddballdave

### Your Role and Team

Senior Software Engineer on Mobile Feature Support

### Product Manager (PM) name and email

Jennifer Brown <jennifer.brown@oddball.io>

### Product Owner (PO) name and email

Jeff Barnes <jeffrey.barnes4@va.gov>

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKgmqGrwScBZdqdb2LSQlg9y6ujii7e/Nf2SrikML/yd formanek@MacBook-Pro.local

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/1a434811-7e9c-4d8f-b8da-b626ca5b0392)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by ph-One** [comment]
SOCKS access granted.
