### ISSUE TITLE
Contact Center Review for Benefits Decision Review - Higher-Level Review 2024 Updates

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#95514]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Higher-Level Review
We've made updates to the existing Higher-Level Review form on VA.gov. Higher-Level Review is a form for one of the three decision review pathways. Veterans can use this form to request VA to review their claim for errors.
Updates are mostly to match the new language used in the paper form. We also included email notification for form failures.

### Launch Date
Ready to launch. Date TBD

### Version Number
Aug/Oct 2024

### Product Guide
https://dvagov.sharepoint.com/:w:/s/vaabdvro/EXIUQdCuoNpOj1VR-ITUG8sB7rTyHt2v7UX2jG8RzaPeug?e=DQNkLT

### Product Video
https://youtu.be/I1cPmohLmbk

### Product Video Transcript
https://dvagov.sharepoint.com/:w:/s/vaabdvro/EYeI4KfxqPRGoZt8uYThwQUB_V-XhqZ7AthoJSLdm6W7cA?e=PfQTEv

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Draft looks good. Sent to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. The working copy is attached for future revisions/updates. Thank you!

[Higher Level Review Product Guide v2 SRT 10212024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzl4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d1018bd761ea5ab29f5d0263dfd04735f530260/Higher%20Level%20Review%20Product%20Guide%20v2%20SRT%2010212024.docx)
