### ISSUE TITLE
Update Datadog board to show descriptive error logs and latency data

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#95531]
Copy the "UploadsController#submit Errors" section from [Simple Forms dashboard](https://vagov.ddog-gov.com/dashboard/a9w-jhk-den/simple-forms-api?fromUser=false&refresh_mode=sliding&from_ts=1729455020101&to_ts=1729541420101&live=true) and adapt it to our needs.
<img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37d6dd0deeb345c490cdd8621a00e75d151b120d/image.png" alt="image.png" />

**Comment by michaelclement** [comment]
For this, we'll want to take advantage of [this new vets-api ZSF logging monitor class](https://github.com/department-of-veterans-affairs/vets-api/pull/19078) that was added recently by another team. 
We should be able to replace our existing logging using this interface, which will standardize the messages we see + give us more information.

We can create our own subclass of `::ZeroSilentFailures::Monitor` and start replacing the inner workings of our current tracking functions across the various models (e.g., `track_user_identity`, `track_current_user_loa`, etc).

**Comment by michaelclement** [comment]
Another note - it looks like our graph in DD is set up the same as Simple Forms' already. The issue is that when they receive an error, they throw an instance of `SimpleFormsApi::Exceptions::ScrubbedUploadsSubmitError`, which has a `message` member (which is what's supposed to be displayed in that `@ERROR.MESSAGE` column. So that's something we'll need to either adapt or replace

**Comment by cloudmagic80** [comment]
department-of-veterans-affairs/vets-api#19370
department-of-veterans-affairs/vets-api#19253

**Comment by cloudmagic80** [comment]
This

**Comment by cloudmagic80** [comment]
Completion of this ticket is dependent on completing this ticket:
https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/97121

Is this because both tickets conflict with using the flipper flag on the uploads controller
