### ISSUE TITLE
Update details page title tags based on CC feedback

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#95539]
## Description

Based on collab cycle feedback (see #91563 for a *lot* of context) we're updating our browser tab titles to:
- Remove PHI/PII - namely type of care
- Make them consistent with design standards - namely using Initial Caps Case. See (title tag guidance in the design system)[https://design.va.gov/content-style-guide/title-tags]. 

Here are the general patterns for appointment browser titles. These are detailed under the requirements:

- Appointments: `Status` `Modality` Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs
- VA Requests: `Status` Request For Appointment | Veterans Affairs
- CC Requests: `Status` Request For Community Care Appointment | Veterans Affairs

---

### VA Requests

- [x] Given a user is on a `confirmed` `VA request` details page
Then the browser tab title should read `Pending Request For Appointment | Veterans Affairs`

- [x] Given a user is on a `pending` `VA request` details page
Then the browser tab title should read `Pending Request For Appointment | Veterans Affairs`

- [x] Given a user is on a `canceled` `VA request` details page
Then the browser tab title should read `Canceled Request For Appointment | Veterans Affairs`

### Community care requests

- [x] Given a user is on a `confirmed` `cc request` details page
Then the browser tab title should read `Pending Request For Community Care Appointment | Veterans Affairs`

- [x] Given a user is on a `pending` `cc request` details page
Then the browser tab title should read `Pending Request For Community Care Appointment | Veterans Affairs`

- [x] Given a user is on a `canceled` `cc request` details page
Then the browser tab title should read `Canceled Request For Community Care Appointment | Veterans Affairs`

### In-person appointments (including COVID-19 Vaccine)

- [x] Given a user is on a `Confirmed` `In-person` details page
Then the browser tab title should read `Upcoming In-person Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Upcoming` `In-person` details page
Then the browser tab title should read `Upcoming In-person Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `In-person` details page
Then the browser tab title should read `Past In-person Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `In-person` details page
Then the browser tab title should read `Canceled In-person Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video appointments (including GFE)

- [x] Given a user is on a `Upcoming` `VA Video` details page
Then the browser tab title should read `Upcoming Video Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `VA Video` details page
Then the browser tab title should read `Past Video Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `VA Video` details page
Then the browser tab title should read `Canceled Video Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video at VA location appointments

- [x] Given a user is on a `Upcoming` `Video at a VA location` details page
Then the browser tab title should read `Upcoming Video Appointment At A VA location On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `Video at a VA location` details page
Then the browser tab title should read `Past Video Appointment At A VA location On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `Video at a VA location` details page
Then the browser tab title should read `Canceled Video Appointment At A VA location On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Video at an ATLAS location appointments

- [x] Given a user is on a `Upcoming` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Upcoming Video Appointment At An ATLAS Location On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Past Video Appointment At An ATLAS Location On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `Video appointment at an ATLAS location` details page
Then the browser tab title should read `Canceled Video Appointment At An ATLAS Location On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Phone appointments

- [x] Given a user is on a `upcoming` `phone appointment` details page
Then the browser tab title should read `Upcoming Phone Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `past` `phone appointment` details page
Then the browser tab title should read `Past Phone Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `canceled` `phone appointment` details page
Then the browser tab title should read `Canceled Phone Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Community care appointments

- [x] Given a user is on a `upcoming` `community care appointment` details page
Then the browser tab title should read `Upcoming Community Care Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `past` `community care appointment` details page
Then the browser tab title should read `Past Community Care Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `canceled` `community care appointment` details page
Then the browser tab title should read `Canceled Community Care Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Claim exam appointments

- [x] Given a user is on a `Upcoming` `Claim exam` details page
Then the browser tab title should read `Upcoming Claim Exam Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Past` `Claim exam` details page
Then the browser tab title should read `Past Claim Exam Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given a user is on a `Canceled` `Claim exam` details page
Then the browser tab title should read `Canceled Claim Exam Appointment On [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`
### Design Assets
N/A

### Developer Reference
N/A

## Definition of Done
- [x] All tasks criteria are met

**Comment by outerpress** [comment]
@JRRoof @Bren22va this ticket addresses feedback in Collab Cycle ticket #91563 . Usually I assign these to @ldelacosta for next steps. I'm not sure what Feature this belongs under - let me know if you need any more info/have questions.

**Comment by ldelacosta** [comment]
Added this to our 10/22 agenda for the review. @outerpress @JRRoof @Bren22va

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/95539?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by outerpress** [comment]
@jenniemc I found most of them on staging, will need to connect with you to test the rest (unchecked) on your local environment

**Comment by outerpress** [comment]
@jenniemc this one is validated, thanks for the help!
