### ISSUE TITLE
Please update list of prohibited characters in Git file names

### ISSUE THREAD

**Issue by JonathanKamensDVA** [department-of-veterans-affairs/va.gov-team#95548]
### Description

I know this is my fault because I'm the one who suggested the list of prohibited characters we should document for git file names, but it turns out I missed a few. Can we add them to the documentation please?

### Relevant URLs

Page to update: https://depo-platform-documentation.scrollhelp.site/getting-started/adding-files-to-the-github-repository
Reference list of all prohibited characters: https://stackoverflow.com/a/31976060 

### Which type of team are you on? (Platform team, VFS team, or Leadership)

Leadership

**Comment by jknipes** [comment]
Hi @JonathanKamensDVA , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@JonathanKamensDVA in order to create a work ticket for this edit, we need to parse out just the info that will be added to the Platform website page.

Would you be able to put that into a comment here or perhaps attach a document with the info?

**Comment by JonathanKamensDVA** [comment]
Right now the platform docs page says to _avoid question marks, colons, and pipe symbols;_ to avoid file names ending with a space or period or starting with a space; and to avoid long file paths because of the 256-character file path limit on Windows.

The information shown in italics in the previous paragraph is what needs to be updated. The list of characters to avoid needs to be expanded. It should include: forward and back slashes (/, \\), less and greater than signs (<, >), colons (:), double quotes ("), pipe symbols (|), question marks (?), and asterisks (*).

**Comment by jknipes** [comment]
work completed in [96753](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?pane=issue&itemId=86437534&issue=department-of-veterans-affairs%7Cva.gov-team%7C96753). Closing this ticket as _Done_
