### ISSUE TITLE
New VFS Team [Mobile Feature Support]

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#95564]
## Welcome and Introduction
We are excited to welcome your team to VA.gov. As a new VFS team, this template should be completed by your teams Product Owner and/or Product Manager.

## User Stories
As the leader of a new VFS team, I need to share basic info about my team with Platform so that Platform teams can have knowledge of my team for future collaboration.

As the leader of a new VFS team, I need to ensure my team follows the instructions for new VFS team members so that they're aware of Platform policies and processes, and Platform is aware of who supports my team for future collaboration.

As the leader of a new VFS team, I need to ensure my teams product information is correct so that Platform can have an accurate list of VA.gov products.

As the leader of a new VFS team, I need to complete ATO orientation so that VA.gov continues to be a secured and approved application within the VA.

## New Team Info
Add your team's practice and contact information below.

- **Team Name:**
- Mobile Feature Support

- **OCTO-DE Product Owner:**
Jeff Barnes

- **VA Business Owner:**
   - [x] OCTO (Office of the CTO)

- **Crew:**
   - [x] Core Veteran Experience

- **Github team name:**
Mobile Feature Support

- **Github team label:**
Mobile-feature-support

- **Team launch date:**
9/23/2024

- **Public slack channel:**
mobile-feature-support-public

- **Other team names:**

- [x] This information has been added.

## ToT (Team of Teams)
- [x] Contact `@Julia Badillo` or `@Erica Robbins [GovCIO_VetsPS]` on the #team-of-teams-slide-collection channel to receive an invite to the Team of Teams meeting and the Team of Teams Agenda and Protocol for reference

## Introduce your team on slack
- [x] Introduce your team on the #vfs-all-teams Slack channel. Include team name, Product Manager, Product Owner, what crew your team is on, and what products you're supporting on VA.gov.

## Platform Orientation for your team members
In addition to providing information to Platform and completing necessary tasks at the team level, there are also tasks that need to be completed at the individual level. As a team leader, you will need to:
- [x] Direct your team members to the guidance for [New VFS team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html#Guidancefornewteamsandteammembers-NewVFSTeammembers) on Platform Website
- [x] Ask all of your team members to complete the process

## Review and update your team's product information
- [x] Go to the [VA Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
- [x] Navigate to and select your team's product
- [x] Review to make sure that all of your team's products are listed and assigned correctly
- [x] If an edit to your team's product page needs to be made, see the [user guide](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide)

## ATO (Authorization to Operate) orientation
- [x] Post in the #platform-security Slack channel to request and schedule an ATO team orientation
- [x] Confirm that the orientation has been completed

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack).
- [x] New VFS Team has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)

**Comment by bdech** [comment]
New VFS Team has been added to the Team Roster in Atlas

**Comment by jennb33** [comment]
We have been added to the ToT meeting (effective 10/22/2024) and the template is here. It has also been saved to the Team Google drive. [Team of Teams - Team Slide Template and Protocol - OCT 2024.pptx](https://github.com/user-attachments/files/17478101/Team.of.Teams.-.Team.Slide.Template.and.Protocol.-.OCT.2024.pptx)

**Comment by jennb33** [comment]
Re: Product Information, need to confirm OCTO Crew, and determine which link(s) should populate Product Link and Product Outline
@Eallan919 or @oddballpete any ideas for these links?

**Comment by jennb33** [comment]
Requested ATO Orientation from Platform Security 10/22/2024 in [Slack](https://dsva.slack.com/archives/C01CJV0L9PS/p1729621851400149)

**Comment by jennb33** [comment]
This ticket is complete, save for the Security training that is to be scheduled and held either the week of 11/4 or 11/11. Please close ticket, @Eallan919 or support. Thank you.
