### ISSUE TITLE
400 Error in F1 submission: no such file or directory @ rb_sysopen solution

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#95561]
During the deployment of F1, around 3% of the time, we get this error "no such file or directory @ rb_sysopen" which is a 400 error. This error is caused by missing files stored under the vets-api tmp folder. To resolve this problem, we will recreate the user's pdf and json submission if the files are missing so that the S3 bucket can pick up the files. The resubmitted pdf and json will have same user's attributes except the UUID. 

### Acceptance criteria: 
- Transmission of forms to s3 does not fail silently when there is a problem
- Errors will be reported appropriately when they arise because of an issue unrelated to this one
- Errors are displayed to the user when the retry is unsuccessful
- Errors are not displayed to the user when their submit has recovered with a successful retry
- Make sure the Pega S3 bucket receives the PDF and Metadata JSON files when the user submits the F1 form.

### Implementation details

- There will only be 1 retry attempt. 
- The Retry is trigger only if 'No such file or directory @ rb_sysopen' is logged in the status.
- If the Retry is unsuccessful, we will still get the 400 error 'No such file or directory @ rb_sysopen' , the applicant will see an error message in the UI and the pdf will not be created. There will be no Pega process triggered. We will get a "missing pega status" in datadog.
- If the Retry is successful, the applicant will see a successful message. Pega will process the pdf. In the backend, we will get 2 processes. The 1st process will show that there was a "missing pega status" and the 2nd attempt will show a completed pega status. They will have 2 Unique IDs

**Comment by pshahVA** [comment]
Hey, I usually don't comment on engineering details, but since @acrollet is out and as part of my silent failure work, I wanted to know if this retry would still be done while the UX is waiting for a response.

**Comment by cloudmagic80** [comment]
@pshahVA The applicant will see a completed application message if the retry is successful. If the retry doesn't work, then they will see an unsuccessful message. The retry only happens once and no further retries occur, regardless of the outcome of the second attempt.

**Comment by baltes** [comment]
Moving this to the backlog for more refinement. Let's hit pause on fixes until we can articulate the approach and define our outcomes.

**Comment by pshahVA** [comment]
Thank you for the clarification @cloudmagic80

**Comment by cloudmagic80** [comment]
@baltes  @andrea-merrill @pshahVA  I've updated the implementation details in the ticket description. Thanks

**Comment by cloudmagic80** [comment]
Tested in Staging with flipper on. Good good!<img width="1596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzY1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1865567ce57993144eb4813731bc1ebb88e770d4/Screenshot%202024-11-13%20at%201.27.25%E2%80%AFPM.png" alt="Screenshot 2024-11-13 at 1.27.25 PM.png" />
