### ISSUE TITLE
[0781 PS] Spike - discovery and solutioning

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#95562]
The purpose of this ticket is to allow the engineer(s) time for discovery and solutioning on the 0781 Paper Sync product. 

- Meetings for design spec walk-throughs
- Meetings for story mapping and refinement
- Solutioning the approach for the following: 
  - MVP for only new claims (post submission) while keeping the existing flow and data in production until no longer needed
  - New PDF of the 0781 while keeping the existing PDF in production until no longer needed
  - Canary rollout 
  - Any monitoring or tracking user actions for future UX analytics 
- Test approach for testing in staging (the plan is to test often, so we just want to talk about what that might look like) 

The goal is to have a technical approach to delivering the 0781 paper sync feature for an MVP that will support future enhancements for the next phase of the project (claims in progress). It is not expected that the entire approach and planning of the stories will be completed, only that next two sprints of work is planned and eventually refined. Understanding the big picture should help us make the right decisions early on vs. having to redo work at the end. 

Technical approach 
- [ ] JSON file ticket
- [ ] New separate PDF
- [ ] The 526 progress bar - does it automatically update when pages are moved, what about when a page is added, how do we start a new section? 

[Design Spec](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9250-77233&t=faPDaJXJqj4NzfAi-4)
[0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
[Story mapping board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)

**Comment by rubensun** [comment]
Conducted initial kickoff!

**Comment by lisacapaccioli** [comment]
Meeting recording:  [0781 Paper Sync - design walkthrough 10/25/24](https://coformaco.zoom.us/rec/share/A1-Lj41g9sNlw3dHN4y9AIbmikteoRI0cgO-JYCVGZP420lhggIKCp8QrwW8zvNY.Ukvh-7Yq3UL0STWw 
Passcode: Dbex2-carbs)

**Comment by lisacapaccioli** [comment]
@freeheeling I added a couple of things that came up in our last working session for you to check into as well. We can talk more about them later.

**Comment by freeheeling** [comment]
### Pertinent Files 
**vets-api**
- [app/models/form_profiles/va_526ez.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va_526ez.rb)
- [config/form_profile_mappings/21-526EZ.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/form_profile_mappings/21-526EZ.yml)
- [config/features.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml)

- [lib/pdf_fill/forms/va210781.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/va210781.rb)
- [lib/pdf_fill/forms/va210781a.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/va210781a.rb)

**vets-website** 
- [src/applications/disability-benefits/all-claims/config/781/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/config/781/index.js)

**vets-json-schema**
- [21-526EZ-ALLCLAIMS-schema.json](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json)

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
