### ISSUE TITLE
VAOS + FHIR - Update Appointment Resource

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#9558]

**Comment by saneshark** [comment]
Pending resource action being available on VSP.

**Comment by ajmagdub** [comment]
Code reviewed and merged into master. Per Brad Crosby, SQA's FHIR server POST/Update Appointment interaction has not yet been deployed and is still being worked on. The HAPI  public test FHIR server was used to create VCR Cassettes.
