### ISSUE TITLE
Discovery: Determine process for adding appointments in VISTA for test users

### ISSUE THREAD

**Issue by ayush-chak** [department-of-veterans-affairs/va.gov-team#95581]
We need to get access to the vista test instance in order to create appointments for our testing.

**Comment by liztownd** [comment]
Instructions for gaining access to VistA and adding test user appointments can be found on [this page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/test.data.md).

**Comment by ayush-chak** [comment]
Hi @mdewey - @liztownd has not heard back on how to add appointments to the database (she submitted that online form over three weeks ago), is there any chance you can follow up? Might be that they need someone from OCTO to weigh in. Thanks!

**Comment by ayush-chak** [comment]
Update: @liztownd has access but needs to determine how to add appointments (through @klawyer)

**Comment by ayush-chak** [comment]
Still trying to troubleshoot why appointments aren't appearing on VA.gov so we are in a slight holding pattern

**Comment by liztownd** [comment]
Follow the instructions on this page.
_However_ apparently the recommended clinics will not show up on VA.gov. So in the `Select clinic` step, if you type in `CHY TEST` and hit enter, it will pop up a few selections for you, choose one of those and you should be able to proceed with making an appointment, that will then show up in the appointments list on VA.gov.
