### ISSUE TITLE
[LH Doc Upload] Improve BDD production monitoring

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#95604]
After we have launched the BDD Instructions migration with the [basic production monitor](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91269), we need to add a few more features to consider it truly complete:

  - [x] Log both `submitted_claim_id` and the `Form526Submission` primary key id in the api providers, we are only doing the first one at the moment

 

- [x] Incorporate the polling metrics that were added in https://github.com/department-of-veterans-affairs/va.gov-team/issues/95603

**Comment by ajones446** [comment]
Unless something changes by the time we get to this task, the ZSF criteria can be removed. Github issue conversation from 10/23: https://github.com/department-of-veterans-affairs/va.gov-team/issues/91269#issuecomment-2433375331

**Comment by NB28VT** [comment]
@ajones446 @kylesoskin FYI I'm removing this item from the acceptance criteria for adding alert monitors to the [BDD release dashboard](https://vagov.ddog-gov.com/dashboard/tf7-mwz-42y/benefits---disability---526---upload-bdd-instructions-lighthouse-migration-produ?fromUser=false&refresh_mode=sliding&from_ts=1730378008165&to_ts=1730464408165&live=true) as @freeheeling 's work on the ZSF compliance would make creating and maintaining these monitors redundant. Agree?


"Add alert monitors and set them up to warn us in the correct Slack channel as was done in the [failure email dashboard](https://vagov.ddog-gov.com/dashboard/jpm-85h-fea/form-526-document-upload-tracking-production?fromUser=false&refresh_mode=sliding&from_ts=1727027343223&to_ts=1729619343223&live=true)."

Ditto for "For monitors, tag them “service:disability-application” ([DataDog standards slack 7/24](https://dsva.slack.com/archives/C04KW0B46N5/p1721841520391079) )"

**Comment by NB28VT** [comment]
PRed the first item here https://github.com/department-of-veterans-affairs/vets-api/pull/19217

**Comment by NB28VT** [comment]
Logging fixes for item 1 completed in https://github.com/department-of-veterans-affairs/vets-api/pull/19217

**Comment by NB28VT** [comment]
Although it's not quite the ideal way to represent the statistics, we are at least showing the polling gauge metics in [this dashboard](https://vagov.ddog-gov.com/dashboard/34u-stx-sk2/benefits-disability-lighthouse-doc-upload-migration-master-dashboard?fromUser=false&refresh_mode=sliding&from_ts=1730836313575&to_ts=1730922713575&live=true), which will suffice for the time being. So I'm going to close this ticket.
