### ISSUE TITLE
Add VA Form content type to CMS

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#9562]
**Acceptance Criteria**
- [ ] VA Form content type is available in CMS

**Implementation**
- [ ] Final review by CMS team
- [ ] Update content type to remove testing behavior
- [ ] PR submitted to CMS team

**Comment by beeyayjay** [comment]
- Created PR and reviewed with CMS team
- Updated PR based on review
  - Created pathauto
  - Improved listing page
 - Fixed display of migrated content on draft pages.

To-do:
- Finalize display of migrated content
- Have another help text review (help text guidelines have been updated since previous review)

**Comment by stephorkandatx** [comment]
Synced with @beeyayjay and we are moving the AC for listing page work to a new ticket. 
#9708 will be that ticket. I am updating the Acceptance Criteria of this ticket now

**Comment by MarciMcGuireGCIO** [comment]
Closing; per this comment https://github.com/department-of-veterans-affairs/va.gov-team/issues/9562#issuecomment-637586660, the acceptance criteria was moved to https://github.com/department-of-veterans-affairs/va.gov-team/issues/9708
