### ISSUE TITLE
Cleanup of saved_claims table

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#95626]
# Overview
Within the `saved_claims` table we used to use a field called `itf_datetime`
Product requested that we change to use a field called `form_start_date`

Instead of renaming the field, it looks like a new field was added which is confusing.   Unless there is some reason to keep this old field, we should copy all of the values from it to the new one and then delete it.

# Tasks
- [ ] - Copy all data from `itf_datetime` to `form_start_date`
- [ ] - Delete `itf_datetime`

**Comment by danlim715** [comment]
PR for data migration rake task is in review. Reminder to self to run the task once deployed to production. Once task is run in production, create follow-up PRs to remove the rake task and add the schema migration to finally be able to remove the `itf_datetime` field.

**Comment by danlim715** [comment]
Screenshot of results after successfully running in staging:

![Image](https://github.com/user-attachments/assets/4ad60341-cb37-48c0-a125-1787140a2430)

**Comment by danlim715** [comment]
Script successfully run in production
