### ISSUE TITLE
Documentation support - Create a new "External service integrations" page for Login.gov

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#95639]
### Request type

- [x] Writing new documentation
- [ ] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Subject matter expert

Megan Driscoll (Identity Content Designer), Joe Niquette (Identity Engineering Lead)

### Approvals

No

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [x] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other

### Anything else?

- [JIRA ticket about the origin of this work](https://jira.devops.va.gov/browse/VI-481)
- [Draft of content for new page](https://docs.google.com/document/d/1v1cTVnIcfw0HrVkumL5FRivHwrAKdle_BJDXYyuk2ZY/edit?usp=sharing), which has been reviewed by the Identity team

**Comment by jknipes** [comment]
Hi @kdmeg-bluetiger,  thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
New page has been published, closing this issue as _done_
