### ISSUE TITLE
Update ID.me content in platform documentation

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#95642]
### Description

The Identity team is updating the platform developer documentation for all of our Credential Service Providers (CSPs) to ensure it's consistent and accurate. I've drafted revisions to our existing page on ID.me in a Google doc which has been reviewed by the Identity team.

### Relevant URLs

- [JIRA ticket with a summary of this work](https://jira.devops.va.gov/browse/VI-481)
- [Existing page](https://depo-platform-documentation.scrollhelp.site/developer-docs/id-me)
- [Link to Google doc with draft revisions](https://docs.google.com/document/d/1_lKH8EpW9BP9cttD5ckgjvZKU1bCnE1nQgCR06u9K5E/edit?usp=sharing)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Identity Experience/Identity Platform

**Comment by jknipes** [comment]
work is completed, closing as _done_
