### ISSUE TITLE
PDF_Filler temp files need to be unique

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#95644]
"Due to the growing number of 7959F1 files, our temporary files with the same name can cause conflicts. This could lead to issues if two users try to save a file with the same 7959F1 name simultaneously."
If the files are named correctly, we won't see this error:` Error: An error occurred while verifying stamp: No such file or directory @ rb_file_s_rename `  which is caused by conflicting naming, e.g.  tmp/vha_10_7959f_1-stamped.pdf or tmp/vha_10_7959f_1.pdf

Old AC: Each application 7959F1 file unique name, like use a SecureRandom.hex. example:
      generated_form_path = Rails.root.join("tmp/#{name}-#{SecureRandom.hex}-tmp.pdf").to_s
      stamped_template_path = Rails.root.join("tmp/#{name}-#{SecureRandom.hex}-stamped.pdf").to_s

New AC: 
All temporary files must be uniquely named. 
Need unit test to ensure that the output file for s3 is named correctly:
It should not be this format:` tmp/vha_10_7959f_1-cf1b6e07204447096d9bf37837c61df7.pdf`
or this` tmp/vha_10_7959f_1-stamped.pdf `or` tmp/vha_10_7959f_1.pdf`
Correct format is:  tmp/0099687f-7e9c-45a9-8865-ac67f0d7ef31_vha_10_7959f_1.pdf for PEGA to process the claims

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/19060/files

**Comment by cloudmagic80** [comment]
Reverting the PR.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/19118

**Comment by cloudmagic80** [comment]
This new PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19143/files
supersedes the other PRs that came before this one

**Comment by cloudmagic80** [comment]
LGTM @stevelong00

**Comment by stevelong00** [comment]
The PR has all needed approvals and is ready to merge.  @baltes, shall I proceed with the merge?

**Comment by baltes** [comment]
If it's behind a feature flag, we can merge. If not, we probably need testing steps to verify it in staging before it goes to prod.

**Comment by stevelong00** [comment]
@baltes It's behind a feature flag and currently disabled in all environments.  Merging now.

**Comment by cloudmagic80** [comment]
@baltes  This looks good in staging.
<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVM1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--972c9aaf0499e04db8706536af58e7df15c2f070/Screenshot%202024-11-13%20at%201.44.57%E2%80%AFPM.png" alt="Screenshot 2024-11-13 at 1.44.57 PM.png" />
