### ISSUE TITLE
Update DS Logon content in platform documentation

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#95645]
### Description

The Identity team is updating the platform developer documentation for all of our Credential Service Providers (CSPs) to ensure it's consistent and accurate. I've drafted revisions to our existing page on DS Logon in a Google doc which has been reviewed by the Identity team.

### Relevant URLs

- [JIRA ticket with a summary of this work](https://jira.devops.va.gov/browse/VI-481)
- [Existing page](https://depo-platform-documentation.scrollhelp.site/developer-docs/ds-logon)
- [Link to Google doc with draft revisions](https://docs.google.com/document/d/1vdFCLNCnrSvggrRxJcYePrA6C9eM3Ua2JI3Ji6IdqZU/edit?usp=sharing)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Identity Experience/Identity Platform

**Comment by jknipes** [comment]
Hi @kdmeg-bluetiger, thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
work is completed, closing this request
