### ISSUE TITLE
[CAIA Intake] Benefits Management Tools Team 2: Payment History alert

### ISSUE THREAD

**Issue by jstrothman** [department-of-veterans-affairs/va.gov-team#95656]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.

## Your team

- **Product name:** Payment History
- **Team name**: Benefits Management Tools Team 2
- **OCTO product owner:** @amylai-va 
- **Product manager:** @salihaghaffar 
- **Designer(s):** @sh0wn @rallencf 
- **Slack channel:** #benefits-management-tools or #benefits-cross-benefits-design
- **Dedicated content writer on your team (if you have one):** @rallencf (Note: Rick has been out of office, so @jstrothman drafted this content. Rick returns tomorrow.)
- **Dedicated a11y specialist on your team (if you have one):** @1Copenut 

## CAIA specialists involved
_Filled out by CAIA_
- **IA:** 
- **Content:** 
- **Accessibility:** 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  

### What's the nature of your initiative and desired outcomes?
The Contact Center has been receiving increased calls related to payments Veterans never received. This is a result of an education payment migration in August that resulted in 3rd party payments displaying to the Veteran as if the payment was made directly to them. There are also other education payments that are miscategorized as “C&P Hardship” instead of “Education Payment” While we investigate fixing these errors, the Contact Center and VBA would like us to display a warning about the potential problem. Unfortunately, we can’t confidently only show the warning to people who will see the problem. 

Related GH issue: #95240 

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content. FOR FIGMA/MURAL: please tell us which screens/board/section to look at so we don't leave comments on old stuff. 
- [Figma file: Payment History](https://www.figma.com/design/AMsEAbhbHtrahQTp6GzVkQ/Payment-History?node-id=2207-2710&t=RvOtpYigm4YAsMDF-4) - The link goes to the proposed screen, `Payment history -- issue alert` on the page `WIP - Payment history issue alert`

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We are waiting to hear back from the BEP Services Team 2 with an example of what people are seeing so that we can be sure the warning info relates to what the interface says. We hope to hear back this week.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- **Hyperlinked Ticket Number:** 

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
- [ ] Please don't close this intake when work is complete - CAIA will close and track

**Comment by kristinoletmuskat** [comment]
Just noting there is no IA work on this one.

**Comment by jstrothman** [comment]
@NaomiPMC @strelichl Would it be possible to get a timing estimate for a content writer to work on this request? No complaint or pressure intended! I have an estimated timeline request from the Call Center and the info would help me reply. TYIA!

**Comment by aprocik1** [comment]
@jstrothman, Beth and I reviewed this together.

Here's our recommendation:

> [Header] We're working to improve what we display here 
> 
> If you receive education benefits, we'll be removing information about payments we send directly to your school. After we've made this update, the list will include only the payments you receive.
> 
> We're also aware that our system displays some education benefit payments as "C&P Hardship." We're working to fix this.

And here are two follow up questions for you:
- We've replaced "Post-9/11 GI Bill (Chapter 33) benefits" with "education benefits" to make this content more concise. Do you think we need to specify PGIB benefits in the alert?
- How does “C&P Hardship” display on this screen? We want to match this text exactly in the alert.

**Comment by rallencf** [comment]
@aprocik1 Hi! Thanks so much for the recommended copy. I chatted with @jstrothman about your follow-up questions:

- "Education benefits" is fine
- We don't know exactly how “C&P Hardship” is displayed. Julie is waiting to get a screenshot to clarify, but we don't want to delay publishing this alert. What do you think about saying, "...'C&P Hardship' or something similar" as a short-term option?

**Comment by rallencf** [comment]
To get this alert message up quickly, we're going to use the following wording:

> [Header] We're working to improve what we display here If you receive education benefits, we'll be removing information about payments we send directly to your school. After we've made this update, this page will only include payments sent to you.

Some education benefit payments may appear as "C&P Hardship" or something similar. We're working to fix this.

**Comment by rallencf** [comment]
@aprocik1 Hello! To get this alert message up quickly, we're going to use the following wording:

> [Header] We're working to improve what we display here 
> 
> If you receive education benefits, we'll be removing information about payments we send directly to your school. After making this update, your list of payments will only include payments sent to you.
> 
> Some education benefit payments may appear as "C&P Hardship" or something similar. We're working to fix this.

We can incorporate any additional feedback you may have in the next update update. Thanks again for your help!

cc/ @jstrothman

**Comment by aprocik1** [comment]
@rallencf, I'm sorry for missing your previous message. I think your edits work--thanks for moving this forward.

Can we close this intake ticket? If you'd like us to return to this after you determine the "C&P Hardship" content, we can reopen it.

**Comment by rallencf** [comment]
@aprocik1 No worries. Yes, closing the ticket is fine. We'll check in when we learn more about the "C&P Hardship" content. Thanks!
