### ISSUE TITLE
Analytics Implementation or QA Support for Debt Resolution Portal - Referring traffic (URL) reporting

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#95669]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Debt Resolution

- **Poduct Name**

    - Debt Portal
      
- **When is the launch date?**
    - ASAP

- **Provide the link(s) for Product/Page urls**
  
    - https://va.gov/manage-va-debt
    - https://va.gov/manage-va-debt/summary/
    - https://va.gov/manage-va-debt/summary/copay-balances/
    - https://va.gov/manage-va-debt/summary/debt-balances/
    - https://va.gov/manage-va-debt/summary/debt-balances/details
    - https://va.gov/manage-va-debt/debt-balances/letters/
    - https://www.va.gov/manage-va-debt/summary/debt-balances/details/{selectedId}/](https://www.va.gov/manage-va-debt/summary/debt-balances/details/%7BselectedId%7D/)
    - https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/)
    - https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement/](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement/)
    - https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement)/
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/veteran-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/veteran-information)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/all-available-debts](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/all-available-debts)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/contact-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/contact-information)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/current-contact-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/current-contact-information)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mobile-phone](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mobile-phone)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-email-address](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-email-address)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mailing-address](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mailing-address)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/employment](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-question](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-question)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-work-dates](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-work-dates)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/gross-monthly-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/gross-monthly-income)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-history](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-history)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/income/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/income/:index)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/benefits)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/your-benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-benefits)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-benefits)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-income-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-income-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-income)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information)
   - [www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records)
   - [www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-work-dates](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-work-dates)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-history](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-history)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse/income/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse/income/:index)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefits)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefit-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefit-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-other-income-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-other-income-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-add-other-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-add-other-income)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-on-hand](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-on-hand)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-in-bank](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-in-bank)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-assets)
   - [www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-assets)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-asset-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-asset-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-assets)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-asset-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-asset-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicle-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicle-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/your-vehicle-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-vehicle-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicles](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicles)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicle-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicle-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-asset-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-asset-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-asset](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-asset)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/expenses-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/expenses-explainer)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/utilities](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utilities)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/add-utility-bill](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-utility-bill)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/repayments](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/repayments)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/repayment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/repayment-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/your-credit-card-bills](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-credit-card-bills)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/your-installment-contracts](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-installment-contracts)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-values)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-summary)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-expense](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-expense)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/option-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/option-explainer)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-option/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-option/:index)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comment/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comment/:index)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-waiver-agreement/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-waiver-agreement/:index)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comments](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comments)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-bankruptcy-history-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-bankruptcy-history-records)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit)
    - www.va.gov/manage-va-debt/request-debt-help-form-5655/confirmation](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/confirmation)

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - We are looking to track all incoming traffic to the portal be it internal or external sources including items such as a QR code that is printed on paper statements (QR code is [here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/84364)). I am not sure of the best format of the output report, we are looking for your help on how to have this data presented. I believe all the URL's are listed but didn't know if you just needed the root or every full destination.

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks @Tom-Davis -- our team will review this, and let you know what the best options will be here. We'll communicate further updates in this ticket. 

FYI @jestutt, @ChristineYoungZA, @Blivaditis

**Comment by jestutt** [comment]
Hi @Tom-Davis There are two parts to what you've asked for: 

1. Finding the sources in GA
2. Creating tracking links for external placement to reduce the unknown/better identify external sources

### Finding the sources in GA
_Before we start, this is a direction analysis and we won't always be dealing with real numbers._ 

When looking at external and internal traffic sources for a single or group of pages, you have to come at the information from a few angles in GA and manually combine them. I've created [Debt Resolution Sources [A&I]](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/Etpo5XE-T86EOpLn6wxDog) Explore report to get you start.

#### Tab 1 Total Views

> Total number of page views generated across all pages with URLs that start with www.va.gov/manage-va-debt

#### Tab 2 Internal Sources

> Page view count for all www.va.gov sources
> 
> - based on `Page referrer`, where the user's browser says they were immediate before viewing pages with URLs that start with www.va.gov/manage-va-debt
> - excludes any referral traffic from the same section (sometimes called self referrals)
> - excludes any referral traffic from auth login pages 
> -- to finish the login process on a page, the users has to have started the process on the same page which means it's a self referral

#### Tab 3 External Sources

> Page view count for all non-www.va.gov sources
> 
> - also based on `Page referrer`, where the user's browser says they were immediate before viewing pages with URLs that start with www.va.gov/manage-va-debt
> - `Session default channel group` is a high-level grouping system for external sources based on a number of values, mostly including `Page referrer` and UTM tracking URLs
> - `Session source / medium` provide the more specific source information like which search was used or which site they came from

#### Tab 4 Link Clicks

> Event count for all tracked link clicks on www.va.gov to a /manage-va-debt destination link
> 
> - you can add other metrics to find placement information if needed
> - excludes any events that happen on pages with URLs that start with www.va.gov/manage-va-debt

### Creating tracking links for external placement

On Tab 3, you'll see that the Direct, or (direct) / (none), makes up more than 40% of the traffic sources. In these cases, direct = unknown and generally come from a non-HTML source like a bookmark, link typed into the browser, link click from an email or document, etc. To help reduce these unknowns in GA and provide better information on any external link placement we can control, we can add UTMs to our URLs to make them trackable.

Google provides a tool to assist in generating these trackable -- https://ga-dev-tools.google/campaign-url-builder/

![Image](https://github.com/user-attachments/assets/2ffcf3f5-a303-4d76-bfd0-f4c3b89481a9)

You must complete the fields with an asterisk (*) when creating these URLs or risk incomplete information in GA. 

- website URL -- the URL to the page you want to create a trackable link to
- campaign source -- think website or platform like facebook, qr code, bit.ly
- campaign medium -- think media like social, offline, email
- campaign name -- keep it simple but understandable/identifiable to others; will be consistent across all the project/campaign links

There is one optional field I recommend using if you need to differentiate placements like the type of letter a qr code is in or the pictures used in a social post.

- campaign content -- similar to name, keep it simple but it really depends on how you want to break down your reporting

**Tip:** I strongly recommend keeping a record of any tracking links you create somewhere. It will come in handy when you're ready to start reporting on any traffic these links have generated.

cc @johnny-jesensky-adhoc
