### ISSUE TITLE
Fix bug with page not focusing to the top when navigating through Appoint a Rep

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#95661]
## Background
When you use the 'continue' or 'back' buttons to navigate through the Appoint a Rep form, the next page doesn't automatically scroll to the top. As a result, you often have to manually scroll up to view the content of the new page.

Fix this :-)

## Steps to Reproduce
1. Head to the intro page of Appoint a Representative https://staging.va.gov/get-help-from-accredited-representative/appoint-rep
2. Click on the "Start your form without signing in" link at the bottom of the page
3. Page advances to the first screen on the Appoint experience, but you're viewing the footer

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/33555/files

**Comment by holdenhinkle** [comment]
I need to test the confirmation and next-steps pages in staging (I couldn't test them locally).

**Comment by mtri** [comment]
This seems like an okay solution! Looks good on desktop and mobile.
