### ISSUE TITLE
Investigate PG Query Duration Spikes for VBA job

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#95678]
## Description:
As part of the actionable alerts investigation, we identified query duration spikes in Postgres during the 2:30-4:00 AM ET window ([insert link to slack conversation here](https://dsva.slack.com/archives/CKUCFQAHJ/p1729171745329239)) via our [Datadog monitor](https://vagov.ddog-gov.com/monitors/199084). The Appeals team owns the related job. We discovered PG query statement timeouts in the logs, but after investigating theories around locking (autovacuum or DB cleanup tasks, etc), this does not appear to be the cause. RDS logs also don’t reveal issues, and the jobs run fine throughout the day. Adjustments were made to job intervals ([link to PRs](https://github.com/department-of-veterans-affairs/vets-api/pull/18982)). We need to work closely with the Appeals team and monitor the situation closely.

Acceptance Criteria:
- [x] Investigate further potential causes of query spikes beyond locking.
- [x]  Coordinate with the Appeals team to understand job behavior.
- [x]  Monitor Postgres query durations between 2:30-4:00 AM ET to track changes.
- [x]  Ensure any job adjustments are documented and tracked.

**Comment by LindseySaari** [comment]
The PG Query duration spiked yet again last night. After some investigation around job run times, here are some findings.

## VBA job runtime notes
`VBADocuments::UploadScanner` - Every 3 minutes
`VBADocuments::UploadRemover` - Every 5 minutes

## Other jobs that run in that window
`EVSS::DeleteOldClaims` – 2:00 AM
`DeleteOldPiiLogsJob` – 2:20 AM
`VBADocuments::UploadScanner` – Every 3 minutes
`VBADocuments::UploadRemover` – Every 5 minutes
`DecisionReview::FailureNotificationEmailJob` – 1:05 AM
`Form526StatusPollingJob` – 3:00 AM
`DeleteOldTransactionsJob` – 3:00 AM
`Representatives::QueueUpdates` – 3:00 AM

## Jobs with Error Logs
- `VBADocuments::UploadRemover` - [logs from last night](https://vagov.ddog-gov.com/logs?query=%22VBADocuments%3A%3AUploadRemover%22%20status%3Aerror%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1729745886661&to_ts=1729759483474&live=false)
- `DeleteOldPiiLogsJob` - DeleteOldPiiLogsJob - logs here from [last night](https://vagov.ddog-gov.com/logs?query=DeleteOldPiiLogsJob%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1729690292434&to_ts=1729776692434&live=true) from 2-4:00am error window
None of the other jobs (only DeleteOldPiiLogsJob) have error logs

**Comment by flooose** [comment]
We have access to the [pg_stat_statements](https://www.postgresql.org/docs/current/pgstatstatements.html) module, which allows us to query queries that last particularly long
```
conn = ActiveRecord::Base.connection
res = conn.execute("SELECT query,  blk_read_time + blk_write_time AS io_time  FROM pg_stat_statements  ORDER BY blk_read_time + blk_write_time DESC  LIMIT 20;")
```
or require high amounts of IO
```
res = conn.execute("SELECT query,  shared_blks_dirtied + shared_blks_written AS blocks_written  FROM pg_stat_statements  ORDER BY shared_blks_dirtied + shared_blks_written DESC  LIMIT 20;")
```

**Comment by jwoodman5** [comment]
PR is up.

**Comment by LindseySaari** [comment]
[The PR for the query change](https://github.com/department-of-veterans-affairs/vets-api/pull/19199) has been deployed. Now we wait for the morning run at 5:10am

**Comment by LindseySaari** [comment]
Closing in favor of [this ticket for next sprint](https://github.com/orgs/department-of-veterans-affairs/projects/1335/views/1?filterQuery=assignee%3ALindseySaari&pane=issue&itemId=85926689&issue=department-of-veterans-affairs%7Cva.gov-team%7C96409)
