### ISSUE TITLE
Flipper UI access for [individual]

### ISSUE THREAD

**Issue by NitheeshaKarnati** [department-of-veterans-affairs/va.gov-team#95687]
### Your Name

Nitheesha Karnati

### Your GitHub handle (Flipper UI access is managed through GitHub)

NitheeshaKarnati

### Team, Role, and Company of the target individual

Team Virtual Agent Chatbot, QA Lead, Thoughtworks

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by davidpetras** [comment]
@NitheeshaKarnati you have been provided access to the `lesser env` within Flipper UI.
