### ISSUE TITLE
[Bug] MDT - Intro, Ch1p1, Ch1p2 - Copy mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9568]
## What happened?
On Staging **[Order hearing aid batteries and accessories](https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction)** form \[Intro, Veteran Information (Ch1p1, Ch1p2) pages], some copy items did not match corresponding design prototypes.

## Specs:
- Browser-/device-agnostic
- `test.gov.user+1@gmail.com`

## Steps to Reproduce
1.  Go to https://staging.va.gov/ .
1.  Sign-in via **ID.me** as **`test.gov.user+1@gmail.com`** (Greg).
1.  Go to https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction .
1.  IF **Your form is in progress** alert is displayed, click **Start a new application** button, then click **Back** button.
1.  Observe copy mismatches on **Intro** page \[see screenshot below].
1.  Click **Order...** button.
1.  Observe copy mismatches on **Veteran Information (Ch1p1)** page \[see screenshot below].
1.  Click **Continue** button.
1.  Observe copy mismatches on **Veteran Information (Ch1p2)** page \[see screenshot below].

**Intro**
![mdt-form-intro](https://user-images.githubusercontent.com/587583/83294889-f0814900-a1a2-11ea-8ea5-7f7c2200b24b.png)

**Ch1p1**
![mdt-c1p1](https://user-images.githubusercontent.com/587583/83294974-173f7f80-a1a3-11ea-8eba-65cae4644f8b.png)

**Ch1p2**
![mdt-c1p2](https://user-images.githubusercontent.com/587583/83463924-3a2c9680-a424-11ea-92e7-0e548bc16ff1.png)

## Desired copy

**[Intro](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/403219934) prototype**
![mdt-design-intro](https://user-images.githubusercontent.com/587583/83465082-a230ac00-a427-11ea-9464-9d6cb7fe7b76.png)

**[Ch1p1](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407912464) prototype**
<img width="695" alt="mdt-design-ch1p1,png" src="https://user-images.githubusercontent.com/587583/83465389-9e515980-a428-11ea-9485-cb87ad13bf58.png">

**[Ch1p2](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407910003) prototype**
<img width="673" alt="mdt-design-ch1p2" src="https://user-images.githubusercontent.com/587583/83465533-191a7480-a429-11ea-8576-787248e53175.png">

## Acceptance Criteria
\[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mr0sari0** [comment]
I don't think our team has received information about a respondent burden or a privacy act.

**Comment by leahkeeler** [comment]
@mr0sari0 The DLC confirmed they do not have respondent burden and Matt confirmed we do not need it

**Comment by mr0sari0** [comment]
Here's an updated pic of the intro page:

![screenshot-localhost_3001-2020 07 06-13_34_01](https://user-images.githubusercontent.com/12755283/86622175-760bcc00-bf8d-11ea-95ed-ba1ef3689b64.png)

**Comment by mr0sari0** [comment]
I think this is safe to close unless there are other outstanding issues.
