### ISSUE TITLE
HIGH: Denial of service in http-proxy-middleware

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#95697]
## Issue Description
Resolve the dependabot alert --

https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/187

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
PR here -- https://github.com/department-of-veterans-affairs/vets-website/pull/32841

**Comment by IGallupSoCo** [comment]
Peter had the PR up, with all checks passing.  We have an approval from Ray Messina, so I completed the merge and am closing this as completed.
