### ISSUE TITLE
Read Code of Conduct

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#957]
Everyone please read the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md) document and comment "done" in the comment section.

**Comment by mojaray2k** [comment]
Done

**Comment by Samara-Strauss** [comment]
Done

**Comment by artistgreen** [comment]
Done

**Comment by lihanli** [comment]
done

**Comment by erikphansen** [comment]
done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by artistgreen** [comment]
Done
