### ISSUE TITLE
IA Ticket: Update education mega menu

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#95702]
### Description

We recently uncovered an underperforming link in the education mega menu that we would like to swap out for one that performs better.
![Image](https://github.com/user-attachments/assets/f11c7fed-ea9f-409b-b158-1e54ec453c92)

![Image](https://github.com/user-attachments/assets/b9e49198-9d00-4fd1-aa28-9a5108be8b0e)

Under 'manage your benefits', 
Remove this: https://www.va.gov/education/change-gi-bill-benefits/
Replace it with this: https://www.va.gov/education/verify-school-enrollment/

This ticket came directly from Beth/Mikki in this thread: https://dsva.slack.com/archives/C03MP8MEPCN/p1729701510952069

### Timeline
ASAP

**Comment by scjwalker** [comment]
Confirming, this change is live
