### ISSUE TITLE
Design Intent - IA Feedback - Modernized Check-in, eCheck-in, Check in with MSAs after eCheck-in

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#95736]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through the collab cycle! Definitely some parts of this process that are typically opaque to us (the in-person interactions) so I look forward to following y'all's work and research on this.
- I offered a little feedback on the text of the confirmation page "Let a staff member know..." header during our call. I reviewed your designs more thoroughly and am deciding not to include that feedback here.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Consider: show instructions to notify staff when user taps the sign-in link again** If someone taps the sign-in link from their text messages again after completing check in, consider showing "Let a staff member know..." language on the screen.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by benbrasso-agile6** [comment]
Thanks, Erin. 

@cgednalske i didn’t read through this yet. Placed for next sprint. Should be able to add a value into the Estimate field.

**Comment by zach-park** [comment]
@cgednalske , I'd like to recommend that we create a spike ticket to revisit it. Thank you!

**Comment by zach-park** [comment]
@cgednalske , here is the Figma link to the exploration when the user signs-in again with the SMS link. Thank you!

**Comment by zach-park** [comment]
@cgednalske @StevenStraily , 

I was able to confirm with Brian and John that this usecase is actually not possible. - The user will get the "We're sorry. This link has expired" error page instead. That being said, I'd like to propose that we close the ticket with no further action on the sign-in use case. 

However, please also note that I was able to identify (with @brianseek and @wullaski) a similar type of situation could happen when the user navigates back to this page from the confirmation page (from the same session). So we. may want to look into it if needed if that becomes a frequent use case.  

Thank you!

**Comment by cgednalske** [comment]
@zach-park that sounds good 👍  Nice work getting to the bottom of this! Agree we can keep an eye on the similar situation if it becomes an issue. I think you're good to close this out. 

cc @erinrwhite for awareness 👆

**Comment by zach-park** [comment]
Closed
