### ISSUE TITLE
Add retry logic for unit tests 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9574]
- Some of our unit tests intermittently fail 
- Add retry logic for unit tests 
- Add a todo to remove retry logic after app separation project

**Comment by rianfowler** [comment]
- Retry logic added to unit tests
- Monitor failures over the next week to determine if approach reduces flakey test failures

**Comment by meganhkelley** [comment]
Duplicate of #16941
