### ISSUE TITLE
HIGH: libxmljs2 vulnerable to type confusion when parsing specially crafted XML

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#95759]
## Issue Description
Resolve the high dependabot alert -- https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/164

---
## Tasks
- [ ] Update whatever packages are required to address the dependabot alert

## Acceptance Criteria
- [ ] Dependabot alert is resolved
---

**Comment by IGallupSoCo** [comment]
Duplicate of Dependabot alert 152
