### ISSUE TITLE
HIGH: Uncontrolled resource consumption in braces

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#95762]
## Issue Description
Resolve the high dependabot alert -- https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/152

---
## Tasks
- [x] _A package update to a recommended/latest version has been attempted._

## Acceptance Criteria
- [x] _Either the upgrade was successful, or failed due to dependency issues tied to vets-website's current node version._
---

**Comment by IGallupSoCo** [comment]
This is another package that's gated behind a node upgrade.
