### ISSUE TITLE
HIGH: libxmljs2 type confusion vulnerability when parsing specially crafted XML

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#95764]
## Issue Description
Resolve the high dependabot alert -- https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/152

---
## Tasks
- [x] _A package update to a recommended/latest version has been attempted._

## Acceptance Criteria
- [ ] _Either the upgrade was successful, or failed due to dependency issues tied to vets-website's current node version._
---

**Comment by IGallupSoCo** [comment]
Let's add this one to the node.js version pile.
