### ISSUE TITLE
Connect with CMS to determine viability of question set management in CMS

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9576]
Some thoughts on what customization might look like:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/51b97a7566a4f23cc819631026411bde24ccb359/products/health-care/COVID-screener/RFCs/customization-rfc.md#coivd-19-screener-customization-rfc

Also see this comment:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/9103#issuecomment-632107433

**Comment by DanielleThierryUSDSVA** [comment]
Hi @batemapf. I've submitted this issue ([#1865](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1865)) to the CMS team and requested a meeting for next week to discuss. Will follow up here once I hear back from Kevin. Thanks!

**Comment by batemapf** [comment]
Acceptance criteria for this is: meeting w/ Kevin W.

**Comment by DanielleThierryUSDSVA** [comment]
Connected again with Kevin today. He's reading over issue again and will reach out for meeting this week.

**Comment by DanielleThierryUSDSVA** [comment]
Connected. Closing issue for now.
