### ISSUE TITLE
Staging Review finding: Excessively complex sentences in content consideration -> "Directions for updating uneditable information"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95770]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Design System Staging Information
**Component:** Help users to... Know when their information is prefilled
**Staging Review ticket:** [AEDP, Design Patterns, Help users to... Know when their information is prefilled](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90181)

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not align with VA.gov voice and tone content principles.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-aligns-with-vagov-voice-and-tone-content-principles)
**VA.gov Experience Standard - category:** [Credibility](https://design.va.gov/about/experience-standards/#category-credibility)
**This is an issue with the:** 
**High-priority:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

The sentence "Directions for updating information that can’t be updated online within the form varies and should be updated based on the context of the form or application being used." is extremely long and does not follow guidelines for plain language standards. 

## Recommended action
Separate the sentence into several. I recommend: "Directions for updating information that can't be updated online vary. So directions should be updated based on the context of the form or application used." 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Plain language - Use short sentences](https://design.va.gov/content-style-guide/plain-language/use-short-sentences)
- **Context:** N/A

---

### Next Steps for DST

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Governance help validating the issue, please comment on the ticket
- If this ticket has a `high-priority` label, please address as soon as possible so VFS teams are not impacted
- If this ticket has a `consider` label, please consider for future implementation

**Comment by msbtterswrth** [comment]
Confirmed this is updated here: https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled.
