### ISSUE TITLE
Staging Review finding: Capitalization of various design principles is inconsistent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95774]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Design System Staging Information
**Component:** Help users to... Know when their information is prefilled
**Staging Review ticket:** [AEDP, Design Patterns, Help users to... Know when their information is prefilled](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90181)

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not meet best practices.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-meets-best-practices)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**This is an issue with the:** 
**High-priority:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

In the design principles section, the copy references both "visibility of system status" and "user control and freedom", but the way these terms are capitalized is inconsistent. 

## Recommended action
Based on other pages in the design system, only the first word should be capitalized, but I would also consider editing this copy to align with the language used in https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Capitalization](https://design.va.gov/content-style-guide/capitalization)
- **Context:** N/A

---

### Next Steps for DST

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Governance help validating the issue, please comment on the ticket
- If this ticket has a `high-priority` label, please address as soon as possible so VFS teams are not impacted
- If this ticket has a `consider` label, please consider for future implementation

**Comment by msbtterswrth** [comment]
Confirmed this has been updated here: https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled
