### ISSUE TITLE
Staging Review finding: Use of "however" as a transition word. 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#95775]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Design System Staging Information
**Component:** Help users to... Know when their information is prefilled
**Staging Review ticket:** [AEDP, Design Patterns, Help users to... Know when their information is prefilled](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90181)

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not align with VA.gov voice and tone content principles.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-aligns-with-vagov-voice-and-tone-content-principles)
**VA.gov Experience Standard - category:** [Credibility](https://design.va.gov/about/experience-standards/#category-credibility)
**This is an issue with the:** 
**High-priority:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

The design style folks made a very recent update that explicitly bans the use of "however" as a conjunction.

## Recommended action
Choose another option such as "but" 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Plain language - Use simple words and terms](https://design.va.gov/content-style-guide/plain-language/use-simple-words-and-terms)
- **Context:** N/A

---

### Next Steps for DST

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Governance help validating the issue, please comment on the ticket
- If this ticket has a `high-priority` label, please address as soon as possible so VFS teams are not impacted
- If this ticket has a `consider` label, please consider for future implementation

**Comment by msbtterswrth** [comment]
confirmed this has been updated here: https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled
