### ISSUE TITLE
Read Platform Principles

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#958]
Everyone read [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md) and comment "done" when completed.

**Comment by mojaray2k** [comment]
Done

**Comment by Samara-Strauss** [comment]
Done

**Comment by lihanli** [comment]
done

**Comment by erikphansen** [comment]
done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by Justin-Pickett** [comment]
@artistgreen please comment done when you have completed this.

**Comment by artistgreen** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. team has completed this task. Closing this ticket.
