### ISSUE TITLE
Define baseline custom fields

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-team#95809]
As a member of the Github Projects task force team, I want to define and establish baseline custom fields within GitHub Projects,
so that I can ensure a smooth transition from ZenHub, retaining necessary metadata and maintaining workflow consistency across projects.

## ACs
**Custom Fields Definition**
- [ ] Establish essential custom fields (e.g., Priority, Story Points, Status, Epic) in GitHub Projects that mirror or replace the fields currently used in ZenHub.
- [ ] Each custom field should have a clear label, description, and expected value types (e.g., dropdowns, number inputs, text fields).

**Workflow Consistency**

 - [ ] Ensure that the new custom fields integrate seamlessly into existing GitHub workflows, replicating the behavior and capabilities of ZenHub.
 - [ ] Validate that any reporting, filtering, or sorting workflows in ZenHub are available or easily replicable with GitHub’s new project management tools and/or Sprintosaurus.

**Comment by tabinda-syed** [comment]
Label: Status
Description: The status (and board column) of an Issue
Value Type: Single-select

Label: Points
Description: Issue estimate in story points
Value Type: Integer

Label: Sprint
Description: The time period to which an Issue is assigned for work and delivery
Value Type: Iteration

Label: Priority
Description: The level of priority
Value Type: Single-select

Label: Start Date
Description: The planned date on which work on this Issue begins
Value Type: Date

Label: End Date
Description: The planned date on which work on this Issue ends
Value Type: Date
