### ISSUE TITLE
Define Templates for Migration to GitHub Projects

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-team#95817]
As a member of the GHP task team, I want to establish GitHub Project Board templates, issue templates, and a standardized set of issue types and sub-types, so that we can optimize the use of GitHub Projects while adhering to limits on issue types and maintain consistency across the organization.

## ACs
**GitHub Project Board Templates**
- [x] Define standardized GitHub Project Board templates that could be used across teams as a baseline.
    - [ ] Each template should be tailored for different workflows (e.g., Agile sprint tracking, Kanban boards, product development roadmaps).
    - [ ] Test and validate each template to ensure it meets the needs of different teams across the VA organization.

### Notes
Consider adding automation to ensure custom fields (e.g., auto-population of "Status" or "Story Points") function in GitHub Projects as they did in ZenHub.

**Comment by tabinda-syed** [comment]
10/29: Group decided to not pursue the full extent of Issue Templates (as described above). We'll add "Select Issue template" steps to the migration runbook (covered in #95845 ).

**Comment by msbtterswrth** [comment]
That links to the GH docs, but let me see if I can find the template and check it out.
