### ISSUE TITLE
CT: COVID-19 Notification should only be on the Landing page

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9582]
The notification implemented in #9257 Should only display on the GIBCT Landing Page at https://staging.va.gov/gi-bill-comparison-tool/. Currently, it shows on all pages in the Comparison Tool.

## Desired behavior
1. COVID-19 Notification banner is removed from all pages except the landing page

![Screen Shot 2020-05-28 at 10.30.35 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6401bf38-517d-44cf-acbe-b169fb0c6c99)

## Current behavior

![Screen Shot 2020-05-28 at 10.26.40 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5233ea71-b5a5-43e6-8554-587be4e134ae)

---

![Screen Shot 2020-05-28 at 10.26.52 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/95b0d4e5-0658-4784-9186-0ff79b93fedd)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12827

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
@delli-gatti-michael UX has reviewed and this looks good!

**Comment by amyknox** [comment]
@delli-gatti-michael - can this be closed since UX reviewed / approved  https://github.com/department-of-veterans-affairs/va.gov-team/issues/9632 ?

**Comment by sonntag-adam** [comment]
Testing passed/UX reviewed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/9632. Closing this bug.
