### ISSUE TITLE
Develop migration runbook for OCTO Product Teams

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#95845]

**Comment by tabinda-syed** [comment]
The group has started a GHP Migration Guide (WIP) on the #github-projects-cop channel on DSVA:
https://dsva.slack.com/docs/T03FECE8V/F07TR9N5XRT

**Comment by tabinda-syed** [comment]
10/29 To Do: Add the steps to select an Issue template as part of the create Issue process.
