### ISSUE TITLE
Rephrase links for disability compensation rates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#9585]
## What happened?
The links at the bottom of the [2020 VA special monthly compensation ](https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/)rates page are confusing. As I was going through them with Beth, we thought they were incorrect but then realized that it's because of the phrasing. Think we should rephrase to give the year the user will see when they get to the page as well as the effective date:

2019 rates (effective December 1, 2018)
2018 rates (effective December 1, 2017)
2017 rates (effective December 1, 2016)

**Update:** This change also needs to be made on Veterans disability compensation rates and birth defect rates pages

## Specs:
NA
## Steps to Reproduce
- URL: https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
- Test User _(if applicable)_: NA

## Desired behavior

See above

## Acceptance Criteria
All links are rephrased on: 
- [x] 2020 Special monthly compensation rates
- [x] 2020 Birth defect compensation rates
- [x] 2020 Veterans disability compensation rates

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

FYSA @jenniferlee-dsva @stephorkandatx

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @AnneHurley I've updated these links for the compensation rates page. We have the same issue with the [birth defect rates](https://www.va.gov/disability/compensation-rates/birth-defect-rates/) page, so I will update the text there as well. ![Screen Shot 2020-05-28 at 12.17.47 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/96faeac6-5859-4cb5-a74d-b639d71a7530)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!

**Comment by RLHecht** [comment]
Moving to validate. Changes made on two 2020 rates pages.

**Comment by RLHecht** [comment]
Also made changes to historic rates on the [2020 Veterans Disability Compensation Rates](https://www.va.gov/disability/compensation-rates/veteran-rates/) page.

**Comment by RLHecht** [comment]
These changes have been validated on live site. Closing ticket. FYSA @DanielleThierryUSDSVA @AnneHurley
