### ISSUE TITLE
Customization: design station-specific visual collateral

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9586]
Each station has its own SMS keyword (e.g. SCREEN483), URL (e.g. /covid19screen/483), and QR code linked to the unique URL. HMW manage all of the custom posters / other collateral that will be needed for 132 unique stations.

**Comment by artsymartha68** [comment]
Current posters and Illustrator file: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/COVID-screener/visual-collateral

**Comment by batemapf** [comment]
TO DO:

- [ ] collateral for Hawaii and outlying clinics (459, 459GE, 459GF, 459GH)
- [ ] VEText implementation for Hawaii and outlying clinics (459GE, 459GF, 459GH)
- [ ] collateral for NY sites *if we move forward with that customization*

**Comment by batemapf** [comment]
@artsymartha68 i generated the qr codes for all of the above, plus connecticut/mass., which came in last night. all in sub directories here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/COVID-screener/visual-collateral/custom-collateral.

feel free to move things around/reorganize as you see fit!

**Comment by artsymartha68** [comment]
Closing this one since I finished this past weekend.
