### ISSUE TITLE
Content: Messaging for appointment reminder letters

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9587]
We spoke with the Patient Experience (PX) team in the Veteran Experience Office (VEO) about additional methods to reach patients headed for VHA facilities regarding the digital screener option. They strongly advised us to see about including a blurb in the appointment reminder letters that go out to patients two weeks before an appointment. The VEO's words, many patients "live by those letters" and build their appointment expectations around them.

The letters are generated at by each station/facility (i.e. not nationally/centrally). I've asked VEO for assistance with getting connected with the right folks in the field to begin discussions on getting content into those letters. In the meantime, let's see if we can:

- [x] get a copy of one of those letters so we have some visibility into what they look like
- [x] draft up some generic content that is not station specific
- [ ] draft up station specific content

**Comment by batemapf** [comment]
for social media content, might want to pull from what Baltimore has already done? From Vishal:

>In response we are putting up more signs throughout the medical center, and also advertising in our social media and daily comms more starting today.

**Comment by DanielleThierryUSDSVA** [comment]
6.15.20: Letter sent to JTF review

**Comment by batemapf** [comment]
Discussed adding a mention of different/changing visitor policies once we get it back from JTF (and hopefully not sending it back to JTF).
