### ISSUE TITLE
Adding Jolene Langlinais to DSVA Slack

### ISSUE THREAD

**Issue by SilkeDannVA** [department-of-veterans-affairs/va.gov-team#95894]
Please add Jolene Langlinais [[jolene.langlinais@coforma.io](mailto:jolene.langlinais@coforma.io)]as a full member. They will be joining the CDS - Clinical Decision Support Applications project. Once they are in, we will add them to the appropriate channels. Their VA email is jordan.langlinais@va.gov, but they don't have their PIV card yet and can't access Outlook. Therefore, please use their corporate email.

If you have any questions or need clarification, please contact Silke Dannemann and/or Jeff Langworthy on DSVA Slack.

**Comment by SilkeDannVA** [comment]
Please let me know where you are with this Slack request? She is picking up her PIV card this week. Her VA email is [jordan.langlinais@va.gov](mailto:jordan.langlinais@va.gov).

**Comment by LEHigley** [comment]
sent to VA email
