### ISSUE TITLE
VA Forms Authoring Experience - externally maintained content

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#9589]
## Problem statement
VA Forms contain a mixture of local content which is maintained in the cms and external content, which gets updated via nightly migrations and should not be edited in the cms. No pattern for edit screens currently exists to address this situation.

## AC
- [ ] Develop an AX pattern for mixed editable/non-editable content
- [ ] Apply the pattern to VA Forms edit screens.

**Comment by MarciMcGuireGCIO** [comment]
Marking this closed since it was moved to Done on Jun 29.
