### ISSUE TITLE
Review the Norms for Communication

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#959]
Everyone read the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md) and comment "done" when completed.

**Comment by mojaray2k** [comment]
Done

**Comment by Samara-Strauss** [comment]
Done

**Comment by lihanli** [comment]
done

**Comment by erikphansen** [comment]
done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by artistgreen** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. team has completed this task. Closing ticket.
