### ISSUE TITLE
Notify PEGA team of records that trigger zsf notifications

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#95915]
As a member of the IVC Forms team, I want to automate a process that will send a notification to the Pega team when we have sent a ZSF email to a user letting them know the UUID of the form in question. 

### Implementation details: 
- Could tie into existing monitor that currently sends emails to users to let the know that they need to resubmit.
- This should be sent at the same time or very shortly after sending the email to the user (that process is currently configurable)
- Email for pega mail box: vbacodocmppeganot@va.gov

### Acceptance criteria
- Automated process
- Notify PEGA team when silent failure notifications are sent (Email sent to the email above)
- Use email template created in this story: [Create Email Templates for Notifying Pega about missing status and when we have sent a ZSF email to user](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98404)

**Comment by michaelclement** [comment]
Possible avenue for storing the Pega mailbox address in VA Notify is to use Testing List. Not sure if it's totally aligned with what we need but it's probably worth checking out:
![Image](https://github.com/user-attachments/assets/8147825f-0403-447f-a468-68d28166955a)

**Comment by andrea-merrill** [comment]
Adding this in case it's helpful: [FMP: Process to monitor missing statuses and send ZSF emails](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95907) 

This is the original ticket that has the monitor that kicks off the ZSF emails to to users.

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19795). Waiting on engineering review.

**Comment by michaelclement** [comment]
![Image](https://github.com/user-attachments/assets/fc4d08ca-f99f-419c-b09e-47182e461b5e)
