### ISSUE TITLE
Remove feature toggle va_online_scheduling_start_scheduling_link	

### ISSUE THREAD

**Issue by JunTaoLuo** [department-of-veterans-affairs/va.gov-team#95925]
## Description

This is a followup to the [initial feature toggle spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92168). [Start scheduling link has been fully released](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64864). We will need to remove the feature toggle from the list and the application code. 

## Requirements 

- Remove feature toggle `va_online_scheduling_start_scheduling_link` from the flipper list and the application code. 
  - [x] vets-website
  - [x] vets-api
  - [x] documentation
  - [x] non-prod environment
  - [x] prod environment

### Design Assets
N/A

---
### Acceptance Criteria

- [ ] vets-website: Remove this feature toggle and update any logic where it's used
- [ ] vets-api: Remove this feature toggle and update any logic where it's used
- [ ] Update the [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md)
- [ ] remove the feature toggle in non-prod environments (dev, sandbox, staging)
- [ ] file platform request to remove the feature toggle in prod environment

### Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
All steps completed, ready for validation @JRRoof

**Comment by jenniemc** [comment]
Validated the feature toggle flag is removed from production and non-production feature flipper admin pages. Documented in VAOS flipper documentation page. Close ticket.
