### ISSUE TITLE
User submissions failed due to missing ICN in the Lighthouse API request

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#95942]
Found during
* #89127 
  * Pulled into Sprint 9 because it is causing submission failures

From 10/23-10/24, 6 duplicate submissions from 2 unique users entered the backup path and failed due to a missing ICN in the lighthouse API request. From the job submission records:

```
bgjob_errors:
   {"1729720521"=>
     {"timestamp"=>"2024-10-23T21:55:21.557Z",
      "error_class"=>"ArgumentError",
      "caller_method"=>"error_hash_for_job_status",
      "error_message"=>"no ICN passed in for LH API request."},
```

Eventually, the users were able to submit successfully, and the dupe submissions were remediated. Digging into the UserAccount records behind these submissions, it was found that there were indeed 2 UserAccounts associated- one with an ICN, and one where ICN was `nil`

## Relevant Info
- User 1 submission ids: 3148488, 3148492, 3148513
- User 2 submission ids: 3148934, 3148971, 3149006

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Implement a fix in the BE that pulls the ICN from alternate sources when missing on the submission's UserAccount record (see Aurora's comment below)
- [ ] Write tests as needed/possible

**Comment by sethdarragile6** [comment]
Another case came in (submission id 3152088) on Friday 10/25, but didn't exhaust in the queue until 10/26. Interesting that it is clearly a non-retryable error, but the backup submission job is still retrying it. Seems like a separate bug.

**Comment by aurora-a-k-a-lightning** [comment]
to get the icn, i can think of three ways to stop the bleeding immediately:
1. check submission.user_account
2. find the user's Account record by their user_uuid
3. is the user still in the redis cache? try to find them there (`User.find(user_uuid)`) (not sure if this has icn, though, check)
(bonus)
4. can we find if the user has another UserAccount somewhere? we found that users that ran into this problem had another UserAccount record that had their icn in it
5. does submission.auth_headers have the icn?

**Comment by sethdarragile6** [comment]
Some findings and notes on Aurora's comment above.

1. Redis lookup results do not directly return ICNs, but they do have links to UserAccount and UserVerification records. Unfortunately, it's very likely that they would just point back to the "bad user account" anyway, since it generally represents the state of the current session
2. Submission.auth_headers does NOT have ICN

The approach I'm taking now is , in absence of an ICN, look up the user's records in the UserVerification table (which seems to contain a historical record of all the user's past and current auth provider/user accounts)) and loop through the unique UserAccount records returned until one with an ICN is found. There doesn't seem to be any other direct way to find a user's "alternate UserAccount" record
