### ISSUE TITLE
Vets-api terminal access for Victoria (Vic) Saleem

### ISSUE THREAD

**Issue by vsaleem** [department-of-veterans-affairs/va.gov-team#95954]
### Your Name

Victoria Saleem

### Your GitHub handle (terminal access is managed through GitHub)

vsaleem

### Your dsvagovcloud AWS user name (if applicable)

Victoria.Saleem

### Team, Role, and Company of the target individual

MHV, Va.gov - Secure Messaging, Developer, By Light

### Product Manager (PM) name and email

Bryan Riley, bryan.riley@va.gov

### Product Owner (PO) name and email

Lichelle Bain, lichelle.bain@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [x] dev
- [ ] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need access to ArgoCD in lower env so that I can begin work for the Va.gov Secure Messages team on updating endpoint changes and access tokens.

Link to previous SOCKS request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/61226

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by AnthonyWFlowers** [comment]
Greetings @vsaleem  You’ve been granted access to the `dev` environment.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help. 

Please reach out with any additional questions or concerns.
