### ISSUE TITLE
CT-103: Update analytics for new 103 content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9596]
As a developer, I need to remove analytics tracking to the new 103 content so that duplicate events are not triggered.

## Assumptions
1. This request originated from the following comment on an Analytics Implementation request for section 103: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-634663167
2. Original analytics implementation story for section 103 Analytics: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9190

## Acceptance Criteria: 
1. The `'gibct-learn-more'` event in showModal is removed from the learn more link for the "learn more about the Transition Act" link: 

   Read our FAQs on the Veteran Benefits and Transition Act
![image](https://user-images.githubusercontent.com/41790951/83185945-c6c01780-a0f9-11ea-9dcf-32d3d64ac2e9.png)

2. The `'gibct-modal-displayed'` event remains.

## Supporting Artifacts
1. ![image](https://user-images.githubusercontent.com/48527022/83024752-c68e2200-9ffc-11ea-8b30-6b679fffa055.png)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12876

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-01 at 12.39.42 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c0360490-cf6f-4062-9dc3-b47d6eee0882)

**Comment by sonntag-adam** [comment]
Commented on request https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-634663167. Change is in staging.

**Comment by sonntag-adam** [comment]
Request https://github.com/department-of-veterans-affairs/va.gov-team/issues/8959#issuecomment-634663167 is closed. Closing story.
