### ISSUE TITLE
Phase 1: VSP Documentation Re-Organization - `vets.gov-team` to `va.gov-team`

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#96]
Note: we are now using #538 to continue the repo reorg.

---

## Story
As a new VSP creator, I need access to the appropriate documentation for my area of focus so I can quickly get up and running in my workflow and start contributing to the work on Va.gov.

## Problem
Currently, the documentation in the `va.gov-team` repo is disorganized and doesn't have clear content or navigation for new platform users to access the appropriate resources for their work.

## Objectives
1. Organize the va.gov repo so that it is easy for new platform creators to navigate and get up and running.
2. Establish a sustainable documentation approach that ensures that this repo's documentation stays up to date and well-organized

## Tasks
- Rearchitect the IA of the `va.gov-team` repo to mimic the work recently done in the `vets.gov-team`
- Audit the content in the `vets.gov-team` repo to determine which content needs to remain **private**
- Migrate the appropriate content from the `vets.gov-team` repo over to the `va.gov-team` repo
- Write a Documentation Code of Conduct that lays out the expectations for updating documentation

**Comment by hpjaj** [comment]
@rtluu @emily - An objective for this sprint starting tomorrow is:

After reviewing repo/IA/documentation approach w/DSVA, migrate documentation to va.gov-team repo

Can you pls check on progress, who is responsible for this work, etc.  Thanks!

**Comment by emilywaggoner** [comment]
@hpjaj Ah that objective actually got moved off of your team's list for this sprint since we are prioritizing the onboarding of the first team next week. Will make sure the team has the latest list!

**Comment by mnorthuis** [comment]
Closed or moved remaining issues to new epic for next phase of work around the va.gov-team repo structure #538.

**Comment by Emily** [comment]
@hpjaj you got the wrong Emily :)
