### ISSUE TITLE
Review GitHub Markdown Cheatsheet

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#960]
Everyone read the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and comment "done" when completed.

**Comment by mojaray2k** [comment]
Done

**Comment by Samara-Strauss** [comment]
Done

**Comment by lihanli** [comment]
done

**Comment by erikphansen** [comment]
done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by artistgreen** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. team has completed this task. Closing this ticket.
