### ISSUE TITLE
A11y-Must: Add whitespace above H1

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9600]
>The area above the h1 typically has the breadcrumbs component. This could have a link to Home, at a minimum. Otherwise, consider customizing the heading to add some whitespace before it.

From: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9497#issuecomment-634176603

**Comment by artsymartha68** [comment]
OK so instead of bringing in the singular Home breadcrumb, we just need a bit more whitespace above our H1. That we can do and it's an easy fix. Adding @Yuffster-usds since it's purely a CSS thing. Renaming to not be a breadcrumb issue.

**Comment by Yuffster-usds** [comment]
![](https://user-images.githubusercontent.com/63240636/84814852-12baf980-afe0-11ea-9149-20561ef8eaa3.png)

https://github.com/department-of-veterans-affairs/vets-website/commit/f0a3e0613a6a79cd654385f4905261d6dd2f57db

**Comment by mchelen-gov** [comment]
closed by https://github.com/department-of-veterans-affairs/vets-website/pull/14499
