### ISSUE TITLE
Remove aria-label from print buttons

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#96012]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The `aria-label="print list"` on the print buttons doesn't add value for AT users, so our A11Y SME recommended we remove it. The label exists on these pages:
- Home/upcoming appts
- Past appts
- Requests

![Image](https://github.com/user-attachments/assets/69687e18-9873-480d-b41b-3f38e425ddec)

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets
N/A

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for validation.

**Comment by outerpress** [comment]
Looks good @JunTaoLuo ! Feel free to close. No documentation to update on my side.

@rileyorr just FYI because you brought this to our attention awhile ago - thanks!

**Comment by outerpress** [comment]
Also just to note, I tested the changes with Voiceover and Voice Control
