### ISSUE TITLE
Flipper UI access for Taras Kurilo

### ISSUE THREAD

**Issue by flex2016** [department-of-veterans-affairs/va.gov-team#96055]
### Your Name

Taras Kurilo

### Your GitHub handle (Flipper UI access is managed through GitHub)

@flex2016

### Team, Role, and Company of the target individual

Education Data Migration, React Developer, GovCio

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
Hi @flex2016, can you please provide a screenshot of your e-qip transmittal? It will look something like this. ![Image](https://github.com/user-attachments/assets/8a24b6be-9671-4410-93ef-22a5eb1e7b29)

**Comment by flex2016** [comment]
![Image](https://github.com/user-attachments/assets/48011e09-0bc3-4880-ad64-db41350558a2)

**Comment by bdech** [comment]
You've been granted access to Flipper prod and lesser environments.
