### ISSUE TITLE
A11y-Should: Semantic markup changes to form input

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9606]
> Consider semantic markup changes. These screen shots include semantic adjustments, as well as moving the buttons side-by-side to clarify the options cognitively. I think this would work for the walking scenario, but trust your judgement since you observed people going into the VAMC.

Note: uses `<form>` `<fieldset>` and `<input>` to replace current `<button>` implementation.

Code changes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9497#issuecomment-634194820
Screen shots: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9497#issuecomment-634232594

**Comment by artsymartha68** [comment]
To clarify: I prefer not to move the buttons side by side. I want them full width as they are now for thumb-only usage regardless of which hand is holding the phone. 

Semantics: yes!

**Comment by mchelen-gov** [comment]
Updated description with some details & links re: markup changes.

**Comment by batemapf** [comment]
@Yuffster-usds have you had a chance to pick this one up? If not, please unassign yourself so others can grab it.
