### ISSUE TITLE
Audit VA.gov health portal for URLs that have been redirected in Classic 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#96065]
## Description
Now that we have information from Rebekah Putera (MHV Portal + Access team, under Carnetta) with a list of 26 URLs that were redirected in a sign-in transition effort on MHV classic last month, we need to audit whether or not these redirected URLs exist on VA.gov and make decisions around how to handle those URL destinations for the best user experience. 

### Details: 
**Web Pages to Remove and Redirect: Sign In Audit 9.24.24**
The following webpages have been approved to be removed from My HealtheVet. The URLs (in all iterations) should be redirected to https://www.myhealth.va.gov/mhv-portal-web/user-login

- https://www.myhealth.va.gov/single-sign-on
- https://www.myhealth.va.gov/connecting-accounts-faqs
- https://www.myhealth.va.gov/disconnecting-accounts
- https://www.myhealth.va.gov/mhv-portal-web/disconnect-accounts-help
- https://www.myhealth.va.gov/mhv-portal-web/en/dod-faqs
- https://www.myhealth.va.gov/dod-military-service-information
- https://www.myhealth.va.gov/mhv-portal-web/st20161202
- https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/ds-logon-premium-account
- https://www.myhealth.va.gov/mhv-portal-web/mhv-registration
- https://www.myhealth.va.gov/registration-help
- https://www.myhealth.va.gov/mhv-portal-web/registration-va-online-rx-refill-for-veterans
- https://www.myhealth.va.gov/user-registration
- https://www.myhealth.va.gov/why-register
- https://www.myhealth.va.gov/mhv-portal-web/register-learn-more
- https://www.myhealth.va.gov/register
- https://www.myhealth.va.gov/registration
- https://www.myhealth.va.gov/mhv-portal-web/ss20200416-upgrade-to-premium-now
- https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/upgrade-account-to-premium
- https://www.myhealth.va.gov/premium
- https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/my-healthevet-offers-three-account-types
- https://www.myhealth.va.gov/mhv-portal-web/upgrade-to-a-premium-level-account
- https://www.myhealth.va.gov/upgrade
- https://www.myhealth.va.gov/mhv-portal-web/upgrade-your-my-healthevet-advanced-account-to-premium
- https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/secure-sign-in-partners
- https://www.myhealth.va.gov/sign-in-partners
- https://www.myhealth.va.gov/en/new-va-sign-in

### User story

As a Cartography team member, I want to update our URL destinations on VA.gov to route users to true pages on the national portal and not rely on redirects to provide a high quality user experience. 

### Notes
This ticket follows #92119 

## Possible tasks:
- [ ] Start a spreadsheet that identifies everywhere we link to one of the pages that they redirected, and then determine if our link should be:
  * updated to point at the new destination page
  * updated to point somewhere else or
  * removed all together
- [ ] and in the process of doing that, make note of all of their pages that really should be redirected somewhere else.

## Acceptance criteria
- [ ] A spreadsheet (see tasks above) is complete
- [ ] We have identified any URLs that route users back to the national portal from VA.gov that are impacted by changes from last month leading to a degraded UX.
- [ ] Any follow-on dev work related to this audit is ticketed

**Comment by nichia** [comment]
Did not find a match when searching for the URLs on Vets-Websit repository.

Noted that 2 of the Urls seems to the content on different URL path.

https://docs.google.com/spreadsheets/d/1kPhwUwO0oZXUHnPy0jGA8xuP13fBUBTXf97PfSTsGE0/edit?usp=sharing

**Comment by sterkenburgsara** [comment]
@nichia closing since you didn't find anything.
