### ISSUE TITLE
MyVA411 Data Request 526ez TE monitoring

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#96072]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

10/21/2024

### Date Range End

10/27/2024

### Product Name(s)

526ez

### Product Description

Disability compensation (21-526ez) is one of the longest and most utilized forms in VA. We are monitoring the release of a new feature, Toxic Exposure.

### Survey URL(s), key term(s), case category or type

Disability benefits, disability compensation, toxic exposure, filing online

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

None

### VA Email Address(es)

evelyn.davis3@va.gov, maya.carroll@va.gov, shannon.ford2@va.gov, jared.pace@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by evelynhilbrichdavis** [comment]
Hey @newworld2616 , is there a list of case categories that include "disability" that I could pull? I just looked back at my notes and saw that there is a case category "Disability Claim Application," for example.

**Comment by newworld2616** [comment]
Hi @evelynhilbrichdavis, what time frame you looking for?

**Comment by newworld2616** [comment]
Hello, I have shared the MYVA411 disability application data. Let me know if you have any questions. Thank you.
