### ISSUE TITLE
Form System Directory

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#9607]
We have an opportunity to leverage our existing forms on va.gov to help provide detailed and contextual examples to new designers and developers on VSP.

- Catalog Existing Forms
  - Outline the area of va.gov (education, healthcare, etc...)
  - Provide a brief description of the form and the intended outcomes
  - Unauthenticated Forms
     - Provide a production url
   - Authenticated Forms
     - Provide staging urls and links to test accounts

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
