### ISSUE TITLE
Review Design & Research Onboarding Documentation

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#961]
Samara and Arthur please review [Review Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers) and comment "done" when completed.

**Comment by Samara-Strauss** [comment]
Done

**Comment by artistgreen** [comment]
Done

**Comment by Justin-Pickett** [comment]
This task has been completed by A.E. design team members. Closing this ticket.
