### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by seipeljl** [department-of-veterans-affairs/va.gov-team#96103]
### Name

Jennifer Seipel

### Email

jennifer.seipel@oddball.io

### Role

UX Designer

### Team

Accredited Representative Facing Team & Claims Evidence

### Product Manager (PM) name

Candi Lemoine

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to jennifer.seipel@oddball.io.

**Comment by naomimarcussen** [comment]
You've been upgraded to have edit access.
