### ISSUE TITLE
Analytics Implementation for [Coronavirus-Chatbot]

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/va.gov-team#9611]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

@kaeliwyuen 
@rumyeahs 
@jeddacp 
@katieho-va 
@shefalinayak 
    
- What team/project is this work for?
    
This is for the VA-Chatbot project
https://github.com/department-of-veterans-affairs/covid19-chatbot

    
- Provide the Domain where Google Analytics needs to be implemented
This is for https://www.va.gov/coronavirus-chatbot 
    
- Please provide any upcoming deadlines or important milestones
Ongoing enhancements for Chatbot
    
    - [Provide relevant dates here]
Desirable to have these in 2 two weeks

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
1. To track internal inbound traffic from VA.gov pages to the Coronavirus-Chatbot (For example, from pages such as MHV, FAQ, various facilities pages and others)

- Additional Comments

   - Since this is the first reporting request on DOMO for Chatbot specific metrics, we would need a new Coronavirus-Chatbot specific dashboard to be set up for the same. 
   - The chatbot has been live since Apr 23, 2020. So we are looking to have the incoming traffic from Apr 23 until date. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Implementation completed & added to the KPI dashboard. Closing this issue.
