### ISSUE TITLE
[0781 PS] JSON file

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#96120]
The system needs to support a JSON file for just the new 0781 form data that will be used to create the paper version of the PDF. 
The current JSON is still needed until 0781 has been fully released and no more claims are going through the "old" path. 

- [ ] New JSON (separate from the existing)
- [ ] An in progress JSON file should be deleted after one year (366 days from the date it was started)
- [ ] After a submission the JSON is saved indefinitely

**Questions:** 
- Currently the JSON are saved indefinitely, should we change this? 

[Design Spec](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9250-77233&t=faPDaJXJqj4NzfAi-4)
[0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)

**Comment by lisacapaccioli** [comment]
@freeheeling - I am not sure what kind of information you need for creating a new JSON. I am not sure if you need multiple tickets for it as well. As part of your discovery can you think about some high level requirements for this so we can define the ticket better? Thanks

cc @kylesoskin

**Comment by SamStuckey** [comment]
I Think this ticket could be better represented as a few distinct chunks of work
 
- [Define the new form JSON schema, based off the form](...)
- [Create BE / FE boilerplate for saving Veteran input into this new schema](https://github.com/department-of-veterans-affairs/vets-api/issues/19363)
- [Create JSON to PDF conversion service](https://github.com/department-of-veterans-affairs/vets-api/issues/19364)
- Have a follow up discussion about how long we should keep this data in the system. If it's already decided (no longer than a year) that's fine, but we should make that a tech debt ticket for later

**Comment by SamStuckey** [comment]
closing in favor of these tickets, which break this down with a bit more specificity
 
- [Define the new form JSON schema, based off the form](https://github.com/department-of-veterans-affairs/vets-api/issues/19414)
- [Create BE / FE boilerplate for saving Veteran input into this new schema](https://github.com/department-of-veterans-affairs/vets-api/issues/19363)
- [Create JSON to PDF conversion service](https://github.com/department-of-veterans-affairs/vets-api/issues/19364)
- [Have a follow up discussion about how long we should keep this data in the system. If it's already decided (no longer than a year) that's fine, but we should make that a tech debt ticket for later](https://github.com/department-of-veterans-affairs/vets-api/issues/19415)

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
