### ISSUE TITLE
Send confirmation emails to users affected by incident

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96121]
As a user who didn't receive my confirmation email after my submit, I need to receive my email so that the information the VA provides is consistent with what the VA told me to expect.

### Acceptance criteria
- We have verified that all users affected in the window below had their form imported into PEGA
- We have confirmed that we did not already send an email
- We have sent a confirmation email that matches the VA notify template to the email address each user submitted on their application
- 
<img width="1150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a473f19644d5ccbab7a3a95bfb5ed6f852d4aa81/image.png" alt="image.png" />

**Comment by michaelclement** [comment]
I've got the local Postman setup working to send emails. Just need the actual list of addresses/names to send them to. I'll get with Don so that we can pull that info out of the production DB.

**Comment by michaelclement** [comment]
Got the list of UUIDs affected and have sent to Cindy to verify those submissions got ingested. Waiting to hear back.

**Comment by michaelclement** [comment]
Blocked until we know (from Cindy) whether or not the submissions have been ingested properly.

**Comment by michaelclement** [comment]
| |before|after|
|-|------|-----|
|Prod emails sent|<img width="1231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9PQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--463f5bf3901b6a9d20aa41d77beb7edfef62bb80/before.png" alt="before.png" />|<img width="1231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFNPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcb3b5941dffc499ab47c93e593808bca8c412a9/after.png" alt="after.png" />|
