### ISSUE TITLE
Zero Silent Failures - Long standing requests without response

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#96130]
## Description
When a veteran submits a request for a medical appointment, we want to ensure that it is processed on time. If a request sits too long, we wish to notify the veteran so they can take other steps to get the needed appointment.

---

## Development Checklist

- [ ] Task 1 - Determine if the date a request was created is returned with the request when it is retrieved to display in the appointments list.
- [ ] Task 2 - If the created date is not currently returned, is it available, and what needs to be done to retrieve it?
- [ ] Task 3 - 

### Design Assets
- N/A

### Developer Reference
- N/A

## Definition of Done
- [ ] All tasks criteria are met
---

**Comment by simiadebowale** [comment]
Requests have a created date, we can use this to calculate how long the request has been sitting without being processed
