### ISSUE TITLE
Sidekiq Admin UI access for Kenneth Santiago

### ISSUE THREAD

**Issue by ksantiagoBAH** [department-of-veterans-affairs/va.gov-team#96150]
### Your Name

Kenneth Santiago

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

ksantiagoBAH

### Team, Role, and Company of the target individual

bah-mbs-selfserv. Tech Lead, Booz Allen Hamilton

### COR Name

Jose Colon-Delgado

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [x] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I need access to test VANotify error emails in staging

**Comment by bmatos312** [comment]
Granted access to all except PROD
