### ISSUE TITLE
Facility phone number issue on locations page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#96156]
## Summary
_Describe what went wrong_

On the choose a location page we have logic display an additional info section "Why isn't my facility listed". I noticed on staging that the phone numbers listed have too many numbers. I don't know if this issue is in prod, or is a staging data issue.

![Image](https://github.com/user-attachments/assets/57244409-7178-4319-a2b4-4aaaec9f4d7a)

## Specs
- Device: MacBook Pro
- Browser: Chrome

## Steps to Reproduce
**Test User:** 

1. Go to staging.va.gov
2. Log in as Royal Tester
3. Start scheduling a new amputation care appointment
4. Navigate to the Choose a Location page
5. Open the additional info "Why isn't my facility listed"

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

- It seems to be adding the numbers "3816" after the main Cheyenne facility phone number. Maybe this is an extension?
- The phone number is missing dashes

<img width="163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9GQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e61662315e0d46fa509f3a8150fc12dadd3f63f/staging.va.gov_my-health_appointments_schedule_location.png" alt="staging.va.gov_my-health_appointments_schedule_location.png" />

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

The phone number should be formatted correctly. If it includes an extension, that should be indicated.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by jenniemc** [comment]
Add the logic to check for the "main" phone extensions. 

The github ticket below inadvertently removed the constant array that separates the phone number from the extension. I incorrectly assumed that main phone numbers do not contain extension. 
https://github.com/department-of-veterans-affairs/vets-website/pull/30969/files/1a1aae9e816eceac1984235842ad94bbff8c5296#diff-f21fbf3645ef0c13c3ae92e275c5c7cdcd381fbccb4fd520515da4d9637bc85d 

Phone object returned for Cheyenne VA Mobile Clinic 
```
{
    "main": "307-778-7550 x3816",
    "fax": "307-778-7381",
    "pharmacy": "866-420-6337",
    "afterHours": "307-778-7550",
    "patientAdvocate": "307-778-7550 x7573",
    "enrollmentCoordinator": "307-778-7550 x7579"
}
```

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for validation

**Comment by outerpress** [comment]
This looks good @JunTaoLuo ! Feel free to close out. FYI @JRRoof

**Comment by JunTaoLuo** [comment]
Thanks Peter!
