### ISSUE TITLE
QA Project - Manual test script for Step 1: Applicant info

### ISSUE THREAD

**Issue by adamcaniparoli** [department-of-veterans-affairs/va.gov-team#96154]
## Issue Description
Create manual regression test for Step 1: Applicant Info. Test plan is written in TestRail and subsequent testing is ideally performed within TestRail.

---
## Tasks
- [ ] Creation of a manual test script for this step

## Acceptance Criteria
- [ ] Every possible action a user can take for this step is documented with the ability to label each action with a Passed/Failed/Skipped/Blocked
---

**Comment by aplatt-coforma** [comment]
Updated documentation here: https://docs.google.com/document/d/1e750OL3LQ-uTDjhHFnr-1sYcrV6PWif7caEUP8oi2mY/edit?tab=t.0#heading=h.2q69qbn7j8h2
