### ISSUE TITLE
[UX] 10-10EZR: Confirmation Exploration

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#96162]
As a Researcher, I would like to further explore the confirmation flow so that I know if it's something Veterans would like.

- [x] Map out a rough timeline with relevant projects leading to the Confirmation Flow.
- [x] Determine which projects/patterns should be developed as this 
- [ ] Discuss with the team to confirm the timeline and feasibility

- [ ] **Success: We have plans for next steps**

**Comment by IMHieuVo** [comment]
- The team rated the importance and feasibility of the section of the form. 
- Team voted for TERA, Financial Information, and Medicare/Medicaid as the most important, mostly falling into the “MUST HAVE” catergory. These are the items the team should consider developing before concept testing.
- The one thing we did not confirm and discuss is the timelines.
- I have several ideas on how to approach this so I’ll visualize them then share with the team for further discussions.
