### ISSUE TITLE
SPIKE | COLA BGS downtime

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#96164]
## Issue Description
_Every fall, VBA conducts a weekend-long cost of living adjustment in the Corporate Database. Downtime for relevant systems (BGS, EVSS, VBMS) is ~2 days. This year it will be Nov 16-17, 2024._

[COLA planning channel](https://dsva.slack.com/archives/C064JKBD0N8).

---
## Tasks
- [x] Determine how PagerDuty works architecturally: PagerDuty  -->  Vets-API --> Vets-website?

## Acceptance Criteria
- [ ] Determine if any downtime messaging needs to be added to notify Veterans of this outage
---

**Comment by steele-lm** [comment]
Anything sent to LH during outage will be queued and submitted later.

**Comment by mjknight50** [comment]
Final decision was to move all retries to 16:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96564
