### ISSUE TITLE
 Engineers: Set Up Local Dev Environment 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#962]
Erik/Lihan/Amen: please  review and complete [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/getting-started.md) and the following below:

[Set Up Front End](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
[Set Up Back End](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
[Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Administrative/Onboarding/request-access-to-tools.md)
[Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

Comment "done" when all tasks listed above have been completed.

**Comment by lihanli** [comment]
3rd link is broken, i'm assuming it means login as a test user on staging/dev, if so i'm done

**Comment by Justin-Pickett** [comment]
Thanks for catching that Lihan. I will get that checked out and update the link. Thanks.

**Comment by erikphansen** [comment]
Done

**Comment by Justin-Pickett** [comment]
All the links should be working now.

**Comment by mojaray2k** [comment]
Update once I get access to devops repos and other access I will be done.

**Comment by Justin-Pickett** [comment]
@mojaray2k be sure to comment done if you're all set up.

**Comment by mojaray2k** [comment]
I was able to sign in to staging.

**Comment by mojaray2k** [comment]
I was able to setup the Front end. I was able to setup internal tools.

**Comment by mojaray2k** [comment]
I am going to ask one of the backend engineers how to setup the backend. I am not even gonna pretend I understand those docs since I am not a ruby developer.

**Comment by mojaray2k** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. engineering team members have completed this task. Closing this ticket.
