### ISSUE TITLE
[GitHub Action] Helm Chart Versioning

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#96205]
## Description
People forget to bump the version of helm charts when making updates to templates. If a Pull Request modifies a chart but the changelog does not include `Chart.yaml`, fail the workflow/check.

## Acceptance Criteria
- [ ] A Pull Request modifying a Helm Chart, but not modifying the `Chart.yaml` can not be merged

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
I have written a workflow that checks to see if there is a modification within a helm deployment, then checks if the particular deployment chart.yaml version is updated or not. I am going to start testing, but also considering if I should force the check upon PR creation or upon PR merge

**Comment by Efe-Oddball** [comment]
I have tested the workflow for this implementation and pushed out a PR

**Comment by Efe-Oddball** [comment]
Once the PR is approved and merged, I will add the work flow as a merge condition to block any merge in which a change was made to any helm configuration, and the corresponding chart.yaml version was not upgraded

**Comment by Efe-Oddball** [comment]
Moving this ticket to a review state
