### ISSUE TITLE
Analytics Implementation or QA Support for Coronavirus-Chatbot

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/va.gov-team#9621]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

@kaeliwyuen 
@rumyeahs 
@jeddacp 
@katieho-va 
@shefalinayak 
    
- What team/project is this work for?
    
This is for the VA-Chatbot project
https://github.com/department-of-veterans-affairs/covid19-chatbot

    
- Provide the Domain where Google Analytics needs to be implemented
This is for https://www.va.gov/coronavirus-chatbot 
    
- Please provide any upcoming deadlines or important milestones
Ongoing enhancements for Chatbot
    
    - [Provide relevant dates here]
Desirable to have these in 2 two weeks

- Typical Website Interactions to Track
    
1. 
- To track the number of times a phone number was clicked, 
- the associated devices (nice to have), 
- the path where the phone number was clicked (since in some cases the same phone number appears is more than one path) (Refer example below) 

Example 1: 
VA311 phone number is presented to the user when the veteran chooses to 'Speak with someone'. This option is available to the veteran under multiple different top level categories they choose, and it would be helpful to understand what top level category was selected when the veteran clicks on a phone number to call.  

**Scenario 1**: The user selects Health care as the top level category and wishes to speak to someone at the end of the path. 

![Screen Shot 2020-05-28 at 12 49 10 PM](https://user-images.githubusercontent.com/2493271/83196965-c714de80-a10a-11ea-8069-09d3576f3b14.png)

**Scenario 2**: The user selects COVID-19 Prevention as the top level category and wishes to speak to someone at the end of the path. 

<img width="844" alt="Screen Shot 2020-05-28 at 12 40 13 PM" src="https://user-images.githubusercontent.com/2493271/83197067-e57ada00-a10a-11ea-9fcd-66923aeac33b.png">

In both scenarios, the VA311 number is presented to the user. Once the user clicks on this phone number, we would like to differentiate between the two paths to know which top level category the user selected originally. 

- Additional Comments
Assumption: This will be added to the Coronavirus Chatbot dashboard on DOMO implemented as part of #9611 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @jeddacp. We will work on getting you all dataLayer requirements to support this tracking. 

Will be in touch soon. 

cc: @bsmartin-ep

**Comment by bsmartin-ep** [comment]
How does this look @jonwehausen?

## Data Layer Request

<table>
<tr>
<th>Description</th><th>Screenshot</th><th>Datalayer</th>
</tr>
<tr>
<td>Click a top-level Chatbot Button</td>
<td>
<img src="https://user-images.githubusercontent.com/62304138/83761450-5ad33700-a644-11ea-9e20-0228ab0528ab.png" />
</td><td>
<pre>{
  'event': 'chatbot-button-click',
  'chatbot-top-category': 'COVID-19 testing at VA'
}</pre></td></tr>
<tr>
<td>
Click on non top-level Chatbot Button
</td>
<td>
<img src="https://user-images.githubusercontent.com/62304138/83761558-7b02f600-a644-11ea-93b1-735bf9380b64.png" />
</td><td>
<pre>{
  'event': 'chatbot-button-click',
  'chatbot-sub-category': 'Should I wear a mask?'
}
</pre></td></tr>
<tr>
<td>
Click on any resource link in results panel
</td><td>
<img src="https://user-images.githubusercontent.com/62304138/83761627-9110b680-a644-11ea-95eb-9ad60c2a362b.png" />
</td><td>
<pre>{
  'event': 'chatbot-resource-link-click'
}
</pre></td></tr>
</table>

**Comment by jonwehausen** [comment]
@bsmartin-ep Looks great! Reviewed and approved. 

@rumyeahs & @jeddacp we are ready to move forward with the above dataLayer specification implementation. Please let us know if you have any questions. 

### Few Dev Notes
- Please note, the event `chatbot-button-click` is an existing event, we are would just request the addition of the two DL variables for `chatbot-top-category` and `chatbot-sub-category` where appropriate. 
- If the user goes down the "Ask a different type of question" path, the DL variables above should reset with the new `chatbot-top-category` and `chatbot-sub-category` questions & answers for the 2nd series. 
- The `chatbot-resource-link-click` should be a reused event attached to any and all link clicks that occur for links provided back to the user as a response.

**Comment by bsmartin-ep** [comment]
### GTM implementation WIP

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000304

TODO:

- Add new custom dimensions to non-prod GA for: `chatbot-top-category` `chatbot-sub-category`
- Update indices for these CDs in button and resource link Chatbot event

**Comment by katieho-va** [comment]
@jonwehausen @bsmartin-ep Just to clarify, are these TODOs and Dev Notes for our team or yours?

**Comment by bsmartin-ep** [comment]
@katieho-va -

GTM TODOs are on me.   [Datalayer implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9621#issuecomment-638843219) is for your team.

**Comment by katieho-va** [comment]
> Please note, the event chatbot-button-click is an existing event, we are would just request the addition of the two DL variables for chatbot-top-category and chatbot-sub-category where appropriate.

@jonwehausen @bsmartin-ep We see the event `chatbot-button-click` in Analytics360, but not in the `vets-website` code. Where is this event coming from?

**Comment by jonwehausen** [comment]
Hi @katieho-va,

Oops, spoke too soon! My mistake -  Seeing now we configured the `chatbot-button-click` event entirely thru GTM. 

In this case, we would like to request the `chatbot-button-click` event be put in place for all of the button clicks according to the specification Brian provided. 

During verification and QA, we will remove our GTM configuration that is firing this event when pushing to ensure we're not getting duplicate event fires. 

Adjust commented above with dev notes to reflect that we will need this event implemented.

**Comment by katieho-va** [comment]
Discussed with Jon/Brian over Slack that there's not much in the HTML to distinguish between top level and sub categories (text matching would be very brittle), so just the two events will be added without DL variables.

[Slack thread](https://dsva.slack.com/archives/C011BG82ZL6/p1591295540033400)

**Comment by jonwehausen** [comment]
Thank you for including the Slack exchange @katieho-va. 

### QA Testing

Description of Interaction | Screenshot of DL | Screenshot of Tags | Test Status
------------ | ------------- | ------------- | ------------- 
Click on first question in chatbot dialogue | ![image](https://user-images.githubusercontent.com/48527022/83892384-96413480-a71c-11ea-9b78-a60051dc9d96.png) | ![image](https://user-images.githubusercontent.com/48527022/83894031-c4277880-a71e-11ea-8027-786f7ac7dd04.png) | ✔️ **PASS**
Click on second question in chatbot dialogue | ![image](https://user-images.githubusercontent.com/48527022/83895027-1d43dc00-a720-11ea-9f52-56a0ddf807e0.png) | ![image](https://user-images.githubusercontent.com/48527022/83894907-ee2d6a80-a71f-11ea-81ad-b2bc113b38af.png) | ✔️ **PASS**
Click on any third question in chatbot dialogue | ![image](https://user-images.githubusercontent.com/48527022/83895675-06ea5000-a721-11ea-939d-a0baaaa62004.png) | ![image](https://user-images.githubusercontent.com/48527022/83895502-c4287800-a720-11ea-89fd-f8ef229582ec.png) | ✔️ **PASS**
Click on any resource link click | ![image](https://user-images.githubusercontent.com/48527022/83896106-a0b1fd00-a721-11ea-8f42-a42491b37bbb.png) | ![image](https://user-images.githubusercontent.com/48527022/83896059-942da480-a721-11ea-9a89-3b4c03eee807.png) | ✔️ **PASS**

QA has passed and the functionality has been published! 

Thank you all for your work here.
