### ISSUE TITLE
[LH Doc Upload] Audit and complete ZSF requirements

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#96216]
## Summary

TBD

Document on requirements:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md

Link to [Slack thread on this ](https://dsva.slack.com/archives/C05MPTGMX0E/p1730383731877819?thread_ts=1730378912.556079&cid=C05MPTGMX0E)

**Comment by NB28VT** [comment]
Note from Scott "we were unsure if the datadog ZSF metric tagging stuff you added also was added to the polling that they all share in order to increment in cases where there is polled failure, or basically we just need to all sync up and make sure we have all states covered, and that is what that last ticket it for before it goes to prod. 
 
That would NOT have been explicitly in scope, since your ticket was only to account for stuff in prod already, to be compliant for Nov 11 deadline. "

**Comment by NB28VT** [comment]
Scott is available to sync on this

**Comment by ajones446** [comment]
@NB28VT  Quick update - my understanding is that the acceptance criteria for this ticket is that both jobs needs to log two cases: 
1. When the failure email fails to send (`log_silent_failure`) 
2. When a failure email sends (`log_silent_failure_avoided`)

Looks like Scott covered that already.

- [ ] 0781 Mailer PR https://github.com/department-of-veterans-affairs/vets-api/pull/19081 and 19122
    - [ ] log_silent_failure
    - [ ] log_silent_failure_avoided

- [ ] Evidence Mailer PR https://github.com/department-of-veterans-affairs/vets-api/pull/19097
    - [ ] log_silent_failure
    - [ ] log_silent_failure_avoided

TODO: There was another ZSF requirement about DD naming conventions we did for BDD. I'll look up and add that here.

**Comment by NB28VT** [comment]
> [@NB28VT](https://github.com/NB28VT) Quick update - my understanding is that the acceptance criteria for this ticket is that both jobs needs to log two cases:
> 
> 1. When the failure email fails to send (`log_silent_failure`)
> 2. When a failure email sends (`log_silent_failure_avoided`)
> 
> Looks like Scott covered that already. 🥇
> 
> * * [x] 
>     [x]  0781 Mailer PR [[DBEX] log and monitor form 0781 failure email events vets-api#19081](https://github.com/department-of-veterans-affairs/vets-api/pull/19081) and [19122](https://github.com/department-of-veterans-affairs/vets-api/pull/19122)
>     
>     * [x]  log_silent_failure* [x]  log_silent_failure_avoided* [x] 
>     [x]  Evidence Mailer PR [[DBEX] log and monitor evidence upload failure email events vets-api#19097](https://github.com/department-of-veterans-affairs/vets-api/pull/19097)
>     
>     * [x]  log_silent_failure* [x]  log_silent_failure_avoided
> 
> ~TODO: There was another ZSF requirement about DD naming conventions we did for BDD. I'll look up and add that here.~ _Nevermind, that was the dashboard names which I added to the DD dashboard tickets._
> 
> * [ ]  TODO: Is there anything else we need to check?

Oops @ajones446  we both ended up looking at this at the same time haha, here is the list I came up with but I haven't checked yet:



Unresolved silent failures to tag:
- [ ] UploadBDDInstructions job exhaustion and failure
- [ ] SubmitUploads Exhaustion handler fails before email is sent
- [ ] Form 0781/a Exhaustion handler fails before email is sent
 - [ ] Failure after polling and before queueing Veteran upload failure mailer
 - [ ] Failure after polling and before queueing Form 0781/a upload failure mailer


Resolved silent failure to tag:
- [ ] Submit Uploads upload error mailer sent
- [ ] Form 0781/a Upload error mailer sent
- [ ] Veteran upload failure mailer sent when Lighthouse fails to process it (marked failed in polling)
- [ ] Form 0781/a failure mailer sent when Lighthouse fails to process it (marked failed in polling)

**Comment by NB28VT** [comment]
TODO:
- [ ] Confirm ZSF does not apply to BDD
- [ ] Confirm it is ok to log a silent failure before a email is sent and then log a silent failure avoided when it is sent, do they cancel each other out? (this is important in the exhaustion handlers for veteran uploads and form 0781/a

**Comment by NB28VT** [comment]
Yes, we need to PR notes in our upload jobs and move the mailer code to the bottom of the begin block

**Comment by ajones446** [comment]
> Still waiting for guidance on failure monitor alerts https://dsva.slack.com/archives/C053U7BUT27/p1731009778372279

We did not get a clear answer on requirements, so we just added our own monitor for the catch-all errors that will go to the benefits-disability-notification channel.

**Comment by ajones446** [comment]
This has been completed for BDD and 0781. Will need to double check Veteran Evidence uploads before release.

**Comment by NB28VT** [comment]
Confirmed in staging this is getting incremented properly, see https://vagov.ddog-gov.com/dashboard/aq9-bew-hjh/benefits---disability---526---veteran-uploads-lighthouse-migration-staging?fromUser=false&fullscreen_end_ts=1733177582984&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=edit&fullscreen_start_ts=1732572782984&fullscreen_widget=266765502534980&refresh_mode=sliding&from_ts=1732572779863&to_ts=1733177579863&live=true
