### ISSUE TITLE
Give Veterans the ability to download additional claim development letters

### ISSUE THREAD

**Issue by iandonovan** [department-of-veterans-affairs/va.gov-team#96224]
# Problem

This issue is for implementing the Claim Letters changes discussed in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95618) and others.

[Here is the original Change Request](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9466)

Veterans are currently not shown the full suite of Claim Development Letters. We are showing them letters with doctype 184, but no other types. We would like to show them the other letter types. Separately, we would like to make sure that the letters are shown with human-readable names.

# Solution
The list of letters we show is managed by [this list and Flippers](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/claim_letters_controller.rb#L43)

First, we need to enable the Flippers that control the non-184 letters (184 is always rendered). These are:
1. `cst_include_ddl_boa_letters`
2. `cst_include_ddl_5103_letters`
3. `cst_include_ddl_sqd_letters`

and they are managed in the [Flipper UI](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

So, we'll need to enable those flippers on production. These Flippers only regulate this list of letters, they are not used elsewhere in vets-api. Enabling them will not turn on other features.

Second, we need to add code to vets-api to ensure these letters' names are sent to the client as what we'd like them to be. Currently, the web client and mobile app maintain separate code to render the correct names. If we move this upstream into vets-api, we will remove this duplication and ensure both applications show the same information.

Third, @Sparowhawk noted in slack that  `The only consideration that needs to happen is to make sure the claim letter has the decision letter sent flag flipped to true in the api/upstream`. I don't know what this means. Or, rather, I understand what it means but I do not see a way to set a decision letter flag.

# Acceptance Criteria

1. All claim development letters are rendered
2. All rendered letters have the correct user-readable names [from this table](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9466#issuecomment-2414960345)
3. Each claim letter has a decision letter flag set to true(?) so mobile knows to display it(?)

**Comment by salihaghaffar** [comment]
I have validated that the human-readable names for claim letters are correctly displayed on the UI, but I was unable to verify the Flipper settings and decision letter flag implementation. @dysbo 
@iandonovan
