### ISSUE TITLE
Contact Center Request - Analytics Implementation for Chatbot

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/va.gov-team#9622]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

## Description
- Is this request for Google Analytics implementation or QA?
Reporting on comparison between contact center numbers and chatbot numbers

- Who is this request for?

@kaeliwyuen 
@rumyeahs 
@jeddacp 
@katieho-va 
@shefalinayak 
    
- What team/project is this work for?
    
This is for the VA-Chatbot project
https://github.com/department-of-veterans-affairs/covid19-chatbot

    
- Provide the Domain where Google Analytics needs to be implemented
This is for https://www.va.gov/coronavirus-chatbot 
    
- Please provide any upcoming deadlines or important milestones
Ongoing enhancements for Chatbot
    
    - [Provide relevant dates here]
Desirable to have these in 2 two weeks

- Typical website interactions to track
Create a report to compare the total number of calls serviced by VA311 Contact Centers against the total number of user sessions within the Coronavirus chatbot, for the same time period. 

For example, we have seen a contact center report along the below lines:
![image](https://user-images.githubusercontent.com/2493271/83198877-20324180-a10e-11ea-8a97-96f0a3896ffc.png)
which has a total of 12k inquiries. 

A similar report for chatbot (as seen below) indicates roughly 15k queries. 
![image](https://user-images.githubusercontent.com/2493271/83198891-288a7c80-a10e-11ea-9d95-40f44d77509c.png)

It would be helpful to see how many queries the chatbot is able to service in the same time period as the contact center. 

Can we do a week on week comparison? 

- Additional Comments
Assumption: This will be added to the Coronavirus Chatbot dashboard on DOMO implemented as part of #9611 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@Kimberley2019 @clantosswett can you add if/where we can find this data? i.e. Covid dashboard, contact center report, etc.

**Comment by clantosswett** [comment]
The VEO Tier 1 Contact Center data for COVID can be found on our COVID dashboard on DOMO: 

https://va-gov.domo.com/page/1872052027?userId=1445817514

The chart is titled "Veterans Experience Office (VEO) Calls by Issue"

If you have any questions, please ping me so I can provide any additional context.

**Comment by joanneesteban** [comment]
Data has been added to the Chatboot KPI dashboard. Will close once the dashboard has been shared.
