### ISSUE TITLE
Contact Center Review for Benefits Decision Review - Supplemental Claim Email Error Notifications

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#96221]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Supplemental Claim is a form for one of the three decision review pathways. Veterans can use this form when they disagree with a previous decision and have new and relevant evidence that may establish a theory of service connection. We've made updates to the email error notifications for form failures
- Email error template for SC form
- Email error template for SC supporting document
- Email error template for SC supporting form (4142)

### Launch Date
Ready to Launch. Date TBD

### Version Number
Oct 2024

### Product Guide
[SC Product Guide](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B5321D206-ABD0-440A-BCFF-0AE5A28841F5%7D&file=Supplemental%20Claim%20Product%20Guide%20(2024).docx&action=default&mobileredirect=true)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi, @comaurice. Can you please attach the draft of the product guide as a Word document to this ticket? Thank you!

**Comment by comaurice** [comment]
[Supplemental Claim Product Guide (2024).docx](https://github.com/user-attachments/files/17601349/Supplemental.Claim.Product.Guide.2024.docx)
Hey @starlow00 here you go

**Comment by starlow00** [comment]
Thank you!

**Comment by starlow00** [comment]
Draft looks good, sending top VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. A working copy is attached for future revisions. Thank you!
[Supplemental.Claim.Product.Guide.v2_SRT_11062024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e3dc45bf6f7f2db897612b044089faaa3d3961b/Supplemental.Claim.Product.Guide.v2_SRT_11062024.docx)
