### ISSUE TITLE
[Bug] MDT - All-items-ineligible alert not displayed

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9624]
## What happened?
On Staging **Order hearing aid batteries and accessories** form, All-Items-Ineligible account-/data-scenario does not trigger expected alert.

## Specs:
- Browser-/device-agnostic
- `vets.gov.user+38@gmail.com` (Pauline)

## Steps to Reproduce
1. Go to https://staging.va.gov/
1. Sign-in via **ID.me** as **`vets.gov.user+38@gmail.com`** (Pauline).
1. Go to https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction .
1. Observe that regular form-intro is displayed, instead of All-Items-Ineligible alert.

### Regular form-intro
![Screen Shot 2020-05-28 at 4 18 53 PM](https://user-images.githubusercontent.com/587583/83203756-0a695000-a0ff-11ea-8b89-b6dca901eb37.png)

## Desired behavior
Instead of regular form-intro, [**All-items-ineligible alert**](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/409233432) should be displayed:
![image](https://user-images.githubusercontent.com/587583/83203581-99299d00-a0fe-11ea-8e97-f0840f47176d.png)

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by bradl3yC** [comment]
@tlei123 this is working in staging - I think the API may have been down when tested originally

**Comment by bradl3yC** [comment]
@tlei123 Can we validate?
