### ISSUE TITLE
[Bug] MDT - Vet-deceased alert not displayed

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9625]
## What happened?
On Staging **Order hearing aid batteries and accessories** form, Veteran-deceased account-/data-scenario triggers incorrect alert.

## Specs:
- Browser-/device-agnostic
- `vets.gov.user+21@gmail.com`(Chad)

## Steps to Reproduce
1. Go to https://staging.va.gov/
1. Sign-in via **ID.me** as **`vets.gov.user+21@gmail.com`** (Chad).
1. Go to https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
1. Observe that regular form-intro is displayed, instead of Veteran-deceased alert.

### Regular form-intro
![Screen Shot 2020-05-28 at 4 18 53 PM](https://user-images.githubusercontent.com/587583/83203756-0a695000-a0ff-11ea-8b89-b6dca901eb37.png)

## Desired behavior
Instead of regular form-intro, [**Veteran-deceased alert**](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/409068827) should be displayed:
![Screen Shot 2020-05-28 at 4 51 57 PM](https://user-images.githubusercontent.com/587583/83205527-9f6e4800-a103-11ea-9ebd-8cbbe1243359.png)

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by bradl3yC** [comment]
@tlei123 this is ready to validate in staging

**Comment by bradl3yC** [comment]
@tlei123 Can we validate?
