### ISSUE TITLE
Verification: 10-10d needs param store update with VA Notify template ID

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96260]
As a CHAMPVA applicant, I need to receive an email confirmation after I submit my form so that I know it was received.

Related to [this user story](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/94365)
Currently, 10-10d submits in prod don't trigger a confirmation email and the template activity in VA notify shows that it's never been triggered.

### Acceptance criteria

Production param store is updated with the 10-10d VA Notify template ID so that notifications work correctly in prod.

**Comment by michaelclement** [comment]
Production email template ID added to AWS param store.

**Comment by michaelclement** [comment]
Currently, I'm able to successfully trigger the email via Postman. However, I've done two submits on production and neither of them have triggered the email. This leads me to believe that the issue is something other than the param store. Going to keep looking

**Comment by michaelclement** [comment]
Looks like we're just waiting for the daily deploy and then the updated param should be live.

**Comment by baltes** [comment]
I got an email after another submit, looks like we should be good.
