### ISSUE TITLE
[Bug] MDT - Vet-not-in-database alert no displayed

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9626]
## What happened?
On Staging **Order hearing aid batteries and accessories** form, Veteran-not-in-database account-/data-scenario does not trigger expected alert.

## Specs:
- Browser-/device-agnostic
- `vets.gov.user+27@gmail.com` (William)

## Steps to Reproduce
1. Go to https://staging.va.gov/
1. Sign-in via **ID.me** as **`vets.gov.user+27@gmail.com`** (William).
1. Go to https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
1. Observe that regular form-intro is displayed, instead of Veteran-not-in-database alert.

### Regular form-intro
![Screen Shot 2020-05-28 at 4 18 53 PM](https://user-images.githubusercontent.com/587583/83203756-0a695000-a0ff-11ea-8b89-b6dca901eb37.png)

## Desired behavior
Instead of regular form-intro, [**Veteran-not-in-database alert**](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/409462681) should be displayed:
![Screen Shot 2020-05-28 at 5 29 41 PM](https://user-images.githubusercontent.com/587583/83208044-85376880-a109-11ea-82c4-70ec86b2f70e.png)

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
@bradl3yC  - Can you please see if you can replicate | and if this is the test user fo rthis story

**Comment by bradl3yC** [comment]
@tlei123 @leahkeeler this is happening because user 27 is returning a 500 error - we really need to handle this error gracefully and right now we aren't.  Perhaps we need to put a diff error block up there.

@rebeccawalsh @rileyorr do you have any thoughts on this?  A generic error for when the MDOT service is not responding appropriately ?

**Comment by rileyorr** [comment]
Hey, everyone! Thank you for making me aware of this bug. I've [created a ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9782)to look into this issue and design an alert for Error 500 (internal server error).

**Comment by bradl3yC** [comment]
@tlei123 this has been resolved - let me know when you plan on testing so I can verify the DLC API is up and running.

**Comment by bradl3yC** [comment]
@tlei123 Can we validate?
