### ISSUE TITLE
Project Kickoff: School Ratings

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9627]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([School Ratings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/product-outline.md))
- Explanation of the problem space
_When Veterans are looking for schools within the Comparison tool, they want to know about the experiences of other Veterans to form a better understanding of what their personal experience at the school would be like. Ratings enable Veterans to quickly assess the suitability of a school (both pro and con), bolstering their confidence and level of comfort in deciding if a particular school is right for them._
- [Historical Rating Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/EDU%20Historical%20Rating%20Documentation.zip)

## Meeting attendees from **requesting team**
- Product Manager (required): Darrell Neel @dneel-bah 
- DEPO Product Lead (required): Mat Self @mattpointzxer0 
- Entire VFS team (recommended): Amy Knox @amyknox, Desiree Turner @desireeturner, Dan Shawkey @shawkey-daniel, Will McCormack @WillMcCormack, Cindy Cruz @ccruzgra, Jen Jones @JenLJ, Michael Delli-Gatti @delli-gatti-michael, Adam Sonntag @sonntag-adam 

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES

## Scheduling
11-12 on Tuesday 6/2 works for our team
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

**Comment by meganhkelley** [comment]
Scheduled 6/2

**Comment by dneel-bah** [comment]
Meeting held; closing out ticket.
