### ISSUE TITLE
Add LOA1 pattern from VADS to Appoint v2 designs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96282]
## Background
We have early designs for the LOA1 experience in our Appoint v2 designs, but they were just [formalized in the VA Design System](https://design.va.gov/components/alert/alert-sign-in/) (and Figma) and we can rally around these! 

## Tasks
- [ ] Update Appoint v2 LOA1 designs to match the VADS standard

## Acceptance Criteria
- [ ] LOA1 users will have an experience in Appoint v2, that matches the platform standard on VA.gov.

**Comment by mtri** [comment]
Requested CAIA content assistance here https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809#issuecomment-2276682129

**Comment by mtri** [comment]
Received new content https://github.com/department-of-veterans-affairs/va.gov-team/issues/97026#issuecomment-2479541598

**Comment by mtri** [comment]
LOA 1 content has been added to v2 Introduction page
[Mobile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=3717-80885&node-type=frame&t=dLnmeCzGTFF6iP97-11)
[Desktop](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=3717-80753&node-type=frame&t=dLnmeCzGTFF6iP97-11)

LOA1 verification screens for v2 Appoint have their own page in Figma here:
[Appoint a Rep v2 – LOA1 Verification](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=12774-720792&node-type=canvas&t=dLnmeCzGTFF6iP97-11)
