### ISSUE TITLE
Qualitative Data Request: Debt Portal - Summary and VHA copay pages only, fiscal year 2023-2024

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#96285]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

10/01/2023

### Date Range End

09/30/2024

### Product Name(s)

Debt portal, VHA copay path

### Product Description

Debt portal VHA copay path

Hi Sarifa,

I'd like to look at **all** data for the **fiscal year** for the **overview pages and VHA copay pages only.** 

I've included the links below. Please include all data. 

Thank you

### Survey URL(s), key term(s), case category or type

VBA and/or VHA copay path

**https://va.gov/manage-va-debt
https://va.gov/manage-va-debt/summary
https://va.gov/manage-va-debt/
https://va.gov/manage-va-debt/summary
https://va.gov/manage-va-debt/
https://va.gov/manage-va-debt/summary/**

VHA copay path

**https://va.gov/manage-va-debt/summary/copay-balances
https://va.gov/manage-va-debt/summary/copay-balances/**

Links that are collecting Medallia data with custom URLS:

**[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement/](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement/)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement)
https://va.gov/manage-va-debt/summary/copay-balances
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement)**

### Sub URLs

Yes

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charlotte.cesana@va.gov, Denise.Coveyduc@va.gov, megan.crigger@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.

**Comment by charlottecesana** [comment]
Thank you!

**Comment by newworld2616** [comment]
Anytime!
