### ISSUE TITLE
Contact Center Review for Benefits Decision Review - Board Appeal NOD Email Error Notifications

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#96287]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Board Appeal Notice of Disagreement (NOD) is for Veterans to appeal a decision to a Veterans Law Judge at the Board of Veterans’ Appeals (also called the Board) in Washington, D.C. A judge who’s an expert in Veterans law will review their case. We've made updates to the email error notifications for form failures

### Launch Date
Ready to launch. Date TBD

### Version Number
Oct 2024

### Product Guide
[NOD Product Guide](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B9C7EE6C7-7BB1-4108-83CB-89F60DCC2502%7D&file=Board%20Appeal%20NOD%20Product%20Guide%20(2024).docx&action=default&mobileredirect=true)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @comaurice. Same on this one; if you could please attach the draft here as a Word doc. Thanks!

**Comment by comaurice** [comment]
Absolutely! Here's the word file [Board Appeal NOD Product Guide (2024).docx](https://github.com/user-attachments/files/17602781/Board.Appeal.NOD.Product.Guide.2024.docx)
@starlow00 thank you

**Comment by starlow00** [comment]
The draft looks good; sending it for VEO review.

**Comment by starlow00** [comment]
No changes from VEO; a working copy is attached for future revisions. Thank you!
[BoardAppeal_NoticeofDisagreement_ProductGuide_v2_SRT_11042024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a76af8e2a999ecd4bae3feade9b681d17de6171/BoardAppeal_NoticeofDisagreement_ProductGuide_v2_SRT_11042024.docx)
