### ISSUE TITLE
Designers: Attend breakout session

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#963]
Samara/Arthur please complete the item below and check the radio button and comment done when completed. 

- [x] Designers: Attend breakout session

## User Story
As a designer, I need participate in a breakout session so I can properly be on-boarded to the team.

## Goal
Attend breakout session for designers

## Acceptance Criteria
Breakout session needs to be completed with VSP team. 

## Definition of Done
- [ To be completed in Sprint 2 ] 
- [ This relates to epic ticket #863 ]

**Comment by Samara-Strauss** [comment]
Yep, I was there.

**Comment by artistgreen** [comment]
I was there.

**Comment by Justin-Pickett** [comment]
A.E. design team members have completed this task. Closing this ticket.
