### ISSUE TITLE
[CAIA Intake] <govcio-vebt>: <GI Bill School Feedback Tool: Step 4 Information Enhancement Initiative>

### ISSUE THREAD

**Issue by arianaadili** [department-of-veterans-affairs/va.gov-team#96307]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.

## Your team

- **Product name:** GI Bill School Feedback Tool
- **Team name**: govcio-vebt
- **OCTO product owner:** Darla van Nieukerk
- **Product manager:** Kara Ciprich (kara.ciprich@va.gov), Lexi Betz @alexisbetz 
- **Designer(s):** @arianaadili 
- **Slack channel:** [govcio-vebt-team](https://dsva.slack.com/archives/C0792CZTZJ5)

## CAIA specialists involved
_Filled out by CAIA_
- **IA:** 
- **Content:** 
- **Accessibility:** 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [x] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  

### What's the nature of your initiative and desired outcomes?
I am working on enhancing the [GI Bill Feedback Tool,](https://www.va.gov/education/submit-school-feedback/introduction) specifically focusing on _Step 4_ out of 5, which involves feedback options and information. The goal of this initiative is to improve user understanding and accessibility of the feedback options available to Veterans who want to report feedback on their school. By adding clear, informative text to each feedback option, I aim to create a more user-friendly experience that encourages meaningful feedback. Ultimately, this will lead to more accurate insights into student Veterans' concerns. 

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content. FOR FIGMA/MURAL: please tell us which screens/board/section to look at so we don't leave comments on old stuff. 
- [Figma wireframe](https://www.figma.com/design/Jc95SADaR8N2vrAb91GDwT/VEBT-745-FT-Step-4-Redesign?node-id=0-1&t=PDqMbbnCUa6m8uDM-1) (one screen)

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No - _This request was made by our stakeholder to enhance the context of this page._
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

The page is currently in production, but I have created a wireframe in Figma to illustrate my ideas for enhancing it. I propose changing the radio buttons to tile components, as seen in the left image (current version) compared to the right image (my proposed design).

From a UX perspective, using tile components can significantly improve user engagement and comprehension. Firstly, tiles can provide a more visually appealing layout, making it easier for users to scan and identify the feedback options. Secondly, the larger clickable area of tiles can enhance accessibility, allowing users to select their feedback options with greater ease, especially on mobile devices. This design change aims to create a more intuitive and user-friendly experience for veterans who want to report feedback on their school. *My deadline for this initiative is before November 19th, but completing it before November 13th would be ideal.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

## Next steps
- [x] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [x] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document). **I do not have a document to share as I don't think this is necessary for this initiative**
- [ ] Please don't close this intake when work is complete - CAIA will close and track

**Comment by NaomiPMC** [comment]
@aprocik1 & @NaomiPMC  to review with Danielle.

**Comment by arianaadili** [comment]
@NaomiPMC this ticket can be closed. It is no longer needed. Thank you
