### ISSUE TITLE
Date of birth rendering incorrectly

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/va.gov-team#96305]
## What happened?
Date of birth is only rendering month information.

**Describe what went wrong**:
`renderDOB` function in `src/platform/user/profile/vap-svc/util/personal-information/personalInformationUtils.js` is only returning the month

Issue started when [momentjs was removed](https://github.com/department-of-veterans-affairs/vets-website/pull/32324) from vets-website

**Add the steps to reproduce the bug**:

1. Login
2. Navigate to Profile -> Personal Information

**Add a screen recording or photo**:
![Image](https://github.com/user-attachments/assets/bd86bb93-6600-4ed2-a287-8adeff26984f)

## How severe is the problem?

- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP.
- [X] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint.

## What is the desired behavior?

1. A user sees their date of birth correctly formatted

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by asiisii** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96258#issuecomment-2455536306
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96258#issuecomment-2455547670
here are the comments about the validation of the ticket
