### ISSUE TITLE
Changing headings to questions - Part 2

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#96300]
## Task Description
This follows our model of asking questions when a user needs to make a choice for the pages at the start of the scheduling flow:

- Type of eye care page (after you select Eye care on Type of care)
- Type of sleep care page (after you select Sleep medicine on Type of care)
- Type of audiology care page (after you select Audiology and speech on Type of care, then Community care facility on Type of facility)

## Notes and References
N/a

## Acceptance Criteria
- [x] Review changes with Content SME
- [x] Design file ready for dev

## Deliverables
- [Design Link ](https://www.figma.com/design/5dWfMQkBCvEX9XYJsNdcT3/Change-direct-schedule-headings-to-questions-%7C-Appointments-FE?node-id=233-8241&t=YlBr3oYZNXjHrAaq-1)

**Comment by Cieramaddox** [comment]
@outerpress Content changes are ready for your review. When you approve, we can ping Content for a review.

**Comment by outerpress** [comment]
@Cieramaddox I dropped in two small comments unrelated to content, otherwise looks good to me!

**Comment by Cieramaddox** [comment]
@outerpress Okay, this is complete (from a design standpoint) and ready to rock and roll to the capable hands of the devs.

**Comment by outerpress** [comment]
@Cieramaddox Thanks! I created dev ticket #99201 for this work

**Comment by outerpress** [comment]
Dev work is done, closing
