### ISSUE TITLE
Architecture Intent page - update a link currently pointing to JIRA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#96315]
### Description
Within the [Architecture Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent) page in the [Preparing for the Architecture Intent section](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#ArchitectureIntent-PreparingfortheArchitectureIntent), there is a link to a Jira document that most teams may not have access, within the first bullet sentence "You have questions about one or more points on the [template below](https://vfs.atlassian.net/wiki/spaces/CC/pages/edit-v2/3460136961#What-artifacts-will-be-needed%3F)."
I am guessing that the link should be pointing to the GH [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md) document that is also linked elsewhere on the page.  

### Relevant URLs
[Architecture Intent page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by jknipes** [comment]
Hi @hdjustice, thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
@hdjustice - Thank you for calling our attention to this - it appears the linked page was still in Edit mode. We'll update it and deploy it with a working link Monday afternoon.

Closing this ticket as _Done_
