### ISSUE TITLE
COVID Notification missing from Comparison Tool

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#9632]
## What happened?
On the GIBCT Landing Page, the COVID notification implemented in #9257 should be displayed. Currently it is not

## Steps to Reproduce
- Access The GI Bill Comparison Tool Landing Page at https://staging.va.gov/gi-bill-comparison-tool

## Desired behavior
![Screen Shot 2020-05-27 at 12.08.50 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2483a369-d45f-4795-a226-d6b65e7e8507)

## Acceptance Criteria
- [ ] Banner is present only on the landing page

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/12859

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-29 at 2.33.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/65c4a2e7-e005-4cf3-8435-c1f660754ea3)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxba in staging.

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this looks good to go!

**Comment by sonntag-adam** [comment]
Closing bug
