### ISSUE TITLE
Text change for phone appointment joining instructions

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#96349]
## Description

From CC ticket #88453 : Change the phone appointment joining instructions on upcoming appt details page. Current state:

![Image](https://github.com/user-attachments/assets/d4f157f5-b6f0-49b6-8b53-e78021d34416)

---

## Development Checklist

- [x] Given a details page for an upcoming phone appointment, update the joining instructions to:`We'll call you at the appointment time. If you have questions or need to reschedule, contact the facility you originally scheduled through.`

### Design Assets
- N/A

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for validation.

**Comment by outerpress** [comment]
Looks good @JunTaoLuo ! Feel free to close. I updated the [feature reference](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1152-101002&t=G3nT3HSTBAN6WcFI-4)
