### ISSUE TITLE
LOA1 state for Rep Status Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96359]
## Background
We are currently showing an error state for LOA1 users, because they do not have an ICN and the ICN is required to lookup a user's active POA status.

Because there are less than 5% of users that are missing an ICN (and throwing a 500 error) we decided to launch our MVP by simply showing an error state to these users and providing a phone number for them to call and understand if they do have current representation.

Now that LOA1 patterns are finalized in the VA Design System and we have time to think about our v2 of the Widget, let's consider a true LOA1 state for these users.

## Tasks
- [ ] Create a LOA1 state for the Rep Status Widget

## Acceptance Criteria
- [ ] LOA1 users will be encouraged to verify their identity, so that they can obtain an ICN and we'll be able to understand if they have any existing representation and display that status in the Representative Status Widget.

**Comment by mtri** [comment]
[Requested CAIA content here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809#issuecomment-2491500805)

**Comment by mtri** [comment]
Verified content is good to go with CAIA.

[Updated sign in alert to new convention](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1411-386887&node-type=frame&t=xmsm8ysS2pOU61g4-11)
[Verification alerts w/ CAIA content](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13016-114226&node-type=frame&t=xmsm8ysS2pOU61g4-11)
