### ISSUE TITLE
Verify doctype mapping in 10-10d supporting doc metadata

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96358]
Currently supporting docs included with 10-10d submits don't carry a consistent document type from dropdown selection to the PEGA interface. For example:
- A document uploaded as a marriage license shows in PEGA as "Medicare"
- A document uploaded as back of medicare card shows in PEGA as "OHI Certificate"
- A document uploaded as back of other health insurance card shows in PEGA as "OHI Certificate"
- A document uploaded as front of other health insurance card shows in PEGA as "OHI Certificate"
- A document uploaded as a birth certificate shows in PEGA as "Marriage Document"
- A document uploaded as a social security card shows as "Miscellaneous Documents"
- A document uploaded as a 10-7959c shows in PEGA as "School Certificate"
- A document uploaded as adoption paper shows in PEGA as "Miscellaneous Documents"
- A document uploaded as a school certificate shows in PEGA as "Miscellaneous Documents"

This one appears correct
- A document uploaded as front of medicare card shows in PEGA as "Medicare"
 
This ticket isn't intended to fix any mapping downstream, but we need to confirm that we're sending the correct doctype.

#### Screenshots for reference
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7222353a3c5e3d6ac3887cf2f772f367d08dd751/image.png" alt="image.png" />

<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9QQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2995f6d6650fcaedd5f2f0cac9f63596e3172f8f/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFNQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--161c64b1ed507ba89c2159f17c89e26934f690de/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85a4573402242472f49866bf57f544a189bfba2a/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6d7998ad18a6b27a936d6af95dbef1dc7c5de3d/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1QQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22cd8c06162498f3973a796fbfb4454997a7b6ff/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6600b68491913aa9ec775e93635d4a24e2b54be0/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHVQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49e7ae29a03fe3e43d2d7f7444a74484aa7acf09/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3680964cf0677d9ec0cf138ffd0eca5888712e2c/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be8971bb6c895370713b42fa7afbafb8920f85c6/image.png" alt="image.png" />
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNCtQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3428cc89d077d331cf59caa33a4e59d8dbd5718/image.png" alt="image.png" />

**Comment by michaelclement** [comment]
Reached out to Cindy to try and better understand the problem. For documentation's sake, when I submit a form with attachments locally this is what the attachments array looks like:
```javascript
[ 
  "vha_10_10d",
  "School enrollment certification form",
  "Enrollment letter",
  "Front of Medicare Parts A or B card",
  "Back of Medicare Parts A or B card",
  "Front of Medicare Part D card",
  "Back of Medicare Part D card",
  "Front of health insurance card(s)",
  "Back of health insurance card(s)",
  "VA form 10-7959c",
  "Birth certificate",
  "Social Security card"
]
```

These labels line up with what I had previously sent to Cindy, so it's unclear if there's an error in the Pega logic that reads the categorization or if our metadata is getting malformed somehow (which seems unlikely).

I'll update here as things progress.

**Comment by michaelclement** [comment]
Talked with Cindy further, we're not seeing consistent failures on this (i.e., we were able to submit multiple 10-10D's on staging and have the attachments be properly categorized in UAT).

@cloudmagic80 will be submitting a followup 10-10d that should match exactly the one that Bo submitted when this error was first noticed, and we'll see what that looks like.

**Comment by cloudmagic80** [comment]
When a document is attached, the website uses the PersistentAttachments method to record it in the backend. The attachments are handled synchronously, and their order cannot be altered.

The issue with inconsistent document types arises when uploading optional documents, specifically Social Security and birth certificates. These optional documents are uploaded before the required ones, but their document types are appended to the end of the array.

This becomes even more complex when multiple applicants upload Social Security cards, birth certificates, and other required documents, leading to additional inconsistencies.

**Comment by cloudmagic80** [comment]
PR Made. 
https://github.com/department-of-veterans-affairs/vets-website/pull/33189#pullrequestreview-2462524039
testing done for 1 applicant, 2 applicants, 3 applicants, and 4 applicants.
Use case:relationship to application:
spouse, child, and 3rd party

applicant died.
biological child
18 and 23 and enrolled in school

1 applicant, 1 sponsor, spouse or partner,
medicare A, medicare D, Other Health, 7959c,

**Comment by michaelclement** [comment]
This has been reviewed by platform and merged.

**Comment by michaelclement** [comment]
[New backend fix here](https://github.com/department-of-veterans-affairs/vets-api/pull/19647) - still working on testing (cc @cloudmagic80 @baltes @andrea-merrill )

**Comment by michaelclement** [comment]
Fix is done and has been tested. Only thing left to do is to deploy it, which we'll queue up for Monday when the code freeze is lifted.

**Comment by baltes** [comment]
Carrying this over since we seem to still have things to look into.

**Comment by michaelclement** [comment]
Issue is fixed as of [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19712).
