### ISSUE TITLE
Mention representative type in search results and selection

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96360]
## Background
We received some feedback from our stakeholders in the last Sprint 6 Demo, where it's not totally clear when a searched/selected representative is an attorney or claims agent.

VSO Representatives are more obvious because there is a mention of the associated organization(s), but is there a way to confirm rep types to users in search results. Possibly after selection too, as the representative cards come up in these pages:
1. Contact the Representative
2. Replace your Representative
3. Next Steps

We seem to have an idea of how this could be visualized in our [Rep Status Widget designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1283-176978) (I don't think this is in our v1 though), so perhaps we can riff on that idea for the Appoint v2 experience and make a comprehensive update for the next iteration of both Appoint and Widget. 

Note: it might actually best for our developers (and possibly for a unified user experience on VA.gov) if we could have some sort of "standard" way we present rep information in both the Widget and Appoint screens.

## Tasks
- [ ] Add in representative type where appropriate in the Appoint v2 design

## Acceptance Criteria
- [ ] Users are able to confirm their representative type (not just the name) when searching and selecting in the Appoint a Rep experience.

**Comment by mtri** [comment]
Waiting on final CAIA copy.

After new CAIA copy comes in:
- [Updating the representative replacement page to align with the two cards](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=12569-674307&node-type=frame&t=x9qq1GiDwT7lYPUP-11) (as opposed to using the widget for the grey card and a unique instance for the other.
- [Displaying rep type and flattening unnecessary variations across products](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=12704-711917&node-type=canvas&t=x9qq1GiDwT7lYPUP-11)

**Comment by mtri** [comment]
This has been added in as a part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/96824
