### ISSUE TITLE
Bump the Sidekiq retry limit up to support longer outages

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#96372]
The COLA event this year will occur on Saturday 11/16 starting at ~4am ET and run through Sunday 11/17 at ~7pm ET, we need to update our retry parameters so we don't lose transactions on 11/16. 

- [ ] change retries from 14(or anything under 16) -> 16 everywhere that is applicable

[Slack thread](https://dsva.slack.com/archives/C053U7BUT27/p1730731734405619)

**Notes**
Given that COLA happens every year, the changes should be extended permanently

[Michael Harlow via Steve Albers:](https://dsva.slack.com/archives/C053U7BUT27/p1730908938884649?thread_ts=1730731734.405619&cid=C053U7BUT27)

- Lighthouse can handle extended downstream outages for APIs that have async processing.
- [Benefits Intake](https://developer.va.gov/explore/api/benefits-intake)
- [Benefits Documents](https://developer.va.gov/explore/api/benefits-documents)
- The other LH APIs require consumers to either block transactions at the source or allow extended retries during outages exceeding 24 hours. So for [VA.gov](http://va.gov/), this COLA event should be handled like last year's that hit EVSS.

**Comment by kylesoskin** [comment]
Completed with https://github.com/department-of-veterans-affairs/vets-api/pull/19341
