### ISSUE TITLE
Identify SNOW Workflow process

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#96370]
## Issue Description
Service Now is the newest tool the Veteran Support team has been tasked with to manage technical issues.  A process must be created for the SNOW CRM to improve our services continuously. 
---
## Tasks
- [ x] Create a process for the Veteran Support Team to work in the SNOW CRM comfortably
- [ x ] Timeline must be established 

## Acceptance Criteria
- [ x] The process clearly and accurately reflects the department’s core functions and values.
- [ x] Key responsibilities or activities of the department are visually represented using appropriate symbols or icons.
- [ x] Team members must be able to use documents for training
- [   ] Document published to Veteran Support Confluence folder 
- [ x] Document published to Veteran Support Teams on the VA side 

## How to configure this issue
- [ x] **Attached to an Epic** (what body of work is this a part of?)

**Comment by Kimberley2023-CSM** [comment]
John and Kim are working together on[ this document](https://docs.google.com/document/d/1JxPcTK3wcUHotk81oGMg3lqhoyfxWfBq2JKTJZtK3-E/edit?usp=sharing) for the SNOW process.

**Comment by Kimberley2023-CSM** [comment]
* discuss templates (if new ones need to be created specifically for SNOW.

**Comment by ATMiddleton** [comment]
Team member needs access to Zen Hub/Git Hub

**Comment by Kimberley2023-CSM** [comment]
@Kimberley2023-CSM reviewed document, added comment.  Please review and advise.

**Comment by Kimberley2023-CSM** [comment]
@starlow00 can you review process and make any needed modifications as you see fit and then publish in TEAMS channel.

**Comment by starlow00** [comment]
Will do.

From: Kimberley2023-CSM ***@***.***>
Sent: Wednesday, December 11, 2024 10:34 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: TARLOW, STEVEN R. (ODDBALL INC) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Identify SNOW Workflow process (Issue #96370)


@starlow00<https://github.com/starlow00> can you review process and make any needed modifications as you see fit and then publish in TEAMS channel.

-

**Comment by starlow00** [comment]
Sent permission to edit request to document owner (@Kimberley2023-CSM and @Jcorcoran9 ).

**Comment by starlow00** [comment]
Maybe it was @ATMiddleton (see previous comment).

**Comment by ATMiddleton** [comment]
@starlow00 has access as of 12/11/24

**Comment by starlow00** [comment]
The document looks good, @Kimberley2023-CSM

**Comment by starlow00** [comment]
@Kimberley2023-CSM @Jcorcoran9 It appears all criteria have been met, but I have not closed because of the step about publishing to Confluence. I'll leave that for you.

**Comment by starlow00** [comment]
Will be posted to Confluence by EOS.
