### ISSUE TITLE
[Frontend] Order in Progress Card - Content (U)

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9638]
Verify if the verbiage is generated by forms system - if it is not, change verbiage per design.

**Comment by mr0sari0** [comment]
Adding screenshots for reference

This is how the link currently looks:
![image (1)](https://user-images.githubusercontent.com/12755283/83429744-7ea73a80-a402-11ea-8965-d90e6eee21f8.png)

This is what we want to update the link to:

![image (2)](https://user-images.githubusercontent.com/12755283/83429839-abf3e880-a402-11ea-9a96-c2c0482ca09f.png)

**Comment by mr0sari0** [comment]
The wording for the link is part of the form system's code. Checking to see if it would be okay to change it...
