### ISSUE TITLE
Investigate issues with KMS encrypted records [Part 1 of 2]

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#96409]
## User Story
As the owners of the KMS encryption for the ActiveRecord Queries and Postgres DB,
we need to identify and resolve records that have encrypted data but a nil KMS key,
OR if records have decryption issues,
so that we ensure data integrity and prevent potential issues with data access or encryption consistency.

## Issue Description

In [follow-up to this issue](https://github.com/department-of-veterans-affairs/vets-api/pull/19199), we identified records with encrypted data but a nil KMS key. These may be legacy records that weren’t fully migrated from the original attr_encrypted integration. Currently, only one such record exists, but further investigation is warranted. Deletion of the record may also be a viable option.

Additionally, we've identified a number of records (5 total) that are unable to be decrypted. It may be related to corrupted data, and deserve investigation. All of the records are still on the `v2023` version of the `encrypted_kms_key`, so they haven't been rotated since the October 12, 2024 key rotation.

```
models.each do |model|
   model = MODELS_FOR_QUERY[model.name] if MODELS_FOR_QUERY.key?(model.name)
   puts ‘#{model.name}-‘ model.where.not('encrypted_kms_key LIKE ?',   "v#{KmsEncryptedModelPatch.kms_version}:%").count
 end


UserCredentialEmail -1 [6336758]
Pensions::SavedClaim - 4 [9525415, 9526128, 9526162, 9526770]
SavedClaim::Pension - 4 [9525415, 9526128, 9526162, 9526770]

Note: SavedClaim::Pension and Pensions::SavedClaim seem to be the same thing!
```

Here is the query that was run in prod rails console to gather records with encrypted data but a nil KMS key:

```
# Loop through each model that uses encryption
ApplicationRecord.descendants_using_encryption.each do |model|
  # Retrieve the encrypted columns for the model
  encrypted_columns = model.lockbox_attributes.keys.map { |col| "#{col}_ciphertext" }

  # Build the query to find records with nil `encrypted_kms_key` and at least one non-nil encrypted field
  query = model.where(encrypted_kms_key: nil)
               .where(
                 encrypted_columns.map { |col| model.arel_table[col].not_eq(nil) }.reduce(:or)
               )

  # Check if any records match the query
  if query.exists?
    puts "Model #{model.name} has records with nil encrypted_kms_key and non-nil encrypted fields."
    puts "Record IDs: #{query.pluck(:id)}"
  else
    puts "Model #{model.name} has no records with nil encrypted_kms_key and non-nil encrypted fields."
  end
end
```

Additionally, there is still a PG Query duraton spike during the 3-5am window. While there are some decryption errors, it seems to be unrelated. It may be related to the Vye::MidnightRun::IngressTimsChunk job [where you can see the errors here](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20status%3A%28error%20OR%20critical%29%20host%3Avets-api-sidekiq%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZMA_looXaVHgwAAAAAAAAAYAAAAAEFaTUFfbkE1QUFEVjcyMXM3Y3R6QWdBQQAAACQAAAAAMDE5MzAxMDYtMjQzMy00ZTY1LWExM2ItZWZjZjY4Y2Q0OGMy&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1730887800000&to_ts=1730890020000&live=false)

## Acceptance Criteria
- [x] Check all models for records with nil encrypted_kms_key and non-nil encrypted data.
- [x] Investigate and mitigate (if possible) records with decryption issues
- [x] Confirm if these records are legacy items or can be deleted 
- [x] Confirm no new records are created with nil KMS keys and encrypted data.
- [x] Investigate PG Query spike for the 3-5am window
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
The Pensions and Burial Claims team is [looking into the decryption issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96639) for the `Pensions::SavedClaim` records

**Comment by LindseySaari** [comment]
Reached out the [EDM team here](https://dsva.slack.com/archives/C075AKQQANS/p1731007172496189)

**Comment by LindseySaari** [comment]
The SavedClaim::Pension records have been deleted [after permission from the team](https://dsva.slack.com/archives/C05MS96P6P2/p1731014316868609?thread_ts=1731013389.334189&cid=C05MS96P6P2)

**Comment by LindseySaari** [comment]
I checked with the Identity team on how to proceed with the corrupted UserCredential record. Additionally, I reached out to VYE team to take a look at the `Vye::MidnightRun::IngressTimsChunk` job - https://dsva.slack.com/archives/C05PUBWTEHM/p1731008408902279

**Comment by AshleyGuerrant** [comment]
Test comment.

**Comment by LindseySaari** [comment]
The corrupted records have been deleted. I noticed an issue with a 686c job and saw some error logs for the `BGS::SubmitForm686cJob` There's a [large number of them over the past day](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20status%3A%28error%20OR%20critical%29%20host%3Avets-api-sidekiq%2A%20%22value%20too%20large%20for%20column%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1731852902872&to_ts=1731939302872&live=true). Matthew Knight and team has been alerted

**Comment by LindseySaari** [comment]
The VYE team has also added the `Vye::MidnightRun::IngressTimsChunk` [issue to their sprint starting on November 19](https://dsva.slack.com/archives/C05PUBWTEHM/p1731515315901689)

**Comment by LindseySaari** [comment]
Continuing to look into the query spike culprits. Issues with the corrupted encrypted records have been taken care of
