### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by mpeterz** [department-of-veterans-affairs/va.gov-team#9640]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please link this issue to the DSVA Slack channel #vfs-platform-support, add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

**Meg.Peters@VA.gov is requesting access to Google Analytics. I'm a new DEPO employee, a UX designer and IA.

I have a Google account with my VA.gov email and also a Google Analytics account. 
(Not sure how to add VSP Analytics & Insights to my message.)**

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
**Look at VA.gov analytics and run my own reports.** 

## Date Required
**Ideally June 1. (Thank you!)**

## Product Team / External Team / VA Office
**DEPO - Digital Experience Program Office**

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
@mpeterz added you to GA! You should receive an invite email. Let us know if you're squared away here, or if you have any questions. 

You can find additional VA.gov GA support [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/google-analytics).

**Comment by jonwehausen** [comment]
Thanks Joanne! Verified with Meg she is able to access the audience overview report as a test.
