### ISSUE TITLE
vets-api ssl issue connecting to www.vba.va.gov

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#9642]
## Issue Description
Vets-api scrapes the vaforms pages on va.gov, which has links to the actual forms, then takse the url of the actual form (this case on www.vba.va.gov) and runs a sha256 on it to see if it has changed from what waspreviously saved to know if there is a new version available.

Vets-api cannot reach www.vba.va.gov due to ssl errors. It is suspected that vets-api has been unable to connect to vba since the move to docker.

## Acceptance Criteria
- [x] vets-api can reach www.vba.va.gov
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@tskinn is this still an issue, if so can we add language around having this go through the FWD proxy.

**Comment by tskinn** [comment]
This is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/9644
