### ISSUE TITLE
Integrate referral mock

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#96439]
The mock was created in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95262
This ticket is to create a all of the boilerplate required to make the API call and store/retrieve in redux. 

 - [ ] ~~add param to include referrals to `fetchFutureAppointments` i.e. `fetchFutureAppointments({ includeRequests = true, includeReferrals = false } = {})` then add an additional promise to also fetch referrals if true.~~ We will no longer need this bit with the count going away. 
 - [ ] ~~Pass a true value for `includeReferrals` in `fetchFutureAppointments` if feature is on~~
 - [ ] Follow the same pattern to add `includeReferrals` to `fetchPendingAppointments`
 - [ ] Create selector and action for single referral fetch. Look at appointment details single appointment fetch to follow for an example

**Comment by loripusey** [comment]
@brianseek @wullaski can you point please?

**Comment by brianseek** [comment]
> [@brianseek](https://github.com/brianseek) [@wullaski](https://github.com/wullaski) can you point please?

Some details are still TBD. Will add more after meeting with Simi today. Then we can point.

**Comment by brianseek** [comment]
This is merged moving to closed since there is no further validation needed
