### ISSUE TITLE
Update SM sign-in widget with VADS components

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#96467]
### User story

As a Veteran, I want the sign-in widget experience on the unauthenticated Secure Messages page to offer the latest design-system content, so that i can have a consistent experience across all the unauthed tool pages. 

### Notes
- VADS/component updates shared with other mhv-widget using pages (see sibling tickets for overlap)
- Unauthed page: www.va.gov/health-care/secure-messaging/
- The needed changes are [documented in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/transition/benefit-hub-page-updates.md)
- VADS/DST will provide the components, which are already [documented in VADS](https://design.va.gov/components/alert/alert-sign-in/) (but not yet implemented as of 11/14)
  - update: Identity team built the special buttons with Id.me/login.gov branding, they are separate from DST "content components" ([slack thread](https://dsva.slack.com/archives/C068QM7CCKG/p1732632501361649?thread_ts=1731017509.219269&cid=C068QM7CCKG))
- See [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97279) for more context

## Possible tasks

- After updating the mhv-widget and uncovering what additional work is needed to add to other unauth pages, update the sibling tickets on the Epic

## Acceptance criteria

- [ ] DECIDED whether to use Carlos's new model or work in the old widget approach/files
  - Tradeoffs include: ease of modification, where/how to test prior to production (toggle vs drupal preview), how to deal with the page-content-inside-widget quirk of these pages, etc
- [ ] ?? (asked Sara in comment) Removed "Create an MHV account" alert that currently shows for verified users without an MHV UUID
- [ ] Content of Secure Messages widget updated to VADS standard per UX design
    - [ ] Initial "please sign in" content – use out of the box VADS component without customization
    - [ ] "Verify your identity" content – use out of the box VADS component without customization
      - Test to ensure it works properly for Login.gov and ID.me credentials
    - [ ] "Sign in with a different acct" – use out of the box VADS component without customization
    - [ ] Last screen – All Veterans who are signed in and have LOA3 credentials are given a single CTA link to the Appts tool on VA.gov, even if they have an Oracle facility in their profile. They no longer see an OH/Cerner routing alert on the unauth page. 
- [ ] Informed CAIA to add widgets to Drupal and test in a Drupal Preview environment
- [ ] QA review
- [ ] A11y review

**Comment by wesrowe** [comment]
@sterkenburgsara, during refinement I signed into the unauthed SM page using User 0 and saw an alert I didn't recognize. It said something like "You need to create an MHV account." I think it might be an equivalent of the landing page's "Register" alert. Are you aware of it? And should we get rid of it?

(Unfortunately I didn't get a screenshot, and now I can't reproduce it – probably because the Acct Creation API "registered" the user in the background.)

**Comment by sterkenburgsara** [comment]
Hmm…both interesting & frustrating bc Florence and I just followed up with
the teams in Slack to get answers to as to how the apps are handling this
and no teams reported that they had an error like this in their apps. I
would love to get a pic of it? Or follow up and ask again? I’d say yes we
should remove as part of account creation API work, but may be difficult if
we can’t point to what it looks like.

I’ll try to replicate on Monday.

**Comment by wesrowe** [comment]
Discovery on the implementation side determined that tool-specific tickets are not generally necessary. Superseded by more appropriate tickets.
