### ISSUE TITLE
Get Platform Access to Lighthouse Roster for Onboarding for Lighthouse

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#96472]
## Description 
We have created a YAML template for LH onboarding. We just need access to the Lighthouse roster. 
---

## Definition of Done
All tasks below complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Gain access to the LH roster

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Will not receive the list in time for this sprint, moving to next. Chatted with Andrea about it.

**Comment by GWright321** [comment]
I spoke with Aubrey Suter and was directed to request access to the LH [list](https://confluence.devops.va.gov/display/VAExternal/Who%27s+Who+-+API+Lighthouse+Program). I’ve since received access and am now waiting for confirmation from my team that everyone has the necessary access as well.
