### ISSUE TITLE
Update Error on which VA facility would you like to go to page

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#96482]
## Description
Update Error on which VA facility would you like to go to page
**Error can be reproduced**:  when there's an error with any of the backend calls.

**Current Alert state**:
![Image](https://github.com/user-attachments/assets/b84a8499-fc1e-4dcf-a6cd-4d025bc50b28)

**Desired Alert state**:
![Image](https://github.com/user-attachments/assets/476fcba0-57a1-497c-bdbd-f85f9b2faa75)

**Content**: 
You can't schedule an appointment online right now
We're sorry. There's a problem with our system. Try again later.  If you need to schedule now, call your VA facility. Find a VA health facility

---

## Development Checklist
No toggle required for this work

- [ ] Alert is updated.
- [ ]  Update unit tests
- [ ]  Update/create e2e test

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by jenniemc** [comment]
@outerpress , Ready for validation. I'm happy to configure my local machine to show you the error alert message.

**Comment by outerpress** [comment]
@jenniemc I was able to find it by killing some network requests. Looks good! Feel free to close :) 

@melissa-lefevre fyi this isn't behind a feature flag so please update the screens in our feature reference and user flows
