### ISSUE TITLE
Render POA Request Detail View

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#96498]
### Description
Create the POA request detail view, excluding the "Claimant POA History" section for now

#### Implementation Details
- [ ] iterate from the restore code
- [ ] utilize mock data

This is the [VA design component library site](https://design.va.gov/components/)

Example object:
```json
{
  "status": "Pending",
  "declinedReason": null,
  "powerOfAttorneyCode": "091",
  "submittedAt": "2024-04-30T11:03:17Z",
  "acceptedOrDeclinedAt": null,
  "isAddressChangingAuthorized": false,
  "isTreatmentDisclosureAuthorized": true,
  "veteran": {
    "firstName": "Herlinda",
    "middleName": null,
    "lastName": "Kertzmann",
    "participantId": "5814279075"
  },
  "representative": {
    "email": "nyla_russel@king-skiles.example",
    "firstName": "Genaro",
    "lastName": "Thompson"
  },
  "claimant": {
    "firstName": "Earline",
    "lastName": "McGlynn",
    "participantId": "2052137776",
    "relationshipToVeteran": "Child"
  },
  "claimantAddress": {
    "city": "Reedview",
    "state": "MD",
    "zip": "16300",
    "country": "GU",
    "militaryPostOffice": null,
    "militaryPostalCode": null
  }
}
```

#### Mockups/Designs

- [detail page for POA Request](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=988-454541&node-type=frame&t=3GwsFNrbh8J1nxB2-0)

### Acceptance Criteria
- view the page 
- view mock data for veteran details

**Comment by jquispe-oddball** [comment]
screenshots of detail page in chrome - some data is hardcoded for now - social, veteran #, phone number, email:

Desktop
![Image](https://github.com/user-attachments/assets/6a4261de-0340-464c-aa12-1908aa04edf9)

Mobile
![Image](https://github.com/user-attachments/assets/3108a561-5470-4c65-9265-701fc75243f0)

**Comment by jquispe-oddball** [comment]
submitted [pr ](https://github.com/department-of-veterans-affairs/vets-website/pull/33106)

**Comment by candilemoine** [comment]
@jquispe-oddball is the PR still pending for review?

**Comment by jquispe-oddball** [comment]
yes. I know the design is going to change. Is there an approved version yet?

**Comment by candilemoine** [comment]
We're close. Should I just spin up a different task for the updates?

**Comment by jquispe-oddball** [comment]
@candilemoine I spoke to @nihil2501, let's make a new ticket for the redesign

**Comment by jquispe-oddball** [comment]
[Pr merged in](https://github.com/department-of-veterans-affairs/vets-website/pull/33106), closing ticket
