### ISSUE TITLE
Render POA Request List Item as a Card

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#96497]
### Description
Create the card design using mock data

#### Implementation Details
- [ ] iterate from the restore code
- [ ] utilize mock data

Example object:
```json
{
  "status": "Pending",
  "declinedReason": null,
  "powerOfAttorneyCode": "091",
  "submittedAt": "2024-04-30T11:03:17Z",
  "acceptedOrDeclinedAt": null,
  "isAddressChangingAuthorized": false,
  "isTreatmentDisclosureAuthorized": true,
  "veteran": {
    "firstName": "Herlinda",
    "middleName": null,
    "lastName": "Kertzmann",
    "participantId": "5814279075"
  },
  "representative": {
    "email": "nyla_russel@king-skiles.example",
    "firstName": "Genaro",
    "lastName": "Thompson"
  },
  "claimant": {
    "firstName": "Earline",
    "lastName": "McGlynn",
    "participantId": "2052137776",
    "relationshipToVeteran": "Child"
  },
  "claimantAddress": {
    "city": "Reedview",
    "state": "MD",
    "zip": "16300",
    "country": "GU",
    "militaryPostOffice": null,
    "militaryPostalCode": null
  }
}
```
Here are [cards on the VA design component library site](https://design.va.gov/components/card). We like to stick to off the shelf components, hopefully this design already does or can be made to match the component library.

#### Mockups/Designs

- [card design](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=853-95346&node-type=frame&t=3GwsFNrbh8J1nxB2-0)

#### Blockers

- approval from Lesley to confirm card design

### Acceptance Criteria
- view the page 
- view the card with mock data

**Comment by jquispe-oddball** [comment]
I have a local branch down with my stashed changes. I need [this pr](https://github.com/department-of-veterans-affairs/vets-website/pull/32933) to hit main so I can update my branch with the latest code.

Screenshot of desktop and mobile:
![Mobile](https://github.com/user-attachments/assets/f7e88a33-e550-478f-b039-a046eaa53c06)
![Desktop](https://github.com/user-attachments/assets/35ab5ace-8448-464d-a53b-2fbf642c2912)

**Comment by jquispe-oddball** [comment]
[Submitted pr ](https://github.com/department-of-veterans-affairs/vets-website/pull/33002)

**Comment by jquispe-oddball** [comment]
Merged into `main` Friday, closing ticket
