### ISSUE TITLE
Call POA Request List API from Frontend

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#96511]
### Description
Frontend will fetch data from the API endpoint.

#### Implementation Details
Use a `react-router` [data loader](https://reactrouter.com/6.28.0/start/overview#data-loading) associated with our list route. I think they recommend colocating the loader function with the route's element.

### Acceptance Criteria
- [ ] See details page for POA requests that exist in the API
- [ ] See an empty result

#### Automated Testing
- [ ] create Cypress and/or unit test that would exercise the API call and show existing POA requests
- [ ] create Cypress and/or unit test that would exercise the API call and show an empty result

**Comment by nihil2501** [comment]
Duplicative of https://github.com/department-of-veterans-affairs/va.gov-team/issues/98718
