### ISSUE TITLE
Call POA Request Detail API from Frontend

### ISSUE THREAD

**Issue by candilemoine** [department-of-veterans-affairs/va.gov-team#96512]
### Description
Frontend will fetch data from the API endpoint. Need a 404 experience designed.

#### Implementation Details
Use a `react-router` [data loader](https://reactrouter.com/6.28.0/start/overview#data-loading) associated with our details route. I think they recommend colocating the loader function with the route's element.
Can handle 404 with a nearby error boundary using [`errorElement`](https://reactrouter.com/6.28.0/route/error-element) and possibly even bubble up less expected stuff to outer error boundaries.

### Acceptance Criteria
- [ ] See details page for POA request that exists in the API
- [ ] See 404 page for POA request that does not exist in the API

#### Automated Testing
- [ ] create Cypress and/or unit test that would exercise the API call and show existing POA request
- [ ] create Cypress and/or unit test that would exercise the API call and show non-existing POA request

**Comment by candilemoine** [comment]
@nihil2501 migrate over to #98718

**Comment by nihil2501** [comment]
Duplicated by https://github.com/department-of-veterans-affairs/va.gov-team/issues/98718
