### ISSUE TITLE
Supply Reordering: Fix breadcrumb issue

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#96513]
## QA Steps/Instructions

Verify breadcrumbs are present at https://staging.va.gov/my-health/order-supplies after signing in.

email: `vets.gov.user+1@gmail.com`
password: available @ https://tud.vfs.va.gov/

**Comment by radavis** [comment]
I believe this has already been addressed. Verify at next Supply Reorder team meeting.
