### ISSUE TITLE
DCM: C123 aircraft agent orange page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#96541]
## Description
First, we need to publish a new resources and support page for the content in this legacy PDF: [C-123 Aircraft Agent Orange Exposure Claims](https://benefits.va.gov/compensation/docs/AO_C123_AFSpecialityCodesUnits.pdf)

Then, we need to update all the crosslinks on VA.gov from the legacy PDF to the new resources and support page.

**Note:** We'll need to update the "Service requirements for presumption of exposure" H3 on this page: [Agent Orange exposure and disability compensation](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/). We'll need to remove the last list of bullet points and add a crosslink to the new resources and support page.

### Step 1: Awareness
- [x] BP: Update SME on migration

### Step 2: Publish
- [x] DB: Draft with AP
- [x] DB: Share with BP
- [x] DB: Share with SME
- [x] DB: Share with ST
- [x] ST: Copyedit and publish
- [ ] MZ: Post-publish R&S checklist

### Step 3: Update
- [x] DB: Identify crosslinks
- [x] DB: Update crosslinks
- [x] DB: Publish crosslinks

## Criteria
- [x] The new resources and support page has been published on VA.gov
- [x] The crosslinks that used to direct to the PDF on the legacy site now direct to the new resources and support page on VA.gov
- [ ] The post-publish steps for new R&S pages are complete.

**Comment by aprocik1** [comment]
@d-beyer, thanks for drafting this page. Here are some notes:

- Your current H1 is 85 characters. We try to keep H1s to a maximum of 52 characters ([VADS reference](https://design.va.gov/content-style-guide/page-titles-and-section-titles#page-titles)), but sometimes that's not doable. Here are some shorter alternative H1s to consider:
  - 61 characters: Disability compensation for Air Force Reservists and Veterans
  - 72 characters: Air Force Specialty Codes and units eligible for disability compensation
- I think we should ask Beth and SMEs about including active duty v. Reserve and abroad v. in the US. These could be important distinctions that help Veterans find their information and help us make the page more scannable. Reference the draft V2 for a recommendation on how to use progressive disclosure (accordions) on this page.
- We should ask Beth if she discussed this page with Danielle: [Agent Orange exposure and disability compensation](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/). I'm curious if we need to add a crosslink or update any of the content.
- Generally, we should alphabetize lists--accordions and bullet points.

<details>
<summary>Draft V2</summary>

# Disability compensation for Air Force Reservists and Veterans
If you had regular contact with C-123 aircrafts while serving as an active-duty service member or Reservist, you may be eligible for VA disability compensation. Find out if your Air Force Specialty Code (AFSC) or unit qualifies.

## Air Force Specialty Codes (AFSC)
These AFSCs help identify enlisted members and officers who may have had regular contact with C-123 aircrafts between 1969 and 1986.

**Note:** Your AFSC number may have changed. We'll accept any relevant evidence showing that you had regular contact with C-123 aircrafts.

<details>
<summary>Enlisted members</summary>

You may be eligible for disability compensation if you served as an enlisted member under any of these AFSCs:

- Aircrew Life Support Specialist: codes 1220-1229, **or**
- Aircraft Maintenance Specialist/Flight Technicians: codes 4313-4359, **or**
- Flight Engineer/Aircraft Loadmaster: codes 1130-1149

</details>

<details>
<summary>Officers</summary>

You may be eligible for disability compensation if you served as an officer under either of these AFSCs:

- Flight Nurse: codes 9761-9766, **or**
- Pilot/Copilot, Transport and Tactical Airlift: codes 1043-1055

</details>

## Active duty Air Force bases in the US
These Air Force bases help identify Veterans who may have had regular contact with C-123 aircrafts in the U.S.

<details>
<summary>Hurlburt Auxiliary Field, Eglin Air Force Base, Florida</summary>

You may be eligible for disability compensation if you served in either of these units between 1970 and 1973:

- 1st Special Operations Wing (SOW), **or**
- 4410th Combat Crew Tactical Wing (CCTW)

</details>

<details>
<summary>Langley Air Force Base, Virginia</summary>

You may be eligible for disability compensation if you served in the 4500th Air Base Wing (ABW) unit between 1962 and 1963 or between 1970 and 1973.

</details>

<details> 
<summary>Luke Air Force Base, Arizona</summary>

You may be eligible for disability compensation if you served in the 56th Air Base Wing (ABW) unit between 1970 and 1973.

</details>

## Active duty Air Force bases overseas
These Air Force bases help identify Veterans who may have had regular contact with C-123 aircrafts overseas.

<details> 
<summary>Clark Air Force Base, Philippines</summary>

You may be eligible for disability compensation if you served in the 405th Fighter Wing (FW) unit between 1969 and 1970.

</details>

<details> 
<summary>Howard Air Force Base, Panama</summary>

You may be eligible for disability compensation if you served in the 24th Special Operations Wing (SOW) unit between 1970 and 1973.

</details>

<details> 
<summary>Osan Air Base, South Korea</summary>

You may be eligible for disability compensation if you served in the 51st Air Base Wing (ABW) unit between 1970 and 1973.

</details>

<details> 
<summary>Tainan Air Field, Taiwan</summary>

You may be eligible for disability compensation if you served in either of these units between 1969 and 1970:

- 309th Special Operations Squadron (SOS), **or**
- 310th Special Operations Squadron (SOS)

</details>

## Reserve Air Force bases
These Air Force bases help identify Reservists who may have had regular contact with C-123 aircrafts.

<details> 
<summary>Lockbourne/Rickenbacker Air Force Base, Ohio</summary>

You may be eligible for disability compensation if you served in any of these units between 1969 and 1986:

- 355th Tactical Airlift Squadron (TAS), **or**
- 356th Tactical Airlift Squadron (TAS), **or**
- 4413th Combat Crew Tactical Wing (CCTW)

</details>

<details> 
<summary>Pittsburgh International Airport, Pennsylvania</summary>

You may be eligible for disability compensation if you served in any of these units between 1972 and 1982:

- 758th Airlift Squadron (AS), **or**
- 911th Aeromedical Evacuation Squadron (AES), **or**
- 911th Aircraft Maintenance Squadron (AMS)

</details>

<details> 
<summary>Westover Air Force Base and Hanscom Field, Massachusetts</summary>

You may be eligible for disability compensation if you served in any of these units between 1972 and 1982:

- 74th Aeromedical Evacuation Squadron (AES), **or**
- 731st Tactical Airlift Squadron (TAS), **or**
- 901st Organizational Maintenance Squadron (OMS)

</details>

## More information
- [File a claim for disability compensation](https://github.com/disability/how-to-file-claim)
- [Learn more about Agent Orange exposure and related health conditions](https://github.com/disability/eligibility/hazardous-materials-exposure/agent-orange)

</details>

What do you think about how I've used accordions in this draft? And what do you think about the way I've formatted the dates and units for each Air Force base?

I'm open to any and all of your feedback!

**Comment by d-beyer** [comment]
Here's a preview of what we're thinking with the table:
## Active duty Air Force units
These active duty Air Force units may have had regular contact with C-123 aircrafts.

| Unit                                    | Years                        |
| --------------------------------------- | ---------------------------- |
| 1st Special Operations Wing (SOW)       | 1970 to 1973                 |
| 4410th Combat Crew Tactical Wing (CCTW) | 1970 to 1973                 |
| 4500th Air Base Wing (ABW)              | 1962, 1963, and 1970 to 1973 |
| 56th Air Base Wing (ABW)                | 1970 to 1973                 |
| 405th Fighter Wing (FW)                 | 1969 to 1970                 |
| 24th Special Operations Wing (SOW)      | 1970 to 1973                 |
| 51st Air Base Wing (ABW) unit           | 1970 and 1973                |
| 309th Special Operations Squadron (SOS) | 1969 to 1970                 |
| 310th Special Operations Squadron (SOS) | 1969 to 1970                 |

## Reserve Air Force units
These Reserve Air Force units may have had regular contact with C-123 aircrafts.

| Unit                                            | Years         |
| ----------------------------------------------- | ------------- |
| 355th Tactical Airlift Squadron (TAS)           | 1969 to 1986  |
| 356th Tactical Airlift Squadron (TAS)           | 1969 to 1986  |
| 4413th Combat Crew Tactical Wing (CCTW)         | 1969 to 1986  |
| 758th Airlift Squadron (AS                      | 1972 and 1982 |
| 911th Aeromedical Evacuation Squadron (AES)     | 1972 and 1982 |
| 911th Aircraft Maintenance Squadron (AMS)       | 1972 and 1982 |
| 74th Aeromedical Evacuation Squadron (AES)      | 1972 and 1982 |
| 731st Tactical Airlift Squadron (TAS)           | 1972 and 1982 |
| 901st Organizational Maintenance Squadron (OMS) | 1972 and 1982 |

**Comment by d-beyer** [comment]
I showed the draft page to BP and ran it by Jamie for a quick accessibility check. I also notified the SME that this page would be going up soon.

@saratorres2 Can you copyedit and publish?

**Comment by saratorres2** [comment]
@d-beyer Updated page and crosslink have been published (12/18) and validated (12/19).

**Comment by aprocik1** [comment]
I added this to our [redirect ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98843). I'm closing this as complete.
