### ISSUE TITLE
10-7959f-2 Architecture Intent

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96547]
https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent

#### What’s the purpose of the Architecture Intent?
The goal of the Architecture Intent meeting (or “touchpoint”) is to ensure you’re building a product that meets VA.gov Engineering and Security standards before you’ve started building your product.

This meeting is less a formal presentation and more a collaborative discussion surrounding the architectural decisions that impact the engineering and security posture of the product you are building or iterating on. It not only provides OCTO-DE and Platform with an early understanding of the product/feature your team wants to build, but is also an opportunity to collaborate with VA’s engineering and security stakeholders to assist you with building out the correct technical solution. The focus is on making sure your code meets user needs within the constraints of the platform you're building on.

### Acceptance criteria
- Prepare any required collab cycle artifacts specific to Architecture Intent
- Schedule meeting with Governance team
- Represent the team at Architecture Intent (with support from the rest of the team as needed)

**Comment by michaelclement** [comment]
[Checklist created here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/checklist/ivc-107959f2-11122024.md)

**Comment by michaelclement** [comment]
[Diagram added here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/diagrams/champva)

**Comment by michaelclement** [comment]
Meeting has been scheduled for the earliest possible slot (Dec 3 @ 12:30pm CT)

Details:

**Architecture Intent**
Platform Governance team
12:30pm - 1:00pm, Tuesday, December 3, 2024
Central Time - US & Canada
https://oddball-io.zoom.us/j/83640573880?pwd=4Q7a0agWyK0ZG3NGelesBm4bxcDtbn.1
michael.clement@adhocteam.us, bo.altes@agile6.com, andrea.merrill@agile6.com, donald.shin@agile6.com, rachel.eiting@copilot.llc, steven.long@adhocteam.us
