### ISSUE TITLE
Refactor for Employee Focused Screener

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#9655]
As an Engineer I need to refactor parts of the code that were written quickly to ensure the codebase is easy to understand by other engineers and easy to extend and maintain. 

Use the most common values as the default values in data file so only the items with less common values need additional fields (disqualifying=true and scope=both should be the default)

Refactor how the form is cleared when switching between Veteran and Staff flow.  

Add needed unit tests

**Comment by artsymartha68** [comment]
Direct field input from Shane Elliott:

From VISN22:
"Just tried it. The only shortfall is that it does not have the 'reset' option that the old QR code had."

They liked the "re-take" because they left that tab in their phone browser open and each day they would hit retake to take it for the day.

**Comment by batemapf** [comment]
Not needed; overcome by events.
