### ISSUE TITLE
10-10d Design: Update flow for signer email 

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96560]
Update the Figma file for 1010D to reflect the agreed-upon changes to the flow.

- [x] Reinstate first screener question
- [x] Update language on checkbox question
- [x] Request CAIA review for text changes
- [x] Drop design link in #96561

**Comment by rspope** [comment]
CAIA raised concerns about the flow for user applying for self: the signer and applicant info could potentially be different if we allow changes to the prefilled fields. 

Discussed in office hours today (CAIA, Michael Clemente, Jaime Fiore, and myself) and agreed on solution to compare the information on the review page and show an error if the information doesn't match. Will provide updated design file as soon as possible so update can be made this sprint.

**Comment by baltes** [comment]
@rspope Thanks for this update, let me know if I can help with anything.

**Comment by rspope** [comment]
@baltes I've made the changes CAIA requeted and dropped the Figma link in the engineering ticket. There are multiple other content updates from CAIA in this file that can probably be handled at a later date. 
[Flow](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=4098-27412&t=uimUtLytNiihEgd1-4)
[Error](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=4297-29057&t=uimUtLytNiihEgd1-4)
