### ISSUE TITLE
Auth exp —Request for access to Google Analytics for VA Profile contractor

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#9657]
# Request Google Analytics access

## What this form is for

This is a request for access to Google Analytics for one of the contractors that works on the VA Profile team. We work closely with this team, but we don't manage them, so this person is not in our Github or Slack at the moment. But I can invite them to Slack if that'd be helpful in managing this request.

## User Email Address

> Please link this issue to the DSVA Slack channel #vfs-platform-support, add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.
> 
> If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

The person that needs access is Deepti Ananthramu (Deepti.Ananthramu@va.gov). I'll inform her she needs to set up a google account.

## Access Requirements
_Please list any requirements, if any._

No requirements, but let me know if this is an all-or-none phenomenon. If you need specific dashboards she should have access to, I can get you that info.

## Date Required
_Please share the date you require access._

No date requirement. Just let me know when you think you'd be able to fill this request.

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

VA DEPO team; Authenticate experience for the VSA contract

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Collaborate, Read, Access permissions have been granted on the production property.  

Closing.

**Comment by Samara-Strauss** [comment]
Thank you so much, Brian!
