### ISSUE TITLE
Front-end Engineers: Attend deep-dive session

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#966]
Check the box below when this task has been completed and comment "done". 

- [x] Front-end Engineers: Attend deep-dive session

**Comment by mojaray2k** [comment]
Are we getting more information about this?

**Comment by Justin-Pickett** [comment]
I believe you all had a deep dive specific to engineers on last week while we were in DC. Didn't this happen in a breakout session?

**Comment by erikphansen** [comment]
The meeting we had Wed Aug 7 wasn't specific to front end engineers, but is probably what this ticket refers to. So I'm marking "done" for now

**Comment by Justin-Pickett** [comment]
I'm going to track down some info on this one to see if it is a special meeting that needs to be set up with the platform team or something.

**Comment by Justin-Pickett** [comment]
@accbjt will be scheduling this intro session.

**Comment by mojaray2k** [comment]
Done

**Comment by Justin-Pickett** [comment]
A.E. front end engineering team members have completed this task. Closing ticket.
