### ISSUE TITLE
VAMC Top task buttons in IE

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9660]
## What happened?
Three top task buttons do not render on single horizontal line when viewed in IE

![image](https://user-images.githubusercontent.com/55411834/83306964-6f34b100-a1b8-11ea-89d3-dbd5a7c4bb49.png)

## Specs:
- Browser: IE 11
- URL: https://www.va.gov/pittsburgh-health-care/

## Desired behavior
Design component should be consistent, regardless of browser

![image](https://user-images.githubusercontent.com/55411834/83307036-97bcab00-a1b8-11ea-94b7-b72de5990ba7.png)

## Acceptance Criteria
- [ ] Top task buttons render in single horizontal line when viewed in IE

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by davidconlon** [comment]
@mmiddaugh Why this is blocked by the SideNav? I'm not sure there is really a dependency between the two...

**Comment by davidmpickett** [comment]
IE is no longer supported browser and we also have an upcoming change to Top Tasks that will not longer have buttons side-by-side
