### ISSUE TITLE
Vets-api terminal access for Mark Chae

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#96617]
### Your Name

Mark Chae

### Your GitHub handle (terminal access is managed through GitHub)

@mchae-nava

### Your dsvagovcloud AWS user name (if applicable)

Mark.Chae

### Team, Role, and Company of the target individual

Disability Benefits Experience, Software Engineer, Nava PBC

### Product Manager (PM) name and email

Jared Pace, jared.pace@agile6.com

### Product Owner (PO) name and email

Emily Theis, emily.theis@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Previously had access, need to verify if it's up to date. Production access is for ongoing priorities that require viewing and generating reports for POs using production data

![Image](https://github.com/user-attachments/assets/c9597c95-caa9-4ad7-9d2f-b9b94a4eb9b2)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by GWright321** [comment]
@mchae-nava  You have access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by GWright321** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by GWright321** [comment]
@mchae-nava You've been granted access to Dev/Staging/Production, 
with access to Production limited to 6 months, expiring 5/11/25.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by GWright321** [comment]
Slack Reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1731334911284689)
