### ISSUE TITLE
Refactor status update jobs

### ISSUE THREAD

**Issue by kayline** [department-of-veterans-affairs/va.gov-team#96645]
## Value Statement

**_As a_**  engineer

**_I want to_** to reduce code duplication

**_So that_** it's easier to maintain and understand the codebase

---

## Background Context

- We need to check on the status of 3 different forms, and possibly associated evidence and secondary forms. Right now each job has very similar code, and it feels a bit messy. Can we create a base job with the shared code? Will that help reveal some ways to simplify the logic?

## Outcome, Success Measure, KPI(S), and Tracking Link

- Fewer lines of code, same functionality, still readable

## Out of scope

- The notification jobs, or original form tracking

## Open questions

- Add here

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
In progress, will have a PR ready soon.

**Comment by eileen-coforma** [comment]
Platform review wait period. Waiting for 2 days.
