### ISSUE TITLE
[Bug] 10-10CG MVP - Submission error

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9666]
On Staging **Apply for the Program of Comprehensive Assistance for Family Caregivers** form, **Review Application** form-page, submitting form triggers error-message.

**NOTE**: Specific test-account names were not used.  Based on recent Sprint Demo, it sounded like dummy-names may have triggered this submission error.

## Specs:
- Browser-/device-agnostic
- Unauthenticated experience

## Steps to Reproduce
1. Go to https://staging.va.gov/caregivers/introduction
1. Keep inputting dummy-info for all required fields and clicking **Continue** button until you reach **Review Application** form-page -- use "John Doe" for Veteran and "Jane Doe" for Primary Family Caregiver.  No need to add Secondary Family Caregiver(s) -- doing so (w/ "Jack Doe" & "Jill Doe") still replicates this bug.
1. Click **Submit application** button.
1. Observe that submission error is displayed -- also you need to scroll up to see the error.

**GIF capture**
![1010cg-submission-error](https://user-images.githubusercontent.com/587583/83599566-5feb9580-a521-11ea-8f5d-fa6d7707876d.gif)

## Desired behavior
- **...full name** texbox-labes and **I certify...** checkbox-labels should display "(*Required)".
- Clicking **Submit...** button with any textbox/checkbox blank should display appropriate error-messages, instead of allowing submission to transmit.
- IF submission error is indeed legitimate, browser should auto-scroll up to make the error visible onscreen.

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
@tlei123 - The submission not working is expected behavior due to CARMA bugs on the backend side. The new error page should now appear for all errors. Please validate and close - thanks!

**Comment by tlei123** [comment]
> The new error page should now appear

@ala-yna , is [this prototype](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/419830701) the "new error page" I should expect on Staging?

I'm still seeing the one shown in my QA GIF-capture above (in main Description) -- just wanna double-check.
