### ISSUE TITLE
Staging Review finding: Product duplicates existing form and entry points

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#96668]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** My Education Benefits
**Product:** 22-5490 Form
**Feature:** (Fry/DEA) Updates

## Findings details
**VA.gov Experience Standard - issue:** [User does not have a path to the content or feature.](https://design.va.gov/about/experience-standards/#user-has-a-path-to-the-content-or-feature)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** Yes
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The product is a duplicate of an existing form on VA.gov that has another set of entry points.

## Recommended action

Please work with CAIA and @mnorthuis to retire the existing form and update the entry points to refer to the new form. If the existing form must remain, determine where entry points must be updated to the new form.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by claytonholcomb** [comment]
Meeting occurred 11/26 between IA, OCTO, EDU, and AFS, determination was made to keep both versions of the form accessible until official decision is made by EDU to retire legacy forms.  Tentative timeline:

- Go live with new 5490 on 12/7
- EDU will conduct assessment until 12/31
- Retire legacy forms and point to new 5490 1/31
