### ISSUE TITLE
Change one of the names of the 2 login widgets called "appointments" 

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#967]
## User Story
As a developer on the CMS team, I need help from the platform team to change the name of one of the two va.gov login widgets named ```appointment```, so I can call and embed the correct appointment widget on the VAMC pages. 

### Situation
Currently on the [Schedule a VA appointment](https://www.va.gov/health-care/schedule-view-va-appointments/) page, there are two login widgets both called ```appointment```. The first, found under **View your appointments** goes to MHV; the second, found under **Schedule or cancel a VA appointment online** goes to VAOS. 

![image](https://user-images.githubusercontent.com/32132681/63032789-7fc3a700-be84-11e9-83e0-54581bf56b5b.png)

## Goal
_What outcome(s) do we want to see?_
Change the name of the FIRST appointment widget (the one that goes to MHV, under "View your appointments") to ```view-appointment```. Leave the name of the second login widget (the VAOS one under "Schedule or cancel a VA appointment online) as ```appointment```. 

## Acceptance Criteria
- [ ] _What needs to happen or be created?_
Only one login widget is called appointments. When the CMS team tries to call the login widget called appointments only the one pictured below shows up on the VAMC page. 

<img width="748" alt="Screen Shot 2019-08-14 at 11 21 44 AM" src="https://user-images.githubusercontent.com/32132681/63033530-c5cd3a80-be85-11e9-91d6-1a7645123691.png">

## Definition of Done
- [x ] **Attached to a Milestone** This needs to be completed by the start of the next sprint. 
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by batemapf** [comment]
@lalexanderson-dsva the login flow is owned by the authenticated experience team. this is the very beginning of a login flow, albeit on a health products page. but we don't have a team for health products ATM, so going to ship it to the authenticated experience team.

**Comment by Samara-Strauss** [comment]
Working to figure out who on our team has time to tackle this

**Comment by Samara-Strauss** [comment]
@erikphansen is going to work on this

**Comment by erikphansen** [comment]
Looking into this. The source that generates that static page might live in the Drupal CMS in which case I think that the CMS team would have to change the markup. Will follow up when i know more.

**Comment by erikphansen** [comment]
@lalexanderson-dsva For total clarity, do you want the `data-app-id` values to be `view-appointment`/`appointment` or `view-appointments`/`appointments`; singular or plural?

**Comment by erikphansen** [comment]
@lalexanderson-dsva I'm reading this ticket again and am a little confused. The first line of the ticket, `As a developer on the CMS team, I need help from the platform team to change the name of one of the two va.gov login widgets...`, doesn't match my understanding of where that `id` comes from. It appears to be entirely within the CMS team's power to set that `data-app-id` value to whatever they want it to be and they don't need anything from the platform or app team.

**Comment by erikphansen** [comment]
This is done and Kevin Walsh made the corresponding changes on the CMS change to use the new appointments widgets.
