### ISSUE TITLE
IA Request [Profile 2.0]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#9670]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)
- Link to or attach [prototype or mockups](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/410216937)
- Link to [research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/cpaa-research-findings.md)

## Information Architecture Worksheet (Optional)
Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content
- direct deposit
- update contact information
- connected apps
- account settings
- profile
- military information
- personal information
- update information

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.
      - va.gov homepage

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
@rileyorr @rebeccawalsh  I noticed that in the prototype, the Account security screens have a scenarios where the left nav and the breadcrumb are both removed.  Can you provide me a bit more detail on that?

**Comment by rebeccawalsh** [comment]
@mnorthuis This is not a BaM2 request - are you looking for someone else like Tressa or Liz? 😅

**Comment by mnorthuis** [comment]
@tressaellen I'm working on the IA and noticed that in the prototype, the Account security screens have a scenarios where the left nav and the breadcrumb are both removed. Can you provide me a bit more detail on that?

**Comment by tressaellen** [comment]
Hi @mnorthuis is this the screen you are looking at? The nav and breadcrumbs should be on all of the screens... so I want to make sure it's in there. This screen does have just Account Security showing because an LOA1 user will only have access to that screen until verify their identity.
<img width="543" alt="Screen Shot 2020-06-12 at 1 20 41 PM" src="https://user-images.githubusercontent.com/58752772/84543210-60192d00-aca7-11ea-856b-b8e9751156e1.png">

**Comment by mnorthuis** [comment]
@tressaellen Here is the final IA information. It includes, the page structure, breadcrumbs, URLs, entry points and the user flows.    Your front end team will likely need this information, as well as the Public Websites team for any entry points needed outside of the authenticated experience. 

Please note we will need to implement a redirect on the old account page URL in case someone has that bookmarked.  A separate redirect issue should be created for that at least 2 weeks in advance of it needing to go live.  There is an issue template for redirects.  

Please let me know if there are any questions about any of this, and you are welcome to close this issue when you are ready.  

cc @Samara-Strauss @peggygannon @mshea0606

**Comment by Samara-Strauss** [comment]
> Here is the final IA information. 

@mnorthuis was there supposed to be an attachment/link in the comment above?

**Comment by mnorthuis** [comment]
Oh my goodness...wouldn't that have been helpful!  So sorry!
Here it is:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/auth-exp-profile-v2.md

**Comment by Samara-Strauss** [comment]
Thank you! This looks good to me 😃

**Comment by tressaellen** [comment]
Thanks @mnorthuis - this looks great!

**Comment by tressaellen** [comment]
We won't need the redirect until the new profile is rolled-out to 100% of users.  I know it's early, but I created a [redirect issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10688) and will updates and notify all parties when the time gets closer.
