### ISSUE TITLE
Create May Contact Center Report

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9671]
## User Story or Problem Statement
How might we show what users are calling in about for VA.gov so that VFS teams can prioritize their work in towards human-centered decisions?

## Goal
Create May Contact Center report.

## Acceptance Criteria
- [x] Create May contact center report
- [x] Share out reports in #vfs-analytics

**Comment by Kimberley2019** [comment]
I am unable to upload raw data into webform for DOMO.
Receive error message stating:
There was an error loading this DataSet. Please return to Data Center and try again later.
While I'm on the VA Network when this message populates. I do NOT receive this message when I'm on this side.

**Comment by Kimberley2019** [comment]
I was able to logon to DOMO while on the VA Network.  Current May data was uploaded on 6/3/2020.

**Comment by Kimberley2019** [comment]
I was able to upload the NCC breakdown into DOMO in order for Jon to review.

**Comment by clantosswett** [comment]
We created one report for April and May. Can be accessed here: https://domo.buzz/r/wAVKokP
