### ISSUE TITLE
Open directions and "Need Help" section links open in the same tab

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#96729]
## Description

Currently some links are opening in a new tab. This changes them to open in the same tab. This is an improvement for AT users - it's generally easier to find pages if they don't open in a new tab automatically, since users can make that choice in their browser. See CC ticket #88444 for more details.

This changes the following links to open in the same tab, instead of their current functionality of opening in a new tab:

Directions links across all details pages:

![Image](https://github.com/user-attachments/assets/0d64afb2-2815-4135-9a83-da8825cf7864)

Need help links across all pages:

![Image](https://github.com/user-attachments/assets/850dc51f-6d57-46dc-b852-99a28f182447)

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

- [ ] Task 1
- [ ] Task 2

### Design Assets

N/A

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [x] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for validation

**Comment by outerpress** [comment]
@JunTaoLuo looks and sounds good to me! Feel free to close. Nothing to update in the docs on our side.
