### ISSUE TITLE
Remove step from website generator that creates file in vagov-content repo

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9674]

**Comment by meganhkelley** [comment]
@U-DON does this still happen?

**Comment by U-DON** [comment]
Yes, I believe this still happens.

https://github.com/department-of-veterans-affairs/generator-vets-website/blob/9f149acbb856e4474336eb55251c62e0be3c5955/generators/app/index.js#L149-L163
