### ISSUE TITLE
Collaboration Cycle for [Sitewide, Facility Pages , VAMC, Alternative Alert Banners]

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-team#96762]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1441) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
### VFS team name

Facilities

### Product name

VAMC

### Feature name

Alternative Alert Banners

### GitHub label for team

sitewide

### GitHub label for product

facilities

### Public DSVA Slack channel for VFS team

#sitewide-facilities

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

23 September 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Static pages

### Does your work require non-trivial code changes or involve PII/PHI?

No

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Will a VA editor (Drupal) notice this change?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/features/vamc-banner-alerts/README.md

### Verify all relevant materials provided to Governance Team

- [x] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [x] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C0FQSS30V/p1731350582188449)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [x] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Architecture Intent
<details>
  <summary>Toggle Architecture Intent instructions</summary>

##### VFS team actions
- [x] Review [Architecture Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent) to understand what this touchpoint involves.
- [x] Schedule your Architecture Intent (with at least 2 business days lead time from now):
  - Open the [Calendly Architecture intent calendar](https://calendly.com/collaboration-cycle/architecture-intent)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [x] Link all artifacts in the `Architecture Intent artifacts for review` section below at least two business days before the scheduled Architecture Intent. Please don't add artifacts in the comments section.
  
**Architecture Intent artifacts for review**

[See guidance on Architecture Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#ArchitectureIntent-Whatartifactswillbeneeded?) Feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] Fully completed [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md) -- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/checklist/2024-11%20Facilities%20VAMC-real-time-banners.md
- [ ] [User data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md), if your application accepts data from a user. -- N/A

##### Platform Team actions
- [x] Meeting date/time: **December 12 at 2:30pm ET**

##### Platform Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Mobile Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Security feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback  

##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
</details>

### CMS Request
<details>
  <summary>Toggle CMS Request</summary>
  
#### VFS actions
- [x] Complete the [CMS request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/cms-request) -- CMS team members will attend the Architecture Intent meeting to satisfy this touchpoint
</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided. -- No test users necessary, this is an unauthed feature
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory). -- N/A, this is a feature within VA Medical Centers (VAMC)
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [x] **URL(s) to review the product**: Tugboat URL, per approval from Governance:   (SOCKS access will be required to view)
  - Banners appear on the following pages. Previously, those were build via content-build. Now they are build in a vets-website React application. This is a data source / markup migration of an existing design that is not changing.
    - https://web-pjrkdo5kzgprzxpfz31rnvzleiegcmh4.demo.cms.va.gov/wilmington-health-care/
    - https://web-pjrkdo5kzgprzxpfz31rnvzleiegcmh4.demo.cms.va.gov/memphis-health-care/
    - https://web-pjrkdo5kzgprzxpfz31rnvzleiegcmh4.demo.cms.va.gov/manchester-health-care/
- [x] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search) -- Veterans will find real-time banners on VAMC System pages
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [x] **Test users and scenarios** (when applicable) -- N/A. Banners are visible in the unauthenticated experience. (Though they are also visible once logged in)
  - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a .md file in the va.gov-team-sensitive repository. 
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [ ] **Link to Sitewide CAIA intake ticket**, if applicable. -- N/A
- [x] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review). -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97684
- [x] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards):  **all requested information is covered in** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/initiatives/2024-real-time-banners/testing-qa.md
  - Regression test plan
  - Test plan
  - Coverage for References
  - Summary (Defects) reports
  - E2E tests
  - Code coverage
  - Endpoint monitoring playbook
  - Logging silent failures

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth. -- N/A, this is editor generated content
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec. N/A, again: just a rebuild of an existing feature / IA.
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C0FQSS30V/p1732022872266379)
- [x] Meeting date/time: ~~2:00pm ET Fri, Dec 20, 2024~~ 2:00pm Fri, Dec 13, 2024

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link ](https://oddball-io.zoom.us/rec/share/HJt5HjSnCRaqPupwmCmnmTmQVjeoiUaFOdW1SAgs_TXW5Rp0nflVkyltdAaPtj9V.7s7TAEqDALL-ZqOz)
  - Password: cL6#CH7#
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review. — N/A per [comments below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96762#issuecomment-2494897891)
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

**Comment by Agile6MSkinner** [comment]
We will not be completing the design intent section, as there is no change to the user experience or flow. This work will only change the background method for displaying the alert banner

**Comment by NaomiPMC** [comment]
Since this work only involves changing the background method for the display alert banner, CAIA will not be needed.

**Comment by shiragoodman** [comment]
@Agile6MSkinner I have updated this ticket to include the Architecture Intent touchpoint after discussing this with the Platform OCTO-DE engineering leads. The process of how we determine if the Architecture Intent is needed is still pretty new, and my team made an error when not originally including it. Please let me know if you have any questions about the touchpoint, and keep in mind that it is required.

**Comment by jilladams** [comment]
@shiragoodman can you confirm that we'll need to make a 508 office request for this after launch? What we're doing is taking a feature that's currently built in content-build and porting it to vets-website. It's not an overall new Veteran-facing feature, it'll just have a different data backend with a new vets-api endpoint.  (cc @laflannery )

**Comment by shiragoodman** [comment]
@jilladams yes, the VA 508 office requests that all products on VA.gov are audited through their process. [More information is available here. ](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVASection508Office-AuditRequestaudit-request)

I believe you asked us the Tugboat question before with another Sitewide product. I don't recall it being an issue for my team before, so I imagine this time it won't be either. However I can follow up with them at our standup on Monday to confirm.

**Comment by shiragoodman** [comment]
If you have additional questions about the VA 508 audit process, @artsymartha68 can help you out.

**Comment by laflannery** [comment]
@shiragoodman and @jilladams I just had a chat with @artsymartha68 regarding the 508 question. We both felt that the 508 audit wouldn't be necessary here for a few reasons:
1. The reason Jill called out that only the plumbing is changing, not the FE display
2. We historically are very judicious with which static pages/products we send to the 508 office because of their capacity.
3. In this case, we could send a page to the 508 office that has a banner but by the time they are available to audit it, that banner might be gone. We simply cannot guarantee the content will be available when they are available.

All this being said, Martha said that we could skip the 508 audit in this case but ensure that decision was documented somewhere.

**Comment by Agile6MSkinner** [comment]
@shiragoodman Any update on whether or not tugboat works for your team?

**Comment by shiragoodman** [comment]
@Agile6MSkinner yes, thanks for the nudge. We should be good to test in Tugboat.

**Comment by jilladams** [comment]
@Agile6MSkinner FYSA next week: I have linked the Architecture Intent and Staging Review artifacts in the ticket body and checked off the boxes for where we're at. Outstanding so far is providing the Tugboat environment, which we're still working on.

**Comment by laflannery** [comment]
Specific Tugboat testing URL:

- https://web-pjrkdo5kzgprzxpfz31rnvzleiegcmh4.demo.cms.va.gov/wilmington-health-care/ 
- https://web-pjrkdo5kzgprzxpfz31rnvzleiegcmh4.demo.cms.va.gov/memphis-health-care/
- https://web-pjrkdo5kzgprzxpfz31rnvzleiegcmh4.demo.cms.va.gov/manchester-health-care/

@jilladams @Agile6MSkinner @shiragoodman

**Comment by DonMcCaugheyUSDS** [comment]
Thank you all for participating in the architecture intent review.  Here are the recommendations from this discussion:

- consider adding a path field to the DB schema with an index
    - because this DB is effectively a cache of the Drupal source-of-truth, this duplication shouldn't be a problem
- consider keeping a permanent operational feature flag that can disable this feature
    - this gives us ongoing protection for both VA.gov and Drupal if this feature ever goes awry
    - ask the platform team if we have a standard way to manage operational feature flags vs development feature flags
- in the future, consider moving away from GraphQL to Drupal's REST API
- after you have some experience running this in production, consider increasing the frequency that you fetch banners from Drupal

**Comment by jilladams** [comment]
We launched! We've addressed all but 2 milestone issues which will either get a tracking ticket or be closed as no-ops, and the arch intent feedback in comment above is also now tracked in our backlog. Closing this ticket. Thank you all so much for your help / support with assisting us to get this out before the break!
