### ISSUE TITLE
Update welcome modal

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9677]
As a Veteran, I want to know that I am now using the newest VA scheduling experience and that I may notice new features and designs that weren't part of the old scheduling experience that is not longer available. 

This welcome modal will be important for assisting the Veteran in understanding why they are seeing a new tool and not legacy VAOS when redirected. (ex. MHV -> VA.gov/VAOS)

## Acceptance Criteria:
- [ ] Update current welcome to something similar to: 
**Welcome to the new VA online scheduling tool**
_Things may look a little different than the last time you tried to schedule an appointment online. Based on feedback from Veterans like you, we've redesigned the VA appointment tool. _ 

_You can now schedule, cancel, and view your future and past appointments all in one place. If you have feedback about the new experience, you'll find a feedback option at the bottom of the page._ 
- [ ] Remove reference going back to 'old' VAOS tool

***For reference here is the current modal:***
![Screen Shot 2020-06-10 at 8.52.01 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/1f3272a9-c3d6-41ef-ac31-465b2940374d)

**Comment by lenaecb** [comment]
@rtwell @peggygannon - I have provide some starting copy for what the updated modal could say, but defer to you on the final version. We're looking to implement this small change this sprint (sprint started today).

**Comment by peggygannon** [comment]
hi, @lenaecb @rtwell 
Here's suggested language for the modal: 

**Welcome to the new VA online scheduling tool**
Things may look a little different than the last time you scheduled a health appointment online. Based on feedback from Veterans like you, we've redesigned the VA online scheduling tool. You can now schedule, cancel, and view your future and past appointments all in one place. 

If you like to send us feedback about the new experience, you’ll find a feedback link at the bottom of the  page in the tool. 

Button: 
Go to your VA appointments


**Also,** can we fix the content for this feedback link in the application to say: 

[Leave feedback about this application] (not *for* this application)

**Comment by lenaecb** [comment]
Thanks @peggygannon! I think this looks good! And yes, we'll the feedback copy updated. I have another ticket for updating the footer, so I'll drop this update in there too (#10130 ). 

@rtwell - thumbs up?

**Comment by rtwell** [comment]
lgtm!
