### ISSUE TITLE
Design feedback - Design intent Collaboration Debt Letters MVP (BAM2)

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#9678]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

- I like the format of these wireflows, it’s nice to see sketches and not hifi in the beginning 
- I like the approach to this problem, debt can be a sensitive subject, and I think they approached it with empathy. 

**Do:**

- No "do" feedback at the moment

**Try:**

- The “debt” unit of information is similar to the “appointment” unit of information - see the VAOS UX and when you get to the design phase, try using that as a starting point -- similarly, it also has states of appointments: upcoming, cancelled, etc. va.gov/health-care/schedule-view-va-appointments/appointments/ 
- The left nav should probably be present on the Manage Your VA Debts content page (the first one) --We discussed this during the meeting. BAM2 will reach out to Mikki about where this could live. We're going to discuss with the VSP collaboration group about the possibility of adding content/IA to these meetings as well. 

**Consider:**

-  No "consider" feedback at the moment 

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by rebeccawalsh** [comment]
@CrystabelReiter Thanks!

We've incorporated the feedback that we got in the meeting today (you can see the updated flows in our log here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md)

We've still got some work to do w/ business, but it's good we got an overall approval in direction.

**Comment by CrystabelReiter** [comment]
@rebeccawalsh awesome work! I'll close this ticket
