### ISSUE TITLE
DCM: Private medical evidence page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#96787]
## Description
First, we need to assess the content on this legacy page to determine if any of it is missing on VA.gov: [Private Medical Evidence](https://benefits.va.gov/compensation/dbq_disabilityexams.asp)

Then, we need to determine where to add the missing content on VA.gov. We should consider adding it to these pages:

- [Evidence needed for your disability claim](https://www.va.gov/disability/how-to-file-claim/evidence-needed/)
- [Supporting forms for VA claims](https://www.va.gov/supporting-forms-for-claims/)
- [Upload evidence to support your disability claim](https://www.va.gov/disability/upload-supporting-evidence/)

### Step 1: Assess pages

- [x] DB: Draft recommendation with support from AP
- [x] BP: Review recommendation

### ~~Step 2: Update pages (if needed)~~

- [ ] ~~DB: Draft updates with support from AP~~
- [ ] ~~BP: Review updates~~
- [ ] ~~SME: Review updates~~
- [ ] ~~ST: Copyedit and publish~~

## Criteria
- [x] All of the content on the legacy page is on VA.gov

**Comment by d-beyer** [comment]
We met with Beth and determined that the content of this page is already covered on modern VA.gov pages and does not need to be migrated. This ticket can be closed.
