### ISSUE TITLE
Adding Priscilla Ohene to DSVA Slack

### ISSUE THREAD

**Issue by kacibowen** [department-of-veterans-affairs/va.gov-team#96799]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Priscilla Ohene, priscilla.ohene@adhocteam.us, as a full member. Priscilla is joining the RISE program as a business analyst and will need access to multiple channels. Priscilla does not have a VA email yet, that is in in progress and we will update the account as soon as we have it.

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by kacibowen** [comment]
cc @goldenmeanie and @meganhkelley

**Comment by LEHigley** [comment]
invite sent. please ensure email is updated to VA account once created and then this can be closed

**Comment by kacibowen** [comment]
User has updated her settings with VA email. Priscilla.Ohene@va.gov. Please close this ticket.
