### ISSUE TITLE
Adding Maulik Parikh to DSVA Slack

### ISSUE THREAD

**Issue by kacibowen** [department-of-veterans-affairs/va.gov-team#96795]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Maulik Parikh, mparikh@ironarchtech.com, as a full member. Maulik is joining the RISE program as a software engineer and will need access to multiple channels. Maulik does not have a VA email yet, that is in in progress and we will update the account as soon as we have it.

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by kacibowen** [comment]
cc @goldenmeanie and @meganhkelley

**Comment by LEHigley** [comment]
inivte sent. please update to VA account once created then this can be closed

**Comment by LEHigley** [comment]
any update on a VA address @kacibowen

**Comment by kacibowen** [comment]
Maulik has updated his profile with his VA email. maulik.parikh@va.gov. Closing this ticket. Thank you.
