### ISSUE TITLE
Content review: STEM VA form 22-10203

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#9680]
## User story

This ticket captures VSP content feedback on STEM form VA 22-10203 

Protoype link: https://bahdigital.invisionapp.com/share/AUIADV5GTC2#/screens/296037351  

## Acceptance criteria

- [x]  Peggy provides content feedback for form/tool
- [ ]  Team incorporates feedback and/or asks follow up questions about the feedback
- [ ] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
@amyknox @ccruzgra I've inserted my comments into the prototype and have also dropped them here into the ticket. Please let me know if you have any questions about my feedback or recommendations: 

Usability prep review for VA Form 22-10203

Introduction page
Recommend updating header to: Apply for Rogers STEM Scholarship

Recommend changing this subhead to be more clear this is about the scholarship:
Follow the steps below to apply for this scholarship

Subway map
Under Prepare bullet: 

add you to this link : Check *your* remaining benefits (also within the form)
add comma after engineering

Apply
You can print **this page** for your records

VA review (make sentence case)

Page 3
Applicant information (make sentence case)

Page 4
Education benefit (make sentence case)

Page 7
Please tweak radio buttons to make them more parallel in construction: 

More than 6 months
Less than 6 months
None. I've used all of my education benefit 

Page 9
Recommended copy updates to tighten up language: 

Based on your responses, it appears you’re not eligible for the Rogers STEM Scholarship


If your situation changes and you meet all of the criteria, you can apply again for the Rogers STEM Scholarship. 
You may be eligible for other education benefits. Learn more learn about what other benefits are available to you.

{button} Explore other education benefits button


Screen 12

I want to confirm that users won't see the green button if they click "yes".. It seems like a confusing UX if this green button still shows if Yes is selected.

Screen 13
If this note at bottom of screen referring to this screen, then I recommended moving it to the top of the page and tweaking as such: 

**Note:** If you need help completing this part of the application, you can contact the School Certifying Official (SCO) at your school.

Screen 14

recommended edits to tighten up content
 

You can receive the Rogers STEM scholarship while you're on active duty, but you won't be eligible for the scholarship's housing allowance.

I'm not sure you would need this  sentence about filling in as much info as possible if the contact fields are "required".


I recommend tweaking question to to give users more than one communication method:

What is the best way for us to contact you? (Check all that apply)


Our style is to not have 1- before phone numbers. 

Please remove the 1- from the phone numbers in the direct deposit modal info. 


Review screen

Make the below headers sentence cased, per our styleguide
Review application
Applicant information
Education benefits
Program details
Military details
Personal information

Social Security number .. please lowercase n

Confirmation screen: 

I suggest changing header in blue box to 
Rogers STEM Scholarship 

so there is no confusing on user's part on what they have applied for (and if they should call in about their claim).

[Find out what happens are you apply] link
Where does this link take users? 

If it goes to  a static page, then I recommend you coordinate with the Public website team to determine if we need to add content to that page about the STEM scholarship and what students can expect.

**Comment by amyknox** [comment]
Thank you @peggygannon ! These tweaks look like they make sense.  We're going to see what we can get into the prototype for testing before tomorrow.  The rest of the style changes we'll incorporate in the final version. 

One update on Screen 12 (the one with the notice that the applicant is likely not eligible)
We're switching that up a bit to include an omnipresent display of the content about looking for other benefits & the green button ahead of the "Do you still want to apply?" button.  

That way they get the alternate exit first - hopefully they'll take it - and there will be more physical distance between the green button and the Back / Continue buttons. 

Getting applicants to opt out at that point is a focus for this effort so we'll be watching that closely during testing. 

LMK if you have other questions!

**Comment by peggygannon** [comment]
ok, thank you @amyknox for the update
