### ISSUE TITLE
Update background color of 2ndary nav 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#96814]
## Description

Currently, the background color of the secondary navigation bar in production/staging is the same exact hex code shade of blue as the hover-state of the mega-menu. We should have some visual distinction between the two since they butt up against one another directly. 

### User story

As a Cartography team member, I want to update the background color of the secondary nav to match what is in Figma, so that it is distinct from the hover state of the primary mega menu on VA.gov (desktop). 

### Notes
- On screens larger than mobile, the mega menu is triggered by selecting dropdown components. When hovering over them, the dropdowns are the exact same shade of blue as the background of the secondary navigation component. 
- We intentionally specified a different shade of blue to avoid this, it is specified in the [Figma file here](https://www.figma.com/design/1vpv191I1zrUZhg5aSuPll/MHV-to-VA.gov-Library?node-id=1-23&node-type=canvas&t=RhTzfFdA2VcArQnJ-0)
- Relevant [Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1728488277961859)

![Image](https://github.com/user-attachments/assets/dc5c42cf-b6ff-4dd0-8f3a-5a48e7dbff21)

## Possible tasks:
- [ ] Update the background color of secondary navigation bar:
    - Current: #005EA2
    - Color we want it to be: #0071BB
- [ ] Check design system color vars
    
## Acceptance criteria
- [x] Background color of secondary nav is now correct (#0071BB)
- [x] UX review
- [x] QA review
- [ ] A11y review

**Comment by wesrowe** [comment]
@nichia this shows as "ready" on the board, but don't you have a PR up for it?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the background color of the secondary nav has been updated to #0071BB

| Before | After |
|--------|-------|
| <img width="500" alt="Image" src="https://github.com/user-attachments/assets/fe0f3a94-d5d4-4c23-a540-774fd0a2f107" /> | <img width="500" alt="Image" src="https://github.com/user-attachments/assets/43c7fc71-f80a-40f1-b41f-150af3b72899" /> |

**Comment by jonathanjnelson** [comment]
I can confirm the background color of the secondary navigation has been updated to #0071BB

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the color has been reverted

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/96fa59af-efa3-46ae-8465-734bed1cd7d2" />

**Comment by wesrowe** [comment]
@allanto-ah, can this close?

**Comment by allanto-ah** [comment]
@wesrowe yeah there isn't anything else that needs to be done here. Closing
