### ISSUE TITLE
User can continue without *selecting* a representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96834]
The requirement to search for a representative on the `/representative-select` screen is not being enforced.

## Expected vs. Actual
**Actual**: Can Continue without selecting a representative. 

**Expected**: If the user clicks Continue without selecting a representative, they should see the following error:
![Image](https://github.com/user-attachments/assets/d728549d-950f-40e3-95be-55c01c82891f)

## Steps to Reproduce
1. Navigate to the `/representative-select` screen
2. Search for a representative
3. Instead of clicking a "Select this representative" button, instead select "Continue" at the bottom of the page

**Comment by oddball-lindsay** [comment]
I am seeing an error when I try to continue (and not select a representative), but the error message doesn't match the expected error message above.

![Image](https://github.com/user-attachments/assets/006f50e2-de1a-4c02-8a00-588cb5bce62d)

**Comment by jvcAdHoc** [comment]
That's an easy fix. Update the [text on this line](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/representative-appoint/components/SelectAccreditedRepresentative.jsx#L65) to match the design.

**Comment by oddball-lindsay** [comment]
Error message looks good, thank you @jvcAdHoc! 

![Image](https://github.com/user-attachments/assets/bfcbf956-6245-4184-982d-92c1b59a97bb)
