### ISSUE TITLE
Text inputs are not pre-populating with Profile information (auth users)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96836]
## Expected vs. Actual
**Expected**: Information from authenticated users' Profile is pre-populated in the text inputs, of the Appoint form-fill experience. Similar to the [26-4555 experience](https://staging.va.gov/housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555/introduction) for authenticated users.

**Actual**: Text inputs are blank for all users, including authenticated users who definitely have personal and contact information in their Profile. 

### Affected screens: 
- claimant-personal-information
- claimant-contact-mailing
- claimant-contact-phone-email

- veteran-personal-information
- veteran-contact-mailing
- veteran-contact-phone-email
- veteran-identification
- veteran-service (unsure if we have this "branch of service" information in a user's Profile -- there is a section that says "military information" but I was unable to find a test user that had this information available)

## Steps to Reproduce

For the **non-Veteran** pathway:
1. Login with one of our [ARM test users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv) for Appoint. An LOA3 user would be best, as they have more information in their Profile (LOA1 users may only have an email address in their Profile)
2. Select "I'm not the Veteran"
3. Navigate through to the Claimant chapter
4. Observe that text inputs are blank

For the **Veteran** pathway:
1. Login with one of our [ARM test users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv) for Appoint. An LOA3 user would be best, as they have more information in their Profile (LOA1 users may only have an email address in their Profile)
2. Select "I'm the Veteran"
3. Navigate through to the Veteran chapter
4. Observe that text inputs are blank

## Next Steps
- If we are able to pre-populate text inputs with Profile information, please proceed to ensure content matches this functionality with this ticket:
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/95534
- If we are unable to pre-populate text inputs with Profile information, we'll want to match the authenticated content with the unauthenticated content: 
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/99083

**Comment by raudabaugh** [comment]
Some potential leads for fixing this:
1. Are the form profile mappings mismatched? (e.g. seeing `email` [here](https://github.com/department-of-veterans-affairs/vets-api/pull/17598/files#diff-85937610438c333fed7b740709955feeacac5b85e4f4a2931fffd1d8e01a489bR6) vs. `emailAddress` [here](https://github.com/department-of-veterans-affairs/vets-website/pull/31226/files#diff-3c468028049745a58feece7b5c3307854a21814aa27ed85b9d0bcc4ab57e3bafR51))
2. Should this [`returnUrl`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va_2122.rb#L25) match one of the chapter paths?
3. In that same `FormProfile` component - could the staging test users be failing identity validation (do they have PIDs)?
4. Try setting the [`verifyRequiredPrefill`](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options) option to `true`

**Comment by oddball-lindsay** [comment]
The Authenticated Experience Design team recommended reaching out to Adam Whitlock for help, he is the Lead FE Engineer on the team and it sounds like he has been working with the Profile code for a while.

**Comment by jvcAdHoc** [comment]
[draft pr for front end](https://github.com/department-of-veterans-affairs/vets-website/pull/33667). I need to add unit tests.

**Comment by oddball-lindsay** [comment]
Tested with both the "I'm the Veteran" and "I'm not the Veteran" pathway, confirming the relative Veteran/Claimant chapter text inputs are pre-populated based on that up-front selection.
