### ISSUE TITLE
User can continue without selecting an organization on /representative-organization

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96835]
## Expected vs. Actual
**Expected**: A user is required to select an organization, in situations where a VSO representative is cross-accredited with multiple organizations. 

**Actual**: Users can continue through the `/representative-organization` screen without selecting an organization.

## Steps to Reproduce
1. Select representative "Billy Wells" who is cross-accredited with two organizations
2. Navigate forward to the /representative-organization page
3. Continue without selecting an organization

**Comment by jvcAdHoc** [comment]
draft pr: https://github.com/department-of-veterans-affairs/vets-website/pull/33015

**Comment by oddball-lindsay** [comment]
Looks good
