### ISSUE TITLE
21-22a: Authorizations in PDF do not reflect user's input

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96848]
## Expected vs. Actual
**Expected**: The PDF download should have the appropriate authorizations specified, based on the user's input in the Appoint experience.

**Actual**: The PDF download doesn't seem to reflect the user's input. Field 21 (limitation of consent) always says "No, they can't access any of these types of records." despite other inputs in the Appoint experience. All other authorizations are blank.

It seems this is because the frontend is not sending the boolean values to the backend.
- consentAddressChange needs to be a yes/no boolean value
- recordConsent needs to be a yes/no boolean value
- consentLimits that are selected in the frontend aren't being submitted in the request, when they are submitted they need to be in the format:  ["ALCOHOLISM ", "DRUG_ABUSE", "HIV", "SICKLE_CELL"].

The frontend should additionally send `consentInsideAccess`, `consentOutsideAccess`, and `consentTeamMembers` as part of the PDF request. These come from authorizeInsideVA, authorizeOutsideVA, and authorizeOutsideVASelect screens.

## Steps to Reproduce

Approving authorizations:
1. Select an attorney or claims agent (I chose Lindsay Cress who is an attorney)
2. Navigate through the experience to the authorization chapter
3. Select "Yes they can access all..." for the medical authorization
4. Select "Yes..." for the address authorization
5. Proceed to download the PDF
6. **The PDF should have Field 20 checked (it's actually blank) and Field 21 should say "Yes, they can access all..." (it actually says "No, they can't access any...").**

Declining authorizations:
1. Select an attorney or claims agent (I chose Lindsay Cress who is an attorney)
2. Navigate through the experience to the authorization chapter
3. Select "No, they can't access..." for the medical authorization
4. Select "No..." for the address authorization
5. Proceed to download the PDF
6.  **The PDF should have all ~medical conditions listed out in Field 21 (it actually says a more general "No, they can't access any...")~ authorizations blank (i.e. not authorized).**

**Comment by opticbob** [comment]
Hey @cosu419 all of the text output in the "Steps to Reproduce" section above is handled on the backend.  As long as the frontend sends the two `consentAddressChange` and `recordConsent` booleans and the `consentLimits` array I'll handle the text.

While you're in the 21-22a request could you also add the three fields we discussed for filling out questions 19a and 19b on the PDF?  Those were: `consentInsideAccess` and `consentOutsideAccess` as booleans and `consentTeamMembers` as an array of strings.

**Comment by oddball-lindsay** [comment]
This looks good! I realize I had a weird expectations in Step 6 of the "Declining authorizations" steps to reproduce. Updated up top in the Issue Description, and that is correctly reflected in the generated forms 👍.
