### ISSUE TITLE
Align Appoint MVP designs with Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96844]
## Background
We've found some discrepancies between the Appoint MVP experience in Staging and our design files in Figma. While we typically strive to match Staging to design, there are a handful of instances where the designs are out of date and need to be updated to match our intentions in Staging.

In a pinch, we'll document things that need to be updated in Figma via Figma comments. 

And at some point (not a high priority) we can take the time to address those comments in Figma.

## Tasks
- [x] Address Figma comments, related to alignment with Staging

## Acceptance Criteria
- [x] Figma designs are aligned with Staging, for the Appoint MVP experience.

**Comment by mtri** [comment]
All comments have been tackled.

**Comment by oddball-lindsay** [comment]
Thank you @mtri !
