### ISSUE TITLE
Organization selection does not stay selected/highlighted

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96855]
## Expected vs. Actual
**Expected**: If I select an organization in the `representative-organization` screen, move to the next screen then go back, my organization selection should remain selected.

**Actual**: My organization selection does not appear to be preserved if I navigate back to the `representative-organization` screen. In reality, it is stored by the application, just not selected/highlighted so the user thinks they need to re-select.

## Steps to Reproduce
1. Select a representative accredited with multiple organizations
2. Select an organization
3. Select Continue
4. On the next screen, select Back -- no organization appears to be selected

**Comment by oddball-lindsay** [comment]
Was planning to address this with #96835, so pulling it into In Progress.

**Comment by jvcAdHoc** [comment]
draft pr: https://github.com/department-of-veterans-affairs/vets-website/pull/33015
