### ISSUE TITLE
Fix link behavior and routing

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96851]
We have uncovered some issues with link behavior that should be updated before launch:

- [x] `introduction` - the authenticated action links at the top AND bottom of the page **should read "Fill out your form to request help"** (currently reads "Request help from a VA accredited representative or VSO").
- [x] `representative-select` - the "Find a VA accredited..." link at the bottom of the page **should open in a new tab** (currently opening in the same window).
- [ ] `claimant-contact-mailing` - the "Find out how to change your address..." link for authenticated users **should open va.gov/change-address in a new tab** (currently opening the va.gov homepage in the same window).
- [ ] `veteran-contact-mailing` - the "Find out how to change your address..." link for authenticated users **should open va.gov/change-address in a new tab** (currently opening the va.gov homepage in the same window).
- [x] `next-steps` - the "Learn how to submit your form" link **should open our landing page `get-help-from-accredited-representative` in a new tab** (currently pointing to `next-steps`).

**Comment by cosu419** [comment]
Introduced an issue with the form title - quick change which will be on my PR tomorrow.

**Comment by oddball-lindsay** [comment]
I'm currently unable to generate a PDF for the other tickets in UX Review, I wonder if it's related to the issue with the form title. Will check back tomorrow.

**Comment by oddball-lindsay** [comment]
Looking over this and there are still things to address:
1. The intro page link for authenticated users does not have the right copy
2. The links for `claimant-contact-mailing` and `veteran-contact-mailing` authenticated experience do now open in a new tab, but they should be pointing to va.gov/change-address -- they are just pointing to the homepage which isn't as helpful.

I've unchecked the tasks above to reflect what is not yet complete.

Currently unable to generate the PDF and access the `next-steps` page to confirm the last piece.

Happy to spend some time together if it helps untangle these smaller details!

**Comment by oddball-lindsay** [comment]
Thanks @cosu419 the Introduction page link is looking good 👍 

I'm not 100% sure the links for claimant-contact-mailing and veteran-contact-mailing are quite right though. They're both linking to https://staging.va.gov/change-address/ but I think it should be a production link https://va.gov/change-address/ ...unless that automatically updates when we push the product to Production? 🤔

**Comment by cosu419** [comment]
@oddball-lindsay correct, that is dynamic and will auto-update to va.gov in prod.

**Comment by oddball-lindsay** [comment]
Got it, thanks!
