### ISSUE TITLE
21-22a: Exclude dashes when adding the rep phone number to the PDF

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96853]
## Expected vs. Actual
**Expected**: Only the numbers of the rep's phone number are entered into the 21-22a PDF.

**Actual**: The dashes are carrying over to the PDF, which causes the rep's phone number to be cut off in the 21-22a PDF.
![Image](https://github.com/user-attachments/assets/9fe80346-e32d-4341-be18-8743145448ca)
Rep's info is:
>Lindsay Cress
> 416 W M Ali Blvd Ste 300 
> Louisville, KY 40202
> 502-584-1254 
> djcress@wyattfirm.com

## Steps to Reproduce
1. Select an attorney or claims agent (I selected Lindsay Cress who is an attorney)
2. Navigate through the Appoint experience 
3. Download the 21-22a PDF and observe the phone number

**Comment by opticbob** [comment]
The PR for this ticket is in review.

**Comment by opticbob** [comment]
Team approved, waiting for platform review.

**Comment by opticbob** [comment]
Still waiting on platform, I'll be able to ping them Monday.

**Comment by opticbob** [comment]
The PR for this ticket has been approved by platform and merged.
