### ISSUE TITLE
IA Request: Debt Letters MVP 

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#9686]
## Issue Description
IA Review request for the 'Debt Letters MVP' product. 

### Project progress:
- [x] Talk to customer service leadership / reps at the DMC to get an understanding of business process and what Veterans call to do 
- [x] Ideation workshop w/ BAM2 team 
- [x] Sketch a design solution 
- [x] Discuss design and get feedback in design intent
  - [ ] **Get more guidance from IA about product placement**
- [x] Build a prototype in uxpin
- [ ] Do hybrid generative research / usability test research round

### Important notes:
- Tool will include debts for Education, Comp & Pension, and Loan Guaranty
- The [DEBTMAN](https://www.va.gov/debtman/) site should be replaced with this launch

## Required:
- [Description and goals of the page/tool or link to a product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp)
- Planned/estimated launch date - TBD
- [Link to prototype or mock ups of all pages in the user flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md)

**Comment by mnorthuis** [comment]
@rebeccawalsh Thanks for getting this started!  A couple questions:
1) Can you add a link to your research discussion guide and readout/results to the above once you have them?
2) Given you statement about about retiring the Debt Management site above, there is quite a bit of content on that site.  Have you accounted for all of those pages?  And have you worked with Public Websites team on that effort to ensure parity of content between old and new experience?

**Comment by mnorthuis** [comment]
@rebeccawalsh @rileyorr @leahkeeler   All IA information will be here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-letters.md

There is a link to view the user flows we looked at today on that page, and I keep my meeting notes there as well.

**Comment by mnorthuis** [comment]
@rebeccawalsh I noticed that the detail level of the debt letters tool may not be done.  Can you let me know if that is accurate?

**Comment by leahkeeler** [comment]
@mnorthuis We are releasing in iterations: 

MVP:Debt summary with ability download letters - 1 page - Release early August 
Iteration 1: MVP+Debt Details including status - 1-2 sprints after release 1
Iteration 2: Above + payments +plain English explanation of statuses and next steps + notification likely email - dependent on notification team, date unknown at this time. We may split off notifications into a separate release 

MVP will be released prior to usability. The usability study will focus on features of Iteration 2

Does this answer your question? Thanks a million, Leah

**Comment by mnorthuis** [comment]
@rebeccawalsh @leahkeeler 

Here is the draft IA for purposes of research.  Happy to talk through this with you.  Once research if finalized we can make any appropriate tweaks based on learnings and finalize entry points/crosslinking. 

https://app.moqups.com/Rnc4BDEKrA/view/page/a1803040d

**Comment by leahkeeler** [comment]
@bradl3yC - FYI for URLs

**Comment by leahkeeler** [comment]
@bradl3yC  - I believe you have completed this - if so, can you ping Mikki to validate and close the ticket

**Comment by bradl3yC** [comment]
@leahkeeler I completed moving the URL - the PW part hasn't been done yet and I don't know if there were any content change requests

**Comment by mnorthuis** [comment]
@leahbannon All final IA information is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-letters.md

This write-up includes everything for the next iterations of this tool.  Please let me know if you want to walk through it or have any questions. 

The only outstanding issue I have is for entry points.  The primary entry point will be within the Records hub, but additional entry points may be needed  from other hubs or content pages.  I will connect with Danielle on those when she returns.  The entry points will be implemented by the PW team.

**Comment by leahkeeler** [comment]
Thank-you @mnorthuis

**Comment by rebeccawalsh** [comment]
Hi @mnorthuis !

I must have written this out before but never hit the comment button for it - whoops.

We noticed some stuff while we were testing - one major one that you may be interested in was how many people would hit the 'Manage your VA debt' breadcrumb to get back to the debt list page (called 'Current VA debt'). 

We also had our participants show us where they might find their debt letters, and our results were a little everywhere:
- The blue hub area on the home page drew most attention, no participant ventured into the primary navigation
- Six participants stated that they'd look beneath the specific benefit hub
- Five participants narrowed in on 'View your payment history' 
- Three participants stated they'd look beneath the 'Records' hub
- Two participants stated that they'd expect the debt letters in their Profile or My VA
- Two participants stated that they would use the search feature
- One participant said they would specifically look for a 'Financial' hub

Please let me know if you need any clarification on any of these points!

[V2 prototypes can be found here](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages//simulate/no-panels?mode=i)

**Comment by mnorthuis** [comment]
@leahkeeler Would you prefer to close this issue from the first iteration and start a new issue for the work on the latest debt management features/content?

**Comment by leahkeeler** [comment]
@mnorthuis Yes, I am closing this -- FSR is a whole different animal
