### ISSUE TITLE
Contact Center Review for [Burial - Action Needed email]

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#96873]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The Pension team is now responsible for the 530EZ  Burial benefit online application.  We've added a new notification, an Action Needed email notification that is sent to the applicant when the application submission fails in downstream process and cannot be resubmitted automatically. Have updated the last page of the Product Guide accordingly and am providing it here for your review.

### Launch Date
Target launch date 11/.12/2024

### Version Number
Burial.benefit.form.-.Product.Guide.-.111224.docx

### Product Guide
[Burial benefit form - Product Guide - 111224.docx](https://github.com/user-attachments/files/17718831/Burial.benefit.form.-.Product.Guide.-.111224.docx)

### Product Video
n/a

### Product Video Transcript
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The draft looks good. Sending for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. The working copy is attached for future revisions; please use it. Thank you!
[Burial.Benefit.Form.530EZ.Product.Guide.v2_SRT 11122024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenU1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc74accccd8d4c430ec2921fd29394469c6d6f97/Burial.Benefit.Form.530EZ.Product.Guide.v2_SRT%2011122024.docx)
