### ISSUE TITLE
Investigation:  "No data" warnings for Missing Pega Status monitor

### ISSUE THREAD

**Issue by stevelong00** [department-of-veterans-affairs/va.gov-team#96875]
The [Missing Pega Status monitor](https://vagov.ddog-gov.com/monitors/263380) has not resolved to an "OK" state when there are no missing Pega statuses since September.  Instead, it goes into a "no data" state which will trigger a warning in our slack channel.

The metric that this monitor is watching, [vets_api.statsd.ivc_champva_forms_missing_status_count](https://vagov.ddog-gov.com/metric/explorer?fromUser=true&start=1728745610089&end=1731427610089&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgViBpOGPIQAHQaCJ4aUM0QFZlOmYxR8hWpru71qhAaGqIwae0IePWZ+CIIwABUPCA8ALpUY6p4mKHhh8cYMaXxO-sgbVhoOaDyGE8ICDlJOHOZJzOZRJoURwJxyRTKdLAqBAkFOehMZQiNweNA7fhTeSYLBghRfYEiJR7Hh8e5Y8QAYSkwhgKBExzQPCAA), is also returning "no data" when it is expected to return 0.

Acceptance criteria
- [ ] Document why this metric and monitor return "no data" instead of 0 or OK when there are no missing Pega statuses
- [ ] If there is an obvious fix, create a ticket for implementing it.  Otherwise create a follow up investigation ticket for determining how to fix this.
- [ ] If no obvious fix after two days, revisit with team

**Comment by stevelong00** [comment]
[Over in slack](https://dsva.slack.com/archives/C06RQR7V9CM/p1732738055148989?thread_ts=1732662105.748119&cid=C06RQR7V9CM), Steve Albers suggested that adding a default_zero function to the query will result in period of time with no data showing as zero (green) instead of empty (gray).  This may be an easy workaround.

**Comment by michaelclement** [comment]
I went ahead and tried out the default zero function on our staging monitor ([message in Slack here](https://dsva.slack.com/archives/C06RQR7V9CM/p1733172772104499)). Now when we have "no data" (i.e., nothing is missing a Pega status as far as I understand it) we see a green zero + a "recovered" message in Slack:
|Count|Recovered Msg|
| - | - |
|![Image](https://github.com/user-attachments/assets/adcf7297-11c3-4c07-933d-836b20730d47)|![Image](https://github.com/user-attachments/assets/524ee140-0594-4394-8f12-be6f1a6daa5f)|

**Comment by michaelclement** [comment]
@stevelong00 @cloudmagic80 @reiting Any thoughts on the above? How do we feel about this update?

CC @baltes @andrea-merrill
