### ISSUE TITLE
Qualitative Data Request for 10-10 team

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#96882]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

10-01-2024

### Date Range End

10-31-2024

### Product Name(s)

10-10 CG, 10-10EZ, 10-10EZR

### Product Description

- The 10-10CG is the application to apply for the Program of Comprehensive Assistance for Family Caregivers
- The 10-10EZ is the application to apply for Veteran Health Care benefits
- The 10-10EZR is the application to update your VA health benefits information

### Survey URL(s), key term(s), case category or type

URLs: Everything under and including the following paths:

- `va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/`
- `va.gov/health-care/apply-for-health-care-form-10-10ez/`
- `va.gov/my-health/update-benefits-information-form-10-10ezr/`

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

None

### VA Email Address(es)

luis.simauchi@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.
