### ISSUE TITLE
21-22a authorizations reference 21-22 legal language

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96896]
## Expected vs. Actual
**Expected**: On the authorization screens, the legal language in the accordions should match the legal language on respective 21-22 or 21-22a forms. 

**Actual**: On the authorization screens, the legal language in the accordions (for the medical and address authorizations) are referencing the 21-22 form. Even if an attorney or claims agent is selected for completion of a 21-22a form, the legal language references the 21-22 legal language. 

## Steps to Reproduce
1. Select a representative that is a claims agent or attorney
2. Navigate through the representative experience until you get to the authorization chapter
3. Expand the legal accordions and compare those with the content in the 21-22a form

## Examples
Reference the [21-22a form](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf) for the expected content.

## Tasks
Ensure the legal content is updated for the 21-22a experience:

- [ ] authorize-medical
- [ ] authorize-address

**Comment by jvcAdHoc** [comment]
I'm going to bump this estimate up to a 3 because I needed to make a bunch of custom components and write unit tests for them

**Comment by oddball-lindsay** [comment]
21-22a legal content is looking right and I double checked the 21-22 path -- also looking right.

Thanks @jvcAdHoc!
