### ISSUE TITLE
Design feedback - Usability Testing Prep: STEM Stand-alone (VA Form 22-10203)

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#9690]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**

- On the review page, the “edit” button seems larger than the average size. There should be 16px around either side, you can follow the edit button size on the expandable form card in the sketch library 

**Try:**

- No “try” feedback for now

**Consider:**

- No “consider” feedback for now

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by ccruzgra** [comment]
Hi @CrystabelReiter we've incorporated your "Do" feedback and updated our prototype. Thanks so much for catching that!

**Comment by CrystabelReiter** [comment]
@ccruzgra Thank you for the awesome work! Closed~
