### ISSUE TITLE
CT-EYB: Update non-VETTEC profile page accordions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9691]
As a comparison tool user, I need to clearly understand how to update my estimated benefits so that I have accurate information to reference when deciding how to use my education benefits.

## Assumptions:
1. This work is completed behind a feature flag #7780.

## Acceptance Criteria
1. The "Calculate benefits" button is removed.
2. Each accordion grouping has an “Update benefits” button.
    a.	The "Update benefits" button is disabled by default.
    b. The "Update benefits" is enabled once a change has been made to any inputs.
    c. The button is disabled after click until another input change has been made.
3. The following instructional content is displayed above the accordions:
    a. For non-OJT/non-VETTEC: "The 4 sections below include questions that will refine your benefits estimate.  Use the fields in each section to make your updates."
    b. For OJT: "The 3 sections below include questions that will refine your benefits estimate.  Use the fields in each section to make your updates."

## Supporting Artifacts:
1. [GIBCT EYB - Schools - v0.3 Post-UT](https://bahdigital.invisionapp.com/share/SDIADYE8CVM)
2. [GIBCT EYB - Schools - Mobile - v0.3 Post-UT](https://bahdigital.invisionapp.com/share/Q6IADXOGVA3)
3. [GIBCT EYB - Employers - v0.2 Post-UT](https://bahdigital.invisionapp.com/share/SPIADYG4BUE)
4. [GIBCT EYB - Employers - Mobile - v0.2 Post-UT](https://bahdigital.invisionapp.com/share/9ZIADYIGHYV)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12957

**Comment by sonntag-adam** [comment]
Moving back to in progress as we decided that we want the "Update benefits" to be disabled when reverting back to the original selection.

**Comment by desireeturner** [comment]
The above change will be covered in a separate story. Moving this back into validate.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-08 at 11.48.41 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/02b47e19-ec97-4695-85c8-aa1eeea59a06)
##
![Screen Shot 2020-06-08 at 11.48.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/030541f8-dce7-4156-a4e5-a822b04b94d4)
##
![Screen Shot 2020-06-08 at 11.48.56 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9bead58a-ab5b-4bfc-bf77-db25f22ff1ac)
##
![Screen Shot 2020-06-08 at 11.49.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/db1f65fe-ec71-4888-b7d6-984e04060691)
##
![Screen Shot 2020-06-08 at 11.49.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a593154c-b802-48de-89b4-cc5acc0827c5)
##
![Screen Shot 2020-06-08 at 11.49.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f8a616be-f646-404d-b79b-172ba1f18f5c)
##
![Screen Shot 2020-06-08 at 11.49.28 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/83aad3f9-1d8b-45d3-96ce-a05e23e791e6)
##
![Screen Shot 2020-06-08 at 11.49.35 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/95adbe08-de82-4e74-b75e-13948bd834e6)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-08 at 11.52.22 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9c8e0b40-7795-4dc9-b50a-ef37c262bd5b)
##
![Screen Shot 2020-06-08 at 11.52.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1ec66514-6091-483c-965c-b6c3911ea3b5)
##
![Screen Shot 2020-06-08 at 11.52.35 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e4cb1184-99ed-415c-a092-ae6972daa56d)
##
![Screen Shot 2020-06-08 at 11.52.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3ea1330b-aaca-4f55-884a-5cf7e9389ee0)
##
![Screen Shot 2020-06-08 at 11.52.49 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c6347278-1b2a-4231-b429-841146fed8ca)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/462&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam, @JenLJ and I took a look, and this checks out!

**Comment by sonntag-adam** [comment]
Closing out story.
