### ISSUE TITLE
Adding Kevin Suarez to DSVA Slack

### ISSUE THREAD

**Issue by smythe5** [department-of-veterans-affairs/va.gov-team#96910]
- Please add kevin.suarez1@va.gov as a single-channel guest to mhv-on-vagov-cartography-team

Kevin is a software engineer on this team. Thank you.

**Comment by smythe5** [comment]
Hello - wanted to follow up on this request. Thank you in advance for your help.

**Comment by jenniferbertsch** [comment]
Hi @smythe5 and Kevin - I'm not sure who either of you are.  I would recommend reaching out to the COR for your contract.

**Comment by smythe5** [comment]
Thank you for the response @jenniferbertsch . I am the Delivery Coach at Agile Six and am helping onboard Kevin to the team (new engineer) while Lynne is on PTO. When I have made these requests in the past and they have stalled, VA POs have been able to help push the request through. It's ok if you are not able to do that. Thank you again for your response.

**Comment by amylai-va** [comment]
@smythe5, another option is following up in the the `#slack-workspace-admin` slack channel about this request.

**Comment by smythe5** [comment]
Hi @amylai-va. I put the request in the slack admin channel before your suggestion with no response.

**Comment by jenniferbertsch** [comment]
@smythe5 - I'd also recommend reaching out to the COR and the govt enabling people on Kevin's team (health?  cartography?).

**Comment by LynneJohnson224** [comment]
@LEHigley @KevinMHoffmanUSDS @KevinMHoffmanUSDS - Kevin is a new engineer on the cartography team. Can you please approve this request?

**Comment by LynneJohnson224** [comment]
@KevinMHoffmanUSDS - can you please update Kevin's access to make him a multi-channel guest. He'll need to join multiple channels. Thank you!
