### ISSUE TITLE
POA request accept/decline flow - pilot design

### ISSUE THREAD

**Issue by eheintzelman** [department-of-veterans-affairs/va.gov-team#96920]
### Issue Description
Based on guidance from the collab cycle midpoint review, we should move the decline workflow out of modals because it is asking a couple of follow-up questions. The modal approach introduces accessibility issues. 

There is a conditional field that displays when a user selects "other" for decline reason. Confirm that this is ok with platform to display this conditionally. 

### Acceptance Criteria
- Revised design moving the decline flow out of a modal and onto a full page.

**Comment by Kate-allbee** [comment]
[Figma File Link](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=1528-82958&t=buK70cHqcEDx9w0L-1)

**Comment by Kate-allbee** [comment]
[Design handoff figma](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=1874-115980)
