### ISSUE TITLE
[0781 PS] Screener Page Skeleton

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#96933]
## SOFT BLOCKED

To deploy, we will need our 'data solution' sorted out. That work is handled in the 'FE / BE' boiler plate work

- department-of-veterans-affairs/va.gov-team#97063 

### Description 

Estimated Entry Point: 2.1 

Estimated Exit Point(s): 3.4, 3.3, 3.1d

Add a skeleton screener page per the design docs to unblock all functionality. No content or style requirements.

## Acceptance Criteria

- As a user arriving at the correct endpoint (see endpoint doc)
  - I am presented with the following
    - 3 choice checkboxes
    - navigation options
  - Selecting any permutation of these choices and clicking `Continue` will result in the routing defined in the [Design Tiles](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9250-77233&node-type=section&t=cq2aZY2Q6NtYsS5V-0) document.
  - Navigating away from the page and returning to it should persist my previous choices
    - TBD: confirm this with design

[See the Planning Doc for more info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/0781_paper_sync_plannig.md)

**Comment by freeheeling** [comment]
PR marked as Ready for Review.

**Comment by lisacapaccioli** [comment]
Entry point is after POW question.

**Comment by lisacapaccioli** [comment]
@freeheeling - Does this ticket include what it should do (error message) if the user selects both a condition and that they are not claiming any MH conditions?

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
