### ISSUE TITLE
If blank, omit Middle Initial and Suffix from Terms and Conditions

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#96940]
## Expected vs. Actual
**Expected**: Leaving the middle initial and suffix blank omits those fields from being mentioned in the Terms and Conditions statement.

**Actual**: If you leave the middle initial and suffix blank, they are still referenced in the Terms and Conditions statement, but as "undefined". (I, the claimant Lindsay undefined Li-Smith undefined hereby appoint...)

## Steps to Reproduce

1. Select "I'm a Veteran"
2. Enter first and last name only in the Veteran info screen (leave the middle initial and suffix blank)
3. Navigate to the Review page
4. Expand the Terms and Conditions statement

## Examples
![Image](https://github.com/user-attachments/assets/0d0292c9-033a-4e1c-8e63-cc7ed807004b)

**Comment by oddball-lindsay** [comment]
This was flagged in Staging Review (not launch blocking): 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98994

Please close out the Staging Review ticket when this is complete!

**Comment by rjohnson2011** [comment]
PR open -> https://github.com/department-of-veterans-affairs/vets-website/pull/33649

**Comment by rjohnson2011** [comment]
![Image](https://github.com/user-attachments/assets/e4611c13-55fb-4c52-a724-71f7c27bdf1e)
