### ISSUE TITLE
CT-EYB: Update Numeric field default mobile keyboard

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9694]
As a comparison tool user on a mobile device, I need number fields to automatically give me a numeric keypad so that I don't have to switch keyboard layouts before entering my information.

## Assumptions:
1. This work is completed behind a feature flag #7780.
2. This work is constrained to display on mobile devices only.

## Acceptance Criteria
1. All fields that accept numeric inputs, prompt the user with a numeric keypad on field focus.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/12909

**Comment by ksantiagomorgan6** [comment]
Fields that will use the number keypad in EYB are:
Scholarships (excluding Pell)
Tuition and fees per year

Fields that will not are:
Zip Code

Zip Code will not use the keypad as it not a real number and can have leading 0's

**Comment by sonntag-adam** [comment]
Moving back to in progress as it needs Vettec as well.

**Comment by sonntag-adam** [comment]
Missing some fields, moving back to in progress
![Screen Shot 2020-06-04 at 12.32.50 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/67fa738f-01c7-488a-b7d0-65f3df6bffbd)
##
![Screen Shot 2020-06-04 at 12.36.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/eaf7d174-1bfe-443d-a6bc-13d46c0da642)
##
![Screen Shot 2020-06-04 at 12.37.49 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ad48ffa6-78f4-45bb-8ae3-c0aa51409ad5)

**Comment by ksantiagomorgan6** [comment]
Vettec Fields

Scholarship
Tuition and fees

**Comment by sonntag-adam** [comment]
![books.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b661cf9f-ea29-468f-aa26-22052899e145)
##
![buy up.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a5871393-49cf-41e4-afc9-66b2bb692527)
##
![In state tuition and fees per year.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e0f99bc6-30c8-4458-ba3a-ddfaf064bca9)
##
![Kicker.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9ff4445d-f01e-420b-a546-18eb9675e876)
##
![military tuition assistance.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5877467d-378b-4757-b984-cfac006f97a2)
##
![scholarships excluding pell.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/46c435ce-1327-40b7-be58-2d9e7f59048b)
##
![Tuition and fees per year.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b2be1855-019a-4db8-af40-0996756cb6d8)
##
![Yellow ribbon amoun from school per year.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3189a974-614d-40c1-ac20-46132542b233)
##
![vettec tuition and fees for program.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b79d78a8-11bf-4c21-8207-5068db736cf9)
##
![vettec scholarships.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fc5b017a-da12-4ccf-8637-ec134e4dec8f)

**Comment by sonntag-adam** [comment]
![books.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/592efc99-3cd0-471a-9953-d472b48dc165)
##
![buy up.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/649c615e-578e-4f9f-91eb-c9a457718803)
##
![in state tuition per year.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4dda672a-4caf-4312-922d-44cc8d6d5d40)
##
![kicker.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9ac9e8bc-3c81-4726-afb0-4bd8d5790133)
##
![Military tuition assistance.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7709fc67-3229-467a-868f-a6124d7cdbd4)
##
![Scholarship excluding pell.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/23118a04-b6bb-45db-a52d-b5d9365fb75e)
##
![Tuition and fees per year.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f5e98910-bf28-4c99-9109-6320e018b3f4)
##
![Yellow ribbon amount.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c2d796d4-325e-4b66-9f86-5155a58cb90b)
##
![vettec tuition.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5a8236b6-f000-4df6-86a7-335b70472410)
##
![vettec scholarships.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/47dc6f4f-54c7-405e-b132-39ec0338a3e5)

**Comment by sonntag-adam** [comment]
behind feature flag gibct_estimate_your_benefits

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/458&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam UXers took a look and this is good to know.

Just noting a defect Amy came across here that is present on iPhone/Android, but not desktop:

![Screenshot_20200605-130947.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/e0c24d1f-e38a-44b3-8b29-2085ed4d056f)

The checkbox is no longer working. You’re supposed to be able to check it and the zip code field goes away, but it’s coming back with an error message. If you try selecting a different location in a dropdown, then go back to the zip code field, the error message is still present there.

**Comment by sonntag-adam** [comment]
Defect was filed here but appears not related to the changes in this story. https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9872

**Comment by sonntag-adam** [comment]
Closing out story.
