### ISSUE TITLE
[Spike] - Setup DataDog to monitor Flipper feature toggles

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#96953]
## Background/Request
Flipper feature toggles can impact the Appointments application when disabled.  The Appointments application has several feature toggles that we don't want to remove but should always be enabled.  Therefore, we want to use DataDog to monitor these feature toggles and ensure they are not inadvertently turned off.

### Goal
- [ ] Identify long-term feature toggles to monitor.  These are feature toggles that we do not want to remove but should always be enabled.
- [ ] Determine how to use DataDog to monitor these feature toggles in Flipper

### Requirements to Consider
How do you access the feature toggle settings in Flipper?

---

## Tasks
- Answer the following questions:
  - Q: What feature toggles should be monitored?
  - Q: How do we access Flipper to monitor these feature toggles?
  - Q: What is the best way to set up DataDog to monitor these feature flags?

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by JunTaoLuo** [comment]
## Investigation notes:

> Q: What feature toggles should be monitored?

Luckily I recently did an inventory for all of our feature toggles and I'll summarize the findings here.

### Long term feature toggles (see details in https://github.com/department-of-veterans-affairs/va.gov-team/issues/95920)

These are confirmed to be used in our code and will be kept for long term control of our app

| Toggle | 
| - |
| `va_online_scheduling` |
| `va_online_scheduling_community_care` | 
| `va_online_scheduling_direct` | 
| `va_online_scheduling_requests` | 

### Potential long term feature toggles (see details in https://github.com/department-of-veterans-affairs/va.gov-team/issues/95919)

| Toggle | Notes |
| - | - |
| `va_online_scheduling_cancel` | This sounds like a toggle for long term use but I can only find its usage in a [component that is obsolete](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/CancelLink.jsx#L21) and [marked for removal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92993). |
| `va_online_scheduling_datadog_RUM` | [Feature ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63374) is closed as completed. Is this toggle intended to be for long term use? |
| `va_online_scheduling_sts_oauth_token` | [Feature](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76148) is fully released, but uncertain if this toggle is intended for long term use |
| `va_online_scheduling_vaos_service_cc_appointments` | Looks like the use of this toggle was for v2 migration. If this is intended as a long term use toggle, we should consider using `va_online_scheduling_community_care` instead. |
| `va_online_scheduling_vaos_service_requests` | Looks like the use of this toggle was for v2 migration. If this is intended as a long term use toggle, we should consider using `va_online_scheduling_requests` instead. |
| `va_online_scheduling_vaos_service_va_appointments` | Looks like the use of this toggle was for v2 migration. If this is intended as a long term use toggle, we should consider using `va_online_scheduling_direct` instead. |

> Q: How do we access Flipper to monitor these feature toggles?

I believe the best way to monitor the modification of these toggles is to use Flipper's [instrumentation feature](https://www.flippercloud.io/docs/instrumentation). Currently this is used to log feature toggle events in vets-api [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/flipper/instrumentation/event_subscriber.rb). We should be able to use this mechanism to add DD monitoring and alerts for flipper toggle changes.

> Q: What is the best way to set up DataDog to monitor these feature flags?

Using the Flipper instrumentation feature as a trigger, we can send events (e.g. `va_online_scheduling_disabled`) to DD via our regular logging mechanism like all other vets-api DD events. We can then set up monitoring for when such events are triggered and send a message to our alerts channel. Note that for each feature toggle, we should set up monitoring for "disable", "remove", "clear" Flipper events.

**Comment by JunTaoLuo** [comment]
@JRRoof can you help take a look at my notes for Q1 and @simiadebowale can you take a look at Q2, Q3? Thanks in advance for helping validate this ticket!

**Comment by simiadebowale** [comment]
@JunTaoLuo - questions 2 & 3 LGTM!

**Comment by JRRoof** [comment]
Add `va_online_scheduling_cancel` to the long term list for monitoring.  `va_online_scheduling_datadog_RUM` & `va_online_scheduling_sts_oauth_token` should not be kept long term.

**Comment by JunTaoLuo** [comment]
> Add `va_online_scheduling_cancel` to the long term list for monitoring.  `va_online_scheduling_datadog_RUM` & `va_online_scheduling_sts_oauth_token` should not be kept long term.

Thanks, I've updated https://github.com/department-of-veterans-affairs/va.gov-team/issues/95919 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/95920 to reflect these updates.
