### ISSUE TITLE
10-7959f-2 Require email on FMP claim cover sheet

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96995]
As the VA, I need a way to contact users to let them know there has been a silent failure.

### Acceptance criteria
- User is unable to submit the form without including their email

**Comment by reiting** [comment]
<img width="1166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNERJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f50a9a195701324e2ad1bbeec6e44fb33c0743c/Screenshot%202024-11-18%20at%2010.14.11%E2%80%AFAM.png" alt="Screenshot 2024-11-18 at 10.14.11 AM.png" />

**Comment by jamiefiore** [comment]
@reiting I couldn't review that screenshot but I looked on staging and everything looks good. Thanks!

**Comment by reiting** [comment]
@baltes this is ready to be reviewed!
