### ISSUE TITLE
Update alert [User is registered at 2+ facilities - dead ends] - Part 2

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#96996]
## Description
Update alert on choose a VA location page. 
Alert can be reproduced: when multiple facilities are configured for appointments but patient has no Past Appt & Direct Schedule Configured

**Scenario:**
- DS is enabled
- Facility requires a recent visit
- AND User doesn’t have a recent visit (VATS: noRecentVisit)
- AND Requests are disabled

**Current Alert state**:

<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3U0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87fd941131a9cb24cf12a3ff825612e79c28da09/Screenshot%202024-11-13%20at%2010.53.43%E2%80%AFAM.png" alt="Screenshot 2024-11-13 at 10.53.43 AM.png" />

**Desired Alert state**:

<img width="231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGE0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--180b594f48c37fe295c6657c91da4eb303ead0b9/Screenshot%202024-11-13%20at%2010.59.26%E2%80%AFAM.png" alt="Screenshot 2024-11-13 at 10.59.26 AM.png" />

**Content**: 
You can’t schedule an appointment online at this facility
You haven’t had a recent appointment at this facility, so you’ll need to call to schedule instead. 
 [Facility] Main phone: [###-###-####](TTY: 711)  Or you can choose a different facility.

[Figma Design](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=6117-31863&node-type=section&t=naRxagCiybY7GmOa-0)

---

## Development Checklist
No toggle required for this work

- [ ] Alert is updated.
- [ ]  Update unit tests
- [ ]  Update/create e2e test

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by jenniemc** [comment]
@melissa-lefevre This is ready for validation

**Comment by melissa-lefevre** [comment]
@jenniemc Looks good, no issues

**Comment by jenniemc** [comment]
Closing ticket.
