### ISSUE TITLE
IA Feedback - Usability testing prep - STEM Stand-alone (VA Form 22-10203)

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#9699]
## VSP IA Feedback

**Feedback framework**
- *Must* - feedback must be applied 
- *Should* - feedback is best practice 
- *Consider* - suggestions/enhancements

**Must**
- As part of the user research, include a task that looks at how/where users would look for the new tool/application within the VA.gov experience.  The goal is not to pinpoint an exact path or location, but to understand the users' mental model around the topic - where on the site do they look, where/how do they navigate around, what terms do they use when talking about it or searching on va.gov.
- While the URL and breadcrumb will be finalized once research is complete, the prototype should reflect the proper structure as accurately as possible.  All of the education applications live today have an old structure that was not updated with the WBC work and we do not want to perpetuate it. 
  - Please update the breadcrumb to:  Home > Education and training > Other education benefits > Rogers STEM Scholarship > Apply 

**Should**
- This standard content structure and user flow for applications includes a static content page that includes information like eligibility and how to apply.  Currently this content exists on a legacy Team site page, but as part of the build it will need to be moved into Drupal.  For research, it is extremely helpful to include this content page so users can experience the full user flow (landing page then application) and can react to all of the content and process. 
  - An example of this structure is the National Call to Service application and content page: https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/

**Consider**
- There is currently work in flight to move the How to apply "wizard" off the static content pages and on to the first page of the application (the introduction page).  You could consider representing this new flow in the test. 
  - Flow would be  STEM static content page --> Click apply now button --> Application introduction page displayed --> user validates they are in the right place using the wizard --> user clicks start application

## Definition of Done
- [x] Feedback is acknowledged by the designer(s) and incorporated into designs and conversation guide
- [x] Responses to questions provided in comments below
- [ ] Issue is closed by VFS team

**Comment by amyknox** [comment]
@dneel-bah - see MUST #2 for requirements guidance on STEM Form breadcrumb

**Comment by amyknox** [comment]
@mnorthuis 
Thanks for the input. We're incorporating Must # 1 into our discussion guide and I tagged our BA for Must # 2.  

Should: The kickoff earlier for Ratings was our first intro to the content support team. Sounds like we may want to loop them in to help update / migrate the STEM copy on benefits.va.gov over to VA.gov. I'll check on this end to see about getting the ball rolling. 

Consider: Not sure I understand this... Are you saying that each application intro is going to include the same wizard that directs users to a form?  I thought the point of having it on the apply page was to help direct people, who didn't know where they were supposed to be, to the form they needed.   Do you know the timeframe for making that update?

**Comment by dneel-bah** [comment]
Must # 2 is captured in #9755

**Comment by mnorthuis** [comment]
@amyknox  Yes, the wizard will be placed as part of every application rather than managed on static pages.  This allows us to deep link to specific applications when needed, but still makes sure the user is at the right application.  Timeframe for implementation varies across the different benefit types.  You can discuss with Matt, he is aware of the proposed change and can possibly speak to when it will happen within Education.

**Comment by dneel-bah** [comment]
@mnorthuis We have some questions/confirmation regarding the breadcrumb.

> Home > Education and training > Other education benefits > Rogers STEM Scholarship > Apply

**Home** link: https://staging.va.gov/
**Education and training** link: https://staging.va.gov/education/
**Other education benefits**:
    - Should this link here: https://staging.va.gov/education/other-va-education-benefits/ ?
    - If that is the correct page, should the breadcrumb be: "Other VA education benefits"
**Rogers STEM Scholarship**:
    - Where does this link to?
**Apply**: 
    - Read only part of breadcrumb
    - Is displayed when the user is on this page: https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction

**Comment by mnorthuis** [comment]
@dneel-bah Answers to your questions, let me know if you want to talk through any of this or if anything isn't clear.  All of this will be detailed out in the final IA work as well, which isn't typically complete until all research is done.   

**Other education benefits**
- Yes, it should link here: https://staging.va.gov/education/other-va-education-benefits/
- Yes, thank you for catching the correct labeling "Other VA education benefits"

**Rogers STEM Scholarship:**
- This will link to a new content page as part of the "should" recommendation above.  I would have put this one under "must" but it does require some communication with stakeholders around retiring of their current page and pulling it into Drupal.  The Public Websites team would help with this process. 
- URL may be something like this (not final yet)  /education/other-va-education-benefits/rogers-stem-scholarship/

**Apply:**
- The URL should not follow the structure that is used currently by other education applications, as they have not been updated since the migration work.  
- URL is not final until we work through the full IA, but would be something like:  `/education/other-va-education-benefits/rogers-stem-scholarship/apply-for-scholarship-form-22-10203/`  (/introduction would be appended for initial page)

**Comment by amyknox** [comment]
@dneel-bah Think this can this be closed as we have breadcrumbs & URLs documented elsewhere.

**Comment by amyknox** [comment]
Musts

- [ ] Including question about how users will navigate to the form in user research. 
We included questions about how users would navigate to the form in our first round of testing.  [Research readout is available here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/research/22-10203-RogersSTEMScholarship-TestingReadout-20200611.pdf).   


- [ ] Prototype should reflect the proper structure.  
Working on accurately reflecting the breadcrumb 100% of the time.  

Should
- [ ] For research, it is extremely helpful to include the STEM content page so users can experience the full user flow (landing page then application) and can react to all of the content and process.

We did not include this content in our research.
 
Consider
- [ ] There is currently work in flight to move the How to apply "wizard" off the static content pages and on to the first page of the application (the introduction page). You could consider representing this new flow in the test.
Flow would be STEM static content page --> Click apply now button --> Application introduction page displayed --> user validates they are in the right place using the wizard --> user clicks start application

We are aware of this work and supporting the team's effort.

**Comment by dneel-bah** [comment]
@mnorthuis Amy provided feedback to each of the items above.  The static page is live and the breadcrumbs have been updated accordingly.  Can this issue be closed out?
