### ISSUE TITLE
Launch Education Analytics MVP

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#97]
## Story
As a VA Product Owner, I need to easily understand how the tools I own are performing so I can make informed product decisions based on data.

## Problem
1. Currently, the analytics for our tools are spread across multiple services (GA, Prometheus, Call Center, Foresee) making them difficult to easily access.
   - Sometimes the data doesn't exist or VSP doesn't currently have access
   - Some tools require complicated authorization to access (SOCKS proxy, etc.)
2. Currently, the event triggers and other monitoring tags aren't easily understandable because they are outputs from engineering based services rather than written in plain language.

## Objectives
1. Create a Product Health Prototype starting with Edu data to test with Edu product owners and 
understand whether the MVP helps them understand the health of their products they own. 

## Tasks
- Identify what data we want to show to stakeholders [Engineering]
   - can we get that data programmatically (realtime?)
   - links back to analytics 
   - what is the right tool for the job (prometheus)
- Create a research plan to test the Analytics MVP [Research Plan]
- Create translations between event tags and their plain language meaning
- Define thresholds for **product health** and apply them to the Analytics MVP to help product team members quickly view when their product is not meeting VSP expectations

**Comment by joanneesteban** [comment]
Education product health tool has been created. Pivoting to add more products to the tool
