### ISSUE TITLE
PM and Front-End Engineers: Request analytics intro

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#970]
Check box below when complete and comment "done" 

- [x] PM and Front-End Engineers: Request analytics intro

**Comment by Justin-Pickett** [comment]
I will see who we need to schedule this with. Stay tuned.

**Comment by Justin-Pickett** [comment]
@nedierecel and @joanneesteban will be getting this intro session set up.

**Comment by Justin-Pickett** [comment]
Done.

**Comment by erikphansen** [comment]
done

**Comment by mojaray2k** [comment]
done

**Comment by Justin-Pickett** [comment]
This task has been completed. Closing this ticket.
