### ISSUE TITLE
10-7959f-2 Enable confirmation emails for FMP claims

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97000]
Verify whether we need this.

As a user submitting an FMP claim, I need to receive an email confirmation when my claim has been imported to PEGA

### Acceptance criteria
- Template is created
- Template ID is added to param store
- vets-api is calling VA notify API to send email when callback is received.

**Comment by michaelclement** [comment]
Staging VA Notify template ID: `63c023ac-147a-481b-be2a-697bdafc2c5c`

**Comment by cloudmagic80** [comment]
<img width="1242" alt="Image" src="https://github.com/user-attachments/assets/542fd947-8666-4e4d-b604-cf53bd69e84b" />

**Comment by cloudmagic80** [comment]
@baltes  Most of the work seems already done. We just need to migrate into production.

**Comment by cloudmagic80** [comment]
<img width="889" alt="Image" src="https://github.com/user-attachments/assets/102ea932-44f2-47e7-a658-0e19cf8cb0a3" />
