### ISSUE TITLE
10-7959c Enable confirmation emails for OHI certification

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97004]
As a user submitting an OHI certification, I need to receive an email confirmation when my form has been imported to PEGA

### Acceptance criteria
- Template is created
- Template ID is added to param store
- vets-api is calling VA notify API to send email when callback is received.

**Comment by michaelclement** [comment]
Staging Template ID: `e85f8d64-484e-494b-8af5-a8370b21d216`

**Comment by baltes** [comment]
completed
