### ISSUE TITLE
Rework secondary nav to see if we can include more options

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#97018]
## Description
Make the MHV secondary nav scalable (to include more than just 4 health tools, and more likely to be added later)

[Link to Figma file](https://www.figma.com/design/6nWnlJUjSK91V9hjc3p0LN/MHV-Secondary-Nav?node-id=1404-47165)
[Research framing doc for in-team communication purposes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/2nd-comparison-study/research-frame.md)

### User story
As a Veteran, I want to access all health tools including copay payment and travel reimbursement from anywhere within the portal. 

### Notes
- When we started looking into a persistent-link secondary nav, one of the major causes for concern about the design was that it could not hold/include ALL health tools (only 4 plus the home page would fit)
- Tools to (possibly) add: medical supplies, travel reimbursement, copay payments, 10-10 EZR to update health care (maybe?); likely to be more as time goes on

Possible tasks:
- [x]  Facilitate sync with UXR to understand scope, research opportunities, and design next steps.  
- [x] Review the research and possibly metrics on secondary nav as needed
- [x] Redesign the secondary nav in Figma to allow for more than 4/5 options 
- [ ] Consider what we might take to a research study surrounding this discovery effort 

## Acceptance criteria
- [x] "Best" design for including more options within the secondary nav is fully designed in Figma

**Comment by sterkenburgsara** [comment]
Mentioned in planning that we may also want to consider taking any feasible designs that come out of this discovery effort to a prototype / research.

**Comment by athenabozak84** [comment]
During Planning/Sync, I mentioned that I could take the lead on this story. I’m currently familiarizing myself with various resources, including Figma files, the design system, and prior research. As a result, this ticket might take me a bit longer than expected to complete.

**Comment by mcarterA6** [comment]
Hi @fmccaf1 @athenabozak84  - Could "all health tools" be defined in this ticket to help further define the tasks and determine if additional tickets might be needed to support this work?

**Comment by fmccaf1** [comment]
Looks like Sara probably beat me to it. There's a list in the notes section of the ticket @mcarterA6

**Comment by athenabozak84** [comment]
Documentation: 

[This Mural]((https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1733362395294/5a4d58bb840fca5882c2bbd6d4cf28b037ce79bc?sender=u2878355c354ebda53a202035) consolidates metrics derived from Veteran tasks and behavior patterns, incorporating Medallia feedback and prior research insights to inform and guide upcoming design decisions.

**Comment by fmccaf1** [comment]
@athenabozak84 it looks like your mural link just downloads as a pdf instead of bringing me to your board. Would you mind switching it out?

**Comment by athenabozak84** [comment]
Mural artifacts & insights link: https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1733362395294/5a4d58bb840fca5882c2bbd6d4cf28b037ce79bc

**Comment by fmccaf1** [comment]
@jonathanjnelson Would love your thoughts on designs and see if you have any ideas I didn't mock up!

**Comment by fmccaf1** [comment]
@athenabozak84 [here's the link to the GH doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/2nd-comparison-study/research-frame.md) I created today. It's very basic/bare bones. If there's anything you think of that is missing, let me know!

**Comment by mcarterA6** [comment]
Hi @fmccaf1 and @athenabozak84 - Once Jonathan completes his review are there any addition tasks that will be needed to complete this by the end of the sprint (12/19)?

**Comment by athenabozak84** [comment]
@mcarterA6: Pending Jon’s design review, I believe all other tasks are complete at this point. Florence and I have our sync on Thursday where I anticipate we’ll address this ticket and move to "done" once we've aligned. The next ticket is already in the queue for usability testing research plan.

**Comment by mcarterA6** [comment]
@athenabozak84 - Solid! With the sprint ending on tomorrow, 12/18, would it be possible to have the sync before Thursday? Or maybe we could split out one point from this ticket to carry into the next sprint to account for you and Florence's review. Let me know what works best for you.
