### ISSUE TITLE
Design 10-7959c Add and require email on OHI certification

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97037]
For zero silent failure purposes, an email address field must be added to the OHI form and it must be a required field.

### Acceptance criteria
- Design recommendation for adding the new required field, accounting for any impact to current flow
- User is able to enter an email address on the form
- User is unable to submit the form without including their email

**Comment by jamiefiore** [comment]
@rspope Here's the [Figma](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3517-41593&node-type=frame&t=h2pfubCM8EytP0rs-0) for this. I wanted to chat about this quickly if we have time to make sure my thinking tracks before I show this during the Monday Design/Product sync.

**Comment by jamiefiore** [comment]
This was approved to go forward for launch by product, Lois and Premal . Here is the[ figma file](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3517-41585&node-type=canvas&t=xYvXVQ8QiMZQmnQz-0)
