### ISSUE TITLE
Sidekiq Admin UI access for Jennica Stiehl

### ISSUE THREAD

**Issue by stiehlrod** [department-of-veterans-affairs/va.gov-team#97036]
### Your Name

Jennica Stiehl

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@stiehlrod

### Your dsvagovcloud AWS user name (if applicable)

Jennica.Stiehl

### Team, Role, and Company of the target individual

Dash, Software Engineer II. Oddball

### COR Name

Cecila Lee

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [x] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [x] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] I currently have access to vets-api Production Terminal via ArgoCD
- [x] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

Previous Requests:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/62000
https://github.com/department-of-veterans-affairs/va.gov-team/issues/54535
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43642

![Image](https://github.com/user-attachments/assets/0be7d864-5512-404d-9387-88f755dcac8f)

**Comment by bdech** [comment]
confirmed in Atlas
E-QIP confirmed

**Comment by bdech** [comment]
@stiehlrod  You’ve been granted access to the `sandbox` environment. You already have access to `dev`, and `staging`.

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by bdech** [comment]
@stiehlrod Can you please provide one to two sentences on why you need access to production?

**Comment by stiehlrod** [comment]
@bdech I need access to prod so I can troubleshoot background jobs when I am on prod support.

**Comment by bdech** [comment]
Thank you

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@stiehlrod You've been granted access to `Production`, with access to limited to 6 months, expiring 5/13/25.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
@stiehlrod  Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.
