### ISSUE TITLE
AWS access for Jeff Marks

### ISSUE THREAD

**Issue by jefftmarks** [department-of-veterans-affairs/va.gov-team#97047]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Jeff Marks

### Your Email

Jeffrey.Marks@va.gov

### Team, Role, and Company of the target individual

Education Data Migration (EDM), backend developer, GovCIO

### Product Manager (PM) name and email

Renee Blanchard, Renee.Blanchard@va.gov

### Product Owner (PO) name and email

Darla van Nieukerk, Darla.vanNieukerk@va.gov

### Desired AWS Access

I need access to upload rsa key to parameter store to establish connection between vets-api and DGIB claimant-service. I would also like to request access for teammate tech lead Vanson Samuel, Vanson.Samuel@va.gov, @binq 

### Access Expiration

May 2025 (end of contract)

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/a964b0a6-6be3-4269-a8c7-e22d750fa850)

### Additional Notes

COR: Joseph Riccio, Joseph.Riccio@va.gov
Onboarding rep: Nikolas.Aberle@va.gov

Note: E-QIP transmittal confirmation is via my previous contractor. I have certificate of reciprocity from when I changed companies that I didn't need to redo investigation

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by ben-allen-oddball** [comment]
User is in atlas

**Comment by jefftmarks** [comment]
role: adhoc-vetsgov-ssm-prod role

**Comment by ben-allen-oddball** [comment]
Created PR: https://github.com/department-of-veterans-affairs/devops/pull/14849
