### ISSUE TITLE
Flipper UI access for Jane Cho

### ISSUE THREAD

**Issue by janechodance** [department-of-veterans-affairs/va.gov-team#97052]
### Your Name

Jane Cho

### Your GitHub handle (Flipper UI access is managed through GitHub)

@janechodance

### Team, Role, and Company of the target individual

Benefits Management Team 2, Frontend Engineer, Coforma

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

The change I am working on required a flipper flag. I need staging access first so I can test, and then production access is secondary.
[Image](https://github.com/user-attachments/assets/1306e49c-1a0f-483f-81ac-43d15d1dab40)

**Comment by lindsay-insco** [comment]
Access to `prod` and `lower environments` granted.

**Comment by GWright321** [comment]
Hello @janechodance looks like you were kicked from Prod. Can you try again please?
