### ISSUE TITLE
Flipper UI access for Stacy Wise

### ISSUE THREAD

**Issue by dysbo** [department-of-veterans-affairs/va.gov-team#97058]
### Your Name

Stacy Wise

### Your GitHub handle (Flipper UI access is managed through GitHub)

@dysbo

### Team, Role, and Company of the target individual

Benefits Management Team II, Engineering Lead, Coforma

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I'm requesting production access because I'll need to support the team on feature flag management in lower environments and in production.

Attached is the e-app transmittal screenshot:
![Image](https://github.com/user-attachments/assets/75048095-5558-494b-bafd-7e04a1a1ce04)

Let me know if I can provide anything else!  Thanks.

**Comment by lindsay-insco** [comment]
Access to `prod` and `lower environments` granted
