### ISSUE TITLE
[0781 PS] (2) JSON to PDF transform service

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#97064]
## SOFT BLOCKED

We can start building this, but it won't really be testable / deployable until we complete our JSON schema work

- department-of-veterans-affairs/va.gov-team#97061 

### Description

Form data stored in the InProgressForm table will need to be converted to PDF for final form submission. There are examples of how we do this in the resources section of this ticket

### Resources

- this new logic should be very simliar to the old logic in
  - [0781 transform](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/va210781.rb)
  - [0781a transform](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/va210781a.rb)

### Acceptance Criteria

- As a developer
  - I am able to call a service with realistic 0781 form JSON that generates a PDF
  - PDF should be saved to the correct data solution (s3?). Developer should determine this by comparison to existing service uses (see resources)

### Expected Deployments
- BE:
  - deploy unused service. No need for a flipper, as it won't be hooked up to anything on initial deployment
  - deploy updates as needed to integrate with InProgressForm model as **soft blocker** is resolved

[See the Planning Doc for more info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/0781_paper_sync_plannig.md)

**Comment by freeheeling** [comment]
[commit](https://github.com/department-of-veterans-affairs/vets-api/commit/65b5e7cfabcc2d202d929cf3e6795682c2226bd5)

**Comment by freeheeling** [comment]
Submitted [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19802)

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
