### ISSUE TITLE
[0781 PS] (2) FE / BE boiler plate (Forms / InProgressForm)

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#97063]
## ~~HARD~~ SOFT BLOCKED

We need the JSON schema defined before we can ~~build~~ deploy boilerplate around it. We can start defining the communication channel and check our work when the JSON schema is done.
- department-of-veterans-affairs/va.gov-team#97061 

### Description

As the Veteran fills out the new 0781 form online, that data will need to be persisted in our database. Most of this FE to BE communication is done for us with the InProgressForm model, so we will create a bare bones FE to BE integration using this model. This foundational work
will define how changes to the front end application are moved through the FE React store, API calls, as well as the BE Controller and Model layer. The goal in this ticket is to have an arbitrary FE form page successfully save form data in a new type of InProgressForm on the backend.

### Acceptance Criteria 

- As a developer
  - I am able to log into a test application page (FE) and submit a peice of arbitrary data
    - This data will be represented as an instance of the InProgressForm model on the backend.
    - When I return to this page, my data is still present

### Expected Deployments

- FE:
  - Boiler plate integration with Forms library
- BE:
  - Boiler plate integration with InProgressForm model
  - incorporate this new type of InProgressForm with the `disability_compensation_sync_modern_0781_flow` flipper as necessary.

**Comment by SamStuckey** [comment]
UPDATE: I think the Hard Blocker is actually a soft blocker here. I'm starting on this work to build the communication channel between the FE and BE, with the assumption that I may need to check my work against the schema before I deploy this

**Comment by SamStuckey** [comment]
UPDATE: added guidelines for subsequent work to the planning document:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/0781_paper_sync_plannig.md#guidelines-for-adding-new-pages

This should be looked at by every dev picking up tickets in this epic.

**Comment by SamStuckey** [comment]
UPDATE: moving this back to in progress. @freeheeling caught something I missed during review... this whole new 0781 flow does *not* go where the old one went, rather it's the first available tile in the entirely new 'Additional Forms' chapter. Therefor I think it's appropriate to re-namespace things under an Additional Forms entry point. This won't be much work

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
