### ISSUE TITLE
[0781 PS] (1) Define new 0781 JSON schema

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#97061]
### Description

Paper sync will require a digital representation of the form in our database. What we have right now is a copy of the new paper form.  We need to

- Define / agree on names & nesting for all the values
  - This should be as close to a copy of our old 0781 Schema as possible. Let's minimize in-flight optimizations and just get it done.
- Document that somewhere

### Acceptance Criteria

- We have a documented JSON schema based on this new [0781 Form](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=0#gid=0)
- The document is published in our  [private Github repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/benefits) for reference, and linked to this ticket
- There is a link to this ^^ document in this ticket

### Expected Deployments

None. 

[See the Planning Doc for more info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/0781_paper_sync_plannig.md)

**Comment by freeheeling** [comment]
**Resources**
- [Toxic Exposure Front End/Back End Contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)
- Swagger [submit_all_claim form526 param structure](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/postSubmitFormV2:~:text=/v0/disability_compensation_form/submit_all_claim)
- [form0781 object](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/95d29813b62abd4a450461497ea8d9ad9fb73e8b/src/schemas/21-526EZ-allclaims/schema.js#L710) in `vets-json-schema`

**New JSON**

```
ipf = InProgressForm.last
json = JSON.parse(ipf.form_data)
```

```
{"mental_health"=>
  {"conditions"=>
    {"tinnitusringingorhissinginears"=>true,
     "none"=>false},
    "view:additional_info"=>{}},
  "view:traumatic_events_info"=>{},
  "view:additional_info"=>false
},
{"additional_forms"=>
  ...
}
```

**Current 0781 JSON**
![Image](https://github.com/user-attachments/assets/a44f2f69-f06b-4a62-b967-06b2708ad796)

**Comment by freeheeling** [comment]
@SamStuckey Proposed JSON schema complete. Take a look and provide feedback. Thanks.

**Comment by kylesoskin** [comment]
@freeheeling are `additionalForms` and `mentalHealth` newly proposed top level keys in the `Form526Submission.form_json` structure? 

Or would these fall under the existing `form_0781` key? 
Or is this ONLY the structure for storing in the `InProgressForm`? We will need json structure defined for both saving the form progress in the in progress form, and for storing in the 526 submission json/sending to the 526 submit endpoint, Im not sure which this is here.

**Comment by freeheeling** [comment]
@kylesoskin – Yes, `mentalHealth` and `additionalForms` are the newly proposed top level keys in `form526`. The thought being that `mentalHealth` data are needed to determine whether the new 0781 flow is presented to the user. The `additionalForms` key is the name of the new UI step; it contains both the new `form0781` data as well as any future "Additional forms". 

I didn't consider placing these new keys under `form_0781` as I imagined that object eventually would be removed from the schema once all users were directed towards the new 0781 flow.

Does the structure defining how `InProgressForm` data are stored not also resemble the form data sent to the `submit_all_claim` endpoint? I haven't verified, but I'm not clear why that would be different, except for some transformation that may occur on submit from the FE.

**Comment by freeheeling** [comment]
```
{
  "form0781New": {
    "traumaticEvents": {
      "combat": true,
        "mst": true,
        "nonMst": true,
        "other": true
      },
    "events": [ 
      {
        "details": "I was mugged",
        "location": "Stationed on U.S.S. XYZ",
        "timing": "Summer of '70"
      },
      {  
        "details": "I was mugged again",
        "location": "Stationed on U.S.S. ABC",
        "timing": "Fall of '70"
      }
    ],
    "reports": [
      {
        "police": {
          "agency": "SVI",
          "city": "Dallas",
          "state": "Texas",
          "country": "USA",
        }
      },
      {
        "otherReport": {
          "description": "I lost all my money"
        }
      },
      {
        "restricted": true
      }
    ],
    "behaviors": {
      "reassignment": true,
      "absences": true,
      "performance": true,
      "consultations": true,
      "episodes": true,
      "medications": true,
      "selfMedication": true,
      "substances": true,
      "appetite": true,
      "pregnancy": true,
      "screenings": true,
      "socialEconomic": true,
      "relationships": true,
      "misconduct": true,
      "otherBehavior": "temper"
    },
    "behaviorsDetails": {
      "reassignment": "requested duty assignment",
      "absences": "used a lot of leave",
      "performance": "poor evaluations",
      "consultations": "increased visits to a counselor",
      "episodes": "severe depression",
      "medications": "stopped taking meds",
      "selfMedication": "stopped treating headaches",
      "substances": "increased alcohol consumption",
      "appetite": "skipping meals",
      "pregnancy": "negative tests",
      "screenings": "positive tests",
      "socialEconomic": "withdrawal",
      "relationships": "separation",
      "misconduct": "reckless",
      "otherBehavior": "frequent rage"
    },
    "evidence": {
      "crisisCenter": true,
      "counseling": true,
      "family": true,
      "faculty": true,
      "police": true,
      "medical": true,
      "clergy": true,
      "peers": true,
      "journal": true,
      "none": true,
      "other": {
        description: string
      }
    }
  }
}  
```

**Comment by freeheeling** [comment]
Documented JSON schema for reference is located [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/engineering_research/0781v2_schema.md).

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
