### ISSUE TITLE
[0781 PS] (5) Events Type Choice & Lead-in Pages Skeleton

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#97078]
## NEEDS REFINEMENT

- [x] we need the specific routing laid out for us by design / product. I thought it was in the Figma, but now I'm not seeing it?

### Description

Entry Point: 3.4, 3.5, 3.6

Exit Points: Complex, see Design Tiles diagram for more info

Adds 3 pages. the first two are just placeholders, there is no routing. The third is the choice between the 4 types of PTSD. This choice informs routing on the next page.

**note** There may or may not be any DB interaction here. We are not creating events, just routing users to the correct page based on their choices. Developer should determine if it's necessary to write anything to the form based on this choice, but my gut says no.

### Acceptance Criteria

- As a user visiting 3.4, I see a placeholder with navigation (Continue to 3.5)
- As a user navigating to 3.5 I see a placeholder with navigation (Continue to 3.6)
- As a user navigating to 3.6 I see four choices for event type
    - I make a selection
        - Continue button has conditional routing based on selections made (See Design Tiles for details)

### Expected Deployments
- FE:
    - form elements to create the appropriate routing based on user input

[See the Planning Doc for more info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/0781_paper_sync_plannig.md)

**Comment by SamStuckey** [comment]
READY: our 'needs refinement' question was answered.

[This document has the info](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-81505&node-type=section&t=gjpXc2hMSRVyHm4A-0)

**Comment by freeheeling** [comment]
Page [3.6], Event type, includes 4 event types. Selections later determine which pages are displayed. The event type(s) selected also are translated to Section II, Question 8 of the form.

**Comment by freeheeling** [comment]
The AC states that there is conditional routing based on the selections made on page [3.6]. However, clicking 'Continue' should route to page [3.7], Event list, regardless as the event types selected on [3.6] only influence pages displayed later in the online form.

**Comment by freeheeling** [comment]
Wrapping up development, but posed a question [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97067#issuecomment-2549925943) regarding data-storage decisions.

**Comment by freeheeling** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33741) drafted

**Comment by freeheeling** [comment]
PR [merged](https://github.com/department-of-veterans-affairs/vets-website/pull/33741#pullrequestreview-2525810263)

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
