### ISSUE TITLE
Add listing page to CMS

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9708]
**Acceptance Criteria**
- [ ] VA Form listing page is available in CMS

**Implementation**
- [ ]  Final review by CMS team
- [ ] Update content type to remove testing behavior
- [ ]  PR submitted to CMS team

**Comment by stephorkandatx** [comment]
This work was separated from #9562 and moved into its own ticket.

**Comment by stephorkandatx** [comment]
@swirtSJW FYSA this item was originally part of the AC of #9562 . Beth & I spoke and felt it made sense to do as a separate ticket.

**Comment by stephorkandatx** [comment]
This work will be mostly ready once #9562 and #9589 are done. The remaining work will be to write the behat tests

**Comment by MarciMcGuireGCIO** [comment]
@kevwalsh cc @johnhashva Kevin - I'm reviewing some old issues in GitHub and ran across this one.  Do you happen to know if it was completed?  I saw that it was moved from In Progress to Validate on Jun 29, and that was the last entry.  Thank you!

**Comment by swirtSJW** [comment]
Closing this as we have Form listing pages  in the CMS for a few years.
https://prod.cms.va.gov/admin/content/va-forms
![image](https://user-images.githubusercontent.com/5752113/236059784-94adf414-6854-429e-9aa0-5aa8f1adf4c8.png)
