### ISSUE TITLE
Roll out Preferred Name vets-api call, smoke test to 5, 20, 100%

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#97095]
### User story

As a cartographer team member, I want to gradually roll preferred name out on the API side and monitor, so that we can be sure that it's behaving as expected before rolling out the Veteran-facing feature.

### Notes
- `va_profile_includes_preferred_name` (vets-api side) affects preferred name fetching and inclusion in /v0/users

Possible tasks:

## Acceptance criteria

- Notified VA Profile team that we are releasing
- Checked analytics and data dog to see that we're tracking what we want to 
- Enabled feature toggle for 5% of Veterans and monitored health stats
- Enabled toggle for 20% of Veterans and monitored
- Monitored for vets-api errors in Sentry/Datadog
- Fully enabled toggle (100%)

**Comment by wesrowe** [comment]
Since we didn't modify an API call after all this isn't needed. Closing.
