### ISSUE TITLE
[GIBCT] evaluate current progress of GIBCT work

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#97119]
It's been about 6 months since we were working on GIBCT. We need to refamiliarize ourselves with what has been done and the state of various tickets/initiatives. We should create/updates tickets to reflect these findings. Many of these were written before we knew how we'd approach this (standardized CI workflows, dedicated cluster, code organization practices), so they'll likely need a good overhaul. Many don't have too many details to begin with. 

## Tasks
- [ ] Evaluate existing tickets within the [GIBCT epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78105), adding details as necessary

## Acceptance Criteria
- [ ] Relevant engineers (Ryan, Eric, Ben) agree all tickets in the epic properly represent work to be done

**Comment by ryan-mcneil** [comment]
While I was able to investigate work already done, and prepared existing tickets for adding necessary details, there is still lots of info needed from Ben. We're meeting tomorrow, 11/21 to re-evaluate work to be done, so this ticket will carry over to next sprint

**Comment by ericboehs** [comment]
Blocked until we confirm our new approach is viable.
