### ISSUE TITLE
[Frontend] Back button does not product expected results - see attached test case 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9712]
See attached test case [https://app.zenhub.com/files/133843125/d637857a-9565-43fb-b118-99e566c3cdaf/download](https://app.zenhub.com/files/133843125/d637857a-9565-43fb-b118-99e566c3cdaf/download)

**Comment by bradl3yC** [comment]
@tlei123 this should be opening in a new browser tab / window - Back button wont work in this situation - you would just need to close the tab or close the new browser window that opened.

**Comment by bradl3yC** [comment]
@leahkeeler ^^

**Comment by leahkeeler** [comment]
@tzelei Will you rerun the test cases or just manually mark as passed per @bradl3yC commnets above

**Comment by tlei123** [comment]
Bugfix validated; Closing this tic.

See [new QA Test Run Rd.2 links in my QA Test Plan tic \#5952](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5952#issuecomment-639021105).
