### ISSUE TITLE
Update Appts sign-in widget with VADS components, remove Oracle facility functionality (Ph1)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#97177]
### User story

As a Veteran, I want the sign-in widget experience on the unauthenticated Appointments page to offer the latest design-system content, so that i can have a consistent experience across all the unauthed tool pages. 

As a Veteran with at least one Oracle Health facility, I want my OH needs to be addressed at the Appts landing page instead of in the sign-in widget, so that I'm only exposed to the complexity of OH in one place.

### Notes
- Appointments may use a different widget than other MHV apps? Investigate
- Unauthed page: www.va.gov/health-care/schedule-view-va-appointments/
- The needed changes are [documented in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/transition/benefit-hub-page-updates.md)
- VADS/DST will provide the components, which are already [documented in VADS](https://design.va.gov/components/alert/alert-sign-in/) (but not yet implemented as of 11/14)
  - update: Identity team built the special buttons with Id.me/login.gov branding, they are separate from DST "content components" ([slack thread](https://dsva.slack.com/archives/C068QM7CCKG/p1732632501361649?thread_ts=1731017509.219269&cid=C068QM7CCKG))
- See [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97279) for more context

## Acceptance criteria

- [ ] Content of Appts widget updated to VADS standard per UX design
    - [ ] Initial "please sign in" content – use out of the box VADS component without customization
    - [ ] "Verify your identity" content – use out of the box VADS component without customization
      - Test to ensure it works properly for Login.gov and ID.me credentials
    - [ ] "Sign in with a different acct" – use out of the box VADS component without customization
    - [ ] Last screen – All Veterans who are signed in and have LOA3 credentials are given a single CTA link to the Appts tool on VA.gov, even if they have an Oracle facility in their profile. They no longer see an OH/Cerner routing alert on the unauth page. 
- [ ] Informed CAIA to add widgets to Drupal and test in a Drupal Preview environment
- [ ] QA review
- [ ] A11y review

**Comment by wesrowe** [comment]
@sterkenburgsara, I added links to a few things, including the VADS page for these alerts. Please review for whether the work is described well – I feel like it might need some clarification still. (The tickets for the other widgets definitely need clarification, I'll work on those next.)

**Comment by sterkenburgsara** [comment]
Reviewed / made some slight tweaks. Looks good to me unless devs have Q's.

**Comment by dcloud** [comment]
Veteran 0 may have a Oracle-Health/Cerner record. They may see an alert post-login about their VA Medical Center locations.

In reference to:

> Last screen – All Veterans who are signed in and have LOA3 credentials are given a single CTA link to the Appts tool on VA.gov, even if they have an Oracle facility in their profile. They no longer see an OH/Cerner routing alert on the unauth page.

**Comment by dcloud** [comment]
The final screen on the appointments widget is likely outside the shared `cta-widget` shared code

**Comment by wesrowe** [comment]
@nichia, note that the final-screen update for the Appts widget is not covered by the other work in sprint 46.

**Comment by wesrowe** [comment]
Oracle part is covered in another ticket, and no other custom work will be needed for Appts widget. closing.
