### ISSUE TITLE
Update the POA widget to save the user's POA to local storage

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#97176]
I'm creating this ticket quickly to get it on the board.

There are several calls to the POA endpoint in the Appoint Flow if the user is logged in, and there should, ideally, be only one.

We need to create a solution that ensures the saved POA data is not stale.

**Comment by oddball-lindsay** [comment]
Having an extra call isn't "expensive" and cleanup isn't a priority, better to err on the safe side to confirm the POA data remains accurate between the two calls.
