### ISSUE TITLE
[Congressional] V12432641 Due 12/27/24 (Rep. Buchanan)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#97207]
## Issue Description
 Veteran’s issue of having his dependent (his wife) listed on the VA.gov site was changed with a man’s name.

---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
11/19/24:
Request for assistance sent to Jeremy Haas, EVSS team.
The EVSS HD has created ticket ETSHD-2657 for internal recording and tracking of this Congressional inquiry.  There are multiple issues with this veteran’s records to resolve including issues with their CORP record, their BIRLS record, with incorrect date of birth, incorrect SSN, and the dependent being seen as the veteran in VBMS.
We do believe our team can help resolve these issues, and I will provide further updates to this thread as they become available.

**Comment by Kimberley2023-CSM** [comment]
https://dsva.slack.com/archives/C02BS78NYRM/p1731614846541359

**Comment by Kimberley2023-CSM** [comment]
11/19/24:
Request for assistance sent to Jeremy Haas, EVSS team.
The EVSS HD has created ticket ETSHD-2657 for internal recording and tracking of this Congressional inquiry.  There are multiple issues with this veteran’s records to resolve including issues with their CORP record, their BIRLS record, with incorrect date of birth, incorrect SSN, and the dependent being seen as the veteran in VBMS.
We do believe our team can help resolve these issues, and I will provide further updates to this thread as they become available.
:thank_you:
1



Kimberley Monroe-Daniels
  [Nov 22nd at 9:35 AM](https://dsva.slack.com/archives/C02BS78NYRM/p1732286152796739?thread_ts=1731614846.541359&cid=C02BS78NYRM)
11/21 Update:
EVSS has -
3 of 5 technical issues with the veteran's account have been resolved.
Coordinating with VBMS to fix the incorrect dependent classification.
Resolving the final issue related to the veteran's date of birth (DOB) after the dependent classification is corrected.
High likelihood issue will be resolved before due date.
:heart:
1



Vicki Caruso
  [Nov 25th at 2:29 PM](https://dsva.slack.com/archives/C02BS78NYRM/p1732562991387689?thread_ts=1731614846.541359&cid=C02BS78NYRM)
EVSS has received confirmation from the veteran that the technical issues he was dealing with are resolved.


Vicki Caruso
  [Nov 26th at 9:57 AM](https://dsva.slack.com/archives/C02BS78NYRM/p1732633030959079?thread_ts=1731614846.541359&cid=C02BS78NYRM)
Complete: OCTO Response has been submitted.  EVSS has received confirmation from the veteran that the issue has been resolved.
:+1::skin-tone-5:
1
:task_done:
1
