### ISSUE TITLE
AWS access for Stacy Wise

### ISSUE THREAD

**Issue by dysbo** [department-of-veterans-affairs/va.gov-team#97212]
### COR Name

Laurene "Reney" Cook

### Vendor Onboarding Representative Name

Coforma - Jeff Langworthy

### Your Name

Stacy Wise

### Your Email

stacy.wise@coforma.io

### Team, Role, and Company of the target individual

Benefits Management Team II, Tech Lead, Coforma

### Product Manager (PM) name and email

Saliha Ghaffar saliha.ghaffar@coforma.io

### Product Owner (PO) name and email

Amy Lai amy.lai2@va.gov

### Desired AWS Access

I am not 100% sure on this as I am pretty new to the org and not super well versed with AWS and its lingo - I need to be able to set up a client ID and an RSA key for use with the benefits-claims Lighthouse API that will be used with the review instances deployed as part of the PR process for vets-api and vets-website.

A lot of the other parameters I'm seeing in the [settings file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/review-instance-configure/vars/settings.local.yml) point to `/dsva-vagov/vets-api/staging` for their values so that may be what I am looking for.

### Access Expiration

1/1/2025

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/d9a4ced2-b276-4eb5-a75a-868f5308659e)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by dysbo** [comment]
@Efe-Oddball I do still need access!  And I see that a change was made in https://github.com/department-of-veterans-affairs/devops/pull/14893 so possibly this was taken care of in this update?

**Comment by Efe-Oddball** [comment]
@dysbo Yes I am working on granting you, Jane and Trevor your AWS access

**Comment by Efe-Oddball** [comment]
Access granted and temporary credentials have been passed to the user via keybase

**Comment by dysbo** [comment]
> Access granted and temporary credentials have been passed to the user via keybase

Thank you!  Can I ask what keybase account you sent to?  I'm not sure I'm in the right space to have received it 😅

**Comment by dysbo** [comment]
Sorry @Efe-Oddball meant to tag you in that ^ new comment since I'm not sure edits will produce notifications
