### ISSUE TITLE
CT-EYB: Add paging to VETTEC approved programs table.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9722]
As a user of the comparison tool, I need the vet tec programs table to support paging so that I do not have to scroll an excessive amount to get to the next section of the page.

## Assumptions:
1. This work is completed behind the feature flag in #7780.

## Acceptance Criteria
1. If 10 programs or less:
    a. Display all of the programs with no paging controls. 
    a. Display “Showing N of N programs” indicator. 
2. If over 10 row items available:
    a. Display 5 programs by default.
    b. Display paging controls (SA#2).
3. When all programs are displayed:
    a. A “…View less” paging control (SA#3) is displayed.
    b. Clicking the view less control collapses the table to the first 5 items displayed
    c. Clicking the view less control puts the focus on the top of the section accordion. 
 4. The programs are displayed alphabetically by program name.

## Supporting Artifacts:
1. [Sketch](https://www.sketch.com/s/55de1c5f-2bd4-4941-a57e-3d1fdeb512fa/p/eyb-vet-tec-desktop-v03-post-ut)
2. ![Paging Controls](https://user-images.githubusercontent.com/48260534/83645058-036b9300-a580-11ea-909f-219ac5a7ca8b.png)
3. ![View Less Paging Controls](https://user-images.githubusercontent.com/48260534/83645083-0a92a100-a580-11ea-8f4d-bc6601660943.png)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12946

**Comment by JenLJ** [comment]
@delli-gatti-michael UX has reviewed and this story is good to go :)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/463&group_by=cases:section_id&group_order=asc
passes. Closing out story.
