### ISSUE TITLE
QA Standards - CMS Team - Next Build and Next Build's Events and Event Listing Templates

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#97239]
#### VFS team name
CMS Team
#### VFS product name
Next Build and Next Build's Events and Event Listing Templates
#### VFS feature name
Events and Event Listing Templates

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Results of executing the Regression Test Plan not included
#### Test Plan
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Results of executing the Test Plan not included
#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 87.77

- Functions %: 84.73

- Statements %: 88.17

- Branches %: 80.07

- [x] Standard has been met
- [ ] Standard has not been met
#### Endpoint Monitoring (Completed Playbook)
- [x] Standard has been met
- [ ] Standard has not been met
#### Logging Silent Failures
- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [x] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by EWashb** [comment]
I approve the regression and test plan.
