### ISSUE TITLE
Improve PDF stamping resiliency 

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#97231]
<img width="1667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNDQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e282e1662e622d04c2c07deaf8c8e4e9370ea09a/Screenshot%202024-11-15%20at%209.35.27%E2%80%AFAM.png" alt="Screenshot 2024-11-15 at 9.35.27 AM.png" />

Problem:  We had a 500 non-ZSF error in 10-7959-F-1. This was caused by pdf stamping process. It looks like a kubernetes pod terminated before the stamping process finished.

Solution and AC: If the tmp stamp file is missing, retry another attempt.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/19662

**Comment by cloudmagic80** [comment]
2nd PR. This is Part 2. 
https://github.com/department-of-veterans-affairs/vets-api/pull/19706

**Comment by baltes** [comment]
@cloudmagic80 Can you comment with info on what I'm reviewing? The last PR is closed but there are no reviews on it so I'm not sure how that happened. I need some help understanding what was done and whether its complete.

**Comment by cloudmagic80** [comment]
@baltes  I can demo to you tomorrow. So this PR fixes the 500 errors from the 7959F1 and 1010D forms. It will be hard to review alone. I can set up a time with you on Monday.
