### ISSUE TITLE
Design: 10-10d Update CHAMPVA mailing address throughout

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97268]
The CHAMPVA mailing address should be changed throughout form 10-10d to match the following:

VHA Office of Integrated Veteran Care
CHAMPVA Eligibility
PO Box 137
Spring City, PA 19475

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92c4e92142e6bf965b1c520557ddc8a3078cd2ea/image.png" alt="image.png" />

Acceptance criteria
Updates designs for 10-10d so that mailing address is current

**Comment by jamiefiore** [comment]
@baltes this is updated on the main [figma file](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=3610-23369&node-type=frame&t=8lBxzP43zBZ2XLRs-0) and all of the other work in progress 1010d iteration files as well. 
[Required Email Field (95333) 10/23/24](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=3731-107518&node-type=canvas&t=8lBxzP43zBZ2XLRs-0)
[Post Staging Review 10-01-24> Make updates from Staging Review tickets here 2](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=3929-29215&node-type=frame&t=8lBxzP43zBZ2XLRs-0)
