### ISSUE TITLE
AWS access for Nathan Wright

### ISSUE THREAD

**Issue by nathanbwright** [department-of-veterans-affairs/va.gov-team#97263]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Nathan Wright

### Your Email

nathan.wright@oddball.io

### Team, Role, and Company of the target individual

VANotify Experience team, Tech lead, Oddball

### Product Manager (PM) name and email

Samantha Jennings samantha.jennings@oddball.io

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Desired AWS Access

`dsva-vfs-developers` policy

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/226496c5-8ac6-4dfa-ac4c-f44054740f21)

### Additional Notes

COR - Rodriguez, Mary - Mary.Rodriguez@va.gov

I need to be able to set/update params listed under `/dsva-vagov/vets-api/*` for the work that my team does in vets-api to support notifications.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
Permission Granted! Resolving ticket
