### ISSUE TITLE
AC-api: Implement MHV Landing Page for 4 "user-action" errors

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#97281]
### User story

As a Veteran for whom the MHV Acct Creation API returned an error requiring MHV Help Desk intervention, I want to be informed on the MHV Landing Page of the issue, which tools are affected, what number to call, and what error code to tell them, so that I can get it resolved efficiently.

### Notes
- design completed in #91876 for error codes that require user action to resolve (i.e., call MHV help desk)
- [Mural area](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?wid=0-1730315018323) breaking these out
- [Figma link](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=229-3&node-type=canvas&t=ve4WQC82goHMCLh9-0)
- [Identity team docs on MHV Account Creation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/MHV%20account%20creation%20API)
  - [Draft docs for `/v0/user/mhv_user_account`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/MHV%20account%20creation%20API/vets-api%20Documentation/mhv_user_account_api.md)

<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/c0961478-0c78-43e3-a098-c082a4a6fe9c)

</details>

Possible tasks:
- CONFIRMED: we have to make an API call to get it
- Add new alert for user-facing errors returned from the Account Creation API 
- This alert will conditionally reveal the specific error codes that require the user to take an action (call the My HealtheVet helpdesk) to resolve the problem. 

## Acceptance criteria

- Loading indicator displays while awaiting API response
- Red alert displays if any of the 4 error codes are returned (below) & conditionally reveals the error code # in the alert heading & body content:
  - [ ] 801
  - [ ] 805
  - [ ] 806
  - [ ] 807
- [ ] Gray boxes for SM, Meds and Records display error instead of links (and icons in headings change to reflect the "error" icon)
- [ ] Alert records event to GA4 with heading metadata (similar to e.g. "Register" alert)
- [ ] Remove the current 'Register wtih My HealtheVet" alert for users who see these 4 alerts. 
- [x] QA review
- [ ] A11y review

**Comment by dcloud** [comment]
@kjsuarez We do need to make an API call to get the errors, per [this MHV User Account API doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/MHV%20account%20creation%20API/vets-api%20Documentation/mhv_user_account_api.md).

We also need to add a [Loading Indicator](https://design.va.gov/components/loading-indicator) given this API could take many seconds in worst case, and we want to indicate to the user that we are checking for MHV account

**Comment by kjsuarez** [comment]
[Branch](https://github.com/department-of-veterans-affairs/vets-website/tree/97281-implement-MHV-account-api-request)
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33236)

**Comment by wesrowe** [comment]
I just added an AC to make sure a GA4 event is triggered when the alert renders, similar to other alerts on the page.

**Comment by kjsuarez** [comment]
[vets-api feature flipper PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19875)

**Comment by kjsuarez** [comment]
### For QA testing on local machine

- Mock feature flipper
  - `src/applications/mhv-landing-page/mocks/api/feature-toggles/index.js:7`
- Mock mhvAccountState data
  - `src/applications/mhv-landing-page/mocks/api/user/index.js:67`
- Mock API response
  - `src/applications/mhv-landing-page/mocks/api/index.js:20`

**Comment by wesrowe** [comment]
@kjsuarez, I thought at one point you considered implementing both ACapi alerts in one PR – the original one in this ticket PLUS the "technical" error one in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98360?

I just want to get a handle on where we are. I looked at the PR linked higher up here, only saw one alert screenshot. And the second story is sitting in Next Sprint.

**Comment by kjsuarez** [comment]
I had considered handling both kinds of errors as a single PR, but considering the size of the PR as it stands I think it would be a good idea to keep these as separate tickets.

**Comment by mcarterA6** [comment]
Moving this ticket to Sprint 47.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that error codes, 801, 805, 806, 807, generates a specific error code alert on the MHV landing page. 

Regression testing was also done to ensure that nothing broke:
1. Verified that the error code didn't shown for a newly created account
2. Verified that existing test users was able to login as expected and didn't run into any issues

<img width="1229" alt="Image" src="https://github.com/user-attachments/assets/1ff93ebc-7b73-4db3-9680-b375b61e1d55" />

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that these alerts appear in GA4

![Image](https://github.com/user-attachments/assets/8a7cef46-1d7e-4045-9bae-17c0760734e2)
