### ISSUE TITLE
FE | Direct Deposit | Montgomery GI Bill Direct Deposit Updates

### ISSUE THREAD

**Issue by asiisii** [department-of-veterans-affairs/va.gov-team#97335]
### Acceptance Criteria: As a Veteran, I will understand how to update my information for the Montgomery GI Bill from the Profile Direct Deposit Page so that I can continue to receive benefit payments. 

Screenshots from the VYE Team (CAIA Approved): 

![Image](https://github.com/user-attachments/assets/2095d2e7-8138-4616-b027-ef4ae3c16884)

### Task: add an additional info component as I'm seeing on some of the other profile screens, so the text will unfurl when the user clicks the label
![Image](https://github.com/user-attachments/assets/bac4b87a-e44e-4588-8b9b-b9912bfa15b8)
[Here is the text to be used](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82157#issuecomment-2445789914): If you’re getting benefits through the Montgomery GI Bill Active Duty (MGIB-AD) or Montgomery GI Bill Selected Reserve (MGIB-SR), you’ll need to update your direct deposit information using our enrollment verification tool.
[Update direct deposit information for MGIB benefits](https://www.va.gov/education/verify-school-enrollment#for-montgomery-gi-bill-benefit)
Link to VYE CAIA Ticket for refernce: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82157

**Comment by ACParker89** [comment]
@asiisii do you need myself or @a6marinos to help with review?

**Comment by asiisii** [comment]
> [@asiisii](https://github.com/asiisii) do you need myself or [@a6marinos](https://github.com/a6marinos) to help with review?

@ACParker89 no one has reviewed my PR yet. Once it’s reviewed and merged, I’d appreciate it if someone could validate it.

**Comment by DanielMiller-agile6** [comment]
verified changes on staging using +12 test user 👍 

![Image](https://github.com/user-attachments/assets/cdf4d697-8610-4e0c-9b00-888f5f6ed792)
