### ISSUE TITLE
[FE] Update Terms and Conditions content (account security)

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9734]
##Background

An updated design mock is needed to reflect the "terms and conditions not accepted" state

[Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8824)
Epic: #2086

##Design and content

![image](https://user-images.githubusercontent.com/58752772/83568549-ae704400-a4cf-11ea-8e3a-782f2c427fda.png)
![image](https://user-images.githubusercontent.com/58752772/83568564-b4febb80-a4cf-11ea-9fcb-aa0b8bfa86e3.png)

Before using our health tools, you’ll need to read and agree to the terms and conditions for medical information. This will give us permission to share your VA medical information with you. Once you do this, you can use the tools to refill your VA prescriptions or download your VA health records.

[Go to the terms and conditions for medical information](link to terms and condition page)

Please update accepted message to:
You've accepted the terms and conditions for using VA.gov health tools

##Tasks
- [ ] Update content for terms and conditions

##Acceptance criteria
- [ ] Section is validated by Tressa/Matt

**Comment by erikphansen** [comment]
@tressaellen @mshea0606 this can be validated in staging.

**Comment by mshea0606** [comment]
@erikphansen  what staging user do we use for this?

**Comment by erikphansen** [comment]
@mshea0606 I think any user will show the "accepted" state, but we weren't able to find a user who still needed to accept the terms and conditions https://dsva.slack.com/archives/C909ZG2BB/p1588780904074300

**Comment by mshea0606** [comment]
@erikphansen Ok thanks!
