### ISSUE TITLE
Cannot access "Replace rep" screen

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#97356]
## Expected vs. Actual
**Expected**: If I'm logged in with a user that has existing representation, I should see the "Replace rep" screen after the "Contact the Rep" screen.

**Actual**: When I'm logged in with a user that has existing representation, I'm moved from "Contact the Rep" to the text input screens to enter my information. I'm not seeing the "Replace rep" screen.

## Steps to Reproduce
I can reproduce with [test user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv) vets.gov.user+232@gmail.com which has existing representation with Disabled American Veterans.

1. Login to VA.gov
2. Head to our landing page https://staging.va.gov/get-help-from-accredited-representative -- use the Rep Status Widget to confirm there is an existing representative 
3. Head into the Appoint experience https://staging.va.gov/get-help-from-accredited-representative/appoint-rep
4. Select "Yes I'm the Veteran"
5. Select a rep (I chose Bobbie Jones), you're taken to the "Contact the Rep" screen
6. Click "Continue" on the "Contact the Rep" screen, the "Replace rep" screen should come next but it jumps right to entering in your information 

Based on when I caught this (after QA, but before we did any work to update the user flow), my guess is that this bug is related to this update https://github.com/department-of-veterans-affairs/va.gov-team/issues/97172.

**Comment by oddball-lindsay** [comment]
Confirming I can access the screen again, thanks @holdenhinkle!

**Comment by holdenhinkle** [comment]
Fixed. Tested with user `vets.gov.user+232@gmail.com`

### https://staging.va.gov/get-help-from-accredited-representative/appoint-rep/representative-replace
![Image](https://github.com/user-attachments/assets/54856fd5-2e01-44d0-a002-5b5011aee3da)
