### ISSUE TITLE
Contact Center Review for [MHV Medical Records Phase 1 Launch (Download All, Radiology Images, Settings)]

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#97364]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

We have previously gone through a contact center review with our product (MHV Medical Records) prior to Phase 0 Launch.  This previous review was capture under the original Phase 0 collab cycle ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53454.  The original collab cycle contact center review ticket is: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63915

We are now returning to Contact Center review with this ticket as we are approaching a release to Phase 1 (all users can try Medical Records on VA.gov).  The final three collab cycle tickets to support this are listed below.  We are seeking your review once for all three of these tickets:
Download Records: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92340
View Radiology Images: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95081
Settings: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95082

As part of this ticket we are providing and updated Contact Center Product Guide.  Note - we are not planning on updating the video at this time unless required.  The link to the guide is below in that section.

### Launch Date
*Please provide the launch or rollout date and details.*

Our intention currently is to complete development prior to December 10th, and roll the feature out before the code freeze (prior to the end of 2024).

### Version Number
*Please provide the version number of the guide and/or video.*
11152024

### Product Guide
*Please provide product guide link*
[MR on VA.gov_Product Guide_update_11152024 .docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/product/MR%20on%20VA.gov_Product%20Guide_update_11152024%20.docx)

### Product Video
*Please provide product video link*
We are not intending to update the product video at this time as these are just additional features that do not fundamentally change the navigation for users.

### Product Video Transcript
*Please provide product video transcript link*
See above - not intending to update the video at this time.

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by bryan-riley-va** [comment]
@starlow00 the guide is added - please let me know of any questions.

**Comment by starlow00** [comment]
The draft looks good. It will go to VEO today for their review.

**Comment by starlow00** [comment]
No changes from VEO. The working copy is attached for future revisions. Thank you!
[Digital Health Modernization_Medical Records on VA.gov_Product Guide_v6_SRT_11192024 .docx](https://github.com/user-attachments/files/17852063/Digital.Health.Modernization_Medical.Records.on.VA.gov_Product.Guide_v6_SRT_11192024.docx)
