### ISSUE TITLE
Accessibility Feedback, Services Operating Statuses, Design Intent Collab

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9737]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** Jennifer (VSA) & Trevor (VSP)

cc @1Copenut — feedback is ready for your review. I created a Codepen sample, tested in JAWS+IE, NVDA+Firefox, VoiceOver+Safari, and the link is enclosed with the potential code here.

### Must

- Test the `button[aria-expanded]` behaviors inside table cells, whatever that HTML structure looks like. We had to do some creative inventing on the VAOS calendar, but I feel we have a good solution.

- Use the semantic structure of a list, per discussion between Jennifer and Ryan.

### Consider

- Async data fetch for the individual `AdditionalInfo` components. Instead of one big data object, only fetch the fragment of data needed to populate the current open element. This should help keep the payload smaller and the UI more responsive. Be sure to test the async data fetch on slow 3G connection.

- Consider content "templates" or guides that could be written to help folks know good ways to write AM/PM, etc. Content team might already be working on these.

## Potential semantic structure

[Codepen sample of code](https://codepen.io/jenstrickland/pen/eYJmdaX)

```html
<h2>Services and operating status</h2>
<p>Current as of <strong>May 21, 2020</strong></p>
<p>Here is a list of the services offered at this facility and their operating statuses.</p>

<ol role="list"><!-- re-adding the list semantics that CSS list-style:none will remove -->
  <li role="listitem">
    <dfn>Emergency care</dfn>
    <button>
      Limited hours of operation
      <span class="sr-only">for emergency care, more details</span>
    </button>
  </li>
  <li role="listitem">
    <dfn>Urgent care</dfn>
    <button>
      Closed
      <span class="sr-only">for urgent care, more details</span>
    </button>
  </li>
  <li role="listitem">
    <dfn>Mental health care</dfn>
      Normal operating status
  </li>
<!-- etcetera -->
```

### Guidance

* ["Fixing" Lists
](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html)
* [W3C WCAG Understanding SC 2.4.9, Link Purpose (link only)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-link.html) - A mechanism is available to allow the purpose of each link to be identified from link text alone, except where the purpose of the link would be ambiguous to users in general. (Level AAA)

## Definition of done

1. Review and acknowledge feedback.
1. Document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions.

**Comment by 1Copenut** [comment]
@jenstrickland This is 💯 I really appreciate the way you structured the SR-only text in the button. I can hear that read back with a clear call to action. No additional comment or items from VSP.

**Comment by jenstrickland** [comment]
@mmiddaugh This accessibility feedback is ready for you.

**Comment by mmiddaugh** [comment]
This feature was deprioritized
