### ISSUE TITLE
Address PgQuery Duration spikes [Part 1]

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#97380]
## User Story
As the owners of the RDS, Postgres DB,
we need to ensure the Postgres Query average remains below the defined threshold (0.09),
so that the database can perform efficiently, and avoid performance degradation for Veterans.

## Issue Description

In [follow-up to this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96409), we are still seeing spikes in the PgQuery duration overnight. The logs show that there are PgQuery timeouts. 

Additionally, there is still a PG Query duraton spike during the 3-5am window.  It may be related to the Vye::MidnightRun::IngressTimsChunk job [where you can see the errors here](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20status%3A%28error%20OR%20critical%29%20host%3Avets-api-sidekiq%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZMA_looXaVHgwAAAAAAAAAYAAAAAEFaTUFfbkE1QUFEVjcyMXM3Y3R6QWdBQQAAACQAAAAAMDE5MzAxMDYtMjQzMy00ZTY1LWExM2ItZWZjZjY4Y2Q0OGMy&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1730887800000&to_ts=1730890020000&live=false)

A few teams have been notified about making improvements to their jobs:
1. `Vye::MidnightRun::IngressTimsChunk`
2. `BGS::SubmitForm686cJob` - There's a [large number of them over the past day](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20status%3A%28error%20OR%20critical%29%20host%3Avets-api-sidekiq%2A%20%22value%20too%20large%20for%20column%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1731852902872&to_ts=1731939302872&live=true). Matthew Knight and team has been alerted and https://github.com/department-of-veterans-affairs/va.gov-team/issues/97301
3. `VBADocuments::UploadScanner ` - Drew Fisher and Michel McDonald + Team [have been alerted here](https://dsva.slack.com/archives/CKUCFQAHJ/p1729171745329239)

## Acceptance Criteria
- [ ] Investigate PG Query spike for [the spike overnight](https://vagov.ddog-gov.com/monitors/199084?eval_ts=1732021756314&from_ts=1731938679391&to_ts=1732021756314)
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
Dependent Experience team [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97301).

**Comment by LindseySaari** [comment]
[PR has been created ](https://github.com/department-of-veterans-affairs/devops/pull/14869)to eliminate alerting that is causing noise and distractions for warning thresholds.

Additional discussion around the VBA job was [discussed here](https://dsva.slack.com/archives/CKUCFQAHJ/p1729171745329239)

**Comment by LindseySaari** [comment]
Closing in favor of: https://github.com/department-of-veterans-affairs/devops/pull/14782

**Comment by AshleyGuerrant** [comment]
Closing out, tracking in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98334) in the upcoming sprint.
