### ISSUE TITLE
Midpoint Review - Design Feedback - Debt Resolution - Digital Debt Dispute

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#97398]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- We have a new experience standard around notifications. Be sure to think about how the users gets notified when the status of this form changes. Are there other notifications you need to think about? Emails, phone calls, texts, etc.
- Matt Dingee: Referring to the minimal header and back link vs button, once you are in the flow using a "back" link is fine because you want to keep them in the flow. They were meant o go hand in hand but you don't have to if you want to go slowly. [Minimal header mock form](https://staging.va.gov/mock-form-minimal-header/introduction).

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: We have a new pattern for [prefilled information](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled). Review the new pattern and align your UI with the new UI. Be sure to include the [prefill note also](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled#signed-in-prefill-alert).
- [x] Should: We have a [check box button tile option](https://design.va.gov/components/form/checkbox#tile) that can help group content inside check boxes. This may be helpful when selecting a specific debt that has more content.

## Governance team actions
- [ ] Format feedback as individual tasks (check boxes)
- [ ] Assign this ticket to the VFS team member that opened the Slack request
- [ ] Add the VFS team product label
- [ ] Add the VFS team the feature label (if applicable)
- [ ] Add the touchpoint labels
- [ ] Add the practice area labels
- [ ] Add the Collaboration Cycle initiative milestone

**Comment by mgleo** [comment]
Hi @allison0034, I had some follow up questions regarding 

> Must: We have a new pattern for prefilled information. Review the new pattern and align your UI with the new UI. Be sure to include the prefill note also.

- I saw that the new [Prefill pattern](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled) is marked as "Use with caution: Candidate". I couldn't find a component for it on Figma. Should I recreate it on Figma or am I missing the component in the Component Library?
- Engineers on our team [received feedback](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/95575#issuecomment-2484228035) that SSN and File Number should not be shown during Architecture Intent. Both the [Know when their information is prefilled](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled) and [Know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated) pattern show SSN and File number. Thoughts on this? Have there been discussion about updating these components?

**Comment by allison0034** [comment]
Hi @mgleo 

- If you are going to do testing then yes, that would be best. Otherwise, you could potentially note it and then when you go to staging just make sure you use any components (eg cards) we have.
- You do not need to show SSN and File Number if your product does not need it. There are 2 examples on the [Know when their information is prefilled](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled) page:
  - Uneditable prefilled information on the personal information page (the SSN example you are referring to). It is not limited to just SSN.
  - Editable prefilled information displayed on the Prefill check page. Things like phone and address.


Does that help?

**Comment by mgleo** [comment]
Hi @allison0034 Thank you! This is helpful, we'll confirm whether File # and SSN is required for this form.

**Comment by josephrlee** [comment]
Marking this as closed as all the feedback has been addressed in the prototypes and mockups through #[97425](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97425)
