### ISSUE TITLE
adjust common settings in vets-api to utilize to "common" folder location from SSM

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#97396]
All common settings in vets-api should be adjusted to start with "common"

## Tasks
- [ ] Add "common" to all settings in common folder of SSM

## Acceptance Criteria
- [ ] Common settings are getting the values from the "common" folder

**Comment by ericboehs** [comment]
Broken up here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/97716

**Comment by JoeTice** [comment]
Ticket has been broken into smaller pieces
