### ISSUE TITLE
[Research] 10-10EZ - Reg Only: Mid-experiment research planning discussions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#97406]
## Benefit to the Veteran
As a Veteran, I want to know what I am signing up for and the benefits I will get, so that I can make an informed decision for my health.

## Background
- The Registration Only experiment has been in place since the beginning of October, and we are seeing an upward trend of people who select to Register, then subsequently leave the form.  The activity shows that these people are looking for facilities, forms (presumable a registration form) and more information on other health related pages.
- As part of the experiment, we outlined action items to conduct a small research session if we saw an upward trend in registration selections.

## Scope
- This ticket is to discuss research options, goals and potential outcomes based on results.

## Resources
- [Experiment outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Reg%20Only%20experiment%20proposal.md)
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/readme.md)
---
## Acceptance Criteria/Definition of Done
-  The team will have a plan to move forward on the Registration Only data.

**Comment by jessicastump** [comment]
[Mural board setup](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731600312853/b3f7b42171fc661e8c0fbb2eabb4329bd5c21e12) to use for notes and discussions around recommendations and next steps

**Comment by jessicastump** [comment]
@aagosto90 and @hdjustice - should we close this ticket since this pre-planning is basically done and maybe open a new ticket to conduct and keep notes for the content working sessions?

**Comment by hdjustice** [comment]
sounds fine to me
