### ISSUE TITLE
PrefName: Display prefName in auth menu when available

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#97411]
### User story

As an authenticated user, I want the authenticated menu (header) to display my preferred name if I have entered one, so that I feel that the VA knows who I am.

### Notes

Possible tasks:
- Check in with public websites and the documentation for making changes to sitewide header

## Acceptance criteria

- **Behind a feature flag,** the auth menu looks for `preferredName` on the User object before falling back to first name, then email address
- QA review

**Comment by dcloud** [comment]
Draft PR started with initial unit test.

**Comment by dcloud** [comment]
Failing e2e tests don't have anything to do with the sitewide header (seeing mhv-medications errors about prescription refills)… but the PR is platform/sitewide, so all tests get run.

Also, messaged public websites team about testing, ahead of putting any feature flag in place.

**Comment by dcloud** [comment]
Moving this into _blocked_ while engineers pivot to department-of-veterans-affairs/va.gov-team/issues/97279

**Comment by dcloud** [comment]
Will merge the PR on Monday 16 Dec, before noon in order to [deploy on Monday](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments)

**Comment by dcloud** [comment]
Just merged

**Comment by mcarterA6** [comment]
@allanto-ah were you able to complete your review? If so, can this ticket be marked as done?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the preferred name is displayed in the auth menu when it is available. If not, the first name of the user is displayed. 

Filed an issue that the first name of the user is displayed briefly before the preferred name is shown: [99422](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99422)
