### ISSUE TITLE
[Bug] 10-10CG MVP - Copy mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9742]
## What happened?
On Staging **Apply for the Program of Comprehensive Assistance for Family Caregivers** form, some copy/layout items appeared erroneous, or did not match corresponding design prototypes.

## Specs:
- Browser-/device-agnostic
- Unauthenticated experience

## Steps to Reproduce
1. Go to https://staging.va.gov/caregivers/introduction
1. Observe copy mismatch \[see screenshot below].
1. Click **Start...** button.
1. Keep inputting dummy-info into required fields and clicking **Continue** button until you reach **Primary Family Caregiver information** (Ch2p1) form-page.
1. Observe apparent error [plural form] \[see screenshot below].
1. Keep inputting dummy-info into required fields and clicking **Continue** button until you reach **Primary Family Caregiver information, Health care coverage** (Ch2p3) form-page.
1. Click **Yes/No** radio buttons for first 4 questions, click **Learn more about Medicare** toggle-link to expand detail-content, then click **Yes** for **...other health care insurance?** question.
1. Observe apparent error & copy mismatch \[see screenshots below].
1. Click **Continue** button to advance to next form-page.
1. Observe chapter/title copy mismatch \[see screenshot below].
1. Keep inputting dummy-info into required fields and clicking **Continue** button until you reach **Secondary Family Caregiver (2) information [Contact info]** (Ch4p2) form-page.
1. Observe missing subtitle \[see screenshot below].

**Intro**
![1010cg-bug-intro](https://user-images.githubusercontent.com/587583/83587524-29535200-a504-11ea-9589-4e909ec76396.png)

**Ch2p1** \[not mismatch; design prototype also shows plural form]
![1010cg-bug-ch2p1](https://user-images.githubusercontent.com/587583/83587744-a5e63080-a504-11ea-9cf3-b74720e6a17e.png)

**Ch2p3**
![1010cg-bug-ch2p3](https://user-images.githubusercontent.com/587583/83588148-987d7600-a505-11ea-936a-0a0d4717449d.png)
![1010cg-bug2-ch2p3](https://user-images.githubusercontent.com/587583/83587803-c57d5900-a504-11ea-915d-0b2057c7c40c.png)

**Ch2p4/Ch3p1** \[Chapter/title mismatch]
![1010cg-bug-ch3p1](https://user-images.githubusercontent.com/587583/83588348-0a55bf80-a506-11ea-9d21-089dbe492630.png)

**Ch4p2**
![1010cg-bug-ch4p2](https://user-images.githubusercontent.com/587583/83588949-5ce3ab80-a507-11ea-927e-c58b8c655d1a.png)

## Desired copy
**[Intro](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/412943887)**
![1010cg-into](https://user-images.githubusercontent.com/587583/83589412-82bd8000-a508-11ea-8a12-e960db43a948.png)

**[Ch2p3](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/417174664)**
["who meet who meet" not a mismatch; design prototype also has this repeat]

![1010cg-ch2p3](https://user-images.githubusercontent.com/587583/83589594-f19ad900-a508-11ea-9820-52e851a52c61.png)

**[Ch3p1](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/412943901)**
![1010cg-ch3p1](https://user-images.githubusercontent.com/587583/83594819-0da47780-a515-11ea-9c37-632ff0389af9.png)

**[Ch4p2](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/412943901)**
![1010cg-ch4p2](https://user-images.githubusercontent.com/587583/83595226-38430000-a516-11ea-8d9c-9b78d13d9cbf.png)

## Acceptance Criteria
- [x] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
@tlei123  - Feedback has been addressed. Please validate and close the ticket when you get a chance. Thanks!

**Comment by tlei123** [comment]
Validated. Closing ticket.
