### ISSUE TITLE
Request Contact Center Review for Dependency Claims (21-686c)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9744]
## Context
Feature moving over from eBenefits to VA.gov that allows Veterans to view, add or remove dependents to their awards.

## Launch Date and Details
Hoping to launch this in [September 2020](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/release-plan.md)

## URL
- staging.VA.gov/view-change-dependents/ [in draft with Public Websites until launch]
- staging.VA.gov/view-change-dependents/view/
- staging.VA.gov va.gov/view-change-dependents/add-remove-form-686c/

## Product Guide
[Link to the latest Product Guide on Github LFS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/view-and-update-dependents/contact-center/Contact-Center-Product-Guide-686_v09032020.pdf)

## Product Video
[Link to the demo video on Github LFS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/view-and-update-dependents/contact-center/686%20Walkthrough%20Video%20Contact%20Center.mp4)

## Product Video Transcript
[Link to the Product Video Transcript on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/view-and-update-dependents/contact-center/21-686c-contact-center-walkthrough-video-transcript.md)

**Comment by Kimberley2019** [comment]
@jason-gcio I will review today and provide any feedback.

**Comment by Kimberley2019** [comment]
@jason-gcio after review it appears to have all the required information.  As long as there have been not edits to the content that has been provided, I will pass along to the contact center to ensure that they do not have any feedback.
Can you advise that no additional content has been added or updated?

**Comment by jason-gcio** [comment]
Actually we do have a couple, last minute, small content changes going in this sprint:

- In add-spouse flow, change Type of marriage radio button label from “Ceremony” to “**Religious or civil ceremony (minister, justice of the peace, etc.)**”
- Add “**Note: This should be where the student is living while attending school.**“ below student address in the 674 flow

The first is a label change that expands on the original for clarity, and the second is an additional note ahead of an address section.

**Comment by Kimberley2019** [comment]
@jason-gcio Have those changes been incorporated into the product guide?  If not, can/will it be done so that I can send over to the contact center for their review?

**Comment by jason-gcio** [comment]
No, not yet. I plan on doing this soon though.

**Comment by Kimberley2019** [comment]
Thank you Jason.  Once that is updated, please advise so that we can send to the call center for their review and any feedback or questions they may have.

**Comment by Kimberley2019** [comment]
Slacked @jason-gcio to inquire on status of product guide.
The information needs to be updated before sending out to contact centers for their feedback.

**Comment by jason-gcio** [comment]
I am confirming those text changes have been merged and will be updating the powerpoint...hope to have it back to you before Wednesday

**Comment by jason-gcio** [comment]
@Kimberley2019 - just a heads up, still working on this

**Comment by Kimberley2019** [comment]
@jason-gcio Thank you for the update.

**Comment by Kimberley2019** [comment]
@jason-gcio Any updates?

**Comment by jason-gcio** [comment]
@Kimberley2019 - We have found a few other very minor text changes, once those are merged I can share the final draft of the doc

**Comment by Kimberley2019** [comment]
@jason-gcio Thank you for the update.

**Comment by Kimberley2019** [comment]
@jason-gcio Checking in to see if the modifications have been made.

**Comment by jason-gcio** [comment]
@Kimberley2019 - thanks for checking, I hope to have this wrapped up soon.

**Comment by Kimberley2019** [comment]
@jason-gcio Thank you for the update.  Please keep me posted.

**Comment by Kimberley2019** [comment]
@jason-gcio Any updates?

**Comment by jason-gcio** [comment]
@Kimberley2019 - apologies for the delay, we still have 2 more text changes that popped up.  Again, they are not very material to functionality but I want to make sure you have the latest and greatest

**Comment by Kimberley2019** [comment]
Thank you for the update @jason-gcio .  I will await further updates from you on this.

**Comment by Kimberley2019** [comment]
Hey @jason-gcio any movement on this as of yet?

**Comment by jason-gcio** [comment]
Another minor edit - looking to see what its impact on the latest documentation might be.  We are close though.

**Comment by Kimberley2019** [comment]
@jason-gcio Any updates as of yet?

**Comment by jason-gcio** [comment]
Yes! 🎉
We are done with all minor copy edits and I made sure they were all reflected in the product guide.
Getting into LFS and will update the link above in the ticket and ping you when uploaded.

**Comment by Kimberley2019** [comment]
Awesome news @jason-gcio.  I may be OOO (9/7/2020 - 9/21/2020) when this is updated and ready for review.  If so, please ping @clantosswett so that my absence does not cause a bottleneck.

**Comment by jason-gcio** [comment]
Here is the latest and greatest!
Transcript, video, and latest guide are all here: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/view-and-update-dependents/contact-center

**Comment by Kimberley2019** [comment]
Thanks Jason.  I will review and pass along to the Contact Center.

**Comment by Kimberley2019** [comment]
@jason-gcio No feedback has been provided by the Contact Center.  With that being said, this ticket can now be closed.
