### ISSUE TITLE
[Bug] 10-10CG MVP - Ch2p3 - Other health insurance name not required despite Yes selection

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#9745]
## What happened?
On Staging **Apply for the Program of Comprehensive Assistance for Family Caregivers** form, **Primary Family Caregiver, Health care coverage** (Ch2p3) form-page, under **...other health care insurance?** question, after clicking **Yes**, **Name of health insurance...** textbox was not required, and clicking **Continue** button advanced to next form-page.

## Specs:
- Browser-/device-agnostice
- Unauthenticated experience

## Steps to Reproduce
1. Go to https://staging.va.gov/caregivers/introduction
1. Click **Start...** button.
1. Keep inputting dummy-info for all required fields and clicking **Continue** button until you reach **Primary Family Caregiver, Health care information** (Ch2p3) form-page.
1. Click **Yes** for all questions.
1. Under **...other health care insurance?** question, observe that **Name of health insurance...** textbox label does not show "(*Required)".
1. Leave textbox blank, and click **Continue** button.
1. Observe that form-page does not display error-message for textbox, and allows advance to next form-page.

**GIF capture**
![1010cg-bug-ch2p3-other-health-ins-name](https://user-images.githubusercontent.com/587583/83595951-442fc180-a518-11ea-9e83-5e474b249eeb.gif)

## Desired behavior
\[See [design prototype](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/417174664)]
- **Name of health insurance** textbox should be required.
![1010cg-ch2p3](https://user-images.githubusercontent.com/587583/83589594-f19ad900-a508-11ea-9820-52e851a52c61.png)
- Clicking **Continue** button with textbox blank should display error-message, instead of advancing to next form-page.

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
@LinnJS  - Can you confirm that with the other QA changes you made, this bug is resolved? (Form continuing even if required other health care is not entered)
