### ISSUE TITLE
Set up entry points for Adaptive Housing Application

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#97456]
### Description
This team launched the form and we just found out. We don't know when it went live (somtime after April), but we do know there are some entry points missing, and we want to make sure that the form has the right URL, is in our sitemaps correctly, and has best bets that it might need. 

### Links

- [IA Spec in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/housing-grants-application.md)
- [Intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53077)
- [Slack convo about this from last November
](https://dsva.slack.com/archives/C044AGZFG2W/p1700516181169419)
- [form URL](https://www.va.gov/housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555/introduction)
- [old redirect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16493) when the form was taken down, before being put back up without us knowing
 
### Team

Forms team
- OCTO-DE product owner: Matthew Dignee
- Product manager: Tricia Baker
- Designer: Jeana Clark
- FE engineer: Tze Lei
- Product/team Slack channel: product-teams-forms

## Acceptance Criteria
- [ ] IA closeout steps are fully resolved
   - [ ] all entry points are set up
   - [x] updated mural sitemaps
   - [x] set up any best bets
   - [x] confirmed the URL/breadcrumbs are accurate

**Comment by kristinoletmuskat** [comment]
Sam is going to pick this up with Triana the first week of December.

**Comment by scjwalker** [comment]
To do:
- [ ] Cut entry point 2 - A and T
- [ ] Update form page in Drupal to have the correct widget into the form - A and T
- [ ] Review Disability page (#4) for SHA SAH acronyms - A and T
- [ ] 5 left nav, text should be "Apply now" - Sam to do
- [ ] mega menu " how to apply for an adaptive housing grant" and "apply for an adaptive housing grant" - Sam to do
- [ ]

**Comment by scjwalker** [comment]
All entry points implemented by IA are done.
Keeping this ticket open since Content has one entry point on Housing hub page that is an entry point - not a cross link. Want to keep this on my radar until that's done, before closing out the ticket.

**Comment by scjwalker** [comment]
Closing this, since Triana and A. and I have mainly been touching base in Slack and can also work against the outstanding items in the Intake ticket comments.
