### ISSUE TITLE
10-10d sponsor info doesn't get address selection drop after signer enters for themself

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97476]
Env: staging

Expected behavior
When user begins 10-10d, selects applying for themself, and enters their address, the user should be able to select that address when entering sponsor info.

Actual behavior
In above scenario, user must enter the sponsor's address without an option to select another.

**Comment by michaelclement** [comment]
Work is done in the above PR. Waiting on:
- [ ] Team approval
- [ ] Platform approval

**Comment by michaelclement** [comment]
@baltes this has been merged and is ready to review. Thanks!
