### ISSUE TITLE
Design | Update GI benefits text & URL on My VA

### ISSUE THREAD

**Issue by a6marinos** [department-of-veterans-affairs/va.gov-team#97509]
As part of an [initiative to update the naming and routing for GI Bill benefits](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/rename-post-9-11-GI-Bill-SoB.md), there is an ask to update the language used for the GI Bill benefits link in the **Education and training** My VA. The URL will also need to be updated to an updated page for GI benefits. 

Text Change:
Current: Check your Post-9/11 GI Bill benefits
New: Check your remaining Post-9/11 GI Bill benefits

URL Change:
Current: [va.gov/education/gi-bill/post-9-11/ch-33-benefit/status](http://va.gov/education/gi-bill/post-9-11/ch-33-benefit/status)
New: [va.gov/education/check-remaining-post-9-11-gi-bill-benefits/status/](http://va.gov/education/check-remaining-post-9-11-gi-bill-benefits/status/)

![Image](https://github.com/user-attachments/assets/0ca303bb-961b-4201-814c-87d94828f75b)

**Comment by ACParker89** [comment]
@mattmarino-adhoc is there an epic for this?

**Comment by mattmarino-adhoc** [comment]
@ACParker89 I am not sure

**Comment by mattmarino-adhoc** [comment]
[Mockup of change](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=3414-26685&t=C16A7XiAsgEfPOn6-1)

**Comment by mattmarino-adhoc** [comment]
@a6marinos @allisonlu @ACParker89 I am going to close this out. Can you make a dev ticket for this for the backlog?

**Comment by a6marinos** [comment]
@mattmarino-adhoc you're good to close this! split out a dev ticket earlier today [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99285) - @allisonlu i just copied the story details over but we can refine this more if you end up picking this up
