### ISSUE TITLE
[Tier 3: Low] Facility Locator Incorrect Data

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#9751]
Issue Description: User/Provider has informed that the information is incorrect on the website.  Asking for all data to be updated.

Priority: Low

Total Number of Issues: 1

Issue Number and User Description:

**IRIS: 200529-000350**

Hello. We are a community provider, and our contact information on the VA’s website is inaccurate. The email address to contact, availability, and a couple other sections need updated with pertinent information to our facility. Can somebody please contact me to update the information so we may be able to be of more assistance to our Veterans? Thank you!

**Comment by mmiddaugh** [comment]
@clantosswett @Kimberley2019 
We'll be happy to follow up. Please email the name (and other available info) of the Facility and the missing or inaccurate detail to VHAOCCPPMSPROJBUSPOCS@VA.GOV, copying Tobie Wethington (Tobie.Wethington@va.gov) Dave Conlon (david.conlon@va.gov) and myself, Michelle Middaugh (michelle.middaugh@adhocteam.us).

**Comment by Kimberley2019** [comment]
@mmiddaugh I have just emailed you the contact information.  Please let me know if you need anything else.

**Comment by Kimberley2019** [comment]
@mmiddaugh 
Currently, this issue has been with your team for over seven days and we have not received any confirmation. Please advise if there is any additional information that we can obtain and provide to you in order for your team to accurately address this issue.

Thank you in advance.

Kind Regards,

The VSP Contact Center Team

**Comment by mmiddaugh** [comment]
Thank you for the follow up. We can close this issue.
