### ISSUE TITLE
STEM: Update breadcrumb of 10203 application

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9755]
As a developer, I need to update the breadcrumb of the new 10203 form so that it matches the new DEPO design patterns and practices.

## Assumptions:
1. This story originated from #9699.

## Acceptance Criteria:
1. The breadcrumb for the 10203 form is: **Home > Education and training > Other VA education benefits > Edith Nourse Rogers STEM Scholarship > Apply for the Rogers STEM Scholarship**
    a. Home link: [https://[environment].va.gov/](https://staging.va.gov/)
    b. Education and training link: [https://[environment].va.gov/education/](https://staging.va.gov/education/)
    c. Other VA education benefits link: [https://[environment].va.gov/education/other-va-education-benefits/](https://staging.va.gov/education/other-va-education-benefits/)
    d. Edith Nourse STEM Scholarship link: [https://[environment].va.gov/education/other-va-education-benefits/stem-scholarship/](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/)
    e. Apply for the Rogers STEM Scholarship: Read only and displayed when the user is on this page: [https://[environment].va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction)
2. For mobile, the breadcrumb only shows the previous page so users can click back up the hierarchy **- this should be standard functionality**. So while on the application the breadcrumb would show "< Edith Nourse STEM Scholarship". Clicking back one by one would walk the user back up, so the progression would be:
< Edith Nourse STEM Scholarship
< Other VA education benefits
< Education and training
< Home

## Supporting Artifacts:
1. https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/registry.json#L573

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14239

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Tested by the following test case

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by delli-gatti-michael** [comment]
#13717 was found as a result of UI/UX review and will be worked separately. Closing this issue
