### ISSUE TITLE
Design: Flow to direct CHAMPVA applicants from 10-10d to 10-7959c

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97569]
Users that report that they have other health insurance on the [CHAMPVA Registration (1010d](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/Application-for-CHAMPVA?node-id=4474-708&node-type=canvas&t=aX285mAjC4VNiTKT-0)) need an simple way to be directed to the complete and submit the digital version of the [OHI cert](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3646-449&node-type=canvas&t=UxsHOsIiR6n29z2B-0) (when it goes into to production).

The solution will be an interim solution that we can quickly implement while we work on the full 1010d- OHI integration as one so user can submit both of these as part of one session. 

- [x] Brainstorm and ideate possible user flows for the 1010d and OHI
- [x] Create hi-fidelity mockups in Figma for user flows
- [x] Review options with Bo, Premal and Lois

**Comment by rspope** [comment]
Options created and reviewed in design sync 12/16. Options need to laid out with pros and cons to each - that will be a new ticket. This ticket can be closed.
