### ISSUE TITLE
VES: Review current API spec for VES endpoint

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#97576]
As an IVC Forms team member developing against the VES API spec, I need to know what issues we might run into so that I can take them back to the VES team.

Current API spec
https://dev.ves.va.gov/ves-vfmp-app-svc/swagger-ui/index.html#

Acceptance criteria
- Identify gaps between VES spec and our data
- Gather questions we need the VES team to answer
- Feasibility check for sending data
- Identify additional user stories needed

**Comment by michaelclement** [comment]
[Notes and questions](https://docs.google.com/document/d/1R8UGOKe-3POEWT-xTQ6TkrXHZaeUxYdnXWjo31w4a6k/edit?usp=sharing) from a spec review meeting the engineers had today.

**Comment by michaelclement** [comment]
@baltes Yes, that works for me, thanks.

**Comment by baltes** [comment]
@michaelclement Great, please email questions to Muthupalaniappan, Meenatchi M. (Booz Allen Hamilton) <[Meenatchi.Muthupalaniappan@va.gov](mailto:Meenatchi.Muthupalaniappan@va.gov)> (she goes by Meena). Please copy @pshahVA , me, and anyone else from our team you'd like to include.
