### ISSUE TITLE
Unauthenticated Support - BAH Education [School Ratings]

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9758]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/product-outline.md)

## Problem Statement (from BAH team)
When Veterans are looking for schools within the Comparison tool, they want to know about the experiences of other Veterans to form a better understanding of what their personal experience at the school would be like. Ratings enable Veterans to quickly assess the suitability of a school (both pro and con), bolstering their confidence and level of comfort in deciding if a particular school is right for them.

How might we bolster GI Bill beneficiaries' confidence and level of comfort when picking schools using the Comparison Tool? Ratings enable them to quickly ascertain the experiences of other Veterans at a particular school and assess the overall suitability of that school for them.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by stephorkandatx** [comment]
A project kickoff for this initiative was held on 06/01/2020. 
Incorporating a rating system into the GI Comparison tool would potentially provide information to prospective veteran students that doesn't exist elsewhere - specific to students using the GI Bill benefits. 
BAH was guided to use the intake form, and to reach out sooner rather than later so we can collaborate. 
Creating this Epic now as requests may start coming in.

**Comment by FranECross** [comment]
Closing as obsolete.
