### ISSUE TITLE
NOD Confirmation Page Audit

### ISSUE THREAD

**Issue by comaurice** [department-of-veterans-affairs/va.gov-team#97618]
Regular audit of NOD Confirmation page. This will mimic the testing done to prepare for a staging review, as spelled out in the [Platform documentation on accessibility staging reviews](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

For: Downloadable Copy of Submission, Decision Reviews.

### URL For testing

[Test URL on Staging](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/confirmation).

Tested with a variety of test users, but started with `vets.gov.user+236@gmail.com`.

Some notes:

- For this launch, we're only testing the confirmation page, since no other changes have been made to the form flow.

### Product information

- [x] Team name, product name, and feature name have been added to the title of this issue.
- [x] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

David Kennedy

### Use of color and color contrast checks

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1 contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

No issues here. Using the standard design system components and no additional elements.

### Who completed the axe scans?

David Kennedy

### axe checks

- [x] Each page has been scanned using axe (results shared below)
- [x] axe is integrated into your end-to-end testing

### axe DevTools scan results

No issues found.

### How did axe testing go?

Also tested with HeadingsMap tool to scan for proper heading structure. No issues there either. Lastly, I did some testing with the ARC Toolkit accessibility scanner on select pages. No major issues found there either.

### Who completed the content zoom and reflow test?

David Kennedy

### Content zoom and reflow checks

- [x] All page elements are readable and usable at 200% zoom
- [x] All page elements are readable and usable at 300% zoom
- [x] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

No issues.

### Who completed the keyboard navigation test?

David Kennedy

### Keyboard navigation checks

- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

No issues.

### Do you have any other results to share?

I also tested using a screen reader: VoiceOver with Safari on a Mac, JAWS with Chrome on Windows and NVDA with Firefox on Windows. No issues to report there.

**Comment by davidakennedy** [comment]
@comaurice Finished testing, and updated the body of the ticket with my findings. No issues.

**Comment by comaurice** [comment]
Fantastic thanks DK! @davidakennedy
