### ISSUE TITLE
Update 526 Form Flow diagram for New Confirmation Page

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#97630]
## Issue Description
As a VSF team member I want to update the 526 form flow diagram to include changes for New Confirmation Page so that I have documentation of the current state I can share with others.

## Tasks
- [ ] Update the form flow diagram to match changes to the Confirmation page

## Acceptance Criteria
- [ ] The form flow diagram is updated to include changes to the Confirmation page

## Additional Information
[form flow diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792)

**Comment by mayacarrolluxa6** [comment]
Updated the Mural board. https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=u2d8a66f6d38755bd8c4c6218
