### ISSUE TITLE
[FE/BE] 10-10EZR: Improve Unit Test Coverage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#97659]
As a team member, I would like as close to 100% test coverage so that Veterans never experience bugs when using the EZR.

- [x] Figure out what our current test coverage is
- [x] **Success: We have as close to 100% unit test coverage as possible**

**Comment by JoshingYou1** [comment]
As of 12/2/24, all EZR-specific **_backend_** code has $\color{#228B22}{perfect}$ code coverage! 🥳 
![Image](https://github.com/user-attachments/assets/f9ad38aa-04d1-49a4-83ea-7229efaae2f9)

**Comment by JoshingYou1** [comment]
As of 12/10/24, the EZR frontend test coverage is at 97.63%! 💚 
![Image](https://github.com/user-attachments/assets/4e284249-ffc9-4f75-9ec4-1427fd835e70)
