### ISSUE TITLE
[FE] Profile 2.0 bug: Sometimes it takes two clicks to exit edit mode

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#9765]
- open an empty field to edit it
- focus a required a field
- then cancel to exit edit mode

you get a validation error and the form does not close

![close.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/7ce46255-331f-402e-8891-4db987fc8433)

This same issue affects benefit forms when you try to click the "back" button if you have set focus in an empty, required field:

![hca-back-before](https://user-images.githubusercontent.com/20728956/93231301-7367e880-f72d-11ea-9d1f-35bfeb3712b7.gif)

Related: we want to warn users when they exit edit mode when they have unsaved data, so it might be tricky to handle this edge case where a form is marked dirty/unsaved but they didn't actually enter any data. This is an edge case we might just want to live with.

**Comment by sanlouise** [comment]
@erikphansen I am only able to reproduce what you are seeing when I click outside of the hit area of the Cancel button (which arguably is too small and could be expanded). Let's talk about this issue on Monday to see if expanding the hit area is the right way forward or if I am missing something.

**Comment by sanlouise** [comment]
Actually, I was able to reproduce with other steps (focusing on an already empty profile field did not throw any issue for me) so I will spend some more time on this.

(1) Focus on a required field that already has saved info
(2) Remove entered data so it is an empty field
(3) Click on cancel

**Comment by erikphansen** [comment]
@Samara-Strauss just curious why this got raised as a high priority issue the other day.

**Comment by Samara-Strauss** [comment]
@erikphansen I marked it as high priority since it seems like something we want to fix pre-launch. I guess it's not truly a launch blocker, but it seems pretty unideal and like something we'd hopefully get fixed before going live.

I'll move this to medium priority, but still hoping we can fix this this sprint :)

**Comment by erikphansen** [comment]
I'm putting this back in the backlog for now. As @sanlouise had mentioned, this would require some changes deep on the bowels of the form system. And honestly I'm not sure what those changes would even be.

Just for our future selves, here are my notes on this:

This issue is due to a the form system's `liveValidate` feature (a prop on the `Form` component from `@department-of-veterans-affairs/react-jsonschema-form`), which validates the form whenever data changes. Specifically, each form input has an `onBlur` handler that triggers validation. When a user clicks the `CANCEL` button, the first thing that happens is the previously focused form input's `onBlur` handler fires. This triggers form validation. And that form validation somehow short circuits the user's click on the `CANCEL` button. _The `CANCEL` button's click handler is never fired_.

It is possible to turn off the `Form`'s `liveValidate` feature, which fixes this problem. BUT that has the side effect of never clearing any form field errors if they exist, which is a terrible UX.

The other potential way to fix this is to not validate on blur. This might be fine, since validation would still happen on every change of the form field. But it could also introduce other unanticipated side effects.

## Next step
- [ ] try disabling form validation on blur in the `Form` component.

**Comment by Samara-Strauss** [comment]
Ah, ok, so this has to do with how forms are handled across the board on VA.gov? If so, this sounds like an issue for the platform team and not for our team to reevaluate this functionality. Am I understanding that correctly?

**Comment by erikphansen** [comment]
Well, yes and no. We totally have the power to try to figure out a solution for this and submit the fix to the form system. And since we might be one of the rare team's the has a problem with the existing behavior, it makes sense for us to be the ones to figure out a solution. So now it's just a question of priority. This issue also affects Profile v1 and has for some time. It's also an edge case; you can still pop open an empty field and immediately cancel out of it without running into this. Maybe this is worth chatting about in standup?

**Comment by erikphansen** [comment]
Oh, there is a way to run into this same issue in any of our multi-page benefit applications:
1. Start working on any benefit application
2. Move past the first page
3. Set focus on any required field
4. Then click the `back` button

![validate-error](https://user-images.githubusercontent.com/20728956/91746127-f8210700-eb70-11ea-9086-d2e8cf9cf615.gif)

**Comment by Samara-Strauss** [comment]
> Well, yes and no. We totally have the power to try to figure out a solution for this and submit the fix to the form system. And since we might be one of the rare team's the has a problem with the existing behavior, it makes sense for us to be the ones to figure out a solution. So now it's just a question of priority. This issue also affects Profile v1 and has for some time. It's also an edge case; you can still pop open an empty field and immediately cancel out of it without running into this. Maybe this is worth chatting about in standup?

Yes, let's talk about it in standup. We can definitely work on this and submit a fix to the form system, but agreed that this is not top priority this sprint.

**Comment by Samara-Strauss** [comment]
Removed this ticket from this sprint's milestone and moved it to the backlog. cc/ @mshea0606 to update the sprint epic accordingly.

**Comment by mshea0606** [comment]
@Samara-Strauss sprint objectives have been updated

**Comment by erikphansen** [comment]
I believe this ticket was added to the sprint accidentally, but I came up with a fix that will require approval from VSP🤞

**Comment by Samara-Strauss** [comment]
Does this need to be moved out of this sprint? Totally understand you need VSP approval, but can't tell if you're implying that this can happen quickly or if we need to push this out past this sprint. I'm OK if we need to move this.

**Comment by erikphansen** [comment]
It may or may not be approved by VSP. If they don't like my approach, we can take it out of our sprint and even our backlog because at that point it's going to be on VSP to adjust the form system code. 🤞

**Comment by Samara-Strauss** [comment]
Got it. Will leave it where it is for now pending VSP discussion.

**Comment by mshea0606** [comment]
@erikphansen  will make a new ticket for VSP to fix the underlying issue

**Comment by erikphansen** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/19473
