### ISSUE TITLE
Facility Locator Community Care Latency

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#977]
## Problem
Community Care searches require multiple repeated round trip queries which result in the following issues: 
- High latency/search performance: Users have reported that when they try to search on Community Care that it could take anywhere up to 2 minutes to return data. 
- Duplication in services for Community Care Providers [#3101] on the search screen and duplicated service descriptions on facility detail pages (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/977)

## High Level Background
- The community Care Facility Locator is the only FL that stores and retrieves data from the PPMS database.
- PPMS database (Cosmos) is relational dynamic db which was never intended to be geographical search
- There are a few fields that do not get returned in the first call to PPMS, such as phone number, address and services. In order to get that information, a second call is made for every result they get up to 20. The second call gets the additional information and adds it to the record before returning it to the front end.

_Note:_  This EPIC is specific to PPMS DB in facility locator.

**Comment by Karak888** [comment]
As of 9/11/19 the Facility Locator tickets for PPMS related issues (including Urgent Care and in network / speed) have been diprioritized in sprint 4 to finalize and continue work on CMS/Drupal.

**Comment by Karak888** [comment]
@davidconlon was just in the midst of writing this to you when I just got your DM re:  availability!  So essentially this is our Epic for PPMS portion of our Facility locator that I wanted to share / pass on to you and @mmiddaugh.

**Comment by mmiddaugh** [comment]
this epic is closed with our recent changes to optimize the single query
