### ISSUE TITLE
Warn user when they attempt to navigate away from the Profile when they have unsaved data

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#9770]
If a user has started editing part of their profile and attempt to navigate away from the Profile/change the URL, we should warn them that they will lose the info they have entered.

We will need to decide on a UX for this. Show a modal? Show an alert somewhere else? The only thing that we have like this, that I know of, is getting warned when you are filling out a benefit application as a logged-out user and attempt to leave the page. I believe in that scenario you are shown a modal warning you that you will lose data.

**Comment by mshea0606** [comment]
@tressaellen could you add an estimate to this ticket? Thanks!
