### ISSUE TITLE
Platform Security Q4 Access Review - Datadog [DUE December 16 2024]

### ISSUE THREAD

**Issue by kell-y** [department-of-veterans-affairs/va.gov-team#97701]
**Access Review Description:** 

OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

OCTO-DE teams periodically review user access to ensure that access is limited to users who currently need to access the systems and applications and that those users have the appropriate permissions.

Platform Security initiates each review cycle and application owners are responsible for executing the process for each application that they own. Once complete, application owners document the results of the access review and send the artifacts to Platform Security to document in eMASS as evidence.

Tasks:

The Q4 access reviews should track any users that were removed or changed outside of normal offboarding processes since the last access review completed in September 2024.

_Note: For Datadog, we are only analyzing elevated privileges (read access or standard roles only)_

- [ ] Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why.
- [x] Cross reference an individual in DataDog that has the read access and cross referencing with request in support role 
- [x] Ensure that existing users have the correct permissions.
- [x] Ensure that every system has at least two administrators, and that any system which is expected to persist even if administration transitions to a new contractor has at least one administrator who is a government employee.
- [x] Document the results of the review using the linked template: [Datadog](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3613753396/Q4+2024+ACCESS+REVIEW+-+Datadog).

AC:

- [ ] Notify Platform Security that the access reviews are complete.

Resources:
Below are three links that describe the access review process:

- [Access Review Process](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2987917734/Access%2BReview%2BProcess&sa=D&source=calendar&ust=1719158451280711&usg=AOvVaw08AyZp9deGU070J8dJO3PF)
- [Access Review Rollout Plan - First Iteration](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3133177925/Access%2BReview%2BRollout%2BPlan%2B-%2BIteration%2B1&sa=D&source=calendar&ust=1719158451280711&usg=AOvVaw0GhA4tfW05Zzqt09vNiBkp)
- [Access Review Inventory](https://www.google.com/url?q=https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2986115091/Access%2BReview%2BInventory&sa=D&source=calendar&ust=1719158451280711&usg=AOvVaw39aqVCe_N4uS34DpyhDjiG)

**Comment by bmatos312** [comment]
https://docs.google.com/spreadsheets/d/1KzU-XvoEGsC0KvkK2mj7nLrL_ePNG5SsHUNwp7QcaFE/edit?usp=sharing
Completed review but dont have access to remove users or to check if they are fed ramped.

added to DD list here[
](https://vfs.atlassian.net/wiki/x/NIBl1w)
