### ISSUE TITLE
HLR | V2 API endpoint for HLR form changes

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#97726]
## Value Statement

**_As a_** Veteran

**_I want to_** be confident that Higher Level Review form versions can be distinguished

**_So that_** any issues with the new form changes can be detected

---

## Background Context

- As the HLR form was updated in #85851, we will need a way to incrementally roll out the changes and ensure there are no issues with the new version. We will be adding a /v2/ version of the Higher Level Reviews submission endpoint which the frontend will be able to send requests to.

Slack thread for context: https://dsva.slack.com/archives/C05FCEH2NRG/p1732211870217139

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
PR ready for review.

**Comment by eileen-coforma** [comment]
@Mottie to also update frontend to use V2 endpoint

**Comment by Mottie** [comment]
Needs BE testing prior to merging in FE work.

**Comment by dfong-adh** [comment]
Verified HLR v2 backend endpoint in staging
