### ISSUE TITLE
POA requests landing page - pilot design

### ISSUE THREAD

**Issue by eheintzelman** [department-of-veterans-affairs/va.gov-team#97737]
**Issue Description**
For the pilot POA requests feature, there will be a landing page displaying POA requests. Design worked on this last Sprint focusing on coming up with an approach to search/filter. This ticket is refine [this design](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=1958-54431&t=5J24u0EHQ08wWlA2-1), resolve a few outstanding questions and prepare the design for engineering hand-off. 

**Open issues**
- tags/statuses. Need sync with engineering to discuss all statuses that we want to render on the cards and align on how this ties to back-end tags. Also run by ARM team. Some [prior discussion here](https://dsva.slack.com/docs/T03FECE8V/F06H1TS0GBZ?focus_section_id=temp:C:IdVe984ea7f82194284879967f92) from August. Tentative list below: 
  - Pending
  - Accepted
  - Declined
  - Withdrawn (what action will trigger this? in ARM teams planned launch, is there a self-service way for Veteran's to withdraw?)
  - Canceled (not sure this is needed in addition to withdrawn, but perhaps could be used if there were a way for a VSO to cancel a request from their end?)
  - Expired (do we render these? For how long do we render expired requests? do we disable link for these?)
- default sort order for request list
- sort options. Tentative list below:
  - By expiration date or decision date, depending on status
  - Alphabetical (very big maybe; potential technical challenges)
- How long do we make POA requests (regardless of status) available in the UI? 60 days? 90 days? 
- What do we want for the quick filter tabs? Pending requests is a definite. But then for the other tab, what do we want? Completed requests? All requests? 
- null states
- error states

**Acceptance Criteria**
Figma design has been refined to address the issues above and is ready for engineering hand-off.

**Comment by candilemoine** [comment]
Questions for planning: 
- what type of order would POA requests by default? 
  - Pending => Created by (newest to oldest)
  - Completed => Last updated (newest to oldest)

**Comment by eheintzelman** [comment]
@candilemoine I'll add the default sort discussion to the list of open questions.

**Comment by candilemoine** [comment]
Have a separate discussion: 
- Kate
- Jen S
- Candi
- Oren
- Kevin
- OJ

**Comment by seipeljl** [comment]
[Notes from team work session 12/03/24
](https://dsva.slack.com/docs/T03FECE8V/F0813G0JM5X?focus_section_id=temp:C:ULTe9a41743e8e94f7e8bbd072e4)

* tags/statuses
    * we'll be tracking all statuses, representation in the UI trivial/TBD
    * withdraw: not aware of ARM allowing Veterans to withdraw a request - check with ARM if this is planned
    * Pilot: pending, accepted, declined
    * all other statuses TBD in future


* sorting
    * MVP/default: most recent at top
    * better option: allow user to sort ascending or descending by date (expiration, decision)
    * Pilot: all sorting options are feasible, design will make a recommendation
* how long do we make POA requests available?
    * have to purge PII after 60 days, but we can retain the skeleton of the request
        * should these skeletons remain visible?
    * should the 60-day timer "reset" after a request is accepted or declined?
        * security question: can we extend the 60-day if the request is accepted?
        * Oren/Sam: Is it ok to reset the 60-day counter when a request is accepted?

**Comment by Kate-allbee** [comment]
Design Rec for Sorting:

- Pending= Sort by expiration date ( Soonest to latest). Default to Soonest
- Completed = Sort by Date completed (newest to oldest). Default to Newest

**Comment by Kate-allbee** [comment]
[Thread on colored tags experimental design](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2993)
