### ISSUE TITLE
[BE, PM] - Turn on flipper toggle to disable BGS call in Production during planned COLA downtime

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#97751]
## Background
- As part of the Cost of Living Adjustment (COLA), some systems (EVSS, BGS, VBMS) will be down over the weekend of 11/16-17. - This was postponed to unknown date.  
- The feedback provided last year was that there were still calls going to BGS (not just EZ form) even though it was going to be down, which caused an excess of errors, making it difficult to determine actual errors.

## Scope
- Temporarily disable the call to BGS for disability ratings on the 10-10EZ during the update weekend

### Resources
- Slack channel for COLA info: [#cola-downtime-planning](https://dsva.slack.com/archives/C064JKBD0N8)
- SNOW ticket [CHG0538489](https://yourit.va.gov/now/nav/ui/classic/params/target/change_request.do%3Fsys_id%3D9f06901a97a19a1442d1fcc0f053af54%26sysparm_view%3DDefault%2Bview%26sysparm_view_forced%3Dtrue) (VA Network)
- Slack Canvas - [COLA Overview & Retro](https://dsva.slack.com/canvas/C064JKBD0N8)
- Flipper toggle was added in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97030)

## Tasks
- [x] Turn on toggle `hca_disable_bgs_service` before downtime window - Saturday starting at ~4am ET
- [ ] Turn off toggle `hca_disable_bgs_service` after downtime window - Sunday at ~7pm ET
---
## Acceptance Criteria/Definition of Done
-  The 10-10EZ form will not be calling BGS while it is down, reducing the opportunity for erroneous error messages

**Comment by hdjustice** [comment]
Feature toggle turned on for this weekend.

**Comment by coope93** [comment]
[Slack comment on turning the toggle on/off for the outage](https://dsva.slack.com/archives/C0310PNS7TQ/p1732916111614219)
