### ISSUE TITLE
Adding Lauren Dawson to DSVA Slack

### ISSUE THREAD

**Issue by pammicmac** [department-of-veterans-affairs/va.gov-team#97777]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Lauren Dawson lauren.dawson@agile6.com as a full member to to DSVA Slack, new UX Design/Researcher on Disability Benefits Experience Team 1. 

- What channel(s) do they need to be added to?
  - [#benefits-disability](https://dsva.slack.com/archives/C04KW0B46N5)
  - [#benefits-disability-design](https://dsva.slack.com/archives/C053UDWMH7U)

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by goldenmeanie** [comment]
Invited as full member with lauren.dawson1@va.gov address. You should be able to add Lauren to those channels yourself, once the invite is accepted.
