### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#97781]
### Name

Wesley Rowe

### Email

wesley.rowe@agile6.com

### Role

product mgr

### Team

Cartographers - MHV-on-VA.gov

### Additional Notes

I only need a view account, no need for edit. Thanks!

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to [wesley.rowe@agile6.com](mailto:wesley.rowe@agile6.com).

**Comment by wesrowe** [comment]
thanks, I'm in!
