### ISSUE TITLE
Account Security content indentation

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#9779]
Should this bit of indentation be removed? @tressaellen 

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/b697958d-de5f-49e0-90d4-735eade69328)

**Comment by tressaellen** [comment]
I've gone back and forth on how that should be aligned... would it be possible to align all of the text and then have the icons aligned? Something like this?
<img width="693" alt="Screen Shot 2020-06-03 at 8 43 51 AM" src="https://user-images.githubusercontent.com/58752772/83664459-7ec84700-a576-11ea-8ed5-fb275d3dd0de.png">

**Comment by erikphansen** [comment]
Well anything is possible! But I'm not crazy about this from a coding perspective. 

![image](https://user-images.githubusercontent.com/20728956/83687756-12af0880-a5a1-11ea-9a64-08330e9b8d1a.png)

What is the bounding box for the content area? The the thin outer cyan box or the thicker inner orange box? If it's the outer cyan box, that means that all the content that _doesn't_ have the green check needs to have extra left padding/margin applied to it. If the inner orange box defines the content area, that means that the green checkbox would need to be pulled out of the content area.

I would vote for using the screenshot I included in the original post of this ticket as the starting point and removing the extra padding that I'm point to. Would be a simple fix where we just make this `<p>` a sibling to the `<Verified>` component rather than a child of it: https://github.com/department-of-veterans-affairs/vets-website/blob/5ee630fcfcc4f8bbec728427b30d614fa3ac79cb/src/applications/personalization/profile-2/components/MHVTermsAndConditionsStatus.jsx#L17-L30

**Comment by tressaellen** [comment]
Sorry @erikphansen I must've missed this comment.  That makes sense, no need to make it more difficult. I'm fine with using the originally screenshot that you posted and removing the padding on the link text.

**Comment by erikphansen** [comment]
@tressaellen Good timing, as I was gone for days anyway!

**Comment by erikphansen** [comment]
@tressaellen @mshea0606 sounds like the alignment of these items with green check marks will be changing, but this little fix can be validated in staging.
