### ISSUE TITLE
Everyone Attend general onboarding meeting

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#978]
Check box when this has been completed and comment "done". 

- [x] Attend general onboarding meeting

**Comment by Samara-Strauss** [comment]
Which of our meetings was this last week?

**Comment by Justin-Pickett** [comment]
I believe this is considered the meeting that happened on 08/05 - VSA: All Team Onboarding

**Comment by mojaray2k** [comment]
Done

**Comment by Samara-Strauss** [comment]
OK! Then if everyone was there, I think we can go ahead and mark this as complete.

**Comment by erikphansen** [comment]
Done

**Comment by Justin-Pickett** [comment]
Done.

**Comment by artistgreen** [comment]
Done

**Comment by tlei123** [comment]
Done.

**Comment by Justin-Pickett** [comment]
A.E. team has completed this task. Closing this ticket.
