### ISSUE TITLE
Create research repo label doc

### ISSUE THREAD

**Issue by beckyphung** [department-of-veterans-affairs/va.gov-team#97805]
## Problem statement
Researchers and other team members need to be able to easily search for relevant studies before starting their own study. Researchers are also responsible for adding and creating labels. The process to do this isn't clear right now with current documentation: 

**Location of current documentation**
- [research repo ticket template](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=&labels=&template=new-research-intake.md&title=YYYY-MM+Title+of+Study)
- [research-findings-template.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [How to add research, what to do when research is complete, and create new labels (if necessary). #70](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70)

## Definition of done
- [x] new page added to platform site
- [x] new page communicated to researchers
- [x] update current documentation pages to link to the new page

## Research principles
This effort relates to the following [Research Operations Principles](https://dvagov.sharepoint.com/sites/oitocto1/SitePages/OCTO-Research-Operations-Overview.aspx):
- 3.1: Well-defined processes

## Monthly updates
- Dec 2024: Naomi added [the page](https://depo-platform-documentation.scrollhelp.site/research-design/adding-labels-in-the-research-repository). Just need to update current documentation pages to link to the new page.
- Nov 2024: Drafted new content [in this Slack canvas](https://dsva.slack.com/canvas/C07ALBM9MAL). Messaged Shane to review. Naomi added it to the task board to create the page ([see Slack](https://dsva.slack.com/archives/C0216PL32HJ/p1732566706305229)).

## Stakeholders
- Naomi Marcussen (Platform team)

## Docs
- [Excel](https://dvagov-my.sharepoint.com/:x:/g/personal/becky_phung_va_gov/EXtEdu3k3IJOllOVffqrjoQBVmU1UarEPKIPKdiiJKc_6g?e=s1B9mG) containing hex codes and label types
- [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1730141257738/325f026f874d22a86db45786598971c2af58a7cc) of research labels and challenges
- [Slack canvas](https://dsva.slack.com/canvas/C07ALBM9MAL) with drafted content for platform page

**Comment by beckyphung** [comment]
I couldn't update [research repo ticket template](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=&labels=&template=new-research-intake.md&title=YYYY-MM+Title+of+Study), but I updated the other existing places where labels are mentioned to link to the new Platform page. Moving to closed.

**Comment by beckyphung** [comment]
Actually @sstrassberg would you like to review before I close this?

**Comment by sstrassberg** [comment]
@beckyphung What do you think needs to be changed [research repo ticket template](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=&labels=&template=new-research-intake.md&title=YYYY-MM+Title+of+Study)?

**Comment by beckyphung** [comment]
I was thinking of adding a link to the new labels doc, something like:
> 2. Add 5-15 labels to make filtering and sorting easier. [Learn how to add labels](https://depo-platform-documentation.scrollhelp.site/research-design/adding-labels-in-the-research-repository) in Platform documentation.

**Comment by sstrassberg** [comment]
@beckyphung Okay, I can make that update.

**Comment by beckyphung** [comment]
Thanks for making the update! I'll close this.
