### ISSUE TITLE
[Design] Block users from entering edit mode if they are already editing a field

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9784]
##Background:

FE ticket: #9766

If a user is already editing a profile field, we should not allow them to start editing another field before they stop editing the first one.  What is the best way to do this?

The simplest way to implement this limitation on the FE would be like this:

- user starts editing their home address

- user then clicks the "edit" button to edit their mailing address
- we show an alert in a modal that tells them they need to finish editing their home address before they can edit their mailing address
- they can then close the alert modal and stop editing their home address

This isn't the best UX, but would be the simplest to implement by far.

Slack convo: https://dsva.slack.com/archives/C909ZG2BB/p1590079754288900?thread_ts=1590079754.288900

**Comment by tressaellen** [comment]
![Screen Shot 2020-06-08 at 5.58.43 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/dd43e9d0-491a-4c3e-9268-da8e4d3dbd51)

**Comment by erikphansen** [comment]
@tressaellen is this final copy or does @peggygannon need to weigh in? FWIW here is a GIF of the modal showing up (with my temporary text)

![block-edit](https://user-images.githubusercontent.com/20728956/84422866-7e612900-abd2-11ea-9ca6-1712da83e5ab.gif)

**Comment by tressaellen** [comment]
We still need to get things approved by Peggy. But either way, we should probably keep 'Oopsie Doopsie'

**Comment by erikphansen** [comment]
@tressaellen @peggygannon Any update on the final copy/UX for this alert modal to show users when they are in the middle of editing one profile field and try to edit another?

**Comment by tressaellen** [comment]
@peggygannon if we can't update from the actual modal - I think the content should read something like:

You are currently editing your [section]

You must finish editing your [section] before you can edit your [section].  If you cancel, your in-progress work won't be saved.
[Button] Ok (? I'm still not sure what to put here)

**Comment by erikphansen** [comment]
@tressaellen No, we can't trigger a save of whatever profile field they are currently editing. In theory we could exit them out of edit mode for the field they are editing and then enter edit mode for the field they just _tried_ to start editing. But honestly this all feels a little convoluted to me.  My thought was that if we just added an "ok" or "close" button on the modal we'd be pretty much good to go.

**Comment by tressaellen** [comment]
I agree - if it's okay with you @peggygannon, let's just go with this.

<img width="1144" alt="Screen Shot 2020-06-15 at 1 53 19 PM" src="https://user-images.githubusercontent.com/58752772/84699966-eb403000-aefe-11ea-868a-6004f9c22352.png">

You are currently editing your [section]

You must finish editing your [section] before you can edit your [section]. If you cancel, your in-progress work won't be saved.
[Button] Ok

**Comment by erikphansen** [comment]
I like how this would work

**Comment by peggygannon** [comment]
@peggygannon @erikphansen Hello! I really like Oopsie doopsie, ha, would that be fun to use. 

In an earlier ticket, i had recommended the below content so we didn't repeat the [section] inputs in the body of the message. What do you think of this? 

You're currently editing your [section]
Please go back and save or cancel your work before editing a new section of your profile. If you cancel, your in-progress work won’t be saved.
[Button] OK

**Comment by tressaellen** [comment]
This is perfect - thanks so much @peggygannon!

<img width="1113" alt="Screen Shot 2020-06-16 at 11 38 15 AM" src="https://user-images.githubusercontent.com/58752772/84808420-20a75500-afb5-11ea-8b69-7152cf5752f0.png">

**Comment by peggygannon** [comment]
hi, @tressaellen can you please update the screenshot to match the message? 

You are > should be You're
and Ok >should be capped OK

**Comment by tressaellen** [comment]
Yes - great catch!

<img width="1121" alt="Screen Shot 2020-06-16 at 11 41 29 AM" src="https://user-images.githubusercontent.com/58752772/84808718-93b0cb80-afb5-11ea-903a-70762bc1f6a7.png">
