### ISSUE TITLE
Allow for text-only row in ProfileInfoTable

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#9785]
We need to adjust the ProfileInfoTable to allow for a row/cell to hold pure text content:

![83567176-a911fa00-a4cd-11ea-9675-6382c00267f7.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/308fc4fc-79e6-44ea-8655-0582c5239450)

Related ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9733

**Comment by erikphansen** [comment]
Currently blocked. Will meet with Jen Strickland tomorrow to chat about the proper HTML structure for this table. [This codepen](https://codepen.io/jenstrickland/pen/eYJmdaX?editors=1100) shows two potential paths forward.

**Comment by sanlouise** [comment]
@mshea0606 There is nothing to validate here on your end, just a code update to allow for text-only rows and an accessibility update :)

**Comment by mshea0606** [comment]
Thanks @sanlouise
