### ISSUE TITLE
AWS access for Bryan Thompson

### ISSUE THREAD

**Issue by SnowboardTechie** [department-of-veterans-affairs/va.gov-team#97859]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Bryan Thompson

### Your Email

bryan.thompson@agile6.com

### Team, Role, and Company of the target individual

Sitewide, Facilities and Public Websites, Agile6 Applications Inc.

### Product Manager (PM) name and email

Jill Adams jill.adams@agile6.com

### Product Owner (PO) name and email

Michelle Middaugh (suzanne.middaugh@va.gov)

### Desired AWS Access

Requesting parameter store access. We need access to both existing paths, and to create a new set of paths/values.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/49f5752e-6d2a-40c9-90fb-7dd8d1fa2aee)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
Access granted!
