### ISSUE TITLE
Qualitative Data Request.

### ISSUE THREAD

**Issue by JonathanPostMO** [department-of-veterans-affairs/va.gov-team#97866]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

11-01-2024

### Date Range End

11-30-24

### Product Name(s)

Secure Sign-in Transition (SSIT) Identity Team (MO)

### Product Description

SSIT is the team responsible for deprecating MyHealtheVet and DS Login, moving users to secure, multi-factor authentication credentials, that are IAL2 compliant. MO is working specifically on change management for this project, helping Veterans and VA employees navigate the sign-in transition. We're looking for the qualitative data from Ask VA (AVA) or call center, for all things related to sign-in. We're able to pull the quantitative data, via Domo, but would like to review feedback or other qualitative data as possible, so we can include it in the thematic analysis we're doing as part of desk research while cataloging common pain points and edge cases. 

### Survey URL(s), key term(s), case category or type

In Domo, these are the drill downs I use when pulling quantitative data: 
- Case type: Signing in to VA.gov and managing VA.gov profile
- Case Tier: AVA
- Case Category: Sign in and technical issues 

### Sub URLs

Yes

### File Delivery Format

All in one file, on one tab

### Word Cloud

No

### VA Email Address(es)

jonathan.post@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by JonathanPostMO** [comment]
Hey @newworld2616 this issue automatically assigned to @ATMiddleton when I created it—do I need to update the assignee field?

**Comment by newworld2616** [comment]
Hi, the AVA data is not available on MYVA 411. There is other source for AVA data. Let me know if you have any questions. Thank you.
