### ISSUE TITLE
STEM: Create 10203 Schema

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9788]
As a developer, I need to create the backend schema for the 10203 form so that the form can be submitted properly.

## Assumptions:
1. This work is done behind feature flag #7271.

## Acceptance Criteria
1. The new/updated schema with data elements outlined in Supporting Artifact # 1 is in the vets-json repository.
2. The vets-api schema leverages the vets-json schema. 
3. The vets-website schema leverages the vets-json schema.

## Supporting Artifacts:
1. [10203-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4731652/10203-Fields.xlsx)
2. [Prototype](https://bahdigital.invisionapp.com/share/WPIADZ0CXQF#/screens)

**Comment by dmccurdybah** [comment]
##Pull Requests

vets-json-schema: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/439

vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/13024

vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/4372

**Comment by dmccurdybah** [comment]
The 3 PRs referenced above have been merged.  Closing story.
