### ISSUE TITLE
Adding Nate Chen to Google Analytics

### ISSUE THREAD

**Issue by Great2BNate** [department-of-veterans-affairs/va.gov-team#979]
# Analytics Access Request

## User Email Address: 
nchen@governmentcio.com

## Access Requirements
VA.gov - _Additionally please see Product Team Below._

## Date Required
ASAP

## Product Team / External Team / VA Office : 
Benefits Team (aka Unicorns)

## Additional Comments
Hi, there may be other sites I might need access to, however, i thought it would be best to begin my analytics audit on the main VA.gov website. Please advise.

**Comment by joanneesteban** [comment]
@Great2BNate You've been added to Google Analytics and you should receive an email - please us know if that access doesn't go through. We can walk through other analytics platforms you may need access to when our team goes through onboarding with Unicorns. Please let us know if you have any additional questions!
