### ISSUE TITLE
Bug: Button group component is misaligned.

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#97935]
## Summary

The continue button is shifted down and appears to have  a different chevron icon than the back button next to it.

## Steps to Reproduce
**Test User:** Judy Morrisson

Go to: https://staging.va.gov/my-health/appointments/schedule/type-of-care
The rest of the flow has this issue

### Actual Result

![Image](https://github.com/user-attachments/assets/b936d4b8-063c-4a6b-ae63-7f4367539c49)

### Desired Result

Should use the [button group component](https://design.va.gov/components/button/button-group)

![Image](https://github.com/user-attachments/assets/654520e9-99a1-48de-bedd-1b7f70e46010)

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by JunTaoLuo** [comment]
Ah I see, yea that looks better 😄

**Comment by melissa-lefevre** [comment]
Looks great! No issues
