### ISSUE TITLE
va.gov email addresses in use

### ISSUE THREAD

**Issue by pwideman** [department-of-veterans-affairs/va.gov-team#97957]
As per our [announcement](https://github.com/orgs/department-of-veterans-affairs/discussions/13), you are receiving this notification because there is activity in this repository that violates a forthcoming repository ruleset to prevent va.gov email addresses leaking through commit metadata in public VA repositories.

These users have activity since Nov 14 that is in violation of this policy:

@kbelikova-oddball 

If the users have since updated their email settings then this notification can be safely ignored.

Tagging admins for visibility:

@department-of-veterans-affairs/cto-office 
@department-of-veterans-affairs/cto-office-github-admin 
@department-of-veterans-affairs/digital-service-at-va 
@governance-team 
@department-of-veterans-affairs/vsp-operations 
@department-of-veterans-affairs/vsp-team-leads

**Comment by kbelikova-oddball** [comment]
Performed steps described [here](https://github.com/orgs/department-of-veterans-affairs/discussions/13) and set my email to be not visible.
