### ISSUE TITLE
[Development] BDD: Add Separation Location and Submit Code Down to Our 526 Service

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#9797]
## Issue Description
During our discussion with EVSS we realized we need separation location added to the BDD flow.

Details are provided in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9735

## Acceptance Criteria
- [ ] BDD integrates with the separation location service.
- [ ] BDD submits code down to EVSS during BDD submission.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
BE is still in review, but here's what you'll get when https://github.com/department-of-veterans-affairs/vets-api/pull/4370 merged. 
/v0/disability_compensation_form/intake_sites
`{"status":200,"intake_sites":[{"code":"98283","description":"AF Academy"},{"code":"123558","description":"ANG Hub"},{"code":"98282","description":"Aberdeen Proving Ground"},{"code":"123657","description":"Al Udeid, Qatar"},{"code":"123578","description":"Alameda Coast Guard"},{"code":"98284","description":"Albuquerque"},{"code":"98285","description":"Altus AFB*"},{"code":"98286","description":"Anchorage"},{"code":"123603","description":"Andersen AFB - Air Force / Guam"},{"code":"98287","description":"Andrews AFB"},{"code":"98288","description":"Annapolis NS/USNA"},{"code":"123585","description":"Ansbach, Germany"},{"code":"123617","description":"Arifjan, Kuwait"},{"code":"98289","description":"Atlanta"},{"code":"123610","description":"Aviano AB, Italy"},{"code":"123555","description":"Bahrain / Kingdom of Bahrain"},{"code":"98290","description":"Baltimore"},{"code":"123586","description":"Bamberg, Germany"},{"code":"98292","description":"Barksdale AFB"},{"code":"123568","description":"Baumholder, Germany"},{"code":"123577","description":"Beale AFB"},{"code":"125209","description":"Beaufort Naval Hospital"},{"code":"123554","description":"Benelux (Brussels/Schinnen/SHAPE)"},{"code":"98293","description":"Bethesda NH"},{"code":"98294","description":"Boise"},{"code":"98295","description":"Bolling AFB"},{"code":"98296","description":"Boston"},{"code":"123652","description":"Buchanan"},{"code":"98299","description":"Buckley AFB"},{"code":"98300","description":"Buffalo"},{"code":"123631","description":"CBC Gulfport"},{"code":"123607","description":"Camp Atterbury (Demob)"},{"code":"98301","description":"Camp Casey (Korea)"},{"code":"98302","description":"Camp Lejeune"},{"code":"98303","description":"Camp Pendleton*"},{"code":"123634","description":"Camp Shelby (Demob)"},{"code":"123644","description":"Cannon AFB"},{"code":"123639","description":"Cape May Coast Guard"},{"code":"98305","description":"Carlisle Barracks"},{"code":"98307","description":"Charleston AFB"},{"code":"125210","description":"Charleston Naval Health Clinic"},{"code":"98308","description":"Cherry Point MCAS"},{"code":"98309","description":"Cheyenne"},{"code":"98310","description":"Chicago"},{"code":"98311","description":"Cleveland"},{"code":"123582","description":"Coast Guard Sector Miami"},{"code":"98314","description":"Columbia"},{"code":"123632","description":"Columbus AFB"},{"code":"98315","description":"Corpus Christi NAS"},{"code":"98317","description":"Dahlgren NSWC"},{"code":"98318","description":"Davis-Monthan AFB"},{"code":"98319","description":"Denver"},{"code":"98321","description":"Des Moines"},{"code":"98322","description":"Detroit"},{"code":"123627","description":"Detroit Arsenal"},{"code":"98323","description":"DiLorenzo-Pentagon"},{"code":"123608","description":"Diego Garcia / BIOT"},{"code":"98324","description":"Dover AFB"},{"code":"123623","description":"Dugway Proving Grounds"},{"code":"98325","description":"Dyess AFB"},{"code":"98326","description":"Earle Naval Weapons (new)"},{"code":"123569","description":"Edwards AFB"},{"code":"98327","description":"Eglin AFB*"},{"code":"123547","description":"Eielson AFB"},{"code":"123663","description":"Ellsworth AFB"},{"code":"98328","description":"Elmendorf AFB"},{"code":"98329","description":"Everett NS"},{"code":"98330","description":"Fairchild AFB*"},{"code":"98331","description":"Fargo"},{"code":"98332","description":"Fort Belvoir"},{"code":"98333","description":"Fort Benning"},{"code":"98334","description":"Fort Bliss"},{"code":"98335","description":"Fort Bragg"},{"code":"98336","description":"Fort Campbell"},{"code":"98337","description":"Fort Carson"},{"code":"98338","description":"Fort Detrick"},{"code":"98339","description":"Fort Dix"},{"code":"98340","description":"Fort Drum"},{"code":"98341","description":"Fort Gordon"},{"code":"98342","description":"Fort Hood"},{"code":"98343","description":"Fort Irwin"},{"code":"98344","description":"Fort Jackson"},{"code":"98345","description":"Fort Knox"},{"code":"98346","description":"Fort Leavenworth"},{"code":"98347","description":"Fort Lee"},{"code":"98348","description":"Fort Lewis"},{"code":"98349","description":"Fort Meade"},{"code":"98351","description":"Fort Polk"},{"code":"98352","description":"Fort Richardson"},{"code":"98353","description":"Fort Riley KS"},{"code":"98354","description":"Fort Rucker"},{"code":"98355","description":"Fort Sam Houston"},{"code":"98357","description":"Fort Sill"},{"code":"98358","description":"Fort Stewart"},{"code":"123622","description":"Ft Devens"},{"code":"123640","description":"Ft Hamilton"},{"code":"123668","description":"Ft Worth (ANG Hub)"},{"code":"123666","description":"Ft. Bliss"},{"code":"98359","description":"Ft. Eustis"},{"code":"98360","description":"Ft. Harrison"},{"code":"98361","description":"Ft. Huachuca"},{"code":"98362","description":"Ft. Leonard Wood"},{"code":"123682","description":"Ft. McCoy"},{"code":"123550","description":"Ft. Wainwright"},{"code":"123588","description":"Geilenkirchen, Germany"},{"code":"98363","description":"Goodfellow AFB"},{"code":"123635","description":"Grand Forks AFB"},{"code":"98364","description":"Great Lakes NTC"},{"code":"123584","description":"Guantanamo Bay / Cuba"},{"code":"123620","description":"Hanscom AFB"},{"code":"98365","description":"Hartford"},{"code":"123561","description":"Heidelberg Germany"},{"code":"98366","description":"Hickam AFB"},{"code":"98367","description":"Hill AFB"},{"code":"123643","description":"Holloman AFB"},{"code":"98368","description":"Homeland Security (HS)"},{"code":"98369","description":"Honolulu"},{"code":"98370","description":"Houston"},{"code":"123594","description":"Hunter AAF"},{"code":"98371","description":"Huntington"},{"code":"98372","description":"Hurlburt Field"},{"code":"123665","description":"Incirlik AB, Turkey"},{"code":"98374","description":"Indianapolis"},{"code":"123659","description":"JB Charleston"},{"code":"123660","description":"JB Charleston-AB"},{"code":"123674","description":"JB Langley-Eustis"},{"code":"123679","description":"JB Lewis-McChord"},{"code":"123605","description":"JB Pearl Harbor-Hickam"},{"code":"123676","description":"JBMH-Henderson Hall"},{"code":"123675","description":"JBMH-Myer"},{"code":"98375","description":"Jackson"},{"code":"98376","description":"Jacksonville NAS"},{"code":"123641","description":"Joint Base McGuire-Dix (Demob)"},{"code":"123560","description":"Kaiserslautern Germany"},{"code":"98377","description":"Keesler AFB"},{"code":"98378","description":"Key West CG"},{"code":"98379","description":"Key West NAS"},{"code":"98380","description":"Kings Bay NAS"},{"code":"98381","description":"Kirtland AFB"},{"code":"98382","description":"Kitsap NS* (formerly Bremerton NB)"},{"code":"123615","description":"Kunsan AB, Korea"},{"code":"98383","description":"Lackland AFB"},{"code":"123656","description":"Lajes Field"},{"code":"98384","description":"Lakehurst (Southern NJ)"},{"code":"123571","description":"Landstuhl Reg Med Ctr"},{"code":"105142","description":"Langley Air Force Base"},{"code":"123670","description":"Laughlin AFB"},{"code":"98387","description":"Lemoore NAS"},{"code":"98388","description":"Lincoln"},{"code":"98390","description":"Little Rock"},{"code":"98391","description":"Little Rock AFB"},{"code":"98392","description":"Los Angeles"},{"code":"123563","description":"Los Angeles AFB"},{"code":"98393","description":"Louisville"},{"code":"123559","description":"Luke AFB"},{"code":"98400","description":"MC Recruit Depot"},{"code":"123574","description":"MCAGTC 29 Palms"},{"code":"123662","description":"MCAS Beaufort"},{"code":"123556","description":"MCAS Yuma"},{"code":"98401","description":"MCB Hawaii"},{"code":"123678","description":"MCB Quantico"},{"code":"123596","description":"MCLB Albany"},{"code":"123565","description":"MCRD San Diego"},{"code":"98394","description":"MacDill AFB"},{"code":"98395","description":"Malmstrom AFB"},{"code":"98396","description":"Manchester"},{"code":"98397","description":"Manila"},{"code":"98398","description":"Maxwell AFB"},{"code":"98399","description":"Mayport NS*"},{"code":"98402","description":"McChord AFB"},{"code":"98403","description":"McConnell AFB"},{"code":"98404","description":"McGuire AFB"},{"code":"123593","description":"Miami"},{"code":"98405","description":"Miami CG"},{"code":"98406","description":"Milwaukee"},{"code":"123636","description":"Minot AFB"},{"code":"98407","description":"Miramar MCAS"},{"code":"98408","description":"Montgomery"},{"code":"123591","description":"Moody AFB"},{"code":"98409","description":"Mountain Home AFB"},{"code":"98410","description":"Muskogee"},{"code":"123647","description":"NAS Fallon / NV"},{"code":"123669","description":"NAS JRB Fort Worth"},{"code":"123618","description":"NAS JRB New Orleans"},{"code":"123671","description":"NAS Kingsville"},{"code":"123633","description":"NAS Meridian"},{"code":"123602","description":"NAVBASE Guam Barrigada / Guam"},{"code":"123572","description":"NAWS China Lake"},{"code":"123557","description":"NB San Diego"},{"code":"123658","description":"NS Newport"},{"code":"98420","description":"NSA"},{"code":"123664","description":"NSA Midsouth Memphis"},{"code":"123601","description":"NSA Souda Bay / Greece"},{"code":"123637","description":"NSY Portsmouth"},{"code":"123611","description":"Naples / ITALY"},{"code":"98412","description":"Nashville"},{"code":"123745","description":"National Capital Region (NCR)"},{"code":"123638","description":"Naval Base Ventura County"},{"code":"123646","description":"Nellis AFB, NV/Creech AFB, NV"},{"code":"98414","description":"New London NSB"},{"code":"98415","description":"New Orleans"},{"code":"98416","description":"New River MCAS"},{"code":"98417","description":"New York"},{"code":"98418","description":"Newark"},{"code":"98419","description":"Norfolk NB"},{"code":"123667","description":"North Ft. Hood"},{"code":"98422","description":"Oakland"},{"code":"98424","description":"Offutt AFB"},{"code":"123616","description":"Osan AB, Korea"},{"code":"123685","description":"Other - AGR"},{"code":"123686","description":"Other - Not on List"},{"code":"98425","description":"Patrick AFB"},{"code":"98426","description":"Patuxent River NAS"},{"code":"98427","description":"Pearl Harbor NB"},{"code":"98428","description":"Pensacola NAS"},{"code":"98429","description":"Pensacola NH"},{"code":"125211","description":"Pentagon In-Take Site"},{"code":"123579","description":"Petaluma Coast Guard"},{"code":"98430","description":"Peterson AFB"},{"code":"98431","description":"Philadelphia"},{"code":"98432","description":"Phoenix"},{"code":"98433","description":"Pittsburgh"},{"code":"98435","description":"Portland"},{"code":"98436","description":"Portsmouth NAS"},{"code":"98437","description":"Portsmouth NH"},{"code":"123576","description":"Presidio of Monterey"},{"code":"98438","description":"Providence"},{"code":"123598","description":"RAF Alconbury, UK"},{"code":"123597","description":"RAF Lakenheath, UK"},{"code":"123599","description":"RAF Menwith Hill, UK"},{"code":"123600","description":"RAF Mildenhall, UK"},{"code":"123589","description":"Ramstein AB, Germany"},{"code":"98439","description":"Randolph AFB"},{"code":"98440","description":"Redstone Arsenal"},{"code":"98441","description":"Reno"},{"code":"98442","description":"Roanoke"},{"code":"123595","description":"Robins AFB"},{"code":"123606","description":"Rock Island"},{"code":"123573","description":"Rota / SPAIN"},{"code":"98443","description":"Salt Lake City"},{"code":"98444","description":"San Diego"},{"code":"98450","description":"San Francisco"},{"code":"98451","description":"San Juan"},{"code":"98446","description":"Schofield Barracks"},{"code":"98447","description":"Schriever AFB"},{"code":"123570","description":"Schweinfurt Germany"},{"code":"98448","description":"Scotia ND(now Saratoga Springs Transition Station)"},{"code":"98449","description":"Scott AFB"},{"code":"98452","description":"Seattle"},{"code":"98454","description":"Seymour Johnson AFB"},{"code":"98455","description":"Shaw AFB"},{"code":"98456","description":"Sheppard AFB"},{"code":"123612","description":"Sigonella / ITALY"},{"code":"98457","description":"Sioux Falls"},{"code":"123587","description":"Spangdahlem AB, Germany"},{"code":"98459","description":"St. Louis"},{"code":"98460","description":"St. Paul"},{"code":"98461","description":"St. Petersburg"},{"code":"123567","description":"Stuttgart Germany"},{"code":"123673","description":"Texas City Coast Guard"},{"code":"98463","description":"Tinker AFB"},{"code":"98464","description":"Togus"},{"code":"98465","description":"Travis AFB"},{"code":"98466","description":"Tripler AMC"},{"code":"98467","description":"Tyndall AFB"},{"code":"123653","description":"USCG Air Station Ramey"},{"code":"123642","description":"USCG Atlantic City"},{"code":"123624","description":"USCG Baltimore"},{"code":"123564","description":"USCG Base Los Angeles"},{"code":"123655","description":"USCG Borinquen"},{"code":"123621","description":"USCG Boston"},{"code":"123648","description":"USCG Buffalo"},{"code":"123661","description":"USCG Charleston"},{"code":"123580","description":"USCG Clearwater"},{"code":"123650","description":"USCG Cleveland"},{"code":"123672","description":"USCG Corpus Christi"},{"code":"123626","description":"USCG Detroit"},{"code":"123628","description":"USCG Grand Haven"},{"code":"123604","description":"USCG Honolulu"},{"code":"123581","description":"USCG Humboldt Bay"},{"code":"123592","description":"USCG Jacksonville"},{"code":"123545","description":"USCG Juneau"},{"code":"123546","description":"USCG Ketchikan"},{"code":"123548","description":"USCG Kodiak"},{"code":"123649","description":"USCG Long Island"},{"code":"123684","description":"USCG Martinsburg"},{"code":"123683","description":"USCG Milwaukee"},{"code":"123551","description":"USCG Mobile"},{"code":"123619","description":"USCG New Orleans"},{"code":"123651","description":"USCG Portland"},{"code":"123681","description":"USCG Portsmouth"},{"code":"123677","description":"USCG Recruiting Command"},{"code":"123625","description":"USCG SW Harbor"},{"code":"123566","description":"USCG San Diego"},{"code":"123583","description":"USCG Savannah"},{"code":"123680","description":"USCG Seattle"},{"code":"123549","description":"USCG Sitka"},{"code":"123630","description":"USCG St Louis"},{"code":"123654","description":"USCG Station San Juan"},{"code":"123629","description":"USCG Su Ste Marie"},{"code":"123552","description":"USCG Valdez"},{"code":"125212","description":"VAMC Biloxi"},{"code":"98468","description":"Vance AFB"},{"code":"123575","description":"Vandenberg AFB"},{"code":"123609","description":"Vicenza Italy"},{"code":"123562","description":"Vilseck Germany"},{"code":"98469","description":"Waco"},{"code":"98470","description":"Walter Reed AMC - C&P"},{"code":"98471","description":"Warren AFB (Cheyenne)"},{"code":"98473","description":"West Point"},{"code":"98474","description":"Whidbey Island NAS"},{"code":"98476","description":"White River Junction"},{"code":"123645","description":"White Sands"},{"code":"98475","description":"Whiteman AFB"},{"code":"98477","description":"Whiting Field"},{"code":"98478","description":"Wichita"},{"code":"123590","description":"Wiesbaden Germany"},{"code":"98480","description":"Wilmington"},{"code":"98481","description":"Winston-Salem"},{"code":"98482","description":"Wright-Patterson AFB"},{"code":"123613","description":"Yokosuka / JAPAN"},{"code":"123614","description":"Yokota AB, Japan"},{"code":"98483","description":"Yongsan (Korea)"},{"code":"123553","description":"Yuma Proving Grounds"}]}`

**Comment by ndsprinkle** [comment]
@annaswims Awesome! And you want it sent back in the same format, {"code"=>"string", "description"=>"string"}? 

So far, I've nested `separationLocation` under `serviceInformation` in the schema. Is this an okay place for it? It's type is `object` and its two properties are `code` and `description`.

**Comment by annaswims** [comment]
Sounds good
They're asking for two strings called 
`separationLocationCode` and  `separationLocationName`, both strings

````
<xs:complexType name="serviceInformation">
        <xs:sequence>
            <xs:element name="servicePeriods" type="servicePeriod" minOccurs="1" maxOccurs="100"/>
            <xs:element name="reservesNationalGuardService" type="reservesNationalGuardService" minOccurs="0"/>
            <xs:element name="servedInCombatZone" type="xs:boolean" minOccurs="0"/>
            <xs:element name="separationLocationName" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="256"/>
                        <xs:pattern value="([a-zA-Z0-9\/\-'.#,*()&amp;][a-zA-Z0-9\/\-'.#,*()&amp; ]?)*$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="separationLocationCode" type="xs:string" minOccurs="0"/>
            <xs:element name="alternateNames" type="alternateName" minOccurs="0" maxOccurs="100"/>
            <xs:element name="confinements" type="confinement" minOccurs="0" maxOccurs="100"/>
        </xs:sequence>
    </xs:complexType>
````

**Comment by ndsprinkle** [comment]
It's weird that they need both considering the IDs are unique? Did they give any reason as to why they need the name as well? It's stranger too that there are restrictions on the length and pattern of the name string considering it is their list that provides the names, right?

**Comment by ndsprinkle** [comment]
Just to update, the format that will be submitted to the back end will be the same outlined above except `separationLocationCode` and `separationLocationName` instead of `code` and `description`.

**Comment by luke-gcio** [comment]
Merged!  Closing.
