### ISSUE TITLE
Spike: Evaluate VA-Notify Webhook

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#97973]
# Overview
As part of the ZSF work, we will need to check if emails sent via VA-notify are successful. 
This ticket is to evaluate the callback change added to the VA Notify library to see if it meets our needs and is generic enough for usage across our forms:

https://github.com/department-of-veterans-affairs/vets-api/pull/19259/files#diff-57b28fc24212f4e08ff5993292a1cdd7bd7fcdf1b2b156c8bad70ed6b20ee9de

Scenarios to support:
1. Identify instances when Action Needed emails fail in the Production Environment for the 527EZ.  Template Name: 21P-527EZ - Action Needed Template, Template ID: b68ed06d-cefe-4e2d-adb1-955e37c21d9b
2. Identify instances when Action Needed emails fail in the Production Environment for the 530EZ. Template Name: 21P-530EZ - Action Needed Template,Template ID: 71de8b72-c5e4-41f9-93d1-14fca2a9828c
3. Filter out failures that do not relate to silent failures.
4. Access failure instances starting 11/12/24 (launch date of templates) if possible.
5. Include associated metrics in[ ZSF Dashboard](https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=true&refresh_mode=sliding&from_ts=1730574102787&to_ts=1730746902787&live=true)
 
# Tasks
- [x] determine if `modules/va_notify/lib/va_notify/default_callback.rb` will meet our needs for usage.
- [ ] create tickets to perform implementation if not usable

**Comment by wayne-weibel** [comment]
VANotify::DefaultCallback evaluation:

- is not general purpose and redundant to VANotify::StatusUpdate
- makes an assumption that all notifications are related to ZSF
    - incorrect metrics will be recorded for `silent_failure*`
    - poorly handles callbacks without metadata
- is not extensible by other teams without requiring further modification to the va_notify module
- expectation that metadata contains specific keys and format
    - expects `form_number` instead of widely used `form_id`
- no documentation

Assumption - PBP will take on creating the general callback class.
VANotify::StatusUpdate expects the callback class to be globablly available, ie. autoloaded 
- a small hurdle will be determining how to use a `lib` class (not autoloaded)
- https://dsva.slack.com/archives/C010R6AUPHT/p1733419965296819

**Comment by wayne-weibel** [comment]
@mjknight50 @aplatt-coforma @matt4su @sanjabaj2 

VANotify::DefaultCallback evaluation:
- is not general purpose and redundant to VANotify::StatusUpdate
- makes an assumption that all notifications are related to ZSF
    - incorrect metrics will be recorded for `silent_failure*`
    - poorly handles callbacks without metadata
- is not extensible by other teams without requiring further modification to the va_notify module
- expectation that metadata contains specific keys and format
    - expects `form_number` instead of widely used `form_id`
- no documentation

Assumption - PBP will take on creating the general callback class.
VANotify::StatusUpdate expects the callback class to be globally available, ie. autoloaded 
- a small hurdle will be determining how to use a `lib` class (not autoloaded)
- https://dsva.slack.com/archives/C010R6AUPHT/p1733419965296819

**Comment by sanjabaj2** [comment]
Thank you @wayne-weibel for providing feedback. Has this been shared with VA-Notify teams and other benefits engineering?
