### ISSUE TITLE
Update the explainer text design on status page

### ISSUE THREAD

**Issue by ayush-chak** [department-of-veterans-affairs/va.gov-team#97985]
## Description
Per CAIA's feedback, our UX team will need to review and make a few changes to the explainer text

## Acceptance Criteria

- [ ] Add a link to location for status definitions so that users see the status definitions

- [ ] Update the explainer text to clearly redirect to BTSSS for any transaction or management of claim. 
* Explainer must use plain language
* Explainer must direct to BTSSS for opening, updating, or otherwise managing a claim

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by micahtaylor** [comment]
[Designs](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=4713-9885&t=iwUfqRU4ZIC80H8z-4)

**Comment by micahtaylor** [comment]
- [Dan's original PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30526)
- [Dan's video walkthrough](https://www.loom.com/share/7cd7d630349e4a8ca541746bcd495370?sid=460d56c3-7dca-4795-adb9-9c432435150e)

**Comment by carafrissell1** [comment]
Note: we also want to include a user survey on this page.  More info to come.
