### ISSUE TITLE
[AWS,EKS] Perform Weekly ASG Refresh on Lower environments

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#97984]
## Description
Perform an instance refresh/replacement on dev, staging, and utility ASGs for EKS clusters, weekly.

## Resources 
- As our EKS nodes grow old/stale, various parts of the system misbehave or consume resources that cause system degradation.
- This should be performed off-hours (if possible) to limit the impact on development and testing
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#max_instance_lifetime-1

## Acceptance Criteria
- [x] Once a week the dev EKS cluster ASG is refreshed
- [x] Once a week the staging EKS cluster ASG is refreshed
- [x] Once a week the utility EKS cluster ASG is refreshed

**Comment by barbarello** [comment]
completed
