### ISSUE TITLE
VRE | Send RES UTC date

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#98002]
## Issue Description
_Va.gov is sending the RES API the claim received date as a date string, but RES needs the full UTC date time instead._

Time format requested: 2024-12-02T09:00:00Z

There are two parts to this:
- The PDF
- The JSON

---

## Acceptance Criteria
- [ ] VA.gov sends the claim received date as UTC date time when sending VRE claims to RES
---

**Comment by mjknight50** [comment]
The JSON payload part was completed and merged. 
This will deploy tomorrow 12/3 at 1:00 EST.
