### ISSUE TITLE
Discovery: approach for Ph1 of sign-in widget updates

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#98000]
### User story

As a Cartography team member, I want to evaluate trade-offs and pick a direction for implementation of the new design system alerts in sign-in widgets. 

### Notes

Text to remove from widget (image): 
- ![Image](https://github.com/user-attachments/assets/ddacffb2-35da-4a4d-ae2c-b22093dd6d1e)

Possible tasks:
- 

## Acceptance criteria

- 
- QA review
- A11y review

**Comment by dcloud** [comment]
```bash
❯ rg CallToActionWidget -l src/applications/static-pages/health-care-manage-benefits

src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js
src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/UnauthContent/index.js
src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.js
src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments-page/components/UnauthContent/index.js

```

**Comment by dcloud** [comment]
It sounds like we may need to:

1. confirm the designs 
2. the availability of this `alert-sign-in` web component 
3. Confirm that its okay to update this for other non-health pages (cta-widget appears to be used in a few other places in code)

**Comment by dcloud** [comment]
There’s an [open PR to edit some code](https://github.com/department-of-veterans-affairs/vets-website/pull/33280/files) in `src/applications/sign-in-changes` to use:

 ```javascript
import { VerifyButton } from '~/platform/user/exportsFile';
```

Maybe relevant?

**Comment by dcloud** [comment]
department-of-veterans-affairs/vets-design-system-documentation/issues/3364 is an "Alert Sign-in - Development" ticket that was moved into "In progress" on 25 Nov. So it looks like the component doesn't exist (or isn't ready) yet.

**Comment by dcloud** [comment]
I got confirmation that the `VerifyButton` e.g. `import { VerifyButton } from '~/platform/user/exportsFile';` is the thing that Identity updated, but we'd need to integrate into our widgets.

**Comment by dcloud** [comment]
The DST is creating `va-alert-sign-in` to make a warning alert with a lock icon. Not really that valuable for what we need to do.

**Comment by dcloud** [comment]
Per Alexander Garcia:

> they don't exist in the component-library. They will have to be imported from platform/user/authentication/components/VerifyButton . Please note that there are no default imports and the "new" design buttons are VerifyLogingovButton and VerifyIdmeButton

`platform/user/authentication/components/VerifyButton` has `VerifyLogingovButton` and `VerifyIdmeButton`

**Comment by dcloud** [comment]
```bash
❯ rg -F 'And you must' -l
vets-website/src/applications/simple-forms/21-0972/containers/IntroductionPage.jsx
vets-website/src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js
vets-website/src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/UnauthContent/index.js
vets-website/src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/AuthContent/index.js
vets-website/src/applications/static-pages/health-care-manage-benefits/secure-messaging-page/components/UnauthContent/index.js
vets-website/src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js
vets-website/src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/UnauthContent/index.js
```

**Comment by dcloud** [comment]
It seems like we need to update the [CallToActionAlert](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx) to conditionally use the `VerifyButton`

We also want to remove some 'And you must' post-alert text

There is a newer sign-in modal (new one is blue) that should be used instead of the current one

**Comment by dcloud** [comment]
It looks like we'd need to update [ServiceProvidersText.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authentication/components/ServiceProvidersText.jsx), [SignIn.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/components/messages/SignIn.jsx), and maybe a few other global/platform spots to update the "Sign in" alerts, and these changes are likely to affect (almost?) all sign-in alerts

**Comment by dcloud** [comment]
perhaps we should do things in this order:

1. Update the sign-in alert content  in the cta-widget (per comment above). This should affect all sign-in alert widgets
2. Change the verify alert, also in the cta-widget. There are variations based on which login service you used, per [this Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=5359-436), which is what is used in the [VADS doc](https://design.va.gov/components/alert/alert-sign-in/)
3. Remove some post-alert content from pages that say "And you must" and list credentials

**Comment by dcloud** [comment]
We'd like a future ticket to refactor the cta-widget since it is unwieldy. Carlos had wanted to clean things up with his mhv-sign-in widget

**Comment by dcloud** [comment]
@nichia volunteered to tackle No. 2, the `verify` alert.

@dcloud Will do No. 3, the "And you must"

No. 1 is up for grabs at the moment.

Will create the 3 tickets for these, and leave the old tickets open for now; the appointments ticket appears to have another wrinkle about Oracle/Cerner that we want to revisit.

**Comment by dcloud** [comment]
Created 3 new tickets

**Comment by wesrowe** [comment]
Mural of sample screenshot of a widget "final screen": https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1651166973924/bc8bc44cab4e4ae7b84819d22ba89b11aa70e5e1?wid=0-1651527781306.

**Comment by wesrowe** [comment]
@dcloud @nichia, I finally on Fri afternoon had a chance to review how discovery changed the ticketing of these widgets for this sprint. Let's discuss in 16th min on Monday.

**Comment by wesrowe** [comment]
@dcloud if you can come to office hours Monday, Joelle from Identity will be there and you can pitch the refactor for her team to pursue.
