### ISSUE TITLE
[Design] Claims Status: Appeals Lane Documentation in InVision or Mural

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#9805]
## Issue Description
In order to proceed through the Claims Status tool, we need to document the appeals lane.  This is also a need for Fred Somers.

Current blocker: Having a user that has an appeal is hard to find.

## Acceptance Criteria
- [x] We have a design document that at least shows the screenshot-level flow for a user in Claims Status with appeals.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We have discovered a user with an appeal in the claim status tool - user 228. But only in dev.va.gov - the user's appeal does NOT show in staging.va.gov (not sure why). 

Here is the Invision flow of what the user sees for an appeal claim in CST:

https://vsateams.invisionapp.com/share/FXY0COTKMRD#/424622570_CST_-_Claims_Listing

@luke-gcio please let me know if you need anything else for this request. Thanks!
