### ISSUE TITLE
Geocode Course-Grained Location Query w/ Mapbox

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#98064]
![Image](https://github.com/user-attachments/assets/9dc10417-181a-4274-8c1c-ff977da3b602)

Wrap `@mapbox/mapbox-sdk`'s `forwardGeocode` (or similar) to take a search string and return a single top-matching object possessing some subset of the fields `city`, `state`, `zip_code`.

The proposed purpose of geocoding is to convert user text input into structured and normalized location data that we can pass along to our POA request search query.

We should use the unit tests from this task's acceptance criteria to give us a sense of the behavior we expect to see for some representative sampling of inputs. The observed behavior will inform the degree of complexity that the UI needs to accomodate: is single top-match almost always the right thing?

### Acceptance criteria
- [ ] Write a unit test with a representative sampling of inputs and outputs (I think the unit test could be backed by real API interactions that are saved into the codebase!)

### Resources
- [Figma mockup](https://www.figma.com/design/LVCQBuW7a6nfVFNyhA4kv4/ARF---Form-21-22-Design-Explorations?node-id=1958-130397&t=9ktJTcwoKfmHBpkl-1)
- [Example integration](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20geocodeUserAddress&type=code) of Mapbox client's forward geocoding
  - This example comes from our sister "find a representative" application

**Comment by nihil2501** [comment]
Being worked on by Patrick.

**Comment by nihil2501** [comment]
@department-of-veterans-affairs/benefits-accredited-rep-facing-engineers I would appreciate any input on this statement of purpose for this task (copying from this ticket's description):
> The proposed purpose of geocoding is to convert user text input into structured and normalized location data that we can pass along to our POA request search query.
> We should use the unit tests from this task's acceptance criteria to give us a sense of the behavior we expect to see for some representative sampling of inputs. The observed behavior will inform the degree of complexity that the UI needs to accomodate: is single top-match almost always the right thing?

**Comment by chumpy** [comment]
@nihil2501 feels like we'll want some sort of feedback to the user on what we grab to help them see where they are actually searching

**Comment by nihil2501** [comment]
> [@nihil2501](https://github.com/nihil2501) feels like we'll want some sort of feedback to the user on what we grab to help them see where they are actually searching

So far I've taken inspiration on the UX of ARM's find a rep product which only gives them that feedback along with the results:
![Image](https://github.com/user-attachments/assets/9f863c43-4768-43b9-89c4-e4a781b04b11)

I think this question that this task can help validate "is single top-match almost always the right thing?" will determine whether submitting the geocoding result without extra preliminary interaction is viable.

**Comment by chumpy** [comment]
@nihil2501 seems reasonable for the pilot. It can definitely be on the list of a feature we look at specifically during the pilot for how much pain it causes.

**Comment by jquispe-oddball** [comment]
@nihil2501 a question that came up today in one of my 1-1s - are we returning only a specific request, like pending only? All request types? will we display them in one list, or keep them in their respective tabs?

**Comment by nihil2501** [comment]
> [@nihil2501](https://github.com/nihil2501) seems reasonable for the pilot. It can definitely be on the list of a feature we look at specifically during the pilot for how much pain it causes.

Great idea @chumpy

**Comment by nihil2501** [comment]
> [@nihil2501](https://github.com/nihil2501) a question that came up today in one of my 1-1s - are we returning only a specific request, like pending only? All request types? will we display them in one list, or keep them in their respective tabs?

@jquispe-oddball My understanding is that a location search wouldn't blow away the context of the tab they are on (pending vs completed). They can change the location part of the query and the status part of the query independently from one another without nulling out the other. Particularly if the search result comes with a summary of what query the results represnt:
> Showing 10 results for location=x,y,z status=pending

Does that make sense?
