### ISSUE TITLE
Add OMB Content to PCI & OH Travel

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98076]
## Description
We have been asked to add some OMB content to our applications.

## Wireframes Tickets
[Create Wireframes for PCI](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97419)
[Create Wireframes for OH Travel](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97420)

## Tasks
- Add the new content, per the wireframe, to Check-in
- Add the new content, per the wireframe, to Pre-Check-in
- Add the new content, per the wireframe, to OH Travel

**Comment by juancstlm-a6** [comment]
@zach-park or @cgednalske Mind reviewing the screenshots for the OMB info in the PR here https://github.com/department-of-veterans-affairs/vets-website/pull/33514

**Comment by cgednalske** [comment]
I put a comment in the PR - I hope that was ok/allowed 😅 

Here it is again:

> @juancstlm-a6 I noticed we're using Estimated burden in our designs (based on what the Travel team is using), but Respondent burden here, which is what is in the design system. I'm checking with some folks on why we have Estimated burden in our designs and if we need to go with that or not - tagged you as well.
> 
> Everything else looks good!
