### ISSUE TITLE
ZSF Pension | ENG: update confirmation page for ZSF stage 2

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#98092]
We will update the confirmation page with a few MVP changes to meet the requirements of ZSF stage 2 that will add an alert and what to expect next text. 

Design files here: https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=9392-54150&t=tzz3rkWvFXU5kWKn-4

Notes from design: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94580#issuecomment-2518787126

Tasks:
- [ ] Implement all changes on the Pension confirmation page 
- [ ] Changes are kept behind a feature flipper
- [ ] Changes are design reviewed
- [ ] Changes are tested
- [ ] Changes are presented to Collab Cycle staging review for approval

Acceptance Criteria:
- [ ] Changes are completed, design reviewed, tested and approved by collab cycle and ready for PROD (but NOT enabled)

NOTE: once approved by stakeholders, we need to HOLD from enabling on production due to the text referencing emails about submission and received email that will be done in Stage 3.

**Comment by ToddWebDev** [comment]
This ticket can be used as a reference for implementation - https://github.com/department-of-veterans-affairs/va.gov-team/issues/95590

**Comment by aplatt-coforma** [comment]
Note: There are some minor text changes that need to be made on this confirmation page tracked in [#99181](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99181). Let's wait to review these changes until that ticket is complete. Currently planned for sprint 10.

cc @matt4su @ToddWebDev @TaiWilkin
