### ISSUE TITLE
SOCKS access for Matthew Guest

### ISSUE THREAD

**Issue by matt-guest-wilcore** [department-of-veterans-affairs/va.gov-team#98117]
### Your Name

Matthew Guest

### Your Email

matt.guest@wilcore.io

### Your GitHub Handle

matt-guest-wilcore

### Your Role and Team

VA MFS

### Product Manager (PM) name and email

Em Allan - emily@oddball.io

### Product Owner (PO) name and email

Jeff Barnes - jeffrey.barnes4@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKoJh8G4cp6zQfamRKWDy9+eCk6iXAAJLYjZjkfz5ljs matthewguest-wilcore@Matthews-MacBook-Pro.local

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/58faceae-50d5-4f3d-90e9-843e33e13074)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by Efe-Oddball** [comment]
@matt-guest-wilcore  Access granted ✅

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
