### ISSUE TITLE
Sign-in widget: Update the sign-in alert content

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#98143]
## Description

The sign-in alert that appears on unauthenticated/Drupal pages needs to reflect that Login\.gov and IDme are the two supported login providers, and that identity verification is required

![Image](https://github.com/user-attachments/assets/247594fa-ff9e-4cbd-869f-6dc0126f5c78)

### User story

As a Veteran, I want to know which sign-in providers I can use to log in to VA.gov now and in the future.

### Notes
- *We don't need to match the alert icon and color with this PR*. In the future, an `alert-signin` component will have the blue alert with the lock.
- Content is in multiple places, e.g.:
  - [src/applications/static-pages/cta-widget/components/messages/SignIn.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/components/messages/SignIn.jsx)
  - [src/platform/user/authentication/components/ServiceProvidersText.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authentication/components/ServiceProvidersText.jsx)
- Changes will affect all pages that (indirectly) use the `cta-widget` or directly use `ServiceProvidersText.jsx`
- Content is in [this Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=5359-436)
- Discovery notes: department-of-veterans-affairs/va.gov-team/issues/98000

URLs of widget pages:
  - [Appts](https://staging.va.gov/health-care/schedule-view-va-appointments)
  - [Medications](https://staging.va.gov/health-care/refill-track-prescriptions)
  - [Messages](https://staging.va.gov/health-care/secure-messaging/)
  - [View lab & test results](https://staging.va.gov/health-care/view-test-and-lab-results) 
  - [Get medical records](https://staging.va.gov/health-care/get-medical-records/)

Possible tasks:
- 

## Acceptance criteria

- Sign-in component of CTA widget (affecting all 5 instances above) is updated with the latest content from VADS
- QA review
- A11y review

**Comment by kjsuarez** [comment]
[Relevant PR](https://github.com/department-of-veterans-affairs/component-library/pull/1424)

**Comment by dcloud** [comment]
Will merge the PR on Monday 16 Dec, before noon in order to [deploy on Monday](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments)

**Comment by mcarterA6** [comment]
Moving this ticket to sprint 47.

**Comment by wesrowe** [comment]
@mcarterA6, I'm pretty sure this is in prod. PR is merged, Ni demoed it. I'm not sure why @allanto-ah's QA notes aren't here, maybe it was covered elsewhere?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the sign in widgets have been put into the proper app pages. Currently there is a "i" icon instead of the lock icon. The "i" icon will be replaced with a lock icon once the actual VADS component is implemented

Example screenshot
<img width="1309" alt="Image" src="https://github.com/user-attachments/assets/35b5e2cb-1940-4c10-94a4-4127af1d9e9d" />
