### ISSUE TITLE
QA Standards - Public Websites - Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#98146]
#### VFS team name
Public Websites

#### VFS product name
Discharge Upgrade Wizard
#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 👉🏽Regression Test Plan in Sharepoint [here](https://dvagov.sharepoint.com/:x:/s/SitewidePublicWebsites/EaqLbCh8zzxHszmtMem6hjoBXW7quKAoKUDevCOuQaadjA?email=Ian.Harrison%40va.gov&e=xw8y6x)
- [x] Standard has been met (Slack [convo](https://dsva.slack.com/archives/C52CL1PKQ/p1733947078425669?thread_ts=1733944497.530999&cid=C52CL1PKQ))
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Since this is an upgrade to the existing tool, there should be a Regression Test Plan.

#### Test Plan 👉🏽 Test Plan in Sharepoint [here](https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/PW%20products/Discharge%20Upgrade%20Wizard/QA/Discharge%20Upgrade%20Wizard.docx?d=w1a180858197d4e99950d773da385e627&csf=1&web=1&e=cfTISv)
- [x] Standard has been met (Slack [convo](https://dsva.slack.com/archives/C52CL1PKQ/p1734036284858119?thread_ts=1733944497.530999&cid=C52CL1PKQ))
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
The QA documents states that: "The team manually tested all flows and branching logic with each complete user story. We tested edit question flows on the review page along with navigation when editing a question." But the specific tests performed are  not  further documented, in particular the results of the tests are not included.

#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage 👉🏽 Per Ian in a comment below, this now passes
- Lines %: 70.29
  - Updated: 82.27

- Functions %: 71.37
  - 86.07
- Statements %: 70.38
  - 82.64
- Branches %: 46.22
  - 62.71

- [x] Standard has been met - Approved by Ian
- [ ] Standard has not been met
#### Endpoint Monitoring (Completed Playbook)
- [x] Standard has been met
- [ ] Standard has not been met
#### Logging Silent Failures N/A - approved by Ian
- [ ] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No logging silent failures artifact provided
---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by chriskim2311** [comment]
@it-harrison Thanks for the review! Couple questions:

For the zero silent failures, there is no api or backend communication for this application. It is purely a react app and have error handling for all questions. Users will not come to a step in the flow where there will be a silent failure. Not sure what we would need to provide for that requirement.

Also for the unit test coverage is there a command we can run locally to give us the current percent coverage? As we stated in the QA Artifact we have both v1 and v2 code in the folder and that v1 is missing some of the tests. I can work on those to get it above 80% and passing but wanted to check if we can get the total coverage locally.

**Comment by it-harrison** [comment]
> [@it-harrison](https://github.com/it-harrison) Thanks for the review! Couple questions:
> 
> For the zero silent failures, there is no api or backend communication for this application. It is purely a react app and have error handling for all questions. Users will not come to a step in the flow where there will be a silent failure. Not sure what we would need to provide for that requirement.
> 
> Also for the unit test coverage is there a command we can run locally to give us the current percent coverage? As we stated in the QA Artifact we have both v1 and v2 code in the folder and that v1 is missing some of the tests. I can work on those to get it above 80% and passing but wanted to check if we can get the total coverage locally.

@chriskim2311 - that's perfectly fine for the logging silent failures artifact, it doesn't apply in your case. as for coverage, we evaluate at the app level, and the app level is normally defined by the level of the  `manifest.json` file, which in your case means running `yarn test:coverage-app discharge-wizard`. If there is code that you plan to remove once this update goes live (but which is in production now) you can remove it locally before running the coverage report if that helps and use those numbers

**Comment by chriskim2311** [comment]
@it-harrison Thank you for the quick response. I will work on that and send you the local screenshot today or tomorrow.

**Comment by chriskim2311** [comment]
@it-harrison Here is the updated testing coverage after removing the v1 code. 

![Image](https://github.com/user-attachments/assets/4b328b0a-cec5-4745-9f11-6a2c27fddbb0)


There are some limitations with DST web components and the shadow DOM that make it difficult to test all the Branches in the coverage doc. We have extensive cypress tests that test the code base as well. Does this new testing report provide enough coverage for the v2 implementation?

**Comment by it-harrison** [comment]
@chriskim2311 - that looks good since your sub-threshold branches coverage is due to shadow DOM testing limitations. Thanks for the heads up.

**Comment by FranECross** [comment]
@it-harrison Here is the[ Regression Test Plan ](https://dvagov.sharepoint.com/:x:/s/SitewidePublicWebsites/EaqLbCh8zzxHszmtMem6hjoBXW7quKAoKUDevCOuQaadjA?email=Ian.Harrison%40va.gov&e=xw8y6x)for DUW. I've shared with you and am happy to share with anyone else that needs access. Thanks!  cc @chriskim2311 @jilladams

**Comment by FranECross** [comment]
Standards have been met for Unit Test Coverage, QA Regression Test Plan, and QA Test Plan and signed off by Ian. Closing ticket.
