### ISSUE TITLE
Sign-in widget: Remove some post-alert content from pages that say "And you must" and list credentials

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#98147]
## Description

Remove the "And you must" content outlined in red below:

![Image](https://github.com/user-attachments/assets/ddacffb2-35da-4a4d-ae2c-b22093dd6d1e)

### User story

As a Veteran, I don't want to see outdated instructions about auth/credential providers that won't make sense in 2025

### Notes
- Discovery notes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98000
- This text may only appear in health-care benefits widgets, as discovered via `rg -F 'And you must' -l`

Possible tasks:
- Remove that text

## Acceptance criteria

- 
- QA review
- A11y review

**Comment by mcarterA6** [comment]
Moving this ticket to sprint 47.

**Comment by wesrowe** [comment]
Same comment. @allanto-ah , this is in prod, can it close?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the above content has been removed from the various pages
