### ISSUE TITLE
Sign-in widget: Change the verify alert to use service-specific buttons and messaging

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#98144]
### User story

As a Veteran who signed in with an unverified credential, I want to see an identity verification alert that is relevant to the CSP I signed in with, so that I can easily complete the verification process.

### Notes
- Discovery notes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98000
- Content/visuals are in [this Figma](https://www.figma.com/design/JDFpGLIojfuQwANXScQjqe/VADS-Component-Examples?node-id=5359-436) (see the alerts with "Verify" in them)
- `platform/user/authentication/components/VerifyButton` has a `VerifyButton`, a `VerifyLogingovButton` and a `VerifyIdmeButton`. Identity team created these button components
- The existing call to action appears to be controlled by [src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx), and the work is likely to require edits to that component
- The `cta-widget` (`src/applications/static-pages/cta-widget`) is used by all of the `src/applications/static-pages/health-care-manage-benefits

URLs of widget pages:
  - [Appts](https://staging.va.gov/health-care/schedule-view-va-appointments)
  - [Medications](https://staging.va.gov/health-care/refill-track-prescriptions)
  - [Messages](https://staging.va.gov/health-care/secure-messaging/)
  - [View lab & test results](https://staging.va.gov/health-care/view-test-and-lab-results) 
  - [Get medical records](https://staging.va.gov/health-care/get-medical-records/)

Possible tasks:
- 

## Acceptance criteria

- "Verify" alerts for all 3 CSPs are updated to latest content and button from the VADS page, and shows in all 5 unauthenticated pages where sign-in widgets appear
  - [ ] Login.gov
  - [ ] ID.me
  - [ ] MHV Basic (no button; it says to use another CSP)
- QA review
- A11y review

**Comment by wesrowe** [comment]
Discussion in office hours clarified for me exactly how the implementation of these will work. It's my impression that this single ticket covers all "verify" alerts. So I'm updating the ACs to cover all 3 CSPs we need to update for. @nichia, this could use points.

// cc @mcarterA6 @dcloud @kjsuarez

**Comment by wesrowe** [comment]
@nichia, I saw your [slack discussion with Alex G](https://dsva.slack.com/archives/C068QM7CCKG/p1734374621523059?thread_ts=1733332973.315609&cid=C068QM7CCKG) about the buttons. Can you please update comments here?

**Comment by mcarterA6** [comment]
Moving this ticket to sprint 47.

**Comment by wesrowe** [comment]
it looks like the PR is closed, @mcarterA6?

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the verify alerts have been changed to the above URLs for the different apps. Example below:

<img width="1309" alt="Image" src="https://github.com/user-attachments/assets/b6c947ac-4326-4008-b1bd-0ef893a6a3a8" />
