### ISSUE TITLE
SOCKS access for Timothy Steele

### ISSUE THREAD

**Issue by timothy-steele-va** [department-of-veterans-affairs/va.gov-team#98153]
### Your Name

Timothy Steele

### Your Email

timothy.steele@blueguardianit.com

### Your GitHub Handle

timothy-steele-va

### Your Role and Team

Automated Tester on VA.gov Medical Records team

### Product Manager (PM) name and email

Lichelle Bain - lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJKQr0C96CTDFMjOSBbG+cff97XWQUR0xhtokq9XYXuX timsteele@Timothys-MacBook-Pro.local

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

I have been here for two years, and I'm just now completing this form. I do not have a copy of my E-QIP confirmation, but I do have a screenshot of my E-QIP archival copy cover sheet. Will this be sufficient? 
![Image](https://github.com/user-attachments/assets/4d835fd3-644c-4469-89cb-818afa37d275)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [ ] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by timothy-steele-va** [comment]
![Image](https://github.com/user-attachments/assets/82810275-b064-4b8e-82ce-e8d4ca8af1a5)
I apologize for the incorrect screenshot attached above.
Here is the screenshot I meant to attach.

**Comment by Efe-Oddball** [comment]
@timothy-steele-va Will you be able to provide your PIV card under this ticket on the _vfs-platform-support_ channel? The original request was the **transmittal notice** email but an image of your PIV should be ok.

**Comment by timothy-steele-va** [comment]
@Efe-Oddball For some reason I'm not seeing this ticket in the _vfs-platform-support_ channel. Are you able to see it? 
Should I create a new ticket in that channel and attach an image of my PIV card there?

**Comment by timothy-steele-va** [comment]
![Image](https://github.com/user-attachments/assets/b878e97c-6f23-454e-9f5b-18bf555fe43d)

**Comment by Efe-Oddball** [comment]
@timothy-steele-va has reached out to me with his PIV card. Will go ahead and approve

**Comment by Efe-Oddball** [comment]
@timothy-steele-va  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
