### ISSUE TITLE
Staging Review finding: Fix the feedback button width

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98156]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

This ticket was part of a merged Staging Review with MHV Medications [List Filter](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88958) and [Prescription Information](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88952)

## Product Information
**Team:** MHV Medications
**Product:** Medications
**Feature:** List Filter & Prescription Information

## Findings details
**VA.gov Experience Standard - issue:** [User encounters design components or patterns that are inconsistent or confusing.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

The feedback button at the bottom of the page is full width.  Looking in production, the width should be 93px.

<details><summary>Link, screenshot or steps to recreate</summary>

![Screen shot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/88952-Allison.png?raw=true)

</details>

## Recommended action

Change the width of the feedback button to match what is in productions

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Button ](https://design.va.gov/components/button)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by TannerBird98** [comment]
This is work is complete. Here is the jira ticket for awareness: https://jira.devops.va.gov/browse/MHV-63966
