### ISSUE TITLE
Staging Review finding: Confusing hierarchy with "About medications" page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98159]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

This ticket was part of a merged Staging Review with MHV Medications [List Filter](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88958) and [Prescription Information](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88952)

## Product Information
**Team:** MHV Medications
**Product:** Medications
**Feature:** List Filter & Prescription Information

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The medications list can be found by navigating to "About medications", then to the medications list link. If users use the "Medications" icon link in the secondary icon-driven MHV nav, they will return to the "about medications" page rather than the medications list. This is confusing and causes extra clicks and time for pages to load.

I flagged this in a previous review as well. I understand this is a temporary workaround, *and* as the features in the medications section increase, this workaround becomes more unwieldy and confusing, and it becomes time-expensive for users.

<details><summary>Link, screenshot or steps to recreate</summary>

![Image](https://github.com/user-attachments/assets/5e0386fe-17bd-46f6-b45f-2d333cb7f21f)

![Image](https://github.com/user-attachments/assets/92093162-00f7-4b6f-bfc9-d1c0a4f559e3)

</details>

## Recommended action

The primary `medications` link in the icon nav, and in the breadcrumbs, should be the medications list. `About medications` should be a child page of the medications page.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Breadcrumbs ](https://design.va.gov/components/breadcrumbs)
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** Navigation

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [x] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by TannerBird98** [comment]
We have decided not to fix this since we are getting rid of the about page in the next few months.
