### ISSUE TITLE
Staging Review finding: Consider reversing order of clauses for "Active: Non-VA" card

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98160]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

This ticket was part of a merged Staging Review with MHV Medications [List Filter](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88958) and [Prescription Information](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88952)

## Product Information
**Team:** MHV Medications
**Product:** Medications
**Feature:** List Filter & Prescription Information

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not meet best practices.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-meets-best-practices)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

The "Active: Non-VA" card currently reads "This isn’t a prescription that you filled through a VA pharmacy. You can’t manage this medication in this online tool." 

## Recommended action

I recommend flipping the order of these clauses for clarity, so we lead with the most important information, then explain why that's true. 

## Screenshot

![Image](https://github.com/user-attachments/assets/5685f0f7-f156-470e-8aeb-663229e17333)

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Content principles](https://design.va.gov/content-style-guide/content-principles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by TannerBird98** [comment]
This ticket was done with another ticket that had some other content changes in it as well. Closing this ticket.
