### ISSUE TITLE
[Development] HLR: Update vets-api HLR endpoint

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#9817]
## Issue Description
The [swagger docs for our HLR endpoint](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/higher_level_reviews/createHigherLevelReview) were written to closely match what we eventually submit to [lighthouse's HLR endpoint](https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current). Lighthouse's HLR endpoint has changed in over time. We should consider updating our own swagger docs so the FE submits data to the BE that requires little transformation before being sent on to lighthouse.

## Acceptance Criteria
- [ ] Swagger/documentation is correct and we are lined up with LightHouse
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
this ticket was completed a few weeks ago, but since then more changes have been made.  
new issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/11094 😿
