### ISSUE TITLE
Review VAOS content for other VA websites/access points 

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9818]
As part of the redirect efforts from legacy VAOS tool to new VAOSR on VA.gov, we want to make sure that the supporting content/copy on these pages reflect the latest for the VAOSR app. 

All of the pages below will be redirected to this VAOSR url: https://www.va.gov/health-care/schedule-view-va-appointments/

## Goals:
- Provide recommendation for content and copy updates on other VA web pages that better reflect/support new VAOSR on VA.gov

## Review tasks for VAOS content on non-VA.gov pages:
- [x] Review [VA Mobile VAOS page](https://mobile.va.gov/app/va-online-scheduling) and provide recommendations _(this is also being reviewed by OCC/Kay, will intro you to her)_
- [x] Review [Launchpad app](https://mobile.va.gov/app/va-launchpad-veterans) (you will need to download app on to any iOS or Android device) and provide recommendations (I would assume this information should mimic the recommendation for the VA Mobile page)
- [x] Review [eBenefits](https://www.ebenefits.va.gov/ebenefits/homepage) - verify no changes needed for VAOS other than redirect 
- [x] Review [MHV "Schedule/Cancel" ](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/schedule-or-cancel-a-va-appointment-online)page and provide recommendations for content updates/consistency for new VAOSR
- [x] Review [MHV "Keeping up with your VA Appointments"](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/keeping-up-with-your-va-appointments) page and provide recommendations for content updates/consistency for new VAOSR

## Acceptance Criteria:
- [ ] Recommendations for what does/does not need updating for these pages for the VAOSR redirects

### For reference, this is the unauth/non-MHV redirect matrix:
![Screen Shot 2020-06-03 at 5.26.01 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/3107a3bb-5464-4866-900e-780aa6e02eb4)

**Comment by peggygannon** [comment]
@lenaecb @lalexanderson-dsva Just want to provide an update on where we are with this: 

Mobile apps content recommendations (might also apply to Launchpad)
--Send to Kay 6/15

MHV VAOS content
--Send to Danielle for her review 6/16. 

We can discuss more at our sync tomorrow. thx!

**Comment by peggygannon** [comment]
**6/30/2020 update**

MHV recommendations 
--sent to Ngozi on 6/30/2020
