### ISSUE TITLE
Staging Review finding: Errant semicolon in "IF [Board] == DRB, SHOW:" 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98242]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Public Websites
**Product:** Discharge Upgrade Wizard
**Feature:** 

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content with errors or inconsistencies.](https://design.va.gov/about/experience-standards/#user-encounters-accurate-consistent-content)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

This copy contains the sentence "The deadline to apply to the DRB is 15 years after your date of discharge; after this time period, you must apply to a different board." The semicolon in this sentence is unnecessary. 

<details><summary>Link, screenshot or steps to recreate</summary>

![Image](https://github.com/user-attachments/assets/fe103173-13c1-4243-ae4c-ee8b9be205a8)

</details>

## Recommended action

I would just replace the semicolon with a period; this also matches plain language standards better.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Plain language - Use short sentences](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by FranECross** [comment]
The text in the actual Wizard is correct (no semicolon). Closing.

The Discharge Review Board (DRB) previously rejected your application because you did not apply to the DRB first. For applications like yours, the DRB can review only cases that have already been rejected by the DRB. The DRB is a panel of commissioned officers, or a mix of senior non-commissioned officers (NCOs) and officers. The deadline to apply to the DRB is 15 years after your date of discharge. After this time period, you must apply to a different board.

![Image](https://github.com/user-attachments/assets/845f4bf0-bc30-4fe7-ba4b-d80041f17e5c)
