### ISSUE TITLE
Modify react_routes to support URLs with query params

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#9824]
## Issue Description

Original issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8396

Some context: [This PR](https://github.com/department-of-veterans-affairs/devops/pull/7033) attempted to implement the following redirect unsuccessfully due to the query param `formno=21-0958`:

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.va.gov/vaforms/form_detail.asp?formno=21-0958 | https://www.va.gov/decision-reviews/legacy-appeals/

This is the first of many redirects for vaforms, most of which will need support for query params.

---
## Tasks
- [ ] Modify template logic to support `src`s with query params in https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml

## Acceptance Criteria
- [ ] https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml supports `src` URLs with query params.

**Comment by kelsonic** [comment]
Devops ticket created to modify template logic to support `src` URLs with query params CC @stephorkandatx

**Comment by johnhashva** [comment]
@kelsonic Is there someone I can reach out to see if we can get help prioritizing this with the right team?  Happy to give it a try.

**Comment by kelsonic** [comment]
Thanks @johnhashva! I believe Taylor is giving it a go 🙂
