### ISSUE TITLE
Documentation Cleanup and Organization for Benefits & Memorials Engineering Resources

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#98265]
### Description
Our current engineering documentation in `/teams/vsa/teams/benefits-memorials-2/engineering/` needs cleanup and organization to improve maintainability and accessibility for team members.

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/benefits-memorials-2/engineering/back-end/onboarding

https://github.blog/news-insights/product-news/moving-and-renaming-files-on-github/

### Current Issues:

1. Documentation is scattered across multiple files
2. Some documentation may be outdated
3. No clear structure for finding specific information
4. Possible redundant information with other VA documentation

### Proposed Changes:

Create clear directory structure:

- /setup - Development environment setup
- /workflows - Common engineering processes
- /best-practices - Coding standards and patterns
- /troubleshooting - Common issues and solutions

### Review and update:

- Remove outdated information
- Update links to current VA resources
- Add missing documentation for recent changes
- Cross-reference with main VA documentation to avoid duplication

### Add standardized README with:

- Quick start guide
- Directory structure explanation
- Links to key resources
- Contribution guidelines

### Acceptance Criteria:

- [ ]  Directory structure reorganized
- [ ]  All documentation reviewed and updated
- [ ]  Outdated content removed or updated
- [ ]  New README created with navigation structure
- [ ]  Links verified and working
- [ ]  Team review completed

**Comment by amponce** [comment]
Took a stab at organizing the directories and files 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end

Here is the new structure:
```
/front-end
  ├─ README.md              # High-level structure of the front-end codebase and docs index
  ├─ getting-started/       # Basics for new developers to ramp up
  │   ├─ local-setup.md     # Steps to set up local environment
  │   └─ howto-local-gmt-db-update.md  # Guide on local GMT DB updates
  │
  ├─ architecture/               # System design, data structures, and architecture-level docs
  │   ├─ cdp-data-structure.md
  │   ├─ fsr-data-structure.md
  │   ├─ transaction-code-mappings.md
  │   └─ honey-dew.md             
  │
  ├─ features/                   # Documentation focused on specific features or modules
  │   ├─ dev-digital-dispute-notes.md
  │   ├─ debt-diary-codes-error-handling.md
  │   └─ GMT yearly update.md
  │
  ├─ tools-and-hooks/            # Developer utilities, hooks, and other reusable components
  │   ├─ crawlers/
  │   │   └─ aria-crawler.md
  │   │   └─ element-crawler.md
  │   │   └─ event-crawler.md
  │   │   └─ set-form-data.md
  │   └─ fsr/
  │   │   └─ hooks/
  │   |   |  └─ useDetectFieldChanges.md
  │
  ├─ guides-and-howtos/          # How-to guides, best practices, and procedural docs
  │   ├─ noteable-changes.md
  │   ├─ the-wrong-way.md        # Might consider renaming to something more descriptive
  │   ├─ andrews-perfect-world.md
  │
  ├─ reference/                  # Reference materials, CSVs, or mapping files not directly architectural
  │   └─fsr-urls-and-pages.csv
  │
  └─ changelogs/                 # Keep track of changes over time, if needed
      └─ Readme.md (If you have version-based docs, put them here)
```

**Comment by mgleo** [comment]
Adding link to Repo guidelines on GH: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/repo-guidelines.md
