### ISSUE TITLE
Flipper UI access for Jennica Stiehl

### ISSUE THREAD

**Issue by stiehlrod** [department-of-veterans-affairs/va.gov-team#98264]
### Your Name

Jennica Stiehl

### Your GitHub handle (Flipper UI access is managed through GitHub)

@stiehlrod

### Team, Role, and Company of the target individual

Dash, Software Eng II, Oddball.io

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

In case we need to enable/disable a flipper feature in production, and the person/s who have access are out of office.

**Comment by stiehlrod** [comment]
Unable to add a label. Out team label is `claims-api`

**Comment by bdech** [comment]
confirmed in Atlas
E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97036)
