### ISSUE TITLE
[0781 PS] (3) Refactor early Screener Page work into form0781 directories

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#98273]
## HARD BLOCKED
We need to finish the boiler plate work before we can do this, as this work uses the folder structure created therin.
- #97063 
- [97062](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97062)

## Description
Some work got done on this epic before we had time to plan it and get the boilerplate out. Now we just need to go back and update Scott's screener page work to match the new directory structure and use shared code where available.

### Acceptance Criteria
- All code in [the mentalHealth directory](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/all-claims/pages/mentalHealth) or other files Scott may have created in [this ticket](TODO) need to be moved into the correct locations based on the naming conventions laid out in the FE boiler plate work (<parent dir>/form0781)
- Any shared functionality made available in the Flipper / Boilerplate work that duplicates Scott's work should be used, e.g. the `showForm0781Pages` flipper function can be used instead of the [showMentalHealthPages](https://github.com/department-of-veterans-affairs/vets-website/blob/e3a6949374f572ee848ca28499ad1a615d696b57/src/applications/disability-benefits/all-claims/content/mentalHealth.jsx#L95)
- Refactor the [mental health screener page](https://github.com/department-of-veterans-affairs/vets-website/blob/e3a6949374f572ee848ca28499ad1a615d696b57/src/applications/disability-benefits/all-claims/config/form.js#L548) to be nested within the new `showForm0781Pages` config

**Comment by SamStuckey** [comment]
CLOSING: we realized after review that we actually will need the existing Screener Page work to remain separate, even though it will share a flipper with the 0781 flow. This is because the new 0781 flow has been moved into the new 'Additional Forms' chapter

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
