### ISSUE TITLE
CF: No space for (Learn more) for "Warnings and school closings(Learn more)"

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9829]
Spacing on mobile doesn't exist on the search results page for "Warnings and school closings(Learn more)". This was discovered on review of https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9029.

![Screen Shot 2020-06-04 at 10.24.55 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/17c47277-80d5-41e6-bc52-0ec9dff3410a)

Observe on both non-vettec and vettec search results
https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=College+of+charleston
https://staging.va.gov/gi-bill-comparison-tool/program-search

**Comment by hughes-dustin** [comment]
Branch: bah-9829
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12955

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-05 at 1.48.00 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/151bee80-d6a0-4061-9511-80b953fa9679)
##
![Screen Shot 2020-06-05 at 1.48.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cd52532e-9ea3-47a8-85b2-770de71fd47e)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
@sonntag-adam Looks good from UX perspective!

**Comment by sonntag-adam** [comment]
Closing out bug.
