### ISSUE TITLE
Design: FMP Claims UXR findings from CHAMPVA claims

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#98297]
The current FMP findings report is formatted as research report but we didn’t do exclusive research for FMP so we don't want it to seem like a full research report. 

- [x] Reformat the FMP findings report as a key takeaways document that can link people back to the original CHAMPVA research and research report. 
- [x] Review the new document format with Lois
- [x] Pull out finding/recommendations and determine what tickets need to be created and any gaps that we may need to think about. Prepare to present in the Monday design/product sync

**Comment by rspope** [comment]
Created two version of this. Will review internally before presenting to Lois.

**Comment by rspope** [comment]
This was reviewed on 12/9 and approved as-is. Closing the ticket now.
