### ISSUE TITLE
Investigate validation behavior when no profile name exists for comparison

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#98291]
As a product team member,
I want to understand what happens when a Veteran enters their name but there's no profile name to validate against,
So that we can ensure Veterans aren't blocked from certification if their profile name is null.

### Background:
During Claim Certification, Veterans must enter their name which validates against their stored profile name. We need to investigate the specific scenario where a Veteran enters their name but there is no profile name (null value) to validate against.

Key Questions to Answer:
1. Does this scenario occur in production - are there Veterans with null profile names?
2. What happens in our validation logic when trying to validate against a null profile name?

Potential Investigation Methods:
- Query database to check for null profile names in production
- Test validation behavior in staging by setting up test accounts with null profile names
- Review validation code to understand null value handling

### Tasks

- [ ] Check if other teams / Platform have run into this

### Acceptance Criteria:
- Determine if null profile names exist in production and if so, how common they are
- Document how our validation handles null profile name values
- Identify any error handling improvements needed
- Recommend solutions if issues are found

**Comment by sethdarragile6** [comment]
Submission 3061259 is a case where just the first name is missing ([thread](https://dsva.slack.com/archives/C055573C508/p1732300996068799?thread_ts=1728483968.481609&cid=C055573C508))

**Comment by christinec-fftc** [comment]
My notes from yesterday

1. where is name coming from?
first network call i see on staging with name is in the api call to `https://staging-api.va.gov/v0/user`.

2. found some documentation [docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/use-cases/system-cant-display-disability-rating-or-legal-name.md) and va.gov profile [mocks](https://www.figma.com/design/qfyUmEOVawplgrEKYKFp0f/Profile---Personal-information?node-id=0-41&node-type=frame&t=6r6ZG4yjbgXPV2ki-0) regarding error handling for names. looks like there is already cases for handling failures getting name. would seem appropriate for to have some error handling on the 526 side

3. documentation on how a Veteran can change their name. it is not something they can do themselves and requires a letter and identification
https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/

**Comment by sethdarragile6** [comment]
Here is a summary of our investigations (w/ @christinec-fftc ):

- **Determine if null profile names exist in production and if so, how common they are**

     A script was written to help spot-checking various historical records. Aside from the known missing first name case (submission 3061259 - see [thread](https://dsva.slack.com/archives/C055573C508/p1732300996068799?thread_ts=1728483968.481609&cid=C055573C508)), no other fully or partially empty names were found. 

- **Document how our validation handles null profile name values**

     It doesn't! Empty or partially empty named users can login, fill out the form, and ultimately hit submit from the front end (which currently errors down in the backup submission path). We also verified that, even with the new claims certification feature, they were still able to submit.

- **Identify any error handling improvements needed**

     We _could_ display a veteran-facing notification of the missing name, however this might be better handled by the platform team/code. If we _do_ want to handle this case internally, we would need a design ticket for this change.

- **Recommend solutions if issues are found**

     No. (see third bullet above)
