### ISSUE TITLE
Design: CHAMPVA Claims Required Email

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#98301]
Allow the person preparing the claim to receive email notifications about their submitting form. 
Create a workflow on the [CHAMPVA Claims Figma file](https://www.figma.com/design/Tfhq5h2LwXEeEEtFBAAFOv/CHAMPVA-Claims-(10-7959a)?node-id=2571-36502&node-type=canvas&t=xYvXVQ8QiMZQmnQz-0) that requires the email address field to be completed for the signer of the form

- [ ] Create Figma file
- [ ] Review with product, Lois and Premal
- [ ] Handoff to engineering

**Comment by andrea-merrill** [comment]
This is already done.  Delete meeee

**Comment by andrea-merrill** [comment]
Updating as closed as this is already done
