### ISSUE TITLE
10-7959f-2 Confirm supporting document count variable in VA-notify

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#98315]
As a user submitting an FMP claim, I want to see a count of my supporting documents in my email confirmation so that I can confirm the VA received all of the documents I uploaded.

### Acceptance criteria
- FMP Claim confirmation emails reflect the count of supporting documents that were uploaded
- The count of supporting documents does not include the form itself

![Image](https://github.com/user-attachments/assets/987b1bb5-0245-4599-a217-58e22818a186)

**Comment by michaelclement** [comment]
Preliminary inspection seems like we have an off-by-one error somewhere. When a user submits a single file, the file is uploaded, but never saved in our database. This causes the count to show 0.

If the user uploads two files, the second file is entered in the database and the count shows as 1.

**Comment by michaelclement** [comment]
Verified that 10-10d does NOT have this issue. So whatever is wrong is specific to FMP2 it seems.

**Comment by michaelclement** [comment]
The issue is that the backend logic that checks if we should generate multiple PDFs (like in the case of 10-10d with > 3 applicants) has an edge case that causes an off-by-one error. I have a fix, just doing some more testing.

**Comment by michaelclement** [comment]
![Image](https://github.com/user-attachments/assets/7d573ea7-5769-4e11-8035-aaeeb007379e)

**Comment by michaelclement** [comment]
@baltes This is ready for your review in staging.
