### ISSUE TITLE
Resolve comments from ZSF metric logging

### ISSUE THREAD

**Issue by andrea-merrill** [department-of-veterans-affairs/va.gov-team#98328]

**Comment by baltes** [comment]
@cloudmagic80 Did this deploy make it through?

**Comment by baltes** [comment]
@cloudmagic80 Checking back for confirmation on this

@andrea-merrill

**Comment by cloudmagic80** [comment]
Here is the PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/19389

**Comment by cloudmagic80** [comment]
I can't find the original story in git projects.

**Comment by andrea-merrill** [comment]
If it was closed when we were still using zenhub, it would be there.  Our
board is still active over there.

*Andrea Merrill*
Delivery Manager
*Agile Six Applications, Inc.*
***@***.*** ***@***.***>*

**Comment by baltes** [comment]
Probably this one? https://github.com/department-of-veterans-affairs/va.gov-team/issues/95196

**Comment by andrea-merrill** [comment]
That’s it!

*Andrea Merrill*
Delivery Manager
*Agile Six Applications, Inc.*
***@***.*** ***@***.***>*

**Comment by baltes** [comment]
We tracked down another story but I don't think I ever got confirmation that there's nothing left to do here.

**Comment by cloudmagic80** [comment]
@baltes  Yes, this has been deployed to production
