### ISSUE TITLE
10-7959c Add dynamic pronouns to OHI flow

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#98329]

**Comment by jamiefiore** [comment]
Here's the [figma file ](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=3517-41585&node-type=canvas&t=xYvXVQ8QiMZQmnQz-0)for this

**Comment by michaelclement** [comment]
This is a small sample of the changes as implemented: 

|         | Is third party | Is applicant |
| ------- | ------ | ----- |
| Mailing address 1 |![before1](https://github.com/user-attachments/assets/f18bbead-400f-492e-abeb-cc657e51a58c)|![after1](https://github.com/user-attachments/assets/6f9b0a2a-1e3f-4e46-b33d-de36a576edeb)|
| Mailing address 2 |![before2](https://github.com/user-attachments/assets/e0ac4526-cc6d-4528-b70d-c3a8c70e3043)|![after2](https://github.com/user-attachments/assets/abae0cd4-97df-4e7f-99d2-551bc56707cf)|

**Comment by michaelclement** [comment]
@baltes This is done and should be visible on staging shortly. Thanks!
