### ISSUE TITLE
Update landing page link for travel pay

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#98336]
## Description
The travel pay team working on a new page on VA.gov has a link on the landing page (check travel reimbursement claim status). This link text is fine, but the destination URL is changing. This is currently behind a feature flag.

## User story

As a developer working on My HealtheVet on Va.gov, I want to update the destination URL for the link to travel pay on the landing page so that it reflects the URL that this team is updating to, ensuring that Veterans will be able to reach that tool when they click our link text. 

## Links
* [Slack thread here ](https://dsva.slack.com/archives/C01K37HRUAH/p1733320185445489)

## Tasks
- [ ] Replace destination URL for the "check travel reimbursement claim status" link in the Payments box of the landing page: 
  * current URL: `va.gov/my-health/travel-claim-status`
  * URL that we need to use instead: `va.gov/my-health/travel-pay/claims`

## Acceptance criteria
- [ ] The URL for this link text (that's behind a feature flag) reflects the new URL desired by the travel pay team.

**Comment by sterkenburgsara** [comment]
// cc @ayushchak @liztownd

**Comment by ayush-chak** [comment]
@sterkenburgsara just clarified with Liz that we should be redirecting to `travel-pay/claims` so I just edited the destination URL. Thank you!

**Comment by sterkenburgsara** [comment]
@ayush-chak @liztownd I have a few questions about this update. But I'll ask them in your team's Slack.

**Comment by sterkenburgsara** [comment]
For paper trail: question about this URL update (posed in Slack) [can be found here](https://dsva.slack.com/archives/C05UTPZRZFY/p1733346047701169).

**Comment by dcloud** [comment]
Update the link in `src/applications/mhv-landing-page/utilities/data/index.js`

**Comment by dcloud** [comment]
Per [Slack](https://dsva.slack.com/archives/C05UTPZRZFY/p1733938740035959?thread_ts=1733346047.701169&cid=C05UTPZRZFY):

> I saw that ticket, and honestly, I'm tempted to say "I'll just change it when I change everything around in our app as well" if you're ok with it. :woman-shrugging:  (Should be easy enough to just do a search through the codebase and change every instance of travel-claim-status links (since this is currently the only entry point)).

I think this makes sense as it is just a find/replace: I did a search for `travel-claim-status` to find where it lives in our app

**Comment by liztownd** [comment]
@dcloud You should have only found it once, right? But yes, I can just do a search for it and update in the MHV landing page app as well.

**Comment by dcloud** [comment]
> [@dcloud](https://github.com/dcloud) You should have only found it once, right? But yes, I can just do a search for it and update in the MHV landing page app as well.

Yes, one result in `mhv-landing-page` when I searched; other results in other apps or parts of code
