### ISSUE TITLE
[0781 PS] (3) Install new JSON -> PDF builder based on form0781 content

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#98339]
## HARD BLOCKED

- [Json PDF transform service](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97064)

## Acceptance Criteria
- Leverage the new JSON to PDF upload service where appropriate. 
  - This is most likely in a job that is currently building 0781 PDF s the *old* way. 
  - We just need to replicate that logic, for the new service, based on `'form0781'` content

**Comment by freeheeling** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19909) submitted for review

**Comment by freeheeling** [comment]
PR approved and merged. Will deploy tomorrow.

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
