### ISSUE TITLE
Review PDF List of Folks Who Need to Be Removed from Prod Terminal

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#98343]
## Description 
Eric Boehs sent us a list of folks who need access revoked during his access review. We need to remove said people. PDF attached in comments.

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
[Access Review Expired Prod Terminal.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01FQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c6718ab16a2b95ba12444ebcb7299b3b91fbf72/Access%20Review%20Expired%20Prod%20Terminal.pdf)

**Comment by lindsay-insco** [comment]
[Wayne Weibel](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75687) Removed
[Sam Stuckey](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64119) Removed
[Tze Lhiu-Lei](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62281) Extension justification requested
[Tai Wilkin](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79751) Extension justification requested
[Jennica Stiehl](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58422) Extension justification requested
[Eric Oliver](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82595) Extension justification requested
[Vid Jovanovic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83095) Removed
[Gregg Puhala](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59191) Extension justification requested
[Rockwell Rice](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60529) Removed
[Josh Houston](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83148) Removed

**Comment by lindsay-insco** [comment]
[Tze Chiu-Lei](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62281) Removed
[Tail Wilkin](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79751) Extension granted
[Jennica Stiehl](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58422) Removed
[Eric Oliver](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82595) Removed
[Gregg Puhala](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59191) Extension granted

Audit complete
