### ISSUE TITLE
Discovery: creating an unauth version of the MHV on VA.gov landing page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#98351]
## Description
Back in June 2024, stakeholders met w/ our team to discuss creating an unauth version of the landing page & a clear outcome was to not do this. We are now walking this back & realizing that significant SEO complications will  grow for users who have learned behaviors of searching for "My HealtheVet" in search engines. 

### User story

As a Cartography team member, I want to create a simple unauth version of the landing page that has a sign-in link on it that will allow users who come in via search queries in search engines to convert to a meaningful destination page on VA.gov. 

### Notes
- Today, there is no mention whatsoever of "My HealtheVet" for the unauth experience on VA.gov - which impacts users who are learning about or applying for healthcare.
- Is it surprising to them once they get benefits that they need to access a portal that has a specific name that they haven't heard before? 
- Where should we mention it? 
- Do we want to "replicate" MHV in the unauth experience at all? How do we do this well? Today, users can't tell if they are signed in or not unless they hit a sign in widget. It isn't obvious. 
- What if instead of replicating stuff, we reduced what exists in the unauth space so that it was more obvious to users when they need to sign in? 

Possible tasks:
- [x] Review the structure of unauth VA pages 
- [ ] Review competitor health portal unauth entry point pages (comparative analysis) 
- [ ] Sketch out ideas for an unauth landing page in Figma
- [ ] Think about where this would be linked in the unauth experience on VA.gov (vs. just being discovered in search engines)
- [ ] Share w/ stakeholders for feedback
- [ ] Discuss w/ devs how this would work since the whole health portal currently sits behind authentication

## Acceptance criteria
- [ ] Have a draft that can be discussed (early stages) in office hours and with the team
- [ ] Have a technical plan for how we will do this

**Comment by wesrowe** [comment]
I heard from Robyn just now (and I think she posted in slack also) that the unauthed MHV page will definitely be in the benefit hub.

**Comment by fmccaf1** [comment]
Robyn has communicated that CAIA will take this on and lead the work. I'll close this ticket until we hear more about how/if we will be involved

**Comment by jonathanjnelson** [comment]
Wanted post Mural for transparency: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1733758036552/86e9862512bcbcddafa7900304aa6df0ee80e113
