### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by ojbucao** [department-of-veterans-affairs/va.gov-team#98354]
### Your Name

Orlando Bucao, Jr.

### Your Email

orlando.bucao@oddball.io

### Your GitHub Handle

ojbucao

### Your Role and Team

Senior Backend Engineer

### Product Manager (PM) name and email

Candi Lemoine candi.lemoine@oddball.io

### Product Owner (PO) name and email

Jennifer Bertsch jennifer.bertsch@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE3qMuBGEJxSHgW0X4rwNwreWiRU2hciHNmPvczK2a7l orland.bucao@oddball.io

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/7733b799-43b7-4e9a-b100-8c7917ac1654)

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by Efe-Oddball** [comment]
@ojbucao  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
