### ISSUE TITLE
ACapi: Implement alert for "technical" error codes

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#98360]
### User story

As a Veteran, I want to be alerted when something technical went wrong with creating a MHV UUID for me with a suggestion to try refreshing the page before calling the MHV help desk, so that I have some clue that something went wrong.

### Notes
- [Figma view for content](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=267-8150&t=FotbN3DC4x1RFjwj-4)

Possible tasks:
- 

## Acceptance criteria

- Generic/default alert content finalized – _preferably with the alert code in the heading element so that it will be included in the GA4 event_
- Generic alert is displayed whenever a specific alert (e.g., "Call MHV Help Desk" one) is not relevant
- Alert event is triggered in GA4
- QA review

**Comment by kjsuarez** [comment]
[Additional PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33713) to patch an issue where multiple errors on a given API response could result in a discrepancy between the status code displayed in the alert and the status code displayed in the cards.

**Comment by wesrowe** [comment]
Riley returned a couple minor content updates for the alerts in [the caia intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99016#issuecomment-2557546056).

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that a generic error alert appears when given an error code outside of the 4 error codes list [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97281) (801, 805, 806, 807). 

Regression testing was also done to ensure that nothing broke:
1. Verified that the error code didn't shown for a newly created account
2. Verified that existing test users was able to login as expected and didn't run into any issues

<img width="892" alt="Image" src="https://github.com/user-attachments/assets/e0cf09eb-9e47-40c6-965f-5c5f04a926da" />

**Comment by wesrowe** [comment]
I was able to verify in GA4 for Staging that the alert components are sending events to GA4: 

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/8b79285c-9487-4b23-b584-01321ae0130e" />
