### ISSUE TITLE
upgrade to node 14 before LTS support ends for node 10

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9837]
![schedule.svg](https://images.zenhubusercontent.com/5a5d4c174b5806bc2bc2db50/591813f8-599c-4a6f-9fd2-be77856b0816)

https://nodejs.org/en/about/releases/

Start this work in October when 14 has LTS

**Comment by timwright12** [comment]
Just noting that the current version appears to be 10.15.3 and the current LTS is 14.15.0 (https://nodejs.org/en/)

Set in two places:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/.nvmrc
https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L274

As well as in CircleCI Config (10 times):
https://github.com/department-of-veterans-affairs/vets-website/blob/master/.circleci/config.yml

**Comment by U-DON** [comment]
The [Dockerfile](https://github.com/department-of-veterans-affairs/vets-website/blob/master/Dockerfile#L3) should also be updated. It's used in the Jenkins pipeline.

**Comment by timwright12** [comment]
Adding PRs to the ticket for good measure:
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/497
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/544
https://github.com/department-of-veterans-affairs/vets-website/pull/14847

**Comment by timwright12** [comment]
Grabbing a hand from ops for this since we have to update Jenkins / Docker to use the AWS CLI

**Comment by timwright12** [comment]
Updating here that vets-json-schema and veteran-facing-services-tools have been merged. Vets-website is with OPS and is looking at next week.

**Comment by timwright12** [comment]
This is merged and complete
