### ISSUE TITLE
Log Silent Failures for PCI & OH Travel

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#98378]
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1733339803609219?thread_ts=1733339296.770079&cid=C02G6AB3ZRS)

We need to start reporting when a Silent Failure  [happen to the data dog dashboard](https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=false&refresh_mode=sliding&from_ts=1725372633738&to_ts=1733325033738&live=true). Since we have a Silent Failure in the Travel Pay flow, we need to start reporting when that happens.

It looks like a low lift; [Here are the direction from the team ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md). Looks like we need to increment [a statsd metric](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md#logging-unresolved-silent-failures) when we think it happens.

We should add something like this when we detect that the claim was failed and the text message failed to send
tags = ['service:veteran-facing-forms', 'function: Day of CheckIn Travel pay Travel Pay Notification Failure']
StatsD.increment('silent_failure', tags:)

I would say this is a work on next sprint priority.

## Tasks
- Log the silent failure to DD
- Update the RSpecs
- Determine if the logged failure has occurred
- Create a F/U ticket to leave as a reminder in the current sprint to check this until we see that it has worked and then create a dashboard for it

**Comment by kanchanasuriya** [comment]
Identified a way to add the `silent_failure` metrics in [travel claims dashboard](https://vagov.ddog-gov.com/dashboard/5pd-req-u6d/check-in-travel-claims?fromUser=false&refresh_mode=sliding&from_ts=1734381017912&to_ts=1734985817912&live=true) & updated the same.
