### ISSUE TITLE
COVID-19 Screener - Exclude Page from Site Map XML

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#9838]
## What happened?

For the [COVID-19 screening tool](https://www.va.gov/covid19screen/) the decision was made to exclude (or no-index) this page from search engine indexing/query.  The [no-index tag was applied to the page](https://github.com/department-of-veterans-affairs/vets-website/pull/12747), but because this page is contained in the [xml site map](https://www.va.gov/sitemap.xml), it is surfacing in Google search.    As a short-term workaround, we have temporarily removed the COVID-19 Screening Tool page from Google Search Results via a blunt force feature in Google Search Console.

## The issue?

How do make sure pages we want to exclude/no-index are not included in the Drupal dynamically published site map xml?

## Specs:
- Device: N/A
- Browser: All -- Google and Bing Search Results
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: Search "VA COVID-19 Screening Tool" on Google.
- Test User _(if applicable)_:

<img width="689" alt="Screen Shot 2020-06-04 at 12 47 26 PM" src="https://user-images.githubusercontent.com/63107147/83787592-050d8780-a662-11ea-8db7-5cb298587319.png">

## Desired behavior
The COVID 19 screening tool page should not be discoverable via Search on Google, Bing and other search engines.

(The page https://www.va.gov/covid19screen should be removed/excluded/no-indexed from the VA.gov site map XML.)

## Acceptance Criteria
- [ ] The COVID 19 screening tool page is no longer indexable from the VA.gov site map xml.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by batemapf** [comment]
connecting with https://github.com/department-of-veterans-affairs/vets-website/pull/12930

**Comment by rianfowler** [comment]
Verified that https://www.va.gov/covid19screen  is not in the [sitemap.xml](https://www.va.gov/sitemap.xml).

**Comment by johnhashva** [comment]
Great -- closing this issue.
