### ISSUE TITLE
Create Email Templates for Notifying Pega about missing status and when we have sent a ZSF email to user

### ISSUE THREAD

**Issue by andrea-merrill** [department-of-veterans-affairs/va.gov-team#98404]
We need to create two VA Notify Email templates to send a notification to the Pega team for the following use cases:

- A user has submitted a form, but we have not heard back from Pega, so the status is "null" 
- A ZSF email notification has been sent to the user 

## Implementation Details
- This story is just to capture creating the two email teamplates.  These stories will be done to hook them templates to a monitor: [Job to warn Pega team prior to sending ZSF email to user](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98406)  and [Notify PEGA team of records that trigger zsf notifications](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95915)

## Acceptance Criteria:
- One email template has been created that will send the UUID of a form with a missing status to Pega after x amount of time, but before 7 days 
- Another email will be created that will send the UUID of a form with a missing status to Pega and inform them that the user has been sent a ZSF email

**Comment by cloudmagic80** [comment]
![Image](https://github.com/user-attachments/assets/c102db03-6ad2-4909-b8d9-3fec8a7f2cf8)

**Comment by cloudmagic80** [comment]
Template has been added to staging AWS param store. Will add production variables once we're through design review of this.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/19783

**Comment by baltes** [comment]
```
One email template has been created that will send the UUID of a form with a missing status to Pega after x amount of time, but 
before 7 days
```

@cloudmagic80 Can you confirm when this would send as it's set up now?
