### ISSUE TITLE
Job to warn Pega team prior to sending ZSF email to user

### ISSUE THREAD

**Issue by andrea-merrill** [department-of-veterans-affairs/va.gov-team#98406]
As a team member monitoring form submissions, I want a warning about submits that may trigger a zsf prior to the trigger so that I can try to resolve them.

## Implementation details: 
- Could tie into existing monitor that currently sends emails to users to let the know that they need to resubmit.
- This should be sent sooner than the job to send ZSF (currently configurable and set to 7 days) so that Pega has time to fix any issues
- Email for pega mail box: vbacodocmppeganot@va.gov

### Acceptance criteria
- Submits at risk of sending a silent failure notification first send a warning to DOCMP team (email)
- Use email template created in this story: [Create Email Templates for Notifying Pega about missing status and when we have sent a ZSF email to user](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98404)

**Comment by andrea-merrill** [comment]
Adding this in case it's helpful: [FMP: Process to monitor missing statuses and send ZSF emails](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95907) 

This is the original ticket that has the monitor that kicks off the ZSF emails to to users.

**Comment by michaelclement** [comment]
Work is done in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19814). Waiting on [the previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19795) to be approved/merged as this one builds on it.

**Comment by michaelclement** [comment]
This screenshot is of the Pega email inbox - note the two different emails on the left-hand pane. The emails are sending successfully.

![Image](https://github.com/user-attachments/assets/700cf95f-7bd0-49ba-bb3e-0ce2a03238cf)

**Comment by baltes** [comment]
Did we hear anything back from DOCMP if these got to their mailbox?

**Comment by michaelclement** [comment]
@baltes Yep! That's a screenshot of the DOCMP mailbox
