### ISSUE TITLE
Document findings from PgQuery Duration spikes

### ISSUE THREAD

**Issue by AshleyGuerrant** [department-of-veterans-affairs/va.gov-team#98410]
## Issue Description
In https://github.com/department-of-veterans-affairs/va.gov-team/issues/96409, we are still seeing spikes in the PgQuery duration overnight. The logs show that there are PgQuery timeouts. The specific slow queries have been identified, and the Veteran Facing Services (VFS) teams have been notified about the issues with their queries. The resolution is being tracked in #97380, #98334, and VFS team tickets.

Research has already been conducted to identify the specific slow queries, potential explanations for why these queries spike overnight, and what systems are involved.

## Tasks
- [x] Research and discovery
- [x] Complete documentation of the research findings

## Acceptance Criteria
- [x] Confluence documentation

**Comment by LindseySaari** [comment]
A document has been started in our [team Confluence space here ](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3680272409/Postgres+Query+Duration+Discovery+and+Investigation)

**Comment by AshleyGuerrant** [comment]
**Standup note:** handed off to stakeholders and key dev's for review.

**Comment by rmtolmach** [comment]
✅ I reviewed the document. Had a couple comments, but it looks good!

**Comment by LindseySaari** [comment]
Thanks @rmtolmach! I've addressed the comments and pinged @AshleyGuerrant to create a ticket for the future improvements suggestion. This doc has been forwarded to stakeholders, so I'm going to close!
