### ISSUE TITLE
Implement best practices for clickable vs. non-clickable TTY numbers (aria labels)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9841]
# User story

As a member of the VA.gov content, design, and development team, I would like TTY numbers to be clickable.

**TIL**
> A TTY is a special device that lets people who are deaf, hard of hearing, or speech-impaired use the telephone to communicate, by allowing them to type messages back and forth to one another instead of talking and listening.

# Details

We have performed research into updating our practices ( #8379) and have determined that we wish to make TTY numbers clickable. In order to do this within Drupal, we need to make use of aria labels. 

There was a discovered issue that aria labels have not been saving, so CMS team will address this need in a separate [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1957) . 

When the fix is complete, we can implement the needed aria label change

### Process steps to completion

- [x] Add guidance to style guide (if not already complete)
- [x] Set up, save use of aria labels to known TTY numbers
- [x] Ensure we're following this guidance consistently throughout all content.

**Aria label added on the following pages:**
- [x] https://www.va.gov/change-direct-deposit/ 
- [x] https://www.va.gov/records/download-va-letters/
- [x] https://www.va.gov/va-payment-history/
- [x] https://www.va.gov/health-care/health-needs-conditions/mental-health/depression/
- [x] https://www.va.gov/health-care/health-needs-conditions/mental-health/ptsd/
- [x] https://www.va.gov/health-care/health-needs-conditions/mental-health/suicide-prevention/
- [x] https://www.va.gov/health-care/health-needs-conditions/mental-health/
- [x] https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/
- [x] https://www.va.gov/health-care/health-needs-conditions/substance-use-problems/index.html
- [x] https://www.va.gov/health-care/refill-track-prescriptions/
- [x] https://www.va.gov/health-care/schedule-view-va-appointments/index.html
- [x] https://www.va.gov/health-care/secure-messaging/
- [x] https://www.va.gov/health-care/view-test-and-lab-results/
- [x] https://www.va.gov/health-care/get-health-id-card/
- [x] https://www.va.gov/health-care/pay-copay-bill/dispute-charges/index.html
- [x] https://www.va.gov/health-care/pay-copay-bill/financial-hardship/index.html
- [x] https://www.va.gov/burials-memorials/veterans-burial-allowance/
- [x] https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/index.html
- [x] https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea/
- [x] https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/testing-storage-areas/index.html
- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/index.html
- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/index.html
- [x] https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/index.html
- [x] https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/index.html
- [x] https://www.va.gov/education/other-va-education-benefits/veap/
- [x] https://www.va.gov/health-care/eligibility/active-duty/index.html
- [x] https://www.va.gov/health-care/get-medical-records/index.html
- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/index.html

**Comment by kelsonic** [comment]
References to `TTY` in `vets-website`:

```
58 results - 52 files

src/applications/auth/containers/AuthApp.jsx:
  313:                   have hearing loss, call TTY: 800-877-3399.
src/applications/caregivers/components/NeedHelpFooter/index.jsx:
  57:           <span>If you have hearing loss, call TTY: 711.</span>
src/applications/disability-benefits/2346/components/FooterInfo.jsx:
  7:     . If you have hearing loss, call <a href="tel:800-877-8339">TTY: 711</a>.
src/applications/disability-benefits/686c-674/components/GetFormHelp.jsx:
  12:     If you have hearing loss, call TTY: 711.
src/applications/disability-benefits/686c-674/config/helpers.js:
  54:       (TTY:711). We're here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.
src/applications/disability-benefits/996/components/GetFormHelp.jsx:
  16:     If you have hearing loss, call TTY: 711.
src/applications/disability-benefits/all-claims/content/common.jsx:
  41:       If you have hearing loss, please call TTY at{' '}
  42:       <Telephone contact={CONTACTS.CRISIS_TTY} />.
src/applications/gi/components/vet-tec/VetTecApplicationProcess.jsx:
  70:             you have hearing loss, call TTY:711, <b>or</b>
src/applications/hca/components/GetFormHelp.jsx:
  15:         TTY:{' '}
src/applications/hca/containers/IntroductionPage.jsx:
  63:             have hearing loss, call TTY: 800-877-8339. We're here Monday through
src/applications/personalization/profile-2/components/MilitaryInformation.jsx:
  137:             p.m. ET. If you have hearing loss, call TTY:{' '}
src/applications/personalization/profile-2/components/direct-deposit/FraudVictimAlert.jsx:
  19:     (TTY: 711). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
src/applications/personalization/profile360/components/MilitaryInformation.jsx:
  124:             hearing loss, call TTY: 1-866-363-2883.
src/applications/personalization/profile360/components/PaymentInformationBlocked.jsx:
  26:         (TTY: 711). We're here Monday &#8211; Friday, 8 a.m. &#8211; 8 p.m. ET.
src/applications/personalization/profile360/components/PaymentInformationEditModalError.jsx:
  28:         (TTY: <span className="no-wrap">711</span>
  45:         (TTY: 711). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
src/applications/personalization/profile360/containers/PaymentInformation.jsx:
  227:               (TTY: 711). We're here Monday through Friday, 8:00 a.m. to 9:00
src/applications/personalization/profile360/tests/components/PaymentInformationEditModalError.unit.spec.jsx:
  280: res additional verification before we can save your information. To use this bank routing number, you'll need to call us at <span class="no-wrap"><a href="tel:1-800-827-1000">800-827-1000</a></span> (TTY: 711). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.',
src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx:
  44:             (TTY:711). We're here Monday-Friday, 8:00 a.m.-8:00 p.m. ET.
src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx:
  24:         (TTY:711). We're here Monday-Friday, 8:00 a.m.-8:00 p.m. ET.
src/applications/personalization/view-dependents/layouts/helpers.jsx:
  15:       (TTY:711). We're here Monday-Friday, 8:00a.m.-8:00p.m. ET.
src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/App/index.js:
  246:                 Or call us at <a href="tel:+18773270022">877-327-0022</a> (TTY:{' '}
src/applications/static-pages/health-care-manage-benefits/prescriptions-refill-content/components/App/index.js:
  299:                 <a href="tel:+18773270022">877-327-0022</a> (TTY:{' '}
src/applications/static-pages/health-care-manage-benefits/schedule-view-va-appointments/components/App/index.js:
  330:                 <a href="tel:+18773270022">877-327-0022</a> (TTY:{' '}
src/applications/static-pages/health-care-manage-benefits/secure-messaging/components/App/index.js:
  286:                 <a href="tel:+18773270022">877-327-0022</a> (TTY:{' '}
src/applications/static-pages/health-care-manage-benefits/view-test-lab-results-page/components/App/index.js:
  254:                 <a href="tel:+18773270022">877-327-0022</a> (TTY:{' '}
src/applications/validate-mhv-account/components/errors/DeactivatedMHVId.jsx:
  32:             hearing loss, call TTY: 800-877-3399.
src/applications/validate-mhv-account/components/errors/MultipleMHVIds.jsx:
  25:             call TTY: 800-877-3399.
src/applications/validate-mhv-account/components/errors/NeedsSSNResolution.jsx:
  31:             hearing loss, call TTY: 711.
src/applications/validate-mhv-account/components/errors/NeedsVAPatient.jsx:
  24:           hearing loss, call TTY: 711.
  40:           TTY: 711.
src/applications/validate-mhv-account/components/errors/VerificationFailed.jsx:
  32:             hearing loss, call TTY: 711.
src/applications/validate-mhv-account/containers/CreateMHVAccountFailed.jsx:
  43:             call TTY: 800-877-3399.
src/applications/validate-mhv-account/containers/UpgradeAccountFailed.jsx:
  40:             call TTY: 800-877-3399.
src/applications/vaos/api/pact.json:
  131:         "staffName": "GULLIVER,BETTY J",
src/applications/vaos/components/NeedHelp.jsx:
  17:         call TTY: 711). We're here Monday &ndash; Friday, 8:00 a.m. to 8:00 p.m.
  23:         call TTY: 711). We're here Monday &ndash; Saturday, 7:00 a.m. to 11:00
src/applications/verify/containers/VerifyApp.jsx:
  105:                     <a href="tel:1-855-574-7286">855-574-7286</a>, TTY:{' '}
src/applications/vre/components/GetFormHelp.jsx:
  12:         TTY:{' '}
src/platform/forms/save-in-progress/SaveInProgressErrorPage.jsx:
  20:   We're sorry. We can't give you access to this information. For help, please call the VA.gov help desk at 855-574-7286 (TTY: 711). We're here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.
src/platform/landing-pages/header-footer-data.json:
  209:       "title": "TTY: 711"
src/platform/site-wide/cta-widget/components/messages/DeactivatedMHVIds.jsx:
  22:             hearing loss, call TTY: 800-877-3399.
src/platform/site-wide/cta-widget/components/messages/MultipleIds.jsx:
  18:             hearing loss, call TTY: 800-877-3399.
src/platform/site-wide/cta-widget/components/messages/NeedsSSNResolution.jsx:
  27:             hearing loss, call TTY: 711.
src/platform/site-wide/cta-widget/components/messages/NeedsVAPatient.jsx:
  22:           hearing loss, call TTY: 711.
  38:           TTY: 711.
src/platform/site-wide/cta-widget/components/messages/RegisterFailed.jsx:
  33:             hearing loss, call TTY: 800-877-3399.
src/platform/site-wide/cta-widget/components/messages/UpgradeFailed.jsx:
  31:             hearing loss, call TTY: 800-877-3399.
src/platform/site-wide/cta-widget/components/messages/mvi/NotFound.jsx:
  21:           hearing loss, call TTY: 711.
src/platform/site-wide/user-nav/components/HelpMenu.jsx:
  30:       <p>TTY: 711</p>
src/platform/site-wide/va-footer/components/CrisisPanel.jsx:
  68:                 Call TTY if you have hearing loss <strong>800-799-4889</strong>
src/platform/static-data/CallHRC.jsx:
  8:       If you have hearing loss, call TTY: 711.
src/platform/static-data/CallNCACenter.jsx:
  8:       loss, call TTY: 711.
src/platform/static-data/CallVBACenter.jsx:
  8:       loss, call TTY: 711.
src/platform/static-data/footer-links.json:
  208:     "title": "TTY: 711"
src/platform/user/authorization/containers/MHVApp.jsx:
  73:           Please call the My HealtheVet Help Desk at 877-327-0022 (TTY:
  93:           Please call the My HealtheVet Help Desk at 877-327-0022 (TTY:
```

**Comment by RLHecht** [comment]
@kelsonic I took care of updating all the TTY instances you found for me on Drupal pages but I need your help with all the others. Is this something you can work on?

**Comment by kelsonic** [comment]
@RLHecht of course! Which TTY numbers in vets-website do you need me to update? (From what number to what number)

**Comment by MickinSahni** [comment]
Using a reusable component but those don't have descriptions (Danielle).
Once descriptions are included, we can use the reusable component. 

2 follow-up tickets (@kelsonic) and link up any blockers, etc.:
- update telephone component with tty numbers
- use telephone component in vets-website for tty numbers

**Comment by kelsonic** [comment]
Sorry about that, didn't mean to close, meant to select `Validate` 😂 So the PR is merged for TTY numbers in `vets-website`, not sure if there's any other work here or if that's it! 📈 CC @RLHecht

**Comment by RLHecht** [comment]
@kelsonic I think that's it if you were able to tackle all the places I couldn't get to within Drupal. Thanks so much for doing this!

**Comment by kelsonic** [comment]
Awesome! Ready for validation + closing then! 🎉

**Comment by RLHecht** [comment]
Closing ticket. Thanks again, @kelson! FYSA @MickinSahni
