### ISSUE TITLE
Sidekiq Admin UI access for Holden Hinkle (AKA Emmerson Hinkle)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#98448]
### Your Name

Holden Hinkle

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@holdenhinkle

### Your dsvagovcloud AWS user name (if applicable)

Holden.Hinkle

### Team, Role, and Company of the target individual

Accredited Representation Management, Tech Lead, Oddball, Inc

### COR Name

Laurene "Reney" Cook

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [x] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

**Comment by ericboehs** [comment]
Since Holden transferred from Platform, I requested he get an access request going for Sidekiq. He was scheduled for removal per our security audits.

**Comment by lindsay-insco** [comment]
@holdenhinkle you have access to `dev`, `staging`, and `sandbox`
