### ISSUE TITLE
Handle CC appointments returned in MAS

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#9844]
Community Care appointments can be created outside of the VAOS workflow and written to VistA directly. It's important VAOSR account for these appointments because a Veteran needs to know they have been schedule with their community provider. 

Context from the bug that started this thread - #11632

### **Constraints/considerations for this solution:**
- Only half of CC-enabled sites use VAOS/SM workflow (71 sites out of 150+ sites). 
   - It can be assumed that some volume of CC appointments need to be accounted for in VAOSR app (ie, display to Veteran in some way) because they are not accounted for in the VAOS/SM workflow.
- Sites not using VAOS/SM workflow instead account for CC appointments in VistA directly
   - Which limits the data available for VistA CC appointments - Currently, there is no other additional provider information/location details associated with the appointment 
   - Today VistA CC appts only display 'date/time of appointment' and whatever else is provided in the 'free text clinic name'
- Recognition of these VistA CC appts is dependent on manual entry of the prefix pattern into free text clinic name field for MAS recognition:
   - COM CARE-<specialty> (example: COM CARE-AUDIOLOGY)
   - Or match one of these two clinic names:  NON VA CARE HCPS HEMODIALYSIS or NON VA CARE HCPS PERITONEAL DIALYSIS
- Potential for duplicates exist only when a site is CC-enabled, is using VAOS/SM workflow, and does not complete the SM workflow which leaves open a CC request in VAOS and also (if we enable the VistA CC appts) a confirmed CC appt for that same time/date -- _still verifying_
- VistA CC appts are necessary to enable tracking of CC appointments by VA

### **Needs:**
- The mobile appointment service has an `communityCare` flag. We need to figure out if this is set to true, are we showing duplicate appointments between that and the booked-cc-appointments endpoint.
- The veterans should not be able to cancel the CC [VistA] appointments. The CC Clerk has to do the cancelation because they have a paper trail of referrals, consults, etc. associated with the CC appointment so it’s an involved process.
- Assumption is there not additional information available to use describing these appointments 
   - Because of that OCC/OVAC asked for the following to be displayed: **_"This appointment is scheduled with a community provider. Please do not report to your local VA facility. If you have questions, please contact your facility community care staff at your local VA."_**

### **Option for addressing:**
**Option** For sites that are CC-enabled, but do not use VAOS/SM workflow, always display VistA CC appointments. 
   - Pro: Addresses differences in sites' processing workflows and thus appointment display; accounts for all CC appointments
   - Con: VistA CC appts will still have little to no information about provider/provider location
   - Discovery: Booking notes cannot be repurposed for these appointments

### **Long term solution:**
- The integration efforts with HSRM create an opportunity for us (VAOS FE app) to use HSRM to pull our Community Care appointments. - This assumes all CC-enabled sites use HSRM to process their Community Care appointments in the future. 
    - Open question - Timing of this solution availability not clear
    - Open assumption to confirm - CC appts will still need to be accounted for outside of the HSRM workflow
    - Open assumption to confirm - that VAOS FE app can pull from future HSRM system and ignore SM MongoBD and CC VistA appts

**Comment by jbalboni** [comment]
This was added to var-web here: https://issues.mobilehealth.va.gov/browse/VAOSR-108

Currently, the display CC flag is set to false prod, per Brad Crosby. So while we should adapt our code to handle CC appointments through VistA, it's not clear what we actually need to do.

Questions:

1. What functionality is present for these appointments? Can they be canceled?
2. We have a clinic name, is there other provider info we can show?
3. Are these duplicates of appointments in the booked cc appointments service?

**Comment by lenaecb** [comment]
@narin @jbalboni - sent an email today asking for help in triaging this. 7/13/2020

**Comment by lenaecb** [comment]
**Right now a VistA CC appt looks like this in new VAOSR:**
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/9b39c382-7a48-40a0-b568-0abffb65ecdd)


**Duplicates can look like this in new VAOSR:** ( Here is a patient that has booked CC from VistA and from VARdb (request made and then booked in SM)
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/b04bb61f-52c7-4909-930f-09fcb11ead7a)

**Comment by lenaecb** [comment]
This is linked to work completed here -- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12735

**Comment by JRRoof** [comment]
Old item.  No longer relevant after migration to VAOS v2.
