### ISSUE TITLE
Staging Review finding: Bold text used for dates and email addresses

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98443]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Identity
**Product:** sign-in transition
**Feature:** interstitial

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content with errors or inconsistencies.](https://design.va.gov/about/experience-standards/#user-encounters-accurate-consistent-content)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

Text throughout the pages uses bold text to draw attention to titles. While the use of bold text for the different types of accounts meet VADS standards, the use of bold text to show dates and email addresses does not meet the VADS standards for when to use bold text.

<details><summary>Link, screenshot or steps to recreate</summary>

to be added

</details>

## Recommended action

Remove the bold text from dates and emails.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Bold & italic text](https://design.va.gov/content-style-guide/bold-text)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by kdmeg-bluetiger** [comment]
Hey @shiragoodman - the bold text for the date and email address were included the the final content we got from CAIA in our collaboration with them. Here's the [issue details with a link to the final edits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91700#issuecomment-2372342660). Please let me know if you need any other information!

**Comment by kdmeg-bluetiger** [comment]
Thanks for the update @KKitagawa-Bosch! 

Our team is moving the design forward for launch this week, so we removed the bold text for now. I appreciate that this discussion prompted some expanded design system guidelines for usage of bold text going forward! 👍
