### ISSUE TITLE
[0781 PS] Save traumatic event selection to DB

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#98450]
## Context

One of the early tickets in the Epic was the 'screener page'. this was deployed before our planning and boilerplate, but we need to revisit it. The veterans choice on this page is not being saved to the database. this is a critical bit of data that informs wether or not we show the 0781

For example, here I've selected a PTSD event on the screener page (2.1) but am not seeing it reflected in what I BELIVE is the appropriate form value, `traumaticEventsInfo`, which was added in our earlier work

![Image](https://github.com/user-attachments/assets/4697f2ee-a20e-4b9f-a538-bea6e85a8441)

I'm fairly certain that if my understanding is correct, all we need to do is add `formData?.traumaticEventsInfo?.length > 0` to the appropriate flippers

## Acceptance Criteria
- the first piece of work is a sanity check by @freeheeling . Is what I'm seeing correct? should this choice be affecting the flow?
- IF this is actually a problem, follow up work is
  - make this data save correctly when selected
  - leverage this data in the `showForm0781Pages` or as needed. this is a top level flipper for the whole flow, so adding this here may be sufficient. However, work is on the Dev to confirm this with [the design tiles](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-81612&node-type=section&t=39LfpSj5MNcq7GQa-0)

**Comment by freeheeling** [comment]
@SamStuckey Is this no longer needed?

**Comment by kylesoskin** [comment]
@SamStuckey says this is no longer needed.

**Comment by lisacapaccioli** [comment]
# Resources
- [Epic] 0781 Paper Sync 	https://github.com/department-of-veterans-affairs/va.gov-team/issues/87438
- [Story Mapping Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718308823134/02c2c9ea74f16b276692af8f31eb65202acc7928?wid=0-1719930043260)
- [Figma 0781 redesigns](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9856-83462&t=us3dJI6ZkhtJ0Wz8-4)
- [Figma 0781 redesigns-final](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8144-135894)
- [Draft - 0781 Field Mapping Tracker](https://docs.google.com/spreadsheets/d/1pdJ5W-dJ56ysxrtkWl8d6Rsurf2nxXDqb8-7C9oGwcg/edit?gid=354068332#gid=354068332)
- [Final -0781 PS Field Mapping.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20Field%20Mapping.md)
- [Final - 0781 PS New SubURL.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/0781%20Paper%20Sync/0781%20PS%20New%20SubURL.md)
