### ISSUE TITLE
AWS access for Kris Pethtel

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va.gov-team#98455]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Kristopher Pethtel

### Your Email

kris.pethtel@adhocteam.us

### Team, Role, and Company of the target individual

IIR, Staff Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Pete Egan, peter.egan@oddball.io

### Product Owner (PO) name and email

Jeff Barnes, jeffrey.barnes4@va.gov

### Desired AWS Access

Please copy permissions from Adam King.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/18ef385d-073c-49cd-8dc2-75d35de11ab4)

### Additional Notes

Ongoing because I'm on an ongoing contract. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
User is part of ATLAS

**Comment by Efe-Oddball** [comment]
Access granted and temporary credentials have been passed to the user at this time.
