### ISSUE TITLE
VSP content feedback - Staging review -  Caregiver form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#9849]
## User story
As a caregiver and Veteran, I need to know how to apply for Caregiver benefits.

This ticket captures VSP content feedback on the 10-10C G form.

Staging link:  https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction

## Acceptance criteria
 - [x] VSP/Peggy provides content feedback and recommendations for the form/tool.
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x]  Product team leaves any comments about feedback they decide not to take
- [ ] Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
VSP content for Caregivers staging review: 

Feedback key
Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

-----

*Must*
1. Breadcrumbs: are these correct? They don’t follow Mikki’s I/A recommendation Home > Family member benefits > Apply for the Program of Comprehensive Assistance for Family Caregivers

2. Are users not required to sign in to fill out this form? 
This page is missing the link [Start application without signing in]

*Must*
3. GLOBAL changes
Please fix style/casing of the below in all content and form field labels
Social Security number
Tax identification number

*Must*
4. You will also need= You’ll need

5. "or discuss these options with your local Caregiver Support Coordinator." = add a comma before “or”

6. Start your application = please sentence case buttons

*Should*
7. Veteran’s sex
Please change “Unknown” option to “Prefer not to answer” or "I don't know"
This align with our style principle of being empathetic

*Should*
8. [What’s a Primary Family Caregiver?] link
Recommend removing this language as it’s legalese and not plain language

A Family Member (defined herein), who is designated as a "primary provider of personal care services" under38 U.S.C. §1720G(a)(7)(A);and who meets the requirements of38 C.F.R. §71.25.

*Must*
9. Cap V in Veteran in this sentence: 
Tricare is a government health care program for service members, veterans, and their families.

*Should*
10. [What’s a Secondary Family Caregiver] link
Recommend removing this language as it’s legalese and not plain language

Secondary Family Caregivers are people approved as a “provider of personal care services” for the eligible Veteran under38 U.S.C. §1720G(a)(7)(A);meets the requirements of38 C.F.R. §71.25.a.

*Must*
11. Go back to VA.gov, please sentence-case labels

12. I am unable to get to see the confirmation page. Is there a way I can access the confirmation page?

**Comment by LinnJS** [comment]
@peggygannon in regards to #2 on this list unfortunately the 1010CG is only an `unauthenticated experience` due to multiple parties having to "sign" this form.

**Comment by LinnJS** [comment]
Breadcrumbs IA PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13985
Content PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13988

**Comment by peggygannon** [comment]
@LinnJS thank you, Justin for the feedback. I took a look at the updates and it looks good.

**Comment by LinnJS** [comment]
@peggygannon just merged the work that fixed content consistency, and sentence casing issues
