### ISSUE TITLE
CF: Update caution flag plain language mappings

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9851]
As a developer, I need to update the Caution Flag content for any issues found post launch so that the user has a good experience when using the Comparison Tool

## Assumptions:
1. This story will remain open until the work is delivered to production, due to the nature of the mapping updates.
2. A new mapping can be created, or the mapping for "Federal Trade Commission Filed Suit for Deceptive Action" can be replaced with AC1.

## Acceptance Criteria:
1. The Caution Flag "Federal Trade Commission (FTC) filed suit for deceptive action" received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
    - Title: Federal Trade Commission (FTC) filed suit for deceptive action
    - Description: The FTC filed a suit against this school for deceptive action. VA may suspend benefits to this school.

## Supporting Artifacts:
1. [Settlement_06042020.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4736108/Settlement_06042020.txt) - CSV renamed to text to upload into github.

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/669

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-11 at 10.40.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cda930ee-4e0e-4575-b3d2-f68e12c158d0)
##
![Screen Shot 2020-06-11 at 10.40.52 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3cb6ddac-be3d-45c1-9688-1d8c1aa7f93b)
##
![Screen Shot 2020-06-11 at 10.41.00 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a891ad44-0056-49b2-ab19-992b5b486ec0)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/481&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam, @JenLJ and I think this is good to go!

**Comment by sonntag-adam** [comment]
Moving to blocked for now

1. This story will remain open until the work is delivered to production, due to the nature of the mapping updates.

**Comment by desireeturner** [comment]
This has been approved to be delivered to Prod.

**Comment by zurbergram** [comment]
Changes are deployed to production
http://jenkins.vfs.va.gov/job/builds/job/gi-bill-data-service/517/
http://jenkins.vfs.va.gov/job/deploys/job/gi-bill-data-service-vagov-prod-post-deploy/40/

**Comment by desireeturner** [comment]
This flag happens for one institution, but the institution is not visible in staging / prod, so this story can be closed.
