### ISSUE TITLE
Recent clinics endpoint is returning a clinic with null attributes

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#98519]
## Description
Investigate why the new **recent clinics** endpoint is returning a clinic with null attributes.
Logged in user: **Judy Morrison**

**See last clinic in response:** 

```
{
  "data": [
    {
      "id": "1067",
      "type": "clinics",
      "attributes": {
        "vista_site": 983,
        "id": "1067",
        "service_name": "HOME TELEHEALTH",
        "physical_location": null,
        "phone_number": "3037208888",
        "station_id": "983",
        "station_name": "CHYSHR-Cheyenne VA Medical Center",
        "primary_stop_code": 685,
        "primary_stop_code_name": "HT PROGRAM PATIENTS",
        "secondary_stop_code": 179,
        "secondary_stop_code_name": "RT CLIN VID CARE HOME",
        "patient_direct_scheduling": true,
        "patient_display": true,
        "char4": null
      }
    },
    {
      "id": null,
      "type": "clinics",
      "attributes": {
        "vista_site": null,
        "id": null,
        "service_name": null,
        "physical_location": null,
        "phone_number": null,
        "station_id": null,
        "station_name": null,
        "primary_stop_code": null,
        "primary_stop_code_name": null,
        "secondary_stop_code": null,
        "secondary_stop_code_name": null,
        "patient_direct_scheduling": null,
        "patient_display": null,
        "char4": null
      }
    }
  ]
}
```

---

## Development Checklist
- [ ] Endpoint should return list of last visited locations with no null response.
- [ ] Document in ticket what endpoint returns when not recent clinic is found.

## Definition of Done
- [ ] All tasks criteria are met

**Comment by JunTaoLuo** [comment]
In the added logs we found: `VAOS recent_clinics details for station: 984 and clinic: 4771 - {"table":{}}` which suggests that there's a configuration issue for that facility and clinic. However, given that we are updating the endpoint to return facility information in https://github.com/department-of-veterans-affairs/va.gov-team/issues/98521, this bug will be obsolete so I'm closing this issue.
