### ISSUE TITLE
Staging Review finding: Add guidance around alert placement

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98532]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Authenticated Experience Design Patterns (AEDP)
**Product:** Authenticated Design Patterns
**Feature:** Help users to...Update prefilled information

## Findings details
**VA.gov Experience Standard - issue:** [User encounters consistent, clear design components and patterns.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

There are currently [2 success alert options](https://dev-design.va.gov/3562/patterns/help-users-to/update-prefilled-information#success-alert). For the alert when a users change has been saved to the form and their VA.gov profile, there is no guidance on where this alert should be placed.

## Recommended action

Alert placement is something designers struggle with. Adding where this alert should be placed will be helpful. 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** [Know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by kristen101606** [comment]
Thanks for flagging this. I've added the guidance under the "How this pattern works" header and "Display success alerts when information has been saved" subheader. There's additional guidance about alerts under this section, so it seemed like a natural place to include placement guidance.

**Comment by msbtterswrth** [comment]
Confirmed this has been updated in [our guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Patterns/update-prefilled-information/Help%20users%20to%20update%20prefilled%20information.md#how-this-pattern-works), looks good! PR will follow once all the content has been updated.
