### ISSUE TITLE
Spike: Strategy for portal-wide alert consistency

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#98556]
### User story

As a Cartography team member, I want to frame a strategy conversation with OCTO stakeholders for how to govern and implement portal-wide access alerts, so that we can decide on an approach and move to implementation.

### Notes (Florence wrote):
- The alerts we need to update most urgently are unverified credential (LOA1) because these alerts block the user from managing their health care AND there is an action users must take to address this obstacle.
- PI planning is in January (starting 17th?)
- We'll need to understand from each of the tool teams: What is the LoE to implement alerts or route guards? Also, which tool teams did not adopt our route guard PR and alert for users with , and why?
- Can we find out how many Veterans might receive this alerts on the portal? 

### Possible tasks:
- [x] Are there alerts that are more urgent than PI planning allows?
- [x] When is PI planning? How would we engage with that process?
- [x] Is there a way (engineering-wise) to make implementation easier for teams?

## Acceptance criteria
- [x] Had a productive conversation at OCTO office hours 
- [x] Ticketed next steps or refined #98545

**Comment by sterkenburgsara** [comment]
Update: we brought this to OCTO office hours on 10/9/24 & got some insights as to how we should move forward. Documentation of notes from office hours in [Slack here](https://dsva.slack.com/archives/C0581MN69TJ/p1733784111113889). 

**Agreement on priority for alerts that should be standardized, and routing plan for them:** 
* Route-guard users to the /my-health page where they will see these alerts, as relevant. Secondary navigation will be suppressed in these scenarios: 
  * 1. ID-verification alerts - which Cartography team is updating in ticket #90884 
  * 2. No access to My HealtheVet alert (when user has 0 facilities in their profile)
* Display alerts in-place within affected tool applications & on the My HealtheVet home landing page. Secondary navigation will be visible in this scenario: 
  * 3. Account Creation API error alerts - which Cartography is building in tickets #98360 & #97281

**Comment by sterkenburgsara** [comment]
Additional needs to be picked up in follow-on ticket (# 98545) for next sprint: 

![Image](https://github.com/user-attachments/assets/f6bd21e8-4b39-41c2-b73b-13ec8ef3ff37)

**Comment by sterkenburgsara** [comment]
I have in my notes that if we get a plan together prior to Dec 20th code freeze, all teams (with exception of MR) could possibly find capacity to prioritize these updates. But MR will not be able to take it on. May need to plan to get this work prioritized as part of PI planning (only "big 4" health tool that does not do PI planning is appts.) 

Can anyone validate if they also heard this? // cc @fmccaf1 @wesrowe

**Comment by fmccaf1** [comment]
I don't remember hearing this about MR @sterkenburgsara

**Comment by sterkenburgsara** [comment]
Okay, thanks for confirming. I think that timeline is already not going to happen anyway. Prepping for PI planning timelines makes sense!
