### ISSUE TITLE
Staging Review finding: Headings on recommended benefits and all benefits pages don't adequately reflect unique content

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98578]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Transition Experience
**Product:** Transition Experience MVP v1
**Feature:** V1 Transition Experience

## Findings details
**VA.gov Experience Standard - issue:** [User doesn't have enough information to complete a task.](https://design.va.gov/about/experience-standards/#user-has-enough-information-to-complete-a-task)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

On the recommended results view and the all benefits views, the page titles do not sufficiently communicate (1) what the results on the page are, and (2) how those results differ from each other from page to page. This could be confusing for all users who visit each page and are trying to understand what they are seeing. Currently, the only way to tell the difference between pages is to look at the URL and see if `allBenefits=true`, or to read the intro paragraph below the H1 carefully.

<details><summary>Link, screenshot or steps to recreate</summary>

**Recommended benefits page**
![Image](https://github.com/user-attachments/assets/cb5ac961-4ee7-4c6f-af45-1e1dd9cd48f6)

**All benefits page**
![Image](https://github.com/user-attachments/assets/5e200f2c-8b38-4fbd-89bb-71254ec0c387)

</details>

## Recommended action

Use clear headings on the recommended results and all benefits pages to clearly indicate what is displayed on the page. This would be an opportunity to repurpose the "Benefits to explore" heading to "Recommended benefits for you" and "All benefits".

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** Headings

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by nkontrabecki** [comment]
Completed in sprint 17. Jira ticket 362.
