### ISSUE TITLE
CF: Update Settlement File Matching to Match on IPED & Facility ID

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9857]
As a developer, I need to update the GIDS version generation to match the Settlement file on both OPEID and Facility code Id so that the caution flags are displayed appropriately.

## Assumptions:
1. This story allows for the display of the following caution flags based on the data provided in the most recent production settlement file.
    - The Caution Flag "States Attorney General Filed Suit for Deceptive Action" received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
        - Title: State’s Attorney General filed suit for deceptive action
        - Description: The state’s Attorney General filed suit against this school for deceptive action. VA may suspend benefits to this school.
    - The Caution Flag "Settlement reached with States Attorney General" received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
        - Title: Settlement reached with state’s Attorney General
        - Description: The state's Attorney General has reached a settlement with this school.

## Acceptance Criteria
1. The settlement file data is included in the GIDS version data when ONE OF the following conditions are met:
    a. The settlement unitid column matches the institutions iped column
    b. The settlement unitid column matches the institutions facility code column

## Supporting Artifacts:
1. [Settlement_06042020.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4736108/Settlement_06042020.txt) - CSV renamed to text to upload into github.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/670

**Comment by delli-gatti-michael** [comment]
Confirmed in Staging. Closing this issue
