### ISSUE TITLE
Update Spotlight links

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#98582]
### User story

As a Veteran, I want the Spotlight articles to be refreshed monthly, so that I feel my experience is curated for me.

### Notes
Tips for Creating Your Login.gov or ID.me Account – https://www.myhealth.va.gov/mhv-portal-web/ss20241209-tips-creating-login-gov-id-me-account

5 Morning Routines to Reduce Stress – https://www.myhealth.va.gov/mhv-portal-web/ss20220719-start-your-day-with-mindfulness

Give Your Immune System a Boost – https://www.myhealth.va.gov/mhv-portal-web/ss20220803-your-body-defense-system

Possible tasks:
- 

## Acceptance criteria

- Spotlight links updated on MHV landing page
- QA review

**Comment by kjsuarez** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33592)

**Comment by allanto-ah** [comment]
Environment: Staging

Verified the spotlight links have been updated to the new ones in the Description

<img width="1349" alt="Image" src="https://github.com/user-attachments/assets/ce8a69f0-2bea-4afc-b737-8ceab2d356b4" />
