### ISSUE TITLE
Add link on DIC page to Agent Orange page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#986]
## User Story
As a family member survivor of a Vietnam Veteran, I need to be made aware of the new Blue Water Navy Vietnam law, so I know that I might be eligible for DIC benefits_.

Add link on DIC page to Agent Orange exposure on Navy or Coast Guard ships page. 

Reason for stakeholder request: survivors of Blue Water Navy Veterans are now eligible for compensation, as part of a new court decision and law. 

- On this page: https://www.va.gov/burials-memorials/dependency-indemnity-compensation/
- Add a link to this page: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/

This information is currently missing on the DIC page; and is not easy to navigate to because DIC is currently in the burials benefit hub (which we are separately working on addressing - moving to Disability or Pension - this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/556 ). 

@peggygannon and @Karak888 for awareness. 

@peggygannon - since this page is i think in content freeze, let's sync on workaround and/or ETA. I can provide draft language.

**Comment by peggygannon** [comment]
@jenniferlee-dsva OK, thanks for the heads up. I think we have two options:
--We can add the language/link on the live burials page now and then make a note to add that info to the page in the CMS once burials is migrated. 
OR
--since we're migrating burials from a heroku instance, I can see if there is any flexibility on adding "content" to the heroku instance if it hasn't been migrated yet. I'd need to check with Beth J. 

Let me know if you have a preference for one of the options? If we decide to update live site now, we could create a Zenhub issue to track this content that needs to be pulled into during UAT (post-migration).

**Comment by jenniferlee-dsva** [comment]
@peggygannon - per convo, let's do option 2 and I'll create another issue to manually make same change in Drupal when this page comes out of CMS freeze. 

@RLHecht  or @AnneHurley  - depending on your bandwidth, could one of you make this change in Github and then pull in Peggy for final review. SME (Angie Smith) is reviewing draft text now and I'll upload it here when she okays.

**Comment by jenniferlee-dsva** [comment]
Ticket to track post-CMS migration: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1008

**Comment by RLHecht** [comment]
@jenniferlee-dsva I can make the change in Github. Just let me know when you have the copy.

**Comment by AnneHurley** [comment]
I'll write the copy later this afternoon or in the morning and will keep you posted. thanks.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley 
Approved alert text - but pending final PDF that we need to link to. Will upload PDF here or provide the pdf URL when Angie Smith sends. 

**[info-icon] DIC eligibility for survivors of Blue Water Navy Vietnam Veterans**

Veterans who served on a Blue Water Navy vessel offshore of the Republic of Vietnam, or on another U.S. Navy or Coast Guard ship operating in the coastal waterways of Vietnam between January 9, 1962, and May 7, 1975, are now entitled to a presumption of service connection for illnesses related to Agent Orange exposure. This is a result of Public Law 116-23, the Blue Water Navy Vietnam Veterans Act of 2019.  

**What this means for you as a survivor**
If we denied your Blue Water Navy Veteran’s service-connected disability claim in the past, you may be eligible for DIC benefits based on this change in law. 

Download the FAQs about how the new law may affect your DIC eligibility (PDF) **[LINK TO APPROVED PDF - TBD]**
Learn about the new law and how to file a claim if you're a Veteran **[https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/]**

**Comment by AnneHurley** [comment]
Yes I will do this and Randi will peek over my shoulder. Starting now.

[image: GovernmentCIO] <http://www.governmentcio.com/>
Anne Hurley
Content Writer
| *mobile* (503) 298-7203
| *e.* ahurley@governmentcio.com
*Government*CIO
website <https://www.governmentcio.com/> | media
<https://governmentciomedia.com/> | services
<https://www.governmentcio.com/services> | jobs
<https://careers-governmentcio.icims.com/> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMedia> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos> [image: Instagram]
<https://www.instagram.com/gciotalent>
*Confidentiality Note: * This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.

**Comment by AnneHurley** [comment]
@peggygannon  @jenniferlee-dsva  This is ready for review by one or both of you. Then a procedural question - Peggy, I'm assuming you'll merge it to publish after that review, and then update the ZenHub board to show this is complete? Let me know - I can do that part as well but just have not as of yet. I promised Adam I would get it done for this sprint :)
Thanks to @RLHecht  for code mastery.

**Comment by AnneHurley** [comment]
@peggygannon  Ready for you to publish - thank you! @jenniferlee-dsva  your last fix has been made. Thanks much.

**Comment by peggygannon** [comment]
thanks, @AnneHurley Can you add me as reviewer to the PR? this will allow me to review/publish this PR.

**Comment by AnneHurley** [comment]
@peggygannon I couldn't add you as a reviewer but added you as an assignee. I see some copy issues though that I need to go in and fix. Apologies for the delay - had 2 back to back doc appts today.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley @peggygannon - I'm so sorry. We looked at this 20 times and I don't know how I missed this, but the alert header is missing "Vietnam"! 

[info-icon] DIC eligibility for survivors of Blue Water Navy **Vietnam** Veterans 

It's important to call that out in the header because not all survivors will know/remember if their Veteran served on a "Blue Water Navy" vessel, but they all know if their Veteran was a Vietnam veteran. Could we get this added for Monday's deploy?
