### ISSUE TITLE
508-defect-1 ❗ Launchblocker [SEMANTIC MARKUP]: <dt> and <dd> elements MUST be contained by a <dl> (Step pages)

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9862]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

> Note: This may not be a defect-1, I'm not sure, and would want Trevor to review. The markup isn't valid, but I don't know what the impact would be on a user.

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The semantic markup structure of a description list (`<dl>`) must have proper structure. If there are `<dt>` and `<dd>` elements, they must be contained by a `<dl>`.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I need semantic markup in order to have correct context for the content.

## Environment

* Operating System: all
* Browser: all
* Server destination: staging

## Steps to Recreate

1. Enter https://staging.va.gov/hearing-aid-batteries-and-accessories/veteran-information/addresses in browser, logged in as user 1
2. Run an axe scan
3. Verify this error appears.

## Possible Fixes (optional)

Remove the `<dd>` element wrapping the `<p>` element.

### Current code
```diff
<div class="address-page">
    <h3 class="vads-u-font-size--h4">Shipping address</h3>
!   <dd class="vads-u-margin-top--2">
        <p>We'll ship your order to the address below. Orders typically arrive within 7 to 10 business days.</p>
!   </dd>
    <p class="vads-u-font-weight--bold">Select the address where you'd like to send your order: <span class="vads-u-font-weight--normal schemaform-required-span">(*Required)</span></p>
    <div class="review-card vads-u-margin-bottom--2 vads-u-background-color--gray-lightest vads-u-border-color--primary vads-u-border--3px">
        <div class="review-card--header vads-u-display--flex vads-u-justify-content--space-between vads-u-align-items--center vads-u-padding-top--3 vads-u-padding-x--3 vads-u-padding-bottom--2" style="min-height: 5rem;">
            <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">Permanent address</h4>
        </div>
```

### Recommended code
```diff
<div class="address-page">
    <h3 class="vads-u-font-size--h4">Shipping address</h3>
        <p>We'll ship your order to the address below. Orders typically arrive within 7 to 10 business days.</p>
    <p class="vads-u-font-weight--bold">Select the address where you'd like to send your order: <span class="vads-u-font-weight--normal schemaform-required-span">(*Required)</span></p>
    <div class="review-card vads-u-margin-bottom--2 vads-u-background-color--gray-lightest vads-u-border-color--primary vads-u-border--3px">
        <div class="review-card--header vads-u-display--flex vads-u-justify-content--space-between vads-u-align-items--center vads-u-padding-top--3 vads-u-padding-x--3 vads-u-padding-bottom--2" style="min-height: 5rem;">
            <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">Permanent address</h4>
        </div>
```

## WCAG or Vendor Guidance (optional)

* [`<dt>` and `<dd>` elements must be contained by a `<dl>`](https://dequeuniversity.com/rules/axe/3.5/dlitem?application=AxeChrome)

## Screenshots or Trace Logs

![Screen Shot 2020-06-04 at 5 53 08 PM](https://user-images.githubusercontent.com/57469/83814275-998cdf80-a68c-11ea-9d00-cb6100a63482.png)

**Comment by bradl3yC** [comment]
@jenstrickland I forgot to tag you in this - this is ready to validate

**Comment by jenstrickland** [comment]
Validated. 🕺
