### ISSUE TITLE
Add row to table in research labels doc

### ISSUE THREAD

**Issue by beckyphung** [department-of-veterans-affairs/va.gov-team#98642]
### Description
Could we add another row in the types of labels table for:
- DST, Design System Template, #006B75

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/research-design/adding-labels-in-the-research-repository#Addinglabelsintheresearchrepository-types-of-labelsTypesoflabels

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership?

**Comment by beckyphung** [comment]
This can be closed. Just had a chat with Matt about this. We don't need a DST label.

**Comment by jknipes** [comment]
Hi @beckyphung , thanks for your content suggestions. The Platform Content team will review your request and put it in our backlog to refine for next steps.

**Comment by jknipes** [comment]
Closing ticket per previous comment from author
