### ISSUE TITLE
Flipper UI access for Vitalii Menshutin

### ISSUE THREAD

**Issue by vmenshutin-bylight** [department-of-veterans-affairs/va.gov-team#98656]
### Your Name

Vitalii Menshutin 

### Your GitHub handle (Flipper UI access is managed through GitHub)

vmenshutin-bylight

### Team, Role, and Company of the target individual

MHV Medications, Technical Lead, ByLight

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [x] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I will be responsible for flipping toggles in PROD (and lesser environments) from my team

**Comment by AnthonyWFlowers** [comment]
@vmenshutin-bylight You've been granted access to production and lesser environments.
