### ISSUE TITLE
CT: Remove prod flag for COVID Notification

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9868]
As a developer, I need to remove the prod flag for the COVID notification so that it is available in the production environment.

## Assumptions:
1. Functionality approved by EDU on staging as of 06/05/20.

## Acceptance Criteria
1. The functionality developed in #9257 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12980

**Comment by delli-gatti-michael** [comment]
This is now on Production. Closing this issue
