### ISSUE TITLE
Implement POA Request Detail API Endpoint

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#98709]
### Description
Replace the current mock data implementation with one that serializes the result of a [pundit-scoped](https://github.com/varvet/pundit?tab=readme-ov-file#scopes) POA request DB query.

#### Implementation Details
Outcomes:
- 200
- 404
- 401
- Probably no 403 for security (don't reveal the existence of a POA request that the user is not authorized to act on when guessing ID)

Include POA request with its extended object graph:
- Claimant
- Veteran
- POA holder membership
  - Accredited individual
  - POA holder
- Resolution
- Authorizations

#### Blockers
POA holder membership data model hasn't been modeled yet.

### Acceptance Criteria/Conditions of Satisfaction
- [ ] See real DB data surfaced in API response

#### Automated Testing
- [ ] Request spec for the above status code outcomes

**Comment by ojbucao** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/19967
