### ISSUE TITLE
Implement POA Request List API Endpoint

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#98710]
### Description
`/power_of_attorney_requests`
Replace the current mock data implement with one that serializes the result of a [pundit-scoped](https://github.com/varvet/pundit?tab=readme-ov-file#scopes) POA requests DB query

#### Implementation Details
Outcomes:
- 200
- 401

Include POA request with its extended object graph (for now rather than bothering with a shallow serializer):
- Claimant
- Veteran
- ~POA holder membership~
  - ~Accredited individual~
  - ~POA holder~
- Resolution
- Authorizations

#### Blockers
POA holder membership data model hasn't been modeled yet.

### Acceptance Criteria/Conditions of Satisfaction
- [ ] See real DB data surfaced in API response

#### Automated Testing
- [ ] Request spec for the above status code outcomes

**Comment by ojbucao** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/19967
