### ISSUE TITLE
CT: Mobile "I'll be taking classes outside of the U.S. and U.S. territories" not selectable

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9872]
On mobile view, the checkbox "I'll be taking classes outside of the U.S. and U.S. territories" is not selectable.

Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11929140 on your phone, and try and select the checkbox for "I'll be taking classes outside of the U.S. and U.S. territories"

![Screen Shot 2020-06-05 at 1.29.07 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4cd01404-36a6-4df9-b958-9594e17f1c13)

**Comment by zurbergram** [comment]
when clicking the checkbox getting below in console
![Screen Shot 2020-06-05 at 2 13 54 PM](https://user-images.githubusercontent.com/1094999/83909467-d7ded900-a736-11ea-936d-dacb86c8dcdb.png)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12981

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-05 at 3.34.34 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/22836bfd-6f6c-4b1e-96d1-fc5e666d4bfd)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by ccruzgra** [comment]
UXers took a look and this checks out!

**Comment by sonntag-adam** [comment]
Closing bug.
