### ISSUE TITLE
AWS access for [Josh Houston]

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#98730]
### COR Name

Laurene "Reney" Cook

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Josh Houston

### Your Email

josh.houston@bylight.com

### Team, Role, and Company of the target individual

Identity, Devops Engineer, by light

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghi@va.gov

### Desired AWS Access

I need permissions to start ssm sessions in order to troubleshoot forward proxy instances. We provide certificates to the forward proxy that need to be verified/confirmed from time-to-time. I currently only need perms for LOWER environments.

Account I need permissions in: 008577686731
Iam username: Josh.Houston
permission needed: ssm:StartSession

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

Eqip transmittal date confirmed in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63945

### Additional Notes

I am making this on behalf of Josh Houston, he is out this week but is another DevOps engineer on the same team as me. His needs the exact same permissions as I do in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98728

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
@department-of-veterans-affairs/operations-aws-approvers  We will need approval for this ticket. @jhouston0  already has prod access for SSM, with _ssm:startsession_, however, the forward proxy tag/deployment name is not part of the resources with SSM access as seen in the attached image. If granted, we will add a forward proxy deployment name/ tag to the condition block in that attached image.                                                                                                                      ![Image](https://github.com/user-attachments/assets/042d5c5d-5b53-40a2-97c8-51ed01d3bade)

**Comment by JonathanKamensDVA** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/98728#issuecomment-2532760567

**Comment by Efe-Oddball** [comment]
@JonathanKamensDVA That was my error, I thought SSM:startsession was only defined within he VagovSSMprodEnvironmentAccess policy but going back to the code I have found the policy for the Lower environments. I will take it from here.
Thank you!

**Comment by Efe-Oddball** [comment]
Access Granted!
