### ISSUE TITLE
AWS access for Micah Chiang

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#98746]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Micah Chiang

### Your Email

micah@adhocteam.us

### Team, Role, and Company of the target individual

VSP Design System, Engineering Lead, Ad Hoc

### Product Manager (PM) name and email

Carol Wong, Carol.Wong@oddball.io

### Product Owner (PO) name and email

Matthew Dingee, matthew.dingee@va.gov

### Desired AWS Access

Please copy permissions from Kerry Powell

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Image](https://github.com/user-attachments/assets/f6640aaf-fdc3-4ebc-a589-ecc63cd83bd8)

This is the only one I have and it's from over 5 years ago when I was on a contract where GovCIO was the prime. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
@micahchiang It does not look like you have any AWS access. You will have to create an AWS access ticket or modify this ticket for AWS access

**Comment by micahchiang** [comment]
@Efe-Oddball - Yes, that's what this ticket is for, requesting AWS access. Can you tell me what needs to be changed? My PIV expiration date is May 12 2027, if that helps.

**Comment by Efe-Oddball** [comment]
@micahchiang I think we are good! I will make the modifications to the ticket myself and grant the request. Thanks for the swift response

**Comment by Efe-Oddball** [comment]
Access granted and temporary credentials have been passed to the user via keybase
