### ISSUE TITLE
STEM: Integrate all form Chapters

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9878]
As a developer, I need to link all chapters of the form workflow so that the form can be submitted successfully.

## Assumptions:
1. This work is done behind feature flag #7271.
2. The "Education benefit eligibility" grey panel is out of scope for this story.
3. The casing of the Review Application is not to be changed as part of this story if it impacts other forms.

## Acceptance Criteria
1. The title of the form is: "Apply for the Rogers STEM Scholarship"
2. There form chapters are navigated in the following order:
    a. 1 of 6 Applicant Information
    b. 2 of 6 Education Benefit
    c. 3 of 6 Program Details
    d. 4 of 6 Military Details
    e. 5 of 6 Personal Information
    f. 6 of 6 Review Application
3. The Review Application section displays a summary of the applicants answers grouped by chapter
    a. The "Rogers STEM Scholarship eligibility summary" is ONLY displayed when the applicant has answered the "Would you still like to apply and let us determine your eligibility?" question.
4. The Review Application section displays the following required question: I have read and accept the privacy policy
5. The layout of the content in AC 1-4 matches that as specified in Supporting Artifact # 2.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040907) as of 07/01
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ac00ddfc52dd101577639d5bdcf25a720a029fbf/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#form-title-apply-for-the-rogers-stem-scholarship-10) as of 07/01
3. [10203-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4805097/10203-Fields.xlsx)

**Comment by hughes-dustin** [comment]
branch: bah-9878
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13386

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-07 at 12.14.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e69a48ae-0126-4ddb-82e3-570bb52bc6ec)
##
![Screen Shot 2020-07-07 at 12.14.59 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/35d0aa25-5be7-4c5d-a566-cfd30458dbdc)
##
![Screen Shot 2020-07-07 at 12.15.05 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9264ba6b-4578-4807-8540-1596c458f8bb)
##
![Screen Shot 2020-07-07 at 12.15.15 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ab447e88-c0f0-4e87-849c-1c33e71394b6)
##
![Screen Shot 2020-07-07 at 12.15.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6154dc22-9f05-4123-b3f1-6c2202367393)
##
![Screen Shot 2020-07-07 at 12.15.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c6775fec-6c5b-4482-ae36-d16143f99446)
##
![Screen Shot 2020-07-07 at 12.15.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b3622478-7662-44fa-9003-571a62348beb)
##
![Screen Shot 2020-07-07 at 12.15.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/184c999c-3d07-4229-9d98-cd3bfbb618fc)
##
![Screen Shot 2020-07-07 at 12.15.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3639f6a7-0883-42a1-a2fb-b0551eb074d5)
##
![Screen Shot 2020-07-07 at 12.20.15 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e00d8d90-c306-4e28-a49b-5d395d1b7452)
##
![Screen Shot 2020-07-07 at 12.20.40 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a9c1695f-6a1c-469f-9ffd-37326628145b)
##
![Screen Shot 2020-07-07 at 12.22.18 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6fd6ed9d-1957-44ca-a1ec-e41ee2edec82)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-07 at 12.14.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c8df97d6-d30e-4b7d-933b-6d0e98170a0d)

**Comment by sonntag-adam** [comment]
<img width="761" alt="Screen Shot 2020-07-07 at 12 14 52 PM" src="https://user-images.githubusercontent.com/48804582/86812445-0826d980-c04d-11ea-96a8-05a40a4afd3a.png">
##
<img width="712" alt="Screen Shot 2020-07-07 at 12 14 59 PM" src="https://user-images.githubusercontent.com/48804582/86812457-0bba6080-c04d-11ea-8553-3f3aeb2761c7.png">
##
<img width="801" alt="Screen Shot 2020-07-07 at 12 15 05 PM" src="https://user-images.githubusercontent.com/48804582/86812469-0f4de780-c04d-11ea-9e5c-551b364afa6a.png">
##
<img width="777" alt="Screen Shot 2020-07-07 at 12 15 15 PM" src="https://user-images.githubusercontent.com/48804582/86812480-14129b80-c04d-11ea-9c00-751ac9fb1f78.png">
##
<img width="827" alt="Screen Shot 2020-07-07 at 12 15 21 PM" src="https://user-images.githubusercontent.com/48804582/86812505-183eb900-c04d-11ea-872d-2a67c3b573c4.png">
##
<img width="716" alt="Screen Shot 2020-07-07 at 12 15 28 PM" src="https://user-images.githubusercontent.com/48804582/86812536-1ecd3080-c04d-11ea-9c7e-2ad886ef29b4.png">
##
<img width="806" alt="Screen Shot 2020-07-07 at 12 15 36 PM" src="https://user-images.githubusercontent.com/48804582/86812550-22f94e00-c04d-11ea-9b5a-994b8e06a86f.png">
##
<img width="746" alt="Screen Shot 2020-07-07 at 12 15 44 PM" src="https://user-images.githubusercontent.com/48804582/86812571-2a205c00-c04d-11ea-98b7-a5565ae873e7.png">
##
<img width="841" alt="Screen Shot 2020-07-07 at 12 15 52 PM" src="https://user-images.githubusercontent.com/48804582/86812588-2f7da680-c04d-11ea-94c9-5c91932857f4.png">
##
<img width="836" alt="Screen Shot 2020-07-07 at 12 20 15 PM" src="https://user-images.githubusercontent.com/48804582/86812608-33112d80-c04d-11ea-97f4-7f4b0afa1247.png">
##
<img width="772" alt="Screen Shot 2020-07-07 at 12 20 40 PM" src="https://user-images.githubusercontent.com/48804582/86812639-39070e80-c04d-11ea-8a8a-0acbc1317425.png">
##
<img width="894" alt="Screen Shot 2020-07-07 at 12 22 18 PM" src="https://user-images.githubusercontent.com/48804582/86812653-3efcef80-c04d-11ea-91ae-25a50dca8d1f.png">

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9318&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this looks good!

**Comment by sonntag-adam** [comment]
Closing out story.
