### ISSUE TITLE
On this page jump links - text reflows onto two lines on page zoom

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#9879]
## What happened?
when viewing the [Work with us page](https://www.va.gov/pittsburgh-health-care/work-with-us/) on Pittsburgh, when a user zooms to 90% or 110%, the jump link "Jobs and careers" breaks onto two lines:
![image](https://user-images.githubusercontent.com/12564977/83909233-6acb4380-a736-11ea-8a81-ce6c9f94ebd4.png)
 

## Specs:
- Device: Macbook
- Browser: Chrome

## Steps to Reproduce
- URL: https://www.va.gov/pittsburgh-health-care/work-with-us/
- Zoom to 110% or 90% in browser

## Desired behavior
"Jobs and careers" should not break onto two lines (the rest of the jump links don't seem to be afffected by this bug, if that helps)

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Looks good!!
