### ISSUE TITLE
[Analytics] Add Benefits data to V1 Product Health MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#988]
## User Story
As a Benefits decision maker, I need Google Analytics for my forms on the Product Health MVP so I can see my product's health at a glance.

## Goal
Add additional benefits Google Analytics data to V1 of the product health MVP.

## Acceptance Criteria
- [ ] Add the following Google Analytics benefits data to the product health MVP:
    - [x] Disability Increase 526EZ
    - [x] Pension Application 527EZ
    - [x] Burial 530
    - [x] Burial Pre-Need Authorization 40-10007
- [ ] _Stretch_: Automate Claims data to product health MVP

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

CC: @amycesal for design verification.

**Comment by nedierecel** [comment]
@joanneesteban @jonwehausen I updated the products to include all Health Care application events and goal starts/completions.

@amycesal - These changes are ready in the latest version of the Google Sheet.
