### ISSUE TITLE
Update calendar page to include the clinic name

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#98807]
## Description
Update calendar page to include the clinic name in the DS VistA flow. 

New content:
Scheduling at [Clinic name]
Times are displayed in Eastern Time (ET).

Design:

![Image](https://github.com/user-attachments/assets/7a7389ef-06df-4dc8-a0d7-7a2800a84c22)

Background: 
This is to be consistent with the OH flow where we added the provider name to the calendar page. In the subtext we have  "Scheduling with [Provider name]
Times are displayed in Eastern Time (ET). "
[For reference here is an example of this](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=6437-42231&node-type=instance&t=oCecRcJuQw3olbws-11)

[Collab cycle ticket initiating this work](https://github.com/orgs/department-of-veterans-affairs/projects/1214/views/9?pane=issue&itemId=87446015&issue=department-of-veterans-affairs%7Cva.gov-team%7C97271)

---

## Development Checklist

- [ ] Update content

### Design Assets
[ Figma file](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2500-13278&node-type=section&m=dev)

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by JunTaoLuo** [comment]
@melissa-lefevre this is ready for validation.

**Comment by melissa-lefevre** [comment]
Looks great. No issues.
