### ISSUE TITLE
STEM - VSP Content Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9884]
Incorporate content update from VSP review, 9680 into content doc

**Comment by amyknox** [comment]
Mural with VSP update recs
https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1592335147361/2715656def9fbf6a239ef2d2ae6d6be81fb89a53

**Comment by ccruzgra** [comment]
Adding updates to Github content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md

**Comment by ccruzgra** [comment]
All VSP updates are now in content doc.
