### ISSUE TITLE
CF: Analytics / KPI review for post-launch	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9885]

**Comment by amyknox** [comment]
Tracking general, aggregate use of the caution flag jumplink at the top of profile pages

Tracking aggregated clicks out of the Comparison Tool on the external links in the “Cautionary information” accordion

Per Jon at VSP (#6876)
1. Putting direct tracking on the 'View cautionary information about this school' link click at the top to signify the user jumped inside the "Cautionary Information" accordion . 
2. For the embedded links within the "Cautionary Information" accordion, we can certainly get tracking on these as well

**Comment by amyknox** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/caution-flags/CFreleasePlan.md#post-launch-questions

**Comment by amyknox** [comment]
#2. Qualitative input from Usability Testing, conducted March 2020
- Caution flags alert Veterans to potential issues with schools and frequently act as a deterrent to further investigating flagged schools.
- Users immediately notice schools with Caution Flags on Comparison Tool’s search results page.
- The more specific caution flag content is on the search results page, the better deterrent it seems to be against users clicking through to the school’s profile page.  Caution flags with less specific language pique curiosity and may cause users to click through to investigate further.

**Comment by amyknox** [comment]
Juries out based on page views.  Overall traffic to GIBCT is down about 22% in May 2020 compared to May 2019.  Traffic to MOST flagged pages is down. Decreases for sample schools range from to a 12% increase to 100% decrease in traffic. Most sample schools have 60-95% decrease.  However, other schools, that previously had caution flags and don't as of today, have similar decreases so it's really difficult to tell at this time. 

[https://app.zenhub.com/files/133843125/4e395422-50c5-4805-a590-b95fa17f244f/download](https://app.zenhub.com/files/133843125/4e395422-50c5-4805-a590-b95fa17f244f/download)

**Comment by amyknox** [comment]
Working with Jon & Brian at VSP to get a tally of the click thrus

**Comment by amyknox** [comment]
Use of jump link at the top of the profile page and Learn more about [CF link to external site] are accessible via [this Google Analytics link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20200423&_u.date01=20200611&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventLabel:nav-warning-alert-box-content-link-click&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-table.rowStart=0/).  

Tracking started April 23, 2020.  For more info, add "Page Title" as a secondary dimension to see which pages have the highest number of clicks on the Caution Flag alerts.
