### ISSUE TITLE
Landing Page: Update custom access/verification alerts with latest content

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#98854]
## Description

The account access and verification alerts content has been updated again, and should be updated to reflect the most accurate version. With the VADS components held up, we need to update the custom alerts again.

### User story

As a Veteran who did not sign in with an ID-verified ID.me or Login.gov credential, I want the clearest possible instructions for how to improve my credentials, so that I can continue accessing VA.gov after Jan 31, 2025.

As a Cartography team member, I want to update the content in our custom account-related alerts with the new VADS-approved content as a stop-gap until the VADS components are available, so that we are communicating the current state to Veterans in the clearest and most accurate language possible. 

### Notes
- Source of truth for [content is here](https://design.va.gov/components/alert/alert-sign-in/)
- per Sara, prioritize updating our MHV Basic "Register" alert since it's very long
- Follow on from https://github.com/department-of-veterans-affairs/va.gov-team/issues/96243

Possible tasks:
- 

## Acceptance criteria

- Alerts have been updated
  - [ ] "Verify" – Login.gov acct
  - [ ] "Verify" – ID.me acct
  - [ ] "Sign in with a different credential" for MHV Basic accts
- QA review

**Comment by allanto-ah** [comment]
Environment: Staging

Alerts have been changed. Example below:

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/456439af-555d-4746-a7a0-8e63f4b7373a" />
<img width="1072" alt="Image" src="https://github.com/user-attachments/assets/c09817ef-299c-459a-b7d9-40ef2ade6930" />
