### ISSUE TITLE
STEM - VSP Prototype Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9886]
Incorporate content update from VSP review, 9680 into prototype

**Comment by ccruzgra** [comment]
Collected Peggy's comments here and have now updated the prototype: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1592335147361/2715656def9fbf6a239ef2d2ae6d6be81fb89a53
