### ISSUE TITLE
Create VAOS user service and configuration

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#989]
**User Story**: As a developer I want to connect to the VAOS service so I can create endpoints for vets-website to consume

**Acceptance Criteria**: Service and Configuration classes exist in a VAOS Rails Engine module on vets-api.

**Comment by markgreenburg** [comment]
@kreek not sure if this issue is a dupe; believe most of this work is either done or split into individual issues for the endpoints that need to be created. Feel free to close or refine as you see fit.

**Comment by markgreenburg** [comment]
user service integration work blocked by devops work but that should be taken care of this sprint.
