### ISSUE TITLE
STEM:  Prioritized findings for Development

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9891]
Prioritize list of updates to UI's Review @ UXBA Sync & Incorporate input

**Comment by ccruzgra** [comment]
Location of UX recommendations: https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/_layouts/15/Doc.aspx?sourcedoc=%7B49B40C72-C0A4-4257-A5B6-14067610AE87%7D&file=STEM-10203-Testing-UX-Recommendations.xlsx&action=default&mobileredirect=true
