### ISSUE TITLE
[URGENT] Undo redirects for historical rates pages

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#9893]
## Issue Description
We have an urgent/timely request, to undo redirects that have been put in place, so that they can go live on June 8th, 2020.

---
## Tasks

Please undo the redirects for these pages: 

**First chunk**
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2015.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2014.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2013.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2012.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2011.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2009.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2008.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2007.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2006.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2005.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2004.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2003.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2002.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2001.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2000.asp 
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_1999.asp 

**Note: DON'T do anything with these (leave as is with redirects):**
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2019.asp
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2018.asp

**Second chunk**
https://www.benefits.va.gov/COMPENSATION/resources_comp0214.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0213.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0212.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0211.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0209.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0208.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0207.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0206.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0205.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0204.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0203.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0202.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0201.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0200.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0299.asp 

**Note: DON'T do anything with these (leave as is with redirects):**
https://www.benefits.va.gov/COMPENSATION/resources_comp02.asp 
https://www.benefits.va.gov/COMPENSATION/resources_comp0218.asp 

**Third chunk**
https://www.benefits.va.gov/COMPENSATION/sb2014.asp 
https://www.benefits.va.gov/COMPENSATION/sb2013.asp 
https://www.benefits.va.gov/COMPENSATION/sb2012.asp 
https://www.benefits.va.gov/COMPENSATION/sb2011.asp

**Note: DON'T do anything with these (leave as is with redirects):**
https://www.benefits.va.gov/compensation/sb2019.asp 
https://www.benefits.va.gov/COMPENSATION/sb2018.asp 

**Additional chunk**
https://www.benefits.va.gov/compensation/resources_comp0114.asp
https://www.benefits.va.gov/compensation/resources_comp0113.asp
https://www.benefits.va.gov/compensation/resources_comp0112.asp
https://www.benefits.va.gov/compensation/resources_comp0111.asp
https://www.benefits.va.gov/compensation/resources_comp0109.asp
https://www.benefits.va.gov/compensation/resources_comp0108.asp
https://www.benefits.va.gov/compensation/resources_comp0107.asp
https://www.benefits.va.gov/compensation/resources_comp0106.asp
https://www.benefits.va.gov/compensation/resources_comp0105.asp
https://www.benefits.va.gov/compensation/resources_comp0104.asp
https://www.benefits.va.gov/compensation/resources_comp0103.asp
https://www.benefits.va.gov/compensation/resources_comp0102.asp
https://www.benefits.va.gov/compensation/resources_comp0101.asp
https://www.benefits.va.gov/compensation/resources_comp0100.asp
https://www.benefits.va.gov/compensation/resources_comp0199.asp

https://www.benefits.va.gov/compensation/rates-index.asp

https://www.benefits.va.gov/COMPENSATION/sb2009.asp
https://www.benefits.va.gov/COMPENSATION/sb2008.asp
https://www.benefits.va.gov/COMPENSATION/sb2007.asp
https://www.benefits.va.gov/COMPENSATION/sb2006.asp
https://www.benefits.va.gov/COMPENSATION/sb2005.asp
https://www.benefits.va.gov/COMPENSATION/sb2004.asp
https://www.benefits.va.gov/COMPENSATION/sb2003.asp
https://www.benefits.va.gov/COMPENSATION/sb2002.asp
https://www.benefits.va.gov/COMPENSATION/sb2001.asp
https://www.benefits.va.gov/COMPENSATION/sb2000.asp
https://www.benefits.va.gov/COMPENSATION/sb1999.asp

## Acceptance Criteria
- [ ] This removal of redirects allows claims staff to access the historical rates info they need without affecting our modernized Veteran-facing experience.
---

**Comment by bethpottsVADEPO** [comment]
@ncksllvn @kelsonic Could you assign back to me to validate before you push this? I want to make sure there were no copy/paste errors either with the original list or with the list I created in this ticket. I'll check each of the links.

**Comment by bethpottsVADEPO** [comment]
@kelsonic  When I click on the links above, I'm still getting redirects to the 2020 pages, which is what we wanted to undo. Any idea why?

**Comment by bethpottsVADEPO** [comment]
Let's get this into the build today, and I'll validate later today when the undo is in place.

**Comment by kelsonic** [comment]
PR is merged! Will be deployed today! 🎉

**Comment by bethpottsVADEPO** [comment]
@kelsonic Has there been a delay in the build today? Just started to check these, and the redirects aren't undone yet, it seems.

**Comment by kelsonic** [comment]
I just checked some of the redirects and they seem to be undone successfully 🙂 Which ones were not removed for you @bethpotts?

**Comment by mnorthuis** [comment]
@bethpotts Are you also reverting the core veteran rate redirects?  Also, why only those 4 of birth defect years?

**Comment by bethpottsVADEPO** [comment]
@kelsonic Here are the additional redirects to undo:

https://www.benefits.va.gov/compensation/resources_comp0114.asp
https://www.benefits.va.gov/compensation/resources_comp0113.asp
https://www.benefits.va.gov/compensation/resources_comp0112.asp
https://www.benefits.va.gov/compensation/resources_comp0111.asp
https://www.benefits.va.gov/compensation/resources_comp0109.asp
https://www.benefits.va.gov/compensation/resources_comp0108.asp
https://www.benefits.va.gov/compensation/resources_comp0107.asp
https://www.benefits.va.gov/compensation/resources_comp0106.asp
https://www.benefits.va.gov/compensation/resources_comp0105.asp
https://www.benefits.va.gov/compensation/resources_comp0104.asp
https://www.benefits.va.gov/compensation/resources_comp0103.asp
https://www.benefits.va.gov/compensation/resources_comp0102.asp
https://www.benefits.va.gov/compensation/resources_comp0101.asp
https://www.benefits.va.gov/compensation/resources_comp0100.asp
https://www.benefits.va.gov/compensation/resources_comp0199.asp
https://www.benefits.va.gov/compensation/rates-index.asp

https://www.benefits.va.gov/COMPENSATION/sb2009.asp
https://www.benefits.va.gov/COMPENSATION/sb2008.asp
https://www.benefits.va.gov/COMPENSATION/sb2007.asp
https://www.benefits.va.gov/COMPENSATION/sb2006.asp
https://www.benefits.va.gov/COMPENSATION/sb2005.asp
https://www.benefits.va.gov/COMPENSATION/sb2004.asp
https://www.benefits.va.gov/COMPENSATION/sb2003.asp
https://www.benefits.va.gov/COMPENSATION/sb2002.asp
https://www.benefits.va.gov/COMPENSATION/sb2001.asp
https://www.benefits.va.gov/COMPENSATION/sb2000.asp
https://www.benefits.va.gov/COMPENSATION/sb1999.asp

**Comment by kelsonic** [comment]
PR is up! 🙂 Please give this a look over and a ✅  if it looks right! https://github.com/department-of-veterans-affairs/vets-website/pull/13039/files

**Comment by bethpottsVADEPO** [comment]
@kelsonic I commented in the PR too. Looks good. Thanks!

**Comment by kelsonic** [comment]
Merged! 🎉

**Comment by mnorthuis** [comment]
I reviewed all of these, and all have now been reverted. 

I have a follow up question: originally it was decided to redirect everything to the 2020 page, however, we do have a 2019 historical rates drupal page for each of the 4 types of rates.  Can we update the redirects on the 4 legacy 2019 rates to now go to the new 2019 drupal page so users are directed to what they are looking for?
https://www.benefits.va.gov/compensation/sb2018.asp
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2018.asp
https://www.benefits.va.gov/compensation/resources_comp0218.asp
https://www.benefits.va.gov/compensation/resources_comp0118.asp (edited)

**Comment by stephorkandatx** [comment]
@bethpottsVADEPO to view @mnorthuis request above

**Comment by bethpottsVADEPO** [comment]
@mnorthuis I'd like to discuss that with Jen, especially since we'll be creating a 2018 modern rates page for each section. Then we'd have two opportunities to 1:1 redirect from teamsite to 2019 and 2018. I'll circle back here after that convo.

**Comment by stephorkandatx** [comment]
@bethpottsVADEPO when you have time in the next day or two, this ticket is ready for final validation/to be closed. I would love to run this through you due to the discussions around undoing redirects. I also don't want to lose the discussion above with Mikki - if there is actionable work here I can write up separately for future work. Thank you!

**Comment by bethpottsVADEPO** [comment]
@stephorkandatx I'm closing this issue since we've done the work. I want to talk to you about creating a new handful of tickets for Anne to work through for getting the 2018 historical rates pages built in drupal across disability and any other benefits sections that need it. Jen Lee and I have discussed that and would like to proceed.
