### ISSUE TITLE
AWS access for Nichelous Herndon (Access Renewal 2024-12)

### ISSUE THREAD

**Issue by nichelous-herndon** [department-of-veterans-affairs/va.gov-team#98942]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Nichelous Herndon

### Your Email

nichelous.herndon@va.gov

### Team, Role, and Company of the target individual

VA Chatbot, Software Engineer Consultant, Thoughtworks

### Product Manager (PM) name and email

Christina Schuler christina.schuler@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais luciana.morais@va.gov

### Desired AWS Access

I need read/write access to dsva-vagov/va-virtual-agent space in AWS parameter store.

### Access Expiration

December 11, 2025

### E-QIP Transmittal Confirmation

From previous AWS Access Request Ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/62888):

"Contacted Lovejoy and confirmed E-QIP Transmission on 07/17/2023/"

### Additional Notes

I need read/write access to dsva-vagov/va-virtual-agent space in AWS parameter store.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
@nichelous-herndon your expiration says _December 11, 2025_ Do you mean 2024?

**Comment by Efe-Oddball** [comment]
@department-of-veterans-affairs/operations-aws-approvers  This user is in need of a renewal. See the [old ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62888)

**Comment by nichelous-herndon** [comment]
> [@nichelous-herndon](https://github.com/nichelous-herndon) your expiration says _December 11, 2025_ Do you mean 2024?

@Efe-Oddball I set it for 1 year from now. Yes I'd like it to last until at least Dec 11, 2025 if possible.

**Comment by JonathanKamensDVA** [comment]
We do not typically grant access for longer than six months at a time. We will ask you shortly before your access expires if it needs to be renewed.

**Comment by nichelous-herndon** [comment]
> We do not typically grant access for longer than six months at a time. We will ask you shortly before your access expires if it needs to be renewed.

6 months is fine. @JonathanKamensDVA
