### ISSUE TITLE
AWS access for Alexander Person (Access Renewal)

### ISSUE THREAD

**Issue by alexperson-tw** [department-of-veterans-affairs/va.gov-team#98943]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Alexander Person

### Your Email

alexander.person@va.gov

### Team, Role, and Company of the target individual

Chatbot Platform Team, Software Engineer Consultant, Thoughtworks

### Product Manager (PM) name and email

Christina Schuler christina.schuler@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais luciana.morais@va.gov

### Desired AWS Access

I need read/write access to dsva-vagov/va-virtual-agent space in AWS parameter store.

### Access Expiration

Jan 05, 2025

### E-QIP Transmittal Confirmation

<img width="815" alt="Image" src="https://github.com/user-attachments/assets/d5521029-01ce-4080-a70d-ed03b5b76978" />

### Additional Notes

I need read/write access to dsva-vagov/va-virtual-agent space in AWS parameter store.

I have had access at one point, however I have either forgotten the password or my access has been revoked.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
- [ ] :warning: Is production access being requested or extended? Be sure to communicate to the Tier 1 Team that they need to set a reminder for the access expiration :warning:

**Comment by Efe-Oddball** [comment]
@alexperson-tw Good morning! I do not see your name in Atlas or the Platform roster. You will have to go through this  [platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) if you have not. You will also have to reach out to your product manager to get added to the platform team roster

**Comment by alexperson-tw** [comment]
Good morning, @Efe-Oddball! I was able to find my name in Atlas. See screenshot below:

<img width="1162" alt="Image" src="https://github.com/user-attachments/assets/d18857bc-0c2a-4765-aa5f-dbb9951ec846" />

**Comment by Efe-Oddball** [comment]
@alexperson-tw  Let me look again

**Comment by Efe-Oddball** [comment]
@alexperson-tw Found you now

**Comment by Efe-Oddball** [comment]
@alexperson-tw I believe what you are looking for is a password reset to get into the console. because the IAM user does not expire, and it looks like it has been a long time since you logged in. I will go ahead and get that done for you

**Comment by Efe-Oddball** [comment]
Access Granted and temporary credentials passed to users at this time

**Comment by Efe-Oddball** [comment]
@department-of-veterans-affairs/operations-aws-approvers This user is in need of a renewal. See the [previously approved ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64706)
