### ISSUE TITLE
SOCKS access for Matthew Wright

### ISSUE THREAD

**Issue by mattwrightva** [department-of-veterans-affairs/va.gov-team#98951]
### Your Name

Matthew Wright

### Your Email

matthew.wright8@va.gov

### Your GitHub Handle

mattwrightva

### Your Role and Team

Software engineer / My HealtheVet medical records on VA.gov

### Product Manager (PM) name and email

Lichelle Bain - lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhs3oAJX4GQNBRAta9pwrDa+M+2WZuTgeeHc2eppl2h matthewwright@Matthews-MacBook-Pro.local

### SSH Key Passphrase

- [x] Please check this box to confirm that your SSH key has a strong passphrase.

### e-App (aka E-QIP) Transmittal Confirmation

<img width="1418" alt="Image" src="https://github.com/user-attachments/assets/dffd7040-3727-425e-be82-f0c029a16590" />

### Lighthouse?

- [ ] I'm on a Lighthouse team

### Platform DevOps Support - please verify the following items before merging the SOCKS PR

- [x] Work email address is listed
- [x] Valid e-QIP/e-App transmittal notice (see what qualifies as valid [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#What-Constitutes-a-Valid-e-qip-(aka-e-App)-Transmittal?))

**Comment by Efe-Oddball** [comment]
@mattwrightva  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
