### ISSUE TITLE
STEM: Update Prototype per Usability Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9896]
Update prototype to incorporate post-testing solutions
Deliver assets to BA to support creation of workable stories

**Comment by amyknox** [comment]
Location of UX recommendations: https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/_layouts/15/Doc.aspx?sourcedoc=%7B49B40C72-C0A4-4257-A5B6-14067610AE87%7D&file=STEM-10203-Testing-UX-Recommendations.xlsx&action=default&mobileredirect=true

**Comment by ccruzgra** [comment]
STEM post-test prototype v0.3, also includes VSP updates: https://bahdigital.invisionapp.com/share/JHIAE4UVKA4
