### ISSUE TITLE
STEM: Update Content doc per Usability Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9898]
Update content doc to incorporate post-test solutions 
Deliver assets to BA to support creation of workable stories

**Comment by amyknox** [comment]
Location of UX recommendations: https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/_layouts/15/Doc.aspx?sourcedoc=%7B49B40C72-C0A4-4257-A5B6-14067610AE87%7D&file=STEM-10203-Testing-UX-Recommendations.xlsx&action=default&mobileredirect=true
