### ISSUE TITLE
Staging Review finding: Update the your identification pattern

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98989]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Accredited Representation Management
**Product:** Appoint a Representative MVP
**Feature:** Appoint a Representative + Representative Status Widget

## Findings details
**VA.gov Experience Standard - issue:** [User encounters consistent, clear design components and patterns.](https://design.va.gov/about/experience-standards/#user-encounters-consistent-clear-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

When testing the your identification page, your pattern does not align with the one we currently have in the [design system](https://staging.va.gov/mock-simple-forms-patterns/ssn-pattern).

<details><summary>Link, screenshot or steps to recreate</summary>

![screen shot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/71535-allison-4.png?raw=true)

</details>

## Recommended action

Follow the design system pattern. If the user types in the VA file field, then that field should become required, not SSN. Also, I am not sure if you need service number.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** [Social security or VA file number](https://design.va.gov/patterns/ask-users-for/social-security-number)
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by oddball-lindsay** [comment]
We have defined SSN to be the only required field for this set of information ([full set of required fields for the 21-22 and 21-22a](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/required-form-fields.md)).

VA file number and Service number are requested on the forms but are not required, and we are reflecting that in this step.

**Comment by oddball-lindsay** [comment]
I just tested this and you can proceed if you clear the incorrect format for VA File Number. So the SSN truly is the only field required, and that matches what we expect in terms of required form fields.

**Comment by allison0034** [comment]
Ok, you can close, thank you!
