### ISSUE TITLE
[Discovery] Identify driven forces of Colmery/Mission Act for EDU Stakeholders

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#99]
## Description
Currently, the VSP team is not aware of the driving forces behind the Mission Act and how they influences Stakeholder decision making/prioritization

## User Story
As an EDU product owner, I need to know when how the driving forces behind the Mission Act in order to determine how they will affect my product decision making and prioritization.

## Objective
Conduct research to better understand the Mission Act's influence on edu forms on VA.gov

## AC
- [ ] Research has been conducted to gather an understanding of the Mission Act
- [ ] Research synthesis has been documented and shared with the team.

**Comment by rroueche** [comment]
This is not part of MVP, but rather a one-off request I believe, so I'm removing it from the MVP epic.

**Comment by rroueche** [comment]
@rtluu does this have to be part of current sprint, or can it wait until next sprint?

**Comment by joanneesteban** [comment]
@rroueche It's not high priority for the MVP, but will eventually help for driving forces for their deadlines and understanding their data. Moving to the next sprint.
