### ISSUE TITLE
School Ratings: Discovery Work

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9901]
Continued discovery efforts. 
Activities may include review of EDU original research, background from previous testing efforts, best practices from other ratings, competitor review

**Comment by amyknox** [comment]
MURAL: Ratings Research Discovery Workshop: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1591188945224/a4c47d0003de412c5abbb6be8b2cee2b51cd81d5

MURAL: General Discovery Research Findings: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1589996279941/0d404f73fdfcde3a892df831eb304150ad57e381
