### ISSUE TITLE
Staging Review finding: Update the mailing address pattern

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#99037]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** 10-10 Health Apps
**Product:** 10-10CG
**Feature:** Improve Facility Selection

## Findings details
**VA.gov Experience Standard - issue:** [User encounters up-to-date design components and patterns.](https://design.va.gov/about/experience-standards/#user-encounters-up-to-date-design-components)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

The pattern you are using for mailing address has been updated since this form was last worked on.

<details><summary>Link, screenshot or steps to recreate</summary>

![screen shot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/51980-allison-2.png?raw=true)

</details>

## Recommended action

Update the address page to align with the [newer pattern in the design system](https://staging.va.gov/mock-form-patterns/mailing-address).

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** [Addresses](https://design.va.gov/patterns/ask-users-for/addresses)
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by hdjustice** [comment]
Commented in Slack team channel and tagged platform governance team members

> - [#99037](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99037): We can only receive US addresses, and the business requires the county field.  For the Veteran address page, we are utilizing the newer pattern on the Veteran address page and utilizing its built-in flexibility.  For the Caregivers' address pages, that is a hardcoded page where we are utilizing DST components and writing our own functionality and validation mechanisms.

**Comment by allison0034** [comment]
Ok, thank you, you can close.
