### ISSUE TITLE
Staging Review finding: Unclear visual heading hierarchy on confirmation page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#99040]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** 10-10 Health Apps
**Product:** 10-10CG
**Feature:** Improve Facility Selection

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that meets best practices.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-meets-best-practices)
**VA.gov Experience Standard - category:** [Comprehension](https://design.va.gov/about/experience-standards/#category-comprehension)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The confirmation page for medical centers shows the medical center you selected on the previous page, as well as the medical center assigned to the caregiver. These use h4/h5 heading structures which are semantically correct. However, visually, it is difficult to distinguish these headers. Having visual distinctions between headers of different levels helps sighted users determine the content hierarchy and groupings. Without that differentiation it becomes more difficult to distinguish what content is associated with other content. (I.e. the name of a medical center is associated with its parent heading describing what that location is.)

<details><summary>Link, screenshot or steps to recreate</summary>

![visual screen shot of headings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/51980-erin-headings-1.png?raw=true)

![heading hierarchy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/51980-erin-headings-2.png?raw=true)

</details>

## Recommended action

Ensure the h5's are visually distinct from the h4's in order to clearly indicate the hierarchy and content groupings on the page.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** Headings

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by jessicastump** [comment]
We were on the path to update this page post [research findings/recommendations](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/674) already! 

Here is a link to our design ticket and we have reviewed this with CAIA already too (cc @aliyahblackmore)

**Comment by hdjustice** [comment]
Review #97705 for design updates (already completed)

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the changes have been made. 

### 1. On the facilities confirmation page, the two facilities address block now matches

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/991fdf73-77a0-4770-85b1-4a1bf1d4a8ac" />

### 2. The comma has been removed after the state to conform to the rest of the app

<img width="922" alt="Image" src="https://github.com/user-attachments/assets/ec2400e8-f8a4-4194-96fb-22a414598df4" />
