### ISSUE TITLE
Staging Review finding: Use of passive voice 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#99110]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Facilities
**Product:** VAMC
**Feature:** Alternative Alert Banners

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content that does not align with VA.gov voice and tone content principles.](https://design.va.gov/about/experience-standards/#user-encounters-content-that-aligns-with-vagov-voice-and-tone-content-principles)
**VA.gov Experience Standard - category:** [Credibility](https://design.va.gov/about/experience-standards/#category-credibility)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

There are several places where the content uses passive voice. Per VADS guidelines, you should always use active voice. 

<details><summary>Link, screenshot or steps to recreate</summary>

<img width="956" alt="Image" src="https://github.com/user-attachments/assets/43de5729-9567-4f52-bc45-bc559e094ccc" />

</details>

## Recommended action

1. On the Wilmington alert, the copy reads "When calling the main line (302) 994-2511 and pressing # to direct dial an extension an error is returned." This can be replaced with "calling the main line . . . returns an error" 

2. On the Memphis alert, the copy reads "The parking garage will be closed . . ." this can be replaced with "we will close the parking garage . . . " 

3. On the Wilmington alert, replace "an update will be sent out" with "we will send an update" 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Plain language - Use active voice](https://design.va.gov/content-style-guide/plain-language/use-active-voice)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by jilladams** [comment]
This content is editor generated. We've added the guidance about active voice to the knowledge base article for this content: https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/about-alerts-and-operating-statuses/how-to-add-a-system-banner-alert
