### ISSUE TITLE
Update current academic year text on YR tool landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9912]
Referencing the specific year info is a business requirement. We made this update on the tool search results page but it was missed on the search landing page. 

On this page: https://www.va.gov/education/yellow-ribbon-participating-schools/

Change this text: "Search for schools participating in the current academic year by one or all of the terms below."

To this text: "Search for schools participating in the current academic year, August 2019 through July 2020."

**Comment by stephorkandatx** [comment]
Validated on production and closing
