### ISSUE TITLE
Vets-api terminal access for Jane Cho

### ISSUE THREAD

**Issue by janechodance** [department-of-veterans-affairs/va.gov-team#99121]
### Your Name

Jane Cho

### Your GitHub handle (terminal access is managed through GitHub)

@janechodance

### Team, Role, and Company of the target individual

Benefits Management Tools Team 2, Front-end Engineer, Coforma 

### Product Manager (PM) name and email

Saliha Ghaffar - saliha.ghaffar@coforma.io

### Product Owner (PO) name and email

Amy Lai - amy.lai2@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Laurene "Reney" Cook

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Coforma - Jeff Langworthy

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [x] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![Image](https://github.com/user-attachments/assets/d476118d-46c2-4db6-bed2-0ff3c937332c)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by GWright321** [comment]
@janechodance  You’ve been granted access to the staging environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
