### ISSUE TITLE
Bug: 10-7959f-2 fails on submit in staging

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#99147]
Two consecutive test submits on staging failed within a few minutes of each other.

Below is the review page for the second submit
![Image](https://github.com/user-attachments/assets/ffb215b7-c131-4cfe-aad6-6175c94e52c0)

**Comment by michaelclement** [comment]
Recommend we close this issue as it's covered by [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19885)

**Comment by cloudmagic80** [comment]
I think this good to close
