### ISSUE TITLE
Change headings to questions - Part 2

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#99201]
## Description

This is follow-up work to #91792 where we're adjusting page titles so we're asking questions on pages that require user input. This handles the "sub-pages" after a user chooses a type of care.

---

## Development Checklist

Update the following page headings as shown in the design file:
- [ ] Type of eye care page (after you select Eye care on Type of care)
- [ ] Type of sleep care page (after you select Sleep medicine on Type of care)
- [ ] Type of audiology care page (after you select Audiology and speech on Type of care, then Community care facility on Type of facility)

### Design Assets
- [Figma file](https://www.figma.com/design/5dWfMQkBCvEX9XYJsNdcT3/Change-direct-schedule-headings-to-questions-%7C-Appointments-FE?node-id=233-8241&t=YlBr3oYZNXjHrAaq-1) (put N/A if not needed) 

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove)

**Comment by outerpress** [comment]
@JRRoof this one's ready for prioritization

**Comment by JunTaoLuo** [comment]
@outerpress this is ready for validation

**Comment by outerpress** [comment]
Passing to @Cieramaddox to validate

**Comment by outerpress** [comment]
Thanks @Cieramaddox ! I'm going to close since @JunTaoLuo 's out today
