### ISSUE TITLE
Design Discovery: Mapping a mural board to explore combining OHI & CHAMPVA Application

### ISSUE THREAD

**Issue by andrea-merrill** [department-of-veterans-affairs/va.gov-team#99298]
## Acceptance Criteria

- [x] All information collected between two forms is visible on mural board
- [x] Create possible options to explore for combining the two forms, whether that's linking at the beginning/end of 1010d or including in the flow itself
- [x] Identify any questions to be answered or problems to be solved in future research/work

**Comment by andrea-merrill** [comment]
@baltes do you want to create an epic to capture this work and anything else that may pop up out of this

**Comment by rspope** [comment]
Reviewed with Lois in design sync 12/23/24. Mural and options need further discussion, but Mural works as-is. Closing this ticket.

**Comment by andrea-merrill** [comment]
[Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1734537770114/c43159bce476eaee8e52f597201223934411963b)
