### ISSUE TITLE
Pull Phone & Fax Numbers for PPMS Care Site Only

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#993]
## User Story
As a Veteran (or family member) looking up a Community Care health provider, I need to see a valid phone number so I can contact the provider. 

## Primary Task
All contact info for Community Care providers should be taken from the 'site-level' data in PPMS, not the provider-level data. 

## Background
The PPMS database for Community Care Facility Locator has 2 sets of contact info: 1.) Provider-Level data and 2.) Care-Site level data. The database has much more comprehensive information for care-sites (about 90% complete) than for providers (less than 30% complete). The Facility Locator uses the Care-Site data for addresses, but currently uses provider-level data for phone and fax numbers. As a result, most provider searches do not display a phone number. 

## Acceptance Criteria
- [ ] Phone and fax numbers (including all contact info) has been pulled from the Care-Site database and tested in staging

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [X] **Attached to an Epic** (FL PPMS)
- [X] **Labeled with Team** (product support)
- [X] **Labeled with Practice Area** (frontend, product, research)
- [x] **Labeled with Type** (request, discovery)

**Comment by ncksllvn** [comment]
For my own reference, [PPMS Swagger Docs](https://dsva.slack.com/files/UFN410MGF/FMUKEAECT/ppms_docs_pprint.json?origin_team=T03FECE8V) taken from https://dev.dws.ppms.va.gov/swagger/ui/index#!/GlobalFunctions/GlobalFunctions_ProviderLocator.

**Comment by ncksllvn** [comment]
@chrisj-usds I'm still investigating this, but is there a possibility that the Care-Site data doesn't include a fax number? I'm looking at some of the raw API data and the only field I see that stores a fax number is called `OrganizationFax`, which is what we're using currently, so I'm assuming that's Provider-level data.

**Comment by ncksllvn** [comment]
I have a PR open in the API for adding a new attribute `caresite_phone` into the provider data. We can then inspect this new attribute in Staging/Prod without affecting the website, since the front-end doesn't do anything with it. If we find that it's more reliable than the phone data we use currently, we can adjust either the API or front-end so that we show that to the user.

**Comment by Karak888** [comment]
@ncksllvn has a PR open for fax number.

**Comment by ncksllvn** [comment]
It looks like CareSite phone is way more reliable in Prod. Most providers do have phone number values from my random searches. We should definitely move forward with showing this on the front-end. 

Just wondering a few things - should we retain both phone numbers values - for Provider-level and CareSite-level - and show the former if we have it, and the latter if we don't. Or if we should just always use the CareSite data? Either way, easy change!

**Comment by ncksllvn** [comment]
Man, I may have just missed the 2 PM cutoff for this :angry: But the work here is merged and will go live soon.

@Karak888 The PPMS developer docs didn't seem to indicate  that there was a CareSite-level fax number, but maybe it's worth additional exploration in a follow-up ticket?

**Comment by ncksllvn** [comment]
We now have phone numbers!

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/296a8ce5-e04c-4947-843b-b6e453f74e38)

**Comment by Karak888** [comment]
awesome @ncksllvn!  I know that @chrisj-usds reviewed on Monday so maybe we can put this PPMS one to rest (cause we gots lots more on the PPMS front)!
