### ISSUE TITLE
Phase 1 - Move components shared by Referral appointments feature to the correct directory

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#99333]
## Description
Phase 1 - Move components shared by Referral appointments feature to the correct directory

---

## Acceptance Criteria
The following files should be moved:
- [ ] ./vaos/appointment-list/components/AppointmentsPage/AppointmentFlexGrid.jsx to ./vaos/components/AppointmentFlexGrid.jsx
- [ ] ./vaos/appointment-list/components/AppointmentsPage/AppointmentRow.jsx to ./vaos/components/AppointmentRow.jsx
- [ ] ./vaos/appointment-list/components/AppointmentsPage/AppointmentRow.unit.spec.js to ./vaos/components/AppointmentRow.unit.spec.js
- [ ] ./vaos/appointment-list/components/AppointmentsPage/AppointmentColumn.jsx to ./vaos/components/AppointmentColumn.jsx
- [ ] ./vaos/appointment-list/components/AppointmentsPage/AppointmentColumn.unit.spec.js to ./vaos/components/AppointmentColumn.unit.specjs
- [ ] ./vaos/appointment-list/components/AppointmentsPage/ListItem.jsx to ./vaos/components/ListItem.jsx
- [ ] ./vaos/appointment-list/hooks/useHandleClick.jsx to ./vaos/hooks/useHandleClick.jsx
- [ ] ./vaos/appointment-list/hooks/useHandleClick.jsx to ./vaos/hooks/useHandleClick.unit.spec.js
- [ ] ./vaos/appointment-list/hooks/useHandleKeyDown.jsx to ./vaos/hooks/useHandleKeyDown.jsx
- [ ] ./vaos/appointment-list/hooks/useHandleKeyDown.jsx to ./vaos/hooks/useHandleKeyDown.unit.spec.js

## Technical Details
None

## Design Assets
None

## Definition of Done
All files have been moved.

**Comment by JunTaoLuo** [comment]
I've tested this change locally and verified that the moved components are displayed correctly so this is ready to be closed.

**Comment by JunTaoLuo** [comment]
We had a chat last week about this and we concluded that we've sufficiently validated this change so I'm closing the ticket.
