### ISSUE TITLE
Update step-by-step learning center template to enable screenshots

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9934]
## Update step-by-step learning center template to enable screenshots 

Currently, we use the subway map/process list component for information suited for an ordered stepped/process list. For the learning center, we want to modify this component to enable screenshots.  A lot of help/support content, especially those created by call center authors, would be more helpful to Veterans with screenshots/visual references for some steps. 

Epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9027 

Acceptance criteria: 

- [x] Update wire/mockup of step-by-step template to indicate screenshots can be included. 

- [x] Drop design files here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files 

- [x] Update Mural board with updated wire/mockup: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b

**Comment by rtwell** [comment]
@jenniferlee-dsva I used the current comp and dropped some random screen grabs in—unless you would like to use some "real" content. If this is gtg, I will update the mural and the Sketch file.

![image](https://user-images.githubusercontent.com/12564977/84093340-f1e31a80-a9c7-11ea-8e1c-b5783e033eef.png)

**Comment by jenniferlee-dsva** [comment]
I love it - thank you @rtwell . Please drop them in the repo wip design files and Mural. (Locations noted above in ticket.)

**Comment by rtwell** [comment]
done and done
