### ISSUE TITLE
QA Standards - vfs-mhv-medical-records - MHV Medical Records/View Radiology Images/Settings

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#99361]
#### VFS team name
vfs-mhv-medical-records

#### VFS product name
MHV Medical Records

#### VFS feature name
Download Records Phase 1

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No Regression Plan among QA artifacts.
#### Test Plan
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No Test Plan among QA artifacts
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Due to restricted access, I have not been able to evaluate these artifacts
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 89.59

- Functions %: 82.26

- Statements %: 89.82

- Branches %: 79.14

- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
All categories must be at least 80%; Branches is _almost_ there!
#### Endpoint Monitoring (Completed Playbook)
- [x] Standard has been met
- [ ] Standard has not been met
#### Logging Silent Failures
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
To satisfy this requirement, we need to see where in code calls to StatsD are made such that any operation susceptible to a silent failure is accounted for. Check out [this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-logging-silent-failuresLoggingSilentFailures) for more information.

---

### Next Steps for the VFS team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Close the ticket** when your Product Owner determines that you have sufficiently met the QA Standards.

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by bryan-riley-va** [comment]
Dev team is working on getting branches up over 80%

**Comment by bryan-riley-va** [comment]
Unit testing above 80% as of this moment:

<img width="1197" alt="Image" src="https://github.com/user-attachments/assets/68552d25-1497-422d-b02d-223a96135214" />

**Comment by bryan-riley-va** [comment]
Test plan link is here (had issues getting it moved so a new one was created):  https://dsvavsp.testrail.io/index.php?/plans/view/6300

**Comment by bryan-riley-va** [comment]
Closing this ticket as I believe we have resolved the previous launch blocking issues - @it-harrison please feel free to review or reopen if anything is still missing!
