### ISSUE TITLE
Discovery: How can search.gov be configured for learning center product?

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9937]
## Discovery: How can search.gov be configured for learning center product?

**Problem statement:** 
The VA.gov site currently uses search.gov for onsite search. We want to use search.gov to be able to search with a sub-site -- like only the learning center product. What do we need to know and prepare for in order to have configure search.gov for a product level search? 

**Note:** This question is relevant for other future products that we may want to use search.gov on. (EX: modern VA forms search)

1. Can search.gov be configured for a product? 
2. How do we configure search.gov for learning center product?  
3. What is the LOE to configure search.gov for the learning center?  
4. What kind/s of effort is needed - FE, BE, content? 
5. Other questions as yet unidentified.

Learning center product outline: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md

WIP mockups: 
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b

**Comment by jenniferlee-dsva** [comment]
Hi @johnhashva - could you document the details of your findings in this ticket, so we can close? I'll point to this ticket from the product repo. 

See original ticket description ^ . Thank you.

**Comment by johnhashva** [comment]
- **Can search.gov be configured for a product?**  Yes, [leveraging the existing directory indexing capability](https://search.gov/manual/domains.html), it is possible Search.gov could power this feature.

- **How do we configure search.gov for learning center product?**  Assuming learning center content is structured in the same index-able format as is VA.gov content, use the configuration manager via our Search.gov accoun to list the Va.gov/folderNote: this will include all sub-folders (if they exist).

- **What is the LOE to configure search.gov for the learning center?** At a high level, this looks like a fairly easy implementation/configuration -- e.g., can be completed in one sprint.

- **What kind/s of effort is needed - FE, BE, content?**   FE engineer can configure this via Search.gov admin panel.

_To validate our assumptions about implementation, we will need more details about Learning Center -- in particular the content and folder structure._

**Comment by jenniferlee-dsva** [comment]
Thank you @johnhashva . 

RE: 
>To validate our assumptions about implementation, we will need more details about Learning Center -- in particular the content and folder structure.

I understand folder structure, but not sure I understand what's meant by "content structure," as that has a certain meaning for me wrt templates. As this search function is basically a search product inside the LC, could I ask you to take the lead on validating/troubleshooting your above assumptions vis-a-vis folder structure and the other "more details" that are needed? 

I've started a placeholder ticket here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11254  

I may be able to provide answers or help answer, if you can identify the specific questions we need to resolve. "Folder structure" sounds vaguely like an IA question, so you may need to pull in Mikki -- or if it's more about FE, then Nick?
