### ISSUE TITLE
Discovery: What are the current known VA.gov help desk and call center issues and articles about common customer VA account topics?

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9938]
## Discovery: What are the current known VA.gov help desk and call center issues and articles about common customer VA account topics?

**User story:** As a Veteran or other beneficiary, I want to be able to solve common VA.gov and VA account questions without calling. 

**Problem statement:** In our MVP launch of the learning center, we want to address the most common customer inquiries that come into call centers about VA.gov or their VA online account issues, so that users can help themselves with clear, helpful content, and not feel frustrated by calling and being put on hold or into a circular phone routing system. 

Call center liaison and DEPO stakeholder: @clantosswett 
PW content strategist:  @DanielleThierryUSDSVA 

**Acceptance criteria:**
[x ] A list of top call center VA.gov account topics - ranked by call volume if available @clantosswett 
[x] Current call center articles and scripts on VA.gov account topics, if available @clantosswett 

**Goal:** 
Identify call center information and history about common VA.gov account questions, and create/update learning center content for the MVP, using the new content templates. @DanielleThierryUSDSVA 

**Learning center product outline:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md

**WIP mockups:**
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b

**Comment by jenniferlee-dsva** [comment]
Confirmed - @DanielleThierryUSDSVA will take point on this for content

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva @bethpotts Here's an initial list of account-related help questions with content sourcing notes for our call today. Thanks!

[Potential faqs for account help on VA.gov_initial list for 6.23.20 call](https://app.zenhub.com/files/133843125/16be65e2-927d-4bcd-a65d-2848a2d4c99d/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenniferlee-dsva. I think we can close this one now too, yes? Next step will be actually writing out the FAQs for these topics.

**Comment by jenniferlee-dsva** [comment]
Thx @DanielleThierryUSDSVA - I'll create a writing story that references the complete list of prototype mvp content here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy#list-of-content-articles-for-the-first-mvp-prototype-user-research-session
