### ISSUE TITLE
10-10d: Update processing time copy

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#99409]
Currently CHAMPVA applicants are told their application will take 90 days to process. We want to update this with new copy from CAIA to acknowledge longer than usual processing times.

### Acceptance criteria
- Confirmation page copy is updated to include the revised processing time guidance.
- VA notify confirmation email template is updated to include the revised processing time guidance.

### New copy
`Note: Right now there's a delay in processing CHAMPVA applications. We expect this delay to be temporary. If you have questions about the status of your application, call us at [800-733-8387](tel:8007338387) (TTY: 711). We’re here Monday through Friday, 8:05 a.m. to 7:30 p.m. ET.`

Slack discussion: https://dsva.slack.com/archives/C068Q9DQACX/p1734357422333669

**Comment by michaelclement** [comment]
VA Notify template:

![Image](https://github.com/user-attachments/assets/c9757f65-ada0-4573-9f97-f69d32da6556)

**Comment by jamiefiore** [comment]
@michaelclement Looks like you are missing a space in between the phone number the (TTY) on the confirmation page. Can you update that? Everything else is good. Thanks!

**Comment by michaelclement** [comment]
Fixed the space and pushed it up! Thanks Jamie!

**Comment by michaelclement** [comment]
Merged, should be visible on staging shortly.
