### ISSUE TITLE
Vets-api terminal access for Daniel Sasser

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-team#99431]
### Your Name

Daniel Sasser

### Your GitHub handle (terminal access is managed through GitHub)

@dsasser

### Your dsvagovcloud AWS user name (if applicable)

Daniel.Sasser

### Team, Role, and Company of the target individual

Sitewide team, Senior Software Engineer, Agile 6

### Product Manager (PM) name and email

Jill Adams (Delivery Manager) - jill.adams@agile6.com or jill.adams1@va.gov

### Product Owner (PO) name and email

Michelle Middaugh suzanne.middaugh@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [x] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [x] dev
- [x] staging
- [x] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![Image](https://github.com/user-attachments/assets/a1576795-f16c-49c2-b0d4-8d766b7cbeb2)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by GWright321** [comment]
@dsasser  @You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by dsasser** [comment]
@GWright321 I'm not seeing the Terminal tab in ArgoCD. I've tried logging out/in but to no avail. Am I missing something?

**Comment by GWright321** [comment]
Hello @dsasser have you tried disconnecting and reconnecting to SOCKS? or maybe even a different browser? I've seen this in the past.

**Comment by dsasser** [comment]
@GWright321 I logged off/on to socks, and tried a completely different browser but I'm still only seeing the Events and Summary tabs:

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/3cd85f6a-90b1-47ed-9d7b-5030e6264e73" />

**Comment by GWright321** [comment]
Thank you @dsasser I'm looking into this.

**Comment by GWright321** [comment]
@dsasser You do have the same permissions as @SnowboardTechie (Bryan.Thompson). I also noticed you are clicking a node instead of a pod. I'm not sure if that changes what your'e looking for but you should have more options when opening a pod.

**Comment by dsasser** [comment]
@GWright321 I guess I was clicking on the wrong thing. Apologies, I'm not well versed in k8s or argocd.

Looks like I'm good to go:

<img width="1230" alt="Image" src="https://github.com/user-attachments/assets/0759e78d-fda0-4a6a-8bfc-a5b57e82b8d2" />

Thank you for your patience.

**Comment by GWright321** [comment]
I'm not well versed either in Argocd. My teammate helped me out. lol
Have a happy Holiday.
