### ISSUE TITLE
[Bug] Left Nav page loading behavior

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9943]
## What happened?
The quirky behavior of children navs in the left nav menu displaying before the Pittsburgh VAMC page loads is still happening. The child items are visible before the page loads. 
Documented in comment on [#9162](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9162#issuecomment-639669939)

## Steps to Reproduce
- URL: https://staging.va.gov/pittsburgh-health-care/ (will be in Prod by the time this issue is brought into sprint)

## Desired behavior
When an element from the left nav is selected, the relevant page should load before the navigation menu appears. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This is a regression bug. It had been previously resolved before launch.

**Comment by ncksllvn** [comment]
Is this still an issue? I'm not seeing the issue when I load the page

**Comment by brangi** [comment]
@ncksllvn , The issue is when selecting items and the loading that happens. For example 

![loading](https://user-images.githubusercontent.com/100468/85053620-6a806e80-b160-11ea-91ac-602746512169.gif)

The requirement is that the content in the right should load first and then see the children items in the left nav should render. I am also not really sure how to fix the desired behavior though, do you have any advice on this?

**Comment by ncksllvn** [comment]
It seems like the sidenav is just a list of links then with some items that only reveal as you navigate deeper. In that case, I don't think you need the onClick behavior of the links anymore. So I think you can remove the `onClick` prop from `src/platform/site-wide/side-nav/components/NavItemRow.js` on line 58. That might do it?
