### ISSUE TITLE
[Bug] Left Nav padding

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9945]
## What happened?

- As documented in the comment on [9162](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9162#issuecomment-639669939), padding needs to be addressed: 

- More white space needed above "Services and locations" . 
- Horizontal line is needed between "In this section" and  "Services and locations"

![image](https://user-images.githubusercontent.com/55411834/84049438-b0238700-a969-11ea-95be-35d9409175bd.png)

- On mobile, "In this section" is too close to "Services and locations". 

![image](https://user-images.githubusercontent.com/55411834/84049466-b7e32b80-a969-11ea-81f1-18cf2a471b5a.png)

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
Padding is consistent in Left nav menu (mobile and laptop/desktop)

## Acceptance Criteria
- [ ] Left Nav appearance and spacing is consistent with design specs above when viewed on laptop/desktop and mobile (Horizontal line and spacing)
- [ ] Has been evaluated on actual mobile devices

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by rtwell** [comment]
This 98% of the way there!

i think we just need to reduce the height of the white space above each "section" (Services and Locations, News and events, and About VA Pittsburgh). I don't know if this helps, but in Sketch, the spacing in prod (red) is 34px, and the desired space (green) is 28, about a 20% decrease in height. Thank you for your patience!

![image](https://user-images.githubusercontent.com/12564977/92606321-cef32b80-f280-11ea-90c0-5b06e8fa27e4.png)
