### ISSUE TITLE
Contact Center Review for Cartographers - MHV-on-VA.gov landing page and portal navigation

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#99451]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

The My HealtheVet-on-VA.gov landing page serves as a front door to VA.gov’s health-related applications. It also includes a My HealtheVet navigation bar (aka "secondary navigation"), which makes the MHV landing page and four main health tools easily accessible to users wherever they are in the My HealtheVet-on-VA.gov portal.

***This release:*** Version 3.0 of the product guide covers a new user-facing alert to the MHV landing page for cases when the MHV back-end failed to return a MHV UUID.

### Launch Date
*Please provide the launch or rollout date and details.*

New alert: 12/20/24

### Version Number
*Please provide the version number of the guide and/or video.*

v3.0

### Product Guide
*Please provide product guide link*
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/contact_center/MHV%20on%20VA.gov%20Landing%20Page%20Guide%20v3.0%20-%20Dec%2011%202024.docx

### Product Video
*Please provide product video link*
n/a

### Product Video Transcript
*Please provide product video transcript link*
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The draft looks good, and I am sending it to VEO for their review.

**Comment by wesrowe** [comment]
Sounds good, thanks @starlow00!

**Comment by starlow00** [comment]
There are no changes from VEO. The working copy is attached for future revisions. Thank you!
[MHV on VA.gov Landing Page v3.0_SRT 12192024.docx](https://github.com/user-attachments/files/18216180/MHV.on.VA.gov.Landing.Page.v3.0_SRT.12192024.docx)
