### ISSUE TITLE
Left Nav ongoing maintenance

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9946]
## High Level User Story
As a user on a content page on VA.gov, I need better on-page and section navigation and menus so I can get to all content and tools in 1-2 clicks/taps.

We will initially redesign and build our new navigation and menu components and patterns for the va.gov/pittsburgh-health-care product. We will do usability testing on staging.va.gov/pittsburgh-health-care.

## Hypothesis/(es)
**If** we continue to iterate on left navigation usability and design, **then** we can expect.....[TBD]

## Goals

- Resolve identified usability issues
- Address design/style gaps
- Implement stakeholder feedback

**Comment by davidmpickett** [comment]
all issues completed
