### ISSUE TITLE
Qualitative Data Request.

### ISSUE THREAD

**Issue by JonathanPostMO** [department-of-veterans-affairs/va.gov-team#99474]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

10-01-2024

### Date Range End

12-31-2024

### Product Name(s)

Secure Sign-in Transition (SSIT), Identity Team (MO)

### Product Description

SSIT is the team responsible for deprecating MyHealtheVet and DS Login, moving users to secure, multi-factor authentication & IAL2 compliant, credential service providers (Login.gov & ID.me). My team is working specifically on change management for this project, helping Veterans and VA employees navigate the sign-in transition. We're looking for the qualitative data from MyVA411, for all things related to the sign-in, authentication, and verification services and experiences.

### Survey URL(s), key term(s), case category or type

NAVIGATION ISSUES
--
Navigation Issues | Account Sign In

INABILITY TO SIGN IN
--
Inability to Sign In | Two-factor authentication
Inability to Sign In | Confirmation Email Issue
Inability to Sign In | EVSS Errors

IDENTITY VERIFICATION ISSUES
--
Identity Verification Issues | ID.me
Identity Verification Issues | DS Logon
Identity Verification Issues | My HealtheVet

### Sub URLs

Yes

### File Delivery Format

One file for each term/URL

### Word Cloud

No

### VA Email Address(es)

jonathan.post@va.gov

**Comment by newworld2616** [comment]
Hello, I have shared the requested data. Let me know if you have any questions. Thank you.

**Comment by JonathanPostMO** [comment]
@newworld2616 Thanks! Happy new year, cheers. 👍

**Comment by newworld2616** [comment]
@JonathanPostMO Anytime! Thank you! Happy new Year!
