### ISSUE TITLE
Spike: Complete AC-API stakeholder syncs & get next steps for tool team implementation

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#99480]
## Description

This ticket is a follow-on of #94098 where A/Cs were not fully completed by the close-of-sprint date 12/18/24. Context: we drafted thorough high-level documentation, have designs, and have nearly implemented the AC-API alerts on the My HealtheVet on Va.gov landing page. We set up a sync to socialize this work w/ affected health tool team POs, but none were able to make that meeting time save for Don McCaughey (VAHB mobile app). 

This spike ticket intends to cover two remaining tasks: 1.) communicating this work to the remaining stakeholders & getting feedback, and 2.) Understanding how to get into PI planning schedules in January to get this work prioritized asap. 

### User story

As a Cartography team member, I want to communicate the importance and outstanding work necessary to implement the AC-API and help minimize the load on Veterans to get access to health tools that rely on the MHV-API backend.

### Notes
- [Account Creation API architecture mural here ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?sender=uf94a77a19aaf687331c09367)
- [Alert designs](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=0-1&node-type=canvas&t=pJFR7uJv6AmiPHLp-0)
- [Documentation of Account Creation API overview + decision options for POs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/account-creation-api.md)

Possible tasks:
- [x] Socialize this work with remaining POs who were not able to attend the scheduled sync on 12/16/24:
  * Kay Lawyer
  * Patrick Bateman
  * Marci McGuire
  * _including Kaitlin Fink and Robyn Singleton as needed_
- [ ] Get clarity from POs on clear next steps to get this work incorporated into roadmaps as part of PI planning in early January

## Acceptance criteria
- [x] Important information has been communicated with remaining stakeholders
- [x] Stakeholders have had a chance to review the documentation, provide feedback, and share any relevant information about how to work with their PI planning processes to get this work prioritized in January 2025. 
- [x] We are prepared to move on to the next ticket: drafting the implementation strategy

**Comment by sterkenburgsara** [comment]
**Update**: held stakeholder sync 2 on Thurs, Dec. 19 and Kay, Robyn, and Kaitlin attended. We have not directly discussed w/ Marci or Patrick, but the other OCTO leads let us know that the documentation would suffice and we can move forward with timelines for getting this work into PI planning. @wesrowe followed-up the meeting with a [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1734631467634219) that included a meeting recap and some clarification on next steps, which includes needing to get information about this work to teams by EOD today (12/20).

**Comment by sterkenburgsara** [comment]
Should engage directly w/ PM/DMs for each of the 3 affected tool teams, provide an estimated LoE for the work to deliver all 3 alerts: 
* Medications - Raquel Robertson and Tanner Bird
* Medical records & SM - Bryan Riley & Lichelle Bain

**Comment by wesrowe** [comment]
We're done with this one! closing
