### ISSUE TITLE
CT: Mobile I'll be taking classes outside of the U.S. and U.S. territories focus on calculation

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#9951]
When "I'll be taking classes outside of the U.S. and U.S. territories" is selected on mobile, when hitting the "Calculate benefits" button it does not put the focus on "Your estimated benefits", instead it scrolls up to the top of the accordion for "Estimate your benefits"

Steps to reproduce
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11929140 on mobile 
2. Make any selection in estimate your benefits besides "I'll be taking classes outside of the U.S. and U.S. territories" and hit the calculate button
3. Observe how it puts focus on "Your estimated benefits"
4. Now select the checkbox for "I'll be taking classes outside of the U.S. and U.S. territories" and select calculate again
5. Notice how it scrolls up to "Estimate your benefits" instead of scrolling down to "Your estimated benefits"

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12999

**Comment by sonntag-adam** [comment]
Fixed in staging. Focus is put on Your Estimated Benefits now.
