### ISSUE TITLE
ZSF | PBP: minor text updates on MVP Confirmation page

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#99510]
**To Do:**
- [x] Work with CAIA to finalize any minor text edits on the confirmation pages for Pension and Burial. 
- [x] Update the ENG ticket #99181 with changes and link to Figma file.

**Comment by gmaciolek** [comment]
Figma files updated based on collaboration with CAIA. Engineering ticket updated.
