### ISSUE TITLE
[COGNITION]: GIBCT EYB - CONSIDER making the Show Next and Show All buttons use full button styles

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#9952]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The VETTEC school locations table allows users to show more results using Show next 10 and Show all buttons. These are styled to look like our additional information show/hide and a link respectively, which could be confusing to some users. I'd like to consider making these the standard blue button for the primary action and the outline button for the secondary action.

/cc @emilywaggoner && @CrystabelReiter for visibility

## Point of Contact

**VFS Point of Contact:** _Trevor, Crystabel_

## Acceptance Criteria

- [ ] Buttons read visually as buttons instead of show/hide actions and links
- [ ] Existing functionality is maintained

## Environment

* /gi-bill-comparison-tool/profile/21852735 (this is a sample profile view with the right information)

## Screenshots or Trace Logs

![Screen Shot 2020-06-08 at 11 46 25 AM](https://user-images.githubusercontent.com/934879/84060397-baea1600-a981-11ea-9613-7816cb49ff08.png)

**Comment by desireeturner** [comment]
@amyknox @ccruzgra @JenLJ When you all have a moment can you review this feedback and provide direction to inform development? Thank you!

**Comment by amyknox** [comment]
@1Copenut - thanks for the suggestion!  We tested this behavior and found it worked well. We also don't want to confuse users and draw their attention away from the rest of the elements on the page by incorporating buttons into the general information flow.  

If Emily and Crystabel are ok with this design solution, we'd like to keep it as-is.  @emilywaggoner ? @CrystabelReiter ?

**Comment by CrystabelReiter** [comment]
@amyknox I spoke to @emilywaggoner @1Copenut We think it's fine to keep it as is, since the button/links tested well.
