### ISSUE TITLE
Health Pages Issue triage

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#9959]
Catalogue and review all health pages tickets to help with the transition of this work to the VSA websites team.

Designate a new tag for tagging all tickets.

**Comment by hinzed1127** [comment]
Met with Nick and Kelson of VSA, there's a corresponding knowledge share ticket in #9696 that I'm going to list all of our existing tickets to and let them designate accordingly

**Comment by hinzed1127** [comment]
VSA has aggregated a lot of this work in #10240. I referenced all of our existing tickets for content updates and alert box work, so this should be considered completed
