### ISSUE TITLE
Design feedback: Staging Review Medical Device Reordering Tool

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/va.gov-team#9964]
#### Feedback framework
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

#### Do
_This section feedback is mandatory to maintain consistency with the design system and global VA.gov experience._

- On all pages, in the breadcrumbs, please make sure to bold the current page the user is on (screenshot of unbolded breadcrumb below) ![image.png](https://images.zenhubusercontent.com/5b0577164b5806bc2bd4524c/d7f5a9c5-7491-4b9f-a6bf-a08394d14665)
- On the permanent address card (when there’s no temporary address added), the button “Send my order to this address” has a lot of padding on both the left and right sides, and expands to the full width of the card. Please reduce the padding to 20px on either side and align it left so that it isn't full card-width. See screenshot: ![image.png](https://images.zenhubusercontent.com/5b0577164b5806bc2bd4524c/b42d2b2c-47ea-4506-9a5b-2fea56934b12)
- On the Review & Submit page, the font-weight is bold on the Additional Info component. Please change the font weight back to normal. See screenshot: ![image.png](https://images.zenhubusercontent.com/5b0577164b5806bc2bd4524c/dc4fdf7e-b1f8-4b68-ae96-530bb0a25484)

#### Try
_This feedback is to prompt exploratory next steps._

- On the [accessories page](https://staging.va.gov/hearing-aid-batteries-and-accessories/accessories), and other pages where there are the cards like this, toggling between the cards (or toggling the checkbox ones on and off) makes the content shift a bit when the 3px border appears. Try having the cards hold a 3px transparent border by default, and only change the color on click. This would prevent the cards from shifting when the border appears.
- In all the cards where these types of buttons appear, try expanding the focus state halo to contain the entire button instead of just the radio or checkbox part. See screenshot: ![image.png](https://images.zenhubusercontent.com/5b0577164b5806bc2bd4524c/289604bb-5744-4ab4-8b87-090ae67ec6de)

#### Consider
_No feedback in this category at this time_

Please let us know if you have any questions or need clarification about any of these items! Thank you!

**Comment by rileyorr** [comment]
Thank you for the feedback @emilywaggoner! I've shared this feedback with my team and we are working on next steps to incorporate the mandatory feedback and try the exploratory next steps for the cards' shifting content.
