### ISSUE TITLE
Access for Luke Markwordt

### ISSUE THREAD

**Issue by lukemarkwordtlibertyits** [department-of-veterans-affairs/va.gov-team#9965]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Luke Markwordt
- Please Provide your email.
   > luke.markwordt@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Pivot, Software Developer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABAQC7jS7LJxQUuVaO0K5aaJaBNw015VBjXbbb06r4HEcYxG+57c75n3iBs0lkNowQdyaspyEc5n741uf2UCm4xh/kWorQTe9ocxj7IJUS8MfxOgO+6nW9PqFzIcCkLU6I3HhBFA8QueazhbIu7E9cSUF5h185e2M/ghgqpgbLq7J5wYNfHIUWgy51Q/BjG0q23vuf9SzNm2jKQ3GEkB3tksOWbottD26DXKjHteSlgVxRFMkgizWeFdd0dL34goekxCacnuv3TYSgJAyJS3pCKqUKoAi6nb0oGy6lSYFdISP+qszvL3dRQLaIzaKDLg9N216Bw4y+fiP2GUWkRh2HWEQV lighthouse@libertyits.com
```

- [Grant AWS Console access?]
  > YES 
  >  Required for support of vets-api and related projects as part of the Lighthouse contract

**Comment by lukemarkwordtlibertyits** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
For AWS:

User: Luke Markwordt
Approval: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
User created and first time login credentials provided
