### ISSUE TITLE
Uploading Files to 21-526EZ Disability Compensation Claim Form

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#9970]
## What happened?
Sometimes when uploading files to the 21-526EZ form, a `Network request failed` error is thrown. The issue seems to happen more frequently on mobile devices.

[Link](http://sentry.vfs.va.gov/vets-gov/website-production/issues/14738/?query=is%3Aunresolved%20logger%3Ajavascript) to Sentry issue.

**Comment by rianfowler** [comment]
appears to be happening a few hundred times a month but I'm not sure how many users that impacts.

**Comment by alexpappasoddball** [comment]
@thilton-oddball this one came through, we need to help identify the issue and traige as needed.  Let us know if you have any questions

**Comment by erluti** [comment]
So using [this event](http://sentry.vfs.va.gov/vets-gov/website-production/issues/14738/events/6861274/) as an example, I was unable to find a matching call in the logs to `https://api.va.gov/v0/upload_supporting_evidence`.  So one scenario is that there was an error trying to connect and it never reached vets-api.
Around that time I did find a request to `https://api.va.gov/v0/upload_supporting_evidence` around that time that took almost 2s (1990ms) to return an OK.  So another scenario might be the timeout isn't long enough?

**Comment by alexpappasoddball** [comment]
@erluti Is this still an ongoing issue?  @johnpaulashenfelter for visibility

**Comment by annaswims** [comment]
I'd suspect that [these backend errors](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/) are als0 related.

We try to send empty files to EVSS and get an error back.
`[{"key"=>"File Upload", "text"=>"Invalid file size:0", "severity"=>"ERROR"}]`

**Comment by annaswims** [comment]
possibly related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/13293

**Comment by annaswims** [comment]
I think this is happening because a user uploads a file that is too large and our reverse poxy rejects it.  but when the reverse proxy rejects it it lacks the `Access-Control-Allow-Origin` header.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/14427

**Comment by leahkeeler** [comment]
This sounds like it may be a feature to check file sizes and provide appropriate alert to end user over an actual bug

**Comment by alsleaders** [comment]
I'm closing this ticket because the feature to check file size of uploads seems to be working correctly.
