### ISSUE TITLE
STEM: Create Spool file entry for 10203 after submission

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9972]
As an EDU team member, I need 10203 submissions to be included in the spool file so that they can be loaded into TIMS and processed appropriately.

## Assumptions:
1. This work is done behind feature flag #7271.
2. When this work is completed, the generated spool file should be sent to the following individuals so that they can do a test run in TIMS to ensure that it loads properly.
   a. shay.norton-leonard@va.gov
   b. pierre.brown@va.gov

## Acceptance Criteria
1. The spool file is routed to buffalo RPO#307.
2. The spool file format matches SA1.
3. When populating the spool file data:
    a. If the applicant views a question and does not answer it, the corresponding spool file field answer is [blank].
    b. If the applicant does not view a question, the corresponding spool file field answer is: "N/A".
4. The spool file data for "Benefit" (which corresponds to Chapter 2: Which benefits have you used or are you currently using?) is populated in the following way:
    a. CH33 if selected
    b. If CH33 not selected, then display the first value selected. 

## Supporting Artifacts:
1. [10203_Spool_20200709_story_version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4899135/10203_Spool_20200709_story_version.docx)

**Comment by dmccurdybah** [comment]
Per standup discussion on 7/16/20, the answer to 'Auto Email Sent to SCO:' will be left blank.

**Comment by dmccurdybah** [comment]
SA1 includes double quotes in the body of the spool file template.  This isn't something done in other spool files because the generation process produces escaped double quote characters (`\"`) so I've replaced those instances with single quotes to match the existing spool files.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4535

**Comment by dmccurdybah** [comment]
vets-website PR (resolves submit issue): https://github.com/department-of-veterans-affairs/vets-website/pull/13513

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9707&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
