### ISSUE TITLE
PI Planning: Update GitHub Document to reflect the MVP approach

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#99737]
## Description
- To update the account creation API doc to reflect changes made to the MVP implementation plan for tool teams, and move it into the governance folder in GitHub. 

### User story

As a Cartography team member, I want to update the account creation API documentation, so that it aligns with the updated standardized alert plan approach that will be implemented by other teams. 

### Notes
- [Account Creation Alert Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/account-creation-api.md)

Possible tasks:
- [x] Move the document under the /governance folder in GH
- [x] Move details about asking tool teams to add the alerts in-place within their own apps to another section in the documentation (could refer to this as "future state")
- [x] Create new section for mvp approach that explains to teams that the initial iteration of this work will be for affected teams (MR, Meds, SM) to route-guard users who are missing an MHV-UUID to the /my-health landing page to see those alerts. 

## Acceptance criteria
- [x] The account creation API doc has been moved to the governance folder in GitHub (Mark: link up where this destination is)
- [x] The document has been updated to reflect the MVP approach (Mark: add link to the approach or ask Wes)
- [x] Updates have been peer-reviewed

**Comment by sterkenburgsara** [comment]
Update: @fmccaf1 took the first pass at this documentation on 12/30. It was peer-reviewed by me (Sara) on 12/31. @wesrowe bumped the file into the /governance folder & took a final pass at editing. Closing.
