### ISSUE TITLE
Request ForeSee Comment Card for Comparison Tool Landing Page

### ISSUE THREAD

**Issue by WillMcCormack** [department-of-veterans-affairs/va.gov-team#9973]
**Description:** The comparison tool landing page is the starting point for Veterans and their dependants to review and research their education benefits.
**Launch Date:** The landing page is already live on VA.gov so this would be an update to an existing product
**Staging URL:** https://staging.va.gov/gi-bill-comparison-tool/?version=a2db91fb-e403-40d3-aa7d-edef7e7879dc
**Production URL:** https://www.va.gov/gi-bill-comparison-tool/

**Comment by WillMcCormack** [comment]
Good morning, @joanneesteban following up on this request. Do you need any more information from us?

**Comment by joanneesteban** [comment]
Good morning, @WillMcCormack - thanks for bringing the ping. The `Feedback` button is in Staging. If you QA on your end, I can go ahead and add that to Production.

![image](https://user-images.githubusercontent.com/48964695/84791183-4a19ae00-afc0-11ea-9a17-4ba0c4f96d1c.png)

**Comment by WillMcCormack** [comment]
Thanks @joanneesteban I will reach out to the customer, have them validate, then circle back with you.

**Comment by WillMcCormack** [comment]
@joanneesteban we have confirmation from EDU that the changes look good on Staging. When you get a chance can you move the update into Production and let me know once it is live?

**Comment by joanneesteban** [comment]
@WillMcCormack The feedback button is live on Prod. Let me know if this works for you!

![image](https://user-images.githubusercontent.com/48964695/85073060-1db08e00-b188-11ea-87fe-89bfcc226ea7.png)

**Comment by WillMcCormack** [comment]
@joanneesteban thank you, looks great! I will let EDU know that it is live.
