### ISSUE TITLE
Update Standardized Alerts Documentation for to align with MVP 

### ISSUE THREAD

**Issue by mcarterA6** [department-of-veterans-affairs/va.gov-team#99740]
## Description

Update the standardized alerts documentation to reflect the update to Cartography team's approach for having tool teams implement the AC-API using route-guards instead of designing for putting error alerts in-place on their applications. 

### User story

As a Cartography team member, I want to update the standardized alerts documentation to align with the selected standardized alert implementation approach. 

### Notes
- [Alert Standardization Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/governance/alert-standardization.md)

Possible tasks:
- [x] Review the documentation & update guidance where it reflects the older approach instead of the new plan to have affected tool teams route-guard their applications to the /my-health landing page to see AC-API error alerts. 

## Acceptance criteria
- [x] The Standardized Alerts Document is updated to reflect the MVP approach. 
- [x] Updates have been peer-reviewed

**Comment by sterkenburgsara** [comment]
Update: Florence took a pass at this yesterday & I just peer-reviewed. This document only needed very minor changes. Closing.
