### ISSUE TITLE
Access for Larry Crochet

### ISSUE THREAD

**Issue by crolarlibertyva** [department-of-veterans-affairs/va.gov-team#9974]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Larry Crochet
- Please Provide your email.
   > larry.crochet@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API Development and Operations. Software Developer. Liberty IT Solutions.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4tyDdQp/8pQ0YWuB6ik0C1btJUsKkS/Z2/nZbKD9IBKFDB7/bU0nxrEzMo7qVkRN9hLiqJy02esaIFtyecvnH94J1pGa7Q/jPxF03jQFWquYsf4G82c9IZyqEZRiIk/d9KSvP9i+hlZ1JQ8eLYE5XQ4ftjMBf09LKAH1daMNfAVzFJgqGMfAJSBXHLHRpZr5xTZyHqZQMfOMIwlFnTMp6JGMV1m2aqxbklQgJIVb8eKwScBthWaTMo8FsU62keHqz5/HigXwjyVqv6yQrPE5oMlAZC8HuPyhqbMS/La1GKDNnOEr4/lPVzhb5QxDsfoBFwmmdm3XLyUm0iQUAO5OFP9AOuqnLkNzSXE+NvMKH0SbjoLVhzdE1bGTgVcbmiCUx+Oyeartj/IuPzIcGG5c7PTNXcRJxFNJl2HvtQ3jI38dOtS8amF0EUuhgTokFnE3teVRMFDBeD1l8TyU7Z6o1Zs0L611H7R1LkexW63Haf4QslVZ5POK2NtlTJHCQfKZhWQEZZ/8rDxBfBjWnaKr+kqhL15lM0skqYqoaJ4eE23vEdNzy+kbjOEerj323akjDR3CO0XlDQhf6UyigEvUC1T5l/oszVGgxCBHauyLPDCoIdvHxjqu6NaOBhJ7qnf/pnDzAo9atxCXrkhePCA2K5XCHUSDgsWPa1PDjtgmHiQ== larry.crochet@libertyits.com
```

- [Grant AWS Console access?]
  > YES
  >  Required for support of vets-api and related projects as part of the Lighthouse contract

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
For AWS Access:

User: Larry Crochet
Approval: @Jeff-Hayter

**Comment by crolarlibertyva** [comment]
Do I still have to wait or it should have connected?

```
$ ssh socks -D 2001
Last login: Tue Jun  9 17:07:39 2020 from ip-172-30-4-112.us-gov-west-1.compute.internal
 __          __     _____  _   _ _____ _   _  _____ _ 
 \ \        / /\   |  __ \| \ | |_   _| \ | |/ ____| |
  \ \  /\  / /  \  | |__) |  \| | | | |  \| | |  __| |
   \ \/  \/ / /\ \ |  _  /| . ` | | | | . ` | | |_ | |
    \  /\  / ____ \| | \ \| |\  |_| |_| |\  | |__| |_|
     \/  \/_/    \_\_|  \_\_| \_|_____|_| \_|\_____(_)

WARNING!

This U.S. government system is intended to be used by authorized VA network 
users for viewing and retrieving information only, except as otherwise 
explicitly authorized. VA information resides on and transmits through 
computer systems and networks funded by VA. All use is considered to be 
understanding and acceptance that there is no reasonable expectation of 
privacy for any data or transmissions on Government Intranet or Extranet 
(non-public) networks or systems. All transactions that occur on this system 
and all data transmitted through this system are subject to review and action 
including (but not limited to) monitoring, recording, retrieving, copying, 
auditing, inspecting, investigating, restricting access, blocking, tracking, 
disclosing to authorized personnel, or any other authorized actions by all 
authorized VA and law enforcement personnel. All use of this system 
constitutes the understanding and unconditional acceptance of these terms.

Unauthorized attempts or acts to either (1) access, upload, change, or delete 
information on this system, (2) modify this system, (3) deny access to this 
system, or (4) accrue resources for unauthorized use on this system are 
strictly prohibited. Such attempts or acts are subject to action that may 
result in criminal, civil, or administrative penalties.

This account is currently not available.
Connection to 172.31.2.171 closed.

```

**Comment by jbritt1** [comment]
Looks like you missed the `-N` part of the suggested command: `ssh socks -D 2001 -N &`. I recommend running `ssh socks -D 2001 -N` the very first time in order to get the prompt to allow the connection going forward. Once accepted, that will actually suspend your entire terminal and hold it open for the process. That is where the `&` comes in as that will background the process and not cause your terminal to be suspended by running it. So now that we have ran it once without the `&` command, accepted the connection, and exited the process (I use ctrl+c) we can run `ssh socks -D 2001 -N &`. From that we should only get a process ID returned as output and you should be able to continue with the guide for [testing SOCKS proxy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#test-and-use-the-socks-proxy).

**Comment by crolarlibertyva** [comment]
Thanks. I think I might be good afterall

`curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov
* Rebuilt URL to: sentry.vfs.va.gov/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* SOCKS5 communication to sentry.vfs.va.gov:80
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 2001 (#0)
> GET / HTTP/1.1
> Host: sentry.vfs.va.gov
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 FOUND
< Content-Language: en
< Content-Type: text/html; charset=utf-8
< Location: http://sentry.vfs.va.gov/auth/login/
< Set-Cookie: sentrysid="gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1jiiXL:XmcgYilEI3POBjkELPN_qOsOKsA"; expires=Tue, 23-Jun-2020 17:59:47 GMT; httponly; Max-Age=1209600; Path=/
< Vary: Accept-Language, Cookie
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Robots-Tag: noindex, nofollow
< X-XSS-Protection: 1; mode=block
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 127.0.0.1 left intact
`

**Comment by crolarlibertyva** [comment]
Curious where this stand?  Are AWS credentials gonna be made available to me?

**Comment by jbritt1** [comment]
Have you submitted an e-QIP?

**Comment by crolarlibertyva** [comment]
Yes, was already in the system and was informed that my security access was granted.  I've since been issued a PIV badge.

**Comment by jbritt1** [comment]
Roger, just need @Jeff-Hayter to confirm/approve.

**Comment by Jeff-Hayter** [comment]
@crolarlibertyva I've been trying to get a copy of your eQIP acceptance email or investigation status from Cecilia, but if you can forward I can expedite the approval.

**Comment by crolarlibertyva** [comment]
I can email that to you. Can you send me your email address?

**Comment by Jeff-Hayter** [comment]
@crolarlibertyva jeffrey.hayter@va.gov

**Comment by crolarlibertyva** [comment]
Sent.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
User created and first time login credentials provided
