### ISSUE TITLE
Request access to Google Analytics for Michelle S.

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#9975]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please link this issue to the DSVA Slack channel #vfs-platform-support, add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Production and non-production WBC content.

## Date Required
6/9/2020

## Product Team / External Team / VA Office
CTO / COVID-19 Screener

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @Yuffster-usds ,

May you provide for us your VA.gov email? 

Also, please note if your VA.gov email is not yet associated as a Google account, you will want to first do that [here ](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). 

Once you've got this done we can provision you Google Analytics access

**Comment by bmcgrady-ep** [comment]
Hi @Yuffster-usds ,

As @jonwehausen noted above, we can provide you Google Analytics access as soon as you provide us your VA.gov email and associate your active VA.gov email as a Google account.

Let us know when that is done and we will provide you access.

**Comment by joanneesteban** [comment]
@bmcgrady-ep moving to the backlog until @Yuffster-usds receives her va.gov email!

**Comment by jonwehausen** [comment]
Followed up with @Yuffster-usds via Slack...closing this until google account is created with .gov account.
