### ISSUE TITLE
508-defect-2 [AXE-CORE]: Heading levels SHOULD increase by one - within Learn more about the fiduciary program list item

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9987]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

There is an `h4` in the item under "Learn more about the fiduciary program', and there isn't an `h3` between it and the preceding `h2`. 

`<h4 class="va-nav-linkslist-title">Fiduciary and beneficiary programs</h4>`

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the hierarchy of the page content using heading levels to save time and frustration.

## Environment

- Operating System: all
- Browser: all
- Screenreading device: any
- Server destination: staging & production

## Steps to Recreate

1. Enter https://www.va.gov/decision-reviews/fiduciary-claims/ in browser
1. Run an axe scan
1. Verify 'Heading levels should only increase by one' is an issue found, associated with `<h4 class="va-nav-linkslist-title">Fiduciary and beneficiary programs</h4>`

### Current code
```diff
<section data-template="paragraphs/list_of_link_teasers" data-entity-id="8855" class="field_related_links">
-    <h2 id="learn-more-about-the-fiduciary-program" class="va-nav-linkslist-heading">
          Learn more about the fiduciary program
      </h2>
      <ul class="va-nav-linkslist-list">
        <li data-template="paragraphs/linkTeaser" data-entity-id="8854" data-links-list-header="Fiduciary and beneficiary programs" data-links-list-section-header="Learn more about the fiduciary program">
          <a href="https://www.benefits.va.gov/fiduciary/">
-           <h4 class="va-nav-linkslist-title">Fiduciary and beneficiary programs</h4>
        
            <p class="va-nav-linkslist-description">Learn about this program if you’d like to apply as a fiduciary for a family member or friend.</p>
    </a>
  </li>
</ul>
</section>
```

### Recommended code
```diff
<section data-template="paragraphs/list_of_link_teasers" data-entity-id="8855" class="field_related_links">
      <h2 id="learn-more-about-the-fiduciary-program" class="va-nav-linkslist-heading">
          Learn more about the fiduciary program
      </h2>
      <ul class="va-nav-linkslist-list">
        <li data-template="paragraphs/linkTeaser" data-entity-id="8854" data-links-list-header="Fiduciary and beneficiary programs" data-links-list-section-header="Learn more about the fiduciary program">
          <a href="https://www.benefits.va.gov/fiduciary/">
+           <h3 class="va-nav-linkslist-title vads-u-font-size--h4">Fiduciary and beneficiary programs</h3>
+ <!-- changed the h4 to an h3 and added the h4 utility class -->
            <p class="va-nav-linkslist-description">Learn about this program if you’d like to apply as a fiduciary for a family member or friend.</p>
    </a>
  </li>
</ul>
</section>
```

## WCAG or Vendor Guidance (optional)

* [axe-core 3.4 - Heading levels should only increase by one](https://dequeuniversity.com/rules/axe/3.4/heading-order)
* [MDN dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)
* [MDN ARIA: alert role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role)
* [MDN Description List element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)

## Screenshot

![Screen Shot 2020-06-09 at 2 26 28 PM](https://user-images.githubusercontent.com/57469/84185596-3e2c6a00-aa5d-11ea-9c40-dc379a664d5d.png)

**Comment by laflannery** [comment]
Heading levels no longer skipped, no issue reported in axe.  Will close in 1 week unless told otherwise
