### ISSUE TITLE
Analytics Implementation for CT: Estimate Your Benefits update

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#9991]
# Google Analytics Implementation  
    
> _Please see the following information for implementation timeline:_
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
 

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics implementation

- Who is this request for?
Booz Allen / VA.gov Education Service team
    - Will McCormack, Delivery Lead
    - Darrell Neel, Product Owner
    - Amy Knox, UX Lead
    - Dan Shawkey, Tech Lead
    - Desiree Turner, Scrum master
    - Matt Self, DEPO

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    - VA.gov Education / Comparison Tool
    
- Provide the Domain where Google Analytics needs to be implemented

    - https://staging.va.gov/gi-bill-comparison-tool/
    - https://www.va.gov/gi-bill-comparison-tool/
    
    - No PII is passed in the URL    

- Please provide any upcoming deadlines or important milestones
    
    - Launch target June 18, 2020

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    

      - School profile example: https://staging.va.gov/gi-bill-comparison-tool/profile/21015323
      - OJT profile example: https://staging.va.gov/gi-bill-comparison-tool/profile/30004020
      - VET TEC profile example: https://staging.va.gov/gi-bill-comparison-tool/profile/2V000125/JAVA%20FULL%20STACK%20SOFTWARE%20DEVELOPER
    
    - *Other User Interactions*: 
    
    - The interactions we're interested in tracking are
      - Accordion open / close on school and OJT profile pages 
      - "Update benefits" button click on all profile pages (school, OJT, VET TEC).  
      - Universal form control toggle tracking for all of the profile types according to the `gibct-form-change` taxonomy outlined in the DL requirements

- Sample Users when authentication is required  
    - [N/A - publicly available functionality]

- Test Users to replicate the event 
    - [N/A - publicly available functionality]

- Certain conditions/responses that need to be reviewed

    - Use "Type of institution" radio buttons on CT landing page to select school, OJT or VET TEC. controls  

- Additional Comments

    - N/A

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
### Notes from Review 
- Cleanup on a few `gibct-form-change` events
- Cleanup on `nav-section-collapse|expand`
- Cleanup on `nav-accordion-collapse|expand` 
- New event structure for 'update benefit clicks' 

@bsmartin-ep Begin drafting dataLayer requirements

**Comment by bsmartin-ep** [comment]
@amyknox -

I'm starting my review of this and wanted to let you know the accordion events on pages like https://staging.va.gov/gi-bill-comparison-tool/profile/35356632 are reversed.  When I expand an accordion, I get the `nav-accordion-collapse` event.

![image](https://user-images.githubusercontent.com/62304138/84420625-4ebd1b80-abe8-11ea-8eb7-430c7f34e3b3.png)

**Comment by bsmartin-ep** [comment]
@amyknox -

Would you consider buttons like _Update benefits_ to be 'Default buttons' in the [button component spec](https://design.va.gov/components/buttons)?

![image](https://user-images.githubusercontent.com/62304138/84499384-7cee3a00-ac80-11ea-912b-47ed3c0402b0.png)

**Comment by amyknox** [comment]
@bsmartin-ep - yes, I'd think so.  Curious if there's any reason you'd think it would not be?

**Comment by bsmartin-ep** [comment]
@amyknox - I didn't see the usual `usa-button` classes on the button, so wanted to double check.

**Comment by amyknox** [comment]
The "Update benefits" button is not a Primary button, a Secondary button, a Big button, nor a Deactivated button. So, all that's left **is** a Default button.

**Comment by bsmartin-ep** [comment]
## Data Layer Recommendations

Does this look like every interaction you want to track, @amyknox?

(cc @jonwehausen)

<table>
    <thead>
        <tr>
            <th>Description</th>
            <th>Screenshot</th>
            <th>Data Layer</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><em>Accordion open / close on school and OJT profile pages</em></td>
            <td><img src="https://user-images.githubusercontent.com/62304138/84799075-b8af3980-afc9-11ea-8649-445d9111f7d5.png" /></td>
            <td>
                <pre>
{
  'event': 'nav-accordion-expand'
}                     
                </pre>
                <pre>
{
  'event': 'nav-accordion-collapse
}                   
                </pre>
            </td>
        </tr>
        <tr>
            <td><em>"Update benefits" button click on all profile pages (school, OJT, VET TEC).</em></td>
            <td><img src="https://user-images.githubusercontent.com/62304138/84799133-cf559080-afc9-11ea-9862-a3f7cefe6d66.png" /></td>
            <td>
                <pre>
{
  'event': 'cta-default-button-click',
  'gibct-parent-accordion-section': 'Estimate your benefits'
  'gibct-child-accordion-section': 'Your military details'                    
}                   
                </pre>
            </td>
        </tr>
        <tr>
            <td><em>
                Use "Type of institution" radio buttons on CT landing page to select school, OJT or VET TEC. controls</em></td>
            <td><img src="https://user-images.githubusercontent.com/62304138/84799183-e5fbe780-afc9-11ea-976e-98ff5f9f6b79.png" /></td>
            <td>
                <pre>
{
  'event': 'gibct-form-change',
  'gibct-form-field': 'category',
  'gibct-form-value': 'Schools'                    
}              
                </pre>
            </td>
        </tr>
    </tbody>
</table>

**Comment by amyknox** [comment]
@bsmartin-ep - The first 2 items look right. The last one, I'm curious about... Is the type of institution on the landing page should be tracking, is it not?  Also, if this is supposed to be an exhaustive list of what we're tracking in the CT?  If so, I'd like to make a more thorough review.

**Comment by bsmartin-ep** [comment]
@amyknox -

re: number 3 - do you want to track EVERY radio button list and drop down list or just the _Type Of Institution_ radio button list?

**Comment by amyknox** [comment]
So your # 3 is focused on the landing page 
The updates we're making with the accordions and the new "Update benefits" button are on the profile page. I thought we were tracking pretty much all of the controls on the profile pages.

**Comment by bsmartin-ep** [comment]
> So your # 3 is focused on the landing page

Sorry - my first draft was accidentally specific to the _Type of Institution_ radio button list.  I updated to show the generic dataLayer object format for GIBCT form changes (which your team is familiar with).

> I thought we were tracking pretty much all of the controls on the profile pages.

It seems to be firing on some radio button and dropdown lists, but I'm not seeing it on certain ones...

![image](https://user-images.githubusercontent.com/62304138/84805370-252e3680-afd2-11ea-9dd3-016922578ace.png)

and

![image](https://user-images.githubusercontent.com/62304138/84805582-7a6a4800-afd2-11ea-9e6f-d0c9f363e247.png)

**Comment by jonwehausen** [comment]
Thank you @bsmartin-ep and @amyknox!

Yes - for #3, as Brian mentioned, we've noticed some of the dropdowns + radio buttons do not have the `gibct-form-change` event and `gibct-form-field` and `gibct-form-value` variables implemented. Here's an example for the 'How many terms per year' dropdown: 

![image](https://user-images.githubusercontent.com/48527022/84806574-e8633f00-afd3-11ea-8862-64f1fbdf6f1b.png)

To the right of the screenshot above identifies the "ID" Brian is referring to that devs seem to use in their identification of `'gibct-form-field'` .

@amyknox - **We would like to request the format identified in #3 [here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9991#issuecomment-644862214) be placed anywhere where this tracking does not currently exist. This is essentially for all 3 of the profile types**

**Comment by amyknox** [comment]
@jonwehausen & @bsmartin-ep - I get it! Please update the description of task 3 so it's clear it's ALL the rest of the controls that aren't currently tracked. LMK when it's updated and I'll pass it on to the Devs.  TY

**Comment by jonwehausen** [comment]
Thank you @amyknox ! No problem - I've update the description above to reflect that we want to universalize the `gibct-form-change` event taxonomy for any form controls across the 3 profiles were not yet implemented. 

We are officially ready to move forward with dataLayer implementation at your FE's availability.

**Comment by amyknox** [comment]
@jonwehausen & @bsmartin-ep - we're planning to tweak the language on #3 just a bit on our implementation story so the scope is clearer: 

Changing of drop-down list and radio button list values **within the Estimate your benefits area** on **all of the profile pages** of all types.

LMK if you have any questions or concerns.

**Comment by jonwehausen** [comment]
Excellent! We are on-the-same page with that scope.

**Comment by jonwehausen** [comment]
@amyknox, per our Slack conversation [here,](https://dsva.slack.com/archives/G015E14K8QM/p1592503004002400) we updated [our spec above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9991#issuecomment-644862214) with the additional `accordion-size` variable. 

As a dev note, please only include the value of `small` for the "mini" accordions.

**Comment by sonntag-adam** [comment]
[10353](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10353)

**Comment by jonwehausen** [comment]
Thank you @sonntag-adam we will QA as soon as we can!

**Comment by bmcgrady-ep** [comment]
Description of Interaction | Screenshot | Test Status
------------ | ------------- | -------------
mini accordion open | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/7b9eb685-4ddb-4a76-9ab2-ca55748e6835) | ✔️ **PASS**
mini accordion close | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/3fa6b121-3ae6-4e13-ba46-94c6a9e51153) | ✔️ **PASS**
"Update benefits" button non-VETTEC | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/4bd90241-09ef-45b0-a711-9c2c095431d1) | ✔️ **PASS**
radio button change | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/e14984d2-e515-42eb-aae5-d5c7aa710bc2) | ✔️ **PASS**
drop down list change | ![image.png](https://images.zenhubusercontent.com/5ed5304a223097003bc78534/d7e11f3c-a9eb-4ac3-8168-baca46c90a6d) | ✔️ **PASS**

**Comment by sonntag-adam** [comment]
@jonwehausen it looks like it passes the testing. Is that safe to say?

**Comment by jonwehausen** [comment]
Thank you @bmcgrady-ep for testing the DL! Very much appreciated. 

Yes @sonntag-adam thank you for your efforts here. I'll go through and get our tag management tested and deployed shortly thereafter.

**Comment by jonwehausen** [comment]
### Tag Management QA - WIP

Description | Screenshot | Status
------------ | ------------- | -------------
Clicked on 'update benefits' button within each of the mini accordions | ![image](https://user-images.githubusercontent.com/48527022/85893235-7d2e1f80-b7c0-11ea-8e99-ecd752163737.png) | ✔️ **PASS**

**Comment by amyknox** [comment]
@jonwehausen - have we completed this story, met all AC and are good to close? 
Looks like yes but we want to make sure we're on the same page.

**Comment by jonwehausen** [comment]
@amyknox Thank you for checking in, it's much appreciated -- we are are still in the process of doing test testing tags from Friday afternoon, planning on picking back up today and will confirm when we're ready to close 😄

**Comment by jonwehausen** [comment]
Hi @amyknox @desireeturner @sonntag-adam , 

Want to thank you again for your efforts here. From our QA, there is one item we would like to request a slight dataLayer adjustment -- apologies on our part for not confirming we would need earlier.

For the regular size accordions (non-minis), if we could include an `'accordion-size': undefined` push with the `nav-accordion-expand` and `nav-accordion-collapse` events that will help us better identify the small accordions vs the larger ones. 

Is that an item we could request of you @sonntag-adam ? Apologies again for not identifying during our first dataLayer testing / specifications. 

cc: @bsmartin-ep @bmcgrady-ep

**Comment by shawkey-daniel** [comment]
> Hi @amyknox @desireeturner @sonntag-adam ,
> 
> Want to thank you again for your efforts here. From our QA, there is one item we would like to request a slight dataLayer adjustment -- apologies on our part for not confirming we would need earlier.
> 
> For the regular size accordions (non-minis), if we could include an `'accordion-size': undefined` push with the `nav-accordion-expand` and `nav-accordion-collapse` events that will help us better identify the small accordions vs the larger ones.
> 
> Is that an item we could request of you @sonntag-adam ? Apologies again for not identifying during our first dataLayer testing / specifications.
> 
> cc: @bsmartin-ep @bmcgrady-ep

Could we define an accordion size for the non-mini accordions? We would prefer not to use undefined.

**Comment by jonwehausen** [comment]
Hi @shawkey-daniel , 

Sure, that is fine -- could we use `'accordion-size': 'full-content-width'? This will let us know the accordion spans the entire width of the body content. 

Thank you sir, we really appreciate it.

**Comment by jonwehausen** [comment]
Hey @shawkey-daniel , 

Want to thank you again for your efforts here. Should we be seeing this variable on the large accordion events at this point? Thanks again.

**Comment by shawkey-daniel** [comment]
@jonwehausen We will have to add that in later. I misunderstood where this was in progress.

**Comment by jonwehausen** [comment]
Hi @shawkey-daniel and @dneel-bah , 


I did a quick review of this tracking again this morning and there are some items we will want to correct. 

### GIBCT Form Change for Text Fields
- The dataLayer push seems to be happening on every keystroke, for example inputting 100 is pushing on `1`, `0`, `0`. **We will want to adjust this event listener to be on click away from the text field -- indicating the user has finished inputting their adjusted numbers**. See the example screenshot below firing 3 separate `gibct-form-change` events
![image](https://user-images.githubusercontent.com/48527022/87788595-99473e80-c80b-11ea-814f-2040a59c3a58.png)

**Comment by jonwehausen** [comment]
@dneel-bah @amyknox Closing this issue in place of bug-specific ticket for item outlined above.
