### ISSUE TITLE
Create a CMS export validation tool

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#9992]
## Issue Description
To estimate the remaining CMS export transformer work needed before that process can be used to build content for production, we need to know all the validation errors there are with the current content.

To this end, we need to build a tool which will:
1. Pull and untar the content from Drupal
2. Get a list of all the files
3. Filter out the ones we know we won't use (such as user.*)
4. Iterate over each remaining file to:
  a. Open the file
  b. Determine the content model type
  c. Validate the contents using the appropriate raw-data JSON schema
  d. Capture any error in a running list
5. Iterate over the list of errors to remove any duplicates
    - Because we only need to change the transformer once per content model type
    - This might be a little tricky, but I'm not especially worried about it
6. Display the results

Additionally, _all_ validation errors should be shown for a given data set. I'm not sure if this is possible right now using AJV, but there's no guarantee it will be a comprehensive view of all the errors unless we _show_ all the errors, not just one per JSON file.

### Lifespan of this tool
This tool is only intended to last until the drift between the current content model in Drupal and the transformers has been reconciled. Once the content build can successfully finish using the production content, this tool should be scrapped in favor of the validation in the CMS export transformation process.

**Comment by meganhkelley** [comment]
Hello @cvalarida who needs to validate that this is complete before we close?

**Comment by meganhkelley** [comment]
The point of this tool was to account for the drift between old transformers and the way things work now. That's been done.

Christopher Valarida  1 hour ago
What we're currently working on is accounting for the differences between the transformers and the GraphQL, which is a different beast.

Christopher Valarida  1 hour ago
It can be closed.
