### ISSUE TITLE
Discover: Post-mortem - how did this page get redirected?

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#9997]
## Discover: Post-mortem - how did this page get redirected?

Could you find out exactly how this got redirected? (Prior to our emergency undo.) 

Originally, we could not do the redirect, and informed Sandy of that: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6087#issuecomment-618028595 

At some point however - yesterday? - the claim exam was redirected without informing VBA. 

We will be discussing with Sandy and other VBA businesses how we can make this work better, and for the sake of transparency and to know for ourselves, I’d like to identify the steps to what happened. 

URLs in question: 
https://www.benefits.va.gov/compensation/claimexam.asp 

https://benefits.va.gov/compensation/add-dependents.asp

**Comment by kelsonic** [comment]
Do we need an estimate on this ticket @stephorkandatx?

**Comment by stephorkandatx** [comment]
@kelsonic yes please. I overlooked that!

**Comment by kelsonic** [comment]
@ncksllvn you think it was a 2? a 3? 🙂

**Comment by ncksllvn** [comment]
Add a 3 since it was a group effort
