### ISSUE TITLE
508-defect-2 [DOCUMENTS]: Documents MUST be 508 compliant

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#9998]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

On the ["Get help with your decision review request"](https://www.va.gov/decision-reviews/get-help-with-review-request/#content) page, there is a link to a PDF. 

1. The PDF **must** be accessible.
1. The PDF link **should** use the [Download PDF Link pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340) (the design.VA.gov documentation is in queue to be updated).

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

(I could use some help with the acceptance criteria. The PDF must be 508 compliant, and the link should communicate what will happen.)

* As an assistive tech user, I want documents to be accessible, so that I may access the content. 
* As a screen reader user, I want to know the context of a PDF download link so that I may make an informed decision regarding selecting the link.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: production: https://www.va.gov/decision-reviews/get-help-with-review-request/#content

## Steps to Recreate

1. Enter https://www.va.gov/decision-reviews/get-help-with-review-request/#content in browser
2. Start screenreading device listed in Environment
3. Navigate to the link "Find out more in the “How to Challenge a Fee” guide (PDF)", under the heading "What does it cost to use an accredited representative or a VSO?".
4. Verify that the screen reader only reads that it is a link and a PDF

## Possible Fixes (optional)

In addition to remediating the PDF, consider using the [Download PDF Link pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340).

```HTML
<a 
  href="https://www.va.gov/playbook/downloads/Voices_Of_Veterans.pdf" 
  download="Voices_Of_Veterans.pdf" 
  title="Download the Voices of Veterans PDF" 
  type="application/pdf">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
      Download the Voices of Veterans <dfn><abbr title="Portable Document Format">PDF</abbr> (4.9<abbr title="Megabytes">MB</abbr>)</dfn>
</a>
```

## WCAG or Vendor Guidance (optional)

* [W3C WCAG Link Purpose (In Context): Understanding SC 2.4.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html)

## Screenshots or Trace Logs

![Screen Shot 2020-06-09 at 6 14 38 PM](https://user-images.githubusercontent.com/57469/84206416-1a791c00-aa7d-11ea-9eea-bca9c681cb30.png)

![Screen Shot 2020-06-09 at 6 15 29 PM](https://user-images.githubusercontent.com/57469/84206486-3aa8db00-aa7d-11ea-99e7-6504be70ed20.png)

**Comment by jenstrickland** [comment]
@MickinSahni @brianalloyd This PDF is still not compliant. Might you find out who the business partner is? I can have the VA 508 Office reach out to them to remediate.

**Comment by joshkimux** [comment]
@coforma-terry looping in CAIA for support on closing out this ticket

**Comment by coforma-terry** [comment]
Thanks @joshkimux - Yeah, this falls right into Evan's wheelhouse :)

**Comment by laflannery** [comment]
@coforma-terry I have reviewed this and have 2 questions:
1. Do you know if anyone on the CAIA team has ever implemented a download PDF link within Drupal? I do not believe this is currently possible which is why I'm asking. I think this is blocked until Sitewide finds a way to do this but I want to be sure.
2. Is the owner of the PDF still outstanding and is that something that you all are able to follow up on? Or do you need assistance from me/my team?

**Comment by coforma-terry** [comment]
Hi @FranECross and @laflannery ! Sincere apologies for the delayed response on this, it dropped out of our pipeline for some reason!

Anyway - just wanted to check in as it looks like the PDF or the content surrounding it isn’t on the page anymore? Are you still looking for resolution on this? 
Thanks!

CC: @EvanAtCoforma @sara-amanda for visibility

**Comment by FranECross** [comment]
@coforma-terry No worries at all! I'm actually just cleaning out old tickets, and it sounds like I can close this as a no op since the PDF and content is no longer present. Thanks! cc @laflannery
